### ISSUE TITLE
Description Attribute in Elementor

### ISSUE THREAD

**Issue by francisvalverde** [elementor/elementor#10005]
Hi, (sorry for my english)
Do you know if it is possible to add an attribute description in elementor product page?

Thanks!

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
