### ISSUE TITLE
FB Like button language selector?

### ISSUE THREAD

**Issue by setupgr** [elementor/elementor#10010]
Hello,

I can't find a way to display in my web sites, using elementor the messages of FB "Like" button in any other languages.
My native language is already selected in WordPress options, but all the messages displayed in English. 

I think there should be a simple straight forward option (language selector) in the widget's options (or globally) to select the preferred language to be displayed.

Please advise if I miss an option to make it work.

p.s. : I don't need to use any language translation program like wpml. I just need my native language to be displayed in most of the cases.

**Comment by shilo-ey** [comment]
The like button locale is set by the WP language.

You can change the language of your WP site to adjust the like button.

Thanks

**Comment by lifeact** [comment]
Not working, lng site is uk -  https://i.imgur.com/OcbNNAc.jpeg   but like button en -  https://i.imgur.com/AGihtx6.jpeg
