### ISSUE TITLE
Blank space on mobile

### ISSUE THREAD

**Issue by Sandernijs** [elementor/elementor#10011]
How do i fix this blank space on the right side of my website? It can be very annoying when scrolling through the website.
I'm using elementor. 
It's just on the mobiel version. 
Thanks!

![IMG_1197](https://user-images.githubusercontent.com/59311475/71544215-83138700-297c-11ea-8768-49bb431194be.jpg)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
