### ISSUE TITLE
Creating New Widget Example Does Not Work

### ISSUE THREAD

**Issue by markolbert** [elementor/elementor#10016]
Following the instructions at https://developers.elementor.com/creating-a-new-widget/

I created the php file in /wp-content/plugins. The widget does not appear in the widget panel.

**Comment by shilo-ey** [comment]
Either create a proper plugin structure, including the plugin file starting with:
```PHP
<?php
   /*
   Plugin Name: YOUR PLUGIN NAME
   Plugin URI: http://YOUR-SITE.com
   description: plugin purpose
   Version: X.X
   Author: YOUR NAME
   Author URI: http://YOUR-SITE.com
   License: YOUR LICENSE
   */
?>
```


or simply add the code in your theme's `functions.php` file

thanks
