### ISSUE TITLE
Disable input field in forms prefilled with dynamic data

### ISSUE THREAD

**Issue by gedogarne** [elementor/elementor#10013]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Prefilled input tag values by dynamic data can be overwritten by the user as he fills out the form. By using this css: mouse-pointer: none !important; the click in the input field can be captured and blocked. While using tabbing in the form the user can still manipulate the input data (what he shall not do!)

**Describe the solution you'd like**
Having an additional property in elementor forms -> input field which may set the "disable" property of the input tag. This would make the prefilled value(s) secure and manipulation impossible.

**Describe alternatives you've considered**
CSS did not work out. Using the HTML method was not successful as I did not manage to grep the dynamic data beforehand and also had trouble by submitting the form. (Input value was not part of the $_POST array of data.)

**Additional context**
Would be a A+ to have this :)

**Comment by shilo-ey** [comment]
Hi @gedogarne 
Thanks for your feedback,

Elementor provides the solution for the common use of forms and allows it to be extendible by its users.

In your case, you can either use a hidden field, or alternatively you can set the field property to be disabled with simple JS:
```JS
document.getElementById("FIELD_ID").disabled = true;
```

Thanks
