### ISSUE TITLE
Unable to edit page after adding custom code 

### ISSUE THREAD

**Issue by Deepak-iBridge** [elementor/elementor#10012]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

we created a website using elementor and added products using woo-commerce.
we want to display products list and I wrote custom PHP script in functions and added it as a shortcode and included it in this page using elementor.
from then I'm getting an error whenever I tried to edit the page.

I have to keep this custom code across all the pages.

## Steps to reproduce

For your reference, I'm giving the custom code which I wrote is in https://pastebin.com/w4CfeZiP

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://my.elementor.com/index.php?gf-download=2019%2F12%2FSystem-Info.png&form-id=2&field-id=13&hash=8f4a042bfc550a5af0bc2da36e6404f56a5946bbe06b43d20bb2277b174bc470
</details>

## ERROR Screen

https://my.elementor.com/index.php?gf-download=2019%2F12%2FElementor-Error1.png&form-id=2&field-id=13&hash=e1402247861dd1293a202f7ef0c40218d43f166ad666c998fca161085426420f

**Comment by shilo-ey** [comment]
Hi @Deepak-iBridge 

It is unclear to understand what you are trying to achieve, but after quick look at your code, it seems like you're missing `wp_reset_query()` or `wp_reset_postdata()` after your custom loop.

Thanks
