### ISSUE TITLE
Missing Count field in Share Buttons Widget

### ISSUE THREAD

**Issue by jainnidhi** [elementor/elementor#10025]
I saw this video https://elementor.com/blog/pro-v130-share-buttons/ here and there is a count field in the Share buttons widget but currently I am using the Elementor Pro version 2.8.2 and there is a no count field in the Share buttons widget.

Has it been removed or am I doing something wrong?

Can you please help me out?

Thanks in advance!

**Comment by shilo-ey** [comment]
Hi @jainnidhi 

Thanks for your feedback.

Since Elementor Pro v2.6.0 we have removed donReach integration from Share Buttons widget due to service inconsistent stability (the 3rd party API was not available anymore)

Thanks

**Comment by jainnidhi** [comment]
Oh, thank you so much for your response. :)
