### ISSUE TITLE
remove h2 from template code not created by me

### ISSUE THREAD

**Issue by varonblu** [elementor/elementor#10022]
Hello, I observe in the code that many widgets and other elements are configured as H2, something that is not good for SEO, how do I change H2 for <p> or <div>?

I don't mean change the text widget and the header widget these widget is not the problem,

the problem is that in the template code the only H2 that have to be are the ones that I choose, the template does not have to put any more

In the video you can see the problem exactly.

https://www.loom.com/share/737ceb5c9d6f4ec68d572199e06d397a

**Comment by shilo-ey** [comment]
Hi @varonblu 

You can change the HTML tag heading level of each element placed in your page.

Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by varonblu** [comment]
** Prerequisites: **
I have looked for similar problems in open and closed tickets and I cannot find the same problem that I raise.
** ## Description **
I have many H2 headers in the web code that I cannot control, I need to remove all H2 headers that do not belong to any widget from the code:
Example of the problem, in this URL [https://www.ruthmontenegro.com/tarot-si-o-no/[(url) in the code you can see the H2 that correspond to the headers put by me but also you can See others that I have not put.
<h2 class="media-frame-menu-heading">Acciones</h2>
<h2 class="media-frame-actions-heading screen-reader-text">
  | Acciones de los medios seleccionados</h2>
<h2 class="upload-message">{{ data.message }}</h2>
<h2 class="upload-instructions drop-instructions">Arrastra los archivos para subirlos</h2>
<h2>Subiendo</h2>
<h2 class="screen-reader-text">Vista previa del adjunto</h2>
<h2 class="screen-reader-text">Detalles</h2>
<h2>
  | Detalles del adjunto			<span class="settings-save-status" role="status">
  | <span class="spinner"></span>
  | <span class="saved">Guardado.</span>
  | </span>
  | </h2>
<h2>Ajustes de visualización de adjuntos</h2>
<h2>Ajustes de la galería</h2>
<h2>Ajustes de la lista de reproducción</h2>
<h2><button type="button" class="button-link advanced-toggle">Opciones avanzadas</button></h2>
***************************
This is an example of the headings that appear in the code and over which I have no control.

The query is clear, as I delete the headers that I have not put from all the web, I attach a video where you can see these H2 headers.
https://www.loom.com/share/7d946a5ab56b456cae94fa5a09c76676

I hope I have done the consultation correctly now and that you can help me
