### ISSUE TITLE
Result count select not translating to target language

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#10026]
Hi, I'm using Farsi language of woocommerce, but some parts of elementor widgets not showing correct language, I checked translation files, they are OK, also tried to find where elementor calls
woocommerce_result_count but could not find it, 

any idea how can I fix this issue? 

![image](https://user-images.githubusercontent.com/2544046/71583099-120bd500-2b1e-11ea-8029-5dfc45b37e33.png)

![image](https://user-images.githubusercontent.com/2544046/71583218-85ade200-2b1e-11ea-851b-37b0f9d4fb6c.png)

**Comment by shilo-ey** [comment]
Hi @amindiary 

Have you tried translating the strings in WooCommerce as well? 

It seems like this string is not being set from Elementor but from WC

Thanks

**Comment by amindiary** [comment]
> Hi @amindiary
> 
> Have you tried translating the strings in WooCommerce as well?
> 
> It seems like this string is not being set from Elementor but from WC
> 
> Thanks

Yes, I investigated files, it's WC issue not Elementor, changed it in WooCommerce core file (template file not works too)  Thanks for attention.
