### ISSUE TITLE
XML exporting/importing

### ISSUE THREAD

**Issue by helvetica123** [elementor/elementor#10035]
Hello, I want to export all things of my design such as customizes, widgets and of course posts.But native XML importing/exporting doesnt work me for posts made by Elementor plugin.It is too important to me because I want to sell my design and I cant do anything in this stage so I wait your solution suggestions.Thank you.

**Comment by a-camacho** [comment]
Hi guys, I have the same issue (that should have been fixed before)
Importing website content.xml does not import elementor data. So everything transforms into a weird classic WP post.

Do you have any clue about that ?

**Comment by helvetica123** [comment]
> Hi guys, I have the same issue (that should have been fixed before)
> Importing website content.xml does not import elementor data. So everything transforms into a weird classic WP post.
> 
> Do you have any clue about that ?

Hi, now my problem is solved.The problem was I didnt install all plugins before import elementor data.Now, I use native wordpress exporter.May your problem is same with mine so check your plugins are installed or not then import the data.I hope your problem will be solved

**Comment by a-camacho** [comment]
Hello,

I have Elementor and Elementor Pro activated when exporting or importing the content.
So I don't think the issue comes from here.

Anyone has any clue ?

**Comment by arielk** [comment]
Merge to https://github.com/elementor/elementor/issues/12340
