### ISSUE TITLE
Text shadows policy

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#10033]
## Description

Inconsistent use of **Text Shadow** controls in Elementor widgets. Some widgets use text shadow, others don't. There should be a consistency or a general policy.

The current policy - when there is text in a widget, there should be a **Typography** control which helps the user design the text.

My proposal - all **Typography** controls should be followed by **Text Shadow** control to allow the user add shadows to the widget text.

![text-shadows](https://user-images.githubusercontent.com/576623/71624721-a8a6c780-2bec-11ea-9320-b77e09556b8c.png)

## Widgets

Widget | Typography | Text Shadow | Notes
-------|------------|-------------|-------
Inner Columns | ❌ | ❌ | -
Heading | 👍🏻 | 👍🏻 | -
Image | 👍🏻 | 👍🏻 | (Under Caption)
Text Editor | 👍🏻 | ❌ | Should be added to Text & Drop Cap
Video | ❌ | ❌ | -
Button | 👍🏻 | 👍🏻 | -
Divider | ❌ | ❌ | -
Spacer | ❌ | ❌ | -
Google Maps | ❌ | ❌ | -
Icon | ❌ | ❌ | -
Image Box | 👍🏻 | ❌ | Should be added to Title & Description
Icon Box | 👍🏻 | ❌ | Should be added to Title & Description
Star Rating | 👍🏻 | ❌ | Should be added to Title
Image Carousel | 👍🏻 | ❌ | Should be added to Caption
Image Gallery | 👍🏻 | ❌ | Should be added to Caption
Icon List | 👍🏻 | ❌ | Should be added to Text
Counter | 👍🏻 | ❌ | Should be added to Number & Title
Progress Bar | 👍🏻 | ❌ | Should be added to Inner Text & Text Style
Testimonials | 👍🏻 | ❌ | Should be added to Counter & Name & Title
Tabs | 👍🏻 | ❌ | Should be added to Title & Content
Accordion | 👍🏻 | ❌ | Should be added to Title & Content
Toggle | 👍🏻 | ❌ | Should be added to Title & Content
Alert | 👍🏻 | ❌ | Should be added to Title & Description
Social Icons | ❌ | ❌ | -
SoundCloud | ❌ | ❌ | -
Shortcode | ❌ | ❌ | -
HTML | ❌ | ❌ | -
Menu Anchor | ❌ | ❌ | -
Sidebar | ❌ | ❌ | -
Read More | ❌ | ❌ | -

We need to add 25 new text-shadow controls.

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!
