### ISSUE TITLE
Help, how to change HTLM code from product liste  "no follow" attribute

### ISSUE THREAD

**Issue by vessiere** [elementor/elementor#10032]
Hi !

I need you help, for my page : https://www.mv-bracelet.com/mirabelle-de-lorraine/
In the first part, we offer two products recommendation. 

However, there is a mistake in the HTLM code for SEO. As you can see, in the last product, we have the attribute « No follow » (in black) that we want to delete.
How can we change it ? 

Many thanks,
<img width="897" alt="Capture d’écran 2019-12-31 à 13 40 57" src="https://user-images.githubusercontent.com/59392402/71621987-3b3a6d00-2bd3-11ea-9685-4c432553823a.png">

**Comment by shilo-ey** [comment]
Hi @vessiere 

This is not an Elementor related issue, but you can use the `woocommerce_loop_add_to_cart_args` to unset the `rel` attribute.

```PHP
// Remove rel=nofollow from add to cart button
add_filter( 'woocommerce_loop_add_to_cart_args', 'remove_rel', 10, 2 );
function remove_rel( $args, $product ) {
    unset( $args['attributes']['rel'] );

    return $args;
}```

Thanks
