### ISSUE TITLE
🔗 🔃 🚀 Feature Request: editing google maps (Merged with #1319) (Related to #626)

### ISSUE THREAD

**Issue by Anthonywp** [elementor/elementor#1003]
Hi team, 

I see that it is super easy to add a google maps widget using elementor but I was hoping that you'd add more function in the way of:

Changing the colour of the map
Changing the colour of the elements i.e the pins
Changing the map views i.e Satellite, terrain, basic

and so on.

This would make the google maps widget a lot more powerfult and customizable.

Thank you

**Comment by kadoogan55** [comment]
I support this feature idea - or at least have them able to be styled by snazzy maps. Also, being able to add personalized pin graphics.

**Comment by arielk** [comment]
Thank you for your feedback!

I merged this issue with another issue #626 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.

**Comment by joshallen73** [comment]
I was just googling this very issue, Maps are used on most all sites so there should be alot of customization options -I agree with above -very lacking
