### ISSUE TITLE
 go to dashboard

### ISSUE THREAD

**Issue by lwoods** [elementor/elementor#10045]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lwoods** [comment]
Trivial addition:  Add a "Go To Dashboard" button at the bottom of the page menu items.  Saves an extra click/select just to get out of development mode back to the Dashboard.

**Comment by DorShahar** [comment]
Hi, 
Thanks for reaching out. You are able to do this and more operations using the Finder. 
Just click `CMD + E` and write "dash".

You can learn more [here](https://elementor.com/help/the-finder/).

Thanks
