### ISSUE TITLE
Dropdown panel not visible when Mobile Dropdown breakpoint set to NONE

### ISSUE THREAD

**Issue by oooh-boi** [elementor/elementor#10043]
Is that a bug or else?
When the "Nav Menu" widget Breakpoint option is set to NONE, it's not possible to style up drop-down menus because there's no "Dropdown" panel visible anymore.

That doesn't make any sense because the drop-down menus should still be visible and functional regardless of the breakpoint!
Am I missing the point here?

![no-drop-down-panel](https://user-images.githubusercontent.com/51370907/71665766-61d8df00-2d5e-11ea-839c-dbfb8c715c80.png)

**Comment by shilo-ey** [comment]
The breakpoint is not a responsive control. It applies to the entire responsive breakpoints.

When you set Mobile Breakpoint to None, the dropdown is not active, hence you cannot style it.

Thanks

**Comment by oooh-boi** [comment]
That doesn't make any sense...
You just wrote that drop-downs won't work if the mobile breakpoint is set to none which is not true coz they work perfectly fine. 
If the Breakpoint is NOT a responsive control with Nav Menu widget then how do you name the "responsive controls" in Elementor?

Please don't just shut the issue! 
What's wrong with enabling Dropdown panel if Breakpoint is set to NONE? Is there any tech problem with that option?
What if I want to create my own Mobile version of the menu as a popup and show/hide these two via Responsive panel?

**Comment by shilo-ey** [comment]
Breakpoint set to none, is the same as hiding the menu toggle.
This is what it was made for.

**Comment by oooh-boi** [comment]
Great, that's exactly what one might want, to get rid of the menu toggle button! Agreed 100%!
But it doesn't make any sense to disable styling up of the drop-down menus. There's no relation between the toggle button and drop-downs.
