### ISSUE TITLE
Inconsistent Minimum WP Versions for Elementor 2.8 Free & PRO

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#10049]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor 2.8.x has raised it's minimum WP version to 5.0. When I'm on older version of WP, I don't get any update notice (even if on E2.6). That's fine and legitimate behavior.

On the other hand it seems, the PRO versions 2.8.x don't have this minimum requirement. Thus, I can see a promt for updating the PRO, but not for the Free. And when I do update the PRO, without updating the Free, I got a notice, that Elementor is obsolete and I should update it. This is not good behavior.

## Steps to reproduce
As said above - try to update Elementor Free & Pro on WP < 5.0.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
Hi @black-eye 

Thanks for your feedback,

This issue was fixed. 

Thanks
