### ISSUE TITLE
Add option for icon and/or (background) image in nav menu items

### ISSUE THREAD

**Issue by kneops** [elementor/elementor#10042]
I would very much like to see an option to add an icon next/above/beneath a menu item and/or option to add a background image to a menu item. Now you can only add underline or something, not even a menu item seperator. 

This way menus can be made much more attractive and looking the same as the rest of the website design. For instance in the screenshot I added a small custom shape underneath a menu item as a background image, but it could also be a small icons next to the menu item name, like an envelope, user group, home symbol etc.

![background image underneath menu item](https://user-images.githubusercontent.com/7037787/71660723-406ef780-2d4c-11ea-9c25-d88ef78a5419.jpg)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
