### ISSUE TITLE
Displaying naviagtion menu as active when viewing post

### ISSUE THREAD

**Issue by EnzoTheBaker** [elementor/elementor#10054]
Hi there

I've figured out most of what I need but have stumbled at the final hurdle!

I am looking to set the appropriate navigation menu as active when viewing posts, not just pages.

I have found a php snippet that allows me to assign this via category and have got it working:

https://www.staging1.luxuremagazine.com/queens-plate/

The link above is a post that has been appears under the 'Social Calendar' section.

As you can see, I am able to target the background of the navigation element, but I cannot target the text/label or the pointer. If you hover over any navigation element, the text and the bottom pointer turn red - and I would like to set that as the active state.

I've identified an e--pointer id but I cannot correctly target it.

Hope you can help

This is the code I've added to the functions.php of my child theme:

//Highlight navigation menu when viewing a post
function mark_menu_item_as_active($classes, $item) {
$category_menuitem_mappings = array();

/* !!! This needs to be customized !!! */
$category_menuitem_mappings['social-calendar'] = 'menu-item-1340';
$category_menuitem_mappings['resources'] = 'menu-item-23';

global $post;
$category_obj = get_the_category($post->ID);
$category_str = $category_obj[0]->slug;

foreach ($category_menuitem_mappings as $key => $value) {
if (in_array($value, $classes) && $category_str === $key) {
$classes[] = 'elementor-nav-menu--main current-menu-item';
}
}

return $classes;
}
add_filter('nav_menu_css_class', 'mark_menu_item_as_active', 10, 2);

***

And this is the custom CSS I am using to apply the background colour:

.elementor-nav-menu--main .current-menu-item {
background-color: #d38928;
}

**Comment by shilo-ey** [comment]
Hi @EnzoTheBaker 

Thanks for your feedback

Elementor uses the WordPress native `wp_nav_menu`, so you can use the hooks and filters provided to add classes as needed and then highlight the items as you wish.


thanks.
