### ISSUE TITLE
No result found on Author tab

### ISSUE THREAD

**Issue by helvetica123** [elementor/elementor#10059]
===== Guidelines ====

I want to display posts by spesific author.To this, I wrote a code.However, in author tab shows "No results found" so I cant select any author.

-->

## Prerequisites

 The issue still exists against the latest stable version of Elementor.

## Description
Widget code:

```
  $this->add_control(
            'authors', [
                'label' => __('Author', 'plugin-name'),
                'label_block' => true,
                'type' => Controls_Manager::SELECT2,
                'multiple' => true,
                'default' => [],
                'options' =>

            get_users([
                //'who' => 'authors',
                'has_published_posts' => true,
                'fields' => [
                    'ID',
                    'display_name',


                    'show_in_nav_menus' => true

                ],
            ]),


            ]
        );

        $this->end_controls_section();
```

## Steps to reproduce

I select the selection tab and it says no results.

**Comment by shilo-ey** [comment]
Please create a new detailed issue and paste the full code of what you're trying to achieve and not just a control. 
The query cannot be placed inside the control, I suggest you either use our Query Control (or even using Posts widget with Author query) or see what we do in widgets uses the Query Control (Posts, Portfolio, Sitemap, Products etc.)

Thanks
