### ISSUE TITLE
small bug: readability issue in darkmode in dynamic fields

### ISSUE THREAD

**Issue by slwirth** [elementor/elementor#10057]
## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: FreeBSD
	Software: Apache
	MySQL version: FreeBSD Ports v5.6.45-86.1
	PHP Version: 7.3.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://emergent.ch
	Home URL: https://emergent.ch
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.2.0
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

== Active Plugins ==
	ACF Cleaner
		Version: 1.4.2
		Author: 1n3JgKl9pQ6cUMrW

	Admin Menu Editor
		Version: 1.9.3
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 5.8.7
		Author: Elliot Condon

	ARI Adminer
		Version: 1.2.3
		Author: ARI Soft

	Custom Post Type UI
		Version: 1.7.1
		Author: WebDevStudios

	Duplicate Page
		Version: 4.0
		Author: mndpsingh287

	DynamicConditions
		Version: 1.4.1
		Author: RTO GmbH

	Edit Author Slug
		Version: 1.6.1
		Author: Brandon Allen

	Ele Custom Skin
		Version: 1.3.9
		Author: Dudaster.com

	Elementor
		Version: 2.8.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Element Pack
		Version: 4.3.0
		Author: BdThemes

	Elements Plus!
		Version: 2.10.2
		Author: The CSSIgniter Team

	Media Library Assistant
		Version: 2.81
		Author: David Lingren

	Members
		Version: 2.2.0
		Author: Justin Tadlock

	Safe SVG
		Version: 1.9.7
		Author: Daryll Doyle

	ShortPixel Image Optimizer
		Version: 4.15.3
		Author: ShortPixel

	Simple History
		Version: 2.33
		Author: Pär Thernström

	Site Kit by Google
		Version: 1.1.4
		Author: Google

	Toolbar Extras
		Version: 1.4.9
		Author: David Decker - DECKERWEB

	UpdraftPlus - Backup/Restore
		Version: 2.16.21.1
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.4.2
		Author: Wordfence

	WPML Media
		Version: 2.5.5
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.3.6
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.0.6
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.9.4
		Author: OnTheGoSystems

	WPS Hide Login
		Version: 1.5.4.2
		Author: WPServeur, NicolasKulka, tabrisrp

	Yoast SEO
		Version: 12.7.1
		Author: Team Yoast

	Yoast SEO Multilingual
		Version: 1.0.3
		Author: OnTheGoSystems

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 2
		button : 2
		global : 1
		heading : 5
		image : 1
		posts : 1
		text-editor : 1
	footer : 2
		form : 2
		heading : 3
		image : 2
		nav-menu : 1
		social-icons : 2
		text-editor : 5
	header : 3
		icon-list : 1
		image : 1
		nav-menu : 1
		social-icons : 1
	loop : 3
		button : 1
		divider : 1
		post-info : 2
		theme-post-featured-image : 1
		theme-post-title : 1
	section : 4
		heading : 12
		image : 9
		posts : 1
		search-form : 1
		text-editor : 9
	single : 4
		button : 4
		heading : 4
		icon : 1
		image : 1
		post-info : 1
		post-navigation : 4
		text-editor : 17
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-post : 2
		button : 5
		flip-box : 11
		form : 1
		google_maps : 1
		heading : 51
		icon : 4
		image : 19
		image-box : 2
		image-carousel : 1
		menu-anchor : 3
		posts : 1
		text-editor : 46
	wp-page : 10
		bdt-post-gallery : 1
		button : 6
		call-to-action : 1
		global : 1
		heading : 43
		icon : 1
		icon-box : 4
		icon-list : 1
		image : 19
		image-box : 1
		image-gallery : 1
		media-carousel : 2
		menu-anchor : 9
		posts : 1
		text-editor : 34

== Log ==
	
Log: showing 20 of 242019-09-11 15:44:31 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-11 15:44:31 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-11 15:44:34 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-11 15:44:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.1',
)]
2019-09-20 12:25:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.1',
  'to' => '2.7.2',
)]
2019-10-17 10:13:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.2',
  'to' => '2.7.4',
)]
2019-10-29 10:58:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-11-24 12:52:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.5',
  'to' => '2.7.3',
)]
2019-12-09 07:57:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.7.6',
)]
2019-12-10 11:06:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.6',
  'to' => '2.8.0',
)]
2019-12-12 10:43:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0',
  'to' => '2.8.1',
)]
2019-12-17 08:27:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2019-12-19 17:16:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.1',
)]
2019-12-24 12:22:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2020-01-04 09:29:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-04 09:29:10 [info] elementor::elementor_updater Started 
2020-01-04 09:29:10 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-04 09:29:13 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-04 09:29:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-04 09:30:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]

PHP: showing 11 of 11PHP: 2019-10-08 12:26:19 [notice X 1][/home/wirthsan/www/impact.strategos.ch/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-17 10:13:15 [warning X 1][/home/wirthsan/www/leadership.strategos.ch/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/home/wirthsan/www/leadership.strategos.ch/wp-content/uploads/elementor/css/post-60.css) [<a href='https://secure.php.net/manual/en/function.unlink.php'>function.unlink.php</a>]: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-24 13:35:44 [warning X 1][/home/wirthsan/www/leadership.strategos.ch/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(logo-2.svg) [<a href='https://secure.php.net/manual/en/function.unlink.php'>function.unlink.php</a>]: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-27 11:34:08 [notice X 3][/home/wirthsan/www/communication.strategos.ch/wp-content/plugins/elementor/includes/elements/column.php::1002] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-29 10:58:50 [warning X 1][/home/wirthsan/www/communication.strategos.ch/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/home/wirthsan/www/communication.strategos.ch/wp-content/uploads/elementor/css/post-60.css) [<a href='https://secure.php.net/manual/en/function.unlink.php'>function.unlink.php</a>]: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-01 10:53:14 [warning X 3][/home/wirthsan/www/communication.strategos.ch/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::120] file_get_contents() [<a href='https://secure.php.net/manual/en/function.file-get-contents.php'>function.file-get-contents.php</a>]: Filename cannot be empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-13 17:59:59 [notice X 2][/home/wirthsan/www/emergent.ch/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-21 11:23:50 [notice X 1][/home/wirthsan/www/emergent.ch/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-21 15:33:42 [notice X 1][/home/wirthsan/www/emergent.ch/wp-content/plugins/elementor-pro/modules/query-control/module.php::290] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-21 16:34:08 [notice X 8][/home/wirthsan/www/emergent.ch/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-custom-field.php::62] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-24 22:44:40 [notice X 4][/home/wirthsan/www/emergent.ch/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::56] Undefined index: return_format [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2019-10-17 11:56:56 [error X 1][https://leadership.strategos.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:7:20237] this.ui.sliders.filter(...)[0] is undefined 
JS: 2019-10-29 11:34:36 [error X 2][https://communication.strategos.ch/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.4:2:39895] n.attributes[e.name].each is not a function 
JS: 2019-10-31 15:47:16 [error X 1][https://communication.strategos.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:7:49496] i is undefined 
JS: 2019-11-13 15:05:17 [error X 6][https://emergent.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:2:46135] this.ui.select is undefined 
JS: 2019-11-14 07:23:56 [error X 8][https://emergent.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:138844] elementorFrontend.elements.window.jQuery is not a function 
JS: 2019-11-14 07:23:56 [error X 20][https://emergent.ch/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.5:2:0]  
JS: 2019-12-08 16:00:52 [error X 1][https://emergent.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:36780] n is undefined 
JS: 2019-12-20 10:07:27 [error X 1][https://emergent.ch/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.8.2:2:156845] this.storage is undefined 

</details>

![image](https://user-images.githubusercontent.com/40966578/71763913-1d764c00-2ee2-11ea-9a31-59e3344b7cc2.png)

**Comment by shilo-ey** [comment]
Hi @slwirth 

Thanks for your feedback.

Please make sure that you're up to date with the latest version (2.8.3).

We couldn't reproduce your issue:
 
![image](https://user-images.githubusercontent.com/45009641/71778254-27687f80-2fb4-11ea-9901-f9763da9c9ec.png)

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by slwirth** [comment]
I am using Elementor Pro 2.8.3. as you can see above. 
I am using FF 71.0 (64-bit).
Best,
Sandra
