### ISSUE TITLE
Text Padding field is not working in share buttons widget

### ISSUE THREAD

**Issue by jainnidhi** [elementor/elementor#10050]
Hello,

I am using 2.8.2 Elementor Pro version.

I am using your share buttons widget and trying to change the text padding but the field is not working.

This is selector for text padding field `{{WRAPPER}} a.elementor-button` but there is no anchor tag output on frontend.

Can you please help me out?

Thanks in advance!

**Comment by jainnidhi** [comment]
Hello team,
what about my this issue?

**Comment by lior-sh** [comment]
Hi @jainnidhi,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
