### ISSUE TITLE
Elementor table of contents and SEO improvement

### ISSUE THREAD

**Issue by marcrevenga** [elementor/elementor#10052]
## Prerequisites
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

When I put the elementor TOC (table of contents) in a page, the generated HTMl is:

`<div class="elementor-toc__list-item-text-wrapper"><a href="#elementor-toc__heading-anchor-0" class="elementor-toc__list-item-text elementor-toc__top-level elementor-item-active">Some H2 text</a></div>`

The problem is that "#elementor-toc__heading-anchor-0" is indexed by Google Search Engine. Is an ugly URL and does not help for SEO. Other TOC plugins sets the anchor text same as H2 label replacing spaces " " with underscores "_".

For example, I see I have indexed this URL in search console:

https://XXXX.com/YYYYYYY/#elementor-toc__heading-anchor-3

I think it can be a good improvement for the TOC in elementor. Or, if you want, a personalized one.

## Steps to reproduce

Simply insert elementor table of contents in a page with multiple H2 and add them to the TOC in its configuration

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
wordpress: 5.3.2 - Free and Pro Elementor plugins:  both 2.8.3
</details>

**Comment by 08ryanpietrzak** [comment]
This is causing me so much frustration.

this has been open for almost a month and no response??

**Comment by Nachdenker** [comment]
I have the same issue.

I love the TOC widget, because it is easy to use.
But the downside is, that it is lacking SEO support.
This is important, because it should increase the pages
ability to rank. Without it... there is a much smaller Chance.

Maybe the developer can include 'something', so that it makes
the TOC widget more SEO friendly; as other parts are fine. 

PS: I am convinced, they work on this and find a suitable solution - fast. ,)

**Comment by stephenjpeg** [comment]
I also have this issue, it seems like an easy fix. I only joined just to voice my support for it

**Comment by matuskopalko** [comment]
Experiencing the same issue, Somebody should write us back to let us know, as the Elementor support fella couldn't provide more info. Thanks !

**Comment by Nachdenker** [comment]
In the End and with regards to SEO the frontend-code should look something like this:

**Jump Link Giving:**

`<a href="#chapter-3" title="Chapter 3">Chapter 3</a>`

**Jump Link Receiving:**

`<h2 id="chapter-3">Chapter 3 - How...</h2>`

**Comment by shilo-ey** [comment]
What do you think should be the `id` when there are identical titles in the page?

for example:
- Heading 1
-- Summary
-- Example
- Heading 2
-- Summary
-- Example

What would you expect to see there?

**Comment by Nachdenker** [comment]
Hello @shilo-ey ,

well, an ID should be an unique identifier, BUT
if there are duplicated Elements within a TOC, then I would go for this...

I would want to be able, to edit an 'id' in the backend without the need
to change names in the Frontend.

OK, an example is needed; I guess. ;)

- Heading 1
- -- Summary
- -- Example
- Heading 2
- -- Summary
- -- Example

**This would be the result with "identical ID's":**
```
<h1 id="heading-one">Heading Number 1</h1>
<h3 id="summary">Summary</h3>
<h3 id="example">Example</h3>
<h2 id="heading-two">Heading Number 2</h2>
<h3 id="summary">Summary</h3>
<h3 id="example">Example</h3>
```

You are right, that this structure isn't SEO-friendly / User-friendly 
and **the better Version could look like THIS:**

```
<h1 id="heading-one">Heading Number 1</h1>
<h3 id="chapter-one-summary">Summary</h3>
<h3 id="chapter-one-example">Example</h3>
<h2 id="heading-two">Heading Number 2</h2>
<h3 id="chapter-two-summary">Summary</h3>
<h3 id="chapter-two-example">Example</h3>
```

So the 'frontend's Element name' stays the same, but 
because we were able to edit the identifier (id) itself in the backend,
we can change things and adjust the TOC to our needs.

I don't know, if you could automize this process, but **I** like to have
control and tweak where it is necessary. 

PS: And it should be possible, to simultaneously edit the ID
of the source and the goals-element.

**Meaning:**
When we change the ID of an TOC-Element it should also
change the given ID of the specified Heading. So we need to 
be able to edit the ID's of every TOC-Element - when needed - 
to adjust Single-Elements of the TOC.

**Comment by kapachon** [comment]
Hi!
Have the same issue, hope you can solve this problem, the support team can't help me and I'm considering removing the widget.

**Comment by kapachon** [comment]
Hi there
can you please update about this issue? its very frustrating and annoying

**Comment by black-eye** [comment]
+1

**Comment by marwis93** [comment]
+1

**Comment by ryantan71** [comment]
It has been 5 month, how come it has still not been fixed??!!!

**Comment by Nachdenker** [comment]
@ryantan71  I know, how you feel.

So far I've been patient, but my patience is slowly breaking. Other pagebuilders seem to respond faster. So far I've liked Elementor, but if it takes longer, I have to look for alternatives in the professional field.

**Comment by kapachon** [comment]
I like elementor but all my search console performance area is messed up and not clear right now.. Unfortunately their last response from 3 days ago was 

"Currently, this is how our system works, this is not a bug,
this a feature request that our developers are aware of.

At this point, we do not an ETA for this.
But I will be sure to update you once there will be a change.

**Comment by Nachdenker** [comment]
If at least the Table of Contents were **indexable** by Search Engines - that would be a huge improvement. 

@kapachon  Really, that was their response?

> Currently, this is how our system works, this is not a bug,
> this a feature request that our developers are aware of.

Sure, when an important (SEO and usability) Element for websites can't be seen & can't be indexed by Search Engines that is normal and no bug at all^^
I mean, we all pay for Elementor Premium just for fun and create websites just for fun.

Who needs good positions in Google these days?

PS: 
I can only hope that they take us seriously and that they understand that this is a massive limitation of our organic positions in Google.

PPS:
Here is a list with 3rd party "Table of Content" Plugins. I haven't tried those, but maybe one of you did and could tell us about his experience:

- https://uaelementor.com/widgets/table-of-contents/
- https://essential-addons.com/elementor/docs/table-of-content/
- https://dbjpanda.me/apps/tocpack

**Comment by kapachon** [comment]
Exactly.. and unfortunately yes, I just copy-past their response...  :(

**Comment by stephenjpeg** [comment]
@Nachdenker 

I use https://wordpress.org/plugins/easy-table-of-contents/ on all my sites, it hyperlinks correctly and shows up in Google, its also 100% free.

**Comment by cvl01** [comment]
@Nachdenker  @kapachon @ryantan71 and others that want to have this fixed.

I have created a widget that uses pretty urls. It is based on the Elementor Pro widget with small changes. You can copy the styling and settings from the Elementor Pro TOC widget.

I have uploaded it to the WP repository. 

https://wordpress.org/plugins/pretty-table-of-contents-for-elementor/

**Comment by ryantan71** [comment]
@cvl01

Thanks for the plugin, i just installed it and it seems to be working.

**Comment by jgajera** [comment]
+1 from Pro user

Elementor has so many small fixes like this that need to be made, but they keep ignoring their users. I'm strongly considering not renewing my Expert Pro license this year.

**Comment by ryantan71** [comment]
@cvl01

Hello,

How can i remove the hyphen (‐) at the beginning of the URL and the numbers at the end of the url.

Exemple:

https://domain.com/adobe-photoshop-download/#-how-can-i-download-adobe-photoshop-for-free-12
---->
https://domain.com/adobe-photoshop-download/#how-can-i-download-adobe-photoshop-for-free

**Comment by stephenjpeg** [comment]
@cvl01 

Great work Christiaan! It works great. 

Is there any way to remove the numbers at the end of a link?

Example

https://www.site.com/#how-to-xxx-0
https://www.site.com/#where-to-buy-xxx-1
https://www.site.com/#how-much-is-xxx-2
https://www.site.com/#xxx-reviewed-3

**Comment by cvl01** [comment]
Will fix the urls with numbering next week. It was added initially because I had some identical headings in my site, thus making the TOC misbehave. I'll add it as an on/off option to allow for clean urls.

**Comment by ryantan71** [comment]
> Will fix the urls with numbering next week. It was added initially because I had some identical headings in my site, thus making the TOC misbehave. I'll add it as an on/off option to allow for clean urls.
@cvl01
Thank you, please also remove the hyphen at the beginning.
#-how-can-i-download-adobe-photoshop-for-free-12
--->
#how-can-i-download-adobe-photoshop-for-free-12

**Comment by WuM1ha1nho** [comment]
@cvl01

Thanks a lot. I was almost planning on giving up on my Elementor Pro license, Elementor should thank you too.

Besides what the above users have stated, would it be possible to add an option to keep the anchor URL within the same page while also making it possible to add custom anchors (not autogenerated based on headings, but on the column/section ID)? Example below:

From: https://example.com/test**/#[H2]**
To:  https://example.com/test**#[custom-anchor]**

Thanks!

**Comment by cvl01** [comment]
Update is out.

Changelog:
- The duplicate anchor fix is now available as an option.

https://wordpress.org/plugins/pretty-table-of-contents-for-elementor/

**Comment by myBCN** [comment]
+1 on SEO and Collapsable on Desktop

**Comment by marcrevenga** [comment]
I opened the issue on 3 Jan 2020. I glad to see people with the same interest on the issue. I hope elementor take care of user interests and upgrade their toc in order to be more usable in SEO way. 

Thanks to everybody collaborating on this thread.

**Comment by ryantan71** [comment]
@cvl01

Thanks for the update.

How can i remove the hyphen (-) at the beginning?

#-how-can-i-download-adobe-photoshop-for-free-12
---->
#how-can-i-download-adobe-photoshop-for-free

**Comment by cvl01** [comment]
@ryantan71 I think the issue is specific to your setup, as I don’t have a hyphen in the anchor.

I you can’t fix it yourself, please make a ticket on wordpress.org plugins support form so we don’t bloat the github issue.

**Comment by draconnia** [comment]
> I opened the issue on 3 Jan 2020. I glad to see people with the same interest on the issue. I hope elementor take care of user interests and upgrade their toc in order to be more usable in SEO way.
> 
> Thanks to everybody collaborating on this thread.

I hope they do something one of these years, it's so frustrating to be ignored....

**Comment by silkogelman** [comment]
Todays Elementor Pro 3.0.0 release has a cool update related to the TOC widget.

It seems by default the anchors from the Table of Content widgets still are in the #elementor-toc__heading-anchor-0 style.
However if a content editor enters a CSS id in a Title widget, that CSS ID is used as a menu item anchor.

That will result in SEO & user friendly links like
https://www.example.com/test-page#seo-anchor-css-id
And have the benefit that if one alters a title, the css id (and thus the anchor id in TOC) stays the same. This is good because that way title adjustments won't result in broken anchor links.

However, if a content editor forgets to enter a css-id for a title (in the title widget or in code), a menu item anchor would still get the user & SEO unfriendly #elementor-toc__heading-anchor-0 format.

To prevent that from happening and maintain the benefit the current css-id route provides:
is there currently a way to auto populate CSS-id's in the titles (from Title widgets etc) based on the current title?
It would pretty much behave like a page / post slug, (generated when title is entered the first time, staying fixed after that) accept for the fact that anchor id redirects are not really possible.

**Comment by shilo-ey** [comment]
Hey guys,

The new Elementor Pro version (3.0) includes an improvement in terms of SEO to the TOC widget.

From now on you can set custom CSS ID to each element - and it will automatically be added as the TOC anchor.

Thanks

**Comment by parfilov** [comment]
@shilo-ey "automatically" means that heading context uses as anchor, as it works at the [Easy Table of Contents](https://ru.wordpress.org/plugins/easy-table-of-contents/) Go and handle write headings IDs in't automatical.

**Comment by VovHub** [comment]
@shilo-ey this is such a dumb "solution". Why are you forcing us to use Elementor Headlines? What If I want to add the TOC as a separate element in a Gutenberg or Classic editor? Why can't you just make it great as EVERY other TOC plugin does? Instead of beating around the bush with those half-worked "solutions".
@parfilov is 100% right.

**Comment by parfilov** [comment]
@VovHub it's possible to use Gutenberg. There are html anchors for any block since WordPress 5.5. However we still should write these id's by hand to make them beautiful in Elementor TOC.

**Comment by acgorecki** [comment]
Any updates here or is there a new ticket? I am still experiencing these unoptimized anchors from the TOC widget on the latest version of Elementor and Elementor Pro.

**Comment by acgorecki** [comment]
Any updates to this enhancement request or is there a new ticket? I am still experiencing these indexed unoptimized anchors from the ToC widget on the current versions of Elementor and Elementor Pro.

**Comment by vendojo** [comment]
Still unusable. After integrating it on one of my sites, the rankings went down due to duplicate content issues...

**Comment by vicO-o** [comment]
Just came across this issue on my website. Google indexed lots of pages #elementor-toc heading-anchor.... in the url, which duplicates the content. This potentially could hurt my site on google. 

From the discussions I see here, there is no straight solution provided by Elementor. how in hell I suppose to set up a css class for each of my header. Wouldn't be easier to use anyhow html tags?

**Comment by bkjproductions** [comment]
+1

**Comment by elysianventures** [comment]
+1

**Comment by shivaharshm** [comment]
Is there a solution to this? 

TIA guys

**Comment by donolsch** [comment]
Any updates on this? This seems to be such a basic feature.

**Comment by shivaharshm** [comment]
Seriously. Not sure as to why the Elementor Team is sitting on this.

**Comment by shivaharshm** [comment]
Btw coming Jan 2022 would be the second anniversary for this "unresolved issue"

**Comment by Trylobytezz** [comment]
Elementor TOC SEO problems continue in 2022...

**Comment by bkjproductions** [comment]
The markup/controls for the widget is suspect, anyway. While it's nice to be able to specify the icon, the icons center vertically on the wrapper for the LI when you have more than one line of text, which can very frequently be the case. 

The toggle button for **Word Wrap** is backwards: If I choose Word Wrap: Yes, then the text overflow is hidden and given an ellipsis, whereas with Word Wrap: No, the text in fact does wrap.

For some reason there is a border below the Title text, a.k.a. "Header". In **Style: Header: Separator Width** you can set it to 0, but there is no way to put extra space between the Header and the List. There is no way to color the border.

**Content: Additional Options: Minimize Box** is a nice feature but unfortunately when the page loads, the full-height box is there and _then_ it shrinks down. It would be better to _start out minimized._

Sure, I can probably overcome these problems with CSS, but the point of using Elementor was to not have to write so much css.

**Comment by Ping123** [comment]
Here is another solution for the problem:

This code should be added to the functions.php of the theme

```
add_filter('the_content', 'add_ids_to_header_tags');

function add_ids_to_header_tags($content)
{

    $pattern = '#(?P<full_tag><(?P<tag_name>h\d)(?P<tag_extra>[^>]*)>(?P<tag_contents>[^<]*)</h\d>)#i';
    if (preg_match_all($pattern, $content, $matches, PREG_SET_ORDER)) {
        $find = array();
        $replace = array();
        foreach ($matches as $match) {
            if (strlen($match['tag_extra']) && false !== stripos($match['tag_extra'], 'id=')) {
                continue;
            }
            $find[] = $match['full_tag'];
            $id = sanitize_title($match['tag_contents']);
            $id_attr = sprintf(' id="%s"', $id);
            $title_attr = sprintf(' title="%s"', $match['tag_contents']);
            $replace[] = sprintf('<%1$s%2$s%3$s>%4$s</%1$s>', $match['tag_name'], $match['tag_extra'], $id_attr . $title_attr, $match['tag_contents']);
        }
        $content = str_replace($find, $replace, $content);
    }
    return $content;
}
```
To add title tags to the table of contents you can add the following in JS

```
setTimeout(function() {

        let toc = $('.elementor-widget-table-of-contents'),
            toc_item = toc.find('.elementor-toc__list-item');

        toc_item.each(function () {
            let item = $(this).find('a.elementor-toc__list-item-text'),
                item_text = item.text();

            item.attr('title', item_text);
        });

    }, 1000);
```

**Comment by tommya4** [comment]
@Ping123 this works beautifully.

Thank for for doing this.

**The Elementor crew is BEYOND a joke.**

**Comment by alirezakhani** [comment]
@Ping123 thank you very much.
there is a little problem here and it's the offset for the header in sites that have a sticky header.

**Comment by cannavis** [comment]
Ladies and gentlemen, here we go.  All you need is to add this to functions.php:  

function auto_id_headings( $content ) {
    $content = preg_replace_callback( '/(\<h[1-6](.*?))\>(.*?)<\/h[1-6]>/i', function( $matches ) {
        if ( ! stripos( $matches[0], 'id=' ) ) :
            $matches[0] = $matches[1] . $matches[2] . ' id="' . sanitize_title( $matches[3] ) . '">' . $matches[3] . '</h' . substr($matches[1], 2, 1) . '>';
        endif; 
        return $matches[0]; 
    }, $content );
    return $content;
}
add_filter( 'the_content', 'auto_id_headings' );

**Comment by ichandler** [comment]
Anybody know why when I use the ugly generated TOC anchor URL it does not work from a browser, only within the page???  Is this an .htaccess issue???  Generic site, Elem Pro, latest version, mostly all default stuff...

**Comment by cannavis** [comment]
No, not an htaccess issue.  All you need to do is: 

- go to the header or text module
- click the third tab at the top (Advanced)
- then go to CSS ID
- add words here in lowercase and separated by hyphens; this will be your new anchor URL to use on other pages, with a hashtag in front.
- The link should look like this when you add it to another page: website(dot)com/page#words-used-in-css-id

See screenshot below for more reference. Hope that helps!

<img width="1604" alt="Screenshot 2023-07-18 at 11 41 08 AM" src="https://github.com/elementor/elementor/assets/134001314/c76e5b37-2de3-4a0c-971a-658c32cf1e0d">

**Comment by ichandler** [comment]
@cannavis - thank you for the details.  That is not the issue at all.  If I get the URL for a TOC widget listing, and paste that in the address bar, the browser does not go to that area of the page.  
In addition, we have long pages, and they are not fractured into Heading Widget, then Text widget, and on and on.  It is one long Text widget with H? throughout.   Maybe that is bad practice, but the alternative is too complex for the newbie editors.  This long text element makes it much easier to edit for everyone.  So we have no individual CSS IDs to target, only the stupid construction of the TOC widget's anchor.  If Elementor were to allow a CSS ID inside the <H?> tag that I could create manually, that would be great, but I cannot get an anchor html to work either (<p id="target"></p>)
An example is 
https://healthwithoutantidepressants.com/stop/#elementor-toc__heading-anchor-25
where that is the URL embedded in the TOC and copied exactly, and works from a click on the TOC itself.  It works fine ON THE PAGE when you click it, but NOT from a new tab in the browser.  Even without the extra slash after the page
https://healthwithoutantidepressants.com/stop#elementor-toc__heading-anchor-25
Thanks for your attention, I really appreciate it.  I am new to WP/Elem, but have been a programmer for over 50 years...

**Comment by bkjproductions** [comment]
A hunch, maybe the ID's that the TOC anchor is referencing are not actually there until the DOM loads. 

That is, if the TOC widget is set to create named anchors to H3's on the page, for example, and the H3s do not normally have ID's, then when the page loads, if your url is whatever.com/#elementor-toc__heading-anchor-25, that anchor does not yet exist, so the browser cannot find it. 

However the TOC widget loads and assigns IDs, so when you click a link in the TOC, it will work.

Solution would be to have a script delay of a second, then send a click to the correct TOC link, or do a scroll-to-the-anchor-ID.

**Comment by ichandler** [comment]
The solution I figured out was fairly direct.  I took the HTML of the page, and added an id="target" to each of the `<H?>` tags manually.  They look like 
`<h4 id="capsules">Which capsules should I buy?</h4>`
and when I use 
https://healthwithoutantidepressants.com/stop/#capsules
it works fine.  Would be nice if Elem facilitated this from the "Visual" editor...  Nobody on the team has the HTML skills to go in the code and add that...
Elem expects you to fragment the page into Heading elements and Text elements and that is not practical for some complex pages we use, given the editor skills.
Thanks everyone for your attention and help.

**Comment by ichandler** [comment]
And ZERO thanks to Elementor, who is insanely negligent in dealing with a critical SEO issue as defined well above.  Should not take YEARS of being ignored to ...  see no progress.
Foo on you, Elementor.

**Comment by sonumodi7208** [comment]
Issue Resolved Follow this article:

[https://digix99.com/resoved-elementor-table-of-contents-seo-friendly-url-issue/](https://digix99.com/resoved-elementor-table-of-contents-seo-friendly-url-issue/)

**Comment by kovou** [comment]
+1 for the solution on this issue. Putting manually Ids to headers isnt a solution.

**Comment by kovou** [comment]
A solution that works for me

Add the bellow code to functions.php

`// toc correction

add_filter('the_content', 'add_ids_and_titles_to_header_tags');

function add_ids_and_titles_to_header_tags($content)
{
    $pattern = '#(?P<full_tag><(?P<tag_name>h\d)(?P<tag_extra>[^>]*)>(?P<tag_contents>[^<]*)</h\d>)#i';
    if (preg_match_all($pattern, $content, $matches, PREG_SET_ORDER)) {
        $find = array();
        $replace = array();
        foreach ($matches as $match) {
            if (strlen($match['tag_extra']) && false !== stripos($match['tag_extra'], 'id=')) {
                continue;
            }
            $find[] = $match['full_tag'];
            $id = sanitize_title($match['tag_contents']);
            $id_attr = sprintf(' id="%s"', urldecode($id));
            $title_attr = sprintf(' title="%s"', $match['tag_contents']);
            $replace[] = sprintf('<%1$s%2$s%3$s>%4$s</%1$s>', $match['tag_name'], $match['tag_extra'], $id_attr . $title_attr, $match['tag_contents']);
        }
        $content = str_replace($find, $replace, $content);
    }
    return $content;
}

// Add the following code to include the title attribute directly in the Table of Contents
add_filter('the_content', 'add_titles_to_toc_items');

function add_titles_to_toc_items($content)
{
    $pattern = '/<div class="elementor-toc__list-item-text-wrapper"><a href="#([^"]+)" class="elementor-toc__list-item-text/';
    preg_match_all($pattern, $content, $matches);

    if (!empty($matches[1])) {
        foreach ($matches[1] as $anchor) {
            $title = urldecode(str_replace('-', ' ', $anchor)); // Replace hyphens with spaces
            $replacement = sprintf('<div class="elementor-toc__list-item-text-wrapper"><a href="#%1$s" title="%2$s" class="elementor-toc__list-item-text', $anchor, $title);
            $content = preg_replace('/<div class="elementor-toc__list-item-text-wrapper"><a href="#' . preg_quote($anchor, '/') . '" class="elementor-toc__list-item-text/', $replacement, $content, 1);
        }
    }

    return $content;
}
`

**Comment by EfrainTorres** [comment]
> Issue Resolved Follow this article:
> 
> https://digix99.com/resoved-elementor-table-of-contents-seo-friendly-url-issue/

Improved

`function auto_id_headings( $content ) {
    $content = preg_replace_callback('/(<h[1-3])(.*?>)(.*?)(<\/h[1-3]>)/is', function($matches) {
        // Check if 'id' attribute already exists
        if ( !stripos( $matches[0], 'id=' ) ) {
            $id = sanitize_title($matches[3]); // Sanitize the headline text for use as an ID
            return $matches[1] . ' id="' . $id . '"' . $matches[2] . $matches[3] . $matches[4];
            // Reconstructs the heading tag with the sanitized ID
        }
        return $matches[0]; // Returns the original match if 'id' attribute exists
    }, $content);
    return $content;
}
add_filter( 'the_content', 'auto_id_headings' );`


The original code snippet added everything inside the text editor widget to the ID. This version only adds the heading tag.

**Comment by richhersey** [comment]
I just recently noticed that Google was indexing my posts with "#elementor-toc__heading-anchor" in the URL. Found this thread and applied that code snippet to my PHP file. 

Went back to check those posts and found that the PHP file had corrupted something else and crashed my entire site. Reverted the PHP and still my site was down, giving me only error pages instead of my website. I had to restore from yesterday's backup file and now everything is working again, but I'm still struggling with resolving the issue of the "#elementor-toc__heading-anchor" posts. 

Any other suggestions or fixes? Any idea what I may have done wrong?

**Comment by cannavis** [comment]
> I just recently noticed that Google was indexing my posts with "#elementor-toc__heading-anchor" in the URL. Found this thread and applied that code snippet to my PHP file.
> 
> Went back to check those posts and found that the PHP file had corrupted something else and crashed my entire site. Reverted the PHP and still my site was down, giving me only error pages instead of my website. I had to restore from yesterday's backup file and now everything is working again, but I'm still struggling with resolving the issue of the "#elementor-toc__heading-anchor" posts.
> 
> Any other suggestions or fixes? Any idea what I may have done wrong?


Hi @richhersey 

The following is what I use and it works for me. However, its not automatic as it seems @EfrainTorres solution seems to do.  

With the PHP version I use, it caters to Headings 1-6, but it doesn't test to see if there is an ID first... 

I manually go to the css ID under advanced and add what I want for the on-page TOC URL display.

-------------------------------------------

function auto_id_headings( $content ) {
    $content = preg_replace_callback( '/(\<h[1-6](.*?))\>(.*?)<\/h[1-6]>/i', function( $matches ) {
        if ( ! stripos( $matches[0], 'id=' ) ) :
            $matches[0] = $matches[1] . $matches[2] . ' id="' . sanitize_title( $matches[3] ) . '">' . $matches[3] . '</h' . substr($matches[1], 2, 1) . '>';
        endif; 
        return $matches[0]; 
    }, $content );
    return $content;
}
add_filter( 'the_content', 'auto_id_headings' );

--------------------------------------------

Also,  As an FYI
I use Code Snippets Pro. 
And choose "run snippet everywhere"

**Comment by Eka-Chu** [comment]
@EfrainTorres, thanx 

Improved.

If the ID is longer than 50 symbols, truncate it in order to be max 125 symlols in whole link.

`function auto_id_headings( $content ) {
    $content = preg_replace_callback('/(<h[1-3])(.*?>)(.*?)(<\/h[1-3]>)/is', function($matches) {
        if ( !stripos( $matches[0], 'id=' ) ) {
            $id = sanitize_title($matches[3]); // Sanitize the headline text for use as an ID
            if (strlen($id) > 50) {
                // If the ID is longer than 50 characters, truncate it
                $words = explode('-', $id);
                $truncated_id = '';
                foreach ($words as $word) {
                    if (strlen($truncated_id . $word) > 50) {
                        break;
                    }
                    $truncated_id .= $word . '-';
                }
                // Remove the trailing dash
                $truncated_id = rtrim($truncated_id, '-');
                $id = $truncated_id;
            }
            return $matches[1] . ' id="' . $id . '"' . $matches[2] . $matches[3] . $matches[4];
        }
        return $matches[0];
    }, $content);
    return $content;
}
add_filter( 'the_content', 'auto_id_headings' );
`

**Comment by cannavis** [comment]
community at its best. love it. Thanks @Eka-Chu

**Comment by layscough** [comment]
The above code is working for me, but it breaks smooth scroll and my css scroll offset.

**Comment by sundown1999** [comment]
Since the #elementor-toc__heading-anchor is only displaying under "results" and not under "indexed URL:s", does it even affect the SEO at all? 

This should not cause multiple content, or am I wrong?

**Comment by krlabs** [comment]
> Issue Resolved Follow this article:
> 
> https://digix99.com/resoved-elementor-table-of-contents-seo-friendly-url-issue/

Thank you very much. It works!

**Comment by paulchiao** [comment]
The above code is working for me, but it breaks smooth scroll and my css scroll offset. how to solve this problem? I need smooth scroll and scroll offset.

**Comment by krlabs** [comment]
Now, for some reason, none of the proposed options work.

**Comment by anatshecodes** [comment]
> Since the #elementor-toc__heading-anchor is only displaying under "results" and not under "indexed URL:s", does it even affect the SEO at all?
> 
> This should not cause multiple content, or am I wrong?

Does anyone know what the situation is as of today after the 3.25.0 update?

The commenter here indicated that his links were indexed:
https://github.com/elementor/elementor/issues/10052#issuecomment-762317037
