### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by ondrej-mahdalik** [elementor/elementor#10068]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Dark mode in the editor is nice, but I think it's more important to bring a dark mode to visitors.
Some of my websites are made in light colors, and they are uncomfortable to browse during the night.
Those websites could really use some sort of switching to dark colors, just like Elementor UI does.

**Describe the solution you'd like**
A possibility to enable dark mode functionality and set up colors for elements that would be used when dark mode is enabled. And for enabling dark mode - either detection of OS settings or a switch widget that could be placed somewhere on the page.

**Comment by shilo-ey** [comment]
Currently, this feature is limited to the Editor only. We don't have any plans for implementing Dark Mode on client side.

If you wish to do that, you can do it using [this guide](https://flaviocopes.com/dark-mode/).

Thanks!
