### ISSUE TITLE
API Key of Mailerlite not being used by form widget. 

### ISSUE THREAD

**Issue by purpleglow** [elementor/elementor#10060]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
API Key of Mailerlite not being used by the form widget. 

## Steps to reproduce
1. Add API key of MailerLite to Settings > integrations > MailerLite and click Validate. 
2. Create a form with the Forms widget and add an Email field
3. Add Mailerlite as an "Action after Submit"
4. Open the Maillerlite section on the left and watch how the "Groups" dropdown never completes loading if you leave it on "Default". 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting, we will address this issue and release a patch.

**Comment by shilo-ey** [comment]
Hi @purpleglow 

Thanks for your feedback.

Try clicking on "Update" after the entering your Integration API key.

Thanks
