### ISSUE TITLE
condition bug in Group Control Background

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#10071]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello great team.

I found a bug related condition of Group Control Background.

When you leave background image in desktop blank then you select background image on tablet/mobile => all controls like background size, position, attachment will not showing.
Could you check & fix it?

![download (1)](https://user-images.githubusercontent.com/7134267/71796209-429ec200-307c-11ea-90c4-1d94891b002c.png)

**Comment by lior-sh** [comment]
Hi @steve231293,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
