### ISSUE TITLE
Can't disable "Pause on hover" in image caroussel

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#10078]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I have an image caroussel and I want it to keep scrolling even if we hover with the mouse. But even with the options "Pause on hover" and "Pause on interaction" set to No, the caroussel pauses when we hover with the mouse.

## Steps to reproduce

1. Create a caroussel
2. Add images
3. Set the option "Pause on hover" to No
4. Set the option "Pause on interaction" to No
5. Hover the caroussel

The caroussel stops scrolling.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @vgstef,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by jemae31** [comment]
I have the same issue, I chose "NO" for the pause on hover option but when I hover on the images it still pauses,
