### ISSUE TITLE
Having issues loading a script in the editor. 

### ISSUE THREAD

**Issue by acehobojoe** [elementor/elementor#10079]
Hello friends, 

I've created a simple widget that loads a JS file upon the page load. It works fine. The functionality is a simple toggle slider that toggles content. The problem I'm running into is with the editor. I can't get it to load the script and display the script in the editor. I'm not sure what is going on with the hooks. 
Here is my js code. 

`"use strict";

( function( $ ) {
  /**
   * @param $scope The Widget wrapper element as a jQuery element
   * @param $ The jQuery alias
   */
  var ToggleHandler = function( $scope, $ ) {
    console.log( $scope );
  };

} )( jQuery );

if (jQuery(".tgl").is(':checked')) {
  jQuery('.section-1').addClass("hide-sec");
  jQuery('.section-2').removeClass("hide-sec");
}

jQuery('.tgl').change(function () {
  jQuery('.section-1,.section-2').toggleClass('hide-sec');

});`

**Comment by udidol** [comment]
Hi @acehobojoe,
How do you load the script?
The proper way to load a JS script is to register it using WordPress's `wp_register_script()` function (PHP), then making sure it is enqueued with your widget. 

The way we recommend enqueuing your script is by implementing the `get_script_depends()` method in your widget's PHP class, as follows:
```
public function get_script_depends() {
    return [ 'script-handle' ];
}
```
A more detailed explanation on how to incorporate JS handlers with Elementor widgets can be found in our developer documentation: https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/
