### ISSUE TITLE
Custom CSS not restricted to widget  in which it is inserted

### ISSUE THREAD

**Issue by maryannstoll** [elementor/elementor#10087]
## Prerequisites

 [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

I added custom CSS to an Elementor Pro Posts widget, expecting the CSS to apply to that one instance of the widget only.  The CSS applied to all instances of the widget within the same template.

I added this CSS to a single Posts widget via the Advanced > Custom CSS tab:
.elementor-post__title a{visibility: hidden;}

Note that I did NOT prepend "Selector" to the statement.
The contents of this video: https://www.youtube.com/watch?v=BZ9RCEU6ph8
imply that "selector .elementor-post__title a{visibility: hidden;}" is equivalent to ".elementor-post__title a{visibility: hidden;}" and that it applies only to the widget being edited.

Unfortunately, the titles on all of my Post widgets in the same template were hidden! 

In testing this, I added other CSS to other Posts widgets within the template in question and observed that the CSS was applied to all widgets, regardless of their type, in that template.  The CSS is not applied to widgets outside of the template where the Custom CSS is inserted.

## Steps to reproduce

Edit a widget in an Elementor template.
Enter the Advanced > Custom CSS tab.
Add CSS attributes to any class ID that could be found in any widget.

## Isolating the problem

- [?] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Elementor and Elementor Pro V 2.8.3

Copied from Elementor > System:
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel79.0, Revision 79.0 v5.6.32-78.0
	PHP Version: 7.2.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://haydenlakewid.com
	Home URL: https://haydenlakewid.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: -8
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

== Active Plugins ==
	ACF Content Analysis for Yoast SEO
		Version: 2.3.0
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Activity Log
		Version: 2.5.2
		Author: Activity Log Team

	Add Categories to Pages.
		Version: 1.2
		Author: a.ankit

	Advanced Custom Fields
		Version: 5.8.7
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.8.7
		Author: Elliot Condon

	Anywhere Elementor
		Version: 1.2.1
		Author: WPVibes

	AnyWhere Elementor Pro
		Version: 2.13.2
		Author: WP Vibes

	Asset CleanUp: Page Speed Booster
		Version: 1.3.5.3
		Author: Gabriel Livan

	Backup
		Version: 1.2.2
		Author: BackupGuard

	Blog2Social: Social Media Auto Post & Scheduler
		Version: 6.0.0
		Author: Blog2Social, Adenion

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.7.1
		Author: WebDevStudios

	Democracy Poll
		Version: 5.5.6.3
		Author: Kama

	Disable Comments
		Version: 1.10.2
		Author: Samir Shah

	Easy Popup Announcement
		Version: 1.0.4
		Author: Pupung Budi Purnama

	Easy Theme and Plugin Upgrades
		Version: 2.0.1
		Author: Chris Jean

	Elementor
		Version: 2.8.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 3.7.0
		Author: WPDeveloper

	Featured Image Caption
		Version: 0.8.9
		Author: Christiaan Conover

	Featured Images in RSS for Mailchimp & Other Email
		Version: 1.5.4
		Author: 5 Star Plugins

	Formidable Forms
		Version: 4.03.06
		Author: Strategy11

	Formidable PRO2PDF
		Version: 2.97
		Author: Alexandre S.

	Google Analytics for WordPress by MonsterInsights
		Version: 7.10.2
		Author: MonsterInsights

	Mmm Simple File List
		Version: 2.1
		Author: Adam Bissonnette

	Really Simple CAPTCHA
		Version: 2.0.2
		Author: Takayuki Miyoshi

	Regenerate Thumbnails Advanced
		Version: 2.1.0
		Author: ShortPixel

	Revolution for Elementor
		Version: 0.0.19
		Author: Jan Thielemann

	RSS Includes Pages
		Version: 3.7
		Author: Marios Alexandrou

	Show Current Template
		Version: 0.3.3
		Author: JOTAKI Taisuke

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	Simple History
		Version: 2.33
		Author: Pär Thernström

	Simple Page Ordering
		Version: 2.3.2
		Author: Jake Goldman, 10up

	Smush
		Version: 3.3.2
		Author: WPMU DEV

	WP File Manager
		Version: 5.5
		Author: mndpsingh287

	Yoast SEO Premium
		Version: 12.7.1
		Author: Team Yoast

== Must-Use Plugins ==
	System Plugin
		Version: 3.12.0
		Author: 

== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		form : 2
		heading : 18
		icon-list : 6
		nav-menu : 2
		social-icons : 4
		term-list : 2
		text-editor : 2
	page : 3
		button : 12
		form : 2
		heading : 30
		icon-list : 6
		image : 10
		nav-menu : 2
		posts : 2
		social-icons : 4
		text-editor : 8
	section : 6
		form : 1
		heading : 12
		image : 2
		nav-menu : 6
		posts : 1
		social-icons : 5
		text-editor : 1
	single : 3
		button : 1
		facebook-button : 1
		form : 3
		heading : 34
		icon-list : 3
		nav-menu : 7
		post-comments : 1
		post-info : 3
		post-navigation : 1
		posts : 9
		search-form : 3
		share-buttons : 3
		social-icons : 6
		term-list : 3
		text-editor : 1
		theme-post-content : 3
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 3
		wp-widget-recent-posts : 1
	wp-post : 1
		ae-acf-gallery : 1
		ae-acf-repeater : 1
		ae-custom-field : 2
		button : 6
		eael-feature-list : 2
		form : 2
		gallery : 1
		heading : 21
		image : 5
		media-carousel : 1
		nav-menu : 3
		posts : 2
		social-icons : 3
		term-list : 1
		text-editor : 10

== Log ==
	
Log: showing 20 of 282019-07-11 14:04:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.11',
  'to' => '2.5.13',
)]
2019-07-17 06:21:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]
2019-08-20 15:45:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.14',
  'to' => '2.6.3',
)]
2019-08-27 13:02:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.3',
  'to' => '2.6.5',
)]
2019-09-30 12:21:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.5',
  'to' => '2.7.1',
)]
2019-10-04 08:01:14 [info] elementor::elementor_updater Started 
2019-10-04 08:01:14 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-10-04 08:01:14 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-10-04 08:01:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.0',
  'to' => '2.7.3',
)]
2019-10-09 09:30:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.3',
  'to' => '2.7.4',
)]
2019-10-09 09:30:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.1',
  'to' => '2.7.2',
)]
2019-11-08 16:46:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-11-08 16:46:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-12-11 12:31:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.1',
)]
2020-01-03 16:46:02 [info] elementor::elementor_updater Started 
2020-01-03 16:46:02 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-03 16:46:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.3',
)]
2020-01-03 16:46:03 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-03 16:46:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.3',
)]
2020-01-03 16:49:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.3',
)]

PHP: showing 5 of 5PHP: 2019-07-09 10:21:02 [warning X 1][/home/content/a2pewpnaspod05_data03/37/41701737/html/wp-content/plugins/elementor/includes/base/controls-stack.php::716] Illegal string offset 'type' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-20 15:45:44 [notice X 1][/home/content/a2pewpnaspod05_data03/37/41701737/html/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-08-28 15:09:12 [notice X 2279][/var/www/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1249] Undefined index: button_icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-11 07:44:40 [notice X 1][/var/www/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::226] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-12 07:55:49 [notice X 52][/var/www/wp-content/plugins/elementor-pro/modules/gallery/widgets/gallery.php::1426] Undefined index: alt [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2019-08-28 23:19:28 [error X 29][https://haydenlakewid.com/wp-admin/load-scripts.php?c=0&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.2.2 line 1 > Function:6:1] eael_feature_list_icon is not defined 
JS: 2019-08-28 23:26:07 [error X 3][https://haydenlakewid.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.8:32:109931] this._parent is undefined 
JS: 2019-11-08 19:44:39 [error X 6][https://haydenlakewid.com/wp-content/uploads/essential-addons-elementor/eael.min.js?ver=3.3.3:1:42430] r is undefined 
JS: 2019-11-08 22:57:36 [error X 27][https://haydenlakewid.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:32:138844] elementorFrontend.elements.window.jQuery is not a function 
JS: 2019-11-08 22:57:37 [error X 11][https://haydenlakewid.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:2:62467] this.ui.tools is undefined 
JS: 2019-11-08 22:57:37 [error X 48][https://haydenlakewid.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.7.4:2:0]  
JS: 2019-11-11 15:44:41 [error X 37][https://haydenlakewid.com/wp-content/plugins/revolution-for-elementor/public/js/public.js?ver=1.0.0:44:21] settingsKeys is undefined 
JS: 2019-12-10 17:32:26 [error X 17][https://haydenlakewid.com/wp-content/plugins/anywhere-elementor-pro/includes/assets/js/common.min.js?ver=2.13:1:5067] n is undefined 
JS: 2020-01-06 19:53:34 [error X 8][https://haydenlakewid.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.3:2:56057] this.ui.select is undefined 

				
</details>

**Comment by shilo-ey** [comment]
Hi @maryannstoll 

Thanks for your feedback

We can't reproduce your issue:
![image](https://user-images.githubusercontent.com/45009641/72216422-6903a800-3529-11ea-9b68-d6417458a960.png)


The first widget is with your added code, the other one is without it.

If the issue persists please contact our support for better debugging.

Thanks
