### ISSUE TITLE
Elementor Popups - How to trigger after contact form 7 submit

### ISSUE THREAD

**Issue by hasintha** [elementor/elementor#10089]
Hello there

I want to display a popup when a user successfully submitted a inquiry using Contact Form 7 form. CF7 has a custom DOM event for this purpose and I intend to add a listener and display the popup.

What is the best way to do this? Popup details are as follows

`popup title: cf7-submission`
`toggle url: #elementor-action%3Aaction%3Dpopup%3Aopen%20settings%3DeyJpZCI6IjE3NzE2IiwidG9nZ2xlIjpmYWxzZX0%3D`
`shortcode : [elementor-template id="17716"]`

best Regards

**Comment by shilo-ey** [comment]
The Shortcode itself doesn't trigger the popup.

To do so you will need to actively trigger it.

Set the shortcode in the submit message, and add the following jQuery code to run after successful form submission:
```JS
// wait for the page to load
	jQuery( document ).ready( function() {
		 // wait for elementor to load
		jQuery( window ).on( 'elementor/frontend/init', function() {
			// wait for elementor pro to load
			elementorFrontend.on( 'components:init', function() {
				 // show the popup
				elementorFrontend.documentsManager.documents[17716].showModal();
			} ); // 17716 is your Popup ID
		} );
	} );
```

Thanks

**Comment by hasintha** [comment]
@shilo-ey Thanks bro Appreciate it.

**Comment by akshayrox123** [comment]
I didn't follow.

So I have added the shortcode in 
Contact form 7 > messages >  Sender's message was sent successfully
Or am i missing something?
