### ISSUE TITLE
[Feature Request] Add Fallback Background - Background Settings

### ISSUE THREAD

**Issue by glanglois** [elementor/elementor#10096]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Description

Add the same configuration settings for a "standard" background image to the fallback background image (used with a background video). Namely:
- Position (Responsive)
- Attachment
- Repeat (Responsive)
- Size (Responsive)

This would enable more flexibility to display the fallback background on different screen size, especially if the background video is only played once. 

Additionally, we should also have the possibility to add Motion Effects to Fallback Background. 
Consequently, if the background video is used for header and cannot load, we could still have a pretty header with parralax effect.

Thank you.

**Comment by glanglois** [comment]
Note that, at the moment, it is possible to add some Custom CSS as follow:

> .elementor-element.elementor-element-******* {
>         background-attachment: fixed !important;
>         background-position: center !important;
>         background-repeat: no-repeat !important;
>         background-size: cover;
>  }

and use @media to achieve responsive fallback backgrounds.

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by jonathanarbely** [comment]
The feature has been implemented a long time ago, but has never worked and still doesn't.
