### ISSUE TITLE
BUG: Testimonials carousel with black background

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#10091]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using **Testimonials Carousel** widget on black background, the pagination can't be seen.

I can control the active pagination dot, but I can;t change the inactive dot color.

![tc](https://user-images.githubusercontent.com/576623/71975212-073af980-321c-11ea-8e1b-f93bbb4a2858.png)

Tested with latest versions of **Elementor Pro** and **Hello Elementor** theme.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by lior-sh** [comment]
Hi @ramiy,

Thanks for reporting, I was able to change the dot color.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
