### ISSUE TITLE
Stumbleupon URL is redirecting on wrong URL in social buttons widget

### ISSUE THREAD

**Issue by jainnidhi** [elementor/elementor#10099]
Hello team,

Stumbleupon is taking me to this URL.
https://mix.com/mixit?su=submit&url=http://google.com/

Is it correct?

Can you please help me out?

Thanks in advance!

**Comment by shilo-ey** [comment]
Hi @jainnidhi 

Thanks for your feedback, StumbleUpon was bought by Mix

We will change the labeling of this option.

Thanks
