### ISSUE TITLE
Background color and background overlay color not working

### ISSUE THREAD

**Issue by Grynn07** [elementor/elementor#10097]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

While editing, background color and background color overlay do not work. If I try applying one is appears the color is applied, but it is not. https://prnt.sc/ql51js 
Then, if I click into a different widget and come back to that section, the color disappears as if I did not apply it. https://prnt.sc/ql51xd

Same thing happens with background overlay color. Background images do work though.

## Steps to reproduce

Try applying a background color or background overlay on a section or any widget, really.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

I do have the most recent version of Elementor and Elementor Pro. I tried reinstalling it and Elementor Pro. I tried changing my theme to a basic WordPress theme. I am using OceanWP, though I have also tried GeneratePress. No errors come up in the console log when I check the browser inspector.

[system-info-yourfam.yooweb.me-09-01-2020.txt](https://github.com/elementor/elementor/files/4038806/system-info-yourfam.yooweb.me-09-01-2020.txt)

```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @Grynn07, 

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
* Video
Without it, we simply can't help.
Thanks.

**Comment by BoBella** [comment]
Im having this same issue!!!

**Comment by eliquame** [comment]
Same issue!

The section background overley function not working! Not with color not with image.

Latest version all of plugins and wordpress. (with elementor pro)
Elementor default theme (Hello Theme)

**Comment by saberlight** [comment]
I'm having the same issue. Column background overly color or image just doesn't show at all.

**Comment by johnsicili** [comment]
Same issue. Column background overlay gradient and color not working. I also have Elementor Pro.

**Comment by ViktorOster** [comment]
I have this issue as well, but only if it's inside a column. If I add a background image and an overlay inside a column, the overlay won't work. I have to add custom CSS to the overlay layer (background color and opacity) to get the same effect.

**Comment by AndrewLeonardi** [comment]
Yep. Same issue. Any updates here?

**Comment by AndrewLeonardi** [comment]
I was having the same issue. I fixed it in my case by going to background overlay, and switching it from Gradient to classic. No idea if that will help in other cases. Good luck!

**Comment by kiber-chaka** [comment]
In mi case the problem was, that it was and empty div. Just adding an element will help. I didn't needed anything, so I put a spacer element there.
