### ISSUE TITLE
color code selector not functioning as it did

### ISSUE THREAD

**Issue by adamisaacs** [elementor/elementor#10092]
The new color selector in Elementor editor does not allow you to type in color codes like it used to. the second you type a letter, it "guesses" at which color code you want and no matter how many times you try to delete it, it continues to set a color itself. the only ways around this are pasting a completed color code in to the text box or solely using premade color choices.

this is a feature elementor used to have but now does not. i prefer the old color selector 1000%.

**Comment by adamisaacs** [comment]
the color selector also pre-selects black, but the text isn't truly black (its some default gray). to select black, you must select a different color, then select black again. minor frustrations, but these disruptions to my work flow did not exist in the last elementor update.

**Comment by lior-sh** [comment]
Hi @adamisaacs,

This first issue was resolved already in the latest builds and regarding the second issue, it will be fixed soon.
Thanks.
