### ISSUE TITLE
Triggering popup

### ISSUE THREAD

**Issue by ronixx1** [elementor/elementor#10090]
Hi,
I'm using an API service that detected the user Geo location.
I want to create number of popups and trigger them according the Geo location of the user.
For example- if the user come from Germany I want to trigger the German popup.
We found that can it be triggered by selector but we don't want it to trigger by clicking on something.
Can u send me some JS code that triggering the popup?

Thanks.

**Comment by hasintha** [comment]
I too want to know this, kindly someone help.

**Comment by shilo-ey** [comment]
Hi @ronixx1 

See here more info regarding triggering your popup: #10089 and also here #10056

Thanks
