### ISSUE TITLE
✅ 🚀 Feature Request: Change image shape on Testimonial Carousel

### ISSUE THREAD

**Issue by mjmcgrath-ct** [elementor/elementor#10103]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to display the logo of the company on the testimonials carousel.  Currently the image is automatically cropped to a circle which does not work with all logos

**Describe the solution you'd like**
I would like the option to toggle the shape of the image between circle and square

**Describe alternatives you've considered**
I've considered using the other sliders or another carousel

**Additional context**

**Comment by peyobaros** [comment]
Hey, if I understood your problem right, then I was facing the same issue as the circle shape does not work well for the images I wanted to display. After checking all the options in that Elementor widget I saw a way to make the shape square, note that this solution is for the whole widget, it does not allow you to change the shape of single images.

What you need to do to change the shape from circle to square is - Go to the Styles tab > Image, where you will see the **Border Radius** option. The only thing you need to do to make the images square is set the border radius value to 0.

That's is all. I wasn't able to find any other solution looking around the net. I hope that helps you.

![image](https://user-images.githubusercontent.com/73580275/131348115-7c0689f3-ae3b-41fb-8dd5-7bc2d36882bd.png)

**The result:**

![image](https://user-images.githubusercontent.com/73580275/131348592-f5072251-e183-4443-a4dd-2eae0fa68f7a.png)

**Comment by nicholaszein** [comment]
Hello there @mjmcgrath-ct!

We have great news! 🙌 

You can now use the new nested Carousel widget and build your own layouts with any widget, including the Image widget, that allows for more control over the size and dimensions of your images. This replaces the need to update the Testimonial Carousel widget, which could introduce backward compatibility issues.

You can learn more about the new Nested Carousel widget in this article: https://elementor.com/help/carousel-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
