### ISSUE TITLE
Add Rel="noopener" options for Social Links (And wherever is needed) as suggested by Google Lighthouse

### ISSUE THREAD

**Issue by ScarletSeven** [elementor/elementor#10109]
According to https://developers.google.com/web/tools/lighthouse/audits/noopener

we're supposed to add noopener for links that open in another browser window/tab. Wordpress does this in Gutenberg, but inside of the Social Icons widget, there is an option to Open in new window but no option to add rel="noopener" or rel="noreferrer". Either do this automatically, or give us an option to select it.

I'm not sure what other widgets have this, but do consider adding this across all other widgets too.

**Comment by shilo-ey** [comment]
I merged this issue with #9079, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
