### ISSUE TITLE
Cannot hook into custom post query

### ISSUE THREAD

**Issue by barrychapman** [elementor/elementor#10118]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Have submitted multiple requests for clarification on this to no avail through support (am a paying pro user).

We have a customized WP_Query object that is used to search a custom post type by geographic location (lat,long). However, we have no way to hook into the results of that WP_Query object to iterate and display in Elementor.

## Steps to reproduce

Create Archive or Page
No way to hook into custom post query

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: MySQL Community Server - GPL v8.0.18
	PHP Version: 7.4.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.5
	Site URL: https://ngfd.ghosttown.io
	Home URL: https://ngfd.ghosttown.io
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name: FloorDetective
	Version: 2.1.0
	Author: Ghosttown Development, LLC
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.1.3
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

== Active Plugins ==
	ACF Options Page Admin
		Version: 3.9.4
		Author: John A. Huebner II

	Advanced Cron Manager
		Version: 2.3.9
		Author: BracketSpace

	Advanced Custom Fields: Extended
		Version: 0.8.3.1
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 5.8.4
		Author: Elliot Condon

	AnyWhere Elementor Pro
		Version: 2.13.2
		Author: WP Vibes

	Astra Pro
		Version: 2.1.4
		Author: Brainstorm Force

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Custom Fonts
		Version: 1.2.0
		Author: Brainstorm Force

	Custom Sidebars
		Version: 3.2.3
		Author: WPMU DEV

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	DynamicConditions
		Version: 1.4.1
		Author: RTO GmbH

	Dynamic Content for Elementor
		Version: 1.5.2
		Author: Dynamic.ooo

	Dynamic Visibility for Elementor
		Version: 3.0.1
		Author: Dynamic.ooo

	Easy WP SMTP
		Version: 1.3.9.1
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 2.8.3
		Author: Elementor.com

	Elementor - Header, Footer & Blocks
		Version: 1.1.4
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 1.9.7
		Author: Flexible-Elementor-Panel.com

	FloorDetective
		Version: 1.0.0
		Author: Ghosttown Development, LLC

	Font Awesome
		Version: 4.0.0-rc13
		Author: Font Awesome

	GEO my WP
		Version: 3.4
		Author: Eyal Fitoussi

	GMW Add-on - Premium Settings
		Version: 2.4
		Author: Eyal Fitoussi

	GP Conditional Pricing
		Version: 1.2.36
		Author: Gravity Wiz

	GP Nested Forms
		Version: 1.0-beta-6.14
		Author: David Smith

	Gradient Button for Elementor
		Version: 1.0.2
		Author: BloomPixel

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	Gravity Forms
		Version: 2.3.6.4
		Author: rocketgenius

	Gravity Forms Constant Contact Add-On
		Version: 3.1.1
		Author: Katz Web Services, Inc.

	Gravity Forms Coupons Add-On
		Version: 2.8
		Author: rocketgenius

	Gravity Forms Stripe Add-On
		Version: 2.6
		Author: rocketgenius

	Gravity Perks
		Version: 2.1.1
		Author: Gravity Wiz

	Heroic Knowledge Base
		Version: 2.17.0
		Author: HeroThemes

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.2.2
		Author: HasThemes

	Inspection Report Generator
		Version: 1.0.0
		Author: Ghosttown Development, LLC

	JetBlocks For Elementor
		Version: 1.2.0
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.2.0
		Author: Crocoblock

	JetElements Dynamic Data Addon
		Version: 1.1.2
		Author: Zemez

	JetElements For Elementor
		Version: 2.2.4
		Author: Crocoblock

	JetEngine
		Version: 2.1.4
		Author: Zemez

	JetSmartFilters
		Version: 1.5.0
		Author: Zemez

	JetThemeCore
		Version: 1.1.17
		Author: Zemez

	JetTricks
		Version: 1.2.6
		Author: Crocoblock

	Loginizer
		Version: 1.4.3
		Author: Raj Kothari

	MailOptin - Lite
		Version: 1.2.23.1
		Author: MailOptin Team

	MemberPress Constant Contact
		Version: 1.0.2
		Author: Caseproof, LLC

	MemberPress Corporate Accounts
		Version: 1.5.6
		Author: Caseproof, LLC

	MemberPress Developer Tools
		Version: 1.1.21
		Author: Caseproof, LLC

	MemberPress Downloads
		Version: 1.0.3
		Author: Caseproof, LLC

	MemberPress Importer
		Version: 1.5.1
		Author: Caseproof, LLC

	MemberPress Math CAPTCHA
		Version: 1.1.7
		Author: Caseproof, LLC

	MemberPress Plus
		Version: 1.7.4
		Author: Caseproof, LLC

	MemberPress User Roles
		Version: 1.0.4
		Author: Caseproof, LLC

	Members
		Version: 2.2.0
		Author: MemberPress

	Nav Menu Roles
		Version: 1.9.5
		Author: Kathy Darling

	Password Protected
		Version: 2.2.5
		Author: Ben Huson

	Popup Trigger URL for Elementor Pro
		Version: 1.0.1
		Author: Suki WordPress Theme

	Premium Addons for Elementor
		Version: 3.7.9
		Author: Leap13

	Premium Addons PRO
		Version: 1.6.2
		Author: Leap13

	QuadMenu
		Version: 1.9.9
		Author: Mega Menu

	QuadMenu PRO
		Version: 1.8.4
		Author: Mega Menu

	Redirection
		Version: 4.5.1
		Author: John Godley

	Redis Object Cache
		Version: 1.5.5
		Author: Till Krüss

	Simple Custom Post Order
		Version: 2.4.7
		Author: Colorlib

	Ultimate Addons for Elementor
		Version: 1.20.1
		Author: Brainstorm Force

	User Role Editor
		Version: 4.52.1
		Author: Vladimir Garagulya

	Widgets in Menu for WordPress
		Version: 1.0.0
		Author: saurabhshukla, yapapaya

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WPSHAPERE
		Version: 5.0.3
		Author: AcmeeDesign Softwares and Solutions

	WPSOLR PRO
		Version: 20.9
		Author: wpsolr

	wp_upload_rename
		Version: 1.2
		Author: Nolan Chou

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	WP Staging Optimizer
		Version: 1.0
		Author: René Hermenau

== Elements Usage ==
	
	archive : 4
		button : 1
		heading : -7
		shortcode : 1
		theme-archive-title : 1
	footer : 1
		form : 1
		heading : 6
		icon-list : 4
		theme-site-logo : 1
	header : 1
		icon-list : 1
		quadmenu : 2
		theme-site-logo : 1
	jet_single : 0
		jet-listing-dynamic-field : 1
	page : 14
		divider : 2
		dyncontel-doshortcode : 2
		heading : 2
		htmega-accordion-addons : 1
		shortcode : 3
		spacer : 1
		uael-advanced-heading : 1
		uael-dual-color-heading : 1
		uael-infobox : 1
	popup : 3
		button : 2
		heading : 5
		text-editor : 2
	section : 22
		divider : 2
		heading : 11
		jet-engine-booking-form : 1
		jet-listing-grid : 1
		premium-addon-banner : 8
		premium-addon-testimonials : 3
		premium-divider : 1
		shortcode : 4
		text-editor : 3
		theme-archive-title : 1
		uael-advanced-heading : 2
		wp-widget-ht-kb-search-widget : 1
	single : 8
		heading : -50
		htmega-tab-addons : 1
		image : 1
		image-gallery : 1
		jet-listing-dynamic-field : 3
		jet-listing-dynamic-image : 1
		premium-divider : 1
		search-form : 1
		shortcode : -7
		spacer : -7
		template : 1
		theme-post-content : 1
	wp-post : 0
		ae-acf : 4
		ae-acf-repeater : 1
		ae-custom-field : 1
		animated-headline : 2
		button : 1
		divider : 1
		heading : 4
		icon : 1
		icon-box : 2
		image : 1
		login : 1
		premium-divider : 1
		spacer : 2
		template : 1
		text-editor : 6
		uael-advanced-heading : 1
	wp-page : 17
		button : 2
		dyncontel-acfposts : 1
		heading : 6
		htmega-tab-addons : 1
		image : 1
		jet-smart-filters-pagination : 1
		shortcode : 1
		spacer : 22
		text-editor : 11
	jet-listing-items : 0
		divider : 1
		heading : 2
		icon : 1
		jet-listing-dynamic-field : 4
		jet-listing-dynamic-image : 1
		jet-listing-grid : 1
		shortcode : 1
		uael-advanced-heading : 1

== Log ==
	
Log: showing 10 of 102019-10-17 15:59:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-10-19 02:11:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.5',
  'to' => '2.7.2',
)]
2019-10-20 09:44:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.3',
  'to' => '2.7.4',
)]
2019-11-28 23:15:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-11-28 23:16:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-12-12 19:20:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.1',
)]
2020-01-01 10:30:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2020-01-01 10:30:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.2',
)]
2020-01-09 01:08:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-09 01:08:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]

PHP: showing 14 of 14PHP: 2019-10-21 12:36:16 [notice X 2][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-11-18 03:38:52 [notice X 17][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-06 03:38:43 [warning X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(fa-brands-400.eot): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-06 03:38:53 [warning X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(): open_basedir restriction in effect. File() is not within the allowed path(s): (/var/www/vhosts/floordetective.ng/:/usr/lib/php/:/tmp/) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-06 03:43:33 [notice X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::393] Undefined index: prefix [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-14 16:45:45 [notice X 47][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/dynamic-tags/tag.php::53] Undefined index: fallback [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-15 15:58:19 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 201191424) (tried to allocate 38176728 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-30 21:08:38 [notice X 3][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php::1423] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-31 02:46:10 [notice X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::44] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-01 04:18:04 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 209715200 bytes exhausted (tried to allocate 38561304 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-01 10:57:18 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 209715200 bytes exhausted (tried to allocate 38600848 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-01 12:43:50 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 209715200 bytes exhausted (tried to allocate 38556168 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-01 12:43:52 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 209715200 bytes exhausted (tried to allocate 38602128 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-02 11:58:54 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 209715200 bytes exhausted (tried to allocate 38467072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 18 of 18JS: 2019-10-22 03:49:09 [error X 3][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:32:132502] Cannot read property \'html\' of undefined 
JS: 2019-11-18 08:42:54 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.4:2:46150] Cannot read property \'select2\' of undefined 
JS: 2019-11-18 08:49:15 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.7.2:2:45763] Cannot read property \'elementSettingsModel\' of undefined 
JS: 2019-11-30 19:34:53 [error X 5][https://ngfd.ghosttown.io/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/dce-editor-visibility.js?ver=3.0.1:16:9] elementorFrontend is not defined 
JS: 2019-11-30 19:44:53 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.5:2:38717] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `htmega-accordion-addons` got <fa fa-plus-circle> as `accordion_open_icon` value. Expected array or object.',
)]
JS: 2019-11-30 19:44:53 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.5:2:38717] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `htmega-accordion-addons` got <fa fa-minus-circle> as `accordion_close_icon` value. Expected array or object.',
)]
JS: 2019-11-30 19:54:15 [error X 1][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1715\") has already been destroyed and cannot be used. 
JS: 2019-12-01 09:01:10 [error X 1][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view85295\") has already been destroyed and cannot be used. 
JS: 2019-12-01 09:01:10 [error X 1][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view85302\") has already been destroyed and cannot be used. 
JS: 2019-12-06 03:45:28 [error X 1][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:7:20270] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-12-06 04:33:20 [error X 7][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:23:97542] Cannot read property \'name\' of undefined 
JS: 2020-01-01 09:19:57 [error X 28][https://ngfd.ghosttown.io/wp-admin/load-scripts.php?c=0&load=jquery-core,jquery-migrate,underscore,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.2.5:4:30645] Cannot read property \'pageYOffset\' of undefined 
JS: 2020-01-01 15:59:04 [error X 2][https://ngfd.ghosttown.io/wp-admin/post.php?post=1050&action=elementor:1:1] Unexpected token \'<\' 
JS: 2020-01-01 16:01:48 [error X 4][https://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:2:67224] Cannot read property \'getContainer\' of undefined 
JS: 2020-01-02 17:11:20 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/dynamic-content-for-elementor/assets/js/dce-editor-visibility.js?ver=1.5.2:55:64] Cannot read property \'attributes\' of undefined 
JS: 2020-01-05 06:26:02 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/premium-addons-pro/assets/frontend/js/premium-addons.js?ver=1.6.2:894:44] Cannot set property \'className\' of undefined 
JS: 2020-01-05 06:48:54 [error X 2][https://ngfd.ghosttown.io/wp-content/plugins/dynamic-content-for-elementor/assets/js/dce-editor-visibility.js?ver=1.5.2:87:5] dce_enable_save_button is not defined 
JS: 2020-01-10 05:40:09 [error X 5][https://ngfd.ghosttown.io/wp-admin/post.php?post=4515&action=elementor#:5:25] Unexpected token \',\'

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
