### ISSUE TITLE
Modal Popups

### ISSUE THREAD

**Issue by arun369** [elementor/elementor#10110]
Feature request for Modal Popup
Hi Elementor team,
I tried to find a modal popup feature on elementor editor and seems like it doesn't have it. It will be a really great idea to add modal popups which can be opened by clicking/hovering certain elements on the page and can be edited directly on the page.

**Comment by rodolphebertozzo** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @arun369 

Meet our [Popup Builder](https://elementor.com/popup-builder/) - Available in Elementor Pro

Thanks
