### ISSUE TITLE
Drop down menus not working anymore (admin logged in)

### ISSUE THREAD

**Issue by emilsan** [elementor/elementor#10114]
JS console error:
Uncaught TypeError: t.dataSM(...).stop is not a function
    at $.SmartMenus.menuShow (jquery.smartmenus.min.js?ver=1.0.1:3)
    at $.SmartMenus.itemActivate (jquery.smartmenus.min.js?ver=1.0.1:3)
    at jquery.smartmenus.min.js?ver=1.0.1:3

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
Mouse over dropdown meniu (when logged in) generates a javascript error in console.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,

It seems like Smart Menus issue and not Elementor.


Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
