### ISSUE TITLE
Allow wrapping of post title text in Post Navigation widget

### ISSUE THREAD

**Issue by snibbe** [elementor/elementor#10117]
**What problem is your feature request going to solve? Please describe.**
The title text in Post Navigation widget is too small and gets elided, both on desktop and mobile.

Desktop:
<img width="711" alt="prev - next web" src="https://user-images.githubusercontent.com/581517/72180576-4d1ecb80-339c-11ea-9bc4-a15a5310a06d.png">

Mobile:
![IMG_6549](https://user-images.githubusercontent.com/581517/72180642-6d4e8a80-339c-11ea-9c2e-00d4b4c3211d.jpg)

**Describe the solution you'd like**
Allow wrapping of post title text in Post Navigation widget. Here's an example from another site:

web:
<img width="625" alt="mmm web" src="https://user-images.githubusercontent.com/581517/72180854-ecdc5980-339c-11ea-8a69-bde9e3b906c8.png">
mobile:
<img width="331" alt="mmm mobile" src="https://user-images.githubusercontent.com/581517/72180864-f1087700-339c-11ea-8291-6326fb5026f2.png">

**Describe alternatives you've considered**
Don't show title (but users like to see the title of post)
Show image
Allow styling

**Comment by shilo-ey** [comment]
I merged this issue with #9842, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
