### ISSUE TITLE
Dropdown panel disappears when Mobile Menu Breakpoint is set to NONE

### ISSUE THREAD

**Issue by dameer** [elementor/elementor#10113]
Not sure whether the problem came up with the latest release or the one before, however, it's no longer possible to style drop-down menu ( under Style Tab ) if Mobile Menu Breakpoint is set to "none".
So, all the drop-downs have suddenly lost styles!

**Comment by shilo-ey** [comment]
Duplicate of #9948

**Comment by dameer** [comment]
That's just an awesome way of solving problems at Elementor; case closed because that's the duplicate of another unresolved issue. Seriously?!?
I've spent a really nice amount of money (on behalf of my clients) last year on Elementor PRO licenses so thanks for understanding.
