### ISSUE TITLE
✔️ 🐞 Bug Report: Menu Cart Widget > "Hide Empty" ON > indicator bug [ED-8995]

### ISSUE THREAD

**Issue by PauletteM** [elementor/elementor#10111]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

I believe there is a bug related to the cart icon (menu cart widget) because I’ve turned on the « Hide Empty » switch as I don’t want the cart to have an indicator when it’s empty, but now **the indicator never appears** even when the cart is full. 

According to [this doc](https://docs.elementor.com/article/456-menu-cart-widget) it is not supposed to do that. 

## Steps to reproduce

- Edit Menu Cart > Content > Menu Icon > Hide Empty: **YES** > _Cart has just an icon, no indicator_
- Update
- Add items to cart > _Cart is not showing the number of items in it_

**Comment by Mirtzii** [comment]
I'm having the same issue. Did you find a solution @PauletteM ?

**Comment by PauletteM** [comment]
Unfortunately no, the indicator is still not showing at all when I "hide on empty"...

**Comment by ryansymons** [comment]
I'm experiencing this on two websites currently and it's quite frustrating tbh. I'm going to search around and will report back with what I find

**Comment by ryansymons** [comment]
> ## Prerequisites
> * [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
> * [ X ] The issue still exists against the latest stable version of Elementor.
> 
> ## Description
> I believe there is a bug related to the cart icon (menu cart widget) because I’ve turned on the « Hide Empty » switch as I don’t want the cart to have an indicator when it’s empty, but now **the indicator never appears** even when the cart is full.
> 
> According to [this doc](https://docs.elementor.com/article/456-menu-cart-widget) it is not supposed to do that.
> 
> ## Steps to reproduce
> * Edit Menu Cart > Content > Menu Icon > Hide Empty: **YES** > _Cart has just an icon, no indicator_
> * Update
> * Add items to cart > _Cart is not showing the number of items in it_

I opened a ticket with Elementor and they are apparently are aware of the issue and are working on it. Unfortunately they could not supply an ETA so let's hope it's fixed soon

**Comment by ryansymons** [comment]
> Unfortunately no, the indicator is still not showing at all when I "hide on empty"...

I opened a ticket with Elementor and they are apparently are aware of the issue and are working on it. Unfortunately they could not supply an ETA so let's hope it's fixed soon

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.9.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
