### ISSUE TITLE
The "before" and "after" in dynamic drop down should be wider

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#10120]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Easier to read what's in the before and after field. See video here: https://hei.vegardbell.no/v/ggDSLb

**Describe the solution you'd like**
A way to "expand" these fields, or drag them out. The best way is to have bigger/wider/taller fields, so it's easier to see all the text at once.

See video here: https://hei.vegardbell.no/v/ggDSLb

**Describe alternatives you've considered**
Not relevant.

**Additional context**
-

**Comment by shilo-ey** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it.

If you, however, decide to write a patch for it, we'll gladly include it after some code review.
