### ISSUE TITLE
Popup problem

### ISSUE THREAD

**Issue by studiotopo** [elementor/elementor#10122]
I have created a popup to use as a full page menu.
To the popup I have assigned entrance and exit animation (fade in/fade out) with duration of 5 seconds.

By clicking on the menu icon (3 bars) the popup opens correctly, but if I click on the close icon before the 5 seconds animation is finished, the popup goes into fade out and reopens (tested on Chrome and Firefox).

You can try it here: https://studiotopo.com/2020_v1_dev1/

**Comment by drawcard** [comment]
Right now the hamburger menu doesn't do anything. It also stops all scrolling on your site. Maybe create a new popup menu, & recreate your steps to troubleshoot.

Also you probably don't want an animation duration of 5 seconds for something like a fade effect on a menu - it would feel quite sluggish for the user to wait all that time to see the menu. 0.5 seconds is probably a better number :)

**Comment by lior-sh** [comment]
Hi @studiotopo, 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
