### ISSUE TITLE
Uncaught Error: Class 'Group_Control_Typography' not found

### ISSUE THREAD

**Issue by helvetica123** [elementor/elementor#10137]
I am writing a post grid widget.When I add this code, it gives the error:

```
$this->add_group_control(
            Group_Control_Typography::get_type(),
            [
                'name' => 'eael_post_grid_title_typography',
                'label' => __('Typography', 'essential-addons-for-elementor-lite'),
                'scheme' => Scheme_Typography::TYPOGRAPHY_1,
                'selector' => '{{WRAPPER}} .eael-entry-title',
            ]
        );

        $this->end_controls_section();
```

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

I can only guess that you did not import/alias the class in your widget file
see here https://www.php.net/manual/en/language.namespaces.importing.php

**Comment by imranhcoder** [comment]
$this->add_group_control(
            Elementor\Group_Control_Typography::get_type(),
            [
                'name' => 'eael_post_grid_title_typography',
                'label' => __('Typography', 'essential-addons-for-elementor-lite'),
                'scheme' => Scheme_Typography::TYPOGRAPHY_1,
                'selector' => '{{WRAPPER}} .eael-entry-title',
            ]
        );

        $this->end_controls_section();
