### ISSUE TITLE
Updating Controls via Hook Doesn't Fully Work for Responsive Controls

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#10135]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
## Description

I'm trying to hide some of the controls in Column widget via condition.

My goal is to add this extra condition to Column Width control, to hide it, when my custom toggle is set to 'yes':

```
'condition' => [
 	'bleye_custom_column_width_enable!' => [ 'yes' ],
],
```

Here's my code:

```
function bleye_update_column_width_condition( $control_stack, $args  ) {
	// Get existing control
	$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), '_inline_size' );

        // add extra condition
	$control['condition']['bleye_custom_column_width_enable!'] = 'yes';

	// Update the control
	$control_stack->update_control( '_inline_size', $control );
}
add_action( 'elementor/element/column/layout/before_section_end', 'bleye_update_column_width_condition', 10, 2 );
```

It works as expected, when I'm on desktop view (native column width control is gone), but as soon as I switch to tablet or mobile, the control is back:

![obrazek](https://user-images.githubusercontent.com/5634870/72283766-bbcf8380-363f-11ea-9751-9e18d6259de3.png)

This should be some kind of bug, since when I hardcode the condition to the core file for column widget, it works as expected.

Any ideas, why is this happening? Or am I doing something wrong?

And yes, I know the screenshots are not from latests Elementor version - but it's acting the same in the latest version as well.

## Steps to reproduce

See above

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by black-eye** [comment]
Oh, and I forget to add one very important note:

This is happening only for responsive controls. When I use it for basic control (e.g. HTML Tag in Column Widget) it works fine. 

The same goes, when I change `$this->add_responsive_control`  to `$this->add_control` in Column Width definition.

**Comment by bainternet** [comment]
@black-eye 

When a control is added via `add_responsive_control` it actually adds 3 controls (currently) on per each break-point: Desktop, Tablet and Mobile and they are named accordingly:
* Desktop: `control_name`
* Tablet: `control_name_tablet`
* Mobile: `control_name_mobile`

In your snippet, you only update the Desktop control with your condition, and not the tablet and mobile.

if you want to update all of them you can do something like this for example:

```PHP
add_action( 'elementor/element/column/layout/before_section_end', function( $control_stack, $args ) {
	foreach ( [ '', '_tablet', '_mobile' ] as $suffix ) {
		// Get existing control
		$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), '_inline_size' . $suffix );
		if ( ! is_wp_error( $control ) ) {
			continue;
		}
		// add extra condition
		$control['condition']['bleye_custom_column_width_enable!'] = 'yes';
		// Update the control
		$control_stack->update_control( '_inline_size', $control );
	}
}, 10, 2 );
```

Hope this helps.

**Comment by black-eye** [comment]
Thanks, @shilo-ey, this info helped. 
I've just needed to correct your code:
1. The condition for checking the WP error should be without the negation (we should skip the rest of the loop, when there IS an error).
2. The breakpoint suffix should be added to update control as well: `$control_stack->update_control( '_inline_size' . $suffix, $control );`

So, for the others, the final working code is this:
```
function bleye_update_classic_column_width_condition( $control_stack, $args  ) {
	foreach ( [ '', '_tablet', '_mobile' ] as $suffix ) {
		// Get existing control
		$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), '_inline_size' . $suffix );
		if ( is_wp_error( $control ) ) {
			continue;
		}

		// add extra condition
		$control['condition']['bleye_custom_column_width_enable!'] = 'yes';

		// Update the control
		$control_stack->update_control( '_inline_size' . $suffix, $control );
	}
}
add_action( 'elementor/element/column/layout/before_section_end', 'bleye_update_classic_column_width_condition', 10, 2 );
```
