### ISSUE TITLE
Pro gallery images not loaded as background

### ISSUE THREAD

**Issue by Jordidriesen** [elementor/elementor#10133]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Pro gallery uses the image as a background, which prevent's it from loading an image as webp or another next-gen format. This has a negative effect on the Page Speed scores and means it is bad for seo.)

**Describe the solution you'd like**
Images should be loaded as an image, not via a css background image. This way they can be converted and loaded as webp which will increase the sites performance.

**Describe alternatives you've considered**
Gallery plugins which load images in a correct manner.

**Additional context**
Elementor has implemented lazy load techniques to optimize speed, but adding images this way prevents more impactfull solutions which are advised by Google.

**Comment by lior-sh** [comment]
Hi @Jordidriesen,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
