### ISSUE TITLE
Menu Cart widget buttons are linked to home page

### ISSUE THREAD

**Issue by oooh-boi** [elementor/elementor#10148]
1. Add Menu Cart widget to any column
2. Preview in Browser 

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

I am using Hello Elementor theme. Cart and Checkout pages have been created and assigned to the corresponding WooC settings/options (WooCommerce > Settings, Advanced tab > Page setup).
Both "View Cart"  and "Checkout" buttons should be linked to corresponding WooCommerce pages but they are just hyperlinks to the home page.

**Comment by shilo-ey** [comment]
Thanks for reporting,

It seems like a misconfiguration of your WC instance.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by HowulKlodagh** [comment]
I fixed mine by going to the sidebar > woocomerce > setting > advanced > and filling in my pages from the drop-down menus.
