### ISSUE TITLE
Elementor template as PHP

### ISSUE THREAD

**Issue by TheBigBanik** [elementor/elementor#10141]
Hi, does anybody know if Elementor supports export template as PHP? I have created a template and needto load it inside the templates part archive.php so on every new installation of the Hello theme this template will be loaded by default as home page.

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
