### ISSUE TITLE
Elementor adds classes to WooCommerce Cart

### ISSUE THREAD

**Issue by sigersmit** [elementor/elementor#10143]
HI,
I have a website with GeneratePress as thema and WooCommerce shop. By default GeneratePress has it's own mini-cart dropdown, which I like. But, for testing purposes I tried the Elementor WooCart widget. After that, Elementor added classes to the cart which cannot be removed (elementor-menu-cart__product, elementor-menu-cart__product-image) when deleting the Cart button. Even clearing the browser cache, cookies, elementor cache, elementor css etc. didn't work. Only deactivating elementor (Pro) brings back the old mini cart. Turning on Elementor (Pro) brings back the classes, even though the widget is not active and no other Elementor elements. 
How is this possible and more important, how do I remove those unwanted classes?
Thanks.

**Comment by bainternet** [comment]
@sigersmit 

We cant replicate, Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by babakfp** [comment]
Why no one takes care of this **bug!**

**Comment by sigersmit** [comment]
> Why no one takes care of this **bug!**

I think I found the solution for this. Go to Elementor > Settings > Integrations and look for WooCommerce and set it to Disable
![image](https://user-images.githubusercontent.com/25135633/86357729-91fe2d80-bc6e-11ea-96df-cf799cabcef6.png)
