### ISSUE TITLE
The list of widgets is displayed with an error.

### ISSUE THREAD

**Issue by UrchenkoV** [elementor/elementor#10145]
Hello. 

I do not understand why there is a gap between widgets, how to remove it? Look at the screenshot and you can see what I'm talking about.

https://i.postimg.cc/DzDdj7NC/Screen-Shot.png

If you need to see the code to understand it, then here is the plugin where this problem exists https://wordpress.org/plugins/drozd-addons-for-elementor/
This is my plugin, so I'm writing to solve the problem.

Thanks.

**Comment by lior-sh** [comment]
Hi @UrchenkoV,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
