### ISSUE TITLE
Option to use svg's instead of eicons font

### ISSUE THREAD

**Issue by Jordidriesen** [elementor/elementor#10164]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The eicons font isn't the best for loading times and the option to use and svg of choice is available in many widgets. I'm really eager to have this option for the hamburger menu and the video widget.

**Describe the solution you'd like**
Implement the option to choose an svg icon for the widgets where this isn't available yet. Since it can be done for most widgets, it should be easy to implement

**Describe alternatives you've considered**
Overwriting the content with a base 64 image and deqeueing the eicons font.

**Additional context**
Pagespeed and optimization should be a priority and this will help.

**Comment by black-eye** [comment]
+1

**Comment by shimsa** [comment]
+1

**Comment by mr-moto** [comment]
+1

**Comment by lucbas** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue #11361 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
