### ISSUE TITLE
Where can I change the time format for posts?

### ISSUE THREAD

**Issue by 09eric09** [elementor/elementor#10185]
Hello, I am pulling in posts to my homepage and I want to include the date of the post without the year. What file can I change the format to exclude the date when I pull in posts?

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@09eric09 

Simply set the date format in your WordPress admin settings panel
https://wordpress.org/support/article/formatting-date-and-time/

thanks.

**Comment by 09eric09** [comment]
@bainternet 

Yes I understand I can simply change it in WP settings, however I do not want it to reflect on the entire site. I want to change the time for one query on the home page. 

Say if I were coding a template and included <?php echo  get_post_time('F j, Y', true,$newspost['ID']); ?>

How would I do this in Elementor?

**Comment by 09eric09** [comment]
*included get_post_time('F j, Y', true,$newspost['ID']);
