### ISSUE TITLE
Grid Sorting by custom field - BB has it, why doesn't Elementor?

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#10184]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tickyboom** [comment]
Hello

Elementor needs to have sorting by custom fields for their post modules and worked into the core. Beaver Builder has this implemented (see screenshots). As it is now we have to use a separate plugin to do sorting or else we would be dead in the water on a project.

Also here is the response we got from a 3rd party module maker on this issue:
"Thanks for sharing that, That is beaver builder and those are builder's custom fields to sort by that. We really loved what they did and It's worth adding in elementor. But, That is completely extended level for sorting, We will need to do research on that further and look at possibilities with elementor's existing group controllers.  "

Please, please!

<img width="1005" alt="Screen Shot 2020-01-08 at 3 24 55 PM_552" src="https://user-images.githubusercontent.com/43012405/72632942-421fea00-390c-11ea-8d53-1161055b3505.png">
<img width="1001" alt="Screen Shot 2020-01-08 at 3 26 16 PM_533" src="https://user-images.githubusercontent.com/43012405/72632943-42b88080-390c-11ea-83f3-ee5a2323fb68.png">

**Comment by bainternet** [comment]
@tickyboom 

Currently, this can be done via a [custom query filter](https://developers.elementor.com/custom-query-filter/) ex:

```PHP
// Showing posts ordered by comment count in Posts Widget
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	// Here we set the query to fetch posts with
	// ordered by post meta
	$query->set( 'meta_key', 'my_meta_key' );
	$query->set( 'orderby', 'meta_value' ); // for numeric meta use `meta_value_num` instead of `meta_value`
} );
```

Hope this helps.

**Comment by tickyboom** [comment]
Hi - thanks for the response. Can this be implemented in the frontend? This is a common behavior that most people using Elementor and CPT's will use, plus both BB and Oxygen (as far as I know) have this built in. 

Thanks!

**Comment by yonahs** [comment]
I agree with @tickyboom that adding this feature to the front end would be great.
But my question is, how can I sort by multiple custom fields?

**Comment by ckunderd** [comment]
This would be great to have!
