### ISSUE TITLE
How to change the "Background" control types "title" and "icon"

### ISSUE THREAD

**Issue by fazleyRabbiRana** [elementor/elementor#10187]
How can I change the "Background" control types "title" and "icon"?
![image](https://user-images.githubusercontent.com/60033053/72662573-f441d980-3a12-11ea-9c7d-59ac8e7edfa3.png)

Like, I want to change the "Classic" types title to "Solid" and icon to "fa fa-square".
NOTE: I want to change that for only one specific control, other Background controls will remain unchanged.

Is it possible, if yes then how?

**Comment by bainternet** [comment]
@fazleyRabbiRana 

It is possible by extending the `Group_Control_Background` control and overite the  
`get_background_types` to return the choose options with the icons you want. 
https://github.com/elementor/elementor/blob/21ff6df09eec1f0a0cee1ae2993ba97ade66a562/includes/controls/groups/background.php#L70-L76

or you can simply update the control `background` with the icons you want for that specific background control instance.

Hope this helps.
