### ISSUE TITLE
[Feature Request] - Display Background Fallback if Video cannot load

### ISSUE THREAD

**Issue by glanglois** [elementor/elementor#10186]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor (Elementor Pro)

**What problem is your feature request going to solve? Please describe.**
Currently if a background video cannot be loaded (bandwidth issue, hosting issue, etc.), there is an error message that is displayed. This can seriously damaged the perception of the website.

**Describe the solution you'd like**
It would be interesting to:
- Be able to load the background fallback if the video cannot be loaded due to an issue
- Be able to setup a notification (mail?) if the background fallback had to be displayed instead of the background video, sending in Error Message Type and TimeStamp.

Thank you.

**Comment by jmedia123** [comment]
<img width="322" alt="Screen Shot 2020-09-03 at 10 14 32 PM" src="https://user-images.githubusercontent.com/40833413/92191747-88da3a00-ee32-11ea-9bb2-fad83ec71bb7.png">
Looks like they have this feature.

However, for some reason if I do upload a picture for the fallback I lose formatting of the Global Fonts I set up in Elementor. Very strange. Searching on here to see if someone else has encountered this as well as submitting a support ticket.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
