### ISSUE TITLE
Popup positioning - IE11.1184.17134.0

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#10182]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by tickyboom** [comment]
Hello,

Using a popup as a full-screen menu. You can view how it works here: https://worldmedicalinnovation.org/

On IE11.1184.17134.0 the popup does not work really well - is there a fix for this? I have attached a screen to show the popup on IE.

I can get you log in credentials if you need it.

**Comment by muazzami** [comment]
for anyone looking to fix popup positioning, this worked for me across browsers.
use this in the custom css of popup settings.
`selector .dialog-widget-content{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}`

**Comment by DorShahar** [comment]
Hi
We are [officially not supporting IE](https://developers.elementor.com/elementor-dropping-support-ie/).
We are suggesting to update to the latest version (I know this post is from ~8 months ago, apologize for the delay)

Thanks
