### ISSUE TITLE
Portfolio module on IE11.1184.17134.0

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#10183]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by tickyboom** [comment]
Hello,

Using the 'Portfolio Module' to pull in Speakers on this site: https://worldmedicalinnovation.org/ and scroll down a bit. 

On IE11.1184.17134.0 the grid is basically broken. Is there a fix for this?

I can get you login credentials if you need them.

**Comment by Aviad-Herman** [comment]
Hi,
IE is no longer supported
