### ISSUE TITLE
Log-in widget

### ISSUE THREAD

**Issue by trevose** [elementor/elementor#10199]
If a user enters an incorrect log-in I would like to be able to direct them to a website (non-private) page rather than to the standard wordpress log-in form

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bainternet** [comment]
Duplicate of #5355
