### ISSUE TITLE
SVG Icon with colour overlay don't display properly

### ISSUE THREAD

**Issue by NaughtyGoose** [elementor/elementor#10195]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Trying to use my own SVG file as Icon in the Icon-Box Widget. Objects with native colour display properly
Elements that have been exported with layer overlay colour don't show up - or with wrong content or with native (but wrong) colour. The SVG File displays properly in the preview window and in many other applications.

## Isolating the problem
Supposed to look like this:
![Original](https://user-images.githubusercontent.com/58230326/72684017-27509f80-3add-11ea-81e8-0337059a34d3.png)

This is the SVG file that will not display properly (exported from the same source):
[AD Test3.zip](https://github.com/elementor/elementor/files/4082877/AD.Test3.zip)

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@NaughtyGoose 

Check your CSS classes and Id's that they are not overwriting each other, for example in the svg you provided it has a `use` element
`<use xlink:href="#_Image1" x="346.549" y="50.679" width="166.08px" height="166.08px" transform="matrix(0.994491,0,0,0.994491,0,0)"/>`

which in turn uses `<image id="_Image1" width="167px" height="167px" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKcAAACnCAYAAAB0FkzsAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAB1UlEQVR4nO3SIQEAIADAMMDTPy4kQHOxJbj4HGefAUHrdwC8mJMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5yTInWeYky5xkmZMsc5JlTrLMSZY5ybo7tgNZJ/FguAAAAABJRU5ErkJggg=="/>` (green by the way)

So if you have another SVG in that same page which has a `<use>` element that calls the same ID (`_Image1`) it will use this same image, and if you happen to have another `<image>` element again with the same id (`_Image1`) it will overwrite all calls of that ID.

hope this helps.

**Comment by NaughtyGoose** [comment]
I'll check that ... thx for the answer!
