### ISSUE TITLE
Icon Block: Not all (new) Font Awesome Icons selectable

### ISSUE THREAD

**Issue by EdwardBlack** [elementor/elementor#10203]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I select the icon module in elementor (pro page builder), I get a list with many icons, but recently released icons are missing (like the starfighter https://fontawesome.com/icons/starfighter-alt?style=light).

## Steps to reproduce

- Go to any elementor page
- Add icon module
- Click icon library
- Search for starfighter
= no starfighter icon found

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

- I have not activated Font Awesome 4 fallback
- I have clicked all icons
- I have a pro license (Elementor & Font Awesome)
- The page uses the right .js / kit
- On the Font Awesome Backend kit is configured to use 'latest'

**Comment by shilo-ey** [comment]
Hi @EdwardBlack 

Our Icon Library currently includes Font Awesome 5.11. this icon was added in v5.12 (about a month ago)

We are constantly upgrading our Icon Library, and will in the upcoming future.

Thanks
