### ISSUE TITLE
Duplicating inner sections doesn't do anything on 2.8+

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#10205]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

![Screenshot_1](https://user-images.githubusercontent.com/60075863/72688103-da84bd00-3b0c-11ea-8926-87d0d78cc4e0.png)

I have this structure. If I right click on the selected inner section and click on duplicate, nothing happens. I cannot duplicate anymore. I can only duplicate the first inner section right below the section. I have to do this on a WP installation with a version of Elementor before 2.8 then export and import the template with how many nested inners I need in order to make the layout I want. This used to work just fine before updating to 2.8. This version broke a lot of stuff that was working just fine before.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @azkalex 

We can't reproduce your issue. 

Please make sure you've updated your plugin to the latest version (Elementor v2.8.4)

If that doesn't work for you, please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to Hello Theme (or other default WordPress theme).


And see if the issue still persists.

Thanks
