### ISSUE TITLE
Elementor 2.8.4 problem

### ISSUE THREAD

**Issue by pblazevski** [elementor/elementor#10206]
Dear sirs, I updated my Elementor, the version 2.8.4 and now I can not edit my web page. The editor does not load at all. 
I tried to disable all the plugins, and changed the theme, but nothing changes. 
I must roll back the previous version to continue with the work.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
