### ISSUE TITLE
HOW TO STYLE ELEMENTOR PRO TOOLTIP FOR THE NAV MENU?

### ISSUE THREAD

**Issue by KoniKodes** [elementor/elementor#10200]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description
I would like to see the title when I hover over the nav item, but not with that box...
How can I fix this?

## Steps to reproduce
Hover over a nav menu item that has a title. 
The title will show inside a box with a solid dark border and sharp corners - dark text on white background.

I have tried to create a css class tooltip and make it light tan with rounded corners and white font. However, the ugly black box is still there. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

```
</details>
![image](https://user-images.githubusercontent.com/18405001/72685312-cc4b8800-3a9d-11ea-9a3b-ecbfffea5465.png)
![image](https://user-images.githubusercontent.com/18405001/72685314-d4a3c300-3a9d-11ea-8214-b84d5a432483.png)
![image](https://user-images.githubusercontent.com/18405001/72685323-f604af00-3a9d-11ea-877d-00af9633b7f8.png)

**Comment by KoniKodes** [comment]
![Menu-Title](https://user-images.githubusercontent.com/18405001/72685375-64e20800-3a9e-11ea-91de-cc23c49e9135.png)
![NavMenu-widget](https://user-images.githubusercontent.com/18405001/72685376-66133500-3a9e-11ea-8fcc-d70c031da345.png)
![tooltip](https://user-images.githubusercontent.com/18405001/72685378-67dcf880-3a9e-11ea-9804-ce7253f45e9a.png)

**Comment by euene** [comment]
The title tooltip is part of the native UI of the web browser which will be different across browsers and can't be changed via CSS or any other way.
