### ISSUE TITLE
Custom SVG are not loaded

### ISSUE THREAD

**Issue by papilia** [elementor/elementor#10213]
Hi there,
i have a problem with your custom icon uploads, i'm using this plugin https://github.com/humanmade/S3-Uploads to upload every single external file of my sites in amazon s3 and distribute it in cloudfront, it ever worked with elementor but unmounting your code (abstract class Icon_Set_Base) it seems the way you're calculating upload and extraction folders in this specific case are based on server relative paths... naturally there are actions and filters to correct it, but i would love to see it working in a more "generic" way without the needs of creating another theme or plugin to let it work. Could you please check? You can find the error.log screenshot attached.
Thanks

![Screenshot_6](https://user-images.githubusercontent.com/9718447/72715518-e4400c00-3b70-11ea-859f-fb30ca89181a.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/9718447/72718128-98439600-3b75-11ea-94fb-14edcd386021.jpg)

**Comment by lior-sh** [comment]
Hi @papilia,

It should work with an SVG file, not a ZIP file.
Thanks.
