### ISSUE TITLE
Image Carousel Widget - Slides to Show option for Tablet breakpoint doesn't work

### ISSUE THREAD

**Issue by euene** [elementor/elementor#10227]
I'm opening a new issue, since my previous issue #9659 got closed but the bug hasn't been fixed yet and it can be easily reproduced despite the comment that @shilo-ey made.

## Prerequisites

- [x] have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

"Slides to Show" option on Image Carousel widget doesn't work on the Tablet breakpoint.

## Steps to reproduce

Create an image carousel widget. 

Go to "tablet" breakpoint view and adjust the "Slides to Show" option number - the result is that no matter what number is selected, only 1 slide will be shown always. 

The "Slides to Show" works as expected on desktop and mobile breakpoints - so it's only the Tablet breakpoint that doesn't work and the number isn't reflected in the Elementor editor as well as on the front-end of the site.

<img src="https://user-images.githubusercontent.com/6027160/69495567-0733a400-0ed1-11ea-9de1-5914daa56e6e.gif" alt="elementor-bug-carousel" style="max-width:100%;">

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Elementor 2.8.4<br>
Elementor Pro 2.8.3<br>
Hello Elementor 2.2.2<br>
PHP 7.3.13<br>
</details>

**Comment by PremiumCoding** [comment]
The same issue when creating a custom widget with Swiper. Breakpoints don't work. Maybe you should update the Swiper since last version is 5.3.x and you are using 4.4.6.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.2

Feel free to update

Thanks!
