### ISSUE TITLE
Dynamic accordion 

### ISSUE THREAD

**Issue by Yonimantin** [elementor/elementor#10223]
Hello
I would like to ask for a feature request to be able to create a dynamic accordion (for FAQ page for example) maybe by using the ACF repeter 
 tools.
Thanks

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/5979 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
