### ISSUE TITLE
Unable to style Dropdown layout of the Nav Menu widget

### ISSUE THREAD

**Issue by oooh-boi** [elementor/elementor#10238]
I already wrote about this problem but the issue was closed swiftly without any reasonable explanation.

With the Nav Menu widget, you can select 3 different Layouts: Horizontal, Vertical and Dropdown.

Dropdown layout is the only one that DOES NOT ALLOW ANY STYLING so all menu items look like the default page text and which doesn't make any sense.

Here's what I am talking about: https://imgur.com/a/9LJLlNh

Please don't just shut me out, I'm dealing with multiple clients, all of them use Elementor to build/maintain their websites and all of them ask me to solve the problem which is obviously Elementor related.

Thanks!

**Comment by shilo-ey** [comment]
Hi @oooh-boi 

Thanks for your feedback, 

This was already reported and fixed, will be released soon: #9948

Thanks
