### ISSUE TITLE
Elementor Pro Gallery - Multiple gallery not working with newest Elementor version

### ISSUE THREAD

**Issue by Netzlichter** [elementor/elementor#10249]
## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Latest WordPress (5.3.2), Elementor (2.8.4) and Elementor Pro (2.8.3), Hello Elementor Version: 2.2.2.

Multiple Pro gallery isn't working anymore. There are multiple ;) design issues.

Please check my screenshots attached:
https://www.dropbox.com/s/m3ynpafsqdi3i6n/01-pro-gallery-widget.jpg?dl=0
https://www.dropbox.com/s/m7mx5edh7yj45if/02-pro-gallery-widget.jpg?dl=0
https://www.dropbox.com/s/0it9wflos98hfbn/03-pro-gallery-widget.jpg?dl=0
https://www.dropbox.com/s/ujgyuj1j220pro4/04-pro-gallery-widget.jpg?dl=0
https://www.dropbox.com/s/fx2j7rpgm17mksb/05-pro-gallery-widget.jpg?dl=0

**Comment by shilo-ey** [comment]
Hi @Netzlichter 

Thanks for your feedback.

We can't reproduce your issue from the details you provided.

I suggest you to create a new issue with all the missing information (system info, steps to reproduce) or, by being a Pro user you are entitled to premium support, so you can create a support ticket and one of our supporters will try to troubleshoot your issue.

Thanks.

**Comment by saawood13** [comment]
I am having this issue currently. My multigallery is not loading on iphones
