### ISSUE TITLE
Editable Column Structure Settings

### ISSUE THREAD

**Issue by aerynlynne** [elementor/elementor#10257]
**Prerequisites**
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.  (Please note: I searched for "structure" - no idea what else this issue would be termed.)
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve?**
I find that I use structure settings for columns often that are not part of Elementor's defaults.

For instance, the default setting for four columns is 25, 25, 25, 25.

![column structure settings](https://user-images.githubusercontent.com/55590768/72917389-c231bf80-3d11-11ea-8c11-f8a5781e7123.png)

I'm **frequently** using 17, 33, 33, 17 - enough so that it's becoming painful to continue inputting these numbers now.

**Describe the solution you'd like**
It would be great if we could add our own presets for column structures. OR, if 17, 33, 33, 17 could be added to the four column preset for the next update, I would be entirely grateful.

Thanks for your time! :)

**Comment by Aviad-Herman** [comment]
Hi,
Thanks for the suggestion.
Currently we are not planning of adding new structures but you can always create a template and insert it wherever you like :)
