### ISSUE TITLE
Gallery Pro - Lazy Load doesn't work if Media Folder's name contains a space

### ISSUE THREAD

**Issue by hexhamhistorian** [elementor/elementor#10256]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I've media items in a folder whose name contains a space (Apache server). Pro galleries can be constructed to use these images, but with Lazy Load enabled, the thumbnail of images in that folder do not appear (thumbnails of images in other folders with no spaces in their name do appear), although the Title and Caption associated with the image are displayed when the mouse cursor hovers over the blank space where the image should be. With Lazy Load disabled, the thumbnails appear correctly.

The media items are properly registered in the system.

Example page:  https://www.hexhamhistorian.org/historic-hexham/photograph-archive/hlhs-photo-archive/hexham-buildings-photo-archive/hexham-beaufront-castle-gallery/

## Steps to reproduce
Upload a media items to a folder created under wp-content/uploads with a space in the folder's name. (NB: You cannout use the Media Library Add New to do this.) Include that image in a Pro Gallery, with Lazy Load enabled.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Already reported to Elementor support.  They say " It is more a feature request but also a compatibility issue."

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @hexhamhistorian 

Could you please explain the way you added those items (with custom path) to the lightbox?

thanks

**Comment by hexhamhistorian** [comment]
Hi shilo-ey:

I used FTP to upload the .jpg images to the site, into the folder created with a space in its name.

Then the plugin [Media from FTP](https://wordpress.org/plugins/media-from-ftp/) to create the registered Media items in that folder for those uploaded .jpg files.

I then added the Media images to an Elementor Pro Gallery through the normal method.  I haven't knowingly used the lightbox directly.

**Comment by hexhamhistorian** [comment]
Hi shilo-ey:

Sorry - I clicked the close button in ignorance!

I used FTP to upload the .jpg images to the site, into the folder created with a space in its name.

Then the plugin [Media from FTP](https://wordpress.org/plugins/media-from-ftp/) to create the registered Media items in that folder for those uploaded .jpg files.

I then added the Media images to an Elementor Pro Gallery through the normal method.  I haven't knowingly used the lightbox directly.

**Comment by Netzlichter** [comment]
I have the same strange issues with gallery pro. Some images are not loaded in Elementor edit view too.

https://github.com/elementor/elementor/issues/10249

What I did? I moved the site from one server to another. You can see the site here live:

https://www.wvleinefelde.de/wohnen/wohnquartiere/ (hover over one box and click on „mehr Informationen“.

Best,

Tobi

**Comment by shilo-ey** [comment]
@hexhamhistorian If you try to upload images to a folder without spacing and import them to your gallery (using the specified plugin and not in the orthodox method of uploading media) - will it work? or the issue will persist?

Thanks

**Comment by Netzlichter** [comment]
Im in contact with the pro support. They got a website clone from me with the problem...

**Comment by hexhamhistorian** [comment]
Yes, images imported from a folder named without a space work fine in the gallery. The example page given earlier illustrates this precisely. The blank spaces in the thumbnail gallery are the media items in a folder with a space in its name ("CDallison PostCards"); those that appear are in a folder named without spaces. Both sets of media items were uploaded using the same plugin.

Thanks.

**Comment by shilo-ey** [comment]
Hi @hexhamhistorian 

Thanks for your feedback,

After inspecting your report and understanding your issue, I want to set some facts in order:

- WordPress Media Upload/Library mechanism not allowing users to upload media files indirectly
- In addition, when providing spaces, WordPress will convert them to dashes (`-`)
- You are using 3rd Party addon which overrides this mechanism

We will consider adding support for this issue, but this repository is not the proper place to report it.

Please report your issue in e-gallery repository (due to the fact that it's an external resource): https://github.com/elementor/elementor-gallery/issues

Thanks

**Comment by hexhamhistorian** [comment]
Hi @shilo-ey:

Thanks for the information. I'll have to get rid of that folder with spaces in its name and recreate the galleries.

I'd just point out that the _only_ thing I've found that didn't work with that folder is the lazy-load option with your galleries. Everything else seems happy with finding images in that folder, including all of the Word Press mechanisms. 

Regards.

**Comment by mahdimadineh** [comment]
I have the same problem. The name of folder also is in persian language and have space in it.
