### ISSUE TITLE
Feature Request: Background slideshow to support ACF / Pods gallery

### ISSUE THREAD

**Issue by pixelxcode** [elementor/elementor#10251]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Have been looking for an ACF gallery widget that will allow us to put static text as the slides change. Allowing background slideshow to connect with ACF / Pods gallery will help so much!

**Describe the solution you'd like**
Allow us to select an ACF / Pods Gallery when setting a background slideshow

**Describe alternatives you've considered**
Smart Slider 3 (doesn't support custom field gallery), ACF frontend gallery

**Additional context**
N/A

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #5760, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
