### ISSUE TITLE
Products Widget Equal Height of Content

### ISSUE THREAD

**Issue by datascientistgonzo** [elementor/elementor#10263]
I use pictures in different sizes and titles with different lengths: editions-schortgen.lu
To make it look better I would like to arrange the picture, title price and button so that they are evenly spread. For example the Button should be always at the same height.
As far as I know, this feature does not yet exist on Elementor. Can you provide custom CSS to make it look better until then?

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
