### ISSUE TITLE
🔗 🚀 Feature Request: Form File Upload Security/Automated Deletion (Duplicate of #4868)

### ISSUE THREAD

**Issue by bodhi1970** [elementor/elementor#10273]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
on one of the websites I made for a client the users are uploading sensitive data via the file upload widget in a contact form (medical information).
By law in EU and Switzerland only doctors and the pharmacists from my client are allowed to see this data. Right now, the data ist stored in a folder on the server and I empty this folder once a months.

**Describe the solution you'd like**
Scheduling automatic deletions or ensuring attachments are not stored.
More security and automatised deletion of the files after a certain time.

**Describe alternatives you've considered**
File also goes to client via email redirect in the form. Can it be only an attachment and not be stored on the server?

**Comment by arielk** [comment]
Duplicate https://github.com/elementor/elementor/issues/4868

**Comment by nicholaszein** [comment]
Hey there @bodhi1970!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
