### ISSUE TITLE
Feature Request - Featured Video, Audio/anything

### ISSUE THREAD

**Issue by GOvEy1nw** [elementor/elementor#10274]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In blog/portfolio grids it would be great to be able to have a featured video or audio or gif etc instead of just a featured image. This seems to be done well by Uncode which you can see here: https://undsgn.com/uncode/blog/blog-boxed-masonry/#

This feature would allow us to have more dynamic blogs/portfolios.

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
