### ISSUE TITLE
Mysterious white space on mobile site

### ISSUE THREAD

**Issue by cocodesalazar** [elementor/elementor#10277]
I'm experiencing mysterious white space to the right of my content on mobile site when you zoom out: [www.cocodesalazar.com](www.cocodesalazar.com). i can't emulate the problem in a desktop browser so i'm wondering if your team has any idea what's wrong. I have disabled plugins, switched the theme, updated wordpress, elementor, and all plug ins. nothing seems to help. 

![IMG_0403](https://user-images.githubusercontent.com/60248288/73043882-1c777100-3e35-11ea-9421-c50dbfb0ecb7.jpg)

**Comment by Aviad-Herman** [comment]
Try to hide all sections using the Navigator (eye icon on hover) and then un-hide them one by one until you find the problematic DIV. After you find it, make sure to select overflow hidden.

If the problematic elements does not have this option, add in in custom CSS.
