### ISSUE TITLE
Cross-Site-Scripting (XSS) possible elementor-system-info page.

### ISSUE THREAD

**Issue by Impenetrable** [elementor/elementor#10283]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This is an authenticated reflected XSS, that was found possible to bypass filters and thus obtain cookie information (depending on CORS policies, WAFs etc).

This issue was tested on the latest 2.8.4 version and confirmed still vulnerable.

When loading the elementor-system-info page via Wordpress, it is possible to append HTML and therefore JavaScript to the end of the URL query, thus breaking out of the HREF within the id "elementor-usage-recalc".

## Steps to reproduce

1. Login to Wordpress

2. Append payload to URL in following format:

`/wp-admin/admin.php?page=elementor-system-info&%22%3e%3cscript%3ealert(1)%3c/script%3e
`

This is the same payload but with the URL decoded:

`/wp-admin/admin.php?page=elementor-system-info&"><script>alert(1)</script>`

This will cause the alert popup box to appear twice (rendered in two locations). The images below show the JavaScript rendered in page.

**Rendered in Elements Usage:**

![image](https://user-images.githubusercontent.com/47977341/73089398-0c5fa000-3ece-11ea-8a3d-b66956c291cb.png)

**Rendered in Log:**

![image](https://user-images.githubusercontent.com/47977341/73089424-21d4ca00-3ece-11ea-9800-ee256bc6d604.png)

**Proof of JavaScript execution:**

![image](https://user-images.githubusercontent.com/47977341/73089556-6b251980-3ece-11ea-92c7-21c25fb24995.png)

It was also possible to bypass some of the filters to create more damaging payloads, such as:

- Spaces were substituted with an underscore, this was possible to bypass using the %0c (form feed) encoded character.

- Some filtered characters reappeared after double encoding. For example, to display the square bracket [ it was possible to input %5b%5b (square bracket twice) and it would render a single [ to the page.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Debian)
	MySQL version: Debian buildd-unstable v10.3.20
	PHP Version: 7.3.12-1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: REDACTED
	Home URL: REDACTED
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

== Active Plugins ==
	BuddyPress
		Version: 5.1.2
		Author: The BuddyPress Community

	Elementor
		Version: 2.8.4
		Author: Elementor.com

	WP File Manager
		Version: 15.2
		Author: N-Media


== Elements Usage ==
	
	wp-post : 0
		button : 1
		google_maps : 1
		spacer : 1
		tabs : 1
		testimonial : 1
		text-editor : 1


== Log ==
	
Log: showing 1 of 12020-01-24 10:02:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
```

</details>

**Comment by shilo-ey** [comment]
Thanks, Fixed in this commit and will be released soon: https://github.com/elementor/elementor/commit/4c26c36b0d7cbbfbe1c0e6cb4307da59451f8459
