### ISSUE TITLE
Posts widget pro : custom query filter on multisite "switch_to_blog"

### ISSUE THREAD

**Issue by calzbert** [elementor/elementor#10284]
Hello

i'm reading this post https://developers.elementor.com/custom-query-filter/ to write my custom query filter.

i have WordPress multisite. My site principal (1) is the corporative web. My site number 2 is "the blog".
i write my custom query filter like this:

`// Posts or Portfolio Widget
add_action( 'elementor/query/my_tlg_filter_blog', function( $query ) {

switch_to_blog(2);
$query->set( 'post_type', 'post' );
$query->set( 'post_status', 'publish' );
$query->set( 'orderby', 'post_date' );
$query->set( 'order', 'DESC' );
$query->set( 'posts_per_page', 4 );

restore_current_blog();

} );`

but NO work.
can you help me? 
it is possible to write a custom query like “ $query->set(‘blog_id’, ‘2’) “ to get the query to read posts from another site of a WordPress multisite

thanks!!

**Comment by guyvellacott** [comment]
Hi did you get an answer to this? I’m looking to do the same thing. Thanks !!

**Comment by calzbert** [comment]
Hi!
Yes, they answered me via the support of their website.
they told me that was not possible.

I ended up writing a custom php and inserting it with a shortcode inside the Elementor template.

**Comment by guyvellacott** [comment]
Hi Albert,

Thanks for the quick feedback.  Any chance you could send me the custom photos you wrote so that I can take inspiration from it?  It would be so helpful if you could.

Many thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by calzbert** [comment]
hi!
yeah , of course!
i can share with you my shortcode code. i hope this help you!

https://paste.ofcode.org/LFWuzH6xjbrvminYG3PTcR

**Comment by realpash** [comment]
Hi @calzbert !

I have exactly the same problem,
Can you repost the code you use to solve this problem ?
The link you shared doesn't work anymore.

Thanks a lot !

**Comment by calzbert** [comment]
hi !

of course:  https://paste.ofcode.org/nyCnMNkU3E4ajcYbRpmg5u

**Comment by realpash** [comment]
Thanks, works well !

**Comment by rolfmblindgren** [comment]
Could you please post the code? The links you point to expire :)

Thank you :)

**Comment by ginanjaritsnain** [comment]
> 
> 
> hi!
> here: https://paste.ofcode.org/W4ACa38PdByzNVjeHxACWW

hai @calzbert, could you please post the code again? all of these link is expire.

Thank you.

**Comment by calzbert** [comment]
hello
yes, of coure:


`function kt_function_blog2_filter($query_args){
         switch_to_blog(2);
         global $post;
         // global $wp_query;
          $query_args['post_type'] = 'post';
          $query_args['post_status'] = 'publish';
          $query_args['orderby'] = 'post_date';
          $query_args['order'] = 'DESC';
          $query_args['posts_per_page'] = 4;
    
         // wp_reset_query();
         // wp_reset_postdata();
         restore_current_blog();
            return $query_args;
     }
add_filter('kt_blog2_filter', 'kt_function_blog2_filter');
`

**Comment by nickelnext** [comment]
Any luck with this? Looks like it does not work at all, because Elementor "clears" the query.

It looks like there's no filters or actions to hook into that could work with a multisite installation.

Most likely a hard customization would require to rewrite 

`$query = new \WP_Query( $this->query_args );// SQL_CALC_FOUND_ROWS is used.`
on line 63 of 
`elementor-post-query.php` in `modules\query-control\classes`

with something like

`$query = new \WP_Multisite_Query($this->query_args)`

having used 

`$query->set(‘blog_id’, ‘2’)` or similar.

But I don't want to fork elementor-pro just for this. I hope there's a cleaner way

**Comment by socenpauriba** [comment]
Hi there!

SOLUTION HERE!

`add_action( 'elementor/query/my_custom_filter', function( $query ) {

    // Temporarily switch to the blog with ID 3
    switch_to_blog(3);

    // Modify the query to fetch posts from blog ID 3
    $query->set( 'post_type', [ 'post' ] );
    
    // Use a hook to restore the original blog after the Elementor widget has been processed
    add_action('loop_end', function() {
        restore_current_blog();
    });

});
`
