### ISSUE TITLE
Redirect form with multiple checkbox data

### ISSUE THREAD

**Issue by Rivess** [elementor/elementor#10282]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I would like to redirect form with data. Using url in redirect action after submit: https://mypage.com/page/create?email=[field id="email"]&checkbox[]=[field id ="multiple_checkbox"]&username=[field id="username"]

If i choose more then one value from my checkbox, only first value is send and after that nothing more, so username field from example above won't be send.

Is there special way to send multiple checkbox values? Am I missing something? Or is it just bug?

Thanks for any advice and help.

## Steps to reproduce

Create form field checkbox with multiple options and try to send them in redirect action after submit in url like described earlier.

**Comment by rami-elementor** [comment]
@Rivess Multiple checkbox returns an array, not a string. You can't use it in a URL.

Alternatively try use several single checkboxes and place them in the URL.
