### ISSUE TITLE
Video widget: Support for YouTube permanent live video URL

### ISSUE THREAD

**Issue by sukafia** [elementor/elementor#10289]
Hi,

the video widget currently doesn't detect a YouTube permanent live video URL as a YouTube video. The permanent URL is just like a live YouTube video URL except that it doesn't change. e.g `https://www.youtube.com/channel/channelID/live`

Here's an example with a real live URL https://www.youtube.com/channel/UCyUKtrMdDilf74SPkCCKKtw/live
The above URL plays a live YouTube video whenever the channel is live. 

Here's what the embed code for a permanent live URL looks like
`<iframe width="560" height="315" src="https://www.youtube.com/embed/live_stream?channel=UCyUKtrMdDilf74SPkCCKKtw&rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>`

Embedding the above codes ensure one doesn't have to copy and embed a new code each time the channel goes live. 

If the YouTube permanent live URL is detected as a YouTube video source in the Elementor video widget, that'll ensure one can just put the URL as the video source and the channel's latest live video will play automatically when the channel is live.

Kindly look into this. Thanks

**Comment by arielk** [comment]
Unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue but you can use embed/html widget for that. If we add the options in the future, we'll try to update here.

Thank you for your feedback!
