### ISSUE TITLE
Links do not have a discernible name

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#10293]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This problems is similar to issue #10189.

I passed all widgets and found some, where combination with image and custom URL is causing accessibility issue.

## Steps to reproduce

Choose image and set custom URL.

<b>Icon Box widget</b>

![icon-box](https://user-images.githubusercontent.com/7617350/73139442-55e6f100-406e-11ea-8dad-05e5ebdba021.png)

Google Lighthouse report (SVG icon)

![icon-box-svg](https://user-images.githubusercontent.com/7617350/73139278-a9583f80-406c-11ea-99f0-33bde6122126.png)

Google Lighthouse report (Font Awesome icon)

![icon-box-font-awesome](https://user-images.githubusercontent.com/7617350/73139279-ac533000-406c-11ea-97b3-0428c91c8f3a.png)

<b>Icon widget</b>

![icon](https://user-images.githubusercontent.com/7617350/73139446-5da69580-406e-11ea-9043-d30478c2d6f6.png)

Google Lighthouse report (SVG icon)

![icon-svg](https://user-images.githubusercontent.com/7617350/73139319-37342a80-406d-11ea-90c9-e07efc2e9fd6.png)

Google Lighthouse report (Font Awesome icon)

![icon-font-awesome](https://user-images.githubusercontent.com/7617350/73139332-56cb5300-406d-11ea-82e4-e2971cf943cb.png)

<b>Gallery widget</b>

![gallery](https://user-images.githubusercontent.com/7617350/73139449-639c7680-406e-11ea-84cc-d9e928b6e7ca.png)

Google Lighthouse report

![gallery-image](https://user-images.githubusercontent.com/7617350/73139349-78c4d580-406d-11ea-9313-08aa91246205.png)

<b>Media Carousel widget</b>

![media-carousel](https://user-images.githubusercontent.com/7617350/73139385-e1ac4d80-406d-11ea-8d02-8c757d7bf71b.png)

Google Lighthouse report

![media-carousel-image](https://user-images.githubusercontent.com/7617350/73139386-e53fd480-406d-11ea-8a3b-64a4fb309916.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @shimsa 
Thanks for your feedback.

Using Custom Link Attributes feature you can determine your own settings to your `<a>` tags.

Read more here: https://docs.elementor.com/article/445-custom-attributes

**Comment by ThorinEk** [comment]
Hello! I am having a similiar issue. Lighthouse complains about no name for the Post Card thumnail image `<a>` tag.
![Skärmbild 2021-01-07 141909](https://user-images.githubusercontent.com/36575668/103897556-0c16df80-50f4-11eb-94c3-020f35ac9148.jpg)

I am trying to add the `aria-label` attribute to the `<a>` tags to solve this, however, I can only add attributes to the surrounding container element. I am not able to edit anything in the post cards themselves, date format for an example. I am trying to add the attributes from this guide https://elementor.com/help/custom-link-attributes/ but that guide has no illustrations and I can not find the options and buttons described in the guide. Is it even possible to to this with elementor?
![Skärmbild 2021-01-07 141924](https://user-images.githubusercontent.com/36575668/103897967-89daeb00-50f4-11eb-9d89-e0b546622434.jpg)

**Comment by yincheng0819** [comment]
> Hi @shimsa
> Thanks for your feedback.
> 
> Using Custom Link Attributes feature you can determine your own settings to your `<a>` tags.
> 
> Read more here: https://docs.elementor.com/article/445-custom-attributes
@shilo-ey 
same here, I was trying to add alt text to <svg> tag, but custom attribute can only add to wrapper div.
![Screenshot 2021-05-04 at 4 16 21 PM](https://user-images.githubusercontent.com/40515940/116977175-b4c8fa80-acf4-11eb-9333-f161a8bb8fa2.png)

**Comment by thejeromelouis** [comment]
same, I was trying to add an aria-label tag, but custom attribute can only add to wrapper div

**Comment by heychowdary** [comment]
This still seems to be an issue, I have just checked my website [HowdyGermany](https://howdygermany.com/) for Google Page Speed insights and this is one of the recommendation.

```
Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users. [Learn more](https://web.dev/link-name/?utm_source=lighthouse&utm_medium=lr).

Failing Elements

div.elementor-widget-wrap > div.elementor-element > div.elementor-widget-container > a
```

**Comment by heychowdary** [comment]
> Hi @shimsa Thanks for your feedback.
> 
> Using Custom Link Attributes feature you can determine your own settings to your `<a>` tags.
> 
> Read more here: https://docs.elementor.com/article/445-custom-attributes

This link doesn't seem to be active anymore :|

**Comment by WebRat45** [comment]
Has anyone found a fix yet? Lighthouse/PSI still doesn't give a perfect Accessibility score because of the "Links do not have a discernible name" warning for the Elementor Icon Boxes etc.

**Comment by psybrbr** [comment]
I'm having the same "problem" with the "loop-grid" images. I'm using it as "Related posts".

In this case your solution is partial, as there are 6 related posts and their images.

Any solution to insert something like "post-image-(POST-ID-HERE)" ?


![screenshot-pagespeed web dev-2023 06 19-23_11_21](https://github.com/elementor/elementor/assets/54563040/77263479-2bb6-4f13-8dc3-7e6f378bf213)

> edit: I've found a solution;
> Adding Custom Attributes in the selected widget -> aria-label|your text here

**Comment by eoanodea** [comment]
I'm also now running into this issue, has there been any update on it?

**Comment by easysports** [comment]
same

**Comment by eoanodea** [comment]
@shilo-ey can we re-open this issue?

**Comment by jonathansoltero** [comment]
Try adding aria-label|namehere to the Custom Attribute section under the Content tab (not in the Advanced tab)
