### ISSUE TITLE
Global Image Widget - Broken Link

### ISSUE THREAD

**Issue by aeleus** [elementor/elementor#10292]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
Create Image Widget and make it global.
Insert Global Widget into a page. It looks normal.
Save page and close it.
View page: it looks normal.
Open page to edit. There is a broken link where the image should be.
Save page and view it. It looks normal.
The broken link is only visible when editing the page. Otherwise, it works as expected.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) PHP/7.3.10
	MySQL version: MariaDB Server v10.4.11
	PHP Version: 7.3.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: http://www.website.com
	Home URL: http://www.website.com
	WP Multisite: Yes
	Max Upload Size: 0 B
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Vantage
	Version: 1.14.4
	Author: SiteOrigin
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71

== Active Plugins ==
	Black Studio TinyMCE Widget
		Version: 2.6.9
		Author: Black Studio

	Category Posts Widget
		Version: 4.9.2
		Author: TipTopPress

	Check Email
		Version: 0.5.6
		Author: Chris Taylor

	Custom Sidebars
		Version: 3.2.3
		Author: WPMU DEV

	Latest Posts Widget
		Version: 1.1
		Author: Mrinal Kanti Roy

	Max Mega Menu
		Version: 2.7.3
		Author: megamenu.com

	Media Library Folders for WordPress
		Version: 5.1.6
		Author: Max Foundry

	Page Builder by SiteOrigin
		Version: 2.10.13
		Author: SiteOrigin

	Redirection
		Version: 4.6.2
		Author: John Godley

	Rotating Tweets (Twitter widget & shortcode)
		Version: 1.9.9
		Author: Martin Tod

	Sidebar Widgets by CodeLights
		Version: 1.4
		Author: CodeLights

	Simple Download Monitor
		Version: 3.8.3
		Author: Tips and Tricks HQ, Ruhul Amin, Josh Lobe

	SiteOrigin CSS
		Version: 1.2.4
		Author: SiteOrigin

	SiteOrigin Widgets Bundle
		Version: 1.15.9
		Author: SiteOrigin

	Smart Slider 3
		Version: 3.3.26
		Author: Nextend

	Social Media Widget
		Version: 4.0.6
		Author: Noah Kagan

	WP Statistics
		Version: 12.6.12
		Author: VeronaLabs

	Yoast SEO
		Version: 12.8.1
		Author: Team Yoast

== Network Plugins ==
	All In One WP Security
		Version: 4.4.2
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.8.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Enable Media Replace
		Version: 3.3.7
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 3.7.1
		Author: WPDeveloper

	HTTP / HTTPS Removal
		Version: 3.1
		Author: Steve85b

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

== Elements Usage ==
	
	popup : 7
		image : 5
		social-icons : 5
		text-editor : 15
	section : 1
		image : 1
		wp-widget-maxmegamenu : 1
	wp-page : 10
		divider : 16
		eael-flip-box : 68
		eael-testimonial : 7
		global : 5
		heading : 1
		image : 20
		image-carousel : 6
		spacer : 9
		text-editor : 69
		wp-widget-maxmegamenu : 10

== Log ==
	
Log: showing 20 of 212019-09-10 20:47:49 [info] elementor::elementor_updater Started 
2019-09-10 20:47:49 [info] Elementor/Upgrades - _v_2_7_0_rename_document_types_to_wp Start  
2019-09-10 20:47:49 [info] Elementor/Upgrades - _v_2_7_0_rename_document_types_to_wp Finished 
2019-09-10 20:47:49 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-10 20:47:49 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-10 20:47:49 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-10 20:47:50 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-10 20:47:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.7.1',
)]
2019-10-04 23:32:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.1',
  'to' => '2.7.3',
)]
2019-10-12 12:25:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.3',
  'to' => '2.7.4',
)]
2019-10-12 12:25:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.3',
  'to' => '2.7.4',
)]
2019-12-03 13:47:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-12-03 13:47:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.4',
  'to' => '2.7.5',
)]
2019-12-11 19:30:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.1',
)]
2019-12-19 13:59:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2020-01-20 19:57:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.4',
)]
2020-01-20 19:57:36 [info] elementor::elementor_updater Started 
2020-01-20 19:57:36 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-20 19:57:37 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-20 19:57:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.4',
)]

JS: showing 3 of 3JS: 2020-01-08 19:06:20 [error X 4][http://www.website.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:7:20398] Cannot read property \'removeClass\' of undefined 
JS: 2020-01-08 19:12:56 [error X 1][http://www.website.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.2:2:110209] Cannot read property \'addElementFromPanel\' of undefined 
JS: 2020-01-12 20:52:46 [error X 1][http://www.website.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view16979\") has already been destroyed and cannot be used. 

PHP: showing 1 of 1PHP: 2020-01-21 01:23:32 [notice X 4][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/query-control/module.php::359] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
				
</details>

**Comment by Aviad-Herman** [comment]
Hello,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by aeleus** [comment]
Currently running Elementor Pro 3.3.1 and the bug no longer manifests.

Thanks

**Comment by Aviad-Herman** [comment]
Thank you @aeleus
