### ISSUE TITLE
Expand the Role Manager for Editors with "change background images"

### ISSUE THREAD

**Issue by Barns-be** [elementor/elementor#10294]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

 I would like to have background images added to the list of items that can be changed under Role Manager restrictions for Editors (currently restricted to text and image widget content). My clients want to change section background images (or sliders) (only the image - not other section settings).
 It would also be logical to my client that they can change ALL images, including one that is used as a background.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9891, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
