### ISSUE TITLE
Elementor 2.9.0-beta1 => Bug and some feature requests

### ISSUE THREAD

**Issue by beziehungsweise** [elementor/elementor#10319]
Hi,

just testet out the new 2.9.0-beta1 and would like to give some feedback:

**1) BUGS**
Elementor won't load if Rank Math plugin in active. See attached screenshot
![Rank Math bug](https://user-images.githubusercontent.com/60393817/73271619-30c6bf80-41e1-11ea-8745-6eb7901ac07b.png)

**2) FEATURE REQUESTS FOR THEME STYLES**

_a) Button Styles_
In the Button Widget we do have FIVE presets to choose from (default, information, success, danger, ...), which is really great. In the new button theme styles we can set a default button layout, but ONLY FOR the default button design, not for the other 4 button presets. Could you please add the possibility to style the other 4 button presets as a global design set too?

_b) Section / Inner Section / Columns / Widgets => Missing in Theme Styes_
Concering the theme styles there is one BIG thing left at the moment, which is setting global defaults for margins and paddings for:
=> sections
=> inner sections
=> rows
=> columns
=> widgets

It should be possible to set every top/bottom/left/right margins or padding in px / % / em / rem / vw, ... on it's own. this would really be helpful and could for sure be implemented quite easy. Could you please add global styling support for these parts of elementor. This is still heavily missing in Elementor. The new theme styles would be the perfect place to set these defaults.

Thanks and best regards
Michael

**Comment by black-eye** [comment]
Confirming RankMath conflict.

**Comment by godvsgodvs** [comment]
Yes Rank Math conflict and this is right after Rank Math integrated into the Elementor editor. This is very important to resolve early.

**Comment by beziehungsweise** [comment]
Found another bug today: Columns padding have not been visible in the Elementor backend, but have been correct on the frontend. Clean install with Hello theme and no plugins activated. Rolled back to 2.8.3 (or 5?) solved the problem!

**Comment by shilo-ey** [comment]
Hi @beziehungsweise 
Thanks for your feedback.

We are in contact with RankMath developers to resolve this conflict from their side. 

As for the feature requests, the beta phase is for bug reports only. we continue to work on the features until RC will be released soon,

Thanks!

**Comment by LuisEduardoPS** [comment]
@shilo-ey Are the Elementor integrated with RankMath?

It is always showing "Focus Keyword not found in subheading(s) like H2, H3, H4, etc.." in RankMath, but they are.

So I found an RankMath staff member saying that it is something that the theme builder theme should add in their code and update. (https://rankmath.com/kb/content-analysis-api/).

So, is it due some update that this bug is happening?
