### ISSUE TITLE
auto fill check box in form field via url / query strings

### ISSUE THREAD

**Issue by Kingfilly13** [elementor/elementor#10310]
Hi there,

I am a Elementor Pro user. Im struggling with the following issue; its regarding the dynamic option for a form field. I have a checkbox field that i would like to give visitors the opportunity to pre select there choice from another page on the website. Normally I use wpforms for this with the 'query var' option. so i can create a custom url with query strings. but in the form element of Elementor I just can't get it done. I hope some of devs can help me out with this feature.
maybe it needs a bit of code to get it done. 

These are the settings that I have tried:

So the dropdown consists of 3 items: (its in Dutch)
'Basic pakket'
'Compleet pakket'
'Pro Pakket'

i selected 'request parameter' in the Advanced tab and than selected 'query var' and as parameter i gave the name 'package'

Each input field is labeled as followed:
Basic pakket|basic1
Compleet pakket|compleet1
Pro Pakket|pro1

whenI tried to test the function to preselect via a link doesn't work.
An example of the link that I tested is:
pagelink/?package=pro1

Am i missing something? Aren't my settings right?

Hope to hear from you guys on short notice.

**Comment by rami-elementor** [comment]
Hi @Kingfilly13 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
