### ISSUE TITLE
Only load CSS of used widget 

### ISSUE THREAD

**Issue by folusuk** [elementor/elementor#10329]
All widgets script + css fully optimized and now load when that widget enable and have in that page.

like in element pack
https://bdthemes.com/products/wordpress-plugins/element-pack-change-log/

4.0.0 [2nd November 2019]

**Comment by black-eye** [comment]
+1

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #14429, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
