### ISSUE TITLE
Fatal error: Call to undefined function primer_the_custom_logo()

### ISSUE THREAD

**Issue by createprint** [elementor/elementor#10330]
I am new to wordpress and elementor but i build a site using wordpress and elementor. i recently face the error message when i type my site url. https://traintreats.co.uk as below:
===================================
Fatal error: Call to undefined function primer_the_custom_logo() in /home/printsmith59/public_html/traintreats.co.uk/wp-content/themes/primer/templates/parts/site-title.php on line 13
=======================================

Can any one point me right direction to solve this problem please?

**Comment by lior-sh** [comment]
Hi @createprint,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
