### ISSUE TITLE
Login Widget - Redirection by role

### ISSUE THREAD

**Issue by PawanjitAhluwalia** [elementor/elementor#10335]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need to be able to redirect users logging in to my site to different landing pages by role.

**Describe the solution you'd like**
In the login widget options, I would like to be able to type in the URL where the user is redirected to based on user role.

**Describe alternatives you've considered**
I am currently using another plugin that does this. However, if this feature could be incorporated into Elementor then I could remove that plugin.

**Comment by arielk** [comment]
Long time, but unfortunately I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future we'll try to update here.

Thank you for your feedback
