### ISSUE TITLE
Role based popups

### ISSUE THREAD

**Issue by PawanjitAhluwalia** [elementor/elementor#10337]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need to create popups by user roles on certain pages.

**Describe the solution you'd like**
I would like a role condition added to the current list of conditions. So I would like to display a popup based on an AND situation - e.g. (the current page is X) AND (the user role is Y).

**Describe alternatives you've considered**
I am not aware of any other popup plugin that does this.

**Comment by emeraldsama** [comment]
I believe you're looking for "display condition" functionality. There are a few plugins that can do this with Elementor.

Check out Elementor Extras here. You can use their display conditions settings + their pop-up widget to display only on certain pages and user roles. https://shop.namogo.com/elementor-extras/extensions/display-conditions/

PAFE/Pionet's Conditional Visibility may also work for you. https://pafe.piotnet.com/docs/conditional-visibility/

**Comment by PawanjitAhluwalia** [comment]
Thank you. These may be good solutions for now. However, going forwards, it would be good if this request could be a core part of Elementor itself rather than an addon.

**Comment by PawanjitAhluwalia** [comment]
I have tried two visibility functionality plugins. These do not work in the way I have specified. These do not "trigger" popups based on the role and page. As far as I can see, these merely hide or make visible content based on conditions. So, what happens is the popup will still trigger. Elements in the popup can be made visible or hidden based on conditions. That is not what I want. I want to control the popup trigger conditions.

**Comment by emeraldsama** [comment]
Are you using Elementor Pro Popups or the Elementor Extras (EE) Popup widget? As previously stated for Elementor Extras (EE) display conditions to work, you need to use the EE popup widget, **not** the native popup in Elementor Pro under Templates -> Popups. 

If you use the Elementor Pro popup, it will still trigger and display an empty popup. This is probably what you experienced.

With EE display conditions using the EE popup widget, the pop up won't trigger at all if the display conditions are not met.

**Steps to Recreate:**
1. Place the EE popup widget in the header* (or footer, I presume) so it can trigger across the whole site by [is/is not] page condition. (*Assuming you have 1 header applied for the site.)
2. Set your display conditions under the "advanced" tab.
3. Set the popup trigger to "instant" if you want it to appear automatically when the user/page display conditions are met.
4. (TIP!) Set the EE popup content 'type' to 'Template' to still build/style your popup content with Elementor.

This works for me, and my display conditions include date, page, and user role.

![not here](https://user-images.githubusercontent.com/4933651/73496335-57722b00-4386-11ea-824c-8066800a383a.png)
![use this widget](https://user-images.githubusercontent.com/4933651/73496334-57722b00-4386-11ea-95f1-b6305528e7ef.png)

**Comment by PawanjitAhluwalia** [comment]
Thank you for this.

Could you please provide me a bit more help.

So, I have placed the EE popup widget on a page and assigned conditions to the "section". Is this the correct element to assign conditions to? Or do I assign conditions to the the popup widget itself?

Then I'm a bit confused where to place this. You mentioned placing it in the header or footer so that it is there for the entire site and the conditions will ensure when it is visible - is this correct? However, if there is already an elementor header being used, do I just place the popup below this? I don't want it actually affecting the existing header.

Also, which element do I style if a want to add a border to the popup? - the section, column or the popup widget?

I would be grateful if you could clarify these points.

Many thanks!

**Comment by emeraldsama** [comment]
This is all off the top of my head, so I might not have it exactly right. If you bought a license for EE, you can open a support ticket for assistance. I'm sure they can explain the setup process better than I can!

1. Assign display conditions to the EE popup widget itself, not the container it's placed in.
2. I just dropped it right into my existing Elementor header template, in an existing column/section below my other content. I had to set the Widget Space under Column -> Layout to 0, or it added a little space to my design. (You could probably use negative margin to correct this as well.) The popup widget you see on the backend should not appear or add any space on the frontend with these settings. I assume if you make a new container for the popup widget, then it will add space and mess up your design.
3. Border would depend on your popup design and if you're using Text content type or Template content type in the popup. I'd try placing it on the EE popup widget -> Styles tab -> Popup tab first, and if that's not the look you want then apply border style to the popup template section or column. Play around with it.
4. Final tip - I had white space around the edge of the popup after setup was complete using the Template content type. If that's a problem you experience, you'll need to set padding/margin (I forget which one, or if it's both) to 0 on the EE popup widget advanced tab to remove this blank space and have your template fill the whole popup space.

I would love to see this native to Elementor, but for now this is a decent workaround. Hope that works for you.

**Comment by PawanjitAhluwalia** [comment]
Thanks for this. I have also submitted a support ticket. Let's see what they say.

**Comment by DorShahar** [comment]
Hi 
Sorry for the late reply.
We are planning to work on a new condition mechanism that will allow you to use AND & OR with various logics.

I'm merging this issue with #6899 for easy tracking.

Thanks
