### ISSUE TITLE
Custom Dynamic Tags

### ISSUE THREAD

**Issue by dimaeromin97** [elementor/elementor#10331]
Hello dear developers of the wonderful plugin Elementor)

I have a question:
Since you implemented the "Dynamic Tags" functionality in Elementor Free, can I create my own custom "Dynamic Tags" in my Elementor add-ons, even without activating Elementor Pro?

**Comment by arielk** [comment]
Maybe it's too late, but you can learn more about dynamic tags here: https://developers.elementor.com/dynamic-tags/

Thanks
