### ISSUE TITLE
Downloaded the new Beta 2.9 Elementor and had problems with the links on my pages. When I hover over them they would enlarge to 4 times what it is supposed to be. I thought it might be a plugin issue. Turn out, when I roll back the Beta Elementor it works fine now. Just a heads up.

### ISSUE THREAD

**Issue by ajm62** [elementor/elementor#10349]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
