### ISSUE TITLE
Page not viewing properly until refreshing

### ISSUE THREAD

**Issue by austinlerbs** [elementor/elementor#10348]
Hi there,

I have recently activated WordPress' native password protect page feature, and I have noticed that it has affected the way that the page is seen by a user. Once I enter the password for the particular page, the contents doesn't display properly until I refresh the page.

The page that I am experiencing the issue with is here:
https://rbs-tops.com/newsletter001/

**Comment by lior-sh** [comment]
Hi @austinlerbs,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
