### ISSUE TITLE
Downloaded the new Beta 2.9 Elementor and had problems with the links on my pages. When I hover over them they would enlarge to 4 times what it is supposed to be.

### ISSUE THREAD

**Issue by ajm62** [elementor/elementor#10347]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by zeinnicholas** [comment]
Buddy, you should have commented directly into #10323 as we suggested at the [Elementor Community Group](https://www.facebook.com/groups/Elementors/?multi_permalinks=2524946877631083&comment_id=2524951530963951&notif_id=1580336848285955&notif_t=feedback_reaction_generic). Can you please had to #10323 and post your issue there as a comment?

Thanks!
