### ISSUE TITLE
Elementor Popups (inside WordPress) closes unexpectedly

### ISSUE THREAD

**Issue by tomas-eklund** [elementor/elementor#10355]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This is a minor issue, but an annoyance that might trip people up (as it did me). It happened three consecutive times before I realized what might be going on.

In the WP backend, on the Elementor > Tools > Version Control page under "Become a Beta Tester" there's a "Click here" link which opens a popup for subscribing to the Beta Updates channel. If you use the mouse to select a part of the e-mail address in order to change it, and if after making your selection you happen to release the mouse button just _outside_ of the popup, the popup will close.

If this behavior also happens on user-built forms (haven't tested myself) it might lead to lost conversions.

It's an edge case, I know. But still...

## Steps to reproduce

See above, or the attached screen capture.

![elementor-subscribe-popup-3](https://user-images.githubusercontent.com/1409791/73450860-8e384900-4366-11ea-922d-85004e7b3111.gif)

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by Ersonusaini** [comment]
Elementor Pro Form make dynamic as devices Input Size and change icon before Custom Messages
after submit form

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!
