### ISSUE TITLE
Add Dynamic to Price Table Widget 

### ISSUE THREAD

**Issue by crazypsycho** [elementor/elementor#10359]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently you can´t set title, description, button text and additional info with dynamic tags.
Only price can set dynamic.

**Describe the solution you'd like**
It would be very nice to have dynamic tags in these fields, so it can be used in a template and filled dynamically.

**Additional context**
![grafik](https://user-images.githubusercontent.com/12948745/73530641-31e23180-4419-11ea-882c-34a0670131b6.png)
![grafik](https://user-images.githubusercontent.com/12948745/73530726-4c1c0f80-4419-11ea-8241-834e42e543a9.png)
![grafik](https://user-images.githubusercontent.com/12948745/73530764-5fc77600-4419-11ea-97ba-1c8aeb6a0735.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
