### ISSUE TITLE
Expand Role Manager to Restrict Theme Builder 

### ISSUE THREAD

**Issue by imagesgroup** [elementor/elementor#10363]
- [ x] I have searched for similar features requests and found a similar issue in #4206. I posted there but have not received a response so perhaps my idea differs. I will expand on it here.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I believe it would be beneficial to allow site owners to limit certain **User Roles** further. While elementor is easy to use the front-end menu can confuse certain users when the **Edit with Elementor** has drop-downs for Globals, Archive, Single. Plus I don't always want my editors to be able to change a global header and have break something globally.

**Describe the solution you'd like**
A simple checkbox within the *Role Manager* to allow site builders to limit the display of Elementor's **Theme Builder** features such as Globals (header/footer), Archive, Single and Product.

**Describe alternatives you've considered**
I have a site built using CPT & ACF. I use Elementor's **Theme builder** to display these custom posts. The blog editor only needs to edit the standard posts without even touching Elementor. 

I tried restricting them from using "No access to editor" which helps somewhat but they can still view items via the Theme builder and damage the site by deleting them. This method also limits them from Editing simple pages via Elementor.

**Additional context**
![Edit with Elementor](https://user-images.githubusercontent.com/13333928/73550782-1db02b80-443d-11ea-8549-237e6334a154.png)

**Comment by shilo-ey** [comment]
I merged this issue with  #1314 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
