### ISSUE TITLE
Elementor popup gravity form not working

### ISSUE THREAD

**Issue by phillipaust** [elementor/elementor#10367]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

i put a contact gravity form in popup content, popup runs well but when the form is submitted the form doesn't provide a response (there is no success message/or if a required field is missed there is no error message). here an example: https://www.kronenhirsch.com/gravityform-popup/

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @phillipaust,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by anurag-kalita** [comment]
Hi @phillipaust , have you found the solution to this issue?

**Comment by thorsolutions** [comment]
https://community.gravityforms.com/t/gravity-forms-doesnt-work-inside-elementor-popup/3813

Gravity forms is saying they can't help and that this is probably an Elementor issue.
