### ISSUE TITLE
$e.run( 'document/save/update' )

### ISSUE THREAD

**Issue by sinashamsizadeh** [elementor/elementor#10366]
Hi,
I will be face with a problem in version 2.9.0. Can you share an example for use
`$e.run( 'document/save/update' )`
I see below warning in console
`update` is soft deprecated since 2.9.0 - Use `$e.run( 'document/save/update' )` instea

**I didn't find any document in this regard.**

current code is
`				elementor.settings.page.addChangeCallback('show_header', function (newValue) {
					elementor.saver.update({
						onSuccess: function () {
							$.ajax({
								action: 'save_builder',
								complete: function () {
									elementor.reloadPreview();
									elementor.once('preview:loaded', function () {
										elementor.getPanelView().setPage('page_settings');
										$e.route('panel/page-settings/settings');
										$('.tipsy').remove();
									});
								}
							});
						}
					});
				});`

**Comment by beratgashi** [comment]
Hi @sinashamsizadeh,

Can you share your code to help "us" the others?

**Comment by SewoSew** [comment]
I posted a solution here #10610 https://github.com/elementor/elementor/issues/10610#issuecomment-2419063833
