### ISSUE TITLE
Call to action: Dynamic Ribbon Content

### ISSUE THREAD

**Issue by stephan1996** [elementor/elementor#10364]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
https://github.com/elementor/elementor/issues/4767 = similar
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am using the CTA to display my posts in an overview, using a loop. 
The problem is, I can not mark certain posts with a ribbon. 

**Describe the solution you'd like**
To solve this it would be nice to see the availability to add dynamic content into the ribbon.
No content = no ribbon
Content = show ribbon on the CTA

**Describe alternatives you've considered**
No alternatives known. Would like to stick to the main widgets from elementor pro.

**Additional context**
![CTA Feature request](https://user-images.githubusercontent.com/20606281/73567499-c6bf4c00-4466-11ea-982c-a50e974156bd.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.0

Feel free to update

Thanks!
