### ISSUE TITLE
Share icon displaying icon ID

### ISSUE THREAD

**Issue by shroomers88** [elementor/elementor#10369]
As you can see in the below screenshot, I've used the "share post" widget and changed the icons using CSS. It works just fine in Elementor, but once I move to the live version of the website (out of the builder), you can see the logo doesn't show. Instead, the font awesome icon ID that's in the CSS code appear.

https://www.screencast.com/t/PKr9ml95

Here's the CSS code I'm using:

.fa-linkedin:before{
content: "\f0e1"
}

.fa-facebook:before{
content: "\f39e"
}

Elementor support told me to deactivate the cache plugin, but that's not a viable solution since I need cache enabled. How can I make sure the customized share icon I've added are displayed in the live version of the website?

**Comment by shilo-ey** [comment]
Hi @shroomers88 

Try regenerating your CSS files by going to WP dashboard > Elementor > Tools > Regenerate CSS Files.

In addition, try rebuilding your cache files.

This is not Elementor related issue.

Thanks

**Comment by shroomers88** [comment]
Hi @shilo-ey 

I've tried what you mentioned. But it doesn't work.

I regenerated the CSS files and emptied cache from WP, the server and the CDN. It doesn't work.

Anything else I could look at to have this working? Can a dev fix this? If so, how?

**Comment by shroomers88** [comment]
I don't know if I can still get help while this post is mentioned as closed. So I'll open a new one, knowing I've applied everything you've said, but it still doesn't work. I've also contacted my host (Siteground, which told me to contact you back).
