### ISSUE TITLE
2.9.0-beta2 Column Width field glitch

### ISSUE THREAD

**Issue by seanvandermolen** [elementor/elementor#10371]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- 					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: Percona Server (GPL), Release '9', Revision '53e606f' v8.0.18-9
	PHP Version: 7.2.26-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://dev2.denvercarpetandflooring.com
	Home URL: https://dev2.denvercarpetandflooring.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/Denver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.0-beta2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com


== Must-Use Plugins ==
	WP CLI Login Command Server
		Version: 1.2
		Author: Evan Mattson


== Elements Usage ==
	
	header : 1
		button : 2
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 4
		button : 1
		heading : 6
		image-box : 3
		slides : 1
		text-editor : 2


== Log ==
	
Log: showing 2 of 22020-02-01 19:18:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.8',
  'to' => '2.8.3',
)]
2020-02-01 22:57:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.0-beta2',
)]


				 -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Beta issues only in beta thread

Thanks.

**Comment by seanvandermolen** [comment]
I put that all in.  If GitHub screwed up the submission that sucks.  Too busy to do it again.   But it is a bug look into it.

Get Outlook for Android<https://aka.ms/ghei36>


SEAN VANDERMOLEN

Office:(775) 954-0710
Direct:(775) 325-5489
www.techpad.biz
MEETING CUSTOMER REQUIREMENTS IS A DAILY JOB
EXCEEDING THEM IS WHAT MAKES US DIFFERENT
This email and any attachments are strictly confidential and may be protected by legal privilege.  If you are not the intended recipient, be aware that any disclosure, copying,  distribution or use of this email or any attachment is STRICTLY PROHIBITED. If you have received this email in error, please notify us immediately by returning it to the sender and delete this copy from your system. Thank you for your cooperation (v.25)
________________________________
