### ISSUE TITLE
Can I get repeater item index in title_field ?

### ISSUE THREAD

**Issue by AbanobAkram** [elementor/elementor#10372]
Hi there :wave: 

I'm trying to create an Elementor widget including a repeater option, so I'm trying to add a text/icon for title_field, but I'm not able to append the item index to that. So, may I ask if there's any workaround for that ?

Please check the code below for more clarification

`$this->add_control('my_repeater',
            [
                'label'         => __('Repeater', 'premium-addons-pro'),
                'type'          => Controls_Manager::REPEATER,
                'fields'        => array_values( $repeater->get_controls() ),
                'title_field'   => 'Repeater Item:  index <i class="{{control_id}}"></i> '
            ]
        );`

Thanks,
Abanob

**Comment by dali-rajab** [comment]
I need this functionnality too,

![image](https://user-images.githubusercontent.com/39015823/123670030-aac70200-d834-11eb-8832-871d61c192b1.png)

i want my list to be like : 

- video 1
- video 2
- video 3

Instead of

- item 1
- item 2
- item 3

**Comment by amitsarker89** [comment]
Use this

'title_field' => '{{{ elementor.helpers.renderIcon( this, icon, {}, "i", "panel" ) || \'<i class="{{ icon }}" aria-hidden="true"></i>\' }}}',
