### ISSUE TITLE
Multisite shared templates and settings

### ISSUE THREAD

**Issue by TheBigBanik** [elementor/elementor#10400]
Hi, I would really like to see in the future versions of Elementor pro a multisite feature that can manage and share templates from the main site to all subsites. The feature must have the following settings in approach:
1. Save a template from the main site as a multisite template.
2. Select inside the subsite if multisite template will be allowed (many subsites maybe don't have to follow the same design)
3. Changes in the multisite templates must also be automatically updated in the subsites.
4. If 3 is not possible, maybe there should be an export-import function that we can select from the network settings in which subsites this templates will be imported.
5. If main site cannot create multisite templates then the network settings must have this option.
6. Since the beta version 2.9 will introduce the global theme style, it would be nice to have a multisite theme style (if subsites load the same theme of course)

That's all for now. I hope you take all this under consideration to help us create more amazing websites with Elementor.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/1225 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
