### ISSUE TITLE
Add Border Hover to Image widget

### ISSUE THREAD

**Issue by badcat** [elementor/elementor#10408]
Would be nice to have animated effects for Color, Width and Radius on the Image widget's border.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
