### ISSUE TITLE
I need an item to be displayed after filling out a form.

### ISSUE THREAD

**Issue by monkychilote** [elementor/elementor#10415]
Hi, good morning. Ask a question on the official channel of elementor and Rizwan, I indicated that this channel could help me.

Thank you. The query you make is as follows.

I am building a template of single products, within this template I have an element that calls a "Listing Grid", which calls a dynamic element that makes the call to safety data sheets. It works very well since I have created a personal CPT where I create each security sheet and in this template I am calling through a "post query" of the post type by ID, using the following code:% related_children_from | safety_sheet%, up to everything is fine there. Now I need you to show me this element only if you fill out a form with data that identifies the person before they show me the download links found in this listing grid.

Very grateful for your suggestions. Thank you

**Comment by rami-elementor** [comment]
Hi @monkychilote ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
