### ISSUE TITLE
Iconmoon Elementor Custom Icon NOT WORKING

### ISSUE THREAD

**Issue by Gionny996** [elementor/elementor#10411]
I need to load the icons on elementor with the original colors (multicolor) so I uploaded them to my iconmoon account, but when I import the SVG.ZIP file it loads the icons but in reality the file is empty and there is nothing there internal. If I do the same thing with Fontastic instead it works, but obviously not monochromatic and not good. How can I solve this Iconmoon problem?

iconmoon: http://prntscr.com/qxn72s
fontastic: http://prntscr.com/qxn7db

**Comment by shilo-ey** [comment]
Hi @Gionny996 
Thanks for your feedback.

You might use the same prefix/font name which causes this conflict.

Try setting a unique prefix/name and upload again.

Thanks.
