### ISSUE TITLE
[FEATURE REQUEST] Elementor 2.9 => 4 Button variations missing in beta

### ISSUE THREAD

**Issue by beziehungsweise** [elementor/elementor#10412]
FEATURE REQUEST FOR THEME STYLES

**Button Styles**
In the Button widget we do have FIVE presets to choose from (default, information, success, danger, ...), which is really great. In the new button theme styles we can set a default button layout, but ONLY FOR the default button design, not for the other 4 button presets. Could you please add the possibility to style the other 4 button presets as a global design set too?

Thanks and best regards
Michael

**Comment by Infestix** [comment]
I have to agree. Lack of this featue is quite annoying.

**Comment by arielk** [comment]
Duplicate of #965
