### ISSUE TITLE
Elementor Videos don't recognize Playsinline Custom Attribute

### ISSUE THREAD

**Issue by mattaguirre29** [elementor/elementor#10426]
I'm trying to make an Elementor video play inline on mobile browsers. I'm able to accomplish this using pure HTML, but I haven't found a way to structure the key|value pair so that Elementor recognizes this custom attribute.
Here is the code that I used to successfully create an inline video on mobile:
`<figure class="wp-block-video"><video controls src="https://staging1.ingoodhealth.co/wp-content/uploads/M1.mp4" Playsinline></video></figure>
`
Here is an image of the HTML code working correctly. This video plays in line on mobile.
<img width="914" alt="HTML Video" src="https://user-images.githubusercontent.com/60714630/73881361-085c4800-4815-11ea-8035-f691c9b95d0b.PNG">

Here is the Elementor video player widget with video|Playsinline in the Custom Attributes:
<img width="932" alt="Video Player with Attribute" src="https://user-images.githubusercontent.com/60714630/73881450-2aee6100-4815-11ea-8a21-cdad59d73af6.PNG">

**Comment by shilo-ey** [comment]
This attribute is for the wrapper of the widget.

We have added support for it in v2.9 which is supposed to release very soon.

Thanks

**Comment by ofmarconi** [comment]
@tamal-sen did you find any solution?
