### ISSUE TITLE
Share icon not displaying as expected

### ISSUE THREAD

**Issue by shroomers88** [elementor/elementor#10428]
Hi,

I hope someone here can help me fix this issue. This relates to another post (#10369) that was closed before being solved.

As you can see in the below screenshot, I've used the "share post" widget and changed the icons using CSS. It works just fine in Elementor, but once I move to the live version of the website (out of the builder), you can see the logo doesn't show. Instead, the font awesome icon ID that's in the CSS code appear.

https://www.screencast.com/t/PKr9ml95

Here's the CSS code I'm using:

.fa-linkedin:before{
content: "\f0e1"
}
.fa-facebook:before{
content: "\f39e"
}

Elementor support told me to deactivate the cache plugin, but that's not a viable solution since I need cache enabled. 

On Github (which was recommend by Elementor support), I was told to "try regenerating your CSS files by going to WP dashboard > Elementor > Tools > Regenerate CSS Files" and to "In addition, try rebuilding your cache files", which I did, but it didn't work. 

Can anyone help? I'm out of resources here...

**Comment by zero4281** [comment]
I just filed a bug report for what might be a related issue.  I can't see your screenshot anymore, so I'm not sure they're related.  I also noticed that when load content this way and I set Elementor to use inline CSS instead of an external file it filters out the '\' and I end up with the hex number instead of the icon.

**Comment by DorShahar** [comment]
Hi 
As @shilo-ey mentioned in #10369, This not related to Elementor.
You can look for a solution on our Facebook community, or in the links below:
- https://stackoverflow.com/questions/29331137/font-awesome-showing-box-instead-of-icons 
- https://stackoverflow.com/questions/26867795/font-awesome-is-not-showing-icon
- https://wordpress.stackexchange.com/questions/232818/font-awesome-stopped-showing-icons-shows-text-instead
- https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/troubleshooting

Good luck
