### ISSUE TITLE
Customization of login pages

### ISSUE THREAD

**Issue by RicardoBenito** [elementor/elementor#10437]
The login widget is very good, but unfortunately I consider it incomplete, since this design should be maintained for password recovery options in all its phases, as well as registration. And so depend on third party plugins. Likewise, add registration and login option with social media profiles.

Finally I want to add, that for two years I have been migrating all my work to Elementor.

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/8222
