### ISSUE TITLE
More responsiveness chocies in Gallery

### ISSUE THREAD

**Issue by JackBodiless** [elementor/elementor#10446]
I did search for open and closed tickets but didnt find anythin on these... hope i didnt miss anything. My first time posting here...

Using Elementor Pro.

Basically I would love to, no i need, NOT to have to create 2-3 duplicates with various settings for responsive galleries.
2 big issues that make me need to do that:

1. is if the images in a gallery will have a link to Media to open in lightbox or not.
Lightbox view is something i want on desktop, sometimes on tablet and almost never on mobile for obvious reasons.

2. is that I mostly want portrait format images on mobile as landscape format isnt good for mobile screens. Thus i always have to create another version of the section with the gallery to choose different images. Så a responsive selector for gallery itself would be excellent.

Then, after those, lazy load could also be good to be able to choose as well as the layout... basically everywhere its possible to make responsive.

Hope this gets implemented. Thanks
Best Regards and keep up the excellent work :)

**Comment by lior-sh** [comment]
Hi @JackBodiless,

Thanks for the feedback.
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Description and examples.
* One request per thread
Thanks.
