### ISSUE TITLE
Lightbox automatically opens for non elementor elements

### ISSUE THREAD

**Issue by SpabRice** [elementor/elementor#10447]
I have a standard link to an image in my footer.
Ex: `<a href="image.jpg">Link to image</a>`

On pages where the elementor editor is activated, this link automatically opens in the elementor lightbox, which ist totally unnecessary and strange.  How can I prevent this, without disabling the  lightbox feature in the global settings for elementor elements?  I just don't want to open the lightbox for custom links.

Thanks

**Comment by lior-sh** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
