### ISSUE TITLE
 [FEATURE REQUEST] Responsive controls for background type, overlay & gradients

### ISSUE THREAD

**Issue by eastriverstudio** [elementor/elementor#10449]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Firstly, I know the gradient part I mention later on in this request has been mentioned here #6783. However I'm looking at this as the complete set of background features lacking responsive controls, not just the gradient settings. However, it is now 2020 and can't see why gradients have not got the same controls as images.

What I'd like you to consider is that whilst the reponsive controls for a background image itself have been implemented previously, the missing features which would compliment this and allow more creative uses is that there aren't the same responsive controls for any of the other background options such as background type, background overlay and background gradients and I'd like to suggest these are considered as a new improvement for a future release.

Having these extra responsive background options would allow more creative freedom and allow certain visual tricks to be more easily achieved, overriden and adjusted across devices without resorting to the use of custom css which is unrelated to the background options which are set in the settings panel.

For example it is currently possible to easily achieve an overlap image effect (like one below) on desktop using the background overlay and setting a custom width in the css. However because we have no responsive controls for the background overlay itself it is not possible to adjust or remove the image on mobile devices (where the overlap style doesn't work) without resorting to custom css overrides and media queries which aren't as intuitive and separate to where we set the image itself. Whilst It is nice to be able to change the image to a different one responsively, what about if it just needs to be removed or the background type needs to changed to something that works better on a smaller device?

![Screenshot 2020-02-07 at 12 12 42](https://user-images.githubusercontent.com/37620756/74043798-f2d85100-49c1-11ea-99c6-154d37cbfb81.png)

![Screenshot 2020-02-07 at 12 30 18](https://user-images.githubusercontent.com/37620756/74043805-f66bd800-49c1-11ea-8b85-36a7c29a50dd.png)

Likewise with background gradients not having any responsive controls, it means it is way less intuitive to create layout effects using gradients if we can't alter how the gradient behaves across devices without resorting to custom css, which again isn't intuitive in my opinion when setting the gradient options somewhere else in the settings.

I hope this illustrates what I believe are still the missing elements to make backgrounds controls truely intuitive and allow us to achieve more visual tricks and effects that work responsively directly through the various background settings.

**Comment by addMitt** [comment]
Yeah it'd be nice to be able to change even the basic Background color of a section per device. The Background Type > Classic > Image property has responsive options, but Color does not? Baffling.

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/10247

**Comment by nicholaszein** [comment]
Hello everyone!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
