### ISSUE TITLE
I need an item to be displayed after filling out a form.

### ISSUE THREAD

**Issue by monkychilote** [elementor/elementor#10448]
Good afternoon:
I am building a template of single products, within this template I have an element that calls a "Listing Grid", which calls a dynamic element that makes the call to safety data sheets. It works very well since I have created a personal CPT where I create each security sheet and in this template I am calling through a "post query" of the post type by ID, using the following code:% related_children_from | safety_sheet%, up to everything is fine there. Now I need you to show me this element only if you fill out a form with data that identifies the person before they show me the download links found in this listing grid.

**Comment by lior-sh** [comment]
Hi @monkychilote,

Thanks for reporting.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by monkychilote** [comment]
> Hi @monkychilote,
> 
> Thanks for reporting.
> Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
> This report is missing key information:
> 
> * Prerequisites.
> * Steps to replicate.
> * Isolating the problem.
> * System info.
> * One issue per thread
>   Without it, we simply can't help.
>   Thanks.

Hi Lior.

I have just turned on my computer, I live in Chile, here it is only 10 AM in the morning and it has only been 2 hours since I wrote your answer and the ticket is already closed, I am just getting up. It is difficult for me to communicate in English and explain the problem in detail, unfortunately they do not have support in Spanish as far as I know.

If you cannot help me, touch another ticket and continue insisting on the detail that was already recognized as an error by elementor support in mail received a few weeks ago.

Thank you
