### ISSUE TITLE
[Feature Request] Navigator: program an icon to indicate on what section, column, inner section or element an animation has been placed

### ISSUE THREAD

**Issue by kayJayBeeisme** [elementor/elementor#10457]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like an easy and visual way to see at a glance if a section, column or element has a motion effect placed on it. This feature can be on multiple places that effect the same area and it can be tedious to find and edit or remove it.

**Describe the solution you'd like**
A visual cue in the Navigator (like an icon) that indicates if a section, column or element has a motion effect or animation placed on it.

**Describe alternatives you've considered**
Obviously right now, the only alternative is to click on each section, column and element to find the animation and remove it. It can take several clicks to get to the motion editor and the animation can be placed in quite a few places. So the process can be extremely tedious. If there were a visual cue in the navigator, we could see instantly where the animation was place (section, column, inner section, or element) and then more easily edit or remove it to save a ton of time.

**Additional context**
Thanks!

**Comment by shilo-ey** [comment]
Hi @kayJayBeeisme 

When we had in mind adding indications to the Navigator, we thought about adding the option you are suggesting but decided not to add this option to the Section/Column/Inner section that hosts the widget which the Motion Effect is applied on, to avoid confusion amongst our users.

As mentioned, you can see to which element you applied Custom CSS/Motion Effects.

A quick tip I can suggest is to expand all of the nested layouts and see visually which element has some Motion Effects applied.

Thanks for your suggestion.
