### ISSUE TITLE
[Feature Request] Table of Contents - initially minimised on All views (desktop, tablet, mobile)

### ISSUE THREAD

**Issue by markwalker92** [elementor/elementor#10454]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Loads table of contents in default minimised view on desktop, tablet and mobile

**Describe the solution you'd like**
At present the option only exists to initialise with minimised TOC on tablet, mobile or none. It would be useful to add an option for 'All' so this includes desktop view.

Thanks

**Comment by JohnMulderFrance** [comment]
See #9946

**Comment by shilo-ey** [comment]
I merged this issue with #9933, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by joelcunha** [comment]
+1

**Comment by JohnMulderFrance** [comment]
I feel elementor is more focussed on developing the elementor eco-system and leaves widget development to third parties.
And maybe rightly so. 
It is included in the free version of essential add-ons for elementor
https://essential-addons.com/elementor/table-of-content/
