### ISSUE TITLE
Change "Exit to dashboard" button URL

### ISSUE THREAD

**Issue by poehaldur** [elementor/elementor#10455]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when clicking the "Exit to dashboard" button and it goes to post or page default wp editor.

**Describe the solution you'd like**
I would love a code snippet or hook in functions.php that would allow me to set the url to go to listings or actual dashboard page and not to default wp editor in post or page.

**Additional context**
![84344733_10216686052927248_3501574505854140416_n](https://user-images.githubusercontent.com/32192439/74089438-d7e10c00-4aa9-11ea-9910-252f0485fe22.jpg)

**Comment by shilo-ey** [comment]
You can add custom JS code to do the job for you.

Make sure it will load in your site:
```js
$('.elementor-panel .elementor-panel-menu-item-exit-to-dashboard a[href]').prop('href', '/wp-admin/');
```

Thanks

**Comment by poehaldur** [comment]
Thanks. Been trying to get it to load but says "Uncaught TypeError: $ is not a function" or even when wrapping into
`<script>
jQuery(document).ready(function($){

$(\'.elementor-panel .elementor-panel-menu-item-exit-to-dashboard a[href]\').prop(\'href\', \'/wp-admin/\');

});
</script>`

Uncaught ReferenceError: jQuery is not defined

I think I have the injection code wrong, is it loading before jquery was loaded?
Can't seem to get the full function working.

**Comment by shilo-ey** [comment]
Add `$ = jQuery;` before the code is added

**Comment by poehaldur** [comment]
Umm, little lost here :) tried it but still get the same error.

For example, if my code is:

``add_action( 'elementor/editor/after_enqueue_styles', function() {
   echo '<script>
jQuery(document).ready(function($ = jQuery){
$(\'.elementor-panel .elementor-panel-menu-item-exit-to-dashboard a[href]\').prop(\'href\', \'/wp-admin/\');
});
</script>
';
} );``


And also 
``add_action( 'elementor/editor/after_enqueue_styles', function() {
   echo '<script>
$ = jQuery;   
$(\'.elementor-panel .elementor-panel-menu-item-exit-to-dashboard a[href]\').prop(\'href\', \'/wp-admin/\');
</script>
';
} );``


Give the same error.

**Comment by poehaldur** [comment]
Ok, this is what I have so far:

``add_action( 'elementor/editor/footer', function() {
   echo '
<script>
$ = jQuery;
$(\'.elementor-panel .elementor-panel-menu-item-exit-to-dashboard a[href]\').prop(\'href\', \'/wp-admin/\');
</script>
';
} );``

Now there is no error but link does not change.

**Comment by poehaldur** [comment]
@shilo-ey Can you please take a look at the final code? Not sure why it is not working.
Thanks.
