### ISSUE TITLE
Open Menu Link in a new Tab

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#10477]
I would like to see additional settings in the menu widget, so one or more menu items can be opened the link in a new tab.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
