### ISSUE TITLE
[Help needed] How can i add new elementor panel navigation tab?

### ISSUE THREAD

**Issue by jatind93** [elementor/elementor#10479]
HI,

I want to add new navigation tab next to the "global" ( in elementor editor ) tab as below screebshot. Is it possible add new tab? if yes then could you please guide me how can i add panel navigation tab.
 : [Screenshot link](http://prntscr.com/r069xn)

Thanks

**Comment by shilo-ey** [comment]
`$e.components.get( 'panel/elements' ).addTab( 'tabName' ); // Replace tabName with your tab name`

The above method works since v2.8, If you want to provide backwards compatibility for earlier versions you can use:
```PHP
if ($e) {
// E >= 2.7.0
// ADD HERE YOUR FUNCTION
} else {
// E < 2.7.0
// ADD HERE YOUR FUNCTION
}
```

**Comment by jatind93** [comment]
@shilo-ey 

Could you please explain bit more in which action i have to add this code?
