### ISSUE TITLE
Thousand separator issues

### ISSUE THREAD

**Issue by Ouwazyz** [elementor/elementor#10487]
Since a few days i have a thousand separator issue. Indeed i wanted to use a COUNTER widget, so i selected a page and insert a counter inside but when the counter value is printed there's one extra zero. I'd tested with and without custom code but the issue it is still there.

You'll find here a screenshot of the file which the counter should print the value on the website and the screenshot of the value the counter has printed on the website and the screenshot of the script that permits the counter to print the value of the file.

I NEED YOUR HELP !

PS : Sorry for my english

![value_printed](https://user-images.githubusercontent.com/51120277/74170100-a9d80500-4c2c-11ea-8bc8-062f9a0aa207.png)
![value_supposed_to_be_printed](https://user-images.githubusercontent.com/51120277/74170110-ae9cb900-4c2c-11ea-94bb-fca4f030174f.png)
![php_script](https://user-images.githubusercontent.com/51120277/74170119-b2304000-4c2c-11ea-85bc-229c33bb1a25.png)

**Comment by shilo-ey** [comment]
Hi @Ouwazyz 

This issue is not Elementor related, it seems related to your code.

Try writing your number to a custom field instead of pulling it with PHP through 3rd party addons.

Thanks
