### ISSUE TITLE
Super Fast speed like JNews theme

### ISSUE THREAD

**Issue by warcraft14115** [elementor/elementor#10489]
Hi, Jnews theme use Elementor too but they can make theme load so fast and have 100/100 Google soccers pagespeed

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
