### ISSUE TITLE
New bugs found with 2.9-beta5:

### ISSUE THREAD

**Issue by Anastasia-Axelrod** [elementor/elementor#10496]
1. I can no longer see the Theme Style Settings button and edit the theme, also it seems that all the settings that I set in the beta4 still working.
2.  I can not set a template (from saved templates) on the page, the widget doesn't give the option to chose or to enter the name of the template.

**Comment by shilo-ey** [comment]
Those fixes were already made and about to release today.

Thanks for your feedback
