### ISSUE TITLE
Open email share button in new tab instead of same tab

### ISSUE THREAD

**Issue by tdechangy** [elementor/elementor#10490]
The actual sharing buttons work quite well BUT the email sharing doesn't open in a new tab, as any other solution does to avoid losing visitors.

I have to use an alternative plugin to use this for now, which is ridiculous. Fix this asap please.

**Comment by lior-sh** [comment]
Hi @tdechangy,

This bug not reproducible. Once you click on the email it will open in a new tab.

Thanks.
