### ISSUE TITLE
Sendy add API_Key into the Functions.PHP

### ISSUE THREAD

**Issue by jmcst24** [elementor/elementor#10491]
I have been using the code listed sendy newsletter. Sendy recently changed their code with an upgrade to require the 'api_key' to be included in the form details.  When I add a hidden field with the API key in the form this code will work, but I just want to add it to the PHP code in the functions.php vs adding it to every form.   Can someone let me know how to modify the below to add api_key = '12345'  into the fields that is passed?

// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    
    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'https://yourwebisteurl.com/sendy/subscribe', [
        'body' => $fields,
    ]);
}, 10, 2 );

Thanks

**Comment by jmcst24** [comment]
I figured it out, if you add the following line with your API code it works.

$fields [ 'api_key' ] = 'YOURSENDYAPIKEY';

---------------------
so new looks like
___________________

/ A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {

$raw_fields = $record->get( 'fields' );
$fields = [];
foreach ( $raw_fields as $id => $field ) {
    $fields[ $id ] = $field['value'];
}
$fields [ 'api_key' ] = 'YOURSENDYAPIKEY';
wp_remote_post( 'https://yourwebisteurl.com/sendy/subscribe', [
    'body' => $fields,
]);
}, 10, 2 );

**Comment by shilo-ey** [comment]
See more here: https://developers.elementor.com/forms-api/custom-form-action/
