### ISSUE TITLE
Popup Editor not loading after 2.9.0 update

### ISSUE THREAD

**Issue by aidan2496** [elementor/elementor#10502]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

 

Using OceanWP

After updating to Elementor Version 2.9.0 the popup editor stopped loading. Would go onto the page but the side menu would stay blank and continue displaying loading symbol. Tried using safe mode and editor still wouldn't. Followed further details on Elementor site with no luck. 

Used incognito and tried using another PC but the problem was still present. 

After backing up and rolling back to 2.8.5 the issue was rectified. 

Same issue referenced here during BETA testing:

> Well...can't edit/create popup - Still not working in test mode too...
> ![image](https://user-images.githubusercontent.com/60903894/74200124-5b475c80-4c66-11ea-955a-9f7e332f3e84.png)

## Steps to reproduce

Opening Elementor editor for popups from the home page and template section on the backend.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.  (Did not check at the time. Will not be updating again to check at this stage) 
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Not disclosing site url details sorry
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.22
	PHP Version: 7.0.33
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: Not disclosing
	Home URL: Not disclosing
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.7.4
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36

== Active Plugins ==
	Admin Menu Editor
		Version: 1.9.3
		Author: Janis Elsts

	DynamicConditions
		Version: 1.4.3
		Author: RTO GmbH

	Elementor
		Version: 2.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Exclusive Team Elementor
		Version: 1.2.3
		Author: DevsCred.com

	Form Vibes - Database Manager for Forms
		Version: 1.1.1
		Author: WPVibes

	Limit Login Attempts Reloaded
		Version: 2.10.0
		Author: WPChef

	ManageWP - Worker
		Version: 4.9.2
		Author: GoDaddy

	Pods - Custom Content Types and Fields
		Version: 2.7.16.2
		Author: Pods Framework Team

	WP Extended Search
		Version: 1.3
		Author: 5um17


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	installatron_hide_status_test.php
		Version: 
		Author: 

	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy
)]


				
```
</details>

**Comment by lolosland** [comment]
Just my 2 cents here, 
if you have used the evergreen timer which hides the popup after x amount of time, make sure to clear in your local storage of the following 2 cookies:

- xxxxxxx-evergreen_due_date
- xxxxxxx-evergreen_interval

**Comment by aidan2496** [comment]
@lolosland Thank you. However, I wasn't using the evergreen timer but thanks for your help.

**Comment by clement-menard** [comment]
Same problem for me...
Wordpress 5.3.2 + Elementor 2.9 + Elementor Pro 2.8.3 + Hello Elementor Theme

**Comment by idesimedia** [comment]
I have the same problem.

Wordpress 5.3.2, Elementor 2.9, Elementor Pro 2.8.3, Hello Child Theme

**Comment by rodolphebertozzo** [comment]
+1

**Comment by black-eye** [comment]
+1 Same here.
I don't get it. The bug was reported during the beta testing phase, yet the 2.9.0 went out as scheduled, no matter what. And this is not the only known bug introduced by the new version. Why to betatest then...?

**Comment by kangarko** [comment]
+1

**Comment by studiotopo** [comment]
+1
Wordpress 5.3.2/Elementor 2.9/Elementor Pro 2.8.3/Hello Elementor theme.

**Comment by Jordidriesen** [comment]
+1, same error here, weirdly not on all websites. All use elementor extras and are hosted on litespeed with the following error

Uncaught ReferenceError: Elementor panel doesn't have page named 'page_settings

**Comment by David-GH** [comment]
Hi everybody !
Same issue here. Impossible to create/edit a popup.
The error in the console : 
`ReferenceError: Elementor panel doesn't have page named 'page_settings' editor.min.js:31:189856`

Version: Elementor 2.9.0

I don't try a roll back, I hope this will be fix soon.

**Comment by kaspergram** [comment]
Same issue here.

editor.min.js?ver=2.9.0:31 Uncaught ReferenceError: Elementor panel doesn't have page named 'page_settings'
    at i.setPage (editor.min.js?ver=2.9.0:31)
    at Component.renderTab (editor.min.js?ver=2.9.0:31)
    at Component.activateTab (editor.min.js?ver=2.9.0:2)
    at Component.<anonymous> (editor.min.js?ver=2.9.0:2)
    at Routes.run (common.min.js?ver=2.9.0:2)
    at Routes.to (common.min.js?ver=2.9.0:2)
    at API.route (common.min.js?ver=2.9.0:2)
    at t.value (editor.min.js?ver=2.8.3:2)
    at p (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3.2:10)
    at f (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3.2:10)

**Comment by VenkmanNL** [comment]
+1

**Comment by israel-tours** [comment]
+1

**Comment by ELSENO** [comment]
+1

**Comment by sirucato** [comment]
Same here

**Comment by PawelRudko** [comment]
Same problem for me...
Wordpress 5.3.2 + Elementor 2.9 + Elementor Pro 2.8.3 + Hello Elementor Theme

**Comment by clement-menard** [comment]
Elementor 2.9.1 solved the problem. Thanks !

**Comment by aidan2496** [comment]
> Elementor 2.9.1 solved the problem. Thanks !

Great to hear. Thanks!

**Comment by aidan2496** [comment]
The issue has now been rectified in Elementor Version 9.0.1

**Comment by studiotopo** [comment]
2.9.1

Inviato da iPhone

**Comment by aidan2496** [comment]
> 2.9.1 Inviato da iPhone
> […](#)
> Il giorno 14 feb 2020, alle ore 12:29, Aidan ***@***.***> ha scritto: The issue has now been rectified in Elementor Version 9.0.1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

...oops. Thanks for that

**Comment by kzenman** [comment]
Just updated to 2.9.9 and now having this same issue. Should open a new thread? 
Pro Version 2.7.3

`editor.min.js?ver=89851.9:31 Uncaught ReferenceError: Elementor panel doesn't have page named 'page_settings'
    at i.setPage (editor.min.js?ver=89851.9:31)
    at Component.renderTab (editor.min.js?ver=89851.9:31)
    at Component.activateTab (editor.min.js?ver=89851.9:2)
    at Component.<anonymous> (editor.min.js?ver=89851.9:2)
    at Routes.run (common.min.js?ver=2.9.9:2)
    at Routes.to (common.min.js?ver=2.9.9:2)
    at API.route (common.min.js?ver=2.9.9:2)
    at t.value (editor.min.js?ver=2.7.3:2)
    at p (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3.3:10)
    at f (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3.3:10)`

**Comment by gonzantos** [comment]
Same problem: Elementor 2.9.11 + Elementor PRO 2.8.5

**Comment by gonzantos** [comment]
> Same problem: Elementor 2.9.11 + Elementor PRO 2.8.5
I RollBack to Elementor 2.9.8 and now I can edit PopUps

**Comment by nonny2019** [comment]
I got same issue, using elementor 2.9.12

editor.min.js:31 Uncaught ReferenceError: Elementor panel doesn't have page named 'page_settings'
    at i.setPage (editor.min.js:31)
    at Component.renderTab (editor.min.js:31)
    at Component.activateTab (editor.min.js:2)
    at Component.<anonymous> (editor.min.js:2)
    at Routes.run (common.min.js:2)
    at Routes.to (common.min.js:2)
    at API.route (common.min.js:2)
    at Editor.<anonymous> (cmm4e-elementor-editor.min.js:1)
    at p (load-scripts.php?c=0&load[chunk_0]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.4.2:16)
    at f (load-scripts.php?c=0&load[chunk_0]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.4.2:16)

**Comment by nonny2019** [comment]
> I got same issue, using elementor 2.9.12
> 
> editor.min.js:31 Uncaught ReferenceError: Elementor panel doesn't have page named 'page_settings'
> at i.setPage (editor.min.js:31)
> at Component.renderTab (editor.min.js:31)
> at Component.activateTab (editor.min.js:2)
> at Component. (editor.min.js:2)
> at Routes.run (common.min.js:2)
> at Routes.to (common.min.js:2)
> at API.route (common.min.js:2)
> at Editor. (cmm4e-elementor-editor.min.js:1)
> at p (load-scripts.php?c=0&load[chunk_0]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.4.2:16)
> at f (load-scripts.php?c=0&load[chunk_0]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.4.2:16)

any solution??

**Comment by Bogsey** [comment]
This is still happening with 2.9.13

**Comment by lord-house** [comment]
+1

**Comment by immefrank** [comment]
+1 2.9.13 still getting the same error message. Worked fine before but suddenly stopped working.

**Comment by luismts** [comment]
+1

I had the 2.9.12 with the error and update it to 2.9.13 and still have the error. I can't edit my popups!

**Comment by g000m** [comment]
+1

2.9.13 & 2.10.3

all other plugins disabled, twentytwenty active

**Comment by sirucato** [comment]
Hello. Someone opened a new thread? This one is closed and nobody takes care of these posts.

**Comment by narkan** [comment]
Fixed for me, by updating to latest version of Elementor and Elementor Pro plugins

**Comment by willdobson79** [comment]
This is fixed with Elementor Pro update (2.10.2)

**Comment by michelmany** [comment]
Same error here:
Elementor panel doesn't have page named 'page_settings'

**Comment by Lukazcreations** [comment]
+1 This issue just reoccured

**Comment by norb-c** [comment]
Same here
