### ISSUE TITLE
Library Connector

### ISSUE THREAD

**Issue by karinwerner** [elementor/elementor#10500]
Should verify by license key rather than email. Only the admin holding the given email linked to elementor's account is allowed access to the library insert request. What if the admin changes their admin email or another admin is needing access. We have had nothing but errors when using other admin accounts when attempting to insert library templates.
A easy fix would be to simply add the permissions in the database for the admin's id. Or, to go by the license key rather than the admin's email.

**Comment by shilo-ey** [comment]
Hey @karinwerner 

The use of Templates Library is per user and not per license. therefore, each user who want to use the template library will need to have a free Elementor account. 

Read more here: https://docs.elementor.com/article/616-connect-library
