### ISSUE TITLE
Change "Exit to dashboard" button URL

### ISSUE THREAD

**Issue by poehaldur** [elementor/elementor#10504]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when clicking the "Exit to dashboard" button and it goes to post or page default wp editor.

**Describe the solution you'd like**
I would love a code snippet or hook in functions.php that would allow me to set the url to go to listings or actual dashboard page and not to default wp editor in post or page.

![74089438-d7e10c00-4aa9-11ea-9910-252f0485fe22](https://user-images.githubusercontent.com/32192439/74314795-c4ba8e80-4d7e-11ea-950e-122a86406384.jpg)

**Additional context**

My previous post https://github.com/elementor/elementor/issues/10455 was closed too early, I did not get the working code.

This is what I have so far:

```
add_action( 'elementor/editor/footer', function() {
   echo '<script>
$ = jQuery;
$(\'.elementor-panel .elementor-panel-menu-item-exit-to-dashboard a[href]\').prop(\'href\', \'/wp-admin/\');
</script>
';
} );
```

But it does not work. 
I think it needs just a minor adjustment but no idea what to do.
Thanks.

**Comment by poehaldur** [comment]
Anyone? :)

**Comment by poehaldur** [comment]
Help? :)

**Comment by poehaldur** [comment]
Final try to find help..

**Comment by poehaldur** [comment]
Nevermind, got it working.

```
function my_exit_to_dashboard(){
$url=admin_url();
return $url;
}
add_filter('elementor/document/urls/exit_to_dashboard' , 'my_exit_to_dashboard');
```

**Comment by get8bit** [comment]
+1 Custom code can work, but what about newbies! This is very confusing and bad UX. Dashboard should mean dashboard, not page settings. lol
