### ISSUE TITLE
Image Carousel not working since 2.9 upgrade

### ISSUE THREAD

**Issue by jdub850000** [elementor/elementor#10505]
I have loaded a page containing 2x Image Carousels on 2x separate pages (on a finished working site) that have now stopped working since updating to the final 2.9 version. Everything worked fine before. No steps to reproduce.

One page I have had to replace with static images, the other is still as was containing the image carousels. The only difference is that it has been loaded into the editor - not even saved. The page is here - carousels alongside the text blocks. Shown with the prev/next buttons: -

https://humedadcontrol.es/construction/

EDIT: Seems it works on an iPad I have here, but not on Safari, latest release version.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by jdub850000** [comment]
Apologies - Seems like some errors there...

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: mariadb.org binary distribution v10.3.21
	PHP Version: 7.4.1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://humedadcontrol.es
	Home URL: https://humedadcontrol.es
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-GB
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.2.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

== Active Plugins ==
	Beehive Pro
		Version: 3.2.3
		Author: WPMU DEV

	Defender Pro
		Version: 2.2.5
		Author: WPMU DEV

	Disable Gutenberg
		Version: 2.0
		Author: Jeff Starr

	Elementor
		Version: 2.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.3
		Author: Elementor.com

	Element Pack
		Version: 4.5.0
		Author: BdThemes

	Essential Addons for Elementor
		Version: 3.7.2
		Author: WPDeveloper

	FileBird Lite
		Version: 2.6
		Author: Ninja Team

	Forminator Pro
		Version: 1.11.2
		Author: WPMU DEV

	GTranslate
		Version: 2.8.51
		Author: Translate AI Multilingual Solutions

	Hummingbird Pro
		Version: 2.4.0
		Author: WPMU DEV

	Preloader
		Version: 1.0.9
		Author: Alobaidi

	Query Monitor
		Version: 3.5.2
		Author: John Blackbourn

	Regenerate Thumbnails
		Version: 3.1.2
		Author: Alex Mills (Viper007Bond)

	Self-Hosted Google Fonts
		Version: 1.0.1
		Author: asadkn

	SmartCrawl
		Version: 2.5.0
		Author: WPMU DEV

	Smush Pro
		Version: 3.5.1
		Author: WPMU DEV

	Snapshot Pro
		Version: 3.2.1.4
		Author: WPMU DEV

	Stop Generating Image Sizes
		Version: 2.0.2
		Author: Nazmul Ahsan

	UpdraftPlus - Backup/Restore
		Version: 2.16.21.1
		Author: UpdraftPlus.Com, DavidAnderson

	Weather Station
		Version: 3.8.9
		Author: Pierre Lannoy

	WooCommerce
		Version: 3.9.1
		Author: Automattic

	WooCommerce Admin
		Version: 0.25.1
		Author: WooCommerce

	WooCommerce Services
		Version: 1.22.3
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.3.1
		Author: WooCommerce

	WPMU DEV Dashboard
		Version: 4.8-beta-1
		Author: WPMU DEV


== Must-Use Plugins ==
	WPMU DEV Hosting
		Version: 0.1
		Author: WPMU DEV


== Elements Usage ==
	
	archive : 1
		bdt-post-grid : 1
		blockquote : 1
		heading : 1
	footer : 2
		form : 1
		heading : 3
		icon-list : 2
		image : 1
		shortcode : 1
		social-icons : 1
		text-editor : 1
	header : 2
		icon-list : 2
		language-switcher : 1
		nav-menu : 2
		social-icons : 2
		theme-site-logo : 2
	page : 1
		blockquote : 1
		button : 1
		eael-feature-list : 2
		heading : 9
		image-carousel : 2
		text-editor : 2
	product : 1
		global : 1
		premium-addon-title : 1
		woocommerce-breadcrumb : 1
		woocommerce-menu-cart : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 2
	section : 2
		animated-headline : 1
		global : 1
		text-editor : 1
	single : 2
		facebook-button : 1
		facebook-comments : 1
		global : 1
		heading : 2
		icon : 1
		image : 1
		post-info : 1
		post-navigation : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-title : 1
	wp-page : 7
		animated-headline : 1
		blockquote : 6
		button : 4
		eael-feature-list : 5
		gallery : 1
		global : 1
		heading : 36
		icon-box : 6
		icon-list : 1
		image : 14
		image-carousel : 2
		shortcode : 3
		text-editor : 11
		woocommerce-products : 1
	product-archive : 1
		global : 1
		woocommerce-products : 1


== Log ==
	
Log: showing 9 of 92020-01-03 17:32:24 [info] elementor::elementor_updater Started 
2020-01-03 17:32:24 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-03 17:32:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-03 17:32:26 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-03 17:32:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-03 17:35:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-20 12:42:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-01-28 17:29:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-02-11 20:14:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.0',
)]

PHP: showing 3 of 3PHP: 2020-01-07 15:05:44 [notice X 10][/var/web/staging/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1423] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-07 18:17:02 [error X 1][/var/web/staging/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 17018768 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-28 17:56:03 [notice X 61][/var/www/vhosts/humedadcontrol.es/staging.humedadcontrol.es/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2020-01-13 20:56:28 [error X 474][https://staginghumedadcontrol.wpmudev.host/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.4.7:2:19440] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2020-01-13 21:37:13 [error X 2][https://staginghumedadcontrol.wpmudev.host/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.3:7:20346] undefined is not an object (evaluating \'this.ui.columnInner.removeClass\') 
JS: 2020-01-14 10:44:55 [error X 8][https://staginghumedadcontrol.wpmudev.host/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.3:2:67223] undefined is not an object (evaluating \'this._parent.getContainer\') 
JS: 2020-01-20 13:15:29 [error X 10][https://staging.humedadcontrol.es/wp-content/plugins/elementor-pro/assets/js/frontend.min.js:2:78729] undefined is not an object (evaluating \'t.gallery.setSettings\') 
JS: 2020-02-11 22:14:47 [error X 1][https://humedadcontrol.es/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.3:2:54590] undefined is not an object (evaluating \'elementor.$previewContents.find(\"#elementor\").offset().top\')
