### ISSUE TITLE
Menu typography issue

### ISSUE THREAD

**Issue by studiotopo** [elementor/elementor#10515]
Hi,

testing the last Elementor update (2.9.0) any typography change does not work in frontend.
<img width="291" alt="Schermata 2020-02-12 alle 14 40 04" src="https://user-images.githubusercontent.com/59436040/74340128-aae07200-4da5-11ea-8dca-067075f87bcc.png">

**Comment by studiotopo** [comment]
Hi,

also in Theme Style there is a bug with typography: line-height does not work.

<img width="280" alt="Schermata 2020-02-12 alle 15 26 08" src="https://user-images.githubusercontent.com/59436040/74343947-29d8a900-4dac-11ea-8150-f5e5ccbceb46.png">

**Comment by lior-sh** [comment]
Hi @studiotopo,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* **Isolating the problem**.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
