### ISSUE TITLE
✅ 🚀 Feature Request: Allow to choose different icons for the Star Rating widget

### ISSUE THREAD

**Issue by varunmohapatra** [elementor/elementor#10529]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Other types of icons are needed in the Star Rating widget. It would be great to have support for choosing other icons from the font awesome family.

**Describe the solution you'd like**
Have another dropdown in the widget settings to choose a font-awesome icon

**Describe alternatives you've considered**
The mentioned solution would be a simple practical solution. No other ones considered as such.

**Additional context**
I was making a dynamic website that needed a price range for each item displayed. I wanted to show the price range on a scale of 1-5 in the form of $ icons. Similarly, show a trust score in the form of thumbs-up icons.

**Comment by nicholaszein** [comment]
Hello @varunmohapatra!

Thank you so much for your patience! 🙏 

We have great news! 🙌 

### 📢 We're happy to announce that the request you raised was resolved with the release of the new Rating widget in Elementor v3.17! 🥳 

With this new widget, you have more options to choose the number of rating points, custom icons, and styling options, and it is fully compatible with Google Rich snippets (updated) and fully accessible.

Your current Start Rating widgets will remain as they were before this update. But moving forward, only the new Rating widget will be available to add to your layouts.

If you are using the old Star Rating widget, we would recommend that you replace it with the new Rating widget.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
