### ISSUE TITLE
Reviews widget bug after updating

### ISSUE THREAD

**Issue by Ediiison** [elementor/elementor#10528]
Hello everybody,

After updating Elementor to 2.9.0 the option "Slides Per View" of the "Reviews" widget does not work anymore(for tablet and mobile)!

I tested it again with another local website using Elementor 2.8.5 and that works fine.

ANd after the demotion of Elementor to version 2.8.5 that works fine again too.

Thanks in advance
Cordially

**Comment by MiguelFalcon** [comment]
The same I published yesterday. You should check before opening new tickets, it is a prerequisite.
[The publication](https://github.com/elementor/elementor/issues/10518)

**Comment by shilo-ey** [comment]
I merged this issue with  #10508, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
