### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Clickable Elementor Text Box (Not column or section) (Duplicate)

### ISSUE THREAD

**Issue by johndjchan** [elementor/elementor#10542]
hi there fellas
lets say i have one column with 10 text box and is it possible to have each text box whole thing clickable to one specific url pls?

thanks a lot!

**Comment by nicholaszein** [comment]
Hello @johndjchan!

This feature is already possible using the Container. Just add your Text Editor widget inside one and change the HTML tag of the Container to a link.

Cheers 🥂
