### ISSUE TITLE
Essential Addon Post Carousel stopped working when updated to beta5 - actually is also on beta4

### ISSUE THREAD

**Issue by skompini** [elementor/elementor#10545]
I am a new beta tester, as well as new to git, so immediate apologies if I'm breaking protocol.

I think this issue could be related to the image carousel issue, but I wanted to put this out there as well. I know EA is not Elementor, but many Elementor patrons use it (I use it mainly for the post carousel, and the dynamic content accordion, so if you guys ever want to make widgets to replace those, I'd happily give up EA!! :)) so I wanted to report this. 

I did the update to beta5 just the other day and I noticed my post carousel immediately stopped working. It just sits on the last slide and does nothing. This isn't going to work at all. When I reverted back to Elementor 2.8.5, it works fine again. So it's definitely something to do with beta5, as this didn't happen with the previous version of beta. If I could go back to the previous version of beta, I would, but I haven't seen that option, but whatever is causing this breakdown happened in beta5. I have not updated other test sites with beta5, and my post carousel is still working fine.

In the test site with the problem, I use:

WP 5.3.2
Hello Theme
Advanced Custom Post Types
Classic Editor
Elementor
Elementor Pro
Envato Elements
EA
EA Pro
Wordfence

All plugins and theme are up to date. I don't believe any are in conflict since the carousel worked just fine in previous beta.

Let me know if there is anything else I can provide. Thanks for all the amazing work!!

**Comment by shilo-ey** [comment]
Please contact the author of the plugin if the issue persists. 

A fix for supporting 3rd party addons has been released.


Thanks
