### ISSUE TITLE
Request for Pre-Loader Animation Widget

### ISSUE THREAD

**Issue by vatitude** [elementor/elementor#10555]
Hi,
Good day to you!
We would like to request Elementor to introduce Pre-Loader Animation (Custom/template animations) for site opening. Wordpress usually takes more time to load webpages because of its plugins, etc. In that time if the user gets irritated seeing a blank page loading for a long time, it makes him bounce out of the site immediately. 

When we present to a client, we try opening the site in front of them and it keeps loading behind a blank page worsens the case. Where the client diverts towards the speed of the site than discussing the agenda of the presentation which is to showcase the elegance & utility features of the website design. 
In this case, trying adding too many caching plugins to speed up, doing other speedup things are hectic. If we have a pre-loader widget, this will make everything better than before. Clients at least will get to see some animation of the loading site. Which makes them sit for some more time till the site opens up. Many 3rd party pre-loaders are going to be a load to the site and they start to stink soon.
Kindly get this widget soon, please. So that we could clear all other unwanted sites speed up/caching plugins and make the user experience best.

Thanks & Regards,
Dev,
Co-Founder,
VATITUDE

**Comment by 79ho3ein** [comment]
It is not clear when this feature will be released?

**Comment by 79ho3ein** [comment]
hi @DorShahar
Will we see this feature in 2021? If possible, please answer.

thank you

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10576, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
