### ISSUE TITLE
Elementor version 2.9.0 and 2.9.1

### ISSUE THREAD

**Issue by sinashamsizadeh** [elementor/elementor#10559]
Hi,
There seems to be an issue in your free version on the wordpress.org.

In development tab you wrote change log for version 2.9.0 and 2.9.1 but downloadable version is 2.8.5
Maybe it's because of the readme.txt

I tested it using the guest browser. So I'm sure that it's not the cache version

Attached screenshot:
https://prnt.sc/r32pcy

**Comment by avermat** [comment]
See here: https://www.facebook.com/groups/Elementors/permalink/2558721377586966/

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
