### ISSUE TITLE
[Feature Request] Label for missing pro widgets (Inactive Widgets)

### ISSUE THREAD

**Issue by agusmu** [elementor/elementor#1055]
With the release of PRO and upcoming API docs, we can expect many custom widgets for Elementor. Then it is important for Elementor to handle inactive widgets properly because custom widgets can be activated and deactivated anytime.

## Description

Inactive widgets data from custom/PRO widgets LOST after deactivating the widgets and save the page. 

and LOST also on major Elementor upgrades. 

## Steps to reproduce

PART 1 = Page Editing

1) Create an Elementor PRO page and add some PRO widgets to this page and save it.
2) Deactivate Elementor PRO.
3) Edit this page again, now you will see that PRO widgets on step 1 disappear from this page. Save this page again.
4) Activate Elementor PRO again.
5) Edit this page again, and we will realize that PRO widgets data on step 1 LOST forever.

PART 2 = Elementor Upgrades

1) Create an Elementor PRO page and add some PRO widgets to this page and save it.
2) Deactivate Elementor PRO.
3) To reproduce this, we need to trigger elementor/includes/upgrades.php to run.  For example, we can edit wordpress options data 'elementor_version' to 0.9.2 to trigger _upgrade_v0110() function to run. 
4) Refresh the page to run _upgrade_v0110() function.
5) Activate Elementor PRO again.
6) Edit this page again, and we will realize that PRO widgets data on step 1 LOST forever.

## PROPOSAL

WordPress can handle inactive widgets, and I hope Elementor can do the same. I propose my solution below. 

1) when editing an Elementor page, when there is a custom/PRO widget on this page and the widget is currently not active, we can display a "placeholder" widget here. 

This placeholder widget of course can't be edited, but can be removed. The inactive widget data is kept here and it is included when saving this page. 

So, when user activate this custom/PRO widget again, the data will stay there. 

2) when running upgrades function, upgrade every post, and find any inactive widgets, please keep this inactive widgets data. 

.
.
.

I hope it is clear. Let me know more details is needed.

**Comment by joshmarom** [comment]
In Elementor pro you can save a widget as a global widget.
With this feature allows you can save an "Inactive" widget as global, remove it from the page, and later on, you can use it again.

Does this suggestion solve the problem?

**Comment by agusmu** [comment]
hi @joshmarom 

unfortunately not. I am developer and I have Elementor PRO, so I understand how global widget works. 

actually the big problem is on major upgrades when upgrades.php run and then custom widgets data will be deleted by Elementor automatically if custom widgets are not active on upgrading process.

this issue happened on some of my clients when Elementor v0.11 long time ago. some of them deactivate our custom widgets for testing purpose. then, when they update Elementor from v0.10 to v0.11, all Elementor pages are updated in the background and custom widgets data on all Elementor pages are DELETED. 

there is no solution except restore the database backup. 

i can understand that you may be think that it is not important issue. But once you release a major upgrade to Elementor that needs to update Elementor post data on upgrade.php, you will probably start receiving some support queries that asking why some of custom widgets data disappear from their Elementor page on upgrades.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
