### ISSUE TITLE
Site logo should have more than just site URL link

### ISSUE THREAD

**Issue by vojjin** [elementor/elementor#10554]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have multilingual website and site logo element can only link media file or site URL. However, site URL differ from language to language... /, /de, /es, /jp... And I cannot set proper URL for language header, it is always linking to site root.

**Describe the solution you'd like**
Just to enable custom URL to be set. Or to fix the issue.

**Describe alternatives you've considered**
As an alternative I just put image element and link it to appropriate home page.

**Comment by klainser** [comment]
What plugin are you using for your multilingual website ?

**Comment by vojjin** [comment]
I'm using Polylang. Also, in a header, I use Elementor's language switcher with flags, which is working just fine - I'm receiving current page in another language when clicked on any flag.

**Comment by shilo-ey** [comment]
Hi @vojjin 

Thanks for your feedback.

The Site Logo widget is an Image widget that has dynamic rule to it: Fetch the Site Logo.

You can do this with any other Image widget in combination with the Dynamic tags that Elementor Pro offers.

In addition, you can use our API to create your own dynamic tag that supports your specific case. see more here: https://developers.elementor.com/dynamic-tags/

Thanks
