### ISSUE TITLE
✅ 🚀 Feature Request: Make the Posts Widget and the Archive Posts widget styling options unified (+ allow copy-pasing styling)

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#10566]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

There are a few annoying discrepancies between the **Posts Widget** and the **Archive Posts widget**.

## 1. You can't copy-paste styling from the Posts widget to the Archive posts widget and vice versa

This makes the workflow of building blog/magazine website quite a bit more difficult.

You very often want the achive post listing to have the same layout and styling as your home page post listing.

Unfortunately you can't copy the styling from Posts to Archive posts and you have to transfer every single styling by hand, which can be like 30 individual settings and that takes a very long time.

## 2. Styling options are different for both widgets

![elgit](https://user-images.githubusercontent.com/36289156/74615135-30558080-511e-11ea-86b3-22c660652259.png)

For some reason the "Box" styling options tab is completely missing in the Archive posts widget.

This makes no sense. The options for styling the box are very important. And why include it in the Posts widget and not in the Archive posts widget?

**Describe the solution you'd like**

These widgets should always be identical when it comes to options and styling settings.

Being able to copy-paste the styling between these widgets would make things so much easier.

**Comment by tomas-eklund** [comment]
Agreed! I've suffered from this too for a long time and only now did I go here to report the same issue. It's very annoying.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the introduction of the Loop Builder in Elementor Pro v3.8.0! 🥳 

You now have full control over the styles of each component inside a Loop Item template, and we recommend you use this new feature.

✅ Feel free to check it out and update your plugin to the latest version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
