### ISSUE TITLE
Control value in other control as class selector

### ISSUE THREAD

**Issue by davidalbert8** [elementor/elementor#10561]
Hi,
Spent more than two weeks, tried everything and search this repository and the internet but no success, I was expecting this a very simple process as it is a basic need of development of plugins and themes. I want to get one control value as a variable that is a class selector and use it in another control as a selector to give color, both controls are in the same widget. I need to have this value as a variable to check some basic things and then use it as a selector.

```php
    protected function _register_controls() {
        $this->start_controls_section(
            'section_title',
            [
                'label' => __( 'General', 'elementor' ),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );
        $this->add_control(
            'class',
            [
                'label' => __( 'Class', 'elementor' ),
                'type' => \Elementor\Controls_Manager::TEXT,
                'placeholder' => __( 'Write class here.', 'elementor' ),
                'default' => 'myclass',
            ]
        );
        
        // This code doesn't work
        // $class = '.' . $this->get_settings('class');
        
        $this->add_control(
            'color',
            [
                'label' => __( 'color', 'elementor' ),
                'type' => \Elementor\Controls_Manager::TEXT,
                'placeholder' => __( 'blue', 'elementor' ),
                'description' => __( 'Write color as red or blue etc.', 'elementor' ),
                // 'selectors' => [
                //     $class => 'color: {{VALUE}}',
                // ],
            ]
        );

        $this->end_controls_section();
    }
    
    protected function render() {
        $settings = $this->get_settings_for_display();

        $output = '<span class="' .  $settings['class'] . '" >' . $settings['class'] . '</span>';
        echo $output;
    }
```

**Comment by zeinnicholas** [comment]
Just saw this on one of the Facebook groups:

https://letswp.io/selectors-elementor-control-css-values/

**Comment by davidalbert8** [comment]
Thanks for the link.
I have seen some of these examples in other articles.
The following example seems a bit similar to what I am looking for but it is not given with any example:
`{{other.SIZE}}`
**Obtain values from other controls using VALUE, SIZE, UNIT, or any named value.**

I tried but it doesn't work, in my example I tried the following code:
```
'selectors' => [
                    '{{class.VALUE}}' => 'color: {{VALUE}}',
                ],
```

But I really need the class as a variable to check some basic things as normal PHP code and then use it in the next control as a selector.

**Comment by zeinnicholas** [comment]
> Thanks for the link.
> I have seen some of these examples in other articles.
> The following example seems a bit similar to what I am looking for but it is not given with any example:
> `{{other.SIZE}}`
> **Obtain values from other controls using VALUE, SIZE, UNIT, or any named value.**
> 
> I tried but it doesn't work, in my example I tried the following code:
> 
> ```
> 'selectors' => [
>                     '{{class.VALUE}}' => 'color: {{VALUE}}',
>                 ],
> ```
> 
> But I really need the class as a variable to check some basic things as normal PHP code and then use it in the next control as a selector.

This is new to me. Does CSS accepts classes as values? I know about vars, but not classes. I think this approach only applies to the builder JS framework. My guess is that you would need to create a custom script to handle that check. But I could be totally wrong. I'm not the most expert dev, I just know my ways around and understand langages... Sorry, that's the most I can help.

**Comment by davidalbert8** [comment]
@zeinnicholas thanks for your help.
Hopefully Elementor team and other experts will help to handle this. There must be a simple way to do this because it is a basic need of development to use the value of one control in another control based on some conditions. I know WPBakery is not a front end editor like Elementor but I apply a lot of conditions and amendments to one control value and then use it in another control, I was expecting the same simplicity but spent weeks but no success.

**Comment by rami-elementor** [comment]
Hi @davidalbert8

This is a bad practice, we don't allow using one control values inside another control selectors.

It can return JS errors and in some cases break sites.
