### ISSUE TITLE
✅ 🚀 Feature Request: Hide Elementor Pro subscription email in the license page

### ISSUE THREAD

**Issue by KHRifat** [elementor/elementor#10565]
Hello,

Now Elementor Pro is showing the license Owner Email Address, It's not a matter for the Single Site Owner but bad for the Developers (Expert License Owner) because every client gets the developer's account email address.

Not only that, After building the site most of the client hires 3rd party Developers from Freelancer Platforms for small tasks/customizations or Other peoples for Business. That means not only the client, lots of technical/non-technical or marketers getting Account Email. This is just breaking Personal Confidentiality.

Now I am getting lots of spam emails to my Elementor Account's Email, any email spammer got my email & set it for spam. Developer & Developer are Direct Competitors, Who know about the Bad Guy If anyone tries to Hack the Elementor Account or Confidential Email Address.? It will ruin the business.

So please change your activation system & hide the Email Address that is used to Activate the Plugin.

Thanks

**Comment by Ersonusaini** [comment]
Right

**Comment by KHRifat** [comment]
Thanks @Ersonusaini

**Comment by bekreative** [comment]
Just wanted to express my thoughts on this as well.

It is a bad practise for numerous reasons, but firstly for personal information protection. Just to mention GDPR, we have not signed up to have our personal email address given out and what is more concerning is that it is half of our login detail to Elementor.

Just as in the main post, freelancers can operate on a website without our knowledge and even with user roles, they would need access to EPRO functions. 

Please let it be a simple active / de-activate button and leave our account email address out of sight.

(I had this issues raised in my community a few times from others who build websites for clients too)

**Comment by thomasdiesenreiter** [comment]
Yep, bugs me too. +1

**Comment by DownUnder1** [comment]
In the meantime, I reached out (for my first time) to Elementor Pro support. Let's just say it was "memorable" to say the least. Anyway, a short term solution could be make a must use plugin and add:
`add_action('admin_head', function() {
  echo '<style>
    .wrap.elementor-admin-page-license form.elementor-license-box .e-row-divider-bottom {
        display:none;
    }
  </style>';
});`

**Comment by bill393** [comment]
Unfortunately the problem persists to this day.

**Comment by nicholaszein** [comment]
Hello there!

It's been a while now that the subscription email only appears for the user who activated the license, and no one else. Each user now has their own connection with the Elementor Library, and can activate their own licenses for other products, like the new AI features.

I'm closing this issue as solved.

Regards
