### ISSUE TITLE
Make Theme Styles available when creating a Single in Theme Builder

### ISSUE THREAD

**Issue by Bovelett** [elementor/elementor#10564]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Right now the Theme Styles option is only available from within a regular page. I am not sure if this is on purpose, so that is why I call this a feature request and not a bug. 

However, having access to theme styles when designing a blog or page template (using a Single) seems very logical to me. As a designer I have no interest in setting up styles from within a regular page that I would normally never make. My sites are all based on Elementor templates I create, using custom fields, so my customers only have to fill out fields in the backend, can even do this from a smartphone that way, and don't ever get their hands on any kind of WYSIWYG editor where they can change colors and styles.

**Describe the solution you'd like**
Make Theme Styles available when creating a Single in Theme Builder.

Thank you, and lots of love from Germany!

- Anne

**Comment by srcek** [comment]
My thoughts exactly! Thank you for posting this.

**Comment by RipGill** [comment]
+1

**Comment by tomas-eklund** [comment]
Also, it would be handy to be able to access Theme Style when creating/editing header, footer and other kind of Theme Builder templates.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.9.1

Feel free to update

Thanks!
