### ISSUE TITLE
⛔ 🔗 🚀 Feature Request: Elementor 3.0 - Animated Hamburger icon (Duplicate of #3275)

### ISSUE THREAD

**Issue by GFCreation** [elementor/elementor#10577]
Hello, For the version 3.0 of Elementor as much to mark the blow.

Currently there are shortcodes to make an animated hamburger menu.

The problem is that for a user who does not know the concepts of css / js it is complicated. Why not include it in the pro version?
And also at the same time give the possibility of adding a cooldown or anti spam on the closed / open button, of the popup / menu

https://elementorcodes.com/animated-elementor-hamburger-menu-icons/

**Comment by shilo-ey** [comment]
I merged this issue with #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
