### ISSUE TITLE
Elementor 3.0 - Page transition 

### ISSUE THREAD

**Issue by GFCreation** [elementor/elementor#10576]
Hello, forgive my level of English ...

My idea for the pro version would be to add page transitions, fade in, slide, bounce and more ...
With the addition of a transition page, you would also have to add a page loader to clean up everything. I await your feedback :)

**Comment by 79ho3ein** [comment]
Do you mean page loader such a feature?
![loading_xxi](https://user-images.githubusercontent.com/77163248/125266654-466b6e80-e31b-11eb-8342-10fde583c8d1.gif)

**Comment by 79ho3ein** [comment]
@DorShahar 
Will we see this feature in 2021?
I saw page transtion in the video released by elementor for 2021. Is this the same feature?

**Comment by alexandra9941** [comment]
Is there an approximate time for its publication?

**Comment by d19dotca** [comment]
If you are following the Dev Edition of Elementor you'll see that the 3.4.0-dev builds currently adds a Page Transitions Site Setting (which I can't quite get to work yet but maybe I'm missing something), so I'd assume this will be coming in 3.4.0 soon (probably in the next month or so).

**Comment by 79ho3ein** [comment]
@d19dotca 
Thank you my friend. It was very good news.

**Comment by 79ho3ein** [comment]
It exists in version 3.4, but is only displayed and has no functionality. I think it will come with elementor pro.

**Comment by jpgif** [comment]
Amazing News !!!!! Thank you!

**Comment by creativeart** [comment]
It seems it was deleted in the 3.5 version, I do not see anymore the page transition in site settings :(

**Comment by 79ho3ein** [comment]
@creativeart 
I still see it in beta. But it has nothing special and is just an image that @d19dotca sent before.

**Comment by creativeart** [comment]
Strange, here I see it in the experiment tab on active. But I don't see it in the site settings. Do you have a print screen for me ? Perhaps I look at the right place since we do not have documentation for dev edition :D

**Comment by 79ho3ein** [comment]
I can not adjust it either. Only one image is available in the dev version.

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
