### ISSUE TITLE
Update controls

### ISSUE THREAD

**Issue by Tim567** [elementor/elementor#10570]
Hello,

I am working on a custom plugin for elementor.
Now I want to add controls based on value of differnt controlls.
F.E.
`if($settings['type'] == 'images') $this->add_control(...) `
I can make this work if i reaload the page and the controls update.
I want to force update the `_register_controls()` function
How can i make this work?

**Comment by davidalbert8** [comment]
Hello,

I checked your code and tried some other examples of similar types of codes but this even don't work for Update and Refresh, to check this try to add another widget to the page as well and make the first one value to match the if condition and the second widget shouldn't match the if condition and Update and Refresh the page and see the new control is added to both the widgets. The new control should be only added to one of them. This code checks the condition of the first widget and apply the same results to all of the widgets on the page.

I tried the same examples with styles as well to change text color but unexpected results.

I am still searching, if you find a solution please let me know.
