### ISSUE TITLE
Headers and Footers Coding

### ISSUE THREAD

**Issue by meetingingorkipark** [elementor/elementor#10586]
Hello,

I love Elementor. Thank you for your work!
Why don't you guy add an option to add paste tracking codes into Headers or Footers of each page?
So that it was like an element (similar to HTML) that one can add before the very first section of a page or after the last one. 
After a tracking code is pasted inside, it won't affect the way how a webpage looks like. So for example if it is pasted in the header above the first section, it won't shift it lower but a code will still exist and that could be checked or edited in the Editor.

Or alternatively just make it able to customize it in similar to this way:
https://www.loom.com/share/ef5dff16da864166b8935be691308133

Thank you.

**Comment by jazir5** [comment]
To add to this, it would be greatly appreciated if you could build in native functionality for tracking via google analytics. There are 3rd party solutions, but they're really all subpar. An official tracking implementation would be very useful.

**Comment by ikoba218** [comment]
Yes, you can hook the wp_head, but only when it is canvas. So for your problem, you just need to "add_action('wp_head', 'your_function'). But just when you are using the canvas model in page. What about the moment when I'm using custom header and footer? I didn't find any hook on custom header and footer. If you hook the wp_head when you are using custom header/footer, you get the html inside the body, not inside the properly place (before /head ). I think it is not so difficult to do an action for custom header/footer. But I'm not sure. Is it?

**Comment by d19dotca** [comment]
Hopefully this feature could be used for anything needed in the header / footer, not just Google Analytics. For example I use Matomo (formerly Piwik) analytics instead, hopefully someone in my boat could use this feature too. 

This might be pushing it, but an extension of this feature request might be whether to apply the header / footer code depending on the role used for the visitor. I.e. analytics wouldn't run if it's an admin logged in, for example. I'm sure there's more examples too beyond just analytics that may not / should not run for administrators who are logged in.

Something like that would completely replace the plugin I'm using to achieve this now. :-)

**Comment by fuzenco** [comment]
> This might be pushing it, but an extension of this feature request might be whether to apply the header / footer code depending on the role used for the visitor. I.e. analytics wouldn't run if it's an admin logged in > 

That would be amazing. An easy way to not distort Analytics data by company personnel.

**Comment by jazir5** [comment]
Taking this even further, if you could make it so we could trigger tracking events for individual widgets, that would be great.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
