### ISSUE TITLE
Incorrect FontAwesome webfont is being loaded, loads FA Free instead of FA Pro when correctly set-up

### ISSUE THREAD

**Issue by artifex-media** [elementor/elementor#10595]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
- [x] I disabled all plugins except Elementor to see if the issue still persists; yes
- [x] I do not have FA v4 fallback turned on, turning it on did not help anyway.
- [x] My Kit ID is correct
- [x] I have a valid pro license for Elementor + FontAwesome
- [x] FontAwesome Kit is set to use the latest version(s).

## Description
Using the latest versions of WP, Elementor + Elementor Pro. I have set-up the FontAwesome integration within Elementor by entering my Kit ID, validated it and re-generated the CSS files (just in case).

When opening the icon library most of the icons are not being loaded, due to the wrong family call. 
![image](https://user-images.githubusercontent.com/43996366/74727515-8f5fe600-5241-11ea-96aa-da6c1e3a9791.png)

The all.min.css calls the FontAwesome Free webfont instead of the Pro one, causing most icons to be broken.
![image](https://user-images.githubusercontent.com/43996366/74727617-bcac9400-5241-11ea-910d-758f2900f9d1.png)

## Steps to reproduce
Use latest WP, Elementor + Elementor Pro version, enter a valid FontAwesome Kit ID, re-generate CSS file(s) if needed and try to pick an icon from the library. 

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active and Elementor's Hello theme + Child theme.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.3.20
	PHP Version: 7.2.19
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://nieuw.texelinformatie.nl
	Home URL: https://nieuw.texelinformatie.nl
	WP Multisite: No
	Max Upload Size: 900 MB
	Memory limit: 265M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: nl
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.7
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.8.7
		Author: Elliot Condon

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Compress JPEG & PNG images
		Version: 3.2.1
		Author: TinyPNG

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Ele Custom Skin
		Version: 1.3.10
		Author: Dudaster.com

	Elementor
		Version: 2.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.4
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		button : 4
		heading : 2
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 3
	header : 2
		button : 5
		heading : 10
		icon : 7
		icon-box : 9
		icon-list : 1
		nav-menu : 2
		search-form : 1
		text-editor : 2
		theme-page-title : 1
		theme-site-logo : 2
	loop : 1
		heading : 3
		icon : 1
		icon-box : 1
		text-editor : 1
	page : 1
		theme-site-logo : 1
	wp-page : 1
		divider : 1
		form : 1
		heading : 10
		icon-box : 26
		image-carousel : 1
		posts : 1
		slides : 1
		text-editor : 2

== Log ==
	
JS: showing 4 of 4JS: 2020-02-17 11:54:25 [error X 1][https://nieuw.texelinformatie.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view30400\") has already been destroyed and cannot be used. 
JS: 2020-02-17 11:54:51 [error X 1][https://nieuw.texelinformatie.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view69\") has already been destroyed and cannot be used. 
JS: 2020-02-17 12:04:12 [error X 1][https://nieuw.texelinformatie.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view72\") has already been destroyed and cannot be used. 
JS: 2020-02-17 13:20:27 [error X 1][https://nieuw.texelinformatie.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view84\") has already been destroyed and cannot be used. 

PHP: showing 1 of 1PHP: 2020-02-17 13:14:18 [notice X 1][/home/texelinfor/domains/nieuw.texelinformatie.nl/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::210] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by Prontoshine** [comment]
+1 I got the same issue here.

![image](https://user-images.githubusercontent.com/17017699/74744816-72550280-5295-11ea-9612-3d6e79faafe8.png)

**Comment by jayakornk** [comment]
+1 Have the same problem here too!!!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.7

Feel free to update

Thanks!

**Comment by artifex-media** [comment]
> This issue has been resolved in Elementor v2.9.7
> 
> Feel free to update
> 
> Thanks!

I don't have any update available? Currently running 2.9.6 free and 2.9.1 pro, no updates available.

**Comment by artifex-media** [comment]
Resolved, thanks a lot.
