### ISSUE TITLE
Page builder not loading after 2.9.2 update, conflict with MainWP Child plugin

### ISSUE THREAD

**Issue by sam-moreton** [elementor/elementor#10598]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

After updating to Elementor 2.9.2 with MainWP Child plugin installed, you can't load the Elementor page builder until you deactivate the MainWP Child plugin. This disconnects your site from your MainWP dashboard. 

It works fine once you reactivate and reconnect your site.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
