### ISSUE TITLE
SUPPORT TICKET ACCOUNT

### ISSUE THREAD

**Issue by TheBigBanik** [elementor/elementor#10608]
Hi, since Elementor Pro is a premium plugin for users that need advanced features and support, how we can't have a support ticket account page to review our tickets or reply or come back and close them? By creating every time new tickets we cannot follow or guide you for issues concerning previously tickets. Every large company has a personalized account for tickets. Please, take this under consideration, we need to have a history of our tickets and their solutions.

**Comment by ocbroadband** [comment]
Isn't this what your referring to?
![image](https://user-images.githubusercontent.com/13633011/74841323-612fe400-52dd-11ea-9a81-ab30bdd5f827.png)

**Comment by TheBigBanik** [comment]
<https://angryparrot.gr/>

*Ticket account*

Hi, I wasn't talking about the Github tickets but Elementor Support tickets
that we create through Elementor's website. I am not sure if these two are
related but since I have created many support tickets inside Elementor's
website, I would like to have a ticket history page in my account, not in
Github.




Πλάτωνος 9 Ανατολή, Ιωάννινα
Τ_2651066987 Κ_6972923992
www.angryparrot.gr

[image: facebook] <https://www.facebook.com/angryparrotstudio/>

**Comment by ocbroadband** [comment]
Gotcha.  I don't think they are related as the base Elementor as you know is free.  I wasn't aware that users that did not purchase the pro version can submit support tickets with the 'free' version, so this is a bit beyond my knowledge.  Be interested to see what the response is.  Good Luck!

**Comment by TheBigBanik** [comment]
I have the Expert plan of Elementor, not the free plugin. That is why I need this ticket system. Thank you for the understanding.

**Comment by gitskessa** [comment]
I agree -- I have a Pro plan and I'm currently waiting for a response from a ticket I submitted four days ago (via my.elementor.com), and there's apparently no way for me to even view my tickets in my account.  Seems to be the best page-builder available, but the support is frustratingly lacking.  Providing a way for paying users to view their tickets would be one step in the right direction.  Thanks.

**Comment by arielk** [comment]
This is something we plan to add in the future. 

Thanks for your feedback!

**Comment by mikekl2** [comment]
Soon, please.

**Comment by douvan** [comment]
Dear Elementor team,

I am writing to request that you implement a fully functioning ticket system for your paid users, where they can see their own ticket history, follow up, and reply to tickets from within the system. As a paying customer of your service, I believe that having a reliable and efficient way to communicate with your support team is crucial.

While the option to reply to tickets via email may seem convenient, it is not always reliable, and it can be difficult to keep track of past tickets and their status. By implementing a dedicated ticket system, you can ensure that all customer inquiries and issues are tracked and addressed in a timely and organized manner.

Not only will this improve customer satisfaction and loyalty, but it will also help your support team to manage and prioritize tickets more effectively. With a centralized system in place, your team can easily see which tickets have been resolved and which ones require follow-up, reducing the risk of tickets falling through the cracks.

Overall, I believe that having a fully functioning ticket system will greatly benefit both your customers and your team. Thank you for your attention to this matter, and I look forward to seeing this improvement implemented in the near future.

Sincerely,
Doug
