### ISSUE TITLE
Elementor w/o WordPress

### ISSUE THREAD

**Issue by MichaelNino** [elementor/elementor#10603]
Can Elementor be used independent of WordPress? It would be worthwhile for our projects and we would purchase a license for such an implementation.

**Comment by badwebdev** [comment]
You're asking them to develop an entire standalone CMS platform and lose all of the other functionality that WordPress brings with it?

**Comment by MichaelNino** [comment]
I am an software engineering with 30 years of experience.  I am considering
purchasing Elementor and incorporating it into a brand new CMS.
Unfortunately WordPress is an antiquated CMS that does not expose modern
programming API or methodology.  thank you and please let me know if this
is possible and worth pursuing.

**Comment by MichaelNino** [comment]
I have selected this framework instead. Thank you for your time.

https://grapesjs.com/docs/#what-is-grapesjs
