### ISSUE TITLE
Feature Request: Left & Right Margin Override on Sections

### ISSUE THREAD

**Issue by bitojoe** [elementor/elementor#10601]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Scenario where this would be required**
Say you are building out a section where the first column includes a background image and the second column has textual content which describes the image.. Okay, but now you want the column with the image to stretch to the edges of the screen / section. In order to accomplish this, you must set the parent section to "Full-Width" and ensure the section has 0 padding around. However, by setting the section to "Full-width" we have lost our inherited margins because the section no longer has a max-width. 

**Actual Problem**
To get back somewhat of an inherited margin we can use an inner-section with a set max-width (typically half of what the normal max-width is on the page).... but the content will float center because elementor does not allow you to adjust the left or right margin of sections, as seen below:

![Screen Shot 2020-02-18 at 12 05 51 PM](https://user-images.githubusercontent.com/32885889/74759664-25e2d600-5247-11ea-9ecd-0fa730e542aa.png)

**Alternate / current solution**
I'm fine with making css changes so the past while I've been adding a class to the inner-section and targeting the class responsible for the max-width to set the `margin-left: 0px;` or `margin-right: 0px;` depending on which way I want the section to float so that it looks like this:

![Screen Shot 2020-02-18 at 12 05 59 PM](https://user-images.githubusercontent.com/32885889/74759676-2b402080-5247-11ea-834c-35eabd2d82a5.png)

**Solution I'd like / Feature Request**
However, even touching the css could be prevented if elementor had an override for allowing you to edit the left & right margins of sections... Maybe in the form of a right-click on the locked margin icon in sections and inner-sections.

Thanks!

**Comment by arielk** [comment]
Thanks for your feedback we will consider it in the future, right now we are not to plan to change it for many reasons.

Thanks
