### ISSUE TITLE
Social Icons Facebook Icon always displays round "recommended" icon

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#10600]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using the social icons or social share feature in elementor, it will not allow users to use the facebook-f icon (https://fontawesome.com/icons/facebook-f?style=brands). Instead it always shows the Facebook Icon (https://fontawesome.com/icons/facebook?style=brands).

This happens despite the fact that I select the facebook-f icon from the list of icons and the intention is to explicitly set that icon and not have the default icon.

## Steps to reproduce

1. Add a "Social Icons" widget.
2. Add a new Icon, select Icon Library > Switch from Recommended to All Icons and select the facebook-f icon.
3. Save.

The preview shows the correct icon. When viewing the live site, the facebook-f icon gets replaced by the default facebook icon. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Not Applicable, issue occurs on any configuration and other icons work fine.
```
</details>

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9110, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
