### ISSUE TITLE
Add to cart dynamic link for button

### ISSUE THREAD

**Issue by DoctorSte** [elementor/elementor#10607]
Having a dynamic link for adding to cart via a regular button would be great. 
The Add to cart button isn't that customisable, you can't add an icon or remove Quantity. 
The Custom add to cart doesn't support a dynamic product.

It would make things way easier for certain use cases.

**Comment by shay1383** [comment]
+1

**Comment by hamed1988** [comment]
Yes that would be great

**Comment by wordxpression** [comment]
+1, would be great indeed. Also... it would be good if optional after pushing the button there can be a redirection to either the cart or checkout page.

**Comment by Chadyka** [comment]
+1, I still miss this bad

**Comment by tobiasfeistmantl** [comment]
+1

**Comment by bilbodog** [comment]
Needed. +1

**Comment by shay1383** [comment]
Any update on this?

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
