### ISSUE TITLE
Suddenly after Update 2.9.0

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#10613]
Hello Elementor Team,
Suddenly after Update 2.9.0 some parts of our custom control for elementor stops working. We have debugged it.
In elementor\core\files\css\base.php file, line 340
When the task is confronted with an issue, "foreach" stops working and this causes other values not to work either. Please change "return" to "continue" so the render style issue would be solved for us.
We can create a test drive for you to check it

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
