### ISSUE TITLE
rel=nofollow and target='_blank' is not working

### ISSUE THREAD

**Issue by dezinux** [elementor/elementor#10616]
If there is an external link on the website and I want this to be attributed to 'nofollow' with target='_blank' and I checked the checkboxes under link settings on the elementor frontend editor. but I don't know why it is not working. I also inspected the source code and console, its showing like `<a rel href="THE EXTERNAL LINK">`
Please look at the screenshot below & fix this.

![FB_IMG_1582201698035](https://user-images.githubusercontent.com/61277919/74934552-7bb4ab00-540c-11ea-83e4-43cc2fa3e29c.jpg)

**Comment by shilo-ey** [comment]
Thanks for reporting,

We can't reproduce your issue.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
