### ISSUE TITLE
Animated headline bug

### ISSUE THREAD

**Issue by CKBarzin** [elementor/elementor#10621]
The animated headline got jacked up on my site too. The static text bunches up on the left while the dynamic text does a weird thing to the right 

I had to jimmy rig it using normal headline mixed with animated headline to kind of fix it

**Comment by robert-neacsu** [comment]
I have the same issue with my title page and the only thing to do it working is to mix animated headline with normal.

**Comment by ianandersonmedia** [comment]
I have just noticed this on my site as well. It was working perfectly, but now the 3 lines of text (static, animated, static) are in 3 columns. See attached pic.
<img width="582" alt="Screen Shot 2020-02-24 at 10 10 58 am" src="https://user-images.githubusercontent.com/12944469/75122893-31724900-56ee-11ea-8f8d-aa82851e0417.png">

**Comment by KoshaK0** [comment]
Same here...

**Comment by berdini** [comment]
Same...  after 5 days 0 answers, very disappointing

**Comment by berdini** [comment]
ADD in Advanced / custom CSS the following text:
 
/*Animated Headline Widget Fix*/
.elementor-widget-animated-headline .elementor-headline
{
display:block;
}

**Comment by shilo-ey** [comment]
I merged this issue with  #10585, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
