### ISSUE TITLE
Customise Nav Menu (Elementor Pro)

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#10629]
It would be nice to be able to add 1 button in the Nav Menu widget and a search bar (and why not social network icons), it would also allow menus to be standardized on mobile. It would also enrich the widget in question.

**Comment by adrianionescuid** [comment]
Talking about menus, I would like to see a clear differentiation between main and mobile (CSS class names). It would make it easier to add specific code.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
