### ISSUE TITLE
Lightbox modal problem

### ISSUE THREAD

**Issue by NenadObradovic** [elementor/elementor#10622]
Hi guys,

Could you please consider to improve your modal lightbox selectors to work only for your elements and not for global a html tag?

**elementor/assets/js/frontend.min.js** main js file
function **module.exports = elementorModules.ViewModule.extend** 
selectors -> **links: 'a, [data-elementor-lightbox]',**

Because if we want to create our custom element ( shortcode, widget, etc. ) with lightbox functionality, we will always get the problem, that 2 modals will show up, one ours and another yours. https://imgur.com/NWbH2sx

This might be the general problem for any other plugins/themes which have lightbox functionality.

Thanks for your time.

Best regards,
Nenad

**Comment by shilo-ey** [comment]
Hi @NenadObradovic 
Thanks for your feedback.

You can go to any editor page, and under Global Settings > Lightbox tab > switch off "Image Lightbox" and then only widgets you specifically selected to use Elementor lightbox will use it.

Thanks
