### ISSUE TITLE
✅ Support Question: How can I dequeue/deregister/remove swiper from selected pages, or at least, my front/home page?

### ISSUE THREAD

**Issue by schecteracademicservices** [elementor/elementor#10632]
How can I dequeue/deregister/remove swiper from selected pages, or at least, my front/home page?

I have only one page that requires swiper, and would like it loaded and active only there. Tried a variety of snippets, all of which failed, so I figured I'd ask the source.

I can remove it everywhere using Asset Queue Manager, but then the Elementor editor will only work in safe mode.

Thanks!

**Comment by forna91** [comment]
Maybe is too later, but it's easy:

```

function remove_jquery_sticky() {
    if ( ! is_admin()) {
       (if ! is_page( 'page_id' )) {
		wp_dequeue_script( 'swiper' );
		wp_deregister_script( 'swiper' );
    }
}
}
add_action( 'elementor/frontend/after_register_scripts', 'remove_jquery_sticky' );
```
I didn't try it but shold work! Take care, u need to replace is_page with is_post if is a post the "page" where u need swiper

**Comment by colmtroy** [comment]
Given all the changes to asset loading with Elementor in the recent past, is there a documented way of selectively dequeuing Swiperjs now? It looks like dequeuing it using wp_dequeue_script now will dequeue a lot more than just Swiper.

**Comment by marekmaurizio** [comment]
Would be interested too.
Given their level of developer support, i don't expect one.

**Comment by wppoland** [comment]
Just mind the parenthesis
```
function remove_jquery_sticky() {
	if ( ! is_admin()) {
		if (!is_page( 'page_id' )) {
			wp_dequeue_script( 'swiper' );
			wp_deregister_script( 'swiper' );
		}
	}
}
add_action( 'elementor/frontend/after_register_scripts', 'remove_jquery_sticky' );`
```

**Comment by colmtroy** [comment]
@wppoland this method doesn't work anymore afaik

**Comment by nicholaszein** [comment]
Hello there!

This issue has been resolved with the **Improved Assets Loading** feature of Elementor. The Swiper library will only load when there are elements that use it. Therefore you don't need to use any technique to dequeue the Swiper.JS file.

To enable this feature, use the latest version of Elementor go to your WordPress _`Dashboard` > `Elementor` > `Settings` > `Features`_ and Activate the _**Improved Assets Loading**_ feature.

I hope this helps.

Kind regards
