### ISSUE TITLE
Lightbox (Galery Pro) don't show captions/descriptions 

### ISSUE THREAD

**Issue by myfriendlead** [elementor/elementor#10648]
The lightbox in Global Settings are correctly. 
- Captions on
- Image with captions/description
- Media File selecttec at link section in the Galery. 

But they are not showing!

**Comment by lior-sh** [comment]
Hi @myfriendlead,

Thanks for reporting, we cannot reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
