### ISSUE TITLE
Additional buttons for Elementor slide

### ISSUE THREAD

**Issue by darrencon** [elementor/elementor#10644]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The ability to add more than one button to an elemetpr pro slide

**Describe the solution you'd like**
I would like to be able to add more than one button to a slider. My current requirement is 3 buttons
**Describe alternatives you've considered**
There is an option to use 3rd party plugins but they require a custom section template to be made. It would be easier to add additional buttons on the elementor slides
![elementor slides](https://user-images.githubusercontent.com/25427644/75155065-d9e8d300-5717-11ea-962d-bbcb8d35d912.PNG)
.

**Additional context**

**Comment by buszmen201** [comment]
As a workaround i can say you can create templete for every page with as many as you need buttons of your slider and use shortcode in description field

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10176, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
