### ISSUE TITLE
[Feature Request] Additional breakpoints in responsive mode

### ISSUE THREAD

**Issue by ShaneLynam** [elementor/elementor#10650]
I've often run into issues where I'd like to change styles for different sized devices not included in responsive mode at the moment. These are mainly devices above 1024px. I develop on a widescreen monitor however some designs I create need to be tweaked for smaller screens such as laptops and the likes. I usually just write media queries but it would be helpful if Elementor had some additional breakpoints.

**Comment by artifex-media** [comment]
+1

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/2043
