### ISSUE TITLE
Cannot edit Homepage

### ISSUE THREAD

**Issue by PetoFeFe** [elementor/elementor#10652]
Hello,

i am using Elementor. I edited homepage and after create other 3 pages with elementor. Now i cannot edit this page or load it on frontpage. It shows me this error:

Fatal error: Uncaught Error: Class '' not found in /wp-content/plugins/elementor/includes/managers/elements.php:86 Stack trace: #0 /wp-content/plugins/elementor/includes/base/element-base.php(359): Elementor\Elements_Manager->create_element_instance(Array, Array, Object()) #1 /wp-content/plugins/elementor/includes/base/element-base.php(970): Elementor\Element_Base->add_child(Array) #2 /wp-content/plugins/elementor/includes/base/element-base.php(313): Elementor\Element_Base->init_children() #3 /wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(111): Elementor\Element_Base->get_children() #4 /wp-content/plugins/elementor/core/files/css/post.php(290): Elementor\Core\DynamicTags\Dynamic_CSS->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array) #5 /wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(112): Elementor\Core\Files\CSS\Post->render_styl in /wp-content/plugins/elementor/includes/managers/elements.php on line 86

I'am using Elementor 2.9.2 with Wordpress 5.3.2
Thanks for help

**Comment by rami-elementor** [comment]
Hi @PetoFeFe is this still relevant in the latest version of Elementor (3.6)?
