### ISSUE TITLE
✔️ 🐞 Bug Report: Accordion - Theme style link defaults don't inherit

### ISSUE THREAD

**Issue by ocbroadband** [elementor/elementor#10651]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

1) Update default 'link' settings to a specific style within Theme Styles.
2) Create a page with an accordion module.
3) Place links within the body of an accordion item body.

The links do not follow the Theme Style settings(inherit).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.3.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 260M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://dev.xxxxx.info
	Home URL: https://dev.xxxxx.info
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -8
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.6.2
		Author: Frank Goossens (futtta)

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Elementor
		Version: 2.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.4
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 2.0.3
		Author: WebMat

	JetBlocks For Elementor
		Version: 1.2.1
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.2.9
		Author: Crocoblock

	JetEngine
		Version: 2.2.3
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.3
		Author: Crocoblock

	JetSmartFilters
		Version: 1.7.0
		Author: Crocoblock

	Wordfence Security
		Version: 7.4.6
		Author: Wordfence

== Elements Usage ==
	
	archive : 2
		jet-listing-grid : 1
		theme-archive-title : 1
	footer : 1
		button : 3
		countdown : 1
		divider : 3
		heading : 6
		text-editor : 3
	header : 1
		heading : 1
		icon-list : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 1
		heading : 1
	wp-page : 3
		accordion : 1
		call-to-action : 1
		heading : 8
		icon-list : 1
		text-editor : 6
	jet-listing-items : 0
		heading : 1
		image : 1
		jet-listing-dynamic-field : 3

== Log ==
	
JS: showing 2 of 2JS: 2020-02-19 05:06:01 [error X 1][https://dev.xxxxx.info/wp-content/plugins/elementor/assets/lib/backbone/backbone.radio.min.js?ver=1.0.4:3:2098] Maximum call stack size exceeded 
JS: 2020-02-19 06:07:32 [error X 1][https://dev.xxxxx.info/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.8.4:2:108366] Cannot read property \'stretch\' of null 

PHP: showing 1 of 1PHP: 2020-02-18 21:29:00 [notice X 1][/home4/xxxxx/public_html/xxxxx-dev/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by nicholaszein** [comment]
Hello there @ocbroadband!

Thank you for taking the time to report this issue, and allow me to apologize for not receiving proper feedback in a timely manner. 🙏 

I've done some tests and found that what you reported does not happen with the latest version of Elementor (3.8). 🙂 

For that reason, I'm closing this issue as Solved! ✔️

Feel free to update your plugin to the new version!

Cheers 🥂
