### ISSUE TITLE
Issue between custom control and elementor

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#10657]
Hi,
**We have an issue and needs your Advice.**
We have developed a Control for Elementor that can style the elements on the page. It performs in 3 general element selectors like:
1. Hover
2. Before
3. After;
Except the neutral selector of the elements.
There’s however, an issue here that I’ll try to explain in depth.
In the “elementor\core\files\css\base.php” path in line “340” (Image num.1)

Screenshot 1:
https://prnt.sc/r78ch1

Before we can explain the reason of this happening, we need to check some of the values.
In the same file, at line 303, most of the times the value of “$external_control_missing” is always ‘false’.
Just like the debug log below:

Screenshot 2:
https://prnt.sc/r78djq

As shown in the image above, in Desktop Property the “$parsed_value” is equal to the created value by our developed style control.
Up until now we haven’t faced any issues and all the styles of this section are rendered correctly. But this is only one of our many selectors of our control center, meaning Hover| After| Before.
That means if the value of any of them is left blank, the value of all of them considered as blank.
For example, if our element doesn’t have any styles on normal statement but it has styles on selectors like Hover and Before, because the normal statement is empty and without any styles, the php interpreter breaks the cycle and returns to top of our foreach loop.
To explain in better words:
We try to search in a ‘foreach’ loop function in an array with 3 values. When we get to an empty value, we return. It is clear that the #1 and #3 have non-empty values and the #2 is empty, when it comes to the second one, it stops the loop, breaks, and never run through #3 condition. (just like the image below). (image #3)

Screenshot 3:
https://prnt.sc/r78cx2

According to the above image if the second value is empty, then the code is stopped and after the search for the second index of the array using the return command the code is stopped and we will only have the value for the first index. However, by changing the return to continue we will overlook the empty values and will let the rest of the indexes to be run.

Screenshot 4:
https://prnt.sc/r78e78

As shown in the image above when the Laptop value is empty, the render for the rest of the styles is not permitted using the ‘return’ code in line 340. So, the styles rendered by Elementor will be not complete in the output. To resolve this, it is necessary to change the value from ‘return’ to ‘continue’ in line 340. This way the render for the styles will be complete in Elementor.

Best,

**Comment by rami-elementor** [comment]
Hi @ghost

Is this issue still relevant?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
