### ISSUE TITLE
⛔ 🧩 🚀 Feature Request: Add Compatibility to YITH WooCommerce Featured Audio & Video Content plugin

### ISSUE THREAD

**Issue by Stegit-dev** [elementor/elementor#10667]
hi, i use elementor pro version with astra pro.
If i use elementor to build with the theme builder a new product site, than i don´t have any possibility to integrate the video-gallery from the plugin "YITH WOOCOMMERCE FEATURED AUDIO & VIDEO CONTENT . If i activate the only astra theme product page i have the feauture below the product image gallery on product site. This means that elementor remove the standard woocommerce hooks.

The problem is now, that elementor remove standard woocommerce hooks.

**Comment by nicholaszein** [comment]
Hello @Stegit-dev,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
