### ISSUE TITLE
[REQ] Sass / Less Support for Custom CSS

### ISSUE THREAD

**Issue by rconcrown** [elementor/elementor#10689]
Title says it all.

It would be lovely to have sass and/or less support for the custom css, i think that would help for cleaner css.

**Comment by rami-elementor** [comment]
Hi @rconcrown ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

Please feel free to contact us again with other feature suggestions.

Regards,
