### ISSUE TITLE
✅ ⛔ 🚀 Theme Style has no options for heading sizes

### ISSUE THREAD

**Issue by kaspergram** [elementor/elementor#10685]
Elementor has a drop-down for selecting  S, M, L, XL and XXL size for a heading element.

This allows for having different sizes H2 for example. This satisfies both SEO and design requirements.

The new Theme Style only allows for styling of the default heading size. Not being able to style the individual styles for each size is a huge omittance. The power of the theme style lies in the ability to preconfigure sizes for each H-tags thus mitigating the need for the content creator to size each individual element. 

![Screenshot 2020-02-27 at 12 15 54](https://user-images.githubusercontent.com/11805646/75440152-823aa980-595b-11ea-9ec8-7f0d77d0347c.png)

**Comment by m0n0mind** [comment]
This should be fixed as it leads to inconsistent heading sizes.
Many CSS-frameworks make it possible to decouple heading sizes from its semantics by applying class modifiers, i.e.
`<h1 class="is-h3">Some title</h1>`
Maybe this could also be implemented here?

**Comment by m0n0mind** [comment]
So, almost 2024 and still no progress in this regard.
Sure, go ahead and implement more fancy AI stuff but then also address such rather minor missing pieces that would really make a difference!

**Comment by KimMai212** [comment]
Just stumbled over this once again and can't really understand why this can't be solved by Elementor, instead of me having to adjust every size for every style in the CSS…

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your contribution and your patience!

This feature was introduced with the Elementor Site Settings in version 3.0.0. You can already set individual styles for each heading size under the Typography section in the Site Settings.

As for the size options in the Heading widget, these were deprecated as they are not compatible with our plans for introducing a class-based system for all elements. 

For these reasons, we are closing this issue.

Kind regards
