### ISSUE TITLE
🔗 🚀 Feature Request: Processing Elementor Forms (Duplicate of #1686)

### ISSUE THREAD

**Issue by ATOPBIO** [elementor/elementor#10680]
Hi all,

I acknowledge this is not meant for support questions but I hope this turns out into a feature request/expansion of the awareness towards the power of Elementor. I was advised to submit this question to Github by the Elementor e-mail support team.

I am using forms on Pro and don't seem to find a way to process submissions with a PHP script, I tried using the webhook action and inserting the integration URL to the directory of the PHP file containing the script, but it is not working.

Is a webhook meant to process such an action, if not is there an alternative method? The PHP script is meant to insert the data into the database. Perhaps there is a certain way to write the PHP in order to understand Elementor?

Many thanks in advance and all the best with your amazing development

**Comment by daffneele** [comment]
I second that issue. 
All I get for the 'elementor_pro/forms/process' is parse error. Function is empty but a small print_r just to see it is getting there. Do I need to return some value? Do I need to use the ajax-handler. The  Form API documentation is not enough to use these actions. Something is missing...

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1686, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
