### ISSUE TITLE
Add Global Theme Style in when editing Theme Builder Template

### ISSUE THREAD

**Issue by Alipio123** [elementor/elementor#10694]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can't see the Global Theme Style Option when creating a Theme Builder Template

**Describe the solution you'd like**
Add Global Theme Style Option when creating a Theme Builder Template

**Comment by shilo-ey** [comment]
I merged this issue with  #10564, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
