### ISSUE TITLE
Image Alignment Issue with Content

### ISSUE THREAD

**Issue by healcharity** [elementor/elementor#10699]
When we are adding content in the section we want image bottom to be aligned to the content.
Please go through the attached screenshot and advise.

``
![ContentToBeAlignedToImageBottom](https://user-images.githubusercontent.com/61585326/75546403-7380ef00-5a4e-11ea-995e-bb918ffa9ac8.png)

**Comment by lior-sh** [comment]
Hi @healcharity,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
