### ISSUE TITLE
Hardcoded widget styles that override global Theme Styles

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#10695]
Hello, now that Elementor offers global Theme Styles is there any use case for hardcoding widget styles like [that](https://github.com/elementor/elementor/blob/5d257d0455d17cd4dae7b1d0d21c73d11ecfafb2/assets/dev/scss/frontend/widgets/heading.scss#L10)? They break the global styles and we have to constantly  override them. Ideally, all styles that are available from the "Theme Styles" panel (typography, etc) should be coming from there. Maybe I m missing something?

**Comment by black-eye** [comment]
Yes, there are definitely css rules, which aren’t necessary and cause conflicts. On the other hand, some are designed well and necessary.

Btw, there’s a special issue for the heading line-height rule, you have mentioned: https://github.com/elementor/elementor/issues/10649

**Comment by amyriounis** [comment]
thanks @black-eye. Closing in favor of #10649
