### ISSUE TITLE
full screen height section with background video not displaying full screen on Edge and Internet explorer

### ISSUE THREAD

**Issue by tfelici** [elementor/elementor#10705]
full screen section with background video set to a MEDIA FILE (not youtube video) not not displaying as full screen on Edge and Internet explorer. Only if you set to Youtube video then the video height will be set at full screen as intended.
Problem not occurring on firefox or chrome

to reproduce 
1: create section
2: set size to full screen height
3: set background video to an MP4 file in your media (not a youtube video)

![image](https://user-images.githubusercontent.com/7666764/75611168-ea31f100-5b0f-11ea-9f8d-f6cc1ac8e5c6.png)

**Comment by CursiveQ** [comment]
I have the same issue. It also appears like the screenshot above. Even when setting section min-height to VH 100%. I can confirm it happens with self-hosted videos.

For me, it happens in Chrome, Firefox, and Safari. Usually on pages where the content in the video background section requires scrolling.

**Comment by DorShahar** [comment]
Hi
We are [officially not supporting IE](https://developers.elementor.com/elementor-dropping-support-ie/).
We are suggesting to update to the latest version (I know this post is from ~8 months ago, apologize for the delay)

Thanks
