### ISSUE TITLE
Elementor: Uploading SVG Social Icon Widget

### ISSUE THREAD

**Issue by NomadAndInLove** [elementor/elementor#10719]
Hello.

I was referred to this platform by Elementor Support. I have run into some issue on the social icon widget in Elementor as follows:

I am using SVG files in the social icons widget. This is to avoid loading Font Awesome. I noticed that by using SVG files, I am failing on Accessibility on the Lighthouse Report because the files do not have a discernible name.

My question is, is there a way to add a name to my SVG files so that they pass the audit?

This is what the code looks like if I use Font Awesome as the icon:

< a href="https://www.instagram.com/nomadandinlove/" class="elementor-icon elementor-social-icon elementor-social-icon-instagram elementor-animation-grow elementor-repeater-item-78c13c9" target="_blank" rel="noopener noreferrer"> < span class="elementor-screen-only" >Instagram< /span > < i class="fab fa-instagram"></i > </a >

This is what the code looks like with an SVG file as the icon:

< a href="https://www.facebook.com/NomadAndInLove/" class="elementor-icon elementor-social-icon elementor-social-icon- elementor-animation-grow elementor-repeater-item-f8125db" target="_blank" rel="noopener noreferrer" > < span class="elementor-screen-only" >< /span > < svg>deleted code</svg > < /a >

The Font Awesome icon passes the audit because of < span >Instagram< /span >. How do I add that for the SVG icon?

Regards,

Michael

**Comment by shilo-ey** [comment]
Have you tried adding alt text to your icon?

This should add the corresponding text to your SVG icon.

Thanks

**Comment by NomadAndInLove** [comment]
No. But I added a title attribute and it seemed to have resolved the issue.

Regards,

Michael
