### ISSUE TITLE
Few major features missing in “table of content” widget

### ISSUE THREAD

**Issue by pankajparchani** [elementor/elementor#10721]
i want to add few options while using "table of content" widget but i am unable to do so.
Issues mentioned below:
1. Unable to add pagination to table.
2. unable to add sort or filter option in table header ., as there are too many tabs and content in my table.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input (and sorry for the huge delay in the response).

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
