### ISSUE TITLE
[Feature Request] Dynamic Tags for Target URL at Share Buttons widget

### ISSUE THREAD

**Issue by artifex-media** [elementor/elementor#10729]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This solution will make it able to add share buttons inside (custom) loop templates which will target the URL of the looped post, not the (archive) page you are on. This solution might apply to more widgets than I am mentioning here.

**Describe the solution you'd like**
I would like to be able to select dynamic tags (such as Post URL) on the 'Target URL' setting from the Share Buttons widget in Elementor, instead of entering an URL manually. This will make it able to share posts inside the Posts/Archive Posts widgets with the post's url instead of the page you are on.

**Describe alternatives you've considered**
Using a shortcode to get the looped post URL but that is also not available.

**Additional context**
![image](https://user-images.githubusercontent.com/43996366/75786173-2d38d200-5d65-11ea-8319-c649dcbd6d55.png)
^No dynamic options here :(

**Comment by utsavmadaan823** [comment]
Need this too. So for the time being until it is implemented i tried to tweak the code to implement this thing.
I tried by adding dynamic = active to add_control for social buttons widget this allowed me to assign dynamic tag but dynamic value was not actually used in rendered widget and than i workaround it by adding a default value as required dynamic value to add_control of social buttons widget.

**Comment by maoxiong** [comment]
I requested this nearly a year ago, so I'm glad some others have now jumped on it :)

To fix it until a proper code fix is pushed:

**elementor-pro/modules/share-buttons/widgets/share-buttons.php**
Add:
`				'dynamic' => [
					'active' => true,			
				],	`
To the 'share_url' control.

This will get the dymanic content option showing in the back end, but to get it to render, you need to also edit:

**elementor/includes/base/controls-stack.php**
Search for the line starting with '$frontend_settings' and change to:
`$frontend_settings = array_intersect_key( $this->get_active_settings($this->get_parsed_dynamic_settings(), $this->get_controls()), array_flip( $this->get_frontend_settings_keys() ) );`

**Comment by laboiteare** [comment]
Need this too.

Elementor team, come on !

**Comment by alexandramclarty** [comment]
I need this too. Thanks for the workaround, maoxiong!

**Comment by bpbezerra** [comment]
> I requested this nearly a year ago, so I'm glad some others have now jumped on it :)
> 
> To fix it until a proper code fix is pushed:
> 
> **elementor-pro/modules/share-buttons/widgets/share-buttons.php** Add: ` 'dynamic' => [ 'active' => true, ], ` To the 'share_url' control.
> 
> This will get the dymanic content option showing in the back end, but to get it to render, you need to also edit:
> 
> **elementor/includes/base/controls-stack.php** Search for the line starting with '$frontend_settings' and change to: `$frontend_settings = array_intersect_key( $this->get_active_settings($this->get_parsed_dynamic_settings(), $this->get_controls()), array_flip( $this->get_frontend_settings_keys() ) );`

It's a shame Elementor can't implement something that you've basically already did for them...

Anyway, I wanted to ask you if there's anyway we can implement this and make it "update-proof"? There was another unrelated custom solution another user did and he create some code in which we could upload a PHP file as an mu-plugin, so it would keep working regardless any Elementor update. Here's what I'm telling: https://gist.github.com/pingram3541/37d1d274893fcc40a1e96c5e368c0b99

**Comment by VenkmanNL** [comment]
+1

**Comment by Talita1996** [comment]
+1

**Comment by judagutor** [comment]
@bpbezerra  This code worked for me. Add it as a Code Snippet:
`add_action( 'elementor/element/share-buttons/section_buttons_content/before_section_end', function( $control_stack, $args ) {
	// Get existing control
	$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), 'share_url' );

	if ( is_wp_error( $control ) ) {
	    return;
    }

	$control['dynamic'] = [
		'active' => true,
	];
	// Update the control
	$control_stack->update_control( 'share_url', $control );
}, 10, 2 );
`

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
