### ISSUE TITLE
Swipper breakpoints problem

### ISSUE THREAD

**Issue by NenadObradovic** [elementor/elementor#10722]
Hi guys,

Inside a 2.9.2 plugin version, you implemented some code for your Swiper functionality, and with that code, you override global breakpoints for any swiper slider on any place (other themes, plugins, etc.).

```
var Swiper = function () {
  ...............................
  return Swiper;
}();

exports.default = Swiper;
window.Swiper = Swiper;
```

I force breakpoint values inside custom swiper js code https://imgur.com/a/QB4UNqg and code from your plugin always override it, as you can see https://imgur.com/pvop6Ov .

Could you please check this problem?

Best regards,
Nenad

**Comment by steve231293** [comment]
Hello @NenadObradovic 
You are right, I can also create ticket with same problem 2 weeks ago. [https://github.com/elementor/elementor/issues/10569](https://github.com/elementor/elementor/issues/10569)

Hope that Elementor team can fix it soon.

**Comment by NenadObradovic** [comment]
Hi @steve231293,

Thanks for your response :) I hoop too.

Best regards,
Nenad

**Comment by shilo-ey** [comment]
Hey all, thanks for your feedback, we solved the issue and added option for you to customize it.

Read more here: https://developers.elementor.com/swiper-update-to-5-3-6-new-wrapper-class/
