### ISSUE TITLE
my custom widget does not working with elementor plugin

### ISSUE THREAD

**Issue by highfly1988** [elementor/elementor#10726]
![Screenshot_1](https://user-images.githubusercontent.com/61719134/75734915-90623e80-5d3c-11ea-87d8-5b8921ef3a25.png)
![Screenshot_2](https://user-images.githubusercontent.com/61719134/75734919-93f5c580-5d3c-11ea-96d2-1db0d349ba1b.png)

I added custom widget with a plugin and it is displayed on the admin elementor editor.
But after i finish the editing and publish the page , the page displays nothing.
i.e. it works well on admin dashboard with elementor page editor (preview i guess) , but on the front end , nothing is displayed.
No content was outputed.
Please help for this!

my code is like this:

[campaign.php.txt](https://github.com/elementor/elementor/files/4278811/campaign.php.txt)

**Comment by udidol** [comment]
Hi @highfly1988 ,
Try adding parenthesis to the instantiation of your `profund_Campaign_Boxes` class in the call to `register_widget_type`:
`Plugin::instance()->widgets_manager->register_widget_type( new profund_Campaign_Boxes() );`

**Comment by udidol** [comment]
Also, I would recommend **not** using Slick as a dependency for your carousel, since it is in a deprecation process from Elementor, and will be completely removed from the product probably sometime later this year. We moved all of our carousels to use Swiper.js, and I recommend using that for any carousel you want to integrate into your custom widgets.

**Comment by highfly1988** [comment]
thanks udidol!
but i found the issue and fixed myself.
it is due to post loop in the render function.
the render function is called within the the_content() filter , so in the render() , we can't call the post loop.
so i just changed it from ordinary loop to foreach loop of $query->posts.
and it works well now
thanks anaway!
