### ISSUE TITLE
🔗 🚀 Feature Request: URL/Slug control directly within elementor (Duplicate of #7044)

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#10720]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Currently, Elementor does not allow you to change url's of pages created with elementor within the Elementor interface. Especially if the page is classed as an Elementor Template via the Elementor Template post type. This means i have to make the post type page, post or another to be able to change the slug. 

**Describe the solution you'd like**

I want to control the url of the page directly within the elementor editor in the "Page Settings" section,
![page settings](https://user-images.githubusercontent.com/31750063/75642583-e1fdb280-5bf0-11ea-89a2-f20b308b80eb.PNG) you could perhaps add an editable url box in one of the circled areas where we can manually set the url for the page. Also allow us to set the url of elementor templates we create within the Elementor Template post type so that I can leave pages set to that post type. As is i have to create templates in a post type that allows slug control. 

**Describe alternatives you've considered**

Installing Rank Math and changing the slug from the SEO tab it adds. It would be significantly better if this was natively integrated into Elementor core. 

**Additional context**

I do not ever want to have a query string in any of my urls that contain "Elementor", i have zero interest in letting anyone know the page was created with Elementor, and the urls that contain it are hideous and not easily memorable. I want to have clear, pretty easy to remember permalinks site wide. URL Structure is a key factor which i believe needs some attention.

**Comment by artifex-media** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/7044 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
