### ISSUE TITLE
Update broke the website

### ISSUE THREAD

**Issue by markhaven-music** [elementor/elementor#10736]
Website: https://soundmasters.org

I'm not sure if this is the right way to bug report, it's my first time.

I just updated to the new version and the website is now not working.

This is the error I get:

Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\zoa_page_settings() must be an instance of Elementor\Core\DocumentTypes\Post, instance of Elementor\Core\Kits\Documents\Kit given, called in /home/soundm18/public_html/wp-includes/class-wp-hook.php on line 290 and defined in /home/soundm18/public_html/wp-content/themes/zoa/inc/elementor.php:15 Stack trace: #0 /home/soundm18/public_html/wp-includes/class-wp-hook.php(290): Elementor\zoa_page_settings(Object(Elementor\Core\Kits\Documents\Kit)) #1 /home/soundm18/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #2 /home/soundm18/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/soundm18/public_html/wp-content/plugins/elementor/includes/compatibility.php(69): do_action('elementor/eleme...', Object(Elementor\Core\Kits\Documents\Kit), 'document_settin...', Array) #4 /home/soundm18/public_html/wp-includes/class-wp-hook.php(288): Elementor\Compatibility::document_post_deprecated_hooks(Object(Elementor\Core\Kits in /home/soundm18/public_html/wp-content/themes/zoa/inc/elementor.php on line 15

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @markhaven-music 

As mentioned in the error trace:
```
home/soundm18/public_html/wp-content/themes/zoa/inc/elementor.php on line 15
```

Please contact your theme authors for support in this issue, the issue originates from the theme

Thanks!
