### ISSUE TITLE
✅ 🔗 🚀 Option to apply an reply-to email address to a form, when using auto filled email field (Duplicate of #6691)

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#10731]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using auto filled form fields in the Elementor form widget, with user data from a logged in user, the form can't add the users email to the reply-to field. The user have to manually write the email before the address follows the mail sent.

**Describe the solution you'd like**
As designed now, the reply-to address option has a drop-down where you can choose either the email address the form is send from, or data from the email address field. 

Since the second option only works with a manually typed email address, a solution could be to make it work with an auto filled form field as well. 

Or adding a 3. option to the reply-to, where a shortcode can be added. 

**Describe alternatives you've considered**
Well, I tried to add the shortcode from the email field as the email address the form is send from. This actually works, choosing the first option in the drop-down. The shortcode is simply added as the reply-to email address, and the form sends the auto applied address with the email. But that doesn't seem like a valid solution. 
The only proper alternative is to force the user to type his email address manually, which would be nice to avoid, when the other fields in the form are auto filled from his data.

**Additional context**
Since shortcodes can be used many other places in the form, I think it should be possible in the reply-to option as well. I know it's a tiny issue, hence it has not been brought up before (I hope, or I did a lousy search). But when using the form with a logged-in users data, it would be a great help saving time every time a request is send by that user.

Thanx for reading.
This is my first post on github, I would like to apologise for any errors or miss explaining here.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.7.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
