### ISSUE TITLE
Whatsapp share link does not escape html entities

### ISSUE THREAD

**Issue by vdwijngaert** [elementor/elementor#10746]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Code: https://github.com/elementor/elementor/blob/master/assets/lib/share-link/share-link.js

The whatsapp share link includes the title, but it does not get properly escaped. So if we have a post with let's say a quote in it (" or `&quot;`), when we share it, whatsapp will cut it off starting at the ampersand, for obvious reasons.

**Example:**

`https://api.whatsapp.com/send?text=*Lorem%20pisum%20&quot;dolor%20sit&quot;*%0Atext%0Ahttps://www.example.com
`

Maybe wrap the title in [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), as it should be?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.7
Feel free to update

Thanks!
