### ISSUE TITLE
exit animation control

### ISSUE THREAD

**Issue by sbc640964** [elementor/elementor#10749]
Peace

I did not find in the documentation,
Can exit animation control like popup exit be added?

**Comment by shilo-ey** [comment]
Hey @sbc640964 

The Exit animation control applies only to Popup.

Thanks.

**Comment by sbc640964** [comment]
Hey @shilo-ey 

I got along ...
\ Elementor \ Controls_Manager :: EXIT_ANIMATION,
I added the value to the design class + reverse
And I made sure to display: none after the animation ended.
