### ISSUE TITLE
Elementor Editing PANES

### ISSUE THREAD

**Issue by QuartermasterSARG** [elementor/elementor#10743]
_I think it's time for you all to expand the capabilities of the Elementor editor window to it's full potential._
Instead of having 'hide widget on tablet or mobile', how about a set of check-boxes that enable (what I call) Elementor Editing PANES for each viewport.

The editor would be capable of displaying three editing PANES, side by side, (best on a wide-screen browser). Each PANE displays the layout at the responsive width of either the desktop, the tablet, or the mobile breakpoint.

Designers would be able to work on their page layout with all three views simultaneously. (Like having multiple views in PhotoShop.)

Rows and modules can be enabled, disabled, and copied from one view to the other. 

This would make for a LOT faster route to final product. You could even work in some auto-sizing features for text and graphics, so all three PANES work together, yet the designer can still adjust them.

I hope this idea intrigues you. 
SCOT

**Comment by DorShahar** [comment]
Hi @QuartermasterSARG 
This is an interesting idea, which I shared with our designers.
I'm merging this issue with #2043 since it is related to the same project that is in the making. 

This could be a future phase, but I need to investigate more. 

Thanks for bringing this up.
