### ISSUE TITLE
"No Templates For Condition" after updating to WP 5.4

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#10745]
We are experiencing an issue where after updating the WP core to 5.4rc the templates of a page are no longer recognized, like so:

![DeepinScreenshot_select-area_20200304212548](https://user-images.githubusercontent.com/9055437/75915253-d3b4ce00-5e5e-11ea-8a1e-7a39819e2170.png)

Reverting WP core back to 5.3 seems to solve the problem and the template along with the "Edit with Elementor" button re-appear.
![DeepinScreenshot_select-area_20200304212616](https://user-images.githubusercontent.com/9055437/75915348-ffd04f00-5e5e-11ea-9eab-92b08f2d6ad5.png)

This test was run on a clean db with only Elementor & Elementor Pro (latest) plugins activated and Hello Elementor theme.

**Comment by shilo-ey** [comment]
Thanks, WordPress has changed the way it handles the admin-bar and that needs some modifications. we will release a compatible version soon.

Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.7
Feel free to update

Thanks!

**Comment by Pikamander2** [comment]
@shilo-ey @kobizz @KingYes @bainternet - This doesn't appear to be fully resolved.

When visiting a post, the first load will successfully show the Edit with Elementor button. If you refresh the page (or load it in another tab), the button stops appearing.

If you edit the post with Elementor and save, then it will appear one more time, but stops appearing after that.

So, in other words, here are the steps for reproduction:

1. Create a post with Elementor and publish it
2. View the page and note that the "Edit with Elementor" button appears at the top and is clickable.
3. Refresh the page and note that the button has disappeared (or at least isn't clickable).

For reference, we're using WordPress 5.4.1, Elementor 2.9.9, and Elementor Pro 2.9.5.

I tested the issue using our staging site with plugins/themes disabled and on a fresh installation as well. The issue occurred on both sites, even with Elementor Pro disabled.

I did some simple debugging and found that this line in frontend.php was failing:

`if ( is_singular() && isset($this->admin_bar_edit_documents[$queried_object_id]))`

The problem there seems to be that the

`1626 => Elementor\Core\DocumentTypes\Post::__set_state(array( 'main_id' => 1626, 'post' => WP_Post...`

value is missing from the `admin_bar_edit_documents` array after the first page load.

Any idea what's happening there? Our writers are getting annoyed.

![image](https://user-images.githubusercontent.com/5246872/83141491-c9048080-a0bd-11ea-844e-b718f65ce5f2.png)

**Comment by howdy0420** [comment]
I also had this issue, I am pretty sure i went directly to the pages list,
made duplicates of the affected pages, deleted them and republished.. or go
to the wordpress editor and you can choose to edit with elementor there...
Hope this helps somebody...

**Comment by shilo-ey** [comment]
[**@Pikamander2**](https://github.com/Pikamander2) commented on [May 28, 2020, 3:44 PM GMT+3](https://github.com/elementor/elementor/issues/10745#issuecomment-635327007 "2020-05-28T12:44:19Z - Replied by Github Reply Comments"):
> @shilo-ey @kobizz @KingYes @bainternet - This doesn't appear to be fully resolved.
> 
> When visiting a post, the first load will successfully show the Edit with Elementor button. If you refresh the page (or load it in another tab), the button stops appearing.
> 
> If you edit the post with Elementor and save, then it will appear one more time, but stops appearing after that.
> 
> So, in other words, here are the steps for reproduction:
> 
> 1. Create a post with Elementor and publish it
> 2. View the page and note that the "Edit with Elementor" button appears at the top and is clickable.
> 3. Refresh the page and note that the button has disappeared (or at least isn't clickable).
> 
> For reference, we're using WordPress 5.4.1, Elementor 2.9.9, and Elementor Pro 2.9.5.
> 
> I tested the issue using our staging site with plugins/themes disabled and on a fresh installation as well. The issue occurred on both sites, even with Elementor Pro disabled.
> 
> I did some simple debugging and found that this line in frontend.php was failing:
> 
> `if ( is_singular() && isset($this->admin_bar_edit_documents[$queried_object_id]))`
> 
> The problem there seems to be that the
> 
> `1626 => Elementor\Core\DocumentTypes\Post::__set_state(array( 'main_id' => 1626, 'post' => WP_Post...`
> 
> value is missing from the `admin_bar_edit_documents` array after the first page load.
> 
> Any idea what's happening there? Our writers are getting annoyed.
> 
> ![image](https://user-images.githubusercontent.com/5246872/83141491-c9048080-a0bd-11ea-844e-b718f65ce5f2.png)

Thanks, we will take a look and update.

**Comment by Pikamander2** [comment]
@shilo-ey - Can we reopen the issue since it's essentially the same bug?

**Comment by ido1990** [comment]
Same here with child theme of Hello and Elementor 2.9.13 and Elementor Pro 2.10.3
![תמונה](https://user-images.githubusercontent.com/16368652/87312575-69591c00-c529-11ea-96f9-137313caca18.png)

**Comment by wayheming** [comment]
Same error.

**Comment by Pikamander2** [comment]
@ido1990 @wayheming - For the sake of testing, does my proposed fix solve your issue?

https://github.com/elementor/elementor/pull/11729/commits/1ff0a3cc19ce808974266dc07efd9490c82fe874

**Comment by igorchernenko92** [comment]
elementor - 3.0.9, pro - 3.0.4 - same issue
Wordpress 5.5.1

**Comment by ravensorb** [comment]
Same issue here..

Elementor v3.0.15
Elementor Pro v3.0.8
Wordpress 5.6

**Comment by yasir-arzo** [comment]
same here

Template File: No Templates for condition > Blocksy - index.php

**Comment by yasir-arzo** [comment]
Template File: No Templates for condition > Astra - index.php

**Comment by mgcadag** [comment]
Hello, I'm having the same issue

Template File: No Templates for condition > /themes/astra/index.php

WordPress Version 5.7.2
Elementor Version 3.2.4
Elementor Pro Version 3.2.2
![elementor-issue-wp5 7 2-elempro3 2 2](https://user-images.githubusercontent.com/33459097/119888570-17b25800-bf68-11eb-9fd3-29ff018f50a2.jpg)

**Comment by promocot** [comment]
this problem appear again

**Comment by promocot** [comment]
i cannot edit all page on new website, elementor update with bags

**Comment by jschouwstra** [comment]
I have this same problem too (september 26 2021)
Latest Elementor release (3.4.4, Pro 3.4.1)

**Comment by churchthecat** [comment]
Having issue as well, Wordpress 5.8.1 , elementor Version 3.4.6 , elementor pro Version 3.4.2 
Issue started after big jumps in update (prior wp 5.4and update from old wp versions.

**Comment by IlPizza79** [comment]
Same issue with an Hello child theme:
"Template File: No Templates for condition > /themes/hello-elementor/index.php"

**Comment by Robinl2018** [comment]
Hi, same issue 

Template File: No Templates for condition > /themes/hello-elementor/index.php

Could anyone help me please?

**Comment by churchthecat** [comment]
@shilo-ey  
this issue needs reopening.

**Comment by Seb7100** [comment]
Have the same issue

**Comment by alishafkat** [comment]
I have been facing the same issue and particularly on my landing page is there a way to solve this issue although i tried disabling all plugins installed and deactivating Hello theme but no luck.

Please reopen this @shilo-ey  and help would be appreciated.

Thanks in adv

**Comment by et279** [comment]
I have the same problem, and I have already followed the steps I was told in support.

1.Backup your website
2. Go to your WordPress Dashboard > Elementor >Tools > General > Regenerate CSS > click on Regenerate Files.
3. Clear all cache: your browser's cache, other plugins' cache, server cache (if possible).
4. Deactivate all plugins apart from Elementor and Elementor pro, Then reactivate them one by one to find the culprit.
5. Switch your theme (temporarily) Better switch to Hello Theme, our default theme.
6.Go to Elementor > Settings on your WordPress dashboard, Click the Advanced tab and then switch the CSS print method to Internal embedding.
7.Switch the CSS print method back after following these steps, regardless of whether it helped or not.

But it has not been solved!

**Comment by YohanPateau** [comment]
I've got the same problem with Wordpress 5.9, Elementor 3.5.5, Elementor Pro 3.6.2, and OceanWP Theme.
Theme > Template files : No templates for condition > OceanWP - page.php

Please help !

**Comment by eghlimaghaderi** [comment]
ME TOO !!! I've got the same problem with Wordpress 5.9, Elementor 3.5.5, Elementor Pro 3.6.2, and OceanWP Theme.
Theme > Template files : No templates for condition > OceanWP - page.php

Please help !

**Comment by tradetheplandan** [comment]
I have the same issue. Does anyone know how to fix this?

**Comment by fracse** [comment]
same problem but the page does not stop to load!
<img width="326" alt="Schermata 2022-08-18 alle 12 27 36" src="https://user-images.githubusercontent.com/111502450/185373919-6917893c-f983-4f66-a82f-8b0610c4b71f.png">

**Comment by kundukundu** [comment]
Same issue here, with the ‘Preview Could Not Be Loaded’ Error. Any fix?

**Comment by TottoHolm** [comment]
I have the same problem. 
"Template File: No Templates for condition > /themes/hello-elementor/index.php"
Wordpress version: 6.1.1
Elementor version: 3.8.1

**Comment by Zakaria0531** [comment]
same error here, anyone found a solution?

**Comment by doxt3r** [comment]
the eeror eccurs when no models exist and assigned, sometime with condition in the page you need to edit.
debug and solution found here:
https://stoorm.org/article/template-file-no-templates-for-condition-themes-hello-elementor-index-php
