### ISSUE TITLE
[Tiny Bug] - Maintenance Mode "Edit Template"  Too Many Redirects

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#10758]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This is something minimal, but sometimes it bothers me. I can't remember from which version it started to happen, it's maybe from 2.6 forwards. But every time I'm on Maintenance Mode and I click on the link to "Edit Template" I selected in the drop-down, it redirects to a link at https://my.domain.com/?p=XXXXXX&elementor and it ends up timing out because of ERR_TOO_MANY_REDIRECTS. I've tried to Clear Cookies and in many different installations, and the error persists.

## Steps to reproduce

1. Go to Elementor > Tools > Maintenance Mode.
2. Choose a Mode (it doesn't matter which).
3. Choose Custom in "Who can access" and select the Roles you want (example: Admin).
4. Select a template and Save Changes.
5. After the page reloads click the Edit Template link that appears under the selected template.
6. Wait for the page to load and the error will appear.

Tested on Chrome, Firefox and Edge, all the latest versions.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Unix) OpenSSL/1.1.1
	MySQL version: mariadb.org binary distribution v5.7.28
	PHP Version: 7.3.15
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 2048M
	Permalink Structure: /blog/%category%/%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Floww
	Version: 1.0.1
	Author: Nicholas Zein
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
	
== Active Plugins ==

	Elementor
		Version: 2.9.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.4
		Author: Elementor.com

	Wordfence Security
		Version: 7.4.6
		Author: Wordfence

== WP_CONFIG Constants ==

	define('DISABLE_WP_CRON', true);
	define( 'WP_DEBUG', true );
	define( 'WP_DEBUG_DISPLAY', true );
	define( 'WP_DEBUG_LOG', true );
	define( 'SCRIPT_DEBUG', true );
	define('WP_MEMORY_LIMIT', '512M');

== Disabled WP Core Functions and Methods ==
	Disable RSS feeds
	Disable Emojis
	Remove RSD Link
	Remove wlwmanifest Link
	Remove Shortlink
	Remove .recentcomments styles
	Disable Dashicons

```
</details>

**Comment by arielk** [comment]
I can't reproduce this issue, everything works fine for me. If you are still having trouble please contact support@elementor.com with full login information for accessing your site and our support team will try to help.

**Comment by zeinnicholas** [comment]
@arielk Thanks for the reply.

I think the issue with this is that you're using the shortlink to edit the product instead of calling the full path. This forces WordPress to redirect to the page, and depending on server security or some other permalink configurations it won't go to the link. 

A safer and error-free way would be to use the full link, as in: 
https://domain.com/wp-admin/post.php?post=XXXX&action=elementor

Right now the link goes to:
 https://domain.com/?p=XXXX&elementor

which is the shortlink version of the full path URL, which causes the error because it's redirected too many times.

This would prevent any permalink or redirection issues, as also would always preserve the capability check before opening the page, which is also the reason for too many redirects. You are asking WordPress to figure out everything and in some cases, it will time out.

**Comment by arielk** [comment]
Thanks, we will look into this soon!

**Comment by myBCN** [comment]
I also get this error 100% of the time when trying to Edit an Inserted Template with the Template Widget. Elementor & Pro.
