### ISSUE TITLE
Fusion mode on iOS 13

### ISSUE THREAD

**Issue by angel2433** [elementor/elementor#10770]
Can someone try to make a background black and white and then put some text and configure it in fusion mode like “difference”? I tried it with and iPad on iOS 8 or emulating an iphone in Firefox with iOS 12 and it works, but with several iPhone and iPad in iOS 13 doesn’t. (Here's the example: https://imgur.com/a/X6zfOp7)

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
