### ISSUE TITLE
How to use optgroup in select input?

### ISSUE THREAD

**Issue by pocketsocialau** [elementor/elementor#10773]
Is it possible to use optgroup 'headings' within a select input in the Form (Pro) widget?

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
