### ISSUE TITLE
Images are not being applied to image/background image

### ISSUE THREAD

**Issue by johnnymcclorey** [elementor/elementor#10778]
A few weeks ago I added a background image to my site, this was all fine, however yesterday I noticed no images are showing on my live site (either standard images, image galleries or background images) or in the Elementor editor. I have tried switching off SSL from my hosting, deleted and remade every section with an image, regenerated css/files in Elementor, cleared cache on website and my browser. I have tried virtually everything and nothing will fix my issue. The images are appearing in my media library, just not on the front end. I'm not sure if anyone else is having this issue lately, but it's extremely frustrating as my website looks awkward with no images!!

**Comment by johnnymcclorey** [comment]
Also if it helps, my image is showing up on inspect element, as if nothing was wrong! 
![Screenshot 2020-03-08 at 11 40 52](https://user-images.githubusercontent.com/48419791/76162085-d4d14e00-6131-11ea-8278-5c31137e29b9.png)

**Comment by GitteOlsen** [comment]
Does your site use ssl? I had the same issue twice this year, the path to the background images suddenly changes from https to http, and the browser hides the "unsafe elements" in this case the background image. I solved it by adding the images again and saving, but it is certainly a bug.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
