### ISSUE TITLE
Box shadow missing on image gallery

### ISSUE THREAD

**Issue by Zazamax** [elementor/elementor#10775]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zazamax** [comment]
Love a shadow around my images but no box shadow available on your image gallery. Please can you add it soon? It is available for about everything else BUT for your image gallery. Thank you :-)

**Comment by pocketsocialau** [comment]
If you put the following in the Custom CSS for the gallery widget, it will put a  box shadow on each gallery photo. 

`<hr>`

**selector** **.elementor-gallery-item** {-webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);
box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);}

`<hr>`

You can change the color, distance and blur of the box shadow. 

Or you can easily generate CSS for the box shadow here: https://www.cssmatic.com/box-shadow

**Comment by DorShahar** [comment]
Hi
We have this now.
Closing the issue.

**Comment by productofberlin** [comment]
I am afraid you don't. The drop shadow Elementor offers for the image gallery applies to the container, the images are in. Not the images themselves.

**Comment by jflipsantos** [comment]
I can confirm that this is still not possible to achieve in elementor.

**Comment by Mrsnibs** [comment]
Still not possible in 2022.

**Comment by nalpure** [comment]
Still not possible in 2023.

**Comment by tekonemedia** [comment]
Seriously need box shadow/drop shadow options on image gallery!!

**Comment by btcdoublerz** [comment]
The image shadow feature is not available May 2024.
