### ISSUE TITLE
layout structure not working properly when it's in 3 column mode

### ISSUE THREAD

**Issue by mehedidb** [elementor/elementor#10776]
Hi,

When click in layout mode it's make unwanted different layout. 
**Example:** my purpose need **width: 25%/25%/50%**
Then when click the layout its make **width: 25%/50%/25%**
Please have a looks all screenshot examples:

![Screenshot_1](https://user-images.githubusercontent.com/12911054/76160414-6487f400-6154-11ea-9236-d8ee7684e671.png)
![Screenshot_2](https://user-images.githubusercontent.com/12911054/76160419-694ca800-6154-11ea-859d-c0f91206d89b.png)
![Screenshot_3](https://user-images.githubusercontent.com/12911054/76160420-6ce02f00-6154-11ea-9bf2-3015075e1519.png)

Problem basically happed in width
25, 25, 50
25, 50, 25
16, 66, 16
Please have a look and fixed them, and make it more pretty.

Thanks

**Comment by lior-sh** [comment]
Hi @mehedidb,

Thanks for reporting, we couldn't reproduce the bug.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
