### ISSUE TITLE
Post Expert Widget not work

### ISSUE THREAD

**Issue by codeorlov** [elementor/elementor#10795]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello, the post expert widget is not working (does not display any information). Tested on various topics and on a clean wordpress installation.

## Steps to reproduce

Try to create a template for a single post and add post experrt to it, you will not see anything in the frontend.
![image](https://user-images.githubusercontent.com/46539627/76219821-1ab81000-621f-11ea-8818-c0e86ec8b401.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
``
</details>

**Comment by codeorlov** [comment]
please pay special attention to this, as it is very important for creating dynamic sites

**Comment by shilo-ey** [comment]
Have you set the excerpt in your post?

**Comment by shilo-ey** [comment]
[**@shilo-ey**](https://github.com/shilo-ey) commented on [Mar 30, 2020, 1:23 PM GMT+3](https://github.com/elementor/elementor/issues/10795#issuecomment-605916079 "2020-03-30T10:23:42Z - Replied by Github Reply Comments"):
> Have you set the excerpt in your post?

@codeorlov ?

**Comment by nullmem** [comment]
It seems logical (at least to me) that the Post Excerpt widget should duplicate the automatically generated post excerpt on archive pages by themes. But this widget seems only to work if you manually set a excerpt for the page or post, which is counter intuitive and not really helpful.
