### ISSUE TITLE
Ability to export code generated for single page/post or element 

### ISSUE THREAD

**Issue by t3m1sHack** [elementor/elementor#10794]
Please, when will you able this feature? To download the page's HTML (with embedded CSS, JS) to use the layout on a website outside of Wordpress.

It's a must have since I'm doing webapp outside of wordpress and would love to keep working with Elementor!

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4417, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
