### ISSUE TITLE
Form upload file deletion 

### ISSUE THREAD

**Issue by mstudioIL** [elementor/elementor#10808]
When I use the form the upload file they are store on the server and the form contain link to download them, can the files be automatically deleted after the download? I can't tell the user to user FTP or file manager to delete them.

**Comment by lior-sh** [comment]
Hi @mstudioIL,

Thanks,
Please create GitHub issues only for bugs reports and feature requests.
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by mstudioIL** [comment]
It is for feature requests not support.
