### ISSUE TITLE
Version 2.9.2 (and higher) changes/breaks how Elementor detects the_content

### ISSUE THREAD

**Issue by PiotrKrzyzek** [elementor/elementor#10807]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

It seems that Elementor (free) at version 2.9.2 or higher has changed how it detects the the_content filter and thus will show the "no the_content" pop-up error message when trying to edit certain things. Specifically, this breaks editing pop-ups.

On version 2.9.1, this works wonderfully and without issue. As soon as you update the base version of Elementor to 2.9.2 or higher I am unable to edit pop-ups.

So far, this happens on non-made-for-Elementor themes. Seems to not happen on Elementor friendly / made-for-Elementor themes.

The version of Elementor Pro doesn't seem to matter.

Regular pages are not effected.

## Steps to reproduce

Pick a custom theme or non-elementor-friendly-theme. Use Elementor (base) version 2.9.2 or higher. Try to create or edit an Elementor Pop-up (with Elementor).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Running on a PHP 7.3 instance on WPEngine. Same issue on PHP 7.2

**Comment by jazir5** [comment]
I am running PHP 7.3 on siteground and i have been running into "the_content" popups frequently as well. I am using Hello Theme, so there shouldn't be any theme related compatibility issues. This seems to be an issue with Elementor/Elementor Pro itself

**Comment by jazir5** [comment]
Any update @shilo-ey, @bainternet? I have pages randomly breaking after i've designed them, making the design time spent a complete waste of time.

**Comment by webdevid** [comment]
hai all any update for this??

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
