### ISSUE TITLE
Add widgets in tabs and accordions

### ISSUE THREAD

**Issue by jorgept** [elementor/elementor#10801]
Possibility to add widgets/sections inside tabs, accordions, etc...

**Comment by rodolphebertozzo** [comment]
Pour cela, dans la version pro, il existe des shortcodes dans la version Pro, il suffit de créer un modèle de section et de désigner ce que vous souhaitez mettre dans votre onglet/accordéon puis je fois le modèle conçu, copiez le shortcodes et collez le au bon endroit dans votre onglet/accordéon

**Comment by jorgept** [comment]
I know, but
If i have 20 our more tabs/accordions/toggles, i need make 20 our more templates?
Rather than one single page/post with one tab/accordion/toggle.
Is not suitable for large number of information...

Thank you

**Comment by black-eye** [comment]
@jorgept Long time issue, please visit the thread here https://github.com/elementor/elementor/issues/2587 and add your vote there.

**Comment by jorgept** [comment]
Done!
+1 for it black-eye!
Thanks

**Comment by shilo-ey** [comment]
I merged this issue with #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by codeorlov** [comment]
this is a very necessary function, which is simply a must. +1 for dragging widgets directly to tabs!

**Comment by TomRaraAvis** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was partially introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Nested Tabs** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Feel free to check it out and update your plugin to the new version!

Stay tuned for the next versions that will introduce Nested Accordions as well. 

🗨️ Please continue the conversation in issue #2587.

Cheers 🥂
