### ISSUE TITLE
Elementor Entrance Animations Causing Webpage To Crash

### ISSUE THREAD

**Issue by Salvatore1234** [elementor/elementor#10804]
I've used Elementor for a while now for a few different projects and I have never experienced webpage crashes on phones and tablets until now. I've noticed on my recent project naturesdependable.com, that the Supplement page will crash repeatedly on phones and tablets without any server errors. On this page I utilize many entrance animations. On the same website, on the other pages there are no crashes. The other pages only have a few or no entrance animations. The crashes occur using safari or chome on my iPhone and iPad. It seems as though the browsers are overloaded and can't handle the many entrance animations.

**Comment by lior-sh** [comment]
Hi @Salvatore1234,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
