### ISSUE TITLE
Share Buttons mailto: Link Template Ignores \n

### ISSUE THREAD

**Issue by ianlee** [elementor/elementor#10803]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

On Share Buttons Widget, clicking on the share by email button opens a mailto without a space or new line between the text and the shared link. This makes it so the link is unclickable by default by recipients of the email.

example body text of the email:

`This is the description.https://example.com`

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

For whatever reason, the \n in the `ShareLink.networkTemplates` gets ignored by my chrome/mac mail client.  So, by replacing the \n with a space, it at least fixes the above issue.

Suggested change: 

social-share.js 
`email: 'mailto:?subject={title}&body={text}\n{url}',`

change to

` email: 'mailto:?subject={title}&body={text}%20{url}',`

## Environment

<details>
<summary>System Info</summary>

```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by MicroRainbow** [comment]
The same thing happens to my Share Buttons for all networks. There is no space between the excerpt text and the post url

**Comment by arielk** [comment]
Fix: https://github.com/elementor/elementor/commit/2795e7ffc37b5c4797823f19d5351f153d8e00a1
