### ISSUE TITLE
Image Box Widget - Typography enhancement

### ISSUE THREAD

**Issue by kaelhoel** [elementor/elementor#10814]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add mouseover state to the typigraphy title and description in the image box widget. Currently only the image has mouseover state settings.

**Describe the solution you'd like**
I would like to be able to change the color and typography settings for text in the image box widget.

**Describe alternatives you've considered**
I have added custom CSS to the elements, but it would be better if the controls were added to the widget.

**Additional context**
Just normal implementation of color and typography settings for mouseover state.

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
