### ISSUE TITLE
Issue with icons in Nav Menu widget

### ISSUE THREAD

**Issue by JuliaArr** [elementor/elementor#10812]
Hi,

There is an issue with icons in the Nav Menu widget - when enabling the Submenu Indicator it isn't displayed correcrly on the front-end: 
 https://www.screencast.com/t/7M9Mi87uJKts but on the back-end it's okay: https://www.screencast.com/t/TQAPQkkEo

But after adding the Icon widget to the page the arrows are shown correctly. Can this issue be solved on the pages without icons?

Thank you!

**Comment by shilo-ey** [comment]
Hi @JuliaArr 

Thanks for your input,

This issue has already been reported and is being taken care of by our developers.

In the meanwhile, you can go to your WP dashboard and under Elementor -> Settings -> Advanced, switch "Load Font Awesome 4 Support" to "Yes"

Thanks!

ref: #9907

**Comment by jdub850000** [comment]
Hi. I'm still having issues with this aspect and have tried the fix suggested. Are there anymore ideas on this?
