### ISSUE TITLE
Need some Idea About Elementor Pro

### ISSUE THREAD

**Issue by tulu2020** [elementor/elementor#10815]
Hi,

I am using elementor Pro and trying to customize my website like https://www.carbibles.com/ but I am facing some problem. I don't understand which add ones need to use to use. here is the screenshot...

https://prnt.sc/reidqe
https://prnt.sc/reidvd

How can I make same type of effects if anyone know plz help me.

Thanks
Hafizur Rahman

**Comment by codeorlov** [comment]
very good work!  Could you tell me which plug-ins you use to filter posts and display the view counter in posts?  or is it a theme?

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues are not for support.

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
