### ISSUE TITLE
create a widget with no wrapper divs

### ISSUE THREAD

**Issue by DirkCarstens** [elementor/elementor#10823]
Hello!
We want to create a widget, that generates the following html:
+form method="GET" action="https://........." class="mphb-booking-form" id="booking-form-74014">
and another widget generates the following html:
+/form>
BUT!
We allways get two wrapper divs
Is there a way to convince \Elementor\Widget_Base not to generate the wrapper-divs?
-----------------------------------------
+div class="elementor-element elementor-element-1ae0910 elementor-widget elementor-widget-price-form-elementshf" data-id="1ae0910" data-element_type="widget" data-widget_type="price-form-elementshf.default">
+div class="elementor-widget-container">
+form method="GET" action="https://........." class="mphb-booking-form" id="booking-form-74014">
+/div>
+/div>

+div class="elementor-element elementor-element-241c7483 elementor-widget elementor-widget-price-form-elementshf" data-id="241c7483" data-element_type="widget" data-widget_type="price-form-elementshf.default">
+div class="elementor-widget-container">
+/form>
+/div>
+/div>"
-------------------------------------------
Thank you!
Best Regards
Dirk

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
