### ISSUE TITLE
Header not working in page, footer does

### ISSUE THREAD

**Issue by RemPro** [elementor/elementor#10829]
Hi, the footer is editable in a page but the header is not !

Maybe usefull to also put them in the inspector !!

**Comment by lior-sh** [comment]
Hi @RemPro,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
