### ISSUE TITLE
Appending ?name=test& after url crashes the site

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#10844]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

Create a test url such as mydomain.com?name=testName

## The problem

The site no longer loads, instead, it contains a notice:

```
Notice: Trying to get property 'ID' of non-object in /data/web/virtuals/201500/virtual/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php on line 204

Notice: Trying to get property 'ID' of non-object in /data/web/virtuals/201500/virtual/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php on line 210

Notice: Trying to get property 'ID' of non-object in /data/web/virtuals/201500/virtual/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php on line 214

Notice: Trying to get property 'ID' of non-object in /data/web/virtuals/201500/virtual/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php on line 217

Notice: Trying to get property 'ID' of non-object in /data/web/virtuals/201500/virtual/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php on line 223

Notice: Trying to get property 'ID' of non-object in /data/web/virtuals/201500/virtual/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php on line 245
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

![a](https://i.imgur.com/RluZ896.png)

**Comment by lior-sh** [comment]
Hi @kangarko,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
*** Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by kangarko** [comment]
Yeah I thought I did?

**Comment by kangarko** [comment]
@shilo-ey consider giving your staff better instructions on replying to tickets

**Comment by lior-sh** [comment]
Hi @kangarko,

Thanks for reporting.
The issue was closed because we couldn't reproduce the bug. Can you provide more info? like system info and on which page you tried to do that.
Thanks.

**Comment by kangarko** [comment]
Got it fixed, I believe it was due to the fact I choose "Elementor Canvas" template
