### ISSUE TITLE
Elementor 2.8.5 => 2.9.6 speed and migration problems

### ISSUE THREAD

**Issue by motiejus1** [elementor/elementor#10863]
Hello, I have a problem.
I'm creating custom page layout with Elementor. 
I used 2.8.5 version and everything worked fine.
Updated Elementor to 2.9.6 and these problems started:
1. Elementor sometimes loads sometimes not. Image link below:
[https://ibb.co/PrtVYLh](https://ibb.co/PrtVYLh)
2. Huge impact on speed and performance. Elementor 2.9.6 in editor mod works much slower than in 2.8.5 version. My system status in the link below:
[https://ibb.co/pj4v0Sn](https://ibb.co/pj4v0Sn)

!!! post_max_size 0 means that this parameter is unlimited

I'm using my own widgets. They are integrated in the theme. They are optimized and works fine until 2.9.6

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
