### ISSUE TITLE
⛔ 🚀 Feature Request: add shortcode dynamic to color control

### ISSUE THREAD

**Issue by sbc640964** [elementor/elementor#10869]
Add the option to use dynamic color short code

**Comment by udidol** [comment]
Hi @sbc640964,
Elementor Pro supports the ACF Color Picker field in the Color control. So you can get dynamic color capabilities by using ACF with Elementor.
Does that answer your requirement?

**Comment by sbc640964** [comment]
No
I want to use a short code for the color and not the ACF

**Comment by nicholaszein** [comment]
Hello @sbc640964,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

Try using custom fields, as they have greater support and can only output sanitized values. If we allow shortcodes to be added as dynamic colors, all sorts of issues could arise that we cannot safely prevent. 

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
