### ISSUE TITLE
Dynamic Contact URL with ACF

### ISSUE THREAD

**Issue by codeagencybe** [elementor/elementor#10878]
Hello fellow elementorists

I think I just ran into some limitation or a bug on the "dynamic contact url" feature from Elementor Pro but I'm not sure, I might just as overlooked something but I can't find the field/option to enable it. 

I'm working on a listing model/template to output contractors and if there is a phone number, it shows a button with a phone URL behind it so visitors can 1-click the button and it will call the contractor. 
This is done with "tel:" instead of "a href" just like email is with "mailto:" in case someone wonders how this is done. 

But now comes the part I'm stuck with. 
I'm using ACF pro and created a custom post type to handle all the contractors details. 
In all the fields I have thy dynamic cog feature so I can select my ACF field. 
But when I pick the button and change the link type to "contact url" > type = TEL 
I can only "hard code" the phone number. This should be automatically my ACF phone field. 
But I don't see any cog or other field for this. 

Anybody who has an idea about this? I've spent already a few hours reading the docs (links below) but they are not clear how this is handled with ACF. 

Enclosed also a screenshot from the settings. 

https://docs.elementor.com/article/448-dynamic-contact-url
https://docs.elementor.com/article/448-dynamic-contact-url

![image](https://user-images.githubusercontent.com/7568546/76946223-00a7bd00-6904-11ea-843d-9a3c8abc4e4b.png)

**Comment by udidol** [comment]
Hi @codeagencybe,
The Contact URL dynamic type does not fetch its value from ACF. 
To use it, for each contractor, you enter their phone number in the `Number` field.

If you want to fetch the contractors numbers from ACF, you would have to create an ACF custom field and choose this field (instead of Contact URL) in the dynamic menu. If you want that value to be a `tel:` link, you should prefix all your entries (in each contractor's CPT page) with `tel:`.

**Comment by IlPizza79** [comment]
I can see that this issue is closed, but it's still an issue in 2021.
Elementor already is great in working togheter with ACF, but it still miss something :-(
Is there any hope to fix this issue?

**Comment by hiviz** [comment]
+1

**Comment by udidol** [comment]
@codeagencybe I told you what you need to do.
Did adding `tel:` before every phone number in each contactor's post not solve your problem?

**Comment by codeagencybe** [comment]
@udidol that solution is not a solution. Because it doesn't output as required. If you prefix with tel: it will also show like that in the frontend which we don't want. We want just to show the phone number "as is" and make it clickable with the proper HTML anchor type just like it also works with mailto: and there are many others like whatsapp:// etc... 

Also, the data is coming from a remote source and we can't manipulate that prefix. So your suggestion is just impossible. 
Besides, that doesn't mean this problem magically disappears. After 2 years, nobody cared to fix it either, no matter if one did use your workaround. 

I don't understand why legit complaints for broken stuff are just ignored for years. This is just one of the many examples that drive people away from Elementor. The focus from many years ago is just long gone. It's all about marketing gimmicks now instead of fixing real problems. [rant over]

**Comment by udidol** [comment]
@codeagencybe 
This is not a bug, it is a feature request.
The ACF URL field doesn't have a built-in option to support `mailto:` or `tel:` prefixes.
What you are asking is for us to expand ACF's capabilities to be able to support such prefixes.
Your example of `whatsapp://` is difference since that's a valid URL and not a prefix.

**Comment by udidol** [comment]
What do you mean by `Elementor "BEFORE" part`?

**Comment by Robert080** [comment]
Maybe I have the same problem. I have a listing with dynamic generated telephone numbers and email addresses.
If in the acf fiel of every "news" I use a **text field** with "mailto:abc@efg.com" or "telto:12345678" the 1-click (clickable) function will be OK. The main problem it's that on the screen (front end) the user will non only see listed the "simple telephone number" but will see on the screen the telephone numer prefixed by tel:  mailto: How can be possible to have a listing with a clickable mail and phone link but without visible in the frontend tel: and mailto: ?

**Comment by codeagencybe** [comment]
@Robert080 this is exactly the problem I'm pointing out. 
The method that elementor proposes which isn't a workable solution, requires you to manually change all those values in the backend first. 
If it is just a few records, no big deal. But if your listing is coming from a remote source, updating realtime, then it's not. 

Simply, the elementor widget needs a fix for href link fields like email and phone numbers so they can behave like normal URL type fields. 
Simple as that.

**Comment by Robert080** [comment]
I may have found a solution. I hope it can be replicated by everyone.
A) in ACF create two different fields. The first is what users will see; the second is a 'text field' in which you enter the 'command', e.g. 'mailto:abc@abc.com' or 'tel:3401234567'.
B) In the Elementor widget, in the first text field leave everything as it was already, so that the user reads the phone number or emai address. In the "link" field select "post custom field", then select the "key" on the left and manually enter in "Custom Key" the _tag_   (filed name in acf, the third field from the top) you entered in ACF associated with the "command" you need, e.g. "phone_number_user". DO NOT USE the "Select command" right above.
It seems to work in my case.

**Comment by codeagencybe** [comment]
duplicate entry is not a "solution" on my watch. If this works for you, all good by all means, but this should not be the final answer for this problem. 
It's wasting resources, it's not efficient, it can cause problems. 
What if somebody changes/updates only 1 field in the backend, then you see number X but the tel: link returns number Z

Also, in most cases listings are generated  programmatically, by fetching 3rd party sources, API, etc... So you don't always have the option to append the data. However it comes in, that's how it's stored. 
As I said before, for low number records not much of a problem but if you build listing sites with thousands of records, I don't want to be the person to keep on fixing the prefixes because of a half baken feature in Elementor. 
It's easy for them to fix this problem by just putting the correct official hyperlinks in place. 
Every developer knows there is also mailto: , tel: , whatsapp: etc... and not only http(s)://

**Comment by Luismw** [comment]
2022 and still this is still not fixed, what a shitty thing to do with Elementor people, that's why I moved to Bricks.

**Comment by iamakram22** [comment]
I have worked around a simple solution for this is to create shortcode and use that shortcode in Elementor to output the Phone number with link. See the example below

`function ak_elementor_shortcode( $atts ) {
	$staff_phone = get_field('phone_number');?>
	<a href="tel:<?php echo $staff_phone; ?>"><?php echo $staff_phone; ?></a><?php
}
add_shortcode( 'staff_phone_acf', 'ak_elementor_shortcode');`

use `[staff_phone_acf]` to out put the [hone number with link.

Make sure to change the field id from "phone_number" to the field id you are using.

add the above code in your child theme function or use code snippets plugin.

**Comment by dulakshirb** [comment]
Create an email field in ACF, then, for the link field in Elementor, simply select the email from your list (do not choose the contact URL).
![image](https://github.com/elementor/elementor/assets/37257711/0f16d223-dff9-4249-8fbd-2cd07e33b5a1)

**Comment by JennyPower** [comment]
It works for the email field but not for telephone. I understand the complexities are probably that you have no idea what format the telephone number will take, therefore converting it to a clickable link is tricky.

I'm using a shortcode that strips out brackets and spaces to form the link, but it's reliant on the ACF field being formatted a certain way.

`// ACF telephone field to link
add_shortcode('phone_link', 'wt_phone_number_to_link');
function wt_phone_number_to_link() {

    // Get the field value
    $phone_number = get_field('phone_number');
    if (!$phone_number) {
        return ''; // Return empty if no phone number is found
    }

    // Strip non-numeric characters
    $clean_number = preg_replace('/[^0-9]/', '', $phone_number);

    // Return the formatted phone link
    return '<a href="tel:' . $clean_number . '">' . $phone_number . '</a>';
}`

**Comment by ayoubkhan558** [comment]
+1

**Comment by corey-codes** [comment]
It's pretty ridiculous that 4 years on Elementor still hasn't provided a solution for this.

**Comment by manuel-will** [comment]
Another year has gone, another year no proper solution. Guys, just look at bricks how it's done correctly!

**Comment by codeagencybe** [comment]
I already gave up on Elementor long time ago. They have no clue or even want to understand the problem here. 5 years later after reporting the bug, there is zero understanding from their end. 

Just like there is http:// and https://, there is also mailto:, tel:, whatsapp://, wa://, etc... 
tel: is an official one that the industry agreed on decades ago to automatically make phonenumbers clickable in a browser.

This should be as simple as just pulling the value from an ACF field that is already formatted as an international (phone)number and does not contain anything else except for integer numbers. 

It goes beyond my mind that Elementor does not understand this while all other page builders like Bricks are perfectly capable of doing this.
