### ISSUE TITLE
The image size appears on the front

### ISSUE THREAD

**Issue by sbc640964** [elementor/elementor#10877]
wighet arcive posts in arcive template,
the image size show on after the grid
![image](https://user-images.githubusercontent.com/46646044/76942296-2cc43d80-6906-11ea-9ca0-dcb3b644867a.png)

**Comment by sbc640964** [comment]
> wighet arcive posts in arcive template
> the size image is show on after the grid
> ![image](https://user-images.githubusercontent.com/46646044/76942296-2cc43d80-6906-11ea-9ca0-dcb3b644867a.png)

**Comment by sbc640964** [comment]
The problem still exists, accidentally closed.

**Comment by pless84** [comment]
I have the same error on several sites

**Comment by shilo-ey** [comment]
Duplicate of #10874 

Thanks
