### ISSUE TITLE
Adding Features

### ISSUE THREAD

**Issue by MrAjnabi** [elementor/elementor#10879]
Please must add vertical thumbnail function in product image widget...also add shadow and size function...Also, You must add hover in heading also add social icons in the flip box in next update....must also add gradian in button or heading....please

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
