### ISSUE TITLE
Menu cart widget "removed" action

### ISSUE THREAD

**Issue by TheVoidCodes** [elementor/elementor#10875]
Hi!

It would be great that the Menu Cart widget would allow you to set the Removed Message whether in the AJAX cart or in a pop-up or outside the AJAX cart and if the web designer selects outside, it should find a good place like for example above a whole section instead of a column.

For example, on this page, it has [two columns](https://bspaequipment.com.mx/wp-content/uploads/2020/03/image1.png) but when a product is removed, the message [pushes down](https://bspaequipment.com.mx/wp-content/uploads/2020/03/image2.png) only one column.

Doesn't look well. I think that is a Woocommerce action, but if with the Elementor's Menu Cart widget we could get access to that message and selecting where to appear it would be great!

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!
