### ISSUE TITLE
How to integrate back-end code in wordpress elementor

### ISSUE THREAD

**Issue by NhuTruong13** [elementor/elementor#10888]
Hey, I am a beginner in wordpress and elementor and I would like to ask you this following question:
I need to build a catalog website with specific filters on the product catalog page, knowing that the products will be fed from the client ERP system.
I wanted to work with another dev, me being in front-end (with elementor for the design of the pages) and the other developer, more in the back-end (with the custom code for catalog page).
The other developer codes in PHP but doesn't use wordpress and elementor. 
How can I advice him to work with me ? Is it better for me to go to the code editor and inject his code ? or to use a plug-in for that ?
What would be your best advice ?
Thanks for your help !

**Comment by shilo-ey** [comment]
Hi @NhuTruong13 

You can use our Developers API, and let him know how to create custom widgets, Form integrations, new controls and much more.

Read here: https://developers.elementor.com/
And in our developers' blog: https://developers.elementor.com/blog/

Other than that, if you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)

Thanks and good luck
