### ISSUE TITLE
Custom attributes to Elementor widgets missing in latest update

### ISSUE THREAD

**Issue by albe89albe** [elementor/elementor#10881]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When editing, the capability to provide custom attributes to Elementor widgets is missing after the update 2.9.1 of Elementor Pro. I was using it with columns to handle them with a custom JS on the page, and now its gone. 

This is URGENT for me.

## Steps to reproduce

There is nothing special to do, it is just this "Custom attributes" feature under the "Advanced" tab in the Elementor editor.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.28
	PHP Version: 7.3.15
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://aleasoft.com
	Home URL: https://aleasoft.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: -1
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

== Active Plugins ==
	Alea Plugin
		Version: 1.1.0
		Author: Alberto

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.9.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.1
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 7.10.4
		Author: MonsterInsights

	Really Simple SSL
		Version: 3.2.9
		Author: Rogier Lankhorst, Mark Wolters

	Visualizer: Tables and Charts for WordPress
		Version: 3.4.2
		Author: Themeisle

	Wordfence Security
		Version: 7.4.6
		Author: Wordfence

	WPML Multilingual CMS
		Version: 4.3.10
		Author: OnTheGoSystems

	Yoast SEO Premium
		Version: 13.3
		Author: Team Yoast

== Elements Usage ==
	
	archive : 5
		archive-posts : 1
		spacer : 2
		theme-archive-title : 1
	footer : 5
		form : 1
		google_maps : 2
		heading : 2
		icon-list : 2
		nav-menu : 1
		social-icons : 1
	header : 5
		icon-list : 1
		image : 1
		nav-menu : 1
		search-form : 1
		shortcode : 2
		social-icons : 1
	page : 1
		button : 3
		divider : 1
		form : 1
		heading : 2
		icon-box : 4
		icon-list : 3
		image : 2
		menu-anchor : 1
		spacer : 6
		text-editor : 8
		theme-site-logo : 1
	single : 11
		post-navigation : 1
		shortcode : 2
		spacer : 2
		theme-post-content : 2
		theme-post-title : 2
	widget : 0
		media-carousel : 1
		nav-menu : 4
	wp-page : 228
		button : 110
		countdown : 7
		counter : 8
		divider : 34
		flip-box : 11
		form : 28
		global : 19
		google_maps : 6
		heading : 397
		html : 4
		icon : 34
		icon-box : 84
		icon-list : 28
		image : 218
		image-box : 59
		image-carousel : 8
		media-carousel : 6
		menu-anchor : 14
		nav-menu : 1
		posts : 5
		price-list : 4
		price-table : 14
		reviews : 1
		shortcode : 6
		social-icons : 5
		spacer : 119
		star-rating : 3
		tabs : 15
		testimonial : 35
		text-editor : 189
		theme-post-title : 1
		video : 8

== Log ==
	
JS: showing 20 of 35JS: 2020-03-09 12:25:21 [error X 1][https://aleasoft.com/wp-admin/post.php?post=42846&action=elementor#:2:1] docume is not defined 
JS: 2020-03-09 12:25:23 [error X 7][https://aleasoft.com/wp-admin/post.php?post=42846&action=elementor#:3:1] Unexpected end of input 
JS: 2020-03-09 12:25:51 [error X 1][https://aleasoft.com/wp-admin/post.php?post=42846&action=elementor#:2:46] Cannot read property \'o\' of null 
JS: 2020-03-09 12:25:51 [error X 1][https://aleasoft.com/wp-admin/post.php?post=42846&action=elementor#:2:46] Cannot read property \'on\' of null 
JS: 2020-03-09 12:25:51 [error X 1][https://aleasoft.com/wp-admin/post.php?post=42846&action=elementor#:2:46] Cannot read property \'onc\' of null 
JS: 2020-03-09 12:25:51 [error X 1][https://aleasoft.com/wp-admin/post.php?post=42846&action=elementor#:2:46] Cannot read property \'onclc\' of null 
JS: 2020-03-12 11:58:08 [error X 2][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:31:196343] Elementor panel doesn\'t have page named \'editorPreferences_settings\' 
JS: 2020-03-12 11:59:37 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:7:72792] Cannot read property \'cid\' of undefined 
JS: 2020-03-12 12:03:27 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:31:196343] Elementor panel doesn\'t have page named \'general_settings\' 
JS: 2020-03-13 13:18:46 [error X 1][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:2:5] f is not defined 
JS: 2020-03-13 13:18:47 [error X 2][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:2:5] func is not defined 
JS: 2020-03-13 13:18:47 [error X 1][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:2:5] funcrio is not defined 
JS: 2020-03-13 13:18:47 [error X 1][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:2:5] funcrion is not defined 
JS: 2020-03-13 13:18:47 [error X 1][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:2:5] funcri is not defined 
JS: 2020-03-13 13:20:30 [error X 2][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:3:20] Unexpected token \';\' 
JS: 2020-03-13 13:51:28 [error X 4][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor#:2:17] Unexpected token \'{\' 
JS: 2020-03-13 13:51:28 [error X 2][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor#:2:17] Unexpected token \'(\' 
JS: 2020-03-13 13:51:35 [error X 2][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor#:2:20] Unexpected token \')\' 
JS: 2020-03-13 13:52:51 [error X 1][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor#:9:43] Unexpected token \',\' 
JS: 2020-03-18 10:44:02 [error X 5][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:7:31384] Cannot read property \'data\' of undefined 

Log: showing 7 of 72020-02-27 09:05:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-05 08:51:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-10 11:50:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-10 11:50:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-10 12:50:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-03-12 10:33:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-18 12:15:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '2.9.1',
)]

PHP: showing 1 of 1PHP: 2020-03-12 15:53:24 [notice X 1][/homepages/1/d810730684/htdocs/web_aleasoft/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::245] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by QTRichieRich** [comment]
I have the same problem... Custom attributes are being output when rendering, but the ability to add new or edit existing is impossible as the box is missing...

**Comment by webdevs-pro** [comment]
Same thing!

**Comment by rodolphebertozzo** [comment]
Resolve in Elementor v2.9.7

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.7
Feel free to update

Thanks!
