### ISSUE TITLE
Dynamic (ACF) colors missing from Theme Style

### ISSUE THREAD

**Issue by nullmem** [elementor/elementor#10883]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The entire point of using ACF fields for color is to setup a ACF Options page for things like color. So why in the world is dynamic colors not available in ﻿Theme Styles! this makes absolutely no sense and makes this feature completely useless to anyone wanting to use Elementor Pro to make a custom theme for a client without having to assign ACF field for every single section on entire site manually!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by nullmem** [comment]
Also, I really miss the ability to choose custom color pallets, which you no longer have available if you use Theme Styler instead. So, why not add the custom color pallet in Theme Styler as well. This would allow for maximum flexibility. Sometimes you need to manually style something with different color than the rest of the site and want the color pallet of the site available while your doing it.

**Comment by shilo-ey** [comment]
Hey @nullmem 

Thanks for your feedback.

This is not a bug but currently, dynamic colors can’t be used in Theme Style. That being said, we have plans for extending this area in the near future.

Thanks

**Comment by horizzons** [comment]
Ridiculous indeed...
