### ISSUE TITLE
Extend Role Manager with more refined functionalities

### ISSUE THREAD

**Issue by Barns-be** [elementor/elementor#10899]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
My clients still have either too many or too few permissions with the current Role Manager.

**Describe the solution you'd like**
It should be possible to deactivate the topics "blocks" and "pages" on the template-popup when building a page. This should be a checkbox option in the Role Manager screen (on/off).
This way I (as the developer) can build template pages or blocks, give an editor (the client) permission to use the Elementor editor, BUT restrict his options to only templates I made for him, so he won't be tempted to insert things completely out of sync with the current brand.

**Comment by shilo-ey** [comment]
Hi @Barns-be 

Thanks for your feedback, I merged this issue with #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

We attend to address this request in the future but for now, you can share your ideas in the issue mentioned above.

Thanks
