### ISSUE TITLE
BUG Inline Edit Header

### ISSUE THREAD

**Issue by ravilrrr** [elementor/elementor#10897]
If I add a template widget when creating a "header" in theme builder, it overlaps with each other.
This happens when I'm on a page and trying to edit it . 
See screen https://yadi.sk/i/BkV1DVTi63RTJw

**Comment by lior-sh** [comment]
Hi @ravilrrr,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
