### ISSUE TITLE
Email Marketing Integrations

### ISSUE THREAD

**Issue by JoseSoteloCohen** [elementor/elementor#10891]
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

I created these plugins:
https://wordpress.org/plugins/moo-elements/
https://wordpress.org/plugins/inboundlatino-sendy-elements/

And they aren't working in the latest version of Elementor Pro 2.9.1

## Steps to reproduce

1. Install Elementor from the repo.
2. Install Elementor Pro version 2.9.1
3. Install Moo Elements or Sendy Elements.
4. Create page with the forms, configure the required fields.
5. Submit the form.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

**Comment by lior-sh** [comment]
Hi @JoseSoteloCohen,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
*** Isolating the problem.**
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
