### ISSUE TITLE
Archive template with that will take the same layout and design as your theme 

### ISSUE THREAD

**Issue by Goodigital-Agency** [elementor/elementor#10896]
Hello Elementor team !
It would be really great if it was possible to use the theme style in the "Publications" widget.
The goal is to create a posts archive with elementor and with the posts with theme style.
 I would like to do like the screenshot attached (its just an image for articles)
[http://www.paima-beaute.com/blog/wp-content/uploads/2020/03/Capture-d’écran-2020-03-18-à-20.52.24.png]

Best regards,
Julien

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Please note that if you are referring to Posts widget - you can disable the Default fonts and colors and the widget will inherit the colors you set in your theme style.

Thanks.
