### ISSUE TITLE
I need to add Favicon to Elementor sites using code.

### ISSUE THREAD

**Issue by WDUK1** [elementor/elementor#10903]
Hi,

We are moving sites from Divi to Elementor. In Divi I was able to set the favicon to show only on the front end adding this code to the head section:

<link rel="icon" href="image_URL.png" sizes="32x32">

I know how to set the favicon n WP but that adds it to all windows. I need the visual difference between the front end tabs and the back end tabs whilst working on sites. Otherwise it takes me much longer to get things done.

Is there similar code for Elementor, or a place where I can add the same code? I have tried a couple of places but it did not work :-/

Thank you :-)

**Comment by drawcard** [comment]
There's no feature for that in Elementor, so I would suggest using the custom function you have already to achieve that.

**Comment by WDUK1** [comment]
Thank you @drawcard 

I did try to but cannot work out how to get it in the head section.  I know it's fairly simple but I'm no coder :-)

**Comment by WDUK1** [comment]
If anyone else is interested I've managed to add the code using this plugin https://wordpress.org/plugins/insert-headers-and-footers/

The code is <link rel="icon" href="image_URL.png" sizes="32x32">

And change URL of the image of course to one in your media library.:-)
