### ISSUE TITLE
Increase / Decrease Page Margin Across Website for All Pages

### ISSUE THREAD

**Issue by Valente-Lagarto** [elementor/elementor#10906]
I have created a Navigation Menu that I am very happy with. Part of the process was to create a Top Bar Template and set its Top and Bottom Margin to -40.

I'm pleased with the results: https://prnt.sc/rilkp3

As a result of the Top Margin being set to -40, ALL my pages are now being covered by the Navigation Menu (e.g. page title), which makes sense, but I can't find the Default Page Setting that allows me to adjust the default page margin by -40 as well.

https://prnt.sc/rjhyko

If the Nav Menu has the ability to drop its margins, then I would assume that a Default Page setting somewhere would have the same functionality, but it doesn't exist. Perhaps create the functionality, or disable the negative margin setting in the Nav Bar?
-- | --

**Comment by color-space** [comment]
You will need to create a page template.

**Comment by udidol** [comment]
Hi @Valente-Lagarto,
As @color-space suggested, you can achieve this by using Elementor's Theme Builder to build page templates. In your template settings, you can set page margins.
