### ISSUE TITLE
Accordion widget title font size cannot be changed

### ISSUE THREAD

**Issue by JuliaArr** [elementor/elementor#10900]
Hi,

At the moment there is no opportunity to change the Accordion  title font size in the widget settings: https://www.screencast.com/t/VJ4uOjA94won as the setting for the font size is applied for the icon only.

Elementor Version 2.9.6, Theme Hello Elementor.

Please fix it. Thank you!

**Comment by shilo-ey** [comment]
ref: #JuliaArr 10887

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.7
Feel free to update

Thanks!
