### ISSUE TITLE
Customize widget Alert

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#10901]
Be able to add icons to an alert next to the alert title, with a separation bar between the icon and the alert title.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples - @rodolphebertozzo , please attach a screenshot of what you asked for. 
* One request per thread

Thanks.
