### ISSUE TITLE
Theme style user role permissions?

### ISSUE THREAD

**Issue by codeagencybe** [elementor/elementor#10914]
Hello

I'm trying the new Theme style feature for the first time on a client project. 
Our customers have "limited" permissions in the backend by default, meaning that they can change everything related to their website via customizer, elementor, etc... we just limit the option to install/change plugins because we do a managed service for customers. 

Our customers usually have a user role like shop manager or editor, 1 level below administrator. 
Yesterday I was trying the theme styler with my login (admin) and all is fine, but my customer with either user role shop manager or editor don't have the option theme styler. 

Is this normal? Because any shop manager or editor still has access to customizer by default, so why not to theme styler? 

Is there an action/filter/hook I can use in child theme to force this specific permissions to a certain user role? 

![image](https://user-images.githubusercontent.com/7568546/77172885-fc73cf00-6abe-11ea-8dc8-28f29ad34b2c.png)

**Comment by shilo-ey** [comment]
Hi @codeagencybe 

Theme Style affects the entire site basic design settings, therefore it's restricted to users who aren't allowed to edit the wp options.

We use `manage_options` capability to check it, so you can use any role management plugin or custom code to change your author:

```PHP
	$role = get_role( 'editor' ); // change to the role that you want to edit
	$role->add_cap( 'manage_options', true ); // name of capability
```

Thanks

**Comment by codeagencybe** [comment]
@shilo-ey 

Thanks for your feedback. 
In our case, we need specific theme style access to user role that don't require access to any of the other permissions. 
I can not give manage_options to those roles, that is out of the question. 
Since the Theme style does not (yet) support ACF custom fields, otherwise we could create an option page and let our customer handle it from there, we need a different approach. 

Is there a different workaround possible? Is there a specific hook/filter/action we can use to override this without giving full manage_options permissions? Or is there a specific "name" for this theme style capability that we can manipulate? 

Thanks!
