### ISSUE TITLE
Custom column widget elementor

### ISSUE THREAD

**Issue by tiethung** [elementor/elementor#10916]
I want to add some settings to the "inner section" and print them out. I have found a few instructions to add settings, but no way to print settings. Do you have any advice for me?

// add_settings
add_action( 'elementor/element/after_section_start', function( $element, $section_id, $args ) {
	/** @var \Elementor\Element_Base $element */
	if ( 'section' === $element->get_name() && 'section_background' === $section_id ) {
		$element->add_control(
			'custom_control',
			[
				'type' => \Elementor\Controls_Manager::NUMBER,
				'label' => __( 'Custom Control', 'plugin-name' ),
			]
		);
	}
}, 10, 3 );

**Comment by lior-sh** [comment]
Hi @tiethung ,

Thanks,
Please create GitHub issues only for bugs reports and feature requests.
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.

**Comment by udidol** [comment]
Hi, can you share a bit more details on what you're trying to achieve?
It would be easier to help you find a solution to your problem.
