### ISSUE TITLE
Image HTML Descriptions aren't parsed as HTML inside Lightboxes

### ISSUE THREAD

**Issue by color-space** [elementor/elementor#10912]
- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.
- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).

## Description

Image descriptions altough beeing interpreted as HTML Code from wordpress in the backend are not parsed as HTML in lightboxes.

## Steps to reproduce

Upload a Image, add a Description with HTML, assure in the global Lightbox options "Description" is set to "Description".

![image](https://user-images.githubusercontent.com/8644906/77163331-21137b00-6aae-11ea-9771-1faeec43149d.png)
![image](https://user-images.githubusercontent.com/8644906/77163340-253f9880-6aae-11ea-9ffc-02ab4f9fad98.png)

[System Info](https://hastebin.com/vuvofufixo.sql)

**Comment by udidol** [comment]
Hi @color-space ,
Elementor's lightbox does not support custom HTML code in the title, description or caption.
