### ISSUE TITLE
Form Editing hangs firefox browser but working in chrome

### ISSUE THREAD

**Issue by asachanfbd** [elementor/elementor#10915]
Using - Elementor 2.9.6 & Elementor 2.9.1

After last update editing of form hangs firefox tabs. It is working in Chrome. Also this version feels little slow than previous ones. Please let me know what else you need to debug.

**Comment by lior-sh** [comment]
Hi @asachanfbd,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
