### ISSUE TITLE
"logo position bug" on tablet and mobile

### ISSUE THREAD

**Issue by danimail49** [elementor/elementor#10910]
Hi Elementor team

I made you a video of the bug:
https://www.loom.com/share/38f5a60ad94d4c15bf3d489195d2d5d6

Can you please fix it?
Thanks,
Daniel.T

**Comment by lior-sh** [comment]
Hi @danimail49,

Thanks for reporting, we cannot reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
