### ISSUE TITLE
Adjust z-index for responsive breakpoints

### ISSUE THREAD

**Issue by rhud** [elementor/elementor#10918]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When reversing columns on tablet/mobile breakpoints, being able to adjust the z-index of a column or element per breakpoint also would allow much more flexibility. **This would be especially helpful when using negative margins on elements for modern layouts.**

**Describe the solution you'd like**
Simply add the breakpoint setting to the z-index field. 

**Describe alternatives you've considered**
Using manual CSS is an option, but not practical for most users. 

**Additional context**
<img width="725" alt="Screen Shot 2020-03-21 at 7 27 42 pm" src="https://user-images.githubusercontent.com/136080/77223634-25bd5980-6baa-11ea-8206-fa27ef39b073.png">
Here is an example of where I was wanting to use negative margins for the '02', but on mobile view, the number is hidden behind the image. The image column needs to be at a higher z-index for desktop view, but not necessary for tablet/mobile

**Comment by shilo-ey** [comment]
Hi @rhud 

Thanks for your inputs, 

We will consider adding this option in the upcoming versions.

Thanks

**Comment by rhud** [comment]
That's all I can ask! Keep up the AMAZING work 😊

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!
