### ISSUE TITLE
Archive Posts widget Image Ratio bug

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#10920]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor 2.9.6 and Pro 2.9.1

## Description
When changing the Image Ratio there is the ratio value displays in the left corner.

## Steps to reproduce

1. Place the Archive Posts widget
2. Move the Image Ratio slider
3. look at the left corner of the widget under the pagination

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

![scale](https://user-images.githubusercontent.com/12493645/77232368-489b3e00-6ba9-11ea-99c4-2f504dd7adb9.gif)

**Comment by shilo-ey** [comment]
Hi @parfilov 

Thanks for your feedback.

I merged this issue with #10874, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks!
