### ISSUE TITLE
[Feature Request] More convenient use of the Tab widget for Pro users

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#10933]
It would be nice to be able to directly select our section template to insert in the Tab widget heading (for the Pro version), this would save time and avoid having to go to the template heading and copy the short code of each template. Another practical aspect is that a user can create a section on the same page, save it as a template and then delete the section. And without leaving the page, by inserting the Tab widget, he can directly select the recently saved template in the field in question. With this feature, the user gains in efficiency!

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by arielk** [comment]
This is one of the most famous and oldest requests in Elementor, we still do not know for sure how to do it without changing the foundations of the editor, so I merge it into the original issue: https://github.com/elementor/elementor/issues/2587

Thanks for your feedback!
