### ISSUE TITLE
FEATURE REQUEST: New Post or Page without going to the Dashboard

### ISSUE THREAD

**Issue by guruscotty** [elementor/elementor#10934]
How about the ability to create a new post or page from inside Elementor, without exiting to the dashboard? Super-duper helpful when cranking out a new site.

**Comment by shilo-ey** [comment]
Have you tried the finder? try clicking CTRL/CMD+E and type "new page" or "new post"

Read more: https://docs.elementor.com/article/440-the-finder

Thanks

**Comment by guruscotty** [comment]
Oh, wow. 
    
    Did not know about that. Thank you!
    
    On 3/23/20 7:25 AM, shilo-ey wrote:
    
    
      
      Have you tried the finder? try clicking CTRL/CMD+E and type
        "new page" or "new post"
      Read more: https://docs.elementor.com/article/440-the-finder
      Thanks
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/elementor/elementor/issues/10934#issuecomment-602559602",
"url": "https://github.com/elementor/elementor/issues/10934#issuecomment-602559602",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
      Scott Anderson
        Agent of Change
        Donovan+Gilhooley
        817.914.5345
        ___________________________________________________________
        Happiness is when what you think, what you say,
        and what you do are in harmony. --Mahatma Gandhi
