### ISSUE TITLE
Change "Maintenance Mode" URL link in the WordPress admin bar

### ISSUE THREAD

**Issue by poehaldur** [elementor/elementor#10938]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

_I asked from Elementor Technical Support first and they directed me here_.

**What problem is your feature request going to solve? Please describe.**
I have clients who do not have access to elementor settings page and I allow them to turn on maintenance mode thru ACF. The problem is that when the maintenance mode is activated in admin menu, it redirects to /wp-admin/admin.php?page=elementor-tools#tab-maintenance_mode

**Describe the solution you'd like**
Is there a snippet that would redirect the link to my custom ACF settings page?

**Additional context**
Long story short this admin bar button directs to /wp-admin/admin.php?page=elementor-tools#tab-maintenance_mode but I need it to go to /wp-admin/admin.php?page=my-settings-page
![download (10)](https://user-images.githubusercontent.com/32192439/77312961-a0ea5100-6d0b-11ea-935f-e830ae4c0f6b.png)

The code itself is at [https://github.com/elementor/elementor/blob/master/includes/maintenance-mode.php](https://github.com/elementor/elementor/blob/master/includes/maintenance-mode.php) but I don't know how to write the filter based on this.

/**
	 * Add menu in admin bar.
	 *
	 * Adds "Maintenance Mode" items to the WordPress admin bar.
	 *
	 * Fired by `admin_bar_menu` filter.
	 *
	 * @since 1.4.0
	 * @access public
	 *
	 * @param \WP_Admin_Bar $wp_admin_bar WP_Admin_Bar instance, passed by reference.
	 */
	public function add_menu_in_admin_bar( \WP_Admin_Bar $wp_admin_bar ) {
		$wp_admin_bar->add_node( [
			'id' => 'elementor-maintenance-on',
			'title' => __( 'Maintenance Mode ON', 'elementor' ),
			'href' => Tools::get_url() . '#tab-maintenance_mode',
		] );
		$document = Plugin::$instance->documents->get( self::get( 'template_id' ) );
		$wp_admin_bar->add_node( [
			'id' => 'elementor-maintenance-edit',
			'parent' => 'elementor-maintenance-on',
			'title' => __( 'Edit Template', 'elementor' ),
			'href' => $document ? $document->get_edit_url() : '',
		] );
	}

**Comment by shilo-ey** [comment]
Hey @poehaldur 

Elementor has CLI command for enabling and disabling Maintenance mode, which you can trigger or extend. read more here: #8112

**Comment by poehaldur** [comment]
My question is not about enabling or disabling maintenance mode but the fact that once it is enabled (red link in image) then by clicking on it goes to /wp-admin/admin.php?page=elementor-tools#tab-maintenance_mode but I need it to go to custom URL.

**Comment by shilo-ey** [comment]
So as described in the issue attached, if you want to bypass the regular method of activate/deactivate you can either grant your user the sufficient capability or alternatively create a custom trigger that triggers the CLI command.

**Comment by poehaldur** [comment]
Not sure what you mean, I need a custom trigger thru CLI to replace the URL? Can't  I use a single line funtions.php snippet that replaces href to my custom url?

**Comment by shilo-ey** [comment]
You don't have to use CLI to do so, 

The code you copied is only responsible for visualization of the state (including a link to the area that controls this feature).
This option won't change generally.

You can use the same method that we used, simply update the options.php table with the corresponding values:
```PHP
class Maintenance_Mode {

	/**
	 * The options prefix.
	 */
	const OPTION_PREFIX = 'elementor_maintenance_mode_';

	/**
	 * The maintenance mode.
	 */
	const MODE_MAINTENANCE = 'maintenance';

	/**
	 * The coming soon mode.
	 */
	const MODE_COMING_SOON = 'coming_soon';
```

Good luck!

**Comment by poehaldur** [comment]
I don't understand what does the maintenance mode options have to do with anything? I can change the options thru ACF on my custom settings page, that is not the problem. The "visualization of the state" code I added generates the link in toolbar menu that by clicking on it goes to the elementor options page.

Can't I just have a function snippet like
If admin_bar_menu 
then 
overwrite 'href' => Tools::get_url() . '#tab-maintenance_mode', 
to 'href' => my_url or something?

**Comment by poehaldur** [comment]
@shilo-ey Can you please open my topic, nobody reads closed topics.
Thanks.

**Comment by shilo-ey** [comment]
```PHP
	add_action( 'admin_bar_menu', function( $wp_admin_bar ) {
		$new_url = 'http://example.com/custom/location'; // your custom URL
	
		if ( $wp_admin_bar->get_node( 'elementor-maintenance-on') ) {
			$wp_admin_bar->add_node( [
				'id'   => 'elementor-maintenance-on',
				'href' => $new_url,
			] );
	} , 999 );
```

Use this and alter your URL.

Thanks
