### ISSUE TITLE
Pro widgets are not draggable unless Elementor license has been activated

### ISSUE THREAD

**Issue by iamntz** [elementor/elementor#10939]
On 2.9.0 - 2020-03-15 build of Pro, this popped up in the changelog:

> * Tweak: Pro widgets are not draggable unless Elementor license has been activated

Since I'm using the elementor both locally and production (on my client sites), this means that... i can't develop sites locally unless i get the localhost activated. Which is... uhm... less than ideal.

The issue that's more important is what it will happen after my client license is expiring? He won't be able to use pro widgets?

**Comment by shilo-ey** [comment]
Hi @iamntz 
Thanks for your feedback. In an effort to fight piracy we decided that sites that are not activated won't have the ability to drag in new widgets.

Expired license - [as mentioned in this doc](https://docs.elementor.com/article/626-why-cant-i-drag-the-pro-widgets) - can still be "draggable"

**Comment by iamntz** [comment]
Alrighty then. I was afraid that my clients will have this issue if, at some point in the future, they decide not to renew their subscription.

Thanks for your swift reply!
