### ISSUE TITLE
[BUG] Dont run redirect action with shortcode in url [Elementor PRO 2.9.1]

### ISSUE THREAD

**Issue by eduardovillao** [elementor/elementor#10932]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Dont run redirect action with shortcode in url. Like: https://www.google.com/search?q=[field id=name]

IMPORTANT: In input tab the auto shortcode generated dont have " " in id.
IMPORTANT 2: Missing " " in shortcode its the BUG. If you add id between " " in shortcode action is run.

![Captura de Tela 2020-03-21 às 13 34 01](https://user-images.githubusercontent.com/60461940/77254602-cbbba300-6c40-11ea-8818-2b5962b1b584.png)

## Steps to reproduce

1. Add action redirect after submit Form on Widget.
2. Add field shortcode in link to redirect. like: https://www.google.com/search?q=[field id=name]
3. Dont redirect WITH shortcode in link.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.29
	PHP Version: 7.3.15
	PHP Max Input Vars: 10000
	PHP Max Post Size: 600M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://www.evcode.com.br
	Home URL: https://www.evcode.com.br
	WP Multisite: No
	Max Upload Size: 600 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Active

== Theme ==
	Name: OceanWP
	Version: 1.7.4
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.4
		Author: Automattic

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Ele Custom Skin
		Version: 1.3.11
		Author: Dudaster.com

	Elementor
		Version: 2.9.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.1
		Author: Elementor.com

	Extension for Elementor Form
		Version: 1.0
		Author: EVCODE

	Form Masks for Elementor PRO
		Version: 1.2
		Author: EVCODE

	Jetpack by WordPress.com
		Version: 8.3
		Author: Automattic

	Ocean Elementor Widgets
		Version: 1.1.9
		Author: OceanWP

	Ocean Extra
		Version: 1.6.0
		Author: OceanWP

	Order on WhatsApp for WooCommerce
		Version: 1.1.6
		Author: EVCODE

	Redirection
		Version: 4.7.1
		Author: John Godley

	Site Kit by Google
		Version: 1.5.1
		Author: Google

	WooCommerce
		Version: 4.0.1
		Author: Automattic

	Wordfence Security
		Version: 7.4.6
		Author: Wordfence

	WP Performance Score Booster
		Version: 1.9.2.2
		Author: Dipak C. Gajjar

	Yoast SEO
		Version: 13.3
		Author: Team Yoast

== Elements Usage ==
	
	page : 3
		heading : 1
		text-editor : 2
	section : 15
		button : 15
		heading : 26
		html : 1
		icon-box : 3
		image : 8
		image-box : 9
		social-icons : 2
		text-editor : 16
	wp-post : 0
		button : 16
		heading : 36
		html : 1
		icon-box : 2
		icon-list : 1
		image : 7
		image-box : 12
		menu-anchor : 4
		social-icons : 1
		text-editor : 13
	wp-page : 11
		form : 1
		heading : 1

== Log ==
	
Log: showing 20 of 402019-10-31 17:58:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.2',
  'to' => '2.7.3',
)]
2019-12-18 16:29:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.8.2',
)]
2019-12-18 16:30:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.1',
)]
2020-01-14 16:53:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-14 16:53:04 [info] elementor::elementor_updater Started 
2020-01-14 16:53:04 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-14 16:53:05 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-14 16:53:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-14 16:53:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-14 16:56:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.1',
  'to' => '2.8.3',
)]
2020-01-30 18:13:32 [info] elementor::elementor_updater Started 
2020-01-30 18:13:32 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-30 18:13:32 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-30 18:13:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.5',
)]
2020-02-17 01:36:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.2',
)]
2020-02-17 01:36:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-02-28 12:07:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-19 19:29:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.6',
)]
2020-03-19 19:54:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.9.1',
)]
2020-03-19 19:54:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.9.1',
)]

PHP: showing 2 of 2PHP: 2019-07-24 08:20:51 [notice X 65][/home/evcode/public_html/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1248] Undefined index: button_icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-28 23:41:05 [error X 5][/home/evcode/public_html/wp-content/plugins/elementor-pro/includes/modules-manager.php::81] syntax error, unexpected '<', expecting end of file [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2019-10-15 18:10:56 [error X 3][https://www.evcode.com.br/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view768\") has already been destroyed and cannot be used. 
</details>

**Comment by shilo-ey** [comment]
Hi @eduardovillao 

Thanks for your feedback.

I'm having trouble understanding the purpose of this issue:
Can you explain why we should block this option? missing quotation marks is something we made by design, to allow users to add user-populated parameters in the actions after submit without breaking the URL encoding.

What is the downside of allowing this?

If you refer to the missing quotation marks please explain why it should be added?

Thanks

**Comment by eduardovillao** [comment]
Hi @shilo-ey without quotation mark in shortcode dont run redirect action. 

If i add shortcode in url dont redirect the form after submit. 

Make a test. Create form, and add redirect link with shortcode (without quotation mark). After submit, dont redirect!

**Comment by PiotrKrzyzek** [comment]
I can confirm this issue.

If, for example, I want to use a field with the id `name` ... the output from Elementor Forms says I should use:

`[field id=name]`

Though if we use that, it will generate an error as instead we need to use:

`[field id='name']`

**Comment by eduardovillao** [comment]
@PiotrKrzyzek Perfect!

**Comment by soyket** [comment]
@shilo-ey issue confirmed

**Comment by eduardovillao** [comment]
Hi @shilo-ey any return?

**Comment by diecreativo** [comment]
This is a BUG.

When the URL is:

mydomain.com/?name=field id=name]

Does not redirect due to space between field and id.

**Comment by soyket** [comment]
@diecreativo 
The field ID should be like this -> 
[field id="name"]

**Comment by lior-sh** [comment]
Hi @eduardovillao,

As @diecreativo described it should be [field id="name"]
Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.9.3

Feel free to update

Thanks!

**Comment by eduardovillao** [comment]
Thanks!
