### ISSUE TITLE
🚀 Feature Request: Author Box widget, add flexible Gravatar image size - [ED-8877]

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#10947]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The Author Box widget creates a request to gravatar like
https://secure.gravatar.com/avatar/number?s=300&d=mm&r=g

s=300 specifies the images size
Even if I change the image size in the Author Box Style settings, the URL parameter is still 300

This leads to a hint in GTMetrix performance report:

```
The following images are resized in HTML or CSS. Serving scaled images could save 30.9KiB (88% reduction).
    https://...avatar/...?s=300&d=mm&r=g is resized in HTML or CSS from 300x300 to 100x100. Serving a scaled image could save 27.8KiB (88% reduction).
```

**Describe the solution you'd like**

Change the URL parameter to the Image Size which is specified in the Author Box Style.
If not specified go with the default.

**Describe alternatives you've considered**

**Additional context**

**Comment by nicholaszein** [comment]
Hello there @ghost!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
