### ISSUE TITLE
Search form widget issues

### ISSUE THREAD

**Issue by JuliaArr** [elementor/elementor#10948]
Hi, 

There is one issue with the Search form widget - the input form shadow is cut: https://www.screencast.com/t/wfU7OYSQO8

Also is there an opportunity to set the space between the input and button, and to have the different border radius for the input and the buttom?

Thanks!

**Comment by lior-sh** [comment]
Hi @JuliaArr,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
