### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Animated Lottie Background (Merged with #20444)

### ISSUE THREAD

**Issue by FrancoDarget** [elementor/elementor#10954]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to create a hero like this one: http://www.gulpie.co/
I have the Lottie animation and don't know if I should convert it to mp4, and set it as a background video, create an image and place it to the right, or set it as a background image and put the Lottie file.
**Describe the solution you'd like**
How can I achieve this example? http://www.gulpie.co/
**Describe alternatives you've considered**
Plugins, converting into mp4.
**Additional context**

**Comment by yawalkar** [comment]
Hey everyone!

I have received quite a few requests on a daily basis for this, so I made a tiny plugin for Elementor to let you add Lottie Animations to Elementor sections and columns. You can grab it from here - [https://www.infiwebs.com/lottie-bg-elementor/](https://www.infiwebs.com/lottie-bg-elementor/)

If you have any questions, or need any help with this plugin, please feel free to contact me.

Kind regards,
Nitin

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11698, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔃  This request is being merged with #20444.

Which is on the same subject. 

For this reason, I'm closing the comments, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
