### ISSUE TITLE
[BUG report]

### ISSUE THREAD

**Issue by davidefiorio** [elementor/elementor#10965]
Elementor PRO
v 2.9.1

When I add 

"Action after submit"
Email2

Form doesn't send email and result in Error

I resolve with rollback to versione 2.8

**Comment by lior-sh** [comment]
Hi @davidefiorio, 

Thanks for reporting, we couldn't reproduce the issue
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
