### ISSUE TITLE
Add "Height" and "Image Fit" commands for widget image

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#10962]
It would be nice to be able to add controls to adjust the height of the image and the type of image resizing

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by fabianenzensperger** [comment]
What can be found in Beta 3 for Elementor 3.0 #11821 is great. It would be even better if you could also determine different aspect ratios. For example 3: 2, 5: 4, 16: 9. As it is now it is relatively spongy, but cool if you want to move freely. But if it should have a certain relationship, it is not useful.

Would be nice if you @shilo-ey would take that into account.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!
