### ISSUE TITLE
German Translation Bug for Text-Transform

### ISSUE THREAD

**Issue by thomasmalley** [elementor/elementor#10964]
Edit: This only affects the "Formal" Version of the German Language Translations 
See https://translate.wordpress.org/projects/wp-plugins/elementor/stable/de/formal/?filters%5Bterm%5D=uppercase for the suggestion 

There are two different Select-Options für Text-Transform with the same Translation / String-Value now
Please refer to the attached Screenshot
<img width="286" alt="Bildschirmfoto 2020-03-25 um 12 06 25" src="https://user-images.githubusercontent.com/13106168/77531505-51cf2800-6e93-11ea-9338-30ae6a3d999d.png">
The Translation for Uppercase is simply wrong. It should be called "Versalien" or "Großbuchstaben" if you write like this: HELLO MY NAME IS 
It was called "Versalien" recently

Capitalize or "Großschreibung" means writing like this "Hello My Name Is" 

Hope this is easily fixable
Best Regards

**Comment by dasigna** [comment]
yeah. thats really annoying.

to be honest - i used to translate a lot of things in the past (this one also, and correctly!).
but thats a big reason i stopped it - investing lots of time in translation until someone else comes along and makes it worse again or changing it to a simply wrong term, as seeing in above example actually ...
already mentioned this towards elementor on more than one occasion. but its not getting better.
this happens far too often. sadly more and more fron non-native speakers that are simply using google - obviously. useless taking any more efforts on this. even though you are native speaker and elementor user ...
thats awful as well as disappointing.

bummer.

**Comment by thomasmalley** [comment]
That sounds very discouraging @dasigna especially since you are one of the main contributors! There should be some kind of hierarchy system based on experience and trust.

BTW: I had Trouble finding the incorrect String in the first place. 
I tried to follow https://docs.elementor.com/article/42-translate but I don't see a possibility to search within https://translate.wordpress.org/projects/wp-plugins/elementor/stable/de/default/  for a certain string. Is there a hidden / pro way to do this? I want to avoid clicking through 77 Pages, scanning 1148 Translations to find the one I'm looking to correct 😅
