### ISSUE TITLE
paragraph tag wraps text in editor field upon cut command. - screencast available

### ISSUE THREAD

**Issue by Bovelett** [elementor/elementor#10960]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**This is mainly about what happens upon cutting text, not so much about the pasting, as you already have another report on the inline styles that are coming along upon pasting**
 
I have searched for similar items, and saw this one  #5671 but found none such as mine. I made a screencast that demonstrates the steps to reproduce this issue, link is below the steps, but I will still describe the steps, just in case.

I had made my screencast before I found the previously reported pasting issue. Please forgive me if I do not remake my screencast, I'm pretty much floored with the flu right now. No need to watch the whole love story there though, you will see the isolated issue from 2m:15s until 3m:24s

I'm using Hello Theme. But I have reproduced this in the WordPress 2020 theme as well.

As soon as you hit cut (I do CMD + X as I am on a Mac), the text within the entire widget is wrapped in paragraph tags. 

I am aware you may not be able to control what CMD -V (or Windows CTRL+V) does, and that it's not so easy to convince people they should use CMD+shift+V upon pasting. Because it feels unnatural in comparison to the very intuitive interface of Elementor in general. But the CMD+X phenomenon is problematic. I don't know of another way to cut text, because it also happens when you select text and then use the edit menu of your browser to cut the selection.

Many unsuspecting end-users work straight in the text widget **on** the page. That they copy and paste from within a text widget is also to be expected. They may at some point figure out that pasting also pastes unexpected styles as this issue has not only been risen here, but is found in our FB Community as well. We may be able guide them into using cmd+shift+v and to use the editor in the side bar. But that is not always pleasant, because often when you type your text in the editor in the sidebar, it doesn't always immediately appear in the widget on the page, unless you refresh the backend...

This bug is probably a real PITA to solve (we dealt with this and the pasting pains at CMSMS™ back in the golden days, by creating a stripped version called MicroTiny, you'll find that flying around on GitHub somewhere, both original and forked).

## Steps to reproduce

1. Add a text widget
2. Type text inside that widget in the page, not in the editor field in the sidebar.
3. Select random text in the widget on the page
4. Switch the editor in the sidebar from visual to text
5. Cut the selection from the text widget **on** the page
6. Now look at the text editor in the sidebar, you see the text gets wrapped in a paragraph tag.

Here is [the link to the screencast](https://geekonheels.dev/wp-content/uploads/2020/03/inline-style-insertion.mp4) I made that demonstrates the steps to reproduce this issue. The isolated issue is shown from 2m:15s until 3m:24s.

Thanks for looking into this.

Cheers and a hug,

Anne

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.6.44-86.0
	PHP Version: 7.3.15
	PHP Max Input Vars: 100000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://annebovelett.eu
	Home URL: https://annebovelett.eu
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.1
		Author: Elementor.com


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	header : 1
		button : 1
		theme-site-logo : 1
	page : 1
		image : 1
	popup : 3
		nav-menu : 1
	wp-page : 2
		button : 1
		heading : 10
		image : 1
		text-editor : 9


== Log ==
	
JS: showing 3 of 3JS: 2020-03-22 21:28:46 [error X 1790][https://annebovelett.eu/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read property \'clone\' of null 
JS: 2020-03-22 21:28:57 [error X 36][https://annebovelett.eu/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read property \'changestop\' of null 
JS: 2020-03-23 22:24:57 [error X 1][https://annebovelett.eu/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.6:2:106915] Routes: `theme-builder-publish/triggers` is already registered. 

PHP: showing 2 of 2PHP: 2020-03-24 00:53:43 [notice X 2][/home/annebovelett/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-24 15:15:47 [error X 1][/home/annebovelett/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/annebovelett/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/annebovelett/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/annebovelett/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/annebovelett/public_html/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/annebovelett/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
				
</details>

**Comment by rami-elementor** [comment]
Hi @Bovelett ,

I'm not sure it's an Elementor issue.

You have two options to paste content from your clipboard:

- **Paste** (CMD + V)
- **Paste as plain text** (CMD + SHIFT + V)

The second option should solve your problem, it strips all the HTML tags.
