### ISSUE TITLE
 A Grid Element

### ISSUE THREAD

**Issue by nexgendevs** [elementor/elementor#10966]
I have tried to search it on google but nothing found.
Is there something like below in planning?

https://theme.co/docs/grid

**Comment by ErwinLiemburg** [comment]
Agree with @nexgendevs . I would like to see a grid Element as an addition to the Inner Section Element. Where I can not only add columns, but rows as well. CSS Grid as an addition to the CSS Flex.

**Comment by creativefold** [comment]
I'd love to see this feature as well!

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #452, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/18839

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the first beta implementation of the Grid Container is live! 🙌 

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪 

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment]
Hello, there everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the first phase of this feature was released with Elementor **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
