### ISSUE TITLE
Animated headline and audio player not working

### ISSUE THREAD

**Issue by tdxiang** [elementor/elementor#10974]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

I'm having problems with the animated headline and audio player. These features are visible in editing mode, but when you go to Preview or Publish, they are not visible at all. They simply come out as blank. The audio player is just an empty box. Any idea how to fix these issues?

**Comment by lior-sh** [comment]
Hi @tdxiang,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
* Record of the bug by video if possible
Without it, we simply can't help.
Thanks.
