### ISSUE TITLE
Filter WP widget categories

### ISSUE THREAD

**Issue by Stiofan** [elementor/elementor#10970]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Plugin authors can't organize their widgets into a new category. All our plugin features are in WP widgets but to show them at the top when editing a specific CPT we would need to register them again instead of just being able to adjust the category of our own widgets.

**Describe the solution you'd like**
Add a filter (pull request to follow)

**Describe alternatives you've considered**
Un-register the widget and then register it again using our own class with the category change but this is much more memory expensive.

**Comment by ramiy** [comment]
This is a very nice idea.

**Comment by rami-elementor** [comment]
See comment https://github.com/elementor/elementor/pull/10971#issuecomment-1397030835
