### ISSUE TITLE
Element visible on column hover

### ISSUE THREAD

**Issue by TheBigBanik** [elementor/elementor#10976]
Element visibility should be a must if we need to create custom archive pages of everything. For example, if creating a loop for a real estate archive page, we have to show the image, the name of the property and the price. But when we hover this loop, the bedroom, bathroom, sqm and other info should show up. Visual composer can do this with the grid builder where we can display different elements in the default view and different elements on hover. That way, we can build any archive, even woocommerce archives without having to use 3rd party plugins or themes that have already this feature implemented. I think it would be easier if the column has an option for hover elements to drag what we need there.

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
