### ISSUE TITLE
⛔ Featured image widget doesn't update automatically when the image is updated in another tab

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#10973]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Changing the featured image in Elementor editor doesn't update the featured image widget in the editor. We need to update the page and reload the page to see the change.

## Steps to reproduce

1. Create a page with Elementor
2. Add a featured image widget
3. Add a featured image
4. The featured image stays gray. 
5. Save the page and reload the page
6. The featured image is visible in the Featured image widget
7. Change the featured image
8. The old image is still shown in the featured image widget.

The featured image in the widget should be updated in the editor when we change the featured image.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @vgstef,

Thanks for reporting, we couldn't reproduce the bug.
Can you please record the issue by a video and add the System info?
Thanks.

**Comment by vgstef** [comment]
Thanks for the follow-up.

I also realised the Title isn't updated live.

I made a Screencast to show the problem and I join the system info.

Sreencast: https://youtu.be/zfuRE6YVpG8

System info: [system-info-traaq.org-27-03-2020.txt](https://github.com/elementor/elementor/files/4391274/system-info-traaq.org-27-03-2020.txt)

**Comment by nicholaszein** [comment]
Hello @vgstef,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- Elementor does not load content dynamically when you are using the Editor. If you change some content in another tab, you need to refresh the editor. Currently we have no plans to change this behavior, as this would dramatically decrease the editor's performance.

### 👍 For now, that's all we can help with. 

Kind regards
