### ISSUE TITLE
Maintenance mode displays header for pages that does not exist

### ISSUE THREAD

**Issue by Maximus97** [elementor/elementor#10985]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

The maintenance mode manages to disable the header for published pages. However, it fails to do so for pages that do not exist (i.e typing in "mydomain.com/asjdlkasd"). By doing this, the template I chose for Maintenance mode displays but the header is not removed.
## Steps to reproduce
Simply visit a page that does not exist, with Maintenance mode activated, and you will see the header displayed

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.22
	PHP Version: 7.2.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: censored
	Home URL: censored
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.3.4
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Starter Templates
		Version: 2.1.0
		Author: Brainstorm Force

	Wordfence Security
		Version: 7.4.6
		Author: Wordfence

	WP Content Copy Protection & No Right Click
		Version: 1.7.3
		Author: wp-buy


== Elements Usage ==
	
	page : 2
		heading : 1
	wp-post : 0
		heading : 37
		icon-list : -2
		image : 27
		social-icons : 31
		spacer : 3
		text-editor : -4
	wp-page : 9
		button : 6
		heading : 66
		image : -10
		image-box : -6
		social-icons : 32
		spacer : 4
		text-editor : -24


== Log ==	
censored due to containing my URL

**Comment by arielk** [comment]
Thanks for reporting, we couldn't reproduce the issue, please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And see if the issue still persists.
