### ISSUE TITLE
Images linked from External sources ex.Flickr,Google Photos

### ISSUE THREAD

**Issue by 2020lillian** [elementor/elementor#10987]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

All widgets except HTML require photos be in Media gallery
**What problem is your feature request going to solve? Please describe.**

All widgets except HTML require photos be in Media gallery, and this makes the site slow, and bigger vs having photos come from different sources
**Describe the solution you'd like**

be able link my photos into other widgets such as Portfolio,Gallery,ETC from a link/Embedded code without using the HTML Widget 
**Describe alternatives you've considered**
HTML widget is only option,but it doesn't have the stylish options as the Portfolio or Gallery widgets

This would look like the video option you put in the URL and it shows
**Additional context**

**Comment by shilo-ey** [comment]
I merged this issue with  #413, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
