### ISSUE TITLE
Share post button issue

### ISSUE THREAD

**Issue by shroomers88** [elementor/elementor#10994]
Hi!

As you can see in the below screenshot, I've used the "share post" widget and changed the icons using CSS. It works just fine in Elementor, but once I move to the live version of the website (out of the builder), you can see that the social logos don't show up. Instead, the font awesome icon ID that's in the CSS code appears.
Here's the screenshot:

https://www.screencast.com/t/Udit7d0s3D
Here's the CSS code I'm using:

.fa-linkedin:before{
content: "\f0e1"
}
.fa-facebook:before{
content: "\f39e"
}
Before Elementor version update 2.9 (which caused several other issues on my site), I was able to have it working by editing the following part of the code: content: "\\f0e1" + content: "\\f39e" (double backslash instead of single). 

Can anyone help me?

**Comment by lior-sh** [comment]
Hi @shroomers88,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
