### ISSUE TITLE
Give Flip Box background image a size setting

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#11005]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The Flip Box would very much benefit from a setting where you can choose which background image file size (from the available sizes (thumbnail, small, medium, large, full) created at upload) to use for front background and back background. Now you have to manually scale an image before upload to a size that you think will suffice. 

If would be even better if you could change this size settings for the different viewport sizes (laptop, tablet, mobile). As it works now the Flip Box takes the original image uploaded (if I am not missing something). Which in most cases is way too large, considering the impact unscaled images has on page speed.

Best wishes
Magnus

**Comment by arielk** [comment]
Since version 2.4 you can do this, please read more here: https://elementor.com/blog/responsive-image-background/

**Comment by tamelander** [comment]
No, I think you're wrong or didn't read what I wrote. The **background image** of the flip-box. It's not the image can be added to the front of the flip-box, which has settings for image size (thumbnail, small, medium, large etcetera). The background image of the flip-box when set is loaded as the size it is in the media library. It doesn't matter if the flip-box is page wide in desktop view or narrow in mobile view, the same background image is loaded.

**Comment by arielk** [comment]
Okay, this is normal behavior in all places where there is background control, we use the image you selected without special compatibility to avoid unexpected display issues.

Note that you can choose a different background image for each device, you can learn about this feature here: https://elementor.com/blog/responsive-image-background/
