### ISSUE TITLE
Feature Request to 'Add individual CSS Id to tabs'

### ISSUE THREAD

**Issue by roh999** [elementor/elementor#11006]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hello,
I would like to request a feature wherein Elementor Pro users can add individual CSS Id while using 'Accordions' or 'Tabs' or 'Filterable Gallery'. I mean, if I have a list of 5 tabs using Accordions, and if I have listed all those 5 items on another page (that are added to the 5 tabs), then if I click on any of the tabs, it should take me to the page where I have already added the 5 tabs using 'Accordions', but the most important part here is that it should automatically open the corresponding /respective tab that I clicked on the previous page.
This can only happen if we define individual CSS Id's for individual tabs in the 'Accordions' or 'Tabs' or 'Filterable Gallery' elements.

Kindly look into this and add this feature, if possible. Thank you.

Regards,
Rohit.

**Describe the solution you'd like**
As mentioned above.

**Describe alternatives you've considered**
I tried many possible alternatives (except coding), but no luck. It would be quite exhaustive to describe here regarding the steps taken on the alternatives.

**Additional context**
N/A

**Comment by Aviad-Herman** [comment]
Hi,
Great idea.
I'm merging this with #8844
