### ISSUE TITLE
On scroll background color change

### ISSUE THREAD

**Issue by pinkgerbils** [elementor/elementor#11017]
There are many flamboyant scrolling effects built into Elementor, but for some reason no simple color change.

This exists in several elementor add-ons so wonder why it isn't offered natively?

See here: https://elementor.theplusaddons.com/widgets/row-background/on-scroll-background-color-change/

**Comment by lior-sh** [comment]
Hi @pinkgerbils,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
