### ISSUE TITLE
Customize Cart and Checkout pages 

### ISSUE THREAD

**Issue by pedrosromano** [elementor/elementor#11014]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Many of my clients want a custom e-commerce buying experience and almost always, custom designed cart and checkout pages are needed.

**Describe the solution you'd like**
I would like Elementor to allow me to customize Cart and Checkout pages for WooCommerce. Right now i use an external plugin to achieve this: https://codecanyon.net/item/woocommerce-page-builder-for-elementor/23339868

Other important features:
- Custom login and promo codes header text and design
- Custom cart sidebar

**Describe alternatives you've considered**
To achieve this i rely on this plugin: https://codecanyon.net/item/woocommerce-page-builder-for-elementor/23339868

**Comment by jazir5** [comment]
Completely agreed, i have tried a number of different third party elementor addons for Checkout and Cart, and they are ALL sorely lacking. To add to this, a customizable Mini-Cart widget that can be placed in a menu would be great to have included in Elementor core as well.

Powerpack has one: 

https://powerpackelements.com/woocommerce-elementor-widgets/mini-cart-widget/

But it's customization options are limited and Powerpack adds a lot of overhead just to have that one widget. 

Briefcase for Elementor has it, but Briefcase also has a ton of overhead and limited customization options for it as well. You can't even use a custom icon on their widget.

**Comment by SirChopper** [comment]
Looking for these feature too !!!!!!!

**Comment by bobmulder** [comment]
Oh man, I really want this so bad! I'm completely comfortable with Elementor Pro but I hate to get out of my comfort zone to just hand-style my checkout pages XD.

Support of Elementor told me this: 

> We do not have an ETA for that right now. I know it is on our internal roadmap but I do not know exactly when is the feature going to be rolled out to Elementor Pro.

So, unfortunately we don't have any insights into the roadmap but I am hoping for the best!

**Comment by PascalClaro** [comment]
Elementor definitely needs a deeper integration with WooCommerce:

1. Cart page
2. Checkout page
3. My account page
4. WooCommerce Buttons and Form styles need to be customisable through the new Theme Style option.

**Comment by peepersqueaker** [comment]
Any progress on this yet?

**Comment by bobmulder** [comment]
Nope, I was hoping for these features in version 3 and I can't find any roadmap from Elementor...

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!

**Comment by qwik3r** [comment]
> This feature has been added to Elementor Pro v3.5.0
> 
> Feel free to update
> 
> Thanks!

It would be great if you could add a thumbnail of the product on the Woocommerce checkout form. It seems like you guys did the bare minimum with the Woocommerce cart widget options.
