### ISSUE TITLE
Google font not loading in Elementor Pro Template widget preview

### ISSUE THREAD

**Issue by evgeniyshay** [elementor/elementor#11019]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Pro Template widget not loading custom google font family, there is no link tag for the desired fonts.

## Steps to reproduce

1. create new section template
    - add heading widget
    - open typography and set custom google font family in this heading widget style tab
    - save template
2. create new page template
    - add Elementor Pro Template widget
    - in Choose Template control select section from step 1
3. in preview you will see that custom google font family not load, but if you go to the frontend google font in this widget loads correctly.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @evgeniyshay,

Thanks for reporting, we couldn't reproduce this issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
* Video 
Without it, we simply can't help.
Thanks.

**Comment by evgeniyshay** [comment]
Ok, it is possible.
There is a reproducing video
https://www.screencast.com/t/WjAH8NZcz0Pv
