### ISSUE TITLE
Background slider not displayed on older versions of IE/Firefox

### ISSUE THREAD

**Issue by flos1988** [elementor/elementor#11016]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I just created my new homepage with the background-slider effect of the free version of Elementor. On my Macbook pro with the latest Firefox and Safari it works great. However, on certain older systems the slider is not displayed, instead just the white background is visible. (Older IE Versions, Firefox 48.0.2)

**Describe the solution you'd like**
I’d like to make sure that everybody sees my site in a decent version. So is there a possibility to fix this or, as an alternative, detect older browser versions that are incompatibile to the slider and show a still image instead? I already inserted an “update browser” plugin to remind visitor to update their browsers.

**Additional context**
Here is my pastebin link: https://pastebin.com/1VP7u69m

The page I need help with: https://www.flostanek.at

**Comment by shilo-ey** [comment]
Hey @flos1988 

In the page you attached I can see that you are using Smart Slider, which is an external plugin.


Consider using Elementor integrated Background slideshow to see if it resolves your issue.

As for compatibility - in order to advance sometimes we need to drop support for old browsers, as we do with IE below v11 in some of our widgets.

Thanks

**Comment by flos1988** [comment]
Hey, thanks for the fast response! 

I am using Smart Slider, but only for a certain element (signature) in front of the Elementor background slideshow to achieve an "overlapping fades" effect. In the old browsers, Smart Slider works, the background slideshow doesn't. 

I see that you have to move on, but this is a real problem for me, because I already got feedback from multiple users that my front page just appears "blank". Is there not a way to make the background slider visible to everyone? 

I already included an "update browser" plugin to remind users to update to a newer browser version, but that doesn't really solve the problem.
