### ISSUE TITLE
New lightbox shows image title instead of caption

### ISSUE THREAD

**Issue by innoforce-dev** [elementor/elementor#11039]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The new lightbox shows the image title by default. There is no option to use the "caption" or "description" instead. As the title field is automatically filled with the file name this is not a good choice. 

This issue is not a duplicate of #2748 or #2502 (both from 2017) as it is about the new lightbox.

**Describe the solution you'd like**
- Show the caption by default. 
- Add a option to choose what field or fields to be displayed (I'm sure there are use cases to even show e.g. the caption and the description)

**Describe alternatives you've considered**
N/A

**Additional context**

![image](https://user-images.githubusercontent.com/20574773/78233280-c7f80e00-74d5-11ea-9ed4-a9c65bbc22a0.png)

**Comment by lior-sh** [comment]
Hi @innoforce-dev,

Thanks for reporting. Did you *set the lightbox settings to display the caption?

* Steps: Hamburger > Global settings > Click on lightbox tab > Set the title to Caption > Click on save and refresh the page

Thanks.
