### ISSUE TITLE
Columns and Section size are not consistent

### ISSUE THREAD

**Issue by 6bears** [elementor/elementor#11030]
There is an issue since last update: I have created several sections with 3 or 4 columns each. In editor mode, the column and section size is totally fine. The problem is when I go in preview mode (from Elementor sidebar) or in real mode (the website page) the columns/sections occupy only half of the space (horizontally) which makes the view seem totally distorted! I have cleared cache and all, but the problem still occurs since more than a week

**Comment by lior-sh** [comment]
Hi @6bears,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
