### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#11033]
I need to have more details about the use of these 4 html tags :
`div` -  Defines a section in a document
`section` - Defines a section in a document
`aside` - Defines content aside from the page content
`nav` - Defines navigation links

Several things on your forum are not clear: 

1- What is the difference in use between the `div `and `section `tags ? 
2- And what exactly are the `aside `and `nav `tags used for ?

**Comment by arielk** [comment]
There is a lot of tuts about it cross the web, you can learn more here:
https://www.codementor.io/@sayantinideb/html-vs-html5-difference-between-html-html5-vxn14ly96
