### ISSUE TITLE
Multilanguage templates not working

### ISSUE THREAD

**Issue by TheBigBanik** [elementor/elementor#11048]
Hi, I discovered a few days ago a huge bug in Elementor Pro that the support team unfortunately verified to me yesterday. When using WPML to create a multilanguage website, the single and archive templates of elementor cannot be assigned to second language or more. Below, I am deploing the steps.

1. Create a single template in greek.
2. Set the conditions to (In child categories) --> TA PROIONTA
3. Create an archive template in greek.
4. Set the conditions to (Any child category of) --> TA PROIONTA
5. Tested the frontend, works great for both templates.
6. Create a single template in english (excactly as the greek one)
7. Set the conditions to (In child categories) -->OUR PRODUCTS
8. Create an archive template in english (excactly as the greek one)
9. Set the conditions to (Any child category of) --> OUR PRODUCTS
10. Tested the frontend, works great for both templates.
11. Switch to greek language on frontend, the Elementor templates are not shown. Instead, it shows the theme's layout.
12. Go back to The greek templates and set the conditions again to the right ones. 
13. Check the frontend, works great. 
14. Switch language to english, Elementor templates are not shown. Instead, it shows the theme's layout.

I have tried many other combinations. Duplicate the original template. Assign the translated template to the first language. Delete any conditions of the second language. Nothing. It looks like Elementor can not associate the templates, the categories and the conditions. This is very urgent because now we can not build multilanguage website with Elementor. It is very dissapointing.

SYSTEM INFO
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (cPanel) OpenSSL/1.1.1e mod_bwlimited/1.4
	MySQL version: MySQL Community Server (GPL) v5.6.47
	PHP Version: 7.1.33
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: https://angryparrot.gr/zoinos
	Home URL: https://angryparrot.gr/zoinos
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 2048M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36

== Active Plugins ==
	Adminimize
		Version: 1.11.6
		Author: Frank Bültge

	Advanced Custom Fields
		Version: 5.8.9
		Author: Elliot Condon

	Advanced Custom Fields Multilingual
		Version: 1.6.1
		Author: OnTheGoSystems

	Advanced Custom Fields PRO
		Version: 5.8.8
		Author: Elliot Condon

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.2
		Author: mndpsingh287

	Duplicator
		Version: 1.3.28
		Author: Snap Creek

	Ele Custom Skin
		Version: 1.4.0
		Author: Dudaster.com

	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.2
		Author: Elementor.com

	Ninja Tables
		Version: 3.5.11
		Author: WPManageNinja LLC

	Rank Math SEO
		Version: 1.0.41.2
		Author: Rank Math

	Really Simple SSL
		Version: 3.3
		Author: Rogier Lankhorst, Mark Wolters

	User Role Editor
		Version: 4.53.1
		Author: Vladimir Garagulya

	WPML CMS Nav
		Version: 1.5.2
		Author: OnTheGoSystems

	WPML Media
		Version: 2.5.5
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.3.11
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.5.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.0.8
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.9.5
		Author: OnTheGoSystems

== Elements Usage ==
	
	archive : 3
		heading : 2
		image : 1
		posts : 3
		text-editor : 1
	footer : 2
		divider : 2
		heading : 2
		image : 4
		text-editor : 14
	header : 2
		button : 2
		image : 3
		nav-menu : 1
	loop : 4
		button : 1
		heading : 2
		image : 1
		text-editor : 2
		theme-post-featured-image : 1
	page : 3
		heading : 1
		text-editor : 3
	popup : 2
		button : 1
		image : 1
		nav-menu : 1
	section : 1
	single : 3
		accordion : 4
		heading : 6
		image : 12
		posts : 2
		shortcode : 2
		text-editor : 20
		theme-post-content : 3
	wp-page : 9
		button : 1
		gallery : 2
		heading : 8
		image : 7
		text-editor : 29

== Log ==
	
PHP: showing 3 of 3PHP: 2020-03-30 13:16:18 [notice X 27][/home/angryparrot/public_html/zoinos/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-30 16:10:35 [warning X 202][/home/angryparrot/public_html/zoinos/wp-content/plugins/elementor/includes/base/controls-stack.php::1201] Illegal string offset 'url' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-01 20:59:21 [notice X 13][/home/angryparrot/public_html/zoinos/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2020-03-30 20:51:20 [error X 3][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2829\") has already been destroyed and cannot be used. 
JS: 2020-03-30 20:59:54 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view155\") has already been destroyed and cannot be used. 
JS: 2020-03-31 11:59:16 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view161\") has already been destroyed and cannot be used. 
JS: 2020-03-31 12:13:09 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view185\") has already been destroyed and cannot be used. 
JS: 2020-03-31 13:34:01 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3962\") has already been destroyed and cannot be used. 
JS: 2020-03-31 14:51:39 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2288\") has already been destroyed and cannot be used. 
JS: 2020-03-31 14:57:27 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2321\") has already been destroyed and cannot be used. 
JS: 2020-03-31 14:57:52 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4688\") has already been destroyed and cannot be used. 
JS: 2020-04-01 14:14:37 [error X 1][https://angryparrot.gr/zoinos/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view114\") has already been destroyed and cannot be used. 

Log: showing 1 of 12020-04-01 13:32:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.1',
  'to' => '2.9.2',
)]

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
