### ISSUE TITLE
malware found (Virusdie)

### ISSUE THREAD

**Issue by codeagencybe** [elementor/elementor#11046]
Hello

I started receiving notifications from Virusdie service that Elementor containers malware and needs cleaning. 
I checked the details, and it points specifically to elementor safe mode code. 

This is happening not just one website, but so far 20+ sites are reporting the same error in Virusdie. 

elementor-safe-mode.php | Not cleaned
Path: /wp-content/plugins/elementor/modules/safe-mode/mu-plugin
Not removed threats: WP.Elementor.CVE

I also fouñd more informaton on that threat here: https://wpvulndb.com/vulnerabilities/10156
The most websites that are being reported by Virusdie are actually already on the latest version for Elementor and pro, but the malware/threat from that specific code is still present in latest version it seems. 

Is this a known issue? Or something new that recently started but not yet reported? 
I would like to know how to fix and patch this security issue asap please. 

Thanks

EDIT

screenshot attached from Virusdie
![image](https://user-images.githubusercontent.com/7568546/78348385-399d8e00-75a2-11ea-83ff-4d39cca9fb73.png)

**Comment by shilo-ey** [comment]
Hi @codeagencybe 

Thanks for your input.

This is not malware but a false positive detection of Elementor's Safe Mode MU Plugin.

thanks
