### ISSUE TITLE
"Edit With Elementor" Admin Bar Missing Templates

### ISSUE THREAD

**Issue by dudaster** [elementor/elementor#11040]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

It is nice that you can select from the top Admin Bar under the Edith With Elementor all the elementor templates that are used in that specific page, but not anymore.
For example I added an template widget and it is shown in the front page but in the Admin Bar is not shown under "Edit with Elementor" or anywhere for that matter.
## Steps to reproduce
The issue appears especially with Hello Elementor Theme.
1. Create a Page Elementor Template
2. Insert it in a page with a Template Widget
3. View that page
4. Observe the missing template form under "Edit With Elementor"

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
							
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.29
	PHP Version: 7.2.29
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: https://clean.ehot.ro
	Home URL: https://clean.ehot.ro
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.2
		Author: Elementor.com


== Elements Usage ==
	
	footer : 1
		divider : 1
		form : 1
		heading : 2
		icon-list : 1
		image : 1
	header : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	page : 1
		countdown : 1
		heading : 4
		spacer : 1
		text-editor : 3
	popup : 1
		button : 1
		heading : 2
		image : 1
		spacer : 1
	wp-page : 1
		posts : 1
		template : 1
		text-editor : 1


== Log ==
								
```
</details>

**Comment by shilo-ey** [comment]
Hi @dudaster 

Thanks for your feedback.

We are familiar with the issue you are raising.
In WordPress 5.4, they changed the way the wp-admin bar works (now it's printed while the `body` tag opens and not later as prior versions act) in such a way that we can now display there editing links only for templates that we know that needs to be loaded in each screen.

We know which template load based on the Theme Builder conditions, and that's how we add them to the wp-admin bar in this early stage of the page load.

Therefore, we can no longer know if you added templates generated from Shortcodes or using Template widget to your pages.

Thanks again!

**Comment by dudaster** [comment]
This issue is not surfacing when using Twenty Seventeen Theme. So it works ok with that theme but not with Hello Theme.

**Comment by shilo-ey** [comment]
Thanks, we will investigate this issue and update you again.

**Comment by shilo-ey** [comment]
Hi @dudaster 

After some clarifications, I got an explanation for this issue you raised:
In accordance with my latest explanation, in order to provide backward compatibility with other WP themes and core versions, Elementor moves the wp-admin bar to the footer and in this way overcomes this issue.

In new versions and 5.4 compatible ones, we use the native mechanism WordPress provides, and therefore can't locate the Templates originated from Template widget or Shortcode.

I hope that provides a proper explanation.

Thanks

**Comment by dudaster** [comment]
What I understood from your reply is that Twenty Seventeen Theme is an old one and that’s why it works, but Hello Elementor Theme complies with wp 5.4 and from now on this feature will be unavailable.

**Comment by jawhalen8463** [comment]
Can we assume that you opened a ticket with WordPress on this? This is adversely affecting my productivity (and I assume many others.)

**Comment by grrog** [comment]
I really miss this feature. I used it a lot when there are a lot of templates on a page.
This issue happens due to a change in WordPress, as you can see [here](https://core.trac.wordpress.org/ticket/47053#comment:44).

For now, you can fix the problem by adding the WordPress Admin Bar back to the wp_footer hook, instead of the new wp_body_open one.

You can do that by adding the following line of PHP to your theme’s functions.php file:
`remove_action( 'wp_body_open', 'wp_admin_bar_render', 0 );`

**Comment by lastjedi89** [comment]
> I really miss this feature. I used it a lot when there are a lot of templates on a page.
> This issue happens due to a change in WordPress, as you can see [here](https://core.trac.wordpress.org/ticket/47053#comment:44).
> 
> For now, you can fix the problem by adding the WordPress Admin Bar back to the wp_footer hook, instead of the new wp_body_open one.
> 
> You can do that by adding the following line of PHP to your theme’s functions.php file:
> `remove_action( 'wp_body_open', 'wp_admin_bar_render', 0 );`

hey! this worked fine! I use hello elementor theme and going to a built template to edit took long time. 
Thank You!

**Comment by danielkv** [comment]
> I really miss this feature. I used it a lot when there are a lot of templates on a page.
> This issue happens due to a change in WordPress, as you can see [here](https://core.trac.wordpress.org/ticket/47053#comment:44).
> 
> For now, you can fix the problem by adding the WordPress Admin Bar back to the wp_footer hook, instead of the new wp_body_open one.
> 
> You can do that by adding the following line of PHP to your theme’s functions.php file:
> `remove_action( 'wp_body_open', 'wp_admin_bar_render', 0 );`

Worked fine for me

**Comment by DODMax** [comment]
Maybe populate that menu after page load via AJAX query? Of course it should only work for logged-in editors or above.
