### ISSUE TITLE
Custom google font family not loading in Elementor Pro Template widget preview

### ISSUE THREAD

**Issue by evgeniyshay** [elementor/elementor#11047]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Pro Template widget not loading custom google font family, there is no link tag for the desired fonts.

## Steps to reproduce

1. add section template document
    - add heading widget
    - open typography and set custom google font family in this heading widget style tab
    - save template
2. add page template document
    - add Elementor Pro Template widget
    - in Choose Template control select section from step 1
3. in preview you will see that custom google font family not load, but if you go to the frontend google font in this widget loads correctly.
[2020-04-03_1230.zip](https://github.com/elementor/elementor/files/4426532/2020-04-03_1230.zip)
[system-info-localhost-03-04-2020.txt](https://github.com/elementor/elementor/files/4426548/system-info-localhost-03-04-2020.txt)
[system-info-localhost-03-04-2020.txt](https://github.com/elementor/elementor/files/4426550/system-info-localhost-03-04-2020.txt)

There is a reproducing video
https://www.screencast.com/t/WjAH8NZcz0Pv

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: WINNT
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.13
	PHP Version: 7.0.8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1536M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.9
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.2
		Author: Elementor.com

	Video Embed & Thumbnail Generator
		Version: 4.6.25
		Author: Kyle Gilman

	Windows Compatibility Fix
		Version: 1.0.2
		Author: Dave Jesch

	WooCommerce
		Version: 4.0.1
		Author: Automattic

== Elements Usage ==
	
	archive : 3
		archive-posts : 1
		author-box : 1
		image : 1
		theme-page-title : 1
	footer : 2
		heading : 2
		nav-menu : 1
		social-icons : 1
	header : 3
		button : 1
		image : 1
		nav-menu : 1
	page : 3
		gallery : 1
		heading : 5
		image : 1
		portfolio : 1
		posts : 1
		sitemap : 1
		template : 1
		text-editor : 4
		woocommerce-products : 1
	popup : 2
		heading : 1
		image : 1
	product : 3
		facebook-page : 1
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 1
		woocommerce-product-additional-information : 1
		woocommerce-product-content : 1
		woocommerce-product-data-tabs : 2
		woocommerce-product-images : 2
		woocommerce-product-meta : 1
		woocommerce-product-price : 2
		woocommerce-product-rating : 2
		woocommerce-product-related : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 2
	section : 5
		button : 2
		flip-box : 1
		heading : 7
		image : 2
		text-editor : 3
	single : 11
		button : 1
		facebook-comments : 1
		heading : 4
		image : 2
		post-comments : 1
		post-info : 2
		posts : 2
		sidebar : 1
		tabs : 1
		template : 1
		text-editor : 3
		theme-post-content : 3
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 6
	wp-post : 2
		image : 1
		share-buttons : 1
		template : 1
		text-editor : 2
	wp-page : 4
		button : 1
		heading : 7
		image : 1
		text-editor : 4
		woocommerce-breadcrumb : 1
	product-archive : 3
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-archive-description : 2
		woocommerce-archive-products : 1

== Log ==

```
[2020-04-03_1230.zip](https://github.com/elementor/elementor/files/4426281/2020-04-03_1230.zip)

</details>

**Comment by lior-sh** [comment]
Hi @evgeniyshay,

Thanks for reporting, we couldn't reproduce the issue.
Can you please add more info like a recorded by a video of the steps to reproduce until you got the issue? 
Thanks.

**Comment by evgeniyshay** [comment]
Ok
There is a reproducing video
https://www.screencast.com/t/WjAH8NZcz0Pv
[2020-04-03_1230.zip](https://github.com/elementor/elementor/files/4437665/2020-04-03_1230.zip)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
