### ISSUE TITLE
Sitemap Widget supports taxonomy exclusion and column support?

### ISSUE THREAD

**Issue by 1101blueli** [elementor/elementor#11042]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I have been looking for a way to create a taxonomy mega menu. with sitemap widget + custom css I can do it easier, except there are some terms I don't want to show. And I don't want to install another 3rd party add-on particular for this matter if elementor could have this option for users. Better with a column option since someone could have more than 20+ terms.

thanks

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
