### ISSUE TITLE
Media Carousel (SwiperJS) slidesPerView not honored

### ISSUE THREAD

**Issue by xmycroftx** [elementor/elementor#11043]
The Media Carousel slidesPerView variable does not get honored if you are not hitting a mobile screen width (767px.)  No matter the setting if the viewable width is larger than the minimum 767 it will only show 2 elements.  Switching the same view to a mobile screen width will show the proper number of slides.

**Comment by lior-sh** [comment]
Hן @xmycroftxת

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by xmycroftx** [comment]
Prequisite: media carousel be on your page
Steps to replicate: have more than 2 slides and a screen width larger than 767 pixels.
isolating the problem: There are mobile cases in the elementor javascript that show different views based on your screen width (ctrl+f 767) 
System info: erm? wut?

**Comment by xmycroftx** [comment]
this is fixed in the latest branch, but I wasn't able to find the fix in any issues.
