### ISSUE TITLE
Lightbox gallery is not filtered

### ISSUE THREAD

**Issue by Moleskinet** [elementor/elementor#11041]
I expect that the lightbox to display only the images that I have on the Filter tab.

For example, if you have 5 birds in a tab and I just want the lightbox to keep displaying those 5 birds instead moving to the other filter tab images

**Comment by lior-sh** [comment]
Hi @Moleskinet,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
