### ISSUE TITLE
Problem with widget text editor

### ISSUE THREAD

**Issue by JulioEISO** [elementor/elementor#11052]
Hi i'm julio césar.

I'm using elementor free on my site with aws. After I migrated my site i've troubles with widget text editor. I follow instructions of this site, https://docs.elementor.com/article/467-site-migration, and the problem is still here. I need some help to resolve this, Thanks a lot for your help.

**Comment by lior-sh** [comment]
Hi @JulioEISO,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
