### ISSUE TITLE
Dynamic URL returning wrong parameters

### ISSUE THREAD

**Issue by CharfishCharlie** [elementor/elementor#11053]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

I am using the Icon List widget to put some links in the footer of a client site. One of the icon list items will link to: example.com/category/case-studies.

To do this I am trying to use the Dynamic Internal URL: Link > Settings > Taxonomy > Categories: Case Study.

When I save the page everything seems fine, but the dynamic URL that is generated comes out as follows:

example.com/?taxonomy=elementor_library_type&term=section

## Steps to reproduce

1. Use Icon List Widget
2. Create item and enter test.
3. For Link, choose Dynamic Tags
4. Choose Site > Internal URL
5. For Settings, choose Taxonomy for the Type
6. In Search & Select, Choose a category
7. Hit Update
8. Refresh and check the link

## Isolating the problem
- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment
<summary>System Info</summary>

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.6.44 |  
PHP Version: | 5.6.40 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 32M |  
GD Installed: | Yes |  
ZIP Installed: | No |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by ZENwww** [comment]
I have the same problem with the latest version of Elementor. Do you fix it? @CharfishCharlie

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by SuperStompie** [comment]
I have the same problem!
