### ISSUE TITLE
Delete popup from many pages and show popup on just a few pages

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#11060]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hello people,

When we want to include the display of a popup for most pages, the process is easy. Just select EXCLUDE and choose the few pages that should not appear in the popup.

However, when we want the opposite, that is, we want to delete the pop-up on most pages and show the popup on just a few pages, the process is very difficult, as I have to select EXCLUDE for most pages.

If I create an EXCLUDE condition for all pages and then I create INCLUDE on some pages that I want to appear in the popup [(https://prnt.sc/rlxaca)](https://prnt.sc/rlxaca) it didn't work. Those few pages that I selected INCLUDE, the popup did not appear because I had selected EXCLUDE for all pages.

For example, if I have 50 pages and I want a popup to appear in just 5 pages, how do I set up the conditions?
Currently, the only way is for me to create INCLUDE on all pages, and then include EXCLUDE on the 45 pages that should not appear in the popup. However, this is very laborious.

I checked with Elementor's support and Luis confirmed that there is really no way to delete the popup from most pages and include it in just a few pages, without doing the process of deleting the popup pages per page. [https://www.loom.com/share/dd1e57266f6d475b8e46d0e1aa949205](https://www.loom.com/share/dd1e57266f6d475b8e46d0e1aa949205)

So, I leave it as a suggestion for you to solve this in a next update.

Thank you,
Rodrigo Carlos

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
