### ISSUE TITLE
add parameters to swiper.js instance after init

### ISSUE THREAD

**Issue by anybany** [elementor/elementor#11067]
Hi, your ticket system on my.elementor.com is giving me a 403 on submit so i thought i write you here ;)

I just discovered your article on "How to Access a Swiper Instance".

I am trying to add the following swiper.js parameters to a "slides" widget:
slidesPerView: 'auto'
freeMode: true
freeModeSticky: false
mousewheel: true

so basically i want to disable/override that the slides snap to the edges and that the slider is scrollable horizontal by mousewheel.

I added this code to html-widget:
<script>
jQuery(document).ready(function( $ ){
  const imageCarousel = jQuery ( '.freeSwiper .swiper-container' );
  swiperInstance = imageCarousel.data( 'swiper', {
    slidesPerView: 'auto',
    freeMode: true,
    freeModeSticky: false,
    mousewheel: true,
  });
});
</script>

But it doesn't work...

Could you please tell me how to fix my code?
You can see the code here: https://rooja.jkjkjk.de/freeswiper/

Please let me know if you need any further information.
I can also send you my purchase code in private!
Jan

**Comment by udidol** [comment]
Hi @anybany ,
If you want to pass new parameters and refresh the Swiper instance, you would need to modify your code to be as follows:
```
<script>
jQuery( document ).ready( function() {
   const imageCarousel = jQuery ( '.freeSwiper .swiper-container' ),
      swiperInstance = imageCarousel.data( 'swiper' );

   swiperInstance.params.slidesPerView = 'auto';
   swiperInstance.params.freeMode = true;
   swiperInstance.params.freeModeSticky = false;
   swiperInstance.params.mousewheel = true;

   swiperInstance.update();
}); 
</script>
```

**Comment by anybany** [comment]
thanks for your modification.
unfortunately i get an error now: _Uncaught TypeError: Cannot read property 'params' of undefined_

i got the _const imageCarousel_ from the Elementor Docs. Maybe it has to be something else because i am using the "normal" slider widget? but otherwise it does something, because i can't use the slider anymore...

**Comment by udidol** [comment]
What do you mean by the "normal" slider widget?
`imageCarousel` is just a variable name, it doesn't matter. Try loading the page, opening your browser console, and pasting just this part of the code:
````
const imageCarousel = jQuery ( '.freeSwiper .swiper-container' ),
      swiperInstance = imageCarousel.data( 'swiper' );
```
Then enter `imageCarousel` into the console and hit the `Enter` key.
After that, also enter `swiperInstance` into the console and hit the `Enter` key.
Paste here what you get.

**Comment by anybany** [comment]
`const imageCarousel = jQuery ( '.freeSwiper .swiper-container' ),
      swiperInstance = imageCarousel.data( 'swiper' );` show `undefined`

the `imageCarousel` shows the following
`n.fn.init [div.elementor-slides-wrapper.elementor-main-swiper.swiper-container, prevObject: n.fn.init(1), context: document, selector: ".freeSwiper .swiper-container"]0: div.elementor-slides-wrapper.elementor-main-swiper.swiper-containercontext: documentlength: 1prevObject: n.fn.init [document, context: document]selector: ".freeSwiper .swiper-container"__proto__: Object(0)
`

and `swiperInstance` shows `undefined`

**Comment by yukino031902** [comment]
I was just having this same issue, I had to use a function that waits for elementor and pro to load that I've used previously with a different widget, hopefully this helps you as well:

```
jQuery(document).ready(function ($) {
    
    $(window).on('elementor/frontend/init', function () {
        // wait for elementor pro to load
        elementorFrontend.on('components:init', function () {

            const imageCarousel = jQuery('#featured-thumbs .swiper-container'),
            swiperInstance = imageCarousel.data('swiper');

            swiperInstance.params.direction = 'vertical';
            swiperInstance.params.slidesPerView = 3;

            swiperInstance.update();
            
        });
    });
    
});
```

**Comment by anybany** [comment]
thanks @yukino031902  you got me one step further!
for example _swiperInstance.params.slidesPerView = 3;_ works great.

but all my other settings like freeMode and mouswheel won't work.
the slider still snaps very ugly to the edges.

if you would like to have a look: [https://rooja.jkjkjk.de/freeswiper/](https://rooja.jkjkjk.de/freeswiper/)

**Comment by udidol** [comment]
If you are running these commands in the editor (and not the Front End), make sure that your console's scope is defined as the preview iFrame (`elementor-preview-iframe`), and not `top` when you run those commands:


![image](https://user-images.githubusercontent.com/36724484/79309950-cb42bf00-7f03-11ea-86b2-c4b11f8cd87e.png)

Let me know if this solves your issue.

**Comment by anybany** [comment]
i've got it all working now.
i had to destroy the original swiper instance and init a new one because i couldn't get mousewheel navigation to work.

now i would like to have all .swiper-slide elements (and probably also all .swiper-slide-inner elements) to be as width as its content. i bet it's just some easy css tweak but i can't figure out how.

can someone please help me on that?


this is the code i am using on [https://rooja.jkjkjk.de/freeswiper/](https://rooja.jkjkjk.de/freeswiper/)
please have a look there because you can see the html and css setup from elementor there.

<pre>
<script>
jQuery(document).ready(function ($) {
    
    $(window).on('elementor/frontend/init', function () {
        // wait for elementor pro to load
        elementorFrontend.on('components:init', function () {
            
            // destroy original swiper
            const oldSwiper = jQuery('.freeSwiper .swiper-container'),
            swiperInstance = oldSwiper.data('swiper');
            swiperInstance.destroy (true, true);

            // init original swiper
            var mySwiper = new Swiper('.freeSwiper .swiper-container', {
                slidesPerView: 'auto',
                updateOnWindowResize: true,
                freeMode: true,
                freeModeSticky: false,
                freeModeMomentum: true,
                freeModeMomentumRatio: 0.7,
                freeModeMomentumVelocityRatio: 0.7,
                freeModeMomentumBounce: true,
                mousewheel: true,
                releaseOnEdges: true,
                simulateTouch: true,
                grabCursor: true,
                cssMode: false,
                keyboard: true,
                navigation: {
                    nextEl: '.elementor-swiper-button-next',
                    prevEl: '.elementor-swiper-button-prev',
                },
                pagination: {
                    el: '.swiper-pagination',
                    type: 'bullets',
                },
            });
        });
    });
});
</script>
</pre>

and here is a working fiddle as it should be: [https://codepen.io/jank/pen/rJGeGL](https://codepen.io/jank/pen/rJGeGL)

**Comment by Jonatan-r** [comment]
For anyone struggling to get it to work fundamentally:

```js
<script>
jQuery(document).ready(function($) {
            $(window).on('load', function () {
                    const swiper_target = jQuery ( '#myslider .swiper-container' );
                    const swiperInstance = swiper_target.data('swiper');
                                swiperInstance.slideTo(2);
            });
});

**Comment by qwik3r** [comment]
> For anyone struggling to get it to work fundamentally:
> 
> ```js
> <script>
> jQuery(document).ready(function($) {
>             $(window).on('load', function () {
>                     const swiper_target = jQuery ( '#myslider .swiper-container' );
>                     const swiperInstance = swiper_target.data('swiper');
>                                 swiperInstance.slideTo(2);
>             });
> });
> ```

Funny, after all that, your solution is the only thing that worked lol. Do you mind assisting a bit further? How would you structure it to add additional parameters such as  .slidesPerView: '1', etc?

**Comment by troytoon** [comment]
Its March 2023 and Elementor v3.1 is using Swiper V8. 
.swiper-container class seems to be deprecated. changing it to .swiper works for me
[https://v8.swiperjs.com/swiper-api]

<script>
jQuery(document).ready(function($) {
            $(window).on('load', function () {
                    const swiper_target = jQuery ( '#myslider .swiper' );
                    const swiperInstance = swiper_target.data('swiper');
                                swiperInstance.slideTo(2);
            });
});

**Comment by rafiul** [comment]
Hi, I added the below codes in my WordPress footer it's working fine on load but after the first slide, the instance not working. Where I missed? 

```
jQuery(document).ready(function($) {
	$(window).on('load', function() {
			const swiper = new Swiper('.swiper', {
				centeredSlides: true,
				spaceBetween:20,
				slidesPerView:2,
				loop: true,
			});
	});	
}); 
```

**Comment by borodin-dev** [comment]
> For anyone struggling to get it to work fundamentally:
> 
> ```js
> <script>
> jQuery(document).ready(function($) {
>             $(window).on('load', function () {
>                     const swiper_target = jQuery ( '#myslider .swiper-container' );
>                     const swiperInstance = swiper_target.data('swiper');
>                                 swiperInstance.slideTo(2);
>             });
> });
> ```

it's January 2024, and Elementor v3.18.3 is using Swiper v8.4.5, after all the solutions here, your solution is the only thing that worked for me. thanks.

**Comment by Anymfah** [comment]
Here is a pure JS method that will work 100% : 

```javascript
(() => {
    // Array to store the found swipers
    const foundSwipers = [];
    /**
     * Observe the container for the swiper to be loaded
     * @param container - The container to observe for the swiper
     * @param cb - The callback to call when the swiper is loaded
     */
    const obsFn = (container, cb = null) => {
        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                if (mutation.type === 'childList'
                    && mutation.target.classList.contains('swiper')
                    && !!mutation.target.swiper && !foundSwipers.includes(mutation.target.swiper)) {
                    foundSwipers.push(mutation.target.swiper);

                    // If you wana hook to an event (else remove this line)
                    document.dispatchEvent(new CustomEvent('swiper:loaded', { detail: mutation.target.swiper }));

                    // Call the callback
                    if (cb)
                    cb(mutation.target.swiper);
                }
            });
        });

        observer.observe(container, {
            childList: true,
            subtree: true,
        });
    }

    // If you wana hook to an event
    document.addEventListener('swiper:loaded', (e) => {
        console.log('Swiper loaded event:', e.detail);
    });

    // Run the observer
    document.querySelectorAll('[data-element_type="container"]').forEach((container) => {
        obsFn(container, (swiper) => {
            console.log('Swiper loaded:', swiper);
        });
    });
})();
```

**Comment by juxido** [comment]
@Anymfah This works well for me. Could you please share how do I get the slideIndex on slideChange event?

**Comment by gewaechshaus** [comment]
@Anymfah 

`          // Run the observer
            document.querySelectorAll('[data-element_type="container"]').forEach((container) => {
                obsFn(container, (swiper) => {
                    //console.log('Swiper loaded:');
                    //console.log(swiper);
                    swiper.allowTouchMove = false;
                    swiper.allowClick = true;
                    swiper.params.preventClicks = false;
                    swiper.params.preventClicksPropagation = false;
                    swiper.update();
                });
            });`

**Comment by nordkite** [comment]
I managed to do it like this
```
jQuery(document).ready(function($){
	setTimeout(function(){
		swiperInstance = jQuery("#mySwiper .swiper").data("swiper");
		if (swiperInstance) {
			swiperInstance.destroy(true)

			new Swiper("#mySwiper .swiper", {
				slidesPerView: 3,
				spaceBetween: 20,
				direction: "vertical",
				pagination: false,
				navigation: {
					nextEl: ".elementor-swiper-button-next",
					prevEl: ".elementor-swiper-button-prev",
				},
			})
		}
	}, 200)
})
```

**Comment by nordkite** [comment]
I managed to it this way
```
jQuery(window).on('elementor/frontend/init', function() {
  elementorFrontend.hooks.addAction('frontend/element_ready/nested-carousel.default', function(scope) {
	setTimeout(function(){
		swiperInstance = jQuery("#mySwiper .swiper").data("swiper");
		if (swiperInstance) {
			swiperInstance.destroy(true)
			new Swiper("#mySwiper .swiper", {
				slidesPerView: 3,
				spaceBetween: 20,
				direction: "vertical",
				pagination: false,
				navigation: {
					nextEl: ".elementor-swiper-button-next",
					prevEl: ".elementor-swiper-button-prev",
				},
			})
		}
	}, 200)
  });
});
```

**Comment by nordkite** [comment]
Managed to do it this way. This makes the preview in the editor to show the changes in Swiper
Based on https://medium.com/@miga_/accessing-swiper-in-elementor-extending-the-image-carousel-widget-5d641ddc5972
```
if (document.readyState !== 'loading') {
	domReady();
} else {
    document.addEventListener('DOMContentLoaded', domReady);
}

jQuery(window).on('elementor/frontend/init', function() {
  elementorFrontend.hooks.addAction('frontend/element_ready/nested-carousel.default', function(scope) {
      domReady();
  });
});

function domReady() {
	setTimeout(function() {
		swiperInstance = jQuery("#mySwiper .swiper").data("swiper");
		if (swiperInstance) {
			swiperInstance.destroy(true)
			new Swiper("#mySwiper .swiper", {
				slidesPerView: 3,
				spaceBetween: 20,
				direction: "vertical",
				pagination: false,
				navigation: {
					nextEl: ".elementor-swiper-button-next",
					prevEl: ".elementor-swiper-button-prev",
				},
			})
		}
	}, 500)
}
```

**Comment by nordkite** [comment]
@mbaierl yes, I agree. I am also curios why Elementor team doesn't improve highly requested features and it is not only this one, there are many others.
I use Bricks and there you can pass custom json parameters to their built-in slider widget and it works out of the box. It uses different library but I am sure the same can be done with Elementor + Swiper JS.

**Comment by sun** [comment]
Created a PR to at least improve the docs on this: https://github.com/elementor/elementor-developers-docs/pull/323

**Comment by rloes** [comment]
Because Elementor still not fire an event for swiper and I didnt want to rely on setTimeout, I used MutationObserver:

```javascript
(function($){
  /**
   * Waits for the Swiper instance to initialize by
   * watching for the `swiper-initialized` class.
   *
   * @param {string} wrapperId – the ID of your Elementor widget wrapper
   * @param {Function} cb – receives the ready Swiper instance
   */
  function onSwiperReady(wrapperId, cb) {
    const wrapper = document.getElementById(wrapperId);
    if (!wrapper) return;
    const swiperEl = wrapper.querySelector('.swiper');
    if (!swiperEl) return;

    // 1) Already initialized?
    if (swiperEl.classList.contains('swiper-initialized')) {
      return cb(swiperEl.swiper);
    }

    // 2) Observe for class changes
    const mo = new MutationObserver((records, obs) => {
      for (let r of records) {
        if (
          r.attributeName === 'class' &&
          swiperEl.classList.contains('swiper-initialized')
        ) {
          obs.disconnect();
          return cb(swiperEl.swiper);
        }
      }
    });
    mo.observe(swiperEl, { attributes: true });
  }

  /**
   * Overrides slidesPerView on all breakpoints
   */
  function setSlidesPerViewAuto(wrapperId) {
    const wrapper = document.getElementById(wrapperId);
    if (!wrapper) return;
    const swiperEl = wrapper.querySelector('.swiper');
    if (!swiperEl || !swiperEl.swiper) return;
    const swiper = swiperEl.swiper;

    swiper.params.slidesPerView = 'auto';
    if (swiper.params.breakpoints) {
      Object.values(swiper.params.breakpoints).forEach(bp => {
        bp.slidesPerView = 'auto';
      });
    }
    swiper.update();
  }

  // Hook into Elementor’s init
  $(window).on('elementor/frontend/init', () => {
    elementorFrontend.hooks.addAction(
      'frontend/element_ready/nested-carousel.default',
      (scope) => {
        // Now wait for Swiper to be fully initialized
        onSwiperReady('ws-area-swiper', () => {
          setSlidesPerViewAuto('ws-area-swiper');
        });
      }
    );
  });
})(jQuery);
```
