### ISSUE TITLE
Animated Headline A Tag not closed properly

### ISSUE THREAD

**Issue by andcha** [elementor/elementor#11076]
Hi

Adding animated headline results in incomplete A tag like this

> <a href="https://some.link" target="_blank" <span="" class="elementor-headline elementor-headline-animation-type-swirl elementor-headline-letters">

Note the missing closing tag **">"**. Also, custom attributes are being truncated due to this.

Normal headlines are working absolutely fine with links.

I am on Elementor 2.9.6, Elementor Pro 2.7.3.

Thanks

**Comment by color-space** [comment]
Hey there, was this originally a "mailto:" link by any chance?

**Comment by andcha** [comment]
No no, a usual hyperlink.
Are you facing similar issues with animated headline?

**Comment by color-space** [comment]
no but i know that if you have mail encryption plugin to protect mailadresses from bots, it can sometimes add  `<span=""` into the link tag if the mail adress is included in the url of the link.

**Comment by arielk** [comment]
Please update to Elementor Pro v2.8.5

Thanks
