### ISSUE TITLE
better carousel / slider.

### ISSUE THREAD

**Issue by folusuk** [elementor/elementor#11071]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am frustrated by the inability to create more complex sliders without using a 3rd party pluging.

**Describe the solution you'd like**
One option to add is from "Plus Widgets - Carousel Anything"

**Describe alternatives you've considered**
found at this URL

**Additional context**
Make your carousels with all stunning options and with the power of templates of elementor. You can use any elementor widgets with various carousal options in this elementor widget.
Powerful carousel Options
Center Mode with Unique Settings
Unlimited Possibilities
Based on “Design the way you want” Philosophy

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/219 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Carousel was released with Elementor Pro v3.14.0! 🥳 

You can now create Carousels or Slides with custom nested widgets without needing to use shortcodes or other features! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
