### ISSUE TITLE
[BUG] Search Form Widget: Global Theme Style overrides background / border color of input element

### ISSUE THREAD

**Issue by princesshorsepower** [elementor/elementor#11072]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Theme Style overrides the background / border color if the Input element in the Search Form Widget
Also the margin of the input element to the Search icons seems to be messed up
(see attached screenshot)

## Steps to reproduce

Set style for Input elements in global Elementor Theme Style 
Happens in a Popup Template and on a page
Input Element in Form Widget shows Background and Border Color of Theme Style

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Current Fix is to use custom CSS for the Search Form

.elementor-search-form__input {
    background-color: #1F1A24 !important;
    border-color: #1F1A24 !important;
    margin-left: 10px !important;
}

<img width="616" alt="search-form" src="https://user-images.githubusercontent.com/52812059/78628041-9c09cd80-78c5-11ea-949e-e79d131dae19.png">

**Comment by princesshorsepower** [comment]
<img width="259" alt="search-form-page" src="https://user-images.githubusercontent.com/52812059/78867799-4fb0c000-7a74-11ea-8102-4330870d5eaf.png">

**Comment by lior-sh** [comment]
Hi @princesshorsepower,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Clear steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
