### ISSUE TITLE
Ability to Choose Admin Dashboard & Installed Plugin Languages

### ISSUE THREAD

**Issue by thechiefalone** [elementor/elementor#11082]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As you all know, the Elementor community growing more and the community behind it marvelous. Also, WordPress development is very international and we have clients from different countries and languages. For me, it is important to make the admin dashboard language in English to understand what is going on. There are some plugins for that but it would be really great if there would be an option for Elementor, to change only the admin dashboard, and plugins language but the website will be preferred language.

**Describe the solution you'd like**
Elementor settings should give 2 options for Language. One for site language and one for admin language. Admin language should affect all installed themes, plugins language just only for the backend. 

**Describe alternatives you've considered**
I have found a plugin works pretty fine for that purposes but it would be better to see this option on Elementor settings. 

https://wordpress.org/plugins/english-wp-admin/

**Comment by agcreateit** [comment]
This would be a great integrated solution!

**Comment by Bovelett** [comment]
A BIG FAT +1 from me! ❤️

**Comment by arielk** [comment]
Merge to: https://github.com/elementor/elementor/issues/5148
