### ISSUE TITLE
Not able to use two slider on one page

### ISSUE THREAD

**Issue by MichalJankowskii** [elementor/elementor#11087]
When ai am creating two sliders:
![2020-04-08_20-59-28](https://user-images.githubusercontent.com/10032671/78825875-efbd0980-79e0-11ea-92ac-8807a2d39b3b.png)
The second one is not working and it is controlling the first one.

**Comment by lior-sh** [comment]
Hi @MichalJankowskii,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
