### ISSUE TITLE
File upload link missing domain, only includes /wp-content/uploads/elementor/forms/FILENAME.docx

### ISSUE THREAD

**Issue by mclever** [elementor/elementor#11098]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When a file is uplaoded via a form, the link that gets written to the DB doesnt include the domain of the site.

## Steps to reproduce

Submit a form with an attachement and notice the file link doesnt include the domain, just /wp-content/uploads/elementor/forms/FILENAME.docx

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
