### ISSUE TITLE
Using swatches like Adobe Illustrator :)

### ISSUE THREAD

**Issue by bobmulder** [elementor/elementor#11108]
Hi there!

It is awesome to be able to save colors to the color palet. However, when I want to change a general color used on my site I still need to replace it on several places.

You will probably know the concept of swatches in Adobe Illustrator. You can define swatches, which are collections of colors. When you color something, you select an item from the swatch. On a specific section you can change that item in the swatch and boooooom.... The whole project changes into that color :)

What do you think about this feature?

**Comment by donwattz1459** [comment]
You could do this with ACF and dynamic tag for colors now. Make an options page, add your colors (as many as you want) in that color picker in ACF, then dynamically pull them into the site builder.

**Comment by bobmulder** [comment]
Whats a pretty nice option @donwattz1459! Haven't thought about that yet...

But my proposal is still valid for the colorpicker-tool used in Elementor :)

**Comment by black-eye** [comment]
Very similar issue (I would say the same one) here: https://github.com/elementor/elementor/issues/11123.
And it's actually on the roadmap! 👍

**Comment by bobmulder** [comment]
You're completely right @black-eye, that's a duplicate ;) Glad to hear it's on the roadmap!

**Comment by black-eye** [comment]
@bobmulder Just to make it clear, I'm not a member of Elementor team. ;) So I have no other info than the milestone here: https://github.com/elementor/elementor/milestone/57

Concerning the roadmap - there is none. And according to several Elementor reps answers, there won't be any. Ever. ;-)
