### ISSUE TITLE
Elementor document main section element/class inconsistency

### ISSUE THREAD

**Issue by ServerDestroyer** [elementor/elementor#11107]
I've noticed something really strange. Not sure whether this is on purpose and if true it's kinda silly... OK, this is how any Elementor page is structured (roughly, of course):

    <body class="...">
       <div class="elementor-location-header..."><div>
       <main class="site-main..."></main>
      </div class="elementor-location-footer..."></div>
    </body>

However, if you create Single or Archive template for the custom post type, the structure changes to:

    <body class="...">
        <div class="elementor-location-header..."><div>
        <div class="elementor-location-single..."></div>
        </div class="elementor-location-footer..."></div>
    </body>
So, if for some reason one is up to style the main section of the site, it won't work across all Elementor templates. For instance...

    main.site-main {
        /* main section styles */
    }
Hope it makes sense!

I am talking about Single or Archive template created with Elementor. So, there's no chance it's coming from the theme.
I'm using Hello Elementor theme.
Others are having the issue as well on different installations so it not just me or the WP setup.

**Comment by oooh-boi** [comment]
I wish you a good luck with this one mate!!!

**Comment by arielk** [comment]
Starting Elementor Pro v2.9 you can select the HTML tag for each document in Elementor.

See more here: https://elementor.com/blog/introducing-full-site-editing/

Thanks
