### ISSUE TITLE
Setup display conditions in theme builder for CPT in taxonomy(category) not saved

### ISSUE THREAD

**Issue by navarroido** [elementor/elementor#11105]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I have post type "Tools" to which taxonomy(category) attached which is already attached with default WordPress post type (post).

so the issue is when I create an archive page for my custom CPT (tools) and try to setup display conditions for archive page, I can select custom CPT archive in condition area like (tools archive) like use this template when it's my custom cpt archive page alright but when i select a category from tools archive list as a condition like fetch posts from post (tools) categories and click and save & close button in the page display option its auto select category from (post archive) and the category i selected from the tools archive list is removed from selection, so as a result its fetch posts from WordPress default post type(post) instead of my custom post type, in simple word i want to use my archive page for my custom post (tools) and fetch posts from category attached to my custom post(tools) post-selection is okay but category section creating issue, why that category selection removed and it's auto select default wordpress category 

## Steps to reproduce

before start:
make sure you have custom post type execpt 'posts'

1. open new page in builder
2. save and click button 'add condition'
3. select the 'in category' under your CPT  
4. save
5. click now on display condition
6. click on the select input and look it change to 'in categroy' of 'posts'

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.29
	PHP Version: 7.3.16
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://menaitc.com
	Home URL: https://menaitc.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: navarro.ido@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.8.9
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.2
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.2.6
		Author: Crocoblock

	WP Force SSL
		Version: 1.55
		Author: WebFactory Ltd

	Yoast SEO
		Version: 13.4.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 1
		heading : 1
		portfolio : 1
	footer : 1
		form : 1
		heading : 1
		icon-list : 6
		text-editor : 2
	header : 1
		image : 1
		nav-menu : 1
		social-icons : 1
	single : 4
		form : 2
		heading : 28
		icon : 9
		image : 6
		jet-posts : 1
		post-navigation : 2
		posts : 1
		share-buttons : 2
		spacer : 1
		text-editor : 30
		theme-post-title : 2
		video : 2
	wp-page : 3
		button : 2
		call-to-action : 2
		heading : 8
		icon : 5
		image : 7
		posts : 1
		text-editor : 11

== Log ==
	
JS: showing 4 of 4JS: 2020-04-05 10:55:41 [error X 1][https://menaitc.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.4:2:106905] Routes: `` not found. 
JS: 2020-04-05 10:56:32 [error X 4][https://menaitc.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.3:2:54590] Cannot read property \&#039;top\&#039; of undefined 
JS: 2020-04-05 18:06:51 [error X 1][https://menaitc.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.4:31:101473] Cannot read property \&#039;message\&#039; of null 
JS: 2020-04-06 15:26:27 [error X 1][https://menaitc.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view8281\&quot;) has already been destroyed and cannot be used. 

Log: showing 2 of 22020-04-06 07:05:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.7',
)]
2020-04-06 07:05:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.9.2',
)]

PHP: showing 2 of 2PHP: 2020-04-06 13:57:14 [notice X 6][/home/menaitcard/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-06 14:22:28 [error X 1][/home/menaitcard/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/menaitcard/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/menaitcard/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/menaitcard/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/menaitcard/public_html/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/menaitcard/public_html/wp-includes/class-wp-hook.php(312): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /home/m [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shenickisland** [comment]
I can confirm this behavior. Fresh install with latest versions of Elementor, Pro and Toolset (to add the CPT) installed only. I wish to do exactly like the original poster and the steps to reproduce are the same for me. 

My temporary workaround was to create a new taxonomy in Toolset, specific to my custom post type, and use that as my "category". Doing this allows the selected option (my new fake category in this case) in Display Conditions to remain selected after saving. Not ideal but works for now.

Hopefully a proper fix is coming soon.

**Comment by michelebruno** [comment]
Got the same issue here. I can't set a template to appear when the CPT is under a category. I guess this happens because all options have the same value "in_category". The value should be something like "CPTslug_in_category".

Please fix this asap, it makes hard to make Elementor work with CPT.

![immagine](https://user-images.githubusercontent.com/43304601/81657213-fc95a880-9437-11ea-993c-478c10bbd0d2.png)
