### ISSUE TITLE
Different Theme on my laptop website and mobile website (laptop theme not working) using just Elementor plugin

### ISSUE THREAD

**Issue by sasiroa** [elementor/elementor#11100]
Hi all,
Not sure what is happening, but I've changed my Theme yesterday from the TwentyTwenty WP theme by to Kadence and I had some problems,, there is some code still running from the old Theme TwentyT,  and my Home Page, stills showing this old theme on my Home page.

I also get some "Bad requests" on my GTMetrix report from this 2020Theme....

Apparently the Theme on  MOBILE phone is running well but on LAP is not working at all as all the design of the website is mixed...

Thank you for your help :)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @sasiroa,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by sasiroa** [comment]
Thank you just solve the problem. Apparently was a cache problem.
Regards,
