### ISSUE TITLE
Facebook Live Widget

### ISSUE THREAD

**Issue by makman111** [elementor/elementor#11112]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Looking for a simple way to embed Facebook live into elementor pages and posts.
I would be great if it allow for an optional place holder image or text when it is not broadcasting

There are other solutions out there like FB Live Auto Embed, but they are not part of the elementor ecosystem.

**Comment by arielk** [comment]
You can use Facebook Embed widget (is part of Elementor Pro) to display FB Live

Thanks
