### ISSUE TITLE
UNCAUGHT SYNTAXERROR: UNEXPECTED TOKEN '.'

### ISSUE THREAD

**Issue by DuerrundSteidle** [elementor/elementor#11116]
Hello together,

I get the error message "Uncaught SyntaxError: Unexpected token '.'".
I think the problem is a wrong code in "CSS" in Elementor. But I don't now where I written that code.
Could you say to me how it is possible to find it?
Thanks or your help.

Greetings
DuerrUndSteidle

**Comment by DuerrundSteidle** [comment]
It would be nice if somebody is able to help me?

**Comment by DuerrundSteidle** [comment]
Is there no solution? Sry for aksing again but I'm waiting for 6 days.

**Comment by lior-sh** [comment]
Hi @DuerrundSteidle,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
