### ISSUE TITLE
Popup New Rule : Show every X sessios

### ISSUE THREAD

**Issue by FrancoisPremier111** [elementor/elementor#11110]
Hey hcongratulations for your Elementor tool. I'm amazed.
Just a suggestion for you about popup conditions : why not add "show every X sessions »
than we see it at first connection than every X times we go back to the site.

**Comment by Nemesis77swe** [comment]
I second this suggestion!
For example, an information popup that only displays every 3, 4th visit.
It's can be very annoying for visitors to see the same popup every time they reload the page!

**Comment by rainbowpets** [comment]
Me too! 
This is an essential function, I HATE popups when visiting sites, so why bother visitors more then necessary?

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
