### ISSUE TITLE
[Feature request] Dynamically change the text color based on the background color

### ISSUE THREAD

**Issue by digitpulse** [elementor/elementor#11129]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
**Describe the solution you'd like**

Hi,

I have an Elementor header drived with OceanWP and when the sticky header comes over the white background or images that has a white shape on, the text or icons are not visible.

It would be great if Elementor can provide such a feature : an option in advanced settings that dynamically change the text or widget color in a black color when passing over white background and so on.

such as https://www.carineroitfeld.com/en does.

I don't know if it's hard to develop on Elementor, but it would be very useful and it's worth asking :)

Best regards

**Comment by Aviad-Herman** [comment]
Hi @digitpulse thanks for submitting this feature request.
In the example you sent the text color actually doesn't change based on the background color, the change is triggered using JavaScript depending on the current visible section.

If you have some coding skills you too can achieve the same effect.

Currently this is not supported as an out-of-the-box feature.
