### ISSUE TITLE
Testimonial Error

### ISSUE THREAD

**Issue by b00tk1ll** [elementor/elementor#11125]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
The testimonial image has a problem.
The image appears in the editor but does not appear on the website and "class =" testimonial-item "> appears in place of the image.
See image
![image](https://user-images.githubusercontent.com/8213622/79076117-cac0e300-7ccd-11ea-9bf0-77d66a976577.png)
![image](https://user-images.githubusercontent.com/8213622/79076124-e6c48480-7ccd-11ea-8bfc-9230c6ecc3cd.png)

## Steps to reproduce

Theme: Ryse 
Testimonial : Version One

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 13, Revision fd33d43 v5.7.17-13
	PHP Version: 7.1.13
	PHP Max Input Vars: 4000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: https://pitree.com.br
	Home URL: https://pitree.com.br
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Ryse
	Version: 1.4.1
	Author: RadiantThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.1.7
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 1.10.2
		Author: Facebook

	Jetpack by WordPress.com
		Version: 8.4.1
		Author: Automattic

	Mailchimp for WooCommerce
		Version: 2.3.6
		Author: Mailchimp

	Radiantthemes Addons
		Version: 2.0.3
		Author: RadiantThemes

	RadiantThemes Custom Post Type
		Version: 1.2.2
		Author: RadiantThemes

	Redux Framework
		Version: 3.6.18
		Author: Team Redux

	Smush
		Version: 3.6.1
		Author: WPMU DEV

	Void Contact Form 7 Widget For Elementor Page Builder
		Version: 1.0.9
		Author: voidCoders

	WooCommerce
		Version: 4.0.1
		Author: Automattic

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.20
		Author: WooCommerce

	WooCommerce Services
		Version: 1.23.0
		Author: Automattic

== Elements Usage ==
	
	section : 9
		heading : 1
		image : 1
		radiant-contact_box : 1
		radiant-custom-button : 1
		text-editor : 1
	wp-page : 62
		heading : 14
		image : 19
		radiant-custom-button : 1
		radiant-popup-video : 1
		radiant-portfolio : 1
		radiant-testimonial : 1
		text-editor : 10

== Log ==
</details>

**Comment by lior-sh** [comment]
Hi @b00tk1ll,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
