### ISSUE TITLE
Global (variable) colors in the color picker

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#11123]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Description
Elementor should consider adding **global (variable) colors in the color picker**.

**1.** You save a color and mark it as global (somehow mark the swatch to distinguish global colors from other saved colors).
**2.** You apply this color to multiple elements.
**3.** Editing the global color changes the color of all elements it was applied to.

It's the same principle as CSS Variables. This is super useful in writing CSS and should be easily available in Elementor.

You set a few variable colors in the root, then you use them throughout your page and then you can edit the colors globally without editing every single element.

## Alternative

Or, if marking colors as global directly in the color picker is too complicated to implement, we could add global variable colors somewhere else in Elementor backend and they would then appear in the color picker marked as global colors.

## Reason

I know Elementor allows pulling dynamic colors from custom fileds, but I think this is not a practical solution for this. Normal users are not going to use this for global colors. Custom fileds are useful for advanced users who want to use dynamic colors but for global variable colors we should have something far simpler incorporated directly into the color picker.

In every single project you are using only a few main colors and when you decide to change one of the main colors you have to edit every single element by hand.

In CSS this is easily solved by variables. It should be just as easy with Elementor. 

Almost every user would use this if you made it easily available in the color picker, it's not hard to implement (you can use CSS variables) and it would make Elementor so much more powerful.

I'm writing this because i was exploring other website builders and similar tools and many of them have this and it's an amazingly powerful yet simple feature to have.

It's the core details like this that matter.

**Comment by black-eye** [comment]
+1
I though this would be solved by #6485, but unfortunately it was a false hope. The whole global/dynamic color stuff shoud work as described here.

**Comment by SegoHero** [comment]
I would love this

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!
