### ISSUE TITLE
Bug: Elementor Pro 2.9.2 CTA Widget

### ISSUE THREAD

**Issue by SebMxx** [elementor/elementor#11122]
Hello Elementor team,
I have just noticed that the text-content section can only be styled if it has a direct value in the input mask.
If you have not entered a value there and only receive a dynamic value, such as a post excerpt, you have no way to style this text area.

**Comment by lior-sh** [comment]
Hi @SebMxx,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Screenshot or video.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
