### ISSUE TITLE
How to add a new font & change the default font of the text editor widget?

### ISSUE THREAD

**Issue by 09eric09** [elementor/elementor#11120]
Can someone point me in a direction as to where/how I can add a new font the "text editor" widget dropdown and enable that as the new default font when that widget is chosen?

**Comment by shirokoweb** [comment]
Please don't create issues that aren't issues. GH is not a support forum. Don't be lazy
![image](https://user-images.githubusercontent.com/63014390/79071473-30b46700-7cdc-11ea-999b-8971d42135a1.png)
The feature you are asking for [is available in "Pro" version](https://docs.elementor.com/article/276-custom-fonts).
Ask support questions [here](https://elementor.com/support/), Elementor Pro users enjoy premium 24/7 support
Not a "Pro" user? Ask community on FB [here](https://www.facebook.com/groups/Elementors) 
There is enough "real" issues that need to be addressed not to add fancy questions on top.
Wonder why it takes so long to fix things...

**Comment by 09eric09** [comment]
Thanks, I honestly didn't know where else to post, which is why I was only asking for someone to point me in the right direction. I will not create issues like this again now that I know where to post.
