### ISSUE TITLE
[bug with diapositive widget on safari]

### ISSUE THREAD

**Issue by oj2frey** [elementor/elementor#11138]
Hi there,
I think there is an issue with the elementor diapositive widget on safari .
 Context : slider  created with one or more image + ken burns effect checked
=> works on chrome
=> works on firefox
=> doesn't work on safari , the image seems to be blocked
 when ken burns effect is unchecked= everything is working fine , on all browser.

thx

**Comment by lior-sh** [comment]
Hi @oj2frey,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
