### ISSUE TITLE
SVG icons have bad positioning

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#11141]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

SVG icons have bad positioning unlike of the Font Awesome icons.

## Steps to reproduce

For example on the Form widget button see difference between Font Awesome icon from Elementor and SVG icon downloaded from Font Awesome.

![font-awesome](https://user-images.githubusercontent.com/7617350/79386991-44293180-7f6b-11ea-9d42-b209129a8855.png)
Font Awesome

![svg](https://user-images.githubusercontent.com/7617350/79387006-48554f00-7f6b-11ea-9385-a8b71feab0c0.png)
SVG

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by udidol** [comment]
Hi,
Elementor does not use FontAwesome SVGs - our widgets' CSS is designed to be compatible with Icon Fonts, not SVGs. There might be differences in the CSS used to achieve the same positioning and sizing between SVGs and Icon Fonts.

If you want to use an SVG downloaded from an external source, outside of Elementor, even if it is from FontAwesome - you will have to take care of any necessary CSS adjustments on your own.
