### ISSUE TITLE
Query Filter for Sale Products?

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#11147]
I need Query Filter the sale products Woocommerce.

Can you help me, please? :)

// Posts or Portfolio Widget
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	// Modify the posts query here
} );

**Comment by lauranunez** [comment]
It doesn´t work

add_action( 'elementor/query/my_custom_filter', function( $query ) {
$meta_query = $query->get( 'meta_query' );
	// Append our meta query
	$meta_query[] = [
'meta_key' => '_sale_price',
	];
	$query->set( 'meta_query', $meta_query );
} );

Please, help me

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
