### ISSUE TITLE
Button Element > Icon alignment when justified

### ISSUE THREAD

**Issue by alexnl** [elementor/elementor#11149]
When a button is justified and an icon added, the icon remains on far left or far right side, while the text is in the middle. There should be an option to have the icon appear immediately to the right or left of the text. 

Example of the issue:
![image](https://user-images.githubusercontent.com/317587/79498001-a1b69000-7ff6-11ea-8c2d-1af79e290370.png)

**Comment by lior-sh** [comment]
Hi @alexnl,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by bottlebug** [comment]
I'm having the same problem.

I created a button with alignment set to justified. Added an icon and it just keeps to the left or right, depending on the icon position. All done on mobile view on the latest version of Elementor.


![Screen Shot 2020-08-17 at 7 10 54 PM](https://user-images.githubusercontent.com/16513636/90367934-69ff4800-e0bd-11ea-8390-aeabf4fd4199.png)
