### ISSUE TITLE
Font Awesome doesn't load for Submit button

### ISSUE THREAD

**Issue by zero4281** [elementor/elementor#11140]
The spinner on the Form Submit button doesn't show up unless there's another Font Awesome element being displayed on the page.  The Form Widget doesn't trigger the Font Awesome CSS file to get loaded.  Once I add a Font Awesome Icon to the page then the Font Awesome CSS gets loaded correctly and the spinner starts working.

This seems like it's related to Issues #10428 and #9907.

**Comment by lior-sh** [comment]
Hi @zero4281,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
