### ISSUE TITLE
Column width not working

### ISSUE THREAD

**Issue by benhenry20** [elementor/elementor#11150]
Hi, this is a problem that has consistently haunted me since I signed up for Elementor. It won't let me adjust the column width at all. It's very frustrating and I have had to build with workarounds. What am I doing wrong?? I have tried on both Chrome and Safari and it behaves the same.

Strangely it works fine in tablet but not desktop mode. Here's video of what I mean.

https://www.dropbox.com/s/vym6j8wzkhmvl4z/column%20width.mp4?dl=0

Ben

**Comment by black-eye** [comment]
@benhenry20  Hi, welcome to the club! ;) 
It's not a bug it's a "feature". Elelementor won't let you have 100% wide column on desktop (unless it's a single column section).

You can join the others, asking why here: https://github.com/elementor/elementor/issues/2218

**Comment by lior-sh** [comment]
As @black-eye said.
Duplicate with #2218
