### ISSUE TITLE
I added a new section on page, and everything on that page get bold

### ISSUE THREAD

**Issue by Skillstekerp** [elementor/elementor#11151]
I already have 2000 words page on elementor in wordpress. I just added a new section with an infographic. And then 80% of the page's content get bold by itself. And even I removed that new section now, it is still bold. please, someone, suggest a solution.

**Comment by lior-sh** [comment]
Hi @Skillstekerp,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
