### ISSUE TITLE
Scrolling effect on Safari iOS

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#11152]
On Safari with iOS 13.4.1 I noticed this kind of glitch with the scrolling effect of Elementor

Link to the video:  https://creationis.netsons.org/files/elementor_issue_scroll_effetc.mp4

How to resolve that?

**Comment by vladarte** [comment]
On macOS also. There seems to be a scroll effects problem with latest Safari.

**Comment by adityabhimesha** [comment]
yep this seems to be the issue on my projects as well, any solutions yet?
