### ISSUE TITLE
Lack of Documentation for Global Styles

### ISSUE THREAD

**Issue by jakebrightfire** [elementor/elementor#11157]
There seems to be a lack of documentation for developers on how to implement global settings in the new Theme Style section of the Elementor Editor as well as how to reference those global settings.

What is the proper way to implement this functionality? Once implemented, how can I get the value of the registered controls from somewhere else in the application like a dynamic tag?

I was told by Elementor Support to come here to ask developer questions.

**Comment by rami-elementor** [comment]
Hi @jakebrightfire 

See this Dev Doc: https://developers.elementor.com/docs/controls/global-style/
