### ISSUE TITLE
✔️ 🚀 Query product latest change

### ISSUE THREAD

**Issue by phcaraujo** [elementor/elementor#11159]
I use the Easy Digital Downloads and Elementor plugin.

How do I create a query by consulting the products/downloads/posts that have been updated recently?

For Elementor, I can only bring the latest added ones.

**Comment by nicholaszein** [comment]
Hello there @phcaraujo!

This feature is already available with both the Products, and Loop Grid widgets. When selecting the Query, make sure to select the option to **Query by**: Latest Products.

For more info check these documents:

https://elementor.com/help/woocommerce-products-pro/

https://elementor.com/help/customize-items-in-loop/

https://elementor.com/help/building-query-loop-grid/

Kind regards
