### ISSUE TITLE
Social icons disappear when adding "toggle" widget.

### ISSUE THREAD

**Issue by tombalazs** [elementor/elementor#11154]
Problem: When I insert a toggle widget anywhere on my page, the social icons embedded in the page at the top turn into boxes instead of icons. I have recreated the problem several times by removing and replacing the toggle section. When the toggle is removed, icons come back. As soon as it is added, they go away.
Using a theme called BlackSilver, Elementor v2.9.7, WP v5.4

**Comment by lior-sh** [comment]
Hi @tombalazs,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
