### ISSUE TITLE
On Post Editing - Section is Not Stretching

### ISSUE THREAD

**Issue by mohsinworld** [elementor/elementor#11155]
Elementor bug or something I missing here? Please note that: This is a post.

After a deep research, I found a specific problem. When I set padding-top then the full width becomes boxed/normal width! And, on "page edits" this problem is not appearing.

Elementor stuff needs attention here! Related video https://www.facebook.com/groups/Elementors/permalink/2690165357775900/

**Comment by arielk** [comment]
Please go to your Elmenetor Settings > Style > and check who inherit class for "Stretched Section Fit To" if it depends on the `body` tag please try to check if the theme adds a redundant style for this tags. 
Anyway, we are not recommended to use this feature, please try to resolve it by changing the theme.

**Comment by mohsinworld** [comment]
I just skip this problem by switching it to page. I'll pass this issue for me. But can you check this issue I encounter today? https://www.facebook.com/groups/Elementors/permalink/2714097795382656/
