### ISSUE TITLE
Elementor Pro - Forms  - Email Obfuscation

### ISSUE THREAD

**Issue by MyListingClub** [elementor/elementor#11162]
Hello. In our forms, we are using a hidden field that pulls in the email address of the WordPress user. This is the email they used when signing up for the website.

**Is there a way, within Elementor, or otherwise, to prevent these email addresses from being scraped?** 

Right now, even with Cloudflare's Email Obfuscation in place, these email addresses are viewable in the source code.

Thank you,
Ryan

**Comment by shilo-ey** [comment]
Hi @MyListingClub 

Thanks for your feedback,

Please read this thread: https://github.com/elementor/elementor/issues/7285#issuecomment-469425891

Thanks

**Comment by MyListingClub** [comment]
Hi. That thread never provided the solution and actually introduced another issue, if you read through the notes. Multiple people have tested it.

Please consider re-opening this thread so we can try and find a solution. Thanks.

**Comment by shilo-ey** [comment]
[**@MyListing Club**](https://github.com/MyListingClub) commented on [Apr 19, 2020, 3:27 PM GMT+3](https://github.com/elementor/elementor/issues/11162#issuecomment-616121870 "2020-04-19T12:27:49Z - Replied by Github Reply Comments"):
> Hi. That thread never provided the solution and actually introduced another issue, if you read through the notes. Multiple people have tested it.
> 
> Please consider re-opening this thread so we can try and find a solution. Thanks.

Hi, 

Can you please describe what is not working in the provided solution?
What are your actions, expectation and actual result.

Thanks.

**Comment by MyListingClub** [comment]
You bet. Where this breaks down is [noted in the thread here](https://github.com/elementor/elementor/issues/7285#issuecomment-469713943).

In short, with the solution provided, Email Obfuscation does work, but the Author Email (as outlined in my guide below) is not getting the email notifications from the form submissions. Instead, the Admin of the website does.

Please see [this section of a guide I wrote](https://mylisting.club/replace-contact-form-7-with-elementor-pro/#integrate-elementor-pro), which breaks down the steps I took to create the form.
