### ISSUE TITLE
Pinterest - specify which image to share - feature request

### ISSUE THREAD

**Issue by jacksarlo** [elementor/elementor#11167]
Hi,

I use Elementor's "share buttons" widget but I want to specify which image the Pinterest share icon picks up to share. Currently, it seems to pick a random image from the page.

The image I want it to share isn't on the page, because it's designed specifically for Pinterest.

Thanks

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Note that we have added an option to share a specific image in the new lightbox, read more here: https://elementor.com/blog/introducing-theme-style/

Thank you for your feedback!
