### ISSUE TITLE
Toggle widget links doesn't work when using create_element_instance and print_element

### ISSUE THREAD

**Issue by pstidsen** [elementor/elementor#11160]
## Prerequisites

- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have used the create_element_instance to print the toggle widget programmatically (full code here: https://pastebin.com/Ay9L6Ump) but the thing is that the toggle does not work at the site afterwards as it should.

## Steps to reproduce

1. Use the following code sample to print the toggle widget: https://pastebin.com/Ay9L6Ump
2. Go to the frontend and see that the toggle links does not work

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

System Info
See: https://pastebin.com/YA7WE0xq

**Comment by udidol** [comment]
Hi,
What do you mean by "the toggle links doesn't work"?
What are you trying to do?

Also, the action you are attaching this function to is not an Elementor action, so I cannot help with that aspect.

**Comment by pstidsen** [comment]
> What do you mean by "the toggle links doesn't work"?
> What are you trying to do?

I mean that if I click the toggle links (the tab_title) then the toggle should reveal the tab_content but it doesn't.

**Comment by udidol** [comment]
Yes, but what are you trying to achieve? Why do you want to inject a Toggle widget like that?

**Comment by pstidsen** [comment]
Yes, that's exactly what I am trying. 

The reason is that I have the data/content for the toggle in an array in the PHP code. Therefore I wanted to generate it programmatically.
And as far as I could read the documentation, I thought, it was how to inject it programmatically.

Maybe I am wrong?

**Comment by udidol** [comment]
It will generate and print the widget's markup. It does not load the widget's handler.
I am not sure I've seen something like this done before, but I can suggest that you try using Elementor's JS hook system to trigger loading the handler:

```
$widget = jQuery( '#the_widget_wrapper_selector' );
elementorFrontend.hooks.doAction( 'frontend/element_ready/' + widgetType, $widget );
```
Replace `the_widget_wrapper_selector` with your toggle widget's unique ID, and `widgetType` with the `widgetType` property in your widget's JSON. 
If that doesn't work, try adding `.default` after the `widgetType` string, like so: `'frontend/element_ready/' + widgetType + '.default'`

**Comment by pstidsen** [comment]
Oh, I see. Sorry for my late reply. I just have two quick follow up questions:

Where should I run these two lines of code? Is it some JavaScript which I should run in the <head> of the page?

Is the_widget_wrapper_selector just the id of a wrapping div?

**Comment by udidol** [comment]
> Where should I run these two lines of code? Is it some JavaScript which I should run in the of the page?

Yes, you should either attach this code to your footer (via the `wp_footer` hook), or put it in a JS file and enqueue it where you need this widget.

> Is the_widget_wrapper_selector just the id of a wrapping div?

It is the unique identifier of the wrapping `<div>` element with the classes `elementor-widget` and `elementor-widget-toggle`.

**Comment by pstidsen** [comment]
Thanks for your reply.

It seems like something need to be loaded maybe. Running the code I get the following error in the console:

`Uncaught TypeError: Cannot read property 'doAction' of undefined`

**Comment by udidol** [comment]
Perhaps you are trying to call the action too early. 
Try to call the action at a later time in your loading sequence. 
You can try to incorporate it on document ready, like so:
```
jQuery( document ).ready( function() {
   $widget = jQuery( '#the_widget_wrapper_selector' );
   elementorFrontend.hooks.doAction( 'frontend/element_ready/' + widgetType, $widget );
} );
```

If you can't get it to work, maybe you should try contacting a developer to assist you.
You can probably find Elementor developers in [Elementor Experts](https://experts.elementor.com/).

Good luck!

**Comment by pstidsen** [comment]
OK, it helped to load it later.

I ended up with the code: https://pastebin.com/mPn7ZWu5 running without console errors. However the issue persists. The toggle heading links does not open the toggle content but it reloads the page..
