### ISSUE TITLE
Tablet Responsive Issue (columns)

### ISSUE THREAD

**Issue by Basilou38** [elementor/elementor#11164]
Hi,

I have a problem with responsive only on tablet.

To better understand, i made a video capture :
https://www.loom.com/share/2c65c054b25a42d2ab84c9d7e1e17aeb

On desktop, I have 3 columns, on tablet, I want 2 columns. When I try to apply 2 column on tablet, the desktop version is broken, I don’t understand, is this a bug with elementor ?

**Comment by lior-sh** [comment]
Hi @Basilou38,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info.**
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by Basilou38** [comment]
Hi @lior-sh lior-sh

here is the report of elementor, that's enough ?

----------------------------
        == Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.46-86.2
	PHP Version: 7.4.4
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4
	Site URL: https://clemenceheller.pro
	Home URL: https://clemenceheller.pro
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: winovax
	Version: 1.0.0
	Author: winovax
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.4.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

== Active Plugins ==
	Animentor – Lottie & Bodymovin widget for Elementor
		Version: 1.1.1
		Author: overengineer

	Astra Pro
		Version: 2.4.0
		Author: Brainstorm Force

	Astra Widgets
		Version: 1.2.3
		Author: Brainstorm Force

	Custom Fonts
		Version: 1.2.1
		Author: Brainstorm Force

	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.2
		Author: Elementor.com

	Elements Plus!
		Version: 2.14.0
		Author: The CSSIgniter Team

	Envato Elements
		Version: 1.1.9
		Author: Envato

	Envato Market
		Version: 2.0.3
		Author: Envato

	Optimus
		Version: 1.6.0
		Author: KeyCDN

	Post Types Order
		Version: 1.9.4.3
		Author: Nsp Code

	Rank Math SEO
		Version: 1.0.42.3
		Author: Rank Math

	Real 3D Flipbook
		Version: 3.13.1
		Author: creativeinteractivemedia

	WP Portfolio
		Version: 1.9.0
		Author: Brainstorm Force

	WPS Hide Login
		Version: 1.5.6
		Author: WPServeur, NicolasKulka, tabrisrp


== Must-Use Plugins ==
	mu-optimize.php
		Version: 
		Author: 


== Elements Usage ==
	
	archive : 3
		archive-posts : 2
		button : 3
		heading : 5
		image : 2
		theme-archive-title : 1
		wp-widget-archives : 1
	page : 15
		button : 26
		divider : 3
		ep-image-comparison : 4
		global : 2
		heading : 51
		icon-box : 3
		image : 19
		image-box : 9
		shortcode : 1
		slides : 1
		social-icons : 3
		spacer : 17
		testimonial-carousel : 1
		text-editor : 26
		toggle : 2
		video : 1
	popup : 2
		form : 1
		heading : 2
		image : 2
		text-editor : 1
	section : 6
		be-timeline : 1
		heading : 1
		image : 6
	widget : 0
		button : 73
	wp-post : 2
		button : 7
		divider : 5
		heading : 25
		icon-box : 3
		image : 21
		lottie : 1
		shortcode : 1
		social-icons : 2
		spacer : 10
		testimonial-carousel : 1
		text-editor : 22
	wp-page : 6
		animated-headline : 1
		button : 2
		divider : 8
		ep-content-toggle-plus : 1
		form : 1
		heading : 23
		image : 9
		lottie : 3
		shortcode : 2
		spacer : 1
		testimonial-carousel : 1
		text-editor : 14


== Log ==
	
Log: showing 18 of 182020-01-02 17:10:36 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-02 17:10:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-02 17:10:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-02 17:10:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2020-01-19 12:30:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-01-29 04:28:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-02-12 10:23:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.0',
)]
2020-02-14 15:49:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.0',
  'to' => '2.9.1',
)]
2020-02-18 17:36:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.1',
  'to' => '2.9.2',
)]
2020-02-18 17:36:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-02-27 14:47:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-05 09:52:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-10 10:13:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-10 10:15:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-03-12 09:31:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-17 09:35:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '2.9.1',
)]
2020-03-25 14:30:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-03-26 12:53:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.1',
  'to' => '2.9.2',
)]

JS: showing 20 of 21JS: 2020-01-31 11:52:18 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2339\") has already been destroyed and cannot be used. 
JS: 2020-02-13 16:01:53 [error X 5][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view96\") has already been destroyed and cannot be used. 
JS: 2020-02-13 16:01:56 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1185\") has already been destroyed and cannot be used. 
JS: 2020-02-13 16:02:58 [error X 2][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view336\") has already been destroyed and cannot be used. 
JS: 2020-02-13 16:03:01 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2155\") has already been destroyed and cannot be used. 
JS: 2020-02-20 09:51:06 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view200\") has already been destroyed and cannot be used. 
JS: 2020-02-21 10:53:10 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-02-21 11:02:56 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6998\") has already been destroyed and cannot be used. 
JS: 2020-02-22 17:25:10 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view302\") has already been destroyed and cannot be used. 
JS: 2020-02-26 17:30:46 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.2:2:97974] Commands internal: `document/history/delete-transaction` not found. 
JS: 2020-02-27 17:16:08 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2491\") has already been destroyed and cannot be used. 
JS: 2020-03-01 14:04:17 [error X 2][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2146\") has already been destroyed and cannot be used. 
JS: 2020-03-01 14:04:28 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2174\") has already been destroyed and cannot be used. 
JS: 2020-03-04 09:25:40 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view85\") has already been destroyed and cannot be used. 
JS: 2020-03-04 09:57:52 [error X 3][https://clemenceheller.pro/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.4:2:54702] Cannot read property \'top\' of undefined 
JS: 2020-03-20 15:34:11 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:31:168588] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-03-20 15:42:03 [error X 1][https://clemenceheller.pro/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2774\") has already been destroyed and cannot be used. 
JS: 2020-03-28 15:46:27 [error X 2][https://clemenceheller.pro/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.7:2:187452] Cannot read property \'map\' of undefined 
JS: 2020-03-31 13:49:12 [error X 2][https://clemenceheller.pro/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.7:31:183966] Cannot read property \'match\' of undefined 
JS: 2020-04-18 15:32:00 [error X 4][https://clemenceheller.pro/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:58852] Cannot read property \'attributes\' of undefined 

PHP: showing 3 of 3PHP: 2020-02-13 17:02:51 [notice X 499][/home/mysocialartcomma/public_html/wp-content/plugins/elementor/includes/managers/image.php::88] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-26 10:13:43 [notice X 2][/home/mysocialartcomma/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-30 12:45:14 [notice X 2321][/home/mysocialartcomma/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1447] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
