### ISSUE TITLE
Can Elementor pages be rendered outside of Wordpress ?

### ISSUE THREAD

**Issue by duderion** [elementor/elementor#11165]
Hi Guys,

in my eyes, one of the main disadvantages in custom programmed apps (laravel, symfony, cakephp whatsoever) is the missing ability to easily create static content, exactly what elementor delivers.
So i ask myself if it wouldnt be nice to have the possibility to render elementor-styled pages literally anywhere.i played around with requesting the rendered html-content via rest-api and elementor internal functions, but then i had to manually copy the header code (and further scripts near the bottom body tag) to make it running. Isnt there a more generic method to render a full elementor-page outside of wordpress ? e.g. render it in a custom web app. i am dreaming of wordpress as a static content engine, rendered within my apps.

Thanks alot!
Adrian

**Comment by FredrikH03** [comment]
So... uhhhh... considering you closed it as completed I hope you don't mind me asking if you ever figured it out, not to mention if you even remember what you did, considering its been 5 years.

**Comment by Recreabox** [comment]
I'm also searching a solution here.

I would like to preview elementor templates outside Wordpress.
