### ISSUE TITLE
Incompatibility with Page Generator PRO

### ISSUE THREAD

**Issue by rafalilloblanco** [elementor/elementor#11188]
Good morning I am using Elementor + Page Generator PRO. When I try to edit any page of Page Generator PRO, no elementor appears and gives me an error in console, besides not allowing me to modify the page.
![Captura4](https://user-images.githubusercontent.com/17000368/79834846-0afb2200-83ae-11ea-85c2-0cf962a5d62b.JPG)
![Captura](https://user-images.githubusercontent.com/17000368/79834872-12223000-83ae-11ea-97b1-8a71f831af7f.JPG)

**Comment by lior-sh** [comment]
Hi @rafalilloblanco,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by n7studios** [comment]
You need to enable Elementor on Page Generator Pro's Content Groups, as Documented:
https://www.wpzinc.com/documentation/page-generator-pro/generate-page-builders-integration-elementor/#setup

This then resolves.
