### ISSUE TITLE
Incompatibility with Page Generator PRO

### ISSUE THREAD

**Issue by rafalilloblanco** [elementor/elementor#11189]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

Good morning I am using Elementor + Page Generator PRO. When I try to edit any page of Page Generator PRO, no elementor appears and gives me an error in console, besides not allowing me to modify the page.

![Captura4](https://user-images.githubusercontent.com/17000368/79838037-b1e1bd00-83b2-11ea-974c-096df077ba17.JPG)
![Captura](https://user-images.githubusercontent.com/17000368/79838052-b6a67100-83b2-11ea-9c66-b4a2e2d2320b.JPG)

## Steps to reproduce

1.- Within the Wordpress administration panel we must go to Page Generator Pro> Generate Content

2.- The page we created long ago appears and we click on Edit with Elementor.

3.- The editor opens but we cannot do anything else.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/AG9jBcga

**Comment by arielk** [comment]
Unfortunately we are not familiar with this plugin, please send this issue to the author of this plugin.

Thanks
