### ISSUE TITLE
Icons_Manager::render_icon not rendering class with SVG

### ISSUE THREAD

**Issue by AbanobAkram** [elementor/elementor#11199]
Hi there,

Hope you're having a great day :)

Well, I'm currently building an Elementor Widget, and I want to use ICONS control. I've added the link below to render the icon, but it seems class is not rendered when I try to insert SVG instead of an icon.

`<?php Icons_Manager::render_icon( $settings['icon_left'], [ 'class' => 'ese-icon-left', 'aria-hidden' => 'true' ] ); ?>`

So, could you please advise ?

Regards,
Abanob

**Comment by bainternet** [comment]
@AbanobAkram 

`Icons_Manager::render_icon` only adds attributes to font icons and not SVG icons as they are printed inline. You can, however, add the class to the SVG prior to uploading it or if you want it on a wrapper you can simply check if the current icons is an SVG ex:

```PHP
<?php
$is_SVG = 'svg' === $settings['icon_left']['library'];
if ( $is_SVG ) {
	?><div class="I-M-Wrapper ese-icon-left"><?php
}
Icons_Manager::render_icon( $settings['icon_left'], [ 'class' => 'ese-icon-left', 'aria-hidden' => 'true' ] );
if ( $is_SVG ) {
	?></div><?php
}

```

Hope this helps.
