### ISSUE TITLE
Admin toolbar has disappeared - Twenty Seventeen theme

### ISSUE THREAD

**Issue by intercommsa** [elementor/elementor#11209]
Another user had their Admin toolbar disappear, but it was linked to a non-standard theme.

https://github.com/elementor/elementor/issues/11040

I am using the theme twentyseventeen and the admin toolbar has disappeared entirely, leaving a white gap. I am using 5.4

I purchased the Unlimited version of Elementor Pro and support in 2018 and 2019, but didn't purchase support in 2020. Therefore if there was a bugfix for 5.4 I would not have received it. How do I restore the WordPress toolbar?

![Untitled-1](https://user-images.githubusercontent.com/38719263/80053778-86ee8a80-84d2-11ea-9c61-0ebf0fba175f.jpg)
![chrome](https://user-images.githubusercontent.com/38719263/80053779-881fb780-84d2-11ea-82c4-bb9247de3161.jpg)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

**I use Elementor Version 2.7.3**

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active. (Twentyseventeen)
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
Please make sure to update Elementor to its latest version (2.9.8),
and let me know if the navigation bar appears.

**Comment by intercommsa** [comment]
Sadly, I can't. My my "unlimited" licence expired a few months ago, and that includes bug fixes.
