### ISSUE TITLE
Allow renaming of global widgets

### ISSUE THREAD

**Issue by groovybluedog** [elementor/elementor#11208]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sometimes one saves a global widget under a name that later needs to be changed... whether that's for clarity, because the intended function of the widget has changed, or otherwise, there is currently no way to rename a global widget. You would have to save it as a new one and then go around replacing everywhere you've used the widget.

**Describe the solution you'd like**
The facility to rename the widget, probably best done in the Saved Templates > Global Widget area of the admin control panel.

**Describe alternatives you've considered**
There is no alternative other than resaving and replacing the widget.

**Comment by arielk** [comment]
merge to: https://github.com/elementor/elementor/issues/1578

**Comment by inspiredearth** [comment]
@arielk Why was this merged into #1578 ? That seems like a far more challenging feature than simply renaming global widgets. Right?

**Comment by arielk** [comment]
> @arielk Why was this merged into #1578 ? That seems like a far more challenging feature than simply renaming global widgets. Right?

Indeed, it is simpler to do this, but we prefer to deal with issues with the same subject in one thread.
