### ISSUE TITLE
Description Box of Price Table Editor is too small

### ISSUE THREAD

**Issue by Braweria** [elementor/elementor#11203]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am in the process of designing a price table, but the description part of the editor is really hard to use if it's more than 10 characters. I want to be able to dive it a short description, but it is hard to edit the sentence in this tiny box.  

**Describe the solution you'd like**
A textbox instead would be a good solution to it.

**Describe alternatives you've considered**
Don't know fo any alternatives.

**Additional context**
Here is what I mean, my version is in German.
![warum ist das so winzig](https://user-images.githubusercontent.com/62669899/80005048-5f43f600-84c3-11ea-9b44-37d4f5f0a3ce.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!
