### ISSUE TITLE
Dark mode option for users

### ISSUE THREAD

**Issue by TheVoidCodes** [elementor/elementor#11219]
It would be great that you would incorporate **Dark Mode For Users** in the Theme Style, and in particular widgets a Dark Mode tab in the Advanced section.

And of course a Dark Mode Toggle Button widget.

**Comment by fabianenzensperger** [comment]
+1

**Comment by actionTurtle** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/11073 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by fabianenzensperger** [comment]
> 

Ok but you work on this or not? @arielk

**Comment by arielk** [comment]
Hi @fabianenzensperger 

It's something we're considering for the future, I can't promise you more than that because it's something that needs a re-architecture of our element style mechanism and frankly that's going to take some time.

Your feedback is appreciated!
