### ISSUE TITLE
ScheduleOnce JavaScript Doesn't Work

### ISSUE THREAD

**Issue by yanivelbaz** [elementor/elementor#11222]
Hi, 
I'm using WP 5.4 (Ocean WP 1.8.2 theme) with Elementor Pro 2.9.3. 
I'm trying to add a short JS code that add a button or a widget to my site and opens a lightbox or a new page to schedule appointments. 
The JS for the lightbox works partially: the button appears, but clicking on it doesn't do anything. 
The JS for opening a new page completely breaks the text (when used inside an Image Box). 

Steps to reproduce: 
1. Add a Button or an Image Box
2. Click on the Dynamic Tags of the button's Link field or the image box Title & Description field. 
3. Select 'Site' --> 'Shortcode'
4. Paste the shortcode (see attached text file). 
5. Click 'Update' and check the site. 

![broken code](https://user-images.githubusercontent.com/33402319/80277425-84b94580-86f7-11ea-8e83-3b7997de7bc9.jpg)

[shortcodes.txt](https://github.com/elementor/elementor/files/4532768/shortcodes.txt)

Thanks for checking this out.

**Comment by udidol** [comment]
Hi @yanivelbaz , 

You cannot add Javascript to an Elementor page by including it as the content of a shortcode, not even as the content of an `onclick` attribute.
That could pose a security risk for websites.

If you want to add some Javascript code to your page, you should include it in your site's header or footer inside a `<script>` tag. 

There are many ways to do this. A simple one would be using a child theme, and in the child theme's `functions.php` file, creating a function and hooking it to the `wp_footer` hook. For example:
```
function my_unique_function_name() {
    ?>
    <script>
    // Add your JS and target your button here
    </script>
    <?php
}
add_action( 'wp_footer', 'my_unique_function_name' );
```

So, what you can do here is include your HTML in the shortcode, and add your Javascript separately.

**Comment by yanivelbaz** [comment]
Great, @udidol , thank you very much for the solution and for the explanation!
