### ISSUE TITLE
Toolset image doesn't work for group controls

### ISSUE THREAD

**Issue by blocksera** [elementor/elementor#11221]
Hi,

When selecting Toolset image field for Group_Control_Background, it does not set any background image. Other dynamic fields like featured image, site logo, etc works

```php
<?php
Group_Control_Background::get_type(),
[
    'name' => 'background',
    'label' => __( 'Background', 'plugin-domain' ),
    'types' => [ 'classic', 'gradient' ],
    'selector' => '{{WRAPPER}} .selector,
];
```

**Comment by lior-sh** [comment]
Hi @blocksera,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
* *List exactly what you tried to do, including the code you tried*
Without it, we simply can't help.
Thanks.
