### ISSUE TITLE
Bulk Selecting Sections and/or Widgets

### ISSUE THREAD

**Issue by geraberl** [elementor/elementor#11223]
Having now worked with Elemenor for a number of years now I, first of all, think it is absolutely terrific. However, one thing I constantly come up against os not being able to shift or control-click to select multiple sections or widget in one go in order to apply specific style changes to which would be an enormous time-saver.

Is this something that could be considered for future updates?

Many thanks

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #8006, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
