### ISSUE TITLE
new Mixcloud social icon

### ISSUE THREAD

**Issue by mistadizzle** [elementor/elementor#11239]
Mixcloud have updated their logos and branding, i noticed when using the social icons widget that the old logo is still the one in Elementor, pls can you update this?

Many thx

**Comment by shilo-ey** [comment]
Hi @mistadizzle 
Thanks for your input.

Elementor uses FontAwesome 5 as it's icons provider. once FA will update a new icon for Mixcloud - we would be able to do so as well.

Thanks.

**Comment by mistadizzle** [comment]
Thx for the info :)
