### ISSUE TITLE
Underscorejs variable for description field doesn't work?

### ISSUE THREAD

**Issue by dbjpanda** [elementor/elementor#11245]
I wanted to interpolate the value of a control inside another control's `description`. But it seems for `description` it doesn't work as like `title_field`. Is there any workaround? I tried #9501  but in vain. 

```php
$widget->add_control(
		    'ap_register_email_message',
		    [
			    'label' => __( 'Message', 'actions-pack' ),
			    'type' => \Elementor\Controls_Manager::TEXTAREA,
			    'default' => __('Thank you for registering to our site.', 'actions-pack'),
			    'placeholder' => __('Thank you for registering to our site.', 'actions-pack'),
			    'description' => '{{{ myHelper( control_key ) }}}',
			    'show_label' => true,
			    'condition' =>[
				    'ap_register_enable_email_notification' => 'yes',
			    ],
		    ]
	    );
```

**Comment by lior-sh** [comment]
Hi @dbjpanda,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by dbjpanda** [comment]
@lior-sh I think this is not a bug. You may consider it as a question.

**Comment by bainternet** [comment]
@dbjpanda 

It's not a bug and you are not doing anything wrong.

the simple answer is you can do that, not without some major custom coding,
the `description` attribute does not support underscore templates like the `title_field` of the repeater does.

thanks.

**Comment by dbjpanda** [comment]
@bainternet Well. Could you please provide some hints which class should i extend or any hook if available. I will try it in my own.

**Comment by bainternet** [comment]
Looking at the example you added then I guess the simplest way would be to extend the textarea control `includes/controls/textarea.php` more specifically the `content_template()` method if you look near the end of it you can see something like this:
```
<# if ( data.description ) { #>
	<div class="elementor-control-field-description">{{{ data.description }}}</div>
<# } #>
```

instead of `data.description` you can try access the other control value, something, for example, add this at the top of the method after the `?>`:
```JS
<#
function getControlValueForDescription( controlName ) {
	var editor = elementor.getPanelView().getCurrentPageView();
	var control = editor.collection.findWhere( { name: controlName } );
	return control.getControlValue()
}
var description = getControlValueForDescription( CONTROL_ID ) || data.description;
#>
```
where `CONTROL_ID` is set to your other control ID and replace 
```JS
<div class="elementor-control-field-description">{{{ data.description }}}</div>
```
with
```JS
<div class="elementor-control-field-description">{{{ description }}}</div>
```

This is not tested and basically a simple example to get you started in the right direction.


Hope this helps.

**Comment by dbjpanda** [comment]
Superb!!! Thanks for the detailed explanation. :)

**Comment by dbjpanda** [comment]
@bainternet `control.getControlValue()` doesn't work anymore. What is the alternative?
