### ISSUE TITLE
Templated Accordion inside of Toggle results in duplicate div IDs

### ISSUE THREAD

**Issue by besweeet** [elementor/elementor#11247]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I have an Accordion that was turned into a template. When the shortcode is pasted into a Toggle, the div IDs are the same. In my case, it's "elementor-tab-content-1411." This poses a WCAG accessibility issue:

> 4.1 Compatible - 4.1.1 Parsing (A) - Ensure that user agents, including assistive technologies, can accurately interpret and parse content.

## Steps to reproduce

1. Create an Accordion
2. Save it as a template
3. Drop the templates's shortcode into a Toggle list item

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by udidol** [comment]
Hi @besweeet ,
What div IDs are the same?
You would need to provide more details in order for us to be able to assist you with your issue.

**Comment by besweeet** [comment]
Here's a screenshot for reference: https://i.imgur.com/XwGypzG.png

All three accordions highlighted in red have div IDs that start with 1411 for the first entry item, even though they're all separate accordions build into a section template: `elementor-tab-title-1411`.

**Comment by udidol** [comment]
I am not sure I understand this, or why you would use templates to do this.
In the screenshot, what I am seeing is one toggle widget with 3 items, and in each item, there is a different shortcode of a different template comprising of a section with an accordion?

**Comment by besweeet** [comment]
> In the screenshot, what I am seeing is one toggle widget with 3 items, and in each item, there is a different shortcode of a different template comprising of a section with an accordion?

Correct. I was basically trying to nest an accordion within an accordion, so I used section templates for the nested accordions. Yet, many of them have the same div IDs.

Here's a better screenshot that illustrates the duplicate IDs: https://i.imgur.com/JNmlerm.png

**Comment by udidol** [comment]
That is strange. I tried to reproduce it but could not, my accordions got different IDs.

Did you use the same accordion instance for all of your templates?

Meaning, did you: 

1. Create an accordion
2. Change its contents to those in the first toggle item in the image you attached
3. Create a template from that
4. Then change this same accordion's contents to the contents in the second toggle item in the image you attached

?

If you did that, and did not use 3 different accordion instances to create your templates, that could potentially cause them having the same ID (because they were created from the same instance).

**Comment by besweeet** [comment]
I need to make a correction. Earlier, I said the three accordions were created as section templates. Instead, they were created as global widgets. I wonder if that route is why the IDs are identical.

**Comment by besweeet** [comment]
Aaaaand that did the trick. Everything now has their own ID.
