### ISSUE TITLE
Custom stylesheets per widget not loading 

### ISSUE THREAD

**Issue by prashantkb** [elementor/elementor#11249]
I am creating the custom Elementor widget. 

plugin.php => Here i am adding hook for the elementor.
`add_action('elementor/widgets/widgets_registered', 'registeElementorWidget');`

widget.php => creating the widget
class ElementorWidget extends Widget_Base {

	public function __construct($data = [], $args = null) {
		parent::__construct($data, $args);

		wp_register_script( 'elementor-script-handle', plugins_url('../src/js/elementor-script.js', __FILE__),
			[ 'elementor-frontend' ], '1.0.0', true );

		wp_register_style( 'elementor-style-handle', plugins_url('../src/css/elementor-style.css', __FILE__), 
			[ 'elementor-frontend' ], '1.0.0', true );
   	}

       public function get_style_depends() {
   		return [ 'elementor-style-handle' ];
   	}

   	public function get_script_depends() {
   		return [ 'elementor-script-handle' ];
   	}
       
      public function get_icon() {
		return 'icon-of-the-widget';
	}

The CSS file is loading the browser but the properties that defined in the file are not applying to the widget.

Currently, get icon function return the class. But I need to show the png file in the ICON place. I added the CSS to how the png file even I tested in the browser by inspecting and editing it. But when I included the CSS in the CSS file and refresh the page, the CSS file is loading but the properties whatever I wrote it's not applying to the widget.

Or is there any other way to display the png image in the Widget ICON ?

Thanks in advance.

**Comment by udidol** [comment]
Hi @prashantkb ,
Do you mean that you want to display an image instead of an icon in the Elementor Panel?
That is not possible.

**Comment by udidol** [comment]
Hi @prashantkb,
Do you mean that you want to display an image instead of an icon in the Elementor Panel?
We generally do not allow using anything other than an icon. You can try replacing the icon after the page is loaded, using JS.
