### ISSUE TITLE
Responsive min-height broken

### ISSUE THREAD

**Issue by owlyowl** [elementor/elementor#11243]
Hi! I love elementor  pro but this bug is driving me crazy in the latest version.

min height for responsive modes was added it does not work.

Steps to reproduce 

1. Set desktop section to Fit to Screen

2. Observe mobile not working as we know Fit to Screen doesn't work (documented in github issue 3 years old still not fixed)

3. Change mobile to min-height: 100vh in section settings

4. Go back to desktop in responsive and observe that Fit to Screen has now been changed to 400px min height??
![1_desktop](https://user-images.githubusercontent.com/1916426/80472125-a92b5100-8987-11ea-960c-bf7b093cd191.JPG)
![2_mobile-not-working](https://user-images.githubusercontent.com/1916426/80472130-ab8dab00-8987-11ea-9027-590b33ca09c9.JPG)
![3_mobile-changeto100vh](https://user-images.githubusercontent.com/1916426/80472133-ac264180-8987-11ea-987b-20bee4c1c18e.JPG)
![4_switch-to-desktop-wtf](https://user-images.githubusercontent.com/1916426/80472128-aa5c7e00-8987-11ea-8c38-f4a84080f835.JPG)

View in browser and either the section height on desktop is just broken or an arbitrary height and mobile is also broken

**Comment by udidol** [comment]
Hi @owlyowl ,
The "Height" control is not responsive. Only the "Min Height" control is. 
When you change the "Height" control's selected option, no matter in which preview state you are in, it changes for all screen sizes.
The default value for the "Min Height" control is 400px, and that is why when you look at the control for the first time in mobile mode, change it's value (for mobiles), then move to desktop mode - the value you see for desktops is the default, 400px.
