### ISSUE TITLE
[Feature Request] Include More Shape Divider Options Brush Stroke Divider

### ISSUE THREAD

**Issue by MrPrieto** [elementor/elementor#11252]
Since you introduce the shape divider options your guy no added more shape options will be nice add more options like the Brush Stroke Divider 
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment]
You can see more fancy dividers here: https://elementor.com/blog/introducing-background-slideshow/

Thanks
