### ISSUE TITLE
<main> tag - span across multiple sections

### ISSUE THREAD

**Issue by besweeet** [elementor/elementor#11256]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Per WCAG guidelines 1.3.1, sections need <header>, <footer>, and <main> tags. The first two are covered in recent Elementor updates (yay!). But, the <main> tag is the issue.

While you can set a <main> tag on a per-section basis, pages should only have one <main> tag. If I set <main> for all the sections, there will be multiple tags, which isn't the right way of doing it.

Ideally, you'd be able to set a start and end point for the tag within Elementor.

**Comment by arielk** [comment]
Starting Elementor Pro v2.9 you can select the HTML tag for each document in Elementor. So you can set the single or the archive page as `main`.

See more here: https://elementor.com/blog/introducing-full-site-editing/

Thanks

**Comment by besweeet** [comment]
@arielk - That works great for archives and other types of templates, but it is not a solution for individual pages. As mentioned, you can set the `main` tag for multiple sections, but pages are only supposed to have a single `main` tag.
