### ISSUE TITLE
Unable to switch Font Awesome 4 Support  to OFF ! 

### ISSUE THREAD

**Issue by spac-em** [elementor/elementor#11288]
gif : https://d.pr/i/BTrEB2/p5OhyPYEqm

Bare installations.

**Comment by lior-sh** [comment]
Hi @spac-em,
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
