### ISSUE TITLE
Reverse or reset entrance (css) animations when scrolling up...

### ISSUE THREAD

**Issue by pietrolicata** [elementor/elementor#11284]
Hello,

Is there any way to play "reverse entrance animation" when scrolling up?
OR just resetting the animations when going to the top would already be great...

Thank you for your amazing product anyway!

## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
