### ISSUE TITLE
Elementor enqueues all scripts used on a site, not just those required by a page

### ISSUE THREAD

**Issue by yourpropertyexpert** [elementor/elementor#11293]
This is NOT a duplicate of #8572.

8572 is a request for a mechanism to disable enqueuing of selected scripts globally (because those scripts have been included as a bundle). 

This is a request for a more sophisticated mechanism to allow scripts to only be included on selected pages... namely the pages that use the components in question.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

On sites that include a large number of widgets, all the scripts for every widget are enqueued at pageload, not just those required for the widgets that happen to be on that page.

**Describe the solution you'd like**

Instead of the code enqueuing every script, there should be a mechanism to only enqueue the scripts that are actually used on the page.

**Describe alternatives you've considered**

I have considered the mechanism outlined in #8572. It does something similar, but different.

**Additional context**

**Comment by MichaelDarko** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by libbeydesign** [comment]
+1

**Comment by kurtosys-sunil** [comment]
+1

**Comment by ridinghoodmedia** [comment]
+1

**Comment by shilo-ey** [comment]
Hey @kurtosys-sunil 

Thanks

I want to refer you to the latest version of Elementor and Elementor Pro, which includes an experiment called "Optimized Asset Load" and should do exactly what you asked for.

In addition, we are about to release a beta for Elementor v3.3.0 which handles the same for widgets CSS files.

Let us know what you think.


Thanks
