### ISSUE TITLE
Elementor pro not working well with my theme CASSIO 

### ISSUE THREAD

**Issue by Bravark** [elementor/elementor#11296]
I have this Premium theme CASSIO that works fine with the free version of elementor theme has its own elementor widget too both static and dynamic but each time I install elementor pro the dynamic widget and even some static keeps loading forever in the front end, but immediately I uninstalled the elementor pro it starts working again.. 

Thank you..

**Comment by lior-sh** [comment]
Hi @Bravark,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
