### ISSUE TITLE
Elementor's Device Sections - The 'muted' issue

### ISSUE THREAD

**Issue by webndesign** [elementor/elementor#11300]
Hi there folks, 

I have scoured the web for answers to this issue I'm seeing while editing in Elementor. A lot of you may flag me for duplicate content, but really, this is not duplicate content!

I'm talking about the sections in Elementor and how they behave when viewing the content in between desktop and mobile devices. 
I read in a similar thread about how this issue of 'seeing different sections when working in mobile' for example and vice-versa were addressed in v2.8. How they are now 'muted', so when I create a section on mobile I see it as muted in desktop. 

Well, in my opinion, this was partly addressed. The point is not to still see them, even muted. This is still confusing and prohibits from a clear design perspective. 
The point is to have them completely hidden unless you're viewing the particular device they were designed for!

Does any of you know if this is going to be addressed any time soon??
Thank you for letting me know.

**Comment by lior-sh** [comment]
Hi @webndesign,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by webndesign** [comment]
Oh great - thank you for letting me know how to post but not an actual acknowledgement of my issue, and I'm sure, other ppl's issue!
