### ISSUE TITLE
Menu Cart Widget Styling and Functionality

### ISSUE THREAD

**Issue by ockoe** [elementor/elementor#11309]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

 Woocommerce Menu Basket, added in the header, is not adopting some styling when editing in elementor. For example the text colour does not change, button styling does not replicate outside of elementor (on live page - localhost) and this is the same for 'hover' styling. 

Also, when a product is in the cart and the x is clicked to remove it the whole webpage refreshes... This seems like an ajax issue. 

## Steps to reproduce

OceanWP Theme with child + Ocean extra plugin
Elementor pro (latest) + essential adding for elementor + rank math + Real media library (free) + Woocommerce

Created a header using elementor pro - includes nav menu, site logo and menu basket. 
Simple product (service, not a physical product or download) - add to cart button on webpage.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.4.2 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.24.0
	MySQL version: MySQL Community Server (GPL) v5.7.26
	PHP Version: 7.4.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: http://localhost:8888/ockoe
	Home URL: http://localhost:8888/ockoe
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.7.8.1584454221
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.8.2
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

== Active Plugins ==
	Child Theme Configurator
		Version: 2.5.2
		Author: Lilaea Media

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 3.9.4
		Author: WPDeveloper

	Ocean Extra
		Version: 1.6.2
		Author: OceanWP

	Rank Math SEO
		Version: 1.0.42.3
		Author: Rank Math

	Real Media Library (Free)
		Version: 4.7.10
		Author: devowl.io

	WooCommerce
		Version: 4.1.0
		Author: Automattic

== Elements Usage ==
	
	footer : 3
		form : 1
		heading : 3
		sitemap : 1
		social-icons : 1
		text-editor : 3
	header : 3
		icon-list : 1
		nav-menu : 4
		social-icons : 1
		theme-site-logo : 3
		woocommerce-menu-cart : 1
	page : 2
		button : 8
		divider : 2
		eael-creative-button : 3
		eael-cta-box : 2
		eael-feature-list : 6
		eael-pricing-table : 12
		eael-testimonial : 2
		heading : 21
		icon : 9
		icon-box : 1
		image : 2
		image-carousel : 4
		spacer : 15
		text-editor : 15
	section : 4
		button : 1
		form : 2
		heading : 4
		image : 1
		nav-menu : 1
		sitemap : 1
		social-icons : 1
		text-editor : 4
		theme-site-logo : 1
	wp-post : 3
		button : 3
		heading : 6
		image : 11
		spacer : 14
		text-editor : 11
	wp-page : 10
		button : 7
		divider : 2
		eael-feature-list : 1
		eael-info-box : 9
		eael-pricing-table : 3
		eael-progress-bar : 3
		eael-testimonial : -6
		form : 2
		gallery : 1
		heading : 16
		icon : -12
		icon-box : 12
		image : 17
		image-box : 1
		image-carousel : 1
		menu-anchor : 1
		nav-menu : 1
		portfolio : 1
		social-icons : 1
		spacer : 32
		testimonial-carousel : 4
		text-editor : 32
		theme-site-logo : 1
		video : 1
		wc-add-to-cart : 2

== Log ==
	
PHP: showing 4 of 4PHP: 2020-03-19 11:58:01 [notice X 1317][/Applications/MAMP/htdocs/Web Design & Management/wp-content/plugins/elementor/includes/base/controls-stack.php::1447] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-23 17:44:58 [notice X 7][/Applications/MAMP/htdocs/ockoe/wp-content/plugins/elementor/includes/managers/image.php::88] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-04 23:31:27 [notice X 4][/Applications/MAMP/htdocs/ockoe/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::142] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-05 19:55:18 [error X 4][/Applications/MAMP/htdocs/ockoe/wp-content/plugins/elementor/core/base/base-object.php::40] Uncaught Error: Using $this when not in object context in /Applications/MAMP/htdocs/ockoe/wp-content/plugins/elementor/core/base/base-object.php:40
Stack trace:
#0 /Applications/MAMP/htdocs/ockoe/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Woocommerce/Checkout/Woo_Checkout_Helper.php(332): Elementor\Core\Base\Base_Object::get_settings()
#1 /Applications/MAMP/htdocs/ockoe/wp-includes/class-wp-hook.php(287): Essential_Addons_Elementor\Elements\Woo_Checkout::checkout_order_review_template(Object(WC_Checkout))
#2 /Applications/MAMP/htdocs/ockoe/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /Applications/MAMP/htdocs/ockoe/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /Applications/MAMP/htdocs/ockoe/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Woocommerce/Checkout/Woo_Checkout_Helper.php(487): do_action('woocommerce_bef...', Object(WC_Checkout))
#5 /Applications/MAMP/htdocs/ockoe/wp-content/plugins/essential-addons-for-e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2020-03-19 12:10:59 [error X 557][http://localhost:8888/WebDesign&Management/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2020-03-19 13:22:25 [error X 11][http://localhost:8888/WebDesign&Management/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.3.2:12:3796] undefined is not an object (evaluating \'delete this.obj._listeners[this.id]\') 
JS: 2020-03-20 15:36:09 [error X 1][http://localhost:8888/WebDesign&Management/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:31:206149] undefined is not an object (evaluating \'this.manager.getCurrentPageView().model.id\') 
JS: 2020-04-24 15:05:18 [error X 92][http://localhost:8888/ockoe/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.9.3:2:55741] undefined is not an object (evaluating \'t.gallery.setSettings\') 
JS: 2020-04-25 09:20:15 [error X 2][http://localhost:8888/ockoe/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:70602] Can\'t find variable: elementorFrontend 

Log: showing 2 of 22020-03-25 16:45:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-04-22 15:10:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!
