### ISSUE TITLE
The vanilla javascript events for popups no longer work

### ISSUE THREAD

**Issue by pryley** [elementor/elementor#11306]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

There is an existing issue #10690 , but it was closed without addressing the vanilla javascript issue described here.

- [x] The issue still exists against the latest stable version of Elementor.

## Description

https://developers.elementor.com/elementor-pro-2-7-popup-events/

The developer documentation describes two ways to listen for popup show/hide events:

**Vanilla javascript version:**

```js
document.addEventListener( 'elementor/popup/show', () => {
	// do your tracking here
} );
```

**jQuery version:**

```js
jQuery( document ).on( 'elementor/popup/show', () => {
	// do your tracking here
} );
```
However, the Vanilla event no longer works.

## Steps to reproduce

Add a vanilla javascript event listener and open a popup.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

N/A

**Comment by NatalieMac** [comment]
I'm having this issue as well. Trying to listen for the vanilla JS event documented here: https://developers.elementor.com/elementor-pro-2-7-popup-events/ but only the jQuery event fires. No vanilla JS event ever fires.

Tried contacting support, but was told "we can't provide support for development/custom code issues". Seems as this is in the documentation and not working, it should be supported.

**Comment by pryley** [comment]
`if ('undefined' !== typeof jQuery) {
    jQuery(document).on('elementor/popup/show', function (ev) {
        // do stuff here
    })
}`
