### ISSUE TITLE
Add a rotate slider in the image widget

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#11303]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I often need to rotate the image widget to style my designs.

**Describe the solution you'd like**

Just like with the icon widget, I'd like a slider to rotate the image in the style tab.

**Describe alternatives you've considered**

Using advanced CSS, but that's not convenient, and really hard to deal with custom CSS if I want a different image rotation for tablet or mobile. 

Custom CSS is also not user friendly is my clients want to simply rotate an image in a post.

**Additional context**

If we have a rotate slider in the icon widget, why not add it also to the image widget? Shouldn't be that hard.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12451, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
