### ISSUE TITLE
PDF export of Elementor page

### ISSUE THREAD

**Issue by cpanfilio** [elementor/elementor#11311]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There are occasions when we need to share our **internal** webpages (long form stories) with vendors. Currently we use Safari print to PDF function with the maximum page length (200 inches. note: some of our stories are 7 pdf pages even at the max PDF length.) Unfortunately, some widgets don't show up in the PDF. (empty image for slideshow (no placeholder single image) and galleries)

**Describe the solution you'd like**
We would like to export page to pdf or a self contained digital booklet of some kind. 

**Describe alternatives you've considered**
Alternative solution (pdf print) mentioned previously. 

**Additional context**
We're long form storytellers, as corporate historians. :)

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
