### ISSUE TITLE
PHP Form Support

### ISSUE THREAD

**Issue by mcpab** [elementor/elementor#11313]
Hello

I was redirected to this forum by the customer service.

I would like to know whether it is possible to use the form capabilities to send a form to the server and process the data with a Wordpress PHP action. I have been looking everywhere but I could not find anything. 

Alternatively, I would have used textfield and regular buttons, but I did not find a way to set the ID of the inputs in a form.

thanks

**Comment by shilo-ey** [comment]
Hi @mcpab 

You can use [Elementor Forms API](https://developers.elementor.com/forms-api/), or create a [Custom Form Action](https://developers.elementor.com/forms-api/custom-form-action/) to achieve your goal.

There are many examples described in this GitHub so look for your need in here before writing your own.

Thanks
