### ISSUE TITLE
[feature request] Add an Option to show Category or Tags on Post Widget with classic skin

### ISSUE THREAD

**Issue by fcungurlu** [elementor/elementor#11314]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Our website is for publishing articles of a think-tank/research institute. Therefore, there are lots of posts and categories. We want to show what categories those posts are from but we can only do that when we use the "Cards" skin in post widgets. However, customization in the "Cards" skin is limited and we want to specifically use the classic skin. We cannot show tags or categories on Post Widget with the classic skin. It is very important for us to make sure that our readers can see what categories those posts are from before clicking and opening the post.

**Describe the solution you'd like**
We would like to be able to show tags or/and categories on post widgets with classic skin. With the "Cards" skin the tags can be shown over the featured picture by adding a 'badge'. The same can be done with the classic skin. Or, it would be ideal to add "categories' or "tags" option in Meta Data. It would be way easier and useful for us.

![Annotation 2020-05-06 162914](https://user-images.githubusercontent.com/64927577/81225186-d21a9a00-8fb6-11ea-989e-e89e63d2601b.png)

**Comment by gene-smith** [comment]
@fcungurlu I'm in the same exact boat as you. I also work at a research-heavy organization and absolutely need the tag or category to be displayed within the post widget. The only change I would make is to have the tag/category displayed above the title and it should be clickable to an archive page listing all of the posts related to that tag/category.

**Comment by TomRaraAvis** [comment]
this is what you are asking for #4440

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
