### ISSUE TITLE
Add more open options to Menu Cart widget

### ISSUE THREAD

**Issue by Gapito2** [elementor/elementor#11312]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**THIS IS A REQUEST**

**What problem is your feature request going to solve? Please describe.**
The Menu Cart widget has, right now, 1 only open style: Off-Canvas style. It would be nice if it's possible to add more options to this feature and display the cart in differerent ways: a dropdown box (like the Astra or Ocean theme menu cart default open style), a full-page cart, etc... Is up to you to think more and beautiful options ;)

**Describe the solution you'd like**
Add more options to the widget Settings to change the style of opening the menu cart item.

**Describe alternatives you've considered**
No alternatives. I can only suggest to check other open styles like Astra or OceanWP menu mini carts.

**Additional context**
Example of dropdown cart:
![Captura de pantalla 2020-05-06 a las 20 36 19](https://user-images.githubusercontent.com/33321460/81215272-6269d680-8fd9-11ea-8a69-f11023a48226.png)

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!

**Comment by Gapito2** [comment]
Thank you! 👍  :D
