### ISSUE TITLE
Mobile menu issue with expanding and closing submenu items

### ISSUE THREAD

**Issue by lucianka18** [elementor/elementor#11325]
The problem is that on mobile menu when I open a submenu item and then I want to close just that same submenu item it closes the whole menu item under which the submenu item belongs. Is it possible to make it that when I open the submenu item then I can close just that same submenu item and all others will stay open?

**Comment by lior-sh** [comment]
Hi @lucianka18,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
