### ISSUE TITLE
Section video-background consume a lot of traffic

### ISSUE THREAD

**Issue by borslava** [elementor/elementor#11320]
When I set the local video-file as background of section, it is start shown in a loop in Elementor's control panel, as preview. At the beginning of each cycle, it is downloading from the server again. It is consumes a lot of traffic, even if the **cache are active on server side**. Fix this please.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
