### ISSUE TITLE
RTL Theme styler line-height (simple fix) [BUG REPORT]

### ISSUE THREAD

**Issue by bentalgad** [elementor/elementor#11323]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Simple And short
When using RTL try to set theme styler's typography line height and you can't!

The reason is that in the "front-end-rtl.css" file you have set:
`.elementor-widget-heading .elementor-heading-title {
  line-height: 1;
}`

which overrides the line height.

**Comment by lior-sh** [comment]
Hi @bentalgad,

Thanks for reporting, this issue is duplicate with #10649.

Thanks.
