### ISSUE TITLE
⛔ 🚀 Feature Request: Hover Propagation Trees 

### ISSUE THREAD

**Issue by voidMike** [elementor/elementor#11328]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
During page building, it is sometimes desirable for a child's hover effect to trigger when the mouse is placed on the parent element but outside of the child element. For example, say I have a section with an image and some text below it ( or to the side ), I might decide that hovering on either the image or the text should give the image an overlay **AND** change the text color. Currently I can only have the overlay happen when the image is hovered, and text color change when the text is hovered, but not both at the same time regardless of which one of them is hovered.

**Describe the solution you'd like**
A solution for this that I had in mind would be to add a tree listing (similar to the way directories are listed) of all children elements, columns, inner sections, etc. and an option to define which inner section and elements will behave as if they are hovered if the parent is hovered.
![image](https://user-images.githubusercontent.com/12560261/81482863-5a5ca180-923a-11ea-8d55-06932d2b9f56.png)
In this mock-up example, the first half shows the tree listing on the left, and the page builder on the right with its elements. 
The second half shows some elements marked with a red circle. The idea is if I hover anywhere inside the red box, the hover effect should happen on all the marked inner elements. The unmarked ones would only have hover happen if directly hovered of course. This would let the feature be powerful yet still quite flexible.
This example assumes that the red box is the page section and that it has been selected for editing. However the feature should also work by selecting any inner section, in which case the tree listing will appear with that section as the root of the tree.

I am unsure whether the implementation should rely on scripting to accomplish the effect or generated CSS. I am unsure of the performance impacts of either choice, but perhaps a toggle option between CSS and JS could be added to allow simpler effects to use just CSS, and more complicated ones JS (if larger complicated CSS selectors would negatively impact site performance).

Since inner sections can have their own propagation trees on top of parent section having theirs and they may not necessarily follow the same paths, I think that inner section's tree should override the propagation behavior for that branch, if it's directly hovered. I don't see majority of uses ever getting this complex, but it is certainly possible.

Let me know if there are any questions, I am happy to try and explain this further if anything is left unclear.

**Comment by nicholaszein** [comment]
Hello @voidMike,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
