### ISSUE TITLE
Not compatible with the last update of WooCommerce V4.1.0

### ISSUE THREAD

**Issue by YitongM** [elementor/elementor#11321]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I just updated WooCommerce to V4.1.0 and then I had issue to edit my "Shop" page. The preview could not be loaded. I can only edit it under Safe Mode. 
I did your step by step debugging and found out that it's the plugin WooCommerce that caused this. Considering I can't abandon WooCommerce, either Elementor. I'm pretty well stucked. Please help me!
Thanks a lot!

## Steps to reproduce

1. Update to WooCommerce v4.10. 
2. In WooCommerce > Settings > Products > set a shop page
3. Try to edit that shop page you just set up. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
https://pastebin.com/hG065KGf
</details>

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
