### ISSUE TITLE
Admin Toolbar Not Showing

### ISSUE THREAD

**Issue by philzilla86** [elementor/elementor#11327]
The Admin Toolbar is not showing but when i disable the Pro version it works fine

Any ideas anyone?

**Comment by lior-sh** [comment]
Hi @philzilla86,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
