### ISSUE TITLE
✔️ 🚀 Feature Request: Support unitless line-height

### ISSUE THREAD

**Issue by nyordanov** [elementor/elementor#11335]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently `line-height` can only be set in `px` or `em`:

![image](https://user-images.githubusercontent.com/192220/81501545-832b7800-92c8-11ea-88ae-b4c6889776ed.png)

 However, unitless values are the recommended best practice, for reasons best described on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values

**Describe the solution you'd like**
Add an option to set `line-height` without an unit.

**Describe alternatives you've considered**
There is no alternative. Unitless values are the only ones which don't break inheritance.

**Comment by swinggraphics** [comment]
This is a thorn in my side on every elementor site I build. This is one of those things that makes it clear Elementor is not built for real-world usage.

**Comment by forrestkirby** [comment]
I second this feature request. Some default line hieghts in Elementor are set unitless. Now if you want to set the same line height for some elements like body (defualt 1.5) and buttons (default 1) , you have to set both to a value in em or px instead of being able to simply set button to 1.5.

**Comment by theavic** [comment]
It's been 2 years since this was flagged, is there an update on this?

**Comment by rami-elementor** [comment]
Hi @nyordanov 

When using unitless value in `line-height`, the browser simply multiplies the value by the element's font size. it's equal to using `em` units.

After a long review we decided not to add this feature to our roadmap. Please use `em` units instead.

**Comment by forrestkirby** [comment]
@rami-elementor I think that you are wrong, using `em` is not equal to using unitless numbers when it comes to inheritence. Please check the example in the section [Prefer unitless numbers for line-height values](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#prefer_unitless_numbers_for_line-height_values) on the MDN page.

**Comment by black-eye** [comment]
:-( Elementor's usual solution - few years od decision-making and then do nothing or something usesless :( 
How difficult would it be to add a "unitless" option and let experienced users input whatever they want, including the units?

**Comment by rami-elementor** [comment]
> @rami-elementor I think that you are wrong, using `em` is not equal to using unitless numbers when it comes to inheritence. Please check the example in the section [Prefer unitless numbers for line-height values](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#prefer_unitless_numbers_for_line-height_values) on the MDN page.

Seems like you are correct.

**Comment by forrestkirby** [comment]
Thanks for reopening the issue!

**Comment by ariestwn** [comment]
waiting for this

**Comment by rami-elementor** [comment]
**UPTADE:**

We are currently working on a feature that will allow you to choose different units in various controls.

I can't tell you when it will be released as it is still under development and we need to take into account backwards compatibility issues, integrations with 3rd party addon and other factors.

But when this feature is released, you will be able to set unitless values.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

There is an option to select a custom unit for the `line-height`, and when you do that, you'll be able to add your unitless values. 😉 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
