### ISSUE TITLE
More Template Builder Display Condition options

### ISSUE THREAD

**Issue by marcel-za** [elementor/elementor#11334]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Template Builder's Display Conditions are limited to Entire Site, Singular, Archive & WooCommerce. There should be more options for Display Conditions.

**Describe the solution you'd like**
More options for Templates' Display Conditions. Possibly "if url contains".

**Describe alternatives you've considered**
I've solved the problem using CSS. That is, if the template is displayed for example on the WooCommerce Checkout page, hide certain widgets using the .woocommerce-checkout class.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
