### ISSUE TITLE
Blend-mode on Headline widget not recognising page background image when using Page Builder.

### ISSUE THREAD

**Issue by isjeremy** [elementor/elementor#11337]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Text Blend modes don't seem to work against page background images when inside the Elementor Builder. Viewing the final published page doesn't have the issue, just seems to be when using the page builder.

## Steps to reproduce

1. Set a page background
2. Create a new headline
3. Set the colour
4. Set the blend mode (I set mine to difference)

This is what Elementor Page Builder displays
https://i.imgur.com/1AuMMbN.png

This is what the actual page displays
https://i.imgur.com/brYfWXy.png

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

_Sorry, had no time to do all the above._
## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: (Ubuntu) v5.6.32
	PHP Version: 7.2.29-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 460M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: http://lostcause.flywheelsites.com
	Home URL: http://lostcause.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 460 MB
	Memory limit: 200M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Melbourne
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.9
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.3
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.17.22
		Author: Gravity Forms

	Invisible reCaptcha
		Version: 1.2.3
		Author: Mihai Chelaru

	Nested Pages
		Version: 3.1.10
		Author: Kyle Phillips

	Redirection
		Version: 4.7.1
		Author: John Godley

	Smush
		Version: 3.6.1
		Author: WPMU DEV

	Style Kits for Elementor
		Version: 1.6.7
		Author: AnalogWP

	User Role Editor
		Version: 4.54
		Author: Vladimir Garagulya

	Yoast SEO
		Version: 14.0.4
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		form : 1
		social-icons : 1
		spacer : 1
		text-editor : 1
	header : 1
		nav-menu : 1
		spacer : 1
		theme-site-logo : 1
	wp-page : 5
		heading : 4
		html : 2
		icon : 1
		spacer : 1
		text-editor : 4

== Log ==
	
PHP: showing 2 of 2PHP: 2019-07-11 07:11:15 [notice X 8][/www/wp-content/plugins/elementor/includes/controls/groups/base.php::493] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-11 17:14:03 [notice X 1][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 252019-09-14 02:31:31 [info] Elementor/Upgrades - _v_2_7_0_rename_document_types_to_wp Finished 
2019-09-14 02:31:31 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-09-14 02:31:31 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-09-14 02:31:31 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-09-14 02:31:31 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-09-14 02:31:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.7.1',
)]
2019-09-14 02:31:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.7.1',
)]
2019-09-14 02:31:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.12',
  'to' => '2.6.5',
)]
2019-09-23 04:10:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.1',
  'to' => '2.7.2',
)]
2019-11-12 03:59:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.2',
  'to' => '2.7.5',
)]
2019-11-12 04:01:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.5',
  'to' => '2.7.3',
)]
2020-02-21 03:08:05 [info] elementor::elementor_updater Started 
2020-02-21 03:08:05 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-02-21 03:08:06 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-02-21 03:08:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.9.2',
)]
2020-02-21 03:08:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.9.2',
)]
2020-02-21 03:08:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.4',
)]
2020-04-20 02:11:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.7',
)]
2020-04-20 02:12:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.9.3',
)]
2020-04-28 10:13:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]

JS: showing 1 of 1JS: 2020-05-11 07:14:03 [error X 1][http://lostcause.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.8:2:187452] Cannot read property \'map\' of undefined 

				

</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
