### ISSUE TITLE
Hiding Section Makes it Unselectable on Affected Viewport

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#11342]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I hode the whole section on a certain viewport, it grays out (which is fine) but it also becomes unselectable and thus uneditable on affected viewport. In Theory, when I select hide on all viewports, I wouldn't be able to edit it at all.

This isn't happening for the single widgets, so I suppose it isn't intended behaviour.

Side note: It would be more distinct, if the hidden content was hidden completely, not just greyed out. The hidden content could be replaced by a small eye symbol or some other indicator, which could eventually toggle the content on/off for editing.

## Steps to reproduce
Select a sectoin and make it hidden on viewport you are currently editing - you won't be able to select it anymore.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
Long time but this feature has been added to Elementor v3.3.0

Thanks!
