### ISSUE TITLE
Self Hosted video player option missing

### ISSUE THREAD

**Issue by gangesh** [elementor/elementor#11346]
I tried Elementor video widget doc and it shows self hosted video option:
https://elementor.com/blog/2-1-new-features/

Using Pro version I see Youtube, Vimeo and Wistia option. 
Am I missing something obvious or self-hosted video option is removed completely?

**Comment by lior-sh** [comment]
Hi @gangesh,

Thanks for reporting.
In order to upload a self-hosted video you need to do the steps below:
1. D&D a video widget to a new section
2. Content tab > Click on Source and select the Self Hosted option
3. Click on 'Choose File' and upload the file

Thanks.

**Comment by gangesh** [comment]
![Screenshot 2020-05-12 at 7 14 26 PM](https://user-images.githubusercontent.com/3194143/81699351-d77b5700-9484-11ea-883c-bc3eec28d7f4.png)

Please check there is no option for Self Hosted in Video type area.

**Comment by lior-sh** [comment]
Hi @gangesh,
Thanks for reporting, *we couldn't replicate the issue.


Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

*As you can see it's working fine on our side:
![video1](https://user-images.githubusercontent.com/59225438/81701188-574bf600-9472-11ea-8a7b-ff40aafe3647.JPG)

**Comment by gangesh** [comment]
I see options properly now. Nothing changed. Probably browser cache after plugin updated to latest version. 
Thanks!
