### ISSUE TITLE
I'd like template items consolidated into a single "kit"

### ISSUE THREAD

**Issue by eswagar** [elementor/elementor#11341]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated finding all pieces of a template "kit" when searching Elementor Templates and needing to search multiple times to find all items.

I wanted to use the "Magazine" "template kit", so I needed to search for "magazine" in Pages, Posts, Archive,  etc until I had all items.  Some items, such as Posts and Archives, had multiple selections.

**Describe the solution you'd like**
The solution would be to group all templates of a given "kit" to allow for simple "demo" import.  If this solution is unworkable, naming all items of a template "kit" as a group would be minimum (see the magazine template as an example.)

**Describe alternatives you've considered**
Envato Elements

**Additional context**
As an example there is only 1 template item available for "Business" in Pages, see attachment.  But, if you were to do the same in "Digital Agency" you'll see multiple Pages.
<img width="1229" alt="Homepage - Business - Page" src="https://user-images.githubusercontent.com/65191813/81604915-4af26b00-9396-11ea-80d8-624ebd4d16c6.png">

**Comment by rodolphebertozzo** [comment]
+1

**Comment by shilo-ey** [comment]
This feature has been added to Elementor v3.3.0

Feel free to update

Thanks!
