### ISSUE TITLE
Carousel Image to replace main image (not open in new window) issue

### ISSUE THREAD

**Issue by herdsupply** [elementor/elementor#11344]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am trying to get a product image to display correctly and knowing how to fix it will stop me from asking you how to do it for the next 20 items.

**Describe the solution you'd like**
I would love to have a product photo at the top and each thumbnail image to enlarge to take its place (I believe this is standard for e-commerce, but here is one example: https://elizabethsuzann.com/collections/all-products/products/sleeveless-kara-snap-dress-midweight-linen?variant=29852558098520), rather than have each thumbnail enlarge to be a huge photo that takes up the entire screen. 

**Describe alternatives you've considered**
I started with a big image and a gallery below (this results in huge images when clicked on), and then I tried using the media carousel. However, the aspect ratio looks wrong in the main photo (although it is fine in the thumbnails) and when I turned off the infinite loop, it disabled the ability to enlarge the thumbnails.

**Additional context**
Add any other context or screenshots about the feature request here. Below is an example of what I've tried – slideshow at the top and the main image with a gallery below. Neither is exactly right. Please help! Can you please help me determine what I need to use (drag and drop, code, or anything else) I need to include to achieve the Elizabeth Suzann effect? Thank you in advance!
<img width="862" alt="Screen Shot 2020-05-11 at 6 36 03 PM" src="https://user-images.githubusercontent.com/65198058/81618873-4b026300-93b6-11ea-8932-4469602afbb7.png">

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
