### ISSUE TITLE
Popup Trigger Not Triggering

### ISSUE THREAD

**Issue by ClickGenie** [elementor/elementor#11350]
'On page exit intent' should trigger a popup when the mouse moves out o fthe webpage but it is not triggering the popup.

**Comment by lior-sh** [comment]
Hi @ClickGenie,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
