### ISSUE TITLE
Add radius to the google map widget

### ISSUE THREAD

**Issue by gavpedz** [elementor/elementor#11359]
It would be great to see the option to add a radius to the map. For example, at the moment if I type in Southampton, United Kingdom I get a nice red border around the are. We work with a few areas based business and they like to be able to display an area radius in which they work. This is ok if it is one town like I mentioned but if they cover several close towns or areas this doesn't work so may if they could put the main location and then add a radius they work it which would then show the red boarding on the map that would be great.

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!

**Comment by IlPizza79** [comment]
Hi, what you mean "This issue has been resolved in Elementor v3.1.0"?
I can't find an option to add the "radius" around the map marker option in my Google Map Widget :-|

**Comment by daniilicic** [comment]
Lol, @IlPizza79 they added BORDER RADIUS to the map widget and they call this issue "Closed". I don't think they even read the original post 😂

**Comment by IlPizza79** [comment]
Wow, that's almost a joke... but it's not funny :-(
