### ISSUE TITLE
SVG icon instead of eicons font

### ISSUE THREAD

**Issue by mrbenjaminjo** [elementor/elementor#11361]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by mrbenjaminjo** [comment]
It's impossible to replace hardcoded icons that are displayed throughout the front end. These include, but are not limited to:

- The hamburger open/close icon in responsive nav.
- The social media icons in the social widget.
- The social share buttons widget.
- The popup close icon.

Various CSS/code hacks allow changes to be made, but this methodology is not commensurate with your "iconic" strategy.

Perhaps merge the related, but less detailed #10164 and #9177 into this, and then please solve quickly - it's a major pain!

**Comment by princesshorsepower** [comment]
@mrbenjaminjo thank you for opening this. Actually I was about to do the same very soon. The icon strategy of Elementor is really messed up for some parts.

- **Hamburger** is loaded from eicons (79k, hardcoded)
- **Submenu** uses the chevron (font awesome solid 75k, hardcoded)
- **Search** Form Widget, uses a search icon (font awesome solid, hardcoded)
- eicons is a mixture of backend and frontend icons (compare this to e.g. WP Astra Theme, their icon font has, I guess, 4k instead of 79k)

Which means, if you use a menu with submenu indicator and/or search icon and hamburger on mobile, you have and additional load of 154k... can you imagine this?

My suggestions to Elementor team: 

1. Per default, use only eicons for your Widgets, do not mix eicons and font awesome
2. Keep this eicons font to a minimum, separate backend and frontend icons into different font files
3. Make icons for menus replaceable with SVG inline icons

**Comment by black-eye** [comment]
⬆️ Oh yes pls, this one! 

Using the whole Font Awesome font just for several arrows is neither "awesome", nor "iconic".  😉  
Sure, we can deque Font Awesome, but it's nowhere near user friendly.

**Comment by MichaelDarko** [comment]
+1

Just another area where Elementor is amateurish when it comes to performance optimization.

If there was strong focus on performance, this could never happen.

**Comment by ArneSaknussemm** [comment]
> 
> 
> ⬆️ Oh yes pls, this one!
> 
> Using the whole Font Awesome font just for several arrows is neither "awesome", nor "iconic". 😉
> Sure, we can deque Font Awesome, but it's nowhere near user friendly.

How do you deque icons fonts?

**Comment by micpurr** [comment]
**+1**

**Comment by OvidiuZeicu** [comment]
Yes, there are plenty of instances when FontAwesome is not needed at all. Also, the dequeue code in the docs doesn't work, I'm using OceanWP + Elementor Pro, that code does nothing.

**Comment by MichaelDarko** [comment]
While working on this, please also solve bugs related to icon loading: #9907

**Comment by yorkfrog** [comment]
> > arrow_up Oh yes pls, this one!
> > Using the whole Font Awesome font just for several arrows is neither "awesome", nor "iconic". wink
> > Sure, we can deque Font Awesome, but it's nowhere near user friendly.
> 
> How do you deque icons fonts?

@ArneSaknussemm - see elementor help article below - has other useful ideas for improving performance too.

https://docs.elementor.com/article/286-speed-up-a-slow-site

-C

**Comment by shimsa** [comment]
+1

**Comment by btward79** [comment]
+1
Was really surprised to see eicons loaded along with font awesome.

Love Elementor, but I think the focus needs to be aimed toward performance at this point. We only use a couple icons and would rather not load a whole library over it. Thanks

**Comment by pierpa010** [comment]
+1

**Comment by jormeer** [comment]
+1 this should be a no brainer.... This wil reduce page size a lot!

**Comment by megaturba** [comment]
+1 please, just one icon to replace

**Comment by simonvanoordt** [comment]
+1

**Comment by ZENwww** [comment]
+1, please remove eicon or give us a option to use only icons we need (hamburger, chevron or search icons).

**Comment by alexcumbers** [comment]
When will this be looked at, can someone from admin please comment?

**Comment by wwdes** [comment]
Chevron icons in Sliders widget are also not replaceable.

Elementor should give full control over each and every icon that will be seen on frontend, letting replace them with icons from custom icons, uploaded SVG’s or url’s to SVG files.

Then we can simply turn off eicons and fontawesome and enjoy much improved site performance.

**Comment by alexcumbers** [comment]
Agreed, all we need on front end is hamburger, social icons

**Comment by MPHood** [comment]
How is it possible that such a simple Task is taking this long?

**Comment by alexcumbers** [comment]
> How is it possible that such a simple Task is taking this long?

This is being considered, but this change needs to happen anywhere an icon can be used, so will take time. Changes are coming in the 3.2 beta, and beyond.

**Comment by oliveandlake** [comment]
Agreed. Remove eicons completely! It's possible to dequeue them and then use CSS to add icons for the mobile menu toggle, etc. But it would be nice to not have to do this! Removing eicons sees a significant improvement in Google's PageSpeed test for mobile.

**Comment by 79ho3ein** [comment]
+1

**Comment by alexcumbers** [comment]
@shilo-ey Can you comment about improvements coming to the management of / alternative to Eicons, and use of SVG's?

**Comment by alexcumbers** [comment]
@avivu Could we have some feedback / comments on icons management / use of SVG please?

**Comment by PPjev** [comment]
+1

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by deepwaterpixel** [comment]
I just checked the changelog and saw this explanation for the inclusion of this issue in the 3.5.0 update:

>Tweak: Adjusted Inline Font Icons experiment to work with eicons library and save up to 110KB of asset loading (#8572, #11361)

Is this what was requested?  I was also under the impression that a Nav Toggle icon custom icon option would be introduced...
