### ISSUE TITLE
We can't disable background image for responsive devices . 

### ISSUE THREAD

**Issue by mamunur105** [elementor/elementor#11367]
We can't disable background image for responsive devices . Most off the time wee need to remove background image for mobile .
https://prnt.sc/sgmhi3

**Comment by lior-sh** [comment]
Hi @mamunur105,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
