### ISSUE TITLE
Migration of Link Actions to Elementor 2.9

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#11362]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
This is not an actual bug, but rather a mistake in documentation. 

I tried to update my custom widget using this tutorial: https://developers.elementor.com/migration-of-modules-to-core-in-2-9/. I needed to replace `create_action_url` by a new method `create_action_hash`, but I ended up with a fatal error.

Is this call correct?
`\Elementor\Plugin::elementor()->frontend->create_action_hash`

Because when I use ElementorPro namespace, everything works fine:
`\ElementorPro\Plugin::elementor()->frontend->create_action_hash`

I wrote a comment below the mentioned post, but it's still waiting for a moderation. And it was 3 weeks ago...

Thanks for the clarification.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rami-elementor** [comment]
@black-eye Is this issue relevant?

**Comment by black-eye** [comment]
> @black-eye Is this issue relevant?

Well, @rami-elementor, in the current version of the documentation is yet another method (which seems to be working):

`\Elementor\Plugin::$instance->frontend->create_action_hash`

But the method ` \ElementorPro\Plugin::elementor()->frontend->create_action_hash` still works as well.

So please, you tell me, what is the correct method to use...

**Comment by rami-elementor** [comment]
As mentioned [in the original post](https://developers.elementor.com/migration-of-modules-to-core-in-2-9/) :

> we split the Link Actions module up into two separate parts and moved it to the Elementor Core plugin.

`\ElementorPro\` implementation was deprecated in favor of new `\Elementor\` implementation.
