### ISSUE TITLE
Elementor Pro Post Type Slides alignment issue in Firefox

### ISSUE THREAD

**Issue by bartistiek** [elementor/elementor#11366]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

When using Posts (Elementor Pro) in slides mode on Firefox, the slide is cut-off on the right side and the previous slide is still partly visible on the left side. This issue is isolated to Firefox and is not appearing in Safari and Chrome.

## Steps to reproduce

Create a full width custom post type (loop)
Use Post type as element using "slides" option
When creating this post type element (using Firefox as the browser to produce the page), the misalignment is already visible in the backend.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

Latest versions of all plugins.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
