### ISSUE TITLE
Elementor "System Info" fails with fatal error

### ISSUE THREAD

**Issue by mwittmann** [elementor/elementor#11364]
This is a duplicate of #8194, but that's marked closed (for no good reason), so I'm opening a new issue.

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Go to "Elementor... System Info". Page says: "There has been a critical error on your website. Please check your site admin email inbox for instructions." 

## Steps to reproduce

1. In the WordPress admin dashboard, go to "Elementor... System Info".

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active. ==> fails in the same way with latest version of 2020 theme.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
Running latest version of WP (v.5.4.1) and Elementor (v.2.9.8, Pro v.2.9.4). `PHP Version 7.2.30`. As suggested on #8194 I tried:

    DELETE FROM wp_options WHERE option_name = "elementor_log";

The above makes no difference. Debug log is below:
  
    [14-May-2020 07:52:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::get_name() in /home/myhome/sites/mysite.org/wp-content/plugins/elementor/core/logger/loggers/base.php:80
    Stack trace:
    #0 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/core/logger/log-reporter.php(64): Elementor\Core\Logger\Loggers\Base->get_formatted_log_entries(20, false)
    #1 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/modules/system-info/reporters/base.php(105): Elementor\Core\Logger\Log_Reporter->get_log_entries()
    #2 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/modules/system-info/module.php(262): Elementor\Modules\System_Info\Reporters\Base->get_report('html_')
    #3 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/modules/system-info/module.php(151): Elementor\Modules\System_Info\Module->load_reports(Array, 'html')
    #4 /home/myhome/sites/mysite.org/wp-includes/class-wp-hook.php(287): Elementor\Modules\System_Info\Module->display_page('')
    #5 /home/dharmag1/sites/dharm in /home/myhome/sites/mysite.org/wp-content/plugins/elementor/core/logger/loggers/base.php on line 80

<details>
<summary>System Info</summary>
```
Uh huh. This is exactly what's not working.
```
</details>

**Comment by shilo-ey** [comment]
Hey @mwittmann 

Thanks

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

We would be able to better troubleshoot it.

thanks.

**Comment by itgiron** [comment]
Hello @shilo-ey !! I can do the same in support; I have the same error.
