### ISSUE TITLE
custom css for sitemap widget

### ISSUE THREAD

**Issue by karrolhk** [elementor/elementor#11385]
I want to use the sitemap widget to just show a list of my post tags. So, I only have 1 type of items (shown in 1 long column). How can I make this 1 column to appear in 3 or 4 columns? any custom css I could add?

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
