### ISSUE TITLE
Adding support for vimeo on-demand links

### ISSUE THREAD

**Issue by levialon** [elementor/elementor#11386]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When embedding a vimeo video link the format is:
https://vimeo.com/73369975
which works perfectly. 
but when viewing and copying shared link from vimeo on demand pages, the shared link looks like this: 
https://vimeo.com/ondemand/10percentinternational/73369975
which doesn't work.

it's not an issue when adding a video manually (you can just copy the link) but when dealing with User Generated Content and forms is becomes a real issue - asking the user to understand the url structure is too complicated. 

**Describe the solution you'd like**
vimeo widget would recognize this VOD format and embed as usual (or automatically change it to the easy, working url format) 

**Describe alternatives you've considered**
Explaining the user how to do it - bad ux;
i've written vimeo on the issue - they can't change it.

**Additional context**
Mostly problematic when you want to embed a video that is a trailer to be bought inside your website (ie catalog)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4518, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
