### ISSUE TITLE
Image paths broken after migration

### ISSUE THREAD

**Issue by Panksi** [elementor/elementor#11391]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

After migrating the Wordpress/elementor website, image paths on some images are broken.
We have tried to fix the paths in database manually but elementor overrides them. When I deactivate the elementor plugin images showup on the website and all paths are good.
path example:
![image](https://user-images.githubusercontent.com/16855132/82185703-f1d08d00-98e9-11ea-8260-151a51384ca7.png)

The issue can be reproduced on:
https://info.viselio.com/how-it-works/

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Panksi 

Thanks, please make sure you [regenerate css files](https://docs.elementor.com/article/218-i-changed-the-url-of-my-website-and-elementor-does-not-work-anymore)

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by Panksi** [comment]
@shilo-ey I am well aware that this is not a support. I am also well aware that there is a regenerate css functionality in elementor. If you look at the pritscreen closely, you will see that path to the images is something like: https://info.viselio.com/%20/https:info.viselio.com...... 
And I tried to regenerate the CSS few times and nothing happened.
so it is obviously a bug.

**Comment by shilo-ey** [comment]
@Panksi 

Thanks, but this issue is not reproducible via standard and recommended migration process.

Clearly there's an issue with the new permalink structure/base URL.

I suggest going over [this tutorial](https://elementor.com/blog/site-migration/) and if this doesn't solve your issue (or directs you to its solution) create a new issue with proper steps to reproduce.

Thanks!
