### ISSUE TITLE
Product Data Tabs Problem

### ISSUE THREAD

**Issue by angvel8** [elementor/elementor#11395]
Hello, 
I have a problem with the "Product Data Tabs" item. In the valuation section, there's a mismatch when you introduce your name and email to give an evaluation of the product. I've tried to deactivated the plugins but it still happen. 
I attached image of the problem.
<img width="1098" alt="Captura de pantalla 2020-05-18 a las 15 06 48" src="https://user-images.githubusercontent.com/65544205/82217450-b8fcdc00-991a-11ea-89fd-bd24c55e21a5.png">

Thank you all!

**Comment by lior-sh** [comment]
Hi @angvel8,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* **Isolating the problem**.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
