### ISSUE TITLE
price list widget - no link!

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#11394]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Problem
when creating a price list throught price list widget theres always a hash '#' as default link which is irritating as it causes a link with a jump to the top of the page -> this is especially annoying on moblie for users (even if they are not tremulous!).

this is no problem when you are creating the website and are aware of it as a designer - but it causes trouble for client when editing and _not_ being aware of this.

there needs to be a way to prevent elementor from inserting this standard hash/link.
thanks for any way or hint to solve this.

## Reproduce
easy to reproduce: see description ...

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## System Info
n/a

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Hi @dasigna,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by dasigna** [comment]
...???

so you're closing this because of 'missing key information' ???

sorry - but thats ridiculous.
the issue is crystal clear - everything is decribed with no need of additional 'information' ...
you could easily help or at least give a better answer if you only wanted to.

this is _really_ getting more and more dissappointing.
