### ISSUE TITLE
Media Carousel moves after click

### ISSUE THREAD

**Issue by angvel8** [elementor/elementor#11393]
Hello, 
I have a problem with the "Media Carousel" item. I added images with custom URLs but when i click to one of them the picture slides to the left before goes to the link. I'm trying to find a way to click the link without the picture moving from its original place. Is this possible?

![Media Carousel problem](https://user-images.githubusercontent.com/65544205/82212252-89e26c80-9912-11ea-9fc6-738257ab5857.gif)

Thank you

**Comment by lior-sh** [comment]
Hi @angvel8,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by Abhimanyusp** [comment]
is the problem solved or what?

**Comment by batmaninkl** [comment]
This issue needs to be re-opened. The resolution that "We try to solve a few days ago, but the infrastructure change was to risky." is not acceptable.
