### ISSUE TITLE
Motion Effects Offset and Effects Offset settings for both Tablet & Mobile

### ISSUE THREAD

**Issue by OmarBakr** [elementor/elementor#11403]
Have the option to set the Motion Effects options for both Tablet & Mobile differently...
E.g. having a nav menu on the mobile I would like it to take minimal height to maxise screen space, on a tablet I would like it to be somewhat bigger. If I would now have a secondary nav menu on some pages there's no way to offset it easily for those. Now I need to use the same main nav height in order as the offset can only be set to the same height.
Mobile Main Nav Height 90 px, Secondary Nav Motion Effects Offset would be set to 90 for it to fall right under.
Tablet Main Nav Height 130px, Secondary Nav Motion Effects Offset would be set to 130 for it to fall right under.
At the moment using for Motion Offset 90px for the mobile means it disappears on the tablet, using 130px it shows a massive gap.

**Comment by lior-sh** [comment]
Hi @OmarBakr,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by OmarBakr** [comment]
Thanks for your reply Lior. Not sure why you would close the report after replying like that as this just means a new report needs to be done again. And actually even more confused about your reply as none of the information is missing. This was not reported as bug report, for which I understand you would need that information, but it was issued as a feature request which I thought was clearly described.

But will provide the requested information as requested:

Prerequisites - Wordpress with Elementor and Elementor Pro

Steps to replicate - Create any kind of widget, section, column, inner column that allows for it to be set to sticky, head over to the "Advanced settings", go to "Motion Effects", change Sticky to either "Top" or "Bottom" and now it will show an area where you can enter a value for "Offset" and "Effects Offset".

Isolating the problem - The values currently apply to Desktop, Tablet and Mobile, there is no way to separately set the values differently depending on the viewport, like you can do for example for paddings, margins, typography, etc. In most cases the offset will be completely different on different devices. 

System info - Irrelevant.

One issue per thread  - The issue is related to Sticky items, so it could be considered one issue, unless you would require me to do a feature request for both Sticky Offset and Sticky Effects Offset.

Please find a screenshot attached of the section I am talking about.
Lemme know if you need any additional clarification.

<img width="284" alt="Screenshot 2020-05-25 20 37 43" src="https://user-images.githubusercontent.com/1358523/82833955-377fed80-9ec8-11ea-810f-f7c440dfbbc3.png">
