### ISSUE TITLE
Safari issue: Media carousel navigation arrows are visible when lightbox is open

### ISSUE THREAD

**Issue by vladarte** [elementor/elementor#11416]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Original media carousel arrows ignore z-index parameters in Safari which causes them to appear on top of lightbox.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by vladarte** [comment]
https://imgur.com/a/oVvnxMr

**Comment by lior-sh** [comment]
Hi @vladarte,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by vladarte** [comment]
If you didn't want to give this issue even a second of consideration - you could have just said so.
What could be more obvious: you open Safari browser on ANY mac and click on ANY media carousel picture, it opens in the lightbox, but the arrows that should be in the background are visible on top of the expanded picture. You would have seen it right away if at least tried.

**Comment by mu4prem** [comment]
I'm also having this same issue. You can see it in action on safari at [https://keeley.rougedigital.co.uk/](https://keeley.rougedigital.co.uk/)

**Comment by iAppleGuy** [comment]
I'm also having this same issue. Glad they dismissed it so quickly. Not sure if I will be recommending people use Elementor pro anymore.

**Comment by fabriziobuonomo** [comment]
Set this: -webkit-transform: translate3d(0,0,0); z-index: 998; in gallery arrows and then in the Lightbox set z-index: 999; -webkit-transform: translate3d(0,0,0). This will solve on Safari

**Comment by lennertdaniels** [comment]
@fabriziobuonomo, actually, that puts the arrows in a different position (lower than the vertical center).

I've had succes with adding the following to my CSS:
```
.dialog-type-lightbox {
	transform: translate3d(0,0,2px);
}
```
since the arrows have a similar `translate3d` applied, but with 1px in the Z-axis, this rule with 2px puts the lightbox on top. 
You can still see the arrows scroll overtop of the admin-bar, so it's not a permanent fix, but it's enough for visitors.

**Comment by plethoradesign** [comment]
lennertdaniels, your solution worked well for me. Thank you.
