### ISSUE TITLE
Conflict with Redux

### ISSUE THREAD

**Issue by dovy** [elementor/elementor#11418]
https://wordpress.org/support/topic/conflict-redux-framework-and-elementor/#post-12864468

I'm the owner of Redux and someone posted this on our forum. Curious if your team wishes to resolve it or not. We have millions of sites world-wide.  ;)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by dovy** [comment]
It's your loss. I'm not going to do all the ground work for your team. I'm just notifying you of a concern. If you wish to disregard 3+ million websites using Redux, that's your choice.  ;)

**Comment by shilo-ey** [comment]
@dovy I didn’t said we won’t fix it, but we have guidelines for disclosing an issue. 
From the report mentioned we can’t reproduce this issue.

Please direct him to create a new issue or contact our support, or simply provide a professional report.

**Comment by dovy** [comment]
That's what I instructed them as well. Just brining it to you attention had they not contacted you.

All the best.

**Comment by Dmwds** [comment]
Elementor  Version 3.1.4
Elementor Pro Version 3.1.1
Redux Version: 4.1.24


1. create page   step 2 switch page to canvas or elementor full width, 3. add footer or header elementor theme builder , goto page editor does not load:
