### ISSUE TITLE
Elementor Pro Attack Issue

### ISSUE THREAD

**Issue by gilcags** [elementor/elementor#11432]
Every time the Elementor website is down, the PRO versions also go down. Prompting some clients on why they don't have the PRO anymore and also hurting client trust.

This is a big liability though.

**Comment by shilo-ey** [comment]
Thank you @gilcags, 

We are aware of this issue and working on a way for providing a more reliable solution.

Rest assured that this is a TOP priority issue for us and we are treating it properly.

To be clear, the only time our service was down in the last year was tomorrow for 1 hour.

In the meantime, we strengthened our servers to keep the system up and running.


Thanks again
