### ISSUE TITLE
Only 1 column showed if I insert a gallery shortcode with shortcode widget

### ISSUE THREAD

**Issue by Iti1980** [elementor/elementor#11438]
Hello,
I'm having some issues if I try to insert a gallery shortcode by means of shortcode widget.
The shortcode is the following:
[gallery ids="1171,1172,1173" columns="3"]

The problem is that it's showed only 1 columns instead 3.
I tried to deactivate all the plugin but nothing.
Do you know anything about it?

Thanks

**Comment by lior-sh** [comment]
Hi @Iti1980,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
