### ISSUE TITLE
Functionality Request

### ISSUE THREAD

**Issue by nayelli-ovi** [elementor/elementor#11433]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

I want to know about the little animation on **plugandpixel.com**
In the background of the portfolio section 
I attached a photo. The animations are the white lines . When I select a category , the animation change, the white lines change of position . 

![IMG_4865](https://user-images.githubusercontent.com/1653960/82567599-330fa980-9b43-11ea-8751-b24617fd1178.jpg)

Elementor support  tells me that I must put this request here ,
Thank you

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
