### ISSUE TITLE
Unwanted Elementor Code getting crawled

### ISSUE THREAD

**Issue by gilcags** [elementor/elementor#11431]
Why do we keep seeing /#elementor-action:action=popup:open&settings in Google Search Console? Any ideas on how to hide this?
![Screenshot (91)](https://user-images.githubusercontent.com/48699362/82563357-fc0fb700-9b87-11ea-983c-e9a2b36f0dca.png)

**Comment by shilo-ey** [comment]
I merged this issue with #11104, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
