### ISSUE TITLE
TEMPLATES COULDN'T SAVE

### ISSUE THREAD

**Issue by Oloyede1** [elementor/elementor#11437]
![ELEMENTOR](https://user-images.githubusercontent.com/65760960/82657503-5d359a00-9c1d-11ea-90d3-36f5b228b099.png)

Hi,
I have the undefined error as seen in attached. I've Elementor Version: 2.9.8 & Envato 2.0.4 when I try to save the entire page or graphics block as template.

i have already tried the following attempts; Disable all plugins and revert to new theme, PHP version 7.2.27, Memory limit: 3000M, Time limit 180, but i still experience same issue. The issue only occurred when I'm trying to save the entire page or graphics block as a page template. But smaller individual section save smoothly. Not only that, if I edit older pages, there are no issues. Only happen for newly created pages.

Please i will appreciate your support.

Many thanks.

**Comment by lior-sh** [comment]
Hi @Oloyede1,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
