### ISSUE TITLE
Wanting API integration with my autoresponder Sendiio

### ISSUE THREAD

**Issue by johnstanley09** [elementor/elementor#11444]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnstanley09** [comment]
**What problem is your feature request going to solve? Please describe**.
Hello, I want to upgrade to Elementor Pro and design opt in form there.
I am currently using Sendiio autoresponder and happy with it BUT it doesn't integrate with Elementor Pro currently.
**Describe the solution you'd like**
So can you please give me your timeframe on when you will work with API to integrate with Sendiio?
Thank you
**Describe alternatives you've considered**
Tried webhooks but Sendiio doesn't integrate with Webhooks.  I like Sendiio as an effective autoresponder.  I don't want to have to move to the more expensive GetResponse.  I cannot use free Mailchimp as I am promoting affiliate marketing.  So need to use Sendiio or GetResponse.  Sendiio was only a 1 time fee and I am really happy with it and all my email autoresponders and lists are currently established there.
**Additional context**
Sendiio support has advised (support@zamuraiblogger.com).  You are free to liaise with them for a solution.  Yuri's advice:
"The whole integration is done on the side of a 3rd party app, by their developers. If you want to get the integration with Sendiio, you can help us and yourself by giving Sendiio API documentation page link (https://sendiio.com/pages/view/sendiio-api) to the support desk of the 3rd party and asking them if they'd agree to make it. If they will receive requests from their own users about such integration, it may be a much better push for them to actually make that integration happen."

I also asked them - When do you expect Sendiio to work with webhooks?
"It's not in any near future plans, if it will ever happen. We work with API, not webhooks."

**Comment by DorShahar** [comment]
Hi 
Thank you for your input, and sorry for the delay.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
