### ISSUE TITLE
Is there a way to create a custom skin for the individual posts in an archive? 

### ISSUE THREAD

**Issue by mzupek** [elementor/elementor#11442]
I want to add a like button to the cards, if I modifiy this code it will most likely be overwritten when I take the next upgrade, is there a way around this?

Please do not mark this as a duplicate of a feature request, I am NOT requesting this as a feature I want to extend it.

- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by TomRaraAvis** [comment]
custom skin for posts is main topic of #4440 vote it up with your comments and likes

**Comment by DorShahar** [comment]
Hi
Sorry for the delay...

The best approach to be is by [creating a new widget](https://developers.elementor.com/creating-a-new-widget/) which extends our widgets.
Read more about extending Elementor widgets [here](https://github.com/elementor/elementor/issues/9363).


Thanks

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
