### ISSUE TITLE
Text color does't override Theme Style "Link" settings in E 2.9.9

### ISSUE THREAD

**Issue by mareklexuan** [elementor/elementor#11462]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

After updating to Elementor 2.9.9, the link color settings set in Theme Style cannot be overridden in the individual widgets. 

If I add a link to a widget (example: Heading) and then want to change its color, the widget settings are always overridden by the Theme Style.

This is not an issue in Elementor 2.9.8

## Steps to reproduce

- Set link color in Theme Style
- Add a link to a widget (example: Heading) and change color in Typography settings

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/STK9HgUb
```
</details>

**Comment by oliveandlake** [comment]
I have exactly the same problem. Rolled back to 2.9.8 - glad it's not just me! :)

**Comment by arielk** [comment]
Thanks for your feedback: https://github.com/elementor/elementor/pull/11472

**Comment by rodolphebertozzo** [comment]
@arielk, see this : https://github.com/elementor/elementor/issues/11470

**Comment by moonbeetle** [comment]
Same problem with the Icon Box element. The icon keeps the set color but the title takes the link color thta is set at a higher level and no way to override unless using extra CSS and !important.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.10

Feel free to update

Thanks!
