### ISSUE TITLE
Add normal state color selection for filter bar in Gallery widget

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#11463]
You cannot change the color of the pointer in the filter bar to "normal".
![elm](https://user-images.githubusercontent.com/56270626/82811733-c1609400-9e91-11ea-9e35-95c7c16b7bc7.PNG)

**Comment by rodolphebertozzo** [comment]
@black-eye, are you having this problem?

**Comment by lior-sh** [comment]
Hi @rodolphebertozzo,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by rodolphebertozzo** [comment]
Hi @lior-sh, concretely, the pointer has a background color but there is no possibility to set a background color for the pointer when the tab is not selected.

**Comment by rodolphebertozzo** [comment]
In the style part, filter bar, "normal" state, there is no possibility to add a color of the pointer contrary to the 2 other parts: "on hover" and "active".

**Comment by rodolphebertozzo** [comment]
Thanks @shilo-ey 😉

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by arielk** [comment]
Thanks for your feedback, In fact there is no need to add the pointer color to normal state, because it takes from active state.
