### ISSUE TITLE
Video Widget - Dynamic Tag in Self Hosted requesting license activation

### ISSUE THREAD

**Issue by teoeugene** [elementor/elementor#11468]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using Video Widget and selecting the self hosted as the source, clicking on the Dynamic Tag when choosing a file will cause a popup to appear requesting to activate license. I've rollback Pro up to 2.9.0 and the issue is still there on a fresh WordPress installation. My license is still active and other Dynamic Tags has no problems except this Video Widget.

![video-widget-dynamic-tag](https://user-images.githubusercontent.com/19911944/82817457-9eed6b80-9ecf-11ea-88ad-6560f66e36a9.png)

## Steps to reproduce

1. Add Video Widget to layout
2. Select Self Hosted as source.
3. Click the Dynamic Tag button at Choosing File

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Tested on multiple websites, and on a freshly installed WordPress with no other plugins except for Elementor and Pro. 

All WordPress versions are 5.4.1

**Comment by auralay37** [comment]
I'm having an issue with this too. I'm trying to make a Elementor Template for a custom post type that has a video meta field, however the video Self-hosted option isn't allowing the Dynamic Tags (displayed as image in original post) despite Pro being installed and having a current subscription.

**Comment by teoeugene** [comment]
@auralay37 One workaround is to enable the "External URL" to be able to select the Dynamic Tag. The only difference I see with this option enabled/disabled is to toggle the availability to select videos from the media library. Anyhow, I've used another video widget from another addon as Elementor's Video widget does not have Dynamic Tag for video poster.

**Comment by loopmill** [comment]
Which video widget was it please?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.12

Feel free to update

Thanks!
