### ISSUE TITLE
Color picker option not available

### ISSUE THREAD

**Issue by DigitalKrishnendu** [elementor/elementor#11464]
Hello Folks, I just recently purchase the elementor pro and I am not a coding guy. I learn things from the internet. When I am trying to add any section color there is no color picker option only dynamic option available. Can anyone please guide me on how to enable the color picker option and set background color and text color. 

Please help me

**Comment by lior-sh** [comment]
Hi @DigitalKrishnendu,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
