### ISSUE TITLE
Native wordpress import/export does not work

### ISSUE THREAD

**Issue by SpabRice** [elementor/elementor#11466]
Hello,

as the title says, the native wordpress import/export does not work for pages created by elementor.  Am I missing something.  Isn't elementor supposed to be compatible with the native wordpress builder?

**Steps to reproduce**
1. Create a page with elementor
2. Tools > Export the full site/content
3. Import to another domain/wordpress install using the native wordpress importer (Tools > Import)
4. Layout is broken

I searched for similar issues but could not find any help.  This has been tested on a fresh install with no plugins and the default theme.

**EDIT**
There is something wrong with the __elementor_data_ meta field.

On the export file the elementor_data field is the following:
`[{"id":"cf381fa","elType":"section","settings":{"structure":"20"},"elements": ....`

After the import on a new site it has backslashes on it:
`[{\"id\":\"cf381fa\",\"elType\":\"section\",\"settings\":{\"structure\":\"20\"},\"elements\":`

Thats the reason why it is not displaying the elementor structure of the page.  How to solve that.  Am I missing something?

**Comment by shimsa** [comment]
+1

**Comment by udidol** [comment]
Hi @SpabRice ,
WordPress escapes all postmeta inserted into its database table. Elementor has a setting that excludes Elementor posts from the escaping process.

Do you have any other plugins installed on your site besides Elementor? Other plugins/themes can interfere with the exclusion. Try to disable all other plugins, and if you are using a non-standard theme (standard being a WP theme like TwentyTwenty, or Elementor's own Hello Theme) change your theme to a standard one and see if you see any change.

Also, next time you open an issue, please use our template for opening issues, which appears when you try to open a bug issue.This can be helpful in debugging and solving the issue. For instance, in this case, there is a rubric there that asks you to check and specify whether this issue occurs with only Elementor / Elementor Pro active and all other plugins disabled. Knowing this would save us time waiting for your response next time.

**Comment by SpabRice** [comment]
Thanks for your answer @udidol. Sorry for not using the template.
As I stated in my first message, Yes, I'm on a fresh install with all plugins disabled and using the standard theme (twentytwenty). 

It is definately related to the elementor plugin and it is an deprecated 'compatibility fix' which is still active and has not been removed/adapted with the new import/export version by wordpress.

See here:
[](https://github.com/elementor/elementor/issues/10774)

How can it be that this issue has not been fixed yet?  It has been 3 months already that it has been stated.  The native wordpress import/export is not working because of it which is a huge feature which is used every day.

**Comment by lior-sh** [comment]
Hi @SpabRice,

I merged this issue with  #10774 , which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.10

Feel free to update

Thanks!

**Comment by shilo-ey** [comment]
This issue has been added more compatibility layer and it was resolved in Elementor v2.9.14

Feel free to update

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!

**Comment by maheshwaghmare** [comment]
The slashes are required if there is no WordPress Importer plugin.
