### ISSUE TITLE
Media Carousel moves after click

### ISSUE THREAD

**Issue by angvel8** [elementor/elementor#11465]
# Prerequisites
wp Astra theme setup with an elementor pro and woocommerce on Wordpress 5.4.1

- [x]  I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

#Description 
I have a problem with the "Media Carousel" item. I added images with custom URLs but when i click to one of them the picture slides to the left before goes to the link. I'm trying to find a way to click the link without the picture moving from its original place. Is this possible?

![Media Carousel problem](https://user-images.githubusercontent.com/65544205/82815971-90d12800-9e9a-11ea-8414-984774c5536c.gif)

# Steps to replicate
1. Install Elementor Pro
2. Add the "Media Carousel" item.
3. Add images with custom urls.

Thank you

**Comment by DorShahar** [comment]
Hi @angvel8 
Thank you for reporting (and sorry for the delay in responding to this).
We will handle this.

Thanks

**Comment by DorShahar** [comment]
Hi @LiavGoldshtein

**Comment by DorShahar** [comment]
Hi @angvel8
In the past few days, we tried to make it work. 
We encounter problems in our infra - and this change will harm other areas in the product.
Due to the risk - and since the user who clicks the image will redirect to another URL - we decided not to implement the change.

Thank you for your understanding

**Comment by tissi-2** [comment]
Dear elementor team,

seeing such comments makes me angry. We all pay a lot for this product and we deserve to get widgets without glitches. We give our very best to help you enhancing this product and so do you... go back into the office and solve that problem - there is always a way to get it working!
