### ISSUE TITLE
Getting Title of Post Widget to be vertically aligned with container

### ISSUE THREAD

**Issue by ronchio** [elementor/elementor#11476]
## Pre
![Nutriology](https://user-images.githubusercontent.com/35655260/82898296-1079f800-9f6a-11ea-9d98-62ade0b8563b.png)
requisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can't seem to get the title of the post widget to be vertically aligned with the container (see attached screenshot).  I've tried custom CSS (ie, such as "vertically-align: middle;"), but that doesn't do anything.  Adding top/bottom padding doesn't help either because the first box of the screenshot won't be vertically aligned then.  

**Describe the solution you'd like**
Have the post title container vertically aligned. 

**Describe alternatives you've considered**
I just need the CSS code to have the post title to be vertically aligned.

**Additional context**
See attached screenshot for more details.

**Comment by DorShahar** [comment]
Hi 
Centering elements in CSS is tricky - you can use[ this guide](https://css-tricks.com/centering-css-complete-guide/), and target the container with the class `elementor-posts-container` for the posts widget, and use `nth-child` (see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) if you aren't familiar with this) to target the relevant post location. 

This being said if you know the height of the title (like how many rows) - so it will center as needed. If not, you will have to do calculations for each container.  

Good luck!
