### ISSUE TITLE
Popup event handler document instance undefined

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#11475]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor Pro.

## Description

The popup event triggers (`elementor/popup/show` and `elementor/popup/hide`) passes 2 extra parameters as separate arguments and therefore when adding an event listener to it, the popup document instance (the 2nd param) returns `undefined`. 

The [JQuery `.trigger()` docs](https://api.jquery.com/trigger/) state that extra parameters need to passed as a single argument either as an array or plainObject.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.1

Feel free to update

Thanks!
