### ISSUE TITLE
Form buttons get a border on hover state even if border is explicitly not set at normal state

### ISSUE THREAD

**Issue by moonbeetle** [elementor/elementor#11488]
EL 2.9.9 / EL PRO 2.9.5 
Form > Style tab > Button > Normal state > Border type: none

Temporarily fixed it with extra CSS:
`selector .elementor-button:hover {border:0;}`

**Comment by lior-sh** [comment]
Hi @moonbeetle,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
* Video
Without it, we simply can't help.
Thanks.
