### ISSUE TITLE
Image carousel widget

### ISSUE THREAD

**Issue by chaser32419** [elementor/elementor#11487]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

--- Feature request ---

Give an option of play on hover with the Image carousel widget. 

With this option you can use something like crocoblocks jet engine listing feature and create a post feature image that can be used to play a gif or several images on hover.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Description and examples.**
* One request per thread

Thanks.
