### ISSUE TITLE
Add " justify" to the text alignment in the column typography

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#11480]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I often have websites with multiple text widget in a column and I'd like to justify the text. 

**Describe the solution you'd like**

In the Section -> Column -> Style  tab -> Typography, there is an option for the text alignment. Only 3 options are offered : left | center | right
It should also include a "Justify" option.

That kind option is already present in the Text widget style tab, so it should also be offered in other places where text alignment can be defined.

**Describe alternatives you've considered**

I can add CSS in the advance panel of the Column, or I can set the Justified option for each Text widget in the Style panel.

Those option works, but the CSS isn't user-friendly, and when we have a lot of text widget, it's long to set all widget individually. And especially painful if in the future the client decides to change the alignment.

**Additional context**

**Comment by vgstef** [comment]
Thanks @ramiy for the commit. I don't understand why this isn't in the latest Elementor version yet. It was just a small change!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.3

Feel free to update

Thanks!
