### ISSUE TITLE
Make the sticky offset control responsive

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#11486]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When using the **Motion Effect** feature, we can set an **Offset** (number control). But we can't set different offsets to different screen sizes.

**Describe the solution you'd like**

Changing the control to a responsive control will fix the issue.

**Describe alternatives you've considered**

Using custom CSS.

**Additional context**

![Elementor_Sticky](https://user-images.githubusercontent.com/576623/83013936-7c219b00-a026-11ea-8968-88dc56344e57.png)

**Comment by Bovelett** [comment]
I second this request. +1

**Comment by tollube** [comment]
Still not available... +1
@ramiy 
Is there any workaround?

**Comment by tollube** [comment]
+1 No workaround?

**Comment by jonnymueller** [comment]
**+1** 

Isn't there a way to do this with CSS? If you could just define the amount of pixels relative to the screen height that would do the job right!?

**Comment by ramiy** [comment]
This issues was fixed!
