### ISSUE TITLE
Registered Users

### ISSUE THREAD

**Issue by Demien2020** [elementor/elementor#11483]
Hi, today I use other plugins to manage registered users and their classes (editor, admin etc.). I would like to manage registered users in the singles pages, articles and menu with elementor pro, when will it be possible?

**Comment by shilo-ey** [comment]
Hi @Demien2020 

Thanks for your feedback.

The user entity is a WordPress entity that Elementor doesn't manage.
You can search for 3rd party plugins that might help you achieve this request but as I can see it, Elementor won't add this functionality anytime soon.

Thanks
