### ISSUE TITLE
add_link_attributes function do not overwrite all in foreach loop item link attributes

### ISSUE THREAD

**Issue by andriussok** [elementor/elementor#11498]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**add_link_attributes function do not overwrite all foreach loop item link attributes**

I'm trying to extend Testimonial widget with Repeater function to make multiple testimonial items grid (Elementor non-Pro 2.9.9 );

When I iterate over extended Testimonial widget items list, I can overwrite *add_render_attribute* for each item by adding last arg in fn as true;
```php
<?php
$this->add_render_attribute( 'meta', 'class', 'elementor-testimonial-meta', true );
```

However *add_link_attributes* function overwrite bool seems do not work.
```php
<?php
$item_link = $item['link'];
$this->add_link_attributes( 'link', $item_link, true); // true do not overwrite
```

**I can manually get the link and add it to a tag href; but why I can't flush/clear/overwrite with  add_link_attributes ?**

## Steps to reproduce

Create new plugin with Elementor Testimonial Widget to extend
Wrap testimonial Controls in Repeater item like
```php
<?php

  protected function _register_controls() {
    $this->start_controls_section(
      'section_testimonial',
      [
        'label' => __( 'Testimonial Grid', 'elementor' ),
        'tab' => Controls_Manager::TAB_CONTENT,
      ]
    );

// =========================================== Repeater content
$repeater = new \Elementor\Repeater();

    $repeater->add_control(
      'testimonial_name',
      [
        'label' => __( 'Name', 'elementor' ),
        'type' => Controls_Manager::TEXT,
        'dynamic' => [
          'active' => true,
        ],
        'default' => 'John Doe',
      ]
    );

    $repeater->add_control(
  'link',
  [
    'label' => __( 'Link', 'elementor' ),
    'type' => Controls_Manager::URL,
    'dynamic' => [
      'active' => true,
    ],
    'placeholder' => __( 'https://your-link.com', 'elementor' ),
  ]

 // more controls for image, job, content all as $repeater->add_control
);
// ======================================= end Repeater

    // Repeater List items
    $this->add_control(
      'list',
      [
        'label' => __( 'Repeater List', 'elementor' ),
        'type' => Controls_Manager::REPEATER,
        'fields' => $repeater->get_controls(),
        'default' => [
          [
            'testimonial_name' => __( 'Title #1', 'elementor' ),
          ],
          [
            'testimonial_name' => __( 'Title #2', 'elementor' ),
          ],
        ],
        'title_field' => '{{{ testimonial_name }}}',
      ]
    );


    $this->end_controls_section();


// Render content
protected function render() {
  $settings = $this->get_settings_for_display();

  if ( $settings['list'] ) {
    foreach (  $settings['list'] as $key=>$item ) {

      $has_name = ! ! $item['testimonial_name'];
      
      if ( ! empty( $item['link']['url'] ) ) {

        $item_link = $item['link'];

        $this->add_link_attributes( 'link', $item_link, true); // <- this TRUE is my issue as it doesn't overwrite item link 

      }

        ?>
          <div class="elementor-testimonial-details">
            <?php
            if ( $has_name ) :
              $this->add_render_attribute( 'testimonial_name', 'class', 'elementor-testimonial-name', true );


              $testimonial_name_html = $item['testimonial_name'];

              if ( ! empty( $item['link']['url'] ) ) :
                ?>
                <a <?php

// here get_render_attribute_string( 'link' ) will generate href="http://linkFromFirstItemURL.com%20http://linkFromSecondItemURL.com%20etc.. "
 
 echo $this->get_render_attribute_string( 'testimonial_name' ) . ' ' . $this->get_render_attribute_string( 'link' ); ?>><?php echo $testimonial_name_html; ?></a>
                <?php
              else :
                ?>
                <div <?php echo $this->get_render_attribute_string( 'testimonial_name' ); ?>><?php echo $testimonial_name_html; ?></div>
                <?php
            endif; ?>
          </div> 
        <?php
    } //end foreach
  } // end if
} // end Render
```

If each item in repeater has url link and extra Link Options each next item will append previous item's url and by using function 
```php
<?php $this->get_render_attribute_string( 'link' )
```
Will return accumulative string like:
`href="http://link-one.com http://link-two.com http://link-three.com" target="_blank _blank _blank"`

Which is coming from render_attributes href array
```
MYFn_Elementor\Widgets\Widget_MYFn_Testimonial::__set_state(array(
   '_has_template_content' => true,
   'children' => NULL,
   'render_attributes' => 
array (
	'link' => 
	    array (
	      'href' => 
	      array (
	        0 => 'http://link-one.com',
	        1 => 'http://link-two.com',
	        2 => 'http://link-three.com',
	      ),
	    )
	  )
```

**In Elementor/includes/base/element-base.php**
```php
<?php
// line 394 add_render_attribute uses 4 args
public function add_render_attribute( $element, $key = null, $value = null, $overwrite = false )

// line 449 add_link_attributes uses 3 args
public function add_link_attributes( $element, array $url_control, $overwrite = false )

// line 495 add_render_attribute takes 3 first args
if ( $attributes ) {
    // with 3 args overwrite doesn't work at all
    $this->add_render_attribute( $element, $attributes, $overwrite );
  }

  // with 4 args like this
    $this->add_render_attribute( $element, $attributes, null, $overwrite );
/*
 overwrite works only for -> href argument,
 other Link Options like target, nofollow and custom are passed to the next items
*/
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
It's not technical, it's code logic
</details>

**Comment by mustafakucuk** [comment]
Hi,

You can use `remove_render_attribute`

Ex;
`$this->remove_render_attribute( 'link' );`

**Comment by NicolaiFriis** [comment]
Just here to confirm @mustafakucuk solution and give and cut out of what i made with a feature list that needed a link attribute. Thanks Mustafa! 

`<?php if ( ! empty( $item['item_text'] ) ) : ?>
									<span <?php $this->print_render_attribute_string( $repeater_setting_key ); ?>>

                    <?php
                    if ( ! empty( $item['item_link']['url'] ) ) :
                      $this->remove_render_attribute( 'item_link' ); // This line removes any old references of links. 
                			$this->add_link_attributes( 'item_link', $item['item_link'] );

                      ?>
                      <a <?php echo $this->get_render_attribute_string( 'item_link' ); ?>>
                  			<?php $this->print_unescaped_setting( 'item_text', 'features_list', $index ); ?>
                  		</a>
                      <?php
                		else :
                      $this->print_unescaped_setting( 'item_text', 'features_list', $index );
                    endif;
                    ?>
									</span>
									<?php
								else :
									echo '&nbsp;';
								endif;`
