### ISSUE TITLE
Typography get's reverted to original settings after reset when clicking it again

### ISSUE THREAD

**Issue by artifex-media** [elementor/elementor#11496]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
If you reset a Typography option on, let's say any Heading element, it get's restetted properly and the element itself also changes perfectly. 
However, when you want to change something in it's settings it will jump back to it's original settings before the reset. I also expierence this with Text Editor, so maybe more elements?

![epmLtob2W0](https://user-images.githubusercontent.com/43996366/83238702-1b65a000-a197-11ea-9f87-523a3d9c9bd8.gif)
![3CGOpFQyGW](https://user-images.githubusercontent.com/43996366/83239233-dee67400-a197-11ea-9450-ad778740f1bf.gif)

## Steps to reproduce

- Install latest WP, Elementor, Elementor Pro, Hello Theme, Hello Theme Child
- Add Heading element to page, give it some Typography options
- Reset the Typography
- Watch the magic happen

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.3.22
	PHP Version: 7.2.29
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: http://artifexmedia.nl/test
	Home URL: http://artifexmedia.nl/test
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.5
		Author: Elementor.com

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elements Usage ==
	
	wp-page : 1
		wp-widget-media_audio : 1

== Log ==
	
Log: showing 1 of 12020-05-25 21:12:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.5',
)]

				
</details>

**Comment by arielk** [comment]
We changed this behavior in Elementor v3.0+

Feel free to update

Thanks!
