### ISSUE TITLE
Add "HTML Tag" option to Divider text

### ISSUE THREAD

**Issue by lannyheidbreder-mc** [elementor/elementor#11499]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

A divider is naturally a good place for a semantic heading. But the Divider widget doesn't let us choose an HTML tag for the divider text, and if you type your own HTML tag in the text field, it overrides your Typography choices in the Style tab.

**Describe the solution you'd like**

When Text is chosen for "Add Element" on a Divider widget, beneath the Text option there should be a new HTML Tag option, similar to what appears in the Heading widget. The available options might be different; it might include only the `<h1>` through `<h6>` elements along with `<div>`. Or maybe not, maybe it can share all of them! Either way, the Typography options on the Style tab should override the styles of whichever HTML tag is chosen, as it works with other widgets.

**Describe alternatives you've considered**

I thought of adding divider functionality to the Heading widget, but that seems way more duplicative and way less elegant.

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
