### ISSUE TITLE
Remove HTML from non-Elementor pages

### ISSUE THREAD

**Issue by jeremysfoster** [elementor/elementor#11494]
I've been in touch with support who haven't been able to answer this question, so they directed me here, instead.

I have Elementor installed on my site but it is set to *only* be used on a single page while I'm in the process of testing it. I'm also using the Asset Clean-Up plugin to stop all Elementor scripts from loading on the entire site with the exception of that one page.

But still...

Elementor is adding code to pages that have nothing to do with the page builder whatsoever. Is there a way to stop Elementor from injecting code into posts/pages that are not using the plugin at all?

Thanks!
Jeremy

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

If I understand your report correctly, I'm merging this issue with #8572 for better handling of this request

Thanks.
