### ISSUE TITLE
Single product page layout issue

### ISSUE THREAD

**Issue by ulgeekiyanage** [elementor/elementor#11501]
Created a single product page using elemntor pro plugin. In a single row section, there are two columns to display product image and product information. The left side has the product image, right side column contains the product title, reviews, a short description and add to cart button.

When I added the product images into the right side column, left side column go outside from the element or row section at the page build. This effect does not happen to the backend editor. This is happening at the front end. Which mean, right side elementor-element not in the elementor-row div at the final view

Here is the screenshot of the issue
https://ibb.co/KLzDFXJ

**Comment by lior-sh** [comment]
Hi @ulgeekiyanage,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
