### ISSUE TITLE
Font-Awesome Brands should have font-weight of 400

### ISSUE THREAD

**Issue by Slapbox** [elementor/elementor#11503]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After removing the FontAwesome 4 shim, or maybe even before, I noticed that the Windows brand icon had become a parallelogram that no longer looked like the brand icon. Eventually I tracked this down to a change where these used to have `font-weight: 400` applied, which is the correct weight [according to their documentation](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements).

![image](https://user-images.githubusercontent.com/6835891/83339519-bb592180-a29c-11ea-9d94-7eb27b9ee764.png)

Our theme seems to be applying a font weight of `600` without this Elementor rule that previously existed to set `400` instead. This affects other brand icons too, but Windows is the most obvious of the ones I've used.

## Steps to reproduce

Use FontAwesome 5 brand icons

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by udidol** [comment]
Hi @Slapbox ,
I am not sure I understand what is causing your issue. 
Elementor doesn't apply a `font-weight` rule on Font Awesome icons.

> Our theme seems to be applying a font weight...

If this is a theme issue, you should consult with your theme's developers. 
You can also just apply a site-wide CSS rule to override the `font-weight` property for Font Awesome brands, such as:
```
.elementor .fab {
    font-weight: 400;
}
```

**Comment by Slapbox** [comment]
@udidol thanks for your reply. I don't know why I said "our theme" - it's Elementor applied styling.

I could just apply a font-weight rule, but considering that you'd expect Elementor to work out of box, I took the time to file a bug report.

![image](https://user-images.githubusercontent.com/6835891/83434622-d2b51d80-a408-11ea-93fc-000029393dd6.png)

**Comment by Slapbox** [comment]
@udidol I'd appreciate if you'd re-open this valid issue.

**Comment by Slapbox** [comment]
@udidol could we please re-open this?

**Comment by udidol** [comment]
Hi @Slapbox ,
We have not received any complaints except for yours on the Font Awesome `font-weight` issue.

We try to be careful when intervening with external libraries and their CSS, so we will consider adding what you are asking for into the core, but it might not be immediate.

**Comment by Slapbox** [comment]
Hey @udidol thanks for your reply. I definitely understand hesitancy to add things willy nilly. Your point about not receiving any other complaints is certainly a fair one. 

**I've discovered that the issue is that if an icon is used in an element with an applied `font-weight` then it inherits the `font-weight` of the parent**, in this case a button. If this used to be the behavior, it was masked by the shim.

I'd expect it to display at the intended font-weight prescribed by the creators of FontAwesome regardless of applying a higher font-weight in the button's typography.

![image](https://user-images.githubusercontent.com/6835891/84447232-7d9db680-ac15-11ea-8733-1bf0aab921d3.png)

Previously the v4 shim was including these styles. I don't know if they're just not included in the shim anymore, but enabling/disabling it makes no difference for me, even if I regenerate Elementor CSS. It's not being overridden by anything, it's just not there.

Thanks @udidol, I appreciate you reading.

**Comment by udidol** [comment]
@Slapbox I understand. However, we take the icons CSS directly from FontAwesome themselves. If they don't see fit to include that in their CSS we prefer not to intervene with it. Good luck!

**Comment by Slapbox** [comment]
What you're saying as a general point makes sense to me, but it was in Elementor's v4 shim and it was taken out randomly so it doesn't really make sense to me in this specific circumstance. I'll just go re-implement it myself, but kind of a pain in the ass. I appreciate your help.

**Comment by udidol** [comment]
It's not Elementor's shim. The shim comes from FontAwesome, we just include it. We don't intervene with FontAwesome's CSS at all.

**Comment by Slapbox** [comment]
Got it, makes sense. Thanks for the clarification, much appreciated.
