### ISSUE TITLE
About TinyMCE plug-ins

### ISSUE THREAD

**Issue by akane33333333** [elementor/elementor#11504]
The TinyMCE plugin I created doesn't work.
It had been deleted in the following file.

How to get plugins to work with TinyMCE.

elementor\core\editor\editor.php
	private function get_wp_editor_config() {
		// Remove all TinyMCE plugins.
		remove_all_filters( 'mce_buttons', 10 );
		remove_all_filters( 'mce_external_plugins', 10 );

**Comment by lior-sh** [comment]
Hi @akane33333333,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
