### ISSUE TITLE
REHUB BREAKS

### ISSUE THREAD

**Issue by JeremyGruver** [elementor/elementor#11519]
Warning: require_once( /wp-content/themes/rehub-theme/rehub-elementor/wpsm-theme.php): failed to open stream: Permission denied in /wp-content/themes/rehub-theme/functions/el_functions.php on line 70

Fatal error: require_once(): Failed opening required ‘//modmymini/wp-content/themes/rehub-theme/rehub-elementor/wpsm-theme.php’ (include_path=’.:’) in //modmymini/wp-content/themes/rehub-theme/functions/el_functions.php on line 70

**Comment by shilo-ey** [comment]
@JeremyGruver 

We are not the authors of Rehub theme, please contact them.

Thanks
