### ISSUE TITLE
Missing swiper.min.js.map file

### ISSUE THREAD

**Issue by babasteve** [elementor/elementor#11511]
Hello,

## Prerequisites

- I looked for similar problems in open and closed tickets: this problem existed, was fixed, and it comes back.
- [X] The problem persists compared to the last stable version of Elementor.

## Description

The file "**swiper.min.js.map**" is missing in the elementor extension, which creates an error in the Google Chrome error console:

`DevTools failed to load SourceMap: Could not load content for https://www.MYDOMAIN.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net :: ERR_HTTP_RESPONSE_CODE_FAILURE`

After several searches, here is what it looks like:

1. The problem appeared in 2018 in this discussion: https://github.com/elementor/elementor/issues/5151
2. A user has found a "temporary" workaround, by adding the file "swiper.min.js.map" by FTP. This file can be found here: https://github.com/nolimits4web/swiper/tree/master/package/js
3. Unfortunately this file disappears after each update of Elementor, and it is difficult to see files returned for each update of the plugins: imagine if all the extensions have the same problem!
4. Obviously, the problem was solved in version "2.1.6" of Elementor but ...
5. ... HOP! The problem returned.

**NB:** this file is supposed to be found here: `/ wp-content / plugins / elementor / assets / lib / swiper / swiper.min.js.map`

## Steps to reproduce

- With Google Chrome: open a page created with "Elementor" (I use the free version but my site is closed => The problem also persists with an open website)
- Open the inspector with a "right-click"
- Go to the "console" tab
- Error line:
`DevTools failed to load SourceMap: Could not load content for https://www.MYDOMAIN.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net :: ERR_HTTP_RESPONSE_CODE_FAILURE`

## Isolating the problem
- [X] This bug happens with only Elementor free active plugin (I don't know for Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
WordPres 5.4.1
Elementor 2.9.9

Please fix this issue once and for all in the next update, please.
Thank you for your attention, cordially.

**Comment by shilo-ey** [comment]
Thanks @babasteve,

I merged this issue with #10764, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

A patch for this issue should release soon.

Thanks for your feedback!
