### ISSUE TITLE
Select field error

### ISSUE THREAD

**Issue by israel-tours** [elementor/elementor#11510]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

https://www.loom.com/share/1911572bebe848a6aac0a4869e6ac8e9

**Comment by lior-sh** [comment]
Hi @israel-tours,

This issue has been resolved in Elementor Pro v2.10.0
Feel free to update
Thanks!
