### ISSUE TITLE
Mailto being replaced with page URL and causing 404 E-Free 2.9.10

### ISSUE THREAD

**Issue by robtucker168** [elementor/elementor#11518]
The latest E-Free update 2.9.10 is removing Mailto: and Tel: and replacing them with the page URL causing 404 errors on all Mailto and Tel links site wide. Even on untouched links. 

e.g. 
The link I'm adding: **mailto:email@mydomain.co.uk?subject=I%20have%20a%20question...**

Then once I update and preview the page, then test the link it is changed to: **https://mydomain.co.uk/demo-page/email@mydomain.co.uk?subject=I%20have%20a%20question...**

This is the case for a link added directly and also if you use the Dynamic>Contact URL function

This is on two sites , both only have E-free and E-Pro.

**Comment by rodolphebertozzo** [comment]
https://github.com/elementor/elementor/pull/11516

**Comment by shilo-ey** [comment]
Thanks, 

We can validate this issue and will release a patch ASAP.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.11

Feel free to update

Thanks!

**Comment by shilo-ey** [comment]
> Ah this broke many of our custom links for our custom Linux distribution website, such as "x-alpm-package://kphotoalbum" - where a link is not a normal URL, but like in the example. Can you please fix this?

Hi, Elementor uses WordPress allowed protocols in URL. You can learn more about this change and see how to extend the allowed protocols here: https://developers.elementor.com/uri-protocols-handling-update/ 

Thanks

**Comment by LizNem** [comment]
Also here to report this broke a bunch of relative links throughout numerous sites of ours.    Only just discovered it, haven't even guaged the impact yet;  we've used Elementor on at least 50 websites by now..... going to be a rough go of it.

**Comment by smilingkite** [comment]
I handle only one elementor-wordpress site, but I too suddenly have links that don't work. They're simple relative links of the type /about-us/ . These no refer to http://about-us/. Which obviously doesn't work.
