### ISSUE TITLE
Social Icons Email and Contact Number not visible

### ISSUE THREAD

**Issue by ThomasANeef** [elementor/elementor#11522]
Hi,

When you add a team member carousel, you can also add social links like facebook, twitter, Instagram, Linkedin, youtube, Pinterest, dribble, email and contact number. Every of this option have an emote, but this does not count for the email and telephone. The first time I added a telephone number and an email i did saw emotes like a telephone icon and email icon, but now I see this two squares. Is it an option to include these emotes as well, because now it looks a bit weird and people will not know the telephone number and email address might be under these square icons. 

![Team member caroussel](https://user-images.githubusercontent.com/66306919/83515640-fe520980-a4d5-11ea-9d5c-aeeb4d20fc8f.jpg)

**Comment by lior-sh** [comment]
Hi @ThomasANeef,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
