### ISSUE TITLE
Please clean up SourceMap from production!

### ISSUE THREAD

**Issue by i30** [elementor/elementor#11527]
<img width="1207" alt="Screen Shot 2020-06-03 at 16 52 30" src="https://user-images.githubusercontent.com/16183687/83623629-c4f3c980-a5bb-11ea-947b-59b29c9c9663.png">

Is sourcemap necessary for production-ready releases? If not, please clean it up! Those warnings are really annoying.

**Comment by shilo-ey** [comment]
Are you using `define( 'SCRIPT_DEBUG', true );` in your production-ready site?

If so, please disable it and make sure your package is built properly.
