### ISSUE TITLE
ACF Color Pickers ignore global options

### ISSUE THREAD

**Issue by mbaierl** [elementor/elementor#11525]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I have a global options page, created with ACF Pro. There I set global colors, which I can properly select for backgrounds etc. within Elementor.

However the color is ignored when being used as a popup background color. It works fine within Elementor when editing the popup, but won't show up on the page itself.

## Steps to reproduce

1. Create an ACF Options page
2. Add a color picker field to the options page (within ACF)
3. create a new Elementor Popup
4. set the background color to be a dynamic ACF color field and choose the just created ACF color option 
5. view the popup on the website - it won't show the chosen color.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by Bovelett** [comment]
I have the same problem. Same steps as @mbaierl took, only difference is I use the colors for background colors.

**Comment by Bovelett** [comment]
Dear development team,
I'm working to make a site  - with a ton of articles - accessible, as the majority of the visitors in the target group is visually handicapped or depending on a screen reader for other reasons. At the same time I want to use this site as a flagship to show the world that you really can make a site made with Elementor 100% accessible.

As this involves dynamically setting backgrounds and colors on headings, sections and pages by the owner of the site, whenever they add a new category to their articles, the whole project heavily relies on colors set in the options page. 

I'd be really really grateful if you could solve this bug! ❤️

Cheers,

Anne

**Comment by lior-sh** [comment]
Hi @mbaierl,

After investigation, we found out that the issue was from the ACF side, they fixed it and it should work fine now.
Thanks.

**Comment by lior-sh** [comment]
Hi @Bovelett,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by mbaierl** [comment]
> Hi @mbaierl,
> 
> After investigation, we found out that the issue was from the ACF side, they fixed it and it should work fine now.
> Thanks.

Thank you!
