### ISSUE TITLE
Elementor Theme Setup Demo Data Not Working After Update

### ISSUE THREAD

**Issue by tanjilahmed7** [elementor/elementor#11524]
Hello, 
Ever since I updated the elementor version (elementor.2.9.11), the design has been crashing while doing the setup demo data.
![image](https://user-images.githubusercontent.com/8897830/83602575-9b737780-a594-11ea-968b-03021ce22555.png)

**When I roll back the last version then everything is fine.**

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
