### ISSUE TITLE
Product Ratings Widget Display Conditions

### ISSUE THREAD

**Issue by wakalooka** [elementor/elementor#11521]
I would like to know if there is a way to Display (Single Product Rating) even when the product has no ratings. 

At the moment ratings only get displayed when a product is reviewed.

Thanks.

**Comment by Aviad-Herman** [comment]
Hi,
Are you referring to WooCommerce / another plugin? Please raise this issue with them.
We don't have a rating functionality within Elementor.

Thanks for reaching out.
