### ISSUE TITLE
Add the whole article in the "post" widget

### ISSUE THREAD

**Issue by anthoking49** [elementor/elementor#11532]
Good morning, sir, 

I took the ELEMENTOR PRO extension today and I would like to know if it is possible to add the option to see "the whole article" in the "post" widget. I'm currently using the BENTO theme and I would like to change to OCEANWP, and under BENTO I have the possibility at the search results page to display the articles but also a shortcode. 

Here is the current presentation :

[Lien 1](https://www.zupimages.net/up/20/23/dxd7.png)

[Lien 2](https://www.zupimages.net/up/20/23/44bc.png)

I would like to have the possibility to do the same. 

Waiting for your return and I hope that my request will be accepted, 

Yours sincerely,

**Comment by arielk** [comment]
You can do it by using skin: Full Content

Thanks
