### ISSUE TITLE
Filter bar for posts widget (Pro) 

### ISSUE THREAD

**Issue by henningjp** [elementor/elementor#11546]
Hey Elementor,

You've got like a **_million_** up-votes for this feature #1716  since 2017.   Are you listening?  As a newer user, I need the same thing and see that so do a LOT of other PRO users.  Can you tell us if this is even on the list?

Thanks!

**Comment by henningjp** [comment]
I'm closing this issue.  I think I just didn't know what I was doing.  I've figured it out with Blog templates.

**Comment by galiainfographics** [comment]
Couldn't find how you figured out a filter bar for users in the posts element with blog template? can you elaborate?

**Comment by henningjp** [comment]
See the referenced issue.  #1716. All this really requires is to let Wordpress do it's thing with archives and to set up an archive template for how those archive pages should look.  A menu can be placed at the top to reference (filter) the different category archives.

This is confusing for people new to Wordpress/Elementor.  I finally figured out how it all works together.

**Comment by galiainfographics** [comment]
Wow Jeff! thank you so much for replying! your reply is the only good thread I found in ages about this topic!!! :)
Sorry for still replying to you in here (I'm aware of thread #1716 but couldn't find any viable solutions in it..) 
Is there any chance you can elaborate a bit more?- do you have a URL example for such a posts archive page with filtering?
Did I understand what you wrote correctly? - I need to create an archive template and in it I need to place a category filter menu?  
Thank you! 
Galia

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔗 As you already mentioned, This issue is a Duplicate of #3140. (Issue #1716 has been merged with #3140).

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released as the Taxonomy Filter widget for the Loop Builder with Elementor Pro v3.15.0! 🥳 

You can now place a standalone taxonomy filter widget anywhere on your layout and target one of the Loop Grid widgets on the page. You can also use multiple taxonomy filters.

You can learn more about this new feature here: https://elementor.com/help/taxonomy-filter-widget/

Thank you, everyone, for your feedback and patience! 🙏  

We are just getting started with filters. 🤫 😉 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
