### ISSUE TITLE
Link from svg image not working

### ISSUE THREAD

**Issue by Peter4832** [elementor/elementor#11544]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have inserted the following code into an Elementor HTML template:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 763 596">
  <image width="763" height="596" xlink:href="image_url.png"></image>
<a xlink:href="page_url">
    <rect x="254" y="492" fill="#fff" opacity="0" width="97" height="50"></rect>
  </a>
</svg>`
When clicking on the defined rectangle, this should link to the specified page, but instead it produces an error with a black screen and a small icon in the middle of it that I do not recognise. 
![BlackScreen](https://user-images.githubusercontent.com/66444242/83863536-5ded2680-a71b-11ea-81cf-4aedfaa318c1.png)

If I edit the page with the Wordpress editor instead of Elementor, the code works.
## Steps to reproduce
Create a page and enter the above code with appropriate image and page link. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.3.21
	PHP Version: 7.3.18
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: https://gorilla-tag.com/edutherapy
	Home URL: https://gorilla-tag.com/edutherapy
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 2147483648
	Permalink Structure: /%postname%/.html
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.8.2
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.11
		Author: Elementor.com

	Ninja Forms
		Version: 3.3.18
		Author: The WP Ninjas

	Ninja Forms - Conditional Logic
		Version: 3.0.22
		Author: The WP Ninjas

	Ninja Forms - Multi-Part Forms
		Version: 3.0.24
		Author: The WP Ninjas

	Ninja Forms - PDF Form Submissions
		Version: 3.0.5
		Author: Ninja Forms

	Ocean Extra
		Version: 1.6.3
		Author: OceanWP

	Really Simple SSL
		Version: 3.3.3
		Author: Rogier Lankhorst, Mark Wolters

	UpdraftPlus - Backup/Restore
		Version: 1.16.25
		Author: UpdraftPlus.Com, DavidAnderson

	When Last Login
		Version: 1.2
		Author: Yoohoo Plugins

== Elements Usage ==
	
	section : 3
		heading : 4
		text-editor : 3
		toggle : 1
	wp-post : 0
		navigation-menu : 1
		site-logo : 1
	wp-page : 13
		button : 1
		heading : 37
		html : 2
		icon-list : 1
		image : 2
		spacer : 3
		text-editor : 36
		toggle : 5

== Log ==
	
JS: showing 1 of 1JS: 2020-05-01 17:16:29 [error X 4][https://gorilla-tag.com/edutherapy/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:7:57120] Blocked a frame with origin \"https://gorilla-tag.com\" from accessing a cross-origin frame. 

Log: showing 1 of 12020-06-03 16:00:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.11',
)]

</details>

**Comment by lior-sh** [comment]
Hi @Peter4832,

Thanks for reporting, I insert the code that you provide above and it's working fine for me and I see the image. Can you please retest it?
Thanks.

**Comment by Peter4832** [comment]
Thank you for your response.
I cannot get the link to work on the website I am developing. If you go to [https://gorilla-tag.com/edutherapy/testpyramid](https://gorilla-tag.com/edutherapy/testpyramid) and click on "Touch" in the bottom row you should see the result I am getting. If I disable javascript in my browser the link works correctly.

**Comment by mikecastrodemaria** [comment]
Same problem, any news ???

**Comment by Peter4832** [comment]
I’m afraid not. I’ve given up on using Elementor for the relevant page.

**Comment by wloburak** [comment]
Hi Guys, 

Elementor has the option to turn off the lightbox with a data-attribute.
`data-elementor-open-lightbox="no"`

So for example:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 763 596"> <image width="763" height="596" xlink:href="image_url.png"></image> <a xlink:href="page_url" data-elementor-open-lightbox="no"> <rect x="254" y="492" fill="#fff" opacity="0" width="97" height="50"></rect> </a> </svg>`

**Comment by DorShahar** [comment]
Hi,
Did you manage to solve the problem?

**Comment by Peter4832** [comment]
I decided to avoid the issue by not using elementor for the problem page.

**Comment by DorShahar** [comment]
Thanks @Peter4832 for reporting back. 
I'm closing the issue. 
Feel free to reopen if needed.
