### ISSUE TITLE
Social media share buttons for Chinese networks

### ISSUE THREAD

**Issue by StevePuts** [elementor/elementor#11554]
Please implement this asap, it's like one billion people don't exist to Elementor...
Here's how to do it:

For weibo:
https://service.weibo.com/share/share.php?url=https://www.woidmo.org/alerts/salmonellosis-china-hong-kong/&title=Salmonellosis+%26%238211%3B+Hong+Kong

For Wechat:
weixin://dl/chat?text=https://www.woidmo.org/alerts/salmonellosis-china-hong-kong/

Related to #3372 which had been closed.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.0

Feel free to update

Thanks!
