### ISSUE TITLE
FEATURE REQUEST: Auto-Video-Play in Lightbox + delete Colors

### ISSUE THREAD

**Issue by Psychopomp777** [elementor/elementor#11553]
**What problem is your feature request going to solve? Please describe.**
a. When a Video has an overlay image and opens in a Lightbox, the video doesn't start automatically.

b. the color picker doesn't work correctly (that would be another issue). So when I saved a wrong colour, I would like to be able to delete it from the color-palette.

**Describe the solution you'd like**
a. video starts autmatically even in a Lightbox

b. delete-color button in the color-palette

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* **One request per thread**

Thanks.
