### ISSUE TITLE
Elementor uses deprecated WPCS comments

### ISSUE THREAD

**Issue by paulschreiber** [elementor/elementor#11569]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Elementor uses deprecated WPCS comments, i.e. 
```
// WPCS: XSS ok.
```

These comments were deprecated in 2018 and will be removed in WPCS 3.0. See https://github.com/WordPress/WordPress-Coding-Standards/pull/1580

**Comment by KingYes** [comment]
Thanks!
