### ISSUE TITLE
No "em" Border Radius option in Button Widget Styling

### ISSUE THREAD

**Issue by fippy** [elementor/elementor#11561]
I think this might be a bug, because I can't see any reason why you wouldn't enable the ability to set the button border radius by emphemeral unit ("em"). Allowing only pixels and percentage values to be set, does not allow for the border-radius of buttons to easily scale.

**Comment by rodolphebertozzo** [comment]
Thanks ! https://github.com/elementor/elementor/pull/12415

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
