### ISSUE TITLE
Timeline Link Broken

### ISSUE THREAD

**Issue by madelive** [elementor/elementor#11574]
Regardless of what is set in the timeline for a link (which is rendered in a h2 tag), the href seems to be populated as null:

`<h2 class="df-timeline-post-title"><a href="" target="">You</a></h2>`

**Comment by lior-sh** [comment]
Hi @madelive,


Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
