### ISSUE TITLE
Elementor pro 2.10.0 Dynamic tags not working on Form widget

### ISSUE THREAD

**Issue by annettePixie** [elementor/elementor#11578]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
I haven't checked all field inputs but none of the dynamic tags work for default values for the fields I have used - hidden, text, textarea, date, email input fields. I have tried using User info for ID (hidden input) and First name (text field), current date (date field), Site title (Textarea).

The rendered form doesn't have a value attribute for the hidden field. None of the "before" "after" or fallback values work either.

## Steps to reproduce

Create a form - normal or stepped and try using a dynamic default value

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by diecreativo** [comment]
Report the same bug!

**Comment by CryBabyOne** [comment]
Report the same ...

**Comment by simonclay** [comment]
Reporting the same bug.

**Comment by oosga-masachen** [comment]
Same here.  Is there a quick fix for it?

**Comment by simonclay** [comment]
I backed up then rolled back Elementor Pro to 2.9.5 which fixed the issue for me.

**Comment by simonclay** [comment]
I must say, with respect, that I am a bit tired of new feature updates breaking old functionality.

On the one hand we are encouraged to keep plugins up to date for security, on the other hand the updates bring new problems and vulnerabilities.

**Comment by JessDelAngel** [comment]
> Same here.  Is there a quick fix for it?


I had the same problem, and I solved it too rolling back to 2.9.5


I hope they solve this bug soon

**Comment by kovou** [comment]
Same Here

**Comment by moonbeetle** [comment]
Reporting the same bug. And wondering how this could have passed.

**Comment by Meow24** [comment]
Reporting same bug. Has blown a whole bunch of client pages. Going to try to roll back to 2.9.5. Not good.

**Comment by srikanthmeenakshi** [comment]
Was trying to debug this for last 2 hours before I searched and found this...Frustrating...:-(

**Comment by alexmathias** [comment]
Apparently they´ve fixed this particular bug. After a while using Elementor PRO its still not clear to me the relation between both versions, why they apply a fix in the free version to a widget thats only available in PRO? It doesnt make any sense to me. Does anyone can please enlight me?
Thining about if worth to take the risk to check it out...
<img width="481" alt="screenshot_378" src="https://user-images.githubusercontent.com/66876358/84592775-6ed62000-ae1e-11ea-8d12-fc8deb67ebb2.png">

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.12

Feel free to update

Thanks!

**Comment by srikanthmeenakshi** [comment]
Yes, can confirm. The fix worked for me. Thanks!

**Comment by drilman** [comment]
The problem still occurs to us Also on version 2.9.12

**Comment by kukkakeppi** [comment]
I'm still having this issue too. 2.10.2. version.

Any news how to fix this?

**Comment by drilman** [comment]
The problem with the current version is when there is a hidden field, the form will not send!

**Comment by shilo-ey** [comment]
@drilman We can verify that there’s an issue with hidden fields: they inherit the “required” property if it was previously selected in this field.

We will address this issue soon and will release a patch.

For the meanwhile you can change your hidden field back to text, switch off the required control and switch back to hidden.

Please continue discussing this bug in a new issue and not in this one.

Thanks.
