### ISSUE TITLE
Better gestion of Handling step control colors in light and dark mode

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#11579]

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.12

Feel free to update

Thanks!

**Comment by rodolphebertozzo** [comment]
Thanks ;)
I also saw that @ramiy has opened a PR to add commands, additional to the Image widget, I had already opened an issue to ask for this function, if you want to add it to the 3.0 milestone: https://github.com/elementor/elementor/issues/10962
