### ISSUE TITLE
Code Contribution

### ISSUE THREAD

**Issue by anamwp** [elementor/elementor#11581]
Hello Elementor team, 
I didn't find any dev documentation how to setup elementor in local for development to contribute in you plugin. 
I want to know below things. 
1. How to setup elementor in my local for development. 
2. Any code of conduct for the contribution. 
3. How add as a contributor in you contributor team. 

I appreciate any reply. 
Thanks.

**Comment by DorShahar** [comment]
Hi
Sorry for the delay and thank you for contributing to us.

1. For Local development - I recommend [Local By Flywheel](https://localwp.com/).
2. As for contributing, see [here](https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md).
Simply, you need to fork the repo and send a pull request.

Thanks a lot!
