### ISSUE TITLE
Show Full Content Skin in Posts Widget Pro not Showing Full Content on Front End

### ISSUE THREAD

**Issue by rickpoet** [elementor/elementor#11580]
Hi,

I'm working on this page: https://staging2.poetrysuperhighway.com/psh/classifieds/ using Post Widgets Pro with skin set to "Full Content" - on the back end of the site within the Elementor interface it looks as it should. On the front end it only shows the title of the post with no content.

Not sure if this is a bug but grateful for any help or direction.

Thank you!

Rick Lupert

**Comment by lior-sh** [comment]
Hi @rickpoet,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by ruijt** [comment]
@rickpoet did you found a solution for this? I have the same problem.

**Comment by rickpoet** [comment]
Hi @ruijt - I know that Elementor flagged this as a bug but I don't think they fixed it as my test page with this implementation still doesn't show the full content. I think I did a work-around by linking to a Category page instead of using Post Widgets Pro and styling the category page which is working for me: https://www.poetrysuperhighway.com/psh/category/classifieds/ in which the full content did work. I think the bug is it didn't work on a regular page...though it was a while ago so I'm not 100% sure.

**Comment by ruijt** [comment]
@rickpoet thanks Rick for the answer and comments. I am going to find out how to do this, because it's a really ugly bug and I need to continue. Thanks again!

**Comment by rickpoet** [comment]
Good luck. Let me know if you find a different solution. I think the bug was specific with using the "full content" skin on a "page"

**Comment by ruijt** [comment]
@rickpoet thanks, I've created a ticket @ elementor support. Keep you posted!

**Comment by ruijt** [comment]
@rickpoet turned out that the Full Content issue was causes by a plugin called: Simple Facebook Connect. We disabled the plugin and now it works like a charm.

**Comment by rickpoet** [comment]
Thanks Rujit. I vaguely recall turning off plugins and it not fixing the issue for me. (But maybe it was a caching issue too and I didn't give it enough time.) Glad you've got it sorted for you!
