### ISSUE TITLE
Add Search option to select box in forms.

### ISSUE THREAD

**Issue by NMarlon** [elementor/elementor#11598]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In my forms, I have to many options in my select list, but I can't search for one them, is to many to select.

**Describe the solution you'd like**
A search option to write the selection.
Just something similar to this: [https://reactjsexample.com/content/images/2019/01/eact-async-select.gif](url)

**Describe alternatives you've considered**
Another plugin form with search option.

**Additional context**
[https://reactjsexample.com/content/images/2019/01/eact-async-select.gif](url)

**Comment by arielk** [comment]
Unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback

**Comment by ProfessorZer0** [comment]
It will be 3 years now. Any update on this feature? @arielk

**Comment by arielk** [comment]
@ProfessorZer0 We are working on a new feature based on community prioritization. To request a new feature, follow this guide: https://github.com/elementor/elementor/issues/21156

You can also follow this issue: https://github.com/elementor/elementor/issues/19203

Thanks
