### ISSUE TITLE
WordPress Importer Compatibility

### ISSUE THREAD

**Issue by NenadObradovic** [elementor/elementor#11591]
Hi guys,

Could you please check this file **elementor\includes\compatibility.php** and method **on_wp_import_post_meta**?

You override default hook **wp_import_post_meta** from WordPress importer plugin in order to modify meta value to work for your purpose when the plugin version is lower than 0.7. 

But for me code inside that method can mess other places if someone else uses the same hook name. For example, if the WordPress importer plugin is not installed and we use the same hook name for our purpose and your plugin is also installed, then your foreach function will override our meta values and our demo content will be broken. This is a very unique and specific case but it is possible :)

Could you please consider modifying that method to be like the example below? To work only when the plugin is installed and when a version is lower than 0.7.

```
public static function on_wp_import_post_meta( $post_meta ) {
	$wp_importer = get_plugins( '/wordpress-importer' );

	if ( ! empty( $wp_importer ) ) {
		$wp_importer_version = $wp_importer['wordpress-importer.php']['Version'];

		if ( ! empty( $wp_importer_version ) && version_compare( $wp_importer_version, '0.7', '<' ) ) {
			foreach ( $post_meta as &$meta ) {
				if ( '_elementor_data' === $meta['key'] ) {
					$meta['value'] = wp_slash( $meta['value'] );
					break;
				}
			}
		}
	}
	
	return $post_meta;
}
```

Thanks for your time.

Best regards,
Nenad

**Comment by udidol** [comment]
Hi @NenadObradovic ,

Is your demo content comprised of Elementor posts?
Because as you can see, we only modify `_elementor_data` in this loop.
If your demo data is unrelated to Elementor, how is it affected?

**Comment by NenadObradovic** [comment]
Hi there,

Yes, because of that I got that issue :) If I use your plugin as the main page builder than my own import functionality will be broken. 

Best regards,
Nenad

**Comment by udidol** [comment]
I understand.
I see no problem with changing the method to what you are suggesting. It will be included in a future release.

**Comment by NenadObradovic** [comment]
Hi there,

Thank you very much, I appreciate that :)

Best regards,
Nenad

Best regards,
Nenad

**Comment by NenadObradovic** [comment]
I accidentally closed the ticket :)
