### ISSUE TITLE
Multi-Step Forms not Working in Elementor Pro v. 2.10.0

### ISSUE THREAD

**Issue by jrodrigovaldez** [elementor/elementor#11596]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I add steps to an existing form. On the last step when clicking to SEND it goes back to the first step.... No send, no redirection If i remove the steps, the form works again.

## Steps to reproduce

1. Use Form with Multisteps
2. Error submit

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) PHP/7.0.33
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: http://www.fundacionparaguaya.org.py/v2
	Home URL: http://www.fundacionparaguaya.org.py/v2
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: es-ES
	Timezone: -4.5
	Admin Email: web@cerocin.co
	Debug Mode: Inactive

== Theme ==
	Name: FUNDACION PARAGUAYA
	Version: 
	Author: CEROCINCO
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 4.1.6
		Author: AdminColumns.com

	Advanced Custom Fields PRO
		Version: 5.7.6
		Author: Elliot Condon

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.11
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.5
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 2.10.0
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 4.0.3
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.0.0
		Author: WPDeveloper

	GA Google Analytics
		Version: 20200325
		Author: Jeff Starr

	InfiniteWP - Client
		Version: 1.9.4.5
		Author: Revmakx

	List category posts
		Version: 0.82
		Author: Fernando Briano

	Polylang
		Version: 2.7.3
		Author: WP SYNTEX

	Polylang Theme Strings
		Version: 4.0
		Author: Modeewine

	Popup Builder
		Version: 3.67
		Author: Sygnoos

	Recent Posts Widget Extended
		Version: 0.9.9.7
		Author: Satrya

	Redux Framework
		Version: 3.6.18
		Author: Team Redux

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	Simple Custom Post Order
		Version: 2.5.0
		Author: Colorlib

	Social Login, Social Sharing by miniOrange
		Version: 7.3.8
		Author: miniOrange

	WP-Matomo
		Version: 1.0.22
		Author: Andr&eacute; Br&auml;kling

	WP File Manager
		Version: 6.4
		Author: mndpsingh287

	WP Mail SMTP
		Version: 2.1.1
		Author: WPForms

	Yoast SEO
		Version: 14.3
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		heading : 5
		icon-box : 3
		image : 1
		social-icons : 1
	header : 1
		image : 1
		nav-menu : 1
		search-form : 1
	popup : 1
		heading : 1
		lottie : 1
	single : 1
		form : 1
		heading : 4
		theme-post-content : 1
		video : 1
	wp-page : 1
		button : 4
		eael-post-carousel : 1
		form : 1
		heading : 6
		video : 1

== Log ==
	
Log: showing 1 of 12020-06-10 17:07:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '2.10.0',
)]

JS: showing 3 of 3JS: 2020-06-10 22:56:43 [error X 4][http://www.fundacionparaguaya.org.py/v2/?post_type=elementor_library&p=9475&elementor-preview=9475&ver=1591829796:125:12] jQuery.okvideo is not a function 
JS: 2020-06-10 23:05:25 [error X 1][http://www.fundacionparaguaya.org.py/v2/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.11:31:95842] Cannot read property \&#039;message\&#039; of null 
JS: 2020-06-11 15:29:32 [error X 1][http://www.fundacionparaguaya.org.py/v2/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.10.0:2:106075] Cannot read property \&#039;match\&#039; of undefined

**Comment by KaneDriscol** [comment]
I'm experiencing a similar thing.

**Comment by robbhobbs** [comment]
Yep, me as well...

**Comment by vmonteswa** [comment]
Same here

**Comment by shilo-ey** [comment]
Can you please provide a JSON export of your page with this issue?

Thanks

**Comment by jrodrigovaldez** [comment]
> Can you please provide a JSON export of your page with this issue?
> 
> Thanks

The problem occurred when using the progress bar, it is solved by using another form of steps e.g. numbers. I finally had to change my form.

**Comment by kbrebel04** [comment]
> > Can you please provide a JSON export of your page with this issue?
> > Thanks
> 
> The problem occurred when using the progress bar, it is solved by using another form of steps e.g. numbers. I finally had to change my form.

This would not be solved. More like circumvented. This must be fixed for it to be solved as some of us would like to use the progress bar.

**Comment by arielk** [comment]
This issue has been resolved in Elementor Pro v2.10.3

Feel free to update

Thanks!

**Comment by israelmeirwi** [comment]
The form is sent but the user receives step 1 for a few seconds
