### ISSUE TITLE
Elementor Video Widget: Sponsor/Promo Videos

### ISSUE THREAD

**Issue by wpacademy** [elementor/elementor#11599]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

**What problem is your feature request going to solve? Please describe.**
It will give an option to content creators to monetize their videos on their own websites with direct sponsors

**Describe the solution you'd like**
There should be an option to add 2 video links, one with the actual video and one with a sponsor/custom video that plays before the actual video (skippable maybe just like YouTube ads).
It will help content creators like me to monetize videos on my own platform with sponsors. The example is my educational website which is built using elementor pro, ACF, and Learndash. For simple single tutorials, I have created a custom post type with custom elementor single template and used video widget to embed videos from YouTube an example can be seen [Here](https://wpacademy.pk/tutorial/web-design-speed-art-elementor-gaming/) 
So it will be a great feature for such websites to play some other video before playing the actual video.

**Describe alternatives you've considered**
There are solutions for native WordPress video shortcode like [this one](https://plugins360.com/wp-video-monetize/)
But it would be great if everything stays pure elementor. 

**Additional context**
I hope this can be considered a valuable addition to the core, otherwise, it's just maybe only me :)

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we'll add the options in the future we'll try to update here.

Thank you for your feedback
