### ISSUE TITLE
Elementor Form - Hide field bug report

### ISSUE THREAD

**Issue by Antotna** [elementor/elementor#11609]
Hello, I'm reporting a bug about Elementor form.

I did set up a form containing a hide field (linked to an ACF email field) and put the relative shortcode in the email "to" field.

The form always worked sending corretly the email but, since one of the last updates (I don't know which one), id doesn't work anymore.

Rolling back Elementor version - to 2.9.8 and 2.9.4 (pro) - it works again.

Thank you.

**Comment by shilo-ey** [comment]
I merged this issue with #11578, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
