### ISSUE TITLE
Excerpt in Archive Post widget shows pictures captions instead post excerpt

### ISSUE THREAD

**Issue by Iti1980** [elementor/elementor#11616]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I created a template for the search results.
During the design of the template with Elementor I see correctly the excerpt of the post, as I wrote during the post creation.
When I visualize the website live and I use the search form, the posts are shown with a different excerpt, that I verified to be composed from all the pictures captions.

## Steps to reproduce

1) Create some posts with the option excerpt filled
2) Add a gallery to the default post creation page, valueing caption for every picture
![gallery and excerpt](https://user-images.githubusercontent.com/65508986/84574220-3f370180-ada5-11ea-8fb9-266ea80957a4.jpg)
3) Create a template for the search results
4) See the correct excerpt during template design
<img width="712" alt="Archive widget design" src="https://user-images.githubusercontent.com/65508986/84574222-46f6a600-ada5-11ea-8cdd-2b1ecffb9eef.png">
5) Publish the template and open a post. You can see the different excerpt made by the pictures catpions
![archive visualization](https://user-images.githubusercontent.com/65508986/84574241-73aabd80-ada5-11ea-9e97-e657500222ab.jpg)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.25-28
	PHP Version: 7.3.18
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: https://www.itineriamo.com
	Home URL: https://www.itineriamo.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.12
		Author: Elliot Condon

	Autoptimize
		Version: 2.7.3
		Author: Frank Goossens (futtta)

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.11
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.6.4
		Author: WebTechStreet

	Elementor Pro
		Version: 2.10.0
		Author: Elementor.com

	GA Google Analytics
		Version: 20200325
		Author: Jeff Starr

	Relevanssi
		Version: 4.7.2.1
		Author: Mikko Saari

	Search & Filter
		Version: 1.2.12
		Author: Designs & Code

	Shortcoder
		Version: 5.3.1
		Author: Aakash Chakravarthy

	Ultimate Maps by Supsystic
		Version: 1.1.10
		Author: supsystic.com

	Under Construction
		Version: 3.75
		Author: WebFactory Ltd

	WP-Optimize - Clean, Compress, Cache
		Version: 3.1.2
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Fastest Cache
		Version: 0.9.0.7
		Author: Emre Vona

	Yoast SEO
		Version: 14.3
		Author: Team Yoast

== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		heading : 2
		spacer : 4
	footer : 1
		heading : 3
		spacer : 1
		theme-site-logo : 1
	header : 1
		html : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
		theme-site-logo : 1
	popup : 1
		button : 1
		heading : 1
	single : 1
		divider : 2
		gallery : 1
		heading : 3
		icon-list : 2
		post-comments : 1
		post-info : 1
		share-buttons : 1
		shortcode : 1
		spacer : 4
		text-editor : 2
	wp-page : 7
		call-to-action : 1
		counter : 4
		divider : 6
		form : 2
		heading : 28
		image-gallery : 2
		media-carousel : 1
		posts : 1
		shortcode : 2
		spacer : 18
		text-editor : 18

== Log ==
	
PHP: showing 11 of 11PHP: 2020-05-07 11:52:31 [notice X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::180] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-07 15:47:38 [warning X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/icomoon-4/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-08 23:39:59 [notice X 4][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/portfolio.php::49] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-10 16:41:53 [notice X 67][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::35] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-13 00:54:07 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044
Stack trace:
#0 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(1219, Object(stdClass))
#1 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/customer/www/itineriamo.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/customer/www/itineriamo.com/public_html/wp-includes/post.php(4153): do_action('save_post', 1219, Object(stdClass), true)
#4 /home/customer/www/itineriamo.com/public_html/wp-includes/post.php(4244): wp_insert_post(Array, fa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-16 21:54:01 [notice X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::771] ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-16 21:54:24 [notice X 3][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::692] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-17 15:39:07 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/itineriamo.com/public_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-19 11:57:35 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(825, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/itineriamo.com/public_h [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-19 11:59:51 [notice X 2][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-05 11:08:08 [notice X 110][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::117] Trying to get property 'post_title' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 26JS: 2020-05-15 10:04:31 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view7471\") has already been destroyed and cannot be used. 
JS: 2020-05-15 12:46:33 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view65484\") has already been destroyed and cannot be used. 
JS: 2020-05-15 12:46:55 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view66207\") has already been destroyed and cannot be used. 
JS: 2020-05-15 13:40:59 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:5] d is not defined 
JS: 2020-05-15 13:40:59 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:5] docu is not defined 
JS: 2020-05-15 13:40:59 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:5] docume is not defined 
JS: 2020-05-15 13:41:00 [error X 4][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:3:1] Unexpected end of input 
JS: 2020-05-15 13:41:15 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:4] dou is not defined 
JS: 2020-05-15 13:41:42 [error X 10][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:13] document.getElementByID is not a function 
JS: 2020-05-15 13:42:36 [error X 68][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:12:25] Invalid or unexpected token 
JS: 2020-05-15 14:08:44 [error X 6][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:10:5] Unexpected token \'<\' 
JS: 2020-05-15 14:08:48 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:10:1] Unexpected token \'>\' 
JS: 2020-05-15 14:08:53 [error X 2][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:46] Cannot set property \'onclick\' of null 
JS: 2020-05-15 17:10:16 [error X 2][https://www.itineriamo.com/wp-content/plugins/addon-elements-for-elementor-page-builder/assets/js/eae.min.js?ver=1.0:1:311] google is not defined 
JS: 2020-05-16 15:07:00 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view35545\") has already been destroyed and cannot be used. 
JS: 2020-05-18 07:08:32 [error X 5][https://www.itineriamo.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:168588] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-05-20 12:41:24 [error X 2][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-05-28 10:42:45 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.9:31:175382] f is not a constructor 
JS: 2020-05-29 08:23:47 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:17] Unexpected identifier 
JS: 2020-06-04 16:20:14 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.11:31:62095] elementorFrontend is not defined 

Log: showing 6 of 62020-05-07 17:34:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-05-24 17:55:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-05-24 17:55:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-06-01 23:09:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.10',
)]
2020-06-03 10:52:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.10',
  'to' => '2.9.11',
)]
2020-06-12 10:10:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '2.10.0',
)]

**Comment by alexstandiford** [comment]
> PHP: 2020-05-13 00:54:07 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044

I received a similar error as the one above today:

```
Uncaught TypeError: Argument 2 passed to ElementorTemplateLibrarySource_Local::on_save_post() must be an instance of WP_Post, null given, called in /www/wp-includes/class-wp-hook.php on line 289 and defined in /www/wp-content/plugins/elementor/includes/template-library/sources/local.php:1081 Stack trace: #0 /www/wp-includes/class-wp-hook.php(289): ElementorTemplateLibrarySource_Local->on_save_post(396205, NULL) #1 /www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /www/wp-includes/post.php(4153): do_action('save_post', 396205, NULL, true) #4 /www/wp-includes/post.php(4244): wp_insert_post(Array, false) #5 /www/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(797): wp_update_post(Array) #6 /www/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/migration/ActionMigrator.php(102): ActionScheduler_wpPostStore->mark_migrated(
```

This error is logged dozens of times in our logging system during times late last week, and I'm not sure what caused it. We did a little work on the site, but all of it was on a custom post type that is not using Elementor

**Comment by Iti1980** [comment]
Hi, finally I solved this issue since I opened the ticket.
Thanks,
Alessandro



Inviato da smartphone Samsung Galaxy.



-------- Messaggio originale --------
Da: Alex Standiford <notifications@github.com>
Data: 29/06/20 19:49 (GMT+01:00)
A: elementor/elementor <elementor@noreply.github.com>
Cc: Iti1980 <itineriamo@hotmail.com>, Author <author@noreply.github.com>
Oggetto: Re: [elementor/elementor] Excerpt in Archive Post widget shows pictures captions instead post excerpt (#11616)


PHP: 2020-05-13 00:54:07 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044

I received a similar error as the one above today:

Uncaught TypeError: Argument 2 passed to ElementorTemplateLibrarySource_Local::on_save_post() must be an instance of WP_Post, null given, called in /www/wp-includes/class-wp-hook.php on line 289 and defined in /www/wp-content/plugins/elementor/includes/template-library/sources/local.php:1081 Stack trace: #0 /www/wp-includes/class-wp-hook.php(289): ElementorTemplateLibrarySource_Local->on_save_post(396205, NULL) #1 /www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /www/wp-includes/post.php(4153): do_action('save_post', 396205, NULL, true) #4 /www/wp-includes/post.php(4244): wp_insert_post(Array, false) #5 /www/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php(797): wp_update_post(Array) #6 /www/wp-content/plugins/wp-mail-smtp/vendor/woocommerce/action-scheduler/classes/migration/ActionMigrator.php(102): ActionScheduler_wpPostStore->mark_migrated(


This error is logged dozens of times in our logging system during times late last week, and I'm not sure what caused it. We did a little work on the site, but all of it was on a custom post type that is not using Elementor

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
