### ISSUE TITLE
links to viber by type do not work  viber://chat?number=%2B375292005818

### ISSUE THREAD

**Issue by PSV-Pecha** [elementor/elementor#11619]
links to viber by type do not work    viber://chat?number=%2B375292005818
the link leads to the main page of the site

**Comment by shilo-ey** [comment]
Hi @PSV-Pecha 

Thanks for reporting.

We will take a look and release a patch to this issue soon.

In the meanwhile you can add the Viber protocol to your allowed protocols by WP:

Read more here: https://developers.elementor.com/uri-protocols-handling-update/

Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.4

Feel free to update

Thanks!
