### ISSUE TITLE
[Idea] Save form contents on browser closing / accidental reloading

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#11629]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, if you build a form in Elementor, and it happens to be lengthy, there is a risk that form data is lost if the user accidentally closes their browser tab, reloads it, or otherwise has a crash of some kind.

**Describe the solution you'd like**
I recently set up [Savy.js](https://github.com/medabida/savy) on a client website and it works wonderfully with Elementor forms, it stores form data into HTML5 LocalStorage. 

This script could be activated with a toggle on the regular / multistep form widget settings, to enable or disable it. You can also program a button for the user to clear the form data if needed.

So it would be nice to see this as a standard optional feature in Elementor, to make forms even more user friendly :)

**Describe alternatives you've considered**
Savy.js, manual implementation. The class I targeted with Savy.js is `.auto-save .elementor-field`, and I added `.auto-save` manually to the element's CSS settings.

**Comment by drawcard** [comment]
I've since discovered that Savy.js isn't working in the latest Safari browser, but it looks like Sisyphus.js does. Just in case this idea is implemented :)

Project: https://github.com/simsalabim/sisyphus

Demo: http://sisyphus-js.herokuapp.com/#controls-sample

**Comment by rami-elementor** [comment]
Hi @drawcard ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap. 

Please feel free to contact us again with other feature suggestions.

Regards,
