### ISSUE TITLE
Show/hide button on Price List items

### ISSUE THREAD

**Issue by angui72** [elementor/elementor#11627]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Creating and deleting items every day, for restaurantes for example.

**Describe the solution you'd like**
The same item is available on sunday and not on friday and then again on saturday, so users have to delete the item, the solution is simply hide the unavailable items and when they are available show them again.

**Describe alternatives you've considered**
None, I think this is the better way to do it.

**Additional context**

**Comment by arielk** [comment]
I'm not sure I realized, what solution are you looking for?

**Comment by angui72** [comment]
There is a widget in Elementor Pro called Price List, when editing this widget we have the List Items, at the top there are 2 buttons, one to copy the other to delete, my suggestion is to place a third button to hide the item, so if, for example, a restaurant has sea bass on one day, and on the other day it does not, and on the third day it has it again, the user instead of deleting and then creating the item again, hides it on the days that it does not have and shows it on the days where they have it, avoiding the trouble of repeatedly creating the same item.

**Comment by angui72** [comment]
> I'm not sure I realized, what solution are you looking for?

There is a widget in Elementor Pro called Price List, when editing this widget we have the List Items, at the top there are 2 buttons, one to copy the other to delete, my suggestion is to place a third button to hide the item, so if, for example, a restaurant has sea bass on one day, and on the other day it does not, and on the third day it has it again, the user instead of deleting and then creating the item again, hides it on the days that it does not have and shows it on the days where they have it, avoiding the trouble of repeatedly creating the same item.

**Comment by arielk** [comment]
Ok, thanks for your feedback.
I suggest you save the widget as global so you can add / remove the widget when needed.

I do not see that we are going to implement these requests in the near future so I close this issue, If we add the options in the future, we'll try to update here.

**Comment by angui72** [comment]
> Ok, thanks for your feedback.
> I suggest you save the widget as global so you can add / remove the widget when needed.


Reading your answer I think my English was not good enough to express my point. thanks anyway.

**Comment by arielk** [comment]
I think I understood you so I recommended you the workaround. In the meantime, you can follow a similar request: https://github.com/elementor/elementor/issues/4246

**Comment by angui72** [comment]
> I think I understood you so I recommended you the workaround. In the meantime, you can follow a similar request: #4246

Not wanting to be boring, here's an image of my idea. It is not a solution for the widget, but for individual items. thank you.

![hide-show](https://user-images.githubusercontent.com/66921637/85369726-894a8080-b525-11ea-9135-75a4ee9d919a.jpg)

**Comment by Musta367890** [comment]
hello angui77,

then you have found an alternative solution, I have the exact same problem every time I have to delete the entry rather than simply hide it

Regards,
M.

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
