### ISSUE TITLE
Problem CSS?

### ISSUE THREAD

**Issue by DemoMann** [elementor/elementor#11638]
Hello!
I don't understand why there's this misalignment.
Will you please help me?

https://beta.worlamb.com/contatti-worlamb/
Click First button.
Thanks

![allineamento-form](https://user-images.githubusercontent.com/48436845/84693376-adb3c500-af47-11ea-92d1-614e9de0badf.jpg)

**Comment by arielk** [comment]
This is something we have recently fixed, please update Elementor Pro to the latest version and let me know if it works for you
