### ISSUE TITLE
🛟 Support Request: Elementor Login Form - redirect after login to wishlist member dashboard

### ISSUE THREAD

**Issue by morrnel** [elementor/elementor#11637]
Hello,
I have Elementor Pro and wish to create a login page or popup do that will direct to a member's dashboard which may be one of three.   Seems as though there is only one option.  How do I make this happen?
Thanks.

**Comment by arielk** [comment]
You can set the URL after login in advanced settings, please read more here: https://docs.elementor.com/article/208-login
