### ISSUE TITLE
The multi-steps not work

### ISSUE THREAD

**Issue by DemoMann** [elementor/elementor#11636]
Hello!
I created a multistep questionnaire.
You can see it here:
https://beta.worlamb.com/contatti-worlamb
(click the first button)

The first step is blocked and it doesn't go on.
This is the error I see in Console

Uncaught ReferenceError: dce_validate_step is not defined
    at HTMLButtonElement.<anonymous> (?preview_id=6231&preview_nonce=c027ac087b&preview=true:187)
    at HTMLButtonElement.dispatch (jquery.js:3)
    at HTMLButtonElement.r.handle (jquery.js:3)

**Comment by shilo-ey** [comment]
It seems like you're using Dynamic Content for Elementor plugin to achieve this step.

Either use Elementor Pro native multi-step form or contact them to resolve this issue.

**Comment by DemoMann** [comment]
I'm working using the Elementor Pro form. I'm not using Dynamic widgets for this form.
![Form-problem](https://user-images.githubusercontent.com/48436845/84678833-c6fd4700-af30-11ea-9bde-661b277e26d7.jpg)

**Comment by DemoMann** [comment]
Forgive me, you're right. I did solve the problem. Thank you very much!

**Comment by marlonmafia** [comment]
> Forgive me, you're right. I did solve the problem. Thank you very much!

How did you solved this problem?
