### ISSUE TITLE
Space between title and Hero image

### ISSUE THREAD

**Issue by ilan1602** [elementor/elementor#11631]
Hi, I don't manage to delete the space between the Menu and Hero Image on the top of my website, and the same on the bottom, there's a space under my footer.
Note that I do hide the title, it doesn't help. 
Thank you

![Capture d’écran 2020-06-15 à 13 54 10](https://user-images.githubusercontent.com/66949184/84650024-2e56cf00-af10-11ea-9376-4dd118e3864c.png)
![Capture d’écran 2020-06-15 à 13 54 16](https://user-images.githubusercontent.com/66949184/84650028-30209280-af10-11ea-8375-c4524b0fd540.png)

**Comment by lior-sh** [comment]
Hi @ilan1602,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
