### ISSUE TITLE
🔗 🔃 🚀 Feature Request: GDPR compliance for Elementor Forms files (Merged with #4868)

### ISSUE THREAD

**Issue by sss9212** [elementor/elementor#11641]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As everyone knows, GDPR compliance is an important issue when dealing with customers from EU. For business websites using Elementor Forms, it is important to have a feature than can put the website owner in control of how the files/information upload through Elementor forms is stored and processed.

**Describe the solution you'd like**
Add GDPR compliance features to Elementor Forms similar to other form builders like WPForms, which gives complete control to the website owner on how the data/files collected through Elementor forms are stored and ability to delete the data collected if the user requests.

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment]
Ref: 
https://github.com/elementor/elementor/issues/1686
https://github.com/elementor/elementor/issues/4868

**Comment by nicholaszein** [comment]
Hello @sss9212!

Thank you for your submission! 🙏 

### 🔃 We are Merging this issue with #4868.

Which is on the same subject. 

For this reason, I'm closing this issue so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Kind regards

**Comment by nicholaszein** [comment]
Hello there @sss9212!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
