### ISSUE TITLE
Elementor form redirect doesn't work 

### ISSUE THREAD

**Issue by Gildabass** [elementor/elementor#11644]
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Since Elementor Pro update 2.10.1 this morning, form field dynamic request is fixed, but now redirect is broken… current page simply reload

## Steps to reproduce

create a form 
set a redirection to an existing page (with or without dynamic parameters) 
test… click submit… no redirection…

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.28
	PHP Version: 7.3.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: https://thesmartfellows.com
	Home URL: https://thesmartfellows.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.3.0.1591624942
	Author: Gildas BENOIT
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

== Active Plugins ==
	Child Theme Configurator
		Version: 2.5.5
		Author: Lilaea Media

	Easy WP SMTP
		Version: 1.3.9.3
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 2.9.12
		Author: Elementor.com

	Elementor Pro
		Version: 2.10.1
		Author: Elementor.com

	EmbedPress
		Version: 2.5.5
		Author: WPDeveloper

	Essential Addons for Elementor
		Version: 4.0.3
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.0.0
		Author: WPDeveloper

	Google Analytics Dashboard for WP (GADWP)
		Version: 6.0.2
		Author: ExactMetrics

	Popup Trigger URL for Elementor Pro
		Version: 1.0.3
		Author: Suki WordPress Theme

	Premium Addons for Elementor
		Version: 3.20.5
		Author: Leap13

	Yoast SEO
		Version: 14.3
		Author: Team Yoast

== Elements Usage ==
	
	footer : 2
		heading : 3
		icon : 1
		image : 1
		nav-menu : 1
	header : 1
		image : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 24
		icon-box : 15
	popup : 2
		form : 2
		heading : 3
		image : 1
		theme-site-logo : 1
	section : 17
		eael-adv-tabs : 1
		eael-divider : 10
		form : 1
		heading : 4
		icon-box : 3
		image : 20
		menu-anchor : 1
		text-editor : 19
	single : 1
		form : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	widget : 0
		eael-adv-tabs : 4
	wp-post : 4
		eael-data-table : 4
		form : 1
		heading : 4
		image : 4
		text-editor : 1
	wp-page : 3
		button : 7
		counter : 6
		eael-adv-tabs : 3
		eael-team-member-carousel : 1
		embedpres_elementor : 1
		form : 4
		heading : 13
		icon-box : 3
		image : 3
		image-carousel : 1
		lottie : 1
		menu-anchor : 4
		premium-lottie : 1
		spacer : 3
		text-editor : 13
		theme-site-logo : 1

== Log ==
	
PHP: showing 20 of 35PHP: 2020-05-25 15:25:41 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341048 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-25 15:34:22 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10340952 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-25 15:58:49 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341296 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-25 16:00:01 [error X 2][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341376 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-25 16:10:49 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341336 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-25 16:13:22 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341176 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-25 16:16:24 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341360 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:25:05 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341432 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:26:17 [error X 2][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341320 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:28:57 [error X 2][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341344 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:29:26 [error X 2][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341408 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:29:43 [error X 2][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341280 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:50:40 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341240 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:51:21 [error X 3][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341272 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:54:44 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341256 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 08:59:12 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341304 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 09:46:40 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341312 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 09:51:35 [error X 2][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341264 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-26 09:52:29 [error X 1][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 10341352 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-02 11:16:05 [notice X 7][/var/www/vhosts/thesmartfellows.com/httpdocs/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::218] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2020-05-25 13:39:28 [error X 4][https://thesmartfellows.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.9.9:2:42537] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `eael_accordion_bg` value. Expected array or object.',
)]
JS: 2020-05-25 14:40:58 [error X 7][https://thesmartfellows.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.9.9:2:42537] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `eael_flip_carousel_slide` value. Expected array or object.',
)]

Log: showing 6 of 62020-05-26 12:16:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-06-02 02:21:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.10',
)]
2020-06-02 11:01:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.10',
  'to' => '2.9.11',
)]
2020-06-08 13:51:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '2.10.0',
)]
2020-06-15 02:21:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.12',
)]
2020-06-16 08:59:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.0',
  'to' => '2.10.1',
)]

				
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by Gildabass** [comment]
WOW ! V2.10.2 is already on, and issue is Fixed ! Never seen an update so reactive !!

**Comment by datorium** [comment]
We experience the same problem after the recent update. Elementor team, please address this issue asap, as our clients are very confused and we may loose many because of this issue :/

**Comment by DeveloperWil** [comment]
Same issue here - Elementor Pro with Hello theme

**Comment by SRTooley** [comment]
Same issue here - Elementor Pro with Hello theme

**Comment by ryanfurtner** [comment]
Yep Im getting it too, elementor pro on astra pro theme. Nginx hosting environment.

**Comment by ryanfurtner** [comment]
I got it working by entering the whole URL, not just /thank-you

**Comment by DeveloperWil** [comment]
Yes, that works for me too - full URL.

**Comment by eSilverStrike** [comment]
Yes this is still an issue. Only the full URL works which is not ideal for those who want everything to work when they migrate the development site to the live site on a different domain. 

Please reopen this issue.

**Comment by insitedigitalmedia** [comment]
This should be re-opened.  1) relative redirect URL does not work and more importantly 2) full path does not redirect when URL parameters are included.  This is affecting a multi step production lead gen site.

**Comment by intissar962** [comment]
Me too i have this issue, i put the full URL but it doesn't working

**Comment by glanglois** [comment]
Hi Elementor Team,

I have the same issue with the Login Form. The redirect doesn't work for dynamic URL or full path URL.
I am using Elementor 3.1.0 and Elementor Pro 3.0.10. 

Thank you for your help. Regards

**Comment by rthomas98** [comment]
Same here, the administrator redirect works but not the other roles.

**Comment by lelas** [comment]
Experiencing the same. Form redirect isn't working at all.

**Comment by SOCPilot** [comment]
Still a problem and the %20 solution didn't work. Was working until a week or two ago.  I tried just a simple redirect to Google and that didn't work either.

**Comment by Martydesign** [comment]
Redirect doesn't work on Iphones, is someone even going to fix this bug?

**Comment by saytionne** [comment]
This is still having issues. I receive the error even with the fix and all I'm trying to do is to get it to redirect after clicking submit (no email collection, etc).

**Comment by srighee** [comment]
It´s working fine with Elementor 3.0.6.

**Comment by SOCPilot** [comment]
Actually it's not in our implementation. None of the redirect or actions are firing. We had to remove the Elementor form. Was working on earlier versions.

**Comment by frindly** [comment]
+1 this is still broken

**Comment by frindly** [comment]
Found the issue i was having:
 I’m running my site behind an SSL load balancer, and using the insecure content fixer plugin.  The experiment “Improved Asset Loading” loads some js after the page is loading, these loads are NOT fixed by the plugin and caused the form code that does the redirect to be blocked as insecure content.  Disabling this experiment fixed the issue for me.

**Comment by gerardreches** [comment]
@frindly my redirects also aren't working right now. Last comment was in Oct 21, 2021 and we suddenly both have this issue the same day? It doesn't look like a coincidence.
