### ISSUE TITLE
Repeater field: crashes when adding a new item

### ISSUE THREAD

**Issue by chrisbrine** [elementor/elementor#11650]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I created a skin for elementor post listings and added a repeater type. The bug seems to not always appear but sometimes when adding an item it crashes the frontend javascript. I don't see anything in particular that is wrong with my code for it and it usually does work.

But occassionaly it will crash saying: TypeError: Cannot read react_devtools_backend.js:6 property 'id' of undefined at i.get (editor.min.js) etc.

I'll include screenshots for you.
<img width="401" alt="Screen Shot 2020-06-16 at 10 48 41 AM" src="https://user-images.githubusercontent.com/40341122/84818857-04fb7900-afcc-11ea-95e4-fa715de2b56b.png">
<img width="248" alt="Screen Shot 2020-06-16 at 10 48 48 AM" src="https://user-images.githubusercontent.com/40341122/84818865-07f66980-afcc-11ea-9609-b11b54420dff.png">
<img width="256" alt="Screen Shot 2020-06-16 at 11 23 57 AM" src="https://user-images.githubusercontent.com/40341122/84818866-07f66980-afcc-11ea-8719-7fe730d6fc73.png">
<img width="349" alt="Screen Shot 2020-06-16 at 11 24 02 AM" src="https://user-images.githubusercontent.com/40341122/84818867-088f0000-afcc-11ea-8d4d-70fb1c3c3540.png">

## Steps to reproduce

It does not always happen. It only happens sometimes when clicking 'add item' in a repeater type. Whenever it happens it seems to be temporarily resolved by saving the form and restarting the editor. Then it shows the created fields and works ok again for awhile before breaking again.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.25
	PHP Version: 7.3.18-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: http://realty-demo.flywheelsites.com
	Home URL: http://realty-demo.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.5
		Author: Elementor.com

	Realty Base Plugin
		Version: 1.000
		Author: Chris Brine

	WP Crontrol
		Version: 1.8.5
		Author: John Blackbourn & crontributors


== Elements Usage ==
	
	archive : 1
		posts : 1
	single : 1


== Log ==
	
Log: showing 2 of 22020-06-06 21:28:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.11',
)]
2020-06-11 22:26:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '2.10.0',
)]

PHP: showing 3 of 3PHP: 2020-06-11 21:34:02 [error X 1][/www/wp-content/plugins/elementor/includes/base/widget-base.php::776] Uncaught ArgumentCountError: Too few arguments to function Elementor\Widget_Base::add_skin(), 0 passed in /www/wp-content/plugins/realty-base-plugin/modules/elementor-posts-skins/skins/skins.php on line 68 and exactly 1 expected in /www/wp-content/plugins/elementor/includes/base/widget-base.php:776
Stack trace:
#0 /www/wp-content/plugins/realty-base-plugin/modules/elementor-posts-skins/skins/skins.php(68): Elementor\Widget_Base->add_skin()
#1 /wordpress/wp-includes/class-wp-hook.php(287): BB\Elementor\Posts\Skins\Plugin->BB\Elementor\Posts\Skins\{closure}(Object(ElementorPro\Modules\Posts\Widgets\Posts))
#2 /wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /www/wp-content/plugins/elementor/includes/base/widget-base.php(133): do_action('elementor/widge...', Object(ElementorPro\Modules\Posts\Widgets\Posts))
#5 /www/wp-content/plugins/elementor-pro/base/module-base.php(27): Elementor\Widget_Base->__construct()
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-11 22:44:02 [notice X 91][/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php::311] Undefined index: cards_custom_open_new_tab [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-11 22:55:33 [notice X 4][/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php::311] Undefined index: full_content_custom_open_new_tab [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2020-06-11 22:43:46 [error X 1][http://realty-demo.flywheelsites.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.4.2:10:1314] e.toLowerCase is not a function 
JS: 2020-06-12 23:24:12 [error X 43][http://realty-demo.flywheelsites.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:768] Cannot read property \'cid\' of undefined 
JS: 2020-06-15 20:24:17 [error X 74][http://realty-demo.flywheelsites.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:767] undefined is not an object (evaluating \'a.cid\') 
```
</details>

**Comment by shilo-ey** [comment]
Can you please add the custom skin code you created?

Maybe try isolating when this issue is happening so we could help?

Thanks

**Comment by latheeshvmv** [comment]
@shilo-ey , @chrisbrine  Noticing the same bug. The problem happens after saving page /reload. If you try clicking the add button it will stop working with the errors as shown in the screenshot.

The problem started after the update 2.9.8 
Fix: Render style on repeater item change in Page Settings

![image](https://user-images.githubusercontent.com/44595562/86004316-c1bff200-ba30-11ea-805a-521e144c0c32.png)

Please fix

**Comment by latheeshvmv** [comment]
@shilo-ey https://github.com/elementor/elementor/issues/11523

**Comment by chrisbrine** [comment]
> Can you please add the custom skin code you created?
> 
> Maybe try isolating when this issue is happening so we could help?
> 
> Thanks

I can't seem to reproduce it. Tried a bunch of times. It just seems to happen randomly. Once saving and reloading it works again.

I've had this happen with a few repeater fields and not just the skin though.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
