### ISSUE TITLE
✅ 🚀 Feature Request: Add "Blend Mode" and or "CSS Filters" settings to Flipbox > Back > Background Overlay

### ISSUE THREAD

**Issue by myVarEquals** [elementor/elementor#11653]
[ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allow developers to add more style effects to backgrounds on hover, namely blend effects like blurring. Currently sections and columns, and maybe more places I'm unaware of yet, allow you to set Blend Modes and CSS Filter settings on Background Overlays. 

**Describe the solution you'd like**
The way sections/columns are structured, the background overlay div is a sibling to a container div that houses the content. Can we do the same for Flipbox background overlays?

**Describe alternatives you've considered**
My only solution was to export additional background images from Adobe XD with the overlay on them, in turn doubling the file space for these images.

I recently worked on a project that I had planned to used Flipboxes in a part of the development. The cards' were supposed to blur the background on hover and reveal text. Flipboxes allowed for all of this except the blur effect. The way the Flipbox is coded in HTML, the background overlay div is a parent to everything. As such, adding CSS to blur the background div blurs everything, including the text and button.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.0

Feel free to update

Thanks!
