### ISSUE TITLE
New Section Area z-index: 999999

### ISSUE THREAD

**Issue by RemPro** [elementor/elementor#11652]
in some design circumstances the New Section Area is not reachable

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
