### ISSUE TITLE
error elementor/includes/base/controls-stack.php on line 1445

### ISSUE THREAD

**Issue by OsoBear** [elementor/elementor#11675]
WP_DEBUG is enabled. Two errors: 

elementor/includes/base/controls-stack.php on line 1445
and 
elementor/includes/base/controls-stack.php on line 1447

**Comment by AFinciuc** [comment]
@OsoBear Have you found a solution yet?
I'm having the same problem, curious whats causing it and how to solve it.
Might not be relevant, but I'm using PHP 7.4.
I hope someone replies.

**Comment by OsoBear** [comment]
> @OsoBear Have you found a solution yet?
> I'm having the same problem, curious whats causing it and how to solve it.
> Might not be relevant, but I'm using PHP 7.4.
> I hope someone replies.

No...never found a fix. ;-(

**Comment by arielk** [comment]
Thanks for reporting,

This report is missing key information: 

* **Prerequisites**.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Without it we simply can't help.

Thanks
