### ISSUE TITLE
Animated Headline widget extension issue

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#11671]
@bainternet @shilo-ey 
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I extended the animated headline widget to add a new heading style and now getting an error due to some js code that presumes that the headline style should be a value between `highlight` and `rotate`.  In more detail, inside the widget's `onInit` method the `fillWords` method is being called which does an `if else` check on the `elementSettings.headline_style` value. This of course produces errors with `undefined` values inside functions that are being called resulting to `TypeError` exceptions.

## Possible Solutions

1. The `fillWords` function should only be called if the headline style value is  `highlight` or `rotate`.
2. The `fillWords` function should `return`  if the headline style value is different than  `highlight` or `rotate`.

**Comment by arielk** [comment]
Can you please share with us the code you are writing so we can check it out and help?
