### ISSUE TITLE
Custom query ID in Theme builder

### ISSUE THREAD

**Issue by netwaretcs** [elementor/elementor#11679]
Hello, it seems that the "custom query ID" feature if used in the theme builder is then totally ignored in the post.

Steps to reproduce the problem:

1. I created a template (theme builder - single)
2. I have inserted a posts widget
3. I added an ID query
4. I created the associated snippet for the query

`it would seem that the "custom query ID" feature if used in the theme builder is then totally ignored in the post.

Steps to reproduce the problem:

1. I created a template (theme builder - single)
2. I have inserted a posts widget
3. I added an ID query
4. I created the associated snippet

```php
// Showing post by category
add_action( 'elementor/query/news_com', function( $query ) {
	$com = get_field('nome_com');
	$query->set( 'category_name', $com );
} );
```

or without ACF, it's the same

```php
// Showing post by category
add_action( 'elementor/query/news_com', function( $query ) {
	$com = 'mycategory';
	$query->set( 'category_name', $com );
} );
```

In the elementor preview (theme builder) the query works, but in the single (post) the query is totally ignored. 

I also tried debugging by adding an echo+exit in the function, but nothing, the function does not start.

**Comment by netwaretcs** [comment]
Never mind, I solved the problem myself. It's not a bug.

**Comment by bainternet** [comment]
Glad you figured it out.
