### ISSUE TITLE
Gallery widget

### ISSUE THREAD

**Issue by milorad-micko** [elementor/elementor#11688]
I wanted to see my Page created with elementor Pro on my Samsung Smart TV with Samsung Smart TV - Webbrowser. Everthing ok,  but Images From Gallery widget are invisible. The Images come up only vor a second and disapear immediatly.
![15925955877895569583061906761628](https://user-images.githubusercontent.com/67166740/85174336-7447c600-b275-11ea-90cc-ba4826e20e4a.jpg)
![15925958627054741758346821507301](https://user-images.githubusercontent.com/67166740/85174689-24b5ca00-b276-11ea-82f7-593f8542f067.jpg)
I am using at moment the Last Version Elementor 2.9.12 and Pro 2.10.1
I Hope it is usfull for you

**Comment by lior-sh** [comment]
Hi @milorad-micko,

The editor supports the following browsers:
- Chrome
- Firefox
- Safari
- Microsoft Edge version 79 or greater.
Thanks.
