### ISSUE TITLE
Wrong row structure inside inner section

### ISSUE THREAD

**Issue by wayheming** [elementor/elementor#11683]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello, I found that the structure row inside the inner section has the wrong display. Checked only on 3 columns maybe there is a problem in other versions.

http://prntscr.com/t2pzqq
http://prntscr.com/t2q004
http://prntscr.com/t2q07k

## Steps to reproduce

Create an inner section
Add three columns
Change structure to 25, 25, 50 or 25, 50, 25 or 16, 66, 16

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
