### ISSUE TITLE
Enable pop-ups to be launched from anywhere even outside elementor

### ISSUE THREAD

**Issue by JohnMulderFrance** [elementor/elementor#11682]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I need to lauch an elementor pop-up from within another plug-in. I use a plug-in to get that done and it works. (Popup Trigger URL for Elementor Pro)
However in one of the last versions of Elementor Pro you changed something in the way Pop-up are called, the plug-in "Popup Trigger URL for Elementor Pro" was updated to cope with that change.
So far, so good you would say but i was forced the recreate all pop-up launches. The work that took was not that considerable, however making sure none of these launches was forgotten took me some time.

Coming to the conclusion of this request: in my honest opinion this feature should be incorporated in Elementor itself and not be left to a plugin developer outside elementor.

Best,
John

**Comment by shilo-ey** [comment]
Hi @JohnMulderFrance 

Have you tried triggering an Elementor Popup using an ID/CSS?
https://docs.elementor.com/article/472-popups#customselector

It should help you incorporate it into other elements/plugins.

Thanks

**Comment by JohnMulderFrance** [comment]
Hi,

Maybe i did not make myself clear: i have to open the pop-up through a URL
within a booking plug-in.
This plug-in allows me to change texts, include a link and that is it. No
ID/CSS possibility.
FYI this is a text used now, with the use of the plugin i described:
"Pay the deposit of 50% now, <strong><a
href="#elementor-action%3Aaction%3Dpopup%3Aopen%26settings%3DeyJpZCI6IjIxNzE4IiwidG9nZ2xlIjpmYWxzZX0%3D">online</a></strong>,
if you arrive in more than 2 months.<br> You can pay with iDEAL, Bancontact
or Creditcard"

Clicking on the link "online" opens up an elementor pop-up where the
conditions and handling of the online payment is described.

Enabling Elementor pop-ups to work from/together with other plug-in looks
like a bonus to me. I am sure that you will recognize better than me what
this plugin Popup Trigger URL for Elementor Pro does within/expands the
possibilities of Elementor.

Best,
John

*Mas Bernadis*
Cora Morren, John Mulder & Luca Mulder

Route des Bois
30160 Robiac-Rochessadoule
France

+33 466 60 42 87

www.masbernadis.eu


Op vr 19 jun. 2020 om 17:21 schreef shilo-ey <notifications@github.com>:
