### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Allow lottie animations to play as a background element (Merged with #20444)

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#11698]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be nice to allow section / column backgrounds to load Lottie animations. This is handy for when you want a Lottie animation to fill a background, but still overlay type / buttons over it.

**Describe alternatives you've considered**
It can currently be done with absolute positioning / z-indexing of a Lottie widget but it doesn't auto-fill the container well.

**Comment by alexplayer** [comment]
Still no such feature?

**Comment by alexsebdev** [comment]
Im waiting on this aswell.

**Comment by ekzig** [comment]
This would be super handy. Hoping this will be implemented in the future.

**Comment by markbosky** [comment]
+1

**Comment by juliettecurran** [comment]
Was just googling trying to find out how to do this, so agreed. +1

**Comment by luminxa** [comment]
look like the only ones who have something out for something like this but its not elementor :/ im looking for a portable solution for this as well https://fusionelegantelements.com/lottie-animation-column-background/

**Comment by yawalkar** [comment]
Hey everyone!

I have received quite a few requests on a daily basis for this, so I made a tiny plugin for Elementor to let you add Lottie Animations to Elementor sections and columns. You can grab it from here - [https://www.infiwebs.com/lottie-bg-elementor/](https://www.infiwebs.com/lottie-bg-elementor/)

If you have any questions, or need any help with this plugin, please feel free to contact me.

Kind regards,
Nitin

**Comment by TitanEraGlobal** [comment]
+1

**Comment by TitanEraGlobal** [comment]
+1

**Comment by endombed** [comment]
+

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔃  This request is being merged with #20444.

Which is on the same subject. 

For this reason, I'm closing the comments, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
