### ISSUE TITLE
Why with Elementor with Astra theme + ACF and wysiwyg editor missing tag <p>?

### ISSUE THREAD

**Issue by exolon82** [elementor/elementor#11693]
I use **ACF** for add on  "aboutme" page the **wysiwyg editor**, 
when use wysiwyg editor, it does not automatically put the <p> </p> tag, but I should put it manually, and this is not a good thing

in the images I have attached, I showed the editor, and then as seen in the preview, that is, the text does not wrap

When I go to see the page you can see from the images that the text is not put back. nothing <br> nothing <p>

Please help me!

![104475875_2306496712978421_3770153119356612889_n](https://user-images.githubusercontent.com/16225287/85202185-e61b2080-b304-11ea-8278-bd597afb5192.jpg)

This is the image of how you see it
![104771814_2306497299645029_2394589992621493986_o](https://user-images.githubusercontent.com/16225287/85202186-e6b3b700-b304-11ea-818a-fd3c8f44d5c8.jpg)

![Annotazione 2020-06-21 224314](https://user-images.githubusercontent.com/16225287/85234898-21a31100-b411-11ea-9b9d-bc72f62069bc.png)
![Annotazione 2020-06-21 224408](https://user-images.githubusercontent.com/16225287/85234899-22d43e00-b411-11ea-9d5f-239821f358ab.png)
![Opera Snapshot_2020-06-21_224542_](https://user-images.githubusercontent.com/16225287/85234900-22d43e00-b411-11ea-98c9-b324eb9525f0.png)

**Comment by adempius** [comment]
> example: i use **ACF** for add on "aboutme" page the **wysiwyg editor**, when use editor, it does not automatically put the
> 
> tag, but I should put it manually, and this is not a good thing
> in the images I have attached, I showed the editor, and then as seen in the preview, that is, the text does not wrap
> Please help me!
> 
> ![104475875_2306496712978421_3770153119356612889_n](https://user-images.githubusercontent.com/16225287/85202185-e61b2080-b304-11ea-8278-bd597afb5192.jpg)
> 
> This is the image of how you see it
> ![104771814_2306497299645029_2394589992621493986_o](https://user-images.githubusercontent.com/16225287/85202186-e6b3b700-b304-11ea-818a-fd3c8f44d5c8.jpg)

follow

**Comment by exolon82** [comment]
with shortcode solved

**Comment by Axel186** [comment]
Have the same issue.
Using Hello theme.

Shortcode solves that, but why it happens to ACF custom fields feature:
![Screenshot_2021-02-16_11-29-48](https://user-images.githubusercontent.com/11068030/108044050-7489a280-704a-11eb-96bf-2959b3c1b710.png)

I think it worked perfectly few months ago.
