### ISSUE TITLE
Menu editor is not loading in elementor

### ISSUE THREAD

**Issue by nonny2019** [elementor/elementor#11691]
I got below issue when I tried to add/edit menu with elementor. I am using Cerato theme, elementor 2.9.12 and Clever Mega menu 1.0.8. Both have latest versions

editor.min.js:31 Uncaught ReferenceError: Elementor panel doesn't have page named 'page_settings'
    at i.setPage (editor.min.js:31)
    at Component.renderTab (editor.min.js:31)
    at Component.activateTab (editor.min.js:2)
    at Component.<anonymous> (editor.min.js:2)
    at Routes.run (common.min.js:2)
    at Routes.to (common.min.js:2)
    at API.route (common.min.js:2)
    at Editor.<anonymous> (cmm4e-elementor-editor.min.js:1)
    at p (load-scripts.php?c=0&load[chunk_0]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.4.2:16)
    at f (load-scripts.php?c=0&load[chunk_0]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[chunk_1]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.4.2:16)

**Comment by lior-sh** [comment]
Hi @nonny2019,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by nonny2019** [comment]
Hi,

As, I told you above that, I am using Cerato theme, which is elementor theme
1. When I try to create mega menu with elementor, loading image scrolls and console window shows as in my above message. Even I tried in different browsers. 
https://www.screencast.com/t/yvCMcmawR3CS

2. Here is system info				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.25-28
	PHP Version: 7.3.18
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: http://crownhospitalitysupplies.com.au
	Home URL: http://crownhospitalitysupplies.com.au
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Cerato Child
	Version: 2.0.8
	Author: ZooTemplate
	Child Theme: Yes
	Parent Theme Name: Cerato
	Parent Theme Version: 2.0.8
	Parent Theme Author: Zootemplate

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

== Active Plugins ==
	Clever Addons
		Version: 2.0.0
		Author: Zootemplate

	Clever Addons for Elementor
		Version: 2.0.6
		Author: CleverSoft

	Clever Addons Pro for Elementor
		Version: 1.2.2
		Author: CleverSoft

	Clever Mega Menu Pro for Elementor
		Version: 1.0.8
		Author: CleverSoft

	Clever Portfolio
		Version: 1.0.3
		Author: CleverAddon

	Clever Swatches
		Version: 2.2.0
		Author: cleversoft.co

	Clever WhatsApp Chat
		Version: 1.0.0
		Author: CleverSoft

	Clever WooCommerce Product Filter
		Version: 1.0.0
		Author: cleversoft

	Contact Form 7
		Version: 5.1.9
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.9.12
		Author: Elementor.com

	Facebook Messenger Live Chat for WordPress
		Version: 1.0.0
		Author: CleverAddon

	Google Analytics for WordPress by MonsterInsights
		Version: 7.10.4
		Author: MonsterInsights

	MC4WP: Mailchimp for WordPress
		Version: 4.7.8
		Author: ibericode

	Meta Box
		Version: 5.3.1
		Author: MetaBox.io

	Multi Currency for WooCommerce
		Version: 2.1.5.4
		Author: VillaTheme

	SG Optimizer
		Version: 5.5.6
		Author: SiteGround

	WooCommerce
		Version: 4.2.0
		Author: Automattic

	WPForms Lite
		Version: 1.6.0.2
		Author: WPForms

	Yoast SEO
		Version: 14.3
		Author: Team Yoast


== Elements Usage ==
	
	page : 1
		clever-product-deal : 1
		clever-product-with-banner-and-tabs : 3
		clever-slider : 1
	site_footer : 8
		clever-canvas-cart : 1
		clever-icon : 4
		clever-search : 1
		clever-site-nav-menu : 3
		divider : 4
		heading : 10
		icon : 6
		icon-list : 1
		text-editor : 3
		wp-widget-mc4wp_form_widget : 1
	site_header : 10
		clever-account : 1
		clever-canvas-cart : 2
		clever-compare : 1
		clever-language-switcher : 1
		clever-search : 1
		clever-site-logo : 2
		clever-site-nav-menu : 3
		clever-wishlist : 1
		heading : 4
		wp-widget-wmc_widget : 1
	wp-post : 0
		clever-product-with-banner-and-tabs : 3
		clever-slider : 1
		icon-list : 2
		text-editor : 2
		wp-widget-woocommerce_products : 1


== Log ==
	
JS: showing 1 of 1JS: 2020-06-19 05:10:16 [error X 1][http://crownhospitalitysupplies.com.au/wp-content/plugins/elementor/assets/js/editor.min.js:31:188045] Elementor panel doesn\'t have page named \'page_settings\'

**Comment by nonny2019** [comment]
any update??

**Comment by arielk** [comment]
We are sorry for the delay, but we are not aware of this plugin / theme, please contact the author of this plugin to resolve this issue.
