### ISSUE TITLE
Form Widget - limit DATE weekdays

### ISSUE THREAD

**Issue by studio-utd** [elementor/elementor#11706]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm looking for a way to exclude week days in date widget form.

**Describe the solution you'd like**
I like people not to be able to select some days in the date widget format (i.e: each saturday or sunday should not be selectable)

**Comment by shilo-ey** [comment]
Hi @studio-utd 


There are several issues raised in this topic:
#6372 , #7223

Thanks

**Comment by studio-utd** [comment]
Hi! I've found these issues but what I was looking for is to limit only weekdays (disable saturdays and sundays to be pickles up).

Regards

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>

________________________________
De : shilo-ey <notifications@github.com>
Envoyé : mardi 23 juin 2020 à 10:31
À : elementor/elementor
Cc : studio-utd; Mention
Objet : Re: [elementor/elementor] Form Widget - limit DATE weekdays (#11706)


Hi @studio-utd<https://github.com/studio-utd>

There are several issues raised in this topic:
#6372<https://github.com/elementor/elementor/issues/6372> , #7223<https://github.com/elementor/elementor/issues/7223>

Thanks
