### ISSUE TITLE
Custom Widget Defaults / Global Defaults

### ISSUE THREAD

**Issue by theamazingaustin** [elementor/elementor#11709]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
**First of all, Mad Respect to Elementor and all the Devs and support behind it. Thanks for all you do.**

I know you can now globally style buttons, fonts, and a few other things, but these barely scratch the surface. If you were working with CSS classes, you could change one value in one location and your entire site would be updated. I know this is a visual page builder, and I don't expect the freedom that comes with hand-coding something, but I just feel it's an oversite to not be able to adjust the defaults of all the widgets, or make more changes globally.

For example, in the widget-selection window, have a little gear or carat icon in the corner of each widget icon that would open a pop-up and allow you to set / create global defaults for that widget. All the same settings you have on-page when editing a widget, but when you change the default, it then updates all of that widget across the site. Anything that's not been set by the user in the global default (ex: the image for the image widget, a secton's background, which icon the icon widget displays) would obviously have to be chosen one-by-one on-page and updated as such, but that is how you would have to do it with HTML and CSS as well if it's not a post type or some sort of loop.

You could even have the ability to create multiple "styles" or "versions" of one widget. For example, create a large icon widget default, and a small icon widget default.

And if you want to make one widget that is different from all the rest? You could take a similar approach to how Elementor Handles fonts. Once you override a setting, it no longer is affected by global font changes. Likewise, if you override a setting that is globally set, it will stay as such unless you delete it or right-click on the widget and change it back to one of the defaults that you have created.

I know implementing something like this is easier said than done, but I feel like (besides adding the options in the elementor UI) it would mostly just take some tweaks to applying and updating CSS classes on the back-end of elementor when working with widgets.

Also, I know a lot of this can be handled with custom CSS in elementor, but I do not like having to create CSS that is fighting with Elementor's CSS. Elementor already creates so many classes and ID's on the page, I try to avoid overriding styling on anything but the standard HTML tags such as links, heading fonts, and lists, etc. It's a huge pain to find the right class sometimes, and I don't want to risk an update destroying a site because the CSS selector I was using was changed in elementor, or something like that.

The motivating reason behind this is consistency. Perhaps I'm not using Elementor correctly, but I just have a hard time keeping everything consistent, especially in sites that change.

For example, say you have 10 similar elements / widgets on the page. Let's just say it's an image widget. You decide you want to tweak the look. You change one of the widgets, then have to copy it, then click one-by-one on the other 9 and paste the style. You don't like it, do it again, and again. If you have the same widget on multiple pages, you've then got to crawl through the site to change every single one of them. And sometimes pasting style can override things you didn't want to override, then you have to go back and re-add them.

Or another example, when adding sections, inner sections, etc. Trying to keep padding / margins consistent, you have to manually tweak every section or inner-section on the entire site if you decide to, say, add more white space. Honestly, just being able to globally set padding and margin alone would make me a very happy man. 😎

It's quite possible that elementor devs are not going to implement something like this because it does complicate things to an extent, and maybe that's not the target audience. But at the same time I feel like this and similar "advanced" features would appeal greatly to the users who are moving from wordpress to webflow, or deciding on one or the other. And looking through the reddit, github, and facebook pages for elementor, it's clear that there is a sizeable group of elementor users who would thoroughly appreciate this and similar features. 🤷‍♂️

Again, a big thanks to the elementor crew!
-Austin

**Comment by DorShahar** [comment]
Hi 
Sorry for the delay with the answer, and thank you for your input.
Indeed, we know what you mean, and we are aiming for this. We calling it Presets (name TBD of course - despite the issue I merged to).

I will merge this to #965 since this relaying to the same problem.

Thanks again.
