### ISSUE TITLE
Blacklist domains in Elementor Contact form

### ISSUE THREAD

**Issue by rcholsk** [elementor/elementor#11701]
I need to restrict people from submitting a form that contains a free email domain (gmail, yahoo, etc..) in the email address field. 

I attach an answer founded in Github: 
![image](https://user-images.githubusercontent.com/33259724/85249739-992d6c00-b422-11ea-8096-90ead5a0ddb4.png)

The following code needs to go in your theme's (or child theme's) functions.php file. Careful, this can crash your site if you do it wrong. 

add_action( 'elementor_pro/forms/validation/email', function( $field, $record, $ajax_handler ) {
	// validate email format
	if ( ! is_email( $field['value'] ) ) {
		$ajax_handler->add_error( $field['id'], 'Invalid Email address, it must be in the format XX@XX.XX' );
		return;
	}
$black_list_domains = [
		'gmail.com',
		'domain.com',
	];
$email_domain = explode( '@', $field['value'] )[1];
if ( in_array( $email_domain, $black_list_domains ) ) {
		$ajax_handler->add_error( $field['id'], 'Invalid Email address, emails from the domain ' . $email_domain . ' are not allowed.' );
		return;
	}
}, 10, 3); 

I don't know how to implement it, some doubt: : How to assign this code to specific form, what file do i need to insert this code to functions.php? and where? Is the functions.php is in the root of public_html?

Thank you

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
