### ISSUE TITLE
I have Elementor Pro, but I still keep getting the "Go Pro" options on some features. Bug?

### ISSUE THREAD

**Issue by iscottjones** [elementor/elementor#11708]
![Screenshot 2020-06-22 at 8 22 34 PM](https://user-images.githubusercontent.com/60908337/85345795-5a171d80-b4eb-11ea-9dcb-2721d899355d.png)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate**.
* **Isolating the problem**.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by iscottjones** [comment]
You didn't even give it a chance to see if someone had a similar issue, so saying "without it we can't help" is a joke.
