### ISSUE TITLE
Elementor with LMS feature? A HOT need of the hour suggestion

### ISSUE THREAD

**Issue by Piya1993** [elementor/elementor#11713]
Hi, I have 1 quick suggestion for Elementor Pro Upcoming Feature.. which is LMS feature as Addon or Built-in ...
Like, these days with **COVID19** you know.. the demand for Online teaching is high .. and every professional is looking for something BEST, Reliable, and Cost-effective Solution for Online teaching/courses platform for their businesses...
So, Elementor Pro can take this BIG opportunity as a BIG advantage...
You can collaborate with some other plugins, OR add an extra **LMS (Learning Management System)** feature ...
If you need any sort of discussion regarding it. I am open to it. I can give you as many references, as you want ...
THANK YOU!!!
Have a Blessed Day!!

**Comment by shilo-ey** [comment]
Your wish might come true soon :)

Please follow our blog for further updates.

Thanks

**Comment by Piya1993** [comment]
Thank you so much...
I will LOVE to see future updates!
