### ISSUE TITLE
Post Info widget don't have Dynamic Content fields

### ISSUE THREAD

**Issue by vovkasolovev** [elementor/elementor#11726]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

There is absolutely no Dynamic Content in the Post Info widget.
For example, this is necessary for a fairly typical task when creating a design for an archive: output of the Category icon or image.
In Post Info widget you can output Terms with Icon or any Custom Field. But, unfortunately, the icon selection field does not have the ability to assign it dynamically, in order to select the Custom Field assigned as the image for the Category. In fact, the similar Icon list widget right now has more features than Post Info widget. Please add Dynamic content in the Post Info widget.

I assume that when the Archive loop item template designer editor appears, this feature will be much in demand for creating a skin.

**Comment by TomRaraAvis** [comment]
#12059 Goes hand in hand with this request!

**Comment by TomRaraAvis** [comment]
This is the best related post with more attention #12051

**Comment by arielk** [comment]
Merge to #4440

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hi @vovkasolovev,

there was already a solution for this when you submitted your request. You can use the Icon List widget with Dynamic Tags. This should be enough to achieve your goals.

As for assigning icons dynamically, this feature isn't supported yet and we don't have plans to implement it for the time being. You might be more successful if you use SVG images instead.

I hope this helps.

Kind regards
