### ISSUE TITLE
Query Sort Order in Archive Posts Widget

### ISSUE THREAD

**Issue by gmariani** [elementor/elementor#11722]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am unable to sort Archive Posts like you can in the Posts widget. I have read about the purpose of the Archive Posts and understand it's limited ability to modify the query. You need to use the display conditions, etc. That all makes sense.

**Describe the solution you'd like**
But what I want to add is just the ability to sort. It's silly to have the X most recent posts on the homepage from newest to oldest and link to the Archive page, only to have the Archive page be in a completely different order... 

**Describe alternatives you've considered**
I ended up installing Code Snippets in order to avoid creating a child theme for a single function to override the sort order ( as mentioned on this page related to custom post types https://github.com/elementor/elementor/issues/6336 ).

```
add_action( 'pre_get_posts', function ( $query ) {
	// Only modify the query we want
	if ( ! $query->is_main_query() || ! $query->is_archive() ) {
		return;
	}
	// set order by
	$query->set( 'orderby', 'post_date' );
	// set order
	$query->set( 'order', 'DESC' );
} );
```

**Additional context**
None

**Comment by anton-dealmeida** [comment]
Would be nice to have native sorting functionality for posts and custom posts in Elementor.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by gmariani** [comment]
"due to inactivity" - What activity are you expecting? I thought someone from Elementor would comment on it. I submitted a decent description of the issue. Just because Elementor didn't respond doesn't meant it's inactive.

**Comment by doublebondweb** [comment]
Why is this closed? Is there a solution already that I'm not aware?

It seems very obvious that the archive posts should also have the option to be sorted just like the posts widgets can. 

Using 3rd party plugins or custom code to write a custom query that sorts the archive posts by date, titles, menu order, or whatever, just doesn't make sense if we think about Elementor and all its capabilities. 

Looking forward for a positive reply.

Cheers!

**Comment by middlebusher** [comment]
Agreed, why is this closed? No solution - lots of comment activity. I'm still trying to solve this.

**Comment by Hawkeye1909** [comment]
@arielk I agree with the others. Please reopen and add a sorting option.

**Comment by saawood13** [comment]
still want this functionality!! my tags archive page are sorted in reverse alphabetical, who wants that?

**Comment by jomarieminney** [comment]
+1

**Comment by FreshLondon** [comment]
+1

**Comment by Jowan-Spooner** [comment]
+1

**Comment by ArnoldRobertTurdean** [comment]
+1

**Comment by ShabaniAmir** [comment]
+1
This is ridiculous. I already switched to Bricks for all future work and stopped buying Elementor licenses.
Keep upselling your crappy AI products instead of working on the core product though. I'm sure people love that and won't just use ChatGPT which does everything better for cheaper.

**Comment by Jamesbinda** [comment]
+1

**Comment by kalozpepi** [comment]
+1

**Comment by rameezwp** [comment]
Any update from Elementor on this?
