### ISSUE TITLE
✔️ 🐞 Bug Report: Border hover transition duration slider not available until 'NORMAL' state border is set to a type other than 'None'

### ISSUE THREAD

**Issue by manyfew** [elementor/elementor#11723]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The problem is that the border transition duration slider is not shown for Section and Column elements unless the 'Normal' border is set to a type other than 'None'.

This is problematic when you want a border on hover but none when not on hover. Or if you want a box shadow on hover only.

## Steps to reproduce

1. Add a section
2. Add a widget e.g. a Image
3. Edit Section > Style > Border > **Normal**, set type to 'None'
4. Edit Section > Style > Border > **Hover** (type not important but you can set it to 'Solid')

**Expected behaviour:** Transition duration slider is available
**Observed behaviour:** Transition duration slider is NOT available

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.43 (cPanel) OpenSSL/1.1.1g mod_bwlimited/1.4 Phusion_Passenger/5.3.7
	MySQL version: MySQL Community Server (GPL) v5.7.30
	PHP Version: 7.2.31
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: https://maxforming.com
	Home URL: https://maxforming.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.13
		Author: Elementor.com


== Elements Usage ==
	


== Log ==
	
Log: showing 1 of 12020-06-23 22:48:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '2.9.13',
)]
```
</details>

**Comment by nicholaszein** [comment]
Hello there @manyfew!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

Thank you so much for reporting this bug, and for being so patient! 🙏 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
