### ISSUE TITLE
step plugins

### ISSUE THREAD

**Issue by MangB0y** [elementor/elementor#11724]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MangB0y** [comment]
how can I install step or multiform in elementor

**Comment by arielk** [comment]
You can learn about it here: https://elementor.com/blog/introducing-multi-step-form/
