### ISSUE TITLE
"Edit with Elementor" isn't clickable after the first page load

### ISSUE THREAD

**Issue by Pikamander2** [elementor/elementor#11728]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When visiting a post, the first load will successfully show the Edit with Elementor button. If you refresh the page (or load it in another tab), the button stops appearing.

If you edit the post with Elementor and save, then it will appear one more time, but stops appearing after that.

This problem is closely related to issue #10745, but the two issues are a bit different. The old issue was fixed with pull request #10889, but this problem still persists even in the latest stable release.

I did some simple debugging and found that this line in `\includes\frontend.php` was failing:

`if ( is_singular() && isset($this->admin_bar_edit_documents[$queried_object_id]))`

The problem there seems to be that the

`1626 => Elementor\Core\DocumentTypes\Post::__set_state(array( 'main_id' => 1626, 'post' => WP_Post...`

value is missing from the admin_bar_edit_documents array after the first page load.

Any idea what's happening there?

## Steps to reproduce
1. Create a post with Elementor and publish it
2. View the page and note that the "Edit with Elementor" button appears at the top and is clickable.
3. Refresh the page and note that the button has disappeared (or at least isn't clickable).

## Isolating the problem

- [x] This bug happens with only the Elementor plugin active.
- [x] The bug is unrelated to Elementor Pro (it happens regardless of whether or not Elementor Pro is installed/activated).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug 100% of the time using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.0.33
	PHP Max Input Vars: 2000
	PHP Max Post Size: 3000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: (hidden)
	Home URL: (hidden)
	WP Multisite: No
	Max Upload Size: 3 GB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.4.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.11
		Author: Elementor.com


== Elements Usage ==
	
	wp-post : 2
		html : 1
		text-editor : 1
	wp-page : 1
		heading : 1
		text-editor : 2


== Log ==
	
Log: showing 17 of 172019-08-29 23:06:04 [info] elementor::elementor_updater Started 
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-29 23:06:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.8',
)]
2019-08-29 23:06:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.8',
)]
2020-05-28 08:23:26 [info] elementor::elementor_updater Started 
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-05-28 08:23:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.9.9',
)]
2020-05-28 08:23:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.9.9',
)]
2020-06-10 07:22:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.11',
)]			
```
</details>

**Comment by howdy0420** [comment]
I remember having an issue like that,  I think I just duplicated it and erased the original, showed up after that

**Comment by vaka2vaka** [comment]
+1 

This problem disappears for reasons unknown to me. Sometimes when changing the style of the plot. Sometimes when adding a block. Discussed here:
https://wordpress.org/support/topic/in-version-2-9-7-the-edit-button-in-elementor-disappeared-on-some-pages/

**Comment by wayheming** [comment]
Same error

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.8

Feel free to update

Thanks!

**Comment by sRavit** [comment]
> This issue has been resolved in Elementor v3.0.8
> 
> Feel free to update
> 
> Thanks!

I didn't have that issue before (v3.0.7), but i've updated to v3.0.8 and now i dont have "edit with elementor" link on the admin bar at all. that issue happened on all of my websites (wp multi-site). 

Any suggestions?

**Comment by Pikamander2** [comment]
@shilo-ey @KingYes @arielk  - Version 3.0.8. doesn't appear to have fixed the issue; in fact, it seems to have made it worse. The "Edit with Elementor" button now never appears on our site at all, even right after saving a page.

**Comment by Pikamander2** [comment]
@shilo-ey @KingYes @arielk - Actually, nevermind. The button is there and it works, although it got moved to the far right side for some reason.

Not that it particularly matters, but would it be possible to move it back next to the "Edit" button? That's where it's been for years, and it seems like the most logical place to put it.

@sRavit - Does the Edit with Elementor button appear on the far right side of your admin bar?

**Comment by shilo-ey** [comment]
@sRavit Can you please share your system info?

@Pikamander2 Can you share a screenshot and your system info?

Thanks

**Comment by Todderz** [comment]
Never had this problem until the latest update and now there is no Edit with Elementor button

**Comment by Pikamander2** [comment]
@Todderz - Does it appear to the right of the other admin bar items?

**Comment by Todderz** [comment]
No, it doesn't appear anywhere, for pages or posts.
System info attached

![image](https://user-images.githubusercontent.com/1296620/93317233-20616480-f805-11ea-8264-c749cada81a4.png)
[system-info-toseethe.world-16-09-2020.txt](https://github.com/elementor/elementor/files/5231118/system-info-toseethe.world-16-09-2020.txt)

**Comment by vaka2vaka** [comment]
> @ shilo-ey @KingYes @arielk - Вообще-то, да ладно . Кнопка есть, и она работает, хотя почему-то переместилась в крайнюю правую часть.


I also moved to the right

**Comment by eleasarchriso** [comment]
Same here - the button is completely missing. If I inspect the generated HTML code it does not seem to be included at all. 
Using latest (free) Elementor version.

**Comment by sRavit** [comment]
indeed, changing Autoptimize settings change fixed that.
