### ISSUE TITLE
has_shortcode not working

### ISSUE THREAD

**Issue by Zyles** [elementor/elementor#11741]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Wordpress 5.4.2
Elementor 2.9.13

## Description

Adding a shortcode with widget and trying to detect it inside a plugin using the Wordpress "has_shortcode" function does not seem to work.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

1. Add a shortcode using the widget
2. Create a new plugin with a functions.php and code:
```
function handle_shortcode() {
    return 'My shortcode';
}
add_shortcode('my_shortcode', 'handle_shortcode');

function enqueue_scripts() {
   global $post;
   if (has_shortcode($post->post_content, "my_shortcode")) {
      wp_enqueue_script('vue', 'https://cdn.jsdelivr.net/npm/vue@2.6.11', [], '2.6.11');
   }
}
```

The if statement will never be true as it seems "has_shortcode" can not find the shortcode.

**Comment by udidol** [comment]
Hi @Zyles,
`has_shortcode` should detect shortcodes in the content returned by `$post->post_content`, both from the Shortcode widget and from the Text Editor widget. I even re-tested it to make sure, and it detected it fine for me.

What do you put into the text field in the shortcode widget?

**Comment by Zyles** [comment]
I use [my_shortcode]

The shortcode works. It returns "My shortcode" in the HTML.

The problem is the wp_enqueue_script never fires.

I am also using it on a page. Will the `global $post; $post->post_content` work for page content?

**Comment by udidol** [comment]
What do you mean 'also' using it in a page? Where were you using it before?

Anyway, it works for pages as well, yes.

If you have xDebug, if I were you, I would try to debug this issue by assigning a variable with `$post->post_content`, adding a breakpoint and checking the value for your shortcode manually.

**Comment by Zyles** [comment]
I solved it. Called the wrong add_action

**Comment by rtorrespr** [comment]
Hi,

Can you post the correct add_actions?

Thanks a lot!

**Comment by smileBeda** [comment]
The ShortCode is NOT inside the `global $post` post body as you'd probably assume!

The ShortCode will be inside the _elementor template post body_, that is what you have to check against. Nothing to do with the action or hook used.
You can do something like this:
```
$elementor_template_id = 1111;
$has_shortcode = has_shortcode( get_the_content( null, false, $elementor_template_id ), 'your_shortcode' );
```
 
I wish Elementor had a function to check "is template used" for example. Maybe there is one, but I couldn't find.
