### ISSUE TITLE
Payment in Multistep form & Loan Calculator using logical form

### ISSUE THREAD

**Issue by aa-prashant** [elementor/elementor#11744]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Multistep forms are next big thing for elementary, but since website owner wants customers to be verified it is really necessary for any website to verify users using OTP . also there are so many websites which do provide registration to the customer and takes a small amount of money for the registration. multistep forms are very very powerful for registration website as it won't need the addition of woo-commerce into the website and making it bulky. just like woocommerce the click to pay feature can be integrated with the all the payment gateway plugins. It will be like ordering a single product with a multistep form where admin can verify customers with OTPand checkout using payment and then show a thank you page.

Also, I am building a real estate website and went through the internet on how to build A loan calculator. since the whole website is powered by elementor, I don't want to include any plugin and make the process more tedious. Since elementor forms are already powerful there can be a conditional field which can take values from other fields and calculate any expression. also since price calculator do not require that much of calculations , the results can also be different fields which shows the calculated values in real-time. just imagine you are sliding the principal amount in the slider and the emi amount changing in the result section.

**Describe the solution you'd like**
1. Multistep form with OTP verification and checkout page with payment gateway integration.
2. Forms with the option of toggling send button and conditional logic fields.

**Describe alternatives you've considered**
other form plugins, not cost-effective.

**Additional context**
N/A

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/2638 & https://github.com/elementor/elementor/issues/10386 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
