### ISSUE TITLE
🚀 Feature Request: Submit Rating option in the Star Ratings Widget (Duplicate of #10713)

### ISSUE THREAD

**Issue by darkpheonic** [elementor/elementor#11745]
Currently the star ratings widget only shows the ratings we have put inside the Elementor editor or through a dynamic meta value. Also the review widget will only show the data from the Elementor editor which is not frontend user submitable.

But I want to see a option to allow users to submit ratings on the front end. The ratings should display the average rating submitted by users. The data should be stored in the database. Also the rating should be limited to per IP or cookie based. This will help build dynamic and complex websites, not just to just build pages

I know there are plugins that does it but most of the times they break or don't work as intended with Elementor. I have tried almost all of the review plugins available in the WordPress repository for my custom post types. And as I have said most of them don't work well with Elementor and the ones that does it's just impossible to customize them. So they don't look good. Maybe because they are not designed for Elementor and custom post types. 

So I am saying that having this feature integrated with Elementor will make it lot easier to implement it and not break.

I am a pro user and it is really bugging me for not able design the website with this feature.

I hope the Elementor team will consider it in the upcoming release.

**Comment by ex-avenger** [comment]
+1 much needed feature. I am also waiting for it from long time.

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #10713

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards
