### ISSUE TITLE
Enter into textarea field moves to the next step

### ISSUE THREAD

**Issue by sbc640964** [elementor/elementor#11766]
In multi-step form
Enter in a textarea field moves to the next step instead of dropping a line

**Comment by lior-sh** [comment]
Hi @sbc640964,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info**.
* **Video**
* One issue per thread
Without it, we simply can't help.
Thanks.
