### ISSUE TITLE
Add The default Font

### ISSUE THREAD

**Issue by andyliuonline** [elementor/elementor#11765]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The default font for Chinese (Traditional Chinese, Simplified Chinese)

**Describe the solution you'd like**

Now, the default font has "Noto Sans", "Noto Sans JP" (for Japan), "Noto Sans KR" (for Korea)
Can add the "Noto Sans CJ TC" or ("Noto Sans TC") and  "Noto Sans CJ SC" or ("Noto Sans SC")?

https://fonts.google.com/specimen/Noto+Sans+TC?query=noto#glyphs

**Describe alternatives you've considered**

![截圖 2020-06-30 23 05 43](https://user-images.githubusercontent.com/34826012/86143761-6c1a4100-bb27-11ea-8a2e-324e8e17964c.png)
**Additional context**

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!

**Comment by silaslin** [comment]
Many Thanks for your help.
