### ISSUE TITLE
Feature Request: Dynamic tag field for Webhook URL in form widget (And other places)

### ISSUE THREAD

**Issue by SDenny** [elementor/elementor#11774]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am trying to set up a post template where the posts have been configured to have a few new custom meta pieces, and I am using it to set up a very replicable form-submission system. I currently have a custom post meta tag that I can add a webhook address to, e.g. a Zapier webhook, but the form widget within Elementor does not support dynamic tags for the webhook URL field in the forms widget.

While this is a very specific use, there are many places that could include the dynamic tag capability for the sake of allowing more customization and increasing the number of possibilities within Elementor. These could include any URLs, Text Fields, Color Selectors, and probably a few others throughout the whole interface (And you guys have done a wonderful job so far, I do see the tags all over the place and have been using them extensively.)

**Describe the solution you'd like**
I would like to be able to assign a dynamic tag to the Webhook URL field.

**Describe alternatives you've considered**
I have considered and am exploring using third-party form plugins to satisfy this need, but it would be a nice feature to be able to include dynamic data in many more places, including the webhook address fields.

**Additional context**
Missing here:
<img width="303" alt="Screen Shot 2020-07-01 at 8 56 26 PM" src="https://user-images.githubusercontent.com/3668475/86311481-beb63480-bbdd-11ea-894d-173fb2710343.png">

But is available here:
<img width="292" alt="Screen Shot 2020-07-01 at 9 00 12 PM" src="https://user-images.githubusercontent.com/3668475/86311611-ffae4900-bbdd-11ea-8ed9-f2c6fa0312b2.png">

**Comment by SDenny** [comment]
Upon further inspection through issues, it does look like using shortcodes from the form widget's hidden fields used to work prior to the stepped forms, as shown here: https://github.com/elementor/elementor/issues/4268#issuecomment-616590468 and while that would absolutely work as soon as it is functioning again, that doesn't totally solve the problem or complete the feature request as it would be more intuitive to be able to select by dynamic tags.

**Comment by steveindzine** [comment]
+1

**Comment by maurocarreraok** [comment]
+1 dynamic webhooks will work for me as well.

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
