### ISSUE TITLE
Missing functionality TemplateLibrary\Manager::unregister_source()

### ISSUE THREAD

**Issue by emmelemme** [elementor/elementor#11777]
Hello, I've been trying to register/unregister custom template sources, but every effort has failed since the unregister_source method isn't actually doing what it's said in the docs.

Method explained at [https://code.elementor.com/methods/elementor-templatelibrary-manager-unregister_source/](https://code.elementor.com/methods/elementor-templatelibrary-manager-unregister_source/):
`public function unregister_source( $id ) {
	if ( ! isset( $this->_registered_sources[ $id ] ) ) {
		return false;
	}
	unset( $this->_registered_sources[ $id ] );

	return true;
}`

Actual code in the [release](https://github.com/elementor/elementor/blob/master/includes/template-library/manager.php#L158):
`public function unregister_source( $id ) {
	return true;
}`

Is there any reason for the difference?
Thanks

**Comment by emmelemme** [comment]
Sorry, I've seen it's been deprecated in 2.7.0, could somebody point me at any alternative to manage the library contents?

**Comment by udidol** [comment]
Hi @emmelemme,
Unfortunately, there currently are no alternatives for programmatically managing the library contents.
