### ISSUE TITLE
set_settings not OK for every attributes

### ISSUE THREAD

**Issue by redpik** [elementor/elementor#11784]
Hi,
`set_settings` works only in some cases.

Here is a simple example :

```
add_action( 'elementor/frontend/widget/before_render', function ( \Elementor\Element_Base $widget ) {
    $settings = $widget->get_settings();

    if ($widget->get_name()=='theme-page-title') {
        // OK
        $widget->set_settings('_css_classes', 'my-custom-class');
        // not OK
        $widget->set_settings('align', 'center');
    }
});
```

Any explanation ?

**Comment by udidol** [comment]
Hi @redpik ,
First of all, I see you assign a variable `$settings` and never use it, so you could just delete it.
Secondly, are you sure the widget has a control named "align"?

**Comment by redpik** [comment]
Hi @udidol , thanx for your answer.
Yes there's a "align" control (it's for text alignment).

**Comment by udidol** [comment]
Hi @redpik,
If your control generates CSS (as opposed to HTML markup, like `_css_classes`), the `before_render` hook runs after the CSS has already been generated, so it would not take effect.

See https://github.com/elementor/elementor/issues/6101#issuecomment-439150316

You will have to find another way to adjust your CSS that is not through this hook.

Good luck!

**Comment by redpik** [comment]
Thank you @udidol
