### ISSUE TITLE
Color Picker on "Wordpress Widget" not working. 

### ISSUE THREAD

**Issue by borayeris** [elementor/elementor#11788]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I created a widget which works fine on Wordpress Sidebar BUT when I drag and drop at Elementor pro theme section and click on the widget I see the error on browser console "TypeError: $(...).wpColorPicker is not a function"

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by udidol** [comment]
Hi @borayeris,
Without steps to reproduce and/or access to the widget you created, there is no way we can help you.
