### ISSUE TITLE
Branch: release/3.0.0 get_theme_mod( 'custom_logo' ) will return false if the theme not support custom_logo

### ISSUE THREAD

**Issue by gvgvgvijayan** [elementor/elementor#11819]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [] The issue still exists against the latest stable version of Elementor.

## Description

Trying to access array offset on value of type bool in  wp-content/plugins/elementor/core/kits/documents/tabs/site-identity.php on line 60

While exploring prerelease of version 3 found a bug, a notice error.

The theme `Twenty Twenty 1.4` by default return false for the function call `get_theme_mod( 'custom_logo' )`  but without type checking the return value which is assigned to the variable `$custom_logo_id` in the following line
https://github.com/elementor/elementor/blob/release/3.0.0/core/kits/documents/tabs/site-identity.php#L23

That variable is accessed on the following line 
https://github.com/elementor/elementor/blob/release/3.0.0/core/kits/documents/tabs/site-identity.php#L60

which throws the following error.
[stack trace](https://pastebin.com/UaCbEFwV)

## Steps to reproduce

1. Install Wordpress 5.4.2
2. Install & activate Elementor from the branch `release/3.0.0.0`
3. Create a page and click Edit with elementor button

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

[Pastebin](https://pastebin.com/4iHznLtV)

</details>

**Comment by rodolphebertozzo** [comment]
How did you manage to install the 3.0 branch?

**Comment by gvgvgvijayan** [comment]
Pulled from git
`git checkout -b release/3.0.0`
then
`npm install && grunt`

**Comment by rodolphebertozzo** [comment]
Ah, do we have to go through Git?
Do you have the file directly compatible with wordpress?

**Comment by gvgvgvijayan** [comment]
Yes, I built it through git.
> Do you have the file directly compatible with wordpress?
Which file you're expecting

**Comment by gvgvgvijayan** [comment]
For a temporary solution, I added a dummy custom logo but this bug will raise if I remove the custom logo.
To resolve this issue you can determine if the site using a custom logo or not then include `add_control` method.

similar to the following logic -> https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentynineteen/template-parts/header/site-branding.php#L12

**Comment by wayheming** [comment]
Same error +

**Comment by arielk** [comment]
This branch is under development, please re-fetch and let me know if the error still there
