### ISSUE TITLE
After upgrading to PHP 7.4, elemntor started giving error

### ISSUE THREAD

**Issue by aldon-ltd** [elementor/elementor#11825]
url: www.aldon.ltd/ 
Cloud Service: GCP 
Server: Openlitespeed Wordpress 
Linux: Ubuntu 20.04 LTS
PHP: 7.4.6

Error:
Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1449

Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1451

Code Causing Error
`/** * End controls section. * * Used to close an existing open controls section. When you use this method * it stops adding new controls to this section. * * This method should be used inside _register_controls(). * * @since 1.4.0 * @access public */ Public function end_controls_section() { $stack_name = $this->get_name();
$current_section = $this->current_section;
            $section_id = $current_section['section'];
            $args = [
                    'tab' => $current_section['tab'],
            ];
`
Error Log at /usr/local/lsws/logs/error.log

[PHP Notice:] wp_deregister_script was called incorrectorrectly. Do not deregister the jquery-core script in the administration area. To target the front-end theme, use the wp_enqueue_scrip> 
[PHP Notice]: /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1449 
[PHP Notice]: /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1451

**Comment by shilo-ey** [comment]
@aldon-ltd 
Can you please make sure this issue persists when no other plugin is activated?

The best way will be to check this with a basic WP theme and only Elementor activated.

We can't reproduce this issue currently.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
