### ISSUE TITLE
Swiper arrows goes over header on Safari

### ISSUE THREAD

**Issue by bluantinoo** [elementor/elementor#11823]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

On Safari arrows of slider goes over the header.
the issue seems related to the following css, in frontend.min.css:

```
.elementor-swiper-button {
    -webkit-transform: translate3d(0,-50%,1px);
                  transform: translate3d(0,-50%,1px);
}

```
the following edit fixes the issue:

```
.elementor-swiper-button {
    -webkit-transform: translate3d(0,-50%,0px);
                  transform: translate3d(0,-50%,0px);
}
```

## Steps to reproduce

1) Using just Elementor and Hello Elementor theme
2) make ad header with theme builder
3) insert a slider/carousel in the page showing arrows
4) Browe with safari and scroll the page: slider arrows goes over the header, very annoying on mobile devices

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by austenosborne** [comment]
I get this too.  Did you resolve it in the end?  Thanks

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
