### ISSUE TITLE
Unable to close navigator

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#11836]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The navigator doesn't close anymore after opening the second time.

The console throws an error `Uncaught Error: cannot call methods on resizable prior to initialization; attempted to call method 'destroy'`

![image](https://user-images.githubusercontent.com/18551588/87217272-fbfc8e00-c364-11ea-930e-b81c913d1211.png)

## Steps to reproduce

1. Open the navigator, close it.
2. Open again, try to close it. It won't.
3. Check the browser console for the mentioned error.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.6

Feel free to update

Thanks!
