### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by pinnz** [elementor/elementor#11834]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
More options for CTA on a blog post and Pagination options for more streamline UX

**Describe the solution you'd like**
It would be nice to allow an actual button for the read more, to make it look like a button that allows secondary colour for gradient look. 
Also, allow an option for infinite load of pagination along with numbers and words. The infinite load is a great UX to allow the user to keep scrolling.

**Describe alternatives you've considered**
Used to use the Raven blog post widget and got these options. 

**Additional context**
Unfortunately, the Raven pagination doesn't work with the hello elementor theme. Which forced the change to the pro-post widget, looks good would just be great to have these options. And also the inner content option (not necessary).

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* **One request per thread**

Thanks.
