### ISSUE TITLE
⛔ ❓ How to set the z-index of the Menu Cart off-canvas container

### ISSUE THREAD

**Issue by webig** [elementor/elementor#11833]
Hi guys,
I am having trouble to find out the way to change Z-index of off canvas from Woocommerce Menu Cart widget. It sets it's Z-index to same as the menu it's in, but I need to make the off canvas part which pops after click on the cart icon, to go on top of everything, because on part of my layout is higher than navigation menu itself, and so it's covering the off canvas sidebar.
Can you help me with some css to set off canvas Z-index? 

Thanks for help.
:)

**Comment by nicholaszein** [comment]
Hello @webig,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

The z-index of the Menu Cart widget is pretty high at 9998. You should reduce the z-index of the other elements on the page to avoid layer conflicts.

If you really wish to change the z-index of the Menu Cart widget container, use the following custom CSS:

````css
.elementor-menu-cart__container {
    z-index: 99998;
}
````

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
