### ISSUE TITLE
Ability to partial disable Lightbox

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#11840]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hello.
Sometimes I need to partial disable Lightbox. The best example — WooCommerce product page. If Elementor lightbox enabled there are two lightboxes shows. Yes, I can disable WooCommerce lightbox with the hook but Elementor' lightbox doesn't see the WooCommerce gallery. So I can't to slide behind main product photo and product gallery photos.

There are also situations when other plugins like portfolio and advanced galleries has self advanced lightbox. I would like to disable Elementor lightbox on the page where I use other lightbox or/and make the ability to add CSS selector to disable lightbox.

**Describe the solution you'd like**
I suggest to make a toggle button into the page/template settings. If the page — so enable or disable lightbox for this page only. If the template — on/off lightbox for all posts that related to this template.

Also, there could be a field for custom CSS selectors to partial disable lightbox. For example, I have a landing page where I want to use lightbox on some widgets only.

**Describe alternatives you've considered**
Tried to disable WooCommerce lightbox for product page, but the Elementor lightbox doesn't "see" the product gallery.

Thanks for your work! 🙏

**Comment by black-eye** [comment]
+1
And please, don’t use your lightbox even when turned off for the PRO gallery:  #11193

**Comment by rami-elementor** [comment]
Closing this issue, as it's not relevant anymore.

You can disable Elementor lightbox from the "**Lightbox**" panel located in the "**Site Settings**" panel.

**Comment by carlos-blazquez-global** [comment]
> Closing this issue, as it's not relevant anymore.
> 
> You can disable Elementor lightbox from the "**Lightbox**" panel located in the "**Site Settings**" panel.

Hi, @rami-elementor

The point in this topic is "partial" disable, not a fulll disable that you propose as a solution. And @parfilov provides a very relevant use case: in WooCommerce single product page you can found a double lightbox, and only the WC lightbox provide gallery functionality. This is why we want to disable in this templates / widgets the Elementor lightbox.
