### ISSUE TITLE
purge old videos

### ISSUE THREAD

**Issue by feliciakw** [elementor/elementor#11841]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Of the 348 videos on the Elementor Website Builder for WordPress YouTube channel, 150 are 3-4 years old, 114 are 2 years old, and only 84 are one year or less.  Of those 84, a little more than half are specifically about the mechanics of designing pages.  I am new to Elementor - this is not helpful. There are many features I would like to understand better. For example, the three "Sections & Columns Part 1,2,3 Options for Sections and Columns" videos are from 2016. The narrator, while following a good script and speaking clearly, has a voice that is not optimal for anything more than a minute or two. I upgraded to Pro (I am a grad student and don't have a job, not lack of wanting one) so the cost was about the same as my electric bill. I do not regret the upgrade, it's necessary to achieve a modern, responsive website, but the documentation videos are very disappointing.  I appreciate the advice videos, but the majority are not applicable until I actually *have* a website. I can't transform anything, I am not a gym or law office, I can't speed up, build a community, make a YT channel, or create just about any of the motions effects on something I don't have yet - a basic site. 

**Describe the solution you'd like**
1. I would like to see more introductory/medium skill level videos that use the most recent (maybe 2?) versions of Elementor Pro. 
2. I would really like a video about how to create a portfolio. 
3. I would like for the 3-4 year videos to be reassessed and have the outdated ones purged so the content isn't so limited. 
4. I would like the playlists and great collections to also be reassessed so they provide the most up to date information, as well as several playlists that are in a "first you do this, then you create these as a baseline, followed by a few more details, that ends with a site that is complete enough to publish". From there the fancier/fun designs can be learned and integrated. The video series with the yellow intro slides are a good example, and are moderately helpful, but don't provide enough of the basics.  
5. I recognize that humans have the attention span of squirrels. Creating quality content that is engaging and efficient is REALLY difficult and that my comments may only apply to me, but I would hope that there are others who would appreciate the results. 
Kind Regards, -felicia stratton

*Randomly, since I upgraded to Ubuntu 20.04, I can only use your product on Firefox. Chrome doesn't load a damn thing. But I also have a System 76 computer so sometimes things are a bit odd. -f

**Describe alternatives you've considered**
I made the decision to commit to WP and Elementor Pro, so I would like the best solutions to come from your company. While there are ten hundred thousand other how-to videos, many are of poor instructional quality and are outdated. Or they are the opposite - way over my newbie head. -f

**Additional context**

**Comment by arielk** [comment]
We are improving our product more and more, along with new educational videos that we are working on all the time. I appreciate your sincerity and I assure you that we make great efforts to improve our documentation as the product progresses.

Thanks for your feedback!
