### ISSUE TITLE
Feature Request: Be able to dynamically change out images in the gallery of the section.

### ISSUE THREAD

**Issue by jmedia123** [elementor/elementor#11874]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [  X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to have a gallery of images loop within a section. However, it looks like the only way I can do that with dynamic content is to use a Image Carosel widget. The thing is that use the case would only be good if I didnt want the images to take up the whole screen and not have text and buttons, in front of, the images. 

**Describe the solution you'd like**
Like the Image Carosel widget, I want the Edit Section > Style > Background : Background Type : : Gallery to be able to pull images from a dynamic field (ACF Image Gallery) as for the client to easily change out the images themselves just like a Featured Image within a Post. 

![Screen Shot 2020-07-14 at 10 58 19 PM](https://user-images.githubusercontent.com/40833413/87498253-59befd80-c625-11ea-80a6-781569e44e2d.png)

**Describe alternatives you've considered**
I've considered placing the Image Carosel as you can use dynamic content like ACF Image Gallery but that's only for a widget that would fit into a column which I don't want. I want the images to play in the background as it makes sense for the text within the column. 

**Additional context**
![Screen Shot 2020-07-14 at 10 54 04 PM](https://user-images.githubusercontent.com/40833413/87497969-ba9a0600-c624-11ea-8e9f-946ddb2204d9.png)

**Comment by kino89** [comment]
+1 I think this is an important feature for sections and columns background!

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/11874 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by mateitudor** [comment]
Elementor. It's only been 84 years™

**Comment by phkoon** [comment]
4 years now ☠️
