### ISSUE TITLE
"Group_Control_Background" Label not changing.

### ISSUE THREAD

**Issue by mdnadimkhan** [elementor/elementor#11873]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am trying to change the label for "Group_Control_Background". But it's not changing. I am using Elementor 2.9.13

My code is 

$this->add_group_control(
		    Group_Control_Background::get_type(),
		    [
		        'name' => 'service_background',
		        'label' => __( 'Service Background', 'text-domain' ),
		        'types' => [ 'classic', 'gradient'],
		        'selector' => '{{WRAPPER}} .my-class',
		    ]
		);

but it's still showing the default label "Background Type".

**Comment by rami-elementor** [comment]
Hi @mdnadimkhan 

Please visit the new docs for more information:
https://developers.elementor.com/docs/controls/classes/group-control-background/

Use the latest Elementor version (3.5.5), if the problem is not resolved, contact me directly so I can help you with this issue.
