### ISSUE TITLE
 Leave a Comment section on blog posts disappear when ELementor Pro is enabled.

### ISSUE THREAD

**Issue by MandarinTangerine** [elementor/elementor#11882]
Hi,

Leave a Comment section on blog posts disappear when ELementor Pro is enabled.

https://synthaharrisinteriors.com/house-plants/  elementor pro is activated
http://synthaharrisinteriors.wptlemon.wptstaging.space/house-plants/ elementor pro is disabled
![image](https://user-images.githubusercontent.com/24966216/87614356-55d4cd80-c742-11ea-8122-c8861174f836.png)

**Comment by arielk** [comment]
You can build a different template for this page or just change the layout to "Elementor  - Full Width".

Thanks
