### ISSUE TITLE
Columns - Allow "auto" setting for width

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#11887]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### **Problem:**

In CSS, flexbox makes it possible to have automatic column width based on it's content.

Elementor uses flexbox, so why is this not possible in Elementor? Why are we stuck with percentages? 

We need to have an option to set column widths as "auto".

### **Solution**

Choosing "auto" width in each individual column is probably not practical, because you would have to set it in every column for it to work, which a lot of users might not understand.

Elegant solution would be this:

**Every section has "Structure" tab with different layouts available. You could just add "auto layout" and every column in that section would have width set as "auto". And that's it, done.**

It's easy to do with custom CSS, but this shouldn't require custom coding. 

- Auto columns are super important in web design.
- It's easy to implement.
- Elementor already uses flexbox, so let us use it as it was intended.

**Comment by black-eye** [comment]
+1, really handy.
And, when you start adding the options, please add the ability to turn off the "only-single-row" feature on desktop, to enable multiple rows in one section (#2218).

**Comment by arielk** [comment]
As @black-eye wrote above, I merged this issue with another issue https://github.com/elementor/elementor/issues/2218 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

We recommend using the Flexbox Container with the option to set the width, which allows you to select the custom unit and add your own CSS `keywords` or `functions()`.

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
