### ISSUE TITLE
Add "Hide when printing" to "Responsive" settings

### ISSUE THREAD

**Issue by jensolafkoch** [elementor/elementor#11886]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
(1) Often there are page elements that should not be printed, like headers, footers, navs and so on. Doing that by hand (CSS) either as Custom CSS on the widget or in style.css is cumbersome.
(2) I recently hid widgets for all three responsive categories to keep them for a while. I found out that they still get printed. 

**Describe the solution you'd like**
It woud be easy to add a "Hide when printing" option to the "Responsive" settings. That would also help people think in oruinting styles more which is something most designers tend to always forget. (That is, in a way, also a matter of ecology: Only print relevant information to save paper/toner.)

**Describe alternatives you've considered**
None besides still doing it all manually. But if I were to do all things manually, I wouldn't use Elementor. :-)

**Additional context**
None.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/4246 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
