### ISSUE TITLE
Elementor PRO, php error

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#11903]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Getting these error messages with Elementor 2.10.3 .

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class ‘ElementorPro\Modules\AssetsManager\AssetTypes\Fonts\Custom_Fonts’ does not have a method ‘posts_fields’ in \wp-includes\class-wp-hook.php on line 289

Warning: Cannot modify header information – headers already sent by (output started at ../wp-includes/class-wp-hook.php:289) in ../wp-includes/functions.php on line 6221

Warning: Cannot modify header information – headers already sent by (output started at ../wp-includes/class-wp-hook.php:289) in ../wp-admin/includes/misc.php on line 1282

Warning: Cannot modify header information – headers already sent by (output started at ../wp-includes/class-wp-hook.php:289) in ../wp-admin/admin-header.php on line 9
```

By looking at the code there seems to be a `add_filter( 'posts_fields', [ $this, 'posts_fields' ] );` and `remove_filter( 'posts_fields', [ $this, 'posts_fields' ] );` but the `posts_fields` method doesn't exist, as well in its parent classes.

Thanks!

**Comment by hugomiggels** [comment]
@hogash Did you ever manage to fix this? I've got the same issue

**Comment by hogash** [comment]
> @hogash Did you ever manage to fix this? I've got the same issue

As a temporary solution, i just commented those 2 lines (310 and 315) from plugins/elementor-pro/modules/assets-manager/asset-types/fonts/custom-fonts.php . On the next EPRO update they'll get overwritten, but perhaps until the next version this will get fixed.

**Comment by arielk** [comment]
Thanks for reporting,

This report is missing key information: 

* **Prerequisites**.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Without it we simply can't help.

Thanks

**Comment by hogash** [comment]
Wow, after over a month ago i pointed all the actual needed details and even specified the fix, you paste some message just to close the issue. Good luck!

**Comment by arielk** [comment]
> Wow, after over a month ago i pointed all the actual needed details and even specified the fix, you paste some message just to close the issue. Good luck!

We just need more information on the issue so we can help, feel free to reopen the issue and we'll be happy to help you further.

**Comment by hogash** [comment]
Ariel, i personally don't need any help, i just reported a bug in EPRO, that's it. 

As i mentioned before, try opening elementor-pro/modules/assets-manager/asset-types/fonts/custom-fonts.php and on lines 310 and 315 there's 2 filter calls for `posts_fields` method which is missing in this class eg: https://d.pr/i/KOSuOr . It's more than enough to see the bug, but your call.

Anyways, with all due respect, i know it was a hard month so congrats on the entire infrastructure upgrades.

**Comment by JensSwaenepoel** [comment]
Hogash is absolutely right... This issue does still exist 6 months later. Yesterday i encountered the issue myself. You call for a method which is exists nowhere else in the code .... This can create some issues, for my site it was big enough of an issue to break the entire webpage.  

I just commented out the lines 310 / 315  for now and the issue is fixed.

**Comment by antoinelubach** [comment]
+1

**Comment by ijcarson1** [comment]
+1 this is still happening for me! 

Was throwing an error 500 with 0 context, thankfully came across this post!

**Comment by zdeem** [comment]
+1

**Comment by MelRoute66** [comment]
+1

**Comment by Dolphi2** [comment]
+1

**Comment by Simonsbs** [comment]
+1
