### ISSUE TITLE
SUGGESTION: Clicking on Button/Link/Icon opens content

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#11918]
Hello people,

I would like to leave a suggestion for Elementor.

On some sites they show a shared icon (https://prnt.sc/tiyjpf), and clicking on it opens social buttons (https://prnt.sc/tiyjvn).

Elementor could offer that too. It would not need to be only with social buttons, but for any content that appears in the window when clicking on the Button/Link/Icon.

Here's the tip.

**Comment by arielk** [comment]
I do not see that we are going to implement these requests in the near future.
You can use our popup builder for this result: https://elementor.com/features/popup-builder/
