### ISSUE TITLE
Integration with Sendinblue

### ISSUE THREAD

**Issue by dharminderbiharie** [elementor/elementor#11932]
**What problem is your feature request going to solve? 
The request is to get the same integration as Mailchimp to get Sendinblue working with Elementor. 

**Describe the solution you'd like**
The landing pages, forms, CTA pages, Pop-Ups combined with Sendinblue

**Describe alternatives you've considered**
There is a WP fusion plugin, but it makes to sense. It has his limitations and pricing and paying is not an option...another paid plugin to do something that can actually work as a default feature. 

**Additional context**
Check the Mailchimp integration, love to see the same functions.

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/6527
