### ISSUE TITLE
elementor VS safari - not loading website

### ISSUE THREAD

**Issue by Teamdigital** [elementor/elementor#11930]
Website is loading from ALL devices, PC, macbook 2015 and older, iphone 6 and older, all android devices.

The problem starts when using iMac or macbook or iphone 8 or newer - 2016 to 2020.

WordPress is not giving any error, but the website does not load.  After waiting 5min... with a bit of luck... you'll see 15% of the website. then it says its fully loaded.

I found out the plugin causing this issue is Elementor Header, Footer & Blocks addon.  Disabling this plugin makes the website load like normal... only with some missing header, footer and blocks of course.

**Comment by arielk** [comment]
Seems like a problem with the plugin you are using, contact the plugin author with the problem.

Thanks

**Comment by Teamdigital** [comment]
Just want to say that I deleted the complete part and rebuild it exactly the same from scratch. Problem solved. Can’t believe I lost 8h here...

Thanks anyway!

**Comment by feoklia** [comment]
> Сразу хочу сказать, что я удалил полную часть и пересобрал ее точно так же с нуля. Задача решена. Не могу поверить, что я потерял здесь 8 часов...
Расскажи - что нужно сделать? Я не понимаю - уже всё перепробовала, удаляла сто раз меню и в контейнерах делала и в секциях, и ни как. Помоги плиз

**Comment by feoklia** [comment]
Tell me what needs to be done? I don’t understand - I’ve already tried everything, deleted the menu a hundred times and did it in containers in sections, and nothing. Help
