### ISSUE TITLE
Popup width uses vw, but other elements dont - Inherenet Problem! (BUG/Missing Feature)

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#11948]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a popup on the side of entire site pages.
I cannot align elements properly because the popup width is 15vw for example
and elements alignment will be 15%

Internal measure must support vw as well

## Steps to reproduce

1. Generate popup with certain width on right or left of the page
2. Use single page template  (or whatever) that will not be covered by the popup

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
Its missing feature that is a design bug
</details>

**Comment by rami-elementor** [comment]
@Mulli 

Closing, not relevant any more. All the popup controls include `vh` and `vw` units.
