### ISSUE TITLE
Post Carousel/Slider

### ISSUE THREAD

**Issue by Mululu** [elementor/elementor#11949]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

No additional plug-ins are required which are not implemented correctly anywa

**Describe the solution you'd like**

Add a Carousel / Slider option in the Post Widget or create an extra Post Carousel / Slider widget.

**Describe alternatives you've considered**

No alternatives

**Additional context**

Example Desktop

![image](https://user-images.githubusercontent.com/5918495/88421180-63482280-cde8-11ea-9573-5119cda7d178.png)

Example Tablet

![image](https://user-images.githubusercontent.com/5918495/88421240-7f4bc400-cde8-11ea-826c-b4bd0672b3a8.png)

Example Mobil

![image](https://user-images.githubusercontent.com/5918495/88421292-9985a200-cde8-11ea-8983-77203caa4aa1.png)

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/219 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
