### ISSUE TITLE
Alternative Mobile Nav Menu Icons for Toggle Button.

### ISSUE THREAD

**Issue by WNTLtd** [elementor/elementor#11950]
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Would it be possible to add alternative icons for use in the Nav Menus toggle button?
Instead of just 'None' and 'HamBurger'?

**Describe the solution you'd like**
Maybe add the use of FontAwesome - as I use Nav menus for a search bar too - and it'd be great to be able to change it to a magnifying glass...

**Describe alternatives you've considered**
I've tried putting responsive text next to it - but it's not as good.

**Additional context**
n/a

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/11361 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
