### ISSUE TITLE
Extend section to left or right

### ISSUE THREAD

**Issue by petranca** [elementor/elementor#11961]
It would be helpful if the content width of the section could also be defined so that it can be extended to the left or right. 

If the width is at 1500px and you expand to the left, the columns within the section will be set to the left edge and expanded to the right to a maximum of >1500px. To right vita versa.

So you could e.g. put an image in the first column up to the edge. This is now only possible in a complicated way.

**Comment by arielk** [comment]
Thank you for your feedback! 

Unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thanks again.
