### ISSUE TITLE
Give us more control over Columns Gap (aka gutter width) between columns

### ISSUE THREAD

**Issue by lastnoob** [elementor/elementor#11978]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As a designer the most frustrating part of the Elementor workflow is the Columns Gap (gutter width). On every single website. Whitespace is essential and often "Wider" is not enough for me. What's more, I'd love to have full control over gutter width. 

**Describe the solution you'd like**
Include a "Custom" option in the "Columns Gap" control for the "Section" widget, where we can specify the gutter width in px, em, or %.

**Describe alternatives you've considered**
Adding padding/margins to the columns, but they are not an ideal solution. I use custom CSS all the time.

**Additional context**
Here's the widget control I'm talking about:
![image](https://user-images.githubusercontent.com/1821091/88776149-8161aa00-d17d-11ea-8b6c-143f0cee5657.png)
![image](https://user-images.githubusercontent.com/1821091/88776329-b79f2980-d17d-11ea-8e63-710372161d1c.png)

**Comment by black-eye** [comment]
+1

**Comment by MichaelDarko** [comment]
Yes! Predefined non-customizable values should never be the way to go.

I don't like to have any default column gap, so I have to change every single section to "No gap". Very annoying workflow.

In the backend styling setting, there should be an option to do this:

- **Set the default value of the column gap** (very needed basic stuff)

- **Set the value of multiple options** (would be a nice bonus)

**Comment by black-eye** [comment]
Not to mention to have an option to get rid of the "outer" gap of the row itself - but it's a different story, which goes back to 2016 (Issue #452).

IMHO E 3.0 with all its changes concerning the DOM structure is the ideal opportunity to get this stuff finally fixed. Unfortunatelly I feel this opportunity will be missed.

**Comment by seriusokhatsky** [comment]
+1

**Comment by fabianenzensperger** [comment]
+1

**Comment by black-eye** [comment]
Looking at the commit mentioned above - nice direction, but:
1. Still not responsive
2. It doesn't solve the "outer gap" ssue (#452)

**Comment by MichaelDarko** [comment]
Ok, so the functionality to add custom column gap will be added. Thats good, but what about default column gap?

I really hope this will come with it. If antyhing, thats much more important. I don't want any default gap, so working with some predefined default value is a major pain, because I need to change every single section to "no gap".

Adding default column gap in global setting should be a priority in this regard.

- We can set default widget spacing
- We also need to set default column gap

It's silly when a design tool is defaulting to some predefined values. But if you have to do it, at least let us change the defaults.

**Comment by fabianenzensperger** [comment]
> Is this issue also related to the default columng gap setting? And does the commint also solve that?
> 
> If not, what about the default column gap? This was requested plenty of times in the 3.0 beta feedback.
> 
> I couldn't find any open feature request, so I opened one: #12763
> 
> If this issue also includes the default column gap, than please merge it.
> 
> If this commint only adresses the custom column gap, please reconsider also adding the default column gap setting in 3.1. That's much more important and basic.
> 
> Working with Elementor every day and having to constantly fight the 10px default column gap by setting every single section to "no gap" is driving me nuts. :-)

It looks like this will all come with 3.1, or am I getting this wrong?

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #6628, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by black-eye** [comment]
@DorShahar 
> 
> Merged issue
> 
> I merged this issue with #6628, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> Thanks for your feedback!

Quite confusing - why to close the issue with assigned milestone in favour of another one?

**Comment by DorShahar** [comment]
@black-eye my bad.

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
