### ISSUE TITLE
Reveal section in elementor page after certain time

### ISSUE THREAD

**Issue by presvijetla** [elementor/elementor#11989]
I have a landing page with video sales letter and I want to show the section below the video that contains the offer 5 minutes after visitor opens the page. 
- I tried revealing section by implementing fade in animation with animation delay on advanced settings tab, but it leaves huge empty space of the section visible and just hides all the elements inside. 
- I tried doing this with implementing Dynamic Content plugin, but they only have timers with predefined dates, days in the week or certain hours in the day.
As far as I searched for, I couldn't find plugin/solution that will reveal section after certain time. I am thankful for any suggestion.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/4246 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
