### ISSUE TITLE
WEBP Images doesn't support in Gallery

### ISSUE THREAD

**Issue by ex-avenger** [elementor/elementor#12009]
Elementor Pro :

In Gallery, WEBP images show up for Grid option. For Justified and Masonry it doesn't work.  Shows blank space where there is Gallery. 

Images only show up when I select Grid as option.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
