### ISSUE TITLE
embeding bitchute.com video in website

### ISSUE THREAD

**Issue by BajanEagle** [elementor/elementor#12004]
Please add the ability to add videos from bitchute.com's video platform into Elementor web builder.

**Comment by arielk** [comment]
Please follow these instructions: https://support.bitchute.com/content/how-to-embed-a-video-on-your-site 

Note, bitchute.com does not seem to be compatible with the oEmbed method, you can [read more here](https://wordpress.org/support/topic/support-for-bitchute-com-videos/#post-10615349), so it will be complicated to do so.

Anyway I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
