### ISSUE TITLE
Add a template widget.

### ISSUE THREAD

**Issue by Pantass** [elementor/elementor#12011]
Elementor free:
It takes a long time to create a pixel perfect page according to a psd template. Before we start creating a page, it would be good to be able to set up a widget and load a template and create a page over it. After creating the page, we can delete the widget.

**Comment by arielk** [comment]
If I understand you correctly, this feature is already has in Elementor Pro, you can learn more about it here: https://docs.elementor.com/article/425-template-widget

Thanks
