### ISSUE TITLE
Add Posts Caroussel

### ISSUE THREAD

**Issue by moisesrox** [elementor/elementor#12017]
Please add posts caroussel.

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/219

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
