### ISSUE TITLE
Add visual bootstrap grid

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#12012]
Hello please add visual bootstrap and baseline grid for better transfer project from photoshop or any program in to a elementor.

Best reference is
BOOTSTRAP: Designer powerup for elementor
BASELINE GRID: Ooohboi steroid for elementor (and have more feature dor elementor)

for simple site it is enough that there is, however, to create complex sites you need a grid, I was personally convinced by making my site how very good grids help in the speed of work and accurate transfer of the project. I and many who have already bought a full license would like to get more ease of use from what they already have, and not buy more plugins just for the sake of one function. The grid is important, it will take you to another level of design, I can give you an example of how and why you need a grid.

**Comment by arielk** [comment]
I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
