### ISSUE TITLE
Blog Subcategories

### ISSUE THREAD

**Issue by Dipixelweb** [elementor/elementor#12026]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need the subcategories of the category of the current post to be shown (both in the category pages and in the posts)

**Describe the solution you'd like**
A widget that allows displaying post subcategories

**Describe alternatives you've considered**
Blog categories to filter Current Query

**Additional context**
Subcategories with dropdowns

**Comment by arielk** [comment]
You can use the official WordPress categories widget or using the Sitemap widget.

Thanks for your feedback!
