### ISSUE TITLE
Please remove default hard coded values from widgets as they will overwrite theme styling

### ISSUE THREAD

**Issue by brittaweller** [elementor/elementor#12024]
Hello!

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Several times now I have my theme styling been overwritten by elementor. 
I load elementor css first, than my theme css but because some widgets have hard coded values and not empty default values they will save as posts css which is being loaded AFTER my theme css and overwrites the styling.

I would expect if one just adds a widget without any styling that the styling is either been handled by elementor css or the theme css. Please stop prioritizing the default settings.

## Steps to reproduce

An example is the form widget. I had given the input field some background color but because the default value of some fields are not empty but filled with #ffffff the background will be white. I only see my theme styling once I have deleted all the values elementor put in there on load.

I don't want to give my theme styling an !important as I still want the user to be able to overwrite the theme settings if wanted. With elementors random practice of setting values on load instead leaving them empty and use the default it is not possible to combine these things.

I would be happy if you would consider removing such hard coded defaults.

Kind regards
B.

**Comment by arielk** [comment]
Hi, you can change the most HTML elements like forms with [Elementor > Theme Style settings](https://elementor.com/help/theme-style-global-settings/)

Thanks

**Comment by brittaweller** [comment]
@arielk How is this a solution to the problem?!
To not solve issues is one thing. But to close them without any solution - this support is really just getting worse.

**Comment by arielk** [comment]
@brittaweller You can edit the form style via Them Style settings for all form instances

**Comment by arielk** [comment]
@brittaweller We try to avoid this as much as possible, if you have specific places to give an example it will help me understand the problem better
