### ISSUE TITLE
Hide/show elements to public/customers based on WordPress role

### ISSUE THREAD

**Issue by splendidjacob** [elementor/elementor#12043]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Provide a more custom user experience, ie dynamic, based on role within WordPress for better marketing/targeting/funnels. Could also be a simple quasi-membership site feature of Elementor.

**Describe the solution you'd like**
Ability to hide/show elements based on user role (similar to some Customize widgets) within Elementor page editor. 

**Describe alternatives you've considered**
Ultimate Member plugin (shortcodes do not work from within text elements of Elementor)

**Additional context**
Could be marketed as a true dynamic webpage, so the public sees one type of header and copy, members see another header and copy, and so on.

**Comment by shilo-ey** [comment]
I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by splendidjacob** [comment]
> I merged this issue with #1314, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!

Hi @shilo-ey . I don't beleive this is the same issue. I found that one during my search, but it appears that one applies only to editors, owners, and designers on what they can do on the back end. What I requested was the ability for a designer/creator to choose which public users (that is, which site member role they need, like Customer, Subscriber, or custom) to be able to SEE an element when visiting the site. Likewise, hide an element from them if they're not already a customer or whatever role.

If I'm not understanding, let me know.

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.18.0, and improved with Elementor Pro 3.19.0! 🥳 

You can now use Display Conditions for widgets based on User Role and a lot of other conditions (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
