### ISSUE TITLE
Add the ability to create custom pages for woocommerce (Cart, Checkout, Thank you pages)

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#12049]
Today, there are quite a few developers with such solutions, but they cost more than licenses for Elementor Pro, some slow down the site and some contain a suspicious code or technical support responds for a very long time and it is difficult to return money. Create a full-fledged designer for an online store so that you can edit each page. And here's another, of course, for this you need to create widgets that will allow you to edit these pages

**Comment by shilo-ey** [comment]
Thanks, this is indeed something in our roadmap.

I merged this issue with #5383, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
