### ISSUE TITLE
Help embedding actionscript 3.0 into site

### ISSUE THREAD

**Issue by scio7** [elementor/elementor#12042]
I am in the process of embedding a dress up game into my site, and would love to have some help. I currently have  swc, swf, and fla files. I uploaded it into the website, and it's currently not working. Also tried html5 since I know flash is basically dead. What file format would I save it in, if it is not possible with actionscript 3.0? Thanks

**Comment by rami-elementor** [comment]
Hi @scio7 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
