### ISSUE TITLE
Tweak : add icon on flyover widget Button

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12058]
on the "BUTTON" widget, there is the possibility to add an icon (on the right or on the left), so an option should be added so that the button icon appears only when the user passes over the button with the mouse

**Comment by udidol** [comment]
@rodolphebertozzo 
This can be easily achieved with CSS.
In Elementor pro, it's even easier with Custom CSS. 
If you have Elementor Pro, you can edit the widget, go to Advanced > Custom CSS, and add the following:

```
selector .elementor-button-icon {
    display: none;
}

selector:hover .elementor-button-icon {
    display: block;
}
```

We are not planning to add this as an option at this time.

**Comment by rodolphebertozzo** [comment]
Tanks :)

**Comment by rodolphebertozzo** [comment]
Thanks, I'll leave this number open in case one day this function is merged ;)

**Comment by rami-elementor** [comment]
Hi @rodolphebertozzo ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being.

Please feel free to contact us again with other feature suggestions.

Regards,
