### ISSUE TITLE
Form: Changing color of form field border shouldn't affect visibility of Select field menu triangle 

### ISSUE THREAD

**Issue by zevrix** [elementor/elementor#12053]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When changing the color of form field border, it also changes the color of the Select field popup menu triangle. So if the border color is fairly light, the menu triangle becomes nearly invisible and also looks like it's disabled. 

**Describe the solution you'd like**
The popup triangle should always be distinctively visible regardless of the field border color. 

**Describe alternatives you've considered**
None as far as I know

Thanks,
Leo

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.6

Feel free to update

Thanks!
