### ISSUE TITLE
Font Awesome 5.14

### ISSUE THREAD

**Issue by gilesholder** [elementor/elementor#12057]
Could we have font awesome 5.14 support in V3? Currently, its still on 5.12 and has had a few patches and icon updates since then which would be great to benefit from.

**Comment by draconnia** [comment]
> Could we have font awesome 5.14 support in V3? Currently, its still on 5.12 and has had a few patches and icon updates since then which would be great to benefit from.

Yes, on previous versions to 5.14 Lighthouse is warning about it.
On version 5.14 they changed font-display:auto to  font-display:block. on font face declaration.
Please update to 5.14 at least

**Comment by gilesholder** [comment]
If this is not going to ship for a few months is it worth working on Font Awesome 6 compatibility. Version 6 is already in the Alpha stage and should be released by the end of the year. See their timetable here: https://fontawesome.com/6#timetable

It would be great to have this functionality as soon as it's available and beating the other page builders to it would not be a bad thing either.

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
