### ISSUE TITLE
Prevent loading "Google Maps" Script when using elementor

### ISSUE THREAD

**Issue by tomer183** [elementor/elementor#12055]
Elementor is loading google maps script with default settings despite i'm not using the google maps widget.
how it can be removed?

soory fot the short bug report.

**Comment by arielk** [comment]
As far as I know we do not load the Google Maps script when the widget is not loaded on the page. In fact even when it's on the page, the script comes as part of embedding the map on the page, just as you would embed the map yourself without an Elementor widget.

For now I'm closing the issue, open it in case you have more information.
