### ISSUE TITLE
Templating for items in archive

### ISSUE THREAD

**Issue by tomatpercipi** [elementor/elementor#12059]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A very simple issue that can be corrected by free plugin, but its so logical that it should be in Elementor Pro : when building an archive template, you can't use custom fields.

**Describe the solution you'd like**
We should be able to edit the item template within the archive post module to be able to add whatever field we want... (phone number for team, note for reviews etc...)

**Describe alternatives you've considered**
a free plugin called Elementor Custom Skin

**Additional context**

**Comment by TomRaraAvis** [comment]
This is best related post with more attention. Post has been around longer w/ more discussion #4440

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
