### ISSUE TITLE
Rename Global Widgets Ability

### ISSUE THREAD

**Issue by ArdentVerve** [elementor/elementor#12052]
My apologies since this has been submitted before, with pleas from nay but was closed. I didn't see that it was resolved, added to a list for future update, or any explanation really.

Please, please, can you make Global Widgets have the ability to be renamed? I'm running across the necessity for this quite often.

Please, please, pretty please... with a cherry on top.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/1578 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
