### ISSUE TITLE
Just columns in menu, a simple megamenu

### ISSUE THREAD

**Issue by tomatpercipi** [elementor/elementor#12060]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
in other builder I use, it's quite simple to add columns in menu, and I'm not talking about big fat mega menu

**Describe the solution you'd like**
A simple way to add columns in menus, that's all, because is often a good UI solutions to separate blocs of menu items without additional submenus

**Describe alternatives you've considered**
don't wanna use a plugin for such a need because I don't need huge megamenu that add to many bloat

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
