### ISSUE TITLE
Insufficient widgets

### ISSUE THREAD

**Issue by mauriziogalli** [elementor/elementor#12093]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Considering the cost and high quality of elementor I think you should increase the number of widgets, self producing them or acquiring a company that has already produced them. Best regards

**Comment by arielk** [comment]
Thanks for your feedback, we always try to improve our product, if you have specific widgets you need please specify according to [our guidelines](https://github.com/pojome/elementor/issues/new?template=Feature_request.md)
