### ISSUE TITLE
Scaling field width in Forms should also have 30%

### ISSUE THREAD

**Issue by gpglang** [elementor/elementor#12096]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like to be able to have three columns in 20-30-50 width (firstname, lastname, email); must be 100% all together.  That is not possible.  I understand the choice 33%.  But that should not leave 30% out the choice list

**Describe the solution you'd like**
Add 30% as an option

**Describe alternatives you've considered**
Only choices I see now is 20-40-40 when the first 40 is to much and the second 40 is often to small

**Additional context**

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
