### ISSUE TITLE
Counter stopped working after WP 5.5 update

### ISSUE THREAD

**Issue by jcded** [elementor/elementor#12109]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Updated to WP 5.5 and having issues with the counter feature. The counters do not count up in most cases, they remain at 0. Tried on different browsers in private/incognito mode (Chrome/Firefox/Edge)

## Isolating the problem
- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.25-28
	PHP Version: 7.3.20
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://flightpathlax.com
	Home URL: https://flightpathlax.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Neve
	Version: 2.7.6
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0

== Active Plugins ==
	Backup
		Version: 1.4.2
		Author: BackupGuard

	Contact Form 7
		Version: 5.2.1
		Author: Takayuki Miyoshi

	Contact Form 7 Extension For Mailchimp
		Version: 0.5.20
		Author: Renzo Johnson

	Elementor
		Version: 2.9.14
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.0.0
		Author: Facebook

	FileBird Lite
		Version: 4.0.5
		Author: Ninja Team

	GA Google Analytics
		Version: 20200325
		Author: Jeff Starr

	Google Analytics for WordPress by MonsterInsights
		Version: 7.12.2
		Author: MonsterInsights

	Gutenberg Blocks and Template Library by Otter
		Version: 1.5.7
		Author: ThemeIsle

	Header and Footer Scripts
		Version: 2.2.1
		Author: Digital Liberation

	Indeed Ultimate Membership Pro
		Version: 8.9
		Author: WPIndeed Development

	Jetpack by WordPress.com
		Version: 8.8.1
		Author: Automattic

	Mailchimp for WooCommerce
		Version: 2.4.5
		Author: Mailchimp

	MC4WP: Mailchimp for WordPress
		Version: 4.8
		Author: ibericode

	Members
		Version: 3.0.10
		Author: MemberPress

	Orbit Fox Companion
		Version: 2.9.16
		Author: Themeisle

	SG Optimizer
		Version: 5.6.2
		Author: SiteGround

	The Events Calendar
		Version: 5.1.5
		Author: Modern Tribe, Inc.

	The SEO Framework
		Version: 4.1.0
		Author: The SEO Framework Team

	Ultimate Addons for Elementor
		Version: 1.26.2
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.16.26
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 4.3.2
		Author: Automattic

	WooCommerce Admin
		Version: 1.3.2
		Author: WooCommerce

	WooCommerce PayPal Checkout Gateway
		Version: 2.0.3
		Author: WooCommerce

	WooCommerce Services
		Version: 1.24.0
		Author: Automattic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WordPress Starter
		Version: 1.1.1
		Author: SiteGround

	WP-Members
		Version: 3.3.5.1
		Author: Chad Butler

	WPForms Lite
		Version: 1.6.2.2
		Author: WPForms

== Elements Usage ==
	
	wp-post : 2
		alert : 1
		button : 7
		counter : 3
		divider : 2
		google_maps : 1
		heading : 14
		icon-box : 11
		icon-list : 1
		image : 5
		menu-anchor : 4
		shortcode : 1
		social-icons : 1
		spacer : 7
		text-editor : 7
		video : 1
	wp-page : 36
		alert : 1
		button : 4
		content_form_contact : 2
		counter : 4
		divider : 3
		google_maps : 2
		heading : 25
		html : 3
		icon-box : 12
		icon-list : 10
		image : 44
		image-box : 12
		image-gallery : 2
		menu-anchor : 1
		shortcode : 3
		spacer : 25
		tabs : 1
		text-editor : 65
		uael-timeline : 1
		ump-select-level-shortcode : 1
		video : 1

== Log ==
	
JS: showing 4 of 4JS: 2020-02-10 02:52:12 [error X 984][https://flightpathlax.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.4.7:2:19416] this.getColorRepresentation(...) is null 
JS: 2020-02-10 13:45:30 [error X 1][https://flightpathlax.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.5:2:110310] e is undefined 
JS: 2020-02-23 23:59:51 [error X 16][https://flightpathlax.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.2:31:196469] i is undefined 
JS: 2020-02-23 23:59:56 [error X 5][https://flightpathlax.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.2:31:168825] r.get(...).models is undefined 

Log: showing 11 of 112020-02-17 04:34:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.2',
)]
2020-02-27 06:29:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-07 03:10:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-13 16:56:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.6',
)]
2020-03-27 07:59:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-04-23 14:45:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]
2020-05-25 07:06:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-06-08 14:05:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.11',
)]
2020-06-16 21:06:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.12',
)]
2020-06-26 17:05:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '2.9.13',
)]
2020-07-23 12:35:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]

				
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @jcded 

The issue origins from JS error you have in your code:
![image](https://user-images.githubusercontent.com/45009641/90112730-0d1c2e80-dd59-11ea-8f51-572d96919c3b.png)


This "breaks" the JS code that supposed to run the counter widget.

Please try to fix these errors and you should be fine.

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress Twenty twenty or Hello theme (or other default WordPress theme).


And see if the issue still persists
