### ISSUE TITLE
Global And Page CSS and JS

### ISSUE THREAD

**Issue by folusuk** [elementor/elementor#12104]
I think this would help a lot of users, web designers and developer, by making the the CSS editor full page instead of the left sidebar, with a couple of features built into it,
1. CSS tidy - so the code is in a easy to read human format
2. minify checkbox, to minify the output to the browser
3. priority selection - to override the wordpress queue from the default theme css to the elementor css.
4. position - head or footer to compensate for render blocking errors

also add the list above for custom JS this will be very helpful

**Comment by rami-elementor** [comment]
Hi @folusuk 

Elementor Pro the "Custom Code" feature - https://elementor.com/help/custom-code-pro/#:~:text=The%20Custom%20Code%20feature%20allows,to%20edit%20your%20theme's%20files.

It has some of the features you mentioned above.

**Comment by nicholaszein** [comment]
Hello @folusuk,

Thank you for submitting a feature request! 🙏 

#### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
