### ISSUE TITLE
Custom color does not appear instantly

### ISSUE THREAD

**Issue by edertuffic** [elementor/elementor#12107]
Hi.

When I create a new custom color for the menu text and then I will change the color of the pointer to the same color I just created, it is not available.

Look:
I created the color for the text, ok!
http://prntscr.com/tyk53l

When I change the color of the pointer, it does not appear.
http://prntscr.com/tyk5ld

Only Elementor is active on this site.

[system-info-coletivopontecultural.com.br-12-08-2020.txt](https://github.com/elementor/elementor/files/5065143/system-info-coletivopontecultural.com.br-12-08-2020.txt)

**Comment by shilo-ey** [comment]
Please report beta issues in the [beta thread only](#11821),

Thanks.
