### ISSUE TITLE
conflict between responsive "greyed out" function and navigator "hide" function 

### ISSUE THREAD

**Issue by Lemente** [elementor/elementor#12123]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

This bug report is a duplicate of #4775 , which has been, I believe, wrongly tagged as a feature request and wrongly closed. I encountered that problem on three different instances of Wordpress.
I opened a ticket, tried everything that was asked, without any luck.

## Description

There are multiple ways to describe the issue (included for SEO) : 
- element hidden in navigator reappears when hiding it in responsive
- navigator "hide" button doesn't hide greyed out elements
- cannot hide element hidden in another responsive mode that the current one
- cannot hide greyed out elements in Elementor edit mode
- cannot hide elements on edit screen that have been hidden with the responsive functionnality
- the "greyed out" functionnality for responsive elements seems to force an element to be visible, wether it has been hidden in the navigator or not

## Steps to reproduce

- create an element
- open navigator
- stay in desktop view
- click the eye icon to hide your Element (not its container!) (your Element isn't visible anymore)
- in Advanced/responsive, hide it for desktop (your Element appears back, and is is greyed out)
- go in tablet or mobile view (your element instantly disappear)
![Elementor_bug_report_hide_responsive_element_cropped](https://user-images.githubusercontent.com/27686967/90252394-b3dafa80-de3f-11ea-80ea-9a4d270eb0db.gif)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
``` (please ask if necessary)
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.1

Feel free to update

Thanks!
