### ISSUE TITLE
No Edit with Elementor in wordpress 5.5 

### ISSUE THREAD

**Issue by aditya58singh** [elementor/elementor#12121]
After I updated the WordPress 5.5 there was no feature on-page to edit with elementor.

I downgrade WordPress then it was working fine. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

**Comment by alexplex** [comment]
Yeah, it's the same with WP Bakery Page builder.

**Comment by shilo-ey** [comment]
We added compatibility in v2.9.14

Please make sure your Elementor is updated.

If the issue persists please open a new issue with full details (system info etc..)
