### ISSUE TITLE
Misspelling of the Word "Occurred" in Default Error Message in Forms

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#12137]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

How long has the word occurred been misspelled as "occured" in the default error message of forms? 🤦‍♂️

![default-error](https://user-images.githubusercontent.com/1435355/90372797-f3bc0080-e03e-11ea-8fd9-49e54bc8f38f.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.1

Feel free to update

Thanks!
