### ISSUE TITLE
Custom Data Table feature with CRUD functions

### ISSUE THREAD

**Issue by thhvancouver** [elementor/elementor#12132]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently Elementor is only able to query tables native to Wordpress. Even though it is able to work with custom fields created by plugins like Advanced Custom Fields, it is does not have the ability to natively create and read data, and simply calls the existing wordpress functions to do so. This is particularly a problem when creating surveys on the website. Once a survey is created with Elementor Form widget, we need to manually create a MySQL datatable to capture the data, use a webhook like Zapier to post the data to the table in the local MySQL database. Afterwards, it's not possible to work with the data anymore (such as creating a dynamic chart based on the survey result) because Elementor cannot query data in a foreign database to Wordpress
**Describe the solution you'd like**
It would be amazing if we can have an integration with a data table plugin like WP Data Access *https://wordpress.org/plugins/wp-data-access/), or a native data table widget with CRUD functions. This way, we will be able to query any MySQL tables, call the values in the current Elementor widgets as dynamic content, or simply display a data table that displays the values
**Describe alternatives you've considered**
I have tried to integrate WP Data Access to my elementor page. I am able to use the plugin's short codes to integrate the data tables, but then I don't have the ability to format the data table directly through Elementor and have to do so manually with CSS. A more critical problem is that this still doesn't solve the problem that the data tables created by WP Data Access remains outside of Elementor's dynamic queries, which means I cannot display any data entered using the plugin
**Additional context**

**Comment by arielk** [comment]
I hope that understand you well, you can use a Custom Query Filter to that, you can read more here:
https://developers.elementor.com/custom-query-filter/

Let me know if it works for you
