### ISSUE TITLE
Global text colors are missing after update to WordPress 5.5

### ISSUE THREAD

**Issue by AlexBlack357** [elementor/elementor#12135]
After update to WordPress 5.5 I can't set global (o any) text/title colors: when I delete unneeded color (drag and drop to trashcan), all colors disappears from color picker, and new ones can't be added.
I switched themes, deactivated plugins, cleared cache (browser, server) and nothing helps.
When I fresh install WordPress 5.4.2 and elementor/elementor pro, everything is Ok - after update to WordPress 5.5 problem returns.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!
