### ISSUE TITLE
BETA 3.0 - Theme Style not applying to Woocommerce

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12130]
Hi.
I dont know why Elementor is not changing the Default Color for Buttons on Woocommerce. If you change Forms and Inputs works... But for everything else is not working.
![image](https://user-images.githubusercontent.com/68023943/90043290-4776c480-dca2-11ea-8910-b02f476f96f6.png)
![image](https://user-images.githubusercontent.com/68023943/90043411-74c37280-dca2-11ea-9ac2-501ef4186070.png)
![image](https://user-images.githubusercontent.com/68023943/90043490-915faa80-dca2-11ea-95cb-b60ba29156b2.png)
![image](https://user-images.githubusercontent.com/68023943/90043526-9f153000-dca2-11ea-86ff-2ed879ef03d3.png)

**Comment by shilo-ey** [comment]
Hi @maurocarreraok 

These settings are deriving from WooCommerce. their selector is "stronger" than Elementor's.

It is on our roadmap to handle these areas.

Please share beta remarks in the beta thread only.

Thanks

**Comment by nicomollet** [comment]
Absolutely need for ecommerce websites.
At the moment buttons and inputs are inconsistent.
