### ISSUE TITLE
Hability to choose files from media library on Icon List Widget

### ISSUE THREAD

**Issue by saulobraine** [elementor/elementor#12144]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sometimes I need to make a PDF's list for any reasons. So I'm need to upload to Media, get the link from upload, before link put on "Link" option in Widget. In a large list this become a inviable and a lot of more time to do. 

**Describe the solution you'd like**
Create an option on dynamic tags from icon list for define a source of link:
- If is a link is a file from Media (this make more sense, cause it is possible to link any media)

**Comment by arielk** [comment]
Great suggestion, but I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback!
