### ISSUE TITLE
Add Control to existing Repeater

### ISSUE THREAD

**Issue by Hubvill** [elementor/elementor#12145]
## Prerequisites
- [x]  I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello team,

I am trying to add a control to an existing repeater for the tabs widget, but cannot seem to figure out how to go about doing this. I have searched for similar issues and could not find a solution.

Here is what I have tried so far:

```
add_action( 'elementor/element/tabs/section_tabs/before_section_end', function( $element, $args ) {

        // This adds a control, but not within the repeater 

	// $element->add_control(
	// 	'custom_control',
	// 	[
	// 		'type' => \Elementor\Controls_Manager::NUMBER,
	// 		'label' => __( 'Custom Control', 'plugin-name' ),
	// 	]
	// );


	// This sort of works, but I get the following error and I'm pretty sure this is the wrong way to do this:
	// Notice: Undefined index: name in /www/wp-content/plugins/elementor/includes/base/controls-stack.php on line 2025

	// First get the repeater control
	$control_data = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $element->get_unique_name(), 'tabs' );
	if ( is_wp_error( $control_data ) ) {
		return;
	}

	// Then you can access and modify the repeater fields as an array directly
	$control_data['fields']['tab_link'] = [
		'type' => \Elementor\Controls_Manager::NUMBER,
		'label' => __( 'Custom Control', 'plugin-name' ),
	];

	// And then just update the control in the stack/element
	$element->update_control( 'tabs', $control_data );

}
```

If someone can point me to the right direction that would be great!

**Comment by Hubvill** [comment]
I was getting the `Undefined index: name` error because I forgot to define the name property in the array.

```
	$control_data['fields']['tab_link'] = [
		'type' => \Elementor\Controls_Manager::NUMBER,
		'label' => __( 'Custom Control', 'plugin-name' ),
	];
```

Should be:

```
	$control_data['fields']['tab_link'] = [
		'type' => \Elementor\Controls_Manager::NUMBER,
		'label' => __( 'Custom Control', 'plugin-name' ),
		'name' => 'tab_link', // This was added
	];
```

Hope that helps someone.

**Comment by mattloker** [comment]
Hey Hubvill,
this helped my a lot. I was able to add a custom controller (a text Field) to the icon list repeater(with the help of your code) but it wont render the value of the field in the output. How did you manage to update the output?

**Comment by mattloker** [comment]
Hey @Hubvill ,
this helped my a lot. I was able to add a custom controller (a text Field) to the icon list repeater(with the help of your code) but it wont render the value of the field in the output. How did you manage to update the output?
