### ISSUE TITLE
Keyboard Shortcuts don't work in Microsoft Edge on Mac

### ISSUE THREAD

**Issue by zevrix** [elementor/elementor#12146]
Keyboard Shortcuts don't work in Microsoft Edge on Mac.

I know it's not the end of the world as they do work in other browsers.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #6145, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
