### ISSUE TITLE
Facebook comments widget only apear in mobile

### ISSUE THREAD

**Issue by sermalefico** [elementor/elementor#12157]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Facebook comments only apear in mobile. 

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.1

Feel free to update

Thanks!

**Comment by sermalefico** [comment]
@shilo-ey sorry but the issue is not fixed.
