### ISSUE TITLE
Elementor Form Not Submitting, Showing "Error X"

### ISSUE THREAD

**Issue by edi365** [elementor/elementor#12154]
Hi,

When trying to submit a form I get an "error X" as you can see in this image: https://imgur.com/a/kWMvq0w

I searched and found out that there is a new bug, that occurs when the form's steps settings type is set to "None" or "Progress Bar". I changed these settings and the same error still appears.

I would really appreciate your thoughts on why it happens and how to solve this.

Thanks,
Edi

---------------UPDATE---------------

I deactivated the "WP Mail SMTP Pro" plugin and all works well. I don't know if the issue is on elementor's side or not, but here is a fix that worked for me.

**Comment by shilo-ey** [comment]
WordPress 5.5 changed the mailing mechanism. 

Please make sure to use different SMTP plugin or other solution.

This issue is not related to Elementor

Thanks
