### ISSUE TITLE
Popup cookies conditions 

### ISSUE THREAD

**Issue by Wpcreatures** [elementor/elementor#12151]
Hello!
Hope you are doing well. 
I just figured out that when we add popup on website. It appears again and again every time when i click some other page on website after closing popup. I think there should be cookies conditions that a user can see popup only once a day or once a week.
This is a big thing that popup should have. It would be good if you add cookies feature in popup conditions. 
Thanks

**Comment by Manjupmf** [comment]
+1 

https://github.com/elementor/elementor/issues/8187

The above ticket is open for more than a year.

@Wpcreatures We must wait a few years more I guess!

**Comment by Wpcreatures** [comment]
Hi,
For what we have to wait for years.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #8187, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
