### ISSUE TITLE
PHP 7.4 Deprecated error Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by ajoah** [elementor/elementor#12161]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

On an old website, accordion created with elementor 1.7.12 and less triggers a deprecated errors :
![image](https://user-images.githubusercontent.com/10757301/90613536-cbccc880-e209-11ea-9e8e-91833a5ab207.png)

The first accordion was created on 1.7.12 version, the second on 2.9.14 version

(`string(7)...` are debug informations)

## Steps to reproduce
on PHP 7.4 installation : 
 - install elementor 1.7.12
 - add an accordion on a page
 - update elementor to last version

## What I think

On version 1.7.12 and before elementor uses a base 36 identifier : https://github.com/elementor/elementor/blob/v1.7.12/assets/js/editor.js#L4954
Since version 1.8.0 elementor uses a base 16 identifier : https://github.com/elementor/elementor/blob/v1.8.0/assets/js/editor.js#L5210
At the same time you added the function : 
https://github.com/elementor/elementor/blob/1312d3c07bf80a5db7a47d27bc345de6b5a65b28/includes/base/controls-stack.php#L155-L157
So hexdec can be applied on characters after "f", because elementor 1.8.0 did not update the old ids.
No problem on PHP 7.3 but on PHP 7.4 : https://3v4l.org/MLim8

On the image above i displayed id of accordions, as you can see the accordion's id created with 1.7.12 version contains not allowed characters (y, k and w)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
Sorry but i don't want copy the report on a public message because it contains a lot of informations of the server.
```
Elementor 2.9.14
WP 5.5
PHP 7.4
```

**Comment by shilo-ey** [comment]
Thanks!

This issue has been resolved in Elementor v3.0.2

Feel free to update
