### ISSUE TITLE
Color Picker doesn't save presets in WP 5.5

### ISSUE THREAD

**Issue by lexigladedigital** [elementor/elementor#12163]
When choosing color presets in the Elementor Theme or page editor, colours are not saved for future use when added with the [+] button. Binned colors stay gone, however.

Rolling back to WP core 5.4 fixed the issue, so I suspect a compatibility issue with 5.5.

**Comment by caseyzman** [comment]
Same problem here.
I've been able to isolate the issue a little further. While adding colors sometimes works (after a browser refresh) removing or re-ordering colors causes all saved colors to disappear until the page is refreshed (and those actions, ie, deleting and/or re-ordering are not saved)
Errors in console attached:

![Picker-error-2020-08-12 at 4 26 30 PM](https://user-images.githubusercontent.com/4513781/90664721-a42d2e80-e210-11ea-8821-9e1f7953e9b1.jpg)

**Comment by qwik3r** [comment]
Was just about to post about this. Although I'm having another issue. If you open up something that already has a color, then click the + icon to add that color, it always adds black first. I have to move the color picker, than command Z back to the color I want, then click + to add it. 

Additionally, I'm noticing that if I drag the colors I don't want to the garbage, then look at the color picker, all the colors are gone and I have to refresh the page to see them. But refreshing the page, the colors don't delete. So now I have like 10 blacks. 

I have no plugins installed, this is a fresh install.

**Comment by arielk** [comment]
Thanks for your feedback!

We're going to change this behavior in Elementor 3.0 version that comes up next week.

Note that [Elementor 3.0 is currently in beta](https://github.com/elementor/elementor/issues/11821), so you can check it out in your development environment.

**Comment by qwik3r** [comment]
Is the official 3.0 out next week or a beta?

**Comment by arielk** [comment]
> Is the official 3.0 out next week or a beta?

Official release

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!
