### ISSUE TITLE
List of Templates in Templates | Saved Templates not displaying properly.

### ISSUE THREAD

**Issue by slewisma** [elementor/elementor#12173]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description
Regular templates aren't saving and are listing properly in WP Admin when The SEO Framework is active.

## Steps to reproduce
With 3.0 beta 3 I made a maintenance mode page template and saved it. I went to Templates | Saved Templates and the of template names was 1 character wide resulting in vertical names that was a mess to navigate. And my new template wasn't there. 

## Isolating the problem
This only happens with The SEO Framework plugin active and is likely because this plugin adds a column  to the WP Admin interface. Elementor needs to handle this better though as there are many plugins that add columns to WP Admin that might result in a similar problem.

**Comment by MichaelDarko** [comment]
+1

**Comment by arielk** [comment]
We do not add a custom style to the WP Admin table so we can do nothing to resolve it.

Thanks for your report.
