### ISSUE TITLE
Elementor run every WordPress hook twice

### ISSUE THREAD

**Issue by burhandodhy** [elementor/elementor#12178]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor runs every WordPress hook twice. Add the below code in your theme `functions.php` and check the logs. When the Elementor is activated the message is printed twice and when the Elementor is deactivated the message is printed only once. 

```
add_action( 'wp_head',function() {
	error_log('---------------------------------------------------------------------------------------------');
	error_log('WordPress Header Loaded');
	error_log('---------------------------------------------------------------------------------------------');
}  );

```

This problem cause the serious performance issue and use double server resources. 

## Steps to reproduce

1) Add the code in default theme.
2) Activate Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by MikevHoenselaar** [comment]
This is a serious issue. Hopefully there will be a fix very soon.

**Comment by salbatyku** [comment]
Just checked this, couldn't reproduce, it only printed once.

**Comment by DorShahar** [comment]
Hi 
We couldn't reproduce. 

Thanks for raising it.
