### ISSUE TITLE
Keep Google Fonts library up to date (regularly with every update)

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12172]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### **Problem**

Google Fonts library in Elementor is never up to date. I keep having problems of finding a font I want to use in Google Fonts, but then the font is not available in Elementor.

This time it's a font called "DM Serif Display " but I had the same problem with other fonts in the past. There are many other people here requesting specific fonts to be added, so I would like to open a general feature request for keeping Google Fonts up to date.

### **Solution**

I think there should be some system or a plan for keeping the library up to date regularly. Right now it seems the library is updated sporadically when you "feel like it". That's not a good approach for something so important.

Elementor should update the Google Fonts library with every update so it's up to date. 

I never experienced this issue with other tools using Google Fonts.

**Comment by DeoThemes** [comment]
Same, been waiting DM Sans for more than one year - https://github.com/elementor/elementor/issues/8637

**Comment by arielk** [comment]
You're right, we need to get better at this point. We will take this to our attention. For now we've done an update for version 3.0, so I'm closing this issue.
