### ISSUE TITLE
On Drag and Drop of social icon button from elementor panel does not appear any thing on column. 

### ISSUE THREAD

**Issue by AyushSeth** [elementor/elementor#12184]
Hello,

While I was drag and Drop the social icon button inside a column no icons appeared not even borders came.
Though when I drag the icon in column the elementor panel display the social links but no icons and borders are displayed. 
I also try to put border colors in styles but still no change.
Please help me.
As I have disabled all the plugins and only elementor active.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
