### ISSUE TITLE
Problem with loading videos in the background for section

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12198]
As you can see, during the first upload, even if it takes 2 seconds on average, there are YouTube items even though it's a background, it's not nice for the rendering.
![IMG_20200823_233127](https://user-images.githubusercontent.com/56270626/90989188-0aaba700-e599-11ea-82a7-af16eb499431.jpg)

**Comment by lior-sh** [comment]
Hi @rodolphebertozzo, 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by rodolphebertozzo** [comment]
With Chrome for mobile and for all browser for the computer

**Comment by rodolphebertozzo** [comment]
@shilo-ey

**Comment by rodolphebertozzo** [comment]
@arielk

**Comment by rodolphebertozzo** [comment]
One answer a Day ?

**Comment by rodolphebertozzo** [comment]
@shilo-ey

**Comment by udidol** [comment]
@rodolphebertozzo,
Youtube used to allow hiding the TItle and controls when the video first loads. 
It is not possible anymore unfortunately, because that option was removed by Youtube.
