### ISSUE TITLE
Elementor 3 broke all my links.

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [elementor/elementor#12202]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I was using Version 2.9.9 and just upgraded to 3. Noticed all my links broke. Instead of taking me to mysite.blah.com/somepage, it linked just to 'somepage', thereby getting a 'server could not be found'. Reverting to Version 2.9.9 fixed this.

I'm using the free version of your plugin and the Twenty Seventeen theme.

**Comment by lior-sh** [comment]
Hi @CodingMonkeyXYZ,

Thanks for reporting, can you please write the **steps to replicate** & **system info**?
Thanks.
