### ISSUE TITLE
Share Buttons don't work on elementor 3.0

### ISSUE THREAD

**Issue by shaulhadarn** [elementor/elementor#12205]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

I am trying to add the social share widget in my single post template.  Whenever i use it it shows nothing, and afterwards if you press on another element, and than go back, you can't find the element, it will only show in the navigation element.

## Steps to reproduce

1. open a new single post template.
2. add the social share widget
3. nothing happenes

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: MariaDB Server v5.6.47-87.0
	PHP Version: 7.2.33
	PHP Max Input Vars: 5000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://livriuta.lm-studio.co.il
	Home URL: https://livriuta.lm-studio.co.il
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: he-IL
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.0.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.0
		Author: Elementor.com

	Elementor SuperCat
		Version: 2.5.3
		Author: Nicola Cavallazzi

	Modern Events Calendar Lite
		Version: 5.10.0
		Author: Webnus

	Piotnet Addons For Elementor
		Version: 2.4.1
		Author: Luong Huu Phuoc (Louis Hufer)

	Polylang
		Version: 2.8
		Author: WP SYNTEX

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		form : 1
		heading : 2
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	header : 1
		image : 2
		nav-menu : 1
		wp-widget-polylang : 1
	loop : 5
		button : 5
		divider : 5
		heading : 5
		icon-list : 6
		image : 5
		post-info : 4
		text-editor : 3
	page : 5
		button : 4
		call-to-action : 3
		divider : 4
		heading : 3
		icon-list : 2
		image : 3
		posts : 1
		text-editor : 3
	single : 3
		divider : 1
		facebook-comments : 2
		heading : 5
		post-comments : 2
		post-info : 5
		posts : 2
		search-form : 1
		share-buttons : 1
		social-icons : 1
		text-editor : 2
		theme-post-content : 3
		theme-post-featured-image : 2
		theme-post-title : 2
		video : 1
		wp-widget-tag_cloud : 1
	wp-page : 16
		button : 9
		call-to-action : 4
		divider : 14
		flip-box : 2
		form : 2
		heading : 18
		icon-list : 1
		image : 22
		portfolio : 1
		post-filter : 1
		post-info : 4
		posts : 11
		premium-img-gallery : 1
		slides : 2
		social-icons : 1
		text-editor : 23

== Log ==
	
JS: showing 7 of 7JS: 2020-07-19 07:45:08 [error X 6][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.2:2:54590] Cannot read property \'top\' of undefined 
JS: 2020-07-19 09:30:03 [error X 1][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.13:31:153580] Cannot read property \'html\' of undefined 
JS: 2020-07-22 11:26:20 [error X 1][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.13:31:217009] Cannot read property \'getBoundingClientRect\' of null 
JS: 2020-07-26 07:35:33 [error X 19][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.9.13:2:59543] Cannot read property \'attributes\' of undefined 
JS: 2020-07-26 07:48:18 [error X 5][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-08-20 07:20:48 [error X 7][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:31:160243] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-08-24 10:05:08 [error X 1][https://livriuta.lm-studio.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view72\") has already been destroyed and cannot be used. 

Log: showing 14 of 142020-07-19 09:17:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.2',
  'to' => '2.10.3',
)]
2020-07-26 08:22:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-08-24 10:14:56 [info] elementor::elementor_updater Started 
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-24 10:14:56 [info] אלמנטור/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-24 10:14:57 [info] אלמנטור/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-24 10:14:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-24 10:14:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-24 10:15:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]

PHP: showing 3 of 3PHP: 2020-07-21 08:52:00 [notice X 3][/var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-30 07:40:04 [error X 1][/var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on boolean in /var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/vhosts/livriu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-19 16:06:59 [notice X 12][/var/www/vhosts/livriuta.lm-studio.co.il/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by arielk** [comment]
Thanks for reporting,

Please deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and see if the issue still persists.

**Comment by shaulhadarn** [comment]
Hi Ariel, thanks for getting back to me.
Yes, I tried deactivating all plugins and the issue it still there.

No matter where i try to put the share buttons, they don't work...

**Comment by arielk** [comment]
Can you please share with us the link to the page with the share buttons so we can check it?

**Comment by shaulhadarn** [comment]
Hi Ariel, I have created a new page named "TEST".
It has a text widget, and underneath the share buttons widget, you won't see it but its there...

https://livriuta.lm-studio.co.il/test/

Let me know how I can help it you need me to check anything else.
Thanks !

**Comment by shaulhadarn** [comment]
Hi I just checked and i have adguard installed. as soon as i disabled it i could see the widget again!  still this is something that has to be fixed, I hope this helps in any way...

**Comment by arielk** [comment]
What is **adguard**?

Anyway it works perfect for me so I close this issue right now, thanks for your reporting.

**Comment by shaulhadarn** [comment]
Hi, it is an extension for chrome to block ads..
