### ISSUE TITLE
global colors - rearrange possition of the saved colors

### ISSUE THREAD

**Issue by webmasterbart** [elementor/elementor#12203]
Missing feature in the latest stable version of Elementor ( Elementor Pro. )

In the site settings I need to be able to change the position of the added "saved colors".
Primair, secundair, text and accent can have fixed positions.
But when you add "saved colors" over time, things can become messy and I should be possible to rearrange them in a logical sequence.

**Comment by fabianenzensperger** [comment]
This was already criticized and demanded in the beta phase, unfortunately it was probably not added ...

**Comment by webmasterbart** [comment]
Ok.. ☹

 

Half step forward, half step backward…

 

Van: fabianenzensperger <notifications@github.com> 
Verzonden: maandag 24 augustus 2020 15:32
Aan: elementor/elementor <elementor@noreply.github.com>
CC: webmasterbart <webmaster@verdographics.be>; Author <author@noreply.github.com>
Onderwerp: Re: [elementor/elementor] global colors - rearrange possition of the saved colors (#12203)

 

This was already criticized and demanded in the beta phase, unfortunately it was probably not added ...

**Comment by fabianenzensperger** [comment]
> Ok.. ☹ Half step forward, half step backward…>


Yes. And actually the beta phase is not yet over. LOL.

**Comment by webmasterbart** [comment]
Yes, it feels like beta…

I just installed it and I have double “Theme Builder” buttons in the wordpress nav.

 

A bit disappointed. Nevertheless, I am a big fan of Elementor.

 

 

 

Van: fabianenzensperger <notifications@github.com> 
Verzonden: maandag 24 augustus 2020 15:41
Aan: elementor/elementor <elementor@noreply.github.com>
CC: webmasterbart <webmaster@verdographics.be>; Author <author@noreply.github.com>
Onderwerp: Re: [elementor/elementor] global colors - rearrange possition of the saved colors (#12203)

 

Ok.. ☹ Half step forward, half step backward…>

Yes. And actually the beta phase is not yet over. LOL.

**Comment by black-eye** [comment]
+1 for rearranging the colors.
As mentioned above, it was requested during the beta, but not implemented (yet). 

BTW, I feel quite baffled about the new color management - couple of versions before they had introduced new (and bit buggy) version of color picker with the possibility of saving the color, which seemed to be the preparation for new global colors. Now they've just removed this function and placed the color management somewhere else with partially lesser functionality.

But this thread would be probably closed anyway, as it hasn't got all the "I have searched for similar issues" boxes checked. ;-)

**Comment by rodolphebertozzo** [comment]
+1

**Comment by dbfischer** [comment]
The new "Global Color" function in 3.0 is much worser than the color picker in 2.x which I really liked. **Several clicks** now in 3.0, if I only want to select a color I need once. Why a global color for changing the color in an element I only need once?
The color picker in 2.x was much more comfortable! One click and the color is changed. Also one click to define a color as preselection and arrange it in the order I like.
Please change the color picker in 3.0 to the old quality.

**Comment by fabianenzensperger** [comment]
> The new "Global Color" function in 3.0 is much worser than the color picker in 2.x which I really liked. **Several clicks** now in 3.0, if I only want to select **one color I need once**. Why a global color for changing the color in an element I only need once?
> The color picker in 2.x was much more comfortable! One click and the color is changed. Also one click to define a color as preselection and arrange it in the order I like.
> Please change the color picker in 3.0 to the old quality.

Global colors are much better! You just don't know yet. If it works properly and used properly, it will make some work easier. The fact of specifying colors in a different section in advance is just a matter of getting used to.

**Comment by shilo-ey** [comment]
Thanks, we will consider adding this feature in the upcoming versions.

**Comment by webmasterbart** [comment]
Great !

Thanks

 

Van: shilo-ey <notifications@github.com> 
Verzonden: vrijdag 28 augustus 2020 10:52
Aan: elementor/elementor <elementor@noreply.github.com>
CC: webmasterbart <webmaster@verdographics.be>; Author <author@noreply.github.com>
Onderwerp: Re: [elementor/elementor] global colors - rearrange possition of the saved colors (#12203)

 

Thanks, we will consider adding this feature in the upcoming versions.

**Comment by dbfischer** [comment]
Now I agree: "Global colors" are better. 
First I missed the normal color picker, but now I see it's a good solution: "Global colors" left and "Color picker" right button. Great!

**Comment by fabianenzensperger** [comment]
> Now I agree: "Global colors" are better.
> First I missed the normal color picker, but now I see it's a good solution: "Global colors" left and "Color picker" right button. Great!

But always complain first ... Joke! Yes the global colors are really cool! You can finally work with it consistently across the entire website. Sometimes you wonder at first that there is something else, but then you see that it has even gotten much better. 😍

**Comment by fabianenzensperger** [comment]
> Thanks, we will consider adding this feature in the upcoming versions.

@shilo-ey Cool, thanks! This is really very important when you use a lot of global colors and fonts. Especially with very complex websites! I hope it comes very soon. Keep it up! 👍🏼

**Comment by rodolphebertozzo** [comment]
Can you take it into consideration quickly. More and more users will very quickly feel its usefulness and limit if it is not implemented by the end of the year.

**Comment by vendojo** [comment]
Totally agree. @shilo-ey please add the option to re-order global fonts and global colors! Would be much appreciated.

**Comment by mcrowell** [comment]
This would be a great added feature! 👍

**Comment by webinsightin** [comment]
+1

**Comment by derKh4N** [comment]
Yes, plz! Do it, E. Ppl! 😉

**Comment by vovkasolovev** [comment]
+1, Please add color ordering to global colors.

**Comment by BimberOnline** [comment]
This would be an amazing feature. There could be this implementation for Global Fonts as well.

**Comment by taidang26** [comment]
+1

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!

**Comment by BimberOnline** [comment]
Fantastic! Thank you for this resource!
