### ISSUE TITLE
BUG - Wait... What? +15 sites broken.

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12212]
Guys...

You make a HUGE mistake throwing that update into Wordpress... I have over 15 sites... All broken. The Styles, The Global Config is not working. I have Wordpress 5.5 nothing works. Buttons with no style (or default), it change the color palette of my clients, menu styles, everything BROKEN...

I'm losing my mind... How can i fix this? I cant roll back, most of my clients have Sells or News on their websites (Newspapers or Online Stores) so rolling back to a backup it will be a mess!

Please... Give me a solution.

Button with a random style or default:
![image](https://user-images.githubusercontent.com/68023943/91117706-a4d92100-e665-11ea-8b5b-2c09f8be0940.png)

Titles with no style font or color.
![image](https://user-images.githubusercontent.com/68023943/91117728-b28ea680-e665-11ea-9cdf-180eaa323a22.png)

Menu with no style
![image](https://user-images.githubusercontent.com/68023943/91117744-c1755900-e665-11ea-87fb-94b7a34c0218.png)

Here you can see the button it was blue like the "Title" and the button and many more lose it as well..
![image](https://user-images.githubusercontent.com/68023943/91117826-f4b7e800-e665-11ea-9280-ffe1f081bbd0.png)

Another thing... All my sites now are updated and activated with Elemetor Pro... (NON OF THEM WORK).... Like, i cant even go to the templates manager, its said: GO PRO.... I've even disconect the sites, clean cache, check from other browsers and is not working either... I cant manage the templates, my licence is not working.

**Comment by TomRaraAvis** [comment]
roll back via **Elementor** > **Tools** > **Version Control** > **Rollback Version**

This does not affect sells or news on your clients websites. "Rolling back" in this way will only reinstall the previous version of Elementor. It will not get rid of any sells or news articles that have recently been posted.

You are confusing that with if you restore from a backup. That's when the older version of your site replaces the lastest version & that's when you would lose the sells and news. So, just roll back Elementor itself via **Elementor** > **Tools** > **Version Control** > **Rollback Version** and you should be okay.

**Comment by shilo-ey** [comment]
Hi @maurocarreraok 

Thanks for sharing this input.

Elementor 3.0 is a major version, which we suggest creating a backup before updating.

Updated and you're experiencing some issues?
You can rollback to the previous version, by going to Elementor > Tools > Version Control > Rollback Version as @TomRaraAvis suggested.

If your Pro plugin is turned off please upgrade your core to v3.0, and then rollback Pro, and just then rollback Pro version.

Thanks
