### ISSUE TITLE
Bug entre Elementor 3.0 et Woocommerce 4.4.1 sur WP 5.5

### ISSUE THREAD

**Issue by Libre2Lire** [elementor/elementor#12216]
Bonjour,
L'installation d'Elementor 3.0 provoque un bug à l'utilisation de certaines fonctions de Woocommerce 4.4.1 sur Wordpress 5.5
Notamment dans l'appel des catégories de produits ou des étiquettes de produits, qui affichent un code source HTML sans balise </html> de fin mais le signalement d'une erreur serveur Elementor entre { }

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites**.
* **Steps to replicate**.
* **Isolating the problem**.
* **System info**.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by MikevHoenselaar** [comment]
I think it's the same issue as described here: https://github.com/elementor/elementor/issues/12209

**Comment by arielk** [comment]
Merge to #12209
