### ISSUE TITLE
A looping in new Theme Builder 3.0.0

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#12230]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

**Description**

A problem that I noticed when I am in the new Theme Builder and click on the logo / heading in the top left corner, the Theme Builder reloads and when I want to get out of it (via the X in the top right), I stay in caught in a loop.

I think the solution here would be if the logo in the top left weren't clickable. Think about it!

**Steps to reproduce**

1. Open new Theme Builder
2. Click on the logo / heading in the left corner
3. Get out of theme builder with X in the right corner
4. Gefangen in einem Loop … HELP! :D

**Isolating the problem**

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Environment**

On my new installation. Theme is Hello from Elementor!

**Comment by fabianenzensperger** [comment]
Fixed in 3.0.2 THANKS!

**Comment by shilo-ey** [comment]
Thanks @fabianenzensperger
