### ISSUE TITLE
White wash on Elementor V.3.0.1

### ISSUE THREAD

**Issue by BAtiyat** [elementor/elementor#12234]
I just updated Elementor to 3.0.1, and the entire site had a White color (semi-transparent) cover on all pages.

Any idea what's happening here?

Thx

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by BAtiyat** [comment]
ok cool.
I'll see how that is done and try to repost

thx

**Comment by chloesun** [comment]
I had the same issue. I can view certain content in the editor, but all the content was not showing up in the view

**Comment by BAtiyat** [comment]
it's the background that changed, I tried to change it in Elementor: Hamburger menu/site settings/ scroll to SETTINGS, and change Background... but that went back to white as soon as I exited

Then I did it in the Customizer: General Options/General Settings/ then changed both Inner and Outer background... it worked.

I also found out that the BUTTONS color and size changed... this I was able to fix in Elementor: Hamburger menu/ site settings/ then set global colors... as some colors have changed.
also under Site Settings I had to reset the button colors... only then the colors went back to the same color.

Funny thing is, the SIZE of the button went back to the original SIZE, when I changed the COLOR...!!!

**Comment by chloesun** [comment]
Thanks for sharing that! @BAtiyat Where is Customizer, in Elementor or in WordPress?

**Comment by BAtiyat** [comment]
In the wordpress dashboard: Appearance/ Customize

BTW, I rolled back to the previous version 3.0.0, but still had to do all that, it did not change back to what it was before

**Comment by BAtiyat** [comment]
Ok, anyone found anything else?
I found over 20 things got f'd up with this update (from 3.0.0 to 3.0.1), and i'm not gonna open over 20 tickets.
Many things went out of wack, i.e....
- Icon sizes got changed
- I con hover responses (Grow is now more of a Side-Stretch, not Grow)
- More than half of the colors got changed
- Alignment went totally insane
- The Menu got doubled (now my menu has 2 of each item/page)
- The color tray is not user friendly (saved colors now in a List, not a palette, so to find your saved color you have to scroll, and if you have many, like in my case, then it's not practical) especially that when you try to save/add a customized color, a pop comes up (are you sure you want to create a new global color?) come on guys, this is way too impractical, the older palette was much easier and quicker
- Another color palette issue, the "CLEAR" button is gone, so to clear you have to slide the overlay slider, if you delete the code from the bottom of the color palette pop-up, nothing happens, it goes back to the same color
- I have a slider on my home page (Smart Slider), got pushed down
- A big problem when you go to Responsive mode, some changes don't show in the editor, you have to go to the mobile device (phone or ipad) to see if it worked (so far the buttons' changes don't show when i go to mobile/ipad mode in the editor, so back and forth between devices)

I did rollback to 3.0.0, even with re-installing the backup file, still many things didn't go back to how i had before, so I'm editing all AGAIN manually

Ok, this was too much for this ticket, i'll open another issue ticket to put all, but i think it's safe to say that it's better to look for another builder

**Comment by shilo-ey** [comment]
Try using the re-migrate option and see if this resolved this issue for you

I'm closing this issue for now. if you see this issue again please create a proper issue report.

Thanks again!
