### ISSUE TITLE
Elementor 3.0 WP 5.5 Internal server error 500 after update / on certain pages

### ISSUE THREAD

**Issue by ELkoos** [elementor/elementor#12233]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Updated to 3.0, both Elementor and Pro to current version, logged into admin, certain subpages don't execute, just show code, console in Chrome displays 500 Internal Server Error - problem is persistent on same page, reloading, cache clearing, etc doesn't solve this. Issue on 2.9.9 does not exist. 
Not being logged into page doesn't seem to reproduce this problem.

## Steps to reproduce

1. Update Elementor and Elementor Pro
2. Log into wp-admin
3. Try to open front-end/back-end pages

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

[system-info-labpharma.pl-25-08-2020.txt](https://github.com/elementor/elementor/files/5125488/system-info-labpharma.pl-25-08-2020.txt)

**Comment by shilo-ey** [comment]
Hi @ELkoos 

This issue probably caused by server issue or conflict with other plugin, hence we can't reproduce it.

Thanks,

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by ELkoos** [comment]
No, it wasn't my plugin or my server, because it was resolved by update 3.0.1. 
So yeah, it was Elementor.
