### ISSUE TITLE
Set predefined global colors and fonts

### ISSUE THREAD

**Issue by kissdaniell** [elementor/elementor#12244]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

Hi! Is there a way to setup global colors and fonts with code like with the schemes?
I used 
```
update_option( 'elementor_scheme_color', array($value) );
```
and 
```
update_option( 'elementor_scheme_typography', array($value) );
```
but can't find any similar solution for the new globals.

Thank you for your work!

**Comment by udidol** [comment]
Hi @kissdaniell,

There is currently no official API for creating globals.
However, there is an unofficial method of achieving what you are looking for. It is not a method we provide support for and we cannot guarantee it would work in the future.

Global Colors and Typography are associated with a Site Kit. Site kits are the package of general site settings, which include things such as Layout settings, Theme Style, Global Colors and Typography.

You can access your active kit and add a custom color to it by using the following code:

```
$kit_id = Plugin::$instance->kits_manager->get_active_id();
$kit = Plugin::$instance->documents->get( $kit_id );

$kit->add_repeater_row( 'custom_colors', [
	'_id' => Utils::generate_random_string(),
	'title' => 'Color Name', // Name your color here
	'color' => $color, // replace the $color variable with the color you want to add to the globals.
] );
```
