### ISSUE TITLE
Column widget "Widgets Space" option issue

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#12256]
[This](https://github.com/elementor/elementor/blob/master/includes/elements/column.php#L208) code when applied [here](https://github.com/elementor/elementor/blob/master/includes/elements/column.php#L217) can lead to an invalid rule like that:
```css
{{WRAPPER}} > .elementor-column-wrap > > .elementor-widget-wrap > .elementor-widget:not(.elementor-widget__width-auto):not(.elementor-widget__width-initial):not(:last-child):not(.elementor-absolute):"margin-bottom: {{VALUE}}px"
```

The problem is the double `>`.

Elementor v3
Elementor Pro v3

**Comment by shilo-ey** [comment]
Thanks!

Your suggestion has been released in v3.0.2

Feel free to update
