### ISSUE TITLE
After update can't edit Theme Builder?

### ISSUE THREAD

**Issue by Ruben2600** [elementor/elementor#12254]
Hello,

I updated Elementor Pro yesterday, now I can only access: Elementor = Templates = Theme Builder, doesn't work anymore.

When I click on theme builder I get this error:

**Error: Method get_site_editor_type does not exist**

Can anyone help me? I really need these on my site!

Greetings Ruben

**Comment by anybany** [comment]
try to deactivate your other plugins and reactivate them one by one.
in my case the plugin "disable blogging" does stop the new theme builder interface from loading...

**Comment by kynello** [comment]
Same issue with Dynamic Content for Elementor Plugin. 
When i disable it all is fine.... but i need this plugin to continue my web project.

**Comment by live-mesh** [comment]
The issue is usually with the plugins. We had this issue with our Livemesh Addons for Elementor plugin and it was fixed last night. BTW, is the 3.x version rolled back? I now see 2.10.3 version listed for download in my Elementor PRO account. I was able to download 3.x yesterday.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
