### ISSUE TITLE
Is it correct that screenshots do not show up in the library when they're added as a featured image?

### ISSUE THREAD

**Issue by ralphjsmit** [elementor/elementor#12255]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
I'm creating templates in Elementor, both sections and pages. When I open the Elementor library to insert a template, I see that the 'default' Elementor blocks and templates all have a preview image. I added screenshots to my own templates by visiting the Templates section in the admin and adding a featured image to templates. The screenshots however do not show up, only the plain title. When I export the templates and import them on another site, the images do not show up either.

## Steps to reproduce
I did it exactly like described here: [https://docs.waashero.com/docs/template-hero-for-elementor/how-to-upload-elementor-templates-and-add-screenshots/](https://docs.waashero.com/docs/template-hero-for-elementor/how-to-upload-elementor-templates-and-add-screenshots/).

I already checked that `allow_url_fopen` and `file_get_contents` are allowed.

Can anyone tell me if it is correct that screenshots do not show up or if it is a bug? 

Many thanks in advance!

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/4166 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
