### ISSUE TITLE
Elementor 3 --> links not rendering properly

### ISSUE THREAD

**Issue by slwirth** [elementor/elementor#12265]
#SOLVED

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Rendering is different in the editor than on the live page as far as links are concerned.
Further, some css appear in the inspector, which look like some Elementor style remainer (pink color code). I was a beta tester so I am familiar with the new settings, beta which was pretty buggy to the end (unlike earlier versions).

![image](https://user-images.githubusercontent.com/40966578/91314452-df9e9e80-e7b6-11ea-95a6-3bdc1bfaf62f.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: FreeBSD
	Software: Apache
	MySQL version: FreeBSD Ports v10.3.23
	PHP Version: 7.2.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://dev.360impact.ch
	Home URL: https://dev.360impact.ch
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0

== Active Plugins ==
	Admin Menu Editor
		Version: 1.9.7
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 5.9.0
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.8.0
		Author: WebDevStudios

	Duplicate Page
		Version: 4.2
		Author: mndpsingh287

	Elementor
		Version: 3.0.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.0
		Author: Elementor.com

	Element Pack
		Version: 5.3.2
		Author: BdThemes

	Enable Media Replace
		Version: 3.4.2
		Author: ShortPixel

	Google Analytics
		Version: 3.0.1
		Author: Themeco

	JetBlog For Elementor
		Version: 2.2.0
		Author: Crocoblock

	Media Library Assistant
		Version: 2.84
		Author: David Lingren

	Members
		Version: 3.0.10
		Author: MemberPress

	Optimize Database after Deleting Revisions
		Version: 5.0
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Permalink Manager Lite
		Version: 2.2.8.9
		Author: Maciej Bis

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	Relevanssi
		Version: 4.8.1
		Author: Mikko Saari

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	Search & Filter
		Version: 1.2.12
		Author: Designs & Code

	ShortPixel Image Optimizer
		Version: 4.20.2
		Author: ShortPixel

	Simple History
		Version: 2.35.1
		Author: Pär Thernström

	Toolbar Extras
		Version: 1.4.9
		Author: David Decker - DECKERWEB

	UpdraftPlus - Backup/Restore
		Version: 2.16.27.0
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.4.10
		Author: Wordfence

	WPML Media
		Version: 2.5.6
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.3.19
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.0.14
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.9.11
		Author: OnTheGoSystems

	WPS Hide Login
		Version: 1.5.6
		Author: WPServeur, NicolasKulka, tabrisrp

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.0
		Author: 

== Elements Usage ==
	
	archive : 4
		global : 1
		theme-archive-title : 1
	footer : 2
		form : 2
		heading : 3
		image : 8
		social-icons : 2
		text-editor : 14
	header : 5
		icon-list : 2
		image : 2
		nav-menu : 2
		search-form : 2
		social-icons : 2
	page : 11
		author-box : 1
		button : 1
		form : 2
		heading : 13
		icon-list : 1
		image : 12
		jet-blog-posts-navigation : 1
		nav-menu : 1
		post-info : 4
		share-buttons : 2
		social-icons : 3
		spacer : 2
		template : 2
		text-editor : 25
		theme-post-content : 2
		theme-post-excerpt : 2
		theme-post-title : 2
	section : 26
		bdt-post-block : 1
		button : 2
		form : 2
		heading : 6
		html : 1
		image : 8
		image-box : 7
		posts : 1
		search-form : 1
		social-icons : 1
		spacer : 6
		text-editor : 14
	single : 3
		author-box : 1
		button : 1
		image : 2
		post-info : 4
		share-buttons : 2
		spacer : 2
		template : 2
		text-editor : 1
		theme-post-content : 2
		theme-post-excerpt : 2
		theme-post-title : 2
	widget : 0
		button : 4
		gallery : 6
		jet-blog-smart-tiles : 4
		text-editor : 4
	wp-post : 6
		bdt-document-viewer : 5
		bdt-twitter-carousel : 1
		blockquote : 1
		button : 3
		gallery : 1
		global : 14
		heading : 82
		html : 1
		icon-list : 2
		image : 32
		image-box : 38
		jet-blog-smart-tiles : 2
		media-carousel : 1
		menu-anchor : 8
		spacer : 20
		template : 37
		text-editor : 143
		toggle : 1
	wp-page : 24
		heading : 2
		image : 2
		image-box : 8
		spacer : 4
		template : 2
		text-editor : 6

== Log ==
	
Log: showing 20 of 372020-08-26 12:59:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-26 12:59:53 [info] elementor::elementor_updater Started 
2020-08-26 12:59:53 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-26 12:59:53 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-26 12:59:53 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-26 12:59:54 [notice] General Settings already exist. nothing to do. 
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-26 12:59:54 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-26 12:59:54 [notice] System colors already exist. nothing to do. 
2020-08-26 12:59:54 [notice] Custom colors already exist. nothing to do. 
2020-08-26 12:59:54 [notice] System typography already exist. nothing to do. 
2020-08-26 12:59:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-26 12:59:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-26 13:02:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]

PHP: showing 3 of 3PHP: 2020-08-13 10:28:32 [error X 1][/home/wirthsan/www/dev.360impact.ch/wp-content/plugins/elementor-pro/license/updater.php::150] Uncaught Error: Cannot use object of type WP_Error as array in /home/wirthsan/www/dev.360impact.ch/wp-content/plugins/elementor-pro/license/updater.php:150
Stack trace:
#0 /home/wirthsan/www/dev.360impact.ch/wp-includes/class-wp-hook.php(287): ElementorPro\License\Updater->plugins_api_filter(false, 'plugin_informat...', Object(stdClass))
#1 /home/wirthsan/www/dev.360impact.ch/wp-includes/plugin.php(206): WP_Hook->apply_filters(false, Array)
#2 /home/wirthsan/www/dev.360impact.ch/wp-admin/includes/plugin-install.php(150): apply_filters('plugins_api', false, 'plugin_informat...', Object(stdClass))
#3 /home/wirthsan/www/dev.360impact.ch/wp-content/plugins/wordfence/lib/wfScanEngine.php(1591): plugins_api('plugin_informat...', Object(stdClass))
#4 /home/wirthsan/www/dev.360impact.ch/wp-content/plugins/wordfence/lib/wfScanEngine.php(391): wfScanEngine->scan_oldVersions_main()
#5 /home/wirthsan/www/dev.360impact.ch/wp-content/plugins/wordfence/lib/wfScanEngine.php(192): wfScanEngine->doScan()
#6 /home/wirthsan/www/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-26 13:22:16 [notice X 3][/home/wirthsan/www/dev.360impact.ch/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-26 13:22:28 [notice X 4][/home/wirthsan/www/dev.360impact.ch/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2020-08-26 11:27:15 [error X 10][https://dev.360impact.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:469677] this.container is undefined 
JS: 2020-08-26 11:28:41 [error X 5][https://dev.360impact.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:314178] $e.routes.getHistory(...).reverse()[0] is undefined 

				
</details>

**Comment by mcrowell** [comment]
+1 Same issue here in Elementor 3.0.1

**Comment by zeinnicholas** [comment]
The link is rendering fine in your screenshot. Your issue is with the link style inherited from Hello Elementor? Or are you saying that you've configured a different color for links using the new Global settings for Typography?

**Comment by slwirth** [comment]
Thanks for your help.

That's actually possible, as I changed to Hello theme with the update. I did the same on another site and had no issue.
Yet, I can't find where I could get rid of the Elementor pink.

In Elementor, the links are set to black (normal and hover).
![image](https://user-images.githubusercontent.com/40966578/91326141-470f1b00-e7c4-11ea-9c20-befc2e221e6c.png)

**Comment by zeinnicholas** [comment]
> In Elementor, the links are set to black (normal and hover).

@slwirth Try regenerating the CSS in your Dashboard > Elementor > Tools.

**Comment by slwirth** [comment]
I have already done that several times. 

I have specific CSS for my underlined links. 

Sandra

**Comment by zeinnicholas** [comment]
@slwirth Sorry, I can't reproduce your issue. 

Global Colors are working fine for me, especially with the Hello theme pink link color. Are you sure this isn't cache related?

**Comment by slwirth** [comment]
It is not cache related IMO. I use FF and cleared it. Same happens in private window and Chrome. No caching plugin. No CDN. 

When you say that you can’t reproduce the error, what do you mean exactly?

Sandra

**Comment by zeinnicholas** [comment]
@slwirth It means that I tried to do the same thing as you, but instead of still seeing the pink color I could see the color I selected.

I just tested this in a staging environment with Elementor 3.0.2 and Elementor Pro 3.0.1 using Hello Elementor (latest).

**Comment by slwirth** [comment]
Thanks for explaining. 

Initially the site was built with Theme X, Pro version. Then I moved to Elementor with WPML and Astra free, before installing Hello. 

Tomorrow, I can try to clean the transient. I am not à développer, so I am not sure whether it can help. 

Sandra

**Comment by zeinnicholas** [comment]
@slwirth I would recommend you to do a basic troubleshooting, maybe this is being caused by a conflict between plugins.

These guides will help:

https://docs.elementor.com/article/189-having-problems-using-elementor-start-here

https://docs.elementor.com/article/204-my-changes-do-not-appear-online

**Comment by slwirth** [comment]
Thanks again Nicholas.
The issue is still there with only both Elementor plugins active (3.0.2 & 3.0.0). Seems to be an Elementor issue.
Still, it is my own website and I have a working version running fine.
Therefore I will wait for a couple of updates before going through the trouble of these procedures.
If it doesn't get resolve by itself, I will of course do so.
