### ISSUE TITLE
Redundant code in widgets having image

### ISSUE THREAD

**Issue by ibndawood** [elementor/elementor#12268]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Widgets like `image_box`, `image` have code like this:

https://github.com/elementor/elementor/blob/master/includes/widgets/image-box.php#L549-L555

The above code adds attributes to the `image` but it is not used in this line:

https://github.com/elementor/elementor/blob/master/includes/widgets/image-box.php#L557

This makes lines 549-555 redundant. The lines should either be removed or extend the `get_attachment_image_html` to accept image attributes as a parameter

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rami-elementor** [comment]
@ibndawood 

What are you trying to solve here? what code is not in use?

**Comment by ibndawood** [comment]
@rami-elementor 

The code has been updated. However the issue is the same. Please refer to lines: 
https://github.com/elementor/elementor/blob/master/includes/widgets/image-box.php#L565-L571

![image](https://user-images.githubusercontent.com/179533/157187083-3e15194e-c5f6-403e-a179-b9aeed349be8.png)

The above code adds attributes to `image` key but the key is not used because the image tag is generated from `get_attachment_image_html` which does not use the `image` key to render attributes. The `get_attachment_image_html` method has its own attributes generation logic and hence the lines 565-571 are redundant and not of any use.
