### ISSUE TITLE
[Bug] Many issues with the browser console after upgrading to v3

### ISSUE THREAD

**Issue by miyanialkesh7** [elementor/elementor#12273]
1. Failed to set referrer policy: The value '' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', 'same-origin', 'strict-origin', 'strict-origin-when-cross-origin', or 'unsafe-url'. The referrer policy has been left unchanged.

2. react_devtools_backend.js:2273 TypeError: Cannot read property 'model' of undefined

3. editor.min.js?ver=3.0.2:2 Uncaught (in promise) TypeError: Cannot read property 'model' of undefined

4. frontend-modules.min.js:2 Uncaught TypeError: Cannot read property 'model' of undefined

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by miyanialkesh7** [comment]
Hello @shilo-ey,

#2, 3 & 4 are getting after upgrading elementor from 2.9.14 to v3.0.2 free version.

Theme: Astra

Getting issues while editing exist widgets that I used during the version last one 2.x.x
