### ISSUE TITLE
Content is different from what I see in Elementor Editor

### ISSUE THREAD

**Issue by DenisFlorin** [elementor/elementor#12271]
Hello, 

I have a little problem. 

The content displayed on the page is different from what I see in Elementor Editor.

See images below:

![Selection_555](https://user-images.githubusercontent.com/38504865/91344690-f2c96280-e7e6-11ea-8d2c-4821cc725c37.png)

![Selection_554](https://user-images.githubusercontent.com/38504865/91344698-f78e1680-e7e6-11ea-9068-06a0982557fb.png)

Any ideas?

**Comment by khammileon** [comment]
Hi, I have the same problem here 😅 The V3 is cool but there are a lot of issues...

**Comment by portrayaloflife** [comment]
looks like a cache issue. Did you try clearing your cache and browser cookies as well?

**Comment by DenisFlorin** [comment]
Hi,

Yes, I cleared the cache. I tried to visit my website in other browsers and I checked on my phone, the content is not that one I expect.

**Comment by wwdes** [comment]
This looks to be related to #12249

**Comment by shilo-ey** [comment]
I merged this issue with #12249, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
