### ISSUE TITLE
Variable Width for Image Carousel

### ISSUE THREAD

**Issue by kim-snaptech** [elementor/elementor#12276]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As a photographer, I need to be able to display images of different orientations and crop sizes (square, different ratio rectangles, etc) in an image carousel so that the images have the same height however might have different widths - and it to look visually appealing. Currently, it has very unattractive white space around the images when they are a different orientation to the image next to it.

**Describe the solution you'd like**
An option on the image carousel or media carousel to have equal height and variable widths, so then when the carousel is displayed all images are the same height, scaled width depending on orientation. then the gap between each image would be equal spacing.

**Describe alternatives you've considered**
I've been trying different plugins, however, most don't actually get this work properly. admittedly I haven't yet paid for a plugin - I really would like to know it works before paying. I have done a lot of research, and it seems something that is wanted - but very minimal options available. I believe there are javascript options - but this is a bit beyond my knowledge.

**Additional context**
This would a major advantage for photographers and other image based businesses.

**Comment by fabianenzensperger** [comment]
+1

**Comment by mauricev** [comment]
+1

**Comment by VL375** [comment]
Hey, I've had a similar issue an found this very simple solution with a short CSS code: https://elementorcodes.com/elementor-justified-image-gallery-carousel/

Just read the article and watch the video and follow the steps. Worked fine for me, now horizontal and vertical images in the carousel are all aligned at the same height. If you need help with this, let me now.

**Comment by DorShahar** [comment]
Thank @VL375 for your help here.
Closing the issue.

**Comment by zovatrop** [comment]
> Hey, I've had a similar issue an found this very simple solution with a short CSS code: https://elementorcodes.com/elementor-justified-image-gallery-carousel/
> 
> Just read the article and watch the video and follow the steps. Worked fine for me, now horizontal and vertical images in the carousel are all aligned at the same height. If you need help with this, let me now.

Link no longer works
