### ISSUE TITLE
License activation and updating problem 

### ISSUE THREAD

**Issue by dibeja** [elementor/elementor#12284]
I downloaded the Elementor Pro plugin from my account page. The version of the file in the filename is 2.10.3.
I Installed it and activated it. When Trying to update the plugin to 3.0.2 the site give me this error: An error occurred while updating Elementor Pro: Download failed. Unauthorized

I followed the step in this article: https://docs.elementor.com/article/163-update-failed

Nothing worked.

I tried to rollback to a previous pro version but when I go in the Tools menu the version listed in the select box is 3.0.1 I tried then to roll back to 2.9.5 but then this error happened: Your license has not been activated for this domain, please activate it first.

I double checked in my account on Elementor and the site is currently listed among the activated ones.

Same thing happened on another site where I installed Elementor Pro form the plackage downloaded under My Account on 27 of august 2020

Something strange is happening, could you please help?

UPDATED: I tried installing a 2.9.3 zip package I have already downloaded. Installation went fine. Then it was propted to me to update to 2.10.3. THis update whent fine. Then it was prompetd me to update to 3.0.1 and this update failed as the one above: An error occurred while updating Elementor Pro: Download failed. Unauthorized

**Comment by shilo-ey** [comment]
Thanks! this issue has been resolved.

Try updating and it should work fine now.
