### ISSUE TITLE
Elementor 3.0 does not allow editing pages

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#12288]
Basic operations stopped working after the 3.0 update. 
And write it off as incompatibility with other plugins will not work: 
- Take the base theme Twenty Twenty and install only one Elementor plugin from the WordPress repository. 
- Creating a page and adding a new section to it. 
- Add the Text and Spacer widgets to the column, and set the background color for the row and column. 
- Save the page and go to Frontend.
- Everything is OK.
- But when you edit this page, the same operations no longer work - styles are not regenerated.

An illustration of my actions - on the video: https://www.screencast.com/t/tpRCi9nj6kYb

And these are elementary operations!

This update also ignored the global settings on the running site: the parameters 'content_width', 'space_between_widgets' and others simply assumed their default values.

**Comment by latheeshvmv** [comment]
I had the same problems since this version go-to tools and click regenerate CSS.
But strangely I had to do this every time! I have website up running on the AWS . Strange

**Comment by arielk** [comment]
How is CSS printing method defined, Internal or external? you can find it under Elementor > Settings > Advanced > CSS Print Method

Anyway please try to update to the latest version 3.0.3 and let me know if it fixes this issue.

**Comment by VadymPogorelov** [comment]
CSS Print Method has the value "Internal Embedding". After upgrading to 3.0.3 everything worked. Thanks.
