### ISSUE TITLE
Modifying time format in forms

### ISSUE THREAD

**Issue by Migueealejandro** [elementor/elementor#12295]
Good morning.

I just talked with support and they asked me to post my issue here.

Two weeks ago, I needed to change the date format in the forms on a client's website. Because the company is US-based, they needed to show the date as mm/dd/yyyy and not dd/mm/yyyy, which is Elementor's default.

I accomplished to change it with the outstanding help of the community here, something I appreciate very much.

Fast-forward a week, the client and I noticed something else in the form. In the time selector in the form, we see the time in 24-hour format. Then, when you click to modify, you have a little tooltip selector that shows you the time in 12-hour format. 

I don't know if I can include an outbound link. Please, let me know and I'll share it so you can see the form yourselves.

Now, it's odd that the same form shows you the time in two different formats simultaneously. Besides, the client, being based in the US, cannot show the time in 24-hour format to its customers. He needs the selector in a 12-hour format.

Elementor support told me that, just like modifying the date format as I already did, this requires custom code to change.

I'm no developer and don't know PHP to make such changes on my own. This is the very last modification needed on the website to be delivered, so any help you could provide will be greatly appreciated.

Thank you very much.

**Comment by DorShahar** [comment]
Hi @Migueealejandro 
Thanks for reaching out.
We are open source for the reason that if you need to change some code - you will be able to do it. Please understand that we cannot do it for you.
With that being said, you can use our [Experts](https://experts.elementor.com/) platform to find a developer that will do it for you. 

All the best.
