### ISSUE TITLE
Elementor updated version 3.0.3 is buggy

### ISSUE THREAD

**Issue by log-out** [elementor/elementor#12294]
I just updated the elementor version to 3.0 and now I can see some bugs. when i try to swap the column it duplicates another one and when I try to delete the row it just deletes the column inside. Is this a bug or just an update with new features? please see attached video
https://www.loom.com/share/56ecd023f161499cb71e58b0e0d8ecab

**Comment by fabianenzensperger** [comment]
Nobody can do anything with so little information. I absolutely cannot find the same problem!

**Comment by log-out** [comment]
Ok sorry, I guess I figured it out. I am using the Jupiter X theme it seems like their designed templates are not working anymore with elementor. All the other themes and their templates are working fine.

**Comment by fabianenzensperger** [comment]
> Ok sorry, I guess I figured it out. I am using the Jupiter X theme it seems like their designed templates are not working anymore with elementor. All the other themes and their templates are working fine.

Yes, you have to wait until your theme is 3.0 compatible. The theme also uses some third party plugins, right? That will cause the problems. Roll back the update.

**Comment by log-out** [comment]
Yes, I just rolled it back to 2.9, and it's working fine. thank you for your help

**Comment by fabianenzensperger** [comment]
> Yes, I just rolled it back to 2.9, and it's working fine. thank you for your help

With pleasure. You are welcome to close the issue. It's best to write to the theme support!

**Comment by rodolphebertozzo** [comment]
Hi @log-out, this is indeed a bug, follow the problem here : https://github.com/elementor/elementor/issues/12242

**Comment by log-out** [comment]
Just tested elementor updated version with different premium themes but the plugin is no more working with all of them.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12242, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

If the issue consists - please reopen a new issue with system info.
