### ISSUE TITLE
Please add support SWUP transition

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#12306]
How can I do that? Everything is very simple:

1) Add support for swap, and in the site settings add a check mark to enable swap transitions.
2) in the theme constructor, in addition to the template name, add the template ID, in this way we will be able to link transitions from one page template to another
3) and finally, when saving a template or a page, add conditions for the transition between templates

this will take sites made with elementor to a completely new level

**Comment by DorShahar** [comment]
Hi @promocot 
Thank you for your input.
This is not our main focus for the moment. If more requests for that will rise, we will consider adding it to the Editor.

Thank you for your understanding.

**Comment by promocot** [comment]
you should make a system of polls about the functionality, find out what users want

**Comment by DorShahar** [comment]
For transparency, the Data Product and UX departments are working on this project.
