### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Elementor\\Modules\\Library\\Documents\\Not_Supported::add_repeater_row()

### ISSUE THREAD

**Issue by madeITBelgium** [elementor/elementor#12302]
After upgrading to v3.0.3 I get this error:

PHP Fatal error:  Uncaught Error: Call to undefined method Elementor\\Modules\\Library\\Documents\\Not_Supported::add_repeater_row() in /home/user/web/xxx.com/public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php:743\nStack trace:\n#0 /home/user/web/xxx.com/public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php(883): Elementor\\Core\\Upgrade\\Upgrades::Elementor\\Core\\Upgrade\\{closure}('23310')\n#1 /home/user/web/xxx.com/public_html/wp-content/plugins/elementor/core/upgrade/upgrades.php(751): Elementor\\Core\\Upgrade\\Upgrades::move_settings_to_kit(Object(Closure), Object(Elementor\\Core\\Upgrade\\Updater), true)\n#2 [internal function]: Elementor\\Core\\Upgrade\\Upgrades::_v_3_0_0_move_default_colors_to_kit(Object(Elementor\\Core\\Upgrade\\Updater))\n#3 /home/user/web/xxx.com/public_html/wp-content/plugins/elementor/core/base/background-task.php(277): call_user_func(Array, Object(Elementor\\Core\\Upgrade\\Updater))\n#4 /home/user/web/xxx.com/public_html/wp-cont in /home/user/web/xxx.com/public_html/wp-content/plugins/elementor/core/upgrade/upgrades.phpon line 743, referer: https://www.xxx.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

**Comment by arielk** [comment]
It seems like you have a migration issue with the new version, 

Please go to WP Admin > Elementor > Tools > Version Control > click on **Rerun Update Script**

Let me know if it solves the issue.

**Comment by madeITBelgium** [comment]
When I do that I get the same error as in my original issue. I think it's the same as #12305.

**Comment by arielk** [comment]
Ok, let's do something more radical:

1. Go to http://YOUR_DOMAIN.COM/wp-admin/edit.php?post_type=elementor_library
2. Find "Default Kit" template > Trash > Delete Permanently
3. Go to Version Control > Rollback > Downgrade to v2.9.14
4. Update again to v3.0.4
5. Version control > click on Rerun Update Script

LMK

**Comment by madeITBelgium** [comment]
This seems to fix it.

**Comment by Rethar-yt** [comment]
this worked. thank you. _**Please go to WP Admin > Elementor > Tools > Version Control > click on Rerun Update Script**_
