### ISSUE TITLE
Remove autogenerated screenshots of templates from Media Library

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12300]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### **Problem**
After updating to 3.0, my media library is full of autogenerated files of screens for the new theme builder. I like to keep my media library tidy for my clients and now it's spammed with these files. 

It makes no sense to throw these files into the media library. Media Library is for files we uploaded and want to use on our website, not for plugin system files.

I'm not even sure if this is a feature or a bug, but I'm seeing these files in my Media Library.

### **Solution**

These files are generated by Elementor for Elementor's functionality and should therefore be stored in some other folder within Elementor. They should not be dumped into the Media Library. 

Lots of plugins use images in their interface, but they keep them in some private folder. I've never seen a plugin that would spam my media library.

**Comment by MichaelDarko** [comment]
![Media library](https://user-images.githubusercontent.com/36289156/91554436-69717780-e92f-11ea-90dd-5a528a6cf14f.png)

This is how my Media Library looks like now. Surely, these autogenerated files should not be there. The Media Library is for files users want to use, it shouldn't be a place for storing plugin files.

**Comment by arielk** [comment]
This issue has been resolved in Elementor Pro v3.0.1

Feel free to update

Thanks!

**Comment by klitsios** [comment]
Still having the same problem with both Elementor v3.17.3 and Elementor Pro v3.17.1 installed
I really don't know how this can be marked as solved.

**Comment by klitsios** [comment]
Got tired of waiting for a fix, so I switched all my projects to Bricks and canceled my Elementor Pro subscription.
