### ISSUE TITLE
Error in editor.min.js after each update

### ISSUE THREAD

**Issue by brigosx** [elementor/elementor#12313]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

Every time I update Elementor there is always an editor.min.js error reported in the console, preventing the editing of existing gallery items like the "Filterable Gallery" one. The problem occurs after clicking on an item and try to edit the contents of the item. I found an undefined error once in the rearrangeButtons function and another one in the place where the following snippet is about to be executed:
**tinymce.get(this.id).fire("hide")**
It seems that the tinymce library returns undefined for some Elementor widgets.
## Steps to reproduce

Just click on an existing "Filterable Gallery" widget in order to edit its contents.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
PHP 7.2 or 7.4, WordPress 5.5, active theme Mesmerize and Highlight.
</details>

**Comment by alan345** [comment]
same here with `editor.min.js`

![image](https://user-images.githubusercontent.com/15246526/91644477-2bd52300-e9f1-11ea-87e7-b30a33595c93.png)

```
editor.min.js?ver=3.0.3:2 Uncaught TypeError: Cannot read property 'urls' of undefined
    at Function.m.initGroups (editor.min.js?ver=3.0.3:2)
    at Function.m.getGroups (editor.min.js?ver=3.0.3:2)
    at Function.m.addItem (editor.min.js?ver=3.0.3:2)
    at child.addPanelMenuItem (editor.min.js?ver=3.0.3:2)
    at child.e.each.r.<computed> [as addPanelMenuItem] (common-modules.min.js?ver=3.0.3:2)
    at child.onInit (editor.min.js?ver=3.0.3:2)
    at child.e.each.r.<computed> [as onInit] (common-modules.min.js?ver=3.0.3:2)
    at child.Module.trigger (common-modules.min.js?ver=3.0.3:2)
    at child.e.each.r.<computed> [as trigger] (common-modules.min.js?ver=3.0.3:2)
    at init (common-modules.min.js?ver=3.0.3:2)
```

**Comment by shilo-ey** [comment]
Do you refer to Elementor's gallery? or to a 3rd party one?

Please attach System info

**Comment by brigosx** [comment]
Hi shilo-ey,

Actually the problem appears to the Filterable Gallery widget of the Essential Addons for Elementor. However, the library that crashes is the editor.min.js of the Elementor. I get errors from 3 places inside the library. One I can recall is from the reArrangeButtons function. I just put a simple "if" just before the "i=t.toolbar1.split(',')" assignment ( editorBasicToolbarButtons = editorProps.toolbar1.split(',') in editor.js) in order to check that "t" (editorProps) has been assigned appropriately from the "tinyMCEPreInit.mceInit[this.editorID]". The other place is where you are trying to hide an element with the "fire" ID. The 3rd error although reported in the console does not affect the editing of widget from the Elementor property inspector. From my perspective it looks that for some elements the "tinymce" object returns undefined and the editor.min.js does not have the appropriate check in order to avoid it. I have the free version of the Elementor but I don't think that this is the matter.

**Comment by brigosx** [comment]
Hi @shilo-ey , 

Below is the system info as it appears through the Elementor plugin corresponding option:

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.39 (Unix) OpenSSL/1.0.2k-fips
	MySQL version: MariaDB Server v5.6.43-84.3
	PHP Version: 7.2.23
	PHP Max Input Vars: 1000
	PHP Max Post Size: 12M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://everfounders.com
	Home URL: https://everfounders.com
	WP Multisite: No
	Max Upload Size: 12 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/Athens
	Debug Mode: Inactive

== Theme ==
	Name: Highlight
	Version: 1.0.15
	Author: ExtendThemes
	Child Theme: Yes
	Parent Theme Name: Mesmerize
	Parent Theme Version: 1.6.96
	Parent Theme Author: Horea Radu

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.7.7
		Author: Frank Goossens (futtta)

	Elementor
		Version: 3.0.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 4.2.3
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 7.12.2
		Author: MonsterInsights

	Insert Headers and Footers
		Version: 1.4.6
		Author: WPBeginner

	Mesmerize Companion
		Version: 1.6.112
		Author: Horea Radu

	Pods - Custom Content Types and Fields
		Version: 2.7.22
		Author: Pods Framework Team

	Premium Addons for Elementor
		Version: 3.21.2
		Author: Leap13

	Pretty Links
		Version: 3.1.1
		Author: Pretty Links

	Really Simple SSL
		Version: 3.3.5
		Author: Really Simple Plugins

	Recent Posts Widget Extended
		Version: 0.9.9.7
		Author: Satrya

	Use Any Font
		Version: 5.11.3
		Author: Dnesscarkey

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WPForms
		Version: 1.6.2.3
		Author: WPForms

	WP Mail SMTP
		Version: 2.3.1
		Author: WPForms

	Yoast SEO
		Version: 14.9
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	section : 15
		eael-creative-button : 2
		eael-filterable-gallery : 1
		heading : 3
		image : 17
		premium-addon-banner : 15
		spacer : 2
		star-rating : 2
		text-editor : 5
	wp-post : 1
		text-editor : 1
	wp-page : 4
		eael-filterable-gallery : 2
		heading : 5
		menu-anchor : 2
		premium-addon-person : 1
		premium-carousel-widget : 1
		spacer : 7
		text-editor : 2
		wp-widget-wpforms-widget : 1


== Log ==
	
JS: showing 20 of 28JS: 2020-07-07 17:03:59 [error X 12][http://everfounders.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.9.13:2:47166] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `project_thumb_image` value. Expected array or object.',
)]
JS: 2020-07-07 21:42:19 [error X 238][http://everfounders.com/wp-includes/js/tinymce/wp-tinymce.js?ver=4960-20190918:3:352649] Cannot read property \'onpageload\' of undefined 
JS: 2020-07-08 08:05:26 [error X 20][http://everfounders.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.13:31:144027] Cannot read property \'fire\' of null 
JS: 2020-07-09 20:06:05 [error X 249][http://everfounders.com/wp-includes/js/tinymce/wp-tinymce.js?ver=4960-20190918:3:352651] Cannot read property \'length\' of undefined 
JS: 2020-07-14 18:12:02 [error X 3][http://everfounders.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.9.13:2:47166] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `portfolio_thumb_image` value. Expected array or object.',
)]
JS: 2020-07-14 18:12:02 [error X 3][http://everfounders.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.9.13:2:47166] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `portfolio_full_image` value. Expected array or object.',
)]
JS: 2020-07-14 19:35:53 [error X 1][http://everfounders.com/wp-content/themes/mesmerize/assets/js/theme.bundle.min.js?ver=1.0.15:1:26101] Cannot read property \'toLowerCase\' of undefined 
JS: 2020-07-14 21:11:31 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view20724\") has already been destroyed and cannot be used. 
JS: 2020-07-14 21:11:31 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view20528\") has already been destroyed and cannot be used. 
JS: 2020-07-14 21:11:50 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view22266\") has already been destroyed and cannot be used. 
JS: 2020-07-14 21:11:50 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view22394\") has already been destroyed and cannot be used. 
JS: 2020-07-15 20:59:26 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.13:31:153604] Cannot read property \'html\' of undefined 
JS: 2020-07-27 20:54:35 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view21282\") has already been destroyed and cannot be used. 
JS: 2020-07-27 20:54:35 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view21492\") has already been destroyed and cannot be used. 
JS: 2020-07-27 20:54:35 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view8393\") has already been destroyed and cannot be used. 
JS: 2020-07-27 20:54:35 [error X 1][http://everfounders.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view8483\") has already been destroyed and cannot be used. 
JS: 2020-08-07 16:26:27 [error X 2][https://everfounders.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.9.14:2:59543] Cannot read property \'attributes\' of undefined 
JS: 2020-08-11 21:28:33 [error X 3][https://everfounders.com/wp-admin/post.php?post=928&action=elementor:2:20] Illegal constructor 
JS: 2020-08-15 11:25:37 [error X 1][https://everfounders.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.14:2:195519] Cannot read property \'map\' of undefined 
JS: 2020-09-01 19:22:00 [error X 1][https://everfounders.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:228236] ElementorConfig is not defined 

PHP: showing 2 of 2PHP: 2020-07-13 22:18:20 [error X 2][/home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::2003] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1041 and defined in /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php:2003
Stack trace:
#0 /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1041): Elementor\Controls_Stack->sanitize_settings('a:1:{s:18:"eael...')
#1 /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1810): Elementor\Controls_Stack->get_data('settings')
#2 /home/thepdac/public_html/wp-content/plugins/elementor/core/base/base-object.php(132): Elementor\Controls_Stack->get_init_settings()
#3 /home/thepdac/public_html/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/control [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-13 22:20:40 [error X 1][/home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::2003] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1041 and defined in /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php:2003
Stack trace:
#0 /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1041): Elementor\Controls_Stack->sanitize_settings('a:2:{s:18:"eael...')
#1 /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1810): Elementor\Controls_Stack->get_data('settings')
#2 /home/thepdac/public_html/wp-content/plugins/elementor/core/base/base-object.php(132): Elementor\Controls_Stack->get_init_settings()
#3 /home/thepdac/public_html/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /home/thepdac/public_html/wp-content/plugins/elementor/includes/base/control [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 13 of 132020-07-26 14:38:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-08-27 22:06:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-27 22:06:58 [info] elementor::elementor_updater Started 
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-27 22:06:58 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-27 22:06:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-27 22:07:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]

**Comment by brigosx** [comment]
Hi to all. Without any offence I would like to propose a fast work around. At the "editor.min.js" file find the "toolbar1" keyword and make the following modification:

var t=tinyMCEPreInit.mceInit[this.editorID]**_;if(t==undefined)return;_**var o=t.toolbar1.split(",")

This way any undefined instance of the gallery items widget will be filtered out. Then the script will become responsive again and the gallery widget items will be editable again.
