### ISSUE TITLE
HTML Tags (example: <br>) Show in SOME Post / Product Title Displays

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#12318]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I use html line breaks in my product title to effectively display product titles. In some parts of my site (some pages), the html <br> tags are showing in the product title display. Everything looks good on the product archive & the woocommerce checkout page (see screenshots w/ big green checkmarks 😊). However, when viewing the product single, the cart, and the woocommerce thank you page, the `<br> ` tags are showing in the product title. I have included also 3 screenshots of the problem areas: product single, cart, and thank you page (seen after checkout). This behavior of showing html tags in the title is not only undesirable, it is inconsistent. I am using Elementor, Elementor Pro, and the Hello theme.

I would like to see all html tags removed from display in every title — be it post, product, or any other custom post type.

![product-edit-admin-area-backend](https://user-images.githubusercontent.com/1435355/91649389-96ae4a80-ea41-11ea-9993-92fa5335ec76.png)
![Shop-Archive-Looks-Good](https://user-images.githubusercontent.com/1435355/91649395-a037b280-ea41-11ea-935d-c02d8bdf30fd.png)
![Product-Single-Title](https://user-images.githubusercontent.com/1435355/91649396-a62d9380-ea41-11ea-8cf3-32af05998559.png)
![Cart-Product-Title](https://user-images.githubusercontent.com/1435355/91649399-b0e82880-ea41-11ea-89a3-4d5f01dbc42d.png)
![checkout-page](https://user-images.githubusercontent.com/1435355/91649400-b6de0980-ea41-11ea-9437-bba29cadd52c.png)
![Download-Product-Link-Thank-You](https://user-images.githubusercontent.com/1435355/91649402-bc3b5400-ea41-11ea-9cce-91a8a0c25ced.png)

**Comment by shilo-ey** [comment]
Hey @TomRaraAvis 

When deactivating Elementor and Elementor Pro this issue still occurs. it's because of security reasons - I assume WC doesn't allow for running unfiltered HTML inside its fields.

We follow their protocols for consistent behavior.

Thanks again!
