### ISSUE TITLE
⛔ 🚀 Feature Request: Show Variable Product Images when a Product Variation is selected in the Products widget

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#12319]
Get the ability to dynamically change the image from a variable product, at the moment there is only a product or tags ... if there was a possibility of a variable brand it would help diversify the design, which I mean ...

I would like to set a simple product image (say, a photo of the door between the room on a white background) to be displayed in the product grid, but as a user clicks on the product, I would like the picture to change from switching product variations ... yes, I know that there is an image of the product for woocommerce, but I do not want to set the usual square image but in the entire column size, it could be an image of this product (door) in the premises, and when choosing a variable product, the entire background would change, just imagine what opportunity opens up in the design by adding one dynamic field

**Comment by promocot** [comment]
also if you make a dynamic link from the product galleries this is a great option for booking or selling real estate when the image of the inerrier is not small but will be full screen just because we have set a dynamic link to the gallery, we can change the room viewing options ... in general, I ask 2 dynamic links (I don't think it's that difficult to add) but it can change the idea of the design

**Comment by TomRaraAvis** [comment]
This issue might be solved with a custom loop for archive display so that you could use any dynamic field?
If that is the case, a relevant thread you might want to follow is #4440
It's difficult to find similar issues in GitHub search when you don't know the proper terms to use. In this case, you should search for "custom loop" or "archive loop" or "post loop" or "custom archive" if want to customize a product archive grid or post archive grid — any content within an archive listing/grid.

**Comment by promocot** [comment]
you do not understand, I do not need a grid with goods, I need to change the background image of the sections

**Comment by promocot** [comment]
here is an example of which product pages can be created with the implementation of my idea

https://dribbble.com/shots/4702632-Purity?utm_source=pinterest&utm_campaign=pinterest_shot&utm_content=Purity&utm_medium=Social_Share

when you select another photo, the image is overlaid on the background and not just a small square, at the moment you can do this only for a regular product, without variations, so I ask you to add a dynamic link to images from product variations

**Comment by nicholaszein** [comment]
Hello @promocot,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
