### ISSUE TITLE
Update link to Wordpress Date Time Documentation

### ISSUE THREAD

**Issue by awakekat** [elementor/elementor#12312]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Wordpress had updated their documentation link for Formatting Date and Time from this address (https://codex.wordpress.org/Formatting_Date_and_Time) to this new address (https://wordpress.org/support/article/formatting-date-and-time/).

## Steps to reproduce

When you use the dynamic tags > Current Date Time, click on the wrench icon, choose Date Format as Custom - the blue link at the bottom: "Documentation on date and time formatting". When you click the link you get a page on Wordpress that tells you they have moved the documentation to https://wordpress.org/support/article/formatting-date-and-time/ 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Clicking a link inside of Elementor - Elementor 3.0.3 and Elementor 3.0.1

**Comment by arielk** [comment]
Thanks! we will update it in the next version

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.4

Feel free to update

Thanks!

**Comment by awakekat** [comment]
Sorry but this was not fixed - it still goes to the old link: https://codex.wordpress.org/Formatting_Date_and_Time

**Comment by shilo-ey** [comment]
This specific one was updated in Pro 3.0.2

Please update and see the change

Thanks

**Comment by awakekat** [comment]
I now see the changes in 3.0.5 to the link, thanks
