### ISSUE TITLE
[FEATURE REQUEST] Toggle Menu Editor & Toggle Responsiveness Elements (On/Off)

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12316]
Hi guys.

I think this would be great for improve the workflow when creating websites.

1. **Toggle Option for Left Menu Editor.** Having more 3rd Party Plugins a quick option for Toggle all Minimized or Expand option will be great to have. In the image you have the "Dropdown" icon, but you need to go one by one closing this... If you can add a Expand All/Colapse All or something like that will be amazing.

![image](https://user-images.githubusercontent.com/68023943/91646462-ee3ebd00-ea25-11ea-864b-101796b9827b.png)

2. When you add "Visibility Options" to an Element, this is showing in GREY. it would be very nice to have an Option to "Toggle On/Off" for have a complete view of the site without the "grey" sections or elements hidden. As you can see here, i have this section with Visibility Options enabled and this really bother if need to work with this in the middle. I think this happens to many more.

![image](https://user-images.githubusercontent.com/68023943/91646493-1af2d480-ea26-11ea-8435-7ff82c34a581.png)

**Comment by maurocarreraok** [comment]
Hi @arielk any news on this? Thanks!!!

**Comment by maurocarreraok** [comment]
@DorShahar Thanks! :)

**Comment by maurocarreraok** [comment]
@shilo-ey

**Comment by travisodell** [comment]
> This feature has been added to Elementor v3.3.0
> 
> Feel free to update
> 
> Thanks!

Where is the option to use this feature? it drives me crazy. lol

**Comment by travisodell** [comment]
> > This feature has been added to Elementor v3.3.0
> > Feel free to update
> > Thanks!
> 
> Where is the option to use this feature? it drives me crazy. lol

Sorry I found it, perhaps a centralization of user preferences might be a good addition :P

**Comment by nilothiago** [comment]
> > > This feature has been added to Elementor v3.3.0
> > > Feel free to update
> > > Thanks!
> > 
> > 
> > Where is the option to use this feature? it drives me crazy. lol
> 
> Sorry I found it, perhaps a centralization of user preferences might be a good addition :P

Finally, where it is? :)

**Comment by maurocarreraok** [comment]
@travisodell where is this? thanks! did u find it?
