### ISSUE TITLE
Breakpoints not working

### ISSUE THREAD

**Issue by rvisima** [elementor/elementor#12320]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The new breakpoints interface (at Site Settings > Layout > Breakpoints) does absolutely nothing when the numbers are changed from the default. Breakpoints are locked at default values of 768 and 1025 no matter what is entered in the fields.

I rolled back to Elementor 2.9.14 and Pro 2.10.3 and breakpoints functioned correctly again.

## Steps to reproduce

Type numbers into breakpoints fields. Regenerate CSS. Refresh page and watch as the breakpoints have no impact at all. Breakpoints are locked at default values of 768 and 1025.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Tested with two sites on Elementor 3.0.3 and Elementor Pro 3.0.1. Tested with WordPress 5.4.2 and WordPress 5.5. Tested with two different hosting environments (local running PHP 7.4.1 and Cloudways running PHP 7.4). Tested with Hello theme and Twenty Twenty theme.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.47-87.0
	PHP Version: 7.4.7
	PHP Max Input Vars: 2500
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://wordpress-418647-1456796.cloudwaysapps.com
	Home URL: https://wordpress-418647-1456796.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Breeze
		Version: 1.1.7
		Author: Cloudways

	Business Reviews Bundle
		Version: 1.6
		Author: RichPlugins <support@richplugins.com>

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.0.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.35
		Author: MalCare Security

	Media Library Assistant
		Version: 2.84
		Author: David Lingren

	The SEO Framework
		Version: 4.1.0
		Author: The SEO Framework Team

	The SEO Framework - Extension Manager
		Version: 2.4.0
		Author: The SEO Framework Team

	WP Mail SMTP
		Version: 2.3.1
		Author: WPForms

	Yoast Duplicate Post
		Version: 3.2.5
		Author: Enrico Battocchi & Team Yoast

== Elements Usage ==
	
	header : 1
		icon : 2
		image : 1
	page : 1
		heading : 1
	section : 2
		button : 2
		icon-box : 2
		image-box : 3
		text-editor : 2
	wp-post : 0
		animated-headline : 1
		button : 8
		divider : 6
		heading : 15
		icon-list : 1
		image : 1
		image-box : 13
		image-carousel : 2
		media-carousel : 3
		menu-anchor : 7
		shortcode : 3
		text-editor : 7

== Log ==
	
JS: showing 2 of 2JS: 2020-03-04 02:44:26 [error X 1][https://wordpress-418647-1456796.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.3:31:98977] Cannot read property \'message\' of null 
JS: 2020-08-29 21:48:03 [error X 15][https://wordpress-418647-1456796.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:470394] Cannot read property \'document\' of undefined 

Log: showing 20 of 372020-06-23 13:21:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '2.9.13',
)]
2020-06-29 19:26:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.2',
  'to' => '2.10.3',
)]
2020-07-21 22:58:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-08-25 20:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]
2020-08-25 20:01:41 [info] elementor::elementor_updater Started 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-25 20:01:41 [notice] System colors are disabled. nothing to do. 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 20:01:41 [notice] System typography is disabled. nothing to do. 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-25 20:01:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-26 23:06:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-26 23:07:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-27 18:08:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]

PHP: showing 3 of 3PHP: 2020-04-28 18:10:30 [error X 1][/home/418647.cloudwaysapps.com/mytjedrwpm/public_html/wp-content/plugins/elementor/includes/elements/section.php::1124] Out of memory (allocated 10485760) (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 18:03:53 [notice X 6][/home/418647.cloudwaysapps.com/mytjedrwpm/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 18:30:26 [notice X 1][/home/418647.cloudwaysapps.com/mytjedrwpm/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::154] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.6

Feel free to update

Thanks!

**Comment by CJKrets** [comment]
It may have been fixed, but it's not working now. Found this thread because of that fact. I change the values and it's not doing a thing.

**Comment by Stilian1** [comment]
Can someone reopen this issue? Custom breakpoints don't work for me. Can you Elementor retest this and see if it needs to be fixed again?

Elementor: 3.0.11
Elementor Pro: 3.0.5

**Comment by ekzig** [comment]
Also having a problem with custom breakpoints not affecting the Reverse Columns option like @Stilian1 mentioned, I'm on Elementor 3.0.11 & Elementor Pro 3.0.5. Hoping for a fix!

**Comment by GeorgeFlorian** [comment]
I don't use Reverse Columns and yet I cannot change the breakpoints. They default back to their original value.

**Comment by harleytans2020** [comment]
Hi has anyone resolved breakpoints yet in the latest patch? 3.0.14 Please do not close the thread when a fix has not been found 👎

**Comment by hapiscalin** [comment]
I don't know but I am facing this issue if my windows screen resolution is at 125%

**Comment by corne-aardig** [comment]
Still not fixed for me as well... Mobile breakpoint is 765 and tablet breakpoint is 1024 and not possible to change it.

**Comment by jamcmich** [comment]
I'm facing the same issue as others in this thread. Reverse columns do not follow custom breakpoint rules and will always trigger at default (1024px).

**Comment by saschakoeth** [comment]
Same here. Breakpoints unchangeable with Elementor PRO 3.2.1

**Comment by kxeilakos** [comment]
Any updates on this bug? 
I am using Elementor Version 3.2.3 and still Breakpoints do not take effect. It is stuck to the defaults 1024 for Tablet and 768 for Mobile.

**Comment by dazdazslk** [comment]
> Any updates on this bug? I am using Elementor Version 3.2.3 and still Breakpoints do not take effect. It is stuck to the defaults 1024 for Tablet and 768 for Mobile.

Same here, did you find a way ?

**Comment by dazdazslk** [comment]
> It may have been fixed, but it's not working now. Found this thread because of that fact. I change the values and it's not doing a thing.
> 
> Elementor Version: 3.0.9 Elementor Pro Version: Version 3.0.4
> 
> This is getting old.

Hi, did you find a solution ? I have the same problem

Thx !

**Comment by Litorian** [comment]
I have the same Problem i guess, i put some Elements on Hide-Mode for Tablet, but it still shows Elements that are literally just hidden for Tablet View in the Tabletview, i dont know what to do changing the breakpoints is not helping at the moment, is there a way to fix that?

**Comment by Shamwedge** [comment]
Add me to the list! I can change the breakpoints, but they do absolutely nothing. Version 3.4.8

**Comment by steven2983745** [comment]
Version 3.5.4 (3.5.2 Elementor Pro) breakpoints not working, any news on a fix?

**Comment by swilkiewicz** [comment]
Invalid styles at a resolution of 767px width is due to the incompatibility of the display scaling settings and the elementor. When we change the display scaling in your system screen settings to value 100%, 200% etc. Styles load correctly. However, when scaling is set up to values 125%, 150% and 175%, the "data-elementor-device-mode" class is set to "none" and the styles break.

**Comment by pbaddock** [comment]
+1 for a fix for this - I can't get them to work trying all kinds of solutions offered by various (switching loading method, disabled advanced breakpoints experiment, regenerating css, clearing cache, etc etc).  Just doesn't seem to work.

**Comment by swilkiewicz** [comment]
> +1 for a fix for this - I can't get them to work trying all kinds of solutions offered by various (switching loading method, disabled advanced breakpoints experiment, regenerating css, clearing cache, etc etc). Just doesn't seem to work.

change scaling on your graphics card -----> monitor scaling to 100% it will fix automaticly

**Comment by pbaddock** [comment]
> > +1 for a fix for this - I can't get them to work trying all kinds of solutions offered by various (switching loading method, disabled advanced breakpoints experiment, regenerating css, clearing cache, etc etc). Just doesn't seem to work.
> 
> change scaling on your graphics card -----> monitor scaling to 100% it will fix automaticly

Tried 'default for display' settings for my display (1920 x 1080) - no luck, tried scaled and manually selected resolution to match display default - no luck.

**Comment by KillStealth** [comment]
Elementor 3.6.5
Elementor pro 3.6.3

Breakpoints not working any news?

**Comment by Selah1337** [comment]
I added the Tablet Extra breakpoint and edited my page using that extra breakpoint, but didn't see any change in the front end after saving and clearing cache.

**Comment by bc1121** [comment]
I've got an Elementor Pro Flip Box that disappears at width 767. I'm assuming this is a related issue?

**Comment by mikeecho2** [comment]
> Add me to the list! I can change the breakpoints, but they do absolutely nothing. Version 3.4.8

+1 Same here, they do not stick. Changing column width has ZERO effects (except between the normal standard 3 breakpoints) Additional break points are VERY BROKEN

**Comment by EmilieDelleyDelisle** [comment]
Doesn't work for me either.
Elementor : 3.7.2
Elementor Pro : 37.3

I have a absolute element and on extra mobile breakpoint and I set my costum with at 175px and when I check on the console there is nothing set.
![Elementor _ Marc-Olivier Perron - Editor](https://user-images.githubusercontent.com/73126367/185927793-1b2d3bcc-4e34-45c0-add5-d650a497bb81.png)
![Marc-Olivier Perron – Lab Emilie - Front End](https://user-images.githubusercontent.com/73126367/185927816-2836b435-72cd-4ef3-b421-57e118a596c8.png)
.

**Comment by mikeecho2** [comment]
I think I have found a way that makes it work and stick
If you work and set the breakpoints, working from largest to smallest, then it seems to stick & work.
So I do Desktop first, then laptop... until mobile last. Works great!

**Comment by AmityTek** [comment]
My breakpoint aren't loading for mobile on my website : https://www.alanage.be/
Any idea why ....?

**Comment by NeffIsBack** [comment]
I have set a custom pixel width for my breakpoints, but they are not respected in the Navigation Menu -> Layout ->  Responsive. I guess this issue is still not resolved? Any chance this can be reopened if validated? Or am i missing something crucial here?
![image](https://github.com/user-attachments/assets/32eac3b8-b0bc-406e-b350-cd212ca55b69) ![image](https://github.com/user-attachments/assets/acf24764-20eb-4b2a-9c14-95a3bf1a6a80)

**Comment by phkoon** [comment]
Any updates to this issue?
