### ISSUE TITLE
Use Vanilla JS instead of jQuery at least on frontend

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#12330]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
jQuery is a heavy library and loading it on the frontend is unnecessary.

**Describe the solution you'd like**
Is there a way make Elementor jQuery free?
Using Vanilla JS instead of jQuery is suggested here:
https://core.trac.wordpress.org/ticket/37110#comment:110

**Describe alternatives you've considered**
Continue to support newer versions of jQuery, but the speed of the websites would not be as good as it will be.

**Comment by arielk** [comment]
It something that will take some time but we are absolutely going to this direction.

This is a bunch of tasks so right now I'm closing this issue but thanks for your feedback.
