### ISSUE TITLE
Global color does not save with JSON file

### ISSUE THREAD

**Issue by awakekat** [elementor/elementor#12340]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.
Elementor 3.0.4
Elementor Pro 3.0.1
Hello Theme

## Description

I set 2 colors as Global Colors for a gradient at the top of the page. I then saved the page as a template. I exported the json file. I then imported the json file in another site. The colors were not showing in the header - it was white.

I know that the global colors are represented by the BLUE GLOBE beside the color swatch. These were set when I exported the template the first time.

The second timeI exported the template, I went to the color swatched and clicked on the swatch, making the BLUE GLOBE turn GRAY.

I exported the template file a second time and imported it into the other site. The colors of the gradient did show up.

So what I can under stand from this is that the JSON files are not getting the Global color values. I have not looked at the JSON itself to see what is different.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

Server Environment |   |  
-- | -- | --
Operating System: | Darwin |  
Software: | nginx/1.16.0 |  
MySQL version: | MySQL Community Server - GPL v8.0.16 |  
PHP Version: | 7.4.1 |  
PHP Max Input Vars: | 4000 |  
PHP Max Post Size: | 1000M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</details>

**Comment by alexisnmorgan** [comment]
+1. For me, this happens when there are more than 4 global colors used. Any color defined outside the main 4, it will not transfer with the JSON. I have not tried this with gradients, though. Exporting the Global Font & Color settings as a kit is a much needed feature for me that I hope comes soon (https://github.com/elementor/elementor/issues/7115)

**Comment by Neptuneking** [comment]
+1

**Comment by ahmetsali** [comment]
+1 

I tried to export all Elementor Templates via WordPress > Tools > Export > My Templates and got a json, it also includes "Default Kit" with global fonts variable in it, then I imported this json file to another wp site, but Elementor doesn't get global colors from the imported "Default Kit" but it creates another "Default Kit 2" with the default global colors only. This is a really annoying issue and it prevents using Elementor for creating transferable desing systems.

@danielkatz and @KingYes please consider fixing this bug as a priority.

thanks.

**Comment by black-eye** [comment]
+1

**Comment by jessehall** [comment]
+1

**Comment by arielk** [comment]
Merge to https://github.com/elementor/elementor/issues/12340

**Comment by black-eye** [comment]
@shilo-ey 
> Merge to #12340

Catch 12340? You are closing this issue (no. 12340) in favour of the issue no. 12340 (which is the same issue, in case you didn't notice)?

I suppose it's a mistake and not done on purpose, but it kind of symbolizes the feeling I've been having lately: Elementor running in circles, trying to catch it's own tail... ;-)

**Comment by arielk** [comment]
Sorry, my mistake :(

We're working on an export/import solution for Elementor, so I'll just gather all the issues in this area to address it properly.

Thanks for your feedback!

**Comment by oooh-boi** [comment]
Wow, it's been 5 months, and one of the most important features still not patched/fixed. I just can't believe that the "Default Kit", a.k.a Site Settings can't be exported nor imported.

**Comment by VoidZA** [comment]
For anyone looking to do this sort of manually, here is how to do it (its pretty straight forward):
On the source site, find your default-kit post id, easiest place to find it is under your Elementor templates, on the right it will show the shortcode for each template with the id in it, something like: [elementor-template id="**3438**"]

Now go to your `wp_postmeta` table in your database, and find/search for the fields with `post_id` = the id you found for default kit. You will find a couple of fields. Now do the same for your destination site, note that the default kit will have a different id on the destination. You can use this SQL query to find the fields you are looking for, just replace the id:
`"SELECT * FROM wp_postmeta WHERE post_id = YOUR_ID_HERE"`

Then simply copy the field values (`meta_value`) from the source to the destination in your databases.
In my case I only copied the `_elementor_page_settings` and `_elementor_css` to get my colors and fonts cloned.

Remember to refresh any open editor pages for it to sync.
