### ISSUE TITLE
Site Settings Unstable causing effective changes without clicking "Update" button

### ISSUE THREAD

**Issue by whokneadsdough** [elementor/elementor#12341]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

In Site Settings changing H1 Color to Global Color Secondary causes all color settings to drop and font-families to change. This became effective on live site without clicking "Update" button.

Elementor 3.0.4
Elementor Pro 3.0.1
Theme: Hello

Tried changing themes to Astra and TwentyTwenty, also regenerated CSS after changing themes. Similar results after changing several headings to inherit different Global Fonts.

## Steps to reproduce

In Site Settings, Changed H1 Color to Global Color Secondary. Screen recording can be seen here https://youtu.be/DfyPKf6HwKg?t=172 (at 2:52 mark)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.9
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://stage.leonelcalara.com
	Home URL: https://stage.leonelcalara.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

== Elements Usage ==
	
	header : 1
		heading : 3
	wp-page : 1
		heading : 6
		text-editor : 1

== Log ==
	
Log: showing 10 of 102020-08-27 14:53:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-08-27 12:39:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: Start 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2020-08-29 11:48:42 [notice] System typography is disabled. nothing to do. 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2020-08-29 11:48:42 [notice] System colors are disabled. nothing to do. 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2020-08-29 11:48:43 [notice] Re-migrate 3.0.0 globals: End 
2020-08-30 09:41:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]

PHP: showing 3 of 3PHP: 2020-08-27 12:32:37 [notice X 4][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 11:48:43 [notice X 2][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 12:19:43 [error X 2][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::77] Uncaught Error: Cannot unset string offsets in /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php:77
Stack trace:
#0 /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php(21): Elementor\Core\Upgrade\Elementor_3_Re_Migrate_Globals->run()
#1 [internal function]: Elementor\Core\Upgrade\Elementor_3_Re_Migrate_Globals->ajax_re_migrate_globals(NULL, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, NULL, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/nelcalara/stage.leonelcalara.com/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/nelcalara/stage.leonelcalara.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/nelcalara/stage.leonelcalara.com/wp-includ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2020-08-29 18:41:08 [error X 1][https://stage.leonelcalara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:329019] elementorFrontend is not defined 

				
</details>

**Comment by whokneadsdough** [comment]
Issue still persists with 3.0.5 / Pro 3.0.2.
<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.9
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://stage.leonelcalara.com
	Home URL: https://stage.leonelcalara.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com


== Elements Usage ==
	
	header : 2
		heading : 3
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 2
		heading : 6
		text-editor : 1


== Log ==
	
Log: showing 16 of 162020-08-27 14:53:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-08-27 12:39:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: Start 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2020-08-29 11:48:42 [notice] System typography is disabled. nothing to do. 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2020-08-29 11:48:42 [notice] System colors are disabled. nothing to do. 
2020-08-29 11:48:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2020-08-29 11:48:43 [notice] Re-migrate 3.0.0 globals: End 
2020-08-30 09:41:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-08-31 07:22:57 [info] elementor::elementor_updater Started 
2020-08-31 07:22:57 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-08-31 07:22:57 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-08-31 07:22:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-08-31 07:22:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-08-31 07:23:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]

PHP: showing 3 of 3PHP: 2020-08-27 12:32:37 [notice X 4][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 11:48:43 [notice X 2][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 12:19:43 [error X 2][/home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::77] Uncaught Error: Cannot unset string offsets in /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php:77
Stack trace:
#0 /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php(21): Elementor\Core\Upgrade\Elementor_3_Re_Migrate_Globals->run()
#1 [internal function]: Elementor\Core\Upgrade\Elementor_3_Re_Migrate_Globals->ajax_re_migrate_globals(NULL, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/nelcalara/stage.leonelcalara.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, NULL, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/nelcalara/stage.leonelcalara.com/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/nelcalara/stage.leonelcalara.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/nelcalara/stage.leonelcalara.com/wp-includ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2020-08-29 18:41:08 [error X 1][https://stage.leonelcalara.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:329019] elementorFrontend is not defined 
JS: 2020-08-31 04:56:44 [error X 1][https://stage.leonelcalara.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.1:2:155090] Cannot read property \'stretch\' of null 


				
</details>

**Comment by arielk** [comment]
I merged this issue with #12363, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
