### ISSUE TITLE
#12249 is still an issue. Should be reopened. Still a problem in 3.0.5.

### ISSUE THREAD

**Issue by skompini** [elementor/elementor#12358]
[x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[x ] The issue still exists against the latest stable version of Elementor.

#12249 is still in existence. Please reference.

**Comment by mcrowell** [comment]
+1 - It seems to be a caching problem.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by whokneadsdough** [comment]
After managing to get Global Colors and Fonts working on the frontend, something as simple as changing an H1 setting in Site Settings breaks the frontend even without clicking the Update button. Check out my screen recording of this happening https://youtu.be/DfyPKf6HwKg?t=172. This problem also persists on 3.0.5 / Pro 3.0.2. 

When it's working `.elementor-kit-90 h1` picks up the styles from `.elementor-kit-90` (see https://youtu.be/DfyPKf6HwKg?t=12). When it breaks `.elementor-kit-90` has the declarations but `.elementor-kit-90 h1` is not found in the CSS (see https://youtu.be/DfyPKf6HwKg?t=172).

I've tried checking and unchecking Disable Default Colors and Fonts, different Optimized DOM Output settings, Regenerate CSS, Hello, Astra, and TwentyTwenty themes...all with similar results. No cache plugins installed, CloudFlare dev mode ON cache purged, incognito windows, different browsers, private mode, CMD+OPT+J > App > Local Storage Cleared.

<details><summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.4.9
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://stage.leonelcalara.com
	Home URL: https://stage.leonelcalara.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com

== Elements Usage ==

	header : 2
		heading : 3
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 2
		heading : 6
		text-editor : 1
== Log ==
</details>
