### ISSUE TITLE
🔗 🚀 Feature Request: Drag n' drop in mobile editing (Duplicate of #482)

### ISSUE THREAD

**Issue by dquak** [elementor/elementor#1235]
Hello, 
I've noticed that when switching to mobile editing, the Drag N' Drop features get disabled,
I was wondering if it something that can be changed by a option flag or something to enable easier redesign of elements on mobile view for mobile purposes pages?

**Comment by KingYes** [comment]
I merged this issue with another issue #482 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
