### ISSUE TITLE
Issues with other plugin

### ISSUE THREAD

**Issue by crossi72** [elementor/elementor#12353]
Hi all,
I’m the developer of Phoenix Media Rename and a user of my plugin reported an issue with Elementor Pro.

I write you here as @arielk-1 requested me on WordPress forum (https://wordpress.org/support/topic/issues-with-other-plugin/#post-13328466)

Do you have a developer version (even to use only on localhost, I just need to run it on a server with XDebug) to debug issues like this, or can you support me in some other way?

**Comment by arielk** [comment]
HI @crossi72,

Please email us the request to partnership@elementor.com with all the details about your plugin and we will send you what is needed there.

Thanks,
