### ISSUE TITLE
BUG | POPUP Scroll Infinite

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12360]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When i add a Popup, when you scroll on Mobile or Tablet the popup goes further down on the page than the "heigh" of the page..

## Steps to reproduce

Create a popup, go to mobile or tablet mode and scroll down.

https://www.loom.com/share/39b198539c5543bbb7c451c581b8695c

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/G6qTpSjd
</details>

**Comment by maurocarreraok** [comment]
Any on this? Thanks!!!

**Comment by maurocarreraok** [comment]
@arielk if you know something about this will be great! Thanks in advance.

**Comment by arielk** [comment]
Sorry for the delay, can you share with us a link to this page or steps to reproduce this situation?
