### ISSUE TITLE
Shortcuts for Navigation is not correct

### ISSUE THREAD

**Issue by lokeshkapoor** [elementor/elementor#12365]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The shortcut window (ctrl + ?) is showing wrong keyboard shortcut for toggle navigation.
The shortcut is ctrl + i, while that short cut shows ctrl + shift + i

## Steps to reproduce

1. Edit Any Page with Elementor
2. Use the shortcut (ctrl + ?) when the editor is open 
3. Now one can see the keyboard shortcut window where the shortcut for navigation (ctrl + shift + i) is wrong

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.31
	PHP Version: 7.4.8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://digirepo.ga/wp
	Home URL: https://digirepo.ga/wp
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Dynamic Content for Elementor
		Version: 1.9.5.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com

	Loginizer
		Version: 1.5.7
		Author: Softaculous

== Elements Usage ==
	

== Log ==
	
Log: showing 7 of 72020-08-29 15:45:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-09-01 03:12:03 [info] elementor::elementor_updater Started 
2020-09-01 03:12:03 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-01 03:12:03 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-01 03:12:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-09-01 03:12:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-09-01 03:12:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]

PHP: showing 3 of 3PHP: 2020-08-29 15:45:31 [warning X 6][/home/drepoga/public_html/wp/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/home/drepoga/public_html/wp/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 16:17:21 [notice X 2][/home/drepoga/public_html/wp/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 16:35:04 [error X 1][/home/drepoga/public_html/wp/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 5511776 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2020-08-29 16:21:39 [error X 1][https://digirepo.ga/wp/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.0.1:2:53165] Cannot read property \'addURLToWatch\' of undefined 

				
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.6

Feel free to update

Thanks!
