### ISSUE TITLE
Button Global Fonts Not working in site settings

### ISSUE THREAD

**Issue by oliveandlake** [elementor/elementor#12364]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If I go to Site Settings and "Theme Style" and style my buttons. There are a number of issues. Ultimately, some don't show on the front end. Global typography are not saved, etc. 

I have tried everything in the v.3 FAQ. I have replicated the issue on a fresh install using just Elementor 3.05, Elementor Pro 3.02 on Hello Theme. I just tried the same thing on a 2nd fresh install (local server) and get exactly the same problem. 

## Steps to reproduce

1. Create a page & Edit with Elementor
2. Add a button to the page.
3. Go to site settings -> buttons.
4. Change the typography - different size, style, whatever. 
5. Click update. Shows on the front end fine. The editor loses the colour and need to refresh the page. Not a huge problem. 
6. Go back to site settings -> buttons.
7. Click the '+' icon to create a new global font. Give it name. 

The font styling all disappears. Then click "global fonts" and the new global font is not saved. 

8. Go to "global fonts" and create a new style. 
9. Go back to 'buttons" and select this new style for the button. Doesn't show on front end.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.41 (Win64) PHP/7.3.12
	MySQL version: mariadb.org binary distribution v10.4.10
	PHP Version: 7.3.12
	PHP Max Input Vars: 2500
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: http://localhost/elementor3test
	Home URL: http://localhost/elementor3test
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0

== Active Plugins ==
	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com

== Elements Usage ==
	
	wp-page : 1
		button : 1
		heading : 2
	single-post : 1
		heading : 1

== Log ==
	
Log: showing 7 of 72020-08-27 06:48:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-09-01 04:16:25 [info] elementor::elementor_updater Started 
2020-09-01 04:16:25 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-01 04:16:25 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-01 04:16:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.5',
)]
2020-09-01 04:16:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.5',
)]
2020-09-01 04:16:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]

PHP: showing 1 of 1PHP: 2020-08-27 06:51:00 [notice X 2][C:\wamp64\www\elementor3test\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/12354 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
