### ISSUE TITLE
Bug with global typography

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12369]
When I create a global typography and assign it to elements, it appears in editor mode, but it does not appear at the rendering level, my elements in question inherit Elementor's basic styles.

**Comment by thehervy** [comment]
Hi, first you have to create a bug through specific guideline: https://github.com/elementor/elementor/issues/new?template=Bug_report.md

Second: this bug is known, really bad and a lot of duplicit issues has been created right now. Hopefully it will be solved really soon!

**Comment by arielk** [comment]
Duplicate of https://github.com/elementor/elementor/issues/12363
