### ISSUE TITLE
Elementor not loading at all - unable to open editor

### ISSUE THREAD

**Issue by agnisharma06** [elementor/elementor#12362]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

The elementor editor is not loading on any page, post or template. We've checked permalinks, tried uninstalling plugin, and it won't work other than in safe mode. Including a link to a screen recording below:

https://app.usebubbles.com/t7FHp7p5Dq98aw2jc1Tmuv/comments-on-buyer-nachonacho-com/#/comment=3HKq17FTsYwrRYjBCekGc1

## Steps to reproduce

1. Open wp.admin
2. Select page to edit
3. click on "edit with elementor
4. *issue* cannot get beyond loading screen

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.17
	PHP Version: 7.3.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://buyer.nachonacho.com
	Home URL: https://buyer.nachonacho.com
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.4.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: wpseo_editor
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Extras
		Version: 3.0.13
		Author: Namogo

	Elementor Pro
		Version: 2.10.3
		Author: Elementor.com

	Font Awesome
		Version: 4.0.0-rc20
		Author: Font Awesome

	Intercom
		Version: 2.6.4
		Author: Intercom

	Postmark (Official)
		Version: 1.12.5
		Author: Andrew Yates & Matt Gibbs

	Site Kit by Google
		Version: 1.15.0
		Author: Google

	Yoast SEO
		Version: 14.8.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		button : 1
		search-form : 1
		spacer : 2
		theme-archive-title : 1
	footer : 5
		nav-menu : 7
		social-icons : 4
		spacer : 2
		text-editor : 4
	header : 3
		button : 2
		ee-offcanvas : 1
		icon : 1
		image : 4
		nav-menu : 1
	page : 14
		button : 10
		ee-offcanvas : 1
		form : 1
		heading : 19
		icon : 1
		icon-list : 2
		image : 22
		menu-anchor : 3
		nav-menu : 1
		text-editor : 25
	popup : 1
		video : 1
	section : 16
		button : 3
		heading : 12
		image : 18
		menu-anchor : 1
		nav-menu : 1
		price-table : 1
		text-editor : 17
	single : 5
		author-box : 3
		button : 3
		call-to-action : 3
		form : 4
		heading : 15
		image : 3
		post-info : 6
		post-navigation : 1
		posts : 7
		share-buttons : 3
		spacer : 10
		text-editor : 2
		theme-post-content : 4
		theme-post-title : 4
	wp-post : 5
		button : 9
		form : 1
		heading : 22
		html : 1
		image : 26
		menu-anchor : 1
		price-table : 1
		spacer : 1
		text-editor : 32
		video : 1
	wp-page : 16
		button : 8
		form : 1
		heading : 29
		icon-box : 1
		image : 14
		menu-anchor : 2
		posts : 7
		price-table : 1
		search-form : 2
		spacer : 5
		text-editor : 12
		video : 4

== Log ==
	
Log: showing 20 of 272020-06-02 13:53:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.11',
)]
2020-07-03 08:19:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.13',
)]
2020-07-03 08:23:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.6.8',
  'to' => '2.10.3',
)]
2020-07-22 21:42:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-08-28 17:49:28 [info] elementor::elementor_updater Started 
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-28 17:49:28 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-28 17:49:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-28 17:49:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-31 10:05:27 [info] elementor::elementor_updater Started 
2020-08-31 10:05:27 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-08-31 10:05:27 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-08-31 10:05:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-08-31 10:05:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]

PHP: showing 8 of 8PHP: 2020-03-12 16:36:29 [error X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php::545] Uncaught Error: Class 'Elementor\Schemes_Manager' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php:545
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): Elementor\Plugin->init('')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(523): do_action('init')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(128): require_once('/opt/bitnami/ap...')
#6 /opt/bitnami/apps/wordpress/htdocs/wp-load.php(37): require_once('/opt/bitnami/ap...')
#7 /opt/bitnami/apps/wordpress/htdocs/wp-admin/admin-ajax.php(22): require_once('/opt/bitnami/ap...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-12 16:36:35 [error X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php::545] Uncaught Error: Class 'Elementor\Schemes_Manager' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php:545
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): Elementor\Plugin->init('')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(523): do_action('init')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(128): require_once('/opt/bitnami/ap...')
#6 /opt/bitnami/apps/wordpress/htdocs/wp-load.php(37): require_once('/opt/bitnami/ap...')
#7 /opt/bitnami/apps/wordpress/htdocs/wp-admin/admin.php(34): require_once('/opt/bitnami/ap...')
#8 /opt/bitnami/apps/wordpress/htdocs/wp-admin/plugins.php(10): requi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-12 16:36:35 [error X 3][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php::545] Uncaught Error: Class 'Elementor\Schemes_Manager' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php:545
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): Elementor\Plugin->init('')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(523): do_action('init')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(128): require_once('/opt/bitnami/ap...')
#6 /opt/bitnami/apps/wordpress/htdocs/wp-load.php(37): require_once('/opt/bitnami/ap...')
#7 /opt/bitnami/apps/wordpress/htdocs/wp-blog-header.php(13): require_once('/opt/bitnami/ap...')
#8 /opt/bitnami/apps/wordpress/htdocs/index.php(17): require('/opt/bi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-12 16:36:41 [error X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php::545] Uncaught Error: Class 'Elementor\Schemes_Manager' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php:545
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/plugin.php(479): Elementor\Plugin->init_components()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(288): Elementor\Plugin->init('')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(523): do_action('init')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(128): require_once('/opt/bitnami/ap...')
#6 /opt/bitnami/apps/wordpress/htdocs/wp-load.php(37): require_once('/opt/bitnami/ap...')
#7 /opt/bitnami/apps/wordpress/htdocs/wp-admin/admin.php(34): require_once('/opt/bitnami/ap...')
#8 /opt/bitnami/apps/wordpress/htdocs/wp-admin/index.php(10): require [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-12 16:36:47 [warning X 2][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/widgets/image-gallery.php::] Declaration of Elementor\Widget_Image_Gallery::add_lightbox_data_to_image_link($link_html) should be compatible with Elementor\Widget_Base::add_lightbox_data_to_image_link($link_html, $id) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-18 14:24:51 [notice X 12][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/elements/column.php::1003] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-07-03 08:23:04 [notice X 168][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/license/updater.php::79] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-31 10:05:27 [warning X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/elementor/css/post-992.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2020-03-13 04:18:38 [error X 7][https://nachonacho.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.6.8:2:40744] Cannot read property \'top\' of undefined 
JS: 2020-05-18 18:38:29 [error X 59][https://nachonacho.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.6.8:2:40744] undefined is not an object (evaluating \'elementor.$previewContents.find(\"#elementor\").offset().top\') 
JS: 2020-05-19 19:41:28 [error X 20][https://nachonacho.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:2:27276] undefined is not an object (evaluating \'this.container.settings.validators\') 
JS: 2020-05-30 01:02:04 [error X 2][https://nachonacho.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:170908] Cannot read property \'isDesignable\' of undefined 
JS: 2020-08-03 21:00:48 [error X 3][https://buyer.nachonacho.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view146\") has already been destroyed and cannot be used. 
JS: 2020-08-29 00:56:16 [error X 34][https://buyer.nachonacho.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:310780] Cannot read property \'urls\' of undefined 
JS: 2020-08-29 19:27:58 [error X 4][https://buyer.nachonacho.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:470394] Cannot read property \'document\' of undefined 

				
```
</details>

**Comment by chkserv** [comment]
Got the same issue. The button doesn't work at all, so no loading screen for me.

**Comment by jonathansoltero** [comment]
I was also experiencing this, I thought it was a plugin conflict as well, seems to happen at random, not much after latest update though.

**Comment by alan345** [comment]
Same issue here! 

Just after upgrading elementor, I cannot edit/create a post/page. It works in safe mode. I have uninstall all other plugins, reset to plain the permalinks, changed theme.. it is not working. Any idea? 🙏


![image](https://user-images.githubusercontent.com/15246526/92011358-d30ece80-ecff-11ea-8476-5669cafed19e.png)

**Comment by Somit1990** [comment]
I am also facing the same issue while building my website, please assist,
![error website](https://user-images.githubusercontent.com/70670014/92046383-04d77200-eda0-11ea-99bd-b269a26abe66.JPG)

**Comment by acal** [comment]
Just updated to 3.0.5 and now I can't get past the Grey Loading screen and into the editor. Even the safe mode doesn't work ... it just takes me to the Elementor Tool dashboard page. I also get this lovely console error on the Frontend. 
![image](https://user-images.githubusercontent.com/10677026/92136865-734e1b80-ee04-11ea-9d22-034a88724f43.png)

**Comment by mcrowell** [comment]
+1

**Comment by acal** [comment]
I also had to rollback to V2.9.9 and also for pro. Please assign someone to this issue.

**Comment by acal** [comment]
Hey folks! I hate to admit it but at least for me the solution was to completely clear the browser. When on your website page go to your browser's code inspector console > Application > Local Storage > Right-click on the website address > Clear. This did it for me. 🤦

**Comment by acal** [comment]
Okay... so while my above fix works... the problem shows up frequently. The processes of clearing the browser cache still works but the problem is consistent even after dumping the cache.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by lacroixfred** [comment]
We have the same issue here. Elementor editor isn't loading on the main site of our multisite. 
We tried to deactivate all plugin and switch to another theme. Finally we rolled back to 2.9.9 and the editor works, but this creates security issues. Is there someone working on this issue?

Please reopen this ticket and help us. Thank you.

**Comment by philcarbo** [comment]
@arielk I finally found the source of the problem.

In assets/js/common.js on line 7954 :
`(0, _defineProperty2.default)(BasePrefixStorage, "DEFAULT_KEY_PREFIX", 'e_');`
The DEFAULT_KEY_PREFIX is defined as 'e_' and used to get Elementor items from the browser's local storage. The problem is that this prefix is not specific enough. In my case I had two other items that were added by Google Ads. The Google Ads item keys seem to be random but in my case they were also starting with the default Elementor Prefix 'e_' and since those items where not expected by Elementor the script failed.

You can actually replicate this on any site using Elementor 3.x by adding a new item to the local storage having a key name starting with 'e_' and any string value. 
I tried with key: 'e_thisWillMakeElementorCrash', value: 'any_string_value' on a different site and was able to reproduce the bug.

In my case, simply changing the prefix from 'e_' to 'elem_' worked but my fix will most likely be overwritten on the next update.
Although using a more specific prefix fixes the problem it might not be the best solution. Using a specific property in the stored objects would be another solution.

Also on line 8020 of the same file, in the 'getItem' function the code checks if 'result' is not null but it should also check if it is an object before trying to parse it.
`if (null !== result) {
    return JSON.parse(result);
}`

I hope my explanation is clear enough but don't hesitate to contact me if you have any questions.

**Comment by blackashconsulting** [comment]
> @arielk I finally found the source of the problem.
> 
> In assets/js/common.js on line 7954 :
> `(0, _defineProperty2.default)(BasePrefixStorage, "DEFAULT_KEY_PREFIX", 'e_');`
> The DEFAULT_KEY_PREFIX is defined as 'e_' and used to get Elementor items from the browser's local storage. The problem is that this prefix is not specific enough. In my case I had two other items that were added by Google Ads. The Google Ads item keys seem to be random but in my case they were also starting with the default Elementor Prefix 'e_' and since those items where not expected by Elementor the script failed.
> 
> You can actually replicate this on any site using Elementor 3.x by adding a new item to the local storage having a key name starting with 'e_' and any string value.
> I tried with key: 'e_thisWillMakeElementorCrash', value: 'any_string_value' on a different site and was able to reproduce the bug.
> 
> In my case, simply changing the prefix from 'e_' to 'elem_' worked but my fix will most likely be overwritten on the next update.
> Although using a more specific prefix fixes the problem it might not be the best solution. Using a specific property in the stored objects would be another solution.
> 
> Also on line 8020 of the same file, in the 'getItem' function the code checks if 'result' is not null but it should also check if it is an object before trying to parse it.
> `if (null !== result) { return JSON.parse(result); }`
> 
> I hope my explanation is clear enough but don't hesitate to contact me if you have any questions.

Hi @philcarbo,
I attempted your fix on two of my sites, but I'm still getting the same error with Elementor not being able to load at all. Is this fix still working for you?

**Comment by advokatb** [comment]
Do we have a working solution for now?
It's very annoying bug
