### ISSUE TITLE
media carousel should be a template carousel

### ISSUE THREAD

**Issue by mauricev** [elementor/elementor#12374]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Consider the graphic on this page, https://einstein.yu.edu/departments/neuroscience/. It's got graphics and regular layout along with buttons. Button in a media carousel. Elementor cannot do this currently

**Describe the solution you'd like**
The way to implement this and also to allow images to look exactly as we want them is to accept templates in the carousel and not pictures. Media carousel widget should be dropped in favor of this.

**Describe alternatives you've considered**
There are none

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Nested Accordion widget released with Elementor v3.14.0! 🥳 

With the new Nested Carousel widget, you can customize the content of each Carousel Item with nested elements! 💪 
Drag & Drop widgets to create complex designs, fine-tune your carousel layout, design, interactions, and much more!

Check out the beta announcement here: https://elementor.com/help/carousel-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
