### ISSUE TITLE
[Bug] Wrong "display: inherit" property causes unnecessary content reflow for muted Inner Section columns inside the editor

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#12376]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When editing an Inner Section's Responsive Visibility, a "display: inherit" CSS property is applied to the element (this property is applied to all elements inside the Editor Preview), which causes an unnecessary reflow of the DOM print. 

This property was applied by **@matipojo on March 9 of this year** for the Elementor 2.9.5 release. I think the idea was that the elements would inherit the display applied by the frontend.css stylesheet, but they don't inherit anything.

## Steps to reproduce

- **Property Location:** https://github.com/elementor/elementor/blob/7690fa36646157b7296ba4753bc34dd108bf1e1e/assets/dev/scss/editor/preview/preview.scss#L895

- **Commit:** https://github.com/elementor/elementor/commit/cd85605d0888fa470a08223ec326731cab20794d

- **Steps to Reproduce:** 
https://www.loom.com/share/a2780051d1404673bacf269e9d039e1b

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Proposed solution

Change the property value to either **display: block** or leave it blank as it was prior to the commit.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.0
	MySQL version: mariadb.org binary distribution v10.4.13
	PHP Version: 7.4.7
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.2
		Author: Elementor.com

	Wordfence Security
		Version: 7.4.11
		Author: Wordfence

== Elements Usage ==
	
	wp-post : 0
		heading : 2
		image : 1
		text-editor : 1
		theme-site-logo : 1
	wp-page : 1

== Log ==
	
Log: showing 19 of 192020-08-26 14:00:42 [info] elementor::elementor_updater Started 
2020-08-26 14:00:42 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-26 14:00:42 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-26 14:00:42 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-26 14:00:42 [notice] System colors are disabled. nothing to do. 
2020-08-26 14:00:42 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-26 14:00:42 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-26 14:00:43 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-26 14:00:43 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-26 14:00:43 [notice] System typography is disabled. nothing to do. 
2020-08-26 14:00:43 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-26 14:00:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-26 14:24:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-09-01 02:23:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-09-01 02:23:37 [info] elementor::elementor_updater Started 
2020-09-01 02:23:37 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-01 02:23:37 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-01 02:23:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.5',
)]
2020-09-01 02:23:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.5',
)]

				
</details>

**Comment by arielk** [comment]
We can' reproduced this issue, Is there any other options on this Inner Section?

**Comment by zeinnicholas** [comment]
> We can't reproduced this issue, Is there any other options on this Inner Section?

@arielk Thanks for your feedback! This is a vanilla installation, with no other settings applied to any other element. Just a simple drag-and-drop of an inner section with no other settings. I think this might have something to do with the removal of the wrapper elements on the new release. But I could be wrong.

From what I've seen, Inner Sections receive the "display: block" property from the user agent (Chrome) as default. But when you mute them, they receive the "display: inherit" property, which inherits first the editor-preview.css's "display: none", which overrides the user agent's "display: block". 

After further investigation, I came to the conclusion that this is actually affecting the container inside the Inner Section. The Inner Section's container has a "display: flex" property, that when the Inner Section is muted doesn't know how to appear, so it takes the width of the content inside it. If you have enough content, it doesn't appear it reflows, if you don't have, you can see it reflowing. Either way, you're forcing the CSS engine to recalculate the position of all elements inside the inner section as well as all subsequent elements on the viewport, which for small pages shouldn't be an issue, but as the page becomes larger it can affect rendering performance, which in turn makes the editor appear slower. 

Thinking back, this might have been more noticeable in older versions of Elementor, when muting elements would take some extra ms to take effect on the page. Since overall the editor was slower, we wouldn't notice this. Now that the editor is much faster, this is more noticeable. I never understood why it would sometimes stutter when muting elements, but now it makes total sense.

I've saved a JSON file of the testing page for further investigation but considering that the CSS applied is from external stylesheets, I don't think it would make any difference.

Here's the link: https://1drv.ms/u/s!Ai7NtqnRsjryubp-R50FqULOeRs0gg?e=jieqHz

This may appear as nitpicking, but it's something that maybe should be tested further to see if it is important enough to be addressed to improve the overall performance of the editor. =)

**Comment by arielk** [comment]
@zeinnicholas thanks for clarification, very appreciate!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.8

Feel free to update

Thanks!

**Comment by zeinnicholas** [comment]
Thanks @shilo-ey !

You guys are awesome! Thank you @arielk !
