### ISSUE TITLE
Elementor doesn't set properly custom weblink (browser protocol)

### ISSUE THREAD

**Issue by Hembi** [elementor/elementor#12371]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor does not allow to set a non HTTP/HTTPS link (for example: TeamSpeak browser protocol link: ts3server://) to button or image url.
The provided link is replaced with the current page URL.

## Steps to reproduce

1. Add a button.
2. Set a custom browser protocol link to URL field in button settings (e.g. ts3server://192.168.1.1)
3. Save the page
4. Refresh

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.6.49 |  
PHP Version: | 7.2.33 |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 64M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

WordPress Environment |   |  
-- | -- | --
Version: | 5.5

Theme |   |  
-- | -- | --
Name: | Hello Elementor Child |  
Version: | 1.0.1 |  
Author: | Elementor Team |  
Child Theme: | Yes |  
Parent Theme Name: | Hello Elementor |  
Parent Theme Version: | 2.3.0 |  
Parent Theme Author: | Elementor Team

Elementor - 3.0.5 | By Elementor.com |  
-- | -- | --
Elementor Pro - 3.0.2 | By Elementor.com
```
</details>

**Comment by arielk** [comment]
We work with the native [WordPress URL protocol](https://developer.wordpress.org/reference/functions/wp_allowed_protocols/) to reduce security issues, you can always extend it by filter, read more here: https://developers.elementor.com/uri-protocols-handling-update/

Thanks for your feedback
