### ISSUE TITLE
Cannot export page as templates. Shows a line of "undefined" error

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#12377]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.x
- [x] The issue still exists against the latest stable version of Elementor.

## Description

On trying on export a page as a template, it just throws a line of "undefined." (21!) :

![image](https://user-images.githubusercontent.com/18551588/91938037-dbbbd080-ed10-11ea-8858-6686cf3b35a0.png)

## Steps to reproduce

1. Create a page.
2. Clicking on the caret icon besides Publish/Update button.
3. Select "Save as Template"
4. Give a name to the template
5. Click on the Save button

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

- PHP - v7.4
- Elementor Core - v3.0.5
- Elementor Pro - v3.0.2

**Comment by Mshiri** [comment]
hey there , i have the same problem, did you find a solution?

**Comment by marco-fabbri** [comment]
same issue here

**Comment by marco-fabbri** [comment]
I solved it disabling Yoast SEO :)

**Comment by svendeckers** [comment]
> I solved it disabling Yoast SEO :)

Worked for me, thanks!
Hope this gets fixed soon, don't want to keep turning Yoast on and off

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!
