### ISSUE TITLE
Title not loading in published pages/articles

### ISSUE THREAD

**Issue by AwayWithYourFairies** [elementor/elementor#12372]
Good Day!

I seek for your help as I encounter issues with the titles. They don't load properly on all pages/posts. They have the right size but not the right color.
When I go to the page builder, I can see them in the right size and right color.
Elementor is up to date. Wordpress as well.
I tried to update the pages and posts but the bug stays.

I deactivated the latest plugins I had. Purged the cache. And even change the Cache tool (from W3 Total Cache to LiteSpeed Cache). But the bug is still there.

Do you have any idea on how to fix it please?

Thanks

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/12363 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
