### ISSUE TITLE
BUG | Maintenance Mode ON

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12373]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

When Mantenance Mode is ON and the User Log in in has any role the site shows up a Warning "Cannot modify header information"

![image](https://user-images.githubusercontent.com/68023943/91875652-27f40b80-ec52-11ea-80e6-2125e5571286.png)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/5PvLQc2r 
```
</details>

**Comment by arielk** [comment]
We can't reproduce this issue, can you please deactivate all of other plugins and let me know if it solves the issue.

**Comment by maurocarreraok** [comment]
Hi @arielk , i've just have Elementor & Pro installed. Anyway. I dont know why its solved.
