### ISSUE TITLE
Conflict with Woocommerce /my-account page

### ISSUE THREAD

**Issue by lutifyme** [elementor/elementor#12383]
There is a conflict between Elementor version 3.X (tested with 3.0.5 and 3.0.2 Pro) and Woocommerce when a non-admin user logs into WordPress installation.

- [V] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [V] The issue still exists against the latest stable version of Elementor.

## Description

With Woocommerce plugin installed, when a non-admin user logs in they are taken to /my-account page. Woocommerce doesn't allow non-admin users to reach /wp-admin. With version 3.X of Elementor installed, user is instead taken to /wp-admin and an error is thrown in dashboard:

Warning: Invalid argument supplied for foreach() in /path-to/wp-content/plugins/elementor/core/app/app.php on line 53

Warning: Cannot modify header information - headers already sent by (output started at /path-to/public/wp-content/plugins/elementor/core/app/app.php:53) in /path-to/wp-includes/functions.php on line 6270

Warning: Cannot modify header information - headers already sent by (output started at /path-to/wp-content/plugins/elementor/core/app/app.php:53) in /path-to/wp-includes/pluggable.php on line 1296

Warning: Cannot modify header information - headers already sent by (output started at /path-to/wp-content/plugins/elementor/core/app/app.php:53) in /path-to/wp-includes/pluggable.php on line 1299

## Steps to reproduce

1. Install Elementor and Elementor Pro latest versions
2. Install Woocommerce latest version
3. Under Settings > General in WP dashboard allow anyone to register
4. Set default role for new registrations to Subscriber
5. Register a new account
6. Login with the new account
7. Instead of /my-account user is taken to /wp-admin and error is thrown as displayed above

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Reverting to version 2.x of Elementor solves the problem.**

## Environment

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.46 (Unix) OpenSSL/1.1.1
	MySQL version: (Ubuntu) v5.7.31
	PHP Version: 7.4.9
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: url
	Home URL: url
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Inactive

**Comment by lutifyme** [comment]
This is the error as it appears in the 'Your site is experiencing an issue' email:

Error Details
=============
An error of type E_ERROR was caused in line 131 of the file /path-to/wp-content/plugins/elementor/includes/autoloader.php. Error message: Uncaught Error: Class 'Elementor\Controls_Manager' not found in /path-to/wp-content/plugins/elementor/includes/autoloader.php:131
Stack trace:
#0 /path-to/wp-content/plugins/elementor/includes/autoloader.php(78): Elementor\Autoloader::init_classes_map()
#1 /path-to/wp-content/plugins/elementor/includes/autoloader.php(251): Elementor\Autoloader::get_classes_map()
#2 /path-to/wp-content/plugins/elementor/includes/autoloader.php(304): Elementor\Autoloader::load_class('Core\\Logger\\Man...')
#3 [internal function]: Elementor\Autoloader::autoload('Elementor\\Core\\...')
#4 /path-to/wp-content/plugins/elementor/includes/plugin.php(663): spl_autoload_call('Elementor\\Core\\...')
#5 /path-to/wp-content/plugins/elementor/includes/plugin.php(472): Elementor\Plugin->__construct()
#6 /path-to

Line is #6 is truncated in the email.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.7

Feel free to update

Thanks!

**Comment by lutifyme** [comment]
Thanks. I can confirm 3.0.7 solves this.
