### ISSUE TITLE
Elementor 3.x issue with User Switching Plugin

### ISSUE THREAD

**Issue by richward111** [elementor/elementor#12388]
The php error below is displayed in the WordPress back-end when clicking on a 'Switch To' link from the User Switching plugin. This only shows with Elementor 3.x including 3.05, with and without Elementor Pro activated. A rollback to Elementor 2.9.x removes the issue. 

_Invalid argument supplied for foreach() in .../wp-content/plugins/elementor/core/app/app.php on line 53

Warning: Cannot modify header information - headers already sent by (output started at .../wp-content/plugins/elementor/core/app/app.php:53) in .../wp-includes/functions.php on line 6270

Warning: Invalid argument supplied for foreach() in .../wp-admin/includes/plugin.php on line 190_

I have also reported this on the User Switching WordPress plugin forum today as I'm not sure which plugin developer will need to resolve this.

**Comment by ZanekShaw** [comment]
I am also getting the Elementor error.
I don't have the User Switching plugin tho.

`PHP Warning:  Invalid argument supplied for foreach() in /[path-to]/wp-content/plugins/elementor/core/app/app.php on line 53`

Started after updating to v3.0.5
Not sure what triggers this to happen but it is filling my `/[path-to]/wp-admin/error_log` file

Elementor v3.0.5
Elementor Pro v 3.0.2

**Comment by lutifyme** [comment]
I can confirm I've encountered this error as well. User switching is installed but the error encountered under different circumstances. I think it's a wider issue as it appears to affect other areas. See my issue here - https://github.com/elementor/elementor/issues/12383

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.7

Feel free to update

Thanks!
