### ISSUE TITLE
Site hacked - Elementor plug-ins backdoor/trojan ?

### ISSUE THREAD

**Issue by ScottyfromParis** [elementor/elementor#12382]
Hi,
My website has been hacked three times in the past two months. No pw has been stolen, though. Seems that Elementor plug-ins are involved, permitting hackers to modify the site database by some kind of trojan-like manipulations. As a result, the default site URL was modified, re-directing to a junk site, and like 20 lines of java code were added to every single plug-in related database item, containing redirections code as well. 
This is more than very annoying. Elementor should take care that every allowed (and promoted) plug-in is safe and match security requests.
Damages can be high and are in fact un-estimable for site owners. As a beginning Email adresses related to infected sites are automatically banned and rejected from potential clients servers. And, of course, you have to rebuild/reload the site every time.
Please consider taking time to address this issue.
If I had to re-do my site now, I'd be very cautious and not very confident about Elementor, because of this lack of security.
Thanks

**Comment by markc** [comment]
Do you happen to have the File Manager plugin installed? If so then it is more likely the culprit.

**Comment by ScottyfromParis** [comment]
I'll check that ASAP. Thank you !!

J-Pascal

Jean-Pascal Audiffren
SCOTT Productions
p: +33 6 85 67 86 52
<jpa@scottprod.com>

**Comment by arielk** [comment]
If you have more details on Elementor Involvement, feel free to reopen the issue.
