### ISSUE TITLE
un-needed requests from elementor that slowing my website down

### ISSUE THREAD

**Issue by ahmedshawkky** [elementor/elementor#12396]
Hi Everyone,
Kindly help to remove these unneeded requests that coming from Elementor as it's slowing my website down more over i'm not even using these custom fonts in my website so would be grateful if someone help on that.
Note: my website URL is: lablancaegypt.com
1- https://www.lablancaegypt.com/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff2
2- https://www.lablancaegypt.com/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-regular-400.woff2
3- https://www.lablancaegypt.com/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff2
4- https://fonts.gstatic.com/s/josefinslab/v11/lW-5wjwOK3Ps5GSJlNNkMalnqg6v.woff2
5- https://fonts.gstatic.com/s/josefinslab/v11/lW-mwjwOK3Ps5GSJlNNkMalvASy6Kerl.woff2
6- https://fonts.gstatic.com/s/montserrat/v14/JTURjIg1_i6t8kCHKm45_cJD3gnD_g.woff2
7- https://fonts.gstatic.com/s/montserrat/v14/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2
8- https://fonts.gstatic.com/s/average/v9/fC1hPYBHe23MxA7rEeV6VA.woff2

**Comment by riadcitaku** [comment]
For Google Fonts:

`add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );`

For Font Awesome:

```
add_action( 'elementor/frontend/after_register_styles',function() {
	foreach( [ 'solid', 'regular', 'brands' ] as $style ) {
		wp_deregister_style( 'elementor-icons-fa-' . $style );
	}
}, 20 );
```

Reference: https://docs.elementor.com/article/286-speed-up-a-slow-site

**Comment by ahmedshawkky** [comment]
Hi bro, i had already saw this article and tried to insert this php code in my php child theme but unfortunately nothing happened 😔

**Comment by arielk** [comment]
Basically we load these assets only if they are used on the page. If you do not use them on the page they should not be loaded.
You can also migrate to Font Awesome 5 to solve this issue: https://docs.elementor.com/article/584-migration-to-font-awesome-5
