### ISSUE TITLE
Documentation references deprecated function _content_template()

### ISSUE THREAD

**Issue by eatbuildplay** [elementor/elementor#12406]
All Elementor document for widget building contains reference to a deprecated function `_content_template()`. This function is deprecated as of v2.9.0 according to line 1906 of controls-stack.php where the use of **`content_template()`** replaces `_content_template()`. 

This needs to be updated at https://developers.elementor.com/render-widget-template/ and other pages that refer to the deprecated function.

**Comment by DorShahar** [comment]
Thanks @eatbuildplay for reporting.
We will handle this. 
Notice it will take time.

**Comment by guytzhak** [comment]
Still reference to the _content_template function.
when tried to use content_template method, it doesn't works

**Comment by alvarini** [comment]
how to solve this meanwhile?

**Comment by zaxwebs** [comment]
Still referes to the _content_template function.

**Comment by zerfl** [comment]
You should really dedicate a person to update the docs once in a while when you soft deprecate something.
