### ISSUE TITLE
Twitter Share - No Space Between Title and URL

### ISSUE THREAD

**Issue by LensDigitalUK** [elementor/elementor#12403]
When you share a post via the Share Buttons widget, there is no space between the page title and the url/

Example can be seen at http://fib.wearelens.co.uk/2019/05/31/the-rivermoor-nominated-for-bracknell-football-ground-award/ and click the Twitter share;

"Reading City's home has undergone significant improvements over the last 12 monthshttp://fib.wearelens.co.uk/2019/05/31/the-rivermoor-nominated-for-bracknell-football-ground-award/"

To my untrained eye, the issue is in https://github.com/elementor/elementor/blob/master/assets/lib/share-link/share-link.js

twitter: 'https://twitter.com/intent/tweet?text={text}{url}'

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
