### ISSUE TITLE
BUG | Importing Template from Library

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12414]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Eveything is connected to the domain. Licence is active. I reconnect the Library and nothing happend as you can see on the video.

## Steps to reproduce

https://www.loom.com/share/0247961e33ec41558748369fe0ac12eb

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/rEp54gRj
```
</details>

**Comment by michaelwright74** [comment]
There is an issue with your licence.

Go to Elementor > Licence then click disconnect.

You should then get a prompt to Connect & Activate your licence, click on that and make sure you sign in with the account that you purchased your PRO licence with.

**Comment by maurocarreraok** [comment]
> There is an issue with your licence.
> 
> Go to Elementor > Licence then click disconnect.
> 
> You should then get a prompt to Connect & Activate your licence, click on that and make sure you sign in with the account that you purchased your PRO licence with.

Hi! Thanks for the reply but same happend.
I disconected the site, after connecting again wordpress took me to Elementor Page to Activate the Licence. Then the site went back to Wordpress and shows "Licence Active".

Nothing happened, same message.

![image](https://user-images.githubusercontent.com/68023943/92267312-f039cd80-eeb6-11ea-9637-03129b2d5a0b.png)

**Comment by michaelwright74** [comment]
> > There is an issue with your licence.
> > Go to Elementor > Licence then click disconnect.
> > You should then get a prompt to Connect & Activate your licence, click on that and make sure you sign in with the account that you purchased your PRO licence with.
> 
> Hi! Thanks for the reply but same happend.
> I disconected the site, after connecting again wordpress took me to Elementor Page to Activate the Licence. Then the site went back to Wordpress and shows "Licence Active".
> 
> Nothing happened, same message.
> 
> ![image](https://user-images.githubusercontent.com/68023943/92267312-f039cd80-eeb6-11ea-9637-03129b2d5a0b.png)

Hmm strange, ok a few questions...

1) Do you actually own an Elementor Pro Licence?
2) What versions of Elementor Core & Elementor Pro are you using?

**Comment by maurocarreraok** [comment]
Hi!
Yes, i have the Pro since 2 years ago.
I have the latest versions in this site.

**Comment by michaelwright74** [comment]
> Hi!
> Yes, i have the Pro since 2 years ago.
> I have the latest versions in this site.

Was the Elementor Pro licence activated by a different WP Admin account than the one you are using?

**Comment by michaelwright74** [comment]
When the licence is activated properly it should include your email address on the Elementor > Licence page as shown below. From your Loom it seems this isn't the case for you.

<img width="511" alt="Capture" src="https://user-images.githubusercontent.com/30985280/92300101-1a8b9980-ef50-11ea-8f45-829d320c315e.PNG">
