### ISSUE TITLE
Section background on different break-points.

### ISSUE THREAD

**Issue by daandegroot123** [elementor/elementor#12430]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a website with a background image on my section. This image is however not suitable for mobile devices and therefore must not be displayed on mobile. I can achieve this by making the image size 0% on mobile. But, now I want my background to have colour on mobile. Enter the problem, I can't give my section a background colour on mobile, because this will also give my section a colour on a desktop.  

**Describe the solution you'd like**
The ability to choose different colours on section backgrounds at different break-points.

**Describe alternatives you've considered**
The only two solutions I see are:

1. Duplicating the section and making one of them only visible on desktop and the other one only on mobile.
2. Creating a background image that is just one colour.

But, both these solutions are not great as 1 requires me to always duplicate every change I make to the section and 2 because using images for background colours takes unnecessary bandwidth?.

**Comment by black-eye** [comment]
+1
Similar, but not identical request here: https://github.com/elementor/elementor/issues/6778

**Comment by Hosting-Mate** [comment]
+1
Great idea!

**Comment by daandegroot123** [comment]
> +1
> Similar, but not identical request here: #6778

The issue you are referencing is similar to my problem with my second solution. But, that does not take away the fact that is really redundant to make images for single colour backgrounds. Besides, the solution in that issue does not solve my problem.

**Comment by pixelicous** [comment]
no response from support teams to paying customer on either this or the other requests for setting background sizes on column background images..

**Comment by garteth** [comment]
+1 Need this like a fat kid needs cake.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10247, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by black-eye** [comment]
> Merged issue
> 
> I merged this issue with #10247, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> Thanks for your feedback!

I think this issue represents the problem better, but I've added my vote there as well.

**Comment by actionTurtle** [comment]
Yeah would be a cool feature

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
