### ISSUE TITLE
Buddyboss section theme button link combining issue

### ISSUE THREAD

**Issue by nzlgl** [elementor/elementor#12438]
Hello,
I'm using buddyboss theme and elementor. I'm creating a section with buddyboss theme section which elementor recently provided. I'm creating a section with tabs, and for each tab I can enter url for buttons. However, tabs are combining these links. To illustrate:
Tab-1: button link url no.1
Tab-2: button link url no.2
I enter like this, but it does make:
Tab-1: button link url no.1
Tab-2: button link url no.1 button link url no.2

How can you fix this?
![tab-2](https://user-images.githubusercontent.com/69120001/92373701-6a609100-f107-11ea-8309-00b541ced289.jpg)
![tab-1](https://user-images.githubusercontent.com/69120001/92373707-6b91be00-f107-11ea-931a-a6072958af5e.jpeg)

Thanks in advance,

**Comment by DorShahar** [comment]
Hi,
Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.


However, you can create templates and shortcodes to render those templates.
