### ISSUE TITLE
Deprecated: Elementor\Editor is deprecated since version 2.6.0! Use Elementor\Core\Editor\Editor instead

### ISSUE THREAD

**Issue by digitizecreation** [elementor/elementor#12436]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by digitizecreation** [comment]
How to resolved this issue

**Comment by shilo-ey** [comment]
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.


Most likely that you're using an extension that uses this deprecated method.

Please make sure all up to date.

**Comment by digitizecreation** [comment]
my all plugins, themes are updated but still facing this problem

**Comment by shilo-ey** [comment]
Try to deactivate them. apparently one of them is outdated and uses deprecated methods.
