### ISSUE TITLE
Post Widget Query

### ISSUE THREAD

**Issue by mrt-gnz** [elementor/elementor#12435]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like an improvement in the way of filtering posts in the "Post Widget". Now it's possible to write e.g. categories to "include" or "exclude". It happens that a post belongs to more than one category and one need to filter in the sub-categories, all belonging to the main one.
![image](https://user-images.githubusercontent.com/65703654/92362001-9c65f900-f0ef-11ea-825d-27c7de1c96af.png)

**Describe the solution you'd like**
Would it be possible to have the following choice: choose if the "where" clause of the query has to use a "and" or a "or"?

**Describe alternatives you've considered**
At the moment I filter manually, adding one post at a time to the desired section. Still, when the posts become a lot, it is going to be difficult to keep up with them.

**Additional context**
![query tab](https://user-images.githubusercontent.com/65703654/92363030-24003780-f0f1-11ea-828c-b1e8da89f29a.PNG)

**Comment by DorShahar** [comment]
Hi @mrt-gnz 
We have the custom query filter for that :) 
Please see our documentation here: https://developers.elementor.com/custom-query-filter/
