### ISSUE TITLE
PHP PROBLEM SINCE I INSTALLED ELEMENTOR PRO AND THEN UPDATED ELEMENTOR

### ISSUE THREAD

**Issue by interpersonal** [elementor/elementor#12437]
I've already looked at a problem similar to this one, but it doesn't match mine at all.

The error it gives me is this:

Warning: Invalid argument supplied for foreach() in /usr/home/interpersonal.es/web/wp-content/plugins/elementor/core/app/app.php on line 53
Warning: Invalid argument supplied for foreach() in /usr/home/interpersonal.es/web/wp-admin/includes/plugin.php on line 1904

interpersonal.es It is a new website and I cannot publish it due to this problem with Elementor.

I have no idea what to do ... never happened to me before.

I deeply appreciate help with the solution.
Thanks in advance.
Regards.

**Comment by shilo-ey** [comment]
I merged this issue with  #12383, #12388, which are on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by interpersonal** [comment]
Ok, step to thread # 12388
Thank you!
