### ISSUE TITLE
Easily move between pages in Elementor

### ISSUE THREAD

**Issue by GaryRWills** [elementor/elementor#12433]
When editing with Elementor, I end up Previewing the website to allow me to select another page to edit.  I would like to suggest a Site Page List on the side.  Click a page and the it opens in Elementor.

**Comment by daandegroot123** [comment]
You could use the Finder from within the editor. You just type in the name of the page you want to edit and you will be brought to the editor of that page.

**Comment by arielk** [comment]
Introducing Finder: The Easiest Way to Switch Between Pages:
https://elementor.com/blog/introducing-finder/
