### ISSUE TITLE
Navigator

### ISSUE THREAD

**Issue by aprosenthal** [elementor/elementor#12442]
Have navigator list sections, etc in order from top to bottom rather than most recent at the bottom. Currently it is extremely difficult & a major time consumer to locate the section I'm working on. Thanks.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for your suggestion, but we reflect the layout of the page you are editing within the Navigator, not by the order of the elements being placed.
The first element will be placed on top, last on bottom.

Thanks again
