### ISSUE TITLE
Different text for devices 

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#12445]
Please make it possible to write text in headers and text editor for each device version. Why do I suggest doing this and not duplicating the section, it complicates the layout process, when hiding one in editing mode, we all see it exactly, hiding it to see how it will be inconvenient, you have to go through how many pixels to move, reduce or enlarge something. Also, there is a problem with the compatibility of the written text for different devices, if you use transfer, then it can work fine for a PC and generally not suitable for a mobile device, and we change the size of the text becomes smaller. Make it possible to work individually with each field just as you did, for example, with setting the indents, if I don't want to change the text, then it is simply taken by default from the versions above, for example, on a PC we wrote one text and it is great for mobile versions, in mobile versions change only the size and the content will already be taken from the pc versions. Me and many people most likely often need to write hyphenated text, since indentation is not a solution for text.

**Comment by fabianenzensperger** [comment]
+1

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Ref: https://github.com/elementor/elementor/issues/2989

Thank you for your feedback

**Comment by promocot** [comment]
> Unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.
> 
> Ref: #2989
> 
> Thank you for your feedback

I do not understand then the point in pro support if you do not listen to your paid subscriber, no matter what solution I write, you cancel everything ... this option also helps for better SEO, since duplicating layers creates mess in the code and is not convenient ... I'm disappointed with how you treat your paid subscribers and don't listen at all, you don't answer for tickets ... what did I pay for? With this attitude, I can go to special sites and download hacked versions ... finally, the attitude is terrible, I'm not happy and intend to write a review about it

**Comment by arielk** [comment]
@promocot How do I know you are a pro user? This is the GitHub community and we try our best to organize user requests according to our roadmap.

Anyway, I wrote that in the short to medium term we are not planning to develop this feature exactly as you wrote but in a slightly different way, so I'm closing it now, but that does not mean I'm ignoring you :(

Hoping for understanding.
