### ISSUE TITLE
Share Button capable of sharing outside of shared page

### ISSUE THREAD

**Issue by brandon-fox-staplegun** [elementor/elementor#12455]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Is it possible to use the Share Button widget outside of the actual page that is being shared and to link to the page that will be shared? I see that you can use the current page or use a custom page, but the custom page option only has the ability to insert an actual link. Is there a way to pull in a Post URL of the current post?

**Describe the solution you'd like**

I am creating an events listing using CPT. The listing has an option to share this listing, but the way it's set up currently, you will be sharing the event listing page and now the actual event that the shared button is attached to. It'd be nice to have the post URL pulled into this button, to be used externally as well as internally.

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment]
We have added Added dynamic tag controls to Share Buttons widget.

Please see here: https://github.com/elementor/elementor/issues/10729

Thanks for your feedback!
