### ISSUE TITLE
Elementor Post Widget Pagination 404 Problem

### ISSUE THREAD

**Issue by ikramkami** [elementor/elementor#12450]
Please help me with this problem. I am using Elementor Pro and Custom Skin Pro. And I an in using a loop template in the Posts widget and I am facing this problem
http://fazlerasheed.com/shop/

you can check it on this page.
Thanks

**Comment by oliver-gomes** [comment]
@ikramkami i went to your site, it looks like it's working now. How did you fix it?

**Comment by rami-elementor** [comment]
Hi,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
