### ISSUE TITLE
Multiple transform values

### ISSUE THREAD

**Issue by skalanter** [elementor/elementor#12451]
Hi There,

I hope you are fine,

I think now Elementor needs the multiple CSS element compatibilities as well. it would be appreciated creating a new **controller** something like it into the plugin core:

http://modernaweb.net/uploads/transform-1.jpg

Maybe create a new one like Divi page builder styles, but smother:
http://modernaweb.net/uploads/transform-2.jpg

Or with more creativity like Webflow:
http://modernaweb.net/uploads/transform-3.jpg

Stay Safe

**Comment by vgstef** [comment]
Good idea to have control over all the axis transformations and other deformations. Especially when we have to deal with desktop, tablet and mobile, in addition of compatibility with different browsers.

Is the implementation of this feature on the roadmap of Elementor?

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
