### ISSUE TITLE
Form widget cannot add custom fields value

### ISSUE THREAD

**Issue by TimSun-Code** [elementor/elementor#12463]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
I made a popup box that has the "form "widget. I added a field with a type of "URL". I went under the advanced tab and tried adding a custom field, but it can't find them. 

I tried doing the same for a regular button widget with the "link" field and it works fine. So it looks to me that is a bug.

## Steps to reproduce
1. Create custom fields defined as URL on wordpress.
2. Create a popup
3. Add the Form widget
4. Create a Field of "URL" in the Form widget
5. Go in custom field, select ACF and you wont see your custom fields to choose.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.14
	PHP Version: 7.3.19
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://moneyballer.net
	Home URL: http://moneyballer.net
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.4.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

== Active Plugins ==
	Advanced Cron Manager
		Version: 2.4.0
		Author: BracketSpace

	Advanced Custom Fields
		Version: 5.9.1
		Author: Elliot Condon

	All In One WP Security
		Version: 4.4.4
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Child Theme Configurator
		Version: 2.5.6
		Author: Lilaea Media

	Cookie Notice
		Version: 1.3.2
		Author: dFactory

	Custom Post Type UI
		Version: 1.8.0
		Author: WebDevStudios

	Duplicator
		Version: 1.3.36
		Author: Snap Creek

	Easy Table of Contents
		Version: 2.0.11
		Author: Steven A. Zahm

	Elementor
		Version: 3.0.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 4.2.3
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 7.12.2
		Author: MonsterInsights

	GP Premium
		Version: 1.11.3
		Author: Tom Usborne

	HappyForms
		Version: 1.9.19
		Author: HappyForms

	Insert Headers and Footers
		Version: 1.4.6
		Author: WPBeginner

	Jetpack by WordPress.com
		Version: 8.9
		Author: Automattic

	Post SMTP
		Version: 2.0.15
		Author: Yehuda Hassine

	PublishPress Capabilities
		Version: 1.9.12
		Author: PublishPress

	Query Monitor
		Version: 3.6.4
		Author: John Blackbourn

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	Smush
		Version: 3.6.3
		Author: WPMU DEV

	SSL Insecure Content Fixer
		Version: 2.7.2
		Author: WebAware

	W3 Total Cache
		Version: 0.14.4
		Author: BoldGrid

	Wordfence Security
		Version: 7.4.11
		Author: Wordfence

	WP User Avatar
		Version: 2.2.7
		Author: ProfilePress

== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		text-editor : 1
		theme-archive-title : 1
	page : 3
		button : 6
		divider : 1
		eael-data-table : 5
		heading : 40
		image : 23
		progress : 5
		spacer : 18
		text-editor : 69
		toggle : 2
		video : 6
	popup : 2
		form : 1
		heading : 1
		image : 1
	section : 8
		button : 3
		eael-cta-box : 1
		heading : 5
		image : 3
		posts : 1
		text-editor : 9
	single : 1
		button : 1
		heading : 1
		image : 1
		spacer : 1
	widget : 0
		text-editor : 35
	wp-post : 4
		archive-posts : 1
		blockquote : 1
		button : 8
		eael-cta-box : 16
		global : 1
		heading : 24
		image : 11
		posts : 1
		table-of-contents : 2
		text-editor : 20
	wp-page : 1
		button : 1
		call-to-action : 24
		divider : 2
		eael-info-box : 1
		heading : 13
		image : 2
		menu-anchor : 1
		posts : 2
		text-editor : 12

== Log ==
	
Log: showing 20 of 362020-04-20 09:04:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-04-21 23:36:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]
2020-06-18 05:06:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.12',
)]
2020-06-18 05:06:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.3',
  'to' => '2.10.2',
)]
2020-07-29 01:31:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '2.9.14',
)]
2020-07-29 01:31:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.2',
  'to' => '2.10.3',
)]
2020-09-09 15:16:41 [info] elementor::elementor_updater Started 
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-09 15:16:41 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-09 15:16:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.7',
)]
2020-09-09 15:16:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.7',
)]
2020-09-09 17:04:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.4',
)]

JS: showing 7 of 7JS: 2019-10-06 03:08:25 [error X 24][http://moneyballer.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.3:32:171536] this.manager.setPage(...).showView is not a function 
JS: 2019-10-08 18:40:47 [error X 3][http://moneyballer.net/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.7.3:2:66303] Routes: `panel/editor/undefined` not found. 
JS: 2019-10-10 07:54:06 [error X 2][http://moneyballer.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.3:32:63917] this.ui.apply.add is not a function 
JS: 2019-10-28 14:36:52 [error X 11][http://moneyballer.net/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.2.4:1:15147] Block-scoped declarations (let, const, function, class) not yet supported outside strict mode 
JS: 2020-04-05 23:11:16 [error X 3][https://moneyballer.net/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.7:2:187452] Cannot read property \'map\' of undefined 
JS: 2020-04-12 22:15:30 [error X 1][https://moneyballer.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.7:31:104032] Cannot read property \'message\' of null 
JS: 2020-06-30 18:16:56 [error X 1][https://moneyballer.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.12:31:153580] Cannot read property \'html\' of undefined 

				
</details>

Screenshots:
https://imgur.com/a/r1t7oJu

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #13355, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
