### ISSUE TITLE
No Right click protection on image gallery

### ISSUE THREAD

**Issue by juanvalerah** [elementor/elementor#12477]
Hi,
I have a plugin to protect image and content for the website (name of plugin: "WP Content Copy Protection & No Right Click") i need to know how can i stop displaying a link to the full image over it. I wrote to them and they answered me this:

"The thing you must know: There is no way to protect any image if you view it with its full url (example: http://www.sitename.com/foldername/image.jpg) because it will be out of your WordPress codes include our plugin codes.

So you should fix the problem by stop displaying a link to the full image over it

Just Edit the post or the page and remove the links over your images or you may find a (removing links) plugins that will do that for you in one click, Also we have an option to do this for you on the fly inside the smart protection tab

On the fly = you will not see the links but the links are not removed permanently and when the plugin deactivated everything return as it was before

if you still want to view large photos when a user clicks on your images and also keep them protected we advise using simple lightbox plugin (https://wordpress.org/plugins/simple-lightbox) with our plugin

You will have a magical mix"

So, my problem is that when I deactivate the right click on an image it opens to a new tab and there the image can be downloaded.

Hope you can help me.

**Comment by arielk** [comment]
You just need to remove the link of the image (Link= None) and that it
