### ISSUE TITLE
We need Hover to tab Typography (widget Column)

### ISSUE THREAD

**Issue by arekuusa** [elementor/elementor#12489]
I selected colors Hover in Background, Background Overlay, Border. http://prntscr.com/ug3f1m
But there is no Hover in Typography. Need white text on hover http://prntscr.com/uezack

**Comment by DorShahar** [comment]
Hi,
Thanks for reaching out
Your request is unclear. 
Please open a new request according to our guidelines - with one request at a time, just so we could understand better your need and handle it.

Thanks
