### ISSUE TITLE
3.0.7 Text Editor Not Reflecting Styling Changes, Ignoring Inline CSS - Typography Size/Weight/Etc - Links Only?? - Global Settings Issue

### ISSUE THREAD

**Issue by badwebdev** [elementor/elementor#12486]
Title essentially reflects the issue.

Elementor Base 3.0.7/Elementor Pro 3.0.4
WordPress 5.5.1
Nginx/Pressable Hosting Enviro
Hello Theme
No other plugins installed

Attempting to create a page, two column layout, text editor will not reflect changes as directed in the styling tab, nor on live page after updating.

ALSO: Unable to manually inline <span style>.

**### All CSS is being ignored.**

**UPDATE**: This appears to be affecting links only once link styling has been set in the Global Settings. As long as it's not a link, it's find - but if it's a link we are unable to override the global CSS on a case-by-case basis.

**Comment by pixelicous** [comment]
i have errors throughout my webpage, tried regenerating css, clearing wp cache and nginx cache.. nothing..
global colors override almost all of my widgets colors, whether its header or text, the font and background are just wrong.

**Comment by Jehu** [comment]
We've problems with CSS also.

**Comment by shilo-ey** [comment]
I merged this issue with  #12363, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
