### ISSUE TITLE
3.0.7 - Heading Widget Won't Take CSS Color Value If It Is A Link - Global Settings Conflict?

### ISSUE THREAD

**Issue by badwebdev** [elementor/elementor#12487]
Same as other recently opened issue.

3.07, Hello, No other plugins, Nginx, etc.

If you make the text in a heading widget a link, you can't change it's color.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
