### ISSUE TITLE
Site Setting - Theme Styles - Button -> Typography Settings not apply to Hover state correctly

### ISSUE THREAD

**Issue by arshish1612** [elementor/elementor#12484]
Elementor Pro 3.0.4

Under Site Setting, Theme Styles, Button, if you change the typography settings, the button font changes however when you hover,  the updated font does not reflect and resets back to a default font. Since the typography settings are independent of normal and hover, the expected behavior is that the changed typography should also affect the hover state.

Disable default colors and fonts is enabled.

**Comment by arshish1612** [comment]
Closing this because I found a duplicate:
https://github.com/elementor/elementor/issues/12354

**Comment by feidaman** [comment]
I've just noticed this bug. I can apply non-global typography settings without problems, but equivalent global settings only apply to the NORMAL state, while the HOVER state remains unchanged.
