### ISSUE TITLE
elementor 3 issues [bug rant]

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#12498]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and of course might find duplicates...
- [x] The issue sadly still exists against the latest stable versions of Elementor free and pro.

## Description

first of all: i used to love elementor for its reliability and performance! totally.

sadly, this has changed drastically with the introduction of 3.0 and hasnt changed much to the better with latest el 3.07 and pro 3.04.
not only the worst update in the wordpress ecosystem i‘ve ever experienced - but nearly the worst one of all software since 30 years!

funny to weird things even on fresh, simple and clean installs - partially close to nightmare on existing sites.
and i still have absolutely no clue how someone can consider the actual scenario as „quite normal“ for a major update?!
seven plus corrections after more than three weeks and still going crazy.

- ongoing erratic behavior of fonts and colours. meanwhile the less in editor but still heavy on front end!
- loosing font settings without reason even if set by theme.
- out of sudden default settings of all kinds in numerous widgets present again.
- global settings in el -e.g. buttons- interfere with generatepress mobile menu.
- changes in editor not taking place on frontend even without any caching etc.
- ...

definitely not motivated anymore to hunt them all down, and even not to open ‚issues‘ here for every single one of them. sorry.
upon updating, things appear in places where you never would expect them ... its so sad and annoying. not to speak of crazy unnecessary time consumption an tons of strained nerves.
and even when using staging environment and such (although being glad do so) this is causing permanent headaches.
not one single site so far where the (intended) update went well and hassle-free. not one that i dared to bring life so far. thats crazy.

imagine youre setting up a book project with indesign; half way through, set up everything for layout and basics, lots of content inserted for building up - id suddenly kills all your setup and custom formatting.
or having lots of book projects that are suddenly breaking after software update?
how would you feel like?

imagine you have your car for inspection, getting an update for software and afterwards beginning to behave erratic and making you sweat because you (of course) dont feel save anymore... in addition the mechanic’s telling you „this is quite normal for a major update“. what would you think???

then comes the next knockout:
support.
response time more than one week and above regulary - since months.
first response almost always (99%) useless and obvious plain boilerplate or not read well. maybe not understood at all sometimes.
regulary needing two or three, sometimes more, approaches just to finally get to the point where those „sorry, but out of our scope“, „we dont offer this kind of support“ or anything alike things appear. 
best of all: constand guidance to post it here on github where is clearly stated "this ist not for support" ... wtf ...??
turning circles.
in the end lately almost always useless to spend the time writing things down ...

nearly deepest depths of support.
percentage of helpfulness going down steep into nowhere.
used to be good too - somewhere back in time.

maybe it is time for an additional developer edition if elementor is not willing to roll out better performance and knowledge to each and everyone (as its getting too big?). name it whatever, let it be the price doubled or tripled compared to the current ‚pro‘ - whatever. if this would guarantee reliability and real (!) support again as it used to - i would probably pay it.
but personally and quite frankly, things cant stay in their current state!
as an user from the early alphas on, as well as an early adopter of pro i am deeply disappointed to be honest.

**big wish: please stop all marketing and fancy stuff till at least christmas, no new features. sit down and make things going great again. and heal some little things too while doing so ...**

- show inherited values for responsive settings finally! this is a daily mess.
- let us hide all those premade templates to editors! completely makes no sense to restrict them to edit content only, but still they can load things they even should not see at all - especially if they‘re clients.
- let us hide google fonts in editor when (at least) using own custom fonts.
- complete portfolio with filter bar.
- fix that bad LCP thing.

...

just to name some of the easy and long overdue things. not the big ones.

by doing so, we all might have some chance for a real happy and merry christmas - even without any other gifts and snow and singing or whatsoever at all!

your reputation got some big dents lately and i think (fear) i am by far not the only one to be deeply concerned about whats going on these days and even more for the future ...
this might even not be the intention of your investors ...? (hopefully!)

so come on: simply ditch off those marketing hours for hunting of errors and go for sheer reliability and performance again. and afterwards be able to state with confidence (and truly) „we deliver“.

for the time being this is more than far from ideal ...
please just make me love elementor again!

just my 2 cents, thanks for reading.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bugs consistently.

## Environment

<details>
<summary>System Info</summary>
```
- any existing setup.
OR
- just el and pro.
- no added or fancy plugins.
- theme of your choice
- latest everything - wp, theme, el, php etc. etc.
- no caching
- just plain dirty install
</details>

**Comment by arielk** [comment]
Hi,

We do our best to fix various issues as a result of the latest update!
Regarding issues in colors and fonts you can follow this thread: https://github.com/elementor/elementor/issues/12363

Anyway thanks for your response, we fully understand your point, I hope we can bring back to you the experience you lost soon.

**Comment by dasigna** [comment]
... wow!

some of the fasted closures of all time?
i suppose this should tell us something...
