### ISSUE TITLE
Global Fonts HTML Codes visibility &naming revision

### ISSUE THREAD

**Issue by avikla** [elementor/elementor#12491]
Hi,

I have two suggestions:

1) Please make the color HTML codes in the global colors clearer. The HTML code shown is very pale and small. I attach a screenshot.

2) Can you add to the revision panel option to give it a specific name? A good example is version history naming scheme in Google Docs...

Avi

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
