### ISSUE TITLE
break down a long blog post/pagination post

### ISSUE THREAD

**Issue by wskxjtzq** [elementor/elementor#12490]
How to use pagination with Elementor page builder?

https://wordpress.org/support/topic/how-to-use-pagination-with-elementor-page-builder/

I encountered the same difficult problem. I found that this problem has not been resolved so far. Is there a workaround? My blog post is very long and really requires pagination.

**Comment by arielk** [comment]
You can learn more here: https://docs.elementor.com/article/101-posts
