### ISSUE TITLE
Color does not work on Divider patterns

### ISSUE THREAD

**Issue by swinggraphics** [elementor/elementor#12501]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Color style setting does not effect Divider patterns.

## Steps to reproduce

Set the Style of a Divider to anything other than Solid, Double, Dotted, or Dashed. Set Color in the Style tab.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Elementor 3.0.7 (elementor-3.0.8-20200912.1945)

**Comment by Sierrv15** [comment]
I have exactly the same problem, colors dont work at all in the divider element within Elementor Pro (3.0.5).

Please let me know as soon as it has been fixed or a solution is found.

Thank you very much in advance

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
