### ISSUE TITLE
Small Caps

### ISSUE THREAD

**Issue by swinggraphics** [elementor/elementor#12500]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Describe the solution you'd like**
Please add small caps in Typography palettes. Even though it's not a feature of text-transform, it could go in that dropdown because it is related to those options, and I don't think other font-variant options are used much.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.

**Comment by jonnymueller** [comment]
+1

**Comment by SophiaLF** [comment]
+1

**Comment by teamelliel** [comment]
+1
