### ISSUE TITLE
Finder incorrectly identifies pages created through Finder as a Post type instead of Page type.

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#12502]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When creating a new page via one of the two "Elementor" ways below...

1. Elementor Finder "Add New Page" function
<img width="317" alt="image" src="https://user-images.githubusercontent.com/8153796/93036884-eff7ab80-f5f5-11ea-879c-56d9750737c4.png">

2. Elementor Dashboard widget "Create New Page" function
<img width="430" alt="image" src="https://user-images.githubusercontent.com/8153796/93036856-e0786280-f5f5-11ea-981c-34eff422717b.png">

... later searching for that newly created page via Elementor Finder will list it but is incorrectly identified as a Post type instead of Page type. This occurs on fresh installs too in my experience. I also had a support case opened up about this a long time ago but I am reporting it here as I don't see it mentioned yet and I see it's still an issue today even though I reported it several months ago. Please see your support case system ticket under my email ID (dustin [at] d19.ca) with the subject titled "Re: Elementor Finder feature incorrectly identifies pages as posts, in most cases."

Notice in this screenshot the new page created using Finder called "Test" was later identified in Finder as a Post, despite there not being any posts in this test environment. 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/8153796/93037920-6eede380-f5f8-11ea-95de-8a9e268ec108.png">

Only when creating a page through the expected WordPress method (Pages > Add New) will it properly show as a Page type when searching for it in Elementor Finder. If a site has many pages and posts created via the Elementor-approved methods, this makes using Finder a burden when trying to locate perhaps a page and post that are identically named when Elementor Finder lists them both as Post type, for example.

## Steps to reproduce

1. Create a new Page via either one of the two options listed above. For the sake of this example, let's stick to the Finder and create a new page using the "Add New Page" function in Finder.
2. Title the page and publish it with the green Publish button in Elementor sidebar.
3. Use Finder to find the page that was just published in step two above. Notice it is listed but the type is incorrectly stated as Post instead of Page.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
<details>
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: (Ubuntu) v5.7.29
	PHP Version: 7.4.10
	PHP Max Input Vars: 1800
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://www.<domain>.<tld>
	Home URL: https://www.<domain>.<tld>
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 384M
	Permalink Structure: /%category%/%postname%/
	Language: en-CA
	Timezone: America/Vancouver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

== Active Plugins ==
	AuthLDAP
		Version: 2.4.2
		Author: Andreas Heigl <andreas@heigl.org>

	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Cloudron Managed WordPress
		Version: 1.0.0
		Author: Cloudron team

	Elementor
		Version: 3.0.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	MainWP Child
		Version: 4.1
		Author: MainWP

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	WP Mail SMTP
		Version: 2.3.1
		Author: WPForms

== Elements Usage ==
	

== Log ==
	
Log: showing 20 of 262020-08-27 21:59:06 [notice] System colors are disabled. nothing to do. 
2020-08-27 21:59:06 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-27 21:59:06 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-27 21:59:06 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-27 21:59:06 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-27 21:59:06 [notice] System typography is disabled. nothing to do. 
2020-08-27 21:59:06 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-27 21:59:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-27 21:59:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.3',
)]
2020-08-27 22:00:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.1',
)]
2020-08-30 15:10:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-09-02 22:26:44 [info] elementor::elementor_updater Started 
2020-09-02 22:26:44 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-02 22:26:44 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-02 22:26:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-02 22:26:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-02 22:27:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.1',
  'to' => '3.0.3',
)]
2020-09-06 11:25:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-13 14:12:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-13 14:25:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
</details>

**Comment by d19dotca** [comment]
This has had a PR for quite a while now but still not out yet with a fix. Any ETA on this fix?

**Comment by d19dotca** [comment]
Curious... @DorShahar will the fix that's being added to the next update (or is at least merged for release later) will it also fix up items it incorrectly identified before? In other words, when I created Pages with the Finder but it identified them as Posts, will that be corrected? Or will it be a fix that only works going forward and nothing retroactively?

**Comment by DorShahar** [comment]
Hi @d19dotca  and the rest,
The fix will be only for Posts/Pages/Landing pages etc' that been **created through the Finder**, by the "Add new".
This should work for existing sites. If there is a problem - you will able to report it to us in the Beta tread once it will be released. 

Therefore, I removed the tag of `status/merged` the problem above didn't solve yet. We will solve it. 

Thanks again, and sorry for the misunderstanding.

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by d19dotca** [comment]
Took over a year and a half since I reported it, but I appreciate that this is finally resolved! 👍
