### ISSUE TITLE
Feature Request  — Max-Width for text

### ISSUE THREAD

**Issue by Flipback8** [elementor/elementor#12503]
Please add Max-Width for text so that we can control the width of Headings and paragraphs.

**Comment by arielk** [comment]
This can be done using > advanced > positioning > width > **custom** in every widget

Thanks for your feedback!

**Comment by Flipback8** [comment]
I see that now but Why does it get rid of the bottom margin of the text? [https://snipboard.io/P0g87G.jpg](url)

**Comment by arielk** [comment]
When using custom width you need to set the margins separately.

Indeed, `max-width` is different from `width`, but this is the current solution to what you asked for.
