### ISSUE TITLE
3.8 Social icons not displaying correctly

### ISSUE THREAD

**Issue by captaincoo1** [elementor/elementor#12519]
I upgraded to Elementor 3.8 and the social icons in the footer are not displaying correctly. When I downgrade to 3.7 they appear correctly. It looks like some styles were changed between the versions and the parent div is displaying as block instead of flex.

Screenshots: 
![Screen Shot 2020-09-14 at 11 06 31 AM](https://user-images.githubusercontent.com/3680356/93116718-e401fd00-f67a-11ea-8171-5f4c9057cadb.png)
![Screen Shot 2020-09-14 at 11 05 35 AM](https://user-images.githubusercontent.com/3680356/93116725-e6fced80-f67a-11ea-96a8-93aec514ffcf.png)

**Comment by chkserv** [comment]
It now has a new setting called "Columns" so in your case, set it to 4

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.8.1

Feel free to update

Thanks!

**Comment by captaincoo1** [comment]
Thanks!
