### ISSUE TITLE
Version 3.0.8 Shape Divider for Sections Broken

### ISSUE THREAD

**Issue by mmdd76** [elementor/elementor#12517]
![Capture](https://user-images.githubusercontent.com/54521673/93113886-114cac00-f677-11ea-9cc8-8ff1c5c539d3.JPG)

Version 3.0.8 Shape Divider for Sections Broken.  Shape Divider settings do not show up on front end or editor.  Previous Shape Dividers no longer show up on front end.

**Comment by incircolo** [comment]
I have the same issue

**Comment by shilo-ey** [comment]
Can you share a link to your site please? a place that has this issue?

**Comment by inztinkt** [comment]
seeing the same issue across a number of sites since upgrading to v3.0.8

**Comment by mmdd76** [comment]
> Can you share a link to your site please? a place that has this issue?

https://cfvgadev.outreachmm.com/food-safety/

It's basically every page header image had a shape divider bottom.  Now disappeared and can't make new one.

**Comment by inztinkt** [comment]
Recreated issue on my own site for you @shilo-ey. 

Pre-updating:

![pre-update-elementor](https://user-images.githubusercontent.com/251348/93116260-0ac82f80-f68b-11ea-81da-a2265b0f0a32.png)

Post updating:

![post-update-elementor](https://user-images.githubusercontent.com/251348/93116311-187db500-f68b-11ea-82ed-9757e7c87324.png)

What is odd is that one of the shape divider stayed, whilst the rest got wiped.

**Comment by mmdd76** [comment]
Tested and I am able to create new shape dividers on new created sections and I am able to add shape dividers to other existing secitons.

But **the section that originally had the shape divider** I cannot add and it is broken.  @shilo-ey.

**Comment by chkserv** [comment]
Same issue here

**Comment by mmdd76** [comment]
**FIXED**: You now must select "Bring to Front" on all existing shape dividers and now they work!!

**Comment by chkserv** [comment]
@mmdd76 Thanks, that fixed it.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.8.1

Feel free to update

Thanks!

**Comment by incircolo** [comment]
Thanks.
v3.0.8.1 correctly fix the issue
