### ISSUE TITLE
WordPress Importer exporter not working with elementor

### ISSUE THREAD

**Issue by Stevemoretz** [elementor/elementor#12523]
## Description

When using WordPress Importer and exporter,on import the content gets filled by some stuff from the exported elementor page.(the content was empty before because elementor handles the stuff in a different way?)So now it doesn't.And things look weird.

## Steps to reproduce

Export all the pages and import the xml, now it happened to all your pages with elementor on them.

## Environment
Mac Os 10.15
Mamp pro 
Elementor 2.9.9
Elementor pro  2.9.5
WordPress 5.4.2

I already have modified the Importer a bit, so I can more to support elementor, please tell me how a regular post turns into an elementor post and how the data is saved.then I will be able to make it, with my own custom exporter and Importer.

Thanks in advance.

**Comment by udidol** [comment]
Which version of Elementor and which version of WordPress Importer are you using?

**Comment by Stevemoretz** [comment]
> Which version of Elementor and which version of WordPress Importer are you using?

Sorry I wasn't at my computer, now I did put the exact version numbers on the question.

Elementor 2.9.9
Elementor pro 2.9.5
WordPress 5.4.2

**Comment by Stevemoretz** [comment]
Found the solution.Had to update elementor to latest version and problem solved!
