### ISSUE TITLE
Ability to delete the default font options for standard css/html markup options

### ISSUE THREAD

**Issue by gravnetic** [elementor/elementor#12524]
I am not sure what your developers are thinking, but the W3C has clear markup for type.  I would like you be able to clear out these weird options for the type.

![screenshot](https://user-images.githubusercontent.com/475331/93151535-775a2300-f6b9-11ea-9a5f-0f932bb3ba35.jpg)

**Comment by shilo-ey** [comment]
Hi @gravnetic 


Although you can't delete these colors and fonts, you can disable them from being used automatically. 

Go to Elementor > Settings and check the boxes of "Disable default colors" and "Disable default fonts"

Once you'll do that they won't be auto assigned to widgets you dragged or will drag in your site.

Thanks

**Comment by dasigna** [comment]
... dont know why this is closed. as sure as the answer is not solving it :)

seems to be a valid request anyway - 'primary', 'secondary' etc. isnt any html definition and further on quite confusing.

would like to have them deleted too - or at least renamed.

**Comment by gravnetic** [comment]
Thank you @shilo-ey in the example above the settings for Elementor are set to Disable default colors and Disable default fonts.  

With these settings, I would expect these very unusual markup definitions to not show up at all in the Elementor UI.  If you could add an If/Else to make these visible or not would be awesome.
