### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Widget Image Carousel - Add padding in caption style (Merged with #21128) - [ED-10064]

### ISSUE THREAD

**Issue by incircolo** [elementor/elementor#12533]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's not possible to style padding caption in Image Carousel items. 

**Describe the solution you'd like**
Adding padding in Style / Caption visual editor.

**Describe alternatives you've considered**
Adding a custom css 

**Additional context**
By setting no space between the images, the caption texts will also be attached. This behaviour can be avoided adding a custom padding field.

**Comment by rodolphebertozzo** [comment]
Hi, I have proposed a PR to the Elementor teams about this, in the meantime, you can go through custom CSS to enable this, just type :
```
.elementor-image-carousel-caption {
margin-top: ;
}
```

**Comment by nicholaszein** [comment]
Hi there!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.19.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
