### ISSUE TITLE
Elementor role manager when set to "Access to edit content only" now BREAKS editor in 3.0.8.1

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#12545]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

After updating to 3.0.8.1 When setting a WP "editor" to have "Access to edit content only" in the Elementor _Role Editor_ it now BREAKS the page editor and just infinite loads showing a ton of JS errors in console.

https://imgur.com/5sQ2Y3z

Set a WordPress user as an editor, go to Elementor settings > Role Manager > Editor > set to "Access to edit content only" > log out and log in as the editor user and try to edit an Elementor page

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

Latest WP and Elementor versions, Astra theme

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
Thanks for your report, merge to https://github.com/elementor/elementor/issues/12521
