### ISSUE TITLE
Elementor Form - Select Dropdown Doesn’t Work on Firefox

### ISSUE THREAD

**Issue by TheJediNinja** [elementor/elementor#12543]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by TheJediNinja** [comment]
Only on Firefox - The dropdown select box is broken. I have tested across multiple sites and all have the same results. The select options are squished and don’t follow the styling, some text is white with a white background, and it is difficult to select and option as the box closes as soon as the mouse is moved. After testing on multiple devices I have also discovered the form in general is buggy and incompatible with Firefox. On iPad, it does not follow the styles. Button colors are white instead of the selected color.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

We also suggest adding a short video with the problem.
Without it, we simply can't help.

Thanks.

**Comment by thwentythree** [comment]
Hi, please create a custom form with options. Go to chrome, open the options field and enjoy the look you have created. Go to firefox and be sad about firefox not showing you the same design but a broken one that is barely readable.

**Comment by DorShahar** [comment]
Hi @
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
