### ISSUE TITLE
Changing Site Title + Tagline Breaks Elementor

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#12540]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Whenever we change the Site title or the tagline in Wordpress backend, it completely breaks Elementor.

Here is a video showing what happens: https://share.getcloudapp.com/Z4ukXe61

We have tried to regenerate CSS, permalinks, and server cache along with browser cache. We have had to restore from a backup.

This needs to be fixed asap as we cannot launch a site because of this.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
[system-info-gwebprod.wpengine.com-15-09-2020.txt](https://github.com/elementor/elementor/files/5227321/system-info-gwebprod.wpengine.com-15-09-2020.txt)

<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
``` 
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by VonJot** [comment]
Same happens when creating a Staging and alter the title.

**Comment by mcrowell** [comment]
+1 - I can confirm this is happening on my end also with Elementor 3.0.8.1

[system-info-wickydemo.com-16-09-2020.txt](https://github.com/elementor/elementor/files/5232165/system-info-wickydemo.com-16-09-2020.txt)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.9

Feel free to update

Thanks!

**Comment by VonJot** [comment]
Seems to work now. Thanks!

**Comment by stuartbrameld** [comment]
Works for us now, thanks for the quick fix 👍
