### ISSUE TITLE
User Roles dosn't work properly since the last Updates (3.0.8 and Pro 3.0.4) Elementor-Editor don't load 

### ISSUE THREAD

**Issue by Nedo21** [elementor/elementor#12549]
Ii noticed just one day ago that the user roles are not working properly. Some customers have complained that the editor does not load. The editor in the toolbar is not visible. You can only click on "edit with Elementor" via "edit pages". After the click the editor does not load. I went on troubleshooting and installed a user role plugin afterwards to create a new role. This did not change anything either. The editor only works for the admin role. So I started to downgrade the Elementor versions. Now it works again. I tested it on three other websites and it was the same problem everywhere. Also, after the downgrade you can see all widgets in the editor, even if you are only allowed to edit the texts.

**Comment by shilo-ey** [comment]
I merged this issue with #12521, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
