### ISSUE TITLE
Full document search and replace, including HTML codes

### ISSUE THREAD

**Issue by JosiahCarberry** [elementor/elementor#12548]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Make post editing more efficient and increase the quality of the resulting document, as compared to tedious manual and error-prone editing.

**Describe the solution you'd like**
Search and replace in all widgets of a single post, including the ability to replace with HTML character codes that cannot otherwise be entered. For example:
Search for "WordPress"
Replace with "Word&shy;Press"
All occurrences of "WordPress" in all widgets in the document would be replaced.
Note that there is no way to enter such codes as optional hyphens other than to select the Text tab of the widget editor.
Needless to say, search&replace can become very elaborate with all sorts of options. I am not necessarily looking for any special options (such as diacritic sensitive, capitalization sensitive, regular expressions, just in one widget, direction of search, etc.) 
The particular case I mention here concerns optional hyphenating of a document. But there is no limit to the sorts of s&r that might be useful, but only on a single posting basis.

**Describe alternatives you've considered**
The only alternative is to manually search and replace each string individually using the widget editor.
There are many search & replace tools, including various plugins, php scripts and the wp cli search-replace command. None of these allow the user to s&r on only a single post. 

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10766, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
