### ISSUE TITLE
Add PrintFriendly to list of options in Share Buttons widget

### ISSUE THREAD

**Issue by gmariani** [elementor/elementor#12541]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Simplified print version of current page, without needing to create a print style-sheet.

**Describe the solution you'd like**
Include an option to use PrintFriendly to print the page. So in the dropdown for options under Share Buttons there is already "Print" but it just triggers print(). What I'd like is another option to use the PrintFriendly service which is just as simple:

`
https://www.printfriendly.com/print?url={url}&title={title}
`

**Describe alternatives you've considered**
Using the PrintFriendly plugin (more overhead), but then i have to install another plugin and tweak the CSS to line it up with the rest of the social icons (more work). AddThis ( https://www.addthis.com/wordpress/ ) includes this feature, but it's a bloated social media plugin when all you want are a few share links.

**Additional context**
https://support.printfriendly.com/button/developer-questions/link-to-open-page-in-printfriendly/

**Comment by Aviad-Herman** [comment]
Hi,
Thanks for the suggestion.
We don't integrate third party solutions like the ones you mentioned but users are free to use them if they like.
I'm merging this request with #14630.
