### ISSUE TITLE
.elementor-inner, .elementor-row and .elementor-column-wrap are still here?

### ISSUE THREAD

**Issue by langhenet** [elementor/elementor#12558]
Hi,
I've updated to elementor 3.0.x on my staging enviroment to check the new (breaking) DOM changes, but I'm still seeing `.elementor-inner`, `.elementor-row` and `.elementor-column-wrap` elements.

Has the change been pushed to a future release?

**Comment by shilo-ey** [comment]
We added legacy mode for not damaging sites that uses 3rd party addons/external code.

If you want to enable the Optimized DOM option go to Elementor > Settings > Advanced tab > and switch Optimized DOM option to Enabled.

Thanks
