### ISSUE TITLE
Still seeing .elementor-inner, .elementor-row and .elementor-column-wrap

### ISSUE THREAD

**Issue by langhenet** [elementor/elementor#12557]
Hello,
I have updated my staging server with the new 3.0.x elementor release, to check the new DOM changes, but I'm still seeing the 3 div elements `.elementor-inner`, `.elementor-row` and `.elementor-column-wrap`.

Shouldn't those be gone?

**Comment by shilo-ey** [comment]
We added legacy mode for not damaging sites that uses 3rd party addons/external code.

If you want to enable the Optimized DOM option go to Elementor > Settings > Advanced tab > and switch Optimized DOM option to Enabled.


Thanks
