### ISSUE TITLE
Custom HTML

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#12556]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We have Custom CSS, so why not Custom HTML? I'm talking about plugin Head & Footer Code, which is great, but it would be really wonderful have this feature implemented in "Elementor way" and with support for WordPress Import/Export.

**Describe the solution you'd like**
So we have Custom CSS for every separate page and Custom CSS applied to all pages. Why not place here also Custom HTML? One box for HEAD Code and one for FOOTER Code. I don't think it takes too much work to implement it. But it would be very handy, universal and clean solution for insert e.g. Google Analytics tracking code, link rel="preconnect" and so on. What do you guys think?

**Describe alternatives you've considered**
Still using plugin Head & Footer Code, but "Elementor way" would be better.

**Additional context**
Head & Footer Code plugin global settings
![head-footer-code](https://user-images.githubusercontent.com/7617350/93349359-a72f3500-f837-11ea-849d-a1693d11d433.png)

Elementor is ready to insert Custom HTML
![page](https://user-images.githubusercontent.com/7617350/93349396-b6ae7e00-f837-11ea-863f-43df3bd8d8f9.png)&#8209;![global](https://user-images.githubusercontent.com/7617350/93349411-bb733200-f837-11ea-8981-fd1563c2b3f3.png)

**Comment by shilo-ey** [comment]
Hey @shimsa 

Thanks for this input!

I merged this issue with #10586, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

I can share that this is something that we are working on.

Thanks for your feedback!
