### ISSUE TITLE
Pop Up on Mobile Safari will not close

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#12564]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello - on mobile iOS Safari when initiating a pop up, clicking on the 'x' will not close the popup. I have to refresh the page to close the popup. This is not working as expected.

Here is video showing the issue: https://share.getcloudapp.com/Z4uk0oPZ

iPhone X - Updated Safari and iOS to newest version
Elementor, Wordpress on newest versions

Cleared caches, regenerated CSS

Website: https://gwebprod.wpengine.com/

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
[system-info-gwebprod.wpengine.com-16-09-2020.txt](https://github.com/elementor/elementor/files/5235440/system-info-gwebprod.wpengine.com-16-09-2020.txt)

</details>

**Comment by bforer** [comment]
I am having the same issue

**Comment by ewokee** [comment]
mine can't even open, iphone X. very strange things going on on ios devices in combination with elementor.

**Comment by lior-sh** [comment]
Hi @tickyboom,

Thanks for reporting, we have checked your site https://gwebprod.wpengine.com/ and we couldn't reproduce the issue. Feel free to reopen if the issue persists.

Thanks.
