### ISSUE TITLE
Steps form issues after update

### ISSUE THREAD

**Issue by mister-mst** [elementor/elementor#12569]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Hello, after the last updates (after the migration to 3.0) I have been able to verify in the contact form of my website, that the divider that separates the icons that represent the steps is out of square with respect to the icon.

[Here](https://share.getcloudapp.com/Qwu0pj81) you can see an image of the problem.

## Steps to reproduce

1- Create any page/template with Elementor
2- Add a form with steps
3- Add a divider width >0 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.24
	PHP Version: 7.2.33
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version:
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.0.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	Limit Login Attempts Reloaded
		Version: 2.15.2
		Author: WPChef

	Really Simple SSL
		Version: 3.3.5
		Author: Really Simple Plugins

== Elements Usage ==
	
	footer : 1
		heading : 1
		icon : 1
		nav-menu : 1
	header : 1
		icon : 2
		icon-list : 1
	popup : 2
		button : 2
		form : 1
		heading : 12
		icon : 4
		image : 4
		spacer : 2
	wp-page : 2
		animated-headline : 1
		button : 4
		flip-box : 4
		form : 1
		heading : 35
		html : 1
		icon : 2
		image : 9
		lottie : 1
		price-table : 3
		slides : 2
		spacer : 9
		text-editor : 1

**Comment by mister-mst** [comment]
The error persists in 3.0.11

**Comment by shilo-ey** [comment]
Can you please share the exported template of this form?

**Comment by mister-mst** [comment]
Sure :)

[elementor-5779-2020-10-01.json.zip](https://github.com/elementor/elementor/files/5312117/elementor-5779-2020-10-01.json.zip)

**Comment by shilo-ey** [comment]
Thanks

This issue doesn't occur in my website when importing your template.

I can see that in your site the value being added to the margin-top property is:
![image](https://user-images.githubusercontent.com/45009641/94833253-970e7c80-0417-11eb-8d5f-0d26d0419c30.png)



and in my site:
![image](https://user-images.githubusercontent.com/45009641/94833191-7fcf8f00-0417-11eb-9667-354801680846.png)


I searched the code of Elementor and no such value exists. 

Have you altered your version of Elementor Pro?

**Comment by mister-mst** [comment]
I don't understand what happens.

I install the latest version of Elementor ( Elementor Free 3.0.11 and Pro 3.0.5 ) on another WP site and the error persists. Whether I import the old template or create a new form.

![Captura de pantalla 2020-10-01 a las 18 15 20](https://user-images.githubusercontent.com/66515542/94835533-1c8f2e00-0412-11eb-956b-496b21d31e52.png)

**Comment by shilo-ey** [comment]
Hey @mister-mst 

Just imported your template:
![image](https://user-images.githubusercontent.com/45009641/95022126-f1107b80-067d-11eb-8ff9-0404effc7b81.png)

Here, again it looks fine.


Please share your site's link and we will examine the output CSS.

Please share the System info from this site as well.

Thanks

**Comment by mister-mst** [comment]
Sorry for the delay in responding.

I have deleted and reinstalled Wordpress and all the plugins that I had installed in it.

All plugins are official and unmodified.

The error continues.

System info:

[system-info-bepumpkin.com-06-10-2020.txt](https://github.com/elementor/elementor/files/5334973/system-info-bepumpkin.com-06-10-2020.txt)

Link: [my web](bepumpkin.com)

**Comment by lmpampaletakis** [comment]
I have issues with the alignment of the steps buttons... The previous and next are not aligned. Also this happens to progress bar too.
![Uploading Screenshot 2020-10-15 at 2.19.03 PM.png…]()

**Comment by DorShahar** [comment]
Hi @mister-mst , @lmpampaletakis 
Do you still having the problem?

**Comment by mister-mst** [comment]
> Hi @mister-mst , @lmpampaletakis
> Do you still having the problem?

Yes: 


![Captura de pantalla 2020-11-17 a las 18 22 30](https://user-images.githubusercontent.com/66515542/99424457-f8c07280-2901-11eb-9f51-fa82f09978e1.png)

**Comment by DorShahar** [comment]
Hi
This bug will be fixed in the Elemntor Pro v3.1.0 release.
Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
