### ISSUE TITLE
My popup form is redirecting my user to a /null page

### ISSUE THREAD

**Issue by damanjitsinghin** [elementor/elementor#12566]
Recently I faced an issue with my popup form I made by using Elementor-pro. I link my button to the dynamic tag of the popup form. If someone clicks that button popup form opens but after a second it redirects to a /null page for example if my page URL is domainname.com/test after clicking the button it redirects on domainname.com/test/null. You can see this issue by visiting [PGDM in digital marketing](https://dforceacademy.com/pgdm-in-digital-marketing/) and clicking the download syllabus button. I tried everything but I did not get any resolution.

**Comment by Todderz** [comment]
I have the same issue. I followed the demo in the youtube video to create a popup and linked it to a button using the toggle popup command. Click the button and the popup begins appearing but then a page blah/null appears.

If I open the link in a new tab, the pop up appears correctly, and once closed the button works normally and shows the pop up. Reload the page and the button resumes opening /null

**Comment by Todderz** [comment]
In my case there is a conflict with the Kadence theme.

In Kadence theme customizer > general > performance, there is a setting "Enable scroll to ID".

With that turned on, I get smooth scrolling to an anchor, but the popup toggle sends to /null.

The navigation to /null is triggered by 
anchorScrollToCheck 
in
wp-content/themes/kadence/assets/js/navigation.min.js

With "Enable scroll to ID" turned off, the pop up toggle works fine, but scrolling to anchors doesn't work properly, with incorrect page positioning (eg link to a specific heading and the page ends up in the wrong position with the targeted heading out of the top of the view)

**Comment by Todderz** [comment]
Related issue in Kadence - https://www.kadencewp.com/support-forums/topic/strange-behavior-null-404-page-returned-on-links-for-fly-out-menus/

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
