### ISSUE TITLE
Testimonials break Points not working correctly

### ISSUE THREAD

**Issue by shahjehan-wpbrigade** [elementor/elementor#12574]
Hello Child theme
[Break Points Not working correctly ](https://monosnap.com/file/FDX3hzJV7X59KQAhE0CYF0ZkQZHrEu)

**Comment by actionTurtle** [comment]
Well you need to give them more info... but yeah this still does not seem to be working... 

I think its that the break points got moved recently in the UI... If I update the break points in the site settings (new location) then nothing happens to the mobile and tablet preview sizes... They are still set at 365 and 768 not matter what I updated the break points too...

I think the front end CSS is pulling the break points from the preview sizes...

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
