### ISSUE TITLE
How do I globally set the padding for every section that I drag in?

### ISSUE THREAD

**Issue by CodeBradley** [elementor/elementor#12578]
I would like to add a 50px padding to every section that I create automatically. What's the best way to go about this?

**Comment by samheavyside** [comment]
As far as I'm aware, you cannot do this currently via the Elementor UI. In my opinion, this _should_ be manageable through the Site Settings panel. I am not sure why only "Typography", Buttons, Forms and Images are available.  I think consistency of the spacing of layout elements (sections, columns etc) is one of the most important aspects of web design. 

You _can_ manage spacing (and achieve this consistency) by creating custom CSS classes/variables and then apply those to each element, but if you aren't familiar with CSS (many elementor users choose elementor primarily because they don't want to learn code) then you are out of luck.

**Comment by dasigna** [comment]
.. besides custom css (which solves it only partly and inherits some risks upon elementor changes the way they handle this - as recently reagrding DOM reduction) you might try custom section templates to re-use.

personally using this a lot where you have repeated sections with same settings but different content.
downside: if you decide to change something you have to go through all sectons again - PITA.

so yes - global setting would be appreciated.
at least for 'column spacing'.

**Comment by wayheming** [comment]
@CodeBradley try to use this code for override section default padding values

```if ( ! function_exists( 'override_section_padding_control' ) ) {
	/**
	 * Add custom fonts to theme group
	 *
	 * @since 1.0.0
	 *
	 * @param Controls_Stack $control_stack The control.
	 */
	function override_section_padding_control( $control_stack ) {
		$control = Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), 'padding' );

		$control['allowed_dimensions'] = [ 'top', 'right', 'bottom', 'left' ];
		$control['placeholder']        = [
			'top'    => '50',
			'right'  => '50',
			'bottom' => '50',
			'left'   => '50',
		];
		$control['default']            = [
			'top'    => '50',
			'right'  => '50',
			'bottom' => '50',
			'left'   => '50',
		];
		$control['selectors']          = [
			'{{WRAPPER}}' => 'padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};',
		];

		$control_stack->update_responsive_control( 'padding', $control );
	}

	add_action( 'elementor/element/section/section_advanced/before_section_end', 'override_section_padding_control', 10, 2 );
}```

**Comment by CodeBradley** [comment]
Thanks for the code @wayheming, I'll give that a shot. And agreed that this and column padding should without a doubt be placed inside of the global settings area. This is one of the most time consuming aspects of Elementor for me personally when creating these websites in bulk, especially if I change my mind after some time which forces me to go through every single section on the entire website.

**Comment by CodeBradley** [comment]
@wayheming How can I set a different default padding for tablet & mobile?

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/965 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
