### ISSUE TITLE
Divider Widget Min-Height With Body Font (New to Elementor v3) BUG

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#12579]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The divider widget has a minimum height of 6. Using a custom font, it appears disabling the font on Google Chrome inspection tool in the body fixes the issue, but removes the font. Can this be looked into as this wasn't an issue in 2.9.14 & 2.10.3 pro. Had today decided to update to the latest version as the major issues looked to be fixed now. Cleared all cache and regenerated css.
Using Astra theme.

![Capture41](https://user-images.githubusercontent.com/55829113/93578732-95fc3a80-f995-11ea-8879-2b7202a0f51a.PNG)
![Capture42](https://user-images.githubusercontent.com/55829113/93578483-4a499100-f995-11ea-8b98-0501d843e410.PNG)
![Capture43](https://user-images.githubusercontent.com/55829113/93578486-4ae22780-f995-11ea-8142-f83493d0684d.PNG)
![Capture44](https://user-images.githubusercontent.com/55829113/93578481-49b0fa80-f995-11ea-8e52-fe2284fc727a.PNG)

## Steps to reproduce
Add custom font that's not Google Font library. Add divider widget to page, play with size from 1+ in size. Check results with inspection tool.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
```
</details>

**Comment by perks98** [comment]
Quick update. It doesn't have to be a custom font, used a Google font and the min-height is 6px, and this was on another site. So after updating the divider has a min-height of 6px. Not an actual attribute, it appears some fonts applied to the body make this happen.

**Comment by arielk** [comment]
Thanks for your report.

Merge to https://github.com/elementor/elementor/issues/12630
