### ISSUE TITLE
Learndash, woocoomerce memberships and the problem with the theme builder

### ISSUE THREAD

**Issue by campiotto** [elementor/elementor#12572]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I believed that there was a problem in the integration of LearnDash with Elementor, so I decided to transfer my project to woocommerce memberships and to my surprise I had the same problem, I will describe it now.

LearnDash
Elementor prevents pages from being protected by learndash if you remove all elements from the page in themebuilder.

WooMemberships
The exact same thing happens if you use the theme builder, I believe that reproducing the problem through woo memberships can help you understand what is going on.

## Steps to reproduce

1. Create a template in the template builder with a title at the top, a post content widget at the bottom and a footer text.

2. - Now go to your post, and add some content to appear inside the post content widget.

3. Create a filter with the_content function

`function filter_the_content_in_the_main_loop( $content ) {    
    if ( is_singular('memberships')) {
    	if (members_restrict($members_list)) {
		    return $content;
	}else {
			return $login_or_buy;
		   }
    }
}
add_filter( 'the_content', 'filter_the_content_in_the_main_loop', 1 );`

ps: Ps: i wrote this structured code but github is leaving it inline, sorry for that.

4. Results: 
The content created by the template builder will appear before this filter, I tried to add a priority of -1000 to it, but the pages of the theme builder keep appearing before.

The filter only works for the theme builder post content widget.

5. Horrible solution 
In place of the theme builder create templates and use them as shortcodes within the posts.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.

Thanks
