### ISSUE TITLE
Custom Breakpoints In The Legacy Mode

### ISSUE THREAD

**Issue by Aleksandr0114** [elementor/elementor#12580]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I change breakpoint https://prnt.sc/ujeoxh it is't working in the legacy mode. CSS File still has 1024 breakpoint https://prnt.sc/ujeq2g

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.0.6

Feel free to update

Thanks!
