### ISSUE TITLE
Add Media Library to Finder

### ISSUE THREAD

**Issue by awakekat** [elementor/elementor#12584]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would very much like to have the option to be able to press CMD+E and CTRL+E to be able to get to the WordPress Media Library. I am wanting to have a quick way to get there and am surprised that it is not in the finder as an option to get to. Please add the Media Library to the Finder, I am sure that is easy to add it as an option with the address ...wp-admin/upload.php

**Describe the solution you'd like**
I would very much like to have the option to be able to press CMD+E and CTRL+E to be able to get to the WordPress Media Library.

**Describe alternatives you've considered**
The only alternative is to hit CMD+E to get the Finder and type das=Dashboard open that in another tab and then click on Media and then click Library. That is a lot of clicking when it could be real easy as an option in the Finder to go directly to it.

**Additional context**
None

**Comment by bainternet** [comment]
@awakekat 

for now, you can use this snippet which utilizes the Finder API to easily add the media link there or any other link you would like:

```PHP
add_filter( 'elementor/finder/categories', function( $categories ) {
	$categories['settings']['items']['wp-media'] = [
		'title' => __( 'Media', 'text-domain' ),
		'icon' => 'image',
		'url' => admin_url( 'upload.php' ),
		'keywords' => [ 'media', 'upload', 'images' ],
	];

	return $categories;
} );
```

**Comment by awakekat** [comment]
Thanks so much for finding a solution to the problem I am having. Unfortunately, you assume far too much of me in thinking I know where to put that code. Could you give me instructions on where to put that code so that it would work?

**Comment by awakekat** [comment]
Hey so wouldn't it be easier to add that code into Elementor's Finder API in the next release, That would be awesome because I work on a lot of sites, and it would not only solve a pain point with me but I am sure other people would definitely benefit from it as well. Thanks

**Comment by d19dotca** [comment]
Yes this would be excellent. Also the ability to jump straight into Elementor Site Settings via Finder instead of needing to edit a page first. Filing a feature request for that too.

**Comment by rami-elementor** [comment]
@awakekat We have reviewed your request again and at this point this request looks like a "plugin territory".

Please check the developers docs:

https://developers.elementor.com/docs/finder/
https://developers.elementor.com/docs/finder/advanced-example/

Thank you.
