### ISSUE TITLE
Tooltips in page editor won't dismiss

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#12596]
Latest E, E Pro and Wordpress, fresh install

![image](https://user-images.githubusercontent.com/1435638/93694486-5ecf8a00-fb4b-11ea-9ed5-62cf36997d7f.png)

**Comment by arielk** [comment]
Thanks for reporting,

This behavior cannot be reproduced, please add information so we can fix it:

* **Prerequisites**.
* **Steps to replicate**.
* **Screencast**
* **System info**.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Without it we simply can't help.

Thanks
