### ISSUE TITLE
Documentation bug: Form Field "tel" validation - not working

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#12592]
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

The example for "tel" form field validation not working see [Elementor Documentation](https://developers.elementor.com/forms-api/)

## Steps to reproduce

Follow the current documentation in [https://developers.elementor.com/forms-api/](https://developers.elementor.com/forms-api/) for "tel" type field validation.

## Isolating/SOLUTION to the problem

Copy/paste issue answer in issue #7580

## Environment

Vanilla installation

**Comment by davext** [comment]
If we want a front end fix, I would recommend https://www.npmjs.com/package/libphonenumber-js It has this which works great in my React apps

```
// If the number is not "valid" but "possible".
parseNumber('(111) 111-1111', 'US', { extended: true }) ===
{
  country: 'US',
  phone: '1111111111',
  ext: undefined,
  countryCallingCode: 1,
  carrierCode: undefined,
  valid: false,
  possible: true
}
```

**Comment by rami-elementor** [comment]
We have updated the [Elementor Developers Docs](https://developers.elementor.com/)

You can find a new example for creating new "tel" form field at - https://developers.elementor.com/docs/form-fields/simple-example/
