### ISSUE TITLE
[Usability] Custom CSS tab, Add decorator to show CSS added

### ISSUE THREAD

**Issue by yorkfrog** [elementor/elementor#12594]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I have added custom CSS to a site, and then come back weeks/months later and can never remember where the CSS is defined.

**Describe the solution you'd like**
It would be great to be able to tell at a glance that Custom CSS code has been defined for a page.  Could some form of decorator be added to the "Advanced/Custom CSS" tab/name to indicate that custom CSS code has been defined for this page.  Similar to where an icon is turned blue when an attribute such as typography is defined for a page to override inherited defaults.

**Describe alternatives you've considered**
Often, I end up installing a "customer CSS" plugin so I can define CSS in one place and know where to find it.
I could also now use the Site Settings/Custom CSS for site wide CSS code.

**Comment by MichaelDarko** [comment]
This is a great idea! Not only for a page custom CSS but even better for a widget custom CSS.

I have to use custom CSS in almost every widget due to Elementor having very limited and inconsistent styling options.

It would be great to have some small indicator that custom CSS was used on the widget. 

If you write something to the custom CSS in the advanced tab - the indicator turns on. If the custom css field is empty, the indicator goes away.

**Comment by TomRaraAvis** [comment]
**+1** ×999,999,999

I think about this **all the time** for custom CSS of individual widgets. I hate digging through everything to find where custom CSS has been added, but I **LOVE** that we can define custom CSS with each widget individually. I've never taken the time to fill out a request; so, thank you for doing this! Image attached of what I imagine for placement of individual widget indicator if there is any code inside the Custom CSS area — a little grey circle in the navigator layers. Not too flashy or distracting, but enough to know something is in there.

![Navigator-CSS-Indicator](https://user-images.githubusercontent.com/1435355/93693891-ae726f00-fad3-11ea-8ce6-3e9c64b90a88.png)

**Comment by arielk** [comment]
Thanks everyone for the feedback!

But it has already exist in Elementor for a long time, you can learn more about the Navigator indicators here: https://docs.elementor.com/article/589-navigator-indicators
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1778512/94860285-858c9b00-043e-11eb-8de1-e1e187233bfc.png">
