### ISSUE TITLE
Site Settings > Buttons > Background Color not being applied

### ISSUE THREAD

**Issue by feidaman** [elementor/elementor#12598]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The button background color set globally in _Site Settings > Buttons > Background Color_ is ignored. Instead, the global "Accent" color is always used. If I try to clear the button's background color in the editor (not in the _Site Settings_), the background color cannot be cleared, and it's always set to global color "Accent". This doesn't happen in v2.x

_Dashboard > Elementor > Tools > General > Regenerate CSS_ does not fix this.

## Steps to reproduce

Self explanatory, see description above.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by feidaman** [comment]
Interestingly, I can't reproduce it anymore, though it was definitely happening consistently.

**Comment by justinstrohbach** [comment]
Same here with the global button text color.

**Comment by feidaman** [comment]
Buttons seem buggy in v3, I keep bumping into issues specifically with buttons.

**Comment by shilo-ey** [comment]
Hi @feidaman ,

Thanks for your input.

Elementor works in a way that you have several layers of design rules you can set, from the general to most specific:
1. Theme Style (basic HTML tags styling options, traditionally set by the theme)
2. Elementor default values
3. Elementor css based values
4. Elementor inline values


The Theme Style settings should apply only if no other setting is set to this specific control.

To allow you achieve your expexted behavior you will have to go to Elementor > Settings > Disable default colors.

Thanks
