### ISSUE TITLE
Add a WYSIWYG field type to Elementor Pro Forms

### ISSUE THREAD

**Issue by Alan-Jacobs** [elementor/elementor#12597]
Yes but it is closed.  https://github.com/elementor/elementor/issues/6139

## Prerequisites

- [See above ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like a new field type added to the Elementor Pro Forms widget. I need a field that can accept formatted text. Eactly like the field I'm using to type this in!

**Describe the solution you'd like**
A new field type added to the Elementor Pro Forms widget.
A WYSIWYG field type that implements the TinyMCE type editor would be ideal.
So I can either type or paste formatted text that includes Fonts, Colours, Sizes, alignments. Even better if it could also allow attachments.

**Describe alternatives you've considered**
I have seen the earlier Github request (closed ) which offers some code to do this. However as I am not a coder I don't underrstand how or where to add it. So of no use to me.
JetEngine provides just such a Form field - however I also need to use Dynamic fields which are provided by Dynamic Content for Elementor, and the Dynamic form fields are not supported in JetEngine.

**Additional context**
Given that Elementor provided the code required to achieve this, in the previous github request 6139, surely  it should be trivial to add to Elementor Pro Forms widget as a built in facility. This would be enormously helpful.

**Comment by arielk** [comment]
I have merged this to the original issue #6139 (reopened) so that we can pay more attention to this request.

Thanks for the feedback!
