### ISSUE TITLE
SSL for urls in CSS files

### ISSUE THREAD

**Issue by silver-wind-ua** [elementor/elementor#12593]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by silver-wind-ua** [comment]
Good day!

When Elementro store generated css files with style sheets it stores urls with http:// prefix without using enabled "HTTPS on" Server status! It's avoid browser show locked lock icon (and even more - Mozilla shows up "unsecure notice").

Can u check HTTPS status for your file-generator?

For now I've added "some toggle" to your code:

IN FILE "/wp-content/plugins/elementor/core/files/base.php"
IN FUNCTION "write()"
CODE:

public function write() {
if ( 'on' == $_SERVER['HTTPS'] ) {
    $_content = str_replace('http:', 'https:', $this->content);
}
else {
    $_content = $this->content;
}

return file_put_contents( $this->path, $_content );
}        

But u sometimes update this file what is normal )) so I need to update it for at least 10-15 sites too -- and it's not normal!
Help please!

**Comment by arielk** [comment]
It appears that something on your server is not configured correctly with SSL. No need to change anything in the code, we support SSL out of the box.
Try to check if your server configuration or ask your hosting service.
