### ISSUE TITLE
Animated Headline - rotating_text not compatible with Dynamic tags.

### ISSUE THREAD

**Issue by gsusI** [elementor/elementor#12607]
As the title says, in the widget `animated-headline` the field `rotating_text` doesn't accept `dynamic` content.

Could you please edit `animated-headline.php:150` from:

```php

		$this->add_control(
			'rotating_text',
			[
				'label' => __( 'Rotating Text', 'elementor-pro' ),
				'type' => Controls_Manager::TEXTAREA,
				'placeholder' => __( 'Enter each word in a separate line', 'elementor-pro' ),
				'separator' => 'none',
				'default' => "Better\nBigger\nFaster",
				'condition' => [
					'headline_style' => 'rotate',
				],
				'frontend_available' => true,
			]
		);

```

To:

```php

		$this->add_control(
			'rotating_text',
			[
				'label' => __( 'Rotating Text', 'elementor-pro' ),
				'type' => Controls_Manager::TEXTAREA,
				'placeholder' => __( 'Enter each word in a separate line', 'elementor-pro' ),
				'separator' => 'none',
				'default' => "Better\nBigger\nFaster",
				'condition' => [
					'headline_style' => 'rotate',
				],
				'dynamic' => [
					'active' => true,
				],
				'frontend_available' => true,
			]
		);

```

So it accepts dynamic tags as an input.

**I have made the change in my local version and it works perfectly fine, but obvioulsy as soon as you release a new version, if I update my copy my changes would be lost**

This change doesn't seem to affect `content_template()` or `render()`.

Thank you

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/4625 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
