### ISSUE TITLE
Transition time does not work for radial gradient background - Elementor 3

### ISSUE THREAD

**Issue by Derillo** [elementor/elementor#12606]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

**System:** 
Elementor 3.0.9, wordpress 5.5.1 - No error in console

**Details**
Set transition time does not work for radial gradient background
![imagen](https://user-images.githubusercontent.com/15325019/93766722-34360d80-fbed-11ea-9fe6-082d421ef1ce.png)

**Comment by MichaelDarko** [comment]
Unfortunately, you can't transition gradients in CSS. Elementor can't do anything about that.

**Comment by Derillo** [comment]
Thank you, closed then
