### ISSUE TITLE
Post title disappeared since v. 3.0

### ISSUE THREAD

**Issue by romspielplatz** [elementor/elementor#12605]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor is now at 3.0.9 and the problem with the missing post titles still persists. Generatepress support found
"Elementor left a mess on your CSS code. It’s saved in your cached wpfc-minified css.

```
.elementor-page-title, h1.entry-title {
    display: var(--page-title-display);
}
```
I’ve checked your site and the same element doesn’t have the .elementor-page-title class anymore.

You seem to be using WP Fastest Cache. Perhaps you can try Delete Cache and Minified CSS/JS and see what happens.

Alternatively, you can apply a workaround fix by applying `h1.entry-title{ display:block !important; }` on your custom CSS code. I believe this will instantly solve the issue but I’d still recommend fixing Elementor related mess first."

I followed all steps and only the workaround solved the problem. Anyhow, I believe Elementor must find out what happens, also for future versions and for having a clean code.

## Steps to reproduce

See sample on my [staging site](https://test.tourist-in-rom.com/en/rome-november/).
## Isolating the problem

- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.22
	PHP Version: 7.4.10
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://test.tourist-in-rom.com
	Home URL: https://test.tourist-in-rom.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child 02
	Version: 2.2.1.1545417839
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.4.2
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0

== Active Plugins ==
	Advanced Ads
		Version: 1.20.1
		Author: Thomas Maier, Advanced Ads GmbH

	Advanced Ads Pro
		Version: 2.9
		Author: Advanced Ads GmbH

	Advanced Ads – Code Highlighter
		Version: 1.0.3
		Author: Thomas Maier

	Advanced Ads – Responsive Ads
		Version: 1.9.2
		Author: Advanced Ads GmbH

	Advanced Ads – Ad Tracking
		Version: 1.20.3
		Author: Advanced Ads GmbH

	Akismet Anti-Spam
		Version: 4.1.6
		Author: Automattic

	amr shortcode any widget
		Version: 3.7
		Author: anmari

	Anywhere Elementor
		Version: 1.2.2
		Author: WPVibes

	Autoptimize
		Version: 2.7.7
		Author: Frank Goossens (futtta)

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Content Aware Sidebars
		Version: 3.13
		Author: Joachim Jensen - DEV Institute

	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Easy FancyBox
		Version: 1.8.18
		Author: RavanH

	Elementor
		Version: 3.0.9
		Author: Elementor.com

	Enhanced Text Widget
		Version: 1.5.1
		Author: Clever Widgets

	Float Menu Pro
		Version: 3.5.1
		Author: Wow-Company

	Fluent Forms
		Version: 3.6.51
		Author: Contact Form - WPManageNinja LLC

	GP Premium
		Version: 1.12.0-alpha.2
		Author: Tom Usborne

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Login No Captcha reCAPTCHA (Google)
		Version: 1.6.10
		Author: Robert Peake

	LuckyWP Table of Contents
		Version: 2.1.4
		Author: LuckyWP

	NextGEN Gallery
		Version: 3.3.17
		Author: Imagely

	Page scroll to id
		Version: 1.6.9
		Author: malihu

	PayPal Donation
		Version: 1.2.9
		Author: Scott Paterson

	Polylang
		Version: 2.8.2
		Author: WP SYNTEX

	Popup Maker
		Version: 1.11.2
		Author: Popup Maker

	Popup Maker - Scheduling
		Version: 1.1.1
		Author: WP Popup Maker

	Popup Maker - Scroll Triggered Popups
		Version: 1.3.2
		Author: WP Popup Maker

	Post Type Switcher
		Version: 3.2.0
		Author: John James Jacoby

	Q2W3 Fixed Widget
		Version: 5.1.9
		Author: Thomas Maier, Max Bond

	Rank Math SEO
		Version: 1.0.48-beta
		Author: Rank Math

	Restore Image Title
		Version: 1.5
		Author: Les Bessant

	Reveal IDs
		Version: 1.5.4
		Author: Oliver Schlöbe

	Sassy Social Share
		Version: 3.3.12
		Author: Team Heateor

	Show modified Date in admin lists
		Version: 1.2
		Author: Apasionados.es

	TablePress
		Version: 1.12
		Author: Tobias Bäthge

	TablePress Extension: DataTables Sorting plugins
		Version: 1.0
		Author: Tobias Bäthge

	TablePress Extension: Responsive Tables
		Version: 1.7
		Author: Tobias Bäthge

	Webcraftic Clearfy – WordPress optimization plugin
		Version: 1.7.4
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	Webcraftic Hide login page
		Version: 1.1.1
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	Webcraftic Robin image optimizer
		Version: 1.4.5
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	WP Fastest Cache
		Version: 0.9.1.0
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.5.9
		Author: Emre Vona

	WP Last Modified Info
		Version: 1.7.2
		Author: Sayan Datta

	WP Rollback
		Version: 1.7.1
		Author: Impress.org

	WP Show Posts
		Version: 1.1.3
		Author: Tom Usborne

	WP Show Posts Pro
		Version: 1.0-beta.1
		Author: Tom Usborne

	WP YouTube Lyte
		Version: 1.7.13
		Author: Frank Goossens (futtta)

== Must-Use Plugins ==
	assets-manager.php
		Version: 1.0.9
		Author: 

	Health Check Troubleshooting Mode
		Version: 1.7.1
		Author: 

== Elements Usage ==
	
	page : 84
		button : 41
		heading : 313
		html : 146
		image : 16
		read-more : 11
		shortcode : 256
		sidebar : 2
		spacer : -6
		tabs : 1
		text-editor : 521
		video : 18
	wp-post : 150
		button : -3
		heading : 493
		html : 227
		image : -76
		image-carousel : 19
		read-more : 44
		shortcode : 399
		sidebar : 1
		spacer : 1
		tabs : 1
		text-editor : 776
		toggle : 2
		video : -7
		wp-widget-wylwidget : 6
	wp-page : 33
		button : 107
		heading : 211
		html : 121
		image : 12
		image-carousel : 1
		read-more : 28
		shortcode : 136
		sidebar : 10
		spacer : 2
		text-editor : 236
		toggle : -3

== Log ==
	
Log: showing 20 of 342020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-25 20:18:37 [notice] System colors are disabled. nothing to do. 
2020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 20:18:37 [notice] System typography is disabled. nothing to do. 
2020-08-25 20:18:37 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 20:18:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-27 15:44:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-28 23:17:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-30 20:26:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-08-31 14:12:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-08-31 14:12:06 [info] elementor::elementor_updater Started 
2020-08-31 14:12:06 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-08-31 14:12:06 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-08-31 14:12:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-14 22:07:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.8.1',
)]
2020-09-20 20:39:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]

JS: showing 6 of 6JS: 2020-03-18 20:39:11 [error X 2][https://test.tourist-in-rom.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.6:31:225502] t is null 
JS: 2020-04-19 21:01:29 [error X 2][https://test.tourist-in-rom.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.7:31:161922] e.ui.form is undefined 
JS: 2020-05-14 19:51:53 [error X 2][https://test.tourist-in-rom.com/wp-content/cache/autoptimize/js/autoptimize_2bf48e8e75711d9c7aae69166e7a87f0.js:207:0]  
JS: 2020-08-02 17:25:04 [error X 1][https://test.tourist-in-rom.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.14:31:160243] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-08-25 22:22:57 [error X 13][https://test.tourist-in-rom.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.1:2:469677] this.container is undefined 
JS: 2020-09-06 18:45:38 [error X 2][https://test.tourist-in-rom.com/wp-content/cache/autoptimize/js/autoptimize_f3cfef26ec19a4a67ea24d8855723692.js:184:59541] r is undefined 

PHP: showing 3 of 3PHP: 2020-04-03 22:20:06 [notice X 48][/home/touris96/test.tourist-in-rom.com/wp-content/plugins/elementor/includes/template-library/sources/local.php::995] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-04-29 17:43:24 [notice X 5][/home/touris96/test.tourist-in-rom.com/wp-content/plugins/elementor/includes/api.php::160] Undefined index: pro_widgets [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-08 09:02:53 [warning X 1][/home/touris96/test.tourist-in-rom.com/wp-content/plugins/elementor/modules/safe-mode/module.php::124] rmdir(/home/touris96/test.tourist-in-rom.com/wp-content/mu-plugins): Directory not empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				

```
</details>

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!

**Comment by romspielplatz** [comment]
I tested with v.3.1.0 and the bug is NOT resolved.

**Comment by FederaikLudikon** [comment]
v.3.2.4 bug still NOT resolved.

**Comment by Dextyle** [comment]
v.3.11.0 I still have 
`--page-title-display: none;`

and my theme doesn't show the page title.
