### ISSUE TITLE
Image Box widget - allow image to stay on the left/right when on mobile

### ISSUE THREAD

**Issue by viveknath322** [elementor/elementor#12602]
Hi

Image Box widget is working fine on desktop but there is an issue when viewing from mobile.

If we set the image position to left or right and when viewed from mobile the image will be stacked to the top. A similar issue is happening with the icon box also.
Any workaround to keep the image to stay left even on mobile?

You can view the icon box issue here elementor/elementor#3040

**Comment by viveknath322** [comment]
I used the same code provided by @gerardreches for iconbox fix in the tread https://github.com/elementor/elementor/issues/3040 . Replaced icon with images. That's it.

`@media (max-width: 767px) {
    .elementor-widget-image-box.elementor-position-left .elementor-image-box-wrapper, .elementor-widget-image-box.elementor-position-right .elementor-image-box-wrapper {
        display: flex;
    }
    .elementor-widget-image-box.elementor-position-right .elementor-image-box-wrapper{
        flex-direction: row-reverse;
    }
    .elementor-widget-image-box.elementor-position-left .elementor-image-box-image {
        margin-right: 15px !important;
    }
    .elementor-widget-image-box.elementor-position-right .elementor-image-box-image {
        margin-left: 15px !important;
    }
}

/**To add a space between image and text**/

selector.elementor-widget-image-box .elementor-image-box-content {
    margin-left: 8px;
}`

**Comment by DorShahar** [comment]
Hi @viveknath322 
I'm glad you found a workaround. 

Closing this issue.

**Comment by jeffrschneider** [comment]
@DorShahar You closed the issue? Having a hack isn't the same as FIXING the issue. Please re-open and _actually_ fix it.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3040, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by heyhans77** [comment]
I realise that the image box widget for elementor doesn't change for mobile when you select align left.

You can enter the CSS below in the widget, under advanced tab and custom css:

/* 700px and smaller screen sizes */
@media (max-width:768px){

	/* Image box wrapper */
	.elementor-widget-image-box .elementor-image-box-wrapper{
		display:flex;
		text-align:left;
	}
	
	/* Image box content */
	.elementor-widget-image-box .elementor-image-box-content{
		margin-left:16px;
		
	}
	
}

Hope it works!

**Comment by JacobBannier** [comment]
Why is this closed? It hasn't been fixed. 

The Icon Box widget had the fix, but not the Image Box widget.

**Comment by vgstef** [comment]
I'm facing this problem now. This is a serious issue. We need a fix. If we need to come here to find a hack, that's a bug and not everyone will do this effort.

**Comment by JacobBannier** [comment]
@DorShahar Please can this issue be re-opened and FIXED. Thank you.

**Comment by gitomit** [comment]
Okay, so after 4 years, this problem is still not fixed for the 'Image Box'? Why even have the option in styling when it is still not working after 4 years... Please fix this problem

https://github.com/user-attachments/assets/e634bb67-8649-4003-a1d9-2fd95dbd398d

**Comment by leonuck** [comment]
Five - yes, FIVE - years, and the problem still persists! Please fix it.

**Comment by dennylai1990** [comment]
How the heck is this not fixed even after 5 years? The team prioritizing fancy new features without fixing simple things like this.

**Comment by kozzmen** [comment]
> How the heck is this not fixed even after 5 years? The team prioritizing fancy new features without fixing simple things like this.

Actually the issue is at least 7 years old and still no fix in Elementor's core! That's a joke! Used the code above and solved it but still wondering how the hack this is still not properly implemented...

**Comment by losvincent** [comment]
2026.03.28,elementor still not fix this error
and thanks for your css,it works fine on mobile.

> I realise that the image box widget for Elementor doesn't change for mobile when you select align left.
> 
> _You can Enter the CSS below within the widget, under advanced tab and custom css:_
> 
> ```
> /* 700px and smaller screen sizes */
> @media (max-width:768px){
> 
> 	/* Image box wrapper */
> 	.elementor-widget-image-box .elementor-image-box-wrapper{
> 		display:flex;
> 		text-align:left;
> 	}
> 	
> 	/* Image box content */
> 	.elementor-widget-image-box .elementor-image-box-content{
> 		margin-left:16px;
> 		
> 	}
> 	
> }
> ```
> 
> Hope it works!
