### ISSUE TITLE
Button stuck in hover state after click

### ISSUE THREAD

**Issue by feidaman** [elementor/elementor#12616]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

1. Insert a button
2. Set the button's 'normal' background color black and the hover background color to fuchsia (basically choose any two different colors)
3. Set the button link to, say, https://elementor.com, and set the link to open in a new window
4. Place mouse cursor over button. The button should turn fuchsia (the hover background color).
5. Click the button. Button background remains fuchsia as cursor is over the button area.
6. Release the button. Button remains fuchsia because the cursor is still over the button area.
7. Move the mouse pointer away from and off the button.

**Expected behaviour:** The button background turns black, since the mouse cursor is no longer over the button area. In other words, the 'normal' state background is restored.
**Observed behaviour:** The button background remains fuchsia even though the mouse cursor is no longer over the button.

The following GIF illustrates the problem:

![Elementor button](https://user-images.githubusercontent.com/11704566/93849340-3317e580-fcac-11ea-9f86-157d3dc0a71a.gif)

Thank you.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Wordpress 5.5.1
Elementor 3.0.9
Browser: Chrome Version 81.0.4044.138 (Official Build) (32-bit)
OS: Windows 10 Pro Version 2004 (OS build 19041.508)
Web server: Nginx
PHP version: 7.3.5
Database: MySQL 8.0.16

**Comment by michaelWalter** [comment]
This is not a bug, it's a feauture...from your browser.

The `:hover`-CSS is the same as for the `:active`-CSS. When you click a button an release the mouse outside of the button, the button will remain in the `active`-state. Therfore you'll keep seeing the "hover"-effect, but technically it is the "active"-effect

**Comment by feidaman** [comment]
> This is not a bug, it's a feauture...from your browser.
> 
> The `:hover`-CSS is the same as for the `:active`-CSS. When you click a button an release the mouse outside of the button, the button will remain in the `active`-state. Therfore you'll keep seeing the "hover"-effect, but technically it is the "active"-effect

The button is active only while the mouse button is being held down. If I release the mouse button AND motion the mouse cursor off the button, it's neither active not hovered, so the button should return to it's normal state. This is the way buttons work in all 'normal' websites. See, for instance, any button on this very GitHub page.

**Comment by arielk** [comment]
It's a `focus` state, not an `active`. and it's appan because we apply the `hover` style into the `focus` style to keep the styling of the page consistently and accessible when you navigate through the keyboard.

Thanks for your feedback

**Comment by Th3BiSh0p** [comment]
This is how a toggle button is supposed to behave, but every button is not a toggle button.

How can we workaround this "feature" ?
Thanks

**Comment by Rickd344** [comment]
This problem seems to occur in the Elementor button widget. I show screen shots in the attached file. It does not occur in the buttons widget that comes in the PowerPack Lite for Elementor plug in. The PP buttons widget provides multiple basic buttons that work well. The stuck in hover color also does not occur in the header button, only in the buttons added with the Elementor widget. It needs to be fixed. 

[Elementor Button Stuck in Hover Color.pdf](https://github.com/elementor/elementor/files/6123352/Elementor.Button.Stuck.in.Hover.Color.pdf)

**Comment by Risbo004** [comment]
> This problem seems to occur in the Elementor button widget. I show screen shots in the attached file. It does not occur in the buttons widget that comes in the PowerPack Lite for Elementor plug in. The PP buttons widget provides multiple basic buttons that work well. The stuck in hover color also does not occur in the header button, only in the buttons added with the Elementor widget. It needs to be fixed.
> 
> [Elementor Button Stuck in Hover Color.pdf](https://github.com/elementor/elementor/files/6123352/Elementor.Button.Stuck.in.Hover.Color.pdf)

Bro thank you so much for actually putting time and effort to help someone. You fixed my issue, and saved me of dozens of hours searching for a solution.

**Comment by bneuswanger** [comment]
Hover states should be hover states - not focus states. To treat both of those pseudo-classes the same is just plain lazy. 

It's not a great workaround, but for anybody reading this, there are a couple options if you can add custom CSS to your site. 

If your button color site-wide is consistent, you can just add this: 

.elementor-button:focus {
	background-color: [your-color-here] !important;
}

If your button color isn't consistent, you'll need to manually add classes to your buttons and apply the same hack to those classes. 

Elementor, please change how you structure the CSS so hover and focus states are not intertwined.

**Comment by spottykay** [comment]
Hi guys, here's the fix that worked for me:

Instead of targeting the class name elementor-button. You need to target elementor-button-link instead and include the active state i.e `.elementor-button-link:active{ css codes... }`
This worked.

BUT if your button widget has no link in it, then: `.elementor-button:focus{ css code..... }`

Let me know if this helps.

**Comment by marecki122** [comment]
> Hi guys, here's the fix that worked for me:
> 
> Instead of targeting the class name elementor-button. You need to target elementor-button-link instead and include the active state i.e `.elementor-button-link:active{ css codes... }` This worked.
> 
> BUT if your button widget has no link in it, then: `.elementor-button:focus{ css code..... }`
> 
> Let me know if this helps.

Works perfectly for me! Thanks. 

You have to remember that you cannot hover again the button if you don't click somewhere else on the site. But for me it's a good enough solution
