### ISSUE TITLE
Elementor Pro automatic background updates not working

### ISSUE THREAD

**Issue by euene** [elementor/elementor#12615]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

When automatic background updates for plug-ins are enabled, Elementor Pro will never get new versions installed automatically and will need to be manually updated by logging into wp-admin and clicking on the Update button. This happens with a valid and active Elementor Pro license. 

All other plug-ins, including the free version of Elementor are being autoupdated correctly in the background.

https://wordpress.org/support/article/configuring-automatic-background-updates/

`add_filter('auto_update_plugin', '__return_true');`

![elementor-pro-autoupdate](https://user-images.githubusercontent.com/6027160/93834423-8bd38800-fc84-11ea-994b-c96a0e6c0c17.png)

By using that code filter, since WordPress 5.5 that added autoupdating UI options in the admin, all plug-ins will get the "Auto-updates enabled" in the plug-ins list. This is not a new filter and has been working to enable plug-in autoupdates even before WP 5.5, now it just has an UI indication.

Elementor Pro autoupdates have never worked, before WP 5.5 and after WP 5.5.

I realise that Elementor Pro has a custom update server, not relying on the default WordPress.org update repository, however the Pro version should still support automatic background updates when they're enabled.

**Comment by lupo2021** [comment]
Hi arielk, will Elementor Pro get the auto update feature in the future? Thanks.

**Comment by d19dotca** [comment]
Interestingly I don't even have the "Auto-updates" feature for Pro, there is no text there, as if it's forced to be disabled. Auto-updates work fine for everything else though including free Elementor version, it's only a problem for Pro. Would love to see Pro have the ability to auto-update in the near future.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.2

Feel free to update

Thanks!

**Comment by sohailmumtaz123** [comment]
Everything gets updated automatically except Elemento Pro, and my website header gets broken because of it. That's why I disable all plugins auto-update.

**Comment by JimBTek** [comment]
we have the same problem. this is so annoying.  our clients sites break because elementor updates and is then incompatible with the older elementor pro.  @shilo-ey @arielk   we are looking at having to pay wpengine.com for an addon to have their service manually update plugins because of this.

**Comment by nicholaszein** [comment]
Hi @JimBTek.

This is very odd. We have received no reports of this issue after it was fixed. Can you please share your Elementor [System Info](https://elementor.com/help/hare-my-system-info/) here?

You can copy & paste it from your WordPress Dashboard > Elementor > System Info page, by scrolling all the way to the bottom. There is a field there with all the information ready to be copied.

From your comment, you're saying this is happening with an older version of Elementor Pro. Does this mean you don't have an active license of Elementor Pro? Can you explain if that is the case?

**Comment by JimBTek** [comment]
@nicholaszein 

- we manually update elementor and pro every release, it is not out of date
- we have a paid agency/enterprise account
- some of these installs are Multisite if it helps

[elementor system info 07-12-2023.txt](https://github.com/elementor/elementor/files/13604967/elementor.system.info.07-12-2023.txt)

<img width="691" alt="image" src="https://github.com/elementor/elementor/assets/1176347/d379d5fc-8ffe-4e89-869c-5549c90c021e">

**Comment by nicholaszein** [comment]
Ok, thank you @JimBTek.

I'll check with the team and will update you when I have more information.

**Comment by nicholaszein** [comment]
Hey @sohailmumtaz123.

Can you please share your Elementor [System Info](https://elementor.com/help/hare-my-system-info/) here?
You can copy & paste it from your WordPress Dashboard > Elementor > System Info page, by scrolling all the way to the bottom. There is a field there with all the information ready to be copied.

**Comment by nicholaszein** [comment]
Hey @JimBTek and @sohailmumtaz123!

We just released Elementor Pro version 3.18.2. Please check if the automatic update works for you.

Remember that it won't work if you have an older version of Elementor. It needs to be at least version 3.10. Preferably 1.18.X or 1.17.X.

Let me know if the auto-update goes as expected.

**Comment by JimBTek** [comment]
@nicholaszein so it seems like it does not work if:

- install/ activate on multisite network
- activate on some but not all sites in the network

The other use cases seem to work:

- single site
- multisite with 100% of sites participating

**Comment by nicholaszein** [comment]
@JimBTek just to be sure, you're reporting that the Auto-update of Elementor Pro won't work if:

1. You have Elementor Pro installed on a multisite installation. AND
2. The current version installed is greater than 8 minor versions ({major}.{minor}.{patch}; e.g.: Current version is between 3.18.1 and 3.10.0}. AND
3. You have activated the Elementor Pro license on the Main website inside the multisite network. AND
4. Elementor Pro is not active on all websites inside the network.

**Comment by JimBTek** [comment]
@nicholaszein yeah that is what I a being told by our WP dev. We ensured before Monday to do your prior instructions across 3 standalone installs, and 2 multisite networks.  1 multisite has 2 sites that both use elementor pro. 1 network has 2 sites and one has a hardcoded theme and the other uses elementor pro.  the standalones and the first multisite upgraded automatically, and the latter multisite did not.

**Comment by nicholaszein** [comment]
Ok @JimBTek,

thank you for confirming this. 🙏 

I'll pass it along to the team and check if this is something on our end, or if it might be something specific to WP-Multisite.

I'll get back to you as soon as I have any news. It might take a while given we are almost at the end of the year. But we will investigate this further for sure! 😉

**Comment by nicholaszein** [comment]
Hey @JimBTek, and @sohailmumtaz123!

We have just merged the fix for the issue you've reported, and it's planned to be released with Elementor Pro 3.22.0.

Thank you for your patience! 🙏

**Comment by nicholaszein** [comment]
Hey @sohailmumtaz123 and @JimBTek!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.22.0! 🥳 

Thank you so much for your patience and help resolving this issue. Elementor Pro should now update automatically for both single, and multisite setups! 💪 

If you are still experiencing this issue, please submit a 
Submit a new 

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), with details so we can help you better.

This issue will be permanently closed as it's too old and does not reflect the current versions of Elementor and Elementor Pro. 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
