### ISSUE TITLE
Button background button does not reset (gets set to global color 'accent')

### ISSUE THREAD

**Issue by feidaman** [elementor/elementor#12619]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

See the following GIF to see the steps to reproduce the problem, thanks

![Elementor button](https://user-images.githubusercontent.com/11704566/93856928-1387b980-fcba-11ea-8747-a8b2943461a1.gif)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Wordpress 5.5.1
Elementor 3.0.9 (free version)
Browser: Chrome Version 81.0.4044.138 (Official Build) (32-bit)
OS: Windows 10 Pro Version 2004 (OS build 19041.508)
Web server: Nginx
PHP version: 7.3.5
Database: MySQL 8.0.16

**Comment by arielk** [comment]
This is normal behavior when you use the default color / fonts by Elementor, you can change this by going to WP Admin > Elementor > Settings > Disable Default Colors/ Fonts

Thanks for your feedback

**Comment by feidaman** [comment]
> This is normal behavior when you use the default color / fonts by Elementor, you can change this by going to WP Admin > Elementor > Settings > Disable Default Colors/ Fonts

Toggling that setting seems to have fixed the problem—either that or a recent update. Since I got this working my life has been a lot easier :)

**Comment by jthouse27** [comment]
Disabling default colors solved this problem for me too! My buttons were stuck on the accent colors. At first, I thought this was an issue related to having duplicate Default Kits and I wondered if Elementor was even using any of my duplicate kits (created from a different bug). Very grateful for this solution. (Using the Hello Elementor theme).
