### ISSUE TITLE
New update popup does not close in mobile

### ISSUE THREAD

**Issue by P258tiwari** [elementor/elementor#12611]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by portrayaloflife** [comment]
+1

**Comment by bforer** [comment]
+1

**Comment by arielk** [comment]
Thanks for reporting,

This report is missing key information: 

* **Prerequisites**.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Without it we simply can't help.

Thanks
