### ISSUE TITLE
Facebook Embed Cover Photo

### ISSUE THREAD

**Issue by carlenmy** [elementor/elementor#12621]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The facebook embed doesn't have an option for a cover photo. 

This increases initial load time and make loading page jumpy as the facebook embed element tends to take so much longer than other elements. This is an issue when using anchor links as the videos will load after the page scrolls down which then moves the position. 

**Describe the solution you'd like**

I would like to have the option to load a cover photo just like video element which integrates with services like YouTube.

I would like to have 
**Describe alternatives you've considered**

Could use a popup instead... which is not a great solution. 

**Additional context**

Seems straight forward to me.

**Comment by DorShahar** [comment]
Hi @carlenmy 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
