### ISSUE TITLE
Question: How to get repeater data to use in another setting?

### ISSUE THREAD

**Issue by hector-farahani** [elementor/elementor#12626]
Is it possible to get a repeater data to use in another setting in a widget?

Imagine I have a form widget and I want to get form fields and let user to choose from added form fields in a select control.

**Comment by bainternet** [comment]
@hector-farahani 
please see this answer https://github.com/elementor/elementor/issues/12666#issuecomment-700615313 which is exactly what you are asking.

Hope this helps.
