### ISSUE TITLE
Divider no longer has font-size: 0

### ISSUE THREAD

**Issue by sunnyt7** [elementor/elementor#12630]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Before v3, Dividers had this CSS:

.elementor-widget-divider .elementor-divider {
    line-height: 0;
    font-size: 0;
}

In v3, they no longer have font-sizes. This is creating an extra spacing, causing the divider to be off-center. It also makes the spacing look off if you initially had it set up before v3.

Here is a screenshot of a Divider with a weight of 1... clearly taking up more than 1px due to the font-size.

![image](https://user-images.githubusercontent.com/5510344/93958868-74001080-fd25-11ea-8667-0bf30fe20cd3.png)

What it looked like before:

![image](https://user-images.githubusercontent.com/5510344/93958958-af9ada80-fd25-11ea-88a3-d65aa7fdd61f.png)

**Comment by mister-mst** [comment]
I have the same issue but in step contact form (between icons)

**Comment by perks98** [comment]
I have the same issue with all my sites with the divider widget since v3.0+. Definitely a must fix, I reported in #12579

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.0.11

Feel free to update

Thanks!
