### ISSUE TITLE
Elementor Search & Replace Text

### ISSUE THREAD

**Issue by standoutmarketingstudio** [elementor/elementor#12634]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Content and page creation will be much quicker.

**Describe the solution you'd like**
It would be great to have a section in Elementor where I can simply search for a word on the page or all word and replace it with another. 

**Describe alternatives you've considered**
The website I use this strategy with are all WP-Bakery sites. I can copy the code and use an online text replace tool to change just one word like "Marketing Agency England" To "Marketing Agency Scotland" and now the website page is all about marketing in scotland.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10766, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
