### ISSUE TITLE
Provide a method for easily cloning/duplicating a Theme Builder Site Part and Templates

### ISSUE THREAD

**Issue by joffff** [elementor/elementor#12649]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
* When creating a Site Part in Theme Builder I have to export and re-import a Site Part in order to create a clone.  
* When I want to clone a template Section I have to use a third-party plugin.

**Describe the solution you'd like**
* I would like to clone an existing Site Part within the Theme Builder.
* I would like to clone a template Section (and other template types) from within Elementor / WP Admin.

**Describe alternatives you've considered**
* To clone a Site Part I export it and re-import it.
* To clone a template I've used "Clone Post" plugins which work but they don't maintain the template's type.

**Comment by arielk** [comment]
You can just use copy/paste all content by clicking on the context menu (right click) in placeholder:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/1778512/94363899-23463a00-00ce-11eb-8376-02e5c832151e.png">

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/8582 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
