### ISSUE TITLE
Elementor opens widget tab/panel TAB_CONTENT first even if its not the first tab/panel in the widget

### ISSUE THREAD

**Issue by andreasnrb** [elementor/elementor#12646]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor opens tab/panel "Content" first even if its not the first tab/panel in the widget.

## Steps to reproduce
Create a widget, start a section with a custom tab before a section with the tab TAB_CONTENT.
Add widget to page, click on widget, tab Content is opened first even if other panel/tab is first.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Not required
```
</details>

**Comment by arielk** [comment]
Merge to https://github.com/elementor/elementor/issues/12658

**Comment by andreasnrb** [comment]
@arielk this depends on #12645, that needs to be fixed inorder for a fix to be applied in editor/component.js setdefaulttab from what I can tell. If not a fix in setdefaulttab you guys need to make the editorDefaultTab setting available in widget settings. But I suggest defaultTab should always be the first tab and not 'content' tab.
