### ISSUE TITLE
Customizer not working in Hestia since recent update

### ISSUE THREAD

**Issue by Qwooshy** [elementor/elementor#12644]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The customizer recently stopped working on my site using the Hestia Pro theme while Elementor is active. I am still using the same version of the theme, but have updated Elementor to the most recent version available. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Qwooshy** [comment]
Log:

[Wed Sep 23 12:46:29.974676 2020] [lsapi:error] [pid 852771:tid 140024305669888] [clientXXX:XXX.XXX.XXX:0] [host website.nl] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined method Elementor\\Utils::get_edit_link() in /home/website/domains/website.nl/public_html/wp-content/themes/hestia-pro/inc/customizer/controls/ui/class-hestia-pagebuilder-button.php:122\nStack trace:\n#0 /home/website/domains/website.nl/public_html/wp-includes/class-wp-customize-manager.php(4965): Hestia_PageBuilder_Button->json()\n#1 /home/website/domains/website.nl/public_html/wp-includes/class-wp-hook.php(287): WP_Customize_Manager->customize_pane_settings('')\n#2 /home/website/domains/website.nl/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)\n#3 /home/website/domains/website.nl/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#4 /home/website/domains/website.nl/public_html/wp-admin/customize.php(281): do_action('customize_contr...')\n#5 {main}\n  thrown in /home/website/domains/website.nl/public_html/wp-content/themes/hestia-pro/inc/customizer/controls/ui/class-hestia-pagebuilder-button.php on line 122\n, referer: https://website.nl/

**Comment by udidol** [comment]
Hi @Qwooshy,
This is a compatibility issue. 
The version of your theme seems to be incompatible with the Elementor 3.0 and up.
You need to update your theme to fix this issue, and if it is still not fixed, you should contact your Theme provider and ask them to fix the issue. From what I can see, the theme is using a method which has been deprecated since Elementor 2.0, and was fully removed from Elementor in version 3.0. 

Good luck!
