### ISSUE TITLE
Error with widget with custom tabs Error: Routes: `panel/editor/customtabname` not found.

### ISSUE THREAD

**Issue by andreasnrb** [elementor/elementor#12645]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor returns JavaScript error  Error: Routes: `panel/editor/customtabname` not found.
Before the release of version 3 you could add custom tabs to your widgets, after the release of 3.0 you can no longer do that unless you also have Controls_Manager::TAB_CONTENT tab in your custom widget.

## Steps to reproduce

* Add a new custom tab to Controls_Manager:add_tab
* Make a custom widget 
* Add a section with same keyword in a custom widget without a TAB_CONTENT section.
* Add the widget to the page using the editor
* Get error in console

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Not required for error
```
</details>

**Comment by arielk** [comment]
Merge to https://github.com/elementor/elementor/issues/12658

**Comment by andreasnrb** [comment]
@arielk The issue is from what I can tell that custom tabs are not registered as routes when added to a widget. Adding the custom tabs to editor/component.js defaultTabs() and they are registered correctly in component-base registerAPI. But I cannot find where the widget settings are actually loaded so that the custom tabs can be registered correctly using registerTabRoute. Hard to write a patch when one does not understand the code base :).
