### ISSUE TITLE
Don't request unused javascript and CSS files

### ISSUE THREAD

**Issue by andreasnrb** [elementor/elementor#12648]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Unnecessary JavaScript and CSS file downloads which slows down page loads for visitors.

**Describe the solution you'd like**
Decouple the the CSS and JS files so that they are only requested when there is actually widgets that use them on the page.

**Describe alternatives you've considered**
Deregistrering the files through code.

**Comment by MichaelDarko** [comment]
+1

This aspect should definitely be perfectly optimized for good performance.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/8572 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
