### ISSUE TITLE
gallery missing image title, caption outside of overlay

### ISSUE THREAD

**Issue by anybany** [elementor/elementor#12641]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Pro Gallery Widget missing title, caption, description below image only on hover/overlay

[https://github.com/elementor/elementor/issues/11378#issue-618720748](url)
[https://github.com/elementor/elementor/issues/9200#issue-498865130](url)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11378, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
