### ISSUE TITLE
Elementor completely broken after URL change in production

### ISSUE THREAD

**Issue by pixelicous** [elementor/elementor#12659]
Elementor pro user here (most updated version)

## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

I have replaced my site url, from X.domain.com to www.domain.com since then nothing works, not css and not images.
I kept the same servers, my web and db server are the same, only the url has changed.

I have followed the guide, and did it correctly.
I used the replace URL tool, I regenerated the CSS, flushed the cache of wordpress/elementor/nginx
I tried to do a small update and save and do the process again, but still the styling is completely off and no background images at all.

The weird thing is that in the editor everything looks completely normal

After i replaced the URL using elementor tool it showed me how many rows were affected.
I tried doing this after by SSHing into the server and using wp CLI together with elementor, same problem.

If i change the embedding mode to internal it works, if i replace it back with external it doesnt work.

This is a production server, i do not wish to use internal embedding.

## Steps to reproduce
Replace your domain url
Go to elementor settings, replace url in the tool, regenerate css, flush cache

## Environment

Operating System: | Linux |  
-- | -- | --
Software: | nginx/1.19.2 |  
MySQL version: | (Ubuntu) v5.7.31 |  
PHP Version: | 7.4.10 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by pixelicous** [comment]
Ok i solved my issue, this should be in the guide, everything looked like it was SUPPOSED to be ok.
Nothing in the style changes could have made this work so i just changed one of the pages' image to the same image.
All of the site is now online again

**Comment by tamelander** [comment]
I have the same problem. Images didn't show. I also had to open a page in Elementor and re-select the images. 

Why can't Elementor store its urls in the common Wordpress way?
