### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Chetan11-dev** [elementor/elementor#12668]
The structure of how elementor is laid out Is very clean and simplistic which is very good. 

I am trying to create a web builder that could output html ans css I thought of taking inspiration about how element are laid out in the panels and thier properties and tabs like Layout, Style, Advanced
Is it okay in case i took inspiration from elementor editor about the side panel?

**Comment by arielk** [comment]
Hi, 

Elementor is an open source editor under GPL license. Feel free to take inspiration, give credit and make sure you abide by the GPL rules. 

Don't forget to share with us your work it will be interesting to see the result :wink:
