### ISSUE TITLE
regen css and cli wp elementor flush_css doen't always work

### ISSUE THREAD

**Issue by jaemmer** [elementor/elementor#12663]
I noticed that if a site is having issues with the new global color setup that came out in v3 that you have to regen the css to fix. The issue is that if you admin UI it doesn't work until you also visit a page that needs it. and if you do it from the wp cli with the 'wp elementor flush_css' command it never fixes the issue

**Comment by lior-sh** [comment]
Hi @jaemmer,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* **Isolating the problem**.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
