### ISSUE TITLE
cli error when doing wp option update blogname

### ISSUE THREAD

**Issue by jaemmer** [elementor/elementor#12662]
when executing via the CLI
wp option update blogname Test

I get the following

Fatal error: Uncaught Exception: Access denied. in /home/customer/www/iodemosite07.com/public_html/wahoorentals.com12/wp-content/plugins/elementor/core/settings/page/manager.php:105
Stack trace:
#0 /home/customer/www/iodemosite07.com/public_html/wahoorentals.com12/wp-content/plugins/elementor/core/base/document.php(1214): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, 812)
#1 /home/customer/www/iodemosite07.com/public_html/wahoorentals.com12/wp-content/plugins/elementor/core/base/document.php(609): Elementor\Core\Base\Document->save_settings(Array)
#2 /home/customer/www/iodemosite07.com/public_html/wahoorentals.com12/wp-content/plugins/elementor/core/kits/manager.php(188): Elementor\Core\Base\Document->update_settings(Array)
#3 /home/customer/www/iodemosite07.com/public_html/wahoorentals.com12/wp-content/plugins/elementor/core/kits/manager.php(262): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option('site_name', 'Wahoo Party Ren...')
#4 /home/customer/www/iodemosite07.com/public_html/ in /home/customer/www/iodemosite07.com/public_html/wahoorentals.com12/wp-content/plugins/elementor/core/settings/page/manager.php on line 105
Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.

**Comment by christoferw** [comment]
We have the same issue when creating a new wordpress site-instances at a wordpress multisite using wpultimo.

**Comment by michaelWTF** [comment]
Same Problem here
Running `wp option update blogname micha` results in this problem:
```
PHP Fatal error:  Uncaught Exception: Access denied. in /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/settings/page/manager.php:105
Stack trace:
#0 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/base/document.php(1218): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings()
#1 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/base/document.php(613): Elementor\Core\Base\Document->save_settings()
#2 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/kits/manager.php(186): Elementor\Core\Base\Document->update_settings()
#3 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/kits/manager.php(274): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option()
#4 /var/www/clients/client5/web63/web/michas-test/wp-includes/class-wp-hook.php(289): Elementor\Core\Kits\Manager->Elementor\Core\Kits\{closure}()
#5 /var/www/clients/client5/web63/web/michas-test/wp-incl in /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/settings/page/manager.php on line 105
Fatal error: Uncaught Exception: Access denied. in /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/settings/page/manager.php:105
Stack trace:
#0 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/base/document.php(1218): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings()
#1 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/base/document.php(613): Elementor\Core\Base\Document->save_settings()
#2 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/kits/manager.php(186): Elementor\Core\Base\Document->update_settings()
#3 /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/kits/manager.php(274): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option()
#4 /var/www/clients/client5/web63/web/michas-test/wp-includes/class-wp-hook.php(289): Elementor\Core\Kits\Manager->Elementor\Core\Kits\{closure}()
#5 /var/www/clients/client5/web63/web/michas-test/wp-incl in /var/www/clients/client5/web63/web/michas-test/wp-content/plugins/elementor/core/settings/page/manager.php on line 105
```

**Comment by robgorrie** [comment]
Confirmed.  Same problem using NS CLONER via API.  Used to work no problem but the line 105 in /wp-content/plugins/elementor/core/settings/page/manager.php now checks for editor permissions on an Elementor post in wp_posts table called 'Default Kit'.  When cloning as the system there is no user so it fails 

Commenting out lines 105-107 (not a solution) returns our cloning to normal

**Comment by DorShahar** [comment]
We released a fix for that.
Closing the issue.
