### ISSUE TITLE
Ability to name sections in the navigator.

### ISSUE THREAD

**Issue by mario312** [elementor/elementor#12677]
Hi,

Would be nice to be able to add reference names the sections in the navigator.

**Comment by arielk** [comment]
You can edit it by double-click on the name of any element.

![name](https://d33v4339jhl8k0.cloudfront.net/docs/assets/573acfa69033602af6969ed2/images/5b83b43a2c7d3a03f89e232a/file-iVIOXVjAAc.gif)

Thanks
