### ISSUE TITLE
wp-admin/elementor-app Page Not Found

### ISSUE THREAD

**Issue by Creativenauts** [elementor/elementor#12676]
Updated to newest version of elementor pro and now the theme editor doesn't work.

"wp-admin/elementor-app"

<img width="478" alt="Screen Shot 2020-09-28 at 12 35 50 PM" src="https://user-images.githubusercontent.com/4481041/94460423-b642ab00-0186-11eb-8857-1b3956f1d943.png">

Also noticed that there are two "theme builder" tabs showing within the admin panel now.

<img width="331" alt="Screen Shot 2020-09-28 at 12 36 39 PM" src="https://user-images.githubusercontent.com/4481041/94460495-cf4b5c00-0186-11eb-90b3-dfa6b01c8744.png">

**Comment by shilo-ey** [comment]
The duplicate Theme Builder items show up when Elementor Pro is not updated to the latest version.

Please update Core and Pro to the latest versions and this should work fine for you.

Thanks.

**Comment by Creativenauts** [comment]
Both are updated to the newest version, however I did find that another plugin was causing the issue. I have reached out to the plugin developer and they are working on an update to address the issue.

**Comment by thecreativeoffices** [comment]
> Both are updated to the newest version, however I did find that another plugin was causing the issue. I have reached out to the plugin developer and they are working on an update to address the issue.

I'm having this problem now -- not with duplicate Theme Builder links, but with /elementor-app generating a 404. Which plugin was causing the conflict for you?
