### ISSUE TITLE
thankful email for users after submission

### ISSUE THREAD

**Issue by fatima-ksm** [elementor/elementor#12675]
How can I send an email thankfull for users after submission on elementor pro form?
I tried to use email 2 and put in the field of To: [field id="emai"] but it dosent worked!

**Comment by d19dotca** [comment]
Not sure if you literally used [field id="emai"] but you are missing the "l" at the end, that could be as simple as that for why it's not working. But it definitely works for me in my testing, so I don't think this is a feature request nor defect in the product, it's likely just how you've configured it. Perhaps attach some screenshots so we can figure out what's incorrectly configured.

**Comment by fatima-ksm** [comment]
yes thanks its worked
