### ISSUE TITLE
Widget post share buttons

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12679]
Added an option to be able to directly display share buttons in the post widget near the metas

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
