### ISSUE TITLE
no color preview for global colors

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#12684]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

new bug since latest versions 3.0.10 / 3.0.5
selection for global colors in editor doesnt show color preview anymore:

![elementor-global-colors](https://user-images.githubusercontent.com/22448174/94540479-cf129580-0246-11eb-999c-078919a200ed.PNG)

this is what it first was, now it looks like this:

![elementor-global-colors-unset](https://user-images.githubusercontent.com/22448174/94540588-e81b4680-0246-11eb-846b-096be43886ba.PNG)

theres no way to solve this and even exist with only elementor and basic theme active

## Steps to reproduce

just appeared lately.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently.

## Environment

<details>
<summary>System Info</summary>
```
only elementor latest version elementor and any theme active

</details>

**Comment by lior-sh** [comment]
Hi @dasigna,
Thanks for reporting, we couldn't reproduce the issue.
Can you please record a video that describes the issue by Loom extension?
Thanks.

**Comment by dasigna** [comment]
@lior-sh - to be honest, i dont know what to show via loom to make it more clear ... :)

simply setting up global colors which works fine and they're showing up.
as soon as trying to select one of those within any widget settings i am experiencing the above.

but just a few minutes ago i discovered a glitch that seems to be related with dynamic.ooo (within tax archives).
i am not shure if this belongs to the same as it was the same even with all widgets disabled...

suggestion: i will try to follow the issue further and setting up a dev site if it is persisting (i fear so) on which you might chase it further down on occasion.

**Comment by lior-sh** [comment]
Great thanks! @dasigna

**Comment by dasigna** [comment]
follow-up JFYI:

... meanwhile tracked it down and is definitely some glitch with REAL MEDIA LIBRARY PRO.
no other plugins etc involved.
opened a ticked there - lets see what they say.
