### ISSUE TITLE
Bug Elementor with BetterDocs plugin

### ISSUE THREAD

**Issue by Obitech96** [elementor/elementor#12682]
Hi there
When install BetterDocs plugin on my website i can't work with Elelementor because it doesn't charge up... so i can see the left column of wordpress but with a foggy layer and i can't click anything....
all on my system is updated and so i have no idea what is the problem....
i saw that betterdocs isn't the only plugin that take me this bug...
i hope someone can help me 
thanks a lot to all community 
Marco

**Comment by lior-sh** [comment]
Hi @Obitech96,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
