### ISSUE TITLE
Show/Hide for Logged In Users

### ISSUE THREAD

**Issue by Hosting-Mate** [elementor/elementor#12697]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have certain buttons that I would only like visible for logged in users.

**Describe the solution you'd like**
A simple enable button that states "Show for logged in users only". I would recommend inserting it in the "Advanced" settings somewhere so all items could use the feature. (Maybe suggest creating a new section called "Users" for future user-related features?)

**Describe alternatives you've considered**
1) Using CSS such as `display:none` or `visibility:hidden` via a PHP script, however anyone with web knowledge could sneak past this one.
2) Using only an item ID or class and PHP could be another work around, however now it is getting in to the more **complex** side that normal everyday clients wouldn't be able to understand/work.
3) Using the aforementioned CSS via jQuery or JavaScript could achieve the same result, however is still penetrable to web-savvy people.

**Additional context**
Attached is a quick rough design for what it may look like!

Could even add the ability to disable buttons for logged out users, so it is still visible but disabled! And have an option there to change the `title` attribute to state whatever the user types in! (E.g. "Enable by logging in or signing up")

![Screenshot (21)](https://user-images.githubusercontent.com/23144026/94652879-0ca61a00-033e-11eb-869f-5fa4240f3e91.png)

**Comment by bainternet** [comment]
I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
