### ISSUE TITLE
RankMath SEO stops Pro Gallery (Multiple Galleries) from displaying.

### ISSUE THREAD

**Issue by samheavyside** [elementor/elementor#12696]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Using the Elementor Pro Gallery (Multiple Galleries Mode). The default (first) Gallery doesn't display on page-load when RankMath is active.

## Steps to reproduce

I have a page created using Elementor which incorporates the Elementor Pro Gallery widget ((Multiple Galleries Mode - 3 Sub Galleries)

All works fine.

I installed RankMath (version 1.0.48.1)

Now the default gallery (First in the list) doesn't display on page-load. The other two display as per normal (when the tab headings are clicked), but the first one doesn't display, even when I switch to and from the other galleries.  Have tried adjusting the "Lazy-Load" setting, but the display issue persists, regardless. 

If I disable the RankMath plugin, normal behaviour is restored. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

##Screenshots

###Elementor Pro Gallery Settings

<img width="439" alt="Screen Shot 2020-09-30 at 3 04 58 pm" src="https://user-images.githubusercontent.com/4188265/94646949-96e68200-032e-11eb-943f-59f72d6829fc.png">

### Frontend (RankMath Disabled)
![Screen Shot 2020-09-30 at 3 06 33 pm_opt](https://user-images.githubusercontent.com/4188265/94888907-acd47e00-04b9-11eb-913f-7c9f01890c99.png)

### Frontend (RanthMath Enabled)
![Screen Shot 2020-09-30 at 3 05 36 pm_opt](https://user-images.githubusercontent.com/4188265/94888915-b9f16d00-04b9-11eb-8356-f2149f61b6d9.png)

**Comment by ludekcerny** [comment]
Hello,

I have exactly the same problem, but in my case there are other prerequisites for reproducing the error.

- [ ] The Gallery widget must be on the page a**long with other sections** and **not the first** on the page

Simple page with just the Gallery widget works well, but more complex pages with other sections suffer from this issue.
And it doesn't matter if I use default theme or Hello Elementor, the behavior is the same

![zsbor woop design_elementor-1316_annotated](https://user-images.githubusercontent.com/43381140/96573352-4e3b3c80-12ce-11eb-9ea2-d41bc61c3afb.png)

I also reported this problem to the RankMath support: https://support.rankmath.com/ticket/elementor-pro-gallery-conflict-2/.

**Comment by rami-elementor** [comment]
@samheavyside @ludekcerny 

Is this issues still relevant?

**Comment by ludekcerny** [comment]
> @samheavyside @ludekcerny
> 
> Is this issues still relevant?

Hi Rami, 
according to my recent tests, I was no longer able to reproduce this error.
