### ISSUE TITLE
Named layers in the navigator palette

### ISSUE THREAD

**Issue by ausdemnichts** [elementor/elementor#12699]
If you have many sections on one page, it is very difficult to select the right layer you are looking for in the Navigator palette.

If the CSS ID were on the label it would be much clearer.

I
<img width="1256" alt="Navigator - Palette mit Label" src="https://user-images.githubusercontent.com/28951234/94663844-6f7dbe00-030a-11eb-9e6f-629c736ffa51.png">

**Comment by DorShahar** [comment]
Hi @ausdemnichts
First of all - thank you for your feedback.

The ids are auto-generated by default, which will lead to unclear naming in the navigator.
Our best proposal is to continue to declare the name in the navigator, as you did.

**Comment by ausdemnichts** [comment]
Hello @DorShahar,

it would be difficult to photoshop every Elementor view. 🙂 it’s not possible to name the layers in Elementor. But that would also be a solution.

In my suggestion the ID would only be displayed in the Navigator palette if the user gave it a name and not the generic one.
