### ISSUE TITLE
Add integration with SendFox on Elementor Pro

### ISSUE THREAD

**Issue by vs999** [elementor/elementor#12707]
Hello, 
could you please add integration with SendFox on Elementor Pro? 
SendFox says that they have an API ready and they are waiting for Elementor to implement it on their system. 

## Prerequisites
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can not use SendFox with Elementor Pro

**Describe the solution you'd like**
add integration with SendFox on Elementor Pro

**Describe alternatives you've considered**
None because I need the integration to make it work

**Additional context**
![Screen Shot 2020-09-30 at 12 44 06](https://user-images.githubusercontent.com/66743125/94744401-33357680-0379-11eb-9ba6-5ff796fbff35.png)

**Comment by bainternet** [comment]
Duplicate of #10975
