### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12704]
Since the new organization of the "readme" of your Github, we no longer have access to the changelog as easily as scrolling. So I wanted to know if you were planning to create a special page for the changelog on the Elementor website like you did for Elementor pro?
Also, I think you forgot to mention the correction of the copy and paste issue in version 3.11 or this issue is not completely solved yet?

**Comment by shilo-ey** [comment]
Hi @rodolphebertozzo 

You have a sharp eye for changes :)

As Elementor grows, our changelog grows as well. We think that GitHub repository is not the best place to store all of that log, and you are still able to find it quickly in the [WordPress repository page](https://wordpress.org/plugins/elementor/#developers). We will consider adding a dedicated page for the changelog for Core versions as well.

Regarding the correction of Copy/Paste - it's not there yet. we need to finalize some more issues we discovered in our tests.

Thanks
