### ISSUE TITLE
`hide_title` page setting applies `--page-title-display: none` globally

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#12717]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The "Hide Title" option in pages settings, when activated, applies the `--page-title-display:none` css variable on `:root`, which means that if other Elementor published content (like mega menus, headers etc.) within the same page have this setting enabled, it will make the main title of the page to hide. 

## Solution 

Use `{{WRAPPER}}` instead of `:root`.

**Comment by udidol** [comment]
Hi @hogash,
I am not sure I understand your problem. If you target the `h1.entry-title` element, or any other unique identifier, why would there be a conflict with any other theme part? No other theme part is supposed to use this selector or this CSS variable.

**Comment by hogash** [comment]
Hey @udidol ,

I'm basically using a Header/Footer builder system that uses `Elementor\Plugin::instance()->frontend->get_builder_content_for_display( $post_id )` for rendering. When this method is called, it also generates its own stylesheet which contains that part `:root {--page-title-display:none;}` (if Hide title is enabled in Page settings panel of this particular post, say - a footer). If {{wrapper}} was used, it would apply this css variable specific to the area.

I haven't looked into Elementor's Document Type API, but i will. This should likely be the way to make those settings (Hide title etc.) hidden ,for "non-post" pages.

**Comment by udidol** [comment]
I see. 
Thing is - Elementor doesn't support using regular document types (page/post) for site parts (meaning, as headers or footers). That's why we have Elementor Pro and the Theme Builder. Header and Footer documents do not have the `'hide_title'` control, so this issue cannot happen if you are working correctly.

**Comment by Aviad-Herman** [comment]
Hi guys,
I read the correspondence, it seems like it has been answered so I'm going to close this issue.
Please keep on raising issues and giving feedback, we appreciate it.
Cheers!
