### ISSUE TITLE
[GLOBAL SETTINGS] Add global Box shadows and Text shadows

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12710]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### **Problem**

Having consistent box shadows throughout your website is important.

**Current workflow looks like this:**

- Set every single box shadow and its values by hand
- Constant cross-checking (If you want consistent values, you have to constantly cross-check the values and go back and forth between widgets, because it hard to remember all the values.)
- When you decide to change the box shadows you have to go through every single widget and every single value

Terrible workflow.

### **Solution**

Box shadows and text shadows should be added to the global settings so we can predefine them and easily use them throughout our website.

**Comment by oliveandlake** [comment]
+1 for this!

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12217, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by MichaelDarko** [comment]
#12217 is on a different subject, but ok.

**Comment by gerardreches** [comment]
+1 for global shadows, I constantly find myself in the workflow stated by the OP.

**Comment by gerardreches** [comment]
And I agree with @MichaelDarko about the issue #12217 having nothing to do with this one.
