### ISSUE TITLE
Popup on cart/checkout based on product

### ISSUE THREAD

**Issue by TheBigBanik** [elementor/elementor#12714]
Since popups are boosting our sales, it would be great if we could set the popup conditions based on the products in the cart. For example, if a user purchases a subscription, when in the checkout page a specific popup will appear giving him a discount while if he selects a physical product another popup will offer him a second product in half price or anything else.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
