### ISSUE TITLE
Wide Gamut Color Picker

### ISSUE THREAD

**Issue by tukyhutsman** [elementor/elementor#12715]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like to use Wide Gamut Colors in Elementor color pickers to specify colors that cannot be rendered by the default sRGB color profile that traditional Hex, HSL & RGB color values assign. My website is a Photo Retouching portfolio and I use AdobeRGB color profiled images which modern browsers can display accurately. These images often use colors that are out-of-gamut in sRGB color space. I'd like to be able to use Wide Gamut Colors for my non-image content in Elementor.

**Describe the solution you'd like**
I'd like Elementor's color pickers to offer a toggle into Wide Gamut Color mode. Or, perhaps the color picker could indicate it's in "sRGB" mode by default, and users could drop-down menu or tab to alternate color profiles, "Display-P3" or "AdobeRGB(1998)" color profiles, for example. When a Wide Gamut Color is picked, it would be great if Elementor could figure out and supply a fallback "sRGB" traditional color for browsers that cannot render Wide Gamut Color.

**Describe alternatives you've considered**
My workaround is to manually create CSS rules for instances where I want to use Wide Gamut Color.

**Additional context**
https://p3colorpicker.cool
https://portfolio.alexguichet.com/80/p3-color-picker
https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/

**Comment by dasigna** [comment]
... interesting idea.
not sure how this might work currently. even when a browser is set to and theoretically capable of showing those colors - most screens or devices probably wont ... which then can give pretty much weird results :)
apart from that - this is such specific, it probably wont be implemented in any mainstream product like elementor for years.

**Comment by tukyhutsman** [comment]
I included a link to a working wide gamut color picker in my post. That’s roughly how it would work. As for rendering weirdly, that’s just not true. Like all other CSS, browsers will ignore wide color gamut syntax it cannot understand. If the browser understands the syntax, the OS will use built in color management to map out of gamut color to a conventional display oif there isn’t a wide gamut display. As long as Elementor would calculate a conventional fallback color, nothing will look weird. Just not as high fidelity as a modern system could.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9862, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
