### ISSUE TITLE
Form Widget - Action After Submit - Download/File

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#12716]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, there is no solution to using a form to capture data which then issues a download. With Free Ebooks and White Papers on the rise, I am seeing more and more of my clients request the use of a form to capture data (name & email) which after completion issues them a PDF file.

**Describe the solution you'd like**
I would like the ability to add a Download as an Action After Submit. Ideally with a file field that auto-downloads after form submission.

**Describe alternatives you've considered**
I have tried using a redirect to the file however this does not work well. I have also created a redirect page which after submission they can download the file from. This works however adds additional unneeded steps. This is also hard to lock down the page allowing savvy users able to find and download without data capture.

**Comment by Omegatcu** [comment]
Hello,

I would love if Elementor made this a lot easier but I do have a solution for your problem:

What you need to set up:
1. Elementor Form with a hidden field for the filename [eg. 'file'] 
(you can use a request parameter to make multiple downloads with this solution possible)

2. A redirect in the Elementor form to: https://yourdomain.tld/dl.php?file=[field id="file"]

3. File dl.php on your webspace:
```
<?php 

$file = basename($_GET['file']);

if(file_exists('files/'.$file.'.pdf')){
    header("Content-type:application/pdf");
    header("Content-Disposition:attachment;filename=".$file.".pdf");
    readfile("files/".$file.".pdf");
    header('LOCATION: index.php'); // or any other URL
}
```

**Comment by webinsightin** [comment]
+1

**Comment by ajlg-vzla** [comment]
> 
> 
> Hello,
> 
> I would love if Elementor made this a lot easier but I do have a solution for your problem:
> 
> What you need to set up:
> 
>     1. Elementor Form with a hidden field for the filename [eg. 'file']
>        (you can use a request parameter to make multiple downloads with this solution possible)
> 
>     2. A redirect in the Elementor form to: [https://yourdomain.tld/dl.php?file=[field](https://yourdomain.tld/dl.php?file=%5Bfield) id="file"]
> 
>     3. File dl.php on your webspace:
> 
> 
> ```
> <?php 
> 
> $file = basename($_GET['file']);
> 
> if(file_exists('files/'.$file.'.pdf')){
>     header("Content-type:application/pdf");
>     header("Content-Disposition:attachment;filename=".$file.".pdf");
>     readfile("files/".$file.".pdf");
>     header('LOCATION: index.php'); // or any other URL
> }
> ```

Hi!
ive tried this solution but is not working
The form is requiring a value for the hidden field, and i dont know what is supposed to be, i also dont know what the LOCATION value should be for my site on the dl.php document code... thank you!

**Comment by ajlg-vzla** [comment]
> 
> 
> Hello,
> 
> I would love if Elementor made this a lot easier but I do have a solution for your problem:
> 
> What you need to set up:
> 
>     1. Elementor Form with a hidden field for the filename [eg. 'file']
>        (you can use a request parameter to make multiple downloads with this solution possible)
> 
>     2. A redirect in the Elementor form to: [https://yourdomain.tld/dl.php?file=[field](https://yourdomain.tld/dl.php?file=%5Bfield) id="file"]
> 
>     3. File dl.php on your webspace:
> 
> 
> ```
> <?php 
> 
> $file = basename($_GET['file']);
> 
> if(file_exists('files/'.$file.'.pdf')){
>     header("Content-type:application/pdf");
>     header("Content-Disposition:attachment;filename=".$file.".pdf");
>     readfile("files/".$file.".pdf");
>     header('LOCATION: index.php'); // or any other URL
> }
> ```

Hi again!
Somehow i managed to get this solution to work, i started modifying the redirection url and realized the bit after ...file= needs to be the file name only, deleting all the other words, like file id=
Thank you so much!

**Comment by raihanratul** [comment]
Hi, 
I am not being able to make this work.
I have copied the code in dl.php.
However should we use the pdfs directory on (file_exists('files/'.$file.'.pdf'))
So, instead of files, i have put wp-content/uploads ...

**Comment by nivek98** [comment]
Hi,

Do you know where I place the dl.php file?

**Comment by acgorecki** [comment]
Until Elementor adds this an Action After Submit, as a workaround, you can create a button with the [download attribute](https://www.w3schools.com/tags/att_a_download.asp) and link to a file uploaded in your media library.

<div class="download-file-button"><a href="https://example.com/wp-content/uploads/year/month/file-name.pdf" class="download-file-button_link" **download=""**>Download PDF file</a></div>

This will allow a user to download the specified file directly to their computer after clicking on the button instead of redirecting to a file "page" with nowhere to go afterward.

**Comment by Sainbloom** [comment]
Hey people, I got it done by doing the following:
1. Add your pdf file at the root folder (public_html), for reference my pdf file name was "whitepaper.pdf".
2. Create a php file at the root folder and add the code below, mine was named "whitepaper-download.php".
`<?php 

$filename = 'whitepaper.pdf'; // of course find the exact filename....        
header('Pragma: public');
header('Expires: 0');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Cache-Control: private', false); // required for certain browsers 
header('Content-Type: application/pdf');

header('Content-Disposition: attachment; filename="'. basename($filename) . '";');
header('Content-Transfer-Encoding: binary');
header('Content-Length: ' . filesize($filename));

readfile($filename);

exit;`

3. In elementor redirect add "https://yourwebsite.com/whitepaper-download.php"

That's it, the file should download on click while staying on the same page

**Comment by johnnny-bravoo** [comment]
@Sainbloom , thank you for your help. This best script works for me.

**Comment by acgorecki** [comment]
The plugin I am currently using will stop functioning on June 1st, 2023 and I'd like to replace it with a native Elementor solution. Are there any updates or timelines on this 2.5 year old issue?

**Comment by johnnny-bravoo** [comment]
@acgorecki The script by @Sainbloom is all perfect. There's still no official update but you can try the script.

https://github.com/elementor/elementor/issues/12716#issuecomment-1336342430

**Comment by WebblaJordan** [comment]
> Hey people, I got it done by doing the following:
> 
> 1. Add your pdf file at the root folder (public_html), for reference my pdf file name was "whitepaper.pdf".
> 2. Create a php file at the root folder and add the code below, mine was named "whitepaper-download.php".
>    `<?php
> 
> $filename = 'whitepaper.pdf'; // of course find the exact filename.... header('Pragma: public'); header('Expires: 0'); header('Cache-Control: must-revalidate, post-check=0, pre-check=0'); header('Cache-Control: private', false); // required for certain browsers header('Content-Type: application/pdf');
> 
> header('Content-Disposition: attachment; filename="'. basename($filename) . '";'); header('Content-Transfer-Encoding: binary'); header('Content-Length: ' . filesize($filename));
> 
> readfile($filename);
> 
> exit;`
> 
> 3. In elementor redirect add "https://yourwebsite.com/whitepaper-download.php"
> 
> That's it, the file should download on click while staying on the same page

Thank you! Worked perfectly for me.
