### ISSUE TITLE
Order of posts by wrong category

### ISSUE THREAD

**Issue by leonardomarioto2** [elementor/elementor#12712]
Hi! How are you?

I have a slightly annoying problem regarding the order of posts by category.

They are being sorted by the last update date, and not by the posting date that was as it was before.

That is, when I update an old post, it starts to appear first in category X, as if I had just posted!

What is going wrong?

**Comment by lior-sh** [comment]
Hi @leonardomarioto2,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
