### ISSUE TITLE
WooCommerce Product Element - Pagination Not Working

### ISSUE THREAD

**Issue by chkserv** [elementor/elementor#12721]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

If done in a normal page, it works fine.. But using the WooCommerce Products element's pagination option in the theme builder page ( Include conditions: Shop Page ) is does not work on the products.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] I can reproduce this bug consistently using the steps above.

## Environment

WordPress 5.5.1
PHP 7.4

Hello Elementor Theme 2.3.0
Elementor Version 3.0.11
Elementor pro Version 3.0.5

**Comment by chkserv** [comment]
UPDATE

If done in a normal page, it works fine.. But if you add the WooCommerce Products element in the theme builder page ( Include conditions: Shop Page ) then pagination and allow order don't work.

**Comment by udidol** [comment]
Hi @chkserv,
I am not sure I understood your problem. But since you have the latest Elementor Pro, you are eligible to receive support from our support team. Please open a ticket at https://my.elementor.com/support/.

**Comment by chkserv** [comment]
Thanks, I found a work around. It's working now. Issue now resolved.

**Comment by luka725** [comment]
Hello same issue here can you please tell me what was solution?
