### ISSUE TITLE
Kumbh Sans  font is missing 

### ISSUE THREAD

**Issue by amjadr360** [elementor/elementor#12723]
I want to use the Kumbh Sans google font: https://fonts.google.com/specimen/Kumbh+Sans

But I cannot find it in the typography settings: 

Please update the google font library.

Creating a template kit don't wanna use the filter to add support.

Thanks in advance!

**Comment by DorShahar** [comment]
Hi @amjadr360 
You can import the fonts you wish.
please follow https://elementor.com/blog/custom-fonts/ 

Thanks

**Comment by viaworksltd** [comment]
+1 It should be in the library. We shouldn't have to upload the font manually when it's a Google font.

**Comment by mdfoo8** [comment]
Agreed. Also Epilogue (another Google font - variable) is missing. Please update the list, thank you.
