### ISSUE TITLE
BUG: Tabs Widget content enlarges from top left corner when switching tab (after latest updates)

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#12724]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating to the 2 latest versions both 3.0.10 & 3.0.11 (w/ Pro 3.0.5 active), all of my tabs do this weird thing when switching tabs. I would like for tabs to function the way they used to before updating. **Before the update, they always functioned nice and smooth when switching**. Now the buggy tabs load ugly with weird resizing and content growing larger from the left side to fill the space. There is nothing in the settings I can do to fix it. See example demonstration before update and after update.

I suspect this bug has something to do with the change that is listed in this changelog:
3.0.10 – 2020-09-23
"Fix: Entrance animation isn’t working on edge cases in Tabs widget"

## Steps to reproduce

1) create a widget with 2 tabs
2) insert a template shortcode (that contains an image) into the content area of each tab
3) switch back and forth between the 2 tabs
Note: you must have Elementor Pro active to use template shortcodes in tab content areas

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: http://clone.local
	Home URL: http://clone.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.0.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		icon-box : 3
		spacer : 1
	header : 1
		button : 4
		spacer : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 1
		button : 20
		spacer : 1
		template : 18
		text-editor : 20
	popup : 2
		button : 1
		heading : 9
		html : 1
		icon : 9
		icon-box : 3
		text-editor : 9
	section : 23
		accordion : 1
		button : 4
		form : 3
		heading : 35
		icon : 36
		icon-box : 5
		image : 53
		image-carousel : 1
		menu-anchor : 17
		spacer : 30
		tabs : 2
		text-editor : 52
		toggle : 14
	wp-post : 0
		heading : 5
		icon : 1
		menu-anchor : 2
		shortcode : 4
		spacer : 4
		template : 9
	wp-page : 9
		shortcode : 1
		spacer : 3
		template : 21
		woocommerce-products : 1
	product-archive : 0
		wc-archive-products : 1

</details>

**BEFORE UPDATE (WORKS GREAT)**
![before-update](https://user-images.githubusercontent.com/1435355/94886669-eb2e5680-0441-11eb-9609-11a3db65ebca.gif)

**AFTER UPDATE (NOT NICE)**
![after update](https://user-images.githubusercontent.com/1435355/94886698-01d4ad80-0442-11eb-9cb0-63d117eded77.gif)

**Comment by heyfletch** [comment]
I have the same issue. 3.0.9 is ok. 3.0.10+ starts introduces tab content "growing" by default.

I have already contacted support. Their position is that the animation in 3.0.10 is the intended behavior by default. Support has pointed to this Github issue as the most likely path to fixing this issue.

I have stressed that Animation as the default makes no sense to me, especially when Animation is usually an enhancement, not the default. Plus, this obviously looks terrible! It is so jarring. One of the main benefits of tabs is the ability to instantly switch content without any appearance of page load or latency. This introduces a terrible delay and I cannot even imagine how anyone wants this at all, much less the default. What is possibly the benefit of this content growing like this?!

So, if this is the default, please give us the option to turn it off, or reverse your decision to make this default and instead at this as an option in the Entrance Animation section... which is really the right, best move here.

This is yet another 3.0 update that is breaking our designs. Not happy, in case you couldn't tell. ;)

**Comment by TomRaraAvis** [comment]
To have this behavior as intended default is absurd. Makes me wonder if the support person you spoke with knows what they are talking about. This certainly feel like a bug.

**Comment by heyfletch** [comment]
IMO it is a bug. If we set up our design with their tool and it worked as desired, then they introduce an update that breaks it... that's a bug. Regardless, the right thing to do now is to provide an option to not have animation.

**Comment by MichaelDarko** [comment]
+1

**Comment by TomRaraAvis** [comment]
@heyfletch Bingo! . . . we at least need an option do disable that janky behavior. Looking forward to a response in this thread from Elementor.

**Comment by nerdtech** [comment]
this simply doesn't look good when using larger blocks of text, please fix this a design tool should never force users to use animations... https://i.imgur.com/15mBgvL.mp4

**Comment by Albert-J04** [comment]
Yes - the screenshot above is mine. This does not look good at all for me, can this change please be reverted and give us the option to enable it. Thanks.

**Comment by mcrowell** [comment]
+1 - Same results with Elementor 3.0.11 and Pro 3.0.4

**Comment by sproutedweb** [comment]
+1 - Same results the above reported.

**Comment by sladjanstojcic** [comment]
Same issue here.. I have tables as tab content and it looks weird when switching tabs..

**Comment by sladjanstojcic** [comment]
So here is how I temporarily solved this issue, a bit hackish solution but it works:

```
$(window).on('load', function() {
    // Unbind default Elementor behaviour
    $('.elementor-tab-title').off('click keydown');

    $('.elementor-tab-title').on('click', function(e) {
        e.preventDefault();
    
        var $this = $(this);
        var $widget = $this.closest('.elementor-widget-tabs');
        
        // Tab title
        var $tabTitle = $('.elementor-tab-title', $widget);
        $tabTitle.removeClass('elementor-active');
        $this.addClass('elementor-active');
        
        // Tab content
        var $tabContent = $('.elementor-tab-content', $widget);
        $tabContent.hide();
        $tabContent.filter('[data-tab="' + $this.data('tab') + '"]').show();
    }); 
});
```

It helped in my case, horizontal tabs...

**Comment by heyfletch** [comment]
@sladjanstojcic thank you! this temporary hack fixes it for our site.

**Comment by sladjanstojcic** [comment]
> @sladjanstojcic thank you! this temporary hack fixes it for our site.

Great, but please test it thoroughly as it could mess with other tab widgets/accordions if they exist on the page.

**Comment by Albert-J04** [comment]
Heyo,

Awesome, I would like to give this a try.

How do I implement this code - has anybody got a guide. Thanks

**Comment by heyfletch** [comment]
Good point. I limited the js to the one page with the tabs.

**Comment by zeldan** [comment]
+1 - Same results with Elementor 3.0.11 and Pro 3.0.5

**Comment by alexkowel** [comment]
Please fix it!

**Comment by PaulPopravkin** [comment]
+1 remove the animation, please

**Comment by david-wingtra** [comment]
+1 yes please remove this animation

**Comment by TomRaraAvis** [comment]
@lior-sh ?

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will check this issue and address it soon.

**Comment by TomRaraAvis** [comment]
Thank you. 👍

**Comment by blakemiller99** [comment]
+1 for me. This is breaking a plugin "PDF Embedder" that automatically calculates the width of the container it sits in to make it 100% width. But, it's finishing it's calculation before the tab gets to 100% so my embedded PDF finishes around 60-70% width and looks bad. https://www.screencast.com/t/cV3ccfIH3Kh

**Comment by blakemiller99** [comment]
> So here is how I temporarily solved this issue, a bit hackish solution but it works:
> 
> ```
> $(window).on('load', function() {
>     // Unbind default Elementor behaviour
>     $('.elementor-widget-tabs .elementor-tab-title').off('click keydown');
> 
>     $('.elementor-widget-tabs .elementor-tab-title').on('click', function(e) {
>         e.preventDefault();
>     
>         var $this = $(this);
>         var $widget = $this.closest('.elementor-widget-tabs');
>         
>         // Tab title
>         var $tabTitle = $('.elementor-tab-title', $widget);
>         $tabTitle.removeClass('elementor-active');
>         $this.addClass('elementor-active');
>         
>         // Tab content
>         var $tabContent = $('.elementor-tab-content', $widget);
>         $tabContent.hide();
>         $tabContent.filter('[data-tab="' + $this.data('tab') + '"]').show();
>     }); 
> });
> ```
> 
> It helped in my case, horizontal tabs...

@sladjanstojcic How & Where did you put this code? On the individual page? Or site?

**Comment by sladjanstojcic** [comment]
> > So here is how I temporarily solved this issue, a bit hackish solution but it works:
> > ```
> > $(window).on('load', function() {
> >     // Unbind default Elementor behaviour
> >     $('.elementor-widget-tabs .elementor-tab-title').off('click keydown');
> > 
> >     $('.elementor-widget-tabs .elementor-tab-title').on('click', function(e) {
> >         e.preventDefault();
> >     
> >         var $this = $(this);
> >         var $widget = $this.closest('.elementor-widget-tabs');
> >         
> >         // Tab title
> >         var $tabTitle = $('.elementor-tab-title', $widget);
> >         $tabTitle.removeClass('elementor-active');
> >         $this.addClass('elementor-active');
> >         
> >         // Tab content
> >         var $tabContent = $('.elementor-tab-content', $widget);
> >         $tabContent.hide();
> >         $tabContent.filter('[data-tab="' + $this.data('tab') + '"]').show();
> >     }); 
> > });
> > ```
> > 
> > 
> > It helped in my case, horizontal tabs...
> 
> @sladjanstojcic How & Where did you put this code? On the individual page? Or site?

You should put it probably only on the page where you have this issue with tabs.

**Comment by TomRaraAvis** [comment]
YEP! confirmed fixed 🙏🙏🙏 thank you!

**Comment by Hiram-dev** [comment]
> > So here is how I temporarily solved this issue, a bit hackish solution but it works:
> > ```
> > $(window).on('load', function() {
> >     // Unbind default Elementor behaviour
> >     $('.elementor-widget-tabs .elementor-tab-title').off('click keydown');
> > 
> >     $('.elementor-widget-tabs .elementor-tab-title').on('click', function(e) {
> >         e.preventDefault();
> >     
> >         var $this = $(this);
> >         var $widget = $this.closest('.elementor-widget-tabs');
> >         
> >         // Tab title
> >         var $tabTitle = $('.elementor-tab-title', $widget);
> >         $tabTitle.removeClass('elementor-active');
> >         $this.addClass('elementor-active');
> >         
> >         // Tab content
> >         var $tabContent = $('.elementor-tab-content', $widget);
> >         $tabContent.hide();
> >         $tabContent.filter('[data-tab="' + $this.data('tab') + '"]').show();
> >     }); 
> > });
> > ```
> > 
> > 
> > It helped in my case, horizontal tabs...
> 
> @sladjanstojcic How & Where did you put this code? On the individual page? Or site?

Hello thanks everyone for finding a solution but i tried it and it didn't work. I tried adding it as is in the <head> of the page via Header and Footer Scripts plugin, and i also tried adding it as code on the page and through the Cuztomize menu additional JS plugin. Other added external JS works fine. Can someone please help, it's driving me crazy how bad this animation is.

**Comment by Hiram-dev** [comment]
> $(window).on('load', function() {
>     // Unbind default Elementor behaviour
>     $('.elementor-widget-tabs .elementor-tab-title').off('click keydown');
> 
>     $('.elementor-widget-tabs .elementor-tab-title').on('click', function(e) {
>         e.preventDefault();
>     
>         var $this = $(this);
>         var $widget = $this.closest('.elementor-widget-tabs');
>         
>         // Tab title
>         var $tabTitle = $('.elementor-tab-title', $widget);
>         $tabTitle.removeClass('elementor-active');
>         $this.addClass('elementor-active');
>         
>         // Tab content
>         var $tabContent = $('.elementor-tab-content', $widget);
>         $tabContent.hide();
>         $tabContent.filter('[data-tab="' + $this.data('tab') + '"]').show();
>     }); 
> });

I feel ridiculous but it worked using this https://www.silkypress.com/simple-custom-css-js-pro/

not sure if there was another option. again thanks for the solution.

**Comment by danstramer** [comment]
+1
