### ISSUE TITLE
@ziogaschr

### ISSUE THREAD

**Issue by Ant67** [elementor/elementor#12729]
@ziogaschr 

Elementor can't guess which multilingual 3rd party plugin you are using and we don't want to keep the conditions system light as possible.

You can, however, extend the conditions system and add your own (like Polylang language based condition ).

But that will not help you in your case because the conditions system currently only supports "OR" between its rules which in your case will limit the condition to language-based only. 

A better approach is to use the provided hooks by elementor and Polylang.
The workflow should be to only define the conditions on the main/default language and not on the connected translation templates.

then you can use this hook `elementor/theme/get_location_templates/template_id` to change the id of the template based on the language, ex:

```PHP
// Polylang
add_filter( 'elementor/theme/get_location_templates/template_id', function( $post_id ) {
	if ( function_exists( 'pll_get_post' ) ) {
		$translation_post_id = pll_get_post( $post_id );
		if ( null === $translation_post_id ) {
			// the current language is not defined yet
			return $post_id;
		} elseif ( false === $translation_post_id ) {
			//no translation yet
			return $post_id;
		} elseif ( $translation_post_id > 0 ) {
			// return translated post id
			return $translation_post_id;
		}
	}
	return $post_id;
} );
```

_Originally posted by @bainternet in https://github.com/elementor/elementor/issues/4839#issuecomment-399866656_

**Comment by shilo-ey** [comment]
Please respond to the user you are trying to respond to and don't create a new issue for that.

Thanks!
