### ISSUE TITLE
woocommerce builder

### ISSUE THREAD

**Issue by metinbicaksiz** [elementor/elementor#12737]
I have just bought the pro plan of elementor and I am supposed to get woocommerce builder, however, I cannot find it on my page's admin panel. Is there a specific link for me to download it. I am trying to make changes on the default cart page of woocommerce. 
Thanks 

- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by shilo-ey** [comment]
Hi @metinbicaksiz 

As mentioned in your issue, GitHub issues are not for support.

Please read more about WooCommerce Builder here: https://elementor.com/blog/woocommerce-tutorial/
or watch here: https://www.youtube.com/watch?v=SuyV4Tevmm0

Thanks
