### ISSUE TITLE
Sub-sites for multi-site install not working in Latest 3.0.11 update

### ISSUE THREAD

**Issue by actionTurtle** [elementor/elementor#12731]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

 
When creating a multi-site install... Sub-sites won't load the elementor back-end... Main site loads fine... Had to roll back to 3.0.7 and 3.0.4 (elementor pro) then everything just worked 

## Steps to reproduce

Created a fresh Wordpress install and added elementor, elementor pro and hello themes as network active. Can edit main site but subsites just get stuck in loading forever... Even safe mode or debug gives no info on what could be the error

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: MySQL Community Server - GPL v8.0.21
	PHP Version: 7.4.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== Network Plugins ==
	Akismet Anti-Spam
		Version: 4.1.6
		Author: Automattic

	Analytify - Google Analytics Dashboard
		Version: 3.1.5
		Author: Analytify

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.0.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	Image optimization service by Optimole
		Version: 2.5.4
		Author: Optimole

	Rank Math SEO
		Version: 1.0.48.2
		Author: Rank Math

	Wordfence Security
		Version: 7.4.11
		Author: Wordfence


== Must-Use Plugins ==


== Elements Usage ==
	


== Log ==
	

				
```
</details>

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
