### ISSUE TITLE
cant open footer in elementor, console problem

### ISSUE THREAD

**Issue by muzil2008** [elementor/elementor#12740]
<img width="352" alt="Screen Shot 2020-10-05 at 09 57 46" src="https://user-images.githubusercontent.com/72360134/95026984-9e70a700-06f1-11eb-82f5-cb4f1471d5e8.png">
<img width="355" alt="Screen Shot 2020-10-05 at 09 45 14" src="https://user-images.githubusercontent.com/72360134/95026985-a03a6a80-06f1-11eb-9fa2-05f0f6b28109.png">

**Comment by muzil2008** [comment]
i found the answer guys. so if you have the same problem like me, you can go to Setting>permalink, change the post link from date and name to postname! hope it is helpful for whom have the same problems.

**Comment by shilo-ey** [comment]
Hi @muzil2008 

Glad you found out the reason in your case.

Closing this issue for now,

Feel free to reopen if the issue persists.

Thanks
