### ISSUE TITLE
Color Control does not support description.

### ISSUE THREAD

**Issue by pacifier007** [elementor/elementor#12747]
The color control in the documentation mentions that, like other controls, it supports description: https://developers.elementor.com/elementor-controls/color-control/

However, it's not true. I have confirmed it by looking at the `content_template()` of color.php and description isn't added there. 

It's a small but quite nifty thing that's missing.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.12

Feel free to update

Thanks!
