### ISSUE TITLE
Request for Popup template in Theme Builder Elementor!

### ISSUE THREAD

**Issue by MThaldi** [elementor/elementor#12744]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Not able to find POPUP Template setting and feature in Theme Builder Elementorl

**Describe the solution you'd like**
Popup template in theme builder elementor Page builder should be included. need enablement to edit in front end

**Describe alternatives you've considered**
Include all backend templates to front end theme builder.

**Additional context**
![image](https://user-images.githubusercontent.com/33521888/95057522-f0c2bf80-0713-11eb-9f35-45ba4abc5639.png)

**Comment by shilo-ey** [comment]
Hi @MThaldi 
Thanks for your suggestion

Actually, we had the same question when ideating this feature.

Eventually, we decided that Theme Builder is the place you go to create your fundamental, must-have parts to achieve a full website.

Without these parts, your site is incomplete.

A website can be full without any popup, therefore it's a different part of our product which we will handle in the future.

Thanks
