### ISSUE TITLE
Can we also have Popup template in Theme Builder Elementor! Currently we dont have that in front end!

### ISSUE THREAD

**Issue by MThaldi** [elementor/elementor#12743]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Duplicate of #12744
