### ISSUE TITLE
Site Settings location in database and customization

### ISSUE THREAD

**Issue by motiejus1** [elementor/elementor#12751]
Hello,
after Elementor 3 release I've got some kind of problem.
http://prntscr.com/uu2k95
The screenshot shows Site Settings. Everything works fine. But the problem is,
 where are these settings located in the database?
How to change them via code?
How to export them?

Because I need to update my theme, and Elementor Kit settings are not proper for my theme, I need to change default values. I'm trying to export pages with these settings, but when I import it on a new Wordpress installation, I get default values.

**Comment by udidol** [comment]
Hi @motiejus1,
Importing and exporting Kit settings is not yet possible. It will become possible in the near future.
