### ISSUE TITLE
Elementor Pro fails with TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by rubenstolk** [elementor/elementor#12756]
![image](https://user-images.githubusercontent.com/692644/95222619-f940f600-07f8-11eb-9bb8-59ac45378311.png)

**Comment by sladjanstojcic** [comment]
In my experience, this is usually caused by the theme or other plugins. Try loading in Safe mode or with all plugins disabled.

**Comment by DorShahar** [comment]
Hi @rubenstolk 

Thanks for reporting,

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
