### ISSUE TITLE
Bullets for Sliders, Carusells

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#12754]
Hi,

It would be great if you can implement custom bullets for Sliders, Img Carrusels, etc.

Like, adding a PNG or some kind of image to "design" more efficiently.

![image](https://user-images.githubusercontent.com/68023943/95217426-8c623780-07c9-11eb-9c7b-57b12e14b0ed.png)

**Comment by maurocarreraok** [comment]
none answers >(

**Comment by maurocarreraok** [comment]
@DorShahar :) Quite old but may be is nice to have on future releases.

**Comment by DorShahar** [comment]
Hi @maurocarreraok 
Thank you for your input! 

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding - And keep raising up suggestions!
