### ISSUE TITLE
Paragraph bottom margin

### ISSUE THREAD

**Issue by siscanu** [elementor/elementor#12755]
Hello,
I builded many websites with Elementor, and the margin bottom for each paragraph is realy annoing for building simetrical websites. Because of that, I use this CSS to solve this annoing problem.

`p:last-child {
    margin-bottom: 0rem;
}`

Please include this CSS in Elementor. Thanks.

**Comment by shilo-ey** [comment]
Hi @siscanu 

Thanks for your suggestion, but Elementor provides a tool for hundreds of themes and custom code modifications and we don't want to interfere with this CSS rule, which usually is set by the theme.

Either modify your theme's styles.css file or add this code in Elementor Site Settings > Custom CSS

Thanks
