### ISSUE TITLE
Advanced Editor Tools (previously TinyMCE Advanced) fails to load in Elementor

### ISSUE THREAD

**Issue by thomarto** [elementor/elementor#12768]
https://github.com/elementor/elementor/blob/bb96e7a2cde78e1000997319accb2bc193c48fa4/core/editor/editor.php#L584

When the _Advanced Editor Tools (previously TinyMCE Advanced)_ plugin is activated and a text widget is selected in Elementor, the Elementor panel is empty.

The author of the plugin has tracked down the issue but says that it is something that needs to be fixed in Elementor. He provides the solution here:
https://wordpress.org/support/topic/editor-fails-to-load-in-elementor/

A temporary solution is to uncheck the "Other instances of the Classic (TinyMCE) editor in wp-admin" option in the plugin's settings

(Note: I don't know anything about GitHub so I hope I've done this right!)

<img width="1084" alt="elementor-panel" src="https://user-images.githubusercontent.com/26119379/95342674-98282980-08af-11eb-9d13-7e7dc04ef21c.png">

**Comment by black-eye** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.12

Feel free to update

Thanks!
