### ISSUE TITLE
Form ajax handler->add_error triggers a javascript error "r is undefined" - common.min.js

### ISSUE THREAD

**Issue by annettePixie** [elementor/elementor#12760]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

Using the action hook 'elementor_pro/forms/validation' to add validation error messages with $ajax_handler->add_error triggers a javascript error "Uncaught TypeError: r is undefined" in common.min.js **when** a form input fails validation. Expected validation messages are rendered but as a result of the javascipt fail, the ajax response data cannot be used for other custom messages. 

This is particularly annoying as I need to validate checkboxes to ensure at least one is selected. As Elementor does not provide for this out of the box for checkboxes, I need to be able to access the ajax response data returned for validation errors.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.3.16
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected
== WordPress Environment ==
	Version: 5.5.1
	WP Multisite: No
Elementor
		Version: 3.0.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

</details>

**Comment by chocochrispi** [comment]
I've got the same issue

**Comment by KohakuDoig** [comment]
Any news on this?

I'm getting this error after upgrading as well. Seems to work OK on a new page but a basic form on an existing one is returning this error in the console. I recreated the form with default settings and just a custom email and still had the issue.

**Comment by SarahElementorProUser** [comment]
Same issue. Any news on this? Is there a workaround?

**Comment by KohakuDoig** [comment]
After a bit of testing I'd found that the end-user had enabled editing that piece of content with Elementor, where the form which was causing the error had been added with Theme Builder. I switched the content back to 'edit with wordpress' and the error vanished. Might be worth checking.

**Comment by maggie-x** [comment]
I am getting this error as well.

**Comment by svrwxrob** [comment]
Hi There - it appears we are seeing the same bug with a form as an AETemplate. Has this been addressed or are there any workarounds for this error?

**Comment by thomasfaboux** [comment]
I've got the same issue.
Elementor v3.0.15

```
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
...
$ajax_handler->add_error( $field['name'], 'invalid name' );
}
```
=> Error in chrome console :
Uncaught TypeError: Cannot read property 'error' of undefined (common.min.js:2)

**Comment by wisejayden** [comment]
After a long time spent troubleshooting, I managed to get it working on my project. 
Hopefully the code will be helpful for some of you!

`add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );

    // Replace MY_FORM_NAME with the name you gave your form
    if ( 'MY_FORM_NAME ' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
	
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    // Replace HTTP://YOUR_WEBHOOK_URL with the actuall URL you want to post the form to
    $response = wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL ', [
        'body' => $fields,
    ]);
	$json_response = json_decode($response['body']); 
        
       //Response from backend
	if($json_response->error == 1){
	   $handler->add_error($json_response->field, $json_response->message);
	} else {
	 $handler->is_success = true; 
	  $handler->add_response_data(true, $response);
	}	
}, 10, 2 );`

**Comment by tollube** [comment]
@wisejayden 
And what did you change that it throws the error message?
How to provoke an error message? 
I need to dump a variable and see whats inside but I cant show it with an error at the frontend form..

Is there another way to show a var in the frontend?

**Comment by wisejayden** [comment]
@tollube 
How you provoke the error message is entirely up to you, however I am returning a 400 from the server with the following JSON body to trigger the add_error function as shown in the code above. 
`
{
  error: true,
  field: 'email',
  message: "Your email address is incorrect"
}
`

**Comment by tollube** [comment]
This seems to happen with normal forms without custom PHP as well.
How to fix this? Forms cannot be sent at all.

**Comment by thomasfaboux** [comment]
Problem is still not resolved for me.
`$handler->add_error($field, $message)` does not change anything unfortunately :(

**Comment by enisdenjo** [comment]
Same for me here. Submitting _any_ erroneous form complains in the console and the form stays the same:

```
Uncaught TypeError: Cannot read property 'error' of undefined common.min.js?ver=3.1.1:2
    at onError (common.min.js?ver=3.1.1:2)
    at dispatch (jquery.min.js?ver=3.5.1:2)
    at v.handle (jquery.min.js?ver=3.5.1:2)
    at Object.trigger (jquery.min.js?ver=3.5.1:2)
    at HTMLFormElement.<anonymous> (jquery.min.js?ver=3.5.1:2)
    at Function.each (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.each (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.trigger (jquery.min.js?ver=3.5.1:2)
    at child.onSuccess (frontend.min.js?ver=3.0.10:2)
    at Object.e.each.n.<computed> [as success] (frontend-modules.min.js?ver=3.1.1:2)
```

- Elementor v3.1.1
- Elementor Pro v3.0.10

The same issue is here #12960. He solved the issue by solving the error itself. However, the error reporting still does not work!

**Comment by shilo-ey** [comment]
Thanks!

We merged your PR and we will release it in the upcoming release.

**Comment by shilo-ey** [comment]
Thanks, closing this issue.
