### ISSUE TITLE
[SITE SETTINGS -> LAYOUT] - Add option to change default Column Gap

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12763]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### Problem

**Right now, the default Column Gap (padding) is 10px.**
- If you want to get rid of this padding, you have to change every single section to "No gap".
- This is super annoying, silly workflow.
- Design tool should never have default predefined values that can't be changed globally. 
- Absolutely basic stuff, that should be taken care of long time ago.

### Solution

**Add default Column Gap setting to Site Setting -> Layout** (Just like the default widget spacing)

**Comment by rodolphebertozzo** [comment]
I think it's a matter of including global settings for sections and columns, I think it's something that will be settled in the future

**Comment by nerdtech** [comment]
i agree with this it should be under site settings and layout... you can over-ride this by CSS however by putting this in your themes custom additional css section and publishing:  

`.elementor-column-gap-default>.elementor-column>.elementor-element-populated {
	padding: 0px;
}`

**Comment by gTaylorRokk** [comment]
Elementor team, I'm still amazed there is no global control for column gap settings and why this was overlooked in 3.0 release! Yes it can be overridden by some simple CSS, but why give us other global theme options for layout but not this? For theme consistency it would be best to set a preferred column gap value globally for each breakpoint. Then if we need to customise we can do so on the section the element. It was nice you recently added the custom column gap value in recent 3.1 release, but agree with @MichaelDarko column gaps really need to be a global layout setting in my opinion.

**Comment by mapsmarketing** [comment]
For those who are still looking for these options, here is a plugin: https://wordpress.org/plugins/analogwp-templates/

Although, it would be best for a native option.

**Comment by arielk** [comment]
Please see the new feature called ["Save as Default" in v3.9 ](https://github.com/elementor/elementor/discussions/20328)

Thanks for your feedback!
