### ISSUE TITLE
Global Widget Template

### ISSUE THREAD

**Issue by hectormartinez018** [elementor/elementor#12779]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Whenever you have a lot of widgets with the same style and only the content is different, and you wish to make styling changes, you currently have to copy it over to each widget one by one. 

**Describe the solution you'd like**
It would be nice to have a global widget that you can edit the content but still retain the styles of the global widget. Very similar to how when you add a class to an object and it picks up the styling properties but it doesn't matter what the content itself is.

**Describe alternatives you've considered**
I've tried using the global widget feature but that is only if you want the exact same widget (and content) in different instances. To edit, you have to unlink, which means any edits to the global widget wont take effect on that one.

**Additional context**
No additional context.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
