### ISSUE TITLE
Lazy Load

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12778]
Not having access to the private Repository, find the 2 files of the widgets posts and portfolio with the inclusion of the lazy load
https://drive.google.com/drive/folders/12e9t86vcfJXxT4GlvEs7wMNz638YHMRL?usp=sharing

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
