### ISSUE TITLE
[COLOR PICKER] - Add input field to control opacity in %

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#12772]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Problem

It seems that Elementor's color picker is now only using HEX color format, even when there is alpha value (transparency).

We now don't have any practical way to set transparency in percentages. We only have the transparency slider, but you can't set any exact value with that.

It used to be the case, that the format would switch to RGBA, when alpha value was set. But this is no longer the case. 

**Using only the HEX format is not a problem, but you have to give us some way of controling transparency in %.**

## Solution

**Just add % input field next to the transparency slider.** 

- When we move the slider, we will be able to see the exact % values. 
- Or we can set the transparency by typing it directly into the % input field.

Here is a design of how it should look:
![Better color picker](https://user-images.githubusercontent.com/36289156/95443939-81401080-095d-11eb-82cb-1f74e553cc6f.png)

## Why it matters

Controlling transparency in percentages is absolutely fundamental in webdesign.

You guys keep revamping the color picker but you never get this right. Any time I need to set an exact transparent color, I have to open some other tool and choose the color there. That's insane.

I have never seen a webdesign tool without the % field.

- HEX format doesn't allow us to set intuitive % based values. (That wouldn't be a problem if you gave us the % input field.)
- Transparency slider without any number indicator is pretty useless.

Please, get this right. It's a tiny and simple change and it would totally fix this UX blunder.

**Comment by black-eye** [comment]
+1 
Exactly

**Comment by MichaelDarko** [comment]
Many other people were requesting some usable transparency control for a year now in this thread: #9862

Why on earth did this not get your attention when you were revamping the color picker with global colors?

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9862, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the option to choose other colors in the color picker is now live in the latest v3.13-Beta release!

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment]
Hello, there @MichaelDarko!

We have great news! 🙌 

### 📢 We're happy to announce that you can now choose to use RGBA or HSLA colors with Elementor **v3.13.0**! 🥳 

This will allow you to select the percentage of the colors you want to add.

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
