### ISSUE TITLE
Popup: Page is scrolling to top when disable page scroll is checked

### ISSUE THREAD

**Issue by linkupdesign** [elementor/elementor#12786]
Create a popup, check "disable page scroll" and the popup is toggled, that whole site is scrolled completely up in the background.

**Comment by lior-sh** [comment]
Hi @linkupdesign,

Thanks for reporting, we couldn't reproduce the issue. 
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
