### ISSUE TITLE
lib/pickr/pickr.min.js.map: HTTP error: status code 404

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#12781]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I am not going to do your work for you, I see this in the Dev Console.  I read about a guy in the Elementor Group yesterday that had problems with SouceMap.

DevTools failed to load SourceMap: Could not load content for https://www.domain.se/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by obe1968** [comment]
I too have confirmed this error AND it is preventing me from dragging and applets to sections, thereby (as far as I am concerned) leaving me dead in the water and backends rendered unusable meaning cannot get any work done. No work means no income, no income makes for pissed off customers!

Even tried rolling back to 2.9.9 and 2.10.3 (pro) respectfully and still no joy!

Please fix this problem ASAP. So we can get back to making money to pay you guys :)

**Comment by lior-sh** [comment]
Hi @tamelander,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
