### ISSUE TITLE
Wordpress Elementor preview not loading

### ISSUE THREAD

**Issue by antonellorossi** [elementor/elementor#12788]
i have a website with Wordpress 5.5.1, Elementor 3.0.11 and Permalink Manager Lite 2.2.9.1 If i set permalink as "base" Elementor preview works fine but i have a problem with my website page because they go to 404. This happend because i set my permalink logic before install Elementor. If i set permalink as "postname" the site works well but Elementor can't modify the page. I receive "Preview Could Not be Loaded" with a jquery error in console. I try everything : change themes, disable and then enable one to one my plugin, safe mode on Elementor.

**Comment by lior-sh** [comment]
Hi @antonellorossi,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
