### ISSUE TITLE
Bug: Mobile Menu Not Working

### ISSUE THREAD

**Issue by Tdubfun** [elementor/elementor#12791]
We are using Elementor Version 3.0.11 on Wordpress (Ocean Extra template) and after the recent update, the Mobile Menu button on Android and iPhone doesn't open on any page. The hamburger menu says it opens but it doesn't. So mobile site is currently not navigatable. Our website is www.ac3.org. ON Elementor FB group, it says to report Bugs on Github. I have cleared my cache under social and purged SG cache as I did see something in a prior ticket. Thank you for your help as I am new to this. Twila

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lior-sh** [comment]
Duplicate with #12790
