### ISSUE TITLE
 Multiple custom fields for 'orderby'

### ISSUE THREAD

**Issue by maxcondor** [elementor/elementor#12806]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by maxcondor** [comment]
Hello,
I would like to sort the posts by descending date and with the same date sort them in descending order by the "ordinamento" field (ACF)
i tried the following code but it doesn't work
`add_action( 'elementor/query/q_primopiano', function( $query ) {
   	$meta_query = [
		[
        'key' => 'visibile',
        'value' => '1',
        'compare' => '=',
    	] ,
		[
        'key' => 'visibile_in_home',
        'value' => '1',
        'compare' => '='
    	], 
		[
        'key' => 'ordinamento',
        'value' => '0',
        'compare' => '>'
    	],
     	];
 	$query->set('meta_query', $meta_query);
        $query->set( 'orderby', array(
          'post_date' => 'DESC',
         'ordinamento' => 'DESC',
	      
    ));
	
} );`

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
