### ISSUE TITLE
Having multiple "Nav Menu global" widgets, Elementor editor shows the wrong menu contents

### ISSUE THREAD

**Issue by Junior9235** [elementor/elementor#12809]
I need different menus for category silo, so we have a  menu for each category and its subpages. Cat 1 and subpages have menu1, Cat2 and its subpages have Menu 2 and so on. 
We have now created 4 different Nav menu (pro feature) for 4 silos,  vertical option enabled and added a css class name for each and a little css code to keep it open on active page. All menus are set as global widget and name differently so we can easily edit each menu in case we need to add a subpages in any category etc. 
The problem is no matter which Nav menu you choose and drop in the page, it will always show the first Nav Menu we created (in the page  we are working). If you publish it shows the right menu but while you are working in the page it shows the wrong menu. 
In addition to that, the edit global widget (while global is LINKED), seems to be inconsistent to upgrade changes on all linked pages and load the enabled borders, normal, hover, active color sets etc. To make it clear, if we edit the global in page 1 and then later working on page 2, the global nav menu in page 2 could also be edited there, however, widget loaded may not have features enabled or set while edit in page 1, not sure if it because is mixing contents with other Nav menu global widgets (as described above), it shows the first menu global created.

===== Guidelines ====

- Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.
- Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).
- If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific.

-->

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Aviad-Herman** [comment]
Hello,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
