### ISSUE TITLE
Forms Conditional Actions

### ISSUE THREAD

**Issue by FIJOR** [elementor/elementor#12812]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Not being able to choose whether to perform an action or not based on the form inputs. For example, to subscribe the user to a mailing list only if he checked a checkbox. This is very important to comply with data privacy norms and we can't do this yet with Elementor Forms.

**Describe the solution you'd like**
Be able to activate actions based on conditional logic. For example, action "mail chimp" if "checkbox" "checked".

**Describe alternatives you've considered**
You have to pay for alternatives like zapier to be able to do this.

**Additional context**
Already explained it pretty well ;)

**Comment by shilo-ey** [comment]
I merged this issue with #2638, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by FIJOR** [comment]
> I merged this issue with #2638, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!

I opened a new one because it is not exactly the same thing, but as long as you keep it in mind :)
