### ISSUE TITLE
Change form background color on form validation 

### ISSUE THREAD

**Issue by CGe0h** [elementor/elementor#12819]
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor Pro feature :
Is there a way to automatically change the background color of the form after submission of it ? For example, if the form is validated with success, I'd like to change the background to green, if there is an error, to red.
Thank you.

**Comment by bainternet** [comment]
Hi @CGe0h 

There are events that are triggered on the form element which you can catch and change the background however you like, ex:

```JS
jQuery( document ).ready(function() {
    const myForm = jQuery( "#myform" );
    myForm.on( 'submit_success', function() {
		// this event means all good form submmited
    	jQuery(this).css('background-color', 'green');
    } );
    myForm.on( 'error', function() {
		// this events mean there is an error
    	jQuery(this).css('background-color', 'red');
    } );
} );
```

Hope this helps.

**Comment by CGe0h** [comment]
Thank you so much !!! I have to try it and let you know...
Best
Christophe
