### ISSUE TITLE
[Feature request] Merging values of 2 form fields into 3rd field and passing all 3 fields on submission

### ISSUE THREAD

**Issue by leannerenee** [elementor/elementor#12823]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I am hoping for a way to combine the values of 2 form fields automatically into a 3rd hidden field, with a custom separator (e.g. a space) prior to the submission of the form so all 3 fields are passed on submission.

E.g.

field 1 (first_name) (type: text) = "John"
field 2 (last_name) (type: text) = "Smith"
field 3 (full_name) (type: hidden) = "John Smith" - automatically populated before submission (possible each time field 1 or 2 is updated).

All 3 fields are passed on submission of form

**Comment by DorShahar** [comment]
Hi,
Thank you for your feedback.
 
As for your request, you have 2 options:

1. Use actions after submit and the relevant shortcodes. You can read more about it here: (https://elementor.com/help/actions-after-submit)
2. Use JS to inject the relevant form field values into the structure you want ( see here: https://stackoverflow.com/questions/11563638/how-do-i-get-the-value-of-text-input-field-using-javascript )

Hope this helps.
