### ISSUE TITLE
Social Icons widget – Columns: Auto not working correctly

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#12833]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Social Icons widget – Columns: Auto not working correct. We are expecting tight alignment on the side.
This is Elementor 3.x issue.

## Steps to reproduce

See screenshots... Focus on the right side of the icons. We want, they be aligned.

![columns-auto-settings](https://user-images.githubusercontent.com/7617350/96013587-ba88ec80-0e45-11eb-833b-2b64c415d6b0.png)&#160;&#160;->&#160;&#160;&#160;&#160;![columns-auto-icons](https://user-images.githubusercontent.com/7617350/96013799-f58b2000-0e45-11eb-8c87-8c0d9dd490d7.png)

![columns-4-settings](https://user-images.githubusercontent.com/7617350/96013608-c1affa80-0e45-11eb-9f63-cc8860d412d6.png)&#160;&#160;->&#160;&#160;&#160;&#160;![columns-4-icons](https://user-images.githubusercontent.com/7617350/96012115-15214900-0e44-11eb-8e5a-2c20f1474383.png)

![columns-3-settings](https://user-images.githubusercontent.com/7617350/96013643-c7a5db80-0e45-11eb-9754-5f72f61878f5.png)&#160;&#160;->&#160;&#160;&#160;&#160;![columns-3-icons](https://user-images.githubusercontent.com/7617350/96012205-2b2f0980-0e44-11eb-9100-4ca4f7f6df81.png)

Columns: Auto and Columns: 4 in this case corresponds. But I think that expecting columns for Auto is 3, not 4, because we have 3 items.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodolphebertozzo** [comment]
Fix here : https://github.com/elementor/elementor/pull/12551

**Comment by lior-sh** [comment]
Hi  @shimsa,

Thanks for reporting.
We will address this issue soon and release a patch.
Please follow this thread for updates.
Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.12

Feel free to update

Thanks!

**Comment by urbancowboy1994** [comment]
Just updated to 3.0.12 and now there is no spacing at all between the icons. The Elementor preview screen shows is correctly in the editor, but not on the published site.

**Comment by JeroenvanderPoll** [comment]
I have exactly the same issue, after updating the spacign is removed.

**Comment by ReisingMedia** [comment]
I also am having a problem after updating to 3.012, however it's specific to mobile. Icons and spacing is as it should be both in the Elementor editor and in a resized browser window, however on  mobile (iphone - firefox, safari and chrome) there is a non-removable padding on the left hand side despite it being aligned center. This is the case on every page where I previously had these social media icons present. 

Has anyone opened up a new bug report for this?

**Comment by Grafi-k** [comment]
Hi, I have a problem with social icons widget, alignment in Iphone view I use center option, but the rusults are right alignment, anyone knows how to solve this issue or bug?. In Android works well, but I need in Iphone works the center alignment as well.
![social icons](https://user-images.githubusercontent.com/68169215/97602221-ac53d800-19d0-11eb-9716-b2529876c8d7.PNG)

**Comment by reachdigitalaus** [comment]
I have the same issue , all my icons have lost spacing, have tried auto, number in the cols and nothing works.

https://nimb.ws/WOB5Ab

**Comment by ReisingMedia** [comment]
> Hi, I have a problem with social icons widget, alignment in Iphone view I use center option, but the rusults are right alignment, anyone knows how to solve this issue or bug?. In Android works well, but I need in Iphone works the center alignment as well.
> ![social icons](https://user-images.githubusercontent.com/68169215/97602221-ac53d800-19d0-11eb-9716-b2529876c8d7.PNG)

Hey there, I just opened up a new Bug Report on this as the issue persists. Many people around the web seem to be having this issue and I've yet to find a fix. Is there anyway you can check to see if this is happening on a desktop version of Safari as well? All is fine on Chrome (desktop) but every browser in IOS it's skewed to the right.

**Comment by urbancowboy1994** [comment]
On Chrome (desktop and mobile), mine have no spacing AT ALL. They are bunched up together no matter what I try to do. In the editor, they show fine, but in the front-end there's this issue.
![Screenshot_20201120-205634_Chrome](https://user-images.githubusercontent.com/73248472/99865972-252ef580-2b73-11eb-99d5-4ec4cc58cf6e.png)

**Comment by sunnyt7** [comment]
Having issues too. It looks to be really poorly coded. It's using a grid class, but then has display: inline-block set, but then uses grid gap. Chrome and Firefox seem to cover most of the issues up, but it doesn't work well on Safari at all.
