### ISSUE TITLE
Multilanguage – make Elementor multilingual

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#12832]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I am convinced, that we need Elementor native multilingual support, also with WordPress import/export working.
Plugins works, but it is not so good and clean solution.

Multilanguage sites are quite often used, so it is essential feature.

What do you guys think about it? Can we count on this feature in the future?

Thank you.

**Describe alternatives you've considered**

Still using plugins :(

**Comment by Aviad-Herman** [comment]
Hi shimsa,
thanks for your suggestion. Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it. For now you can use either WPML, or Polylang for achieving this goal.

Thanks for the feedback
