### ISSUE TITLE
Elementor background slideshow and Woocommerce conflict?

### ISSUE THREAD

**Issue by dmiller643** [elementor/elementor#12836]
I have an issue that only occurs when the Woocomnmerce plugin is activated. The background slideshow images set in the inner section at the top of the page do not display.   When Woocommerce is deactivated they display.
https://inks.cleverdemo.co.uk/

I have the latest versions of Elementor, Elementor Pro and Woocommerce.

**Comment by lior-sh** [comment]
Hi @dmiller643,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.
