### ISSUE TITLE
slide widget not works in my site , i use elementor pro 

### ISSUE THREAD

**Issue by ssathamenterprises** [elementor/elementor#12845]
slide widget not works in my site ( i use revo wordpress theme template )

when i add slides its shows perfectly everything looks good ( during edit )

after i update the page goes live ( the slides are missing )

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites**.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**

Without it we simply can't help.

Thanks.
