### ISSUE TITLE
🚀 Feature Request: Image Widget Custom Position for Object Fit Cover - [ED-10423]

### ISSUE THREAD

**Issue by zahnd** [elementor/elementor#12849]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When adding an image with the image widget and setting the object-fit to cover, I'm not able to set a custom position of the image. In fact, it's not possible to set a position like "center, center", "center, bottom" (like in the background image setting of columns), etc. at all. 

**Describe the solution you'd like**
In the above scenario, I would like to have at least the option to set a custom position of the image with object-fit "cover". 

**Describe alternatives you've considered**
I tried to add a nested column, set a background image with a fit of cover, and positioned it accordingly. Unfortunately, as I want to let the image overlap another element (with changing the margin of the object), I cannot do that as columns can't be moved left or right like that.

**Comment by black-eye** [comment]
+1

**Comment by DorShahar** [comment]
Hi @zahnd 
Please attach a screenshot or video with the desired UI and the current situation. I want to be 100% aligned with what you asked. 

Thanks.

**Comment by zahnd** [comment]
Hi @DorShahar 
Thank you for your message. Good question! I tried to figure out what I was trying to do and think I either mixed things up or made a wrong description. Sorry about that!

I think what I really wanted to say is that for the widget "image" it would be useful to have an option to set the image size to "cover" like it's possible within the "Background" settings of a section. Here's an example:
<img width="530" alt="Screenshot 2020-11-09 at 16 33 21" src="https://user-images.githubusercontent.com/3197552/98561928-bc5d9880-22a9-11eb-8413-e0c4bc66eb45.png">

Meanwhile, I could solve my problem (overlapping elements) by using an inner section but it's not that pretty as it would be by using the image widget. Have a look at https://dev.sunchasingtravelers.com/about/ and the images and descriptions of us in the middle of the page.

What I had in mind was to use the image widget and give it a certain height and width. To only show a certain section of the image, I had the idea to set the image size to cover and position it with a custom position within the image widget. A layer mask in Photoshop would be the best comparison for what I tried to do. 

I hope this helps to understand what I really wanted to do :). Sorry again for not being accurate from the beginning.

Cheers, Stefan

**Comment by DorShahar** [comment]
Hi @zahnd , 
No worries :) 

1. As for the Image position, I see your point.
2. To make the overlay, I suggest you avoid inner sections and use a divide section, and there play with image position absolute. 
But - I think the best option for you is to ask in one of our Facebook communities, you have a lot of experienced designers there.

**Comment by zahnd** [comment]
Hi @DorShahar ,
Thank you very much for your reply and hint with the divide section. I'm going to try this as well as asking in the community. 
Cheers, Stefan
