### ISSUE TITLE
Testimonial carousel is showing all testimonials 

### ISSUE THREAD

**Issue by Rebelzgmac** [elementor/elementor#12841]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

This was working. But now the testimonial  carousel in Elementor Pro is showing ALL of the testimonials (instead of one at a time) and I am getting these errors in the console:
jquery.js?ver=1.12.4-wp:2 Uncaught Error: Syntax error, unrecognized expression: .menu-item-has-children > a[href*=#]
    at Function.ea.error (jquery.js?ver=1.12.4-wp:2)
    at ea.tokenize (jquery.js?ver=1.12.4-wp:2)
    at ea.select (jquery.js?ver=1.12.4-wp:2)
    at Function.ea [as find] (jquery.js?ver=1.12.4-wp:2)
    at n.fn.init.find (jquery.js?ver=1.12.4-wp:2)
    at new n.fn.init (jquery.js?ver=1.12.4-wp:2)
    at n (jquery.js?ver=1.12.4-wp:2)
    at HTMLUListElement.<anonymous> (theme-addons.js?ver=5.5.1:1492)
    at Function.each (jquery.js?ver=1.12.4-wp:2)
    at n.fn.init.each (jquery.js?ver=1.12.4-wp:2)

 
## Steps to reproduce

Create a testimonial slider.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.3.23
	PHP Max Input Vars: 3000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1
	Site URL: https://entrustmortgage.ca
	Home URL: https://entrustmortgage.ca
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 1000M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Stoni Child
	Version: 1.0
	Author: WebGeniusLab
	Child Theme: Yes
	Parent Theme Name: Stoni
	Parent Theme Version: 1.0.7
	Parent Theme Author: WebGeniusLab

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

== Active Plugins ==
	AWSM Team Pro
		Version: 1.8.1
		Author: AWSM Innovations

	Calculated Fields Form
		Version: 1.0.418
		Author: CodePeople

	CC Canadian Mortgage Calculator
		Version: 2.0.5
		Author: Calculators Canada

	Custom Facebook Feed Pro Personal
		Version: 3.10.5
		Author: Smash Balloon

	Elementor
		Version: 3.0.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.5
		Author: Elementor.com

	Really Simple SSL
		Version: 3.3.5
		Author: Really Simple Plugins

	Slider Revolution
		Version: 6.1.0
		Author: ThemePunch

	Smush
		Version: 3.7.1
		Author: WPMU DEV

	Stoni Core
		Version: 1.0.7
		Author: WebGeniusLab

	UpdraftPlus - Backup/Restore
		Version: 2.16.30.24
		Author: UpdraftPlus.Com, DavidAnderson

	WP Fastest Cache
		Version: 0.9.1.1
		Author: Emre Vona

	Yoast Duplicate Post
		Version: 3.2.6
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Endurance Browser Cache
		Version: 0.4
		Author: Mike Hansen

	Endurance Page Cache
		Version: 2.0.4
		Author: Mike Hansen

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== Elements Usage ==
	
	page : 6
		counter : 4
		divider : 5
		heading : 1
		icon : 8
		image : 10
		image-gallery : 1
		spacer : 45
		text-editor : 26
		wgl-blog-hero : 1
		wgl-button : 2
		wgl-clients : 1
		wgl-double-headings : 17
		wgl-image-layers : 1
		wgl-info-box : 9
		wgl-portfolio : 1
		wgl-progress-bar : 4
		wgl-team : 1
		wgl-testimonials : 1
	section : 16
		counter : 8
		divider : 2
		image : 3
		spacer : 6
		text-editor : 3
		wgl-button : 1
		wgl-clients : 1
		wgl-double-headings : 2
		wgl-image-layers : 1
		wgl-info-box : 21
		wgl-pricing-table : 3
		wgl-toggle-accordion : 1
	widget : 0
		heading : 1
		text-editor : 1
		wgl-info-box : 1
		wgl-testimonials : 2
	wp-post : 0
		button : 2
		divider : 2
		global : 3
		heading : 12
		icon : 8
		image : 35
		spacer : 169
		template : 3
		text-editor : 113
		wgl-blog-hero : 2
		wgl-button : 4
		wgl-clients : 1
		wgl-double-headings : 10
		wgl-info-box : 14
		wgl-testimonials : 1
		wgl-toggle-accordion : 6
	wp-page : 7
		divider : 1
		image : 1
		spacer : 1
		text-editor : 2
		wgl-testimonials : 1

== Log ==
	
PHP: showing 2 of 2PHP: 2019-10-31 22:48:37 [warning X 1][/home2/thehaqd6/public_html/area11/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(calculator_icon.png): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-01-10 06:25:40 [notice X 21][/home2/thehaqd6/public_html/area11/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2019-11-01 20:12:58 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:32:64106] this.ui.apply.add is not a function 
JS: 2019-11-01 20:47:41 [error X 30][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.5:2:38717] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/images/placeholder.png> as `thumbnail` value. Expected array or object.',
)]
JS: 2019-11-01 21:00:52 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view49793\") has already been destroyed and cannot be used. 
JS: 2019-11-11 23:36:49 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.7.5:2:39895] n.attributes[e.name].each is not a function 
JS: 2020-01-10 06:10:45 [error X 80][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.3:2:46796] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `thumbnail` value. Expected array or object.',
)]
JS: 2020-01-10 06:27:20 [error X 12][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.3:2:56072] Cannot read property \'select2\' of undefined 
JS: 2020-01-10 06:27:21 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2631\") has already been destroyed and cannot be used. 
JS: 2020-01-10 06:33:56 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2896\") has already been destroyed and cannot be used. 
JS: 2020-01-10 06:35:16 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4771\") has already been destroyed and cannot be used. 
JS: 2020-01-10 06:53:48 [error X 1][https://area11.divadesigntestsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view9073\") has already been destroyed and cannot be used. 

Log: showing 20 of 252020-01-15 05:29:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.3',
)]
2020-01-24 17:38:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-02-27 18:41:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.4',
  'to' => '2.9.3',
)]
2020-02-27 18:41:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-05-05 19:02:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.8',
)]
2020-05-05 19:02:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.9.3',
)]
2020-05-19 17:02:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-05-28 18:45:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-05-28 18:45:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-10-15 16:26:51 [info] elementor::elementor_updater Started 
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-10-15 16:26:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '3.0.11',
)]
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-10-15 16:26:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-10-15 16:26:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '3.0.11',
)]
2020-10-15 16:26:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.5',
  'to' => '3.0.5',
)]

				

</details>

**Comment by ntlnicklas** [comment]
I have similiar (or maybe same issue depending on how threadstarter set up the component).   If I set desktop to 3 slides per view. Then setting new value for mobile in setup and set it to 1 slide per view. It will still use desktop setting and show all 3 on mobile also.  If i set it to 1 per view on desktop then it will also use 1 on mobile.

**Comment by DorShahar** [comment]
Hi @
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.
Soon we will release new versions for Core and Pro (v3.1.0). If the problem persists, please reopen a new issue. 

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
