### ISSUE TITLE
Responsive tablet version is mess-up 

### ISSUE THREAD

**Issue by hosamhos60** [elementor/elementor#12846]
when i make tablet version of my page, it looks good in the preview while editing, but after publish and review how the page looks like in tablet version on chrome it's a mess!

**Comment by lior-sh** [comment]
Hi @hosamhos60,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
* Screenshot/Video
Without it, we simply can't help.
Thanks.
