### ISSUE TITLE
[Dev Docs] Add a documentation on how to add field type to Pro Forms widget (JS + PHP)

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#12848]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to add a field type to the Pro version Forms widget. I found code samples of the PHP side (extending Field_Base and registering the new classes) on this issue tracker but not in the developer documentation. The problem I have is that there is no documentation on the web on how to add JavaScript for this new field: I found the `depended_scripts` property but how to target the field (what's the equivalent of `elementorFrontend.hooks.addAction('frontend/element_ready/widget_name.default', callback)`?), where to register the script (in the __construct?),...

**Describe the solution you'd like**
For widget, we have this great page: https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/

Can you create a page explaining how to add field type to the Pro Forms widget (JS + PHP)?

**Describe alternatives you've considered**
Doing some dirty jQuery('body').on('click', '.field_type', callback);....

**Comment by bytebunch** [comment]
I have same problem, Please provide proper documentation for "how to add new field type to Pro Forms widget"

**Comment by sunshineandmoonshine** [comment]
I'd like something similar.

**Comment by sf-steve** [comment]
Same, this would be very useful

**Comment by DorShahar** [comment]
Thank you guys for reporting this.
We will handle it.
Notice that it will take time.

**Comment by Fancy11111** [comment]
Any update here? Would be greatly appreciated
