### ISSUE TITLE
Nav Menu more control and hover animation smoother?

### ISSUE THREAD

**Issue by neosaveme** [elementor/elementor#12856]
I don't know if the people of elementor are nice or kind to notice this little remark

I created a header exactly like this [site inspiration](https://modern.realhomes.io/)

I did not find how to do a right or left alignment neither padding nor margins I used this piece of code

```
/ * menu nav link* /
.sm-nowrap .menu-item a {
padding-left: 15px! important;
}
```

I would like to have a more fluid menu animation like on the site inspiration.

 for the moment I don't want to use a plugin for menus..

Or mayble someone can tell me the code to make the hover animation smoother?

**Comment by DorShahar** [comment]
Hi @neosaveme 
We are not supporting that kind of thing at the moment. As you mention, you can use CSS to create what you need.

In the future, we will consider adding more animations and possibilities to design the menu. 

Thanks.
