### ISSUE TITLE
Fallback in custom post query

### ISSUE THREAD

**Issue by matar360** [elementor/elementor#12854]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by matar360** [comment]
When creating a custom query for the "posts" widget - the fallback (when the query returns zero posts) is to show all the posts. INSTEAD OF SHOWING NONE OF THEM.

I know that this how it was before version 2.5 and then it fixed. but now it happened again in the latest version.

**Comment by Aviad-Herman** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* System info.

Without it we simply can't help. Please make sure to include the code snippet you are trying to add.

Thanks.
