### ISSUE TITLE
Bug - theme builder - URGENT !!!

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12855]
After publishing a template, the defined conditions do not work, therefore, once a template is published, it does not apply to the defined pages.

Create a template (header, single page template or footer), publish it and set conditions and view

**Comment by lior-sh** [comment]
Hi @rodolphebertozzo,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
