### ISSUE TITLE
Re-Ordered Global Fonts & Colors

### ISSUE THREAD

**Issue by iqbalmauludy** [elementor/elementor#12852]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

**What problem is your feature request going to solve? Please describe.**
When you add lots of colors or fonts to the global settings, it's very easy to organize everything by title so it's more organized and clean.

**Describe the solution you'd like**
I want all the colors to be freely rearranged, maybe drag / drop would be good for this.

**Comment by black-eye** [comment]
+1

**Comment by lucafagherazzi** [comment]
+1

**Comment by shilo-ey** [comment]
I merged this issue with #12203, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by TurnkeyProfit** [comment]
Thank you.
