### ISSUE TITLE
✅ 🚀 Feature Request: Update Heading Widget with Hover Style Options - [ED-13603]

### ISSUE THREAD

**Issue by acal** [elementor/elementor#12877]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

For the Heading Widget... I often use them with hyperlinks. There is no Hover style options in the Style tab. It would close the loop if Elementor offered Hover styles as found in many of the other widgets. Currently, I write CSS to handle this but from a layperson/client perspective this is not great.
Thanks.

**Comment by nicholaszein** [comment]
Hello there @acal!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor version 3.26.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
