### ISSUE TITLE
Mobile Menu Cut Off

### ISSUE THREAD

**Issue by twomensocial** [elementor/elementor#12876]
Website mobile menu gets cut off 
![image](https://user-images.githubusercontent.com/73148170/96529253-415f1e80-12b7-11eb-9fb8-dc46383f92b8.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
