### ISSUE TITLE
Advanced Option (Before & After) on Archive Title in Search Result Template Not Working

### ISSUE THREAD

**Issue by itcomindo** [elementor/elementor#12885]
Advanced Option (Before & After) on Archive Title in Search Result Template Not Working, it's still show "search result for".

Case & E.g:

I add some text (e.g) "MY TEXT" in before "Archive Title", but in front page still show and become: MY TEXT + "Search Results for"

note: include context set is NO

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
