### ISSUE TITLE
Gap between Column border radius and overlay 

### ISSUE THREAD

**Issue by JohnMulderFrance** [elementor/elementor#12889]
#12733  Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

When setting a border with a radius on a column with an overlay, there is a little gap in all corners as if the overlay has a different radius. 

[Screenshot 2020-10-21 at 11 26 00](https://user-images.githubusercontent.com/37953844/96701049-74291580-1390-11eb-900a-553ab4ff348b.jpg)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
