### ISSUE TITLE
Urgent : Advance Tabs Elementor

### ISSUE THREAD

**Issue by saeedLima** [elementor/elementor#12888]
Hi

In the following page :
https://taflab.berkeley.edu/research

Advance Tab doesn't work properly. Tabs aren't clickable.

Tabs are clickable for the administrators that login in the site. But it doesn't work for others.

**Comment by khelochagabia** [comment]
I think it is not a bug. email me at khel@khelochagabia.com I can help you with it

**Comment by Aviad-Herman** [comment]
Hi saeedLima,
Advanced tabs is actually a widget that belongs to a different plugin you installed named "Essential Addons" which does not belong to Elementor. You should contact them for support. I looked them up online for you, this it their support link: https://essential-addons.com/elementor/support/

Hope they help you fix the issue ASAP. Good luck!
