### ISSUE TITLE
Possibility to add category name above post title

### ISSUE THREAD

**Issue by dennisaarts** [elementor/elementor#12895]
Hi,

Could you please add the option to show a category title/ name above or below a post title?
Like in this example:

![image](https://user-images.githubusercontent.com/71874088/96741440-13b2cc00-13c2-11eb-8e2e-38ea0ccfad2b.png)

Thank you!

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
