### ISSUE TITLE
Integration with Mailster

### ISSUE THREAD

**Issue by attunist** [elementor/elementor#12898]
Please provide integration with the popular eNewsletter plugin "Mailster".

Elementor's forms are way more manageable and good-looking but the user data provided need to populate in real time specific Mailster lists so that drip and other mail marketings may be initiated with less steps and better control.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/10871 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
