### ISSUE TITLE
Column swipe in mobile

### ISSUE THREAD

**Issue by soundplay-production** [elementor/elementor#12890]
I thought it was very useful to have the columns in carousel mode only on mobile. The problem is that you create the stack by converting columns to rows .. while it might be interesting to have a button to make these columns simple elements for the carousel by swiping left and right.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4440 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by daniilicic** [comment]
@DorShahar I don't think this issue is merged correctly. This one is about columns layout on mobile, and the one you merged it with is for the  Posts / Archive loop item. 😕

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Carousel widget released with Elementor Pro v3.11.0! 🥳 

With the new Loop Carousel widget, you can customize your post listings with custom templates (including WooCommerce Products)! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Carousel layout, design, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-carousel/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Nested Accordion widget released with Elementor v3.14.0! 🥳 

With the new Nested Carousel widget, you can customize the content of each Carousel Item with nested elements! 💪 
Drag & Drop widgets to create complex designs, fine-tune your carousel layout, design, interactions, and much more!

Check out the beta announcement here: https://elementor.com/help/carousel-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
