### ISSUE TITLE
Elementor not render dynamic element ID or class in editor

### ISSUE THREAD

**Issue by webdevs-pro** [elementor/elementor#12896]
I`m trying to add dynamic ID or class to element (post ID with prefix) or section but it work only on frontend. If I add ID as a text it render normally in editor, only dynamic tags not rendering in editor. Elementor 3.0.12 and Elementor Pro 3.0.5

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.
_You can also contact our support for help._ 

Thanks.
