### ISSUE TITLE
Transforming GSheets into Layout (as steinhq.com)

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#12894]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will facilitate changes made by customers to Calendars, for example.

**Describe the solution you'd like**
Every new line in GSheets it will create a new layout based on those parameters as in https://steinhq.com/

**Describe alternatives you've considered**
I've already used Stein itself, but it requires recurring payment and is not integrated with the Elementor layout, I have to do HTML from scratch, I also considered Table Ninja, but it is still just a table.

**Additional context**
![image](https://user-images.githubusercontent.com/6594795/96728640-afc0e100-138a-11eb-86a7-1389e3046569.png)
### TO
![image](https://user-images.githubusercontent.com/6594795/96728937-fc0c2100-138a-11eb-8a5b-61747258d287.png)

**Comment by DorShahar** [comment]
Hi @ofmarconi  
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
