### ISSUE TITLE
I want a text hoover

### ISSUE THREAD

**Issue by julaskip** [elementor/elementor#12904]
HI,
I noticed that this feature (text hoover) is missing in the latest stable version of Elementor ( Elementor Pro. )
I have currently a black text, and when I click on it I want that it changes to white.
I would like that the color of text changes as soon as I click on it on my website (hoover setting but not for background but for text)

Thank you

**Comment by rodolphebertozzo** [comment]
Hi,your functionality seems interesting to me, I will send a PR!

**Comment by DorShahar** [comment]
Hi @julaskip 
You can use custom CSS for that. 
Use `:active` and `:focus`.

You can see an explanation in this [StackOverflow](https://stackoverflow.com/questions/42134731/css-change-button-style-after-click) question.
