### ISSUE TITLE
Button font weight is coming from link font weight

### ISSUE THREAD

**Issue by scott8035** [elementor/elementor#12911]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
At run time, or in the WYSIWYG template editor, the on-hover Button font weight being used is coming from the site setting typography section for the Link font weight. In this case the link settings were coming from the custom typography button (the pencil) instead of the global setting (the globe). What should have happened, obviously, is the the on-hover button font weight should have come from the site settings button settings.

**Comment by shilo-ey** [comment]
Hi @scott8035 
Thanks for your feedback.

Elementor's Button widget is actually an `<a>` tag, therefore, if no setting were made to the Button tag in Theme Style - the changes on Theme Style > Link will affect the attributes that weren't set on the button.

Simply add the fallback font-weight property you wish to add to your Button tags in Theme Style > Buttons and it should override the Link setting.

Thanks
