### ISSUE TITLE
Disable lightbox feature for basic image gallery

### ISSUE THREAD

**Issue by nepa** [elementor/elementor#12913]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am using the **Basic Image Gallery** component of Elementor.

In the gallery settings, I enabled the "Link" option and set it to "Media File". I disabled the "Lightbox" option and set it to "No", because I use a third-party lightbox plug-in (_Easy FancyBox_) and do not want the Elementor lightbox to show up.

I expect no Elementor lightbox to show, only the Easy FancyBox one. However, when I click on an image, actually two overlays open, one stacked upon the other.

**I assume that the Elementor lightbox is not disabled correctly on a per-gallery level.**

When I disable the lightbox feature of Elemetor completely (in the _Site Settings_), the gallery works as expected (i.e. only the plug-in's lightbox appears).

## Steps to reproduce

1. Add basic image gallery to page.

2. Add multiple images.

3. Set "Link" option to "Media File" and disable "Lightbox" feature.

4. Publish page and click on first gallery image.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

WordPress v. 5.5.1
Elementor v.  3.0.12

**Comment by lior-sh** [comment]
Hi @nepa,

Thanks for reporting.
We will address this issue soon and release a patch.
Please follow this thread for updates.
Thanks!

**Comment by black-eye** [comment]
@lior-sh Hopefully fix comes sooner than in a year. This issue was already reported and tagged as a bug more than a half year ago and it’s still here: https://github.com/elementor/elementor/issues/11193

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.4

Feel free to update!

**Comment by nepa** [comment]
Thanks, works for me.
