### ISSUE TITLE
It would be good to be able to see the details of a global widget on the Elementor Edit page

### ISSUE THREAD

**Issue by Ostii** [elementor/elementor#12914]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Having to click on Edit or activate the Navigator to see which Global Section is on the page.

**Describe the solution you'd like**
When I look at the Global section on the page I want to see the name of it.

**Describe alternatives you've considered**
1. Opening the Navigator and finding the name.
2. Clicking on the Edit Global Widget button to see the nam

Neither of these is ideal.

**Additional context**

![Elementor___Setting_The_Scene](https://user-images.githubusercontent.com/5764507/97070864-66d98880-1627-11eb-84ea-2503076f10ee.jpg)

**Comment by DorShahar** [comment]
Hi @Ostii 
Thank you for your input.
This UI/UX change is not in our focus at this point. If there will be more requests like that, we will consider making a change.

In the meanwhile - It looks that your workaround by using the navigator and there changing the name of the widget (like global_<widget name> ) is the best option.

Thank you for your understanding
