### ISSUE TITLE
Enforce A Featured Image On Pages

### ISSUE THREAD

**Issue by jonnygrm** [elementor/elementor#12937]
## Prerequisites
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like some way of enforcing featured images on pages designed within Elementor

**Describe the solution you'd like**
The ability to set featured images as mandatory within new Elementor pages

**Describe alternatives you've considered**
PHP code within a theme's functions.php. I could get it working for WordPress pages but not Elementor created pages.

**Additional context**
We want to enforce a professional look and feel for a posts widget that is displaying our "What's new" pages.

**Comment by Aviad-Herman** [comment]
Hi @jonnygrm ,
Thanks for taking the time to submit this request. Featured images are a wordpress entity and we try to avoid forcing unexpected behavior on wordpress core. It is possible to develop a personal solution to this issue if you have coding experience, or hire someone to do it for you.

Please don’t hesitate to submit more requests in the future.

We appreciate your time.
