### ISSUE TITLE
How To Import Templates Progammatically?

### ISSUE THREAD

**Issue by BackuPs** [elementor/elementor#12930]
Hi

I am using this code.

`

		if ( did_action( 'elementor/loaded' ) ) {
			

				require_once WP_PLUGIN_DIR .
					'/elementor/includes/db.php';	
				require_once WP_PLUGIN_DIR .
					'/elementor/includes/template-library/sources/base.php';	
				require_once WP_PLUGIN_DIR .
					'/elementor/includes/template-library/sources/local.php';
					
					

				$local = new \Elementor\TemplateLibrary\Source_Local();
				
				
				if (method_exists($local,'import_template') && is_callable(array($local, 'import_template'))){
					  $filepath = '/var/docs/server.tst/public/wp-content/uploads/import/selements_block.zip';
					  $filename = 'selements_block.zip';
					  
					  $item_imported= $local->import_template( $filename, $filepath );
				}				

			

		}

But i get this error.

`

		Fatal error: Uncaught Error: Call to a member function iterate_data() on null in /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/base.php:313
		Stack trace: #0 /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/local.php(1372): Elementor\TemplateLibrary\Source_Base->process_export_import_content()
		#1 /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/local.php(879): Elementor\TemplateLibrary\Source_Local->import_single_template()
		#2 /var/docs/server.tst/public/wp-content/themes/champion/functions.php(55): Elementor\TemplateLibrary\Source_Local->import_template()
		#3 /var/docs/server.tst/public/wp-settings.php(514): include('/var/docs/serve...')
		#4 /var/docs/server.tst/public/wp-config.php(90): require_once('/var/docs/serve...')
		#5 /var/docs/server.tst/public/wp-load.php(37): require_once('/var/docs/serve...')
		#6 /var/docs/server.tst/public/wp-admin/admin.php(34): require_once('/var/docs/serve...')
		#7 /va in /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/base.php on line 313

What am i doing wrong?

**Comment by BackuPs** [comment]
Shouldn't elementor base.php include elementor db.php?  How can this error happen?

**Comment by Aviad-Herman** [comment]
Hi @BackuPs,
I asked our engineers to review your code and it looks OK.
One possibility is that there is a problem with your ZIP file. Can you try using your code to import the following file we created? [sample-templates.zip](https://github.com/elementor/elementor/files/5450488/sample-templates.zip)

Keep us updated.

**Comment by BackuPs** [comment]
Hi

Thank you for the feedback but the zip file is ok. The problem is that db->iterate_data() is NULL

the sample-templates.zip does not import anything.

The problem is that elementor plugin class has not run some how as all the public variables in the plugin class are still NULL

Do you want me to send my zip file?

Kind regards

**Comment by matipojo** [comment]
Hi @BackuPs Please try get the Source_Local instance via:
`$local = \Elementor\Plugin::$instance->templates_manager->get_source( 'local' );`
(and remove all `require_once` statements)

**Comment by BackuPs** [comment]
@matipojo 

that throws a fatal

Fatal error: Uncaught Error: Call to a member function get_source() on null in /var/docs/server.tst/public/wp-content/themes/striking_r_212/functions.php:42 Stack trace: #0 /var/docs/server.tst/public/wp-settings.php(537): include() #1 /var/docs/server.tst/public/wp-config.php(90): require_once('/var/docs/serve...') #2 /var/docs/server.tst/public/wp-load.php(37): require_once('/var/docs/serve...') #3 /var/docs/server.tst/public/wp-admin/admin.php(34): require_once('/var/docs/serve...') #4 /var/docs/server.tst/public/wp-admin/edit.php(10): require_once('/var/docs/serve...') #5 {main} thrown in /var/docs/server.tst/public/wp-content/themes/striking_r_212/functions.php on line 42

**Comment by matipojo** [comment]
@BackuPs try run your code on after the `elementor/init`:
`add_action( 'elementor/init', ...);` 
you can remove the `if ( did_action( 'elementor/loaded' ) )`.

**Comment by BackuPs** [comment]
HI

Thank you for your reply, But I need this to happen when a user clicks in the admin area on a button to install all the additional templates ..... not on init of elementor. How to accomplish that?

**Comment by Aviad-Herman** [comment]
Hey @BackuPs ,
I'm sorry but this is more of a support issue than a feature request or bug.
I can suggest requesting help via support or Elementpr's facebook community. There are some really talented developers in the community.

Feel free to post what you've found here so it can help other people facing the same issue.

Thanks!

**Comment by BackuPs** [comment]
Why dont you just answer the question the correct way?  Closing the issue after almost 14days going back and forth? I really can not appreciate this. Is this how elementor support works?

**Comment by Aviad-Herman** [comment]
Our GitHub is not a support channel, it's purpose is to submit feature requests, pull requests and to report bugs.

Elementor has pretty vibrant communities and many talented developers willing to help:
[Elementor community
](https://www.facebook.com/groups/Elementors)[Elementor pro community
](https://www.facebook.com/groups/elementor.pro.community/)

Thank you for understanding.

**Comment by SecDet65** [comment]
> Hi
> 
> I am using this code.
> 
> `
> 
> ```
> 	if ( did_action( 'elementor/loaded' ) ) {
> 		
> 
> 			require_once WP_PLUGIN_DIR .
> 				'/elementor/includes/db.php';	
> 			require_once WP_PLUGIN_DIR .
> 				'/elementor/includes/template-library/sources/base.php';	
> 			require_once WP_PLUGIN_DIR .
> 				'/elementor/includes/template-library/sources/local.php';
> 				
> 				
> 
> 
> 			$local = new \Elementor\TemplateLibrary\Source_Local();
> 			
> 			
> 			if (method_exists($local,'import_template') && is_callable(array($local, 'import_template'))){
> 				  $filepath = '/var/docs/server.tst/public/wp-content/uploads/import/selements_block.zip';
> 				  $filename = 'selements_block.zip';
> 				  
> 				  $item_imported= $local->import_template( $filename, $filepath );
> 			}				
> 
> 		
> 
> 	}
> ```
> 
> But i get this error.
> 
> `
> 
> ```
> 	Fatal error: Uncaught Error: Call to a member function iterate_data() on null in /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/base.php:313
> 	Stack trace: #0 /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/local.php(1372): Elementor\TemplateLibrary\Source_Base->process_export_import_content()
> 	#1 /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/local.php(879): Elementor\TemplateLibrary\Source_Local->import_single_template()
> 	#2 /var/docs/server.tst/public/wp-content/themes/champion/functions.php(55): Elementor\TemplateLibrary\Source_Local->import_template()
> 	#3 /var/docs/server.tst/public/wp-settings.php(514): include('/var/docs/serve...')
> 	#4 /var/docs/server.tst/public/wp-config.php(90): require_once('/var/docs/serve...')
> 	#5 /var/docs/server.tst/public/wp-load.php(37): require_once('/var/docs/serve...')
> 	#6 /var/docs/server.tst/public/wp-admin/admin.php(34): require_once('/var/docs/serve...')
> 	#7 /va in /var/docs/server.tst/public/wp-content/plugins/elementor/includes/template-library/sources/base.php on line 313
> ```
> 
> What am i doing wrong?
 Hi @BackuPs try this:
 
 ```php
 add_action( 'elementor/init', function(){
			$path = __DIR__ . "/inc/el.json";
			$name = basename($path);

			\Elementor\Plugin::$instance->templates_manager->import_template([
				'fileData' => base64_encode(file_get_contents($path)),
				'fileName' => $name
			]);
		} );
 ```
