### ISSUE TITLE
Switching the page layout does not refresh the preview the first time

### ISSUE THREAD

**Issue by gerasimovdaniel** [elementor/elementor#12942]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Switching the page layout does not refresh the preview the first time. Following page layout switching does refresh the preview.

## Steps to reproduce

Edit any page in Elementor.
Go to Settings -> General Settings.
Switch Page Layout.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Elementor - 3.0.12, WP - 5.5.1, Twenty Twenty-One
</details>

**Comment by Aviad-Herman** [comment]
Hi @gerasimovdaniel,
Thanks for the detailed bug report.
We are working to fix the issue (#124730).
