### ISSUE TITLE
Enable plugin auto update for Elementor Pro

### ISSUE THREAD

**Issue by lupo2021** [elementor/elementor#12949]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
WP has enables automatic plugin update function. 
This is not supported in Elementor Pro

**Describe the solution you'd like**
Enable the function in Elementor Pro

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/12615 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
