### ISSUE TITLE
Dynamic tags issue with button

### ISSUE THREAD

**Issue by klanash** [elementor/elementor#12959]
Hi, this is just to report a small things

If you try to do like a "back to" button, for exemple an article page, you will try to use the "terms" with the dynamic tags but the link is injected outside the button.

<img width="672" alt="Capture d’écran 2020-10-29 à 13 50 24" src="https://user-images.githubusercontent.com/10233829/97576426-71609d00-19ee-11eb-8b5f-0069a031c92b.png">

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
