### ISSUE TITLE
Adding a colour picker custom field (ACF) to categories to dynamically reference them for styles in a posts loop

### ISSUE THREAD

**Issue by MartyFly** [elementor/elementor#12952]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The ability to assign colours to categories

**Describe the solution you'd like**
By adding a colour picker custom field (ACF) to categories I would like to dynamically reference them for styles in a posts loop (or when creating a custom loop in plugins such as Ele Custom Skin)

**Comment by parfilov** [comment]
+1
For now custom fields colors works only at the archive page. Will be great to set colors for terms inside the loop.

**Comment by rami-elementor** [comment]
Hi @MartyFly @parfilov 

I'm closing this issue as this is not the place to ask feature requests for 3rd party plugins (Ele Custom Skin)

In addition, the new Elementor Loop Builder should allow you to that without the external plugin.
