### ISSUE TITLE
Elementor toggle closed by default in WordPress 5.6 beta2

### ISSUE THREAD

**Issue by andy00087** [elementor/elementor#12958]
When trying to edit a page with Elementor with the WordPress 5.6 beta, the Elementor toggles are closed by default.
Tested on a fresh WordPress installation (with WordPress 5.6-beta2-49360) with no plugins except Elementor free.
![aaaaaaa](https://user-images.githubusercontent.com/7100937/97573764-89ceb880-19ea-11eb-886b-ce4308011cda.png)

**Comment by rodolphebertozzo** [comment]
Hi,
This is due to the fact that the show method of jQuery v3 does not modify the "display" property of an element unless it is attached to the DOM.
Fix in next version !

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.0

Feel free to update

Thanks!
