### ISSUE TITLE
Edit with Elementor Button Missing in 3.0.7 and Newer

### ISSUE THREAD

**Issue by pegues** [elementor/elementor#12951]
As of this writing, Elementor 3.0.12 is out.

The "Edit with Elementor" button has been missing from the frontend of my custom theme for a few weeks. I've been trying to hunt down what the issue is, such as JS issues,, issues with PHP in my custom theme, etc. I've gone so far as to completely tear down my custom theme to fully barebones, and the button is still missing. I've switched to TwentyTwenty, and the button then reappears. There are other custom themes I have in which the button appears.

The workaround that I figured out through trial and error is to downgrade Elementor, but this workaround only works for the initial page reload in the frontend. I first downgraded to 3.0.8, then 3.0.7. After downgrading Elementor each time, I would regenerate the CSS. I then downgraded to 3.0.6 and regenerated the CSS, and the button appeared again on initial page load in the frontend. After reloading a page the second time, the button disappears again.

I've seen no JS errors in the console log, and no PHP errors or warnings are being thrown that would cause anything like this to happen.

I've also tried installing older versions of WordPress without downgrading Elementor, and that didn't make a difference in showing the button.

**Comment by Sidlegionair** [comment]
Can confirm, I also have multiple sites facing this issue.

**Comment by pegues** [comment]
As of continued troubleshooting last night, the only release of Elementor in the 3.x build that keeps the "Edit with Elementor" button visible is 3.0.8.1 using the latest WordPress.

**Comment by sf-steve** [comment]
Same, just upgraded to fix the posts widget pagination bug, and having this issue.

**Comment by faerieian** [comment]
Same me too

**Comment by perks98** [comment]
I did get the issue but I discovered on our websites that we had an optimisation plugin that aggregate JS files, once that option was disabled it came back, it also messes with the multi-step feature of the forms widget. Some hosting providers have web optimisation in the hosting, that could also play a part.

Not sure if that helps anyone or applies to this?

**Comment by Sidlegionair** [comment]
@shilo-ey Any chance you can give us some insight on when we could expect the fix to ship so I can provide clients with a rough ETA?

**Comment by pegues** [comment]
I started development on a new site and theme on Friday, and the issue is there as well. Running 3.0.8.1 with the latest WP build has the "Edit with Elementor" button showing. Make sure that if you downgrade from the latest Elementor (3.0.12 as of this writing) to 3.0.8.1, make sure to regenerate your CSS, otherwise you will still not see the "Edit with Elementor" button. Steps below:

1. /wp-admin/admin.php?page=elementor-tools#tab-versions and downgrade to 3.0.8.1.
2. After successfully downgrading via rollback, click the "Regenerate Files" button to regenerate your CSS. /wp-admin/admin.php?page=elementor-tools#tab-general
3. Clear your browser cache to be on the safe side.

**Comment by pegues** [comment]
@shilo-ey I don't have Autoptimize installed. Never even used Autoptimize before.

**Comment by IT-VBFK** [comment]
I use Autoptimize and Elementor 3.0.13. But as long as I activate the checkbox "Also optimize for registered editors / administrators?" the "Edit with Elementor" button is not displayed.

**Comment by Sidlegionair** [comment]
@shilo-ey No Autoptimize here either.

**Comment by Sidlegionair** [comment]
Resolved with Elementor 3.0.13, no auto-optimize installed. Thanks @shilo-ey!

**Comment by pegues** [comment]
I've just had a chance to update to 3.0.13, then regenerated the CSS. The "Edit with Elementor" button is still available!!! I then upgraded to the latest build of WordPress (5.5.3) and the button still remains. Thank you for the fix!
