### ISSUE TITLE
How to change Section settings default value?

### ISSUE THREAD

**Issue by atripolskyy** [elementor/elementor#12965]
I need to set another **email_to** default value, and I don't need administrator email.
Is there way to implement it?
Thank you!

**Comment by DorShahar** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests.
GitHub issues ARE NOT FOR SUPPORT!

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

thanks.
