### ISSUE TITLE
🔗 🚀 Feature Request: dynamically (ajax loaded content) Popups (Duplicate of #7106)

### ISSUE THREAD

**Issue by Insomnia88** [elementor/elementor#12966]
## Prerequisites
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For example forms that open a popup after submit containing additional information based on the sent data (that wasn't there at pageload). Especially for stuff like e-commerce and upselling this is important when you focus on high interactivity. 
Additionally it would slightly improve the performance since the popup is only loaded when it's needed and not on every page at render time.

**Describe the solution you'd like**
Just like the regular popup builder but with an additional checkbox to call the popup as ajax-request. The parameters will be send via POST or GET method so that I can use these for examples in a shortcode included in the popup.

**Describe alternatives you've considered**
I tried it with manually catching the `submit_success` event calling a function to do the stuff but I need to use a seperate js plugin for popups and html/js/styles of my current elementor theme just to fake the content of it.
I also looked for other elementor plugins that might do it but can't find any free. I found "jetpopup" which has a switch for ajax content loading but I havn't tested it (.. because I don't want to pay for it when I already own elementor pro and this should be an included feature)

**Comment by willryanuk** [comment]
This is a more specific request, but the general request is allowing Elementor to be loaded over AJAX, and loaded into a target HTML element. i.e. loading Elementor lazily.

Here is the general request:
https://github.com/elementor/elementor/issues/11493

**Comment by mredodos** [comment]
+1

**Comment by ofmarconi** [comment]
+1

**Comment by lith-imad** [comment]
+1

**Comment by itsinalis** [comment]
+1 To the functionality of loading dynamic elements lazily

**Comment by imihaiart** [comment]
+1 
Cmooon Elementor devs!!!
It's already 3+ years!

I'm trying to load a listing grid in a popup and it just messes around and not updating on ajax!

We really need using AJAX content in elementor popups!

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #7106

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

Kind regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.26.0! 🥳 

You can now use the **Off-Canvas** widget inside your **Loop Item** templates to display additional Dynamic Content for each post in your **Loop Grid** widgets! 🎉 🥳 🙌 

You can learn more about the Off-Canvas widget (and how to use it) here: 
https://elementor.com/help/off-canvas-widget/
And about the Loop Grid here: 
https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
