### ISSUE TITLE
Inline background images to HTML

### ISSUE THREAD

**Issue by mrbenjaminjo** [elementor/elementor#12973]
Feature request

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Create an option to inline background images to HTML rather than CSS.

## Environment

Elementor.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
