### ISSUE TITLE
Selectively load JS - cut bloat, easily reduce page load by 250k

### ISSUE THREAD

**Issue by mrbenjaminjo** [elementor/elementor#12976]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor could easily be faster by doing this:

eicons, waypoints.js, animation.js and swiper.js add a lot of weight to the page - make them optional - or better still don't load them if the functionality isn't used. eicons loads on the front end literally just for a hamburger icon.

**Describe alternatives you've considered**
Removing them with Asset Cleanup

**Additional context**
E doesn't need to be picked on for being bloated. Just make it lighter!

**Comment by MichaelDarko** [comment]
+1

**Comment by black-eye** [comment]
+1
And Elementor team, please do not try to fool us with the reply Elementor is the best optimized tool, it’s not bloated at all and couldn’t be done better. ;-)

**Comment by shimsa** [comment]
+1

**Comment by shilo-ey** [comment]
I merged this issue with #8572, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
