### ISSUE TITLE
I'm use selected2 to choose post in Elementor. But i cant limit number select post. Anyone can help me?

### ISSUE THREAD

**Issue by hotandat260399** [elementor/elementor#12972]
Here my code:
$this->add_control(
			'post_list',
			[
				'label' => __( 'Choose Posts', 'plugin' ),
				'type' => \Elementor\Controls_Manager::SELECT2,
				'multiple' => true,
                'options' => $options,
                'size'=>3,
				'default' => [],
			]
		);

**Comment by rami-elementor** [comment]
The Select2 control doesn't support limiting the number of selected items.

For more information check the Select2 dev docs at https://developers.elementor.com/docs/controls/classes/control-select2/
