### ISSUE TITLE
Background for menu items (buttons)

### ISSUE THREAD

**Issue by ttodua** [elementor/elementor#12971]
We would like to have the "background" color available for each navigation menu-item. At this moment, that is only possible under "hover" tab, 
![img](https://i.imgur.com/PY7YbYb.png)
so when we mousoever any item in "navigation menu", then that item can have the colored-background. 
However, we would definitely need to have backgrounds on items without need to hover. 

As mentioned, at this moment, there is only "Text-color" available, and the "background color" becomes available under "hover" tab, with its standard options (border-size px, etc)

**Comment by Aviad-Herman** [comment]
Hi,
Thanks for submitting this feature request. 
Just so I can understand you better can you attach a link or pictures of the effect you are trying to achieve (specifically why setting the entire element's background color isn't an option).

Thanks.

**Comment by ttodua** [comment]
Sorry, I dont understand why i can't simply set nav-item's background color. I dont want link or external image. Just a simple background color.

**Comment by Aviad-Herman** [comment]
The following menu was created in wordpress:
<img width="467" alt="Screen Shot 2020-11-08 at 23 13 47" src="https://user-images.githubusercontent.com/73067562/98484447-5c40f680-21c4-11eb-839e-d9fcd5106c54.png">

1. Background color is green (style tab-->dropdown)
2. Hover background color is grey (style tab-->main menu-->hover-->pointer color)

Is this what you asked for?

**Comment by leecollings** [comment]
Just my two cents here.

Firstly, why close it immediately after asking for more information?

Secondly, I don't think this is what the user is asking. They want to set an individual item to have a background colour initially, not the entire menu.

As they have said, the background colour option only appears on the 'Hover' settings, not the default state.

**Comment by ttodua** [comment]
@Aviad-Herman  No, that was not what I was asking, and @leecollings  perfectly said whatever answer I could have posted. kudos leecollings.

**Comment by Aviad-Herman** [comment]
Oh, I understand now.
Could you use custom CSS similar to the example bellow?

1. In the advanced panel, define a custom css id to the navigation widget
2. Add custom CSS to make the design you like.

The thing is, custom css is not robust. Things can get messed up if you change things on your site (like adding more items to your navigation menu), so make sure to test the behavior once in a while.

![image](https://user-images.githubusercontent.com/73067562/98485925-e2623a80-21ce-11eb-8678-bb27cb737f14.png)

**Comment by ttodua** [comment]
Sorry for saying, but I have feeling that you are just talking about quite different thing. I dont know how to express it better, while in previous my above comment, i have even named the example menu item (named `My Account`) from your screenshot, to say about what i was talking. But you still discussing quite different thing. 
I've quite clearly defined that in original post too. So, i dont think there remains any way to explain it again, just the last resort is screenshot:  https://i.imgur.com/dPxZneV.png
So, i want to customize the backgrounds of main items of menu.
