### ISSUE TITLE
Post List Pagination Error

### ISSUE THREAD

**Issue by ATOPBIO** [elementor/elementor#12984]
Hello,

I would like to report an error I experienced using the Post List Widget

Using a repeater loop template, I added child post list inside parent post list template.

Unfortunately, if a child list is inserted into the parent list, the pagination will produce a repeating bug for the pagination button. The pagination will be rendered for every list.

**Comment by ATOPBIO** [comment]
![image](https://user-images.githubusercontent.com/61521619/97878961-62e8ed00-1d30-11eb-9313-b6dc83bfea99.png)

**Comment by ATOPBIO** [comment]
I am no expert but would assume the way to resolve this would be to assign a unique pagination class for every post list, rather than the elementor-pagination class.

I might be wrong, but I hope it contributes.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
