### ISSUE TITLE
Add option to hide "← Back to WordPress Editor" button

### ISSUE THREAD

**Issue by euene** [elementor/elementor#12988]
I suggest that there is a new option added in the Elementor settings which will completely hide the "← Back to WordPress Editor" button on pages which were created by Elementor.

![button-1](https://user-images.githubusercontent.com/6027160/97904015-95064900-1d48-11eb-867c-861dc9fae4a3.png)

Even though there is a warning after pressing the button, informing the user that the page layout/design may break, clients that are attempting to edit their website will still occasionally click the button, ignore the warning message, save the page and then complain that the page is broken.

A very common workflow with Elementor is to create all pages using only the Elementor editor, and using Gutenberg/WordPress editor only for posts where Elementor editor would be disabled. So there should be a way to ensure that pages are only built using Elementor and never Gutenberg.

Perhaps it would be best to add another area under the Elementor Settings which is for enabling the editor on different post types, but for disabling switching back to the WordPress editor on different post types. 

This way, administrators will be able to hide the  "← Back to WordPress Editor" button completely.

![elementor-settings](https://user-images.githubusercontent.com/6027160/97903992-8a4bb400-1d48-11eb-92b7-1a0cc37fbc79.png)

Another option is to add the setting to disable switching editors in the Role manager.

![elementor-role-manager](https://user-images.githubusercontent.com/6027160/97903969-81f37900-1d48-11eb-81b1-3ad27918edd2.png)

**Comment by euene** [comment]
@arielk

**Comment by rodolphebertozzo** [comment]
+1

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by get8bit** [comment]
Definitely need this! This is a very important option with simple solutions.

**Comment by nesoor** [comment]
This option is really important because I am getting so annoyed of customers panicking that they messed up their website just because they clicked that button and even after telling them 10 times they still click on it.

**Comment by joshcoast** [comment]
+1

**Comment by jthouse27** [comment]
+10

**Comment by maxms** [comment]
@DorShahar this really isn't the same as the issue it was merged with. This is referring to hiding the button in the Wordpress page editor. I have many clients who continue to break their sites because they keep clicking that button.

<img width="714" alt="Image" src="https://github.com/user-attachments/assets/3f495872-6018-49dc-91c9-84e6a71633a5" />
