### ISSUE TITLE
Redirect Doesn't Work

### ISSUE THREAD

**Issue by SRTooley** [elementor/elementor#12991]
Same issue here - Elementor Pro with Hello theme
Redirect does NOT work.
Really need this fixed to leadgen for client.

_Originally posted by @SRTooley in https://github.com/elementor/elementor/issues/11644#issuecomment-720875454_

**Comment by Aviad-Herman** [comment]
Thanks for reporting,

I couldn't reproduce you're bug.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it we simply can't help.

Thanks.
