### ISSUE TITLE
Image vertical alignment of carousel

### ISSUE THREAD

**Issue by jofranlirio** [elementor/elementor#12997]
When we use image carrossel on a project, sometimes, the images in galery have diferente heights. So, if I want center vertically the images, I need to center using the custom css at WordPress customize pane. In the widget controllers, could have buttons that I choose if I want the images aligned on the top, center or bottom.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
