### ISSUE TITLE
Background overlay not working for columns.

### ISSUE THREAD

**Issue by wwdes** [elementor/elementor#12993]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi,

Background overlay not working **for columns**.

UPDATE: Only empty columns affected. Overlay works as expected if any widget is present in the column.

## Steps to reproduce
- Create section with any number of columns.
- Select any column, go to styles>background and set a background image.
- Got to styles>background overlay - nothing there works.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by MichaelDarko** [comment]
#12748

I also have no idea why we can't use background overlays on empy columns. Seems like a bug or a silly design decision. This has been frustrating me for years but they don't seem to care about fixing it.

**Comment by amichel86** [comment]
Does anyone know a workaround for this? I need an empty column with a background image + overlay so it fits the height of the other column.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
