### ISSUE TITLE
Elementor Pro Form text fields throwing error on extending the widget adding another Repeater field control

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#12992]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor Pro.

## Description

I'm a 3rd party add-on dev who has extended Elementor with a new tab which adds controls to all the elements and widgets. Within this new tab, there's a repeater control for some functionality.

So, the problem happens when the functionality is extended in the form widget, and the form is used on the page. It happens during form render.

Here's a screenshot of the error with PHP notices enabled:

![Screenshot_2020-11-03 Form test – EDP(2)](https://user-images.githubusercontent.com/18551588/97964028-1cea6280-1dde-11eb-8e76-e391f33e670f.png)

Also, on logging the `$item` variable (from `form.php` line number `2089`), it was visible that a bunch of form item array fields were missing, hence those errors. But, funnily enough, it also contained the keys from the extended repeater control although this `$item` variable is only from the `$instance['form_fields']` array from `form.php` line number `2088` foreach loop. 

Meaning somehow, the extended repeater control values are being fetched and made part of this form field repeater (and other field item values are being lost) which seems to be the root cause.

*So, how do we fix this?*

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tiagoefreitas** [comment]
Same bug also happens with Crocoblocks Jetengine. It may have been introduced recently.

**Comment by webdevs-pro** [comment]
Any updates?

**Comment by webdevs-pro** [comment]
Paste widget styles also not working when custom repeater control added to advanced tab. Not only for form widget but for all widgets

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
