### ISSUE TITLE
Automatically cycle tabs

### ISSUE THREAD

**Issue by RockwareTRT** [elementor/elementor#13007]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Need multiple layouts like what can be produced in the tabs option (example: media (image/video) to the left and text to the right) for a home page carousel type environment. Auto scrolling on a timer.  

**Describe the solution you'd like**
I would like to be able to add a tabs object and set a timer when the tabs automatically progress to the next

*Describe alternatives you've considered**
I tried all your other carousel type options and none allowed multi-column media /content mix. I will likely use revolution slider for now.

**Additional context**

**Comment by RockwareTRT** [comment]
It would be nice to be able to cycle entire sections of content automatically.

**Comment by RockwareTRT** [comment]
I accomplished my goal using Slide Anything. You can see the results at [Intelliscreen.us](Intelliscreen.us) until we break it or change it.

**Comment by DorShahar** [comment]
Hi @RockwareTRT 

I'm sorry for your bad experience.
We are updating our product constantly, while user experience is our top priority.  
You are welcome to see all our features and possibilities on the [widgets page.  ](https://elementor.com/widgets/)

You can address our support team to check for a refund. 

All the best.
