### ISSUE TITLE
Countdown doesn't have Dynamic Tags support

### ISSUE THREAD

**Issue by rschmelzer** [elementor/elementor#13001]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Countdown element needs support for Dynamic Tags in the timestamp field

**Describe the solution you'd like**
Add support for Dynamic tags option in Countdown

**Describe alternatives you've considered**
I would need to find a way to modify the data-date field with jQuery or something like that but it's a hassle, especially with multiple countdowns on the same page.

**Additional context**
No option for Dynamic Tag in date selection field

**Comment by riadcitaku** [comment]
You can easily achieve this via some custom actions until they'll release an update.

```
public function countdown_custom_options( Controls_Stack $controls_stack ) {

    $controls_stack->update_control(
        'due_date',
        [
            'dynamic' => [
                'active' => true,
            ]
        ]
    );
}
```
`add_action( 'elementor/element/countdown/section_countdown/after_section_end', [ $this, 'countdown_custom_options' ], 10, 2 );`

**Comment by rschmelzer** [comment]
@riadcitaku Interesting. Not sure where I should be inserting this public function or the add_action with a reference to $this outside of the scope?

**Comment by riadcitaku** [comment]
$this would be used if the code is inside a class scope if you want to insert the whole code in functions.php, add as below.

```
function countdown_custom_options( Elementor\Controls_Stack $controls_stack ) {

    $controls_stack->update_control(
        'due_date',
        [
            'dynamic' => [
                'active' => true,
            ]
        ]
    );
}
add_action( 'elementor/element/countdown/section_countdown/after_section_end', 'countdown_custom_options', 10, 2 );
```

**Comment by rschmelzer** [comment]
@riadcitaku Thanks! This is helpful. I've inserted the code into my functions but not noticing any changes - is the above code supposed to expose a Dynamic Tag capability in the due date field for the Countdown element? If so, that's not showing for me with the above code. Thanks again!

**Comment by DorShahar** [comment]
Sorry for the late response. I'm glad you could work out a solution.
Closing the issue.
