### ISSUE TITLE
ClipBoard - Elementor PRO

### ISSUE THREAD

**Issue by depasbox** [elementor/elementor#13004]
Hello, I request that in the next updates you add an option that allows the user to cipyrate numbers or text from a box I think is called ClipBoard.

**Comment by Aviad-Herman** [comment]
Hi, 
Please explain what you mean.
Perhaps attach some screenshots so we can understand.

Thanks.

**Comment by depasbox** [comment]
![image](https://user-images.githubusercontent.com/73910932/98047887-b889cc00-1dfa-11eb-9d98-8824ab1f3bfa.png)


I require that when a user clicks on the button I indicate in the image can copy to the clipboard the numbers that appear there. I think it's called ClipBoard there is a plugin that has that function but I think it would be good that elementor PRO already has that function

Attached is a video guide that I posted on the elementor facebook group because I didn't explain myself well here https://www.facebook.com/100035063221206/videos/396770761501695/
