### ISSUE TITLE
Menu Cart (Pro) becomes unclickable on mobile

### ISSUE THREAD

**Issue by thelorddoyle** [elementor/elementor#13005]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

When I've added 6+ items in to the cart, it is impossible to get to the cart or checkout buttons as clickable elements. This basically means that customers can't access their cart on mobile. I assume I could make it static in it's position so the items above are scrollable but the buttons stay where they are, but I don't know how.

My website is https://mymoonbox.com.au

Can anyone help?

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
