### ISSUE TITLE
Different section columns gap causing different outer line of the elements

### ISSUE THREAD

**Issue by gregamer** [elementor/elementor#13003]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
Choosing different section columns gap causes different width of the columns in the section instead of just changing the gap between the columns. This is caused with padding that is added to the columns by section columns width setting but the section itself does not compensate that padding to align outer items to the same visual line.
From the design perspective this is a terrible thing to have because it breaks the page layout. Outer elements should be aligned no matter what the gap is in between them.

Solution would be to add negative margin to the wrapper of the columns with same value as columns padding. So if a gap-narrow has 10px padding wrapper should have -10px margin to compensate for that.

![elementor-columns-gap-problem](https://user-images.githubusercontent.com/4144796/98014391-e02d6400-1dfb-11eb-856d-4eab425f4bb6.png)
## Steps to reproduce
Make multiple sections and set different columns gap to each of them. First and last column in sections will not visually align.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Aviad-Herman** [comment]
Hi @gregamer,
Thanks for your suggestion.

Columns in Elementor are used in many diverse use cases and it's a little hard to make a 1-click solution to fit them all.

May I suggest you achieve your required design by:
1. Creating a section with only a single column
2. In the section's settings, choose Layout -> Column gap = no gap
3. Drag an image to the section
4. In the image's settings choose Advanced -> Positioning -> Width = inline (auto)
5. Duplicate the image as many times as you need
6. In the column's settings choose -> Horizontal align = space between

<img width="1740" alt="A" src="https://user-images.githubusercontent.com/73067562/98050334-52934980-1de6-11eb-8777-134e647ee430.png">

<img width="1740" alt="B" src="https://user-images.githubusercontent.com/73067562/98050353-5de67500-1de6-11eb-8dcf-6e9912a23b00.png">

<img width="1740" alt="C" src="https://user-images.githubusercontent.com/73067562/98050364-6343bf80-1de6-11eb-9bca-57f449d77838.png">

<img width="1740" alt="D" src="https://user-images.githubusercontent.com/73067562/98050355-5e7f0b80-1de6-11eb-8978-7cb9fa3ca293.png">

<img width="1740" alt="E" src="https://user-images.githubusercontent.com/73067562/98050380-6a6acd80-1de6-11eb-9d47-e75a0f712fb5.png">

**Comment by gregamer** [comment]
Hi,

thank you for your suggestion but that doesn't really solve the problem. With your suggestion you eliminated the columns as if they're not needed. Don't take my example (attached image) as the only possible scenario. We can have multiple columns of different widths etc. What you should implement is compensate the far left and far right for the columns gap so they all align. That is very easily achieved by negative margins as I already mentioned in my original post. If the row is width: calc(100% + 2*columns_gap) and have margin-left: -columns_gap; everything aligns well. 
I don't think you're aware of the importance of that (mis)behavior. Web sites are usually designed with some kind of grid in mind. The columns gap setting breaks that grid because total width of columns within one section changes when columns gap is changed. That is a very bad behavior which makes the use of columns gap parameter useless.  
Attached is another example of two sections with image and text which should have outer lines aligned but doesn't have due to different column gaps.

I think with a team of developers it shouldn't be too hard to make a fix for that especially since that would save tons of problems for all using Elementor. Elementor is a beautiful page builder with many exceptional features (that's why I chose it over other page builders) but there are a few things to change that are causing some serious problems when building pages. I understand that many users building personal pages aren't very picky about that but building a professional pages for clients using a design from a designer this becomes a problem. And since this is a misbehavior I really hope you can add it to the list of things to fix.

This is how I fixed that problem. It doesn't cover all scenarios but for a specific site it works. The only problem is custom column padding doesn't work any more because you use 4 selectors to set columns gap and 4 selectors for custom column padding therefore not leaving space for me to set my custom padding rules in between. 

// elementor column gaps
.elementor-section{overflow-x: hidden;} // because we're widening the row to align inner elements
$sizesLarge: ("narrow": "10px", "default": "20px", "extended": "30px", "wide": "40px", "wider": "50px");
$sizesSmall: ("narrow": "8px", "default": "14px", "extended": "20px", "wide": "30px", "wider": "36px");
@each $name, $val in $sizesSmall {
	@media (max-width: $tabletBreakpoint){
		.elementor-section-boxed{
			.elementor-column-gap-#{$name}{
				.elementor-row{
					margin-left: calc(-#{$val});
					margin-right: calc(-#{$val});
					width: calc(100% + #{$val} + #{$val});

					&>.elementor-column>.elementor-element-populated{
						padding-left: #{$val};
						padding-right: #{$val};
						padding-top: calc(#{$val} * 0.5);
						padding-bottom: calc(#{$val} * 0.5);
					}
				}
			}
		}
	}
}

@each $name, $val in $sizesLarge {
	@media (min-width: $tabletBreakpoint){
		.elementor-section-boxed{
			.elementor-column-gap-#{$name}{
				.elementor-row{
					margin-left: calc(-#{$val});
					margin-right: calc(-#{$val});
					width: calc(100% + #{$val} + #{$val});

					&>.elementor-column>.elementor-element-populated{
						padding-left: #{$val};
						padding-right: #{$val};
						padding-top: calc(#{$val} * 0.5);
						padding-bottom: calc(#{$val} * 0.5);
					}
				}
			}
		}
	}
}

**Comment by black-eye** [comment]
@Aviad-Herman Do you really thing the solution for the problem with columns and column gaps is don't use columns and column gap at all? In other words, ignore the problem? Does it make sense to you, why to have them there then?

@gregamer Check out the issue https://github.com/elementor/elementor/issues/452 - the problem is here from the very beginning of Elementor itself. You can add your voice there, but I wouldn't expect much. The issue is more than 4 years (sic!) old, and there's no sign of the will to solve it. In contrary, the DIY solution proposed there (basically the same as yours) no longer works in version 3.0 (unless you you use legacy mode), because Elementor has got rid of the "elementor-row" div.

Elementor should definitely fix this, because without it it simply cannot be considered a pixel perfect tool for the page layouts. But the last reaction from Elementor team was on March 2018 and it was basically an insult, how do we dare to ask for a fix. Sad...

**Comment by gregamer** [comment]
A quick fix would also be that Elementor team add 5 selectors for custom column padding so we could set our custom rules in between (with 4 selectors and a div for example. 
Elementor custom column gap:
.elementor-1558 .elementor-element.elementor-element-255b138 > .elementor-column-wrap.elementor-element-populated

Then my rule would be:
.elementor-column-gap-default>.elementor-row>.elementor-column>div.elementor-element-populated

This way my rule would sit above default elementor column gaps (4 selectors) and below custom column (5 selectors)

I must say that I'm quite disappointed with Elementor support on such an important tasks. I understand they develop new fancy features, but that is no excuse to ignore basic functionalities. As mentioned in many other tickets having hardcoded values (e.g. columns gap, columns layout etc.) is also a no-no with page builders. There should be no hardcoded values. It should be either saved in css variables or in Elementor page parameters so it can be adjusted to one's need.

I hope the Elementor team will improve their support for important topics because it's a great page builder overall, but with a few bugs (if you can call them this way) that makes a life quite harder when building a serious site.

Cheers,
Grega

**Comment by Aviad-Herman** [comment]
Sorry for the delay, for now is it feasible for you to define custom padding for each column (not section) using the advanced tab?

![image](https://user-images.githubusercontent.com/73067562/98485243-d9229f00-21c9-11eb-98b0-a70c648a9694.png)

I'm merging this issue with #452 as black-eye suggested.
