### ISSUE TITLE
Uncaught TypeError: e.animate is not a function (Elementor Form Widget)

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#13015]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When attempting to submit a contact form (connected to Mailchimp API), the following error occurs:

![image](https://user-images.githubusercontent.com/1435638/98183699-a7ef6800-1f58-11eb-8cb7-53b6ae60100c.png)

A different error occurs on Wordpress 2020 theme with no other plugins enabled:

![image](https://user-images.githubusercontent.com/1435638/98183855-fc92e300-1f58-11eb-8011-c069ed3eaa93.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by ag-skyler** [comment]
Currently dealing with this as well.

**Comment by a-camacho** [comment]
We have the same issue. Anyone ?

**Comment by umar834** [comment]
One common issue could be that you have added a JQuery script through **wp_enqueue_script** maybe in your functions.php file. Either try removing that or use the latest version of JQuery. Also, make sure that you are not using the slim version. 

Another possible issue could be a conflict of JQuery with some other plugins. Try Deactivating your plugins and then try it.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
