### ISSUE TITLE
Accept also Custom CSS without selector

### ISSUE THREAD

**Issue by brandontan903** [elementor/elementor#13014]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In Elementor, to add Custom CSS to an element (as example), we need to write the unique CSS ID selector and use it in Custom CSS. Below is for example:

```
#mynewid{
    background:red
}
```

**The problem is:**

<ins>Problem 1</ins>
It is tedious to create: I need to create unique CSS ID and use it in Custom CSS.

<ins>Problem 2</ins>
Tedious to duplicate: When duplicate the element, the Custom CSS did not works out of the box. I need to add unique CSS ID and change from `mynewid` in Custom CSS section to the new CSS ID.

**The solution is:**

Accept also Custom CSS without the selector.

In Divi or Beaver Builder, to add custom CSS, I don't need to write selector. Instead of write `#mynewid{background:red}`, I only need to write `background:red` and the particular element background will be red (I can write full with selector as well).

I hope Elementor can have this feature so that duplication process can be done much faster.

**Comment by drawcard** [comment]
You can already add custom CSS to widgets, pages, etc: https://www.youtube.com/watch?v=BZ9RCEU6ph8

**Comment by DorShahar** [comment]
Hi @brandontan903 ,
Thank you for your comment.

Indeed, @drawcard answer is the way to do it!

I suggest that you subscribe to our YouTube Channel, or look at our [blog](https://elementor.com/blog/), and you can see great tutorials and how-to's. 

Also, we have facebook communities were you can ask questions there. 

If you have any requests, feel free to write an issue. 

All the best!
