### ISSUE TITLE
Elementor Background Slideshow does not take ACF Gallery field 

### ISSUE THREAD

**Issue by TomVDH** [elementor/elementor#13011]
Issue as described in the title. Elementor currently does not support selecting images for a **background slideshow** through an ACF gallery field. 

Can this be taken up please?

**Comment by sermalefico** [comment]
Please fix this

**Comment by shilo-ey** [comment]
I merged this issue with  #11056, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
