### ISSUE TITLE
Request/feature !  Gallary Widget add limit show images

### ISSUE THREAD

**Issue by ravilrrr** [elementor/elementor#13016]
There is no way to create an image gallery, but to display only one main image. Therefore, I decided to suggest the idea of adding the ability to set a limit on the number of images displayed to the standard widget.

**Comment by DorShahar** [comment]
Hi @ravilrrr ,
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.

**Comment by ravilrrr** [comment]
Thank you for not hearing me :( Found a solution not in Elementor Pro

https://powerpackelements.com/elementor-widgets/album/
