### ISSUE TITLE
Custom global colour selection generating error for public users, admin works as expected.

### ISSUE THREAD

**Issue by mackski** [elementor/elementor#13021]
Selecting custom colour, from global colours generates error on front end. When logged in the page displaysand works as expected.
Selecting a custom colour using the picker only also works as expected for both admin and public users, so this is isolated to using a custom > global colour. 

[06-Nov-2020 00:05:52 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_data() in /public_html/wp-content/plugins/elementor/data/manager.php:406
Stack trace:
#0 /public_html/wp-content/plugins/elementor/core/files/css/base.php(766): Elementor\Data\Manager->run('globals/colors')
#1 /public_html/wp-content/plugins/elementor/core/files/css/base.php(324): Elementor\Core\Files\CSS\Base->get_selector_global_value(Array, 'globals/colors?...')
#2 /public_html/wp-content/plugins/elementor/core/files/css/base.php(653): Elementor\Core\Files\CSS\Base->add_control_rules(Array, Array, Object(Closure), Array, Array, Array)
#3 /public_html/wp-content/plugins/elementor/core/files/css/base.php(528): Elementor\Core\Files\CSS\Base->add_control_style_rules(Array, Array, Array, Array, Array)
#4 /public_html/wp-content/plugins/elementor/data/manager.php on line 406

Further to this error, debugging the rest call:
globals/colors/accent
Array ( [id] => accent ) GETWP_Error Object ( [errors] => Array ( [rest_not_logged_in] => Array ( [0] => You are not currently logged in. ) ) [error_data] => Array ( [rest_not_logged_in] => Array ( [status] => 401 ) ) )

[SOLVED]
Plugin was disabling REST API - Disable REST API and Require JWT / OAuth Authentication

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
