### ISSUE TITLE
Where the global style are saved in database??

### ISSUE THREAD

**Issue by Muazhesam** [elementor/elementor#13024]
I am importing one demo from one wp site to another but when I go to elementor pages i see there is something different.. It in global CSS.It's because elementor pages post css are inserted postmeta table but its not suficient.Elementor is creating a new css file that contains global css styling.But i want the previous site's one

**Comment by udidol** [comment]
Hi @Muazhesam,
Unfortunately, we don't offer the capability to export global site settings at this point.

**Comment by wayheming** [comment]
@udidol Hello, the problem is very serious, we also need to export and import global settings for clients. Perhaps you can come up with a solution? Any code or something else? I really need a fix.

**Comment by wayheming** [comment]
@Muazhesam I found solutions for myself. Elementor stores global settings in the post meta Default kit. Below is the code with which I take data for export and later import it.

```php
// For export
$default_post_id = get_option( 'elementor_active_kit' );
$global_data = get_post_meta( $default_post_id, '_elementor_page_settings', true );

// For import
$default_post_id = get_option( 'elementor_active_kit' );
update_post_meta( $default_post_id, '_elementor_page_settings', 'your data from export');
```

**Comment by udidol** [comment]
@Muazhesam @wayheming 
We understand the need for this feature, and it is in the works.
I wouldn't recommend working the way @wayheming is suggesting, we can't guarantee this would not cause any problems with your site. The Elementor Global Settings need to be synchronized with WordPress' global settings (such as Site Identity). There could be unexpected bugs.

**Comment by magino50** [comment]
I also have experienced this problem, after importing a demo, there is suddenly its CSS stored "somewhere" in a css, but its not findable. That is not really helpful and surely is a bug!

**Comment by Muazhesam** [comment]
@udidol yes, I had also tried this way. But it may change when regenerating assets. And when regenerating assets there is a new kit id.That's why we cannot go for a fixed it ID and its CSS

**Comment by udidol** [comment]
Regenerating CSS should not change the Kit ID.

**Comment by kevanbulmer** [comment]
Any update on this? I've spent months building a site with custom colors/typography, but when I export/import my theme, none of these custom colors/typography get imported. This lack of functionality really limits the capabilities of this wonderful plugin. I am now contemplating have to scrap all of my custom colors/typography & manually assign of my my styling to each & every element, which is going to take forever & defeats the whole purpose of CSS!

**Comment by udidol** [comment]
@kevanbulmer There's something in the works.

**Comment by kevanbulmer** [comment]
ok thanks!

**Comment by kevanbulmer** [comment]
@udidol could you point me in the right direction as to what needs doing, I would like to see if i can hack this change into my theme, whilst this is being built. If its a case of exporting some db records, them I am happy to do this.

I think the settings are stored under this key '_elementor_page_settings' in postmeta?

**Comment by wayheming** [comment]
@kevanbulmer [yes](https://github.com/elementor/elementor/issues/13024#issuecomment-726081363)

**Comment by shumsen** [comment]
> @kevanbulmer There's something in the works.

Any update on this 6 weeks later? It's impossible to do a clean 1:1 site migration with this bug.

**Comment by riadcitaku** [comment]
I'm using a 'hack' to import the default settings, so far works only on a fresh install WordPress where the default Kit is the second template after the one created automatically. I'm exporting the default kit as a template, so Tools > Export > My Templates.

```
$args = array(
    'post_type'   => 'elementor_library',
    'meta_query'  => array(
        array(
            'key'   => '_elementor_template_type',
            'value' => 'kit',
        ),
    ),
);

$query = get_posts( $args );

if ( ! empty( $query ) && isset( $query[1] ) && isset( $query[1]->ID ) ) {
    update_option( 'elementor_active_kit', $query[1]->ID );
}
```

**Comment by fidelsalz** [comment]
I installed Style Kits plugin which promises to create style kits and move them anywhere. It looked to work ok but I deactived it, uninstalled it, in the middle installed other plugins, then back to reinstall it and now it doesn-t work.
I searched to find where it stores their data and I found it is the same structura as Elementor does by post meta data. I  would like to delete all this information but don-t know how, I am in a multisite configuration.

**Comment by iMiek** [comment]
Any update? I really need to export a demo site to a live site where I was working on for weeks! It's unbelievable that there's no possibility to export/import global site settings! Did you ever think of export/import when implemented global site settings?

Please Elementor solve this asap!! It's in the make for 6 months now...
Is there any solution on this?

**Comment by estlacksensory** [comment]
Interested in taking the global post meta from one WPmultisite in _elementor_page_settings copying and pasting into other sql cell - but data doesn't seem like it would line up. (ie.  ( a:11:{... ) in one site  ( a:9:{... ) in another  ) - I suspect this would be bad.

**Comment by fidelsalz** [comment]
Even I just occasionally make websites with Word Press wanted to be serious in learning it. I got to learn that a good website starts with a solid design style so I went to Figma, then back to Elementor, I explored global styles and a plugin style kits, and several other things just to find out the final solution was confusing, heavy and not flexible. To summarize I moved on to Oxygen builder, yes a steeper learning curve but the real one. Sorry to hear here problems you can avoid choosing the right (not lazy) tool.

**Comment by aprilbeingsocial** [comment]
Hello!

I found this thread while searching for an easy way to create a client style guide after I design a site.  Currently, I am copying and pasting all of my settings into the style guide and I am tired of doing that so I'm looking for where all the settings are located to just copy and paste the style sheet on the backend, or via browser tools into a text document.

For your purposes @Muazhesam @wayheming @iMiek @ kevanbulmer why aren't you using a migrator tool to accomplish what you are trying to do?  If I understand correctly, you are creating sites on a demo URL and then want to publish on the fina/client URL, am I correct?  If so, all you need to do is use Updraft Plus migrator tool and search and replace.  It is flawless and I have been using it for six years for every site I create, it literally takes five minutes tops.  I actually buy a few site licenses for backups and also the migrator plugin that you can use as many times as you need throughout the year.

I hope I did not misunderstand you needs and I hope this helps one of you!

**Comment by kevanbulmer** [comment]
My scenario doesn't use any third-party plugins. My WP theme acts as an installer for pre-made demos, a bit like what you find on marketplaces like ThemeForest.

**Comment by aprilbeingsocial** [comment]
Got it, so you are hoping to sell premade sites??  Has the new kits feature helped you?  I am finding it a bit buggy, but it is a great improvement for sure.

**Comment by hiviz** [comment]
@udidol 

> @kevanbulmer There's something in the works.

Is the "export kit" (https://elementor.com/help/export-kit/) the official solution for the issue raised in this ticket?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
