### ISSUE TITLE
Background options consistency (sometimes 4, sometimes 2 ).

### ISSUE THREAD

**Issue by ttodua** [elementor/elementor#13039]
Some elements are able to have a background set from 4  different options (color | gradient | video | slideshow), but some elements only have 2 options (color | gradient) to be chosen from. Would be nice if all elements have the same consistency for background options (having all 4 options, instead of 2).

**Comment by arielk** [comment]
Hi @ttodua 

For now, In the Section or Container type element you have the option to choose between 4 types of backgrounds, in the Widget type elements you can only choose a color, image or gradient background.

Anyway, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
