### ISSUE TITLE
#FEATURE - Hide widgets on desktop/mobile/tablet

### ISSUE THREAD

**Issue by wouthardy** [elementor/elementor#13040]
Hi There,

I have a good and important proposal for every user of elementor. This from developer to customer.

If we are going to develop in elementor we usually start with desktop or tablet. If you have one of these 2 ready you start with the next one.

Now it is very confusing that if you are editing on desktop and you see all the elements of mobile (even if they are hided) it would be very user friendly if we only see the elements on desktop that are actually shown and not the hiden ones of mobile.

Hierarchy in creating a design in elementor is very important.  I am convinced that this will be much more user friendly.

Summarized:
You only see the elements you need to see. All the haired elements fall away here. 
Example: elements that are hid on a mobile phone are not visible on a desktop.

If all 3 options are gehide we can make sure that we see it how we see it now.

See an example below. So this is very unclear for me and for the customer if he is going to change something in this.

<a href="https://ibb.co/GPHnjdM"><img src="https://i.ibb.co/WKVG1Hz/Screenshot-2020-11-09-at-13-21-10.png" alt="Screenshot-2020-11-09-at-13-21-10" border="0"></a>

**Comment by DorShahar** [comment]
Merged issue. This issue will be handled as part of the Custom Breakpoints project.

I merged this issue with  #2043, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
