### ISSUE TITLE
/wp-admin/plugins.php - Undefined index: requires and new_version

### ISSUE THREAD

**Issue by Daniel-Richard** [elementor/elementor#13049]
Getting error messages via Query Monitor in this page especially

/wp-admin/plugins.php - Undefined index: requires and new_version

![2020-11-11_161843](https://user-images.githubusercontent.com/14333530/98787146-11301900-243a-11eb-832a-7b92be732ef4.png)

Nothing too critical, and I was wondering if it has something to do with Elementor / Pro, as this error message been persistent from multiple versions since noticing it last year.

**Comment by shilo-ey** [comment]
Hi @Daniel-Richard 

Thanks for reporting, unfortunately, this is not something that reproduces on our end.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to Hello theme


And see if the issue still persists...
