### ISSUE TITLE
Posts grid devices customization

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13041]
add full customization for devices, for example settings for gap, per page posts, shadow settings

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
