### ISSUE TITLE
Image Overlay For Vimeo Video Crashes The Page

### ISSUE THREAD

**Issue by hamdirizal** [elementor/elementor#13047]
## Description

The image-overlay for Vimeo video crashes the page if clicked.

## Steps to reproduce

1. Create a video element.
2. Set the video to Vimeo
3. Add any image overlay
4. Test on the front-end and try to play the video by clicking the image overlay.

## Isolating the problem

- [ ] The issue happens on Elementor 3.0.11active (and Elementor Pro).

**Comment by lior-sh** [comment]
Hi @hamdirizal,

Thanks for reporting, we couldn't reproduce the issue.
Can you please add a video that shows the issue and write your system info?
Thanks.

**Comment by hamdirizal** [comment]
The error happens on Chrome, Windows 10. I didn't test it on other browsers.

Here is the system info
[https://pastebin.com/V2F2xz0p](https://pastebin.com/V2F2xz0p)

Here is the video
[https://imgur.com/GZmLWfY](https://imgur.com/GZmLWfY)

**Comment by DorShahar** [comment]
Hi @hamdirizal 
Thank you for taking the time and reporting this.

We recreated your process of work once again and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
