### ISSUE TITLE
Issues faced while using your Page Builder

### ISSUE THREAD

**Issue by harsh-313** [elementor/elementor#13055]
I don't know what is wrong with Elementor, it keeps redirecting me to the new URLs, and it won't stop even after i explicitly removed the script code which is being added dynamically.

Also, my changes are not reflecting on front end which i applied and push the button called "UPDATE". 
please do real update on update.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread

We also suggest adding a short video recording of the problem.
Without it, we simply can't help.

Thanks.
