### ISSUE TITLE
Elementor Pro Posts / Post Grid: add links and more options to meta data

### ISSUE THREAD

**Issue by jordanjustkidding** [elementor/elementor#13058]
I have built several blogs and news websites for clients using Elementor Pro, which is fantastic, however I have the same very simple problem which shows up in all of them: the Elementor Pro posts widget has limited meta data functionality. This is the widget I use most for blogs and news sites, and I know there are third party post grid widgets available, but the best thing about the Elementor Pro posts widget is the use of a custom query field. Custom queries make this a very powerful widget. The frustrating thing is that the meta data options are so limited. Here are some issues and requests below:

- **Make Author link to author archive - this is the most important and probably very simple to implement**
- Allow tags (link to tag archive)
- Allow categories (link to category archive)
- Allow options to display meta data on different lines (instead of inline with a separator)

I know the last request is a bit more complicated. But different user case layout options might look something like this:

Author
**Post Title**
Excerpt
Tags

Category
**Post Title**
Author

Tags
**Post Title**
Author
Excerpt
Category

At the very least – please please make the author name link to the author archive.

Thank you

**Comment by dudaster** [comment]
You can use custom query field with Ele Custom Skin

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there @jordanjustkidding!

📢 We have great news! 

### We're happy to announce that the issue you raised will be resolved in Elementor Pro **v3.8**, with the release of the Loop Builder, which will allow you to build your own template for your posts!! 🥳 

Please, join the folks at #4440 to continue the discussion there!

Feel free to check it out when it's launched and update your plugin to the new version! 💪 

Cheers 🥂
