### ISSUE TITLE
Nav Menu Widget - Submenu Indicator - 4 Awesome 4 Icons.

### ISSUE THREAD

**Issue by gilesholder** [elementor/elementor#13056]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
The nav menu widget seems to be using font awesome 4 icons as its icons. This causes inconsistent errors on multiple sites I have tried to develop. Sometimes the submenu icon loads as a box other times it works. Enabling loading of font-awesome 4 support fixes this inconsistency so guessing its related. I do only use the Hello theme so not sure if this is related.

## Steps to reproduce
Disable Font Awesome 4 Support (Default in settings)
Create a nav menu using the widget.
Include sub-menu icons.
View live for inconsistency.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

</details>

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9907, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
