### ISSUE TITLE
exporting template bug

### ISSUE THREAD

**Issue by brandart** [elementor/elementor#13050]
I am using Elementor Pro 3.0.6 and Elementor 3.0.13 and when I export a template the syntax is false and it gets wrong exported.

e.g.

`{"version":"0.4","title":"temp_template","type":"section","content":[{"id":"705ff8dd","settings":[],"elements":[{"id":"3b5e2ff","settings":{"_column_size":100,"_inline_size":null},"elements":[{"id":"173834bb","settings":{"title":"Gib hier deine \u00dcberschrift ein","title_color":"#B85959","typography_typography":"custom","typography_font_size":{"unit":"px","size":44,"sizes":[]}},"elements":[],"isInner":false,"widgetType":"heading","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"
`

at the end there are `}]}` missing

**Comment by shilo-ey** [comment]
Thanks but we couldn't reproduce your issue.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
