### ISSUE TITLE
Why doesn't this code work?

### ISSUE THREAD

**Issue by jbrown832** [elementor/elementor#13063]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by jbrown832** [comment]
Hi,

Firstly let me say I'm a designer who has just discovered Elementor. Nice and easy drag and drop for my simple brain.

However being the type of personality I am, I want to see how much I can do before the learning curve gets too steep. In my case any type of coding, css, javascript etc, is completely beyond me. So I'll answer my own question of why the code doesn't work, because I simply don't understand it.

But... Is it possible to use code without fully understanding it? I.e. copy and paste a code somebody else has written.

This is a essentially what I'm doing (and failing at).

There's a bunch of animations at this site http://animation.kaustubhmenon.com/

My thinking is, I can just copy and paste them into the custom css panel in elementor and it should work.

This is the code
selector @-webkit-keyframes fadeIn {
  0% {
    opacity: 0; }
  100% {
    opacity: 1; } }
@-moz-keyframes fadeIn {
  0% {
    opacity: 0; }
  100% {
    opacity: 1; } }
@-o-keyframes fadeIn {
  0% {
    opacity: 0; }
  100% {
    opacity: 1; } }
@keyframes fadeIn {
  0% {
    opacity: 0; }
  100% {
    opacity: 1; } }

.u--fadeIn {
  -webkit-animation: fadeIn 1s ease-in;
  -moz-animation: fadeIn 1s ease-in;


I'm getting the error message:
Expected LBRACE at line 1, col 10.

I've tried adding in { into the first line before @-webkit but that throws up more errors.

Any help is greatly appreciated. It's probably a case of me leaving this stuff alone but just curious to see!

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
