### ISSUE TITLE
Correct the column width settings

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13069]
Correct the column width settings, why can I set 4 columns only on the mobile version to 100%, 2x50%, 100%, but I can't do it in the PC or Tablet version? This is possible only with the help of a third-party plug-in, however, it loads the site and the use of internal sections increases the page code, as well as make it possible to configure several breakpoints, at the moment we only have a push, not a setting, not all smart backgrounds, for example, have a resolution of 360 px. and 320, the site should display well at this size, as many widgets do not have settings for individual screens. As a pro user, I don't want to download other solutions when it can be implemented here

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

At the moment, we don't see a requirement for that. It may be that in the future we will change the page layouts to reduce DOM elements. 

Thanks.

**Comment by promocot** [comment]
then I see no reason to buy about a subscription because it does not give me the opportunity to do better optimization ... if it is difficult or you do not see the point in making the same speaker distribution for the PC as for mobile devices and for this you need to download or buy third-party add-ons, you either a fool or you don't care about your users since such a setting is available for tablets and smartphones ... as an example, this is the Harakiri function of steroids for elmentor... I will definitely not write more about the functionality, because the developers do not listen to users at all + there is no technical support at all ... next year I will not buy a license, I will download pirated versions
