### ISSUE TITLE
Better use of HTML tags

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#13066]
Currently, we can assign a <section> tag to determine a specific part of our page, but we can't drag a div tag into it to enclose this content as is currently possible, for example :

```
<section>
<h1> Title </h1>
<div>
<p> paragraph 1 </p>
<p> paragraph 2 </p>
</div>
</section>
```

So give us a possibility to insert several tags at the same time, in this case a div tag in a section tag, so a way to access the HTML code of the site.

**Comment by DorShahar** [comment]
Hi @rodolphebertozzo 
Does this [dev page](https://developers.elementor.com/add-html-attribute/) helps you?

**Comment by rodolphebertozzo** [comment]
Hi @DorShahar, I make it simpler, it's simply a question of being able to customise your code.

**Comment by DorShahar** [comment]
Hi @rodolphebertozzo 
We do have a plan to allow DOM manipulation. I can't tell when it will be available.
In the meantime, you can do what you need using JS.

Thanks
