### ISSUE TITLE
Custom content carousel

### ISSUE THREAD

**Issue by Martydesign** [elementor/elementor#13068]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Missing option to add custom template to carousel. This feature is must, I needed this feature in 10+ projects and had to use Element Pack plugin only for this feature. Widget can be used to carousel services, product categories and other custom content.

**Describe the solution you'd like**
Custom Carousel widget with option to add a section templates as a slides. So you can add carousel with custom content - image, title, button etc. 

**Describe alternatives you've considered**
Custom HTML Carousel widget with option to add a custom HTML a slides.

**Additional context**
Your plugin is great!

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/219 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Carousel was released with Elementor Pro v3.14.0! 🥳 

You can now create Carousels or Slides with custom nested widgets without needing to use shortcodes or other features! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
