### ISSUE TITLE
Reduce Google Fonts Payload with apply_filter

### ISSUE THREAD

**Issue by shaneonabike** [elementor/elementor#13065]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Basically, when I add Google fonts into Elementor I noticed that it adds all the variants and unicode variants. This is fine to ensure that it will work, but it's a huge payload for Google Pagespeed and also mobile devices if we only need a few variants. 

An example: https://fonts.googleapis.com/css?family=EB+Garamond%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7COswald%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRaleway%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CBarlow+Semi+Condensed%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&ver=5.5.3

**Describe the solution you'd like**
I have three distinct solutions that I think could help this situation.

1. Add an apply_filter for the Google font rendering that actually allows us to modify the added styles. Presently, Elementor adds _all_ the styles no matter whether we use them or not. This can potentially increase the payload and cause slow page speeds . This would also allow us to append a display=swap solution where needed.

A simple solution around https://github.com/elementor/elementor/blob/64137a2af69ad2a9e8411d25d850e2e03078ce67/includes/frontend.php#L789

We could put : `apply_filters('elementor/frontend/google_font_url', $fonts_url);`

2. In the Elementor configuration allow us to select the subset used by default. I realize there is a apply_filter (ref:https://github.com/elementor/elementor/blob/64137a2af69ad2a9e8411d25d850e2e03078ce67/includes/frontend.php#L808) but something more universal that simply allows the user to checkoff the relevant sets would be awesome

**Describe alternatives you've considered**
The only solution as a workaround is for me to turn off printing Google fonts and then rendering them myself. The *major issue* with that is that if the maintainer of the website adds new fonts these won't be included in the font loading and therefore won't work.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10886, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by shaneonabike** [comment]
... I don't understand this really isn't the same issue at all. The issue there from the title indicates including a "preload" tag so that the fonts are preload. In my suggestion I'm talking about a hook that will allow me to reduce what is loaded even before it gets output. I don't see how these are the same to be really honest...

And if they are! Can you change the title in the other ticket to reflect all things Google Fonts and then I would be happy to comment, cause presently it's fairly confusing and specific for the masses.

**Comment by DorShahar** [comment]
Hi @shaneonabike 
This merged due to a project of improving our performance overall. Improving performance for fonts is a part of that.
