### ISSUE TITLE
Solo toggle to only display responsive eligible elements, truly hide non-applicable other screen size elements.

### ISSUE THREAD

**Issue by MagneticArrow** [elementor/elementor#13070]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be helpful if when toggling thru the responsive builder views there was an additional option to 'Solo' or similar.

**Describe the solution you'd like**
'Solo' or similar would restrict elements displayed to just the current responsive size viewed (Desktop/Tablet/Mobile)
Currently, blank blocks or blocks with lines thru them appear to indicate what is not seen in the particular responsive view.  Sometimes that can result in a lot of scrolling, say when tweaking a mobile view and there are stacks of black blocks not rendered in that view.

**Describe alternatives you've considered**
Scrolling more than seems needed to get to the mobile elements I want to tweak.

**Additional context**

**Comment by DorShahar** [comment]
Merged issue - as it will be handled with #2043 

I merged this issue with  #2043, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
