### ISSUE TITLE
incompatibility with a third-party plugin - Starter Templates

### ISSUE THREAD

**Issue by radoslavak** [elementor/elementor#13071]
I got from this answer support@elementor.com:

Gabriel replied | Nov 14, 20:32
-- | --
Hi Radoslava,
Thanks for getting in touch.I've been checking your website and this issue is generated by an incompatibility with a third-party plugin
Please check this loom: https://www.loom.com/share/c13011f0be0349759e560d69936130c1When the third-party plugin Starter Templates is deactivated, the editor works wellIn  this case, **we suggest you report this issue to the plugin authors and  see if they can provide a fix on their end. If they need help from us,  they can open an issue on our Github account and our developers will be  happy to assist.**

 **https://github.com/elementor/elementor/issuesLet me know if you need further assistance.**

Kind Regards,                             

--Elementor Technical SupportFacebook \| Twitter \| YouTube \| InstagramJoin the conversation & learn from our Elementor Community

[watch recorded problem](https://www.loom.com/share/c13011f0be0349759e560d69936130c1)

**Comment by DorShahar** [comment]
Hi
Your request is unclear. 
As our support representative explained- this issue is in the plugin authors and you should consult with them.
If any support needed from our end, please describe what with further details.

Thanks
