### ISSUE TITLE
Lazy loading Elementor JS files 

### ISSUE THREAD

**Issue by Aramis1977** [elementor/elementor#13073]
Hi,

I would like to lazy load Elementor JS files using the Flying Scripts plugin (i.e. load them only when the user moves his mouse or scrolls). However, I noticed that once I do that the following functionalities stop working from time to time:

- Sticky Header
- Table of Contents is empty
- The posts page isn't displayed correctly (please see the attached screenshot).
<img width="956" alt="BlogPosts" src="https://user-images.githubusercontent.com/74483395/99178075-6dd05400-2718-11eb-9f56-5e644154717d.png">

This is my site (if you want to check it for yourself):
https://www.francophilesanonymes.com/all-posts-about-france-and-its-culture/ 

Can you please let me know, which of the JS files affect these functionalities so I will not lazy load them?

Thanks in advance.

**Comment by DorShahar** [comment]
Hi @Aramis1977 
We are working on a solution for Lazy loading for JS files
Unfortunately, we cannot help you with your question of which JS files affect the functionalities (we cannot debug your code).

So please stay tuned for the Lazy load release.
Thank you for your understanding.
