### ISSUE TITLE
select2 sorting

### ISSUE THREAD

**Issue by Stas0238** [elementor/elementor#13078]
Hello, 
I am a one of one campaign developers using Elementor plugin to create really cool templates and pages. We have our custom widgets for Elementor plugin and due to using a lot of different field types one of them has a small issue. The Select2 with multiple choices outputs the results in ASC order anyway user select values. Video provided under will show you in more details ->

https://gyazo.com/fad28f0c3bff04510093587fd65ab58a

What I want to get is results as I types step by step. Ids provided order. 
In the current way category with id 31 is moving on second position but I should have it on 4th after all items before.

Can you add some param for this type of field to sort results by options provided. Thanks.

**Comment by webdevs-pro** [comment]
+1

**Comment by ka-Reema** [comment]
+1

**Comment by Stas0238** [comment]
@webdevs-pro @DorShahar @ka-Reema @nicomollet 
https://www.youtube.com/watch?v=vbb9MPYT23Y

**Comment by nicomollet** [comment]
@Stas0238 I don't have anything to do with that, so don't do that anymore.

**Comment by Stas0238** [comment]
@nicomollet 
I just decided to remind that this question is not closed yet (after 2 years)

Also, what about answering me on other questions ?
How long should I wait for answers ? Again 2 years ? but even after that time as I see no normal answer is provided  

Maybe you could help me to get answers I asked ?
1/ https://github.com/elementor/elementor/issues/16881 (5 months ago)
2/ https://wordpress.org/support/topic/get_style_depends-on-edit-mode-only/#post-15596311 (7 months ago)
3/ https://wordpress.org/support/topic/get_script_depends-based-on-option/#post-15596300 (6 months ago)
bonus +1 https://github.com/elementor/elementor/issues/18510 (new one)

**Comment by rami-elementor** [comment]
Hi @Stas0238 ,

You can't change order of [Select2](https://developers.elementor.com/docs/controls/classes/control-select2/) items. We don't plan to change this behavior anytime soon.

I suggest to build your widget in a different way, maybe using a repeater, this way your users will have control the items order.

**Comment by Stas0238** [comment]
Hello @rami-elementor 
much better to have at least this one answered !
Not the best solution but I thank for your time for my question :)
Hope my other questions will get their answers sooner than after 2 years.

**Comment by andreas83** [comment]
Even the ticket is closed, it would be very nice to have this feature. 
Here is an example on how to add sortable to select2.

https://jsfiddle.net/karthi3788/cveekdxy/2/

**Comment by xmedia-nl** [comment]
Here's a snippet that works in the Elementor editor. Adding items in the order they are selected and allowing drag and drop to re-order the items. 

```
elementor.hooks.addAction( 'panel/open_editor/widget/my-widget-name', function( panel, model, view ) {
    var selectElements = panel.$el.find('select[type="select2"]');

    selectElements.each(function() {
        var selectEl = $(this).select2();
        selectEl.on('select2:select', function (e) {
            var newlySelectedItem = e.params.data.element;
            $(newlySelectedItem).detach();
            $(selectEl).append(newlySelectedItem);
        });
        selectEl.next().children().children().children().sortable({
            containment: 'parent', 
            stop: function (event, ui) {
                ui.item.parent().children('[title]').each(function () {
                    var title = $(this).attr('title');
                    var original = $( 'option:contains(' + title + ')', selectEl ).first();
                    original.detach();
                    selectEl.append(original);
                });
                selectEl.change();
            }
        });
    });
});
```
