### ISSUE TITLE
Add Link field to Testimonial Carousel widget

### ISSUE THREAD

**Issue by Banter-aus** [elementor/elementor#13083]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I use the Testimonial Carousel widget on most projects. When using for B2B businesses, it would be great if we could link out to the business leaving the review. Great for SEO.

**Describe the solution you'd like**
Add a Link Field to Testimonial Carousel widget.

**Describe alternatives you've considered**
I have been unable to find a third-party add-on with this functionality.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #8934 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
