### ISSUE TITLE
Elementor Pro - Default body hook inside header template

### ISSUE THREAD

**Issue by NenadObradovic** [elementor/elementor#13089]
Hi guys,

Could you please consider to add default WordPress function/hook after the body open inside your PRO version -> header template? 

Example, inside **elementor-pro/modules/theme-builder/views/theme-support-header.php** file, find code below

```
<body <?php body_class(); ?>>

<?php $location_manager->do_location( 'header' ); ?>
```

and replace it with this one

```
<body <?php body_class(); ?>>
<?php
// Default WordPress hook after body tag open (added inside WordPress 5.2)
if ( function_exists( 'wp_body_open' ) ) {
	wp_body_open();
}
?>
<?php $location_manager->do_location( 'header' ); ?>
```

so we can be able to use default hook **do_action( 'wp_body_open' );** to add additional content after the body is open for both header templates (theme default header template and your custom header template).

Thanks for your time.

Best regards,
Nenad

**Comment by pawkat** [comment]
> Hi guys,
> 
> Could you please consider to add default WordPress function/hook after the body open inside your PRO version -> header template?
> 
> Example, inside **elementor-pro/modules/theme-builder/views/theme-support-header.php** file, find code below
> 
> ```
> <body <?php body_class(); ?>>
> 
> <?php $location_manager->do_location( 'header' ); ?>
> ```
> 
> and replace it with this one
> 
> ```
> <body <?php body_class(); ?>>
> <?php
> // Default WordPress hook after body tag open (added inside WordPress 5.2)
> if ( function_exists( 'wp_body_open' ) ) {
> 	wp_body_open();
> }
> ?>
> <?php $location_manager->do_location( 'header' ); ?>
> ```
> 
> so we can be able to use default hook **do_action( 'wp_body_open' );** to add additional content after the body is open for both header templates (theme default header template and your custom header template).
> 
> Thanks for your time.
> 
> Best regards,
> Nenad

Use  'elementor/theme/before_do_header' hook. locations-manager.php
elementor-pro/modules/theme-builder/classes/locations-manager.php(269 line)
