### ISSUE TITLE
Slider Options (Lottiefiles)

### ISSUE THREAD

**Issue by martinMRD** [elementor/elementor#13093]
- [x]  I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Provide a more diverse experience in using the Slider widget to add some more possibilities
 
**Describe the solution you'd like**
To me, the slider content is too much restricted into some use cases. In fact, I would like to build a slider for my website but I am very limited by the possibilities offered by the Elementor slider. For example, it is impossible for me to integrate a Lottie File or to make a precise and deep edition of each element on each of the slider's cards.

**Describe alternatives you've considered**
Some features to think about adding to this powerful block : 
- Lottie file
- Content editor as it was a simple block (or import some templates)
- Changing the look of the navigation arrows and the page indicator (importing or using the icons library) 
- Changing the position of the navigation arrows and the page indicator on the card itself

**Additional context**
Thanks for your time and consideration.

**Comment by DorShahar** [comment]
Hi ,
I'm merging this issue with #4440 , since we are planning the same mechanism for these 2 cases.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Carousel widget released with Elementor Pro v3.11.0! 🥳 

With the new Loop Carousel widget, you can customize your post listings with custom templates (including WooCommerce Products)! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Carousel layout, design, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-carousel/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
