### ISSUE TITLE
Loop for custome post

### ISSUE THREAD

**Issue by toukirahmed0** [elementor/elementor#13096]
Please include custom post type loop

**Comment by makaus** [comment]
Hi
Do you know Elementor Custom Skin?
It's really good.

**Comment by toukirahmed0** [comment]
> Hi
> Do you know Elementor Custom Skin?
> It's really good.

yes, i know that, but that is now Pro with limited free features, 

But if elementor make this option than we don't need to depends on 3ed pretty.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
