### ISSUE TITLE
Add an Option to Prevent Image Import During Template Import

### ISSUE THREAD

**Issue by ui-lawson** [elementor/elementor#13095]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor's import/export template function is ideal for moving content from one domain to another where the content doesn't already exist.

However, this feature is less than ideal across multiple development environments (e.g. DEV, TEST, LIVE) where the media already exists in each installation and only the Replace URL tool would be required.

**Describe the solution you'd like**
A checkbox option, specifically for implementation in multiple development environments that prevents image import during the import of Elementor templates.

**Describe alternatives you've considered**
Modifying the core plugin files by commenting out Line 70 of ~/wp-content/plugins/elementor/includes/controls/media.php

**Comment by black-eye** [comment]
+1 Makes absolute sense. With imports like these the same images start to multiply in the Media Library.
Either add an option not to import images at all, or just the new ones. Or detect the existing images and just update their URL.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4417, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
