### ISSUE TITLE
Elementor Tools > Recalculate elements usage triggers: Warning: Cannot modify header information - headers already sent by...

### ISSUE THREAD

**Issue by gsusI** [elementor/elementor#13100]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

In a **fresh WordPress installation**, with **EXCLUSIVELY** Elementor and Elementor Pro installed (just downloaded), using the option to Recalculate Elements Usage triggers a Headers error.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

![image](https://user-images.githubusercontent.com/4558016/99658837-ee17f180-2a57-11eb-8daf-427233ce5fc6.png)

<details>
<summary>Warning: Cannot modify header information - headers already sent by (output started...</summary>

> Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-admin/includes/template.php:2488) in /var/www/html/wp-includes/pluggable.php on line 1296 Call Stack: 0.0029 363296 1. {main}() /var/www/html/wp-admin/admin.php:0 1.2031 6533488 2. do_action() /var/www/html/wp-admin/admin.php:259 1.2032 6533864 3. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:478 1.2032 6533864 4. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:311 1.2032 6534992 5. Elementor\Modules\System_Info\Module->display_page() /var/www/html/wp-includes/class-wp-hook.php:287 1.2032 6534992 6. Elementor\Modules\System_Info\Module->load_reports() /var/www/html/wp-content/plugins/elementor/modules/system-info/module.php:151 1.6680 6663968 7. Elementor\Modules\Usage\Usage_Reporter->get_report() /var/www/html/wp-content/plugins/elementor/modules/system-info/module.php:262 1.6680 6664416 8. Elementor\Modules\Usage\Usage_Reporter->get_usage() /var/www/html/wp-content/plugins/elementor/modules/system-info/reporters/base.php:105 20.3051 18297016 9. wp_safe_redirect() /var/www/html/wp-content/plugins/elementor/modules/usage/usage-reporter.php:55 20.3167 21687952 10. wp_redirect() /var/www/html/wp-includes/pluggable.php:1404 20.3167 21688008 11. header() /var/www/html/wp-includes/pluggable.php:1296 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-admin/includes/template.php:2488) in /var/www/html/wp-includes/pluggable.php on line 1299 Call Stack: 0.0029 363296 1. {main}() /var/www/html/wp-admin/admin.php:0 1.2031 6533488 2. do_action() /var/www/html/wp-admin/admin.php:259 1.2032 6533864 3. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:478 1.2032 6533864 4. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:311 1.2032 6534992 5. Elementor\Modules\System_Info\Module->display_page() /var/www/html/wp-includes/class-wp-hook.php:287 1.2032 6534992 6. Elementor\Modules\System_Info\Module->load_reports() /var/www/html/wp-content/plugins/elementor/modules/system-info/module.php:151 1.6680 6663968 7. Elementor\Modules\Usage\Usage_Reporter->get_report() /var/www/html/wp-content/plugins/elementor/modules/system-info/module.php:262 1.6680 6664416 8. Elementor\Modules\Usage\Usage_Reporter->get_usage() /var/www/html/wp-content/plugins/elementor/modules/system-info/reporters/base.php:105 20.3051 18297016 9. wp_safe_redirect() /var/www/html/wp-content/plugins/elementor/modules/usage/usage-reporter.php:55 20.3167 21687952 10. wp_redirect() /var/www/html/wp-includes/pluggable.php:1404 20.3182 21688064 11. header() /var/www/html/wp-includes/pluggable.php:1299

</details>

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.22
	PHP Version: 7.4.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
		 - Elementor uploads directory
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: http://127.0.0.1
	Home URL: http://127.0.0.1
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.3.0.282
	Author: Jesus Iniesta
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com


== Must-Use Plugins ==
	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	Plugin Organizer MU
		Version: 10.1.4
		Author: Jeff Sterup


== Elements Usage ==
	
	archive : 3
		archive-posts : 2
		heading : 3
		posts : 1
		theme-archive-title : 3
	footer : 2
		form : 2
		heading : 2
		icon-list : 6
		social-icons : 2
		text-editor : 4
	header : 1
		heading : 2
		nav-menu : 6
		theme-site-logo : 3
	page : 83
		alert : 2
		animated-headline : 3
		author-box : 4
		blockquote : 3
		button : 45
		divider : 81
		form : 9
		heading : 235
		html : 5
		icon : 1
		icon-box : 11
		icon-list : 32
		image : 129
		image-box : 4
		login : 1
		menu-anchor : 6
		nav-menu : 1
		post-comments : 4
		post-info : 2
		posts : 4
		share-buttons : 2
		social-icons : 2
		spacer : 100
		text-editor : 226
		theme-post-featured-image : 1
		theme-post-title : 2
		theme-site-logo : 2
		video : 4
	popup : 9
		form : 4
		global : 3
		heading : 7
		html : 2
		spacer : 3
		template : 1
		text-editor : 4
	section : 15
		animated-headline : 1
		button : 8
		divider : 2
		global : 3
		heading : 14
		html : 1
		icon-box : 1
		image : 4
		image-box : 1
		login : 1
		social-icons : 1
		spacer : 3
		text-editor : 7
	single : 2
		author-box : 2
		button : 2
		divider : 2
		global : 1
		heading : 3
		post-comments : 2
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		spacer : 9
		text-editor : 1
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 2
	widget : 0
		author-box : 1
		blockquote : 1
		button : 2
		divider : 1
		form : 15
		heading : 5
		image : 3
		text-editor : 1
	wp-post : 15
		author-box : 1
		blockquote : 4
		button : 4
		divider : 53
		form : 1
		global : 2
		heading : 141
		html : 1
		image : 87
		post-info : 1
		posts : 1
		share-buttons : 1
		spacer : 33
		text-editor : 204
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-page : 17
		alert : 2
		animated-headline : 1
		author-box : 1
		button : 19
		divider : 7
		form : 4
		global : 3
		heading : 44
		html : 3
		icon-box : 4
		icon-list : 14
		image : 18
		image-box : 1
		menu-anchor : 3
		post-comments : 3
		post-info : 1
		posts : 1
		shortcode : 2
		spacer : 40
		text-editor : 33
		theme-page-title : 2
		theme-site-logo : 1
		video : 4
	single-page : 5
		alert : 1
		button : 6
		divider : 6
		heading : 23
		icon-list : 7
		image : 11
		menu-anchor : 3
		posts : 1
		shortcode : 1
		spacer : 9
		text-editor : 4
		theme-post-content : 1
	not-supported : 0
		animated-headline : 1
		button : 2
		call-to-action : 2
		divider : 2
		flip-box : 1
		heading : 18
		image : 3
		image-box : 2
		progress : 1
		spacer : 9
		text-editor : 25


== Log ==
	

				
```
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.16

Feel free to update

Thanks!
