### ISSUE TITLE
Remove Elementor Pro renewal sticky notice

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#13102]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

![image](https://user-images.githubusercontent.com/18551588/99663798-2be33d00-2a8d-11eb-874f-f6732146df31.png)

A non-closable admin notice on all dashboard pages of all the licensed sites is just too much. It's annoying, and should not be shown on any WP dashboard, mine or my clients'..

Furthermore, it's just worrisome for clients. Why do they have to be bothered about a plugin/software the designer used to build their website?

Elementor Pro operates in a common shared environment (WordPress dashboard), not its own SaaS UI, and that comes with its own responsibility of not cluttering the shared UI. The WP Dashboard is not the appropriate place to put a sticky un-closable big notice for renewal of a license, and that too on every single dashboard UI page.

**Describe the solution you'd like**
Just send an email or two and that should be enough of a renewal notice..

**Describe alternatives you've considered**
Switching to some other website builder I guess...

**Comment by simonclay** [comment]
Completely agree with you on this. Wordpress Dashboard is forever being cluttered with notifications and, in my opinion, now looks too amateur for serious businesses.

**Comment by shilo-ey** [comment]
Hey @parasshah195 and @simonclay 
Thanks for this feedback.

Elementor Pro is a premium plugin that requires a valid license. 

When using manual renewal AND when the user is an administrator on the specific site - only then the notice will be displayed.

Unfortunately, this is not something that we will remove at the moment.

Thanks

**Comment by bouveng** [comment]
It should not be shown on accounts that has auto renewal active.

**Comment by kangarko** [comment]
Put this to functions.php file and profit:

````
/**
 * Remove annoying Elementor license notice
 */
add_action("admin_enqueue_scripts", function() {
    ?>
    <style>
        .e-notice--extended.e-notice--dismissible.e-notice.notice {
            display: none !important;
        }
    </style><?php
});
````

**Comment by kangarko** [comment]
@craigburdett haha thanks :) You can get my course at mineacademy.org/nms-advanced ($67 USD, I guess then I have to invite you for a beer!) or donate any amount to billing@mineacademy.org via PayPal, thanks so much <3

**Comment by bouveng** [comment]
> Put this to functions.php file and profit:

That removes all notices. FYI.

**Comment by luckybhumkar** [comment]
> Put this to functions.php file and profit:
> 
> ```
> /**
>  * Remove annoying Elementor license notice
>  */
> add_action("admin_enqueue_scripts", function() {
>     ?>
>     <style>
>         .e-notice--extended.e-notice--dismissible.e-notice.notice {
>             display: none !important;
>         }
>     </style><?php
> });
> ```

✅ Worked! 🙏 Thanks.

**Comment by khairulimran-97** [comment]
It so annoying. As my customer keep ask.  I know when to renew. Please add option to remove this annoying notifications.

**Comment by jdelgadoesteban** [comment]
Would not the code above be overwritten after an update?

**Comment by luckybhumkar** [comment]
> Would not the code above be overwritten after an update?

No, if you place the code in a functions.php of your child theme. Or inject code through a plugin. Such as WPCode.

**Comment by jdelgadoesteban** [comment]
@luckybhumkar nice one, will try WPCode. Cheers

**Comment by Etech-afzaal** [comment]
go to wp-content\plugins\elementor-pro\license\admin.php 

and comment the below code
API::STATUS_EXPIRED => [
				'title' => esc_html__( 'Your Elementor Pro license has expired.', 'elementor-pro' ),
				'description' => esc_html__( 'Want to keep creating secure and high-performing websites? Renew your subscription to regain access to all of the Elementor Pro widgets, templates, updates & more', 'elementor-pro' ),
				'button_text' => esc_html__( 'Renew Now', 'elementor-pro' ),
				'button_url' => API::RENEW_URL,
				'button_type' => 'cta',
			],

**Comment by grafxlab** [comment]
I agree, Elementor and all plugins that offer a paid editions can notify you an upgrade option. But users should be able to turn off the nag notification. If you go into settings for the plugin component there, they can nag you. But incessant nagging is annoying and gives users every reason to ditch the product rather than be bugged about "we want your money" every time.

**Comment by den1sa** [comment]
> Put this to functions.php file and profit:
> 
> ```
> /**
>  * Remove annoying Elementor license notice
>  */
> add_action("admin_enqueue_scripts", function() {
>     ?>
>     <style>
>         .e-notice--extended.e-notice--dismissible.e-notice.notice {
>             display: none !important;
>         }
>     </style><?php
> });
> ```

This works, however, when you go into the appearance->customize the layout of the selections on the left are massively spaced apart. Can this script be amended to address this issue?

**Comment by Webney-Website-Design** [comment]
> Hey [@parasshah195](https://github.com/parasshah195) and [@simonclay](https://github.com/simonclay) Thanks for this feedback.
> 
> Elementor Pro is a premium plugin that requires a valid license.
> 
> When using manual renewal AND when the user is an administrator on the specific site - only then the notice will be displayed.
> 
> Unfortunately, this is not something that we will remove at the moment.
> 
> Thanks

Use This:

/**
 * Remove annoying Elementor license notice
 */
add_action("admin_enqueue_scripts", function() {
    ?>
    <style>
        .e-notice--extended.e-notice--dismissible.e-notice.notice {
            display: none !important;
        }
    </style><?php
});

**Comment by rpmcmurphy** [comment]
This is super annoying. I am on localhost. How the hell you license your plugin for localhost! On my client's server, the license is there for that domain. Stop annoying users like that on dev environment. Cheap behavior.

**Comment by ddpanda** [comment]
go to wp-content\plugins\elementor-pro\license\admin.php
Change
`add_action( 'admin_notices', [ $this, 'admin_license_details' ], 20 );`
to
`remove_action( 'admin_notices', [ $this, 'admin_license_details' ], 20 );`
 
`add_filter( 'elementor/core/admin/notices', function( $notices ) {
    $notices[] = new Trial_Period_Notice();
    $notices[] = new Trial_Expired_Notice();
    return $notices; 
});`

to 

`add_filter( 'elementor/core/admin/notices', function( $notices ) {
    return []; // Remove all Elementor notices
});`

**Comment by emreerkan** [comment]
Elementor Pro has a specific filter for this: `elementor_pro/license/should_show_renew_license_notice`

You can add the line below into your theme's `function.php` or use a must-use plugin. This'll do the trick and hide the renewal notice.

```php
add_filter( 'elementor_pro/license/should_show_renew_license_notice', '__return_false', 99, 1 );
```
