### ISSUE TITLE
Support for HCaptcha in stead of reCaptcha from Google.

### ISSUE THREAD

**Issue by Mahyulan** [elementor/elementor#13101]
It would be great to have HCaptcha as alternative to reCaptcha.
Can you implement this?

Thanks,

Bert

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by d19dotca** [comment]
This should be closed and merged instead with a feature request filed months earlier... https://github.com/elementor/elementor/issues/11737

**Comment by Mahyulan** [comment]
OK, thanks.
