### ISSUE TITLE
Social Icon Widget not showing spacing between icons

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#13118]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The Social Icons widget does not keep the space set between widgets.

It shows correctly during edit, but when viewing the actual page, the space is gone and the icons are squashed up together.

## Steps to reproduce

Place the Social Icons widget on the page. Note the spacing between the default 3 icons (set to 5 by default in the Style tab).

Update the page and then visit the actual page. The space is gone.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

![Screen Shot 2020-11-20 at 14 34 48](https://user-images.githubusercontent.com/2143351/99814579-12033200-2b41-11eb-912d-588b300ac89f.jpg)

![Screen Shot 2020-11-20 at 14 35 08](https://user-images.githubusercontent.com/2143351/99814650-29dab600-2b41-11eb-9d7f-daad11c3acc6.jpg)

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.22
	PHP Version: 7.2.34
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	
![Screen Shot 2020-11-20 at 14 34 48](https://user-images.githubusercontent.com/2143351/99814201-90130900-2b40-11eb-994e-c93efeef8ba9.png)
![Screen Shot 2020-11-20 at 14 35 08](https://user-images.githubusercontent.com/2143351/99814206-91dccc80-2b40-11eb-88d7-906bc7d0e2b4.png)


	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

== Active Plugins ==
	A2 Fixed W3 Total Cache
		Version: 0.9.4.6.4.8.1
		Author: 

	A2 Optimized WP
		Version: 2.0.11.1.1
		Author: A2 Hosting

	Easy Hide Login
		Version: 1.0.7
		Author: Arshid

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 5.8.2
		Author: Exactly WWW

	LiteSpeed Cache
		Version: 3.5.2
		Author: LiteSpeed Technologies


== Elements Usage ==
	
	archive : 0
		archive-posts : 1
		theme-archive-title : 1
	popup : 0
		heading : 1
		image : 1
		login : 1
		text-editor : 1
	wp-page : 2
		pafe-form-builder-field : 1
		pafe-form-builder-submit : 1
		social-icons : 2
		text-editor : 1


== Log ==
	
JS: showing 2 of 2JS: 2020-08-19 15:02:52 [error X 2][https://wordpresstesting.developmentandtesting.co.uk/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-08-20 02:07:05 [error X 1][https://wordpresstesting.developmentandtesting.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3707\") has already been destroyed and cannot be used. 

Log: showing 20 of 282020-08-25 14:45:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 14:45:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-25 14:45:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-26 02:30:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-27 02:45:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-28 02:49:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-31 02:39:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]
2020-08-31 14:48:20 [info] elementor::elementor_updater Started 
2020-08-31 14:48:20 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-08-31 14:48:20 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-08-31 14:48:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-08-31 14:48:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-07 02:42:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-10 02:42:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-15 02:47:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]
2020-09-18 03:18:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]
2020-09-23 14:37:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-10-02 02:46:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-21 03:18:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 15:02:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]


				
```
</details>

**Comment by Laavanya001** [comment]
I am facing the exact same problem. I found a similar post from 2017 (#2321) that suggested a css workaround .elementor-social-icons-wrapper {
    font-size: inherit;
}.

I've tried this, which works on the elementor editor but does not work on the published site.

selector .elementor-social-icons-wrapper.elementor-grid .elementor-grid-item{
    margin-right: 100px;
}

Can someone please help resolve this?

**Comment by Laavanya001** [comment]
@simonclay : this solution actually worked for me. May you could give it a shot.
selector .elementor-social-icons-wrapper.elementor-grid .elementor-grid-item{
margin-right: 100px;
}

**Comment by Aviad-Herman** [comment]
Hi thanks for raising this issue.
We fixed it in the latest version of elementor.
Let me know if you update and the problem persists.

**Comment by ReJoNL** [comment]
> Hi thanks for raising this issue.
> We fixed it in the latest version of elementor.
> Let me know if you update and the problem persists.

I still got this problem. (on a coming soon template for maintenance mode) 

This css workaround does work for me but not ideal.
Please solve...

thanks in advance

**Comment by cgfred** [comment]
Same issue still remains for me also when sign the widget in a footer.

**Comment by arshish1612** [comment]
This issue is not fixed. Still need to use custom CSS to address the problem. Please fix.

**Comment by Aviad-Herman** [comment]
Hey guys,
Still experiencing the problem with Elementor 3.1.1?
If so, could you please share what css / html minimization plugin you are using?

**Comment by ph-webetc** [comment]
> Hey guys,
> Still experiencing the problem with Elementor 3.1.1?
> If so, could you please share what css / html minimization plugin you are using?

Still happening when minimising html (LiteSpeed Cache).
When html minify turned off, there seems to be some extra spacing before the widget in mobile responsive which doesn't show in the editor.

**Comment by juzer-hakimji** [comment]
Hi
facing the same issue with elementor version 3.1.3
I am using LiteSpeed Cache plugin to minify HTML and CSS

**Comment by juzer-hakimji** [comment]
Meanwhile I am using this workaround

```
.elementor-social-icons-wrapper > .elementor-grid-item {
	margin-right: 1rem;
}
```

**Comment by ph-webetc** [comment]
The spacing issue appears to be something to do with the Columns>Auto setting - I can resolve it by manually setting the number of columns to match the number of icons.

**Comment by martinsapinis** [comment]
> The spacing issue appears to be something to do with the Columns>Auto setting - I can resolve it by manually setting the number of columns to match the number of icons.

Thank you! had the same problem with latest elementor and Lite speed cache plugin. Just choose exact amount of Columns for icons and problem resolved.

**Comment by cgfred** [comment]
> The spacing issue appears to be something to do with the Columns>Auto setting - I can resolve it by manually setting the number of columns to match the number of icons.

Thanks to worked excellent for me too.

**Comment by wpministry** [comment]
###The spacing issue appears to be something to do with the Columns>Auto setting - I can resolve it by manually setting the number of columns to match the number of icons.

This works in Chrome but not in Edge.
