### ISSUE TITLE
How can I disable Google fonts?

### ISSUE THREAD

**Issue by ali110309** [elementor/elementor#13119]
Hello
I'm going to disable Google fonts.
Please advise what code I can use in my theme or plugin to disable Google fonts in the Mentor plugin.
Thanks

**Comment by DorShahar** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

thanks.
