### ISSUE TITLE
Bullet point appearing in upper right of sidebar widget

### ISSUE THREAD

**Issue by TimOMagee** [elementor/elementor#13116]
[Bullet in Sidebar Widget Elementor Bug.docx](https://github.com/elementor/elementor/files/5573847/Bullet.in.Sidebar.Widget.Elementor.Bug.docx)
Good afternoon,

I purchased Elementor Pro for a second website and decided to use Elementor Hello as the theme. It doesn't come with a sidebar widget. Elementor made the following suggestion:
To enable the Widgets menu item in the WordPress admin menu, use the following code:

if (function_exists("register_sidebar")) {
register_sidebar();

So I did that using the Code Snippets plug-in—and voila I had a sidebar.

The only challenge is that at the upper right of the top of the side bar there is a round bullet.

I have tried several solutions but this seems to be a bug in Elementor Hello.

Any ideas?

I can't send a link because it's on a development site.

Thank you in advance for your help. Sincerely, Tim Magee.

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
