### ISSUE TITLE
Elementor hides code

### ISSUE THREAD

**Issue by ArtySites** [elementor/elementor#13110]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by ArtySites** [comment]
Elementor hides inline CSS that is entered in the text areas. For example, let's say I want to style just one link in one text box. I put in the code for things like color change on mouseover. It works. But once I leave the text box, if I go back, some of the code isn't visible. The link and styling effects still work, but I can't see what I did. If I want to remember what colors I used, or exactly what I did to make the effect, I have to use Inspector (or remember to save my work elsewhere.) The same thing happens with some kinds of text formatting, but I don't have a specific example right now.

**Comment by shilo-ey** [comment]
Hi @ArtySites 

The native Text editor widget uses TinyMCE to add rich text editing capabilities, and they have 2 options: Visual / Text.

Adding CSS / HTML in the text area might change when focusing out of the text area. 
I would suggest you to use Elementor [Custom CSS](https://elementor.com/help/custom-css-pro) feature for better results.

Thanks
