### ISSUE TITLE
Can't determine which element is which

### ISSUE THREAD

**Issue by ttodua** [elementor/elementor#13123]
For example, I have 7 different search widgets. When I add one of them inside editor, and after a while, I click that element,
I can't find out which one (from those 7 widgets) specifically I have used. So, i can't identify the added elements.
https://i.imgur.com/GPMJOM6.png
Please add some functionality, that will show up the Widget icon in the EditorPanel for any widget (like in Yellow marked areas: https://i.imgur.com/msZzORw.png)

**Comment by DorShahar** [comment]
Hi @ttodua 
I suggest that you rename each widget in the navigator. 
This will help you to identify your widgets.

I'm closing the issue.
If more issues like that will rise, We will definitely consider a solution to the problem.

Thanks for the understanding
