### ISSUE TITLE
Elementor Headline two Words on one line with Space

### ISSUE THREAD

**Issue by magino50** [elementor/elementor#13128]
Hi, 
I am not sure if its a bug or a feature request, but please make it possible that its possible to use two Words with spacing on the Animated Headline module.

For example: Hello World
-> Which gets shown as "HelloWorld"
even when I put a HTML Space in between. Why is it not possible to use two words?
Thanks

**Comment by DorShahar** [comment]
Hi @magino50 
Thanks for reaching out.
I don't understand your request. Please go over the Animated Headline links, I think you find your solution here:
1. https://elementor.com/widgets/animated-headline/
2. https://elementor.com/blog/introducing-animated-headline/

Reach out if you didn't found a solution - we can discuss further on this.
Thanks

**Comment by magino50** [comment]
Hi, to be clearer, here is a Screenshot.
When I write "Brand Strategy", the words get glued together! Thanks.

![image](https://user-images.githubusercontent.com/74729773/99993220-a4147000-2db7-11eb-9cfa-a6b3d131b477.png)
![image](https://user-images.githubusercontent.com/74729773/99993242-aaa2e780-2db7-11eb-8acf-70d0cfb13ecf.png)

**Comment by DorShahar** [comment]
Hi @magino50 
I cannot reproduce it.
Please check if another plugin or the theme harming the experience.
In any way - you can contact our [Support](https://elementor.com/support/).

Thanks
