### ISSUE TITLE
Show Style Values in Mobile / Tablet

### ISSUE THREAD

**Issue by SanDiegoCasey** [elementor/elementor#13149]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, all styles that are set on the Desktop view, are carried down to Tablet and Mobile, however there is no indication that they are a style that comes from an upper viewport as opposed to some other styling.  

When we encounter this it would be convenient to know that it is a custom widget level style that was added and what it is. instead of just providing a remove option. 

At this point, we can either clear all the styles or change back to the desktop view to check them and then switch back again with the styles in our head to adjust. 

**Describe the solution you'd like**

Would be nice to have a greyed-out *tip,  showing what it is currently which by being there would signal it was set on desktop or an upper layout in the case of Tablet > Mobile. 

**Describe alternatives you've considered**

Using CSS and breakpoints on everything, which is what I do most of the time, but for these types of reasons. 

**Additional context**

**Comment by webdevs-pro** [comment]
+1

**Comment by DorShahar** [comment]
Hi @SanDiegoCasey ,
This will be part of the "Additional Breakpoints" project. 

Therefore - I'm merging this issue with #2043 for easier tracking.

Thanks.
