### ISSUE TITLE
Cant delete Newsletter section with footer

### ISSUE THREAD

**Issue by dgfbankcom** [elementor/elementor#13140]
I have a problem with deleting the Newsletter section with the footer. 
Cant delete the Newsletter line, block, or whole footer cause of it. Nothing works, even trying past versions. 
Due to this, I have 2 footers on the main webpage now(
My WP version 5.5.3, Elementor 3.0.9
If somebody had the same problem and get a solution, pls help!
https://drive.google.com/file/d/1ziDVkMd6K70_wEoHUQY9AUTjSHcI475O/view?usp=sharing

**Comment by DorShahar** [comment]
The Newsletter widget is not Elementor's widget.
You can always do nasty solution like to use CSS with `display:none;`



--------------
Please create GitHub issues only for bugs reports and feature requests.
GitHub issues are not for support!

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

thanks.
