### ISSUE TITLE
UI elements not loading properly in backend

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#13143]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Occasionally, UI elements won't load properly in the backend - for instance, the "close arrow" here didn't load, and strange characters appear instead:

![image](https://user-images.githubusercontent.com/1435638/100053394-e13c3900-2e6f-11eb-8345-ad8ed5f9259b.png)

## Steps to reproduce

Happens intermittently

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hey @drawcard 

Thanks for your feedback

This happens when the cached version of e-icons is not loaded properly.

Clear cache (CTRL + SHIFT + R) to load it properly

Thanks

**Comment by drawcard** [comment]
Thanks @shilo-ey , I will try this when the issue crops up again.
