### ISSUE TITLE
Accordion Expansion for Image and Label

### ISSUE THREAD

**Issue by critterles** [elementor/elementor#13142]
I have do this with code but option in the Accordion would make it so much easier.
1. Add an image with size and position options to the title line of the accordion. right-left-center. Show it on top.
2. Align the title Right-Left-Center
3. Schedule each item for display per a date parm. Show and hide.
This concept works great on the mobile.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by Serpent6877** [comment]
@critterles Can you please point me to how you were able to add an image to the Accordion Title? I have looked all over on how best to do this. I am trying to add an image to the right for a food menu.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Accordion widget was released with Elementor v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
