### ISSUE TITLE
Finder (called from frontend) will inherit site Global Theme properties

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#13156]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When accessed from the frontend (ie visiting a page while logged in, and pressing Cmd-E), Elementor Finder will inherit styles from the website's Global Settings, causing it to appear in random fonts and colours. 

The Finder styling should be decoupled from the website theme's styles, and have its own independent appearance.

Here is an example of it inheriting Arial, with orange hover underline style, which was set in Elementor's Global Typography:

![image](https://user-images.githubusercontent.com/1435638/100173649-d8547180-2f1a-11eb-9bbe-6106c52d2140.png)

## Steps to reproduce

- Use Global Theme / Typography to set some styles
- Visit the front end of your website while logged in
- Press Cmd-E and see that typography styles have been inherited

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @drawcard ,
Thank you for your input.
At the moment, we don't see it necessary, and our teams are focusing on another area of the product.

I'm closing the issue, and if more suggestions from this area will rise up, we will consider changing it.

Thanks again.
