### ISSUE TITLE
creating a page system

### ISSUE THREAD

**Issue by hurtrez** [elementor/elementor#13157]
Hi
On behalf of a client, I have to create this page principle that he particularly appreciates :

https://www.molecularproducts.com/

Frozen vertical bands that come alive when the mouse passes over them, both by the video and by the movement that the latter generates.
Each mouse click will of course send to a specific page.
I thought Elementor made it easy to do, but now I'm blocking.

Thank you for your help

**Comment by DorShahar** [comment]
Hi @hurtrez ,
We don't support that option yet. 
We will consider making it work with the feature request below.

------ 

Merged issue

I merged this issue with  #6116 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by DorShahar** [comment]
@hurtrez 
You can look at other plugins, like this one: https://codecanyon.net/item/unleash-a-wordpress-responsive-accordion-slider/12688077

Thanks

**Comment by hurtrez** [comment]
Hiand thank you for this feedback
unfortunately the links appear to be dead. I watched the video that introduces the concept, it seems to match, great ... but what guarantee that it works ...? I will dig the thing
Thank you already for your responsiveness

**Comment by hurtrez** [comment]
I also note that the video has photo integrations and not videos ... too bad
but in any case, thank you for the approach
Someone might have a better idea ;-)
