### ISSUE TITLE
Dropdown Menu Icon

### ISSUE THREAD

**Issue by okkine** [elementor/elementor#13151]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The icon used for the dropdown menu is not customizable, and is permanently stuck on the hamburger icon.

**Describe the solution you'd like**
It's not urgent, but it would be nice if we could change the icon (including uploading our own) for the dropdown menu, instead of being stuck with the three lines. Thanks!

**Describe alternatives you've considered**
Considered making my own dropdown menu from scratch, but I only have a rough idea on where to start, and I really don't have the time right now.

**Additional context**

**Comment by Phenomen** [comment]
Agree. Hamburger icon and submenu dropdown icons should be customizable. I would like to completely get rid of FontAwesome bloat and use custom SVG icons.

**Comment by fuzenco** [comment]
Agreed. It’s this refinement, granular stuff that would make me lean more heavily on Elementor versus gravitating to Webflow.

**Comment by gilesholder** [comment]
Would love this! Custom SVG or Lottie file support would be amazing!

**Comment by mrbenjaminjo** [comment]
This is already open here: https://github.com/elementor/elementor/issues/11361

They don't care. The hamburger icon is now 15% of my page load.

**Comment by 79ho3ein** [comment]
+1

**Comment by fuzenco** [comment]
> They don't care. The hamburger icon is now 15% of my page load.

You’re saying it’s that high because you’re having to load the entirety of Font Awesome? I’ve never really looked into what contributes to the overall weight of Elementor.

**Comment by mrbenjaminjo** [comment]
> > They don't care. The hamburger icon is now 15% of my page load.
> 
> You’re saying it’s that high because you’re having to load the entirety of Font Awesome? I’ve never really looked into what contributes to the overall weight of Elementor.

The hamburger is in e-icons, I think. ...and yes - if you want the default mobile menu you're loading the full icon set (or were when I wrote this!)

I've completely moved to Oxygen now though, which destroys elementor from a requests/page size perspective. It's actually embarrassing at this point for elementor.

**Comment by fuzenco** [comment]
> I've completely moved to Oxygen now though, which destroys elementor from a requests/page size perspective. It's actually embarrassing at this point for elementor.

I’m new to WordPress so I’d never heard of Oxygen. Have you ever used it with WooCommerce; fully compatible?

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
