### ISSUE TITLE
SVG Upload Conflict - Upload Disabled Even When Using SVG Support Plugin

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#13150]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I'm unable to upload SVG file while editing Elementor page until I enable "Enable Unfiltered Files Uploads" setting.
This is happening even though I have [SVG Support plugin](https://wordpress.org/plugins/svg-support/) installed and properly configured.

When I disable Unfiltered Files Uploads in Elementor settings:

![obrazek](https://user-images.githubusercontent.com/5634870/100136205-fffbf900-2e8a-11eb-9373-e43ac4bd371c.png)

I get this error message while attemting to upload a SVG file:

![obrazek](https://user-images.githubusercontent.com/5634870/100136248-143ff600-2e8b-11eb-8224-ce787fbffc7a.png)

This is happenig only while editing the Elementor page. It's not happening if I upload SVG file right into the Media Library or while editing a non Elementor page. I suppose this has to do something with uploading the SVG icons, but I'm not sure wheather this is the correct behaviour.

Moreover, **what is the actual status of Elementor's SVG Support**? Do I need any SVG support plugin, when Elementor is active? Because it SEEMS, that I don't!
- When Elementor is active, I can upload and preview any SVG file without any further issues (except this one reported here). 
- **I can upload SVG files even when the "Enable Unfiltered Files Uploads" is disabled!** But only to the Media Library, not while editing the pages.

I'd like to know the official Elementor statement and recommendation on how to deal with SVG files correctly and safely.

## Steps to reproduce
1. Install and activate SVG Support Plugin
2. Install and activate Elementor & Elementor Pro
3. Check wheather "Enable Unfiltered Files Uploads" setting is disabled.
4. Create and edit Elementor page
5. Drag in the Image widget
6. Open the image selection dialog and try to upload SVG file in there.

Change "Enable Unfiltered Files Uploads" setting to enabled and repeat the steps 4-6.

Also check out uploading SVG files right into the Media Library, both when "Enable Unfiltered Files Uploads" setting is disabled and enabled.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.3.27
	PHP Version: 7.3.24
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.4
	Site URL: https://www.daihatsu-auto.cz/test
	Home URL: https://www.daihatsu-auto.cz/test
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: cs
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

== Active Plugins ==
	Activity Log
		Version: 2.6.0
		Author: Activity Log Team

	Admin Menu Editor
		Version: 1.9.7
		Author: Janis Elsts

	Caldera Forms
		Version: 1.9.2
		Author: Caldera Forms

	Central Color Palette
		Version: 1.15.5
		Author: Daniel Menzies

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Clean Image Filenames
		Version: 1.3
		Author: Upperdog

	Disable Comments
		Version: 1.11.0
		Author: WPDeveloper

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

	HappyFiles Pro
		Version: 1.4.1
		Author: Codeer

	Intuitive Custom Post Order
		Version: 3.1.2
		Author: hijiri

	iThemes Security
		Version: 7.9.0
		Author: iThemes

	Lightbox with PhotoSwipe
		Version: 3.1.3
		Author: Arno Welzel

	Nested Pages
		Version: 3.1.11
		Author: Kyle Phillips

	Page Builder Framework Premium Addon
		Version: 2.5.6
		Author: David Vongries

	The SEO Framework
		Version: 4.0.7
		Author: The SEO Framework Team

	TinyMCE Advanced
		Version: 5.4.0
		Author: Andrew Ozz

	WPvivid Backup Plugin
		Version: 0.9.46
		Author: WPvivid Team

	Yoast Duplicate Post
		Version: 3.2.6
		Author: Enrico Battocchi & Team Yoast

	Zalomení
		Version: 1.4.7
		Author: Honza Skypala


== Elements Usage ==
	
	footer : 1
		heading : 5
		shortcode : 3
		social-icons : 1
		text-editor : 1
	page : 1
		image : 1
	single : 1
		heading : 1
		text-editor : 1
	wp-page : 8
		divider : 1
		google_maps : 1
		heading : 8
		image-box : 30
		tabs : 1
		text-editor : 15
		wp-widget-caldera_forms_widget : 1


== Log ==
	
Log: showing 20 of 412020-08-15 20:34:21 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-15 20:34:21 [notice] Custom colors already exist. nothing to do. 
2020-08-15 20:34:21 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-15 20:34:21 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-15 20:34:21 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-15 20:34:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta4',
  'to' => '3.0.0-beta5',
)]
2020-08-15 20:34:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta4',
  'to' => '3.0.0-beta5',
)]
2020-08-15 20:35:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0-beta1',
  'to' => '3.0.0-beta2',
)]
2020-11-24 18:22:36 [info] elementor::elementor_updater Started 
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-11-24 18:22:36 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-11-24 18:22:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta5',
  'to' => '3.0.13',
)]
2020-11-24 18:22:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta5',
  'to' => '3.0.13',
)]
2020-11-24 18:26:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0-beta2',
  'to' => '3.0.6',
)]

PHP: showing 1 of 1PHP: 2020-08-07 11:07:36 [notice X 19][/www/doc/www.daihatsu-auto.cz/www/test/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2020-08-07 12:38:01 [error X 1][https://www.daihatsu-auto.cz/test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.0-beta4:2:461325] this.container is undefined 


				
```
</details>

**Comment by guibarbas** [comment]
Hello, good evening, how are you ?

I also have the same problem.

Even upgrading to V3.0.14, the error persists.

**Comment by shilo-ey** [comment]
Hi all,

Elementor handles the uploads via Elementor Editor.
It doesn't allow users to upload SVG files outside of Elementor Editor.
The reason for this is due to sanitation mechanism implemented in Elementor, that reduces the risk of uploading unfiltered files.

If you still want to upload unfiltered files, please use Elementor, add the mime type to be supported or alternatively use external plugin.

Thanks

**Comment by black-eye** [comment]
@shilo-ey Please read my comment carefully. Maybe I wasn't clear enough,

What I've experienced is:
-  I CAN upload SVG files to Media Library, even when there's no plugin for SVG support installed. Just Elementor & Elementor Pro allows me to do that. 
- When I deactivate E+E PRO, I cannot upload SVG anymore. So I'm quite sure, Elementor itself enables this, not a theme or some other plugin.

I would be fine, if I wouldn't be able to upload SVG without enabling uploading unfiltered files. But the situation is,  I CAN upload SVG files to Media Library, even when I disable this option, only by activating the Elementor. The restriction applies only to uploading SVGs while editing the page in Elementor.

That is why I've asked the question on the status of Elementor's SVG support. Because it seems that Elementor itself brings SVG support. But I'm afraid it's a side effect even you are not aware of.

Please check this problem again!

**Comment by shilo-ey** [comment]
Thanks @black-eye , but this issue has been fixed in the last version of Elementor.
Please try again and let me know if the issue persists

**Comment by black-eye** [comment]
@shilo-ey Oh, my fault, didn't mention the last updates. 
So OK, now I can't upload SVG to the Library, when there's no SVG suport plugin activated.

On the other hand, there are still inconsistencies, that are baffling:

**1. No SVG support plugin, Elementor's unfiltered upload enabled**
I can upload SVG to the Library when editing, but not directly. Why not both? Elementor has apparently the ability to do so, so why not add the SVG support officialy? (Of course as an option, not by default.)  One less plugin needed.

**2. SVG support plugin activated, Elementor's unfiltered upload disabled**
I can upload SVG to Library, but not while editing. Why Elementor overrides the settings enabled by 3rd part plugin? I've already enabled this function elsewhere and I'm aware of the possible security problems - why Elementor wants me to do the same once again?

So, my suggetion is - please consider adding the SVG support officially.
Or don't override the settings made by 3rd party plugins.
Thanks

**Comment by Ezra-Siton-UIX** [comment]
Wordpress = Headache. For such simple idea (Upload simple SVG) - you need to search a solution for hours. The worst CMS EVER: ) Thanks

**Comment by benjaminpeto** [comment]
This issue still persist on latest version. Has anyone managed to upload SVGs? It's super annoying..

**Comment by josephkabba** [comment]
This is really annoying. I have done all that is needed:
1. Allowed SVG usage.
2. Used a code snippet.
3. Used a plugin.

But for some reason SVGs ARE STILL NOT ALLOWED BY WORDPRESS. IT IS THE MOST STUPID THING I HAVE SEEN IN SOFTWARE DEVELOPMENT HISTORY.
