### ISSUE TITLE
Entrance Animation Delay Specific for Desktop, Tablet & Mobile

### ISSUE THREAD

**Issue by contempoinc** [elementor/elementor#13153]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Having animation delays that are device-specific, a lot of the times delays need to be changed for smaller displays especially when elements are stacking in different orders depending on the screen size, might come sooner or later in the flow which means an entrance animation on desktop set for a delay of 800ms is going to be different when that element shows on a tablet or mobile device can be 200ms since it appears later in the scroll, so now when a user scrolls into that element on a mobile device it takes 800ms to show and looks terrible, also kills usability as they might just keep scrolling past thinking nothing is there, so the only option is to remove the animation for that device. Which is fine but maybe not ideal for all cases. Hope that makes sense.

**Describe the solution you'd like**

Allow for the delay to be device-specific (desktop, tablet, mobile) just like the entrance animation type itself is.

**Describe alternatives you've considered**

There are none, other than removing the animation altogether for tablet or mobile.

**Additional context**

None

**Comment by DorShahar** [comment]
Hi @contempoinc 
You can use [Entrance Animation](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay) wrapped in [media-query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) for now - based on your device width.

It will take time for use to develop something like this since we have other priorities in our queue.
