### ISSUE TITLE
Elementor Pro Bug: Posts Widget stuck at 10 posts per page under current query

### ISSUE THREAD

**Issue by jordanjustkidding** [elementor/elementor#13154]
When using the Posts widget, if I set the query to 'Current query' then the number of posts shown becomes stuck at 10 posts per page. Doesn't matter if I type 1 post per page, or 100 posts per page, it remains stuck at 10 posts per page. Only seems to occur with 'Current query'.

**Comment by Ectropy** [comment]
I found a workaround.

Go to Settings > Reading (Settings) > "Blog pages show at most x posts" > change to the desired number of posts.

I was having a similar problem where I was only seeing 3 posts per page when using current query. (For category pages or search results pages). Mine was set to "show at most 3 posts". Changing this to a different number fixed it for me.

**Comment by jordanjustkidding** [comment]
Ah, thank you @Ectropy. That fixes the problem nicely. 

Such a simple thing but an easy one to overlook where the default Wordpress controls are conflicting with Elementor's controls.

**Comment by Aviad-Herman** [comment]
Hey,
Thanks for answering @Ectropy.

I'll merge it with another issue (#12126) for future reference.

**Comment by rwkyyy** [comment]
@Aviad-Herman this issue is still persistant, I have 3 custom post types that I need to show different number of posts per page and now I'm forced to show only the global one.

**Comment by Aviad-Herman** [comment]
@rwkyyy
Yea, currently you can't set a different number posts per page for each archive template.
Unfortunately it will require us to grossly override core WordPress functionality, which will take a lot of effort, might cause many bugs and keep making new bugs in the future. I will raise this issue again to the dev team but to be honest I can't promise this will be done anytime soon or at all. 

There might be some hacky creative solutions like creating your own fake archive pages and setting up redirects and / or trying to use the posts widget instead of the archive widget.

**Comment by rwkyyy** [comment]
@Aviad-Herman I understand, but if you need an example of implementation I ended up using AnyWhere Elementor and it's all good.

**Comment by mclendening** [comment]
> @Aviad-Herman I understand, but if you need an example of implementation I ended up using AnyWhere Elementor and it's all good.

How did you work around this issue in AE? I'm still having the same problem with displaying different number of post per page in an AE archive template using a Query Source of "Current Archive". The option to limit the number of post per page is not available when using this source.

**Comment by rwkyyy** [comment]
> > @Aviad-Herman I understand, but if you need an example of implementation I ended up using AnyWhere Elementor and it's all good.
> 
> How did you work around this issue in AE? I'm still having the same problem with displaying different number of post per page in an AE archive template using a Query Source of "Current Archive". The option to limit the number of post per page is not available when using this source.

I just add `ae - post block` and set number per page + pagination.

**Comment by TheLucDev** [comment]
thanks you so much <3 from the bottom of my heart

**Comment by atikurrion** [comment]
Many many thanks to you, you made my day!
