### ISSUE TITLE
New pop up triger

### ISSUE THREAD

**Issue by ibd2004** [elementor/elementor#13166]
Hello
It can.be great if you can add a new pop up triger such as:
1. adding spesific item to cart.
2. When total cart amount is more than X but less than Y.

I will be happy to see those trigers.
Thank you
Itai

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by ibd2004** [comment]
Hi
What tr hat means?
Any chance this will be done soon?
Thank you

בתאריך יום א׳, 29 בנוב׳ 2020, 17:59, מאת Dor_S ‏<notifications@github.com>:
