### ISSUE TITLE
✅ 🐞 Missing icon and tooltips error in Elementor form

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#13171]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

If we have an Elementor form that has a field reCAPTCHA V3 in it, there are bugs.

First thing, when we click the Send button, if a field contains errors (ie. missing fields), the tool tip doesn't work and the error message is put under the erroneous field.

Second thing, when sending the form, there is a rolling icon that appears in the button, left to the button text. When the form contains the field reCAPTCHA V3, that rotating icon is wrong. It shows a kind of rectangle that rotates. It looks like a missing icon. 

## Steps to reproduce

1. First, add the integration of reChaptcha V3 in Elementor settings page (public and secret keys). 
2. Add a form widget in a page.
3. Publish the page and view the page.
4. Click on the Send button.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by nicholaszein** [comment]
Hello there @vgstef!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

Icons in the forms should appear correctly now when the Inline Font Icons experimental feature is active.

This should solve your issue. However, if you are still experiencing issues with ReCaptcha3, please open a new issue and provide the required information so we can properly verify it.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
