### ISSUE TITLE
Form step bug

### ISSUE THREAD

**Issue by Imaginaerum** [elementor/elementor#13178]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

An empty element appear when creating a form step... No action is possible...

![bug](https://user-images.githubusercontent.com/7314174/100385211-4d5e9e80-3022-11eb-948f-34a557ab614a.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.30
	PHP Version: 7.3.24
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	WP Multisite: No
	Max Upload Size: 64 Mo
	Memory limit: -1
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		heading : 6
		icon-list : 4
		image : 1
		social-icons : 1
		text-editor : 1
	header : 1
		html : 1
		social-icons : 1
	popup : 1
		theme-site-logo : 1
		wp-widget-nav_menu : 1
	wp-page : 14
		button : 4
		call-to-action : 1
		flip-box : 1
		form : 1
		google_maps : 1
		heading : 19
		html : 2
		icon-box : 6
		image : 2
		media-carousel : 1
		nav-menu : 1
		price-table : 3
		reviews : 1
		text-editor : 5
		theme-site-logo : 1
		wp-widget-nav_menu : 1

</details>

**Comment by dasigna** [comment]
if this was the only bug with form steps / steps form i would be VERY happy.
currently it throws error after error and is definitely not useable at all ... beginning with always jumping back to first step upon editing up to unfunctional responsiveness of steps and buttons.
the whole thing is a complete mess!

**Comment by Aviad-Herman** [comment]
Hey,
There are a few bugs in the form widget but this is not one of them :)

If you add a step to a form it automatically ads a step at the start of the form. This makes sense.
You can't delete it but you can click it to reveal more options.

If you delete all steps from the form it will also disappear.

**Comment by dasigna** [comment]
... if THIS is no bug i would be very glad you would at least resolve the 'few ones' that are there. finally.

**Comment by Aviad-Herman** [comment]
Will do, my friend
