### ISSUE TITLE
[BUG - TEMPLATE WIDGET] - CSS of the "Template" widget doesn't load in editor if you use the widget in "Single Post/Product" template

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#13173]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

CSS of the "Template" widget doesn't load in editor if you use the widget in "Single Post/Product" template. 

Here is a screen of the bug for easier understanding:

![Template](https://user-images.githubusercontent.com/36289156/100336125-14004180-2fd6-11eb-8aa7-af7c207ab286.png)

## Steps to reproduce

1. Create a section with some content and style the content.
2. Save the section as a template.
3. Create a Single Post or a Single Product template with all the usual content (Title, Post Content, Featured image). 
4. Insert the saved section through the Template widget.
5. Save and close.
6. **Reopen the Single Post/Product template in the editor.** (The CSS loads when you first insert the widget, but not when you open the editor again.)
7. **The content of the Template widget loads unstyled (CSS of that template is not loaded in editor.).**
__
- **It's happening in the Single Post and Single product templates. It might be happening in other dynamic templates - I haven't tested those (Archive templates etc.).**
- **It's not happening in regular pages.**
- **The CSS doesn't load only in editor, frontend is fine**.

This bug has been there for some time now. It 100% is a bug and I've been experiencing it consistently on many websites. It's not a huge problem because it works fine on frontend, but it should be fixed.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.41-84.1
	PHP Version: 7.4.12
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.7
		Author: Elementor.com

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 1
		heading : 2
	header : 2
		button : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	page : 2
		form : 1
		heading : 5
		text-editor : 1
	section : 1
		button : 3
		heading : 2
	wp-page : 1
		button : 5
		heading : 80
		icon : 6
		image : 17
		menu-anchor : 1
		testimonial-carousel : 1
	single-post : 1
		template : 1
		theme-post-content : 1
		theme-post-title : 1

== Log ==
	
Log: showing 3 of 32020-11-08 13:50:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-11-26 09:26:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-11-26 09:27:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]

PHP: showing 1 of 1PHP: 2020-11-08 18:38:19 [notice X 3][/data/web/virtuals/202311/virtual/www/domains/energom.mbdemo.cz/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2020-11-26 08:37:07 [error X 1][https://energom.mbdemo.cz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view78\") has already been destroyed and cannot be used. 
JS: 2020-11-26 09:31:14 [error X 1][https://energom.mbdemo.cz/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view87\") has already been destroyed and cannot be used. 

</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
