### ISSUE TITLE
Save as draft on published posts does not save a draft but a revision.

### ISSUE THREAD

**Issue by herregroen** [elementor/elementor#13175]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When saving a published post as a draft that post is not saved as a draft but instead as a revision. This can cause issues as third-party plugins are likely to save data to post_meta which will be written to the published post instead of the revision as WordPress core automatically substitutes the post IDs of revisions with the published variant.

The end result is that your post_content is saved to a revision but all post_meta is saved to the published post which could lead to issues ( for example, if storing the meta description in post meta it may lead to cases where a rewritten post in draft warrants a very different meta description which will then be saved to the original post where it may not make sense ).

## Steps to reproduce

1. Create a plugin that adds an input field somehwere in elementor.
1. Hook into the save action of elementor and send your own ajax/REST request to save the value of this input to post_meta.
1. Open a published post.
1. Change your input.
1. Save your post as draft.
1. Observe how the post_meta of the published post is changed and not the revision.

## Isolating the problem

This explicitly concerns integrations with other plugins so does not occur with only elementor active.
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Will happen on any environment.

**Comment by iNewLegend** [comment]
Hi,
If you use [elementor/documents/ajax_save/return_data](https://code.elementor.com/hooks/elementor-documents-ajax_save-return_data/)
you will have the relevant information.

Beyond that, if you will create the input using the Elementor Controls system, you don't have to manually handle the *meta data*.
If your input field is data of the document settings, it will be available via `$document->get_db_document_settings()`
if your field is data of widget, it will be available via `$document->get_elements_data()`
