### ISSUE TITLE
Update of 3.014/3.07 causes media carousel navigation issues.

### ISSUE THREAD

**Issue by Worldwebscapes** [elementor/elementor#13172]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

After updating, the navigaion arrows for the media carousel both appear of the right as X's

## Steps to reproduce
Drag a media carousel to the page and see the issue.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.
![image](https://user-images.githubusercontent.com/7572038/100326380-e2688580-2f97-11eb-9a3a-4a419f4ae665.png)

Other users from Elementor Facebook are reporting the same.

![image](https://user-images.githubusercontent.com/7572038/100326466-03c97180-2f98-11eb-811a-99e1a5217b03.png)

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.32
	PHP Version: 7.3.24
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://mysandboxwebsite.com
	Home URL: https://mysandboxwebsite.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

== Active Plugins ==
	ACF Frontend
		Version: 2.6.20
		Author: Shabti Kaplan

	Advanced Custom Fields
		Version: 5.9.3
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 7.31
		Author: ServMask

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Custom Post Type UI
		Version: 1.8.1
		Author: WebDevStudios

	Disable Comments
		Version: 1.11.0
		Author: WPDeveloper

	Dynamic Content for Elementor
		Version: 1.9.6.7.2
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.7
		Author: Elementor.com

	FakerPress
		Version: 0.5.0
		Author: Gustavo Bordoni

	OoohBoi Steroids for Elementor
		Version: 1.5.6
		Author: OoohBoi

	WooCommerce
		Version: 4.7.1
		Author: Automattic

	WP User Avatar
		Version: 2.2.8
		Author: ProfilePress

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	installatron_hide_status_test.php
		Version: 
		Author: 

== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		heading : 5
		image : 1
		social-icons : 1
	popup : 7
		form : 3
		heading : 6
		image : 3
	widget : 0
		html : 2
	single : 2
		author-box : 1
		heading : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		table-of-contents : 2
		theme-post-content : 2
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 2
		wp-widget-categories : 1
		wp-widget-meta : 1
		wp-widget-recent-posts : 1
	section : 7
		heading : 22
		icon : 5
		shortcode : 3
		tabs : 1
	custom_grid : 1
		button : 1
		heading : 1
		text-editor : 1
	product : 2
		heading : 1
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-images : 2
		woocommerce-product-meta : 1
		woocommerce-product-price : 2
		woocommerce-product-rating : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 3
	page : 24
		accordion : 1
		alert : 1
		button : 29
		countdown : 1
		divider : 14
		heading : 154
		icon : 3
		icon-box : 5
		icon-list : 1
		image : 8
		lottie : 9
		nav-menu : 2
		posts : 3
		price-table : 3
		progress : 5
		slides : 2
		spacer : 7
		tabs : 4
		text-editor : 30
	loop : 2
		button : 2
		heading : 3
		post-info : 2
		theme-post-featured-image : 1
		theme-post-title : 1
	header : 3
		dyncontel-modalwindow : 1
		nav-menu : 1
		theme-site-logo : 1
		theme-site-title : 1
	footer : 1
		heading : 2
		nav-menu : 1
		social-icons : 1
	wp-page : 8
		button : 10
		form : 2
		gallery : 1
		heading : 72
		html : 1
		icon : 1
		image : 1
		lottie : 2
		media-carousel : 1
		portfolio : 1
		posts : 1
		social-icons : 3
		tabs : 4
		text-editor : 12
		video : 1
	error-404 : 1
		button : 1
		heading : 3
		search-form : 1
		text-editor : 1
	single-post : 1
		button : 1
		post-info : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	single-page : 3
		heading : 2
		post-info : 1
		theme-post-content : 1
		theme-post-title : 1
		wc-elements : 1
	search-results : 1
		archive-posts : 1
		search-form : 1
		theme-archive-title : 1
	product-archive : 1
		wc-archive-products : 1

== Log ==
	
PHP: showing 6 of 6PHP: 2020-10-19 14:07:58 [notice X 23][/home/mysandboxwebsite/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-22 17:29:57 [notice X 116][/home/mysandboxwebsite/public_html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-23 12:28:47 [notice X 26][/home/mysandboxwebsite/public_html/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-24 12:18:54 [warning X 79][/home/mysandboxwebsite/public_html/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/home/mysandboxwebsite/public_html/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-15 21:10:12 [notice X 2][/home/mysandboxwebsite/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-23 02:53:21 [notice X 2][/home/mysandboxwebsite/public_html/wp-content/plugins/elementor-pro/core/utils.php::217] Trying to get property 'post_author' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 31JS: 2020-10-24 15:51:44 [error X 1][https://mysandboxwebsite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:4:12675] Syntax error, unrecognized expression: #elementor-control-polygon(50% 0%, 80% 10%, 100% 35%, 100% 70%, 80% 90%, 50% 100%, 20% 90%, 0% 70%, 0% 35%, 20% 10%)-c28940 
JS: 2020-10-24 15:51:47 [error X 1][https://mysandboxwebsite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:4:12675] Syntax error, unrecognized expression: #elementor-control-polygon(50% 0%, 90% 20%, 100% 60%, 75% 100%, 25% 100%, 0% 60%, 10% 20%)-c28940 
JS: 2020-10-24 15:51:50 [error X 1][https://mysandboxwebsite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:4:12675] Syntax error, unrecognized expression: #elementor-control-circle(50% at 50% 50%)-c28940 
JS: 2020-10-26 13:00:16 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view8047\") has already been destroyed and cannot be used. 
JS: 2020-10-26 13:00:16 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view17656\") has already been destroyed and cannot be used. 
JS: 2020-10-26 21:12:39 [error X 1][https://mysandboxwebsite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:4:12675] Syntax error, unrecognized expression: #elementor-control-polygon(50% 0%, 80% 10%, 100% 35%, 100% 70%, 80% 90%, 50% 100%, 20% 90%, 0% 70%, 0% 35%, 20% 10%)-c1128 
JS: 2020-10-26 21:12:43 [error X 1][https://mysandboxwebsite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:4:12675] Syntax error, unrecognized expression: #elementor-control-circle(50% at 50% 50%)-c1128 
JS: 2020-10-26 21:12:45 [error X 1][https://mysandboxwebsite.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5.1:4:12675] Syntax error, unrecognized expression: #elementor-control-ellipse(25% 40% at 50% 50%)-c1128 
JS: 2020-11-10 17:31:42 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/dynamic-content-for-elementor/assets/js/dce-editor-form.js?ver=1.9.6.5:96:27] Cannot read property \'models\' of undefined 
JS: 2020-11-12 00:07:08 [error X 2][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view118\") has already been destroyed and cannot be used. 
JS: 2020-11-12 16:05:21 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view96\") has already been destroyed and cannot be used. 
JS: 2020-11-12 16:09:49 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view101\") has already been destroyed and cannot be used. 
JS: 2020-11-12 20:45:57 [error X 598][https://mysandboxwebsite.com/wp-content/plugins/dynamic-content-for-elementor/assets/js/dce-editor-visibility.js?ver=1.9.6.5:198:17] elementorFrontend.config.elements is undefined 
JS: 2020-11-20 13:54:01 [error X 2][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view104\") has already been destroyed and cannot be used. 
JS: 2020-11-20 14:09:59 [error X 2][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view121\") has already been destroyed and cannot be used. 
JS: 2020-11-20 21:29:12 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2311\") has already been destroyed and cannot be used. 
JS: 2020-11-23 12:59:12 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view30059\") has already been destroyed and cannot be used. 
JS: 2020-11-23 12:59:12 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view34235\") has already been destroyed and cannot be used. 
JS: 2020-11-25 15:31:00 [error X 1][https://mysandboxwebsite.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.13:2:160019] Routes: `theme-builder-publish/triggers` is already registered. 
JS: 2020-11-25 22:39:09 [error X 4][https://mysandboxwebsite.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.7:2:95150] Cannot read property \'setSettings\' of undefined 

Log: showing 5 of 52020-10-21 06:22:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 09:19:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-04 09:56:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-11-25 11:22:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-11-25 11:25:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]

				

```
</details>

**Comment by MichaelDarko** [comment]
Same here.

**Comment by Worldwebscapes** [comment]
Can replicate on another site/server with no other plugins enabled and only Hello.
![image](https://user-images.githubusercontent.com/7572038/100354326-ff17b400-2fbd-11eb-89e1-779663a7ad49.png)

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.49
	PHP Version: 7.4.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://www.worldwebscapes.com/training
	Home URL: https://www.worldwebscapes.com/training
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.7
		Author: Elementor.com


== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author:

**Comment by mcrowell** [comment]
I can confirm the same bug on my end on a brand new website.
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.32
	PHP Version: 7.4.12
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://webdesignvideos.com
	Home URL: https://webdesignvideos.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

== Active Plugins ==
	All In One SEO Pack
		Version: 3.7.1
		Author: All in One SEO Team

	BackWPup
		Version: 3.8.0
		Author: Inpsyde GmbH

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.7
		Author: Elementor.com

	Wordfence Security
		Version: 7.4.12
		Author: Wordfence


== Elements Usage ==
	
	header : 1
		nav-menu : 1
		theme-site-title : 1
	wp-page : 1
		heading : 1


== Log ==
	
PHP: showing 2 of 2PHP: 2020-11-25 11:32:41 [notice X 2][/home/webdesignvideos/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-25 11:33:52 [notice X 2][/home/webdesignvideos/public_html/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 2 of 22020-11-26 09:22:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-11-26 09:23:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]


![media-x-elementor](https://user-images.githubusercontent.com/7768009/100362526-8585c300-2fc9-11eb-9216-fad9ef4748dc.jpg)

**Comment by Worldwebscapes** [comment]
The issue has now been fixed in Elementor Pro 3.08.

Thank you for an amazingly swift patch.

**Comment by shilo-ey** [comment]
Cheers, thanks for your input!
