### ISSUE TITLE
Allow Elementor Global Colors to be Set Automatically in Wordpress Editor 

### ISSUE THREAD

**Issue by eSilverStrike** [elementor/elementor#13179]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Users when they create their own blog posts/pages using the built in Wordpress editor, they don't have easy access to the Global Colors set in Elementor. If they want to color something in a blog post using the Wordpress editor they end up picking colors that don't exactly match in the color picking tool.

**Describe the solution you'd like**
Allow Elementor to automatically overwrite the default colors set by the theme like Hello for the Editor with the Global colors set in Elementor

**Describe alternatives you've considered**
I currently set these editor colors by using code like

```
function mytheme_setup_theme_supported_features() {
    add_theme_support( 'editor-color-palette', array(
        array(
            'name' => __( 'strong magenta', 'themeLangDomain' ),
            'slug' => 'strong-magenta',
            'color' => '#a156b4',
        ),
        ...
    ) );
}
 
add_action( 'after_setup_theme', 'mytheme_setup_theme_supported_features' );
```

Unfortunately it is not done automatically so any changes in Elementor Global Colors I have to remember to do in my custom code.

**Additional context**

**Comment by DorShahar** [comment]
Hi @eSilverStrike 
Thank you for your input. We are thinking about working on this feature in 2021.

I'm merging this issue with #11351 for easy tracking.

**Comment by wordfishgroup** [comment]
Besides supporting the Gutenberg editor for content creation using the WordPress block editor, the ability to manage the theme styles only through Elementor would also benefit workflow when using Toolset blocks for building dynamic and advanced WordPress sites and Apps.
