### ISSUE TITLE
Navigation Submenu Dropdown Icons Are Not Loading Without FA4

### ISSUE THREAD

**Issue by Phenomen** [elementor/elementor#13185]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Since the last update, all submenu dropdown icons are not loading (outside of Editor mode) and shows as empty squares. Enabling FontAwesome 4 fix this issue but I do not want to load this library just for 1 icon.

![brave_1pMPzdvGEC](https://user-images.githubusercontent.com/138311/100466661-df07f380-3096-11eb-8ef7-60b04e1893d2.png)

## Steps to reproduce

1. Add the submenu indicator icon to the nav menu.
2. Save and exit Editor mode.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @Phenomen ,
Thanks for reporting.
 We are familiar with the issue and working to fix it. 

I'm closing the issue.
