### ISSUE TITLE
ELEMENTOR + CLOUDFLARE (not using Rocket Loader)

### ISSUE THREAD

**Issue by ZIODIOZIO** [elementor/elementor#13183]
idk why but my site is not able to load the page for editing with elementor. I am not using Rocket Loader. In order to exit pages i am forced to change url of the site into the ip address.

Can u help me out?
https://ricercatori-liceoeinsteinmilano.it/

**Comment by ZIODIOZIO** [comment]
idk why but my site is not able to load the page for editing with elementor. I am not using Rocket Loader. In order to EDIT pages i am forced to change url of the site into the ip address.

Can u help me out?
https://ricercatori-liceoeinsteinmilano.it/

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
