### ISSUE TITLE
Dynamic Tags for Tab Widget

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#13186]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Pretty self explanatory.... it'll let people easily create dynamic content inside Tabs that would otherwise need an Elementor Template to do so.

**Describe the solution you'd like**
Ability to set Dynamic Tags for text editor inside Tabs Widget

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Nested Tabs** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
