### ISSUE TITLE
FEATURE REQUEST: Eye Dropper Color Selector Option for Standard Elementor Color Picker Section

### ISSUE THREAD

**Issue by mjmultimedia** [elementor/elementor#13187]
I have a logo for a site. The logo has a particular shade of red I want to use as one of my site's template colors. Instead of trying to guess the color with the current Elementor color selector, I would love to be able to use an eyedropper to select a color off of the page. In this case, I'd select the red color on my logo which I added as an image in the header.

Can you add an eyedropper color selector option to your standard Elementor color picker?

Identical to how the eyedropper color selector works in photoshop or other applications.

## Prerequisites

- [ X ] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have no way to get the EXACT color from an image or logo I want to base my color pallet after.

**Describe the solution you'd like**
Eyedropper color selector option built into the standard color selection section in Elementor.

**Comment by mjmultimedia** [comment]
Alternative:
https://imagecolorpicker.com/en/

(This can give you an idea of what I'm hoping will be built into Elementor)

**Comment by DorShahar** [comment]
Hi @mjmultimedia ,
In the meanwhile, you can use [chrome extension like this one](https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp?hl=en) for a color picker.

**Comment by mjmultimedia** [comment]
Thank you for the suggestion!

Matthew Jordan
CEO | MJ Multimedia
www.mj-multimedia.com
<https://signrt.online/click?redirect=http%3A%2F%2Fwww.mj-multimedia.com%2F&dID=1606835249793&linkName=www.mj-multimedia.com>
