### ISSUE TITLE
More viewport emulations please

### ISSUE THREAD

**Issue by monographix** [elementor/elementor#13184]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It is a many years long requested feature now about additional (and custom) breakpoints. Although that would be an impressive feature for sure, i believe that carefully placing breakpoints for just three groups as currently Elementor is set-up to do, is adequate. What is more important though i believe when it comes to design responsively is the ability to check the design in all those screen viewports within the breakpoint groups in order to catch some element that has not been set-up responsively (it might look OK in eg 360px but when checked on 414px (iPhone 8) to discover that you have forgotten some padding or margin or size set in pixels as it will look either out of place or size) This is vital

**Describe the solution you'd like**
Please . More viewports preview options. Eg width sub-options WITHIN the main two current viewports of Tablet (currently emulating only 768px width) and Mobile (currently emulating only 360px width) . An identical list (or way) of viewport widths that Inspectors in Chrome and Firefox are emulating would be great. Or just a slider (or numerical input) to choose a custom width within the breakpoints range (eg any width between 360 & 768 for phones, any width between 768 and 1024 for tablets) 

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Hi @monographix - it will be part of the work on "additional breakpoints" project. Therefore- I'm merging the issue. 

---------
Merged issue

I merged this issue with  #2043, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
