### ISSUE TITLE
Tabs widget active tab title color mobile bug

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#13188]
The active tab title color does not apply on mobile.

That's because this [selector](https://github.com/elementor/elementor/blob/master/includes/widgets/tabs.php#L269) is only targeting `<a>` tags inside the currently active tab when in mobile the tab title is outputted inside the [`<div>`](https://github.com/elementor/elementor/blob/master/includes/widgets/tabs.php#L382) element directly.

Possible Solutions:
- Add another selector that targets the mobile element properly:
`'(mobile){{WRAPPER}} .elementor-tab-mobile-title.elementor-active' => 'color: {{VALUE}};'`
- Output the mobile tab title inside an `<a>` alement as in [desktop/tablet](https://github.com/elementor/elementor/blob/master/includes/widgets/tabs.php#L354)

**Comment by DorShahar** [comment]
Hi,
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
