### ISSUE TITLE
Add Responsive Options To Column Text Align

### ISSUE THREAD

**Issue by rtpHarry** [elementor/elementor#13199]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

The issue was raised in #7801 but closed for not following this templated reporting format.

- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This is missing the responsive options for text alignment:

1. Add a column widget
1. Go to style tab
1. Under Typography
1. Text Align option

It's here in this panel of the Column widget:

![image](https://user-images.githubusercontent.com/1038062/100551575-79279180-3279-11eb-99f5-ff1f6c6c5d4d.png)

**Describe the solution you'd like**
It should be a responsive control so that the text alignment can be set per media query breakpoint.

It has been applied in other widgets such as the Header widget:

![image](https://user-images.githubusercontent.com/1038062/100551571-6ad97580-3279-11eb-8a79-cc447cf286a6.png)

**Describe alternatives you've considered**
There are alternative options for many widgets, but not all. 

For example the Nav Menu widget doesn't support styling the text responsively so it requires being set on the next level up - the Column container.

**Comment by MichaelDarko** [comment]
+1 The styling options across the board should be more unified. Right now, they often seem quite random.

**Comment by black-eye** [comment]
+1

**Comment by fuzenco** [comment]
Please make this happen. Webflow makes tweaking responsive websites so easy.

**Comment by bkjproductions** [comment]
I think all widgets that have settings should have a responsive option, I wonder if there is a plugin that would do this across the board?  The Posts Widget could certainly use something like this:

![posts-widget--missing-responsive-controls](https://user-images.githubusercontent.com/4551281/108891718-0c543700-75dd-11eb-9de0-e30b61d657d9.jpg)

**Comment by rtpHarry** [comment]
Yeah I agree. I was fresh to Elementor when I submitted this and thought I had found a rare case. However, it appears to be everywhere, and responsive is only a half implemented feature. 

It seems strange because, as far as I can tell, all that's required is changing the one function call to use the responsive version instead.

**Comment by bkjproductions** [comment]
@rtpHarry "changing one function" --- do you mean it might be possible to do a plugin that would add in the responsive option for everything?  Would be interested in learning more about that. I guess if everything is written in PHP classes then it would be something that could be easy to extend (or maybe adding these things is a planned upgrade later).

In general, the interface for Elementor's widget control is decent enough, certainly better than some of the other pagebuilders out there.

**Comment by rami-elementor** [comment]
This issue is resolved and merged to Elementor 3.8
