### ISSUE TITLE
Background Dynamic Tag in Section not Displaying Featured Image for Templates

### ISSUE THREAD

**Issue by eSilverStrike** [elementor/elementor#13197]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
1) Add a feature image to a template
2) Edit the template in Elementor
3) Add a section and set the background of that section using dynamic tags to Post "Featured Image"
4) Nothing happens. The background Image for the section will not load in (like it does for regular Posts and Pages)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Using latest version of Elementor Pro and Wordpress
</details>

**Comment by Aviad-Herman** [comment]
Hi @eSilverStrike ,
The reason for this is that empty sections do not show up in your live site.
It shouldn't happen if the section has any widgets in it (for example, the spacer widget).
You can also set the section margin values (Edit --> Advanced) to force it to appear.

I'm going to close the issue but don't hesitate to reopen it or just continue the conversation if you run into any trouble.

**Comment by eSilverStrike** [comment]
It doesn't seem to work on my end. Have you tested it on yours?

My section in my Archive Custom Post Type template does have a Header Widget in it with a large margin for the top. I also have a minimum height set for the section of 300px. 

I set a featured image for the template. I then load up the template in Elementor and set the background of the section to Featured Image. It doesn't pull it in dynamically (it is just blank) but the Background Overlay (it is a gradient that goes transparent to a blue color) is displayed. If I just pick an image for the background it works fine but it doesn't when I tell it to use the featured image instead (by using the Dynamic Tags option).

**Comment by Aviad-Herman** [comment]
I think I understand.
So actually there is no way to reference the featured image of a template. What it does is pull the featured image of the current post the site visitor is viewing (In case of an archive it pulls the featured image of the first post in the archive).

This is intentional, in fact maybe we should have removed the ability to assign a featured image to templates in the first place...

Can you implement your design without assigning a featured image to your template? For example instead of using a dynamic tag just directly choose the image you want to display?

**Comment by eSilverStrike** [comment]
Yeah if the setting doesn't work then it shouldn't be there :-)

I could do that and probably will end up doing it that way. 

I was originally doing this so I could pick the size of the image I wanted like you can in other widgests so it wouldn't use just the Full Image size. You can see the issue here: https://github.com/elementor/elementor/issues/6778#issuecomment-735422285

**Comment by Aviad-Herman** [comment]
I totally agree. I think it's a default WordPress option and we just forgot to remove it for templates :/
I hope that choosing an image from the media library instead of using a dynamic tag works out for you.

Let me know if you need anything else.

**Comment by eSilverStrike** [comment]
Yup it works. Thanks for the quick responses.

BTW Could you look at issue: https://github.com/elementor/elementor/issues/6778 about adding the ability for Background image size selection and give the issue an official update. It's not good from a page loading standpoint to use the full image size for a background if something much smaller will do and ideally we should be able to pick from the other image sizes that Wordpress already creates for the image when we upload it (instead of manually adding the same image again to Wordpress but at a smaller size). The Posts widget already does this and it makes sense to add this functionality to backgrounds.

**Comment by Aviad-Herman** [comment]
You are absolutely correct.
Thanks for sharing.
