### ISSUE TITLE
Disappearing global font and colour settings

### ISSUE THREAD

**Issue by DavidGMiles** [elementor/elementor#13208]
For about the fourth time in a fortnight, all my global font and colour settings have disappeared - regenerating CSS does nothing - anyone else have this issue and knows how to fix it, I am almost at the end of my tether with Elementor, I've repaired this too much already, it's one step forward and two steps back with the product lately

**Comment by markedwardsims** [comment]
We're having the same issues. Checkout https://github.com/elementor/elementor/issues/12363 which seems to be a more active thread about this.

**Comment by DorShahar** [comment]
Hi, 
As @shilo-ey mentioned in #12363 - please reach out to our support team.

--------
Hey all,
For those of you who still experiencing some issues with colors and fonts that disappear- please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me (shilo-ey) and reference this issue.

Thanks

**Comment by ben-geee** [comment]
+1
