### ISSUE TITLE
Open Slideshow with a button

### ISSUE THREAD

**Issue by stefanomonteiro** [elementor/elementor#13203]
I am using Elementor's Basic Gallery widget which opens a Lightbox slideshow when an image is clicked.

How can I open the Lightbox slideshow when a button (Gallery) is clicked instead?

**Comment by rtpHarry** [comment]
If you have [Unlimited Elements](https://unlimited-elements.com/) then I have posted a custom widget that I've developed using it, which is described here:

  - https://github.com/elementor/elementor/issues/13824#issuecomment-774539887

**Comment by shilo-ey** [comment]
Hi,

I merged this issue with #8054, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
