### ISSUE TITLE
Social Icons widget offset to the right on Safari browsers

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#13206]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

On safari, the icons in the social media icons widget are all shifted over to the right. Even on a blank theme with no other plugins installed but Elementor. Works fine in Chrome. Temporary fix seems to adjust it back when setting columns to the amount of icons and away from "auto". 

## Steps to reproduce

Ad social media icons widget to site, view on safari to see shifted element to the right. Super frustrating when being used in menus or centered footers. Makes the site look amateur and unprofessional. 

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @portrayaloflife - we are aware of this bug and it will be fixed soon.
You can track #13122 

Thanks
