### ISSUE TITLE
elementor pro with measurament price calculator

### ISSUE THREAD

**Issue by bitteri57** [elementor/elementor#13209]
hi i have a problem with elementor pro and sky verge measurament price calculator plugin.
Specifically, if I create a product page template where the plugin is used to calculate the price, the calculator does not work, that is, on the display you see all the functions except the calculation with the final price. If you go to the cart, the product is managed with the right price, so the calculator works but does not appear on the display on the product page. I have already opened a ticket in elementor with no response. can you help me? thanks.

**Comment by Aviad-Herman** [comment]
Hey @bitteri57 ,
Unfortunately the GitHub is intended for feature requests and bug reports only.

Did you open a support ticket through this link?
https://my.elementor.com/support/  

I'm guessing support will need your site's credentials. we shouldn't share these things on GitHub where you can't be sure of people identity.

You can also try posting in the Elementor community FaceBook page.

Thanks
