### ISSUE TITLE
Popups not working in Internet Explorer 10

### ISSUE THREAD

**Issue by usamaibrahim93** [elementor/elementor#13204]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

My website is using both Elementor and Elementor Pro. A couple of days ago I updated both the plugins to their latest stable versions and noticed that popups have stopped working in IE 10. Before the update, they were working fine. Obviously I won't look for them to work in any version before 10 but before the update, IE 10 was displaying popups correctly.

Right now I am using Elementor version 3.0.13 and Elementor Pro version 3.0.6 alongside WordPress 5.5.3 latest. The popups are working fine on other browsers but IE 10. IE 10 gives the following error on console:

'elementorModules' is undefined frontend.min.js (2,51407)

And sometimes this:

ReferenceError: 'DialogsManager' is undefined

## Steps to reproduce

Visit the following link on Internet Explorer 10 vs any other browser say Chrome. And then check the console:

http://demo5.folio3.com:8087/contact

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/10.0
	MySQL version: MySQL Community Server - GPL v8.0.17
	PHP Version: 7.3.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: http://demo5.folio3.com:8087
	Home URL: http://demo5.folio3.com:8087
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: AirMedcareNetwork - Website Redesign
	Version: 1.0.0
	Author: Folio3 Consumer Division
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

== Active Plugins ==
	Admin Bar & Dashboard Control
		Version: 1.2.5
		Author: Author: Collins Agbonghama (W3Guy LLC)

	Adminimize
		Version: 1.11.7
		Author: Frank Bültge

	Advanced Custom Fields
		Version: 5.8.7
		Author: Elliot Condon

	AMCN
		Version: 2.2.1
		Author: Magnetik

	AMCNB2B
		Version: 2.0.6
		Author: Noman Rizwan

	Boosted Elements
		Version: 4.0
		Author: Progression Studios

	Cronjob Scheduler
		Version: 1.40.1
		Author: chrispage1

	Custom Post Type UI
		Version: 1.8.1
		Author: WebDevStudios

	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.21
		Author: Gravity Forms

	Gravity Forms Event Tracking
		Version: 2.3.10
		Author: Ronald Huereca

	Gravity Forms Post to Third-Party API
		Version: 1.3.0
		Author: gravity+

	Manage Notification E-mails
		Version: 1.5.1
		Author: Virgial Berveling

	ProfilePress
		Version: 2.9.21
		Author: ProfilePress Team

	Redirection
		Version: 4.9.2
		Author: John Godley

	Simple History
		Version: 2.37.2
		Author: Pär Thernström

	User Role Editor Pro
		Version: 4.37
		Author: Vladimir Garagulia

	User Switching
		Version: 1.5.6
		Author: John Blackbourn & contributors

	WP Mail SMTP
		Version: 2.5.1
		Author: WPForms

	WP Term Images
		Version: 1.0.0
		Author: John James Jacoby

	Yoast SEO
		Version: 15.3
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		call-to-action : 3
		heading : 1
		image : 1
		sidebar : 1
	footer : 2
		html : 1
		image : 3
		shortcode : 1
		social-icons : 1
		template : 1
		text-editor : 2
		wp-widget-nav_menu : 1
	header : 4
		image : 2
		nav-menu : 2
		shortcode : 3
	page : 4
		button : 1
		heading : -4
		icon-list : 2
		image : 1
		text-editor : 1
	popup : 5
		button : 1
		heading : 4
		shortcode : 1
	section : 3
		call-to-action : 3
		shortcode : 2
	single : 2
		button : 5
		call-to-action : 3
		heading : 7
		image : 2
		post-info : 3
		shortcode : 2
		sidebar : 1
		text-editor : 1
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 2
	wp-post : 0
		text-editor : 1
	wp-page : 65
		boosted-elements-post-list : 1
		button : 85
		call-to-action : 57
		google_maps : 1
		heading : 385
		icon-list : 2
		image : 158
		image-box : 72
		image-carousel : 1
		image-gallery : 1
		price-table : 14
		shortcode : 128
		sidebar : 1
		slides : 24
		social-icons : 25
		spacer : 5
		testimonial : 9
		text-editor : 258
		wp-widget-nav_menu : 23

== Log ==
	
Log: showing 17 of 172020-02-10 13:21:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.5',
)]
2020-03-03 10:36:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.3',
)]
2020-03-03 10:37:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-11-23 12:48:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '3.0.13',
)]
2020-11-23 12:48:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '3.0.6',
)]
2020-11-23 13:23:17 [info] elementor::elementor_updater Started 
2020-11-23 13:23:21 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-11-23 13:23:23 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-11-23 13:23:24 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-11-23 13:23:25 [notice] System colors are disabled. nothing to do. 
2020-11-23 13:23:26 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-11-23 13:23:26 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-11-23 13:23:35 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-11-23 13:23:36 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-11-23 13:23:37 [notice] System typography is disabled. nothing to do. 
2020-11-23 13:23:38 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-11-23 13:23:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '3.0.13',
)]

JS: showing 14 of 14JS: 2020-02-27 06:01:28 [error X 1][http://demo11.folio3.com:8891/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view20206\") has already been destroyed and cannot be used. 
JS: 2020-02-27 06:03:03 [error X 10][http://demo11.folio3.com:8891/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.5:31:115928] Cannot read property \'html\' of undefined 
JS: 2020-02-27 06:05:33 [error X 27][http://demo11.folio3.com:8891/wp-admin/post.php?post=116&action=elementor:1:36] gformInitSpinner is not defined 
JS: 2020-02-27 19:53:59 [error X 1][http://demo11.folio3.com:8891/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1804\") has already been destroyed and cannot be used. 
JS: 2020-03-02 09:20:09 [error X 1][http://demo11.folio3.com:8891/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.5:31:36487] Cannot read property \'0\' of undefined 
JS: 2020-03-04 13:55:20 [error X 62][http://demo11.folio3.com:8891/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.4:2:54702] Cannot read property \'top\' of undefined 
JS: 2020-03-04 15:14:37 [error X 3][http://demo11.folio3.com:8891/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.3:2:98665] Commands internal: `document/history/delete-transaction` not found. 
JS: 2020-06-15 12:44:03 [error X 1][http://demo11.folio3.com:8891/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view104\") has already been destroyed and cannot be used. 
JS: 2020-06-28 18:21:56 [error X 1][http://demo5.folio3.com:8087/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.3:2:187542] this.target.getContainer is not a function 
JS: 2020-09-29 09:53:02 [error X 1][http://demo5.folio3.com:8087/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2652\") has already been destroyed and cannot be used. 
JS: 2020-10-22 15:33:14 [error X 1][http://demo5.folio3.com:8087/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4582\") has already been destroyed and cannot be used. 
JS: 2020-10-22 15:34:46 [error X 1][http://demo5.folio3.com:8087/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view509\") has already been destroyed and cannot be used. 
JS: 2020-10-22 16:20:11 [error X 1][http://demo5.folio3.com:8087/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5025\") has already been destroyed and cannot be used. 
JS: 2020-10-26 11:47:45 [error X 1][http://demo5.folio3.com:8087/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view542\") has already been destroyed and cannot be used. 

PHP: showing 11 of 11PHP: 2020-02-27 06:46:44 [notice X 168][D:\xampp\htdocs\AirMedCare-Network-ReDesign\wp-content\plugins\elementor\includes\libraries\bfi-thumb\bfi-thumb.php::750] A non well formed numeric value encountered [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-27 19:41:01 [warning X 1][D:\xampp\htdocs\AirMedCare-Network-ReDesign\wp-content\plugins\elementor\modules\safe-mode\module.php::107] rmdir(D:\xampp\htdocs\AirMedCare-Network-ReDesign/wp-content/mu-plugins): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-28 11:14:09 [notice X 36][C:\xampp\htdocs\amcn-redesign\wp-content\plugins\elementor-pro\modules\theme-elements\widgets\breadcrumbs.php::38] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-06 10:11:09 [notice X 72][C:\xampp\htdocs\amcn-redesign\wp-content\plugins\elementor\includes\base\controls-stack.php::1443] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-23 12:52:17 [warning X 28][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\files\assets\svg\svg-handler.php::101] file_get_contents(C:\Sites\AirMedCare-Network/wp-content/uploads/2019/10/instagram-icon.svg): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-23 13:23:52 [warning X 17][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\files\manager.php::121] unlink(C:\Sites\AirMedCare-Network/wp-content/uploads/elementor/css/post-8.css): Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-23 13:25:34 [warning X 32][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\files\base.php::180] file_put_contents(C:\Sites\AirMedCare-Network/wp-content/uploads/elementor/css/post-116.css): failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-24 07:02:43 [warning X 2][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\files\base.php::180] file_put_contents(C:\Sites\AirMedCare-Network/wp-content/uploads/elementor/css/post-6.css): failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-24 08:15:26 [warning X 2][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\files\base.php::180] file_put_contents(C:\Sites\AirMedCare-Network/wp-content/uploads/elementor/css/post-8.css): failed to open stream: Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-24 14:22:01 [warning X 13][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\files\base.php::189] unlink(C:\Sites\AirMedCare-Network/wp-content/uploads/elementor/css/post-116.css): Permission denied [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-24 17:06:26 [notice X 1][C:\Sites\AirMedCare-Network\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by DorShahar** [comment]
Hi @usamaibrahim93 
[We are officially not supporting IE. ](https://developers.elementor.com/elementor-dropping-support-ie/)

All the best.

**Comment by usamaibrahim93** [comment]
That's sad :(
