### ISSUE TITLE
Add wiget single attribute 

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13202]
Add a Single attribute widget for the ability to display and customize the attribute table, please don't tell me that there is a product tabs widget, it looks terrible, moreover, using the tab widget, I want to customize my template with tabs wherever in the first there is a description of the product, in the second there are attributes + some text, and in the third or even even the fourth I would indicate the terms of delivery and return, the guarantee in general here is only limited by imagination.
Why is this necessary?
This allows you to make a more extended product card, saving space. Product tabs are very theme-dependent, I'm using your theme and it has a terrible display of these tabs, other themes are not as easy as yours. Also, such a conclusion of the hotel allows you to create a detailed design of the product page

Who has such a solution?
The crockoblock in the jet woo plugin, the problem is that their solution is not optimized like yours and it takes longer to load, and it is not displayed quite as it should, and in general, it is impossible to make custom settings for tabs in it, they just have this widget, many have the problem with the output of attributes, I pushed through the snippet, I could not

**Comment by Aviad-Herman** [comment]
Hey,
You are correct, current functionality is pretty limited.
I'm merging this with issue #4440 It's more general (not just Woo) but same concept.

Thanks for your feedback.

**Comment by RazvanFarte** [comment]
Also check my comment [here](https://github.com/elementor/elementor/issues/4885#issuecomment-752848696)
