### ISSUE TITLE
Feature Request: Add icon size option for toggle and accordion elements

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#13212]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Icons in toggle and accordion elements are static. There are no options to manage their size. 

**Describe the solution you'd like**
Add icon size option for toggle and accordion elements >>> (+)(-) etc

**Describe alternatives you've considered**
Custom CSS

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by portrayaloflife** [comment]
@DorShahar I don't think those tickets are the same. I'm talking specifically about giving a size option for the icons themselves in the toggle. The + or - to open or close the toggle. You can't edit the icon size without custom css and so they remain very small.

**Comment by DorShahar** [comment]
Hi @portrayaloflife - we are working on a global solution that will allow you to do way more than that. 
This solution makes the layout more flexible, and it will answer your demand as well.

I cannot share more details because this is at an early stage. 

Thanks

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the feature you requested was introduced with the new Nested Accordion widget which was released with Elementor v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
