### ISSUE TITLE
Replace URL Interface Upgrade

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#13214]
Will it be possible to stack the input fields for the Replace URL interface in a future release?
It's easy to make a mistake if the domain URLs are long with the existing field length.

Below is an example of how it could look if the fields are stacked.

![Elementor-Replace-Tool-Upgrade](https://user-images.githubusercontent.com/7768009/100801730-625a7980-33f6-11eb-8dbf-b931bb5c422f.jpg)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
