### ISSUE TITLE
Fatal error: Uncaught RangeException: Max value for this device is out of range. 

### ISSUE THREAD

**Issue by hermanfan** [elementor/elementor#13213]
Hello everyone. This error arises when adding an incorrect value in the breakpoint for tables and cell phones of the hamburger menu, making the elementor editor and the page unusable.

All plugins were deactivated and Elementor was even reinstalled and the same error continues to appear.

Opening the debug mode returns the following info:

Fatal error: Uncaught RangeException: Max value for this device is out of range. in /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/includes/stylesheet.php:300 Stack trace: #0 /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/includes/stylesheet.php(354): Elementor\Stylesheet->get_device_max_value() #1 /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/includes/stylesheet.php(385): Elementor\Stylesheet->hash_to_query() #2 [internal function]: Elementor\Stylesheet->Elementor\{closure}() #3 /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/includes/stylesheet.php(412): uksort() #4 /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/includes/stylesheet.php(149): Elementor\Stylesheet->add_query_hash() #5 /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/core/files/css/base.php(41 in /mnt/web518/e1/05/59623705/htdocs/STRATO-apps/wordpress_01/app/wp-content/plugins/elementor/includes/stylesheet.php on line 300

Line 300 on stylesheet.php

if ( $next_index >= count( $devices_names ) ) {
			throw new \RangeException( 'Max value for this device is out of range.' );
		}

Any solution? Thank you!

**Comment by DorShahar** [comment]
Hi @hermanfan 
For you to continue your work on the site, Go to the WP Dashboard > Elementor > Templates > All, and then delete `Default Kit`
