### ISSUE TITLE
Add options for text (Paragraph spacing)

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13226]
Now there are settings only text size, line height, style, decoration, transform letter spacing, but not have paragraph spacing. And this option will allow you to create beautiful text for a blog or other sections where there is a lot of text divided into paragraphs. In addition, if separating the text by hyphenation is 1) wrong, and as I know (but this is not accurate) it saves unnecessary code.

Where is it? 
We all know the figma editor, so they have it in the text settings, the elementor is almost perfect for transferring a design from the figma editor, but there are no completely options settings

**Comment by promocot** [comment]
![12223444](https://user-images.githubusercontent.com/66754335/101278298-1bd49880-37c3-11eb-9794-1c2bedf68b54.jpg)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2396, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
