### ISSUE TITLE
Colored section + label

### ISSUE THREAD

**Issue by GringoWhoowhere** [elementor/elementor#13229]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I often like to run timed changes on some website homepages for events, such as Christmas, halloween, etc, and often will make a few general changes so using revisions is sometimes not the best option, but I would like it if we could change section colors to determine something, could be anything, for me I'd like to set a section color to red so I know that it's a section that I'll remove when it comes time to remove the event theme. Could have different section colors to show different items, such as something to come back to later on, etc. 

**Describe the solution you'd like**
Right Click > Set Color

**Describe alternatives you've considered**
//

**Additional context**
https://i.imgur.com/ASimWAB.jpg

**Comment by Aviad-Herman** [comment]
Hey @GringoWhoowhere,
Thanks for the feature request!
It's a great idea but to tell you the truth it will cause us some trouble. We currently use colors to differentiate regular sections from Header and Footer templates (in Elementor Pro) and we might implement more in the future.

I really appreciate your feedback, keep the good ideas coming!

In the meantime may I suggest the following?
Duplicate the pages / posts you want to customize and use a redirect for the duration of the event? You can use a plugin like [redirection](https://wordpress.org/plugins/redirection/). It might save you the hassle of adding and deleting content and maybe forgetting how the original looked like etc.
