### ISSUE TITLE
Double images in product list and wrong preview

### ISSUE THREAD

**Issue by Danianez** [elementor/elementor#13224]
My website is presenting a problem in the display of products that contain more than one image in the product gallery.

The problem is that two photos are displayed in the image preview and when you hover over the image it changes to white, on the edit page of the products grid module it is displayed correctly but when saving the change and reviewing in live preview it doesn't work correctly.

I leave a demonstration video so that you can visualize the problem and can help me correct this problem.
[Elementor.zip](https://github.com/elementor/elementor/files/5636883/Elementor.zip)

Greetings and thanks to the developer community.

**Comment by DorShahar** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests.
GitHub issues are not for support.

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by daniel-stevens** [comment]
Hi @Danianez, did you manage to find a fix to this? I am currently experiencing the same issue. Thank you
