### ISSUE TITLE
URL as source for images

### ISSUE THREAD

**Issue by shirokoweb** [elementor/elementor#13225]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Only images from Library can be added from builder for Background (Style setting)

**Describe the solution you'd like**
Use an URL as source for images

For now the only way is to add a custom CSS like this :

> selector{
>     background: url(https://images.unsplash.com/photo-1551522435-a13afa10f103?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80) no-repeat center center scroll;
>     -webkit-background-size: cover;
>     -moz-background-size: cover;
>     -o-background-size: cover;
>     background-size: cover;
> }

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #413, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
