### ISSUE TITLE
Elementor slider 

### ISSUE THREAD

**Issue by wodo87** [elementor/elementor#13237]
Hello, I have a problem on my website https://mag-jew.pl/ I have a slider added, everything works and it's ok. But for some time, when I updated the page, after entering edit, I can't see it at all, I can't change or edit it anywhere. I would like to delete it completely and add a new one, how to do it ?? I will just add that I used the pro version before, now I have free and the pro is still installed, only not active

**Comment by DorShahar** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests.
GitHub issues are not for support!

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

thanks.
