### ISSUE TITLE
New feature for global settings

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13238]
Please add

1) Settings for shadow
2) Export global settings

For what?
1) If i want to use shadow on site, for comfortable and fast design i can activate shadow and get one type shadow
2) For creators who can often repeat most of the settings (for example, font sizes and other settings, and a partial modification is required, saves more time to create than to create everything again.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4417, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
