### ISSUE TITLE
Freezing screen Elementor Pro in combination with JetThemeCore

### ISSUE THREAD

**Issue by LeonS3** [elementor/elementor#13230]
The Elementor support team refered me to this website. The problem is Elementor Pro in combination with JetThemeCore is giving problems, when one of these plugins deactivated there is no problem. The issue is that every Elementor editing page is freezing and I cannot preform or save any task.
Please support.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Isolating the problem.
* System info.

Without it, we simply can't help.
Please understand the although you talked to our support, it is difficult to track your ticket and therefore I am asking for more infornation

Thanks.
