### ISSUE TITLE
Pause Feature for Individual Slides in Slides Widget

### ISSUE THREAD

**Issue by Mij-Strebor** [elementor/elementor#13235]
**What problem is your feature request going to solve? Please describe.**

Slides widget on autoplay may not start on slide one.

**A clear and concise description of what the problem is.** 

When a user moves to a page with a carousel (Slides widget) or moves to a section of a page with a Slide, the will arrive when some of the individual slides have changed with a Slider on autoplay.  This is a problem if the slides "tell a story" and should be viewed first to last.

**Describe the solution you'd like**

Best, I think, would be a Style setting on the individual slides "Initial delay" that would add time to the Slider autoplay for that one slide.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Aviad-Herman** [comment]
Hi @Mij-Strebor ,
Thanks for your input, we really appreciate it.
You're correct, it would be better to only initiate autoplay once the slides widget is visible on the screen.
Unfortunately we currently don't have such an option. To be honest we don't have plans to implement this in near future.

I'm sorry for the inconvenience and I hope you find some sort of hack, perhaps using custom Javascript in an HTML widget.

In any case I hope you will keep sharing your great ideas with us.

Aviad
