### ISSUE TITLE
Url Links with Elementor Pro Gallery

### ISSUE THREAD

**Issue by turski123** [elementor/elementor#13242]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by turski123** [comment]
Love using Elementor Pro.... But seriously guys... when are you going to provide the ability to have a different URL link to each image in your gallery widget..
Virtually all 3rd party gallery plugins can do this... can you please explain why even after so many requests, you have not done this? (unless I have missed something recently)
It would make life so much easier if you can include this but it seems you are just not willing or able to?

**Comment by DorShahar** [comment]
Hi @turski123 
Thank you for your input, I'm happy to hear that you are enjoying our product! 

The Product and Devs teams are dealing with other projects at the moment (strategic capabilities, safer release, community developer involvement, and more).

As there are many requests, we will try to reach and develop that (important) capability as well. 

I'm merging this issue with #413  for easy tracking.
