### ISSUE TITLE
401 Server Errors all the time

### ISSUE THREAD

**Issue by llafata** [elementor/elementor#13258]
Please fix the elementor editor update issues. Using jupiter X with Elementor Pro. Always getting 401 and other server errors when attempting to update a page with the elementor editor.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
