### ISSUE TITLE
Compoundable widget AKA custom widget made of ... widget

### ISSUE THREAD

**Issue by SuperstrongBE** [elementor/elementor#13254]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I came with this idea while using tabs with content. I was using section shortcode to populate the tabs. But create 4 differents sections/shorcode with the same layout and just changing the content was redundant... 
As I'm a freelance,i usually create a website for my own customer, and then deliver the product. So my customer is able to create and edit content as he want. And often my customer ask me to create advanced content because he have not enougth skills to do it, so:
What if we can create new widget ... made of basic widget ? 

**Describe the solution you'd like**
As far as i know, "widgets are just shortcode". So adding dynamic args in shortcode should be easy... 
```[elementor-template id="869"]``` is bound to a section made of components. 
But a more dynamic approach could be 
```[elementor-template id="869" my-custom-title='Hello world' my-custom-btn-label='Click here'  my-custom-link='https://google.com']```

The binding key (eg:my-custom-link) could be located in the content "Dynamic tag" section, which made it easy to use and keep things aligned with the elementor logic.

These newly create custom widget could be inside a new widget group, and their keys could be displayed in the new section of the advanced tab. 

With this approach, we speed up the creation process, allow more creativity/productivity, and deliver better, ready to use, back-office experiences for our customers. And last but not least, reduce the footprint and time spend on the translation process... 

**Describe alternatives you've considered**
- ACF (not working)
- Home made implementation

**Comment by Aviad-Herman** [comment]
Hi @SuperstrongBE ,
This is a great idea and I'm glad you reached out.
Depending how much time you want to invest in this there are several options:

**Global Widgets**
This is an Elementor Pro feature that allows you to reuse the same widget configuration in different locations on the site.

**Templates**
Another Pro feature which is similar to Global Widgets only it allows you to insert entire sections that might include several widgets. You can insert template you created using the "Template" widget.

**Develop your own widget**
Elementor is open source and we have created a set of APIs that allow you to extend Elementor any way you like. Check out our [Developer Documentation](https://developers.elementor.com). WordPress has many plugins that extend Elementor, take a look at [Essential Addons](https://essential-addons.com/elementor/) for inspiration.

In the future we might be looking into a simple way to allow the creation of personal widgets. Some sort of "Widget builder" but that is very far into the future.

Was this what you meant?

I'm going to close this issue but please feel free to tag me and continue the conversation. Keep the good ideas coming :)

**Comment by SuperstrongBE** [comment]
Hi @Aviad-Herman Thank for reply.

My though is uses cases are biased by the idea of a guy that makes a single website on his own with elementor. But as a dev, i provide to my customer an (almost) finished product based on elementor a let them edit/create their content. The main issue with sites builder is to reduce the "cognitive charge" for my customer.

**Global Widgets**
This feature does not cover the same purpose, because it's just store/paste an existing set of shortcode. This is not dynamic

**Templates**
Same as above, not really dynamic. I use template extensively, to keep everything DRY while the integration phase. 

**Develop your own widget**
This is the option I'm considering. And I understand that this kind of feature could kill the "addons business model game".
But as I dig a lot on the [doc](https://code.elementor.com/) lately, I'm feeling a bit frustrated by not really understanding how classes are structured and how lifecycle is working in elementor.

**Widget builder**
Yes, this is the name: Widget builder ! 

I love elementor, and i really want to elevate the debate by proposing new ideas. I'm have a new deal with a digital company here in Belgium and i provide them full stack service with advanced frontend (ThreeJS, PixiJS, AJAX, ..) and i'm 90% time use wordpress as CMS. So i'm looking to push boundaries and use Elementor to allow my customers to have the same editing experience.

**Comment by Aviad-Herman** [comment]
I love your way of thought.
It will be a long time until we can achieve this vision so unfortunately don't expect it anytime soon.

I would really appreciate if you would agree to a 45 minute video chat just to talk about how you use Elementor and the workflow you have with your customers. It won't help you but it would definitely help me 😂.

Could you spare some time for me? If yes - let's continue this conversation over email: aviadh@elementor.com

Thanks
