### ISSUE TITLE
"Edit with Elementor" sub menu item in admin bar not showing on WordPress 5.6

### ISSUE THREAD

**Issue by namncn** [elementor/elementor#13256]
When I update WordPress to verion 5.6, all sub menu items of "Edit with Elementor" button in adminbar don't show. Everything lost, just show "Edit with Elementor" button.

**Comment by koddajr** [comment]
yep, i confirm this... isnt work for me either

**Comment by salsa-system** [comment]
same issue for me...

**Comment by Aviad-Herman** [comment]
Thanks for the input guys!
@Nevoss just opened a PR (#13266) to fix it.
It still has to go through code review etc. but it should solve the issue once it's out.

**Comment by get8bit** [comment]
Having same issue. Just started today after updating WordPress. The "Edit with Elementor" drop down does not show the list of templates used on each page.

I disabled ALL plugins, except elementor and elementor pro. I have checked with other users on other hosts and they are having same issue.

![Screen Shot 2020-12-09 at 1 41 04 PM](https://user-images.githubusercontent.com/36855453/101687429-7aef1300-3a38-11eb-902a-88f094a9dc37.png)

**Comment by borayeris** [comment]
With every update something is broken.

**Comment by portrayaloflife** [comment]
yeah all the updates lately have been awful

**Comment by Aviad-Herman** [comment]
I agree. We are taking efforts to minimize this, like implementing automated testing but in the meanwhile, we really appreciate your help here on GitHub. Thanks for your help and support.

**Comment by nickdesignz** [comment]
Noticed the same issue. But was able to identify a little bit better.
I updated Wordpress to version 5.6 but **not my Elementor** Plugin which was still version **3.0.12**, everything **worked well** including the Dropdown. After updating Elementor 3.0.12 to version 3.0.14 I lost my dropdown list in my Menu.

Maybe it helps 👍

**Comment by brmuse** [comment]
Same problem on my two Elementor sites (one on SiteGround, the other on my dedicated server). I had also upgraded both Elementor standard and pro plug-ins before WP 5.6 and the "Edit with Elementor" drop would not work, so I added bookmarks to the home page and post page edit URLs in my browser toolbar for the time being with hopes a later update will fix it.

I haven't found any other problems with Elementor but have my fingers crossed.

**Comment by Simpa77** [comment]
Having same issue. Using Hello-theme with Wordpress version 5.6 and Elementor 3.0.14 and Elementor Pro 3.0.8. Note! I also have a site were Im using the latest build of the development version of WordPress and I don´t  have the same issue on that site.

**Comment by Simpa77** [comment]
Sorry, I just realized that the autoupdate on my test site had failed and I had an old beta version. Now after updating to 5.6.1-alpha-49778 I have the same problem on my test site.

**Comment by renzoesposito** [comment]
Same issue for me. Using Hello-theme with WordPress version 5.6 and Elementor 3.0.14 and Elementor Pro 3.0.8

**Comment by perks98** [comment]
+1

**Comment by arkadygold** [comment]
FOLLOWING +1

**Comment by flippeters** [comment]
Ditto. Hello-Elementor. Latest Elementor & Pro.

**Comment by Phukit** [comment]
+1 

waiting for fix please

**Comment by brmuse** [comment]
Got thing working (on a temp basis) by using WP's Enable jQuery Migrate Helper plug-in. The problem seems to be centered on the  jQuery update in 5.6. Wordpress says it should only be used as a temp fix until patches solve the problem. My "Edit with Elementor" is working as a band-aid  solution until the updates are updated. 
https://wordpress.org/plugins/enable-jquery-migrate-helper/

**Comment by shilo-ey** [comment]
We are currently working on a fix.

This issue origins from the upgrade of jQuery version build in WP 5.6

To avoid this issue for the meanwhile please use the following plugin:
https://wordpress.org/plugins/enable-jquery-migrate-helper/

A patch will release in the upcoming days.

Thanks

**Comment by get8bit** [comment]
@shilo-ey I've added the Jquery Migrate Helper, but still elementor sub menus are not appearing. I'm on WordPress 5.6, Hello Theme 2.3.0, and Elementor and Pro are up-to-date. The Migrate Helper is showing no logged depreciations. Please release patch asap. I need to hand off to client and show them how to use Elementor. Hard to do without sub menus.

![Screen Shot 2020-12-13 at 1 34 39 PM](https://user-images.githubusercontent.com/36855453/102020565-feb24380-3d47-11eb-917c-69b8d02c6224.png)

**Comment by nickdesignz** [comment]
> @get8bit  I need to hand off to client and show them how to use Elementor. Hard to do without sub menus.

If you step back a version (or zwo) with Elementor, you‘ll be fine.

**Comment by RonR-WebDesign** [comment]
Same +1

Plugin:  Enable jQuery Migrate Helper   did  not fix the problem.

**Comment by koddajr** [comment]
jQuery Migrate fix the problem for now, to make work go to:

on front end admin bar
![11](https://user-images.githubusercontent.com/53986027/102040933-e6c0db00-3dac-11eb-9a79-8c6e18ae644c.png)

change to legacy and click save
![2](https://user-images.githubusercontent.com/53986027/102040968-f809e780-3dac-11eb-8221-cd07932b10f4.png)

after that submenu will work again
![3](https://user-images.githubusercontent.com/53986027/102040991-09eb8a80-3dad-11eb-98e6-04782bed5a0f.png)

**Comment by RonR-WebDesign** [comment]
Sorry koddajr, that didn't work for me.   I have a very stripped down dev site with only latest Elementor and WP core.

**Comment by get8bit** [comment]
@koddajr That worked for my sites. Thank you! Still hope they get the patch done soon.
<img width="503" alt="Screen Shot 2020-12-14 at 12 02 52 PM" src="https://user-images.githubusercontent.com/36855453/102111497-79409900-3e04-11eb-8f08-861fa59d7c6a.png">

**Comment by RonR-WebDesign** [comment]
This works for me...  add to your site CSS:

`#wp-admin-bar-elementor_edit_page:hover > div {
	display: block !important;
}`

**Comment by get8bit** [comment]
@RonR-WebDesign That's even better! Worked like a charm, and not my clients don't have to see giant Jquery warning messages. Thank you!

**Comment by davidamarek** [comment]
+1

**Comment by dipakparmar** [comment]
Same for us not showing the edit templates used on that page!

![image](https://user-images.githubusercontent.com/24366206/102274365-9e064080-3ed8-11eb-93c9-67aba458d860.png)

**Comment by davidamarek** [comment]
Found the solution for me and may help some people - my administrator account has a secondary role assigned to it that does not include Elementor permission. Apparently that was overriding the Administrator permission.

**Comment by timaxsos** [comment]
> This works for me... add to your site CSS:
> 
> `#wp-admin-bar-elementor_edit_page:hover > div { display: block !important; }`
> 
> No need for jQuery fix...

yes, it works very well, thank you

**Comment by arkadygold** [comment]
> > This works for me... add to your site CSS:
> > `#wp-admin-bar-elementor_edit_page:hover > div { display: block !important; }`
> > No need for jQuery fix...
> 
> yes, it works very well, thank you

I copied it to my theme css and it didnt work

**Comment by RonR-WebDesign** [comment]
arkadygold - You may need a cache purge.

I added it to Customize > Additional CSS and it worked.

**Comment by timaxsos** [comment]
> > > This works for me... add to your site CSS:
> > > `#wp-admin-bar-elementor_edit_page:hover > div { display: block !important; }`
> > > No need for jQuery fix...
> > 
> > 
> > yes, it works very well, thank you
> 
> I copied it to my theme css and it didnt work

Refresh/Update your css

**Comment by Florian-GM** [comment]
> This works for me... add to your site CSS:
> 
> `#wp-admin-bar-elementor_edit_page:hover > div { display: block !important; }`
> 
> No need for jQuery fix...

It works !

Thanks a lot !

**Comment by nickdesignz** [comment]
> arkadygold - You may need a cache purge.
> 
> I added it to Customize > Additional CSS and it worked.

only this version worked for me!

Thanks mate

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.15

Feel free to update

Thanks!

**Comment by nickdesignz** [comment]
> This issue has been resolved in Elementor v3.0.15
> 
> Feel free to update
> 
> Thanks!

Still there, sorry. It only works with the CSS code above.

**Comment by Phukit** [comment]
works here.  

try clearing cache.
