### ISSUE TITLE
HUGE ISSUE: Elementor has intergration issue with latest WordPress 5.6 update!

### ISSUE THREAD

**Issue by shay1383** [elementor/elementor#13267]
Elementor design, mainly in 'Theme Builder' based websites, gets broken and doesn't function correctly.

כאשר מעדכנים את גרסת הוורדפרס מ5.5.3 ל-5.6 עיצוב שנבנה בבונה תבנית של אלמנטור לעיתים נשבר והסאב-מניו שבאדמין מניו של וורדפרס לא נפתח כלל ואינו מציג "ערוך header, או ערוך footer, כבדרך כלל (https://prnt.sc/vz2m3k).

**Comment by mcrowell** [comment]
+1. I'm experiencing the same issue. When you hover the "Edit with Elementor" button there's no dropdown to select the theme page elements.

WordPress 5.6
Elementor v3.0.14
Elementor Pro v3.0.8

**Comment by shilo-ey** [comment]
I merged this issue with #13256, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
