### ISSUE TITLE
Layout overflow while using "Stretch section"

### ISSUE THREAD

**Issue by SecondLineThemes** [elementor/elementor#13260]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using the new default TwentyTwentyOne theme on a fresh install, the layout width overflows.
Browser width 1263px. Chrome/FF.

## Steps to reproduce
Fresh WP install, TwentyTwentyOne theme, Elementor (free).
Example - https://elementor-test.mystagingwebsite.com/elmntr/

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (without Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @SecondLineThemes 

Can you please share what's the overflow here?

I can see it without overflow in your provided example:
![Uploading image.png…]()

**Comment by SecondLineThemes** [comment]
There's a horizontal scroll bar as soon as the stretched section is added, maybe that's not visible in the emulator?
I guess the problem is that the HTML doc is 1263px wide, but the Elementor section's width is wider at 1280px.
Seems like this happens on other sizes as well, and on multiple browsers/machines.

**Comment by mcrowell** [comment]
+1. I noticed this same bug with Wordpress 5.6. When you scale down the browser to mobile size you will see the browser horizontal scroll bar on sections with the "Stretch section" active.

**Comment by peterlombardi** [comment]
Likewise, having the same issue on a clients site with stretched sections. On chrome/firefox/safari (mac) it's persistent. 

<img width="1628" alt="Screen Shot 2020-12-09 at 2 55 03 PM" src="https://user-images.githubusercontent.com/19938097/101698594-9ead5b80-3a2e-11eb-8790-302054b1db41.png">

**Comment by JamboMedia** [comment]
Yes, we got the same issue. With strechted sections the with is not good anymore.

Please fix this asap!

**Comment by Merlin1987** [comment]
+1

**Comment by Merlin1987** [comment]
I can reproduce it when i create a new empty page and put a stretched block in it. when the height is larger than the screen the scrollbar on the right site shows up and in the same moment the scrollbar on the bottom.

<img width="1920" alt="Bildschirmfoto 2020-12-10 um 16 22 47 (2)" src="https://user-images.githubusercontent.com/41824265/101791804-3e88e900-3b04-11eb-8e48-87a001cc493e.png">

**Comment by thithi242** [comment]
JQuery 3.5.1 is causing the problem.
More information here : https://wordpress.org/support/topic/stretch-section-bug-jquery/

**Comment by Khaleddev20** [comment]
I am facing the same issue. Do you get any solution..?

**Comment by shilo-ey** [comment]
It seems to reproduce when "Show Scroll Bars" option is set to "Always"

We will review it and update as soon as possible.

**Comment by thomasfaboux** [comment]
Same issue. A tip, don't fix everything (waiting for better):

body {overflow-x: hidden;}

**Comment by shilo-ey** [comment]
We are currently working on a fix.

This issue origins from the upgrade of jQuery version build in WP 5.6

To avoid this issue for the meanwhile please use the following plugin:
https://wordpress.org/plugins/enable-jquery-migrate-helper/

A patch will release in the upcoming days.

Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0.15

Feel free to update

Thanks!
