### ISSUE TITLE
Can't access swiper js instance since Wordpress 5.6

### ISSUE THREAD

**Issue by astbarc** [elementor/elementor#13268]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

Since wordpress version 5.6, I can't access swiper js instance as describe in this article:
https://developers.elementor.com/expose-swiper-in-elementor/

The reference is equal to undefined. 

I can confirm that with a previous version of JQuery this works.

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

**Comment by udidol** [comment]
Hi @astbarc,
Which Swiper instance are you trying to access? I just tested it with the Image Carousel widget and successfully accessed the instance:
![image](https://user-images.githubusercontent.com/36724484/101733764-019f0100-3ac8-11eb-8bec-49cbcd675063.png)

**Comment by astbarc** [comment]
Hi @udidol,

Many thanks for the help. I've been able to fix. The problem was in the code I was using not in elementor.

Sorry for the inconvenience.

**Comment by nicmare** [comment]
this does not work for me. "swiper" is always returning "undefined"
`const carousel = jQuery( '.elementor-image-carousel-wrapper' );
            const swiper = carousel.data( 'swiper' );
            console.log(swiper);`

**Comment by nicmare** [comment]
i even tried to wrap it into elementor events. no success:
```$( window ).on( 'elementor/frontend/init', function() { //wait for elementor to load
                
                if(elementorFrontend){
                    elementorFrontend.on( 'components:init', function() {
                        const imageCarousel = jQuery ( '#my_swiper .swiper-container' );
                        const swiperInstance = imageCarousel.data( 'swiper' );

                        console.log(swiperInstance);

                    });
                }
            });```

**Comment by udidol** [comment]
Hi @nicmare,
You have the `#my_swiper` ID on your Swiper widget's wrapper element?

**Comment by nicmare** [comment]
sure. it should work if you only select by class. but it does not. always returning undefined

**Comment by udidol** [comment]
Go to the Admin Dashboard > Elementor > Experiments
Look for the "Improved Asset Loading" experiment. Is it on?
If it is, turn it off and check if it works when it is off.
Let me know what you find.

**Comment by nicmare** [comment]
also thought about that feature. already turned it off with no success 👎 but i bet it stopped since they included swiper into that feature.

**Comment by nicmare** [comment]
build a sample page here:
https://vivorino.de/tabtest/
password: user
open browser console please

**Comment by KamilBT** [comment]
Hi, also have same problem - cant acces swiper via mentioned method: 

const imageCarousel = jQuery ( '#my-id .swiper-container' ); 
//of course i have correct id in file, this is just copied from https://developers.elementor.com/expose-swiper-in-elementor/

swiperInstance = imageCarousel.data( 'swiper' );
swiperInstance.slideTo( 0 ); 

It only works if typed in console, for example in chrome, but not in js file. This code returns undefined for swiperInstance. And I never turned on Improved Asset Loading, so that is not causing the problem.

**Comment by nicmare** [comment]
> Hi, also have same problem - cant acces swiper via mentioned method:
> 
> const imageCarousel = jQuery ( '#my-id .swiper-container' );
> //of course i have correct id in file, this is just copied from https://developers.elementor.com/expose-swiper-in-elementor/
> 
> swiperInstance = imageCarousel.data( 'swiper' );
> swiperInstance.slideTo( 0 );
> 
> It only works if typed in console, for example in chrome, but not in js file. This code returns undefined for swiperInstance. And I never turned on Improved Asset Loading, so that is not causing the problem.

yes it has something to do with running the code to the right moment. thats why it works in the console where everything is already loaded. including swiper.

**Comment by udidol** [comment]
@nicmare
I see the problem.
This has nothing to do with this closed issue.
This is due to a change we made in Elementor v3.2.0 to how we load Javascript (Improved Asset Loading).

Please open a new issue describing your problem and mentioning the important details from our thread here.

**Comment by KamilBT** [comment]
ok, got it
it did not work when code was in wrapped in ready:  jQuery(document).ready(function() { ...
i will work when it is wrapped in jQuery(window).load(function() {

so just place it in window load, and problem is fixed. thanks for idea of running the code to the right moment, solution was simple :D

**Comment by nicmare** [comment]
wow can not believe its that simple but can confirm it works now. here a complete real world example how i combine the image carousel with the tab widget:

```js
jQuery(document).ready(function($) {
            $(window).on('load', function () {

                $(".elementor-tabs-wrapper").each(function(i,e){
                    const swiper_target = $(this).closest(".elementor-top-section").find(".swiper-container");
                    const swiperInstance = swiper_target.data('swiper');
                    if(swiper_target.length>0){
                        $(this).find(".elementor-tab-title").each(function(i,e){
                            $(this).find("a").on("click",function(e){
                                swiperInstance.slideTo(i+1);
                            });
                        });
                    }
                });
            });
});
```

**Comment by udidol** [comment]
Good to hear you found a solution :)

**Comment by nicmare** [comment]
> ok, got it it did not work when code was in wrapped in ready: jQuery(document).ready(function() { ... i will work when it is wrapped in jQuery(window).load(function() {
> 
> so just place it in window load, and problem is fixed. thanks for idea of running the code to the right moment, solution was simple :D

does it still work for you? seems it stopped on my side

**Comment by amitsarker89** [comment]
How I will make this code work? After updating elementor 3.5.2, in console error "Swiper is not defined".

`	var WidgetSliderHandler = function ($scope, $) {
		var slider_el = $scope.find(".slider-two, .slider-one, .slider-three");
		if (slider_el.length === 0)
			return;
		var settings = slider_el.data('settings');
		var interleaveOffset = 0.5;
		var slidervar = new Swiper('.slider-two, .slider-one, .slider-three', {
			navigation: {
				nextEl: '.elementor-swiper-button-next',
				prevEl: '.elementor-swiper-button-prev',
			},
			pagination: {
				el: '.swiper-pagination',
				type: 'bullets',
				clickable: true,
			},
			autoplay: {
				delay: settings.autoplay_speed,
				disableOnInteraction: false,
			},
			effect: settings.content_animation,
			speed: 1000,
			parallax: true,
			loop: true,
			on: {
				progress: function () {
					var swiper = this;
					for (var i = 0; i < swiper.slides.length; i++) {
						var slideProgress = swiper.slides[i].progress;
						var innerOffset = swiper.width * interleaveOffset;
						var innerTranslate = slideProgress * innerOffset;
						swiper.slides[i].querySelector(".slide-inner").style.transform = "translate3d(" + innerTranslate + "px, 0, 0)"
					}
				},
				setTransition: function (speed) {
					var swiper = this;
					for (var i = 0; i < swiper.slides.length; i++) {
						swiper.slides[i].style.transition = speed + "ms";
						swiper.slides[i].querySelector(".slide-inner").style.transition = speed + "ms"
					}
				}
			}
		});

		if ('yes' !== settings.autoplay) {
			slidervar.autoplay.stop();
		}
	};
	$(window).on('elementor/frontend/init', function () {
		elementorFrontend.hooks.addAction('frontend/element_ready/osfins-slider.default', WidgetSliderHandler);
	});`

**Comment by Jonatan-r** [comment]
> wow can not believe its that simple but can confirm it works now. here a complete real world example how i combine the image carousel with the tab widget:
> 
> ```js
> jQuery(document).ready(function($) {
>             $(window).on('load', function () {
> 
>                 $(".elementor-tabs-wrapper").each(function(i,e){
>                     const swiper_target = $(this).closest(".elementor-top-section").find(".swiper-container");
>                     const swiperInstance = swiper_target.data('swiper');
>                     if(swiper_target.length>0){
>                         $(this).find(".elementor-tab-title").each(function(i,e){
>                             $(this).find("a").on("click",function(e){
>                                 swiperInstance.slideTo(i+1);
>                             });
>                         });
>                     }
>                 });
>             });
> });
> ```


 
For anyone struggling to get it to work fundamentally:

```js
<script>
jQuery(document).ready(function($) {
            $(window).on('load', function () {
                    const swiper_target = jQuery ( '#myslider .swiper-container' );
                    const swiperInstance = swiper_target.data('swiper');
                                swiperInstance.slideTo(2);
            });
});
</script>
```

**Comment by Marketricksco** [comment]
> > wow can not believe its that simple but can confirm it works now. here a complete real world example how i combine the image carousel with the tab widget:
> > ```js
> > jQuery(document).ready(function($) {
> >             $(window).on('load', function () {
> > 
> >                 $(".elementor-tabs-wrapper").each(function(i,e){
> >                     const swiper_target = $(this).closest(".elementor-top-section").find(".swiper-container");
> >                     const swiperInstance = swiper_target.data('swiper');
> >                     if(swiper_target.length>0){
> >                         $(this).find(".elementor-tab-title").each(function(i,e){
> >                             $(this).find("a").on("click",function(e){
> >                                 swiperInstance.slideTo(i+1);
> >                             });
> >                         });
> >                     }
> >                 });
> >             });
> > });
> > ```
> 
> For anyone struggling to get it to work fundamentally:
> 
> ```js
> <script>
> jQuery(document).ready(function($) {
>             $(window).on('load', function () {
>                     const swiper_target = jQuery ( '#myslider .swiper-container' );
>                     const swiperInstance = swiper_target.data('swiper');
>                                 swiperInstance.slideTo(2);
>             });
> });
> </script>
> ```

This really works, Thanks!
I had issues trying to enable autoplay and keyboard navigation with the Elementor Horizontal Scroll widget and this help to solve the issue.

```js
jQuery(document).ready(function($) {
    $(window).on('load', function() {
        //const swiper = document.querySelector('.swiper-container').swiper;
        //swiper.keyboard.enable();
        //swiper.autoplay.run();

        const swiper = new Swiper('.swiper-container', {
            speed: 1000,
            keyboard: {
                enabled: true,
                onlyInViewport: false,
            },
            autoplay: {
                delay: 2000,
            },
            loop: true,
        });


    });
});
```

**Comment by LucaPonz** [comment]
I tried everything contained in the post but still the same problem: swiper remains undefined.. does anyone still encounter the same problem with more current versions of Elementor?.. Thanks

**Comment by mahesh-dubal** [comment]
Its working very fine Thank you
jQuery(document).ready(function ($) {
  $(window).on("load", function () {
    //const swiper = document.querySelector('.swiper-container').swiper;
    //swiper.keyboard.enable();
    //swiper.autoplay.run();
console.log('inside swiper');
    swiper = new Swiper(".elementor-main-swiper", {
      // Default parameters
      slidesPerView: 1,
      spaceBetween: 10,
      // Responsive breakpoints
      breakpoints: {
        // when window width is >= 320px
        768: {
          slidesPerView: 1,
          spaceBetween: 20,
        },
        970: {
          slidesPerView: 2,
          spaceBetween: 20,
        },
        1366: {
          slidesPerView: 3,
          spaceBetween: 20,
        },
        1701: {
          slidesPerView: 4,
          spaceBetween: 20,
        },
      },
    });
  });
});

**Comment by r-interactive** [comment]
Is there a way to make the swiper carousels set to autoHeight to true? or set the height to scale with content?
the height for the loop carousel/testimonial Carousel doesn't scale with content leaving a lot of whitespace.
thanks!
