### ISSUE TITLE
Responsive Options for 'Layout' Settings

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#13270]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Enable us to create more Responsive Layouts without using Custom CSS.

**Describe the solution you'd like**
Add Mobile & Tablet Options to the following settings: http://prntscr.com/vz7p22

**Comment by DorShahar** [comment]
Hi
I merged this issue with #2043 since it is technically related. Once #2043 will be solved, we could address this request. 
 
Please feel free to continue the conversation there.
Thanks for your feedback!
