### ISSUE TITLE
Media Button on links

### ISSUE THREAD

**Issue by stockholmr** [elementor/elementor#13271]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I link to a lot of documents from the media gallery at the moment i have to open media copy the url of the document then paste it in to the link box of each item.

**Describe the solution you'd like**
Could you add a button to open the media browser for quicker document selection and add the link to the link field.

**Additional context**

![image](https://user-images.githubusercontent.com/54328941/101685958-4ee78800-3a60-11eb-9c80-d1e87cade783.png)

**Comment by DorShahar** [comment]
Hi
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
