### ISSUE TITLE
Reduce bloat. Increase speed. Increase GTMetrix Scores.

### ISSUE THREAD

**Issue by get8bit** [elementor/elementor#13272]
Is it possible to reduce the bloat to make Elementor lean and increase page speed? For the longest time, I had thought Elementor was limited by Wordpress, but Oxygen page builder found an elegant solution that has their software outperforming even Webflow.

[Here's a post about how they did it. ](https://oxygenbuilder.com/tour/performance/)

![Screen Shot 2020-12-09 at 3 54 08 PM](https://user-images.githubusercontent.com/36855453/101690425-4597f480-3a3b-11eb-8529-c9a6b1d5d8d1.png)
![Screen Shot 2020-12-09 at 3 54 19 PM](https://user-images.githubusercontent.com/36855453/101690431-4761b800-3a3b-11eb-9b98-bdd0261f5c62.png)
![Screen Shot 2020-12-09 at 3 55 19 PM](https://user-images.githubusercontent.com/36855453/101690433-47fa4e80-3a3b-11eb-9acc-0ebd6dac816a.png)
![Screen Shot 2020-12-09 at 4 09 40 PM](https://user-images.githubusercontent.com/36855453/101690435-47fa4e80-3a3b-11eb-992c-c5e6814c5a4e.png)

**Comment by DorShahar** [comment]
Hi @get8bit 
Thanks for the reference! 
In the last time and during 2021 we are constantly working on our page performance. 
Please keep up with our next updates.

Cheers
