### ISSUE TITLE
CSS finder - Css navigator

### ISSUE THREAD

**Issue by cebesten** [elementor/elementor#13276]
[x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

What problem is your feature request going to solve? Please describe.
Find CSS in the elements created. Sometimes when I create pages is the need to add some css to an element or section, when my mind is fresh I can find it easily, but after some months and creating other pages the memory is not the same, and when Im going to edit it again I must search for it, sometimes element by element, section by section....
Did I use 
selector .class ? .selector #id? I add it in the element? , In the widget? in the section? in the header? (yes sometimes for example the buttons that I change in general I add it in the header that way is global, or in the global css for the section) 
Yes sometimes is a mess to find where the custom css is. 

Describe the solution you'd like
A css tab in the navigator or emphasis in the element that shows which one has custom css applied

![image](https://user-images.githubusercontent.com/48234458/101756932-68ea9000-3a8b-11eb-8464-06d910b9dd1a.png)

Describe alternatives you've considered
A css navigator, or a tab in the navigator that shows the elements with css active

Additional context

**Comment by mcrowell** [comment]
Good idea!

**Comment by DorShahar** [comment]
Hi @cebesten 
Actually with have [exactly this feautre](https://elementor.com/help/navigator-indicators/). Just hover on the blue line and you will see custom CSS (and additional stuff, like animation). 

All the best.
