### ISSUE TITLE
Add dynamic capabilities to add images in background slideshow feature

### ISSUE THREAD

**Issue by kino89** [elementor/elementor#13277]
Background slideshow feature miss the option to add dynamically images to it. It would be very useful if you add this simply feature to Elementor PRO version.

![image](https://user-images.githubusercontent.com/72086516/101778370-0ed1e500-3af4-11eb-9379-bd8283406f57.png)

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by shilo-ey** [comment]
I merged this issue with #11056, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
