### ISSUE TITLE
More features to build more robust menus

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#13285]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hello guys,

In the Elementor theme builder, when building a Header, it is possible to use the Menu> Drop-down list widget, but the resources offered for building this menu are very small, that is, it is possible to build a very simple menu.

**Describe the solution you'd like**
So, I would like to suggest that the Elementor team offer more resources to build a more robust menu. For example, being able to divide the menu into columns, being able to insert images and icons, showing posts in a category (image and title), ...

I leave the suggestion here.

**Describe alternatives you've considered**
Some good ecommerce themes offer header builders with the possibility to build elegant menus. Consider this as an idea to offer in the Elementor builder.

**Additional context**
Examples: 
https://prnt.sc/w15ra8
https://prnt.sc/w15qer
https://prnt.sc/w15qp6

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
