### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by SoheilMatouri** [elementor/elementor#13291]
Hello 
I created a menu in elementor pro but unfortunately, the submenu is too large and goes off-screen when it opens, and I can not make it RTL . so please can everyone help me how to make a submenu in elementor RTL?

![Untitled-2](https://user-images.githubusercontent.com/72821098/102006366-e76a5a80-3d35-11eb-9927-8cd40ccf196d.jpg)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
