### ISSUE TITLE
Social Icons widget sharing problem multibyte languages

### ISSUE THREAD

**Issue by borayeris** [elementor/elementor#13295]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

If the site is Persian or Arabic AND if URL has Arabic/Persian letters; Twitter sharing is problematic. URL that is shared must be url raw encoded.

## Steps to reproduce

Create a WP page with a Persian title. Click Twitter share button.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

Latest WP and Elementor versions.

**Comment by DorShahar** [comment]
Hi @bainternet 
Thank you for taking the time and reporting this.

We recreated your process again of work and it seems to work properly.

If the problem persists, please open a new issue and link to this one.

Thanks.
