### ISSUE TITLE
Full-Width Page - incorrect work of the script

### ISSUE THREAD

**Issue by DekSter87** [elementor/elementor#13309]
Hi, I noticed that the script does not work correctly, which stretches the page to full width.
Incorrect work is as follows: the section is stretched to the width of the "visible" window + the width of the side scrollbar of the page. Because of this, a left-right page scroll bar also appears at the bottom. 
This causes problems on some sites. The width of the ELEMENTOR layout is wider than the width of the WordPress page container.
![Сохраненное изображение 2020-12-15_16-52-27 418](https://user-images.githubusercontent.com/38693925/102199923-cb61e700-3ef6-11eb-9038-f4da56f7ea44.jpg)

**Comment by DorShahar** [comment]
Hi @DekSter87 
This is a bug due to WP 5.6  which we are fixing as we speak. 
Please update the next minor version which will be available soon.

Thanks

**Comment by DekSter87** [comment]
Thanks!
