### ISSUE TITLE
3.x.x versions does not load

### ISSUE THREAD

**Issue by Amirhosseinkianfard** [elementor/elementor#13306]
I installed last version of elementor but editor doesnt load in **normal** and **safe** mode
*I try all 3.x.x versions* and
when i downgrade to *2.9.9 version* elementor editor loaded in normal mode 
How can i fix this problem for last version??

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
