### ISSUE TITLE
Templates in elementor pages incompatibility WordPress 5.6

### ISSUE THREAD

**Issue by alfredo49** [elementor/elementor#13307]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description
Hi:

Since i updated to WordPress 5.6 when i edit a elementor page, templates used in this page (yellow box you can edit) has dissapeared, clicking in navigation button either appears (it’s as if someone had deleted the template from that page), if i change to WP 5.5.3 all works ok normally.

Thxs

## Steps to reproduce

- Enter a page created with elementor in which some block is of type template (yellow box)
- Template structure has dissapears! yo cant select it, move it, edit it...
- if you go to WP 5.5.3 , template structure appears again in elementor blocks created in that page and always works OK again

## Isolating the problem
- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 9.13 v5.6.49-89.0
	PHP Version: 7.3.23
	PHP Max Input Vars: 10000
	PHP Max Post Size: 35M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: http://www.tqmdesarrollo.com/elguiadelparaiso
	Home URL: http://www.tqmdesarrollo.com/elguiadelparaiso
	WP Multisite: No
	Max Upload Size: 35 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.6.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:78.0) Gecko/20100101 Firefox/78.0

== Active Plugins ==
	ACF Content Analysis for Yoast SEO
		Version: 3.0.1
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Advanced Custom Fields
		Version: 5.9.3
		Author: Elliot Condon

	Akismet Anti-Spam
		Version: 4.1.7
		Author: Automattic

	Astra Pro
		Version: 2.7.2
		Author: Brainstorm Force

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	DynamicConditions
		Version: 1.4.6
		Author: RTO GmbH

	Easy Watermark
		Version: 1.0.6
		Author: BracketSpace

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com

	Flow-Flow
		Version: 4.6.12
		Author: Looks Awesome

	GDPR Cookie Compliance (CCPA, PIPEDA ready)
		Version: 4.4.2
		Author: Moove Agency

	Server IP & Memory Usage Display
		Version: 2.1.0
		Author: Apasionados, Apasionados del Marketing

	Smush
		Version: 3.8.2
		Author: WPMU DEV

	WooCommerce
		Version: 4.8.0
		Author: Automattic

	Yoast Duplicate Post
		Version: 3.2.6
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 15.4
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		divider : 1
		global : 1
		heading : 3
		icon : 1
		social-icons : 1
		theme-site-logo : 1
	loop : 2
		heading : 2
		post-info : 2
		theme-post-title : 2
	page : 9
		button : 1
		divider : 9
		heading : 13
		icon : 5
		icon-box : 4
		icon-list : 2
		post-info : 2
		posts : 1
		share-buttons : 1
		spacer : 1
		text-editor : 4
		theme-post-title : 2
		woocommerce-breadcrumb : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-rating : 1
		woocommerce-product-title : 1
		wp-widget-nav_menu : 1
	popup : 1
		form : 1
		heading : 1
	product : 12
		button : 3
		divider : 28
		heading : 35
		icon : 17
		icon-box : 11
		icon-list : 6
		nav-menu : 1
		posts : 3
		share-buttons : 3
		spacer : 3
		text-editor : 14
		woocommerce-breadcrumb : 3
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 3
		woocommerce-product-data-tabs : 3
		woocommerce-product-images : 3
		woocommerce-product-rating : 3
		woocommerce-product-title : 3
		wp-widget-nav_menu : 3
	section : 1
		divider : 1
		heading : 1
	widget : 0
		media-carousel : 4
	wp-post : 1
		text-editor : 1
	wp-page : 3
		button : 1
		heading : 2
		posts : 2
		woocommerce-products : 1
	single-post : 1
		divider : 2
		heading : 3
		icon : 1
		image : 6
		post-comments : 1
		post-info : 1
		post-navigation : 1
		posts : 3
		sidebar : 1
		spacer : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	search-results : 1
		heading : 1
		posts : 1
	product-archive : 3
		posts : 1

== Log ==
	
JS: showing 20 of 34JS: 2020-12-08 10:30:23 [error X 5][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view284\") has already been destroyed and cannot be used. 
JS: 2020-12-08 11:08:14 [error X 3][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view281\") has already been destroyed and cannot be used. 
JS: 2020-12-08 11:42:30 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1323\") has already been destroyed and cannot be used. 
JS: 2020-12-09 09:20:15 [error X 2][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view278\") has already been destroyed and cannot be used. 
JS: 2020-12-10 19:47:52 [error X 3][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view115\") has already been destroyed and cannot be used. 
JS: 2020-12-10 20:16:23 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view9091\") has already been destroyed and cannot be used. 
JS: 2020-12-10 20:19:36 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3720\") has already been destroyed and cannot be used. 
JS: 2020-12-10 20:32:49 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view601\") has already been destroyed and cannot be used. 
JS: 2020-12-10 20:34:38 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5541\") has already been destroyed and cannot be used. 
JS: 2020-12-12 17:40:05 [error X 2][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.8:2:95150] Cannot read property \'setSettings\' of undefined 
JS: 2020-12-13 18:36:12 [error X 2][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view126\") has already been destroyed and cannot be used. 
JS: 2020-12-13 18:45:41 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1535\") has already been destroyed and cannot be used. 
JS: 2020-12-13 18:46:59 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view127\") has already been destroyed and cannot be used. 
JS: 2020-12-13 18:56:33 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view122\") has already been destroyed and cannot be used. 
JS: 2020-12-13 19:04:05 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view129\") has already been destroyed and cannot be used. 
JS: 2020-12-14 11:09:08 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view128\") has already been destroyed and cannot be used. 
JS: 2020-12-14 11:09:48 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view903\") has already been destroyed and cannot be used. 
JS: 2020-12-14 11:38:10 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view100\") has already been destroyed and cannot be used. 
JS: 2020-12-14 17:15:51 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view313\") has already been destroyed and cannot be used. 
JS: 2020-12-14 18:07:19 [error X 1][http://www.tqmdesarrollo.com/elguiadelparaiso/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view316\") has already been destroyed and cannot be used. 

PHP: showing 8 of 8PHP: 2020-12-01 11:02:12 [warning X 1][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/home/tqmdesarrollo.com/tmp/xuacu-v1.1/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-01 12:16:26 [notice X 25][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-01 18:41:22 [error X 4][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /usr/home/tqmdesarrollo.com/w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-05 09:55:46 [notice X 1][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor/includes/conditions.php::90] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-05 13:30:10 [notice X 5][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/query-control/module.php::738] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-11 09:26:52 [notice X 2][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-12 10:38:42 [notice X 1][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-14 12:17:43 [notice X 5][/usr/home/tqmdesarrollo.com/web/elguiadelparaiso/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by DorShahar** [comment]
Hi 
We are fixing this issue as we speak. 
Please update the next patch version which will be available soon.

 Thanks

**Comment by Seventhose** [comment]
Same issue here:

Log: showing 3 of 3
2020-10-21 17:27:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 21:09:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-26 01:18:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
JS: showing 20 of 21
JS: 2020-11-11 15:54:40 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view40650\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view44962\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view45002\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view40725\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view45159\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view45188\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view45420\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view45437\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view49868\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view49884\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view49892\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view49908\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view45512\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view50065\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view50094\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view50326\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view50343\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:53 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view55923\") has already been destroyed and cannot be used. 
JS: 2020-11-11 15:57:10 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3156\") has already been destroyed and cannot be used. 
JS: 2020-12-18 08:27:25 [error X 68][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.14:2:6232] container or containers are required. 
PHP: showing 3 of 3
PHP: 2020-12-05 17:07:15 [error X 10][/var/www/vhosts/greenwoodluxuryhome.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 6293064 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-13 00:35:51 [error X 4][/var/www/vhosts/greenwoodluxuryhome.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 6477320 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-15 23:12:39 [error X 5][/var/www/vhosts/greenwoodluxuryhome.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 6477448 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by Seventhose** [comment]
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.30
	PHP Version: 7.4.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://greenwoodluxuryhome.it
	Home URL: http://greenwoodluxuryhome.it
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 0
	Admin Email: valentina@pimentasolutions.it
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.6.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.32
		Author: ServMask

	All-in-One WP Migration Direct Extension
		Version: 1.7
		Author: ServMask

	Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd
		Version: 6.0.9.0
		Author: SeedProd

	Elementor
		Version: 3.0.14
		Author: Elementor.com

	MainWP Child
		Version: 4.1.3
		Author: MainWP


== Must-Use Plugins ==
	WP Time Capsule
		Version: 
		Author: Revmakx


== Elements Usage ==
	
	jet_footer : 0
		heading : 8
		icon-list : 2
		social-icons : 1
	jet_header : 0
		icon-list : 2
		image : 1
		navigation : 1
	page : 11
		button : 40
		counter : 20
		google_maps : 1
		heading : 295
		icon-list : 36
		image : 100
		image-carousel : 2
		image-gallery : 2
		navigation : 9
		social-icons : 9
		spacer : 34
		toggle : 1
	section : 5
		button : 23
		divider : 4
		heading : 119
		icon : 1
		icon-box : 6
		icon-list : 14
		image : 27
		image-carousel : 5
		navigation : 3
		social-icons : 3
		spacer : 31
	wp-post : 0
		heading : 8
		icon-list : 4
		image : 1
		navigation : 1
		social-icons : 1
	wp-page : 7
		button : 16
		counter : 4
		google_maps : 1
		heading : 113
		icon : 2
		icon-list : 1
		image : 29
		image-box : 36
		image-carousel : 5
		image-gallery : 1
		spacer : 38
		text-editor : 2
		uael-fancy-heading : 1


== Log ==
	
Log: showing 3 of 32020-10-21 17:27:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 21:09:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-26 01:18:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]

JS: showing 20 of 21JS: 2020-11-11 15:54:40 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view40650\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view44962\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view45002\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view40725\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view45159\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view45188\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view45420\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:00 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view45437\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view49868\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view49884\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view49892\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:16 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view49908\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view45512\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view50065\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view50094\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view50326\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:17 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view50343\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:55:53 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view55923\&quot;) has already been destroyed and cannot be used. 
JS: 2020-11-11 15:57:10 [error X 1][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view3156\&quot;) has already been destroyed and cannot be used. 
JS: 2020-12-18 08:27:25 [error X 68][https://greenwoodluxuryhome.it/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.14:2:6232] container or containers are required. 

PHP: showing 3 of 3PHP: 2020-12-05 17:07:15 [error X 10][/var/www/vhosts/greenwoodluxuryhome.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 6293064 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-13 00:35:51 [error X 4][/var/www/vhosts/greenwoodluxuryhome.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 6477320 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-15 23:12:39 [error X 5][/var/www/vhosts/greenwoodluxuryhome.it/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 6477448 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by alfredo49** [comment]
in the new elementor version, the problem is partially solved but not totally solved. The global section still does not appear in the visual editor, the only way to access it is through the structure browser
