### ISSUE TITLE
elementor-pro-3.0.8.zip is missing style.css stylesheet

### ISSUE THREAD

**Issue by Katemateo** [elementor/elementor#13305]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I have a brand new instance of Wordpress 5.6 installed @godaddy.com. 
the only plug in that is installed is to prevent someone from trying to login multiple times with the wrong password.

## Steps to reproduce
1)  Downloaded elementor-pro-3.0.8.zip from your site.
2) Logged into wordpress dashboard.
3) Clicked on the Appearance menu and upload the theme.

The package could not be installed.  The theme is missing the style.css stylesheet.
Theme installation failed.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>wordpress 5.6 at godaddy.com
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
<img width="1024" alt="Screen Shot 2020-12-14 at 8 41 48 PM" src="https://user-images.githubusercontent.com/76028816/102174224-c7c85480-3e51-11eb-9ac2-4440119a7e4f.png">

**Comment by shilo-ey** [comment]
Hi @Katemateo 

Elementor Pro is a plugin and not a theme. please upload it via the Plugins screen and make sure you have [Elementor](https://wordpress.org/plugins/elementor/) installed

Thanks
