### ISSUE TITLE
Saving Templates

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#13326]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by drosa88** [comment]
This seems to be a known issue with the current WordPress version. Please check the output of your console if you get the error which was described here: https://github.com/elementor/elementor/issues/13297

**Comment by Aviad-Herman** [comment]
Thanks for reporting guys.
I'm merging this with #13273.
