### ISSUE TITLE
Fallback background image not working

### ISSUE THREAD

**Issue by kostas33** [elementor/elementor#13322]
Hi all. Just what the title says, I have an ACF field for background image and the fallback does not show.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
