### ISSUE TITLE
how to go directly to the new page builder without pressing button try new page builder

### ISSUE THREAD

**Issue by hustache** [elementor/elementor#13339]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustache** [comment]
how to go directly to the new page builder without pressing button try new page builder

**Comment by Aviad-Herman** [comment]
Hey @hustache,
You'd have to send me a screenshot or something. I can't understand what you mean.

- If you want a quicker way to create a page press ctrl+e and then type "new page".
- If you mean new "Theme Builder" you can use ctrl+shift+e
