### ISSUE TITLE
No posts found message on Posts widget

### ISSUE THREAD

**Issue by DeveloperWil** [elementor/elementor#13338]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When there are no posts matching the query conditions on the Posts widget, it returns an empty container.
Can you add a customisable message to display when no posts are returned?

**Describe the solution you'd like**
A custom field: "No Posts Found Message"

**Describe alternatives you've considered**
Adding a CSS ID to the widget then writing JS to test to see if the container is empty and writing my own text - not very nice.

**Comment by emeliosm** [comment]
I vote on this. I hope this feature can be added to the posts widget. Thanks.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #7624, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
