### ISSUE TITLE
Feature Request: Image Carousel should support an offset feature

### ISSUE THREAD

**Issue by dagostinelli** [elementor/elementor#13337]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When the image size is set to something less than full, the image zooms into the center of a picture. Imagine you have 1000x1000 portrait of a person in the carousel. If you set the image size to  it to 250x250 it just zooms into the person's neck.

**Describe the solution you'd like**
The image carousel needs an offset feature so that we can shift the image up or down, left or right.  

**Describe alternatives you've considered**
Buying this: https://premiumaddons.com/docs/carousel-widget-tutorial/

**Additional context**
N/A

**Comment by DorShahar** [comment]
Hi @dagostinelli 
Thank you for your input. At this point, we are focusing on other areas of the product, so we cannot integrate your desired suggestion. 
 
However, you can use [Cloudinary ](https://cloudinary.com/) and you can use a free account. They have awesome [API](https://cloudinary.com/documentation/image_transformations) which will allow you to do whatever you desire. 

All the best!

**Comment by black-eye** [comment]
> Hi @dagostinelli
> Thank you for your input. At this point, we are focusing on other areas of the product, so we cannot integrate your desired suggestion.
> 
> However, you can use [Cloudinary ](https://cloudinary.com/) and you can use a free account. They have awesome [API](https://cloudinary.com/documentation/image_transformations) which will allow you to do whatever you desire.
> 
> All the best!

Really? Your advise is to use 3rd party solution, because your own sucks and you are not willing to improve it? Good to know. Next advise will be to use another pagebuilder, maybe?
