### ISSUE TITLE
Header and Footer access in Navigator

### ISSUE THREAD

**Issue by RemPro** [elementor/elementor#13349]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RemPro** [comment]
It would be very nice if the Header and Footer also will be accessible in the Navigator. Sometimes the layout is contructed that the header and footer are not accessible .

Cheerzzzz

-Rem

**Comment by shimsa** [comment]
+1

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10979, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
