### ISSUE TITLE
Telegram link: tg://resolve

### ISSUE THREAD

**Issue by awp-sirius** [elementor/elementor#13342]
I want to add a link for telegrams in the format: **tg://resolve?domain={login}**
But after saving the changes in the code I see an empty href

**Comment by Aviad-Herman** [comment]
Hey, I'm no expert so I'm not sure what "tg://resolve?domain={login}" does.

If you want to share the webpage using telegram, use either:
- https://t.me/share/url?url={url}&text={text}
- https://telegram.me/share/url?url={url}&text={text}
- tg://msg_url?url={url}&text={text}

If you want to open a chat, use:
 - [Tutorial on Quora](https://www.quora.com/How-can-I-share-my-Telegram-link)
 
 Does this answer your question?

**Comment by awp-sirius** [comment]
https://core.telegram.org/api/passport#uri-format

I want to use exactly this, because links _t.me_ and _telegram.me_ may not be available in Russia

**Comment by Aviad-Herman** [comment]
I see. Before we continue, a question:
 tg://resolve?domain={login} works only on mobile if you have telegram installed, right?

**Comment by awp-sirius** [comment]
google chrome supports it in windows 10
![image](https://user-images.githubusercontent.com/17874415/102502555-d13f0000-408f-11eb-9423-d0373fe25244.png)

**Comment by Aviad-Herman** [comment]
Which widget are you using, Social Icons?
One possible workaround / hack is to place an html widget after it and use JQUERY to change the href attribute of the link.

**Comment by awp-sirius** [comment]
no. just icons, with links

**Comment by Aviad-Herman** [comment]
Here is a tutorial I made that can help you hack around this issue:
https://www.loom.com/share/6ffd5aef07a34aec89ce24c2deeac4b3

<script>
    let a = jQuery('#custom-id a');
    a.attr('href', 'tg://resolve?domain=your-tg-user');
</script>

**Comment by rezaahmadiza** [comment]
> Here is a tutorial I made that can help you hack around this issue: https://www.loom.com/share/6ffd5aef07a34aec89ce24c2deeac4b3
> 
> ```
> <script>
>     let a = jQuery('#custom-id a');
>     a.attr('href', 'tg://resolve?domain=your-tg-user');
> </script>
> ```
hey Aviad
Thanks for the way you taught.
I had the same problem. But I use acf and I need to have a separate button for each post that displays the Telegram channel link.
Do you have a solution for this issue?

**Comment by pravinkumar35** [comment]
Fiuthj

**Comment by pravinkumar35** [comment]
pravinkumar358035@gmail.com

**Comment by mrzaro** [comment]
Colour trading
