### ISSUE TITLE
Popups (in Elementor Backend) stuck

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13343]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description

Hi,

- Newsletter Popup in Elementor Backend
- Template Save Popup
- Template Import Popup
Get stuck when its loaded after the action. This happend in all my sites with the latest Wordpress release and Elementor & Elementor Pro (latest version as well)

## Steps to reproduce

You can use Elementor & Pro within the DevEdition. It happens into normal sites as well.

Saving Templates
1. Go to a Page.
2. Save template.
3. Get stuck in saving...
4. You need to go to Elementor > Templates and download it from there.

Importing Templates
1. Go to Page
2. Import a Template
3. Get stuck in Uploading...
4. Need to refresh page to see the imported template.
## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.3.25
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://elementor.maurocarrera.com
	Home URL: https://elementor.maurocarrera.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.1.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.0.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com

	Ultimate Addons for Elementor
		Version: 1.28.0
		Author: Brainstorm Force

== Elements Usage ==
	
	header : 1
		button : 1
	wp-page : 33
		blockquote : 1
		button : 99
		call-to-action : 15
		counter : 7
		divider : 55
		flip-box : 23
		form : 5
		gallery : 3
		google_maps : 4
		heading : 325
		icon : 20
		icon-box : 52
		icon-list : 29
		image : 77
		image-box : 26
		image-carousel : 7
		image-gallery : 1
		media-carousel : 1
		menu-anchor : 9
		nav-menu : 1
		portfolio : 4
		posts : 31
		price-table : 3
		progress : 4
		search-form : 1
		slides : 1
		social-icons : 13
		spacer : 42
		testimonial : 11
		testimonial-carousel : 10
		text-editor : 141
		toggle : 1
		video : 7

== Log ==
	
PHP: showing 4 of 4PHP: 2020-08-30 18:27:38 [notice X 2][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-26 07:36:36 [notice X 1][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::154] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-13 18:37:05 [notice X 14][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-14 17:06:14 [notice X 11][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::226] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 12 of 122020-09-03 20:39:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.3',
)]
2020-09-03 20:39:51 [info] elementor::elementor_updater Started 
2020-09-03 20:39:51 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-03 20:39:51 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-03 20:39:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-03 20:39:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-11-06 01:20:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.13',
)]
2020-11-06 01:20:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.6',
)]
2020-11-26 07:23:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-11-26 07:23:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-12-13 18:43:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.7',
  'to' => '3.0.8',
)]
2020-12-17 15:04:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.1.0-dev2',
)]

JS: showing 3 of 3JS: 2020-12-17 15:04:51 [error X 3][https://elementor.maurocarrera.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=5.6:2:31670] Cannot read property \'landingPagesHasPages\' of undefined 
JS: 2020-12-17 15:04:51 [error X 4][https://elementor.maurocarrera.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=5.6:2:31670] elementorAdmin is not defined 
JS: 2020-12-17 15:05:12 [error X 1][https://elementor.maurocarrera.com/wp-content/plugins/elementor/assets/js/beta-tester.min.js?ver=3.1.0-dev2:2:23495] elementorBetaTester is not defined 

				
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
