### ISSUE TITLE
Introducing Elementor Beta Developer Edition Plugin

### ISSUE THREAD

**Issue by shilo-ey** [elementor/elementor#13346]
Hi there,
We’re excited to launch the new **Elementor Beta Developer Edition plugin**.

As you are a part of an exclusive group of advanced Elementor users and developers, we invite you to access our newest features and experimental functionalities before they are released.

You will get to share your feedback directly with the Elementor development team, via a dedicated GitHub issue (tagged Developer Edition), and help contribute to the future versions of Elementor.

This will allow us to test and release new features more frequently, once they’ve been tried and tested by the community.

Want to find out more? Read about it [on our blog](https://elementor.com/blog/introducing-beta-developer-edition/?utm_source=Elementor&utm_campaign=Developer_Plugin_Release-16.12.20-Github_Users&utm_medium=Github).

**Ready to dive in?** [Download the plugin from WordPress plugins repository](https://wordpress.org/support/plugin/elementor-beta)

**Important Note!**
We highly recommend using the Developer plugin on staging environments only, and backing up your entire website before updating.

 
Thank You,
Elementor Developer team

**Comment by maurocarreraok** [comment]
Nice in this one! I would love to see some improvements into the plugin like taking the SysInfo automatically. But well done!

**Comment by fabianenzensperger** [comment]
OK that's good! But how do I know which Elementor version it actually is? And why do I also need the normal Elementor plugin? And where can I see what's new in this developer version?

**Comment by black-eye** [comment]
@fabianenzensperger 
> And where can I see what's new in this developer version?

Exactly! What are we supposed to do with this plugin? What should we test, what to look for, what has been changed? @shilo-ey, remember those times there were use cases and test flows in the description of each beta?

The whole stuff seems to me like a beta version of a beta testing plugin ...

**Comment by rodolphebertozzo** [comment]
The concept is interesting, it's a good idea, it was about time it happened, there are still 5 million active installations on Elementor! If I understood correctly, we are testing ONE PART of the features brought to version 3.1, the other part being in the process of being finalized has not yet been merged into the developer edition branch?

**Comment by rodolphebertozzo** [comment]
@fabianenzensperger,
You are offered the upgrade to 3.1.0, but this is not the finalized version, part of the features have been released in the 3.1 branch. All future features will go through the developer edition branch while testing.

**Comment by fabianenzensperger** [comment]
Yes that actually sounds good. Sorry, that shouldn't sound outrageous, but now there are 4 plugins, Elementor Free, Pro, Free Beta, Pro Beta, Free Developer, something between beta and experiments and soon the Pro Developer. Don't you lose track of it?

If I remember, it didn't run smoothly with 2 plugins (Free & Pro) when 3.0 was introduced. Correct me if I see it wrong. Oh, and of course I'll be taught a better one! :)

**Comment by fabianenzensperger** [comment]
> @fabianenzensperger
> 
> > And where can I see what's new in this developer version?
> 
> Exactly! What are we supposed to do with this plugin? What should we test, what to look for, what has been changed? @shilo-ey, remember those times there were use cases and test flows in the description of each beta?
> 
> The whole stuff seems to me like a beta version of a beta testing plugin ...

Found this: https://github.com/elementor/elementor/blob/developer-edition/CHANGELOG.md

**Comment by black-eye** [comment]
> Found this: https://github.com/elementor/elementor/blob/developer-edition/CHANGELOG.md

Yes, found that page too. But there's still not much more info there, isn't it? What are the Landing Pages for example...?

I Also found there's a new tab in Tools:
![obrazek](https://user-images.githubusercontent.com/5634870/102551402-b1273500-40bf-11eb-9877-d8a1507d1514.png)

But when you click on more info for Accesibility Improvements, the page doesn't exist. That's why I have this beta-ish feeling...

**Comment by riadcitaku** [comment]
@black-eye Landing Pages are added below Theme Builder, under the Templates tab. I'm still confused about its purpose, it's not much different than section or Elementor page.

**Comment by MichaelDarko** [comment]
Seems like a good idea. If I understand it correctly:

- **Beta versions** - Testing things that are about to get released in the next version
- **Beta Developer Edition** - Testing new things that Elementor is working on in general 

Although at this point, there is not much to test, but I assume this will change in the future.
___

**Some ideas to motivate people to use the Beta Developer Edition:**

- There should be a central place in the admin that tells you what's different from the regular version, what new features were added with each update, where to find them and how to test them (All regularly updated). 

(Are all changes gonna be under the "Experiments" tab? I assume not. Simple changelog doesn't give enough information. Right now, we sort of have to "figure it out ourselves" which discourages us from using it.)

- Make it juicy. The more stuff you put in there the more people will be interested in testing it.

(If changes are introduced too sporadically, or if they're just small details, most people will probably just wait for the beta versions.)

**Comment by godvsgodvs** [comment]
Weird, I'm on 3.1.0-dev3 but I don't see the Experiments tab.

**Comment by godvsgodvs** [comment]
I found it but it's under settings not tools

**Comment by fuzenco** [comment]
Why not just call it Developer Edition? The word Beta adds complexity and without it it’s implied this is a very closed. And why so many editions?

**Comment by fuzenco** [comment]
> Don't you lose track of it?

Yes, good question. It’s enough to halt anyone in their tracks.

**Comment by shilo-ey** [comment]
> Nice in this one! I would love to see some improvements into the plugin like taking the SysInfo automatically. But well done!

@maurocarrerao
What do you mean by taking the system info automatically? 


@fabianenzensperger @black-eye
> OK that's good! But how do I know which Elementor version it actually is? And why do I also need the normal Elementor plugin? And where can I see what's new in this developer version?

The Developer Edition plugin is basically an enhanced version manager: It adds some visual aids to identify that you're using this plugin (because it's not stable by definition).
It fetches Elementor dev-track versions for you to give feedback on, and prepare 3rd party addons with the latest version to avoid conflicts.

The dev version currently can be seen in the file: https://github.com/elementor/elementor/blob/developer-edition/CHANGELOG.md

The main reason for us to release this version is to allow much more stable beta versions, and create a continuous delivery workflow before the version is officially released.

As for the beta version - it will still be available with test flow and information about each teak/fix/addition.

The Developer edition will contain the features/changes/fixes that we are working on. Every version we will take some features from this "Basket" of features and will pack them as a major version. this way, features will get more time "out there" so you could share your thoughts on, inputs, bugs etc, and we will have more time to adjust to your feedback.


@black-eye 
> But unfortunately it brings more questions than the answers. That's why I have this beta-ish feeling...

Yes, the dev-edition is prior to beta, and we are not encouraging users to use these version on live sites.
This plugin is the way everybody can get a glimpse into the next releases before they are officially released and share inputs.


@MichaelDarko

> **Some ideas to motivate people to use the Beta Developer Edition:**
> 
> * There should be a central place in the admin that tells you what's different from the regular version, what new features were added with each update, where to find them and how to test them (All regularly updated).

We will add a changelog for dev-edition versions soon.

> (Are all changes gonna be under the "Experiments" tab? I assume not. Simple changelog doesn't give enough information. Right now, we sort of have to "figure it out ourselves" which discourages us from using it.)
> 
> * Make it juicy. The more stuff you put in there the more people will be interested in testing it.
> 
> (If changes are introduced too sporadically, or if they're just small details, most people will probably just wait for the beta versions.)

One of the differentiators for the Developer Edition versions, is that we intentionally don't want to share too much information about each feature to avoid biasing the natural discovery of the feature.


Thank you all! hope this will bring more transparency and clarity to our next releases.

**Comment by black-eye** [comment]
@shilo-ey 
> One of the differentiators for the Developer Edition versions, is that we intentionally don't want to share too much information about each feature to avoid biasing the natural discovery of the feature.

Ok, now I've got it. If someone has the real urge to help you, you will allow him to do so this way. But you won't tell him what to test and how to do it, because you don't want to spoil your secrets. Fair enough. Count me out.

**Comment by shilo-ey** [comment]
Quite the opposite @black-eye , it's supposed to reveal the next features prior to the time our entire documentation and tutorials are ready. Of course we will do our best to provide with a proper explanation just like we did with:
- Next version deprecations - [here](https://developers.elementor.com/v3-1-planned-deprecations/)
- Experiments - [here](https://developers.elementor.com/elementor-experiments/)
- Compatibility Tag - [here](https://developers.elementor.com/compatibility-tag/)
- More docs to come. 

This way we won't block any progress and release and won't condition the release with the preparation of these docs to allow more agility.

Once a new developer-oriented feature will be introduced we will share a blog post about it. 

Thanks

**Comment by rodolphebertozzo** [comment]
@shilo-ey, I still don't see the load optimization feature, is that normal?

**Comment by shilo-ey** [comment]
> @shilo-ey, I still don't see the load optimization feature, is that normal?

Yes, we had an issue. thanks for raising it. it is now available in the Beta version

Thanks
