### ISSUE TITLE
Changing Preview Width

### ISSUE THREAD

**Issue by kwashykwash** [elementor/elementor#13352]
Hi! I'm trying to set a custom preview width in the elementor preview editor, but I'm running into some issues.  Is there a value I can tap into to set the preview width?  Rather than setting it through the DOM?  I'm trying to change the mobile width to 414px and tablet to 1024px.  The code below works, but doesn't seem to be compatible with widget extensions.  

//Set custom elementor preview width on tablet and mobile
add_action( 'elementor/editor/wp_head', function() {
    if (\Elementor\Plugin::$instance->editor->is_edit_mode()) {
        echo "<script>window.addEventListener('DOMContentLoaded', function() {
                var checkExist = setInterval(function() {
                  if (document.querySelector('.elementor-device-mobile #elementor-preview-responsive-wrapper')){
                    document.querySelector('.elementor-device-mobile #elementor-preview-responsive-wrapper').style.width = '414px';
                    document.querySelector('.elementor-device-mobile #elementor-preview-responsive-wrapper').style.height = '640px';
                  }
                  if (document.querySelector('.elementor-device-tablet #elementor-preview-responsive-wrapper')){
                    document.querySelector('.elementor-device-tablet #elementor-preview-responsive-wrapper').style.width = '1024px';
                    document.querySelector('.elementor-device-tablet #elementor-preview-responsive-wrapper').style.height = '1025px';
                  }
                  if (document.querySelector('.elementor-device-desktop #elementor-preview-responsive-wrapper')){
                     document.querySelector('.elementor-device-desktop #elementor-preview-responsive-wrapper').style.height = '100%';
                     document.querySelector('.elementor-device-desktop #elementor-preview-responsive-wrapper').style.width = '100%';
                  }
                }, 100);
        });</script>";
    }
});

**Comment by DorShahar** [comment]
Hi @kwashykwash 
Why not changing the preview in Chrome dev-tools? Is that what you need?
![image](https://user-images.githubusercontent.com/19154938/102708014-7df3ca00-42a8-11eb-9071-bbf8ef2a002b.png)

**Comment by kwashykwash** [comment]
No, because that doesn't change the elementor preview width and allow me to still edit the content while previewing.  It just changes the window width.

**Comment by DorShahar** [comment]
Hi 
Preview UI will change in the #2043 feature. 
Therefore, I'm closing this issue. Please followup in #2043 .

Thanks.
