### ISSUE TITLE
✔️ 🔗 🚀 Feature Request: A more flexible section with auto-width columns (Related to #2219)

### ISSUE THREAD

**Issue by Arian-c27** [elementor/elementor#13356]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**My request**
Option to make a section more flexible where the columns take no more space than they require instead of fixed percentage

**The issue**
Let's say you full width section with 3 columns, in this case a header. The structure is

[LOGO] [MENU------------------] [LOGIN]

So you add a section with 3 columns, and you can set their percentages, let's say 20% 60%, 20%;

Within the logo column, I add the logo image however I don't want to set the image to have percentage width as it may be too big on some screens and too small on others. I want a fixed logo image width. 

But if I do so, the logo image will (most of the time) be smaller or bigger than the logo column depending on screen width.

If it's smaller, that creates empty space between the logo and the menu

[LOGO**/////**] [MENU------------------] [LOGIN]

**Describe the solution you'd like**

The solution I propose is, add an option to each section which when enabled sets each child column to width: auto;

```
.elementor-row  > .elementor-column {
width: auto;
}
```

Add an additional option to control the behaviour of the columns with flexbox e.g center, left, right, space-between, space-around.

```
.elementor-row {
justify-content: space-between; /*center, left, right, space-between, space-around.*/
}
```

You could also add flex-grow option for each column

**Comment by fuzenco** [comment]
Absolutely. And perfectly explained.

**Comment by perks98** [comment]
+1

**Comment by MichaelDarko** [comment]
I was also requesting "auto" option for columns: #11887

Maybe using custom positioning could help you achieve what you need. 

1. Create only one column
2. Insert Logo, Menu, Login widgets
3. Set for every widget: Custom positioning -> Width -> Inline (auto)
4. Set for the column: Horizontal align -> Space between

**Comment by black-eye** [comment]
+1

**Comment by fabianenzensperger** [comment]
+1

**Comment by Arian-c27** [comment]
> I was also requesting "auto" option for columns: #11887
> 
> Maybe using custom positioning could help you achieve what you need.
> 
> 1. Create only one column
> 2. Insert Logo, Menu, Login widgets
> 3. Set for every widget: Custom positioning -> Width -> Inline (auto)
> 4. Set for the column: Horizontal align -> Space between

Wasn't aware of that option. Although, you still can't control flex-wrap without custom CSS. So when building the header parts of it may wrap to the next line

**Comment by parasshah195** [comment]
+1

**Comment by lllopo** [comment]
> I was also requesting "auto" option for columns: #11887
> 
> Maybe using custom positioning could help you achieve what you need.
> 
> 1. Create only one column
> 2. Insert Logo, Menu, Login widgets
> 3. Set for every widget: Custom positioning -> Width -> Inline (auto)
> 4. Set for the column: Horizontal align -> Space between

This doesn't really work. Well ... it works if you don't need a more complicated structure, like a row of inline elements and some of them being containers for columns of other elements. Elementor is stupid enough to offer only "section" and "inner section" as containers so you can't just place a div wherever you want, make it display flex and use it as container. On top of that - inner section, which would be your only option if you need an internal container does NOT offer inline positioning ... so if you want to create something quite common as a profile element, containing a photo with flexible width on the left and a column of elements (like name, logout link etc on the right) ... you are out of luck.
 I simply don't understand why there is no such thing as simple container element that renders a div and then - this element having all possible flex and grid CSS options so the advanced users have the freedom to create custom flexible layouts.

**Comment by mohsinworld** [comment]
I really need this feature. Auto width depends on content size. For example, I have 6 buttons with 6 columns. I have added 6 country names that are not the same characters. In that case, the button looks ugly depending on the button size. So auto column width will solve this issue.

Screenshot of the problem's example: https://prnt.sc/25twVcqQ28i8

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/2219

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
