### ISSUE TITLE
Fatal Error everytime i try to edit a Page with Elemetor

### ISSUE THREAD

**Issue by Danny1994m** [elementor/elementor#13351]
Hello everyoneone,

i couldn't find this exact error yet, so here i am making this thread. I never had any Problems with Elementor untill today Suddenly i get this error:

`
Fatal error: Uncaught Error: Undefined class constant 'ICONS' in /www/htdocs/w017bff9/optiker-neukirchen-vluyn.de/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/pricing-table.php:271 Stack trace: #0 /www/htdocs/w017bff9/optiker-neukirchen-vluyn.de/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/pricing-table.php(83): ThemeIsle\ElementorExtraWidgets\Pricing_Table->features_section() #1 /www/htdocs/w017bff9/optiker-neukirchen-vluyn.de/wp-content/plugins/elementor/includes/base/controls-stack.php(1908): ThemeIsle\ElementorExtraWidgets\Pricing_Table->_register_controls() #2 /www/htdocs/w017bff9/optiker-neukirchen-vluyn.de/wp-content/plugins/elementor/includes/base/controls-stack.php(485): Elementor\Controls_Stack->init_controls() #3 /www/htdocs/w017bff9/optiker-neukirchen-vluyn.de/wp-content/plugins/elementor/includes/base/widget-base.php(160): Elementor\Controls_Stack->get_stack() #4 /www/htdocs/w017bff9/optiker-neukirchen-vluy in /www/htdocs/w017bff9/optiker-neukirchen-vluyn.de/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/pricing-table.php on line 271`

How do i get Elementor to work again ?

**Comment by shilo-ey** [comment]
This issue is related to the 3rd party extension Elementor Extra Widgets
Please contact the developer and let them know about it.

Thanks
