### ISSUE TITLE
Append Custom HTML Output Inside Elementor Main Sections

### ISSUE THREAD

**Issue by Oxibug** [elementor/elementor#13362]
Some people talking about this feature but it seems like they comfortable with your answers which are not suitable for my case.
https://github.com/elementor/elementor/issues/3591
https://github.com/elementor/elementor/issues/3334

## Prerequisites
- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In the previous issues they talking about adding controls in the section tab but What about the output? I need to add my own output INSIDE the section tag not before or after it.

I tried everything possible and search inside Elementor's plugin, I used the following:

Replace **{$element_type}** with **section**

Filter: **elementor/{$element_type}/print_template** located in **\elementor\includes\base\controls-stack.php** to Print out the backbone live output

Action: **elementor/frontend/{$element_type}/before_render** located in **\elementor\includes\base\element-base.php** Print out the final output for end-user

Unlike the action [**elementor/frontend/section/before_render**] the filter [**elementor/section/print_template**] append new html output inside the section correctly (That exactly what I need) But the action [**elementor/frontend/section/before_render**]  or [elementor/frontend/section/after_render] append the output before or after the boundaries of the section so I cannot style it with absolute positions or apply correct zindex because it makes all clickable items in the section unreachable,

### **--------- Solution 1 - Very Easy ------------**

- In function [**init_elements**] located in **Elements_Manager** class, We need you to add '$this' to action 'elementor/elements/elements_registered' to use the current class's function [**register_element_type**] to be like that:
`do_action( 'elementor/elements/elements_registered', $this );`

- Modify private functions to public [**get_html_tag**] and [**print_shape_divider**] located in **Element_Section** class in [section.php]
- Developer can add new controls using action **'elementor/element/section/section_advanced/after_section_end'** mentioned in the opened issues at the top.
- Now the developer can Extends the **Element_Section** class instead of create new section and override the functions [content_template], [before_render], [after_render]

To achieve that:
```
class ModifyElementorSection {

    public function __construct() {
        add_action( 'elementor/elements/elements_registered',         [ $this, 'modify_section' ] );
    }

    public function modify_section( $el_manager ) {        
        $el_manager->register_element_type( new TheNewSection() );
    }

}

class TheNewSection extends \Elementor\Element_Section {

    public function content_template() {
        /* Copy the Elementor's section and Modify|Add as you wish */
    }

    public function before_render() {
        /* Copy the Elementor's section and Modify|Add as you wish */
    }

    public function after_render() {
        /* Copy the Elementor's section and Modify|Add as you wish */
    }

}
```

### **--------- Solution 2 ------------**

My Suggested Solution is to add a new action inside the functions [**before_render**] and [**after_render**] located in [**\elementor\includes\elements\section.php**] directly after the section's open tag, For Example:

```
public function before_render() {
    $settings = $this->get_settings_for_display(); ?>

    <<?php echo esc_html( $this->get_html_tag() ); ?> <?php $this->print_render_attribute_string( '_wrapper' ); ?>>
        
        <?php do_action( "elementor/frontend/section/after_open_section", $this ); ?>

}

public function after_render() { ?>
    <?php do_action( "elementor/frontend/section/before_close_section", $this ); ?>

    </<?php echo esc_html( $this->get_html_tag() ); ?>>
    <?php
}
```

> Those suggested actions could be added after video and image backgrounds to be sure all new html tags will be above them even with relative positions so it will be suitable for all other developers' cases
> 

Thanks and Hope to add it because I'm stuck inside my code and make modification inside Elementor's plugin itself to achieve this.

**Comment by Oxibug** [comment]
@DorShahar @bainternet 

Hey Guys, 
I'm Waiting for any reply, Is that possible to make these changes? It's only a comma and a three words.

Thanks

**Comment by DorShahar** [comment]
Hi @Oxibug 
Our developers said that there is no official solution at the moment (due to the complication)
My suggestion is that you will send a PR, and our developers could dive into that and reply to your suggestion. 

Sorry for not having a conclusive solution.
Thanks

**Comment by Oxibug** [comment]
They know their plugin more than me but what complications!! You made a fully customizable plugin, I've some ideas must use the section not the columns, basically the action (elementor/elements/elements_registered) cannot be used, **this** must appended.
