### ISSUE TITLE
Filterable Gallery Call Stack Limit Exceeded

### ISSUE THREAD

**Issue by sebastianbiehl** [elementor/elementor#13365]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The filterable Gallery throws a "Callstack Limit Exceeded" Error when clicking on the filterable gallery tabs too often and too fast in a row. Over time, it causes the site to significally slow down and stop working altogether eventually.

This error is thrown in jQuery 3.5.1:2

## Steps to reproduce

Create new page
Add filterable Gallery widget
Click "preview site" and quickly alternate between the two existing tabs.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

##Details

Happens with newest jquery (jquery.min.js?ver=3.5.1:2)

**Comment by Aviad-Herman** [comment]
Hey,
this widget actually does not belong to Elementor, it belongs to a plugin called Essential Addons.
Unfortunately we can't help and you will have to take it up with them.
