### ISSUE TITLE
Elementor display language if from the wrong setting

### ISSUE THREAD

**Issue by YSRAZ** [elementor/elementor#13370]
Hello,

My site language is set to Hebrew, but my Wordpress language is set to English.
While all of my Wordpress menues are in English, when I edit a page, post or anything, all the Elementor menues are in Hebrew - the site language.
I would like there to be a separation between the site language (Hebrew - in my case) and the Elementor display language (English - in my case).

Thank you

**Comment by DorShahar** [comment]
Hi @YSRAZ 
Thank you for reporting.

This is not supported at the moment.
Please see #5148 last comments for workarounds.
