### ISSUE TITLE
Gutenberg blocks "Wide and Full-width" settings don't apply using the "Post Content" widget

### ISSUE THREAD

**Issue by tdechangy** [elementor/elementor#13389]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Building a single post template with the "Post content" widget, the content on frontend doesn't respect the wider widths (Wide and Full-width) configured per block (example for images).
Nothing has to be found to explain correct settings if it's not a bug, including @ https://elementor.com/help/single-post-site-part/

## Steps to reproduce
- Create a post with various block widths for testing.
- Test the post print on frontend with the theme default template, and then using all possible settings around a single post template as described below.
- Create a single post template using the Post content widget, without a sidebar.
- Tweak all possible settings to customise the container's widths, in Elementor and theme settings (without a sidebar), from boxed to 100% full-width. 
- let me know if you found the magic setup

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
<details>
Any kind
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
