### ISSUE TITLE
Review Elementor beta developer edition

### ISSUE THREAD

**Issue by Alasenaccion** [elementor/elementor#13384]
<!--  ## BEFORE POSTING YOUR ISSUE

- Picture is in the blank before posting when I creating a product page with woo commerce pictures despairs.

-

**Comment by DorShahar** [comment]
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
