### ISSUE TITLE
Add an HTML tag option to the widget text Button

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#13380]
![image](https://user-images.githubusercontent.com/56270626/102903981-60be2780-4471-11eb-9fe5-efee07eb9d53.png)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
