### ISSUE TITLE
Custom ordering of woocommerce product categories in page builder

### ISSUE THREAD

**Issue by salsa-system** [elementor/elementor#13381]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Current version of Elementor doesn’t have option to sort the woocommerce product categories in a custom order. It's only possible to order product categories by name, slug, description and count, which is not useful in many use cases.

**Describe the solution you'd like**
A solution would be to be able to select individual product categories and define the listing order.

**Describe alternatives you've considered**
An alternative solution would be to be able to map in Elementor the order of the product categories set in the woocommerce backend.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11412, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
