### ISSUE TITLE
Forms Steps

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#13391]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If the step has more than a few fields, when clicking 'next' or 'previous' on a form step, the browser does not go to the top of the form.

## Steps to reproduce

Create an Elementor form with 2 or more steps each containing enough form fields to cause the user to scroll.

**Comment by DorShahar** [comment]
Thanks for reporting, However, we couldn't reproduce the issue. 

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* System info.
* It will help us if you will add a video with the problem. 

Without it, we simply can't help.

Thanks.
