### ISSUE TITLE
Custom Attributes: Multiple Classes

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#13392]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allow one to add multiple classes to an element through Custom Attributes

**Describe the solution you'd like**
Perhaps allow multiple pipes to signal multiple class names being inputted?

**Comment by DorShahar** [comment]
Hi @zachkinsey 
You can add classes through Advanced > CSS classes. Just type the classes with space between them.
![image](https://user-images.githubusercontent.com/19154938/103166167-100b4d80-4828-11eb-8066-cfbed5b49a15.png)
![image](https://user-images.githubusercontent.com/19154938/103166193-4ea10800-4828-11eb-942e-7b5a3b20bb9f.png)

Cheers.

**Comment by zachkinsey** [comment]
That's not the same because it only adds the classes to a wrapper element.

For example, I needed to add multiple classes to an A tag in order for the button to interact with JavaScript etc. Couldn't do so because setting classes under the advanci tab doesn't set them in anything but the wrapper

**Comment by DorShahar** [comment]
Then you will need to use JS: `document.querySelector('YOUR ELEMENT').classList.add('YOUR CLASS')`
