### ISSUE TITLE
Additional Form Elements

### ISSUE THREAD

**Issue by brown7477** [elementor/elementor#13390]
I was creating a pretty big form and seen where there could be a couple more field types that could be added.
One of the things I wanted to see was Section Dividers to split the sections up.
I also would have like to have had the ability to add Headlines between Fields.
I guess this could be accomplished with a simple Section Field that has some options like Text, BG Color, BG Image, Etc.
It would have been nice to have been able to build the form like a page with different sections, columns, etc.
I was trying to duplicate this form page.
https://demo.vehicatheme.com/panel/?action=create_car
I really like how the gallery field and how the other fields look.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there @brown7477!

### 📢 This feature was released with Elementor Pro v2.10.0!

You can use the HTML field type and write your own headings (or add any static content you wish) to your forms. You can also use the Multi-step feature if you wish. 

Here are some articles you can follow to learn more:

https://elementor.com/help/form-fields/#:~:text=HTML
https://elementor.com/help/multi-step-forms/

For the time being, we have no plans to create separate fields for forms, or a form builder similar to the Popup builder, where you would edit the entire form as an Elementor template.

However, if you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
