### ISSUE TITLE
Flip Box Widget (Pro) – [ Background color ] option requested for Title & Description

### ISSUE THREAD

**Issue by projektorius96** [elementor/elementor#13402]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As far as I am experienced in front-end dev the pro widget option as requested i.e. [ **Background color** ] option for **Title & Description within Flip Box Widget (Pro)** should be configured on the back-end of Elementor/Wordpress. Currently  the [ **Background color** ] option is available only for Buttons.

**Describe the solution you'd like**
[ Background color ] option request for Title & Description within Flip Box Widget (Pro)

**Describe alternatives you've considered**
As far as I know CSS would not help in this scenario as it's done behind the scene.

**Comment by DorShahar** [comment]
Hi,
Thanks for reaching out.

Your use case is not clear to me. 

If you want to change the `background-color` for Title & Description, it will look like in the picture below, which not look good UI wise (I just targeted each element, and applied `background-color: orange;`) 
![image](https://user-images.githubusercontent.com/19154938/103267031-8ee3c000-49b9-11eb-8892-8659c5d889ba.png)

Could you attach a screenshot of the desired output? 
Thanks

**Comment by projektorius96** [comment]
@DorShahar 

Referring to my written code snippet on plnkr (URL below):
[dynamic-css-width.html](https://plnkr.co/plunk/3JM5z4tPFRsoJQ4m)

I can practically say that even using GUI controllers like Tweakpane@cocopon we can easily target width property within JS as a slider for custom values of the width applying same approach onto Elementor. I see nothing impractical here including the fact I present a practical example within presented URL above.

Thank you.
