### ISSUE TITLE
Add a dark mode class to Elementor panel when it is active

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#13419]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I develop a 3rd party add-on that adds some custom controls. Currently, there's no way to control its styling when dark mode is active. 

**Describe the solution you'd like**
A new dark mode class on `#elementor-panel` so we can add CSS selectors targeting that hierarchy for custom styling of controls when dark mode is active.

**Describe alternatives you've considered**
Hooking into the User Preferences' UI theme switcher, but it didn't quite work out.

**Comment by fabianenzensperger** [comment]
+1

**Comment by christianbrucki** [comment]
+1

**Comment by actionTurtle** [comment]
Yeah this would be awesome... I feel like its going to happen for sure but when is the question?

**Comment by fabianenzensperger** [comment]
> Yeah this would be awesome... I feel like its going to happen for sure but when is the question?

It's Elementor, so probably long. But no offense, I like to be taught better.

**Comment by jtsternberg** [comment]
Agreed, this makes styling custom widget icons very difficult, and nearly impossible to do in response to the UI toggle changing. Body class goes a long way.

**Comment by rami-elementor** [comment]
We are not planning to add this feature in the near feature.

But here is a workaround:

```php
$editor_preferences = Elementor\Core\Settings\Manager::get_settings_managers( 'editorPreferences' );
$theme_preference = $editor_preferences->get_model()->get_settings( 'ui_theme' );

// Dark mode
if ( 'dark' === $theme_preference) {
}

// Light mode
if ( 'light' === $theme_preference) {
}

// Auto detect based on OS preference
if ( 'auto' === $theme_preference) {
}
```
