### ISSUE TITLE
Loop template in theme builder for items

### ISSUE THREAD

**Issue by alfredo49** [elementor/elementor#13412]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor has a great limitation since it is not possible to create a template for the loop elements, for example in the shop page you cannot define how each of the products (loop item) is when they are all shown, the same happens when they are shown all blog posts or when you want to display any post type on a page. You cannot layout loop item to your liking. Is important to product archive pages, archive pages an other pages where you show post type items.

**Describe the solution you'd like**
Create a Loop tab in the theme builder where you can design different loop elements to use in products archive page, archive pages and other pages. These tabs should also be created in the theme builder

**Describe alternatives you've considered**
There are third-party plugins that do the job like Ele Custom Skin (https://wordpress.org/plugins/ele-custom-skin/), but ideally the functionality would be integrated into Elementor Pro and not depend on an external freelancer who can leave the project at any time.

**Comment by Aviad-Herman** [comment]
Hey, thanks for the idea.
We definitely have this on our sights but it's a fairly complicated feature and we don't know when exactly it will be implemented.

I'm merging this with issue #4440 so we'll have all the user input centralized in one place.

Thanks.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
