### ISSUE TITLE
Additional Menu Style/Advanced Portfolio Lightbox Options

### ISSUE THREAD

**Issue by mattrittman** [elementor/elementor#13429]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be nice if the mobile menu offered additional style options.
It would also be nice to be able to place YouTube videos in Portfolio grid elements.

**Describe the solution you'd like**
More styling options for the mobile menu. For example an off-canvas menu, or slide-in menu.
For the YouTube videos in Portfolio grid suggestion, it would be nice to have it show as a thumbnail just like the other images in a portfolio. When clicked, open a lightbox with the video.

**Describe alternatives you've considered**
The [Salient theme](https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266) on themeforest has a very nice mobile menu and portfolio grid element. You can see how this is working on my personal website: https://www.mattrittman.com/ The main problem with this theme however is that it uses the WPBakery builder, which has become somewhat dated and restricted in many other areas.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4787, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
