### ISSUE TITLE
TABS mess in Mobile when have 4 or more items.

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13445]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description

When you add more than 4 items on Tabs. Get messy on Mobile version.

![image](https://user-images.githubusercontent.com/68023943/103368696-fa578b80-4aa6-11eb-8fdb-1711313bbb00.png)

## Steps to reproduce

Add TABS then add more than 4 items. Check mobile version.

**Comment by DorShahar** [comment]
Hi @maurocarreraok 
Thanks for your report.
I couldn't reproduce it. 
Could you please share the system info?

**Comment by maurocarreraok** [comment]
Sure,

Here is all the info.

URL: https://elementor.maurocarrera.com/elementor-899/
Sys Info: https://pastebin.com/4Ag6PjYE
Page JSON: https://pastebin.com/Y9jk89hg

**Comment by DorShahar** [comment]
Hi
The bug been fixed and will be released in v3.1.0 

Thanks

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
