### ISSUE TITLE
TABS Background Color

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13444]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description

The TABS have an issue. There is no way to change the TAB TITLE background color. The BACKGROUND color change the TAB TITLE and CONTENT.

This should be one for TITLE and CONTENT.

**Comment by DorShahar** [comment]
Hi
 @maurocarreraok
