### ISSUE TITLE
No Dynamic Video on Section

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13446]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description

This should be working right? I checked and i cant find the Dynamic Video for Background on Sections.
![image](https://user-images.githubusercontent.com/68023943/103369013-d21c5c80-4aa7-11eb-843a-607c96e01b37.png)

**Comment by DorShahar** [comment]
Hi @maurocarreraok 
We never had this option. 

I'll mark it as enhancement, but this is not a bug.

**Comment by maurocarreraok** [comment]
Hi! I thought this was the enhancement.
![image](https://user-images.githubusercontent.com/68023943/103486334-e203ab80-4ddb-11eb-921c-90fff25f9382.png)

Anyway if you don't have it will be great :D Thanks!
