### ISSUE TITLE
Custom Columns Gap with Optimized DOM Output

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13443]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description

If you want to use the Custom Columns Gap and you don't have this option active "Optimized DOM Output" the Option in the editor will not work.

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.3.25
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://elementor.maurocarrera.com
	Home URL: https://elementor.maurocarrera.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.1.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.0.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.9
		Author: Elementor.com

	Ultimate Addons for Elementor
		Version: 1.28.1
		Author: Brainstorm Force

== Elements Usage ==
	
	header : 1
		button : 1
	wp-page : 34
		blockquote : 1
		button : 99
		call-to-action : 15
		counter : 7
		divider : 55
		flip-box : 23
		form : 5
		gallery : 3
		google_maps : 4
		heading : 325
		icon : 20
		icon-box : 52
		icon-list : 29
		image : 77
		image-box : 26
		image-carousel : 7
		image-gallery : 1
		media-carousel : 1
		menu-anchor : 9
		nav-menu : 1
		portfolio : 4
		posts : 31
		price-table : 3
		progress : 4
		search-form : 1
		slides : 1
		social-icons : 13
		spacer : 42
		testimonial : 11
		testimonial-carousel : 10
		text-editor : 141
		toggle : 1
		video : 7
	landing-page : 0
		google_maps : 1
		heading : 2
		text-editor : 2

== Log ==
	
PHP: showing 4 of 4PHP: 2020-08-30 18:27:38 [notice X 2][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-26 07:36:36 [notice X 1][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::154] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-13 18:37:05 [notice X 14][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-14 17:06:14 [notice X 11][/home/customer/www/elementor.maurocarrera.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::226] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152020-09-03 20:39:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.3',
)]
2020-09-03 20:39:51 [info] elementor::elementor_updater Started 
2020-09-03 20:39:51 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-03 20:39:51 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-03 20:39:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-09-03 20:39:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.4',
  'to' => '3.0.5',
)]
2020-11-06 01:20:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.13',
)]
2020-11-06 01:20:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.6',
)]
2020-11-26 07:23:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-11-26 07:23:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-12-13 18:43:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.7',
  'to' => '3.0.8',
)]
2020-12-17 15:04:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.1.0-dev2',
)]
2020-12-18 13:40:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0-dev2',
  'to' => '3.1.0-dev3',
)]
2020-12-21 20:22:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0-dev3',
  'to' => '3.1.0-dev4',
)]
2020-12-30 16:46:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]

JS: showing 5 of 5JS: 2020-12-17 15:04:51 [error X 17][https://elementor.maurocarrera.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=5.6:2:31670] Cannot read property \'landingPagesHasPages\' of undefined 
JS: 2020-12-17 15:04:51 [error X 8][https://elementor.maurocarrera.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=5.6:2:31670] elementorAdmin is not defined 
JS: 2020-12-17 15:05:12 [error X 1][https://elementor.maurocarrera.com/wp-content/plugins/elementor/assets/js/beta-tester.min.js?ver=3.1.0-dev2:2:23495] elementorBetaTester is not defined 
JS: 2020-12-17 15:13:13 [error X 2][https://elementor.maurocarrera.com/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:31670] Cannot read property \'elementWrappers\' of undefined 
JS: 2020-12-18 14:27:34 [error X 3][https://elementor.maurocarrera.com/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=5.6:2:31670] Cannot read property \'option_enabled\' of undefined 

				
</details>

**Comment by DorShahar** [comment]
Hi 
This bug fixed and will be released in v3.1.0

Thanks!

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
