### ISSUE TITLE
 Email form - Create and save user in Wordpress as selected user role

### ISSUE THREAD

**Issue by tdechangy** [elementor/elementor#13451]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add the ability to use local notification systems

**Describe the solution you'd like**
When a user fills a newsletter form, create and save him/her in Wordpress using a selected user role.

**Describe alternatives you've considered**
I don't know many good plugins to do that job, especially since I thought that Elementor include it.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1686, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
