### ISSUE TITLE
URGENT! | Popups Not Closing

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13469]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Hi,

I have a huge issue in every single website witch had a Popup with the X button to close... None of them closes on Mobile.

In desktop and tablet is working as expected, but when you go to Mobile do not work at all.

Im using a Pixel 3XL with Chrome. And i tested this as well in a Samsung Galaxy and is not working as well.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.3.25
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://www.alcurro.com
	Home URL: https://www.alcurro.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.6.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.32
		Author: ServMask

	Elementor
		Version: 3.0.15
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.9
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.5.3
		Author: Crocoblock

	MainWP Child
		Version: 4.1.3.1
		Author: MainWP

	Media Cleaner (Pro)
		Version: 6.1.2
		Author: Jordy Meow

	Screets Live Chat
		Version: 2.9.3
		Author: Screets

	Site Kit by Google
		Version: 1.23.0
		Author: Google

	TranslatePress - Multilingual
		Version: 1.9.0
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	UpdraftPlus - Backup/Restore
		Version: 1.16.43
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.4.14
		Author: Wordfence

	WP Activity Log
		Version: 4.1.5.1
		Author: WP White Security

== Elements Usage ==
	
	header : 1
		button : 1
		icon-list : 1
		image : 1
		nav-menu : 1
		social-icons : 1
	page : 2
		button : 1
		form : 1
		heading : 3
		icon-list : 1
		image : 2
	popup : 2
		button : 2
		divider : 2
		heading : 6
		icon-box : 2
		icon-list : 1
		text-editor : 1
	wp-page : 5
		button : 4
		form : 1
		heading : 6
		icon : 2
		image : 4
		jet-animated-text : 1
		text-editor : 4

== Log ==
	
PHP: showing 1 of 1PHP: 2020-12-04 00:09:24 [notice X 1][/home/customer/www/alcurro.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2020-12-17 04:28:02 [error X 1][https://www.alcurro.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:13466] An \"el\" undefined must exist in DOM 
JS: 2020-12-20 22:41:37 [error X 1][https://www.alcurro.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:22:19954] View (cid: \"view79486\") has already been destroyed and cannot be used. 

Log: showing 2 of 22020-12-22 03:06:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.15',
)]
2020-12-30 15:52:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]

				
</details>

**Comment by DorShahar** [comment]
Hi @maurocarreraok 
Please contact our support - they could help you. 

Please try to disable the other plugins and check the console in chrome emulator if you have any errors.

**Comment by maurocarreraok** [comment]
frontend.min.js:2 Uncaught TypeError: Cannot read property 'size' of undefined
    at n.value (frontend.min.js:2)
    at n.value (frontend.min.js:2)
    at n.value (frontend.min.js:2)
    at frontend.min.js:2
