### ISSUE TITLE
More Options to Menu Styling 

### ISSUE THREAD

**Issue by StammDXB** [elementor/elementor#13461]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when trying to create a modern Menu. It doesn't contain an option to retract the menu when the user scrolls down. It doesn't allow me to style the menu offering the click instead of only hovering. I can not add an icon to the menu or the dropdown options.

**Describe the solution you'd like**
Having more styling options without using JetElements for example.

**Describe alternatives you've considered**
JetElements plugin

**Additional context**
I'm still looking for solutions without coding.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
