### ISSUE TITLE
Why is there still no Tik Tok icon available? No $ icon?

### ISSUE THREAD

**Issue by Needforname** [elementor/elementor#13475]
I updated the Font Awesome icon library when it became available and was excited that a bunch of new needed icons would become available. Yet I'm surprised of how few new icons there seem to be. Actually, I'm not really noticing anything new. Is it possible my icons never updated with the update a few months ago? How do I tell? I thought for sure there would be a Tik Tok icon, considering it's one of the top social media platforms. My clients ask for me to include a Tik Tok icon amongst their social media links. There's also no icons for commonly used symbols (like the $ for example) and no cohesive outline icon sets. I realize I can create my own icons or find them elsewhere and upload them, but this is quite time consuming; especially when trying to match the particular style of the existing Font Awesome icons. 

I also find the icon library to be quite dated looking. I think most of your customers would agree (if you did a poll), that the most desired, modern and versatile icons for today are outline style icons. They provide a sense of uniformity, can be mimicked easily when creating custom icons to match in style, and they just look minimalist and modern. It would be great if Elementor could work a deal with an icon company to provide a more extensive collection of icons for your customers. Please consider, and in the mean time please add some of the missing icons if possible (dollar symbol, Tik Tok icon, etc). Thank you kindly.

**Comment by Aviad-Herman** [comment]
Hi,
We use Font Awesome icons.
Currently our library is a bit outdated as you mentioned. 
I will pass this internally. For now you can upload icons manually. For example here is one for TikTok: https://fontawesome.com/icons/tiktok?style=brands
