### ISSUE TITLE
Table of Content is not loading because of error 'Cannot read property 'id' of null'

### ISSUE THREAD

**Issue by drosa88** [elementor/elementor#13494]
Currently the Table of content widget is not loading. There is an infinite loading spinner. The console outputs the following error in `elementor-pro/assets/js/frontend.min.js`:

`Cannot read property 'id' of null`

Is this a known issue? The Elementor and Elementor Pro versions are the newest. Also the WordPress Core version.

**Comment by DorShahar** [comment]
Thanks for reporting,

I couldn't reproduce the problem that you have. 

In general, please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.
If the problem continues - please open a new issue with the points above, or contact our support. 

Thanks.
