### ISSUE TITLE
The elementor pro theme builder can't seperate the single product page view correctly.

### ISSUE THREAD

**Issue by whygit2000** [elementor/elementor#13497]
I got more than one shop manager for my woocommerce site with elementor builder.
The theme builder come with the function of seperate the view of single product page by setting the display condiction.
However, there will be problem when doing this.
For example:
I create a single product page A1 for shop manager A's product page with red sytle.
then create a single product page B1 with blue sytle for shop manager B.
then I set the A1 page 's display condiction by including all author and exclude B's product.
and also seting the B1 page properly.
However, it's just can't display separetely view for different product create by  different author.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.17
	PHP Version: 7.4.13
	PHP Max Input Vars: 100000
	PHP Max Post Size: 999M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	
	WP Multisite: No
	Max Upload Size: 999 MB
	Memory limit: 5120M
	Permalink Structure: /%postname%/
	Language: zh-CN
	Timezone: Asia/Shanghai
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: zh_CN
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	Advanced Database Cleaner
		Version: 3.0.3
		Author: Younes JFR.

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Contact Form 7
		Version: 5.3.2
		Author: Takayuki Miyoshi

	Contact Us all-in-one button
		Version: 1.9.9
		Author: Areama

	Disable Cart Fragments
		Version: 1.21
		Author: Optimocha

	Easy WP SMTP
		Version: 1.4.5
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 3.0.15
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.9
		Author: Elementor.com

	JetMenu
		Version: 2.0.8
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.7.4
		Author: Crocoblock

	LiteSpeed Cache
		Version: 3.6.1
		Author: LiteSpeed Technologies

	Media Library Folders for WordPress
		Version: 6.0.6
		Author: Max Foundry

	Site Kit by Google
		Version: 1.23.0
		Author: Google

	WC Product Author
		Version: 1.0.1
		Author: Nitin Prakash

	WooCommerce
		Version: 4.8.0
		Author: Automattic

	WooCommerce Multilingual
		Version: 4.10.4
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.4.8
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.6
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.10.4
		Author: OnTheGoSystems

	Yoast SEO
		Version: 15.5
		Author: Team Yoast

	Yoast SEO: WooCommerce
		Version: 13.7
		Author: Team Yoast

	Yoast SEO Multilingual
		Version: 1.2.4
		Author: OnTheGoSystems

== Elements Usage ==
	
	footer : 3
		heading : 12
		icon-list : 4
		social-icons : 2
		text-editor : 4
		theme-site-logo : 2
		wp-widget-tag_cloud : 2
	header : 2
		heading : 8
		icon-list : 4
		jet-mega-menu : 1
		menu-anchor : 2
		nav-menu : 1
		search-form : 2
		theme-site-logo : 2
		wpml-language-switcher : 2
	page : 3
		divider : 2
		eael-post-block : 1
		heading : 4
		icon-box : 3
		social-icons : 1
		text-editor : 3
		wp-widget-woocommerce_product_categories : 1
		wp-widget-woocommerce_product_tag_cloud : 1
	popup : 5
		divider : 2
		form : 2
		heading : 2
		text-editor : 4
		woocommerce-product-title : 2
	product : 3
		button : 4
		divider : 7
		eael-adv-tabs : 1
		gallery : 3
		heading : 9
		social-icons : 3
		tabs : 2
		template : 3
		woocommerce-breadcrumb : 3
		woocommerce-product-data-tabs : 3
		woocommerce-product-images : 3
		woocommerce-product-related : 3
		woocommerce-product-short-description : 3
		woocommerce-product-title : 3
		wp-widget-woocommerce_product_categories : 3
		wp-widget-woocommerce_product_tag_cloud : 3
	section : 8
		breadcrumbs : 1
		divider : 3
		eael-adv-tabs : 1
		form : 1
		gallery : 1
		heading : 4
		share-buttons : 1
		social-icons : 1
		text-editor : 2
		woocommerce-product-title : 1
		wp-widget-woocommerce_product_categories : 1
		wp-widget-woocommerce_product_tag_cloud : 1
	widget : 0
		icon-list : 11
		image : 3
		woocommerce-product-add-to-cart : 12
	wp-post : 1
		heading : 1
		jet-woo-products-list : 1
		search-form : 1
		text-editor : 1
	wp-page : 27
		breadcrumbs : 10
		button : 4
		divider : 6
		eael-adv-tabs : 1
		eicon-woocommerce : 1
		form : 2
		gallery : 4
		google_maps : 1
		heading : 42
		icon-box : 11
		icon-list : 3
		image : 14
		image-carousel : 2
		jet-woo-products : 5
		login : 1
		slides : 2
		social-icons : 2
		spacer : 7
		tabs : 1
		template : 8
		testimonial-carousel : 1
		text-editor : 26
		theme-site-logo : 1
		video : 4
		woocommerce-products : 2
		wp-widget-woocommerce_product_categories : 2
		wp-widget-woocommerce_product_tag_cloud : 2
	single-post : 1
		author-box : 1
		heading : 2
		post-comments : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		template : 2
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
	product-archive : 1
		divider : 4
		form : 1
		heading : 3
		icon-box : 1
		social-icons : 1
		theme-archive-title : 1
		wc-archive-products : 1
		wp-widget-woocommerce_product_categories : 1
		wp-widget-woocommerce_product_tag_cloud : 1

== Log ==
	

Log: showing 15 of 152020-11-19 13:52:01 [info] elementor::elementor_updater Started 
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-11-19 13:52:01 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-11-19 13:52:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '3.0.13',
)]
2020-11-19 13:52:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '3.0.13',
)]
2020-11-19 14:04:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.2',
  'to' => '3.0.6',
)]
2020-12-22 14:30:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.15',
)]
2020-12-22 14:48:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.8',
)]
2021-01-05 21:50:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]

				
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
