### ISSUE TITLE
`elementor_pro/forms/new_record` hook not invoking

### ISSUE THREAD

**Issue by YaakovHatam** [elementor/elementor#13500]
Consider the following code inside `functions.php`:

```php
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	$ajax_handler->data['output'] = "hello";
}, 10, 2 );
```

and i see in the response (network tab at developer tools) the response:
```javascript
{"success":true,"data":{"message":"The form was sent successfully.","data":[]}}
```

the data array is empty, so, i guess, the hook dont work. what can be the problem?

**Comment by j-ender-garcia-us** [comment]
I have the same problem. How did you solved it?
