### ISSUE TITLE
Please add JetBrains Mono to Google Fonts list

### ISSUE THREAD

**Issue by mrtopf** [elementor/elementor#13501]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
JetBrains Mono is missing from the fonts list although it is a Google font. I added it myself to `elementor/includes/fonts.php` but that's not so update proof. There also might be more fonts missing (maybe there is a script to sync them?)

**Describe the solution you'd like**
Well, add it :-)

**Describe alternatives you've considered**
Uploading it manually.

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!
