### ISSUE TITLE
Currency symbol after amount in Price Table

### ISSUE THREAD

**Issue by savevjr** [elementor/elementor#13519]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Some currency symbols have to be placed after the amount.
In the widget Price Table (Pro) the currency symbol of the **original** amount cannot be configured.

The discount price shows the currency symbol correctly after the amount (because this is configurable there), but the original price (strikethrough) shows the currency before the price.

**Describe the solution you'd like**
The currency symbol configuration should be applied on both **original price** and **discount price**.

**Describe alternatives you've considered**
I didn't find any alternative solutions.

**Additional context**
A screenshot is worth a thousand words:
![image](https://user-images.githubusercontent.com/1876727/103875724-753e2900-50db-11eb-81d4-49081b8c1d35.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.3.0

Feel free to update

Thanks!
