### ISSUE TITLE
Slider not working as intended

### ISSUE THREAD

**Issue by glassesUSA** [elementor/elementor#13510]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

On mobile browsers the slider jumps between slides and the images don't span the full width.

## Steps to reproduce

1. Insert a slider in an elementor page
2. Insert images
3. Observe on mobile what happens when you click

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://hastebin.com/qewotalofi.yaml
</details>

**Comment by TheoFreud** [comment]
The issue seems to happen when you slide with your finger rather then clicking the buttons

**Comment by DorShahar** [comment]
Hi @glassesUSA 
Thanks for reaching out. 

Our QA team tried to reproduce the bug, without any success. 
If the problem still continues, please reach out to our support team with system info (not only the site: plugins, theme, OS, etc'). 

Thanks
