### ISSUE TITLE
Broken Image Icon error in both Preview and Live modes

### ISSUE THREAD

**Issue by Mediatonic-Shelley** [elementor/elementor#13515]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

<summary>Getting the Broken Image Icon error in both Preview and Live modes. In Elementor editor the images display, but in preview it's the broken image icon. Also, when I publish it anyway then it gets stuck loading (there's a cancel preloaded button) and when you click that it has the same broken images. 

Additional troubleshoot step: Theme designer said this is likely and https/http loop but host (Bluehost) confirmed it's all on https and not looping. 

Note: Same issue as (#12419) Theme builder image previews are broken - but they dropped off the thread so it was closed before resolved. 

![Screen Shot 2021-01-05 at 12 49 30 PM](https://user-images.githubusercontent.com/77072894/103809006-d9eb7c00-5026-11eb-9ea8-beec0c2b72f7.png)
![Screen Shot 2021-01-06 at 1 29 06 PM](https://user-images.githubusercontent.com/77072894/103809010-da841280-5026-11eb-91d6-d76886e0d3b7.png)

</summary>

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info: WordPress 5.6  Chrome  Mac OSX 10.15.7</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by Mediatonic-Shelley** [comment]
We had gone thru "support" and were getting nowhere that's why we were honing in on a "bug". Sorry if asking for trouble shooting tips fell into support category. Anyway we got to the solution! 

Posting in case anyone else comes across this. 

It turned out - and even Elementor says this is "very rare" + the preview bug wasn't detecting this because the preview was loading (just not everything). So that was kind of buggy. ;) It was an issue on the settings in the .htacess was conflicting with Elementor. Now set htaccess as the default of WordPress and working well.
