### ISSUE TITLE
Screen Width Pixel Measurement in Editor / Snap sidebar to breakpoints

### ISSUE THREAD

**Issue by JMartinCollins** [elementor/elementor#13520]
When resizing the editing side panel in the elementor editor, it would be nice if the main page display area would provide feedback about the current width of the page in pixels(such as a little tooltip that only appears while resizing). This would be handy for testing breakpoints on multiple screen widths.

For example this would help to test when inline elements within a container would be pushed to a new line on slightly narrower screen resolutions, such as on a Microsoft Surface device. 
![image](https://user-images.githubusercontent.com/61546355/103885188-95410d00-511a-11eb-9c86-f2bce7133da9.png)

The standard three breakpoint sizes(desktop, tablet, mobile) are not sufficient to make a page fully responsive on every device. One possible implementation would be to have a toggle button in the editing sidebar to "Snap" the editor bar width at certain screen widths when resizing the sidebar, such as the screen widths listed in the image above, and notify me with a quick tooltip on the screen which describes the device and pixel width at which the page display has been snapped. 

I mean sure, I know there are plugins that do similar things, but how nice would it be to just click once and drag the editor side panel and quickly sweep through all possible breakpoints in one fell swoop! [Rather than clicking twice to check each one]

**Comment by DorShahar** [comment]
Hi 
Part of your suggestion will take place in the Additional breakpoints project.

---

I merged this issue with  #2043 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
