### ISSUE TITLE
Link an element setting to Global settings (allow content to unlink)

### ISSUE THREAD

**Issue by ericholter** [elementor/elementor#13529]
[x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The new global style sheets are wonderful to link color and font settings. But there are many other settings which are set on a per instance basis. We would like to be able to link a particular instance of an element's setting to a global (or template) parent, but for its settings only (allowing for the content to be changed while maintaining a link to the parent settings).  

Brainstorm Force's UAE product has a "UAE Copy" and "UAE Paste" which allows settings from one instance of an element to be quickly applied to another. We would essentially like to use that kind of mechanism, but maintaining a permanent connection from an instance of an element back to the settings of the Global/Template parent.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by black-eye** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issuehttps://github.com/elementor/elementor/issues/19232 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
