### ISSUE TITLE
enqueue elementor font-awesome to my plugins

### ISSUE THREAD

**Issue by unikforceit** [elementor/elementor#13527]
wp_enqueue_style('font-awesome'); is not working as elementor/frontend/after_enqueue_styles with  a add action

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
