### ISSUE TITLE
Can't select Popup list under action

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#13521]
I am running Elementor Version 3.1.0-beta1 and Elementor Pro 3.0.9 - System Info and Image Attached. 

When adding Popup as the action from a button or link Popup is added as the "link content" but the 'dynamic content icon' is shown instead of the normal 'wrench icon' (see image) and you cannot select which popup you want to open. Under "Experiments" I have Optimised DOM, Improved Asset Loading, Accessibility Improvements and Landing Pages all active.
--

[system-info-elementary.websitesdesigned4u.com-04-01-2021.txt](https://github.com/elementor/elementor/files/5781381/system-info-elementary.websitesdesigned4u.com-04-01-2021.txt)
![Screenshot-2021-01-04-161451](https://user-images.githubusercontent.com/22448787/103889196-ee3e8000-50dd-11eb-95c6-bf1941e00695.png)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #13257, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
