### ISSUE TITLE
✈️ 🚀 Feature Request: More Space for Page Titles When Setting Up More Complex Template Display Conditions (Migrated/Merged with #22143)

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#13525]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

There's a very little room for the page name, when you set up more complex conditions.

Here is the example for setting a condition for one particular child page:

![obrazek](https://user-images.githubusercontent.com/5634870/103908451-c877a200-5102-11eb-8113-17bf112a8482.png)

As you can see, there's not much left of the page name. The page name is "Jazykové kurzy na dálku", the title tries to show the name including the parent page: "Individuální jazykové kurzy > Jazykové kurzy na dálku".

When you have to add several particular pages like this to the condition list, you have no idea, what's written in the list (especially, when the pages have the same or similar parrent) .

**Describe the solution you'd like**
Make the whole section wider - there's a lot of space for it there.

**Describe alternatives you've considered**
Hovering over the file names and trying to decipher what's written there (including html entities).

**Comment by nicholaszein** [comment]
Hi there,

### ✈️ This Feature Request has been merged and migrated with #22143  

if you still think this request should be considered for our roadmap, please cast your **⬆️ Upvote** on the first comment.

Happy voting! 🙂
