### ISSUE TITLE
Break CSS and JS into modularly assembled files

### ISSUE THREAD

**Issue by cshanejennings** [elementor/elementor#13533]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

This issue appears similar to https://github.com/elementor/elementor/issues/8572 on the surface, but is fundamentally different in it's effect and architectural implications.  This is a big ask, but please hear me out as this issue might warrent executive review.

**What problem is your feature request going to solve? Please describe.**
With the google user experience algorithm update coming in May, things like First Contentful Paint (FCP), Largest Contentful Paint (LCP), Flashes of Unstyled Content (FOUC), etc are going to create a nightmare matrix of optimazation concerns for end users that I don't think can be solved through current optimization plugins like WP Rocket or Asset Cleanup.

This new ranking signal is going to create a sudden and urgent shift towards load speed optimization, lightweight html, css and js payloads, etc.  This could cause a mass exodus from content builders until these problems are solved and that deadline is approaching fast.  This probably should be on your radar if it's not already.

I'm trying to optimize my site via SEMRUSH and I'm down to fixing load time problems.  After gradually chipping away at the warnings, I think I've reached the limits of the current state of the plugin and my site is full of slow load-time warnings and I know this is coming from elementor's html scaffolding and the excess CSS / JS.

The only real complaints I have myself and from what I can see in the FB groups are around bloat.  I use the pro-version, an astra theme and powerpack.  I did some testing and based on what I'm seeing in chrome / lightouse I'm only using about 15% of the code or so.  This comes out to over 1Mb MINIFIED...  I'm not sure about the exact number, but I believe I'm only using 300k or so of the associated CSS / JS.  I've built browser based application builders before that consumed a JSON manifest (KickApps back in 2013), so I truly understand reducing the HTML bloat is probably not an option.  ..however, please see my suggestion below for resource loading.

**Describe the solution you'd like**
I would like to suggest that modules have the option to be turned on and off based on the user's preference similar to powerpack with one additional side-effect.  Break the js and css up into module and core files that get concatonated into a generated file before registering them to be enqueued.  This can all be controlled via an application manifest / file generation engine that shouldn't be too hard to create or be a burdon to maintain if it's done well.

I made a small react / js demo to illustrate the concept in the browser here: https://codesandbox.io/s/dreamy-chaum-28t3v?file=/src/App.js .  I understand this does not completely solve the problem and the manifest will also need to have some information about sequence, etc but I think this small addition is well worth the payoff.

I realize this example is over simplified, but I think the concept will open your product up to SEO houses that might not otherwise take a page builder seriously due to bloat and make elementor an even more serious contendor in the wordpress marketplace.

**Describe alternatives you've considered**
The only thing I've found that's close to this is the WP plugin Asset Cleanup, but this is a blunt instrument and doesn't solve the problems that come from large blocks of dormant code in large, concatonated files.  As best I can tell, there's no out of the box solution for solving this problem.

**Additional context**
Concept illustration here: https://codesandbox.io/s/dreamy-chaum-28t3v?file=/src/App.js

**Comment by jazir5** [comment]
https://toolkitforelementor.com/

Does this accomplish what you're looking for?

**Comment by shilo-ey** [comment]
This feature has been added to Elementor v3.3.0

Feel free to update

Thanks!

**Comment by adrewetx** [comment]
It's great to see this and other CSS/JS improvements in the latest 3.3.0 elementor.

Do you have any advice on how we configure Cloudflare, Siteground, WP-Optimise to leverage the new functionality?  e.g.  Will these caching tools recognise the more dynamic operation of Elementor?   Do we have to force a cache refresh following update, or should sites now be configured with CSS cached off?  and does this then mean we lose modification?
