### ISSUE TITLE
Section shape divider bug 

### ISSUE THREAD

**Issue by projektorius96** [elementor/elementor#13530]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description
Section-shape-divider-bug screenshot (_link presented below_) describes the situation. If shape divider on sections selected (_top / bottom_), seems that if decided to switch it off by selecting **none** It leaves strange triangle-like shape line of the section width as some kind of rendering bug. Cannot be remove even if page is reloaded within Editor. 

[section-shape-divider-bug](https://flic.kr/p/2kq2exn)

## Steps to reproduce
Create section apply Shape divider save changes applied, than remove shape divider selecting on **none** within Section Style

## Steps to solve 
Create fresh (_not copy_) of section within the same template copy paste the content from buggy section to new section. Voila. Job is done. Some would say it's not a bug. Opposite, it's a bug like day and night! What if every tiny little detail was applied to section as well via UI? Coping such would copy buggy divider as well. Depends on situation. I am kindly requesting Developers to consider this issue.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
[Current system info](https://pastebin.com/raw/1e3645pr)
</details>

**Comment by DorShahar** [comment]
Hi @projektorius96 
Thanks for reaching out. 
I couldn't reproduce the bug, and the link you attached is invalid so I can't see the problem on your end.

If the problem persists, you are welcome to contact our support or open a new issue with more information (like browser, system info live versions, plugins, theme, and so on).

Thanks.
