### ISSUE TITLE
Error Coming when loading builder

### ISSUE THREAD

**Issue by Tronic247** [elementor/elementor#13549]
Warning: Undefined array key "pro_widgets" in C:\xampp\htdocs\wp-content\plugins\elementor\includes\api.php on line 160
This error will show when elementor is loading 
![Screenshot_2021-01-10 Menus ‹ dds — WordPress](https://user-images.githubusercontent.com/76736580/104117892-c7d14c80-534a-11eb-99d9-d45b1779347b.png)

**Comment by DorShahar** [comment]
Hi @Tronic247 
Does the problem still happen? 
If yes - can you provide system info?

**Comment by notrealdev** [comment]
Hi @DorShahar , i got same here
`wp-content\plugins\elementor\includes\api.php line 160`
```
public static function get_promotion_widgets() {
	$data = self::get_info_data();
	var_dump( $data ); // empty array();

	return $data['pro_widgets'];
}
```
![Imgur](https://i.imgur.com/Qemopdx.png)
![Imgur](https://i.imgur.com/BQvHDyj.png)
