### ISSUE TITLE
Tabular view of all theme conditions

### ISSUE THREAD

**Issue by Mramorov** [elementor/elementor#13546]
Hello,

I would like to be able to somehow quickly see which element of the theme is used where? That is, what conditions are involved for which element, it would be great to have some kind of general tabular view.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by Mramorov** [comment]
Hello,

 

It seems to me that the topic of the ticket  <https://github.com/elementor/elementor/issues/4246> #4246 is not exactly what I had in mind. Perhaps my English is not good enough)

I would just like to be able to quickly view the conditions for applying different blocks of the theme (without going into edit mode each time), like I sketched it in the figure.
