### ISSUE TITLE
Unable to remove "processing circle" in submit button in elementor forms

### ISSUE THREAD

**Issue by hackzie** [elementor/elementor#13548]
I am using elementor forms widget. Is there any way to remove this processing circle, which appears after clicking the submit button?
Please help! Check the attached video.

https://drive.google.com/file/d/1AW1nV0ANzOExsUIQq6u4lsqnIIlqT8hl/view?usp=sharing[](url)

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
