### ISSUE TITLE
Table Of Contents Not Working Properly

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#13540]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

In an Elementor Theme part (Singular post) I have a Table Of Contents setup to be sticky in a sidebar and jump to my h2's and h3's. 

It is not working properly and you can view the walkthrough here: https://share.getcloudapp.com/yAuZRbZ7

Website: https://gogogo.rocks

## Steps to reproduce

Go to Episodes in nav
Click on an episode
Scroll down to content
Watch TOC not work.

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: Percona Server (GPL), Release '12', Revision '7ddfdfe' v8.0.21-12
	PHP Version: 7.3.24-3+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://gogogo.rocks
	Home URL: https://gogogo.rocks
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.3
		Author: Elliot Condon

	Cloudflare
		Version: 3.8.7
		Author: Cloudflare, Inc.

	Ele Custom Skin
		Version: 3.0.0
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.0.16
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.9
		Author: Elementor.com

	Happy Elementor Addons
		Version: 2.18.0
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 1.13.1
		Author: weDevs

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 7.48.85
		Author: HubSpot

	ManageWP - Worker
		Version: 4.9.7
		Author: GoDaddy

	Nginx Helper
		Version: 2.2.2
		Author: rtCamp

	SEOPress
		Version: 4.2.1
		Author: SEOPress

	SEOPress PRO
		Version: 4.2.2
		Author: SEOPress

	ShortPixel Image Optimizer
		Version: 4.21.1
		Author: ShortPixel

	ToolKit For Elementor
		Version: 1.2.2
		Author: ToolKit For Elementor

== Must-Use Plugins ==
	GridPane Mailer
		Version: 1.0.0
		Author: Chad Butler, Jeff Cleverley

	GridPane Nginx Cache Purger
		Version: 1.0.0
		Author: Jeff Cleverley Jebat

	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy

	WP CLI Login Command Server
		Version: 1.2
		Author: Evan Mattson

== Elements Usage ==
	
	archive : 1
		heading : 1
		posts : 1
	footer : 1
		form : 1
		heading : 2
		icon-list : 2
		image : 3
		text-editor : 1
	header : 1
		button : 1
		icon : 1
		image : 1
		nav-menu : 1
	loop : 1
		heading : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	page : 1
		posts : 1
	popup : 3
		heading : 1
		icon-list : 2
		image : 1
		share-buttons : 1
		text-editor : 6
		wp-widget-tag_cloud : 1
	section : 3
		button : 2
		heading : 2
		icon : 4
		icon-list : 4
		image : 1
		text-editor : 2
		video : 2
	wp-page : 3
		button : 1
		divider : 1
		heading : 2
		icon : 2
		icon-list : 2
		image : 2
		posts : 1
		text-editor : 5
		video : 1
	single-post : 1
		button : 2
		divider : 2
		heading : 3
		icon : 1
		post-info : 3
		table-of-contents : 1
		theme-post-content : 1
		video : 1

== Log ==
	
PHP: showing 5 of 5PHP: 2020-11-11 19:34:07 [notice X 13][/var/www/gogogo.rocks/htdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-12 00:46:23 [notice X 6][/var/www/gogogo.rocks/htdocs/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1988] Undefined index: button_icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-12 00:46:30 [notice X 3][/var/www/gogogo.rocks/htdocs/wp-content/plugins/elementor/includes/widgets/button.php::555] Undefined index: icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-12 02:19:54 [notice X 7][/var/www/gogogo.rocks/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-12 23:44:26 [notice X 24][/var/www/gogogo.rocks/htdocs/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2020-11-12 01:18:41 [error X 2][https://gogogo.rocks/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.0.6:1:2683] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2020-11-12 03:59:33 [error X 8][https://gogogo.rocks/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.13:2:62775] e.get is not a function 
JS: 2020-11-13 19:48:12 [error X 1][https://gogogo.rocks/wp-admin/post.php?post=92&action=elementor:1:7] Unexpected token \')\' 
JS: 2020-11-13 19:48:15 [error X 4][https://gogogo.rocks/wp-admin/post.php?post=92&action=elementor:26:6] Invalid regular expression: missing / 
JS: 2020-11-13 19:48:20 [error X 1][https://gogogo.rocks/wp-admin/post.php?post=92&action=elementor:7:31] Cannot read property \'scrollHeight\' of undefined 
JS: 2020-12-13 23:36:36 [error X 1][http://staging.gogogo.rocks/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:13466] An \"el\" undefined must exist in DOM 
JS: 2021-01-08 00:06:11 [error X 2][https://gogogo.rocks/:210:23] Cannot read property \'substr\' of undefined 
JS: 2021-01-08 22:06:35 [error X 3][https://gogogo.rocks/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.16:2:131271] Cannot read property \'error\' of undefined 
JS: 2021-01-08 22:12:49 [error X 5][https://gogogo.rocks/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.16:2:131269] r is undefined 

Log: showing 5 of 52020-12-01 18:28:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-12-01 18:29:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.0.8',
)]
2020-12-21 17:38:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.15',
)]
2021-01-04 19:41:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-07 00:44:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]

				
</details>

**Comment by shilo-ey** [comment]
Hi @tickyboom 

Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to Hello Theme (or other default WordPress theme).


And see if the issue still persists.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


Thanks.
