### ISSUE TITLE
There should be a way to do middots and the like between items in a nav bar without custom css

### ISSUE THREAD

**Issue by snelzing** [elementor/elementor#13544]
Clients often seem to want decoration for their nav bar, but you have to be quite the expert in CSS to get custom css to select the correct item. I figure there should be a way to skip devs having to do the work and make it a feature in Elementor.

Example:

<img width="889" alt="Screen Shot 2021-01-04 at 10 26 20 AM" src="https://user-images.githubusercontent.com/39928924/104086978-5e5a1c80-522a-11eb-899e-582bf40b0e85.png">

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
