### ISSUE TITLE
Optimize Elementor code

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13554]
Hello, please optimize your HTML and CSS code, for exemple Oxygen generate small code, while the element creates a lot of extra lines, oxygen and without a caching plugin shows a high page load speed, why can't you have this, you have a huge number of solutions, you are almost perfect but there is a problem with the code, why you do not solve it ?

**Comment by promocot** [comment]
![Elementor code](https://user-images.githubusercontent.com/66754335/104126427-2a374680-5365-11eb-9931-b49c73a9aab1.jpg)

**Comment by promocot** [comment]
![elementor code 2](https://user-images.githubusercontent.com/66754335/104126433-302d2780-5365-11eb-9c05-735cf7bdc49e.jpg)

**Comment by promocot** [comment]
and oxygen code

**Comment by promocot** [comment]
![oxy code](https://user-images.githubusercontent.com/66754335/104126442-3d4a1680-5365-11eb-8408-0ddd9e449777.jpg)

**Comment by promocot** [comment]
269 vs 75 string of code, i create page with one button and save and what i see in code without optimize? and in google page speed in mobile version i get 56 point elementor vs 94 point oxygen. Is terrible work with code

**Comment by tobias992** [comment]
HaHa... oh man... you are a funny guy. Elementor is Open Source - you can optimize the Code by yourself. You are also free to use any other Page Builder on the market.

Since 3.0 there are much performance improvements under the hood (reduced DOM and optimized CSS). Now with 3.1 there are also big JS improvements. In my mind these are great steps...

All my Websites (at the moment 73) are build with Elementor and all has best performance scores and are super fast. Also WooCommerce Shops with more than 1.000.000 views per day -> no Problem.

**Comment by promocot** [comment]
> HaHa... oh man... you are a funny guy. Elementor is Open Source - you can optimize the Code by yourself. You are also free to use any other Page Builder on the market.
> 
> Since 3.0 there are much performance improvements under the hood (reduced DOM and optimized CSS). Now with 3.1 there are also big JS improvements. In my mind these are great steps...
> 
> All my Websites (at the moment 73) are build with Elementor and all has best performance scores and are super fast. Also WooCommerce Shops with more than 1.000.000 views per day -> no Problem.

For better reduce DOM, elementor team must fix flex-wrap for PC, in tablet or mobile mode colum width work 1) 50%, 2) 50%, 3) 100%, 4) 50%, 5) 25%, 6) 25%, that would not use additions for this or code using values for sections selector .elementor-container .elementor-row {
     flex-wrap: wrap;
}

and write for any colum selector{
    width:100%;

}
/* Media Query - Tablet */
@media (min-width: 768px) and (max-width: 1024px) {
	selector {
		width: 60%; /* or whatever you like */
	}
}
/* Media Query - Mobile */
@media (max-width: 767px) {
	selector {
		width: 100%; /* or whatever you like */
	}
}

and add manual colum order for any devices, for exemple i have 6 colum, and on mobile i want second colum make first, if i use reverse, my last colum will be first..

This is a small thing that can be done to make the code smaller and will not be affected by the plugin code.

**Comment by promocot** [comment]
and i know how reduce DOM in construction page, use correct widget and flex trick, for example i need to create 3 block with title and description with white BG and shadow. Beginner elementor user will be create section with 3 column and add 3 title and 3 text editor... this way not better for reduce DOM.. my solution - use 3 Image list (and remove image) and in column settings horizontal alignment select - space between... and you optimize code...If you multiply this by what I wrote above, the code will be greatly reduced (but these are property fixes + skillful page layout and understanding how everything works, since many do not know all the tricks with flex properties

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10329, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
