### ISSUE TITLE
Allow CSS grid to collapse empty columns (fill available width)

### ISSUE THREAD

**Issue by gnowland** [elementor/elementor#13558]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When there isn't enough content available to fill grid columns the columns don't resize to fit the content -- the content is unnecessarily smushed into a fraction of the available space on one side of the page, leaving a bunch of empty whitespace to the other side... this isn't very "responsive" as it needs to be because query filters can cause total number of objects returned to be < available columns.

## Steps to reproduce

1. Add "Posts widget".
2. If there are 2 posts available set columns to >= 3
3. See the 2 posts crammed onto the left half of the page, with the right half empty

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
- Any system setup will exhibit this behavior, as this is a CSS Issue
</details>

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #7624 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

----

Since at the moment, we have no solution for that, try to use one of the code snippets in the thread and modify the box container. 

Sorry for the inconvenience.

**Comment by gnowland** [comment]
@DorShahar are you sure that's the right issue number? It doesn't appear to me that the linked issue has anything to do with what this issue/PR is addressing... am I missing some reference to CSS Grid columns in that issue? It would appear to me that #7624 is about when there are 0 posts available, while this one is for instances when there ARE posts available, but less than the number of columns specified. Please advise?

**Comment by DorShahar** [comment]
Hi @gnowland 
Sorry for the disinformation. 
We are looking at the problem as a whole - I mean that if we will able to know the number of posts in the response (answer from the query), compared to what the user requested, we will be able to do more complex layouts, and enable to the user to do which configuration (code, layout) he/she wants.

As for the code - maybe you can hardcode the situation, inject classes and control the layout (it will be rendered in the preview).

You can also consult in one of the [Facebook groups](https://www.facebook.com/groups/Elementors/). 

Thanks.
