### ISSUE TITLE
Custom motion transition easing timeline

### ISSUE THREAD

**Issue by laurentcrombe** [elementor/elementor#13552]
I would like to suggest the creation of a mini timeline motion-based tool like adobe Animate but included to Elementor maybe based on a system like gsap that allow to do custom easing like Easing Expo, Easing Bounce, etc.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
