### ISSUE TITLE
Play sound on popup

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [elementor/elementor#13557]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like someway of playing a sound like a "ding" whenever a popup appears.

**Describe the solution you'd like**
When the popup appears, an ogg or mp3 file would play automatically.

**Describe alternatives you've considered**
I am not really sure about any alternatives that would work with elementor.

**Comment by shilo-ey** [comment]
Hi 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


Thanks for the feedback.
