### ISSUE TITLE
Compatibility Tag Dev edition 3.2.0-dev1

### ISSUE THREAD

**Issue by chichille** [elementor/elementor#13555]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description
I don't see the compatibility alert message under the Dev edition 3.2.0-dev1 (screenshots)

**Plugin header**
* Author: EAC Team
* Version: 1.6.5
* Elementor tested up to: 3.1.0

### Question
Can you confirm that the functions
**_content_template and _register_controls**
are hard deprecated with 3.2.0-dev1 edition.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
Wordpress 5.5.3
PHP 7.3.21
Elementor Dev edition 3.2.0-dev1
</summary>
</details>

##  Alert message Dev edition 3.1.0-dev4

![CompatibilityTag_v310](https://user-images.githubusercontent.com/74245284/104125818-87c59600-5359-11eb-8d02-bb37ecf92b08.png)

## Vs Dev edition 3.2.0-dev1
![CompatibilityTag_v320](https://user-images.githubusercontent.com/74245284/104125958-497ca680-535a-11eb-8aaf-8ef8589e75f9.png)

**Comment by DorShahar** [comment]
Hi
`content_template` will be hard deprecated in v3.3.0
`_register_controls` will be hard deprecated in v3.4.0

At the moment, the functions are soft-deprecated. 

What are you trying to do?

**Comment by Aviad-Herman** [comment]
Hi @chichille,
The alert only shows before upgrading to a major version and only via the plugins screen.

If you want to see the current compatibility tags of your plugins you can do so under Elementor --> System Info.
 
![image](https://user-images.githubusercontent.com/73067562/104186066-b4fe5c80-53ca-11eb-9d68-ca37b2164e1e.png)

If I misunderstood you, please let me know and I'll reopen the issue.
