### ISSUE TITLE
Section Background Video 1px Gap

### ISSUE THREAD

**Issue by tissi-2** [elementor/elementor#13556]
When using a background video for a section there is a 1px gap on the left side within the section.
In my case the video has an even px width, and the gap will be shown with an odd elementor-background-video-container width.
When using an additional fallback image, this gap is showing the 1px part of the fallback image. 

Wordpress 5.6
Elementor 3.0.16
Elementor Pro 3.0.9
Firefox 84.0.2

**Comment by boylaban** [comment]
I've seen this issue. Theme doesn't matter. It seems to be a Firefox only issue, it works fine on Chrome.

For example: Screen width is 1920px, the video element background is only 1903px on Firefox but 1920px on Chrome.

**Comment by fiaew** [comment]
Is there some workaround, maybe with custom css, to fix this issue?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
