### ISSUE TITLE
 [Human memory bug] I forgot what I did to rename the button elementor..

### ISSUE THREAD

**Issue by neosaveme** [elementor/elementor#13569]
I have a loss of memory or a bad handling done in any case I can no longer make it work,
during my exploration of different possible designs.
I managed to get the button to change text during a show / hide a section
![Sans titre](https://user-images.githubusercontent.com/75816572/104255020-66a79700-5478-11eb-83c6-2ca543a099e0.png)

I will trace what i did and put all the codes i tried one of them worked but i didn't save it in a note ..
if you know where the fault is tell me. you can also test

at the beginning I went to see this [elementor page](https://elementor.com/help/button-widget/)

after I tried this

```
/* Show/hide rename button text  */ 
    $(document).ready(function(){
        $("#TEST_BTN").click(function(){
            $(this).text($(this).text() == 'show contact' ? 'hide contact': 'show contact')
            $('#hidden-content').slideToggle('250','swing','hide');
        });
    });
```

then that

```
/* Show/hide rename button text  */      
document.addEventListener("DOMContentLoaded", function(event) {
  jQuery('#TEST_BTN').click(function(){
  event.preventDefault();
      $(this).text($(this).text() == 'show contact' ? 'hide contact': 'show contact')
      jQuery( '#hidden-content' ).slideToggle('250','swing','hide');
  });
}); 
```

after that

```
/* Show/hide rename button text  */ 
jQuery(document).on('click', '#TEST_BTN', function(event) {
     event.preventDefault();
    $(this).text($(this).text() == 'show contact' ? 'hide contact': 'show contact')
          $('#hidden-content').slideToggle('250','swing','hide');
     });    	
```
it's terrible I don't remember what I did ...
at least I have the method 2  working

```
/*Show/Hide Remove button*/	
jQuery(document).on('click','#TEST_BTN',function() {
  jQuery('#hidden-content').slideDown('230','swing','hide');
  this.remove();
});
```
**Edit :**  

well I found my mistake and recovered my memory

now it works well :)

```
/* Show/hide rename button text  */ 
    jQuery(document).ready(function($){
        $("#TEST_BTN").click(function(){
            $(this).text($(this).text() == 'show contact' ? 'hide contact': 'show contact')
            $('#hidden-content').slideToggle('250','swing','hide');
        });
    });
```

now you know how to rename the text of the button
who knows ? maybe it will give ideas to the elementor team...

**Comment by shilo-ey** [comment]
Hi @neosaveme 

Glad you managed to make this work

You can find additional information about how to replace text here:
https://stackoverflow.com/questions/21459599/jquery-change-text-on-click-also-change-back

```
jQuery ("#fold") .click (function () {
    if (jQuery (this).children ("#fold_p").text() == "Fold it") {
            jQuery (this).children ("#fold_p").text("Expand It");
    }
    else {
         jQuery (this).children ("#fold_p").text("Fold it");        
    }
});
```
