### ISSUE TITLE
Please Add Word-Wrap to the Code Highlighter Widget

### ISSUE THREAD

**Issue by Worldwebscapes** [elementor/elementor#13577]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest development version of Elementor.

## Description

I really like the new Code Highlight Widget. Could it be possible to add a word wrap toggle to this so the horizontal scroll may be eliminated? 

![image](https://user-images.githubusercontent.com/7572038/104363785-b2dbf100-54e3-11eb-931c-133882fd1195.png)

## Steps to reproduce

Add a Code Highlighter Widget with code. Must use a horizontal scroll to see all of the code.

## Isolating the problem

- [ X] This bug happens with only the Elementor plugin active (and Elementor Pro) with development versions.
- [X ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

Local Install/NGINX/PHP 7.4.1/SQL 8.0.16/WP 5.6

**Comment by Worldwebscapes** [comment]
I submitted this via the Developer version but seems to have not been flagged as a developer feature request
.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
