### ISSUE TITLE
Almost all my pages on www.pilgroupconsulting.com are not visible since last night

### ISSUE THREAD

**Issue by JesusCariel** [elementor/elementor#13585]
On my website www.pilgroupconsulting.com with the expecion of my home page all the others are no longer visible and they give me the messages that I attach below in screenshots, I am not a programmer or anything, install and create elementor because I thought it was simple but this scares me that the whole page is literally down with the 404 error, please help

[

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi
Please attach system info and console error (use Chrome Dev tools) - without it, it will be hard to help you.
If you are a Pro user - you can contact our support. 

Thanks

**Comment by JesusCariel** [comment]
Excuse me, I already attached the screenshots and explain the error
well, I think you do not read and answer automatically and not very
empathetically, in the end, not reading does not solve anything, what
a terrible support really. Thank God I was able to solve it by other
means other than the support of elementor, what irony and what
disappointment

**Comment by DorShahar** [comment]
@JesusCariel 
I requested the **Console Error**, and not the UI Errors - since I can show it to our developers. They contain more info (Stack trace, which points to the problematic file) and the info in English and not Spanish. 

I'm sorry to hear that you are disappointing. 
With that being said, GitHub is for bugs and feature requests, but we try to help our users in this platform as well.

All the best.
