### ISSUE TITLE
Please add Epilogue to Google Fonts list

### ISSUE THREAD

**Issue by mdfoo8** [elementor/elementor#13595]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Epilogue is missing from the fonts list although it is a Google font.

**Describe the solution you'd like**
Well, add it :)

**Describe alternatives you've considered**
Uploading it manually.

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.4

Feel free to update!

**Comment by mdfoo8** [comment]
Good! Thank you
