### ISSUE TITLE
Javascript in Pop-up 

### ISSUE THREAD

**Issue by Angiolettocoppola** [elementor/elementor#13597]
Hi, i  want to open a booking form in javascript in elementor popup but it dosn't work.
This is my code:
`<script type="text/javascript"> (function (i, s, o, g, r, a, m) { i['SBSyncroBoxParam'] = r; i[r] = i[r] || function () { (i[r].q = i[r].q || []).push(arguments) }, i[r].l = 1 * new Date(); a = s.createElement(o), m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m) })(window, document, 'script', 'https://cdn.simplebooking.it/search-box-script.axd?IDA=1234','SBSyncroBox'); </script>`

To load a booking form in a page i use this html code: `<div id="sb-container"></div>`

Please can you help me with right code for function.php file. Thanks

**Comment by DorShahar** [comment]
Hi @Angiolettocoppola 
Is there an Error thrown?

**Comment by Angiolettocoppola** [comment]
No, the booking bar inside the pop-up is simply not loaded, I think the javascript function in the pop-ups is disabled!? When I am in the backend editor of elementor it works regularly but from the frontend it is not loaded

**Comment by DorShahar** [comment]
Hi guys,
Try to work with these API :
https://developers.elementor.com/elementor-pro-2-7-popup-events/ 

If there is a problem, please open another issue at the link to that.

Good luck
