### ISSUE TITLE
Media Carousel needs the ability to add Youtube Video Controls

### ISSUE THREAD

**Issue by donsimon505** [elementor/elementor#13596]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The media carousel hides video controls for YouTube by default whereas it is sometimes useful or needed.

**Describe the solution you'd like**
The ability to customize settings for the embedded player like choosing if I prefer controls as controls=0, controls=1 or controls=2.

**Describe alternatives you've considered**
Can't see an alternative other than changing the default elementor module behaviour in core files which will break at next update. In case adding more options is not your choice for bloating purpose, making youtube player parameter a possible custom attribute to the media carousel would provide users which want this feature a way to interact without changing core files and without adding any gui options to use them.

**Additional context**
Other options as provided by youtube parameters would be great as color, autoplay, fullscreen button etc…

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9747, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
