### ISSUE TITLE
Add Signal and Threema to Share Buttons Widget

### ISSUE THREAD

**Issue by gawins** [elementor/elementor#13607]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Due current trend to switch from Whatsapp Messenger to alternative services there should be the availibility to add share buttons for Signal and Threema (Telegram is already added, thanks for that).

**Describe the solution you'd like**
Add Signal and Threema to Share Buttons Widget

**Comment by Aviad-Herman** [comment]
Hi,
We use FontAwesome icon library and unfortunately they do not have the icons you specified.
https://fontawesome.com/icons?d=gallery&s=brands

The only solution for now is uploading your own icon.

Sorry for the inconvenience.
