### ISSUE TITLE
Multiple Global Buttons and Global Anchor Link styling

### ISSUE THREAD

**Issue by mac10046** [elementor/elementor#13602]
Cannot make multiple Global buttons like CTA (Call to Actions) - only one is possible on the global - Tried using section but its a bit difficult to do that

Anchor Links Styling can be done globally - with Normal, Hover and clicked states options

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
