### ISSUE TITLE
Responsive Pictures (Not with backgrounds)

### ISSUE THREAD

**Issue by tt89player** [elementor/elementor#13601]
Why isn`t it possible to make pictures responsive? Right now, the only way is to use backgrounds, which is not always possible. 
For example use Original size for Desktop, cropped 768px for tablet and cropped 360px for mobil. With Google enforcing mobil as the main ranking factor, it is sad when my big sized pictures, which are great for desktop, are the same KB size for mobil. 
Or that you can add pictures for the different devices on your own, like with backgrounds. 
![Responsive Pictures-Medium-Quality](https://user-images.githubusercontent.com/77539336/104815277-dcfb1f00-5813-11eb-99d7-1b557ef131e1.jpg)

**Comment by DorShahar** [comment]
Hi @tt89player ,
Thanks for reaching out.
The best practice is to define the with of the image in percentages. In this way, you can keep the image aspect ratio. 
Therefore, go to Style > width > and define it by %. 

BTW - we have thought to change the image loading size according to the device (as in Android Studio for example). but for now, this is the solution. 

Thanks

**Comment by samuelgoldenbaum** [comment]
> Hi @tt89player ,
> Thanks for reaching out.
> The best practice is to define the with of the image in percentages. In this way, you can keep the image aspect ratio.
> Therefore, go to Style > width > and define it by %.
> 
> BTW - we have thought to change the image loading size according to the device (as in Android Studio for example). but for now, this is the solution.
> 
> Thanks

Sorry, but this is not acceptable and should be reopened. 

A desktop image for modern devices will be substantially larger - why would you send all your desktop media down to a mobile client? 

If your answer had any merit, why were responsive background images added then?

Incredibly frustrating to have elementary issues like this sidelined.

**Comment by samuelgoldenbaum** [comment]
I have started a [Custom Widget](https://github.com/samuelgoldenbaum/elementor-responsive-image) for this.
