### ISSUE TITLE
Staging issue with new license activation

### ISSUE THREAD

**Issue by amateur-rc** [elementor/elementor#13603]
I'm writing this in case anyone else has the same issue using siteground hosting of wordpress sites. I had my live site as wpbakery and was setting up my staging with Elementor and Elementor pro with a new theme. When I went to activate the license for Elementor pro I kept getting redirected to the live site which only had wp-bakery. In the end I had to install Elementor on the live site then Elementor pro then activate the license. Then I deleted the Elementor pro folder from staging and copied the Elementor folder from live to staging site. activated the staging site. Then I manually reset the license using instructions from
https://github.com/elementor/elementor/issues/8667
Go to
your site domain/wp-admin/admin.php?page=elementor-license&mode=manually
It will bring up the old manual license entry box.

This finally worked for me. Hope it helps anyone else with the same issue.

**Comment by Aviad-Herman** [comment]
Cool, thanks for sharing!
I'm not sure if relevant but this may be another solution:
https://elementor.com/blog/elementor-expands-license-to-include-staging-sites/

I marking this issue as closed. I hope it will help many people to come!
