### ISSUE TITLE
sticky header duplicated

### ISSUE THREAD

**Issue by mfranji** [elementor/elementor#13608]
![لقطة الشاشة 2021-01-18 080038](https://user-images.githubusercontent.com/13570545/104879596-d29d6a00-5966-11eb-8ca2-ed5cda6b88b2.jpg)
i create a header template and save the condition to entire site,
but when i open the home page i found that is 2 header section on the page (the same header but duplicated on the same page) how to fix that?

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues are not for support.

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by sotosbic** [comment]
same problem here

**Comment by iamthemovie** [comment]
@shilo-ey there's clearly a bug with this - we're having the same issue and your community, support and knowledge base are coming up empty. 

The source generated on the page is duplicated, this means we end up with a fixed header and sticky header on our instance. 

I've reviewed this in depth and it looks this is an issue when selecting sticky header, using display conditions and select mobile, desktop tablet.

We pay for Elementor Pro but it would be fantastic if you could help me understand what is going on so a) my marketing team can get our new site launched b) this helps other people get to the issue.

1. Elementor Pro - setup a header template
2. Set it to sticky like so:
![image](https://user-images.githubusercontent.com/369020/114886666-a2e3ee00-9dff-11eb-9bb7-f8c839ba895b.png)
3. Set display conditions on entire site
4. Witness duplicate headers one sticky and one that moves with the page

Is this meant to happen if so why?
