### ISSUE TITLE
HTML Export Option

### ISSUE THREAD

**Issue by zmedia786** [elementor/elementor#13617]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? 
I'm always frustrated when we have to design the page in elementor and can't export html

**Describe the solution you'd like**
I need html export button so all website designs are exported in html.

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4417, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
