### ISSUE TITLE
SVG Image Export Doesn't Work!

### ISSUE THREAD

**Issue by khan-rafin-ahmed** [elementor/elementor#13628]
I am facing a strange issue when trying to import templates which contains SVG Images/Icons. The Imported SVG Images don't show at all.

Strangely enough, the link URL shows wrong in the media as well. Instead of showing the media file like this: https://example.com/wp-content/uploads/2021/01/cesta-llena.svg

It shows the following (which is wrong): https://example.com/cesta-llena-svg-2/

Here's the screenshot: https://d.pr/i/iXOGxx

So, is this a known issue? I have tried this on few different sites and kept all the plugins deactivated except for Elementor & Elementor PRO.

Looking forward to hearing back from you soon. Thank you!

**Comment by shimsa** [comment]
Try it with this code in theme functions.php

// Enable Media Library upload for additional mime types
function additional_mime_types( $mimes ) {
  $mimes['svg'] = 'image/svg+xml';
  $mimes['svgz'] = 'image/svg+xml';
  return $mimes;
}
add_filter( 'upload_mimes', 'additional_mime_types' );

**Comment by khan-rafin-ahmed** [comment]
@shimsa,

Thanks for the suggestion. However, it looks like an Elementor bug and need this to be resolved from within the plugin.

**Comment by drawcard** [comment]
Once you have imported the template, have you checked to see if each Image widget is set to "Full" size? If it's set to other sizes (eg. Thumbnail 150x150) the SVG may not render.

**Comment by DorShahar** [comment]
Hi everyone
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by abid112** [comment]
Hi @DorShahar ,

I found the same issue actually.
Please have a look at this video: https://d.pr/v/VXN7Xr

You can use this SVG: https://d.pr/f/dGFEUz

Thank you!
