### ISSUE TITLE
FEATURE REQUEST - Slidershow and Slider Widget Responsive Images

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13637]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add the possibility to add different images on different breakpoints.

![image](https://user-images.githubusercontent.com/68023943/105351942-01684a00-5bcc-11eb-989d-b3d5d5c7cdc1.png)
![image](https://user-images.githubusercontent.com/68023943/105352021-1ba22800-5bcc-11eb-8e07-33ba60eef5a2.png)

**Comment by maurocarreraok** [comment]
Hi @DorShahar @shilo-ey how are you? There is any comment about this? Thanks!

**Comment by DorShahar** [comment]
Hi @maurocarreraok 
I'm good buddy, Thanks :) 
You can do this functionality in Advanced > Responsive > Visibility. 
So create 3 sections (or widgets) with different images, and display them in the relevant breakpoints.

Note that it may affect the page performance.  
If we will see more requests like this  - we will consider changing the workflow.  

Thanks

**Comment by maurocarreraok** [comment]
> Hi @maurocarreraok
> I'm good buddy, Thanks :)
> You can do this functionality in Advanced > Responsive > Visibility.
> So create 3 sections (or widgets) with different images, and display them in the relevant breakpoints.
> 
> Note that it may affect the page performance.
> If we will see more requests like this - we will consider changing the workflow.
> 
> Thanks

Hi @DorShahar Glad that you are Ok!

Yes, I know how can I do this now BUT... Is kinda complicated if you have for example 2 languages... Because in that case I will need for example 3 Widgets multiplied the amount of languages.

I think this should be proposed or pinned to add "different" images for different "breakpoints" instead of duplicate the widget as many times.

Just saying! Thank you!

**Comment by shilo-ey** [comment]
ref: #9719
