### ISSUE TITLE
BUG - The page template does not apply to the page declared as "Archive Pages" in the Wordpress settings.

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#13645]
1- Create a template and apply it to all pages, making sure that the page is declared as Archive in the Wordpress settings.
2- In our page declared archive (so our old articles put together), notice that the model does not apply.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #13718, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
