### ISSUE TITLE
Doesn't work with Twenty Fourteen

### ISSUE THREAD

**Issue by dugo3number2** [elementor/elementor#13648]
Yesterday, while I was at school looking at themes for my website with Elementor as the front page, I found out that part of my front page was hidden behind the sidebar.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

As for your issue - try switching theme to a more modern and clean one or adjust your appearance using Elementor Theme Builder.

Thanks.
