### ISSUE TITLE
data-elementor-device-mode error switch

### ISSUE THREAD

**Issue by alexhien** [elementor/elementor#13642]
My site is: https://laura-sunshine.com/
Iam using mobile and click chat button, and then close chat the responsive data-elementor-device-mode="mobile" change to "tablet" . (iam still using mobile device). How to fix it ? 
Thanks
Best regards.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.


Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support.**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Thanks.
