### ISSUE TITLE
Safari and Elementor bug

### ISSUE THREAD

**Issue by kiliancreative** [elementor/elementor#13640]
Link to video - https://youtu.be/RLNvQalI_cE

Color box not refreshing.

1. Using safari add a text element to a page.
2. Change the text color and the color box does not update.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
