### ISSUE TITLE
Add google sheet integration

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#13656]
Hello, please add the ability to upload data for filling out forms in a google sheet. Today this is possible only through special services or add-ons, which are mostly useless and needed only for the sake of one function. Side decision is unnecessary waste and influence of third-party code on the site.

How to do it ? in the same way as you added api for other services

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10999, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by wes1337** [comment]
IS there any update here?

I don't see this feature in Elementor Pro. A simple way to export all form entries to Google sheets should exist like many other free form builders.
