### ISSUE TITLE
divider widget - mobile width not support it 

### ISSUE THREAD

**Issue by yaron86** [elementor/elementor#13662]
i made a divider and set the width to 10px 
but there is no way to set the with to 3px on mobile

would love to see it fixed in the future please

**Comment by DorShahar** [comment]
Hi @yaron86 
Thanks for reaching out.

I couldn't reproduce the problem.
If the problem continues, please open a new ticket with a short video or screenshot.  
If you are a Pro user, you are welcome to contact our support. 

Thanks
