### ISSUE TITLE
iFrame not working on Elementor pages

### ISSUE THREAD

**Issue by Medienor** [elementor/elementor#13661]
When i add "HTML" into Elementor pages and copy paste this:

<iframe width="100%" height="650px" frameborder="0" src="https://fornye.speedtestcustom.com"></iframe>

The entire screen is white, and nothing occurs on live site. Can't see iframe on edit mode, or live mode.

Please help.

**Comment by icarlosmendez** [comment]
@Medienor, 
I just implemented the use of an iframe today to get the Calendly interface into one of my pages. I used the shortcode widget and then just put my HTML code in the content box (if you call it that) and it worked great. Try using the shortcode widget and see what happens. Good luck!

**Comment by Barnabas2** [comment]
Hi, I've been trying this iframe code myself that I got from goodreads

`<div id="goodreads-widget">
  <iframe sandbox id="the_iframe" src="https://www.goodreads.com/api/reviews_widget_iframe?did=DEVELOPER_ID&format=html&header_text=Goodreads+reviews&isbn=0951278649&links=BF9b30&min_rating=4&num_reviews=8&review_back=ffffff&stars=bf9b30&stylesheet=&text=000" width="575" height="400" frameborder="0"></iframe>
  <div id="gr_footer">
    <a class="gr_branding" target="_blank" rel="nofollow noopener noreferrer" href="https://www.goodreads.com/book/show/51298303-we-shall-see-him-as-he-is?utm_medium=api&utm_source=reviews_widget">Reviews from Goodreads.com</a>
  </div>
</div>
    `

It shows in editing mode but not when I publish and preview. I tried the Text, Shortcode and Html widgets. Nothing seems to work

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by Barnabas2** [comment]
@cristian1991 Thank you so much! ❤️
It's exactly what it needed to work. I added the folowing as a code snippet and all is working now.

add_filter( 'wp_kses_allowed_html', function ( $tags, $context ) {
if ( 'post' === $context ) {
$tags['iframe'] = array(
'id' => true,
'src' => true,
'width' => true,
'height' => true,
'frameborder' => true,
);
}
return $tags;
},10,2);

**Comment by jayecreates** [comment]
This still didn't work for me using Code Snippets. Are there any other solutions?

**Comment by subhasish-smiles** [comment]
Any solution so far? It is not working for me. Thank you in advance!

**Comment by wireinet** [comment]
The same. 
I put iframe to html widget and all site below - is crashed.
Delete iframe - all alright again.
No matter what is inside the src, even if there is nothing ""
I am disappointed in elementror ( it would be better to write a website without it

**Comment by wireinet** [comment]
Take my word back )
I fint the solutuion in my case.
Elementor dont like trailing solidus as it told in the html editor as error. I just rewrite gived code to write...</iframe> insted just  />
