### ISSUE TITLE
Version 3.2.0-dev2 | Version 3.1.0-dev1 and Woocommerce My account page

### ISSUE THREAD

**Issue by ratnaksl** [elementor/elementor#13664]
With the above version, the links on my account page will not work on woocommerce
They will not work even if you put url direct
They work once optimized DOM and Improved Asset loading is disabled
![3 2 error](https://user-images.githubusercontent.com/64305166/105653897-e60a8100-5ee2-11eb-8a2f-8c54c7feaae0.png)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @ratnaksl 
Please provide more info, like console errors, Steps to reproduce, and system info so we can reproduce the issue. 
What kind of errors do you get?
It is also recommended to attach a short video.

Thanks

**Comment by ratnaksl** [comment]
This is very easy to reproduce Themes Astra or 2021Woocommerce  4.91Elementor dev 3.2Elementor pro dev 3.1With optimized DOM output and improved asset loading enabled Woocommerce endpoints for my account section stops working Even typing the url directly doesn't workI do not want to reproduce this again on my staging  as only way out of me for it was to do a complete new wordpress  installTomorrow  I will do it on a local test environment and send it across RegardsRatna KariyawasamNo20 6th LaneAraliya UyanaDepanama PannipitiyaCO 10230Sri LankaTel:+94112850686Mobile:+94777349859
-------- Original message --------From: Dor_S <notifications@github.com> Date: 25/01/2021  12:16  (GMT+05:30) To: elementor/elementor <elementor@noreply.github.com> Cc: ratnaksl <ratnak78@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [elementor/elementor] Version 3.2.0-dev2 | Version 3.1.0-dev1 and Woocommerce My account page (#13664) 
Hi @ratnaksl
Please provide more info, like console errors, Steps to reproduce, and system info so we can reproduce the issue.
What kind of errors do you get?
It is also recommended to attach a short video.
Thanks

**Comment by shilo-ey** [comment]
Thanks, but we couldn't reproduce your issue in several environments.

Please try to reproduce it and share the system info and steps to reproduce with us.

Thanks

**Comment by shilo-ey** [comment]
@ratnaksl Can you please try to deactivate the Landing Pages experiment and let us know if it solved the problem in your case?

Thanks

**Comment by ratnaksl** [comment]
HiI did it as requested and its resolved.I now have all woocommerce pages active  When landing page experiment is inactive the woocommerce end points work even through firs two experiments are active Now my experiments page is as attached  Ratna KariyawasamNo20 6th LaneAraliya UyanaDepanama PannipitiyaCO 10230Sri LankaTel:+94112850686Mobile:+94777349859 From: shilo-eySent: Wednesday, January 27, 2021 9:48 PMTo: elementor/elementorCc: ratnaksl; MentionSubject: Re: [elementor/elementor] Version 3.2.0-dev2 | Version 3.1.0-dev1 and Woocommerce My account page (#13664) @ratnaksl Can you please try to deactivate the Landing Pages experiment and let us know if it solved the problem in your case?Thanks—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DorShahar** [comment]
Hi 
We glad that the problem resolved.

Thanks.
