### ISSUE TITLE
✅ 🔃 🚀 Feature Request: Select own icon for Menu Cart Widget (Pro) - [ED-7187]

### ISSUE THREAD

**Issue by SdVGits** [elementor/elementor#13678]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
So far it is not possible to choose my own icon for the Menu Cart Widget (Pro). This limits mine a bit and I would be happy if a selection were possible, as with the other widgets. 

**Describe the solution you'd like**
The same selection options as with the other widgets in which icons can be used.

Thank you for reading my feature request!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
