### ISSUE TITLE
Widget Tabs - Alignement

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#13683]
At the time of the JUSTIFIED alignment of the navigation bar of the Tabs widget, the text moves to the left, which is not very nice, it is possible to add a condition to be able to center the text when the navigation bar is set to justified.

**Comment by DorShahar** [comment]
Hi @rodolphebertozzo 
please open a feature request at we asked, or (in your case) you can send a PR ... 

Listing here the template and closing the issue. Thank. 

[A new feature request templae can be found here](https://github.com/pojome/elementor/issues/new?template=Feature_request.md).
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
