### ISSUE TITLE
 Editing a widget in a post affects all other posts. I don’t want that.

### ISSUE THREAD

**Issue by Caspoor** [elementor/elementor#13686]
So,

I’ve created a single post template for posts, when I try to edit a widget in a SPECIFIC post separately, I find ALL other posts affected and edited in the same way.

Is there a way to edit a specific widget without affecting the other posts?

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
