### ISSUE TITLE
Posts widget: Current query unable to order by title

### ISSUE THREAD

**Issue by jordanjustkidding** [elementor/elementor#13688]
Hello,

I’m creating a glossary of terms on a website, and using a custom post type (Glossary) and custom taxonomy (Letters). I need the posts in these archives to be ordered by title, instead of by date.

On the archive template I’m using a posts widget with ‘current query’. **By default the posts are ordered by date and there is no option to change the order (all options are removed with Current Query).** _– Feature request to add options to change order of posts here._

I’ve set up a custom query to order the posts by title, instead of by date. However, I cannot seem to get it work.

My code is:

```
add_action( 'elementor/query/pre_get_posts', function ( $query ) {
if ( ! is_admin() && $query->is_archive() && $query->is_main_query() ) {
if ( get_query_var( 'post_type' ) == 'glossary' ) {
$query->set( 'category_name', 'letter' );
$query->set( 'posts_per_page', -1 );
$query->set( 'order', 'ASC' );
$query->set( 'orderby', 'title' );
};
};
} );
```

I'm not sure if there a bug with my code, or if there is a bug with the Elementor posts widget.

The page I need help with: https://progressiveeconomyforum.com/glossary/letter/a/

Any help would be appreciated. Thanks.
Jordan

**Comment by vgstef** [comment]
I've similar problem. The custom query ID doesn't seem to have any impact on a current query.  Did you find a solution?

**Comment by jordanjustkidding** [comment]
@vgstef – This is the code that worked for me:

```
add_action( 'elementor/query/glossary_archives', function ( $query ) {
	$query->set( 'posts_per_page', 1000 );
    $query->set( 'order', 'ASC' );
    $query->set( 'orderby', 'title' );
});
```

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by formgarten** [comment]
@jordanjustkidding Thanks dude! Found your question on wordpress first with no solution as I know the support answers of elementor on my own. This guy from unlimited elements has a great starting point for elementor query ids, too:

[](https://www.youtube.com/watch?v=-IKPrKUmupo)

**Comment by acal** [comment]
I solved this by first creating a custom query filter ID in the query section of the Elementor Loop Grid widget which I was using. The following code is modified from Elementors dev docs.
https://developers.elementor.com/docs/hooks/custom-query-filter/

The term `my_custom_filter` is user-defined and must be added to the Elementor widget for this code to work.
```
 /**
 * Order the posts in the query by comment count.
 *
 * @since 1.0.0
 * @param \WP_Query $query The WordPress query instance.
 */
function my_query_by_different_order( $query ) {
  $query->set( 'orderby', 'title' );
  $query->set( 'order', 'ASC' );
}
add_action( 'elementor/query/my_custom_filter', 'my_query_by_different_order' );
```
