### ISSUE TITLE
"Find an Expert" link in Dashboard should be removed for Agency licence installs

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#13693]
## Prerequisites
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The "Find an Expert" link was added in 3.1.0, and while I'm sure it's helpful to many who run solo sites, it seems like it would work against those who are managing sites for customers with an Agency license. In that scenario, customers who may have access to the website for their own needs will see the "Find an Expert" link, which essentially links them up with competitors to the agency handling the client site. This seems like a great feature for those on the Free, Personal, or even Plus licenses, however it seems to make no sense and in fact counter-productive for those running with an Agency license.

**Describe the solution you'd like**
The "Find an Expert" link to be removed from installations with Agency license.

**Additional context**
<img width="523" alt="image" src="https://user-images.githubusercontent.com/8153796/105922585-c57c1d00-5fef-11eb-8cd2-ad817bd4755f.png">

**Comment by shilo-ey** [comment]
Hi @d19dotca 

Thanks for your input.

We already thought of the possible inconvenience that might occur when you are building a website for your client, therefore, we incorporated the following display logic for this link to appear:
- Visible to Administrator role in all states
- Visible ONLY to License owner when Elemetnor Pro is activated
- Visible to all users regardless of their state and role when only Elementor is active (without Pro)
- Not visible to Pro users besides the mentioned above ones

This should cover the needs you described.


Thanks again!
