### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by caspergrl** [elementor/elementor#13705]
After the host updated all of the plugins, we have a white screen critical error and a site that is down. I can get into the dashboard and disabling elementor fixes the problem, but then of course the site (built entirely with the plugin) doesn't work. This happened when we updated back months ago and rolling back to an older version of elementor helped, but doesn't seem to be working this time. The error log seems to show this hundreds of times:

Tue Jan 26 18:17:06 2021] [warn] [client 66.249.64.219] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:17:23 2021] [warn] [client 54.236.1.13] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:09 2021] [warn] [client 98.21.53.104] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:10 2021] [warn] [client 98.21.53.104] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:10 2021] [warn] [client 98.21.53.104] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:11 2021] [warn] [client 98.21.53.104] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:12 2021] [warn] [client 98.21.53.104] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:18 2021] [warn] [client 98.21.53.104] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90
[Tue Jan 26 18:18:40 2021] [warn] [client 54.236.1.13] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_id() in /home/wp_yu8h2s/garvinandco.com/wp-content/plugins/elementor/core/kits/manager.php:90

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by caspergrl** [comment]
Thanks! To me, this is a bug report :) It appears to be the result of a bug!
