### ISSUE TITLE
Ability to re-order Global Colors & Typography

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#13704]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Ability to re-order (drag-drop) global colors and typography options so that colors added later can be brought to top if they're going to be used a lot. Speeds up the workflow of applying the color and not having to scroll everytime to apply a color added later.

**Describe the solution you'd like**
The ability to re-order global colors and typography like repeaters.

**Comment by shilo-ey** [comment]
I merged this issue with #12203, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
