### ISSUE TITLE
Elementor 3.1: break archive page

### ISSUE THREAD

**Issue by yansircc** [elementor/elementor#13718]
## Prerequisites
1. Elementor 3.1
2. Elementor pro 3.0.10
3. Use the "archive posts" widget on the blog page
4. WordPress permalink setting is "post"

## Description
When I enable 3.1, my archive page will break, all post will disappear and only a post named 'blog' will remain, who's link is the archive page URL.

## Isolating the problem
This problem happened only on 3.1
Only when I use the archive post widget
Only happened on the archive page
Only happened if I use the "current post" query

## Environment
PHP5.6

**Comment by sermalefico** [comment]
you must use archive post in an archive template, no in a page template. You can use post widget no archive post.

**Comment by yansircc** [comment]
> you must use archive post in an archive template, no in a page template. You can use the post widget no archive post.

Hi, I have set the blog page as the blog archive in WordPress settings.
In 3.0.9, everything works fine, but in 3.0.10, the archive post didn't work.
@sermalefico

**Comment by sermalefico** [comment]
you make a Archive Blog theme to asign the template to the page ? or you edit directly the page in the elementor wordpress editor?

**Comment by yansircc** [comment]
Yes, I set the blog page as the posts archive in the WordPress setting(admin panel → settings → reading → the static page as home page and blog as the post archive.
Then, assign the template to 'all archive'.
You can have a try to see this error. @sermalefico

**Comment by rodolphebertozzo** [comment]
Is this issue also related to this problem? https://github.com/elementor/elementor/issues/13645

**Comment by yansircc** [comment]
Exactly @rodolphebertozzo

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
