### ISSUE TITLE
YouTube player element ID required.

### ISSUE THREAD

**Issue by astbarc** [elementor/elementor#13711]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Since last version (3.1) in the pages that includes the video widget, Elementor shows the following error on the console:

`www-widgetapi.js:638 Uncaught Error: YouTube player element ID required.
    at new Z (www-widgetapi.js:638)
    at Video.prepareYTVideo (video.cadfb803f731eda62363.bundle.min.js:2)
    at video.cadfb803f731eda62363.bundle.min.js:2
    at YoutubeLoader.onApiReady (frontend.min.js:2)
    at frontend.min.js:2`

**Comment by DorShahar** [comment]
Hi @astbarc 
Please attached more details: System info, browser, Plugins, etc'. 
Also, please add steps to reproduce. 

Thanks

**Comment by astbarc** [comment]
Hi @DorShahar 

To reproduce the issue, with Elementor 3.1 active, you only need to use the video widget with a youtube link as a source. 

 I've seen many websites made with elementor that has the same js error appearing in the browser console. It happens with different youtube videos-

![image](https://user-images.githubusercontent.com/2587221/106116256-ff653480-6151-11eb-8b94-bbb636a4bdc6.png)

**Comment by bobhuf** [comment]
I'm experiencing the same issue but only when an image overlay is selected.

**Comment by astbarc** [comment]
Thanks for the info @bobhuf 

In my case is also happening only when the image overlay is enabled.

**Comment by pensierinmusica** [comment]
Same issue here, causing thousands of errors for our website's visitors.

@kobizz @KingYes @matipojo @iNewLegend @arielk @udidol can someone from the dev team please get it fixed and push the patch in the next Elementor upgrade?

Thanks!

**Comment by zahidlabs** [comment]
Please fix this problem. there is an error in the console and it does not seem to go away.
image overlay is selected.

**Comment by black-eye** [comment]
+1

**Comment by udidol** [comment]
Hi everyone, thank you for your feedback. 

**To be sure we are solving your issues, a few questions to you all:**
Do all of you have your video widget set to Privacy Mode?
Do you happen to have more than one video in your page? 
Or a background video somewhere on the page in addition to your video widget?

**Comment by bobhuf** [comment]
1. Yes
2. Yes
3. Yes, all of them set to privacy mode
4. No
5. It only occurs when using the Image Overlay option, so yes.

**Comment by astbarc** [comment]
Hi, In my case:

1. No privacy mode but happens also with privacy mod enabled.
2. Yes, but happens also with only one video.
3. No, none of them in privacy mode.
4. No
5. Yes, only happens with image overlay enabled.

**Comment by Franz333** [comment]
Hello
1. yes
2. no
3. N/A
4. no
5. yes

**Comment by koszza** [comment]
Hi !

1. yes
2. no
3. N/A
4. no
5. yes

**Comment by pensierinmusica** [comment]
1. No
2. Yes
3. N/A
4. No
5. Yes

**Comment by udidol** [comment]
Hi everyone, thank you for your feedback.
This issue has been fixed, the fix will be available in the upcoming patch release.

**Comment by Prestozer** [comment]
Good

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.2

Feel free to update

Thanks!

**Comment by Prestozer** [comment]
Thanks @shilo-ey

**Comment by aryan3650** [comment]
Hi,
I'm having same issue with **Vimeo videos**.
Having same error in the console when **image overlay is enabled**.
I'm using **Elementor v3.1.3**

**Comment by dmasells** [comment]
If you still have this error even after updating (like I did), try flipping image overlay off, saving then back on. Also, you may have to delete the video element and re-add it.
