### ISSUE TITLE
Disabling Elementor Minicart template not working

### ISSUE THREAD

**Issue by legenddaniel** [elementor/elementor#13713]
https://github.com/elementor/elementor/issues/9304

Jan 2021 with Elementor Pro 3.0.9. Disabling still not working and I can't find the rollback option. I try overriding the template in my child theme not working either. Resetting plugins and theme not working, just nothing works. In the database the elementor_use_mini_cart_template has been falsy but it is still rendering.

**Comment by legenddaniel** [comment]
I make a new page and set the option in the database and now it works

**Comment by codelogixuk** [comment]
This issue still exist, is there a fix for this? changing the value in the database did not work for me. @legenddaniel please can you kindly add the steps here.

**Comment by legenddaniel** [comment]
> This issue still exist, is there a fix for this? changing the value in the database did not work for me. @legenddaniel please can you kindly add the steps here.

Hi actually I have no idea how it went working. I make a new page and change the databse value from 'no' to 'yes' to 'no' and everything is good.
