### ISSUE TITLE
Cookie and privacypolice pop-up / GDPR compliant

### ISSUE THREAD

**Issue by seekings** [elementor/elementor#13710]
Would be fantastic if Elementor developed an ´drag and drop` / Easy to setup, cookie pop-up.
It should be GDPR compliant, auto scan for cookies, be possible to declining cookies, etc.

There are great plugins for this. But it would be fantastic if it was and easy to use standard in Elementor. 

It`s legal to install and setup on all homepages. Therefor it should be an standard, in my mind. Thanks :-)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
