### ISSUE TITLE
Custom image position for background slideshow of responsive mode designs

### ISSUE THREAD

**Issue by danlsk** [elementor/elementor#13737]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am not able to set the image position of background slideshow because the default options is not sufficient to align the image I want for mobile mode. 

**Describe the solution you'd like**
Please create a custom position option just like you did for classic type background image. 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/9096838/106236325-9526bf80-6237-11eb-87bc-9ed71be5ba21.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
