### ISSUE TITLE
FEATURE REQUEST | Shape Divider Vertical | Image/Background Masks

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13736]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Would be amazing to have Shape Dividers Vertical on Sections. In addition, the possibilitie to add Masks for Background Images, Videos, Image Widget and Image Videos! As well as sections and Columns.

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!
