### ISSUE TITLE
Constant logouts when loading Elementor 3.1 in staging environment

### ISSUE THREAD

**Issue by srack835** [elementor/elementor#13731]
We are using Elementor 3.1 and Elementor Pro 3.0.10 in a staging environment, with all plugins, the Hello theme, etc up to date. It's a pretty simple install, without a child theme.

Any time we attempt to open the Elementor editor or access a page built with Elementor, we are immediately logged out of the staging site.
A couple of sessions I've gotten as far as enabling Elementor safe mode before being logged out, but the editor will not load and "Your session has expired. Please log in to continue where you left off." appears just a moment later.

Disabling Elementor and Elementor Pro prevents the constant logouts.

We have been working with our host, who can reproduce the issue and has also independently narrowed down the issue to Elementor and not any other plugins.

Obviously disabling Elementor in general is not an option for us. However the issue prevents us from editing _any_ content.

Our live site is not yet running 3.0 or 3.1, so I can't speak to whether this issue will occur outside of a staging environment.

**Comment by DorShahar** [comment]
Hi @srack835,
Thanks for reaching out.

If you have any security or login plugin running please deactivate it on your site.
I suppose one of these plugins is deleting the session. Try also to delete the cookies before you log in to the staging site.

If the problem continues - you are welcome to contact our support or ask in the Facebook community. 

Thanks
