### ISSUE TITLE
slider: static h1 (SEO) above changing backgrounds

### ISSUE THREAD

**Issue by MitchBuchannon** [elementor/elementor#13740]
Hi,

in order to avoid multiple h1-tags (SEO) in the slider widget, an option to set one headline (h1) static is urgently needed. 
(only the background images should change). Like here:
https://smartslider3.com/static/

It would also be great to expand the slideshow-option (image background) with a slider navigation
(arrows left/right + dot navigation at the bottom). So you could set a static h1 over changing backgrounds.

With these features, no other slider would be necessary!

Thanks a lot

**Comment by shilo-ey** [comment]
Hey, you can do this using the Background slideshow and design the content by your own.

https://elementor.com/help/background-slideshow/

Thanks for your suggestion

**Comment by MitchBuchannon** [comment]
Hi,
thanks for your suggestion.
unfortunately the background slideshow option has no controls (arrows left/right / dot navigation bottom). So its not possible to "simulate" a real slider effect with controls ;-(
