### ISSUE TITLE
The Images in the media carousel created with Elementor are not displayed on page

### ISSUE THREAD

**Issue by SuperSdelka** [elementor/elementor#13747]
I create a media carousel with linked images (with Elementor) on my site and use it as a template in the branding area.

The Problem: the images are not displayed in the media carousel!

I did the following steps:
Step 1: I created a widget (media carousel) with linked images with the help of Elementor.
Step 2: Then I converted the widget (media carousel) into shortcode/template .
Step 3: I used the short code in the branded area on my site (I copied the short code in my theme: Theme Options> Ads and Code Zones>Branded area).
If you teke a look at my test page [https://stage4test.supersdelka.com] can clearly see that the images 
from the media carousel  in the branded area are not displayed.
The problem happens when I insert the media carousel in the branding area.

If I use media carousel in other areas, everything works fine and the images are shown correctly in the media carousel.

If I delete the links (custom URL) from every image in the medial carousel, everything works fine again and the images are shown correctly in the media carousel in the branded area.

I use 
Elementor 3.0.16
Elementor  Pro 3.0.9

**Comment by DorShahar** [comment]
Hi @SuperSdelka 
Please pay attention to the upcoming release of `core v3.1.1` - and update your core version (don't forget to backup your sites).

In case the problem continues - open a new issue with the system info so we could investigate. 

Thanks.
