### ISSUE TITLE
WP rocket still loads the Elementor JS files that are disabled with the new Elementor asset loading experiment enabled

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#13778]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

Describe the bug
Tested: occurs with minification and concentation, as well delay javascript are on. These are the settings that give me the best performance, so that's what i tested it with. It seems to be an issue with wp-rocket concentating and including the swiper js even when it is not supposed to be loaded.

The number of assets that should be loaded has decreased on all pages, this is confirmed via asset cleanups js/css files list, there are numerous js files that are supposed to no longer load on the page. The largest of these js files is swiper.js, with over 100+ kb of unnecessary data loaded on every page that does not contain a slider. The homepage does not have a slider on it, or anything that uses the swiper js library at all. The asset does not show up in the loaded list of assets in asset cleanup at all. It should by all accounts not load on the page.

Even on pre 3.1, if you disable the swiper.js file via asset cleanup with the ignore dependencies option checked, the file is always loaded. This only occurs with Elementor based js files. I'm not sure why. The issues with dequeuing these files seems to only apply to elementor js files regardless of how they're dequeued(asset cleanup or the new elementor update). Other js/css files I've dequeued with asset cleanup ARE removed from the page weight and improve the sites load time.

However, when I run the site through pagespeed insights, gtmetrix or any other speed scanner, the page weight is identical and the site loads in exactly the same time, no performance increase. This leads me to believe that WP-Rocket still loads and compresses the file regardless of whether the experiment in elementor is active or not. Swiper ALWAYS loads.

To Reproduce

1. Install elementor

2. Activate Wp-rocket and enable minification and concentation for css and js, as well as delay javascript.

3. Activate an both elementor and elementor pro with the latest version under 3.1(the version just before 3.1 was released), as it does not have the asset loading experiment

4. Build a page that does not include a slider so that the swiper js file shouldn't be relevant to the page's functioning. (This ensures the asset does not appear in the loaded asset list in asset cleanup once you activate the asset loading experiment in 3.1.1 AFTER building the page in the elementor version PRE 3.1 first.)

5. Run it through a speedtest and notate the page size

6. Update elementor to 3.1.1

7. Enable the asset loading experiment

8. Check asset cleanup to confirm/ensure the file no longer appears in the list for a page, it should appear to not be loading at all.

9. Clear the cache to ensure old cache files that should contain the swiper js file due to elementor pre 3.1 loading it on the page and including the asset regardless of whether it was being utilized. This ensures new cache files are generated for 3.1.1 with the asset loading experiment enabled.

10. Speed test the site again, the page weight has not decreased, and the loading time scores have not improved. WP-Rocket still loads the JS file even though it is not supposed to be included in the minified/compressed files.

Expected behavior
A page weight reduction equal to the size of the files no longer being loaded. WP-Rocket should automatically detect the experiment has been activated and exclude the files that are not supposed to be loaded on the page from minification and concentation, so the expected page size reduction happens and performance of the site improves. The new elementor update with the experiment enabled is supposed to decrease page weight by up to 177 KB, my site should have between 480-550 KB loaded after enabling the experiment.

My mobile pagespeed insights score is in the 60's-70 range(there's variance between tests. Make sure you run at least 12 tests, 6 at a time in multiple tabs to accurately measure the pagespeed. I recommend running the test 3 times in all tabs for a total of 18). 70 is my top end score for pagespeed insights mobile. After enabling the asset loading feature, my scores should jump to always be in the 70's or 80's range due to the expected gigantic reduction in page size.

Once you run the first test, you can just copy paste the url into a new tab and it will automatically re-run the test, i just open it in 6 different tabs at a time and run the tests at the same time. There's zero chance of my site being overloaded, i've run load tests with 10k users within 15 seconds and my site can handle the load with zero failures.

Testing multiple times on pagespeed insights gives you a much more accurate picture of the loading times if you average the scores together. That's why I listed a range of scores that average from 60-70.

Screenshots
wp rocket

The page weight does not change whatsoever after elementor is updated and the asset loading experiment has been enabled. The page weight size does not decrease at all from the older elementor that does always load swiper, to 3.1.1 with the feature enabled. The values remain identical. WP-Rocket should auto-detect the asset loading changes and reduce the size of the page accordingly.

Additional context
I even tried using a file manager plugin and deleted all the files out of the cache>min>1 folder, and they regenerated after visiting the homepage, so I know they are fresh cache files.

Additionally, If I use the older version of elementor and try to disable the swiper.js file from loading on the page with ignore dependencies checked, the page weight remains the same. It seems there is an issue specific to that file, that it is always included in the minified/concentated files, regardless of if it is supposed to be disabled or not. This applies to both the new elementor 3.1.1 update and the version pre 3.1, the file is ALWAYS loaded regardless of whether it is supposed to be active or not. Swiper ALWAYS loads.

I'm not sure why this is specific to swiper or additionally the other elementor js files that are supposed to not load on this page, but I would assume it's due to not being compatible with the way elementor dequeues the file to be loaded.

I know this is for js files, but i've even tried the elementor regenerate css option just in case, didn't fix it.

Supporting dequeuing elementor js files, especially when the experiment is active, is imperative. This is supposed to massively increase the performance of elementor and I'm completely unable to take advantage of the reduction in page weight size while wp-rocket is active. I should be able to take advantage of this feature. It would significantly improve load times and conversion rates on my ecommerce site. Elementor is traditionally considered one of the slower page builders, and it's in part due to these unnecessary js files that are loading on every page.

Please test this and do not just close the issue. This is a real problem and I've tried to go to great lengths to explain and document the why, what and how of what's happening. I would sincerely appreciate if you could give this bug the attention it deserves. Please at least respond and let me reply before closing. I assure you this issue IS happening to me, and I would really love it if you could fix it. The elementor asset loading is currently an experiment, but it will become the standard behavior in a future update.

Seeing as Elementor has over 5 million users, that's a ton of people that do not get any benefit from the feature with wp-rocket active. I've tested this extensively, and this is reproducible for me on a fresh wordpress install and a default theme.

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] I am using Astra
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

[system-info-www.test.com-02-02-2021.txt](https://github.com/elementor/elementor/files/5910126/system-info-www.test.com-02-02-2021.txt)

**Comment by jazir5** [comment]
@arielk @bainternet 

Could you guys look into this? 

https://github.com/wp-media/wp-rocket/issues/3544#issuecomment-774378925 

Other people are having this issue as well.

**Comment by shilo-ey** [comment]
Hey, thanks for the report.

I would like to disregard the scoring that you are currently getting and focus on the loading of swiper when not needed.

Please try to disable all of your 3rd party addons, and keep only Elementor 3.1.1 and Elementor Pro 3.1.0 active.

In addition please switch to Hello theme (or any vanilla theme) and check if the swiper library is loaded.

From an examination we did with WP-Rocket team, it seems that everything works as expected.

Let me know,
thanks

**Comment by rotemee** [comment]
Hi @jazir5,

Please note that after testing this issue, I was not able to reproduce it.

When comparing the WP-Rocket generated JS file that was created using a version prior to 3.1 with a JS file created using V3.1, you should get a file size difference of about ~40KB (GZIP). When checking without GZIP (save the files to your local machine and check their size), you should get a file size difference of more than ~130KB.
Therefore it might seem like there is no significant difference in GZIP mode, but if you compare the source files, the difference will be more clear to see.

In addition, you can also verify that the Swiper JS library does not exist in the WP Rocket generated JS file by searching a line of code from the Swiper JS library - for example:

`JSpaginationBulletMessage:"Go to slide {{index}}`

This line should appear in the generated JS file when the optimized mode is disabled and should NOT appear when enabled.

Thanks.

**Comment by d19dotca** [comment]
For what it's worth, I cannot reproduce this issue either. Using "swiper" as the file to look for, I see it not appearing (as expected) on pages which do not call it, and I see it when I expect to see it on pages that call it. Disabling the Improved Asset Loading experiment brings the swiper back on every page. The related WP Rocket issue was closed (on Feb 24th) as they couldn't reproduce it either.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
