### ISSUE TITLE
✅ 🚀 Feature Request: Option to remove smooth scroll js

### ISSUE THREAD

**Issue by AleksBaikalski** [elementor/elementor#13773]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There're some cases when js for smooth scroll to anchor is not needed. There's a css property for that:
`:root { scroll-behavior: smooth; }`
Also for me Elementor's js scroll works somewhat jumpy.
Also in most cases I need to show the anchor value in the browser, and moreover, this value is needed for good UX with native history API browser behavior, just for user to go to the previous or the next anchor. 
Modern browsers support all this natively. No need to use js here, it's always additional weight for the page. Let's keep only js that changes `.elementor-item-active` class depending on the position of targeted element in the veiwport.

**Describe the solution you'd like**
I want a checkbox in Elementor settings to remove Elementor smooth scroll js.

**Describe alternatives you've considered**
To not use Elementor anchor widget, replacing it with HTML.

**Additional context**
Just one small feature that'll make Elementor-powered sites faster and more optimized.

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by black-eye** [comment]
+1 Yes please!

**Comment by Camilo517** [comment]
+1

**Comment by gabyferman** [comment]
+1 !!!

**Comment by barrycosta** [comment]
+1 ... I just ran into this. While I appreciate Elementor is trying to be helpful the jump is not a smooth jump and I don't like that I can't control the offset. I have my own smooth scroll option that uses the easing functions js file. Way better smoother transition for my clients and I can control the feel of the jump for users. I don't like that Elementor is hijacking my anchor links. Please make this an option in settings that creators can decide to disable this effect on anchor links. Thanks!

**Comment by barrycosta** [comment]
For those of you searching for a solution to the dilemma of disabling the Elementors smooth scroll function @jamesckemp has a solution here:  https://github.com/elementor/elementor/issues/4227#issuecomment-723002739

**Comment by nicholaszein** [comment]
Hey everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Core v3.25.0! 🥳 

Elementor now uses native CSS smooth scrolling!

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
