### ISSUE TITLE
Add link to Pdf in link field?

### ISSUE THREAD

**Issue by Prozac2000** [elementor/elementor#13775]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have been using Elementor for years but the possibility of finding pdfs in the search field and not just Articles and Pages.

**Describe the solution you'd like**
Find pdf uploaded too.

**Describe alternatives you've considered**
Paste the link to pdf but is boring.

**Additional context**
no

**Comment by ShamanFromSiberia** [comment]
More correct it will be to search in media. PDF is too specific.

**Comment by shilo-ey** [comment]
Hi @Prozac2000 

Thanks for your input.

You can achieve this behavior with custom code or 3rd party plugin that extends the capabilities of WordPress e.g https://wordpress.org/plugins/add-search-to-menu/

Thanks
