### ISSUE TITLE
Elementor Nav Menu

### ISSUE THREAD

**Issue by marcomadruga** [elementor/elementor#13777]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When designing websites, it´s important the nav menu layout, and the Elementor native widget Nav Menu don´t have many choices, mainly in the mobile menu... so i need to install a theme payed (like JupiterX) or free (like Plhox) only to have a better widget for Nav Menu... and because of this widget i get stucked with a theme that slow the performance of my website... 
I looked for nav menus plugins for Elementor addons but they are not good.... the better ones, and with more options are with themes like Phlox and JupiterX.

**Describe the solution you'd like**
The solution is to have an Elementor native widget navigation menu, that is flexible and with more options to design the menu layout, options like:
- If menu is on bottom of page, the, the option for sub-menus open from bottom to top
- Customize burguer icon with image or svg.
- Have more options on burguer opened menu like: 
    - Full Screen menu
    - Open menu on the side of screen, with slide on left or right side

**Describe alternatives you've considered**

**Additional context**
I think its really important to have this improvement, a diferent nav menu can make the webesite design more unique... and with this improvement i don't need to get slow themes just because of the nav menu widget, and i can finally use the Hello theme :)

I'm sending a screen-capture of the theme Phlox nav menu widget, tht is more complete.
![Phlox-Nav-Menu-Screenshot 1](https://user-images.githubusercontent.com/69525556/106514894-c53ac080-64cc-11eb-9480-0f12ac78f604.jpg)
![Phlox-Nav-Menu-Screenshot 2](https://user-images.githubusercontent.com/69525556/106514895-c5d35700-64cc-11eb-8b2b-d9e8d9049ab4.jpg)

**Comment by ShamanFromSiberia** [comment]
+1
I'd add to this request options for hamburgers animations, and that styles for it were used ONLY WHEN is necessary. Hamburgers I suggest are here: [jonsuh.com/hamburgers](https://jonsuh.com/hamburgers/) No svg is used, just css.

**Comment by DorShahar** [comment]
Hi,
Great suggestion! we will definitely consider this
I'm merging this with #3275 since this handling the same topic.

Thanks!
