### ISSUE TITLE
3.1.1 update breaking dropdown menus

### ISSUE THREAD

**Issue by rkm82** [elementor/elementor#13780]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description
When updating from 3.0.16 to 3.1.1, our main menus suddenly no longer show any dropdown entries, just the "main items" are shown. 

This can be replicated on a staging page, and a rollback to 3.0.16 solves the issue.

## Steps to reproduce

Update from 3.0.16 to 3.1.1 within WP updates

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ n/a ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.17
	PHP Version: 7.4.14
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: https://www.staging.swissinsurancepartners.com
	Home URL: https://www.staging.swissinsurancepartners.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: SIP Theme Child
	Version: 1.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: instive
	Parent Theme Version: 1.1.2
	Parent Theme Author: Tripples

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.53

== Active Plugins ==
	Advanced iFrame
		Version: 2020.10
		Author: Michael Dempfle

	AffiliateWP
		Version: 2.6.4.1
		Author: Sandhills Development, LLC

	AffiliateWP - Affiliate Area Tabs
		Version: 1.2.9
		Author: Sandhills Development, LLC

	AffiliateWP - Affiliate Dashboard Sharing
		Version: 1.1.6
		Author: AffiliateWP

	AffiliateWP - Custom Affiliate Slugs
		Version: 1.0.3
		Author: Sandhills Development, LLC

	AffiliateWP - Direct Link Tracking
		Version: 1.1.4
		Author: Sandhills Development, LLC

	AffiliateWP - Pushover Notifications
		Version: 1.0.2
		Author: Chris Klosowski

	Analytify - Google Analytics Dashboard
		Version: 3.1.6
		Author: Analytify

	Analytify - Gooogle Analytics Dashboard Widget
		Version: 1.1.5
		Author: Team Analytify

	Analytify Pro
		Version: 2.2.1
		Author: WPBrigade

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	CRM Perks Analytics
		Version: 1.0
		Author: CRM Perks, Inc.

	CRM Perks Geolocation
		Version: 1.3
		Author: CRM Perks, Inc.

	CRM Perks Marketing Data
		Version: 1.3
		Author: CRM Perks, Inc.

	CRM Perks Partial Entries
		Version: 1.0
		Author: CRM Perks, Inc.

	Customizer Export/Import
		Version: 0.9.2
		Author: The Beaver Builder Team

	Disable Admin Notices Individually
		Version: 1.2.4
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	Elementor
		Version: 3.2.0-dev2
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.10
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.1.4
		Author: Wpmet

	Essential Addons for Elementor
		Version: 4.4.1
		Author: WPDeveloper

	Gravity Forms
		Version: 2.4.22
		Author: Gravity Forms

	Gravity Forms Infusionsoft Pro
		Version: 1.1.1
		Author: CRM Perks.

	Gravity Forms Multilingual
		Version: 1.5.4
		Author: OnTheGoSystems

	Gravity Forms Styles Pro
		Version: 2.5.2
		Author: Warp Lord

	Grid Layout Gravity Forms
		Version: 3.3.6
		Author: Sushil Kumar

	Header Footer Code Manager
		Version: 1.1.8
		Author: 99robots

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Image Map Pro
		Version: 5.3.2
		Author: Webcraft Plugins Ltd.

	Instive Essentials
		Version: 1.6
		Author: 

	Login LockDown
		Version: v1.8.1
		Author: Michael VanDeMar

	Ninja Tables
		Version: 4.1.1
		Author: WPManageNinja LLC

	Ninja Tables Pro
		Version: 4.1.3
		Author: WPManageNinja

	Post Duplicator
		Version: 2.22
		Author: Metaphor Creations

	Query Monitor
		Version: 3.6.7
		Author: John Blackbourn

	Rank Math SEO
		Version: 1.0.56.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 2.0.7
		Author: Rank Math

	Really Simple SSL
		Version: 4.0.7
		Author: Really Simple Plugins

	Really Simple SSL pro
		Version: 4.0.5
		Author: Really Simple Plugins

	Redux
		Version: 4.1.24
		Author: Redux.io + Dovy Paukstys

	Simple Custom CSS
		Version: 4.0.4
		Author: John Regan, Danny Van Kooten

	Slack Live Chat
		Version: 1.1.0
		Author: Chatlio

	Slider Revolution
		Version: 6.3.8
		Author: ThemePunch

	Smush Pro
		Version: 3.8.1
		Author: WPMU DEV

	Styles & Layouts Gravity Forms
		Version: 4.2.10
		Author: Sushil Kumar

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.25
		Author: Sucuri Inc.

	Unyson
		Version: 2.7.24
		Author: ThemeFuse

	UpdraftPlus - Backup/Restore
		Version: 1.16.47
		Author: UpdraftPlus.Com, DavidAnderson

	WP Fastest Cache
		Version: 0.9.1.4
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.5.9
		Author: Emre Vona

	WP Mail SMTP Pro
		Version: 2.5.3
		Author: WPForms

	WPML Multilingual CMS
		Version: 4.4.9
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.7
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.10.5
		Author: OnTheGoSystems

	WP Rollback
		Version: 1.7.1
		Author: Impress.org

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists
	Essential Addons for Elementor: header_not_exists

== Elements Usage ==
	
	header : 2
		button : 1
		image : 1
		nav-menu : 1
	page : 20
		button : 3
		elementskit-client-logo : 2
		elementskit-heading : 4
		elementskit-icon-box : 6
		elementskit-social-media : 2
		heading : 13
		html : 1
		icon : -1
		icon-list : 4
		image : 7
		nav-menu : 3
		shortcode : 2
		slider_revolution : 1
		spacer : 5
		template : 4
		text-editor : 9
	section : 78
		button : 1
		eael-info-box : 2
		eael-post-grid : 1
		elementskit-accordion : 2
		elementskit-blog-posts : 1
		elementskit-button : 9
		elementskit-client-logo : 1
		elementskit-heading : 11
		elementskit-icon-box : 3
		elementskit-mail-chimp : 1
		elementskit-testimonial : 3
		heading : 31
		icon : 2
		icon-list : 1
		image : 31
		instive-cf-form : 3
		nav-menu : 1
		shortcode : 1
		spacer : 2
		testimonial : 2
		testimonial-carousel : 2
		text-editor : 29
	single : 2
		heading : 1
		post-comments : 1
		posts : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	widget : 0
		elementskit-heading : 2
		shortcode : 13
	wp-post : 2
		button : 5
		ekit-nav-menu : 4
		elementskit-button : 8
		elementskit-header-offcanvas : 2
		elementskit-heading : -16
		elementskit-icon-box : -29
		elementskit-mail-chimp : 1
		elementskit-pricing : 3
		elementskit-social-media : 9
		global : 3
		heading : 75
		icon : 2
		icon-list : 23
		image : 39
		instive-back-to-top : 3
		instive-insurance : -36
		instive-logo : 1
		instive-search : 2
		nav-menu : 2
		price-table : 10
		shortcode : 17
		spacer : 28
		template : 62
		text-editor : 75
		toggle : 4
	wp-page : 76
		blockquote : 1
		call-to-action : 13
		eael-team-member : 16
		elementskit-button : 7
		elementskit-heading : 7
		elementskit-icon-box : 5
		form : 2
		google_maps : 1
		heading : 42
		html : 5
		icon-box : 6
		icon-list : 3
		image : 9
		image-gallery : 2
		instive-team : 8
		instive-testimonial : -1
		shortcode : 10
		slider_revolution : 6
		spacer : 35
		template : 57
		text-editor : 17
		toggle : 4
		video : 4
	single-post : 1
		author-box : 1
		divider : 2
		form : 1
		heading : 6
		image : 2
		nav-menu : 1
		post-comments : 1
		post-info : 1
		post-navigation : 1
		posts : 2
		share-buttons : 1
		social-icons : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1

== Log ==
	
Log: showing 20 of 312020-09-01 08:17:53 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-01 08:17:53 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-01 08:17:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '3.0.5',
)]
2020-09-06 19:19:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-09-06 19:22:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-09 21:03:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-14 21:05:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]
2020-09-18 09:10:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]
2020-09-23 21:11:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-09-30 22:36:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-09 09:57:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.3',
  'to' => '3.0.5',
)]
2020-12-10 23:27:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.14',
)]
2020-12-10 23:27:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.8',
)]
2021-01-05 09:24:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.15',
)]
2021-01-05 09:24:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-06 20:10:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-24 23:21:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2021-01-26 20:06:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
2021-02-02 12:29:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-02-02 12:32:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.2.0-dev2',
)]

PHP: showing 5 of 5PHP: 2020-09-02 02:58:01 [notice X 12][/home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-06 19:19:22 [warning X 1][/home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/uploads/elementor/css/post-7886.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-12 04:47:46 [notice X 464][/home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1430] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-13 01:15:26 [error X 10][/home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php::206] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php:206
Stack trace:
#0 /home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor-pro/modules/screenshots/module.php(226): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode()
#1 /home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor/core/base/module.php(83): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor-pro/core/modules-manager.php(63): Elementor\Core\Base\Module::instance()
#3 /home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor-pro/plugin.php(268): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/sienamal/domains/swissinsurancepartners.com/public_html/wp-includes/class-wp-hook.php(287): ElementorPro\Plu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-30 12:08:08 [notice X 1][/home/sienamal/domains/swissinsurancepartners.com/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2020-09-12 02:45:22 [error X 1][https://www.swissinsurancepartners.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.7:2:473653] Cannot read property \'document\' of undefined 
JS: 2020-10-19 11:37:04 [error X 2][https://www.swissinsurancepartners.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.0.11:2:60285] Cannot read property \'attributes\' of undefined 
JS: 2020-10-21 06:41:57 [error X 1][https://www.swissinsurancepartners.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2235\") has already been destroyed and cannot be used. 
JS: 2020-12-14 10:10:11 [error X 4][https://www.swissinsurancepartners.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:468052] Cannot read property \'html\' of undefined 
JS: 2021-01-29 09:26:55 [error X 625][https://www.swissinsurancepartners.com/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:31670] Cannot read property \'data\' of null 
JS: 2021-01-30 12:32:21 [error X 5][https://www.swissinsurancepartners.com/wp-content/plugins/elementor-pro/assets/lib/smartmenus/jquery.smartmenus.min.js?ver=1.0.1:3:13548] Cannot read property \'parentNode\' of null

**Comment by shilo-ey** [comment]
Hi @rkm82 

Thanks for reporting.

Unfortunately, we can't reproduce the issue you reported.

From looking at your System info it seems like you had a JS error that caused your menus to break:
```
JS: 2021-01-30 12:32:21 [error X 5][https://www.swissinsurancepartners.com/wp-content/plugins/elementor-pro/assets/lib/smartmenus/jquery.smartmenus.min.js?ver=1.0.1:3:13548] Cannot read property 'parentNode' of null
```

Please make sure no other plugin conflicts with your menus.

PS - check your server settings for CORS policy.

If the issue persists please contact our support for specific issue isolation,

Thanks
