### ISSUE TITLE
Video Background is Discarding Vimeo Player URL Parameters

### ISSUE THREAD

**Issue by Christopher-Hayes** [elementor/elementor#13797]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using the video background feature, Elementor will discard any URL parameters you put on the video URL. Vimeo is designed to allow you to customize their player with URL parameters, this functionality is impossible to use in Elementor because it throws the URL parameters away and replaces them with its own. This functionality is important because the Elementor background video settings are non-exhausive and doesn't cover essential parameters like `quality` and `dnt`.

## Steps to reproduce

1. Give an Elementor section a video background.
2. In the "Video Link" field, put the Vimeo player URL of a Vimeo video.
For example: https://player.vimeo.com/video/45232468
3. Add Vimeo URL parameters to customize the player.
For example: https://player.vimeo.com/video/45232468?quality=240p&dnt=true
![image](https://user-images.githubusercontent.com/6013871/106814634-b37a2a00-6640-11eb-8f52-402aa025dbb6.png)
4. After publishing the page, the resulting iframe will have URL parameters that were set in the Elementor UI with toggles, but any URL parameters added by the user to the "Video Link" will be discarded.
![image](https://user-images.githubusercontent.com/6013871/106814715-d1478f00-6640-11eb-91b3-a8fdb57d11ee.png)

## Expected Behavior

Merge the URL parameters in some way. The video player loses a lot of functionality by discarding all URL parameters entered by the user.

## Isolating the problem
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Christopher-Hayes** [comment]
Fixing this issue would also resolve security concerns in #13631

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
Very counterintuitive behavior

**Comment by ShamanFromSiberia** [comment]
Also users parameters should overwrite those default ones set by Elementor

**Comment by FlorianW7** [comment]
+1

**Comment by jonasdumas** [comment]
+1

**Comment by sbtre** [comment]
This feature is so crucial. Please fix @yossi-elementor  @rami-elementor  @arielk  ♡

**Comment by nicholaszein** [comment]
Hey all!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

Thanks for your contribution, and for your patience! 🙏 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
