### ISSUE TITLE
elementor_pro/forms/process not able to set empty field value for actions

### ISSUE THREAD

**Issue by tiagoefreitas** [elementor/elementor#13790]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Need to set a form field value when it is empty before actions are run.
Used elementor_pro/forms/process but field is still empty on the action.

## Steps to reproduce

create field in form and use the following code to set it when null, use it in an action on submit.

```
add_action( 'elementor_pro/forms/process', function ( $record, $ajax_handler ) {
    $fields = $record->get_field( [
        'id' => 'emptyfield',
    ] );
    if ( empty( $fields ) ) {
        return;
    }
    $field = current( $fields );

    if ( $field['value'] == null ) {
		$field['value'] = "XXX";
		$field['raw_value'] = "XXX";
    }
}, 10, 2 );
```

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/TmeNQEgj

**Comment by tiagoefreitas** [comment]
also tried this one, same result:

```
add_action( 'elementor_pro/forms/process/text', function ( $field, $record, $ajax_handler ) {
    if ( $field['id']=='emptyfield' and $field['value'] == null ) {
		$field['value'] = "XXX";
		$field['raw_value'] = "XXX";
    }
}, 10, 3 );

```

**Comment by tiagoefreitas** [comment]
Also tried elementor_pro/forms/process with $record->update_field( $field['id'], 'value', 'XXX') and also doesn't work

**Comment by hackerfabian** [comment]
@tiagoefreitas was looking for the same problem. This code works for me:

`add_action( 'elementor_pro/forms/process', function( $form_record, $ajax_handler ) {
    $form_name = $form_record->get_form_settings( 'form_name' );


    if ( 'FORMNAME' !== $form_name ) {
        return;
    }
    // get fields
    $raw_fields = $form_record->get( 'fields' );

    // loop over the fields
    foreach ( $raw_fields as $id => $field ) {
        if ( $id = 'FIELDID'  ) {

            $form_record->update_field( $id, 'value', 'NEW VALUE' );
        }
    }
}, 100, 2 );`

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by biosman22** [comment]
I have triggered the same problem after 3 years don't use "update_field" to change the value 
use "set" instead 

    $fields = $record->get( 'fields' );
    if ( isset( $fields['email']) && str_contains($fields['email']['value'], 'test') ) {
        error_log("------------ test value has been detected--------------");
        $fields['full_name']['value'] = 'dummy Interactive';
        
        // that failed
        // $record->update_field( 'full_name',  $fields['full_name']['value'], 'dummy Interactive' );
        // $record->update_field( 'email',  $fields['email']['value'], 'a@test.com' );
    }
    $record->set('fields', $fields);
