### ISSUE TITLE
Links in Slider Widget not rendered

### ISSUE THREAD

**Issue by hackerfabian** [elementor/elementor#13796]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In the slider widget I added some links to the buttons, but these links get not rendered in the frontend of my website. I'm using Elementor 3.1.1 and Elementor Pro 3.0.10

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
