### ISSUE TITLE
New Feature: integrating Zoho CRM forms with Elementor

### ISSUE THREAD

**Issue by inessenceva** [elementor/elementor#13794]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will allow me to move leads to my CRM and eliminate manually having to do it.

**Describe the solution you'd like**
I would like to integrate Zoho forms for catching leads into the Zoho CRM. This requires you to work with Zoho who I understand reaching out to you but haven't heard from your development team. I am not the only one looking for this option.

**Describe alternatives you've considered**
I am looking at using your webhook and Zoho flow to transfer the data to CRM at someone's suggestion or the plugin by IT Galaxy: Elementor Pro Form - Zoho CRM & Desk, which was someone else suggested. But rather have you work with Zoho to provide an integration.

**Additional context**
There are other elementor/Zoho users who really want this.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9158, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
