### ISSUE TITLE
Get Global Colors Value

### ISSUE THREAD

**Issue by AbanobAkram** [elementor/elementor#13802]
I'm trying to get a global color value in render() method of a widget, but I'm only getting this
`Array ( [premium_gradient_colors] => globals/colors?id=primary `

 Is there a way I can get global color values to be used later in my code?

Regards

**Comment by udidol** [comment]
Hi @AbanobAkram,
What you are getting is the key. What do you need the global color value for?
If you have a control in your widget with this global color set as its value, when you run `$this->get_settings_for_display()` in the `render()` method, you will get the parsed value and not the key.

**Comment by udidol** [comment]
Hi @AbanobAkram,
To get the system colors' values (primary, secondary, accent, text), you can run the following:

```
$kit = Plugin::$instance->kits_manager->get_active_kit_for_frontend();
$kit_settings = $kit->get_settings_for_display( 'system_colors' );
```
