### ISSUE TITLE
Change Swiper with TinySlider

### ISSUE THREAD

**Issue by nicmare** [elementor/elementor#13806]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Swiper Library is very heavy and bloated. It takes to much performance and affects Google Insights Page Speed

**Describe the solution you'd like**
You should drop that swiper library. I know you already have conditional asset loading. But this is not enough.

**Describe alternatives you've considered**
Consider switching to a lightweight library like [TinySlider](https://github.com/ganlanyuan/tiny-slider).

**Comment by shilo-ey** [comment]
Thanks, 

We recently moved to Swiper to allow general purpose and load it only on use.

Currently, we won't switch to a different library.

We will look into it in the future if we see a large demand for it.

Thanks for the feedback.
