### ISSUE TITLE
Section Background Slideshow - Dynamic Images

### ISSUE THREAD

**Issue by MartinJacksonUK** [elementor/elementor#13808]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Frustrating that I have to download and pay for yet another Elementor plugin.

A clear and concise description of what the problem is. 

Not being able to control images dynamically via ACF or similar solution provider.

**Describe the solution you'd like**

The ability to control the images used in the section background slideshow via ACF.

**Describe alternatives you've considered**

Plugin "Anywhere Elementor Pro" looks to offer this feature. https://aedocs.webtechstreet.com/article/40-background-slider

**Comment by shilo-ey** [comment]
I merged this issue with  #11056, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
