### ISSUE TITLE
Image Carousel Not Working

### ISSUE THREAD

**Issue by Anurag-Kaushik** [elementor/elementor#13813]
The image carousel on my elementor page suddenly stopped working after the recent stable release of elementor.

After updating, image carousel is not changing images and remains static. Even after clicking to arrow to navigate to other image, it does nothing.

Since the problem has started after updating, it seems to be a bug to me.

**Comment by ppulpipatnan** [comment]
There is javascript error "Cannot read property 'global' of undefined" when adding "image carousel slider" widget.

![Screen Shot 2564-02-05 at 14 21 45](https://user-images.githubusercontent.com/44386818/107002276-91f27d00-67bd-11eb-94da-7aaae0e2a00b.jpg)

Elementor 3.1.1

**Comment by kevtanner** [comment]
Having the same issue. Multiple other bugs on my site as well since the most recent release

**Comment by shilo-ey** [comment]
Sounds like JS error that broke this behavior.


Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

thanks.

**Comment by kgozman** [comment]
Turning the plug-in responsible for the carousel off and then on again seems to resolve the issue. I believe the origin of the problem is when you run an update the plug-ins get initialized in the incorrect order in the Elementor program need to be initialized first before addon-elementor plug-ins.
