### ISSUE TITLE
Make post widget excerpt clickable 

### ISSUE THREAD

**Issue by christiankroeber** [elementor/elementor#13814]
When using the post widget it would be so cool, if you could make the excerpt also clickable.

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
