### ISSUE TITLE
Header & Footer Theme Builder Issue

### ISSUE THREAD

**Issue by EquilibriumTechx** [elementor/elementor#13819]
HI Team, 

I am not sure if this is correct or not, 

header & footer cannot set elementor full width as the default template. it keeps on reverting to the default template.

**Comment by shilo-ey** [comment]
What do you mean
Can you please elaborate on the issue you are facing?
Steps to reproduce? Expected vs. actual behavior?

Thanks

**Comment by EquilibriumTechx** [comment]
issue is solved
