### ISSUE TITLE
Elementor updates 3.1.0 and 3.1.1 do not work with Elementor Pro on mobile 

### ISSUE THREAD

**Issue by Nadia2021** [elementor/elementor#13816]
Hai,
I am a website builder and I promote Elementor and Elementor Pro through my website.
But I would like to let you know that the updates of Elementor 3.1.0 and 3.1.1 do not work with Elementor Pro on mobile. Everything is ok on desktop, but on mobile the following issues arise:

- The menu dropdown doesn’t work anymore or the menu disappears
- Texts and elements disappear
- Fonts changes 
- The Elementor Pro form does not work on mobile. 

The websites that have not been updated are working perfectly (3.0.9).
I hope someone can do something about this.
Thank you so much.

**Comment by shilo-ey** [comment]
Hi @Nadia2021 
Thanks for your feedback.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
