### ISSUE TITLE
Need some clarifications

### ISSUE THREAD

**Issue by thegulshankumar** [elementor/elementor#13829]
1. elementor/document/after_save: Fires when document save is complete.
– Which document?

2. elementor/editor/after_save: Fires after Elementor saves data to the database.
– What types of data? Please share in example.

3. elementor/core/files/clear_cache: Fires after Elementor clears files
– Did you mean CSS and JS files created by Elementor?

PS. Not a Elementor user. So these are questions.

Thanks

**Comment by udidol** [comment]
1. The document being saved. If you are editing a page/post using Elementor, then saving it, the `elementor/document/after_save` hook will fire after the saving process is complete.

2. The `elementor/editor/after_save` is also fired when saving a document by Elementor. It is just fired earlier in the process, after the post meta is updated with the contents of the page (sections, columns, widgets etc.).

3. The `elementor/core/files/clear_cache` action fires after all of the custom CSS generated by Elementor is deleted from the `{site root}/wp-content/uploads/elementor/css` directory.
