### ISSUE TITLE
Posts Widget full content skin - the content not displayed

### ISSUE THREAD

**Issue by zivit-drori** [elementor/elementor#13822]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by zivit-drori** [comment]
Hi, in backend the content of the posts display, in front page only the title and the post image, if I choose not to display the title and image noting is display.

[system-info-www.new.zivit-design.co.il-06-02-2021.txt](https://github.com/elementor/elementor/files/5936353/system-info-www.new.zivit-design.co.il-06-02-2021.txt)
[log.txt](https://github.com/elementor/elementor/files/5936359/log.txt)

**Comment by zivit-drori** [comment]
Hi. I have roll back to the previous stable version of elementor
and still - Posts Widget full content skin is not displayed.

[system-info-www.new.zivit-design.co.il-07-02-2021.txt](https://github.com/elementor/elementor/files/5938304/system-info-www.new.zivit-design.co.il-07-02-2021.txt)

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by ruijt** [comment]
hi @zivit-drori did you found a solution for this problem? I have the same. Thanks!
