### ISSUE TITLE
WP YouTube Lyte does not work with the newest Elementor 3.1.1

### ISSUE THREAD

**Issue by dakini73** [elementor/elementor#13827]
Why WP YouTube Lyte plugin does not work with the newest Elementor 3.1.1 ??? WP YouTube Lyte is VERY useful for optimizing You Tube videos in websites! It worked very well before I updated Elementor! Now it does not work! Please, what shall I do to get the plugin work again??? You can not develope Elementor and ruin the functionality of other parts of the websites at the same time! People will turn back from you if you do so!

Regards
Kasia

**Comment by shilo-ey** [comment]
Hi @dakini73 

Thanks for your feedback.

First, please create an issue with the bug details.

Second, in v3.1 we introduced a better way of adding YouTube videos to your pages. 
From now on Elementor uses the YouTube API to parse the videos you add to your page and in this way they can be better adjust to work with YouTube technical API requirements.

If the plugin isn't working for you please check where's the problem.

If the problem resides on Elementor side - we will try to resolve it, if not - we will suggest you to contact this plugin author for better compatibility.

Thanks

**Comment by dakini73** [comment]
Hi,How do I create a ticket?"From now on Elementor uses the YouTube API to parse the videos you add to your page and in this way they can be better adjust to work with YouTube technical API requirements." - how do I use it? I updated to Elementor 3.1, noticed that the page with published youtube videos slowed down drastically (as the plugin WP YouTube Lyte) stopped working and downgraded to Elementor 2.9 again!!! I have video blog and it is ESSENTIAL that my website is fast eith 12-15 embedded YT videos / page!How do I exactly get Elementor to do this job as it DID NOT happrn automatically after upgrading to 3.1!RegardsKasia
-------- Oryginalna wiadomość --------Od: shilo-ey <notifications@github.com> Data: 07.02.2021  11:47  (GMT+01:00) Do: elementor/elementor <elementor@noreply.github.com> DW: dakini73 <dakini2@interia.pl>, Mention <mention@noreply.github.com> Temat: Re: [elementor/elementor] WP YouTube Lyte does not work with the
  newest Elementor 3.1.1 (#13827) 
Hi @dakini73
Thanks for your feedback.
First, please create an issue with the bug details.
Second, in v3.1 we introduced a better way of adding YouTube videos to your pages.
From now on Elementor uses the YouTube API to parse the videos you add to your page and in this way they can be better adjust to work with YouTube technical API requirements.
If the plugin isn't working for you please check where's the problem.
If the problem resides on Elementor side - we will try to resolve it, if not - we will suggest you to contact this plugin author for better compatibility.
Thanks
