### ISSUE TITLE
Clone Loop Template (unable to convert page to loop or clone loop templates)

### ISSUE THREAD

**Issue by gravnetic** [elementor/elementor#13825]
I find it very inconvenient that you are unable to clone a loop template with tools such as Duplicate Post.  Is there a way to clone a loop, or alternatively convert a page template to a loop.

**Comment by shilo-ey** [comment]
Hey,

The CMS items and entities are managed via WordPress, which has its own plugins and capabilities: e.g https://wordpress.org/plugins/duplicate-post/

Thanks

**Comment by gravnetic** [comment]
I can set the page template, popup, etc to be cloneable, but not a loop template?

**Comment by gravnetic** [comment]
@shilo-ey I hate to call this into question.  The ability to create a loop using a clone is not possible.  This at the very least is a feature request.
