### ISSUE TITLE
Add gallery support to image lightbox button

### ISSUE THREAD

**Issue by rtpHarry** [elementor/elementor#13824]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

This is a semi-duplicate of #13203 but that one was never acknowledged and doesn't follow the template.

**What problem is your feature request going to solve? Please describe.**
Please add support for selecting multiple images with the lightbox:

![image](https://user-images.githubusercontent.com/1038062/107123091-870a1c00-6893-11eb-9b7c-7e9c7ab3478c.png)

My client wants to add a button like "View Gallery" and it open up a slideshow lightbox, with multiple images.

The feature is already supported in some sense, because the Basic Gallery widget will open a lightbox. It allows navigating between other images in that gallery from within the lightbox:

![image](https://user-images.githubusercontent.com/1038062/107123175-039cfa80-6894-11eb-893f-c2171c3d4b0d.png)

The problem with this is that the entire gallery has to be on the page which doesn't work with that layout.

I appreciate that things are never that simple, and the underlying lightbox script might need some "encouragement" to get the image gallery source passed in by an array rather than reading it from the image media links on the gallery.

**Describe the solution you'd like**
Allow multiple images to be selected in the lightbox source instead of just one.

**Describe alternatives you've considered**
I've also searched Unlimited Elements and Crocoblock and couldn't find any solution from them either.

**Additional context**

**Comment by black-eye** [comment]
+1

**Comment by rtpHarry** [comment]
@black-eye ahh thanks for the heads up, I did do a search but didn't find that one.

**Comment by rtpHarry** [comment]
This won't solve it for everyone, but I have a pro version of [Unlimited Elements](https://unlimited-elements.com/) addon, so I have created an interim solution to my problem.

Here is an export of the button gallery widget:

  - [Download SOKA Button Gallery](https://1drv.ms/u/s!ApenyEmwMfcVgZ8nagnsmRUdCwWhgQ?e=EDt5Wf)

It adds an element in which has the basics, a gallery and a clickable trigger:

![image](https://user-images.githubusercontent.com/1038062/107128965-ad42b280-68b9-11eb-980b-e6309ce1ffb0.png)

This is just a starting point, intended for developers that understand html / css / twig.

It just outputs a simple button:

![image](https://user-images.githubusercontent.com/1038062/107129053-a1a3bb80-68ba-11eb-9545-f5bd129c37e8.png)

Which triggers a gallery lightbox:

![image](https://user-images.githubusercontent.com/1038062/107129071-c4ce6b00-68ba-11eb-8f4f-c6479e95de2a.png)


Some notes:

1. The button will need styling, which is actually as simple as adding `class="elementor-button"` to the trigger `<a>` link - I had just already exported and uploaded it before I realised.
1. I added some css in the css tab to undo some of the Elementor button styles - you might not need them depending on your theme setup.
1. I found that the built in lightbox was automatically triggering underneath my lightbox. It seems that you can manually disable it using `data-elementor-open-lightbox="no"` on a link pointing to a media file, which I've done in this widget.
1. If you're looking to modify this further, its powered by [Fancybox](https://fancyapps.com/fancybox/3/) which is bundled with Unlimited Elements.

**Comment by shilo-ey** [comment]
Hi all,

Thank you for your suggestion, we will consider adding it in the future.

I merged this issue with #8054, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
