### ISSUE TITLE
overflow issues when using e.g. 'fade to top' animation

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#13820]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

there are issues with horizontal overflow when using 'fade to top' animations.
no matter where and no matter if section, row or widget.

hunted this error for hours and blamed several plugins to be guilty before i found this! no theme issues, no plugin issues - just plain elementor fault.

would be great to have this solved with 3.1 too.

## Steps to reproduce

assign the mentioned animation to one ore more widgets or whatever and see.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
not needed.

</details>

**Comment by DorShahar** [comment]
Thanks for reporting,

I tried to reproduce the issue by assigning Entrance animation: "Fade in Up" but I didn't notice any problems. 

Therefore, if the problem persists: please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Accurate steps to replicate.
* System info.
* A video will be the best to reproduce and investigate

Without it, we simply can't help.

Thanks.
