### ISSUE TITLE
Display all responsive values at once

### ISSUE THREAD

**Issue by rtpHarry** [elementor/elementor#13823]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor has become my favourite page builder, but the responsive editing is a massive pain.

I want to be able to see all breakpoints settings at once, not just the current breakpoint.

It's a constant game of switching back up through the breakpoints to try and find which controls have values at higher breakpoints and are therefore affecting the current breakpoint.

Case in point:

![image](https://user-images.githubusercontent.com/1038062/107119419-51f3ce80-687f-11eb-9139-40c77db591b9.png)

This has a margin bottom of 10px at the desktop, but there is no hint that this is inheriting this value.

I have to switch back up to the top breakpoint to check.

Switching the breakpoints are really fiddly as the button to move between them is really small.

There is no keyboard shortcut to flip.

And then on most designs you have a complex layout, where the adjustment might be in the section, the column or the actual widget. 

Trying to track it down and memorise all the values between all the elements at play, plus their related values like paddings... it's a frustrating chore.

**Describe the solution you'd like**
I would like to be able to see all values at once to be able to edit them. 

This might not be everyone's preference as it would probably create a visually cluttered ui, but even if it was behind a "responsive edit mode" toggle it would improve things so much. 

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3356, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
