### ISSUE TITLE
Flip Box in combination with inner section

### ISSUE THREAD

**Issue by Flake-Webagentur** [elementor/elementor#13836]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
If you create an inner section and add inside of these inner section two flip boxes only the first one will be correctly displayed.
In the Creator the Issue will not come up. After looking in the preview the view looks crazy. (see additional picture)
![Elementor](https://user-images.githubusercontent.com/78703171/107158396-f19d8380-6989-11eb-8188-8482dba2c7a0.png)
![preview](https://user-images.githubusercontent.com/78703171/107158397-f2361a00-6989-11eb-815a-db88de5f08d2.png)

## Steps to reproduce
1. create an inner section
2. add two flip boxes 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @Flake-Webagentur 
Thanks for reporting.
Our QA staff looked into this and they couldn't reproduce the issue. Here is their testing site: https://tests.elementor.cloud/flip-box-in-combination-with-inner-section-13836/

If the problem continues, you are welcome to contact our support team with more information (system info will be the best).

Thanks

**Comment by Flake-Webagentur** [comment]
Hi @DorShahar,
I have had a look again. Could you please check in your test "no graphic picture". Then i get at my side a bad result. In the elementor editor it looks fine but the preview looks like the attached GIF.

![2021-02-15_21h17_45](https://user-images.githubusercontent.com/78703171/107990057-dd820380-6fd3-11eb-9641-91b4a5613e46.gif)

Thanks.
