### ISSUE TITLE
Elementor Editor not working with %postname% permalinks

### ISSUE THREAD

**Issue by triangle-stream** [elementor/elementor#13849]
Hello,

We have an Elementor Pro plan and an issue started to appear from yesterday. This issue cause elementor editor not working after publishing a page, so our pages are no more editable.

From the browser console log, these errors appears:
• TypeError: Cannot read property 'data' of undefined. [common.min.js?ver=3.1.1:2];
• Uncaught (in promise) TypeError: Cannot read property 'data' of undefined. [editor.min.js?ver=3.1.1:2]

Before the issue, nothing was changed server side and in wordpress (no plugin added). Tried to deactivate all of the plugins and theme but nothing changed.

In order to reproduce the issue, simply create a page, edit with elementor befor publishing, then publish the page. After this step, elementor editor is broken.
Only way to work is to not to close the elementor editor page after the page publishing. 

I though it could be a cache problem: cleared browser cache, wordpress cache and deactivated wp super cache plugin. Nothing changed.

Our wordpress [5.6.1] is hosted on a Centos7 VPS with PHP7.2 (i know it is old but for know we need to keep this version) and MySQL5.7. 

Also tried with elementor switch editor. Nothing changed.

On the server, files are served from Nginx 1.18 by using fastCGI microcache (no errors in nginx also with info loglevel).

The strange thing is that this happened without any change, as i mentioned above.

Here is the elementor log from sys info (from wordpress dashboard):

```
JS: showing 5 of 5
JS: 2021-01-04 16:52:00 [error X 1][https://glamitaly.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.15:2:332699] elementorFrontend is not defined 
JS: 2021-01-19 17:21:57 [error X 1][https://glamitaly.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.16:2:312533] elementor.config.document is undefined 
JS: 2021-01-19 17:21:58 [error X 1][https://glamitaly.it/wp-includes/js/wp-auth-check.min.js?ver=5.6:2:479] s is undefined 
JS: 2021-01-19 17:47:09 [error X 1][https://glamitaly.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.16:2:498557] PerfectScrollbar is not defined 
JS: 2021-02-09 08:49:05 [error X 1][https://glamitaly.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:546094] React is not defined 
Log: showing 3 of 3
2021-01-19 18:02:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-02-08 19:25:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.1',
)]
2021-02-08 19:26:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
PHP: showing 2 of 2
PHP: 2021-01-19 18:35:43 [notice X 1][/var/www/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::162] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-08 19:36:35 [notice X 1][/var/www/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```

Thank you!

**Comment by triangle-stream** [comment]
EDIT:
It seems to be something related to wordpress' permalink structure. 
If using simple format (page_id) elementor editor works also on published pages; 
if I set the permalink structure to be %postname% then elementor editor doesn't work anymore on published pages.

I've also simplified the nginx configuration, pausing the microcaching and using as usual.

**Comment by triangle-stream** [comment]
#11035 Seems to solve the issue. 

Closing this.

**Comment by ALPSIT** [comment]
I just want to give my experience with this issue which cost me hours and I eventually worked out.

I'm annoyed I didn't realise this earlier.

I had the same issue with post name permalink pages not loading elementor in published view and only as drafts view or if i changed the permalinks to plain. so i tried every solution in here to no prevail.

The page I was working on had 'Adwords' in the title and Adblock Plus was blocking the elements in the page from loading due the this naming. Took me a while to figure it out grrrr.. just incase anyone else runs into the same issue haha.

Regards,

Alp

**Comment by th3m00n** [comment]
> I just want to give my experience with this issue which cost me hours and I eventually worked out.
> 
> I'm annoyed I didn't realise this earlier.
> 
> I had the same issue with post name permalink pages not loading elementor in published view and only as drafts view or if i changed the permalinks to plain. so i tried every solution in here to no prevail.
> 
> The page I was working on had 'Adwords' in the title and Adblock Plus was blocking the elements in the page from loading due the this naming. Took me a while to figure it out grrrr.. just incase anyone else runs into the same issue haha.
> 
> Regards,
> 
> Alp

you saved me from wasting my time on this with your reply! I was going to be crazy with this :)) every page I tried to edit was ok except the one with the "Ad" word in the permalink and whenever I put the permalinks settings on plain permalinks everything was working fine! with your comment I got the problem is the "Ad" word in the permalink. I didn't get what exactly is cussing this?

Thank you so much @ALPSIT

**Comment by ALPSIT** [comment]
> > I just want to give my experience with this issue which cost me hours and I eventually worked out.
> > I'm annoyed I didn't realise this earlier.
> > I had the same issue with post name permalink pages not loading elementor in published view and only as drafts view or if i changed the permalinks to plain. so i tried every solution in here to no prevail.
> > The page I was working on had 'Adwords' in the title and Adblock Plus was blocking the elements in the page from loading due the this naming. Took me a while to figure it out grrrr.. just incase anyone else runs into the same issue haha.
> > Regards,
> > Alp
> 
> you saved me from wasting my time on this with your reply! I was going to be crazy with this :)) every page I tried to edit was ok except the one with the "Ad" word in the permalink and whenever I put the permalinks settings on plain permalinks everything was working fine! with your comment I got the problem is the "Ad" word in the permalink. I didn't get what exactly is cussing this?
> 
> Thank you so much @ALPSIT

I'm so glad that my comment saved you some time! i went crazy trying to figure this one out haha.

**Comment by Nemesis77swe** [comment]
This is still an issue!.
I changed my permalinks from the strange custom (that apparently was default?), to ,%postname%, and now I couldn't edit any pages, I had to change it to  plain to get elementor to work again...

**Comment by coma0815** [comment]
Yes - it is still an issue!

I have the same setup as described in the first post (php7.2; nginx; fastCGI, etc) and elementor will not load the editing page if
-> the page is published,
-> I change permalinks to "%postname%" AND
-> I edit the name of the post after that. 

From this moment on, the edit page does not load. 
Workaround is, to set the page into draft mode (so it is not published) - then it works like charm. do your changes in elementor and publish the page again..

I think this issue should be opened up again..

**Comment by teamvaluecreatives** [comment]
Still an issue

**Comment by craigjwallace** [comment]
Still an issue.

Tested plugin interference (none)
Elementor Pro editor fine on plain permalinks.
Elementro Pro 'the_content' error when %postname% -- even after resetting.

I simply can not change my site to plain links as I have external app traffic.

I will check my hosters to confirm no apache config errors.

Suffice to say after 4 hours of debugging I'm pretty annoyed at this.

**Comment by jakubmirejovsky** [comment]
For me it was **nginx config**.

This is my current working conf:
```
server {
            root /var/www/html/WORDPRESS_LOCATION;
            index index.php index.html;
            server_name DOMAIN.TLD;

	    access_log /var/log/nginx/blog.access.log;
    	    error_log /var/log/nginx/blog.error.log;

            location / {
            try_files $uri $uri/ /index.php?$args; 
}
            location ~ \.php$ {
                         include snippets/fastcgi-php.conf;
                         fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
            }
            
            location ~ /\.ht {
                         deny all;
            }

            location = /favicon.ico {
                         log_not_found off;
                         access_log off;
            }

            location = /robots.txt {
                         allow all;
                         log_not_found off;
                         access_log off;
           }
       
            location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                         expires max;
                         log_not_found off;
           }

    listen 80;
}
```

of course, you probably have SSL, different PHP version and other config here.

The important part is this rewrite:
```
location / {
            try_files $uri $uri/ /index.php?$args; 
}

```

Hope this helps. And again, this is a solution for **Wordpress + nginx**, not apache.

**Comment by lucassantosw** [comment]
Still an issue. Tried the tips above and nothing! Any updates please!

**Comment by grntco** [comment]
> This is still an issue!. I changed my permalinks from the strange custom (that apparently was default?), to ,%postname%, and now I couldn't edit any pages, I had to change it to plain to get elementor to work again...

This is exactly my problem. I created my site prior to changing the permalink structure to %postname%, realized my mistake after building the site with Elementor Pro's theme builder, and when I switch the structure from the default to %postname% my pages don't appear in the theme builder to edit. So, I just switched back to the default structure.

**Comment by rugter100** [comment]
I still have this issue. I tried the other bugreport linked in the conversation here and tried every solution in the comments i could find without success

**Comment by reinder** [comment]
Still an issue. (I'm using apache as webserver)

**Comment by Mexxez** [comment]
I am not an Apache nor am I a Ningx specialist. In my case the issue disappeared after changing from Nginx to Apache and renewing security headers (Really Simple SSL will not do it, it also breaks; PHP won't work; you have to do it in root .htaccess (still some issues) or via HTTP Headers plugin which I finally did). After renewing the headers permalinks had to be flushed immediately as almost all pages on frontend went to a 404. After flushing permalinks everything else so far works fine.

Possibly, the standard server config was not set to:
`X-Frame-Options: sameorigin`
and / or
`Content-Security-Policy: frame-ancestors 'self' https://www.example.org;`

https://elementor.com/help/requirements/
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

Server config may have interfered in another way. Probably security measures by the webhosting provider.

**Comment by fudojahic** [comment]
Is this been resolved?

**Comment by Feliperaw** [comment]
> For me it was **nginx config**.
> 
> This is my current working conf:
> 
> ```
> server {
>             root /var/www/html/WORDPRESS_LOCATION;
>             index index.php index.html;
>             server_name DOMAIN.TLD;
> 
> 	    access_log /var/log/nginx/blog.access.log;
>     	    error_log /var/log/nginx/blog.error.log;
> 
>             location / {
>             try_files $uri $uri/ /index.php?$args; 
> }
>             location ~ \.php$ {
>                          include snippets/fastcgi-php.conf;
>                          fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
>             }
>             
>             location ~ /\.ht {
>                          deny all;
>             }
> 
>             location = /favicon.ico {
>                          log_not_found off;
>                          access_log off;
>             }
> 
>             location = /robots.txt {
>                          allow all;
>                          log_not_found off;
>                          access_log off;
>            }
>        
>             location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
>                          expires max;
>                          log_not_found off;
>            }
> 
>     listen 80;
> }
> ```
> 
> of course, you probably have SSL, different PHP version and other config here.
> 
> The important part is this rewrite:
> 
> ```
> location / {
>             try_files $uri $uri/ /index.php?$args; 
> }
> ```
> 
> Hope this helps. And again, this is a solution for **Wordpress + nginx**, not apache.

This one worked for me! Also using Wordpress+Nginx Thanks a lot!

**Comment by GeorgeBogdanA** [comment]
It's all NGIX's fault, in the location condition it doesn't pass the arguments. 

In my case I replaced 
```
location / {
     try_files $uri $uri/ /index.php$args;
     expires 30d;
}
```
with
```
location / {
     try_files $uri $uri/ /index.php$is_args$args;
     expires 30d;
}
```
After you have changed the configuration file, remember to restart nginx:
`nginx -s reload`

Then you need to regenerate the permalinks in Wordpress:

WordPress Admin panel  -> Settings -> Permalinks:
Step 1: Change Permalinks to **Plain** and save.
Step 2: Change Permalinks to **Post** name and save.

This worked for us on a Magento integrated Wordpress using the Fishpig theme.

Credit: https://www.gokuldeepak.com/elementor-plugin-and-nginx-configuration/

**Comment by OSpotato** [comment]
https://www.youtube.com/watch?v=d3C-y9GsN9c - it solved my issue

**Comment by sriramgroot** [comment]
Recently, I had faced this issue in my local wordpress development.

1. Just by changing the configurations in the MAMP installation of **httpd.conf** with uncommenting "LoadModule rewrite_module modules/mod_rewrite.so"
2. By increasing the memory limit to 512M in php.ini
