### ISSUE TITLE
🔗 🚀 Feature Request: Prevent Scroll setting disables all Google Maps interactions (Duplicate of #1319)

### ISSUE THREAD

**Issue by JoelEadeDesign** [elementor/elementor#1384]
Heyo!

I've found when you enable Prevent Scroll for a Google Maps element that the +- zoom buttons, satellite/map toggle, "View larger map" links aren't clickable. I believe there's an overlay on the map that blocks all links.

My preference would be to disable mouse-wheel/trackpad scrolling but leave the other links/functional elements active.

Cheers!

**Comment by arielk** [comment]
Unfortunately it's not possible with the simple method of embed google map, just with the Maps API.

You can follow about this future enhancement here: #1319

Thanks for your feedback!
