### ISSUE TITLE
Code Highlight - direction

### ISSUE THREAD

**Issue by ishnechmad** [elementor/elementor#13846]
I encountered a text alignment issue in the 'Code Highlight' widget

It is important to emphasize that the language of my site is Hebrew, so the default alignment is from right to left, and this is probably what affects the text in this widget as well.

I solved the problem spot by point by adding CSS:
`selector{
    direction: ltr;
}`

**Comment by shilo-ey** [comment]
Hi @ishnechmad 

Thanks for your report.

From our inspection, it seems that the widget is always set to LTR. you might have a different CSS rule applied.

If the issue persists, please comment in the beta thread, and share a link for reference.

Thanks!
