### ISSUE TITLE
Copy and paste of style settings changes the image

### ISSUE THREAD

**Issue by PhilDrinkwater** [elementor/elementor#13841]
If I copy from one section or column to another, and there is an image in the background, it changes the image in the section I'm pasting to. In 99% of cases, that isn't the functionality I want - I want to keep the image as it was, but change the other settings (such as border etc...)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
