### ISSUE TITLE
Text Editor Block

### ISSUE THREAD

**Issue by DanishHaidri** [elementor/elementor#13858]
Hi,

For some reason, we are not able to update our Elementor page. We added a Text Block under the existing Heading Block. Here are the issues:

1. Test block text automatically displays in BLOD on the front end
2.  Unable to centre

We deleted all cache on website, server, browser and still the same problem. This has never happened before. How do we fix this issue?

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
