### ISSUE TITLE
Directory Widget

### ISSUE THREAD

**Issue by saguiitay** [elementor/elementor#13850]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When creating a website with a large amount of data, it is helpful to display the data in a Directory-like format - list of entries ordered alphabetically, with paging. This makes it easy for users to find whatever they are looking for.

**Describe the solution you'd like**
I'd like to have a Directory Widget, which will display a grouped (e.g. by First Letter) list of posts/pages, with support for paging.

**Describe alternatives you've considered**
I'm currently using a "Posts" widgets, which does not provide grouping by first letter.

**Additional context**

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
