### ISSUE TITLE
elementor multiple gallery - link to each gallery

### ISSUE THREAD

**Issue by iMiek** [elementor/elementor#13861]
I use the Elementor Pro gallery, type Multiple with different galleries.
I want to add a link to the each gallery so I can point straight to the seperate galleries in stead of standard gallery “All”.

See screenshot for example.
![Multiple-Galleries-links](https://user-images.githubusercontent.com/42237516/107378943-c3848480-6aec-11eb-82b2-3f9625d3fe63.jpg)

Thanks!

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by iMiek** [comment]
It's not a support questions but feature requests.....

**Comment by iMiek** [comment]
Hi, Dor_S



It's not a support questions but feature request…..

Met vriendelijke groet,


Mieke de Leeuw
Aanwezig op maandag, dinsdag, donderdag en vrijdag.








ideesign+
grafisch ontwerp + websites + drukwerk

Hoogstraat 14
6644 BT  Ewijk

06 4452 8596
ideesign.nl <http://ideesign.nl/>
