### ISSUE TITLE
Elementor no longer works 

### ISSUE THREAD

**Issue by lenmerlin** [elementor/elementor#13860]
Hello, elementor has not been displayed for some time. I download, reinstall, the latest version and this is what appears when I click on elementor 
![Sans titre-1](https://user-images.githubusercontent.com/13049536/107376195-e5303c80-6ae9-11eb-80c0-b1fd829a9c42.jpg)
does anyone have a solution?

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by lenmerlin** [comment]
I just downloaded the elementor system information file. In the meantime I restored a backup from the month of August hoping that this fixes the problem but it is not the case ;-( 
[system-info-edencamping.be-09-02-2021.txt](https://github.com/elementor/elementor/files/5952941/system-info-edencamping.be-09-02-2021.txt)
