### ISSUE TITLE
Create a template folder structure

### ISSUE THREAD

**Issue by garteth** [elementor/elementor#13864]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Making it easier to structure Elementor Templates

**Describe the solution you'd like**
A way of having a folder hierarchy for Elementor Templates.

Currently the templates are just dumped into the My Templates library, with no way to sort them. This would mainly be useful for sections saved as templates, but can be used for full page templates.

A great way would be allow the user to create the structure, similar to the plugin HappyFiles.
e.g.
Home
   -Top Section Template
   - Middle Section Template
   - Bottom Section Template
This way if you are creating a new page, and want to use an existing page section, you can easily get to it.

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #454, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
