### ISSUE TITLE
Templates to Menu

### ISSUE THREAD

**Issue by jkosoglow** [elementor/elementor#13867]
I created several templates for Elementor.  How the heck do I transfers so I can add to my menus?

Thanks.

Joe

**Comment by DorShahar** [comment]
Hi
Thanks for reaching out. 
This cannot be done at the moment. 

I'm merging this issue with #2587 for easier tracking (Adding templates to different elements).

Thanks.

**Comment by nicholaszein** [comment]
Hello there @jkosoglow!

We have great news! 🙌 

### 📢 We're happy to announce that the feature you requested was released with the new nested (Mega) Menu in Elementor Pro v3.12.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
