### ISSUE TITLE
Archive Posts widget needs a "Post count" setting

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#13879]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The current Archive Posts widget is locked to a post count of 10, which throws off layouts in 3, 4, and 6 column views (an single extra card appears at the bottom of the grid).

So for example a 3 x 3 grid ends up being 3 x 3 + 1:

```
[] [] []
[] [] []
[] [] []
[]
```

**Describe the solution you'd like**
It would be nice to allow post counts to be customised, eg we can set 9 posts so a 3 x 3 grid layout can be achieved.

```
[] [] []
[] [] []
[] [] []
```

**Describe alternatives you've considered**
The regular Posts widget has this feature but it is not suitable for Archive templates.

**Comment by rami-elementor** [comment]
It's not an Elementor issue, It's a WordPress issue. other page builders users report the same problem.

The solution is very simple, you should define to display 9 items in your archive pages. This will change the archive query.

![Reading-Settings-‹-dev-edition-—-WordPress](https://user-images.githubusercontent.com/92088692/175829515-888ae464-ba7b-4747-b945-2ae04b3330bd.png)
