### ISSUE TITLE
Post Widget - pause on hover not working

### ISSUE THREAD

**Issue by DigitalBerry** [elementor/elementor#13882]
I am seeing an issue with the Posts widget when using a custom template loop (ele custom skins plugin) and in slider mode that the posts do not pause on hover when function is active. 

![image](https://user-images.githubusercontent.com/62887371/107665584-7ee02100-6c85-11eb-861a-d7c855956d88.png)

Video of widget not pausing on hover - https://www.loom.com/share/54021cbb6a53405a8f0c73be65291ea3

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by G470** [comment]
I have exactly the same Problem. Would be nice to get this fixed.

**Comment by Jonatan-r** [comment]
Same problem! Any fix for this?

**Comment by Jonatan-r** [comment]
@ele-custom-skin @dudaster Are you aware of this problem? :)

**Comment by dudaster** [comment]
Yes I’m on it!

**Comment by arielk** [comment]
I'm closing an issue because it looks like an issue with a third-party plugin. If the problem still exists, feel free to reopen the issue or contact our support through your account.

Thanks

**Comment by tope0924** [comment]
Pause on hover is not working.

**Comment by Karthik-raj384** [comment]
I'm facing same issue with elementor pro the loop is not pausing on hover

**Comment by jemae31** [comment]
I have the same issue, I chose "NO" for the pause on hover option but when I hover on the images it still pauses,

**Comment by jemae31** [comment]
I have the same issue, I chose "NO" for the pause on hover option but when I hover on the images it still pauses,
