### ISSUE TITLE
Comments widget styling has no controls

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#13880]
The Comments widget is severely lacking in customisation options. It currently inherits a lot of whatever the original theme styles are, and if you're using something like Hello Elementor it basically defaults to system fonts.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9748, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
