### ISSUE TITLE
<!--more> HTML code breaks theme typography

### ISSUE THREAD

**Issue by flschroeter** [elementor/elementor#13884]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Adding HTML code in a post that results in text, like !--more--, which results in "(more...)" on the Posts page, breaks the typography for my theme - in this case, the "(more...)" gets the Monaco font and all content below inherits it. The fonts before are all sans-serif (Roboto aso.), so the difference is very obvious.

## Steps to reproduce

1. Use Twentyseventeen theme.
2. Create a post in Wordpress.
3. Add a text block.
4. Edit the post with Elementor.
5. Add the Wordpress HTML-block with !--more-- below the text block, to mark the part of the post that should be shown on the Posts page.
6. Add another block, e.g. a gallery.
7. Repeat 1 to 6.
8. View your Posts page.
Actual: All typography after the first post's "(more...)" is not what is defined in the theme, including the side bar. The same happens with Elementor's "Continue Reading"-block.
Additional Info: I have also tried to use the Elementor HTML block for the same purpose, but this results in all content below the HTML block not being shown.

Workaround: Place code manually after the end of the paragraph, like
`!-- /wp:paragraph --

!-- wp:more --
p></p
!-- /wp:more --`

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: SunOS
	Software: Apache/2.4.43 (Unix)
	MySQL version: Source distribution v5.6.42
	PHP Version: 7.4.13
	PHP Max Input Vars: 4000
	PHP Max Post Size: 76M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.1
	Site URL: https://www.kwsantiques.de
	Home URL: https://www.kwsantiques.de
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: en-GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 2.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:85.0) Gecko/20100101 Firefox/85.0

== Active Plugins ==
	Elementor
		Version: 3.1.1
		Author: Elementor.com

	Polylang
		Version: 2.9.2
		Author: WP SYNTEX

	Site Kit by Google
		Version: 1.25.0
		Author: Google

	UpdraftPlus - Backup/Restore
		Version: 1.16.47
		Author: UpdraftPlus.Com, DavidAnderson

	WPForms Lite
		Version: 1.6.4
		Author: WPForms


== Elementor - Compatibility Tag ==
	


== Elements Usage ==
	
	page : 3
		image : 2
		image-gallery : 2
		spacer : 3
		text-editor : 3
	wp-post : 1
		image : 1
		image-gallery : 2
		text-editor : 2
		wp-widget-custom_html : 2
	wp-page : 78
		image : 48
		image-gallery : 63
		spacer : 79
		text-editor : 82


== Log ==
	
Log: showing 12 of 122020-12-23 15:22:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '3.0.15',
)]
2020-12-23 15:22:59 [info] elementor::elementor_updater Started 
2020-12-23 15:22:59 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-12-23 15:22:59 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-12-23 15:22:59 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-12-23 15:23:00 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-12-23 15:23:00 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-12-23 15:23:00 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-12-23 15:23:00 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-12-23 15:23:00 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-12-23 15:23:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '3.0.15',
)]
2021-02-09 17:50:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.1.1',
)]


				
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
