### ISSUE TITLE
Shortcode not displaying on the frontend when using the Heading widget

### ISSUE THREAD

**Issue by Hubvill** [elementor/elementor#13894]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

When I try to add a shortcode to the heading widgets Title box the shortcode does not get displayed. All I see is the shortcode text for example [shortcode]. Nothing is rendered on the frontend. Is there a way to fix this?

Thanks!

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
