### ISSUE TITLE
Revisions are not working Properly

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#13909]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When you are working on a Page for example. In come cases you can't view the content on the revision. This is critical when you are creating new versions, so I think this should be fixed asap.

https://www.loom.com/share/e4db8063b12d4a24a6676b9830eb0109

## Steps to reproduce
Edit a page multiple times. Check the revisions. No content is shown.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.2.32
	PHP Max Input Vars: 10000
	PHP Max Post Size: 4096M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.1
	Site URL: https://www.pedrocastre.com
	Home URL: https://www.pedrocastre.com
	WP Multisite: No
	Max Upload Size: 4 GB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: America/Lima
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 2.0.2
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

== Active Plugins ==
	ActiveCampaign
		Version: 8.1.5
		Author: ActiveCampaign

	Autocomplete WooCommerce Orders
		Version: 1.3.4
		Author: QuadLayers

	Checkout Field Editor for WooCommerce
		Version: 1.4.5
		Author: ThemeHigh

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Crisp
		Version: 0.27
		Author: Crisp

	Custom Code
		Version: 1.0
		Author: Alberto Uozumi

	Elementor
		Version: 3.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.1.0
		Author: Elementor.com

	Facebook for WordPress
		Version: 3.0.3
		Author: Facebook

	Google Tag Manager for Wordpress
		Version: 1.11.6
		Author: Thomas Geiger

	Insert Headers and Footers
		Version: 1.5.0
		Author: WPBeginner

	JetBlog For Elementor
		Version: 2.2.12
		Author: Crocoblock

	JetEngine
		Version: 2.6.4
		Author: Crocoblock

	Ocean Elementor Widgets
		Version: 1.0.16
		Author: OceanWP

	Ocean Extra
		Version: 1.7.1
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.1.8
		Author: OceanWP

	PixelYourSite
		Version: 8.0.6
		Author: PixelYourSite

	Smush
		Version: 3.8.2
		Author: WPMU DEV

	SurveySlam
		Version: 1.9.1
		Author: The SurveySlam Team

	WC-AC Hook
		Version: 1.3.2
		Author: Matthew Treherne

	WooCommerce
		Version: 5.0.0
		Author: Automattic

	WooCommerce PayPal Checkout Gateway
		Version: 2.1.1
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 4.8.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.3.4
		Author: Prospress Inc.

	YITH Custom ThankYou Page for Woocommerce Premium
		Version: 1.1.4
		Author: YITH

	Yoast Duplicate Post
		Version: 4.1.1
		Author: Enrico Battocchi & Team Yoast

== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible
	JetBlog For Elementor: header_not_exists
	Ocean Elementor Widgets: header_not_exists

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		form : 2
		heading : 12
		icon-box : 4
		icon-list : 2
		image : 2
		text-editor : 4
	header : 1
		button : 1
		icon-box : 5
		nav-menu : 2
		theme-site-logo : 2
	page : 13
		accordion : 1
		button : 41
		countdown : 6
		counter : 10
		divider : 29
		flip-box : 43
		form : 3
		gallery : 2
		heading : 157
		html : 1
		icon : 27
		icon-box : 82
		icon-list : 11
		image : 76
		image-box : 12
		image-carousel : 9
		image-gallery : 1
		jet-listing-grid : 3
		nav-menu : 6
		portfolio : 3
		price-table : 12
		progress : 9
		shortcode : 1
		slides : 2
		spacer : 45
		text-editor : 64
		theme-site-logo : 1
		toggle : 5
		video : 8
	popup : 4
		button : 3
		form : 1
		heading : 4
		text-editor : 1
	section : 8
		animated-headline : 1
		button : 4
		heading : 17
		icon-list : 4
		image : 6
		spacer : 11
		text-editor : 4
		video : 1
	wp-post : 1
		blockquote : 3
		divider : 9
		form : 3
		heading : 12
		icon-list : 3
		image : 6
		text-editor : 12
	wp-page : 34
		button : 41
		countdown : 8
		counter : 4
		divider : 31
		flip-box : 11
		form : 4
		gallery : 11
		heading : 251
		html : 14
		icon : 11
		icon-box : 43
		icon-list : 20
		image : 74
		image-box : 4
		image-carousel : 9
		image-gallery : 2
		jet-blog-smart-tiles : 1
		jet-listing-grid : 5
		nav-menu : 2
		portfolio : 1
		posts : 1
		price-table : 4
		progress : 3
		shortcode : 4
		social-icons : 1
		spacer : 97
		text-editor : 99
		theme-site-logo : 1
		toggle : 6
		video : 12
	single-post : 2
		form : 2
		heading : 6
		icon : 2
		image : 2
		jet-listing-dynamic-field : 7
		jet-listing-dynamic-link : 1
		jet-listing-dynamic-meta : 2
		post-comments : 2
		post-info : 1
		posts : 2
		share-buttons : 1
		theme-post-content : 2
		theme-post-title : 2
	jet-listing-items : 0
		heading : 4
		icon : 1
		icon-list : 1
		image : 3
		jet-listing-dynamic-field : 8
		jet-listing-dynamic-link : 3
		jet-listing-dynamic-meta : 1
		post-info : 2

== Log ==
	
Log: showing 20 of 232021-01-09 09:53:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-09 09:53:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-09 09:53:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-09 09:53:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-09 09:53:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-22 04:14:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2021-01-22 04:14:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2021-01-31 13:53:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.1',
)]
2021-02-15 04:43:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-15 04:43:21 [info] elementor-pro::elementor_pro_updater Started 
2021-02-15 04:43:21 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-15 04:43:22 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-15 04:43:22 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-15 04:43:22 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-15 04:43:22 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-15 04:43:23 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-15 04:43:23 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-15 04:43:23 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-15 04:43:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-15 04:43:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]

PHP: showing 4 of 4PHP: 2021-01-31 13:53:06 [error X 1][/home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/core/admin/admin.php::242] Uncaught Error: Class 'Elementor\Tools' not found in /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/core/admin/admin.php:242
Stack trace:
#0 /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/plugin.php(327): ElementorPro\Core\Admin\Admin->__construct()
#1 /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/plugin.php(108): ElementorPro\Plugin->__construct()
#2 /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/plugin.php(339): ElementorPro\Plugin::instance()
#3 /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/home/admin/web...')
#4 /home/admin/web/pedrocastre.com/public_html/wp-includes/class-wp-hook.php(287): elementor_pro_load_plugin('')
#5 /home/admin/web/pedrocastre.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 /home/admin/web/pedrocastre.com/public_html/wp-includes/plugin.php(484): WP_Hook->do_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-31 13:53:06 [error X 2][/home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Call to undefined method Elementor\Modules\AdminBar\Module::get_experimental_data() in /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor/includes/plugin.php(600): Elementor\Core\Modules_Manager->__construct()
#1 /home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor/includes/plugin.php(514): Elementor\Plugin->init_components()
#2 /home/admin/web/pedrocastre.com/public_html/wp-includes/class-wp-hook.php(287): Elementor\Plugin->init('')
#3 /home/admin/web/pedrocastre.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /home/admin/web/pedrocastre.com/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /home/admin/web/pedrocastre.com/public_html/wp-settings.php(557): do_action('init')
#6 /home/admin/web/pedrocastre.com/public_html/wp-config.php(68): require_once('/home/admin/web...')
#7 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-03 11:06:35 [notice X 1][/home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/portfolio.php::50] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-10 09:17:33 [notice X 1][/home/admin/web/pedrocastre.com/public_html/wp-content/plugins/elementor/includes/widgets/image-carousel.php::705] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 16 of 16JS: 2021-02-03 16:06:16 [error X 2][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:120231] Failed to execute \'readAsDataURL\' on \'FileReader\': parameter 1 is not of type \'Blob\'. 
JS: 2021-02-11 14:35:32 [error X 2][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:191239] Cannot read property \'html\' of undefined 
JS: 2021-02-11 15:27:26 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4138\") has already been destroyed and cannot be used. 
JS: 2021-02-11 15:29:12 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view11142\") has already been destroyed and cannot be used. 
JS: 2021-02-11 15:30:52 [error X 4][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view171\") has already been destroyed and cannot be used. 
JS: 2021-02-11 15:31:24 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view12952\") has already been destroyed and cannot be used. 
JS: 2021-02-13 14:18:39 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3246\") has already been destroyed and cannot be used. 
JS: 2021-02-13 14:19:49 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view612\") has already been destroyed and cannot be used. 
JS: 2021-02-13 14:20:19 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1766\") has already been destroyed and cannot be used. 
JS: 2021-02-13 14:20:26 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3324\") has already been destroyed and cannot be used. 
JS: 2021-02-13 14:27:15 [error X 3][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view154\") has already been destroyed and cannot be used. 
JS: 2021-02-13 15:00:22 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view68173\") has already been destroyed and cannot be used. 
JS: 2021-02-13 15:32:08 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2392\") has already been destroyed and cannot be used. 
JS: 2021-02-13 15:34:59 [error X 2][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view180\") has already been destroyed and cannot be used. 
JS: 2021-02-13 17:32:17 [error X 3][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view157\") has already been destroyed and cannot be used. 
JS: 2021-02-15 09:33:51 [error X 1][https://www.pedrocastre.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1596\") has already been destroyed and cannot be used. 

				
</details>

**Comment by shilo-ey** [comment]
Hi @maurocarreraok 

Thanks for your input.

Elementor saves the content of your page as an array of JSON properties in the page.

When switching from Elemenor to WordPress native post - it removes some properties, this is the reason for this behavior.


For best results, you can use the Revisions from within Elemnetor and get live preview for this:

**Comment by maurocarreraok** [comment]
Hey @shilo-ey ! How are you?

Thanks in advance. But there is no way to "compare" the versions? Even showing on the "Classic" revisions panel the two versions of the JSON code?

Is sometimes faster if we can quickly search for a word on a code than looking for the complete design.

Other thing... sorry for bringing this again into the table but did you see my reply on: https://github.com/elementor/elementor/issues/13637 ??

Thank you so much.

Have a nice one.

**Comment by shilo-ey** [comment]
The comparison here is visual, not in the code level.

You can create a new feature request for the ability to compare between revisions if it's something you find useful.

As for the other request - there's an open feature request prior to the one you made:
#9719 - we will check if there's a possible solution for that.


Thanks again
