### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by fredwave** [elementor/elementor#13908]
There has been a critical error on this website.

Learn more about debugging in WordPress.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
