### ISSUE TITLE
vertical align not working in layout V 

### ISSUE THREAD

**Issue by souqalshoorja** [elementor/elementor#13900]
Hi .....
can pleas help how fix this issue as this link:

 https://streamable.com/w9fqqa 

when try to Align Products in home page, shop. Category page ..etc not work in elementor such as in video link .vertical Align not work . I looked in help, support pages not found any solution to solve this problem. .ELEMENTOR LAST UPDATE...hope to help fix this issue . regards
----------------------------------------------------------------------------------------------------------------
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.49-89.0
	PHP Version: 7.4.14
	PHP Max Input Vars: 2500
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.1
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 500M
	Permalink Structure: /%postname%
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
