### ISSUE TITLE
[Bug] How to set the Google ReCaptcha language with Elementor Pro ?

### ISSUE THREAD

**Issue by arthur911p** [elementor/elementor#13924]
Hi, I have a French website which uses Elementor Pro pop-ups. 
The language used with the reCapatcha is English only, I would like to be able to force the language (French only). How can I do ?

Thank you.

**Comment by DorShahar** [comment]
Hi,
Thanks for reaching out.

Please take a look in the code snippets [here](https://github.com/elementor/elementor/issues/3756) and [here](https://github.com/elementor/elementor/issues/4060) for this case.

If need, you can look for additional help in the Facebook Elementor communities

Thanks.

**Comment by arthur911p** [comment]
Hi, 
Thanks for your reply, i saw this topic but i didnt understand how to use this answer. Where should it be added?

 function add_language_to_recaptcha(){
    // Remove Elementor's script
    wp_deregister_script( 'elementor-recaptcha-api' );
    // Re-add with language param in url
    wp_register_script( 'elementor-recaptcha-api', 'https://www.google.com/recaptcha/api.js?render=explicit&hl=pt-BR' );
}
add_action( 'elementor/preview/enqueue_scripts', 'add_language_to_recaptcha', 9 );
add_action( 'elementor_pro/forms/render_field/recaptcha', 'add_language_to_recaptcha', 9 );
