### ISSUE TITLE
error Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by Ahmedegt441** [elementor/elementor#13931]
Fatal error: Uncaught TypeError: Elementor\Elements_Manager::create_element_instance(): Argument #1 ($element_data) must be of type array, string given, called in C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\core\base\document.php on line 810 and defined in C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\includes\managers\elements.php:68 Stack trace: #0 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\core\base\document.php(810): Elementor\Elements_Manager->create_element_instance(‘Array’) #1 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\core\base\document.php(535): Elementor\Core\Base\Document->get_elements_raw_data(Array, true) #2 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\includes\base\controls-stack.php(923): Elementor\Core\Base\Document->get_initial_config() #3 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\core\editor\editor.php(527): Elementor\Controls_Stack->get_config() #4 C:\xampp\htdocs\bourbon\wp-includes\class-wp-hook.php(287): Elementor\Core\Editor\Editor->enqueue_scripts(”) #5 C:\xampp\htdocs\bourbon\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(”, Array) #6 C:\xampp\htdocs\bourbon\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #7 C:\xampp\htdocs\bourbon\wp-includes\script-loader.php(2004): do_action(‘wp_enqueue_scri…’) #8 C:\xampp\htdocs\bourbon\wp-includes\class-wp-hook.php(287): wp_enqueue_scripts(”) #9 C:\xampp\htdocs\bourbon\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(”, Array) #10 C:\xampp\htdocs\bourbon\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #11 C:\xampp\htdocs\bourbon\wp-includes\general-template.php(3005): do_action(‘wp_head’) #12 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\includes\editor-templates\editor-wrapper.php(31): wp_head() #13 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\core\editor\editor.php(322): include(‘C:\\xampp\\htdocs…’) #14 C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\core\editor\editor.php(163): Elementor\Core\Editor\Editor->print_editor_template() #15 C:\xampp\htdocs\bourbon\wp-includes\class-wp-hook.php(287): Elementor\Core\Editor\Editor->init(”) #16 C:\xampp\htdocs\bourbon\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(”, Array) #17 C:\xampp\htdocs\bourbon\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #18 C:\xampp\htdocs\bourbon\wp-admin\admin.php(408): do_action(‘admin_action_el…’) #19 C:\xampp\htdocs\bourbon\wp-admin\post.php(12): require_once(‘C:\\xampp\\htdocs…’) #20 {main} thrown in C:\xampp\htdocs\bourbon\wp-content\plugins\elementor\includes\managers\elements.php on line 68

i cant edit the page and it didnt opened
i use astra theme
and it after add a block from astra library to elementor
i also tried disable Elementor – Header, Footer & Blocks
and stil some problem
but it just for the homepage

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
