### ISSUE TITLE
Conflict issue with unlimited widget -  Elementor Pro

### ISSUE THREAD

**Issue by jamdevweb** [elementor/elementor#13936]
Hi, I already open support ticket on my account at elementor 3 days before until now i don't receive ant response on my ticket.

Actually, i start face conflict issue with last update version from elementor, i used before the unlimited widget plugin and its working fine, after the last update i start face the conflict, i checked the cause of the issue and its come from elementor pro core file.
I already share the system status and the page link where the issue comes on my ticket. 

Please check it and update me my work stop because of this issue.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

From our support department I've been told that they responded your ticket, please take a look and keep communication there.

Thanks.
