### ISSUE TITLE
Share Button Widget and AdGuard Chrome Extention

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#13942]
If the AdGuard Chrome Extention is installed and active then the Share Button Widget is invisible in the elementor editor and can only be accessed using the navigator. It also cannot be seen in preview mode or on the front end.

**Comment by DorShahar** [comment]
Hi
Thanks for reaching out.
This is an extreme edge-case. If you are a pro user - you are welcome to contact our support for help.
If you are familiar with CSS, you can target the button and use `!important` to display it. 

Thanks
