### ISSUE TITLE
Custom Code Not Publishing

### ISSUE THREAD

**Issue by tinotriste** [elementor/elementor#13940]
Hi,

Just tested the new Custom Code feature but it's not saving the code under "publish settings"
See attached screencast.

Thanks

https://user-images.githubusercontent.com/3301661/108191039-964a5e80-710a-11eb-8dab-109830928fc3.mov

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
