### ISSUE TITLE
Nav Menu Widget Pro - Why can't you set different alignments for desktop, tablet, mobile.

### ISSUE THREAD

**Issue by myfatalparadox** [elementor/elementor#13949]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I want to align my horizontal menu on the desktop to the right, but on tablet I would like the horizontal menu to fall below the logo and be centered. There is only an option to align the item once across all devices which is really annoying.

**Describe the solution you'd like**
I'd like to be able to align the menu separately across each device.

**Describe alternatives you've considered**
There are other plugins that will do this but I would prefer to use Elementor's default nav widget to not add extra bulk to my sites with additional plugins when this seems like such a simple fix.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
