### ISSUE TITLE
How to close popup by vanila js or jquery ?

### ISSUE THREAD

**Issue by abhisavadiya** [elementor/elementor#13965]
I created popup which will show after scrolling 30% of page When popup show after that I scroll up it's not hide than how can i hide ?

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
