### ISSUE TITLE
Background graphics are not displayed

### ISSUE THREAD

**Issue by dexu** [elementor/elementor#13968]
Background graphics are not displayed.
The page looks correct in the editor. After exiting the editor, it is run over and does not display graphics in the background. As if something with CSS is wrong.

[https://malgorzata-gruszka.pl/](url)

**Comment by dexu** [comment]
![image](https://user-images.githubusercontent.com/7745689/108520459-fd167600-72ca-11eb-9ca2-64b4164d9c1b.png)
Here's the problem in CSS. Instead of a period, there is a comma.

**Comment by DorShahar** [comment]
Hi @dexu 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
