### ISSUE TITLE
Widget improvement and new request

### ISSUE THREAD

**Issue by manthankanani** [elementor/elementor#13964]
I know elementor very well and an expert too. But for some days I found some new feature that should be in elementir widget.

>  There is no datatable widget.

>  Where I can't use widget inside widget like in accordion or tab view I can't use code highlight(recently made), heading or other simple widget as content directly.

>  Shop page ajax filter

> input type=range in form widget in elementor pro

**Comment by DorShahar** [comment]
ן @manthankanani 
Thanks for reaching out.
As for your comments:
- We are thinking about a table widget, we have some blockers in the implementation of it, which we aim to solve this year
- This is part of our roadmap for this year. 

For all the rest - please open a feature request for each topic, so we could evaluate the need much better. 

Thanks
