### ISSUE TITLE
Global Colors and Global Fonts Improvements

### ISSUE THREAD

**Issue by 2000holmes** [elementor/elementor#13978]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would really appreciate being able to reorder and duplicate global colors and fonts. 

For example, I may begin building my site with just one page title style, but discover later on that I need a similar, smaller hero style as well. I can create a new style at the bottom of the Global Fonts list, *but both are hero styles*, and I’d prefer putting them next to each other on the list (Blame obsessive-compulsive tendencies, but still). 

Similar problems occur with adding a new accent color in Global Colors.

To do the example above, I’d also need to remember what styles I gave the large hero while building out the small hero or switch between the two pop-ups a few times. This is a minor frustration, but a real one when working on a site with a few similar styles.

**Describe the solution you'd like**
I would really appreciate having duplicate and reorder options next to the delete option for Global Fonts and Global Colors.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12203, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
