### ISSUE TITLE
Elementor condition not work as well after update 3.1.0

### ISSUE THREAD

**Issue by sinashamsizadeh** [elementor/elementor#13974]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After release version 3.1.0 I realize that conditions will not work some times, It's a bit confusing, because this problem happens sometimes. Has anyone like me had this problem?

When it happen, It will resolve by refreshing page

## Isolating the problem

- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
