### ISSUE TITLE
Invert columns setting does not work correctly when using custom breakpoints

### ISSUE THREAD

**Issue by jszineap** [elementor/elementor#13975]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If you have custom breakpoints, the "Inverting columns" options will use the default breakpoints of Elementor, and not the custom breakpoints that I've set.
![image](https://user-images.githubusercontent.com/26528975/108594520-7c965a80-7348-11eb-87c4-029e0bd5a664.png)

![image](https://user-images.githubusercontent.com/26528975/108594543-9b94ec80-7348-11eb-95ef-079368b88de9.png)

Inverted below 768px:

![image](https://user-images.githubusercontent.com/26528975/108594567-bc5d4200-7348-11eb-9568-c34ce9e81689.png)

Not inverted: (which should be as my mobile breakpoint is 999px)

![image](https://user-images.githubusercontent.com/26528975/108594579-ca12c780-7348-11eb-9fda-31677e469f54.png)

(Also and slightly off-topic: Why can't we set breakpoints above 1439px? We usually want 1500px - 1023px breakpoints but 1439 is the maximum)

--

## Steps to reproduce

Edit the breakpoints.

Invert columns on mobile.

Test between the default breakpoints and the custom ones.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.33
	PHP Version: 7.2.34
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.1
	Site URL: redacted
	Home URL: redacted
	WP Multisite: No
	Max Upload Size: 64 Mo
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	AnyWhere Elementor Pro
		Version: 2.17.3
		Author: WP Vibes

	Custom Post Type UI
		Version: 1.8.2
		Author: WebDevStudios

	Duplicate Post Page Menu & Custom Post Type
		Version: 1.6.0
		Author: Inqsys Technology

	DynamicConditions
		Version: 1.4.6
		Author: RTO GmbH

	Elementor
		Version: 3.1.1
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.10
		Author: WP Vibes

	Elementor Pro
		Version: 3.1.0
		Author: Elementor.com

	LiteSpeed Cache
		Version: 3.6.2
		Author: LiteSpeed Technologies

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro: compatible
	Elementor Addon Elements: compatible
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	
	AnyWhere Elementor Pro: incompatible
	Elementor Addon Elements: incompatible

== Elements Usage ==
	
	header : 1
		html : 1
		icon : 1
		nav-menu : 1
	section : 3
		ae-post-blocks-adv : 1
		button : 2
		heading : 4
		html : 4
		image : 3
		text-editor : 1
	widget : 0
		ae-post-blocks-adv : 4
	wp-post : 0
		ae-post-blocks-adv : 1
		button : 6
		heading : 10
		html : 5
		image : 6
		text-editor : 3
		theme-post-featured-image : 1
		video : 1
	wp-page : 1
		ae-acf-repeater : 1
		ae-post-blocks-adv : 2
		button : 3
		divider : 1
		heading : 4
		html : 4
		image : 3
		text-editor : 1

== Log ==
	
PHP: showing 3 of 3PHP: 2021-01-28 07:27:19 [notice X 8][/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-29 06:20:53 [notice X 8][/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-29 07:28:44 [notice X 2][/wp-content/plugins/elementor/core/dynamic-tags/manager.php::75] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 13 of 13JS: 2021-01-29 13:35:11 [error X 2][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.0:2:280102] Cannot read property \'id\' of null 
JS: 2021-01-29 14:06:14 [error X 3][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.0:2:467361] Cannot read property \'route\' of undefined 
JS: 2021-01-30 09:54:14 [error X 1][/wp-content/plugins/elementor/assets/js/preloaded-elements-handlers.min.js?ver=3.1.0:2:24762] this.elements.$video[0].play is not a function 
JS: 2021-01-30 10:08:51 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view179\") has already been destroyed and cannot be used. 
JS: 2021-02-01 04:47:45 [error X 2][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view183\") has already been destroyed and cannot be used. 
JS: 2021-02-01 10:35:08 [error X 3][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view122\") has already been destroyed and cannot be used. 
JS: 2021-02-06 06:07:25 [error X 3][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view101\") has already been destroyed and cannot be used. 
JS: 2021-02-17 08:13:09 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view91\") has already been destroyed and cannot be used. 
JS: 2021-02-17 08:26:08 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view93\") has already been destroyed and cannot be used. 
JS: 2021-02-17 09:57:11 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view48362\") has already been destroyed and cannot be used. 
JS: 2021-02-17 09:57:11 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view48295\") has already been destroyed and cannot be used. 
JS: 2021-02-17 09:57:11 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view48445\") has already been destroyed and cannot be used. 
JS: 2021-02-17 09:57:11 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view48331\") has already been destroyed and cannot be used. 

Log: showing 12 of 122021-02-02 04:13:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-02-17 01:52:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-17 01:52:26 [info] elementor-pro::elementor_pro_updater Started 
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-17 01:52:26 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-17 01:52:27 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-17 01:52:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]

				</summary>
</details>

**Comment by DorShahar** [comment]
Hi @jszineap 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by jszineap** [comment]
Hi DorSharar,

We found the issue and it is caused by frontend-legacy, which seems to be incompatible with the new breakpoints.

As frontend-legacy is only activated when optimized DOM delivery is activated, and the latter is in Beta, I feel like the experiment process is counterintuitive. If it's in Beta, regular settings should work without us having experiments activated.
