### ISSUE TITLE
FEATURE REQUEST | Random/shuffle mode in Animated Headline Widget

### ISSUE THREAD

**Issue by ilmanto13** [elementor/elementor#13977]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Missing "shuffle/random" mode in animated headlines widget.
A way to randomize the items in the "rotating text" box.

**Describe the solution you'd like**
A "randomize" built in button in the widget.

**Describe alternatives you've considered**
I couldn't find any plugin that can solve this problem.

**Additional context**
None.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.

**Comment by VulkraneFalls** [comment]
I'd love to see a randomize button in the widget, would be lifechanging
