### ISSUE TITLE
Bug in elementor video widget

### ISSUE THREAD

**Issue by cloudcreatr** [elementor/elementor#13983]
The story starts with a issue called as 'reduce the impact of third-party code in page Speed insight

This occurred when I embedded the YouTube video on my page with elementor video widget 

This drastically reduced my speed and score in page Speed insight

Screenshot of the error
https://drive.google.com/file/d/17d8NYnJ06G9VRcLZpvtr_ojqjs7Cbav5/view?usp=drivesdk

After researching I came across some plugin like wp youtube lyte and wp rocket 🚀

I use wp rocket

There's a option in wp rocket to replace the YouTube iframe with preview image, which I turned on 

But unfortunately it didn't worked for me,

 I even used wp youtube lyte but no change in speed and score it was still worse 

There's was no change in speed after I turned the video optimization in respectively plugins

The page was build with elementor

Then I started to test

In test 1

(Wp rocket 'YouTube iframe with preview image' was turned on)

I made a page (blank canvas) with the native wordpress editor and only embedded the YouTube video(only pasted the link in Gutenberg block editor and published), 

then I saw that the  Google page insight score were amazing and there were no issues about the third party code impact

After that 

I removed the option/turn off the option in wp rocket about replace the YouTube iframe with preview image.

The score went worse and it showed the issue of third-party impact 

Still I am using the blank canvas build in test 1

Then I again turned the option on and Page speed insight score improved

Screenshot
https://drive.google.com/file/d/17YpQ_j8IhFd3OhYgayUGqPa-Cm3vnNyd/view?usp=drivesdk

This tells that the wp rocket and wp YouTube lyte was working properly

Test 2 

This time I created a blank page with elementor and I embedded only the YouTube video using the video widget in elementor and this time the wp rocket 'replace the YouTube iframe with preview image' was turned on

I checked the scores and I found the score and speed were still worse and showed the error 

Reduce the impact of third-party code

Screenshot of the error
https://drive.google.com/file/d/17d8NYnJ06G9VRcLZpvtr_ojqjs7Cbav5/view?usp=drivesdk

This show that there's something bug in the elementor video widget that doesn't allow wp rocket and wp YouTube lyte to optimise the YouTube video for speed or replace the iframe 

Hope you understand

Please 🙏 anybody fix this issue

I embedd a lot of video and  I use elementor

Inspite of turning on the optimization options (replace YouTube iframe with preview image) in wp rocket 

elementor video widget slow down the website
And shows the error in page Speed insight

There's is a way around for this issue/alternative

Use text editor widget in elementor
Place the link of YouTube video directly in the text editor
Then YouTube video will be embedded
Then it will be optimised by wp rocket 

But there's no much styling option
It's not well optimised in terms of design
You can use the features you get in video widget elementor

Please fix this issue as soon as possible
Eagerly waiting for your reply

**Comment by arielk** [comment]
We currently have Lazy Load for video widget, so please try this out. Anyway I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
