### ISSUE TITLE
TypeError: Cannot read property ‘global’ of undefined

### ISSUE THREAD

**Issue by mehditayebi** [elementor/elementor#13981]
Hi. When I edit Custom element Items I get this error in console live preview.
So this doesn’t let me see live preview in editing mode.
Elementor version : 3.1.1
Works fine if I switch to a version 3.0.6

![Rh7Gaa8](https://user-images.githubusercontent.com/10958447/108620076-bba6d780-743e-11eb-8d60-8cf793d58a89.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it, we simply can't help.

Thanks.
