### ISSUE TITLE
Dynamic Facebook page

### ISSUE THREAD

**Issue by AndreasH08** [elementor/elementor#13985]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I wish to add a dynamic tag to my Facebook page so that I can create a template for several pages. 

**Describe the solution you'd like**
Dynamic tag added to the Facebook page link, just like with the YouTube video

**Describe alternatives you've considered**
Previously we created several pages that we're all unique, where you didn't need a dynamic link, but as we have so many of these pages, it would REALLY help if the Facebook page link was dynamic.w

**Additional context**
![Skærmbillede 2021-02-22 092636](https://user-images.githubusercontent.com/79444693/108683251-a8a10f80-74f1-11eb-9a41-decaf8127d5e.png)
![Skærmbillede 2021-02-22 092556](https://user-images.githubusercontent.com/79444693/108683256-ab036980-74f1-11eb-9fff-fb3521d19626.png)

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
