### ISSUE TITLE
Editing inline disabled

### ISSUE THREAD

**Issue by Ringsoe** [elementor/elementor#14018]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description
When I try edit inside texteditor I can't! No problem Header or anything else. What went wrong?! In text area in left side of the screen, there is no problem.

## Steps to reproduce

The error appear both when I edit posts and pages.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
[Systeminfo ‹ Ringsøs blog — WordPress.pdf](https://github.com/elementor/elementor/files/6035185/Systeminfo.Ringsos.blog.WordPress.pdf)

</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.
If you are a Pro user - you are welcome to contact our Support team. 

Thanks.
