### ISSUE TITLE
TEXTAREA control improvements in the editor - line breaks and formatting

### ISSUE THREAD

**Issue by euene** [elementor/elementor#14010]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The TEXTAREA control that's present on a lot of Elementor's widgets (Call to Action, Image Box, Testimonial Carousel and many others) can be significantly improved.

**1.** The main issue with the TEXTAREA control at the moment is that it doesn't support line breaks/paragraphs. Text entered like this:
```
Lorem ipsum.
Lorem ipsum.
```

Or like this:

```
Lorem ipsum.

Lorem ipsum.
```

Is going to get rendered like this on the actual front-end:

`Lorem ipsum. Lorem ipsum.`

However, when actually clicking on the widget inside of the Elementor editor and typing/editing the text there - paragraphs/line breaks will be added as long as editing the text and the widget is focused. But when the widget is unfocused and the page is saved, there will be no line breaks - which is a strange bug.

![line-break-bug](https://user-images.githubusercontent.com/6027160/108886393-961df780-7611-11eb-9b44-af346681db7c.gif)

**2.** The other issue with the TEXTAREA control is that it lacks any WYSIWYG/formatting options - it's just a plain textarea and there are no controls for adding bold/italic and these don't render in the textarea. However, on the editor side - when highlighting the text, "B", "U" and "I" icons will appear for bold/underline/italic formatting.

These same formatting options are missing from the sidebar textarea which is inconsistent - once added from the editor, there's no way to remove the formatting from the textarea unless manually deleting the HTML tags.

![no-wysiwyg](https://user-images.githubusercontent.com/6027160/108886778-0cbaf500-7612-11eb-8073-d63066703292.gif)

## Proposal 1

Change the TEXTAREA control to use a minimal, simplified TinyMCE editor with only the "B", "U" and "I" buttons - to match the editor UI and be consistent, without any of the other TinyMCE buttons - there's a native way to control which buttons appear in TinyMCE (in both the Visual and Text modes).

![improved-textarea-ui](https://user-images.githubusercontent.com/6027160/108887071-6cb19b80-7612-11eb-9d03-33b0b5937016.png)

This will also solve the line break/paragraph issue - as TinyMCE will be run through `wpautop()` by default, I think? Where `<p>` tags will be added automatically.

And maybe don't even just limit the number of buttons to only Bold/Underline/Italic. I think it would be safe to leave ordered/unordered list buttons as well, and potentially a few others, while still keeping the TEXTAREA control simple.

## Proposal 2

If TinyMCE will not be used but the plain textarea should remain, then add the CSS `white-space: pre-line;` to the front-end of all widgets that use the TEXTAREA control to easily render line breaks without `<p>` tags.

However, I prefer **proposal 1** - as that not only takes care of line breaks, but also adds additional rich text formatting options.

**Because this will be a potentially visually breaking change (due to adding line breaks where there were no line breaks before) - this could be added under an experimental flag to be toggled on/off or maybe just as a normal setting and not an experiment.**

**Comment by DorShahar** [comment]
Hi @euene 
Thanks for reaching out and for your comments.
As for the Textarea control - there is an option to achieve your points using HTML tags: 
1. Line break: use `<br>`
2. Use the relevant tag, like for bold - use `<b>`

I attached a screenshot for your convenience: 
![image](https://user-images.githubusercontent.com/19154938/109121501-fdda5c80-774f-11eb-91ae-f18f8e75f0a2.png)

I agree that this is not intuitive - and we will try to improve that. 

Thanks

**Comment by PhanKhai8x** [comment]
This version is working, but when i changed the language to Germany, it did not work
