### ISSUE TITLE
Sharing button widget

### ISSUE THREAD

**Issue by starnetwork** [elementor/elementor#14015]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description
I'm having a common issue with several sites regarding the Share Buttons widget.

https://danielisfarim.com/%d7%9c%d7%93%d7%91%d7%a8-%d7%90%d7%9c-%d7%94%d7%a8%d7%99%d7%91 % d7% 95% d7% a2% d7% 99% d7% 9d /

https://www.inbarshohat.co.il/shop/%d7%a7%d7%9c%d7%a4%d7%99-%d7%a8%d7%92%d7%a2-%d7%9c%d7 % a2% d7% a6% d7% 9e% d7% 99 /

When I build a template for a single product or a single post and I put the share buttons in the template
And states that they will share the current page on WhatsApp, when I switch to template preview mode
The template, the share button in WhatsApp works on this page.
But in the posts or products for which I produce the template, the button does not work and so does
At the animal site.
When I share on Google Chrome I get the error
When I insert a share button for each post individually, it does work in Chrome as well. But there is no product
I have such an option when I need the template template.
Thanks in advance for your help

## Steps to reproduce
I'm having a common issue with several sites regarding the Share Buttons widget.

https://danielisfarim.com/%d7%9c%d7%93%d7%91%d7%a8-%d7%90%d7%9c-%d7%94%d7%a8%d7%99%d7%91 % d7% 95% d7% a2% d7% 99% d7% 9d /

https://www.inbarshohat.co.il/shop/%d7%a7%d7%9c%d7%a4%d7%99-%d7%a8%d7%92%d7%a2-%d7%9c%d7 % a2% d7% a6% d7% 9e% d7% 99 /

Can you with your connections to the Elementor team ask and get an answer for me?
When I build a template for a single product or a single post and I put the share buttons in the template
And states that they will share the current page on WhatsApp, when I switch to template preview mode
The template, the share button in WhatsApp works on this page.
But in the posts or products for which I produce the template, the button does not work and so does
At the animal site.
When I share on Google Chrome I get the picture:
And what's weird is that in a Mozilla browser, it does work:
When I insert a share button for each post individually, it does work in Chrome as well. But there is no product
I have such an option when I need the template template.
Thanks in advance for your help

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Hi
Please contact our support with the system information so they could replicate and investigate the issue.

Thanks

**Comment by starnetwork** [comment]
Hi,
from client account at https://my.elementor.com
where I can see all client support Inquiries?
from what I know the client sent ticket about that without any answer.

this is why I put it here on the git.
