### ISSUE TITLE
In the middle of a build and "Edit with Elementor" on my WP header bar at the top is gone, items are not working on the site, and the builder is stuck on loading. I am unable to change tabs inside settings to enable safe mode. 

### ISSUE THREAD

**Issue by Delabove** [elementor/elementor#14028]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
PHP: 2021-02-24 11:49:16 [error X 1][/nas/content/live/bandgnappavall/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /nas/content/live/bandgnappavall/wp-includes/class-wp-hook.php on line 289 and defined in /nas/content/live/bandgnappavall/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /nas/content/live/bandgnappavall/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(1351, NULL)
#1 /nas/content/live/bandgnappavall/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /nas/content/live/bandgnappavall/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /nas/content/live/bandgnappavall/wp-includes/post.php(4260): do_action('save_post', 1351, NULL, true)
#4 /nas/content/live/bandgnappavall/wp-includes/post.php(4354): wp_insert_post(Array, false)
#5 /nas/content/live/bandgnappavall/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /nas/content/l [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by Delabove** [comment]
PHP: 2021-02-24 11:49:16 [error X 1][/nas/content/live/bandgnappavall/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /nas/content/live/bandgnappavall/wp-includes/class-wp-hook.php on line 289 and defined in /nas/content/live/bandgnappavall/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /nas/content/live/bandgnappavall/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(1351, NULL)
#1 /nas/content/live/bandgnappavall/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /nas/content/live/bandgnappavall/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /nas/content/live/bandgnappavall/wp-includes/post.php(4260): do_action('save_post', 1351, NULL, true)
#4 /nas/content/live/bandgnappavall/wp-includes/post.php(4354): wp_insert_post(Array, false)
#5 /nas/content/live/bandgnappavall/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /nas/content/l [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
