### ISSUE TITLE
Add Video Man option to Videos

### ISSUE THREAD

**Issue by mgravette** [elementor/elementor#14025]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Please add Videoman to the options for the Video widget.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
