### ISSUE TITLE
Autoplay off for self hosted video via modal doesn't work

### ISSUE THREAD

**Issue by marcinkrzeminski** [elementor/elementor#14038]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have a situation when I have a self hosted video with an image overlay + lightbox enabled the Autoplay off is not respected. I looked at the source code and the autoplay attribute is set explicitly in `frontend.js`, and since this is a boolean attribute it seems to be impossible to override. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
https://pastebin.com/dfxaXX10
</details>

**Comment by anakhha** [comment]
Still got the problem (#14038), even with Elementor version 3.1.4.

**Comment by DorShahar** [comment]
This issue has been handled in v3.1.4
If the problem persists - please open a new issue and link to this one.

Thanks
