### ISSUE TITLE
PayPal Button - GBP 

### ISSUE THREAD

**Issue by Grassmedia** [elementor/elementor#14036]
Could I suggest in the currency selector making it GBP or GB pounds rather than "Pounds Sterling", more intuitive looking for GBP.

**Comment by fabianenzensperger** [comment]
The best thing to do is to write it in the beta channel #14034 ... 👀

**Comment by Grassmedia** [comment]
I just clicked on the "reporta problem" in Elementor dev, it led me here. No matter.

**Comment by shilo-ey** [comment]
Thanks. 

We implemented your suggestion.

Feel free to contribute in the beta post.

Thanks
