### ISSUE TITLE
elementor not open preview edit page error 

### ISSUE THREAD

**Issue by milksung** [elementor/elementor#14047]
elementor not open preview edit page error  !!!
<script data-cfasync="false" type='text/javascript' id='jquery-migrate-js-after'>
jQuery.holdReady( true );
</script>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites**.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
