### ISSUE TITLE
changed "data-elementor-type"?

### ISSUE THREAD

**Issue by dertuerke** [elementor/elementor#14049]
Hello, can it be that you have changed the data-elementor-type from "product-post" to "product"?

Before the update of WooCommerce and Elementor, it still said data-elementor-type="product-post".

Due to this small change, all the product pages no longer work properly for me.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
