### ISSUE TITLE
Conflict with theme builder

### ISSUE THREAD

**Issue by FabQuimbaya** [elementor/elementor#14040]
Elementor got stuck if I don't deactivate my theme's page builder (Shuttle theme).

It's impossible to do any action until I deactivate it. 

But I can't keep it deactivated because many posts were built with that builder.

Great if you can fix this! Thank you.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

By the way - You can also contact our support team.

Thanks.
