### ISSUE TITLE
Counter Widget Errors on Edge with 3.1.1

### ISSUE THREAD

**Issue by jkerner-ic** [elementor/elementor#14048]
Using Elementor 3.1.1, Optimized Dom Output is turned off, Improved Asset loading is turned off

The animated counters (totalling up to an integer) never start due to a script error in the frontend.min.js (see screenshots attached). The line numbers reference an 'import' call...

Does anyone know a solution without hacking about the Elementor JS code?

<img width="1187" alt="Screenshot 2021-02-26 at 10 24 55" src="https://user-images.githubusercontent.com/79696005/109288823-49a70780-781d-11eb-8522-de6b12bf67bf.png">
<img width="1613" alt="Screenshot 2021-02-26 at 10 24 28" src="https://user-images.githubusercontent.com/79696005/109288834-4d3a8e80-781d-11eb-8fa3-4ac38bdad6b6.png">

**Comment by shilo-ey** [comment]
Hi @jkerner-ic 

Thanks for your feedback

We can't reproduce the issue.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

Anyway, we need proper steps to reproduce to see if this is an actual bug or local JS conflict you have

Thanks
