### ISSUE TITLE
Elementor slides cannot transition automaticlly from one to another

### ISSUE THREAD

**Issue by potatohai** [elementor/elementor#14044]
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.28
	PHP Version: 7.3.26
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.2
	Site URL: https://www.techsoupasiapacific.org
	Home URL: https://www.techsoupasiapacific.org
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 8
	Debug Mode: Inactive

== Theme ==
	Name: Maisha (shared on wplocker.com)
	Version: 1.0
	Author: Anariel Design
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.9.1
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 7.27
		Author: ServMask

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.4
		Author: Takayuki Miyoshi

	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Easy Table of Contents
		Version: 2.0.16
		Author: Steven A. Zahm

	Elementor
		Version: 3.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.3
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 7.12.2
		Author: MonsterInsights

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 7.43.4
		Author: HubSpot

	MC4WP: Mailchimp for WordPress
		Version: 4.8.1
		Author: ibericode

	Minimal Coming Soon & Maintenance Mode
		Version: 2.18
		Author: WebFactory Ltd

	Ninja Forms
		Version: 3.4.34
		Author: Saturday Drive

	Official Facebook Pixel
		Version: 2.2.0
		Author: Facebook

	Smart Slider 3
		Version: 3.4.1.16
		Author: Nextend

	TablePress
		Version: 1.12
		Author: Tobias Bäthge

	Ultimate Addons for Gutenberg
		Version: 1.17.0
		Author: Brainstorm Force

	Widget Importer & Exporter
		Version: 1.6
		Author: ChurchThemes.com

	Wordfence Security
		Version: 7.4.11
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP File Manager
		Version: 6.9
		Author: mndpsingh287

	WP Table Builder
		Version: 1.3.3
		Author: WP Table Builder

== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists

== Elements Usage ==
	
	section : 2
		posts : 2
	wp-page : 17
		counter : 3
		heading : 6
		icon-box : 3
		image : 1
		image-box : 4
		posts : 3
		shortcode : 1
		slides : 2
		text-editor : 4

== Log ==
	
JS: showing 6 of 6JS: 2020-06-26 04:21:05 [error X 1][https://www.techsoupasiapacific.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view7338\") has already been destroyed and cannot be used. 
JS: 2020-06-26 04:21:05 [error X 1][https://www.techsoupasiapacific.org/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.9.13:2:59543] Cannot read property \'attributes\' of undefined 
JS: 2020-06-26 04:21:06 [error X 1][https://www.techsoupasiapacific.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1300\") has already been destroyed and cannot be used. 
JS: 2021-01-27 23:57:24 [error X 725][https://www.techsoupasiapacific.org/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.3:2:52105] Cannot read property \'data\' of null 
JS: 2021-01-28 04:28:13 [error X 4][https://www.techsoupasiapacific.org/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.3:2:52082] this.$element is null 
JS: 2021-02-03 08:34:50 [error X 1][https://www.techsoupasiapacific.org/wp-content/plugins/ninja-forms/assets/js/min/builder.js?ver=3.4.34:1:12563] n is undefined 

PHP: showing 3 of 3PHP: 2020-06-29 10:23:26 [error X 1][/home/aussiebb/public_html/techsoupasiapacific/wp-content/plugins/elementor/includes/template-library/sources/local.php::1081] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/aussiebb/public_html/techsoupasiapacific/wp-includes/class-wp-hook.php on line 289 and defined in /home/aussiebb/public_html/techsoupasiapacific/wp-content/plugins/elementor/includes/template-library/sources/local.php:1081
Stack trace:
#0 /home/aussiebb/public_html/techsoupasiapacific/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(4058, Object(stdClass))
#1 /home/aussiebb/public_html/techsoupasiapacific/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/aussiebb/public_html/techsoupasiapacific/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/aussiebb/public_html/techsoupasiapacific/wp-includes/post.php(4153): do_action('save_post', 4058, Object(stdClass), true)
#4 /home/aussiebb/public_html/techsoupasiapacific/wp-includes/post.php(4244): wp_insert_post(Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-05 16:03:19 [error X 12][/home/aussiebb/public_html/techsoupasiapacific/wp-content/plugins/elementor-pro/base/base-widget-trait.php::2] Namespace declaration statement has to be the very first statement or after any declare call in the script [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-05 16:24:32 [error X 19][/home/aussiebb/public_html/techsoupasiapacific/wp-content/plugins/elementor-pro/elementor-pro.php::57] require(): Failed opening required '/home/aussiebb/public_html/techsoupasiapacific/wp-content/plugins/elementor-pro/plugin.php' (include_path='.:/opt/alt/php70/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 302020-09-05 16:02:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-05 16:02:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-05 16:02:52 [info] elementor::elementor_updater Started 
2020-09-05 16:02:52 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-05 16:02:52 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-05 16:02:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '3.0.5',
)]
2020-09-05 16:33:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.2',
  'to' => '3.0.3',
)]
2020-09-07 09:10:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]
2020-09-11 10:30:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.6',
  'to' => '3.0.7',
)]
2020-09-15 10:26:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]
2020-09-18 10:23:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.8.1',
  'to' => '3.0.9',
)]
2020-09-23 22:23:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-10-01 10:22:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-21 10:27:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-04 22:29:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-26 10:23:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-12-22 10:43:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.15',
)]
2021-01-07 10:45:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-27 10:44:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
2021-02-01 10:43:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
