### ISSUE TITLE
Background Image disappears in responsive mode in style tab

### ISSUE THREAD

**Issue by awakekat** [elementor/elementor#14055]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest development version of Elementor.

## Description
When switching between responsive modes of tablet and mobile the background image chosen from the media library in the style tab disappears, but shows in Desktop mode.

## Steps to reproduce

I have a video link for screen recording: https://www.loom.com/share/817e85fc1c0549a888c65d15a4a2058e
Insert section with 5 columns, each column has a background image. I activate responsive mode, then switch between tbalet and mobile and the background image in the styles tab disappears.

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X ] I can reproduce this bug consistently using the steps above.

## Environment
Mac Big Sur 11.2.1
LocalWP - 5.9.9+5246
Chorme - Version 88.0.4324.192 (Official Build) (x86_64)
Hello Theme

**Comment by DorShahar** [comment]
Hi
Thanks for reaching out.
This is the default behavior for responsive elements in the Editor. 
We know it might be confusing - and we are thinking about changing it in the future. 

Thanks
