### ISSUE TITLE
Deprecated: Elementor\Scheme_Typography não é usado desde a versão 2.8.0! 

### ISSUE THREAD

**Issue by P-atricia-designer** [elementor/elementor#14056]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
I have this message: "Deprecated: Elementor\Scheme_Typography não é usado desde a versão 2.8.0! Use Elementor\Core\Schemes\Typography em substituição. in /var/www/wp-includes/functions.php on line 5049"
how do i fix it?
thankz

```
</details>

**Comment by shilo-ey** [comment]
There's a plugin or 3rd party custom code that extends Elementor and uses the old Schemes system.

This was deprecated in v2.8.0

Please make sure all of your plugins are updated and it should not be displayed in this case.

Thanks
