### ISSUE TITLE
Issue with the icon list while centralizing

### ISSUE THREAD

**Issue by boesmedia** [elementor/elementor#14076]
There is an issue with the icon list in horizontal mode. If you turn on the divider and centralize the list the dividers are always come to the bottom. If you make it left- or right-justified - no problem. The dividers are like they should be. But if you centralize it they appear at the bottom. 

I tried it with different themes and it is the same issue. You can't centralize the list without having the issue that the dividers don't stay in place. It's a minor issue but it looks unnatural and can't be configured without changing the code of Elementor.

**Comment by DorShahar** [comment]
Hi 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
