### ISSUE TITLE
Add support of dynamic tag to link attributes 

### ISSUE THREAD

**Issue by mredodos** [elementor/elementor#14084]
Hi, in advanced tab->attributes that setting support dynamic tags.
 But in the link field(in all widget) in link option, we have custom attributes but that field not support dynamic tags. 
 
 can you add support of dynamic tags in the custom attributes in link field ?

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* **Prerequisites**.
* **Description and examples.**
* One request per thread

Without it, it is hard for us to understand your need. 
Thanks.

**Comment by mredodos** [comment]
I've written everything there is to say ... what should I add? 

Elementor had attributes on the element and that have support of dynamic tag

Link field in the option have custom attributes and not support dynamic tag. 

I have request dynamic tag on the option of link field.
