### ISSUE TITLE
Elementor

### ISSUE THREAD

**Issue by sabrinaad** [elementor/elementor#14081]
Hello, 
i have a problem with my Elementor , i upload some elementor plugin like EA and their section doesn't appear on the elementor board

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
