### ISSUE TITLE
⛔ Icon Element adds over 100 DOM elements

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#14092]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Adding a single icon element to my header adds over 100 DOM elements. That is far, far too many for a simple icon element. This should be a focus for optimization.

Speed test a page before adding an icon, notate DOM size. Add an icon, watch the DOM size increase.

## Steps to reproduce

1. Speed test an elementor page

2. Note DOM size

3. Add an icon, watch DOM size immediately increase.

Please fix this, this should be an easy performance win.

**Comment by JoeHana** [comment]
Can't verify this issue. Added an icon and it adds 3 dom elements and not 100. Are you sure the issue you're facing doesn't come from somewhere else?

**Comment by jazir5** [comment]
It does for me, it raises me DOM element count from 846 to over 960. Only
change I made is changing from an image element to an Icon element, resized
the icon slightly.

**Comment by jazir5** [comment]
I uploaded a svg file, not default icon library.

**Comment by parasshah195** [comment]
It would be nice if you could post some before/after screenshots to better understand the exact issue. A screencast would be even better.

**Comment by shilo-ey** [comment]
Hi @jazir5 

Thanks for your input but placing an SVG file in the DOM adds more DOM elements.
If you want to include it externally you can use an Image widget to reduce it.

The DOM addition is based on your SVG file.

**Comment by jazir5** [comment]
Adding an svg file shouldn't add 100 dom elements. Is there any way you
could reduce it?

**Comment by shilo-ey** [comment]
https://jakearchibald.github.io/svgomg/

You can use a tool like this to minify or clean unwanted dom elements
