### ISSUE TITLE
Preview_id setting in Elementor Pro is not saved with Elementor 3.1.2

### ISSUE THREAD

**Issue by andreasnrb** [elementor/elementor#14104]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I apply Preview Settings with Elementor Pro 3.1.1 (and earlier versions) and use Elementor 3.1.2 the preview_id setting is not saved to the post meta field. The preview_type value is saved correctly.
Reverting to Elementor 3.1.1 resolves this is and the preview_id is correctly saved to the post meta _elementor_page_settings on update.

## Steps to reproduce
Set Preview in Preview Settings using Elementor Pro, apply settings and update and then refresh the page, preview value is lost in the control.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Elementor 3.1.2
Elementor Pro 3.1.1
```
</details>

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.3

Feel free to update

Thanks!
