### ISSUE TITLE
Post widget with manual selection don´t show.

### ISSUE THREAD

**Issue by KiQdev** [elementor/elementor#14109]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating to the latest versions, free 3.1.2 and pro 3.1.1, the post widget don´t display anything if it´s set to manual selection of pages.
Creating new works in editor, but disappears again after saving.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by fleks** [comment]
Same issue here!

**Comment by joelmcna** [comment]
Same here!

**Comment by JoeHana** [comment]
I can confirm. It doesn't work with any widget (even from 3rd party plugins). It is possible to select posts/pages and they will load and display fine in the editor but it seems like it doesn't get saved. After reloading the editor the field for the manual selection is emptied.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.1.3

Feel free to update

Thanks!

**Comment by KiQdev** [comment]
It works now in the new version.
Unfortunately it didn´t return the manual selections that was there before, so have to insert them again.

**Comment by JoeHana** [comment]
> It works now in the new version.
> Unfortunately it didn´t return the manual selections that was there before, so have to insert them again.

Possibly you have "saved" it while it was "broken" out of testing purpose? Then yes, it's most likely gone. Same was on my site.
