### ISSUE TITLE
3.1.3 update causes error on multisite

### ISSUE THREAD

**Issue by lskala** [elementor/elementor#14116]
3.1.3 update causes "There has been a critical error on this website. Please check your site admin email inbox for instructions. Learn more about debugging in WordPress." on multisite admin panel. 

A rollback to Version 3.1.0 works fine.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
