### ISSUE TITLE
On add to cart click open elementor cart sidebar.

### ISSUE THREAD

**Issue by nikkonone** [elementor/elementor#14119]
## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This feature boosts sales and engagement. Users see what is in they cart without a need to go to the cart page. They can go straight to the checkout or cart.

**Describe the solution you'd like**
When clicking on add to cart button on product page it opens elementor cart sidebar (with a products that are in your cart).
Triggers on every product add.

**Describe alternatives you've considered**
Woocommerce redirect to cart on add is not a solution.

**Additional context**
There are some websites that use this feature already.
https://il.shein.com/

**Comment by ahmedzeidan** [comment]
The cart popup is not opening when adding to cart, tested on staging site with Elementor and WooCommerce only enabled and Ajax add to cart is enabled as well.

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

@ahmedzeidan please create a new issue report and we will examine the issue, thanks!

Thanks!
