### ISSUE TITLE
Intire site went 50 pixels down

### ISSUE THREAD

**Issue by maxroeleveld** [elementor/elementor#14121]
Hi,

So i put my wordpress site in the develper modus, but after that the intire site was not aligned any more.
all the pages are like 50 pixels downwards. (see picture) what is this? all the settings are the same. 
![Knipsel123](https://user-images.githubusercontent.com/80052569/109984570-3061f780-7d04-11eb-91bf-19db88feaaee.JPG)

**Comment by riadcitaku** [comment]
Turn off maintenance, so we can help you.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.
BTW - If you are a Pro user - you are welcome to contact our support team. 


Thanks.
