### ISSUE TITLE
🚧 📚 ❓ Community Question: Overriding elementor-pro mini-cart.php

### ISSUE THREAD

**Issue by whipster-loaded** [elementor/elementor#14136]
What is the correct way to override the elementor mini-cart markup.  

I understand I can disable it altogether and rely on woocommerce default mini-cart.  But I am using Hello Theme, when I disable the elementor mini-cart, I lose the mini-cart widgets functionality (ie, it doesn't open the mini-cart).

I can edit the mini-cart markup directly in the plugin folder, but obviously this is not sufficient.  What would the folder structure be to override the mini-cart template within my child theme structure?

There was a suggestion to place the elementor mini-cart.php template into my child themes woocommerce folder overrides, but alas this does nothing as well.

**Comment by emrahkan** [comment]
copy this file  /plugins/elementor-pro/modules/woocommerce/wc-templates/cart/mini-cart.php in to my child themes woocommerce/cart/ folder.

adding this code to the my child themes functions.php file.

function elementor_woocommerce_locate_template( $template, $template_name, $template_path ) {
    if ($template_name !== 'cart/mini-cart.php') {
		return $template;
    }
	$template_directory = __DIR__ . '/woocommerce/';
	if ( file_exists( $template_directory . $template_name ) ) {
		$template = $template_directory . $template_name;
	}
    return $template;
}
add_filter( 'woocommerce_locate_template', 'elementor_woocommerce_locate_template', 15, 3 );

**Comment by nisiwi** [comment]
I tried your suggestion @emrahkan however it's still not overriding the standard template.  Did you manage to find a solution @whipster-loaded ?

**Comment by nisiwi** [comment]
This does work; however, you don't need to add the function suggested by @emrahkan as Elementor has one built in to switch to your child themes mini-cart.

So, just copy the mini-cart.php file to your child theme directory as described above and then

Then Disable - Elementor -> Settings -> Integrations - "Mini Cart" to use your child themes version.

Lastly, you must make a change to the CART page (removing and adding product) to force a change in the Mini-Cart template as this gets cached and you will only see the changes with a cart update.

**Comment by Bamstian** [comment]
Hi, 

I am trying to add a custom Button to close the Side cart. 

The button works if I am linking it to the current product but I wanted to have the smoother way, like elementors close button does. 

Does s.o. knows how I could achieve this? 
Like is it a special link or event listener?

Thank you :)

**Comment by nicholaszein** [comment]
Hello there, 

#### 🕙 It's been a while, and we see there are a few solutions already. 

## ✔️ For this reason, we are closing this issue as solved.

Kind regards
