### ISSUE TITLE
Randomize Background Image for Sections on Page Load

### ISSUE THREAD

**Issue by CatinkaK** [elementor/elementor#14130]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
(I did find a similar request from 2018, but the request had missing key information, so it was never handled. https://github.com/elementor/elementor/issues/5462)
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am designing a website with a shop. The style of the site is quite informal and 'happy' with lots of graphic design on the different pages. My problem is that product pages can't be designed individually. I am using elementor's theme builder to customize the product page, but this ofcourse will aplly to every single product, so all products will have the same background on their page. The problem is that it gets a little boring. Every page on the site has a fresh feel to it with different graphic design, but every product page is the same. This is a shame because product pages will most likely get the most views. I would love them to have a fresh look as well with room for variations in graphic design. 

**Describe the solution you'd like**
In Elementor, when choosing a background, you can choose classic, gradient, video and slideshow. I would love to have an option to add a gallery like in the slideshow, but not have it behave like a slideshow. Instead I would like it to randomly choose one of the images in this galery on every page load and use it as a still background image. 

**Describe alternatives you've considered**
There is of course the option to insert a slideshow, but that would just be too busy. I don't want things to move, I just want it to open to fresh and new backgrounds on every page load, or at least switch between 5 to 10 different background images on every page load. That would be really great. 

**Additional context**
I would greatly appreciate it! 

(I edited my description of the problem to clarify it a bit)

**Comment by petranca** [comment]
Yes, please add this feature

**Comment by 1naveengiri** [comment]
Any updates on this guys?

**Comment by iveyopt** [comment]
Also looking for this feature!

**Comment by webdevs-pro** [comment]
Check my comment here https://github.com/elementor/elementor/issues/5462#issuecomment-1101657177

**Comment by arielk** [comment]
@CatinkaK Long time, you can use dynamic filed for every product page to achieve this goal. 

Unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback

**Comment by nadworks** [comment]
Such a simple yet valuable feature: If you have a background image slideshow, displaying the images in random order on each page load would keep the website fresh and repeat users engaged without much manual work. The fact you don't consider this a worthwhile option is disappointing.
