### ISSUE TITLE
Roadmap for conditional logic forms

### ISSUE THREAD

**Issue by neosaveme** [elementor/elementor#14134]
Can you show us what you have planned or the roadmap for conditional logic forms?

it's time to save us from plugins that provide this function for money.

I am waiting for you in the beta version.
see you soon

**Comment by fabianenzensperger** [comment]
Mhm, yes. But it is more of a Pro function and is unfortunately not included in the current Beta 1 for Pro 3.2. However, there are finally form submissions #14034. That means something is happening.

**Comment by shilo-ey** [comment]
Thanks.

I can share that this is in our roadmap and we will share more info in the upcoming months.

I merged this issue with #2638, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks
