### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by 1gkwc6** [elementor/elementor#14138]
I can't see an option to change the size of the icon of the buttons

**Comment by fabianenzensperger** [comment]
I once made a request #14140 for this feature for all widgets that incons and buttons offer. Please write that you are also for it with +1 or whatever you want.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  ##14140, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
