### ISSUE TITLE
Add support of dynamic tag to link options custom attributes

### ISSUE THREAD

**Issue by mredodos** [elementor/elementor#14152]
we have in advanced tab the attributes setting
![image](https://user-images.githubusercontent.com/42175654/110250977-98bc0d80-7f7e-11eb-8d54-dbf760b11cb9.png)

and that setting support dynamic tags. we can make dynamic attributes 

in a lot of widget we have the link setting field and have as an option "custom Attributes" but we cant make dynamic attributes because that setting not have dyanamic tags

![image](https://user-images.githubusercontent.com/42175654/110251029-d456d780-7f7e-11eb-9874-4e5ac21b3e83.png)

![image](https://user-images.githubusercontent.com/42175654/110251096-2697f880-7f7f-11eb-879e-d116a20ee87b.png)
Can you add dynamic tags on that settings like attributes in advanced tab ? 
![image](https://user-images.githubusercontent.com/42175654/110251127-55ae6a00-7f7f-11eb-9ca4-c8cb74fe239e.png)

in this way we can create dynamic attributes associated with the link of the specific widget.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
