### ISSUE TITLE
Module Forms with webhook and data in url

### ISSUE THREAD

**Issue by cedricDevWP** [elementor/elementor#14167]
Hi, 

I would like to know if it is possible to add data in the url of the webhook, for example =

![Capture d’écran 2021-03-08 à 18 41 41](https://user-images.githubusercontent.com/12508260/110359828-480be980-803e-11eb-90f7-41e86913355f.png)

for example I have fields with the name "lang", "datecheckin" ... and I would like to add them in the webhook because it only accepts data transmitted like this...

thank you in advance,
Cédric

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
