### ISSUE TITLE
How to fix deprecated issues

### ISSUE THREAD

**Issue by yeahbrunz** [elementor/elementor#14176]
Deprecated: elementor/element/post/ekit_page_settings/before_section_end is deprecated since version 2.7.0! Use `elementor/element/wp-post/ekit_page_settings/before_section_end` or `elementor/element/wp-page/ekit_page_settings/before_section_end` instead. in /home3/bruno/sumis.events/wp-includes/functions.php on line 5234

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
