### ISSUE TITLE
Invisible content on page visible for (Google) bots

### ISSUE THREAD

**Issue by sonnesworld** [elementor/elementor#14177]
## Description

How can I make the content not only visible for user but also not visible for search engines? I created a website for a client with job descriptions and set them on not visible for all devices. So he can easily activate/deactivate job ads. But now bots can read this job descriptions which are not visible for website visitors but for bots and several ads are visible on different external job platforms. With Elementor the content is still visible in page source code, even I hide it in backend. Many thanks.

Some screenshots:
https://drive.google.com/file/d/1zbwHMuqvoSgzpuqlnxeRWdLsJT_brfgk/view?usp=sharing
https://drive.google.com/file/d/1FyPToYdP3JYDllcAfCrL9CcQRqfdfHSM/view?usp=sharing

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by sonnesworld** [comment]
This is a feature request! I know it's not possible at this time.

**Comment by DorShahar** [comment]
Hi @sonnesworld 
Please open a feature request issue according to the guideline - so we could interoperate better in our systems.

Thanks

**Comment by sonnesworld** [comment]
Thanks, I will do this. But where can I post my feature request, I can't find this option on your page (elementor.com, I have a Elementor Pro licence) or here? Many thanks.
