### ISSUE TITLE
Incorrect display of colour in the editor after updating to Elementor Dev 1.1.1

### ISSUE THREAD

**Issue by anelkata** [elementor/elementor#14173]
My site just updated automatically to Elementor Dev 1.1.1 and the first page that loaded in the editor started showing incorrectly. The screenshots below are of the same blocks copied from a tab running the 1.1.0 to a tab running 1.1.1. All elements display correctly on the live site.

I tried rolling back and dectivating Dev but neither worked.

This Icon list shows the on hover colour (or maybe the title colour) instead of the manually set gray one.
![Screenshot_1](https://user-images.githubusercontent.com/42134627/110425893-c81d6800-80ad-11eb-82b5-d60b841f2f26.png)
![Screenshot_2](https://user-images.githubusercontent.com/42134627/110425897-c8b5fe80-80ad-11eb-89bf-2e5fabb90195.png)

This countdown shows a background colour despite the transparent background setting.
![Screenshot_3](https://user-images.githubusercontent.com/42134627/110426158-44b04680-80ae-11eb-8943-0a5cbe0b6e8f.png)
![Screenshot_4](https://user-images.githubusercontent.com/42134627/110426160-4548dd00-80ae-11eb-88fa-57904719e81b.png)

These progress bars display red text instead of gray.
![Screenshot_5](https://user-images.githubusercontent.com/42134627/110426217-61e51500-80ae-11eb-838c-53a255771ab7.png)
![Screenshot_6](https://user-images.githubusercontent.com/42134627/110426220-627dab80-80ae-11eb-9e7b-eff01883f469.png)

I cannot identify where the red is coming from as it is set as a basic colour in several places both manually and as a global color. The site runs the Hello theme with no color settings.

**Comment by DorShahar** [comment]
Hi
Thanks for reaching out.
If the case is due to "Elementor Beta (Developer Edition)" you can always deactivate the plugin.  
Before that - Please deactivate other plugins to check if the problem continues.

Please let us know if it worked.
Thanks

**Comment by PhillB1965** [comment]
I have same problem.

This is how the page looks on our site:
![image](https://user-images.githubusercontent.com/80406641/110644581-28470380-81ad-11eb-8521-842b46fca77b.png)

This is how the Elementor editor displays it:
![image](https://user-images.githubusercontent.com/80406641/110645103-9ab7e380-81ad-11eb-9cf9-ffbf6895d032.png)

Updated yesterday to:
Elementor v3.2.0-dev7
Elementor Pro v3.2.0-dev6

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://guisachanguesthouse.co.uk
	Home URL: https://guisachanguesthouse.co.uk
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.1.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.74

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.9
		Author: Automattic

	Asset CleanUp Pro: Page Speed Booster
		Version: 1.1.8.9
		Author: Gabe Livan

	Astra Pro
		Version: 3.1.0
		Author: Brainstorm Force

	BackupBuddy
		Version: 8.7.2.0
		Author: iThemes

	Business Reviews Bundle
		Version: 1.6.1
		Author: RichPlugins <support@richplugins.com>

	Cloudflare
		Version: 4.2.2
		Author: Cloudflare, Inc.

	Custom Facebook Feed Pro Business
		Version: 3.19.2
		Author: Smash Balloon

	Elementor
		Version: 3.2.0-dev7
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.0-dev6
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 4.5.2
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.3.3
		Author: WPDeveloper

	Imagify
		Version: 1.9.14
		Author: WP Media

	Instagram Feed Pro Personal
		Version: 5.11.2
		Author: Smash Balloon

	iThemes Security Pro
		Version: 6.8.3
		Author: iThemes

	iThemes Sync
		Version: 2.1.8
		Author: iThemes

	Lazy Load - Optimize Images
		Version: 2.3.4
		Author: WP Rocket

	Query Monitor
		Version: 3.6.7
		Author: John Blackbourn

	Shortcodes Ultimate
		Version: 5.9.8
		Author: Vladimir Anokhin

	Starter Templates
		Version: 2.6.1
		Author: Brainstorm Force

	Virtual Robots.txt
		Version: 1.10
		Author: Marios Alexandrou

	WP AutoTerms
		Version: 2.4.4
		Author: WP AutoTerms

	WPForms
		Version: 1.6.5.1
		Author: WPForms

	WPForms Custom Captcha
		Version: 1.3.0
		Author: WPForms

	WPForms Form Templates Pack
		Version: 1.2.1
		Author: WPForms

	WPForms Geolocation
		Version: 2.0.0
		Author: WPForms

	WPForms Signatures
		Version: 1.3.1
		Author: WPForms

	WPForms Surveys and Polls
		Version: 1.6.3
		Author: WPForms

	WPForms User Registration
		Version: 1.3.3
		Author: WPForms

	WP Mail SMTP Pro
		Version: 2.6.0
		Author: WPForms

	WP Rocket
		Version: 3.8.6
		Author: WP Media

	Yoast SEO: Local
		Version: 13.8
		Author: Team Yoast and Arjan Snaterse

	Yoast SEO Premium
		Version: 15.9.1
		Author: Team Yoast


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan

	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Page Cache
		Version: 2.0.5
		Author: Mike Hansen

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen


== Elementor - Compatibility Tag ==
	
	Elementor Pro: incompatible
	Essential Addons for Elementor: incompatible
	Essential Addons for Elementor - Pro: incompatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: incompatible
	Essential Addons for Elementor - Pro: incompatible

== Elements Usage ==
	
	page : 5
	wp-post : 12
		divider : 1
		image : 6
		image-carousel : 5
		image-gallery : 2
		navigation-menu : 1
		spacer : 1
		text-editor : 13
	wp-page : 28
		button : 60
		divider : 1
		eael-post-carousel : 3
		eael-post-grid : 2
		gallery : 2
		google_maps : 2
		heading : 62
		html : 22
		icon-list : 3
		image : 167
		image-gallery : 3
		login : 1
		menu-anchor : 5
		posts : 1
		price-table : 2
		shortcode : 2
		spacer : 39
		text-editor : 89
		toggle : 1
		wp-widget-instagram-feed-widget : 1
		wp-widget-wpforms-widget : 2
	single-post : 1
		author-box : 1
		divider : 1
		heading : 2
		post-comments : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1


== Log ==
	
Log: showing 20 of 362021-02-15 09:09:21 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-15 09:09:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-15 09:09:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-18 10:30:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.2.0-dev2',
)]
2021-02-18 21:38:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev2',
  'to' => '3.2.0-dev3',
)]
2021-02-22 21:48:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev3',
  'to' => '3.2.0-dev4',
)]
2021-02-26 11:55:23 [info] elementor-pro::elementor_pro_updater Started 
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-26 11:55:23 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-26 11:55:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.2.0-dev5',
)]
2021-03-02 21:55:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev4',
  'to' => '3.2.0-dev5',
)]
2021-03-03 21:39:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev5',
  'to' => '3.2.0-dev6',
)]
2021-03-08 21:40:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.0-dev6',
  'to' => '3.2.0-dev7',
)]
2021-03-09 09:26:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0-dev5',
  'to' => '3.2.0-dev6',
)]

PHP: showing 3 of 3PHP: 2021-01-16 10:44:16 [notice X 2][/home3/guisacha/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-21 12:06:20 [notice X 561][/home3/guisacha/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::36] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-24 22:21:47 [notice X 1][/home3/guisacha/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2021-02-03 14:31:53 [error X 2][https://guisachanguesthouse.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view258\") has already been destroyed and cannot be used. 
JS: 2021-02-03 16:39:55 [error X 1][https://guisachanguesthouse.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view68\") has already been destroyed and cannot be used. 
JS: 2021-02-07 13:15:20 [error X 1][https://guisachanguesthouse.co.uk/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.1.1:2:80913] Routes: `theme-builder-publish/triggers` is already registered.

**Comment by anelkata** [comment]
No deactivations or roll-backs worked but today the problem is gone. I suppose that is the update of Elementor (from version 3.2.0-dev7 to 3.2.0-dev8). I the developers have found the problem.

It still seems interesting that the bug was picking several different colours from the global palette. I counted at least 3.

Anyways, thanks!

**Comment by DorShahar** [comment]
Hi
Thanks for your feedback.
Since the problem fixed on @anelkata  I'm closing the issue. 

@PhillB1965  - in case that the problem still continues, please open a new issue. 

Thanks.
