### ISSUE TITLE
Word duplicated when enter non-English inside HTML block

### ISSUE THREAD

**Issue by ImKaiUn** [elementor/elementor#14183]
Editing non-English words (especially Chinese) inside the HTML block, each word enter will be duplicated. If copy the text then paste them on the HTML block it will be fine.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites**.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
