### ISSUE TITLE
Toggle Switch Button

### ISSUE THREAD

**Issue by Proktologe** [elementor/elementor#14190]
I want to Use ACF Fields with a nice looking Toggle/Switch Button instead of having ugly Dropdown or Checkboxes for TRUE/FALSE fields

Like this good one:
![image](https://user-images.githubusercontent.com/25704471/110635085-00ef3700-81ab-11eb-99bd-556c7cf47f33.png)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

In addition:
* What is the use case? 
* How this could help you in your work besides the different UI? 

Please help us to understand better your request.

I'm closing the issue - feel free to open a new one with the information above so we could relate. 

Thanks.
