### ISSUE TITLE
How to render the ACF Image data properly 

### ISSUE THREAD

**Issue by roelof-otten** [elementor/elementor#14198]
I'm searching for a way to update the columns.php render function. Is there some kind of add_action hook to change the complete output of that render function? Also i'm trying to access the 

I'm looking for a way to render the ACF Image data output. When i'm looking at it with var_dump i'm seeing something like this:

[elementor-tag id="c0156d8" name="image" settings="%7B%22acf-field image%22%3A%22field_6048dd729b924%22%7D"]

Is there a way to get the url from that ACF Field?

**Comment by udidol** [comment]
Hi @roelof-otten,
Regarding the `render()` content, see: https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/includes/base/widget-base.php#L571
