### ISSUE TITLE
Permalink to attachment page WITHOUT a Parent Info causes Error 404

### ISSUE THREAD

**Issue by ole1986** [elementor/elementor#14192]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When enabling the Elementor plugin I am unable to access attachment pages not containing a Parent Info through its permalink.

## Steps to reproduce

* Upload a media image into the media library
* Make sure it is not linked to a parent (E.g. Post or page)
* Make sure Elementor plugin is enabled.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

When disabling the Elementor plugin the permalink does work as expected

## Possible Workaround

Edit the file `wp-content/plugins/elementor/modules/landing-pages/module.php` on line 333 
and add the `attachment` type into the `$query_post_types` array

```
// Create the post types property as an array and include the landing pages CPT in it.
$query_post_types = [ 'post', 'page', self::CPT, 'attachment' ];
```

## Environment

Tested on Wordpress 5.6.X and 5.7

**Comment by ole1986** [comment]
Our even more comfortable using a quick plugin script

```
<?php
/*
Plugin Name: Elementor Fix Attachment Page
Description: Fixed Elementor issue not displaying attachment pages (Error 404)
Version:     1.0.0
Author:      ole1986
Author URI:  https://profiles.wordpress.org/ole1986
License:     GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
*/

add_action( 'pre_get_posts', function ( $query ) {
    $post_types = $query->get('post_type');
    array_push($post_types, 'attachment');
    $query->set('post_type', $post_types);
}, 11);
```

**PLEASE NOTE**
For some unknown reason I have one website (out of three) where this issue does not occur. I assume this has some thing to do with other plugins being installed on that machine

**Comment by gabrielle** [comment]
I have this same issue with the new version of Elementor (3.3.0)

**Comment by ole1986** [comment]
This issue just disappeared.
Even in version 3.3.0 its now working for me. So maybe its was caused by wordpress?

**Comment by hoolius** [comment]
FYI - https://github.com/elementor/elementor/issues/15943
