### ISSUE TITLE
[Feature Request] Add atributte "Lazy" to slider img

### ISSUE THREAD

**Issue by eduardovillao** [elementor/elementor#14193]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Include the "lazy" attribute in the slide widget images for save load time.

**Describe the solution you'd like**
Include the "lazy" attribute in the slide widget images for save load time.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.6.0 and Pro v3.7.0

Feel free to update

Thanks!
