### ISSUE TITLE
Show widget ICON in the settings headline

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#14214]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
An easier way to see what widget you are using when you have multiple widgets with the same name (when using addons/extensions).

**Describe the solution you'd like**
Show the ICON to the specific widget next to the headline in a widget setting page (at the top). See image here:
https://postimg.cc/gallery/1ymH9Qz

**Describe alternatives you've considered**
None.

**Additional context**
https://postimg.cc/gallery/1ymH9Qz
![image](https://user-images.githubusercontent.com/35301469/110935538-d67ab680-832f-11eb-96b3-37aed3b32b3f.png)

![image](https://user-images.githubusercontent.com/35301469/110935557-ded2f180-832f-11eb-9cc9-6c247cf47c4d.png)

**Comment by shilo-ey** [comment]
Thanks!

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it.

If you, however, decide to write a patch for it, we'll gladly include it after some code review.
