### ISSUE TITLE
As for Opstore , how to reduce the 

### ISSUE THREAD

**Issue by joetst** [elementor/elementor#14215]
I have installed opstore plugin (https://wordpress.org/themes/opstore/) and elementor pro. May I know how I can reduce the space between the products as shown below:

![Screen Shot 2021-03-12 at 9 54 29 PM](https://user-images.githubusercontent.com/80404993/110949430-8a566300-837d-11eb-91f5-adc590996e91.png)

**Comment by shilo-ey** [comment]
If this element is a theme element - than you need to be able to control it via your theme settings.
If not - it's via the Products/Products archive widget

Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
