### ISSUE TITLE
widget product grid is not supporting queryid

### ISSUE THREAD

**Issue by bipeen** [elementor/elementor#14211]
I created an widget via unlimited elements pro version to display custom product grid and tried to add queryid to filter and show recently viewed products but the grid is not supporting queryid

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
I created an widget via unlimited elements pro version to display custom product grid and tried to add queryid to filter and show recently viewed products but the grid is not supporting queryid

## Steps to reproduce
go to unlimited elements 
create cutom product grid
apply the save grid to single product page

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x
![grid](https://user-images.githubusercontent.com/265115/110899582-77b23e80-8329-11eb-9535-6cf17c6bacf4.PNG)
] I can reproduce this bug consistently using the steps above.

## Environment
	 

				
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Webtica** [comment]
Hi Bipeen,

The query ID is the name you can give to use in your function to alter the query.
You can find more info on it here: https://developers.elementor.com/custom-query-filter/
You can add your query function in your functions file of your child theme. 
If you already did that can you post your code?

**Comment by DorShahar** [comment]
Hi
Unlimted Elements for Elementor is an Addon for Elementor - so you should address them with any problem or question.
If there is a problem with our API - please open a ticket with the problem and system info.

Thanks
