### ISSUE TITLE
Button animation effect problem!

### ISSUE THREAD

**Issue by princ-imran** [elementor/elementor#14220]
<details>
<summary>Bug Report</summary>
I am your elementor expert planer customer. I faced some problems with your plugin. When I adding animation efect in elementor button then some problem on content area, Like: image box content, Icon Box content. When hove your button its show different color on text field.
Please check it.

Thanks
</details>

**Comment by DorShahar** [comment]
Hi,
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
