### ISSUE TITLE
Counter widget custom thousands separator

### ISSUE THREAD

**Issue by rb-ar** [elementor/elementor#14237]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. (#3459)
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There are only three types of separators available, which don't cover every style in the world.
This has been requested before (#3459), but was implemented by simply adding the aforementioned three choices.

**Describe the solution you'd like**
I like to have a selection "custom" which allows to enter any string/character, which will then be used.

**Describe alternatives you've considered**
~~I personally need `'` as a separator, simply adding that would suffice.~~ Implemented in #18026

**Comment by black-eye** [comment]
+1

**Comment by MarloKessler** [comment]
+1
