### ISSUE TITLE
🐞 Elementor Responsive Sidebar Reset Issue/BUG

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#14240]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hi, when using the responsive feature of changing device view the sidebar changes back to the widget selection view which is highly inconvenient. Not sure if this is a feature or not but could you leave it on the item you are editing when changing views?

## Steps to reproduce
See GIFs below (keep your eye on the side panel): --

Using the bottom panel responsive selection : 
![EE GIF 16-03-2021 09-09-00](https://user-images.githubusercontent.com/55829113/111285313-edbfe980-8638-11eb-9d64-e4e1fb5d75d4.gif)

Using in-widget responsive selection : 
![EE 2 GIF 16-03-2021 09-13-33](https://user-images.githubusercontent.com/55829113/111285424-092af480-8639-11eb-9b3a-af54ffabbf8b.gif)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @perks98 

Thanks for sharing this.

I couldn't reproduce the issue you are describing.

Can you please share your system info?
Have you tried to make sure it's not a conflict with another plugin/theme?

thanks

**Comment by perks98** [comment]
Hi @shilo-ey 
I've had a better look at it and it seems to mainly happen with the Astra theme enabled on a fresh new install website. This issue didn't happen a few months ago. Are you able to look into it?

Test environment I can replicate the issue with specs: - 
<details>
<summary>System Info</summary>
```				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.31
	PHP Version: 7.3.26
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://elementor2021.elementorwp.uk
	Home URL: https://elementor2021.elementorwp.uk
	WP Multisite: Yes
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.1.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.1.4
		Author: Elementor.com


== Must-Use Plugins ==
	StackCache
		Version: 
		Author: Stack CP


== Elementor - Compatibility Tag ==
	


== Elements Usage ==
	
	wp-page : 1
		button : 1
		heading : 3


== Log ==
	

				
```
</details>

**Comment by shilo-ey** [comment]
Hi @perks98 

I still have trouble reproducing this issue.

It seems like a local issue with your site.

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


Thanks.

**Comment by perks98** [comment]
@shilo-ey please review this video of point a to b on how to replicate this issue : [https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Elementor-Side-Panel-Responsive-Bug-With-Astra-Theme-2021-03-16.mp4](https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Elementor-Side-Panel-Responsive-Bug-With-Astra-Theme-2021-03-16.mp4)

**Comment by perks98** [comment]
@shilo-ey ?

**Comment by shilo-ey** [comment]
Thank you, 

Does this issue occur without configuring the layout in Astra?
Does it happen in a site that is outside of a multisite?

It seems like a JS conflict originates from Astra but let's make sure.

I suggest contacting them as well.

**Comment by perks98** [comment]
Hi @shilo-ey,
Thanks for the reply. I've done 3 videos below. I just do the layout configuration out of habit just so the page is full-width you can see in the single install vs multisite that the layout doesn't matter. These are sites made in the last month or so with plugins up-to-date.

Single Install vs Multisite: [https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Single-Install-vs-Multisite-same-2021-03-18.mp4](https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Single-Install-vs-Multisite-same-2021-03-18.mp4)

The issue with Astra theme: [https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Astra-Theme-Problem-2021-03-17.mp4](https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Astra-Theme-Problem-2021-03-17.mp4)

No issue with Twenty Twenty-One theme: [https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Twenty-Twenty-One-Theme-No-Problem-2021-03-17-16-58-39.mp4](https://elementor2021.elementorwp.uk/wp-content/uploads/sites/11/2021/03/Twenty-Twenty-One-Theme-No-Problem-2021-03-17-16-58-39.mp4)

I've put a support ticket to the Astra team but no offence to them but it takes a LOT of back and forth and in the end they don't fix issues presented unless reported by many users. Like this issue [[#10733](https://github.com/elementor/elementor/issues/10733)] they submitted they haven't push for you guys to fix as it conflicts with their theme.

Any feedback is appreciated.

**Comment by perks98** [comment]
Update: the Astra team have fixed this in the latest update.
