### ISSUE TITLE
Rotating animated headline

### ISSUE THREAD

**Issue by Morgane62117** [elementor/elementor#14241]
Hi !

I have a display problem with the animated headline with rotating mode. I selected the swirl animation but then when you refresh the page the words inside the animated text overlay themselves. Like this...
<img width="960" alt="2021-03-16" src="https://user-images.githubusercontent.com/43224643/111292922-fe785b80-8648-11eb-8f3a-9d4f3abc230e.png">

**Comment by shilo-ey** [comment]
This issue is resolved in Elementor Pro v3.2.0 which will release today.

Thanks
