### ISSUE TITLE
ELEMENTOR PRO gallery issue

### ISSUE THREAD

**Issue by sera2017** [elementor/elementor#14247]
I made a multiple gallery and its shows only one image 
till I click on one of the tabs
then its shows the all images
how can I fix it?

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

We also suggest adding a short video so we can observe the situation better.

Without it, we simply can't help.

BTW - you are welcome to contact our support or ask for assistance in the Facebook community. 

Thanks.

**Comment by sera2017** [comment]
I realy didnt understand which info is missing
I can add a video it will help?
