### ISSUE TITLE
Update Go Pro link with Affiliate Id number

### ISSUE THREAD

**Issue by vrabota** [elementor/elementor#14255]
I create premium WordPress themes and a lot of users go and buy premium Elementor license from Admin Dashboard after they installed my theme. I will be happy to have a filter and change "Buy Elementor Pro" with my affiliate id. The same approach I discovered for Beaver Builder.

```
function my_bb_upgrade_link() { return 'YOUR_LINK_HERE'; }

add_filter( 'fl_builder_upgrade_url', 'my_bb_upgrade_link' );
```

In that case, we will have a win-win, we will generate for you new customers and Elementor will pay us a bonus for that.

Thank you!

**Comment by DorShahar** [comment]
Hi @vrabota 
Thanks for reaching out.
At the moment - your request is against our [policy](https://elementor.com/terms/affiliate/) - see under the "Bad Practices" section, the "xi" point.

However - you are welcome to contact us in this mail: affiliate@elementor.com, explain your needs, and we could work on that win-win situation. 

Thanks
