### ISSUE TITLE
Elementor Pro v3.2.0 - Increase file size of elements-handlers.js

### ISSUE THREAD

**Issue by astbarc** [elementor/elementor#14260]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
Version 3.2.0 of elementor pro increase the size of the file assets/js/elements-handlers.js in 66Kb and includes a lot of new code.
¿What is the reason for this increase? I think this affects speed and performance.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @astbarc 
Thanks for sharing this input.

From our comparison you can see the file sizes:
v3.1.1 - 
![image](https://user-images.githubusercontent.com/45009641/111902311-a628cb80-8a45-11eb-83d8-a99af7578602.png)


v3.2.0 - 
![image](https://user-images.githubusercontent.com/45009641/111902317-b2ad2400-8a45-11eb-97a0-258ed21e17ee.png)

Can you share a live environment with more details? 

Thanks

**Comment by astbarc** [comment]
Hi @shilo-ey

Thanks for the reply.

If I rollback to version 3.11 the file element-handlers-min.js size is 34kb instead of 50kb

![image](https://user-images.githubusercontent.com/2587221/111961439-59023380-8af1-11eb-80da-d4a8db878a6b.png)

Also If I compare the two files I can see a lot of new code. You can see comparision here: https://www.diffchecker.com/U5d2K5Es

**Comment by shilo-ey** [comment]
This issue has been resolved in the latest versions of Elementor, thanks for reporting!
