### ISSUE TITLE
Form submissions - action and filter hooks

### ISSUE THREAD

**Issue by euene** [elementor/elementor#14261]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Please add PHP action/filter hooks to form submissions that landed in Elementor Pro v3.2 to assist plug-in developers and customising forms.

- An action before form submission data is added to database (for certain validation/changes to data)
- An action after form submission data is added to database (to perform extra actions after submission)
- A filter for the rendered submission data table in wp-admin to modify the field data that will be displayed/rendered in the table without modifying the actual data in the database
- Other useful actions/filters for different use cases?

Thanks.

@shilo-ey

**Comment by shilo-ey** [comment]
Hey all,

This feature has been added to Elemetnor Pro v3.3.0

Feel free to update

The new filter `elementor_pro/forms/record/actions_before` allow you as a developer to manipulate the user inputs before all “actions after submit” runs, the first parameter is a `Form_Record` object which holds all the user inputs + some metadata about the user, the second parameter is an `Ajax_Handler` object which response for running all the “actions after submit” and actually handling the submission itself.

Cheers!

**Comment by alisalti1992** [comment]
> > Hey all,
> > This feature has been added to Elemetnor Pro v3.3.0
> > Feel free to update
> > The new filter `elementor_pro/forms/record/actions_before` allow you as a developer to manipulate the user inputs before all “actions after submit” runs, the first parameter is a `Form_Record` object which holds all the user inputs + some metadata about the user, the second parameter is an `Ajax_Handler` object which response for running all the “actions after submit” and actually handling the submission itself.
> > Cheers!
> 
> It is still impossible to get submission_id in elementor_pro/forms/new_record hook. Can it be added into this hook as parameter or something else?

+1
