### ISSUE TITLE
Webp  not displaying in elementor slider

### ISSUE THREAD

**Issue by cloudcreatr** [elementor/elementor#14278]
I am using imagify plugin, and it's working fine but for elementor slider it's not displaying webp. 

They told elementor slider doesn't support it

**Comment by DorShahar** [comment]
Hi @cloudcreatr 
Thanks for reaching out.
It's unclear what is the problem? 
* Are there any errors in the console?
* Is there a specific functionality that doesn't work on Elenentor's side? 

Please open a new issue with more details so we could address it better. 

Thanks
