### ISSUE TITLE
New Instagram post widget

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#14277]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will be cool to have a widget to display instagram posts in elementor Pro. We will not need any other plugin and our website will be lighter.

**Describe the solution you'd like**
A new widget to display instagram images (slider, normal and video). Also would be cool if it possible to filter from specific users and hastags.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11315 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
