### ISSUE TITLE
Add filter to YouTube embeds

### ISSUE THREAD

**Issue by MatzeKitt** [elementor/elementor#14276]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
With [Embed Privacy](https://wordpress.org/plugins/embed-privacy/) we filter embedded videos to display an overlay and thus introduce a 2-click functionality, which is required to comply with the European GDPR.

Currently, only embed code that is not a self-hosted video nor a YouTube video is passed through `Embed::get_embed_html()` and thus through the filter `oembed_result`. While self-hosted videos are no problem as they are allowed to be loaded without 2 clicks, wen cannot change the behaviour of YouTube videos.

**Describe the solution you'd like**
Pass the YouTube embed code through `oembed_result`.

Or a better solution: provide a filter of Video::render() before echoing the embed HTML code for all videos and pass the HTML and the video type.

**Comment by udidol** [comment]
Hi @MatzeKitt,
What exactly does your plugin do in the `oembed_result` filter?

YouTube video iframes are generated dynamically via the YouTube Embed API script. If you attach some functionality to the `<iframe>` element itself - that would have to happen only once the iframe is asynchronously created.

We will look into a solution, maybe something in the lines of adding a JS event that will trigger once the iframe is ready.

**Comment by MatzeKitt** [comment]
We wrap the embed code in additional HTML divs and transform it to JSON code. Then, on click on our divs, we transform the JSON back to HTML.

I don’t know why you generate the YouTube videos differently since WordPress does that the same way as Vimeo for instance.

**Comment by MatzeKitt** [comment]
Since I needed to change the method we workaround the behavior Elementor is generating embeds, we don’t need this anymore.
