### ISSUE TITLE
Uncaught Error: Call to a member function get_default_args()

### ISSUE THREAD

**Issue by jetflyer27** [elementor/elementor#14299]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Fresh install of wordpress, installed the Elementor plugin from the WP Plugin Library. Created new page, edited with elementor and got critical error page. White page when viewing public facing site.

## Steps to reproduce

- Reinstalled plugin, changed theme, fresh install of wordpress, deactivated all other themes

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.32
	PHP Version: 7.4.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://jetchartersearch.com
	Home URL: https://jetchartersearch.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

== Active Plugins ==
	Aheto
		Version: 1.0.9.4.4
		Author: UPQODE

	Booked
		Version: 2.3
		Author: Boxy Studio

	Contact Form 7
		Version: 5.4
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.1.4
		Author: Elementor.com

== Must-Use Plugins ==
	Rocket Wordpress
		Version: 1.1.2
		Author: 

== Elementor - Compatibility Tag ==
	

== Elements Usage ==
	

== Log ==
	
PHP: showing 2 of 2PHP: 2021-03-19 22:14:51 [error X 9][/home/rqjihx0/public_html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /home/rqjihx0/public_html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/files/css/post.php(172): Elementor\Elements_Manager->create_element_instance(Array)
#1 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/files/css/base.php(617): Elementor\Core\Files\CSS\Post->render_css()
#2 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/files/base.php(166): Elementor\Core\Files\CSS\Base->parse_content()
#3 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/files/css/base.php(131): Elementor\Core\Files\Base->update_file()
#4 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/files/css/base.php(207): Elementor\Core\Files\CSS\Base->update()
#5 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/files/css/post.php(199): Elementor\Core\Files\CSS\Base->enqueue()
#6 /home/rqjihx0/public_html/wp-content/plugins/eleme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-19 22:16:18 [error X 3][/home/rqjihx0/public_html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /home/rqjihx0/public_html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/base/document.php(810): Elementor\Elements_Manager->create_element_instance(Array)
#1 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/base/document.php(535): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#2 /home/rqjihx0/public_html/wp-content/plugins/elementor/modules/library/documents/library-document.php(65): Elementor\Core\Base\Document->get_initial_config()
#3 /home/rqjihx0/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(923): Elementor\Modules\Library\Documents\Library_Document->get_initial_config()
#4 /home/rqjihx0/public_html/wp-content/plugins/elementor/core/editor/editor.php(527): Elementor\Controls_Stack->get_config()
#5 /home/rqjihx0/public_html/wp-includes/class-wp-hook.php(292): Elementor\Core\Editor\Edito [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by Berque** [comment]
Hello,
I am facing the very same problem. We probably are using the same theme, as i can see the setup is pretty much similiar. But I believe "Aheto  1.0.9.4.4" is causing the problem. It started after updating this. Even i deactivate all other plugins, it still is buggy and website shuts itself down. Then i get the recovery mode email...

**Comment by DorShahar** [comment]
Hi
As @Berque mentioned - Please try to change to Elementor Hello theme and disable other plugins and see if the problem appears. 

Let us know if the problem is on our side.
Thanks

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
