### ISSUE TITLE
is there any way to show external api data with elementor?

### ISSUE THREAD

**Issue by slim-python** [elementor/elementor#14292]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by DorShahar** [comment]
Hi

1. Create a child theme
2. In `functions.php` use this code snippet:


```
function load_js(){
   wp_register_script('customjs',get_stylesheet_directory_uri() . '/js/scripts.js',['elementor-frontend'],1, true);

    $data_detials = api_call(<THE API CALL>);
    wp_localize_script('customjs','detailsObj',$data_detials);
    wp_enqueue_script('customjs');
}

add_action('wp_enqueue_scripts','load_js');

function api_call() {
    $request_url = <REQUEST URL>
    $curl = curl_init();
    curl_setopt($curl,CURLOPT_URL,$request_url);   
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    $response = curl_exec($curl);
    curl_close($curl);

    return json_decode($response);
}
```

3.  Create file name `scripts.js` in a file name `js` under the child theme directory 
4. The data will be stored in `detailsObj` and you can use it in `scripts.js`. For example, `scripts.js` can look like this:
```
function myInit(){
    console.log('Scripts are loaded');
    console.log('detailsObj');
}


window.addEventListener('load', function() {
    myInit();
});
```

Good luck
