### ISSUE TITLE
Text form fields disappear when using Crocoblock JetEngine's "Dynamic Visibility for Widgets & Sections"

### ISSUE THREAD

**Issue by marcel-za** [elementor/elementor#14303]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After extensive support assistance from Crocoblock: 
"Things are so that Elementors conditions (especially Elementor Form widget) do not allow our plugin to work correctly.
﻿We reported this information to Elementor, tried to contact them. But we never get any solution. ﻿For our part, there's nothing we can do. We can't fix it, unfortunately. Maybe if you will try to contact them - it will help! We will be glad if you can find out something and write to us!"

WordPress 5.7
Elementor 3.1.4
Elementor Pro 3.2.0
JetEngine (by Crocoblock) 2.7.4
No other plugins installed
TwentyTwentyOne theme

JetEngine: all options are off except the "Dynamic Visibility for Widgets & Sections" feature

On back-end, text fields appear as normal. 

On the front-end, text fields are entirely removed/gone from the code.
(only text fields. All other fields incl email, telephone, hidden, textbox, etc do not have this issue)

The moment the "Dynamic Visibility for Widgets & Sections" feature is off, there is no problem.

Using the default contact form, this is the html on the front end:

<div class="elementor-field-type- elementor-field-group elementor-column elementor-field-group-name elementor-col-100"><label for="form-field-name" class="elementor-field-label">Name</label> </div>

Note that the first email class, "elementor-field-type-", should actually read "<div class="elementor-field-type-text elementor-field-group elementor-column elementor-field-group-name elementor-col-100">"

ie. "elementor-field-type-text" has the word 'text' removed with Dynamic Visibility is on.

## Steps to reproduce

1. WordPress with only these 3 plugins (listed above) installed.
2. Add a default Elementor form to a Page (e.g. default contact form)
3. Publish
4. View/preview Page
5. Text fields do not appear, all other fields work as expected

Any changes to the form field, including changing 'required', adding a ID, adding/removing default value, etc make absolutely no difference.

## Isolating the problem
- [  ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with only Elementor plugin active (and Elementor Pro) and JetEngine
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: mariadb.org binary distribution v10.3.28
	PHP Version: 7.4.16
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://redacted
	Home URL: https://redacted
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-ZA
	Timezone: Africa/Johannesburg
	Admin Email: redacted
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.0
		Author: Elementor.com

	JetEngine
		Version: 2.7.4
		Author: Crocoblock

== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	archive : 2
		theme-archive-title : 1
		uael-posts : 1
	footer : 1
		button : 2
		divider : 3
		heading : 4
		image : 1
		social-icons : 1
		uael-nav-menu : 6
	header : 2
		button : 7
		global : 6
		heading : 1
		html : 2
		image : 5
		nav-menu : 3
		uael-nav-menu : 2
		woocommerce-menu-cart : 1
		wp-widget-bcn_widget : 1
	page : 18
		button : 1
		divider : 1
		dyncontel-content : 1
		gallery : 1
		heading : 2
		image : 1
		shortcode : 1
		text-editor : 1
	popup : 7
		form : 1
		heading : 2
		shortcode : 2
		uael-image-gallery : 1
	product : 0
		button : 1
		global : 1
		heading : 1
		theme-page-title : 1
		uael-woo-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-price : 1
	section : 27
		button : 4
		heading : 1
		image : 1
		jet-listing-dynamic-field : 5
		jet-listing-dynamic-image : 1
		jet-listing-dynamic-repeater : 2
		nav-menu : 1
		shortcode : 1
	widget : 0
		button : 39
		heading : 13
		image-carousel : 32
		single-posts-menu : 5
		woocommerce-menu-cart : 39
		wp-widget-bcn_widget : 39
	wp-page : 1
		button : 1
		countdown : 1
		dyncontel-animateText : 1
		heading : -36
		icon-list : 1
		image : -4
		jet-engine-booking-form : 1
		menu-anchor : 2
		tabs : 1
		uael-advanced-heading : -5
		uael-fancy-heading : 1
		uael-image-gallery : 1
		uael-marketing-button : 1
	single-post : 2
		divider : 1
		global : 1
		heading : 4
		jet-listing-dynamic-field : 4
		jet-listing-dynamic-image : 1
		jet-listing-dynamic-repeater : 2
		post-info : 1
		post-navigation : 2
		posts : 1
		share-buttons : 1
		shortcode : 2
		template : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
		uael-nav-menu : 1
		uael-posts : 1
	single-page : 2
		divider : 1
		heading : 1
		theme-page-title : 1
		theme-post-content : 2
		theme-post-title : 1
		theme-site-logo : 1
	product-archive : 0
		dyncontel-title : 1
		uael-woo-products : 1
	jet-listing-items : 0
		button : 2
		icon : 1
		jet-listing-dynamic-field : 5
		jet-listing-dynamic-image : 2
		jet-listing-dynamic-repeater : -1

== Log ==
	
Log: showing 20 of 242021-03-07 20:23:56 [info] dynamic-content-for-elementor::dce_updater Started 
2021-03-07 20:23:56 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Start  
2021-03-07 20:23:56 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Finished 
2021-03-07 20:23:56 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Start  
2021-03-07 20:24:02 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Finished 
2021-03-07 20:24:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic Content For Elementor',
  'from' => '1.12.3',
  'to' => '1.12.4',
)]
2021-03-07 20:24:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic Content For Elementor',
  'from' => '1.12.3',
  'to' => '1.12.4',
)]
2021-03-11 22:16:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-11 22:16:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-15 19:17:37 [info] dynamic-content-for-elementor::dce_updater Started 
2021-03-15 19:17:37 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Start  
2021-03-15 19:17:37 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Finished 
2021-03-15 19:17:37 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Start  
2021-03-15 19:17:38 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Finished 
2021-03-15 19:17:38 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Start  
2021-03-15 19:17:38 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Finished 
2021-03-15 19:17:38 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Start  
2021-03-15 19:17:39 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Finished 
2021-03-15 19:17:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic Content For Elementor',
  'from' => '1.12.4',
  'to' => '1.13.0',
)]
2021-03-16 09:51:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]

JS: showing 3 of 3JS: 2021-03-03 10:15:34 [error X 4][https://www.psasouthernafrica.co.za/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:36788] Cannot read property \&#039;attributes\&#039; of undefined 
JS: 2021-03-03 11:50:10 [error X 1][https://www.psasouthernafrica.co.za/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view12646\&quot;) has already been destroyed and cannot be used. 
JS: 2021-03-03 11:50:10 [error X 1][https://www.psasouthernafrica.co.za/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view12684\&quot;) has already been destroyed and cannot be used. 

PHP: showing 15 of 15PHP: 2021-03-09 16:29:37 [notice X 5][/var/web/site/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::215] Undefined index: field_label [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-10 09:48:31 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13151928 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-10 10:08:30 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13152736 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-10 15:11:27 [error X 2][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13151960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-10 16:02:02 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13153992 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-10 17:56:23 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13152832 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-11 16:44:38 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13152264 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-11 21:49:13 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/categories.php::245] Out of memory (allocated 73400320) (tried to allocate 32768 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 13:14:26 [notice X 32][/var/web/site/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1050] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 13:14:41 [notice X 20][/var/web/site/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::2060] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-17 13:04:02 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 14138616 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-18 15:42:36 [notice X 2][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-18 16:26:54 [notice X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/files/css/base.php::441] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-19 14:42:24 [error X 1][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 268435456 bytes exhausted (tried to allocate 13925080 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-19 15:04:59 [notice X 26][/var/web/staging/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-base.php::212] Undefined index: allow_multiple [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

</details>

**Comment by marcel-za** [comment]
@crocoblock

**Comment by shilo-ey** [comment]
Hey @marcel-za 

I am sorry you are experiencing this.
We work hard on providing features to our users. 
If there's a 3rd party extension that adds extra functionality Elementor doesn't allow - they should comply with the API guidelines we expose for extending Elementor.

I don't know about any report from @crocoblock end and I encourage them to contact us via our partners representative. 

Unfortunately, there's nothing we can do in this matter.

Thanks

**Comment by marcel-za** [comment]
@shilo-ey I have been told by @crocoblock that they have posted the issue here: https://github.com/elementor/elementor/issues/13117
