### ISSUE TITLE
data-elementor-device-mode not correct

### ISSUE THREAD

**Issue by Yaohotnik** [elementor/elementor#14322]
The internal pages of the site do not adapt correctly
https://test.yaohotnik.pro/product-category/teplovizory/

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
