### ISSUE TITLE
❌ 🚀 Feature Request: Customizing the icon on post navigation?

### ISSUE THREAD

**Issue by J-Skarbek** [elementor/elementor#14348]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by J-Skarbek** [comment]
Hello,

With Elementor Pro, I'm using the Post Navigation Widget. I guess my request is 2 part. One, a good feature for this widget would be to allow a user to select any svg icon for it, rather than the predetermined list provided by elementor.

The second part is: how would I go about using a custom icon here? Right now you're limited to 'angle', 'double angle', 'chevron', etc. I'd like to upload a thinner angle icon than the one that is provided. Within post-navigation.php, I have found this array:

`$this->add_control(
			'arrow',
			[
				'label' => __( 'Arrows Type', 'elementor-pro' ),
				'type' => Controls_Manager::SELECT,
				'options' => [
					'fa fa-angle-left' => __( 'Angle', 'elementor-pro' ),
					'fa fa-angle-double-left' => __( 'Double Angle', 'elementor-pro' ),
					'fa fa-chevron-left' => __( 'Chevron', 'elementor-pro' ),
					'fa fa-chevron-circle-left' => __( 'Chevron Circle', 'elementor-pro' ),
					'fa fa-caret-left' => __( 'Caret', 'elementor-pro' ),
					'fa fa-arrow-left' => __( 'Arrow', 'elementor-pro' ),
					'fa fa-long-arrow-left' => __( 'Long Arrow', 'elementor-pro' ),
					'fa fa-arrow-circle-left' => __( 'Arrow Circle', 'elementor-pro' ),
					'fa fa-arrow-circle-o-left' => __( 'Arrow Circle Negative', 'elementor-pro' ),
				],
				'default' => 'fa fa-angle-left',
				'condition' => [
					'show_arrow' => 'yes',
				],
			]
		);`


I haven't found anything in docs that says how to do this, and can't find it on the regular forums either. I found this page https://code.elementor.com/methods/elementor-widget_button-_register_controls/, but it doesn't quite explain everything. 

I believe I should be able to essentially create a plugin that will essentially replace this array with a new one, that is the exact same, except adds a row to the array like this:

`'fa fa-thin-angle-type' => __( 'Thin Angle', 'elementor-pro' ),`

The only question I have is how would I upload the actual graphic to the site to be categorized as 'fa fa-thin-angle'? I've looked through the other files called at the top of post-navigation.php (I cannot find the controls_manager or group_control_typography files:
`use Elementor\Controls_Manager;
use Elementor\Core\Kits\Documents\Tabs\Global_Colors;
use Elementor\Core\Kits\Documents\Tabs\Global_Typography;
use Elementor\Group_Control_Typography;
use ElementorPro\Core\Utils;`

When I look through here, I don't see where the icons would be called from in the array above.

Is this possible to do: add an svg to the wordpress media library so it can be assigned a URL, then referencing it in the array so it will show up in the post-navigation widget?

**Comment by nicholaszein** [comment]
Hello @J-Skarbek,

Thanks for your feedback! 🙏 

### ❌ 🚀  While reviewing your request we noticed it was missing the following key information:

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and explain in detail what your request is going to solve. Describe the solution and give context. Be thorough.
- 📝 **Describe the Solution:** Try to be as thorough as possible, giving details of what you expect from this new feature.
- 🔀 **Describe Alternatives:** Please provide some examples of alternatives so we can understand your request better.
- 🎯 **Additional Context:** Can you give us more details about the intended use of this new feature?

Feel free to submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request) following these guidelines. 😉 

Take care,

Nick
