### ISSUE TITLE
Theme Builder - Can't change Template Conditions or Rename Template

### ISSUE THREAD

**Issue by SmoothPixelUK** [elementor/elementor#14350]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
<img width="922" alt="Screenshot 2021-03-24 192804" src="https://user-images.githubusercontent.com/36083601/112372014-29ad1b80-8cd7-11eb-977a-e8a524ca8427.png">

Within the Theme Builder interface, whenever I try to **Edit Conditions** for a template, I cannot save the changes. Clicking the green **Save & Close** button does nothing apart from a split-second flash (as if a loader icon is displayed for few milliseconds in place of the button). Clicking the button doesn't **Save** or **Close** anything.

I have tried this with several different installs, including a fresh install of WP + Elementor + Elementor Pro today. While my dev environment is Windows 10 + IIS, I have also tried this on my Linux cPanel webhosting.

The problem exists when opening Theme Builder from within the Elementor page builder, and from the Elementor menu from the main WP admin. It also exists no matter which template I try to change the conditions for (single page, header, footer etc).

The only way I can edit the conditions for the template is to load the template in the page builder, then go to Update > Display Conditions.

<img width="391" alt="Screenshot 2021-03-24 195129" src="https://user-images.githubusercontent.com/36083601/112374783-6d555480-8cda-11eb-9581-079e3ebfc0d6.png">

This is really tedious when you need to remove a condition from an older template before adding it to a new template!
 

## Steps to reproduce

- Open up Theme Builder, either:
 - Elementor page builder main settings > Theme Builder
 - WP admin > Templates > Theme Builder > Try It Now
- Select any template, then click Edit Conditions (see arrow 1 below)
- Add/Edit/Remove a condition then try to **Save & Close**
<img width="635" alt="Screenshot 2021-03-24 200721" src="https://user-images.githubusercontent.com/36083601/112376817-d3db7200-8cdc-11eb-912d-bb1cd8a09a19.png">

For a bonus bug, see arrow 2 above!
- Can't **Rename** the template
 - Click **Rename**
 - Change the template name in the popup dialogue box
 - Click **Change**
 - Dialogue closes without changing the name. (Same thing if you click **Cancel**)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/10.0
	MySQL version: MySQL Community Server (GPL) v5.7.32
	PHP Version: 7.4.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: http://examplesite.local
	Home URL: http://examplesite.local
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	wp-page : 1
		form : 1
		text-editor : 1
	single-page : 1
		button : 5
		heading : 7
		image : 3
		social-icons : 1
		testimonial : 1
		text-editor : 3
		video : 1


== Log ==
	
Log: showing 11 of 112021-03-24 18:20:16 [info] elementor-pro::elementor_pro_updater Started 
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-03-24 18:20:16 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-03-24 18:20:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.2.1',
)]
2021-03-24 18:20:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.2.1',
)]

PHP: showing 1 of 1PHP: 2021-03-24 18:23:15 [notice X 3][C:\Users\ExampleUser\Websites\ExampleSite\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by ScottKemp** [comment]
I second this.  Exact same problem. Windows 10, Chrome and Firefox replicating.

**Comment by SmoothPixelUK** [comment]
Just tested again today, and all issues appear to have been fixed.

WP5.8, Elementor 3.3.1, Elementor Pro 3.3.4

Have tested on Win10 + IIS dev environment and Linux cPanel production site.

@ScottKemp - can you confirm it's fixed for you and I'll close this issue. Thanks.
