### ISSUE TITLE
Ability to replace hamburger and associated close icon.

### ISSUE THREAD

**Issue by samuelgoldenbaum** [elementor/elementor#14357]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Users must be able to replace the hamburger icon with an icon from custom icons, or an SVG/image upload. Right now, even in beta 3.2 pro - the entire eicons.woffs are downloaded just to display 2 icons.

**Describe the solution you'd like**
Apply the same logic as used for other icons like social.

**Describe alternatives you've considered**
Not using Elementor when basics like this are ignored.

**Additional context**

**Comment by alexcumbers** [comment]
Agreed, I've asked for this.  We can save a lot of bandwidth by enabling this.

**Comment by come456456456** [comment]
Lots of people have this issue including me. There is already a topic about it and it is broader because it include:
- hamburger open/close icon in responsive nav.
- The social share buttons widget.
- The popup close icon.

The link of the topic is here : https://github.com/elementor/elementor/issues/11361

**Comment by alexcumbers** [comment]
Perhaps this is part of SVG icon instead of eicons font #11361

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
