### ISSUE TITLE
Cannot log in to dashboard

### ISSUE THREAD

**Issue by task1tvs** [elementor/elementor#14365]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

I was editing using Dev Edition when my mac re-booted. Now I cannot log in to the WP dashboard. At first when logging in with user details it would appear like I had logged in but would just take me to the front end site not the dashboard. I have cleared browser cache, cleared server cache, tried incognito, tried different browsers. I have been on call with support from my host for over an hour and they can't resolve the issue either, they have whitelisted my IP, I have disabled my firewall. I added a new user in the database and now it shows me a bar across the top of the screen, if I click on the dashboard nothing happens and the only other two items showing are Elementor, Debugger and Report and Issue.  Screenshot attached.

![Screenshot 2021-03-26 at 18 38 48](https://user-images.githubusercontent.com/78282225/112679755-74a86980-8e64-11eb-819f-dc6cbdfbde71.png)

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
