### ISSUE TITLE
Hello I have a problem, everything I integrate in the site is replicated for 3, I do not know how to solve it, I am using wordpress, if someone could help me I would be very grateful

### ISSUE THREAD

**Issue by waznauwaga** [elementor/elementor#14367]
do not leave anything in the description because the problem is defined in the title, I forgot to say that I am using the pro version of elementor
my email is rpemcampos@gmail.com, if someone from elementor could help me

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
