### ISSUE TITLE
Custom Query Filter - sorting by acf custom field

### ISSUE THREAD

**Issue by hellomahfuzpro** [elementor/elementor#14374]
I have a custom post type called music, I want to sort the order of the music posts by a custom field called 'music_featured'. Also, I filtered music posts by custom taxonomies from the post widget. So far I've written this code for the sorting

`add_action( 'elementor/query/my_custom_music_feature_sorting', function( $query ) {

	$meta_query = $query->get( 'meta_query' );
	$query->set( 'meta_query', $meta_query );
	$query->set('orderby', 'meta_value'); 
	$query->set( 'order', 'ASC' );
	$query->set('meta_key', 'music_featured' );

} );`

But it seems it's not working. How do I get it working?
Thanks

**Comment by DorShahar** [comment]
Hi @hellomahfuzpro 
Please look at this issue: #9770. 

If this didn't help you, open a new issue and mention this and #9770.

Thanks
