### ISSUE TITLE
Stretch section is not working with Elementor 3.1.4 + Elementor Pro 3.2.1

### ISSUE THREAD

**Issue by RickSlashee** [elementor/elementor#14386]
I am trying to work on a simple page, but the stretch section is unresponsive. It works when I set it up the very first time. In the Header the stretch section works flawlessly, but it won't accept it in the homepage.

![image](https://user-images.githubusercontent.com/40864652/112985101-ff1af280-911c-11eb-9fff-780e2dc21cbe.png)

**Comment by DorShahar** [comment]
Hi @RickSlashee 
Please follow the guidelines in the  [learn more](https://elementor.com/help/how-to-create-a-full-width-page/?utm_source=editor-panel&utm_medium=wp-dash&utm_campaign=learn) link.

I wasn't able to reproduce the problem. 

If this still didn't work, and in case you are a Pro user you are welcome to contact our Support team. 
Else, open a new issue and mentions this one, and add steps to reproduce and the system info so we could investigate. 

Thanks
