### ISSUE TITLE
"Collect Submission" - Action after Submit enabled by default

### ISSUE THREAD

**Issue by thorsolutions** [elementor/elementor#14399]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For those upgrading to the latest version of Elementor Pro and with many forms on a site this is going to be a hassle to go in and update all forms with the "Action on Submit"

**Describe the solution you'd like**
If by default when people enable Collect Submissions feature in the Experiments, "Action after submit" of Collect Submissions should be simply added to all the forms and then the user can go in and remove it if they don't want it on any form. 

**Describe alternatives you've considered**
Barring this, most will have to stick to third party plugins.

**Comment by mcrowell** [comment]
+1

**Comment by shilo-ey** [comment]
Hey @thorsolutions 

This is the behavior, the action is added to all forms once the experiment is active.

If you wish to disable it you need to go form by form and remove the default action after submit.

Thanks

**Comment by thorsolutions** [comment]
Noted thanks, on a few of the websites where I enabled this, only new forms had this enabled by default not all forms which had already been created. I am going to test it on some other sides and come back to you if I can replicate the issue.
