### ISSUE TITLE
Elementor Layout / Breakpoints does not match with Bootstrap 5 container width and breakpoint

### ISSUE THREAD

**Issue by themeix** [elementor/elementor#14401]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am using elementor in my theme and facing some weird issue for layout match with Bootstrap 5. 
In bootstrap 5, there has 6 breakpoints.

Extra small<576px 
Small≥576px 
Medium≥768px
Large≥992px 
X-Large≥1200px
XX-Large≥1400px

But in elementor there have only 3 breakpoints and we can set custom content width for mobile, tablet, desktop. 

So that will not work if i use bootstrap container and elementor container in the same page. Please give bootstrap 5 support option in elementor for the developers.

Thanks

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread

Without it, we simply can't help.

Thanks.
