### ISSUE TITLE
Internal note field for NEW form submissions

### ISSUE THREAD

**Issue by fuzenco** [elementor/elementor#14404]
You should add an internal notes field to the new form submissions feature. Just a simple plain text field in the right sidebar or somewhere so that site owners can jot down a note about the submission. It would make for a simple CRM solution.

**Comment by Aviad-Herman** [comment]
Hi @fuzenco,
That is a really good Idea but we are actually trying to steer away from becoming a CRM.
I do have a hack to offer:

You can add a Hidden field (field type = Hidden) to the form and then use it for personal notes later by editing its content.
Let me know if you need any further assistance.

**Comment by fuzenco** [comment]
Well, I wasn’t asking you to become a CRM. But your solution will do. Thanks.
