### ISSUE TITLE
Option to style the ul, ol and il

### ISSUE THREAD

**Issue by neiltomlow** [elementor/elementor#14405]
Hi there,  
I've got an idea/request to have a option within your Elementor   Customizer.   One thing that I miss, and really should be a huge help, is the option to   style the ul, ol and il that are used within the text editor. At this moment (I use by default your Hello theme) I need to set this with a custom css   because the bottom padding is always to small. 

Please consider this. Shouldn't be much work for you to build ;-)
--

![Screenshot_2021-04-02 Elementor Dorpsoverleg](https://user-images.githubusercontent.com/5989725/113399808-1ec24d00-93a1-11eb-9c83-106d67107df1.jpg)

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
