### ISSUE TITLE
Support to Google Core Web Vitals

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#14429]
Core Web Vitals are a new initiative from Google designed to measure and improve user experience on the web. 
Refer to this article - https://web.dev/vitals/

I tested the Elementor website with the page speed insights tool. Here is the performance of the same  - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Felementor.com%2F&tab=mobile

Here you can check, one of the major issues is "Eliminate render-blocking resources"
It includes the Elementor and Elementor Pro's Frontend.min.css files which almost takes 300ms for each!

In the Frontend.min.css file, we load all the widgets common CSS! Can we add some features like enqueue CSS only for the widgets loaded on the page?
Like we already have get_script_depends() function for JS!

**Comment by shilo-ey** [comment]
We are aware of the performance improvements needed in order to improve Elementor.

In our latest releases, we released various improvements and will keep on adding more improvements such as breaking CSS files to be loaded conditionally based on the widgets being used.

Thanks for raising this issue, you can keep on tracking this thread.

**Comment by asadkn** [comment]
I have noticed the focus seems to be mainly on CSS split. That's great. However, don't forget JS - the unused JS is an even  bigger offender as parsing a larger JS payload isn't cheap.

There's just too much unused JS. The payload size on network is a smaller issue, but the bigger issue is that it contributes to a lot of parsing time on slow mobile devices blocking the main thread, even if not all of it is executed.

**Comment by joshcummingsdesign** [comment]
The Image Carousel widget does not include image sizes which gets flagged in Web Core Vitals as being an issue. This and render-blocking scripts seem to be the two issues I'm struggling with the most.

**Comment by joshcummingsdesign** [comment]
I opened #15014 two months ago, but it's still awaiting review. @shilo-ey Can you take a look, or have someone approve it? A simple fix which improves Web Core Vitals support.

**Comment by rami-elementor** [comment]
> In the Frontend.min.css file, we load all the widgets common CSS! Can we add some features like enqueue CSS only for the widgets loaded on the page? Like we already have get_script_depends() function for JS!

Elementor supports both `get_script_depends()` and `get_style_depends()` (see [reference](https://developers.elementor.com/docs/widgets/widget-dependencies/)).

We do invests time and effort to make Elementor faster, please read [this post](https://developers.elementor.com/how-elementor-improved-asset-loading-and-made-your-website-run-faster/).

Splitting the CSS not always improves performance. Although the final CSS is smaller, but you get more HTTP requests. This can lower your site performance. We are working with Google CWV team to add more improvements.

For now, I'm closing this ticket as it has no practical suggestion to fix existing issues.
