### ISSUE TITLE
Avoid Duplicates not working Elementor 3.1.4

### ISSUE THREAD

**Issue by parksidemedia** [elementor/elementor#14434]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Avoid duplicates is not working as expected. It was working fine until the latest updates of WP and Elementor.

![screencapture-homemagazine-nz-2021-04-06-11_43_16](https://user-images.githubusercontent.com/82002764/113639574-922fcb80-96cd-11eb-815c-3674de6eeb6a.jpg)

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hey @parksidemedia 

Thanks for your input.

Unfortunately, we couldn't reproduce your issue with the latest version of Elementor.

Please contact our support for inspecting your specific problem.

Thanks
