### ISSUE TITLE
Conflict with the visual product configurator plugin

### ISSUE THREAD

**Issue by carmendas** [elementor/elementor#14439]
Hello! I am a developer of the visual product configurator plugin. We have a conflict with the elementor plugin and we had asked the client to put us in contact with you. The problem is that when we load our configurator, all the radio inputs previously checked are unchecked.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* **Steps to replicate**
* **Isolating the problem**
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
