### ISSUE TITLE
Text color icon widget icon in Safari browser

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14447]
In some cases, the text color of the icon list widget in the Safari browser is red.
Please check.

Thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
