### ISSUE TITLE
Add dynamic tags feature to code highlight widget

### ISSUE THREAD

**Issue by SaltedLevity** [elementor/elementor#14441]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allowing code to be pulled from a field of a post, enabling quick code submissions to be displayed in the elementor code widget in templates. For example having editors be able to quickly enter code snippets (for display, reader copying, review, educational purposes, etc.) into a custom post type or a custom field, and then have a template be able to pull in that field dynamically to show the different entries.

**Describe the solution you'd like**
Just add the "dynamic tag" capability that exists for most inputs (text boxes, images, heading text, etc.) to the "Code" input field of the code widget. 

**Describe alternatives you've considered**
There is a plugin that allows for code entry in ACF: https://wordpress.org/plugins/acf-code-field/ I'd like to combine that plugin's ability with elementor to be able to dynamically display different code (markup) text blocks in a template.

**Additional context**
![image](https://user-images.githubusercontent.com/54490191/113683591-617e7080-9692-11eb-894a-e43ed41751ba.png)
^just this thing, with ACF field support, in the code highlight widget.

**Comment by Aviad-Herman** [comment]
Hi,
I'm closing this issue as this feature has been added.
We know about bug #14766, it is being handled.

Thanks,
