### ISSUE TITLE
A few suggestions for improving elementor and elementor widgets 

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14450]
1- Add border-radius to the slider widget. Very necessary
2- Add the ability to move the icon to the left of the text in the icon list widget.
3- When we put the jet smart filter plugin widget in the elemental pop-up, it does not work. If in the Offcanvas content widget, the power pack plugin works. And if possible, add this feature to the pop-up mentor.

4- Please customize the comments section of the hello elementor template. Very simple and beginner.
please check it.

thanks

**Comment by DorShahar** [comment]
Hi 
Thank you for your comments. We are aware of them, and we will try to address them. 
For next time, please open an issue for a feature request/improvement per topic - so it will be easy for us to track it.

I'm merging this issue with #6110 related to the last bullet. 

Thanks for your feedback!
