### ISSUE TITLE
Post Slider or Post Carousel

### ISSUE THREAD

**Issue by CordialGit** [elementor/elementor#14461]
Elementor doesn't have a Post Slider. I'm requester that Elementor adds a Post Slider/Carousel.

Or, since Elementor already has Slides widget, it should make it possible for us to choose Post Type-- where we can choose Post Source--in which case we can choose Posts, Pages or Custom Post Type. And the second option will be Manual-- where we can then create Slides as is already possible with the Slides widget.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Carousel widget released with Elementor Pro v3.11.0! 🥳 

With the new Loop Carousel widget, you can customize your post listings with custom templates (including WooCommerce Products)! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Carousel layout, design, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-carousel/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
