### ISSUE TITLE
Feature Add icon to elementor navigation menu

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14472]
Please add the ability to add icons to the elementor pro navigation menu.
It's so important.

thanks

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hi @79ho3ein!

I'm just catching up. 😉 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.13.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
