### ISSUE TITLE
Templates for error codes other than 404 (410 Gone, etc.)

### ISSUE THREAD

**Issue by lannyheidbreder-mc** [elementor/elementor#14478]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I use HTTP response 410 Gone for deleted content. It would be great to be able to make Theme Builder templates for this, just like we can for 404.

I went looking to see if I could add these myself. In `elementor-pro/modules/theme-builder/`, I found `conditions/not-found404.php` and `documents/error-404.php`. None of the classes used in these files seem to be documented on the developer site. I could dig further and try to see how to register my own instances of these classes, but I hesitate to spend a bunch of time on a possibly-unsupported type of extension that might stop working at any time.

I would like any or all of the following:

- The built-in ability to make Theme Builder templates for any 4xx HTTP response code
- Documentation on how to make custom Theme Builder documents and conditions
- To be told that these APIs aren't any more likely to randomly change on a point release than any of the APIs that *are* documented

I suppose I could use another plugin that allows template files for other error codes, then use shortcodes to embed a non-Theme Builder template, but that's yucky.

**Comment by DorShahar** [comment]
Hi @lannyheidbreder-mc 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.

**Comment by lannyheidbreder-mc** [comment]
@DorShahar Thanks. What about the developer APIs to let us do it ourselves? Is that something you'd encourage us to dig into, or would you warn us away from it since those APIs are not documented?

**Comment by DorShahar** [comment]
Hi @lannyheidbreder-mc 
In general - we encourage you to use our API and dig into our code. 
We are aware of the lack of our documentation, and we will improve it, but you know - it takes time...

For any question - feel free to raise it up on GitHub or on Facebook.

Thanks
