### ISSUE TITLE
Elementor Pro - Custom fonts not loading on all pages due to fontface declaration in a single page's css

### ISSUE THREAD

**Issue by ianlee** [elementor/elementor#14479]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
We have a font that is being used on certain headings (h2) and one of those (an h2) is always in the elementor theme builder footer.
Occasionally, on certain pages, the font isn't loaded even though the font should be applied to a heading in the footer (ie on every page).  The font seems to load on pages where the heading exists in the body/content but not on pages without. 

From what I can tell, the font-face declaration is sometimes loaded in the Homepage's css file instead of one of the more global template's css files.  These global template files are reused between pages, and when navigating to another page, none of the loaded css files have the font-face declaration.

I presume this is a product of the advanced settings css print method: external file (default).

This may be exacerbated by caches, minifiers, etc.

As a temporary work around on the site I'm maintaining, I've duplicated the font declaration into a custom css file.

## Steps to reproduce

- add custom font.
- create 2 pages : P1, P2
- on P1, have the custom font. 
- on P2, don't.
- create a theme builder footer with the custom font
- apply footer template to entire site
- clear css cache, 
- load the P1 - page with the custom font first. (all instances of custom font should load)
- check page without the custom font in content (custom font instance in footer should not load) 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @iamntz 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
