### ISSUE TITLE
Trending Posts Widget

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14473]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
I use the "posts" widget that is on elementor pro, and I want the widget to be able to display posts based on posts are "trending" on the site.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10258, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
