### ISSUE TITLE
Shortcodes in popup are not working with lastest update.

### ISSUE THREAD

**Issue by Rubbal9** [elementor/elementor#14485]
![image](https://user-images.githubusercontent.com/53484443/114002307-600f9c80-987a-11eb-966f-15a252410f00.png)

Elementor version 3.1.4

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
