### ISSUE TITLE
Repeater control "sort update" issue for tabs, toggle and accordion.

### ISSUE THREAD

**Issue by CodeExplore** [elementor/elementor#14494]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
There is **repeater** control **sort update** issue. This issue same in Tabs, Toggle, Accordion repeaters. Suppose you have added a Tabs or Toggle widget then go to **Style** tab and change border-width then return back repeater and try to **sort update** it doesn't work.

https://user-images.githubusercontent.com/11369109/114053963-17ff7280-9898-11eb-906a-3621ceef7667.mp4

## Isolating the problem
- [x] I can reproduce this bug consistently using the steps above.

## Environment
It's same in all versions (also development version same).

**Comment by CodeExplore** [comment]
Isn't that important to anyone? :)

**Comment by rami-elementor** [comment]
Tested with the latest Elementor version and the new 3.7-beta-1 version. In both versions it works as expected.
