### ISSUE TITLE
🚀 Feature Request: Allow decimal EMs and REMs for sizing

### ISSUE THREAD

**Issue by Spleeding1** [elementor/elementor#14493]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I go to adjust the size of things, the options are "PX, EM, %, REM". While I agree "PX, %" only need whole numbers, to use "EM, REM" effectively there really needs to be one decimal. (1.3, 2.1, etc)

**Describe the solution you'd like**
When adjusting sizes in EMs and REMs, allow one decimal. (1.3, 2.1, etc)

**Describe alternatives you've considered**
I could use percentage, but then why even offer the EM and REM options

**Additional context**
<img width="298" alt="image" src="https://user-images.githubusercontent.com/34792693/114050325-29c22500-985a-11eb-90b1-6d5a3d44b027.png">

**Comment by nicholaszein** [comment]
Hello, this is actually a bug that we are already aware of. I will close this issue and point to bug report #18135 so we can track it better.

Thanks for reporting!
