### ISSUE TITLE
"panel/open_editor/widget" hook not firing for columns & sections

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#14492]
The hook doesn't seem to be firing for column & sections.

Because of this, the example you have  [here](https://code.elementor.com/js-hooks/#panelopen_editorelementType) doesn't really work as expected.

You can easily try it using:
```js
elementor.hooks.addAction( 'panel/open_editor/widget', function( panel, model, view ) {
	console.log( model );
} );
```
1. Open editor.
2. Click on several widgets.
3. Click on columns or sections.

You will see that for columns and sections the hook doesn't trigger at all.

Elementor Version 3.1.4

**Comment by shilo-ey** [comment]
Please change the route to `column` or `section` accordingly in the `panel/open_editor/widget` route.

**Comment by amyriounis** [comment]
@shilo-ey thanks for the quick response, although there is still an issue here.

In order to intercept the event you have to use a different route for these two, which is `panel/open_editor/column` for columns and `panel/open_editor/section` for sections. 

The `panel/open_editor/widget/` and thus `panel/open_editor/widget/section` & `panel/open_editor/widget/column` are **not** gonna work for columns and sections. 

You can easily test this by pasting this script to the dev console and click on a section or column

```js
// Sections
elementor.hooks.addAction( 'panel/open_editor/widget/section', function( panel, model, view ) {
    console.log('\nClicked on a section\nRoute is: "panel/open_editor/widget/section"');
} );
elementor.hooks.addAction( 'panel/open_editor/section', function( panel, model, view ) {
    console.log('\nClicked on a section\nRoute is: "panel/open_editor/section"');
} );

// Columns
elementor.hooks.addAction( 'panel/open_editor/widget/column', function( panel, model, view ) {
    console.log('\nClicked on a column\nRoute is: "panel/open_editor/widget/column"');
} );
elementor.hooks.addAction( 'panel/open_editor/column', function( panel, model, view ) {
    console.log('\nClicked on a column\nRoute is: "panel/open_editor/column"');
} );
```

The output will be:
![DeepinScreenshot_select-area_20210408211632](https://user-images.githubusercontent.com/9055437/114076995-fad69e00-98af-11eb-9120-a60fb7778b6a.png)

I m pointing this out because the example you show [here](https://code.elementor.com/js-hooks/#panelopen_editorelementType) is confusing:
![DeepinScreenshot_select-area_20210408211905](https://user-images.githubusercontent.com/9055437/114077223-3b361c00-98b0-11eb-9ae4-0f7191cee667.png)

as you are checking for `column` and `section` inside the `panel/open_editor/widget/` route which will **not** fire for any of those.
