### ISSUE TITLE
Add icon transfer option to the left of the text, in the icon list widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14503]
Hi
Please Add icon transfer option to the left of the text, in the icon list widget.
Like the image below :
https://prnt.sc/11874rx

Thanks.

**Comment by DorShahar** [comment]
Hi,
Thanks for reaching out. 
This option is available by default, so your request is unclear for us. See the image below: 
![image](https://user-images.githubusercontent.com/19154938/114601188-e4f51e80-9c9d-11eb-898e-550ca308c2b1.png)

Please share more information about your request - in a new issue. 

Thanks
