### ISSUE TITLE
Use of Vimeo subtitles parameters in video block 

### ISSUE THREAD

**Issue by ckri2000** [elementor/elementor#14505]
There is a compatibility limitation when using the video block along with vimeo. Vimeo uses parameters for some of its features, in particular to set certain subtitles by default (for example :
https://vimeo.com/503790722/7da1c4cdeb?texttrack=en-us )
This parameter feature is described here :
https://vimeo.zendesk.com/hc/en-us/articles/360027818211-Enabling-Captions-and-Subtitles-in-Embeds-by-Default

the parameter is removed by elementor when presenting the video.
You can see a test here (1st video) :
https://staging-mylivhaorg.kinsta.cloud/test-integration-vimeo/

As a workaround it is possible to use the html block along with vimeo ember player, which allows having vimeo parameters not stripped out. However, it would be much easier to have it directly work with the video block. 

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11161, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by jonasdumas** [comment]
+1
