### ISSUE TITLE
Elementor not Loading

### ISSUE THREAD

**Issue by tonyobj247** [elementor/elementor#14506]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
I am trying to develop a site using Astra Themes on my WAMP server, not live environment. I used the Sierra Industry Theme starter template. All plugins installed, but I cannot edit with Elementor. It shows a gray screen and the Elementor keeps loading without showing the editor section. It won't even show Edit in Safe Mode. 
I have disabled all plugins except Elementor. I'm using the current version of PHP, WordPress an MySQL as well as the current version of Elementor. 

![image](https://user-images.githubusercontent.com/67270462/114217465-1ac59a80-9960-11eb-81ab-74b07d58b259.png)

Kindly assist. Thanks

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
