### ISSUE TITLE
A few suggestions to improve the slider widget.Please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14507]
Hello
1- Option to change the flash slider by uploading an svg file.
2- Border radious option for the slider border.
3- Shading option for slider navigation buttons.
4- Border radious option for slider navigation buttons.
5- Hover animation option for flash slider.

Please check. Small cases, but very important

thanks

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Description and examples.**
* **One request per thread**

Without it - it is hard for us to filter and prioritize the requests. 
Thank you for your understanding.
