### ISSUE TITLE
Forms tab missing from template types

### ISSUE THREAD

**Issue by lindabenefield** [elementor/elementor#14508]
It was working just fine until today. The form tab to create a new form template is completely missing and my forms are saying type not supported. I was using them for ACF to add new posts through various relationship fields. Now, there's no way to add a form template. What happened?

**Comment by DorShahar** [comment]
Hi @lindabenefield 
What do you mean by "Form templates"? 

Thanks

**Comment by lindabenefield** [comment]
I actually found out that it was a tab put on there by ACF frontend form
and they decided to change it so that you can only use it if you get their
pro plugin. They never let anyone know, so I didn't know which plugin it
belonged to. But after some research, I figured it out. So, it's all good
now. Thanks!!

**Comment by DorShahar** [comment]
Happy to hear :)
