### ISSUE TITLE
image-set()

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#14502]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be great if CSS images were displayed in different sizes according to the screen resolution.

**Describe the solution you'd like**
Implementing image-set() solve this issue.
https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()
https://caniuse.com/css-image-set

**Comment by DorShahar** [comment]
Hi 
Thanks for reaching out.
We are exploring how to do this in the best way.

In the meanwhile, I'm merging this issue with #6778 for better tracking.

Thanks
