### ISSUE TITLE
Filter Post By Category

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14509]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
I want a widget that can display posts based on a certain category

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DorShahar** [comment]
Hi
Please see [this page](https://elementor.com/help/posts-widget-pro/) for more information.

You can ask for help from our support, or in the Facebook community. 

Thanks
