### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by AstroBoyD94** [elementor/elementor#14501]
Hi, All Responsive issue, testing in mobile or tablet force "columns" to 50% left align (new site so no possible cross script)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by AstroBoyD94** [comment]
I have since noticed... my responsive icons are gone from elementor... so when I change view it doesn't change edit that responsive layer... just desktop

**Comment by AstroBoyD94** [comment]
Ok, I have tested the actual view of the site's changes through elementor pro - no dev - on actual devices... I have concluded that the responsive view on elementor is not parallel to the actual devices... ergo ... although they look 50% left-aligned through elementor they are in fact perfectly centred on the device.

Have tried safe mode and have removed any new or un unused plugins that could have altered this. 

Would reinstalling elementor pro fix this... have already re-synced the css files and so forth... or is this a version issue... or

**Comment by dcexc** [comment]
its been happening the past 2 releases.  Still no sign of a fix. Who has time to keep loading on a device to check every single time you make an edit when your trying to build a page to be tablet friendly

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
