### ISSUE TITLE
Custom Code Bug Report. please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14519]
hello

In the custom code section, when saving the code, the save and close button is not inside the screen size. And I must set the browser zoom to 80% to make this button appear.While all browser magnifications are 100% by default.
Like the submitted photo

https://prnt.sc/119s5wr

thanks

**Comment by frydhogg** [comment]
same here, elementor teams need to fix this ASAP.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.3.1

Feel free to update

Thanks!

**Comment by 79ho3ein** [comment]
Thank you for your efforts❤
