### ISSUE TITLE
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RSS_Import has a deprecated constructor in /home/cedecrai/public_html/monwordpress/wp-content/plugins/rss-importer/rss-importer.php on line 43

### ISSUE THREAD

**Issue by cedec1985** [elementor/elementor#14510]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi 
This ain't related to Elementor. 
You can see that the problem caused by "rss-importer" plugins due to the root : `wp-content/plugins/rss-importer/rss-importer.php`.

Please address this plugin. 
Thanks
