### ISSUE TITLE
Please add Bodoni Moda to Google Fonts list

### ISSUE THREAD

**Issue by ArtstudioWorks** [elementor/elementor#14536]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Bodoni moda is missing from the fonts list although it is a Google font.

**Describe the solution you'd like**
The best solution is to add feature for google fonts list auto-update. A such powerful plugin must have it.

**Describe alternatives you've considered**
Add bodoni moda to fonts list manually.

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.4

Feel free to update!
