### ISSUE TITLE
Display of units

### ISSUE THREAD

**Issue by ytovman** [elementor/elementor#14546]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

When working on a desktop version with certain units and moving to any other view (tablet or mobile) a user does not see if any values have been set in the fields of

**Describe the solution you'd like**
In my opinion when switching between views a default view should preserve the values entered in the element creation.
Maybe light grey (before touching the area)

thank you

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #5018 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
