### ISSUE TITLE
Please make popup elementor compatible with jet smart filter plugin

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14542]
Hello
Please make popup elementor compatible with jet smart filter plugin.
Because when we put the filters on the pop-up element, it does not work. Please check. Very important.

thanks

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples: **Please add the link to this plugin for use to understand the use case**
* One request per thread

Thanks.
