### ISSUE TITLE
Image Gallery - Justified Mode - Row Height Slider doesn't change text box

### ISSUE THREAD

**Issue by DavidGMiles** [elementor/elementor#14549]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Image Gallery - Justified Mode - Row Height Slider doesn't change text box

## Steps to reproduce

Add an image gallery to a page, add some images, switch to justified mode, slide the slider for the row height - nothing changes for me.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.49-89.0
	PHP Version: 7.4.16
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://wordpress-556865-1829284.cloudwaysapps.com
	Home URL: https://wordpress-556865-1829284.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 1024M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

== Active Plugins ==
	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Download Plugins and Themes from Dashboard
		Version: 1.7.1
		Author: Algoritmika Ltd

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor - Events For Region Shortcode Wrapper
		Version: 1.0.0
		Author: 

	Elementor Pro
		Version: 3.2.0
		Author: Elementor.com

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.57
		Author: MalCare Security

	Pluginception
		Version: 1.3
		Author: Otto

	WP Debugging
		Version: 2.9.2
		Author: Andy Fragen

== Elementor - Compatibility Tag ==
	
	Elementor - Events For Region Shortcode Wrapper: header_not_exists
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	wp-page : 2
		gallery : 1
		icon-box : 3
		menu-anchor : 2

== Log ==
	
PHP: showing 3 of 3PHP: 2021-04-06 11:23:17 [notice X 3][/home/556865.cloudwaysapps.com/nfcxdabxxt/public_html/wp-content/plugins/elementor-events-for-region/widgets/class-events-for-region.php::164] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 11:25:14 [notice X 4][/home/556865.cloudwaysapps.com/nfcxdabxxt/public_html/wp-content/plugins/elementor-events-for-region/widgets/class-events-for-region.php::166] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-13 12:39:38 [notice X 1][/home/556865.cloudwaysapps.com/nfcxdabxxt/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by shilo-ey** [comment]
Please add your system info.

**Comment by DavidGMiles** [comment]
@shilo-ey I have verified it on 4 separate systems - one is bare-bones, elementor, elementor pro, hello - still broken

Actually worse than I thought, the space between slider is broken too

And spacing for masonry layout

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.
