### ISSUE TITLE
Pagination Ajax

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14557]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
I use the "post" widget in elementor pro
And I use pagination on the "post" widget, but when clicked, pagination reloads the page
What I want is, when pagination is clicked, the page doesn't load, so what I want is pagination using ajax.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by 79ho3ein** [comment]
+1

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!

**Comment by mushlih-almubarak** [comment]
Thank you very much!
