### ISSUE TITLE
Icon transfer option to the right, in the icon list widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14554]
Please add the icon transfer option to the right to the icon list widget.
It's a small thing, but it's necessary. https://prnt.sc/11ccokp

thanks

**Comment by 79ho3ein** [comment]
hello
excuse me @avivu  ...
How long does it take for such small features to be added to the plugin?

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. A list starts with an icon, not ends with one.

Please feel free to contact us again with other feature suggestions.

Regards,

**Comment by 79ho3ein** [comment]
hi @rami-elementor 
Isn't that a limitation for this widget?
Personally, there were many situations where I needed to move the icon to the end, but it was not possible.
Is it time consuming to add such a small feature? Or is it difficult to add?

**Comment by rami-elementor** [comment]
@79ho3ein 

We usually say - it's not a bug it's a feature.

But jokes aside, this is not a limitation, it's structured that way by design.

You don't use list bullets at the end of the line.

We develop for the majority, not rare use-cases.

**Comment by 79ho3ein** [comment]
ok,thank you @rami-elementor
