### ISSUE TITLE
Elementor not working

### ISSUE THREAD

**Issue by clangon** [elementor/elementor#14552]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by clangon** [comment]
When I click on the editor the wheel just spins and editor never shows up

**Comment by avivu** [comment]
Hello @clangon,
If the problem is still valid, please contact our support with all the necessary details to help you solve the problem.
Thank you!
