### ISSUE TITLE
Getting Started Video is not Available

### ISSUE THREAD

**Issue by khan-rafin-ahmed** [elementor/elementor#14567]
Hi guys,

The 'Getting Started' video shows this error 'Video is not available'. Here's the screenshot: https://d.pr/i/6zzkHZ

I hope it will be fixed with the next update.

Thank you!

**Comment by DorShahar** [comment]
Hi @khan-rafin-ahmed 
Thank you for taking the time and reporting this.
We recreated your process of work and it seems to work properly.

In case the problem continues - please open a new issue with system info and console errors. 

Thanks.
