### ISSUE TITLE
add_skin & nav-menu mobile problem

### ISSUE THREAD

**Issue by odoremieux** [elementor/elementor#14563]
If I create my own skin for nav-menu, the burger menu doesn't togle anymore on mobile.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
