### ISSUE TITLE
🔗 ⛔ Improved error avoid an excessive DOM size in elementor (Duplicate of #2100)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14577]
Hello, in the sites I created with elementor, there is always this error (avoid an excessive DOM size) in site speed test websites such as gt metrix and google page speed. Please resolve these issues. Elementor to make it stronger  needs.
Please share your thoughts on this

Thanks

**Comment by d19dotca** [comment]
This isn't always 100% on Elementor and can often come from ineffective design practices too (using too many inner sections when regular sections will work fine, for example). Just something to keep in mind. Also, it helps if you follow the defined template for bug reports and include your system info and maybe a link to the website, etc.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate**.
* **Isolating the problem**.
* **System info**.
* One issue per thread

Without it, we simply can't help.

BTW - If you are a Pro user - you are welcome to contact our support and they will investigate the issue. 

Thanks.
