### ISSUE TITLE
Custom user Login page in Elementor Pro Theme Builder

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#14588]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be nice to be able to customize the login page inside elementor pro just like creating 404 error pages and other pages and would be nice to be able to change login url too using elementor.

**Describe the solution you'd like**
Adding a new section inside Theme Builder to be able to customize the login page and change url if needed.

**Describe alternatives you've considered**
Other plugins but it must be added inside elementor pro!

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #5140, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
