### ISSUE TITLE
Add global settings for column gap

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#14581]
Please add global setting for column gap, default is 10 px, but for responsive need use %, To go into each column and reconfigure everything is very inconvenient, moreover, make settings like fonts for example, preset 1 and 2,3,4 for indents, why, here I am in order to do everything on the grid sometimes you need to put an indent from the right 20 pixels and from the left 10, and vice versa, for other cases, other values may also be needed, and having the ability to set this globally would lead to the fact that I can set a preset for indents just like fonts or colors. Also add the setting of the margins of widgets, by default 20 pixels, but according to different design systems it is better that it was 16 or 24 or even 32 ... there is no special desire to manually configure it.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12763, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
