### ISSUE TITLE
Scheduled activation & deactivation of sections to show depending on day or date.

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#14587]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I need to manualy activate or deactivate sections. I'm the develper of a website of a client and it's website has a page where some sections must be activated and deactivated depending of the day. (Saturday, sunday and non-work days need to show non-work menu and other days need to show the section of normal day menu, but with the other deactivated and vice versa)

**Describe the solution you'd like**
I would like to have an option to schedule activation and deactivation of blocks and sections, and pages and other things in elementor pro. Maybe a new panel for that? It would be a time saver as I won't need to enter everyday to do so.

**Describe alternatives you've considered**
Additional plugins but as I'm paying for elementor pro...

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
