### ISSUE TITLE
Change the text color of the icon list widget in Safari browser

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14580]
In some cases, the text color of the icon list widget in the **Safari browser** changes (in red). I tested on two similar sites, but for one site it was red. I do not know what the reason is. But it happens. Please check

thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
