### ISSUE TITLE
Nav Menu Responsive Align

### ISSUE THREAD

**Issue by DevGregory** [elementor/elementor#14594]
Hi all,

Are we able to make the Nav Menu Align setting responsive? At the moment, one setting controls all devices..

Seems to be an easy addition but missing.

![image](https://user-images.githubusercontent.com/72046842/115149847-d328c800-a05d-11eb-85e7-b8a0585d0c16.png)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
