### ISSUE TITLE
Sticky Setting At Column

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14596]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
Currently, elementor only can sticky which can only be set per widget.
And I want to set sticky per column, not have to be per widget anymore.
For more details, look in section one of the widgets on Elementor, you will see in the "advance" section the "sticky" settings.
Now go to the "column" section where the widget is placed, go to the "advance" section, and you don't see the "sticky" setting.
**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DorShahar** [comment]
Hi 
Thanks for reaching out. 

We recently added the option to use [sticky inner section](https://youtu.be/G7rQnqZQAqw).
Will it help you?
If no - please add more info for the use case why the sticky inner section does not help you.


Thanks

**Comment by mushlih-almubarak** [comment]
> Will it help you?
Yes, thank you
