### ISSUE TITLE
Please make pop-up elementor compatible with jet smart filter plugins.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14595]
Hello
Please make Mentor pop-up compatible with jet smart filter plugin. Filters cannot be displayed on the pop-up at this time.
It's great, because in mobile mode, the filters are displayed as sliders, but at the moment it doesn't work when I put the filters on the pop.Like this picture(https://prnt.sc/11n874e)
Please add this feature. It is very necessary.

Thank you

**Comment by DevDietheR** [comment]
+1 currently the filter only works on jetpopup

**Comment by 79ho3ein** [comment]
Hi @DevDietheR 
jet smart filters are said to add this feature.  I close this request here.
Good luck.
