### ISSUE TITLE
Elementor update white page problem.

### ISSUE THREAD

**Issue by samiulhasan94** [elementor/elementor#14601]
Notice : Undefined index: auxicon2 in /home/mphv2017/RSFranceMotors.com/wp-content/themes/phlox-pro/auxin/auxin-include/classes/class-auxin-font-icons.php on line 80

Fatal error: Uncaught Error: Call to undefined function Auxin \ Plugin \ CoreElements \ Elementor \ Elements \ Theme_Elements \ auxin_get_available_post_types_for_search () in /home/mphv2017/RSFranceMotors.com/wp-content/plugins/auxin-elements/includes/elgetswidthor/ -elements / modern-search.php: 1085 Stack trace: # 0 /home/mphv2017/RSFranceMotors.com/wp-content/plugins/auxin-elements/includes/elementor/widgets/theme-elements/modern-search.php ( 147): Auxin \ Plugin \ CoreElements \ Elementor \ Elements \ Theme_Elements \ ModernSearch-> get_post_types () # 1 /home/mphv2017/RSFranceMotors.com/wp-content/plugins/elementor/includes/base/controls-stack.php ( 1951): Auxin \ Plugin \ CoreElements \ Elementor \ Elements \ Theme_Elements \ ModernSearch -> _ register_controls () # 2 /home/mphv2017/RSFranceMotors.com/wp-content/plugins/elementor/includes/base/controls-stack.php ( 461):Elementor \ Controls_Stack-> init_controls () # 3 /home/mphv2017/RSFranceMotors.com/wp-content/plugins/elementor/includes/base/widget-base.php(154): Elementor \ Controls_Stack-> get_stack () # 4 / home / mph in/home/mphv2017/RSFranceMotors.com/wp-content/plugins/auxin-elements/includes/elementor/widgets/theme-elements/modern-search.php on line 1085

**Comment by DorShahar** [comment]
Hi 
Thanks for reaching out.
According to the notice, the problem is in the theme "phlox-pro". 
According to the Fatal error - the problem is in the "[Auxin-elements](https://wordpress.org/plugins/auxin-elements/)" plugin.

Please contact them if needed. 
Thanks
