### ISSUE TITLE
Pop Up templates missing from the new theme builder

### ISSUE THREAD

**Issue by Salimoh** [elementor/elementor#14605]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Salimoh** [comment]
Hi
I think it would be a great idea to include popups also in the new theme builder in Elementor.

**Comment by DorShahar** [comment]
Hi 
Thanks for reaching out.
The Popup is not a theme part, and therefore it is not in the theme builder.
However - a Popup is a template, and once you create one, it's automatically been saved under "My templates".

According to this logic - Popup should not appear in the Theme Builder. 

We are thinking to change it - so ALL site parts will have a visual approach as in the Theme builder, but will not happen in the near future. 


Thanks
