### ISSUE TITLE
Endless loop in HTML Element

### ISSUE THREAD

**Issue by AlexLarentis01** [elementor/elementor#14600]
Hi, 
I had the fantastic idea to insert some buggy af Java Script code in a html component. Is there any way to access the editor without JS, alter it in the File System or Database?? Otherwise im screwed.

Thanks
Alex Larentis

**Comment by shilo-ey** [comment]
Hi @AlexLarentis01 

When trying to access the editor are you facing issues with loading the editor?

If so - either try to activate elementor in [safe mode](https://elementor.com/help/what-is-safe-mode/), or access your post db record and delete the incorrect JS script from your page (in `wp_postmeta` table).

Please backup your site before editing your DB.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
Thanks
