### ISSUE TITLE
The social icons widget icon spacing

### ISSUE THREAD

**Issue by inocampo** [elementor/elementor#14616]
The widget of social icons, when we are in design, there is a space between the icons, but already in the fontend the space disappears.

![Design](https://user-images.githubusercontent.com/1313634/115341048-774d6480-a16d-11eb-8f52-14c64c673daf.png)
![Production](https://user-images.githubusercontent.com/1313634/115341052-77e5fb00-a16d-11eb-856a-7dced045c2b4.png)

Thank you.

**Comment by svrdoljak123** [comment]
This happens to me to.

**Comment by DorShahar** [comment]
Hi
Thanks for reporting. 
For the next time - please add system info so we could investigate. The best is to follow the issue report guidline. 
This is a known issue so I merging it with #13122.

Thanks

**Comment by shahjehan-wpbrigade** [comment]
I try to fix this issue here
Chrome emulator social icons space is different than on mobile view.
https://github.com/elementor/elementor/pull/12247
