### ISSUE TITLE
The slider widget will load late on the site. please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14610]
The slider widget will load late on the site. I think it has a lot to do with optimization. It is clear that it is very heavy. Please check. Thank you

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.
In case you are a Pro user - you are welcome to contact our support, and they could investigate the problem. 

Thanks.
