### ISSUE TITLE
ACF, Custom post type, Crockoblock custom fields do not work anymore

### ISSUE THREAD

**Issue by svrdoljak123** [elementor/elementor#14618]
So now this isn't funny anymore. My 1st e-mail to customer support is sent on APR 13. 7 days ago. I got an e-mail that it's with the tier 2 agent, whatever that means... Can't get anyone on the customer support chat for 2 days now!!! ACF, Crockoblock, Pods any type of custom post fields do not show up if used as a dynamic tag, the sole reason I purchased Elementor. So now I cant build my custom template like I used to do with all my websites. This worked like a charm on the older version, I have tried everything, older versions of WordPress, older versions of Elementor, themes, PHP versions...localhost, servers.... Can anyone from Elementor look into this, like urgent!!! My custom post type is made out of 3 simple fields, title, text, and image. None of them show up.....

Or please send me a refund, 5 of my sites that are built like this work, but if any change is needed in the future I'm screwd!!

![image 1](https://user-images.githubusercontent.com/26928581/115366647-ccb56000-a1c5-11eb-8274-3b984be222d2.PNG)
![foto, text and title not showingup](https://user-images.githubusercontent.com/26928581/115366668-d048e700-a1c5-11eb-9626-e258193135a2.jpg)
![Custompost with data](https://user-images.githubusercontent.com/26928581/115366682-d343d780-a1c5-11eb-8d58-65b5a38bf2f2.jpg)
![Jetengine-custom post type](https://user-images.githubusercontent.com/26928581/115366687-d4750480-a1c5-11eb-9710-0a30b086818a.jpg)
![Jetengine-custom post type](https://user-images.githubusercontent.com/26928581/115366699-d76ff500-a1c5-11eb-9465-c20ecb977a56.PNG)
![image 2](https://user-images.githubusercontent.com/26928581/115366606-c3c48e80-a1c5-11eb-964b-856603ab1e3d.PNG)

**Comment by shilo-ey** [comment]
Hey @svrdoljak123 

Sorry to hear that you encounter this experience.

We'll try to speed things up, because your issue requires a manual inspection of your site.

Please contact our support at support @elementor.com for guidance in resolving this issue **and mention that you were directed by me (shilo-ey) and reference this issue**.

Thanks.
