### ISSUE TITLE
Add some social media in sharing widget

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14629]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
I am using the "share button" widget in elementor pro and I will have the following social share buttons:
1. Facebook Messenger
2. Lines
Because for now there is no that social media share on the "share button" widget

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12395, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
