### ISSUE TITLE
Website Loads But Editor Gives Blank Screen: ​ Uncaught TypeError: Cannot read property 'scrollHeight' of null

### ISSUE THREAD

**Issue by sebastianvdn** [elementor/elementor#14638]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

For the landing page of a course I am building on thinkific.com I copied some code to paste on my website:

```
<div class="thinkific-product-card" data-btn-txt="Buy Now" data-btn-txt-color="#ffffff" data-btn-bg-color="#1b9eea" data-card-type="button" data-link-type="checkout" data-product="1392589" data-embed-version="0.0.2" data-store-url="https://thebgang.thinkific.com/embeds/products/show"><div class="iframe-container"></div><script type="text/javascript">document.getElementById("thinkific-product-embed") || document.write('<script id="thinkific-product-embed" type="text/javascript" src="https://assets.thinkific.com/js/embeds/product-cards-client.min.js"><\/script>');</script><noscript><a href="https://thebgang.thinkific.com/enroll/1392589?et=free" target="_blank">Buy Now</a></noscript></div>
```
This code caused the issue that I can't edit anymore. This is a bug as just before that I could do edit just fine. Please help.
## Steps to reproduce
Just go to a page and edit with elementor, add a html widget and copy and paste the code I just showed.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
Wordpress 5.7 and latest version of Elementor
</details>

**Comment by Aviad-Herman** [comment]
Open the Navigator, find the problematic HTML widget, right click on it and delete.
Make sure to save and refresh the page.
Your page is now editable again.

Debug your code and try again if you want.

![image](https://user-images.githubusercontent.com/73067562/115707696-f4bad580-a323-11eb-9e2d-fc85c371e3b0.png)
