### ISSUE TITLE
Add sorting for Global Colors (now it's just random)

### ISSUE THREAD

**Issue by Sitecentrale** [elementor/elementor#14643]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When your add Global Colors you cannot sort them in the Global Colors panel. At first I thought it was annoying, especially when you add a lot of colors, because when I added 20 colors and saw I missed a color, I had to go in and copy/paste all colors to one spot below. But when I finished doing that and saved them, went to a page and tried to select a custom color, I saw that the order of Global Colors that is inside the Global Colors setting panel, is not the same as inside the color pickers, so me ordering the colors (the hard way, like described above) was all for nothing :(

**Describe the solution you'd like**
1. I would like to have the Global Colors made SORTABLE inside the Global Colors panel
2. I would like to have that SORT ORDER inside all color pickers when you try to select a global color

Thanks for a great editor and lets try to make it even more awesome  👍

**Comment by d19dotca** [comment]
Yes, this would be great. I remember suggesting this while testing the 3.0 beta "back in the day", but it was not implemented at that time.

**Comment by Aviad-Herman** [comment]
Hi guys,
Great request.
I'm merging this with #12203
