### ISSUE TITLE
post Excerp is not working from long...

### ISSUE THREAD

**Issue by mdmoinahmed** [elementor/elementor#14648]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x
![issue](https://user-images.githubusercontent.com/71731342/115632825-626a0000-a32a-11eb-81fe-5a6b391560cc.png)
] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi
It might be that the section height is limited, and therefore it's cut-off. 
Without Steps to reproduce and system info, we can't help and investigate if this is a bug. 

You can ask in the Facebook community for further help, or, if you are a pro user - contact our support. 

Thanks.
