### ISSUE TITLE
Request two features for slider widgets and icon list.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14666]
Hello
1-Please add a border-radius feature to the slider widget.

2-please Add the ability to move the icon to the right of the text to the icon list widget
These two are small, but very practical.

Thanks🙏🏻

**Comment by 79ho3ein** [comment]
hi @avivu
Sorry, I have a question...
How long does it take for such small requests to be added to the plugin?

**Comment by rami-elementor** [comment]
Hi @79ho3ein 

1. The "Slides Widget" has a border-radius control under the "Button" section. In addition, you can use the advanced tab, open the "Border" section to set a border-radius.

2. The "Icon List Widget", as answered in the other GitHub issue, lists start with an icon, then don't end with one. This feature won't be changed.

Finally, how long does it take for such small requests to be added to the plugin? well, we have over 10 million customers, each wants to add some features and fix some bugs. It takes time to prioritize those tasks and assign developers.

Thank you for all your feedback, I see you opened 272 issues. Hopefully some of them will be prioritized and fixed.
