### ISSUE TITLE
frontend.min.js - Uncaught (in promise) TypeError: c is undefined

### ISSUE THREAD

**Issue by karinwerner** [elementor/elementor#14667]
THIS IS NEW.

Uncaught (in promise) TypeError: c is undefined
createSwiperInstance /wp-content/plugins/elementor/assets/js/frontend.min.js:2
SwiperBC /wp-content/plugins/elementor/assets/js/frontend.min.js:2

frontend.min.js
Line 2 at 47248

**Comment by fleks** [comment]
Try to deactivate Improved Asset Loading in Elementor > Settings > Experiments

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites.**
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
