### ISSUE TITLE
Elementor issue

### ISSUE THREAD

**Issue by webriplex** [elementor/elementor#14661]
Deprecated: Elementor\Scheme_Color is deprecated since version 2.8.0! Use Elementor\Core\Schemes\Color instead. in /home1/webriplex/public_html/wp-includes/functions.php on line 5051

**Comment by alexcumbers** [comment]
You need to be MUCH clearer starting with an effective title of the issue and full details of when / how it happens, does it occur all the time etc

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites**.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
