### ISSUE TITLE
Responsive Mode (in 3.2) - Default to Desktop view and order Desktop > Tablet > Mobile view

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#14662]
## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## What problem is your feature request going to solve? Please describe.
The new Responsive Mode introduced in version 3.2.0 / 3.2.1 currently behaves in a way where when it's used, it automatically switches from Desktop to Mobile straight away while also putting Mobile on the left side (basically outright replacing the previous behaviour). This is a jarring change and does not match how designers work especially given how Elementor is designed. This is a step backwards from how it was prior to 3.2.0.

Elementor is currently designed in a way where mobile breakpoints inherit values from tablet breakpoints which in-turn inherits from desktop view. Thus, designers tend to work on a large -> small methodology. In other words, Desktop first, then Tablet, then Mobile. So why did the Responsive Mode change to Mobile first then Tablet then Desktop?  

The current updates to the Responsive Mode are well intentioned but miss the mark for how users actually appear to work within Elementor.

## Describe the solution you'd like
As was [described many times in the 3.2.0 beta process](https://github.com/elementor/elementor/issues/14313), many of us would like to see this changed in the following ways:

1) Swap the Desktop & Mobile icons so that Desktop is on the furtherest left side, then Tablet in the middle as always, then Mobile on the furthest right side. That way it'd seem more intuitive as most people move their eyes left to right and since the mobile settings inherit from the desktop and tablet settings above it, it seems natural to keep Desktop at left, Tablet in middle, and Mobile at right.

2) Default to Desktop mode when a user enters Responsive mode so as not to drastically change the immediate view, then a user can choose which mode they want to go to next (i.e. Tablet or Mobile) rather than Mobile being forced. Again, since Mobile inherits values from Tablet which in-turn inherits from Desktop, it doesn't make sense to go straight to Mobile.
 
## Describe alternatives you've considered
There don't appear to be any alternatives.

## Additional context
These improvements were presented by numerous beta testers such as myself in the [in the 3.2.0 beta process](https://github.com/elementor/elementor/issues/14313) but was never really addressed in a satisfactory way. In fact, as beta testers we felt a bit ignored here as there was a real lack of communication. I hope to see these improvements in the next version / ASAP, as many of us felt the current workflow is now "broken" due to it being a step backwards to our design process and workflows.

**Comment by DavidGMiles** [comment]
I fully support this request - this is how it needs to be to work best

**Comment by black-eye** [comment]
+1
As stated here and in the beta thread by many. Unfortunately all the feedback ended up on usual "we will iterate on this and consider ..." phrase.

**Comment by fleks** [comment]
The vast majority of the active Beta Tester told the developer to change it in this thread https://github.com/elementor/elementor/issues/14313 - but it's pity they didn't listen.
And nobody asked for a minimum mobile width of 320px - 360px was advised instead of the 375px of the beta version.

**Comment by jazir5** [comment]
+1

**Comment by DorShahar** [comment]
Hi everyone.
We are fully aware of this request, and we are working on an option s.t the user will be able to determine the desired behavior of the responsive bar, in terms of which device will be open up first in the responsive view.  

Thanks.

**Comment by KingGrizzly** [comment]
Haven't seen this yet, but all of our current sites are built with the understanding the styling flows down from desktop. Reversing this flow would break all of our site styling.

**Comment by d19dotca** [comment]
> Haven't seen this yet, but all of our current sites are built with the understanding the styling flows down from desktop. Reversing this flow would break all of our site styling.

To be clear, the actual value inheritance flow stays the same (mobile inherits from tablet which inherits from desktop) so nothing should break functionally, and that's precisely why the visual change to responsive mode jumping straight to mobile from desktop makes no sense to any of us who brought this up during the beta testing phase. It should behave in the same way as the values are inherited since that's what logically makes sense to designers. In other words... Desktop, then Tablet, then Mobile, and not the other way around. 

Not sure who at Elementor thought that swapping them was a good idea. Only possible reason I could think of is if Elementor is planning changes to implement a "mobile first" design approach in the immediate future where the flows would be reversed, though I don't expect that is happening. Hopefully Elementor changes this in the very next version. Doing so will show that they are actively listening and prioritizing our feedback, especially when this feedback was presented to them (overwhelmingly) during the beta testing phase where we're all volunteering our time to help Elementor's team.

**Comment by DavidGMiles** [comment]
Nicholas - one of the mods in the FaceBook group has already pointed out that his first inclination was to change settings for mobile, he then went and duplicated them for tablet - because inheritance works desktop > tablet > mobile - he then realised what was happening - he was doubling up on CSS unnecessarily - in these days of removing unused and duplicated CSS, we now have a scenario in which users will unwittingly add unused and duplicate CSS

**Comment by d19dotca** [comment]
I just noticed one more reason today why this needs to be fixed (or at least another area that needs fixing)... there is an inconsistency in behaviour when activating Responsive Mode. 

When clicking the Responsive Mode button, it jumps straight to Mobile view. However when using the keyboard combination of Shift + Command (apple) + M for the Responsive Mode shortcut, it jumps instead to the Tablet view rather than Mobile. Yet another reason for this to be fixed.

I guess for now we can use the keyboard shortcut to activate Responsive Mode as a workaround to get the "old" behaviour (that should never have been changed to begin with).

**Comment by fabianenzensperger** [comment]
+1000

**Comment by fabianenzensperger** [comment]
Maybe the developers (@shilo-ey) listen to their famous designer and programmer (Zoë) more than us:

https://www.facebook.com/groups/Elementors/permalink/3700245910101168/

**Comment by perks98** [comment]
I have to use Elementor for most of my workday and it really feels clunky with more steps. Please update soon. They need to review their UX/UI understanding, we need fewer clicks to achieve our goal, not more. My thoughts: reverse the icons so the desktop is first with mobile last and when you click on the responsive button just bring down the bar and not change to mobile like this thread author mentioned.

**Comment by perks98** [comment]
Also does anyone have a problem with this, or is it just me?
https://user-images.githubusercontent.com/55829113/116692161-d86a0900-a9b3-11eb-81b7-e7d04c54e976.mp4

You enable the responsive bar but when using the responsive control on the widget itself the responsive bar goes away for desktop view, even when toggled on. Could just be me being picky.

**Comment by DavidGMiles** [comment]
> Also does anyone have a problem with this, or is it just me?
> https://user-images.githubusercontent.com/55829113/116692161-d86a0900-a9b3-11eb-81b7-e7d04c54e976.mp4
> 
> You enable the responsive bar but when using the responsive control on the widget itself the responsive bar goes away for desktop view, even when toggled on. Could just be me being picky.

Yes - this shows how inconsistent the whole approach is - it has been badly thought out and badly implemented - almost as though they had no planning and no feedback!

**Comment by fleks** [comment]
So, here is the Facebook discussion about the new Responsive UI - it's not only a nerdy GitHub issue 😉https://www.facebook.com/groups/Elementors/permalink/3700245910101168/

**Comment by DavidGMiles** [comment]
I've asked Verdi on the FB discussion, if now it has a load of public feeling as well, whether they will take feedback on-board - let's see what happens - I suspect I will be slapped down or ignored.

**Comment by DorShahar** [comment]
Hi Everyone,
I'm glad to say that we implemented your request! 
At the moment the change in QA, and will be available in the next core major version. 


Thanks

**Comment by perks98** [comment]
@DorShahar Thanks for the update, much appreciated. Can you please confirm the exact changes that will be acted on, for example what is the new default action when you click on the responsive mode button?

**Comment by DorShahar** [comment]
Hi @perks98 ,
You as a user be able to select the device which will open up once you clicked on the responsive mode button.

**Comment by black-eye** [comment]
@shilo-ey 

OK, so now, when the additional breakpoints are out as an experiment and we can see the whole picture, would you mind to explain us the reason, why the breakpoints in the responsive bar are in the opposite direction to what they are in the other controls and to what the every day workflow is?

![obrazek](https://user-images.githubusercontent.com/5634870/123639837-dc35d280-d820-11eb-8d9c-a4759e96459a.png)

The current workflow is desktop first - we start on desktop and move one by one to lower breakpoints. The lower breakpoint inherits the value from the higher breakpoint.

New responsive bar forces us to start on mobile and move upwards - it absolutely doesn't make any sense. We were told, everything will make sense after additional breakpoits are out. Now they are out, but I still don't get it. Please, explain it to us.

**Comment by DavidGMiles** [comment]
I agree on this point - it doesn't make a whole lot of sense - the first thing I have to do when switching to responsive mode is to switch away from mobile

**Comment by shilo-ey** [comment]
This feature has been added to Elementor v3.3.0 (select the initial device per user)

Now (after a quick adoption time) we can update the behavior as you mentioned @black-eye. will be added in the upcoming releases.

Keeping this thread open for now. 

Feel free to update

Thanks!

**Comment by perks98** [comment]
@shilo-ey can't we have it back to how it was and have tablet view be the next view when you click the responsive button or is it hardcoded at the moment in the new layout? As this thread has also mentioned it currently goes from desktop to mobile than tablet when the inherital value doesn't work like that it should be desktop > tablet > mobile. Rather than on a user basis changing your default behaviour from mobile to tablet, why not tablet by default then let the others change it to mobile or remove the behaviour when clicking the responsive button so when clicked it just brings the bar down on desktop view then you click where you want to go next?

Any changes are appreciated but it feels like with this issue the team broke something that didn't need fixing and now adding more ways around it to deal with it. @shilo-ey would you or your team be able to express to us why the responsive workflow changed in the first place?

PS: don't take this negatively still love Elementor 😉

**Comment by shilo-ey** [comment]
> @shilo-ey can't we have it back to how it was and have tablet view be the next view when you click the responsive button or is it hardcoded at the moment in the new layout? As this thread has also mentioned it currently goes from desktop to mobile than tablet when the inherital value doesn't work like that it should be desktop > tablet > mobile. Rather than on a user basis changing your default behaviour from mobile to tablet, why not tablet by default then let the others change it to mobile or remove the behaviour when clicking the responsive button so when clicked it just brings the bar down on desktop view then you click where you want to go next?
> 
> Any changes are appreciated but it feels like with this issue the team fixed something that didn't need fixing and now adding more ways around it to deal with it. @shilo-ey would you or your team be able to express to us why the responsive workflow changed in the first place?
> 
> PS: don't take this negatively still love Elementor 😉

Thanks, based on your feedback we want to make it work as expected:
Initial device: Desktop
From left to right: D, T, M
If more devices are added they will be placed in the correct order: Wide screen, D, Laptop, Tablet, Mobile (for example)

Sounds fine?

**Comment by perks98** [comment]
> > @shilo-ey can't we have it back to how it was and have tablet view be the next view when you click the responsive button or is it hardcoded at the moment in the new layout? As this thread has also mentioned it currently goes from desktop to mobile than tablet when the inherital value doesn't work like that it should be desktop > tablet > mobile. Rather than on a user basis changing your default behaviour from mobile to tablet, why not tablet by default then let the others change it to mobile or remove the behaviour when clicking the responsive button so when clicked it just brings the bar down on desktop view then you click where you want to go next?
> > Any changes are appreciated but it feels like with this issue the team fixed something that didn't need fixing and now adding more ways around it to deal with it. @shilo-ey would you or your team be able to express to us why the responsive workflow changed in the first place?
> > PS: don't take this negatively still love Elementor 😉
> 
> Thanks, based on your feedback we want to make it work as expected:
> Initial device: Desktop
> From left to right: D, T, M
> If more devices are added they will be placed in the correct order: Wide screen, D, Laptop, Tablet, Mobile (for example)
> 
> Sounds fine?

Yeah that sounds fine 👍. I have to use Elementor daily for work and going from desktop to mobile back to tablet then mobile just takes a few more clicks at the moment and eager to have a smoother flow 😉. Currently manage a lot of sites so I can't keep going into user preferences and change from default (mobile currently) to tablet on all sites.


like @DavidGMiles comment:

> I agree on this point - it doesn't make a whole lot of sense - the first thing I have to do when switching to responsive mode is to switch away from mobile

But I'll look forward of what gets released next for it as the plugin adapts with the custom breakpoints coming next 👍

**Comment by KingGrizzly** [comment]
Possibly related with the introduction of these new breakpoint sizes @shilo-ey, many of our sites tap into the Elementor CSS convention for breakpoints in order to do custom styling:

body[data-elementor-device-mode="mobile"] 
body[data-elementor-device-mode="tablet"] 
body[data-elementor-device-mode="desktop"] 

Will these be maintained and possibly new ones available (eg: body[data-elementor-device-mode="tablet-landscape"])?

I'm worried these will deprecate and break many of our sites styles.

Thanks for any info and great work!

**Comment by udidol** [comment]
Hi @KingGrizzly,
These responsive dynamic attributes on the `body` tag **will remain**.

When the "Additional Custom Breakpoints" experiment is **inactive**, everything should behave exactly the same as before.
When the "Additional Custom Breakpoints" experiment is **active**, whenever you add a new breakpoint, the device mode values will change according to the currently active devices. 

For example, if you add a 'laptop' breakpoint, the `data-elementor-device-mode` attribute on the `body` tag will get a value of `laptop` in the appropriate width range. By default, if the only additional custom breakpoint added is 'Laptop', then that range would be between the max width value for tablet+1px and the max width value for laptop, which is `1366px` by default).

**Comment by KingGrizzly** [comment]
Thank you @udidol ,
This is great to see, and extremely useful for targeted styling. I appreciate the detailed explanation. This is a relief because we've been utilizing this styling approach for some time.

**Comment by black-eye** [comment]
@shilo-ey, @udidol, @DorShahar  - maybe I am missing something, but I still see the "wrong" device order in the topbar - mobile, tablet, desktop. As mentioned by many here, it should be desktop, tablet, mobile (from left to right), because it should follow the workflow.

What am I doing wrong? I'm on 3.4.0-dev13.

**Comment by DavidGMiles** [comment]
I am on beta 1 - not the dev edition - I see the right order - and it feels so right!

**Comment by black-eye** [comment]
> 
> I am on beta 1 - not the dev edition - I see the right order - and it feels so right!

Hmm, that's strange, I would expect the latest dev version would "include" the latest beta, not to stay behind. 
OK, I'll try the beta later on another staging site, since it's quite complicated to get back from dev edition to beta.

**Comment by shilo-ey** [comment]
This tweak has been implemented in Elementor v3.4.0

Feel free to update

Thanks!
