### ISSUE TITLE
add the Height equal to the screen option for mobile and tablet.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14670]
Please add the Height equal to the screen option for mobile and tablet. This feature is currently only available for the desktop.
thanks.

**Comment by avivu** [comment]
hello @79ho3ein,
Can you please add more details for your suggestion?

**Comment by 79ho3ein** [comment]
Each section made with elementor has height settings, such as custom or equal to the height of the screen.
If you set the height on the screen measurement, this only applies to the desktop and tablet. Mobile phones do not have this possibility.

**Comment by 79ho3ein** [comment]
hello @avivu I apologize for the delay.
I will close this request and describe it in the new issue. Thanks
