### ISSUE TITLE
Request to display message notification from elementor form in WordPress counter.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14683]
Hello good time.
Please add an attribute to elementor, as long as the form is submitted by the user, displayed as a notification in the WordPress counter.
This feature is required for the elementor submission form.

thanks.

**Comment by DorShahar** [comment]
Hi 
Thanks for reaching out. 
Not long ago we released the[ Form Submissions](https://elementor.com/help/form-submissions/) feature (in the Pro version) - which answers your request.

Thanks
