### ISSUE TITLE
add CSS Grid support or fix colum size in % 

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#14680]
Hello, please add CSS grid support, or fix the trouble with column size in PC versions like in tablet or mobile version. What do I mean? If I want to add a section with 4 columns I need to separate space for the first column 50%, second 50%, third 100%, and last 100%. With Elementor and Elementor pro I can't do this, if I instal addons for example - OoohBoi Steroids for Elementor, I can set column size how I want, and order column for devices, for example, the last column on the mobile version make second or third or firs, is not simple revers columns.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #452, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/18839

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the first beta implementation of the Grid Container is live! 🙌 

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪 

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment]
Hello, @promocot!

We have great news! 🙌 

### 📢 We're happy to announce that the first phase of the Grid Container was released with Elementor **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
