### ISSUE TITLE
Display the built-in section, in the tab widget and accordion.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14688]
As you can see in the image opposite, the template widget is able to display the section created in the elementor theme builder.
https://prnt.sc/120xdqw
If you still do not understand what I mean, please see this link. This is exactly what I suggested. : https://www.youtube.com/watch?v=0k9ak2fh4Uo
If you add this feature to tab and accordion widgets, this would be great.elementor really needs it.

thanks

**Comment by shilo-ey** [comment]
Hey, thanks for your suggestion.

Currently you can use the template shortcode.

We are working on a more holistic solution for this.

Follow this thread for more information: #2587

**Comment by 79ho3ein** [comment]
Yes, that's exactly what I mean.  When will this feature be added?Sent from my Galaxy
-------- Original message --------From: shilo-ey ***@***.***> Date: 25/04/2021  13:43  (GMT+03:30) To: elementor/elementor ***@***.***> Cc: 79ho3ein ***@***.***>, Author ***@***.***> Subject: Re: [elementor/elementor] Display the built-in section, in the tab widget and accordion. (#14688) 
Hey, thanks for your suggestion.
Currently you can use the template shortcode.
We are working on a more holistic solution for this.
Follow this thread for more information: #2587

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Accordion widget was released with Elementor v3.15.0! 🥳 

With this release, we finally conclude this Feature Request! 🎉

Thank you very much for all the feedback shared here, and for helping shape the future of Elementor! 🙏 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
