### ISSUE TITLE
Add section display feature in tab widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14682]
Please add the section display feature to the tab elmentor widget. Like the jet tabs plugin

**Comment by fleks** [comment]
Please describe more accurate.

**Comment by 79ho3ein** [comment]
If you've worked with the jet tabs plugin, its tab widget is able to display the part we create in the elementor template.
just like this elementor widget, which does the same thing. : https://prnt.sc/11z8ecc
https://prnt.sc/11z8cd3
Of course, this widget can also have this feature : https://prnt.sc/11z8xay

This feature is really needed for elementor. Please add this feature if possible.

Thank you for your attention

**Comment by fleks** [comment]
The only "JetTabs" plugin is paid and I won't buy it. Your screenshots don't help.
So you have to describe and provide more.

**Comment by DorShahar** [comment]
@79ho3ein , Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* **Prerequisites**.
* **Description and examples**.
* One request per thread

As @fleks mentioned, your description is unclear to us, and we cannot understand your need. Please follow the guidelines.

Thanks.
