### ISSUE TITLE
Custom breakpoints

### ISSUE THREAD

**Issue by sinashamsizadeh** [elementor/elementor#14685]
Hi,
I added my custom breakpoints and responsive sizes to elementor, and it works properly, After Release version 3.2.0 I realized it doesn't work and I can not add my custom breakpoints and responsive sizes again, Is there any solution for it? how can I add my custom breakpoints and responsive sizes in version 3.2.0

**Comment by shilo-ey** [comment]
If you are using a 3rd party addon - please contact them for instructions.

This capability of adding additional breakpoints is not yet developed in Elementor. we are working on this and you can follow the progress in #2043 

Thanks
