### ISSUE TITLE
Request to add a loading page to elementor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14691]
hello
Hi, does elementor have a plan to add a loading page to mentor? : https://prnt.sc/1213fry
This feature is much needed. elementor really lacks this.

Thanks to the elementor team.

**Comment by DorShahar** [comment]
Hi @79ho3ein 
We do, and we are planning this feature as we speak.
I'm closing this issue and merging it with #10555 since this is the same request.

Thanks
