### ISSUE TITLE
Ability to move the icon to the right, in the icon list widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14700]
Hello
Please allow the icon list widget to move its icon to the right of the text. This widget does not have this item.

thanks

**Comment by d19dotca** [comment]
If it's a list though, shouldn't the icon always be on the left? Much like writing a list in an email with bullet points or a numbered list... there's no option to change the location of those numbers or bullet icons, they are always on the left side of the text for a LTR language.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #14554, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
