### ISSUE TITLE
Elementor Nav Menu widget - Mobile Dropdown - Tablet Breakpoint is not working Elementor 3.2.x

### ISSUE THREAD

**Issue by chemocool** [elementor/elementor#14711]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Nav Menu Mobile Dropdown Tablet Breakpoint is not working starting at version 3.2.0.

Rolling back to 3.1.4 fixes the issue (after regenerating CSS).

## Steps to reproduce

1. Start with a blank instance of Wordpress. Install Elementor 3.1.4 (or 3.2.2 and rollback to 3.1.4) and Elementor Pro 3.2.1.
2. Add a Nav Menu Widget (to a elementor header template) with a few items in it. Set it's Mobile Dropdown to Tablet, so the mobile menu appear when we reach the tablet breakpoint.
3. Test the NavMenu in Tablet, it works.
4. Upgrade Elementor 3.1.4 to latest (3.2.2).
5. Regenerate CSS
6. Reload the Elementor editor with the Nav Menu, put it in Tablet size. Menu stay as in desktop instead of hiding and showing the mobile menu icon. It's also broken if you test the site itself.

![image](https://user-images.githubusercontent.com/29230607/116097749-6c686780-a678-11eb-9b6d-0b769137a56b.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.1
	MySQL version: mariadb.org binary distribution v10.4.17
	PHP Version: 8.0.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: http://localhost/wordpress
	Home URL: http://localhost/wordpress
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.2.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	Elementor Pro: incompatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	header : 1
		nav-menu : 1
	wp-page : 1
		text-editor : 1

== Log ==
	
Log: showing 2 of 22021-04-26 13:13:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-04-26 13:20:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.1',
)]

**Comment by Arudd101** [comment]
I am also facing the exact same issue. 
The problem shows on both the editor and live version of the website. 

Not sure if this is because we have set a custom breakpoint for tablet the only way to fix it is to rollback to 3.1.4

**Comment by chemocool** [comment]
It seems that if we pick either Mobile Breakpoint or Tablet Breakpoint, it behaves as Mobile Breakpoint. 

While selecting "None" behave as expected.

**Comment by kromeninja** [comment]
Having issues with the sections not resizing correctly since the last few updates

**Comment by taylorbenefitz** [comment]
I am also encountering this issue!

I also have a custom breakpoint set for mobile (<1176px)

**Comment by brunolimawd** [comment]
I have the same problem when I upgrade to 3.2.x

**Comment by StuartPBW** [comment]
I have the same problem when upgrading Elementor from 3.1.4 to 3.2.2. I'm also using Elementor Pro version 3.1.0 

Please fix this!

**Comment by phil-beachler-id** [comment]
Confirmed on Elementor 3.2.2 and Elementor Pro 3.2.1. Tried multiple settings for layout width and breakpoints to try and resolve to no avail.

**Comment by chemocool** [comment]
Any Elementor dev can check this issue ?

This needs to be fixed, it's a bug introduced by Elementor 3.2.0.

**Comment by DorShahar** [comment]
Hi
Thanks for reporting.

**Comment by Morris0ne** [comment]
I, too, found this issue just yesterday, I have a custom tablet breakpoint.
I tried to better understand and to fix the bug using backup restores, without success. Unsure if it is useful, but I found that after updating to 3.2.2 the breakpoint for tablet went down one pixel, if I recall correctly. Changing it back of course did not work. Hope it is fixed soon!

**Comment by chemocool** [comment]
> I, too, found this issue just yesterday, I have a custom tablet breakpoint.
> I tried to better understand and to fix the bug using backup restores, without success. Unsure if it is useful, but I found that after updating to 3.2.2 the breakpoint for tablet went down one pixel, if I recall correctly. Changing it back of course did not work. Hope it is fixed soon!

You have to rollback to 3.1.4 to fix the problem (and regenerate css). The problem is present with 3.2.0, 3.2.1 & 3.2.2.

**Comment by Morris0ne** [comment]
> > I, too, found this issue just yesterday, I have a custom tablet breakpoint.
> > I tried to better understand and to fix the bug using backup restores, without success. Unsure if it is useful, but I found that after updating to 3.2.2 the breakpoint for tablet went down one pixel, if I recall correctly. Changing it back of course did not work. Hope it is fixed soon!
> 
> You have to rollback to 3.1.4 to fix the problem (and regenerate css). The problem is present with 3.2.0, 3.2.1 & 3.2.2.

Thank you, I actually did before replying to this thread, and now it works. 
However, at least with my website, rolling back did not immediately work, even after regenerating CSS and fully cleaning my cache. In the end I had to fully restore a previous backup. I guess the "database upgrade process" (I can't really recall the name, the process Elementor shows at the top of the screen after upgrading to 3.2.x) messed things up.

**Comment by DorShahar** [comment]
Hi, 
We fixed the bug and we will release the fix soon. 

Thanks

**Comment by chemocool** [comment]
Thanks for the quick reaction/fix !

**Comment by StuartPBW** [comment]
Thank you, Elementor team!

**Comment by Morris0ne** [comment]
Just updated to 3.2.3, it works as intended on my website. Thank you!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.2.3

Feel free to update

Thanks!

**Comment by jrevillini** [comment]
There is still a related problem where the tablet may see the horizontal menu but the dropdowns don't work when the tablet is horizontal.

Conditions:
- nav menu has drop-downs
- SITE tablet breakpoint is set to <1023px (custom, originally 1024px)
- iPad tablet (768x1024) is rotated horizontally -> (1024x768)
- elementor nav menu breakpoint is set to Tablet

Expected: 
- tablet in portrait should have the hamburger menu
- tablet rotated to landscape should have the regular nav menu as long as it's above 1023px

Result: With tablet rotated to landscape (1024px wide), you can see the horizontal menu as expected, but dropdowns and menu click triggers are not applied, so only top-level menu items work.

Should I file a new bug?
