### ISSUE TITLE
Eicons not found in dev tools

### ISSUE THREAD

**Issue by Rushdiey** [elementor/elementor#14718]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
After update to 3.2.1 , my website has been detected eicons not found. I try also update 3.2.2 by today but this issue still not fix.
The fonts injected 
in here wp-content/uploads/elementor/css/custom-frontend.min.css
instead here  wp-content/plugins/elementor/assets/css/frontend.min.css

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.
To fix this problem i need to downgrade my Elementor to 3.1.4
## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by pako69** [comment]
Hi, 
Same issue
Please fixe it
Thanks

**Comment by sujukiaren** [comment]
I also found Eicons errors in my console, even today I also upgrade elementor to 3.2.2 but nothing happens.
This is my humble request to elementor technical team to please resolve this issue.

**Comment by Rushdiey** [comment]
I try to use this method for one of my site.
I upgrade to 3.2.2 error still occur. then downgrade to 3.1.4
error still occur,  the i regenerate css. no error
then update to 3.2.2 i works.

But i try to another site. upgrade 3.2.2 then downgrade 3.1.4 but no error
regenerate css no error then upgrade 3.2.2 still error.

So this solution not working for all site

**Comment by shilo-ey** [comment]
Thank you for reporting.

We will examine the issue and update here with an update.

Does it happens when you Deactivate / Activate the Improved Asset Load experiment?

**Comment by Rushdiey** [comment]
I try that method. Still not solve the problem

**Comment by pako69** [comment]
This issue is easy to solve and to understand :)

In /wp-content/uploads/elementor/css there is a generated file named: custom-frontend.min.css 

But in this file there is some CSS that shouldn't be here, there should be in: /wp-content/plugins/elementor/assets/css/frontend.min.css

This:

```
@font-face{
    font-family:eicons;
    src:url(../lib/eicons/fonts/eicons.eot?5.10.0);
    src:url(../lib/eicons/fonts/eicons.eot?5.10.0#iefix) format("embedded-opentype"),url(../lib/eicons/fonts/eicons.woff2?5.10.0) format("woff2"),url(../lib/eicons/fonts/eicons.woff?5.10.0) format("woff"),url(../lib/eicons/fonts/eicons.ttf?5.10.0) format("truetype"),url(../lib/eicons/fonts/eicons.svg?5.10.0#eicon) format("svg");
    font-weight:400;
    font-style:normal
}

```

And I'm pretty sure that this below shouldn't be here as well:

`[class*=" eicon-"],[class^=eicon]{
    display:inline-block;
    font-family:eicons;
    font-size:inherit;
    font-weight:400;
    font-style:normal;
    font-variant:normal;
    line-height:1;
    text-rendering:auto;
    -webkit-font-smoothing:antialiased;
    -moz-osx-font-smoothing:grayscale
}
@-webkit-keyframes eicon-spin{
    0%{
        -webkit-transform:rotate(0deg);
        transform:rotate(0deg)
    }
    to{
        -webkit-transform:rotate(359deg);
        transform:rotate(359deg)
    }
}
@keyframes eicon-spin{
    0%{
        -webkit-transform:rotate(0deg);
        transform:rotate(0deg)
    }
    to{
        -webkit-transform:rotate(359deg);
        transform:rotate(359deg)
    }
}
.eicon-animation-spin{
    -webkit-animation:eicon-spin 2s linear infinite;
    animation:eicon-spin 2s linear infinite
}
.eicon-loading:before{
    content:"\e8fb"
}
.eicon-menu-bar:before{
    content:"\e816"
}
.eicon-chevron-right:before{
    content:"\e87d"
}
.eicon-chevron-left:before{
    content:"\e87e"
}
.eicon-close:before{
    content:"\e87f"
}
.eicon-share-arrow:before{
    content:"\e96c"
}
.eicon-zoom-in:before{
    content:"\e882"
}
.eicon-zoom-in-bold:before{
    content:"\e92e"
}
.eicon-zoom-out-bold:before{
    content:"\e943"
}
.eicon-frame-expand:before{
    content:"\e95c"
}
.eicon-frame-minimize:before{
    content:"\e95d"
}
.eicon-play:before{
    content:"\e89d"
}
.eicon-facebook:before{
    content:"\e959"
}
.eicon-twitter:before{
    content:"\e95a"
}
.eicon-pinterest:before{
    content:"\e95b"
}
.eicon-download-bold:before{
    content:"\e96b"
}`

**Comment by StuartPBW** [comment]
Also having this problem. Please fix this!

**Comment by warudin** [comment]
The path to the Eicons font in /wp-content/uploads/elementor/css/custom-frontend.css is wrong. 

Very annoying, solved it temporarily by changing:

```
@font-face {
  font-family: 'eicons';
  src: url("../lib/eicons/fonts/eicons.eot?5.10.0");
  src: url("../lib/eicons/fonts/eicons.eot?5.10.0#iefix") format("embedded-opentype"), url("../lib/eicons/fonts/eicons.woff2?5.10.0") format("woff2"), url("../lib/eicons/fonts/eicons.woff?5.10.0") format("woff"), url("../lib/eicons/fonts/eicons.ttf?5.10.0") format("truetype"), url("../lib/eicons/fonts/eicons.svg?5.10.0#eicon") format("svg");
  font-weight: normal;
  font-style: normal; }
```

to:

```
@font-face {
  font-family: 'eicons';
  src: url("../../../plugins/elementor/assets/lib/eicons/fonts/eicons.eot?5.10.0");
  src: url("../../../plugins/elementor/assets/lib/eicons/fonts/eicons.eot?5.10.0#iefix") format("embedded-opentype"), url("../../../plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0") format("woff2"), url("../../../plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.10.0") format("woff"), url("../../../plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.10.0") format("truetype"), url("../../../plugins/elementor/assets/lib/eicons/fonts/eicons.svg?5.10.0#eicon") format("svg");
  font-weight: normal;
  font-style: normal; }
```

Of course this won't hold after an update. So that update had better contain a fix for this.

**Comment by mcrowell** [comment]
+1

**Comment by EquilibriumTechx** [comment]
Same issue here

**Comment by Rushdiey** [comment]
Waiting for this issue to fix asap.

**Comment by Rushdiey** [comment]
This bug has been fixed with update 3.2.3.
Thanks dev team

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.2.3

Feel free to update

Thanks!

**Comment by elviajemehizoami** [comment]
I Update elementor to v3.2.3 but i continue with this problem. 

Any idea?

Thanks

**Comment by Jessiemexx** [comment]
The same issue....driving me crazy!

**Comment by zeinabrika** [comment]
I don't have a custom-frontend.min.css in this dir /wp-content/uploads/elementor/css/.
Also Eicons 404 error, I use this version 3.6.4. 
Any idea why this happened?
Thanks

**Comment by migraniaboy** [comment]
> 

same issue here... v3.6.6,

**Comment by Ljuk67** [comment]
For me, it was because of this Elementor>Settings>Features option:

Inline Font Icons

When deactivated, the icons started showing.

**Comment by vitalis251288** [comment]
> For me, it was because of this Elementor>Settings>Features option:
> 
> Inline Font Icons
> 
> When deactivated, the icons started showing.

Amazing!!! It's works
