### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined and Uncaught (in promise) TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Punisher0916** [elementor/elementor#14728]
![image](https://user-images.githubusercontent.com/83265443/116189842-2389df00-a75c-11eb-8cfe-1d09b86f0211.png)

I'm having problem with my wordpress, I cannot go into my elementor builder, it is not loading and show some error in developer tool. I already tried the safe mode and change the template but still no luck

TIA

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
