### ISSUE TITLE
Indian Rupees currency option for paypal button

### ISSUE THREAD

**Issue by bhavanthsoni** [elementor/elementor#14735]
## Prerequisites

- [ yes ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ yes ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aviad-Herman** [comment]
Hi, unfortunately this currency is not supported by our implementation of PayPal.
