### ISSUE TITLE
Accordion - Default All Closed Option

### ISSUE THREAD

**Issue by jeffmankini** [elementor/elementor#14738]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Whenever I use an accordion element, I have to add a code snippet that sometimes doesn't even work, to collapse/close the first accordion item.

**Describe the solution you'd like**
It would be great to have an option in the accordion element that allows you to "collapse/close first/all items by default" or even open them if you wanted, but that isn't what I personally need. I just need it closed.

**Describe alternatives you've considered**
I have used an HTML code snippet that closes them, but with the latest Elementor versions, have had issues.

**Additional context**
None.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2756, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
