### ISSUE TITLE
Please add Karantina - Google Fonts

### ISSUE THREAD

**Issue by ishnechmad** [elementor/elementor#14732]
## Karantina - Google Fonts

The variety of fonts that were in Hebrew to this day in the database of Google fonts was limited and monotonous.
Recently added to the Google fonts ['Karantina'](https://fonts.google.com/specimen/Karantina) font which is multilingual, and its special design can contribute greatly to the design of titles on websites.
As a member in a designer community, I have seen that there is a [great demand](https://www.prog.co.il/articles/%D7%A4%D7%95%D7%A0%D7%98-%D7%97%D7%93%D7%A9-%D7%91%D7%92%D7%95%D7%92%D7%9C-%D7%A4%D7%95%D7%A0%D7%98-%D7%A7%D7%A8%D7%A0%D7%98%D7%99%D7%A0%D7%94.1867/) to include this font in Elementor.

thanks!

**Comment by d19dotca** [comment]
I believe you [can install any custom fonts in Elementor Pro](https://elementor.com/help/custom-fonts-pro/) already, if you needed Karantina urgently.

**Comment by ishnechmad** [comment]
For working alone - I can use CSS without Elementor at all... The advantage of Elementor is in simplifying the processes.

**Comment by d19dotca** [comment]
I'm not certain I understand what you mean. If you are looking to add a font that isn't included in Elementor by default, then that's where the Custom Fonts feature comes into play in Elementor. Perhaps I've misunderstood the request, my apologies if I did.

**Comment by ishnechmad** [comment]
I know the function of custom fonts in Elmentor Pro, and my request focuses on Elementor's built-in support of the [Google Fonts](https://fonts.google.com/specimen/Karantina) font library without having to upload the font to the site.

**Comment by ishnechmad** [comment]
> Looks like it's (among other fonts are) being added for 3.3.0. 👍

I have this version in beta (for developers), and unfortunately it is not there.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.2.4

Feel free to update

Thanks!
