### ISSUE TITLE
Page content widget or page content dynamic tag

### ISSUE THREAD

**Issue by diogostg** [elementor/elementor#14733]
Like the post content widget and the post title and page title dynamic tag, I would like to have the page content widget or page content dynamic tag.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
