### ISSUE TITLE
Elementor editor doesn't load - grey screen

### ISSUE THREAD

**Issue by vipetrus** [elementor/elementor#14734]
I'm using Elementor with the theme Astra, and for a few days there's been an issue with the editor. It's the grey kind of loader screen. I tried everything that is suggested, safe mode, loading method, different computer, different browser, there's no other active plugins (except for elementor header footer, but I have tried deactivating it, same issue), I contacted the host about x-frame settings, I went through the whole list. Everything is up to date.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
