### ISSUE TITLE
fix the display of icons on smartphones

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#14744]
Hello, on mobile devices, icons began to appear as squares after updating to version 3.1 and higher

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

In case the problem persists, please sent a screenshot. 
Without it, we simply can't help.

Thanks.
