### ISSUE TITLE
Report a bug in the elementor pop-up

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14747]
If we design a drop-down menu with elementor pop-up, if the number of menu options is large and the user opens the submenu, a number of options will go down and will not be seen.And are only seen if the user closes the submenu they opened.
Please investigate this issue.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
