### ISSUE TITLE
Report a bug on page 404 elementor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14742]
On large screens (1920 × 1200), the header section moves slightly to the right.This is not the case with smaller screens.
The bug is visible in this image.This bug only exists on page 404  :  https://prnt.sc/126orrd

Please check. Thanks.

**Comment by d19dotca** [comment]
You should add your environment details to the thread so people can test and know if this is theme-related, etc. Should ideally be filing bugs using the [Bug Report template](https://github.com/elementor/elementor/issues/new?assignees=&labels=&template=Bug_report.md).

**Comment by 79ho3ein** [comment]
If we design the 404 page inside the "Internal Section" widget, the section will move like the uploaded image.
I do not know, maybe this happens with wp-rocket enabled.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
