### ISSUE TITLE
Send elementor form notification to contact number

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14746]
Please add a feature to the mentor form, so that we can send the notification of the user-filled form to the webmaster number.
This feature is excellent and useful. Please check. Thanks

**Comment by 79ho3ein** [comment]
Please add this feature for Persian language as well.
thanks

**Comment by rami-elementor** [comment]
@79ho3ein 

When you say "webmaster number", are you talking about a phone number?

**Comment by 79ho3ein** [comment]
Yes, but that does not make sense for elementor.
