### ISSUE TITLE
URL Dynamic Content

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14755]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want if someone prints my post, then on the page they print there is the URL from which they print the page

**Describe the solution you'd like**
The solution is to add URL Dynamic Tags to elementor, because currently there is no "URL" in Dynamic Tags

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by mushlih-almubarak** [comment]
Hi @DorShahar 
This is not a bug report, it is a new feature request
Thank you

**Comment by DorShahar** [comment]
Sorry - my bad.
Could you please explain a bit more about your pain and need?

**Comment by mushlih-almubarak** [comment]
I want the [dynamic content URL ](https://elementor.com/blog/dynamic-content-elementor/)feature to be on elementor, currently elementor only supports dynamic content in part, for example, "article title", "user name", etc.
However, there is no "URL" dynamic content feature yet, can you add it?

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11234, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
