### ISSUE TITLE
Can't duplicate Testimonial Carousel

### ISSUE THREAD

**Issue by SayedTareq** [elementor/elementor#14751]
This error showing 
Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined
    at SwiperBC.createSwiperInstance (frontend.min.js?ver=3.3.0-dev3:2)
    at frontend.min.js?ver=3.3.0-dev3:2

When duplicate Testimonial Carousel

**Comment by DorShahar** [comment]
Hi 
Thanks for reporting.
I wasn't able to reproduce the issue. If the problem persists, please send your System info and a short video of the problem. 

Without it, we simply can't help.

Since you are a pro user - you are welcome to contact our support. 

Thanks.
