### ISSUE TITLE
Form Widget - eMail From not working

### ISSUE THREAD

**Issue by saschakoeth** [elementor/elementor#14759]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
See attached system info
[system-info-marketing-partner.de-28-04-2021.txt](https://github.com/elementor/elementor/files/6398616/system-info-marketing-partner.de-28-04-2021.txt)

```
</details>

**Comment by saschakoeth** [comment]
Hi Again!

Not sure if the desciption went through:

The email from feature of your form widget is not working.

See attached image:
https://prnt.sc/12954ay

What to do to make it work?

Thanks

Sascha

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
