### ISSUE TITLE
✅ 🚀smooth scroll feature in elementor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14765]
Please add this feature to elementor.
This feature can improve the user interface.There is currently a plugin for this feature. But it would be great if elementor made us not need this plugin.
Please share your opinion about this.

Thank you

**Comment by rami-elementor** [comment]
Hi @79ho3ein 

This feature request does not require an external plugin, there is a CSS property that do exactly that:

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

Already talked with the team. The only problem we see here is the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior#browser_compatibility). Safari is not fully supports this property in both mobile and desktop browsers.

But I think this is a great suggestion. We can replace our current JS based scrolling mechanism we are using and further improve site performance.

**Comment by 79ho3ein** [comment]
thank you @rami-elementor , This is really great. Of course, I used the plugin in the WordPress repository and did not see any problems with Safari.
https://wordpress.org/plugins/mousewheel-smooth-scroll/

**Comment by rami-elementor** [comment]
> thank you @rami-elementor , This is really great. Of course, I used the plugin in the WordPress repository and did not see any problems with Safari. https://wordpress.org/plugins/mousewheel-smooth-scroll/

This plugin uses a JS solution. It adds an extra HTTP request to your site and a JS that needs to be loaded. As mentioned above this solution will have a negative performance impact on your site. We try use CSS solutions wherever possible to improve performance.

**Comment by 79ho3ein** [comment]
Thank you!

**Comment by logosur** [comment]
> 

if you try to setup scroll smooth with css, you will see that sticky form error info won't be shown when validating.

html {
	scroll-behavior: smooth;
}

**Comment by nicholaszein** [comment]
Hey everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.25.0! 🥳 

CSS Smooth scroll is now a native part of Elementor.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
