### ISSUE TITLE
[Code Highlight] Settings menu for Dynamic Content broken

### ISSUE THREAD

**Issue by diiigle** [elementor/elementor#14766]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Pro 3.2 added dynamic content support for the _code syntax highlighter_ widget.
This does not work as expected from other widgets with dynamic content support.

The dynamic content button does appear over the code editor and for simple things like `Post Date` it works fine.
But if you choose dynamic content, that has further settings, the usual **dynamic content settings menu** does not appear over the code editor.

## Steps to reproduce

1. Add the `Code Highlight` Widget
2. Try to add dynamic content to the **Code** field using the usual button on the top right
![image](https://user-images.githubusercontent.com/5210911/116606100-83d17a00-a930-11eb-95ce-b508fac36a75.png)
3. After choosing an option, no settings menu appears that allows customizing the chosen dynamic content.
![image](https://user-images.githubusercontent.com/5210911/116606230-b2e7eb80-a930-11eb-9c41-9e2b97bf8def.png)

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
Elementor - 3.2.2 
Elementor Pro - 3.2.1
```

</details>

**Comment by tomasiser** [comment]
Yep, this is quite an issue for us. Looks like a small bug in the user interface.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.0

Feel free to update

Thanks!
