### ISSUE TITLE
Report a bug in the elementor section.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14769]
When we divide the section into 6 parts, and place the widget inside it, the section shrinks from the right by changing the width with the mouse.
As shown in the submitted image, the empty space is clear : https://prnt.sc/12awa0q

Please investigate this issue. is very important.thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
