### ISSUE TITLE
6th Custom Post Type breaks all Add New requests for all types

### ISSUE THREAD

**Issue by BGTheDog** [elementor/elementor#14774]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When creating custom post types (I need about 11 in total) I can add the first 5 and everything remains functional. Upon adding the 6th custom post type, The Add New function in the Admin Menu or in the post pages starts throwing this error: 

![image](https://user-images.githubusercontent.com/12819180/116791572-577d4100-aa89-11eb-8707-ed97a6ad9e69.png)

As soon as I delete the 6th post type all returns to working again.

## Steps to reproduce

1. Create up to 5 Custom Post Types
2. Validate that all remains working
3. Add the 6th custom post type
4. Attempt to add a new post under any of the existing 6 custom types (Also, attempting to add a generic Wordpress post also fails when there are 6 or more custom post types)
5. Remove any/all posts exceeding 5
6. Re-attempt to add a new post to any of the remaining types and all works as expected
 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.49
	PHP Version: 7.2.34
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://www.hoophavenct.com
	Home URL: https://www.hoophavenct.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Mesmerize PRO
	Version: 1.6.137
	Author: Horea Radu
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.49

== Active Plugins ==
	CaptainForm
		Version: 2.5.3
		Author: captainform

	Crocoblock Wizard
		Version: 1.1.0
		Author: Crocoblock

	Elementor
		Version: 3.2.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Jet Appointments Booking
		Version: 1.3.3
		Author: Crocoblock

	JetBooking
		Version: 2.2.3
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.5.7
		Author: Crocoblock

	JetEngine
		Version: 2.7.8
		Author: Crocoblock

	JetMenu
		Version: 2.0.9
		Author: Crocoblock

	JetPopup
		Version: 1.5.2
		Author: Crocoblock

	JetThemeCore
		Version: 1.2.1
		Author: Crocoblock

	Mesmerize Companion
		Version: 1.6.122
		Author: Horea Radu

	Social Feed Gallery
		Version: 3.2.1
		Author: QuadLayers

	VW Gallery Images
		Version: 0.1
		Author: VW Themes

	WooCommerce
		Version: 5.2.2
		Author: Automattic

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: incompatible
	JetElements For Elementor: compatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: compatible

== Elements Usage ==
	
	jet_page : 0
		jet-listing-dynamic-field : 2
		jet-listing-dynamic-image : 1
		jet-listing-grid : 1
	widget : 0
		image : 1
		jet-booking-calendar : 1
	wp-post : 0
		jet-booking-calendar : 1
		jet-engine-booking-form : 2
		jet-listing-dynamic-meta : 1
		jet-listing-dynamic-terms : 1
		jet-listing-grid : 1
		text-editor : 1
	wp-page : 3
		jet-engine-booking-form : 1
	single-page : 1
		jet-listing-dynamic-image : 1
		jet-listing-grid : 1
	jet-listing-items : 0
		heading : 1
		jet-listing-grid : 1

== Log ==
	
PHP: showing 3 of 3PHP: 2021-04-01 23:43:16 [notice X 7][/home/rb53sd69ud1o/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-27 02:52:22 [notice X 2][/home/rb53sd69ud1o/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-base.php::54] Undefined index: required [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-30 16:43:47 [error X 19][/home/rb53sd69ud1o/public_html/wp-content/plugins/elementor/core/files/css/base.php::361] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 6 of 62021-04-22 20:56:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-22 20:56:04 [info] elementor::elementor_updater Started 
2021-04-22 20:56:04 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-22 20:56:04 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-22 20:56:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-27 08:52:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]

				
</details>

**Comment by Aviad-Herman** [comment]
Elementor doesn't have the ability to create custom post types. You must be using an external plugin so you should be contacting their support team.

Thanks.

**Comment by BGTheDog** [comment]
Yes, It was Crocobloc—my mistake. Thanks for the response!

On Jun 15, 2021, at 4:49 PM, Aviad-Herman ***@***.***> wrote:

﻿
Elementor doesn't have the ability to create custom post types. You must be using an external plugin so you should be contacting their support team.

Thanks.
