### ISSUE TITLE
Please add the display conditions feature to elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14771]
This is a very important feature that elementor currently lacks.A similar example of this feature is available in Power pack and elementor extras plugin. : https://prnt.sc/12c0k0u
Please add this feature. elementor desperately needs it.

thanks.

**Comment by avivu** [comment]
I merged this issue with #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
