### ISSUE TITLE
Video as Site Background

### ISSUE THREAD

**Issue by failzapper** [elementor/elementor#14775]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, you cannot use a video as site background choices for site background include _classic_ and _gradient_. (see photo 1)

Such an option is only available for sections. (see photo 2)

 
**Describe the solution you'd like**
I would like to have this option available for the whole site.

**Describe alternatives you've considered**
I haven't fully considered any good alternatives as of the moment. Just duplicating a section, but that doesn't work that well.

**Additional context**

![image](https://user-images.githubusercontent.com/48150099/116805379-d4c3b700-ab58-11eb-910b-23c0778de9e3.png)
![image](https://user-images.githubusercontent.com/48150099/116805412-0177ce80-ab59-11eb-8075-76005b87c971.png)

**Comment by DorShahar** [comment]
Hi @failzapper  - how would you imagine it works? 
A video for the entire body, while the default section background is "transparent"?

**Comment by failzapper** [comment]
Yes, exactly like that. 

I was also trying to use a video background for a section with full-height inner sections, but the video just stretches throughout all the inner sections.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
