### ISSUE TITLE
Mobile Version is Jumpy

### ISSUE THREAD

**Issue by chris-mccarston** [elementor/elementor#14782]
Hey,

can't really find a solution so I hope I will have more luck posting my issue here:

https://screenrec.com/share/pyxl3VFmvB

As you can see, as soon as the columns faded in the page jumps back up a bit. I've got no idea why this happens

I think it is related to the motion "fade in from side". But I would love a fix for this since it makes the side more alive

Cheers

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
