### ISSUE TITLE
Not working - might be Safari High Sierra

### ISSUE THREAD

**Issue by Shopgirl76116** [elementor/elementor#14792]
Just an FYI -- Using PremiumPress Classified Theme on a Mac Laptop with Safari. Elementor worked fine last night, April 30,2021. Today, May 1, Elementor does not work, it will not load inside PremiumPress theme. After turning plugins off and other such things, I tried another computer with the newest Mac OS, and Elementor worked. So back at my laptop, I changed browser from Safari to Firefox and Elementor worked on Firefox. My laptop is still on the older OS High Sierra, as I would lose some programs if I upgrade OS, that means I am also on an older version of Safari 12.1 -- So what happened overnight I wonder, Elementor was working fine, then stopped. Crazy.

**Comment by alexcumbers** [comment]
Use Google Chrome or Firefox

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
