### ISSUE TITLE
I need different colors In icon List

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#14799]
If I user use Icon List the color icon is the same, I need every icon with a diferent color.

I have tried with CSS but I don´t know how use it.

selector .elementor-icon-list-icon i:first {color:#C31971;}

Is there any alternative?

Thank you !!

**Comment by anduinmooney** [comment]
In "Style", you can change the color of the icon. If you are using the selector property in CSS, ensure you are using just "Selector" and not .elementor-icon-list-icon i:first.

The final alternative is adding it to a stylesheet manually instead of using CSS built in with elementor.

**Comment by lauranunez** [comment]
Yes, but in Style change with the same color all icons. I need every icon different color. It is only possible with CSS, but I don´t find the Solution.

I have used selector but it doesn´t work. I don´t know if elementor-icon-list-icon i:first is right.

Thanks for your reply.

**Comment by JoeHana** [comment]
Just use

`selector .elementor-icon-list-item:nth-child(1) i {color: #333;}`

And increase the number in the brackets for every other icon you want to style in your list.

That should do the trick. Just make sure to not have a default color applied on the icons or use the !important statement (which I'd rather not recommend to overuse but nevertheless it will add the necessary specifity to your CSS to get you what you want)

**Comment by lauranunez** [comment]
yes!! It Works

selector .elementor-icon-list-item:nth-child(1) i {color: #333;}
selector .elementor-icon-list-item:nth-child(2) i {color: red;}
selector .elementor-icon-list-item:nth-child(3) i {color:green;}

THANK YOU

I was using

i:nth-child(1)

Wrong.

Thank you!!!!!!!!!

**Comment by JoeHana** [comment]
@lauranunez glat it works now. Please close this issue now.

**Comment by Aviad-Herman** [comment]
Great conversation!
