### ISSUE TITLE
Column flexbox alignment bug

### ISSUE THREAD

**Issue by wpbits** [elementor/elementor#14806]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The vertical-align setting doesn't work anymore. https://share.getcloudapp.com/Z4uo2gQe 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
https://pastebin.com/QmhCGGVy
```
</details>

**Comment by shilo-ey** [comment]
Hi @wpbits 

The feature you are describing is working to Elementor widgets and elements and not to image inside WYSIWYG editor.

Thanks

**Comment by wpbits** [comment]
@shilo-ey It is not inside the WYSIWYG editor. They are in two columns.

Just figured out, the problem happens only when you import a template from an older version. Say, you have created your website with Elementor 2.7 and exported it via WordPress Export, then imported it to a new install with Elementor 3.2, then the "flexbox:"  fails.
