### ISSUE TITLE
column on text editor (woodmart theme)

### ISSUE THREAD

**Issue by yukaisonline** [elementor/elementor#14802]
upgrading elementor from 3.1.4 to 3.2.2 the column in text editor doesn't work yet. all text stay on the first column and the second it's blank and it's impossible do nothing else. I downgraded to 3.1.4 and problem is fixed.
the image below show the problem.
I hope you can fix it! thanks

![Schermata 2021-05-03 alle 20 34 21](https://user-images.githubusercontent.com/83604165/116917539-10d94380-ac4f-11eb-85c3-0364278754da.jpg)

**Comment by DorShahar** [comment]
Hi @yukaisonline 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
