### ISSUE TITLE
Suggest an improvement in elementor.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14808]
In the icon list widget, when we color the text when hovering, it should be in such a way that the color changes when the user hovers over the text. Not the whole row of that text.
At the moment, when the mouse is hovering on the specified parts, the color is applied, which is not good.
Before pointing : https://prnt.sc/12h8jtk
after point : https://prnt.sc/12h8n5j
According to these images, to change the text rank after the hover, the mouse does not need to be on the hover text.
While this is not good. And it is better when the color of the text changes, so that the text itself is hovering.
Please correct this. Thank you

**Comment by JoeHana** [comment]
There is a setting with which you can apply the link on the full with or just inline. Guess this will solve this issue for you?

**Comment by 79ho3ein** [comment]
@JoeHana 
Yes, the link is inline and there is no problem.I mean, when the mouse hovers over the widget row (like a photo), the color of the text changes. (Floating mode) https://prnt.sc/12iwd8e This is not good.
It should be such that when the mouse is on the text, the color of the text changes.
I'm talking about hover mode in the icon list widget.

Do you understand what I mean?
thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
