### ISSUE TITLE
Elementor Icon not showing

### ISSUE THREAD

**Issue by patpayte** [elementor/elementor#14807]
Hello, most of the icons on elementor are not reflecting on our previews. It was okay before. most of our pages are affected by this. please advise

domain: porcelainskin.com

![image](https://user-images.githubusercontent.com/83644283/116992824-37f44b80-ad09-11eb-9646-33400bdd9f37.png)
![image](https://user-images.githubusercontent.com/83644283/116992832-3aef3c00-ad09-11eb-87be-fe709501d96f.png)

**Comment by luvkeyz** [comment]
Go to the “Elementor” > “Settings” and open the “Advanced” tab. Here you need to find the “Load Font Awesome 4 Support” option and activate it.

**Comment by patpayte** [comment]
Hi @luvkeyz , upon check on the backend. it is already activated but the issue still persists
![Uploading image.png…]()

**Comment by patpayte** [comment]
Hi @luvkeyz, upon checking on the backend. it is already activated but the issue still persists

![image](https://user-images.githubusercontent.com/83644283/117122278-50776b00-adc8-11eb-84b7-767b8c86c9f5.png)

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
