### ISSUE TITLE
A suggestion for the new elementor widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14805]
Please add a widget so we can slideshow our content.Just like a drop-down menu.
This widget will be very useful.  We can use it to create a drop-down menu or in the store section, slide show product filters to users.
We can create the desired section in the theme builder and then display it in this widget.
Just like the template widget that is currently available among elementor widgets.
Please review this offer.  It will be very useful.

 Thank you

**Comment by avivu** [comment]
I merged this issue with #13054, which is on the same subject, to deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
