### ISSUE TITLE
🔗 🚀 Feature Request: Can you please make a Table feature. (Duplicate of #1342)

### ISSUE THREAD

**Issue by bhavanthsoni** [elementor/elementor#14804]
## Prerequisites

- [ yes] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ yes] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

example: https://rankgarp.com/wp-content/uploads/2021/05/Table-Elementor.png

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rushdiey** [comment]
Ya good for pro user. I need to use alternate addon for this table. or using html code. Hope they will update this

**Comment by bhavanthsoni** [comment]
That's true for many Pro users it will be useful. 

I had used addons but the plugin was causing my site to load slow. and when moved to HTML I'm facing an alignment issue. ( check this out. https://prnt.sc/12gjhh2 )

if Elementor could have the feature I think the issue can be solved.
