### ISSUE TITLE
Does elementor have a program to add display conditions ???

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14817]
Does elementor have a program to add display conditions ???
This feature is widely used in powerpack and elementor extra plugins.
Will this feature be added to elementor?

**Comment by luvkeyz** [comment]
Download "master addon for elementor"

**Comment by DorShahar** [comment]
Hi 
Yes! we are working on this at the moment. 
If you would like to participate in the usability test - please fill up [this form](https://uxpractices.elementor.cloud/joinresearch/
). 

Thanks
