### ISSUE TITLE
Bug with custom SVG on Social Icon Widget

### ISSUE THREAD

**Issue by boriscaldeira** [elementor/elementor#14811]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

There is a bug when using custom SVG icons regarding the Social Icon Widget. It goes as follows. I want to have different sections of the website using different colors for the Social Icons on the Social Icon Widget, therefore I have a white version and a brown version of the Social Icons. What happens is that the **all** icons in **every section** turn brown when a new section is made and brown icons used with the Social Icon Widget in that section, and if the icons used in the new section are the white ones, all the icons in all of the sections turn white.

## Steps to reproduce

1. Create a section with the Social Icon Widget and use custom SVG icons. These have the brown color as can be seen on the step1.png file.
2. Create a new section, adding the Social Icon Widget, adding custom SVG icons of the white color. This can be seen on the step2.png file.
3. As a result of step2, the icons created on step1 are now of white color, even though the files haven't been changed. This can be seen on the step3.png file.
4. A new section is created, along with a new Social Icon Widget. The custom brown SVG icon is used as can be seen on the step4.png file.
5. As result of the previous step, all other Social Icon Widgets on all other sections assume the brown SVG icon. This can be seen on the step5.png file.
![step1](https://user-images.githubusercontent.com/36826715/117030537-a8926c80-acf7-11eb-8839-e98efcb98d67.png)
![step2](https://user-images.githubusercontent.com/36826715/117030544-a9c39980-acf7-11eb-8da0-f45577edcee7.png)
![step3](https://user-images.githubusercontent.com/36826715/117030547-aa5c3000-acf7-11eb-9a01-1fa22286e0d2.png)
![step4](https://user-images.githubusercontent.com/36826715/117030548-aa5c3000-acf7-11eb-9681-9edc30702ac7.png)
![step5](https://user-images.githubusercontent.com/36826715/117030552-aaf4c680-acf7-11eb-9fdf-efeec9e99ab1.png)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.49
	PHP Version: 7.3.23
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://casacalmaria.com
	Home URL: https://casacalmaria.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: pt-PT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36 OPR/75.0.3969.243

== Active Plugins ==
	Elementor
		Version: 3.2.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Under Construction
		Version: 3.88
		Author: WebFactory Ltd

== Elementor - Compatibility Tag ==
	
	Elementor Pro: incompatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	page : 1
		button : 2
		heading : 3
		image : 14
		social-icons : 4
		text-editor : 7
		video : 1
	wp-page : 5
		button : 5
		heading : 9
		image : 32
		social-icons : 10
		spacer : 2
		text-editor : 14
		video : 2

== Log ==
	
PHP: showing 3 of 3PHP: 2021-05-03 15:04:23 [notice X 3][/home/er492awv/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-03 15:19:58 [warning X 1][/home/er492awv/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-03 15:47:02 [warning X 1][/home/er492awv/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(GEEKCASE_PROPOSTA_CALMARIA_WEBSITE_Prancheta 1 cópia 3.png): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by DorShahar** [comment]
Hi
Thank you for your feedback. 
Could you please add your SVG's here so we could investigate? 

Thanks

**Comment by boriscaldeira** [comment]
Hello,
Thank you for the quick reply.
I have placed the SVG's on the attached zip file.

Best regards

[socialicons.zip](https://github.com/elementor/elementor/files/6426599/socialicons.zip)

**Comment by boriscaldeira** [comment]
Greetings,

Any news regarding this issue?

Best regards

**Comment by DorShahar** [comment]
Hi @boriscaldeira 
We will need to investigate this problem, but it might take time due to other tasks (and bugs) in our backlog. 

Thank you for your patience.

**Comment by DorShahar** [comment]
Hi @boriscaldeira 

We recreated your process of work once again and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro)
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

Thanks.
