### ISSUE TITLE
Elementor Slider, Testimonial, Counter is not working when  Improved Asset Loading is active

### ISSUE THREAD

**Issue by DevDietheR** [elementor/elementor#14826]
### Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

### Description
I was testing the Elementor Version 3.2.2 and Pro, I'm not sure if it is really like that or it is a bug. Coz I like the Improved Asset Loading, it helps the site to speed up a little bit but suddenly I encounter this problem. if it is active the slider, testimonial, counter etc is not working anymore.

### Steps to reproduce

- [x]  Use the Widget Slider, testimonial etc.
- [x]  Activate Improved Asset Loading

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active/Hello Elementor.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DevDietheR** [comment]
@DorShahar You can close this issue now, Suddenly it's working fine

**Comment by DorShahar** [comment]
Thanks @DevDietheR
