### ISSUE TITLE
⛔ 🐞 Bug Report: Check needed for in_the_loop() context on add-to-cart.php render() function

### ISSUE THREAD

**Issue by deepwaterpixel** [elementor/elementor#14825]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

I need to use a custom SVG icon for the Add to Cart button on a project, and the Elementor Pro Custom Add to Cart button works best for me because it provides me with the SVG option, and when you do not explicitly set a product for this widget, it will pick up the post_id using a few different checks, making it ideal for use in dynamic templates.  However, I've run into a problem in the past where not setting the product, and using the button in loop template results in a failure to create the AJAX button that works to add the product to cart.

## Steps to reproduce

1. Create a loop template (JetEngine Listing template, Ele Custom Skin loop template, custom PHP loop, or any other loop creation method you prefer)
2. Add the **Custom Add to Cart** widget to the loop template
3. Make sure the loop template is assigned to custom post with a `_price` field, or the `product` post type
4. Check the add to cart HTML and functionality in the editor or the front end, it does nothing.

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

## Environment

I have solved this problem agnostic of environment.

## Solution

Add a new check to the `/elementor-pro/modules/woocommerce/widgets/add-to-cart.php` file around line 148, where you have the following checks:

```
if ( ! empty( $settings['product_id'] ) ) {
	$product_id = $settings['product_id'];
} elseif ( wp_doing_ajax() ) {
	$product_id = $_POST['post_id'];
} else {
	$product_id = get_queried_object_id();
}
```

If you insert an additional check after these attempts to grab the `product_id`, using `get_the_id()` instead of the result of `get_settings_for_display()` (set in the widget settings by choosing a specific product), the `$_POST` global, or `get_queried_object_id()`, which are not accessible from within the loop context.

Obviously, you don't have to use my solution, but here's how I solved it, by adding an additional check after the checks above:

```
if ( ! empty( $settings['product_id'] ) ) {
	$product_id = $settings['product_id'];
} elseif ( wp_doing_ajax() ) {
	$product_id = $_POST['post_id'];
} else {
	$product_id = get_queried_object_id();
}

global $product;
$product = wc_get_product( $product_id );

// If previous attempts to get product from ID fail, attempt to grab the ID from within post loop
if( ! $product ){
	$product_id = get_the_id();
	$product = wc_get_product( $product_id );
}
```

I don't like to modify core files, but I knew that there were already checks in place for dynamic usage (where ID isn't supplied in widget settings but picked up by context).  I also did not have time to solve this before, and while I didn't really have it this time, I had to solve it in order to deliver the project I'm working on.

**Comment by deepwaterpixel** [comment]
I just checked v3.3.2 the code is the same.  Just wondering if there was an update to this?  I realize I probably didn't implement the most efficient method to check this, but I would like to find a solution that doesn't require me to manually modify this file after every update.

**Comment by nicholaszein** [comment]
Hello @deepwaterpixel,

Thank you for reaching out and thank you for being so patient! 🙏 

I want to give you an update about this issue. What you requested was not possible because we do not give support for 3rd-party add-ons. And that's why it wasn't accepted before.

However, now we have the new [Loop Builder ](https://elementor.com/help/loop-grid/), with full WooCommerce support. This means you can now build your Loop Templates natively without any hassle! 🙌 

#### ⛔ For this reason I'm closing this issue.

In the future, please keep in mind that we do not provide support for 3rd-party add-ons.

I hope the new features help you achieve what you want.

Kind Regards
