### ISSUE TITLE
prevent post widget from reload the page

### ISSUE THREAD

**Issue by luxpatrick** [elementor/elementor#14828]
When I click on the pagination of the post widget, then the page reloads and moves to the top of the page. 
I want the page to stay at the same position and not moving to the top when clicking on the pagination.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
