### ISSUE TITLE
Report a bug in the button widget and icon list.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14831]
Unfortunately, when we use the svg file for the icons of these two widgets, they bug.
I tested this problem on several similar sites and it existed. please check

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
