### ISSUE TITLE
Custom Break Point Nav Menu not breaking for hamburger icon

### ISSUE THREAD

**Issue by nishantpatel227** [elementor/elementor#14833]
I setup custom breakpoint for tablet 1100px but nav menu is not breaking up at 1000px. It break up for mobile at 768px perfect.
Tried to regenerate CSS didn't help.
Theme: Astra 
Plugin: Elementor Pro
Wordpress: 5.6 
![image](https://user-images.githubusercontent.com/60674211/117221928-7c462100-adc7-11eb-8599-cd415ade3572.png)

![image](https://user-images.githubusercontent.com/60674211/117221629-ead6af00-adc6-11eb-803b-2f64142b4cac.png)
![image](https://user-images.githubusercontent.com/60674211/117221719-1d80a780-adc7-11eb-8158-f8cd0b5e57f1.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.2.3

Feel free to update

Thanks!
