### ISSUE TITLE
Website looks like it no longer has any css, everything since the upgrade to wordpress 5.7.1. It looks like a document, and not a website

### ISSUE THREAD

**Issue by ramirezc77** [elementor/elementor#14835]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by ramirezc77** [comment]
Please revert the upgrade or add restore the page prior to the update of wordpress 5.7.1

**Comment by BTC-Bob** [comment]
This has been a recurring issue for me as well. My FIX has been to open each page again and do a couple of simple edits (like delete a word, then type it back again). After this I refresh the page again and it often comes back fully formatted again. But not always, sometimes I have to repeat the process several times. This is extremely time consuming and frustrating (and it would be embarrassing it my client every see his/her site this way. Fixing this BUG should be a high priority!

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
