### ISSUE TITLE
Eicons / font-display:swap error

### ISSUE THREAD

**Issue by lafilg** [elementor/elementor#14841]
Hi all,

since the known eicon-problem & fix, the eicons didn't register with "**font-display:swap**" so it is marked as error in google page speed insights.

Thanks for an update,

all the best,

lars

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
