### ISSUE TITLE
Style changes in Title component upon adding values to link input

### ISSUE THREAD

**Issue by oxuserhr** [elementor/elementor#14847]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

When I use the title component and adjust the text style it appears correctly if I do not add a link. However once I add any value in the Content > Title > Link input the style seems to be removed, and change to another, although the style settings remain the same and reflect the intended style. Once you remove the url value, then the style changes back to the expected style.

![After adding a link](https://user-images.githubusercontent.com/3381184/117458267-031f0900-af42-11eb-83e2-033183cf8e55.PNG)
![Before adding link to Title component](https://user-images.githubusercontent.com/3381184/117458271-04503600-af42-11eb-94f0-c4e6f9917a83.PNG)

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Windows 10 desktop, Chrome
User Agent:-
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
```
</details>

**Comment by Aviad-Herman** [comment]
Hi,
Somewhere in your theme or site, unrelated to Elementor, someone defined CSS styles that target links.
For some reason, in your case it seems to take precedence.

You need to figure out where this style is coming from and remove it.
