### ISSUE TITLE
Add Instagram Direct in social sharing widget

### ISSUE THREAD

**Issue by aggrawalmohit** [elementor/elementor#14840]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Instagram is more popular now a days than any other social media platforms. There should be instagram direct sharing button available in social sharing widget.

**Describe the solution you'd like**

Simply add a instagram sharing widget.

**Describe alternatives you've considered**

We have to install 3rd party plugins to solve this problem.

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11315, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
