### ISSUE TITLE
Local Time Dinamic Content

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#14854]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
I want time dynamic content features according to the user's local time, and not according to the WordPress default time. Because now Elementor only supports time dynamic content according to the time in wordpress, and not according to the time the user accesses my site

**Describe alternatives you've considered**
n/a
**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by DorShahar** [comment]
@mushlih-almubarak - this will be taken care of in the same project of Elements Display Conditions that we are working on.

Thanks.

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on User Role and a lot of other conditions (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
