### ISSUE TITLE
Sitebreaking Responsive Mode Visbility Bug

### ISSUE THREAD

**Issue by Aebl8** [elementor/elementor#14873]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Since the new Responsive Update there is a pixel width where all elements are shown (Elements hidden with Responsive -> Visibility hidden on tablet / desktop etc.)

For Example: 
Tablet Breaking Point is set to 1024 pixel. When in Google Chrome I am at exactly 922 pixel, Elements that are usually only visible on Desktop and Elements that are set to visible only on tablet are both present at the same time.

Why the tablet breakpoint is at 922 instead of the set 1024 is another problem but that might me do to some scaling issue.

## Steps to reproduce

Open Google Chrome go to swi.idesign.tirol press f12 and set pixel to 922 at the team section you can see it the most easily. 
Recreate it yourself: Hide one section on tablet another on desktop. Find your Breakpoint and you'll se that both sections are visible.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.3.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://swi.idesign.tirol
	Home URL: https://swi.idesign.tirol
	WP Multisite: Yes
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Vienna
	Debug Mode: Inactive

== Theme ==
	Name: Stoffwechsel Innsbruck
	Version: 1.0.1
	Author: Marco Ströher
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

== Active Plugins ==
	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.0.4
		Author: Hu-manity.co

	JetElements For Elementor
		Version: 2.5.3
		Author: Crocoblock

	reSmush.it Image Optimizer
		Version: 0.4.1
		Author: reSmush.it

== Network Plugins ==
	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	SG Optimizer
		Version: 5.7.20
		Author: SiteGround

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	JetElements For Elementor: header_not_exists

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		form : 1
		icon-list : 4
		nav-menu : 2
		text-editor : 5
	section : 5
		form : 1
		image : 3
		text-editor : 1
	wp-page : 4
		button : 10
		divider : 4
		flip-box : 12
		form : 1
		heading : 5
		html : 5
		image : 5
		jet-timeline : 1
		text-editor : 39
		video : 5

== Log ==
	
PHP: showing 2 of 2PHP: 2021-05-01 17:23:15 [notice X 3][/home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-03 09:59:33 [error X 1][/home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(4, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/idesign.tirol/public_html/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/idesign.tirol/public_html/wp- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52021-05-05 08:20:32 [info] elementor::elementor_updater Started 
2021-05-05 08:20:32 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-05-05 08:20:32 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-05-05 08:20:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.3',
)]
2021-05-05 08:20:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.3',
)]
</details>

**Comment by DorShahar** [comment]
Hi @Aebl8 
Thanks for reaching out. 

I couldn't reproduce your problem on my end.
If you are a Pro user - please contact our support team and they could investigate the problem.

Thanks.
