### ISSUE TITLE
A question from elementor developers. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14878]
hello
In previous requests, I was informed that you have decided to add the display conditions feature to elementor. Is there a time limit for the release of this feature?
I personally count the moments to release this feature.

Thanks to the elementor team.

**Comment by isotrope** [comment]
In the meantime, you can use something like https://wordpress.org/plugins/visibility-logic-elementor/

**Comment by 79ho3ein** [comment]
Yes, there are similar plugins, but this feature is much needed in the elementor plugin itself.
And as far as I know, elementor is working on this feature.
Thank you for your attention.

**Comment by DorShahar** [comment]
Hi 
We hope to release it in Q3, but there is no release date at the moment. 
Thanks.
