### ISSUE TITLE
Nav-bar Dropdown Menu stopped working since Update-Version 3.3.0-dev12

### ISSUE THREAD

**Issue by noraceday** [elementor/elementor#14905]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

 This ussue exits since the last Elementor Pro-Update 3.3.0-dev12. I don't know what else to say, all plugins deactivated  - no effect, flushed cache - same. Even switched the templates and tried to reproduce the issue - same outcome.

## Steps to reproduce

 1. Set a nav-bar menu for mobile devices. 2. Set the Dropdown menu to dropdown mode and select full width. Thats all i've done.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Zahtar** [comment]
Had the same issue with E-Pro dropdowns, and with pop-ups not working. Traced it to a recent update with Breeze plugin, which now includes a default list of deferred js scripts. I cleared that whole list from Breeze and flushed the cache, and Elementor was working properly again. Could have taken the time to delete those scripts one-by-one to identify which of them were needed for Elementor, but had already wasted enough time on the problem. Several other people in the Elementor FB group have reported the same issue with Breeze, so I also sent a heads-up to Cloudways.

If you're not using Breeze, then carry on.... but hope this helps!

**Comment by noraceday** [comment]
Unfortunately not, but i'll keep you up to date. Thanks for your response!

**Comment by tomvansichem** [comment]
I've had the same issue. By deleting (or comment out) the 'nonce'-attribute in the Breeze Delay JS Inline script-section, everything was working again.

**Comment by noraceday** [comment]
I‘m not using breeze so can‘t tell :}
Hopefully it works for someone else.

**Comment by timtunnicliff** [comment]
I am having the same issue. Full-width mobile dropdown doesn't work.

Can be seen here: https://thegreatruggerrun.org/

**Comment by noraceday** [comment]
Solved this issue by downgrade to an older version of elementor.
