### ISSUE TITLE
After complete DB dump Elementor losts its Global settings

### ISSUE THREAD

**Issue by david-strejc** [elementor/elementor#14914]
On multiple sites with Elementor 3.2.3 and Elementor Pro 3.2.1 after mysqldump and restore Elementor does not have it's global settings.

This is probably from version 3.2

**Comment by shilo-ey** [comment]
The associated Kit - all of your site settings are stored in the "Default Kit" template and assigned in the wp_options table.

I can assume that once you reset your DB your setting in options.php was cleared.

You can either update the ID or update the global settings

Thanks
