### ISSUE TITLE
[Elementor PRO]PHP notice error caused by missing field in response from https://my.elementor.com/api/v1/licenses/

### ISSUE THREAD

**Issue by ajoah** [elementor/elementor#14912]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
A PHP notice appears on page /wp-admin/plugin-install.php when there is an elementor pro new version available :

`Notice: Undefined property: stdClass::$plugin in /wp-includes/class-wp-list-util.php on line 159`

## Steps to reproduce

Go to /wp-admin/plugin-install.php when an elementor pro new version is available

## Details
I traced the origin of the problem : it is due to the incomplete response of the licence request to https://my.elementor.com/api/v1/licenses/, the field "plugin" is missing which causes the error.

The field is used here : https://github.com/WordPress/WordPress/blob/5.7.1/wp-admin/includes/class-wp-plugin-install-list-table.php#L258

**Comment by shilo-ey** [comment]
Thank you @ajoah 

We are checking your report and will update here soon.

**Comment by shilo-ey** [comment]
@ajoah Are you still experiencing this issue?

**Comment by ajoah** [comment]
Yes.

1. Enable WP_DEBUG
2. Install the previous version of Elementor pro
2. Delete transient `_site_transient_update_plugins`
3. Go to /wp-admin/plugin-install.php

![elementor](https://user-images.githubusercontent.com/10757301/118829089-1f199780-b8be-11eb-9796-808948c694e5.gif)

Blues lines comes from a var_dump I added in wp_list_pluck function : 
```
if ( empty( $value->$field ) ) {
   d( $value );
}
```

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
