### ISSUE TITLE
Elementor will not load at all

### ISSUE THREAD

**Issue by blackashconsulting** [elementor/elementor#14920]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Elementor will not load at all. Upon clicking "edit with elementor", nothing happens. it just sits there and does nothing except attempt to load. This happens on all sites that I've currently tested (over 10), and happens regardless of Cloudflare use or not. Cloudflare simply renders a 524 issue, but sites that don't utilize Cloudflare simply won't load at all. I've tried rolling back all the way to 2.9.9, and the issue remains.

## Steps to reproduce

Go to Pages > try to edit any page using elementor.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: (Ubuntu) v5.7.33
	PHP Version: 7.2.34-21+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: http://ellesanderson.blackashadmin.xyz
	Home URL: http://ellesanderson.blackashadmin.xyz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0

== Active Plugins ==
	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.7
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Head, Footer and Post Injections
		Version: 3.2.2
		Author: Stefano Lissa

	Superfly Menu
		Version: 5.0.19
		Author: Looks Awesome

	UpdraftPlus - Backup/Restore
		Version: 2.16.57.25
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.5.3
		Author: Wordfence

	WP-Optimize - Clean, Compress, Cache
		Version: 3.1.9
		Author: David Anderson, Ruhani Rabin, Team Updraft

	Yoast SEO
		Version: 16.2
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Contact Form DB: header_not_exists
	Elementor Pro: header_not_exists

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	page : 15
		accordion : 1
		button : 7
		form : 1
		gallery : 2
		global : 47
		heading : 118
		html : 3
		icon : 2
		image : 36
		nav-menu : 10
		posts : 1
		search-form : 2
		social-icons : 6
		spacer : 40
		text-editor : 39
	section : 1
		global : 4
		heading : 1
	widget : 0
		button : 77
		heading : 45
		html : 7
		image : 3
		nav-menu : 46
		social-icons : 67
		text-editor : 59
	wp-page : 9
		accordion : 1
		button : 4
		divider : 1
		form : 1
		gallery : 1
		global : 53
		heading : 67
		image : 20
		posts : 1
		price-list : 2
		spacer : 26
		text-editor : 14


== Log ==
	
Log: showing 9 of 92021-03-27 23:32:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]
2021-04-22 13:32:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-22 13:32:28 [info] elementor::elementor_updater Started 
2021-04-22 13:32:29 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-22 13:32:29 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-22 13:32:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-27 00:18:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-06 18:58:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-06 18:58:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]


				
```
</details>

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

In addition , 524 error is a Cloudflare error. You can look for more details [here](https://www.raramuridesign.com/kb/articles/error-524-a-timeout-occurred-what-it-is-how-to-fix-it.html#:~:text=The%20524%20A%20Timeout%20Occurred,using%20a%20piece%20of%20software.).

Thanks.

**Comment by blackashconsulting** [comment]
This is Literally a bug in elementor's JS- there are tickets open about this. Why are you all ignoring this issue when it's been posted about several times here?

**Comment by blackashconsulting** [comment]
> Hi,
> 
> Please create GitHub issues only for bugs reports and feature requests.
> **GitHub issues are not for support.**
> 
> If you have questions or need general support, Please try:
> 
>     * Elementor Community on Facebook
> 
>     * Elementor Knowledge base
> 
>     * Support forums on WordPress.org
> 
>     * Elementor Developers docs
> 
> 
> If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).
> 
> In addition , 524 error is a Cloudflare error. You can look for more details [here](https://www.raramuridesign.com/kb/articles/error-524-a-timeout-occurred-what-it-is-how-to-fix-it.html#:~:text=The%20524%20A%20Timeout%20Occurred,using%20a%20piece%20of%20software.).
> 
> Thanks.

This is Literally a bug in elementor's JS- there are tickets open about this. Why are you all ignoring this issue when it's been posted about several times here?

As I said in my post above, this is NOT simply effecting my my Cloudflare sites- this is effecting every site I have on my server that utilizes Elementor. I am not the only person having this issue, and it is clear by other posts that there is an error in the JS that is making elementor unable to load.

Closing these issues and responding with trivial nonsense that I am well-aware of isn't helping me or anyone else who is experiencing this bug in the JS. Please fix this issue. We are literally unable to work because of this bug.
