### ISSUE TITLE
Please add a header return widget to elementor.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14936]
hello
**I think elementor strongly lacks this widget** : https://prnt.sc/12vnlal
As you can see in the picture, this is a very important feature that is present in every site.Of course, it is now possible to create such a thing in elementor with a little skill, but it is not what is expected.And it is very rudimentary.
Great if you add elementor to this widget. Because in this case, it can develop it in a more specialized way.
Features such as user transfer speed, animation, reaction after reaching the top, etc. are required for this widget.
I will introduce a similar example of this feature to elementor developers, I hope if possible they will add this important and useful widget to elementor. https://woodmart.xtemos.com/

thanks.

**Comment by Aviad-Herman** [comment]
Hey, 
Thanks for the input.

We will think about adding this as a widget but it's currently not top priority.
Like you said, users can use these instructions to create this effect on their own:
https://elementor.com/help/how-to-add-a-back-to-top-button-using-elementor/

So I'm closing this issue for now but be sure that if we decide to build such a widget we will search GitHub and find your suggestion.

Thanks and please continue giving us great ideas!
