### ISSUE TITLE
Elementor Forces a value in padding!

### ISSUE THREAD

**Issue by Flipback8** [elementor/elementor#14945]
Elementor forces you to have a value in padding! When you insert a value it places a Zero in the fields! Zero is a value. So annoying!

https://snipboard.io/zWL18k.jpg

I don't want Elementor to generate any values in the padding or margin fields for me. How can inherit desktop settings if when I go to mobile view to change one value Elemntor forces all the Zeros!

**Comment by riadcitaku** [comment]
Click on the right to link/unlink, after that you can remove the zero.

**Comment by Flipback8** [comment]
Negative you can't remove the zeros.  You can override them with other numbers but you can't leave the field blank. I did unlink the fields.

**Comment by DorShahar** [comment]
@Flipback8 , thanks for reaching out.
You can delete any value in any field and it will restore that original value. 

As for the inheritance value, we are working on changing it in the future.

Thanks.
