### ISSUE TITLE
Link Dynamic Tags Missing 

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#14942]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

The Dynamic Tag icon is missing from the link field when Elementor Pro has expired or is disconnected. Is this a bug or a "feature"?

## Steps to reproduce

Disconnect the Elementor Pro license and try to use a link Dynamic Tag on a widget like a Button. See attached screenshot.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 7.4.19
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 2.0
	Author: Wicky Design
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.0.3
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

== Active Plugins ==
	Advanced Post Queries
		Version: 1.0.15
		Author: Shabti Kaplan

	All in One SEO
		Version: 4.1.0.2
		Author: All in One SEO Team

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Ele Custom Skin
		Version: 3.1.0
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.2.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	GP Premium
		Version: 2.0.1
		Author: Tom Usborne

	Head, Footer and Post Injections
		Version: 3.2.2
		Author: Stefano Lissa

	JetSmartFilters
		Version: 2.2.2
		Author: Crocoblock

	Open External Links in a New Window
		Version: 1.42
		Author: WebFactory Ltd

	Redirection
		Version: 5.1.1
		Author: John Godley

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	Search & Filter - Elementor Extension
		Version: 1.0.6
		Author: Code Amp

	SVGator
		Version: 1.1.1
		Author: SVGator

	White Label CMS
		Version: 2.2.2
		Author: www.videousermanuals.com

	WooCommerce
		Version: 5.2.2
		Author: Automattic

	Wordfence Security
		Version: 7.5.3
		Author: Wordfence

	WP-PostViews
		Version: 1.76.1
		Author: Lester 'GaMerZ' Chan

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: compatible
	Elementor Pro: incompatible
	Search & Filter - Elementor Extension: header_not_exists

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: compatible

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		button : 1
		heading : 1
		template : 1
		text-editor : 2
	footer : 1
		button : 1
		heading : 1
		html : 1
		text-editor : 4
	header : 1
		image : 1
		uael-nav-menu : 1
	loop : 3
		button : 2
		post-info : 2
		text-editor : 2
		theme-post-featured-image : 3
		theme-post-title : 2
	page : 5
		button : 15
		divider : 2
		form : 2
		heading : 39
		html : 1
		icon : 9
		image : 21
		reviews : 1
		spacer : 1
		template : 1
		text-editor : 21
		wp-widget-rss : 2
	popup : 4
		form : 4
		heading : 5
		icon : 1
		spacer : 1
		text-editor : 3
	section : 7
		button : 2
		global : 1
		heading : 6
		image-box : 12
		testimonial-carousel : 1
		text-editor : 4
	single : 2
		button : 1
		heading : 2
		image : 1
		nav-menu : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		search-form : 1
		share-buttons : 1
		spacer : 1
		template : 2
		text-editor : 4
		theme-post-content : 1
		theme-post-title : 1
	widget : 0
		image : 4
		posts : 4
	wp-post : 3
		button : 84
		divider : 28
		form : 11
		global : 5
		heading : 279
		html : 7
		icon : 71
		icon-box : 12
		icon-list : 1
		image : 158
		image-box : 18
		menu-anchor : 1
		posts : 3
		reviews : 2
		shortcode : 1
		spacer : 5
		template : 22
		testimonial-carousel : 1
		text-editor : 223
		toggle : 3
		video : 7
	wp-page : 86
		button : 43
		countdown : 1
		divider : 8
		form : 7
		heading : 166
		html : 3
		icon : 52
		icon-box : 6
		icon-list : 1
		image : 84
		image-carousel : 1
		jet-smart-filters-date-period : 1
		jet-smart-filters-pagination : 1
		jet-smart-filters-select : 1
		jet-smart-filters-sorting : 1
		nav-menu : 1
		posts : 7
		shortcode : 1
		sidebar : 1
		template : 6
		text-editor : 110
		video : 2
		wp-widget-media_svgator : 1
	search-results : 1
		posts : 1
		wp-widget-search_filter_register_widget : 1

![elementor-missing-dynamic-tags](https://user-images.githubusercontent.com/7768009/118149955-0d2c8600-b3e0-11eb-8c9a-a42e50630860.jpg)

**Comment by DorShahar** [comment]
Hi @mcrowell 
Thanks for reaching out.
* If the Pro license been expired - this is a bug.
* If the Pro license is disconnected - this is normal behavior. 

The logic is - any user with a license (active or expired) has access to the Pro feature. 

What is your case? ( so we could understand if there is a bug) 
Thanks

**Comment by mcrowell** [comment]
@DorShahar Thanks for the info.
In this case it was a client who had an expired license.

**Comment by DorShahar** [comment]
Thanks, @mcrowell  , 
We will check it out.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
