### ISSUE TITLE
Serious compatibility issues with Safari and Firefox

### ISSUE THREAD

**Issue by galooshkin** [elementor/elementor#14955]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by galooshkin** [comment]
Browsing from Safari and firefox causes unacceptable bugs.
In this site and page specifically:
Popups does not open automatically, links does not open popups, fonts not loading, links open multiple tabs.
Elementor does not seems to answer or provide any answer to that.


Anyone had luck with solving those?

Thanks


Link: https://www.welcometotherepublic.org/index.php/work/islandsinthenet/

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.33
	PHP Version: 7.3.27
	PHP Max Input Vars: 2000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6.2
	Site URL: https://www.welcometotherepublic.org
	Home URL: https://www.welcometotherepublic.org
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Custom Breakpoints for Elementor
		Version: 1.0.9
		Author: Jewel Theme

	Custom Post Type UI
		Version: 1.8.2
		Author: WebDevStudios

	Duplicator
		Version: 1.4.0
		Author: Snap Creek

	Dynamic Content for Elementor
		Version: 1.12.4
		Author: Dynamic.ooo

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.1.0
		Author: Elementor.com

	Jetpack by WordPress.com
		Version: 9.5
		Author: Automattic

	Master Addons for Elementor (Pro)
		Version: 1.5.6.2
		Author: Jewel Theme

	SEOPress
		Version: 4.4.0.7
		Author: SEOPress

	TranslatePress - Extra Languages Add-on
		Version: 1.0.1
		Author: Cozmoslabs, Razvan Mocanu

	TranslatePress - Multilingual
		Version: 1.9.0
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	TranslatePress - SEO Pack Add-on
		Version: 1.3.5
		Author: Cozmoslabs, Razvan Mocanu


== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 


== Elementor - Compatibility Tag ==
	
	Custom Breakpoints for Elementor: header_not_exists
	Dynamic Content for Elementor: compatible
	Elementor Pro: compatible
	Master Addons for Elementor (Pro): header_not_exists

== Elementor Pro - Compatibility Tag ==
	
	Dynamic Content for Elementor: compatible

== Elements Usage ==
	
	archive : 2
		dyncontel-acfposts : 2
		heading : 1
	footer : 2
		divider : 4
		heading : 5
		icon : 17
		image : 8
	header : 5
		heading : 1
		icon : 10
	page : 10
		button : 3
		divider : 4
		dyncontel-acfposts : 2
		dyncontel-post-nextprev : 5
		dyncontel-template : 2
		global : 2
		heading : 39
		image : 235
		spacer : 13
		text-editor : 29
	popup : 53
		divider : 18
		dyncontel-acfposts : 33
		heading : 33
		html : 1
		icon : 38
		image-carousel : 31
		nav-menu : 1
		spacer : 20
		text-editor : 18
	section : 32
		dce_add_to_calendar : 1
		divider : 22
		dyncontel-acf : 23
		dyncontel-acfposts : 8
		dyncontel-content : 8
		dyncontel-featured-image : 7
		dyncontel-post-nextprev : 2
		dyncontel-title : 7
		gallery : 1
		heading : 15
		icon : 3
		image : 2
		spacer : 5
		text-editor : 6
		theme-post-content : 3
		theme-post-title : 3
	widget : 0
		button : 929
		dyncontel-post-nextprev : 144
	wp-post : 2
		button : 2
		dce-dynamicposts-v2 : 4
		divider : 4
		dyncontel-acf : 6
		dyncontel-acfposts : 1
		dyncontel-template : 3
		dyncontel-title : 1
		global : 1
		heading : 5
		icon-box : 5
		image : 10
		spacer : 1
		text-editor : 15
		theme-post-featured-image : 2
	wp-page : 9
		divider : 5
		dyncontel-acfposts : 4
		dyncontel-template : 2
		flip-box : 56
		heading : 19
		html : 2
		image : 201
		spacer : 4
		text-editor : 8
	single-post : 15
		accordion : 2
		button : 3
		dce-dynamicposts-v2 : 2
		divider : 16
		dyncontel-acf : 56
		dyncontel-acfposts : 9
		dyncontel-content : 2
		dyncontel-featured-image : 1
		dyncontel-template : 16
		dyncontel-title : 11
		flip-box : 8
		gallery : 1
		global : 8
		heading : 24
		html : 4
		icon : 2
		icon-box : 5
		image : 96
		ma-image-hotspot : 6
		spacer : 10
		text-editor : 6
		theme-post-content : 1
		theme-post-featured-image : 13
		theme-post-title : 1
	single-page : 1
		divider : 1
		dyncontel-acf : 3
		heading : 2
		theme-post-content : 2
		theme-post-title : 1


== Log ==
	
JS: showing 12 of 12JS: 2021-02-18 14:05:40 [error X 15][https://www.welcometotherepublic.org/wp-content/plugins/master-addons-pro/assets/js/isotope.js?ver=1.5.6.2:11:1258] Cannot read property \'length\' of null 
JS: 2021-02-18 16:25:21 [error X 3][https://www.welcometotherepublic.org/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:13600] Syntax error, unrecognized expression: .elementor-6690.elementor > .elementor-inner > .elementor-section-wrap > .#fx 
JS: 2021-02-18 16:32:34 [error X 7][https://www.welcometotherepublic.org/wp-content/plugins/dynamic-content-for-elementor/assets/js/paypal.min.js?ver=1.12.0:3:300] paypal is not defined 
JS: 2021-02-18 17:09:07 [error X 1][https://www.welcometotherepublic.org/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:31670] Cannot read property \'style\' of null 
JS: 2021-02-18 18:45:16 [error X 6][https://www.welcometotherepublic.org/wp-content/plugins/master-addons/assets/js/isotope.js?ver=1.5.6.2:11:1249] t is null 
JS: 2021-02-18 19:34:03 [error X 1][https://www.welcometotherepublic.org/wp-content/plugins/master-addons/assets/js/isotope.js?ver=1.5.6.2:11:1249] can\'t access property \"length\", t is null 
JS: 2021-02-22 11:28:46 [error X 1088][https://www.welcometotherepublic.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read property \'clone\' of null 
JS: 2021-02-22 11:28:48 [error X 57][https://www.welcometotherepublic.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read property \'changestop\' of null 
JS: 2021-02-22 16:39:44 [error X 22][https://www.welcometotherepublic.org/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.1.1:2:80913] Routes: `theme-builder-publish/triggers` is already registered. 
JS: 2021-02-22 16:49:59 [error X 5][https://www.welcometotherepublic.org/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:33347] Cannot set property \'selected\' of undefined 
JS: 2021-02-23 16:32:59 [error X 1][https://www.welcometotherepublic.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3716\") has already been destroyed and cannot be used. 
JS: 2021-02-23 18:41:25 [error X 1][https://www.welcometotherepublic.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2564\") has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2021-02-18 15:48:50 [warning X 7][/home/welcomet/public_html/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/home/welcomet/public_html/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-18 16:36:51 [notice X 13][/home/welcomet/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-18 17:09:56 [notice X 36][/home/welcomet/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-02 11:04:45 [error X 1][/home/welcomet/public_html/wp-content/plugins/elementor-pro/modules/popup/module.php::98] Uncaught Error: Call to undefined method Elementor\Core\Kits\Documents\Kit::save_display_settings_data() in /home/welcomet/public_html/wp-content/plugins/elementor-pro/modules/popup/module.php:98
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/welcomet/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/welcomet/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/welcomet/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /home/welcomet/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /home/welcomet/public_html/wp-admin/admin-ajax.php(184): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-29 11:28:34 [error X 2][/home/welcomet/public_html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php::133] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /home/welcomet/public_html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php:133
Stack trace:
#0 /home/welcomet/public_html/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(151): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#1 /home/welcomet/public_html/wp-content/plugins/elementor/includes/frontend.php(192): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#2 /home/welcomet/public_html/wp-includes/class-wp-hook.php(287): Elementor\Frontend->init_render_mode('')
#3 /home/welcomet/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /home/welcomet/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /home/welcomet/public_html/wp-includes/template-loader.php(13): do_action('template_redire...')
#6 /home/welcomet/public_html/wp-blog-header.php(19): require_once('/home/welcomet/...')
#7 /home/welcomet/public_html/index.php(17): require('/home/we [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 8 of 82021-03-11 11:49:25 [info] dynamic-content-for-elementor::dce_updater Started 
2021-03-11 11:49:25 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Start  
2021-03-11 11:49:25 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_remove_option_api_array Finished 
2021-03-11 11:49:25 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Start  
2021-03-11 11:49:25 [info] Dynamic Content For Elementor/Upgrades - _v_1_12_4_dce_tokens_html_tag_default Finished 
2021-03-11 11:49:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic Content For Elementor',
  'from' => '1.12.0',
  'to' => '1.12.4',
)]
2021-03-11 11:49:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic Content For Elementor',
  'from' => '1.12.0',
  'to' => '1.12.4',
)]
2021-03-11 11:49:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.1.1',
  'to' => '3.1.4',
)]

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* **One issue per thread**

Without it, we simply can't help.

Thanks.
