### ISSUE TITLE
Elementor Pro editor cant loading

### ISSUE THREAD

**Issue by talol987** [elementor/elementor#14957]
**Hey, I got an issue in my website with Elementor Pro plugin, the editor is not loading and I cant change nothing and some elements are broken. Tried to disable all plugins then enable one by one, it seems that only Elementor Pro is not working.**

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.8
	MySQL version: MariaDB Server v10.4.18
	PHP Version: 7.4.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://momi-pinuim.ussl.co.il
	Home URL: https://momi-pinuim.ussl.co.il
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Extended
		Version: 0.8.8.3
		Author: ACF Extended

	Autoptimize
		Version: 2.8.4
		Author: Frank Goossens (futtta)

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Custom Icons for Elementor
		Version: 0.3.1
		Author: Michael Bourne

	Duplicate Page
		Version: 4.4
		Author: mndpsingh287

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Extras for Elementor
		Version: 2.2.51
		Author: Namogo

	Header Footer Code Manager
		Version: 1.1.10
		Author: 99robots

	Imagify
		Version: 1.9.14
		Author: WP Media

	Mobile Contact Bar
		Version: 2.0.7
		Author: Anna Bansaghi

	PowerPack Lite for Elementor
		Version: 2.3.4
		Author: IdeaBox Creations

	Rank Math SEO
		Version: 1.0.63
		Author: Rank Math

	Real-Time Find and Replace
		Version: 4.0.2
		Author: Marios Alexandrou

	WeSafe by uPress
		Version: 1.7.2
		Author: uPress

	WP Rocket
		Version: 3.2.5
		Author: WP Media

	WP Sitemap Page
		Version: 1.6.4
		Author: Tony Archambeau

== אלמנטור - Compatibility Tag ==
	
	Custom Icons for Elementor: header_not_exists
	Elementor Pro: compatible
	Extras for Elementor: compatible
	PowerPack Lite for Elementor: compatible

== אלמנטור פרו - Compatibility Tag ==
	
	Extras for Elementor: compatible
	PowerPack Lite for Elementor: compatible

== Elements Usage ==
	
	archive : 3
		archive-posts : 2
		heading : 3
		shortcode : 3
		text-editor : 3
	footer : 1
		divider : 1
		form : 1
		heading : 1
		icon-list : 1
		image : 1
		menu-anchor : 1
		shortcode : 2
		text-editor : 2
	header : 1
		icon-list : 2
		nav-menu : 2
		text-editor : 2
		theme-site-logo : 2
	section : 5
		divider : 1
		form : 1
		heading : 1
		icon-list : 1
		menu-anchor : 1
	single : 2
		heading : 2
		icon : 1
		icon-box : 1
		shortcode : 2
		star-rating : 1
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-post : 20
		call-to-action : 1
		divider : 6
		form : 1
		google_maps : 1
		heading : 10
		icon-box : 4
		icon-list : 1
		image : 4
		text-editor : 41
		video : 2

== Log ==
	
Log: showing 6 of 62021-05-15 16:50:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.2.3',
  'to' => '3.3.0-dev4',
)]
2021-05-15 21:23:31 [notice] Re-migrate 3.0.0 globals: Start 
2021-05-15 21:23:31 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2021-05-15 21:23:31 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2021-05-15 21:23:31 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2021-05-15 21:23:31 [notice] Re-migrate 3.0.0 globals: End 

PHP: showing 2 of 2PHP: 2021-05-15 21:23:31 [notice X 1][/home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-15 21:25:14 [error X 1][/home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor-extras/modules/posts/widgets/posts-base.php::60] Uncaught Error: Class 'ElementorPro\Modules\QueryControl\Controls\Group_Control_Related' not found in /home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor-extras/modules/posts/widgets/posts-base.php:60
Stack trace:
#0 /home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor-extras/modules/posts/widgets/posts.php(291): ElementorExtras\Modules\Posts\Widgets\Posts_Base->register_query_content_controls()
#1 /home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1926): ElementorExtras\Modules\Posts\Widgets\Posts->_register_controls()
#2 /home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(485): Elementor\Controls_Stack->init_controls()
#3 /home/momipinu/domains/momi-pinuim.ussl.co.il/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(148): Elementor\Controls_Stack->get_stack()
#4 /home/momipinu/domains [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
