### ISSUE TITLE
Problem after updating Elementor

### ISSUE THREAD

**Issue by TheSinistro** [elementor/elementor#14951]
After updating Elementor, the website became broken and only display text instead of the previous content of the page.
Can anyone check this and five some help?

Website: https://www.hzeventos.com.br/
The problem is only in the index, the other pages seems to be fine.

**Comment by shilo-ey** [comment]
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).


And see if the issue still persists.

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
