### ISSUE TITLE
Please add Thank you page design feature to elementor theme builder.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14954]
It would be great if we could design a WooCommerce Thank you page with elementor.
This feature is currently available in the jet woobuilder plugin. It would be great if we had it in elementor. Just like the 404 page that already exists.
Please check. Thank you

**Comment by shilo-ey** [comment]
I merged this issue with #5383, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
