### ISSUE TITLE
Please add advanced shopping cart menu widget to elementor.Very important

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14952]
I design a store theme with elementor, and I think elementor has done very poorly in this area.Because we, the designers of the store site, feel very lacking in the field of shopping cart menu. https://prnt.sc/12xl8pq
I think it would be great if elementor professionally added the shopping cart widget menu to elementor and expanded it.
WooCommerce plugin has this widget for elementor by default. But it does not have a good user interface at all and is not user friendly.
I ask elementor developers to add this widget to elementor as soon as possible.This widget is very important for elementor and its place in elementor is very empty.
Please share your opinion in this regard.

Thank you

**Comment by paauserrat** [comment]
I will also vote for this! Actualy, not only for the cart widget improvement but also for all e-commerce related things! Elementor should allow us to customize every woocommerce page without the need of Crocoblock!

**Comment by 79ho3ein** [comment]
Crocoblock plugins are unique. Along with elementor, they can be used to build powerful websites. Unfortunately, crocoblock has also done poorly in this area.
I hope to see this widget in elementor soon. Because elementor gives us more and better personalization.
I also hope that elementor developers will comment on this.
thanks.

**Comment by alexcumbers** [comment]
This is not for elementor to add this, it's for eCommerce platforms.

**Comment by paauserrat** [comment]
> This is not for elementor to add this, it's for eCommerce platforms.

But elementor must allow us to fully customize every aspect of the cart, which doesn't

**Comment by 79ho3ein** [comment]
Yes, exactly

**Comment by avivu** [comment]
Hello @79ho3ein  and @paauserrat,
We are currently improving our WooCommerce components, such as the Menu Cart widget and much more. 
We will update you with more information later on.

Thank you for your feedback,
Aviv

**Comment by paauserrat** [comment]
> Hello @79ho3ein  and @paauserrat,
> We are currently improving our WooCommerce components, such as the Menu Cart widget and much more. 
> We will update you with more information later on.
> 
> Thank you for your feedback,
> Aviv
> 

Will you include woocommerce page customizations with elementor? 😊

**Comment by 79ho3ein** [comment]
> Hello @79ho3ein and @paauserrat,
> We are currently improving our WooCommerce components, such as the Menu Cart widget and much more.
> We will update you with more information later on.
> 
> Thank you for your feedback,
> Aviv

So elementor will add the menu cart widget?
Or will you update the menu cart of the WooCommerce plugin?

**Comment by avivu** [comment]
Hi @paauserrat,
We are focus on improving the WooCommerce experience. We will update you about the changes later on.

Hi @79ho3ein,
We already have a Menu Cart widget - You can check it under the WooCommerce plugins.
We are currently improving the widget capabilities to offer more design options.

**Comment by 79ho3ein** [comment]
@avivu 
excellent. Can we share our ideas with you to improve this feature?

**Comment by avivu** [comment]
@79ho3ein 

Sure, any suggestion is welcome.
It will be appreciated if you will write them down in one comment so everything will be clear.

**Comment by fabianenzensperger** [comment]
+1

Oh yes, WooCommerce widgets are unfortunately very outdated and getting on in years. A refresh and significantly more functions would be very desirable.

It's frustrating that you just can't change the icon from the shopping cart widget to your own without CSS. 🙈

**Comment by 79ho3ein** [comment]
@avivu 
Thank you, you are unique ...
I will definitely send my ideas.
Is it just clear when the menu cart widget will be updated?
Do you have time for that?
thanks

**Comment by avivu** [comment]
@79ho3ein 
Your welcome.
We are working on that so that it will be released in the next few months, but I don't have an exact time for that.

**Comment by 79ho3ein** [comment]
excellent.
I am currently using the power pack plugin shopping cart menu. I hope to get rid of this plugin soon.
Good luck

**Comment by 79ho3ein** [comment]
hi @avivu 
Good time...
Do you have any new information about the new shopping cart menu feature?
We will be happy if we are aware of this important feature.
Thank you for your efforts

**Comment by fabianenzensperger** [comment]
> hi @avivu
> Good time...
> Do you have any new information about the new shopping cart menu feature?
> We will be happy if we are aware of this important feature.
> Thank you for your efforts


Watch this: https://youtu.be/zUBG27llWKQ

**Comment by 79ho3ein** [comment]
@fabianenzensperger 
thanks bro

**Comment by fabianenzensperger** [comment]
> @fabianenzensperger
> thanks bro

With pleasure.

The menu cart widget was not specifically mentioned in the video, but the video only mentioned the highlights. And I can't imagine ignoring this existing widget which URGENTLY needs a revision.

Stay tuned and enjoy being that active. Sometimes you must take feeling on the tooth the Elementor team or how someone says it.

**Comment by 79ho3ein** [comment]
@fabianenzensperger 
In any case, I hope in the near future we will be able to build very large store sites with elementor. I love elementor.

**Comment by avivu** [comment]
Hi @79ho3ein ,
As @fabianenzensperger mentioned, the video highlights the main features that will be released in the near future,
but don't worry - the Menu Cart widget will get a facelift also :)

**Comment by 79ho3ein** [comment]
> Hi @79ho3ein ,
> As @fabianenzensperger mentioned, the video highlights the main features that will be released in the near future,
> but don't worry - the Menu Cart widget will get a facelift also :)

Thank you for your efforts. Good luck

**Comment by fabianenzensperger** [comment]
> Hi @79ho3ein ,
> As @fabianenzensperger mentioned, the video highlights the main features that will be released in the near future,
> but don't worry - the Menu Cart widget will get a facelift also :)


Perfect! Thank you. I‘m excited. 😜

**Comment by 79ho3ein** [comment]
I hope this feature is added as soon as possible to get rid of the power pack plugin...

**Comment by fabianenzensperger** [comment]
> I hope this feature is added as soon as possible to get rid of the power pack plugin...


New feature is the next months or according to the video this year. 🤗

**Comment by 79ho3ein** [comment]
@avivu 
Excuse me, does the shopping cart menu come with an elementor or elementor pro update?

**Comment by fabianenzensperger** [comment]
> @avivu
> Excuse me, does the shopping cart menu come with an elementor or elementor pro update?


Since all WooCommerce widgets are only in the Pro version, I think this question is superfluous. 😉

**Comment by 79ho3ein** [comment]
> > @avivu
> > Excuse me, does the shopping cart menu come with an elementor or elementor pro update?
> 
> Since all WooCommerce widgets are only in the Pro version, I think this question is superfluous. 😉

Yes that's right.

**Comment by projektorius96** [comment]
Am I not the only one who experiences this [BUG] ?
I hope this request will bugfix the issue shared below as well, can't wait for it! 🔢 
[reference to elementor/issues/15451](https://github.com/elementor/elementor/issues/15451)

**Comment by 79ho3ein** [comment]
According to the developers elementor, the shopping cart menu widget will be updated soon.
Although I'm not interested in the power pack plugin and I do not recommend it to anyone, I suggest that if you can not wait for the update, use the power pack plugin shopping cart widget. It has a very high level of personalization.

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!

**Comment by fabianenzensperger** [comment]
> This feature has been implemented in Elementor Pro 3.4.0
> 
> Feel free to update
> 
> Thanks!


Jup, thanks. Please don't forget the custom icon in the near(!) future. 👀

**Comment by 79ho3ein** [comment]
friends, I could not get the beta version due to technical problems. But now that I have installed the official version, I have a problem.
**After adding and removing products from the cart several times, the display of the number of products disappeared!**
Have you experienced this problem?
