### ISSUE TITLE
Elementor Editor goes blank not working

### ISSUE THREAD

**Issue by selvasankars** [elementor/elementor#14969]
We use Elementor Pro plugin on our website to build pages. It goes blank on a couple of pages white trying to edit them.
When we checked the browser console, following error are thrown.
1. You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors
2. InvalidValueError: not an instance of HTMLInputElement (maps.googleapi)
3. TypeError: elementor.helpers.validateHTMLTag is not a function (from Elementor common.min.js)

When we tried to find the cause, found that Elementor works fine on deactivating the Element pack plugin. However, we need the Element pack plugin. 

Could you help us to find a solution ?

![Clipsal-Elementor-Error](https://user-images.githubusercontent.com/62884308/118477736-a3d4ac00-b72c-11eb-9ebf-fac9d9a14bad.png)
[ErrorsFound-OnConsole.pdf](https://github.com/elementor/elementor/files/6493295/ErrorsFound-OnConsole.pdf)
[Plugins-Clipsal.pdf](https://github.com/elementor/elementor/files/6493296/Plugins-Clipsal.pdf)
[system-info-staging.clipsalsolar.com-17-05-2021.txt](https://github.com/elementor/elementor/files/6493303/system-info-staging.clipsalsolar.com-17-05-2021.txt)

**Comment by shilo-ey** [comment]
Hi @selvasankars 

Thanks for reporting

According to the details you shared it's indeed sounds like a conflict with Elements pack plugin.

We suggest you to make sure you are using the latest version of that plugin and if the issue persists contact the plugin's author and let them know about it.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
