### ISSUE TITLE
Form submissions - can't middle/scroll mouse click to open submission in a new tab

### ISSUE THREAD

**Issue by euene** [elementor/elementor#14967]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In the Form submissions table (/wp-admin/admin.php?page=e-form-submissions) it's not possible to middle click (using the mouse scroll button) on either the email address or "View" link in the "Main" column of the table.

This is because neither the email address `<a>` tag or the "View" `<a>` tag have a proper `href` attribute and the actual opening of the submission is done only with JS with no fallback.

The email address href attribute will just go to https://example.com/SUBMISSION_ID_NUMBER (which is a 404 as such a page usually won't exist) while the "View" link just goes to "#".

There needs to be a way for submissions to open in a new URL as middle click to open new tab is a common UX convention that's currently broken - there has to be a way to quickly open new tabs with many submissions.

The email address & View Links href attributes have to be changed to:
https://example.com/wp-admin/admin.php?page=e-form-submissions#/SUBMISSION_ID_NUMBER

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

WordPress 5.7

Only plug-ins active:
Elementor 3.2.3
Elementor Pro 3.2.2

Active theme:
Hello Elementor 2.3.1

Server:
PHP 8.0.5
Apache/2.4.46
MariaDB 10.5.8

@shilo-ey

**Comment by Aviad-Herman** [comment]
This is great input @euene, thanks.
I will look into this.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.4.0

Feel free to update

Thanks!

**Comment by shilo-ey** [comment]
Update: this feature will be introduced in v3.5.0 and not in v3.4.0 as mentioned.

Thanks.

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!
