### ISSUE TITLE
Hidden in tablet and mobile functionality is not working at the two exact points

### ISSUE THREAD

**Issue by webmaster-adcom** [elementor/elementor#14968]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I use the default breake points for my websites. At the 2 exact points (767px and 1025px) the hidden functionality is not working.
In this image you can see that i have two navigation menus and the width of the screen is 1025px. However one of them must be invisible.
![1](https://user-images.githubusercontent.com/84316503/118467132-d28a5c80-b703-11eb-9b59-282e45e9b5c1.png)

when I change the screen width to the 1024px it is working ok.
![2](https://user-images.githubusercontent.com/84316503/118467331-fe0d4700-b703-11eb-8bb7-50169d40a9ef.png)

This is the same issue for the 767px. If I change the default breake points to the 769px and 1025px then everything will be ok. You can check [atto.at](https://www.atto.at) for this issue, also you can check the [dignus.adcom.at](https://dignus.adcom.at/) for the case when i changed the default breake ponts.

## Steps to reproduce

- Change the screen size from 1026px to 1024px

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

- PHP Version: 7.4.14
- WordPress Version: 5.7.2
- Theme: GeneratePress
- Elementor 3.2.3
- Elementor Pro 3.2.2

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.** Plus, we need to see how you configure the hidden elements. 
* Isolating the problem.
* **System info**.
* One issue per thread

Without it, we simply can't help.
You are welcome to contact our support team. 

Thanks.

**Comment by webmaster-adcom** [comment]
Hi,
Can u just check this website. 
[https://www.elalce.es/](https://www.elalce.es/)
This is one of the top 10 websites created by elementor and introduce by you [here](https://elementor.com/blog/showcase-april-2021/).
Use firefox and make the width of the windows 1025px. The same issue which i had in my websites. There will be 2 navigation menu (desktop mode and mobile mode). The navigation menu which used by me or here is the default widget by the elementor. Tghis issue is produces in firefox not in chrome.

**Comment by theavic** [comment]
Is there an update on this issue, since it still appears to be reoccuring
