### ISSUE TITLE
add customization for all widget

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#14966]
- [x] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

What problem is your feature request going to solve? Please describe
Solve the problem of setting up and designing any widget

Description
Add the ability to customize any widgets, add or remove some widget settings, for example, I want to add another button for a form or a call to action widget ... or add a header for a list with icons and the ability to customize their styles

Alternatives
Like unlimited widget

P.S. In general, it would be nice to be able to connect your codes for certain functions, for example, parallax effects or animation of both appearances and hover. All this will help you create unique solutions without giving money to other developers.

**Comment by DorShahar** [comment]
Hi @promocot 
Please look on our [developer docs](https://developers.elementor.com/register-widget-controls/). You can register new controls as you wish.

Thanks
