### ISSUE TITLE
Allow shortcodes in custom attributes

### ISSUE THREAD

**Issue by besweeet** [elementor/elementor#14974]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When providing a custom attribute, it would be extremely convenient if you can use shortcodes or other variables.

For example, I manually add `aria-label|Click to open [post_title_shortcode_here] (opens in a new window)` to links to have proper accessibility. Since shortcodes don't work, I can't automatically include post titles in `aria-label` tags.

**Comment by DorShahar** [comment]
Hi @besweeet 
You can do it with custom JS which targets the element with the relevant attribute end trigger what's needed.
At this moment, we are keeping the attributes as it is. 

Thanks
