### ISSUE TITLE
An excellent suggestion for the elementor form widget, please check.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14989]
Yesterday, I was designing a survey form for a store site with elementor, but I noticed a lack of functionality in it.I will describe it and hope you add it in future updates.
In this form, I asked the user for the field, city, province, name and contact number.
But the user who has registered on the site must enter the complete information. And this will be boring for the user.
It would be great if we could make the elementor form fields dynamic.
This means that if the user has registered on the site, its name will be automatically placed in the username field.
As well as the city, province and its contact number.
Please consider this possibility.The ability to dynamize forms will be great.

thanks

**Comment by Aviad-Herman** [comment]
This is a great suggestion.
Please check if this answers your need:
Advanced --> Default Value --> Dynamic tag --> User info

If it doesn't, feel free to re-open the thread.

![image](https://user-images.githubusercontent.com/73067562/118665110-b4ebee80-b7fa-11eb-93bd-3e10be7be4e6.png)
