### ISSUE TITLE
Some suggestions for developing menu cart widget (# 14952)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14988]
@avivu 
Here are some suggestions for developing this widget. I hope it helps you.
1- Please add the ability to insert the desired icon to this widget.Like inserting an SVG icon https://prnt.sc/132qmn9
2- Please add a feature so we can choose to open the menu cart from the right or the left(Optional)
3- Ability to fully edit the title, image and price of selected products : https://prnt.sc/132qubs
4- Ability to move the image left or right : https://prnt.sc/132qw3o
5- Ability to change the number of products as + - : https://prnt.sc/132qxf2
6- Please place the buttons at the bottom : https://prnt.sc/132r08h
7- Ability to full width for buttons : https://prnt.sc/132r3ht
8- please Enable animation with menu cart buttons : https://prnt.sc/132r6hh
9- Ability to apply the desired width for the menu cart : https://prnt.sc/132r8mi
10- Full edit Close menu cart section : https://prnt.sc/132radb
11- Complete edit of the menu cart title section : https://prnt.sc/132rcvt
12- Ability to display the number of products as follows: : https://prnt.sc/132rfnj (In the desired location)
13- Possibility of custom menu card design, if the product is not selected. https://prnt.sc/132rgzp
14- When the menu cart opens, the space around it darkens. Just like the pop-up in elementor https://prnt.sc/132rjow

Please check these items. They are very necessary. Thanks to the elementor team

**Comment by avivu** [comment]
Thank you @79ho3ein for these suggestions. We will take a look and address them if possible.

I merged this issue with #14952, which is on the same subject, to deal with it more efficiently. 
Please feel free to continue the conversation there.

Thank you!
