### ISSUE TITLE
Glitch display dark mode - Kit Library

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#14981]
Pay attention to the display of tags at the bottom left in the template preview
![ui glitches](https://user-images.githubusercontent.com/56270626/118614323-e6939400-b7bf-11eb-94b9-7ea7dfe7eab6.PNG)

**Comment by avivu** [comment]
Hello @rodolphebertozzo 

Thank you for your comment.
We will address this issue in one of the upcoming releases.

Thank you,
Aviv

**Comment by rodolphebertozzo** [comment]
It also concerns the other elements of the page after having looked at them in more detail
![Uploading ui glitches.PNG…]()

**Comment by rodolphebertozzo** [comment]
It also concerns the other elements of the page after having looked at them in more detail
![ui glitches](https://user-images.githubusercontent.com/56270626/118653049-74cf4080-b7e7-11eb-92f5-dbed5f659ea7.PNG)

**Comment by avivu** [comment]
@rodolphebertozzo 
The dark mode in the Kit Library is not yet executed.
We will address this in the upcoming releases.

Again, thank you!

**Comment by rodolphebertozzo** [comment]
fix in 3.3.0-dev14
