### ISSUE TITLE
A few suggestions to improve the elementor form widget.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14990]
1- In multi-step form, the Hover animation only works on the submit button.That is, it does not work on the before and after buttons.It can be said that this is a bug.
2- Please add the possibility of shading the forms. https://prnt.sc/132t38g
3- Please add active mode to the fields. Take the desired style until the user clicks on the desired field, such as taking a shadow or changing the background color
4- Please add an animation feature for the multi-step form. To move the user to the next or previous page of the form, as a slider or other items.
5- Please add a feature so that we can display our desired text to the user to display the error.This is very, very important. https://prnt.sc/132t9qy

thanks

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* **One request per thread**

This can help us to track it and prioritze.
Thanks.
