### ISSUE TITLE
Please add the dropdown widget to elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15000]
Undoubtedly one of the widgets that elementor needs is the dropdown widget.
This widget is currently available in the element pack plugin. But we prefer to have this widget in elementor.
I hope to see this widget in elementor soon.

thanks.

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
