### ISSUE TITLE
Please add the ability to design a loading page to elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15001]
One of the most important parts of the site that is used in many sites today is the loading page. https://prnt.sc/133b1g3
With this feature, the user feels less tired while waiting for the page to load.
It would be great if we could design this page in elementor.

Suggestions for implementing this feature:
It is better to design this page, like page 404 in elementor theme builder.And as we design the 404 page, we can also design the loading page.
Using the lottile animation widget, we will be able to create unique loading pages.
There is currently a plugin for this feature, but it is not optimal at all and makes the site heavy.
It would be great if you could add this feature to elementor.

Does the elementor team have a plan to release this feature?
Can we wait for it this year?

thanks

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #14449 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
