### ISSUE TITLE
Widget - disable Position Absolute on small screens

### ISSUE THREAD

**Issue by betagoo** [elementor/elementor#15003]
There is no icons Phone, Tablet, Desktop next to widget Position
Is this possible to add feature to **disable Position Absolute** on small screens?
It is convenient for there to be such a function instead code:
`@media (max-width: 1025px) {
    selector {
        position: initial !important;
    }
}`

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
