### ISSUE TITLE
Please add a dedicated user panel to elementor.(Important offer)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15013]
I design shop templates with elementor. Unfortunately, in the user panel section, there are big problems due to the use of various user panel plugins.And this part, that is, the user panel on a site designed with elementor, is very poor and of poor quality.

My suggestion is to add a dedicated professional user panel to the hello elementor theme that is fully editable.
This feature would be great. It will also be a big step for elementor.
In my opinion, a dedicated user panel is more necessary for elementor than anything else.

Please share your opinion. Thanks

**Comment by DorShahar** [comment]
Hi @79ho3ein 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
