### ISSUE TITLE
Problem with /wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0

### ISSUE THREAD

**Issue by elviajemehizoami** [elementor/elementor#15017]
Hi.

I have a bug in my website with this code. 

/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0

I read in another post that it fix it updating elementos to v3.2.3 but in my case the bug continue.

I need fix it.

Thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
