### ISSUE TITLE
Problem with /wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0 #15017

### ISSUE THREAD

**Issue by elviajemehizoami** [elementor/elementor#15018]
Hi.

I have a bug in my website with this code.

/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0

I read in another post that it fix it updating Elementor to v3.2.3 but in my case the bug continue.

I need fix it.

Thanks

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.28
	PHP Version: 7.4.16
	PHP Max Input Vars: 20000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://elviajemehizoami.com
	Home URL: https://elviajemehizoami.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.0.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

== Active Plugins ==
	AdSensei B30
		Version: 1.9.9.9
		Author: <a href="https://blogger3cero.com/nuevo-adsensei-b30" target="_blank">Alberto Del Águila, Jaime Sempere, Dean Romero</a>

	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	Akismet Anti-Spam
		Version: 4.1.9
		Author: Automattic

	Easy Affiliate Links
		Version: 3.5.0
		Author: Bootstrapped Ventures

	Easy Table of Contents
		Version: 2.0.17
		Author: Steven A. Zahm

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	FAQ Schema For Pages And Posts
		Version: 2.3.0
		Author: Krystian Szastok (SEO Consultant)

	GP Premium
		Version: 2.0.2
		Author: Tom Usborne

	Imagify
		Version: 1.9.14
		Author: WP Media

	Perfmatters
		Version: 1.7.1
		Author: forgemedia

	Revive Old Posts
		Version: 9.0.1
		Author: revive.social

	Schema Pro
		Version: 2.5.2
		Author: Brainstorm Force

	Simple CSS
		Version: 1.1.1
		Author: Tom Usborne

	WE-Varnish-Cache
		Version: 0.1
		Author: David

	WP Comment Policy Checkbox
		Version: 0.3.2
		Author: Fco. J. Godoy

	WP Rocket
		Version: 3.8.8
		Author: WP Media

	Yoast SEO
		Version: 16.3
		Author: Team Yoast

	Yuzo - Related and List post (Pro)
		Version: 6.2.36
		Author: Lenin Zapata

== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	archive : 68
		archive-posts : 1
		breadcrumbs : 3
		heading : 4
		posts : 3
		text-editor : 9
		theme-archive-title : 1
	footer : 1
		heading : 4
		icon-list : 1
		image : 3
	header : 1
		image : 2
		nav-menu : 1
		search-form : 2
		social-icons : 1
	section : 8
		button : 2
		heading : 7
		icon-list : 2
		image : 1
		text-editor : 3
	single : 2
		breadcrumbs : 1
		heading : 3
		icon-list : 1
		post-comments : 1
		post-info : 2
		share-buttons : 1
		theme-post-content : 1
		theme-post-title : 1
	wp-post : 0
		heading : 1
		shortcode : 3
		text-editor : 5
	wp-page : 2
		button : 3
		divider : 1
		form : 2
		heading : 15
		image : 11
		posts : 2
		text-editor : 12

== Log ==
	
PHP: showing 2 of 2PHP: 2020-09-19 17:35:46 [notice X 7][/home/elviajem/public_html/elviajemehizoami.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-06 13:16:09 [notice X 4][/home/elviajem/public_html/elviajemehizoami.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 402021-02-16 07:02:05 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-16 07:02:05 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-16 07:02:05 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-16 07:02:05 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-16 07:02:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-16 07:02:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-03-03 08:49:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.2',
)]
2021-03-05 07:08:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.2',
  'to' => '3.1.3',
)]
2021-03-05 07:09:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-11 06:45:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-16 11:53:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]
2021-03-25 16:31:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]
2021-04-23 07:56:00 [info] elementor::elementor_updater Started 
2021-04-23 07:56:00 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-23 07:56:00 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-23 07:56:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-23 07:56:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-28 08:18:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-05 08:06:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-06 09:02:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]

**Comment by 79ho3ein** [comment]
+1
Yes, this error is also present on my website.

**Comment by centralplexus** [comment]
I have the same issue on a website that also uses the GeneratePress theme, if that has got anything to do with it. Editor won't open in either normal or safe modes.

**Comment by shilo-ey** [comment]
What is the issue you are referring to?

Please describe

**Comment by 79ho3ein** [comment]
hello @shilo-ey 
I do not know what the reason is but this error has recently occurred in elementor. This error is seen in gt metrix and even in Chrome browser inspact. https://prnt.sc/14dclca
This error did not exist before. At first I thought this error only exists on my site. But I saw that others also reported this problem.
I hope I have described this enough.

Thank you for your attention

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
