### ISSUE TITLE
Please add the ability to shade the form field to the elementor form widget.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15020]
Unfortunately in elementor it is not possible to shade the form fields. Please check this feature and add it to elementor if possible.
Also please add active mode to the form widget.
In this way, when the user clicks on a field and is filling it, its background color or border changes.
Of course, the active mode must be fully customizable.

please check. thanks

**Comment by promocot** [comment]
and label color change to, this image example for better UI/UX

![aesthetic-accessibility-paradox](https://user-images.githubusercontent.com/66754335/118992643-7dfa1200-b98d-11eb-99ba-85607911435d.png)
from uxmatarerials.com

**Comment by promocot** [comment]
and I think if add attention field is the increased trust, reference 

![image](https://user-images.githubusercontent.com/66754335/118996831-df6fb000-b990-11eb-9199-9df37892a187.png)

**Comment by 79ho3ein** [comment]
@promocot 
Yes. This is a great idea.
In this case, we can test for users.

**Comment by Aviad-Herman** [comment]
Hi,
Let's try to keep each issue focused on one problem at a time, it's impossible to track and solve issues if we don't.
I'm not sure what you mean by shading but it is possible to change the field background color.
I'm going to close this issue for now, Reopen it if you can attach examples of field shading.

Regarding the "increased trust" you can just add any message you want as a text widget or icon list right under the form.

**Comment by promocot** [comment]
> Hi,
> Let's try to keep each issue focused on one problem at a time, it's impossible to track and solve issues if we don't.
> I'm not sure what you mean by shading but it is possible to change the field background color.
> I'm going to close this issue for now, Reopen it if you can attach examples of field shading.
> 
> Regarding the "increased trust" you can just add any message you want as a text widget or icon list right under the form.

I am not the author, however, I have attached an example of the form in question above, the first picture
