### ISSUE TITLE
Please add a feature to the social network icon widget, so that we can color each icon separately.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15027]
Please add a feature to the social network icon widget, so that we can color each icon separately. https://prnt.sc/135uj3g
This feature is much needed.
Thanks

**Comment by Aviad-Herman** [comment]
![image](https://user-images.githubusercontent.com/73067562/120123326-d9f73e80-c1b6-11eb-8984-e9bd6728d092.png)

You can
