### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Add support lottie animation for button, icon box for better UI/UX (Merged with #20444)

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15025]
- [x] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hello, for what this option? You have a video where you show how to create a button with animation, but for example, I am not a motion designer and I cannot create an entire animated button, but I found a good animation for example a call and I want to add it to my buttons, this will help me create a more interactive button ... Also, adding this option to the icon, I solve the problem of optimizing the DOM, since I do not add 3 widgets but 1, and if we take into account that at least 3 or more benefits are added with icons, then this is multiplied according to mathematical progressions. I believe that this should be added not only as a widget but also as an option for choosing what to use the icon or lottie animation and where to select the link or local

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔃  This request is being merged with #20444.

Which is on the same subject. 

For this reason, I'm closing the comments, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
