### ISSUE TITLE
A question from elementor developers.Please reply.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15039]
I apologize for asking this question again.But in the past I did not get the answer to this question. I hope I get the answer.
I wanted to ask if elementor has a program to add the ability to design a loading page to elementor? https://i.gifer.com/KMu0.gif
If yes, is the release date specified?
There is currently a plugin for this feature (https://wordpress.org/plugins/loading-page/) but it is not optimal at all. I hope this feature will be added to elementor soon.

Thanks to the elementor team.

**Comment by d19dotca** [comment]
You've referred to a loading page multiple times prior:

- https://github.com/elementor/elementor/issues/14614 (this is the open one that you should be putting your comments in with regards to loading pages)
- https://github.com/elementor/elementor/issues/15001 (this one was closed and merged with the first one)

**Comment by DorShahar** [comment]
Hi @79ho3ein - @d19dotca  is right. Opening a new issue on the same topic will just caused an overload on the GitHub issues. 
There is no release date. 

Merged issue

I merged this issue with  #14614, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
