### ISSUE TITLE
Copy & Paste Not working on Safari

### ISSUE THREAD

**Issue by jaysonwebtel** [elementor/elementor#15038]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Copy and Paste is no longer functioning correctly in Safari. It often pastes incorrect items and doesn't correctly load items / all items of a section into the clipboard. This does not happen in other browsers.

## Steps to reproduce

In Safari, when editing a page using Elementor
Right Click, Select Copy
Go to a new section and paste the copies items. 
Incorrect items appear or nothing appears.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by jaysonwebtel** [comment]
Safari Version 14.1 (16611.1.21.161.6)
Mac OS Big Sur 11.3.1

**Comment by alexcumbers** [comment]
Have you cleared safari cache / restarted safari? Demonstrate it via a Loom - loom.com

**Comment by DorShahar** [comment]
Hi @jaysonwebtel 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:
- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
