### ISSUE TITLE
Report a bug in the lottie widget.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15032]
Lottie animations do not load when I upload my site with a duplicator.
And I have to add each of them back to the site and it takes a long time.
After the transfer is displayed as follows : https://prnt.sc/136sqxz

Please check this bug. thanks

**Comment by DorShahar** [comment]
Hi @79ho3ein 
Please contact the Plugin author to investigate the problem, since it didn't been imported with Elementor.

Thanks.
