### ISSUE TITLE
Report an elementor error.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15040]
This error has been observed on elementor websites for a few days. I checked this problem on several elementor websites and it existed.  https://prnt.sc/137ui6h
Please fix this problem. Because it has slowed down the website and mobile friendly errors.

thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
