### ISSUE TITLE
Version 3.3.0-dev7

### ISSUE THREAD

**Issue by AgeTM** [elementor/elementor#15049]
Dear Elementar Team,

I get this message:  
Deprecated : Elementor \ Utils :: is_ajax is obsolete since version 2.6.0 ! Use wp_doing_ajax () instead. in /var/www/vhosts/agetm.com/httpdocs/wp-includes/functions.php on line 4861

On my website:
https://agetm.com/en/urlaubsziele/island/

I checked the functions.php but found no solution.

Afterwards I was trying to post a new article wit Elementor and got this message:
Update failed. The response is not a valid JSON response.

How can I get back to normal version, please?

Thanks a lot

## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.44
	PHP Version: 7.3.5
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://agetm.com
	Home URL: https://agetm.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 128M
	Permalink Structure: /%category%/%postname%/
	Language: de-DE
	Timezone: 0
	Admin Email: platux@live.com
	Debug Mode: Active

== Theme ==
	Name: soledad
	Version: 7.9.2
	Author: PenciDesign
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

== Active Plugins ==
	Contact Form 7
		Version: 5.4.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.3.0-dev7
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Envato Market
		Version: 2.0.6
		Author: Envato

	Google Language Translator
		Version: 6.0.8
		Author: Translate AI Multilingual Solutions

	Koko Analytics
		Version: 1.0.27
		Author: ibericode

	MC4WP: Mailchimp for WordPress
		Version: 4.8.4
		Author: ibericode

	NextGEN Gallery
		Version: 3.10
		Author: Imagely

	oAuth Twitter Feed for Developers
		Version: 2.3.0
		Author: Liam Gladdy (Storm Consultancy)

	Penci PageSpeed Optimizer
		Version: 2.0.4
		Author: PenciDesign

	Penci Portfolio
		Version: 2.7
		Author: PenciDesign

	Penci Recipe
		Version: 3.0
		Author: PenciDesign

	Penci Review
		Version: 2.6
		Author: PenciDesign

	Penci Shortcodes & Performance
		Version: 3.0
		Author: PenciDesign

	Penci Slider
		Version: 1.1
		Author: PenciDesign

	Penci Soledad Demo Importer
		Version: 3.0
		Author: PenciDesign

	Shortcodes Ultimate
		Version: 5.10.0
		Author: Vladimir Anokhin

	Vafpress Post Formats UI
		Version: 1.7
		Author: vafpress

	Weather Atlas Widget
		Version: 1.2.1
		Author: Yu Media Group d.o.o.

	WPForms Lite
		Version: 1.6.7
		Author: WPForms

== Elementor - Compatibility Tag ==
	

== Elements Usage ==
	
	wp-post : 9
		penci-portfolio : 9
		penci-text-block : 1
		text-editor : 5

== Log ==
	
Log: showing 20 of 352020-09-10 09:08:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-09-10 09:08:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-09-10 09:08:51 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Start  
2020-09-10 09:08:51 [info] Elementor/Upgrades - _v_3_0_5_re_move_space_between_widgets_to_kit Finished 
2020-09-10 09:08:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '3.0.7',
)]
2020-09-18 13:07:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.9',
)]
2020-09-24 19:46:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2020-10-04 19:00:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-11-29 17:54:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.14',
)]
2021-01-10 22:26:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.16',
)]
2021-02-04 21:47:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.1',
)]
2021-04-03 19:59:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.4',
)]
2021-04-24 20:37:25 [info] elementor::elementor_updater Started 
2021-04-24 20:37:25 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-24 20:37:25 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-24 20:37:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-24 20:37:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-05-07 12:52:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.3',
)]
2021-05-09 20:29:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.3.0-dev4',
)]
2021-05-22 09:57:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0-dev4',
  'to' => '3.3.0-dev7',
)]

JS: showing 1 of 1JS: 2020-09-15 15:40:09 [error X 1][https://agetm.com/wp-content/themes/soledad/inc/elementor/assets/js/editor.js?ver=7.3.2:1:26889] null is not an object (evaluating \&#039;t.getEditModel\&#039;) 

PHP: showing 3 of 3PHP: 2021-01-14 23:16:43 [notice X 1][/var/www/vhosts/agetm.com/httpdocs/wp-content/plugins/elementor/includes/api.php::160] Undefined index: pro_widgets [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-06 17:04:01 [notice X 1][/var/www/vhosts/agetm.com/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-17 14:47:02 [notice X 1][/var/www/vhosts/agetm.com/httpdocs/wp-content/plugins/elementor/modules/system-info/reporters/user.php::113] Undefined index: HTTP_USER_AGENT [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>

**Comment by udidol** [comment]
Hi @AgeTM,
`Utils::is_ajax()` is a deprecated static method not used anywhere in Elementor any more.
It seems like your theme or one of your plugins is calling this method. Try to disable all other plugins and check if this issue persists, that's how you will find your culprit.

Good luck!
