### ISSUE TITLE
Mobile menu incompatibility with latest wp-rocket delay js update

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#15044]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
the new Delay js feature has completely broken the mobile menu

## Steps to reproduce

1. Install wp-rocket 3.9.
2. Enable delay js
3. Check mobile menu on frontend after clearing caches
4. See that its broken 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Hi @jazir5 
Thanks for reaching out. 
Please check it with wp-rocket, due to your description. 
If needed, their developers have our contact point for any questions if needed.

Thanks.
