### ISSUE TITLE
The error message on a Select Field will put out of place the select drop-down arrow.

### ISSUE THREAD

**Issue by xoich** [elementor/elementor#15042]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The error message on a Select Field will put out of place the select drop-down icon. The icon stays on the right margin of the form while the field shrinks to the left to make space for the error. 

## Steps to reproduce

Add an error message to a select field with `$ajax_handler->add_error`

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by 79ho3ein** [comment]
+1

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
