### ISSUE TITLE
Cannot edit text 

### ISSUE THREAD

**Issue by omkar-tenkale** [elementor/elementor#15041]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Clicking text to edit it does nothing except printing this in console

TypeError: "t is undefined"
    rearrangeButtons https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    initialize https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    Backbone 19
    setPage https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    renderTab https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    activateTab https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    activateTab https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    registerTabRoute https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    to https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    route https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    apply https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    c https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    onEditRequest https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    Backbone 4
    onClickEdit https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    Backbone 2
common.min.js:2:116333
    consoleError https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    onCatchApply https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    c https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    run https://my.site/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.2.3:2
    onEditRequest https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    Backbone 4
    onClickEdit https://my.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.2.3:2
    Backbone 2

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by omkar-tenkale** [comment]
Makes sense
