### ISSUE TITLE
Suggestion for countdown widget.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15047]
Please add a feature to this widget(https://prnt.sc/139jwrx) so that we can place our favorite icon between times.
For example, I wanted to put a (:) symbol between times, but it was not possible. https://prnt.sc/139k3yr

Please add this feature to its widget. Thanks

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* **Prerequisites.**
* **Description and examples.**
* One request per thread

Thanks.
