### ISSUE TITLE
The update tab does not take the background color.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15053]
I wanted to give the tab the background color update mode but it does not take color. While this was not the case before.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
