### ISSUE TITLE
Media carousel slide animation on click

### ISSUE THREAD

**Issue by tissi-2** [elementor/elementor#15059]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When clicking on an media carousel item, a slide animation is fired that moves the clicked item to the left side although the option "pause on interaction" is selected "on".

`function(t) {
  return e.onLinkClick(t)
}`

frontend.min.js?ver=3.2.3:2:45393

**Describe the solution you'd like**
If clicked the item should stay where it is - "on click prevent default".

**Describe alternatives you've considered**
Using a plugin from an other company.

**Comment by SYLondon** [comment]
I'm facing the same issue here. Seems new as I use media carousel often and can't remember facing this before. I'm running Hello Elementor with Elementor Version 3.2.4 and Elementor Pro Version 3.3.0 on Wordpress 5.7.2

I also noticed someone reported it here with a good demo of the issue: https://github.com/elementor/elementor/issues/11393

**Comment by DorShahar** [comment]
Hi 
We try to solve a few days ago, but the infrastructure change was to risky.
See my comments at #11465

Thank you for your understanding

**Comment by tissi-2** [comment]
Dear elementor team,

seeing such comments makes me angry. We all pay a lot for this product and we deserve to get widgets without glitches. We give our very best to help you enhancing this product and so do you... go back into the office and solve that problem - there is always a way to get it working!
