### ISSUE TITLE
When I click edit popup after loading template it opens edit section controls on the sidebar

### ISSUE THREAD

**Issue by natebhan** [elementor/elementor#15077]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I go to modify a popup template, it loads fine, but then I can't access the template popup editor. I right click in the popup and click "edit popup" then instead of the edit popup section I get the edit section loading in the sidebar. I have tried different templates, but it still always only shows the edit section NOT the edit popup. I am using the most current versions of wp, elementor and elementor pro. 

## Steps to reproduce

Go to templates -> add template -> popup -> name template -> load design -> right click -> click edit popup -> loads edit section NOT edit popup. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.29
	PHP Version: 7.4.15
	PHP Max Input Vars: 3200
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://webapp.wildcatcatalyst.com
	Home URL: https://webapp.wildcatcatalyst.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.4.6
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

== Active Plugins ==
	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	header : 1
		image : 1
		nav-menu : 1
	section : 1
		icon : 1
		theme-site-logo : 1
	wp-page : 1
		uael-table : 1
	single-post : 1
		template : 1
		theme-post-content : 1


== Log ==
	
PHP: showing 2 of 2PHP: 2021-05-24 21:56:03 [notice X 1][/home/dh_rcepiv/webapp.wildcatcatalyst.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-24 22:01:50 [notice X 1][/home/dh_rcepiv/webapp.wildcatcatalyst.com/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
![edit_popup_not_working](https://user-images.githubusercontent.com/17461780/119417895-13f6ab00-bcb4-11eb-914f-21ec468509b8.JPG)

**Comment by DorShahar** [comment]
Hi @natebhan 
Thanks for reaching out.

We don't have "Edit Popup" so the flow you descrobe is unclear for us. 
Although - what you describe (without "edit popup") is normal behavior. Any template in Elementor (includes Popup) is built using sections, and this is the reason the controls showing sections (As the parent of the element). 

If you wish to go to Popup Settings, click on the cog button on the lower left side of the panel. See the first note in our doc [here](https://elementor.com/help/popups/).

Thanks
