### ISSUE TITLE
WP Theme Compatibility with Elementor Pro

### ISSUE THREAD

**Issue by qlacapra** [elementor/elementor#15071]
Hello! We contacted Elementor support late last year because one of our Pro widgets was experiencing a glitch. Elementor Support told us at the time this was likely due to our base website theme not being compatible with Elementor Pro. Now, they are deferring to you to confirm this issue. I just want confirmation before my nonprofit spends $2,000-$3,000 to switch a theme.

**Comment by Aviad-Herman** [comment]
Hey, 
I trust the support know what their saying but if you want please send over more information and I'll take a look:

- Screenshots
- Elementor version
- Theme

**Comment by qlacapra** [comment]
Hi there,
We first noticed a problem when one of our pro widgets stopped working and the advice I got at the time was that our theme was incompatible with Pro, but I am having trouble getting Elementor to confirm that before we pay a couple thousand to change the theme. We are a nonprofit so I’m hoping to get a definitive answer before we go down that road. That said, I don’t have screenshots of an error because it was just something relayed to us. Here is the other information:

System Info
Server Environment
Operating System:
Linux
Software:
Apache
MySQL version:
Percona Server (GPL), Release '36', Revision '7e403c5' v5.7.33-36
PHP Version:
7.3.28-1+ubuntu18.04.1+deb.sury.org+1
PHP Max Input Vars:
10000
PHP Max Post Size:
100M
GD Installed:
Yes
ZIP Installed:
Yes
Write Permissions:
All right
Elementor Library:
Connected
WordPress Environment
Version:
5.7.1
Site URL:
https://ciesandiego.org
Home URL:
https://ciesandiego.org
WP Multisite:
No
Max Upload Size:
50 MB
Memory limit:
512M
Permalink Structure:
/%year%/%monthnum%/%day%/%postname%/
Language:
en-US
Timezone:
America/Tijuana
Admin Email:
***@***.***
Debug Mode:
Inactive

Theme
Name:
Sage Starter Theme
Version:
8.5.4
Author:
Roots
Child Theme:
No
If you want to modify the source code of your theme, we recommend using a child theme<https://go.elementor.com/wordpress-child-themes/>.

**Comment by Aviad-Herman** [comment]
Hey,
I'm really sorry but I'm not familiar with Sage Starter Theme.
In any case without screenshots, videos etc there is really nothing I can do.
