### ISSUE TITLE
External Custom Font

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#15086]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
n/a

**Describe the solution you'd like**
I want the custom font to be loaded from an external source, [eg cloudflare](https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css)

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
