### ISSUE TITLE
Report an important bug in loading fonts and symbols in elementor (custom icons and fonts). please check it. This is very important

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15098]
When we load and use a number of icons on the site, everything is fine and not a problem.
But when we move the site to another domain with the duplicator plugin, none of the icons are displayed،And we have to reload all the icons, and that's very time consuming.
There is also this problem loading fonts ...

Please solve this problem. thanks

**Comment by 79ho3ein** [comment]
Also lottie animation files

**Comment by DorShahar** [comment]
Hi 
Please contact the "duplicator" plugin developers, since this is kind of problem is relating to them. 

Thanks.
