### ISSUE TITLE
Elementor Forms don't respect WordPress Blacklist

### ISSUE THREAD

**Issue by tobias992** [elementor/elementor#15095]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Would be really nice if you can add support for WordPress internal Blacklist to Forms widget. This would help to reduce Spam. Otherwise an internal Blacklist feature in Forms widget would be also nice.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
