### ISSUE TITLE
Google Maps widget API request error

### ISSUE THREAD

**Issue by Michmela** [elementor/elementor#15090]
The elementor google maps widget isn't working and is rejecting the request. 

![image](https://user-images.githubusercontent.com/39302720/119558219-6b267980-bda1-11eb-95cf-7fabbcf2b6c5.png)

**Comment by black-eye** [comment]
Same here

**Comment by Merlin1987** [comment]
Same here

**Comment by masterchrister** [comment]
Same for me as well.

![image](https://user-images.githubusercontent.com/686054/119564957-a3ca5100-bda9-11eb-87e3-684d60906c34.png)

**Comment by Wait-Ace** [comment]
I got the same error on my Elementor sites 
Working okay on sites without Elementor

**Comment by mcrowell** [comment]
+1 - Odd, it seems to be "random" on my end. Certain browsers will cause the error and other browsers are fine. It looks to be a problem on Google's end?

**Comment by jfriedley715** [comment]
API key configuration issue?

**Comment by chkserv** [comment]
Got the same issue here.

**Comment by alexspyr** [comment]
Same issue on multiple sites, started in the last couple hours

**Comment by alexspyr** [comment]
Seems to be an issue with Google maps. Saw the same error on multiple non Elementor sites

**Comment by thepowbe** [comment]
Same here on all the elementor sites, embedding via iframe works fine.

**Comment by imandings** [comment]
It appears Elementor is using v2 of the Maps API. v2 was deprecated overnight. Hopefully they fix this soon.

Maps JavaScript API v2 (May 19, 2010 - May 26, 2021)
Version 2 of the Maps JavaScript API is deprecated as of May 19, 2010, and will be turned off on May 26, 2021. As a result, your site's v2 maps will stop working, and will return JavaScript errors. To avoid any inconvenience, we strongly recommend migrating your site to the Maps JavaScript API v3 before May 26, 2021. Learn more about upgrading Your Maps JavaScript API Application from v2 to v3.
https://developers.google.com/maps/deprecations#maps_javascript_api_v2_-

**Comment by mcanyucel** [comment]
same here, hope this gets fixed soon.

**Comment by 79ho3ein** [comment]
+1
This error has occurred to me as well.

**Comment by Webtica** [comment]
+1 Same issue

**Comment by nicmare** [comment]
unbelievable elementor sticked to v2 of google maps. this is ridiculous

**Comment by shilo-ey** [comment]
We are working on a fix and we will release it soon.

Thanks for letting us know.

PR for reference: #15099

**Comment by ahmeddhaoui** [comment]
+1

**Comment by black-eye** [comment]
> We are working on a fix and we will release it soon.
> 
> Thanks for letting us know.
> 
> PR for reference: #15099

Looking at PR, does it mean that the map won't work without the API key?

**Comment by mcanyucel** [comment]
> 
> 
> > We are working on a fix and we will release it soon.
> > Thanks for letting us know.
> > PR for reference: #15099
> 
> @shilo-ey: Looking at PR, does it mean that the map won't work without the API key?

Looks that way. In PR I have noticed a new section in dashboard>integration section where the api key will be entered but TBF I just scanned it in a glance.

**Comment by shilo-ey** [comment]
> > We are working on a fix and we will release it soon.
> > Thanks for letting us know.
> > PR for reference: #15099
> 
> @shilo-ey: Looking at PR, does it mean that the map won't work without the API key?

This is how Google maps API v3 works, so unfortunately yes.

**Comment by alexnl** [comment]
Getting this in Firefox (left) and Chrome (right):

![image](https://user-images.githubusercontent.com/317587/119688280-d90c8880-be15-11eb-95ee-4f78fcd06b24.png)

**Comment by real-bluefair** [comment]
My maps has returned, I think it is ok now.

**Comment by ianlee** [comment]
Assuming everything gets approved asap, would the fixes be published to a hotfix patch or will we have to wait for the next update?

**Comment by chkserv** [comment]
This has now been fixed in Elementor v3.2.3

**Comment by siatrisx** [comment]
Not fixed in Elementor v3.2.3, This is what I have and it is not working. 40 websites not working on different servers.

**Comment by chkserv** [comment]
Sorry, I mean 3.2.4

**Comment by ianlee** [comment]
eta on 3.2.4?

**Comment by Merlin1987** [comment]
For me it's working again on Elementor 3.2.3

**Comment by d19dotca** [comment]
> eta on 3.2.4?

Version 3.2.4 is already out, I can see this for about a dozen websites I manage right now.

**Comment by leandromenezes** [comment]
For me it's working in some moments, but stopping working again. V3.23

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.4

Feel free to update!

**Comment by 79ho3ein** [comment]
@DorShahar 
excuse me ...
Do we have to have an Api key to display Google Maps?
Isn't it easy to show the map to users like before?
The map will not be displayed until we enter the code?

**Comment by d19dotca** [comment]
> @DorShahar 
> 
> excuse me ...
> 
> Do we have to have an Api key to display Google Maps?
> 
> Isn't it easy to show the map to users like before?
> 
> The map will not be displayed until we enter the code?

This isn't up to Elementor. It's Google's requirement, an API key must be used.

**Comment by webcoreinc** [comment]
Elementor no longer works with Google maps api. You will have to manually embed maps now.
