### ISSUE TITLE
JS Still not working for me

### ISSUE THREAD

**Issue by mguillou56** [elementor/elementor#15097]
I have Elementor v3.2.2 and I still have a problem with JS not working on my website.

For instance the links for this gallery don't work. I also couldn't implement MegaMenu extensions.

Can you help me please ?

https://polesante-kervignac.fr/#gallerylinks

Thanks and best regards.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bug reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
