### ISSUE TITLE
Elementor Google Maps Widget suddently stops working

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#15100]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Suddently my google maps widget from elementor stopped working. I tried to drag and drop a new widget and also changing the location but nothing works.
I'm using Elementor and Elementor Pro
Another user has reported this here: https://wordpress.org/support/topic/google-maps-widget-not-working-2/
![image](https://user-images.githubusercontent.com/73240206/119661850-01ee4700-be31-11eb-8937-4c3c99a310d5.png)

## Steps to reproduce
Drag and drop a google maps widget

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by nicmare** [comment]
why are you submitting something which is already known? https://github.com/elementor/elementor/issues/15090

**Comment by 79ho3ein** [comment]
It is discussed in #15090. Please close this request so they can better handle it. 
thanks

**Comment by amtone1** [comment]
Google Maps JavaScript API has been loaded directly without a callback. This is not supported and can lead to race conditions and suboptimal performance. For supported loading patterns please see https://goo.gle/js-api-loading
