### ISSUE TITLE
Elementor Version 3.3.0-dev8 / Pro Version 3.4.0-dev8 - Breaks the footer

### ISSUE THREAD

**Issue by riseandshineluke** [elementor/elementor#15105]
The columns in the footer are no longer top-aligned after updating to the latest beta versions. Using Astra free theme, and header and footer area designed in Elementor theme builder.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
