### ISSUE TITLE
Product Stock Widget not working

### ISSUE THREAD

**Issue by petranca** [elementor/elementor#15114]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

The product stock widget does not display stock status on the product page.

**Comment by avivu** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it, we simply can't help.

Thanks.
