### ISSUE TITLE
Compatibility issues with Elementor Pro and User Role Editor affecting the HTML widget contents

### ISSUE THREAD

**Issue by JeroenvanderPoll** [elementor/elementor#15116]
Hi,
I manage a corporate website and we use the plugin User Role Editor (https://wordpress.org/plugins/user-role-editor/) to create specific roles and permissions for the users managing the website. We noticed a compatibility issue when using Elementor Pro with User Role Editor.

## The Issue

Whenever a user with a user role, created using this plugin, edits or re-saves a page containing any HTML widget, parts of the contents of those widgets were removed. The issue happens when editing any of the content on the page. Even if the HTML element is untouched, if the page is saved the HTML widget contents are affected.

We added the following code to an HTML element:
`<!--HubSpot Call-to-Action Code --><span class="hs-cta-wrapper" id="hs-cta-wrapper-9654a023-a981-4f1a-8f09-3957785354a9"><span class="hs-cta-node hs-cta-9654a023-a981-4f1a-8f09-3957785354a9" id="hs-cta-9654a023-a981-4f1a-8f09-3957785354a9"><!--[if lte IE 8]><div id="hs-cta-ie-element"></div><![endif]--><a href="https://cta-redirect.hubspot.com/cta/redirect/7178226/9654a023-a981-4f1a-8f09-3957785354a9" ><img class="hs-cta-img" id="hs-cta-img-9654a023-a981-4f1a-8f09-3957785354a9" style="border-width:0px;" src="https://no-cache.hubspot.com/cta/default/7178226/9654a023-a981-4f1a-8f09-3957785354a9.png"  alt="Get a Quote"/></a></span><script charset="utf-8" src="https://js.hscta.net/cta/current.js"></script><script type="text/javascript"> hbspt.cta.load(7178226, '9654a023-a981-4f1a-8f09-3957785354a9', {"region":"na1"}); </script></span><!-- end HubSpot Call-to-Action Code -->`

When the page was edited by a user with a custom role, the code was reduced to:
`<!--HubSpot Call-to-Action Code --><span class="hs-cta-wrapper" id="hs-cta-wrapper-9654a023-a981-4f1a-8f09-3957785354a9"><span class="hs-cta-node hs-cta-9654a023-a981-4f1a-8f09-3957785354a9" id="hs-cta-9654a023-a981-4f1a-8f09-3957785354a9"><!--[if lte IE 8]&gt;<div id="hs-cta-ie-element"></div>&lt;![endif]--><a href="https://cta-redirect.hubspot.com/cta/redirect/7178226/9654a023-a981-4f1a-8f09-3957785354a9"><img class="hs-cta-img" id="hs-cta-img-9654a023-a981-4f1a-8f09-3957785354a9" style="border-width:0px" src="https://no-cache.hubspot.com/cta/default/7178226/9654a023-a981-4f1a-8f09-3957785354a9.png" alt="Get a Quote" /></a></span> hbspt.cta.load(7178226, '9654a023-a981-4f1a-8f09-3957785354a9', {"region":"na1"}); </span><!-- end HubSpot Call-to-Action Code -->`

## Steps to reproduce:

- Install Elementor Pro
- Create a page
- Add a piece of heading to the page
- Add an HTML widget with some HTML content or script.
- Install User Role Editor
- Create a specific role using the User Role Editor
- Create a new WordPress user and assign the newly created role.
- Login as the newly created user with the custom role
- Visit the page
- Edit the page with Elementor
- Edit the heading and save
- Visit the page and you will notice that the HTML element is broken.

## System Info

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.2
	MySQL version: Debian 10 v10.3.17
	PHP Version: 7.4.6
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Resolving timed out after 5000 milliseconds)

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://development-www.i3d.net
	Home URL: https://development-www.i3d.net
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Amsterdam
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

== Active Plugins ==
	404page - your smart custom 404 error page
		Version: 11.3.0
		Author: Peter Raschendorfer

	Admin Menu Editor
		Version: 1.9.10
		Author: Janis Elsts

	Advanced Custom Fields
		Version: 5.9.6
		Author: Elliot Condon

	Autoptimize
		Version: 2.8.4
		Author: Frank Goossens (futtta)

	BackupBuddy
		Version: 8.7.2.0
		Author: iThemes

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Broken Link Checker
		Version: 1.11.15
		Author: WPMU DEV

	Cookiebot | GDPR/CCPA Compliant Cookie Consent and Control
		Version: 3.10.1
		Author: Cybot A/S

	Custom Error Pages
		Version: 1.1
		Author: Jesin

	Custom Post Type UI
		Version: 1.9.1
		Author: WebDevStudios

	Display Posts
		Version: 3.0.2
		Author: Bill Erickson

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Duplicate Page
		Version: 4.4
		Author: mndpsingh287

	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Google Map Extended Pro
		Version: 1.1.7
		Author: InternetCSS

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	Favicon by RealFaviconGenerator
		Version: 1.3.20
		Author: Philippe Bernard

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 8.0.166
		Author: HubSpot

	Imagify
		Version: 1.9.14
		Author: WP Media

	iThemes Security Pro
		Version: 6.8.4
		Author: iThemes

	JetElements For Elementor
		Version: 2.5.7
		Author: Crocoblock

	JetEngine
		Version: 2.8.0
		Author: Crocoblock

	JetMenu
		Version: 2.0.9
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.11
		Author: Crocoblock

	Modern Events Calendar Lite
		Version: 5.19.1
		Author: Webnus

	Pre-Publish Checklist
		Version: 1.1.1
		Author: Brainstorm Force

	Redis Object Cache
		Version: 2.0.18
		Author: Till Krüss

	Reveal IDs
		Version: 1.5.4
		Author: Oliver Schlöbe

	Search Exclude
		Version: 1.2.6
		Author: Roman Pronskiy

	Simple Post Redirect
		Version: 1.6
		Author: Mohit Agarwal

	SVG Support
		Version: 2.3.18
		Author: Benbodhi

	WP External Links
		Version: 2.48
		Author: WebFactory Ltd

	WP Rocket
		Version: 3.8.2
		Author: WP Media

	WP Rollback
		Version: 1.7.1
		Author: Impress.org

	Yoast SEO Premium
		Version: 14.8
		Author: Team Yoast

== Elementor - Compatibility Tag ==
	
	Elementor Google Map Extended Pro: Compatibility not specified
	Elementor Pro: Compatible
	JetElements For Elementor: Compatible
	JetSearch For Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Compatible
	JetSearch For Elementor: Compatible

== Elements Usage ==
	
	archive : 15
		archive-posts : 1
		breadcrumbs : 3
		button : 7
		divider : 2
		global : 23
		heading : 56
		icon-box : 3
		image : 3
		nav-menu : 36
		posts : 13
		shortcode : 5
		spacer : 29
		template : 1
		text-editor : 5
		theme-archive-title : 1
	footer : 4
		button : 6
		divider : 3
		form : 3
		global : 8
		heading : 46
		image : 2
		nav-menu : 23
		social-icons : 3
		spacer : 11
	header : 6
		icon : 4
		image : 1
		jet-mega-menu : 2
		nav-menu : 4
		wp-widget-media_image : 5
	page : 30
		breadcrumbs : 10
		button : 18
		divider : 5
		eb-google-map-extended : 1
		global : 16
		heading : 149
		html : 1
		icon : 3
		icon-box : 16
		icon-list : 15
		image : 27
		jet-mega-menu : 3
		nav-menu : 23
		posts : 12
		search-form : 1
		shortcode : 9
		spacer : 45
		template : 16
		text-editor : 60
		theme-post-featured-image : 7
		toggle : 1
		video : 2
		wp-widget-media_image : 2
	section : 22
		breadcrumbs : 1
		button : 5
		divider : 1
		eb-google-map-extended : 1
		global : 5
		heading : 33
		icon-box : 9
		icon-list : 3
		image : 2
		nav-menu : 5
		search-form : 1
		shortcode : 6
		sitemap : 1
		spacer : 9
		text-editor : 13
	widget : 0
		breadcrumbs : 355
		button : 1174
		eb-google-map-extended : 25
		google_maps : 14
		heading : 320
		html : 6
		icon-box : 2
		icon-list : 21
		image : 44
		image-box : 168
		jet-ajax-search : 37
		jet-posts : 53
		nav-menu : 3
		share-buttons : 439
		shortcode : 2446
		sitemap : 1
		spacer : 15
		text-editor : 322
		video : 4
		wp-widget-gform_widget : 15
	wp-post : 41
		breadcrumbs : 49
		button : 5
		divider : 26
		global : 190
		heading : 906
		html : 13
		icon : 1
		icon-list : 50
		image : 34
		nav-menu : 100
		shortcode : 46
		spacer : 232
		table-of-contents : 7
		template : 178
		text-editor : 490
		theme-post-featured-image : 76
		toggle : 1
		video : 11
	wp-page : 82
		animated-headline : 2
		breadcrumbs : 38
		button : 57
		divider : 13
		global : 56
		heading : 435
		html : 14
		icon-box : 114
		icon-list : 30
		image : 105
		image-box : 4
		jet-posts : 2
		jet-table : 2
		menu-anchor : 1
		nav-menu : 28
		posts : 21
		search-form : 2
		shortcode : 128
		sitemap : 1
		spacer : 155
		tabs : 2
		template : 12
		text-editor : 164
		video : 1
	error-404 : 1
		button : 1
		heading : 1
		image : 1
		spacer : 1
		text-editor : 1

== Log ==
	
JS: showing 14 of 14JS: 2021-02-04 16:21:36 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3581\") has already been destroyed and cannot be used. 
JS: 2021-02-04 16:22:10 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view430\") has already been destroyed and cannot be used. 
JS: 2021-02-04 16:39:27 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view463\") has already been destroyed and cannot be used. 
JS: 2021-02-04 16:51:40 [error X 3][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view469\") has already been destroyed and cannot be used. 
JS: 2021-02-08 09:50:52 [error X 3][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view474\") has already been destroyed and cannot be used. 
JS: 2021-02-10 15:52:53 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view483\") has already been destroyed and cannot be used. 
JS: 2021-02-16 16:23:36 [error X 2][https://development-www.i3d.net/wp-content/plugins/jet-search/assets/js/jet-search.js?ver=2.1.9:93:14] Cannot read property \'isInit\' of undefined 
JS: 2021-03-05 10:07:33 [error X 2][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view507\") has already been destroyed and cannot be used. 
JS: 2021-03-05 15:07:29 [error X 8][https://development-www.i3d.net/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.1.1:2:36786] n is undefined 
JS: 2021-03-05 15:20:55 [error X 4][https://www.youtube.com/s/player/a09205f7/www-widgetapi.vflset/www-widgetapi.js:647:30] YouTube player element ID required. 
JS: 2021-03-05 15:32:29 [error X 5][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view441\") has already been destroyed and cannot be used. 
JS: 2021-03-12 10:47:12 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view446\") has already been destroyed and cannot be used. 
JS: 2021-03-12 15:42:09 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view448\") has already been destroyed and cannot be used. 
JS: 2021-03-15 13:45:52 [error X 1][https://development-www.i3d.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view488\") has already been destroyed and cannot be used. 

Log: showing 20 of 212021-03-16 07:44:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.4',
)]
2021-03-16 07:54:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.1.1',
)]
2021-03-16 07:56:11 [info] elementor-pro::elementor_pro_updater Started 
2021-03-16 07:56:11 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-03-16 07:56:12 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-03-16 07:56:12 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-03-16 07:56:13 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-03-16 07:56:13 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-03-16 07:56:14 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-03-16 07:56:14 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-03-16 07:56:14 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-03-16 07:56:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.1.1',
)]
2021-04-07 06:27:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.1',
)]
2021-05-20 13:15:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.3',
)]
2021-05-20 13:16:08 [info] elementor::elementor_updater Started 
2021-05-20 13:16:08 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-05-20 13:16:08 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-05-20 13:16:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.3',
)]
2021-05-20 14:06:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-27 10:17:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]

PHP: showing 7 of 7PHP: 2021-03-12 13:52:32 [notice X 223][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor-google-map-extended-pro/include/class.updater.php::25] Non-static method icss_eme\CodeAutoUpdate::prepare_request() should not be called statically [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-24 13:12:40 [notice X 14][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-01 09:31:19 [notice X 66][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-07 06:47:36 [notice X 79647][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor-google-map-extended-pro/widgets/eb-google-map-extended-widget.php::1688] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-22 10:02:05 [error X 3][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php::180] Uncaught Error: Call to a member function get_component() on null in /var/www/development-www.i3d.net/www/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php:180
Stack trace:
#0 /var/www/development-www.i3d.net/www/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php(68): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->set_preview_settings()
#1 /var/www/development-www.i3d.net/www/wp-content/plugins/elementor/includes/base/element-base.php(736): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->get_raw_data()
#2 /var/www/development-www.i3d.net/www/wp-content/plugins/elementor/includes/base/element-base.php(736): Elementor\Element_Base->get_raw_data()
#3 /var/www/development-www.i3d.net/www/wp-content/plugins/elementor/core/base/document.php(816): Elementor\Element_Base->get_raw_data()
#4 /var/www/development-www.i3d.net/www/wp-content/plugins/elementor/modules/usage/module.php(566): Elementor\Core\Base\Document->get_elements_raw_data()
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-23 15:36:07 [notice X 2][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor/includes/frontend.php::1221] Trying to get property 'post_excerpt' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-22 16:58:22 [notice X 1][/var/www/development-www.i3d.net/www/wp-content/plugins/elementor/modules/system-info/reporters/user.php::113] Undefined index: HTTP_USER_AGENT [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by Aviad-Herman** [comment]
Hi,
This is actually a WordPress safety mechanism that we comply with.
Most user roles are not authorized to add (or save) potentially harmful code.
I'm not familiar with User Role Editor but I think that if you are willing to take the security risk you can try giving all users this permission:

![image](https://user-images.githubusercontent.com/73067562/120123050-66a0fd00-c1b5-11eb-80c5-fb380384454d.png)

I haven't tested this but alternatively it might also be possible for an admin to use our custom code feature and / or create a global widget / template with the custom script and add them to the page. Worth a try.

Let me know if this doesn't work out and you need further assistance.

**Comment by JeroenvanderPoll** [comment]
Thank you Aviad for clarifying this!
