### ISSUE TITLE
Elementor incompatible with last Elementor Pro version message

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#15128]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

It's annoying but Elementor shows an incompatibility tag with Elementor Pro.
![image](https://user-images.githubusercontent.com/73240206/119959581-6a116a00-bfa4-11eb-994b-7ae4d6a2de71.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Aviad-Herman** [comment]
Thanks!
Fixed
