### ISSUE TITLE
Report a problem in the form widget. please check it.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15137]
In the form widget, after the user registers the information, the information entered by the user in the form remains until the user deletes it.
However, after submitting the form, the information entered in the form should not exist. Please resolve this issue.

thanks

**Comment by Aviad-Herman** [comment]
Hi @79ho3ein 
Unfortunately I can't understand what you mean.
When a form is submitted successfully all fields are cleared.
Please supply exact steps to reproduce.
