### ISSUE TITLE
A bug will occur if we load the svg icon into the button widget or icon list.please check (report bug)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15131]
When we load the svg format icon button or icon list widget, the appearance of these two widgets will be corrupted. These two widgets completely overlap with the svg format. Please solve this big problem. Thank

**Comment by Aviad-Herman** [comment]
Some SVG files come with embedded height / width attributes. If you can't find a "clean" SVG file you can also fix this by adding custom CSS to the button:

`selector svg {
    height: 1em;
}`
