### ISSUE TITLE
Urgent - Multiple rows in one section

### ISSUE THREAD

**Issue by qwer1234qwerq** [elementor/elementor#15133]
I am looking for a solution to the same problem mentioned here
https://github.com/elementor/elementor/issues/2218

See the following link for an illustration:
How with css can all columns be displayed in one row?
(Open the link and view a maximum width of 768).
It must be css that solves the issue with 2 divs, because there is no other way ...
https://jsfiddle.net/t7ku9c2q/

**Comment by Aviad-Herman** [comment]
Currently this is not possible with Sections, Inner Sections and Columns.
Depending on your specific use case it might be possible by changing the item's position to inline.
We are planning of providing more complex layouts in the future.
