### ISSUE TITLE
Feature request: Dynamic Tags for Global Colors

### ISSUE THREAD

**Issue by tizum** [elementor/elementor#15135]
I would like to be able to choose the global colors through a dynamic tag in the constructor, this would optimize my time and give my clients freedom to change more efficiently, as they would be visible for choice in the edition, as I am currently doing it is necessary to add the tag directly into the color settings individually.

![elementor sugestão](https://user-images.githubusercontent.com/6773491/120032010-f6855200-bfcf-11eb-932e-da9669627de5.jpg)

**Comment by Aviad-Herman** [comment]
Interesting concept @tizum , thanks for the input!

**Comment by tizum** [comment]
@Aviad-Herman 

could you analyze again?  with the amazing updates that have been happening... this new feature is going to look amazing.

I'm currently using Dynamics tags, but it's a very tiring process.

**Comment by Aviad-Herman** [comment]
So the request to have one place to edit your site's design system (including colors) that's easy enough for clients to edit without knowing elementor or having editor permissions?

**Comment by tizum** [comment]
The colors are currently attached here on the Global options page performed with JetEngine, however you need to do the configuration process every time, with the dynamic global option I would forward the request directly there, in the builder it would be wonderful to attach them to any widget.

![image](https://user-images.githubusercontent.com/6773491/127606714-529e0081-0f4e-45f2-a0ce-c098e02032a7.png)
![image](https://user-images.githubusercontent.com/6773491/127606892-ad052709-5f11-4705-9fda-59f97e5dc7d9.png)

**Comment by tizum** [comment]
Hello everyone, Elementor is increasingly standing out and becoming more dynamic.

Could you carefully review this request? I believe that the dynamic tag released here in the global colors would be very useful and would add more power to Elementor.

![image](https://user-images.githubusercontent.com/6773491/156868013-3610a79e-e779-4911-9de2-beab3c67414f.png)

**Comment by arielk** [comment]
Hi @tizum,

Sorry about that, but we initially thought there was a technical issue with adding this feature. I tested it in the last few hours and it seems okay for now (not tested yet).

I hope this will be included in the next version, you can follow this PR: https://github.com/elementor/elementor/pull/19598

Thank you very much for the feedback!

**Comment by tizum** [comment]
@arielk thank you very much, this resource will be magnificent

**Comment by dantetesta** [comment]
this is very important to us!  make it croco please!

**Comment by gerardreches** [comment]
Now that this has been added to Elementor 3.8, we would only need that we could also change the global color variable names for new colors that we add.

**Comment by arielk** [comment]
> Now that this has been added to Elementor 3.8, we would only need that we could also change the global color variable names for new colors that we add.

Just double click on the name and change it :)

**Comment by gerardreches** [comment]
> > Now that this has been added to Elementor 3.8, we would only need that we could also change the global color variable names for new colors that we add.
> 
> Just double click on the name and change it :)

I mean not the name of the color, but the name of the CSS variable generated.

**Comment by arielk** [comment]
> > > Now that this has been added to Elementor 3.8, we would only need that we could also change the global color variable names for new colors that we add.
> > 
> > 
> > Just double click on the name and change it :)
> 
> I mean not the name of the color, but the name of the CSS variable generated.

Please follow this issue: https://github.com/elementor/elementor/issues/12571

**Comment by elisandromoreira** [comment]
It didn't work with crocoblock's jetengine.

When I'm in the editor the colors appear as defined in the dynamic tags, but when I save the page, the colors don't appear on the frontend.

**Comment by oncps** [comment]
Realmente ... eu testei aqui com JetEngine, as cores mudam na cor global, aparece na tela do elementor e no widget que foi mudado a cor... mas quando salva .. nao aparece no front
