### ISSUE TITLE
Please add the ability to change the color of the icon in svg format to elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15132]
Unfortunately, it is not possible to change the color of svg icons in elementor.
Of course, this was possible in several elementor add-ons. But unfortunately there is no elementor in itself.
Please add a feature so that we can directly change the color of the svg icons in the elementor editor. Just like elementor bookcase icons.

thanks

**Comment by Aviad-Herman** [comment]
Hey, it should be possible.
If you encountered a specific case in which it doesn't, please supply exact steps to reproduce. Preferably a video.
