### ISSUE TITLE
Image widget can't align picture center or right after version 3.1.4.

### ISSUE THREAD

**Issue by BorisOrbis** [elementor/elementor#15139]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The images widget in elementor wont align center or right.
Tried it on the older version of Elementator (Version 3.1.4.), and everything was working as it should be. After the update, I wasn't able to align images center and right.
## Steps to reproduce

Open new page, insert picture and try to align to the center or the right.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Raspbian)
	MySQL version: Raspbian 9.0 v5.6.42-84.2
	PHP Version: 7.0.33-0+deb9u7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: http://192.168.1.48
	Home URL: http://192.168.1.48
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: hr
	Timezone: Europe/Zagreb
	Admin Email: bkugla@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: InteriorPress
	Version: 1.4.4
	Author: ThemeArile
	Child Theme: Yes
	Parent Theme Name: ArileWP
	Parent Theme Version: 2.7.5
	Parent Theme Author: ThemeArile

== User ==
	Role: administrator
	WP Profile lang: hr
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.43
		Author: ServMask

	Arile Extra
		Version: 2.5
		Author: ThemeArile

	Contact Form 7
		Version: 5.4.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.2.4
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	

== Elements Usage ==
	
	wp-post : 0
		google_maps : 1
		text-editor : 1
	wp-page : 11
		button : 1
		divider : 1
		heading : 4
		html : 2
		image : 2
		image-gallery : 1
		spacer : 2
		text-editor : 5

== Log ==
	
JS: showing 1 of 1JS: 2020-11-03 11:14:38 [error X 2][http://localhost/lightshade/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.12:2:229393] Cannot read property \&#039;map\&#039; of undefined 

Log: showing 11 of 112020-11-05 07:32:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2021-05-28 21:01:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.2.4',
)]
2021-05-28 21:01:52 [info] elementor::elementor_updater Started 
2021-05-28 21:01:53 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-05-28 21:01:58 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-05-28 21:01:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.2.4',
)]
2021-05-28 21:02:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.2.4',
)]
2021-05-28 21:02:03 [info] elementor::elementor_updater Started 
2021-05-28 21:02:03 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-05-28 21:02:05 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-05-28 21:02:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.2.4',
)]

</details>

## Picture
![FB_IMG_1622268354190.jpg](https://user-images.githubusercontent.com/50413711/120059934-e8c5e000-c054-11eb-9ed2-945b82d98062.jpg)

**Comment by Aviad-Herman** [comment]
Hi @BorisOrbis 
Thanks for the feedback.
Seems to be working fine on the latest version of Elementor and we haven't received any other complaints about this.
Chances are this bug is not caused by 3rd party plugins, themes, or manual CSS overrides.

If you update your plugin version and are still experiencing this issue, please let me know.

A few other things to help isolate the issue:
- Change your theme to "Hello Elementor"
- Turn off all other plugins
- Try using other images
- See if it happens on new pages
- Turn off all Elementor experiments
