### ISSUE TITLE
Please add a feature so I can link to the columns.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15140]
It would be great if you could add a feature so we could link to the columns. https://prnt.sc/13k8149
This feature is very important, but unfortunately elementor has not paid attention to it so far.
This is possible by using one of the elementor add-ons. But why shouldn't elementor itself have this feature?
Please review this request and add it to elementor if possible.

thanks

**Comment by Aviad-Herman** [comment]
Hey,
You can link to a column (or any other element) by giving it a CSS ID (it's under the advanced tab).

Than the link will be:
www.mywebsite.com/my-page/#my-id

![image](https://user-images.githubusercontent.com/73067562/120109717-4bad9900-c173-11eb-97c9-d5f393419e9a.png)
