### ISSUE TITLE
Add a way to set padding/margin only for one direction

### ISSUE THREAD

**Issue by ilearnio** [elementor/elementor#15155]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

In my theme style.css I have defined `padding-left` and `padding-right` to `.elementor-container`. And when from Elementor editor I need to set padding-top to that container I cannot set only padding-top. Because it sets `padding: 50px 0px 0px 0px`;

**Describe the solution you'd like**

Add a way to define only `padding-top`, `padding-bottom` etc separately. Same for `margin`.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
