### ISSUE TITLE
🔗 🔃  🚀 Feature Request: Use Lottie animation as a shopping cart icon (Merged to #15025)

### ISSUE THREAD

**Issue by ishnechmad** [elementor/elementor#15153]
Elementor now allows to use the SVG image as your shopping cart icon.

Is it possible to ask that we can place a Lottie animation there as a dynamic icon?

**Comment by 79ho3ein** [comment]
Which widget do you mean? WooCommerce Shopping Cart?

**Comment by ishnechmad** [comment]
> Which widget do you mean? WooCommerce Shopping Cart?

yes.

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔗 This request is being merged to #15025.

Which is on the same subject. 

For this reason, I'm closing the comments, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
