### ISSUE TITLE
Dynamic Favicons

### ISSUE THREAD

**Issue by liveonshuffle** [elementor/elementor#15151]
https://css-tricks.com/dynamic-favicons-for-wordpress/

Can y'all make this a site identity feature before someone else does?

Super cool!!! 

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aviad-Herman** [comment]
Hey @liveonshuffle!
Very cool request, thanks for letting us know!
Unfortunately this is super-niche so we will probably not implement this anytime soon.
Luckily power users like your self can always implement it personally with code.

Keep the good ideas coming! We really appreciate it!
