### ISSUE TITLE
Image caroussel widget

### ISSUE THREAD

**Issue by rute-carvalho** [elementor/elementor#15175]
I have created a image caroussel widget in my elementor page which apparently works fine in desktop (image below).

![1](https://user-images.githubusercontent.com/85176943/120338307-052f7a00-c2ec-11eb-8fbc-0fb198231af1.png)

But in responsive this widget causes the whole page to strech (image below), except for the smart slider in the beggining.

![2](https://user-images.githubusercontent.com/85176943/120341660-f9918280-c2ee-11eb-9726-db8e48e68483.png)

If I remove this widget from my elementor page everything goes back to normal.

All I did was add the widget to my page and the only settings I set up were: "Slides to show". "Slides to scroll", "Navigation" and of course I added the images. I didn't change any section or column settings.

Also there is this dark grey area that appears around the images that I can't get rid off.

![3](https://user-images.githubusercontent.com/85176943/120341168-8f78dd80-c2ee-11eb-9d9c-830a0ded35a3.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
