### ISSUE TITLE
Getting this error message:  Warning: Illegal string offset 'custom_css_post_id' in /home/SITENAME/public_html/wp-includes/theme.php on line 1063

### ISSUE THREAD

**Issue by FirstforNews** [elementor/elementor#15181]
Hi,

I wonder if someone can help me, I am a complete novice and I am getting this error message:  

Warning: Illegal string offset 'custom_css_post_id' in /home/SITENAME/public_html/wp-includes/theme.php on line 1063

I have redacted the site name with "SITENAME".  The error prevents the main menu from displaying within the site and instead I get this "ADD PRIMARY MENU" 

Any ideas how I can fix it? 

Many thanks and I look forward to hearing from you.

Regards,

Paul

**Comment by rami-elementor** [comment]
Hi Paul,

It looks like this is a WordPress issue, not and Elementor issue. Try asking at WordPress forums.
