### ISSUE TITLE
Section container 

### ISSUE THREAD

**Issue by abubacker7** [elementor/elementor#15189]
1. In section .elementor-container has max-width and flex and in column .elementor-widget-wrap element has padding to achieve spaces between columns while doing this content has spaces in left and right. To remove space left and right we need to add minus margin flex container like bootstrap row column it's not possible to minus margin to .elementor-container because its marin auto to center container to resolve this if you add flex property after .elemntor-container elementor content width will be same as container width.
2.  .elemntor-section > .elementor-container > .new-element for flex
<img width="1440" alt="Screenshot 2021-06-02 at 7 53 04 PM" src="https://user-images.githubusercontent.com/39765380/120502242-e01c3380-c3df-11eb-8258-32898862bbc9.png">

3. You see here content has in both left and right side

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
