### ISSUE TITLE
The image on the main page doesn't load when it's been replaced in elementor

### ISSUE THREAD

**Issue by dheahendra666** [elementor/elementor#15190]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

The first step
- Login WordPress
-Go to the main page that has been created
- Edit pages with elementor
-change old image with new image
- save

Second step
- Clear cache
- go to web main page url

Image doesn't change

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info
OS : Windows 10 Home Single Langguage 64 byte
Browser : Chrome Version 90.0.4430.212 (Official Build) (64-bit)
Wordpress : 5.7.2
Elementor : 

Operating System: | Linux | 
Software: | LiteSpeed | 
MySQL version: | MariaDB Server v10.3.28 | 
PHP Version: | 7.4.16 | 
PHP Max Input Vars: | 1000 |
PHP Max Post Size: | 8M | 
GD Installed: | Yes | 
ZIP Installed: | Yes | 
Write Permissions: | All right | 
Elementor Library: | Connected

</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
this my system environment link
https://pastebin.com/x6yCEEVv
</details>
@nicomollet @iamntz @ibndawood @rsiddall @pingram3541

**Comment by dheahendra666** [comment]
old image
![image](https://user-images.githubusercontent.com/85266536/120576326-c82ec900-c44c-11eb-97d6-988c08ec218b.png)
new image
![image](https://user-images.githubusercontent.com/85266536/120576398-e4326a80-c44c-11eb-8559-f96d286f04b2.png)

**Comment by nicomollet** [comment]
Why the mention?

**Comment by pingram3541** [comment]
Possibly still a caching issue but need more to go on.  You didn't really explain your cache-busting procedures so we don't know if you just cleared a plugin, your browser or what.

1) Many web hosts provide caching service like Cachewall - typically on by default
2) There could be caching via a DNS provider like Cloudflare
3) There could be caching plugins that need to be cleared
4) Your browser stores cache as well
5) If you use Chrome and are logged into a Google account, it also is known to cache content.

You can also debug Elementor pretty easily using many of the hooks such as the 'elementor/widget/render_content' hook.  You could simply write the entire output to a log file and verify the image widget is indeed providing the old url path vs the new one.  

If it is showing the new url path but the browser is still showing the old path, this is an indication of cache *somewhere* from init to grave of the http request.

If it is showing an old url path however, maybe your changes aren't actually saving, i.e. ajax failure or conflicting script etc. or maybe you indeed did find a bug and posting those results will help get it acknowledged and hopefully fixed.

**Comment by dheahendra666** [comment]
oke thats fixed,
one more please,

There is also a problem when I want to upload a different image using the
same image file name as the image file that has been uploaded, the new
image file does not load and only displays the old file with the same name.

Pada tanggal Jum, 4 Jun 2021 pukul 06.36 pingram3541 <
***@***.***> menulis:

**Comment by pingram3541** [comment]
Same issue, the old image is cached.  Change the file name and you force it to be downloaded for the first time.

**Comment by dheahendra666** [comment]
Thanks, I'll check it out.

**Comment by DorShahar** [comment]
Hi @dheahendra666  and @pingram3541  - thanks for helping each other! 
@dheahendra666  - if you have a new issue, please open a new one in case we need to investigate. 

Good luck
