### ISSUE TITLE
Please add image hover mode to the elementor image widget.Very important

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15199]
Please add a feature to the image widget to start scrolling the image by moving the mouse over the image.
This feature is extremely useful.Now to use such a feature we need to use the add-on. But why shouldn't there be such an important feature in elementor?
To see the details of this request, please see these two images (https://prnt.sc/13wogwp) on this website.
https://imagehoverpro.blocksera.com/
When you hover the mouse over the image, the image starts to scroll.

Please review this request. Thanks

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. You can find external addon that do that.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,
