### ISSUE TITLE
Request for breadcrumb widget in WooCommerce elementor.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15201]
Please add a feature to the breadcrumb widget so we can select the desired icon for it : https://prnt.sc/13wxz3v
This is a small request. But changing its symbol would be great

thanks

**Comment by rami-elementor** [comment]
@79ho3ein 

Currently Elementor don't plan to add a breadcrumb widget.

As for the current Yoast breadcrumb widget, you will see it only if you have installed and activated Yoast SEO plugin. If you use Rank Math you won't see the Yoast breadcrumb widget.
