### ISSUE TITLE
Popup entrance and exit effects with animation duration.

### ISSUE THREAD

**Issue by adnanalbeda** [elementor/elementor#15206]
I have a pop up with entrance and exit effects. I set the duration to 1 sec. 
On windows, I have accessibility feature, simplify animation, or something like that enabled. 
This should mean that I'm not supposed to see animation and actions must run directly. 
So now I don't see the animation, but the popup still waits for the animation duration before it takes effect.
Whether I try to open or exit a popup with 1 second animation duration, nothing happens for one second then it suddenly appears or close.

I'm using Firefox browser, and running wordpress 5.7.2 with php 7.3 on wsl debian 10 (localhost).
I have Elementor V3.2.4 and Elementor  Pro V3.2.2

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

In general - this seems to be a case for your 3rd party plugin developers to solve. 
You are welcome to contact our support, they might encounter a similar case. 

Thanks.
