### ISSUE TITLE
There is an update notification. but cannot update.

### ISSUE THREAD

**Issue by thaandcat** [elementor/elementor#15218]
wordpress version 5.7.2 and all plugins are up to date
![2021-06-06_5-44-46](https://user-images.githubusercontent.com/59549612/120907393-192c0080-c68b-11eb-8f0a-61c25fec8775.jpg)
![2021-06-06_5-45-27](https://user-images.githubusercontent.com/59549612/120907397-234dff00-c68b-11eb-8a2d-b193e6ecb4b4.jpg)

**Comment by shilo-ey** [comment]
It seems to be related to some specific server restriction rule.

Please contact our support at support @elementor.com for guidance in resolving this issue and reference this issue.

Thanks.
