### ISSUE TITLE
"No Templates For Condition"  for WP 5.7.2

### ISSUE THREAD

**Issue by likhoman** [elementor/elementor#15219]
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi. When i created template for post this template doesn't apply to my post.

I enabled debug mode and saw this "Template File: No Templates for condition > Astra - single.php"

<img width="587" alt="Screenshot 2021-06-06 at 10 16 57" src="https://user-images.githubusercontent.com/20304131/120911298-8c943900-c6b0-11eb-80f2-e25c345a6623.png">

Please give me advice how to fix it!

## Steps to reproduce

Ctreate template for post. Add "post content" dynamic element, and title. Add display condition for post.
Then create post and publish. Go to url with this post through "posts" in wordpress.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
[system info link](https://pastebin.com/W4dzC24r)
</details>

**Comment by DorShahar** [comment]
Hi 
As the file show - this has nothing to do with Elementor. 
You can contact our support team, they may help, but I suggest that you reach out to Astra developers. 

Good luck
