### ISSUE TITLE
Text editor widget issu

### ISSUE THREAD

**Issue by vxlou** [elementor/elementor#15212]
Hello there,

I can't use the text editor widget. When I try, my text don't appears on the left panel...

I have Elementor PRO and I created this website today.

**Comment by avivu** [comment]
Hi @vxlou 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it, we simply can't help.
Please share with us as many details as possible, so we can assist you better.

Thanks.
