### ISSUE TITLE
Copy and Paste doesn't work between pages

### ISSUE THREAD

**Issue by DavidGMiles** [elementor/elementor#15213]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Copy and Paste between two instances of the Elementor fails - it seems to paste something spurious from a few sessions ago

## Steps to reproduce

See this Loom - https://www.loom.com/share/857903e0692f430fb83430baa85526a1

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Hi @DavidGMiles 
Please attach your System info, and share console logs so we could inverstigate. 

I'm also suggesting deactivating Experiments and other plugins to check if this is the root cause.

Thanks

**Comment by DavidGMiles** [comment]
This only happens in Safari - so system logs may help - but it works as it should in Edge, Chrome and Brave - it fails only in Safari - with or without Experiments and other plugins

**Comment by cirkut** [comment]
Can confirm that this is happening in Safari. No console errors show up, tried with only having E & E Pro active (and up-to-date) and same result. Using CSS-modified Hello Theme as well. No Experiments are active either.

Copying and pasting on the same page works as expected. Can't copy from one page to another.

Copying and reloading the page will keep the same-page item copied for pasitng on the same page (Page A copy element, reload Page A, paste element works). 

This should 100% be reported as a bug and be fixed kinda quick.

Here's system info:

<details>
<summary>System Info</summary>					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.3.29
	PHP Version: 7.4.18
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://wordpress-43087-1909427.cloudwaysapps.com
	Home URL: https://wordpress-43087-1909427.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 256M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Detroit
	Debug Mode: Inactive

== Theme ==
	Name: Cirkut Media Base
	Version: 1.0.0
	Author: Cirkut Media
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		heading : 1
		html : 1
		icon-list : 2
		image : 1
		text-editor : 1
	header : 1
		html : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	widget : 0
		divider : 7
	wp-page : 2
		button : 3
		button-group : 1
		call-to-action : 21
		divider : 2
		global : 1
		heading : 6
		spacer : 1
		text-editor : 3


== Log ==
	
Log: showing 13 of 132021-05-04 02:30:01 [info] elementor-pro::elementor_pro_updater Started 
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-05-04 02:30:01 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-05-04 02:30:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.2.1',
)]
2021-05-04 02:30:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.2.1',
)]
2021-06-05 22:21:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.4',
)]
2021-06-05 22:23:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]

PHP: showing 2 of 2PHP: 2021-05-05 08:20:39 [notice X 4][/home/46885-43087.cloudwaysapps.com/qgucafesng/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-05 22:21:38 [warning X 1][/home/46885-43087.cloudwaysapps.com/qgucafesng/public_html/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/home/46885-43087.cloudwaysapps.com/qgucafesng/public_html/wp-content/uploads/elementor/css/post-59.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]```
</details>

**Comment by donwattz1459** [comment]
Can confirm this is happening in my case too. macOS v11.3.1 Safari v14.1, Latest everything. Chrome works fine. This seems to have been an issue for several weeks too. When can we expect a fix?

**Comment by DavidGMiles** [comment]
I can replicate it on multiple machines - the commonality is Safari @shilo-ey

**Comment by donwattz1459** [comment]
Any update on this issue?

**Comment by DavidGMiles** [comment]
+1

**Comment by DavidGMiles** [comment]
@shilo-ey do you if this is on anyone’s radar for a fix yet?

**Comment by 319heads** [comment]
Same issue here OSX 11.4 / Safari Version 14.1.1 

Copy and Paste stopped working on Safari.

**Comment by drawesome** [comment]
+1  - works everywhere but safari.  copy paste does not work on same domain/site... sometimes even on same page.

**Comment by DavidGMiles** [comment]
Thank you for verifying

**Comment by captaincoo1** [comment]
This has been an issue for me for a few months. :( It has been very frustrating. Seems to be an issue with the latest versions of Safari. I'm running Safari 14.1.1 under Mac OS Big Sur 11.4 and it will not work. However, Copy/Paste still works with Safari 13.1.2 on MacOS Catalina and Safari 12.1.2 on MacOS Mojave.

I even downloaded today the Safari Technology Peview browser (Release 127 Safari 15.0) for Big Sur and luckily it DOES work there. Hopefully that means it will work again in the future when the next major Safari release happens.

Copy/Paste has also been an issue for a clipboard plugin I use on sites built with WPBakery Page Builder (Visual Composer). It will not copy between same site pages in Safari either. (https://codecanyon.net/item/visual-composer-clipboard/8897711)

So this issue seems to be something Safari changed and maybe not Elementor, but I've been hoping Elementor would acknowledge the issue and help us and Apple find a work around so we don’t have to wait for Safari 15 to eventually fix it.

**Comment by captaincoo1** [comment]
I had a co-worker just test it with Safari 14.0.3 on Big Sur and it worked for him. So sometime with Safari 14.1 or 14.1.1 this copy and paste issue occurred.

**Comment by DavidGMiles** [comment]
Cheers buddy

**Comment by captaincoo1** [comment]
One work around "solution" I just discovered:

Whatever page you want to paste into has to be opened AFTER you've copied something into the Elementor clipboard. So you if want to copy a row from page A to page B. You need make sure page B isn't already open (you may need to close it first), then copy the row on page A you want into the Elementor clipboard, and then open page B in a new tab and you can paste to it.

On further investigation, it looks like when you copy something in Elementor it stores the ID of the copied element in a local storage with the key of "elementor". For whatever reason, already open Elementor pages aren't able to access changes to local storage. By opening a page in a new tab after copying, it's able to pull up the latest local storage.

**Comment by DorShahar** [comment]
Thanks for reporting.  
We will investigate.

**Comment by DavidGMiles** [comment]
> Thanks for reporting.
> We will investigate.

Anything further?

**Comment by captaincoo1** [comment]
This appears to have been fixed in Safari 14.1.2 released this week!

**Comment by DavidGMiles** [comment]
Yup - latest update of Safari works for me too

**Comment by Sebastiangperez** [comment]
Elementor won't copy from other site if i'm logged in the same browser profile and in two different tabs: 
Browser : Chrome latest 
Same Browser Profile
Tab : Site1 
Tab: Site 2 

Dont work 

Chrome profile 1
Tab 1 
Chrome Profile 2 
Tab 1 

This works.

**Comment by alvarindev** [comment]
not working again

**Comment by Sebastiangperez** [comment]
Seems like elementor is dying .... Bricks builder is the new kid in the block and 1000 times better.

**Comment by cswebstuff** [comment]
using Brave browser - copy paste from one site to another is still not working as of today - June 12th 2024.
