### ISSUE TITLE
Synchronous elements initialization may produce long JavaScript tasks

### ISSUE THREAD

**Issue by FlyingDR** [elementor/elementor#15228]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor initializes itself at `jQuery.ready` moment. During process of its initialization it also performs initialization of all page elements, that are built using Elementor. 

In a case of large amount of elements to initialize, or in a case of long initialization process of some element - this initialization process may take quite some time to complete.

Nothing is wrong there except for one small nuance: this initialization process is **synchronous**. And since JavaScript by itself runs into main thread - long synchronous task blocks whole main thread, effectively making browser less responsive for user interactions. Another visible consequence is lower score from Google's [PageSpeed](https://developers.google.com/speed/pagespeed/insights/) which tracks [main thread load](https://web.dev/mainthread-work-breakdown/) and treats significant load as severe negative factor. This is especially important in a case of mobile devices.

At the same time there is no any practical reason to have this initialization process to be synchronous because it performs initialization of a set of independent elements.

Digging into Elementor code shows that [`runElementsHandlers()`](https://github.com/elementor/elementor/blob/92d09f924db0ea16bee595d446f41c6f10949dbf/assets/dev/js/frontend/document.js#L40-L42) method is the best candidate for a place to break this solid synchronous process into smaller pieces.

There is a very simple (one line) solution for the issue: it is just required to run every handler as separate JavaScript event cycle, which can be achieved by wrapping `runReadyTrigger()` call in `setTimeout()`:

```js
runElementsHandlers() {
	this.elements.$elements.each( ( index, element ) => setTimeout( () => elementorFrontend.elementsHandler.runReadyTrigger( element ) ) );
```

## Steps to reproduce

1. Put multiple (10+) elements of different types that will require JavaScript initialization on the page
2. Open page in browser. Chrome is used by me for test purposes because it closely resembles PageSpeed test
3. Open "Performance" tab in Chrome DevTools
4. Measure page loading performance by running performance information gathering
5. Take a look at "Main" line at a time of `DCL` event

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Example

Here is and example of performance report from actual site of one of ours client:
![image](https://user-images.githubusercontent.com/822673/120924705-9da76f00-c6dd-11eb-9864-ec7e229080e5.png)

As can be seen - initialization process took about 400ms on my notebook and main thread remains blocked for almost all time.

## Test of proposed solution

Here is example of performance report from same site with proposed patch applied:
![image](https://user-images.githubusercontent.com/822673/120924858-71d8b900-c6de-11eb-9b43-28b72bab2bbb.png)

As can be seen - it looks much better now with main thread blocking to be much less. They're caused by long initialization of elements which are caused by third-party plugin. It, of course, also improves PageSpeed rank.

**Comment by ramiy** [comment]
The main concern is whether there will be synchronous code using functionality passed to **JS Event Loop**.

What widgets did you use to test the solution?

And what problems did you encounter when performing tests?

**Comment by FlyingDR** [comment]
I've performed tests on the pages of the site of one of our clients. There was a number of widgets that came from Elementor, Elementor Pro and Ultimate Addons for Elementor.

Main performance impact in a case, shown in original report came from: 
 - [Woocommerce Products](https://ultimateelementor.com/widgets/woocommerce-products/) widget (Ultimate Addons for Elementor)
 - [Navigation Menu](https://ultimateelementor.com/widgets/navigation-menu/) widget (Ultimate Addons for Elementor)
 - [Slides](https://elementor.com/widgets/slides-widget/) widget (Elementor Pro)
 - `StickyHandler` (Elementor Pro)

Main issue (without applying proposed patch) is long task running in main thread which affects PageSpeed rank. By applying proposed patch I get this long task to be split into smaller chunks that results in less blocking. I'm not aware about any side effects and I don't think that there can be any because initialization tasks seem to be independent.

**Comment by Camilo517** [comment]
Fixed?

**Comment by FlyingDR** [comment]
> Fixed?

Was fixed at the time of reporting, but still not merged. See #15229

**Comment by Camilo517** [comment]
> > Fixed?
> 
> Was fixed at the time of reporting, but still not merged. See #15229

Why?

**Comment by FlyingDR** [comment]
> > > Fixed?
> > 
> > 
> > Was fixed at the time of reporting, but still not merged. See #15229
> 
> Why?

No idea, I've just provided information and fixed, it but have no permission to merge it in this repository. 

@kobizz @matipojo are probably have more information since they're assigned as reviewers to #15229.
