### ISSUE TITLE
Suggested to improve the ability of custom icons and fonts in elementor.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15230]
The ability to customize fonts and icons in elementor is very useful and excellent.
But one problem is that when we upload a font or icon in elementor, it adds a lot of files to the WordPress media.You can see these files in the image opposite, which is the result of loading 4 icons : https://prnt.sc/137ij3l
It would be great if after uploading icons and fonts, these files are not displayed in the media section.
In this case, the media sector would be much more regular.
Please review this offer and, if possible, hide uploaded fonts, fonts and icons from within WordPress media.

thanks

**Comment by DorShahar** [comment]
Hi @79ho3ein 
Elementor uses WP mechanism, and enable you to manage your files. 

In case you wish to remove the files, use this script:
```
function media_library_hide_elementor_files($where) {
	if(isset($_POST['action']) && ( $_POST['action'] == 'query-attachments')) {
	   $where .= ' AND guid NOT LIKE "%wp-content/uploads/elementor/custom-icons%"';
	}
	return $where;
 }
 add_filter('posts_where', 'media_library_hide_elementor_files');
```
