### ISSUE TITLE
Report a bug in the button widget.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15231]
When we set the button to full width, the distance between the icon and the button text gets out of control.
![20210606_190655](https://user-images.githubusercontent.com/77163248/120928589-790dc000-c6fa-11eb-9872-b10a9bae038a.jpg)
Great if you add a feature, so we can adjust the distance between the text of the button and the icon, if the button is full width.

Thanks

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
