### ISSUE TITLE
Bug - New template library

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#15249]
The preview of a part of a template does not work for site parts and popups but only for pages.

**Comment by shilo-ey** [comment]
Thanks, we are working on resolving this issue and will release a beta version once done.

**Comment by matipojo** [comment]
@rodolphebertozzo it still will not show popups, because currently they are not a part of the theme.

**Comment by rodolphebertozzo** [comment]
Thanks for your feedbacks @matipojo, Part of the problem is still solved, thank you.
