### ISSUE TITLE
Adapt to screen - without header

### ISSUE THREAD

**Issue by weebgeek** [elementor/elementor#15242]
Hi Elementor

Thank you for a great product!

I'm having trouble locating a sulution to this issue:
[https://wordpress.org/.../section-with-fit-to-screen-height/]

Been in contact with support whitout beeing wiser. 

Have a great day

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
