### ISSUE TITLE
New admin bar - Feedback

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#15250]
The sticky effect is not active when scrolling on the page

**Comment by fabianenzensperger** [comment]
Yep, it would be great, as described by Rodolp, if the bar were adhesive.

And the ele logo with the text is a bit disproportionate. Making the logo a little smaller and the font a little bold would be more aesthetic. Like here:

![109153492-a9e26e80-7775-11eb-8a7b-dee0f5d73052](https://user-images.githubusercontent.com/57997262/121090098-5954c580-c7e8-11eb-9e37-3b40e34fd5a0.gif)

**Comment by shilo-ey** [comment]
Thanks, 

Won't the top bar be disturbing if it were sticky?

What is the use case for you to need it actively visible all the time?

**Comment by rodolphebertozzo** [comment]
Hi @shilo-ey,
There is no specific case, why not propose for the beta release to make it scroll and see the reactions of the users to be able to make a decision on this subject consequently.

**Comment by shilo-ey** [comment]
Because it should have some value,

This feature relates to better UX in terms of making Connect and Finder more accessible.

I think that the placement of this top bar is emphasized enough and it wouldn't make any value when scrolling.

Do you have a reason for users to need it constantly?

**Comment by fabianenzensperger** [comment]
> Because it should have some value,
> 
> This feature relates to better UX in terms of making Connect and Finder more accessible.
> 
> I think that the placement of this top bar is emphasized enough and it wouldn't make any value when scrolling.
> 
> Do you have a reason for users to need it constantly?


Do you know the top bar at WooCommerce? I think it could be something like that.

**Comment by shilo-ey** [comment]
In the current state of functionality - do you find any use case that requires it to be sticky?

The sticky effect can annoy some people if not beneficial enough because it takes height from the preview.

**Comment by fabianenzensperger** [comment]
@shilo-ey Apart from that, the bar "destroys" the arrangement of Wordpress elements a little. Strangely enough, some things move down, but others stay up. Furthermore, the WP columns are reduced in size and shifted left and right. Even on non-Elementor dashboard pages. For example, "Create" has slipped down under Pages.

That would be more important than sticky, but sticky would be nice too. 😅

**Comment by d19dotca** [comment]
Personally I don't think this new admin bar needs to be sticky, I'm not sure what problem it solves by being sticky when it only presents a few options to begin with (in most cases so far it seems to just present "Finder" which is keyboard-accessible anyways and "My Account", and perhaps "Add New" button depending on the Elementor page being viewed). Just my two cents. 🤷‍♂️ 😄

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.0

Feel free to update

Thanks!
