### ISSUE TITLE
Search and Replace URL Tool doesn't recognize empty space in url

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#15253]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When searching for a url with a space in it and replacing with the same url but without the space, an error is shown saying the "From" must be different from the "To".  It is different.

## Steps to reproduce

Have post content or postmeta with a url in it such as mysite.com /....then try to replace it without the space after the .com using the tool and see it complain they are not different.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
Long time, but the Replace URL only replaces the full URL without spaces or relative URL, for this purpose I suggest you to use other search and replace plugins to do this.

Thanks
