### ISSUE TITLE
Reset icon for responsive controls

### ISSUE THREAD

**Issue by Codevz** [elementor/elementor#15263]
It would be great if you add reset icon support for responsive controls. Now it's hard to switch between responsive modes and reset one control responsive values.

**Comment by Aviad-Herman** [comment]
Hey, 

Can you please explain the reason a bit more?
Is using the icons next to the responsive field not fast enough?

![ezgif-2-e6ce657534f6](https://user-images.githubusercontent.com/73067562/121386139-6988b400-c952-11eb-9dea-48fb3d713317.gif)

**Comment by Codevz** [comment]
I understood, But user should spend at least 2-4 seconds depending on his speed to reset each mode. But with a simple reset icon it will much easier and will have better UX, Also it will good feature for developers that have custom responsive controls. I hope you get my mean.

**Comment by Aviad-Herman** [comment]
Hey @Codevz,
We considered you suggestion and although it's a smart idea, it's not a top priority right now.
If more people will suggest this in the future we will merge the discussions to this one.

Keep suggesting good ideas!

I'm closing this issue but it stays documented, don't worry.
