### ISSUE TITLE
Video playlist widget can't handle more than approx. 10 videos

### ISSUE THREAD

**Issue by janoschsworkspace** [elementor/elementor#15270]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I add a certain amount of videos to the new video playlist widget, Elementor stops working. At around 13 videos the widget stops registering new videos I add and when I go out of the editor I can't get back in

## Steps to reproduce

Add lots of videos to the new video playlist

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.3.28
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://janoschsworkspace.com
	Home URL: https://janoschsworkspace.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.4.8
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

== Active Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.26
		Author: Benjamin A. Bornschein, Borlabs

	Disable/Remove Google Fonts
		Version: 1.3.0
		Author: Fonts Plugin

	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.0
		Author: Elementor.com

	Envato Elements
		Version: 2.0.8
		Author: Envato

	iThemes Security Pro
		Version: 6.8.4
		Author: iThemes

	SEOPress
		Version: 4.7.0.1
		Author: SEOPress

	SEOPress PRO
		Version: 4.7.0
		Author: SEOPress

	UpdraftPlus - Backup/Restore
		Version: 2.16.58.25
		Author: UpdraftPlus.Com, DavidAnderson

	WP Rocket
		Version: 3.8.8
		Author: WP Media

	Zapier for WordPress
		Version: 1.0.2
		Author: Zapier

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Envato Elements: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		sp-breadcrumbs : 1
		theme-archive-title : 1
	footer : 1
		icon-list : 1
		theme-site-logo : 1
	header : 4
		button : 1
		nav-menu : 3
		theme-site-logo : 3
	page : 13
		alert : 5
		button : 56
		form : 2
		heading : 123
		icon : 24
		image : 44
		menu-anchor : 3
		posts : 5
		text-editor : 61
	section : 6
		button : 1
		divider : 2
		form : 2
		heading : 7
		icon-list : 2
		posts : 2
		text-editor : 1
		video-playlist : 1
	widget : 0
		button : 1
	wp-page : 19
		button : 44
		call-to-action : 7
		form : 8
		heading : 130
		html : 1
		icon : 12
		icon-list : 1
		image : 40
		posts : 4
		shortcode : 1
		sp-breadcrumbs : 4
		tabs : 2
		text-editor : 93
		video : 1
		video-playlist : 1
	single-post : 3
		form : 3
		heading : 9
		posts : 3
		share-buttons : 3
		text-editor : 3
		theme-post-content : 3
		theme-post-featured-image : 2
		theme-post-title : 3
	error-404 : 1
		button : 1
		heading : 1
		text-editor : 1

== Log ==
	
Log: showing 20 of 372021-02-18 17:20:30 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-18 17:20:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-03-04 08:31:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-11 08:57:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-04-05 21:17:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.2.1',
)]
2021-04-29 06:54:27 [info] elementor::elementor_updater Started 
2021-04-29 06:54:27 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-29 06:54:27 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-29 06:54:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.2',
)]
2021-04-29 06:54:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.2',
)]
2021-05-06 07:19:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-06 07:19:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-27 07:04:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]
2021-06-08 15:05:34 [info] elementor-pro::elementor_pro_updater Started 
2021-06-08 15:05:34 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-08 15:05:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-08 15:05:35 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-08 15:05:35 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-08 15:05:36 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-08 15:05:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]

JS: showing 3 of 3JS: 2021-01-01 23:38:09 [error X 2][https://janoschsworkspace.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.15:2:414166] Cannot read property \'message\' of undefined 
JS: 2021-02-12 11:50:32 [error X 99][https://janoschsworkspace.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.1.1:2:35000] Cannot read property \'global\' of undefined 
JS: 2021-02-13 17:56:28 [error X 1][https://janoschsworkspace.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:768] Cannot read property \'cid\' of undefined 

PHP: showing 3 of 3PHP: 2021-01-02 01:24:46 [notice X 1][/home/customer/www/janoschsworkspace.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::217] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-03 14:50:00 [notice X 52][/home/customer/www/janoschsworkspace.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-04 08:48:42 [error X 1][/home/customer/www/janoschsworkspace.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/janoschsworkspace.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/customer/www/janoschsworkspace.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/janoschsworkspace.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/janoschsworkspace.com/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/custome [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by Aviad-Herman** [comment]
Hey @janoschsworkspace 
I'm trying to recreate this bug locally without any luck.
To try and pinpoint the root cause, can you please try the following?
* disable all plugins other than Elementor and Elementor Pro
* Switch your theme to Hello Elementor or a native WP theme

If the bug still occurs will it be possible to send a video? (loom is a great tool for this).

Thanks!

**Comment by janoschsworkspace** [comment]
Hey Aviad, I think the issue is fixed. It appeared because I imported the video playlist widget as part of a template that I got from a site using the beta version. Using a fresh video widget fixed the issue.

**Comment by Aviad-Herman** [comment]
Thanks for sharing!
It still might be a bug so thanks for the update @janoschsworkspace
