### ISSUE TITLE
Please add slider content to the elementor section.Very important

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15275]
A very important feature that elementor lacks and desperately needs is slider content.So, as usual, we put our content in the section, but we can slide it.
Of course, this feature is more used in mobile phones.
My suggestion is to add a setting to this section(https://prnt.sc/14sm4wf), so that if it is enabled, the content of the section will be displayed as a slider.
If you add this feature, we can design something like this (https://prnt.sc/14smgwv) to make it mobile.In general, we can slide show any content to users.
This feature is extremely important. Please add it to elementor if possible.

thanks

**Comment by d19dotca** [comment]
You're just looking for a section that operates like a slider? I think you can achieve this by just using the Slider widget in full-width and no-gap config.

**Comment by 79ho3ein** [comment]
hi @d19dotca 
No, the slider widget limits us to a few.But if it is possible to slide the section, we can slide any content.
