### ISSUE TITLE
Please add the ability to display the number of views to the posts widget.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15291]
Great if you add a feature to the posts widget, so we can show users the number of views of each article.
This feature will be extremely useful and practical.

**Comment by d19dotca** [comment]
I don't think WordPress keeps track of that type of data, so that may be a bit difficult to do, but might be a nice addition if possible. This actually reminds of the old-style "hit counter" back in the Yahoo GeoCities days. 😆  But I can see a use for it on posts.

**Comment by 79ho3ein** [comment]
@d19dotca 
Thanks
Of course, I meant adding a query to the posts widget as the most visited articles.

**Comment by mcrowell** [comment]
I created a video on how to do this exact functionality. It works well and can be done using free plugins.

https://youtu.be/3F3MlY-4eh4

**Comment by 79ho3ein** [comment]
@mcrowell 
thanks

**Comment by rami-elementor** [comment]
Hi @79ho3ein 

Thank you for submitting a feature request.

This feature will have a negative effect on site performance as each visit will require to update the database.

Elementor is focusing on performance improvements. This is why this feature is not accepted.

You can still use external plugins for this kind of functionality.

Regards,

**Comment by 79ho3ein** [comment]
Thank you @rami-elementor. But one question ...
Is it possible to sort posts or products by "most visited" also have the problem of reduced performance?
For example, you are working on an elementor loop. Using the loop, we can display posts and products in an advanced way ...
For example, in the elementor loop query section, can we display products or posts based on the most visited?
Does this reduce performance? And is it possible to have this query in elementor loop?

**Comment by rami-elementor** [comment]
WordPress does not store data about the most visited pages. So Elementor can't filter products/post based on this metric.
