### ISSUE TITLE
videos in video playlist widget all start muted

### ISSUE THREAD

**Issue by iStuff0** [elementor/elementor#15292]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

All videos in playlist widget start muted.

This is with videos self hosted and external URL. Not YouTube

## Steps to reproduce

Just create a video playlist with widget and press play on the front end.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/XyVj6tZ1

**Comment by Aviad-Herman** [comment]
Hi, 
Thanks for reporting this bug!
I transferred it to our internal bug management system.

---
For internal purposes:
ED-3717

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.4.0

Feel free to update

Thanks!
