### ISSUE TITLE
Video Playlist Lazy Load Not Saving

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#15304]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

The lazy load option doesn't stay active after you save the page.

## Steps to reproduce

Enable the lazy load option inside the video playlist widget and save the page.
Refresh the page and the option is not active.
This happens with/without the image overlay active.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 7.4.20
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 2.0
	Author: Wicky Design
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.0.3
	Parent Theme Author: Tom Usborne

== Active Plugins ==
	Advanced Post Queries
		Version: 1.0.15
		Author: Shabti Kaplan

	All in One SEO
		Version: 4.1.1.1
		Author: All in One SEO Team

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Ele Custom Skin
		Version: 3.1.0
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.0.0
		Author: Dudaster.com

	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.0
		Author: Elementor.com

	GP Premium
		Version: 2.0.2
		Author: Tom Usborne

	Head, Footer and Post Injections
		Version: 3.2.2
		Author: Stefano Lissa

	JetSmartFilters
		Version: 2.2.3
		Author: Crocoblock

	Open External Links in a New Window
		Version: 1.42
		Author: WebFactory Ltd

	Redirection
		Version: 5.1.1
		Author: John Godley

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	SVGator
		Version: 1.1.1
		Author: SVGator

	White Label CMS
		Version: 2.2.2
		Author: www.videousermanuals.com

	WooCommerce
		Version: 5.3.0
		Author: Automattic

	Wordfence Security
		Version: 7.5.4
		Author: Wordfence

	WP-PostViews
		Version: 1.76.1
		Author: Lester 'GaMerZ' Chan

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Incompatible

**Comment by Aviad-Herman** [comment]
Hi,
Great bug documentation!
I transferred it to our internal bug management system.
Thanks!

---
For internal use:
ED-3750
