### ISSUE TITLE
Forms: Action after submit - Download

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#15302]
The ability to activate a download (eg. PDF eBook) after the user has submitted the form.

Not as a link in an email, but as an automatic download after the form has been submitted.

Bonus feature would be to not ask the user for their details if another download is requested (presumably using cookies).

**Comment by d19dotca** [comment]
This is a duplicate of #12716 and should be closed.

**Comment by simonclay** [comment]
Ah I see, yes. Closing.
