### ISSUE TITLE
Requesting to Add Widgets For...

### ISSUE THREAD

**Issue by ecom-gypsy** [elementor/elementor#15307]
Adding any/all of the following widgets will be a great addition to already the best plugin out there for WordPress:

1. Currency Widget (currency auto changes based on IP address
2. Track shipping widget
3. Control over checkout (direct/delayed etc)
4. Live Chat widget, not messenger or WhatsApp which is already there. Most customers don't feel comfortable starting a customer service chat through WhatsApp cuz it gives away their personal number. Whereas a live chat widget is ideal for all types of visitors and customers.

Thanks, elementor pro is the best thing that happened to WordPress ever. And elementor pro saved me tons of money that I could end up paying Shopify.
Elementor Pro rocks (period)

**Comment by d19dotca** [comment]
Best to file individual feature requests for each item since they're not exactly related at all.

**Comment by Aviad-Herman** [comment]
Hi,
@d19dotca is right, it's not good to address several issues in one thread.

I'll try to give some answers nonetheless:

1. I'm not sure what you mean by Currency widget and what problem it's solving.
2. Currently we are not planning to extend retail functionality beyond WooCommerce capabilities.
3. I'm not sure exactly what you mean but I can tell you we are planning to supply more WooCommerce customizations.
4. This is currently way out of our scope but you can use one of the many excellent services out there such as Intercom.

Thanks for the suggestions and the compliments.
