### ISSUE TITLE
Allow dynamic url using Share Buttons widget

### ISSUE THREAD

**Issue by maoxiong** [elementor/elementor#15317]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The "Share Buttons" widget only allows you to either share the current page, or a custom fixed url - it doesn't allow dynamic.

**Describe the solution you'd like**
For there to be a dynamic selector in the custom url part

**Describe alternatives you've considered**
You can add this yourself by adding the following code in share-buttons.php, but it will overwrite every upgrade (it also gives a lot of warnings in the php.ini)

`				'dynamic' => [
					'active' => true,			
				],	`

**Additional context**
I opened this before and was told to use the social icons widget - THIS IS NOT THE SAME - the social icons widget just allows you to link to the various social media pages, whereas the Share Buttons widget allows you to *share* the selected page to the selected social network.

This is very handy if you are using a loop or ACF fields.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.7.0

Ref: https://github.com/elementor/elementor/issues/10729

Feel free to update

Thanks!
