### ISSUE TITLE
Add Vimeo support to the video playlist widget

### ISSUE THREAD

**Issue by Aviad-Herman** [elementor/elementor#15319]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to create video playlists from Vimeo.
Currently the video playlist widget only supports YouTube videos.

**Describe the solution you'd like**
Exactly the same as choosing a video from YouTube, just add an option to use Vimeo as a source.
![image](https://user-images.githubusercontent.com/73067562/121798662-3edb7b80-cc30-11eb-8727-20ac323aecd7.png)

**Comment by ruorcr** [comment]
Good idea, it’d be a necessary feature! I hope it soon

**Comment by highrise955** [comment]
Yes, Vimeo and DailyMotion would be quite helpful.

**Comment by rubenhzz** [comment]
Yes Vimeo support is a must, the playlist is great, I was actually looking for something like that, but I can not use it yet as it does not have Vimeo support.

Hopefully you can add this feature quick as you already have it in the normal videos

**Comment by vogelmy** [comment]
Please add Vimeo support!
It would really help with a project I'm working on right now.

**Comment by bd360** [comment]
Yes please, we don't use YouTube in any of our projects and are not self-hosting anytime soon. Without Vimeo support the playlist widget isn't usable for us (but we'd love to!)

**Comment by dvir3674** [comment]
Please add Vimeo support!
It would really help with a project I'm working on right now.

**Comment by jimmyscratch** [comment]
same as above, please add vimeo support

**Comment by billyheidt** [comment]
PLEASE add Vimeo!

**Comment by ChristophGeier** [comment]
Please add Vimeo support!
It would really help with a project I'm working on right now.

**Comment by vogelmy** [comment]
Yes please add Vimeo support to the next version! 
This request was opened a while ago and shouldn't be too hard too implement.

**Comment by rezultstudio** [comment]
Urgently needed!

**Comment by DTR96** [comment]
Please add Vimeo Videos option!!!!!!!!

**Comment by curlygirly1** [comment]
Please add VIMEO. And the ability to add channels, plus some useful features as the CodeCanyon plugin "ultimate video player" WP plugin has. Super good plugin with ultimate control and features.
It's really useful for edu sites and a pity needing another plugin if you already have a playlist.
WHY NO VIMEO?!

**Comment by curlygirly1** [comment]
THANKS for finally adding vimeo support :)

I have played with this element yesterday on a staging site and now after updating Elementor Pro to 3.4.0 this element I am looking at on this test e-landerpage  displays no more YT videos or tabs. FYI.

Also a new element with zero changes to it is the same - the list shows the 3 vids you have out of the box [YT] and in main display player is empty regardless what I try.

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!

**Comment by curlygirly1** [comment]
Thanks for adding it but now it DESTROYED this element completely. Nothing
functions with your new update and I cleared all caches endless times,
refreshed a test page for this element etc and buggy as hell.

https://www.dropbox.com/s/wqxhjiwa79vkgrd/2021-08-31_elementor_3-4-update-killed-video-playlist-element.mp4?dl=0

**Comment by adriantaverner** [comment]
Loving the Vimeo support. Could we please get a _start time_ field? And/or chapter support. My education site relies on segmenting larger videos.

<img width="372" alt="Screen Shot 2021-09-29 at 9 48 57 AM" src="https://user-images.githubusercontent.com/91625104/135313960-1b041128-4043-468e-8f47-cac3e5e9397a.png">
?

**Comment by NathanR-85** [comment]
> Loving the Vimeo support. Could we please get a _start time_ field? And/or chapter support. My education site relies on segmenting larger videos.
> 
> <img alt="Screen Shot 2021-09-29 at 9 48 57 AM" width="372" src="https://user-images.githubusercontent.com/91625104/135313960-1b041128-4043-468e-8f47-cac3e5e9397a.png">
> 
> ?

You might be able to add the start time to the URL.

On Youtube, go to your video, click Share, add Timestamp, then use that link.
