### ISSUE TITLE
Suggest to add the ability to copy text in the clipboard

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15322]
Please add this important feature to elementor if possible.
Currently only possible with coding and the ACF plugin.
To understand more about this request, read this link. Thanks
https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

**Comment by 79ho3ein** [comment]
This feature can be added to the button widget.
This button is designed with elementor : https://prnt.sc/158zmv1
It would be great if the user could copy the link after clicking on the specified section (icon).
And after copying, the symbol changes as follows : https://prnt.sc/158zoh4

**Comment by Aviad-Herman** [comment]
Hey,
Thanks for the suggestion but we are not planning to add an option to copy the contents of a button.
You sent a great link, you can use it to program your own copy text functionality. Seems like you know what you're doing!

**Comment by 79ho3ein** [comment]
hi @Aviad-Herman
thanks for your answer...
My point was not to add this feature to the button widget. Rather, my suggestion was to add this feature to elementor.
Rather, this feature can be a new widget, or integrated with other widgets of the element.In any case, it is a very important feature, it is very widely used today.
Is there a program element to add this feature anyway?
I will be happy if you let me know
thanks

**Comment by Aviad-Herman** [comment]
Add an HTML widget above the button you want to have the copy action.
Give the button a CSS ID

In the HTML widget you can target the button using:
```
<script>
    let a = jQuery('#custom-id a');
    ....add any action you want to the button using code
</script>
```

You can add any onclick function to the button and have it copy anything you want from the page.

We are not planning to release such a feature anytime soon

**Comment by 79ho3ein** [comment]
thank you
