### ISSUE TITLE
Playlist widget adds querystring to URL

### ISSUE THREAD

**Issue by marketingspectrumNL** [elementor/elementor#15348]
I'm using it on a site now (like it!) but for some reason it adds a querystring to the url itself. 
Sometimes it immediately jumps to the playlist itself as well.

So the URL looks like this when you navigate to the url itself: 
url/?playlist=8e8edaab&video=b9t59b3

**Comment by Aviad-Herman** [comment]
Hi,
We actually designed it like this.

The querystring is to allow your users to share a link to a specific video.
We also created a feature that scrolls the user to the playlist if it's not visible.

What is your opinion on these features? are they good or bad in your eyes?

I'm closing the issue but please continue the conversation, I'd really like to hear what you have to say.

**Comment by marketingspectrumNL** [comment]
Hi Aviad-Herman, thanks for the reply! 
It's bad in my opinion. The playlist is a tool used on a page, it's not what the page is about.
So having an option to directly link to the list is good, but having it added to the url by default is not.

Querystrings can even create SEO problems.
Therefor this should be a user choice, not something that is automatically added when you enter the url itself.
If it stays added by default I'd really appreciate having the option to turn it off.

**Comment by Aviad-Herman** [comment]
Thanks, I will raise this issue.
And in case the user chose to share a link to a specific video under the fold, is the scrolling wanted or annoying?

**Comment by marketingspectrumNL** [comment]
I'd say scrolling is good when the specific link is selected. 
That way it acts the same as using an anchor url/#anchor

Now the user is in control:
Normal url = normal page
Using the url with querystring = pagevisit with scroll to the selected video.

**Comment by yewzy** [comment]
Hi, for some reason, the query string will cause the page to return a 404 error when refreshed. Does anyone else have this issue?

**Comment by Aviad-Herman** [comment]
@yewzy can you please share some more info? maybe a video and an example of your entire URL that causes this error?

**Comment by bouveng** [comment]
@Aviad-Herman 

Please make this an option. It is not usable like this!

Why would anyone want this query string in the url if they not have asked for it?
I'm working on top of the page, but this auto scroll takes me down to the video playlist on every page load.
Anything, no matter what it is, that messes with default behaviours should be an option.

👀 

Br.

/J

**Comment by Dreamleaf** [comment]
I agree 100% with it either being optional or removed altogether. I'm building a site that has a playlist on the homepage... except this fantastic widget can't be used due to the url rewriting.

Is there any way to disable this in the short term?

**Comment by bouveng** [comment]
> Is there any way to disable this in the short term?

Should be somewhere in the js, have not looked it up yet. Might be cancelable from `functions.php`.

**Comment by Aviad-Herman** [comment]
Hi everyone,
Thanks for the feedback.

Regarding the URL change: We have a PR planned for Pro 3.4.0. after which the query string will be appended only after a video in the playlist starts playing. 

Regarding canceling the autoscroll behavior, I opened a task but cannot promise a version number.

Keep the great feedback coming,
Let's make Elementor the best it can be, together.

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!

**Comment by CodeBradley** [comment]
How does one go about removing the URL Parameters from the URL by default? I'm on 3.4.0 and don't see an option in the video playlist. It's causing my homepage to scroll, which I don't want.

**Comment by davidmt3** [comment]
Hello

I'm facing the same issue here. Using version 3.3.8 and I don't see find the opcion to prevent the querystring or the scroll.
