### ISSUE TITLE
VIMEO in new playlist widget VIMEO is really wanted.... please make that work please!  as in normal the video widget!

### ISSUE THREAD

**Issue by charlyshort** [elementor/elementor#15342]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
duplicate #15319
