### ISSUE TITLE
Custom Code with CPT Conditions Shows only first CPT in Dropdown

### ISSUE THREAD

**Issue by TheCookieMonster70** [elementor/elementor#15350]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Only the first CPT will show in the dropdown for conditions for Custom Code any additional CPT will not show in the list.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

Worpress version: 5.7.2
Elementor Version: 3.2.4
Elementor Pro Version: 3.3.0 & 3.2.2
```

**Comment by Aviad-Herman** [comment]
Hi,
Seems to be working fine on my end.
I'm not sure how you register CPT but the problem might be with you plugin or code.

As this doesn't seem to be a wide-spread bug, for any specific assistance for your site please contact Elementor support.

If you have exact steps to reproduce feel free to send them over too.
