### ISSUE TITLE
Responsive mode on Elementor Editor doesn't work properly

### ISSUE THREAD

**Issue by DrSDuarte** [elementor/elementor#15362]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

When I try to edit a page in the responsive mode, the Elementor Editor doesn't adjust the view. I can't see the elements on the page and cannot edit them.

## Steps to reproduce
I open a page on the editor and click on the "Responsive Mode" button at the bottom next to the "preview". The view changes to the settings of mobile devices but the page is not well adjusted, as I only see a small portion of the right site of the page

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.20
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://theclarityforge.com
	Home URL: https://theclarityforge.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 2.1.0
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.9
		Author: Automattic

	Bluehost
		Version: 2.7.1
		Author: Bluehost

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.0.4
		Author: Hu-manity.co

	Duplicate Page
		Version: 4.4
		Author: mndpsingh287

	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.0
		Author: Elementor.com

	FileBird Lite
		Version: 4.7.4
		Author: Ninja Team

	Google Analytics for WordPress by MonsterInsights
		Version: 7.17.0
		Author: MonsterInsights

	Interact Quiz Embed
		Version: 3.0.7
		Author: The Quiz Collective Inc.

	Jetpack
		Version: 9.8.1
		Author: Automattic

	Kali Forms - WordPress Forms Made Easy
		Version: 2.3.7
		Author: Kali Forms

	Ocean Extra
		Version: 1.7.6
		Author: OceanWP

	OptinMonster
		Version: 2.3.3
		Author: OptinMonster Team

	Sticky Menu (or Anything!) on Scroll
		Version: 2.31
		Author: WebFactory Ltd

	UpdraftPlus - Backup/Restore
		Version: 1.16.56
		Author: UpdraftPlus.Com, DavidAnderson

	WP Quiz
		Version: 2.0.6
		Author: MyThemeShop

	Yoast SEO
		Version: 16.5
		Author: Team Yoast

== Must-Use Plugins ==
	Endurance Browser Cache
		Version: 0.4
		Author: Mike Hansen

	Endurance Page Cache
		Version: 2.0.7
		Author: Mike Hansen

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		spacer : 2
		text-editor : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 12
		button : 5
		divider : 3
		google_maps : 1
		heading : 18
		html : 2
		icon : 1
		icon-box : 6
		icon-list : 1
		image : 10
		image-box : 3
		image-carousel : 1
		portfolio : 1
		social-icons : 3
		spacer : 18
		text-editor : 54
		video : 1
		wp-widget-ocean_custom_menu : 2
	popup : 1
		html : 1
	section : 4
		heading : 1
		icon : 1
		posts : 1
		table-of-contents : 1
		text-editor : 7
		toggle : 3
	wp-post : 20
		button : 219
		html : 10
		icon : 22
		image : 132
		image-carousel : 1
		portfolio : 1
		posts : 1
		social-icons : 2
		spacer : 492
		text-editor : 801
		toggle : 17
	wp-page : 13
		button : 39
		heading : 8
		html : 57
		icon : 1
		icon-box : 2
		image : 33
		shortcode : 2
		spacer : 121
		text-editor : 268
		toggle : 99

== Log ==
	
Log: showing 20 of 312021-04-22 18:19:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-22 18:19:43 [info] elementor::elementor_updater Started 
2021-04-22 18:19:43 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-22 18:19:43 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-22 18:19:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 19:05:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-05 07:23:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-27 20:16:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]
2021-06-11 16:19:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.3.0',
)]
2021-06-11 16:19:16 [info] elementor-pro::elementor_pro_updater Started 
2021-06-11 16:19:16 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-11 16:19:17 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-11 16:19:17 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-11 16:19:19 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-11 16:19:19 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-11 16:19:20 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-11 16:19:20 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-11 16:19:22 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-11 16:19:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.3.0',
)]
2021-06-11 16:19:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.3.0',
)]

PHP: showing 6 of 6PHP: 2020-10-05 16:28:26 [notice X 14][/home2/theclbi7/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-07 09:57:10 [error X 1][/home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1085] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home2/theclbi7/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1085
Stack trace:
#0 /home2/theclbi7/public_html/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(3698, Object(stdClass))
#1 /home2/theclbi7/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home2/theclbi7/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home2/theclbi7/public_html/wp-includes/post.php(4260): do_action('save_post', 3698, Object(stdClass), true)
#4 /home2/theclbi7/public_html/wp-includes/post.php(4354): wp_insert_post(Array, false)
#5 /home2/theclbi7/public_html/wp-content/plugins/elementor/includes/db.php(228): wp_update_post(Array)
#6 /home2/theclbi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-02 14:19:59 [notice X 1][/home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::701] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-04 10:27:45 [error X 1][/home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home2/theclbi7/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home2/theclbi7/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(5084, NULL)
#1 /home2/theclbi7/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home2/theclbi7/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home2/theclbi7/public_html/wp-includes/post.php(4384): do_action('save_post', 5084, NULL, true)
#4 /home2/theclbi7/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home2/theclbi7/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /home2/theclbi7/public_html/wp-content/plugins/e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-20 14:56:52 [error X 1][/home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1090] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home2/theclbi7/public_html/wp-includes/class-wp-hook.php on line 294 and defined in /home2/theclbi7/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1090
Stack trace:
#0 /home2/theclbi7/public_html/wp-includes/class-wp-hook.php(294): Elementor\TemplateLibrary\Source_Local->on_save_post(5555, Object(stdClass))
#1 /home2/theclbi7/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#2 /home2/theclbi7/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home2/theclbi7/public_html/wp-includes/post.php(4384): do_action('save_post', 5555, Object(stdClass), true)
#4 /home2/theclbi7/public_html/wp-includes/post.php(4486): wp_insert_post(Array, false, true)
#5 /home2/theclbi7/public_html/wp-content/plugins/elementor/core/settings/page/manager.php(122): wp_update_post(Arr [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-26 18:53:47 [error X 1][/home2/theclbi7/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/controller.php::11] Uncaught Error: Class 'Elementor\Data\Base\Controller' not found in /home2/theclbi7/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/controller.php:11
Stack trace:
#0 /home2/theclbi7/public_html/wp-content/plugins/elementor-pro/plugin.php(140): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Co...')
#2 /home2/theclbi7/public_html/wp-content/plugins/elementor/data/manager.php(89): spl_autoload_call('ElementorPro\\Co...')
#3 /home2/theclbi7/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php(80): Elementor\Data\Manager->register_controller('ElementorPro\\Co...')
#4 /home2/theclbi7/public_html/wp-content/plugins/elementor-pro/core/app/app.php(83): ElementorPro\Core\App\Modules\SiteEditor\Module->__construct()
#5 /home2/theclbi7/public_html/wp-content/plugins/elementor-pro/plugin.php(362): ElementorPro\Core\App\App->__construct()
#6 /home2/theclbi7/public_html/wp-content/plugins/elementor-pro/plugin.php(108): ElementorPr [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2020-10-17 08:06:38 [error X 2][https://theclarityforge.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.0.11:2:70224] malformed URI sequence 
JS: 2020-11-17 14:46:17 [error X 1][https://theclarityforge.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.13:2:474266] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-12-06 14:23:21 [error X 1][https://theclarityforge.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:468052] Cannot read property \'html\' of undefined 
JS: 2020-12-23 09:57:45 [error X 58][https://theclarityforge.com/wp-includes/js/jquery/jquery.min.js?ver=3.5.1:2:31670] Cannot read property \'querySelectorAll\' of undefined 
JS: 2020-12-24 10:18:37 [error X 1][https://theclarityforge.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view29439\") has already been destroyed and cannot be used. 

				
</details>

**Comment by Aviad-Herman** [comment]
Hey,
I can't be sure by your description if this is a bug or because the page you designed wasn't adjusted to mobile.
To test this, try creating a new page and use one of Elementor's page templates. Does the responsive mode work correctly now?

You can learn more about creating responsive pages here:
https://www.youtube.com/watch?v=EqFxeluk4U4

![image](https://user-images.githubusercontent.com/73067562/122107058-5464c700-ce23-11eb-8533-09aa2172536e.png)

![image](https://user-images.githubusercontent.com/73067562/122107229-86762900-ce23-11eb-8d19-a815201a510a.png)

**Comment by Aviad-Herman** [comment]
Hey I'm sorry but I still can't reproduce.
If you still need assistance please write more exact steps to reproduce, maybe even a video.

**Comment by DrSDuarte** [comment]
Hi, 

Thank for your reply. I recorded my screen to show what I mean.
https://vimeo.com/564069563/8a755751ba

**Comment by Aviad-Herman** [comment]
Perfect, thanks for your time.

I think (can't be sure) that the problem is with the margin and padding values.
One of your page elements has a margin / padding value that looks good on desktop but is just too big for mobile and tablet.

Fixing this is easy, just write zeros "0" in that field on tablet / mobile and see if the problem is fixed.

BTW your header could be optimized. If you need help, feel free to schedule with me using the following link. I'll gladly help in return for a user interview :)

https://calendly.com/aviadh/feedback-session-with-elementor
