### ISSUE TITLE
Toolset short code and elementor for issue

### ISSUE THREAD

**Issue by jeanlevatic** [elementor/elementor#15364]
![form](https://user-images.githubusercontent.com/48252952/122084381-1014ff00-ce02-11eb-8e26-ddaca3132d49.JPG)
![slug](https://user-images.githubusercontent.com/48252952/122084411-16a37680-ce02-11eb-8cf6-85412d5385e7.JPG)

Hi there,

I use toolset and elementor and I tried to put a toolset shortcode (with an email address) in the "to" field of the elementor form, but it doesn't take it. 
I'asked both, toolset and elementor in order to have a solution to this problem, and the elementor team sent me here...

**Comment by arielk** [comment]
Due to the fact that [Toolset stops releasing new features](https://toolset.com/2022/06/whats-next-for-toolset/), we are currently suspending all requests for integration with Toolset, if the status will change in the future we can reopen it.

Thanks for your feedback!
