### ISSUE TITLE
How to register widget type after unregistering with unregister_widget_type?

### ISSUE THREAD

**Issue by shahmanish877** [elementor/elementor#15384]
Is there any way to undo unregister_widget_type('widget-name')? 
I tried register_widget_type('widget-name') but it didn't work, instead gave an error " Argument 1 passed to Elementor\Widgets_Manager::register_widget_type() must be an instance of Elementor\Widget_Base".

I want this to work because I am making a plugin from which the user can enable/disable custom widget created by me.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
