### ISSUE TITLE
Very simple features that are not currently available in elementor...

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15383]
Hi @shilo-ey 
I have been working with elementor for about 3 years and I have mastered almost all its widgets and add-ons.
There are a number of very simple shortcomings in elementor widgets, which I will discuss in detail below. I hope these shortcomings will be addressed in future versions.I hope it can help you fix the elementor shortcomings.

**slider Widget :**
1- It is not possible to create curvature in the corners of the slider. (border-radious) https://prnt.sc/15lruh2
2- It is not possible to change the slider navigation flash icon. https://prnt.sc/15lrytj

**list icon widget**
1- It is not possible to move the symbol to the right of the text.
2- It is not possible to insert a number instead of an icon

**form widget**
1- In the previous and next buttons of the form widget, it is not possible to insert icons and animations.That is, we can not create a shadow in this way : https://prnt.sc/15lsq9w
2- We can not disable the display of successful sending messages, etc. https://prnt.sc/15lt08k
3-We can not restrict the user in the number form for the contact number. For example, determine the number between 1-9 and 11 digits.
4- In the selected form fields, when you change the color of the field, the list pop-up arrow will crash. https://prnt.sc/15lu10u

**Carousel image widget**
1- It is not possible to link to each image separately. We can only put one link.
2- It is not possible to insert the desired icon for the carousel navigation flash.

**Tab Widget**
1- It is not possible to upload content directly to it (like the jet tabs plugin). Only possible with short code.
2- When we enter the shortcode, it looks like this in the editor (https://prnt.sc/15ltza9) . But the output is correct.
3-It is not possible to curve the marked parts (border-radious) https://prnt.sc/15luq4h
4- It is not possible to switch tabs to the right or left. https://prnt.sc/15luxw0

5- In the toggle widget, it is not possible to apply borders and border curvature(border-radious).
That means we can't design such a thing right now : https://prnt.sc/15r0s8j

And many more that I will cover in the future.
With thanks for your attention

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* **One request per thread**

Thanks.
