### ISSUE TITLE
Media carousels and youtube videos are not working 

### ISSUE THREAD

**Issue by ZakariaGuismi** [elementor/elementor#15392]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by drawcard** [comment]
Can you provide more information and examples?

**Comment by ZakariaGuismi** [comment]
www.kreiosmedia.com if you notice the mobile version there is plenty of
problems ( I hadn't these problems before ) so probably it's due to the
update
the problems are: carousels, videos, and our skills

**Comment by drawcard** [comment]
Seems to be working fine here?
![image](https://user-images.githubusercontent.com/1435638/122714353-522cbd80-d2a6-11eb-8994-89ad65f69f1b.jpeg)
![image](https://user-images.githubusercontent.com/1435638/122714375-5ce75280-d2a6-11eb-934d-9069079ea921.jpeg)

**Comment by ZakariaGuismi** [comment]
Yes, it is. i just went back to previous elementor versions.
thanks :)

**Comment by Aviad-Herman** [comment]
Hi,
Without more information about the bug and exact steps to reproduce we cannot help.
It's also better to contact support unless you are sure that this is a global bug in Elementor.
