### ISSUE TITLE
Reset Colors and Fonts after URL Change

### ISSUE THREAD

**Issue by heymarten** [elementor/elementor#15395]
Wordpress version 5.7.2
Elementor version 3.2.5
Elementor Pro version 3.3.0
Hello Theme 2.3.1
Child theme

Whenever I use Replace URL (Elementor function), all colors and fonts are reset to default.

**Comment by shilo-ey** [comment]
Hey @heymarten 

Thanks for reporting.

We couldn't reproduce your issue after several tests.
Please make sure no cache is activated on your site, and no other tool made these replacements before/after Elementor's.

If the issue persists please contact our support for further investigation of the issue and reference this issue.

Thanks
