### ISSUE TITLE
Elementor Forms File Upload "Choose File"Button Styling

### ISSUE THREAD

**Issue by mitchdn** [elementor/elementor#15394]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The "Choose File" button on Elementor forms File Upload isn't able to be styled, even with custom css, this is an issue as it can deviate from the branding of the relevant project
**Describe the solution you'd like**
Adding this button to the style section where users can select background colors/fonts/sizes/etc like any other type of regular button in Elementor
**Describe alternatives you've considered**
There Is no way to select this button via Custom CSS as it is fused with the file input div

**Comment by drawcard** [comment]
Styling the input button for file uploads is notoriously difficult & unlikely to be supported in Elementor, but there are some workarounds: https://stackoverflow.com/questions/572768/styling-an-input-type-file-button

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/11651 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by Novavamp** [comment]
Here is a solution, as the button is difficult to style so we hide it and create a new one in CSS:
`/* Hide the default file input */
.elementor-upload-field {
    opacity: 0;
    position: absolute;
    width: 100%;
    height: 100%;
    cursor: pointer;
    z-index: 2;
}

/* Style the container to look like a button */
.elementor-field-group-resume {
    position: relative;
    display: inline-block;
    width: 100%;
    max-width: 300px; /* Adjust as needed */
    padding: 10px;
    background-color: #0073e6; /* Button background color */
    color: #fff; /* Button text color */
    text-align: center;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.elementor-field-group-resume:hover {
    background-color: #005bb5; /* Button background on hover */
}

/* Optional: Change the label text */
.elementor-field-group-resume::before {
    content: 'Upload Resume';
    position: relative;
    z-index: 1;
    pointer-events: none;
}
`
