### ISSUE TITLE
Add support woocommerce product and adding button for hot spot

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15413]
- [x] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hello this option will be increase conversion on the e-commerce website as it simplifies navigation. For button add custom ID

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
*** Description and examples.**
* One request per thread

Thanks.
