### ISSUE TITLE
Posts Widget - Does not allow to add a "Term" or "Author"

### ISSUE THREAD

**Issue by paul-scl** [elementor/elementor#15419]
While trying to update my archive posts pages, which is sorted into certain categories ("terms"). I tried to update the "terms" to reflect the category changes we've made to some sections of our site and it will not let me type anything into the box after selecting "term" to be included. 

See screenshot below:
![image](https://user-images.githubusercontent.com/86192824/122675397-d5fb8280-d19e-11eb-964d-cde2cdee4083.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
