### ISSUE TITLE
add share button in widget posts

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15416]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hello, add a share button in posts to choose where I want to share. Example what I mean
![blog ui card](https://user-images.githubusercontent.com/66754335/122673296-6e622900-d1d8-11eb-9ceb-744594278259.png)

**Comment by Aviad-Herman** [comment]
Thanks for the suggestion.
Merging with issue #4440

**Comment by promocot** [comment]
> Thanks for the suggestion.
> Merging with issue #4440

yes is a good idea, if additional we have the ability to set color for different category of the tag will be great

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
