### ISSUE TITLE
Kit Library > View Demo > Apply Kit - not working 

### ISSUE THREAD

**Issue by healiny** [elementor/elementor#15411]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
Operating System: Linux
Software: LiteSpeed
MySQL version: MariaDB Server v10.3.29
PHP Version: 7.4.20
PHP Max Input Vars: 10240
PHP Max Post Size: 24M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 5.7.2
Site URL: https://elementor3-3beta.turquoise-spirit.co.il
Home URL: https://elementor3-3beta.turquoise-spirit.co.il
WP Multisite: No
Max Upload Size: 24 MB
Memory limit: 512M
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Language: he-IL
Timezone: 0
Debug Mode: Inactive

== Theme ==
Name: Hello Elementor Child
Version: 1.0.1
Author: Elementor Team
Child Theme: Yes
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.3.1
Parent Theme Author: Elementor Team

== User ==
Role: administrator
WP Profile lang: he_IL
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

== Active Plugins ==
Elementor
Version: 3.4.0-dev4
Author: Elementor.com

Elementor Beta (Developer Edition)
	Version: 1.1.1
	Author: Elementor.com

Elementor Pro
	Version: 3.4.0-dev19
	Author: Elementor.com
== אלמנטור - Compatibility Tag ==

Elementor Pro: Incompatible
== אלמנטור פרו - Compatibility Tag ==

== Elements Usage ==

wp-page : 1
	login : 1
	text-editor : 1
== Log ==

Log: showing 6 of 62021-06-18 18:20:48 [info] elementor::elementor_updater Started
2021-06-18 18:20:48 [info] אלמנטור/Upgrades - _on_each_version Start
2021-06-18 18:20:48 [info] אלמנטור/Upgrades - _on_each_version Finished
2021-06-18 18:20:48 [info] Elementor data updater process has been completed. [array (
'plugin' => 'אלמנטור',
'from' => '3.2.5',
'to' => '3.4.0-dev4',
)]
2021-06-18 18:20:48 [info] Elementor data updater process has been queued. [array (
'plugin' => 'אלמנטור',
'from' => '3.2.5',
'to' => '3.4.0-dev4',
)]
2021-06-19 10:41:24 [info] Elementor data updater process has been completed. [array (
'plugin' => 'אלמנטור פרו',
'from' => '3.3.0',
'to' => '3.4.0-dev19',
)]

PHP: showing 1 of 1PHP: 2021-06-19 10:20:10 [notice X 4][/home/sissilve/sites/elementor3-3beta/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
```
https://www.loom.com/share/50e69bcd79ff444491ec94a19c6e9c56

Work only with elementor plugins, and Hello Elementor Child.
The bug also exists in the themes - Hello Elementor and twenty one of wordpress.

**Comment by healiny** [comment]
https://www.loom.com/share/50e69bcd79ff444491ec94a19c6e9c56

Work only with elementor plugins, and Hello Elementor Child.
Also does not work in the template Hello Elementor and twenty one of wordpress.

**The system Info:**
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.29
	PHP Version: 7.4.20
	PHP Max Input Vars: 10240
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://elementor3-3beta.turquoise-spirit.co.il
	Home URL: https://elementor3-3beta.turquoise-spirit.co.il
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: he-IL
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.4.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.0-dev19
		Author: Elementor.com


== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== אלמנטור פרו - Compatibility Tag ==
	


== Elements Usage ==
	
	wp-page : 1
		login : 1
		text-editor : 1


== Log ==
	
Log: showing 6 of 62021-06-18 18:20:48 [info] elementor::elementor_updater Started 
2021-06-18 18:20:48 [info] אלמנטור/Upgrades - _on_each_version Start  
2021-06-18 18:20:48 [info] אלמנטור/Upgrades - _on_each_version Finished 
2021-06-18 18:20:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.2.5',
  'to' => '3.4.0-dev4',
)]
2021-06-18 18:20:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.2.5',
  'to' => '3.4.0-dev4',
)]
2021-06-19 10:41:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.3.0',
  'to' => '3.4.0-dev19',
)]

PHP: showing 1 of 1PHP: 2021-06-19 10:20:10 [notice X 4][/home/sissilve/sites/elementor3-3beta/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by d19dotca** [comment]
Odd, that is definitely works for me in my testing so far. Best to link this to the 3.3 beta thread too though as this feature isn't actually public yet and this post so far doesn't mention the fact this is a beta feature right now. 

https://github.com/elementor/elementor/issues/15336

**Comment by shilo-ey** [comment]
Hi @healiny, thanks,

As @d19dotca beta issues should be referred in the pinned Beta issue for us to manage it properly.

#15336

Please explain your issue there.

Thanks!
