### ISSUE TITLE
A HREF TAG for Sections and Columns

### ISSUE THREAD

**Issue by openstoic** [elementor/elementor#15423]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Columns and sections are not linkable

**Describe the solution you'd like**
A field to link a whole section or column 

**Describe alternatives you've considered**
A link wrapper widget

**Additional context**
It's quite simple.

Some plugins already do this
https://theplusaddons.com/plus-extras/wrapper-link/
https://wordpress.org/plugins/make-column-clickable-elementor/

But this must be clearly something core.

**Comment by paauserrat** [comment]
Please, this is needed as sometimes we need a section or column to be clickable. Also, it would be great if any elementor widget has this ability.

I'm using custom HTML to achive this in a custom made google star rating widget with elementor:
![image](https://user-images.githubusercontent.com/73240206/122729311-52fb2a80-d279-11eb-96fb-8fbea0c7c2e4.png)

But I need to go widget from widget to add the custom code for it to work. I would like to be able to go to the section and make all the inside elements clickable

**Comment by d19dotca** [comment]
Yes, that'd be awesome to have this functionality. Similar to a "link wrapper" element that Oxygen Builder has, I guess.

**Comment by Aryehhirsc** [comment]
Im going to comment here because I want this to get more visibility I can really use this feature

**Comment by DorShahar** [comment]
Hi
Technically speeking, a link shold be added to an anchor tag ('a') and not to a wrapper (`section` or `div`). If there are specific widgets you wish to add links to, you are welcome to open a new issue, and ask for a feature request there. 

I'm leaving this thread open - please add your use cases and motivations, so we might think on a workaroud for this request.


Thanks.

**Comment by openstoic** [comment]
> Hi
> Technically speeking, a link shold be added to an anchor tag ('a') and not to a wrapper (`section` or `div`). If there are specific widgets you wish to add links to, you are welcome to open a new issue, and ask for a feature request there.
> 
> I'm leaving this thread open - please add your use cases and motivations, so we might think on a workaroud for this request.
> 
> Thanks.

This is completely trivial.

The feature asked here could be two-folded:

1. The simplest way, from my perspective, is behaving similarly to the **Image Widget**: it simply adds the `<img>` and then adds the `<a>` tag inside the `<img>`. If this has already been done with many widgets, like image one, this is obviously easy to be introduced in any other widget.
2. A more complex way, but still acceptable: An specific Link Wrapper Widget. The advantage of this, is that you could completely wipe the linking function from 100% of the widgets, and delegate this to this widget. It will simply add this wrapper to any object within (this may operate like a section, but an anchor tag instead).

If I were an Elementor programmer, and would like to spend the least time possible, I would choose the first option, that could be done in 15 minutes copying and pasting the code from other widgets. But if they want to be the "pro-Elementor team with best features available out there in the market", then the second option is a really pro solution, identical to what Oxygen Builder already have.

I have to say that the decision of leaving this to 3rd party plugins is obnoxious because this should be the bread and butter of almost any respectable front-end designer out there. Linking a whole div or section is truly essential.

Currently, I've solved this years ago with some classes and JavaScript. But then I tested Oxygen Builder and I though, why Elementor doesn't already implement this by default? Are we crazy? I don't like how I have solved it my way because it makes convoluted everything for something that is one of the most trivial aspects in HTML.

**Comment by 79ho3ein** [comment]
If I'm not mistaken, the number #10969 is in the same issue. And many people have this request to be added to elementor.
It is strange why elementor does not have such an important feature and also does not add. A feature that I do not think is time consuming to add.
In any case, I hope dear developers pay attention to our request and add this feature to elementor...

**Comment by GBallzus** [comment]
+1

**Comment by BrockwayProd** [comment]
+1

**Comment by 79ho3ein** [comment]
hi @DorShahar
Does elementor have a program to add this feature? Will we see it in 2021?
Or does elementor still have no plan for it?
thank you

**Comment by andrewvink** [comment]
What we do as a work around is add this JS in the Custom Code area (Body - End)

1 - Create your column add the class "column-clickable" (Advanced Tab)
2 - Make sure there is a button or a heading with a link inside that column.  

The JS will find the first link inside the column (if you have more than one link) and use that for your column link. 

`<script>
// Just  to a column in Elementor and make sure a heading or button inside that column has the link to make it clickable.
jQuery(document).ready(function() {
	jQuery('body').find('.column-clickable').css('cursor', 'pointer');
	jQuery('body').on('click', '.column-clickable', function() {		
		var href = jQuery(this).find('a').attr('href');
		window.location = href;
	});
});
</script>`

**Comment by SirLouen** [comment]
> What we do as a work around is add this JS in the Custom Code area (Body - End)
> 
> 1 - Create your column add the class "column-clickable" (Advanced Tab)
> 2 - Make sure there is a button or a heading with a link inside that column.
> 
> The JS will find the first link inside the column (if you have more than one link) and use that for your column link.
> 
> ```
> <script>
> // Column Clickable
> jQuery(document).ready(function() {
> 	if( !jQuery('body').hasClass('elementor-editor-active') ) {
> 		jQuery('body').find('.column-clickable').css('cursor', 'pointer');
> 		jQuery('body').on('click', '.column-clickable', function() {		
> 			var href = jQuery(this).find('a').attr('href');
> 			window.location = href;
> 		});
> 	}
> });
> </script>
> ```

This is what we already do, and it feels 100% obnoxious.

**Comment by Caspoor** [comment]
> 
> 
> > What we do as a work around is add this JS in the Custom Code area (Body - End)
> > 1 - Create your column add the class "column-clickable" (Advanced Tab)
> > 2 - Make sure there is a button or a heading with a link inside that column.
> > The JS will find the first link inside the column (if you have more than one link) and use that for your column link.
> > ```
> > <script>
> > // Column Clickable
> > jQuery(document).ready(function() {
> > 	if( !jQuery('body').hasClass('elementor-editor-active') ) {
> > 		jQuery('body').find('.column-clickable').css('cursor', 'pointer');
> > 		jQuery('body').on('click', '.column-clickable', function() {		
> > 			var href = jQuery(this).find('a').attr('href');
> > 			window.location = href;
> > 		});
> > 	}
> > });
> > </script>
> > ```
> 
> This is what we already do, and it feels 100% obnoxious.
> 
> PS: Do it vanilla JS don't use JQuery for such simple functiontionality
> 
> ```js
> <script type="text/javascript" id="click-script"> 
>  		const clicklinks = document.querySelectorAll(".clickable");
> 		clicklinks.forEach((clicklink) => {
> 			clicklink.addEventListener("click", function() { 
> 				window.location.href = clicklink.dataset.clicklink;
> 			}); 
> 			clicklink.style.cursor = "pointer";
> 		});
> 	</script>`
> ```

Thanks for the code. It made the column clickable, but I wasn't able to open it in a new tab nor the link appears on the left hand corner when I hover it. Can u fix this please?

**Comment by Rayken** [comment]
I'll just post [this](https://github.com/elementor/elementor/issues/10969#issuecomment-900099906) here. It's for columns but can be modified to work with sections too. It's not a perfect solution, but it's as "native" as it gets (afaik) and it beats JavaScript trickery. Read the comments/gist before use though.

**Comment by SirLouen** [comment]
> I'll just post [this](https://github.com/elementor/elementor/issues/10969#issuecomment-900099906) here. It's for columns but can be modified to work with sections too. It's not a perfect solution, but it's as "native" as it gets (afaik) and it beats JavaScript trickery. Read the comments/gist before use though.

Hope they include this in Elementor default

**Comment by shilo-ey** [comment]
I merged this issue with #10969, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

I can share that we are currently working on a solution that would resolve this demand.

Thanks for your feedback!
