### ISSUE TITLE
Not a complete list of google fonts

### ISSUE THREAD

**Issue by dimaeromin97** [elementor/elementor#15436]
👋🏻

I can't find at least the "[Shippori Mincho](https://fonts.google.com/specimen/Shippori+Mincho)" and "[Lexend](https://fonts.google.com/specimen/Lexend?query=Lexend)" fonts in the Font Family list.

What is the reason they are not on the list?

Thank you!

**Comment by Aviad-Herman** [comment]
For performance concerns we can't load everything.
If you have Elementor pro you can always import fonts OR use the custom code feature for the same purpase.
