### ISSUE TITLE
Report a problem in the form widget. (Multiple choice field)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15431]
hi @shilo-ey 
Thank you for fixing the form widget bugs in the new elementor pro update.
But one problem with this widget is that if we make the selection field multiple-choice in the form widget, the user will not realize that it can select multiple items.
I suggest placing a check box next to each option, so that the user knows how many items to select.
Just like this picture : https://prnt.sc/167nza7
Please review this offer. The selection field is very useful in the form widget. The current situation is not favorable at all.

Thank you for your efforts

**Comment by d19dotca** [comment]
I believe it currently generates using regular HTML5 as all web browsers display selection lists, but you're right it'd be nice to somehow make it more obvious for users who aren't as tech savvy to realize it's a multi-select field.

**Comment by sushmak02** [comment]
I have the latest Elementor ( 3.2.5 ) and Elementor Pro (3.3.1) Versions on my site.
My form fields are not displaying correctly in the editor and frontend too! I can see few notices in the error log related to Elementor Pro - https://share.getcloudapp.com/NQuoY1BO
Is this a known issue or I am missing something at my end?

**Comment by 79ho3ein** [comment]
> I believe it currently generates using regular HTML5 as all web browsers display selection lists (which is basically the "industry standard" since it's the method built-in to web browsers), but you're right it'd be nice to somehow make it more obvious for users who aren't as tech savvy to realize it's a multi-select field.

Thanks for the reply. Yes, unfortunately this is a problem and the fact that the field is multiple choice is not at all understandable to users. I hope Mentor will further develop the form widget and work on it. If I want to write a request about its shortcomings, it will take 1 day.
Finally, thank you again for your response🌹

**Comment by 79ho3ein** [comment]
@sushmak02 
I have never seen such a problem. do you use the original elementor pro?

**Comment by sushmak02** [comment]
Yes @79ho3ein

**Comment by 79ho3ein** [comment]
> Yes @79ho3ein

So it is better to contact elementor support. This problem can have many causes.
Installing many plugins and ...

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
