### ISSUE TITLE
Layout issue with Playlist Widget

### ISSUE THREAD

**Issue by Lexlufer** [elementor/elementor#15443]
Playlist Widget appears randomly broken on the live page. Just in editing mode, it shows up correctly.

Page:
<img width="1430" alt="Bildschirmfoto 2021-06-22 um 10 42 49 AM" src="https://user-images.githubusercontent.com/86325398/122995956-91dccd80-d3aa-11eb-9a04-96ea2d086518.png">

Editing mode:
![issue elemntor](https://user-images.githubusercontent.com/86325398/122996369-16c7e700-d3ab-11eb-9fe8-0e90f9255770.JPG)

**Comment by Aviad-Herman** [comment]
Hey,
Can you please check two things?
1) try going to elementor --> settings --> experiments and turn off the Improved asset loading and optimized DOM experiments.
2) try disabling all other plugins

Dos this solve the problem?

**Comment by Lexlufer** [comment]
Thanks, @Aviad-Herman  . Turns out it was the "Complianz | GDPR/CCPA Cookie Consent" Plugin. I just turned off the Elemntor toggle and it worked. Thanks!

**Comment by Aviad-Herman** [comment]
Thanks for the update!
