### ISSUE TITLE
Wordpress/Elementor - Post Content multimedia not full width

### ISSUE THREAD

**Issue by blw1996** [elementor/elementor#15444]
Hi all,

I’ve had this issue for a while now. Using Wordpress + Elementor Pro.

For context:
I have created a blog post template with a simple title (H1), description (H2) and then ‘post content’ widget. I then create posts using Gutenberg and add post content in there. 

The issue:
In Gutenberg, YouTube embeds, images etc. show up full width but when I view on the front-end, the text is full width but the YouTube embed, images and any multimedia only show 90%. I’ve tried adding images with 100% width, but no luck.  Originally, it was one column and I added a new column to reduce that first column width, but the embed scaled down so it's not an issue of the content not being 'wide' enough.

Here is the link to an example: https://www.bior.org.au/news/dr-david-paton-discusses-biodiversity-in-the-mt-lofty-ranges-on-abc-891-adelaide/

Any ideas? Would really appreciate your help.
Thank you.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

As for your specific case - I didn't fully understand it, but try to solve it with:

1. Site Settings > Layout
2. Post settings > Style > Padding
3. Page Settings > Settings > Page layout (https://elementor.com/help/canvas-vs-full-width/) 

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
