### ISSUE TITLE
edit with elementor not showing up

### ISSUE THREAD

**Issue by jblanco106** [elementor/elementor#15453]
![image](https://user-images.githubusercontent.com/86384343/123172516-d605c600-d4af-11eb-9a80-2c2e779fb160.png)

In every page its not showing up

**Comment by Aviad-Herman** [comment]
Hey,
Are we talking about pages that are already edited with elementor or pages that are currently Guttenberg etc?
We only show this button when the page is already edited with elementor because converting an existing page to elementor might break its content.

**Comment by jblanco106** [comment]
Hi

 

Thank for your support. So what do I need to do to edit an existing theme that I like?

 


Business /Multi-Media Virtual Assistant

Pineapple Staffing // Temark International Inc

t.    <https://links94.mixmaxusercontent.com/5f5ab7132493cb38dabfeecb/l/Dg6l4hA9z29eAZbOn?messageId=JcfVZkaE6kBwfstCp&rn=i82YuFGbCByQgwWZv5EIuFGa0FmbvpkI&re=i02bj5CbpFWbnBUZsBHchVmbpBnLvNmbhxmYuomI&sc=false> (63) 906-025-5519 
e.   ***@***.***> ***@***.***
w.  <https://pineapplestaffing.com/> https://pineapplestaffing.com/
a.  4990 E Mediterranean Drive, Suite D, Sierra Vista, AZ 85635
Skype Name: live:jonathan.blanco106

**Comment by Aviad-Herman** [comment]
When you create / edit a post make sure you select "Edit with Elementor"

![Screen Shot 2021-06-24 at 16 18 21](https://user-images.githubusercontent.com/73067562/123269817-037e5e00-d508-11eb-8d28-5688dd33636f.png)


![image](https://user-images.githubusercontent.com/73067562/123269677-dd58be00-d507-11eb-9e45-abbb16232945.png)
