### ISSUE TITLE
Dev 3.4.0 Dev4 <style> were missing upon generate the site.

### ISSUE THREAD

**Issue by Jonathlee** [elementor/elementor#15455]
The latest version of 3.4.0 Dev4

It direct output the CSS, it missed the tag of `<style>` before these CSS were generated.

This happen in both front end and back end.

![image](https://user-images.githubusercontent.com/696956/123200253-ed11db80-d4e2-11eb-8f7e-55cedb7de07c.png)
![image](https://user-images.githubusercontent.com/696956/123200277-f8650700-d4e2-11eb-8cc1-d172873fd744.png)
![image](https://user-images.githubusercontent.com/696956/123201567-8215d400-d4e5-11eb-82ba-447447dea0c4.png)
![image](https://user-images.githubusercontent.com/696956/123201602-92c64a00-d4e5-11eb-9be6-8e6fe28a0c9c.png)

Look at the text description, html not rendered properly.

Testing site : https://dev.jlex.my/beta-page/

**Comment by d19dotca** [comment]
Yes, I see this all over the place too. It's been there for a while though, at least several dev iterations now. 

PS - You made the title "6.4.0" when it should be "3.4.0".

**Comment by Jonathlee** [comment]
@d19dotca  thank you for the noticing, my bad 😆

**Comment by rodolphebertozzo** [comment]
+1

**Comment by Aviad-Herman** [comment]
Hi, thank you very much for the detailed report.
All these issues will be fixed before 3.4.0 is released to the general public.
We generated an automatic list of all the places the occurs and we will fix them programatically.
I added a link to this thread in our internal task management system.

**Comment by Aviad-Herman** [comment]
Hey guys,
Most issues are currently fixed in the developer edition latest version.
Do any of these problems still happen?
Thanks for your help

**Comment by Jonathlee** [comment]
the problem still exist

![image](https://user-images.githubusercontent.com/696956/125192737-effb2300-e27b-11eb-90c4-043a4c10a1bd.png)
![image](https://user-images.githubusercontent.com/696956/125192743-f9848b00-e27b-11eb-94f6-ca295421a3ea.png)
![image](https://user-images.githubusercontent.com/696956/125192757-05704d00-e27c-11eb-9b98-4c90d238d5f1.png)
