### ISSUE TITLE
CSS-Rules-Text appears in front of widgets

### ISSUE THREAD

**Issue by blwtxc** [elementor/elementor#15456]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

After update to newest version CSS-Rules-Text appears in front of widgets in rendered page.

e.g.:
<pre>
/*! elementor - v3.2.5 - 23-06-2021 */ .elementor-widget-image{text-align:center}.elementor-widget-image a{display:inline-block}.elementor-widget-image a img[src$=".svg"]{width:48px}.elementor-widget-image img{vertical-align:middle;display:inline-block}
</pre>

<pre>
/*! elementor - v3.2.5 - 23-06-2021 */ .elementor-widget-video .elementor-widget-container{overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.elementor-widget-video .elementor-open-inline .elementor-custom-embed-image-overlay{position:absolute;top:0;left:0;width:100%;height:100%;-webkit-background-size:cover;background-size:cover;background-position:50%}.elementor-widget-video .elementor-custom-embed-image-overlay{cursor:pointer;text-align:center}.elementor-widget-video .elementor-custom-embed-image-overlay:hover .elementor-custom-embed-play i{opacity:1}.elementor-widget-video .elementor-custom-embed-image-overlay img{display:block;width:100%}.elementor-widget-video .e-hosted-video .elementor-video{-o-object-fit:cover;object-fit:cover}
</pre>

Text is not enclosed in style tags so it appears as plain text on page.

Tested with themes: Twenty Twenty, Hello Elementor

## Steps to reproduce

Update to newest Dev version.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.48 (Ubuntu)
	MySQL version: MySQL Community Server - GPL v8.0.25
	PHP Version: 7.4.20
	PHP Max Input Vars: 3000
	PHP Max Post Size: 96M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://xxxxx
	Home URL: https://xxxxx
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 384M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty Child
	Version: 1.0
	Author: xxxxx
	Child Theme: Yes
	Parent Theme Name: Twenty Twenty
	Parent Theme Version: 1.7
	Parent Theme Author: the WordPress team

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.9.7
		Author: Delicious Brains

	Advanced Custom Fields Multilingual
		Version: 1.8.2
		Author: OnTheGoSystems

	Custom Post Type UI
		Version: 1.9.2
		Author: WebDevStudios

	Ele Custom Skin
		Version: 3.1.1
		Author: Dudaster.com

	Elementor
		Version: 3.4.0-dev5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.0-dev21
		Author: Elementor.com

	GDPR Cookie Consent
		Version: 2.0.3
		Author: WebToffee

	Media Library Folders for WordPress
		Version: 7.0.0
		Author: Max Foundry

	WP Cerber Security, Anti-spam & Malware Scan
		Version: 8.8.5
		Author: Cerber Tech Inc.

	WPFront Scroll Top
		Version: 2.0.4.04013
		Author: Syam Mohan

	WP Mail SMTP
		Version: 2.8.0
		Author: WPForms

	WPML Media
		Version: 2.6.4
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.4.10
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.8
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.10.6
		Author: OnTheGoSystems


== Must-Use Plugins ==
	aaa-wp-cerber.php
		Version: 1.0
		Author: Cerber Tech Inc.


== Elementor - Compatibility Tag ==
	Ele Custom Skin: Incompatible
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	Ele Custom Skin: Incompatible

```

</details>

**Comment by Aviad-Herman** [comment]
Hi,
Thanks for the bug report.
It will be solved before 3.4.0 will be released to the general public.
The bug is currently only in the developer edition.
