### ISSUE TITLE
[BUG] - Elementor Pro - Menu cart widget do not render properly

### ISSUE THREAD

**Issue by projektorius96** [elementor/elementor#15451]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If I click on a Menu cart widget for a default pop-up (_on the right hand side_), even if cart is provided with Products the pop-up do not display cart preview whilst on Live-editing [**image-1**]. However Products are rendered in the cart list only if statically previewed (**not** whilst editing) [**image-2**]. It means I will not be able to see changes reflected whilst on live editing. I will have to foresee the design make changes and reload static page so each time I could preview changes made upon. It's a time waster and inconvenient. Definitely not the way Elementor should behave.

## Steps to reproduce
Simply up to date version of Elementor, Elementor Pro and Wordpress. **Notice**: changing theme e.g. from Hello Elementor to Twenty Sixteen does not help. Keeping in mind I do work on localhost currently. Still this is and old issue [proof on **image-3**]
**Live-editing**
[image-1](https://flic.kr/p/2m7dVSX)
**Static-preview**
[image-2](https://flic.kr/p/2m7dVSg)
Opened ticket since March, still no fix:
[image-3](https://flic.kr/p/2m7a9Sy)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug **consistently** using the steps above.

**Comment by avivu** [comment]
Hello @projektorius96,
We are aware of this bug and will release a fix soon.
Thank you!

**Comment by projektorius96** [comment]
Finally! 🏁

**Comment by projektorius96** [comment]
@avivu Menu cart live editing finally works ! Elementor Pro v3.4 Beta Release #15947  the bug !
Tested on localhost using :

- Elementor v3.5.0-dev7
- Elementor Pro v3.5.0-dev3

**Comment by shilo-ey** [comment]
This feature has been implemented in Elementor Pro 3.4.0

Feel free to update

Thanks!

**Comment by de-er-kid** [comment]
After adding a product to cart it takes a few seconds to view cart data & it's blank for that much time, can we Add 'Loading..' text to elementor Menu Cart Widget while the cart data are being retrieved ?

There could be a 'No products in the cart' when no products are in the cart. But after adding a product to cart it's totally blank until the new cart data is retrived, A loading text with spinner while loading data through ajax is an common used method.

Or could anyone say where is the source code for this widget inside the plugin ?
