### ISSUE TITLE
Additionnal Breakpoints - UI

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#15473]
Beware of the dark mode, the already selected breakpoints are not highlighted unlike the clear mode.

**Comment by udidol** [comment]
Hi @rodolphebertozzo,
Not sure what you mean. Can you provide a screenshot?

**Comment by rodolphebertozzo** [comment]
@udidol 
![clear](https://user-images.githubusercontent.com/56270626/123959965-10d79480-d9af-11eb-806a-a30e58ea068e.PNG)
![dark](https://user-images.githubusercontent.com/56270626/123959971-1208c180-d9af-11eb-88b0-81c06fe91c9b.PNG)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.0

Feel free to update

Thanks!
