### ISSUE TITLE
Form submit issue with mailerlite.php on iOS and Android

### ISSUE THREAD

**Issue by ppwebox** [elementor/elementor#15474]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

A newsletter form built with Elementor Pro, located in the footer, has a submit issue with mailerlite.php on both iOS and Android, causing the following PHP error: 
Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /DELETED/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php on line 209'

The form works perfectly with desktop browser, such as Firefox, Safari, Chrome, etc. After actions include sending an E-Mail to the admin, redirecting user to the thank you page, and transmitting the form data to MailChimp, which sends a welcome mail to user.   

But on iOS and Android devices, the only after action working is the admin mail notification, and a small error notice appears below the form - a red X but without any message. 

## Steps to reproduce
Submit filled-in form on iOS or Android.

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB package v10.4.17
	PHP Version: 7.4.6
	PHP Max Input Vars: 20000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: -
	Home URL: -
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: Kadence
	Version: 1.0.26
	Author: Kadence WP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

== Active Plugins ==
	Advanced Scripts
		Version: 1.1.0
		Author: Clean Plugins

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	CAOS
		Version: 4.1.2
		Author: Daan from FFW.Press

	Cart Reports for WooCommerce
		Version: 1.2.9
		Author: WooCommerce

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Complianz | GDPR/CCPA Cookie Consent
		Version: 5.1.0
		Author: Really Simple Plugins

	Custom Fonts
		Version: 1.3.2
		Author: Brainstorm Force

	Easy Updates Manager
		Version: 9.0.9
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.2.5
		Author: Elementor.com

	Elementor Form Builder for MEC
		Version: 1.1.6
		Author: Webnus

	Elementor Pro
		Version: 3.3.1
		Author: Elementor.com

	Elementor Shortcode Builder for MEC
		Version: 1.5.6
		Author: Webnus

	Elementor Shortcode Designer
		Version: 1.2.1
		Author: Webnus

	Elementor Single Builder for MEC
		Version: 1.6.5
		Author: Webnus

	Falcon
		Version: 2.0.4
		Author: eLightUp

	GTmetrix for WordPress
		Version: 0.4.4
		Author: GTmetrix

	Kadence Custom Fonts
		Version: 1.1.0
		Author: Kadence WP

	Kadence WooCommerce Elementor
		Version: 1.0.6
		Author: Kadence WP

	Kadence WooCommerce Email Designer
		Version: 1.4.7
		Author: Kadence WP

	Mailchimp for WooCommerce
		Version: 2.5.1
		Author: Mailchimp

	Maintainn Tools
		Version: 2.3.3
		Author: Maintainn

	mame TWINT for WooCommerce
		Version: 2.2.3
		Author: mame webdesign hüttig

	Manage Notification E-mails
		Version: 1.8.0
		Author: Virgial Berveling

	Modern Events Calendar
		Version: 5.20.0
		Author: Webnus

	Pods - Custom Content Types and Fields
		Version: 2.7.28
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.66
		Author: Rank Math

	Really Simple SSL
		Version: 4.0.15
		Author: Really Simple Plugins

	Search Exclude
		Version: 1.2.6
		Author: Roman Pronskiy

	Sequential Order Numbers for WooCommerce
		Version: 1.3.5
		Author: WebToffee

	TablePress
		Version: 1.13
		Author: Tobias Bäthge

	User Role Editor
		Version: 4.60
		Author: Vladimir Garagulya

	WooCommerce
		Version: 5.4.1
		Author: Automattic

	WooCommerce Checkout Field Editor
		Version: 1.6.0
		Author: WooCommerce

	WooCommerce Custom Thank You Pages
		Version: 1.0.4
		Author: Jeroen Sormani

	WooCommerce Email Customizer
		Version: 1.1.19
		Author: WooCommerce

	WooCommerce Integration for MEC
		Version: 1.4.2
		Author: Webnus

	WP Rocket
		Version: 3.9.0.1
		Author: WP Media

	WP Server Stats
		Version: 1.6.10
		Author: Saumya Majumder, Acnam Infotech

== Elementor - Compatibility Tag ==
	
	Elementor Form Builder for MEC: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Elementor Shortcode Builder for MEC: Compatibility not specified
	Elementor Shortcode Designer: Compatibility not specified
	Elementor Single Builder for MEC: Compatibility not specified
	Kadence WooCommerce Elementor: Compatibility not specified
	Kadence Woocommerce Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 2
		divider : 17
		form : 17
		heading : 53
		icon-box : 8
		icon-list : 1
		image : 9
		nav-menu : 27
		search-form : 9
		share-buttons : 9
		spacer : 8
	header : 2
		image : 5
		nav-menu : 7
		search-form : 2
		woocommerce-menu-cart : 5
	page : 12
		event_booking : 3
		event_breadcrumbs : 2
		event_content : 2
		event_cost : 4
		event_custom_data : 2
		event_date_module : 4
		event_export_module : 2
		event_google_map : 2
		event_location : 4
		event_organizer : 2
		event_qr : 2
		event_social : 2
		event_tags : 2
		event_time_module : 4
		event_title : 5
		form : 3
		heading : 14
		shortcode : 2
		single-product-title : 1
		spacer : 1
		text-editor : 3
	product : 1
		product-social : 1
		spacer : 1
		theme-post-title : 1
		wc-categories : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-additional-information : 1
		woocommerce-product-content : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 2
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-stock : 1
		woocommerce-product-title : 1
	wp-page : 20
		MEC-SHORTCODE-BUILDER : 1
		form : 8
		heading : 68
		icon : 1
		image : 1
		shortcode : 13
		sitemap : 1
		spacer : 4
		text-editor : 26
		video : 2
	single-page : 3
		heading : 2
		icon : 1
		shortcode : 1
		spacer : 1
		theme-post-content : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		heading : 1
		theme-archive-title : 1
	product-archive : 1
		MEC-SHORTCODE-BUILDER : 3
		heading : 6
		text-editor : 3
	error-404 : 1
		heading : 3
		nav-menu : 1
		search-form : 1

== Log ==
	
PHP: showing 3 of 3PHP: 2021-05-12 02:00:55 [warning X 19][/XXX/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/XXX/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 23:30:53 [error X 1][/XXX/wp-content/plugins/elementor/core/documents-manager.php::518] Uncaught Error: Call to a member function get_post() on bool in /XXX/wp-content/plugins/elementor/core/documents-manager.php:518
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /XXX/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /XXX/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /XXX/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#4 /XXX/wp-includes/plugin.php(484): WP_Hook->do [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-22 00:44:54 [warning X 5][/XXX/wp-content/plugins/elementor-pro/modules/forms/actions/mailerlite.php::209] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by ppwebox** [comment]
Addendum to clarify some details. 

I use the same form twice in the footer: one styled for desktop/tablet and one for mobile. Both have the same form ID and fields etc. The mobile form had MailerLite selected accidentially as after action, instead of MailChimp, which I fixed. But this does of course not explain the " Invalid argument supplied for foreach" error thrown with MailerLite. I have given a different form iD to the mobile form just in case this could cause the error. But I still think this is bug with Elementor's MailerLite.

**Comment by rami-elementor** [comment]
@ppwebox have you tried to change the form ID's? using the same form ID can cause issues.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
