### ISSUE TITLE
Ability to add before footer template

### ISSUE THREAD

**Issue by Aryehhirsc** [elementor/elementor#15487]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like to add a contact section above my footer for most but not all of my web pages & on top of that I add a small about us section on some pages as well . Other apps like Elementor Header & Footers offer a before footer option.

**Describe the solution you'd like**
Add before footer template

**Describe alternatives you've considered**
An alternative is to create different footers with conditions but this is very inefficient

**Comment by shilo-ey** [comment]
Hi @Aryehhirsc 

Thanks,
You can use the [Theme Locations API](https://developers.elementor.com/theme-locations-api/) to register a custom location before the footer.

You need to:
1. Register the Pre-footer location for it to be available in the Theme Builder
2. Render the location in your theme with `do_location()` above your footer

Ref: https://developers.elementor.com/theme-locations-api/


Thanks

**Comment by Aryehhirsc** [comment]
Thanks for your reply. I understand there is a way to get this to work with the Theme API. My suggestion was to add this as a feature that is preinstalled with elementor as other plugins offer. The idea for me at least is to minimize the number of plugins needing to load on each page.
