### ISSUE TITLE
Need a Good Post Category Widget & Custom Loop Support

### ISSUE THREAD

**Issue by johndejaciv** [elementor/elementor#15489]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It's been a longstanding need of my team to have a robust post category widget to use within elementor. We often need to display category grids/lists, and functionality is vastly limited for doing these types of queries. We need the same capabilities offered with standard posts for post categories as well, as this is a crucial design elementor for custom post type-heavy sites with many posts and blogs/shops.

**Describe the solution you'd like**

I would love for ELementor to offer a new post category widget and to integrate the use of custom loop templates for post types, so separate plugins are not needed for this crucial design elementor. I'd like this to also apply to post terms/categories, so there can be robust use of dynamic content and layouts when categorizing posts in archive pages.

**Describe alternatives you've considered**

I've used AE Pro, Ele custom skin pro, and Jet Blog but all of these have limits that do not allow the above-desired functionality to be achieved.

**Additional context**

Thanks!

**Comment by Nazrinn** [comment]
Elementor definitely need some [WordPress Loop](https://codex.wordpress.org/The_Loop) functionality. It would also help with Custom Field such as repeaters.

It would work much better if Elementor had some more modular/composite widgets similar to Oxygen in that regard, rather than completely "premade" widget where its content and layout of its content would be determined by inflexible settings.

**Comment by Aviad-Herman** [comment]
Hey,
Good suggestions everyone.
Merging with #4440

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
