### ISSUE TITLE
Error 404 na gravação

### ISSUE THREAD

**Issue by WACAMPAN** [elementor/elementor#15483]
Ao inserir html ou script na page com plugin elementor consta não encontrado (erro no servidor ´404´). Quais sugestões para corrigir esse bug?

**Comment by Aviad-Herman** [comment]
Hi,
You need to contact support and share your site with them. We can't help you without exact details.

**Comment by WACAMPAN** [comment]
Com quem? ELEMENTOR?

**Comment by Aviad-Herman** [comment]
Yes please:
https://elementor.com/contact/
