### ISSUE TITLE
Enable setting a global section overflow value

### ISSUE THREAD

**Issue by asafm7** [elementor/elementor#15491]
While the default section overflow value is visible, on a full-width design it is important to set it to hidden in order to prevent elements weirdly overflowing the screen.

Right now, there is a need to manually set it to each section, and remembering doing it for each new section. Or using custom CSS, which makes the Elemnetor setting obsolete and might lead to confusion in the future.

I suggest enabling a global setting for it. Maybe even enable a global setting to each and every widget setting? Or at least enable changing the default to for each setting that has a default

**Comment by promocot** [comment]
will be better if introduced, global presets for section, padding & margin, shadow, border, corner radios like in color and typography. One time for setup global system, after faster selection in editing. If you use import/export you will be efficient

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #5252, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
