### ISSUE TITLE
Enhance the Nav Menu widget

### ISSUE THREAD

**Issue by asafm7** [elementor/elementor#15492]
Enhance the Nav Menu widget:

- Add "before" and "after" sections. For example for adding differently-designed "Sign Up" and "Log In" buttons (that will appear inside the mobile hamburger menu as well)
- Add an option of a full-screen mobile hamburger menu (that covers the full width and height of the screen when open)
- Add an option to change and disable the opening animation of the mobile hamburger menu

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4787, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
