### ISSUE TITLE
Make page backgrounds drivable using dynamic data like section backgrounds can be

### ISSUE THREAD

**Issue by DavidGMiles** [elementor/elementor#15498]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

A simple request - take the dynamic data options for driving the source of section backgrounds and apply the same code to page backgrounds - this will allow for page backgrounds to be driven from ACF fields in the backend

**Comment by arielk** [comment]
Duplicate: https://github.com/elementor/elementor/issues/19322
