### ISSUE TITLE
Add scenario for 404 page (automatic redirect on home page after xxx seconds)

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15494]
- [ ] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

What problem is your feature request going to solve?
Hello, many users may accidentally go to non-existent pages and not understand what happened. Not all users understand the 404 error, and not a small percentage of visitors close the site seeing such an error, the decision to make an automatic transfer to the home page by a plugin, such as rank math, will not be correct for search engines, since they will define this transition as an existing link. And if there is a transition to 404, the system will see that there is no such link, and will not index it, in the case of an incorrect sitemap or deletion of the page/product/post after indexing

**Comment by Aviad-Herman** [comment]
Hi @promocot, interesting idea!
We will take note of it.

Meanwhile you can achieve this in other ways, for example add an HTML widget with the following code:

```
<script>
    if ( ! window.top.elementor ) {
      setTimeout( () => {
            window.location.replace( 'http://stackoverflow.com' );
         }, 5000 );
    }
</script> 
```
