### ISSUE TITLE
Custom Breakpoints | WARNING! Major concern!

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#15502]
So, I have been working with Elementor BETA where Custom Breakpoints are enabled, and I found out that when I go to Responsive Visibility only 3 “Main Categories” appear:

![image](https://user-images.githubusercontent.com/68023943/123553787-a2e36100-d753-11eb-8786-f30558762019.png)

Please, enable this feature to be set to each of the enabled responsive breakpoints instead to the main category. I think this is a MUST if Elementor releases Custom Breakpoints.

**Comment by black-eye** [comment]
+1

**Comment by maurocarreraok** [comment]
@shilo-ey

**Comment by shilo-ey** [comment]
Thanks, this feature is still under development and will be dealt with soon.

Thanks
