### ISSUE TITLE
[BUG] Page Layout Breaks Down After Few Hours With Elementor Pro

### ISSUE THREAD

**Issue by chiranshuofficial** [elementor/elementor#15504]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.
- [ ] No Solution Found From Support, Even They Stopped Replying.

## Description

Page Layout Breaks after few hours because CSS stops working, I checked with CDN, Cache plugins everything is correct. I found this issue mentioned below. (Found in Chrome Console) Server Engine NGINX

Refused to apply style from 'https://www.technoven.com/wp-content/uploads/elementor/css/post-25507.css?ver=1624650023' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I have to click on Regenerate CSS again & again when layout breaks.

## Isolating the problem

- [ ] This bug happens with only the Elementor plugin active (and Elementor Pro).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Aviad-Herman** [comment]
This happens only on one specific page or on all pages?

**Comment by chiranshuofficial** [comment]
Whole pages made by Elementor

**Comment by Aviad-Herman** [comment]
Hey @chiranshuofficial I couldn't find any other documentations to this issue. So it's probably not a general bug but something to do with external plugins, Themes, server caching or configuration.

I would love to help but unfortunately only Elementor Support can get access to your site and try to solve the problem.

 https://elementor.com/contact/
