### ISSUE TITLE
Submissions disappearing 

### ISSUE THREAD

**Issue by lautmarketing** [elementor/elementor#15514]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.
[system-info-nanajuanamarina.com-29-06-2021.txt](https://github.com/elementor/elementor/files/6735630/system-info-nanajuanamarina.com-29-06-2021.txt)

## Environment

<details>
<summary><img width="1440" alt="Screen Shot 2021-06-29 at 12 15 43" src="https://user-images.githubusercontent.com/86682912/123849696-58d6b880-d8d6-11eb-8872-2e6bae37f5f8.png"></summary>
```
<img width="1440" alt="Screen Shot 2021-06-29 at 12 16 00" src="https://user-images.githubusercontent.com/86682912/123849794-73109680-d8d6-11eb-8210-6c3ab955694a.png">

<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by SteveKinzey** [comment]
It could be a conflict with gravity forms. Try using elementor forms.

**Comment by lautmarketing** [comment]
I'm already using Elementor forms. Have also deleted the Gravity Forms plugin, and the error persists.

**Comment by helloarpitgshah** [comment]
Hey @lautmarketing 

Please check with action after submit within your forms. It may be having some third party action that stuck with this or given error.

Thanks,
Arpit G Shah

**Comment by Aviad-Herman** [comment]
Did the submissions appear in the past and one day just disappeared or were they never saved in the first place?
Do new submissions appear in this screen?
Did you make any changes prior to the disappearance?

Please provide any info that might help us figure out this bug.

**Comment by lautmarketing** [comment]
Yes, they did when I first installed Elementor Dev (day 1). 
I then removed the gravity form that was installed inside the popup and started testing the submissions via Elementor Forms. Have removed all plugins on the page (RankMath, Sitekit) to ensure it's only running Elementor but still no luck. 
I do receive a confirmation message on the form that it was submitted correctly but cannot find it under submissions. 
Initially, I was using Gravity Forms on the Elementor Popup but switched to Elementor Forms because of incompatibility with Gravity Forms, reCAPTCHA, and Elementor Popups.

**Comment by 79ho3ein** [comment]
I tested it. There is no problem sending, receiving and processing forms. Everything is working properly

**Comment by Aviad-Herman** [comment]
So now if you create a new page, and a new form widget (from the panel, not a template) you still get no new saved responses?

Any chance you can you send me a video please? (Loom is a great tool for that).

**Comment by lautmarketing** [comment]
Yes, unfortunately, the whole tab won't show. The video explains it best. I've also submitted a ticket with Elementor, and they are currently investigating. 
https://user-images.githubusercontent.com/86682912/124187276-d4716a80-da7a-11eb-8caa-24fd193bb7d0.mov

**Comment by Aviad-Herman** [comment]
Great video, I understand now.
I did not notice you had 2 pictures in the original description.

Please try these steps and see if it solves your issue:

1. Switch to Hello theme
2. Deactivate all other plugins  (including elementor dev edition)
3. Rollback to none-dev versions of Elementor (3.2.5 and pro 3.3.0)
4. Turn off all Elementor experiments other than form submissions

Does the issue still happen?

**Comment by lautmarketing** [comment]
Hi Aviad, thanks for your help thus far. This is what I've tried thus far:

1. Have switched to Hello theme
2. All other plugins have been deactivated
3. Cannot rollback to an earlier version of Elementor, I receive a cURL error
4. All Elementor experiments other than submissions have been turned off

The problem persists. Since it's a new site, I was wondering if doing a clean WordPress installation, might eliminate the error altogether. I have other Elementor-powered sites, and this is the only one giving me this error. What are your thoughts?

**Comment by SteveKinzey** [comment]
Elementor or WordPress does not cause the cURL error. It is a server error. You need to contact your host provider and ask for their assistance.

You will want to have them help you with: ensuring that you are running the most current/stable version of PHP, possibly increasing your Server Memory Limits settings; and, making sure if there is not some limitation with wp-cron or if loopback is disabled. 

It is very likely that with a boost in Memory Limits, your entire site will begin working again. So make sure you have your host help you increase that value.

**Comment by Aviad-Herman** [comment]
A clean install should fix this.
I'm asking a developer what happens to form submissions if you do a clean install.
I'll get back to you soon.

In any case, if you want to try it now, I would suggest  to export your submissions just in case.

**Comment by lautmarketing** [comment]
Elementor was able to fix the issue. It seems an invalid submissions entry (with "main_meta_id" of 0) in the "wp_e_submissions" database table was causing the issue. I can now see all the submissions. 

Thank you guys
