### ISSUE TITLE
Responsive options for heading text size

### ISSUE THREAD

**Issue by sam-moreton** [elementor/elementor#15516]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Currently, setting text size "small, medium, large" etc. In header widgets (and possibly others) allows you to adjust the size of text independently of header tags (H1, H2 H3...) Which is the right approach to optimise for SEO. However, it would be nice to be able to set different text sizes for different breakpoints in order to scale down large text to fit mobile.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by SteveKinzey** [comment]
I am not completely sure I understand your problem, but what about viewing the section using the tablet and mobile views and editing the text accordingly?

**Comment by Aviad-Herman** [comment]
You can do so in Style --> Typography
![image](https://user-images.githubusercontent.com/73067562/123988598-d121a480-d9d0-11eb-82f7-344cacc88fae.png)
