### ISSUE TITLE
Elementor background fixed not working properly

### ISSUE THREAD

**Issue by showbizas0450** [elementor/elementor#15526]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description
Setting up any image as fixed in background will not display it properly when previewing on site on both Google Chrome and Microsoft edge. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Local server hosting site for overhauling
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,

Unfortunately we can't reproduce your issue.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
