### ISSUE TITLE
Ability to customize the notification bar in elementor (More advanced than alert widget)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15528]
I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve?**

hello
It would be great if you add a feature so that we can customize the notification bar. Currently, the alert widget does this, but it does not have much customization and is very limited.
![Screenshot (63)](https://user-images.githubusercontent.com/77163248/124104632-b8b89500-da77-11eb-8293-ab75f7d6c74d.png)

**If you approve this request, please also consider the following suggestions :**
This request can be accompanied by a new widget, or can be integrated with the alert widget.

1- It would be great if we could design this announcement as we wish and use the necessary widgets in it. The use of widgets such as buttons, titles is very common in it.

2- Ability to apply animation when closing it. Just like the pop-up in elementor.

3- Ability to customize the close button. This item is also currently available in the elementor pop-up. But in the alert widget, it is not possible to customize the close button.

I hope I have conveyed my point well. This feature is one of the most important features that elementor currently lacks.

Finally, if this feature is added to elementor, we can design such a notification bar with elementor. (Very advanced compared to the alert widget)
![Screenshot (64)](https://user-images.githubusercontent.com/77163248/124109530-7ba2d180-da7c-11eb-8743-00c4d9eca897.png)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

If do you mean by notification to Hello Bar (https://elementor.com/help/popups-hello-bar/) then this is a template, and you can create and customize it as you wish. 


Thanks.
