### ISSUE TITLE
Preload images in elementor ( Increase site speed )

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15539]
I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve?**
Adding this feature dramatically increases the site loading speed.

**Describe the solution you'd like**
It would be great if you could add a feature to elementor so that we can preload all the images on the website. 
**I preloaded 5 site images using the Opposite code :** <link rel="preload" as="image" href=" image link ">
This increased the loading speed by 1.5 seconds. And the loading speed of the site increased tremendously.
Of course, I could not preload the pictures of the products and so on. Because I had to copy a lot of the above preload code and it was very time consuming. For this reason, I did not pre-load product images.
**Finally, I suggest please check the ability to preload images. It is extremely effective.**

As elementor is adding more and more settings for optimization day by day, I suggest you please add a section in elemenor settings and put all the optimization settings in it. In this case, we can easily access the optimization settings.

thank you

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #15205 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
