### ISSUE TITLE
Elementor Form Steps Not Working Properly

### ISSUE THREAD

**Issue by webbosg** [elementor/elementor#15548]
Elementor Form Steps not working at all
![Screenshot 2021-07-03 202851](https://user-images.githubusercontent.com/86912891/124384775-73a99280-dd05-11eb-8119-34ea665e1c65.jpg)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
