### ISSUE TITLE
Notice: Undefined index: pro_widgets in %location%/wp-content/plugins/elementor\includes\api.php on line 160

### ISSUE THREAD

**Issue by codersaiful** [elementor/elementor#15542]
https://github.com/elementor/elementor/blob/8d5e8d68057880d2b4c6899dea07dca3e7adb8d1/includes/api.php#L160

should be: 
`php
return isset( $data['pro_widgets'] ) ? $data['pro_widgets'] : false;
`

**Comment by codersaiful** [comment]
![Elementor Library Issue](https://user-images.githubusercontent.com/6463919/124343971-8468e400-dbf1-11eb-80f0-572ebc99f53b.png)

I got that issue, when the library site was site from here.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.0

Feel free to update

Thanks!
