### ISSUE TITLE
ELEMENTOR NOT UPDATING AUTOMATIC

### ISSUE THREAD

**Issue by Loopdigitalmarketing** [elementor/elementor#15562]
Dear support i have installed the ELEMENTOR PRO in 14 Websites so far and i notice the plugin EASYUPDATES Manager is not updating the ELEMENTOR PRO Automatic, all other plugins are updating automatic.

That's very time-consuming since i have to go in 14 websites and do a manual update.

I Contact EASYUPDATES Manager plugin authors and they told me this issue occurs from ELEMENTOR PRO site, something is preventing it from auto updating...

NEED YOUR HELP!

**Comment by d19dotca** [comment]
This is not an Elementor Support forum, just FYI, but this has been the behaviour for a very long time. For what it's worth, when you're managing more than a couple of websites you should be using something like MainWP (free, or many of its alternatives) to manage updates across all of the websites you manage. It saves so much time and you can have it set to auto-update "trusted" apps like Elementor Pro every 24 hours.

**Comment by Loopdigitalmarketing** [comment]
I Did that but keeps skiping elementor pro updates.
  
  
   
    On 07/05/2021 6:24 PM Dustin Dauncey ***@***.***> wrote:
   
   
    
   
   
    
   
   
   This is not an Elementor Support forum, just FYI, but this has been the behaviour for a very long time. For what it's worth, when you're managing more than a couple of websites you should be using something like MainWP (free, or many of its alternatives) to manage updates across all of the websites you manage. It saves so much time and you can have it set to auto-update "trusted" apps like Elementor Pro every 24 hours.

**Comment by Aviad-Herman** [comment]
Hey,
A couple of followup questions:

1. Is Elementor Core updating correctly?
2. Do you have any other Pro plugins that ARE updating correctly?

I have a feeling that this plugin update system is based on WordPress' repository and Pro / paid plugins (Elementor or other) are NOT allowed to be stored on WP repository.

If this is the case, there is no way we can solve this on our end.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
