### ISSUE TITLE
make it leaner & integrate caching+optimizations with release.

### ISSUE THREAD

**Issue by lootnath** [elementor/elementor#15564]
make it leaner & integrate caching+optimizations with release.

**Comment by d19dotca** [comment]
There are already various Experiments that you can enable which make it far leaner than it is without the experiments enabled. Speed is a focus for them as they realize they're losing customers to alternatives that produce much cleaner code. For caching, that should be done with a third-party tool for various reasons.

**Comment by d19dotca** [comment]
This is also a duplicate of several other posts in here as well where the focus of discussion is improving performance and generating better code.

**Comment by DorShahar** [comment]
Thanks for the feedback,
@d19dotca explained it perfectly. 
Please use our experiments to improve performance. 

Thanks
