### ISSUE TITLE
Please develop the tabs widget.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15568]
I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, the tabs widget is very simple and does not have proper customization.

It would be great if you could add a feature so that we can insert icons as tabs : https://prnt.sc/18uhtba
The tabs widget is one of the most widely used elementor widgets. But unfortunately, the situation is not good at the moment.
The crocoblock jet tabs plugin is a perfect example of this widget.
Great if elementor upgrades its tabs widget. As elementor plans to upgrade its WooCommerce widgets in 2021, the tabs widget can also be upgraded. Because it is one of the most widely used widgets in store sites.
Of course, these include the Accordion widget. But the Tabs widget takes precedence.

thank you

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2587 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Nested Tabs** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
