### ISSUE TITLE
Width position in mobile

### ISSUE THREAD

**Issue by mstudioIL** [elementor/elementor#15560]
I setting the width position to auto and it still look likes the full width,
It break the layout, and it was working before.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.

**Comment by mstudioIL** [comment]
It is a bug, how width position set to auto (inline) look likes full width?
