### ISSUE TITLE
Popups don´t found in Safari

### ISSUE THREAD

**Issue by JorgeLu10** [elementor/elementor#15575]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have created popups that help to customize the product, these are created with Elementor and are included in the products with a Pluging that allows you to customize the products. This pluging is called UniCpo, it allows you to create buttons and embed the popup class to open it. The popups work in all search engines except safari, we have tested with an iPhone 10 but not with a Mac (We do not have that possibility). The safari popups are opened but immediately close automatically. We leave you a couple of URLs where you can find the buttons, they are all blue with the word "ayuda"
https://corticolors.com/mecanismo-para-estores-con-cadena-paqueto-plegable/
https://corticolors.com/mecanismo-para-estores-ocultos-compactos-paqueto-plegable/

## Steps to reproduce
1º Open safari 
2º Open a product from our store with the buttons we mentioned
3ºClick on one of the help buttons "Ayuda"

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [] I can reproduce this bug consistently using the steps above.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.27
	PHP Version: 7.3.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://corticolors.com
	Home URL: https://corticolors.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 512M
	Permalink Structure: /blog/%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.3.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.9
		Author: Automattic

	Customer Reviews for WooCommerce
		Version: 4.15
		Author: CusRev

	Custom Product Tabs for WooCommerce
		Version: 1.7.7
		Author: YIKES, Inc.

	Elementor
		Version: 3.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.1
		Author: Elementor.com

	Estados de pedido con notificación
		Version: 2.3.0
		Author: Enrique J. Ros

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.11.0
		Author: FiboSearch Team

	Funciones
		Version: 1.0
		Author: Fernando Tellado

	GDPR Cookie Consent
		Version: 2.0.3
		Author: WebToffee

	Loco Translate
		Version: 2.5.2
		Author: Tim Whitlock

	Mailchimp for WooCommerce
		Version: 2.5.1
		Author: Mailchimp

	Media Library Folders for WordPress
		Version: 6.1.5
		Author: Max Foundry

	Premmerce Permalink Manager for WooCommerce
		Version: 2.3.1
		Author: premmerce

	Product Feed PRO for WooCommerce
		Version: 10.1.9
		Author: AdTribes.io

	Product Options and Price Calculation Formulas for WooCommerce – Uni CPO (Premium)
		Version: 4.9.10
		Author: MooMoo Agency

	Schema
		Version: 1.7.9.2
		Author: Hesham

	WooCommerce
		Version: 5.3.0
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.12
		Author: CartFlows Inc

	WooCommerce Google Analytics Integration
		Version: 1.5.1
		Author: WooCommerce

	WooCommerce Pay for Payment
		Version: 2.0.18
		Author: Karolína Vyskočilová

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.9.0
		Author: Ewout Fernhout

	WooCommerce Product CSV Import Suite
		Version: 1.10.21
		Author: WooCommerce

	WooCommerce Redsys Gateway Light
		Version: 3.0.4
		Author: José Conti

	WooCommerce RRP
		Version: 1.7.5
		Author: Bradley Davis

	WP Mail SMTP
		Version: 2.7.0
		Author: WPForms

	WP Rocket
		Version: 3.9.0.5
		Author: WP Media

	YITH WooCommerce Delivery Date Premium
		Version: 2.1.29
		Author: YITH

	Yoast SEO
		Version: 16.1.1
		Author: Team Yoast

== Must-Use Plugins ==
	p3-profiler.php
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		facebook-page : 1
		form : 1
		heading : 6
		icon-list : 4
		social-icons : 1
		spacer : 3
		star-rating : 1
		text-editor : 3
		theme-site-logo : 1
	header : 5
		countdown : 1
		icon : 2
		icon-box : 7
		icon-list : 1
		image : 1
		nav-menu : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 1
		wp-widget-dgwt_wcas_ajax_search : 2
	page : 5
		icon : 1
	popup : 34
		button : 1
		divider : 28
		image : 56
		text-editor : 126
	wp-page : 21
		accordion : 12
		button : 1
		form : 19
		heading : 98
		icon-box : 4
		icon-list : 19
		image : 18
		image-box : 1
		lottie : 1
		spacer : 38
		text-editor : 26
		theme-page-title : 19
		woocommerce-products : 20
	search-results : 1
		sidebar : 1
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-breadcrumb : 1
	product-archive : 11
		heading : 47
		icon : 14
		icon-box : 7
		image : 29
		reviews : 7
		sidebar : 9
		spacer : 22
		text-editor : 3
		theme-archive-title : 9
		toggle : 7
		wc-archive-products : 9
		woocommerce-archive-description : 9
		woocommerce-breadcrumb : 9
		woocommerce-products : 2
	error-404 : 3
		heading : 4
		woocommerce-products : 1
		wp-widget-woocommerce_product_categories : 1

				
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @JorgeLu10 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly:
![image](https://user-images.githubusercontent.com/19154938/124695213-71a12880-deeb-11eb-944d-6aff0b5a71ae.png)


Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

Since you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by JorgeLu10** [comment]
Hi,
None of the actions that you comment solves our problem, seeing that you
have tried with Mac, we think that the problem is in the iphone that use
safari, we have tried with an Iphone 10, in safari it does not work but
with chrome it does.
Thanks you
