### ISSUE TITLE
Upgraded PRO to 3.3.1  from 3.1.1 

### ISSUE THREAD

**Issue by najeeboffice** [elementor/elementor#15577]
![Untitled-1](https://user-images.githubusercontent.com/25299124/124650625-f881e100-deaa-11eb-91b5-394698c546c0.jpg)
On Home page no errors but n inner page this error generates and while scrolling it keeps coming in.

**UPDATES:**
When i turn off Sticky Top Option no errors appear.

So i kept Sticky On to top on Frontpage and About page. Rest of the pages i removed Sticky on top effect. If you want to see the error on console please refer https://redtag-stores.com/ar/about/

**Comment by najeeboffice** [comment]
When i turn off Sticky Top Option no errors appear.

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
