### ISSUE TITLE
Open a page with only footer, exception happens

### ISSUE THREAD

**Issue by arkuka** [elementor/elementor#15578]
This problem happens on a page with only footer, it works well on the first day, but when I try to open it to edit it on the second day, problem happens.

Error Log:

Fatal error: Uncaught TypeError: Elementor\Elements_Manager::create_element_instance(): Argument #1 ($element_data) must be of type array, string given, called in D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\post.php on line 177 and defined in D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\managers\elements.php:68 Stack trace: #0 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\post.php(177): Elementor\Elements_Manager->create_element_instance('Array') #1 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php(616): Elementor\Core\Files\CSS\Post->render_css() #2 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\base.php(166): Elementor\Core\Files\CSS\Base->parse_content() #3 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php(130): Elementor\Core\Files\Base->update_file() #4 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php(206): Elementor\Core\Files\CSS\Base->update() #5 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\post.php(206): Elementor\Core\Files\CSS\Base->enqueue() #6 D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\frontend.php(671): Elementor\Core\Files\CSS\Post->enqueue() #7 D:\xampp\htdocs\wordpress\wp-content\plugins\header-footer-elementor\inc\class-header-footer-elementor.php(384): Elementor\Frontend->enqueue_styles() #8 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(292): Header_Footer_Elementor->enqueue_scripts('') #9 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #10 D:\xampp\htdocs\wordpress\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #11 D:\xampp\htdocs\wordpress\wp-includes\script-loader.php(2027): do_action('wp_enqueue_scri...') #12 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(292): wp_enqueue_scripts('') #13 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #14 D:\xampp\htdocs\wordpress\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #15 D:\xampp\htdocs\wordpress\wp-includes\general-template.php(3009): do_action('wp_head') #16 D:\xampp\htdocs\wordpress\wp-content\themes\astra\header.php(26): wp_head() #17 D:\xampp\htdocs\wordpress\wp-includes\template.php(730): require_once('D:\\xampp\\htdocs...') #18 D:\xampp\htdocs\wordpress\wp-includes\template.php(676): load_template('D:\\xampp\\htdocs...', true, Array) #19 D:\xampp\htdocs\wordpress\wp-includes\general-template.php(48): locate_template(Array, true, true, Array) #20 D:\xampp\htdocs\wordpress\wp-content\themes\astra\page.php(20): get_header() #21 D:\xampp\htdocs\wordpress\wp-includes\template-loader.php(106): include('D:\\xampp\\htdocs...') #22 D:\xampp\htdocs\wordpress\wp-blog-header.php(19): require_once('D:\\xampp\\htdocs...') #23 D:\xampp\htdocs\wordpress\index.php(17): require('D:\\xampp\\htdocs...') #24 {main} thrown in D:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\managers\elements.php on line 68

--------------------------------------------------------------------------

I tried to add some debug code as below:

protected function render_css() {
		$data = $this->get_data();
		
		if ( ! empty( $data ) ) {
			
			foreach ( $data as $element_data ) {

				echo "in render_css(); type of $element_data is:".gettype($element_data)."<br>";
				echo "in render_css(); type of $element_data is:[".$element_data."]<br>";

				$element = Plugin::$instance->elements_manager->create_element_instance( $element_data );

				if ( ! $element ) {
					continue;
				}

				$this->render_styles( $element );
			}
		}
	}

The output of the above debug code is:
in render_css(); type of Array is:string
in render_css(); type of Array is:[Array]

---------------------------------------------------------

create_element_instance asks for an array type parameter, while render_css provides a string type parameter as 'Array', it looks like a bug.

Thanks!

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
