### ISSUE TITLE
Issue when try to extend any widget

### ISSUE THREAD

**Issue by saulobraine** [elementor/elementor#15585]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello, when I try to extend some widgets, like Portfolio, Forms, or Skin like Base Skin have some issues with JS. Example, with Portfolio the filter bar not working, only work if I've use the same name as original widget and is not always what I want to do, doing this the original widget is disappear.
I've investigated the case of Portfolio widget and with my knowledge I would try to make a another class using the same code. But the package has just the babel convert files, nothing on assets paths.

Can I extend this widgets with original JS in individidual?

## Steps to reproduce

Extend a Portfolio widget with a different name, set the filter bar, and try to filter.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by webdevs-pro** [comment]
+1

**Comment by rami-elementor** [comment]
> Can I extend this widgets with original JS in individidual?

The best practice for external addon developers is to create new widgets, not to extend existing widgets.
