### ISSUE TITLE
How to add an "elementor-add-section-area-button" or "elementor-add-new-section"? 

### ISSUE THREAD

**Issue by designomo** [elementor/elementor#15581]
We would like to know how to add a button in the lower section similar to the extension plugins from Envato, Templatey or ElementsKit. We are currently working on a plugin with templates for Elementor and would like to see the button on the lower end of the page when editing. 
https://www.loom.com/share/38119d32d4e04e999d61a584fb190f72

**Comment by designomo** [comment]
@Aviad-Herman Hey Aviad, What does type/developer-api mean? do we need a "special" developer api for this function?

**Comment by Aviad-Herman** [comment]
Hey,
It's just a tag we use to gather developer requests so we know what documentation to work on next.

**Comment by rami-elementor** [comment]
Hi @designomo ,

We don't have an official method to add additional buttons to this area.

The Elementor addons you mentioned above probably inject code to this area. We can't stop developers from doing this, but we don't recommend it.

Elementor addon developers should extend only the components that are documented in the [Elementor Developers Docs](https://developers.elementor.com/docs/). Those components have extendable code and well documented methods for developers.
