### ISSUE TITLE
I can use the license for Elementor Pro through wp-config

### ISSUE THREAD

**Issue by jlcaicedo** [elementor/elementor#15584]
The most WordPress plugins allow us to use their licenses through the wp-config file through:

`define('NAME_KEY', 'KEY');`

**Comment by rami-elementor** [comment]
@jlcaicedo 

We don't support this feature. You can't define an Elementor license from the wp-config file.

But we do offer a CLI command that activates the license: https://developers.elementor.com/docs/cli/license-activate/
