### ISSUE TITLE
PHP 8 + Pods Framework + Ele Custom Skin | PHP Warning: Trying to access array offset on value of type bool in...

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#15597]
Hi I use Elementor Pro with Pods Framework + PHP 8. 

– PHP 8
– Elementor 3.2.5
– Elementor Pro 3.3.1
– Pods – Custom Content Types and Fields 2.7.28

I create a custom post type with a custom post field (text).
I create a Loop Template (For Custom Skin) by your plugin:
Add Heading Text with Dynamic Tags is a “Pods” Field (Text Field).

I got the Warning:

PHP Warning: Trying to access array offset on value of type bool in /home/my-domain.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-text.php on line 20

Please Check. Thanks.

**Comment by Aviad-Herman** [comment]
Hi, thanks for the report.
Pods is an external plugin that registers values into our dynamic field capabilities.
If adding a dynamic pods heading never works, even when not using ele skins - contact pods support.
If the dynamic heading works everywhere else, just not with ele skins - contact ele custom skins support.

Thanks for understanding.
