### ISSUE TITLE
Suggestion to add "mobile menu bottom" feature to elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15593]
[ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This feature is widely used on websites today. And its place in elementor is very empty.

![tab_bar_design](https://user-images.githubusercontent.com/77163248/124997066-463f4a80-e05f-11eb-8579-db311ada82b6.jpg)

**Describe the solution you'd like**
Great if elementor adds this feature. So we can design very nice menus for websites (of course only for mobile).

Of course, we can do it right now, but it will not be interesting. Both in terms of design and performance. I think if elementor adds this feature, it can work on it more professionally and develop it better.
There are many ideas about this feature. I hope this proposal is approved by the developers.
But in any case, this feature is becoming more widely used day by day and sooner or later, elementor will need it.

thank you

**Comment by mehdimoradi1500** [comment]
+1 i also like this option

**Comment by Aviad-Herman** [comment]
You can do it by creating a popup in Elementor Pro.
Here are a few hints. I'm Sure you can figure it out.

![image](https://user-images.githubusercontent.com/73067562/125358107-2c5c7b00-e371-11eb-8937-978699cc72e9.png)
![image](https://user-images.githubusercontent.com/73067562/125358219-4f872a80-e371-11eb-932a-9f655a584883.png)

**Comment by mehdimoradi1500** [comment]
Thank you so much for your help 🌷

**Comment by 79ho3ein** [comment]
thank you
