### ISSUE TITLE
🔗 🔃  🚀 Feature Request: Vertical shape dividers (Merged with #2729)

### ISSUE THREAD

**Issue by Ryan147** [elementor/elementor#1559]
Elementor has horizontal shape dividers for sections. How about vertical shape dividers for columns?

**Comment by ramiy** [comment]
Can be a nice feature. How will that look on mobile devices?

**Comment by pastemedia** [comment]
It'd be nice.
@ramiy  even the current horizontal ones are not suitable for mobile devices most of the time

**Comment by arielk** [comment]
I'm sorry, but I can not find a way to do it, so I'm closing the issue for now.

Thanks for the feedback anyway!

**Comment by tgp1994** [comment]
I'd like to chime in and say that I'd also like to see this feature in elementor. See [this StackOverflow](https://stackoverflow.com/questions/571900/is-there-a-vr-vertical-rule-in-html) question & accepted answer. The solution is to just customize the left or right borders in an html element. This should be easy to implement, no?

**Comment by arielk** [comment]
Ref: #2729

**Comment by tgp1994** [comment]
Which issue should we follow now? I could paste my workaround in the newer issue if that might help at all.

**Comment by kellyug** [comment]
Hello everyone, it might be too late but this might help someone: You can only create a section drug and drop in a custom html widget, don't give it a name and the 
Paste this code in the code section, then you can customize according to the size and color you want. this is what i had to do,

`
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.vl {
  border-left: 1px solid black;
  height:50px;
}
</style>
</head>
<body>

<div class="vl"></div>

</body>
</html> `
