### ISSUE TITLE
Show dynamic Tag Data of Taxonomy in Block Style and add filtering options

### ISSUE THREAD

**Issue by CordialGit** [elementor/elementor#15594]
I wanted to achieve 2 things:
1.) Assign Multiple Categories to a Post, but display the taxonomy output as separate individual items.

2.) Assign Multiple Categories to a Post, but be able to filter these categories and place them in different areas of a Card Design.

MY USE CASE
1.) For Request Number 1(one), I used Dynamic Tag to call in my used Taxonomies on a Page Design. It showed the Taxonomies as a Comma-Separated-List. It showed it like this-- https://prntscr.com/19ln7kb

But I wanted it like this-- https://prntscr.com/19lnm4p

The summary is that--from my Images, Elementor shows Taxonomies attached to a Post only as a Comma-Separated-List. 
But it would be nice to also be able to show these multiple Taxonomies attached to a Post as Block level elements.

2.) There are times when multiple Taxonomies are attached to a Post. But you'd like to show only one from the list of the multiple Taxonomies attached to a Post. As you can see from here--https://prntscr.com/19lpl2v

The Badge is a Category. Holidays and Dinner which are after the Recipe Image are also Categories. But intelligent programming made it possible to filter the specific Category that should appear on the Badge(Top Right corner) and which one should appear after the Image .

There's no filtering option like this in Elementor, and I believe it's a useful feature that Elementor provide.

Full Site Editing is coming. It is to Elementor's benefit to provide useful Features of control that will still make people stick with Elementor.

Would Elementor implement these Features soon?

Regards [x] -->

**Comment by Aviad-Herman** [comment]
Hi,
We don't have anything like that planned currently.
For 1: You can use custom CSS to target each <a> and style them to look like separate tags
For 2: for now you'd have to find a workaround, perhaps ACF custom fields

**Comment by CordialGit** [comment]
You see, these things I've asked for, are things that have been achieved somewhere as you can see from my Images.

While Elementor doesn't have anything like that planned for now, may be because Elementor hasn't thought of it. And truthfully, Elementor alone cannot think of every possible thing that Users can need.

Thence, I've needed these two things, and Elementor screwed me up by not having these simple common features. 

However, I give Elementor a thousand hugs because Elementor made our lives beautiful ,easy and sweet. And I encourage Elementor not to back down from its innovative and creative proactiveness.

Moving on then, I plead with Elementor to please add these features in its upcoming updates.

Needing to hear from you soon.

Regards [x] -->

**Comment by Aviad-Herman** [comment]
Elementor has to balance user requests, simplicity and performance. There is no one size fits all.
This is why we added the ability to add custom code and dynamic tags - so advanced users can achieve pretty much anything.

Here is an example of terms list styled as blocks using custom CSS (The example is from a yet unreleased page in elementor.com).
![image](https://user-images.githubusercontent.com/73067562/125430664-a31f1944-cadf-4f40-9374-39f92e215ca4.png)


Regarding ACF colors. I don't know, seems to be working fine for me:

![image](https://user-images.githubusercontent.com/73067562/125432500-67195c41-0327-4788-9349-ab91e2142c70.png)

**Comment by CordialGit** [comment]
Thanks very much for this answer. Your answer proved to me that the answer to my problem may not be too far.

So I am going straight to tell you what I want exactly, and expect that you could provide me the needed codes, or tell me what to do, how to set it up, and where to look.

**MY CHALLENGE**
I need to add Taxonomy Terms to the Top part of my Custom Card Design. These Terms would have a background color like a Badge.

The Terms and their colors are as below:
Breakfast: #ffbf00
Brunch: #ff8c00
Lunch:  #37c400
Dinner: #009ace

And the output when the Card has Single Terms is this-- https://prntscr.com/13nnjz2

Then, when it is multiple Terms, it should display as a Block Style like this-- https://prntscr.com/19lnm4p

How should I go about it? Using Elementor and Pods to achieve this?

Regards [x] -->

**Comment by Aviad-Herman** [comment]
I think you will get more answers in the community FB group:
https://www.facebook.com/groups/916625091796611

**Comment by CordialGit** [comment]
I've been posting this for more than 3 weeks now, and I've not found
answers.

**Comment by CordialGit** [comment]
The Facebook Group doesn't seem to have the capacity for what I'm asking.  I've posted this request for more than 3 weeks, but there doesn't seem to be any reasonable answer.

If you do have the answer, I'd be very glad if you can help me with it.

Regards[x] -->
