### ISSUE TITLE
Elementor Image Carousel Image too Large 

### ISSUE THREAD

**Issue by flancast90** [elementor/elementor#15596]
Hello, 
Recently I have been experiencing issues with the Image Carousel on a site I help with (arcanimalrescue.com). As shown in both the attached images, the pics in the carousel are stretched, rendering most of them not visible. As of a few days ago, the images were perfect, and fit the container without any overflow or stretch. Since then, the settings have not been touched. Is there a recent update to blame?
Image 1 (Too stretched with one image):
![IMG 1](https://i.imgur.com/uHnaAsq.png)

Image 2 (Too stretched multiple. See how nav arrows are covered, and images overflow container):
![IMG 2](https://i.imgur.com/pY2fnuN.png)

Can anyone either give a quick-fix with the settings (maybe another volunteer updated the settings?), or confirm that this is a bug. If it is the latter, is there a time-frame for when a patch will be added?

**Comment by Aviad-Herman** [comment]
Hi,
Sorry for the inconvenience but this is not a valid bug report.
Better contact support or the Community facebook group.

I would suggest disabling all other plugins, deactivating all experiments and switching to Hello theme and create a new page with a new image carousel widget. Only if the problem persists there is reason to assume a bug. In which case we will need access to your site to replicate the issue, which can only be dome through support.
