### ISSUE TITLE
Why elementor call all the widget or at least many of the custom widget as soon as you click edit with elementor?

### ISSUE THREAD

**Issue by hkmsadek** [elementor/elementor#15595]
When I click edit with elementor, I see elementor is calling many widgets and it;s external apis ? Why does this happen since you are not even using that widget?

**Comment by Aviad-Herman** [comment]
In the front end, we are currently working on an experiment that only loads what you need.

In the editor, we load everything so it will be available without delay in case you want to drag it into the screen.
