### ISSUE TITLE
✅ 🚀 Ajax search in Elementor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15613]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will be great if you develop the search widget in elementor.

**Describe the solution you'd like**
As elementor plans to expand its WooCommerce widgets in 2021, Ajax Search will be one of the most important features in this area.
Now the elementor search widget is very simple. For example, it is not possible to search Ajax. Or, for example, we can not dedicate the search only to posts or products.
Currently, the jet search plugin is the best template for this feature. **I hope elementor has a special program for developing search widget.**

thank you

**Comment by 79ho3ein** [comment]
Hello elementor developers!
I have a question and I am very curious about it ... 
I wanted to ask if elementor works on Ajax search? Or do you still have no plans for it.

thank you in advance

**Comment by nicholaszein** [comment]
Hey @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.23.0! 🥳 

To learn more check this article: https://elementor.com/help/search-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
