### ISSUE TITLE
v3.3.0 - Site Setting - Custom CSS bug

### ISSUE THREAD

**Issue by s5t5n** [elementor/elementor#15628]
Go this code in "Site Setting - Custom CSS" overriding default animation distance. After update it's not working and not overrides default animation css. After roll back it's working. How to override this in v.3.3.0 with css and do not touch plugin.js file?

```
@keyframes fadeInLeft {
	from {
		opacity: 0;
		transform: translate3d(-10%, 0, 0)
	}
	to {
		opacity: 1;
		transform: none
	}
}
```

**Comment by shilo-ey** [comment]
Can you please share a live example? more detailed steps to reproduce?

Thanks

**Comment by Merlin1987** [comment]
Same here. After updating to the newest version of Elementor Pro, some css broke in WooCommerce, especially the css i fill in the Design -> Customizer -> Custom CSS Section.

I downgrade to Elementor Pro 3.2.2 (leave all other plugin untouched) and it works again. After i wanted to do some screenshots for you i update to 3.3.1 and it still works. It breaks when i update again to 3.3.2.

<img width="1311" alt="Bildschirmfoto 2021-07-15 um 22 10 21" src="https://user-images.githubusercontent.com/41824265/125851610-a8b3ab1b-47ee-4181-b2c9-540656d9fcd6.png">
<img width="1276" alt="Bildschirmfoto 2021-07-15 um 22 11 32" src="https://user-images.githubusercontent.com/41824265/125851618-2f5eaf10-2947-4567-acc8-9b64b1a1af49.png">

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
