### ISSUE TITLE
Ability to "post carousel" and Custom design of posts template (posts widget)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15627]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be great if you could add a feature to the posts widget so that we can display the posts as a Carousel.

**Describe the solution you'd like**
Currently, plugins like Elementor Custom Skin Pro add this feature to elementor, but if we have this in elementor, it is very useful.
This feature can be very important and necessary, as elementor updates indicate that it intends to eliminate the need for third-party plugins for its users.

**But another suggestion that is extremely important. And if elemenor adds it it would be great.**

elementor must add a custom mode to the posts widget, in addition to the classic mode, cards and full content. Using custom mode, we can design mailboxes dynamically, completely customized, and call through the mail widget. This feature is currently only available in jet engine and Elementor Custom Skin Pro plugins.
An example of a custom post design :
![Screenshot (74)](https://user-images.githubusercontent.com/77163248/125444192-d34bdc50-0fad-4c13-b45a-1f9cf3892067.png)

If elementor adds this feature, it will easily override the two plugins.

Thank you for your attention

**Comment by Aviad-Herman** [comment]
Hey I'm merging this with #4440

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Carousel widget released with Elementor Pro v3.11.0! 🥳 

With the new Loop Carousel widget, you can customize your post listings with custom templates (including WooCommerce Products)! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Carousel layout, design, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-carousel/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
