### ISSUE TITLE
Slides and Image Gallery widget no longer respecting columns after update 

### ISSUE THREAD

**Issue by GSJ-Projects** [elementor/elementor#15639]
After the last update, my image gallery no longer stays within a column. I'm unsure why, but I have not touched or added anything other than the update. Please see attached image. This is WITHOUT changing any margin/padding at all. 
![Screenshot 2021-07-13 at 11-20-55 Elementor Home](https://user-images.githubusercontent.com/35821246/125489370-d846b8ea-580b-4b59-aaa0-ae0ac58f76c2.png)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
After the last update, my image gallery no longer stays within a column. I'm unsure why, but I have not touched or added anything other than the update. Please see attached image. This is WITHOUT changing any margin/padding at all. 

## Steps to reproduce
Add an image gallery or slides anywhere and you will notice it no longer respects the grid it is placed in. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @GSJ-Projects 

Can you please share your system info? 
Go to Elementor > System info and paste the report here.

Make sure to update Elementor Pro to v3.3.2 and update if the issue resolved

**Comment by GSJ-Projects** [comment]
Thanks for the response @shilo-ey . I JUST updated to the latest and the issue is still not resolved. It seems that it just outputs the default 3 images in the slider irrespective of the grid or the "slides to show" number. 

Here is my system info: 

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.30
	PHP Version: 7.4.20
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://nfturself.com
	Home URL: https://nfturself.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

== Active Plugins ==
	Elementor
		Version: 3.3.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.2
		Author: Elementor.com

	Jetpack
		Version: 9.9
		Author: Automattic

	Loginizer
		Version: 1.6.7
		Author: Softaculous

	MonsterInsights - eCommerce Addon
		Version: 7.5.0
		Author: MonsterInsights Team

	MonsterInsights Pro
		Version: 7.17.0
		Author: MonsterInsights

	MyCryptoCheckout
		Version: 2.96
		Author: edward_plainview

	PowerPack Pro for Elementor
		Version: 2.2.7
		Author: Team IdeaBox - PowerPack Elements

	ShortPixel Image Optimizer
		Version: 4.22.2
		Author: ShortPixel

	WooCommerce
		Version: 5.5.0
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 1.25.16
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 5.2.3
		Author: WooCommerce

	WooCommerce Upload Files
		Version: 61.4
		Author: Lagudi Domenico


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	PowerPack Pro for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	PowerPack Pro for Elementor: Incompatible

== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 2
		image : 1
		social-icons : 1
		text-editor : 4
	header : 1
		image : 1
		nav-menu : 1
	product : 1
		share-buttons : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 2
	wp-page : 11
		accordion : 8
		button : 5
		call-to-action : 3
		countdown : 1
		divider : 6
		heading : 17
		image : 13
		pp-woo-cart : 1
		pp-woo-checkout : 1
		pp-woo-my-account : 1
		spacer : 1
		testimonial-carousel : 1
		text-editor : 9
		woocommerce-breadcrumb : 6
	product-archive : 1
		heading : 1
		image : 1
		pp-woo-products : 1


== Log ==
	
Log: showing 20 of 362021-04-26 20:06:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-06 16:27:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-11 17:39:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-05-30 18:13:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]
2021-06-16 16:19:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.4',
  'to' => '3.2.5',
)]
2021-06-16 16:19:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-16 16:19:08 [info] elementor-pro::elementor_pro_updater Started 
2021-06-16 16:19:08 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-16 16:19:08 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-16 16:19:08 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-16 16:19:08 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-16 16:19:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.0',
)]
2021-06-23 19:40:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-13 16:33:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:33:57 [info] elementor::elementor_updater Started 
2021-07-13 16:33:57 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-13 16:33:58 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-13 16:33:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:33:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 16:35:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.2',
)]

PHP: showing 1 of 1PHP: 2021-07-09 20:21:26 [notice X 5][/home/vs7581s3/nfturself.com/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by fellowshipdevs** [comment]
I had the same issue on the Image Carousel. Turned out to be caused by Jetpack CSS file, which can be very easily deactivated by following this guide: [](https://css-tricks.com/snippets/wordpress/removing-jetpack-css/)

**Comment by handmadestateofmind** [comment]
I have the same issue.

I use a 3 column structure at the top of my page. On both sides I have static images uploaded, while the middle column holds the image carousel. Until recently, carousel fitted perfectly the height and width of the column but few days ago it expanded across half of the page. The problem is across over 20 pages that use this layout and is visible on desktop , on mobile there is no issue.
This layout has been used for over a year without any issue until now.

You can reproduce the issue by going on this site:
https://handmadestateofmind.com/all-day-long-cardigan-knitting-pattern/

**Comment by monobloclimber** [comment]
I had the same problem and I just solved it by disabling the "Activate site accelerator" option of the Jetpack plugin

**Comment by handmadestateofmind** [comment]
> disabling the "Activate site accelerator" option of the Jetpack plugin

@monobloclimber thanks for tip.I just did that but no effect. will check later on.

**Comment by dunksten** [comment]
I have the same problem. Disabling site accelerator did not solve it. I tried to downgrade, but even that does not help. For now I just disabled the image carousels.

**Comment by Mal027** [comment]
I am having the same problem. Most image carousels no longer respect page parameters. For my **Media Carousel** widgets, however, swapping the skin from "Slideshow" to "Carousel" enables a width option that corrects the alignment issue. 

![image](https://user-images.githubusercontent.com/46428121/126018434-5c165f3a-a6d7-4cee-ad5f-de57765b3537.png)

I've had to disable a few carousels because they are not working right whatsoever. For example:

![image](https://user-images.githubusercontent.com/46428121/126018880-4b0e16a7-10eb-4ae8-8bc4-6bdb39bc25d7.png)
This is what is occurring vs what it is supposed to look like.

![image](https://user-images.githubusercontent.com/46428121/126018913-26e98359-3e52-4130-af8a-369cf20ff41d.png)

This is happening on v3.2.5 and 3.3.0 (I have since reverted back to 3.2.5 due to new bugs with edit functionality from the latest release. ([thread](https://github.com/elementor/elementor/issues/15672))

**Comment by DorShahar** [comment]
Hi everyone
After checking the issue, we noticed that is on the Jetpack plugin end. 
This has been also reported here: https://github.com/Automattic/jetpack/issues/20289 

This has also been reported here: https://wordpress.org/support/topic/jetpack-9-9-bug/#post-14640238

Thanks
