### ISSUE TITLE
new elementor issues conflict with wpallimport. Old version works fine

### ISSUE THREAD

**Issue by MartinLedpaleis** [elementor/elementor#15633]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by MartinLedpaleis** [comment]
After updating to the new stable elementor the wpallimport does not import new files. When i deactivate elementor it works.
elementor Versie: 3.3.0 (early version does not give problems)
elementor pro Versie: 3.3.2 
wpallimport Versie: 4.6.7

**Comment by cirkut** [comment]
@MartinLedpaleis Soflyy introduced a new update (4.6.8) that addresses this issue. This issue shouldn't be reopened.
