### ISSUE TITLE
Error import kits from library

### ISSUE THREAD

**Issue by alexdalzovo** [elementor/elementor#15630]
Hello,
I have tried in several environments to use the new "kit library" function and I am pretty sure that in the nginx environment it does not work properly.
The problem I have is that it does not overwrite the site settings and the header and footer, so in turn I find myself with inaccurate fonts and sizes and the wrong or absent header and footer (I have the PRO license).
i tried to test on another apache environment locally and it seems to work much better.
One mistake I find on both sides is that it duplicates posts and pages all the time :)

**Comment by alexdalzovo** [comment]
I am making several attempts and I doubt that it is a problem with each template kit, some import well, others do not

**Comment by alexdalzovo** [comment]
I'm mainly importing the Wedding Photographer template, if you have a pro license and already have headers and footers inserted it is not very intuitive, mainly there is a warning that says that this template is based on the new features of hello theme and that a function that deactivates or overwrite the existing.
the various font errors still remain, even if you reset the default kit

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
