### ISSUE TITLE
3.3.0 Buttons don't adopt style of Type

### ISSUE THREAD

**Issue by iStuff0** [elementor/elementor#15645]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Buttons don't adopt the style of Type selected and instead have the colour of style > normal > colour (which can't be cleared).

This is on the backend, on the front it adopts style of type.

3.3.0 also removed all hover colour styling, but again only on the backend, on the front it's fine. 

## Steps to reproduce

Hmm, might be tricky considering the pre-populated colour in style > normal is one of my global colours and i don't know how that's come about as it wasn't there pre-3.3.0, but drag in a button widget and, assuming it has pre-selected colour in style > normal, the type doesn't change it.

As for hover, just check a button that was created pre-3.3.0 and the colour in hover won't be there, yet will still be there on front end.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/6WxKvgcU

**Comment by DorShahar** [comment]
Hi @iStuff0 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
