### ISSUE TITLE
3.3.0 All global widgets greyed out

### ISSUE THREAD

**Issue by iStuff0** [elementor/elementor#15641]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
All global widgets are greyed out when editing page/post with Elementor. You can get them to show by clicking the widget then clicking edit, but it doesn't remain. On page re-load they're greyed out again.

These were all widgets and pages/posts created prior to 3.3.0

This is only on the backend. On the front everything is fine.

## Steps to reproduce

Edit with Elementor a page or post that has global widgets created before 3.3.0

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/6WxKvgcU

**Comment by DorShahar** [comment]
Hi @iStuff0 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
