### ISSUE TITLE
Responsive Problems on Mobile

### ISSUE THREAD

**Issue by GGZ78** [elementor/elementor#15653]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I'm having big issues with responsive on Mobile. What is displayed on navigators Dev Tools (Google Chrome, Firefox) and on Elementor's interface isn't what appears on my smartphone : titles are disappearing, margins and padding change, form fields can't be seen.
I've worked a lot with Elementor and it's just happening since recently which disappoints me. I'm attaching screens so you can see. I would like to had that phones' screens are taken with an iPhone X, just like the type of screen I'm using in Dev Tools.
![Bug2](https://user-images.githubusercontent.com/49448038/125676327-a7c1eba5-8855-41d6-abef-6d2d423aaa6c.png)
![Bug1](https://user-images.githubusercontent.com/49448038/125676328-68c8044e-6b31-4c42-bcc6-1512c9a93085.png)

I've tried to change themes (I'm using Hello Elementor), to downgrade my Elementor versions but nothing works. I've also tried to change theme settings, CSS from A to Z by myself, but it just doesn't want.
Thank you !

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active. (Hello Elementor)
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.50
	PHP Version: 7.2.34
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://www.webion-paris.fr
	Home URL: https://www.webion-paris.fr
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.3.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.2
		Author: Elementor.com

	Really Simple SSL
		Version: 4.0.15
		Author: Really Simple Plugins

	UpdraftPlus - Backup/Restore
		Version: 1.16.56
		Author: UpdraftPlus.Com, DavidAnderson

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		heading : 20
		image : 2
		social-icons : 1
	header : 1
		button : 1
		heading : 1
		icon : 2
		icon-list : 2
		image : 2
		nav-menu : 1
	popup : 2
		image : 1
		nav-menu : 1
	section : 1
		accordion : 4
		heading : 4
		image : 4
	wp-page : 23
		button : 33
		divider : 17
		form : 1
		heading : 343
		html : 3
		icon : 29
		icon-box : 41
		image : 9
		image-carousel : 2
		menu-anchor : 2
		price-table : 3
		slides : 1
		spacer : 5
		testimonial-carousel : 1

== Log ==
	
PHP: showing 3 of 3PHP: 2021-05-07 23:24:23 [notice X 5][/home/webionpanr/www/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-22 08:32:33 [error X 2][/home/webionpanr/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on null in /home/webionpanr/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/webionpanr/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(13, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/webionpanr/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/webionpanr/www/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/webionpanr/www/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#5 /home/webionpanr/www/wp-includes/plugin.php(484): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-22 23:32:41 [notice X 3][/home/webionpanr/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142021-06-21 23:36:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.5',
)]
2021-06-21 23:38:38 [info] elementor-pro::elementor_pro_updater Started 
2021-06-21 23:38:38 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-21 23:38:38 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-21 23:38:38 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-21 23:38:39 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-21 23:38:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]
2021-06-21 23:38:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]
2021-07-12 23:04:29 [info] elementor::elementor_updater Started 
2021-07-12 23:04:29 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-12 23:04:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-12 23:04:29 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-12 23:04:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-13 09:40:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.2',
)]

**Comment by Aviad-Herman** [comment]
Hi,
The issue seems to be happening on Safari (mobile & desktop alike).
To help you solve this issue I need a picture of the Editor Panel while editing the problematic widgets. I need to see what you did there please.

It seems to be related to the css property text-decoration:none so if you can tell me where you defined this it could also help

**Comment by GGZ78** [comment]
Hello,
It also occurs on Google Chrome on Mobile. I have not tested it on Safari Browser on desktop.
My text has no particular CSS definition. Here is screens tho : 
![Sans titre (1)](https://user-images.githubusercontent.com/49448038/125695762-2d15f6de-c6ae-4fa4-a61a-1b7c1cb0f027.png)

Thank you !

**Comment by GGZ78** [comment]
I'm closing this as the issue actually comes from **Gotham** font on Mac Safari and iOS mobile ; it's actually independent from Elementor. Thank you.

**Comment by Aviad-Herman** [comment]
Thanks for the explanation, you helped me learn too!
