### ISSUE TITLE
Elementor tablet mode not showing as an option in responsive mode

### ISSUE THREAD

**Issue by marka33** [elementor/elementor#15650]
elementor responsive tablet mode not visible

I do not have an option to see the page in tablet mode in the responsive icon at the Botton left of the page edit.

I have checked the mobile and tablet breakpoints and they are all set up correctly. I have regenerated the CSS files and cleared th site cache. Still no tablet option.
See an image of the problem below:

<img width="272" alt="Screen Shot 2021-07-13 at 6 35 00 PM" src="https://user-images.githubusercontent.com/15248178/125640701-a1bb3e13-a0bc-44f7-a546-17c65e654a84.png">

- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by avivu** [comment]
Hello @marka33 
We introduced a new Responsive Top Bar a few versions ago.
When clicking on the "Responsive Mode" Icon, a new top bar appears at the top of the edit screen.
You can find the option to switch between Desktop, Tablet, and mobile on the top bar.
Is that helped?

**Comment by marka33** [comment]
Yes, I figured it out. Thanks.
