### ISSUE TITLE
Swiper slider doesn't work.

### ISSUE THREAD

**Issue by htzenaul** [elementor/elementor#15657]
After activating the Improved Asset Loading, the Swiper slider doesn't work. 
http://prntscr.com/1bboita
My Activation 
http://prntscr.com/1bbqjpz
http://prntscr.com/1bbqzg7

**Comment by DorShahar** [comment]
Hi @htzenaul 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.


Thanks.
