### ISSUE TITLE
Responsive mode in slider widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15669]
[ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
By adding this feature, the dimensions of the slider images will be the same in all sizes (mobile, tablet and desktop).

**Describe the solution you'd like**
Unfortunately, when we upload an image to the slider widget, the size of that image varies from device to device. This works in contrast to the image widget. In the image widget, when we display an image using the image widget, the size of that image is the same on all devices.
**Of course, I mean the size of the image, the content of the image that is displayed on each device differently.**

To better understand this problem, I compare the slider widget and the image.

**At the bottom we see the image content in the image widget, which is the same shape on all devices,And this is great.**
Image Widget - Desktop Display : https://prnt.sc/1bjf63o
Image Widget - tablet Display : https://prnt.sc/1bjfvck
Image Widget - mobile Display : https://prnt.sc/1bjg6nv

**But at the bottom we see the image content in the slider widget, which is different for each device, and this is not good at all.**
slider Widget - Desktop Display : https://prnt.sc/1bjjqbo
slider Widget - tablet Display : https://prnt.sc/1bjkjvf
slider Widget - mobile Display : https://prnt.sc/1bjm1s2

As you can see above, in the slider widget, the smaller the screen size, the more incomplete the image size (it will shrink from the sides)
Of course, changing the height of the slider solves the problem to some extent, but the result is not satisfactory at all.
**Great order if you add a feature to the slider widget, so that the images are the same size in all sizes. Just like the image widget.**

I hope I conveyed my words well. thank you

**Comment by masoudahmadpour** [comment]
+1

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

When you edit a slide, you can choose a background image, the "Size" control allows you to set the [background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size). Please try to change it to contain/cover/auto to fix this issue.

![1](https://user-images.githubusercontent.com/92088692/157530603-b4098f02-82e0-4e44-88c9-ca89dde0f2c6.png)
