### ISSUE TITLE
E 3.3 / E pro 3.3.2 + improved CSS loading. Gallery pro filter bar pointer shows only in editor.

### ISSUE THREAD

**Issue by Deadlift79** [elementor/elementor#15660]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor 3.3/ Elementor pro 3.3.2. Enabling the experiment "improved CSS loading" makes gallery pro filter bar pointer (any type of pointer) visible only inside elementor editor. Previewing the page (or on frontend)
it disappears.

![Cattura1](https://user-images.githubusercontent.com/87310457/125778239-b5fcbcaa-1534-4e97-9026-5a50d58439f2.JPG)

![Cattura3](https://user-images.githubusercontent.com/87310457/125778255-a03f248b-8ecf-4c9a-ac0a-b29501fb0018.JPG)

## Steps to reproduce

Create a new multiple pro gallery, style your pointer, enable improved CSS loading.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #15683 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.1

Feel free to update

Thanks!
