### ISSUE TITLE
Testimonial carousel not working on Safari (iPad / iPhone)

### ISSUE THREAD

**Issue by sandra-dudley** [elementor/elementor#15674]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Since the latest updates, the testimonial carousel interaction doesn't work anymore. Only the first slides show, but it is not possible to slide to the next, and autoplay is not working either.

## Steps to reproduce
- It works fine when using Elementor  3.2.5 and Elementor Pro 3.3.1.
- It doesn't work when using Elementor 3.3.0 and Elementor Pro 3.3.2
- The issue seems to only happen on Safari for iPhone/iPad. It works on iMac.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.
Recently there was a problem with Jetpack regarding Carousels widgets - please check if it is related. 

Thanks.
