### ISSUE TITLE
Ability to Remove unused css in elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15678]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

**Description of the request :**
It would be great if you could add a feature so that we can delete unused css from the website. This feature has just been added to the wp-rocket plugin, but using it has no effect and worse it increases the page volume.
This option can be very important because elementor is desperately looking for its own optimization. Removing unused css has a great effect on reducing page volume and increasing loading speed.
**The image below is the result of analyzing a elemetor site(A site built entirely with elementor.). And shows how many unused css there are on the pages.**
![Screenshot (76)](https://user-images.githubusercontent.com/77163248/125948785-4cb13be1-d9e9-470d-a7cf-d46c58b73bd8.png)
If you add this feature to elementor, it would be great. **Provided that it really removes unused css.**
I hope elementor has a plan for that

thank you

**Comment by d19dotca** [comment]
Have you used the new CSS experiment in 3.3.0? It helped significantly with the "reduce unused css" recommendation from Google's Lighthouse analyzer. It didn't eliminate completely but had a positive impact on it.

**Comment by 79ho3ein** [comment]
Yes, I used it and it was very useful، But it is completely different from unused css cleanup. Unused CSS is present in a significant amount on all websites and is one of the main reasons for slowing down the website. As I mentioned above, the wp-rocket plugin added this feature, but it was not successful at all.
That's why I decided to make this offer to elementor. Because elementor is unique in everything And she can do it in the best possible way.

**Comment by d19dotca** [comment]
I don't really think they're "completely different" at all. The point of the CSS experiment was to basically remove or really slim down the frontend.css files that used to be quite large, and then load CSS conditionally depending on the widgets used in the page. This experiment is basically the same as Improve Asset Loading experiment where they did the same thing but for the JS files instead. 

If you turn on the experiment, you should see (as I did in my testing) that the "Reduce unused CSS" tag goes from a high impact to a low impact, meaning that the CSS experiment has indeed reduced the unused CSS. 

Naturally it still has a bit more work to be done on it (it is "alpha" state after all), but it definitely was meant to help with unused CSS, that's basically the whole point of that experiment as I understand it.

**Comment by 79ho3ein** [comment]
Yes, I agree with you. This new feature of elementor worked very well and as you said, there is definitely room for improvement. Of course, adding the same option to js files can also be very useful.

In any case, thank you for your valuable comments.

**Comment by shilo-ey** [comment]
Hey @79ho3ein 

As @d19dotca mentioned, you can try to use the new experiment to reduce the use of unused css dramatically, and we will continue reducing unneeded assets in Elementor.

Thanks, closing this for now, keep an eye for the next releases.
