### ISSUE TITLE
Site down if Elemento-pro is updated.

### ISSUE THREAD

**Issue by Luke-SF** [elementor/elementor#15671]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
I have encountered this on multiple sites with the Elementor version 3.1.4 or so. When upgrading to Elementor-pro 3.3 (latest version) it takes the site down.

Cannot call constructor, at:

/wp-content/plugins/elementor-pro/modules/query-control/module.php in ElementorPro\Modules\QueryControl\Module::__construct at line 51

	public function __construct() {
		parent::__construct();

## Steps to reproduce
Upgrade Elementor-pro before Elementor

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Multiple PHP7.4 environments.

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v10.3.30 |  
PHP Version: | 7.4.21 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by shilo-ey** [comment]
Hi @Luke-SF 
There's an intentional dependency between Elementor 3.3.0 & Elementor Pro v3.3.2. you need to update to v3.3.0 before you get Pro v3.3.2 to prevent breaks when editing the plugin.

All you need to do is update Elementor to v3.3.0 before updating to v3.3.2

Thanks
