### ISSUE TITLE
If i active Improved CSS Loading (custom css don't work)

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15681]
Hello, I add this code for an accordion

.elementor-accordion .elementor-tab-content {
    border-top: 0px;
    
}
.elementor-accordion .elementor-accordion-item {
    border-top: 1px solid ;
    border-bottom: 1px solid ;
    border-left: 0px;
    border-right: 0px;
}

in the editor, I see all changes, after on page I see a page without custom CSS, if I disable improved CSS all is good

**Comment by rotemee** [comment]
Hi @promocot,

When targeting your specific element, add `selector` before the tags and classes you want to exclusively target, i.e: selector a { color: red;}.

Visit the following URL for more details:
[https://elementor.com/help/custom-css-pro/](https://elementor.com/help/custom-css-pro/)

Thanks.

**Comment by promocot** [comment]
> Hi @promocot,
> 
> When targeting your specific element, add `selector` before the tags and classes you want to exclusively target, i.e: selector a { color: red;}.
> 
> Visit the following URL for more details:
> https://elementor.com/help/custom-css-pro/
> 
> Thanks.

I try, don't work

**Comment by promocot** [comment]
@DorShahar  you don't help, but close ticket

**Comment by rotemee** [comment]
@promocot, can you please send me the code that you've added?

**Comment by promocot** [comment]
> @promocot, can you please send me the code that you've added?

i write in ticket

.elementor-accordion .elementor-tab-content {
border-top: 0px;

}
.elementor-accordion .elementor-accordion-item {
border-top: 1px solid ;
border-bottom: 1px solid ;
border-left: 0px;
border-right: 0px;
}

**Comment by promocot** [comment]
i try to use 

selector .elementor-accordion .elementor-tab-content {
border-top: 0px;

}
.elementor-accordion .elementor-accordion-item {
border-top: 1px solid ;
border-bottom: 1px solid ;
border-left: 0px;
border-right: 0px;
}

I try to add before selector # and . but don't work

**Comment by rotemee** [comment]
@promocot, please add the "selector" the second rule as well:

selector .elementor-accordion .elementor-tab-content {
    border-top: 0px;
}
selector .elementor-accordion .elementor-accordion-item {
    border-top: 1px solid ;
    border-bottom: 1px solid ;
    border-left: 0px;
    border-right: 0px;
}

**Comment by promocot** [comment]
> @promocot, please add the "selector" the second rule as well:
> 
> ```
> selector .elementor-accordion .elementor-tab-content {
>     border-top: 0px;
> }
> selector .elementor-accordion .elementor-accordion-item {
>     border-top: 1px solid ;
>     border-bottom: 1px solid ;
>     border-left: 0px;
>     border-right: 0px;
> }
> ```

now is work, thanks, I understand my problem

**Comment by promocot** [comment]
> @promocot, please add the "selector" the second rule as well:
> 
> ```
> selector .elementor-accordion .elementor-tab-content {
>     border-top: 0px;
> }
> selector .elementor-accordion .elementor-accordion-item {
>     border-top: 1px solid ;
>     border-bottom: 1px solid ;
>     border-left: 0px;
>     border-right: 0px;
> }
> ```

with this code, I have another problem, double border in center of accordion, top and bottom is good, but center have 2 borders, if I change border-top 0px i resolve this problem, but first tab don't have border line

**Comment by rotemee** [comment]
@promocot, You need to change your CSS, to something like this:
```
selector .elementor-accordion .elementor-tab-content {
    border-top: 0px;
}
selector .elementor-accordion .elementor-accordion-item:first-child {
    border-top: 1px solid;
}
selector .elementor-accordion .elementor-accordion-item {
    border-bottom: 1px solid ;
    border-left: 0px;
    border-right: 0px;
}
```

**Comment by promocot** [comment]
> @promocot, You need to change your CSS, to something like this:
> 
> ```
> selector .elementor-accordion .elementor-tab-content {
>     border-top: 0px;
> }
> selector .elementor-accordion .elementor-accordion-item:first-child {
>     border-top: 1px solid;
> }
> selector .elementor-accordion .elementor-accordion-item {
>     border-bottom: 1px solid;
>     border-left: 0px;
>     border-right: 0px;
> }
> ```

thanks, work without problem
