### ISSUE TITLE
When "Improved CSS Loading" is active my Templates for the catergories doesn't work

### ISSUE THREAD

**Issue by JidWictut** [elementor/elementor#15683]
Hello,

when I activate "Improved CSS Loading" then my created templates for my catergory pages are no longer displayed correctly. In the editor everything looks normal.

I use the archive posts widget from Elementor.

Improved CSS Loading inactiv:
![Catergory inaktiv](https://user-images.githubusercontent.com/65712457/126043854-393567ef-515c-4ca6-9728-6d8e3ad0bba9.JPG)

Improved CSS Loading activ:
![Catergory aktiv](https://user-images.githubusercontent.com/65712457/126043886-f7446e67-2230-493c-b375-34ab338431e6.JPG)

With Kind Regards

**Comment by datverse** [comment]
Hi, I got this bug too.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.1

Feel free to update

Thanks!
