### ISSUE TITLE
Ability to live chat in elementor (elementor exclusive live chat)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15684]
[ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Great if elementor adds a live chat feature to its plugin. There are currently many plugins for this feature, but most are not optimized. They reduce the speed of the site.
If elementor adds this feature and makes it its own, it will definitely be better than other available plugins, Because elementor develops it specifically for its users.
![Screenshot (77)](https://user-images.githubusercontent.com/77163248/126046874-363ddf81-b290-492f-b029-05c98bdc00cd.png)

**Describe the solution you'd like**
As you know, live chat is better so that the communication between users and the webmaster is faster and easier. 
**The idea behind the live chat feature is that we can connect users and the webmaster in three ways.**
1- Connect elementor live chat feature to Telegram robot.
2- Connect elementor live chat feature to WhatsApp.
3- Connect elementor live chat feature to elementor live chat Application.

Of these 3 ways, the third is the best. But of course, building an application for this is time consuming. So the first way is the most appropriate. But the third case is definitely excellent and more user-friendly.
What matters is that this feature is added. It will definitely get better over time.
This feature can attract many users to elementor. And it certainly is.
There are many ideas for this live chat feature. I would like to know the opinion of elementor developers about this feature.

thank you

**Comment by Nazrinn** [comment]
Honestly you are better off using a third party plugin for that. Live chats are a huge feature that are usually handled better by CRM.

**Comment by 79ho3ein** [comment]
Hi @Nazrinn 
True, this is just an idea and it is not impossible to do it by the element.  But it is great if it is added to the element one day.

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. Elementor is not a chat-bot, it's a website builder.

Please feel free to contact us again with other feature suggestions.

Regards,
