### ISSUE TITLE
parseerror when submitting form (mailoptin plugin & sendinblue)

### ISSUE THREAD

**Issue by laurentmacca** [elementor/elementor#15698]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I got a parseerror message on front when I submit newsletter form build with elementor : only one field email with id email.
These form is driven by mailOptin connector to Sendinblue mailer agent.
On network console I got a xhr on status 200 but with this JSON response 
 <br />
<b>Notice</b>:  Undefined index: name in <b>/data/web/preprod.dlm.fr/htdocs/wp-content/plugins/mailoptin/src/connections/ElementorConnect/Elementor.php</b> on line <b>223</b><br />
<br />
<b>Notice</b>:  Undefined index: first_name in <b>/data/web/preprod.dlm.fr/htdocs/wp-content/plugins/mailoptin/src/connections/ElementorConnect/Elementor.php</b> on line <b>224</b><br />
<br />
<b>Notice</b>:  Undefined index: last_name in <b>/data/web/preprod.dlm.fr/htdocs/wp-content/plugins/mailoptin/src/connections/ElementorConnect/Elementor.php</b> on line <b>225</b><br />
{"success":true,"data":{"message":"Votre inscription est valid\u00e9e.","data":[]}}

I repeat : only one field. Documention of both mailOptin and Sendinblue allow a one field form.
Thanks for your help !

## Steps to reproduce
Just submit newsletter form on footer with any email adress.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>

<summary>System Info</summary>
				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '34', Revision '2e68637' v5.7.31-34
	PHP Version: 7.4.11
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.6
	Site URL: https://preprod.dlm.dlm.dis.app
	Home URL: https://preprod.dlm.dlm.dis.app
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0

== Active Plugins ==
	Duplicate Page
		Version: 4.3
		Author: mndpsingh287

	Elementor
		Version: 3.3.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.1
		Author: Elementor.com

	MailOptin - Lite
		Version: 1.2.38.0
		Author: MailOptin Team

	[DLM] Agences de location
		Version: 0.0.1
		Author: Eclipse communication

	[DLM] Catégorie de véhicule
		Version: 0.0.1
		Author: Eclipse communication

	[DLM] Formulaire de création de compte
		Version: 0.0.1
		Author: Eclipse communication

	[DLM] Formulaire de reservation
		Version: 0.0.1
		Author: Eclipse communication

	[DLM] Login
		Version: 0.0.1
		Author: Eclipse communication

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Non compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	section : 20
		button : 4
		call-to-action : 2
		divider : 6
		form : 2
		global : 10
		heading : 33
		icon-list : 7
		image : 5
		image-box : 3
		nav-menu : 5
		price-table : 7
		testimonial-carousel : 2
	widget : 0
		form : 1
		image-box : 1
		nav-menu : 5
		social-icons : 1
		wp-widget-dlm_login : 1
	wp-page : 79
		accordion : 2
		button : 115
		divider : 72
		form : 56
		global : 864
		google_maps : 30
		heading : 1391
		icon-list : 109
		image : 270
		image-box : 418
		nav-menu : 60
		price-table : 219
		share-buttons : 1
		testimonial-carousel : 35
		text-editor : 8
		wp-widget-dlm_account : 1

== Log ==
	
Log: showing 20 of 422021-07-05 11:17:08 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (26 of 36, 73%) 
2021-07-05 11:17:10 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (27 of 36, 75%) 
2021-07-05 11:17:12 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (28 of 36, 78%) 
2021-07-05 11:17:14 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (29 of 36, 81%) 
2021-07-05 11:17:16 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (30 of 36, 84%) 
2021-07-05 11:17:18 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (31 of 36, 87%) 
2021-07-05 11:17:20 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (32 of 36, 89%) 
2021-07-05 11:17:23 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (33 of 36, 92%) 
2021-07-05 11:17:25 [info] elementor-pro::elementor_pro_updater Started 
2021-07-05 11:17:25 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (34 of 36, 95%) 
2021-07-05 11:17:27 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (35 of 36, 98%) 
2021-07-05 11:17:30 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (36 of 36, 100%) 
2021-07-05 11:17:32 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-07-05 11:17:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.3.0',
)]
2021-07-05 11:17:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-07-19 12:14:25 [info] elementor::elementor_updater Started 
2021-07-19 12:14:25 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-19 12:14:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]
2021-07-19 12:14:26 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-19 12:14:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.0',
)]

PHP: showing 1 of 1PHP: 2021-07-07 09:21:47 [error X 2][/data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor\Modules\System_Info\Module->create_reporter()
#5 /data/web/preprod.dlm.fr/htdocs/wp-content/plugins/elementor/includes/tracker.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				

```
</details>

**Comment by Webtica** [comment]
Hi @laurentmacca, 

maybe I can help here. I just released a new plugin to the wordpress repo. 
It is a lightweight integration for Sendinblue for Elementor forms.
You can check it out here: https://wordpress.org/plugins/integration-for-elementor-forms-sendinblue/
I'm refining the plugin next week with some extra features like Dynamic fields and documentation aswel as a global API key field option.

Let me know if you need help!

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
