### ISSUE TITLE
iconHTML is not defined

### ISSUE THREAD

**Issue by EnterVPL** [elementor/elementor#15707]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi.
As it is in the documentation, I wanted to add an icon control https://developers.elementor.com/elementor-controls/icons-control/ but there is a problem when **_content_template** does not render the icon and an error in the console `iconHTML is not defined`

How am I to understand this
```html
<div class="my-icon-wrapper">
    {{{ iconHTML.value }}}
</div>
```
It just doesn't work?

I avoid the problem this way:

```html
<div class="my-icon-wrapper">
    <i aria-hidden="true" class="{{{ settings.icon_control.value }}}"> </i>
</div>
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.25
	PHP Version: 7.4.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: pl-PL
	Timezone: 1
	Admin Email: lukasz.bieniek@sembot.io
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.1
		Author: Elementor.com

	Polylang
		Version: 3.0.6
		Author: WP SYNTEX

	Query Monitor
		Version: 3.7.1
		Author: John Blackbourn

	Tavingo Elementor
		Version: 1.8.11
		Author: Łukasz Bieniek (EnterVPL)

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilny
	Tavingo Elementor: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	wp-page : 4
		tavingo-categories : 3
		tavingo-categorybox : 1
		tavingo-results : 3
		tavingo-search-bar : 3
		wp-widget-polylang : 3

== Log ==
	
PHP: showing 13 of 13PHP: 2021-03-15 10:10:51 [error X 1][/var/www/tavingo/wp-content/plugins/elementor/includes/plugin.php::709] Uncaught Error: Class &#039;Elementor\Data\Manager&#039; not found in /var/www/tavingo/wp-content/plugins/elementor/includes/plugin.php:709
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/plugin.php(487): Elementor\Plugin-&gt;__construct()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/plugin.php(725): Elementor\Plugin::instance()
#2 /var/www/tavingo/wp-content/plugins/elementor/elementor.php(54): require(&#039;/var/www/taving...&#039;)
#3 /var/www/tavingo/wp-settings.php(388): include_once(&#039;/var/www/taving...&#039;)
#4 /var/www/tavingo/wp-config.php(95): require_once(&#039;/var/www/taving...&#039;)
#5 /var/www/tavingo/wp-load.php(37): require_once(&#039;/var/www/taving...&#039;)
#6 /var/www/tavingo/wp-admin/admin-ajax.php(22): require_once(&#039;/var/www/taving...&#039;)
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-15 10:16:54 [error X 1][/var/www/tavingo/wp-content/plugins/elementor-pro/license/admin.php::280] Uncaught Error: Call to a member function get_component() on null in /var/www/tavingo/wp-content/plugins/elementor-pro/license/admin.php:280
Stack trace:
#0 /var/www/tavingo/wp-includes/class-wp-hook.php(292): ElementorPro\License\Admin-&gt;admin_license_details()
#1 /var/www/tavingo/wp-includes/class-wp-hook.php(316): WP_Hook-&gt;apply_filters()
#2 /var/www/tavingo/wp-includes/plugin.php(484): WP_Hook-&gt;do_action()
#3 /var/www/tavingo/wp-admin/admin-header.php(288): do_action()
#4 /var/www/tavingo/wp-admin/plugins.php(603): require_once(&#039;/var/www/taving...&#039;)
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-15 13:37:33 [notice X 2][/var/www/tavingo/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-05-18 11:09:26 [notice X 2][/var/www/tavingo/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 11:00:26 [notice X 13][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2004] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 11:04:30 [error X 1][/var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php::109] Uncaught TypeError: Argument 1 passed to Elementor\Core\Base\Base_Object::get_items() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 992 and defined in /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php:109
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(992): Elementor\Core\Base\Base_Object::get_items()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/base/element-base.php(997): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/includes/base/element-base.php(313): Elementor\Element_Base-&gt;init_children()
#3 /var/www/tavingo/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(35): Elementor\Element_Base-&gt;get_children()
#4 /var/www/tavingo/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(36): Elementor\Core\DynamicTags\Dynamic_CSS-&gt;render_styles()
#5 /var/www/tavingo/wp-content/plugins/el [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 14:06:17 [error X 9][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1001): Elementor\Core\Base\Base_Object-&gt;get_settings()
#5 /var/www/tavingo/wp-content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 14:28:35 [error X 1][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/categorybox/CategoryBoxRegisterControls.php(10): Elementor\Core\Base\Base_Object-&gt;get_setti [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-08 14:31:09 [error X 3][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/categorybox/CategoryBoxRegisterControls.php(45): Elementor\Core\Base\Base_Object-&gt;get_setti [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-09 09:56:13 [error X 1][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/categorybox/CategoryBoxRegisterControls.php(44): Elementor\Controls_Stack-&gt;get_init_settings()
#3 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1951): Sembot\Widgets\CategoryBox\CategoryBoxRegisterControls-&gt;_register_controls()
#4 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/Widget.php(1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-09 09:58:33 [error X 1][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/categorybox/CategoryBoxRegisterControls.php(46): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1951): Sembot\Widgets\CategoryBox\CategoryBoxRegisterControls-&gt;_register_controls()
#3 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/Widget.php(14): Elementor\Controls_Stack-&gt;init_controls()
#4 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(461): S [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-09 10:30:40 [error X 2][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#3 /var/www/tavingo/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#4 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(325): Elementor\Core\Base\Base_Object-&gt;get_settings()
#5 /var/www/tavingo/wp-content/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-09 10:38:49 [error X 1][/var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack-&gt;sanitize_settings()
#1 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/categorybox/CategoryBoxRegisterControls.php(49): Elementor\Controls_Stack-&gt;get_data()
#2 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(1951): Sembot\Widgets\CategoryBox\CategoryBoxRegisterControls-&gt;_register_controls()
#3 /var/www/tavingo/wp-content/plugins/tavingo-wp-elementor/widgets/tavingo/Widget.php(14): Elementor\Controls_Stack-&gt;init_controls()
#4 /var/www/tavingo/wp-content/plugins/elementor/includes/base/controls-stack.php(461): S [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 292021-03-15 10:11:38 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-03-15 10:11:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.1.1',
)]
2021-03-15 10:11:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.1.1',
)]
2021-04-27 12:40:02 [info] elementor::elementor_updater Started 
2021-04-27 12:40:02 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-27 12:40:02 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-27 12:40:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.2',
)]
2021-04-27 12:40:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.2',
)]
2021-04-27 12:40:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.1',
)]
2021-05-06 12:52:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.2',
  'to' => '3.2.3',
)]
2021-05-06 12:52:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.2.2',
)]
2021-06-07 12:35:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.3',
  'to' => '3.2.4',
)]
2021-06-18 14:12:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.4',
  'to' => '3.2.5',
)]
2021-06-25 09:40:58 [info] elementor-pro::elementor_pro_updater Started 
2021-06-25 09:40:58 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-25 09:40:58 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-25 09:40:58 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-25 09:40:58 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-25 09:40:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]
2021-06-25 09:40:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]

</details>

**Comment by shilo-ey** [comment]
Hi @EnterVPL 

Thanks,

The correct value is `{{{ settings.icon.value }}}`
We will update the documentation according to the correct parameter

**Comment by EnterVPL** [comment]
{{{ settings.icon.value }}} printing `[object Object]`

**Comment by EnterVPL** [comment]
Wait!
For SVG printing `{{{ settings.icon.value }}`
For selected icon printing class name eg `fas fa-align-justify`

**Comment by rotemee** [comment]
@EnterVPL, What you did is correct:

`settings.icon_control.value`

The `icon_control` is the name of your control, and this is the correct solution.

**Comment by EnterVPL** [comment]
@rotemee 
And then i use this
```html
<div class="my-icon-wrapper">
    <i aria-hidden="true" class="{{{ settings.icon_control.value }}}"> </i>
</div>
```
for selected icon and this
```html
<div class="my-icon-wrapper">
    <div style="background-image: url({{{ settings.icon_control.value.url }}})"></div>
</div>
```
for SVG?

**Comment by rotemee** [comment]
@EnterVPL, you don't need an SVG solution in the content_template function, because it runs only inside the editor.
In the editor, the Font-Awesome library is always loaded and available.

Therefore, the SVG solution is only needed inside the render() function, and it should be handled automatically by the `\Elementor\Icons_Manager::render_icon` function.

**Comment by EnterVPL** [comment]
@rotemee 
But why I don't need? If I upload SVG (or I'll change anything not related to the icon) then a icon is not showing on editor. This is problem.
What should I use to contnet_template to work properly?

**Comment by EnterVPL** [comment]
@shilo-ey
@rotemee

Today I updated Elementor and checked this problem again

I see change in doc ( https://developers.elementor.com/elementor-controls/icons-control/ ) but it still not working:
```html
<div class="my-icon-wrapper">
    {{{ settings.icon.value }}}
</div>
```
This printing icon class name (eg. `far fa-bookmark`) but not creating html element (eg. `<i aria-hidden="true" class="far fa-bookmark"> </i>`)
and if I upload SVG as icon then printing `[object Object]`.

Is there a function in the content template that, like the `Icons_Manager::render_icon()` method in render(), creates an icon no matter if it's me fa icon or svg?

**Comment by rotemee** [comment]
@EnterVPL, Try to use the following instead (only inside the content_template function):

`var iconHTML = elementor.helpers.renderIcon( view, settings.icon_control, { 'aria-hidden': true }, 'i' , 'object' );

{{{ iconHTML.value }}}`

**Comment by EnterVPL** [comment]
@rotemee 
It's working!

Thank you

**Comment by saulobraine** [comment]
Hi, have a render function for frontend JavaScript class?
My html is returned by ajax call.
