### ISSUE TITLE
Please add the preloader feature to elementor.

### ISSUE THREAD

**Issue by alexandra9941** [elementor/elementor#15704]
hello elementor teame
The preloader feature is excellent and widely used. But it is strange that it does not exist in elementor. I use a plugin that is compatible with elementor for this feature. But using the plugin is not optimal and makes the site heavy.
Please see this plugin : https://wordpress.org/plugins/loading-page/
Does elementor have a plan to add this feature?
**Will we see this feature in elementor in 2021?**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #10576, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
