### ISSUE TITLE
Slider widget navigation points are loaded late...

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15717]
hello
This problem existed for me in elementor pro from the beginning, but I do not know if it is the same for other users, But I used the slider widget at the top of the page. **When the page loads, the dots in the slider widget load 2 seconds later than the slider image.**
I do not know exactly what the problem is, but there is and it is very annoying.
This problem is clearly evident when I test from gtmetrix.

thank you

**Comment by DorShahar** [comment]
Thanks for letting us know.
Unfornuetly - this is the behavior of the JS, which runs after `document.loaded`
This happens in purpose - to improve the page performance. We are aware of the UX problem, however, the cost-effectiveness of 2-sec' delay in certain situations in prefer of blocking the page and increasing its loading time.

Thank you for understanding.

**Comment by 79ho3ein** [comment]
thank you @DorShahar
