### ISSUE TITLE
WooCommerce grid styles missing from frontend.css in Elementor Pro 3.3.3 thus breaking archive grids

### ISSUE THREAD

**Issue by askwpgirl** [elementor/elementor#15718]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Updating to Elementor Pro 3.3.3 results in WooCommerce product grids displaying products singly rather than in column grids.

## Steps to reproduce

1. Create Product Archive template in Elementor > Theme Builder.

2. Add Product Archive widget.

3.  Set Conditions to be used on Product Category or Product Archive pages.

4. Update to Elementor Pro 3.3.3.

5. Refresh your product archive page. Products will display one per row rather than in a grid.

The missing CSS is in Elementor Pro > Assets > CSS > frontend.css. If you look at Elementor 3.3.1, the CSS for the column grids for products starts on line 507 through line 637. This has been removed from Elementor 3.3.3 thus causing this issue.

The problem can be fixed by copying the 3.3.1 styles (from the lines listed above) to your child theme or de-activating the Elementor Theme Builder Product Archive template and using the theme's default product grid or rolling back Elementor Pro to version 3.3.0 or 3.3.1. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/9Dv3yMCD
```
</details>

**Comment by webinfinitynz** [comment]
I'm having the same problem. Also, the problem (ignoring the column settings / only showing in 1 column) is also happening on the 'Product Categories' widget.

**Comment by ivansuknovic** [comment]
I'm having the same issue that @askwpgirl described.
I'm using Elementor Pro + Astra Pro Theme on one website and Elementor Pro + Hello Elementor Theme on another.

**Comment by htmlswift** [comment]
Same issue for me, missing Grid CSS code.

Here is the missing CSS code, if anyone is looking for - 

`@media (min-width: 1025px) {
  .elementor-element.elementor-products-grid ul.products.columns-2 {
    grid-template-columns: repeat(2, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-2 ul.products {
    grid-template-columns: repeat(2, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-3 {
    grid-template-columns: repeat(3, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-3 ul.products {
    grid-template-columns: repeat(3, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-4 {
    grid-template-columns: repeat(4, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-4 ul.products {
    grid-template-columns: repeat(4, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-5 {
    grid-template-columns: repeat(5, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-5 ul.products {
    grid-template-columns: repeat(5, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-6 {
    grid-template-columns: repeat(6, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-6 ul.products {
    grid-template-columns: repeat(6, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-7 {
    grid-template-columns: repeat(7, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-7 ul.products {
    grid-template-columns: repeat(7, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-8 {
    grid-template-columns: repeat(8, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-8 ul.products {
    grid-template-columns: repeat(8, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-9 {
    grid-template-columns: repeat(9, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-9 ul.products {
    grid-template-columns: repeat(9, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-10 {
    grid-template-columns: repeat(10, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-10 ul.products {
    grid-template-columns: repeat(10, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-11 {
    grid-template-columns: repeat(11, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-11 ul.products {
    grid-template-columns: repeat(11, 1fr); }
  .elementor-element.elementor-products-grid ul.products.columns-12 {
    grid-template-columns: repeat(12, 1fr); }
  .elementor-element.elementor-products-grid .woocommerce.columns-12 ul.products {
    grid-template-columns: repeat(12, 1fr); } }

@media (max-width: 1024px) {
  .elementor-element.elementor-products-grid ul.products {
    grid-template-columns: repeat(3, 1fr); } }

@media (max-width: 767px) {
  .elementor-element.elementor-products-grid ul.products {
    grid-template-columns: repeat(2, 1fr); } }

@media (min-width: 1025px) {
  .elementor-element.elementor-products-grid.elementor-products-columns-1 ul.products {
    grid-template-columns: repeat(1, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-2 ul.products {
    grid-template-columns: repeat(2, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-3 ul.products {
    grid-template-columns: repeat(3, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-4 ul.products {
    grid-template-columns: repeat(4, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-5 ul.products {
    grid-template-columns: repeat(5, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-6 ul.products {
    grid-template-columns: repeat(6, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-7 ul.products {
    grid-template-columns: repeat(7, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-8 ul.products {
    grid-template-columns: repeat(8, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-9 ul.products {
    grid-template-columns: repeat(9, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-10 ul.products {
    grid-template-columns: repeat(10, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-11 ul.products {
    grid-template-columns: repeat(11, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-12 ul.products {
    grid-template-columns: repeat(12, 1fr); } }

@media (max-width: 1024px) {
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-1 ul.products {
    grid-template-columns: repeat(1, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-2 ul.products {
    grid-template-columns: repeat(2, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-3 ul.products {
    grid-template-columns: repeat(3, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-4 ul.products {
    grid-template-columns: repeat(4, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-5 ul.products {
    grid-template-columns: repeat(5, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-6 ul.products {
    grid-template-columns: repeat(6, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-7 ul.products {
    grid-template-columns: repeat(7, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-8 ul.products {
    grid-template-columns: repeat(8, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-9 ul.products {
    grid-template-columns: repeat(9, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-10 ul.products {
    grid-template-columns: repeat(10, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-11 ul.products {
    grid-template-columns: repeat(11, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-tablet-12 ul.products {
    grid-template-columns: repeat(12, 1fr); } }

@media (max-width: 767px) {
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-1 ul.products {
    grid-template-columns: repeat(1, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-2 ul.products {
    grid-template-columns: repeat(2, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-3 ul.products {
    grid-template-columns: repeat(3, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-4 ul.products {
    grid-template-columns: repeat(4, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-5 ul.products {
    grid-template-columns: repeat(5, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-6 ul.products {
    grid-template-columns: repeat(6, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-7 ul.products {
    grid-template-columns: repeat(7, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-8 ul.products {
    grid-template-columns: repeat(8, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-9 ul.products {
    grid-template-columns: repeat(9, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-10 ul.products {
    grid-template-columns: repeat(10, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-11 ul.products {
    grid-template-columns: repeat(11, 1fr); }
  .elementor-element.elementor-products-grid.elementor-products-columns-mobile-12 ul.products {
    grid-template-columns: repeat(12, 1fr); } }
`

**Comment by wpturnedup** [comment]
Same issue. I'm using the latest version of Astra (FREE), the latest versions of Elementor/Elementor Pro, and I have ALL Elementor Experiments turned OFF.

**Comment by shilo-ey** [comment]
Hey Angela @askwpgirl and @wpturnedup !
Thanks for letting us know.

A patch has been released that resolves this issue.

Feel free to update to Elementor Pro v3.3.4

Thanks

**Comment by webinfinitynz** [comment]
1. Elementor Pro v3.3.4 isn't appearing in my site's WordPress update (dashboard>updates) yet. Does the patch just need time to get pushed to all the update servers?
2. Will v3.3.4 also fix the Product Categories widget (also broken since last version)?

**Comment by wpturnedup** [comment]
3.3.4 just popped into my dashboard minutes ago. Would give it time.

**Comment by webinfinitynz** [comment]
Thanks @wpturnedup

**Comment by webinfinitynz** [comment]
Just to confirm the update did also fix the Product Categories widget as well.

**Comment by sstrantz** [comment]
I have installed 3.3.4, but it did not resolve the column issue.

**Comment by askwpgirl** [comment]
> I have installed 3.3.4, but it did not resolve the column issue.

@sstrantz - Try clearing all your caches. It does resolve the problem, so now it might be caching of the old stylesheet that is the issue for you.

**Comment by sstrantz** [comment]
@askwpgirl 
Thank you for the response.  When I read the topic a little closer, it may be a little different than you described.  Here is what's happening:

Problem on Product Grid mobile view.
Elementor Pro version: 3.3.4

Product Grid, Mobile View, Columns set to 1

Displays 2 columns rather than 1.

VERSION 3.3.4 Pro version does not fix this issue.

**Comment by askwpgirl** [comment]
@sstrantz - Yes, I think that's a different problem, and I actually noticed that last night. I am looking more closely into it this afternoon. If it is a bug with 3.3.4, I'm going to submit another github ticket. That's the first time I saw that, and it's the only site I'm working with 3.3.4 on.

**Comment by sstrantz** [comment]
@askwpgirl 
I also just noticed that it won't change the number of columns on tablet either.

Thanks again.

**Comment by sstrantz** [comment]
PS:  
I'm new to github and tried to submit a bug report but (by initial ignorance) didn't follow the correct format.  Not sure if that will make them ignore it.  This is the link:  https://github.com/elementor/elementor/issues/15773

If I should delete that and just let you submit with proper format, let me know.

**Comment by askwpgirl** [comment]
I think perhaps it will need to be adjusted. I'll do some testing today and comment on that ticket and cc: Shilo if it's really what we think it is.

**Comment by sstrantz** [comment]
@askwpgirl 
Thank you.  I'm kind-of at a standstill as I need to create a new site but don't want to proceed until this issue is resolved.  And, of course, under deadline.  Right now the product grid columns aren't even editable on tablet.

**Comment by askwpgirl** [comment]
@sstrantz - This CSS will fix the issue:

`@media (max-width: 767px) {
	.elementor-element.elementor-products-grid ul.products {
    	grid-template-columns: repeat(1,1fr);
		}
	}`

They seem to be deliberately setting the columns to two across. I see this on another site that was not updated, so this may be by design for awhile. On my non-Elemenetor sites, it is one across.

If you want to further fine-tune this, you could instead keep it 2 across for the 767 (vertical tablet) and instead change it over to 1 across at a small size using this code instead:

`@media (max-width: 600px) {
	.elementor-element.elementor-products-grid ul.products {
    	grid-template-columns: repeat(1,1fr);
		}
	}`
	
I'm not sure if this is a bug, so I don't know whether to report it. I think two across on all mobile devices is too wide, and on my sites, it forces the second product to overflow the container. 

Let me know if the above CSS does the trick for you. You can put it under Appearance > Customize > Custom CSS or in your child theme's stylesheet. It works for me.

**Comment by sstrantz** [comment]
@askwpgirl 

Thank you!  I'll look at that today.  Also, the other topic I linked above got a reply that they'd address the issue soon.

**Comment by kieranmccarthy** [comment]
Updated today and the same issue has come back, columns display one product per row.
Using Elementor 3.3.1 and Elementor 3.3.1 Pro 3.3.5

**Comment by PauloCarrasco** [comment]
Hi.

I've solved it until the bug fix by customizing the upsell and related grids independently. Here's my implementation:

.elementor-widget-woocommerce-product-upsell ul.products {  grid-template-columns: repeat(3,1fr); } 

.elementor-element.elementor-widget-woocommerce-product-related ul.products {  grid-template-columns: repeat(5,1fr); } 

@media (max-width: 792px) { 
	.elementor-widget-woocommerce-product-upsell ul.products,
	.elementor-element.elementor-widget-woocommerce-product-related  ul.products { 
		grid-template-columns: repeat(2,1fr); 
	} 
}

@media (max-width: 600px) { 
	.elementor-widget-woocommerce-product-upsell ul.products,
	.elementor-element.elementor-widget-woocommerce-product-related  { 
		grid-template-columns: repeat(1,1fr); 
	} 
}

hope it helps until Elementor fixes this bug.

**Comment by Majordoit** [comment]
I do not see this issue as resolved as it is still happening on many of my websites. The only workable solution so far has been to role bace Elementor Pro to v 3.3.0

**Comment by askwpgirl** [comment]
@shilo-ey - Shilo, you fixed the issue in 3.3.4 and then repeated the mistake in 3.3.5 with all the same missing styles. Please re-open this ticket.

You need to make sure the commit for the original mistake is corrected, so it doesn't keep getting removed with each version.

For those of you wanting the missing styles, I have put them in a gist here:

https://gist.github.com/askwpgirl/4f83c25cd4f08607eeb2653d1aa21336

 @Majordoit @sstrantz @PauloCarrasco @kieranmccarthy

**Comment by zeinnicholas** [comment]
+1

**Comment by DonD30** [comment]
I get the same error on my current development site. Using Elementor 3.3.1 and Elementor Pro 3.3.5

**Comment by richward111** [comment]
+1

**Comment by ZENwww** [comment]
+1 on PRO 3.3.4 and free version 3.4.4
