### ISSUE TITLE
ELEMENTOR PRO TEMPLATE KITS NOT ABLE TO BE APPLIED/IMPORTED - ONGOING ISSUE

### ISSUE THREAD

**Issue by BillyBatson88** [elementor/elementor#15715]
After nearly a week of trying - and having others try - it appears that the new "Kit Library" of Template Kits cannot be utilized. Every time I've tried, I get a "Something Went Wrong" error message. When I refresh and try again, I get the "Connect To The Elementor Template Library By Creating An Account" dialogue box - even though I'm trying to use the Template Kit feature WITH my activated/verified/connected Elementor Pro License.

![screenshot-www daltonmediagroup com-2021 07 20-11_32_25](https://user-images.githubusercontent.com/87679086/126378944-bbbbe863-5792-465f-a2df-63e81906b388.png)

When I do click the "Connect ..." button, I am brought to a screen saying that "Your License Has Exceeded The Limitation."

![screenshot-my elementor com-2021 07 19-16_35_24](https://user-images.githubusercontent.com/87679086/126378988-f28ed827-f484-413d-8a8f-04766764ce81.png)

The problem is, HOW can my license have "exceeded its limitation" if I'm trying to utilize a Template Kit via my active/verified/connected Elementor Pro License within the site backend for which the license is assigned?

Has anyone else been able to "Apply" any of the Template Kit Templates - as advertised by Elementor as part of the latest Pro update ???

If not, then this is definitely a serious bug that needs to be fixed.

It wouldn’t bother me so much if there wasn’t one of the templates with “ready-made/configured” features I REALLY LIKE and REALLY want to utilize - and being able to would save me A LOT of time trying to clone design/configure it myself.

I even upgraded my Elementor Pro License - optimistically hoping this would resolve the "license limitation" issue.  
It Did Not.

![screenshot-my elementor com-2021 07 20-00_30_54](https://user-images.githubusercontent.com/87679086/126379144-de257177-c1d7-4851-b74f-0dbfdcef29ef.png)

I did as you (**shilo-ey**) directed yesterday (July 19, 2021) and the Elementor Support Team has not seen fit to respond relative to this ongoing issue - despite my advising of your direction.

Further, I updated my Elementor Pro to the latest 3.3.3 update - and the issue continues to persist . . . still getting the "Something went wrong. - Nothing to worry about, just try again. If the problem continues, head over to the Help Center." error message and unable to apply any Template Kit (let alone the ONE I very much want/need).

![screenshot-www daltonmediagroup com-2021 07 20-11_32_25](https://user-images.githubusercontent.com/87679086/126379304-d5f6154d-eda4-4d30-905c-a404af6d1947.png)

Would it be at all possible to obtain a zip file of the ONE Template Kit I want/need- while this persistent problem continues?
The Template Kit to which I am referring is the black "MUSIC FESTIVAL" Kit.

Looking forward to your further pro-active response.

THANK YOU !!!

**Comment by goblineer** [comment]
I am also completely unable to use this feature. 

I'm sure that your whole team is painfully aware of whatever it is that's going wrong, so I won't make a redundant complaint. 

Suffice it to say that the open issue persists, is very frustrating, and is extremely well-documented in this post.

Please communicate with your (paying) users. Your customer service folks have been no help whatsoever regarding this problem. I'm sure we're all looking forward to a speedy reply containing a respectful amount of information -- and, of course, to a quick resolution. Thanks.

**Comment by BillyBatson88** [comment]
Here's a "FIX IT IMMEDIATELY" suggestion  . . . . 

**Why not flip a code switch and make the Template Kits DOWNLOADABLE for paid/licensed Elementor Pro member**s - similar to how Envato Elements does with its Template Kits?  That way, members can utilize the parts of the kits they want - rather than having to import the entire kit. 

I think this would be a reasonable temporary - and most importantly, **IMMEDIATE USE** - fix for Elementor's Pro Members while the "Dev Team" works on fixing the import/apply issue.   


Here's hoping for a cooperative/considerate solution we can utilize IMMEDIATELY rather than days/weeks/months from now.

**Comment by andre-orion** [comment]
> Aqui está uma sugestão "CORRIGIR IMEDIATAMENTE". . . .
> 
> **Por que não girar uma chave de código e tornar os kits de modelo** BAIXÁVEIS para **membros do Elementor Pro pagos / licenciados** - semelhante a como o Envato Elements faz com seus kits de modelo? Dessa forma, os membros podem utilizar as partes dos kits que desejam - em vez de ter que importar o kit inteiro.
> 
> Eu acho que isso seria uma correção temporária razoável - e mais importante, **USO IMEDIATA** - para membros Pro do Elementor enquanto o "Dev Team" trabalha para consertar o problema de importação / aplicação.
> 
> Esperamos por uma solução cooperativa / atenciosa que possamos utilizar IMEDIATAMENTE, em vez de dias / semanas / meses a partir de agora.

That's exactly what I asked for in support. I got no answer...

**Comment by ruben-peters-panton** [comment]
Hi,

I also had the: "Something went wrong. - Nothing to worry about, just try again. If the problem continues, head over to the Help Center." error message

For me what fixed it was a PHP downgrade from 8.0 > 7.4! Most hosting providers let you select which PHP version you want to use.

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by ingodwetryst** [comment]
No it absolutely has not.  I am still having the problem today with a lot of the kits.

**Comment by robertmylne** [comment]
Same issue here. Can't even activate my licence.
