### ISSUE TITLE
Improved JS Loading in elementor...

### ISSUE THREAD

**Issue by alexandra9941** [elementor/elementor#15719]
**What problem is your feature request going to solve? Please describe.**
In the serious version of the elementor plugin, the Improved CSS Loading feature has been added. This feature worked great and to a great extent **Eliminate reduced render-blocking** resources.
But it would be great if you could add such a feature to optimize JS code as well. This feature is extremely required. Elementor site scripts are in dire need of improvement.
This is an example of an all elementor website. (hello theme) :
![Screenshot (85)](https://user-images.githubusercontent.com/77163248/126415139-5de58907-48f5-4a17-9e4c-b39f60a7616f.png)
As shown in the image, the scripts are in dire need of improvement.
Will we see such a feature to improve JS in elementor?

**Comment by shilo-ey** [comment]
Yes, We are working on several additional improvements to this aspect in the next version,

You can try it out using Dev Edition

Closing this for now.
Thanks
