### ISSUE TITLE
Report an important bug in elementor sectioning.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15725]
hello
I do not know if this problem existed in the beginning, or arose in version 3.3. But there is a problem anyway, and I realized it by accident.
The problem is that if in a section, the number of columns is more than 6, by changing the length of the columns, their control is out of reach. (The section is spaced from the right and not aligned with the left)
To better understand this problem, please watch this video. **(Please note the parts I point to with the mouse)**

https://drive.google.com/file/d/1EPpyVnmFxD5a3JD4MYhstKrDEJF6Abfp/view?usp=sharing

As you can see in the video above, everything was fine when I divided the columns into 6 parts. But when I increased or decreased the distance between the columns, the section moved to the left.

It should be noted that I encountered this problem in designing the header.

thank you

**Comment by Aviad-Herman** [comment]
Hey,
thanks for raising this issue. It seems like a problem.
I would suggest doing one of several things:

1. Using many columns is slowing down your site. It's much better to use one column and for each element assign them Advanced > Positioning > Width = Custom.
![image](https://user-images.githubusercontent.com/73067562/126563337-eb88e201-d735-41bf-b147-85d24df3f377.png)



2. If you absolutely must use columns you can set their width manually.
![image](https://user-images.githubusercontent.com/73067562/126563596-fde1f74f-2c43-4c45-9eab-a4b0b3507c99.png)

3. You can always decrease the browser screen resolution using ctrl and "-" and then resize by dragging.

**Comment by 79ho3ein** [comment]
thank you @Aviad-Herman 
The first one is great, but it has its drawbacks. By doing this, there is no distance between the two widgets and they stick together.

**Comment by Aviad-Herman** [comment]
Set some margin on each element.
Another option is to use Custom CSS to make one column (which are display:flex) have direction: row and play with the spacing property or child grow / shrink properties.

**Comment by 79ho3ein** [comment]
thank you
