### ISSUE TITLE
Dark mode feature, on websites made with elementor (Ideas for adding this feature)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15748]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

**Request description**
hello
Dark mode is very common today and its place in elementor is very empty. I have ideas to add this feature to elementor and I do not know if elementor has thought about it before or not ...

**Idea to add this feature to elementor :**

To add a dark mode feature to elementor, just add another color to all the widgets and sections of the site that can apply color.
This means that we can apply 2 colors to all widgets. **Like the image below, which I try to implement the concept design :**
![Screenshot (89)](https://user-images.githubusercontent.com/77163248/126777548-bd054897-930f-47a9-8dec-ded833c37c8e.png)
As you can see in the image above, we can apply two colors to all widgets. One color for light mode, and the other for dark mode.
**In addition, we can put two colors in the global color section so that the dark mode can be implemented more quickly for users.** Like the image below :
![Screenshot (90)](https://user-images.githubusercontent.com/77163248/126778114-7facc4e1-7c6e-4e5e-b113-858c4806e432.png)

**We've run 80% of the way so far, but how do users enable this dark mode in website?** 
To do this, we need to add a new widget, this widget will have many uses in the elementor future and there are many ideas for it. 
But in this suggestion, I want to say its use to activate the dark mode ...
new widget = **Switcher widget**
![Screenshot (91)](https://user-images.githubusercontent.com/77163248/126779126-4a79bcfe-3b75-4f52-a7a6-725568153051.png)
As I said above, this widget will have many uses in the future. This widget works with dynamic tags. Because it is supposed to be used a lot. One of these uses is to activate the dark mode we are talking about.
When we use this widget and see its dynamic tags, if we have already set the dark mode colors, a new item will be added in the dynamic tag options section as dark mode activation.
![Screenshot (92)](https://user-images.githubusercontent.com/77163248/126780029-e4c07a76-6f04-4848-9ce6-fb68948f6b09.png)
By selecting this option, the Switcher widget connects to the dark / light mode feature. And users can use this widget(Switcher widget) to change the site to dark and light.

I hope the explanation was helpful. Thank you

**Comment by Michaelgimii** [comment]
+1 
It was a very interesting idea, I welcome it.
