### ISSUE TITLE
Bug in the new version of elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15751]
hello
I just came across this bug and wanted to share it with you. **The problem is that I can not see the editing records. When I click view, the page crashes.** I also see several errors in the Chrome browser console tab for this page (header builder).
Of course, this problem is very confusing. I could not tell where the problem was, because everything is messed up and every time something new happens. To better understand the problem.
please watch this video, you will see that viewing editing records is unusual : https://drive.google.com/file/d/1vt5gfcMC7XzwprnenTjRhDFUqPX-hZVr/view?usp=sharing
**This problem only exists in the header builder**. The number of errors on this page is terribly high.

thank you

**Comment by 79ho3ein** [comment]
This problem exists in all parts. footer builder, header builder and ... 
Above, I just saw the problem in the header builder.But now I see that it is much broader.

**Comment by DorShahar** [comment]
Hi @
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by 79ho3ein** [comment]
thank you 
I am using hello elementor theme and my WordPress version is 5.8.
I tested this problem on several websites built with elementor and it was there. 
Surprisingly, this problem often occurs when we are editing the icon widget. In this case, we can not see the date of the changes. Just like the video.
