### ISSUE TITLE
✅ 🚀 Feature Request: Visual Indication of element that has CSS ID/class/custom code set

### ISSUE THREAD

**Issue by hiviz** [elementor/elementor#15780]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When you set CSS ID/class/custom code to Elementor elements (reference: https://prnt.sc/1gjk43d ... https://prnt.sc/1gjk6qm), there is no indication that these values have been set. The only way to check if (and to what value) a CSS ID/class/custom code has been set, is to brute force manually inspect each and every element. This becomes especially more laborious when you have many many elements on the page/post/template of interest. 

**Describe the solution you'd like**
1) Some sort of visual indicator of the element itself or in the navigator for those elements that have a CSS/ID/class/custom code value set. For inspiration, (un)responsive views have a "dimmed" visual indicator (reference: https://prnt.sc/1gjljo9).

...and/or

2) Central dashboard that specifies exactly which element in which page/post/template has a CSS ID/class/custom code value set.

**Describe alternatives you've considered**
Separately write down the value and location of CSS ID/class/custom code in a notepad. This approach has no "real time connection" to the actual website, and thus, becomes outdated as soon as any changes are made on the website and the notepad is not correspondingly updated. Also, is prone to human error.

**Additional context**
I'm not requesting a "centralised" location to implement CSS. I'm happy with this "decentralised" and "as-needed" approach of setting CSS ID/classes/custom code via the Elementor frontend editor. Just want to improve on this environment by having the aforementioned visual indicator implemented.

**Comment by rtpHarry** [comment]
I would like something like this as well, especially for when the Advanced > Custom CSS has been set as its easy to forget about or not know of, if you're working with others in a team.

Maybe this could be a debug toggle, which shows more if you want it to, and you can tick which elements are shown.

They would be shown as a row of badges in the corner of the widget, with the values in the tooltip, and clicking them would take you directly to the edit section for that property.

**Comment by nicholaszein** [comment]
Hello!

Thank you for sharing your ideas and for being so patient! 🙏 

### ✅ The feature you requested has already been available since version **2.6**.

Elementor offers many gems., and we don't expect every user to know them all. The feature you are talking about is called **`Navigator Indicators`**, and you can learn more about them [here](https://elementor.com/help/navigator-indicators/).

I'm closing this request as solved!

Kind regards
