### ISSUE TITLE
Custom Breakpoint not rendering correct css rules

### ISSUE THREAD

**Issue by choijun** [elementor/elementor#15782]
Hi guys,

Firstly I am sorry because English is not my mother language and I found the problem related to Custom breakpoint feature #15488. Below are details

What happens if the device value is `mobile_extra` and `tablet_extra` ?

https://github.com/elementor/elementor/blob/2b8fd80ba44de6a8ca7aa91f7317827d5f9ad60d/includes/stylesheet.php#L320

https://github.com/elementor/elementor/blob/2b8fd80ba44de6a8ca7aa91f7317827d5f9ad60d/assets/dev/js/editor/utils/stylesheet.js#L24

Here is how I solved it .

https://github.com/elementor/elementor/blob/722114bfac9809959fe2507351e7da0568f05a67/includes/stylesheet.php#L320

For the editor mode, I added the custom `split` javascript function and it will to similar with `explode` function of PHP

```
var customSplitFn = function( input, separator, limit ){
  input = input.split(separator);
  if (limit) {
    input = input.slice(0, limit - 1).concat(input.slice(limit - 1).join(separator));
  }
  return input;
}
```

and replace the line code `var queryParts = singleQuery.split( '_' ),` by `var queryParts = customSplitFn( singleQuery, '_', 2 ),` more detail on here https://github.com/choijun/elementor/blob/da5df17a27667702b0959c67c6905d0cd87b0122/assets/dev/js/editor/utils/stylesheet.js#L30

This should solve the issue  #15488

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.0

Feel free to update

Thanks!
