### ISSUE TITLE
Not the same original design

### ISSUE THREAD

**Issue by WealthVoyage** [elementor/elementor#15799]
I'm using the "Digital and Technology Design School "theme
and the " App Design Course  " page is not the same original page In the theme
I tried many ways to solve this problem but it does not solve

I uploaded the photo for issues in google drive please check the link
https://cutt.ly/kQiyuFF

please solve this problem ASAP I have to finish this today 

Best Regards

**Comment by WealthVoyage** [comment]
؟؟؟؟؟

**Comment by shilo-ey** [comment]
Please make sure you have:
1. Site identity set up
2. Menu set up
3. Default values

On the other hand you can try to re-import the Kit or the page specifically.

Thanks
