### ISSUE TITLE
Elementor Calendar, Event Popup Missing Close X

### ISSUE THREAD

**Issue by PetrusVermaak** [elementor/elementor#15790]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When you view a Elementor Google Calendar, and click on the event (https://prnt.sc/1gr5swk) it brings up a popup that can be closed with an X (https://prnt.sc/1gr4qiu)

However on mobile iPhone there is no X to close the popup: https://prnt.sc/1gr58ka

## Steps to reproduce
Install WordPress, Elementor & Elementor Pro. Add Google Calendar API and email address. Create the event in Google Calendar. View the calendar on mobile and click the event created. The popup will be missing the closing X.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hey @PetrusVermaak 

It seems like you are working with a 3rd party plugin, hence Elementor doesn't have this kind of capabilities.

I suggest you to contact your theme/plugin provider for this integration.

Cheers.

**Comment by PetrusVermaak** [comment]
@shilo-ey  You are right, the culprit is Happy Elementor. Live gets busy and we dropped the ball here... SORRY!!!!!!
