### ISSUE TITLE
Video background makes text flicker on chrome for android 

### ISSUE THREAD

**Issue by Deadlift79** [elementor/elementor#15825]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

From chrome for android latest versions (90+) I've noticed that using a video background section (placed above the fold) makes the text and the logo (presents on that page) flicker on page loading. 
It doesn't happen on every page load, only sometimes.
It happens on many chromium based browsers (but not on edge and Samsung Internet)
I've tried regenerating CSS, cleared any cache, changed Elementor CSS print method. Nothing helped. Tried also on another server.
Disabling all Elementor experiments doesn't change that behaviour.
Disabling latest chrome update solves the issue like of course disabling video background playback for mobile.
## Steps to reproduce

Simply use Hello theme and create a normal video background section giving some min height across devices. It happens only on mobile view. Could you please have a look?

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rami-elementor** [comment]
Hi @Deadlift79 

Thanks for reporting this bug, but it sounds like it's not an Elementor issue, rather than chrome for android.

**Comment by Deadlift79** [comment]
Hi Rami,

You can close. As you have said it was related to chromium based browsers and happened between 90 to 93 versions. Then it was solved.
Thank you
