### ISSUE TITLE
Elementor Pro Gallery widget breaks with Dynamic Tags

### ISSUE THREAD

**Issue by ultramizer** [elementor/elementor#15829]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When adding dynamic tags to a Elementor Pro Gallery widget, the widget settings can't be changed anymore once you select another widget and then back to the gallery. The widget panel is just blank. The widget also can't be deleted from the page anymore in the first two tries, only on the third try it is deleted correctly.

## Steps to reproduce

1. Drag Elementor Pro Gallery widget onto any page or template
2. Change settings as you need, no problems
3. As a file source, select a dynamic tag and choose any of the available, for ex. the "attached image of post".
4. You can then still change settings of the gallery widget or style and so on
5. Select anything else (widget, coloumn or section)
6. Select the gallery from the previous step again
7. Settings panel of gallery widget is completely blank. No settings or styles can be changed anymore. There is no recovery.
8. If you duplicate the broken widget, the duplicate shows the exact same behavior and can't be changed anymore as well.
9. If you try to delete the broken widget either from the pen right click menu or in the layer panel, it doesn't delete until the third try

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

[Pastebin](https://pastebin.com/4cAr4qA8)

</details>
<img width="301" alt="Bildschirmfoto 2021-07-30 um 10 58 11" src="https://user-images.githubusercontent.com/10888687/127628863-58d480b3-fbc8-49f5-b40b-c859f3324244.png">

**Comment by d19dotca** [comment]
This bug report should be closed in favour of the previously filed bug report at https://github.com/elementor/elementor/issues/15529. Please ensure you are searching prior to filing bug reports to avoid duplicates.

**Comment by DavidGMiles** [comment]
Previously reported - five weeks ago

**Comment by ultramizer** [comment]
Thanks for the info. Amazingly, i have spent 15 minutes searching on this git in the issues for "Gallery Dynamic" "Dynamic Gallery" "Dynamic Field Gallery" and haven't found the other issue, hence i opened a new one.
