### ISSUE TITLE
images include in template .json file in BASE64 form

### ISSUE THREAD

**Issue by talha-rafique** [elementor/elementor#15833]
when import template from elementor, it not included images used in that template,  either using localhost or livewebsite.

include images with templates via BASE64 technique in .json template fil.

**Comment by shilo-ey** [comment]
Hey @talha-rafique 

Thank you for your suggestion.

Elementor uses its Live images import mechanism to allow dynamic import of images from templates.

In addition, we want to keep the process of importing a Kit/Template as light as possible to avoid timeout errors, so even if your server disconnects - you will still have all of your structure.

We might incorporate this feature as an option in the future if we will see a large demand for it.

Thanks.
