### ISSUE TITLE
Can´t use Elementor

### ISSUE THREAD

**Issue by Hagamostuweb** [elementor/elementor#15836]
I have used Elementor for quite some time, but since a few days Elementor has not worked on my website. Everything looks fine when viewing my site, but I can't edit with Elementor in any way. I already have the latest version of WordPress, PHP, and Elementor, but it still doesn't work.

**Comment by DorShahar** [comment]
Hi @Hagamostuweb ,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
