### ISSUE TITLE
Please add the "3d shadow" feature to elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15834]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Describe the solution you'd like**
3d shadow is a great feature that unfortunately does not currently exist in elementor. We see an example of this type of shadow in the following figure : 
![box-shadow-3d-style](https://user-images.githubusercontent.com/77163248/127737533-957fe64b-d543-4602-b1ea-bef9bcca7368.png)
Please add this feature to elementor if possible. thank you

**Comment by sanjupanikkar** [comment]
Those aren't "3D" shadows. That effect can be achieved using box shadows with some position and transform tricks.

**Comment by 79ho3ein** [comment]
thank you @sanjupanikkar 
I did not know the exact name of these shadows. I inquired and found out that they are called 3d shadow.
In any case, we can not design such a thing in elementor ...

**Comment by sanjupanikkar** [comment]
Of course it would be nice if additional controls for box shadows were added to the Elementor UI. Anyway, I was going to link to a CSS codepen in my reply but I forgot, so here it is: https://codepen.io/haibnu/pen/FxGsI

**Comment by 79ho3ein** [comment]
Thanks, I hope to add...

**Comment by DorShahar** [comment]
Hi @79ho3ein 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
thank you
