### ISSUE TITLE
Display conditions in elementor (hide sections, widgets and various conditions)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#15832]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A very important feature that is not present in elementor is the display conditions. This feature has many uses that you are definitely aware of. Currently, a number of elementor add-ons have this feature. Such as power pack, element pack, elementor extras.
![Screenshot (102)](https://user-images.githubusercontent.com/88034902/127711694-f3f131d7-3077-41a4-8377-f960ac5e93b0.png)
**Does elementor have a plan to add this important feature?** In 2021 ?

More pictures of this feature : 
http://i.prntscr.com/zq43l54STjqb7pqJ3XdRKg.png
http://i.prntscr.com/UqmQLeLRS0q4x2xRwG7Dsg.png
http://i.prntscr.com/rDz0NPYtS4i6TF65iX_8qg.png
http://i.prntscr.com/M-1R0biJTWGGccJ65cj3bA.png
http://i.prntscr.com/rZHbYUVtSD__-jsaj_gOoQ.png
http://i.prntscr.com/Xz2fnpUFRjSYjMI84wCs1w.png

**Comment by 79ho3ein** [comment]
+1
This feature is great. Unfortunately, I am currently using the power pack plugin to meet this need, which is a very heavy plugin.
I hope elementor has a plan for that in 2021. The place of this feature is strongly empty in elementor.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
