### ISSUE TITLE
Icons do not fit exactly in the middle. (Slightly higher than usual)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15845]
hello
I have been working with elementor for almost 4 years, unfortunately there was a very annoying problem from the beginning and I do not know if a similar report has been given to you so far or not ...
The problem is that the symbols are not completely in the middle and have moved slightly upwards. Please see the image below :
![Screenshot (103)](https://user-images.githubusercontent.com/77163248/127769999-b522c895-e8dd-4e1c-8136-5c01d4ea8541.png)
As you can see in the figure above, the icon is tilted slightly upwards. This problem is clearly visible on the mobile phone, and the fact that the icon is not in the middle is easily visible and severely undermines the ui.
In the image below, you can see the Woodmart theme with the icon correctly in the middle.
![Screenshot (104)](https://user-images.githubusercontent.com/77163248/127770142-8c8d2bd8-99a9-4a68-a716-2391c68d7348.png)
Unfortunately this problem is present in all icons, even custom or SVG icons.
Please check this issue. It is very vital.

Thank you

**Comment by godvsgodvs** [comment]
Icons are treated like fonts and inherit the global typography css like line-height. Go to that icon's advanced settings, custom css and add this line:

selector {line-height: 0;}

That should do it.

**Comment by 79ho3ein** [comment]
thnak you @godvsgodvs 
It is true, But this is a problem anyway. I hope elementor has a way to solve it on a large scale. Because if the number of site icons is high, it will be a problem.

**Comment by godvsgodvs** [comment]
Not really. Use your site settings custom css and add this:

.elementor-icon-wrapper {line-height:0;}

This will affect all icons. Problem solved.

**Comment by 79ho3ein** [comment]
thank you my friend

**Comment by Metalmorph** [comment]
I didn't know about the line height. I was usually fixing it with:
SELECTOR .elementor-icon-wrapper{height:HEIGHT_OF_THE_ICON}

The line height one is much better, thank you :)
