### ISSUE TITLE
`onReady` is soft deprecated since 3.0.0 notice

### ISSUE THREAD

**Issue by cristian-ungureanu** [elementor/elementor#15854]
It seems like the `onReady` function is deprecated according to your [deprecation plan](https://developers.elementor.com/v3-0-planned-deprecations/). The error comes from `assets/dev/js/editor/controls/select2.js` in elementor so whenever a widget is using a control with `Controls_Manager::SELECT2` type the deprecation notice will appear in the console.
I checked the [elementor controls](https://developers.elementor.com/elementor-controls/) documentation and it says nothing about deprecating the SELECT2 control.
My question is: will you fix the control or should I replace it in my custom widget with a simple SELECT?

**Comment by udidol** [comment]
Hi @cristian-ungureanu,
You can still use the Select2 control. The deprecation notice you see is a soft deprecation, notifying that Elementor will no longer be using the `onReady()` method in any control JS handlers.
We will be removing the `onReady()` usage in the Select2 widget in an upcoming version.

**Comment by udidol** [comment]
@tleifj 
Hi, the deprecated `onReady` is only the `onReady` method in the Select2 control.
If you are using it in a custom control, there should be no problem with that.
I do concede that the deprecation message should definitely have been more clear.

**Comment by tleifj** [comment]
Great. Thanks @udidol!
