### ISSUE TITLE
✅ 🚀 Call to action widget add new options (have screenshots) 

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15851]
Hello 

1) Add button position for image, when I have text top and image bottom (this option is good for mobile design when we need to make text first) 
![12](https://user-images.githubusercontent.com/66754335/127786404-af094228-4b07-40f3-af41-089d42b32a4d.jpg)

2) Add ID for button for better website analytics 
![13](https://user-images.githubusercontent.com/66754335/127786422-44d2dc92-158c-4126-b808-e186e1079a69.jpg)

3) Add responsive option for alignment content
![14](https://user-images.githubusercontent.com/66754335/127786431-00fb592a-4c46-491f-9cb8-a8b3b22e24da.jpg)

For what need to add this option? These options will improve the experience of the layout of a website with a Z pattern, which will save a lot of code and give better optimization for the website

**Comment by promocot** [comment]
and please FIX hover effect option, if I disable it, he work, if I set color transparent I disable all hover effect, please make this if I disable, I disable total hover effect

**Comment by promocot** [comment]
4) add alignment for the button, in the mobile version I cannot set full-size button
![15](https://user-images.githubusercontent.com/66754335/127786788-17594e42-ad62-401c-8f11-2a6490e68686.jpg)

**Comment by promocot** [comment]
5) add padding for title and description
![16](https://user-images.githubusercontent.com/66754335/127786973-3f5012eb-8b1f-46d2-8abe-c7b759dd120e.jpg)

for what? Padding can work like custom width in positioning for a text editor for example if I have text block and his looks better when having 380px width, now I need to add custom CSS

**Comment by promocot** [comment]
please fix the bug - the button doesn't have global option for the button, I must set this in style options

**Comment by promocot** [comment]
All these options will allow you to refuse the layout in 2 columns, which reduces the amount of code by 16 lines every time we would need to use the image, title, text, and button widget, and here we save the code not only from fewer widgets but also columns

**Comment by sanjupanikkar** [comment]
Great suggestions.

I would also suggest adding responsive control to the Call To Action image, as seen for section background images:
![elementor_responsive_image_controls](https://user-images.githubusercontent.com/72470487/127808242-cd46c367-e99b-4d5c-aa3b-0af827bca9c1.jpg)

**Comment by promocot** [comment]
> Great suggestions.
> 
> I would also suggest adding responsive control to the Call To Action image, as seen for section background images:
> ![elementor_responsive_image_controls](https://user-images.githubusercontent.com/72470487/127808242-cd46c367-e99b-4d5c-aa3b-0af827bca9c1.jpg)

yeah is a good idea, I think it will be also the ability to adjust the width of the area for example 70/30% or another value, by default we have only 50/50%

**Comment by promocot** [comment]
finally, for the perfect widget, add options for the second button, for example, I need to add a play button with popup with video presentation, or I need two options and I want to make one CTA button... all these changes will create the perfect widget that can save a lot of code, in your videos you yourself showed how it can do it, and now imagine how these add-ons will make it even better

**Comment by nicholaszein** [comment]
Hello there @promocot!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.23.0! 🥳 

You can now change the position of the Call To Action image to appear below the content.

As for the other request, since you submitted your request, we have changed the way we track and prioritize requests, and we can no longer track multiple requests per submission. If you think the other options are still valid, please [submit new Feature Requests](https://elemn.to/gh-new-feature-request) for each option (separately), so we can track them better and watch for community engagement.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
