### ISSUE TITLE
⚠️ Support Request: How to change Form Submission exported CSV delimiter?

### ISSUE THREAD

**Issue by shaktimanpurush** [elementor/elementor#15858]
hi,

When using ELementor Pro form submissions, the CSV export uses a COMMA as field separator:

`field1,fiels2,field3`

How can I make this CSV export use COMMA-POINT as a field separator ?
`
field1;fiels2;field3`

Thanks

**Comment by nicholaszein** [comment]
Hello @shaktimanpurush,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

After a quick Google search I found the following article:

https://www.ablebits.com/office-addins-blog/change-excel-csv-delimiter/

Try to follow the article to change the delimiter of your CSV files.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
