### ISSUE TITLE
Thanks page in elementor theme builder. (Request a new feature)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15862]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

**Request Description :**
Since elementor is making a big change in its WooCommerce division in 2021, Adding a "Thanks page" design feature can be great and important.
Such as 404 page design, single page, etc. in elementor theme builder...
This feature is currently available in the jet woobuilder plugin, but it is better to localize it in elementor.
Please consider this.

thank you

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
