### ISSUE TITLE
Elementor Overview widget in WordPress Dashboard has very outdated "News & Updates" links

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#15869]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I'm guessing the Elementor team is already aware of this, but I didn't see this raised yet so am filing it here for an official report... the Elementor Overview widget on WordPress Dashboard has very old "News & Updates" section links. It hasn't been updated since Elementor 3.1 was released, it seems. I used to use this to quickly be aware of new blog posts on Elementor.com, but it's not quite working as expected now. 

I'd like to see this either fixed or outright removed as its content is no longer relevant if it isn't updating correctly, particularly after this many months now.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/8153796/127941941-1509c1ec-0fac-4796-ac97-306b221b5540.png">

## Steps to reproduce
1. Add the Elementor Overview widget to the Dashboard in WordPress
2. See if the News & Updates section looks current or not. If it's like mine, it will be way out of date.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Elementor 3.3.1 & Elementor Pro 3.3.4

**Comment by shilo-ey** [comment]
Thank you @d19dotca 

We are aware of this issue and working on resolving it (no version update needed)

I merged this issue with #15809 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by d19dotca** [comment]
Ah my mistake. I didn't catch that other one because I was specifically searching for "Elementor Overview" and nothing related was returned. Thanks for merging this with the other one.
