### ISSUE TITLE
Widescreen breakpoint tooltip is wrong

### ISSUE THREAD

**Issue by paulherzlich** [elementor/elementor#15866]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

The tooltip for the widescreen breakpoint in the responsive top bar wrongly explains that the breakpoint applies to screen widths lower; it should say higher
## Steps to reproduce

Add the Widescreen breakpoint 
Hover the mouse over the breakpoint

The message you see says: :"Settings added to Widescreen device will apply to 2400px screens and down"
The word "down" should be "up"

<img width="203" alt="Screenshot 2021-08-02 at 21 36 46" src="https://user-images.githubusercontent.com/7724692/127915816-dab98eed-56e8-4ba8-8431-3eb50177d85b.png">

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by 79ho3ein** [comment]
Please report this in your issue (# 15797)

**Comment by shilo-ey** [comment]
Thanks,

This issue was already fixed in beta 3

Next time please send us your input in the beta thread as @79ho3ein mentioned.

Cheers.
