### ISSUE TITLE
How can we remove all the Suggested youtube video at the end of every video that we uploaded in the page..?

### ISSUE THREAD

**Issue by linkanandco** [elementor/elementor#15871]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by linkanandco** [comment]
https://www.loom.com/share/e8d38506488144d3af7c26a39ea5a037

**Comment by d19dotca** [comment]
The repo on GitHub is for reporting defects/bugs and feature requests, not for seeking help. Your question would be better served by the Elementor Support team or posting on the new Elementor Hub (forum.elementor.com).

**Comment by rami-elementor** [comment]
Hi @linkanandco,

Elementor offers only two options for "Suggested Videos": Current Video Channel, Any Video.

Currently, you can't hide the suggested videos.
