### ISSUE TITLE
How To Change Wordpress Theme Without Breaking Website 

### ISSUE THREAD

**Issue by shawlworld** [elementor/elementor#15885]
Hi there, 

I want to delete astra+elementor pro and install flatsome ecommerce theme successfully. Can anybody advise me how to do that without breaking the website? 

thank you in advance.

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
