### ISSUE TITLE
Custom Code - minify and strip comments

### ISSUE THREAD

**Issue by JennyPower** [elementor/elementor#15890]
With the new custom code section under the Elementor menu, the code isn't minified (even though the asset loading experiment is on). Not a problem if you utilise a caching solution, but would assist performance for a lot of users.

Or as a minimum include a field in the editor for comments so that comments aren't passed to the browser

**Comment by rami-elementor** [comment]
Hi @JennyPower 

We have reviewed your request again and at this point this feature is not part of our roadmap.

Meanwhile you can use online minifying tools - https://www.google.com/search?q=minify+code+online

Thank you.
