### ISSUE TITLE
Add styling options for the WooCommerce "added to cart"-notification (and others)

### ISSUE THREAD

**Issue by Xpressprint** [elementor/elementor#15896]
Possible duplicate requesting similar change as a pop-up: https://github.com/elementor/elementor/issues/15186
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I create and customize WooCommerce shops using Elementor for a living. Elementor works great with WooCommerce, but the MAIN weakness in my opinion is the "added to cart" notification. Look at ANY Elementor theme demo using WooCommerce, and add a product to the cart. No matter how pretty the theme, 99% of the time, you will see the same ugly notification below the header, spanning the entire screen width and pushing down the content of the page. In most cases it will not keep the same width or padding/margins as the content. In every WooCommerce store, this is a part that is designed to be noticed by the user. So please, Elementor team, lets make it as pretty as we now can make every other part of the shopping experience using Elementor and Elementor Pro. Thank you.

**Describe the solution you'd like**
Ability to easily edit the "added to cart" notifications visual appearance, such as font and color, and equally important, the with/margins/padding. In a perfect world, I would love to be able to select between an inline render or a pop-up message, dismissible.

**Describe alternatives you've considered**
Custom CSS styling for each new theme, a lot of work.

**Additional context**
Attaching a screenshot of a pretty Elementor theme, showing a notification that does not match at all. Typical for this, see any theme demo.

![Screen Shot 2021-08-05 at 10 12 50](https://user-images.githubusercontent.com/26872809/128317796-3114f12d-147a-42d2-933b-b7da667d72ff.png)

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
