### ISSUE TITLE
Section height (fit to screen) only works properly on tablet and desktop and does not work on mobile.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15898]
hello elementor team...

This problem existed in the beginning and is not related to recent versions. As I said in the title of this issue, the problem is that if we set the section height to fit to screen, it only works properly on the desktop and tablet. But it does not work on mobile phones.

For a better understanding, please see the pictures below. 

in desktop :
![Screenshot (108)](https://user-images.githubusercontent.com/77163248/128343763-7a533cb3-9fd5-45a4-bbd6-f295133d8fd5.png)

in tablet :
![Screenshot (109)](https://user-images.githubusercontent.com/77163248/128343961-3e512de0-91a1-4f0a-90e2-81fcdf8ae05e.png)

in mobile :
![Screenshot (110)](https://user-images.githubusercontent.com/77163248/128344321-b14c144b-2e9a-4cfe-9887-739b58559a45.png)

As you can see in the pictures above, the fit to screen height does not apply to the mobile phone.  Please check it.

Thank you

**Comment by Michaelgimii** [comment]
That's right- this is a problem for me too. I hope it will be resolved soon. I need it a lot.

**Comment by iqbalmauludy** [comment]
Hi, you can use 100vh. That will be same like 'fit to screen' too.

**Comment by 79ho3ein** [comment]
hi @iqbalmauludy
True, but still different from "fit to screen".
