### ISSUE TITLE
Related Products is broken in Hello! Elementor Theme

### ISSUE THREAD

**Issue by Rubanho** [elementor/elementor#15905]
- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

Hello,

I'm using the newest version of Elementor Pro and have the Hello! Elementor theme installed (Also newest version).
Somehow the 'Related Products' section on the product page is broken. It shows the image really huge and only 1 product per column, while my settings are 4 colums. Also, I didn't do any updates, nor on the theme or on any plug-in. Last weekend everything was looking fine. I went away for vacation a couple of days and now the section is broken. 

Does anyone know how I can fix this?

**Comment by PolarEndTech** [comment]
Hello.

I would like to confirm we have the same on our sites. For now we rolled back to 3.3.0. When I get time, I will roll forward or live with whatever it was that was broken in that older version, if it is less a problem.

**Comment by AkramiPro** [comment]
same problem i have in my website. show one column except  4.

**Comment by avivu** [comment]
Hello @Rubanho, @PolarEndTech, and @AkramiPro 

To deal with it more efficiently, I merged this issue with #15857, which is on the same subject. 
Please feel free to continue the conversation there. 

We are aware of the issues and will release a fix in the next version.

Thanks for your feedback!

**Comment by ppwebox** [comment]
I have exactly the same issue even with newest Elementor Pro 3.7.1 and the Related Products widget.

Initially I had a different theme (Blocksy) installed when creating the Single Product Archive template , which includes a section of the Related Products widget, and everything was fine. Then  I switched theme to "Hello" from Elementor, which ironically broke the Related Products rendering. 

So this bug is still not properly fixed!

**Comment by ppwebox** [comment]
And possibly related: the quantity plus and minus signs aside the cart buttons simply disappeared. I now have to use a plugin to regain quantity selection. Such bugs simply should not occur with an inherited Elementor theme like Hello.

**Comment by SieBer15** [comment]
+1
Very strange this has not been fixed yet.

**Comment by ppwebox** [comment]
I guess that's what you get when using a free theme from a commercial WP page builder developer. No money to be made so no budget allocation for further development. And the bugs begin to pile up until complete uselessness. 

In any case, I won't be making that mistake again for customer sites... ;)
