### ISSUE TITLE
Hello! .... I just set up my website and my homepage on mobile seems to be different from PC.... Any help

### ISSUE THREAD

**Issue by osafodaniel** [elementor/elementor#15901]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by d19dotca** [comment]
You didn't mention if you did any mobile-specific optimizations. Typically - for most websites - you can't make a desktop website and expect no changes to mobile. 

I'd recommend you following the product documentation: https://elementor.com/help/mobile-editing/
