### ISSUE TITLE
Add % units for column width (better optimization for DOM)

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#15917]
Hello, for better design and responsive layout I must add padding in px or for flexibility %, but this creates a bunch of code since I need to use this property for each column, however, if I set 80% for the width of the container, all my columns will have a single indentation without additional code for each column, which simplifies work and reduces the amount of code, which gives better optimization. I verify this theory with custom code and have better optimization of code with standard padding I have 16 kb of code, if I try my solution I have 11 kb 68% less code.

**Comment by shilo-ey** [comment]
This feature is implemented in the next-gen Container element.

Feel free to try it out in the dev edition.

Thanks!
