### ISSUE TITLE
Related Product Grid - Displays 1 Columns When Set to 4

### ISSUE THREAD

**Issue by AkramiPro** [elementor/elementor#15914]
in RTL version columns are not effected . and there is just one column . a chose 4 columns but only 1 one column show . 
the problem is in this file : 
elementor-pro/assets/css/frontend-lite-rtl.min.css
it's broken in new pro version (3.3+)

**Comment by shilo-ey** [comment]
I merged this issue with #15857, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
