### ISSUE TITLE
elementor do not work on dooplay theme I changed the color on the page but doesn't changed

### ISSUE THREAD

**Issue by awaisarain-marker** [elementor/elementor#15948]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by awaisarain-marker** [comment]
please do something about the dooplay theme

**Comment by shilo-ey** [comment]
Hi @awaisarain-marker 

Thank you for contacting us.

Elementor plays along properly will all compatible themes. 
Full compatibility includes the proper use of [Elementor’s Theme Locations API](https://developers.elementor.com/theme-locations-api/) and adherence to the WordPress Codex coding standards.

Please contact this theme author for better support.

Thank you
