### ISSUE TITLE
A little bug in your 'Number Control' documentation page.

### ISSUE THREAD

**Issue by hasanfardous** [elementor/elementor#15954]
Hello there,
I am happy to inform you for a little bug/mistype here for first time. Basically, I am a developer and using the Elementor page builder regularly for a long time.

Today, I can see a little bug/mistype in your 'Number Control' documentation page. The page is here https://developers.elementor.com/number-control. In the 'Arguments' table to the 8th row the 'mix' should be changed to 'max'. I hope this is a type error mistakenly.

Thanks & Regards
Md Hasan Fardous

**Comment by rami-elementor** [comment]
Thank you for reporting.

The typo was already fixed.

New Number control page: https://developers.elementor.com/docs/editor-controls/control-number/

**Comment by hasanfardous** [comment]
Thanks for the update.
