### ISSUE TITLE
Good morning. My name is Alberto Rosado and I am a new user. my web should be rosadocanread.com but it says http://gator3095.temp.domains/~rosadead/. I would like to know what happened and how can I fix it? Thank you. Alberto Rosado e-mail rosadoalbe@gmail.com

### ISSUE THREAD

**Issue by rosadoalberto** [elementor/elementor#15978]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by d19dotca** [comment]
This is not the appropriate place for support, you will need to contact the [Elementor Support team](https://elementor.com/support/) if you wish for product support. However, what you're reporting seems to be a hosting issue with HostGator, doesn't sound like an Elementor issue at all.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
