### ISSUE TITLE
Suggestions for the checkout page editing feature in 2021 updates.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15990]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello @avivu
We all know that elementor has decided to add the ability to edit the payment page in 2021 ... I have two suggestions for this feature, I hope it will be useful in developing this feature.
I am currently using the jet woobuilder plugin to edit the payment page, which has two very important features that I will explain to you. I hope elementor also benefits from it.

1- **Ability to fully edit the coupon section on the payment page :**  In this feature, we can customize the coupon section of the payment page. Just like a form. That's great...
![Screenshot (117)](https://user-images.githubusercontent.com/77163248/129487755-2a6e0784-bbff-4766-96d0-75ee96017db2.png)

2- **It is possible to completely edit the WooCommerce checkout fields :** This is extremely important. Please pay attention to it ...
The ability to edit payment fields allows us to customize WooCommerce checkout fields. Features such as **deleting or adding fields, determining whether they are necessary or not, the width of each field (to specify single column or double column)**
And other things that you are definitely aware of. If you add this feature, you will eliminate the need for your users to use a plugin. (WooCommerce checkout Fields Editing Plugin)
**This feature has been added to the latest version of the jer woobuilder plugin, the image of which you can see below.**
![Screenshot (119)](https://user-images.githubusercontent.com/77163248/129488046-84f66bd4-0000-4e60-b563-7a3ce3c83037.png)
The next thing that is very important in this feature is the possibility of complete personalization of list fields such as city, country or province. (The image below)
![Screenshot (120)](https://user-images.githubusercontent.com/77163248/129488188-16e9a01c-feb0-4897-acae-9c30cc790fcd.png)

But there are two very important points about this feature that I suggest you pay attention to.

1- **In editing the payment field, if we assign the sale to a specific country (from within the WooCommerce configuration), calculating the shipping cost on the mobile phone will encounter an error. We must delete the country field using the code to avoid any problems ( display: none)**

2- Unfortunately in the hello elementor theme, selected fields such as country, province or city have no style. Text fields such as name, contact number, company name, etc. are customized correctly, but list fields, such as city and province, are very disappointing. To solve this problem, it is better to add settings, so that we can style the list fields separately from the text fields such as name, contact number, etc.  **In the image below, it is clear that the text fields are styled correctly. But the list fields ....**
![Screenshot (120)](https://user-images.githubusercontent.com/77163248/129488474-6c65f834-6e1b-44ae-8ef6-9069ba038997.png)
**But in Woodmart, we see that the list fields are properly styled...**
![Screenshot (121)](https://user-images.githubusercontent.com/77163248/129488525-7dcd4a6d-8fa6-46e2-af4f-e6c8ede22e14.png)

I apologize for making this request too long.Because I needed to share the details with you so that no problem would arise later. I have reviewed all these cases beforehand and I am aware of all the problems.

I wish the elementor team success...

**Comment by paauserrat** [comment]
I found your suggestions important. I'm looking forward to see them implemented! In my opinion, the most important thing is ability to edit every woocommerce page with drag and drop elementor. The checkout fields are important too

**Comment by 79ho3ein** [comment]
thank you @paauserrat , Yes, exactly. That's great. **Of course, two other things can be important for the payment page ...**

1- Ability to multi-step checkout form. Just like the elementor form widget.
2- Add a Google Map widget to the checkout page :  Using this widget, the user determines his exact address on the map. And the address that the user has specified on the map is automatically placed in the address field. No need for the user to type in their address.

I hope elementor considers these.

**Comment by avivu** [comment]
Hello @79ho3ein,
Let me start by thanking you for taking the time and preparing these requests for the checkout page.
We are welcoming suggestions from the community, and it׳s part of our process in creating new features.

We'll consider all of your suggestions and check how we can incorporate them in the new Checkout widget. I can't promise to address all of the requests at the first phase, but I believe you will be satisfied when released. I can ensure you we are focusing on style and layout customization. 

Again, thank you!

**Comment by 79ho3ein** [comment]
Thank you for your efforts @avivu. Good luck🌹

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!
