### ISSUE TITLE
A small bug in the new version of elementor... please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15999]
hello
Thanks to the elementor team for the new update.
After the official update, I encountered a problem that I did not notice in the beta...

The problem is that if the title widget has a link, its color gets out of control. Please see the image below :
![Screenshot (125)](https://user-images.githubusercontent.com/77163248/129587984-995052ef-1e8c-4b69-89a6-e1a8f9d9c9d9.png)
Actually, I left this text white, but on the website, the color of the text is like the image above. When editing the color of the text is white. But on the website this problem shows itself.
**This problem only exists in the title widget.**

Finally, I emphasize that this problem arises when the title widget has a link. thank you

**Comment by DorShahar** [comment]
Hi @79ho3ein 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by 79ho3ein** [comment]
hi @DorShahar
May you do not close issues quickly? Our conversation always remains unfinished and the issue remains incomplete forever ...

**This bug occurs in the following conditions for the title widget :**
1- The widget text have a link.
2- option Improved CSS Loading is enabled.

In fact, the problem is with activating the Improved CSS Loading option. Definitely did not enable this option when you tested.

Please review again and reopen the request if the problem is confirmed. thank you

**Comment by 79ho3ein** [comment]
To expedite the problem-solving process, I stated this request in a new issue in more detail.

thank you
