### ISSUE TITLE
Being able to separate mobile and desktop templates with elementor

### ISSUE THREAD

**Issue by ardalan13** [elementor/elementor#16005]
To better display the site on mobile and optimize the speed and volume of the page for mobile in order to improve the side in the first mobile algorithm, I suggest adding a feature so that a separation template can be designed for mobile.
When the site is opened on mobile, it is detected by JavaScript and a different template with the same page address is opened.
In this case, mobile and desktop templates can be completely different and optimal.
Thank you for your support.
Ardalan Davoudi - SEO specialist

**Comment by shilo-ey** [comment]
Hi @ardalan13 
Thanks for your feedback.

Elementor provides a powerful responsive editing capabilities, and not mobile/desktop versions.

I'm sure that you can find a separate solution for loading templates/posts based on user agent.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
