### ISSUE TITLE
✔️ 🚀 Feature Request: Lazyload background images just like other images

### ISSUE THREAD

**Issue by yorkfrog** [elementor/elementor#16000]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm trying to make my page loading as fast as possible and background images are the only thing I can't force to lazyload - this impacts google PSI score significantly.  This impacts user experience, client google rankings and fits with E's current push on improving performance.

**Describe the solution you'd like**
I would like background images, added by Elementor as CSS url(..)'s, to be lazyloaded either as default or as an option on the background properties config in the editor.  I would like this to work for all image format (jpg, webp, png etc) as well as SVG files.

I reckon for pages with a few bk images below the fold, this would be low hanging fruit to improve page load performance.

**Describe alternatives you've considered**
There are some scripts out there and plugins, but often they don't play nice with Elementor.
I got this simple plugin to work for section backgrounds, but seems to be problematic for many other people and not supported on current WP : https://wordpress.org/plugins/lazy-load-background-images-for-elementor/

**Additional context**
This post suggests a possible alt to above plugin: https://wordpress.org/support/topic/now-working-on-my-site/#post-13598327

This is also related in ways to  https://github.com/elementor/elementor/issues/6778 (Background image size selection) as the addition of responsive backgrounds and lazyloading would slash page loading times.

**Comment by DavidGMiles** [comment]
You'd be worthwhile having a look at e-Addons for the now - they have both of these features in their addon pack

Background Image Sizes - https://e-addons.com/elementor/background-image-sizes/
Background Lazy Load - https://e-addons.com/elementor/background-lazyload/

They have the optimal way of doing both of these additions - as you don't want above the fold images lazy-loading

**Comment by nicholaszein** [comment]
Hi, there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.10**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
