### ISSUE TITLE
Autoplay not working for Vimeo videos in Lightbox

### ISSUE THREAD

**Issue by hybridvision** [elementor/elementor#16008]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The iframe URL generated for Vimeo videos that load in the lightbox is incorrect, which breaks the autoplay functionality.

I isolated this behaviour with the latest WordPress (5.8) and Elementor (3.4.0) running on the default theme and with no other plugins. The video loads correctly in the iframe inside the lightbox modal but it doesn't autoplay.

Examining the iframe URL generated, I see the following:

```
https://player.vimeo.com/video/235215203?color&autopause=0&loop=0&muted=0&title=0&portrait=0&byline=0#t=&autoplay=1
```

Note the `#t=` in the URL above is in the wrong position - it should be at the end of the URL, after `autoplay=1`.

## Steps to reproduce

1. Make a new Elementor page and insert a Video widget onto the page.
2. Select "Vimeo" as the source and set following settings: <br>
![image](https://user-images.githubusercontent.com/11492432/129712193-0a37b091-1f21-46e0-8008-1f5eda2e7c80.png)
3. Set Image Overlay and activate Lightbox: <br>
![image](https://user-images.githubusercontent.com/11492432/129712285-75acc0eb-1397-416c-bf96-8d261b033e11.png)
4. Save the page and see that clicking on the image overlay opens the video in the Lightbox but it fails to autoplay.

Related code: https://github.com/elementor/elementor/blob/v3.4.0/assets/dev/js/frontend/handlers/video.js#L68

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info (local development environment listed but this behaviour also exists on production server</summary>

```
					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.19.0
	MySQL version: Homebrew v5.7.32
	PHP Version: 7.4.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: [redacted]
	Home URL: [redacted]
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.4.0
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	

== Elements Usage ==
	
	wp-page : 2
		image : 2
		text-editor : 1
		video : 2


== Log ==
	
Log: showing 7 of 72021-08-17 09:47:59 [info] elementor::elementor_updater Started 
2021-08-17 09:47:59 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 09:47:59 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-17 09:47:59 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-08-17 09:47:59 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-08-17 09:47:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.4.0',
)]
2021-08-17 09:47:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.4.0',
)]

```

</details>

**Comment by ofmarconi** [comment]
@rami-elementor 
It still doesn't work, see: https://vapordigital.com.br/

Or here:https://vapordigital.com.br/#:~:text=Bem%20Fixa,Viva%20Utile

**Comment by ofmarconi** [comment]
I tested it in Firefox, it works so the problem is adapting it to chrome.

I didn't do any fixes I just updated Elementor, but it doesn't work in my chrome.

**Comment by cognitivefilms** [comment]
I am also having trouble getting this to work properly.  I tried using the direct video file links via Vimeo from a button link trigger. This solved the autoplay issue but I have lost all of the video controls.  https://www.cognitivefilms.com/

**Comment by ljakievu** [comment]
@cognitivefilms I checked your site and it seems like you made it work with a player control!
 Would you mind sharing how did you pull the direct link and make the control appears? 
 I ran into the same issue as well. 
 Thank you

**Comment by aebs90** [comment]
Hi @nicholaszein,

The vimeo videos are still failing to autoplay when using the **Video widget + Image Overlay → Lightbox** option.

I see that @cognitivefilms was able to solve it on his site, but it was using a Popup, not the Video widget.

Could you please reopen this ticket as this is still a bug on version 3.30.2 (Free) + 3.30.0 (Pro).
