### ISSUE TITLE
Custom code (pro) doesnt work

### ISSUE THREAD

**Issue by Zeitli** [elementor/elementor#16016]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Zeitli** [comment]
We have a retirement calculator (based on javascript, php, html/css) that we wanted to add as custom code but it doesnt work. 
![calculator design](https://user-images.githubusercontent.com/89038522/129737567-9d2c1e7f-8939-4640-b976-3e4c9c60ab8a.JPG)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
