### ISSUE TITLE
Popup on scroll to element trigger breaks content

### ISSUE THREAD

**Issue by tissi-2** [elementor/elementor#16018]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When activating the on scroll to element trigger in conjunction with an id or class, part of the popup content (in my case a youtube video) will not show up and some following content that does not belong to the popup is missing, too.

## Steps to reproduce

1. create a popup with a video widget/youtube video
2. set the conditions to a single site
3. set the on scroll to element trigger to an id or class
4. activate show on devices to desktop / tablet / mobile
5. activate show on browsers to all browsers

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== WordPress Environment ==
	Version: 5.8
	Site URL: https://www.hh-film.de/helge2
	Home URL: https://www.hh-film.de
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.0.4
	Author: Tom Usborne
	Child Theme: No

== Active Plugins ==
	Complianz | GDPR/CCPA Cookie Consent
		Version: 5.2.6
		Author: Really Simple Plugins

	Elementor
		Version: 3.4.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com	
</details>

**Comment by DorShahar** [comment]
Hi @tissi-2 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
