### ISSUE TITLE
Show/Hide based on Dynamic Tags

### ISSUE THREAD

**Issue by benjaminmead** [elementor/elementor#16027]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
With the Pro Theme Builder, there is the opportunity to create layouts for custom post types etc. However, there is no way to show/hide different elements dynamically based on things such as user role.

**Describe the solution you'd like**
It would be great if we could set conditions for blocks to be displayed. Example: SHOW/HIDE <block> IF value of DynamicTag1 CONTAINS/DOES NOT CONTAIN value of DynamicTag2.

**Describe alternatives you've considered**
There are external plugins that do this which are low quality / may be prone to security issues.

**Additional context**
Nil.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
