### ISSUE TITLE
Elementor 3.4.0 and Additional Custom Breakpoints breaks Global Font Sizes

### ISSUE THREAD

**Issue by juliewiens** [elementor/elementor#16033]
## Prerequisites

- [x]  I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating to Elementor 3.4.0 and activating Additional Custom Breakpoints, the global fonts don't work properly. In the Elementor editor, they are shown correctly, but on the live site, it only displays the desktop or biggest font size and doesn't show the saved smaller font-sizes as the screen size changes. If you turn off the Additional Custom Breakpoints altogether (not just disable certain ones) the global font settings and sizes set for the smaller screen sizes work again. 

## Isolating the problem

- [x]  This bug happens with only Elementor plugin active (and Elementor Pro).
- [x]  This bug happens with a default WordPress theme active.
- [x]  I can reproduce this bug consistently using the steps above.

## Environment

Wordpress 5.8
Elementor 3.4.0
Elementor 3.3.7

<details>
					
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.11
	PHP Version: 8.0.6
	PHP Max Input Vars: 3000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://test.sicher-starten.de
	Home URL: https://test.sicher-starten.de
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.4.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 2
		icon : 2
		text-editor : 6
	header : 2
		button : 1
		icon : 1
		nav-menu : 1
		theme-site-logo : 2
	page : 2
		form : 1
		heading : 2
		spacer : 4
		text-editor : 6
	popup : 2
		heading : 2
		image : 2
		text-editor : 2
	section : 3
		divider : 3
		heading : 49
		icon-list : 10
		image : 2
		text-editor : 46
	wp-page : 3
		divider : 1
		heading : 40
		image : 2
		text-editor : 32
	error-404 : 1
		button : 1
		heading : 1

== Log ==
	

</details>

**Comment by shilo-ey** [comment]
Hi @juliewiens 
Thanks for reporting,

Can you please share the steps to reproduce this issue?

Thanks

**Comment by juliewiens** [comment]
This problem still persists in 3.4.1.

Steps to Reproduce:

1. Install Elementor 3.4
2. activate Additional Custom Breakpoints, it doesn't matter how many of the breakpoints are actually used
3. In the Elementor Website Settings. create a global font style with different sizes for the different breakpoints. for example Desktop and Mobile
3. On your site, create a headline and assign the global font style to it
4. In the Elementor editor, everything appears normal but on the actual live site the global styles don't change according to the various breakpoints. 

The problem only pertains to text styled with global fonts, not other normally created text styles. 

I attached some screenshots of the problem. 

![Image1](https://test.sicher-starten.de/images/1.jpg)![Image2](https://test.sicher-starten.de/images/2.jpg)
![Image4](https://test.sicher-starten.de/images/4.jpg)
![Image3](https://test.sicher-starten.de/images/3.jpg)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.2

Feel free to update

Thanks!
