### ISSUE TITLE
Price Table Wiget Breaks With Font Awesome Invline SVG Experiment Active

### ISSUE THREAD

**Issue by MyListingClub** [elementor/elementor#16045]
Elementor v 3.4.1
Elementor Pro v 3.3.7

Please[ see this video](https://cloud.mylisting.club/jo5F06V) showing the issue.

Thank you,
Ryan

**Comment by shilo-ey** [comment]
Hi @MyListingClub 

Thanks for reporting.

Please share an example for a live website for better debugging.

This report is missing key information: 

* Steps to replicate
* Isolating the problem
* System info

Without it we simply can't help.

Thanks.

**Comment by MyListingClub** [comment]
**- Steps to replicate:** Already shown in the video.Toggle ON the Font-Awesome Inline Experiment.
**- Isolating the problem:** Hello theme. Only E and E Pro active.
**- System info:**  Attached


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.10
	MySQL version: mariadb.org binary distribution v10.5.10
	PHP Version: 7.4.22
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://staging-mylistingclub.kinsta.cloud
	Home URL: https://staging-mylistingclub.kinsta.cloud
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.6.8
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73

== Active Plugins ==
	AffiliateWP
		Version: 2.7.4
		Author: Sandhills Development, LLC

	AffiliateWP - Affiliate Portal
		Version: 1.0.8
		Author: Sandhills Development, LLC

	AffiliateWP - Recurring Referrals
		Version: 1.8
		Author: Sandhills Development, LLC

	Elementor
		Version: 3.4.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com

	Free Downloads WooCommerce Pro
		Version: 3.3.30
		Author: Square One Media

	JetSearch For Elementor
		Version: 2.1.14
		Author: Crocoblock

	Loco Translate
		Version: 2.5.3
		Author: Tim Whitlock

	Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue
		Version: 3.1.15
		Author: Sendinblue

	Perfmatters
		Version: 1.7.5
		Author: forgemedia

	RafflePress Pro
		Version: 1.8.4
		Author: RafflePress

	SEOPress
		Version: 5.0.4
		Author: SEOPress

	SEOPress PRO
		Version: 5.0.4
		Author: SEOPress

	Simple Feature Requests Pro
		Version: 2.2.1
		Author: Spellhammer

	WooCommerce
		Version: 5.6.0
		Author: Automattic

	WooCommerce API Manager
		Version: 2.3.10
		Author: Todd Lahman LLC

	WooCommerce Memberships
		Version: 1.22.4
		Author: SkyVerge

	WooCommerce Stripe Gateway
		Version: 5.4.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 3.1.4
		Author: WooCommerce

	WPCodeBox
		Version: 1.1.8
		Author: WPCodeBox

	WP Rocket
		Version: 3.9.1.1
		Author: WP Media


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 2.3.2
		Author: Kinsta Team

	Perfmatters MU
		Version: 1.7.5
		Author: forgemedia


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetSearch For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetSearch For Elementor: Compatible

== Elements Usage ==
	
	header : 3
		button : 3
		heading : 2
		image : 3
	page : 7
		accordion : 2
		button : 5
		call-to-action : 65
		global : 3
		heading : 39
		image : 2
		jet-ajax-search : 1
		reviews : 11
		text-editor : 24
		woocommerce-products : 1
	popup : 18
		button : 5
		call-to-action : 7
		countdown : 1
		heading : 16
		jet-ajax-search : 1
		text-editor : 7
	section : 5
		accordion : 1
		call-to-action : 12
		global : 1
		heading : 1
	widget : 0
		call-to-action : 2
		code-highlight : 2
		heading : 4
		table-of-contents : 1
	wp-post : 156
		button : 14
		call-to-action : 65
		code-highlight : 27
		global : 85
		heading : 614
		image : 113
		text-editor : 525
		video : 8
	wp-page : 48
		accordion : 3
		animated-headline : 1
		button : 14
		call-to-action : 10
		heading : 44
		image : 11
		jet-ajax-search : 2
		price-table : 2
		reviews : 6
		shortcode : 1
		sitemap : 3
		tabs : 1
		text-editor : 19
		video : 1
		woocommerce-products : 2


== Log ==
	
Log: showing 20 of 382021-06-21 18:50:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.3.1',
)]
2021-07-22 20:55:51 [info] elementor::elementor_updater Started 
2021-07-22 20:55:51 [info] Elementor/Upgrades - _on_each_version Start  
2021-07-22 20:55:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.1',
)]
2021-07-22 20:55:51 [info] Elementor/Upgrades - _on_each_version Finished 
2021-07-22 20:55:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.3.1',
)]
2021-07-22 20:56:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.4',
)]
2021-08-03 07:58:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.4',
  'to' => '3.3.5',
)]
2021-08-11 08:39:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.3.6',
)]
2021-08-16 07:24:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.6',
  'to' => '3.3.7',
)]
2021-08-17 09:02:45 [info] elementor::elementor_updater Started 
2021-08-17 09:02:45 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 09:02:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-17 09:02:46 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-17 09:02:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-18 10:49:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-18 10:49:28 [info] elementor::elementor_updater Started 
2021-08-18 10:49:28 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-18 10:49:29 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-18 10:49:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]

PHP: showing 4 of 4PHP: 2021-06-06 19:44:33 [notice X 1][/www/mylistingclub_662/public/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-19 08:49:48 [notice X 16][/www/mylistingclub_662/public/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-30 10:29:44 [warning X 3][/www/mylistingclub_662/public/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php::538] libxml_disable_entity_loader() has been disabled for security reasons [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-17 09:53:45 [notice X 25][/www/mylistingclub_662/public/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::160] Trying to get property 'taxonomy' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by urbancowboy1994** [comment]
Same here. Was this fixed in 3.4.2 by any chance?

**Comment by d19dotca** [comment]
Doesn't look like it, but it does have a pull request already according to the label that @shilo-ey added a couple of days ago, so I suspect this will be in the very next Elementor bug-fix update. I don't see what PR they're referring to but assuming the label is correctly added then it shouldn't be much longer.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.3.8

Feel free to update

Thanks!

**Comment by urbancowboy1994** [comment]
3.3.8 not yet available, not sure why it was closed before we can even test.

**Comment by MyListingClub** [comment]
> 3.3.8 not yet available, not sure why it was closed before we can even test.

Yeah, they really do have a double standard when it comes to what we have to do to submit (i.e. communicate) a bug and what they have to do in terms of their communication. The amount of effort is completely backward and comments like "Without it we simply can't help." are crazy. WE ARE HELPING YOU TOO ELEMENTOR.

**Comment by shilo-ey** [comment]
You don't need to test it. 

The version was released. the delivery mechanism in your site might have cache (transients) so in the next hours you will see it in your plugin updates.

In the meanwhile, you can download it via https://my.elementor.com/

Thanks

**Comment by urbancowboy1994** [comment]
> You don't need to test it.
> 
> The version was released. the delivery mechanism in your site might have cache (transients) so in the next hours you will see it in your plugin updates.
> 
> In the meanwhile, you can download it via https://my.elementor.com/ top bar button
> 
> Thanks

Fantastic, thanks for the update. I tried updating directly though the WordPress Plugins page when the issue was closed. Also checked the Elementor Downloads page in my account, and only 3.3.7 was available. I'll check again -- thanks boss!
