### ISSUE TITLE
Buttons and headings no longer inheriting colors from theme

### ISSUE THREAD

**Issue by hopkinsph** [elementor/elementor#16046]
Elementor checkboxes are set to inherit colors for buttons and headings from the theme (Astra, in this case). Was working perfectly until the most recent Elementor update earlier today.

Now, buttons that the theme styles as red are light green. Headings that were dark gray are now light blue.

I unchecked inherit theme color and font boxes and saved the setting. Then I rechecked the inherit boxes and saved the setting. Again, Elementor continues to display non-theme button and heading colors.

Went next to Elementor site settings. Manually changed button color to match theme color. Saved this setting, reloaded Web page and the button colors continue to be incorrect.

Note: When editing with Elementor, the buttons and heading text colors appear as expected (i.e., styled per theme colors). Using the hamburger menu to "View Page" results in buttons and headings styled incorrectly. I consider that this may be a cache issue, so I purged the page cache and the site cache. This had no effect on the incorrect color styling.

**Comment by jormeer** [comment]
Same problem. How can this problem pass your testing before release

**Comment by hogash** [comment]
Same here.

**Comment by hogash** [comment]
Seems like this commit https://github.com/elementor/elementor/commit/78600603f635639938050a742b149bae35f977b8 is  causing this.

**Comment by jrevillini** [comment]
Same issue - also using Astra.

**Comment by sonderjames** [comment]
Same issue - Hello theme

**Comment by bvisibleio** [comment]
Same problem. Applying theme color manually on each widget works - which defeats the purpose of a theme color.

**Comment by awebguy99** [comment]
Same problem. Hello Elementor theme. Global colors broken for various things (headings, buttons, icons).

**Comment by shilo-ey** [comment]
Thank you for reporting!

I merged this issue with #16037, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
