### ISSUE TITLE
Elementor 3.4.1 bug -  Motion effects 

### ISSUE THREAD

**Issue by gianpaolo-mowgli** [elementor/elementor#16044]
The Motion effects > scrolling effects 
Vertical scroll
Orizontal scroll
Rotate

have a problem

<img width="292" alt="Screen Shot 2021-08-18 at 17 49 21" src="https://user-images.githubusercontent.com/71620092/129930132-971662ac-167f-46a5-b211-8f01eaa7b197.png">

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.2

Feel free to update

Thanks!
