### ISSUE TITLE
Sitemap widget outputting nasty error message instead of nodes

### ISSUE THREAD

**Issue by DavidGMiles** [elementor/elementor#16049]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

No changes other than upgrade to latest Elementor release - Sitemap now does not render all nodes properly - see Screenshot

![sitemap error](https://user-images.githubusercontent.com/20774089/129972255-30da4690-f3f7-453a-87c7-98093189b961.jpg)

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hey @DavidGMiles 

Thanks!

Which versions are you using?
What is the query that you asked for?

I'm trying to understand how to reproduce this warning.

Thanks

**Comment by DavidGMiles** [comment]
Versions

![shiloh](https://user-images.githubusercontent.com/20774089/130350234-53482c1b-0a23-47f6-8931-7aaa6c26d409.jpg)

Query - every one that queries my event CPT for a Taxonomy is failing

They all worked previously

**Comment by shilo-ey** [comment]
Thanks

Can you portray the structure of the Taxonomy / CPT relations?

**Comment by DavidGMiles** [comment]
Simple - event CPT - example taxonomy is event country - a list of countries that we run trips to - single choice from option buttons 


Regards
David Miles
e: ***@***.***
w: http://natureslens.co.uk

**Comment by DavidGMiles** [comment]
@shilo-ey I've got another place it happens too - this one was just listing out repeater fields - a guide CPT has a number of repeaters associated with it - linked to taxonomies

**Comment by DavidGMiles** [comment]
Not convinced it was caused by Elementor - but wrapping implode code in a check first, clears the error

**Comment by shilo-ey** [comment]
Thanks
