### ISSUE TITLE
✅ 🔃 🚀 Feature Request: Icon List - vertically align icon settings - [ED-9265]

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#16056]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The most recent update to Elementor 3.4 introduced a "Fix: Icons are not vertically aligned in Icon List widget." But some of us liked having the icon vertically aligned at the top instead of in the middle. 

**Describe the solution you'd like**
It would be great to have a setting to choose the vertical alignment of the icon in an icon list.

**Describe alternatives you've considered**
Right now I've been using cutsom CSS to position the icon at the top

`selector .elementor-icon-list-item{align-items: start;}`
`selector .elementor-icon-list-item .elementor-icon-list-icon{margin-top: 5px; //or whatever works for you}`

**Comment by black-eye** [comment]
+1

**Comment by eSilverStrike** [comment]
I 100% want this. 

The icons in the icon list need a vertical alignment as well (top, middle, bottom). The top should align icons in multi row items to the first row so the margins of the icon are the same as a single row item. This also replicates how a regular list item works.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
