### ISSUE TITLE
🐞 3.4 and 3.4.1 BUG - Elementor Section/Column Styling and Image Links

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#16058]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description & Steps to reproduce
Since version 3.4 the image link width is wrong, elementor makes the a tag for the image display inline, but changing to block fixes it.
How it should be: 
![Screenshot_28](https://user-images.githubusercontent.com/55829113/130034202-f26efb07-e376-49ea-9684-9611164d4d6b.jpg)

Image link issue now being right size: 
![Screenshot_27](https://user-images.githubusercontent.com/55829113/130034255-d8e130e1-4749-4330-a653-cf873d3f8826.jpg)

Also in the above image look at the white text titles, this should be white but since 3.4.1 the Elementor colouring is dominating the colour here : 
![Screenshot_31](https://user-images.githubusercontent.com/55829113/130034416-4a604442-b6b2-4802-b6c0-f21a4740fe80.jpg)

Settings: 
![Screenshot_29](https://user-images.githubusercontent.com/55829113/130034446-dd225b54-8afa-4472-b8f6-6b1a0e4590e5.jpg)
![Screenshot_30](https://user-images.githubusercontent.com/55829113/130034456-3eda379c-d422-4a0e-b222-a8528a845c44.jpg)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.31
	PHP Version: 7.4.16
	PHP Max Input Vars: 2500
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://www.smithstimber.co.uk
	Home URL: https://www.smithstimber.co.uk
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 3221M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.6.8
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 3.5.8
		Author: Brainstorm Force

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Checkout Field Editor for WooCommerce (Pro)
		Version: 3.1.6
		Author: ThemeHigh

	Code Snippets
		Version: 2.14.1
		Author: Code Snippets Pro

	Cookie Bar
		Version: 1.8.8
		Author: Brontobytes

	Elementor
		Version: 3.4.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com

	Facebook Chat Plugin - Live Chat Plugin for WordPress
		Version: 2.2
		Author: Facebook

	Facebook for WooCommerce
		Version: 2.6.1
		Author: Facebook

	MainWP Child
		Version: 4.1.7
		Author: MainWP

	Manage Notification E-mails
		Version: 1.8.0
		Author: Virgial Berveling

	More Sorting Options for WooCommerce
		Version: 3.2.8
		Author: WP Wham

	Paymentsense Gateway for WooCommerce
		Version: 3.0.36
		Author: Paymentsense

	Rank Math SEO
		Version: 1.0.70
		Author: Rank Math

	Redirection
		Version: 5.1.3
		Author: John Godley

	Role Based Pricing for WooCommerce
		Version: 1.5.2
		Author: Addify

	Site Kit by Google
		Version: 1.39.0
		Author: Google

	User Role Editor Pro
		Version: 4.60.1
		Author: Vladimir Garagulia

	WooCommerce
		Version: 5.6.0
		Author: Automattic

	WooCommerce Measurement Price Calculator
		Version: 3.19.2
		Author: SkyVerge

	WooCommerce Order Approval
		Version: 5.6
		Author: Lagudi Domenico

	WooCommerce Product Add-ons
		Version: 4.1.0
		Author: WooCommerce

	WooCommerce Tab Manager
		Version: 1.14.1
		Author: SkyVerge

	WooCommerce Unit Of Measure
		Version: 3.0.2
		Author: Bradley Davis

	WP Mail SMTP
		Version: 3.0.3
		Author: WPForms

== Must-Use Plugins ==
	StackCache
		Version: 
		Author: Stack CP

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	section : 4
		divider : 1
		heading : 4
		icon-box : 2
		social-icons : 1
		text-editor : 3
	page : 1
		heading : 2
	wp-post : 0
		icon-box : 2
		search-form : 1
		social-icons : 1
		theme-site-logo : 1
	wp-page : 14
		button : 5
		counter : 3
		divider : 7
		google_maps : 1
		heading : 38
		html : 1
		icon : 2
		icon-box : 8
		icon-list : 9
		image : 1
		shortcode : 1
		text-editor : 22
	not-supported : 0
		divider : 2
		heading : 5
		html : 1
		icon-list : 1
		text-editor : 4

== Log ==
	
Log: showing 20 of 422021-08-17 08:10:15 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 08:15:18 [info] elementor::elementor_updater Started 
2021-08-17 08:15:18 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 08:20:15 [info] elementor::elementor_updater Started 
2021-08-17 08:20:15 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 08:25:16 [info] elementor::elementor_updater Started 
2021-08-17 08:25:16 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 08:30:14 [info] elementor::elementor_updater Started 
2021-08-17 08:30:14 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 08:34:15 [info] elementor::elementor_updater Started 
2021-08-17 08:34:15 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 08:34:16 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-17 08:34:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-17 08:34:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-18 09:53:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.3.7',
)]
2021-08-19 07:08:11 [info] elementor::elementor_updater Started 
2021-08-19 07:08:11 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-19 07:08:11 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-19 07:08:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-19 07:08:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]

PHP: showing 1 of 1PHP: 2021-08-17 08:15:18 [error X 4][/home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php::180] Uncaught Error: Call to a member function get_component() on null in /home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php:180
Stack trace:
#0 /home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php(68): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->set_preview_settings(Array)
#1 /home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-content/plugins/elementor/includes/base/element-base.php(537): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->get_raw_data(false)
#2 /home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-content/plugins/elementor/includes/base/element-base.php(537): Elementor\Element_Base->get_raw_data(false)
#3 /home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-content/plugins/elementor/includes/base/element-base.php(537): Elementor\Element_Base->get_raw_data(false)
#4 /home/virtual/vps-743362/5/5ec0dd9c4b/public_html/wp-conte [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by puregraphx** [comment]
There is certainly something off with link colours in 3.4.1.
I have an Icon List widget where the first items is a link. Prior to 3.4.1 the link would get its colour from
`.elementor-kit-8 a {
    color: var( --e-global-color-primary );
}`

In 3.4.1. the elementor-icon-list-text will override the link colour even though text colour is NOT set in the widget.
![image](https://user-images.githubusercontent.com/10434048/130045214-9f977cd8-4636-4986-b198-de9035d32e8a.png)
![image](https://user-images.githubusercontent.com/10434048/130045391-c3601eb0-d04d-4cda-8408-2b3b6cf56938.png)

**Comment by shilo-ey** [comment]
Thanks for reporting.

If you rollback to v3.4.0 the issue resolves?

We are aware of the issue with global colors overrides the default "None" settings.

Thanks

**Comment by shilo-ey** [comment]
If so, I'm merging this issue with #16037, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by perks98** [comment]
Hi @shilo-ey, when rolling back to 3.4 and regenerating css with Elementor the colour seems to fix itself. That's just for the colour.
The image link issue is still present, when you make an image a link Elementor encases the image with an 'a' tag which is styled with inline-block display so if the image is set with fixed height and 100% width it doesn't go 100%.

**Comment by perks98** [comment]
@shilo-ey example of the image issue: 
![GIF 19-08-2021 10-54-37](https://user-images.githubusercontent.com/55829113/130048739-eaf750bd-7582-451b-8f00-793d5d070081.gif)

**Comment by shilo-ey** [comment]
@perks98 can you please share a link for a page that experiences this issue?

**Comment by perks98** [comment]
Hi @shilo-ey I've quickly created this page, hope that helps.
[https://the-cobham-larder.callistowp.uk/image-link-elementor-issue/](https://the-cobham-larder.callistowp.uk/image-link-elementor-issue/)

**Comment by shilo-ey** [comment]
Thanks, will check it

But it seems unrelated to v3.4.* but to ±v3.2.*

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
