### ISSUE TITLE
Layout settings for content width not working for new additional breakpoints

### ISSUE THREAD

**Issue by digital-designer-au** [elementor/elementor#16055]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

The layout width set for the ‘widescreen’ breakpoint has no effect. Have also tried the laptop breakpoint with the same results. When a browser window reaches the set width for the widescreen breakpoint, it is still using the 'desktop' default content width.

Everything works as it should in the elementor builder, however when you preview the page on the front end, the content widths do not work and default to the desktop setting.

## Steps to reproduce

Add the new breakpoint of ‘widescreen’ and set to a value of something like 2000px. 

Go to the layout settings in the global settings and change the ‘content width’ to 1200px for the desktop breakpoint. Switch to the widescreen breakpoint and change the ‘content width’ to 1500px. 

Now add some content, specifically an element with a ‘boxed width’ layout. Now preview the page. If your window size is 2000px or more, the boxed width should be 1500px. If you resize the browser window to below 2000px, the boxed width on the page should reduce to 1200px. 

What is actually happening is that the setting/media query for the widescreen is not being inserted into the css. So even if your browser window is 2000px or more, the boxed width remains at a maximum size of 1200px.

https://www.loom.com/share/d3fd7ff5d8944af5951c5e5a124b3470?sharedAppSource=personal_library

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.2

Feel free to update

Thanks!

**Comment by bradallenfisher** [comment]
I'm still experiencing this 3.4.2. It
