### ISSUE TITLE
Values visible on each breakpoint 

### ISSUE THREAD

**Issue by JCwebTECH** [elementor/elementor#16051]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In the context of adding additional breakpoints in 3.4, it would be good to see the value of a parameter, that is set on another breakpoint.

**Usecase:**

1) I set Padding on default breakpoint
2) Go on with my life (design)
3) I come back to adjust the design for mobile devices

   **Currently:** I need to constantly switch to the default breakpoint and back to mobile one to see the values to adjust them reasonably. For example, I want padding 10px smaller, but I need to go see what is the value on the default breakpoint, remember it, come back to the mobile breakpoint and insert the value.

**Ideally:** I would see the set values on any breakpoint. Displaying the value in lighter grey/other colour would signal that it comes from a different breakpoint. I Could change it right away (ideally without affecting the other 3 values in case of margin/padding).

Thanks for considering this.

**Comment by shilo-ey** [comment]
Hey, this feature was just introduced. 

https://elementor.com/help/inherited-responsive-values/

Hope it will help you with the progress of work

Cheers
