### ISSUE TITLE
Elementor 3.4.1 The editor does not work if the condition of any option contains a key with characters outside the range a-z 0-9 - _ [ ] !

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#16065]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After update to Elementor 3.4.1 the editor does not work if the condition of any option contains a key with characters outside the range a-z 0-9 - _ [ ] !

When you open the editor, an error message appears in the console: 
"TypeError: conditionNameParts is null"
and the editor stops working

The error occurs in editor.js on line 23168:
`        	conditionRealName = conditionNameParts[1],
`
because in the previous line
`        var conditionNameParts = conditionName.match(/(^[a-z0-9-_\[\]]+)(!?)$/i),
`
the 'match' method returns false, because condition name contains invalid character.

In my opinion, it is much more logical to check the return value and ignore this condition if it is incorrect than to interrupt the editor.  Because because of one incorrectly named option in some plugin, the entire site stops being edited! And who said it was "wrong"? Why can't I use, for example, a '.' (dot) in the option name?

## Steps to reproduce

Add the condition shown below to any element:
```
		$element->add_control(
			'some_param',
			[
				'label' => esc_html__( 'Title', 'elementor' ),
				'type' => Controls_Manager::ANY_TYPE,
				'condition' => [
					'incorrect.name' => '1',
					'incorrect name' => '1'
				]
			]
		);

```
## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #16003, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
