### ISSUE TITLE
Broken color inheriting by code addition in base.php (lines 704 - 706)

### ISSUE THREAD

**Issue by Liarekon** [elementor/elementor#16069]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

By the followning code change (core/files/css/base.php lines 704-706) all not set colors are replaced by there default ones. So there is no inheriting from column or row styling any more for text or headlines.

```
		if ( ! is_numeric( $value ) && ! is_float( $value ) && empty( $value ) ) {
			_if ( ! empty( $control['global']['default'] ) ) {
				return $this->get_selector_global_value( $control, $control['global']['default'] );
			}_

			return null;
		}
```

## Steps to reproduce

1. Set the default kit color for Text (--e-global-color-text) to #ff0000 save it.
2. Create a page and insert a row with one column and a text widget.
3. Set color for text in the row style tab -> catrgory typography to #00ff00.
4. Check that there is no text color set in the text widget.
5. Show front end render and the text widget will render with #ff0000 instead of #00ff00.

## Isolating the problem

core/files/css/base.php lines 704-706

```
		if ( ! is_numeric( $value ) && ! is_float( $value ) && empty( $value ) ) {
			_if ( ! empty( $control['global']['default'] ) ) {
				return $this->get_selector_global_value( $control, $control['global']['default'] );
			}_

			return null;
		}
```

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Thanks,

This issue was already been reported and fixed. patch version should be released soon (couple of hours)
Please follow this issue for more information: #16037
