### ISSUE TITLE
Elementor Template Kit Library: "Expert" tag doesn't show nothing. I expected it to show Expert Templates.

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#16075]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description
I'm in the new Elementor Template Kit Library trying to filter kits from Free, Pro and Expert Plans. The problem is that the "Tags" only feature the "Expert" and it shows nothing.

## Steps to reproduce
Go to the new Template Kit Library and use the tag "Expert". Nothing will show up.
![image](https://user-images.githubusercontent.com/73240206/130108239-a9697713-b034-47f0-834d-e9ad92b446e5.png)

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment
Fresh elementor install
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by avivu** [comment]
Hello @paauserrat,
Thank you for your feedback.

We removed the Expert tag for now and will add in an upcoming release a new option to filter by price plan, so it will be easy to discover the different kits.

**Comment by paauserrat** [comment]
Amazing. Remember to also check some tags that are similar and display the same kits because there are a lot of tags and some of them aren't essential.
