### ISSUE TITLE
Picture Carousel after update 3.4.0 wrong text

### ISSUE THREAD

**Issue by DuerrundSteidle** [elementor/elementor#16073]
After updating to 3.4.0, the text in the picture carousel no longer works properly. The text entered in the description is output directly. This means that `<h2> </h2>` is no longer converted.

An update to 3.4.2 did not result in any improvement.

![image](https://user-images.githubusercontent.com/57152921/130106224-bc72d4e9-9683-4263-971f-8be0d1e99bec.png)

Before 
![image](https://user-images.githubusercontent.com/57152921/130106525-e06cb26f-2db4-4943-9bd5-8852f1d571e0.png)

After
![image](https://user-images.githubusercontent.com/57152921/130106487-e1a047ce-950c-4d39-96a4-e25a63f7bbef.png)

**Comment by DuerrundSteidle** [comment]
Sorry for asking but could the error be traced. Unfortunately, there is no fix after the last update.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.3

Feel free to update

Thanks!

**Comment by DuerrundSteidle** [comment]
Now it works thanks for it.
