### ISSUE TITLE
header color when mouse on the bottom

### ISSUE THREAD

**Issue by jmanopla** [elementor/elementor#16074]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by jmanopla** [comment]
hi since the last update of elemento, my header menu Bottom when i place the mouse on top of the bottom change to a grey color, this not happend before my header is Yellow always.

my site is www.rapipet.com

**Comment by shilo-ey** [comment]
Please make sure your Elementor version is updated to v3.4.2

Thanks
