### ISSUE TITLE
Single Page Template is not working on Hello Theme Elementor

### ISSUE THREAD

**Issue by DevDietheR** [elementor/elementor#16079]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
- [x] Install Elementor plugin (and Elementor Pro).
- [x] Use Hello Elementor Theme
- [x] Create a sample page
- [x] Create a Single Page Template and add post title, post content, etc and set Display Conditions to Pages > ALL

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Hello Elementor theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Hi @DevDietheR 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
