### ISSUE TITLE
Style Border improvement: Border Padding

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#16076]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to add a border to a container but I noticed there's not any option to set a border padding. I would like the border not to be at the very bottom of the container and instead, have the option to add some padding within the container and the border.

**Comment by rami-elementor** [comment]
@pauserratgutierrez 

This can be done simply by adding a **padding** to your section/column/widget.
