### ISSUE TITLE
🔥 New bug in recent elementor update...

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16091]
hello
In the icon list widget, if we put the Divider between the two options, it will not be in the middle. It is located below the text.
![Screenshot (126)](https://user-images.githubusercontent.com/77163248/130305662-7370f290-0e11-4f05-bb9a-54a7ed6bbbd6.png)
While before the update, it was exactly in the center. This is a small case, but it is definitely a bug. Please check it.

thank you

**Comment by shilo-ey** [comment]
I merged this issue with #14547, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
