### ISSUE TITLE
When Updating Elementor from 3.3.1 to 3.4.x the Database Updater does has a Critical Error Message

### ISSUE THREAD

**Issue by eSilverStrike** [elementor/elementor#16100]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

There is an Elementor Data Updater Bug. I get a WordPress Critical Error message when I attempt to run the database update process which it keeps asking me to do in the WordPress Admin. This happens on any of the Elementor 3.4.x versions.

Rolling back Elementor to 3.3.1 removes the Elementor Database Update message. Elementor Pro version installed is now at 3.3.7.

This bug happens on Elementor 3.4.0, 3.4.1, and 3.4.2 using WordPress version 5.8.

Disabling other plugins does not seem to fix the database updater and I get no additional information when I turn WordPress Debug on.

## Steps to reproduce

From Elementor 3.3.1 update to version 3.4.0 or 3.4.1 or 3.4.2

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by eSilverStrike** [comment]
I did find a work around. I disabled most of the plugins and then ran the upgrade and it worked.

**Comment by greggdev** [comment]
Disabled ALL plugins, db upgrade still fails and no debug error messages!  Forced to revert to 3.3.1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.4

Feel free to update

Thanks!

**Comment by zonerap** [comment]
I have updated elementor to 3.4.4, and have the same error again. >> 

Une erreur critique est survenue sur ce site. Veuillez consulter la boite de réception de l’e-mail d’administration de votre site pour plus d’informations.

En apprendre plus sur le débogage de WordPress.

**Comment by ceejayuk** [comment]
I have the same problem across three websites OR most recently, attempting to update Elementor core or Eleemntor Pro results in the message:

Elementor Data Updater
Database update process is running in the background. Taking a while?

To see if the issue resolves itself I've left one 'test' website in this state for MONTHS now and the problem remains.
Beneath the above message is the button "Click here to run it now". Click the button and the website breaks.

Please can someone at Elementor take a look at this long outstanding issue?
