### ISSUE TITLE
⛔ 🐞 Bug Report: Templates inserted by Template Widget or Shortcodes aren't styled in Editor

### ISSUE THREAD

**Issue by DYNOMENTS** [elementor/elementor#16103]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using the Templates Widget it doesn't show the right style when rendered into the Editor. You do see the font color, but the right font isn't rendered. This also applies to all the other styling options. 
-->

## Steps to reproduce

- Create a new Elementor Template
- Fill this with the content that you need
- Go to the page where you want to implement the template
- Choose the Template Widget of Shortcodes Widget and insert the right template
- Save and reload the editor. 

When reloading the Editor you will see that it does keep some of the styling parts, but for example, the fonts aren't styled properly. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: http://rexy-elementor.local
	Home URL: http://rexy-elementor.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

== Active Plugins ==
	ACF Options Page Admin
		Version: 3.9.6
		Author: John A. Huebner II

	Advanced Custom Fields PRO
		Version: 5.9.7
		Author: Delicious Brains

	Advanced Post Queries
		Version: 1.0.15
		Author: Shabti Kaplan

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.9.2
		Author: WebDevStudios

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Dynoments Rexy - Alfa
		Version: 1.0.5.3
		Author: Dynoments

	Elementor
		Version: 3.4.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.3.7
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	section : 9
		gallery : 1
		heading : 8
		image : 3
		posts : 1
		repeaters-widget : 3
		template : 1
		text-editor : 2
	wp-page : 6
		flexible-content-widget : 5
		form : 1
		heading : 3
		posts : 1
		repeaters-widget : 2
		star-rating : 1
		template : 1
	single-post : 1
		heading : 1

== Log ==
	
PHP: showing 19 of 19PHP: 2021-07-05 11:53:14 [error X 4][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php::2038] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 987 and defined in /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php:2038
Stack trace:
#0 /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php(987): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/includes/base/controls-stack.php(1787): Elementor\Controls_Stack->get_data('settings')
#2 /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /Users/roelofotten/Local Sites/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-09 16:59:29 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:314) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-10 15:58:33 [warning X 3][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:374) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-10 16:03:07 [warning X 2][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:382) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-10 16:04:18 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:380) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-16 04:35:26 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:275) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 08:44:09 [warning X 6][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:287) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 08:48:10 [warning X 2][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:288) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 09:07:14 [warning X 6][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:286) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 09:12:32 [warning X 2][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:246) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 09:15:27 [warning X 11][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:285) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 09:21:06 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:257) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 09:38:55 [warning X 2][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:295) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 12:14:35 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:21) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-18 13:47:54 [warning X 2][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:78) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-19 08:01:10 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:53) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-19 08:03:48 [warning X 2][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:83) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-19 08:46:20 [notice X 14][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-19 13:15:20 [warning X 1][/Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Users/roelofotten/Local Sites/dynoments-rexy-elementor/app/public/wp-content/plugins/dynoments/modules/dynamic-tags/classes/flexible-subfields.php:73) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 242021-07-19 08:36:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0-dev4',
  'to' => '3.3.0',
)]
2021-07-19 08:36:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.3.1',
)]
2021-08-17 11:35:28 [info] elementor::elementor_updater Started 
2021-08-17 11:35:28 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-17 11:35:28 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-17 11:35:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0',
  'to' => '3.4.0',
)]
2021-08-17 11:35:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.0',
  'to' => '3.4.0',
)]
2021-08-17 11:36:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.3.7',
)]
2021-08-19 08:46:06 [info] elementor::elementor_updater Started 
2021-08-19 08:46:06 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-19 08:46:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-19 08:52:37 [info] elementor::elementor_updater Started 
2021-08-19 08:52:37 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-19 08:52:37 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-19 08:52:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-20 11:00:19 [info] elementor::elementor_updater Started 
2021-08-20 11:00:19 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-20 11:00:19 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-20 11:00:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-08-20 11:00:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]

**Comment by nicholaszein** [comment]
Hello @DYNOMENTS,

We know it's been a while since you submitted your issue, and I want to apologize for that. Thank you for reaching out and for your patience, and sorry for the inconvenience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor anymore. Here's what we found out:
* We tested with Elementor version 3.8.0, and Elementor Pro 3.8.1, with the Hello Elementor theme v2.6.1, and all the styles appeared as expected, both using the Shortcode and Template widgets.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get.

Kind regards
