### ISSUE TITLE
Elementor Pro crashed my website - Cant get back in.

### ISSUE THREAD

**Issue by Wallisco** [elementor/elementor#16114]
## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).  No issue with Elemento but on installation of Elementor Pro it crashed.
- [x] This bug happens with a default WordPress theme active.  I have Porto theme running and t worked fine with just Elementor
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
