### ISSUE TITLE
Cannot upload svg anymore - Post-processing error

### ISSUE THREAD

**Issue by brittaweller** [elementor/elementor#16119]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I can't upload svg images anymore. And yes I have enabled it in elementor settings.
When I upload any svg it will fail to upload with this error message: "Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels."

## Steps to reproduce

Theme: Twenty One or Hello Elementor / Elementor activated 
Widget Icon -> Upload Svg => Not working

----
When I use a theme which allows svg upload than it works only if I deactivate Elementor

If I downgrade to Elementor 3.3.0 it is working as expected again!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/rcR63BFU				
</details>

**Comment by d19dotca** [comment]
This is a duplicate of https://github.com/elementor/elementor/issues/16084 and should be closed.

**Comment by brittaweller** [comment]
> This is a duplicate of #16084 and should be closed.

Yes you are right. Sorry I didn't find this before..

**Comment by shilo-ey** [comment]
duplicate of #16084

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.4.3

Feel free to update

Thanks!
