### ISSUE TITLE
Motion effect not applied on the new breakpoints

### ISSUE THREAD

**Issue by navarroido** [elementor/elementor#16117]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
Description:
Motion effect not applied on the new breakpoints.
when you set a motion effect on widget, for example: 
set scrolling blur effect on image, and you set this effect to applied on all devices (desktop, mobile, tablet) 
until now all work perfect.

when you use the new breakpoint, for example set the laptop device and set his resolution to be from "1500px"
then if you look on the live site with the effect, the effect don't work.
if i understand the code behind the motion effect lookup for device that triggered in the "applied effect on" field there we can choose only desktop, mobile, tablet and cant see the new breakpoint so the code don't set the effect in the new breakpoint

stesp:
1. add image or text widget to page
2. set motion effect ( i used Transparency on scrolling)
3. set new breakpoint ( i used laptop and change his size to "1500px")
4. open page in live mode 

![Capture](https://user-images.githubusercontent.com/10985125/130523078-243f42d9-143d-4b5f-844c-26db85da5767.JPG)

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```


<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by udidol** [comment]
Hi @navarroido,
Please check you are using the latest versions of Elementor and Elementor Pro.
Also, please check that the Additional Custom Breakpoints experiment is active in your admin dashboard.
