### ISSUE TITLE
🔗 🚀 Feature Request: addition of TABLE, CHART & GRAPHS Widgets (Duplicate of #1342, #1685)

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#16137]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently elementor doesn't have any widget to implement a table, chart or graph.

**Describe the solution you'd like**
The addition of a table widget
The addition of a chart & graphs widget

Each one should come with some presets and a lot of customization

**Describe alternatives you've considered**
Custom HTML, CSS or using widgets to create it, but elementor should include them.
Extra plugin for chart and graph: https://elements.envato.com/graphs-charts-for-elementor-GFHG7J8
Extra plugin for tables.

**Additional context**
Options to sort, import & download data to CSV and EXCEL, icon, url, search, filtering, sticky header, pagination, nav style, table layout,  integration with woocommerce to show items and compare, style options, pre-build layouts

Some Tables:
![image](https://user-images.githubusercontent.com/73240206/130701456-e64808b8-2370-4a2c-a8f8-45c3485cc65c.png)
![image](https://user-images.githubusercontent.com/73240206/130701770-adca79e2-ea9e-432e-bea0-b64687ade658.png)
![image](https://user-images.githubusercontent.com/73240206/130701741-05da28cd-861b-4326-a914-034c4135ce79.png)

Some Graphs:
![image](https://user-images.githubusercontent.com/73240206/130701937-e6b6a400-c3ec-41ec-a52a-afe740b17bc2.png)
![image](https://user-images.githubusercontent.com/73240206/130701886-080ad21f-d127-461b-96ef-0a35ca29915e.png)
![image](https://user-images.githubusercontent.com/73240206/130701911-09736834-adf6-4095-8ad5-823071a5a9ba.png)

**Comment by paauserrat** [comment]
https://github.com/elementor/elementor/issues/1685

**Comment by 79ho3ein** [comment]
+1

**Comment by LausanneMarketing** [comment]
+1

**Comment by pauserratgutierrez** [comment]
@rami-elementor

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #1342 , and here #1685.

Since we are now organizing our feature requests, and preparing them to be migrated to the new Discussions page, we are prioritizing single requests rather than multiple ones. For this reason, I am closing this issue.

Feel free to continue the conversation on each respective issue!

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards
