### ISSUE TITLE
Hooks for new tabs/menu items

### ISSUE THREAD

**Issue by joshuatf** [elementor/elementor#1614]
It would be great if there were a hook to create a custom panel menu item (like the current Global Colors or Page Settings).  Hoping to create custom fields to store in the options table.

I looked at doing this by extending Page Settings Manager, but it appears the actual menu items are generated from the editor.js file if I'm not mistaken.

**Comment by kamalahmed** [comment]
Hi, any update on this after 28 months?

**Comment by rami-elementor** [comment]
I will try to answer this issue but have to point out that the title talks about "menu tabs" in an existing panel and but the message talks about custom panels.

We currently don't have an API the create new panels. But we do have a method to add new tabs and use them in existing panels.

Read this dev doc: https://developers.elementor.com/docs/editor/elementor-tabs/
