### ISSUE TITLE
BUG in Share buttons widget (new version of elementor)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16148]
hello
If "Font-Awesome Inline" is enabled in the settings, the sharing buttons widget crashes. The bug is that the custom color of the share buttons widget gets out of control. For example, Secondary Color I choose red but it is white on the website.

**Please check this problem, if you do not understand the problem, I will send a video. In any case, I am sure there is a bug. Because I tested on a website that had only elementor and elementor pro installed.**

details :

wordpress : 5.8
elementor : 3.4.2
elementor pro : 3.3.8

thank you

**Comment by 79ho3ein** [comment]
hi @DorShahar Please check this bug.

thank you

**Comment by 79ho3ein** [comment]
hello @shilo-ey Please check this bug.

thank you

**Comment by 79ho3ein** [comment]
Please let me know if you need to make a video of the bug. Thank you

**Comment by 79ho3ein** [comment]
hello @ShayHel please check this bug.

thank you

**Comment by 79ho3ein** [comment]
hello @shilo-ey  please check this bug.

thank you

**Comment by zhiru** [comment]
This is not solved yet?

**Comment by 79ho3ein** [comment]
No!

**Comment by nicholaszein** [comment]
Hello there!

### 📢 The issue you raised was resolved in Elementor Pro v3.4.2! 🥳 

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
