### ISSUE TITLE
 after update 3.4.0 – 2021-08-17 / animated text Highlighted text and countdown are not displayed correctly

### ISSUE THREAD

**Issue by Robby27041986** [elementor/elementor#16176]
There are still problems with the font color, I noticed it in the animated text Highlighted text and countdown
Attached Files: https://my.elementor.com/wp-content/uploads/sites/2/gravity_forms/22-8fa82d82d4bd295a437b035bfb146a16/2021/08/animated-text-Highlighted-text.jpg 

https://my.elementor.com/wp-content/uploads/sites/2/gravity_forms/22-8fa82d82d4bd295a437b035bfb146a16/2021/08/countdown.jpg 

https://my.elementor.com/wp-content/uploads/sites/2/gravity_forms/22-8fa82d82d4bd295a437b035bfb146a16/2021/08/system-info-happybirthday-girl.com-23-08-2021.txt

**Comment by DorShahar** [comment]
Hi @Robby27041986 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
