### ISSUE TITLE
Elementor breaks 'view' link on Media Library items

### ISSUE THREAD

**Issue by bob7123** [elementor/elementor#16175]
Hello,

With the (latest production) Elementor plugin enabled, there is a problem if you go to the media library and try to click on “view” on an item.  

If Elementor is disabled, the problem goes away.  If all other plugins are disabled and Elementor is enabled, the problem occurs.

Normally, clicking on the “View” option opens a page showing the media item.  

Enabling Elementor does not change the URL of the “View” link, but instead of the link showing a page, it shows “Oops! That page can’t be found” instead. 

I don’t have the pro version installed, just the free one.

Please let me know if there is anything I can do to help resolve this.

Take care,

-Bob

**Comment by DorShahar** [comment]
Hi @bob7123 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by bob7123** [comment]
Hi,

I logged in to the admin site today and saw there was an update for elementor.  I verified the problem is still occuring, then applied the update and the problem went away.  

I was using the Sydney theme, BTW. 

-Bob
