### ISSUE TITLE
Replace Inner Sections with Flex Box

### ISSUE THREAD

**Issue by c-nickerson** [elementor/elementor#16178]
**What problem is your feature request going to solve? Please describe.**
The standard section/inner section system is too limiting. It is very annoying and frustrating when trying to create less than basic designs. As of now, you cannot nest inner sections within each other, you cannot wrap columns using flex-wrap as all columns must add up to 100%, and you cannot have more than 12 columns in a single row. While these are generally good ideas for basic designers they are crippling to advanced designers.

Currently, you CANNOT create a 12 item grid that is 4x3 on desktop, 3x4 on tablets, and 2x6 on mobile. This is something I am currently trying to do and it isn't possible so I'm at a standstill.

**Describe the solution you'd like**
Replace the inner section widget with a flexbox widget similar to Bootstraps grid. https://getbootstrap.com/docs/5.1/layout/grid/

This would allow users to create a flexbox and create inner columns. The flexbox can be set You could set a column to different widths based on the viewport to allow collapsing of columns within the flexbox.

Demo
https://codepen.io/cory-nickerson/pen/zYzvYyN

**Describe alternatives you've considered**
I've tried other plugins. The closest one that works is the ooohboi one which allows you to override the Elementor column widths and puts anything over onto a new line. This can be achieved with hard-coded CSS as well by using media queries to set the width of the columns based on screen size. However, it doesn't allow more than 12 columns in a single inner section which can be problematic when trying to create a grid with more than 12 items. You also still cannot nest inner sections as well.

**Comment by black-eye** [comment]
Agreed that the current layout aproach starts to get aged, but since the whole section/column concept needs to be overwritten (and probably won’t be backward compatible), it would be better to give it a fresh start from a scratch and use CSS grid.

**Comment by c-nickerson** [comment]
> Agreed that the current layout aproach starts to get aged, but since the whole section/column concept needs to be overwritten (and probably won’t be backward compatible), it would be better to give it a fresh start from a scratch and use CSS grid.

Probably would be best to not remove the current inner sections completely, but move to a legacy section to allow people the option to still use or edit existing designs.

**Comment by black-eye** [comment]
> 
> 
> > Agreed that the current layout aproach starts to get aged, but since the whole section/column concept needs to be overwritten (and probably won’t be backward compatible), it would be better to give it a fresh start from a scratch and use CSS grid.
> 
> Probably would be best to not remove the current inner sections completely, but move to a legacy section to allow people the option to still use or edit existing designs.

Yes, definitely! I would keep the current section approach as it is and introduces brand new container element. This new Container could have options for both CSS grid and flexbox layout and could be also used INSIDE other widgets as tabs, accordeons, sliders/carousels etc. Current section/column widgets would stay as they are to maintain backwards compatibility. There could be an option to turn the old approach on/off. Everyone would be happy, nothing won't get broken. 

So much for the dreams and how it could be done. We can dream on... ;-)

**Comment by DorShahar** [comment]
Hi @c-nickerson 
We are on it ;) 
Stay tuned, and follow our `dev-edition` (See [here](https://elementor.com/help/elementor-developer-edition/) for more info)

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!
