### ISSUE TITLE
Responsive columns issue

### ISSUE THREAD

**Issue by Ringsoe** [elementor/elementor#16188]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I may be able to report a bug after the last update to four more breakspoints!

It looks like desktop view is overriding mobile view. 

## Steps to reproduce

If the column width is set by default, ie not specified, then I can specify the column width for mobile. [A and B] And thus get what I want.
Conversely, if I specify the column width for desktop, then it works incorrectly for mobile. [C and D]

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>I am using updated versions of wordpress v5.8,
Hello Elementor v2.4.1, Elementor v3.4.2 and Elementor Pro v3.3.7
For a complete list
</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

![A](https://user-images.githubusercontent.com/17222607/131240524-dab9f798-40bb-44bf-ba04-1a87cceaba82.jpg)

![B](https://user-images.githubusercontent.com/17222607/131240527-2ee1ccfe-c194-495f-a6dc-4814ef3eb66f.jpg)

![C](https://user-images.githubusercontent.com/17222607/131240530-f1939ab0-ea82-4a14-bdc8-050058b0678c.jpg)

![D](https://user-images.githubusercontent.com/17222607/131240533-197bd5c4-bb56-474a-8783-8ed77170cb43.jpg)

![Plugins](https://user-images.githubusercontent.com/17222607/131240538-cefdb36b-3f0e-43a2-a17b-484deca399a5.jpg)

**Comment by DorShahar** [comment]
Hi @Ringsoe 
Desktop values cascade down from desktop to "smaller devices" like mobile unless you define otherwise. 
In the case of not entering a value - the default value applies as well (so in this case it's just worked for you).

Elementor is built to design from big screens to small screens.

Thanks

**Comment by Ringsoe** [comment]
Hi @DorShahar
I know, I know :) But that's not the problem. Columns defined for mobile devices do not appear as desired. Instead of [B], it ends up in [D]. For mobile devices, I specify 100% per column. [E] Preview does not display it correctly.

**[B]**

![B](https://user-images.githubusercontent.com/17222607/131240527-2ee1ccfe-c194-495f-a6dc-4814ef3eb66f.jpg)

**[D]**

![D](https://user-images.githubusercontent.com/17222607/131240533-197bd5c4-bb56-474a-8783-8ed77170cb43.jpg)

**[E]**

![E](https://user-images.githubusercontent.com/17222607/131253864-f61a7d44-4338-4433-9cda-f686a1f83f17.jpg)

**Comment by Ringsoe** [comment]
Unsolved!
