### ISSUE TITLE
Animation Scroll effects and animation  mouse effects stopped working after the latest update

### ISSUE THREAD

**Issue by marvben** [elementor/elementor#16180]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Hi @marvben 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by marvben** [comment]
Great! Thank you so much!
