### ISSUE TITLE
BUG | Sicky Header or Sticky Elements

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#16186]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Sticky elements such us Header, Columns, or whatever are not working properly with the latest update: Custom Breakpoints. I need to resize the screen to the sticky header to show up.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by d19dotca** [comment]
It seems this was fixed in 3.4.1, is it? Just curious because this is still marked as open in GitHub.

**Comment by maurocarreraok** [comment]
It is fixed @d19dotca.

**Comment by DorShahar** [comment]
Hi @maurocarreraok and @d19dotca 
We fixed the issue in Pro 3.4.1

I'm closing this issue.
Thanks
