### ISSUE TITLE
Ability to insert icons for nav menu widget (Request a new feature)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16205]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Ability to add custom icons to the nav menu widget.

We can boldly say that one of the most important features that elementor currently lacks is the ability to insert a custom icon for the nav menu ...
![Screenshot (129)](https://user-images.githubusercontent.com/77163248/131445077-73c516b9-b99e-4819-8367-d8017c76a4b3.png)

**Describe the solution you'd like**

**Does elementor have a plan to release this feature?**
**Will this feature be released in 2021 with Megamenu?**

In any case, I hope to see this important feature in elementor soon. Elementor plugins do this, **but it does not make sense to use miscellaneous plugins for a simple feature.**

Thanks to the elementor team

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by 79ho3ein** [comment]
thank you @DorShahar 
Please check # 16148 if possible.

thanks

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
