### ISSUE TITLE
Visual Indicator that site is in maintenance mode

### ISSUE THREAD

**Issue by JennyPower** [elementor/elementor#16203]
It would be great if there was a visual indicator that the site is in maintenance mode. Perhaps an indicator in the WP toolbar area.

**Comment by DorShahar** [comment]
Hi @JennyPower 
There is a visual indicator.
One you enable maintenance mode (Elementor > Tools > Maintetnece mode ) the top bar will look like this:
![image](https://user-images.githubusercontent.com/19154938/131463982-5371e73e-c98d-4d54-86df-d462a2139985.png)
 
 
 Thanks
