### ISSUE TITLE
✅ 🐞 Media Carousel widget with Vimeo videos

### ISSUE THREAD

**Issue by AbanobAkram** [elementor/elementor#16209]
It seems there is an issue with Vimeo videos in the Media Carousel widget when lightbox is enabled.

Steps to reproduce: 

- Add Elementor Media Carousel
- Add more than one repeater item
- Set media type to video, use Vimeo videos as: https://vimeo.com/587643652/4ebddffa2b
- You will see lightbox opens, but the video is not loaded

Regards

**Comment by nicholaszein** [comment]
Hello there @AbanobAkram!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

Now Vimeo videos that have privacy settings enabled should load correctly on the lightbox.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
