### ISSUE TITLE
MEDIA CAROUSEL // Cannot change number of "Slides Per View" depending on NEW additional Breakpoints

### ISSUE THREAD

**Issue by lordloadalot** [elementor/elementor#16210]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by lordloadalot** [comment]
WIDGET: MEDIA CAROUSEL.
SITUATION: I want to show **5 Slides on Widescreen** / 4 Slides on Desktop / 2 Slides on Tablet / 1 Slide on Mobile.
PROBLEM: After activating the new Feature "Additional Breakpoints" the number of "Slides Per View" disapperas in the backend.
I can only change "Slides To Scroll". Please Help :)

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
