### ISSUE TITLE
DOGESHOP.COM

### ISSUE THREAD

**Issue by conradstrauss** [elementor/elementor#16223]
Cannot get into my admin account. What can I do?

**Comment by d19dotca** [comment]
This is not an Elementor issue and should be closed. Also seems somewhat spammy with the web address in the title. 🤷‍♂️

**Comment by DorShahar** [comment]
Hi @conradstrauss 

As @d19dotca  mentioned, this issue isn't related to Elementor.  Please create GitHub issues only for bugs reports and feature requests.

**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
