### ISSUE TITLE
Developer Experience Survey

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#16227]
Hi,

I’m inviting you to participate in our first **Elementor Developers' Survey** to help us improve your developer experience.

The survey includes questions about yourself, your needs, pain points you’ve encountered developing with Elementor and places you want us to improve.

Follow this link to fill our short (7 min) survey:
https://docs.google.com/forms/d/e/1FAIpQLScaahAYzX1y4DqjOHLzvfpvnXKAai6p_3liLaiEosz56EvQpg/viewform

Thank you!

Rami Yushuvaev,
Head of Developer Experience 
[developers.elementor.com](https://developers.elementor.com/)

**Comment by shilo-ey** [comment]
Thank you for your inputs!
