### ISSUE TITLE
Table of contents bug

### ISSUE THREAD

**Issue by jormeer** [elementor/elementor#16229]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

Table of contents bug.
Use the show bullets option and then select none. Like the screenshot. This will cause a "undefined" error in the table of contents.
See second screenshot

(https://user-images.githubusercontent.com/24415427/131671083-2938af7b-2208-43a8-82f8-1fb313f68b3c.JPG)

(https://user-images.githubusercontent.com/24415427/131671486-f8b2606a-042e-4661-ad2e-0df7f9d476ec.JPG)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.10
	MySQL version: mariadb.org binary distribution v10.5.10
	PHP Version: 8.0.8
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8
	Site URL: https://smoothiesenzo.nl
	Home URL: https://smoothiesenzo.nl
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: nl
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.10.2
		Author: Delicious Brains

	Autoptimize
		Version: 2.9.2
		Author: Frank Goossens (futtta)

	Ele Custom Skin
		Version: 3.1.2
		Author: Dudaster.com

	Elementor
		Version: 3.4.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.0
		Author: Elementor.com

	Form Vibes - Database Manager for Forms
		Version: 1.3.7
		Author: WPVibes

	GDPR Cookie Consent
		Version: 2.0.5
		Author: WebToffee

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	ProfilePress
		Version: 3.1.17
		Author: ProfilePress Team

	Rank Math SEO
		Version: 1.0.70
		Author: Rank Math

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	ShortPixel Image Optimizer
		Version: 4.22.5
		Author: ShortPixel

== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 2.3.2
		Author: Kinsta Team

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatibel
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatibel

== Elements Usage ==
	
	archive : 3
		button : 2
		divider : 2
		heading : 6
		image : 2
		posts : 2
		spacer : 4
		text-editor : 2
	footer : 1
		button : 1
		divider : 1
		facebook-page : 1
		heading : 5
		image : 5
		nav-menu : 2
		social-icons : 1
		text-editor : 7
	header : 2
		button : 4
		heading : 4
		icon : 2
		nav-menu : 4
		theme-site-logo : 4
	loop : 1
		author-box : 1
		post-info : 1
		text-editor : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	page : 10
		button : 17
		counter : 13
		divider : 2
		gallery : 3
		heading : 68
		icon-box : 4
		icon-list : 8
		image : 32
		posts : 1
		text-editor : 61
		theme-page-title : 1
	popup : 1
		button : 1
		heading : 1
		text-editor : 1
	section : 16
		button : 11
		facebook-page : 2
		gallery : 1
		heading : 23
		image : 11
		nav-menu : 6
		social-icons : 3
		spacer : 1
		text-editor : 20
	single : 2
		divider : 1
		heading : 2
		post-info : 1
		posts : 1
		share-buttons : 1
		spacer : 3
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	widget : 0
		button : 1
		icon : 1
	wp-post : 4
		button : 3
		heading : 39
		icon-list : 3
		image : 12
		spacer : 1
		table-of-contents : 5
		text-editor : 45
	wp-page : 14
		button : 12
		counter : 6
		divider : 8
		form : 1
		gallery : 4
		heading : 99
		html : 1
		icon-box : 4
		icon-list : 9
		image : 60
		posts : 4
		spacer : 6
		text-editor : 108
		theme-page-title : 2

== Log ==
	
Log: showing 20 of 402021-08-11 12:30:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.5',
  'to' => '3.3.6',
)]
2021-08-15 21:31:18 [info] elementor::elementor_updater Started 
2021-08-15 21:31:18 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-15 21:31:19 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-15 21:31:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-15 21:31:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-16 09:54:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.6',
  'to' => '3.3.7',
)]
2021-08-25 11:59:46 [info] elementor::elementor_updater Started 
2021-08-25 11:59:46 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-25 11:59:46 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-25 11:59:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.2',
)]
2021-08-25 11:59:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.2',
)]
2021-08-27 14:42:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.7',
  'to' => '3.3.8',
)]
2021-08-31 12:17:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-31 12:17:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.8',
  'to' => '3.4.0',
)]
2021-08-31 12:17:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.8',
  'to' => '3.4.0',
)]
2021-08-31 12:17:07 [info] elementor::elementor_updater Started 
2021-08-31 12:17:07 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-31 12:17:08 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-31 12:17:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]

PHP: showing 2 of 2PHP: 2021-08-15 23:38:22 [warning X 12][/www/smoothies_684/public/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg.php::30] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-17 17:57:57 [warning X 1][/www/smoothies_684/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by DorShahar** [comment]
Hi @jormeer 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by jormeer** [comment]
> Hi @jormeer
> Thank you for taking the time and reporting this.
> 
> We recreated your process of work and it seems to work properly.
> 
> Please try:
> 
> * Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
> * Change your WordPress theme to Hello Theme (or other default WordPress theme).
>   And see if the issue still persists.
> 
> If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.
> 
> Thanks.

I used a staging website and i found the issue. It has to do with the 
Font-Awesome inline option. When enabled you get this bug. Disabled it is gone.

Please try that.
