### ISSUE TITLE
Error On elementorFrontend.getCurrentDeviceSetting Function Call

### ISSUE THREAD

**Issue by meceware** [elementor/elementor#16236]
Hi,

I'm an Elementor plugin developer, and I've been facing an issue with Elementor 3.4. When `elementorFrontend.getCurrentDeviceSetting` is called when the page is ready, the function generates the error below:

```
Uncaught TypeError: Cannot read property 'getActiveBreakpointsList' of undefined
    at Frontend.getDeviceSetting (frontend.min.js?ver=3.4.3:2)
    at Frontend.getCurrentDeviceSetting (frontend.min.js?ver=3.4.3:2)
```

You can install the file as a new plugin on a test site. This code works with previous versions of Elementor but not with Elementor 3.4.0. Can you help and see what's happening?

Thank you,

[sample-plugin.zip](https://github.com/elementor/elementor/files/7097789/sample-plugin.zip)

```php
<?php
/**
 * Plugin Name: Sample Plugin
 * Author: meceware
 * Version: 1.0.0
 * Description: Sample Plugin
 * Text Domain: sample-test-plugin
**/

/*
Steps to reproduce:

- Activate this plugin
- Create a new page
- Add a heading (or any other element) to the page
- Set Entrance Animation option under Motion Effects for the heading element
- View the page

*/

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
  exit;
}

add_action('plugins_loaded', 'myOnPluginsLoaded', 100);
function myOnPluginsLoaded() {
  add_action('elementor/init', 'myOnElementorInit');
}

function myOnElementorInit() {
  add_filter( 'wp_footer', 'myOnElementorContent' );
}

function myOnElementorContent(){
?>
<script type="text/javascript">
  window.addEventListener("DOMContentLoaded", function(){
    function elementorGetParsed(element) {
      if (!element) {
        console.warn("Set an element with an entrance animation");
        return "";
      }
      var parsed = {};
      var settings = element.getAttribute("data-settings");
      if ( /_?animation/.test( settings ) ) {
        try {
          parsed = JSON.parse(settings);
        }catch(e){};
      }

      return parsed;
    }

    let parsed = elementorGetParsed( document.querySelector("[data-settings]") );

    /* The line below (elementorFrontend.getCurrentDeviceSetting function call) generates the error below */
    /* Uncaught TypeError: Cannot read property 'getActiveBreakpointsList' of undefined */
    console.log( "parsed value: ", elementorFrontend.getCurrentDeviceSetting(parsed, "animation") );
  });
</script>
<?php
}
```

**Comment by udidol** [comment]
Hi @meceware,
If you use `elementorFrontend`, you should run your code after it has been initialized.
Instead of running your code on the `'DOMContentLoaded'` event, run it on the `'elementor/frontend/init'` (also triggered on the `window` global).

Extra tip: When using the `elementor` global object, run the dependent code on `'elementor:init'`, also triggered on the `window` global.

The fact that it worked before was a matter of chance, you generally shouldn't trust that any methods on `elementorFrontend` (in the front end) or `elementor` (in the Editor) are available before these components are initialized.

**Comment by meceware** [comment]
Thanks for the answer @udidol. Is there a way to check if the `elementorFrontend` is initialized? (to check if `'elementor/frontend/init'` is triggered or not)

**Comment by udidol** [comment]
Why would you want that? Just run your code as a callback to the hook...

**Comment by meceware** [comment]
If the scripts are deferred on the page, it's good practice that checking if the event is fired or not. If the event is not fired already, run the function inside the event, otherwise, if event is fired, run the function directly. I've had an issue in the past because of this in the past, solved it like this. (`document.attachEvent?document.readyState==="complete":document.readyState!=="loading"`)

**Comment by udidol** [comment]
Not sure how to help you on that one, you just have to make sure to run tests and make sure your code runs at the proper time.
