### ISSUE TITLE
Embeed PDF with Elementor

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#16240]
I'm currently trying to embeed a Google Drive PDF but elementor doesn't have a widget for that. I tried with HTML but then I don't have options to style it.

My code
    <object data="https://docs.google.com/viewer?srcid=1Eg3awFiTNv7sAJmGSgR8P4M0g5lO7rpJ&amp;pid=explorer&amp;efh=false&amp;a=v&amp;chrome=false&amp;embedded=true" width="100%" height="474px" type="application/pdf">
        <embed src="https://docs.google.com/viewer?srcid=1Eg3awFiTNv7sAJmGSgR8P4M0g5lO7rpJ&amp;pid=explorer&amp;efh=false&amp;a=v&amp;chrome=false&amp;embedded=true" width="100%" height="474px" type="application/pdf" />
    </object>
![image](https://user-images.githubusercontent.com/73240206/131900221-dfb1dda3-ae96-4bbf-b269-eb3d99dc83f0.png)

Result:
![image](https://user-images.githubusercontent.com/73240206/131900097-b31d5c2e-9bfa-4e0a-b492-821b36f8cf0e.png)

It works but the problem is that I can't get rid of that gray background color. It's impossible to remove even with CSS for me. Can anyone help me?

**Comment by rami-elementor** [comment]
Hi @pauserratgutierrez ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by rami-elementor** [comment]
On a personal note, it's not an Elementor/WordPress issue, looks like it's a browser issue.
