### ISSUE TITLE
Rearrange custom "Global Colors/Fonts" in Site Settings

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#16249]
Hi,
Can I request a feature is:

Rearrange custom "Global Colors/Fonts" in Site Settings (Not System Global Colors/Fonts). This is helpful for create, edit, manage the Global Colors/Fonts. 

Because "created" Global Colors/Fonts applied for some Widget when design. And new Global Colors/Fonts need be above "created" Global Colors/Fonts

Thanks

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #12203, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by datverse** [comment]
Hi @DorShahar,
Thank you so much :)
