### ISSUE TITLE
Error wp-admin custom login

### ISSUE THREAD

**Issue by Arisvelperbroek** [elementor/elementor#16255]
Foutdetails

===========

Een fout van het type E_ERROR werd veroorzaakt op regelnummer 291 van het bestand /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-content/plugins/admin-custom-login/init.php. Foutmelding: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-content/plugins/admin-custom-login/init.php:291

Stack trace:

#0 /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-includes/class-wp-hook.php(303): acl_footer_func('')

#1 /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(Array, Array)

#2 /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-includes/plugin.php(470): WP_Hook->do_action(Array)

#3 /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-login.php(121): do_action('login_head')

#4 /var/www/vhosts/webadsign.nl/aris-velperbroek.nl/wp-login.php(1299): login_header('Inloggen', '', Object(WP_Error))

#5 {main}

  thrown

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
