### ISSUE TITLE
warning: headers already sent

### ISSUE THREAD

**Issue by VerzhineGalstyan** [elementor/elementor#16268]
When Elementor is active and I am activating other my plugins the warning is appears in php-fpm.log -- WARNING: [pool wplive] child 316363 said into stderr: "NOTICE: PHP message: PHP Warning: Cannot modify header information - headers already sent. Without active elementor the errors are not appears.
I use Form Maker by 10Web plugin, with which warning is appeared.
Elementor version 3.4.3, PHP version 8.0

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
