### ISSUE TITLE
🔗 🚀 Feature Request: Suggestion for developing the progress bar widget (Duplicate of #1685)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16261]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello
Great if you develop this widget. Currently this widget has a very simple shape. The jet element plugin is very powerful in this widget.
Two of the most important requests for the development of this widget are: **1- Circular progress bar**, **2- Applying color as a gradient** in this widget.

Below are some examples of the development of this widget :
![Untitled-2](https://user-images.githubusercontent.com/77163248/132203856-35f30e34-ad47-4ae8-9fab-a1333c26d807.jpg)

thank you

**Comment by 79ho3ein** [comment]
A very important problem right now is that we can not have multiple progress bars of different colors with one use of the progress bar widget.
So we have to use this widget many times, so we can have different colors.

My suggestion is to add a similar part of the image below to this widget, so that we can add a number of progress bar to a widget. In different colors : 
![Screenshot (139)](https://user-images.githubusercontent.com/77163248/132205153-7e201dd7-8eea-43f0-83ab-a210ec21a88c.png)

Just like the icon list widget to which we can add different items.

**Comment by paauserrat** [comment]
I requested Table and Chart widgets which are similar to this:
https://github.com/elementor/elementor/issues/16137

**Comment by 79ho3ein** [comment]
> I requested Table, Chart and Graphs widgets which are similar to this:
> #16137

excellent

**Comment by LausanneMarketing** [comment]
+1

**Comment by nicholaszein** [comment]
Hello, @79ho3ein!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #1685.

As we are organizing our feature requests to be migrated to the Discussions tab, we are going to close some duplicate issues. This is one of them. 

Feel free to continue the conversation there! 👉

Kind regards
