### ISSUE TITLE
Protect pages and content with user and password in Elementor

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#16277]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need to protect content with password. It's possible to protect a page with password but with a generic one and not user's password. Also, it's not possible to protect content in elementor with email and password

**Describe the solution you'd like**
Ability to set user and password protection like login or generic password for any type of content in elementor. For entire pages, for containers, for forms...

**Describe alternatives you've considered**
Custom code of other plugins

**Additional context**
![image](https://user-images.githubusercontent.com/73240206/132496360-459325d6-3557-4862-92eb-51735f9e60bf.png)

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
