### ISSUE TITLE
Side menu Cart doesn't open automatically when adding product from product page 

### ISSUE THREAD

**Issue by aggrawalmohit** [elementor/elementor#16276]
Steps to repro : 

1 create a side menu cart .
2. Select Auto open when new product added from additional options.
3. Save settings.
4. Go to website and open any product page.
5. Add product to Cart and observe that side menu cart doesn't open automatically.
Note : feature works fine when adding product from any other location ( other than product page )

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
