### ISSUE TITLE
Video playlist lazy load toggle keeps resetting to "no"

### ISSUE THREAD

**Issue by Deadlift79** [elementor/elementor#16274]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In the video playlist widget the lazy load toggle button when switched from "no" to "yes" (lazy loading enabled) keeps resetting itself to no = no lazy loading. 
If I save the page the lazy load option previously enabled is now greyed out. 
Even in the elementor editor in the widget itself changing from "content" to "style" (or elsewhere) lazy load losts its setting. 
I've first noticed it on self hosted videos and I've thought video playlist lazy load acts like the video widget (lazy load only for vimeo/YouTube videos when image placeholder is set) but the same behaviour happens on all video sources with or without image placeholder setted.
## Steps to reproduce

https://user-images.githubusercontent.com/87310457/132424894-5a845d3e-57db-47c7-bfe8-f954e48ad6e0.mp4

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
