### ISSUE TITLE
Menu Widget breakpoint feature optimising 

### ISSUE THREAD

**Issue by metmme** [elementor/elementor#16285]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.** 
Mobile Dropdown i can only use < 1024px and < 767px, it would be ideal if we can add sone custom px.
<img width="1275" alt="Screenshot 2021-09-09 at 11 29 40 AM" src="https://user-images.githubusercontent.com/44073976/132660972-f7877f64-4815-410b-8b33-ca13bb61d344.png">

**Describe the solution you'd like**
Elementor - menu widget - Mobile Dropdown i can only use < 1024px and < 767px, it would be ideal if we can add sone custom px.

**Describe alternatives you've considered**
There is none more

**Additional context**
  
<img width="284" alt="Screenshot 2021-09-09 at 11 24 34 AM" src="https://user-images.githubusercontent.com/44073976/132661044-3b95bdce-d980-4008-88d0-1d915f502660.png">

**Comment by DorShahar** [comment]
Hi @metmme, thank you for reaching out.

The Nav menu widget supports all of your Additional Custom Breakpoints (in case that the Experiment is active).
The custom breakpoint you wish for is doable by changing the value of one (or more) of the breakpoints. 

For example , it might look like the image below:

![image](https://user-images.githubusercontent.com/19154938/132684628-de0543c6-23e8-4d2a-8550-ef143a65769b.png)

Thanks
