### ISSUE TITLE
Form Input Type = Text not showing

### ISSUE THREAD

**Issue by jtdissing** [elementor/elementor#16295]
Elementor is throwing something funny on a cloudways Network website with using the built in Contact form.
 
Collecting the persons name (first, last) -> Input type = text
 
Form shows in the visual editor, but not on the actual page.
It actually doesn't matter the field names, no Input type = Text fields display. The label will, but not the input.
 
 
Doing an inspection of output code, it looks like it's not even rendering as there is no input HTML at all, just the label.
Using latest version of Elementor. Only one site on the network has this problem weirdly enough.

Systeminfo:

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.22
	PHP Max Input Vars: 2500
	PHP Max Post Size: 30M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://betterfootball.eu
	Home URL: https://betterfootball.eu
	WP Multisite: No
	Max Upload Size: 30 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.6.9
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38

== Active Plugins ==
	Advanced Database Cleaner PRO
		Version: 3.1.6
		Author: Younes JFR.

	Astra Bulk Edit
		Version: 1.2.6
		Author: Brainstorm Force

	Astra Pro
		Version: 3.5.9
		Author: Brainstorm Force

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 1.16.6
		Author: Dynamic.ooo

	Elementor
		Version: 3.4.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.1
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 2.3.7
		Author: WebMat

	iThemes Security Pro
		Version: 7.0.3
		Author: iThemes

	JetEngine
		Version: 2.9.2
		Author: Crocoblock

	MainWP Child
		Version: 4.1.7
		Author: MainWP

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.63
		Author: MalCare Security

	OoohBoi Steroids for Elementor
		Version: 1.7.9
		Author: OoohBoi

	PDF viewer for Elementor
		Version: 2.9.3
		Author: RedLettuce Plugins

	Perfmatters
		Version: 1.7.7
		Author: forgemedia

	Post SMTP
		Version: 2.0.23
		Author: Yehuda Hassine

	TranslatePress - Multilingual
		Version: 2.1.1
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	WP Migrate DB Pro
		Version: 2.1.2
		Author: Delicious Brains

	WP Migrate DB Pro Media Files
		Version: 2.0.3
		Author: Delicious Brains

	WP Migrate DB Pro Theme & Plugin Files
		Version: 1.1.2
		Author: Delicious Brains

	WP Rocket
		Version: 3.9.3
		Author: WP Media

	WPvivid Backup MainWP
		Version: 0.9.22
		Author: WPvivid Team

	WPvivid Backup Plugin
		Version: 0.9.61
		Author: WPvivid Team

	WPvivid Imgoptim Free
		Version: 0.9.14
		Author: WPvivid Team

	WPvivid Plugins Pro
		Version: 2.0.24
		Author: wpvivid.com

	WPvivid Staging
		Version: 2.0.3
		Author: wpvivid.com

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Flexible Elementor Panel: Compatibility not specified
	OoohBoi Steroids for Elementor: Compatibility not specified
	PDF viewer for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	header : 1
		heading : 1
		icon : 1
		nav-menu : 1
	popup : 1
		nav-menu : 1
	wp-post : 0
		heading : 5
		image : 1
		text-editor : 3
	wp-page : 8
		button : 4
		divider : 9
		form : 5
		heading : 14
		image : 3
		image-box : 3
		jet-listing-grid : 1
		pdf_viewer : 1
		share-buttons : 2
		shortcode : 1
		star-rating : 1
		text-editor : 5
	jet-listing-items : 0
		heading : 1
		jet-listing-dynamic-image : 1
		share-buttons : 1

== Log ==
	
Log: showing 20 of 352021-08-21 14:02:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '1.16.3',
  'to' => '1.16.4',
)]
2021-08-22 14:02:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '1.16.4',
  'to' => '1.16.5',
)]
2021-08-24 16:03:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.7',
  'to' => '3.3.8',
)]
2021-08-30 22:10:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-30 22:10:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.8',
  'to' => '3.4.0',
)]
2021-08-30 22:10:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.8',
  'to' => '3.4.0',
)]
2021-08-30 22:10:22 [info] elementor::elementor_updater Started 
2021-08-30 22:10:22 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-30 22:10:23 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-30 22:10:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-09-07 16:44:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '1.16.5',
  'to' => '1.16.6',
)]
2021-09-07 16:53:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-09-07 21:52:13 [notice] Re-migrate 3.0.0 globals: Start 
2021-09-07 21:52:13 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2021-09-07 21:52:13 [notice] System typography is disabled. nothing to do. 
2021-09-07 21:52:13 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2021-09-07 21:52:13 [notice] System colors are disabled. nothing to do. 
2021-09-07 21:52:13 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2021-09-07 21:52:13 [notice] Custom colors already exist. nothing to do. 
2021-09-07 21:52:13 [notice] Re-migrate 3.0.0 globals: End 

PHP: showing 7 of 7PHP: 2021-08-23 17:45:16 [notice X 1][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-01 16:16:33 [notice X 3][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::229] Undefined index: field_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-07 17:06:24 [notice X 296][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index:  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-07 17:28:56 [notice X 14][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1114] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-07 19:21:20 [error X 1][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-07 21:52:13 [notice X 1][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-07 22:10:33 [notice X 5][/home/yyyyyyyyy/eyeurppefn/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-base.php::139] Undefined index: inline_list [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by DorShahar** [comment]
Hi @jtdissing 
Please deactivate all of your plugins and look if there is a  plugin conflict that may be the cause of this issue.
If not  - please contact our support so they could investigate this. 

Thanks
