### ISSUE TITLE
Table of Contents --> Icon None --> Bug

### ISSUE THREAD

**Issue by dannyjunkle** [elementor/elementor#16300]
![TableofContents](https://user-images.githubusercontent.com/90502435/132942448-7b3c8b9c-17ce-498c-9dcc-5b56d11170e9.jpg)

**Comment by DorShahar** [comment]
Hi @dannyjunkle 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by dannyjunkle** [comment]
Hi @DorShahar 
this is what the support says:

![Unbenannt](https://user-images.githubusercontent.com/90502435/133557408-4fd43fac-6cf6-4cd0-bb70-d676ac3ebca9.JPG)


I think you can reopen the issue.

Cheers,
Daniel
