### ISSUE TITLE
elementor safe mode issue

### ISSUE THREAD

**Issue by ekta1607** [elementor/elementor#16308]
unable to turn on elementor safe mode issue

**Comment by DorShahar** [comment]
Hi @ekta1607 

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
