### ISSUE TITLE
Ability to display notifications to website users in elementor / Request a new feature.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16315]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be great if you could add a feature so that we can display some important information to website users. This feature is especially needed on e-commerce websites.
Using this feature, we can inform website users about products discount times, website update times and many more.

**The image below is a simulation of this feature :**
![Screenshot-(150)](https://user-images.githubusercontent.com/77163248/132997442-f553b3d9-fa2c-4aa9-ad26-99b9316b542b.jpg)

**Suggestions for how to implement :**

This feature definitely requires a new widget. Using this widget, we can display the desired notifications to users. 
**But how do we send these notifications?** 
My suggestion is to add a new section in this section (as shown below) so that we can use it to type our notifications, and send them to users for display. (Exactly like the submissions section But on the contrary)
![Screenshot-(151)](https://user-images.githubusercontent.com/77163248/132997852-6c58e938-a738-4823-b746-abc18c0cce24.jpg)

This was just a suggestion, there are many ideas to complete it that I will put forward if you approve.

thank you

**Comment by rami-elementor** [comment]
Hi @79ho3ein,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,
