### ISSUE TITLE
⛔ 🐞 Bug Report: Mini Cart Needs To Be Position Aware

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#16324]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Have Elementor cart widget in page navigation, but when the cart is positioned close to the end of the page it overflows. If possible can it be more content-aware to not overflow the body. Gif below:

![GIF 13-09-2021 13-38-31](https://user-images.githubusercontent.com/55829113/133084961-6652eb09-3773-464d-b139-6148684cb6ac.gif)

Theme: Astra

Plugins:
Elementor
Elementor Pro
Astra Pro
Woocommerce
Woocommerce Swatches

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by 79ho3ein** [comment]
+1
It would be great if we could move it manually, left or right. This causes problems with the mini cart position in different situations. Unfortunately, this is not possible at the moment.

**Comment by jazir5** [comment]
This is a huge issue issue for me as well. It basicallly makes it impossible to position the mini cart at the edge of the screen, which is where it's going to be placed 90% of the time.

**Comment by jazir5** [comment]
@avivu

**Comment by perks98** [comment]
@DorShahar @shilo-ey ?

**Comment by avivu** [comment]
Hello @jazir5 and @perks98,

Thank you for your feedback.
At the moment, you can adjust the Mini Cart position on different devices. See attached image.

![image](https://user-images.githubusercontent.com/76733085/133660018-902d9be0-5f03-4275-9069-dbbfac82ba9d.png)

I understand what you are saying and the issue. We will examine it and update you here on the progress.

Thank you!

**Comment by nicholaszein** [comment]
Hi @perks98,

I wanted to give some feedback about this issue.

This feature as @avivu mentioned was deliberately defined to let you choose the position of the cart, and it is even responsive. Which means we don't consider this a bug. You need to choose the position of the mini-cart when styling your Menu Cart widget.

For this reason, I'm closing this issue.

If you think this could be a good enhancement to the Menu Cart widget, please submit a new [Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request) and we will consider it if there are enough votes.

Kind regards
