### ISSUE TITLE
Problem with shopping cart widget (z-index bug)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16333]
hello dear @avivu

I have already explained this bug briefly, but I will explain it in more detail. Please check this bug. Because it has many design limitations.
The problem is that the shopping cart menu has a z-index problem.

My site has a header at the top, and a menu at the bottom (Picture below).
![Screenshot_20210914-130024_Chrome](https://user-images.githubusercontent.com/77163248/133224988-8287451f-a256-4e33-afa0-dcd4f71e06c2.jpg)

I designed the bottom menu in the footer and set it to sticky. **As you can see in the image above, the shopping cart widget is in both the header and the bottom menu.**

**When we click on the shopping cart in the header, it opens and there is no problem.**(Picture below)
![Screenshot_20210914-125321_Chrome](https://user-images.githubusercontent.com/77163248/133225425-6cf31177-cfe8-4e47-b705-4b70892c0055.jpg)

**But when we click on the shopping cart in the bottom menu, it opens, but there is a problem.** The problem is that when we open the shopping cart menu (bottom menu shopping cart), the bottom of the header opens. (Picture below)
![Screenshot_20210914-125312_Chrome](https://user-images.githubusercontent.com/77163248/133226623-5879e2d8-14e9-4f81-a97d-53cafa7ef79b.jpg)

I tried hard to solve this problem but it didn't work. Please check this bug. I checked it on several sites and it was like that.
Prior to this elementor pro update, I was using the power pack plug-in shopping cart widget, and this was not a problem.

Finally, I apologize for raising this issue again. **It should be noted that this request is not a request for a new feature. It is a bug report.**

thank you

**Comment by Azswanepoel** [comment]
This cart widget was not tested very well. It breaks mobile and causes an extra 1 inch of space on the right. The z index screws up anything on the page, as if the cart is always open even when its not. This is when you are using the mini cart instead of side cart. Will have to delete and remove in the mean time. Can share any wesbite and screenshots you need. 

Please TEST the mini cart on mobile, and test the z-index when the mini cart is no open but has items in cart.

**Comment by 79ho3ein** [comment]
thank you @Azswanepoel 
Unfortunately the shopping cart widget has two frustrating bugs. Of course, these two problems exist only in the size of the cell phone. The next bug is in the display of the shopping cart buttons that I mentioned in this issue.
I hope these bugs are fixed as soon as possible. Because it has severely damaged the user interface.

**Comment by avivu** [comment]
Hello @Azswanepoel and @79ho3ein,

We will examine your issues and update you here soon.
Thank you for the information

**Comment by 79ho3ein** [comment]
@avivu , thank you for your attention🙏🏻

**Comment by avivu** [comment]
Hello @79ho3ein,
Can you please attach your system info?

**Comment by 79ho3ein** [comment]
dear @avivu Yes, Sure.
[system-info-geroza.ir-19-09-2021.txt](https://github.com/elementor/elementor/files/7191713/system-info-geroza.ir-19-09-2021.txt)
To better understand the problem, please let me know if you need a video.

**Comment by avivu** [comment]
Thank you @79ho3ein,
I tried to reproduce this issue, but with no success.
I noticed that you are using several 3rd party plugins.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one until you spot the problematic plugin.
 - Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).


And see if the issue persists.

I am waiting for your answer. Thank you!

**Comment by 79ho3ein** [comment]
thank you @avivu
I always use the hello elementor. I disabled all plugins, but the problem persists. I am very worried about this. So, once again, I will explain the problem in full in the form of a video. I hope it is clear what the problem is.

The site is designed as follows :
On this website (on mobile, of course), there is a header and a bottom navigation. The bottom navigation option is designed in footer theme builder. And in floating mode is set at the bottom. **The shopping cart widget is located in both the header and the bottom navigation.**
When we open the shopping cart menu (in the header), there is no problem with the z-index and it works properly. But the problem is that when we add a product to the cart, at first glance there is only one button (the cart view button) but the checkout button is hidden. **Not actually hidden, but beyond screen size. Appears when we scroll the page.**
**This problem is quite evident in the video below.** (In the video below, I just open the shopping cart menu (in the header)
https://user-images.githubusercontent.com/77163248/133930431-4c00dcc9-a9d9-481b-89be-7f682e748827.mp4

But in the video below, I just open the shopping cart menu (in bottom navigation). **When we open it, there are two problems.**

The first problem is exactly the same problem as displaying the payment button, which was also present in the shopping cart menu (in header).
The second problem is that when the shopping cart menu opens, the header is placed on top of it. Therefore, it makes the product in the cart appear incomplete. This is actually the z-index problem in the title of this issue. **These two problems are quite obvious in the video below.**
(In the video below, I just open the shopping cart menu (bottom navigation) .
https://user-images.githubusercontent.com/77163248/133930693-6a4fdca6-1f3a-4477-ac90-ac6e5a95c659.mp4

Please consider the following when reproducing this issue :
1- Both bugs are only available in mobile size. (Of course I did not test the tablet)
2- The shopping cart menu widget is located in both the header and the bottom navigation.
3- The bottom navigation option is designed in the elementor footer. Hidden on the desktop and floating at the bottom.

**I apologize for the lengthy explanation. I did my best to report the bugs exactly. I hope it was useful.**

Thank you for your efforts🌹🌹🌹

**Comment by 79ho3ein** [comment]
Hello @avivu , good time!
As you can see in the video above, the problem of displaying the payment button is very obvious after opening the shopping cart menu.
Please watch the video below if possible.

https://user-images.githubusercontent.com/77163248/135169775-1928e0f0-5d86-42af-b0bd-eae6f5375ff5.mp4

The video below is the Woodmart template shopping cart widget, which once opened, the payment button will not be hidden under any circumstances, after scrolling. And it is designed so that it never leaves the screen.
I hope I have described the problem well. This has misled many customers. Because first, after opening the shopping cart menu, the payment button is off the screen. The user has to scroll a bit to make the button appear.
**Please note that this problem only exists on tablets and mobile phones.**

**Comment by avivu** [comment]
Hello @79ho3ein,
Thank you again for the information and videos.
We are examining the issue and ways to solve the problem.

Thank you!

**Comment by 79ho3ein** [comment]
Thank you very much @avivu🙏🏻

**Comment by 79ho3ein** [comment]
hello @avivu, I'm sorry to bother you again...
Did you Need more explanation about these two bugs? I do not know if other users reported it to you or not, but these two bugs are present in all of my websites as well as those of my colleagues. And it's very annoying for website users.
Is there any hope that these issues will be resolved in version 3.6? Because they are really simple bugs. If I can help, I will be happy to serve you. thank you

**Comment by avivu** [comment]
Hello @79ho3ein,
You are not bothering me at all - כeel free to ask.
We are working on several fixes regarding the Menu Cart widget and I believe that they will be part of Pro 3.6.0.
We will add a comment on this thred when relevant.
Thank you!

**Comment by 79ho3ein** [comment]
You are wonderful @avivu . Thank you🌹

**Comment by Azswanepoel** [comment]
The shopping cart widget, on safari and chrome when in the menu, it
sometimes is in a state of dark. A dark square overlaps the widget
completely and it looks just like a block. It is hard to replicate, maybe
it's when cache is in play with rankmath or a cdn.

I have removed the widget for this reason, it was a nice idea but too many
bugs to use on professional website. Hope the next release would address
the issues.

If there if anyway I can submit screenshots or beta test or help in anyway
please let me know. I'd really like to help get this flushed out.

Alec

**Comment by 79ho3ein** [comment]
Hello @Azswanepoel, Yes, this widget is really great and needed.  But there are drawbacks that developers are definitely aware of.
I think it would be better for you to describe the bugs here so that we can help the developers in this way.

Thank you

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!
