### ISSUE TITLE
✅ 🚀 Feature Request: Change Vimeo background-video "transparent" settings to true on /handlers/section/background-vimeo.js - [ED-8469]

### ISSUE THREAD

**Issue by gardenbaum** [elementor/elementor#16336]
https://github.com/elementor/elementor/blob/e0f0db16123c2e9fa5854bb825844c399adf90c4/assets/dev/js/frontend/handlers/section/background-video.js#L105

**Comment by gardenbaum** [comment]
The YT Video Background works fine. If i use a Vimeo Video i get a Black Screen on loading. A Fallback Image won't help because the Vimeo Video loads a Black Background first.

**Comment by mattmckenny** [comment]
+1 We're experiencing the same problem and I 100% agree with the proposed change to set transparent "false" by default.

**Comment by mbaierl** [comment]
@nicholaszein This is open since a year, any chance to fix this?

**Comment by nicholaszein** [comment]
Hello @mbaierl,

thanks for bringing this to my attention. 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon. I will add this to my list of little things that are nice to have and see if the team can give it some care.

Best regards

**Comment by mbaierl** [comment]
Hi @nicholaszein - thanks for your response. 
After further investigating I think this is a bug in Elementor.
In case the background fallback image is set and transparent=1 (the VIMEO default) the background image is shown and as soon as the video is ready it starts playing without any visual issues.
In Elementor's case it's set to transparent=0 (not the VIMEO default), so the background image is shown, then a few seconds a black frame, and then the video starts playing.
To me this clearly is a bug and defeats the whole purpose of setting a video fallback image in Elementor at all.

What's Elementors reason of setting a black background versus a transparent one? Can you please elaborate?

Michael

**Comment by rob1998** [comment]
Why not just change this line to true?
https://github.com/elementor/elementor/blob/109d3406a185bef096c3521805848ccaed759ab2/assets/dev/js/frontend/handlers/background-video.js#L104

**Comment by blockmonkey** [comment]
I'm running into this same issue. Looking for a solution.

**Comment by nicholaszein** [comment]
Hello guys!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
