### ISSUE TITLE
Ability to properly preview responsive show/hidden states

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#16348]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I'd like to see an actual preview of what a layout looks like with hidden/shown items set via this feature:

<img width="406" alt="CleanShot 2021-09-16 at 10 55 57@2x" src="https://user-images.githubusercontent.com/1435638/133534644-513cbec8-03af-45b6-8e81-6bf30a0ff755.png">

Perhaps under these toggles, there could be a checkbox like "Preview show/hide states [  ]" that will let you quickly see what the finished results are like within the editor. There could also be some sort of global indicator in the editor to let users know that it's turned on.

This is handy in cases where you're laying out a menu system / header layout, and you want to hide certain things like a long button, so that the section height doesn't push downward for mobile. Currently, the element is only shaded out in the editor, but it still occupies space, and that makes it more difficult to fully visualise how a mobile menu layout might look.

**Comment by DorShahar** [comment]
Hi @drawcard 
You can!
Go to the hamburger icon on the upper left side > User Preferences > Responsive Preview > Hidden elements and set the toggle to hide.

Thanks
![hidden_elements](https://user-images.githubusercontent.com/19154938/133917031-1a334b1f-d88a-4a2f-b4c7-a6b1bd9d955a.png)
