### ISSUE TITLE
smooth scroll in elementor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16362]
Please add smooth scroll to elementor. That's great.
Is there a plan to add this feature? 
There is a plugin for this feature in the WordPress repository, but it slows down the site drastically. It would be great if this feature was added to elementor.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #14765, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
