### ISSUE TITLE
Validation Error closing </a> before </div>

### ISSUE THREAD

**Issue by kornwaikas** [elementor/elementor#16368]
I am trying to validate the code with W3C standards i am seeing that validator are not closing well the labels.

I have a Image with link to "Custom Url"

the code: 
`<a href="LINKURL"><div class="elementor-image"><img src="IMAGEURL.png" width="XXX" height="XXX" alt="alternativetext" class="elementor-animation-pulse-shrink" /></a></div>   `

I think that the code must be this to validate with standards (closing "div" before "a" label)
`<a href="LINKURL"><div class="elementor-image"><img src="IMAGEURL.png" width="XXX" height="XXX" alt="alternativetext" class="elementor-animation-pulse-shrink" /></div></a>`

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rami-elementor** [comment]
Hi @kornwaikas 

What widget are you using in this area with the validation error? Is it a simple image widget or some other widget?

**Comment by rami-elementor** [comment]
No response. Probably fixed. Closing the issue.
