### ISSUE TITLE
Js Loading Error

### ISSUE THREAD

**Issue by aralshimi** [elementor/elementor#16360]
I have this issue on my home page: [www.aralshimi.com](https://www.aralshimi.com/). I need to solve it ASAP. could you please check it for me.

Uncaught ReferenceError: wpshNumIgnore is not defined
    at <anonymous>:2:1
    at (index):3
    at new Promise (<anonymous>)
    at RocketLazyLoadScripts._transformScript ((index):3)
    at async RocketLazyLoadScripts._loadScriptsFromList ((index):3)
    at async RocketLazyLoadScripts._loadEverythingNow ((index):3)
stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-162783074-1&cid=1571287274.1632038649&jid=608970712&gjid=1215717248&_gid=1856364516.1632038649&_u=YEBAAUAAAAAAAC~&z=1746192904:1 Failed to load resource: net::ERR_TIMED_OUT
rbtools.min.js?ver=6.5.4:21 [Violation] 'requestAnimationFrame' handler took 114ms

![Error js](https://user-images.githubusercontent.com/78299815/133920951-060e894d-2684-45a6-86bc-bcf8a0b8f334.JPG)

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
