### ISSUE TITLE
Custom visibility for sections and any element

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#16371]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's not possible to show or hide some sections or blocks only using elementor.

**Describe the solution you'd like**
A new addition into advanced tab, for example. This should allow us to activate or deactivate the section depending on if user is logged in, role, hour, post...
It would be perfect to be able to create fallback templates and allow us to set a fallback template so we can determine if the user will see nothing or a hide message that encorages him to login or to buy something.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
