### ISSUE TITLE
Database Updater Still Has Critical Error Message

### ISSUE THREAD

**Issue by NickT87** [elementor/elementor#16376]
This issue has been resolved in Elementor v3.4.4

Feel free to update

Thanks!

_Originally posted by @shilo-ey in https://github.com/elementor/elementor/issues/16100#issuecomment-918334583_

**Comment by NickT87** [comment]
**THIS HAS NOT BEEN FIXED!!!**

Roll back to version 3.3.0 Elementor Data Uploader goes.

Update Elementor and Data Uploader returns and causes fatal errors.

This is with all plugins disabled except for Elementor & Elementor Pro

**Comment by Aviad-Herman** [comment]
Hey @NickT87 ,
It is possible that in certain unique configurations the data updater still fails.
We would like to fix this, of course.

If you are willing to help, please send a loom video of you reproducing the bug and send us your system info.

Thanks!

**Comment by NickT87** [comment]
Hi there: screencast: https://screencast-o-matic.com/watch/crQOFwV6g65

`					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.24
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://staging23.swingrz.co.uk
	Home URL: https://staging23.swingrz.co.uk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: REIGN Child
	Version: 3.0.0
	Author: Wbcom Designs
	Child Theme: Yes
	Parent Theme Name: REIGN
	Parent Theme Version: 5.8.3
	Parent Theme Author: Wbcom Designs

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Edg/94.0.992.31

== Active Plugins ==
	(BuddyDev) BuddyPress Poke
		Version: 1.1.2
		Author: Anu Sharma

	Age Verification
		Version: 2.6
		Author: Devio Digital

	Akismet Anti-Spam
		Version: 4.1.12
		Author: Automattic

	AyeCode Connect
		Version: 1.2.7
		Author: AyeCode

	BP Better Messages (Premium)
		Version: 1.9.9.37
		Author: WordPlus

	BP Profile Search
		Version: 5.4.3
		Author: Andrea Tarantini

	BuddyDev Dashboard
		Version: 1.0.4
		Author: BuddyDev.com

	BuddyPress
		Version: 9.1.1
		Author: The BuddyPress Community

	BuddyPress Follow
		Version: 1.3-alpha
		Author: Andy Peatling, r-a-y

	BuddyPress Global Search
		Version: 1.2.1
		Author: BuddyBoss

	BuddyPress Hashtags
		Version: 2.5.0
		Author: wbcomdesigns

	BuddyPress Member Blog
		Version: 1.2.0
		Author: Wbcom Designs

	BuddyPress Member Types Pro
		Version: 1.4.8
		Author: BuddyDev

	BuddyPress Moderation Pro
		Version: 3.1.0
		Author: wbcomdesigns

	BuddyPress Modify Member Directory/Header
		Version: 1.4.0
		Author: Wbcom Designs

	BuddyPress Notifications Widget
		Version: 1.3.2
		Author: BuddyDev

	BuddyPress Private Community Pro
		Version: 2.1.0
		Author: wbcomdesigns

	BuddyPress Profile Completion
		Version: 1.0.8
		Author: BuddyDev

	BuddyPress Quotes
		Version: 1.8.0
		Author: wbcomdesigns

	BuddyPress Reactions and Status
		Version: 1.8.0
		Author: wbcomdesigns

	BuddyPress Xprofile Custom Field Types
		Version: 1.2.0
		Author: BuddyDev

	Classic Widgets
		Version: 0.2
		Author: WordPress Contributors

	Colorlib Login Customizer
		Version: 1.3.0
		Author: Colorlib

	Elementor
		Version: 3.4.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.1
		Author: Elementor.com

	GDPR Cookie Consent
		Version: 2.0.5
		Author: WebToffee

	GeoDirectory
		Version: 2.1.1.3
		Author: AyeCode Ltd

	GeoDirectory Advanced Search Filters
		Version: 2.1.0.8
		Author: AyeCode Ltd

	GeoDirectory Custom Post Types
		Version: 2.1.0.4
		Author: AyeCode Ltd

	GeoDirectory Location Manager
		Version: 2.1.0.15
		Author: AyeCode Ltd

	GeoDirectory Re-Captcha
		Version: 2.1.0.1
		Author: AyeCode Ltd

	GEO my WP
		Version: 3.7.1
		Author: Eyal Fitoussi

	GMW Add-on - BP Xprofile Geolocation
		Version: 1.6.0.1
		Author: Eyal Fitoussi

	GMW Add-on - Buddypress Members Directory Geolocation
		Version: 1.5.6
		Author: Eyal Fitoussi

	LoginWP (Formerly Peter's Login Redirect)
		Version: 3.0.0.2
		Author: LoginWP Team

	Ninja Forms
		Version: 3.5.8.2
		Author: Saturday Drive

	Paid Memberships Pro
		Version: 2.6.2
		Author: Stranger Studios

	Premium Addons for Elementor
		Version: 4.5.5
		Author: Leap13

	Premium Addons PRO
		Version: 2.5.2
		Author: Leap13

	Really Simple SSL
		Version: 5.1.0
		Author: Really Simple Plugins

	rtMedia Custom Attributes
		Version: 1.2.9
		Author: rtCamp

	rtMedia for WordPress, BuddyPress and bbPress
		Version: 4.6.6
		Author: rtCamp

	rtMedia Membership
		Version: 2.2.4
		Author: rtCamp

	rtMedia Sorting
		Version: 1.2.0
		Author: rtCamp

	Screets Live Chat
		Version: 2.9.5
		Author: Screets

	User Role Editor
		Version: 4.60.2
		Author: Vladimir Garagulya

	Verified Member for BuddyPress
		Version: 1.2.1
		Author: Themosaurus

	W3 Total Cache
		Version: 2.1.8
		Author: BoldGrid

	Wbcom Designs - Buddypress Member Profile Views
		Version: 1.0.0
		Author: Wbcom Designs<admin@wbcomdesigns.com>

	Wbcom Designs - BuddyPress Member Reviews
		Version: 2.5.0
		Author: Wbcom Designs

	Wbcom Essential
		Version: 3.4.1
		Author: Wbcom Designs

	WP-Discourse
		Version: 2.3.0
		Author: Discourse

	WP Discourse Shortcodes
		Version: 0.24
		Author: scossar

	WP Easy Updates
		Version: 1.1.18
		Author: AyeCode Ltd

	WP Event Manager
		Version: 3.1.22
		Author: WP Event Manager

	WP HTML Mail - Email Template Designer
		Version: 3.0.9
		Author: Hannes Etzelstorfer // codemiq

	WP Mail SMTP Pro
		Version: 3.0.2
		Author: WPForms


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	wp-page : 17
		premium-addon-blog : 1


== Log ==
	
Log: showing 20 of 402021-09-26 17:37:25 [info] elementor::elementor_updater Started 
2021-09-26 17:37:25 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 17:42:47 [info] elementor::elementor_updater Started 
2021-09-26 17:42:47 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 17:46:06 [info] elementor::elementor_updater Started 
2021-09-26 17:46:06 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 17:59:30 [info] elementor::elementor_updater Started 
2021-09-26 17:59:30 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 18:01:26 [info] elementor::elementor_updater Started 
2021-09-26 18:01:26 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 18:20:56 [info] elementor::elementor_updater Started 
2021-09-26 18:20:56 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 18:26:55 [info] elementor::elementor_updater Started 
2021-09-26 18:26:55 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 18:28:52 [info] elementor::elementor_updater Started 
2021-09-26 18:28:52 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 18:30:55 [info] elementor::elementor_updater Started 
2021-09-26 18:30:55 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-26 18:32:55 [info] elementor::elementor_updater Started 
2021-09-26 18:32:55 [info] Elementor/Upgrades - _on_each_version Start  

PHP: showing 2 of 2PHP: 2021-09-26 18:26:55 [error X 2][/home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/core/base/document.php(857): Elementor\Elements_Manager->create_element_instance(Array)
#1 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(461): Elementor\Core\Base\Document->get_elements_raw_data(Array, false)
#2 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/modules/usage/module.php(567): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(Array)
#3 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/modules/usage/module.php(181): Elementor\Modules\Usage\Module->save_document_usage(Object(ElementorPro\Modules\ThemeBuilder\Documents\Sec [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-26 18:30:56 [error X 1][/home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/core/base/document.php(857): Elementor\Elements_Manager->create_element_instance(Array)
#1 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/modules/usage/module.php(567): Elementor\Core\Base\Document->get_elements_raw_data(Array)
#2 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/modules/usage/module.php(181): Elementor\Modules\Usage\Module->save_document_usage(Object(Elementor\Modules\Library\Documents\Section))
#3 /home/customer/www/staging23.swingrz.co.uk/public_html/wp-content/plugins/elementor/modules/usage/module.php(293): Elementor\Modules\Usage\Module->after_document_save(Object(Elementor\Modules\Library\Documents\Section))
#4 /home/customer/www/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


Feel free to email me & ill send you login credentials :)
nicktomlinson87@gmail.com				`

**Comment by Aviad-Herman** [comment]
@NickT87 
Perfect, thanks!
I see you are using buddypress, this is something we see in a lot of tickets.
Turns out buddypress saves data in our DB tables in serialized syntax and we didn't address this properly in a specific data updater script in a certain elementor version, your specific case is even more unique so we didn't catch it in the last fix.

I believe the fastest way to resolve this is to contact Elementor support and they will manually fix the corrupted value in the DB and run the updater. This will be faster than waiting for an additional fix.

So can you please open a support ticket? In parallel I will forward your email address to the relevant professionals and ask them to contact you.

**Comment by NickT87** [comment]
Thank you, i have opened up a support ticket :)

**Comment by black-eye** [comment]
I've got the same problem on last Dev Edition. 

No need to screencast the video - simply after a click on the button here:

![obrazek](https://user-images.githubusercontent.com/5634870/134959546-622b84b5-269d-4d49-9db5-7cf46357da5d.png)

I receive this error:

![obrazek](https://user-images.githubusercontent.com/5634870/134959729-d44e576b-f686-4dfe-b037-81e87064198c.png)


<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: Debian 9.13 v5.6.49-89.0
	PHP Version: 7.2.34-4+0~20201018.51+debian9~1.gbpc553f7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://www.blackeye.cz/report
	Home URL: https://www.blackeye.cz/report
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Debug Mode: Active

== Theme ==
	Name: re-port WPBF
	Version: 1.0.0
	Author: Petr Jandák
	Child Theme: Yes
	Parent Theme Name: Page Builder Framework
	Parent Theme Version: 2.6.22
	Parent Theme Author: David Vongries

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

== Active Plugins ==
	Admin Menu Editor
		Version: 1.9.10
		Author: Janis Elsts

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Caldera Forms
		Version: 1.9.4
		Author: Caldera Forms

	Central Color Palette
		Version: 1.15.5
		Author: Daniel Menzies

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Clean Image Filenames
		Version: 1.3
		Author: Upperdog

	Disable Comments
		Version: 2.2.1
		Author: WPDeveloper

	Elementor
		Version: 3.5.0-dev29
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.0-dev9
		Author: Elementor.com

	Extras for Elementor
		Version: 2.2.51
		Author: Namogo

	HappyFiles Pro
		Version: 1.5.1
		Author: Codeer

	Intuitive Custom Post Order
		Version: 3.1.3
		Author: hijiri

	iThemes Security
		Version: 8.0.2
		Author: iThemes

	Lightbox with PhotoSwipe
		Version: 3.2.2
		Author: Arno Welzel

	Nested Pages
		Version: 3.1.16
		Author: Kyle Phillips

	Page Builder Framework Premium Addon
		Version: 2.7.5
		Author: David Vongries

	SEOPress
		Version: 5.1.0
		Author: SEOPress

	ShortPixel Image Optimizer
		Version: 4.22.5
		Author: ShortPixel

	Simple History
		Version: 2.42.0
		Author: Pär Thernström

	SVG Support
		Version: 2.3.19
		Author: Benbodhi

	WPvivid Backup Plugin
		Version: 0.9.62
		Author: WPvivid Team

	WPvivid Plugins Pro
		Version: 2.0.25
		Author: wpvivid.com

	Yoast Duplicate Post
		Version: 4.1.2
		Author: Enrico Battocchi & Team Yoast

	Zalomení
		Version: 1.4.7
		Author: Honza Skypala


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Extras for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	


== Log ==
	
Log: showing 20 of 392021-09-10 12:41:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev20',
  'to' => '3.5.0-dev21',
)]
2021-09-13 13:28:55 [info] elementor::elementor_updater Started 
2021-09-13 13:28:55 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-13 13:28:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev21',
  'to' => '3.5.0-dev23',
)]
2021-09-13 13:28:56 [info] Elementor/Upgrades - _on_each_version Finished 
2021-09-13 13:28:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev21',
  'to' => '3.5.0-dev23',
)]
2021-09-19 23:22:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev23',
  'to' => '3.5.0-dev28',
)]
2021-09-19 23:22:23 [info] elementor::elementor_updater Started 
2021-09-19 23:22:23 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-19 23:22:24 [info] Elementor/Upgrades - _on_each_version Finished 
2021-09-19 23:22:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev23',
  'to' => '3.5.0-dev28',
)]
2021-09-19 23:22:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev23',
  'to' => '3.5.0-dev28',
)]
2021-09-22 14:14:26 [info] elementor::elementor_updater Started 
2021-09-22 14:14:26 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-22 14:15:32 [info] elementor::elementor_updater Started 
2021-09-22 14:15:32 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-22 14:16:52 [info] elementor::elementor_updater Started 
2021-09-22 14:16:52 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-27 19:44:55 [info] elementor::elementor_updater Started 
2021-09-27 19:44:55 [info] Elementor/Upgrades - _on_each_version Start  

PHP: showing 3 of 3PHP: 2021-09-06 19:39:30 [notice X 3][/jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-22 14:14:27 [error X 4][/jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/modules/default-values/module.php::94] Uncaught TypeError: Argument 1 passed to Elementor\Modules\DefaultValues\Module::prepare_default_data_for_update() must be of the type array, null given, called in /jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/modules/default-values/module.php on line 66 and defined in /jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/modules/default-values/module.php:94
Stack trace:
#0 /jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/modules/default-values/module.php(66): Elementor\Modules\DefaultValues\Module->prepare_default_data_for_update(NULL, Array)
#1 /jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/modules/default-values/module.php(52): Elementor\Modules\DefaultValues\Module->update_local_control_defaults(Object(Elementor\Widget_Heading), Object(Elementor\Core\Utils\Collection))
#2 /jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/modules/default-values/module.php(112): Elementor\Modules\DefaultValues\Module->update_control_defaults(Object(Element [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-22 21:00:12 [notice X 1][/jail/blackeye/blackeye.cz/report/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by Aviad-Herman** [comment]
@black-eye hey,
thanks for raising this issue! We will check why it happens.
For now, you can turn off the default values experiment and try to run the updater again (you can turn in back on afterwards).

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by Luke-SF** [comment]
Still happening, 

/wp-content/plugins/elementor/includes/managers/elements.php:86inElementor\Elements_Manager::create_element_instance

Call to a member function get_default_args() on array

Wordpress 6.9.4, Elementor Version 4.1.4, Elementor pro 4.1.2.

It does only happen on a specific page.
