### ISSUE TITLE
BUG / sharing buttons in mobile (Size of sharing buttons)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16384]
hello
I do not know exactly why, but the sharing buttons on the mobile are very small. Everything works fine in the elementor editor, but on a mobile phone these buttons are too small.
**Please check this if possible.
Thank you**

**details :**
elementor 3.4.4
elementor pro 3.4.1
theme : New version of Hello Elementor
DOM option is on
Optimize css display is on

**Comment by SteveKinzey** [comment]
My initial thought is when you are editing with Elementor, how does the site look when you switch to responsive mode? If all looks good, I recommend that you view the site in a private window of a web browser. Choose to use the Site Inspector to see the code, then choose the responsive option and when you get it to the width where the buttons are too small, check the CSS. Play with the CSS and notice how the button(s) will change. Find the CSS settings you need, copy them down, return to the template or page in Elementor and insert an @media CSS for the mobile width and using the additional CSS option.

If you want, I would be more than willing to take a look at this for you. Would you please provide the URL for the website?

**Comment by DorShahar** [comment]
Hi @79ho3ein 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.
Without additional information (system info) we cannot investigate.

Thank you for your understanding.
