### ISSUE TITLE
[Suggestion] Page Preloader

### ISSUE THREAD

**Issue by vovkasolovev** [elementor/elementor#16380]
## Prerequisites

- [+] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [+] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Preloader is an interesting element for the site. On the one hand, it is a technical possibility to show that the site is loading. On the other hand, it is a way to brand the entire screen, show the logo effectively, and a decent excuse to add animation before displaying the page. Preloader gives you a reason to make a visual impression, so that Preloader is not only needed for heavy pages for technical reasons.

**Describe the solution you'd like**
I suppose the implementation could be just like Popup is now щr specifically be a Popap type. Canvas with customizable appearance and positioning and with a section in which some widgets can be inserted. Only add "until page is fully loaded" as the event to show, with a "minimum show time" setting.

**Additional context**
A Preloader would be a good place to use the Lottie widget.

**Comment by DorShahar** [comment]
Hi @vovkasolovev 
We are currently working on this feature.
I believe that in few weeks, we will be able to release it to our `dev-edition` and it will be officially released in one of the next Pro releases. 

You are welcome to follow our new feature in [Elementor's community hub](https://forum.elementor.com/).
Merging this issue with #10576 for better tracking.

Thanks
