### ISSUE TITLE
Dynamic text, change color according the text

### ISSUE THREAD

**Issue by brevalo123** [elementor/elementor#16399]
Hello,

I have online marketplace and using Elementor Pro.
Also I'm using ACF Pro. 
So, I have custom fields for product condition: new, like new and used.
I want to make it so that when I choose "New", text must be green. It I choose "Like new" text must change to yellow and I choose "Used" then text must appear to be black.

How to make it with Elementor? Do I need other instruments for this?

Thank you in advance.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- **Elementor Community on Facebook**
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

You are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
