### ISSUE TITLE
Popup close on scroll in elementor

### ISSUE THREAD

**Issue by AlebB-fn** [elementor/elementor#16393]
Hello,
It's easy to setup a trigger for popup display, in my case it's On scroll down within 10%. But what I really need is when scrolling back up and reaching that 10% mark, the popup would close.
Thank you.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11899 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
