### ISSUE TITLE
Custom php template of element in theme builder

### ISSUE THREAD

**Issue by cedricDevWP** [elementor/elementor#16392]
Hello,

For a project I am using astra and elementor, in the theme builder I have created several templates for the type “Search result”. I would like to modify for all these templates the html behind so I would like to create a php file which takes the basic content and add what I want.

This is similar to wanting to create a single.php in the child theme to modify that of the parent theme.

However, I cannot figure out how to name this file. I tried search.php but it doesn’t work … Does anyone have an idea?

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- **Elementor Community on Facebook**
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
