### ISSUE TITLE
Elementor with the extension "The events  Calendar"

### ISSUE THREAD

**Issue by marieange31** [elementor/elementor#16396]
Hi everyone,

I use "The events calendar" as extension for my wordpress website. I can't change the structure. I want the content in full-page but I can't do it with Elementor, it's maybe not compatible. Maybe there is another solution to dot it...

My page : https://www.assoartis.com/a-venir/

Thanks a lot. 

![elementor](https://user-images.githubusercontent.com/87612933/134765028-9f623d5a-3d72-4208-b506-4f95a668811c.png)
r.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
