### ISSUE TITLE
Access to the menu

### ISSUE THREAD

**Issue by marieange31** [elementor/elementor#16395]
Hi

I've got an issus with my menu. I did a mistake with the high and now I can't access to "edit article" for the menu. I don't if there is another solution to change the menu or supress because I can't change the high of the page titre and with the version phone, it's totaly offbeat.... My website is : https://www.assoartis.com/

Thanks a lot.
![bug1](https://user-images.githubusercontent.com/87612933/134763858-9d86b695-7e79-4167-aba2-04595b19cbd4.png)
,

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

I didn't fully understand your problem, but you can access different parts of your page using the [Navigator](https://elementor.com/help/navigator/) at the bottom of the panel. 

If you have more questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
