### ISSUE TITLE
🚀 Feature Request: Registration Form widget (Duplicate of #2775, #5184)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16401]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
One of the most important parts of any website is its login and registration form. In elementor, it is possible to design an entry form, but unfortunately there is no registration form.
**This wonderful feature is required. Especially since the possibility of designing a user panel in 2021 will be added to elementor.**

I have a suggestion for this feature that I hope will be useful. Of course, if you decide to add a registration form!
**The suggestion is to remove the login form widget if possible.**And integrate the login and Register form with the elementor form widget.
This is a great feature.
Another part that is required next to the registration form is the possibility of designing a password forgetting form. This will also be possible by using the elementor form.

**Do you have any information about the Action Pack plugin? (https://actions-pack.com/)** This plugin adds the ability to design an login and registration form to the elementor form widget.
It would be great if you could add this feature to elementor.

thank you

**Comment by 79ho3ein** [comment]
Hello @DorShahar. excuse me...
Is this feature on your roadmap? May you inform?

Thank you

**Comment by mehdimoradi1500** [comment]
I am waiting for it since long time a go
+1

**Comment by paauserrat** [comment]
Needed. +1!

**Comment by rami-elementor** [comment]
Please note that Elementor has a built-in **Login** widget which is using the WordPress login form with custom styling options.

**Comment by 79ho3ein** [comment]
@rami-elementor
Yes, but integrating it with the form widget can be great. I suggest you take a look at the action pack plugin. Makes the elementor form much more efficient.
This plugin adds features to the elementor form with which we can create login, registration and password forgetting form. Isn't this wonderful?

**Comment by pauserratgutierrez** [comment]
> Please note that Elementor has a built-in **Login** widget which is using the WordPress login form with custom styling options.

Yep, Elementor has a built-in Login widget. But in my opinion it should be re-mastered offering more features. Will be an awesome feature to make the form widget Login capable, or at least, make the form widget integrate with the Login widget. This will allow more advanced use cases, allowing to not only ask for the email and password, but also to ask for a phone, a profile picture, a custom name or any other thing. Using this method will result in re-thinking the way the login stores and works, backend login entries should be dynamic and created depending on what the form is asking the user to prompt.

It might be difficult to implement, but an amazing feature for elementor users.

**Comment by mehdimoradi1500** [comment]
@pauserratgutierrez and @79ho3ein
+1

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #5184 , which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
