### ISSUE TITLE
Social Share | Event on Click for Analytics

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#16420]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When a social button is clicked we need to execute some script. For example:

When Facebook share button is clicked we need to execute this

```
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
  'event' : 'socialSharing',
  'platform' : 'facebook'
});
```

When LinkedIn is clicked we need to execute this:

```
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
  'event' : 'socialSharing',
  'platform' : 'linkedin'
});
```

And so one...

**Comment by DorShahar** [comment]
Hi @maurocarreraok 
You can use Custom Code to add custom code snippets. 
You can also add [EventClickListnter](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) to execute what you need.

At the moment, we are focusing on other areas in the product. 

Thank you for understanding
