### ISSUE TITLE
Round of luck Widget in elementor 

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16446]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Great if you add the Round of luck widget to elementor. This feature has a tremendous impact on e-commerce. There are currently many plugins for this feature in the WordPress repository. But if this is localized in elementor, it would be great.

The most important requirements for this feature :

1-Full compatibility with WooCommerce
2-display conditions (Display after x scroll value , Display when the user exits the website, Only registered users can use Round of luck.)
3-Each user can use Round of luck x times with one account
4-Complete statistics of the number of users who participated as well as the number of people who won.
5-Coordinate with the elementor form (users must complete the form before using the Round of luck, name and contact number or any other information to be able to use it)
6-Ability to fully customize Round of luck

**Comment by DorShahar** [comment]
Hi @Michaelgimii 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
