### ISSUE TITLE
Elementor bugged in mobine version

### ISSUE THREAD

**Issue by muylder** [elementor/elementor#16453]
The site from the guy im working with broke in the mobile version and I cant find the solution to this error, please, help me!
https://mentordepropositos.com.br/
/\ this is the site

The site gets weird like the photo I'm attaching \/
![WhatsApp Image 2021-10-01 at 21 54 27](https://user-images.githubusercontent.com/65868139/135698766-2413f12f-2e7b-42b9-bfe7-8c3d5dca1e4f.jpeg)

**Comment by muylder** [comment]
im using hello elementor, and elementor free 3.4.4

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
