### ISSUE TITLE
Font awesome icons not showing

### ISSUE THREAD

**Issue by UVLabs** [elementor/elementor#16474]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Description

Font awesome icons do not show up for Elementor widgets. Neither:

```
public function get_icon() {
 return 'fa fa-instagram';
}
```

Nor 

```
public function get_icon() {
 return 'fab fa-instagram';
}
```

Displays the icon. This seem to have stopped working at v3.4.0 but works at v3.3.1

## Steps to reproduce

Test a font awesome 4/5 icon as a widget icon.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ x ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

					
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.49 (Unix) OpenSSL/1.0.2g
	MySQL version: (Ubuntu) v5.7.33
	PHP Version: 7.4.24
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://thick-marmoset.jurassic.ninja
	Home URL: https://thick-marmoset.jurassic.ninja
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

== Active Plugins ==
	Companion Plugin
		Version: 1.18
		Author: Osk

	Elementor
		Version: 3.4.4
		Author: Elementor.com

	Jetpack
		Version: 10.1
		Author: Automattic

	Orbit Fox Companion
		Version: 2.10.8
		Author: Themeisle

	WP Rollback
		Version: 1.7.1
		Author: Impress.org


== Elementor - Compatibility Tag ==
	


== Elements Usage ==
	


== Log ==
	

				
```

**Comment by DorShahar** [comment]
Hi @UVLabs 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by UVLabs** [comment]
@DorShahar Even with just hello theme and the plugin creating the widget the icon doesn't appear, `eicons` show just fine but the font awesome assets doesn't appear to be loaded in the editor, but they are loaded in the page's iframe.

I rolled back to Elementor 3.3.1 and I can see the font-awesome assets loaded, here's a video showing the issue: https://vertis.d.pr/jJDCe3

Did Elementor change something about how to set font awesome icons for widgets? So far I can confirm this issue on two different plugins that create custom widgets and use elementor as the icon

**Comment by murilots** [comment]
Same issue here. 

Temporary fix, add to function.php

`add_action( 'elementor/editor/before_enqueue_scripts', function() {
    wp_enqueue_style( 'font-awesome', plugins_url( '/elementor/assets/lib/font-awesome/css/all.css'), false);
} );`
