### ISSUE TITLE
Select Control order not respected

### ISSUE THREAD

**Issue by Bounty31** [elementor/elementor#1650]
I am creating my own Elementor widget and I found a bug when creating a SELECT type control. It looks like the value=>key order you provide to the "options" array (when creating the control) is not respected when you put keys with dots inside the string.

Steps to reproduce the bug (Example) :
- Open /plugins/elementor/includes/elements/column.php line 400
- Add for example '10.1' => '10.1%' at the beginning of the 'options' array and save
- When you now go to Column->Advanced->Responsive tab, put a Custom Mobile width and then open the Column Width SELECT you will see that 10.1% is added at the end of the select list instead of where you placed it in the code (see screenshot). Looks like adding a dot in the key of the array breaks the order in which it gets printed.

Any way to force the order to be respected?

**Comment by KingYes** [comment]
We know this bug. It's cuz JS order arrays different :(

I think to fix this we need to write other way the `options` value.

**Comment by Bounty31** [comment]
It looks like options is not an Array but an Object type and I know that for some browsers the Object properties order is not respected, I think the best way of doing it is to use an Array because JavaScript respects the Array items order on any browser.

**Comment by KingYes** [comment]
@Bounty31 But if we change this, all widgets need to be replaced to new way..

**Comment by mindpalette** [comment]
I'm fighting with possibly the same issue. I'm creating a select control with a list of pages, where the page ID is the select value and the page name is the label. The pages need to be ordered alphabetically, but the select options are getting auto sorted numerically by ID on output. Only way I've come up with to fix is to add a string to the beginning of the value, like "page:231", and then filtering that back out later (not ideal, but it appears string values are not affected). Is this the same issue, or a different bug?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
