### ISSUE TITLE
Elementor is too buggy

### ISSUE THREAD

**Issue by moonfinex** [elementor/elementor#16509]
Supre buggy and can not preview the site builder. I have been using Phlox theme

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
