### ISSUE TITLE
Google Font Update

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#16516]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Could you please update the Google font library. Many fonts seem to be missing such as "Atkinson Hyperlegible" and many more I have found.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!
