### ISSUE TITLE
✅ 🚀 Feature Request: Ajax pagination (numerical) in Elementor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16512]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
An Ajax pagination is much needed in elementor. Both for the post widget and the product widget. This new feature, along with the existing load more feature, will be excellent and perfect.

Currently, the jet smart filters plugin has a powerful paging widget that can be a great template.

Uploading Untitled Project.mp4…

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

This feature was added to the Loop Grid widget in version 3.17.0.

Thank you for sharing your ideas! 🙏
