### ISSUE TITLE
Columns cannot be divided into 3 equal parts.

### ISSUE THREAD

**Issue by yasinsarigul** [elementor/elementor#16520]
Hello Everyone,

Now I'm going to describe a bug my friend found. this is really silly. but the problem is: elementor cannot divide a partition into 3 equal parts.

I can describe you like this: create a partition and select 3 parts. Then let's give these 3 pieces different colors. now make a copy of this section to understand the origin of the error.

Let's start trading in the second column and you will see the difference.
Now let's resize the columns. Let the first column be 35% and the second column be 35%. Now look at the 3rd column.. what is that 29.33%? :D this is really a ridiculous mistake, it adds up to 99.33%.

please write if there is a solution for this. otherwise i'm calling elementor developers. Elementor has such a bug. Can you please solve this. Screenshot is in the link.

Thanks in advance for everything. We love elementor.

[https://www.hizliresim.com/se4h4gu](url)

**Comment by Aviad-Herman** [comment]
Hey @yasinsarigul,
Hope this helps:
https://www.loom.com/share/ff41d3c605e24ccc8582c5076a13ca56

Let me know if you need any further assistance or if you have feature requests.

**Comment by yasinsarigul** [comment]
but these are predefined columns. so I still can't add columns like 20 20 60, right?
Isn't this an error? actually solvable. :D
