### ISSUE TITLE
[💯] responsive control default values

### ISSUE THREAD

**Issue by so-ali** [elementor/elementor#16536]
I have been facing a problem recently while using the method `add_responsive_control`.
when using the default values in this method, it returns the correct values at the first save but after one time refreshing the page, it does not return any value.
my code:
```
$this->add_responsive_control('space_between',
  [
    'label' => __( 'Spacing', 'test' ),
    'type' => Controls_Manager::SLIDER,
    'range' => [
	    'px' => [
		    'min' => 0,
		    'max' => 100,
	    ],
    ],
    'devices' => [ 'desktop', 'tablet', 'mobile' ],
    'default' => [
	    'size' => 30,
	    'unit' => 'px',
    ],
    'tablet_default' => [
	    'size' => 20,
	    'unit' => 'px',
    ],
    'mobile_default' => [
	    'size' => 10,
	    'unit' => 'px',
    ],
    'selectors' => [
	    '{{WRAPPER}} .widget-image' => 'margin-bottom: {{SIZE}}{{UNIT}};',
    ],
  ]
);
```
first time output when dump $settings variable:
 ```
["space_between"]=>
  array(3) {
    ["unit"]=>
    string(2) "px"
    ["size"]=>
    int(30)
    ["sizes"]=>
    array(0) {
    }
  }
  ["space_between_tablet"]=>
  array(3) {
    ["unit"]=>
    string(2) "px"
    ["size"]=>
    int(20)
    ["sizes"]=>
    array(0) {
    }
  }
  ["space_between_mobile"]=>
  array(3) {
    ["unit"]=>
    string(2) "px"
    ["size"]=>
    int(10)
    ["sizes"]=>
    array(0) {
    }
  }
```
second time (after refreshing page):
`["space_between"]=> array(3) { ["unit"]=> string(2) "px" ["size"]=> int(30) ["sizes"]=> array(0) { } }`

**Comment by thenahidul** [comment]
Were you able to solve it? I'm having the same issue with elementor 3.6.5

**Comment by mapsmarketing** [comment]
Can confirm the exact same issue. The other responsive sizes are not being saved

**Comment by sebcolor** [comment]
Same issue. with elementor 3.16.5. In fact "desktop_default" becomes simply… "default" and issue is solved. the doc should be updated.

**Comment by so-ali** [comment]
I found a resolve, just use frontend_available=>true
