### ISSUE TITLE
Bug with share widget

### ISSUE THREAD

**Issue by ZENwww** [elementor/elementor#16530]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

There is a error with share widget. When I clicked on share button (whatssapp or skype) there is a popup with blank page, additionaly when I share with e-mail in message there was a pure HTML code.

Error in console:

```
share-link.min.js:1 [Deprecation] Resource requests whose URLs contained both removed whitespace (`\n`, `\r`, `\t`) characters and less-than characters (`<`) are blocked. Please remove newlines and encode less-than characters from places like element attribute values in order to load these resources. See https://www.chromestatus.com/feature/5735596811091968 for more details.
h @ share-link.min.js:1
(anonymous) @ share-link.min.js:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
domains.com/:1 
```

## Steps to reproduce

Add share widget to the page and used it on frontend.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by d19dotca** [comment]
Based on that error, it seems like a Chrome-specific issue ("https://www.chromestatus.com/feature/5735596811091968" in message) as the status page shows no indication of similar behaviour in other browsers, but hopefully can still be worked around by the Elementor team for Chrome users.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
