### ISSUE TITLE
Dev Edition: Activate All Experiments & Deactivate All Experiments buttons do not work in Elementor Dev v3.5.0-dev36

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#16531]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description
Navigating to the Elementor > Settings > Experiments tab and hitting either the Activate All Experiments or Deactivate All Experiments do not appear to make any changes. 

Observed behaviour: Buttons do not correctly activate or deactivate all experiments.
Expectation: Buttons correctly activate or deactivate all experiments.

## Steps to reproduce
1. Using Elementor v3.5.0-dev36 and Elementor Pro v3.5.0-dev9, navigate to the Elementor > Settings > Experiments tab.
2. Ensure there is a mix of activated and disabled experiments set.
3. Click the Activate All Experiments button, the page will reload with the same experiments disabled that were prevously disabled when they should now be enabled instead. 
4. Click the Deactivate All Experiments button, the page will reload with the same experiments enabled that were previously enabled when they should now be disabled instead.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Elementor v3.5.0-dev36
Elementor Pro v3.5.0-dev9
Safari 15.1

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
