### ISSUE TITLE
Ability to add to home screen in elementor (website shortcut in user's mobile like an app)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16543]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello
It would be great if you add a feature to elementor, so that the **user can add a shortcut from our website to their mobile home screen with one click.**
I do not mean that elementor will make our website a mobile app for users. It just adds a simple shortcut from our website built with elementor to the user's mobile.
**Currently, the Chrome browser on mobile phones has a similar feature. But it is not complete and of course it can be difficult for users to use. Many users may not be aware of such a feature in the Chrome browser.**
![download](https://user-images.githubusercontent.com/77163248/136757802-2168f970-3004-4267-a726-1a7ebb790915.png)

**But if this feature is added to elementor, what is the difference with this feature in Chrome mobile browser?**

To complete this useful feature in elementor, we need to customize this shortcut in elementor. **This customization only involves changing the image of this shortcut.** Also, the possibility of changing the link of this shortcut can be very useful. For example, I want to direct users directly to my web store using this shortcut. Therefore, I change the shortcut link, which is the home page of the website by default, to the store page. Or to any other page!

**Only one case remains. How can users add our website shortcut to their mobile phone?**
For this purpose, we need to make the button widget dynamic with this feature. So, on our website we ask users, do you want to access our website easier than ever?
If the user clicks the button mentioned above, the website shortcut will be added to the user's mobile phone. With just one click!
Of course, the above message can be displayed to users in a pop-up. After the user clicks on the desired button, the pop-up will be hidden.

I hope I have made my proposal clear. But this feature is great and makes users access the website faster. This will be a big revolution, especially for e-commerce websites built with elementor.

**Comment by rami-elementor** [comment]
Not sure is a feature like this should be part of a page builder. This is a browser feature. You need to ask Chrome / Firefox / Safari developers to develop this kind of feature.

**Comment by 79ho3ein** [comment]
@rami-elementor
This idea is funny for a plugin like Visual Composer. But not for elementor!
Elementor is now much larger than a page builder. We build a powerful store theme with elementor. (by hello elementor).
So developing this feature in elementor can be great. For the reasons I mentioned above. Because this feature makes mobile users much easier to access the website. This feature will increase the sales on a store website.
Because no plugin has implemented it yet. Except on dedicated website.

**Comment by rami-elementor** [comment]
We understand the need. But we can't control the browser fields. Only the browser developers can add this kind of feature.

I'm closing this issue as "Won't Fix" for now.
