### ISSUE TITLE
Template Builder Condition Based on URL Variable

### ISSUE THREAD

**Issue by ParedesCreative** [elementor/elementor#16550]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently there doesn't seem to be a good way to A/B test Archive and Single Product Page templates.

**Describe the solution you'd like**
It would be nice to be able to select a template based on whether there is a variable in the url (e.g.: domain.com/?test=a), which would allow devs to pass the variable via Google Optimize (or another testing tool) and do proper A/B testing on templates. So the condition would look something like this: https://snipboard.io/i7Wxhl.jpg

**Describe alternatives you've considered**
I've asked your customer support team and your Tier 2 representative mentioned explicitly that there is no current way to accomplish this, which is super unfortunate. If there is another way, I am all ears!

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2436, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
