### ISSUE TITLE
Ability to "scrolling progress bar" in elementor / Suggest a new feature(new widget)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16576]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello
The scrolling progress bar feature is excellent and versatile. Adding it to elementor can be great.
This feature requires a new widget. Of course, this feature is present in some elementor add-ons. But I and other users prefer elementor to any other plugin. **So localizing this feature is very exciting!**

This feature does not require any special settings. Settings including :
1- background color
2- color & Gradient color (scrolling progress bar)
3- **heigh**
4- border radious
5- shadow
6- border
7- **Linear and circular mode**
8- smooth percent

The video below is an example of this feature on a website : 
https://user-images.githubusercontent.com/77163248/137205381-56b8c0b3-3f5a-42c8-92ac-46edd089f754.mp4

There is also a more advanced version of this feature in the elementor extras plugin. By scrolling, the name of the desired part is displayed at the same time. (Video right at the bottom👇)
Also in the video below, there is a scrolling progress bar of the circular type that I will mention in the video.
https://user-images.githubusercontent.com/77163248/137208007-6ae06135-78b6-41ad-bbfd-67b983f73ff1.mp4

I hope it was useful
thank you

**Comment by avivu** [comment]
Hello @79ho3ein,
Thank you for your suggestion. It's your lucky day.
In the next release of Pro 3.5.0, we will add a new Progress Tracker widget with most of the features you mentioned above.

If you are using our Elementor Developer plugin, you can see it already in action.

Thank you!

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!

**Comment by 79ho3ein** [comment]
Thank you for your efforts

**Comment by SaltedLevity** [comment]
It would be nice if there was an option to have the tracker not show if the content on the page is under a certain height. I added this to a single template, but realized it was breaking the design on pages that didn't need any scrolling. Alternatively, have it not show until a user scrolls to a certain distance down the page.
