### ISSUE TITLE
Can not import a kit

### ISSUE THREAD

**Issue by bouwemetz** [elementor/elementor#16578]
Trying for many days Kit is not importing

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
