### ISSUE TITLE
Error dispay card

### ISSUE THREAD

**Issue by JacquesBertens** [elementor/elementor#16593]
Error dispay cards on https://loonsfotowerk.nl/fotoblog/

Since the last update there is a problem with displaying cards on the site www.loonsfotowerk.nl. Only a link is displayed but the card image does not appear on the page.  

----
The problem was solved by running an earlier version first. Then run the update again. 
Edit: The problem still exists... 
----

![Schermafbeelding 2021-10-16 120256](https://user-images.githubusercontent.com/80720459/137583400-c0cd7b3c-d036-4e03-8730-d74ec1c67049.png)
	
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.3.24
	PHP Version: 7.4.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://loonsfotowerk.nl
	Home URL: https://loonsfotowerk.nl
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: Europe/Amsterdam
	Admin Email: info@hobbybrouwen.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0

== Active Plugins ==
	Add From Server
		Version: 3.4.5
		Author: Dion Hulse

	Ad Inserter
		Version: 2.7.4
		Author: Igor Funa

	Asset CleanUp: Page Speed Booster
		Version: 1.3.8.4
		Author: Gabe Livan

	CDN Enabler
		Version: 2.0.4
		Author: KeyCDN

	Code Snippets
		Version: 2.14.2
		Author: Code Snippets Pro

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.1.5
		Author: Hu-manity.co

	Elementor
		Version: 3.5.0-dev41
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.4
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.5.0-dev16
		Author: Elementor.com

	FileBird
		Version: 4.9.3
		Author: Ninja Team

	Limit Login Attempts Reloaded
		Version: 2.23.2
		Author: Limit Login Attempts Reloaded

	Post Type Switcher
		Version: 3.2.1
		Author: Triple J Software, Inc.

	Rank Math SEO
		Version: 1.0.74
		Author: Rank Math

	Scheduled Post Trigger
		Version: 3.0
		Author: Jennifer Moss - Moss Web Works

	Site Kit by Google
		Version: 1.43.0
		Author: Google

	TaxoPress Pro
		Version: 3.3.1
		Author: TaxoPress

	The Plus Addons for Elementor
		Version: 5.0.2
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.3
		Author: POSIMYTH

	To Top
		Version: 2.3
		Author: Catch Plugins

	WP Rocket
		Version: 3.10.1
		Author: WP Media

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	installatron_hide_status_test.php
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Niet compatibel
	Elementor Pro: Niet compatibel
	The Plus Addons for Elementor: Niet compatibel
	The Plus Addons for Elementor - Pro: Niet compatibel

== Elementor Pro - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Niet compatibel
	The Plus Addons for Elementor: Niet compatibel
	The Plus Addons for Elementor - Pro: Niet compatibel

== Elements Usage ==
	
	page : 7
		icon-box : 2
		page-title : 2
		spacer : 2
		text-editor : 2
		theme-post-featured-image : 2
		tp-gallery-listout : 2
	widget : 0
		tp-gallery-listout : 1
	wp-post : 414
		facebook-button : 5
		gallery : 2
		icon-box : 67
		menu-anchor : 2
		page-title : 97
		spacer : 96
		text-editor : 97
		theme-post-featured-image : 97
		tp-gallery-listout : 96
		video : 6

== Elementor Experiments ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Font-Awesome inline: Standaard inactief
	Toegang verbeteringen: Actief
	Import export template kit: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	Default to New Theme Builder: Standaard actief
	Hello Theme header & footer: Standaard actief
	Landingspagina's: Actief
	Kleur sampler: Actief
	Beheerder bovenste balk: Standaard actief
	Custom Default Widget Styles: Standaard inactief
	Page Transitions: Standaard actief
	Form Submissions: Standaard actief

== Log ==
	
PHP: showing 1 of 1PHP: 2021-10-06 00:34:35 [notice X 1][/home/u55105p52384/domains/loonsfotowerk.nl/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 422021-10-14 23:30:12 [info] elementor::elementor_updater Started 
2021-10-14 23:30:12 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-14 23:30:13 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-14 23:30:13 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-14 23:30:13 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-14 23:30:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev36',
  'to' => '3.5.0-dev40',
)]
2021-10-14 23:30:14 [info] elementor::elementor_updater Started 
2021-10-14 23:30:14 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-14 23:30:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev36',
  'to' => '3.5.0-dev40',
)]
2021-10-14 23:30:15 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-14 23:30:15 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-14 23:30:15 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-14 23:30:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev36',
  'to' => '3.5.0-dev40',
)]
2021-10-15 16:58:20 [info] elementor::elementor_updater Started 
2021-10-15 16:58:20 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-15 16:58:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev40',
  'to' => '3.5.0-dev41',
)]
2021-10-15 16:58:20 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-15 16:58:20 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-10-15 16:58:20 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-10-15 16:58:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0-dev40',
  'to' => '3.5.0-dev41',
)]

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.5.0

Feel free to update

Thanks!
