### ISSUE TITLE
Color sampler feature development/Ability to extract color code from other sections

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16602]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Unfortunately, at this time, it is only possible to extract the color code of the images. This is very limited.
Please add this feature, so we can extract the color code from the other sections. Other parts such as background colors of sections, widgets and ... (In the elementor editor framework) Just like a Photoshop dropper.
Please remove this restriction

**Comment by shilo-ey** [comment]
Hi @Michaelgimii 

Thank you for sharing this feedback.

Elementor's eyedropper works in a way that allows us to extract the main color values of each element without the need for a 3rd party extension (e.g Chrome extension).

To achieve this feature we had to allow only sampling of the main colors presented in each element as you mentioned:
- Images
- Backgrounds
- Widgets

If you encounter a feature in Elementor that is not extracting colors properly, please update here and we will examine it.

Closing this issue for now.

Thanks!
