### ISSUE TITLE
WEbsite mobile Hamburger menu not responding

### ISSUE THREAD

**Issue by bloggerjoshi2021** [elementor/elementor#16601]
The mobile version of my website http://www.kingswayacademy.in is not being toggled. I thibk there is a javascript issue. I dont know java script . Can someone help?

**Comment by rami-elementor** [comment]
Hi @bloggerjoshi2021 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
