### ISSUE TITLE
Fatal error with new block widgets

### ISSUE THREAD

**Issue by litexservice** [elementor/elementor#16662]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using a sidebar widget for adding a sidebar menu, the pages on which the widget is implemented do not load properly. On first page load after a save/update the only thing that loads is the header elements and the widget, the rest of the dom does not even generate. The following error occurs.

![lg-error-widget](https://user-images.githubusercontent.com/92910518/138239443-766672db-4546-46f3-a242-5b0dcb8f82a9.PNG)

After multiple contacts with Elementor Support we've decided to report this as an issue, because they were unable to sort this out. We've researched both Gits: Elementor and WooCommerce. Found the following:

woocommerce/woocommerce-gutenberg-products-block#4683
woocommerce/woocommerce-gutenberg-products-block#4647
#16187

As you can see Automattic is pointing towards Elementor. The only thing we haven't tried yet is completely disabling the new block widgets and moving back towards old widgets - which we would like to avoid.

## Steps to reproduce

1. Edit a page in Elementor.
2. Add a sidebar widget.
3. Publish the page.
4. Refresh the page on frontend.
5. See the missing elements and fatal errors if WP Debug is on.
6. Refresh the page 2nd time and notice the page is correctly loaded now.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: Ubuntu 18.04 v5.6.49-89.0
	PHP Version: 7.4.23
	PHP Max Input Vars: 9000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: RESTRICTED
	Home URL: RESTRICTED
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Debug Mode: Active

== Theme ==
	Name: Litex Garden
	Version: 1.0.0
	Author: Litex Service
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.3
	Parent Theme Author: Brainstorm Force

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.10
		Author: Delicious Brains

	Astra Pro
		Version: 3.6.0
		Author: Brainstorm Force

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.2
		Author: Elementor.com

	Permalink Manager Lite
		Version: 2.2.14
		Author: Maciej Bis

	SEOPress
		Version: 5.1.0
		Author: SEOPress

	SEOPress PRO
		Version: 5.0.4
		Author: SEOPress

	WooCommerce
		Version: 5.8.0
		Author: Automattic

	WooCommerce Attribute Swatches by Iconic
		Version: 1.3.4.0
		Author: Iconic <support@iconicwp.com>

	WooCommerce Chained Products
		Version: 2.10.0
		Author: StoreApps

	WooCommerce Linked Variations by Iconic
		Version: 1.1.0
		Author: Iconic <info@iconicwp.com>


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilny

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		divider : 4
		heading : 4
		image : 1
		nav-menu : 4
		social-icons : 1
		spacer : 1
		text-editor : 3
	page : 4
		button : 4
		call-to-action : 6
		heading : 18
		icon : 4
		icon-box : 5
		image : 2
		sidebar : 1
		slides : 1
		sp-breadcrumbs : 1
		spacer : 2
		text-editor : 7
		woocommerce-products : 1
	product : 1
		shortcode : 1
		sidebar : 1
		sp-breadcrumbs : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	section : 1
		icon-list : 1
	wp-page : 8
		button : 5
		call-to-action : 6
		heading : 25
		html : 1
		icon : 4
		icon-box : 19
		image : 2
		sidebar : 7
		sp-breadcrumbs : 7
		spacer : 18
		text-editor : 15
		woocommerce-products : 1
	product-archive : 1
		heading : 1
		image : 1
		sidebar : 1
		sp-breadcrumbs : 1
		text-editor : 2
		woocommerce-products : 1

</details>

**Comment by choijun** [comment]
Hi @litexservice 

I have the same problem as you, I tried using your way to fix but unfortunately it didn't work. I found the cause of this problem and you can try this

Open the file wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/RestApi.php and add the code below after line 64 https://i.ibb.co/FHkW9YT/Screenshot-at-Nov-17-01-26-49.png

`if(is_wp_error($namespace_index)){
			return null;
		}`

Also, I reported this problem to WooCommerce  https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-method-wp_errorget_data-4/ and hope they will solve it soon

Have a nice day.
