### ISSUE TITLE
Additional breakpoints and popups issue

### ISSUE THREAD

**Issue by asafmoraz** [elementor/elementor#16680]
When the option of additional breakpoints is activated, control over the size of a pop-up area on mobile devices does not affect. The definition of size is drawn directly from the definition of the desktop. The only solution that I have found is to set the size in CSS using media queries but this is a bug that needs to be resolved.

Thanks.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
