### ISSUE TITLE
Compatibility of Breadcrumbs widget with Rank Math plugin

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16690]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello elementor team !
Unfortunately, elemenetor is not currently compatible with the Rank Math plugin. If we install the Rank Math plugin, we will not have the Breadcrumbs widget in elementor. Please add this compatibility to elementor. it's too important.

thank you

**Comment by rami-elementor** [comment]
Rank Math offers an Elementor integration with custom breadcrumbs widget.

See: https://rankmath.com/blog/elementor-seo/

We won't develop widgets for different plugins, except for the big plugins like WooCommerce and Yoast SEO.
