### ISSUE TITLE
PHP (7.4) error log being filled with warnings. These are fatal errors in PHP 8.

### ISSUE THREAD

**Issue by DownUnder1** [elementor/elementor#16719]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

```
<!-- 
Describe which problem you've encountered. What caused the issue, and what did you expect to happen. Attach screenshots and related links to help us understand the issue in more detail. 

Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action. 
-->
```
My PHP 7.4 error is being filled with warnings which are fatal errors under PHP 8 

PHP Warning:  Illegal offset type in isset or empty in  /public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php on line 61
```
## Steps to reproduce

<!-- 
For bug reports, list all the steps needed to reproduce your issue, so we can replicate it ourselves. 
-->

Simply use Elementor and watch your log file fill!

## Isolating the problem
<!-- MARK COMPLETED ITEMS WITH AN [x] -->
- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.6.51
	PHP Version: 7.4.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://cartooncats.io
	Home URL: https://cartooncats.io
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Cartoon Cats
	Version: 1.0.0
	Author: DownUnder
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.10.2
		Author: Delicious Brains

	Disable Gutenberg
		Version: 2.5.1
		Author: Jeff Starr

	Dynamic Visibility for Elementor
		Version: 4.1.0
		Author: Dynamic.ooo

	Elementor
		Version: 3.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.2
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.0
		Author: ShortPixel

	Nested Pages
		Version: 3.1.16
		Author: Kyle Phillips

	Yoast SEO
		Version: 17.4
		Author: Team Yoast

== Must-Use Plugins ==
	Must Use Plugins Boot Loader
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		heading : 1
		social-icons : 1
	header : 1
		button : 2
		heading : 2
		icon-list : 2
		theme-site-logo : 2
	wp-page : 1
		button : -1
		heading : -1
		html : 3
		icon : 1
		image : 2
		image-box : 5
		media-carousel : 1
		spacer : -2
		text-editor : 5
	single-page : 2
		breadcrumbs : 1
		theme-post-content : 2
		theme-post-title : 1

== Log ==
	
Log: showing 12 of 122021-10-13 09:41:29 [info] elementor::elementor_updater Started 
2021-10-13 09:41:29 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-12 22:41:29 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-12 22:41:29 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-12 22:41:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.4.5',
)]
2021-10-13 09:41:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.4.5',
)]
2021-10-13 02:21:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-10-19 22:45:26 [info] elementor::elementor_updater Started 
2021-10-19 22:45:26 [info] Elementor/Upgrades - _on_each_version Start  
2021-10-19 22:45:26 [info] Elementor/Upgrades - _on_each_version Finished 
2021-10-19 22:45:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.5',
  'to' => '3.4.6',
)]
2021-10-19 22:45:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.5',
  'to' => '3.4.6',
)]

PHP: showing 5 of 5PHP: 2021-10-13 03:03:49 [notice X 51][/home/deficentral/cc.deficentral.app/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-13 19:44:30 [notice X 1871][/home/deficentral/cc.deficentral.app/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::68] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-14 05:40:11 [error X 1][/home/deficentral/cc.deficentral.app/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::285] Uncaught Error: Call to a member function update_meta() on null in /home/deficentral/cc.deficentral.app/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:285
Stack trace:
#0 /home/deficentral/cc.deficentral.app/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(166): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/deficentral/cc.deficentral.app/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/deficentral/cc.deficentral.app/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/deficentral/cc.deficentral.app/wp-includes/class-wp-hook.php(327): WP_Hook [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-17 08:32:23 [warning X 1][/home/deficentral/cc.deficentral.app/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::61] Illegal offset type in isset or empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-17 21:33:55 [notice X 6][/home/deficentral/cc.deficentral.app/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
