### ISSUE TITLE
Unable to add an Inner Section

### ISSUE THREAD

**Issue by duncanplatt** [elementor/elementor#16716]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

## Description
When trying to add an Inner Section, it simply doesn't add it.

## Steps to reproduce
I have tried to add an Inner Section to a section, but nothing happens.
Here is a Loom video of my attempts:
https://www.loom.com/share/bc7f0d0d74114dc3aa586b4e2dc8a6a8

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '38', Revision '3692a61' v5.7.35-38
	PHP Version: 7.4.24
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Orion Theme
	Version: 1.0.1
	Author: BoldOrion
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.4.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.10.2
		Author: Delicious Brains

	Elementor
		Version: 3.5.0-dev45
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0-dev3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 4.9.4
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 4.4.11
		Author: WPDeveloper

	GDPR Cookie Consent
		Version: 2.0.6
		Author: WebToffee

	Give - Donation Plugin
		Version: 2.15.0
		Author: GiveWP

	Give - Donation Upsells for WooCommerce
		Version: 1.2.0
		Author: GiveWP

	Instant Images
		Version: 4.4.0.3
		Author: Darren Cooney

	Jetpack
		Version: 10.2.1
		Author: Automattic

	PowerPack Pro for Elementor
		Version: 2.6.0
		Author: Team IdeaBox - PowerPack Elements

	Printful Integration for WooCommerce
		Version: 2.1.25
		Author: Printful

	WooCommerce
		Version: 5.8.0
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 1.25.19
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 5.7.0
		Author: WooCommerce

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	WPE ElasticPress Autosuggest Logger
		Version: 1.0.0
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 4.1.0
		Author: WP Engine

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Essential Addons for Elementor: Incompatible
	Essential Addons for Elementor - Pro: Incompatible
	PowerPack Pro for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible
	Essential Addons for Elementor - Pro: Incompatible
	PowerPack Pro for Elementor: Incompatible

== Elements Usage ==
	
	footer : 2
		heading : 2
		html : 1
		image : 2
		nav-menu : 1
		social-icons : 1
		text-editor : 3
	header : 1
		image : 1
		nav-menu : 1
		woocommerce-menu-cart : 1
	product : 1
		button : 1
		heading : 2
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	wp-page : 4
		button : 3
		divider : 4
		heading : 6
		html : 1
		image : 1
		pp-woo-products : 2
		text-editor : 4
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
	product-archive : 1
		divider : 1
		pp-woo-products : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active by default
	Font-Awesome Inline: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Custom Default Widget Styles: Inactive by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive by default

== Log ==
	
Log: showing 20 of 432021-10-26 11:07:19 [info] elementor-pro::elementor_pro_updater Started 
2021-10-26 11:07:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-10-26 11:07:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-10-26 11:07:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:07:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:08:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:08:30 [info] elementor-pro::elementor_pro_updater Started 
2021-10-26 11:08:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-10-26 11:08:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-10-26 11:08:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:08:32 [info] elementor-pro::elementor_pro_updater Started 
2021-10-26 11:08:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-10-26 11:08:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-10-26 11:08:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:08:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:08:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
2021-10-26 11:08:34 [info] elementor-pro::elementor_pro_updater Started 
2021-10-26 11:08:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-10-26 11:08:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-10-26 11:08:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev2',
  'to' => '3.6.0-dev3',
)]
</details>

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
