### ISSUE TITLE
The Nav Menu widget of Elementor is inserting two drop-downs (line as well as filled). It should display only one.

### ISSUE THREAD

**Issue by Scrupulicous** [elementor/elementor#16721]
The Nav Menu widget of Elementor is inserting two drop-downs (line as well as filled). It should display only one. Please refer to the screenshot below:

![Screen Shot 2021-10-27 at 3 42 24 AM](https://user-images.githubusercontent.com/17683781/139022192-ce4a3c3e-b752-45dd-8ac4-264aadb5c924.png)

**Comment by 79ho3ein** [comment]
I experience this problem in elementor dev

**Comment by rami-elementor** [comment]
@Scrupulicous @79ho3ein @heypopto 

Is this issue still relevant with the latest version of Elementor? 

If so, can you provide us system info?

**Comment by 79ho3ein** [comment]
@rami-elementor , For me, everything works fine.

elementor 3.5.5
elementor pro 3.6.1
wordpress 5.9
hello elementor 2.5.0
