### ISSUE TITLE
Can't remove scrollbar from elementor calendar on mobile view

### ISSUE THREAD

**Issue by Azertooth** [elementor/elementor#16734]
I want to remove [this](https://i.postimg.cc/SxbnjZ16/immagine.png) scrollbar, extending the addon through the bottom, to show the full calendar without scrolling. I tried with every addon margin but without success

**Comment by rami-elementor** [comment]
@Azertooth Which widget are you using? Is this a default Elementor widgets?

**Comment by Azertooth** [comment]
Hi @rami-elementor, thank you for joining the conversation. My bad, it's a widget external to elementor, this is not the place where to ask for help, sorry
