### ISSUE TITLE
Lazy load for image widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16753]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Please add the lazy load activation check box to the image widget. It will be great

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

When you add the Image widget, the `loading="lazy"` attribute is added automatically by default on the frontend.

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
