### ISSUE TITLE
Content reflow/image reflow

### ISSUE THREAD

**Issue by Hsharma9643** [elementor/elementor#16758]
elementor page isn’t performing same page jump (hyperlink) to different sections as expected. 

Especially on mobile device- it gets past the section. 

Help to fix the issue. 

Example page: https://www.adschoolmaster.com/seo-course/what-is-seo/

<!--  ## BEFORE POSTING YOUR ISSUE

- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at https://developers.elementor.com/

===== Guidelines ====

- Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.
- Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to WordPress TwentySixteen (or

**Comment by Vossha** [comment]
Do you use lazy loading for images? Seems on my end lazy loading might be the issue as the page keeps jumping after I selected a topic to jump to. 

_See 'Why does it happen?' in Anchor navigation scrolls to wrong position: https://docs.wp-rocket.me/article/997-anchor-navigation-scrolls-to-wrong-position_

**Comment by Hsharma9643** [comment]
Thanks for the response Vossha. 

Yes, I get it.. it must be happening because of image lazy loading. 

I want to use lazy loading to make loading faster. 

Is there any alternate solution to it? 

Any plugin that can help block the content reflow? 

Or in any way can I stop image lazy loading on the specific page?

I am using SiteGround Optimizer.

Thanks again:)

**Comment by Vossha** [comment]
I don't know about other alternate solutions but you should be able to exclude lazy loading on certain pages, etc.. I would search the plugin documentation or contact their support for help with this. Glad I could help :)

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
