### ISSUE TITLE
custom code - conditions - failed to fetch

### ISSUE THREAD

**Issue by marketingspectrumNL** [elementor/elementor#16779]
Elementor Pro - custom code feature.

Trying to add a Google Ads tag script to the < head >. 
When setting a condition I get a 'Failed to fetch' message. 
The learn more link goes to https://elementor.com/help/elementors-theme-builder/
So that isn't giving any help either.

I did the same thing on another site the other day and that worked fine.
It is a different hosting service, so I'm expecting something there. But I can't troubleshoot it sadly enough.
Happens in Elementor pro 3.5.0 and the previous version.

[1] setting condition (with ads code in background)
![image](https://user-images.githubusercontent.com/59880703/139726955-6450bc5c-dc56-4915-97ca-f960712cda6f.png)

[2] Failed to fetch Error.
![image](https://user-images.githubusercontent.com/59880703/139726653-5e03b931-a823-400c-b057-4820f5cc04a1.png)

**Comment by AntonMett** [comment]
I am trying to use theme builder, gives me same result as I try to trash template or modify conditions...

**Comment by Carl0s1z** [comment]
Got the same problem when adding Custom code to the Head and trying to set some conditions. 
Just updated the plug-in to:
- Elementor - 3.5.2 
- Elementor Pro - 3.5.2

**Comment by jenyafross** [comment]
I have faced the same issue on our servers and the reason was a disallowed PUT method in the web server configs that Elementor uses to set conditions.

**Comment by Carl0s1z** [comment]
I found a fix to, by adding the method to DirectAdmin. Restart services and it worked like a charm again.

**Comment by rami-elementor** [comment]
> I found a fix to, by adding the method to DirectAdmin. Restart services and it worked like a charm again.

Not an Elementor issues, this is a server issue.

**Comment by NASSERABDELLAH** [comment]
If you are having hosting or server difficulties using Elementor, we’ve included a simple switch that may solve your issue.

To use it, go to Elementor > Settings > Advanced, and under ‘Editor Loader’, enable ‘Switch front-end editor loader method’.

**Comment by ahahahaaaa** [comment]
> I have faced the same issue on our servers and the reason was a disallowed PUT method in the web server configs that Elementor uses to set conditions.

Tks you ! it still right now.
