### ISSUE TITLE
Variables Selection Widget (Colour swatches) on Single Product Page / New Widget / WooCommerce

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16770]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello dear @avivu , Please review these items if possible. Thank you

One of the most important features that is used in many store sites today is the Color swatches feature. Unfortunately, so far no attention has been paid to it in elementor. **Before continuing the explanation, please see the following gif :**
![132317893-c90719b0-1dbb-4cf9-980c-542dcf1a7aa6](https://user-images.githubusercontent.com/77163248/139602705-48c61964-569e-43c5-befb-f747fcdf08fb.gif)

As you can see above, the user chooses the desired color as well as the desired size. very beautiful !
This feature is extremely useful as well as essential. **It is noteworthy that by selecting the variables (color and size), the price is updated in Ajax at the same time.** The user can also delete the colors of the variables she has selected to return to the default state.
You, dear developers, are definitely aware of this wonderful feature. If you decide to add this feature, I suggest you consider a **new widget** for this feature. This is very logical and excellent.
In this case, we can display the variables in the desired field. And we will not have any restrictions in design. You can also work on this widget in a more specialized way in the future.

**The Color swatches feature has another great use.** It is also great if you add Color swatches to the **products widget**.
Using the product widget, we display the product archive ...
If you add the Color swatches feature to the products widget, we can show users the available colors of each product. this is fabulous ! **Please look at the following two images :**
https://prnt.sc/1xzikap & https://prnt.sc/1xziq07     Like these images, we can display the available colors of each product to users. This is really great.

thank you

**Comment by rami-elementor** [comment]
Looks like a WooCommerce feature, not Elementor feature.

You should ask WC developers to develop this feature - https://github.com/woocommerce/woocommerce

**Comment by 79ho3ein** [comment]
@rami-elementor 
no I do not think so. Because there is now a third party plugin for this feature. Also, the Jet woobuilder plugin, one of the largest elementor plugins, will be adding this feature soon.
This is a very important feature like my account page.
With your permission, I will integrate this with #16266.
