### ISSUE TITLE
Popups not showing properly

### ISSUE THREAD

**Issue by grizzly94** [elementor/elementor#16783]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hi, I've been experiencing a problem with my popups for a few days. These are not displayed correctly on the web page, but they are displayed correctly in the editor. On the website it seems that only some of the styles that I create are being loaded. I recently turned on Experimental Elementor options to reduce website load, I thought this might be the problem but I turned them off and the problem persists.
On the other hand, I did a test with a popup template generated by Elementor to rule out that there was a problem only with mine and in the same way they are not displayed correctly.

I am not using any other plugin other than Elementor, Elementor Pro and Sina Extension. I don't know where else to look to solve the problem, overnight the popups started to look bad on the website. 

Website Popup:
![imagen](https://user-images.githubusercontent.com/9687738/139785469-d32804dd-0778-40cc-b745-636a4165094a.png)

Editor Popup:
![imagen](https://user-images.githubusercontent.com/9687738/139785539-6071f297-9b9c-433d-bbde-4e72c3d790be.png)

## Steps to reproduce
Create a popup, and publish it in Entire Site. Call it from a button and see how it looks.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/hi0bNFUu

**Comment by grizzly94** [comment]
I solved switching the CSS print method from internal to external in Elementor > Settings

**Comment by whyohssab** [comment]
It doesn't work properly in safari
