### ISSUE TITLE
When editing the desktop, tablet elements are displayed, and vice versa

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16781]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello elementor team!

This request is actually related to the responsive section ...  For example, if we hide the part related to the tablet and mobile from the desktop (using the responsive part), that part will be hidden in the desktop, but not completely!
So displayed, but faint.
I think it is better not to show the parts that we have hidden from the desktop when we edit the desktop. Be completely hidden. **This is much better. In this case, we can focus on the desired part.**
Or, for example, if we enable tablet mode, we only see content that is dedicated to the tablet. This is really great.
**I hope I have conveyed my words well.**

thank you

**Comment by jazir5** [comment]
Install flexible elementor panel(free) and enable the hide option for responsive mode in the settings panel(top left hamburger). Completely hides any responsively hidden items on whatever responsive mode they're hidden on

**Comment by 79ho3ein** [comment]
This option already exists in elementor. (In these 3 years of working with elementor, I did not pay attention to it)
**But it has a bug : #17880**
