### ISSUE TITLE
Insert Google Analytics code using elementor (New feature)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16787]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's great to be able to embed Google Analytics code using elementor. A section for inserting Google Analytics code in the site settings section would be great.

**Comment by gilesholder** [comment]
This is already possible in the Pro version and even allows you to specify what pages you wish to load on etc.

See here: https://elementor.com/help/custom-code-pro

I doubt this would come to free. You could try using the free Snippets plugin though to add or insert directly into your theme via the header.php file or as a function.

**Comment by rami-elementor** [comment]
Hi @Michaelgimii 

I'm closing this issue as [this feature already exist](https://elementor.com/help/custom-code-pro) in Elementor Pro.

Currently, we are not going to offer this feature as part of Elementor Core. But there are many free plugins with the same functionality.
