### ISSUE TITLE
Doesn't work when editing with Elementer

### ISSUE THREAD

**Issue by thaikhoi123** [elementor/elementor#16784]
Hello, I want to edit the page with elementor, but I can't edit it, it is reported as shown below, please help me fix it.
Thank all
![image](https://user-images.githubusercontent.com/69787104/139807766-ee018471-cf78-4fab-bdd1-3ca54f0e5251.png)

**Comment by shilo-ey** [comment]
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Deactivate all of the Experiments and activate them one by one until you identify the buggy experiment (Elementor > Settings > Experiments tab)
- Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).


And see if the issue still persists.


Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.

**Comment by thaikhoi123** [comment]
I tried:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin. -> error
- Deactivate all of the Experiments and activate them one by one until you identify the buggy experiment (Elementor > Settings > Experiments tab) -> error, I can't move between tabs

- Change your WordPress theme to Hello Theme (or other default WordPress theme). -> Can edit, But on the themes I use, it doesn't work

-> Help me, My themes: Megahost (https://themeforest.net/item/hosting-technology-software-and-whmcs-wordpress-theme-megahost/5021665)
