### ISSUE TITLE
 motivating quotes on startup

### ISSUE THREAD

**Issue by Chetan11-dev** [elementor/elementor#16798]
you people do it all wrong. 
You instead should have motivating quotes on startup such as:

"Great Designer you are", "Hero Designer", "Mater Designer", It will maake us happy. Get it done quickly.

**Comment by Chetan11-dev** [comment]
Progress??

**Comment by Chetan11-dev** [comment]
WHat is this?

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.

**Comment by Chetan11-dev** [comment]
ok
