### ISSUE TITLE
Bug - Gradients editor mode

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#16793]
Gradients no longer appear in the editor mode, they do appear in the global preview of the page, but not when the page is edited. When creating the gradient, it appears, but when the editor mode is reloaded, it disappears, and there is only one color instead.

**Comment by MichaelDarko** [comment]
+1

**Comment by arielk** [comment]
I'm closing an issue due we already fixed this issue. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
