### ISSUE TITLE
Animated Headline got messed up in latest update

### ISSUE THREAD

**Issue by rouxsean** [elementor/elementor#16816]
Animated headlines have 3 textual elements.

In the 3rd element, "After Text", I had the following text:

`in the ones who bring out the <span style="color:#00AEAD;">Good </span> in you` 

And it rendered properly.

After the update, no matter what I do (pretty much everything including re-installing elementor & pro), the widget IGNORES the html, and the "After text" is literally: "`in the ones who bring out the <span style="color:#00AEAD;">Good </span> in you`" (yes, with the span tags & everything - yes the user sees the html code).

When editing the text, everything is formatted "properly", but when I switch to a new block or save, it goes back to showing the html literally with no interpretation.

It worked properly before the update, now it is broken.

(The "regular" non-animated headline widget properly interprets html)

**Comment by avivu** [comment]
Hello @rouxsean 

Thanks for reporting.
We will address this issue soon and release a patch.
Please follow this thread for updates.

Thanks!

**Comment by avivu** [comment]
Hello @rouxsean,

This issue has been resolved in Elementor Pro v3.5.1

Feel free to update

Thanks!

**Comment by rouxsean** [comment]
Awesome. Updating Pro now. Much thanks, @avivu !

**Comment by GTrodd** [comment]
Hi @avivu,

I'm afraid I have to reopen this thread. My site is currently using the Archived Widget Pro ([https://elementor.com/help/archive-posts-widget-pro/](https://elementor.com/help/archive-posts-widget-pro/)) and in the Layout section we are using the "Read More Text" field. 

Therein we are using an `<i>` tag and it is displaying in the same manner as @rouxsean reported. 

This began after updating to Elementor Pro v3.5.0 and continued after updating to Elementor Pro v3.5.1. 

Any assistance would be appreciated.

Thank  you!

**Comment by avivu** [comment]
Helllo @GTrodd 

Thank you for reporting this issue.
For what purpose are you using the <I> tag inside the "Read More" text field?

**Comment by GTrodd** [comment]
Hi @avivu,

Thank you for the quick follow up! We are currently placing the "chevron-right" icon from Font Awesome in this section as requested by our client. This icon, as well as other directional chevrons, is used throughout the site. At present this is the only location we have noticed that has this issue.

Thank you for assistance with, and consideration of, this issue!

![Thumbnail](https://user-images.githubusercontent.com/63249914/142429543-334a9859-ccd3-4f7c-9015-02bcd458962c.png)

**Comment by avivu** [comment]
Hi @GTrodd ,

Thank you for the explanation.
Would you please open a new issue with all of the details and tag me?

I'll move it forwards to our developers for further investigation.

Have a great day!
