### ISSUE TITLE
[Feature Request] SVG inline for eicons.woff2

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#16817]
**What problem is your feature request going to solve? Please describe.**
The Elementor eicons library is 90 kb and a pretty significant performance drag.

**Describe the solution you'd like**
SVG inline for eicons font, just as the elementor team has done for the font-awesome library. This would significantly improve performance of all elementor sites

**Describe alternatives you've considered**
None

**Comment by DorShahar** [comment]
Hi @jazir5 
This will be implemented in the upcoming Core 3.5.0 version. Stay tuned! 

Merging this with #11361 for better tracking

Thanks
