### ISSUE TITLE
bug in background section

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16828]
hello
Everything works fine if we put the image in the section or column, but if we enable Scrolling Effects, the image we put is out of control. **Please watch the video below :**
https://user-images.githubusercontent.com/77163248/140609278-eaad3de4-2876-46ac-859f-406627d32837.mp4

[system-info-localhost-06-11-2021.txt](https://github.com/elementor/elementor/files/7490423/system-info-localhost-06-11-2021.txt)

thank you

**Comment by 79ho3ein** [comment]
hello @shilo-ey, please check this. thank you

**Comment by enuzzo** [comment]
Have a similar problem: enabling the scrolling effects, image disappear

https://user-images.githubusercontent.com/3628008/150674678-6bf2f1d7-67de-428d-9081-8e94eb674769.mp4

**Comment by enuzzo** [comment]
...got the notification for 3.5.4 a second ago, updated and working fine! :-) Kudos!

**Comment by 79ho3ein** [comment]
Thanks for the good news @enuzzo.
cheers!
