### ISSUE TITLE
✅ 🐞 Elementor ajax search (Especially for WooCommerce)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16832]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Searching for Ajax is absolutely essential.Now the elementor search widget is very simple and old. Therefore search widget, it is practically unusable in a store website.
I hope you already have a plan to develop this widget. **Please consider some of the suggested features in developing this widget:**
1-Show loader before displaying search results
2-Search results can be scrolled vertically, or paged in Ajax
3-Open in new tab for search results options
4-The pagination buttons are numbered, or buttons
5-Ability to assign a search to a specific post type (For example, only products should be displayed in the results, not posts or pages)
6- **Ability to display the most searched (This is great in e-commerce.)**
7-Custom icons for search
8- Full compatibility with WooCommerce (Ability to display product points, previous prices and special sales)

**Comment by nicholaszein** [comment]
Hi @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.23.0! 🥳 

To learn more check this article: https://elementor.com/help/search-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
