### ISSUE TITLE
Gradient brackground not loading correct in section after refresh

### ISSUE THREAD

**Issue by Igcorreia** [elementor/elementor#16831]
Hi, I made a video that shows the error in action.

Steps to reproduce:  - Select a section and add the following settings:

![image](https://user-images.githubusercontent.com/1076409/140618786-0d46239f-5fbe-4c99-a252-c5ca89246614.png)

After refresh the website is not loading the correct color from the ORIGIN css gradient. Please notice that I am using the radial effect.

https://user-images.githubusercontent.com/1076409/140618870-f5026b57-bc71-43fa-abd2-ffc84b5b0aa3.mp4

**Comment by rodolphebertozzo** [comment]
Duplicata of : https://github.com/elementor/elementor/issues/16793

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
