### ISSUE TITLE
Issues with creating Loops (also reported on Ele Skin git)

### ISSUE THREAD

**Issue by morgank-atl** [elementor/elementor#16858]
Steps tried:

Templates - Theme Builder [table view] - Loop tab - Add New Loop
Loop is selected by default - put in a name - click Create Template - get No Content Area error.
![image](https://user-images.githubusercontent.com/17280082/140751897-b517425a-ecad-46dc-8045-84e0dd3e21ec.png)
It does save the file as a Loop draft but I cannot edit it - same No Content Area message.  

If I go to the "new" Theme Builder it shows that draft loop on the main view, but not on the Loop view. 
![image](https://user-images.githubusercontent.com/17280082/140752952-f8a493a9-63b6-471f-befb-3ed66e5c735c.png)
![image](https://user-images.githubusercontent.com/17280082/140753037-d6cc831d-5c3a-4966-aa96-dac6dc5d122b.png)

I went back to the Theme Builder table view and instead of editing my loop with Elementor I just did "Edit". I changed the canvas to Elementor Canvas, then Updated, then I could edit it with Elementor. 
![image](https://user-images.githubusercontent.com/17280082/140754265-3cb0ccaa-7c28-4172-ae99-365fdd84bb6b.png)

I'm using the Hello Elementor theme and the only build plugins I have are Ele Custom Skin Pro and Premium Elementor Add-Ons Pro (and Elementor Pro).

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
