### ISSUE TITLE
Ability to copy & paste style between two elementor websites

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16870]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello
A very interesting feature has been added in version 3.5 elementor that we can import images directly from the desktop into the elementor editor. this is great. **But I had a suggestion that is almost similar to this feature. But it is really practical.**

Suppose we have two websites and both are built with elementor. In the current situation, we can not transfer a style to the opposite site using copy + paste. Or, for example, **move a section to the opposite site**. Instead, we can just move the style between different pages of one website.

I hope I conveyed my words well. Let me know if you need a video.

thank you

**Comment by StenderIternum** [comment]
There are numerous addons that add this functionality - To name a few : 
https://happyaddons.com/cross-domain-copy-paste/ 
https://ultimateelementor.com/widgets/cross-site-copy-paste/
https://powerpackelements.com/elementor-widgets/cross-domain-copy-paste/ 
https://mightythemes.com/cross-domain-copy-paste/ 

It is weird that Elementor doesn't include this functionality in its core. 
Especially usefull when working on a staging site, and you want to move a section of it to the live site.

**Comment by 79ho3ein** [comment]
hi @StenderIternum 
Yes, there are many plugins. But for us, elementor comes first. We do not want to depend on another plugin. I hope this feature will be localized in elementor soon.
hello @DorShahar , If possible, please check this.

Thanks

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/9424

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
