### ISSUE TITLE
Menu Cart don't open automatically in single product after click add to cart button

### ISSUE THREAD

**Issue by AV-Projects** [elementor/elementor#16879]
In single product page side or mini cart don't open automatically after click add to cart button. This function works only in product's archive pages. Any solution for this without adding another plugins or this is be solved in next updates?

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!

**Comment by jazir5** [comment]
@avivu 

But the latest release of elementor pro is 3.6.1?

**Comment by avivu** [comment]
Hi @jazir5 ,
The fix for this issue was part of Pro 3.6.0,
but now we have already released 3.6.1.
Thank you!

**Comment by tamal-sen** [comment]
@avivu hi, this is still not working on single product page. I have turned on AJAX option and automatically open cart option is ON.
