### ISSUE TITLE
Container - Feedbacks

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#16886]
Hi,
I've been testing the new element container available in development version for half an hour now, I find the design more free, more relaxed, you can trust your eye more for the design. I noticed a first bug, the container causes a scrolling bug at the page level, every time I move the mouse wheel up, I am automatically redirected to the top of the previous section or to the bottom of my container, so my page does not stay fixed to the part of the container where I stop my mouse.

**Comment by fabianenzensperger** [comment]
@shilo-ey @DorShahar 

Oh my God!! Container is AWESOME !! It's awesome and intuitive. You finally have full control over the layout. And finally a great column order with even responsive settings.

Thank you thank you thank you Elementor, I can't stop it is so much fun! I want to do a website with it right now, please bring it out soon! 😍

**Comment by 79ho3ein** [comment]
Really amazing elementor. The container feature leaves nothing to be said. But it has a number of small flaws that are normal.
Congratulations to the elementor developers. They are truly unique. Both themselves and their work.

**Comment by fabianenzensperger** [comment]
> If you find a bug or have a suggestion, should we report in this issue or wait until beta 3.6?


Use this in your dashboard:

<img width="152" alt="Bildschirmfoto 2021-11-10 um 11 01 51" src="https://user-images.githubusercontent.com/57997262/141092472-9d9030a5-2037-4647-8cdc-0a759ce02348.png">

**Comment by shilo-ey** [comment]
Hey @rodolphebertozzo thanks for reporting!

We improved the container and are going to release it soon to an alpha stage experiment in all versions.

If you encounter any other issue please create a new issue for us to inspect and fix it.

Thanks!
