### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vraverat** [elementor/elementor#16895]

**Comment by shilo-ey** [comment]
Hi @vraverat 
Thank you for contacting us and sharing this information with us.

Found a vulnerability? Submit it to [our bug bounty program](https://bugcrowd.com/elementor)

Security issues can affect existing site, therefore extra caution is needed when reporting one.

We will take a look over this and update this issue.

**Comment by vraverat** [comment]
Hi @shilo-ey!

Thanks for your fast reply.

Though not critical, the issue I was describing will force us to reward the searcher that found it on our own bounty program.
I'll let him know he should also report it to you and hope that you'll be able to fix it as soon as possible.

Best regards.

**Comment by vraverat** [comment]
Hi @shilo-ey !

Posted the report to the bounty program, but I'm not sure this is actually the right place to do it.
The bug affect the WordPress plugin, and all it's users.

What We want is to have this issue fixed in the plugin, not especially on Elementor's networks.

Could you confirm that your plugin development teams are working on a solution about it ?

Regards.
