### ISSUE TITLE
WooCommerce Checkout Bug

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#16894]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When using WooCommerce Checkout Field Editor (popular plugin) with the new checkout widget the shipping functionality does not work correctly.
I have shipping methods configured by postcode and when the address is entered the shipping does not update from please "enter an address to see available shipping methods". When I deactivate WooCommerce Checkout Field Editor it works as expected.

I tested with the stock WooCommerce checkout and it works as expected so has to be something going on with the new checkout widget.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by avivu** [comment]
Hello @gilesholder 

Thank you for the information.
We will investigate this issue and notify you of the result in this thread.
