### ISSUE TITLE
Disabling LazyLoad on Specific Images

### ISSUE THREAD

**Issue by Hsharma9643** [elementor/elementor#16896]
Hi,

I want to disable lazyload on specific images. 

For example images in the header section. 

I am using Elementor Pro with the Hello theme. And the site is hosted on SiteGround and using the SiteGround Optimizer plugin. 

SiteGround Optimizer plugin has an option to prevent lazyload on specific images by excluding Image CSS.

I am unable to find out CSS for the images. And contacted Elementor support and they directed me here.

Can anybody help?

Example page: https://www.adschoolmaster.com/keyword-research/

Thanks,
Hemant 

P.S. Just help me with 1 or 2 images so that I can replicate the same process throughout the site if that's a possibility. Thanks again:)

**Comment by StenderIternum** [comment]
According to Sitegrounds plugin docs, you can add CSS classes to exclude images from lazy loading.. 
So in the sitegrounds plugin you can add a class like "no-lazy" and then add the "no-lazy" class to the images you don't want to lazyload. 
Read the docs here : https://www.siteground.com/tutorials/wordpress/sg-optimizer/image-optimizations/

**Comment by Hsharma9643** [comment]
Thanks for the response. But I didn't find any detailed tutorial on the link you shared. It just says You can also exclude specific CSS classes and media types from the Lazy Load functionality.

**Comment by rami-elementor** [comment]
Hi @Hsharma9643 ,

Currently Elementor has no lazy load functionality (but we are working on that).

Sounds like the lazy loading functionality it is part of the "SiteGround Optimizer" plugin you are using.

I'm closing this issue but feel free to update this ticket for other users with the same problem using "SiteGround Optimizer" plugin.
