### ISSUE TITLE
unable to see or use new Container element in Editor & errors

### ISSUE THREAD

**Issue by adi0071** [elementor/elementor#16916]
![no container](https://user-images.githubusercontent.com/42467776/141488172-d1832fad-c90b-4266-b535-b5a3b07d8049.jpg)
![errors](https://user-images.githubusercontent.com/42467776/141488207-8f8eeeef-165e-4b0d-a218-3178950a018b.jpg)

Just trying the beta version .....installed updated all fine , tried to update and edit an elementor page and did not see container , then tried to add a new template to see if that was the problem , but again the same issue plus errors at top on page

[system-info-staging.seventyplenty.com-12-11-2021.txt]

(https://github.com/elementor/elementor/files/7528524/system-info-staging.seventyplenty.com-12-11-2021.txt)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
It seems like you are having a conflict with Elementor.
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Deactivate all of the Experiments and activate them one by one until you identify the buggy experiment (Elementor > Settings > Experiments tab)
- Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).


And see if the issue still persists.

The Container experiment should be activated from the Experiments screen
