### ISSUE TITLE
Set language of Elementor based on user's profile instead of the site's language

### ISSUE THREAD

**Issue by raabmar** [elementor/elementor#16918]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's annoying that the language of Elementor depends on the site's language. 

**Describe the solution you'd like**
If you are used to use Elementor in English it's super annoying to be forced to use it in another language. Some sites require the language to be set to a different language than English. The result: Elementor itself is also shown in that site's language.

E.g. I need to change the site language to German so that WordPress converts the umlaute. The result: Elementor is also in German.

**Describe alternatives you've considered**
Show Elementor in the language of the user profile, not the site's language.

**Comment by shilo-ey** [comment]
I merged this issue with #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
