### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Allow to select different icons for the Star Rating widget (Duplicate of #10529)

### ISSUE THREAD

**Issue by bbua97** [elementor/elementor#16955]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I'm creating membership sites for music-school projects and I need something like a Difficulty-Rating for the different songs to learn. Stars are not really in relation with difficulty. Additional a basic difficulty scale are three levels: easy, middle, hard.  A 5 or 10 scale does not fit for this use-case.

The perfect solution for that would be to be able to choose a different icon or even upload own icons. In addition to that you should be able to select not only between a 5 or 10 scala, you should be able to select ascending from 1-10. 

Here is another example of a difficulty level for hiking trails (to show another usecase)

![Screenshot_1](https://user-images.githubusercontent.com/85588537/142032379-8340885e-10e0-49df-8db3-c512b10bcc6b.jpg)

**Comment by ewancluckie** [comment]
+1 for this. Hotels and Resorts need a 1-6 star rating so doesn't fit in the specified ranges provided. It would be good if the range was customisable within the Elementor editor.

**Comment by nicholaszein** [comment]
Hello there, @XXX!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #10529

Feel free to continue the conversation there! 👉

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you so much for your patience! 🙏 

We have great news! 🙌 

### 📢 We're happy to announce that the request you raised was resolved with the release of the new Rating widget in Elementor v3.17! 🥳 

With this new widget, you have more options to choose the number of rating points, custom icons, and styling options, and it is fully compatible with Google Rich snippets (updated) and fully accessible.

Your current Start Rating widgets will remain as they were before this update. But moving forward, only the new Rating widget will be available to add to your layouts.

If you are using the old Star Rating widget, we would recommend that you replace it with the new Rating widget.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
