### ISSUE TITLE
Easy access to activate Maintenance & Coming Soon mode elementor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16968]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
hello
Please make it easy to activate the "coming soon" and "Maintenance" modes. This is not really hard for us web designers, But activating it is difficult for customers. For example, they want to enable "soon" mode to update product prices. But it is difficult for them to enter the elementor settings> Tools> Maintenance Mode.

**proposed solution :**
It's great if you add a button to the Admin Top Bar, so we can enable Maintenance & Coming Soon mode with just one click. this is great.

thank you

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,
