### ISSUE TITLE
Broken shortcodes and internal URLs in v3.5.0 beta 3

### ISSUE THREAD

**Issue by OferBenda** [elementor/elementor#16971]
beta3 from/releases you just uploaded broke shortcodes and internal URLs: https://i.imgur.com/Y2XQozT.png --> they are simply not generated for the `<a>` element. Downgrading to beta2 fixed the problem.

_Originally posted by @kangarko in https://github.com/elementor/elementor/issues/16840#issuecomment-971388018_

**Comment by kangarko** [comment]
Not sure if reposting is needed, they must have tons of work already. But thanks & hopefully it gets patched asap

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
