### ISSUE TITLE
Popup close on any link/button click

### ISSUE THREAD

**Issue by sarkarpartho76** [elementor/elementor#16977]
I think a feature where the popup can be set to close on clicking any link or button would be very helpful. Like if I create an off-canvas menu, and some menu items are linked to an anchor link on the same page, I would want the popup to close when that menu item is clicked, so that when the page scrolls to the menu anchor, the popup is not covering the screen.

**Comment by TomRaraAvis** [comment]
+1
#8125 — Trigger to close popup
#27727 — Add an option to close the Off-Canvas widget when a link inside is clicked
#8125 — Trigger to close popup
#7085 — Popup - Close when you click on a button
#16977 — Popup close on any link/button click 
#28853 — hiding offcanvas doesn't work well with 2 or more. / problem shown in the video
