### ISSUE TITLE
Inserindo digitação de campo de texto em link

### ISSUE THREAD

**Issue by sturtdll** [elementor/elementor#16989]
Boa noite! Amigos programadores,

Estou com um sério problema na criação de uma função em meu formulário elementor pro.

A função que estou tentando criar, é um campo de texto, onde a pessoa insere algo, e quando clica no botão submit, ele vai abrir uma nova aba com um link ex: https://www.example.com/consult/(TEXTO INSERIDO NO CAMPO)

No HTML

```
<html>
<h3>
SELO DIGITAL
</h3>
<input size="30" type="text" name="form_fields[campotexto]" id="form-field-campotexto" class="elementor-field elementor-size-sm  elementor-field-textual" placeholder="Name" aria-invalid="false">
<hr>
<button type="submit" class="elementor-button elementor-size-sm" id="consultaselo" aria-invalid="false"> <span> <span class=" elementor-button-icon"> </span> <span class="elementor-button-text">consultar</span> </span> </button>
</html>

```

Script
```
<script>
var selodigital = document.getElementById('form-fields-campotexto');
var botaopesquisa = document.getElementById('consultaselo');
botaopesquisa.onclick = function() {
   window.open('https://selo.funarpen.com.br/consulta/Selo/'+ selodigital +'', '_blank');
};
</script>

```
Porém quando clico em subimt, ele me gera uma URL com final "null", mesmo que o campo tenha algo escrito.

[https://jsfiddle.net/8m5hkf2s/](url)

**Comment by rami-elementor** [comment]
Please reopen this issue in English.
