### ISSUE TITLE
Read More Text Displaying HTML Tags

### ISSUE THREAD

**Issue by GTrodd** [elementor/elementor#16985]
Hello,

I have recently encountered an issue where my Read More Text fields (of the [Archived Widget Pro](https://elementor.com/help/archive-posts-widget-pro/)) are displaying the HTML tags I am using within the field. This issue is occurring on Elementor Pro v3.5.0 and Elementor Pro v3.5.1. 

Associated Issue(s): [#16816](https://github.com/elementor/elementor/issues/16816)

I was guided by @avivu to create a new bug report thread for this issue. Thank you for your help, @avivu!

**Comment by splinksl** [comment]
Hi, we have the same issue,
we appreciate any help.
Best regards!

**Comment by phil-beachler-id** [comment]
We are also experiencing this issue on sites using the <SVG> tag in the "read more" section.

**Comment by splinksl** [comment]
Hi, any progress on this topic?

**Comment by avivu** [comment]
Hello @splinksl,

This issue is resolved and will be part of Elementor Pro v3.6.0.
Please follow this thread for updates.

Thanks!

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!

**Comment by GTrodd** [comment]
Hi Avivu,

Sorry for the delay in reply - thank you for releasing a fix for this!

Take care!
