### ISSUE TITLE
Deprecated: _register_controls

### ISSUE THREAD

**Issue by ArkyDany** [elementor/elementor#17026]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by ArkyDany** [comment]
Hi Dev team,
I installed the Dev version and it's great, however, I have many Warnings and 1 deprecated function.
For every page I'm creating and also if I open Appearance -> Customize -> Additional CSS I have:

Deprecated: _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /var/www/vhosts/.../wp-includes/functions.php on line 5211

Is there anything that I have to do?

WARNINGS
Because I'm working in a DEV environment I have errors/warnings active and I can see everytime I'm refreshing any pages:

Warning
: file_get_contents(.../wp-content/plugins/elementor/assets/lib/font-awesome/json/solid.json): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in
/var/www/vhosts/.../wp-content/plugins/elementor/core/page-assets/data-managers/base.php
on line 209


Notice
: Trying to access array offset on value of type null in
/var/www/vhosts/.../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php
on line 45


Notice
: Trying to access array offset on value of type null in
/var/www/vhosts/.../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php
on line 45


Notice
: Trying to access array offset on value of type null in
/var/www/vhosts/.../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php
on line 48


Notice
: Trying to access array offset on value of type null in
/var/www/vhosts/.../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php
on line 49


Notice
: Trying to access array offset on value of type null in
/var/www/vhosts/.../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php
on line 50

Thank you the DEV version looks great :)

**Comment by rami-elementor** [comment]
You are using a plugin that extends Elementor functionality the old way.

Deactivate the plugin one-by-one until you find the plugin. Contact the plugin author and ask him to update the code.

The plugin author should to replace the _register_controls() method with register_controls() removing the _ prefix (this was changed in Elementor 3.1.0).

More info at https://developers.elementor.com/docs/widgets/widget-structure/
