### ISSUE TITLE
🐞 Bug Report: Not all active breakpoints appear under "Advanced Rules" in popup publish settings - [ED-7973]

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#17020]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When enabling Additional Breakpoints say for Laptop when you go to Popups > Advanced Rules > Show On Devices
Only Desktop, Tablet & Mobile are displayed. There is no option available for Laptop.

## Steps to reproduce

1. Enable Additional Breakpoints
2. Add Laptop as a breakpoint
3. Create a popup template
4. In advanced rules select "Show on devices"
5. No option for laptop is displayed just the default (Desktop, Tablet & Mobile) options.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by hitsgee** [comment]
This issue still remains in the latest versions. Please fix Elementor.

Screenshots attached
![Elementor-Press-Release (2)](https://user-images.githubusercontent.com/40209785/214323431-feb7343a-dd63-4fe5-a434-9b774eddfdb1.png)
![Elementor-Press-Release (1)](https://user-images.githubusercontent.com/40209785/214323433-12d0e098-59b7-4609-8585-f1870ee0d85d.png)
.

**Comment by hitsgee** [comment]
Closed issue as included in 3.12 beta.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
