### ISSUE TITLE
Enabling scroll-snap disables scroll anchoring links

### ISSUE THREAD

**Issue by Jannik-Momo** [elementor/elementor#17035]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

Enabling Scroll-snap on a page stops the functionality of using a menu with scroll to anchor points or regular <a> linking to IDs. when clicking them you just land on the top of the page. Its possible to use them when opening the link in a new tab.

## Steps to reproduce

Create a page with multiple menu anchors or give sections an ID
create a menu using links that contain those IDs or alternativly a regular <a> link linking to an #ID on your page
Enable scroll snap on that page
Click one of the menu links

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Debian)
	MySQL version: MySQL Community Server (GPL) v1.2.10
	PHP Version: 7.4.26
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: XY
	Home URL: XY
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 1
	Admin Email: XXX
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

== Active Plugins ==
	Allow Webp Image
		Version: 1.0.0
		Author: Top Infosoft

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.22
		Author: Benjamin A. Bornschein, Borlabs

	Contact Form 7
		Version: 5.5.2
		Author: Takayuki Miyoshi

	Duplicate Page
		Version: 4.4.5
		Author: mndpsingh287

	Ecwid Ecommerce Shopping Cart
		Version: 6.10.15
		Author: Ecwid Ecommerce

	Elementor
		Version: 3.6.0-dev10
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.11.11
		Author: WPVibes

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0-dev14
		Author: Elementor.com

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 8.4.348
		Author: HubSpot

	Real-Time Find and Replace
		Version: 4.0.2
		Author: Marios Alexandrou

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	The Plus Addons for Elementor
		Version: 5.0.3
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.7
		Author: POSIMYTH

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

	WPML Multilingual CMS
		Version: 4.5.1
		Author: OnTheGoSystems

	WPML SEO
		Version: 2.0.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.0
		Author: OnTheGoSystems

	Yoast SEO
		Version: 17.6
		Author: Team Yoast

== Must-Use Plugins ==
	strattic.php
		Version: 
		Author: 

== Elementor - Compatibility Tag ==
	
	Elementor Addon Elements: Compatibility not specified
	Elementor Pro: Compatibility not specified
	The Plus Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		heading : 3
		image : 1
		nav-menu : 3
		social-icons : 1
		text-editor : 4
	header : 6
		button : 5
		icon-list : 2
		image : 9
		nav-menu : 9
	page : 5
		button : 3
		heading : 9
		html : 3
		image : 2
		nav-menu : 2
		social-icons : 1
		text-editor : 2
	popup : 1
		html : 1
	section : 24
		button : 7
		heading : 27
		html : 3
		icon : 4
		image : 35
		nav-menu : 2
		social-icons : 3
		spacer : 5
		text-editor : 34
		video : 1
	widget : 0
		button : 1
		heading : 1
		image-carousel : 1
		testimonial-carousel : 2
	wp-post : 3
		posts : 3
		text-editor : 9
	wp-page : 56
		button : 28
		container : 1
		divider : 15
		heading : 303
		html : 53
		icon : 15
		icon-list : 1
		image : 46
		image-carousel : 2
		menu-anchor : 2
		nav-menu : 3
		posts : 1
		search-form : 1
		social-icons : 1
		spacer : 2
		testimonial-carousel : 2
		text-editor : 218
		toggle : 2
		tp-carousel-anything : 1
		video : 2
	error-404 : 1
		button : 1
		heading : 2
		image : 1

== Elementor Experiments ==
	Optimierte DOM Ausgabe: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Container: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Custom Default Widget Styles: Inactive by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 412021-11-19 09:17:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev5',
  'to' => '3.6.0-dev6',
)]
2021-11-19 09:18:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev5',
  'to' => '3.6.0-dev6',
)]
2021-11-22 10:57:03 [info] elementor::elementor_updater Started 
2021-11-22 10:57:03 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-22 10:57:04 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-22 10:57:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev6',
  'to' => '3.6.0-dev8',
)]
2021-11-23 16:51:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev8',
  'to' => '3.6.0-dev9',
)]
2021-11-23 16:51:49 [info] elementor::elementor_updater Started 
2021-11-23 16:51:49 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-23 16:51:51 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-23 16:51:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev8',
  'to' => '3.6.0-dev9',
)]
2021-11-25 09:44:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev9',
  'to' => '3.6.0-dev10',
)]
2021-11-25 09:44:37 [info] elementor::elementor_updater Started 
2021-11-25 09:44:37 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-25 09:44:39 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-25 09:44:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev9',
  'to' => '3.6.0-dev10',
)]
2021-11-25 10:02:29 [info] elementor-pro::elementor_pro_updater Started 
2021-11-25 10:02:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-11-25 10:02:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-11-25 10:02:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev12',
  'to' => '3.6.0-dev14',
)]

PHP: showing 2 of 2PHP: 2021-11-19 09:54:19 [error X 1][/var/strattic/site/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /var/strattic/site/public_html/wp-includes/class-wp-hook.php on line 305 and defined in /var/strattic/site/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1042
Stack trace:
#0 /var/strattic/site/public_html/wp-includes/class-wp-hook.php(305): Elementor\TemplateLibrary\Source_Local->on_save_post(12111, NULL)
#1 /var/strattic/site/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /var/strattic/site/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /var/strattic/site/public_html/wp-includes/post.php(4468): do_action('save_post', 12111, NULL, true)
#4 /var/strattic/site/public_html/wp-includes/post.php(4570): wp_insert_post(Array, false, true)
#5 /var/strattic/site/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /var/strattic/site/pub [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-19 16:56:11 [error X 1][/var/strattic/site/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /var/strattic/site/public_html/wp-includes/class-wp-hook.php on line 305 and defined in /var/strattic/site/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1042
Stack trace:
#0 /var/strattic/site/public_html/wp-includes/class-wp-hook.php(305): Elementor\TemplateLibrary\Source_Local->on_save_post(12233, NULL)
#1 /var/strattic/site/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /var/strattic/site/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /var/strattic/site/public_html/wp-includes/post.php(4468): do_action('save_post', 12233, NULL, true)
#4 /var/strattic/site/public_html/wp-includes/post.php(4570): wp_insert_post(Array, false, true)
#5 /var/strattic/site/public_html/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /var/strattic/site/pub [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by gerardreches** [comment]
I'm experiencing this while using the current version of Elementor and Elementor Pro.

**Comment by graphicgenie** [comment]
I've got the same issue with Elementor Pro 3.22.0

**Comment by HatimLs** [comment]
Same issue with Elementor Pro 3.23.0 ..

**Comment by kshitijmatey** [comment]
Has anyone found a solution for this? I am also facing this issue of scroll to CSS ID not working or working weirdly when Scroll-Snap is ON. I am on Elementor Pro version 3.21.3 
@Jannik-Momo 
@DorShahar 
@gerardreches 
@PhilippS93 
@graphicgenie 
@HatimLs

**Comment by gerardreches** [comment]
> Has anyone found a solution for this? I am also facing this issue of scroll to CSS ID not working or working weirdly when Scroll-Snap is ON. I am on Elementor Pro version 3.21.3 @Jannik-Momo @DorShahar @gerardreches @PhilippS93 @graphicgenie @HatimLs

No solution

**Comment by HolyHeidi** [comment]
Workaround @gerardreches @DorShahar @PhilippS93 @HatimLs @graphicgenie @:
Create an Anker-Menü with two /
example:
https://www.yourdomain.com//#anker
so the page reloads with the anker.
far away from perfect, but it works as workaround
