### ISSUE TITLE
BUG in slides widget.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17055]
hello
In the widget slider, "Content Animation" has a problem.

**To reproduce this bug, please follow the steps below :**

1- Add a slides widget.
3- In the slider options tab, Set "Content Animation" to left. https://prnt.sc/20xpt0e
(Of course, it does not matter if it is left, right or even up)
4- Now see the preview. 

**You will see that "Content Animation" does not work.**  Actually true in the editor, but does not work on the website.

Let me know if you need a video. Thank you

**Active plugins:**

1- elementor 3.4.8
2- elementor pro 3.5.1

**Comment by tjlabais** [comment]
I confirm this bug with elementor pro 3.5.1 and 3.5.2

I downgraded to 3.4.1 and animation works again.

**Comment by Remsboys** [comment]
I have the same problem.
While editing the slider and selecting a content animation, the animation is shown in the editor.
After saving and visiting the site, the animation isn't working.
When opening the editor again, the animation isn't working as well.

Comparision between the CSS-Classes while editing and preview:
"animated fadeInUp" are not set for "swiper-slide-contents"

@DorShahar could you please have a look at this. Thanks.

**Comment by denissonstos** [comment]
I have the same problem.

**Comment by Remsboys** [comment]
I contacted the Elementor Pro Support and received the following answer:

```
I checked it very closely and it is a confirmed bug and our development team is already working on fixing it. 

I'm afraid I cannot provide an ETA but if you wish to keep an eye on our changelog, they're available through the pages below:
https://elementor.com/pro/changelog/
https://elementor.com/help/changelog-of-elementor/​

I'm afraid the only workaround, for now, is to roll back Elementor Pro to 3.4.2. Sorry for the inconvenience.
```

**Comment by 79ho3ein** [comment]
thank you @Remsboys 🌹

**Comment by havn** [comment]
Thanks @Remsboys - 
unfortunately I have tried various versions of jQuery/JS snippets and only the first slide takes, the other 5 remain static. 
The shortest and easiest jQuery snippet I used was:

` jQuery(document).ready(function($){
      $("[class*=swiper-slide-contents]").attr("class", "swiper-slide-contents animated fadeInDown");
  });` 

So yeah, it works but somehow the other 5 slides apparently revert after the pageload function() has run...
Thanks anyway!

**Comment by tjlabais** [comment]
this bug is fixed in version 3.60

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.1

Feel free to update

Thanks!

**Comment by kcalpesh** [comment]
The issue has re-occured in the latest version it seems. The content animation isn't working again.

**Comment by tjlabais** [comment]
> The issue has re-occured in the latest version it seems. The content animation isn't working again.

I don't have this problem

**Comment by kcalpesh** [comment]
It's not working on my desktop browsers.
The animation works fine on a mobile phone but it doesn't show up on desktop.

 However when I preview the page using desktop-mode on a mobile phone it works for me. This is a bit strange.

**Comment by tjlabais** [comment]
> It's not working on my desktop browsers. The animation works fine on a mobile phone but it doesn't show up on desktop.
> 
> However when I preview the page using desktop-mode on a mobile phone it works for me. This is a bit strange.

change browser and use incognito mode or clear browser cache and reload screens.

**Comment by kcalpesh** [comment]
Switched to Firefox and Edge, from Chrome it didn't work.
Cleard all time cache and reloaded the screen. That too didn't work.
Guess I should troubleshoot to check if there's a clash with some other plugin.
