### ISSUE TITLE
Nav menu icon got messed up with the Pro 3.5.2 update

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#17059]
It seems that you fixed some stuff and broke other stuff, once again, as you can see in the video. Is no one testing the stable releases?? This happens on tablet/mobile, whenever the hamburger menu shows up.

https://user-images.githubusercontent.com/60075863/143784132-84c4effc-df6c-44ee-acf8-173fbd95094f.mov

**Comment by shilo-ey** [comment]
Hi @azkalex 

Try to disable "Inline Font Awesome" experiment for now until this issue will be resolved


Thanks

**Comment by azkalex** [comment]
Hey @shilo-ey, it is not active, I have trust issues regarding the experiments same as I do with Elementor updates, because every time I post an issue, it's NOT coming from a conflict with another plugin, it's coming from Elementor/Elementor Pro alone. 

It's like every time I press that update button, I know something is going to break, and this is not normal for a STABLE build on a paid product. Feels like the concept of stable build means nothing on Elementor. Since version 3.0, almost every update messes something up.

When will I feel confident about clicking that update button? I'm a client, I pay for this product, and this is definitely not a cheap product. Even a little design issue, when something is off, matters, because it's an issue, and it means that the team didn't pay enough attention. And these issues are way too often.

Yeah, you can always roll back, but this shouldn't be an excuse for releasing a faulty build. And regarding the roll back, how can I roll back to the build right before the new one, in this case, 3.5.1, when that's all I see?

![image](https://user-images.githubusercontent.com/60075863/143874467-44553eab-4724-400e-a48b-340024bc39b3.png)

Oh yes, from the website! I logged in and downloaded Elementor Pro, but that was already updated with the 3.5.2 version, so what now? I got lucky that I had the 3.5.1 zip in my PC, but that's probably nothing, like all the other issues.

This is a great product, don't get me wrong, but it feels like people there lost interest in it. And same with this small issue, I'm assuming you're planning to have this fixed in the 3.6 build since you added it to that milestone? Like, who cares if people have 2 menu icons now, they can wait until the 3.6 build is released, right?

Please keep track of the changes you make in the files, stop breaking things that work perfectly fine, stop focusing on releasing features that only get half of the job done and focus on improving the current features, fix stuff, take your time, polish this product before adding new stuff. But who cares about my message anyway, people will still buy the product, including me, and that's what matters, right?

**Comment by azkalex** [comment]
So I was right about my message, why did I even bother writing it ... 10 days later, and still nothing.

**Comment by marcocarrozzini** [comment]
Regenerate CSS & Data fixed the issue for me.

**Comment by acs254** [comment]
I also have this issue, and regenerating CSS didn't solve the problem.

**Comment by yberman66** [comment]
I also have the issue - found this post ina firum am yet to try it as I have only tried the update on staging and am holding off until there's a proper fix https://forum.elementor.com/bug-reports-45/close-icon-appears-next-to-the-hamburger-9484.
FYI @shilo-ey the other fixes you suggested didnt work for me.

**Comment by azkalex** [comment]
2 months later, unreal.
