### ISSUE TITLE
Admin Bar not showing for Editors

### ISSUE THREAD

**Issue by mbaierl** [elementor/elementor#17065]
If the user role is "Editor" the Admin Bar does not contain the "Edit with Elementor" entry, even if the user has the right capabilities.

Please fix.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
