### ISSUE TITLE
[FEATURE REQUEST] Custom CSS | Per Breakpoint

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#17061]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Same as when we have CSS Properties on diferents breakpoints, will be AMAZING if instead of creating a "Custom Media Query" for certain elements or widgets when we add "Custom CSS" this can be added automaticly to that specific breakpoint.

**Describe the solution you'd like**
Now when i need to change for example the Border of a certain thing on a element using Custom CSS when the Custom CSS is added, is beign added into the "Global CSS" of that specific section, page or widget BUT for all the Breakpoints.

The solution will be having the same workflow of "if i go to Mobile view, the Custom CSS of that element or whatever applied into that specific breakpoint."

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/17567 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
