### ISSUE TITLE
CONTAINER - sticky and motion effects not available for containers 

### ISSUE THREAD

**Issue by Deadlift79** [elementor/elementor#17068]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

I'm not able to find sticky options and motion effects for containers (in the way it works for sections).
Both sticky and motion effects are available only for widgets.
Do you plan to implement them? Because in that way will be difficult to do simple things like applying transparency to a container, a parallax effect with vertical scroll, containers overlapping setting them to sticky or a sticky header. Thank you.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thank you for reporting. these changes will be implemented soon.

This feature is still under development.

**Comment by fabianenzensperger** [comment]
> Thank you for reporting. these changes will be implemented soon.
> 
> This feature is still under development.


@shilo-ey, while you're at it, you could even expand the sticky functions. But if not, I'll be happy when the previous ones return to the containers. 👀

**Comment by 79ho3ein** [comment]
hello @shilo-ey, excuse me...
Can we add links to containers in version 3.6? (#15423)

**Comment by fabianenzensperger** [comment]
> hello @shilo-ey, excuse me...
> Can we add links to containers in version 3.6? (#15423)


Yes!

<img width="300" alt="Bildschirmfoto 2021-11-30 um 11 57 50" src="https://user-images.githubusercontent.com/57997262/144035010-30162b58-79a1-451b-8abf-8fac68a407e8.png">

**Comment by 79ho3ein** [comment]
> > hello @shilo-ey, excuse me...
> > Can we add links to containers in version 3.6? (#15423)
> 
> Yes!
> 
> <img alt="Bildschirmfoto 2021-11-30 um 11 57 50" width="300" src="https://user-images.githubusercontent.com/57997262/144035010-30162b58-79a1-451b-8abf-8fac68a407e8.png">

excellent, I just saw this. This is a wonderful update.

But if used, there is a problem :
https://user-images.githubusercontent.com/77163248/144039672-ac56eb1b-fceb-47f4-8dbd-c83eb31cb83c.mp4

**Comment by shilo-ey** [comment]
Hey @Deadlift79  thanks for reporting!

We improved the container and are going to release it soon to an alpha stage experiment in all versions.

If you encounter any other issue please create a new issue for us to inspect and fix it.

Thanks!

**Comment by ofmarconi** [comment]
@shilo-ey Thank you!
Any deadline to work the scroll effects with containers?

**Comment by ofmarconi** [comment]
@shilo-ey I saw that you closed this, but how is it resolved?

Last update and:
![image](https://user-images.githubusercontent.com/6594795/169699082-faac3de8-4106-4b74-9279-748c99e2c2eb.png)

In beta works?

**Comment by dwdigitalnz** [comment]
Guys we are up to version 3.11+
Is there any solution??? Super annoying! 
Thanks

**Comment by ShehabAlFardan** [comment]
Is there a work around yet?
