### ISSUE TITLE
✔️ 🚀 Feature Request: Can't set column width to 100% on Desktop

### ISSUE THREAD

**Issue by mbaierl** [elementor/elementor#17075]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Create a section with 3 columns. Try to set the column width of any column to 100 on the Desktop.
The width is reset to 10.

Setting the width to 100 only works on Tablet and Mobile, not on Desktop.

## Steps to reproduce

see description above.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Followup of @elementor/elementor/issues/17070

**Comment by gerardreches** [comment]
This could be merged to #5072

**Comment by nicholaszein** [comment]
Hello@mbaierl!

We have great news! 🙌 

### 📢 We're happy to announce that you can now use the <ins>stable</ins> version of the Flexbox Container experiment introduced with Elementor **v3.8** to set child containers with 100% width on the desktop! 🥳 

Everyone is invited to activate the Flexbox Container experiment and start to enjoy the power of CSS Flexbox! 💪 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
