### ISSUE TITLE
Can't set color width to 100% on Desktop

### ISSUE THREAD

**Issue by mbaierl** [elementor/elementor#17070]
The width for columns cannot be set to 100% on the desktop breakpoint. Always reverts back to 10.

Please fix.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
