### ISSUE TITLE
Documentation on JS hooks is out of date

### ISSUE THREAD

**Issue by rb-ar** [elementor/elementor#17086]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The docs at https://code.elementor.com/js-hooks/ are out of date.

I found out via this article: https://developers.elementor.com/a-new-method-for-attaching-a-js-handler-to-an-element/

**Comment by DorShahar** [comment]
Hi @rb-ar 
Thanks for your feedback. 
We are fully aware of our lack of documentation. 
We are currently working on a total update for our developer's docs.

I hope we will be able to release it soon.
Please stay tuned!

Thanks
