### ISSUE TITLE
elementor Container - Version 3.6.0-dev14

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17082]
hello
Here are some tips in this version :

1- If we link to the containers, they will be completely damaged. (True in the editor, but completely corrupted on the website)

2- If we click on a container, the navigator will open automatically. I think it is better if it is optional. We can choose whether to open navigation when selecting a container. https://prnt.sc/218dtod

3- We can not margin the containers from left and right. This is actually a big limitation. In some designs we need to be able to margin from left and right. https://prnt.sc/218dqks

4- I'm not sure if this is a bug. Maybe related to the dev version. When we drag the widget near the save button, the save button appears with the widget.
https://user-images.githubusercontent.com/77163248/144222789-51ac82a2-d5e2-48b5-b93e-bd8bb99caa64.mp4

5- Finally, please resolve this issue so that wrap activation does not affect the width of the content. This is really important. In the video below, the problem is quite clear : 
https://user-images.githubusercontent.com/77163248/144223654-4f01a327-00ec-46fa-a32c-47ea7cc201f2.mp4

Both buttons are 50% wide. But if we enable the wrap, they will move down each other.

thank you

**Comment by 79ho3ein** [comment]
thank you @shilo-ey. There are two other cases, please check if possible :

1- If we change the width of the column using the mouse, the width of the sides of the container will not be displayed as before : https://prnt.sc/21a2o5a

2- Again, if we change the width of the columns in a container, the space on the opposite side will be empty. If it should not be so. To better understand the subject, I compare the previous mode (section) with the Flexbox.

Ex-mode : 
https://user-images.githubusercontent.com/77163248/144292937-0c5e30cf-124b-404e-a2af-59b779a9e395.mp4

Fax Box : 
https://user-images.githubusercontent.com/77163248/144294391-e15e9130-03a6-4801-bec4-6d0888750c25.mp4

As you can see in the Flexbox video, the right side of the container emptied after moving the columns to the left. While in the former case, this did not happen.
**Also, if you look closely at the Flexbox video, changing the width of the columns is a bit of a hassle. Not as easy as before.**


**As for the problem of applying a link to the container :**
https://user-images.githubusercontent.com/77163248/144295853-b07bf01a-869b-429a-8874-7387c4ae75db.mp4

Sorry, it's a little long...

As you can see in the video above, when I put the title widget in the container, the link was applied without any problems. But when I put the button widget, the container completely collapsed. I did it again, but it fell apart in a different way.

thank you

**Comment by 79ho3ein** [comment]
another case :

The width of the container on the desktop is based on% by default. But when we enter the tablet and mobile mode, it changes to px. https://prnt.sc/21kgl4q
I think it makes more sense if% is also the default on tablets and mobiles. Exactly like a desktop.

**Comment by alanavelino** [comment]
3- We can not margin the containers from left and right. This is actually a big limitation. In some designs we need to be able to margin from left and right. https://prnt.sc/218dqks

Totally agree, this is not optional, it must come already integrated or we will be limited, we hope the people of Elementor will solve it or it will be a failure.

It would be similar to what Bricks already has implemented

https://i.ibb.co/XWdTnK7/Captura25.jpg

**Comment by alanavelino** [comment]
3- We can not margin the containers from left and right. This is actually a big limitation. In some designs we need to be able to margin from left and right. https://prnt.sc/218dqks

////

Changing this part of the container.php code solves hopefully you can check this as it is necessary.

Original https://i.ibb.co/VqLPHjg/001FIX.png
Changed https://i.ibb.co/9b2G0gy/002FIX.png
