### ISSUE TITLE
Dynamic "tool tip" not closing

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#17091]
When hovering opens a Dynamic Tags "tool tip" it is persisting when moving away
![dynamic tab](https://user-images.githubusercontent.com/22448787/144299226-840b3979-d5ea-42bc-a8df-8b5533733058.png)
.

**Comment by DorShahar** [comment]
Hi @nickdgreen 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
