### ISSUE TITLE
Elementor PRO Theme Builder crashing Themify Shoppe Header

### ISSUE THREAD

**Issue by Help3D-Padova** [elementor/elementor#17096]
Hi community

ISSUE:
- When using Elementor PRO and Themify Shoppe the header and footer postion are not working on the base theme

If i disable elementor PRO i can see Shoppe Header and footer. When PRO enabled nothing is shown 

![image](https://user-images.githubusercontent.com/76519178/144464992-c75e6570-83c7-41e4-83e0-b7e5f24b1cc0.png)

Also using Hook insert is not working.

-----------------
If i use a different theme like Astra header and footer are shown correctly.

I'm using the last version of both

**Comment by DorShahar** [comment]
Hi @Help3D-Padova 
According to your description, it seems like a problem with the Theme (Astra Theme is working as needed according to your mention). 

Please contact the Theme owner. 

Thanks
