### ISSUE TITLE
In the form widget, HoneyPot does not work properly.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17108]
On 3 of my websites, I enabled the HoneyPot option on forms.  But spam continues. Please check this item.

Thank you

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Having said that, we have addressed an issue with multiple honeypot widgets in the upcoming Pro 3.7.0 release

Thanks.

**Comment by nerdylist** [comment]
Can confirm, this is happening on all of my sites also. RE: "missing information"... Here's how to reproduce it... Setup a form on a public website. Put a Honeypot on it. It's not very complicated. I have some basic sites with very basic forms on them... I put the "HoneyPot" widget on there, and yet... it's as if it's not even there.
