### ISSUE TITLE
Margins for the container and minimum width

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#17109]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by alanavelino** [comment]
Hello, the team and I have been testing the beta for several days with the new container and the possibility of adding side margins to the containers is lacking.

https://i.ibb.co/qYMJymv/Captura.png

https://i.ibb.co/gzsT69G/01.jpg

Another detail is that it would be very useful to have a max-width and min-width in the widgets, because for example if I have a container at 100% width, already within a heading I would like to be able to weight for example 1140px but with a max -width of 800px, it is very useful not to have to add two containers.

**Comment by alanavelino** [comment]
It would be similar to what Bricks already has implemented

https://i.ibb.co/XWdTnK7/Captura25.jpg

**Comment by alanavelino** [comment]
We can not margin the containers from left and right. This is actually a big limitation. In some designs we need to be able to margin from left and right.

https://i.ibb.co/p2n3PS7/Captura1.png

**Comment by alanavelino** [comment]
Changing this part of the container.php code solves hopefully you can check this as it is necessary.

Original  https://i.ibb.co/VqLPHjg/001FIX.png
Changed https://i.ibb.co/9b2G0gy/002FIX.png

`$this->add_responsive_control(
			'margin',
			[
				'label' => esc_html__( 'Margin', 'elementor' ),
				'type' => Controls_Manager::DIMENSIONS,
				'size_units' => [ 'px', 'em', '%', 'rem' ],
				//'allowed_dimensions' => 'vertical',
				'placeholder' => '10',
				'selectors' => [
					'{{WRAPPER}}' => '--margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};',
				],
			]
		);`

**Comment by rami-elementor** [comment]
Screenshot from Elementor 3.9.0-dev2 :

![container-margins](https://user-images.githubusercontent.com/92088692/194338648-d23d343a-be4e-4aaa-b703-cf49ddb1c28f.png)

**Comment by theavic** [comment]
I believe the max-width and the min-width properties are still missing
