### ISSUE TITLE
Elementor icon library and content management issue

### ISSUE THREAD

**Issue by sohamrulz** [elementor/elementor#17106]
Hi team,

I have created a website on paid theme - homlisti
URL: https://arkrealestatedubai.com

The icon library isn't opening up. and
I tried to take a backup, and half of the content isn't there.
Please advise

Regards,
Soham

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
