### ISSUE TITLE
sticky mode in elementor 3.6 - dev version

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17112]
hello dear @shilo-ey. I apologize for taking your time.
Prior to version 3.6 elementor, there was a major weakness in the sticky section feature. Now is the best time to correct this weakness. Because version 3.6 is under development.

**Problem statement :**
If in the latest elementor version, which is version 3.4.8, we put two consecutive sections in sticy mode, they will be moved below each other.
**Please watch this video :**

https://user-images.githubusercontent.com/77163248/144763038-40c5ec49-f526-4adf-85ef-96c312aea244.mp4

As you can see in the video above, there were two sections. The upper section had a sticky feature that worked properly after scrolling. **But when I put the bottom section in sticky mode like the top, after scrolling, the top section was hidden.** (It was actually under the lower section.)
But this is not true and it has many limitations. **In fact, after scrolling, the bottom section should stick to the top section. Because both sections have sticky properties.**
The video below is the correct form of this request : 

https://user-images.githubusercontent.com/77163248/144763214-8a4e73d4-e665-4bbf-8495-cffcc96fd443.mp4

As you can see in the video above, after scrolling, both sections moved together. Because they both had sticky properties. This is much better and more logical.

**Suggestions for resolving this issue :**
Please add an option to Motion Effect > sticky, for example called "Dependent".
If we enable this option, two sections that are both sticky will stick together when scrolling. If we do not activate, as in the current situation, they will not stick together.
**Of course, we may not need this option and this mode is enabled by default.**

Please check this option. If there is a question, I will be happy to serve you.

Thank you

**Comment by hettbeans** [comment]
Could you not solve this by setting a sticky offset on the lower section equivalent to the height of the top section?
