### ISSUE TITLE
Section > Responsive > Reverse Columns - does not work for tablet too.

### ISSUE THREAD

**Issue by healiny** [elementor/elementor#17113]
@udidol @DorShahar 
You fixed the bug in Mobil and it works well.
There is another related problem, that the tablet has the exact same bug, needs to be fixed there as well. 
https://www.screencast.com/t/MJPSMHFy

_Originally posted by @healiny in https://github.com/elementor/elementor/issues/16322#issuecomment-981836157_

**Comment by DorShahar** [comment]
Hi @healiny 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly on **Elementor Core 3.5.0**

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

Thanks.

**Comment by healiny** [comment]
@DorShahar 
Hi
This bug belongs to the bug in the previous card. 
https://github.com/elementor/elementor/issues/16322#issuecomment-981836157

It only happens if I change the breakpoint, between the phone and the tablet. 
Thanks.
