### ISSUE TITLE
Header and footer despair after update 

### ISSUE THREAD

**Issue by Matanmu** [elementor/elementor#17117]
After update dev9 to dev14 the header and footer are despairing.
I've try to set it up by click on remove the Instances and save again
[system-info-demo1.get-marketing.co.il-06-12-2021.txt](https://github.com/elementor/elementor/files/7659917/system-info-demo1.get-marketing.co.il-06-12-2021.txt)
.

**Comment by shilo-ey** [comment]
Hi @Matanmu 

Please go ahead to Settings > Experiments and activate the "Container" experiment. this will make sure your content that was built with Containers is available.

Thanks
