### ISSUE TITLE
Elementor + Elementor Pro v3.5.2 breaks WP-CLI

### ISSUE THREAD

**Issue by HushWorkDev** [elementor/elementor#17127]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
On HostGator VPS with fresh install of latest WP v5.8.2 + Elementor 3.4.8 + Elementor Pro 3.5.2.
In Cpanel's SSH Terminal, cd public_html and execute any command that references the wordpress install or plugin and I get the error below. 

When Elementor Pro v3.5.2 is NOT activated, everything WP-CLI works fine.
When Elementor Pro v3.5.2 IS activated, I get the following error in terminal:
my_user_name@my_domain[dot]com [public_html]# wp plugin list
```
Fatal error: Allowed memory size of 41943040 bytes exhausted (tried to allocate 20480 bytes) in /home/my_user_name/public_html/wp-content/plugins/elementor/core/common/modules/connect/apps/base-app.php on line 716
Fatal error: Allowed memory size of 41943040 bytes exhausted (tried to allocate 65536 bytes) in /home/my_user_name/public_html/wp-includes/functions.php on line 3599
```

## Steps to reproduce
Install Elementor and Pro v3.5.2.. then try and execute WP-CLI command example commands: **`wp plugin list`** or even **`wp help`**
Then deactivate Pro v3.5.2, and try a WP-CLI command again.

## Isolating the problem

- [x ] This bug happens when Elementor Pro is installed.
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @HushWorkDev 
Thanks for raising this issue.

It seems like your allowed memory size is beneath the system requirements (128MB minimum)

https://elementor.com/help/requirements/

Thanks

**Comment by HushWorkDev** [comment]
> Hi @HushWorkDev Thanks for raising this issue.
> 
> It seems like your allowed memory size is beneath the system requirements (128MB minimum)
> 
> https://elementor.com/help/requirements/
> 
> Thanks

@shilo-ey yes I can confirm this fixed my issue. Initially, when I saw the error, I assumed it was an issue with memory and I did bump up memory_limit in php.ini to 256M. 

But like you pointed out..
`define( 'WP_MEMORY_LIMIT', '256M' );`

in wp-config DID fix my issue.. thank you for the help.
