### ISSUE TITLE
Bug: Hiding column for tablet doesn't get rid of the space

### ISSUE THREAD

**Issue by leecollings-sb** [elementor/elementor#17135]
I am trying to hide a column for tablets, but when I do this via the checkbox, fair enough the column doesn't show, but I expect the other columns to take up that left over space and re-size.

What happens instead is that a blank space is left where this column should be.

Using Elementor v3.4.8

![Screenshot 2021-12-08 at 15 13 07](https://user-images.githubusercontent.com/12139008/145233253-bafa1886-8365-4b94-88e7-03d612e32914.png)
![Screenshot 2021-12-08 at 15 14 23](https://user-images.githubusercontent.com/12139008/145233274-e8d97494-c6bb-4717-a687-2deb39bc2edf.png)
![Screenshot 2021-12-08 at 15 14 34](https://user-images.githubusercontent.com/12139008/145233281-833c71a0-f9b7-4e08-a45c-aecd37ca321e.png)

**Comment by shilo-ey** [comment]
Hi @leecollings-sb 

Thank you for raising this issue.

This is the way Elementor hidden elements work currently. the logic is that we can manually specify each item's width in a responsive manner.

That's being said, we DO work on a solution that would help you in your use case (Container experiment in dev-edition)

By adding this functionality there- you could use the no-wrap option and to hide specific elements/containers.

Cheers.
