### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17142]
You need to update this https://developers.elementor.com/creating-a-new-widget/

```
( ! ) Deprecated: _content_template is <strong>deprecated</strong> since version 2.9.0! Use Elementor\Controls_Stack::content_template() instead. in C:\wamp\www\_dev\wp-includes\functions.php on line 5211
```

**Comment by udidol** [comment]
Hi @babakfp!
Thank you for your time and attention to detail! You were right. it has now been updated with the updated method names.
