### ISSUE TITLE
elementor Container - Version 3.6.0-dev14

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17149]
hello

1- If we increase or decrease the width of the content using the mouse, the width of the content will increase or decrease with a delay. Not like before. 

https://user-images.githubusercontent.com/77163248/145390776-6ace5095-0464-4f2e-b4bd-0105685868b9.mp4

2-If I'm not mistaken, this bug is related to the previous case. Please watch the video below:

https://user-images.githubusercontent.com/77163248/145390839-e49327a6-a446-4228-8bec-010ecc3fa5a4.mp4

As you can see in the video above, I added a container with two columns. After that, I reduced the size of the right column using the mouse, but the width of the right container was still 50%.
This problem also exists in 4-column containers and so on.

thanks

**Comment by 79ho3ein** [comment]
hello dear @shilo-ey, good time!
A suggestion ....
Isn't it better that the width of the containers is no longer decimal? Now is the best time to solve this option. 
Decimal width seems to be quite an extra item. https://prnt.sc/22h1bh6
what is your opinion?

thanks

**Comment by shilo-ey** [comment]
Hey @79ho3ein 

Thanks for the feedback.

Every container stands on its own and is not part of a column complex- therefore it won't grow when there's no space.


The lag in the resize is a known bug in our resize mechanism and we will handle it along the way.

Closing this issue for now. thanks!
