### ISSUE TITLE
Elementor Toggle items cannot be linked to from Heroic Table of Contents

### ISSUE THREAD

**Issue by onbeschrijflijk** [elementor/elementor#17156]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When combining Elementor with Heroic Knowledge Base, the Heroic table of contents sidebar displays links to the headings used in Elementor blocks. Providing an autoscroll to bring the clicked element's target into view. This should also work for Toggle items when the Toggle Block's "Title HTML Tag" setting is set to H2, H3, etc. It does not work (yet) because the Toggle elements do nog get a relevant`id` attribute. Example: when adding an Elementor Toggle block with titles "Toggle item 1" and "Toggle item 2", it would be nice if the inner `<a>` elements looked like `<a href class="elementor-toggle-title" id="toggle-item-1">` and `<a href class="elementor-toggle-title" id="toggle-item-2">`.

**Describe the solution you'd like**
I would like to see the inner `<a>` element of each toggle title getting an`id` attribute based on the text provided.

**Describe alternatives you've considered**
The `id` attribute could also be added to the `<span>` element for the toggle icon or the ancestral toggle item element with CSS class `elementor-toggle-item`.

**Additional context**
none

**Comment by rami-elementor** [comment]
@onbeschrijflijk 

You can add to all your heading `id` attributes and add links to those `id`s. Only that you will need to name those IDs based on your text.

We are not going to develop this feature as it is not part of our roadmap.

But you can ask "Heroic Knowledge Base" plugin developers to do that. Sound like it's their core functionality.
