### ISSUE TITLE
Bug - footer preview

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#17150]
when inserting a list of icons and the social network widget, when previewing the footer area, the rendering is wrong!
![bugpreview](https://user-images.githubusercontent.com/56270626/145395070-df281fb0-e930-4e23-9fd8-b9ccd639dad8.PNG)

**Comment by shilo-ey** [comment]
Hey @rodolphebertozzo On which version are you?
Please share your system info.

Thanks!

**Comment by rodolphebertozzo** [comment]
@shilo-ey :
<html>
<body>


Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MariaDB Server v10.3.32 |  
PHP Version: | 7.4.25 |  
PHP Max Input Vars: | 2000000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected


</body>
</html>

**Comment by shilo-ey** [comment]
When trying to "Regenerate CSS" in Elementor > Tools > General - it resolves the issue?

Please copy the Experiments section as well and try to deactivate "Inline Icon Fonts" experiment

Thanks.

**Comment by rodolphebertozzo** [comment]
Done. I regenerated the CSS and disabled the experiment, the problem is partly solved
![v1](https://user-images.githubusercontent.com/56270626/145400629-23664db9-759b-4466-a196-19f1a29f5ec5.PNG)
![v2](https://user-images.githubusercontent.com/56270626/145400627-0671ad91-d2e3-4697-866b-48c9ffcc3287.PNG)

**Comment by babakfp** [comment]
Do you have a cache plugin installed? Or maybe your hosting provider is using a cache or a minify system by default.

**Comment by shilo-ey** [comment]
@rodolphebertozzo ?

**Comment by rodolphebertozzo** [comment]
Yes, I checked everything, I have the same problem on other sites, then I repeat, it happens only when you want to preview a specific area of the footer; @shilo-ey, do you have the same problem at home by following the instructions?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
