### ISSUE TITLE
Please allow CSS' calc() value to be inserted as a container width!

### ISSUE THREAD

**Issue by oooh-boi** [elementor/elementor#17151]
PLEASE consider adding the option that allows users to insert the CSS "calc()" function/value! Things are never as simple as percentage or pixels or vw only, mix and match of these is quite often rather crucial!

![add-calc-width](https://user-images.githubusercontent.com/51370907/145412990-77591209-a97f-49bb-947a-a2664843fda0.png)
l

**Comment by babakfp** [comment]
Yes please👌

**Comment by black-eye** [comment]
+1 oooh yes!

**Comment by Matanmu** [comment]
+1

**Comment by thedisturbio** [comment]
@shilo-ey hello, this is necessary in addition to being able to customize the side margins of the containers.

**Comment by perks98** [comment]
+1 yep

**Comment by tekonemedia** [comment]
yess

**Comment by poziomapl** [comment]
+1 Yes! This is very important!

**Comment by jlock6000** [comment]
+1

**Comment by drawcard** [comment]
Let's also add all the CSS math calculations as an option: https://www.w3.org/TR/css-values-4/#comp-func

Could this be done just by having a "Custom" input field, that would let a user put their own custom units / calcs in? 

eg. PX, %, VW, Custom [enter unit / function]

**Comment by babakfp** [comment]
It doesn't need to do anything special. The current functionality of the width field doesn't allow characters other than letters. So, they can disable this functionality, that's all.

**Comment by pauserratgutierrez** [comment]
I feel very limited when creating layouts with Elementor basically because the lack of smart calculations.

I'm designing the Error 404 page with a height of 100% vh so basically I have a full page template. I also want to include my header and my footer. But then the Error 404 page takes more than 100% vh, it takes exactly: (404 height + header height + footer height).

So in this case I would need Elementor to let me set the height of the Error 404 template to be: 100vh - (header height + footer height).

So my suggestion here would be to make Elementor have smart calculations and pull dynamically all data about each of the templates heights and widths, exactly like a Global Color, so that if we change something, it automaticlly updates.

**Comment by perks98** [comment]
I think they just need a custom field for the width and min-height, so like in @pauserratgutierrez example instead of using calc(), you would use max(500px, 100vh - (var(--fixed-header-height) + var(--fixed-footer-height))). So the content doesn't get crushed on smaller height devices while still offering a calculation and the ability to maybe pull in your own custom variables if set elsewhere.

I also agree it would be next level if it could pull in Elementor dynamic CSS variables already in use for some sort of dynamic tag or reference snippet like when doing custom CSS you can use 'selector' to target the parent.

**Comment by babakfp** [comment]
> I feel very limited when creating layouts with Elementor basically because the lack of smart calculations.
> 
> I'm designing the Error 404 page with a height of 100% vh so basically I have a full page template. I also want to include my header and my footer. But then the Error 404 page takes more than 100% vh, it takes exactly: 404 height + (header height + footer height).
> 
> So in this case I would need Elementor to let me set the height of the Error 404 template to be: 100% vh - (header height + footer height).
> 
> So my suggestion here is make Elementor have smart calculations and pull dynamically data about each template's heights, widths... (Exactly how Global Color or Fonts work) so that if we change something, it automaticlly updates.

Dude, they don't even put 5 minutes to work on a very simple problem to make hundreds or maybe thousands of people's jobs easier, and you expect them to do something harder?! You need to lower your expectations **a lot**.

**Comment by pauserratgutierrez** [comment]
> > I feel very limited when creating layouts with Elementor basically because the lack of smart calculations.
> > I'm designing the Error 404 page with a height of 100% vh so basically I have a full page template. I also want to include my header and my footer. But then the Error 404 page takes more than 100% vh, it takes exactly: 404 height + (header height + footer height).
> > So in this case I would need Elementor to let me set the height of the Error 404 template to be: 100% vh - (header height + footer height).
> > So my suggestion here is make Elementor have smart calculations and pull dynamically data about each template's heights, widths... (Exactly how Global Color or Fonts work) so that if we change something, it automaticlly updates.
> 
> Dude, they don't even put 5 minutes to work on a very simple problem to make hundreds or maybe thousands of people's jobs easier, and you expect them to do something harder?! You need to lower your expectations **a lot**.

I already have low expectations HAHAHA, but that doesn't mean we should stop pushing suggeriments. Don't loose faith 👍🏼

**Comment by babakfp** [comment]
> > > I feel very limited when creating layouts with Elementor basically because the lack of smart calculations.
> > > I'm designing the Error 404 page with a height of 100% vh so basically I have a full page template. I also want to include my header and my footer. But then the Error 404 page takes more than 100% vh, it takes exactly: 404 height + (header height + footer height).
> > > So in this case I would need Elementor to let me set the height of the Error 404 template to be: 100% vh - (header height + footer height).
> > > So my suggestion here is make Elementor have smart calculations and pull dynamically data about each template's heights, widths... (Exactly how Global Color or Fonts work) so that if we change something, it automaticlly updates.
> > 
> > 
> > Dude, they don't even put 5 minutes to work on a very simple problem to make hundreds or maybe thousands of people's jobs easier, and you expect them to do something harder?! You need to lower your expectations **a lot**.
> 
> I already have low expectations HAHAHA, but that doesn't mean we should stop pushing suggeriments. Don't lose faith 👍🏼

😂👏 I'm in, all points on faith

**Comment by oooh-boi** [comment]
I have added that option to my add-on "Steroids for Elementor". 
If anyone has a suggestion with regards to the Container improvements - lemme know, I'll be glad to extend it. 

![container-extras](https://user-images.githubusercontent.com/51370907/170814048-d3d9f230-e103-4c43-9fd0-434564641874.png)

**Comment by nicholaszein** [comment]
Hello all! 

This is something that we are planning to bring in the future, and it's part of something more advanced that we've been researching for quite some time. There is already a discussion about this issue, and for the sake of being able to follow all the requests and gather all the feedback as well as understanding the real demand for this new feature, I will be closing this issue and merging it with the issue [#2219](https://github.com/elementor/elementor/issues/2219).

Please continue the conversation there!

Best regards,

Nick
