### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Two requests for "display conditions" feature (Duplicate of #4246)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17167]
hello @avivu 
You said earlier that you are working on the display conditions feature. I had two requests for this great feature, please check it out. They are very excellent and important.

**Feature 1-** Possibility of conditioning based on the input link > Using this option, we can specify that this section be displayed only to users, who come from Instagram. Or be displayed only to users, who come from Google. That's great.

**Feature 2-** Possibility to condition pages > In elementor, all pages have settings as well as an advanced tab. On the other hand, the display conditions settings are also in the advanced tab. It would be great if we could condition the pages with the display conditions feature.
**For example, I want page X to be seen only by registered users. Or, for example, users see the x screen, which uses the iPhone operating system.**
As in the example above, it would be great to see the x screen if the user was ios. If it is not iOS, redirect to the y page. (Possibility of redirect in conditioning)

**A great example of this feature :**

Using this display condition feature, we can specify that if the user has registered, she can enter the settlement sheet. If you have not registered, you will be redirected to the login / registration form. **We implemented this redirect completely with the elementor display conditions feature. this is fabulous.**

I hope you run this. I do not know, maybe you have run it before.

**Comment by 79ho3ein** [comment]
+1

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
