### ISSUE TITLE
column reverse / column order tablet not working

### ISSUE THREAD

**Issue by marketingspectrumNL** [elementor/elementor#17174]
Hi, 

for some reason my column order isn't working on tablet. I'm not working with custom breakpoints just the regular ‘desktop / tablet / mobile’ settings.

Selecting advanced → Responsive → Reverse column (tablet) does nothing. 
Mobile settings works fine.

Tried to restart the computer, clear all browser cache, regenerate CSS. Nothing works? 
Any tips / ideas what to try → or the right CSS to do so?

**Comment by mcrowell** [comment]
+1

**Comment by marketingspectrumNL** [comment]
Yes, reverting to 3.4.8 solves it. Got a css workaround through the forum for those in need.


https://forum.elementor.com/bug-reports-45/column-reverse-column-order-tablet-not-working-10176?postid=31220#post31220

**Comment by parfilov** [comment]
+

**Comment by marketingspectrumNL** [comment]
Added problem.
After updating - live sites that HAD the columns set up right are now also broken. 
Please add priority to the bug.

**Comment by mcrowell** [comment]
Still happening in v 3.5.1

**Comment by ArtyshukPavlo** [comment]
+1 Same issue in v3.5+

**Comment by njspider842** [comment]
Not yet resolved with v 3.5.1

**Comment by ryanlabelle** [comment]
+1 bug seen in 3.5.0 and 3.5.1 (Elementor with Twenty Twenty theme)

**Comment by njspider842** [comment]
Fixed with the 3.5.2 update!

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.5.2

Feel free to update

Thanks everyone!

**Comment by marketingspectrumNL** [comment]
Thanks @arielk !

**Comment by ryanlabelle** [comment]
Nice work @arielk
