### ISSUE TITLE
Header priority/index 

### ISSUE THREAD

**Issue by KristianSaomi** [elementor/elementor#17177]
After updating to: 3.5.0 – 2021-12-14
Once editing with elementor, header section goes under most widgets automaticly (z-index is lower than most elements) 
This does not appear to effect live/preview pages.

**Comment by shilo-ey** [comment]
I merged this issue with #17187, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
