### ISSUE TITLE
Update to an old version, new version disappeared 

### ISSUE THREAD

**Issue by Mahdibeev** [elementor/elementor#17185]
Hello guys, i create a page on wordpress and modify it on elementor. The latest version of this page date of one week ago. But then, while i was looking at it for informations, i realized that the page i was on date of 3 weeks ago. Wordpress get back to an old version and deleted the newest version. What can i do to bring back the newest version ? Thank you in advance.

**Comment by shilo-ey** [comment]
Please make sure you have Safe mode disabled. 

Alternatively, try to rollback to previous version and see if the changes appear again.

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


Thanks.
