### ISSUE TITLE
2 bug in new version of elementor (3.5.0)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17187]
hello

1- In the new version, the header is completely below the content. Of course, this problem only occurs in the editor. To reproduce the bug, please follow these steps :

1- Create a header for the desktop.
2- sticky the header at the top : https://prnt.sc/22zf7rb
3- Create a tab and put the content you want in it. For example, a slider.
4- Now in the editor, scroll down. You will see that the header moves below the content.

https://user-images.githubusercontent.com/77163248/146047254-4f67fdbe-2b32-4f2a-82fa-070597b8e237.mp4

2- The inner section widget does not work properly. I reported this in version 3.5, but it still remains in the official version. I do not know, maybe I'm wrong. When we add the inner section widget, only one section is added. While a main section should be added, and an inner section inside. Like before 3.5.0  **Please watch the video below :**

https://user-images.githubusercontent.com/77163248/146045668-08d915e3-e30a-4a89-96dc-5c6bcbd39732.mp4

**Comment by perks98** [comment]
I literally experienced this yesterday when working on a customer website. Definitely not normal 😅

**Comment by Michaelgimii** [comment]
I experience these too.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Next time please open one ticket per issue.

Thanks!

**Comment by shilo-ey** [comment]
These issues have been resolved in Elementor v3.5.1

Feel free to update

Thanks!

**Comment by 79ho3ein** [comment]
Thank you dear @shilo-ey , please check # 17238. 

Thanks
