### ISSUE TITLE
 Reverse column stopped working for tablet 

### ISSUE THREAD

**Issue by pthorup** [elementor/elementor#17198]
The reverse column stopped working for tablet under Responsive tab after updating to Elementor 3.5.0.

**Comment by pthorup** [comment]
Uhmm seems to work. I reverted back to previous version and updated again and regenerated CSS & Data in each step.

**Comment by shilo-ey** [comment]
I merged this issue with #17174, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
