### ISSUE TITLE
Dark Mode Glitch In 3.5 Update

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#17199]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When 3.5 is active and the editor UI is set to dark mode the overlay for image uploads reflects that of Light Mode instead of Dark Mode. Disabling 3.5 reverts this back to the correct setup.

Below is also a video showing this bug in action. When I disable some CSS it displays correctly.

https://user-images.githubusercontent.com/40209785/146199399-f330f9fc-a496-4773-af3e-3efffd2aa20a.mp4

It looks like editor.min.css is overwriting editor-dark.min.css

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by arielk** [comment]
This issue has been resolved in one of the latest versions

Feel free to update

Thanks!
