### ISSUE TITLE
Bug in adding widgets / Version 3.6.0-dev19

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17207]
hello
1- In the latest version, every widget we add is doubled.

**2- Another thing** is that choosing the widget location in flexbox mode has become very difficult. In one container, I put two images with a width of 50%. Then I wanted to put a text on top of each of these two images. But no matter what I did, I did not succeed. Please check this out, because it's very important. For a better description, please watch the video below :

https://user-images.githubusercontent.com/77163248/146360620-adcf5fa7-8a2e-4ef2-91ac-582a4ae0867c.mp4

(Bug number 1 is also very clear in this video)

**Comment by awakekat** [comment]
I am also getting the Double Widget problem. 
MacOS - 11.6
Chrome - Version 96.0.4664.110 (Official Build) (arm64)
LocalWP local environment
Elementor - 3.6.0-dev19
Elementor Beta (Dev Edition) - 1.1.1
Elementor Pro 3.5.1

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by DesignMike** [comment]
There's also a HUGE bug where all global elements stopped working. Every time I drag a global element into the page, it's just the original element without any of my saved changes.

**Comment by sf-steve** [comment]
Just a quick note to say that the text above image issue seems like expected behaviour - you set the flexbox container direction to row - this causes all the children (the text and the image are siblings) to stack left to right. To get the desired effect, you would need to keep it default (column) , with 1 image and 1 text block per column, and add extra columns.

**Comment by 79ho3ein** [comment]
This bug has been fixed in the dev version.

thank you
