### ISSUE TITLE
Text stroke responsive ability

### ISSUE THREAD

**Issue by alexdalzovo** [elementor/elementor#17212]
as the title suggests, I noticed that the text stroke functionality does not have the responsive capability
<img width="289" alt="Screenshot 2021-12-16 at 20 33 04" src="https://user-images.githubusercontent.com/38038928/146436640-f8a58043-d81e-4eec-acfd-28d029571d32.png">
.

**Comment by alexdalzovo** [comment]
Hi @shilo-ey when will the bug be fixed?

**Comment by rami-elementor** [comment]
Hi @alexdalzovo ,

Thank you for your feedback.

We’re happy to say that the issue you raised was resolved in Elementor 3.6.0

Please feel free to check it out and update your issue. 

Regards,

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!
