### ISSUE TITLE
Ongoing Experiments => Favorite Widgets

### ISSUE THREAD

**Issue by chichille** [elementor/elementor#17219]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I want to add a widget in the favorites
I try and read that in the javascript console

Javascript console = 500 internal server error => xxxx/wp-json/elementor/v1/favorites/widgets?favorite=inner-section
and three more errors

PHP error log:
[17-Dec-2021 12:46:35 UTC] PHP Fatal error:  Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::create_item_permissions_check' not implemented. Must be overridden in subclass. in C:\wamp64\www\eac160\wp-content\plugins\elementor\data\v2\base\controller.php:227
Stack trace:
#0 C:\wamp64\www\eac160\wp-content\plugins\elementor\data\v2\base\base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 C:\wamp64\www\eac160\wp-content\plugins\elementor\data\v2\base\base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 C:\wamp64\www\eac160\wp-includes\rest-api\class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 C:\wamp64\www\eac160\wp-includes\rest-api\class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 C:\wamp64\www\eac160\wp-includes\rest-api\class-wp-rest-server.php(41 in C:\wamp64\www\eac160\wp-content\plugins\elementor\data\v2\base\controller.php on line 227

http://my-domaine/wp-json
Displays site data well

## Steps to reproduce

Ongoing Experiments Favorite Widgets active
Open a page, right click on any widget and 'Add to Favorites'
Close the page and reopen it
The widget is not displayed in favorites

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
Wordpress 5.8.2
Elementor 3.5.0 free version
Only the elementor plugin is active
</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.5.2

Feel free to update

Thanks!
