### ISSUE TITLE
How to properly load Swiper instance

### ISSUE THREAD

**Issue by DeoThemes** [elementor/elementor#17218]
## Prerequisites
- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description
I have searched docs and read all the comments, but still can't get how to load Swiper instance properly. After the recent update, 3.5 Improved Asset Loading is on by default and it breaks all my slider widgets. In my console I'm getting _Uncaught ReferenceError: Swiper is not defined_

**Here is my code that was working before:**

```javascript
var eversorPromoSlider = function ($scope, $) {
        let id = $scope.data("id");
	let slider = $(".eversor-promo-slider-" + id);
	let settings = slider.data("slider-settings");

	if (slider.length > 0) {
	  	var swiper = new Swiper(slider, settings);
	}
}

jQuery(window).on("elementor/frontend/init", () => {
	elementorFrontend.hooks.addAction(
		"frontend/element_ready/deo-promo-slider.default",
		eversorPromoSlider
	);
});
```

**Comment by bdkoder** [comment]
I am also facing the same issue. I need the kind help of someone to fix the issue. And it's urgent.

Anybody here to solve this?

**Comment by DeoThemes** [comment]
From what I understand when **Improved Asset Loading** is active, we can't instantiate Swiper like before. Instead, we need to access Swiper class like so:

```
// Access swiper class
const Swiper = elementorFrontend.utils.swiper;

// It's important to use async / await here since Swiper is now returning Promise.
initSwiper();
async function initSwiper() {
	// Instantiate Swiper
	const swiper = await new Swiper(slider, settings);

	// Now we can access instance methods and events
	swiper.on("slideChange", function () {
		console.log("slide changed");
	}
}
```

Not sure if this is the correct approach but it works with both active/inactive **Improved Asset Loading**. Would like to hear any suggestions from developers.

**Comment by amitsarker89** [comment]
@DeoThemes , I used your codes, but does not work

**Comment by bdkoder** [comment]
@DeoThemes  thank you for your kind help. **It's perfect.** Thank you very much,

**Comment by amitsarker89** [comment]
> @DeoThemes thank you for your kind help. **It's perfect.** Thank you very much,

Do you have any more solutions to fix Swiper issues?

**Comment by DeoThemes** [comment]
@amitsarker89 Can you share your code example?

**Comment by webdevs-pro** [comment]
Here is my working example
```
      if ( 'undefined' === typeof Swiper ) { // Improved Asset Loading enabled
         var asyncSwiper = elementorFrontend.utils.swiper;
          new asyncSwiper( sliderElement, swiperSliderConfig ).then( function( newSwiperSliderInstance ) {
             swiperSlider = newSwiperSliderInstance;
          } );

      } else { // Improved Asset Loading disabled
         swiperSlider = new Swiper( sliderElement, swiperSliderConfig );
      }
      ```

**Comment by DeoThemes** [comment]
@webdevs-pro Great one! This should work as well.

**Comment by amitsarker89** [comment]
> 
Here is my code-
`	var WidgetSliderHandler = function ($scope, $) {
		var slider_el = $scope.find(".slider-two, .slider-one, .slider-three");
		if (slider_el.length === 0)
			return;
		var settings = slider_el.data('settings');
		var interleaveOffset = 0.5;
		var slidervar = new Swiper('.slider-two, .slider-one, .slider-three', {
			navigation: {
				nextEl: '.elementor-swiper-button-next',
				prevEl: '.elementor-swiper-button-prev',
			},
			pagination: {
				el: '.swiper-pagination',
				type: 'bullets',
				clickable: true,
			},
			autoplay: {
				delay: settings.autoplay_speed,
				disableOnInteraction: false,
			},
			effect: settings.content_animation,
			speed: 1000,
			parallax: true,
			loop: true,
			on: {
				progress: function () {
					var swiper = this;
					for (var i = 0; i < swiper.slides.length; i++) {
						var slideProgress = swiper.slides[i].progress;
						var innerOffset = swiper.width * interleaveOffset;
						var innerTranslate = slideProgress * innerOffset;
						swiper.slides[i].querySelector(".slide-inner").style.transform = "translate3d(" + innerTranslate + "px, 0, 0)"
					}
				},
				setTransition: function (speed) {
					var swiper = this;
					for (var i = 0; i < swiper.slides.length; i++) {
						swiper.slides[i].style.transition = speed + "ms";
						swiper.slides[i].querySelector(".slide-inner").style.transition = speed + "ms"
					}
				}
			}
		});

		if ('yes' !== settings.autoplay) {
			slidervar.autoplay.stop();
		}
	};
	$(window).on('elementor/frontend/init', function () {
		elementorFrontend.hooks.addAction('frontend/element_ready/osfins-slider.default', WidgetSliderHandler);
	});`

Would you please suggest to me, how I will integrate your codes to fix my code?

**Comment by bdkoder** [comment]
@amitsarker89 I fixed your code. Please use the below code - 

`var WidgetSliderHandler = function ($scope, $) {
        var slider_el = $scope.find(".slider-two, .slider-one, .slider-three");
        if (slider_el.length === 0)
            return;
        var settings = slider_el.data('settings');
        var interleaveOffset = 0.5;

         const Swiper = elementorFrontend.utils.swiper;
         initSwiper();
         async function initSwiper() {
             var slidervar = await new Swiper('.slider-two, .slider-one, .slider-three', {
                 navigation: {
                     nextEl: '.elementor-swiper-button-next',
                     prevEl: '.elementor-swiper-button-prev',
                 },
                 pagination: {
                     el: '.swiper-pagination',
                     type: 'bullets',
                     clickable: true,
                 },
                 autoplay: {
                     delay: settings.autoplay_speed,
                     disableOnInteraction: false,
                 },
                 effect: settings.content_animation,
                 speed: 1000,
                 parallax: true,
                 loop: true,
                 on: {
                     progress: function () {
                         var swiper = this;
                         for (var i = 0; i < swiper.slides.length; i++) {
                             var slideProgress = swiper.slides[i].progress;
                             var innerOffset = swiper.width * interleaveOffset;
                             var innerTranslate = slideProgress * innerOffset;
                             swiper.slides[i].querySelector(".slide-inner").style.transform = "translate3d(" + innerTranslate + "px, 0, 0)"
                         }
                     },
                     setTransition: function (speed) {
                         var swiper = this;
                         for (var i = 0; i < swiper.slides.length; i++) {
                             swiper.slides[i].style.transition = speed + "ms";
                             swiper.slides[i].querySelector(".slide-inner").style.transition = speed + "ms"
                         }
                     }
                 }
             });

              if ('yes' !== settings.autoplay) {
                  slidervar.autoplay.stop();
              }
              
         };
  
   };

   
   $(window).on('elementor/frontend/init', function () {
       elementorFrontend.hooks.addAction('frontend/element_ready/osfins-slider.default', WidgetSliderHandler);
   });
   `
