### ISSUE TITLE
Problem with navigation Menu hamburger

### ISSUE THREAD

**Issue by Kheurt** [elementor/elementor#17234]
The navigation menu in mode hamburger do not work since Elementor v3. I thought it was v3.5 but I tryed other elementor v3 and it still don't work.
The elementor hamburger menu don't display menu both in mobile device and desktop (instead wordpress' one work)
I found that this issue happened some years ago and the support asked to update both wordpress core and wordpress's plugin to solve the problem. I've upated the core, all plugins, all themes, etc but the problem is still there. I'm trying to solve this for months... (actually 2 months)
Need some help

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

**We tried to recreate the problem, but the nav-menu seems to work on mobile (Hamburger menu).** 
**You are welcome to contact support again and they will help you until the problem will be solved.** 

Thanks.

**Comment by Kheurt** [comment]
Elementor v3 (3.5.0)
WordPress 5.8.2
Elementor Pro installed
PHP 7.4 and 8 tested
