### ISSUE TITLE
Another 3.5 UI Bug

### ISSUE THREAD

**Issue by gilesholder** [elementor/elementor#17240]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Since 3.5 when I toggle reverse content order on Tablet or Mobile it is not reflected in the editor UI. The output is correct but for some reason in the editor is not switching like it used to. This makes it a bit confusing when trying to work on tablet and mobile styling layouts. I have noticed this on a few sites I am working on so its not just limited to one.

Happy to produce a video if you cannot reproduce.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.5.2

Feel free to update

Thanks!
