### ISSUE TITLE
Inner section and global widget

### ISSUE THREAD

**Issue by 43o2d8Bt4R4P8dK9H3j96X9E9M18A4** [elementor/elementor#17257]
Problem with inner-sections, which I already read other users experience same problem.

Also I have problem with global widget: once drag and drop a existing global widget, it loses all of it's design (colors, size, configuration, etc). It's like dropping a whole new widget in the section.

**Comment by TNHSAesop** [comment]
I'm having this issue too, I created a discussion thread on the support website:
https://forum.elementor.com/fixing-common-issues-33/global-widgets-not-working-properly-10633?postid=32573#post32573

**Comment by JidWictut** [comment]
Hello, i have the same issues (inner section and global widget) after updating to ver. 3.5.1 on my staging site :(

**Comment by erikwillemse** [comment]
Hi there, 

I have the same issue and was pointed to this issue. But I had already described my issue and how to reproduce it in https://forum.elementor.com/fixing-common-issues-33/global-widgets-not-working-properly-10633?postid=32707#post32707

I hope this helps to solve it in a next release. 

Thx. Erik

**Comment by bradallenfisher** [comment]
yes, I'm having the same issue. Is this related to #17270?

**Comment by TNHSAesop** [comment]
> yes, I'm having the same issue. Is this related to #17270?

They look to be related yes, but the inner section sections and the global widgets may be two separate bugs.  Would love to hear something from the devs here..

**Comment by bradallenfisher** [comment]
@TNHSAesop YUP I agree. 

Hoping that making some noise here will bump this up. It's a breaking change. You can't add global widgets to the page right now as they have been . Anyone who uses fields on the classic editor in combination with dynamic elementor widgets (as globals) is pretty much screwed. ;)

**Comment by shilo-ey** [comment]
I merged this issue with #17249, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
