### ISSUE TITLE
Adding the possibility to modify the lateral margin in the container, this is very limiting.

### ISSUE THREAD

**Issue by thedisturbio** [elementor/elementor#17268]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

Adding the possibility to modify the lateral margin in the container, this is very limiting.

https://i.ibb.co/Pz19V5k/Captura2.png

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hey @thedisturbio  thanks for reporting!

We improved the container and are going to release it soon to an alpha stage experiment in all versions.

If you encounter any other issue please create a new issue for us to inspect and fix it.

Thanks!
