### ISSUE TITLE
In the new version of elementor, the finder does not work properly.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17266]
hello
In the new version, Finder finds pages built into WordPress, but does not display the templates we used in elementar theme builder in search results. This bug is also present in 3.5.1.
I reported this before on # 17238, but it closed immediately!

**Comment by Michaelgimii** [comment]
+1

**Comment by JakJakson** [comment]
+1 

Assume this is to push the user to the Theme Builder page? :)    But it's more clicks so kinda kills off the whole idea of Ele Finder no?

Please can we have it back?  Pretty please :)

**Comment by 79ho3ein** [comment]
hello @JakJakson , This is a bug. Because it finds the Pages, but not the builder theme templates.

**Comment by Smokey55** [comment]
Searching the templates and migrating between them using the finder is extremely time-saving and useful.
Can we pretty please have the functionality back? Or at least add it in the Experiments Section to have the possibility to either activate it or deactivate it?

**Comment by Heavy-meta** [comment]
+1 

Kindly please add the feature back! It saves so much time when working via the Finder and using the keyboard.

**Comment by 79ho3ein** [comment]
@DorShahar , @shilo-ey . Please check this problem. Thank you

**Comment by 79ho3ein** [comment]
duplicate of #17569
