### ISSUE TITLE
Search for Global Elements/Templates Doesn't Work 3.5.X

### ISSUE THREAD

**Issue by mkiii333** [elementor/elementor#17270]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

After upgrading Elementor to 3.5 and 3.5.1, the search function can't find any saved global elements: https://monosnap.com/file/kZXegAamq0cU1uZtYLldsHclCUGnbm

## Steps to reproduce
Widgets > Global > Search Widgets

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by bradallenfisher** [comment]
Also, all styles and configs have been lost on widgets that were created. If not related let me know and I will file a separate issue.

**Comment by DesignMike** [comment]
I'm having the same issue. Hopefully, the patch this very soon.

**Comment by mkiii333** [comment]
Any news?

**Comment by JidWictut** [comment]
I have the same issue. Elementor 3.5.5 / Pro 3.6.0.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.5.6

Feel free to update

Thanks!
