### ISSUE TITLE
Slides Widget animation (zoom) not working in version 3.5.0+

### ISSUE THREAD

**Issue by wangstein** [elementor/elementor#17271]
Using Slides Widget for a hero slider. Set content animation to "zoom", doesn't not function as expected using Elementor 3.5.0+ and Elementor Pro 3.5.2. Rolled back to Elementor 3.4.8 and Pro 3.4.2 it works as intended.

**Comment by shilo-ey** [comment]
I merged this issue with #17055, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
