### ISSUE TITLE
Problem when adding a widget + impossible to insert an internal section SINCE 3.5.2

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#17284]
Every time I add a widget, it is inserted twice in the page. I can't insert an internal section widget in a column

**Comment by shilo-ey** [comment]
Hey @rodolphebertozzo, there was an issue with the inner section in v3.5.1

A fix has been released.
Please make sure your site doesn't have any cache.

As for the duplicate dragging - this is an issue in the Dev edition and is being fixed.

Thanks
