### ISSUE TITLE
Adding enough products to the new menu cart widget, pushes the checkout and view cart buttons out of view on mobile.

### ISSUE THREAD

**Issue by TowyTowy** [elementor/elementor#17283]
Adding enough products to the new menu cart widget, pushes the checkout and view cart buttons out of view on mobile (happens with enough different products on desktop too.

This is how my cart looks like for starters:
![image](https://user-images.githubusercontent.com/85077986/147132204-558b704b-e609-455f-87e8-4e7c47332629.png)

Then by adding more than 5 items in this instance, pushes the buttons far enough down so they're out of view, and inaccessible, as you can scroll on the cart itself.
![image](https://user-images.githubusercontent.com/85077986/147132348-1eaea525-0bf8-405f-82d6-00a90d505666.png)

I hope I was able to provide enough info, let me know if you need more. I haven't submitted any issues on GitHub before 😬

**Comment by 79ho3ein** [comment]
Finally, someone reported a similar case. I had this problem in the menu cart widget from the beginning, I reported it. I'm not sure if the developers found the problem. (#16333)
This situation is very annoying for users.
