### ISSUE TITLE
Cart icon showing incorrectly after upgrade to 3.5

### ISSUE THREAD

**Issue by Salimoh** [elementor/elementor#17282]
Cart icon no longer show in all my client websites after updating to elementor 3.5. [Here ](https://iranbatri.com/)is an example
screenshot is [here](https://tinyurl.com/yyaphdbd)

**Comment by rami-elementor** [comment]
@Salimoh I see the cart icon in the link.

**Comment by Salimoh** [comment]
the problem has been fixed after elementor 3.7 pro update
