### ISSUE TITLE
Global Widget not working in Elementor 3.5.2 (see #17249)

### ISSUE THREAD

**Issue by JidWictut** [elementor/elementor#17296]
Hello the bug with the global widget you can see here [#17249](https://github.com/elementor/elementor/issues/17249) is not solved.
When i drag a global widget into a new section it loses all it's design.
I hope the issue will be solved soon!

https://user-images.githubusercontent.com/65712457/147387148-43a14a1a-a0e6-4156-b863-bd2969541b2a.mp4

With Kind Regards and Happy Christmas!!!

**Comment by JennG228** [comment]
Same issue with global widget in v3.5.2

**Comment by jp-wolf** [comment]
Ich habe gleiches Problem mit dem Globalen Widget ( v3.5.2 )

**Comment by avivu** [comment]
Hi All,

This issue has been resolved in Elementor v3.5.3

Feel free to update

Thanks!

**Comment by jp-wolf** [comment]
Danke ... funktioniert wieder einwandfrei :-)

**Comment by askwpgirl** [comment]
I believe this update broke how Global Colors and Global Fonts are applied resulting in the inability to override font choice in the Site Settings under Typography; inability to choose font color under Section > Style > Typography; inability to choose button color under Site Settings > Buttons. 

I recommend not doing this update and rolling back this change in Elementor and thinking through this more carefully. Global Fonts and Global Colors should not overwrite everything. And however this "issue" was "fixed" is not correct.
