### ISSUE TITLE
The widget update button gives a error message, and does not do the update.

### ISSUE THREAD

**Issue by Aprentice-01** [elementor/elementor#17294]
The widget update button gives an error message and does not update.

**Comment by arafatjamil01** [comment]
Can you please be more specific?  Which version of Elementor are you using? Is the update you are talking about, being caused when updating a page? What is the error message that you see?

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
