### ISSUE TITLE
Elementor 3.5.2 Bug

### ISSUE THREAD

**Issue by xaviermendozadev** [elementor/elementor#17290]
Elementor 3.5.2 Can't Edit Popup

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by 79ho3ein** [comment]
hi @xaviermendozadev 
Please describe the bug more so we can test. thanks

**Comment by babakfp** [comment]
What is wrong with these people? I see this all the time in this repo that people open a nonsense issue report. Freaking block them.

**Comment by actionTurtle** [comment]
Definitely plugin conflicts... Editing pops up works fine if you don't have all the different elementor add-on plugins

**Comment by DorShahar** [comment]
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
