### ISSUE TITLE
Bug after update to 3.5.2: Any newly adding widget turns into Image with error

### ISSUE THREAD

**Issue by kskonovalov** [elementor/elementor#17291]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
After update to 3.5.2 (latest), any drag and drop widget (I tried inner section, HTML, Heading) turns into Image with '**No data supplied message**'. So it's not possible to add new widget on the page
Screens:
[While adding widget](https://ibb.co/ChB6THS)
[After widget was added](https://ibb.co/MNkqvzw)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
Tried with only Elementor plugin active (even with Elementor Pro disabled)
- [x] This bug happens with a default WordPress theme active.
Bug exists with Hello Elementor theme
- [x] I can reproduce this bug consistently using the steps above.
- [x] I flushed browser cache while testing

**Comment by stasonua0** [comment]
+1

**Comment by kskonovalov** [comment]
I checked it on a new empty installation, and the issue remains. But in incognito both sites I tried with, worked fine.
So I tried to restart my browser, and it helped

**Comment by Gabugbuster** [comment]
Hi @kskonovalov, do you use Safari with an external monitor?

**Comment by Gabugbuster** [comment]
Given that it works in incognito, it can be a conflict with one of the extensions

**Comment by kskonovalov** [comment]
@Gabugbuster I was messed because the external empty installation had the same issue. I tried to disable all extensions, it didn't help
I use Chrome and no external monitor this time
