### ISSUE TITLE
Add “preload=none” to <video> tags, on self hosted videos

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#17308]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need the video to load slowly, I need to add to <video> parameters preload="none"
How is it possible to do this with Elementor?

**Describe the solution you'd like**
https://web.dev/lazy-loading-video/

**Describe alternatives you've considered**
I didn't find alternatives for inline videos

**Additional context**
I have a page with 30 videos (https://trendyvisuals.com/assets), I'm using the overlay Thumbnail but it's still preloading the videos, making the page extremely heavy to scroll.
(Is it possible with background too?)

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can now select the preload attribute for self-hosted videos. 💪 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
