### ISSUE TITLE
Add a SWITCHER control below ICONS control

### ISSUE THREAD

**Issue by AbanobAkram** [elementor/elementor#17305]
Hi there,

Is there a way to add a SWITCHER control after a specific control? For example, can I add a code to insert a switcher to be shown after any ICONS type control?

Look forward to hearing from you.

**Comment by DorShahar** [comment]
Hi 
Please search in our new and updated developers documentation: https://developers.elementor.com/docs/widgets/widget-controls/

**Comment by AbanobAkram** [comment]
Hi @DorShahar 

Actually, I'm asking to extend an Elementor control itself, not adding a control to a widget.

We need to extend Elementor ICONS control with a switcher. So, whenever this control is used in any Elementor widget, that switcher appears below it.

Hope you got our question.
