### ISSUE TITLE
Extra code in the button widget (for example)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17338]
You probably know, but elementor is known for generating extra code. Many people say that you should not use elementor because it generates additional code ...
Of course I do not believe in not using elementor and I believe elementor is great. And I will personally use it as long as it exists.
But yes, as mentioned earlier, unfortunately extra code is generated. For example, let's look at the button widget codes :

button Widget  : https://prnt.sc/25571n0

For example, in the image above, the fill code has no use. But it is written. **More importantly, only 3 lines of code are written for the border. While this is enough** > border : 2px solid #31384A;

This was just one example of a button widget. This is the case in all sections (widgets and sections). If the code is optimized in elementor in the future, elementor will definitely be more wonderful than it is now.

thank you

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

The widget has 3 different controls for button border. Each control updates different CSS property. CSS shorthand are great, but they are limited, you can't create a border shorthand with 4 different width settings.

Regards,
