### ISSUE TITLE
Export any HTML layout template to Elementor .json

### ISSUE THREAD

**Issue by jgabriellima** [elementor/elementor#17336]
Hi, I would like to know if there is already any plugin or library in Python or NodeJS that will export any HTML layout template to .json to use inside elementor, programmatically.
If not exist, where can I find a specification that will help me implement this functionality?
Thanks in advance!

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
