### ISSUE TITLE
✅ 🚀 Feature Request: Disable specific widgets in role manager

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#17340]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When managing sites for clients we don't allow them to use widgets but simply use editor mode where they can only edit text which is great. But there's a middle ground that would be great where we only allow them to use a few specific widgets, based in role but still exclude them from editing a header or footer, but being able to create a new page if they wanted with a few simple widgets we select. 

**Describe the solution you'd like**
A new user role or an addition to the editor role that allows more customization in that you can disable or enable specific widgets for a certain role. So like a mini admin, where they can create new pages with a small amount of select widgets but they still can't edit themes or templates etc. 

**Describe alternatives you've considered**
There's a few other plugins that exist for enabling and disabling widgets but nothing well supported.

**Additional context**
Would be a great addition for those of us that manage sites but the clients want a bit more "control" without giving them everything.

**Comment by black-eye** [comment]
+1

**Comment by nicholaszein** [comment]
Hey guys, I think I missed this one back in 3.19. We released the option to restrict widgets per role in the new Element Manager.

I'm closing this issue as solved.

Kind regards
