### ISSUE TITLE
Elementor 3.5.2 update breaks header, footer and all submenus

### ISSUE THREAD

**Issue by a89s** [elementor/elementor#17342]
Hi.
After updating to Elementor 3.5.2, header, footer and all submenus are broken. I forgot to take a picture, but it looks something like this:
![Screenshot 2021-12-30 at 14 40 06](https://user-images.githubusercontent.com/84576933/147752855-0b99d426-3cff-401e-8e80-6a1ecb7b4777.png)

Anyone else is experiencing this kind of an issue?

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites.**
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
