### ISSUE TITLE
Ability to create a child theme in hello elementor theme.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17361]
Please add the possibility of creating a child theme to the hello elementor theme. This is a wonderful feature. So to meet such a need, we will not need secondary plugins.
This feature can be added to hello elementor or elementor pro. But the best option is hello elementor.

**Comment by rami-elementor** [comment]
Hi @Michaelgimii 

Unfortunately, we are not going to develop this feature. Not for Elementor and not for Elementor Pro.

But, you can use our child theme for "Hello Elementor" theme - https://github.com/elementor/hello-theme-child
