### ISSUE TITLE
Elementor Editor Not Available After Favorite Widgets is Activated (Experiment)

### ISSUE THREAD

**Issue by sstrantz** [elementor/elementor#17364]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When favorite widgets is active in experiments, Elementor editor will not load after first attempt.  Can load editor first time, then successive attempts will not load.  Must log out, then log in to edit each time.  Sometimes the editor is not available at first attempt.  

Inactivating favorite widgets experiment resolves issue.

## Steps to reproduce
Activate favorite widgets experiment.

## Environment
Hello Theme

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Indiana/Indianapolis
	Admin Email: sstrantz@rwps.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

**Comment by itsViney** [comment]
So relieved to have found this issue report. I've been unable to use the Elementor editor for a few days (hanging on the grey loading screen) and and when I saw this I remembered that one of the last things I'd done before the site stopped working was favourite a widget.

For me, the issue didn't present itself until the Favourite Widgets experiment had been turned on **and** I'd favourited at least one widget.

Per @sstrantz 's report, can confirm that disabling the experiment resolves the issue and I'm now able to load the editor again.

**Comment by awakekat** [comment]
I have had the same issue with the favorites widget being activated and then getting the gray screen of death. Once the Favorites is turn off in the experiments, all pages load fine.

**Comment by wpturnedup** [comment]
I'm noticing this is going behind just the first load. There are some templates that won't load at all, while some load just fine, even on the first attempt.

**Comment by bdkoder** [comment]
Hello Friends,
We are also facing the same issue. If we will add widgets as favorites then on the next reload of the page, we are not able to edit any widgets. The editor panel is completely blank.

And on the other website, we are getting another issue also like this. But in this case, we are getting JS errors.
Errors- Uncaught Error: noUiSlider (13.0.0):
Here the issue link - [https://github.com/elementor/elementor/issues/17418](https://github.com/elementor/elementor/issues/17418)

Thanks.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.5.4

Feel free to update

Thanks!

**Comment by lcgitrdone** [comment]
This is prob no longer relevant, but I do want to note one thing for the record.  For me, it wasn't necessary to logout in order to fix the problem.  A cache clear in Chrome worked fine (and is a lot faster).  I just recently switched to Chrome as my main browser, so I didn't realize this issue was a bug.  Figured it was something to do w/ my config.  Thank you.

**Comment by Skiol** [comment]
Hola buen dia amigos, se que sonara raro, pero en mi caso no me funciono ninguno de loa pasos ateriores, y continuo con el mismo problema.
