### ISSUE TITLE
Fatal error bug on wordpress / elementor articles

### ISSUE THREAD

**Issue by ValentinGratz** [elementor/elementor#17366]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

On a friend's site under elementor (all day, latest version), with the creatic theme, we encounter a problem in the articles, on the site page he displays it with the home page link.

In the article management, no articles appear but a fatal error:

```
(pas de titre)
Fatal error: Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::post_row_actions() must be an instance of WP_Post, null given, called in C:\laragon\www\wordpress\wp-includes\class-wp-hook.php on line 303 and defined in C:\laragon\www\wordpress\wp-content\plugins\elementor\includes\template-library\sources\local.php:875 Stack trace: #0 C:\laragon\www\wordpress\wp-includes\class-wp-hook.php(303): Elementor\TemplateLibrary\Source_Local->post_row_actions(Array, NULL) #1 C:\laragon\www\wordpress\wp-includes\plugin.php(189): WP_Hook->apply_filters(Array, Array) #2 C:\laragon\www\wordpress\wp-admin\includes\class-wp-posts-list-table.php(1526): apply_filters('post_row_action...', Array, NULL) #3 C:\laragon\www\wordpress\wp-admin\includes\class-wp-posts-list-table.php(1026): WP_Posts_List_Table->handle_row_actions(NULL, 'title', 'title') #4 C:\laragon\www\wordpress\wp-admin\includes\class-wp-list-table.php(1443): WP_Posts_List_Table->_column_title(NULL, 'title column-ti...', 'data-colname="T...', 'tit in C:\laragon\www\wordpress\wp-content\plugins\elementor\includes\template-library\sources\local.php on line 875
```

I have already seen answers on the forums, out, these do not work. Whether by disabling extensions, and the version of Elementor and the Cretic theme is up to date.

Rendering : 
![image](https://user-images.githubusercontent.com/39189263/147967364-7c312b98-e6e4-40c1-b4a8-5003d6a57654.png)

and what he tells us in the administration:
![image](https://user-images.githubusercontent.com/39189263/147967393-bb46be68-d8d1-460a-871a-7764afdfdd91.png)

## Steps to reproduce

Cannot tell you how to reproduce this problem. Whether online or locally, we have the same problem.

No information that there would be a conflict.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
`
### wp-core ###

version: 5.8.2
site_language: fr_FR
user_language: fr_FR
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\laragon\www\wordpress
wordpress_size: 51,45 Mo (53944724 bytes)
uploads_path: C:\laragon\www\wordpress/wp-content/uploads
uploads_size: 168,61 Mo (176795632 bytes)
themes_path: C:\laragon\www\wordpress/wp-content/themes
themes_size: 77,78 Mo (81560070 bytes)
plugins_path: C:\laragon\www\wordpress/wp-content/plugins
plugins_size: 205,97 Mo (215979782 bytes)
database_size: 30,69 Mo (32178176 bytes)
total_size: 534,49 Mo (560458384 bytes)

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: Cretic Child (cretic-child)
version: 1.3
author: RS Theme
author_website: http://rstheme.com
parent_theme: Cretic (cretic)
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, post-formats, align-wide, custom-header, woocommerce, wc-product-gallery-slider, widgets, editor-style
theme_path: C:\laragon\www\wordpress/wp-content/themes/cretic-child
auto_update: Désactivé

### wp-parent-theme ###

name: Cretic (cretic)
version: 1.6
author: RS Theme
author_website: http://www.rstheme.com
theme_path: C:\laragon\www\wordpress/wp-content/themes/cretic
auto_update: Désactivé

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 2.1, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty: version: 1.8, author: L’équipe WordPress, Mises à jour auto désactivées
Twenty Twenty-One: version: 1.4, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-plugins-active (14) ###

All-in-One WP Migration: version: 7.51, author: ServMask, Mises à jour auto activées
All-in-One WP Migration Unlimited Extension: version: 2.42, author: ServMask, Mises à jour auto désactivées
Breadcrumb NavXT: version: 7.0.1, author: John Havlik, Mises à jour auto activées
CL Testimonial: version: 1.1, author: RS Theme, Mises à jour auto activées
Cmap regions France: version: 5.1, author: Stefan M., Mises à jour auto activées
Contact Form 7: version: 5.5.3, author: Takayuki Miyoshi, Mises à jour auto activées
Elementor: version: 3.5.3, author: Elementor.com, Mises à jour auto activées
Head & Footer Code: version: 1.2.4, author: Aleksandar Urosevic, Mises à jour auto activées
Page Links To: version: 3.3.6, author: Mark Jaquith, Mises à jour auto désactivées
Redux: version: 4.3.5, author: Extendify, Mises à jour auto activées
Rs Addons: version: 1.0, author: RS Theme, Mises à jour auto activées
RS Framework: version: 1.0, author: RS Theme, Mises à jour auto activées
Slider Revolution: version: 6.3.5, author: ThemePunch, Mises à jour auto activées
W3 Total Cache: version: 2.2.1, author: BoldGrid, Mises à jour auto activées

### wp-plugins-inactive (15) ###

Akismet Anti-Spam: version: 4.2.1, author: Automattic, Mises à jour auto activées
All in One SEO: version: 4.1.5.3, author: All in One SEO Team, Mises à jour auto activées
AMP: version: 2.2.0, author: AMP Project Contributors, Mises à jour auto activées
Bitnami Production Console Helper: version: 1.2, author: Bitnami, Mises à jour auto activées
Google Analytics for WordPress by MonsterInsights: version: 8.3.0, author: MonsterInsights, Mises à jour auto activées
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Mises à jour auto activées
Hummingbird: version: 3.2.1, author: WPMU DEV, Mises à jour auto désactivées
Imagify: version: 1.10, author: WP Media, Mises à jour auto désactivées
Jetpack: version: 10.4, author: Automattic, Mises à jour auto activées
MC4WP: Mailchimp for WordPress: version: 4.8.6, author: ibericode, Mises à jour auto activées
One Click Demo Import: version: 3.0.2, author: OCDI, Mises à jour auto activées
Orbit Fox Companion: version: 2.10.10, author: Themeisle, Mises à jour auto désactivées
TaxoPress: version: 3.4.3, author: TaxoPress, Mises à jour auto activées
WP Rollback: version: 1.7.1, author: Impress.org, Mises à jour auto désactivées
Yoast SEO: version: 17.8, author: Team Yoast, Mises à jour auto activées

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Non disponible
imagemagick_version: Non disponible
imagick_version: Non disponible
file_uploads: File uploads is turned off
post_max_size: 2G
upload_max_filesize: 2G
max_effective_size: 2 Go
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
php_version: 7.4.19 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 36000
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 2G
php_post_max_size: 2G
curl_version: 7.70.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.33
client_version: mysqlnd 7.4.19

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\laragon\www\wordpress/wp-content
WP_PLUGIN_DIR: C:\laragon\www\wordpress/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
0: Writable

### redux-framework ###

version: 4.3.5
installation: plugin
data directory: C:/laragon/www/wordpress/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36
	Browser: Chrome
	Version: 96.0.4664.113
	Platform: Windows

### redux-instance-cretic_option ###

opt_name: cretic_option
global_variable: cretic_option
dev_mode: false
ajax_save: true
page_slug: CreticChild
page_permissions: manage_options
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Customizer: 4.0.0
	Import Export: 4.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0
	Search: 3.4.5
	Shortcodes: 4.3.5

`
</details>

Thank you for your help

**Comment by shilo-ey** [comment]
Hey @ValentinGratz 

Thanks for reporting.

In order to verify this issue we need more information.

Does this bug happen with Hello theme active?

**Comment by ValentinGratz** [comment]
It occurs with any theme, Cretic, Hello ...

We do not have more information to provide on this issue.

**Comment by Saga4** [comment]
https://github.com/elementor/elementor/issues/9908#issuecomment-780384449
