### ISSUE TITLE
Widget Person

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#17377]
Create a person widget : https://www.youtube.com/watch?v=-8tRSkewl_o

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
