### ISSUE TITLE
Custom form widget crash when adding steps

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#17375]
I literally just copied and pasted the form widget and edited lines 632 and added lines starting 1866 and it crashes when appearing steps to the form:

<img width="1650" alt="Screenshot 2022-01-04 at 13 24 28" src="https://user-images.githubusercontent.com/1918426/148058715-c62cf889-c7d5-4879-b9fb-1a2ab8c5680f.png">

Code: https://pastebin.com/cy01vhmN

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
