### ISSUE TITLE
Custom post types not showing up in condition settings/Cannot set conditions in templates

### ISSUE THREAD

**Issue by mitchellsl** [elementor/elementor#17389]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Description

When adding a custom post type with either, JetEngine or CPT UI I am unable to link the post type to a previously build template for that specific post type. It does not show my post type in the dropdown (see attached screenshot). I have checked every setting from enabling it in the Elementor settings, from removing and re-adding the post type numerous times
, nothing seems to work. Although it has worked within a dev version, but when i roll back to a previous version it still doesn't show up.
![Schermafbeelding 2022-01-06 om 10 52 37](https://user-images.githubusercontent.com/82220524/148365540-a98e0a0c-42ef-4752-87d0-7843a05c064f.png)

Another issue i'am experiencing which is very annoying, is that I am unable to set my display conditions for pop-ups and every other element. (see attached screenshot)

The condition modal shows but I am unable to see any options, let alone click them. 
![Schermafbeelding 2022-01-06 om 10 57 22](https://user-images.githubusercontent.com/82220524/148365500-e7761ad9-bdbf-46f2-ab74-cfa9e7ee2dbe.png)

**Comment by DorShahar** [comment]
@mitchellsl , Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

**Without it, we simply can't help.**

Thanks.
