### ISSUE TITLE
Use Elementor inside Angular app

### ISSUE THREAD

**Issue by Aventrue** [elementor/elementor#17409]
Is it possible to include elementor inside an angular application? 
I'm an application developer an it would be possible that I adapt the code to it. 
Is Elementor just running inside the browser (javascript, without php)?

**Comment by rtpHarry** [comment]
It has some JavaScript front end components but the overall system is deeply integrated into WordPress and php code.

**Comment by Aventrue** [comment]
Do you think it's really complicated to use the drag and drop editor outside wordpress? 
Can you give me a hint in which javascript file is a good starting point to adapt?
Thank you very much for you help :)

**Comment by sf-steve** [comment]
thats a huge project, that would absolutely not be worth the time - it would be unsupported, undocumented, and require constant patching as the main elementor repo gets upgrades (which happen a LOT).

If you want to enable an elementor like UI in a custom js application, i would suggest an open source library made for the job would be a thousand times better a starting point. https://grapesjs.com would be a good start

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
