### ISSUE TITLE
Column Slideshow - ACF Gallery Issue

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#17402]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
 
If you try to set an ACF Gallery as a slideshow option in Column > Background Type > Slideshow nothing is displayed. This seems silly as there is the option for a dynamic tag.

When I use the carousel widget, gallery etc everything works as expected with the ACF Gallery and the images are displayed. So for this, it cant be an ACF issue or image issue.

## Steps to reproduce

> Edit a Column
> Open Style Options
> Under Background Type "Select Slideshow"
> Select the dynamic tag icon and assign an ACF Gallery to it
> Result = nothing is displayed

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by gilesholder** [comment]
When I check the markup I am seeing this: style="background-image: url(undefined;);"

Console Error: GET https://www.thelifestylecard.co.uk/lp/weymouth-fc/undefined 404

I have the ACF Gallery set to return an Array however when I change to return a URL a critical WordPress error message is displayed.

**Comment by rami-elementor** [comment]
Sounds like and ACF issue. If you could set it to return a URL it should be fixed.

**Comment by hitsgee** [comment]
I tested it with various return outputs, including URL, and it does not work. It works fine if I create a slider widget with ACF just not if I try to use the ACF dynamic tag in the column slideshow. If I set the slideshow with static images (not dynamic) it works fine so I know that works. I have also had this issue on a few sites so its not a one off.
