### ISSUE TITLE
Container centering not working

### ISSUE THREAD

**Issue by zierbeek** [elementor/elementor#17415]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest development version of Elementor.

## Description

I have created several containers and set them to align to the center, they do in the preview, when generating the live page, it does not. 

## Steps to reproduce

Create new section
Add 3 containers 33,33% width each
add icon box
Center

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ x] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v5.6.49-89.0
	PHP Version: 8.0.8
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://dejaegher-bouwmaterialen.be
	Home URL: https://dejaegher-bouwmaterialen.be
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%slug%/
	Language: nl-BE
	Timezone: 1
	Admin Email: borremans.matthias@outlook.be
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_BE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15

== Active Plugins ==
	Advanced AJAX Product Filters for WooCommerce
		Version: 1.6.1.1
		Author: BeRocket

	Autoptimize
		Version: 2.9.5
		Author: Frank Goossens (futtta)

	Cloudflare
		Version: 4.7.0
		Author: Cloudflare, Inc.

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Cookiebot | GDPR/CCPA Compliant Cookie Consent and Control
		Version: 3.11.3
		Author: Cybot A/S

	Duplicate Page
		Version: 4.4.7
		Author: mndpsingh287

	Elementor
		Version: 3.6.0-dev27
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev3
		Author: Elementor.com

	Events Tracker for Elementor
		Version: 1.2.9
		Author: wpl.agency

	MWB Product Filter for WooCommerce
		Version: 2.0.0
		Author: MakeWebBetter

	Opening Hours
		Version: 2.3.0
		Author: Jannik Portz

	Product Filter by WooBeWoo
		Version: 2.0.5
		Author: WooBeWoo

	Site Kit by Google
		Version: 1.48.1
		Author: Google

	WooCommerce
		Version: 6.0.0
		Author: Automattic

	YITH WooCommerce Catalog Mode
		Version: 2.5.0
		Author: YITH

	Yoast SEO
		Version: 17.8
		Author: Team Yoast

== Elementen gebruik ==
	
	archive : 2
		archive-posts : 2
		button : 2
		heading : 6
		image : 2
		theme-archive-title : 2
	footer : 2
		button : 1
		container : 4
		divider : 2
		form : 1
		heading : 6
		icon : 1
		icon-list : 4
		image : 1
		media-carousel : 1
		nav-menu : 2
		social-icons : 1
		text-editor : 3
		theme-site-logo : 1
		wp-widget-widget_op_overview : 2
	header : 2
		button : 1
		html : 1
		nav-menu : 2
		shortcode : 1
		theme-site-logo : 2
	page : 3
		button : 8
		heading : 13
		image : 6
		image-carousel : 4
		testimonial-carousel : 1
		text-editor : 4
	single : 5
		button : 3
		divider : 2
		heading : 14
		icon : 8
		image : 1
		post-info : 4
		post-navigation : 4
		posts : 4
		share-buttons : 6
		social-icons : 1
		spacer : 5
		text-editor : 3
		theme-post-content : 4
		theme-post-featured-image : 2
		theme-post-title : 3
	wp-page : 18
		button : 34
		call-to-action : 2
		container : 34
		flip-box : 3
		form : 1
		google_maps : 1
		heading : 55
		html : 2
		icon-box : 17
		icon-list : 2
		image : 11
		image-carousel : 1
		posts : 1
		shortcode : 4
		sitemap : 1
		spacer : 3
		tabs : 1
		text-editor : 14
		woocommerce-products : 1
		wp-widget-widget_op_overview : 2
	error-404 : 1
		button : 1
		heading : 3
		image : 3

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Inline lettertype iconen: Actief
	Toegang verbeteringen: Actief
	Import export template kit: Actief
	Extra aangepaste onderbrekingspunten: Actief
	Hide native WordPress widgets from search results: Actief
	Container: Actief
	: Standaard inactief
	Default to New Theme Builder: Actief
	Hello Theme Header & Footer: Actief
	Landingspagina's: Actief
	Kleur sampler: Actief
	Favoriete widgets: Actief
	Beheerder bovenste balk: Actief
	Page Transitions: Actief
	Form Submissions: Actief
	Scroll Snap: Actief

== Log ==
	
Log: showing 20 of 372022-01-03 21:13:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev24',
  'to' => '3.6.0-dev25',
)]
2022-01-06 12:31:06 [info] elementor-pro::elementor_pro_updater Started 
2022-01-06 12:31:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-06 12:31:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-06 12:31:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev15',
  'to' => '3.7.0-dev2',
)]
2022-01-06 12:31:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev15',
  'to' => '3.7.0-dev2',
)]
2022-01-06 12:31:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev15',
  'to' => '3.7.0-dev2',
)]
2022-01-06 18:06:06 [info] elementor::elementor_updater Started 
2022-01-06 18:06:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-06 18:06:07 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-06 18:06:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev25',
  'to' => '3.6.0-dev26',
)]
2022-01-07 17:37:13 [info] elementor::elementor_updater Started 
2022-01-07 17:37:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-07 17:37:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev26',
  'to' => '3.6.0-dev27',
)]
2022-01-07 17:37:14 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-07 17:37:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev26',
  'to' => '3.6.0-dev27',
)]
2022-01-07 18:15:47 [info] elementor-pro::elementor_pro_updater Started 
2022-01-07 18:15:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-07 18:15:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-07 18:15:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev2',
  'to' => '3.7.0-dev3',
)]

PHP: showing 5 of 5PHP: 2021-12-06 09:33:33 [notice X 1][/www/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-26 20:12:12 [notice X 1][/www/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-03 11:18:26 [error X 1][/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(2155, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#5 /www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /www/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element... [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-07 14:01:36 [warning X 2][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-08 15:42:16 [warning X 2][/www/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibiliteit niet gespecificeerd
	Events Tracker for Elementor: Compatibiliteit niet gespecificeerd

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
Thanks, this issue has been resolved and will be released soon,

thanks for reporting
