### ISSUE TITLE
Product Grid "Compare" Button Customize Text

### ISSUE THREAD

**Issue by alstrar** [elementor/elementor#17420]
I'd like to change the "Compare" button to the Swedish "Jämför" if that's possible to add to the Product Grid?

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
