### ISSUE TITLE
Logo misplacement after developer update

### ISSUE THREAD

**Issue by SXYDjango92** [elementor/elementor#17436]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
System Info Link:
Link: https://pastebin.com/A7kbcP6m
Password: yakMh9ynRe

Link to issue: https://spencerschotel.com/2021/10/05/xlmg/
XL logo on timeline is glitched after updating. 

I have checked elementor and it is displayed normally within the editor. This only occurred after updating.

</details>

**Comment by SXYDjango92** [comment]
This is my first issue, apologies if it is formatted oddly.

**Comment by DorShahar** [comment]
Hi @SXYDjango92 ,Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites**.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
