### ISSUE TITLE
Erro  Jquery Elementor

### ISSUE THREAD

**Issue by JheimisonFLX** [elementor/elementor#17449]
![image](https://user-images.githubusercontent.com/82410880/148966645-aa740eb9-bfcf-441d-a67c-458c39a7fb46.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
