### ISSUE TITLE
Deprecated code in PHP 8.1

### ISSUE THREAD

**Issue by Camilo517** [elementor/elementor#17446]
Deprecated: Return type of Elementor\Core\Utils\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/utils/collection.php on line 404

Deprecated: Return type of Elementor\Core\Utils\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/utils/collection.php on line 413

Deprecated: Return type of Elementor\Core\Utils\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/utils/collection.php on line 421

Deprecated: Return type of Elementor\Core\Utils\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/utils/collection.php on line 432

Deprecated: Return type of Elementor\Core\Utils\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/utils/collection.php on line 446

Deprecated: Return type of Elementor\Core\Utils\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/utils/collection.php on line 439

Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in /var/www/vhosts/web.es/httpdocs/wp-content/plugins/elementor/core/upgrade/manager.php on line 62

**Comment by rami-elementor** [comment]
Thanks for reporting,

Please follow guidelines for opening a new issue report, so we can help you better.

This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
