### ISSUE TITLE
Logo misplacement

### ISSUE THREAD

**Issue by SXYDjango92** [elementor/elementor#17440]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

System Info Link: https://pastebin.com/A7kbcP6m Password: yakMh9ynRe 

```
</details>

I was asked to start a issue report, previous post is located at https://github.com/elementor/elementor/issues/17436

It seems that when using elementor which is built in to be used with my theme, the logos are misplaced despite being displayed as normal in the editor - I haven't had this issue before, only when updating to the Developer Edition. 

Link of Issue: https://spencerschotel.com/2021/10/05/xlmg/

I am not sure what is directly causing this.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
