### ISSUE TITLE
I'm getting duplicate blocks each time I add a block

### ISSUE THREAD

**Issue by WebWeaver64** [elementor/elementor#17452]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest development version of Elementor.

## Description

Each block I've tried to add has added a duplicate. I've left the page and re-entered the page and the issue continues.

## Steps to reproduce
Add a block, and you get two blocks added.
See it in action: https://www.screencast.com/t/GaaZuhSaW3Yp

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ x ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.27
	PHP Version: 7.4.27
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://shari-playground.com
	Home URL: https://shari-playground.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: shari@websupportgoddess.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 2.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.2
		Author: WordPress Contributors

	Dashboard Widgets Suite
		Version: 3.0
		Author: Jeff Starr

	Elementor
		Version: 3.6.0-dev28
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev4
		Author: Elementor.com

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP Maintenance
		Version: 6.0.4
		Author: Florent Maillefaud

	WSG Helper Plugin
		Version: 3.0
		Author: Shari Lynn Smith

== Elements Usage ==
	
	wp-post : 1
		html : 1
		progress : 1
		text-editor : 1
	wp-page : 5
		animated-headline : 4
		call-to-action : 2
		divider : 1
		heading : 2
		image : 1
		image-box : 1
		price-list : 1
		spacer : 1
		text-editor : 3

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Container: Inactive by default
	: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 422021-12-17 19:43:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev19',
  'to' => '3.6.0-dev20',
)]
2021-12-17 19:43:52 [info] elementor::elementor_updater Started 
2021-12-17 19:43:52 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-17 19:43:53 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-17 19:43:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev19',
  'to' => '3.6.0-dev20',
)]
2021-12-20 23:15:22 [info] elementor::elementor_updater Started 
2021-12-20 23:15:22 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-20 23:15:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev20',
  'to' => '3.6.0-dev21',
)]
2021-12-20 23:15:22 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-20 23:15:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev20',
  'to' => '3.6.0-dev21',
)]
2021-12-20 23:15:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev20',
  'to' => '3.6.0-dev21',
)]
2022-01-11 20:23:44 [info] elementor::elementor_updater Started 
2022-01-11 20:23:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-11 20:23:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-11 20:23:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev21',
  'to' => '3.6.0-dev28',
)]
2022-01-11 20:39:22 [info] elementor-pro::elementor_pro_updater Started 
2022-01-11 20:39:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-11 20:39:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-11 20:39:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev20',
  'to' => '3.7.0-dev4',
)]
2022-01-11 20:39:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev20',
  'to' => '3.7.0-dev4',
)]

PHP: showing 1 of 1PHP: 2021-12-15 21:21:00 [error X 2][/home/shariste/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/shariste/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/shariste/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/shariste/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/shariste/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/shariste/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/shariste/public_html/wp-includes/class-wp-hook.php(303): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home/shariste/public_html/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
Thanks, this issue occurs in the latest dev editions.

I merged this issue with #17484, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
