### ISSUE TITLE
Elementor Experiments Icon Bug

### ISSUE THREAD

**Issue by k25hoops** [elementor/elementor#17458]
I have noticed that many of the icons do not display properly unless "Inline Font Icons" is active in Settings>Experiments. However, the menu cart widget for Elementor does not display properly on mobile or tablet when "Inline Font Icons" is selected. I have tested this on multiple sites and had the same error when trying to use icons and a menu cart widget. 

The problem = when you activate "Inline Font Icons" to fix the icon problem (icons showing as squares), the menu cart widget stops working on mobile and tablet.

**Comment by Squeezemind** [comment]
I can confirm this too
