### ISSUE TITLE
Video Popup not working

### ISSUE THREAD

**Issue by hainguyenhd** [elementor/elementor#17461]
Hello team,

In latest version, when i use Video element and enable lightbox, it doesn't work.
Press the Play button and the video doesn't show up
https://ibb.co/pfcLXTZ

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
