### ISSUE TITLE
Add possibility do disable live update editor for widgets

### ISSUE THREAD

**Issue by jacktaffa** [elementor/elementor#17463]
Often, for some widget ajax requests for live update on elementor editor become very heavy(example forms), and elementor for every edit send an ajax request, it could make very slow editing of simple pages.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #9647, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @jacktaffa!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
