### ISSUE TITLE
Every template with no "wp_content" tag are uneditable

### ISSUE THREAD

**Issue by dibeja** [elementor/elementor#17483]
Hello, 
After Elementor 3.5.3 and Elementor Pro 3.5.2 update I'm unable to edit ANY template that has no "wp_content" tag in it.
I cannot edit:
- header
- footer
- sections

I can edit:
- pages
- single
- archives
- popups

Anyone with the same issue?

**Comment by DorShahar** [comment]
Hi
Please see here: https://elementor.com/help/the-content-area-was-not-found-error/

If you still request help, you are welcome to ask our Support team.

Thanks
