### ISSUE TITLE
How to change products per page

### ISSUE THREAD

**Issue by choijun** [elementor/elementor#17489]
Hi guys,

I am using Elementor Pro 3.5.2 and my question is : How can I change the total products per page on the product category page ?

Looking forward to your response.

Thank you.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
