### ISSUE TITLE
Added spacing between the category title and the items in the widget Site Map

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#17495]
Simply add a margin at the bottom of the .elementor-sitemap-title element, like this, on line 421 of the widget :

`$this->add_responsive_control(
			'bottom_space',
			[
				'label' => esc_html__( 'Spacing', 'elementor-pro' ),
				'size_units' => [ 'px', '%', 'vw' ],
				'type' => Controls_Manager::SLIDER,
				'range' => [
					'px' => [
						'min' => 0,
						'max' => 1000,
					],
					'%' => [
						'min' => 0,
						'max' => 100,
					],
					'vw' => [
						'min' => 0,
						'max' => 100,
					],
				],
				'selectors' => [
					'{{WRAPPER}} .elementor-sitemap-title' => 'margin-bottom: {{SIZE}}{{UNIT}};',
				],
			]
		);`

**Comment by rami-elementor** [comment]
Thanks for reporting,

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
