### ISSUE TITLE
🔗 🚀 Feature Request: Table Element (Duplicate of #1342)

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#1749]
I would really love to see a Table Element wherein we can add data into the rows live, along with HTML support, and header sorting feature.

I know this can be currently achieved using plugins like TablePress but I have a requirement wherein each page needs to have a table with sortable headers, HTML input and responsiveness requirement wherein creating all the tables in TablePress (adding HTML in TablePress cells using their backend interface is a tedious task of writing all the HTML codes manually) and adding shortcodes in all the pages is a difficult task.

I think others might also have this sort of requirement and I believe that the Table element would make up as a very good addition to the library of elements available in Elementor.

Thanks for this awesome page builder!

**Comment by arielk** [comment]
I merged this issue with another issue #1342 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
