### ISSUE TITLE
2 BUG in elementor 3.6.0-dev31 

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17504]
hello

1- If we have a container with two columns, copy and paste the style of one column in the other column, the width of the previous column will also be transferred. This was not the case before. (The video below)

https://user-images.githubusercontent.com/77163248/149889545-a12532f4-3e50-42ac-a0f2-00e065716283.mp4

2- The height of the two columns in the container depends on each other. If it should not be so. I increase the height of the container on the left, but the container on the right also increases with it. (The video below)

https://user-images.githubusercontent.com/77163248/149891261-86947f09-afe4-4f87-b2a8-5faee2098649.mp4

thank you

**Comment by perks98** [comment]
Hi @79ho3ein,
I thought I'd try and replicate but I'm not sure if I see the problem you are reporting, I think Elementor has added those parts as more of a feature I think.

1. With the old sections I've always had the issue of copying and pasting and the columns would shift, example vid:

https://user-images.githubusercontent.com/55829113/149920408-141ddb60-daaa-4d45-9598-b9763e77bc39.mp4



2. With the old sections the default for columns would be that they would be the same height unless you mess with the alignment. With the new containers you need to play with the 'Align Items' part, example vid:

https://user-images.githubusercontent.com/55829113/149920430-21718bce-4520-4e83-97ca-62b20c1b43e9.mp4



I'm still learning about the new containers too so let me know if I'm understanding you wrong 😀. I would say it would be great to lock options in so they don't transfer when copying and pasting as I've had issues with it copying background images and moving that over too.

**Comment by 79ho3ein** [comment]
> Hi @79ho3ein, I thought I'd try and replicate but I'm not sure if I see the problem you are reporting, I think Elementor has added those parts as more of a feature I think.
> 
> 1. With the old sections I've always had the issue of copying and pasting and the columns would shift, example vid:
> 
>  2022-01-18.10-25-10.mp4 
> 2. With the old sections the default for columns would be that they would be the same height unless you mess with the alignment. With the new containers you need to play with the 'Align Items' part, example vid:
> 
>  2022-01-18.10-19-23.mp4 
> I'm still learning about the new containers too so let me know if I'm understanding you wrong 😀. I would say it would be great to lock options in so they don't transfer when copying and pasting as I've had issues with it copying background images and moving that over too.

It is true.
