### ISSUE TITLE
🔗 🚀 Feature Request: Accordions need an option to be closed by default. (Duplicate of #2756)

### ISSUE THREAD

**Issue by pinkgerbils** [elementor/elementor#17507]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate*
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

***This issue was previously acknowledge and wrongly closed after being 'fixed' in version 1.8 back in 2017 but this update never happened - please re-open the original ticket!**

**What problem is your feature request going to solve? Please describe.**
Accordions are designed to show/hide content based on user interaction, mainly via clicking a link. In many cases designers wish for all accordion content to be closed when the page first loads, however Elementor will always open the first accordion by default giving the user no choice but to show the first section of content.

Toggles are closed by default so it makes no sense to force accordions to be open as the design ethos behind both elements is exactly the same.

**Describe the solution you'd like**
Add a simple option to allow the option for web designers to close all accordions by default.

**Describe alternatives you've considered**
Custom Javascript & creating a blank accordion box which can then be hidden with css.

**Additional context**
Issue is 5 years old. Original ticket on GitHub was acknowledged and wrongly closed as fixed.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2756, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
