### ISSUE TITLE
Video Background Not Loading Until Scroll Page

### ISSUE THREAD

**Issue by martynthinklazy** [elementor/elementor#17502]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

When loading a page with a video background, the video will not load until the page is scrolled. You may see this in the Chrome Inspector console that the video is only called after page scrolling begins.

## Steps to reproduce

Load the following page:
https://kaiaponi.co.nz

The video background will not load.

Scroll the page to see the video load.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

Chrome browser

**Comment by rami-elementor** [comment]
Thanks for reporting, we can't reproduce the issue. May be it's not an Elementor issue, maybe it's a 3rd party plugin. 

Please follow guidelines for opening a new issue report, so we can help you better.

This report is missing key information: 

* Steps to replicate
* System info

Without it we simply can't help.

Thanks.
