### ISSUE TITLE
Problem with Gallery widget

### ISSUE THREAD

**Issue by steve-manes** [elementor/elementor#17501]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

While editing existing Elementor page from last year, I ran into a fairly serious issue with the mapping of the Gallery widget to the editor page. It shows up in the column as only a pair of closely-spaced horizontal lines. You have to go into Navigator to actually see what it is but you can't edit it. Clicking on Edit Gallery in Navigator does nothing. 

However, the gallery is clearly there.  See: https://annabelgreen.com/seasonal-valentines-day/

## Steps to reproduce

1. Opened a page with an existing Gallery widget.
2. The above is what I get.
3. This is happening with all Gallery widgets on this site.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
System Info
			
				Server Environment
			
						
				Operating System:
					Linux
					
						
				Software:
					Apache/2.4.29 (Ubuntu)
					
						
				MySQL version:
					MySQL Community Server (GPL) v5.7.36
					
						
				PHP Version:
					7.4.27
					
						
				PHP Max Input Vars:
					1000
					
						
				PHP Max Post Size:
					64M
					
						
				GD Installed:
					Yes
					
			
				ZIP Installed:
					Yes
					
				Write Permissions:
					There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
		 - .htaccess file
					
						
				Elementor Library:
					Connected
					
			
				WordPress Environment
					
						
				Version:
					5.8.3
					
						
				Site URL:
					https://annabelgreen.com
					
						
				Home URL:
					https://annabelgreen.com
					
						
				WP Multisite:
					No
					
						
				Max Upload Size:
					64 MB
					
						
				Memory limit:
					512M
					
			
				Permalink Structure:
					/%postname%/
					
						
				Language:
					en-US
					
						
				Timezone:
					America/New_York
					
			
				Admin Email:
					steve@stevemanes.com
					
			
				Debug Mode:
					Inactive
					
			
![Screen Shot 2022-01-17 at 1 02 50 PM](https://user-images.githubusercontent.com/60283625/149820066-14ff66bc-0e05-4291-9cf1-77b218f1377d.png)

			
				Theme
					
						
				Name:
					Astra Child
					
			
				Version:
					1.0.0
						
				Author:
					Brainstorm Force
					
			
				Child Theme:
					Yes
					
			
				Parent Theme Name:
					Astra
					
			
				Parent Theme Version:
					3.7.6
					
			
				Parent Theme Author:
					Brainstorm Force
					
			
				User
					
						
				Role:
					administrator
					
						
				WP Profile lang:
					en_US
					
						
				User Agent:
					Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
					
			
				Active Plugins
					
					
					Advanced Editor Tools (previously TinyMCE Advanced) - 5.6.0
						By Automattic
						
								
					Akismet Anti-Spam - 4.2.1
						By Automattic
						
								
					Astra Pro - 3.6.5
						By Brainstorm Force
						
								
					Astra Widgets - 1.2.9
						By Brainstorm Force
![Screen Shot 2022-01-17 at 1 03 10 PM](https://user-images.githubusercontent.com/60283625/149820080-ed9b377e-c781-4f07-9b90-a3fcfb2ff27f.png)

						
				
					Better Search Replace - 1.3.4
						By Delicious Brains
						
								
					bunny.net - 1.0.8
						By bunny.net
						
								
					Classic Editor - 1.6.2
						By WordPress Contributors
						
								
					Elementor - 3.5.3
						By Elementor.com
						
				
					Elementor Contact Form DB - 1.7
						By Sean Barton - Tortoise IT
						
								
					Elementor Pro - 3.5.2
						By Elementor.com

								
					Essential Addons for Elementor - 5.0.1
						By WPDeveloper
						
								
					Essential Addons for Elementor - Pro - 5.0.1
						By WPDeveloper
						
								
					Extras for Elementor - 2.2.51
						By Namogo
						
								
					GA Google Analytics - 20210719
						By Jeff Starr

								
					Insert Headers and Footers - 1.6.0
						By WPBeginner
						
					iThemes Security - 8.0.2
						By iThemes
						
								
					JetMenu - 2.1.4
						By Crocoblock
						
								
					Make Column Clickable Elementor - 1.3.1
						By Fernando Acosta
						
				
					OnePress Image Elevator - 2.6.2
						By OnePress
						
								
					Optimize Database after Deleting Revisions - 5.0.110
						By CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands
						
								
					Popup Maker - 1.16.3
						By Popup Maker
						
								
					reSmush.it Image Optimizer - 0.4.2
						By reSmush.it
						
								
					Simple Custom CSS and JS PRO - 4.23
						By SilkyPress.com
						
								
					Stop Spammers - 2021.20
						By Trumani
								
					TinyMCE Custom Styles - 1.1.2
						By Tim Reeves (original author David Stöckl)
						
								
					Ultimate Addons for Elementor - 1.36.1
						By Brainstorm Force

								
					Wordfence Security - 7.5.7
						By Wordfence
						
								
					WP Rocket - 3.10.6
						By WP Media
						
				
					Yoast SEO - 17.9
						By Team Yoast
						
			
				Elementor Experiments
					
					
Optimized DOM Output: 	Inactive by default
Improved Asset Loading: 	Inactive by default
Improved CSS Loading: 	Inactive by default
Inline Font Icons: 	Inactive by default
Accessibility Improvements: 	Inactive by default
Import Export Template Kit: 	Active by default
Additional Custom Breakpoints: 	Inactive by default
Hide native WordPress widgets from search results: 	Active by default
Default to New Theme Builder: 	Active by default
Landing Pages: 	Active by default
Color Sampler: 	Active by default
Favorite Widgets: 	Active by default
Admin Top Bar: 	Active by default
Form Submissions: 	Active by default
Scroll Snap: 	Inactive by default

**Comment by steve-manes** [comment]
I found the culprit. Something in Essential Addons for Elementor was causing this.  Disabling it was the fix.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
