### ISSUE TITLE
Heading control do not render description argument

### ISSUE THREAD

**Issue by webdevs-pro** [elementor/elementor#17512]
Elementor Heading control do not render description argument but support of this argument is described in documentation. https://developers.elementor.com/docs/controls/classes/control-heading/

Here is Heading control template:
```
<script type="text/html" id="tmpl-elementor-control-heading-content">
   <div class="elementor-control-content">
      <div class="elementor-control-field">
         <h3 class="elementor-control-title">{{{ data.label }}}</h3>
      </div>
   </div>
</script>
```

**Comment by rami-elementor** [comment]
Hi @webdevs-pro ,

The `description` argument is inherited from `Base_Control`. The base class supports several arguments applied to all the controls that extend the base control.

See this Dev Doc: https://developers.elementor.com/docs/controls/labels-description/
