### ISSUE TITLE
navigator hidden

### ISSUE THREAD

**Issue by martinleeseo** [elementor/elementor#17516]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If there is too much material on the site, the surfer will be able to choose what he needs to read.
  That way he does not have to scroll down and go through the whole page.
He gets only what he is looking for

**Describe the solution you'd like**navigator__element--hidden
Give a web surfer (client side) a check box
When he ticks the box the same sectin is revealed
The idea that all sectin will be in a hidden state
And the surfer will choose what suits him with the help of the check box

**Describe alternatives you've considered**
Despite many searches I did not find anything close to this request
**Additional context**
![image](https://user-images.githubusercontent.com/20929701/150124759-acc9f8c9-ca7d-42f6-a755-29f0903510a8.png)

**Comment by DorShahar** [comment]
Hi @martinleeseo 
You can implement this with the menu anchor widget: https://elementor.com/help/menu-anchor-widget/
The UI is up to you :)

Thanks
