### ISSUE TITLE
Share buttons.- WhatsApp dose not isolate link from title and content page

### ISSUE THREAD

**Issue by umm-wdc** [elementor/elementor#17517]
**Issue**:
The sharing command does not isolate the link from the page title and this does not allow the correct display of the page contents and the relative image. 
While it should be noted that the title of the site is instead surrounded by * like this: *abcdefg*contenthttps://xyz.abc
is it possible to generate the separation space and where can I insert it?

===== Guidelines ====

- Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.
- Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).
- If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific.

-->

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
I merged this issue with #14698, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
