### ISSUE TITLE
Cannot Set W/H for linked SVG

### ISSUE THREAD

**Issue by vltgdgsn** [elementor/elementor#17520]
I'm using an svg in place of an image via the image element for my websites logo.  When I link the svg it breaks styling and does not allow to set width/height/ect.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
