### ISSUE TITLE
Autenticação Two-factor

### ISSUE THREAD

**Issue by lschramm0790** [elementor/elementor#17524]
Bom dia!

Não está sendo possível realizar a autenticação Two-factor. Está apresentando a mensagem "Two-factor code verification failed. Please try again.".

Já tentei utilizar o Microsoft authenticator e o Google authenticator

Já tentei usar Google Chrome (janela anônima e não anônima), Mozilla Firefox, Internet Explorer, Microsoft Edge.

![Autenticação](https://user-images.githubusercontent.com/90204061/150346753-ae7cc4e7-a17e-4471-bd57-03b34750fb22.jpg)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help. 
Please re-write it in English for us to understand. 

Thanks.
