### ISSUE TITLE
🔗 🚀 Feature Request: Elementor custom post type & metafiled & metabox. (Duplicate of #11126)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17521]
It would be great if elementor adds these 3 features. So we will not need third-party plugins.

Does elementor have a plan to develop these?

**Comment by MichaelDarko** [comment]
It's the most requested feature:

#4440
#11126

They are working on it but I'm worried they will only add loop item designer, but not custom post and custom fields interface. So it will be half-baked solution.

They simply need to build something like JetEngine from Crocoblock: https://crocoblock.com/plugins/jetengine/

Create post type -> Add fields -> Build loop item

If they listened to web creators, they would've built it many years ago.

**Comment by shilo-ey** [comment]
I merged this issue with #11126, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
