### ISSUE TITLE
Undefined text when there's no any icon selected in "Table of contents"

### ISSUE THREAD

**Issue by afrancel28** [elementor/elementor#17523]
- Undefined text when there's no any icon selected in "Table of contents"

![Untitled-1](https://user-images.githubusercontent.com/29262350/150306433-c6356d1e-dbfc-4a26-ac0f-7d6fbc5f086b.jpg)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by davronakil** [comment]
I have the same issue. 
Steps to replicate: 
WordPress 5.8.1
Elementor Version 3.4.6 
Add table of contents element
hide icons (select none)
Add H2s only to the selector
Add content with some h2s to populate the Elementor Table of Contents

Problem: 

prepends "undefined" to the items <li> in the <ul>

<img width="302" alt="image" src="https://user-images.githubusercontent.com/3535504/167223771-f95045c3-62a2-41ff-84e1-ed5f54bd3484.png">

**Comment by soulreverie** [comment]
I had this same issue but the TOC was saved as a Global Widget. When unlinked it, the icons worked properly.

**Comment by davronakil** [comment]
Issue is still present with the latest version of WP & Elementor (absolutely everything is up to date as of today). 

<img width="146" alt="image" src="https://user-images.githubusercontent.com/3535504/195242401-117752b5-0aef-4c57-9bcd-5f3331b0f280.png">

**Comment by kmk-pdx** [comment]
Also experiencing this issue as of Feb 2023. 
![image](https://user-images.githubusercontent.com/50334513/218874363-477aed6b-ae9a-472b-824e-46b145e5c324.png)

**Comment by davronakil** [comment]
For now I recommend picking any icon from the list, and then inspecting the code, and adding a CSS rule i.e. display:none on that element to hide the 'undefined'. But yes, the issue is still there on my end as well.

**Comment by GitteHubbard** [comment]
@DorShahar, this issue has been documented by @davronakil and others, and I can also confirm it is still outstanding. Could you please reopen it so it gets fixed?

Many thanks!
