### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by Gelo1978r** [elementor/elementor#17542]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Gelo1978r** [comment]
Notice: Undefined index: requires in /home3/artolore/public_html/wp-content/plugins/elementor-pro/license/updater.php on line 73

Notice: Undefined index: new_version in /home3/artolore/public_html/wp-content/plugins/elementor-pro/license/updater.php on line 83

Notice: Undefined index: requires in /home3/artolore/public_html/wp-content/plugins/elementor-pro/license/updater.php on line 73

Notice: Undefined index: new_version in /home3/artolore/public_html/wp-content/plugins/elementor-pro/license/updater.php on line 83

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.

**Comment by michellemcdines** [comment]
I'm getting exactly the same error on several WP installations - so I'd say this is definitely a bug!!

**Comment by bwat-dev** [comment]
I have the same error with elementro-pro 3.7.1
"Undefined index: require"
<img width="1082" alt="Screenshot-error" src="https://user-images.githubusercontent.com/20904573/173577971-6cef700e-15d0-4174-9503-e876377d0e6a.png">
s

**Comment by grindelf** [comment]
> I have the same error with elementro-pro 3.7.1 "Undefined index: require" <img alt="Screenshot-error" width="1082" src="https://user-images.githubusercontent.com/20904573/173577971-6cef700e-15d0-4174-9503-e876377d0e6a.png"> s

I have the same error.
Appear on plugins tab.

How to solve it?

**Comment by zahinwadud** [comment]
I'm running Version 3.7.7 and got the same problem each and every time I install another plugin, but when refreshed the message goes away. But that's the latest version.

**Comment by grindelf** [comment]
> I'm running Version 3.7.7 and got the same problem each and every time I install another plugin, but when refreshed the message goes away. But that's the latest version.

Mine too.
I updated the theme, be theme, and now the error dont appear anymore.
Dont know what was the problem. Now is ok

**Comment by SallyMoo** [comment]
I've just inherited a site using Elementor Pro 3.7.7 and it displays the same error, in the same circumstances. Refreshing the plugins page makes it disappear. 

As ideas anyone?

Thanks.

**Comment by jakubforman** [comment]
I'v just install/reinstal/downgrade Elementor 3.7.7 - 3.8.0 and get same error (only in Admin). In my case showing error only if `elementor pro` want to check if new version exist or not. Also if want to downgrade in admin, shows `cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received` Error. 


```txt
Warning: Undefined array key "requires" in /data/web/virtuals/308792/virtual/www/domains/khszlin.cz/wp-content/plugins/elementor-pro/license/updater.php on line 69

Warning: Undefined array key "new_version" in /data/web/virtuals/308792/virtual/www/domains/khszlin.cz/wp-content/plugins/elementor-pro/license/updater.php on line 84

Warning: Undefined array key "requires" in /data/web/virtuals/308792/virtual/www/domains/khszlin.cz/wp-content/plugins/elementor-pro/license/updater.php on line 69

Warning: Undefined array key "new_version" in /data/web/virtuals/308792/virtual/www/domains/khszlin.cz/wp-content/plugins/elementor-pro/license/updater.php on line 84

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/308792/virtual/www/domains/khszlin.cz/wp-content/plugins/elementor-pro/license/updater.php:69) in /data/web/virtuals/308792/virtual/www/domains/khszlin.cz/wp-admin/admin-header.php on line 9
```
