### ISSUE TITLE
Docs - How to organize controllers

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17547]
Hi
Please add a tutorial or a few code examples to teach how to organize the controllers. For a simple element, you need to add a few controllers. If you even have 10 elements, you are going to have 100 controllers and 1000 lines of code or more! We need to have a way to organize them.
Thanks

**Comment by rami-elementor** [comment]
Hi @babakfp 

If you are referring widget controls, please read https://developers.elementor.com/docs/widgets/widget-controls/

You can also see full addon examples at:
* https://developers.elementor.com/docs/widgets/simple-example/
* https://developers.elementor.com/docs/widgets/advanced-example/

There is no best practice for control organization. You are welcome to suggest one at the [Elementor Docs GitHub repo](https://github.com/elementor/elementor-developers-docs/).
