### ISSUE TITLE
⛔ 🚀 Feature Request: Push mode for menu cart widget & elementor pop up

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17541]
Hello

It would be great if you add the push mode to the menu cart and especially the pop-up. With this feature, they push the site content when the menu cart or pop up opens.
See its example in the following link (last button)
https://tympanus.net/Blueprints/SlidePushMenus/

This feature will be especially useful for elementor pop up.

Thank you

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
