### ISSUE TITLE
Button Border on Hover 

### ISSUE THREAD

**Issue by gboxxx** [elementor/elementor#17543]
[x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[x] The issue still exists against the latest stable version of Elementor.

**Description**

The border color on hover cannot be changed to be something different on hover when editing a button. Additionally, you cannot enable a border on hover without it also adding a border to normal state, and vice versa.

**Steps to reproduce**

Button Widget > Style > Hover > Add border > change color. It will also change for the normal state. 

[VIDEO DEMONSTRATION](
https://user-images.githubusercontent.com/96701009/150657279-6bb0d7bb-b0c9-4187-b443-0f9123b7019b.mp4)

**Isolating the problem**

    [x] This bug happens with only Elementor plugin active (and Elementor Pro).
    [x] This bug happens with a default WordPress theme active.
    [x] I can reproduce this bug consistently using the steps above.

**System Info** 
WordPress version: 5.8.3

Operating System:
Software: Flywheel/5.1.0 
MySQL version: (Google) v5.7.36 
PHP Version: 7.4.27
Elementor Version: 3.5.3
Elementor Pro Version: 3.5.2

**Comment by paauserrat** [comment]
Totally needed!

**Comment by rami-elementor** [comment]
Hi @gboxxx ,

You can easily solve this without changing Elementor.
On hover use white or transparent border-color.
