### ISSUE TITLE
Elementor Editor always opening the style kit settings first

### ISSUE THREAD

**Issue by ashutosh7403** [elementor/elementor#17557]
Elementor  Version 3.5.4
when i want to edit my page edit with elementor the page is not open properly its always open my style kit at the left side and when i close that after that i am able to edit my page
![image](https://user-images.githubusercontent.com/90984349/150754299-0f9f9663-1419-4626-aa11-a328f5ef429a.png)

**Comment by DorShahar** [comment]
Hi @
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
