### ISSUE TITLE
Is content_template() still a thing / working?

### ISSUE THREAD

**Issue by Jonas-360ty** [elementor/elementor#17558]
Hi There,
I am creating a Widget that renders GPU heavy 3D Content. Problem is: in the editor, the constant reloading of the script when editing the controls causes the WebGL context to overload, which eventually slows down the browser or even crashes it. My Solution for this is having it render on another site and insert an iframe instead.
About a year ago, I used the content_template() method to render stuff in the editor. Trying it now, it doesn't work. I googled a bunch and checked the documentation but couldn't find any Information if the content_template method still works or is deprecated. 
The Widget Creation Documentation still [refers ](https://developers.elementor.com/docs/widgets/advanced-example/#:~:text=protected%20function%20content_template()%20%7B) the Method.

It won't work for me, tho. I did everything the same way it is done in the documentation example.

To test it, I included it like this, but it still displays the "render method" way:

````
public function content_template() {
?>
<#
view.addInlineEditingAttributes( 'basepath', 'basic' );
#> 
<script type="text/javascript">console.log("{{{ settings.basepath }}}")</script>
<iframe src="{{{ settings.basepath }}}"></iframe>
<?php
}
````

**Comment by rami-elementor** [comment]
Hi @Jonas-360ty 

We didn't changed anything. The `content_template()` method is still working.

You can find more information at https://developers.elementor.com/docs/widgets/widget-rendering/

Two things to keep inmind, the method should be `protected` not `public` and you should not use the `addInlineEditingAttributes` for the URL parameter used in the `iframe`.

```
protected function render() {
	echo '<iframe src="' . esc_url( $settings['basepath '] ) . '"></iframe>';
}

protected function content_template() {
	?>
	<iframe src="{{{ settings.basepath }}}"></iframe>
	<?php
}
```
