### ISSUE TITLE
Elementor breaks lazy load plugins

### ISSUE THREAD

**Issue by jiang-yuan** [elementor/elementor#17555]
I have two video backgrounds at the bottom of my homepage and set Lazy Load Iframes to ‘on’.
I used Slider Revolution before, which litespeed can lazy loading it until get into the viewpoint.
Today I replace Slider Revolution with Elementor section’s background, but these two videos do not lazy-load anymore.

screenshot:https://ibb.co/BPCkzt8

The page I need help with: https://www.theryang.com/

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.

**Comment by jiang-yuan** [comment]
Doesn't it is a bug of Elementor?

**Comment by jiang-yuan** [comment]
I am reporting the lazy load bug

**Comment by jiang-yuan** [comment]
> Hi,
> 
> Please create GitHub issues only for bugs reports and feature requests. **GitHub issues are not for support.**
> 
> If you have questions or need general support, Please try:
> 
> * Elementor Community on Facebook
> * Elementor Knowledge base
> * Support forums on WordPress.org
> * Elementor Developers docs
> 
> If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).
> 
> Thanks.

I am reporting the lazy load bug
