### ISSUE TITLE
Elementor Editor always opening the style kit settings first

### ISSUE THREAD

**Issue by ashutosh7403** [elementor/elementor#17556]
1. As i am going to edit my page with [Edit with Elementor] it always open the style kit settings first

![image](https://user-images.githubusercontent.com/90984349/150745389-7f595956-7722-44d6-ba15-7980a6c07a83.png)

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
