### ISSUE TITLE
PDF Viewer (new widget)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17563]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Using this widget, we can display pdf files in the most professional way possible on the website. 

Demo of this widget : https://demo.happyaddons.com/elementor-pdf-view-widget-demo/?_ga=2.46795687.1649573058.1643018719-629583119.1643018716

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2814, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
