### ISSUE TITLE
frontend-lite.min.css  loaded on every page

### ISSUE THREAD

**Issue by LukaszJaro** [elementor/elementor#17568]
I have the latest elementor installed as of today with the various theme experiments on, I thought it was not supposed to load on every page that is not using elementor? I still see frontend-lite.min.css

If that behavior is correct then maybe alternative is to just dequeue on unnecessary pages.

**Comment by udidol** [comment]
It could happen if you are logged in, because of the admin bar or some other administrative purpose.
Try to open your page in incognito mode and check if it happens.

**Comment by LukaszJaro** [comment]
Found the issue, even though I wasn't using elementor on some pages and instead php page templates, I still had the default editor set as elementor, so I had to click on 'back to WordPress editor' and then update the page. Now frontend-lite.min.css does not load anymore.

![image](https://user-images.githubusercontent.com/10998875/151430156-4f4f2fc1-7d29-4c95-aece-efbcd4c42f0e.png)

Thank you for helping me look into this!
