### ISSUE TITLE
Content Switcher (New widget)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17562]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

This feature is excellent. With this widget, we can switch between page content.

See the demo of this widget in the following link : https://demo.happyaddons.com/elementor-content-switcher-demo/?_ga=2.50397225.1649573058.1643018719-629583119.1643018716

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #11813, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
