### ISSUE TITLE
🔗 🚀 Feature Request: Advanced table widget (new widget) (Duplicate of #1342)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17561]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

elementor drastically lacks the table widget. This is really needed. It is strange that elementor did not pay attention to it after 5 years of activity.
The jet elements plugin has this widget. I think it can be a good model for localizing this widget in elementor. 

See this widget in this link : https://crocoblock.com/widgets/table/

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1342, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
