### ISSUE TITLE
📢 finder is not working properly. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17569]
hello

I have reported this bug many times but ...

After updating elementor 3.5, the finder encountered a problem. The problem is that the finder only finds WordPress tabs, and in the theme builder only the page! Finds only the pages of these two sections : https://prnt.sc/26iqyy2     **Therefore, it does not find the header, footnote and other parts of the theme builder.**

**Steps to reproduce this bug :**

1- Publish a page in WordPress : https://prnt.sc/26ir0ch
2- Create a header or footer in the theme builder.
3- Create a page in the elementor theme builder : https://prnt.sc/26ir0z4
4- Return to the WordPress Dashboard and enable Finder.
5- Search for the names of the pages you created. What WordPress page, what elementor theme builder page.     **Finds it right !**
6- Now search for the name of the header or footer you created.      **Does not find. There is a problem.**

**tip :** Finder also does not find single, 404 page , archive pages. Please test everything in theme builder.

thank you

**Comment by aperojo** [comment]
Finder still not working properly. It doesn't find theme builder's templates.

**Comment by zeinnicholas** [comment]
+1

**Comment by manuel-will** [comment]
+1

**Comment by uigoris** [comment]
Still not working.. it's shame such a useful feature is not supported :(

**Comment by 79ho3ein** [comment]
This bug was solved in version 3.7
thank you @shilo-ey & @rami-elementor

**Comment by zeinnicholas** [comment]
> This bug was solved in version 3.7 thank you @shilo-ey & @rami-elementor

Yep! It's working again! 🙌

**Comment by yhlee-op** [comment]
Hi, Im on version 3.7.2 and finder is not working.

**Comment by 79ho3ein** [comment]
> Hi, Im on version 3.7.2 and finder is not working.

It works well for me.

**Comment by Anomrace** [comment]
Same here finder not on the 18th january 2023. I made my update today

**Comment by 79ho3ein** [comment]
> Same here finder not on the 18th january 2023. I made my update today

Everything works fine for me.

**Comment by 79ho3ein** [comment]
Hi @crohde2 

There is no problem for me. Maybe this is related to your site. Please disable all plugins except Elementor and Elementor Pro and install and activate hello elementor theme. Are you still facing this bug? If you're still having issues, please submit system information for the Elementor team to review.
