### ISSUE TITLE
Add “loading=lazy” attribute to background video iframes [ED-7687]

### ISSUE THREAD

**Issue by jiang-yuan** [elementor/elementor#17570]
I have two section video backgrounds at the bottom of my homepage and set Lazy Load Iframes to ‘on’.
I used Slider Revolution before, which litespeed can lazy loading it until entering the viewpoint.
Today I replace Slider Revolution with Elementor section’s background, but these two videos do not lazy-load anymore.
I also try to enable lazy loading by wp-rocket and perfmatters but none of them work.
Besides, Elementor load youtube script  3 times (a video background each time, costing 700kb * 3). It is no need to load 2 extra times, which wastes 1.5MB traffic.

screenshot:https://ibb.co/BPCkzt8

The page you can check: https://www.theryang.com/

**Comment by rami-elementor** [comment]
I confirm, background video iframes are missing the `loading="lazy"` attribute.

**Comment by Jonatan-r** [comment]
Any updates on this???

**Comment by jiang-yuan** [comment]
I do not where the “loading=lazy” attribute is.

**Comment by rami-elementor** [comment]
Elementor’s background videos use the [YouTube iFrame Embeds API](https://developers.google.com/youtube/iframe_api_reference) which _does not support lazy loading_.

**Comment by gangesh** [comment]
@rami-elementor what if background video is from Vimeo?

**Comment by rami-elementor** [comment]
The same, we use [Vimeo Embeds API](https://developer.vimeo.com/player/sdk/embed) which currently does not support lazy loading.

**Comment by rmelchner** [comment]
you can also add html5 video url - there it would be needed (but preload="metadata" or preload="none")

**Comment by rmelchner** [comment]
in case anyone needs a solution i created a function in my child theme:

```
/**
 * Elementor Background Video Optimization
 *
 * Improves page load performance by adding preload="metadata" attribute to Elementor background videos.
 * This tells the browser to only load video metadata initially, not the full video content.
 */
class Elementor_Video_Optimization
{
    /**
     * Constructor
     */
    public function __construct()
    {
        // Add filter to modify video HTML output - higher priority to run after Elementor
        add_filter('elementor/frontend/the_content', array($this, 'modify_content_videos'), 999);
    }

    /**
     * Modify content to add preload="metadata" attribute to all videos
     *
     * @param string $content The content HTML
     * @return string Modified content
     */
    public function modify_content_videos($content)
    {
        // Use regex to find video tags without preload attribute and add it
        $pattern = '/<video(?![^>]*preload=)([^>]*)>/i';
        $replacement = '<video $1 preload="metadata">';
        $content = preg_replace($pattern, $replacement, $content);
        return $content;
    }
}

// Initialize the video optimization functionality
new Elementor_Video_Optimization();

```
