### ISSUE TITLE
Hello, receiving error code "Deprecated:_register_controls is deprecated since  version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home4/physihub/public_html/wp-includes/functions.php on line 5211. Please can you help me fix this problem

### ISSUE THREAD

**Issue by brian361** [elementor/elementor#17580]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rami-elementor** [comment]
You are using a plugin that extends Elementor functionality the old way.

Deactivate the plugin one-by-one until you find the plugin. Contact the plugin author and ask him to update the code.

The plugin author should to replace the `_register_controls()` method with `register_controls()` removing the `_` prefix (this was changed in Elementor 3.1.0).

More info at https://developers.elementor.com/docs/widgets/widget-structure/

**Comment by Mulli** [comment]
In my case: Dynamic Conditions v. 1.5.2 fixed the problem. Thanks @rami-elementor !

**Comment by shubhamprajapati241** [comment]
Make the debugging changes in wp-config.php file : 

define('WP_DEBUG', 'true');
 /** Affichage des erreurs à l'écran */
 
define( 'WP_DEBUG_LOG', true );
 
define( 'WP_DEBUG_DISPLAY', false );

@ini_set( 'display_errors', 0 );

Hope it will solve your issues.
Thank you

**Comment by Mulli** [comment]
@shubhamprajapati241 Changing debug log mode - will NOT fix the problem!

**Comment by rami-elementor** [comment]
Hi,

In my comment above I used the wrong link, just fixed it now to https://developers.elementor.com/docs/deprecations/simple-example/

Also, read about the [Elementor Deprecation Proccess](https://developers.elementor.com/docs/deprecations/).

**Comment by MurshediSultan** [comment]
Hello ; 
I am facing the following problem, how do I fix it?


Deprecated: الوظيفة _register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379

Deprecated: الوظيفة _register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379

**Comment by Mulli** [comment]
@MurshediSultan see the following link [https://developers.elementor.com/docs/deprecations/simple-example/](url)

**Comment by Mulli** [comment]
@MurshediSultan see the following link [https://developers.elementor.com/docs/deprecations/simple-example/](url)
