### ISSUE TITLE
Changing the domain leads to a loss of functionality

### ISSUE THREAD

**Issue by asattelmaier** [elementor/elementor#17581]
**Description**

If I change my domain from https://test.com to https://www.test.com I get a strange behavior in my navigation that I built in Elementor. I lose the sticky feature and also the dynamic submenus are no longer displayed. What is strange is that everything behaves as expected as soon as I log in via wp-admin and use the site with admin bar. That's why my first guess was that it's due to caching like the cache is turned off in admin and turned on in normal use. But I can't find any information or settings about this.

**System**

- Elementor Version 3.5.4
- Wordpress Version 5.8.3
- PHP Version 7.4.25

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
