### ISSUE TITLE
I'd like some help implementing an api I have with a website built with elementor

### ISSUE THREAD

**Issue by Sajodi110** [elementor/elementor#17586]
I'd like some help implementing an api I have with a website built with elementor

I have a client that generates leads for electric companies and he has a form where customers put in their adresses. The problem is a lot of people are putting wrong adresses in. In Denmark we have a database of all adresses so it was pretty easy to make the api and upload it using filezilla. Now the problem is connecting it to the website with elementor pro.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
