### ISSUE TITLE
Accordion - setting for all closed at start

### ISSUE THREAD

**Issue by liranbp** [elementor/elementor#17592]
Hey this issue and suggest was on 2017 and many of us want and need it.
I'm just asking to have a setting switch to start accordion when all items are closed.

Currently, 5 years after we use ugly JS snippets to solve it, it looks bad and flickering on the screen.
Please add this feature.
link to original issue which closed by you: https://github.com/elementor/elementor/issues/2481

**Comment by alexplayer** [comment]
+1 for this feature request.

**Comment by cirkut** [comment]
+1 from me. It would be great to get a response from the devs on this old issue. While there is a 'workaround' to use the toggle element, it may be important in some situations to ensure that only one section is opened at a time. Shouldn't be tough or bad on UX to include a 'Closed by default?' toggle.

**Comment by 79ho3ein** [comment]
Hi guys
If I'm not mistaken, elementor will soon be developing the Accordion widget. Of course, its release date is not known, but it is definitely on the roadmap.
See this : #16557

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2756, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
