### ISSUE TITLE
Animated Headline - Styles not working

### ISSUE THREAD

**Issue by Donkies11** [elementor/elementor#17609]
I am using Chrome with Windows 10: Version 97.0.4692.99 (Official Build) (64-bit)

I was able to adjust the font size earlier today for the Animated Headline element. I am not able to make any adjustments to "style" this afternoon; size, weight, etc.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* **Prerequisites.**
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
