### ISSUE TITLE
LOREM IPSUM

### ISSUE THREAD

**Issue by Leonard227** [elementor/elementor#17611]
I recently published a website but I have a problem. There is Lorem Ipsum texts in each and every page. Could someone please help me to remove it.
loaloboche.co.ke

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
