### ISSUE TITLE
🐞 Bug report: Can't delete element on multisite since version 3.5

### ISSUE THREAD

**Issue by Knoclar** [elementor/elementor#17615]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using elementor and elementor pro on multisite, since version 3.5 (maybe earlier), removing an element with right click or DEL key generate an error in console
here : `Uncaught TypeError: n.container is undefined` in preview.js:10:21473

Remark : works perfect on version 3.4.4 and 3.4.5 (free) with elementor pro version 3.5.2 installed

### Steps to reproduce

1. Must be multisite
2. install elementor and elementor pro and activate in network
3. add a widget or something
4. try to remove it with right click or DEL key
5. see the error in consol
![firefox_eqHPH64HuX](https://user-images.githubusercontent.com/48055858/151556475-faf336a2-8f10-421d-b160-8ab3e58cd287.gif)
e

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.50
	PHP Version: 7.4.25
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://deliresdencre.org/scientilivre
	Home URL: https://deliresdencre.org/scientilivre
	WP Multisite: Yes
	Max Upload Size: 128 Mo
	Memory limit: 1G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: hello@codekitchen.fr
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

== Active Plugins ==
	Elementor
		Version: 3.5.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

== Network Plugins ==
	Advanced Custom Fields PRO
		Version: 5.11.4
		Author: Delicious Brains

	Broadcast
		Version: 48.05
		Author: edward_plainview

	Broadcast 3rd Party Pack
		Version: 48.01
		Author: edward_plainview

	BulkPress
		Version: 0.3.5
		Author: Jesper van Engelen

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Custom Post Type UI
		Version: 1.10.1
		Author: WebDevStudios

	Duplicator Pro
		Version: 4.0.5.3
		Author: Snap Creek

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.2.11
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Elementor
		Version: 3.5.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	NS Cloner - Site Copier
		Version: 4.1.9.3
		Author: Never Settle

	OoohBoi Steroids for Elementor
		Version: 1.9.0
		Author: OoohBoi

	Premium Addons for Elementor
		Version: 4.8.4
		Author: Leap13

	Regenerate Thumbnails Advanced
		Version: 2.4.0
		Author: ShortPixel

	Temporary Login Without Password
		Version: 1.7.1
		Author: StoreApps

	Total Upkeep
		Version: 1.14.13
		Author: BoldGrid

	Total Upkeep Premium
		Version: 1.5.9
		Author: BoldGrid

	UpdraftPlus - Backup/Restore
		Version: 2.22.1.25
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.5.7
		Author: Wordfence

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

	WP Activity Log
		Version: 4.3.4
		Author: WP White Security

	WP Grid Builder
		Version: 1.5.8
		Author: Loïc Blascos

	WP Grid Builder - Elementor
		Version: 1.0.4
		Author: Loïc Blascos

	Yoast SEO
		Version: 17.9
		Author: Team Yoast

== Expériences d’Elementor ==
	Sortie DOM optimisée: Inactif par défaut
	Amélioration du chargement des ressources: Inactif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Inactif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Inactif par défaut
	Hide native WordPress widgets from search results: Actif par défaut
	Default to New Theme Builder: Actif par défaut
	En-tête et pied de page du thème Hello: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Favorite Widgets: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Form Submissions: Actif par défaut
	Scroll Snap: Inactif par défaut

== Log ==
	
PHP: showing 8 of 8PHP: 2022-01-24 13:31:12 [notice X 1][/home/delirec/www/wp-content/plugins/elementor/core/app/modules/import-export/module.php::163] Undefined index: session [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-25 07:42:10 [notice X 17][/home/delirec/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-25 12:15:54 [notice X 3][/home/delirec/www/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-25 13:47:36 [notice X 882][/home/delirec/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index:  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-26 14:08:34 [notice X 10][/home/delirec/www/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-26 18:44:19 [notice X 1][/home/delirec/www/wp-content/plugins/elementor-pro/modules/forms/submissions/actions/save-to-database.php::120] Undefined index: field_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-27 20:24:17 [error X 1][/home/delirec/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::139] Uncaught Error: Call to a member function get_edit_url() on bool in /home/delirec/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:139
Stack trace:
#0 /home/delirec/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(159): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts_by_location(&#039;include/general&#039;, &#039;header&#039;, 162)
#1 /home/delirec/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(103): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;get_conditions_conflicts(162, &#039;include/general&#039;)
#2 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_check_conditions_conflicts(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/delirec/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /home/delirec/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 14:21:30 [notice X 2][/home/delirec/www/wp-content/plugins/elementor-pro/license/admin.php::250] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 232022-01-24 15:34:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.5.4',
)]
2022-01-24 15:34:41 [info] elementor::elementor_updater Started 
2022-01-24 15:34:41 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2022-01-24 15:34:41 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2022-01-24 15:34:41 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-01-24 15:34:41 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-01-24 15:34:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.5.4',
)]
2022-01-25 08:47:16 [info] elementor-pro::elementor_pro_updater Started 
2022-01-25 08:47:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-25 08:47:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-25 08:47:17 [info] elementor-pro::elementor_pro_updater Started 
2022-01-25 08:47:17 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-01-25 08:47:17 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-01-25 08:47:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.2',
)]
2022-01-25 08:47:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.2',
)]
2022-01-28 12:17:38 [info] dynamic-content-for-elementor::dce_updater Started 
2022-01-28 12:17:38 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Start  
2022-01-28 12:17:38 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_3_0_signature_change_default Finished 
2022-01-28 12:17:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.9',
  'to' => '2.2.11',
)]
2022-01-28 12:17:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.2.9',
  'to' => '2.2.11',
)]

JS: showing 2 of 2JS: 2022-01-25 06:46:03 [error X 42][https://deliresdencre.org/scientilivre/wp-content/plugins/wp-grid-builder-elementor/assets/js/preview.js?ver=1.0.4:10:21485] Cannot read properties of undefined (reading \&#039;model\&#039;) 
JS: 2022-01-25 07:25:50 [error X 34][https://deliresdencre.org/scientilivre/wp-content/plugins/wp-grid-builder-elementor/assets/js/preview.js?ver=1.0.4:10:21473] n.container is undefined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==
	
[system-info-deliresdencre.org-28-01-2022.txt](https://github.com/elementor/elementor/files/7959033/system-info-deliresdencre.org-28-01-2022.txt)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
