### ISSUE TITLE
Save error, missing style changes after reload elementor page.

### ISSUE THREAD

**Issue by AppsTotalSEOMarketing** [elementor/elementor#17610]
Hello friends, wishing you well.

I believe i found a bug building a woocommerce site with elementor, i made some color adjustment to the site in elementor, save the page, the changes reflected in the frontend BUT when reload the editing page, the changes in the design like gradient colors are "invisible" until make some adjustment in elementor the changes magically reappear.

This only happen in the new version of elementor 3.5.4, i have two other sites with Version 3.2.5 and they don't have that problem.

I already uninstall the wordpress installation three times and change root directory, re install wordpress with new credentials, install only elementor from plugin wordpress repository, active and make a page test and i get again the error. Is there any way to fix this bug?

I appreciate a lot your help to solve this issue.
Kind regards.
3rnest  (Elementor PRO user, advanced web designer)
![01-make-changes](https://user-images.githubusercontent.com/80184829/151713178-1f99aff6-1e21-4411-89e8-edc529c16be3.jpg)

![02-after-reload](https://user-images.githubusercontent.com/80184829/151713191-7c88df20-b737-4e75-923c-7f0d127fd5f5.jpg)

![03-change-boxed](https://user-images.githubusercontent.com/80184829/151713198-a42b8c69-d627-48bb-af7a-1d35104feab6.jpg)

![04-changes-re-appear](https://user-images.githubusercontent.com/80184829/151713205-94e631af-f732-42e0-80f1-9165bd7af2e4.jpg)

![05-only-elementor-plugin](https://user-images.githubusercontent.com/80184829/151713211-2df16df2-94d0-4d77-ba2f-6cf859f63ae5.jpg)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
