### ISSUE TITLE
Portfolio and Post Widgets Query Not Working

### ISSUE THREAD

**Issue by FRWDstudio** [elementor/elementor#17620]
Both the portfolio and post widgets have an empty query state. Seems to default to all post.
<img width="334" alt="Screenshot 2022-01-29 at 02 23 45" src="https://user-images.githubusercontent.com/72129924/151643651-2a00efd7-5641-4d1f-b382-117c27b194e4.png">

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.
