### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by nikosgrsr** [elementor/elementor#17627]
Hello, 
I have this issue to my site
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function '_disable_block_editor_for_navigation_post_type' not found or invalid function name in /home/centarha/online.tamarainikos.com/wp-includes/class-wp-hook.php on line 307
Any help?

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
