### ISSUE TITLE
Social Section 

### ISSUE THREAD

**Issue by RKiera** [elementor/elementor#17623]
How can I modify the social section on the posted I created. It seems it's theme related but unfortunately no tool in SEO or wordpress is helping resolving the issue. 

Thanks 
RT

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
