### ISSUE TITLE
Error 500 keeps occurring

### ISSUE THREAD

**Issue by brian361** [elementor/elementor#17639]
Hello

Cannot update site and server 5600 error keeps occurring, any help would be appreciated

**Comment by DorShahar** [comment]
Hi @brian361 
Please check with your site host. The kind of error (I guess you meant [the 506 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/506)) is on the Server-side and has something to do with an internal server configuration. 

If you are a pro user, you are welcome to content our support for further assistance. 

Thanks

**Comment by brian361** [comment]
Hi

I am a pro user, do you have a link to that support team

Many thanks

Brian
