### ISSUE TITLE
Character constraint feature for form fields

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17636]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

This feature is simple and at the same time very important. It is strange that it has not been noticed so far.
**Please add character limit feature.** This feature is essential for all fields, especially the number field (contact number).

### Describe the solution you'd like

Ability to set the number of characters for each field. For example, a maximum of 10 characters. The user can not type more than this value.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #13654, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
