### ISSUE TITLE
TBT error in all elementor website

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17631]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Almost all websites built with elementor (especially hello elementor template) receive TBT error in gt metrix. Unfortunately this is not good. Please think about this problem. elementor calls a lot of scripts and this increases TBT. Surely you know this better than anyone.
elementor is a great website builder. Therefore, this problem can keep many users away from elementor. All critics consider this to be the only elemental weakness. Other than that, they have nothing to say. That's right, elementor knows this and is working to improve it.
But if elementor creates a revolution in its optimization, it will be great. I can boldly say that its users will increase at least twice.
Great if elementor offers a big update just to optimize its code. We do not want any new features in this update. Just optimize code and performance.
I'm sure elementor can easily reach its optimal state. This is really possible.
**I would love to know your opinion, dear developers.**

### Describe the solution you'd like

Dramatically improve the ranking of elementor websites. D >>> A

**Comment by rami-elementor** [comment]
Thank you for the suggestion, every Elementor version has performance improvements. You don't really need to do anything, just upgrade to new versions and see how your GTmetrics and Page Speed score improves.

For more information, read this post:

https://developers.elementor.com/how-elementor-improved-asset-loading-and-made-your-website-run-faster/
