### ISSUE TITLE
⛔ 🚀 Feature Request: Slide mode does not work well in elementor pop up and menu cart widget.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17635]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

As the title suggests, unfortunately the slide mode in elementor does not fit well. Simply put, when closing, it does not convey a pleasant feeling to the user.
Of course, it works well when opened. Pop-up action, also cart menu. But when it closes, very bad ...
For example, when we close the pop-up, the slide does not go to the end. Rather, near the end, it disappears quickly. Also, the overlay color is not removed at the right time.
It's really hard for me to describe this mode, but if you look closely at the pop-up and the menu cart closing time, you will see that the closing mode does not make good sense.
Also, when the pop-up and menu cart are closed, the overlay color is removed in an instant. It is best to remove it infrequently.
Please review this again. I explained in full : #15496

### Describe the solution you'd like

They should feel good when the pop-up and menu cart are closed. (In slide mode)
The best example is the Woodmart template menu. https://woodmart.xtemos.com/handmade/
In the link above, open the shopping cart menu. Then close. It closes beautifully. Also, the overlay color rarely fades. this is fabulous.

Thank you in advance for your attention.

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

As you can see in the video below, the animation is very smooth and pleasant. It behaves exactly like the example you gave. It doesn't look like this is an issue to be solved. it's likely you might be experiencing some animation hiccups with your device. When there are multiple CSS animations applied to the same object or children of the object, some machines might not be able to run those animations smoothly, and some drops in the frame-rate might occur. This is rare but possible.

https://user-images.githubusercontent.com/113993460/216222687-7f3f04d4-d18d-45e6-bbba-60fab09b7294.mp4 

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
