### ISSUE TITLE
🐞 Bug report: UX annoyance in templates page

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17647]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

https://user-images.githubusercontent.com/44144724/151917590-4ece9689-e3cd-4592-b546-a4d5cb317cdb.mp4

### Steps to reproduce

_

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

_

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by babakfp** [comment]
@DorShahar
😐 You have everything you need
