### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by shoaib-sme** [elementor/elementor#17649]
Hi,

When I am logged in to the Wp Admin Panel, there is no error. But when i am not logged in, i get this error is console
"Uncaught ReferenceError: jQuery is not defined"

and jqeury elements does not work.

This happens when I add elementor Nav menu (pro). 

Can you please help me to resolve this?

Regards
Shoaib

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
