### ISSUE TITLE
Elementor Premium Modal Box - Show Modal on mouse hover

### ISSUE THREAD

**Issue by modkore** [elementor/elementor#17646]
### ❓ Support Question

- [x] Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!
- [ ] If you have questions or need general support, please use:  https://wordpress.org/support/plugin/elementor
- [X] For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/
- [ ] To read more about Elementor, check out our documentation: https://docs.elementor.com
- [ ] Developers docs are located at: https://developers.elementor.com/

**Comment by modkore** [comment]
I need help implementing a function on this Elementor Premium Modal Box

Created an modal where the subject is an image
Default Function: Click Image > Show Modal
Needed Function: Hover Image > Show Modal

I hope someone can help.

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
