### ISSUE TITLE
> @fxaviers

### ISSUE THREAD

**Issue by COM1BOUTIK** [elementor/elementor#17651]
> @fxaviers
> 
> if you want to catch a specific form submit event then add the listener on the form instead of the document, ex:
> 
> ```js
> //The event is submit_success so you can catch it for example:
> jQuery( document ).ready(function( $ ){
> 	$( '#FORM_ID_HERE' ).on('submit_success', function(){
> 		// form has been submitted
> 		window.open('YOUR URL', '_blank');
> 	});
> });
> ```

Thank you! 
I have a question: if i'm using dynamic fields on the URL, how do i manage to insert them inside the 'YOUR URL' space? 

For example, my URL looks like this:
https://mysite.com/Booking?lang=es-ES&fd=[field%20id="fd"]&td=[field%20id="td"]&promo=[field%20id="promo"]

Some help would be much appreciated ^_^

_Originally posted by @antisomatismico in https://github.com/elementor/elementor/issues/6974#issuecomment-855472178_

**Comment by COM1BOUTIK** [comment]
I currently use "redirection" to an url with parameters using fields values entered, but I'm not able to redirect to a new tab, nor I'm not able to open this redirection into a popup containing an iframe for example.
Is there any solution or workaround to achieve this ?

**Comment by udidol** [comment]
@COM1BOUTIK 
What are you trying to achieve exactly?
