### ISSUE TITLE
Elementor Pro form widget PHP 8 undefined array key warnings

### ISSUE THREAD

**Issue by bratvanov** [elementor/elementor#17650]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am noticing PHP 8.0 warnings in my error_log:
The page contains a simple Elementor form widget with a couple of default fields.

`Undefined array key "referrer" in /wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php on line 179'`

### Steps to reproduce

Create a form widget containing a couple of "Text" fields, a "Textarea" field, a "Tel" field, a "Honeypot" field and a "reCAPTCHA V3" field.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

WordPress 5.9
Elementor 3.5.4
Elementor Pro 3.5.2
Hello Elementor 2.5.0

Server:
PHP 8.0.15
Apache/2.4.41
MariaDB 10.5.11

**Comment by lekiend** [comment]
Same issue with System Info
Wordpress 6.0.1
Elementor - 3.7.2
Elementor Pro - 3.7.3

Server:
PHP Version: 8.0.22
Operating System:  Linux   
Software: nginx/1.20.1  
MySQL version: mariadb.org binary distribution v10.3.36

**Comment by lekiend** [comment]
@rami-elementor Could you please have a look at this issue ?
Is it a bug ?

Regards

**Comment by KingYes** [comment]
Hello, it should be fixed on Elementor Pro 3.15+.
