### ISSUE TITLE
🐞 Bug report: Portfolio Widget not working

### ISSUE THREAD

**Issue by FamiliarRich** [elementor/elementor#17653]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Portfolio Widget dosn't function at all when dragged in from the widgets panel. Does not display content

Elementor Version 3.6.0-dev36
Elementor Pro Version 3.7.0-dev12

### Steps to reproduce

Drag the portfolio widget into a flex container

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://forms2mobile.familiardev.com
	Home URL: https://forms2mobile.familiardev.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: accounts@2mnetworks.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.0-dev36
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev12
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		button : 2
		container : 8
		divider : 1
		heading : 2
		icon : 1
		image : 2
		social-icons : 1
		text-editor : 3
	header : 3
		button : 8
		call-to-action : 13
		container : 22
		divider : 4
		heading : 18
		html : 5
		icon-list : 6
		image : 7
		posts : 3
		text-editor : 14
	loop : 0
		accordion : 1
		container : 1
	page : 3
		accordion : 1
		button : 7
		container : 32
		heading : 24
		html : 4
		icon : 1
		icon-list : 1
		image : 6
		menu-anchor : 4
		text-editor : 18
	section : 4
		button : 4
		heading : 30
		html : 2
		icon-list : 1
		spacer : 3
		text-editor : 14
	wp-page : 25
		accordion : 8
		blockquote : 6
		button : 96
		container : 445
		divider : 4
		eael-advanced-data-table : 1
		form : 2
		heading : 242
		html : 16
		icon : 40
		icon-box : 54
		icon-list : 12
		image : 93
		image-box : 2
		lottie : 14
		menu-anchor : 4
		posts : 3
		text-editor : 176
	single-post : 1
		container : 3
		heading : 5
		post-info : 1
		text-editor : 4
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		button : 1
		container : 2
		heading : 1
		image : 1
		text-editor : 1

== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Container: Active
	: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 292021-12-08 11:58:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-12-08 11:58:10 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2021-12-08 11:58:10 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2021-12-08 11:58:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.6.0-dev18',
)]
2021-12-08 11:58:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.6.0-dev18',
)]
2022-01-07 09:29:56 [info] elementor::elementor_updater Started 
2022-01-07 09:29:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-07 09:29:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-07 09:29:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev14',
  'to' => '3.6.0-dev27',
)]
2022-01-07 09:29:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev14',
  'to' => '3.6.0-dev27',
)]
2022-02-01 01:21:39 [info] elementor::elementor_updater Started 
2022-02-01 01:21:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-01 01:21:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-01 01:21:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev27',
  'to' => '3.6.0-dev36',
)]
2022-02-01 01:21:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev27',
  'to' => '3.6.0-dev36',
)]
2022-02-01 11:16:51 [info] elementor-pro::elementor_pro_updater Started 
2022-02-01 11:16:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-01 11:16:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-01 11:16:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev18',
  'to' => '3.7.0-dev12',
)]
2022-02-01 11:16:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev18',
  'to' => '3.7.0-dev12',
)]

PHP: showing 11 of 11PHP: 2021-12-12 02:18:01 [warning X 2][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-pro/license/api.php::377] in_array() expects parameter 2 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-13 15:11:27 [error X 7][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api-&gt;get_active_plugins()
#2 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins-&gt;get_plugins()
#3 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/modules/system-info/module.php(292): Elementor\Modules\System_Info\Reporters\Plugins-&gt;is_enabled()
#4 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/modules/sy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-07 09:45:32 [error X 14][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-super-cat-master/widgets/param-button.php::286] Uncaught Error: Class &#039;Elementor\Scheme_Typography&#039; not found in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-super-cat-master/widgets/param-button.php:286
Stack trace:
#0 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2231): ElementorSuperCat\Widgets\Param_Button-&gt;_register_controls()
#1 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(480): Elementor\Controls_Stack-&gt;init_controls()
#2 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(175): Elementor\Controls_Stack-&gt;get_stack()
#3 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(341): Elementor\Widget_Base-&gt;get_stack(false)
#4 [internal function]: Elementor\Widgets_Manager-&gt;ajax_get_widget_types_controls_config(Array, Object(Elemento [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-10 19:09:57 [error X 16][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method &#039;WP_REST_Controller::get_item_permissions_check&#039; not implemented. Must be overridden in subclass. in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller-&gt;get_permission_callback(Object(WP_REST_Request))
#1 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route-&gt;get_permission_callback(Object(WP_REST_Request))
#2 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route-&gt;Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/rest-api/class- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-12 16:09:06 [notice X 26][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-12 17:07:12 [error X 1][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/class-wp-hook.php on line 305 and defined in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1042
Stack trace:
#0 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/class-wp-hook.php(305): Elementor\TemplateLibrary\Source_Local-&gt;on_save_post(6819, NULL)
#1 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#3 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/post.php(4468): do_action(&#039;save_post&#039;, 6819, NULL, true)
#4 /home/customer/www/forms2mobile.familiardev.com/public [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-19 12:25:10 [error X 1][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-25 15:26:02 [notice X 45][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: apply_indexer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 01:21:40 [notice X 125][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 11:10:40 [error X 7][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-super-cat-master/widgets/param-button.php::286] Uncaught Error: Class &#039;Elementor\Scheme_Typography&#039; not found in /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor-super-cat-master/widgets/param-button.php:286
Stack trace:
#0 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2253): ElementorSuperCat\Widgets\Param_Button-&gt;_register_controls()
#1 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack-&gt;init_controls()
#2 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(175): Elementor\Controls_Stack-&gt;get_stack()
#3 /home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(336): Elementor\Widget_Base-&gt;get_stack(false)
#4 [internal function]: Elementor\Widgets_Manager-&gt;ajax_get_widget_types_controls_config(Array, Object(Elemento [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 12:07:42 [notice X 1][/home/customer/www/forms2mobile.familiardev.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::115] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-02-01 11:24:20 [error X 3][https://forms2mobile.familiardev.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev36:2:401633] Cannot read properties of undefined (reading \&#039;parent\&#039;) 
JS: 2022-02-01 11:53:55 [error X 12][https://forms2mobile.familiardev.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.7.0-dev12:2:98289] Cannot read properties of undefined (reading \&#039;attributes\&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by matipojo** [comment]
Hi @FamiliarRich Thanks for reporting! The bug was fixed and will be released in the next Pro release.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.7.2

Feel free to update

Thanks!
