### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Page Transitions Lottie Animation

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#17668]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The new "Page Transitions" feature only allows to use pre defined animations.

### Describe the solution you'd like

Allow us to upload custom Lottie Animations

**Comment by 79ho3ein** [comment]
Hello @paauserrat

Do not worry, there is a better way. Go to this website:
https://lottiefiles.com/category/loading/animations?page=8

Here is the whole lottie animation. Choose whichever you like and change its color to the desired color.
After doing this, download the file and go to the lottie animation conversion section.
Convert the animation to gif and upload it to the preloader > image  section.

Easily display your favorite animation. I think this was the best way to add a preloader that elementor did.
Lottie alone was not interesting.

Good luck

**Comment by 79ho3ein** [comment]
But I think if elementor also supports the lottie animation json file in the preloader, it would be great.

**Comment by DorShahar** [comment]
Hi @paauserrat 
Thanks for your feedback.

We didn't implement the Lottie option due to serious harm in the site performance (the same reason is for allowing the presentation of a custom template).

In the near future, we will not support this kind of functionality. 
In case we will see more requests we will consider adding this functionality to this feature. 

I'm leaving this request open for future tracking.

Thank you for your understanding

**Comment by pgirzalsky** [comment]
Please add this functionality. I'm currently using a different solution using a 3rd party plugin and the performance is completely fine using a section with a Lottie widget: https://www.nw-dev.one/

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔃  This request is being merged with #20444.

Which is on the same subject. 

For this reason, I'm closing the comments, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
