### ISSUE TITLE
🐞 Bug report: Custom Code feature not working

### ISSUE THREAD

**Issue by bjc999** [elementor/elementor#17675]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Upon updating to Elementor Pro version 3.6.0, the Custom Code feature has stopped working.

### Steps to reproduce

Update to Elementor Pro version 3.6.0

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== WordPress Environment ==
	Version: 5.9
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== Elementor ==
		Version: 3.5.4
		Author: Elementor.com

== Elementor Pro ==
		Version: 3.6.0
		Author: Elementor.com

**Comment by wpeasy** [comment]
I have seen the same issue. 
Verdi Heinz asked me to DM him a link to the issue. He will see if it can be pushed along.

**Comment by avivu** [comment]
Hello @bjc999,

Thank you for reporting.
Can I ask you if you are also using WooCommerce?

**Comment by bjc999** [comment]
Hi @avivu 

Yes I am. I deactivated WooCommerce, but there is no change.

The issue begun after I updated to v3.6.0.

No other plugins were added or updated at the time.

Thank you.

**Comment by avivu** [comment]
Thank you @bjc999 

We are aware of this issue.
We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by bjc999** [comment]
Excellent!

Keep up the good work! :D 

Thank you.

**Comment by 79ho3ein** [comment]
+1

**Comment by MikeLikesThat** [comment]
Notifications turned on. This would break most of my sites. Hopefully the fix isn't too difficult to solve.

**Comment by trofimartya** [comment]
For those who looking for solution:
Rollback to prev version and update all scripts in bulk.
This should help.
In my case all website was broken so this is the easiest solution. Lets wait for fix,

**Comment by relima** [comment]
I am also having this issue on my sites.

**Comment by Webtica** [comment]
Same issue here. Following.

**Comment by bjc999** [comment]
Any updates?

Cheers.

**Comment by bjc999** [comment]
Hi @avivu,

Any updates?

Cheers.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.1

Feel free to update

Thanks!

**Comment by inovacio-github** [comment]
Came to this thread after an auto-update msg of Elementor Pro (while auto-updates are disabled), is this update being forcefully pushed (happened +/- 20  min ago 14.29 Dutch time)?

**Comment by black-eye** [comment]
> Came to this thread after an auto-update msg of Elementor Pro (while auto-updates are disabled), is this update being forcefully pushed (happened +/- 20 min ago 14.29 Dutch time)?

Oh my, I thought it was the Dev Edition problem only, but it seem to be the problem of 3.6 PRO as well - https://github.com/elementor/elementor/issues/17751

I cannot confirm this issue myself, I have not updated to 3.6 PRO on my live sites yet. You know, I've had bad experiences with Elementor untested and rushed updates. ;) Now they are in unwanted auto-update mode! :)) Excellent move, Elementor! :))

**Comment by Webtica** [comment]
And again this is broken in Elementor Pro 3.6.2.
Hope this won't auto update on all my sites. 
You can enter the code but the conditions popup doesn't show up and the code is not set. 

@black-eye Do you get this aswel?

**Comment by leevincent** [comment]
> You can enter the code but the conditions popup doesn't show up and the code is not set.

Same issue here.
