### ISSUE TITLE
No puedo editar en Elementor

### ISSUE THREAD

**Issue by Skiol** [elementor/elementor#17684]
Se queda en la pantalla de carga y no pasa de  ahi

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
