### ISSUE TITLE
Getting out of Dev. Elementor

### ISSUE THREAD

**Issue by tharring** [elementor/elementor#17688]
I made a mistake by upgrading to Developer Elementor. I was using regular Elementor on a website, and didn't know I shouldn't upgrade to Developer until it was too late and I saw the message that says "don't use this on a working website". I'd already hit the button, so it was too late for me to get that message. Now I can't get into my Site Settings, into my Body Text and various global font areas. Is there a way for me to reverse my error and go back to regular Elementor?
Thanks.

**Comment by shilo-ey** [comment]
Hey,

Simply deactivate and remove the "Elementor Beta - Developer Edition" plugin,
Then go to Elementor > Tools > Version control and rollback your Elementor/Elementor Pro versions to the latest versions available.

Thanks

**Comment by tharring** [comment]
Not that simple. My Dev. Elementor version doesn't show any Plugins in the
sidebar. I can't deactivate anything. Is there another way?
Thanks,
