### ISSUE TITLE
Custom Date List Order

### ISSUE THREAD

**Issue by ericrounds** [elementor/elementor#17689]
It’ll be really wonderful if we could list posts based on custom date and not the date of the published post. This can be used for events, concerts, upcoming publications, etc.

**Comment by hitsgee** [comment]
They have this via a custom query Id I believe.

**Comment by rami-elementor** [comment]
Hi @ericrounds ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

Meanwhile you can use [custom query filter](https://developers.elementor.com/docs/hooks/custom-query-filter/) as @hitsgee mentioned.

Regards,
