### ISSUE TITLE
🐞 Bug report: issue in Settings > Integrations

### ISSUE THREAD

**Issue by bugnumber9** [elementor/elementor#17695]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

See the screenshot below.
![bug](https://user-images.githubusercontent.com/1769548/152312328-fbacc92c-b237-4d6b-8b9c-b68ab4e56f47.png)

### Steps to reproduce

Update Elementor Pro to 3.6

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

n/a

**Comment by DorShahar** [comment]
Hi @bugnumber9 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by bugnumber9** [comment]
Sorry, false alarm. I overlooked one active plugin, that was causing the issue.
