### ISSUE TITLE
Se ha borrado mis plantillas en el maquetador de temas y ya no se ven en mi pagina

### ISSUE THREAD

**Issue by spadnor** [elementor/elementor#17706]
Se me ha borrado en el maquetador de temas de elementor la cabecera y el footer lo unico que hice fue borrar otras plantillas que no me sirven estoy realizando una pagina web con word press , elementor y generate press. Ahora no se como recuperarlos

**Comment by DorShahar** [comment]
Hi @spadnor 
Please report in English. Without it, we can't help
