### ISSUE TITLE
SOLICITUD AYUDA PLUGIN REALHOMES

### ISSUE THREAD

**Issue by Luchithub** [elementor/elementor#17707]
Llevo algún tiempo tratando de estructurar una página que me sirva para administrar la finca raíz (compra y arrendamiento de bienes inmuebles), con el  lamentable resultado de que no he podido lograrlo y creo que fundamentalmente se debe a un plugin que descargué  pero que parece tiene algún problema, ya que en la sección de COMENTARIOS me sale este aviso “RealHomes License Purchase Verification Failed” y en la sección de PLUGINS me aparece este otro comentario “RealHomes License Purchase Verification Failed” a pesar de que la versión que supuestamente descargué es libre de pago.
Soy un principiante y aunque pagué desde noviembre de 2012 el Hosting y Dominio, no he podido sacarle provecho a esta página por mi desconocimiento en su estructuración.

Debo manifestarles además que he intentado ingresar a los links que ustedes me han enviado en este correo sin que haya logrado cambio alguno

Estoy acudiendo a ustedes porque estoy seguro que de allí recibiré la mejor orientación para resolver mi problema.

 Mil gracias

[2022 02 03 captura pantalla.docx](https://github.com/elementor/elementor/files/7999686/2022.02.03.captura.pantalla.docx)
[captura pantalla sitio inseguro.docx](https://github.com/elementor/elementor/files/7999693/captura.pantalla.sitio.inseguro.docx)

 
Cordial saludo,

**Comment by DorShahar** [comment]
Hi @Luchithub 
Please report the issue in English. Without it, we can't help.

**Comment by Luchithub** [comment]
I have been trying for some time to structure a page that will help me manage the real estate (purchase and lease of Real estate), with the unfortunate result that I have not been able to achieve it and I think it is fundamentally due to a plugin that I downloaded but that seems to have some problem, since in the COMMENTS section I get this notice“RealHomes License Purchase Verification Failed” and in the PLUGINS section I get this other comment “RealHomes License Purchase Verification Failed” despite the fact that the version that I supposedly downloaded is free of charge.
I am a beginner and although I paid for the Hosting and Domain since November 2012, I have not been able to take advantage of this page due to my lack of knowledge in its structuring.
I must also tell you that I have tried to access the links that you have sent me in this email without making any changes.

I am coming to you because I am sure that from there I will receive the best guidance to solve my problem.
Thank you
[2022 02 03 captura pantalla.docx](https://github.com/elementor/elementor/files/8011462/2022.02.03.captura.pantalla.docx)
[captura pantalla sitio inseguro.docx](https://github.com/elementor/elementor/files/8011463/captura.pantalla.sitio.inseguro.docx)
