### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by galitms** [elementor/elementor#17704]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is a problem with the gallery, the pictures can not be arranged or moved in a different order

### Steps to reproduce

Open a page and add photos. Enter the gallery and try to arrange the pictures in a different order by dragging. - This is possible

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: http://lenazaidel.com
	Home URL: http://lenazaidel.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: galit_ms@netvision.net.il
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child Theme
	Version: 1.0.0
	Author: WebsiteBundles
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.4.7
		Author: mndpsingh287

	Elementor
		Version: 3.5.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Jetpack
		Version: 10.5.1
		Author: Automattic

	WPForms Lite
		Version: 1.7.2
		Author: WPForms

	Yoast SEO
		Version: 18.0
		Author: Team Yoast

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

== Elements Usage ==
	
	header : 1
		divider : 1
		image : 1
		nav-menu : 1
	widget : 0
		heading : 1
		nav-menu : 1
	wp-page : 11
		divider : 1
		gallery : 9
		heading : 9
		image : 8
		image-carousel : 1
		nav-menu : 10
		text-editor : 7

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive by default

== Log ==
	
Log: showing 20 of 312021-09-20 10:16:58 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-09-20 10:16:58 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-09-20 10:16:58 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-09-20 10:16:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.4.1',
)]
2022-01-23 16:14:43 [info] elementor-pro::elementor_pro_updater Started 
2022-01-23 16:14:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-23 16:14:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-23 16:14:43 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-01-23 16:14:43 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-01-23 16:14:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.2',
)]
2022-01-23 16:14:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.2',
)]
2022-01-23 16:15:22 [info] elementor::elementor_updater Started 
2022-01-23 16:15:22 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-01-23 16:15:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.4.4',
  'to' => '3.5.4',
)]
2022-01-23 16:15:22 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-01-23 16:15:22 [info] אלמנטור/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2022-01-23 16:15:22 [info] אלמנטור/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2022-01-23 16:15:22 [info] אלמנטור/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-01-23 16:15:22 [info] אלמנטור/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-01-23 16:15:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.4.4',
  'to' => '3.5.4',
)]

PHP: showing 2 of 2PHP: 2021-09-28 09:11:46 [error X 8][/home2/lenazaidel/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home2/lenazaidel/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home2/lenazaidel/public_html/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor\Modules\System_Info\Module->create_reporter(Array)
#5 /home2/lenazaidel/public_html/wp-content/plugins/elementor/includes/tracker.php(228): Ele [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 09:14:19 [error X 1][/home2/lenazaidel/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home2/lenazaidel/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home2/lenazaidel/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home2/lenazaidel/public_html/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home2/le [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-01-23 18:19:06 [error X 12][http://lenazaidel.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-02 17:30:54 [error X 1][http://lenazaidel.com/wp-content/plugins/elementor-pro/assets/js/preloaded-elements-handlers.min.js?ver=3.5.2:2:46911] Cannot read properties of undefined (reading \'setSettings\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
