### ISSUE TITLE
Content is different in editor and final page

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#17718]
I'm using Hello Theme 2.5.0, Elementor 3.6.0-dev37, Elementor Beta (Developer Edition) 1.1.1 and Elementor Pro 3.7.0-dev14.

Video for reference: https://vimeo.com/674107911/e6a77a7cbf

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by paauserrat** [comment]
> Thanks for reporting,
> Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
> This report is missing key information: 
> * Prerequisites.
> * Steps to replicate.
> * Isolating the problem.
> * System info.
> * One issue per thread
> 
> Without it, we simply can't help.
> 
> Thanks.

I filled the report that automatically opened from using the developer edition support button on my wordpress website. The issue template redirected me to this, without any default info to follow
