### ISSUE TITLE
product table woo commerce

### ISSUE THREAD

**Issue by parsiian** [elementor/elementor#17716]
Hi
I define the features for my product Woo commerce tables in WordPress site. When I use from these tables in one pages of my site, the first table displays the names of features above table. But the others don't display. plz help me, What can I do???

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
