### ISSUE TITLE
🚀 Feature Request: Checkout Widget - Ship to different address button

### ISSUE THREAD

**Issue by mike-smrst** [elementor/elementor#17724]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The ship to different address button is automatically checked and open.

### Describe the solution you'd like

It would be best to have the ability to have this auto unchecked when customers get to the checkout page.

**Comment by avivu** [comment]
Hello @mike-smrst 

The ship to a different address is open automatically only on edit mode (on the editor) for styling purposes.
The ship to a different address is unchecked and close by default on live preview.

Also, it depends on your WooCommerce settings on the shipping settings screen:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/76733085/152746225-c2cfd249-ec38-44dd-b4c9-8cef2779b90c.png">
