### ISSUE TITLE
🚀 Feature Request: Allow to choose another language instead of take the native

### ISSUE THREAD

**Issue by raylinanthony** [elementor/elementor#17732]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Elementor no have a personalized language.

### Describe the solution you'd like

I would like a differente language for elementor instead of use the wordpress language. I am a native spanish speaker, but I prefer elementor in english, is easier to me work on english. 

### Describe alternatives you've considered

Allow a field to choose a language

### Additional context

You can see how awful is work with this in spanish... if I could select the another language (english) to work, will be perfect! 

See the image:  https://imgur.com/a/OG1RhEy

**Comment by black-eye** [comment]
+1000
This request was here before, but why not to try it again. Hopefully one day somebody in Elementor will hear us.

My native language is Czech, and its translation is more than horrible. The main problem is that it attempts to translate everything, including the technical terms like shortcode, which sometimes lead to absolutely incomprehensible terms.

**Comment by raylinanthony** [comment]
@black-eye Agree with you bro

**Comment by shilo-ey** [comment]
I merged this issue with #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

We are working on introducing this feature. please follow the original thread for further updates.

Thanks for your feedback!
