### ISSUE TITLE
🚀 Feature Request: It's really needed to add the ability to selectively delete an olds unnecessary versions of templates

### ISSUE THREAD

**Issue by design77b** [elementor/elementor#17739]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I built a footer with an Elementor Theme Builder.
**I got 64 versions of this footer !!!** (because the client is problematic and requires changes all the time).
This slows down the website traffic very much.
**Please copy the link below and follow it to see the visual argument:**
[https://design77b.co.il/visual-argument/](url)

### Describe the solution you'd like

Unfortunately, **at this time** in the list of footer versions, **possible only delete all versions at once** (then I will be left without a footer at all), or define not to store them in cached memory at all (it's too late).

### Describe alternatives you've considered

**Needed** an addition of the **ability to selectively delete** an **olds** unnecessary **versions** of templates.

### Additional context
**Or**, at least, **add a function: "Delete all versions except the latest**".

**Comment by rami-elementor** [comment]
Hi @design77b 

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being.  This is not an Elementor issue, this is a WordPress issue. Elementor uses the WordPress "Revisions" feature. You can find plugin to manage those revisions. But Elementor won't be developing Revision features any time soon.

Please feel free to contact us again with other feature suggestions.

Regards,
