### ISSUE TITLE
🚀 Feature Request: Compatibility with pretty links plugin

### ISSUE THREAD

**Issue by groovelikeapig** [elementor/elementor#17738]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I need to auto paste All my affiliate links otherwise your theme and plugin are useless.
Please make sure that Elementor will work with pretty links

### Describe the solution you'd like

When I write a specific keyword, pretty link auto fill a URL link in that keyword.

**Comment by shilo-ey** [comment]
I merged this issue with #17738, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
