### ISSUE TITLE
Error on load Elementor editor

### ISSUE THREAD

**Issue by Alcateiaec** [elementor/elementor#17740]
Hi, today during the job,  the Elementor got an error while it was loading the page (edit with Elementor), and now it doesn't load anymore. I can not access anymore my site project!

![error elementor](https://user-images.githubusercontent.com/99224649/152894648-e1ac4690-facb-46e4-9dd6-09aaeb8f75a3.jpg)
.

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
