### ISSUE TITLE
REPEATER `'label' => false`

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17758]
Hi
![Screenshot 2022-02-08 130512](https://user-images.githubusercontent.com/44144724/153075600-1f171ddb-f1e0-4ad1-ac04-a4b9d5b25155.png)

**Comment by babakfp** [comment]
![Screenshot 2022-02-08 132954](https://user-images.githubusercontent.com/44144724/153078857-a2a56b9b-7484-4dbd-812e-992c6bb80fdd.png)
 Can we remove this empty space too?
thanks

**Comment by webdevs-pro** [comment]
Hey, what about `show_label' => false`?

**Comment by babakfp** [comment]
> Hey, what about `'show_label' => false`?

Thanks it works.

**Comment by babakfp** [comment]
Can we just deprecate the  `show_label` and show the label based on is it's value truthy or falsy? Also, can we remove the whole HTML instead of hiding it with CSS.
