### ISSUE TITLE
Why does Cart Totals part appears two times on my Cart Page?

### ISSUE THREAD

**Issue by StartingProgramming** [elementor/elementor#17755]
### ❓ Support Question

- [ ] Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!
- [ ] If you have questions or need general support, please use:  https://wordpress.org/support/plugin/elementor
- [ ] For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/
- [ ] To read more about Elementor, check out our documentation: https://docs.elementor.com
- [ ] Developers docs are located at: https://developers.elementor.com/

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
