### ISSUE TITLE
Elementor Pro Dev Edition Keeps Updating Automatically

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#17751]
Since several last versions of Elementor Pro Dev, the plugin keeps updating automatically even though this feature is disabled:

![obrazek](https://user-images.githubusercontent.com/5634870/153000305-686a4807-6c78-4ab1-8601-e84d8daed303.png)

Please fix it, this is unacceptable (concerning the long record of  the issues Elementor updates keep causing).

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.2

Feel free to update

Thanks!
