### ISSUE TITLE
Bug Report: nothing in the header is clickable with sticky top active

### ISSUE THREAD

**Issue by hilkon** [elementor/elementor#17750]
If you have sticky top active and scrolling down then no link in the header is clickable. 

Elementor - 3.6.0-dev37
Elementor Beta (Developer Edition) - 1.1.1 | By Elementor.com |  
Elementor Pro - 3.7.0-dev16

no other plugins active.

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
