### ISSUE TITLE
👌Make the UI controls name non required

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17760]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

Let's say we have this control:
```PHP
$this->add_control(
  'important_note',
  [
    'label' => esc_html__( 'Important Note', 'plugin-name' ),
    'type' => \Elementor\Controls_Manager::RAW_HTML,
    'raw' => esc_html__( 'A very important message to show in the panel.', 'plugin-name' ),
    'content_classes' => 'your-class',
  ]
);
```

I don't need that unique name, so it's annoying to pick a name for it.

### Describe the solution you'd like

```PHP
$this->add_control(
  [
    'label' => esc_html__( 'Important Note', 'plugin-name' ),
    'type' => \Elementor\Controls_Manager::RAW_HTML,
    'raw' => esc_html__( 'A very important message to show in the panel.', 'plugin-name' ),
    'content_classes' => 'your-class',
  ]
);
```

**Comment by rami-elementor** [comment]
@babakfp 

We can't change that, it's a fundamental requirement.
