### ISSUE TITLE
Elementor Editor doesn't load... Period.

### ISSUE THREAD

**Issue by KimmikoLLC** [elementor/elementor#17772]
I downloaded the Moover Template from Envato Elements, for some reason it still doesn't allow me to edit after uploading the initial Homepage Template.  I place it in safemode, and the same thing happens good old Elementor Loading Screen
![Screenshot 2022-02-09 140442](https://user-images.githubusercontent.com/99357948/153272074-dec5f042-b049-49c2-802f-d2af896ed13d.png)
.

**Comment by abbasdv** [comment]
Try disabling plugins and see if it works. 
Go through them all one by one until you find which one is causing it.

**Comment by abbasdv** [comment]
It could also be memory related, check this one

https://wpdeveloper.com/elementor-stuck-loading-screen/

**Comment by paauserrat** [comment]
> I downloaded the Moover Template from Envato Elements, for some reason it still doesn't allow me to edit after uploading the initial Homepage Template.  I place it in safemode, and the same thing happens good old Elementor Loading Screen
> ![Screenshot 2022-02-09 140442](https://user-images.githubusercontent.com/99357948/153272074-dec5f042-b049-49c2-802f-d2af896ed13d.png)
> .

Try to go under elementor settings and enable the loading method for when it doesn't load well

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
