### ISSUE TITLE
Friendly Captcha integration for Elementor forms

### ISSUE THREAD

**Issue by ashentertain** [elementor/elementor#17786]
European developers urgently need more GDPR-friendly alternatives to ReCaptcha. Please consider esp. "Friendly Captcha" integration and we would be happy to make more use of Elementor's forms feature.

It's a widget with great potential but unfortunately in the EU we cannot use it as it is.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/18029 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
