### ISSUE TITLE
🐞 BUG in elementor pro 3.6.1

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17788]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

1- In the new version, opening and closing the accordion is not the same as before and creates a bad situation. After opening and closing, the screen shakes.

2- The new version has a problem with the wp-rocket plugin. If in the wp-rocket plugin, we enable the two options of combin css and combin js, the console error will appear in the browser. This error did not exist before 3.6.
Error image : https://prnt.sc/26sv30s

**This error will be visible to guest users. (See browser in incognito mode)**

### Steps to reproduce

1- Install the wp-rocket and elementor pro plugins.
2- In the rocket plugin settings, enable the two combin css and combin js options.
3- Console error is visible.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

wordpress 5.8.3
elementor : 3.5.5
elementor pro : 3.6.1
hello elementor 2.4.2

**Comment by 79ho3ein** [comment]
+1

**Comment by 79ho3ein** [comment]
Of course, I have no problem with wp-rocket. The only thing is that after the update to pro 3.6, the number of JavaScript requests increased from 1 to 5.

**Comment by astbarc** [comment]
Hi @79ho3ein ,

See these other issues. Seems like this new version is adding some scripts for multilanguage in the frontend that are not necessary.

https://github.com/elementor/elementor/issues/17714
https://github.com/elementor/elementor/issues/13720

**Comment by 79ho3ein** [comment]
Thank you @astbarc, Hopefully it will be resolved in the new version soon.
