### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by agsym** [elementor/elementor#17795]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Using dynamic gallery from meta field data I need a slider with thumbnail and main image.

### Describe the solution you'd like

 I assume it could be done somehow by syncing two identical carousels/sliders so that one can be thumbnails and one the large image. If I then click on one carousel/slider the active image shows in the other carousel/slider. 

### Describe alternatives you've considered

I have been unable to find any solution.

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
