### ISSUE TITLE
🐞 Bug report: Container Layout "Width" error

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#17799]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

The new container isn't working as expected. I want to create a container with a Layout that takes the 80% of the horizontal screen but keeping the Container in the center. I can't find any option to make the container Left, Middle or Right align itself horizontally with the full canvas.

**Flex "align-self" horizontally for container "Layout" is missing.**
Where's the horizontal align self?:
![image](https://user-images.githubusercontent.com/73240206/153513603-a0eece43-2295-4add-95ef-ba8fa529c12e.png)

Editor:
![image](https://user-images.githubusercontent.com/73240206/153512991-32254c50-3791-41b3-9f51-f495afce67b2.png)

Preview:
![image](https://user-images.githubusercontent.com/73240206/153513032-f2c030aa-cd84-497b-801f-bc0871e3bdc1.png)

As we can se, the editor shows the container in the middle but it isn't. We should be able to set horizontal position of the container to middle, left or right.

### Steps to reproduce

1. Add a new Container.
2. Give it a 80% width (any value different from 100% reproduces it too)
3. Put content or background color to the container
4. See that it's auto aligned to center horizontally in the editor
5. Save changes
6. See how the live page shows the container left self aligned

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.0.0
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: http://experiment.local
	Home URL: http://experiment.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Madrid
	Admin Email: pauserratgutierrez@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.0-dev37
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev17
		Author: Elementor.com

<br />
<b>Warning</b>:  Undefined array key "title" in <b>C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\core\experiments\experiments-reporter.php</b> on line <b>89</b><br />

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	Container: Active
	: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
PHP: showing 6 of 6PHP: 2022-01-29 00:49:33 [warning X 1][C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\core\app\modules\import-export\module.php::136] file_get_contents(C:\Users\pause\Documents\WordPress Local\experiment\app\public/wp-content/uploads\elementor\tmp\61f4810d65e22\manifest.json): Failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 00:51:47 [warning X 1][C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 00:52:15 [warning X 4][C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-30 22:35:04 [warning X 1][C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-30 23:10:35 [warning X 2][C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\includes\template-library\sources\local.php::1393] Undefined array key "type" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-06 12:56:20 [notice X 1][C:\Users\pause\Documents\WordPress Local\experiment\app\public\wp-content\plugins\elementor\core\utils\import-export\parsers\wxr-parser-simple-xml.php::52] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-01-28 23:53:22 [error X 7][https://experiment.local/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.4:2:18381] Cannot read properties of undefined (reading \'top\') 
JS: 2022-01-30 10:45:35 [error X 5][https://experiment.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:558642] elementorFrontend is not defined 
JS: 2022-01-30 10:50:29 [error X 2][https://experiment.local/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils&ver=5.9:2:31703] elementorAdmin is not defined 
JS: 2022-01-30 10:51:38 [error X 1][https://experiment.local/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.9:2:31703] Cannot read properties of undefined (reading \'subscribe\') 
JS: 2022-01-30 21:25:12 [error X 2][http://experiment.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev35:2:401633] Cannot read properties of undefined (reading \'parent\') 

Log: showing 20 of 222022-01-29 01:39:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-29 01:39:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0-beta3',
)]
2022-01-29 01:39:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0-beta3',
)]
2022-01-30 11:50:21 [info] elementor::elementor_updater Started 
2022-01-30 11:50:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-30 11:50:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-30 11:50:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.6.0-dev35',
)]
2022-02-06 11:51:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev35',
  'to' => '3.6.0-dev37',
)]
2022-02-06 11:51:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-beta3',
  'to' => '3.7.0-dev14',
)]
2022-02-06 11:51:57 [info] elementor::elementor_updater Started 
2022-02-06 11:51:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-06 11:51:58 [info] elementor-pro::elementor_pro_updater Started 
2022-02-06 11:51:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-06 11:51:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-06 11:51:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev35',
  'to' => '3.6.0-dev37',
)]
2022-02-06 11:51:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-beta3',
  'to' => '3.7.0-dev14',
)]
2022-02-10 23:03:00 [info] elementor-pro::elementor_pro_updater Started 
2022-02-10 23:03:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-10 23:03:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-10 23:03:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev14',
  'to' => '3.7.0-dev17',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by pauserratgutierrez** [comment]
> Hi
> 
> Are you still experiencing this issue using "Boxed" option?
> 
> Thanks

Hi, yes. I can't find a Flex "align-self" horizontally option for container "Layout", like the vertically option. It's missing

**Comment by shilo-ey** [comment]
Hey @pauserratgutierrez 

Thanks, 

Please try the folllowing:
1. Create a container with two inner containers (you can use the preset one). make sure that the width is set to "boxed"
2. Place content in each one of them
3. Go to the parent container and set the Justify Content to center: 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/45009641/170439887-30ebd958-ff50-4f37-a758-86bef666bb05.png">


This should work as expected

Thanks
