### ISSUE TITLE
🐞 Bug report: Content is different in editor and final page

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#17796]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

The content using the new flexbox container doesn't respect the size. The final page isn't the same as when editing.

Video for reference: https://vimeo.com/674107911/e6a77a7cbf

### Steps to reproduce

Simply add a container with an image and other content. It won't be displayed respecting spaces and measures

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

I'm using Hello Theme 2.5.0, Elementor 3.6.0-dev37, Elementor Beta (Developer Edition) 1.1.1 and Elementor Pro 3.7.0-dev14 in local by Flywheel

**Comment by paauserrat** [comment]
https://github.com/elementor/elementor/issues/17718

**Comment by paauserrat** [comment]
Oh, I updated elementor pro 3.7.0 to dev 17 and it seems to work well now

**Comment by Michaelgimii** [comment]
hi @paauserrat , What new features have been added to version 3.7 pro?

**Comment by shilo-ey** [comment]
Thanks, this issue is resolved.
