### ISSUE TITLE
🐞 Bug report: Elementor "Report an issue" button in wordpress

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#17797]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Some days ago I reported an issue I was having with the developer edition. The problem is that I did it using the wordpress button that elementor has in the editor bar. This button redirects to an issue with a blank template. Any blank template is automaticly closed by you so all issues comming from that button get closed without any looking.

The button I'm talking about:
![image](https://user-images.githubusercontent.com/73240206/153505104-4419f959-f920-470e-a4bb-8e6c6d2a5c83.png)

It links to:
https://github.com/elementor/elementor/issues/new?labels=Developer+Edition&template=Bug_report_dev_edition.md

I guess it should link to:
https://github.com/elementor/elementor/issues/new?assignees=&labels=bug%2Cdeveloper-edition&template=bug_dev_edition.yaml&title=%F0%9F%90%9E+Bug+report%3A+

### Steps to reproduce

Click the button, post any issue and check for any of the admins to close it hehe

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by shilo-ey** [comment]
Thanks @paauserrat 
This has been fixed!
