### ISSUE TITLE
Ability to customize the scroll bar in elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17800]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Great if you can add custom scroll bar to elementor. Using this feature, we can customize the browser scroll bar..
Of course, Firefox browser is not fully compatible with this feature at this time. We can have this feature in elementor, as long as firefox is compatible.

### Describe the solution you'd like

Ability to customize the scroll bar

**Comment by paauserrat** [comment]
#17254
