### ISSUE TITLE
Embeded Video not working when "Lightbox" is ticked on the Elementor Video Widget 

### ISSUE THREAD

**Issue by ChrismerAmbay** [elementor/elementor#17806]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

There's an issue to Elementor Video widget. If you embed the wistia video and tick the Lightbox, it only has blank pop-up and there is no video on the pop-up. But if the Lighbox is unticked, the video plays normally. Any solutions for that?
## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
I merged this issue with #17749, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
