### ISSUE TITLE
🐞 Bug report: Custom Add to cart widget alignment is not working properly

### ISSUE THREAD

**Issue by CJKrets** [elementor/elementor#17810]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Custom Add To Cart button no longer applies alignment styles.

### Steps to reproduce

Add Custom Add To Cart button and try to align it using Elementor Builder. 

Elementor support was given access to a fresh install where they had to add custom code to get the button to align. I was instructed that the code was not recommended and it would up to me to fix it if/when it breaks. This is obviously not a long term solution.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.33
	PHP Version: 7.4.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 1025M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: REDACTED
	Home URL: REDACTED
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: REDACTED
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.1
		Author: Elementor.com

	LiteSpeed Cache
		Version: 4.4.7
		Author: LiteSpeed Technologies

	Temporary Login Without Password
		Version: 1.7.1
		Author: StoreApps

	WooCommerce
		Version: 6.2.0
		Author: Automattic

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 7 of 72022-02-10 23:55:25 [info] elementor-pro::elementor_pro_updater Started 
2022-02-10 23:55:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-10 23:55:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-10 23:55:25 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-02-10 23:55:25 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-02-10 23:55:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.6.1',
)]
2022-02-10 23:55:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.6.1',
)]

PHP: showing 2 of 2PHP: 2022-02-11 00:04:26 [notice X 8][/home/REDACTED/public_html/REDACTED.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-11 00:09:18 [notice X 1][/home/REDACTED/public_html/REDACTED.com/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::186] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-02-11 00:14:34 [error X 3][https://REDACTED.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.5:2:5069] Cannot read properties of undefined (reading \'attributes\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.5

Feel free to update

Thanks!
