### ISSUE TITLE
Slides Widget Suggestions

### ISSUE THREAD

**Issue by mnburch32951** [elementor/elementor#17815]
I was a loyal Divi user for two years until I discovered how superior Elementor Pro is. I switched and will never go back. I do have a couple of suggestions for the Slides widget, however.

I would like to have the option to specify the number of slides to display at one time. I'd also like to have the option of including an image other than as a background image.

Thank you.

**Comment by rami-elementor** [comment]
Hi @mnburch32951 

Happy to hear that you love Elementor. You can use other widgets with similar functionality. Elementor has sever carousel widgets where you can specify the number of slides where you can include images other than as a background image. Also, check out [Elementor Academy](https://elementor.com/academy/).

In any case, next time you open a feature request, please use the "Feature Request" template.

Thank you!

**Comment by mnburch32951** [comment]
Thanks, Rami. Sorry if I used the wrong template for my suggestions. Have a
great day!

Michael
