### ISSUE TITLE
🚀 Ability to poll users in the form of emojis (like elementor community)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17827]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you could add polls to elementpr. This feature is present in the elementor community and is really great.
https://prnt.sc/26v4olb

After the user clicks on the emoji, the form is sent immediately and then a text is displayed to the user.

### Describe the solution you'd like

I do not think a new widget is needed to add this feature. It can be integrated with the form widget.

**Comment by rami-elementor** [comment]
@79ho3ein 

Sound like a useful idea, but currently it's not in our roadmap. It can be developed as an Elementor Addon - https://developers.elementor.com/.

In any case, I have forwarder this request to the relevant people to see how we can prioritize this feature.

**Comment by 79ho3ein** [comment]
duplicate of #14991
