### ISSUE TITLE
🐞 elementor maintenances mode interferes with rank math plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17831]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If we create a page for maintenances mode and consider the background color for it, after installing the rank math plugin, the background color will change. **The background color changes to the color we considered in elementor site setting > background.**

### Steps to reproduce

1- In the site settings, select the general background color for the website. A specific color, such as blue. https://prnt.sc/26vky43
2- Create a page in the theme builder and select the background color from the page settings. **For example, white.** https://prnt.sc/26vkvfe & https://prnt.sc/26vkxix
3- Enable maintenances mode and view the website as a guest user. Make sure the maintenances mode background color works as expected. **According to step 2, the background color should be white.**
4- Now install and activate the Rank Math plugin. Configure it. (It is enough to proceed to the site map stage) https://prnt.sc/26vl1jg
5- Now visit the website again as a guest user.  maintenances mode is displayed, but its background color is blue. While according to step 2, the background color should be white. The background color has changed to the color we set in the elementor site settings > Background. If you change the background color in the Site setting, the maintenances mode background color will also change.
6- Now disable the Rank Math plugin. The problem is solved.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: http://localhost:85/jetengine
	Home URL: http://localhost:85/jetengine
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Admin Email: hosein.79@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.1
		Author: Elementor.com

	Rank Math SEO
		Version: 1.0.82.1
		Author: Rank Math

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Inactive
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 342022-01-27 13:46:15 [info] elementor::elementor_updater Started 
2022-01-27 13:46:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-27 13:46:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-27 13:46:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.4',
)]
2022-01-27 13:46:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.4',
)]
2022-02-03 01:37:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-03 01:37:01 [info] elementor-pro::elementor_pro_updater Started 
2022-02-03 01:37:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-03 01:37:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-03 01:37:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-12 03:33:35 [info] elementor::elementor_updater Started 
2022-02-12 03:33:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-12 03:33:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-12 03:33:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-14 12:20:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-02-14 12:20:24 [info] elementor-pro::elementor_pro_updater Started 
2022-02-14 12:20:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-14 12:20:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-14 12:20:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-02-14 12:20:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]

PHP: showing 9 of 9PHP: 2021-12-29 22:51:52 [error X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::create_item_permissions_check' not implemented. Must be overridden in subclass. in C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php:227
Stack trace:
#0 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 C:\xampp\htdocs\jetengine\wp-includes\rest-a [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 22:51:55 [error X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::delete_item_permissions_check' not implemented. Must be overridden in subclass. in C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\controller.php:227
Stack trace:
#0 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\data\v2\base\base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(1107): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 C:\xampp\htdocs\jetengine\wp-includes\rest-api\class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 C:\xampp\htdocs\jetengine\wp-includes\rest-a [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 22:30:15 [error X 4][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\dynamic-tags\manager.php::10] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 18:56:37 [error X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\includes\template-library\sources\local.php::1042] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in C:\xampp\htdocs\jetengine\wp-includes\class-wp-hook.php on line 309 and defined in C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\includes\template-library\sources\local.php:1042
Stack trace:
#0 C:\xampp\htdocs\jetengine\wp-includes\class-wp-hook.php(309): Elementor\TemplateLibrary\Source_Local->on_save_post(2026, NULL)
#1 C:\xampp\htdocs\jetengine\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 C:\xampp\htdocs\jetengine\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
#3 C:\xampp\htdocs\jetengine\wp-includes\post.php(4686): do_action('save_post', 2026, NULL, true)
#4 C:\xampp\htdocs\jetengine\wp-includes\post.php(4788): wp_insert_post(Array, false, true)
#5 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\includes\db.php(235): wp_update_post(Array)
#6 C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\base [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-02 01:35:13 [notice X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\app\modules\import-export\module.php::178] Undefined index: session [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-03 01:37:01 [warning X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor\core\files\manager.php::111] unlink(C:\xampp\htdocs\jetengine/wp-content/uploads/elementor/css/post-1581.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-05 15:37:35 [notice X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor-pro\license\updater.php::88] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-12 03:27:02 [notice X 2][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor-pro\includes\source.php::186] Undefined variable: info_data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-14 12:20:29 [notice X 1][C:\xampp\htdocs\jetengine\wp-content\plugins\elementor-pro\license\updater.php::69] Undefined index: requires [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by alisadrona** [comment]
I have this problem
