### ISSUE TITLE
🚀 Online Digital Currency Price Widget.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17856]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Adding a new widget to display digital currency prices online would be great.

### Describe the solution you'd like

-

**Comment by paauserrat** [comment]
I really like this suggestion. In addition, it will be amazing to also display cryptocurrency prices as now it's beeing more and more used.
