### ISSUE TITLE
🚀 open in new tab for "edit header & footer"

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17854]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hello

This is a great possibility that we can switch between header and footer : https://prnt.sc/26wdggo
But a simple case can complete this feature. This happens on the current page if we are on a tab and want to move to the header or footer edit. So we can not open it in the new tab. (Even if we right-click on it, there is no option to open in the new tab).
Please add the possibility of open in new tab to this section. **This feature can be added in two ways :**

1- Open in new tab by default.
2- After right-clicking on it(https://prnt.sc/26wdggo), the "Open in new tab" option will be displayed.

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request. 

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,

**Comment by 79ho3ein** [comment]
Thank you @rami-elementor
