### ISSUE TITLE
🐞 Bug report: Ultimate Addons for Elementor giving errors in the system info

### ISSUE THREAD

**Issue by aiwan** [elementor/elementor#17859]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Elementor System Info says there is an error with this plugin: https://ultimateelementor.com/.

### Steps to reproduce

Just activate Elementor and UAE plugin.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.32
	PHP Version: 7.3.33
	PHP Max Input Vars: 20000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: http://chulucan-cp503.webprestashop.com/woocommerce
	Home URL: http://chulucan-cp503.webprestashop.com/woocommerce
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1024M
	Permalink Structure: /%category%/
	Language: es
	Timezone: 2
	Admin Email: andres.iwan@chulucanas.es
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.7.7
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.53
		Author: ServMask

	Astra Pro
		Version: 3.6.5
		Author: Brainstorm Force

	Contact Form 7
		Version: 5.5.4
		Author: Takayuki Miyoshi

	Decorator - WooCommerce Email Customizer
		Version: 1.1.3
		Author: WebToffee

	DynamicConditions
		Version: 1.5.1
		Author: RTO GmbH

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.8
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.7.0-dev22
		Author: Elementor.com

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.15.0
		Author: FiboSearch Team

	Flexible Shipping
		Version: 4.11.2
		Author: WP Desk

	Hide Categories and Products for Woocommerce
		Version: 1.2.2
		Author: N.O.U.S. Open Useful and Simple

	Loco Translate
		Version: 2.5.8
		Author: Tim Whitlock

	Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue
		Version: 3.1.32
		Author: Sendinblue

	Permalink Manager Pro
		Version: 2.2.16
		Author: Maciej Bis

	Premium Starter Templates
		Version: 3.1.2
		Author: Brainstorm Force

	Rank Math SEO
		Version: 1.0.82.1
		Author: Rank Math

	Redsys WooCommerce
		Version: 3.1.0
		Author: Redsys

	Sendinblue - WooCommerce Email Marketing
		Version: 2.0.33
		Author: Sendinblue

	Shipping Filter Plugin - AI
		Version: 1.0
		Author: Andres Iwan

	Site Kit by Google
		Version: 1.49.1
		Author: Google

	Ultimate Addons for Elementor
		Version: 1.36.2
		Author: Brainstorm Force

	WooCommerce
		Version: 6.1.1
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.13
		Author: CartFlows Inc

	Woocommerce Custom Product Addons
		Version: 4.1.4
		Author: Acowebs

	WooCommerce Google Analytics Integration
		Version: 1.5.8
		Author: WooCommerce

== Uso de los elementos ==
	
	page : 2
		heading : 1
	section : 2
		heading : 9
		icon-box : 8
		site-logo : 1
		spacer : 6
		text-editor : 1
	wp-post : 0
		animated-headline : 1
		button : 3
		call-to-action : 6
		copyright : 1
		divider : 1
		google_maps : 1
		heading : 12
		icon-box : 16
		icon-list : 3
		image : 4
		image-box : 3
		nav-menu : 3
		search-form : 1
		shortcode : 2
		site-logo : 1
		social-icons : 1
		spacer : 4
		testimonial : 6
		text-editor : 1
		theme-site-logo : 4
		uael-dual-color-heading : 1
		uael-fancy-heading : 1
		uael-woo-products : 1
		woocommerce-menu-cart : 3
	wp-page : 9
		google_maps : 1
		heading : 2
		html : 1
		image : 2
		shortcode : 1
		text-editor : 4

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Inactivo por defecto
	Carga de CSS mejorada: Inactivo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Inactivo por defecto
	Importar o exportar un kit de plantillas: Activo por defecto
	Puntos de ruptura personalizados adicionales: Inactivo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Page Transitions: Activo por defecto
	Envíos de formulario: Activo por defecto
	Ajuste de scroll: Activo por defecto

== Registro ==
	
Log: showing 20 of 302022-01-26 13:44:06 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-01-26 13:44:08 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon callback needs to run more 1 times 
2022-01-26 13:44:08 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-01-26 13:44:08 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-01-26 13:44:08 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-01-26 13:44:09 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-01-26 13:44:09 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start (2 of 2, 100%) 
2022-01-26 13:44:10 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-01-26 13:44:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.5.2',
)]
2022-01-26 13:44:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.5.2',
)]
2022-02-01 14:33:33 [info] elementor::elementor_updater Started 
2022-02-01 14:33:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-01 14:33:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-01 14:33:33 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2022-02-01 14:33:33 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2022-02-01 14:33:33 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2022-02-01 14:33:33 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2022-02-01 14:33:33 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-02-01 14:33:33 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-02-01 14:33:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.6.0-dev36',
)]

JS: showing 6 of 6JS: 2022-01-26 12:18:53 [error X 28][http://chulucan-cp503.webprestashop.com/woocommerce/wp-content/plugins/ultimate-elementor/assets/min-js/uael-woocommerce.min.js?ver=1.27.1:1:343] o.slick is not a function 
JS: 2022-01-26 14:09:09 [error X 2][http://chulucan-cp503.webprestashop.com/woocommerce/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:349560] Cannot read properties of null (reading \&#039;id\&#039;) 
JS: 2022-01-29 21:00:05 [error X 1][http://chulucan-cp503.webprestashop.com/woocommerce/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.4:2:5069] Cannot read properties of undefined (reading \&#039;attributes\&#039;) 
JS: 2022-01-29 21:13:59 [error X 2][http://chulucan-cp503.webprestashop.com/woocommerce/wp-admin/load-scripts.php?c=1&loadchunk_0=regenerator-runtime,wp-polyfill,wp-hooks,jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.8.3:12:31703] elementorAdmin is not defined 
JS: 2022-02-01 08:10:35 [error X 1][http://chulucan-cp503.webprestashop.com/woocommerce/wp-admin/post.php?post=155&action=elementor#:3:77] Cannot read properties of undefined (reading \&#039;id\&#039;) 
JS: 2022-02-01 08:17:19 [error X 1][http://chulucan-cp503.webprestashop.com/woocommerce/wp-admin/post.php?post=155&action=elementor#:1:1] Identifier \&#039;$dcWidgetIdInput\&#039; has already been declared 

PHP: showing 6 of 6PHP: 2022-01-26 14:56:04 [notice X 11][/home/chulucan/public_html/woocommerce/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 23:39:35 [notice X 331][/home/chulucan/public_html/woocommerce/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] ¡El argumento $control_id está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 10:44:03 [notice X 1][/home/chulucan/public_html/woocommerce/wp-content/plugins/elementor-pro/modules/query-control/module.php::740] Trying to get property &#039;name&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-01 22:16:34 [warning X 1][/home/chulucan/public_html/woocommerce/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(brush-pink.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-02 14:12:25 [notice X 2][/home/chulucan/public_html/woocommerce/wp-content/plugins/elementor-pro/license/updater.php::85] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-16 11:59:00 [notice X 7][/home/chulucan/public_html/woocommerce/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatible
	Elementor Pro: Compatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible
	Ultimate Addons for Elementor: Incompatible

**Comment by rami-elementor** [comment]
@aiwan 

You should report this to "Ultimate Addons".
