### ISSUE TITLE
🐞 Custom code also does not work in version 3.6.2.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17865]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Custom code bug re-created after update to 3.6.2. Unfortunately, version 3.6 has many bugs. We report a lot of bugs, but we do not know if the developers have read our report or not !

### Steps to reproduce

Install version 3.6.2

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by renanterebz** [comment]
Yes, I have the same issue. Uncaught ReferenceError: elementorProAdmin is not defined

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/18082080/154386401-5e5de631-72b1-4726-9f6b-de141e308552.png">

**Comment by hedberg** [comment]
Got the same issue, on two different installs.

**Comment by wecodifyco** [comment]
Same issue. The conditions selector link doesn't show up.

**Comment by nicmare** [comment]
confirming the problem here too !!!

**Comment by marowi85** [comment]
Same here. Cannot change conditions for custom code anymore.

**Comment by Michaelgimii** [comment]
hi @shilo-ey , @avivu , @rami-elementor . Are you aware of these bugs? Version 3.6.2 has two major bugs. #17821

**Comment by shilo-ey** [comment]
Hey @Michaelgimii, we are aware of this bug and it's already been fixed.

A version will be released in the next couple of days

Thanks

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.3

Feel free to update

Thanks!
