### ISSUE TITLE
🐞 Elementor coding type

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17877]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm a big fan of elementor. But what elementor critics always say is why elementor generates extra code?

To test, I just created a section in elementor and put a button inside it. See generated codes : https://prnt.sc/VhsIRWChOBZ3
On the other hand, I wrote a situation like this manually. See this code now : https://prnt.sc/BeYWN-CdKHJw

What do you think about these two images? Doesn't elementor generate a lot of extra code?
Does elementor have a plan to improve their code?

I forgot to say, the elementor code in the first image was created with a container in the dev version.

### Steps to reproduce

.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

.

**Comment by rami-elementor** [comment]
Hi @Michaelgimii 

We are working on performance and DOM size. You can activate the [Optimized DOM Output](https://elementor.com/help/what-is-the-optimized-dom/) experiment to reduce DON size. Containers is another solution we are exploring. In any case, [each version has it's own performance improvements](https://developers.elementor.com/how-elementor-improved-asset-loading-and-made-your-website-run-faster/).
