### ISSUE TITLE
🐞 Bug report:  both  elementor/editor/before_enqueue_scripts and elementor/editor/after_enqueue_scripts write to head in preview / editor

### ISSUE THREAD

**Issue by christianswanepoel** [elementor/elementor#17879]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When my JavaScript loads correctly in preview but in editor it keeps rendering in the frame head. This happens with both corrusing elementor/editor/before_enqueue_scripts and elementor/editor/after_enqueue_scripts 

### Steps to reproduce

Plugin code…

```
class Elementor_orenda_vcard extends \Elementor\Widget_Base {
. . .  
       public function get_script_depends() {
		wp_register_script( 'my-widget', 'https://myscript.com' ); 
		return ['my-widget'];
	}

	protected function render() {
		echo '<div>Howdy</div>';

		add_action( 'elementor/editor/after_enqueue_scripts', function() { 
			wp_enqueue_script( 'my-widget' );
		});
}
}
```

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

`
### wp-core ###

version: 5.9
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 255.54 MB (267948072 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 10.29 KB (10537 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 10.42 MB (10929825 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 28.42 MB (29800322 bytes)
database_size: 4.25 MB (4456448 bytes)
total_size: 298.64 MB (313145204 bytes)

### wp-active-theme ###

name: Skelementor (skelementor)
version: 1.1.4
author: Mousebuilt (Konker)
author_website: https://mousebuilt.com.au/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, title-tag, post-thumbnails, automatic-feed-links, html5, custom-logo, custom-header, woocommerce, menus
theme_path: /var/www/html/wp-content/themes/skelementor
auto_update: Disabled

### wp-themes-inactive (4) ###

Twenty Nineteen: version: 2.1, author: the WordPress team (latest version: 2.2), Auto-updates disabled
Twenty Twenty: version: 1.8, author: the WordPress team (latest version: 1.9), Auto-updates disabled
Twenty Twenty-One: version: 1.4, author: the WordPress team (latest version: 1.5), Auto-updates disabled
Twenty Twenty-Two: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (2) ###

Elementor: version: 3.5.5, author: Elementor.com, Auto-updates disabled
Orenda Widgets for Elementor: version: 1.1.1, author: Orenda Finance, Auto-updates disabled

### wp-plugins-inactive (5) ###

Akismet Anti-Spam: version: 4.2.1, author: Automattic (latest version: 4.2.2), Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Misha Update Checker: version: 1.0, author: Misha Rudrastyh, Auto-updates disabled
Orenda Finance: version: 0.0.0, author: Christian Swanepoel, Auto-updates disabled
Progressive WordPress (PWA): version: 2.1.13, author: Nico Martin, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 aarch64 2021-01-25 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: 9.53.3

### wp-server ###

server_architecture: Linux 5.10.76-linuxkit aarch64
httpd_software: Apache/2.4.51 (Debian)
php_version: 7.4.27 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.74.0 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.6.5-MariaDB-1:10.6.5+maria~focal
client_version: mysqlnd 7.4.27
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

**Comment by rami-elementor** [comment]
@christianswanepoel 

See the documentation at https://developers.elementor.com/docs/widgets/widget-dependencies/#registering-scripts-styles The script will be loaded only if the "**Elementor_orenda_vcard**" widget is used in the page.

```php
class Elementor_orenda_vcard extends \Elementor\Widget_Base {

       public function get_script_depends() {
		wp_register_script( 'my-widget', 'https://myscript.com' ); 
		return ['my-widget'];
	}

	protected function render() {
		echo '<div>Howdy</div>';
	}

}
```

Also check https://developers.elementor.com/docs/scripts-styles/

**Comment by christianswanepoel** [comment]
Hi @rami-elementor 
I am aware how to use the widget on a page - the issue is, as the title says, elementor/editor/before_enqueue_scripts and elementor/editor/after_enqueue_scripts. As both insert my code in the <head> of the <iframe> of the editor.

I need the widget to draw in the elementor editor, and the code needs to be loaded some time after my echo '<div>Howdy</div>'. 
i.e. the script needs to be added before </body>

**Comment by christianswanepoel** [comment]
The following fixes the above issue - but Elementor doesn't execute the `<script>` in Editor but does in Preview and Live site. Despite the `<script>` being in the `<iframe><body>` where it should be. 

```

public function get_script_depends() {

wp_register_script( 'my-widget', 'https://my-javascript.link', [], null, true );

wp_enqueue_script('my-widget');

return [‘my-widget'];

}

```

I ma guessing I need to get `elementor/editor/after_enqueue_scripts` working - but it seems to have no effect..

**Comment by rami-elementor** [comment]
You should not _enqueue_ the script inside the `get_script_depends()` method, only _register_ the script.

```php
public function get_script_depends() {
    wp_register_script( 'my-widget', 'https://my-javascript.link', [], null, true );
    return [ 'my-widget' ];
}
```

Regarding to script loading, can you attach your JS?
