### ISSUE TITLE
3 tips about Version 3.6.0-dev39

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17878]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

1- If none of the direction options are enabled (disable all), it is not clear what the default mode is. https://prnt.sc/iV93z607-4_v
I think it is better if we disable all the direction options, the default mode is a little more prominent than the other options to know what the default direction mode is. As you know, the default mode for direction is row.

2- **This may be a bug.** From dev 39 onwards, when we add a widget to the container, there is no space around it and it sticks perfectly around. Even if the Content Width is on a box. https://prnt.sc/Rq1pSdcpK3pB
**It should be noted that spacing is set to 20 by default.**

3- **I had a question at the end, thank you for answering.** In older versions, we could consider the width of a widget as inline. But in the container we can only specify its width. https://prnt.sc/Np4Dj6GuJDWO
In the container, how can we consider the width of a widget inline?  With Align Self?

### Describe the solution you'd like

-

**Comment by shilo-ey** [comment]
Hey Hosein, thanks for sharing your feedback!

I would like to answer the topics you raised:

1- the "none" value for direction is Row
2- Padding was removed from the default state of every container for consistent design
3- You can set the container direction to be Row and adjust the width to your needs

Thanks.

**Comment by 79ho3ein** [comment]
thank you @shilo-ey.
2- is there no alternative? For example, isn't it better to add the **Columns Gap** option as in previous versions? The current situation is causing damage to other parts. For example, whatever nested container we add, we can not access the settings of that container except by using navigation! please Watch the video below.


https://user-images.githubusercontent.com/77163248/154908653-6c2b06ae-2c64-4a6c-82b3-edfdc2ba0f9e.mp4

Therefore, the containers are completely inside each other and are not nested. So that if we put 2 containers inside each other, only one container is visible.
Is it possible to re-add the Columns Gap option?

**Comment by nicholaszein** [comment]
Hello!

This issue has been partially solved since the latest versions of Elementor.

I'm just commenting here to ensure this issue has been accounted for when we launch the stable version of the Flexbox Container.

Thanks for sharing your insights!
