### ISSUE TITLE
🚀 Feature Request: Dynamic tags for Typography

### ISSUE THREAD

**Issue by RumenGeorgieff** [elementor/elementor#17889]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

if the Typography can use dynamic tags, this will allow much more local styling for each page. For example, with ACF, Pods or JetEngine it will be possible to create a metabox for a specific page / post through which to change the typography only for the specific page.

### Describe the solution you'd like

Typography to be able to use dynamic tags, like colors or other parts of widgets can.

**Comment by rami-elementor** [comment]
Hi @RumenGeorgieff 

Thank you for submitting a feature request. 

After review, we have decided not to add this to our roadmap. Dynamic Tags are built to add custom functionality, it's not used for styling. 

We understand you use case, but it can be achieved with other methods, not using Dynamic Tags.

Regards,

**Comment by RumenGeorgieff** [comment]
Then why colors have dynamic tags? Can you mention some of those "other methods" for achieving this? Thanks :)

**Comment by RumenGeorgieff** [comment]
Thanks for the links. Check this: https://prnt.sc/Cd6q1x7ItHdJ . Here you can set dynamic color from post custom field. This is the same feature that I suggest for typography :)
