### ISSUE TITLE
Social Login and Theme My Login

### ISSUE THREAD

**Issue by Zoruak** [elementor/elementor#17888]
Please add more functionality on the login.
I wanna have custom default login, like its possible with ThemeMyLogin Plugin.

And please add Social Login!

Thanks!

**Comment by rami-elementor** [comment]
Thanks for the feedback,

Please follow guidelines for opening a new feature request, so we can help you better.

This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
