### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by hoclaya** [elementor/elementor#17881]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

 when I select the query option in the toolbar on the left (where I would generate the designation), it comes up blank. 
<img width="1592" alt="Screen Shot 2022-02-04 at 11 28 51 AM" src="https://user-images.githubusercontent.com/17105506/154735025-d24e26be-b822-47e4-8080-ade7f50536b9.png">

### Steps to reproduce

<img width="1592" alt="Screen Shot 2022-02-04 at 11 28 51 AM" src="https://user-images.githubusercontent.com/17105506/154736094-3148b479-e579-487c-ae7f-ed47211bf7e3.png">

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '39', Revision '305619d' v5.7.36-39
	PHP Version: 7.4.26
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://ghcorps.org
	Home URL: https://ghcorps.org
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: admin@ghcorps.org
	Debug Mode: Inactive

== Theme ==
	Name: GHC
	Version: 10.9
	Author: GHC
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.5.14
		Author: Elliot Condon

	All in One SEO
		Version: 4.1.5.3
		Author: All in One SEO Team

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.5.3
		Author: Takayuki Miyoshi

	Custom Twitter Feeds
		Version: 1.8.4
		Author: Smash Balloon

	Elementor
		Version: 3.6.0-dev39
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0-dev18
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.0.9
		Author: WPDeveloper

	Facebook for WordPress
		Version: 3.0.6
		Author: Facebook

	Max Mega Menu
		Version: 2.9.5
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.2.4
		Author: megamenu.com

	Newsletter
		Version: 7.3.3
		Author: Stefano Lissa & The Newsletter Team

	Newsletter - Addons Manager
		Version: 1.1.5
		Author: The Newsletter Team

	Really Simple SSL
		Version: 5.2.0
		Author: Really Simple Plugins

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Smart Slider 3
		Version: 3.5.1.2
		Author: Nextend

	Templately
		Version: 1.3.1
		Author: Templately

	Toolset Types
		Version: 3.4.14
		Author: OnTheGoSystems

	User Photo
		Version: 0.9.10
		Author: <a href="http://weston.ruter.net/">Weston Ruter</a>

	Widget Content Blocks
		Version: 2.3.9
		Author: Danny van Kooten

	Widget Logic
		Version: 5.10.4
		Author: WPChef

	WP Advance Register Login Form
		Version: 1.0
		Author: google

	WP PLACEMENT
		Version: 1.0
		Author: google

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WPE ElasticPress Autosuggest Logger
		Version: 1.0.0
		Author: WP Engine

	WP Engine Cache Plugin
		Version: 1.0.5
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

== Elements Usage ==
	
	footer : 1
		heading : 6
		html : 1
		icon-list : 2
		media-carousel : 1
		social-icons : 1
		text-editor : 2
		theme-site-logo : 1
	header : 2
		button : 1
		heading : 1
		icon : 5
		image : 1
		nav-menu : 1
		theme-site-logo : 1
		wp-widget-maxmegamenu : 1
	page : 1
		accordion : 1
		button : 5
		counter : 1
		divider : 27
		eael-feature-list : 4
		eael-image-accordion : 3
		gallery : 1
		heading : 45
		icon-list : 13
		image : 30
		image-carousel : 1
		menu-anchor : 19
		shortcode : 1
		spacer : 4
		testimonial-carousel : 1
		text-editor : 36
		video : 4
	section : 25
		button : 10
		divider : 6
		heading : 17
		icon : 4
		image : 16
		image-box : 4
		posts : 1
		slides : 2
		spacer : 2
		text-editor : 21
		theme-site-logo : 1
		video-playlist : 1
		wp-widget-maxmegamenu : 1
	widget : 0
		button : 2
		divider : 1
		icon-list : 1
		image : 1
	wp-post : 2
		button : 1
		text-editor : 2
	wp-page : 65
		accordion : 1
		blockquote : 1
		button : 98
		call-to-action : 59
		counter : 12
		divider : 195
		eael-adv-tabs : 1
		eael-contact-form-7 : 1
		eael-feature-list : 16
		eael-image-accordion : 6
		eael-post-grid : 4
		eael-progress-bar : 14
		eael-twitter-feed : 1
		facebook-page : 1
		flip-box : 16
		gallery : 1
		heading : 432
		html : 3
		icon : 8
		icon-box : 16
		icon-list : 54
		image : 278
		image-box : 4
		image-carousel : 1
		media-carousel : 1
		menu-anchor : 33
		posts : 5
		progress : 3
		shortcode : 5
		spacer : 27
		text-editor : 299
		theme-page-title : 1
		toggle : 10
		video : 17
		video-playlist : 1
		wp-widget-custom_html : 1
	single-post : 1
		button : 1
		divider : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-title : 1
	single-page : 5
		blockquote : 1
		button : 5
		divider : 3
		heading : 10
		image : 8
		text-editor : 4
		theme-post-content : 4

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 342022-01-31 13:09:52 [info] elementor::elementor_updater Started 
2022-01-31 13:09:52 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-31 13:09:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev35',
  'to' => '3.6.0-dev36',
)]
2022-01-31 13:09:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-31 13:09:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev35',
  'to' => '3.6.0-dev36',
)]
2022-02-03 13:11:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev36',
  'to' => '3.6.0-dev37',
)]
2022-02-03 13:11:31 [info] elementor::elementor_updater Started 
2022-02-03 13:11:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-03 13:11:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-03 13:11:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev36',
  'to' => '3.6.0-dev37',
)]
2022-02-15 01:11:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev37',
  'to' => '3.6.0-dev38',
)]
2022-02-15 01:11:10 [info] elementor::elementor_updater Started 
2022-02-15 01:11:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-15 01:11:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-15 01:11:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev37',
  'to' => '3.6.0-dev38',
)]
2022-02-17 13:12:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev38',
  'to' => '3.6.0-dev39',
)]
2022-02-17 13:12:17 [info] elementor::elementor_updater Started 
2022-02-17 13:12:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-17 13:12:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-17 13:12:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev38',
  'to' => '3.6.0-dev39',
)]

PHP: showing 3 of 3PHP: 2022-01-25 13:09:26 [notice X 88306][/nas/content/live/ghcorps/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-31 17:56:53 [notice X 3][/nas/content/live/ghcorps/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-10 01:11:09 [warning X 1][/nas/content/live/ghcorps/wp-content/plugins/elementor-beta/modules/developer-edition/core-version-control.php::183] uasort() expects parameter 1 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-01-31 15:54:51 [error X 13][https://ghcorps.org/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.6.0-dev36:2:223706] Cannot read properties of undefined (reading \'global\') 
JS: 2022-02-04 15:18:45 [error X 10][https://ghcorps.org/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.6.0-dev18:2:94757] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-02-04 16:19:17 [error X 4][https://ghcorps.org/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.6.0-dev18:2:94756] undefined is not an object (evaluating \'this.elementSettingsModel.attributes\') 
JS: 2022-02-05 23:12:14 [error X 21][https://ghcorps.org/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.6.0-dev37:2:223706] undefined is not an object (evaluating \'L[C]\') 
JS: 2022-02-08 17:25:15 [error X 1][https://ghcorps.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:478971] elementor.getCurrentElement().getContainer is not a function. (In \'elementor.getCurrentElement().getContainer()\', \'elementor.getCurrentElement().getContainer\' is undefined) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Essential Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible

**Comment by shilo-ey** [comment]
I merged this issue with #17885, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
