### ISSUE TITLE
🐞 Bug report: Validation issue 2

### ISSUE THREAD

**Issue by Jelena1** [elementor/elementor#17893]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Error: Bad value false for attribute hidden on element [div]
in HTML Validator for Tabs. Please fix.

### Steps to reproduce

Use tabs element.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html><body>

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1 |  
PHP Version: | 7.4.27 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 128M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
