### ISSUE TITLE
🚀 Custom icon for share button widget.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17896]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add the ability to load a custom icon (svg) to the share button widget. It is very important and necessary. The current situation is not really good.

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
Hi @Michaelgimii,

Share button widget and icons widgets are two completely different things. With icons widget you can select custom SVG files but with share buttons widgets each icon has an entire JS logic behind it that send data to an external service.

Even if users could select custom SVG icons, they can't add the functionality.

**Comment by Michaelgimii** [comment]
@rami-elementor 
So, is it not possible to add a custom icon feature for the share buttons widget? That is, elementor does not add this feature?

**Comment by rami-elementor** [comment]
@Michaelgimii 

You can use two widgets side-by-side, the **Share Button** widget and the **Icon** widget.

In both widgets go the the "advanced" tab, select the "position" section and set the "width" to "inline".
