### ISSUE TITLE
History not working for me on 3.7.0-dev24

### ISSUE THREAD

**Issue by ianstudio** [elementor/elementor#17891]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Using Hello Elementor Theme

					
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.26
	PHP Version: 8.1.2
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://ianstudio.ch
	Home URL: https://ianstudio.ch
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 1280M
	Max Memory limit: 1280M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Rome
	Admin Email: webmaster@ianstudio.com
	Debug Mode: Inactive

== Theme ==
	Name: ianstudio
	Version: 1.0
	Author: in-pulse.me
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15

== Active Plugins ==

	Elementor
		Version: 3.6.0-dev39
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev24
		Author: Elementor.com

== Must-Use Plugins ==
	Plugin Organizer MU
		Version: 9.7
		Author: Jeff Sterup

	WP Time Capsule
		Version: 
		Author: Revmakx

== Elements Usage ==
	
	container : 1
		container : 1
		quadmenu : 1
	footer : 1
		container : 5
		nav-menu : 3
	header : 1
		container : 1
		dyncontel-popup : 1
	page : 2
		container : 1
		nav-menu : 1
		text-editor : 1
	section : 4
		form : 1
		heading : 6
		icon : 1
		image : 2
		media-carousel : 1
		menu-anchor : 1
		premium-img-gallery : 1
		social-icons : 1
		text-editor : 5
	single : 1
		post-navigation : 1
		theme-post-content : 1
	wp-post : 0
		button : 5
		container : 41
		divider : 26
		heading : 73
		icon : 3
		icon-list : 1
		image : 6
		progress : 16
		shortcode : 1
		social-icons : 1
		spacer : 54
		text-editor : 41
		theme-page-title : 8
		theme-post-title : 1
	wp-page : 15
		container : 19
		heading : 2
		icon-list : 3
		photomentor-gallery-packery : 2
		shortcode : 1
	single-page : 1
		container : 1
		theme-post-content : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 362022-02-16 16:29:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-16 16:29:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-16 16:29:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev19',
  'to' => '3.7.0-dev22',
)]
2022-02-16 16:32:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev22',
  'to' => '3.7.0-dev23',
)]
2022-02-16 16:32:45 [info] elementor-pro::elementor_pro_updater Started 
2022-02-16 16:32:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-16 16:32:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-16 16:32:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev22',
  'to' => '3.7.0-dev23',
)]
2022-02-16 16:32:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev22',
  'to' => '3.7.0-dev23',
)]
2022-02-19 18:16:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev38',
  'to' => '3.6.0-dev39',
)]
2022-02-19 18:16:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.3.3',
  'to' => '2.3.4',
)]
2022-02-19 18:16:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.3.3',
  'to' => '2.3.4',
)]
2022-02-19 18:16:22 [info] elementor::elementor_updater Started 
2022-02-19 18:16:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-19 18:16:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-19 18:16:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev38',
  'to' => '3.6.0-dev39',
)]
2022-02-19 18:50:09 [info] elementor-pro::elementor_pro_updater Started 
2022-02-19 18:50:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-19 18:50:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-19 18:50:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev23',
  'to' => '3.7.0-dev24',
)]

PHP: showing 3 of 3PHP: 2022-02-11 19:01:34 [warning X 9][/home/clients/3341b0c2e3a3bfca8967967cd3e89e60/ianstudio/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/home/clients/3341b0c2e3a3bfca8967967cd3e89e60/ianstudio/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-11 19:18:47 [notice X 738][/home/clients/3341b0c2e3a3bfca8967967cd3e89e60/ianstudio/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-11 19:20:57 [notice X 1][/home/clients/3341b0c2e3a3bfca8967967cd3e89e60/ianstudio/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-02-11 21:28:09 [error X 9][https://ianstudio.ch/wp-content/plugins/elementor/assets/js/editor.min.js:2:401633] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-02-11 22:25:59 [error X 7][https://ianstudio.ch/wp-content/plugins/dynamic-content-for-elementor/assets/js/copy-paste-cross-sites.js:100:28] Can\'t find variable: dce_model_cid 
JS: 2022-02-11 22:27:00 [error X 3][https://ianstudio.ch/wp-content/plugins/premium-addons-for-elementor/assets/editor/js/premium-cross-cp.js:12:22] null is not an object (evaluating \'b.elecode\') 

== Elementor - Compatibility Tag ==

== Elementor Pro - Compatibility Tag ==
	

				
</details>

**Comment by rami-elementor** [comment]
Thanks for reporting,

Please follow guidelines for opening a new issue report, so we can help you better.

This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
