### ISSUE TITLE
🚀 Feature Request: Transform Hover Class/ID Selector

### ISSUE THREAD

**Issue by urieljsoto** [elementor/elementor#17892]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I hate how I cant choose my own hover class/id to my transform hover option. It's like they gave it to us half done. 

### Describe the solution you'd like

I want to choose which class or id will trigger my transform hover effect in the new transform feature. I hope this is simple enough to understand.

**Comment by rami-elementor** [comment]
Hi @urieljsoto ,

Thank you for submitting a feature request. 

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Regards,

**Comment by urieljsoto** [comment]
It's better than the useless things you think people will like. Instead you
should focus on the things people need.
