### ISSUE TITLE
🔥 Criticism of the elementor team

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17898]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

For a long time, I wanted to have this criticism from the elementor team, but I decided to raise this criticism here to know the opinion of other users...

Elementor team, it's really weird that you do not pay any attention to the requests of your users in GitHub. There are very simple requests in this GitHub that are at least 4 years old. Why should it be like this?
Suppose new requests do not matter at all. But why not fix the bugs? All these bugs have been reported by users on GitHub. Users who are interested in elementor report these bugs so that elementor minimizes bugs. But no attention is paid.
What is elementor really looking for?
I myself spend hours a day identifying elementor bugs and reporting them here. But when no attention is paid to them, what is the solution?
Do we charge you for a bug report? No, we do this entirely out of interest in elementor.
See this : https://prnt.sc/C2GaX-fbQVwh         I registered a new feature request in crocoblock and it was added to the plugin only after **11 days**.  
**Now see this bug report in elementor : #16566**         Does it take a long time to fix such a simple thing?
In the example of Crocoblock above, there was a new feature request. See this bug report now : https://prnt.sc/vCRj1JVsdljF
**Only one day!**

In my opinion, if elementor is really going to care about users' opinions and ideas, it should increase its interaction with its users a bit. So that when we (users) report a bug, we know what stage it is at. Have the developers seen our report? Have they succeeded in reproducing it? Will it fix it in the new version? Or, for example, in which version this bug will be fixed. All of this lets users know that their request is being considered.
Finally I had a request from the elementor team. Please, please, please, increase your interaction with users. Provide a platform for users to report all bugs they have identified. It's really worthwhile for elementor to have a team to fix the current bugs.
An example: Pro3.6 version has several bugs. Many users are still left in previous versions...
There is a lot of talk and criticism ... I hope elementor speeds up its evolution as well as fixes its bugs. Before giving way to another plugin.

### Steps to reproduce

-

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by oooh-boi** [comment]
This is not the place to land such a post, however...
I work with Elementor every single day. Not only that developer docs are extremely poor/lame/clumsy/incomplete, there's a ton of bugs that are just piling up with every new release. Some of the bugs are even a few years old. 
Should I start with user support? I better don't. 
Everything is so great and shiny all over the web when it comes to Elementor while just a couple inches "below the surface" things start to smell really bad.
I AM TRULY AND HONESTLY SORRY TO SAY THAT but when you're left on your own to spend time on all kinds of workarounds and solutions and patches due to the overall clumsiness underneath the hub of Elementor, I just can not to keep my mouth shut. 
@Michaelgimii - I can fully understand your frustration.

**Comment by Michaelgimii** [comment]
Many bugs are added in each update. Version 3.6 was buggy. Still does not work in the new version of the custom code. Do they even know what they are doing?
I know this was not the place for this request. But I wanted users to comment as well to see what happens. This situation is really disappointing. If I want to describe all the bugs in elementor, I have to write for 2 days in a row!
I do not know. I hope elementor thinks about this issue ...

**Comment by shilo-ey** [comment]
Hi,
We would like to thank you for the feedback and the great effort you put into reporting bugs, it really makes the difference for us and Elementor's web creators. 

We take these bugs very seriously and work tirelessly on fixing them, small and big alike, while developing more necessary capabilities.

As we're using a different platform to manage the bugs (Github is one source of but reports), it might not always be reflected on Github.
We are currently working on some of the fixes you reported such as [#16566](https://github.com/elementor/elementor/issues/16566), and are simultaneously working on providing our users with more transparency into what we’re currently working on. 

We promise to communicate more here and on other platforms with every new fix we deploy.

Thank you again.

**Comment by Michaelgimii** [comment]
@shilo-ey , You're Great. I hope you are not upset with my criticism.

**Comment by oooh-boi** [comment]
@shilo-ey thanks for the lesson on how to be polite!
