### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by PansiPassword1** [elementor/elementor#17907]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

I needed to redownload the Soledad theme because Elementor did not seem to work. I assumed there must have been an update, which worked out. There was a needed update and I uploaded it, and was able to use Elementor to make pages.

But on my homepage, my slider just disappeared upon doing this. I could never use Elementor there, and I worried then why I couldn't seem to use it. But nothing seems to be wrong all over the rest of the site, just the homepage slider. I am not sure if this needs to be addressed here or with Pensi (Soledad makers)

### Steps to reproduce

Not really sure honestly. I know the Elementor plugin is working just fine all over the rest of the website. But seems to not be working on the homepage at all. I assume this might be why my slider is now magically not working when it was prior.

That Pensi slider is harder to add on any page without Elementor the moment you have this plugin installed for some reason. It was working before, but not on the homepage as mentioned prior. Now it's as if Elementor woke up to work on the homepage yet still IS NOT working there.

Yet it WILL work on the rest of the site. I cannot possibly explain this.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: Percona Server (GPL), Release 90.0, Revision 9dd29a1 v5.6.50-90.0
	PHP Version: 7.4.10
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://www.manvs.co
	Home URL: https://www.manvs.co
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: soledad
	Version: 8.1.1
	Author: PenciDesign
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

== Active Plugins ==
	Accelerated Mobile Pages
		Version: 1.0.77.36
		Author: Ahmed Kaludi, Mohammed Kaludi

	Adminimize
		Version: 1.11.7
		Author: Frank Bültge

	Advanced post slider
		Version: 2.5.1
		Author: digontoahsan

	AMP
		Version: 2.2.1
		Author: AMP Project Contributors

	Candid Advanced Toolset
		Version: 1.0.8
		Author: Candid Themes

	Child Theme Configurator
		Version: 2.5.8
		Author: Lilaea Media

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd
		Version: 6.9.0.8
		Author: SeedProd

	Contact Form 7
		Version: 5.5.5
		Author: Takayuki Miyoshi

	Disable Gutenberg
		Version: 2.6
		Author: Jeff Starr

	Elementor
		Version: 3.6.0-dev39
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Fancy Facebook Comments
		Version: 1.2.8
		Author: Team Heateor

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Jetpack
		Version: 10.6
		Author: Automattic

	MC4WP: Mailchimp for WordPress
		Version: 4.8.6
		Author: ibericode

	oAuth Twitter Feed for Developers
		Version: 2.3.0
		Author: Liam Gladdy (Storm Consultancy)

	One Click Demo Import
		Version: 3.0.2
		Author: OCDI

	Penci Portfolio
		Version: 3.0
		Author: PenciDesign

	Penci Recipe
		Version: 3.3
		Author: PenciDesign

	Penci Review
		Version: 2.7
		Author: PenciDesign

	Penci Shortcodes & Performance
		Version: 4.5
		Author: PenciDesign

	Penci Slider
		Version: 1.1
		Author: PenciDesign

	Penci Soledad Demo Importer
		Version: 3.8
		Author: PenciDesign

	PWA for WP
		Version: 1.7.41
		Author: Magazine3

	Site Kit by Google
		Version: 1.68.0
		Author: Google

	Vafpress Post Formats UI
		Version: 1.7
		Author: vafpress

	Widget Shortcode
		Version: 0.3.5
		Author: Hassan Derakhshandeh

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.7.2.1
		Author: WPForms

	WP Super Cache
		Version: 1.7.7
		Author: Automattic

	Yoast SEO
		Version: 18.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.0
		Author: Team Yoast

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active

== Log ==
	
Log: showing 10 of 102022-02-14 10:59:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.0-dev37',
)]
2022-02-14 10:59:10 [info] elementor::elementor_updater Started 
2022-02-14 10:59:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-14 10:59:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-14 10:59:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.0-dev37',
)]
2022-02-14 10:59:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.0-dev37',
)]
2022-02-17 13:01:43 [info] elementor::elementor_updater Started 
2022-02-17 13:01:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-17 13:01:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-17 13:01:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev37',
  'to' => '3.6.0-dev39',
)]

PHP: showing 1 of 1PHP: 2022-02-14 11:01:11 [notice X 3820][/hermes/bosnacweb07/bosnacweb07ag/b1989/ipg.burgettjoe00925694/manvs.co/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
