### ISSUE TITLE
Feature Request:  Avoid the BLOCK/Gutenberg editor entirly.

### ISSUE THREAD

**Issue by petervangorder** [elementor/elementor#17916]
I'm using Elementor (thank you!) and ToolSet.  
They pair wonderfully!  - except for in one usage:  Views. 

As far as I can tell, if I want to use Toolset Repeatable fields (or any other complicated query) then I'm left with using Views in a way that forces me to use the new wordpress block editor.   Aaahrg!  Not only is the "block editor" the worst editor in history (so confusing, impossible to do anything quickly), it means that any styling or custom CSS I've done for things like "accordions" or any thing else suddenly has to be recreated in with all new CSS - and I have to of course override all the built-in css for it as well.

There are also bugs in the BLOCK editor wherein if you try to use a short-code for a LINK, it will oddly strip the ":" of the "http://" part of the link.  [See this image for an example.](https://petervangorder.com/dm/wp-content/uploads/2022/02/Screen-Shot-2022-02-21-at-12.36.21-PM.png).
I know you're not responsible for the issues with the BLOCK editor - I'm just pointing out one of the many reasons why the block editor should be blocked and avoided - in favor of Elementor template parts.

But most simply:  If I'm forced to use the BLOCK editor at any point, then I'm redoing all my styling and CSS again, and many of the most amazing styling features of Elementor are suddenly not available and then...  what's the point?

So please-please-please figure out a way we can use build and use some template part in Elementor that can be referenced by a ToolSet VIEW so we can skip the BLOCK editor all together.

Thanks for listening!

**Comment by rami-elementor** [comment]
Hi @petervangorder 

Thank you for the feedback.

While reviewing your report, we noticed it was missing the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/elementor/elementor/issues/new?assignees=&labels=bug&template=bug.yaml&title=%F0%9F%90%9E+Bug+report%3A+).

Please feel free to open a new issue in accordance with these guidelines.

Regards,

**Comment by petervangorder** [comment]
I was trying to make a Feature Request.
Did I put it in the wrong place?

Is there another, better place to make a Feature Request?

For a Feature Request, I don’t see how any of these are applicable:
> Prerequisites
> Steps to replicate
> Isolating the problem
> System info

I put submitted this feature request on the GitHub site because the instructions and link on the Elementor.com website.

 - peter

   Peter van Gorder
   (707) 486-2048
   Dream-Create-Communicate.com

**Comment by rami-elementor** [comment]
@petervangorder 

All the required fields are here:

https://github.com/elementor/elementor/issues/new?assignees=&labels=request&template=feature_request.yml&title=%F0%9F%9A%80+Feature+Request%3A+
