### ISSUE TITLE
🐞 Bug report:  Contact page

### ISSUE THREAD

**Issue by calvinspires1** [elementor/elementor#17915]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

My contact page shows the below

404 Not Found
Looks like you have taken a wrong turn. Dont worry it happens to the best of us.
[RETURN TO HOME PAGERETURN TO HOME PAGE](https://spirescourierllc.com/)
[Transport WordPress Theme](https://www.themescaliber.com/themes/free-logistics-wordpress-theme/) By ThemesCaliber

### Steps to reproduce

deactivated all plugins to resolve issue as indicated above.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

404 Not Found
Looks like you have taken a wrong turn. Dont worry it happens to the best of us.
[RETURN TO HOME PAGERETURN TO HOME PAGE](https://spirescourierllc.com/)
[Transport WordPress Theme](https://www.themescaliber.com/themes/free-logistics-wordpress-theme/) By ThemesCaliber

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
