### ISSUE TITLE
✅ 🐞 Bug report: Inline Font Icons - Missing icons on form fields

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#17929]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The icons on the form widget don't show when you have Inline Font Icons experiment active.

![elementor-form-missing-arrow](https://user-images.githubusercontent.com/7768009/155154418-c09fbd5a-d74b-4b04-a4de-fb4e1439091e.jpg)

### Steps to reproduce

Activate Inline Font Icons experiment and create a form with a select field. The dropdown icon is missing from the field when viewed on the front end of the website (not logged in).

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.37
	PHP Version: 7.4.27
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	

== Active Plugins ==
	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Crocoblock Wizard
		Version: 1.2.3
		Author: Crocoblock

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	Jet Appointments Booking
		Version: 1.6.7
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.2
		Author: Crocoblock

	JetEngine
		Version: 2.11.3
		Author: Crocoblock

	JetReviews For Elementor
		Version: 2.2.4
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.10
		Author: Crocoblock

	Safe SVG
		Version: 1.9.9
		Author: Daryll Doyle

	User Profile Picture
		Version: 2.6.0
		Author: Cozmoslabs

	Wordfence Security
		Version: 7.5.8
		Author: Wordfence


== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Active
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive


	

````

</details>

**Comment by nicholaszein** [comment]
Hello there @mcrowell!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
