### ISSUE TITLE
🚀 Feature Request: Add Outfit font to Google fonts

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#17930]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello,

The Outfit font seems to be missing in the font list: https://fonts.google.com/specimen/Outfit

### Describe the solution you'd like

Add it to the list.

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!
