### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Custom Icon for Menu Cart Widget (Duplicate of #13678) - [ED-7187]

### ISSUE THREAD

**Issue by ahmedzeidan** [elementor/elementor#17941]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

the menu cart widget uses pre-set icons which in most times does not match the theme or the used icons around the site...

### Describe the solution you'd like

to allow using fontaewsome icons or SVG upload

### Describe alternatives you've considered

by using powerpack addon

### Additional context

topic is also discussed here: https://forum.elementor.com/getting-started-7/custom-icon-for-menu-cart-widget-9870

**Comment by 3l3mentor** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
