### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Enable ACF-Fields in "Posts Widget" - "Meta Data" Settings (Duplicate of #4440)

### ISSUE THREAD

**Issue by Stml-St** [elementor/elementor#17940]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I cannot display Advanced Custom Fields in the "Posts widget - Meta Data", there is just "author, date, time, comments and date modified".

### Describe the solution you'd like

I would like to display Advanced Custom Fields in the "Posts widget - Meta Data" (Screenshot).

![feature-request](https://user-images.githubusercontent.com/29859095/155213151-de492e90-aa45-456e-9197-f74b3762e7d1.png)

### Describe alternatives you've considered

I have used Plugins like "Elementor Custom Skin" and "JetElements For Elementor". Both Plugins can do ACF Fields for the "Posts Widget" respectively JetElements has their own "Posts Widget" that can load ACF-Fields.

**Comment by euene** [comment]
This, and much more will be possible when the loop builder (#4440) launches later this year.

https://lookingforward.elementor.cloud/

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
