### ISSUE TITLE
🐞 Bug in drag and drop widgets.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17968]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hello

If we drag and drop the widget to the top of the page, this widget will move to the bottom of the page. While it should be in the desired position. Please watch the video below :

https://user-images.githubusercontent.com/77163248/155517686-e56f97f4-349c-402e-a5f4-01d8e73c892b.mp4

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by perks98** [comment]
+1 I get the same problem

**Comment by iamdanbarrett** [comment]
We have been something similar in that we have to duplicate an element in order to move it to another location and then delete the original.

**Comment by 79ho3ein** [comment]
@iamdanbarrett , If I'm not mistaken, this bug was added in version 3.5 core. But it certainly was not so from the beginning. Even in 3.6 dev, this bug does not exist and has been corrected.
