### ISSUE TITLE
🚀 Feature Request: WooCommerce - Form LOGIN/LOGOUT 

### ISSUE THREAD

**Issue by ilkanellop** [elementor/elementor#17976]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Adding this feature will help the users of elementor singing in the main dashboard of woocommerce without the need of buying a plugin that creates registration form that integrate with woocommerce and the customer role that is needed to apply in order to view the dashboard of the customer. 

### Describe the solution you'd like

To add login/logout feature that intergrades with woocommerce customer role.

**Comment by nicholaszein** [comment]
Hello @ilkanellop,

Thank you for submitting a feature request! 🙏 

### 📢 We have great news! 

✔️ Elementor Pro **[already has a Login widget](https://elementor.com/blog/pro-v140-login-widget/)**, it was introduced in **Elementor Pro v1.4**, in 2017. It allows you to redirect the user after login into a link of your liking just as you requested.

#### Please make sure to visit [this article](https://elementor.com/help/login-widget-pro/) to learn how to use the Login widget (Pro).

Please feel free to contact us again with other feature suggestions. 😉 

Cheers 🥂
