### ISSUE TITLE
[⌛ Awaiting Feedback]🐞 Bug report: Convert to Container messes up the layout too much

### ISSUE THREAD

**Issue by Fritsflow** [elementor/elementor#17970]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Convert to container messes up a website to much. Tried it on the "portrait photography" website from the kit library on header and hero. 

### Steps to reproduce

convert header and hero to container and layout messes up. Using Hello theme, latest WP vesrion.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-staging.fritsdewolf.com-24-02-2022.txt](https://github.com/elementor/elementor/files/8132925/system-info-staging.fritsdewolf.com-24-02-2022.txt)

**Comment by shilo-ey** [comment]
Can you provide some examples?

Other than that - please add a title to your issue.

**Comment by fabianenzensperger** [comment]
Yes. It's still quite a disaster. The conversion does not keep the width setting, i.e. "Boxed" or "Full-Width", and doesn't take the individually values.

**Comment by 79ho3ein** [comment]
Friends, please watch this video :

https://user-images.githubusercontent.com/77163248/155572806-5fd1a409-1af1-406e-a5ba-29b9ad8fab70.mp4

In this video, when I added the second container, it completely merged into the first container. So, even if we put 10 containers inside each other, they will merge perfectly.
In other words, in the container, we do not have the container Gap option. (Like the former) https://prnt.sc/pWaW7_I-5UgG
This is why containers are merged. I feel that if this option does not exist, there will be many disorders. Am I wrong?

**Comment by nicholaszein** [comment]
Hello guys, do you think this is still an issue?

@fabianenzensperger, @79ho3ein, @Fritsflow

**Comment by fabianenzensperger** [comment]
> Hello guys, do you think this is still an issue?
> 
> @fabianenzensperger, @79ho3ein, @Fritsflow

Hi @nicholaszein I can only speak by myself, but I think this feature is good now. Maybe not in all cases, but in 98%. 🤗

**Comment by 79ho3ein** [comment]
Hi @nicholaszein , Everything in the container is greatly improved.  thank you🥂

**Comment by nicholaszein** [comment]
Thanks for the feedback @fabianenzensperger and @79ho3ein!

I'm closing this issue as solved! ✔️ 🙌
