### ISSUE TITLE
🐞 Bug report: Container width not working in responsive

### ISSUE THREAD

**Issue by disturbio128** [elementor/elementor#17978]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

The width in the container does not work in responsive view.

https://i.ibb.co/kc3JFDy/01.png 

### Steps to reproduce

Add a container and try to change the width in tablet view

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] I can reproduce this bug consistently using the steps above.

</body>
</html>

**Comment by bobhuf** [comment]
Did you set the items to 'wrap'?

**Comment by alanavelinorb** [comment]
> Did you set the items to 'wrap'?

I don't have it in wrap, but the strange thing is that in mobile view and PC it works in the other breakpoints it doesn't.
