### ISSUE TITLE
🐞 Bug report: 3.6.0-dev41:  Advanced -> Width setting disappears

### ISSUE THREAD

**Issue by joehdevwp** [elementor/elementor#17988]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

The Width setting ( Full Width 100%  / Inline / Custom) that in stable versions is under Advanced -> Positioning appears to have been moved in 3.6 to Advanced -> Layout... or has it?  It is there some times and not others.  When it is there, and set to something other than Default, changing it to Default makes it disappear again with no way to get it back.

Its' there:
![Screen Shot 2022-02-25 at 9 13 33 AM](https://user-images.githubusercontent.com/64614431/155759343-d705dfb9-7477-435d-9ca2-c8f908cdb1b5.jpg)

Now its gone:
![Screen Shot 2022-02-25 at 9 14 41 AM](https://user-images.githubusercontent.com/64614431/155759389-da20898b-8e02-4488-b5e0-321522ba746d.jpg)

### Steps to reproduce

Difficult to say because I am not sure how to make the setting appear initially. I imported a template that had the setting set to Inline, but when I changed this to Default, the setting disappeared, with no way I can see to set it back to Inline. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.3.30
	PHP Version: 7.4.27
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 60M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://wordpress-475499-1918502.cloudwaysapps.com
	Home URL: https://wordpress-475499-1918502.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 60 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: emailjough@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36

== Active Plugins ==
	Breeze
		Version: 2.0.1
		Author: Cloudways

	DethemeKit for Elementor
		Version: 1.5.9.5
		Author: deTheme

	Elementor
		Version: 3.6.0-dev41
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev26
		Author: Elementor.com

	Envato Elements
		Version: 2.0.11
		Author: Envato

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.75
		Author: MalCare Security

	Nexter Extension
		Version: 1.0.8
		Author: POSIMYTH

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Page Transitions: Active by default
	Notes: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 432022-02-22 07:13:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-22 07:13:09 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-02-22 07:13:09 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-02-22 07:13:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.6.2',
)]
2022-02-22 07:13:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.6.2',
)]
2022-02-22 12:48:32 [info] elementor::elementor_updater Started 
2022-02-22 12:48:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-22 12:48:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-22 12:48:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.0-dev40',
)]
2022-02-22 12:48:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.0-dev40',
)]
2022-02-25 09:02:11 [info] elementor-pro::elementor_pro_updater Started 
2022-02-25 09:02:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-25 09:02:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-25 09:02:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.7.0-dev26',
)]
2022-02-25 09:02:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.7.0-dev26',
)]
2022-02-25 09:02:50 [info] elementor::elementor_updater Started 
2022-02-25 09:02:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-25 09:02:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-25 09:02:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev40',
  'to' => '3.6.0-dev41',
)]
2022-02-25 09:02:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev40',
  'to' => '3.6.0-dev41',
)]

== Elementor - Compatibility Tag ==
	
	DethemeKit for Elementor: Compatibility not specified
	Elementor Pro: Incompatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible

**Comment by puregraphx** [comment]
Custom width seems VERY buggy in the (latest) release. I have a similar issue with any other widget where I set custom width under Advanced. It's fine in the Editor and in Desktop frontend, but tablet/mobile completely ignores the custom width.

**Comment by marketingspectrumNL** [comment]
It is very buggy now indeed. Experiencing the same issues as @puregraphx

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.6.2

Feel free to update

Thanks!
