### ISSUE TITLE
🚀 Ability to display "Current Time" as Ajax

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18006]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi
If we display the current time on the website, using the dynamic tag, it will be displayed well. https://prnt.sc/HZdBQ63UJ9en
But there is a problem. If we display the current time on the website, **the time will not be updated unless the page is reloaded**.
This is the only weakness of this problem.
It would be great if develop this feature so that the current time is updated in Ajax. So, time is updated without having to reload the page, and that's great.

### Describe the solution you'd like

Update the current time without having to reload the page.

**Comment by m1ga** [comment]
Why should that be in Elementor? It is not a very common use so no need to be in the core.
Just add an empty element, give it a custom ID and use a simple JS to set and update the time with a simple setInterval e.g. http://jsfiddle.net/5JWEV/ 
Using AJAX would be overkill. 

And I'm pretty sure there are multiple plugins out there displaying the time or create a Elementor plugin yourself with the code from the jsfiddle. Shouldn't take more than 30mins (without publishing it of course)

**Comment by 79ho3ein** [comment]
I agree. Thanks
