### ISSUE TITLE
🔗 🚀 Feature Request: Google maps with shortcodes from the template library (Duplicate of #1319)

### ISSUE THREAD

**Issue by odivius** [elementor/elementor#1803]
Hello,

I think this would be a powerfull solution for creating custom Google Maps:

- Customizing the map colors (like with Snazzy maps)
- Custom markers from the media gallery
=> Custom infoboxes  **with shortcodes from the elementor template library**!

**Comment by arielk** [comment]
I merged this issue with another issue #1319 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
