### ISSUE TITLE
🚀 Feature Request: Ability to show the category meta/category badge in the classic skin in the Posts widget

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#18038]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Why is there still no way to show the category in the posts widget while using the classic skin after all this time?

![image](https://user-images.githubusercontent.com/60075863/156269906-1a4f8c38-e81c-44aa-9bb1-fb90be3618c6.png)

And besides that, the meta options are not linked, there's no way of getting to the archive of that date, author, and moreover, the category.

### Describe the solution you'd like

Allow linking to the meta options and add the category too, also linked. Allow showing the category (or terms) as a badge, the way it is in the card skin, but for the classic skin too.

![image](https://user-images.githubusercontent.com/60075863/156270248-67b610d2-a56b-45ae-ade8-5a53d905d469.png)

I don't know why since you added it in the cards skin, you didn't add it in the classic skin too, but this is a common problem in Elementor widgets, no consistency. The category badge in the cards skin is also not linked, so it just shows up and that's it, you can't click on it and see an archive of the articles containing that specific category.

**Comment by rami-elementor** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
