### ISSUE TITLE
🐞 Bug report: Ongoing issues with styles disappearing - css 404

### ISSUE THREAD

**Issue by rtpHarry** [elementor/elementor#18048]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm having ongoing issues with Elementor where the css styles are disappearing. 

It's happening across totally different sites and servers and caching systems.

It's an ongoing pain for my clients and embarrassment for me.

I'm finding completely unstyled sites, where the css files have just disappeared. 

The folder is empty, or virtually empty:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1038062/156368187-df7aee5c-03b8-4954-8c09-a9dcd2f0af7a.png">

This one is a siteground hosted site with their caching system implemented.

Yesterday I had it with a guru.co.uk / litespeed / litespeed cache hosted site.

What is going on? Why do the sites keep failing? Why doesn't it recover from it? Why doesn't it at least confirm that it can generate new files before deleting the originals?

It's impossible for me to do anything, and I cannot recreate it manually, I just come back to Elementor powered sites and find they are totally visually broken.

### Steps to reproduce

Just wait some time, and sooner or later clients will start complaining.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.28
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://www.thenewhomesagent.co.uk
	Home URL: https://www.thenewhomesagent.co.uk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: matthew@sokastudio.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: TNHA
	Version: 1.0
	Author: Claire Cheyne
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.5
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36

== Active Plugins ==
	301 Redirects
		Version: 2.72
		Author: WebFactory Ltd

	Advanced Custom Fields: Extended
		Version: 0.8.8.7
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 5.12
		Author: Delicious Brains

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Astra Pro
		Version: 3.6.5
		Author: Brainstorm Force

	Avatar Manager
		Version: 1.6.1
		Author: Cătălin Dogaru

	Cachebuster
		Version: 1.3
		Author: Albert Peschar

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.2.2
		Author: Hu-manity.co

	Custom Adobe Fonts (Typekit)
		Version: 1.0.18
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.10.2
		Author: WebDevStudios

	Disable User Login
		Version: 1.3.2
		Author: Saint Systems

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.3
		Author: Elementor.com

	JetEngine
		Version: 2.11.4
		Author: Crocoblock

	Mailgun
		Version: 1.7.9
		Author: Mailgun

	MainWP Child
		Version: 4.1.10
		Author: MainWP

	Ninja Forms
		Version: 3.6.7
		Author: Saturday Drive

	Ninja Forms - Layout & Styles
		Version: 3.0.29
		Author: The WP Ninjas

	SiteGround Optimizer
		Version: 7.0.4
		Author: SiteGround

	The New Homes Agent - Elementor Addons
		Version: 1.0.0
		Author: Matthew Harris, Soka Studio

	Wordfence Security
		Version: 7.5.8
		Author: Wordfence

	WP Property Feed
		Version: 1.232
		Author: Ultimateweb Ltd

	WP Statistics
		Version: 13.1.6
		Author: VeronaLabs

	Yoast SEO
		Version: 18.2
		Author: Team Yoast


== Elementor Experiments ==
	Optimised DOM Output: Inactive by default
	Improved asset loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 402022-02-01 17:14:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-09 22:16:56 [info] elementor-pro::elementor_pro_updater Started 
2022-02-09 22:16:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-09 22:16:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-09 22:16:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-02-09 22:16:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-02-15 10:32:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-15 10:32:34 [info] elementor-pro::elementor_pro_updater Started 
2022-02-15 10:32:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-15 10:32:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-15 10:32:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-03-01 13:21:23 [info] elementor-pro::elementor_pro_updater Started 
2022-03-01 13:21:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-01 13:21:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-01 13:21:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-01 13:21:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-02 13:09:56 [info] elementor::elementor_updater Started 
2022-03-02 13:09:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-02 13:09:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-02 13:09:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.6',
)]

PHP: showing 3 of 3PHP: 2022-02-09 22:31:15 [error X 1][/home/customer/www/thenewhomesagent.co.uk/public_html/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php::13] Uncaught Error: Class 'ElementorPro\Base\Base_Widget' not found in /home/customer/www/thenewhomesagent.co.uk/public_html/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php:13
Stack trace:
#0 /home/customer/www/thenewhomesagent.co.uk/public_html/wp-content/plugins/elementor-pro/plugin.php(141): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#2 /home/customer/www/thenewhomesagent.co.uk/public_html/wp-content/plugins/elementor/core/base/module.php(325): spl_autoload_call('ElementorPro\\Mo...')
#3 /home/customer/www/thenewhomesagent.co.uk/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Base\Module->init_widgets(Object(Elementor\Widgets_Manager))
#4 /home/customer/www/thenewhomesagent.co.uk/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 /home/customer/www/thenewhomesagent.co.uk/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /home/customer/www/thenewhomesagent.co.uk/pub [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-10 12:55:31 [notice X 6][/home/customer/www/thenewhomesagent.co.uk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1515] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-01 15:00:14 [notice X 22][/home/customer/www/thenewhomesagent.co.uk/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::59] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	The New Homes Agent - Elementor Addons: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

```

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.

**Comment by rtpHarry** [comment]
I know this was closed as a support request, but can you clarify what the difference is between a bug report and a support request?

I'm still experiencing this with different sites, months later. 

I've seen it on multiple hosting providers, and on basic sites right up to powerful servers. Even with different caching systems.

I have just upgraded a client to a brand new, powerful server, and I'm still seeing the issue crop up.

Doing searches online I can find other threads with people discussing these external post-xx.css files being 404 but no solution.

**Comment by rami-elementor** [comment]
@rtpHarry 

A bug in Elementor is an issue that can be recreated on other sites. This is why we request "Steps to reproduce". We need to able to see the bug in our development environment, or in any other environment. Only then we can start fixing the bug for all Elementor users.

If this issue is not reproducible in other sites, it may be a server issue, a buggy plugin, some kind of wrong configuration, etc. In this case, it's a support issue. You need to fix something in your site/server.

**Comment by contremaitre** [comment]
Hello, 
I have the same issue and elementor support tell me it must come from my server caching, but I already checked this
@rtpHarry have you been able to figure this out

**Comment by rtpHarry** [comment]
No it still happens with various sites and its an ongoing problem. I have been experimenting with one site, trying to track this down. I've turned the cache combine and minification off and still the files have gone missing.

It is a real mystery. With other things like crocoblock jet menu, the cache is expiring way after the nonce has expired, breaking things, but with this one, the files are physically not in the folder any more, the folder is completely empty when it goes wrong. 

So the cache is still pointing at files that used to exist, but I don't know what is triggering the folder to be emptied out. 

Even if the cache was refreshed it seems that this still would have errors because there are zero files in the css folder, so the new cache doesn't seem like it would have anything to point at.

It feels like Elementor is trying to trigger the generation of new files and maybe overloading something on the server and failing to generate them. Or something else is tidying up folders. 

But I've seen this happen on completely different web hosts and caching systems, with different sets of plugins.

Its just a real mystery and the worst part about this system, because it totally erodes client trust in their site.

I haven't spoken with support as I dont have any kind of idea how to frame it in a way that they could feasibly diagnose it. The issue happens totally intermittently.

**Comment by rhud** [comment]
@rtpHarry @contremaitre I've had this happen a few times now - the latest was yesterday. 

Nothing I can see happening from a hosting POV. I do wonder if something happens when I hit the Elementor 'Regenerate CSS'.  

Can I ask what host you guys are using? I'm with Cloudways.

**Comment by rtpHarry** [comment]
I've seen it happen with Guru Reseller, Guru Reseller Pro, and on sites powered by SiteGround.

**Comment by garhbod** [comment]
Getting the same issue. "Regenerate CSS" doesn't help and can actually make things worse. I've found that the Regenerate CSS clears out the `uploads/elementor/css` folder successfully but doesn't regenerate the files.
I thought it was a SiteGround issue but have noticed it on other hosting.
