### ISSUE TITLE
✅ ⛔ 🚀 Feature Request: Container component suggestions

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#18055]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

I'm on these versions of Elementor to test the container component.

![image](https://user-images.githubusercontent.com/60075863/156472822-e5186cef-98b5-4945-a933-234e744aeee6.png)

The content tab doesn't look like the one in the article below, am I doing something wrong?

https://elementor.com/help/container-element/

The fact that the section below exists, is confusing and buggy.
100% on Boxed acts different than 100% on Full width. Padding, width, don't work properly on Boxed, and the CSS output is messy.

![image](https://user-images.githubusercontent.com/60075863/156472959-9cf81392-baa0-4c9e-9cb3-b72e9e53e972.png)

I hope you guys stick to this 

![image](https://user-images.githubusercontent.com/60075863/156473276-b5b507dd-41f1-46c2-a813-7b5d162aa1b2.png)

when you push it to production. There's no reason to have the dropdown for Boxed or Full width. 
Selecting Full width, the container behaves alright. 

In my opinion, you should stick to the code that's behind "Full width", while keeping the width and height just like this without the dropdown. This way it's not confusing and working properly.

![image](https://user-images.githubusercontent.com/60075863/156473650-649707f8-f501-494f-849f-8bb176aac70e.png)

Also, please make it so who doesn't want to use the container experiment can keep on going like before with the sections and inner sections even when new updates are being released, and have the container as an experiment to choose even when it's fully functional. This way, people can choose to start building with the containers from scratch, or rebuild the older websites with the containers when they feel like it, thus, avoiding the 3.0 issues.

Thank you.

### Steps to reproduce

Just add a component into the page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Showed the versions.

**Comment by nicholaszein** [comment]
Hello @azkalex,

Thank you for submitting a feature request! 🙏 

I'm organizing all things related to Container, and I stumbled upon this issue.

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Having the boxed option is important for a great majority of users. As for the other settings, your suggestions were actually taken into account, and the controls are now much more organized and streamlined. So thank you for that. 🙏 

I'm closing this issue as completed.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
