### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by tcampayo** [elementor/elementor#18059]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello Support,

Our production site is running on Wordpress 5.8.3, Elementor 3.4.8 and Elementor Pro 3.5.2

On our test environment, we have updated Wordpress and all the plugins to their latest version.

Problem, our plugin "penrose-plugin" which generates the https://tinyurl.com/987YTGQS reservation page of the site can no longer be activated at the same time as Elementor Pro, causing a "Fatal error" on the whole Wordpress.

If you deactivate Elementor Pro, the error disappears. It seems that Elementor Pro deactivates a large part of the "taxonomy" used by our site on this page generated by our "penrose-plugin" (view screenshots before / after activation Elementor Pro)

How to solve the problem?

PS: currently "penrose-plugin" is deactivated, you can activate it in the wordpress extensions to see the error message by yourself.

htpasswd :
Id : betabart
Password : demo;2022

![before-taxo](https://user-images.githubusercontent.com/100844267/156559262-f18e5c84-4a6f-44cd-8571-41ac22eaa307.png)
![after-taxo](https://user-images.githubusercontent.com/100844267/156559278-d210e58b-b368-457d-9888-39734b1c9c75.png)

### Steps to reproduce

Just enable/disable the Elementor Pro plugin to reproduce the bug.
The entire site is in error following.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rami-elementor** [comment]
Hi @tcampayo ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
