### ISSUE TITLE
🐞 Bug report: Custom width positioning is not responsive for tablet or mobile.

### ISSUE THREAD

**Issue by MatthewsDesign** [elementor/elementor#18054]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Custom width positioning is not responsive for tablet or mobile.

When I set an image widget at a custom width for 33.33% for desktop, and 50% for mobile, the mobile setting is not reflected on the live site - the image remains at 33% width.

I've noticed this issue for a few weeks, and as a workaround, I have to change the positioning from custom to full width, and then back to custom, and then specify the width.

![image](https://user-images.githubusercontent.com/98335164/156438465-2c29924a-ac4b-4f9a-a4a1-311636cecf0a.png)
![image](https://user-images.githubusercontent.com/98335164/156438282-9403fb3f-4ef2-4487-b459-feb981479345.png)
![image](https://user-images.githubusercontent.com/98335164/156438377-9d54ef51-9b30-45e9-a9b4-2ad54895dcb2.png)

### Steps to reproduce

Set an image widget at 50% width on desktop, and then 100% on mobile. You will find that it is still 50% on mobile.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1d
	MySQL version: Source distribution v10.3.32
	PHP Version: 7.4.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: http://18.233.110.145.nip.io
	Home URL: http://18.233.110.145.nip.io
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -8
	Admin Email: user@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

== Active Plugins ==
	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.1
		Author: Dudaster.com

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

== Network Plugins ==
	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	JetEngine
		Version: 2.11.3
		Author: Crocoblock

	Redirection
		Version: 5.2.3
		Author: John Godley

	WP Mail SMTP
		Version: 3.3.0
		Author: WPForms

	WP Rocket
		Version: 3.9.4.1
		Author: WP Media

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 18.1
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 3 of 3PHP: 2022-02-21 07:44:23 [notice X 11][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-21 12:05:44 [notice X 12][/bitnami/wordpress/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-26 08:59:26 [notice X 1][/bitnami/wordpress/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-02-21 17:33:05 [error X 2][http://18.233.110.145.nip.io/wp-content/plugins/elementor-pro/assets/js/gallery.87cf817e57c8522b3dec.bundle.min.js:2:5563] Cannot read properties of undefined (reading \'setSettings\') 
JS: 2022-02-21 18:43:59 [error X 9][http://18.233.110.145.nip.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-21 20:47:52 [error X 4][http://18.233.110.145.nip.io/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.6.2:1:741] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-03-01 16:06:15 [error X 1][http://18.233.110.145.nip.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view116\") has already been destroyed and cannot be used. 
JS: 2022-03-01 16:06:51 [error X 2][http://18.233.110.145.nip.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view113\") has already been destroyed and cannot be used. 
JS: 2022-03-02 15:51:21 [error X 1][http://18.233.110.145.nip.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view38129\") has already been destroyed and cannot be used. 
JS: 2022-03-02 18:55:25 [error X 1][http://18.233.110.145.nip.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4359\") has already been destroyed and cannot be used. 
JS: 2022-03-02 19:00:51 [error X 2][http://18.233.110.145.nip.io/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view131\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	

== Elementor Pro - Compatibility Tag ==

**Comment by puregraphx** [comment]
I have reported this exact issue to E support on March 2 and this is their response.

_It looks like we already have reported this issue to our developers. This should be reviewed by one of them and addressed in one of the future plugin updates.
What I can do is add your vote to the report to make its priority even higher.
I apologize for any confusion._

**Comment by puregraphx** [comment]
Temporary workaround https://www.loom.com/share/217db34b84174f4089db09779b35b80b

**Comment by shilo-ey** [comment]
Hey all,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!
