### ISSUE TITLE
🚀 Feature Request: A <br> should not be removed.

### ISSUE THREAD

**Issue by bhs67** [elementor/elementor#18053]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

------------------------------------
I entered a <   br   > in this request.  It is not appearing in my request.
------------------------------------

Elementor --- Edit with Elementor > Text Editor > Paragraph > Text {tab} > enter text that includes <br> in multiple places.  
.
Later, the <br> has been removed.  I must re-enter the <br> in all of the places they were before.

### Describe the solution you'd like

It would be good to not remove <br>.

**Comment by rami-elementor** [comment]
Hi @bhs67 ,

Unfortunately we can't fix this. Elementor Text Editor Widget uses the WordPress TinyMCE library for rich editing. We simply inherit the functionality. This should be fixed by fixed WordPress or by TinyMCE.

**Comment by bhs67** [comment]
I'm surprised by the statement, "can't fix this", especially since I have written code for many years.  There is nothing that I could not fix.

Perhaps, someone, in the future, can fix this.  Thanks for the response!

**Comment by rami-elementor** [comment]
Hi @bhs67,

We see many requests from our 11M users. We try to focus only on Elementor. I'm sorry, but we don't have the capacity to fix external libraries.

Our roadmap has many interesting features like Containers and the Loop Builder. Fixing TinyMCE is currently out of scope. Sorry.

**Comment by bhs67** [comment]
What is the link to WordPress and TinyMCE code writers?  They may know a solution.  Thanks!

**Comment by rami-elementor** [comment]
> What is the link to WordPress and TinyMCE code writers? They may know a solution. Thanks!

https://core.trac.wordpress.org/

**Comment by bhs67** [comment]
The support agent at TinyMCE, says it is Elementor's problem.   TinyMCE is unwilling to help.
