### ISSUE TITLE
🚀 Gravity Forms Widget - new widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18050]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Gravity Forms plugin is one of the biggest WordPress plugins. It would be great if elementor were fully compatible with it. So that we can edit forms created with Gravity Forms with elementor. This feature requires a new widget. Now some elementor add-ons like PowerPack and Ultimate Addons add this widget to elementor. But it would be great if you localized this widget in elementor.

### Describe the solution you'd like

Styling and managing forms made with Gravity Forms in elementor

**Comment by rami-elementor** [comment]
@Michaelgimii 

At this time, we are not going to create widgets for Gravity Forms as we have Forms widget in Elementor Pro.
