### ISSUE TITLE
🐞 Bug report: Black bar interfering with menu, no settings change this

### ISSUE THREAD

**Issue by jodiyeh** [elementor/elementor#18075]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is a transparent sticky header that scrolls throughout the page. For some reason, whenever scrolled completely to the top, it turns black though there are no black colors on our theme. We've tried changing all the colors and nothing. It occurred after we added a few pages.

### Steps to reproduce

I have no idea, it just happened.

all the way at the top

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62637534/156873111-19d97ec5-fbf8-4f20-978f-701b349a3e80.png">

scrolled down a little
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62637534/156873095-0beedc58-6d6b-46b9-97e8-19766f80380b.png">

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://duuwxdu.wpcomstaging.com
	Home URL: https://duuwxdu.wpcomstaging.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: duudevops@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Fmwave Child
	Version: 2.3.1646415422
	Author: RadiusTheme
	Child Theme: Yes
	Parent Theme Name: Fmwave
	Parent Theme Version: 2.3
	Parent Theme Author: RadiusTheme

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	AMP
		Version: 2.2.1
		Author: AMP Project Contributors

	Breadcrumb NavXT
		Version: 7.0.2
		Author: John Havlik

	Child Theme Configurator
		Version: 2.5.8
		Author: Lilaea Media

	Crowdsignal Forms
		Version: 1.5.15
		Author: Automattic

	Crowdsignal Polls & Ratings
		Version: 3.0.7
		Author: Automattic, Inc.

	Elementor
		Version: 3.6.0-dev45
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Fluent Forms
		Version: 4.3.3
		Author: Contact Form - WPManageNinja LLC

	Fmwave-Core
		Version: 2.3
		Author: RadiusTheme

	Gutenberg
		Version: 12.7.0
		Author: Gutenberg Team

	Jetpack
		Version: 10.8-a.1
		Author: Automattic

	Layout Grid
		Version: 1.8
		Author: Automattic

	Page Optimize
		Version: 0.5.2
		Author: Automattic

	Radio Station
		Version: 2.4.0.5
		Author: Tony Zeoli, Tony Hayes

	RT Demo Importer
		Version: 4.3
		Author: RadiusTheme

	RT Framework
		Version: 2.4
		Author: RadiusTheme

	Sugar Calendar (Lite)
		Version: 2.2.4
		Author: Sandhills Development, LLC

	Template Kit Import
		Version: 1.0.14
		Author: Envato

	WooCommerce
		Version: 6.2.1
		Author: Automattic

	WordPress.com Editing Toolkit
		Version: 3.28276
		Author: Automattic

	WP Radio PRO
		Version: 3.1.3
		Author: WP Military

	YITH WooCommerce Compare
		Version: 2.11.0
		Author: YITH

	YITH WooCommerce Quick View
		Version: 1.13.0
		Author: YITH

	YITH WooCommerce Wishlist
		Version: 3.6.0
		Author: YITH

== Must-Use Plugins ==
	WP.com Site Helper
		Version: 
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 6 of 6PHP: 2021-01-07 11:08:13 [notice X 391][/home/customer/www/demo.radiustheme.com/public_html/wordpress/themes/fmwave\wp-content\plugins\elementor\includes\controls\groups\base.php::181] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-01-22 05:29:32 [notice X 4][/home/customer/www/demo.radiustheme.com/public_html/wordpress/themes/fmwave/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-09 03:26:07 [warning X 23][/home/customer/www/demo.radiustheme.com/public_html/wordpress/themes/fmwave\wp-content\plugins\elementor\includes\managers\controls.php::694] array_merge(): Argument #2 is not an array [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-27 09:59:17 [error X 2][/home/customer/www/demo.radiustheme.com/public_html/wordpress/themes/fmwave\wp-content\plugins\elementor\core\files\css\post.php::10] Maximum execution time of 120 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-04-30 10:47:21 [notice X 8][/home/customer/www/demo.radiustheme.com/public_html/wordpress/themes/fmwave/wp-content/plugins/elementor/includes/api.php::160] Undefined index: pro_widgets [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-05 02:16:37 [notice X 1][/srv/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2021-01-12 05:40:52 [error X 24][https://radiustheme.com/demo/wordpress/themes/fmwave/wp-content/themes/fmwave/assets/js/scrollMagic/ScrollMagic-function.js?ver=1.0:12:18] TweenMax is not defined 
JS: 2021-01-12 05:48:00 [error X 24][https://radiustheme.com/demo/wordpress/themes/fmwave/wp-content/themes/fmwave/assets/js/main.js?ver=1.0:96:39] $(...).nivoSlider is not a function 
JS: 2021-01-15 08:00:32 [error X 1406][https://radiustheme.com/demo/wordpress/themes/fmwave/wp-content/themes/fmwave/assets/js/slick.min.js?ver=1.0:1:19335] Cannot read property \'add\' of null 
JS: 2022-02-23 06:50:01 [error X 3][https://radiustheme.com/demo/wordpress/themes/fmwave/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.5:2:21771] Cannot read properties of undefined (reading \'global\') 

Log: showing 8 of 82021-03-08 06:14:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.3',
)]
2021-03-11 03:41:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-04-26 05:58:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 05:58:46 [info] elementor::elementor_updater Started 
2021-04-26 05:58:46 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-26 05:58:47 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-26 05:58:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-26 05:58:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Please create GitHub issues only for bugs reports and feature requests. 

GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Thanks.
