### ISSUE TITLE
🐞 Bug report: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by gsg-mcmxcii** [elementor/elementor#18079]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

`Warning: Trying to access array offset on value of type null in /home/.sites/331/site1523/web/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1511`

`Warning: Trying to access array offset on value of type null in /home/.sites/331/site1523/web/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1513`

### Steps to reproduce

That is very difficult to say because it's only on one page on my website - this page has a split layout (on the left side is a picture and on the right side a text).
This is the only difference between the page with this error and the other.

The issue on this page is since the update to PHP 8.1.
I'm on the latest version of Elementor and WordPress with "fotofly" Theme.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 8.1.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://www.bildhauer-leitner.at
	Home URL: https://www.bildhauer-leitner.at
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Admin Email: aon@gasg.at
	Debug Mode: Inactive

== Theme ==
	Name: Fotofly
	Version: 3.0
	Author: Frenify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.5.6
		Author: Takayuki Miyoshi

	Disable REST API
		Version: 1.7
		Author: Dave McHale

	Disable XML-RPC Pingback
		Version: 1.2.2
		Author: Samuel Aguilera

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Fotofly Core
		Version: 2.4
		Author: frenify

	Maintenance
		Version: 4.05
		Author: WebFactory Ltd

	Redux Vendor Support
		Version: 1.0.1
		Author: Team Redux

	WP Meta SEO
		Version: 4.4.5
		Author: JoomUnited

	WPvivid Backup MainWP
		Version: 0.9.22
		Author: WPvivid Team

== Elementor Experiments ==
	Optimierte DOM Ausgabe: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @gsg-mcmxcii ,

We need the steps to reproduce to isolate the problem.

Without this information we can't recreate the issue.
