### ISSUE TITLE
Informe de errores

### ISSUE THREAD

**Issue by AGROCHEM2022** [elementor/elementor#18081]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

No actualiza los precios de los productos.

### Steps to reproduce

No actualiza los precios de los productos.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

No actualiza los precios de los productos.
![image](https://user-images.githubusercontent.com/101072525/156948107-7d4d1207-6f99-49be-887a-be65fe2d5715.png)
![image](https://user-images.githubusercontent.com/101072525/156948117-aa2f9dac-4d9e-4501-87e0-e1bf25df7d2d.png)

**Comment by rami-elementor** [comment]
@AGROCHEM2022 

Please write in English we need to understand the issue.
