### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by misslaidlaw** [elementor/elementor#18083]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

When I right click on Container  I am unable to add this to "Favourites" currently 

### Steps to reproduce

1. Click on container in the left hand bar
2. Click on add to favourites 
3. NOTHING!

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.46 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 PHP/7.4.21 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.13
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 7.4.21
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: http://localhost:8888/testing
	Home URL: http://localhost:8888/testing
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: dianelaidlaw@outlook.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.0-dev45
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev30
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Active
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 10 of 102022-03-07 08:38:31 [info] elementor::elementor_updater Started 
2022-03-07 08:38:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-07 08:38:31 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-07 08:38:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0-dev45',
)]
2022-03-07 08:38:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0-dev45',
)]
2022-03-07 09:04:35 [info] elementor-pro::elementor_pro_updater Started 
2022-03-07 09:04:35 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-07 09:04:35 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-07 09:04:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.7.0-dev30',
)]
2022-03-07 09:04:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.7.0-dev30',
)]

PHP: showing 1 of 1PHP: 2022-03-07 08:39:42 [notice X 1][/Users/dianelaidlaw/Sites/localhost/testing/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
Hey @misslaidlaw  thanks for reporting!

We improved the container and are going to release it soon to an alpha stage experiment in all versions. this issue will be fixed soon as well

If you encounter any other issue please create a new issue for us to inspect and fix it.

Thanks!
