### ISSUE TITLE
🚀 Add widget, without drag and drop - just With one click. (new User performance)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18097]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Great if you add this feature. Using this feature, we can add it with just one click on the desired widget.

**But how to add the desired widget in the desired location with one click?**

Just select a section, or widget, then click on the desired widget. So the widget is added below the section or widget we selected.

This feature greatly enhances user performance. Of course, this feature can be completely optional. Add the widget by **Drag & Drop** method, or **one click**.

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
Hi @XXX,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,
