### ISSUE TITLE
🚀 Custom tabs for elementor my account page.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18113]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi

Now, on my account page we are limited to a few tabs. So we can not add more tabs. For example, on multi-vendor websites we need vendor tabs and the products they upload.
Or, for example, I want to put a new tab in my account to show the interests of users or also the products they have recently visited.
Another example could be the users' ticket submission tab. Therefore, the ability to add a custom tab is extremely important.
**Another thing that is very important for my account page is the ability to insert custom icons for different tabs.**

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
Hi @XXX,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by 79ho3ein** [comment]
@rami-elementor
This was not a support request! It was a suggestion for a new feature. I think you did not understand what I meant.
