### ISSUE TITLE
🐞 Bug report: elementor won't load

### ISSUE THREAD

**Issue by UrbanWell2022** [elementor/elementor#18118]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When we go to edit elementor in wordpress the page doesn't load and comes up with 'enable safe mode'. Even when we do this, it still doesn't load. We have tried updating elementor plug ins. 
![image](https://user-images.githubusercontent.com/101244438/157570834-3a95a686-74ba-4a8a-b6a5-cd7fc4e9b25c.png)

### Steps to reproduce

Wordpress --> pages --> edit --> elementor not loading.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not sure how to do this?

**Comment by shilo-ey** [comment]
Hi @UrbanWell2022 
Thank you for contacting us.

You seem to have a JS/PHP/Plugin conflict somewhere in your install.

To isolate this conflict, please try:

- Deactivating all your plugins aside from Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you identify the problematic plugin.
- Changing your WordPress theme to the [Hello Theme](https://wordpress.org/themes/hello-elementor/) or a different default WordPress theme.

If the problem persists, try:
- Checking the memory limit of your site
- Checking the PHP version of your site. This is done by going to Elementor > System Info. 

Please note that GitHub issues are reserved for bug reports and feature requests, and are not used for support.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.for details.

Regards
