### ISSUE TITLE
⛔ Adding locally uploaded individual SVG icons massively bloats the DOM and significantly hurts pagespeed, even though SVGs are smaller than webfonts

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#18117]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using SVG files massively increases DOM size and has a very negative effect on pagespeed. The whole reason you would use individual SVGs over icon fonts is to reduce page weight and file size, which _should_ have a positive impact on performance. Instead, using the custom SVG feature negatively affects performance. This basically makes using custom icon SVGs impossible to use without just nuking your pagespeed.

### Steps to reproduce

1. Speed test the site to see what your current DOM size is for a specific page

2. Add an icon list widget

3. Upload custom svgs(in my case social icons for facebook, twitter, and instagram)

4. Recheck pagespeed insights, the DOM size should have exploded.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

[### System Info
(https://pastebin.com/UKUpibGF)

**Comment by jazir5** [comment]
@avivu @shilo-ey

**Comment by shilo-ey** [comment]
Hi @jazir5, thanks for contacting us.

When inserting SVG files it depends on whether they are optimized or not. you can try using SVG cleanup and optimization tools such as https://jakearchibald.github.io/svgomg/ to improve your SVG markup (it basically implements this SVG in your site)

Alternatively, you can create a custom icon pack and activate the Inline Font icons experiment that will add your icon as an inline SVG (with less markup printed)

Thanks
