### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by rayedgar** [elementor/elementor#18121]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am seeing elementor css code on the terms and conditions (checkout in Woocommerce) in the editor and frontend.

===
/*! elementor – v3.5.6 – 28-02-2022 */
.elementor-heading-title{padding:0;margin:0;line-height:1}.elementor-widget-heading .elementor-heading-title[class*=elementor-size-]>a{color:inherit;font-size:inherit;line-height:inherit}.elementor-widget-heading .elementor-heading-title.elementor-size-small{font-size:15px}.elementor-widget-heading .elementor-heading-title.elementor-size-medium{font-size:19px}.elementor-widget-heading .elementor-heading-title.elementor-size-large{font-size:29px}.elementor-widget-heading .elementor-heading-title.elementor-size-xl{font-size:39px}.elementor-widget-heading .elementor-heading-title.elementor-size-xxl{font-size:59px}
===
tried: Disabling all plugins, roll back, regenerate css, remove experiments, assigned different terms conditions page. removed all personal css and snippets.

<img width="589" alt="Screenshot 2022-03-10 at 08 47 58" src="https://user-images.githubusercontent.com/6242489/157617527-4f686f21-7e70-4540-a32b-0b10d46494a3.png">

### Steps to reproduce

put item in cart go to checkout. click on terms and conditions. 
https://www.hetamsterdamskleibedrijf.nl/betalen4/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.28
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://www.hetamsterdamskleibedrijf.nl
	Home URL: https://www.hetamsterdamskleibedrijf.nl
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 1
	Admin Email: akb@rayedgar.com
	Debug Mode: Inactive

== Theme ==
	Name: hello-elementor child theme
	Version: 1.0
	Author: Ray Edgar
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL_formal
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.8.3
		Author: Activity Log Team

	Advanced Order Export For WooCommerce
		Version: 3.2.2
		Author: AlgolPlus

	Autocomplete WooCommerce Orders
		Version: 1.5.0
		Author: QuadLayers

	Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro
		Version: 2.6.1
		Author: codewoogeek

	Booking Activities
		Version: 1.13.0
		Author: Booking Activities Team

	Checkout Field Editor for WooCommerce
		Version: 1.5.3
		Author: ThemeHigh

	Checkout Styling for WooCommerce and Elementor
		Version: 1.0.0
		Author: Skynet Solutions Inc.

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.3
		Author: Elementor.com

	Flexible Invoices for WooCommerce and WordPress
		Version: 5.6.4
		Author: WP Desk

	Kadence WooCommerce Email Designer
		Version: 1.4.10
		Author: Kadence WP

	Loco Translate
		Version: 2.6.0
		Author: Tim Whitlock

	Mollie Payments for WooCommerce
		Version: 7.0.2
		Author: Mollie

	My Downloads Shortcode for WooCommerce
		Version: 1.8.0
		Author: Pramadillo

	Password Protect WordPress Lite
		Version: 1.8.1
		Author: BWPS

	Product Customer List for WooCommerce
		Version: 2.9.3
		Author: Kokomo

	PublishPress Capabilities
		Version: 2.3.4
		Author: PublishPress

	SiteGround Optimizer
		Version: 7.0.6
		Author: SiteGround

	Volunteer Sign Up Sheets
		Version: 3.7.1
		Author: Stephen Sherrard

	WooCommerce
		Version: 6.3.0
		Author: Automattic

	WooCommerce Menu Cart
		Version: 2.10.4
		Author: WP Overnight

	WP Mail SMTP
		Version: 3.3.0
		Author: WPForms

== Must-Use Plugins ==
	sku.php
		Version: 
		Author: 

== Elementor Experiments ==
	Geoptimaliseerde DOM-uitvoer: Inactief
	Verbeterd laden van assets: Inactief
	Verbeterd laden van CSS: Inactief
	Inline Font Icons: Inactief
	Toegang verbeteringen: Inactief
	Import export template kit: Inactief
	Extra aangepaste onderbrekingspunten: Inactief
	Hide native WordPress widgets from search results: Inactief
	Default to New Theme Builder: Inactief
	Hello Theme Header & Footer: Inactief
	Landingspagina&#039;s: Inactief
	Kleur sampler: Inactief
	Favorite Widgets: Inactief
	Beheerder bovenste balk: Inactief
	Page Transitions: Inactief
	Form Submissions: Inactief
	Scroll Snap: Inactief

== Log ==
	
Log: showing 20 of 312022-02-12 15:36:42 [info] elementor-pro::elementor_pro_updater Started 
2022-02-12 15:36:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-12 15:36:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-12 15:36:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.1',
)]
2022-02-12 15:36:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.1',
)]
2022-02-19 15:46:46 [info] elementor-pro::elementor_pro_updater Started 
2022-02-19 15:46:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-19 15:46:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-19 15:46:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-19 15:46:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-03-07 08:37:57 [info] elementor::elementor_updater Started 
2022-03-07 08:37:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-07 08:37:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-07 08:37:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-07 08:37:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-07 09:23:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-07 09:23:33 [info] elementor-pro::elementor_pro_updater Started 
2022-03-07 09:23:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-07 09:23:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-07 09:23:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]

PHP: showing 3 of 3PHP: 2022-01-20 13:54:58 [notice X 3][/home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-04 18:02:07 [notice X 9][/home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-04 11:06:03 [error X 2][/home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/hetamsterdamskleibedrijf.nl/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_requ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2022-02-01 16:59:03 [error X 5][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:245894] Cannot read properties of undefined (reading \&#039;id\&#039;) 
JS: 2022-02-03 22:25:42 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view11679\&quot;) has already been destroyed and cannot be used. 
JS: 2022-02-04 17:07:08 [error X 6][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-02-04 17:30:38 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view56509\&quot;) has already been destroyed and cannot be used. 
JS: 2022-02-04 17:30:38 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view75658\&quot;) has already been destroyed and cannot be used. 
JS: 2022-02-04 17:30:39 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view76139\&quot;) has already been destroyed and cannot be used. 
JS: 2022-02-04 17:30:39 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view76149\&quot;) has already been destroyed and cannot be used. 
JS: 2022-02-04 17:30:39 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view76194\&quot;) has already been destroyed and cannot be used. 
JS: 2022-03-07 08:20:21 [error X 1][https://www.hetamsterdamskleibedrijf.nl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view21181\&quot;) has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Checkout Styling for WooCommerce and Elementor: Compatibiliteit niet gespecificeerd
	Ele Custom Skin: Compatibel
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Niet compatibel

**Comment by nextOver** [comment]
I have the same problem, did you manage to solve it?

**Comment by nextOver** [comment]
I have the same problem, did you manage to solve it?
