### ISSUE TITLE
🚀 Feature Request: Access static widget id for custom widget

### ISSUE THREAD

**Issue by MarloKessler** [elementor/elementor#18120]
### Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello there,

this is not really a feature request, but since I could not find any answer in the developer docs, I asked the Elementor Pro support team. They told me to post my question here.

I'm currently developing my own Elementor widget. Therefore, I programmatically need to access the static id of the widget programmatically in the `render()` function of my widget, to pass it to the frontend and store it there in a cookie, so I can compare it to the stored id on a new request. My idea was to take the same id which Elementor provides as selectors in controls (`{{ID}}`, e.g. in Dimension Controls) since it is static for every widget instance i provide on a site. 

Could you please tell me how I can access this or a better way to do this? 

I also tried a hidden control where an id is created via `uniqid()` but in my case the `_register_controls()` function is executed on every page load so if I create there an unique ID it is overwritten every reload.

Thanks and best regards
Marlo Kessler

![with the](https://user-images.githubusercontent.com/48910761/157618190-c74f8292-d965-41fa-be0f-2065db0a5498.jpg)
![Screenshot 2022-03-10 at 00 24 19](https://user-images.githubusercontent.com/48910761/157618179-14882f11-cf39-4f23-96dc-5b2a7d0aa92c.jpg)
![the id in the frontend](https://user-images.githubusercontent.com/48910761/157618197-de1d7172-b060-4b3f-abed-518aec382465.jpg)
![Connapptivity](https://user-images.githubusercontent.com/48910761/157618200-4b03efd2-5a4e-4431-ad29-bd0edff78743.jpg)

### Describe the solution you'd like

Getting a static non-changing id per widget instance.

### Describe alternatives you've considered

I also tried a hidden control where an id is created via `uniqid()` but in my case the `_register_controls()` function is executed on every page load so if I create there an unique ID it is overwritten every reload.

**Comment by udidol** [comment]
Each element's ID can be fetched anywhere in the widget class by calling `$this->get_id()`

**Comment by rami-elementor** [comment]
Also, you are using an old `_register_controls()` method that was deprecated. You should switch to `register_controls()`. Simple remove `_` prefix.

**Comment by MarloKessler** [comment]
Awesome, thank you a lot! Also for the hint that I use a deprecated method😃
