### ISSUE TITLE
Elementor saves 3 revisons in database

### ISSUE THREAD

**Issue by fleks** [elementor/elementor#18124]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating/saving a page/post, Elementor automaticly saves three identical revisions in the database:
![image](https://user-images.githubusercontent.com/2400024/157635894-48999a75-49d3-4976-b70d-74835dc41861.png)

This is a huge amount of unnecessary data and bloats the database.
Is there any rational reason for this behavior?

### Steps to reproduce

Saving a post/page and look at `wp_posts` table in the database.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '10', Revision 'f446c04' v8.0.19-10
	PHP Version: 8.0.0
	PHP Max Input Vars: 1500
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: http://wordpress.p612250.webspaceconfig.de
	Home URL: http://wordpress.p612250.webspaceconfig.de
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: p612250@wordpress.p612250.webspaceconfig.de
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.20 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.3
		Author: Elementor.com

== Elementor Experiments ==
	Optimierte DOM Ausgabe: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
== Elementor - Compatibility Tag ==
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
It's not a bug, those are WordPress revisions. You can deactivate the revisions.

**Comment by hoanglocth** [comment]
This is actually a bug that is caused by the wp_update_post() function being called duplicated 3 times in the process of the save() function in wp-content\plugins\elementor\core\base\document.php.
Below are 3 callback functions in the process of save() function:

![Image](https://github.com/user-attachments/assets/c5cf993e-a03a-45b8-9fb3-20d800d31af9)

![Image](https://github.com/user-attachments/assets/ce0cc1c7-2f95-4e1d-a650-7ffb275fec6e)

![Image](https://github.com/user-attachments/assets/dcb4defb-1e3d-44b2-892f-def99b6a0748)
