### ISSUE TITLE
✅ 🐞 Bug report: Theme Display Conditions not Workking

### ISSUE THREAD

**Issue by luizeof** [elementor/elementor#18132]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Theme Display Conditions not Workking

### Steps to reproduce

1. Create an Theme Header
2. When saving, the screen for choosing the conditions for the template to be displayed is empty

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

php 7;4
latest wordpress
helo theme

**Comment by huubl** [comment]
Same here

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
