### ISSUE TITLE
Thanks for reporting.

### ISSUE THREAD

**Issue by leonardramirezjr** [elementor/elementor#18138]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

_Originally posted by @shilo-ey in https://github.com/elementor/elementor/issues/16084#issuecomment-903219540_

**Comment by leonardramirezjr** [comment]
Originally reported in #16084, this issue was closed inadvertently. The problem still exists in Elementor v3.5.6 / Elementor Pro v3.6.3. Am still getting The server cannot process the image. Unable to upload SVG. Thils can happen if the server is busy or does not have enough resources to complete the task. Uploading a smaller image may help. Suggested maximum size is 2560 pixels.

SVG file is way smaller than this limit.  PHP 8.0 has maxed out memory of 512MB and it was tried in an incognito window. Problem still persists as it was reported originally in Issue 

https://github.com/elementor/elementor/issues/16084#issuecomment-903219540
![sqc-349](https://user-images.githubusercontent.com/99048774/157786032-1132ec8d-75b7-4500-8275-477cf23cdfda.svg)
![Media Library Fail - Unable to Upload SVG](https://user-images.githubusercontent.com/99048774/157786048-4705f1dd-c94b-42dd-b85e-70e17cc8558f.png)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
