### ISSUE TITLE
🐞 Bug report: I am getting strange ads popping up on my site - have I been hacked?

### ISSUE THREAD

**Issue by JamesW50** [elementor/elementor#18133]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

On my homepage pop up ads are appearing for a porn site 

### Steps to reproduce

the website homepage is www.jwp.tv

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.3
	Site URL: https://jwp.tv
	Home URL: https://jwp.tv
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: james@jwp.tv
	Debug Mode: Inactive

== Theme ==
	Name: Inspiro
	Version: 7.0.2
	Author: WPZOOM
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.12
		Author: Automattic

	Beaver Builder Plugin (Lite Version)
		Version: 2.4.2.5
		Author: The Beaver Builder Team

	Brizy
		Version: 2.3.17
		Author: Brizy.io

	BuddyPress
		Version: 10.1.0
		Author: The BuddyPress Community

	Category Order and Taxonomy Terms Order
		Version: 1.5.7.5
		Author: Nsp-Code

	Easy Theme and Plugin Upgrades
		Version: 2.0.0
		Author: Chris Jean

	Elementor
		Version: 3.5.3
		Author: Elementor.com

	Elementor Addons by WPZOOM
		Version: 1.1.10
		Author: WPZOOM

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Google Apps Login
		Version: 3.2
		Author: Lever Technologies

	Google Drive Embedder
		Version: 4.2
		Author: Dan Lester

	PDF Embedder
		Version: 3.1.8
		Author: Dan Lester

	Related Posts Slider
		Version: 2.2
		Author: SliderVilla

	ShareThis Dashboard for Google Analytics
		Version: 2.5.3
		Author: ShareThis

	Social Icons Widget & Block by WPZOOM
		Version: 4.0.5
		Author: WPZOOM

	Traffic Armor
		Version: 
		Author: 

	Twitter
		Version: 2.0.3
		Author: Twitter

	Unyson
		Version: 2.7.19
		Author: ThemeFuse

	Widget for Social Page Feeds
		Version: 6.1
		Author: Milap Patel

	WPForms Lite
		Version: 1.6.3.1
		Author: WPForms

	WPide
		Version: 2.4.0
		Author: Simon @ WPsites

	WPZOOM Instagram Widget
		Version: 1.7.3
		Author: WPZOOM

	WPZOOM Shortcodes
		Version: 1.0
		Author: WPZOOM

	Yoast SEO
		Version: 9.0.2
		Author: Team Yoast

== Must-Use Plugins ==
	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== Elements Usage ==
	

== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 1 of 1PHP: 2022-01-07 12:02:58 [notice X 6][/home1/jwptv/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::993] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Addons by WPZOOM: Compatibility not specified

**Comment by rtpHarry** [comment]
This issue will probably get closed soon by the moderators as it's not for support.

From what you have said it sounds like you have been hacked, yes.

I don't think anyone is going to want to click your link to investigate it as it might infect their computers.

In the past I have used WordFence to clean up this kind of mess:

https://www.wordfence.com/wordfence-site-cleanings/

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support purposes.**

If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


thanks.
