### ISSUE TITLE
🚀 After adding each widget to the page, the widget configuration panel opens ...

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18145]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi

As mentioned in the title, if we add a widget to the page, the configuration panel of that widget will open immediately. So, if I want to add several widgets in a row, adding the first widget opens its configuration panel, we have to close its panel, then go to the widgets section again and this operation will continue ...
But it can be much easier. So that after adding each widget, its configuration panel does not open so that we can add several widgets if necessary. After adding the widgets, we can now open the configuration panel of the desired widget.
**Of course, this option can be optionally available to users.** 

### Describe the solution you'd like

Do not open their configuration panel after adding any widget. **In other words, after adding each widget, the list of widgets is still open, so we can add the desired widgets without interruption.** After adding the desired widgets, we can open the configuration panel of the desired widget.

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to change the current behavior.

Please feel free to contact us again with other feature suggestions.

Regards,

**Comment by 79ho3ein** [comment]
thank you
