### ISSUE TITLE
✅ 🔀 🐞 Bug report: Star Rating Widget Display Issue (PR #18170) - [ED-7362]

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#18169]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When you input a rating value that has two decimal places it rounds it up, while if you use one decimal place it works as intended and doesn't round up. I noticed this when I did a customers website and did an average rating of 4.65 and it rounded to 5 in star value.

### Steps to reproduce

Add star rating widget to a page. Add a value like '4.65' to the rating field then click the 'Style' tab and you will see it round up.

Video: 

https://user-images.githubusercontent.com/55829113/158565368-1b60b16e-79b5-4604-a957-4bc83b6535ca.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello, @perks98!

Thank you so much for your patience! 🙏 

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved with the release of the new Rating widget in Elementor v3.17! 🥳 

With this new widget, you have more options to choose the number of rating points, custom icons, and styling options, and it is fully compatible with Google Rich snippets (updated) and fully accessible. This also solves the issue with the decimal points raised here.

Your current Start Rating widgets will remain as they were before this update. But moving forward, only the new Rating widget will be available to add to your layouts.

If you are using the old Star Rating widget, we would recommend that you replace it with the new Rating widget.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
