### ISSUE TITLE
🚀 Feature Request: Custom measures

### ISSUE THREAD

**Issue by Fadirko** [elementor/elementor#18185]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The given measurement (e.g. px, vw, vh, ...) are good, but not sufficient. Very often I get into the situation that the unit I need is not given. So I can't use the setting, instead I have to use CSS. Unfortunately I'm not fit in CSS either, so I don't know which code I need for my needed setting. I can imagine that more than a few are in this situation. Defaults are, after all, limited.

### Describe the solution you'd like

It would be a really very good feature if you had the possibility to enter your own unit as text. The defaults should remain, of course. An extra field for input would be the most optimal here.

Greetings from Germany!

**Comment by rami-elementor** [comment]
Hi @Fadirko ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. Each control has it's own units. We try to add specific units when users ask for them and we see a high demand. But creating a new mechanism for custom units is out of scope for our planned roadmap.

Please feel free to contact us again with other feature suggestions.

Regards,
