### ISSUE TITLE
🐞 Bug report: Applying values from other controls in responsive control selectors argument not working in tablet mode

### ISSUE THREAD

**Issue by SEwebm** [elementor/elementor#18182]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, first off I want to say you have a great Dev API when it comes to custom widget development. Unfortunately I might have found a bug.
With the following dummy widget I want to set the css position properties horizontally for the different screen sizes. 

Breakpoints:<br>
- Tablet (max-width: 1279px)
- Mobile (max-width: 767px)

I created two responsive Controls:<br>
1. controlling the css vertical position property (top or bottom)
2. controlling value and unit

I expected the different values to be applied correctly in all 3 Screen Modes. If I set a value for the mobile control, the mobile control is applied in tablet mode as well.<br> 
I tested this in Elementor 3.4 - 3.5.6 and Elementor Pro, WP 5.8 - 5.9.2, PHP 7.3 - 8.0.6 and the issue still stands.

I made a short video displaying the issue (Please Note that Desktop Mode is not working in this case because of the recorded browser window size which is in Tablet Mode, Desktop is working fine)

https://user-images.githubusercontent.com/94447668/158984320-9c95bfd5-2963-4456-9dab-94ebc402b71b.mov

I checked the CSS through web inspection and could see that the wrong value (mobile) is applied in tablet mode (correct media query)

![Screenshot](https://user-images.githubusercontent.com/94447668/158984938-7346237c-e05d-4982-a229-34e13720dc8f.png)

### Steps to reproduce

1. Create Test Widget with the two responsive controls I provided where one is controlling the css property and the other the value.
2. Set different values in Desktop Mode, then Tablet Mode, then Mobile, then check Tablet again.
3. You will see that the Mobile value is applied in Tablet Mode and changing the Tablet Mode value has no effect.

### Dom Structure

``` 
  <div class="test-wrapper">
	  <div class="test-div"></div>
  </div>
```

### Controls Methods

  	$this->start_controls_section(
			'section',
			[
				'label' => __( 'Settings', 'test-plugin' ),
				'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
			]
		);
		
		$this->add_responsive_control(
			'position_vertical_prop',
			[
				'type' => \Elementor\Controls_Manager::CHOOSE,
				'label' => __( 'Position Vertical Property', 'test-plugin' ),
				'devices' => [ 'desktop', 'tablet', 'mobile' ],
				'desktop_default' => 'bottom',
				'tablet_default' => 'bottom',
				'mobile_default' => 'bottom',
				'options' => [
					'top' => [
						'title' => __( 'Top', 'ks-plugin' ),
						'icon' => 'eicon-v-align-top',
					],
					'bottom' => [
						'title' => __( 'Bottom', 'ks-plugin' ),
						'icon' => 'eicon-v-align-bottom',
					],
				],
				'selectors' => [
					'(desktop){{WRAPPER}} .test-div' => 'top: unset; bottom: unset; {{VALUE}}: {{position_vertical.SIZE}}{{position_vertical.UNIT}}',
					'(tablet){{WRAPPER}} .test-div' => 'top: unset; bottom: unset; {{VALUE}}: {{position_vertical_tablet.SIZE}}{{position_vertical_tablet.UNIT}}',
					'(mobile){{WRAPPER}} .test-div' => 'top: unset; bottom: unset; {{VALUE}}: {{position_vertical_mobile.SIZE}}{{position_vertical_mobile.UNIT}}',
				],
				'toggle' => false,
				'frontend_available' => true,
			]
		);
		
		$this->add_responsive_control(
			'position_vertical',
			[
				'label' => __( 'Position Vertical Value', 'test-plugin' ),
				'type' => \Elementor\Controls_Manager::SLIDER,
				'devices' => [ 'desktop', 'tablet', 'mobile' ],
				'size_units' => [ 'px', '%', 'em', 'rem' ],
				'range' => [
					'px' => [
						'min' => -1000,
						'max' => 1000,
						'step' => 1,
					],
					'%' => [
						'min' => -50,
						'max' => 100,
						'step' => 0.5,
					],
					'em' => [
						'min' => -25,
						'max' => 100,
						'step' => 0.5,
					],
					'rem' => [
						'min' => -25,
						'max' => 100,
						'step' => 0.5,
					],
				],
				'selectors' => [
					'(desktop){{WRAPPER}} .test-div' => 'top: unset; bottom: unset; {{position_vertical_prop.VALUE}}: {{SIZE}}{{UNIT}}',
					'(tablet){{WRAPPER}} .test-div' => 'top: unset; bottom: unset; {{position_vertical_prop_tablet.VALUE}}: {{SIZE}}{{UNIT}}',
					'(mobile){{WRAPPER}} .test-div' => 'top: unset; bottom: unset; {{position_vertical_prop_mobile.VALUE}}: {{SIZE}}{{UNIT}}',
				],
				'frontend_available' => true,
			]
		);

		$this->end_controls_section();

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1m PHP/8.0.15 mod_perl/2.0.11 Perl/v5.32.1
	MySQL version: Source distribution v10.4.21
	PHP Version: 8.0.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 7: Failed to connect to my.elementor.com port 443: Bad file descriptor)

== WordPress Environment ==
	Version: 5.8.3
	Site URL: http://localhost/wordpress
	Home URL: http://localhost/wordpress
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 1000M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: example@example.org
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Test Plugin
		Version: 1.0.0
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 9 of 9PHP: 2022-02-16 14:33:05 [warning X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::162] Undefined array key &quot;url&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-19 17:20:07 [warning X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Undefined array key &quot;value&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-10 10:36:49 [error X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::363] Uncaught ArgumentCountError: Too few arguments to function Elementor\Controls_Stack::add_control(), 0 passed in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/ks-elementor-plugin/widgets/class-ks-media-carousel.php on line 816 and at least 2 expected in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php:363
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/ks-elementor-plugin/widgets/class-ks-media-carousel.php(816): Elementor\Controls_Stack-&gt;add_control()
#1 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2217): KSPlugin\Widgets\KSMediaCarousel-&gt;_register_controls()
#2 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(480): Elementor\Controls_Stack-&gt;init_controls()
#3 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(172): Elementor\Controls_Stack-&gt;get_stack()
#4 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(286): Elementor\Widget_Base-&gt;get_stack()
#5 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2306): Elementor\Controls_Stack-&gt;get_controls()
#6 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1062): Elementor\Controls_Stack-&gt;sanitize_settings(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2053): Elementor\Controls_Stack-&gt;get_data(&#039;settings&#039;)
#8 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack-&gt;get_init_settings()
#9 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object-&gt;ensure_settings()
#10 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(895): Elementor\Core\Base\Base_Object-&gt;get_settings(&#039;_skin&#039;)
#11 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(909): Elementor\Widget_Base-&gt;get_current_skin_id()
#12 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(576): Elementor\Widget_Base-&gt;get_current_skin()
#13 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/document.php(271): Elementor\Widget_Base-&gt;render_content()
#14 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/widgets.php(323): Elementor\Core\Base\Document-&gt;render_element(Array)
#15 [internal function]: Elementor\Widgets_Manager-&gt;ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#16 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#17 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#18 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-admin/admin-ajax.php(187): do_action(&#039;wp_ajax_element...&#039;)
#21 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-10 13:01:14 [warning X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;media_integration&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-10 13:02:06 [warning X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/conditions.php:87) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-10 13:02:09 [warning X 2][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;item_background_position&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-17 10:35:23 [error X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::1254] Uncaught TypeError: array_merge(): Argument #2 must be of type array, string given in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php:1254
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1254): array_merge(Array, &#039;active&#039;)
#1 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1113): Elementor\Controls_Stack-&gt;parse_dynamic_settings(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1198): Elementor\Controls_Stack-&gt;get_parsed_dynamic_settings()
#3 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/ks-elementor-plugin/widgets/class-ks-media-carousel.php(3637): Elementor\Controls_Stack-&gt;get_settings_for_display()
#4 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2188): KSPlugin\Widgets\KSMediaCarousel-&gt;render()
#5 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack-&gt;render_by_mode()
#6 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/document.php(282): Elementor\Widget_Base-&gt;render_content()
#7 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/widgets.php(390): Elementor\Core\Base\Document-&gt;render_element(Array)
#8 [internal function]: Elementor\Widgets_Manager-&gt;ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#9 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#10 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#11 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#13 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-admin/admin-ajax.php(187): do_action(&#039;wp_ajax_element...&#039;)
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-17 10:35:25 [error X 3][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::1254] Uncaught TypeError: array_merge(): Argument #2 must be of type array, string given in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php:1254
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1254): array_merge(Array, &#039;active&#039;)
#1 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1113): Elementor\Controls_Stack-&gt;parse_dynamic_settings(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1198): Elementor\Controls_Stack-&gt;get_parsed_dynamic_settings()
#3 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/ks-elementor-plugin/widgets/class-ks-media-carousel.php(3637): Elementor\Controls_Stack-&gt;get_settings_for_display()
#4 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2188): KSPlugin\Widgets\KSMediaCarousel-&gt;render()
#5 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack-&gt;render_by_mode()
#6 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base-&gt;render_content()
#7 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base-&gt;get_raw_data(true)
#8 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Element_Base-&gt;get_raw_data(true)
#9 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/document.php(876): Elementor\Element_Base-&gt;get_raw_data(true)
#10 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/document.php(553): Elementor\Core\Base\Document-&gt;get_elements_raw_data(Array, true)
#11 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1007): Elementor\Core\Base\Document-&gt;get_initial_config()
#12 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/editor/editor.php(522): Elementor\Controls_Stack-&gt;get_config()
#13 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor-&gt;enqueue_scripts(&#039;&#039;)
#14 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#15 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#16 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/script-loader.php(2083): do_action(&#039;wp_enqueue_scri...&#039;)
#17 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts(&#039;&#039;)
#18 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/general-template.php(3015): do_action(&#039;wp_head&#039;)
#21 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#22 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/editor/editor.php(317): include(&#039;/Applications/X...&#039;)
#23 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/editor/editor.php(158): Elementor\Core\Editor\Editor-&gt;print_editor_template()
#24 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor-&gt;init(&#039;&#039;)
#25 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#26 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#27 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-admin/admin.php(408): do_action(&#039;admin_action_el...&#039;)
#28 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-admin/post.php(12): require_once(&#039;/Applications/X...&#039;)
#29 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-17 16:37:22 [error X 1][/Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php::777] Uncaught TypeError: array_merge(): Argument #2 must be of type array, string given in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php:777
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(777): array_merge(Array, &#039;bottom&#039;)
#1 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(419): Elementor\Controls_Manager-&gt;add_control_to_stack(Object(TestPlugin\Widgets\TestWidget), &#039;position_vertic...&#039;, Array, Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(928): Elementor\Controls_Stack-&gt;add_control(&#039;position_vertic...&#039;, Array, Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/test-widget/widgets/class-test-widget.php(136): Elementor\Controls_Stack-&gt;add_responsive_control(&#039;position_vertic...&#039;, Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2247): TestPlugin\Widgets\TestWidget-&gt;_register_controls()
#5 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack-&gt;init_controls()
#6 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(175): Elementor\Controls_Stack-&gt;get_stack()
#7 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base-&gt;get_stack()
#8 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(2336): Elementor\Controls_Stack-&gt;get_controls()
#9 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1095): Elementor\Controls_Stack-&gt;sanitize_settings(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(529): Elementor\Controls_Stack-&gt;get_data()
#11 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php(724): Elementor\Element_Base-&gt;get_raw_data(true)
#12 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base-&gt;get_raw_data(true)
#13 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Element_Base-&gt;get_raw_data(true)
#14 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/document.php(876): Elementor\Element_Base-&gt;get_raw_data(true)
#15 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/base/document.php(553): Elementor\Core\Base\Document-&gt;get_elements_raw_data(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1007): Elementor\Core\Base\Document-&gt;get_initial_config()
#17 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/editor/editor.php(522): Elementor\Controls_Stack-&gt;get_config()
#18 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor-&gt;enqueue_scripts(&#039;&#039;)
#19 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#21 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/script-loader.php(2083): do_action(&#039;wp_enqueue_scri...&#039;)
#22 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts(&#039;&#039;)
#23 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#24 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#25 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/general-template.php(3015): do_action(&#039;wp_head&#039;)
#26 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#27 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/editor/editor.php(317): include(&#039;/Applications/X...&#039;)
#28 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/elementor/core/editor/editor.php(158): Elementor\Core\Editor\Editor-&gt;print_editor_template()
#29 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Editor\Editor-&gt;init(&#039;&#039;)
#30 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#31 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook-&gt;do_action(Array)
#32 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-admin/admin.php(408): do_action(&#039;admin_action_el...&#039;)
#33 /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-admin/post.php(12): require_once(&#039;/Applications/X...&#039;)
#34 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 9 of 92022-03-16 13:59:31 [info] elementor::elementor_updater Started 
2022-03-16 13:59:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-16 13:59:31 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-16 13:59:31 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2022-03-16 13:59:31 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2022-03-16 13:59:31 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-03-16 13:59:31 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-03-16 13:59:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.5',
  'to' => '3.5.6',
)]
2022-03-16 13:59:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.5',
  'to' => '3.5.6',
)]

JS: showing 2 of 2JS: 2022-03-16 14:21:09 [error X 1][http://localhost/wordpress/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.6:2:29844] elementor.settings.page is undefined 
JS: 2022-03-16 14:21:10 [error X 1][http://localhost/wordpress/wp-includes/js/wp-auth-check.min.js?ver=5.8.3:2:652] h is undefined 

== Elementor - Compatibility Tag ==

**Comment by SEwebm** [comment]
One thing to add, I got the idea from [here](https://letswp.io/selectors-elementor-control-css-values/)
If this currently is not impossible could you suggest a workaround or an alternative?
Thanks in advance!

**Comment by rami-elementor** [comment]
@SEwebm You are using wrong values in your `selectors` argument.

See the slider control docs: https://developers.elementor.com/docs/controls/classes/control-slider/

The `selectors` argument can accept the following:

```
'selectors' => [
	'{{WRAPPER}} .your-class' => 'width: {{SIZE}}{{UNIT}};',
],
```
