### ISSUE TITLE
🚀 Feature Request: Name items in the navigator

### ISSUE THREAD

**Issue by WebWeaver64** [elementor/elementor#18186]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

When you're building with the containers it would be extremely helpful if you could name them. I add all the items before adding content so I'm building my "blocks" within the containers for how I want the content to flow within full screen and mobile.

When you're adding a ton of "levels" it's easy to get confused about where you are.

If I could name them it would be easy to locate the block I need right from the navigator. Things get moved out or moved in and it's difficult to figure out where it should be, with the ability to name the container it would make it easier.

See below for what I'm thinking about.

[block 1]
 [block1.1]
  [image]
  [text]
 [block2.1]
  [image]
[block 2]
 [text]
[block 3]
 [block3.1]
  [image]
  [image]
  [image]
 [block3.2]
  [text]
 [block3.3]
  [image]
  [text]
  [image]

### Describe the solution you'd like

Possibly just show the class name instead of the word container? Or allow for editing.

**Comment by rtpHarry** [comment]
This is already possible. Just double click on the name in the navigator and it lets you type whatever you want.

**Comment by WebWeaver64** [comment]
Thank you! I swear I tried that, but... it's working so it's all good in my Elementor world now :)

**Comment by soumahmed** [comment]
@WebWeaver64 great to see it's working now. Can you close this issue now?
