### ISSUE TITLE
🐞 Bug Report: Cannot use Decimals in Margin and Padding (Duplicate of #18135)

### ISSUE THREAD

**Issue by soumahmed** [elementor/elementor#18188]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Cannot use decimal values in margin and padding boxes, in the advanced tab, when the values are linked together. So we can only use integers like 1, 2, 10, 20. But not 1.6, 2.5.

The workaround is to unlink the values then manually enter, for example, 2.5 in all the boxes. Why not let us do this when the values are linked together?

### Steps to reproduce

Go to advanced tab of any widget, or column, or section. Enter a decimal value like 1.6 while the values are linked together. You'll realize you can't. It won't let you.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: Ubuntu 20.04 v10.3.31
	PHP Version: 7.4.25
	PHP Max Input Vars: 1000
	PHP Max Post Size: 60M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://example.com
	Home URL: https://example.com
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: Mars
	Admin Email: soum@spacex.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Code Snippets
		Version: 2.14.3
		Author: Code Snippets Pro

	Easy Theme and Plugin Upgrades
		Version: 2.0.2
		Author: Chris Jean

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.3
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 5.0.10
		Author: WPDeveloper

	FluentCRM - Marketing Automation For WordPress
		Version: 2.5.8
		Author: Newsletter Team by Fluent CRM

	FluentCRM Pro
		Version: 2.5.7
		Author: Fluent CRM

	Fluent Forms
		Version: 4.3.3
		Author: Contact Form - WPManageNinja LLC

	Fluent Forms Pro Add On Pack
		Version: 4.3.2
		Author: Fluent Forms

	FluentSMTP
		Version: 2.1.1
		Author: FluentSMTP & WPManageNinja Team

	Flying Pages by WP Speed Matters
		Version: 2.4.2
		Author: Gijo Varghese

	HappyFiles Pro
		Version: 1.5.1
		Author: Codeer

	LiteSpeed Cache
		Version: 4.5.0.1
		Author: LiteSpeed Technologies

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 4.77
		Author: MalCare Security

	ManageWP - Worker
		Version: 4.9.13
		Author: GoDaddy

	OoohBoi Steroids for Elementor
		Version: 1.9.0
		Author: OoohBoi

	Perfmatters
		Version: 1.8.7
		Author: forgemedia

	Premium Addons for Elementor
		Version: 4.9.1
		Author: Leap13

	Premium Addons PRO
		Version: 2.7.4
		Author: Leap13

	Pretty Links Developer Edition
		Version: 3.2.4
		Author: Pretty Links

	Public Post Preview
		Version: 2.9.3
		Author: Dominik Schilling

	Rank Math SEO
		Version: 1.0.84
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.5
		Author: Rank Math

	The Plus Addons for Elementor
		Version: 5.0.7
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.9
		Author: POSIMYTH

	Ultimate Dashboard
		Version: 3.5.3
		Author: David Vongries

	Ultimate Dashboard PRO
		Version: 3.5.2
		Author: David Vongries

	Unlimited Elements for Elementor
		Version: 1.5.7
		Author: Unlimited Elements

	WordPress Geo Plugin
		Version: 7.13.20
		Author: INFINITUM FORM

	WP Activity Log
		Version: 4.4.0
		Author: WP White Security

	WP Social Ninja
		Version: 3.5.3
		Author: WPManageNinja LLC

	WP Social Ninja Pro
		Version: 3.5.2
		Author: WPManageNinja LLC

== Must-Use Plugins ==
	ET Support Center :: Must-Use Plugins Autoloader
		Version: 
		Author: Elegant Themes

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Page Transitions: Active by default
	Form Submissions: Inactive
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 352022-02-08 18:23:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-22 17:03:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.2',
)]
2022-02-22 17:03:52 [info] elementor-pro::elementor_pro_updater Started 
2022-02-22 17:03:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-22 17:03:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-22 17:03:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.2',
)]
2022-03-03 08:13:41 [info] elementor::elementor_updater Started 
2022-03-03 08:13:41 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-03 08:13:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-03 08:13:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-03 08:15:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-03 08:15:44 [info] elementor-pro::elementor_pro_updater Started 
2022-03-03 08:15:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-03 08:15:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-03 08:15:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-18 05:25:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-18 05:25:30 [info] elementor-pro::elementor_pro_updater Started 
2022-03-18 05:25:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-18 05:25:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-18 05:25:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

JS: showing 5 of 5JS: 2022-01-26 21:30:32 [error X 6][https://example.com/wp-content/plugins/premium-addons-for-elementor/assets/frontend/min-js/typed.min.js?ver=4.8.4:1:194] can\'t access property \"toLowerCase\", this.el.tagName is undefined 
JS: 2022-01-28 18:56:48 [error X 9][https://example.com/wp-content/plugins/ooohboi-steroids-for-elementor/assets/js/ooohboi-steroids-min.js?ver=1.9.016012022b:1:89] can\'t access property \"handlers\", elementorModules.frontend is undefined 
JS: 2022-01-28 18:56:48 [error X 10][https://example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.4:2:6362] can\'t access property \"tools\", elementorModules.frontend is undefined 
JS: 2022-02-06 08:14:12 [error X 1][https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:348732] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-02-06 08:14:12 [error X 1][https://example.com/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.16:12:0]  

PHP: showing 3 of 3PHP: 2022-02-22 17:03:52 [notice X 853][/home/example.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-23 17:15:27 [notice X 9][/home/example.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-23 18:20:10 [warning X 1][/home/example.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(label.png): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	OoohBoi Steroids for Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor - Pro: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @soumahmed!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #18135, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Please, in the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
