### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by sar1ca** [elementor/elementor#18180]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My page crashed and i can't edit my page. It won't open up with customize or show ”edit with elementor”. I have the latest version. It looks like a blog no
![Uploading Screenshot 2022-03-17 at 19.11.21.png…]()
w

### Steps to reproduce

I dont understand

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://zdraviobrok.hr
	Home URL: https://zdraviobrok.hr
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: Plain
	Language: hr
	Timezone: 0
	Admin Email: zdraviobrok.hr@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Sydney
	Version: 2.02
	Author: aThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: hr
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	aThemes Starter Sites
		Version: 1.0.16
		Author: aThemes

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.7.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.9
		Author: Brainstorm Force, Nikhil Chavan

	Forminator
		Version: 1.15.12
		Author: WPMU DEV

	FortressDB
		Version: 2.0.21
		Author: FortressDB

	Hello Dolly
		Version: 1.7.2
		Author: Matt Mullenweg

	Jetpack
		Version: 10.7
		Author: Automattic

	Sydney Toolbox
		Version: 1.22
		Author: aThemes

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	WooCommerce Blocks
		Version: 7.2.0
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 1.25.24
		Author: WooCommerce

	Woo Discount Rules
		Version: 2.3.13
		Author: Flycart

	WooLentor - WooCommerce Elementor Addons + Builder
		Version: 2.2.2
		Author: HasThemes

== Elements Usage ==
	
	page : 4
		athemes-testimonials : 1
		button : 9
		heading : 9
		icon-box : 4
		icon-list : 2
		image : 1
		shortcode : 1
		text-editor : 4
		woolentor-product-archive-addons : 2
		woolentor-universal-product : 1
	wp-page : 11
		athemes-testimonials : 1
		button : 8
		heading : 13
		icon : 3
		image : 11
		spacer : 7
		text-editor : 12
		woolentor-universal-product : 8
	landing-page : 0
		button : 2
		divider : 1
		heading : 11
		icon : 5
		icon-box : 4
		icon-list : 2
		image : 5
		image-box : 4
		star-rating : 2
		testimonial : 2
		text-editor : 2

<br />
<b>Notice</b>:  Undefined index: title in <b>/home/malivrthr/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php</b> on line <b>89</b><br />

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 4 of 4PHP: 2022-02-25 12:35:28 [notice X 1][/home/malivrthr/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::186] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-25 15:29:43 [notice X 2][/home/malivrthr/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-27 12:54:19 [notice X 4][/home/malivrthr/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 11:19:23 [error X 1][/home/malivrthr/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 3653128 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-02-25 15:31:03 [error X 25][https://zdraviobrok.hr/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.5:2:21986] undefined is not an object (evaluating \'new elementorModules.frontend.tools\') 
JS: 2022-02-27 17:24:35 [error X 1][https://zdraviobrok.hr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:245893] undefined is not an object (evaluating \'T.params.args.data.id\') 
JS: 2022-03-07 11:17:01 [error X 1][https://zdraviobrok.hr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:349560] Cannot read properties of null (reading \'id\') 
JS: 2022-03-07 11:42:47 [error X 1][https://zdraviobrok.hr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:252935] Cannot read properties of undefined (reading \'html\') 
JS: 2022-03-07 11:42:56 [error X 1][https://zdraviobrok.hr/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.5:2:5069] Cannot read properties of undefined (reading \'attributes\') 

Log: showing 10 of 102022-03-16 11:38:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.7.0-dev1',
)]
2022-03-16 11:38:05 [info] elementor::elementor_updater Started 
2022-03-16 11:38:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-16 11:38:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-16 11:38:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.7.0-dev1',
)]
2022-03-16 11:38:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.7.0-dev1',
)]
2022-03-17 18:28:39 [info] elementor::elementor_updater Started 
2022-03-17 18:28:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-17 18:28:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-17 18:28:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev1',
  'to' => '3.7.0-dev2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible
	WooLentor - WooCommerce Elementor Addons + Builder: Incompatible

**Comment by rami-elementor** [comment]
Hi @sar1ca ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
