### ISSUE TITLE
✔️ 🐞 Bug Report: Padding Container & Live Preview Issue

### ISSUE THREAD

**Issue by elementor-presents** [elementor/elementor#18201]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Hello dear community!

I have two problems and I hope you can help me.

I am currently using version 3.7., everything up to date.

First problem:

When using the new container widget, I noticed that for some breakpoints like tablet and tablet extra, just padding top + bottom works, but not left + right. However, for desktop, mobile, etc, it works fine. Anyone with the same issues?

Second:

In the editor, I can see the spacing from content to content within a container, which I have set with the "Element Gap" for different breakpoints. When I view the web page live in the browser, all these settings are not visible. Here is a screenshot to show you.

### Steps to reproduce

<img width="1723" alt="editor" src="https://user-images.githubusercontent.com/101981631/159168787-40b83519-5581-4084-965f-e0f91beea470.png">
<img width="687" alt="live tablet" src="https://user-images.githubusercontent.com/101981631/159168796-a9eed127-622d-4d9c-b130-6676776d209b.png">

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.15
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://klatho.marsall-media.de
	Home URL: https://klatho.marsall-media.de
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 1024M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: wordpress@marsall-media.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

== Active Plugins ==
	All in One SEO
		Version: 4.1.8
		Author: All in One SEO Team

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.42
		Author: Benjamin A. Bornschein, Borlabs

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Duplicator
		Version: 1.4.4
		Author: Snap Creek

	Ele Custom Skin
		Version: 3.1.4
		Author: Dudaster.com

	Elemental Menu
		Version: 2.0.6
		Author: WP Clevel

	Elementor
		Version: 3.7.0-dev1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0
		Author: Elementor.com

	Fluent Forms
		Version: 4.3.3
		Author: Contact Form - WPManageNinja LLC

	Fluent Forms Pro Add On Pack
		Version: 4.3.2
		Author: Fluent Forms

	OoohBoi Steroids for Elementor
		Version: 1.9.0
		Author: OoohBoi

	Password Protected
		Version: 2.5
		Author: Ben Huson

== Elementor Experiments ==
	Optimierte DOM Ausgabe: Aktiv
	Improved Asset Loading: Aktiv
	Improved CSS Loading: Aktiv
	Inline Font Icons: Aktiv
	Accessibility Improvements: Aktiv
	Import Export Template Kit: Aktiv
	Additional Custom Breakpoints: Aktiv
	Hide native WordPress widgets from search results: Aktiv
	: Inactive by default
	Flexbox Container: Aktiv
	Default to New Theme Builder: Aktiv
	Hello Theme Header & Footer: Aktiv
	Landing Pages: Aktiv
	Color Sampler: Aktiv
	Favorite Widgets: Aktiv
	Admin Top Bar: Aktiv
	Page Transitions: Aktiv
	Form Submissions: Aktiv
	Scroll Snap: Aktiv

**Comment by nicholaszein** [comment]
Hello there @elementor-presents!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
