### ISSUE TITLE
🐞 Bug report: Issue with the shopping cart icon. The bubble with number of items added to the cart is over the amount

### ISSUE THREAD

**Issue by theitpyme** [elementor/elementor#18227]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello all, I hope you're doing well, After Upgrade to Elementor Pro 3.6.4 from 3.6.3, I have an issue with the shopping cart icon. The bubble with number of items added to the cart is over the amount and when try to control de position of the icon through elementor widget, not work properly, do not do nothing. I've updated three sites and three has the same issue, if you revert version to previous version, all is ok again.

![image](https://user-images.githubusercontent.com/102185752/159566235-f8aa0090-e68c-42c9-b737-2109019d4397.png)

I try to:

Disable Caché Plugins
Regenerate CSS
Install another theme (Hello) and then activate theme

And none of these things has worked.

If I add this CSS lines (Workaround):

.elementor-menu-cart__toggle .elementor-button {
   gap: 10px;
}

The amount is moved 10px to the right and now is not covered by bubble.

### Steps to reproduce

Install Blank Wordpress Site
Install WooCommerce
Install Elementor and Elementor Pro Plugins
Create a Header with Shopping Cart Widget
See the Result

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.6.47
	PHP Version: 7.4.23
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://www.fabricatn3d.com
	Home URL: https://www.fabricatn3d.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: es
	Timezone: Europe/Madrid
	Admin Email: info@fabricatn3d.com
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

== Active Plugins ==
	Cecabank WooCommerce Plugin
		Version: 0.1.9
		Author: Cecabank, S.A.

	Colorlib Login Customizer
		Version: 1.3.1
		Author: Colorlib

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	GA Google Analytics
		Version: 20220124
		Author: Jeff Starr

	GDPR Cookie Compliance
		Version: 4.8.1
		Author: Moove Agency

	GP Premium
		Version: 2.1.2
		Author: Tom Usborne

	JetEngine
		Version: 2.11.5
		Author: Crocoblock

	JetPopup
		Version: 1.5.5
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.15
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.10
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.15
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.12.1
		Author: Crocoblock

	Smush Pro
		Version: 3.9.6
		Author: WPMU DEV

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	WooCommerce Checkout Field Editor
		Version: 1.7.0
		Author: WooCommerce

	WooCommerce Email Customizer with Drag and Drop Email Builder
		Version: 1.5.15
		Author: Flycart Technologies LLP

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.14.1
		Author: WP Overnight

	WooCommerce PDF Invoices & Packing Slips Premium Templates
		Version: 2.17.0
		Author: Ewout Fernhout

	Yoast SEO
		Version: 18.4.1
		Author: Team Yoast

	Yoast SEO: WooCommerce
		Version: 14.6
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.0
		Author: Team Yoast

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo por defecto
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Activo por defecto
	Importar o exportar un kit de plantillas: Activo por defecto
	Puntos de ruptura personalizados adicionales: Inactivo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	Default to New Theme Builder: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Page Transitions: Activo por defecto
	Form Submissions: Activo por defecto
	Scroll Snap: Activo por defecto

== Registro ==
	
PHP: showing 6 of 6PHP: 2022-02-20 00:12:20 [notice X 2283][/home/fabtn3d/domains/fabricatn3d.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] ¡El argumento $finder_category_name está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-20 00:12:20 [notice X 108][/home/fabtn3d/domains/fabricatn3d.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::116] Trying to get property 'post_title' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-20 02:51:01 [notice X 7][/home/fabtn3d/domains/fabricatn3d.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-26 14:29:48 [notice X 2][/home/fabtn3d/domains/fabricatn3d.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-06 13:32:48 [notice X 6][/home/fabtn3d/domains/fabricatn3d.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-14 06:26:22 [notice X 2][/home/fabtn3d/domains/fabricatn3d.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142022-03-01 08:44:39 [info] elementor::elementor_updater Started 
2022-03-01 08:44:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-01 08:44:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 08:44:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 08:46:40 [info] elementor-pro::elementor_pro_updater Started 
2022-03-01 08:46:40 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-01 08:46:40 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-01 08:46:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-01 08:46:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-20 12:31:25 [info] elementor-pro::elementor_pro_updater Started 
2022-03-20 12:31:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-20 12:31:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-20 12:31:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-20 12:31:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

JS: showing 6 of 6JS: 2022-03-02 15:51:23 [error X 1][https://www.fabricatn3d.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9329\") has already been destroyed and cannot be used. 
JS: 2022-03-02 15:51:24 [error X 1][https://www.fabricatn3d.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9295\") has already been destroyed and cannot be used. 
JS: 2022-03-02 15:51:24 [error X 1][https://www.fabricatn3d.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9363\") has already been destroyed and cannot be used. 
JS: 2022-03-02 16:01:19 [error X 1][https://www.fabricatn3d.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3908\") has already been destroyed and cannot be used. 
JS: 2022-03-02 16:01:19 [error X 1][https://www.fabricatn3d.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3942\") has already been destroyed and cannot be used. 
JS: 2022-03-02 16:01:19 [error X 1][https://www.fabricatn3d.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3976\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada
	JetSearch For Elementor: Compatibilidad no especificada
	JetTabs For Elementor: Compatibilidad no especificada
	JetWooBuilder For Elementor: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

**Comment by michaelwright74** [comment]
Updating Core to v3.6.1 has fixed this for me.

**Comment by theitpyme** [comment]
Same for me, after upgrade to v3.6.1 has been fixed. Thanks.
