### ISSUE TITLE
🚀 Font Awesome new "Thin" style is not available from the icon picker

### ISSUE THREAD

**Issue by pan-athen** [elementor/elementor#18236]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Font Awesome introduced a new "Thin" version of all their icons in their version 6.

This style is not available in Elementor's icon picker tool to use in any elements that offer it.

### Describe the solution you'd like

This style should be available in Elementor's icon picker tool to use in any elements that offer it.

### Describe alternatives you've considered

Using the Font Awesome shortcodes doesn't solve the problem the right way as we cannot integrate the icons with each element's design to achieve consistency, ease of use, and responsive behavior. It's too much work and it doesn't offer a solid result.

### Additional context

The solution should be extended to dynamically retrieve the styles available in a Font Awesome Kit. Font Awesome already announced another style coming and styles should be available as they become available within a kit from their platform.

**Comment by 3l3mentor** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/18397 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
