### ISSUE TITLE
🐞 Bug report: Copy paste container

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#18232]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I copy a container and want to paste it, everything works fine, the only difference is that a section and a column that encompass the whole container are added every time I paste a container.

### Steps to reproduce

copy a container, paste it and observe that a section and a column are added to it

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

none

**Comment by fabianenzensperger** [comment]
Jup. Same here. I hope they fix this soon.

**Comment by parfilov** [comment]
Same bug. Container pastes inside sections and it's not possible to move child widgets.

**Comment by rodolphebertozzo** [comment]
Resolved in 3.6.3 version

**Comment by arditneziri93** [comment]
Problem still persists after years. Please fix this!!!
