### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found

### ISSUE THREAD

**Issue by iggy097** [elementor/elementor#18251]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Sorry I'm new and not advanced in Wordpress - hope this is the correct way to post.
After updating my Wordpress site to the new Elementor I am greeted with a Fatal Error.

 Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found
in /www/wp-content/plugins/essential-addons-elementor/includes/Extensions/EAEL_Tooltip_Section.php on line 224
Call stack:
1.	Essential_Addons_Elementor\P\E\EAEL_Tooltip_Section::register_controls()
wp-includes/class-wp-hook.php:309
2.	WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
3.	WP_Hook::do_action()
wp-includes/plugin.php:474
4.	do_action()
wp-content/plugins/elementor/includes/base/controls-stack.php:1594
5.	Elementor\Controls_Stack::end_controls_section()
wp-content/plugins/elementor/includes/widgets/common.php:605
6.	Elementor\Widget_Common::register_layout_section()
wp-content/plugins/elementor/includes/widgets/common.php:1652
7.	Elementor\Widget_Common::register_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:2282
8.	Elementor\Controls_Stack::init_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:494
9.	Elementor\Controls_Stack::get_stack()
wp-content/plugins/elementor/includes/base/widget-base.php:177
10.	Elementor\Widget_Base::get_stack()
wp-content/plugins/elementor/includes/base/controls-stack.php:300
11.	Elementor\Controls_Stack::get_controls()
wp-content/plugins/elementor/core/files/css/global-css.php:120
12.	Elementor\C\F\C\Global_CSS::render_schemes_and_globals_css()
wp-content/plugins/elementor/core/files/css/global-css.php:66
13.	Elementor\C\F\C\Global_CSS::render_css()
wp-content/plugins/elementor/core/files/css/base.php:632
14.	Elementor\C\F\C\Base::parse_content()
wp-content/plugins/elementor/core/files/base.php:180
15.	Elementor\C\F\Base::update_file()
wp-content/plugins/elementor/core/files/css/base.php:131
16.	Elementor\C\F\C\Base::update()
wp-content/plugins/elementor/core/files/css/base.php:218
17.	Elementor\C\F\C\Base::enqueue()
wp-content/plugins/elementor/includes/frontend.php:980
18.	Elementor\Frontend::parse_global_css_code()
wp-content/plugins/elementor/includes/frontend.php:633
19.	Elementor\Frontend::enqueue_styles()
wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php:90
20.	ElementorPro\M\T\C\Locations_Manager::enqueue_styles()
wp-includes/class-wp-hook.php:307
21.	WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
22.	WP_Hook::do_action()
wp-includes/plugin.php:474
23.	do_action()
wp-includes/script-loader.php:2105
24.	wp_enqueue_scripts()
wp-includes/class-wp-hook.php:307
25.	WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
26.	WP_Hook::do_action()
wp-includes/plugin.php:474
27.	do_action()
wp-includes/general-template.php:3042
28.	wp_head()
wp-content/plugins/elementor-pro/modules/theme-builder/views/theme-support-header.php:21
29.	require()
wp-content/plugins/elementor-pro/modules/theme-builder/classes/theme-support.php:72
30.	ElementorPro\M\T\C\Theme_Support::get_header()
wp-includes/class-wp-hook.php:309
31.	WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
32.	WP_Hook::do_action()
wp-includes/plugin.php:474
33.	do_action()
wp-includes/general-template.php:38
34.	get_header()
wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php:9
35.	include()
wp-includes/template-loader.php:106
36.	require_once()
wp-blog-header.php:19
37.	require()
index.php:17

### Steps to reproduce

I updated yesterday same error. 
Tried today with the latest version, same error.
Rolling back my site fixes.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.36
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://www.seductivestudiosmembers.com/girls-will-be-girls-club
	Home URL: https://www.seductivestudiosmembers.com/girls-will-be-girls-club
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: dan@seductivestudios.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46

== Active Plugins ==
	Category Ajax Filter PRO
		Version: 8.3.1
		Author: Trusty Plugins

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.0.10
		Author: WPDeveloper

	Paid Memberships Pro
		Version: 2.7.5
		Author: Paid Memberships Pro

	Paid Memberships Pro - Cancel on Next Payment Date
		Version: 0.4
		Author: Paid Memberships Pro

	Paid Memberships Pro - Multisite Membership Add On
		Version: 0.4.5
		Author: Paid Memberships Pro

	Paid Memberships Pro - Reason For Cancelling Add On
		Version: 0.2.1
		Author: Paid Memberships Pro

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

== Network Plugins ==
	Advanced Database Cleaner
		Version: 3.0.4
		Author: Younes JFR.

	Category Ajax Filter
		Version: 2.3
		Author: Trusty Plugins

	Category Ajax Filter PRO
		Version: 8.3.1
		Author: Trusty Plugins

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor Pro
		Version: 3.1.1
		Author: Elementor.com

	Essential Addons for Elementor - Pro
		Version: 4.3.2
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 8.4.0
		Author: MonsterInsights

	Hide Admin Bar
		Version: 0.4.2
		Author: Shelby DeNike

	LoginWP (Formerly Peter's Login Redirect)
		Version: 3.0.0.7
		Author: LoginWP Team

	Paid Memberships Pro - User Pages Add On
		Version: .6
		Author: Stranger Studios

	Post SMTP
		Version: 2.0.24
		Author: Yehuda Hassine

	Query Monitor
		Version: 3.8.2
		Author: John Blackbourn

	Sendy Widget
		Version: 1.4
		Author: WebHolics

	WP Cerber Security, Anti-spam & Malware Scan
		Version: 8.9.6
		Author: Cerber Tech Inc.

	WP Rollback
		Version: 1.7.1
		Author: Impress.org

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 432021-12-29 08:39:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2021-12-29 08:39:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2021-12-29 08:39:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.2',
  'to' => '3.5.3',
)]
2022-01-24 13:40:46 [info] elementor::elementor_updater Started 
2022-01-24 13:40:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-24 13:40:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-24 13:40:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-02-03 06:11:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-03 06:11:50 [info] elementor::elementor_updater Started 
2022-02-03 06:11:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-03 06:11:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-03 06:11:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-03-01 07:40:19 [info] elementor::elementor_updater Started 
2022-03-01 07:40:19 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-01 07:40:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 07:40:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 07:40:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 07:40:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 07:40:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 07:40:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by DaanG47** [comment]
Hi there! 

Same problem here after updating to Elementor 3.6.1. A fatal error on the public side of the website:

PHP Fatal error:  Uncaught Error: Class 'Elementor\\Scheme_Typography' not found in....

Using Elementor 3.6.1 in combination with Elementor PRO 3.6.4.
A rollback to Elementor 3.5.6 seems to remove the issue and makes the website accessible again.

**Comment by shilo-ey** [comment]
Hey, 

The problem resides in essential-addons-elementor plugin which uses a deprecated function that is not being supported since Elementor v2.8 - https://developers.elementor.com/v3-6-planned-deprecations/

We already reached out to the developers of this plugin and it should be compatible soon.

Closing this for now.

Thanks

**Comment by DaanG47** [comment]
Hi,

I do not have  essential-addons-elementor installed.
The error is only present in Elementor version 3.6.1 but everything is still working under 3.5.6.
Are there any functions deprecated between 3.5.6 and 3.6.1 ?


My apache log shows me the following:


PHP Fatal error:  
Uncaught Error: Class 'Elementor\\Scheme_Typography' not found in /data/www/***.nl/public_html/wp-content/plugins/ultimate-reviewer/admin/elementor/elementor-add-user-ratings.php:66\n

Stack trace:\
n#0/data/www/***.nl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): GPUR_Elementor_Add_User_Rating_Widget->_register_controls()\
n#1 /data/www/***.nl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\\Controls_Stack->init_controls()\
n#2 /data/www/***.nl/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\\Controls_Stack->get_stack()\
n#3 /data/www/***.nl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\\Widget_Base->get_stack()\
n#4 /data/www/***.nl/public_html/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\\Controls_Stack->get_controls()\
n#5 /data/www/***.nl/p in /data/www/***.nl/public_html/wp-content/plugins/ultimate-reviewer/admin/elementor/elementor-add-user-ratings.php on line 66

**Comment by Gabugbuster** [comment]
@DaanG47 According to the error you receive, you use the "ultimate-reviewer" plugin, which calls the deprecated class. It is the same issue. The long deprecation cycle (that began several versions ago) ended with Elementor 3.6.0.

**Comment by iggy097** [comment]
This issue still persists after Ultimate Addons have updated claiming they are compatible
 Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found
in /www/wp-content/plugins/essential-addons-elementor/includes/Extensions/EAEL_Tooltip_Section.php on line 224

Call stack:

Essential_Addons_Elementor\P\E\EAEL_Tooltip_Section::register_controls()
wp-includes/class-wp-hook.php:309
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-content/plugins/elementor/includes/base/controls-stack.php:1594
Elementor\Controls_Stack::end_controls_section()
wp-content/plugins/elementor/includes/widgets/common.php:605
Elementor\Widget_Common::register_layout_section()
wp-content/plugins/elementor/includes/widgets/common.php:1652
Elementor\Widget_Common::register_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:2282
Elementor\Controls_Stack::init_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:494
Elementor\Controls_Stack::get_stack()
wp-content/plugins/elementor/includes/base/widget-base.php:177
Elementor\Widget_Base::get_stack()
wp-content/plugins/elementor/includes/base/controls-stack.php:300
Elementor\Controls_Stack::get_controls()
wp-content/plugins/elementor/core/files/css/global-css.php:120
Elementor\C\F\C\Global_CSS::render_schemes_and_globals_css()
wp-content/plugins/elementor/core/files/css/global-css.php:66
Elementor\C\F\C\Global_CSS::render_css()
wp-content/plugins/elementor/core/files/css/base.php:632
Elementor\C\F\C\Base::parse_content()
wp-content/plugins/elementor/core/files/base.php:180
Elementor\C\F\Base::update_file()
wp-content/plugins/elementor/core/files/css/base.php:131
Elementor\C\F\C\Base::update()
wp-content/plugins/elementor/core/files/css/base.php:218
Elementor\C\F\C\Base::enqueue()
wp-content/plugins/elementor/includes/frontend.php:980
Elementor\Frontend::parse_global_css_code()
wp-content/plugins/elementor/includes/frontend.php:633
Elementor\Frontend::enqueue_styles()
wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php:90
ElementorPro\M\T\C\Locations_Manager::enqueue_styles()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/script-loader.php:2105
wp_enqueue_scripts()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/general-template.php:3042
wp_head()
wp-content/plugins/elementor-pro/modules/theme-builder/views/theme-support-header.php:21
require()
wp-content/plugins/elementor-pro/modules/theme-builder/classes/theme-support.php:72
ElementorPro\M\T\C\Theme_Support::get_header()
wp-includes/class-wp-hook.php:309
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/general-template.php:38
get_header()
wp-content/themes/twentytwentyone/single.php:12
include()
wp-includes/template-loader.php:106
require_once()
wp-blog-header.php:19
require()
index.php:17

**Comment by encreinformatique** [comment]
> Hey,
> 
> The problem resides in essential-addons-elementor plugin which uses a deprecated function that is not being supported since Elementor v2.8 - https://developers.elementor.com/v3-6-planned-deprecations/
> 
> We already reached out to the developers of this plugin and it should be compatible soon.
> 
> Closing this for now.
> 
> Thanks

The problem still occurs with Essential Addons as of today. I contacted the support with a proper fix monthes ago. (might be a year) I have a pro license with them to make things worse.
They really don't care.
