### ISSUE TITLE
Dark Mode - Auto-Detect not functioning correctly🐞 Bug report: 

### ISSUE THREAD

**Issue by AshleyinSpain** [elementor/elementor#18266]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I had Elementor dark mode set to auto-detect - I have my desktop w10 and all programs and browsers set to dark mode
After one of the auto upgrades of Elementor including Pro
Dark Mode is not being set in the Theme Builder anymore
The page editor is set in Dark mode ok though

I can set dark mode manually by setting to dark and the Theme Builder reverts to dark again

But it no longer works on auto detection

### Steps to reproduce

In Page builder > hamburger > preferences - set UI Theme to Auto Detect and save 
Update Elementor and Elementor Pro to latest versions
Go to Dashboard Menu > Templates > Theme Builder
Check Theme Builder showing in dark mode

On my installation it shows in light made
This is incorrect and new behaviour since one of the upgrades - don't know which though

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.25
	PHP Version: 8.0.16
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://www.musicologic.es
	Home URL: https://www.musicologic.es
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Admin Email: ashley@musicologic.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36

== Active Plugins ==
	Akeeba Backup Professional for WordPress
		Version: 7.6.2.1
		Author: Akeeba Ltd

	All In One WP Security
		Version: 4.4.10
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Dynamic Visibility for Elementor
		Version: 4.1.2
		Author: Dynamic.ooo

	Elementor
		Version: 3.6.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Favicon by RealFaviconGenerator
		Version: 1.3.23
		Author: Philippe Bernard

	JetTabs For Elementor
		Version: 2.1.16
		Author: Crocoblock

	Quantity Discounts & Pricing For Woocommerce
		Version: 2.0.1
		Author: Plugify

	Simple Custom CSS and JS
		Version: 3.39
		Author: SilkyPress.com

	Teams for WooCommerce Memberships
		Version: 1.6.2
		Author: SkyVerge

	UpdraftPlus - Backup/Restore
		Version: 2.22.11.25
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	WooCommerce Checkout Field Editor
		Version: 1.7.2
		Author: WooCommerce

	WooCommerce Memberships
		Version: 1.22.11
		Author: SkyVerge

	WooCommerce PayPal Payments
		Version: 1.7.0
		Author: WooCommerce

	WooCommerce PDF Invoices
		Version: 4.15.4
		Author: Andrew Benbow

	WooCommerce Stripe Gateway
		Version: 6.3.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 4.1.0
		Author: WooCommerce

== Must-Use Plugins ==
	Admin language fix for elementor
		Version: 1.0.0
		Author: Ashley from @crazypsycho Github

	akeeba-backup-coreupdate.php
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 1
		heading : 2
		icon-list : 1
		nav-menu : 3
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 2
		button : 3
		heading : 1
		icon-list : 1
		nav-menu : 2
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 5
		heading : 4
	popup : 2
		button : 2
		image : 4
		login : 2
	product : 3
		heading : 1
		icon : 2
		spacer : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 1
		woocommerce-product-images : 2
		woocommerce-product-price : 2
		woocommerce-product-short-description : 1
		woocommerce-product-title : 4
		woocommerce-product-upsell : 2
	section : 6
		button : 16
		heading : 72
		html : 16
		icon-list : 40
		jet-tabs : 1
		text-editor : 24
	wp-page : 15
		accordion : 1
		button : 12
		form : 1
		heading : 58
		icon : 8
		icon-box : 13
		icon-list : 3
		image : 20
		jet-tabs : 1
		login : 2
		media-carousel : 2
		social-icons : 1
		spacer : 5
		testimonial-carousel : 2
		text-editor : 31
		wc-add-to-cart : 2
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-products : 1
	product-archive : 1
		icon : 1
		spacer : 1
		theme-archive-title : 1
		woocommerce-products : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 252022-02-28 19:55:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-02-28 19:55:06 [info] elementor-pro::elementor_pro_updater Started 
2022-02-28 19:55:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-28 19:55:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-28 19:55:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-16 11:27:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-16 11:27:51 [info] elementor-pro::elementor_pro_updater Started 
2022-03-16 11:27:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-16 11:27:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-16 11:27:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-23 17:55:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 17:55:44 [info] elementor::elementor_updater Started 
2022-03-23 17:55:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 17:55:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 17:55:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-24 23:53:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-24 23:53:58 [info] elementor::elementor_updater Started 
2022-03-24 23:53:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-24 23:53:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-24 23:53:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]

PHP: showing 6 of 6PHP: 2022-03-01 02:00:59 [error X 1][/home/xbwxanem/public_html/wp-content/plugins/elementor/includes/controls/groups/base.php::529] Out of memory (allocated 84934656) (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-01 12:48:05 [warning X 53][/home/xbwxanem/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-07 17:59:15 [warning X 4][/home/xbwxanem/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 17:55:44 [notice X 2069][/home/xbwxanem/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 18:10:03 [notice X 556][/home/xbwxanem/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] ¡El argumento $control_id está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-25 21:11:23 [warning X 2][/home/xbwxanem/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 11 of 11JS: 2022-03-02 20:07:41 [error X 4][https://www.musicologic.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:453890] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-03-04 23:03:49 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:558688] elementorFrontend is not defined 
JS: 2022-03-05 21:41:09 [error X 2][https://www.musicologic.es/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Cannot read properties of undefined (reading \'data\') 
JS: 2022-03-09 17:43:23 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6687\") has already been destroyed and cannot be used. 
JS: 2022-03-09 17:43:24 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6724\") has already been destroyed and cannot be used. 
JS: 2022-03-09 17:43:24 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6798\") has already been destroyed and cannot be used. 
JS: 2022-03-09 17:43:24 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6761\") has already been destroyed and cannot be used. 
JS: 2022-03-09 18:07:35 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view18666\") has already been destroyed and cannot be used. 
JS: 2022-03-09 18:07:36 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view18702\") has already been destroyed and cannot be used. 
JS: 2022-03-09 18:07:36 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view18774\") has already been destroyed and cannot be used. 
JS: 2022-03-09 18:07:36 [error X 1][https://www.musicologic.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view18738\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Elementor Pro: Compatible
	JetTabs For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	JetTabs For Elementor: Incompatible

**Comment by arielk** [comment]
Merge: https://github.com/elementor/elementor/issues/19670
Fix: https://github.com/arielk/elementor/commit/c9573048bfa5523168b672513a3fb5297f42b844
