### ISSUE TITLE
🔗 🚀 Extra space in WooCommerce notice widget (Merged into #25711)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18275]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi @avivu 
In fact, this is not a bug. But it is strange why it has not been paid attention to ...

In the WooCommerce notice widget, by default there is a large space at the bottom that makes design difficult. Please see this image : https://prnt.sc/-V7u571OBLqh
This is really a very simple case. please check it

### Steps to reproduce

please Delete this extra space in the WooCommerce notice widget

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello!

We are organizing GitHub Issues, and migrating Feature Requests to discussions. This Issue specifically points to a bug, it it's actually simply not a bug, just haven't been implemented yet. 

### 🔗 🚀 There is already a similar request submitted by someone here #25711

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards
