### ISSUE TITLE
🐞 Bug report: Elementor PRO (Woocommerce) Widgets styling not applied

### ISSUE THREAD

**Issue by ciltocruz** [elementor/elementor#18289]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The styles of widgets for woocommerce elements is not working. 

For example, cart widget for woocommerce, I have set background color to red in the checkout button but on preview it is blue. I can see that background-color is applied from widget-woocommerce.min.css not from post*.css.

I am attaching three screenshots:
![image](https://user-images.githubusercontent.com/19903919/160451774-61ca8b8e-116a-49bd-89f3-d8545289c5f8.png)
![image](https://user-images.githubusercontent.com/19903919/160451845-94030c06-b0a9-4300-888f-48056737ea23.png)
![image](https://user-images.githubusercontent.com/19903919/160452193-e9f07813-0a8d-4f08-aaad-30011c092e5b.png)

NOTE: I did clear caches and regenerated css, even tried to switch css loading mode. 

### Steps to reproduce

Create cart module.
Edit checkout button style.
View the resulting page.

It seems that the woocommerce style always takes precedence over the post style.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9
	MySQL version: MariaDB Server v10.3.27
	PHP Version: 7.4.12
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 4096M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	WP Multisite: No
	Max Upload Size: 4 GB
	Memory limit: 128M
	Max Memory limit: 1024M

== Theme ==
	Name: Hello Elementor
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.7 Safari/537.36

== Active Plugins ==
	Additional Variation Images Gallery for WooCommerce
		Version: 1.2.9
		Author: Emran Ahmed

	All In One WP Security
		Version: 4.4.10
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Antispam Bee
		Version: 2.10.0
		Author: pluginkollektiv

	Elementor
		Version: 3.6.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	GDPR Cookie Compliance
		Version: 4.7.7
		Author: Moove Agency

	MailPoet 3 (New)
		Version: 3.84.0
		Author: MailPoet

	Premmerce Permalink Manager for WooCommerce
		Version: 2.3.3
		Author: premmerce

	ShortPixel Image Optimizer
		Version: 4.22.7
		Author: ShortPixel

	Visual Term Description Editor
		Version: 1.8.1
		Author: Shea Bunge

	WooCommerce
		Version: 6.2.2
		Author: Automattic

	WooCommerce Multilingual
		Version: 4.12.3
		Author: OnTheGoSystems

	WooCommerce PayPal Payments
		Version: 1.6.5
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 6.2.0
		Author: WooCommerce

	Wordfence Security
		Version: 7.5.5
		Author: Wordfence

	WP Maintenance Mode
		Version: 2.4.1
		Author: Designmodo

	WPML Media
		Version: 2.7.0
		Author: OnTheGoSystems

	WP Rocket
		Version: 3.8.7
		Author: WP Media

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Uso de los elementos ==
	
	archive : 1
		archive-posts : 1
		heading : 3
		icon-list : 1
		posts : 1
		search-form : 1
	footer : 2
		heading : 3
		html : 1
		icon : 2
		icon-list : 4
		image : 1
		search-form : 1
		social-icons : 1
		text-editor : 1
	header : 2
		icon : 1
		nav-menu : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
		wpml-language-switcher : 1
	product : 2
		icon-box : 1
		share-buttons : 1
		text-editor : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-stock : 1
		woocommerce-product-title : 1
	section : 1
		table-of-contents : 1
	wp-post : 3
		heading : 11
		image : 10
		image-box : 22
		text-editor : 16
	wp-page : 23
		accordion : 3
		button : 3
		call-to-action : 2
		flip-box : 4
		form : 1
		heading : 75
		html : 1
		icon-list : 1
		image : 31
		image-box : 15
		menu-anchor : 3
		posts : 2
		search-form : 1
		spacer : 7
		text-editor : 82
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-products : 3
	single-post : 1
		author-box : 1
		heading : 4
		icon-list : 1
		post-info : 1
		posts : 2
		search-form : 1
		share-buttons : 1
		table-of-contents : 1
		theme-post-content : 1
	product-archive : 4
		woocommerce-archive-description : 2
		woocommerce-products : 2

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo por defecto
	Carga de recursos mejorada: Activo por defecto
	Carga de CSS mejorada: Activo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Activo por defecto
	Importar o exportar un kit de plantillas: Activo por defecto
	Puntos de ruptura personalizados adicionales: Activo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	: Inactivo por defecto
	Flexbox Container: Inactivo por defecto
	Default to New Theme Builder: Activo por defecto
	Hello Theme Header & Footer: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Page Transitions: Activo por defecto
	Form Submissions: Activo por defecto
	Scroll Snap: Activo por defecto

== Registro ==
	
PHP: showing 7 of 7PHP: 2021-10-07 18:47:29 [notice X 250][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-13 18:44:12 [notice X 155][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-10-14 13:03:18 [notice X 52][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::142] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-21 09:30:36 [notice X 1][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::256] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 11:34:29 [error X 1][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/haramakimeu/web/haramakimeu.es/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/haramakimeu/web/haramakimeu.es/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/haramakimeu/web/haramakimeu.es/public_html [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-27 11:55:51 [notice X 2][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-terms.php::93] Undefined index: taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-27 17:34:52 [notice X 1][/home/haramakimeu/web/haramakimeu.es/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 282022-02-21 08:57:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.4',
  'to' => '3.5.5',
)]
2022-02-21 09:02:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.6.2',
)]
2022-02-21 09:02:35 [info] elementor-pro::elementor_pro_updater Started 
2022-02-21 09:02:35 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-21 09:02:35 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-21 09:02:35 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-02-21 09:02:43 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-02-21 09:02:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.6.2',
)]
2022-02-21 09:02:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.6.2',
)]
2022-03-28 18:58:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.1',
)]
2022-03-28 18:58:03 [info] elementor::elementor_updater Started 
2022-03-28 18:58:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-28 18:58:03 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-28 18:58:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.1',
)]
2022-03-28 18:59:50 [info] elementor-pro::elementor_pro_updater Started 
2022-03-28 18:59:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-28 18:59:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-28 18:59:50 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-03-28 18:59:55 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-03-28 18:59:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]

JS: showing 8 of 8JS: 2022-02-21 14:07:40 [error X 5][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.5:2:5069] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-02-23 12:43:16 [error X 2][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:585621] Cannot read properties of undefined (reading \'view\') 
JS: 2022-02-25 17:13:00 [error X 2][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-03-02 10:13:46 [error X 17224][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-03-02 10:13:53 [error X 469][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-03-09 15:48:12 [error X 1][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6046\") has already been destroyed and cannot be used. 
JS: 2022-03-25 17:04:00 [error X 2][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453830] T is null 
JS: 2022-03-26 18:04:57 [error X 3][https://www.haramakimeu.es/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:245894] Cannot read properties of undefined (reading \'id\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by hitsgee** [comment]
I have this issue to. Not sure if it's hello theme related

**Comment by ciltocruz** [comment]
I don't think so. That occurs without Hello Theme

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Comment by ciltocruz** [comment]
Thanks!

**Comment by aiyubpanara786** [comment]
I am facing same issue.

Elementor Pro - Version 3.16.2
