### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Elarrasador** [elementor/elementor#18282]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Cuando abro la pagina web se queda bloqueado, se activa el modo seguro y aun asi sigue sin funcionar. He seguido todos los pasos a seguir pero sigue sin funcionar.

### Steps to reproduce

Abro wordpress. Me meto para editar las paginas y se queda en constante carga.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px;">

Linux |  
-- | --
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.13 |  
PHP Version: | 7.4.27 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div><div class="elementor-system-info-section elementor-system-info-elementor-pro_compatibility" style="outline: 0px; margin-bottom: 10px;"><table class="widefat" style="border-spacing: 0px; width: 1817px; clear: both; margin: 0px; border: 1px solid rgb(195, 196, 199); box-shadow: rgba(0, 0, 0, 0.04) 0px 1px 1px; background: rgb(255, 255, 255); white-space: pre;"><thead style="overflow-wrap: break-word;"><tr style="overflow-wrap: break-word;"><th style="overflow-wrap: break-word; padding: 8px 10px; text-align: left; line-height: 1.4em; font-size: 14px; color: rgb(44, 51, 56); font-weight: 400; border-bottom: 1px solid rgb(195, 196, 199);">Elementor Pro - Compatibility Tag</th><th style="overflow-wrap: break-word; padding: 8px 10px; text-align: left; line-height: 1.4em; font-size: 14px; color: rgb(44, 51, 56); font-weight: 400; border-bottom: 1px solid rgb(195, 196, 199);"></th><th style="overflow-wrap: break-word; padding: 8px 10px; text-align: left; line-height: 1.4em; font-size: 14px; color: rgb(44, 51, 56); font-weight: 400; border-bottom: 1px solid rgb(195, 196, 199);"></th></tr></thead><tbody style="overflow-wrap: break-word;"><tr style="overflow-wrap: break-word;"><td style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-weight: 400; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">
</body>
</html>Linux	
Software:	LiteSpeed	
MySQL version:	MariaDB Server v10.5.13	
PHP Version:	7.4.27	
PHP Memory Limit:	512M	
PHP Max Input Vars:	5000	
PHP Max Post Size:	512M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	5.9.2	
Site URL:	https://escamondao.com	
Home URL:	https://escamondao.com	
WP Multisite:	No	
Max Upload Size:	512 MB	
Memory limit:	40M	
Max Memory limit:	512M	
Permalink Structure:	/%postname%/	
Language:	es	
Timezone:	0	
Admin Email:	christian.business.work6@gmail.com	
Debug Mode:	Inactive	
Theme		
Name:	Twenty Twenty	
Version:	1.9	
Author:	the WordPress team	
Child Theme:	No	Si quieres modificar el código fuente de tu tema, te recomendamos utilizar un [tema hijo](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	es_ES	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36	
Active Plugins		
[All-in-One WP Migration](https://servmask.com/) - 7.56	By [ServMask](https://servmask.com/)	
[All in One SEO](https://aioseo.com/) - 4.1.8	By [All in One SEO Team](https://aioseo.com/)	
[Creative Mail by Constant Contact](https://wordpress.org/plugins/creative-mail-by-constant-contact/) - 1.5.1	By [Constant Contact](https://www.constantcontact.com/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.7.0-dev2	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.6.4	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[Google Analytics for WordPress by MonsterInsights](https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=pluginurl&utm_content=7%2E0%2E0) - 8.4.0	By [MonsterInsights](https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=authoruri&utm_content=7%2E0%2E0)	
Experimentos de Elementor		
Salida del DOM optimizada: 	Activo por defecto
Carga de recursos mejorada: 	Activo por defecto
Carga de CSS mejorada: 	Activo por defecto
Fuentes de iconos integradas: 	Inactivo por defecto
Mejoras de accesibilidad: 	Activo por defecto
Importar o exportar un kit de plantillas: 	Activo
Puntos de ruptura personalizados adicionales: 	Activo por defecto
Ocultar los widgets nativos de WordPress de los resultados de búsqueda: 	Activo por defecto
: 	Inactivo por defecto
Flexbox Container: 	Inactivo por defecto
Default to New Theme Builder: 	Activo por defecto
Páginas de destino: 	Activo por defecto
Muestrario de colores: 	Activo por defecto
Widgets favoritos: 	Activo por defecto
Barra superior de administración: 	Activo por defecto
Page Transitions: 	Activo por defecto
Form Submissions: 	Activo por defecto
Scroll Snap: 	Activo por defecto
Registro[Vaciar el registro](https://escamondao.com/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=46fe23ede7#elementor-clear-log)		
JS: showing 8 of 8
JS: 2022-03-18 07:56:14 [error X 14][https://escamondao.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:558688] elementorFrontend is not defined 
JS: 2022-03-18 07:57:31 [error X 91][https://escamondao.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:405235] _.findWhere is not a function 
JS: 2022-03-20 18:54:35 [error X 5750][https://escamondao.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-03-20 18:54:36 [error X 168][https://escamondao.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-03-20 18:54:52 [error X 1][::] Cannot read properties 
JS: 2022-03-23 20:29:30 [error X 3][https://escamondao.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0:2:515679] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-03-23 21:22:33 [error X 9][https://escamondao.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.0:2:12166] this.parent.children.splice is not a function 
JS: 2022-03-23 21:22:35 [error X 2][https://escamondao.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0:2:363196] Cannot read properties of undefined (reading \'isEditable\') 
PHP: showing 10 of 10
PHP: 2022-03-20 15:21:39 [notice X 16][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-20 15:53:30 [warning X 2][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::272] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-20 16:42:09 [notice X 8][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::256] Undefined index: sub_name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-20 16:49:02 [error X 6][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/u470355930/domains/escamondao.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/u470355930/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-20 18:55:31 [notice X 1][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-22 13:03:09 [error X 1][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(4606, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/u470355930/domains/escamondao.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/u470355930/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-22 13:28:01 [error X 2][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(3973, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/u470355930/domains/escamondao.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/u470355930/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 14:19:55 [error X 1][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(4726, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/u470355930/domains/escamondao.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/u470355930/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-27 16:27:23 [notice X 7][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-27 16:52:26 [notice X 1][/home/u470355930/domains/escamondao.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
Log: showing 15 of 15
2022-03-23 13:21:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 13:21:08 [info] elementor::elementor_updater Started 
2022-03-23 13:21:08 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 13:21:08 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 13:21:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-24 15:20:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-24 15:20:50 [info] elementor::elementor_updater Started 
2022-03-24 15:20:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-24 15:20:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-24 15:20:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-24 15:20:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-27 16:29:26 [info] elementor::elementor_updater Started 
2022-03-27 16:29:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-27 16:29:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-27 16:29:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.7.0-dev2',
)]
Elementor - Compatibility Tag		
 Elementor Pro 	 Incompatible 
Elementor Pro - Compatibility Tag

**Comment by rami-elementor** [comment]
@Elarrasador Please write in English.
