### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by suyogricha** [elementor/elementor#18285]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

beta.(*) domain is not in https://elementor.com/help/activate-your-license-key/

### Describe the solution you'd like

Add beta.(*) domain so that development could be free and it should not ask for license for it. beta subdomains should not be considered as a license.

**Comment by rami-elementor** [comment]
Hi @suyogricha ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. We offer 6 top-level domains and 4 subdomain to choose from.

Regards,
