### ISSUE TITLE
⛔ 📢 Report a bug and a suggestion in the Menu cart widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18290]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hello @avivu , Please check these if possible.

**BUG**

If there are many products in this widget and it can be scrolled, there is a lot of empty space at the top. please [Look](https://prnt.sc/9OeNPC3HNKfo) at this picture. Its boundaries are quite clear. Of course, even if scrolling is not active, this distance exists, but it is not very noticeable : https://prnt.sc/8JThHHEUYkuo

**Suggest a new feature**

Please add the ability to customize the scroll bar in this widget. The [current scroll bar](https://prnt.sc/eEFem5ZaVlhO) severely corrupts the user interface.
This scroll bar will be great : https://prnt.sc/xquSk-_qE-uB

 Thanks in advance

### Describe the solution you'd like

As described above

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Next time lease open a separate ticket for each bug and each feature request.

**Comment by 79ho3ein** [comment]
hi @rami-elementor
ok , thank you

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
