### ISSUE TITLE
⛔ 🐞 Bug report: Group_Control_Base doesn't extend Base_Control

### ISSUE THREAD

**Issue by sanbec** [elementor/elementor#18295]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As it says in https://developers.elementor.com/docs/controls/group-controls/ I have created a control group by extending the \Elementor\Group_Control_Base class:

`class Group_Control_Highlighter extends \Elementor\Group_Control_Base {`

However, when I want to register it (in the same way that works perfectly for other type controls), I get a fatal error:

Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\Controls_Manager::register() must be an instance of Elementor\Base_Control, instance of Elemendas_Addons\Group_Control_Highlighter given

In the page https://developers.elementor.com/docs/controls/control-types/ it says that class Group_Control_Base inherits from Base_Control, although looking at the code it doesn't seem to be so:

`abstract class Group_Control_Base implements Group_Control_Interface {`

Is there any way to register a group control? Is there an alternative filter to elementor/controls/register to do this?

### Steps to reproduce

Create a Group Control extending Group_Control_Base
`class Group_Control_Highlighter extends \Elementor\Group_Control_Base {`

register it with elementor/controls/register action filter hook like:

```
	public function init() {
		add_action( 'elementor/controls/register', [ $this, 'register_controls' ] );
	}

	public function register_controls( $controls_manager ) {

		require_once( __DIR__ . '/controls/highlighter.php' );
		$controls_manager->register( new Group_Control_Highlighter() );

	}

```

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: Ubuntu 20.04 v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: http://desarrollo.local/elemendas
	Home URL: http://desarrollo.local/elemendas
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 0
	Admin Email: santi@wpcombo.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	Elemendas Addons
		Version: 1.0.0
		Author: Elemendas

	Elementor
		Version: 3.6.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Manage Admin Columns
		Version: 1.4.0
		Author: Santiago Becerra

	Rewrite Rules Inspector
		Version: 1.3.1
		Author: Automattic, Daniel Bachhuber

== Must-Use Plugins ==
	Optimización WPCombo
		Version: 1.1
		Author: WPCombo

<br />
<b>Notice</b>:  Undefined index: title in <b>/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/core/experiments/experiments-reporter.php</b> on line <b>89</b><br />

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo por defecto
	Carga de recursos mejorada: Activo por defecto
	Carga de CSS mejorada: Activo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Activo por defecto
	Importar o exportar un kit de plantillas: Activo por defecto
	Puntos de ruptura personalizados adicionales: Inactivo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	: Inactivo por defecto
	Flexbox Container: Inactivo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Cabecera y pie de página del tema Hello: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Page Transitions: Activo por defecto
	Envíos de formulario: Activo por defecto
	Ajuste de scroll: Activo por defecto

== Registro ==
	
Log: showing 20 of 212022-02-28 13:42:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-28 13:42:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-28 13:42:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 11:17:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.6.3',
)]
2022-03-01 11:17:28 [info] elementor-pro::elementor_pro_updater Started 
2022-03-01 11:17:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-01 11:17:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-01 11:17:28 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-03-01 11:17:28 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-03-01 11:17:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.0',
  'to' => '3.6.3',
)]
2022-03-16 17:37:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-16 17:37:35 [info] elementor-pro::elementor_pro_updater Started 
2022-03-16 17:37:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-16 17:37:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-16 17:37:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-23 10:56:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 10:56:53 [info] elementor::elementor_updater Started 
2022-03-23 10:56:53 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 10:56:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 10:56:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]

PHP: showing 10 of 10PHP: 2022-03-16 18:31:36 [notice X 4][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-18 11:54:43 [error X 10][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/base/controls-stack.php::2334] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1095 and defined in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/base/controls-stack.php:2334
Stack trace:
#0 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/base/controls-stack.php(1095): Elementor\Controls_Stack->sanitize_settings()
#1 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/base/controls-stack.php(2083): Elementor\Controls_Stack->get_data()
#2 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Objec [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-18 11:57:23 [notice X 1][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor-pro/modules/screenshots/screenshot.php::249] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 15:46:18 [warning X 4][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/controls/base.php::73] array_merge(): Expected parameter 2 to be an array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 15:46:22 [warning X 1][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/controls/base.php::73] array_merge(): Expected parameter 2 to be an array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/controls/base.php(73): class type array_merge()
#2: /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/controls/base-data.php(19): Elementor\Base_Control -> __construct()
#3: /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/managers/controls.php(436): Elementor\Base_Data_Control -> __construct()
#4: /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/managers/controls.php(589): Elementor\Controls_Manager -> register_controls()
',
)]
PHP: 2022-03-24 09:04:49 [notice X 1][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Undefined index: openquote [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-25 17:29:37 [error X 1][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/desarrollo.local/public_html/elemendas/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/desarrollo.local/public_html/elemendas/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/desarrollo.local/public_html/elemendas/wp-in [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-25 19:12:23 [warning X 2][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/controls/groups/base.php::260] array_flip(): Can only flip STRING and INTEGER values! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-25 20:00:05 [error X 4][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/managers/controls.php::518] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Manager::register() must be an instance of Elementor\Base_Control, instance of Elemendas_Addons\Group_Control_Highlighter given, called in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elemendas-addons/includes/plugin.php on line 413 and defined in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/managers/controls.php:518
Stack trace:
#0 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elemendas-addons/includes/plugin.php(413): Elementor\Controls_Manager->register()
#1 /var/www/desarrollo.local/public_html/elemendas/wp-includes/class-wp-hook.php(307): Elemendas_Addons\Plugin->register_controls()
#2 /var/www/desarrollo.local/public_html/elemendas/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /var/www/desarrollo.local/public_html/elemendas/wp-includes/plugin.php(474): WP_Hook->do_action()
#4 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/el [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-28 18:40:37 [error X 2][/var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/managers/controls.php::518] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Manager::register() must be an instance of Elementor\Base_Control, instance of Elemendas_Addons\Group_Control_Highlighter given, called in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elemendas-addons/includes/plugin.php on line 386 and defined in /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elementor/includes/managers/controls.php:518
Stack trace:
#0 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/elemendas-addons/includes/plugin.php(386): Elementor\Controls_Manager->register()
#1 /var/www/desarrollo.local/public_html/elemendas/wp-includes/class-wp-hook.php(307): Elemendas_Addons\Plugin->register_controls()
#2 /var/www/desarrollo.local/public_html/elemendas/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /var/www/desarrollo.local/public_html/elemendas/wp-includes/plugin.php(474): WP_Hook->do_action()
#4 /var/www/desarrollo.local/public_html/elemendas/wp-content/plugins/el [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 11 of 11JS: 2022-03-16 20:07:12 [error X 3][http://desarrollo.local/elemendas/wp-includes/js/wp-auth-check.min.js?ver=5.9.2:2:652] h is undefined 
JS: 2022-03-22 16:38:39 [error X 4][http://desarrollo.local/elemendas/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.2:18:50] missing ) after formal parameters 
JS: 2022-03-22 16:56:21 [error X 1][http://desarrollo.local/elemendas/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.2 line 2 > Function:18:2] marks is not defined 
JS: 2022-03-23 10:55:32 [error X 18][http://desarrollo.local/elemendas/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `search-results` got as `quotation_marks` value. Expected array or object.',
)]
JS: 2022-03-23 18:36:15 [error X 2][http://desarrollo.local/elemendas/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.2 line 2 > Function:13:10] data.range is undefined 
JS: 2022-03-23 18:37:39 [error X 1][http://desarrollo.local/elemendas/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.2 line 2 > Function:13:10] data.range.px is undefined 
JS: 2022-03-24 10:12:16 [error X 5][http://desarrollo.local/elemendas/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.2 line 2 > Function:136:1] data.range[unit] is undefined 
JS: 2022-03-24 11:45:42 [error X 4][http://desarrollo.local/elemendas/wp-content/plugins/elemendas-addons/includes/controls/assets/js/QuotationMarks.js?ver=5.9.2:267:13] self.ui.link is undefined 
JS: 2022-03-24 11:50:28 [error X 1][http://desarrollo.local/elemendas/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=5.9.2 line 2 > Function:55:7] allowed_dimensions is not defined 
JS: 2022-03-24 12:03:00 [error X 4][http://desarrollo.local/elemendas/wp-content/plugins/elemendas-addons/includes/controls/assets/js/QuotationMarks.js?ver=5.9.2:73:33] this.getPossibleDimensions is not a function 
JS: 2022-03-25 16:24:30 [error X 1][http://desarrollo.local/elemendas/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.6.0:2:71277] Data commands: `none` not found. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

**Comment by tiatki** [comment]
Is it fixed?

**Comment by sanbec** [comment]
It doesn't look like it, unfortunately they have not taken any notice.

**Comment by tiatki** [comment]
That’s not the reason, they know why , but they just don’t have time or intent to help. You should be calling add_group_control()

**Comment by nicholaszein** [comment]
Hello there,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The methods you're using seem to be missing some key pieces of information.

### ✅ What you can do to solve your issue:

You need to call the class you're trying to extend.

````php
<?php

namespace MyPlugin // Add your plugin namespace here

use Elementor\Group_Control_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class My_Group_Control_Class extends Elementor\Group_Control_Base {...}

````

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
