### ISSUE TITLE
🐞 Bug report: Elementor 3.6 Carousels broken on mobile

### ISSUE THREAD

**Issue by s5t5n** [elementor/elementor#18298]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

All Carousels (legacy elementor widget) (same goes to all Crocoblock widgets with carousel/slider modes) are broken on mobile.

### Steps to reproduce

Add Container widget. Add carousel inside it with 4 images (columns). Switch to mobile view. Broken. Same goes to any carousels by Crocoblock.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 Phusion_Passenger/5.3.7 |  
MySQL version: | Percona Server (GPL), Release 30, Revision 8916819 v5.7.27-30 |  
PHP Version: | 7.4.27 |  
PHP Memory Limit: | 1024M |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 128M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by Abdoo-mayhob** [comment]
I had the same problem with the testimonials carousel, I fixed it by setting the carousel widget width (from advanced tab) to "full width (100%)" on mobile. Give it a try.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.6.2

Feel free to update

Thanks!

**Comment by eknown** [comment]
> I had the same problem with the testimonials carousel, I fixed it by setting the carousel widget width (from advanced tab) to "full width (100%)" on mobile. Give it a try.

Issue hasn't been resolved, but this solution still works
