### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by raj1eev2** [elementor/elementor#18305]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Theme Builder started giving following error message after updating Elementor Pro:
Error: Server error, see Elementor => System Info

### Steps to reproduce

Error: Server error, see Elementor => System Info

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

`
### wp-core ###

version: 5.9.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%category%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 7
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 214.84 MB (225272728 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 997.21 MB (1045654425 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 27.37 MB (28696692 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 2.09 GB (2242697481 bytes)
database_size: 157.50 MB (165150720 bytes)
total_size: 3.45 GB (3707472046 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Hello Elementor Child (hello-theme-child-master)
version: 1.0.1
author: Elementor Team
author_website: https://elementor.com/
parent_theme: Hello Elementor (hello-elementor)
theme_features: core-block-patterns, widgets-block-editor, menus, post-thumbnails, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /var/www/html/wp-content/themes/hello-theme-child-master
auto_update: Disabled

### wp-parent-theme ###

name: Hello Elementor (hello-elementor)
version: 2.4.1 (latest version: 2.5.0)
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
theme_path: /var/www/html/wp-content/themes/hello-elementor
auto_update: Disabled

### wp-themes-inactive (2) ###

PopularFX: version: 1.2.0, author: Pagelayer (latest version: 1.2.3), Auto-updates disabled
Twenty Twenty-Two: version: 1.0, author: the WordPress team (latest version: 1.1), Auto-updates disabled

### wp-mu-plugins (1) ###

Elementor Safe Mode: version: 1.0.0, author: Elementor.com

### wp-plugins-active (20) ###

Advanced Post Queries: version: 1.0.15, author: Shabti Kaplan, Auto-updates disabled
All-in-One WP Migration: version: 6.77, author: ServMask (latest version: 7.57), Auto-updates disabled
All In One WP Security: version: 4.4.9, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy (latest version: 4.4.10), Auto-updates disabled
Code Snippets: version: 2.14.1, author: Code Snippets Pro (latest version: 2.14.3), Auto-updates disabled
Contact Form 7: version: 5.5.6, author: Takayuki Miyoshi, Auto-updates disabled
Contact Form CFDB7: version: 1.2.6.4, author: Arshid, Auto-updates disabled
Elementor: version: 3.7.0-dev2, author: Elementor.com, Auto-updates disabled
Elementor Beta (Developer Edition): version: 1.1.1, author: Elementor.com, Auto-updates disabled
Elementor Header & Footer Builder: version: 1.6.10, author: Brainstorm Force, Nikhil Chavan, Auto-updates disabled
Elementor Pro: version: 3.7.0-dev37, author: Elementor.com, Auto-updates disabled
Enable Media Replace: version: 3.6.3, author: ShortPixel, Auto-updates disabled
Flamingo: version: 2.2.3, author: Takayuki Miyoshi, Auto-updates disabled
Header Footer Code Manager: version: 1.1.20, author: 99robots, Auto-updates disabled
Increase Maximum Upload File Size: version: 2.0.4, author: Imagify, Auto-updates disabled
Members: version: 3.1.7, author: MemberPress, Auto-updates disabled
Premium Addons for Elementor: version: 4.9.4, author: Leap13, Auto-updates disabled
The Plus Addons for Elementor: version: 5.0.8, author: POSIMYTH, Auto-updates disabled
WP File Manager: version: 7.1.2, author: mndpsingh287 (latest version: 7.1.4), Auto-updates disabled
WP Rocket: version: 3.6.1, author: WP Media, Auto-updates disabled
Yoast SEO: version: 18.4.1, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (15) ###

Advanced Database Cleaner: version: 3.0.3, author: Younes JFR. (latest version: 3.0.4), Auto-updates disabled
Asset CleanUp: Page Speed Booster: version: 1.3.8.0, author: Gabe Livan (latest version: 1.3.8.5), Auto-updates disabled
Better Search Replace: version: 1.3.4, author: Delicious Brains, Auto-updates disabled
Flying Images by WP Speed Matters: version: 2.4.13, author: Gijo Varghese, Auto-updates disabled
Form Masks for Elementor: version: 1.6, author: EduardoVillao.me, Auto-updates disabled
Media Cleaner: version: 6.3.2, author: Jordy Meow, Auto-updates disabled
Oasis Workflow: version: 5.9, author: Nugget Solutions Inc., Auto-updates disabled
Plugins Garbage Collector (Database Cleanup): version: 0.12, author: Vladimir Garagulya, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.8.10, author: Pods Framework Team, Auto-updates disabled
Redirection: version: 5.1.3, author: John Godley (latest version: 5.2.3), Auto-updates disabled
Statically: version: 1.2.1, author: Statically, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
WP Force SSL: version: 1.65, author: WebFactory Ltd, Auto-updates disabled
WP Mail Debugger: version: 1.0, author: Timothy Jacobs, Auto-updates disabled
WP Rocket: version: 3.6.1, author: WP Media, Auto-updates disabled

### wp-media ###

image_editor: false
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1500M
upload_max_filesize: 1500M
max_effective_size: 1 GB
max_file_uploads: 20
gd_version: not available
ghostscript_version: 9.07

### wp-server ###

server_architecture: Linux 3.10.0-327.el7.x86_64 x86_64
httpd_software: Apache/2.4.6 (CentOS) PHP/7.2.34
php_version: 7.2.34 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 1024M
max_input_time: 60
upload_max_filesize: 1500M
php_post_max_size: 1500M
curl_version: 7.29.0 NSS/3.19.1 Basic ECC
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.46
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
max_allowed_packet: 4194304
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

**Comment by rami-elementor** [comment]
Hi @raj1eev2 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
