### ISSUE TITLE
🐞 Bug report: error con Reactive pro

### ISSUE THREAD

**Issue by izcdarked** [elementor/elementor#18326]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

estoy trabajando con reactive pro y al editar paginas con elementor y plugin reactive pro, elementor no muestra configuracion de las secciones 

### Steps to reproduce

1)instalar reactive pro
2)instalar elementror
3) editar paginas 
4) agregar codigo de reactive pro en elementor 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 10 v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 5160M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://proyectosappicua.com/paramos
	Home URL: https://proyectosappicua.com/paramos
	WP Multisite: No
	Max Upload Size: 5 GB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es-CO
	Timezone: -5
	Admin Email: pablo@appicua.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es_CO
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.1
		Author: Elementor.com

	Reactive Pro
		Version: 5.0.0
		Author: redqteam

== Must-Use Plugins ==
	akeeba-backup-coreupdate.php
		Version: 
		Author: 

== Uso de los elementos ==
	
	section : 3
		heading : 1
		image-box : 6
		text-editor : 1
	wp-page : 11
		button : 5
		heading : 30
		html : 6
		icon : 1
		image : 21
		image-box : 42
		shortcode : 11
		spacer : 2
		text-editor : 20

<br />
<b>Notice</b>:  Undefined index: title in <b>/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/core/experiments/experiments-reporter.php</b> on line <b>89</b><br />

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Inactivo
	Carga de CSS mejorada: Inactivo
	Fuentes de iconos integradas: Inactivo
	Mejoras de accesibilidad: Inactivo
	Importar o exportar un kit de plantillas: Activo
	Puntos de ruptura personalizados adicionales: Inactivo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo
	: Inactivo por defecto
	Flexbox Container: Inactivo
	Cabecera y pie de página del tema Hello: Inactivo
	Páginas de destino: Inactivo
	Muestrario de colores: Inactivo
	Widgets favoritos: Activo
	Barra superior de administración: Activo

== Registro ==
	
PHP: showing 7 of 7PHP: 2022-02-08 16:42:50 [notice X 3][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-07 11:45:41 [warning X 4][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/reactivepro/app/reactive-helper-functions.php:202) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-07 11:51:04 [warning X 22][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-22 10:22:57 [notice X 71][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-25 20:46:11 [error X 1][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/includes/template-library/sources/local.php::1050] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-includes/class-wp-hook.php on line 309 and defined in /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/includes/template-library/sources/local.php:1050
Stack trace:
#0 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-includes/class-wp-hook.php(309): Elementor\TemplateLibrary\Source_Local->on_save_post(1726, NULL)
#1 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-includes/post.php(4687): do_action('save_post', 1726, NULL, true)
#4 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-includes/post.php(4789): wp_insert_post(Array, false, true)
#5 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/includes/db.php(235): wp_update_post(Array)
#6 /var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/e [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-29 15:31:35 [notice X 276][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] ¡El argumento $control_id está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-31 17:43:04 [notice X 1][/var/www/vhosts/proyectosappicua.com/httpdocs/paramos/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 222022-03-04 21:36:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-04 21:36:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.6',
)]
2022-03-04 21:36:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.6',
)]
2022-03-23 10:41:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 10:41:12 [info] elementor::elementor_updater Started 
2022-03-23 10:41:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 10:41:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 10:41:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-31 17:14:10 [info] elementor::elementor_updater Started 
2022-03-31 17:14:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-31 17:14:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-31 17:14:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-31 17:14:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-31 17:38:21 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2022-03-31 17:38:22 [info] elementor::custom_task_manger Started 
2022-03-31 17:38:22 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2022-03-31 17:38:22 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2022-03-31 17:38:22 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2022-03-31 17:38:22 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2022-03-31 17:38:22 [info] elementor::custom_task_manger Completed 

JS: showing 3 of 3JS: 2022-03-07 20:27:21 [error X 15][https://proyectosappicua.com/paramos/wp-content/plugins/elementor/assets/lib/nouislider/nouislider.min.js?ver=13.0.0:2:4604] noUiSlider (13.0.0): \'start\' option is incorrect. 
JS: 2022-03-07 20:27:37 [error X 10][https://proyectosappicua.com/paramos/wp-admin/js/editor.min.js?ver=5.9.1:2:734] Cannot read properties of undefined (reading \'style\') 
JS: 2022-03-28 16:36:35 [error X 1][https://proyectosappicua.com/paramos/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0:2:363196] Cannot read properties of undefined (reading \'isEditable\') 

== Elementor - Compatibility Tag ==
	

				
![error](https://user-images.githubusercontent.com/102770241/161163496-3630ebd4-828d-4abb-8878-9d73af20cae9.png)

**Comment by rami-elementor** [comment]
Hi @izcdarked

Please create a new bug report in English.
