### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by AffinitoLit** [elementor/elementor#18323]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I updated to the most recent version of Elementor this week, all of my blog posts in the body of my site reduced to half size. I reverted back to the original version and it works fine, but I'd like to be able to update without changing the layout of my posts.. 

### Steps to reproduce

Update to newest version of Elementor. 
Check body posts. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://www.alitlife.com
	Home URL: https://www.alitlife.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: stephanieaffinito@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Jenifer
	Version: 1.0
	Author: WAT Design Express
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 3.3.5
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36

== Active Plugins ==
	Blogger Importer
		Version: 0.9
		Author: wordpressdotorg

	Bluehost
		Version: 2.9.0
		Author: Bluehost

	Creative Mail by Constant Contact
		Version: 1.5.1
		Author: Constant Contact

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Genesis Connect for WooCommerce
		Version: 1.1.1
		Author: StudioPress

	Genesis eNews Extended
		Version: 2.2.0
		Author: Brandon Kraft

	Genesis Featured Page Advanced
		Version: 1.9.9
		Author: Nick Diego

	Genesis Portfolio Pro
		Version: 1.2.3
		Author: StudioPress

	Google Analytics for WordPress by MonsterInsights
		Version: 8.4.0
		Author: MonsterInsights

	Jetpack
		Version: 10.7
		Author: Automattic

	jQuery Pin It Button for Images
		Version: 3.0.6
		Author: Marcin Skrzypiec

	Ninja Forms
		Version: 3.6.9
		Author: Saturday Drive

	One Click Demo Import
		Version: 3.1.1
		Author: OCDI

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Simple Social Icons
		Version: 3.0.2
		Author: StudioPress

	Smash Balloon Instagram Feed
		Version: 6.0.4
		Author: Smash Balloon

	UpdraftPlus - Backup/Restore
		Version: 1.22.11
		Author: UpdraftPlus.Com, DavidAnderson

	Widget Importer & Exporter
		Version: 1.6
		Author: ChurchThemes.com

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP Font Awesome
		Version: 1.7.8
		Author: Zayed Baloch

	WPForms Lite
		Version: 1.7.3
		Author: WPForms

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 2 of 2PHP: 2021-07-13 12:33:25 [error X 1][/home1/alitlife/public_html/wp-content/plugins/elementor/core/document-types/post.php::8] Class Elementor\Core\DocumentTypes\Post contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Elementor\Controls_Stack::get_name) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-05 16:11:09 [notice X 1][/home1/alitlife/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 312021-08-16 20:19:50 [info] elementor::elementor_updater Started 
2021-08-16 20:19:50 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-16 20:19:52 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-16 20:19:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.3.1',
  'to' => '3.4.0',
)]
2021-08-18 20:54:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-18 20:54:53 [info] elementor::elementor_updater Started 
2021-08-18 20:54:53 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-18 20:54:54 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-18 20:54:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-19 20:31:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-08-19 20:31:07 [info] elementor::elementor_updater Started 
2021-08-19 20:31:07 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-19 20:31:08 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-19 20:31:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-08-30 08:22:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-30 08:22:14 [info] elementor::elementor_updater Started 
2021-08-30 08:22:14 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-30 08:22:16 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-30 08:22:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-30 08:22:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]

JS: showing 2 of 2JS: 2022-01-25 16:45:30 [error X 6][https://www.alitlife.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.4:2:5069] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-01-27 17:17:59 [error X 2][https://www.alitlife.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:348732] elementorFrontend.elements.window.jQuery is not a function 

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @AffinitoLit ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by rami-elementor** [comment]
@AffinitoLit Please understand that we need more information the debug the issue. With steps to reproduce the issue in a clean environment without external plugins that can cause the problem.
