### ISSUE TITLE
🐞 Bug report: Gravity Forms and Sizzify Addons currently Incompatible.

### ISSUE THREAD

**Issue by Ephremjlm** [elementor/elementor#18333]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

On our test website we have found that the latest version of Elementor has compatibility issues with two plugins. Information below.

Elementor 3.6.1
Elementor Pro 3.6.4
Theme Twentyseventeen 2.9
Wordpress 5.9.2

Plugins that break the site - 
Elementor Addons & Templates - Sizzify Lite 1.3.2
Gravity Forms Styler for Elementor 1.0.0

Gravity Forms Styler is currently incompatible with 3.6.1 and just strait up breaks the site.
Elementor Addons from Sizzify doesn't break the site right away but for some reason breaks it later. I tested this and it was the plugin that gave my site a broken error. 

### Steps to reproduce

Activate "Elementor Addons & Templates - Sizzify Lite 1.3.2" and "Gravity Forms Styler for Elementor 1.0.0" with Elementor 3.6.1 activated. This is regardless of having Elementor Pro active. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.28
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://www.chapmanlawgroupdummy.com
	Home URL: https://www.chapmanlawgroupdummy.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: emolina@chapmanlawgroup.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 2.9
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	CLG Functionality
		Version: 1.0.0
		Author: Egoy Magnaye

	Cloudflare
		Version: 4.8.3
		Author: Cloudflare, Inc.

	Custom Post Type UI
		Version: 1.11.2
		Author: WebDevStudios

	Duplicate Page and Post
		Version: 2.7
		Author: Arjun Thakur

	Easy Social Share Buttons for WordPress
		Version: 8.3
		Author: CreoApps

	Elementor
		Version: 3.6.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.3
		Author: ShortPixel

	G-Forms hCaptcha
		Version: 1.2.3
		Author: Web & App Easy B.V.

	Google Tag Manager for Wordpress
		Version: 1.14.2
		Author: Thomas Geiger

	Google XML Sitemaps
		Version: 4.1.1
		Author: Auctollo

	Gravity Forms
		Version: 2.6.1
		Author: Gravity Forms

	Gravity Forms Email Blacklist
		Version: 2.5
		Author: hallme

	Gravity Forms Mailchimp Add-On
		Version: 5.0
		Author: Gravity Forms

	Image Hover Effects - Elementor Addon
		Version: 1.3.5
		Author: Blocksera

	LayerSlider
		Version: 7.1.4
		Author: Kreatura Media

	Livemesh Addons for Elementor
		Version: 7.1.6
		Author: Livemesh

	NitroPack
		Version: 1.5.9
		Author: NitroPack LLC

	Redirection
		Version: 5.2.3
		Author: John Godley

	Simple Custom CSS and JS
		Version: 3.39
		Author: SilkyPress.com

	Theme My Login
		Version: 7.1.4
		Author: Theme My Login

	UpdraftPlus - Backup/Restore
		Version: 2.22.11.1
		Author: UpdraftPlus.Com, DavidAnderson

	User Profile Picture
		Version: 2.6.0
		Author: Cozmoslabs

	WP Revisions Control
		Version: 1.3
		Author: Erick Hitter

	Yoast SEO
		Version: 18.4.1
		Author: Team Yoast

== Elements Usage ==
	
	page : 541
		divider : 8
		image : 8
		text-editor : 16
	wp-post : 187
		button : 72
		call-to-action : 66
		divider : 138
		heading : 995
		html : 5
		icon-list : 212
		image : 53
		posts : 223
		reviews : 1
		search-form : 25
		slides : 1
		social-share-display : 87
		spacer : 73
		template : 127
		text-editor : 326
		theme-post-title : 25
		video : 18
		wp-widget-archives : 25
		wp-widget-categories : 25
		wp-widget-recent-posts : 25
	wp-page : 32
		button : 2
		divider : 4
		heading : 17
		image : 4
		spacer : 4
		template : 4
		text-editor : 24
		video : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 4 of 4JS: 2022-02-03 20:38:50 [error X 2][https://www.chapmanlawgroup.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453830] T is null 
JS: 2022-02-22 16:36:42 [error X 19][https://www.chapmanlawgroup.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.5:2:222546] L is undefined 
JS: 2022-02-22 18:16:49 [error X 73][https://www.chapmanlawgroup.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.5:2:222547] Cannot read property \'global\' of undefined 
JS: 2022-03-07 16:29:03 [error X 8][https://www.chapmanlawgroup.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.5.6:2:222546] Cannot read properties of undefined (reading \'global\') 

PHP: showing 4 of 4PHP: 2022-02-09 11:39:55 [notice X 5][/home/customer/www/chapmanlawgroup.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-30 11:20:46 [error X 12][/home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-gravity-forms/includes/gravity-form.php::551] Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-gravity-forms/includes/gravity-form.php:551
Stack trace:
#0 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Widget_Eael_Gravity_Form_Stand_Alone->_register_controls()
#1 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls()
#2 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#3 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack()
#4 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2369): [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-30 11:21:24 [error X 13][/home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-gravity-forms/includes/gravity-form.php::551] Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-gravity-forms/includes/gravity-form.php:551
Stack trace:
#0 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Widget_Eael_Gravity_Form_Stand_Alone->_register_controls()
#1 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls()
#2 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#3 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack()
#4 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/core/files/css/global-css.php(120): Ele [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-30 12:46:46 [error X 167][/home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php::895] Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php:895
Stack trace:
#0 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php(153): ThemeIsle\ElementorExtraWidgets\Posts_Grid->grid_title_style_section()
#1 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): ThemeIsle\ElementorExtraWidgets\Posts_Grid->_register_controls()
#2 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls()
#3 /home/customer/www/chapmanlawgroupdummy.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_st [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 342022-03-06 21:51:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-06 21:51:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-06 21:51:40 [info] elementor::elementor_updater Started 
2022-03-06 21:51:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-06 21:51:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-06 21:51:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-06 21:51:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-30 11:20:46 [info] elementor::elementor_updater Started 
2022-03-30 11:20:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-30 11:20:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.1',
)]
2022-03-30 11:21:12 [info] elementor-pro::elementor_pro_updater Started 
2022-03-30 11:21:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-30 11:21:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-30 11:21:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-30 11:25:56 [info] elementor::elementor_updater Started 
2022-03-30 11:25:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-30 11:32:08 [info] elementor::elementor_updater Started 
2022-03-30 11:32:08 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-30 11:32:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-30 11:32:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Image Hover Effects - Elementor Addon: Compatibility not specified
	Livemesh Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @Ephremjlm 

Yu need to contact the plugin developers to fix compatibility with Elementor.

They need to check if their plugin works with the latest version of Elementor and update the "Compatibility Tag".

More info at https://developers.elementor.com/docs/addons/compatibility/

**Comment by rami-elementor** [comment]
Hi @Ephremjlm 

Yu need to contact the plugin developers to fix compatibility with Elementor.

They need to check if their plugin works with the latest version of Elementor and update the "Compatibility Tag".

More info at https://developers.elementor.com/docs/addons/compatibility/

**Comment by rami-elementor** [comment]
Hi @Ephremjlm 

Yu need to contact the plugin developers to fix compatibility with Elementor.

They need to check if their plugin works with the latest version of Elementor and update the "Compatibility Tag".

More info at https://developers.elementor.com/docs/addons/compatibility/

**Comment by rami-elementor** [comment]
Sorry @Ephremjlm, wrong link...

Read this one https://developers.elementor.com/docs/addons/plugin-header/
