### ISSUE TITLE
Image and icon size in viewports

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#1833]
Hello! When using svg, WP image sizes not working and it's one way to set size is the style tab. But the size is universal for all viewports that's not right. The same situation with icon widget.

Make size changing for all viewports please!

Thanks!

**Comment by pingram3541** [comment]
same as https://github.com/pojome/elementor/issues/1410

**Comment by alexnl** [comment]
Size of an SVG cannot be adjusted via custom width or height input either.

**Comment by parfilov** [comment]
@alexnl did you tried to set image size Full?

**Comment by alexnl** [comment]
@parfilov Yes, I tried full size, large, medium and custom sizes.

# Full
![image](https://user-images.githubusercontent.com/317587/42323793-5c93baca-802f-11e8-8d98-41fad297a0a9.png)

# Large
![image](https://user-images.githubusercontent.com/317587/42323813-6a14fbaa-802f-11e8-821e-d440faf0811a.png)

# Medium
![image](https://user-images.githubusercontent.com/317587/42323826-78d38f1c-802f-11e8-9e7d-5c4902e2eac7.png)

# Custom
![image](https://user-images.githubusercontent.com/317587/42323847-85fba3a0-802f-11e8-9e8f-029aa609b8bd.png)

# My solution was to add custom css to the image which worked:
![image](https://user-images.githubusercontent.com/317587/42323917-b1a5fb9a-802f-11e8-8f01-8c9a44488a72.png)

**Comment by parfilov** [comment]
@alexnl try to set Image Size — Full on the Content tab and then try to change Width on the Style tab. It works for me.

**Comment by alexnl** [comment]
Thanks! That worked. But in this case I want to base the size on a specific height and have the width automatic. 
In the future, I will use your method. I have included a screenshot here for anyone else finding this issue.

![image](https://user-images.githubusercontent.com/317587/42336811-cf284358-8052-11e8-8dfc-ad9d0b93ef61.png)

**Comment by shilo-ey** [comment]
Hey all,

This feature has been added to Elementor in it's latest versions, Feel free to update.

Thanks
