### ISSUE TITLE
🐞 Bug report: Auto margin becomes 0 after save

### ISSUE THREAD

**Issue by Stas0238** [elementor/elementor#18335]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,
I have found a bug with dimentions control after saving 
describe the issue in next steps below 

### Steps to reproduce

1/ Open any post/page editor with Elementor plugin
2/ Add section or edit existing one 
3/ Go to Advanced Section of section options
4/ Set Margin (top/bottom) values to any you want to -> http://prntscr.com/D4lNmxJAp0w8
5/ Save page/post 
6/ Refresh editor 
7/ Go to the section you edited before
8/ Go to Advanced Section of section options
9/ Margin is now set to your value(top) 0 your value (bottom) 0 -> http://prntscr.com/UEr6XGfYPtBa

Comparing -> 
before -> http://prntscr.com/u-6-Yxr9sl-q
after -> http://prntscr.com/UEr6XGfYPtBa

Regards, @stas0238

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

I would like to keep it in private for myself - there are allota info i don't want to share

**Comment by rami-elementor** [comment]
Hi @Stas0238 

It's not a bug, it by design. We had this behavior since the first version of Elementor.
