### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by justingourley** [elementor/elementor#18344]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Elementor form does not have an "already subscribed" integration with Aweber. If a user signs up for an email list, but they are already on that list, there's no way to redirect them to an "already subscribed" page. There is also no way to track that this behavior is NOT a conversion. As a result, using google analytics (or other tracking services) will inflate the number of conversions for each already subscribed user who subscribes again.

### Describe the solution you'd like

In the Aweber form integration, add an "already subscribed" feature which will allow either a popup or a new page to be navigated to.

### Describe alternatives you've considered

None

### Additional context

NA

**Comment by rami-elementor** [comment]
Hi @justingourley ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being.

Please feel free to contact us again with other feature suggestions.

Regards,
