### ISSUE TITLE
W3 Validate: Section lacks heading

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#18355]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello team,

Your plugin rasing html validate warning on https://validator.w3.org/

Warning: Section lacks heading. Consider using h2-h6 elements to [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing), or else use a div element instead for any cases where no heading is needed.

Could you please add filter to change default Tag HTML from **section** to **div**?

![Screenshot at Apr 05 11-33-30](https://user-images.githubusercontent.com/7134267/161679629-4fed7d93-ce3b-4f3e-9288-9c73ee30ee33.png)

### Steps to reproduce

1. Edit any page then create some Sections
2. Go to https://validator.w3.org/ enter the page url
3. Hit to "Check" button

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.13.6
	MySQL version: mariadb.org binary distribution v5.7.24
	PHP Version: 7.2.12
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

**Comment by rami-elementor** [comment]
Hi @steve231293 ,

To solve the HTML validation, you need to create a new section/column and add new H1-H6 headings to that section.

Elementor won't force additional headings, you need to create your own HTML structure using dedicated widgets.

**Comment by steve231293** [comment]
Hello @udidol ,
Could you please review to add filter to change default Tag HTML? Please see my attachment
Something like this:
`$html_tag = apply_filters('elementor/element/section/default_html_tag', 'section')`

**Comment by udidol** [comment]
@steve231293 There is a control that lets you select the tag type, between: `div`, `header`, `footer`, `main`, `article`, `section`, `aside`, `nav`.
