### ISSUE TITLE
🐞 Bug report: Elementor Pro 3.6.4 Preview cannot be loaded 

### ISSUE THREAD

**Issue by HemersonPimenta** [elementor/elementor#18362]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Pro 3.6.4 Preview cannot be loaded 

When I enter popups to create a new one and proceed to edit with the element, the error occurs: Preview cannot be loaded.

It's been like this for 2 days now. I've tried Elementor support, I've searched the internet, I've watched tutorials, but none worked.

### Steps to reproduce

1°) Go to templates and select popups.

2°) create a popup.

From there, before editing with Elementor, the error appears.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>
<h3 class="wp-heading-inline" style="display: block; font-weight: 600; color: rgb(29, 35, 39); font-size: 1.3em; margin: 1em 0px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Informações do sistema</h3><div style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23 |  
PHP Version: | 8.1.4 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 516M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div></div><h3 style="display: block; font-weight: 600; color: rgb(29, 35, 39); font-size: 1.3em; margin: 1em 0px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Informações para cortar e colar</h3><div id="elementor-system-info-raw" style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><label id="elementor-system-info-raw-code-label" for="elementor-system-info-raw-code" style="cursor: pointer; vertical-align: middle; padding: 5px; display: block;">Pode copiar as informações em texto simples da caixa abaixo com Ctrl+C / Ctrl+V:</label><textarea id="elementor-system-info-raw-code" readonly="" style="box-sizing: border-box; font-family: inherit; font-size: 14px; font-weight: inherit; overflow: auto; padding: 2px 6px; line-height: 1.42857; resize: vertical; box-shadow: transparent 0px 0px 0px; border-radius: 4px; border: 1px solid rgb(140, 143, 148); background-color: rgb(240, 240, 241); color: rgb(44, 51, 56); width: 1100px; height: 200px;"></textarea></div>
</body>
</html>Informações do sistema
Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23	
PHP Version:	8.1.4	
PHP Memory Limit:	512M	
PHP Max Input Vars:	10000	
PHP Max Post Size:	516M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	5.9.2	
Site URL:	https://hemersonpimenta.com	
Home URL:	https://hemersonpimenta.com	
WP Multisite:	No	
Max Upload Size:	512 MB	
Memory limit:	40M	
Max Memory limit:	256M	
Permalink Structure:	/%year%/%monthnum%/%day%/%postname%/	
Language:	pt-PT	
Timezone:	0	
Admin Email:	Hemersomneves548@gmail.com	
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	2.5.0	
Author:	Elementor Team	
Child Theme:	No	Se quiser modificar o código fonte do seu tema, recomendamos a utilização de um [tema dependente](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	pt_PT	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36 OPR/84.0.4316.52	
Active Plugins		
[ActiveCampaign](http://www.activecampaign.com/apps/wordpress) - 8.1.9	By [ActiveCampaign](http://www.activecampaign.com/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.6.2	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.6.4	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[Split Test For Elementor](https://wordpress.org/plugins/split-test-for-elementor/) - 1.5.1	By [Rocket Elements](https://www.rocketelements.io/)	
Elements Usage[Recalculate](https://hemersonpimenta.com/wp-admin/admin.php?page=elementor-system-info&elementor_usage_recalc=1&_wpnonce=e1365a403e#elementor-usage-recalc)		
Página ( 6 )	Botão: 8
Editor de texto: 14
Espaçador: 5
HTML: 2
Imagem: 12
Lista de ícones: 1
Mostrar/esconder: 1
Nav Menu: 1
Título: 26
Vídeo: 6
Library - Página ( 7 )	Botão: 5
Editor de texto: 12
Espaçador: 1
HTML: 1
Imagem: 6
Lista de ícones: 2
Mostrar/esconder: 1
Nav Menu: 1
Título: 31
Vídeo: 6
Ícone: 6
Elementor Experiments		
Optimized DOM Output: 	Active by default
Improved Asset Loading: 	Active
Improved CSS Loading: 	Active by default
Inline Font Icons: 	Inactive by default
Accessibility Improvements: 	Active by default
Import Export Template Kit: 	Active by default
Additional Custom Breakpoints: 	Active by default
Hide native WordPress widgets from search results: 	Active by default
: 	Inactive by default
Flexbox Container: 	Inactive by default
Default to New Theme Builder: 	Active by default
Hello Theme Header & Footer: 	Active by default
Landing Pages: 	Active by default
Color Sampler: 	Active by default
Favorite Widgets: 	Active by default
Admin Top Bar: 	Active by default
Page Transitions: 	Active by default
Form Submissions: 	Active by default
Scroll Snap: 	Active by default
Log[Limpar registo](https://hemersonpimenta.com/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=f8cce2f5b0#elementor-clear-log)		
PHP: showing 8 of 8
PHP: 2021-12-15 22:56:51 [error X 4][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func(Array, Array)
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /home3/hemers28/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Mo [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-15 23:05:27 [error X 4][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func(Array, Array)
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /home3/hemers28/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#6 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /home3/hemers28/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /home3/hemers28/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-26 00:34:05 [notice X 3][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-26 01:32:26 [notice X 8][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-27 23:54:51 [error X 2][/home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor\Modules\System_Info\Module->create_reporter(Array)
#5 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/tracker.php(228): Elementor\Modules [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-21 06:57:33 [error X 1][/home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(303): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home3/hemers28/publi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 00:58:44 [error X 5][/home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home3/hemers28/publi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-03 14:17:38 [notice X 2][/home3/hemers28/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
Log: showing 20 of 20
2022-01-11 08:51:18 [info] elementor::elementor_updater Started 
2022-01-11 08:51:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-11 08:51:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-11 08:51:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.3',
)]
2022-01-11 08:51:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.3',
)]
2022-04-03 13:57:43 [info] elementor-pro::elementor_pro_updater Started 
2022-04-03 13:57:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-03 13:57:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-03 13:57:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.4',
)]
2022-04-03 13:57:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.4',
)]
2022-04-03 13:57:49 [info] elementor::elementor_updater Started 
2022-04-03 13:57:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-03 13:57:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-03 13:57:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.6.1',
)]
2022-04-03 13:57:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.6.1',
)]
2022-04-05 13:14:09 [info] elementor::elementor_updater Started 
2022-04-05 13:14:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 13:14:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 13:14:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-05 13:14:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
Elementor - Compatibility Tag		
 Elementor Pro 	 Compatible 
 Split Test For Elementor 	 Compatible 
Elementor Pro - Compatibility Tag		
 Split Test For Elementor 	 Compatible 
Informações para cortar e colar
Pode copiar as informações em texto simples da caixa abaixo com Ctrl+C / Ctrl+V:
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.1.4
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://hemersonpimenta.com
	Home URL: https://hemersonpimenta.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: pt-PT
	Timezone: 0
	Admin Email: Hemersomneves548@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36 OPR/84.0.4316.52

== Active Plugins ==
	ActiveCampaign
		Version: 8.1.9
		Author: ActiveCampaign

	Elementor
		Version: 3.6.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Split Test For Elementor
		Version: 1.5.1
		Author: Rocket Elements

== Elements Usage ==
	
	page : 7
		button : 5
		heading : 31
		html : 1
		icon : 6
		icon-list : 2
		image : 6
		nav-menu : 1
		spacer : 1
		text-editor : 12
		toggle : 1
		video : 6
	wp-page : 6
		button : 8
		heading : 26
		html : 2
		icon-list : 1
		image : 12
		nav-menu : 1
		spacer : 5
		text-editor : 14
		toggle : 1
		video : 6

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 8 of 8PHP: 2021-12-15 22:56:51 [error X 4][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func(Array, Array)
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /home3/hemers28/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Mo [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-15 23:05:27 [error X 4][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(550): call_user_func(Array, Array)
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/template-library/manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 /home3/hemers28/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#6 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#7 /home3/hemers28/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /home3/hemers28/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-26 00:34:05 [notice X 3][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-26 01:32:26 [notice X 8][/home3/hemers28/public_html/wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-27 23:54:51 [error X 2][/home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php(36): Elementor\Core\Wp_Api->get_plugins()
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(44): Elementor\Core\Wp_Api->get_active_plugins()
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/reporters/plugins.php(75): Elementor\Modules\System_Info\Reporters\Plugins->get_plugins()
#3 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/module.php(298): Elementor\Modules\System_Info\Reporters\Plugins->is_enabled()
#4 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/system-info/module.php(255): Elementor\Modules\System_Info\Module->create_reporter(Array)
#5 /home3/hemers28/public_html/wp-content/plugins/elementor/includes/tracker.php(228): Elementor\Modules [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-21 06:57:33 [error X 1][/home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(303): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home3/hemers28/publi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-29 00:58:44 [error X 5][/home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home3/hemers28/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home3/hemers28/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home3/hemers28/public_html/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home3/hemers28/publi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-03 14:17:38 [notice X 2][/home3/hemers28/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 202022-01-11 08:51:18 [info] elementor::elementor_updater Started 
2022-01-11 08:51:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-11 08:51:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-11 08:51:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.3',
)]
2022-01-11 08:51:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.0',
  'to' => '3.5.3',
)]
2022-04-03 13:57:43 [info] elementor-pro::elementor_pro_updater Started 
2022-04-03 13:57:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-03 13:57:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-03 13:57:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.4',
)]
2022-04-03 13:57:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.4',
)]
2022-04-03 13:57:49 [info] elementor::elementor_updater Started 
2022-04-03 13:57:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-03 13:57:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-03 13:57:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.6.1',
)]
2022-04-03 13:57:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.6.1',
)]
2022-04-05 13:14:09 [info] elementor::elementor_updater Started 
2022-04-05 13:14:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 13:14:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 13:14:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-05 13:14:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Split Test For Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Split Test For Elementor: Compatible

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
