### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Maetta** [elementor/elementor#18369]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Hello, I hope this is the right place to report this issue. The new update gives me a fatal error, so I am still stuck to the previous version. I have Elementor basic. I attach here the screenshot of the issue, it makes my website impossible to see.
<img width="848" alt="Screenshot 2022-04-06 at 09 15 50" src="https://user-images.githubusercontent.com/103101508/161918790-40a4d944-d617-489f-9ed3-2b3767916b4d.png">
.

### Steps to reproduce

Update Elementor to the new version.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.28
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://emanuelamaeagrini.art
	Home URL: https://emanuelamaeagrini.art
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 1
	Admin Email: emanuela.agrini@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Ozark
	Version: 1.1
	Author: GradaStudio
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.1
		Author: Delicious Brains

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	Black Studio TinyMCE Widget
		Version: 2.7.0
		Author: Black Studio

	CoBlocks
		Version: 2.22.9
		Author: GoDaddy

	Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd
		Version: 6.10.0
		Author: SeedProd

	Contact Form 7
		Version: 5.5.6
		Author: Takayuki Miyoshi

	Cookie and Consent Solution for the GDPR & ePrivacy
		Version: 2.5.91
		Author: iubenda

	Disk Usage Sunburst
		Version: 1.1.3
		Author: raidboxes.io

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 8.5.0
		Author: MonsterInsights

	Jetpack
		Version: 10.8
		Author: Automattic

	MainWP Child
		Version: 4.2
		Author: MainWP

	Ozark Plugin
		Version: 1.1
		Author: GradaStudio

	Portfolio Post Type
		Version: 1.0.1
		Author: Devin Price

	Rank Math SEO
		Version: 1.0.85.1
		Author: Rank Math

	Shortcodes Ultimate
		Version: 5.12.0
		Author: Vladimir Anokhin

	Simple Custom CSS
		Version: 4.0.5
		Author: John Regan

	SiteGround Optimizer
		Version: 7.0.7
		Author: SiteGround

	SiteGround Security
		Version: 1.2.4
		Author: SiteGround

	Smush
		Version: 3.9.5
		Author: WPMU DEV

	UpdraftPlus - Backup/Restore
		Version: 1.22.11
		Author: UpdraftPlus.Com, DavidAnderson

== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attivo per impostazione predefinita
	Caricamento delle risorse migliorato: Attivo per impostazione predefinita
	Caricamento CSS migliorato: Inattivo per impostazione predefinita
	Icone dei font in linea: Inattivo per impostazione predefinita
	Miglioramenti dell'accessibilità: Attivo per impostazione predefinita
	Importa un kit modello esportato: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Inattivo per impostazione predefinita
	Nascondi i widget nativi di WordPress dai risultati di ricerca: Attivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Campionatore di colori: Attivo per impostazione predefinita
	Widget preferiti: Attivo per impostazione predefinita
	Barra superiore dell'amministratore: Attivo per impostazione predefinita

== Registro ==
	
Log: showing 20 of 412022-03-01 09:38:10 [info] elementor::elementor_updater Started 
2022-03-01 09:38:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-01 09:38:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 09:38:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 09:38:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-23 09:19:49 [info] elementor::elementor_updater Started 
2022-03-23 09:19:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 09:19:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 09:19:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 09:19:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-25 10:02:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-25 10:02:50 [info] elementor::elementor_updater Started 
2022-03-25 10:02:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-25 10:02:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-25 10:02:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-04-06 02:34:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 02:34:56 [info] elementor::elementor_updater Started 
2022-04-06 02:34:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 02:34:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 02:34:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]

PHP: showing 1 of 1PHP: 2022-03-23 09:39:12 [notice X 103][/home/customer/www/emanuelamaeagrini.art/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1511] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @Maetta ,

From the screenshot I see that the issues is in the "Ozark Plugin". I that they use classes deprecated in Elementor 2.8 and deleted in Elementor 3.6.

When Elementor [deprecates code](https://developers.elementor.com/docs/deprecations/), addon developers have 8 versions to update to new code until we delete the old code.

In your case, it’s a simple fix, the Ozark Plugin developer simply need to rename the “scheme” classes as mentioned in our [3.6 deprecation post](https://developers.elementor.com/v3-6-planned-deprecations/). You should contact the addon developer, or loo for an alternative. Meanwhile, deactivating the plugins should fix the issue.

In any case, I'm closing this ticket as it's not an Elementor bug, and there is nothing to fix in Elementor.

**Comment by Maetta** [comment]
Thank you so much and sorry I didn't know this needed to be fixed by the them dev. I will contact them, thanks for the patience and for telling me this! @rami-elementor
