### ISSUE TITLE
When loading my loop template into the post template it's not acting responsively 

### ISSUE THREAD

**Issue by Fjashaw** [elementor/elementor#18379]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

This is how I have styled my testimonial template to display on mobile:
![Screen Shot 2022-04-07 at 11 07 28 AM](https://user-images.githubusercontent.com/90364747/162087808-66ea273f-45bd-4037-8ccb-93982210c364.png)

This is how it is displaying on mobile when loaded into the post widget (which is how it is set up for desktop):
![Screen Shot 2022-04-07 at 11 08 08 AM](https://user-images.githubusercontent.com/90364747/162088177-79e1a349-1161-4a7d-bd65-ae279f8da375.png)

### Steps to reproduce

Create a loop template
Load into a post template

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.36
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://sheenajayne.co.nz
	Home URL: https://sheenajayne.co.nz
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 300M
	Max Memory limit: 300M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hello@whitelightstudio.co.nz
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.7.9
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.2
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.11.2
		Author: WebDevStudios

	Ele Custom Skin
		Version: 3.1.5
		Author: Dudaster.com

	Elementor
		Version: 3.7.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev41
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.3
		Author: Crocoblock

	JetEngine
		Version: 2.11.6
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.16
		Author: Crocoblock

	JetTricks
		Version: 1.4.1
		Author: Crocoblock

	MailPoet 3 (New)
		Version: 3.86.0
		Author: MailPoet

	PowerPack Pro for Elementor
		Version: 2.8.1
		Author: Team IdeaBox - PowerPack Elements

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	Sticky Header Effects for Elementor
		Version: 1.4.7
		Author: Rwattner

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.9
		Author: Unlimited Elements

	User Role Editor
		Version: 4.61.2
		Author: Vladimir Garagulya

== Elements Usage ==
	
	container : 4
		accordion : 1
		button : 1
		container : 17
		image : 2
		posts : 1
		text-editor : 13
	footer : 1
		container : 12
		divider : 1
		form : 1
		text-editor : 11
	header : 2
		container : 8
		image : 6
		nav-menu : 1
	loop : 10
		accordion : 7
		button : 21
		container : 88
		image : 1
		jet-headline : 6
		jet-unfold : 1
		spacer : 1
		text-editor : 99
	page : 3
		button : 1
		container : 29
		icon : 1
		image : 9
		spacer : 8
		template : 1
		text-editor : 24
	popup : 1
		button : 1
		form : 1
		text-editor : 1
	section : 2
		image : 2
	wp-page : 7
		accordion : 4
		button : 6
		container : 218
		divider : 1
		form : 1
		html : 3
		image : 21
		posts : 8
		spacer : 5
		text-editor : 72

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active
	Notes: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 272022-03-31 08:53:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-31 08:53:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-31 08:53:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev35',
  'to' => '3.7.0-dev37',
)]
2022-03-31 08:53:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev35',
  'to' => '3.7.0-dev37',
)]
2022-04-05 11:43:08 [info] elementor-pro::elementor_pro_updater Started 
2022-04-05 11:43:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-05 11:43:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-05 11:43:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev37',
  'to' => '3.7.0-dev40',
)]
2022-04-05 11:43:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev37',
  'to' => '3.7.0-dev40',
)]
2022-04-06 01:54:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev2',
  'to' => '3.7.0-dev3',
)]
2022-04-06 01:54:50 [info] elementor::elementor_updater Started 
2022-04-06 01:54:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 01:54:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 01:54:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev2',
  'to' => '3.7.0-dev3',
)]
2022-04-06 21:17:40 [info] elementor-pro::elementor_pro_updater Started 
2022-04-06 21:17:40 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-06 21:17:40 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-06 21:17:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev40',
  'to' => '3.7.0-dev41',
)]
2022-04-06 21:17:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev40',
  'to' => '3.7.0-dev41',
)]
2022-04-06 21:17:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev40',
  'to' => '3.7.0-dev41',
)]

JS: showing 3 of 3JS: 2022-03-31 09:05:30 [error X 1][http://sheenajayneclone2.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev2:2:238164] Cannot read properties of undefined (reading \'id\') 
JS: 2022-04-02 03:25:31 [error X 3][http://sheenajayneclone2.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev2:2:534289] this.manager.setPage(\"elements\",null,T).showView is not a function. (In \'this.manager.setPage(\"elements\",null,T).showView(C)\', \'this.manager.setPage(\"elements\",null,T).showView\' is undefined) 
JS: 2022-04-06 04:48:09 [error X 2][https://sheenajayne.co.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev3:2:607670] Cannot read properties of undefined (reading \'localized\') 

PHP: showing 12 of 12PHP: 2022-04-05 07:29:39 [warning X 1][/www/wp-content/plugins/elementor/core/files/uploads-manager.php::257] unlink(/www/wp-content/plugins/unlimited-elements-for-elementor/cache/import/single_layout/layout_1_iw704md1he/elementor-327-2022-04-05.json): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 01:54:53 [notice X 375][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 38][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(247): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 38][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(285): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 37][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 38][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 20][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 20][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 20][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 01:55:53 [notice X 20][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /www/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-06 03:10:26 [notice X 7][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 21:17:01 [error X 1][/www/wp-content/plugins/elementor-pro/plugin.php::431] Uncaught Error: Class 'ElementorPro\License\Admin' not found in /www/wp-content/plugins/elementor-pro/plugin.php:431
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/plugin.php(108): ElementorPro\Plugin->__construct()
#1 /www/wp-content/plugins/elementor-pro/plugin.php(446): ElementorPro\Plugin::instance()
#2 /www/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/www/wp-content...')
#3 /wordpress/wp-includes/class-wp-hook.php(307): elementor_pro_load_plugin('')
#4 /wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /wordpress/wp-settings.php(453): do_action('plugins_loaded')
#7 /www/wp-config.php(110): require_once('/wordpress/wp-s...')
#8 /wordpress/wp-config.php(5): require('/www/wp-config....')
#9 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#10 /wordpress/wp-admin/admin-ajax.php(22): require_once('/wordpress/wp-l...')
#11 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	PowerPack Pro for Elementor: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @Fjashaw 

Elementor has no "loop templates". It sounds like it's an addon issue.

I think you should contact the developers of "Ele Custom Skin".

**Comment by aureliePrd** [comment]
Hi, 
I'm having a similar issue for a while with "section" template. Just created it here : #18412

**Comment by BaronVonDerpsalot** [comment]
Sounds almost exactly the same as this issue, which involves any and all single templates with custom breakpoints. 
https://github.com/elementor/elementor/issues/16819
After lengthy talks with tier 2 support, after tier 1 support constantly told me it "sounded like an addon issue" and "Perhaps I should talk with them" it turns out this is an Elementor issue.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core 3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
