### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by smartfoxes** [elementor/elementor#18378]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After upgrade from 3.5 to latest 3.6 
"Exapand Column Background" stopped working

Columns are not expanded to full page width as it used to be in previous version

### Steps to reproduce

1. add section
2. check "Exapand Column Background" (or whatever is spelled now) and select content width "boxed"
3. add 2 columns with background colors (we used pre-set dark grey)

On the page, background is only visible within the boxed content, not 100% width.

Absolutely same setup works on 3.5.5, but not on 3.6

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://silverphoenixconsulting.ca
	Home URL: https://silverphoenixconsulting.ca
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: -6
	Admin Email: eugene@silverphoenixconsulting.ca
	Debug Mode: Inactive

== Theme ==
	Name: Devfox
	Version: 1.1
	Author: CymolThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	Breadcrumb NavXT
		Version: 7.0.2
		Author: John Havlik

	CF Post Formats
		Version: 1.3.1
		Author: crowdfavorite

	Codestar Framework
		Version: 1.0.1.1
		Author: Codestar

	Contact Form 7
		Version: 5.5.6
		Author: Takayuki Miyoshi

	CymolThemes Devfox Demo Content Setup
		Version: 1.0
		Author: CymolThemes

	Devfox Theme Extras
		Version: 1.2
		Author: CymolThemes

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Enhanced Text Widget
		Version: 1.5.2
		Author: Clever Widgets

	Envato Market
		Version: 2.0.7
		Author: Envato

	Slider Revolution
		Version: 6.5.14
		Author: ThemePunch

	Widget CSS Classes
		Version: 1.5.4.1
		Author: Jory Hogeveen

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
JS: showing 3 of 3JS: 2022-03-29 08:47:27 [error X 104][https://silverphoenix.betamxpertz.xyz/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.5:2:12166] this.parent.children.splice is not a function 
JS: 2022-03-29 08:47:28 [error X 1][https://silverphoenix.betamxpertz.xyz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:332595] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-03-29 08:49:51 [error X 1][https://silverphoenix.betamxpertz.xyz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:350072] Cannot read properties of undefined (reading \'isEditable\') 

PHP: showing 2 of 2PHP: 2022-04-04 07:10:49 [notice X 77][/home1/th925jox/silverphoenixconsulting.ca/wp-content/plugins/elementor/includes/base/controls-stack.php::1517] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-05 00:38:06 [notice X 4][/home1/th925jox/silverphoenixconsulting.ca/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52022-04-04 14:31:37 [info] elementor::elementor_updater Started 
2022-04-04 14:31:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-04 14:31:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-04 14:31:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.2',
)]
2022-04-04 14:31:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.2',
)]

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @smartfoxes 

You are using "**Devfox**" theme but you mention that "**This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).**"

Can you confirm that the bug occurs on both themes?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
