### ISSUE TITLE
🐞 Bug report: Missing Advanced Position Option

### ISSUE THREAD

**Issue by allouise** [elementor/elementor#18387]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor 3.5.6
![image](https://user-images.githubusercontent.com/31465806/162355223-50934530-9842-458a-9756-116a3ba2611b.png)

Elementor 3.6.0 to latest
![image](https://user-images.githubusercontent.com/31465806/162354957-a6305e4d-bbf1-4805-a3fa-d0948bde30c6.png)
The option Position in Advanced tab is missing after updating to the latest version of the plugin. We did a test from 3.5.6 to latest.

### Steps to reproduce

From Elementor 3.5.6 update to 3.6.2

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: http://jnwootemplate.allysonflores.com
	Home URL: http://jnwootemplate.allysonflores.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: elixirlouise@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

== Active Plugins ==
	Change Quantity on Checkout for WooCommerce
		Version: 2.0
		Author: Bhavik Kiri

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.3
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPS Hide Login
		Version: 1.9.4
		Author: WPServeur, NicolasKulka, wpformation

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 15 of 152022-03-23 02:31:40 [info] elementor::elementor_updater Started 
2022-03-23 02:31:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 02:31:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 02:31:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-23 02:31:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-24 04:26:05 [info] elementor::elementor_updater Started 
2022-03-24 04:26:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-24 04:26:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-24 04:26:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-24 04:26:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-04-08 03:02:45 [info] elementor::elementor_updater Started 
2022-04-08 03:02:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-08 03:02:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-08 03:02:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-08 03:02:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]

JS: showing 3 of 3JS: 2022-03-23 03:09:34 [error X 9][http://jnwootemplate.allysonflores.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0:2:515679] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-03-24 03:05:25 [error X 1][http://jnwootemplate.allysonflores.com/wp-content/plugins/ht-mega-for-elementor/assets/js/slick.min.js?ver=1.8.3:17:19555] Cannot read properties of null (reading \'add\') 
JS: 2022-03-24 04:20:31 [error X 3][http://jnwootemplate.allysonflores.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.5.6:2:235936] title invalid type: string. 

PHP: showing 2 of 2PHP: 2022-03-23 03:31:06 [notice X 5][/home/allouise/JNWooTemplate.allysonflores.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-24 04:26:50 [notice X 7][/home/allouise/JNWooTemplate.allysonflores.com/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by Deadlift79** [comment]
Changed position, see below:

![162354957-a6305e4d-bbf1-4805-a3fa-d0948bde30c6](https://user-images.githubusercontent.com/87310457/162538061-e65cd36e-394d-47b4-8f21-c860789f5e45.png)

**Comment by allouise** [comment]
Thank you! :D
