### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by JohnDoug** [elementor/elementor#18384]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am not able to edit any of my Elementor pages on my website dynamicsalestupperware.co.za

### Steps to reproduce

I am not able to edit any of my Elementor pages on my website dynamicsalestupperware.co.za

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 40M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://dynamicsalestupperware.co.za
	Home URL: https://dynamicsalestupperware.co.za
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-ZA
	Timezone: 2
	Admin Email: info@dynamicsalestupperware.co.za
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 3.2.1
	Author: OceanWP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29

== Active Plugins ==
	Contact Form 7
		Version: 5.5.6
		Author: Takayuki Miyoshi

	Contact Form Ready
		Version: 2.0.11
		Author: NickDuncan

	Contact Widgets For Elementor
		Version: 1.0.5
		Author: WPex - Ronen Abutbul & Gilad Takoni

	Elementor
		Version: 3.7.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Email Templates
		Version: 1.3.2.1
		Author: Damian Logghe

	Email Users
		Version: 4.8.8
		Author: Mike Walsh & MarvinLabs

	Essential Addons for Elementor
		Version: 5.0.12
		Author: WPDeveloper

	FluentCRM - Marketing Automation For WordPress
		Version: 2.5.8
		Author: Newsletter Team by Fluent CRM

	Fluent Forms
		Version: 4.3.4
		Author: Contact Form - WPManageNinja LLC

	FluentSMTP
		Version: 2.1.1
		Author: FluentSMTP & WPManageNinja Team

	GAinWP Google Analytics Integration for WordPress
		Version: 5.4.6
		Author: IntelligenceWP

	Google Analytics and Google Tag Manager by WebKinder
		Version: 1.9.4
		Author: WebKinder

	Import and export users and customers
		Version: 1.19.2
		Author: codection

	Instant Indexing
		Version: 1.1.13
		Author: Rank Math

	MC4WP: Mailchimp for WordPress
		Version: 4.8.7
		Author: ibericode

	Ocean Extra
		Version: 1.9.4
		Author: OceanWP

	Open Currency Converter
		Version: 1.4.5
		Author: David Artiss

	PDF viewer for Elementor
		Version: 2.9.3
		Author: RedLettuce Plugins

	Rank Math SEO
		Version: 1.0.85.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.9
		Author: Rank Math

	Site Reviews
		Version: 5.22.2
		Author: Paul Ryley

	Sliced Invoices
		Version: 3.8.17
		Author: Sliced Invoices

	Slimstat Analytics
		Version: 4.9.0.1
		Author: Jason Crouse

	Smart Recent Posts Widget
		Version: 1.0.2
		Author: Idenovasi

	Sticky Chat Widget
		Version: 1.1.2
		Author: Ginger Plugins

	TablePress
		Version: 1.14
		Author: Tobias Bäthge

	Templately
		Version: 1.3.3
		Author: Templately

	Ultimate Member
		Version: 2.3.1
		Author: Ultimate Member

	Ultimate Member - Online
		Version: 2.1.5
		Author: Ultimate Member

	WP Google Maps
		Version: 8.1.22
		Author: WP Google Maps

	WP Google Maps - Pro Add-on
		Version: 8.1.20
		Author: WP Google Maps

	WP Table Builder
		Version: 1.3.17
		Author: WP Table Builder

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Colour Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
Log: showing 20 of 392022-03-22 23:43:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-22 23:43:06 [info] elementor::elementor_updater Started 
2022-03-22 23:43:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-22 23:43:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-22 23:43:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-22 23:43:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-03-31 08:11:12 [info] elementor::elementor_updater Started 
2022-03-31 08:11:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-31 08:11:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-31 08:11:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-31 08:11:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-04-06 15:47:05 [info] elementor::elementor_updater Started 
2022-04-06 15:47:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 15:47:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 15:47:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 16:06:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.7.0-dev3',
)]
2022-04-06 16:06:41 [info] elementor::elementor_updater Started 
2022-04-06 16:06:41 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 16:06:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 16:06:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.7.0-dev3',
)]

PHP: showing 3 of 3PHP: 2022-03-23 00:05:22 [notice X 220][/home/dynamoju/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 17:14:46 [notice X 16][/home/dynamoju/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-06 17:31:38 [notice X 13][/home/dynamoju/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Contact Widgets For Elementor: Compatibility not specified
	Essential Addons for Elementor: Incompatible
	PDF viewer for Elementor: Compatibility not specified

**Comment by rami-elementor** [comment]
Hi @JohnDoug ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by rami-elementor** [comment]
I see in the log you attached that you updated Elementor 3.5.6 to Elementor 3.6.0.

Try to downgrade Elementor version back to 3.5.6.
