### ISSUE TITLE
A very simple case about container

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18390]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi

If we add a container [as a row](https://prnt.sc/mliWk8cYwIQP), then enter the items section, the [row symbol is enabled by default](https://prnt.sc/4sgKhdIiKsEF).

But if we add a container [as a column](https://prnt.sc/kfxxz6WZFWmO) and then enter the items tab, the [column icon is not active](https://prnt.sc/dxqBTmr9yKmh).

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
Nice catch!

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!
