### ISSUE TITLE
🐞 Bug report: Container - Background overlay does not work with carousel background images

### ISSUE THREAD

**Issue by jonasdaouani** [elementor/elementor#18391]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The container element does not show the background overlay when using a background carousel, for a normal background image it does work tho. The color option does not show as the image option does not show.

### Steps to reproduce

Create container element with background carousel images and then try to have an overlay on the container.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.28
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: http://silviom1.sg-host.com
	Home URL: http://silviom1.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 0
	Admin Email: contact@cosmicwebdevelopment.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL_formal
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 2.3.7
		Author: WebMat

	SiteGround Optimizer
		Version: 7.0.9
		Author: SiteGround

	SiteGround Security
		Version: 1.2.7
		Author: SiteGround

== Elements Usage ==
	
	wp-page : 1
		container : 1

== Elementor Experiments ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard actief
	Inline Font Icons: Standaard inactief
	Toegang verbeteringen: Standaard actief
	Import export template kit: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	Hide native WordPress widgets from search results: Standaard actief
	: Standaard inactief
	Flexbox Container: Actief
	Default to New Theme Builder: Standaard actief
	Hello Theme Header & Footer: Standaard actief
	Landingspagina's: Standaard actief
	Kleur sampler: Standaard actief
	Favorite Widgets: Standaard actief
	Beheerder bovenste balk: Standaard actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief

== Log ==
	
PHP: showing 11 of 11PHP: 2022-04-08 13:01:10 [notice X 12][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-08 13:09:18 [notice X 2][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:09:18 [notice X 2][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:09:18 [notice X 2][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:09:18 [notice X 2][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:29:38 [notice X 66][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-08 13:30:20 [notice X 4][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:30:20 [notice X 4][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:30:20 [notice X 4][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 13:30:20 [notice X 4][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-08 14:22:25 [notice X 1][/home/customer/www/silviom1.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Niet compatibel
	Flexible Elementor Panel: Compatibiliteit niet gespecificeerd

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!

**Comment by najmamat** [comment]
It is still happening on Elementori v3.12.1
