### ISSUE TITLE
🚀 Feature Request: Font Awesome 6 local

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#18397]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

![image](https://user-images.githubusercontent.com/6594795/162587880-9c356b09-9c23-411d-b87e-c87922738b75.png)

I'm having issues with Font Awesome, connecting to their servers is delaying loading.

And it is impossible to upload as custom icons.

Please make it possible that FA can be loaded manually.

It's Bad to use their CDN.

### Describe the solution you'd like

We can manually load Font Awesome as custom icons.

### Describe alternatives you've considered

It's no use uploading as a source, it needs to be part of the Elementor solution and be recognized as an icon.

**Comment by rami-elementor** [comment]
@ofmarconi 

Have you test the "Inline Font Icons" Experiment ?

https://elementor.com/help/inline-font-awesome/

**Comment by ofmarconi** [comment]
@rami-elementor not work: 

https://elementor.com/help/inline-font-awesome/#:~:text=Note%3A%20This%20feature%20does%20not%20convert%20Font%20Awesome%20Pro%20icons.%20If%20you%20are%20a%20Pro%20FA%20user

Anyway, it's not a local solution.

**Comment by rami-elementor** [comment]
> Anyway, it's not a local solution.

No, it's not a local solution, it's an inline SVG, reducing HTTP request, and loading just the required icons, not the entire font file.

**Comment by ofmarconi** [comment]
If it is not a local solution, it will be necessary at some point to consult an external server, getting back to the root of the problem.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/18397 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
