### ISSUE TITLE
🚀 Dark mode (New feature)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18405]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi
I do not know if you have a plan for it or not. But please add the dark mode feature. It's really great.

https://user-images.githubusercontent.com/77163248/162624855-034c1ce5-7e9d-4094-ad65-4091ec01ed64.mp4

### Describe the solution you'd like

-

**Comment by 3l3mentor** [comment]
Good idea

**Comment by Joliamendi** [comment]
Nice idea!

**Comment by fabianenzensperger** [comment]
+100

**Comment by 3l3mentor** [comment]
Also mention here: : https://github.com/elementor/elementor/issues/11073
