### ISSUE TITLE
🐞 Bug report: FLEXBOX - Gallery Widget on mobile view!!!

### ISSUE THREAD

**Issue by which-addon** [elementor/elementor#18408]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use the Gallery widget in the new FlexBox and there is another widget below it, I get display errors on the mobile version.
It looks like the Gallery is displayed in the background behind the other widgets....

### Steps to reproduce

1. activate FLEX BOX
2. add the Gallery widget (pro) and add a few pictures
3. add another widget below the gallery (e.g. Heading)
4. view the website in the mobile version

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] I can reproduce this bug consistently using the steps above.
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).

### System Info

-

**Comment by ConsultMePL** [comment]
I have another issue related to Flexbox - there is a strange load animation, as it was loading off the container, causing bad looking entrance animation (it shows a horizontal scroll bar) as well as causing CLS, which is not good for SEO

**Comment by ConsultMePL** [comment]
@which-addon I found a solution to the issue on mobile - in Elements (below Container) go to wrap and then choose "No wrap". It solves the problem ;)

**Comment by puregraphx** [comment]
I am on 3.7.5. and still having this issue

![image](https://user-images.githubusercontent.com/10434048/188585857-d3237f7e-ce5c-4076-9376-5f55eba74f81.png)

**Comment by tehben** [comment]
This issue returned with version 3.8. It wasn't happening before this latest release.

**Comment by mhv2408** [comment]
Thanks a lot @puregraphx . Setting Full Width to 100% solved my issue on mobile. 
For anyone wondering how to do this, 
1. Select your image/gallery widget.
2. Navigate to the advanced tab on your Elementor edit page. 
3. You can find the width attribute there, if it is set to default(as in my case) change it to Full Width (100%).

**Comment by SteidleSolutions** [comment]
> Thanks a lot [@puregraphx](https://github.com/puregraphx) . Setting Full Width to 100% solved my issue on mobile. For anyone wondering how to do this,
> 
>     1. Select your image/gallery widget.
> 
>     2. Navigate to the advanced tab on your Elementor edit page.
> 
>     3. You can find the width attribute there, if it is set to default(as in my case) change it to Full Width (100%).

This no longer works as a fix, at least for me.
