### ISSUE TITLE
🚀 Feature Request: Equal height for containers

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18404]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add a feature for containers that if activated, the height of all child containers will be equal. 

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
This feature already exist. You need to set the "Align Items" to "Stretch".
