### ISSUE TITLE
🚀 Elementor query builder. Powerful feature

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18407]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I am using a jet engine plugin that has a powerful query builder. Is it possible to add this important feature to elementor? It will definitely be extremely useful in the future. Especially for elementor loop builder

### Describe the solution you'd like

Elementor query builder

**Comment by rami-elementor** [comment]
Hi @Joliamendi ,

Thank you for submitting a feature request.

Elementor Pro has a query builder. It is used in Posts Widget and several other widgets. In addition, we are working on the "loop builder", but currently there is no official time table.

Regards,
