### ISSUE TITLE
Column link option

### ISSUE THREAD

**Issue by PixelDesigns** [elementor/elementor#18415]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Allow users to click in the whole column instead of individual elements. Users will be able to click in the whole column when you add a link on that.

### Describe the solution you'd like

Allow users to click in the whole column instead of individual elements. Users will be able to click in the whole column when you add a link on that.

**Comment by 79ho3ein** [comment]
hi @PixelDesigns 
This feature was added in version 3.6. Of course, it can only be used in containers.

**Comment by PixelDesigns** [comment]
Hi @79ho3ein , That's the problem. :) Why not working on Inner section / column element? Or regular section / column?

**Comment by fabianenzensperger** [comment]
> > Hi @79ho3ein , That's the problem. :) Why not working on Inner section / column element? Or regular section / column?
> 
> I think this was not possible due to the elementor infrastructure. Container is a very up-to-date type of sectioning that was published in elemntor, sooner or later we have to get used to it. The container has a more extraordinary performance than the section.

Maybe because Container is a classic widget and not a section or column (other infra as @79ho3ein says).

Maybe you should wait for Stable Containers. 👀

**Comment by rami-elementor** [comment]
Hi @PixelDesigns ,

Thank you for submitting a feature request.

We discussed this feature request several times. A decision was made not to add feature to columns/sections. Instead we added this feature to Containers.

Currently, we are not planning to support links in columns/sections.

Regards,
