### ISSUE TITLE
🐞 Bug report: When using elementor pro form URL field, form submission doesn't work

### ISSUE THREAD

**Issue by helenzimtstern** [elementor/elementor#18437]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the elementor form's URL-field and a URL is entered, the submission form isn't sending and an error occurs (see attached file).
I am certain this error is caused by the URL field, because the form will be submitted just fine, if I skip the information in the URL input field ans leave it blank. 

![URLSubmissionFormBUG](https://user-images.githubusercontent.com/103569694/163155047-f856c5ad-ef0d-4345-a876-1dc550c172c7.png)

 

### Steps to reproduce

Create a elementor pro form and add the URL form item. When filling in the form, enter a URL and check if the submission works. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 8192
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://soundscape-intervention.org
	Home URL: https://soundscape-intervention.org
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: c.moshona@tu-berlin.de
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0

== Active Plugins ==
	Custom Fonts
		Version: 1.3.4
		Author: Brainstorm Force

	DSGVO All in one for WP
		Version: 4.1
		Author: Michael Leithold

	Elementor
		Version: 3.6.1
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.11.15
		Author: WPVibes

	Elementor Header & Footer Builder
		Version: 1.6.9
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Header Footer Code Manager
		Version: 1.1.19
		Author: 99robots

	Simple CSS
		Version: 1.1.1
		Author: Tom Usborne

	Wordfence Security
		Version: 7.5.9
		Author: Wordfence

	WP DoNotTrack
		Version: 0.8.8
		Author: Frank Goossens (futtta)

	WP Maintenance Mode & Coming Soon
		Version: 2.4.4
		Author: Themeisle

	WPS Hide Login
		Version: 1.9.4
		Author: WPServeur, NicolasKulka, wpformation

	WPS Limit Login
		Version: 1.5.5
		Author: WPServeur, NicolasKulka, wpformation

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 402022-03-09 07:59:04 [info] elementor::elementor_updater Started 
2022-03-09 07:59:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-09 07:59:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-09 07:59:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-09 07:59:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-09 07:59:22 [info] elementor-pro::elementor_pro_updater Started 
2022-03-09 07:59:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-09 07:59:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-09 07:59:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-03-25 06:53:45 [info] elementor-pro::elementor_pro_updater Started 
2022-03-25 06:53:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-25 06:53:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-25 06:53:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-25 06:53:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-25 06:53:45 [info] elementor::elementor_updater Started 
2022-03-25 06:53:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-25 06:53:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-25 06:53:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.1',
)]
2022-03-25 06:53:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.1',
)]
2022-03-25 06:53:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]

PHP: showing 3 of 3PHP: 2021-12-16 14:43:11 [notice X 1][/var/www/vhosts/h168042.web201.dogado.net/soundscape-intervention.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-24 10:27:03 [notice X 2][/var/www/vhosts/h168042.web201.dogado.net/soundscape-intervention.org/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::260] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-13 09:19:30 [notice X 1][/var/www/vhosts/h168042.web201.dogado.net/soundscape-intervention.org/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Addon Elements: Compatible
	Elementor Header & Footer Builder: Incompatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Elementor Addon Elements: Compatible
	Elementor Header & Footer Builder: Compatible

**Comment by rami-elementor** [comment]
Hi @helenzimtstern ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by rami-elementor** [comment]
P.S. it sounds like a server issue... There are [many SMTP plugins](https://wordpress.org/plugins/tags/smtp/) that can help you either test your server SMTP, or use an external one.
