### ISSUE TITLE
add_responsive_control() issue with multiple control types

### ISSUE THREAD

**Issue by DesignInvento** [elementor/elementor#18434]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi There,
I found that there are multiple control types do not support add_responsive_control(). A couple of those are listed below,

1. control type SELECT
2. control type SELECT2
3. SWITCHER

editor shows responsive control options but value dies not change in render method, it always shows desktop selection on mobile devices. In its normal please mention the controls does not support add_responsive_control()

### Steps to reproduce

try to add add_responsive_control() for Select2, Select, or SWITCHER control types and get settings in render method for mobile devices.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.11
	MySQL version: mariadb.org binary distribution v10.4.14
	PHP Version: 7.4.11
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: http://localhost/wp/petclassified
	Home URL: http://localhost/wp/petclassified
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: help.designinvento@gmail.com
	Debug Mode: Active

== Theme ==
	Name: PetClassified
	Version: 1.0.0
	Author: Designinvento
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.57
		Author: ServMask

	DHEForm
		Version: 1.0.9
		Author: Sitesao

	DirectoryPress
		Version: 3.4.5
		Author: DirectoryPress

	DirectoryPress Advanced Fields
		Version: 1.0.1
		Author: DirectoryPress

	DirectoryPress Claim Listing
		Version: 1.0.1
		Author: DirectoryPress

	DirectoryPress Extended Location
		Version: 1.7.1
		Author: DirectoryPress

	DirectoryPress Frontend Listing
		Version: 2.5.5
		Author: DirectoryPress

	DirectoryPress MultiDirectory
		Version: 2.8.1
		Author: DirectoryPress

	DirectoryPress Payment Manager
		Version: 2.9.2
		Author: DirectoryPress

	Elementor
		Version: 3.6.3
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.5.5
		Author: Wpmet

	ElementsKit Pro
		Version: 2.6.3
		Author: Wpmet

	Frontend Messages For DirectoryPress
		Version: 5.4.1
		Author: Designinvento

	Header Footer Builder
		Version: 1.0.0
		Author: Designinvento

	PetClassified Core
		Version: 1.0.0
		Author: Designinvento

	PetClassified Templates
		Version: 1.0.0
		Author: PetClassified

	weDocs
		Version: 1.7.1
		Author: weDevs

	WooCommerce
		Version: 6.3.1
		Author: Automattic

<br />
<b>Notice</b>:  Undefined index: title in <b>D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\elementor\core\experiments\experiments-reporter.php</b> on line <b>89</b><br />

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 422022-04-05 22:36:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-05 22:36:23 [info] elementor::elementor_updater Started 
2022-04-05 22:36:23 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 22:36:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 22:36:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-05 22:36:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-05 22:36:36 [info] elementor::elementor_updater Started 
2022-04-05 22:36:36 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 22:36:36 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 22:36:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-12 21:10:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-12 21:10:59 [info] elementor::elementor_updater Started 
2022-04-12 21:10:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-12 21:11:00 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-12 21:11:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-12 21:11:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]
2022-04-12 21:11:13 [info] elementor::elementor_updater Started 
2022-04-12 21:11:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-12 21:11:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-12 21:11:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.3',
)]

JS: showing 1 of 1JS: 2022-04-12 02:32:56 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/js/editor.min.js:2:181401] this.ui.controlTitle is undefined 

== Elementor - Compatibility Tag ==

**Comment by DesignInvento** [comment]
ok i found that we can access breakpoints like this
```
$breakpoints_default_config = Breakpoints_Manager::get_default_config();
$breakpoint_key_mobile = Breakpoints_Manager::BREAKPOINT_KEY_MOBILE;
$breakpoint_key_tablet = Breakpoints_Manager::BREAKPOINT_KEY_TABLET;
```

but still not sure how to get current device, is there any function to detect device like wp_is_mobile()?

**Comment by rami-elementor** [comment]
Hi @DesignInvento,

Thank you for submitting a bug report but it's not really a bug. Not all the control types have the ability to set [multiple] responsive value. In not so distant past, the number control could not accept responsive value.

Currently we have no plan to add responsive to the Select/Select2/Switcher controls. Please use alternative methods.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,

**Comment by DesignInvento** [comment]
i was able to access responsive settings in render method but still needs to detect mobile devices, is there any builtin function to detect if current device is a mobile device or tablet just like wp_is_mobile()?
