### ISSUE TITLE
🐞 Bug report: update to 3.6.3 and Pro to 3.6.5 breaks header and footer

### ISSUE THREAD

**Issue by iggy097** [elementor/elementor#18439]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When updating to the newest version of Elementor - header and footer will break. I'm not sure on how else to explain it, sorry.
I have tried updating each plugin individually and the issue still persists. 

### Steps to reproduce

If I roll back my site to 3.6.2 and 3.6.4 pro the issue resolves itself.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.36
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://www.seductivestudiosmembers.com
	Home URL: https://www.seductivestudiosmembers.com
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 128M
	Max Memory limit: 128M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: dan@seductivestudios.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36

== Active Plugins ==
	Age Gate
		Version: 2.20.2
		Author: Phil Baker

	Category Ajax Filter
		Version: 2.4
		Author: Trusty Plugins

	Hide Admin Bar
		Version: 0.4.2
		Author: Shelby DeNike

	Paid Memberships Pro
		Version: 2.7.5
		Author: Paid Memberships Pro

	Paid Memberships Pro - Cancel on Next Payment Date
		Version: 0.4
		Author: Paid Memberships Pro

	Paid Memberships Pro - Reason For Cancelling Add On
		Version: 0.2.1
		Author: Paid Memberships Pro

	Query Monitor
		Version: 3.8.2
		Author: John Blackbourn

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP Maintenance Mode & Coming Soon
		Version: 2.4.4
		Author: Themeisle

== Network Plugins ==
	Advanced Database Cleaner
		Version: 3.0.4
		Author: Younes JFR.

	Category Ajax Filter
		Version: 2.4
		Author: Trusty Plugins

	Category Ajax Filter PRO
		Version: 8.4
		Author: Trusty Plugins

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.6.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.0.13
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.0.10
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 8.5.0
		Author: MonsterInsights

	Hide Admin Bar
		Version: 0.4.2
		Author: Shelby DeNike

	LoginWP (Formerly Peter's Login Redirect)
		Version: 3.0.0.8
		Author: LoginWP Team

	Paid Memberships Pro - User Pages Add On
		Version: .6
		Author: Stranger Studios

	Post SMTP
		Version: 2.0.25
		Author: Post SMTP

	Query Monitor
		Version: 3.8.2
		Author: John Blackbourn

	Sendy Widget
		Version: 1.4
		Author: WebHolics

	WP Cerber Security, Anti-spam & Malware Scan
		Version: 8.9.6
		Author: Cerber Tech Inc.

	WP Rollback
		Version: 1.7.1
		Author: Impress.org

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 392022-03-01 06:52:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-01 06:52:31 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 06:52:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-04-05 17:13:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-05 17:13:33 [info] elementor::elementor_updater Started 
2022-04-05 17:13:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 17:13:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 17:13:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-05 18:04:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.6.4',
)]
2022-04-05 18:04:13 [info] elementor-pro::elementor_pro_updater Started 
2022-04-05 18:04:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-05 18:04:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-05 18:04:13 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-04-05 18:04:13 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-04-05 18:04:13 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-04-05 18:04:14 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-04-05 18:04:14 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-04-05 18:04:14 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-04-05 18:04:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.6.4',
)]
2022-04-05 18:04:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.6.4',
)]

JS: showing 1 of 1JS: 2022-03-01 12:49:45 [error X 1][https://www.seductivestudiosmembers.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2569\") has already been destroyed and cannot be used. 

PHP: showing 2 of 2PHP: 2022-04-05 17:18:30 [notice X 6][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-05 18:04:14 [notice X 15][/www/wp-content/plugins/elementor-pro-3.6.4/license/api.php::361] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	

== Elementor Pro - Compatibility Tag ==

**Comment by calebsylvest** [comment]
@iggy097 I believe I'm having the same issue. Do you menu styles not render properly?

Looking at the console log I see a Mixed Content error, preventing the NavMenu CSS from loading.

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/4457883/163248301-8e67a669-9b9e-4122-88be-e5e74f6cad05.png">

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/4457883/163248555-fd615fdd-d33a-44f9-989d-1449ce7b00ce.png">

**Comment by iggy097** [comment]
I'm not sure - this is what mine looks like

**Comment by iggy097** [comment]
Update - I was able to fix this this morning. After I updated I had to go into Network and network activate Elementor Pro which was not activated after the update.
