### ISSUE TITLE
🐞 Bug report: Icon list element icon position

### ISSUE THREAD

**Issue by PixelDesigns** [elementor/elementor#18458]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The problem is, on the Icon List element icon position is middle, not top. Only this code solves it: 
selector .elementor-icon-list-item{align-items: start;}
selector .elementor-icon-list-item .elementor-icon-list-icon{margin-top: 6px;}

### Steps to reproduce

The problem is, on the Icon List element icon position is middle, not top. Only this code solves it: 
selector .elementor-icon-list-item{align-items: start;}
selector .elementor-icon-list-item .elementor-icon-list-icon{margin-top: 6px;}

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.31
	PHP Version: 7.4.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: http://maohu.web.maxer.hu
	Home URL: http://maohu.web.maxer.hu
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: hu
	Timezone: 0
	Admin Email: info@pixeldesigns.hu
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: hu_HU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	HelloPack
		Version: 1.1.9
		Author: HelloWP Ltd

	Loco Translate
		Version: 2.6.1
		Author: Tim Whitlock

	Polylang Connect for Elementor
		Version: 2.0.8
		Author: Creame

	Polylang Pro
		Version: 3.1.4
		Author: WP SYNTEX

	Stachethemes Event Calendar
		Version: 3.2.6
		Author: Stachethemes

== Elements Usage ==
	
	footer : 1
		heading : 1
		image : 2
		social-icons : 1
		text-editor : 3
	wp-page : 60
		heading : 69
		html : 26
		image : 87
		stachethemes_ec : 1
		text-editor : 84

== Elementor Experiments ==
	Optimalizált DOM kimenet: Alapértelmezés szerint aktív 
	Improved Asset Loading: Alapértelmezés szerint aktív 
	Továbbfejlesztett CSS betöltés: Alapértelmezés szerint aktív 
	Inline Font Icons: Alapértelmezés szerint inaktív
	Hozzáférhetőségi fejlesztések: Alapértelmezés szerint aktív 
	Import Export Template Kit: Alapértelmezés szerint aktív 
	Additional Custom Breakpoints: Alapértelmezés szerint aktív 
	Hide native WordPress widgets from search results: Alapértelmezés szerint aktív 
	: Alapértelmezés szerint inaktív
	Flexbox Container: Alapértelmezés szerint inaktív
	Default to New Theme Builder: Alapértelmezés szerint aktív 
	Hello Theme Header & Footer: Alapértelmezés szerint aktív 
	Landing oldalak: Alapértelmezés szerint aktív 
	Színválasztó: Alapértelmezés szerint aktív 
	Favorite Widgets: Alapértelmezés szerint aktív 
	Admin Top Bar: Alapértelmezés szerint aktív 
	Page Transitions: Alapértelmezés szerint aktív 
	Form Submissions: Alapértelmezés szerint aktív 
	Scroll Snap: Alapértelmezés szerint aktív 

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Összeillő
	Polylang Connect for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Duplicate of #18420
