### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by crobertwatson** [elementor/elementor#18455]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I run WP-CLI commands, I am seeing the following:

[notice X 0][/code/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

This notice is causing certain CI/VRT scripts to fail because they cannot continue without this warning being resolved.

At the very least, resolving this notice will reduce logging and improve site performance.

### Steps to reproduce

Run any WP-CLI command, such as `plugin list` and you will see the deprecation notice present.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

`
### wp-core ###

version: 5.9.3
site_language: en_US
user_language: en_US
timezone: America/Chicago
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 440
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /code
wordpress_size: loading...
uploads_path: /code/wp-content/uploads
uploads_size: loading...
themes_path: /code/wp-content/themes
themes_size: loading...
plugins_path: /code/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Astra (astra)
version: 3.7.9
author: Brainstorm Force
author_website: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
parent_theme: none
theme_features: core-block-patterns, astra_hooks, widgets-block-editor, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, rank-math-breadcrumbs, amp, menus, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /code/wp-content/themes/astra

### wp-themes-inactive (2) ###

Twenty Twenty-One: version: 1.5, author: the WordPress team
Twenty Twenty-Two: version: 1.1, author: the WordPress team

### wp-mu-plugins (3) ###

MU WP Native PHP Sessions: version: 0.1, author: Pantheon
Pantheon: version: 0.1, author: Pantheon
stagingpilot.php: author: (undefined), version: (undefined)

### wp-plugins-active (43) ###

Antispam Bee: version: 2.11.0, author: pluginkollektiv
Astra Widgets: version: 1.2.11, author: Brainstorm Force
Bloom: version: 1.3.12, author: Elegant Themes
Braintree for WooCommerce Payment Gateway: version: 2.6.4, author: WooCommerce
Contact Widgets: version: 1.7.0, author: GoDaddy
Cookie Notice & Compliance for GDPR / CCPA: version: 2.2.3, author: Hu-manity.co
CTX Feed: version: 4.4.57, author: WebAppick
Ele Custom Skin: version: 3.1.4, author: Dudaster.com
Elementor: version: 3.6.3, author: Elementor.com
Elementor Pro: version: 3.6.4, author: Elementor.com
Facebook for WooCommerce: version: 2.6.12, author: Facebook
Google Analytics for WordPress by MonsterInsights: version: 8.5.0, author: MonsterInsights
Limit Login Attempts: version: 1.7.1, author: Johan Eenfeldt
Ninja Forms: version: 3.6.9, author: Saturday Drive
Pantheon Advanced Page Cache: version: 1.0.0, author: Pantheon
Pinterest for WooCommerce: version: 2.4.2, author: premmerce
PixelYourSite: version: 8.2.18, author: PixelYourSite
PixelYourSite Pinterest: version: 3.2.5, author: PixelYourSite
Premium Addons for Elementor: version: 4.9.5, author: Leap13
Premium Addons PRO: version: 2.6.8, author: Leap13
Redirection: version: 5.2.3, author: John Godley
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond)
SendGrid: version: 1.11.8, author: SendGrid
Simple History: version: 3.2.0, author: Pär Thernström
Smush: version: 3.9.5, author: WPMU DEV
Storefront Product Pagination: version: 1.2.4, author: WooThemes
SVG Social Menu: version: 2.0.0, author: Florian Brinkmann
The Plus Addons for Elementor: version: 5.0.8, author: POSIMYTH
The Plus Addons for Elementor Page Builder: version: 4.1.7, author: POSIMYTH
Ultimate Addons for Elementor: version: 1.36.4, author: Brainstorm Force
Ultimate Addons for Gutenberg: version: 1.25.4, author: Brainstorm Force
Variation Swatches for WooCommerce: version: 1.1.19, author: Emran Ahmed
Vintage Charm Homestead Custom Post Types: version: 1.0, author: Easily Amused
WooCommerce: version: 6.4.0, author: Automattic
WooCommerce Advanced Shipping Packages: version: 1.1.7, author: Jeroen Sormani
WooCommerce Blocks: version: 7.3.0, author: Automattic
WooCommerce Content Inserter: version: 1.0.0, author: Rob Watson
WooCommerce Smart Coupons: version: 4.12.2, author: StoreApps
WooCommerce Square: version: 2.9.1, author: WooCommerce
WooCommerce USPS Shipping: version: 4.4.64, author: WooCommerce
Woo Custom Stock Status: version: 1.3.0, author: Softound Solutions
Wordfence Security: version: 7.5.9, author: Wordfence
Yoast SEO: version: 18.5.1, author: Team Yoast

### wp-plugins-inactive (2) ###

Astra Pro: version: 3.6.6, author: Brainstorm Force
Mailchimp for WooCommerce: version: 2.6.2, author: Mailchimp

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-86 Q16 x86_64 2020-01-13 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 100M
max_effective_size: 100 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 126 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 24576
	imagick::RESOURCETYPE_MAP: 126 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 5.10.109+ x86_64
httpd_software: nginx/1.16.1
php_version: 7.4.27 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 300
memory_limit: 256M
max_input_time: 900
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.61.1 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.4.18-MariaDB-log
client_version: mysqlnd 7.4.27
max_allowed_packet: 67108864
max_connections: 1024

### wp-constants ###

WP_HOME: https://vintagecharmhomestead.com
WP_SITEURL: https://vintagecharmhomestead.com
WP_CONTENT_DIR: /code/wp-content
WP_PLUGIN_DIR: /code/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: not writable
uploads: writable
plugins: not writable
themes: not writable
mu-plugins: not writable

`

**Comment by rami-elementor** [comment]
Hi @crobertwatson ,

It usually happen when one of your Elementor addons is using deprecated code.

It's not an Elementor issue, so I'll close this ticket as there is nothing here to fix.

But you should find the plugin causing the issue and ask the developer to read more about the [Elementor Deprecations](https://developers.elementor.com/docs/deprecations/)

And to solve the problem on your site, ask him to [read this](https://developers.elementor.com/docs/deprecations/advanced-example/#controls) and how [register controls in Elementor 3.5+](https://developers.elementor.com/docs/managers/registering-controls/).
