### ISSUE TITLE
🚀 Feature Request: modify filter hook 'elementor/theme/get_location_templates/template_id'  to include an additional second argument $location.

### ISSUE THREAD

**Issue by lakong** [elementor/elementor#18453]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

We have a need to include an additional second argument for $location

### Describe the solution you'd like

Currently this filter hook look like so: 
$theme_template_id = apply_filters( 'elementor/theme/get_location_templates/template_id', $theme_template_id );

We would like you folks to modify it like so:
$theme_template_id = apply_filters( 'elementor/theme/get_location_templates/template_id', $theme_template_id, $location );

This hook can be located in the file: pro/modules/theme-builder/classes/conditions-manager.php

### Describe alternatives you've considered

We couldn't come up with a solution so we modified the code for now on our site.  Of course this is not an ideal solution since we will need to keep it updated as you release new builds.

**Comment by lakong** [comment]
Mistake above:  This hook can be located in the file: elementor-pro/modules/theme-builder/classes/conditions-manager.php

**Comment by barthc** [comment]
@rami-elementor

**Comment by barthc** [comment]
@rami-elementor  any update on this issue?

**Comment by lakong** [comment]
I any response here?  We really need this done!

**Comment by rami-elementor** [comment]
The PR is waiting for approval.

**Comment by lakong** [comment]
Thanks, any idea when it might be published?

- Scot

**Comment by rami-elementor** [comment]
@lakong PR merged to Elementor Pro 3.9.0

**Comment by nicholaszein** [comment]
Hey there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by jgarcianewemage** [comment]
THIS gets lightspeed response but 4+ years to add ID/Class to "current" page body? lol
https://github.com/elementor/elementor/issues/4545
