### ISSUE TITLE
🐞 container 50% 50%

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18461]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When we have two containers with a width of 50%, it will not be possible to access one of the containers, except by using a navigator : https://prnt.sc/bw6n8oOK-Bcx
The reason for this bug is that the handle of one of the containers is placed under the handle of the parent container.
This bug is only present in the container. I tested in the section and there is no problem.

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by thejaydip** [comment]
Yes, you are right, When we select Page Layout as "Elementor Canvas" then it's faced.

**Comment by 79ho3ein** [comment]
it's true. In Canvas mode, header builder and popup builder have this problem.
