### ISSUE TITLE
🐞 Bug report: In the CHOOSE control, the toggle option does not work. 

### ISSUE THREAD

**Issue by sanbec** [elementor/elementor#18462]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use a CHOOSE control in a widget, its 'toggle' option does nothing
It doesn't matter if it is set to false, it always behaves as if it were true.

### Steps to reproduce

Add a CHOOSE control i.e.:

		$this->add_control(
			'direction',
			[
				'label' => esc_html__( 'Direction of rotation', 'elemendas-addons' ),
				'type' => Controls_Manager::CHOOSE,
				'options' => [
					'reverse' => [
						'title' => esc_html__( 'Left', 'elementor' ),
						'icon' => ' eicon-arrow-left',
					],
					'normal' => [
						'title' => esc_html__( 'Right', 'elementor' ),
						'icon' => ' eicon-arrow-right',
					],
				],
				'default' => 'normal',
				'selectors' => [
					'{{WRAPPER}} .elmadd-3Dcards-div' => 'animation-direction: {{VALUE}};',
				],
                                'toggle' => 'false',
			]
		);

The behaviour is the same if you put 'toggle' => 'true' or removing the 'toggle'  option

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

n/a

**Comment by thejaydip** [comment]
I have checked and the toggle functionality works fine after when I set it to true or false. Please check the below attachment.

![screencast-from-21-04-22-112534](https://user-images.githubusercontent.com/46511743/164388931-be72079f-e3a4-4902-bbb2-add938cba1da.gif)

**Comment by sanbec** [comment]
Oh shit, I know what the mistake is. If you look at my code you'll see 
                            toggle' => 'false',
and it should be
                            toggle' => false,
without quotes in the value.

Thank you very much!
