### ISSUE TITLE
🚀 Suggestions for developing icon and icon boxe widgets.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18464]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Icon widgets and icon boxes are great. But they can do better. There are also a number of limitations to these two widgets.

Please see this option in these two widgets : https://prnt.sc/v1Bi2a91FT6J
This option is really useless in this section and only complicates the work! In this option we can specify whether the icon or icon box has a border or not. Have a background color, or not. While we can remove this option, add simpler and much better controls in the style tab of these two widgets.

### Describe the solution you'd like

I think it is better to remove [this option](https://prnt.sc/v1Bi2a91FT6J) in these two widgets. On the other hand, add color, background color, and border color to the style tab. With the addition of these 3 items, there will really be no need for the view option in the content tab
**There are also two very important points in this widget :** 

1- There is no box shadow option in these two widgets. While really needed.
2- In these two widgets, it is not possible to specify the color for the border separately. https://prnt.sc/Jn0IpKCcy4Lx

Please check these items. Thank you!

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. Changing this will require lots of backwards computability code and have the potential to break sites.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Regards,

**Comment by 79ho3ein** [comment]
thank you
