### ISSUE TITLE
🚀 Feature Request: Allow hyphens in Form widget fields' IDs

### ISSUE THREAD

**Issue by gerardreches** [elementor/elementor#18475]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm always frustrated when I can't use hyphens in the ID of a field in the Form widget. Hyphens are valid in HTML for `id` attributes, so I see no reason not to allow them in Elementor.

I guess there is some reason to make it easier for Elementor, but there are situations where the use of hyphens in IDs is necessary.

I use Toolset Types, and all the custom fields are prepended with `wpcf-`. So when I want to use the custom field's name as the form field ID, I can't due to this, making it more difficult to write my own functions.

I use the Dynamic.ooo plugin to directly save form values into my database, since it matches the fields' IDs with my metadata, but not being able to use hyphens is a big inconvenient since I can't easily match the metadata names.

### Describe the solution you'd like

Hyphens should be allowed in form fields' IDs, as [it is valid HTML](https://www.w3.org/TR/1999/REC-html401-19991224/types.html#type-cdata).

Maybe Elementor is using hyphens for something else and that's why it doesn't allow them, but that's not our problem, it's Elementor's issue and it should find the way to make them work as they are supposed to by web standards.

### Describe alternatives you've considered

I've to write my own functions to replace underscore with hyphens, which it just makes the code dirtier, more difficult to maintain, and less understandable, since IDs in the form won't match those of my custom fields.

**Comment by rami-elementor** [comment]
Hi @gerardreches ,

In some languages, like PHP, hyphens are treated as minus sign.

For example, `$contact-id` is actually treated as `$contact` variable minus `id` constant. This is why in PHP variable names has a convention - using `_` instead of `-`.

We understand your frustration but we are subject to language limitations.

Unfortunately this request won't be fixed.

**Comment by gerardreches** [comment]
> Hi @gerardreches ,
> 
> In some languages, like PHP, hyphens are treated as minus sign.
> 
> For example, `$contact-id` is actually treated as `$contact` variable minus `id` constant. This is why in PHP variable names has a convention - using `_` instead of `-`.
> 
> We understand your frustration but we are subject to language limitations.
> 
> Unfortunately this request won't be fixed.

Hi @rami-elementor , but you aren't using a variable, are you? It's just a string and it comes from an HTML context. You may not be able to name a variable `$contact-id`, but you can definitely use `$form['contact-id']`. This is creating a problem where it doesn't exist. If you can't name variables with hyphens, adapt the code to use arrays instead of variables/objects. There is no language limitation here, just a workaround required.

Let's remember that using hyphens in `id` attributes *is* absolutely valid HTML code, and it should be. Please, reconsider this request.

**Comment by rami-elementor** [comment]
@gerardreches 

The use of PHP variables was merely an illustration of programming language limitations.

I'm not going to get into the code to explain why Elementor Form built this way; all I'm saying is that the Forms team chose not to use hyphens for a reason.
