### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by danieltubau** [elementor/elementor#18477]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I made some changes and I solved a problem with your help. But now I discover i've lost mi menu and it is impossible to view again

### Steps to reproduce

I try to put again the menu

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-wordpress.danieltubau.com-21-04-2022.txt](https://github.com/elementor/elementor/files/8535048/system-info-wordpress.danieltubau.com-21-04-2022.txt)
![Diletante Lost Image and Menu](https://user-images.githubusercontent.com/9770705/164551979-dbeb003e-bffe-4c79-bb76-843539efb7b4.JPG)

**Comment by rami-elementor** [comment]
Hi @danieltubau ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
