### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by danieltubau** [elementor/elementor#18474]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor doesnt work when I try to edit a post

### Steps to reproduce

I a post I try to edit with elementor, and I cant. The page never end the charge

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.2.34
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://wordpress.danieltubau.com
	Home URL: https://wordpress.danieltubau.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Admin Email: danieltubau@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Ashe Pro
	Version: 3.7.1.3
	Author: Royal Flush
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Ad Inserter
		Version: 2.7.13
		Author: Igor Funa

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Click To Tweet
		Version: 1.4
		Author: CoSchedule

	Custom PHP settings
		Version: 1.4.3.3
		Author: Cyclonecode

	Display Widgets
		Version: 2.7
		Author: Strategy11

	Draw Attention Pro
		Version: 1.8.8
		Author: Tyler Digital & Purple Pen Productions

	Duplicate Widgets
		Version: 1.2
		Author: aleksandargubecka

	Elementor
		Version: 3.7.0-dev5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Fonts Plugin Pro
		Version: 1.4.6
		Author: FontsPlugin.com

	Fonts Plugin | Google Fonts Typography
		Version: 3.0.16
		Author: Fonts Plugin

	footnotes
		Version: 2.7.3
		Author: Mark Cheret

	Footnotes for WordPress
		Version: 2016.1230
		Author: Charles Johnson

	Fullwidth Page Templates
		Version: 1.1.1
		Author: Brainstorm Force

	Google Analytics Dashboard for WP (GADWP)
		Version: 7.5.0
		Author: ExactMetrics

	ImageMapper
		Version: 1.2.6
		Author: A.Sandberg AKA Spike, Tarmo Toikkanen <tarmo.toikkanen@iki.fi>

	Image Map Pro
		Version: 4.4.1
		Author: Webcraft Plugins Ltd.

	Max Mega Menu
		Version: 2.9.6
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.0.1
		Author: megamenu.com

	mmfilesi-random-post
		Version: 1.0
		Author: mmfilesi

	Multiple Themes
		Version: 7.1.1
		Author: David Gewirtz

	Ninja Tables
		Version: 4.1.14
		Author: WPManageNinja LLC

	Perfect Pullquotes
		Version: 1.7.5
		Author: Adam DeHaven

	PHP Compatibility Checker
		Version: 1.5.2
		Author: WP Engine

	Redirection
		Version: 5.2.3
		Author: John Godley

	Remove Orphan Shortcodes
		Version: 1.2
		Author: Meks

	Royal Elementor Addons
		Version: 1.3.41
		Author: WP Royal

	Scripts n Styles
		Version: 3.5.1
		Author: unFocus Projects

	Simple Custom CSS
		Version: 4.0.5
		Author: John Regan

	Simple Custom CSS and JS
		Version: 3.39
		Author: SilkyPress.com

	SwfObj
		Version: 1.0.2
		Author: Matt Carpenter

	TablePress
		Version: 1.14
		Author: Tobias Bäthge

	TinyMCE Custom Styles
		Version: 1.1.2
		Author: Tim Reeves (original author David Stöckl)

	UpdraftPlus - Backup/Restore
		Version: 1.22.11
		Author: UpdraftPlus.Com, DavidAnderson

	Widget Importer & Exporter
		Version: 1.6
		Author: ChurchThemes.com

	WooCommerce
		Version: 6.4.1
		Author: Automattic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.3
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP OAM Renderer
		Version: 1.1
		Author: Ekino

	WP Show IDs
		Version: 110709
		Author: PriMoThemes.com / WebSharks, Inc.

== Uso de los elementos ==
	

== Experimentos de Elementor ==
	Salida del DOM optimizada: Inactivo
	Carga de recursos mejorada: Inactivo
	Carga de CSS mejorada: Inactivo
	Fuentes de iconos integradas: Inactivo
	Mejoras de accesibilidad: Inactivo
	Importar o exportar un kit de plantillas: Inactivo
	Puntos de ruptura personalizados adicionales: Inactivo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Inactivo
	: Inactivo por defecto
	Contenedor Flexbox: Inactivo
	Por defecto, el nuevo constructor de temas: Inactivo
	Páginas de destino: Inactivo
	Muestrario de colores: Inactivo
	Widgets favoritos: Inactivo
	Barra superior de administración: Inactivo
	Transiciones de páginas: Inactivo
	Envíos de formulario: Inactivo
	Ajuste de scroll: Inactivo

== Registro ==
	
PHP: showing 1 of 1PHP: 2022-04-16 12:28:04 [notice X 20497][/home/danieltu/public_html/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] ¡El argumento $control_id está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152022-04-17 19:48:22 [info] elementor::elementor_updater Started 
2022-04-17 19:48:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-17 19:48:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-17 19:48:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-17 20:59:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-17 20:59:06 [info] elementor-pro::elementor_pro_updater Started 
2022-04-17 20:59:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-17 20:59:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-17 20:59:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-21 12:51:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.7.0-dev5',
)]
2022-04-21 12:51:05 [info] elementor::elementor_updater Started 
2022-04-21 12:51:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-21 12:51:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-21 12:51:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.7.0-dev5',
)]
2022-04-21 12:51:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.7.0-dev5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Royal Elementor Addons: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Royal Elementor Addons: Compatible

**Comment by rami-elementor** [comment]
Hi @danieltubau ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
