### ISSUE TITLE
✔️ 🚀 Feature Request: Global Column Gap from Global settings

### ISSUE THREAD

**Issue by ra-ther** [elementor/elementor#18471]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Every time I design a new website I have to set the column gap in every section. Creating different websites with differents moods means choosing the blank space between the elements in the structure each time in every section. Column gap selector inside section may help us with that, but if the design concept need a different column gap than default (about 80% of times), we have to set that gap manually to every section in the page.

### Describe the solution you'd like

It would be nice to have a simple selector in Global Settings > Layout where we can define the column gap of all sections. I'ld add a notification to prevent it to change in case of production websites, because obviously it can break some designs already done. But still is a nice feature to set at the begining process. 

Another way to see it is make the default column gap size editable from global settings.

### Describe alternatives you've considered

Rather, a better solution can be to add variables for spaces. Following UX concepts, spaces are design tokens as typography and colors, so why not to include them as global settings? It could work like other variables like fonts or colors, it could be used to set the global column gap, but also button space, space between widgets or even set space for every component following that size.

A simple way to deliver it to the user could be provide just one field to set a medium space variable, so Elementor can autoscale it to calculate a propotional size system. I mean, where the user set `15px` as space token, elementor could set a simple CSS calc like `calc(--space * 1.25)`.

**Comment by nicholaszein** [comment]
Hello there @ra-ther!

We have great news! 🙌 

### 📢 We're happy to announce that you can now use the <ins>stable</ins> Flexbox Container experiment introduced with Elementor **v3.8**, and define a default column-gap in the Site Settings > Layout section! 🥳 

You're invited to update to the latest version, activate the Flexbox Container experiment, and enjoy the full power of CSS Flexbox with the easy-to-use Elementor interface! 💪 

Cheers 🥂
