### ISSUE TITLE
🚧 🐞 Bug report: Mini-cart icon breaks when the inline fonts experiment is active.

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#18473]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As soon as the inline fonts experiment is activated, the menu cart icon instantly breaks. It reappears as soon as the experiment is deactivated.

### Steps to reproduce

1. Put a menu cart in the header
2. Activate the svg inline experiment
3. Check the frontend and the cart icon is now broken

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1f
	MySQL version: mariadb.org binary distribution v10.4.24
	PHP Version: 7.4.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://elementor.us.instawp.xyz
	Home URL: https://elementor.us.instawp.xyz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.7.10
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	WooCommerce
		Version: 6.4.1
		Author: Automattic

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 1 of 1PHP: 2022-04-21 09:46:32 [notice X 7][/home/fegumuwuyevuzele/webapps/elementor/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
# 17705

**Comment by cgdmohamed** [comment]
same issue

**Comment by shilo-ey** [comment]
Please try to go to Elementor > Tools > Regenerate files and see if the problem persists.

This issue was resolved a while ago and we can't reproduce it.

Thanks.

**Comment by 79ho3ein** [comment]
Everything works fine for me
