### ISSUE TITLE
🚀 please update Swiper library in elementor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18472]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I have repeatedly asked the crocoblock development team to develop the carousel, but they said we could not add such capabilities because the js libraries in elementor are not up to date. See for example
https://github.com/Crocoblock/suggestions/issues/5240

So I wanted to ask you to please update these libraries to get rid of the current restrictions. thanks

### Describe the solution you'd like

**please update Swiper library in elementor**

**Comment by mbaierl** [comment]
+1 - the swiper library is VERY old and should be updated to include the latest fixes. Actually fixes from a few years already.

**Comment by 79ho3ein** [comment]
+1

**Comment by delykj** [comment]
+1

**Comment by nicholaszein** [comment]
Hey there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
