### ISSUE TITLE
✅ 🚀 Feature Request: Ability to apply links for each image in the image carousel widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18488]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add the possibility of applying a link for each image to the image carousel widget. We can now enter a link, but this link applies to all images in this widget and this is not really good. For this reason, elementor users have to use third-party plugins such as element pack, which allow them to apply links to each image in their image carousel widget.

### Describe the solution you'd like

**Ability to apply links for each image in the image carousel widget.**

**Comment by perks98** [comment]
@79ho3ein have you tried the media carousel widget? it should let you add links to individual images.

**Comment by 79ho3ein** [comment]
@perks98 
Yes, but the image carousel widget needs it too. On the other hand, the Carousel media widget is a bit problematic in image size

**Comment by nicholaszein** [comment]
Hi @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel in Elementor v3.14.0! 🥳 

You can now add your own content to your nested carousel and configure it as you'd like, including adding images with links. 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
