### ISSUE TITLE
🚀 Improve elementor speed using reactjs

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18492]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

React is used in many large websites and applications today, and one of the most important reasons for its use is its high speed. Certainly you, dear developers, are quite familiar with it. So, do you plan to add React to elementor? The development of react in elementor can increase the speed significantly.
What do you think about that?

### Describe the solution you'd like

React development in elementor

**Comment by Michaelgimii** [comment]
hi @rami-elementor 
I have a question...
Will a new elementor editor be introduced this year? https://prnt.sc/kTlJZ97Z83g-
Another question is whether with the new ui, the elementor editor will be rewritten or only the ui will be changed? Thank you in advance for your answer

**Comment by rami-elementor** [comment]
@Michaelgimii 

> Will a new elementor editor be introduced this year? https://prnt.sc/kTlJZ97Z83g-

I'm sorry, can not answer this question. The new Editor is part of our roadmap but I can not specify schedules.

> Another question is whether with the new ui, the elementor editor will be rewritten or only the ui will be changed?

Only the UI will be changed. We are not rewriting the Editor.

**Comment by Michaelgimii** [comment]
thanks @rami-elementor , But you said before that you have a plan to rewrite the elementor editor. Has this issue been ruled out?
https://prnt.sc/WLQd8MKQj18R

**Comment by rami-elementor** [comment]
> thanks @rami-elementor , But you said before that you have a plan to rewrite the elementor editor. Has this issue been ruled out? https://prnt.sc/WLQd8MKQj18R

It's in our roadmap, but there are no final details yet. It's not a simple task to rewrite your core engine while +10M users are using the product.
