### ISSUE TITLE
🐞 Bug report: Global  Color for Borders

### ISSUE THREAD

**Issue by quickDESIGNnl** [elementor/elementor#18494]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I add a global color to a border is doesn't show on frontend. (also using this in advanced tab of widgets)

### Steps to reproduce

Add a global color to a border.

Load page on frontend.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-initialminds.com-25-04-2022.txt](https://github.com/elementor/elementor/files/8554125/system-info-initialminds.com-25-04-2022.txt)

**Comment by rami-elementor** [comment]
@quickDESIGNnl 

Can you add a screenshot? where do you set this border?

**Comment by 79ho3ein** [comment]
I do not experience such a bug.

wordpress : 5.9.3
hello elementor : 2.5.0
elementor : 3.6.4
e pro : 3.6.5
