### ISSUE TITLE
🐞 Bug report: ElementKits Lite always stopping builder from loading I have contacted plugin dev also

### ISSUE THREAD

**Issue by barryg865** [elementor/elementor#18499]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

ElementKit Lite plugin always stopping the builder from loading I have contacted the plugin dev also but not heard anything yet, It is a highly marketed plugin I am surprised it always causes issues.

### Steps to reproduce

ElementKit Lite plugin always stopping the builder from loading I have contacted the plugin dev also but not heard anything yet, It is a highly marketed plugin I am surprised it always causes issues.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: http://vigeowellness.ketademo.com
	Home URL: http://vigeowellness.ketademo.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: contact@ketaminemedia.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.5.7
		Author: Wpmet

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Header Footer Code Manager
		Version: 1.1.21
		Author: 99robots

	Mobile Buttons
		Version: 1.0.0
		Author: Chris and David

	Schema Pro
		Version: 1.4.1
		Author: Brainstorm Force

	SEOPress
		Version: 5.6
		Author: SEOPress

	WP Compress | Image Optimizer
		Version: 5.11.04
		Author: WP Compress

== Elements Usage ==
	
	footer : 1
		divider : 3
		heading : 4
		icon-list : 3
		image : 1
		metform : 1
		social-icons : 1
		text-editor : 1
	header : 1
		button : 1
		ekit-nav-menu : 1
		icon-list : 1
		image : 1
	section : 4
		button : 8
		divider : 17
		ekit-nav-menu : 1
		elementskit-blog-posts : 1
		elementskit-client-logo : 1
		elementskit-icon-box : 6
		elementskit-progressbar : 2
		elementskit-video : 2
		heading : 33
		icon : 6
		icon-box : 5
		icon-list : 11
		image : 8
		metform : 2
		social-icons : 2
		spacer : 2
		testimonial : 2
		text-editor : 14
		video : 3
	widget : 0
		button : 2
	wp-page : 1
		button : 3
		divider : 5
		elementskit-blog-posts : 1
		elementskit-icon-box : 9
		heading : 11
		icon : 5
		icon-list : 4
		image : 1
		reviews : 1
		spacer : 1
		text-editor : 6

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 10 of 102022-04-12 16:27:28 [info] elementor-pro::elementor_pro_updater Started 
2022-04-12 16:27:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-12 16:27:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-12 16:27:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-12 16:27:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-14 08:20:20 [info] elementor::elementor_updater Started 
2022-04-14 08:20:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 08:20:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 08:20:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 08:20:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]

PHP: showing 6 of 6PHP: 2022-04-25 13:59:58 [notice X 395][/home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-25 14:00:00 [notice X 6][/home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-25 14:00:06 [notice X 48][/home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/metform/controls/base.php(46): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-25 14:00:06 [notice X 18][/home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/jeg-elementor-kit/lib/jeg-element/includes/class/elementor/class-elementor-manager.php(66): Elementor\Controls_Manager -> register()
#4: /home/customer/www/vigeowellness.ketademo.com/public_html/wp-includes/class-wp-hook.php(307): Jeg\Element\Elementor\Elementor_Manager -> register_control()
',
)]
PHP: 2022-04-25 16:49:58 [error X 1][/home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/vigeowellness.ketademo.com/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-25 20:34:27 [notice X 1][/home/customer/www/vigeowellness.ketademo.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::115] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-04-25 15:48:17 [error X 1][http://vigeowellness.ketademo.com/wp-content/plugins/elementor/assets/js/editor.min.js:2:515479] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-04-25 18:47:08 [error X 2][http://vigeowellness.ketademo.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.6.2:2:179050] Cannot read properties of undefined (reading \&#039;global\&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible

**Comment by rami-elementor** [comment]
Hi @barryg865 ,

Thank you for the feedback.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**.

If it's an Elementor bug, we'll need further details on how to isolate the problem and steps to reproduce in a clean site.

However, it appears to be an external addon to which we do not have access. Please get in touch with the addon's creators.

Regards,
