### ISSUE TITLE
How the hell do you add custom JS to your custom widget?

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#18500]
Hi
This is how you load a JS or CSS file for your widget:
https://developers.elementor.com/docs/widgets/widget-dependencies
But it doesn't work. I used the `window load` event and the `elementor/frontend/init` event but they don't work either.
```
Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
```

Is there any solution? I do exactly what is described in the docs above but the JS code doesn't work as expected in the Elementor editor, but it's fine in the preview and normal page view.

Elementor Version: **3.7.0-dev4**

**Comment by thejaydip** [comment]
Please try the below code in your custom widget JS, maybe that helps.

```
class Elementor_List_Widget extends elementorModules.frontend.handlers.Base {

	Elementor_List_Init( $scope ) {

		var $container = document.querySelector( '.elementor-widget-container' );

		console.log( $container );
	}

	onInit( ...args ) {

		super.onInit( ...args );
		this.Elementor_List_Init();
	}
}

jQuery( window ).on( 'elementor/frontend/init', () => {
	const addHandler = ( $element ) => {
		elementorFrontend.elementsHandler.addHandler( Elementor_List_Widget, {
			$element,
		} );
	};

	elementorFrontend.hooks.addAction( 'frontend/element_ready/elementor-list.default', addHandler );
} );
```

**Comment by babakfp** [comment]
> class Elementor_List_Widget extends elementorModules.frontend.handlers.Base {
> 
> 	Elementor_List_Init( $scope ) {
> 
> 		var $container = document.querySelector( '.elementor-widget-container' );
> 
> 		console.log( $container );
> 	}
> 
> 	onInit( ...args ) {
> 
> 		super.onInit( ...args );
> 		this.Elementor_List_Init();
> 	}
> }

```
Uncaught ReferenceError: elementorModules is not defined
```

**Comment by mbaierl** [comment]
Would be amazing to have up to date developer documentation.

**Comment by rami-elementor** [comment]
> @thejaydip Hi It gives out this error:
> 
> ```
> Uncaught ReferenceError: elementorModules is not defined
> ```

See this example: https://developers.elementor.com/docs/controls/frontend-available/

It talks about something different, but the code example explains how to avoid the `Uncaught ReferenceError: elementorModules is not defined` error. You simply need to define the `elementorModules` as a dependency in your widget `get_script_depends()` method.
