### ISSUE TITLE
Ability to change row height of posts on responsive views & other Responsive options

### ISSUE THREAD

**Issue by enkota** [elementor/elementor#1851]
If you set row height to 0 on posts (for instance posts of 3) tablet view row gap will not exist. It would be good to allow the ability to set the row/column widths responsively - same for portfolio module!

Also allow the read more to be fixed to the bottom of the column/card using flex would be great too!

<img width="1664" alt="screen shot 2017-06-16 at 15 10 02" src="https://user-images.githubusercontent.com/13979799/27230125-20861102-52a6-11e7-8d36-3ef285e566ff.png">
<img width="793" alt="screen shot 2017-06-16 at 15 09 54" src="https://user-images.githubusercontent.com/13979799/27230128-223bf156-52a6-11e7-98e6-7876f18453f7.png">

**Comment by HelmutGoebel** [comment]
This issue is 2 and a half year old and still not done? Why?

**Comment by jamieburchell** [comment]
> Also allow the read more to be fixed to the bottom of the column/card using flex would be great too!

Is that available now? In every project I add that CSS manually to achieve this

**Comment by shilo-ey** [comment]
This option has been added in Elementor Pro v3.5.0

Feel free to update

Thanks!

**Comment by jamieburchell** [comment]
@shilo-ey There doesn't appear to be any option for allowing the read more to be fixed to the bottom of the column/card using flex
