### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Raja-Zeeshan** [elementor/elementor#18513]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

when I click Elementor Update Button then show Error 401 please help me how can ?

### Steps to reproduce

yes 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.46 (Unix) OpenSSL/1.1.1i PHP/7.4.14 mod_perl/2.0.11 Perl/v5.32.0
	MySQL version: Source distribution v10.4.17
	PHP Version: 7.4.14
	PHP Memory Limit: 1000M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 750M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://sd-uk.info/dhobees
	Home URL: https://sd-uk.info/dhobees
	WP Multisite: No
	Max Upload Size: 750 MB
	Memory limit: 40M
	Max Memory limit: 1000M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: nraja1368@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Blocksy
	Version: 1.8.28
	Author: CreativeThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	Anywhere Elementor
		Version: 1.2.5
		Author: WPVibes

	Blocksy Companion
		Version: 1.8.27
		Author: CreativeThemes

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.5.7
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.1.0
		Author: WPDeveloper

	Google Listings and Ads
		Version: 1.12.5
		Author: WooCommerce

	Gutenberg
		Version: 13.0.0
		Author: Gutenberg Team

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.8.6
		Author: HasThemes

	Ninja Forms
		Version: 3.6.9
		Author: Saturday Drive

	Product Table by WooBeWoo
		Version: 1.5.8
		Author: WooBeWoo

	Product Table for WooCommerce
		Version: 3.1.4
		Author: CodeAstrology.com

	Smart Slider 3
		Version: 3.5.1.4
		Author: Nextend

	Starter Templates
		Version: 3.1.8
		Author: Brainstorm Force

	WooCommerce
		Version: 6.4.1
		Author: Automattic

	WooCommerce Payments
		Version: 4.0.1
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 1.25.26
		Author: WooCommerce

	WooODT Lite
		Version: 2.2.6
		Author: ByConsole

	WP Table Builder
		Version: 1.3.17
		Author: WP Table Builder

== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 4 of 4PHP: 2022-02-15 08:49:33 [error X 1][C:\xampp\htdocs\allparts\wp-content\plugins\elementor\core\base\document.php::864] Uncaught Exception: Invalid data: {"data":["Array","Array"],"element":"Array"} in C:\xampp\htdocs\allparts\wp-content\plugins\elementor\core\base\document.php:864
Stack trace:
#0 C:\xampp\htdocs\allparts\wp-content\plugins\astra-sites\inc\importers\batch-processing\class-astra-sites-batch-processing-elementor.php(122): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#1 C:\xampp\htdocs\allparts\wp-content\plugins\astra-sites\inc\importers\batch-processing\class-astra-sites-batch-processing-elementor.php(66): Elementor\TemplateLibrary\Astra_Sites_Batch_Processing_Elementor->import_single_post(544)
#2 C:\xampp\htdocs\allparts\wp-content\plugins\astra-sites\inc\importers\batch-processing\helpers\class-wp-background-process-astra.php(41): Elementor\TemplateLibrary\Astra_Sites_Batch_Processing_Elementor->import()
#3 C:\xampp\htdocs\allparts\wp-content\plugins\woocommerce\includes\libraries\wp-background-process.php(301): WP_Background_Process_Astra->task(Object(Elementor\TemplateLibrary\Astra_Sites_Batch_Processing_Elementor))
#4 C:\xampp\htdocs\allparts\wp-content\plugins\woocommerce\includes\libraries\wp-background-process.php(175): WP_Background_Process->handle()
#5 C:\xampp\htdocs\allparts\wp-includes\class-wp-hook.php(307): WP_Background_Process->maybe_handle('')
#6 C:\xampp\htdocs\allparts\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#7 C:\xampp\htdocs\allparts\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
#8 C:\xampp\htdocs\allparts\wp-admin\admin-ajax.php(187): do_action('wp_ajax_wp_imag...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 13:39:38 [notice X 644][C:\xampp\htdocs\allparts\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-24 11:27:34 [notice X 1][C:\xampp\htdocs\allparts\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The Plugin::$instance->posts_css_manager argument is deprecated since version 2.7.0! Use Plugin::$instance->files_manager instead. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 042256qMonday [notice X 1][/opt/lampp/htdocs/dhobees/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-02-15 12:36:19 [error X 7][http://sd-uk.info:18134/allparts/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-17 09:08:42 [error X 1][http://sd-uk.info:18134/allparts/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view36571\") has already been destroyed and cannot be used. 
JS: 2022-02-17 09:08:42 [error X 1][http://sd-uk.info:18134/allparts/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view36594\") has already been destroyed and cannot be used. 
JS: 2022-02-17 09:08:42 [error X 1][http://sd-uk.info:18134/allparts/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view36617\") has already been destroyed and cannot be used. 
JS: 2022-03-02 08:44:51 [error X 17][http://sd-uk.info:18134/allparts/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:293228] Cannot read properties of undefined (reading \'inheritors\') 

Log: showing 15 of 152022-03-01 14:35:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 14:35:11 [info] elementor::elementor_updater Started 
2022-03-01 14:35:11 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-01 14:35:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-01 14:35:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 14:35:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-04-06 10:28:25 [info] elementor::elementor_updater Started 
2022-04-06 10:28:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 10:28:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 10:28:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.0',
)]
2022-04-06 10:31:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.2',
)]
042243qWednesday [info] elementor::elementor_updater Started 
042243qWednesday [info] Elementor/Upgrades - _on_each_version Start  
042243qWednesday [info] Elementor/Upgrades - _on_each_version Finished 
042243qWednesday [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.4',
)]

== Elementor - Compatibility Tag ==
	
	Anywhere Elementor: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	HT Mega - Absolute Addons for Elementor Page Builder: Compatibility not specified

**Comment by rami-elementor** [comment]
Hi @Raja-Zeeshan ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
