### ISSUE TITLE
🐞 Bug report: TypeError: Cannot read properties of undefined (reading 'library')

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#18529]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

[Pro] After updating to Elementor Pro 3.6.0 or so my custom code extending a Form element broke. I am using 99% vanilla code and just needed some custom POST actions after the form is submitted. 

The error happens in the editor and that's why I believe it's unrelated to my code edits.

<img width="952" alt="Screenshot 2022-04-28 at 13 57 38" src="https://user-images.githubusercontent.com/1918426/165747023-7a20c569-1949-4729-a0d9-bccaeb8876b7.png">

1-min video description: https://www.loom.com/share/4163250483cf43c4b38879a2af0c07e8
Code: https://pastebin.com/sneVanyE

Thank you.

### Steps to reproduce

See above.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/D22wauFm

**Comment by kangarko** [comment]
@rami-elementor @shilo-ey any update please?

**Comment by rami-elementor** [comment]
Hi @kangarko 

1. The video URL returns 404.
2. I'm sorry but we are not going to debug your code.

**Comment by kangarko** [comment]
@rami-elementor I am sorry, but I have already contacted your email support after finding that the form steps would break even by simply extending your Form class:

```
class WidgetBoardingForm extends Form {
 
    public function get_name(): string {
        return 'boarding-form';
    }
 
    public function get_title(): string {
        return 'Boarding Form';
    }
}
```

I think you can debug this, it's literally a dummy class extending your form class and then being registered, and it breaks right away after adding a Step

**Comment by kangarko** [comment]
@rami-elementor @shilo-ey any input? It's been for over a month, I literally gave you your own code right above which does not work
