### ISSUE TITLE
🔥 A suggestion for the elementor team 

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18525]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team!

We all elementor users are eager to know about your roadmap. This is a very important issue. I don't know if you know, but Bricks builder will be the most serious elementor competitor in the future. This page builder uses two great methods that elementor has not yet considered. 1- Uses react js to increase page build speed. bricks builder loads very fast   **2- Surveys users about future features and tells users what features they are currently working on.**

**There is also a section on their website to get users' ideas directly : https://prnt.sc/qOrExis_4Qrx
In addition, users can rate each other's ideas. Any idea that scores more is passed on to the development team.**

In fact, I decided to dedicate 1 hour to this topic to talk to you about Item 2.

If you go to the [bricks builder site](https://bricksbuilder.io/), there is an option in the header called the Road map.
If you enter the roadmap page, you will see three options : **Planned** - **Next** - **In Progress**

Therefore, bricks builder keeps users informed about their future features. **Most importantly, on the roadmap page, users can [rate future features](https://prnt.sc/m1hHRifcBln6), so developers can prioritize them.**

So I wanted to ask you elementor team to please add the roadmap section to the elementor website. It is really important for us to know what features elementor works on. Also creating polls to add new features is really great.
I and many users love elementor. So we do not want elementor to suffer the fate of Visual Composer. Please increase your interaction with users and also speed up the development process. Before a new page builder replaces elementor. We really do not want this. I would also like to know your (elementor team) opinion on this.

thank you!

### Describe the solution you'd like

Please inform users of the roadmap. (Show on website Similar to bricks builder) - Survey of users for future features

**Comment by perks98** [comment]
**I completely agree.** Other plugins use request feature voting too like the Amelia booking plugin. I'm also disappointed that they rushed to release the flexbox container experiment in a highly unfinished state (should have been left on the dev plugin), as it feels like they are out of touch and clearly had marketing planned around it that they couldn't wait. But that's just my opinion...

**Comment by mcrowell** [comment]
+1

**Comment by webdevs-pro** [comment]
+1

**Comment by 3l3mentor** [comment]
+10000

**Comment by mehdimoradi1500** [comment]
Great features 👍👍
I hope elementor team just listen to this wonderful feature that @79ho3ein requested, road map section and rebuild widgets with react js knowledge that its incredibly fast 😍

**Comment by mehdimoradi1500** [comment]
Will elementor team read this features? I hope so

**Comment by Michaelgimii** [comment]
+1000
It's really great to know about the roadmap. also possible to display ongoing features, pending, ideas. bricks has done a great job in this regard. I hope elementor does not ignore this issue

**Comment by Joliamendi** [comment]
+1
elementor please. Do users' opinions matter to you? Now is the time to prove it.

**Comment by pauserratgutierrez** [comment]
@avivu @shilo-ey

**Comment by editor-acd** [comment]
Please add mega menu option. A website builder should have this. I don't want to install another plugin just for mega menu.

**Comment by elasticeye** [comment]
YES! This is important. I love all software with a roadmap. If you don't want it public, have it inside the account area, so only PRO users can see and vote for features. It's primarily PRO users that wanna vote for features anyway. Transparency and communication is KEY!
