### ISSUE TITLE
🚀 Feature Request: Save changes, but do not publish.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18528]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It's great if you add a feature, so we can make changes in the elementor editor, save it, but don't publish it and publish it whenever we want.
This feature is extremely useful. Please keep this in mind.

### Describe the solution you'd like

We can save changes, but not publish. After completing the desired design, we will publish it.

**Comment by perks98** [comment]
You can sort of do this already but isn't intuitive and doesn't always save the draft properly (don't exit by closing the browser tab). When you have a page already published you can save the page as a draft while the page is still published.

![Screenshot_314](https://user-images.githubusercontent.com/55829113/165733351-ed386238-dfcf-4544-99fd-6dff91bf09a2.jpg)
![Screenshot_315](https://user-images.githubusercontent.com/55829113/165733504-2ae05976-e92d-4c5d-ad65-f98fe7abfcc0.jpg)



When reloading the editor you get this message:
![Screenshot_316](https://user-images.githubusercontent.com/55829113/165733568-4c70c13a-878f-458d-8735-7d1ee03bfe9b.jpg)


But I can also see maybe people publishing changes by accident. This could be implemented with the new pro notes experiment where if not approved it doesn't load on the frontend perhaps.

Something I want to see is like with WP Bakery and Flatsome UX builder where you can disable rows completely so in the editor it is present and on the frontend there is no HTML code. Currently, you can disable different viewpoints like mobile and tablet but the code is still present on the frontend.

**Comment by 79ho3ein** [comment]
Oh, thank you @perks98 
Strange, I had not paid attention to it before! 
It is a great idea to be able to disable sections or containers. If I'm not mistaken, you have already submitted a request for it. It is true?

**Comment by perks98** [comment]
@79ho3ein I don't remember doing a feature request for this. But I think I saw a similar feature request years ago on the issues list on GitHub. Not sure where it is though but this is the first issue I can find with something similar to the issue #18183
