### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by kp-marz** [elementor/elementor#18537]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Currently there is an inability to enable the JavaScript API parameter (enablejsapi) without the use of custom code.

### Describe the solution you'd like

Within the video player module, add "Enable JS Support" or something similar under _Video Options_.

### Describe alternatives you've considered

Add a field to pass custom parameters.

### Additional context

Google is currently pushing for users to install GA4 which comes preloaded with video event tracking, pending the enablejsapi parameter being present on video embeds. It would be nice to have a simple way to enable this and have a simple integration with the new Google analytics platform.

**Comment by rami-elementor** [comment]
Hi @kp-marz ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,
