### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by sergeyzozulya** [elementor/elementor#18539]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor keeps loading the sidebar due to failed admin_ajax.php request that returns error 500

<img width="284" alt="image" src="https://user-images.githubusercontent.com/45847816/166097528-6e276554-1249-454e-9282-151f255cb6f7.png">

Payload is the following:

actions: {"get_widgets_config":{"action":"get_widgets_config","data":{"exclude":{}}}}
_nonce: 0996addd4f
editor_post_id: 15102
initial_document_id: 15102
action: elementor_ajax

Reverting Elementor to v3.5.6 resolves the issue, it seems it was introduced in v3.6.0

### Steps to reproduce

Open any page for editing with Elementor, the sidebar keeps loading

<img width="139" alt="image" src="https://user-images.githubusercontent.com/45847816/166097445-1c7e8baf-4065-48a5-a474-763739ae6d05.png">

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.19-67.0
	PHP Version: 7.3.10
	PHP Max Input Vars: 1500
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://complac.com
	Home URL: https://complac.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 2048M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: admin@nolo-marketing.de
	Debug Mode: Inactive

== Theme ==
	Name: instive
	Version: 1.0.6
	Author: Tripples
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36

== Active Plugins ==
	301 Redirects Pro
		Version: 5.98
		Author: WebFactory Ltd

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.49
		Author: Benjamin A. Bornschein, Borlabs

	CleverReach® WP
		Version: 1.5.14
		Author: CleverReach GmbH & Co. KG

	Contact Form 7
		Version: 5.5.6
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.10
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.5.7
		Author: Wpmet

	Instive Essentials
		Version: 1.3.1
		Author: 

	Ivory Search
		Version: 5.4.5
		Author: Ivory Search

	Jetpack
		Version: 10.8
		Author: Automattic

	Loco Translate
		Version: 2.6.1
		Author: Tim Whitlock

	MetForm
		Version: 2.1.6
		Author: Wpmet

	Page Generator Pro
		Version: 3.6.6
		Author: WP Zinc

	ShortPixel Image Optimizer
		Version: 4.22.9
		Author: ShortPixel

	Site Kit by Google
		Version: 1.73.0
		Author: Google

	Slider Revolution
		Version: 6.1.7
		Author: ThemePunch

	Unyson
		Version: 2.7.26
		Author: ThemeFuse

	UpdraftPlus - Backup/Restore
		Version: 2.16.24.1
		Author: UpdraftPlus.Com, DavidAnderson

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.3
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Mail SMTP
		Version: 3.4.0
		Author: WPForms

	WP Maintenance Mode & Coming Soon
		Version: 2.4.4
		Author: Themeisle

	WP Rollback
		Version: 1.7.1
		Author: Impress.org

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 18.6
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Page Generator Pro: Performance Addon
		Version: 2.9.3
		Author: WP Zinc

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 342022-04-06 19:19:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 19:19:20 [info] elementor::elementor_updater Started 
2022-04-06 19:19:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 19:19:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 19:19:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-15 10:44:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-15 10:44:30 [info] elementor::elementor_updater Started 
2022-04-15 10:44:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-15 10:44:31 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-15 10:44:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-15 10:44:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-15 10:44:38 [info] elementor-pro::elementor_pro_updater Started 
2022-04-15 10:44:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-15 10:44:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-15 10:44:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-30 09:56:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-30 09:56:28 [info] elementor::elementor_updater Started 
2022-04-30 09:56:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-30 09:56:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-30 09:56:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

JS: showing 3 of 3JS: 2022-03-21 11:35:11 [error X 1][https://complac.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:349872] Cannot read properties of null (reading \'id\') 
JS: 2022-04-05 08:37:09 [error X 5][https://complac.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.6:2:21771] Cannot read properties of undefined (reading \'global\') 
JS: 2022-04-29 12:13:37 [error X 1][https://complac.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4952\") has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2022-03-26 12:57:17 [notice X 9026][/kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 18:50:16 [notice X 257][/kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::260] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-31 05:53:01 [notice X 43][/kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/metform/controls/base.php(46): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-31 05:53:01 [notice X 43][/kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/themes/instive/components/editor/elementor/elementor.php(112): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-07 13:38:31 [notice X 2][/kunden/373567_32278/webseiten/www.complac.com/web/relaunch/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @sergeyzozulya ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
