### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by hwsstart** [elementor/elementor#18538]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I click on a menu item for a second you see the total menu, this couses a huge CLS

### Steps to reproduce

click on the menu

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.36
	PHP Version: 7.4.25
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://genietenophetwater.nl
	Home URL: https://genietenophetwater.nl
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: nl
	Timezone: 2
	Admin Email: henk@schoemanmail.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Duplicator Pro
		Version: 4.5.2
		Author: Snap Creek

	Elementor
		Version: 3.7.0-dev5
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev4
		Author: Elementor.com

	GTmetrix for WordPress
		Version: 0.4.4
		Author: GTmetrix

	Head, Footer and Post Injections
		Version: 3.2.3
		Author: Stefano Lissa

	SEO Redirection
		Version: 8.5
		Author: wp-buy

	Site Reviews
		Version: 5.23.6
		Author: Paul Ryley

	Social Chat
		Version: 5.0.3
		Author: QuadLayers

	SSL Insecure Content Fixer
		Version: 2.7.2
		Author: WebAware

	Widget for Google Reviews
		Version: 2.1.5
		Author: RichPlugins <support@richplugins.com>

	WP Fastest Cache
		Version: 1.0.0
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.6.3
		Author: Emre Vona

	WPS Hide Login
		Version: 1.9.4
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 18.6
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.4
		Author: Team Yoast

== Gebruik van elementen ==
	
	footer : 1
		button : 1
		heading : 5
		icon : 1
		nav-menu : 3
		social-icons : 1
		spacer : 1
		text-editor : 3
	header : 2
		breadcrumbs : 2
		button : 2
		icon : 1
		image : 7
		nav-menu : 6
		spacer : 2
		theme-site-logo : 5
	page : 11
		button : 18
		call-to-action : 2
		divider : 2
		gallery : 2
		heading : 26
		html : 2
		image : 20
		shortcode : 9
		slides : 3
		spacer : 14
		tabs : 2
		text-editor : 38
		wp-widget-grw_widget : 4
	popup : 1
		button : 1
		heading : 3
		image : 1
		spacer : 1
	section : 15
		author-box : 1
		button : 9
		form : 1
		gallery : 1
		heading : 2
		icon : 1
		image : 10
		nav-menu : 3
		post-info : 1
		shortcode : 3
		spacer : 2
		text-editor : 2
		theme-site-logo : 2
		wp-widget-grw_widget : 1
	widget : 0
		button : 1
	wp-post : 16
		author-box : 10
		button : 25
		divider : 8
		form : 2
		gallery : 7
		google_maps : 1
		heading : 96
		html : 4
		image : 55
		image-carousel : 7
		image-gallery : 3
		post-info : 8
		share-buttons : 4
		shortcode : 13
		spacer : 34
		tabs : 2
		text-editor : 125
		video : 5
		wp-widget-grw_widget : 1
	wp-page : 48
		button : 118
		flip-box : 6
		form : 1
		gallery : 8
		google_maps : 1
		heading : 129
		html : 11
		icon-list : 5
		image : 82
		image-gallery : 2
		menu-anchor : 2
		posts : 1
		shortcode : 43
		spacer : 28
		tabs : 4
		text-editor : 124
		theme-page-title : 1
		video : 3
		wp-widget-grw_widget : 9
		wp-widget-recent-posts : 1
	error-404 : 1
		heading : 2
		icon : 1
		icon-list : 1

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Pictogrammen inline lettertype: Actief
	Toegang verbeteringen: Actief
	Import export template kit: Inactief
	Extra aangepaste onderbrekingspunten: Standaard inactief
	Verberg verouderde WordPress widgets voor zoekresultaten: Actief
	: Standaard inactief
	Flexbox container: Standaard inactief
	Default to New Theme Builder: Actief
	Hello Theme header & footer: Actief
	Landingspagina's: Standaard actief
	Kleur sampler: Standaard actief
	Favoriete widgets: Actief
	Beheerder bovenste balk: Standaard actief
	Page Transitions: Standaard actief
	Notes: Standaard actief
	Form Submissions: Actief
	Scroll Snap: Standaard actief

== Log ==
	
Log: showing 20 of 372022-03-25 23:11:44 [info] elementor-pro::elementor_pro_updater Started 
2022-03-25 23:11:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-25 23:11:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-25 23:11:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev29',
  'to' => '3.7.0-dev35',
)]
2022-03-25 23:11:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev29',
  'to' => '3.7.0-dev35',
)]
2022-04-17 09:16:14 [info] elementor::elementor_updater Started 
2022-04-17 09:16:14 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-17 09:16:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev2',
  'to' => '3.7.0-dev5',
)]
2022-04-17 09:16:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-17 09:16:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev2',
  'to' => '3.7.0-dev5',
)]
2022-04-17 09:16:25 [info] elementor-pro::elementor_pro_updater Started 
2022-04-17 09:16:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-17 09:16:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-17 09:16:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev35',
  'to' => '3.8.0-dev2',
)]
2022-04-17 09:16:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev35',
  'to' => '3.8.0-dev2',
)]
2022-04-26 22:46:41 [info] elementor-pro::elementor_pro_updater Started 
2022-04-26 22:46:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-26 22:46:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-26 22:46:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev2',
  'to' => '3.8.0-dev4',
)]
2022-04-26 22:46:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev2',
  'to' => '3.8.0-dev4',
)]

JS: showing 2 of 2JS: 2022-03-04 22:13:04 [error X 2][https://genietenophetwater.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev45:2:487343] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-04-23 20:08:37 [error X 2][https://genietenophetwater.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev5:2:185245] Cannot read properties of undefined (reading \'data\') 

PHP: showing 3 of 3PHP: 2022-03-08 14:40:46 [notice X 2][/home/waterhuisjesheeg.nl/genietenophetwater/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-17 13:03:36 [notice X 74][/home/waterhuisjesheeg.nl/genietenophetwater/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-17 22:18:11 [notice X 10][/home/waterhuisjesheeg.nl/genietenophetwater/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibiliteit niet gespecificeerd

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @hwsstart ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the steps to replicate the issue. What menu item did you clicked? what widget did you used? We need more information for debug to understand it Elementor is not working and how to fix it.

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
