### ISSUE TITLE
🐞 Bug report: display articles

### ISSUE THREAD

**Issue by oloap16** [elementor/elementor#18541]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

when i put my articles in any page. They don't display as they're supposed to. It's very annoying and i don't know how to fix that problem. I put it in "grid" with 2 columns but they display just at the left of the page.

### Steps to reproduce

I don't really know what i do to have this issue. Maybe it comes to a plugin or a bad setting. I juste have a right sidebar on my article's page, that's all. And a few extensions like Akismet, Elementor, Elementor Addons, Cookie Notice, Pionet. And I have the theme "Ocean WP" 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

![Capture d’écran 2022-04-30 170531](https://user-images.githubusercontent.com/104687050/166111805-524c4b01-7b17-4f80-ac53-e7fd85b10c7c.png)
![Capture d’écran 2022-04-30 170552](https://user-images.githubusercontent.com/104687050/166111806-73fba8a9-76ac-4400-89b4-0297aa29951b.png)

**Comment by rami-elementor** [comment]
Hi @oloap16 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
