### ISSUE TITLE
🐞 Bug report: underlines are not displaying in Text Editor widget <a> elements

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#18556]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Underlines do not appear on link text when using the Text Editor widget, because this delcaration overrides them:
![CleanShot 2022-05-02 at 18 25 43@2x](https://user-images.githubusercontent.com/1435638/166209873-1bd891fa-82ce-49bb-a5bb-8c3763fd0b23.png)

### Steps to reproduce

1) Install and activate Elementor Hello theme
2) Drag in a text editor widget
3) Add a link to dummy text
4) Underline won't appear on text

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Affects multiple sites

**Comment by drawcard** [comment]
Supporting screenshots:

<img width="1168" alt="CleanShot 2022-05-02 at 18 37 07@2x" src="https://user-images.githubusercontent.com/1435638/166211113-d19f2846-6fce-41dd-ae91-145b7bc29c40.png">

The missing underline isn't such a problem if the link is a different colour, however for themes that have links set to the same colour as text, the link is hard to make out:

<img width="1008" alt="CleanShot 2022-05-02 at 18 39 05@2x" src="https://user-images.githubusercontent.com/1435638/166211337-d15be098-2a64-4bc9-a524-132eb0c28319.png">

**Comment by rami-elementor** [comment]
First of all, it's not a bug, this CSS rule was set to make sure your Elementor site will look the same on all the themes. We had to reset some rules.

You can create a new Feature Request to style links.

As a temporary solution, you can override this with custom CSS:

```css
selector a {
   text-decoration: underline;
}
```

**Comment by drawcard** [comment]
Hi @rami-elementor,

I had tried your workaround, however it seems to affect all elements on the page, eg. buttons and breadcrumbs. Is there a better selector I can target that affects just the written content?

<img width="1156" alt="CleanShot 2022-05-08 at 19 21 26@2x" src="https://user-images.githubusercontent.com/1435638/167290903-05087d78-bb2e-48cd-bf7f-719746c19667.png">

**Comment by rami-elementor** [comment]
Hi @drawcard ,

I usually select the widget where the main content is displayed and add a Custom CSS only to that widget.

Also, you need to replace `.elementor a` with `selector a`. Elementor uses `selector` to target the widget wrapper element. It also generates a higher CSS specify.
