### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by yaron86** [elementor/elementor#18559]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

i made a checkout page with elementor, added the checkout widget (in hebrew is called עגלת קניות)
my font site is set globally and it's Rubik font, from google fonts... and 2 things happened when i add the widgets:

1. the font is roboto: https://prnt.sc/y-ePPrWytPrK
2. my wordpress is in hebrew and also my elementor shows in hebrew, but in the widget there are part that shows in english, please make a good experice for me when i add the widget so it will all be in hebrew, please see this imge: https://prnt.sc/HUr_PTHG_cuM

### Steps to reproduce

just add the elementor checkout widget

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.6.49-89.0
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://israel-surf.co.il
	Home URL: https://israel-surf.co.il
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 0
	Admin Email: barlivny1987@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Check & Log Email
		Version: 1.0.5
		Author: WPChill

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Conditional Shipping for WooCommerce
		Version: 2.3.0
		Author: Lauri Karisola / WP Trio

	CTX Feed
		Version: 4.4.56
		Author: WebAppick

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Facebook for WordPress
		Version: 3.0.6
		Author: Facebook

	Finale Lite - Sales Countdown Timer & Discount for WooCommerce
		Version: 2.14.1
		Author: XLPlugins

	Free Shipping Bar for WooCommerce
		Version: 1.1.7
		Author: VillaTheme

	HFD Integration
		Version: 2.2.0
		Author: HFD

	iCount Payment Gateway
		Version: 1.5.6
		Author: iCount Systems

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	JetElements For Elementor
		Version: 2.6.3
		Author: Crocoblock

	Loco Translate
		Version: 2.6.1
		Author: Tim Whitlock

	Ocean Extra
		Version: 1.9.4
		Author: OceanWP

	PixelYourSite
		Version: 8.2.18
		Author: PixelYourSite

	Site Kit by Google
		Version: 1.71.0
		Author: Google

	SOGO  Accessibility
		Version: 2.1
		Author: Sogo

	Upsell Order Bump Offer for WooCommerce
		Version: 2.0.1
		Author: MakeWebBetter

	WooCommerce
		Version: 6.0.0
		Author: Automattic

	WooCommerce Conditional Shipping Pro
		Version: 2.6.0
		Author: Lauri Karisola / WooElements.com

	WooCommerce PayPal Checkout Gateway
		Version: 2.1.3
		Author: WooCommerce

	WooCommerce Shipping & Tax
		Version: 1.25.20
		Author: WooCommerce

	WooCommerce Shipping Per Product v2
		Version: 2.3.9
		Author: WooCommerce

	WPForms Lite
		Version: 1.7.3
		Author: WPForms

== שימוש באלמנטים ==
	
	footer : 1
		divider : 1
		form : 1
		heading : 4
		icon : 2
		icon-list : 1
		image : 1
		text-editor : 3
		wp-widget-nav_menu : 2
	header : 1
		nav-menu : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	page : 1
		heading : 1
		text-editor : 1
	popup : 1
		text-editor : 1
	product : 1
		accordion : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-images : 2
		woocommerce-product-price : 2
		woocommerce-product-related : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 4
	single : 2
		form : 1
		gallery : 1
		heading : 3
		post-navigation : 1
		share-buttons : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-title : 2
	wp-post : 4
		heading : 5
		html : 1
		icon : 1
		image-carousel : 1
		jet-instagram-gallery : 1
		text-editor : 1
		video : 1
		woocommerce-products : 1
	wp-page : 13
		divider : 1
		form : 2
		heading : 13
		html : 1
		icon : 1
		icon-list : 3
		image : 3
		posts : 1
		spacer : 2
		text-editor : 12
		woocommerce-cart : 1
		woocommerce-purchase-summary : 2
		wp-widget-nav_menu : 2

== Elementor Experiments ==
	פלט DOM שעבר אופטימיזציה: לא פעיל כברירת מחדל
	טעינת נכסים משופרת: לא פעיל כברירת מחדל
	Improved CSS Loading: לא פעיל כברירת מחדל
	Inline Font Icons: לא פעיל כברירת מחדל
	שיפורי נגישות: לא פעיל כברירת מחדל
	Import Export Template Kit: פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	: לא פעיל כברירת מחדל
	Flexbox Container: לא פעיל כברירת מחדל
	Default to New Theme Builder: פעיל כברירת מחדל
	Hello Theme Header & Footer: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	באר עליון אדמין: פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	Scroll Snap: פעיל כברירת מחדל

== יומן שינויים ==
	
PHP: showing 5 of 5PHP: 2022-01-26 10:28:52 [notice X 4][/var/www/vhosts/israel-surf.co.il/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-24 10:26:40 [notice X 22456][/var/www/vhosts/israel-surf.co.il/httpdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-27 16:26:44 [notice X 2][/var/www/vhosts/israel-surf.co.il/httpdocs/wp-content/plugins/elementor-pro/license/updater.php::85] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-11 19:58:21 [notice X 48][/var/www/vhosts/israel-surf.co.il/httpdocs/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-02 09:18:45 [warning X 1][/var/www/vhosts/israel-surf.co.il/httpdocs/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/vhosts/israel-surf.co.il/httpdocs/wp-content/uploads/elementor/css/post-8.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 362022-04-06 09:22:56 [info] elementor::elementor_updater Started 
2022-04-06 09:22:56 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-04-06 09:22:58 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-04-06 09:22:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 09:22:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.0',
  'to' => '3.6.4',
)]
2022-04-06 09:22:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-17 10:07:59 [info] elementor::elementor_updater Started 
2022-04-17 10:07:59 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-04-17 10:07:59 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-04-17 10:07:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-17 10:08:03 [info] elementor-pro::elementor_pro_updater Started 
2022-04-17 10:08:03 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-04-17 10:08:03 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-04-17 10:08:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-02 09:18:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-02 09:18:44 [info] elementor::elementor_updater Started 
2022-05-02 09:18:44 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-05-02 09:18:45 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-05-02 09:18:45 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-05-02 09:18:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

JS: showing 1 of 1JS: 2022-03-24 10:27:07 [error X 1][https://israel-surf.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:336011] Blocked a frame with origin \"https://israel-surf.co.il\" from accessing a cross-origin frame. 

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תואם
	JetElements For Elementor: לא תואם

== אלמנטור פרו - Compatibility Tag ==
	
	JetElements For Elementor: לא תואם

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
