### ISSUE TITLE
🐞 In the container, the responsive state of the elements is not well discernible.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18551]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the container, if we disable a container from the responsive section, only the color of the container changes. But the color of the widgets inside the container does not change, which makes it difficult to judge which items are inactive. https://prnt.sc/71m-NXHLZpNe
But if we disable only one widget, there is no problem and its color changes : https://prnt.sc/b3ZDOOQGwytg

But if you look at this in the section, it does not have this problem. When we disable the section, the section and all the widgets in it change color : https://prnt.sc/4lrf96WkQpUf

### Steps to reproduce

If the description is not enough, please let me know so I can send the video @shilo-ey 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!
