### ISSUE TITLE
🚀 Feature Request: Missing filters in the Uploads Manager

### ISSUE THREAD

**Issue by patrick-leb** [elementor/elementor#18565]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

`public function create_temp_file( $file_content, $file_name )` and `public function get_temp_dir()` do not have any hooks to overwrite the path chosen to upload. This causes a problem when another path, not in `/uploads` needs to be selected for any reason.

I personally need this feature because ZipArchive doesn't handle an S3 stream, which is what I have for my media library. I therefore need to move downloaded kits to a temp directory on the file system, like `/tmp/`, instead of the `wp_upload_dir()`.

### Describe the solution you'd like

It would be trivial to add hooks to change the paths of the `temp file` and/or `temp dir` should they be needed.

### Describe alternatives you've considered

Unfortunately there are no other hooks that can be used to change those paths.

### Additional context

I will submit a PR containing the two hooks like this:
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/68301566/166395290-c4c51b49-d00c-4419-a67b-3344b7259629.png">

**Comment by patrick-leb** [comment]
Can anyone have a look and approve or suggest changes to the PR? thank you.

**Comment by shilo-ey** [comment]
Hey,

This feature has been implemented in Elementor v3.7.0

Thank you for this contribution

Feel free to update

Thanks!
