### ISSUE TITLE
🐞 Bug report: Problème menu elementor

### ISSUE THREAD

**Issue by Guillaume-Himalaya** [elementor/elementor#18582]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Le menu de mon site casse à chaque fois qu'il y a une MAJ avec elementor

### Steps to reproduce

Voir le problème sur Himalaya.academy

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.6.50 |  
PHP Version: | 8.1.0 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 16000 |  
PHP Max Post Size: | 130M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by ValentinGratz** [comment]
Pour résoudre ce problème, remettez PHP en 7.1

la version 8 et + ne fonctionne pas, j'ai eu le tour (et idem, j'ai créé un ticket pour signaler ce problème)

**Comment by Guillaume-Himalaya** [comment]
Cela ne résout pas le problème... Le menu est toujours cassé. 
Ce qui est bizarre c'est que himalaya.academy et blog.himalaya.academy sont configurés exactement pareil. Le sous-domaine blog fonctionne très bien lui.

**Comment by rami-elementor** [comment]
Hi @Guillaume-Himalaya ,

Closing the bug report. Please open a new one in English.
