### ISSUE TITLE
🚀 Feature Request: Preview H5P content in editor

### ISSUE THREAD

**Issue by agichim** [elementor/elementor#18580]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It will show a preview of H5P content in the editor.

### Describe the solution you'd like

Being able to see H5P content when using it through the WordPress plugin with shortcodes.

### Additional context

H5P content is viewable and works fine only in the published page. But you have to guess when customizing the elements in the editor.

**Comment by rami-elementor** [comment]
@agichim What's H5P?

**Comment by drawcard** [comment]
@rami-elementor H5P is a cross platform kit for making interactive widgets, mainly used in education settings.

https://h5p.org/content-types-and-applications
https://wordpress.org/plugins/h5p/

**Comment by rami-elementor** [comment]
Looks like the H5P plugin generate WordPress shortcodes. You can use the Elementor Shortcode Widget to embed H5P content.
