### ISSUE TITLE
🐞 Bug report: Elementor Pro Compatibility Issue with Advanced Ads Pro

### ISSUE THREAD

**Issue by madjaeg** [elementor/elementor#18586]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is a plugin conflict when updating Advanced Ads Pro (Version 2.17.0) with Elementor Pro (Version 3.6.5) already installed and active. The entire front end of the site is blank and white. Backend is still accessible, and no other error or log is present.

### Steps to reproduce

Update Advanced Ads Pro to version 2.17.0, with Elementor Pro version 3.6.5 already installed and active on the site.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '40', Revision '3a1347ec0d4' v5.7.37-40
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://gcsaadev.wpengine.com
	Home URL: https://gcsaadev.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%
	Language: en-US
	Timezone: America/Chicago
	Admin Email: wpengine@epiccreative.com
	Debug Mode: Inactive

== Theme ==
	Name: GCSAATV Child
	Version: 1.0.0
	Author: EPIC Creative
	Child Theme: Yes
	Parent Theme Name: HTML5 Blank
	Parent Theme Version: 1.4.3
	Parent Theme Author: Todd Motto (@toddmotto)

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36

== Active Plugins ==
	Advanced Ads
		Version: 1.20.0
		Author: Thomas Maier, Advanced Ads GmbH

	Advanced Ads Pro
		Version: 2.13.0
		Author: Advanced Ads GmbH

	Advanced Ads – Geo Targeting
		Version: 1.3.4
		Author: Advanced Ads

	Advanced Ads – Responsive Ads
		Version: 1.10.3
		Author: Advanced Ads GmbH

	Advanced Ads – Ad Tracking
		Version: 1.21.0
		Author: Advanced Ads GmbH

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	DynamicConditions
		Version: 1.5.2
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.5
		Author: Dudaster.com

	Elementor
		Version: 3.6.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.5
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.3
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 5.1.0
		Author: WPDeveloper

	Gravity Forms
		Version: 2.6.2
		Author: Gravity Forms

	Gravity Forms + Custom Post Types
		Version: 3.1.26
		Author: Gravity Wiz

	Gravity Forms SendGrid Add-On
		Version: 1.5
		Author: Gravity Forms

	Insert Headers and Footers
		Version: 1.6.0
		Author: WPBeginner

	Make Column Clickable Elementor
		Version: 1.3.1
		Author: Fernando Acosta

	Toolset Types
		Version: 3.4.15
		Author: OnTheGoSystems

	Toolset Views
		Version: 3.6.2
		Author: OnTheGoSystems

	Unlimited Elements for Elementor
		Version: 1.5.11
		Author: Unlimited Elements

	WP All Export - User Export Add-On Pro
		Version: 1.0.7
		Author: Soflyy

	WP All Export Pro
		Version: 1.7.5
		Author: Soflyy

	WP All Import - Yoast WordPress SEO Add-On
		Version: 1.1.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.7.2
		Author: Soflyy

	Yoast SEO
		Version: 18.6
		Author: Team Yoast

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WPE ElasticPress Autosuggest Logger
		Version: 1.0.0
		Author: WP Engine

	WP Engine Cache Plugin
		Version: 1.0.9
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.5.5
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 432022-03-10 14:50:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.3',
)]
2022-03-10 14:51:01 [info] elementor-pro::elementor_pro_updater Started 
2022-03-10 14:51:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-10 14:51:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-10 14:51:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.6.3',
)]
2022-03-15 11:51:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-03-15 11:52:42 [info] elementor-pro::elementor_pro_updater Started 
2022-03-15 11:52:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-15 11:52:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-15 11:52:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-14 12:18:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.4',
)]
2022-04-14 12:19:16 [info] elementor::elementor_updater Started 
2022-04-14 12:19:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 12:19:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 12:19:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.4',
)]
2022-04-14 12:19:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-14 12:20:01 [info] elementor-pro::elementor_pro_updater Started 
2022-04-14 12:20:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-14 12:20:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-14 12:20:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @madjaeg ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
