### ISSUE TITLE
🐞 Bug report: Elementor note compatible php 8

### ISSUE THREAD

**Issue by ValentinGratz** [elementor/elementor#18583]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Ticket to ask when php 8 will be supported for elementor.

I tested WordPress and Elementor in localhost on php 8. WordPress no problem, but found that Elementor is not yet compatible for php 8.

I had a lot of bugs and fatal errors like this:
`(!) fatal error: uncaught error: class "elementor\scheme_typography" not found in (site link)\wp-content\plugins\rs_addons\rselements\widgets\heading\heading.php on line 314
`
My question: will it ever be?

### Steps to reproduce

- Install wordpress in localhost on your PC.
- Put the php version in 8.0
- Install elementor and go to the homepage of its site

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

`
### wp-core ###

version: 5.9.3
site_language: fr_FR
user_language: fr_FR
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\wamp64\www\projectoi
wordpress_size: 53,51 Mo (56106184 bytes)
uploads_path: C:\wamp64\www\projectoi/wp-content/uploads
uploads_size: 90,15 Mo (94527414 bytes)
themes_path: C:\wamp64\www\projectoi/wp-content/themes
themes_size: 53,02 Mo (55599043 bytes)
plugins_path: C:\wamp64\www\projectoi/wp-content/plugins
plugins_size: 137,03 Mo (143690200 bytes)
database_size: 19,88 Mo (20840448 bytes)
total_size: 353,59 Mo (370763289 bytes)

### wp-active-theme ###

name: Cretic Child (cretic-child)
version: 1.3
author: RS Theme
author_website: http://rstheme.com
parent_theme: Cretic (cretic)
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, post-formats, align-wide, custom-header, woocommerce, wc-product-gallery-slider, widgets, editor-style
theme_path: C:\wamp64\www\projectoi/wp-content/themes/cretic-child
auto_update: Désactivé

### wp-parent-theme ###

name: Cretic (cretic)
version: 1.6
author: RS Theme
author_website: http://www.rstheme.com
theme_path: C:\wamp64\www\projectoi/wp-content/themes/cretic
auto_update: Désactivé

### wp-themes-inactive (4) ###

Twenty Nineteen: version: 1.9, author: L’équipe WordPress (latest version: 2.2), Mises à jour auto désactivées
Twenty Twenty: version: 1.6, author: L’équipe WordPress (latest version: 1.9), Mises à jour auto désactivées
Twenty Twenty-One: version: 1.1, author: L’équipe WordPress (latest version: 1.5), Mises à jour auto désactivées
Twenty Twenty-Two: version: 1.1, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-plugins-active (14) ###

All-in-One WP Migration: version: 7.59, author: ServMask, Mises à jour auto désactivées
All-in-One WP Migration Unlimited Extension: version: 2.39, author: ServMask (latest version: 2.45), Mises à jour auto désactivées
Breadcrumb NavXT: version: 6.6.0, author: John Havlik (latest version: 7.0.2), Mises à jour auto désactivées
CL Testimonial: version: 1.1, author: RS Theme, Mises à jour auto désactivées
Cmap regions France: version: 5.1, author: Stefan M., Mises à jour auto désactivées
Contact Form 7: version: 5.4, author: Takayuki Miyoshi (latest version: 5.5.6), Mises à jour auto désactivées
Elementor: version: 3.1.1, author: Elementor.com (latest version: 3.6.5), Mises à jour auto désactivées
MC4WP: Mailchimp for WordPress: version: 4.8.3, author: ibericode (latest version: 4.8.7), Mises à jour auto désactivées
One Click Demo Import: version: 2.6.1, author: ProteusThemes (latest version: 3.1.1), Mises à jour auto désactivées
Redux: version: 4.1.24, author: Redux.io + Dovy Paukstys (latest version: 4.3.13), Mises à jour auto désactivées
Rs Addons: version: 1.0, author: RS Theme, Mises à jour auto désactivées
RS Framework: version: 1.0, author: RS Theme, Mises à jour auto désactivées
Slider Revolution: version: 6.3.5, author: ThemePunch, Mises à jour auto désactivées
WP Mail SMTP: version: 2.6.0, author: WPForms (latest version: 3.4.0), Mises à jour auto désactivées

### wp-plugins-inactive (9) ###

Akismet Anti-Spam: version: 4.1.8, author: Automattic (latest version: 4.2.3), Mises à jour auto désactivées
All in One SEO: version: 4.0.15, author: All in One SEO Team (latest version: 4.2.0), Mises à jour auto désactivées
AMP: version: 2.0.10, author: AMP Project Contributors (latest version: 2.2.4), Mises à jour auto désactivées
Bitnami Production Console Helper: version: 1.2, author: Bitnami, Mises à jour auto désactivées
Google Analytics for WordPress by MonsterInsights: version: 7.16.2, author: MonsterInsights (latest version: 8.5.1), Mises à jour auto désactivées
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Mises à jour auto désactivées
Jetpack by WordPress.com: version: 9.4, author: Automattic (latest version: 10.9), Mises à jour auto désactivées
TaxoPress: version: 3.0, author: TaxoPress (latest version: 3.6.1), Mises à jour auto désactivées
W3 Total Cache: version: 2.1.1, author: BoldGrid (latest version: 2.2.1), Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Non disponible
imagemagick_version: Non disponible
imagick_version: Non disponible
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 Mo
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.51 (Win64) PHP/7.4.26
php_version: 7.4.26 64bit                                            **_reset to 7.4 instead of 8.0_**
php_sapi: apache2handler
max_input_variables: 2500
time_limit: 120
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.70.0 OpenSSL/1.1.1l
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.36
client_version: mysqlnd 7.4.26
max_allowed_packet: 1048576
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\wamp64\www\projectoi/wp-content
WP_PLUGIN_DIR: C:\wamp64\www\projectoi/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Indéfini
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wp_mail_smtp ###

version: 2.6.0
license_key_type: lite
debug: Aucune notification de débogage trouvée.
db_tables: wp_wpmailsmtp_tasks_meta
lite_install_date: Jan 27, 2021 @ 11:59 

`

**Comment by rami-elementor** [comment]
@ValentinGratz 

Not an Elementor issue. The error indicated that it's in `\wp-content\plugins\rs_addons\`.
