### ISSUE TITLE
🚀 Responsive controls for custom css sections in each element.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18591]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you could add css code for each breakpoint to the custom css section : https://prnt.sc/agsTF_dgBBXE
This feature is great in its own right.

### Describe the solution you'd like

A new feature where we can write custom css for any breakpoint.

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request. We decided not to add this to our roadmap.

The CSS area usually used by people how have a minimum CSS understanding and know how to write a media query.

Regards,
