### ISSUE TITLE
🚀 Feature Request: Element names could inherit IDs in Navigator

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#18599]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

When using the inspector, it's hard to work out which container is which, because all containers are labelled "Container". Or, you might have ten headings in a container, and it's not easy to select the one you're looking for.

It would be nice if we could customise the display of these names, by inheriting the ID of the element.

Here is how it currently looks:
<img width="250" alt="CleanShot 2022-05-09 at 11 34 21@2x" src="https://user-images.githubusercontent.com/1435638/167328564-3faf5200-588d-40ce-8746-7a6686c33494.png">

### Describe the solution you'd like

**Mockup:**
<img width="271" alt="CleanShot 2022-05-09 at 11 37 29@2x" src="https://user-images.githubusercontent.com/1435638/167328673-679dbce2-f650-427c-9136-258876c52e89.png">

<img width="242" alt="CleanShot 2022-05-09 at 11 42 00@2x" src="https://user-images.githubusercontent.com/1435638/167329054-de5d0093-155e-41b7-9567-fa091331ca36.png">

### Describe alternatives you've considered

No other alternatives exist

**Comment by rami-elementor** [comment]
Hi @drawcard ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. The element name and the element CSS ID are two separate entities.

Please feel free to contact us again with other feature suggestions.

Regards,

**Comment by drawcard** [comment]
@rami-elementor The main reason why I request it, is that it's difficult to locate specific containers you're looking for - please see this example. If we could give containers an alias, it would help visualise the structure of the page much more easily.

<img width="241" alt="CleanShot 2022-05-09 at 19 15 08@2x" src="https://user-images.githubusercontent.com/1435638/167384878-cbd67706-1e7d-4cd3-b700-413809027ba5.png">

**Comment by drawcard** [comment]
Maybe this is possible already, I spotted this at: https://playground.elementor.com/demo/flexbox/#

Does anyone know how to rename containers?
<img width="304" alt="CleanShot 2022-05-11 at 21 11 03@2x" src="https://user-images.githubusercontent.com/1435638/167841970-378e0b11-1ea7-4acb-a136-ef3c77d5d7c4.png">

**Comment by drawcard** [comment]
Just discovered that double clicking on an in the navigator lets you edit the title. Closing the ticket, thanks
