### ISSUE TITLE
✅ 📊 🚀 Feature Request: Remove unused css in Elementor such as wp-rocket

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18602]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In elementor, we have the **Improved CSS Loading** option. But when I enable it, I do not really see any change in the website optimization results. While according to the developers, this feature deletes unused css codes!
On the other hand, the wp-rocket plugin develops the feature of deleting unused css, which works great.
**According to the wp rocket site, if we enable the option to delete unused css in this plugin, it will eliminate up to 88% of unused css code elementor!**
I tested this and it is absolutely true. After activating this option in wp-rocket, Google's performance score increased from 35 to 78!

dear elementor developers, please check the code of the wp-rocket plugin and, if possible, localize it in elementor. Adding this feature to elementor would be great...

### Describe the solution you'd like

smart Remove unused css in elementor

**Comment by nicholaszein** [comment]
Hi @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Core v3.24.0 and enhanced with the release of Elementor Pro v3.25.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
