### ISSUE TITLE
✅ 🐞 Bug report: Theme Builder templates do not maintain flex container percentages and breakpoints

### ISSUE THREAD

**Issue by bowmandesign** [elementor/elementor#18626]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

When creating a template in Elementor's themebuider, the nested flex container percentages are not maintained between the laptop, tablet extra, and tablet breakpoints. Widescreen, Desktop, and Mobile container percentages are maintained.

It previews correctly in Elementor, but not live in Safari Version 15.4 or Chrome Version 101.0.4951.54.

If I take the same container construction and publish it in a page or post directly, it works fine.

### Steps to reproduce

1. Create a template, set HTML tag to either DIV or Header or Footer (both do not address the problem.)
2. Create a full width container, Items = row and wrap, with two nested containers 66.6666 / 33.3333%.
4. In the 66.666% container make 6 nested containers at full width 30%. No or any  item settings do not address the problem.
5.  At the widescreen and desktop breakpoints, set the 6 nested containers, in the 66.666% parent container, to default.
6. At the tablet extra breakpoint, set the 6 nested containers, in the 66.666% parent container, to 40%.
7. At the mobile extra breakpoint, set the 6 nested containers, in the 66.666% parent container, to 100%.
8. Preview in Elementor and all works fine.
9. Preview in Safari and Chrome and the 6 nested containers that should switch between 3x2 containers at the widescreen and desktop, do not switch to 2x3 containers on tablet extra to tablet.
10. Mobile extra and mobile work fine showing 1x6 containers at 100%
11. The second top level 33.3333% parent container has one nested container at 100% and it works fine at all breakpoints. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by MichaelDarko** [comment]
Could it be related to #16819 / #16591?

**Comment by umm-wdc** [comment]
Facing same issue +1, footer custom widths not responsive

**Comment by bowmandesign** [comment]
> Could it be related to #16819 / #16591?
You are right @MichaelDarko this is related, thanks. I have also been regenerating the stylesheets, exhausting and delaying work.

**Comment by bowmandesign** [comment]
> Facing same issue +1, footer custom widths not responsive
> Could it be related to #16819 / #16591? @MichaelDarko 

Hi @umm-wdc and @MichaelDarko 

Regenerating the CSS works. 

I may have also found a possible reason why this is happening and the current fix is needed.

If you don't install the Elementor Developer Edition, basically, only install..

Elementor 3.6.4 + Pro 3.6.4 + custom breakpoints active + flexbox active, the problem goes away.

If Elementor Dev 3.7+ is installed, it updates the database tables and the css has any place to go. 

Regenerating, migrates the lost css to the new table in Elementor Dev 3.7+.

I just tested a server with the specs above and it behaved better.

**Comment by bowmandesign** [comment]
Hello Elementor,

After much dev, troubleshooting, and not getting any work done for my project, I found that the Elementor flexbox containers with custom breakpoints bugs are not specific to the 'Footer' theme template.

ANY theme template with a flexbox container that utilizes custom margins and paddings per custom breakpoints will not preview mobile correctly in the Elementor editor and a live website.

@MichaelDarko was kind enough to comment on the similarity to issues, 
#16591   (reported seven months ago on October 5, 2021)
& 
#16819   (reported seven months ago on November 5, 2021)

@umm-wdc has also experienced the same bugs and many other #elementor users.

I understand the Flexbox experiment is in alpha. Still, I am concerned that I will be unable to continue with Elementor without Flexboxes that can maintain padding and render correctly in preview or a live webpage.

All works fine if you do not make any theme templates and only utilize the out-of-the-box single-page template with no custom padding for all singular usages, which is unreasonable.

Like most, all Elementor users need theme templates to control unique padding per device. Otherwise, you have to administer this at the page level for each page with a wrap-around custom container, which does work, but it is not reasonable.

You must repeatedly render two workarounds to address the bug, each different for the preview vs. live variants of the bug.

1. Incorrect Preview = In 'edit with Elementor', click 'responsive mode', click the responsive 'gear' icon to the right of the breakpoints sizes, open, then close, and your preview will re-render mobile correctly.
2. Incorrect Live serving of your page = Elementor/ Tools / 'Regenerate CSS & Data.'

Elementor cannot currently successfully use flexbox containers in ANY theme templates and maintain custom padding per device when previewed in the Elementor editor and sometimes in the live site.

To reproduce,

1. Use Elementor.
2. Use flexbox containers.
3. Use custom breakpoints.
4. Make any theme template, like a single page, place your container and post content widget.
5. Make custom padding settings on your container flexbox per device.
6. Make a page that uses your new theme template.
7. Place your content and design.
8. Preview it in responsive mode, mobile, and your containers will be pushed to the right with typography, not wrapping.
9. The bug is straightforward to reproduce and occurs in preview and live.

This problem is out-of-the-box, using only Elementor, Elementor Pro, and Elementor's Hello Theme.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core 3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
