### ISSUE TITLE
custom loops for posts and categories🚀 Feature Request: 

### ISSUE THREAD

**Issue by mohammed-breky** [elementor/elementor#18625]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

there is a lot of situations when i want to make a custom loop for cpts or category (taxonomies) for example for an online store categories listing in the front page

### Describe the solution you'd like

a section in the theme builder area where i can make a custom loop for categories or posts

### Describe alternatives you've considered

like the plugin custom ele skin
but that plugin missing the categories query

**Comment by elasticeye** [comment]
Like this:
https://github.com/elementor/elementor/issues/4440

It's coming.

**Comment by arielk** [comment]
> Like this: #4440
> 
> It's coming.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
