### ISSUE TITLE
🐞 Bug in elementor pro 3.7 - menu cart widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18629]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating elementor pro to version 3.7, if [this option](https://prnt.sc/HM6Wvn75rFrb) is enabled in the shopping cart widget, the shopping cart menu will open automatically each time the editor is [updated](https://prnt.sc/E4WfZ-7a0aJ7).

**It should be noted that immediately after updating elementor pro to version 3.7, I also updated WooCommerce to the new version (6.5.0). So I'm not sure if the problem is with elementor pro or WooCommerce**

Please let me know if you were not successful in reproducing this bug @avivu 

thank you

### Steps to reproduce

1- Add the menu cart widget and enable [this option](https://prnt.sc/HM6Wvn75rFrb).
2- Then [update](https://prnt.sc/E4WfZ-7a0aJ7) the changes

After that, the menu cart will open automatically. **Even if you save changes to site settings, it will still open automatically.**

This bug did not exist in the version 3.5.2. I did not test versions 3.6 to 3.65

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by avivu** [comment]
Hello @79ho3ein 

Thanks for reporting. It's very appreciated.

I succeeded to reproduce the issue.

We will address this issue soon and release a patch.
Please follow this thread for updates.

Thanks!

**Comment by 79ho3ein** [comment]
Thank you, good luck.

**Comment by 79ho3ein** [comment]
This bug fixed in version 3.7.2
thank you @avivu
