### ISSUE TITLE
🐞 Bug report: Only the first 100 sites are processed by default usage of `get_sites()` 

### ISSUE THREAD

**Issue by vdwijngaert** [elementor/elementor#18639]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There's an issue in your code when iterating over sites in a multisite. A little known thing about the [`get_sites()`](https://developer.wordpress.org/reference/functions/get_sites/) function, is that the `WP_Site_Query` powering it, takes a `number` argument is used as the total number of sites to fetch from the database. [This `number` argument defaults to **100**](https://github.com/WordPress/wordpress-develop/blob/44cd1981b967966e22f4e40fa1ab04ee3ce2f728/src/wp-includes/class-wp-site-query.php#L127).

Because of this, most cli commands you provide for doing maintenance and automation after deployments will currently only process the first 100 sites. This includes things like:
- database upgrades
- flush_css commands
- cloud library syncs
- ...

**Currently, it's being used in these places:**

- https://github.com/elementor/elementor/blob/a4ba3cdece9dfd52b28acd55fc110be39a4e49da/includes/maintenance.php#L39
- https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/modules/wp-cli/update.php#L47
- https://github.com/elementor/elementor/blob/9aadba35a9ad52cd5e9cbef55a5761f47403491c/core/experiments/wp-cli.php#L128
- https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/modules/wp-cli/command.php#L41
- https://github.com/elementor/elementor/blob/15f9a99db9b35d63358f26ebd46ed7c7b6f45d68/modules/wp-cli/library.php#L45

A quick fix would be to pass in `['number' => 0]` for `$args`, but it might be better to get the total blog count with `get_blog_count()` and iterate over all sites in chunks :)

### Steps to reproduce

1. Find or create a multisite network that has over 100 active sites.
2. Open up a wp cli shell: `wp shell`
3. Run `count(get_sites());`

```bash
 $ wp shell
wp> count(get_sites());
=> int(100)
```

If we pass in the `number` argument, and set it to zero, we can see that the actual number of sites returned is bigger.
```bash
wp shell
wp> count(get_sites(['number' => 0]));
=> int(213)
```

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

NULL

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Thank you for the contribution!

Feel free to update

Thanks!
