### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by owoblow2020** [elementor/elementor#18632]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I tried creating a "Post" I get a blank page.

### Steps to reproduce

1. I clicked on the post button to create a new post and got a blanked page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://emmanjokufoundation.org/welcome
	Home URL: https://emmanjokufoundation.org/welcome
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Admin Email: o.olulegan@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Alone
	Version: 7.4
	Author: Bearsthemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.12.2
		Author: Delicious Brains

	Advanced Custom Fields: Font Awesome
		Version: 4.0.3
		Author: Matt Keys

	Bearsthemes Addons
		Version: 2.2.0
		Author: Bearsthemes

	Broken Link Checker
		Version: 1.11.16
		Author: WPMU DEV

	Cloudflare
		Version: 4.9.1
		Author: Cloudflare, Inc.

	Custom Twitter Feeds
		Version: 1.8.4
		Author: Smash Balloon

	Elementor
		Version: 3.7.0-dev7
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev11
		Author: Elementor.com

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Give - Donation Plugin
		Version: 2.20.0
		Author: GiveWP

	Kirki Customizer Framework
		Version: 4.0.23
		Author: David Vongries

	Piotnet Addons For Elementor
		Version: 2.4.14
		Author: Piotnet

	Rave WooCommerce Payment Gateway
		Version: 2.2.5
		Author: Flutterwave Developers

	Sermon'e - Sermons Management
		Version: 1.0.0
		Author: Beplus

	Smash Balloon Custom Facebook Feed
		Version: 4.1.3
		Author: Smash Balloon

	Smash Balloon Instagram Feed
		Version: 6.0.5
		Author: Smash Balloon

	The Events Calendar
		Version: 5.14.2.1
		Author: The Events Calendar

	Tidio Chat
		Version: 5.0.0
		Author: Tidio Ltd.

	UberMenu 3 - The Ultimate WordPress Mega Menu
		Version: 3.7.3
		Author: Chris Mavricos, SevenSpark

	WooCommerce
		Version: 6.4.1
		Author: Automattic

	Yoast SEO
		Version: 18.8
		Author: Team Yoast

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

== Elements Usage ==
	
	page : 3
		be-counter : 2
		be-give-form : 1
		be-icon-box : 4
		be-members : 1
		be-members-carousel : 1
		be-pie-chart : 1
		be-posts-carousel : 1
		be-video-box : 1
		be-video-play-button : 1
		button : 2
		heading : 30
		icon : 3
		icon-list : 5
		image : 9
		tabs : 1
		text-editor : 16
	section : 8
		accordion : 3
		be-give-form-button : 3
		be-posts : 1
		be-recent-posts : 9
		be-uber-menu : 29
		be-video-box : 1
		button : 22
		divider : 6
		google_maps : 1
		heading : 137
		html : 2
		icon : 7
		icon-box : 3
		icon-list : 94
		image : 55
		shortcode : 8
		social-icons : 42
		spacer : 5
		text-editor : 14
	wp-post : 1
		text-editor : 1
	wp-page : 12
		be-counter : 6
		be-events : 1
		be-events-carousel : 1
		be-icon-box : 3
		be-logo-carousel : 1
		be-members : 1
		be-members-carousel : 1
		be-posts-carousel : 1
		be-video-box : 3
		button : 9
		divider : 2
		google_maps : 1
		heading : 41
		icon : 1
		icon-box : 3
		icon-list : 1
		image-carousel : 1
		tabs : 1
		text-editor : 12

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 332022-05-04 14:51:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-04 14:51:54 [info] elementor::elementor_updater Started 
2022-05-04 14:51:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-04 14:51:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-04 14:51:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-04 14:51:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-06 22:43:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-06 22:43:42 [info] elementor-pro::elementor_pro_updater Started 
2022-05-06 22:43:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-06 22:43:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-06 22:43:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-06 22:43:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-12 18:23:29 [info] elementor::elementor_updater Started 
2022-05-12 18:23:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-12 18:23:34 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-12 18:23:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev7',
)]
2022-05-12 18:56:36 [info] elementor-pro::elementor_pro_updater Started 
2022-05-12 18:56:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-12 18:56:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-12 18:56:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.8.0-dev11',
)]

JS: showing 5 of 5JS: 2022-03-29 21:43:28 [error X 1][https://emmanjokufoundation.org/welcome/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:56:365] null is not an object (evaluating \'this.conditionsConfig.getOptions\') 
JS: 2022-04-21 18:51:01 [error X 1][https://emmanjokufoundation.org/welcome/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:406153] Cannot read properties of null (reading \'id\') 
JS: 2022-05-04 09:03:24 [error X 1][https://emmanjokufoundation.org/welcome/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view11449\") has already been destroyed and cannot be used. 
JS: 2022-05-06 08:50:47 [error X 1][https://emmanjokufoundation.org/welcome/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view45569\") has already been destroyed and cannot be used. 
JS: 2022-05-06 08:50:47 [error X 1][https://emmanjokufoundation.org/welcome/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view45610\") has already been destroyed and cannot be used. 

PHP: showing 4 of 4PHP: 2022-03-29 23:25:13 [notice X 1][/home3/emmanion/public_html/welcome/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-01 06:41:32 [notice X 3][/home3/emmanion/public_html/welcome/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-04 15:30:56 [notice X 64][/home3/emmanion/public_html/welcome/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-12 21:30:26 [notice X 2][/home3/emmanion/public_html/welcome/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home3/emmanion/public_html/welcome/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home3/emmanion/public_html/welcome/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home3/emmanion/public_html/welcome/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home3/emmanion/public_html/welcome/wp-content/plugins/custom-facebook-feed/inc/CFF_Elementor_Base.php(29): Elementor\Controls_Manager -> register_control()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Piotnet Addons For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @owoblow2020 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
