### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by MissPNixon** [elementor/elementor#18637]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Ok so I'm not doing a deep search for info on an experimental feature. I'm just letting you know that I noticed the NOTES icon on my Wordpress Admin bar and clicked it and nothing happened. That's all. Ask if you need more detail than that.

### Steps to reproduce

Log into Wordpress and click the Notes icon on the admin bar while on the home page of your site.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

`<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Source distribution v5.7.29 |  
PHP Version: | 8.1.0 |  
PHP Memory Limit: | 256M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	Source distribution v5.7.29	
PHP Version:	8.1.0	
PHP Memory Limit:	256M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	512M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	5.9.3	
Site URL:	https://www.eahwp.com	
Home URL:	https://www.eahwp.com	
WP Multisite:	No	
Max Upload Size:	512 MB	
Memory limit:	40M	
Max Memory limit:	256M	
Permalink Structure:	/%postname%/	
Language:	en-US	
Timezone:	America/New_York	
Admin Email:	MissPNixon@gmail.com	
Debug Mode:	Inactive	
Theme		
Name:	soledad	
Version:	8.1.6	
Author:	PenciDesign	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36	
Active Plugins		
[DreamHost Panel Login](https://www.dreamhost.com/wordpress/) - 1.0.0	By [DreamHost, danielbachhuber](https://dreamhost.com/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.6.5	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.7.0	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[Envato Market](https://envato.com/market-plugin/) - 2.0.7	By [Envato](https://envato.com/)	
[Penci Shortcodes & Performance](http://pencidesign.com/) - 4.9	By [PenciDesign](http://themeforest.net/user/pencidesign?ref=pencidesign)	
[Yoast Duplicate Post](https://yoast.com/wordpress/plugins/duplicate-post/) - 4.4	By [Enrico Battocchi & Team Yoast](https://yoast.com/)	
[Yoast SEO](https://yoa.st/1uj) - 18.8	By [Team Yoast](https://yoa.st/1uk)	
[Yoast SEO Premium](https://yoa.st/2jc) - 18.4	By [Team Yoast](https://yoa.st/2jc)	
Elementor Experiments		
Optimized DOM Output: 	Active by default
Improved Asset Loading: 	Active by default
Improved CSS Loading: 	Active by default
Inline Font Icons: 	Inactive by default
Accessibility Improvements: 	Active by default
Import Export Template Kit: 	Active by default
Additional Custom Breakpoints: 	Active by default
Hide native WordPress widgets from search results: 	Active by default
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Inactive by default
Default to New Theme Builder: 	Active by default
Landing Pages: 	Active by default
Color Sampler: 	Active by default
Favorite Widgets: 	Active by default
Admin Top Bar: 	Active by default
Page Transitions: 	Active by default
Notes: 	Active by default
Form Submissions: 	Active by default
Scroll Snap: 	Active by default`

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help. unfortunately, we couldn't reproduce your issue. I suggest you contact support.

Thanks.
