### ISSUE TITLE
🐞 Bug report: Missing Include by field option when setting query source to related on Post widget

### ISSUE THREAD

**Issue by bomsbong** [elementor/elementor#18633]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating both Elementor and Elementor Pro to latest version, when you choose related as query source on post widget Include By field is gone. 
![image](https://user-images.githubusercontent.com/25917185/168207845-7f71d2b6-befe-4981-87bb-24f1b99527b8.png)

### Steps to reproduce

1. Update both elementor and elementor pro to latest version
2. Use post widget and choose related as query source

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.2.34
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://devwptest.esrgear.com
	Home URL: https://devwptest.esrgear.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: globalsupport@esrgear.com
	Debug Mode: Inactive

== Theme ==
	Name: ESR
	Version: 1.0.0
	Author: Cross Border Digital
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.10
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

== Active Plugins ==
	Ajax Search Lite
		Version: 4.9.5
		Author: Ernest Marcinko

	Custom links in Elementor Image Carousel
		Version: 1.1.0
		Author: Charlie Etienne

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0
		Author: Elementor.com

	Klaviyo
		Version: 3.0.3
		Author: Klaviyo, Inc.

	Max Mega Menu
		Version: 2.9.6
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.2.4
		Author: megamenu.com

	Post Views Counter
		Version: 1.3.11
		Author: Digital Factory

	Simple Custom CSS and JS
		Version: 3.39
		Author: SilkyPress.com

	Ultimate Addons for Elementor
		Version: 1.36.6
		Author: Brainstorm Force

	WooCommerce
		Version: 6.5.0
		Author: Automattic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	Yoast SEO
		Version: 18.8
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 8 of 8PHP: 2022-04-21 00:36:44 [notice X 15][/data/www2/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-02 09:59:54 [error X 1][/data/www2/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /data/www2/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /data/www2/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(24, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /data/www2/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /data/www2/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /data/www2/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /data/www2/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /data/www2/wp-admin/admin-ajax [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 03:54:59 [error X 1][/data/www2/wp-content/plugins/elementor-pro/plugin.php::443] Uncaught Error: Class 'ElementorPro\Core\App\App' not found in /data/www2/wp-content/plugins/elementor-pro/plugin.php:443
Stack trace:
#0 /data/www2/wp-content/plugins/elementor-pro/plugin.php(109): ElementorPro\Plugin->__construct()
#1 /data/www2/wp-content/plugins/elementor-pro/plugin.php(472): ElementorPro\Plugin::instance()
#2 /data/www2/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/data/www2/wp-c...')
#3 /data/www2/wp-includes/class-wp-hook.php(307): elementor_pro_load_plugin('')
#4 /data/www2/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 /data/www2/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /data/www2/wp-settings.php(450): do_action('plugins_loaded')
#7 /data/www2/wp-config.php(96): require_once('/data/www2/wp-s...')
#8 /data/www2/wp-load.php(50): require_once('/data/www2/wp-c...')
#9 /data/www2/wp-admin/admin-ajax.php(22): require_once('/data/www2/wp-l...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 03:55:31 [error X 2][/data/www2/wp-content/plugins/elementor-pro/plugin.php::435] Uncaught Error: Class 'ElementorPro\Core\Connect\Manager' not found in /data/www2/wp-content/plugins/elementor-pro/plugin.php:435
Stack trace:
#0 /data/www2/wp-content/plugins/elementor-pro/plugin.php(109): ElementorPro\Plugin->__construct()
#1 /data/www2/wp-content/plugins/elementor-pro/plugin.php(472): ElementorPro\Plugin::instance()
#2 /data/www2/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/data/www2/wp-c...')
#3 /data/www2/wp-includes/class-wp-hook.php(307): elementor_pro_load_plugin('')
#4 /data/www2/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 /data/www2/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /data/www2/wp-settings.php(450): do_action('plugins_loaded')
#7 /data/www2/wp-config.php(96): require_once('/data/www2/wp-s...')
#8 /data/www2/wp-load.php(50): require_once('/data/www2/wp-c...')
#9 /data/www2/wp-admin/admin-ajax.php(22): require_once('/data/www2/wp-l...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 04:17:10 [error X 21][/data/www2/wp-content/plugins/elementor-pro/elementor-pro.php::57] require(): Failed opening required '/data/www2/wp-content/plugins/elementor-pro/plugin.php' (include_path='.:/usr/share/pear:/usr/share/php') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 04:54:46 [notice X 1][/data/www2/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 04:59:58 [error X 1][/data/www2/wp-content/plugins/elementor-pro/modules/forms/submissions/component.php::168] Uncaught Error: Class 'ElementorPro\Modules\Forms\Submissions\Database\Migration' not found in /data/www2/wp-content/plugins/elementor-pro/modules/forms/submissions/component.php:168
Stack trace:
#0 /data/www2/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Forms\Submissions\Component->ElementorPro\Modules\Forms\Submissions\{closure}('')
#1 /data/www2/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /data/www2/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /data/www2/wp-admin/admin-ajax.php(45): do_action('admin_init')
#4 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 07:10:18 [error X 17][/data/wptest/wp-content/plugins/elementor/modules/page-templates/module.php::270] Allowed memory size of 134217728 bytes exhausted (tried to allocate 1236992 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-04-25 06:30:49 [error X 10][https://wptest.esrgear.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-04-25 06:41:45 [error X 148][https://wptest.esrgear.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:375483] Cannot read properties of undefined (reading \'get\') 
JS: 2022-04-25 08:26:09 [error X 14][https://wptest.esrgear.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.4:2:13282] r.get is not a function 
JS: 2022-04-29 02:26:07 [error X 3][https://wptest.esrgear.com/wp-content/plugins/ultimate-elementor/assets/min-js/uael-nav-menu.min.js?ver=1.36.5:1:18991] Cannot read properties of undefined (reading \'includes\') 
JS: 2022-05-10 02:33:51 [error X 1][https://wptest.esrgear.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2872\") has already been destroyed and cannot be used. 

Log: showing 10 of 102022-04-28 02:34:55 [info] elementor::elementor_updater Started 
2022-04-28 02:34:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-28 02:34:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-28 02:34:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-28 02:34:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-11 09:48:31 [info] elementor-pro::elementor_pro_updater Started 
2022-05-11 09:48:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-11 09:48:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-11 09:48:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.0',
)]
2022-05-11 09:48:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.0',
)]

== Elementor - Compatibility Tag ==
	
	Custom links in Elementor Image Carousel: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by Bovelett** [comment]
Hey @bomsbong From experience, I can tell you that it's a good idea to make your bug report title more descriptive.

**Comment by editor-acd** [comment]
I have also observed that. I have submitted a bug report where the query is not working as expected. It is not listing the specific category. It is listing all the posts.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.7.2

Feel free to update

Thanks!
