### ISSUE TITLE
Mark a font family as favorite

### ISSUE THREAD

**Issue by dudaster** [elementor/elementor#1863]
Like the way you can customize a palette of colors in Color Picker we should have font family picker and also predefined font matches. This fonts should a appear first in the font family drop down before all the google fonts list.

This would help a lot to create a page without a need to check what the font you used before is called.

**Comment by dasigna** [comment]
as an addition maybe generally a good idea to set specific fonts within el-settings and prevent the complete google list from showing up?

and as another one: a way to implement/show up custom (self hosted) fonts.
had this one before, and while the custom fonts are selected within theme (GP) and correctly picked up by elementor they do not show up within elementors font list... but would be quite handy.

**Comment by black-eye** [comment]
+1

**Comment by dudaster** [comment]
Let's do it guys!

**Comment by laboiteare** [comment]
+10 
Hi Elementor Team.. 

Plllleassse, add this.. It's essential for people making website every days !
(ps : Or at least a WordPress filter to remove some fonts !)

**Comment by shilo-ey** [comment]
From now on (Elementor 3.0.0) you can create your own preset of Global Font and set whatever font family you like.

Enjoy!
