### ISSUE TITLE
✔️ 🚀 Feature Request: css transform for section & container

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18648]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

As you know, this great feature was added in previous versions. But it is really strange why it can not be used on containers and sections!
In fact, unlike what has just been added, I think the css transform feature is much more useful on sections and containers. In fact, it is much better if this option is added to containers and sections in addition to widgets. Just an example of why this feature should be added for sections and containers...

Suppose there is [such a thing](https://prnt.sc/ldrezHhijwUA) as three containers. We want 5 Px to move upwards when each of these containers are hovering. Unfortunately, this is not possible now.

### Describe the solution you'd like

Please add the css transform feature to sections and containers.

**Comment by rami-elementor** [comment]
CSS transforms added to Elementor Core 3.5.0.

From the 3.5.0 changelog:

* New: Introducing CSS Transform – rotate, scale, skew, offset and flip any element ([#12451](https://github.com/elementor/elementor/issues/12451))

**Comment by 79ho3ein** [comment]
hi @rami-elementor.
Yes, I mentioned at the beginning of my request that this feature has already been added. In fact, my request was that you please add this feature to the container and section as well. Because this feature is not currently available for section and container.
https://prnt.sc/nD06NmGFGoeG

**Comment by Michaelgimii** [comment]
Hi @udidol , Will this great feature be added in version 3.9? (According to the evidence of Pull requests)

**Comment by nicholaszein** [comment]
Hey @79ho3ein and @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

Thanks for your contribution! 🙏 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
