### ISSUE TITLE
✅ 🚀 Feature Request: Title and Price automatically aligned

### ISSUE THREAD

**Issue by datascientistgonzo** [elementor/elementor#18640]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The pictures and the price in the products widget are not aligned, if the pics have different sizes or the title of the product differs in length.

### Describe the solution you'd like

It would be great, if you could add an automatic alignment function for the pictures (if they have different sizes), title and price.

### Describe alternatives you've considered

Currently I am helping myself with this CSS code:

/** Fixed height on images **/

    .inside-wc-product-image {
        width: 100%;
    }
    .woocommerce ul.products li.product a img {
        height: 280px; /* adjust height */
        object-fit: contain;
    }

/** Fixed height on product titles **/

  selector .woocommerce-loop-product__title {
    height: 65px;
    min-height: 65px;
  }

**Comment by nicholaszein** [comment]
Hello there @datascientistgonzo!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.9.0! 🥳 

You can now build your own template for Products, and align everything the way you want. This is a replacement for the Products and Archive Products widget, which will not be further developed in favor of the Loop Grid and Loop Carousel widgets.

For this reason, we are closing this issue as solved.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
