### ISSUE TITLE
Global site setting🐞 Bug

### ISSUE THREAD

**Issue by xeonsteel** [elementor/elementor#18656]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

You guys REALLY NEED to fix the screwed up custom breakpoints ASAP! When setting custom breakpoints, it will NOT set AT ALL. It continues to revert back to the default. WHY is that happening??

Also setting global fonts and global H tags does not work properly either - Fix these please ASAP! It does not show within the pages. Always have to manually set it for every single individual page for fonts and H tags!

### Steps to reproduce

Done everything to fix and NOT working

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

All latest version, Elementor Pro and WordPress

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by xeonsteel** [comment]
Yep, like ive heard githib is worthless - thanks for the non help 👎👎👎🤦‍♂️🤦‍♂️🤦‍♂️SMH
