### ISSUE TITLE
🚀 Feature Request: Enable lazyloading option in Media Carousel widget (Pro)

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#18652]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The Image Carousel widget has lazyloading as an option, but not media carousel.

### Describe the solution you'd like

It would be nice if we could lazy load things in the media carousel.

**Comment by rami-elementor** [comment]
Hi @drawcard 

Elementor Pro 3.7 added lazy loading to the Media Carousel widget.

Quote from the [Changelog](https://elementor.com/pro/changelog/):

* Tweak: Added lazy load option to Media Carousel, Reviews and Testimonial Carousel widgets
