### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by akaakaakaakaaka** [elementor/elementor#18651]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I was seeing this error when navigating to my website:
`Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/customer/www/amandakay.design/public_html/wp-content/plugins/dragfy-addons-for-elementor/elementor/widgets/dragfy-addons-fancy-heading.php:174 Stack trace: #0 /home/customer/www/amandakay.design/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): DragfyAddons\Elementor\Widgets\Dragfy_Addons_Fancy_Heading->_register_controls()`

After deactivating Dragfy, I saw this instead:
`Class 'Elementor\Scheme_Typography' not found in /home/customer/www/amandakay.design/public_html/wp-content/plugins/webify-addons/elementor/widgets/section-heading.php:180 Stack trace: #0 /home/customer/www/amandakay.design/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Webify_Section_Heading_Widget->_register_controls() #1 /home/customer/www/amandakay.design/public_html/wp-content/plugins/elementor`

After deactivating Webify, my site partially loaded. 
Now that I've tried reactivating both plugins to reproduce the error messages, now my site just endlessly loads instead of showing those errors again. All plugins are up to date.

I'm not a developer; I was given this link to report this bug info my Elementor support, so if there's anything missing or incomplete above, please let me know.

### Steps to reproduce

Please see above

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://amandakay.design
	Home URL: https://amandakay.design
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 128M
	Max Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: amandakay1@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Webify
	Version: 4.4
	Author: themebubble
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

== Active Plugins ==
	Breadcrumb NavXT
		Version: 7.0.2
		Author: John Havlik

	Change Password Protected Message
		Version: 1.2.5
		Author: pipdig

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Codestar Framework
		Version: 2.1.5
		Author: Codestar

	Conditional Menus
		Version: 1.2.0
		Author: Themify

	Contact Form 7
		Version: 5.5.6
		Author: Takayuki Miyoshi

	Dragfy Addons for Elementor
		Version: 1.0.2
		Author: Dragfy

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0
		Author: Elementor.com

	Enable Media Replace
		Version: 3.6.3
		Author: ShortPixel

	Envato Market
		Version: 2.0.7
		Author: Envato

	Html5 Video Player
		Version: 2.5.5
		Author: bPlugins LLC

	MaxButtons
		Version: 9.2
		Author: Max Foundry

	MC4WP: Mailchimp for WordPress
		Version: 4.8.7
		Author: ibericode

	Multiple Themes
		Version: 7.1.1
		Author: David Gewirtz

	Newsletter
		Version: 7.4.2
		Author: Stefano Lissa & The Newsletter Team

	One Click Demo Import
		Version: 3.1.1
		Author: OCDI

	Remove Protected In Title
		Version: 3.1
		Author: Dejan Blazeski

	Shortcodes Ultimate
		Version: 5.12.0
		Author: Vladimir Anokhin

	SiteGround Central
		Version: 2.0.4
		Author: SiteGround

	SiteGround Optimizer
		Version: 7.0.9
		Author: SiteGround

	Smash Balloon Instagram Feed
		Version: 6.0.5
		Author: Smash Balloon

	UpdraftPlus - Backup/Restore
		Version: 1.22.12
		Author: UpdraftPlus.Com, DavidAnderson

	Webify Addons
		Version: 4.3
		Author: themebubble

	WooCommerce
		Version: 6.4.1
		Author: Automattic

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 4 of 4JS: 2020-08-28 15:30:48 [error X 25][http://amandakay.design/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:470394] Cannot read property \&#039;document\&#039; of undefined 
JS: 2020-09-01 22:16:09 [error X 8169][http://amandakay.design/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read property \&#039;clone\&#039; of null 
JS: 2020-09-01 22:16:16 [error X 219][http://amandakay.design/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read property \&#039;changestop\&#039; of null 
JS: 2020-09-02 00:21:20 [error X 140][http://amandakay.design/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.5:2:133297] Cannot read property \&#039;get\&#039; of undefined 

PHP: showing 4 of 4PHP: 2020-08-28 16:06:13 [notice X 1][/home/amandak5/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-06-27 08:44:53 [notice X 49][/home/customer/www/amandakay.design/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1428] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-30 02:21:45 [notice X 221][/home/customer/www/amandakay.design/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-15 00:47:02 [notice X 1][/home/customer/www/amandakay.design/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 322022-04-14 08:57:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 08:57:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 08:57:37 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2022-04-14 08:57:37 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2022-04-14 08:57:37 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2022-04-14 08:57:37 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2022-04-14 08:57:37 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-04-14 08:57:37 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-04-14 08:57:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.6.4',
)]
2022-04-14 08:57:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.6.4',
)]
2022-04-30 02:21:45 [info] elementor::elementor_updater Started 
2022-04-30 02:21:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-30 02:21:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-30 02:21:45 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2022-04-30 02:21:45 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2022-04-30 02:21:45 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2022-04-30 02:21:45 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2022-04-30 02:21:45 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-04-30 02:21:45 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-04-30 02:21:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]

== Elementor - Compatibility Tag ==
	
	Dragfy Addons for Elementor: Compatibility not specified
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @akaakaakaakaaka ,

You are using the "**dragfy-addons-for-elementor**" addon. This addon is uses the `Elementor\Scheme_Typography` class. The class was deprecated.

You can either deactivate the addon or contact the addon developers and ask them to [replace deprecated classes](https://developers.elementor.com/docs/deprecations/). Our dev docs explain how to do that. It's a simple process.
