### ISSUE TITLE
🐞 Bug report: Deprecated: The $control_id argument is deprecated since version 3.5.0! in /home4/slqyormy/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php on line 301

### ISSUE THREAD

**Issue by Mirasawaf99** [elementor/elementor#18650]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I can’t edit with element or 

Deprecated: The $control_id argument is deprecated since version 3.5.0! in /home4/slqyormy/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php on line 301

### Steps to reproduce

I open the template home page 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.0.16
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://slq.yor.mybluehost.me
	Home URL: https://slq.yor.mybluehost.me
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: mirasawaf99@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.3
		Author: Automattic

	Bluehost
		Version: 2.10.0
		Author: Bluehost

	Bluehost Website Builder
		Version: 1.0-2626 : 20220421_095804
		Author: Newfold Digital

	Creative Mail by Constant Contact
		Version: 1.5.3
		Author: Constant Contact

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.10
		Author: Brainstorm Force, Nikhil Chavan

	ElementsKit Lite
		Version: 2.5.9
		Author: Wpmet

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Essential Addons for Elementor
		Version: 5.1.2
		Author: WPDeveloper

	Google Analytics for WordPress by MonsterInsights
		Version: 8.5.2
		Author: MonsterInsights

	Google Listings and Ads
		Version: 1.12.8
		Author: WooCommerce

	Jeg Elementor Kit
		Version: 2.4.2
		Author: Jegstudio

	Jetpack
		Version: 10.9
		Author: Automattic

	Kirki Customizer Framework
		Version: 4.0.23
		Author: David Vongries

	MailPoet 3 (New)
		Version: 3.89.0
		Author: MailPoet

	MetForm
		Version: 2.1.6
		Author: Wpmet

	OptinMonster
		Version: 2.6.12
		Author: OptinMonster Popup Builder Team

	Rollback Update Failure
		Version: 2.2.0
		Author: Andy Fragen, Ari Stathopolous, Colin Stewart, Paul Biron

	Sticky Header Effects for Elementor
		Version: 1.4.8
		Author: Rwattner

	Unlimited Elements for Elementor
		Version: 1.5.12
		Author: Unlimited Elements

	WPForms Lite
		Version: 1.7.4.1
		Author: WPForms

	Yoast SEO
		Version: 18.8
		Author: Team Yoast

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elements Usage ==
	

<br />
<b>Warning</b>:  Undefined array key "title" in <b>/home4/slqyormy/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php</b> on line <b>89</b><br />

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 6 of 6PHP: 2022-05-14 15:02:05 [notice X 35][/home4/slqyormy/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-14 17:22:29 [warning X 6][/home4/slqyormy/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home4/slqyormy/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php:301) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-14 17:29:50 [notice X 1][/home4/slqyormy/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::720] ob_end_clean(): Failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-14 22:21:40 [warning X 1][/home4/slqyormy/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-14 22:28:10 [warning X 1][/home4/slqyormy/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home4/slqyormy/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php:171) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-14 22:29:47 [warning X 1][/home4/slqyormy/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home4/slqyormy/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php:304) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-05-14 17:17:32 [error X 7][https://slq.yor.mybluehost.me/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.6.5:2:32470] Can\'t find variable: elementorFrontendConfig 

Log: showing 15 of 152022-05-14 22:24:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev7',
)]
2022-05-14 22:24:32 [info] elementor::elementor_updater Started 
2022-05-14 22:24:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-14 22:24:34 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-14 22:24:34 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-05-14 22:24:34 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-05-14 22:24:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev7',
)]
2022-05-14 22:28:09 [notice] Re-migrate 3.0.0 globals: Start 
2022-05-14 22:28:09 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2022-05-14 22:28:09 [notice] System typography is disabled. nothing to do. 
2022-05-14 22:28:09 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2022-05-14 22:28:09 [notice] System colors are disabled. nothing to do. 
2022-05-14 22:28:09 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2022-05-14 22:28:09 [notice] Custom colors already exist. nothing to do. 
2022-05-14 22:28:09 [notice] Re-migrate 3.0.0 globals: End 

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Jeg Elementor Kit: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

**Comment by ishnechmad** [comment]
see:
https://developers.elementor.com/v3-5-planned-deprecations/

**Comment by rami-elementor** [comment]
Hi @Mirasawaf99,

One of your Elementor addon is using deprecated code.

You need to disable your plugin one-by-one until you find the one that breaks your site.

When you find the plugin / Elementor addons, please contact the addon developers and ask them to [update the way the are registering controls](https://developers.elementor.com/docs/deprecations/advanced-example/#controls). Our dev docs have more information about the [Elementor deprecation process](https://developers.elementor.com/docs/deprecations/).

**Comment by ARONDALE** [comment]
BlueHost tells me it is actually PHP v8.x itself that is not compatible with Elementor and that they need to update their code to be compatible with the latest version of PHP (v8.x). I tried to have them roll back v7.x so that I can at least use the Elementor WP editor again. However, one still shows PHP code, visually, in the header and one site does not (prod vs staging) - wp-content/plugins/elementor/modules/dev-tools/deprecation.php on line 301

**Comment by rami-elementor** [comment]
It's not a PHP issue. It's an addon using outdated code. We are familiar with this error message. It accrues when addons don't upgrade their code.

**Comment by SirRossiAir** [comment]
Disabling Bluehost Website Builder Plugin Worked for me.

**Comment by AinmoRD** [comment]
You need to uninstall elementor and install version 4.4.1, because the new version is not compatible with some wordpress plugins, here is the link> https://drive.google.com/drive/folders/1QQwtLMQAmO6NDTtqdQpHU2pMjeLqPQ3v

**Comment by witty-code** [comment]
> You need to uninstall elementor and install version 4.4.1, because the new version is not compatible with some wordpress plugins, here is the link> https://drive.google.com/drive/folders/1QQwtLMQAmO6NDTtqdQpHU2pMjeLqPQ3v

Elementor is now at version 3.7.7 and still far from 4.4.1
You can downgrade the Elementor version through the WordPress control panel >> Elementor >> Tools
And you don't need to download it from unofficial sources…

**Comment by Rahisaiful** [comment]
### Solution 

This is not elementor bug. I faced the same problem on "Enter Addons" plugin when I updated elementor. This is the custom control Registering depreciation issue. Elementor changed the custom control Registering hook and method name from 3.5 version. I got the solution from the documentation link.

https://developers.elementor.com/docs/managers/registering-controls/
