### ISSUE TITLE
✅ 🚀 Feature Request: Integration of post widget and post archive - Integration of Products widget and Product Archive.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18669]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi

In elementor, we have 4 widgets, which is great if they integrate with each other. In fact, 4 widgets will become 2 widgets. 
1-**Post widget** and **post archive widget** merge.
2-**Products widget** and **Product Archive widget** also merge.

That would be really great. Version 3.7 elementor [integrated WooCommerce widgets](https://prnt.sc/omBHkNqzIyde) perfectly. But this situation can be applied to the 4 widgets mentioned above.
The jet woobuilder plugin has already implemented this and can be a good Pattern. In this plugin, we add the product grid widget. By default, this widget cannot display products in an archive.But if we want to enable the archive for this widget, it is enough to enable [this option](https://prnt.sc/UeEcqBiLkqxj) in this widget. Therefore, this method is much smarter than the current method in elementor. Please check this if possible @avivu
Finally, it's great if you check out the product grid widget plug-in jet woobuilder. This plugin is great for developing WooCommerce in elementor.
### Describe the solution you'd like

Merge post widget and post archive. Therefore, integrating them into a single widget will require the Use Current Query option. If we enable this option, the posts will be displayed as archives.
In addition to the above, the Products widget and Product Archive can also be integrated. I think this method will be very smart.

thank you!

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

I found this one during my triaging. The request was solved with the introduction of the **Loop Builder** on **Elementor Pro v3.8.0 and v3.9.0** for WooCommerce.

✅ For this reason, I'm closing this issue as solved.

🥂 Cheers!
