### ISSUE TITLE
🐞 Bug in container > Column direction

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18662]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

1- In the container, if the direction is columnar, horizontal scrolling is activated. But if it is on the row, there is no horizontal scrolling and there is no problem.

https://user-images.githubusercontent.com/77163248/168568648-12f906dd-b327-452d-9cab-b0c94a6d11f7.mp4

In fact, there is horizontal scrolling in the column, reverse column and reverse row directions. And it does not appear only in the direction of the row of this horizontal scroll. It should be noted that this bug is solved by hiding the overflow, but by default this bug exists for containers.

### Steps to reproduce

The steps are shown in the video above. Just note that there must be a widget inside the container for this bug to occur.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!
