### ISSUE TITLE
Closing the Popup with Scroll-up

### ISSUE THREAD

**Issue by cheithan** [elementor/elementor#18671]
Hello everyone,

I'm in need of your support. I have build my site using Elementor Pro. Recently, I have triggered a popup with scroll down. And would like to close with scroll up. I am aware that Elementor doesn't provide this feature as of yet. I have contacted the support but didn't get a solution. Can you please help me with the code or some other ways to close the Popup on Scroll up(90%).

Really appreciate your time and effort.

**Comment by rami-elementor** [comment]
Hi @cheithan ,

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
