### ISSUE TITLE
free Elementor version 3.6.5 SimpleMenu Misbehaviour

### ISSUE THREAD

**Issue by PowerUser1234** [elementor/elementor#18703]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Dear Elementor,

I am running **Windows 10 64 bit Home Edition**.  My defalt web browser is **Firefox 64 bit v 100.0.2**. I have been using the presently installed and updated **free Elementor version 3.6.5** page builder on a main page area for my website, to act as a hub page for the other pages that are part of my web page as a whole.  I have been working from the free initial Theme, 
**Twenty Twenty-One.**

I installed the Windows XAMPP framework from the following file name:

**xampp-windows-x64-7.4.27-2-VC15-installer.exe**

and installed and updated to **WordPress version 6** from the following file:

**wordpress-5.9.2.zip**

I installed and got started using WordPress using the following online tutorial:

[https://www.wpbeginner.com/wp-tutorials/how-to-create-a-local-wordpress-site-using-xampp/](https://www.wpbeginner.com/wp-tutorials/how-to-create-a-local-wordpress-site-using-xampp/)

From there I have added and upgraded WordPress itself and the plugins as asked, from which point I have had no problems.

I have included a screenshot of the problem that is occuring.  When the browser area is smaller, such as on a smart phone, or just plain resized and shrunk on a modern PC's wide screen, things go wrong for the free SimpleMenu.

The problem is not the inclusion of the Hamburger button and the auto conversion to a Vertical menu from a Horizontal one.
The problem is that I can't centre this new menu, by top, left and right outer borders on screen, or compact its width to the widest menu item link name, a text derived width, by default or setting.

Is there a simple, systematic solution I can use, or can this bug be updated in the plugin itself and the update broadcasted to everyone, so that I can click on 'update' and obtain the correction logic, and a correct working SimpleMenu, automatically and by default?

### Steps to reproduce

I have uploaded the image of my problem in the Elementor Facebook Group, which can be seen with another copy of this article, at

[https://www.facebook.com/groups/Elementors/permalink/4861465867312494/](https://www.facebook.com/groups/Elementors/permalink/4861465867312494/)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

**Windows 10 64 bit Home Edition.
Firefox 64 bit v 100.0.2.
Windows XAMPP installatin file: xampp-windows-x64-7.4.27-2-VC15-installer.exe.
WordPress version 6
PHP7, not 8.
free Elementor version 3.6.5.
WordPress theme Twenty Twenty-One.**

**Comment by PowerUser1234** [comment]
Are there any live humans who have noticed that this Discussion of mine is an issue, and has been officially labelled as a bug?
Does this mean that people are working on this issue, or what does it mean?  Can a human being kindly reply to me either 
in this GitHub Issue, the corresponding GitHub Discussion at 

[https://github.com/elementor/elementor/discussions/18708](https://github.com/elementor/elementor/discussions/18708) 

or in my Facebook group post at 

[https://www.facebook.com/groups/Elementors/permalink/4861465867312494/](https://www.facebook.com/groups/Elementors/permalink/4861465867312494/)

please, kindly, so I know what is going on in terms of this problem?

**Comment by rami-elementor** [comment]
Hi @PowerUser1234 ,

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by PowerUser1234** [comment]
Dear Rami,

I have downloaded and added theme 'Hello Elementor' and made it active,
just as you have suggested.  It makes no difference to the non-centering
and non-compacting of my now vertical SimpleMenu, when the size of
the web browser window is size changed so much that the horizontal menu
can't fit, and gets changed to a vertical menu within one hamburger button.

Unfortunately, what you suggest doesn't make any difference to my problem.

I think that this may be a problem within the component.

I can't give you an internet URL for the website, since clearly it is in no fit state
to be on the live internet.

Would you like me to archive the website that I have, and then using something
like Smash to give you the archives, so that you can load it in its present state,
plugins and all, to try and obtain and see my problem?

I use either the free version of WPvivid, or the free version of All-in-One WP Migration.

What do you suggest from here, and if you want my website archive files, which archive
plugin would you like me to use?

Zachary Mitchell.

Z.M.
________________________________

**Comment by PowerUser1234** [comment]
Dear Rami,

I have attempted what you suggested to me in your last email.
It makes no difference, to now avail.

-Are you a part of the Global Elementor Community, that is set up within Facebook?

How are you going with my issue? I believe it is a problem inside
the plugin.

Can you email reply to me when you can with an update at your end?

If you like, I can organise sending an archive of my website across.

I use either the free version of WPvivid, or the free version of All-in-One WP Migration.

I await your response.  I do need to iron this bug out of my website, because it's can't quite
go up with these sorts of things going wrong with it, particularly for the sake of smart phones.

I do await!

Zachary Mitchell.

Z.M.
________________________________

**Comment by PowerUser1234** [comment]
To Rami,

Are you the person who has closed my bug at

https://github.com/elementor/elementor/issues/18703


? What does this mean?  Will the problem I have be addressed and
corrected as a bug?  Will it just be entirely ignored in its present closed state?
I need this problem fixed for my website.  Verdi Heinz doesn't seem to be
responding to direct Facebook messages.  To get a solution, what should I do,
and where should I go, what should happen, from here?

Zachary Mitchell.

Z.M.
________________________________

**Comment by PowerUser1234** [comment]
To Rami,

Are you the person who has closed my bug at

https://github.com/elementor/elementor/issues/18703
[https://opengraph.githubassets.com/472faf73bba4e060261cdbc19a6e821ad16a66b69a92f2f45a899c9a17ade878/elementor/elementor/issues/18703]<https://github.com/elementor/elementor/issues/18703>
free Elementor version 3.6.5 SimpleMenu Misbehaviour #18703<https://github.com/elementor/elementor/issues/18703>
Prerequisites I have searched for similar issues in both open and closed tickets and cannot find a duplicate. The issue still exists against the latest stable version of Elementor. Description Dear Elementor, I am running Windows 10 64 b...
github.com


-What does this mean?  Will the problem I have be addressed and
corrected as a bug?  Will it just be entirely ignored in its present closed state?

-I need this problem fixed for my website.  Verdi Heinz doesn't seem to be
responding to direct Facebook messages.  To get a solution, what should I do,
and where should I go, what should happen, from here?  Can someone please
actively reply to me, informing me about what is going on, please?

Zachary Mitchell.

Z.M

________________________________

**Comment by rami-elementor** [comment]
Hi @PowerUser1234 ,

As I mentioned before, GitHub issues reserved for **bug reports** and **feature requests**. There are many other channels reserved for support. 

If you found a bug, please create a new issue with "steps to reproduce". Our developers need to replicate the issue in their environment to repair that issue.

Attaching a simple screenshot it not helping. You can be using a theme that changes some CSS roles or wrong configuration in the editor.

**Comment by PowerUser1234** [comment]
To Rami,

Are you the person who has closed my bug at

https://github.com/elementor/elementor/issues/18703


? What does this mean?  Will the problem I have be addressed and
corrected as a bug?  Will it just be entirely ignored in its present closed state?
I need this problem fixed for my website.  Verdi Heinz doesn't seem to be
responding to direct Facebook messages.  To get a solution, what should I do,
and where should I go, what should happen, from here?

Zachary Mitchell.

Z.M.

________________________________
