### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Rebeccamumsandmore** [elementor/elementor#18713]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to change a page, Elementor is not loading, so I cannot change anything on my website.

### Steps to reproduce

No idea what happened or why this bug came. It just keeps on loading. Everything on the website works except Elementor. To do with PHP?

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

PHP: 2022-05-23 14:13:46 [notice X 1][/home/mumsandmore.nl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1465] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by rami-elementor** [comment]
Hi @Rebeccamumsandmore ,

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
