### ISSUE TITLE
🐞 Bug report: Clipping Video widget & container

### ISSUE THREAD

**Issue by zierbeek** [elementor/elementor#18714]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

When I use a video widget, it keeps on clipping with the other widgets when using the responsive mobile preview
<img width="359" alt="Schermafbeelding 2022-05-23 om 15 27 03" src="https://user-images.githubusercontent.com/58994651/169830079-2fa5f487-a9f7-4f08-af58-87d28328dcee.png">

### Steps to reproduce

Create container
create other container below
use video widget.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v5.6.49-89.0
	PHP Version: 8.0.19
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://dejaegher-bouwmaterialen.be
	Home URL: https://dejaegher-bouwmaterialen.be
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /nieuws/%postname%/
	Language: nl-BE
	Timezone: 1
	Admin Email: borremans.matthias@outlook.be
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_BE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

== Active Plugins ==
	Advanced AJAX Product Filters for WooCommerce
		Version: 1.6.2
		Author: BeRocket

	Cloudflare
		Version: 4.9.1
		Author: Cloudflare, Inc.

	Code Snippets
		Version: 3.1.0
		Author: Code Snippets Pro

	Cookiebot | GDPR/CCPA Compliant Cookie Consent and Control
		Version: 4.0.3
		Author: Cybot A/S

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.7.0-dev8
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev11
		Author: Elementor.com

	Events Tracker for Elementor
		Version: 1.2.9
		Author: wpl.agency

	Flying Pages by WP Speed Matters
		Version: 2.4.2
		Author: Gijo Varghese

	Headers Security Advanced & HSTS WP
		Version: 4.8.88
		Author: 🐙  Andrea Ferro, Augusto Bombana

	Hotjar
		Version: 1.0.12
		Author: Hotjar

	Opening Hours
		Version: 2.3.0
		Author: Jannik Portz

	Perfmatters
		Version: 1.9.0
		Author: forgemedia

	Rank Math SEO
		Version: 1.0.89.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.11
		Author: Rank Math

	Site Kit by Google
		Version: 1.74.0
		Author: Google

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WP Mail SMTP
		Version: 3.4.0
		Author: WPForms

	YITH WooCommerce Catalog Mode
		Version: 2.10.0
		Author: YITH

== Elementen gebruik ==
	
	archive : 2
		archive-posts : 2
		button : 2
		heading : 6
		image : 2
		theme-archive-title : 2
	footer : 2
		button : 1
		container : 4
		divider : 2
		form : 1
		heading : 8
		icon : 1
		icon-list : 2
		media-carousel : 1
		nav-menu : 2
		social-icons : 2
		text-editor : 4
		theme-site-logo : 2
		wp-widget-widget_op_overview : 2
	header : 2
		button : 1
		html : 1
		nav-menu : 2
		shortcode : 1
		theme-site-logo : 2
	page : 3
		button : 8
		heading : 13
		image : 6
		image-carousel : 4
		testimonial-carousel : 1
		text-editor : 4
	single : 5
		button : 2
		container : 5
		divider : 2
		heading : 12
		icon : 8
		image : 1
		post-info : 4
		post-navigation : 3
		posts : 4
		share-buttons : 6
		social-icons : 1
		spacer : 4
		text-editor : 3
		theme-post-content : 4
		theme-post-featured-image : 2
		theme-post-title : 3
	wp-post : 2
		container : 4
		gallery : 1
		image : 1
		image-box : 1
		spacer : 1
		text-editor : 6
		video : 2
	wp-page : 18
		button : 31
		call-to-action : 2
		container : 63
		flip-box : 3
		form : 1
		google_maps : 1
		heading : 56
		html : 1
		icon-box : 25
		icon-list : 11
		image : 12
		image-carousel : 1
		media-carousel : 1
		posts : 1
		shortcode : 5
		sitemap : 1
		spacer : 1
		tabs : 1
		text-editor : 15
		woocommerce-products : 1
		wp-widget-widget_op_overview : 2
	error-404 : 1
		button : 1
		heading : 3
		image : 3

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Inline lettertype iconen: Actief
	Toegang verbeteringen: Actief
	Import export template kit: Actief
	Extra aangepaste onderbrekingspunten: Actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Actief
	: Standaard inactief
	Flexbox container: Actief
	Default to New Theme Builder: Actief
	Hello Theme Header & Footer: Actief
	Landingspagina's: Actief
	Kleur sampler: Actief
	Favoriete widgets: Actief
	Beheerder bovenste balk: Actief
	Page Transitions: Actief
	Notes: Actief
	Form Submissions: Actief
	Scroll Snap: Actief

== Log ==
	
Log: showing 20 of 342022-05-05 16:58:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev7',
  'to' => '3.8.0-dev8',
)]
2022-05-08 09:18:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev6',
  'to' => '3.7.0-dev7',
)]
2022-05-08 09:18:28 [info] elementor::elementor_updater Started 
2022-05-08 09:18:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-08 09:18:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-08 09:18:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-05-08 09:18:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-05-08 09:18:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev6',
  'to' => '3.7.0-dev7',
)]
2022-05-15 09:17:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev7',
  'to' => '3.7.0-dev8',
)]
2022-05-15 09:17:47 [info] elementor::elementor_updater Started 
2022-05-15 09:17:47 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-15 09:17:48 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-15 09:17:48 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-05-15 09:17:48 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-05-15 09:17:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev7',
  'to' => '3.7.0-dev8',
)]
2022-05-16 14:41:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev8',
  'to' => '3.8.0-dev11',
)]
2022-05-16 14:41:04 [info] elementor-pro::elementor_pro_updater Started 
2022-05-16 14:41:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-16 14:41:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-16 14:41:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev8',
  'to' => '3.8.0-dev11',
)]

PHP: showing 3 of 3PHP: 2022-05-05 12:01:32 [error X 2][/www/wp-content/plugins/elementor-pro/modules/notes/usage.php::161] Uncaught Error: Call to a member function format() on null in /www/wp-content/plugins/elementor-pro/modules/notes/usage.php:161
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/modules/notes/usage.php(43): ElementorPro\Modules\Notes\Usage->get_first_interaction()
#1 /www/wp-content/plugins/elementor-pro/modules/notes/usage.php(27): ElementorPro\Modules\Notes\Usage->get_usage_data()
#2 /www/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Notes\Usage->ElementorPro\Modules\Notes\{closure}(Array)
#3 /www/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#4 /www/wp-content/plugins/elementor/includes/tracker.php(563): apply_filters('elementor/track...', Array)
#5 /www/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#6 /www/wp-includes/class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#7 /www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#8 /www/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#9 /www/wp-cron.php(138): do_action_ref_array('elementor/track...', Array)
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-15 09:17:48 [warning X 1][/www/wp-content/plugins/elementor/includes/base/controls-stack.php::1465] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-19 08:57:07 [warning X 4][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-05-06 07:29:52 [error X 8][https://dejaegher-bouwmaterialen.be/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31710] undefined is not an object (evaluating \'elementorModules.frontend.tools\') 
JS: 2022-05-16 13:39:46 [error X 1][https://dejaegher-bouwmaterialen.be/wp-content/plugins/elementor/assets/js/admin-top-bar.min.js?ver=3.7.0-dev8:2:39463] Can\'t find variable: ReactDOM 
JS: 2022-05-16 13:50:55 [error X 8][https://dejaegher-bouwmaterialen.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev8:2:614350] undefined is not an object (evaluating \'this.store.find((function(T){return T.original===C})).localized\') 
JS: 2022-05-18 11:52:52 [error X 32][https://dejaegher-bouwmaterialen.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev8:2:185527] undefined is not an object (evaluating \'C.originalEvent.data\') 
JS: 2022-05-19 14:58:48 [error X 5][https://dejaegher-bouwmaterialen.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev8:2:461391] null is not an object (evaluating \'this.$currentEditingArea.data\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Niet compatibel
	Events Tracker for Elementor: Compatibiliteit niet gespecificeerd

== Elementor Pro - Compatibility Tag ==

**Comment by williamjclinton** [comment]
Adding the following CSS fixed it for me:

`.elementor-widget-video {
	width:100%;
}`

**Comment by rami-elementor** [comment]
Fixed: https://github.com/elementor/elementor/pull/19153

**Comment by rami-elementor** [comment]
Fixed: https://github.com/elementor/elementor/pull/19153

**Comment by jamieburchell** [comment]
@rami-elementor I'm seeing this today with all latest versions of Elementor on image widgets and it is fixed by making sure the widget is full width. Regression?
