### ISSUE TITLE
✔️ 🚀 Feature Request: Upgrade Swiper Library to 8.x.x

### ISSUE THREAD

**Issue by thejaydip** [elementor/elementor#18724]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Upgrade Swiper Library From 5.x.x to 8.x.x So we can use more latest features of Swiper.

### Describe the solution you'd like

Please Swiper library update to 8.x.x

**Comment by 79ho3ein** [comment]
#18472

**Comment by bdkoder** [comment]
I also agree with you. Swiper Library should be the latest version on Elementor, so we can use all the latest features.

**Comment by bdthemes** [comment]
Please update to the latest version as soon as possible, we are missing tons of new features for it 😟

![Untitled Project](https://user-images.githubusercontent.com/2105615/189060099-3c707fe8-ec3b-4576-985e-d3f5872193be.gif)



![ezgif com-gif-maker](https://user-images.githubusercontent.com/2105615/189067535-866289a9-dfb7-46c3-b26c-d38894f56a81.gif)

**Comment by mapsmarketing** [comment]
Here is another reason why upgrading makes sense: https://github.com/nolimits4web/swiper/issues/6074

**Comment by lesvauriens** [comment]
+1

**Comment by nicholaszein** [comment]
Hello, there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️  Feel free to check it out and update your plugin to the new version!

Cheers 🥂
