### ISSUE TITLE
problem with using button control in elementor custom widget

### ISSUE THREAD

**Issue by nimaaminz** [elementor/elementor#18727]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello 
i search this a lot in internet and nothing found ! 
in [document](https://developers.elementor.com/docs/controls/classes/control-button/) the doc tell us that should use button controls with an event and its ok 
but when you trigger and event like a simple alert in your widget all the widget will trigger their event !! all the widget which i have in my page . imagine we have a button in our widget that's going to send an alert('hello') and we have more widget from our custom widget in screen (for example 4 widget on page) when we click on Alert button control from one of our widget , you will see 4 alert in the screen !! 
I hope that I'm wrong and I don't know about somethings ! but if I'm right I really regretful for choosing this page builder as a professional plugin to developing widgets ! 

** 
I asked this question here cause nobody answered me on forum on Facebook ! 
and its not a bug

**Comment by rami-elementor** [comment]
@nimaaminz Can you attach your code please?
