### ISSUE TITLE
✅ 🐞 Bug report: Slider & Testimonial Widgets break Elementor Theme Builder templates using FlexBox Containers with % or REM padding/margins.

### ISSUE THREAD

**Issue by bowmandesign** [elementor/elementor#18721]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Slider & Testimonial Widgets break Elementor Theme Builder templates using FlexBox Containers different % or REM padding/margins per device size.

A current fix is to make your slider or testimonial widgets as section templates, then import the saved template sections into your page as shortcodes. 

You will need this workaround if you are using FlexBox containers and Custom Breakpoints in your Single Page and Post Theme Builder templates that use % or REM padding on the FlexBox.

Similar and related issues
#18626 #16819 #16591

### Steps to reproduce

1. Make any template with the Elementor Theme Builder
2. Place your Flex Container
3. Set padding with % or REM across different devices
4. Save
5. Make a page or post that leverages your new theme builder template
6. Place a slider or testimonial widget
7. Notice, on mobile the template, page, or post break widths and push the container to the right on mobile.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Out of the box Elementor and Elementor Pro
FlexBox and Custom Breakpoints Experiments on.

**Comment by gameDNAstudio** [comment]
+1, also facing this issue

**Comment by gameDNAstudio** [comment]
Your workaround doesn't work for me tho.

**Comment by bowmandesign** [comment]
Hi @gameDNAstudio, my fix stopped working, the bug came back.

It looks like the only workaround for using Elementor Flexboxes in theme templates is to temporarily turn theme templates off or turn off their display conditions until Elementor fixes Flexbox usage on theme templates. 

Next, on each page or post, set a master container with the same unique padding per device found in your template and the fix allows pages and posts to maintain their padding unique to each device, also Testimonials, sliders, and carousels work again. 

Setting unique padding on every page and post seems daunting and defeats the purpose of containers by forcing customers to use multiple nested containers.

Did you notice that Testimonials, sliders, and carousels only broke on mobile when you had flexboxes in your theme templates?

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core 3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
