### ISSUE TITLE
🚀 Feature Request: Container - Add "calc()" to Container Width (Duplicate of #2219)

### ISSUE THREAD

**Issue by wpeasy** [elementor/elementor#18738]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Easier spacing with the new FlexBox Containers

### Describe the solution you'd like

This FB post raised a question about minimising the use of containers for a layout.
https://www.facebook.com/groups/Elementors/posts/4879687532156994/

Basically, the question is how to get a layout with one full-width row, a second row with 3 columns and equal spacing, with as few Containers as possible.

The accepted answer included fudging the Widget widths on the lower row to get consistent row and column spacing.

It would be great if the Widget and Container "Width" setting allowed for CSS Calc.

So if you have a parent Container with the "Elements Gap" set to 10px. The 3 column row would have 2 x 10px spaces. If we could set the Widget Widths to "calc((100%-20px)/3)", the widths would fit perfectly, and Element spacing would be consistent.

**Comment by nicholaszein** [comment]
Hello @wpeasy! 

This is something that we are planning to bring in the future, and it's part of something more advanced that we've been researching for quite some time. There is already a discussion about this issue, and for the sake of being able to follow all the requests and gather all the feedback as well as understanding the real demand for this new feature, I will be closing this issue and merging it with the issue [#2219](https://github.com/elementor/elementor/issues/2219).

Please continue the conversation there!

Best regards,

Nick
