### ISSUE TITLE
🚀 Feature Request: Custom CSS accessibility improvements

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#18736]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Elementor Pro allows us to add custom CSS to any element, but the prompt window to do so is very small and doesn't suit our needs. I know we can already make it higher, and we can make the editor bar longer so the CSS box becomes bigger. But this isn't the way to go in my opinion.

### Describe the solution you'd like

I suggest to keep the actual CSS mode, but add a button below the custom CSS box, which triggers a popup that gives us the ability to continue editing the site like the navigator. A popup which doesn't go away until you close it in a certain way. This will allow us to continue editing the site while having access to edit the CSS of the certain element.

### Describe alternatives you've considered

Resizing the CSS box, altough it's not the best thing to do.

### Additional context

Custom CSS:
![image](https://user-images.githubusercontent.com/73240206/170126851-5ee464a8-e89c-494f-897c-1dd7dd50041d.png)

A popup like the navigator:
![image](https://user-images.githubusercontent.com/73240206/170126910-d5ead12c-768d-4fd3-9ade-9bf90eb7deaa.png)

**Comment by rami-elementor** [comment]
Hi @pauserratgutierrez ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

Please feel free to contact us again with other feature suggestions.

Regards,
