### ISSUE TITLE
🚀 Feature Request: my idea about specialy trial free basis please make sure all tools for trial openong and after some period these limited please open all modes for developer on free and trial basis as per demand and request period.

### ISSUE THREAD

**Issue by BINPAKISTAN** [elementor/elementor#18740]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

it is requested for elememtor plugin for free for developers and trial basis open for studennts and fresh developer.some time plugin not properly worked.

and please request for help tabs create new button.
thanks

### Describe the solution you'd like

making with help and query button

**Comment by rami-elementor** [comment]
Hi @BINPAKISTAN ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. 

Regards,
