### ISSUE TITLE
🚀 Dedicated section to improve performance

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18757]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I had a suggestion for the elementor team ...
Currently, the settings for improving elementor performance are inside the settings. So, all the settings that are not related to performance improvement are there, so everything looks very crowded.
Therefore, the suggestion is to please add a new section called "Performance" to the elementor settings so that all the options related to the function are there. Exactly like this : https://prnt.sc/bBABS0GL8LbK
This method will be much more efficient to use optimization options.

### Describe the solution you'd like

A dedicated section, for all optimizer options (performance improvement) in site settings : https://prnt.sc/Z4MLTNjGnhT4

**Comment by rami-elementor** [comment]
Hi @Joliamendi , 

Elementor is not an optimization plugin, it's a page builder. Saying that, each Elementor version includes performance improvements, but you don't need to activate them. That are applied when you update the plugin.

Some experimental features are displayed in the "Experiments" tab. But when they will be stable enough, they will be activated by default.
