### ISSUE TITLE
🚀  Disable Emojis, Disable Embed, Disable Google Fonts & Disable JQuery Migrate in elementor.

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18758]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Disable Emojis, Disable Embed, Disable Google Fonts & Disable JQuery Migrate
Please consider the above options to improve performance in elementor.

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment]
Hi @Joliamendi 

You can find optimization plugins that do exactly that - Disable Emojis, Disable Embed, Disable Google Fonts & Disable JQuery Migrate.
