### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by lucyjaynemakeup** [elementor/elementor#18754]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi all, I am having an issue with the mobile responsive mode. The footer appears at the top of my page under the header. So Header, Footer, and then page gallery? Does anyone know why this would happen? I have disabled all plugins so there shouldn't be any conflicts.
I'm using Hello Theme
Footer Template is set to appear on the entire site

### Steps to reproduce

I added the gallery elementor widget and after adding the widget the issue with mobile responsive mode happened

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elementor/core/logger/items/base.php:138 Stack trace: #0 /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elementor/core/logger/items/base.php(124): Elementor\Core\Logger\Items\Base->format_trace() #1 /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elementor/core/logger/loggers/base.php(80): Elementor\Core\Logger\Items\Base->format('raw') #2 /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elementor/core/logger/log-reporter.php(68): Elementor\Core\Logger\Loggers\Base->get_formatted_log_entries(20, false) #3 /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elementor/modules/system-info/reporters/base.php(148): Elementor\Core\Logger\Log_Reporter->get_log_entries() #4 /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elemento in /home/customer/www/staging3.lucyb17.sg-host.com/public_html/wp-content/plugins/elementor/core/logger/items/base.php on line 138
There has been a critical error on this website. Please check your site admin email inbox for instructions

**Comment by rami-elementor** [comment]
Hi @lucyjaynemakeup ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
