### ISSUE TITLE
🐞 Bug report: Repeater in repeater

### ISSUE THREAD

**Issue by MrGrock** [elementor/elementor#18769]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I did, but there is a bug when creating an element of the second level (an element of both the first and second levels is created)

### Steps to reproduce

`

		/* Start repeater */

		$repeater = new \Elementor\Repeater();

		$repeater->add_control(
			'title',
			[
				'label' => esc_html__( 'Title', 'armed' ),
				'type' => \Elementor\Controls_Manager::TEXT,
				'dynamic' => [
					'active' => true,
				],
			]
		);

		$repeater->add_control(
			'links',
			[
				'label' => esc_html__( 'Links', 'armed' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => [
					[
						'name' => 'title',
						'label' => __( 'Title', 'armed' ),
						'type' => \Elementor\Controls_Manager::TEXT,
						'placeholder' => __( 'Title', 'armed' ),
						'label_block' => true,
					],
					[
						'name' => 'link',
						'label' => __( 'Link', 'armed' ),
						'placeholder' => __( 'https://site.com/', 'armed' ),
						'type' => \Elementor\Controls_Manager::URL,
						'label_block' => true,
						'show_label' => true,
					],
				],
			]
		);

		/* End repeater */

		$this->add_control(
			'tabs_items',
			[
				'label' => esc_html__( 'Banner Items', 'armed' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $repeater->get_controls(),
                'prevent_empty' => false,
			]
		);
`
https://user-images.githubusercontent.com/23105202/170739869-dff1eff3-efac-4a3b-94cb-e5166e6a57a7.mp4

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Unix)
	MySQL version: (LTD BeGet) v5.7.21-20
	PHP Version: 7.4.25
	PHP Memory Limit: 268435456
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1047527424
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

**Comment by rami-elementor** [comment]
Hi @MrGrock , Try changing the field names.

Your first control name is "title" and second control name is "links". Repeater fields use those names too - "title" and "links".

**Comment by MrGrock** [comment]
Hi @rami-elementor, don't help(

`

		/* Start repeater */

		$repeater = new \Elementor\Repeater();

		$repeater->add_control(
			'title_parent',
			[
				'label' => esc_html__( 'Title', 'armed' ),
				'type' => \Elementor\Controls_Manager::TEXT,
				'dynamic' => [
					'active' => true,
				],
			]
		);

		$repeater->add_control(
			'links_parent',
			[
				'label' => esc_html__( 'Links', 'armed' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => [
					[
						'name' => 'title_child',
						'label' => __( 'Title', 'armed' ),
						'type' => \Elementor\Controls_Manager::TEXT,
						'placeholder' => __( 'Title', 'armed' ),
						'label_block' => true,
					],
					[
						'name' => 'link_child',
						'label' => __( 'Link', 'armed' ),
						'placeholder' => __( 'https://site.com/', 'armed' ),
						'type' => \Elementor\Controls_Manager::URL,
						'label_block' => true,
						'show_label' => true,
					],
				],
			]
		);

		/* End repeater */

		$this->add_control(
			'tabs_items',
			[
				'label' => esc_html__( 'Banner Items', 'armed' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $repeater->get_controls(),
				'prevent_empty' => false,
			]
		);

`

**Comment by rami-elementor** [comment]
Ok, so I talked to a colleagues, you need to create another repeater() instance for the inner fields:

```php
/* Child repeater */

$child_repeater = new \Elementor\Repeater();

$child_repeater->add_control(
    'title_child',
    [
        'label' => __( 'Title', 'armed' ),
        'type' => \Elementor\Controls_Manager::TEXT,
        'placeholder' => __( 'Title', 'armed' ),
        'label_block' => true,
    ]
);

$child_repeater->add_control(
    'link_child',
    [
        'label' => __( 'Link', 'armed' ),
        'placeholder' => __( 'https://site.com/', 'armed' ),
        'type' => \Elementor\Controls_Manager::URL,
        'label_block' => true,
        'show_label' => true,
    ]
);



/* Parent repeater */

$parent_repeater = new \Elementor\Repeater();

$parent_repeater->add_control(
    'title_parent',
    [
        'label' => esc_html__( 'Title', 'armed' ),
        'type' => \Elementor\Controls_Manager::TEXT,
        'dynamic' => [
            'active' => true,
        ],
    ]
);

$parent_repeater->add_control(
    'links_parent',
    [
        'label' => esc_html__( 'Links', 'armed' ),
        'type' => \Elementor\Controls_Manager::REPEATER,
        'fields' => $child_repeater->get_controls(),
    ]
);



/* Repeater */

$this->add_control(
    'tabs_items',
    [
        'label' => esc_html__( 'Banner Items', 'armed' ),
        'type' => \Elementor\Controls_Manager::REPEATER,
        'fields' => $parent_repeater->get_controls(),
        'prevent_empty' => false,
    ]
);
```

**Comment by rami-elementor** [comment]
BUT... it look like it won't work! Elementor doesn't support repeater inside a repeater. I was told that it's a known issue, but we are not going to fix it any time soon.

Sorry I couldn't help you.

**Comment by MrGrock** [comment]
@rami-elementor
Checked, does not help, the same problem.
Very sad, it would be a very useful feature.
Thanks!

**Comment by sawwd** [comment]
Yes , it doesn't work. When a repeater contains another repeater the Add Item button adds a new item to the parent repeater. What I find strange is the docs have an example of nested repeater and this doesnt work as it should - https://developers.elementor.com/docs/editor-controls/control-repeater/

**Comment by CodeCurosity** [comment]
I am facing the same issue, if nested repeater is working, only issue is the bug you stated, when you add item in nested repeater it also adds to parent repeater, must be classes issue, anyone has any fix on this?

**Comment by LaiQuyetThang** [comment]
Have you solved the problem, can you give me your solution?

**Comment by toan10921** [comment]
still not work now
