### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by SWIMS1** [elementor/elementor#18763]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I see this error when site is published.  How do I fix it?  

Deprecated: Function Elementor\DB::is_built_with_elementor is deprecated since version 3.2.0! Use Plugin::$instance->documents->get( $post_id )->is_built_with_elementor() instead. in /var/www/vhosts/societywithms.org/public_html/wp-includes/functions.php on line 5379

### Steps to reproduce

.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 20.04 v10.3.34
	PHP Version: 8.0.19
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://societywithms.org
	Home URL: https://societywithms.org
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: hello@societywithms.org
	Debug Mode: Active

== Theme ==
	Name: Astra
	Version: 3.8.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.4
		Author: Automattic

	Astra Widgets
		Version: 1.2.11
		Author: Brainstorm Force

	Elementor
		Version: 3.7.0-dev8
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.4
		Author: WPDeveloper

	Gutenberg
		Version: 13.3.0
		Author: Gutenberg Team

	Gutenberg Blocks and Template Library by Otter
		Version: 2.0.4
		Author: ThemeIsle

	Premium Addons for Elementor
		Version: 4.9.15
		Author: Leap13

	Starter Templates
		Version: 3.1.10
		Author: Brainstorm Force

	Templates Patterns Collection
		Version: 1.1.21
		Author: ThemeIsle

	Ultimate Addons for Gutenberg
		Version: 1.25.4
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.22.12
		Author: UpdraftPlus.Com, DavidAnderson

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.3
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPForms Lite
		Version: 1.7.4.2
		Author: WPForms

	WP Mail SMTP
		Version: 3.4.0
		Author: WPForms

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 282022-04-09 20:33:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-09 20:33:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.2',
)]
2022-04-22 05:55:45 [info] elementor::elementor_updater Started 
2022-04-22 05:55:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-22 05:55:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-22 05:55:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-22 05:55:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-28 13:34:55 [info] elementor::elementor_updater Started 
2022-04-28 13:34:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-28 13:34:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-28 13:34:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-28 13:34:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-19 03:32:32 [info] elementor::elementor_updater Started 
2022-05-19 03:32:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-19 03:32:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-19 03:32:32 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-05-19 03:32:32 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-05-19 03:32:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev8',
)]
2022-05-19 03:32:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev8',
)]
2022-05-19 03:32:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev8',
)]

PHP: showing 4 of 4PHP: 2022-04-10 02:13:38 [warning X 4][/var/www/vhosts/societywithms.org/public_html/wordpress/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key &quot;title&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-22 06:33:16 [warning X 1][/var/www/vhosts/societywithms.org/staging.societywithms.org/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-15 20:46:29 [warning X 37][/var/www/vhosts/societywithms.org/staging.societywithms.org/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-16 05:43:57 [warning X 1][/var/www/vhosts/societywithms.org/staging.societywithms.org/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key &quot;url&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-05-12 04:20:25 [error X 4][https://staging.societywithms.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:515479] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-05-16 05:42:36 [error X 1960][https://staging.societywithms.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \&#039;clone\&#039;) 
JS: 2022-05-16 05:43:03 [error X 10][https://staging.societywithms.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \&#039;changestop\&#039;) 
JS: 2022-05-18 00:46:51 [error X 1][https://staging.societywithms.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view15144\&quot;) has already been destroyed and cannot be used. 
JS: 2022-05-25 22:22:12 [error X 3][https://staging.societywithms.org/wp-content/plugins/premium-addons-for-elementor/assets/editor/js/premium-cross-cp.js?ver=4.9.14:104:9] elementor is not defined 

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible
	Premium Addons for Elementor: Incompatible

**Comment by gensd** [comment]
I am having this same issue

**Comment by rami-elementor** [comment]
Hi @SWIMS1 @gensd ,

One of your Elementor addons is using deprecated code.

You need to disable your plugin one-by-one until you find the one that breaks your site.

When you find the plugin / Elementor addon, you need to contact the addon developers and ask them to read about the [Elementor deprecation process](https://developers.elementor.com/docs/deprecations/) and update the addon code.

**Comment by axmedov2001** [comment]
**THE SOLUTOIN :** From left menu go to **Elementor / Tools / Version Control** (Rollback Version) and **reinstall the previous** version. Then **disable auto update** for elementor.

This may be due to the late update of the Esstentials for Elementor plugin in particular. In this way, you can fix the problem by installing elementor to the previous version.
