### ISSUE TITLE
🔥 🚀 WooCommerce Invoice in elementor.

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18770]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Providing a purchase invoice to customers is very important in online stores. So it would be great if you could develop this feature 
There are many plugins like [this](in elementor. https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/) for this, but they have very poor customization. With many bugs.

### Describe the solution you'd like

A great way to implement this feature in elementor ...
In one part we can customize the invoice. The store logo is automatically inserted from the website (it is not bad to insert a custom logo).
The user must be able to download this purchase invoice. So, we need a new dynamic WooCommerce tag.
Just add the button widget, select the new dynamic tag (invoice). After that, if the user clicks on this button, the invoice will be downloaded. We will display this button on the thank you page. If desired, after the purchase, the user can download (pdf file) his purchase invoice. @avivu, Please check this feature. thanks

**Some other features required**

Send invoice to email (optional) - Ability to design invoice template as html - Possibility to customize the invoice using the elementor editor - Invoice can be downloaded from my account > Orders - Ability to print invoices directly

**Comment by 79ho3ein** [comment]
I do not think elementor would add such a feature. But if it adds this feature, it's really great. I'll be looking forward to it.

**Comment by rami-elementor** [comment]
Hi @Joliamendi ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being.  Elementor is a page builder, not an e-commerce plugin. We are not going to extend WooCommerce functionality.

Regards,
