### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by purifytones** [elementor/elementor#18777]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My website "[www.purifytones.info](url)" using Elementor when I access it gives a message titled:"There has been a critical error on this website." I upgraded to the developer version but still the same message coming.
I tried many more things like regenerating files and data or syncing the library, but nothing happen.
-

### Steps to reproduce

I think the problem with Elementor, is cause I deactivated it then the website worked well
when I activate it the website does not work.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - (GPL) v5.7.37
	PHP Version: 7.4.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://www.purifytones.info
	Home URL: https://www.purifytones.info
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: purifytones@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: ryancv
	Version: 2.0.4
	Author: beshleyua
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

== Active Plugins ==
	Advanced Custom Fields: Font Awesome
		Version: 4.0.3
		Author: Matt Keys

	Advanced Custom Fields PRO
		Version: 5.9.3
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 7.61
		Author: ServMask

	CMP - Coming Soon & Maintenance Plugin
		Version: 4.1.2
		Author: NiteoThemes

	Contact Form 7
		Version: 5.5.6.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.6.1
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.1.4
		Author: WPDeveloper

	Formidable Forms
		Version: 5.3
		Author: Strategy11

	LiteSpeed Cache
		Version: 4.6
		Author: LiteSpeed Technologies

	Master Addons for Elementor
		Version: 1.9.1
		Author: Jewel Theme

	Max Mega Menu
		Version: 2.9.6
		Author: megamenu.com

	One Click Demo Import
		Version: 3.1.1
		Author: OCDI

	RyanCV Plugin
		Version: 1.0.6
		Author: beshleyua

	WP Encryption - One Click SSL & Force HTTPS
		Version: 5.7.16
		Author: Go Web Smarty

	WP Force SSL
		Version: 1.65
		Author: WebFactory Ltd

	WPML Media
		Version: 2.6.2
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.4.8
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.6
		Author: OnTheGoSystems

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 18.9
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	installatron_hide_status_test.php
		Version: 
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
Log: showing 20 of 372022-05-26 12:15:15 [info] elementor::elementor_updater Started 
2022-05-26 12:15:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-26 12:15:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-26 12:15:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.5',
)]
2022-05-26 12:15:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.5',
)]
2022-05-29 09:21:29 [notice] Re-migrate 3.0.0 globals: Start 
2022-05-29 09:21:29 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2022-05-29 09:21:29 [notice] System typography is disabled. nothing to do. 
2022-05-29 09:21:29 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2022-05-29 09:21:29 [notice] System colors are disabled. nothing to do. 
2022-05-29 09:21:29 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2022-05-29 09:21:29 [notice] Custom colors already exist. nothing to do. 
2022-05-29 09:21:29 [notice] Re-migrate 3.0.0 globals: End 
2022-05-29 09:55:02 [info] elementor::elementor_updater Started 
2022-05-29 09:55:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-29 09:55:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-29 09:55:02 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-05-29 09:55:02 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-05-29 09:55:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev9',
)]
2022-05-29 09:55:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.0-dev9',
)]

JS: showing 3 of 3JS: 2022-02-22 16:58:34 [error X 410][https://www.purifytones.info/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.5:2:21754] r[a] is undefined 
JS: 2022-02-22 17:24:31 [error X 1][https://www.purifytones.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453830] T is null 
JS: 2022-02-23 06:32:49 [error X 7][https://www.purifytones.info/wp-content/plugins/unlimited-elements-for-elementor/provider/core/plugins/unlimited_elements/elementor/assets/uc_front_admin.js?ver=1.5.1:107:2] elementorFrontend is not defined 

PHP: showing 2 of 2PHP: 2022-05-26 12:30:02 [notice X 164][/home/purifytones/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-29 09:21:29 [notice X 2][/home/purifytones/public_html/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified
	Master Addons for Elementor: Compatibility not specified

**Comment by rami-elementor** [comment]
Hi @purifytones ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
