### ISSUE TITLE
⛔ 🐞 Bug report: Can't find the Notes Feature 

### ISSUE THREAD

**Issue by zvaranka** [elementor/elementor#18773]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Greeting!

There is a problem with the Elementor Version 3.7.1 Note function. I turned on the Elementor> Settings> Experimental page in the Stable section. But it doesn’t show up anywhere, neither when editing the page nor in the top left hamburger menu 'Navigate from page' section. What could be the problem?

I am using WordPress 6.0, Elementor 3.6.5 and Elementor Pro 3.7.1

Thank you in advance.

Zoltán

### Steps to reproduce

Elementor> Settings> Experimental page > Notes > Enabled 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.18
	PHP Version: 7.4.29
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://novolibro.eu
	Home URL: https://novolibro.eu
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: hu-HU
	Timezone: Europe/Budapest
	Admin Email: info@novolibro.eu
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: hu_HU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.162 Safari/537.36

== Active Plugins ==
	Calculated Fields Form
		Version: 10.1.107
		Author: CodePeople

	CFF Progress Bar
		Version: 1.0.3
		Author: CodePeople.net

	Easy Updates Manager
		Version: 9.0.12
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.6.1
		Author: Wpmet

	Envato Elements
		Version: 2.0.11
		Author: Envato

	HelloPack
		Version: 1.1.9
		Author: HelloWP Ltd

	MailPoet 3 (New)
		Version: 3.89.3
		Author: MailPoet

	MailPoet 3 Premium (New)
		Version: 3.89.0
		Author: MailPoet

	Pages with category and tag
		Version: 0.9.0
		Author: YAHMAN

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.3
		Author: David Anderson, Ruhani Rabin, Team Updraft

== Elemek használata ==
	
	archive : 1
		posts : 1
		theme-archive-title : 1
	footer : 1
		ekit-nav-menu : 1
		elementskit-social-media : 1
		form : 1
		heading : 3
		icon-list : 2
		image : 1
		text-editor : 3
	header : 1
		call-to-action : 1
		ekit-nav-menu : 1
		elementskit-header-search : 1
		image : 1
	page : 1
		countdown : 1
		form : 1
		heading : 3
		image : 1
	wp-post : 0
		share-buttons : 2
		text-editor : 1
	wp-page : 3
		author-box : 1
		divider : 1
		heading : 1
		posts : 2
		text-editor : 3
		theme-post-excerpt : 1
	single-page : 2
		divider : 5
		heading : 1
		post-info : 2
		posts : 1
		share-buttons : 2
		social-icons : 2
		theme-page-title : 1
		theme-post-content : 2
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 1

== Elementor kísérletek ==
	Optimalizált DOM kimenet: Alapértelmezetten bekapcsolt
	Továbbfejlesztett eszközbetöltés: Kikapcsolva
	Továbbfejlesztett CSS betöltés: Kikapcsolva
	Beágyazott betűikonok: Kikapcsolva
	Akadálymentesítési továbbfejlesztések: Alapértelmezetten bekapcsolt
	Sablonkészlet importálása és exportálása: Bekapcsolva
	További egyéni töréspontok: Kikapcsolva
	A natív WordPress kisalkalmazások elrejtése a keresési eredményekből: Alapértelmezetten bekapcsolt
	: Alapértelmezetten kikapcsolt
	Rugalmas tároló: Kikapcsolva
	Alapértelmezett az új témaépítő: Bekapcsolva
	Hello téma fejléc és lábléc: Bekapcsolva
	Fogadóoldalak: Bekapcsolva
	Színmintavevő: Bekapcsolva
	Kedvenc kisalkalmazások: Bekapcsolva
	Felső adminisztrációs sáv: Bekapcsolva
	Oldalátmenetek: Kikapcsolva
	Jegyzetek: Bekapcsolva
	Űrlapbeküldések: Bekapcsolva
	Görgetési illesztés: Bekapcsolva

== Napló ==
	
PHP: showing 8 of 8PHP: 2022-05-20 16:19:49 [notice X 110][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-20 17:59:58 [error X 3][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/connect/kit-library.php::19] Uncaught Error: Call to undefined method Elementor\Core\App\Modules\KitLibrary\Connect\Kit_Library::http_request() in /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/connect/kit-library.php:19
Stack trace:
#0 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/data/repository.php(184): Elementor\Core\App\Modules\KitLibrary\Connect\Kit_Library->get_all()
#1 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/data/repository.php(52): Elementor\Core\App\Modules\KitLibrary\Data\Repository->get_kits_data(false)
#2 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/data/kits/controller.php(18): Elementor\Core\App\Modules\KitLibrary\Data\Repository->get_all(false)
#3 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/data/v2/base/endpoint/index.php(25): Elementor\Core\App\Modules\KitLibrary\Data\Kits\Control [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-20 17:59:59 [error X 3][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/connect/kit-library.php::23] Uncaught Error: Call to undefined method Elementor\Core\App\Modules\KitLibrary\Connect\Kit_Library::http_request() in /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/connect/kit-library.php:23
Stack trace:
#0 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/data/repository.php(205): Elementor\Core\App\Modules\KitLibrary\Connect\Kit_Library->get_taxonomies()
#1 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/data/repository.php(99): Elementor\Core\App\Modules\KitLibrary\Data\Repository->get_taxonomies_data(false)
#2 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/kit-library/data/taxonomies/controller.php(28): Elementor\Core\App\Modules\KitLibrary\Data\Repository->get_taxonomies(false)
#3 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/data/v2/base/endpoint/index.php(25): Elementor\Core\App\Modules\Ki [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-21 18:29:00 [notice X 2][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::260] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-22 15:58:27 [error X 2][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/www/clients/client3832/web8310/web/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/www/clients/client3832/web8310/web/wp-includes/class-wp-ho [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-22 16:39:12 [notice X 3][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/app/modules/import-export/module.php::90] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-23 15:10:17 [notice X 1][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/includes/template-library/sources/local.php::720] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-28 07:32:58 [notice X 1][/home/www/clients/client3832/web8310/web/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 18 of 18JS: 2022-05-21 04:53:27 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.6.5:2:71271] Data commands: `` not found. 
JS: 2022-05-22 07:08:30 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:406153] Cannot read properties of null (reading \'id\') 
JS: 2022-05-22 11:22:36 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view35359\") has already been destroyed and cannot be used. 
JS: 2022-05-22 11:23:43 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view38456\") has already been destroyed and cannot be used. 
JS: 2022-05-22 11:28:03 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view95\") has already been destroyed and cannot be used. 
JS: 2022-05-22 11:40:36 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view96\") has already been destroyed and cannot be used. 
JS: 2022-05-22 13:48:02 [error X 5][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view101\") has already been destroyed and cannot be used. 
JS: 2022-05-22 14:38:09 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view99\") has already been destroyed and cannot be used. 
JS: 2022-05-22 14:39:26 [error X 3][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view94\") has already been destroyed and cannot be used. 
JS: 2022-05-22 15:23:20 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view8751\") has already been destroyed and cannot be used. 
JS: 2022-05-22 15:58:25 [error X 3][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view100\") has already been destroyed and cannot be used. 
JS: 2022-05-23 04:51:37 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view104\") has already been destroyed and cannot be used. 
JS: 2022-05-23 06:56:04 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view106\") has already been destroyed and cannot be used. 
JS: 2022-05-23 07:32:31 [error X 3][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view112\") has already been destroyed and cannot be used. 
JS: 2022-05-23 13:11:16 [error X 2][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view110\") has already been destroyed and cannot be used. 
JS: 2022-05-23 13:13:40 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2245\") has already been destroyed and cannot be used. 
JS: 2022-05-23 13:34:25 [error X 1][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view27684\") has already been destroyed and cannot be used. 
JS: 2022-05-23 13:45:24 [error X 2][https://novolibro.eu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view126\") has already been destroyed and cannot be used. 

Log: showing 6 of 62022-05-22 18:00:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-05-22 18:00:33 [info] elementor-pro::elementor_pro_updater Started 
2022-05-22 18:00:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-22 18:00:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-22 18:00:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-05-22 18:00:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: A kompatibilitás nincs megadva.

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @zvaranka,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The Notes Feature can be found in various places:
   1. In the Elementor Widget Panel, go to the Menu at the top left corner and click on the Notes option.
   2. In your WordPress Dashboard, go to the Menu on the left, then Elementor > Notes.
   3. In your website's front end, you can find the Notes menu in the Admin Bar at the top.

For more information on how to use Elementor, please **always refer to the Help Center first**. Here's the article that covers the Notes feature:
https://elementor.com/help/notes-feature/

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
