### ISSUE TITLE
✅ 🐞 Bug report: editor.min.css?ver=3.6.2 net::ERR_ABORTED 404 (Not Found) - [ED-7826]

### ISSUE THREAD

**Issue by aylitat** [elementor/elementor#18818]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

elementor/assets/css/modules/container-converter/editor.min.css?ver=3.6.2 
net::ERR_ABORTED 404 (Not Found)
website location：China

### Steps to reproduce

open a post with elementor...and then... failed

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

website location：China

**Comment by rami-elementor** [comment]
Hi @aylitat ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by sgripen** [comment]
This bug was also observed by me in versions 3.6.6 and 3.6.7

**Comment by wes-davis** [comment]
This bug still persists. Github description specifically says this is for bug reports — this should not have been marked closed.

**Comment by sgripen** [comment]
This bug #18818 doesn't seem like a priority for the team, nothing I found the fix preview in Beta Release Elementor v3.7. This bug and other JS errors can also be viewed here https://playground.elementor.com/demo/flexbox/

**Comment by rami-elementor** [comment]
@aylitat @sgripen @wes-davis Our QA team asked to update the ticket to add "Steps to reproduce".

**Comment by marcofrasson** [comment]
any update?

**Comment by histevenlee** [comment]
this also happens in elementor fee 3.7.2,  3.7.0, which in my case, I have flexbox enabled.

**Comment by Adkowski** [comment]
It happens after adding Image Slider, I ran into this problem today, made a new page and started to copy every element and updating with success. When I copied Image Slider widget it suddenly refused to save page (Error 500) and thread error appeard. Deleting image slider did no change. (Plugins: only Elementor and Elementor Pro active with Hello Theme)

**Comment by nicholaszein** [comment]
This issue was solved with the release of Elementor 3.19.
