### ISSUE TITLE
🚀 separator for title widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18823]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

This is a great idea for a title widget. This feature is available in the bricks page builder. Watch the video below.

https://user-images.githubusercontent.com/88034902/171504866-682c1280-ebad-4c0a-9bbe-c1f626623926.mp4

Please add this feature to elementor

### Describe the solution you'd like

separator for title widget

**Comment by 79ho3ein** [comment]
+1

**Comment by choijun** [comment]
Hi @Michaelgimii 
Why you don't use Divider widget for this ?

**Comment by rami-elementor** [comment]
Closing this issue.

As @choijun mentioned, you can use the divider widget to do that.
