### ISSUE TITLE
🚀 better ux for pinning widgets

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18826]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team!

In elementor it is possible to pin widgets and it works very well. But i think this feature does not have a good ux. (Personal opinion) and can be much better. So, I had a suggestion to improve ui, ux that feature, I hope it is useful. If you do not agree to change ui, ux in this feature, simply close this request.

### Describe the solution you'd like

Button add  to Favorites (pin), from [this ui](https://prnt.sc/aoqk68BKjMBK) to, [this ui](https://prnt.sc/qo-gwlTnGucD).
When hovering on each widget, pin button appears. Clicking on the desired icon will be added to the pinned widgets section. To remove the pinned widgets, we do exactly the same as before. With a slight change in the pin icon : https://prnt.sc/SB_sz7mqrC3b

The only thing is that when hovering, the pin and unpin text is displayed. This design of the pin & unpin icon was just a concept design of this feature that I designed in just 10 minutes in Photoshop. It could definitely be better. So this could be much better than the current situation.

Anyway, thank you!

**Comment by 79ho3ein** [comment]
Another case ...

[This option](https://prnt.sc/NiNHSUAgQKMU) is still displayed even if no widget is added to the favorites list. So, isn't it better to hide this section if no widget has been added to the favorites?
When the first widget is added to the favorites list, the favorites section will appear immediately. (For suggestion only)

**Comment by arielk** [comment]
Hi @79ho3ein, I'm not sure why this behavior is better than the current one, so for now I'm closing this issue, but thanks for your feedback!!
