### ISSUE TITLE
 🐞 Bug in gradient background (section & container)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18827]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If we use universal colors in the background gradient colors, the default gradient color will be displayed after reloading the editor. This problem arises for a color that uses a universal color. Please watch the video below @shilo-ey 

https://user-images.githubusercontent.com/77163248/171580594-484f1d0b-78a9-457c-bc6f-f88a90ef5a00.mp4

If we use both colors as a universal color, something else will happen, which can be seen in the video below.

https://user-images.githubusercontent.com/77163248/171579627-53ba4eca-516e-4d68-89d2-7c6fbfd43b34.mp4

📢📢Please note that this bug is only present in the gradient background color of the container and section. For example, if you use the gradient background color of universal colors in the button widget, there will be no problem.

### Steps to reproduce

The above videos are enough. If you were successful in reproducing, please let me know, thank you!

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by MichaelDarko** [comment]
This problem has been there for ages. It has been reported many times. They don't care.

#16793
#16831
#17616
