### ISSUE TITLE
🚀 prevent input zoom on iphone

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18822]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

If you are careful, in Safari browser, the page automatically zooms when we click on inputs such as search box or form field. This zoom creates a very bad experience for users.
So, please add an option to elementor, so that we can prevent this zoom in Safari browser. 

### Describe the solution you'd like

prevent input zoom on iphone in elementor

**Comment by rami-elementor** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request, but we have decided not to add this to our roadmap. 

Restricting the zoom will severely impact the accessibility of your site. Visually impaired people often use this option.
Regards,
