### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by BCNoticias** [elementor/elementor#18833]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hola, compré un tema que solo es compatible con elementor, pero me marca errores constantes, si lo desactivo no me funciona. El problema es que no me deja publicar entradas y dificulta mi sitio web. 

### Steps to reproduce

Error 524 Ray ID: 7154b209ecb66db9 • 2022-06-03 01:37:40 UTC
A timeout occurred
You
Browser
Working
Miami
Cloudflare
Working
www.bcnoticias.com.co
Host
Error

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Error 524 Ray ID: 7154b209ecb66db9 • 2022-06-03 01:37:40 UTC
A timeout occurred
You
Browser
Working
Miami
Cloudflare
Working
www.bcnoticias.com.co
Host
Error

**Comment by rami-elementor** [comment]
@BCNoticias Please re-open the issue in English.
