### ISSUE TITLE
Render Section Widget Custom controls

### ISSUE THREAD

**Issue by enovathemes** [elementor/elementor#18836]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I added custom controls to the Section widget with `add_action( 'elementor/element/section/section_advanced/before_section_start'` and `$element->start_injection`

But can't get them rendered with 

`add_action( 'elementor/widget/before_render_content'`

Please guide me on how i should extend the Section widget to have new controls for the render

### Steps to reproduce

Extend section with given hooks

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.46 (Win64) PHP/7.4.9 mod_fcgid/2.3.10-dev
	MySQL version: MySQL Community Server (GPL) v5.7.31
	PHP Version: 7.4.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://localhost/meow
	Home URL: http://localhost/meow
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: enovathemes@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Meow!
	Version: 1.0
	Author: Enovathemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Currency Switcher for WooCommerce
		Version: 2.15.0
		Author: WP Wham

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Enovathemes add-ons
		Version: 1.0
		Author: Enovathemes

	Envato Market
		Version: 2.0.7
		Author: Envato

	One Click Demo Import
		Version: 3.1.1
		Author: OCDI

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Safe SVG
		Version: 2.0.1
		Author: 10up

	Slider Revolution
		Version: 6.5.19
		Author: ThemePunch

	Transients Manager
		Version: 2.0.2
		Author: WPBeginner

	Variation Swatches for WooCommerce
		Version: 2.1.5
		Author: Woosuite

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WP Reset
		Version: 1.95
		Author: WebFactory Ltd

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

**Comment by rami-elementor** [comment]
Hi @enovathemes ,

See the following dev doc: https://developers.elementor.com/docs/hooks/injecting-controls/
