### ISSUE TITLE
🚀 Feature Request: Allow options to customise Elementor Overview pane

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#18848]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The Elementor Overview pane on the WP Dashboard is quite large, and it pushes down a lot of the the other panes on screen. When you compare it to the WordPress News & Events panel for instance, it's twice the length. 

### Describe the solution you'd like

It would be nice to perhaps reduce the size a little - maybe we just have newsfeed headlines instead of the snippets of content. Or maybe there's a preference to hide the news feed altogether, if we just want the functionality.

### Describe alternatives you've considered

- 

### Additional context

Here's a screenshot:

![download](https://user-images.githubusercontent.com/1435638/172094752-d595c47f-2bdf-4183-91cd-0a1d72a1e4ef.png)

**Comment by rami-elementor** [comment]
Hi @drawcard ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being. 

We don't want to allow access to this area. But we also understand that plugins add many dashboard widgets, WordPress allows you to re-arrange those widgets or hide entirely. 

Regards,
