### ISSUE TITLE
🚀 Button for icon box and image box widget.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18844]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add a button to these two widgets. Buttons seem to be necessary for these two widgets. 

### Describe the solution you'd like

Add a button feature to this widget so we can use it if needed. (If no text is written for the button, the button will not be displayed). Just like the slide widget

**Comment by rami-elementor** [comment]
Hi @Michaelgimii,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being. You can do that with two separate widgets. Our long-term roadmap has the opposite direction, to break complex widgets to smaller parts.

Regards,

**Comment by 79ho3ein** [comment]
hi @rami-elementor , Is your goal actually to convert large widgets into smaller ones? For example cart, checkout and my account widgets?

**Comment by rami-elementor** [comment]
> hi @rami-elementor , Is your goal actually to convert large widgets into smaller ones? For example cart, checkout and my account widgets?

@79ho3ein, In the long run, yes. It will increase page performance. Each widget will have smaller CSS footprint and will reduce the unused CSS.

**Comment by 79ho3ein** [comment]
thank you @rami-elementor , This is really great. The fact that the cart, checkout and my account pages only have one widget is very limiting. But it is strange why it was not added in the form of smaller widgets from the beginning. Anyway, I wish you the best of luck.
