### ISSUE TITLE
🐞 Bug report: Elementor newsletter form not working

### ISSUE THREAD

**Issue by githailey** [elementor/elementor#18853]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have added the premade newsletter form and have connected Elementor to my mailchimp via API. I am not sure if I am doing something wrong, but when I go to submit an email in the form it opens up a new tab and reloads the page. When I check my audience on mailchimp it has not added the new email. There is a section when editing the form that I haven't filled out which states "MailChimp Submit URL". I am not sure what this is or if filling it out will fix my issue. I assumed that including the API key would be enough. Please advise. 

### Steps to reproduce

Insert the premade newsletter form. Save progress. Open page to test newsletter sign up form. Insert an email and submit it. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel5.7, Revision 26 v5.7.26-29
	PHP Version: 7.4.29
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://techneo.io
	Home URL: https://techneo.io
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hecutshall@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: SmartMag
	Version: 8.0.6
	Author: ThemeSphere
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	a3 Lazy Load
		Version: 2.5.0
		Author: a3rev Software

	Akismet Anti-Spam
		Version: 4.2.4
		Author: Automattic

	All in One SEO
		Version: 4.2.1.1
		Author: All in One SEO Team

	Bunyad AMP
		Version: 2.1.3
		Author: ThemeSphere, AMP Project Contributors

	Bunyad Demo Import
		Version: 2.6.2
		Author: ThemeSphere & ProteusThemes

	Bunyad Widget for Instagram
		Version: 1.2.4
		Author: ThemeSphere

	CoBlocks
		Version: 2.24.0
		Author: GoDaddy

	Complianz Privacy Suite (GDPR/CCPA) premium
		Version: 6.2.0.1
		Author: Really Simple Plugins

	Contact Form 7
		Version: 5.5.6.1
		Author: Takayuki Miyoshi

	Custom Sidebars
		Version: 3.35
		Author: WebFactory Ltd

	Debloat
		Version: 1.2.1
		Author: asadkn

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	Gravity Forms
		Version: 2.5.15
		Author: Gravity Forms

	Limit Login Attempts Reloaded
		Version: 2.25.3
		Author: Limit Login Attempts Reloaded

	MonsterInsights - EU Compliance
		Version: 2.2.2
		Author: MonsterInsights Team

	MonsterInsights - Media Addon
		Version: 1.0.1
		Author: MonsterInsights Team

	MonsterInsights - Page Insights Addon
		Version: 1.5.0
		Author: MonsterInsights Team

	MonsterInsights Pro
		Version: 8.5.4
		Author: MonsterInsights

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Self-Hosted Google Fonts
		Version: 1.0.1
		Author: asadkn

	SmartMag Core
		Version: 1.3.4
		Author: ThemeSphere

	Sphere Core
		Version: 1.5.2
		Author: ThemeSphere

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.30
		Author: Sucuri Inc.

	Under Construction
		Version: 3.93
		Author: WebFactory Ltd

	Wordfence Security
		Version: 7.5.10
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.7.4.2
		Author: WPForms

	Yoast SEO
		Version: 19.0
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.6
		Author: Team Yoast

== Must-Use Plugins ==
	System Plugin
		Version: 4.25.1
		Author: 

== Elements Usage ==
	
	wp-page : 3
		call-to-action : 2
		heading : 3
		media-carousel : 3
		smartmag-grid : 4
		smartmag-newsletter : 4
		smartmag-overlay : 1
		smartmag-postslist : 4
		social-icons : 2
		spacer : 3
		text-editor : 2
	single-page : 1
		smartmag-grid : 2
		smartmag-heading : 2
		smartmag-newsletter : 1
		smartmag-overlay : 1
		wp-widget-bunyad-social : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 292022-04-23 23:14:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.4',
)]
2022-04-23 23:14:33 [info] elementor::elementor_updater Started 
2022-04-23 23:14:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-23 23:14:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-23 23:14:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.4',
)]
2022-04-23 23:25:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-04-23 23:25:21 [info] elementor-pro::elementor_pro_updater Started 
2022-04-23 23:25:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-23 23:25:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-23 23:25:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-06-05 02:53:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-05 02:53:59 [info] elementor::elementor_updater Started 
2022-06-05 02:53:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-05 02:53:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-05 02:53:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-05 04:07:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-06-05 04:07:04 [info] elementor-pro::elementor_pro_updater Started 
2022-06-05 04:07:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-05 04:07:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-05 04:07:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]

PHP: showing 10 of 10PHP: 2022-04-23 23:13:37 [notice X 4235][/var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-23 23:17:47 [notice X 82][/var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/wp-content/plugins/smartmag-core/inc/elementor/elementor.php(455): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-23 23:17:47 [notice X 2][/var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-23 23:17:47 [notice X 2][/var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-23 23:17:47 [notice X 2][/var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-23 23:17:47 [notice X 2][/var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-05 06:20:19 [error X 3][/var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /var/www/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /var/www/wp-includes/plugin.php(474): WP_Hook-&gt;do_action(Array)
#6 /var/www/wp-admin/admin-ajax.php(187): d [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-05 07:45:21 [notice X 4][/var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-05 08:04:48 [warning X 1][/var/www/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::195] unlink(2048px-Instagram_icon.png): Read-only file system [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-06 12:31:27 [notice X 1][/var/www/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2022-06-05 06:12:44 [error X 1][https://techneo.io/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.5:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `column` got as `column_order` value. Expected array or object.',
)]
JS: 2022-06-05 06:31:54 [error X 2][https://techneo.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:242684] Cannot read properties of undefined (reading \&#039;html\&#039;) 
JS: 2022-06-05 06:32:50 [error X 1][https://techneo.io/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.5:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `smartmag-heading` got as `css_bhead_inner_pad` value. Expected array or object.',
)]
JS: 2022-06-05 06:32:50 [error X 1][https://techneo.io/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.5:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `smartmag-overlay` got as `css_format_icon_size` value. Expected array or object.',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @githailey ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
