### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Aje-dotcom** [elementor/elementor#18865]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

I keep getting a deprecated error notice on a contact page that I publish a few months ago

the message reads:
![2022-06-07 08_05_12-Contact – Pastor Ministers Prayer Network](https://user-images.githubusercontent.com/74695986/172317911-97943bd5-e367-404e-8b4f-abeaa4c2869b.png)
 
Deprecated: Function Elementor\DB::is_built_with_elementor is deprecated since version 3.2.0! Use Plugin::$instance->documents->get( $post_id )->is_built_with_elementor() instead. in /home2/apmpnetw/public_html/wp-includes/functions.php on line 5379

How may I go about it after I updated a version of Elementor 3.7.0-dev9, and Elementor Pro 3.6.5

### Steps to reproduce

![2022-06-07 08_05_12-Contact – Pastor Ministers Prayer Network](https://user-images.githubusercontent.com/74695986/172319169-cd698445-7e6d-42cc-afa1-49ac84aef204.png)
check apmpnetwork.com to find the link to the bug on top of the page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1 |  
PHP Version: | 7.4.29 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 516M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div><div class="elementor-system-info-section elementor-system-info-experiments" style="outline: 0px; margin-bottom: 10px;"><table class="widefat" style="border-spacing: 0px; width: 1405.22px; clear: both; margin: 0px; border: 1px solid rgb(195, 196, 199); box-shadow: rgba(0, 0, 0, 0.04) 0px 1px 1px; background: rgb(255, 255, 255); white-space: pre;"><thead style="overflow-wrap: break-word;"><tr style="overflow-wrap: break-word;"><th style="overflow-wrap: break-word; padding: 8px 10px; text-align: left; line-height: 1.4em; font-size: 14px; color: rgb(44, 51, 56); font-weight: 400; border-bottom: 1px solid rgb(195, 196, 199);">Elementor Experiments</th><th style="overflow-wrap: break-word; padding: 8px 10px; text-align: left; line-height: 1.4em; font-size: 14px; color: rgb(44, 51, 56); font-weight: 400; border-bottom: 1px solid rgb(195, 196, 199);"></th><th style="overflow-wrap: break-word; padding: 8px 10px; text-align: left; line-height: 1.4em; font-size: 14px; color: rgb(44, 51, 56); font-weight: 400; border-bottom: 1px solid rgb(195, 196, 199);"></th></tr></thead><tbody style="overflow-wrap: break-word;"><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;"></td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);"></td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Optimized DOM Output: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Improved Asset Loading: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Improved CSS Loading: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Inline Font Icons: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Accessibility Improvements: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Import Export Template Kit: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Additional Custom Breakpoints: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Hide native WordPress widgets from search results: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">admin_menu_rearrangement: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Inactive by default</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Flexbox Container: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Default to New Theme Builder: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active by default</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Landing Pages: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Color Sampler: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Favorite Widgets: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Admin Top Bar: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Page Transitions: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active by default</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Form Submissions: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94); width: 300px;">Scroll Snap: </td><td style="font-family: inherit; font-size: 13px; font-weight: inherit; line-height: 1.5em; overflow-wrap: break-word; padding: 8px 10px; vertical-align: top; color: rgb(80, 87, 94);">Active by default</td></tr><tr style="overflow-wrap: break-word; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
</body>
</html>Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1	
PHP Version:	7.4.29	
PHP Memory Limit:	512M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	516M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.0	
Site URL:	https://www.apmpnetwork.com	
Home URL:	https://www.apmpnetwork.com/home	
WP Multisite:	No	
Max Upload Size:	512 MB	
Memory limit:	40M	
Max Memory limit:	512M	
Permalink Structure:	/%postname%/	
Language:	en-US	
Timezone:	1	
Admin Email:	admin@apmpnetwork.com	
Debug Mode:	Active	
Theme		
Name:	Astra	
Version:	3.8.2	
Author:	Brainstorm Force	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36	
Active Plugins		
3D FlipBook : Dflip Lite - 1.7.31	By [DearHive](https://dearflip.com/go/wp-lite-author)	
[Astra Widgets](https://wpastra.com/) - 1.2.11	By [Brainstorm Force](https://www.brainstormforce.com/)	
[Classic Editor](https://wordpress.org/plugins/classic-editor/) - 1.6.2	By [WordPress Contributors](https://github.com/WordPress/classic-editor/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.7.0-dev9	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.6.5	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[FluentSMTP](https://fluentsmtp.com/) - 2.1.1	By [FluentSMTP & WPManageNinja Team](https://fluentsmtp.com/)	
[Import / Export Customizer Settings](https://wpastra.com/) - 1.0.6	By [Brainstorm Force](http://www.brainstormforce.com/)	
[Site Kit by Google](https://sitekit.withgoogle.com/) - 1.75.0	By [Google](https://opensource.google.com/)	
[Starter Templates](https://wpastra.com/) - 3.1.11	By [Brainstorm Force](https://www.brainstormforce.com/)	
[WPForms](https://wpforms.com/) - 1.7.3	By [WPForms](https://wpforms.com/)	
[WP Mail SMTP](https://wpmailsmtp.com/) - 3.4.0	By [WPForms](https://wpforms.com/)	
Must-Use Plugins		
Endurance Page Cache - 2.2	By [Mike Hansen](https://www.mikehansen.me/)	
Elements Usage[Recalculate](https://www.apmpnetwork.com/wp-admin/admin.php?page=elementor-system-info&elementor_usage_recalc=1&_wpnonce=0f571eba42#elementor-usage-recalc)		
Page ( 12 )	Animated Headline: 3
Basic Gallery: 2
Button: 7
Counter: 1
Divider: 7
Facebook Embed: 2
Form: 1
Google Maps: 1
Heading: 10
Icon Box: 6
Image: 14
Image Box: 4
Image Carousel: 1
Media Carousel: 1
Progress Bar: 1
Slides: 3
Spacer: 2
Testimonial: 2
Text Editor: 14
Video: 4
container: 35
Post ( 1 )	Divider: 10
Flip Box: 1
Google Maps: 1
Heading: 12
Icon Box: 3
Icon List: 3
Image: 7
Image Box: 7
Image Carousel: 3
Portfolio: 1
Post Info: 1
Read More: 1
Shortcode: 1
Social Icons: 1
Spacer: 2
Star Rating: 1
Text Editor: 10
Video: 2
container: 11
Library - Page ( 1 )	Heading: 4
Icon Box: 3
Shortcode: 1
Social Icons: 1
Library - Section ( 2 )	Button: 1
Divider: 1
Heading: 5
Image: 3
Text Editor: 3
Library - Global Widget ( 0 )	Slides: 1
Elementor Experiments		
Optimized DOM Output: 	Active
Improved Asset Loading: 	Active
Improved CSS Loading: 	Active
Inline Font Icons: 	Active
Accessibility Improvements: 	Active
Import Export Template Kit: 	Active
Additional Custom Breakpoints: 	Active
Hide native WordPress widgets from search results: 	Active
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Active
Default to New Theme Builder: 	Active by default
Landing Pages: 	Active
Color Sampler: 	Active
Favorite Widgets: 	Active
Admin Top Bar: 	Active
Page Transitions: 	Active by default
Form Submissions: 	Active
Scroll Snap: 	Active by default

**Comment by rami-elementor** [comment]
Hi @Aje-dotcom ,

One of your Elementor addons is using deprecated code.

You need to disable your plugin one-by-one until you find the one that breaks your site.

When you find the plugin / Elementor addon, you need to contact the addon developers and ask them to read about the [Elementor deprecation process](https://developers.elementor.com/docs/deprecations/) and update the addon code.
