### ISSUE TITLE
🚀 Ability to change the color of the elementor editor theme.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18861]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It's great if you give your users this option so they can change their editor theme color to their liking. Of course, this change only applies to the dark mode of the editor.
[Editor theme color](https://prnt.sc/Pvg9Lrl2RZ-I) in dark mode does not look interesting now. Therefore, it will be great for users to change it to the [desired color](https://prnt.sc/WLwLBVUpnYMk).
Even when hovering over widgets : https://prnt.sc/jcKbKonlnLHh

### Describe the solution you'd like

Only one new option to change the color of the elementor editor theme (this color only applies in "dark mode")

Preview of this feature : https://prnt.sc/tOWx6dU2eqc3

Also as a bug, if you look at the switcher buttons in the dark mode, there is a white border at the beginning and end, which destroys the ui of these buttons : https://prnt.sc/if2ADBjewNc_

**Comment by rami-elementor** [comment]
Hi @79ho3ein,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being. 

We can offer many controls to style the Elementor Editor, but at this point we prefer to work on site editing, not editor theming. Although our roadmap include a facelift for the Editor.

Regards,

**Comment by 79ho3ein** [comment]
Yes, that makes perfect sense. thanks for your response
