### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Sistema1A1** [elementor/elementor#18860]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Por favor, tenho urgência em solucionar o erro do plugin!

### Steps to reproduce

Ao tentar carregar a página do site aparece a mensagem: **Há um erro crítico no seu site. Verifique seu e-mail para instruções.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<img width="798" alt="Captura de Tela 2022-06-06 às 16 58 40" src="https://user-images.githubusercontent.com/79766849/172238227-c41b3975-e5f4-4460-b5c0-648875c513d9.png">

**Comment by rami-elementor** [comment]
Hi @Sistema1A1 

Closing this issue. please re-open a new issue in English.
