### ISSUE TITLE
🐞 Bug: Products Widget Cannot Filter By Price - WooCommerce - [ED-8525]

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#18874]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Had a report from a customer that when they change the products widget to order by price, it doesn't do it right. It starts to put it in a rough order then it throws in ones that are not even close to the price order. Tried every solution which include removing cache, using Woocommerce tools to clear template cache and regenerate lookup tables, changing the order filter in the theme customiser settings and removing hosting caching.

From removing all plugins except Woocommerce, Elementor and Elementor Pro and changed to a few themes. I then used Woocommerce products shortcode and that works. Using another Elementor third-party plugin doesn't work as I think they must use Elementor's queries.

Example ~ this should be in price order of highest to lowest (Products widget | doesn't work):
![Screenshot 2022-06-07 164017](https://user-images.githubusercontent.com/55829113/172423804-742297ba-6cd5-455b-844e-7ac07356f38e.png)

Using Woocommerce shortcode ~ should be in price order of highest to lowest ([products columns="3" limit="20" orderby="price" order="DESC"] | works):
![Screenshot 2022-06-07 164847](https://user-images.githubusercontent.com/55829113/172424763-fc36e891-8095-4556-a6dc-73cdcbd435d1.png)

I even tried this on another eCommerce website and found the same problem. The archive pages seem fine, it is just when you use the products widget with Elementor.

### Steps to reproduce

From a fresh WordPress install, add Woocommerce, Elementor and Elementor Pro.

Add 20 different products with different names and completely different prices.

Create a new page, edit with Elementor and change the page layout to Elementor Canvas to remove the default theme bloat. Add the products widget to the page and change the Order By to Price and Order to DESC so it should be highest to lowest.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Tried on two eCommerce websites

**Comment by perks98** [comment]
@shilo-ey @avivu ?

**Comment by perks98** [comment]
For anyone else getting this. I have contacted Elementor Pro support and they did not help. Apparently, they are aware of the bug but do not have a fix currently and do not know how long it has been a known bug for internally. They suggested doing a rollback to see if that helps, but it didn't. I rolled back core, pro and woocommerce down multiple major versions and from what I can tell the order by filter never worked....

**Comment by 319heads** [comment]
This bug is not just limited to _Order By Price_, if you select _Order By Popularity_ there is the exact same issue - it incorrectly orders the products by Date. This has been an unaddressed issue for well over a year now.

This issue should be merged with [#15255](https://github.com/elementor/elementor/issues/15255) which shows the issue existed back in Elementor 3.2.4 and still remains in the current version. 

Just like with Order By Price, a workaround for the bug as related to Order by Popularity is to use Woocommerce shortcodes: i.e. [products best_selling="true" ]

**Comment by nicholaszein** [comment]
Hello everyone! 

Thank you for submitting your issue, and thank you for being so patient! 🙏 

I can reproduce this issue and will be forwarding this to the team.

Best regards

**Comment by arielk** [comment]
Hello,

We have great news! 🙌 

📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.14.0! 🥳 

Feel free to check it out and update your plugin to the new version!

Thanks
