### ISSUE TITLE
🚀 Replacing the splide library with the current library (swiper)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18871]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

As you know, elementor now uses the Swiper library for carousels and sliders. But the splide library is much more efficient than the swiper library. The most important advantage is that it is more Optimal. Because it has a much smaller volume than the swiper.
If you are working on elementor optimization, (you are definitely looking for this) please replace splide with swiper.

### Describe the solution you'd like

Replacing the splide library with swiper library

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for submitting a feature request.

We are not planning to replace Swiper with any alternative library in Elementor. 

This is our stated intention, and we have stated this in a number of GitHub issues in the past.

Yet, external developers can use any other library in their Elementor addons.

Regards,
