### ISSUE TITLE
🚀 Feature Request: transform for section & container

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18881]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add the transform feature to sections and containers. Currently we can only use transform for widgets. But this feature is disabled for containers and sections. I checked this in the bricks page builder, but in this page builder it is possible to use transform for sections and containers : https://prnt.sc/DOSXouelZKJF

Please add this feature to elementor.

### Describe the solution you'd like

transform feature for section & container

**Comment by joehdevwp** [comment]
+1 for this

**Comment by avivu** [comment]
I merged this issue with #18268 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
