### ISSUE TITLE
🐞 Bug in container (Accordion and toggle widget)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18880]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi

If in a container, the direction is in the form of columns and Align Items in the center, the Accordion and toggle widget will have a problem. Please watch the video below :

https://user-images.githubusercontent.com/77163248/172606942-96112878-a9db-41fb-81ee-32168b23ad7f.mp4

As you can see in the video above, opening and closing the accordion encounters bug. **Please note that this bug is present in Accordion and toggle widgets.**

### Steps to reproduce

Video above

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by 79ho3ein** [comment]
This bug is also present in the Price List widget

**Comment by 79ho3ein** [comment]
thank you @shilo-ey

**Comment by shilo-ey** [comment]
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!

**Comment by sebask63** [comment]
Is it a must-have Elementor Pro for this feature?
I can't get if in the free version of Elemento v3.7

**Comment by sebask63** [comment]
Am happy to share one of my works with Elementor; [www.katikatisafaris.com](www.katikatisafaris.com)
