### ISSUE TITLE
🐞 Bug report: Footer doesn't show correct and can't be edited

### ISSUE THREAD

**Issue by KristenMathiasen** [elementor/elementor#18892]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The footer created by Elementor has suddenly changed layout so that it looks totally different than in the editor (and like it looked earlier)
uploaded pictures to show the difference:
![pfbiler-dk-correct-looking-footer](https://user-images.githubusercontent.com/6515464/172846527-96b218d2-3aca-4f27-92cd-30749a3fe26a.png)
![pfbiler-dk-wrong-looking-footer](https://user-images.githubusercontent.com/6515464/172846531-6b7c6eb0-0341-4614-8b70-5eae6ccfb71a.png)

### Steps to reproduce

I have no idea of how and when the issue startet but when I found the problem I did the following:
I started by taking a backup of the whole site.
I visited the footer template and updated it = no change
I have tried to deactivate all plugins = no change
I have tried to roll back WordPress to 5.8.4 = no change
I have run Wedsite Health and there are no problems found.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 41, Revision da46e5474f9 v5.7.38-41
	PHP Version: 7.4.30
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://pfbiler.dk
	Home URL: https://pfbiler.dk
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: 1
	Admin Email: moyten1@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Business Hours Indicator
		Version: 2.3.8
		Author: Maarten Belmans

	Contact Form 7
		Version: 5.5.6.1
		Author: Takayuki Miyoshi

	Contact Form 7 Widget For Elementor Page Builder & Gutenberg Blocks
		Version: 1.1.3
		Author: HT Plugins

	Elementor
		Version: 3.7.0-dev9
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev16
		Author: Elementor.com

	UpdraftPlus - Backup/Restore
		Version: 1.22.12
		Author: UpdraftPlus.Com, DavidAnderson

	Yoast SEO
		Version: 19.0
		Author: Team Yoast

== Elementor Experiments ==
	Optimeret DOM-output: Aktiv som standard
	Forbedret ressourceindlæsning : Aktiv som standard
	Forbedret indlæsning af CSS ressourcer: Inaktiv som standard
	Inline Font Icons: Inaktiv som standard
	Accessibility Improvements: Aktiv som standard
	Importer/Eksporter Kit skabelon: Aktiv som standard
	Additional Custom Breakpoints: Inaktiv som standard
	Hide native WordPress widgets from search results: Aktiv som standard
	: Inaktiv som standard
	Flexbox Container: Inaktiv som standard
	Default to New Theme Builder: Aktiv som standard
	Hello sidehoved og sidefod: Aktiv
	Landingsside: Aktiv som standard
	Color Sampler: Aktiv som standard
	Favorit widgets: Aktiv som standard
	Administrator topbjælke: Aktiv som standard
	Page Transitions: Aktiv som standard
	Notes: Aktiv som standard
	Modtagne formularer: Aktiv som standard
	Scroll Snap: Aktiv som standard

== Log ==
	
Log: showing 20 of 362022-05-22 11:31:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-22 11:31:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-22 11:31:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-08 19:49:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-08 19:49:55 [info] elementor::elementor_updater Started 
2022-06-08 19:49:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-08 19:49:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-08 19:49:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-09 12:07:29 [info] elementor::elementor_updater Started 
2022-06-09 12:07:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-09 12:07:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-09 12:07:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-06-09 12:07:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-06-09 12:07:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0-dev9',
)]
2022-06-09 12:07:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0-dev9',
)]
2022-06-09 13:04:44 [info] elementor-pro::elementor_pro_updater Started 
2022-06-09 13:04:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-09 13:04:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-09 13:04:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.8.0-dev16',
)]
2022-06-09 13:04:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.8.0-dev16',
)]

PHP: showing 3 of 3PHP: 2022-05-14 09:44:03 [notice X 6046][/var/www/pfbiler.dk/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1446] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-08 20:02:00 [notice X 1][/var/www/pfbiler.dk/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-09 12:53:48 [notice X 2][/var/www/pfbiler.dk/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-06-09 10:50:49 [error X 2][https://pfbiler.dk/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Failed to execute \'removeChild\' on \'Node\': The node to be removed is no longer a child of this node. Perhaps it was moved in response to a mutation? 
JS: 2022-06-09 11:06:28 [error X 1][https://pfbiler.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6150\") has already been destroyed and cannot be used. 
JS: 2022-06-09 11:53:17 [error X 1][https://pfbiler.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev9:2:702036] elementorFrontend is not defined 

== Elementor - Compatibility Tag ==
	
	Contact Form 7 Widget For Elementor Page Builder & Gutenberg Blocks: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @KristenMathiasen ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
