### ISSUE TITLE
🚀 Feature Request: Margin & padding presets for containers in Site Settings

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#18897]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The new Container widget is pretty cool, but it is very bare bones, and I often find myself having to set up the basics for padding and margins, and then tweak this for tablet mobile. Once that's done I then need to copy and paste this to all the other containers across my site, which is time consuming & prone to inconsistency.

I do miss the way that Sections and Inner Sections used to work, where it was easy to set some basic padding rules on containers, and there was also a default which applied to everything. It made it much easier to display content with adequate padding on mobile, without having to worry about content touching the edge of the screen.

### Describe the solution you'd like

I would like to have a Site Settings preference that allows us to create different margin and padding styles for containers, and then each container would have a dropdown that lets us pick the various styles. 

For example, I could create my own presets like:
**Zero margin / padding** - 0,0,0,0 margin, 0,0,0,0 padding
**CTA section margins** - 32px, 0, 32px, 0 margin, 0,0,0,0 padding
**Column padding for mobile only** - {Desktop} 0,0,0,0 padding, {Mobile} 5vw, 0, 5vw, 0 padding

and so on. 

Then, for each container, I could pick from a dropdown:

Layout style: [Zero margin / padding  ⌄ ]

Later on if I want to tweak the padding/margin for a style, I can simply do that and all the applied styles on each container automatically update.

### Describe alternatives you've considered

You could do this by writing CSS rules and then applying classes to sections. Advanced users would be comfortable with this, but first time / beginners would find it challenging. 

I figure that we already have a strong Site Settings system in place for colours, fonts, etc. and it could be easily extended to margins and padding too.

It also doesn't have to be limited to just containers, the margin and padding styles could also be easily set on other elements, and be fully overridden by values in the Advanced tabs.

**Comment by black-eye** [comment]
+1
Very needed, indeed.

**Comment by 79ho3ein** [comment]
+1
I think all containers should have 10 pixels padding by default. It was the same in the beta, but elementor dropped it. But by adding this feature, this issue will be completely solved

**Comment by joehdevwp** [comment]
YES I completely agree with this! +1000 
I have already built several sites using Containers and this is quickly becoming a serious issue.

**Comment by james-mallette** [comment]
+1

My current solution is to save an empty container with margin/padding applied as a template, then include that anytime I need a new section. But your proposed solution is much better.

**Comment by ludekcerny** [comment]
+1

**Comment by arielk** [comment]
Ref: #965
