### ISSUE TITLE
Problem in scrolling up and down 🐞 Bug report: 

### ISSUE THREAD

**Issue by vasudevz** [elementor/elementor#18891]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I activate Elementor Pro and open the site in the mobile version, there is a problem scrolling up and down. This happens because of a conflict between Olympus theme and Elementor Pro.

### Steps to reproduce

Just visit any page on the website www.soulipi.club and scroll. On my site, the plugin is deactivated because it creates a problem for the user. Kindly email me at vasudev__bajpai@hotmail.com to have it activated.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v8.0.28
	PHP Version: 7.4.25
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 505M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://www.soulipi.club
	Home URL: https://www.soulipi.club
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Asia/Kolkata
	Admin Email: vasudev__bajpai@hotmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Olympus child Theme
	Version: 1
	Author: Crumina Team
	Child Theme: Yes
	Parent Theme Name: Olympus
	Parent Theme Version: 3.97
	Parent Theme Author: crumina

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33

== Active Plugins ==
	All in One SEO
		Version: 4.2.1.1
		Author: All in One SEO Team

	bbPress
		Version: 2.6.9
		Author: The bbPress Contributors

	BuddyPress
		Version: 10.3.0
		Author: The BuddyPress Community

	BuddyPress Anonymous Activity
		Version: 1.0.10
		Author: Brajesh Singh

	BuddyPress Follow
		Version: 1.3-alpha
		Author: Andy Peatling, r-a-y

	BuddyPress Moderation Tools
		Version: 1.4.7
		Author: BuddyDev

	BuddyPress Username Changer
		Version: 1.2.6
		Author: BuddyDev

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Code Snippets
		Version: 3.1.0
		Author: Code Snippets Pro

	DaftPlug Instantify - PWA & Google AMP & Instant Articles
		Version: 6.6
		Author: DaftPlug

	DreamHost Panel Login
		Version: 1.0.0
		Author: DreamHost, danielbachhuber

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Olympus Widgets
		Version: 1.9.5
		Author: 

	Envato Market
		Version: 2.0.7
		Author: Envato

	GamiPress
		Version: 2.3.4
		Author: GamiPress

	GamiPress - BuddyPress integration
		Version: 1.5.3
		Author: GamiPress

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	Meta Box
		Version: 5.6.4
		Author: MetaBox.io

	Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue
		Version: 3.1.43
		Author: Sendinblue

	Post grid and filter ultimate
		Version: 1.4.5
		Author: WP OnlineSupport, Essential Plugin

	Proxy Cache Purge
		Version: 5.1.2
		Author: Mika Epstein

	Razorpay for WooCommerce
		Version: 3.8.2
		Author: Team Razorpay

	Razorpay Subscriptions for WooCommerce
		Version: 2.3.3
		Author: Razorpay

	Robin image optimizer
		Version: 1.5.6
		Author: Creative Motion <info@cm-wp.com>

	Tidio Chat
		Version: 5.0.0
		Author: Tidio Ltd.

	Unyson
		Version: 2.16
		Author: ThemeFuse

	Webcraftic Clearfy – WordPress optimization plugin
		Version: 2.0.5
		Author: Creative Motion <info@cm-wp.com>

	WebinarPress Pro
		Version: 2.24.30
		Author: WebinarPress

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WooCommerce Membership
		Version: 2.2.4
		Author: RightPress

	WooCommerce One Page Checkout
		Version: 1.9.3
		Author: Automattic

	WooCommerce Subscriptions
		Version: 4.1.0
		Author: WooCommerce

	wpDiscuz
		Version: 7.3.17
		Author: gVectors Team

	Youzify
		Version: 3.3.2
		Author: KaineLabs

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive

== Log ==
	
Log: showing 20 of 352022-04-13 23:17:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-13 23:17:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-13 23:17:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-04-13 23:17:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.3',
  'to' => '3.6.4',
)]
2022-05-01 23:07:17 [info] elementor::elementor_updater Started 
2022-05-01 23:07:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-01 23:07:17 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-01 23:07:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-07 20:05:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-06-07 20:06:20 [info] elementor-pro::elementor_pro_updater Started 
2022-06-07 20:06:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-07 20:06:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-07 20:06:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-06-07 20:06:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-06-09 02:03:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-09 02:03:59 [info] elementor::elementor_updater Started 
2022-06-09 02:03:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-09 02:03:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-09 02:03:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-09 02:04:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]

JS: showing 1 of 1JS: 2022-04-11 19:12:42 [error X 3][https://www.soulipi.club/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:242684] Cannot read properties of undefined (reading \'html\') 

PHP: showing 7 of 7PHP: 2022-04-12 21:44:48 [error X 1][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/theme-builder/module.php::30] Uncaught Error: Class 'ElementorPro\Core\Utils' not found in /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/theme-builder/module.php:30
Stack trace:
#0 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/theme-builder/conditions/archive.php(39): ElementorPro\Modules\ThemeBuilder\Module::get_public_post_types()
#1 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): ElementorPro\Modules\ThemeBuilder\Conditions\Archive->register_sub_conditions()
#2 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(182): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct(Array)
#3 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(193): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_condition('archive', Array)
#4 /home/wp_tk6q3q/soulipi.club/wp-content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-12 21:44:48 [error X 1][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/plugin.php::327] Uncaught Error: Class 'ElementorPro\Core\Modules_Manager' not found in /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/plugin.php:327
Stack trace:
#0 /home/wp_tk6q3q/soulipi.club/wp-includes/class-wp-hook.php(307): ElementorPro\Plugin->on_elementor_init('')
#1 /home/wp_tk6q3q/soulipi.club/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/wp_tk6q3q/soulipi.club/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/plugin.php(646): do_action('elementor/init')
#4 /home/wp_tk6q3q/soulipi.club/wp-includes/class-wp-hook.php(307): Elementor\Plugin->init('')
#5 /home/wp_tk6q3q/soulipi.club/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 /home/wp_tk6q3q/soulipi.club/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#7 /home/wp_tk6q3q/soulipi.club/wp-settings.php(587): do_action('init')
#8 /home/wp_tk6q3q/soulipi.club/wp-config.php(100): require_once('/home/wp_tk6q3q...')
# [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-16 00:27:37 [error X 1][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/managers/elements.php::84] Uncaught Error: Call to a member function get_default_args() on array in /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/managers/elements.php:84
Stack trace:
#0 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/files/css/post.php(172): Elementor\Elements_Manager->create_element_instance(Array)
#1 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/files/css/base.php(632): Elementor\Core\Files\CSS\Post->render_css()
#2 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#3 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/files/css/base.php(131): Elementor\Core\Files\Base->update_file()
#4 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/files/css/base.php(218): Elementor\Core\Files\CSS\Base->update()
#5 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#6 /home/wp_tk6q3q/soulipi.club/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-04 04:51:45 [notice X 18][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-05 00:53:22 [notice X 2][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-02 14:30:57 [notice X 1][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-07 19:53:52 [error X 2][/home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/base/controls-stack.php::2367] Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1105 and defined in /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/base/controls-stack.php:2367
Stack trace:
#0 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/base/controls-stack.php(1105): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/base/controls-stack.php(2116): Elementor\Controls_Stack->get_data('settings')
#2 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /home/wp_tk6q3q/soulipi.club/wp-content/plugins/elementor/includes/base/cont [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Olympus Widgets: Compatibility not specified

**Comment by rami-elementor** [comment]
Sounds like the "Olympus theme" is not compatible with "Elementor".

Try switching to [Hello theme](https://wordpress.org/themes/hello-elementor/), or contact the olympus developers to fix the issue.
