### ISSUE TITLE
🐞 Bug report: Site goes  blank without displaying any error

### ISSUE THREAD

**Issue by temsool** [elementor/elementor#18903]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We had a hard week and no one helped to find the issue, so I debugged everything, 
disabled all plugins, and enabled all of them one by one. at the end, found that when **Elementor PRO is Active**, and Enable **LightSpeed** cache OR Enable **"Mixed content fixer"** feature in Really simple SSL, while **Elementor PRO is Active**, site goes blank without showing any error.

Asked server support, they Not helped.

Asked Elementor Support, they simply replied:

> Thank you for contacting Elementor Support.
> ​
> 
> Unfortunately, third-party plugins fall out of our support scope.
> 
> If the site is working correctly as you said when you have only Elementor and Elementor Pro active, we cannot guarantee the functionality of additional third-party plugins.
> 
> We suggest contacting the author of the plugin that's causing the conflict directly, as they should be able to help.
> 
> Sorry for the inconvenience.
> 
> For any other Elementor-related questions, don't hesitate to contact us again.

So, I told to myself, **ONLY YOU CAN HELP YOURSELF!**

Started disabling all plugins and WordPress default theme, still broken, and Tested with Hello Elementor, it was gone!
so, something was in Hello Elementor theme, and NOT in any other WordPress Default theme.

after Checking `function.php` in Hello Elementor, and other files, could sort the issue!

Solution is here:
You must have this in `function.php` in your theme folder
```

// ---------------------- this is solving Blank Screen bug --------------------------

function myprefix_register_elementor_locations( $elementor_theme_manager ) {
   
  
	$elementor_theme_manager->register_all_core_location();
	

} 
add_action( 'elementor/theme/register_locations', 'myprefix_register_elementor_locations' );

// ---------------------- this is solving Blank Screen bug --------------------------
```

and in `header.php` must have this:
```
if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'header' ) ) {
		//does nothing! just must be here to solve stupid bug!
}
```

and in `footer.php` must have this:

```
if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'footer' ) ) {
    //does nothing! just must be here to solve stupid bug!
}
```

and in `index.php` must have this:
```

get_header();


$is_elementor_theme_exist = function_exists( 'elementor_theme_do_location' );

if ( is_singular() ) {
	if ( ! $is_elementor_theme_exist || ! elementor_theme_do_location( 'single' ) ) {
	the_content();	
	}
} elseif ( is_archive() || is_home() ) {
	if ( ! $is_elementor_theme_exist || ! elementor_theme_do_location( 'archive' ) ) {
	the_content();	
	}
} elseif ( is_search() ) {
	if ( ! $is_elementor_theme_exist || ! elementor_theme_do_location( 'archive' ) ) {
		the_content();
	}
} else {
	if ( ! $is_elementor_theme_exist || ! elementor_theme_do_location( 'single' ) ) {
	the_content();	
	}
}

get_footer();
```

### Steps to reproduce

Not sure but I'm sure about that someone out there is looking for solution, so, if your site goes blank without any error after recently update on Elementor, try this.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rami-elementor** [comment]
It usually means that you are using a Theme that is not Elementor compatible.

**Comment by rami-elementor** [comment]
Red more about Elementor compatible themes at https://developers.elementor.com/docs/themes/
