### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by kevinpajak** [elementor/elementor#18929]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, I'm hoping that somebody can help me here. I'm trying to locate **WHERE EXACTLY IN THE HELLO ELEMENTOR THEME FILES** that the code elements are located that would allow you to custom edit output on an individual post??

I noticed that in index.php, you CAN actually grab elements from $post, and I also see:
if ( is_singular() ) {
	if ( ! $is_elementor_theme_exist || ! elementor_theme_do_location( 'single' ) ) { 
		get_template_part( 'template-parts/single' );
	}
} 

, which APPEARs to indicate that this would be in the file: 'template-parts/single', but it does not look like this is actually the case.

What I am trying to do is: if someone uploads a "Secondary Featured Image" using the Elementor theme, then use this as the Featured Image for an individual post, else use the regular featured image already included for a post.

something like:
if (!empty(get_field("featured_image_2")))
{
	$featuredImage = get_field( "featured_image_2")['url'];
}
else
{
        $featuredImage = get_the_post_thumbnail_url( get_the_ID());
}

but I can not see where to place this code in the theme. **Where in your theme does $featuredImage get defined and then used to output within an individual blog post??**

thank you so much for your help!!

### Steps to reproduce

themes/hello-elementor/index.php

themes/hello-elementor/template-parts/single.php

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | nginx/1.16.1 |  
MySQL version: | MariaDB Server v5.6.26-76.0 |  
PHP Version: | 7.3.33 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | There are some writing permissions issues with the following directories/files: 		 - WordPress root directory |  
Elementor Library: | Connected |  

</div>Server Environment		
Operating System:	Linux	
Software:	nginx/1.16.1	
MySQL version:	MariaDB Server v5.6.26-76.0	
PHP Version:	7.3.33	
PHP Max Input Vars:	10000	
PHP Max Post Size:	100M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	There are some writing permissions issues with the following directories/files:
		 - WordPress root directory	
Elementor Library:	Connected	
WordPress Environment		
Version:	5.8.1	
Site URL:	https://cdp.com	
Home URL:	https://cdp.com	
WP Multisite:	No	
Max Upload Size:	100 MB	
Memory limit:	256M	
Permalink Structure:	/articles/%postname%/	
Language:	en-US	
Timezone:	0	
Admin Email:	nik@treasure-data.com	/ kevin.pajak@treasure-data.com
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	2.4.1	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36

**Comment by rami-elementor** [comment]
Hi @kevinpajak ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
