### ISSUE TITLE
🚀 Feature Request: CSS Functions in Widgets Panel

### ISSUE THREAD

**Issue by james-mallette** [elementor/elementor#18939]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm always frustrated when I have to use custom CSS to include CSS functions in my website. 

### Describe the solution you'd like

It would be nice if Elementor allowed the user to input CSS functions such as calc() and clamp() directly into the unit inputs in the widgets panel.

### Describe alternatives you've considered

Can be solved by using custom CSS, but it would be nice if it was allowed in the widgets panel.

**Comment by arielk** [comment]
Hello,

in order to keep the conversation only in one place, I'm closing the comments here.

Please, feel free to continue the conversation there: 👉 https://github.com/elementor/elementor/issues/2219

Thanks! 🙏

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
