### ISSUE TITLE
🚀 Feature Request: Ability to display a caret indicator in the Tabs widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18932]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

This is a small request, but great if added in the Tabs widget development version...

Please add the ability to display the [cursor](https://prnt.sc/i4LKbn-yhnBZ) to the tabs widget. It can be very useful.

### Describe the solution you'd like

https://user-images.githubusercontent.com/77163248/173597758-9a91005b-7532-4d62-b621-53d059b81e23.mp4

**Comment by nicholaszein** [comment]
Hello @79ho3ein ,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
