### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by dlayd** [elementor/elementor#18949]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I am creating a new saved template (section) after setting the "view dynamic content as" to anything and reloading the page I am faced with a message that says the page is missing "the_content."

### Steps to reproduce

1. Create a new saved section template
2. After the elementor panel loads, click the settings gear
3. Select any option from the "preview dynamic content as" dropdown under the "preview settings" tab
4. Click the "apply & preview" button

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://staging4.mindfuldegens.com
	Home URL: https://staging4.mindfuldegens.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -6
	Admin Email: d3layd@mindfuldegens.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 17 of 172022-06-09 14:29:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-09 14:36:19 [info] elementor-pro::elementor_pro_updater Started 
2022-06-09 14:36:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-09 14:36:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-09 14:36:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-14 13:49:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.6.0',
  'to' => '2.6.1',
)]
2022-06-14 15:59:00 [info] dynamic-content-for-elementor::dce_updater Started 
2022-06-14 15:59:00 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_6_1_views_change_default Start  
2022-06-14 15:59:00 [info] Dynamic.ooo - Dynamic Content for Elementor/Upgrades - _v_2_6_1_views_change_default Finished 
2022-06-14 15:59:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.6.0',
  'to' => '2.6.1',
)]
2022-06-15 15:08:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-06-15 15:15:16 [info] elementor-pro::elementor_pro_updater Started 
2022-06-15 15:15:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-15 15:15:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-15 15:15:16 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-15 15:15:16 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-15 15:15:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

PHP: showing 8 of 8PHP: 2022-06-09 14:53:13 [notice X 7][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 15:29:10 [notice X 8][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor-pro/modules/library/wp-widgets/elementor-library.php::42] Undefined index: id [array (
  'trace' => '
#0: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor-pro/modules/library/wp-widgets/elementor-library.php(42): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/widgets.php(1257): ElementorPro\Modules\Library\WP_Widgets\Elementor_Library -> widget()
#2: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(548): class type the_widget()
#3: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(518): WP_REST_Widget_Types_Controller -> get_widget_preview()
#4: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1143): WP_REST_Widget_Types_Controller -> encode_form_data()
',
)]
PHP: 2022-06-13 15:29:11 [notice X 7][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor-pro/modules/library/wp-widgets/elementor-library.php::42] Undefined index: id [array (
  'trace' => '
#0: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor-pro/modules/library/wp-widgets/elementor-library.php(42): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/widgets.php(1257): ElementorPro\Modules\Library\WP_Widgets\Elementor_Library -> widget()
#2: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/blocks/legacy-widget.php(51): class type the_widget()
#3: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/class-wp-block-type.php(288): class type render_block_core_legacy_widget()
#4: /home/customer/www/staging4.mindfuldegens.com/public_html/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(644): WP_Block_Type -> render()
',
)]
PHP: 2022-06-13 21:39:48 [notice X 29][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 21:45:17 [notice X 17][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor/core/app/modules/import-export/module.php::90] Trying to get property &#039;label&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 21:45:19 [notice X 16][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-15 18:31:53 [notice X 1][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-16 15:22:05 [notice X 1][/home/customer/www/staging4.mindfuldegens.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 18 of 18JS: 2022-06-14 03:28:48 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view6574\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-14 03:30:47 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view128\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-14 12:39:08 [error X 1][https://staging4.mindfuldegens.com/wp-admin/post.php?post=453&action=elementor#:3839:22] Cannot read properties of null (reading \&#039;url\&#039;) 
JS: 2022-06-15 21:07:12 [error X 2][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view92\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 21:33:38 [error X 5][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view115\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 21:37:53 [error X 5][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view119\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 21:42:14 [error X 2][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view96\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 21:46:22 [error X 2][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view104\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 21:48:32 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view111\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 21:48:38 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view7163\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 22:05:09 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view127\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 22:09:05 [error X 2][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view131\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 22:13:30 [error X 2][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view100\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 22:22:38 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view110\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 22:34:54 [error X 1][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view2596\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 23:02:48 [error X 4][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view137\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 23:03:23 [error X 5][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view95\&quot;) has already been destroyed and cannot be used. 
JS: 2022-06-15 23:25:04 [error X 2][https://staging4.mindfuldegens.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @dlayd ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by dlayd** [comment]
This isn't support, that's an actual bug. @rami-elementor

**Comment by rami-elementor** [comment]
Hi @dlayd ,

I could not recreate the issue. Can you upload a video? or add a more detailed steps to reproduce?
