### ISSUE TITLE
🐞 Inline Font Icons bug  For all icons and menu cart icon

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18947]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After the new elementor pro update, by fixing the bug related to Inline Font Icons, the menu cart widget icon is no longer hidden and works well.
But activating Inline Font Icons creates a problem. **The problem is that if we enable this option, all elementor icons will move slightly up.**  Please see this bug in the menu cart widget icon in the video below : 

( Unfortunately, the video cannot be uploaded )

As you can see in the video above, there is a difference before and after activating the Inline Font Icons option. After activating this option, the icon will move slightly upwards. **Of course, this happens to all icons in elementor.**

Inline Font Icons is disabled : https://prnt.sc/xydAfhuEsmqw
Inline Font Icons is enabled : https://prnt.sc/sTry2r4pUBju

If you look closely at the images above, after activating the Inline Font Icons, the thickness of the icon has changed and even moved a bit. Also the size of the button has changed!

### Steps to reproduce

1- Add a button and assign an icon to it 
2- Compare this button before and after activating the Inline Font Icons option. It is quite clear that there is a problem.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by m1ga** [comment]
Hi @79ho3ein
since you do so many reports here a quick suggestion: just drag&drop the images into the issue so they are included right away. Makes it so much easier/quicker to see the images without going to prnt.sc all the time :smile:

**Comment by perks98** [comment]
With ❤ I agree with @m1ga.

For me, both the screenshots you submitted are the same.

But also the Inline Font Icons experiment has been broken for a very long time which is why they left it in alpha state for so long which is disappointing. I do wish they would put time into finalising this, but I would prefer they fix all the major problems with the flexbox experiment first, to be honest.

**Comment by 79ho3ein** [comment]
hi @perks98 , Thanks for the comment. In fact, the two screenshots are not the same. But this is because of the way the image was sent, which I did not do properly.
I totally agree with you about the container. Stabilization of the container is definitely a priority.

**Comment by rami-elementor** [comment]
Hi @perks98 ,

When the "**Inline Font Icons**" experiment is deactivated, Elementor loads the fonts with the CSS file and an `<i>` tag. When the experiment is active, Elementor loads only the `<SVG>` files.

The "Inline Font Icons" experiment is not broken, it is still in **alpha** state development. The core functionality works as expected, **but** we still need to fix all the widgets to support both situations, with and without the experiment.

We monitor all the bug reports. But du to tight schedule we need to prioritize some tasks. Currently the container has a higher priority.

**Comment by nicholaszein** [comment]
Hey guys,

There is another issue related to the Menu Cart icon not appearing when the Inline Font Icons experiment is active.

To simplify things, I'm going to close this issue and **🔃 Merge** it with the original #17692, since this is the only icon with this problem.

Thanks! 🙏
