### ISSUE TITLE
🐞 Bug report: YouTube Video Player Thumbnails without HTTPS

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#18945]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

So, the Video Player from Elementor is showing the thumbnails without https.
<img width="807" alt="Screen Shot 2022-06-16 at 11 39 48" src="https://user-images.githubusercontent.com/68023943/174095150-0ffed5a9-66ee-46b3-b46f-51ed3b53f12c.png">

### Steps to reproduce

Add 3 videos to a video player. See the code.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.1
	MySQL version: MariaDB Server v10.5.12
	PHP Version: 8.1.3
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://mydomain.com.gg
	Home URL: https://mydomain.com.gg
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%
	Language: es
	Timezone: America/Argentina/Buenos_Aires
	Admin Email: -
	Debug Mode: Inactive

== Theme ==
	Name: Globant Theme
	Version: 2.0.0
	Author: Globant
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	File Manager Advanced
		Version: 4.1.4
		Author: modalweb

	Forms to Pardot
		Version: 1.8.1
		Author: Globant

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	GD Security Headers
		Version: 1.6.1
		Author: Milan Petrovic

	JetBlocks For Elementor
		Version: 1.3.2
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.2.17
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.6
		Author: Crocoblock

	JetEngine
		Version: 2.11.9
		Author: Crocoblock

	JetFormBuilder
		Version: 2.0.6
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.17
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.12
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.17
		Author: Crocoblock

	JetTricks
		Version: 1.4.1
		Author: Crocoblock

	JQuery UI replacer
		Version: 1.0
		Author: Globant

	MainWP Child
		Version: 4.2.3
		Author: MainWP

	Rank Math SEO
		Version: 1.0.90
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.13
		Author: Rank Math

	Wordfence Security
		Version: 7.5.11
		Author: Wordfence

	WP Activity Log
		Version: 4.4.1
		Author: WP White Security

	WPvivid Backup Plugin
		Version: 0.9.72
		Author: WPvivid Team

	WPvivid Imgoptim Free
		Version: 0.9.16
		Author: WPvivid Team

	WPvivid Plugins Pro
		Version: 2.2.5
		Author: wpvivid.com

== Uso de los elementos ==
	
	header : 2
		nav-menu : 2
		theme-site-logo : 1
	page : 3
		button : 6
		heading : 6
		image : 3
	section : 16
		button : 15
		counter : 3
		heading : 34
		icon-box : 2
		image : 17
		jet-listing-dynamic-field : 1
		jet-listing-dynamic-terms : 2
		jet-listing-grid : 10
		jet-smart-filters-radio : 1
		jet-tabs : 1
		social-icons : 4
		text-editor : 1
	wp-post : 4
		text-editor : 3
	wp-page : 5
		button : 2
		counter : 2
		heading : 36
		icon-box : 3
		image : 24
		jet-images-layout : 1
		jet-listing-grid : 9
		jet-tabs : 1
		menu-anchor : 1
		text-editor : 3
		video : 2
	jet-listing-items : 0
		button : 2
		heading : 1
		icon-box : 2
		image : 1
		image-box : 1
		jet-listing-dynamic-field : 4
		jet-listing-dynamic-link : 1
		jet-listing-dynamic-repeater : 1

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo por defecto
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Inactivo
	Mejoras de accesibilidad: Activo por defecto
	Importar o exportar un kit de plantillas: Activo
	Puntos de ruptura personalizados adicionales: Activo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	: Inactivo por defecto
	Contenedor Flexbox: Inactivo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Cabecera y pie de página del tema Hello: Inactivo
	Páginas de destino: Inactivo
	Muestrario de colores: Inactivo
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Transiciones de páginas: Activo por defecto
	Notes: Activo por defecto
	Envíos de formulario: Activo
	Ajuste de scroll: Activo por defecto

== Registro ==
	
Log: showing 20 of 212022-04-04 09:45:32 [info] elementor-pro::elementor_pro_updater Started 
2022-04-04 09:45:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-04 09:45:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-04 09:45:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.4',
)]
2022-04-04 09:45:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0',
  'to' => '3.6.4',
)]
2022-04-06 14:07:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 14:07:01 [info] elementor::elementor_updater Started 
2022-04-06 14:07:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-06 14:07:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-06 14:07:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-06 14:07:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-06-13 11:35:04 [info] elementor-pro::elementor_pro_updater Started 
2022-06-13 11:35:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-13 11:35:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-13 11:35:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.1',
)]
2022-06-13 11:35:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.1',
)]
2022-06-13 11:35:09 [info] elementor::elementor_updater Started 
2022-06-13 11:35:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-13 11:35:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-13 11:35:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.5',
)]

PHP: showing 12 of 12PHP: 2022-04-04 09:45:27 [notice X 57678][/var/www/mydomain.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-04 11:20:48 [notice X 126][/var/www/mydomain.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/mydomain.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/mydomain.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/mydomain.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/mydomain.com/wp-content/plugins/jet-search/includes/integration.php(108): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-04-25 15:06:04 [warning X 2][/var/www/mydomain.com/wp-content/plugins/elementor/core/files/css/base.php::697] Undefined array key "background_color" [array (
  'trace' => '
#0: /var/www/mydomain.com/wp-content/plugins/elementor/core/files/css/base.php(697): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/mydomain.com/wp-content/plugins/elementor/core/files/css/base.php(671): Elementor\Core\Files\CSS\Base -> get_style_control_value()
#2: Elementor\Core\Files\CSS\Base -> Elementor\Core\Files\CSS\{closure}()
#3: /var/www/mydomain.com/wp-content/plugins/elementor/core/files/css/base.php(442): class type call_user_func()
#4: /var/www/mydomain.com/wp-content/plugins/elementor/core/files/css/base.php(348): Elementor\Core\Files\CSS\Base -> parse_property_placeholder()
',
)]
PHP: 2022-04-25 15:48:57 [notice X 188][/var/www/mydomain.com/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-30 10:23:42 [notice X 1539][/var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/mydomain.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/mydomain.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/mydomain.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/mydomain.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/mydomain.com/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-05-31 14:32:51 [notice X 13][/var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-01 11:30:27 [notice X 25][/var/www/mydomain.com/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-12 01:35:25 [notice X 6][/var/www/mydomain.com/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/mydomain.com/wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: /var/www/mydomain.com/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: /var/www/mydomain.com/wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
#4: /var/www/mydomain.com/wp-includes/plugin.php(476): WP_Hook -> do_action()
',
)]
PHP: 2022-06-13 11:28:40 [warning X 1][/var/www/mydomain.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 18:09:28 [notice X 3][/var/www/mydomain.com/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/mydomain.com/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/mydomain.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/mydomain.com/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/mydomain.com/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-06-14 09:51:31 [notice X 3][/var/www/mydomain.com/wp-content/plugins/elementor-pro/license/updater.php::84] version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-16 11:22:45 [notice X 38][/var/www/mydomain.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] ¡El argumento $control_id está obsoleto desde la versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2022-04-12 13:47:21 [error X 1][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2898\") has already been destroyed and cannot be used. 
JS: 2022-04-25 18:29:30 [error X 3][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view78\") has already been destroyed and cannot be used. 
JS: 2022-05-23 20:33:08 [error X 1][https://mydomain.com.gg/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.5:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `custom_thumb` value. Expected array or object.',
)]
JS: 2022-05-23 20:40:58 [error X 2][https://mydomain.com.gg/wp-content/plugins/elementor-pro/assets/js/video-playlist.e85695d7b9171d89c565.bundle.min.js:2:5698] Cannot read properties of undefined (reading \'setVideoProviderData\') 
JS: 2022-05-23 20:49:56 [error X 1][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6197\") has already been destroyed and cannot be used. 
JS: 2022-05-23 20:49:57 [error X 1][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6234\") has already been destroyed and cannot be used. 
JS: 2022-06-13 16:35:42 [error X 1][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view331\") has already been destroyed and cannot be used. 
JS: 2022-06-13 18:39:04 [error X 8][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view355\") has already been destroyed and cannot be used. 
JS: 2022-06-16 14:18:23 [error X 1][https://mydomain.com.gg/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view82\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada
	JetBlocks For Elementor: Compatibilidad no especificada
	JetBlog For Elementor: Compatibilidad no especificada
	JetElements For Elementor: Compatibilidad no especificada
	JetSearch For Elementor: Compatibilidad no especificada
	JetTabs For Elementor: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Related: #18895

**Comment by rami-elementor** [comment]
Hi @maurocarreraok,

Thank you for taking the time to report this bug.

I fixed this issue. You will see it in the coming **Elementor Pro 3.8** release.

**Comment by avivu** [comment]
This issue has been resolved in Elementor Pro v3.8.0

Feel free to update

Thanks!
