### ISSUE TITLE
🚀 Change slide controls In elementor editor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18971]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I think these controls are obsolete in another elementor and do not work well. https://prnt.sc/daOc4-_URaou
These sliders limit us in a size range. For example, they consider a minimum of 500 and a maximum of 1600. https://prnt.sc/5t_l2yLitqps

I think it is better to remove this type of slider forever. A simple box to enter the amount (without limit) will be much better. 
Like this: https://prnt.sc/ees8AOwESRFv

### Describe the solution you'd like

Change slide controls

**Comment by Michaelgimii** [comment]
This works well in the bricks page builder https://prnt.sc/yXcfzyM0Ixxs

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for submitting a feature request.

After review, we have decided not to remove the slider control.

Please feel free to contact us again with other feature suggestions.

Regards,
