### ISSUE TITLE
Feature Request: Add "Hover Animation" to "Image Gallery"

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#1898]
The regular "**Image**" widget has both the "**Hover Animation**" (in "Style" tab) and the "**Entrance Animation**" (in the "Advanced" tab).

The "**Image Gallery**" widget has only the "**Entrance Animation**" (in "Advanced" tab). It's missing the beautiful "**Hover Animation**".

**Comment by TritonB7** [comment]
I too would like to have hover animations added to the Image Gallery.

**Comment by ramiy** [comment]
I tried to add "**Hover Animation**" control to add Elementor animation classes to "**Image Gallery**" widget, but it seems like the widget uses WordPress `[gallery]` shortcode. This shortcode doesn't support custom classes for images.

**Comment by haemeulrich** [comment]
@ramiy Is this still the case? Do you have a solution for this in the meantime? I'm interested in the same effect as well.

**Comment by nepa** [comment]
I would also appreciate a hover option for pictures in the Image Gallery. It would be sufficient to define the style once for the entire gallery, not individually for each image. I'd use it to add a simple overlay effect, such that the image slightly looses saturation, when you hover it. For single images this already works great in Elementor.

While Elementor's Image Gallery does not support hover effects, is there any other Elementor add on or hack that I can use to achieve the desired effect?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by nepa** [comment]
> This issue has been resolved in Elementor Pro v2.7

@shilo-ey: As of now, I'm using Elementor 2.8.2 and I cannot find any additional options for *Hover Animation* in the image gallery. Still, there is only *Entrance Animation*. Is this feature only available in the Pro version?

**Comment by JeremyLopez** [comment]
I also don't see this feature and I am a Pro user...
