### ISSUE TITLE
🐞 Bug report: HTML Widget and Text Widget does not allow HTML when Dynamic Tags are used

### ISSUE THREAD

**Issue by rouxsean** [elementor/elementor#18995]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I have a URL as a dynamic tag (in the user meta), I am able to properly pull this tag into the HTML. (The URL properly appears with no improper conversion of any characters.

However, when I use the following as "Before" the dynamic tag (under "Advanced"):  <img src="

and this as "After" the dynamic tag: ">

Elementor outputs the following:

&lt;img src=&quot;https://my.home.url/wp-content/uploads/gravity_forms/7-c21cc6d93b0f4d54935fff542f32ef14/2022/06/my_awesome_photo.jpg"&gt;

(EDIT: github shows the HTML character, not the named code. For the sake of clarity, less than appears as & l t ; and less than as & g t : and opening quotes as & q u o t ; - all without the spaces of course.)

And yes, funny enough, the closing quotes appear properly, but the less than, greater than, and opening quotes are translated into HTML Named Codes, thereby preventing the HTML block from rendering properly.

### Steps to reproduce

Using a dynamic tag pulled from user meta, use HTML characters "Before" and "After" in the Dynamic Tag Advanced dropdown, and preview. Your raw, uninterpreted HTML will appear, and a look at the Page Source will reveal the HTML Characters converted to HTML Named Codes.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

System Info
Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.3.29 |  
PHP Version: | 7.4.26 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 135M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

Wordpress Environment
Version: | 6.0 |  
-- | -- | --
WP Multisite: | No |  
Max Upload Size: | 128 MB |  
Memory limit: | 40M |  
Max Memory limit: | 512M |  
Permalink Structure: | /blog/%postname%/ |  
Language: | en-US |  
Timezone: | 0 |  
Debug Mode: | Inactive

Theme |   |  
-- | -- | --
Name: | Hello Elementor Child |  
Version: | 1.0.1 |  
Author: | Elementor Team |  
Child Theme: | Yes |  
Parent Theme Name: | Hello Elementor |  
Parent Theme Version: | 2.5.0 |  
Parent Theme Author: | Elementor Team

**Comment by rami-elementor** [comment]
Hi @rouxsean ,

It's not a bug, it's a security measure. It prevents hackers injecting code to dynamic tag controls. We are not going to change this behavior.

You can use the Image widget and set the dynamic tags as the image source.
