### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by extraordinaryvisionsmedia** [elementor/elementor#19002]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My draft pages do not load all of the content that was saved in them when I leave the page and return to edit. When I load the preview all of the content is there, but it does not appear in the editor. 

### Steps to reproduce

I haven't received a bug report, but the content will not properly load when I revisit the draft page to continue editing. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Don't have a system info report.

**Comment by rami-elementor** [comment]
Hi @extraordinaryvisionsmedia ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
