### ISSUE TITLE
🚀 Feature Request: Get device sizes for responsive controls

### ISSUE THREAD

**Issue by mapsmarketing** [elementor/elementor#19021]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

How to retrieve all device sizes for a responsive control within the render function?

https://developers.elementor.com/docs/controls/responsive-control/

### Describe the solution you'd like

Being able to retrieve all device sizes within the render function using `$this->get_settings_for_display();`. Example output for a slider could be something along the lines of:

```
array(
  'sizes' => array(
    'desktop' => 4,
    'tablet' => 2,
    'mobile' => 1
  )
)
```

Other types of controls may need different kinds of output.

**Comment by lotsofchimps** [comment]
Answer me man

**Comment by m1ga** [comment]
sorry? Are you talking to me or the issue author?

**Comment by mapsmarketing** [comment]
> 

This actually works. Where is this in the developer documentation?

**Comment by m1ga** [comment]
I think I only found this randomly or in another issue a while ago.

**Comment by mapsmarketing** [comment]
I thought as much because I couldn't find a thing about it. Thank you mate at least you got me on the right track.

**Comment by rami-elementor** [comment]
Hi @mapsmarketing ,

Elementor has 7 responsive sizes:

* `mobile`
* `mobile_extra`
* `tablet`
* `tablet_extra`
* `laptop`
* `desktop`
* `widescreen`

By default, only `mobile`, `tablet` and `desktop` are active.

Users can turn other sizes from "**Site Settings**" > "**Layout**" > "**Breakpoints**".

Hope this helps.

**Comment by mapsmarketing** [comment]
Hi @rami-elementor 

You didn't understand my question above. This is not related to the breakpoints settings on the site settings. Please look at the link I provided above; it will be a bit clearer.

Thank you
