### ISSUE TITLE
🐞 Bug report: Icon glitch in editor

### ISSUE THREAD

**Issue by lotsofchimps** [elementor/elementor#19031]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I open the editor, the panel on the left shows a very odd tiny group of items/icons. Hoping this is just a backend error for the website. Has anyone ran into this issue?
<img width="286" alt="Screen Shot 2022-06-28 at 9 53 25 AM" src="https://user-images.githubusercontent.com/108359237/176238451-d60e7c64-fc75-4571-9c64-674dbcc3fdbc.png">

### Steps to reproduce

Refreshed the page numerous times, update elementor, same plugins installed a year ago

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - (GPL) v5.7.37
	PHP Version: 7.4.29
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://frontierdoor.com
	Home URL: https://frontierdoor.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: tyler@kinetekmedia.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.6
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.7
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.1.4
		Author: WPDeveloper

	Full Screen Menu for Elementor
		Version: 1.0.5
		Author: wepic

	PDF Forms Filler for CF7
		Version: 2.0.5
		Author: Maximum.Software

	Really Simple SSL
		Version: 5.3.2
		Author: Really Simple Plugins

	Smush
		Version: 3.10.2
		Author: WPMU DEV

	Wp Maximum Upload File Size
		Version: 1.0.9
		Author: CodePopular

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 1
		eael-creative-button : 1
		heading : 1
		image : 1
		social-icons : 1
		text-editor : 2
	header : 1
		eael-creative-button : 1
		full-screen-menu-for-elementor : 1
		image : 2
		nav-menu : 1
	wp-page : 24
		call-to-action : 5
		divider : 1
		eael-creative-button : 32
		form : 12
		gallery : 8
		heading : 191
		icon-box : 29
		image : 22
		spacer : 1
		text-editor : 215
		video : 4

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 392022-05-17 15:28:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-17 15:28:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-17 15:28:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-17 15:48:14 [info] elementor-pro::elementor_pro_updater Started 
2022-05-17 15:48:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-17 15:48:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-17 15:48:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-05-17 15:48:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.1',
)]
2022-06-20 16:48:11 [info] elementor::elementor_updater Started 
2022-06-20 16:48:11 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-20 16:48:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-20 16:48:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-20 16:48:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-20 16:48:16 [info] elementor-pro::elementor_pro_updater Started 
2022-06-20 16:48:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-20 16:48:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-20 16:48:16 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-20 16:48:16 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-20 16:48:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-06-20 16:48:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

PHP: showing 2 of 2PHP: 2022-04-01 16:50:50 [warning X 16][/home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/modules/payments/classes/payment-button.php::16] Declaration of ElementorPro\Modules\Payments\Classes\Payment_Button::render_button($tag = 'a') should be compatible with Elementor\Widget_Button::render_button(?Elementor\Widget_Base $instance = NULL) [array (
  'trace' => '
#0: /home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/modules/payments/classes/payment-button.php(16): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/plugin.php(141): class type include()array (
  0 => '/home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/modules/payments/classes/payment-button.php',
)
#2: ElementorPro\Plugin -> autoload()
#3: /home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/modules/payments/widgets/paypal-button.php(13): class type spl_autoload_call()
#4: /home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/plugin.php(141): class type include()array (
  0 => '/home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor-pro/modules/payments/widgets/paypal-button.php',
)
',
)]
PHP: 2022-04-05 22:30:26 [notice X 2][/home/kineteksandbox/frontier.kineteksandbox.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-06-20 19:34:27 [error X 2][https://frontierdoor.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible
	Full Screen Menu for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible
	Full Screen Menu for Elementor: Incompatible

**Comment by lotsofchimps** [comment]
bum

**Comment by lotsofchimps** [comment]
*bump lol

**Comment by theslimbrady** [comment]
some1 halp this guy

**Comment by 79ho3ein** [comment]
This bug could be due to other plugins you have installed. Because I do not have this problem with the latest elementor versions.

**Comment by shilo-ey** [comment]
Please hard reload and clear the cache on your browser (CMD+SHIFT+R)
This should fix the icons issue.
