### ISSUE TITLE
🐞 Bug report: Call to Action widget. Title spacing slider not working

### ISSUE THREAD

**Issue by catchlightWeb** [elementor/elementor#19032]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use the Title spacing slider to create vertical spacing between the title of the description, there is no change in the spacing. The slider isn't doing anything at the moment. 

### Steps to reproduce

Drag the Call to Action widget onto the page. Click on the Style tab and open the Content section. Using the Title Spacing slider makes no change to the spacing. Description Spacing slider below is working fine.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://restorative-justice.local
	Home URL: http://restorative-justice.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 13
	Admin Email: brock@catchlight.co.nz
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	ClientPlugin
		Version: 1.0.0
		Author: Brockdin Barr

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Gravity Forms
		Version: 2.5.16
		Author: Gravity Forms

	Post Types Order
		Version: 1.9.9
		Author: Nsp Code

	Premium Starter Templates
		Version: 3.1.11
		Author: Brainstorm Force

	Ultimate Addons for Elementor
		Version: 1.36.7
		Author: Brainstorm Force

== Elements Usage ==
	
	footer : 2
		container : 3
		nav-menu : 1
		template : 1
		text-editor : 3
	header : 1
		button : 3
		container : 2
		nav-menu : 1
		theme-site-logo : 1
	page : 1
		call-to-action : 1
		container : 1
	section : 1
		call-to-action : 1
		container : 2
	wp-page : 5
		blockquote : 1
		button : 1
		call-to-action : 6
		container : 21
		heading : 19
		image : 1
		text-editor : 13

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 262022-05-04 12:20:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-04 12:20:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.5',
)]
2022-05-04 12:20:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.5',
)]
2022-05-04 12:33:07 [info] elementor-pro::elementor_pro_updater Started 
2022-05-04 12:33:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-04 12:33:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-04 12:33:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-05-04 12:33:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.2',
  'to' => '3.6.5',
)]
2022-06-27 14:22:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-27 14:22:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-06-27 14:22:10 [info] elementor::elementor_updater Started 
2022-06-27 14:22:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-27 14:22:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-27 14:22:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-27 14:22:10 [info] elementor-pro::elementor_pro_updater Started 
2022-06-27 14:22:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-27 14:22:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-27 14:22:10 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-27 14:22:10 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-27 14:22:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]

PHP: showing 13 of 13PHP: 2022-05-04 12:26:13 [notice X 63][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 1][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 1][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 1][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 1][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 2][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/ultimate-elementor/modules/query-post/module.php(69): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 2][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/ultimate-elementor/modules/control-query/module.php(315): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:28:12 [notice X 2][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/ultimate-elementor/modules/presets-select/module.php(102): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-04 12:35:21 [notice X 3][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The Plugin::$instance->posts_css_manager argument is deprecated since version 2.7.0! Use Plugin::$instance->files_manager instead. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-27 14:23:43 [notice X 6][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-28 15:41:24 [notice X 5][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-28 16:16:25 [error X 1][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(33, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->ha [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-29 16:20:26 [notice X 1][/Users/brockdinbarr/Local Sites/restorative-justice/app/public/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2022-06-27 05:57:47 [error X 1][http://restorative-justice.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:605818] elementorFrontend is not defined 
JS: 2022-06-28 23:51:01 [error X 29][http://restorative-justice.local/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:13282] r.get is not a function 
JS: 2022-06-28 23:51:40 [error X 25][http://restorative-justice.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:362278] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-06-29 00:25:59 [error X 15][http://restorative-justice.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:391230] Cannot read properties of undefined (reading \'parent\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ultimate Addons for Elementor: Compatible

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
