### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by TDLTR** [elementor/elementor#19038]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello I'm not able to activate in worpress my Elementor pro add on. It give me an eror in wordpres and a fatal error on my website. Here what wordpress keep seending me ( i put screeshots with this contact form). The same thing happen when activating multi widget addon and elementor pro together in wordpress in recovery mode. Thanks for the help.

### Steps to reproduce

Activate multi-widget Add-on
Then activate elementor pro.
Then the conflic appen
![Error elementor pro and multi widget addon when trying to activating in recovery](https://user-images.githubusercontent.com/108417784/176474374-b1465087-0d84-4975-a72b-f698d712f251.jpg)
![Error for elementor](https://user-images.githubusercontent.com/108417784/176474381-70618bef-6237-4509-b298-06900509bec0.jpg)
![Error in wordpress Elementor pro](https://user-images.githubusercontent.com/108417784/176474383-0121e290-9446-4fa2-8d67-d4b1f20cadb8.jpg)
![Error Multi-Widget addon](https://user-images.githubusercontent.com/108417784/176474388-5cfd5797-a3b1-4d64-8cef-1b4526ec9308.jpg)
.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://tdltr.ca
	Home URL: https://tdltr.ca
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: 0
	Admin Email: admin@tdltr.ca
	Debug Mode: Inactive

== Theme ==
	Name: Finance Accounting Pro
	Version: 1.1.8
	Author: Themeseye
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0

== Active Plugins ==
	Contact Form 7
		Version: 5.6
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Finance Accounting Pro Posttype
		Version: 1.1
		Author: Themeseye

	Font Awesome
		Version: 4.2.0
		Author: Font Awesome

	Multi-Widget Addon
		Version: 1.0
		Author: Vowelweb

	WooCommerce
		Version: 6.6.1
		Author: Automattic

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut

== Journal ==
	
JS: showing 1 of 1JS: 2022-06-28 15:52:21 [error X 4][https://tdltr.ca/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `button_url` value. Expected array or object.',
)]

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @TDLTR ,

You should contact the "**Activate multi-widget Add-on**" developers.

I looks like their addon is breaking Elementor Pro.
