### ISSUE TITLE
✅ 🐞 Bug report: 404 on Dev Edition Blog Post Changelog Link

### ISSUE THREAD

**Issue by loucasl** [elementor/elementor#19030]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Just wanted to let the Elementor team know that there is a broken link on the Developer Edition blog post that takes you to a 404 github page rather than the changelog

![72898933-35B8-4E2B-AF92-C7455DACF701](https://user-images.githubusercontent.com/35241778/176232522-a10f4f13-01c4-4e72-b90f-0e11d27fee22.jpeg)

https://elementor.com/blog/introducing-beta-developer-edition

### Steps to reproduce

Visit the blog post link above and scroll to the last paragraph, then click the “release notes” link

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

N/A

**Comment by nicholaszein** [comment]
Hi @loucasl. Apologies for the delay in answering your issue. 🙏 

Thank you for sharing your findings. I'll pass this along to the team responsible for the Elementor Blog.

Please, in the future, use GitHub issues only to report Bugs in the Elementor Plugin code.

Kind regards
