### ISSUE TITLE
Feature request: Vimeo as a video background 

### ISSUE THREAD

**Issue by upekshapriya** [elementor/elementor#1903]
Be good to have Vimeo as an option for a video background as well as YouTube and MP4 file. See https://codepen.io/mattgrosswork/pen/jrdwK

**Comment by HammerOz** [comment]
I thought I would try and use the vimeo source mp4 file link that you have access to as a pro user. The video is actually visible while editing, yet fails when viewing the live page. Any ideas? 

example file link:

 https://player.vimeo.com/external/226866110.hd.mp4?s=4c4c1ed74fbd38d861c83bff708ed17167957252&profile_id=174

**Comment by i2g-lweiss** [comment]
It seems the Vimeo link generates a request for a token for access when selecting "use with your own player" (Settings/Video file in Vimeo).  If you paste that link into your browser it changes to one with a token.  You can use this generated link in elementor and it works everywhere but the token expires the next day.

**Comment by bainternet** [comment]
Currently, Vimeo allows removing controls and background embeds just for a Plus, PRO, or Business member.

**Comment by i2g-lweiss** [comment]
We are a pro member, have not found this option.  We are using the direct links to "use with your own player".  It's not about removing the controls, we just want to use a vimeo video link as a background.

**Comment by HammerOz** [comment]
It's all a bit so so. I'm self hosting now

**Comment by zimventures** [comment]
Throwing my +1 in as a feature request.

**Comment by dasignlady** [comment]
I would also like to see this feature added. Gotta upload same video to youtube just to use it as background, when I can use vimeo in video widget?

**Comment by mskks64** [comment]
"YouTube link or video file (mp4 is recommended)."

Mp4 from vimeo does not work.

**Comment by dasignlady** [comment]
So, I just purchased a subscription to Publit.io and uploaded the section background video from there instead. It seems to be faster than the other services so I am happy with that. NOW, I need the option of using _that same source_ for my standalone videos but I can only choose from Vimeo, YT, Daily Motion or self-hosted. (The latter is not an option!) I do not understand why there is such a disparity between what sources we are able to use for one or the other? If adding a custom link works for background video, please add same option for the video widget. OR, make it so background video works on mobile as well, eliminating the need for a mobile-only separate video. Thanks in Advance!

**Comment by danishiqbal4** [comment]
+1 for this feature

**Comment by Deralict** [comment]
+1 for me too. Vimeo is such better quality so is more suitable for a background than YouTube.

**Comment by Matherone** [comment]
+1.

Vimeo uses gentler compression (up to about twice the bitrate). Hence the **Vimeo video quality is superior** to Youtube's when playing the same original upload. When using a third-party service primarily as a content delivery network service for video to be viewed your website, Vimeo is better. And this is exactly what Elementor videos are for.

Also, since the Vimeo's video window design is more restrained, it **looks better visually**.

For designers looking for a third-party video hosting platform, Vimeo is often the better choice.

In all places where Elementor allows for videos - **please add Vimeo**.

**Comment by dcollis** [comment]
With youtube deprecating showinfo=0 since 25th Sept this year (https://developers.google.com/youtube/player_parameters#showinfo), this has become more important as a youtube video can't effectively be used as a background video anymore, as it will always show title etc.

**Comment by krb5225** [comment]
+1 for this feature.

Vimeo doesn't work as video background and Youtube shows title, etc. Does anyone know of a solution?!

**Comment by Simon-J-N-Reading** [comment]
+1 It is infuriating to build a site around a customer who specifically pays to use Vimeo Pro - only to find that we cannot use the same source for the site's video backgrounds - it is not joined up thinking.

**Comment by i2g-lweiss** [comment]
In the meantime here's a workaround that also works on mobile.  You can use it in a text element but you may need to play around to get it position correctly behind your content.

Get your vimeo link from video/distribution/Video file links

`<video style="min-width: 100%; min-height: 100%; width: auto; height: auto; top: 50%; z-index: -1; left: 50%; position: absolute; transform: translate(-50%, -50%);" autoplay="autoplay" loop="loop" muted=""><source src="https://player.vimeo.com/external/xxxxxx.hd.mp4?s=xxxxxxxxxxxxxxxxxxxxxxxxxxx&profile_id=xxx"></video>`

**Comment by dasignlady** [comment]
I noticed a change in the branding on YT videos in Elementor lately. It seems to ignore the settings and subsequently garbaged up with my account logo and something in each corner. I looked at it on a client's monitor and was shocked. Moving everything to a private server. Just disgusting.

**Comment by mskks64** [comment]
This is still an issue that needs to be addressed.  Youtube videos aren't cutting it due to delay and showing title/shadow.

**Comment by plasticboxuk** [comment]
This is a real oversight guys.

Vimeo is the 'pro' method of hosting videos, and means a video background can be achieved without the YouTube branding coming up.

I'd suggest this is urgent.  

Vimeo as a background video has been supported as standard by the other page builders for years.

**Comment by swamiofsuccess** [comment]
I'm real confused, since I see this listed in the integrations section:
![image](https://user-images.githubusercontent.com/48006889/53392458-0c25f000-395f-11e9-89ca-fbe5f43bff55.png)


Specifically says, "Add Vimeo videos and background videos anywhere." At least I found this thread, so I know I am not the only one struggling with this.

**Comment by Simon-J-N-Reading** [comment]
> 
> 
> I'm real confused, since I see this listed in the integrations section:
> ![image](https://user-images.githubusercontent.com/48006889/53392458-0c25f000-395f-11e9-89ca-fbe5f43bff55.png)
> 
> Specifically says, "Add Vimeo videos and background videos anywhere." At least I found this thread, so I know I am not the only one struggling with this.

Dig a little deeper & all will be revealed ;-)

**Comment by mskks64** [comment]
Still an issue. Not sure the oversight on this.

**Comment by cgrobin** [comment]
+1 on this feature!! 
**Section Background Video Options should INCLUDE Vimeo** or at least provide an explanation on why it's not a viable option. Please...please...please...please.... your customers are confused about this not being addressed.

**Comment by thephilm** [comment]
+1 - Would love to have an option for "Pro" users to also remove the play button as part of the integration. It's simply adding a "background=1" to the parameters. This is a game changer especially if it can be loaded properly and lightweight.

**Comment by BobIMG** [comment]
+1 - We're a new Elementor Pro user and just discovered this feature wasn't available. We too would really like to be able to use Vimeo Pro as background video.

**Comment by seanivek** [comment]
+1 - We really need to be able to embed Vimeo video as well.

**Comment by mskks64** [comment]
> +1 - We really need to be able to embed Vimeo video as well.

Vimeo embed is definitely possible. Use the video module or just paste the embed code.

**Comment by cgrobin** [comment]
Video embed is not possible in section background scenario.

**Comment by BobIMG** [comment]
I'm amazed that this feature is so blatantly overlooked, especially given that as of September last year YouTube mandates their branding overlays. For others that need a workaround until the Elementor Team prioritizes this necessary feature ....

Create an Elementor HTML container. Within that container, add (insert your video ID):

`<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/XXXXXXXXXX?background=1' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>`

Set the margins on the HTML Container to -10 all the way around.

Also, make sure the Section is set to Stretch and Full Width for the content.

This will provide a responsive autoplay background video w/o sound and w/o vimeo player overlays. This will likely only work for Plus and Pro accounts.

**Comment by mskks64** [comment]
Any update on this being integrated?

**Comment by extrapros** [comment]
+1 from me here.  We could really use this feature.  Please add Vimeo to the background video options in Elementor!

**Comment by ianstudio** [comment]
..meanwhile, in June 2019..

**Comment by mskks64** [comment]
Two years later... Still waiting

**Comment by dcambria** [comment]
++1 for this feature

**Comment by Karenskeens** [comment]
After serious research on video solutions for Elementor, I just now stumble on this thread? Ya, I agree with everything you guys are saving. Hello, Elementor? Add Vimeo as a background video feature to Elementor? Are you negotiating a partner price from Vimeo? Do we need to reach out to Vimeo?

**Comment by webfocusdesign** [comment]
+1 from me as well.

I'm absolutely stunned that this is still not implemented. Video backgrounds from Vimeo are a must for most serious businesses. We also have a client for a new project that have a Pro level Vimeo account and they'll be pissed when I tell them we need to copy their videos to YoutTube for them to work as video backgrounds in Elementor... or go back to Beaver Builder which I  DO NOT want to have to do...

This needs to happen now!

**Comment by JumaDM** [comment]
I'm stunned too! between this and the responsive breakpoint limitations, these two basic and essential features are being blindsided for some reason!

**Comment by mark4TPI** [comment]
+1 from me as well.

**Comment by mskks64** [comment]
> +1 from me as well.

It's in Beta 2.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.7

Feel free to update

Thanks!

**Comment by Matherone** [comment]
Thank you.

**Comment by mark4TPI** [comment]
am I the only one getting like 10 seconds of black before I see my video. I have a fallback image in there too.

**Comment by artoflifefilms** [comment]
This doesn't appear to be fixed.. I'm still stuck using YouTube for videos. Vimeo links result in nothing showing.

**Comment by artoflifefilms** [comment]
I wish.

I only get a video showing if I put a YouTube link. If I put a Vimeo link I just see the Background fallback image. 

I don’t understand from what you say I need to do for the background fallback? I have an image set there.

I don’t see anything at all with a Vimeo link.

**Comment by Karenskeens** [comment]
Sorry to hear that –
  I had no problems inserting a vimeo link to play as a background, but maybe it’s because I’m using Astra with Elementor Pro?

**Comment by barttermorshuizen** [comment]
https://github.com/elementor/elementor/pull/6326 seems to work fine. why wasn't this integrated in the code base?
