### ISSUE TITLE
🐞 Bug report: Horizontal scrollbar in mobile & tablet responsive mode

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19049]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi elementor team !

In the editor, if you are in tablet or mobile mode, a [horizontal scroll bar](https://prnt.sc/-S8M0VSdtU17) appears in the editor for no particular reason.
In fact, this horizontal scrolling bar only appears in the editor in tablet and mobile mode. If the editor is in desktop mode, there is no scroll bar.

### Steps to reproduce

1- In elementor editor, enable responsive mode. The default will be the desktop : https://prnt.sc/oi1oM4OE6oCI
2- Following the previous step, there is no horizontal scroll bar in the editor : https://prnt.sc/OYame2GmUwMY
3- Now enter tablet or mobile mode. This horizontal scroll bar appears : https://prnt.sc/px16nWDLW09U  This horizontal scroll bar is even available in mobile mode

**I experience this bug in Windows, Chrome browser.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by hitsgee** [comment]
I have spotted this bug as well

**Comment by 79ho3ein** [comment]
fixed in 3.7.2 , thank you @shilo-ey

**Comment by shilo-ey** [comment]
Hey friends, thank you for reporting.

This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!
