### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by kristeenagrover** [elementor/elementor#19051]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have downloded latest version of elementor to my site at wordpress and getting the fatal error as below

https://tejasvani.com/

Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/naturally-elementor-addons/widgets/naturally-button.php:316 Stack trace: #0 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Naturally_Button_Widget->_register_controls() #1 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls() #2 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack() #3 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack() #4 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2369): Elementor\Controls_Stack->get_contro in /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/naturally-elementor-addons/widgets/naturally-button.php on line 316
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

### Steps to reproduce

the previous version works fine

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/naturally-elementor-addons/widgets/naturally-button.php:316 Stack trace: #0 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Naturally_Button_Widget->_register_controls() #1 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls() #2 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack() #3 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack() #4 /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2369): Elementor\Controls_Stack->get_contro in /home/u728819151/domains/tejasvani.com/public_html/wp-content/plugins/naturally-elementor-addons/widgets/naturally-button.php on line 316
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

**Comment by rami-elementor** [comment]
Hi @kristeenagrover,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by rami-elementor** [comment]
To solve your issue, deactivate the "**naturally-elementor-addons**" plugin.

From the error message I understand that they are using deprecated Elementor methods.
