### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by lanablha** [elementor/elementor#19054]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to enter the kit library section but I cannot get in

### Steps to reproduce

When I try to enter the kit library section but I cannot log in , I get this message from my browser: "Hmm... can't reach this page " ''The connection was reset".
I need your assistance. Any help???

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | WINNT |  
Software: | Apache |  
MySQL version: | mariadb.org binary distribution v10.4.25 |  
PHP Version: | 8.0.20 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 40M |  
GD Installed: | No |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>Server Environment		
Operating System:	WINNT	
Software:	Apache	
MySQL version:	mariadb.org binary distribution v10.4.25	
PHP Version:	8.0.20	
PHP Memory Limit:	512M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	40M	
GD Installed:	No	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.0	
Site URL:	http://localhost/wordpress	
Home URL:	http://localhost/wordpress	
WP Multisite:	No	
Max Upload Size:	40 MB	
Memory limit:	256M	
Max Memory limit:	512M	
Permalink Structure:	/%year%/%monthnum%/%day%/%postname%/	
Language:	en-US	
Timezone:	0	
Admin Email:	belhaousasmaa@gmail.com	
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	2.5.0	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37	
Active Plugins		
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.7.0-dev10	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)	
[Elementor Header & Footer Builder](https://github.com/Nikschavan/header-footer-elementor) - 1.6.11	By [Brainstorm Force, Nikhil Chavan](https://www.brainstormforce.com/)	
Envato Elements - 2.0.11	By [Envato](https://elements.envato.com/extensions/wordpress/?utm_source=extensions&utm_medium=referral&utm_campaign=elements_extensions_wpplugins)	
[Jeg Elementor Kit](http://jegtheme.com/) - 2.4.3	By [Jegstudio](http://jegtheme.com/)	
[MetForm](http://products.wpmet.com/metform/) - 2.2.0	By [Wpmet](https://wpmet.com/)	
[WP File Manager](https://wordpress.org/plugins/wp-file-manager) - 7.1.5	By [mndpsingh287](https://profiles.wordpress.org/mndpsingh287)	
Elementor Experiments		
Optimized DOM Output: 	Active by default
Improved Asset Loading: 	Active by default
Improved CSS Loading: 	Active by default
Inline Font Icons: 	Inactive by default
Accessibility Improvements: 	Active by default
Import Export Template Kit: 	Active
Additional Custom Breakpoints: 	Active by default
Hide native WordPress widgets from search results: 	Active by default
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Inactive by default
Hello Theme Header & Footer: 	Active by default
Landing Pages: 	Active by default
Color Sampler: 	Active by default
Favorite Widgets: 	Active by default
Admin Top Bar: 	Active by default
Log[Clear Log](http://localhost/wordpress/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=9a51200c72#elementor-clear-log)		
PHP: showing 1 of 1
PHP: 2022-06-30 21:15:22 [warning X 4][C:\Bitnami\wordpress-6.0-0\apps\wordpress\htdocs\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
Log: showing 7 of 7
2022-07-01 09:02:55 [info] elementor::elementor_updater Started 
2022-07-01 09:02:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-01 09:02:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-01 09:02:55 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-07-01 09:02:55 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-07-01 09:02:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0-dev10',
)]
2022-07-01 09:02:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.0-dev10',
)]
Elementor - Compatibility Tag		
 Elementor Header & Footer Builder 	 Incompatible 
 Envato Elements 	 Incompatible 
 Jeg Elementor Kit 	 Incompatible

**Comment by rami-elementor** [comment]
Hi @lanablha ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
