### ISSUE TITLE
🐞 Bug report: Replace URL does not replace Custom Font URLS

### ISSUE THREAD

**Issue by mattpramschufer** [elementor/elementor#19060]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The replace URL function does not replace URLs of Custom Fonts.

### Steps to reproduce

If you have custom fonts added to Admin->Elementor->Custom Fonts, and you then use Admin->Elementor->Replace URL, the replace URL function does not replace the URLs in Custom Fonts

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.12
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://www.bookpage.com
	Home URL: https://www.bookpage.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: services@southernmade.co
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 5.5.3
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 2.6.4
		Author: AdminColumns.com

	Advanced Custom Fields PRO
		Version: 5.10.2
		Author: Delicious Brains

	Advanced Post Queries
		Version: 1.0.15
		Author: Shabti Kaplan

	BookPages (PX)
		Version: 1.0
		Author: PixelDesign

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Code Snippets
		Version: 3.1.1
		Author: Code Snippets Pro

	Cron Jobs
		Version: 1.2.9
		Author: Ariel

	Disable Comments
		Version: 2.3.6
		Author: WPDeveloper

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.6.3
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.1.6
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.1.0
		Author: Dudaster.com

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	FluentSMTP
		Version: 2.1.1
		Author: FluentSMTP & WPManageNinja Team

	GA Google Analytics
		Version: 20220517
		Author: Jeff Starr

	GP Advanced Calculations
		Version: 1.0.3
		Author: Gravity Wiz

	Gravity Forms
		Version: 2.6.3
		Author: Gravity Forms

	Gravity Forms Emma Add-On
		Version: 1.5
		Author: Gravity Forms

	Gravity Perks
		Version: 2.2.7
		Author: Gravity Wiz

	Hide from Search
		Version: 1.1.3
		Author: Micah Wood

	Highlight Search Terms
		Version: 1.8.2
		Author: RavanH

	JetEngine
		Version: 2.9.3
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.2
		Author: Crocoblock

	Post View Count
		Version: 1.6.1
		Author: Naresh Parmar

	Pretty Links Developer Edition
		Version: 3.2.4
		Author: Pretty Links

	Public Post Preview
		Version: 2.9.3
		Author: Dominik Schilling

	Public Post Preview Configurator
		Version: 1.0.3
		Author: Björn Weinbrenner

	Redirection
		Version: 5.2.3
		Author: John Godley

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.3
		Author: TinyPNG

	Ultimate Addons for Elementor
		Version: 1.36.7
		Author: Brainstorm Force

	User Role Editor Pro
		Version: 4.60.1
		Author: Vladimir Garagulia

	User Switching
		Version: 1.6.0
		Author: John Blackbourn & contributors

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP Admin Pages PRO
		Version: 1.8.4
		Author: Arindo Duque - NextPress

	WP All Export Pro
		Version: 1.7.0
		Author: Soflyy

	WP All Import - ACF Add-On
		Version: 3.3.6
		Author: Soflyy

	WP All Import - User Import Add-On Pro
		Version: 1.1.6
		Author: Soflyy

	WP All Import Pro
		Version: 4.6.9
		Author: Soflyy

	WP Extended Search
		Version: 2.1.1
		Author: 5um17

	WP Migrate
		Version: 2.3.3
		Author: Delicious Brains

	WP Offload Media
		Version: 2.5.5
		Author: Delicious Brains

	WP Rocket
		Version: 3.11.3
		Author: WP Media

	Yoast SEO
		Version: 19.2
		Author: Team Yoast

== Must-Use Plugins ==
	WP Migrate DB Pro Compatibility
		Version: 1.2
		Author: Delicious Brains

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active
	Scroll Snap: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by isidorosrigas** [comment]
+1

**Comment by LoganStrike** [comment]
@arielk The replace URL tool also does not replace Section background image URLs when the image is set as a Fallback for a dynamic tag. I confirmed this bug still remains in Elementor 3.8.0.

**Comment by psaintjust** [comment]
The buggy code is in Elementor Pro.
File: elementor-pro/modules/assets-manager/asset-types/fonts/custom-fonts.php
Method: replace_urls()

Since there's no public repo, I can't provide a pull request.  Please find a working implementation below (verified on Elementor 3.9.2):

private function replace_urls( $rows_affected, $from, $to ) {
	$rows_affected = 0;

	$fonts = new \WP_Query( [
		'post_type' => Fonts_Manager::CPT,
		'posts_per_page' => -1,
	] );
	foreach ( $fonts->posts as $font ) {
		$saved = get_post_meta( $font->ID, self::FONT_META_KEY, true );
		if ( ! is_array( $saved ) ) {
			continue;
		}

		$row_updated = false;
		foreach ( $saved as &$font_data ) {
			foreach ( $this->get_file_types() as $type => $mime ) {
				if ( ! isset($font_data[$type]) || ! isset($font_data[$type]['url']) ) {
					continue;
				}
				$rows = 0;
				$font_data[$type]['url'] = str_replace( $from, $to, $font_data[$type]['url'], $rows );
				$row_updated = $row_updated || ($rows > 0);
			}
		}
		$rows_affected += (int) $row_updated;

		$this->save_meta( $font->ID, array('font_face' => $saved) );
	}

	return $rows_affected;
}

**Comment by psaintjust** [comment]
hi @nicholaszein @arielk is there a process to submit fixes for Elementor Pro?

**Comment by arielk** [comment]
Hi @psaintjust,

The best way to change a URL in this area is to work with the official [WordPress search & replace](https://developer.wordpress.org/cli/commands/search-replace/) instead of this hack. 

You can use in many WordPress plugins to do that. Our tool relevant only for the Elementor post content.

Thanks
