### ISSUE TITLE
🚀 Feature Request: login widget - on mistypedon't redirect me to wordpress login screen

### ISSUE THREAD

**Issue by yaron86** [elementor/elementor#19095]
### Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

i made a custom login page, and on the login form if i mistype it redirect me to the wp login screen:  https://prnt.sc/pXQcWWVR9Bfl
instead of showing me this screen, just write a message below the form that the username\password are wrong... what's the point of redirecting me to wp-login? now i lost all my branding and i need to find another plugin... 

### Describe the solution you'd like

showing me a message below the form

**Comment by rami-elementor** [comment]
Hi @yaron86 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
