### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by NGOLZR** [elementor/elementor#19097]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I activate Elementor, I keep getting an error that says This page can't be reached || the connection was reset which includes ERR_CONNECTION_RESET.
I have tried increasing the memory limit, Enabling Loader method in the Advanced Elementor settings, uninstalling and reinstalling Elementor but nothing seems to work

### Steps to reproduce

Install elementor
Activate Elementor 
Connection reset error

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.25
	PHP Version: 8.0.20
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://127.0.0.1/wordpress
	Home URL: http://127.0.0.1/wordpress
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: nigelogott@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44

== Active Plugins ==
	Elementor
		Version: 3.7.0-dev10
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Hello Theme Header & Footer: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
PHP: showing 1 of 1PHP: 2022-07-06 12:10:01 [warning X 3][C:\Bitnami\wordpress-6.0-0\apps\wordpress\htdocs\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 7 of 72022-07-06 12:17:09 [info] elementor::elementor_updater Started 
2022-07-06 12:17:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-06 12:17:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-06 12:17:09 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-07-06 12:17:09 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-07-06 12:17:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0-dev10',
)]
2022-07-06 12:17:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0-dev10',
)]

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @NGOLZR ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
