### ISSUE TITLE
Condition not working in repeater field

### ISSUE THREAD

**Issue by afgupload** [elementor/elementor#19099]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

Hello All,

**I want use condition in repeater field, please see the code:**

```
        $this->start_controls_section(
            'slider_layouts',
            [
                'label' => esc_html__( 'Slider Layout', 'plugin-name' ),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );

        $this->add_control(
            'slider_layout',
            [
                'label' => esc_html__( 'Select Slider Layout', 'plugin-name' ),
                'type' => \Elementor\Controls_Manager::SELECT,
                'default' => 'design_01',
                'options' => [
                    'design_01'  => esc_html__( 'Design 01 - Image and Text', 'plugin-name' ),
                    'design_02'  => esc_html__( 'Design 02 - Image and Text', 'plugin-name' ),
                    'design_03'  => esc_html__( 'Design 03 - Only Image', 'plugin-name' ),

                ],
            ]
        );

        $this->end_controls_section();
```

**I want to display the title in repeater filed based on above selector, please see the repeater filed:**

        $this->start_controls_section(
            'main_slider',
            [
                'label' => esc_html__('Add and Remove Slider', 'plugin-name'),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );

        $repeater = new \Elementor\Repeater();

          //Title
        $repeater->add_control(
            'slider_title',
            [
                'label' => esc_html__('Title', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXTAREA,
                'rows' => 3,
                'default' => esc_html__('Slider title', 'plugin-name'),
                'placeholder' => esc_html__('Type your title here', 'plugin-name'),
                '**condition**' => [
                                          'slider_layout' => 'design_01',
                ],
            ]
        );

But this is not working. I have checked all same issue but there was no solution.

So please help me.

Thanks

### Steps to reproduce

```
<?php

class Slider_Widget extends \Elementor\Widget_Base
{


    public function get_name()
    {
        return 'theme_slider';
    }

    public function get_title()
    {
        return esc_html__('Slider', 'elementor-addon');
    }

    public function get_icon()
    {
        return 'dashicons dashicons-slides';
    }

    public function get_categories()
    {
        return ['theme'];
    }


    public function get_keywords()
    {
        return ['Posts', 'Articles'];
    }

    protected function register_controls()
    {
        $this->start_controls_section(
            'slider_layouts',
            [
                'label' => esc_html__( 'Slider Layout', 'plugin-name' ),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );

        $this->add_control(
            'slider_layout',
            [
                'label' => esc_html__( 'Select Slider Layout', 'plugin-name' ),
                'type' => \Elementor\Controls_Manager::SELECT,
                'default' => 'design_01',
                'options' => [
                    'design_01'  => esc_html__( 'Design 01 - Image and Text', 'plugin-name' ),
                    'design_02'  => esc_html__( 'Design 02 - Image and Text', 'plugin-name' ),
                    'design_03'  => esc_html__( 'Design 03 - Only Image', 'plugin-name' ),

                ],
            ]
        );

        $this->end_controls_section();

        // Add or Remove Slider

        // Title and Description
        $this->start_controls_section(
            'main_slider',
            [
                'label' => esc_html__('Add and Remove Slider', 'plugin-name'),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );


        $repeater = new \Elementor\Repeater();

        //Choose Image
        $repeater->add_control(
            'slider_image',
            [
                'label' => esc_html__('Choose Image', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::MEDIA,
            ]
        );

        // Slider Content Align
        $repeater->add_control(
            'slider_content_align',
            [
                'label' => esc_html__('Content Align', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::SELECT,
                'default' => 'text-center',
                'options' => [
                    'text-left' => esc_html__('Left', 'plugin-name'),
                    'text-right' => esc_html__('Right', 'plugin-name'),
                    'text-center' => esc_html__('Center', 'plugin-name'),
                ],
            ]
        );

        //Title
        $repeater->add_control(
            'slider_title',
            [
                'label' => esc_html__('Title', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXTAREA,
                'rows' => 3,
                'default' => esc_html__('Slider title', 'plugin-name'),
                'placeholder' => esc_html__('Type your title here', 'plugin-name'),
            ]
        );

        //Subtitle
        $repeater->add_control(
            'slider_subtitle',
            [
                'label' => esc_html__('Subtitle', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXTAREA,
                'rows' => 3,
                'default' => esc_html__('Slider subtitle', 'plugin-name'),
                'placeholder' => esc_html__('Type your subtitle here', 'plugin-name'),
            ]
        );

        //Description
        $repeater->add_control(
            'slider_description',
            [
                'label' => esc_html__('Description', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXTAREA,
                'rows' => 5,
                'default' => esc_html__('Slider description', 'plugin-name'),
                'placeholder' => esc_html__('Type your description here', 'plugin-name'),
            ]
        );

        //Button 01
        $repeater->add_control(
            'slider_btn1',
            [
                'label' => esc_html__('Button 01', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXT,
                'default' => esc_html__('Read more', 'plugin-name'),
                'placeholder' => esc_html__('Button text here', 'plugin-name'),
            ]
        );

        // Button 01 URL
        $repeater->add_control(
            'btn1_link',
            [
                'label' => esc_html__('Button 01 URL', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::URL,
                'placeholder' => esc_html__('https://your-link.com', 'plugin-name'),
                'default' => [
                    'url' => '',
                    'is_external' => true,
                    'nofollow' => true,
                    'custom_attributes' => '',
                ],
                'label_block' => true,
            ]
        );

        //Button 02
        $repeater->add_control(
            'slider_btn2',
            [
                'label' => esc_html__('Button 02', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::TEXT,
                'default' => esc_html__('Read more 02', 'plugin-name'),
                'placeholder' => esc_html__('Button text here', 'plugin-name'),
            ]
        );

        //Button 02 URL
        $repeater->add_control(
            'btn2_link',
            [
                'label' => esc_html__('Button 02 URL', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::URL,
                'placeholder' => esc_html__('https://your-link.com', 'plugin-name'),
                'default' => [
                    'url' => '',
                    'is_external' => true,
                    'nofollow' => true,
                    'custom_attributes' => '',
                ],
                'label_block' => true,
            ]
        );


        // Repeater List
        $this->add_control(
            'main_slider_items',
            [
                'label' => esc_html__('Repeater List', 'plugin-name'),
                'type' => \Elementor\Controls_Manager::REPEATER,
                'fields' => $repeater->get_controls(),
                'default' => [
                    [
                        'slider_image' => esc_html__('Slider Item', 'plugin-name'),
                        'slider_content_align' => esc_html__('Slider Content Align', 'plugin-name'),
                        'slider_title' => esc_html__('Slider Title', 'plugin-name'),
                        'slider_subtitle' => esc_html__('Slider Title', 'plugin-name'),
                        'slider_description' => esc_html__('Slider Description', 'plugin-name'),
                        'slider_btn1' => esc_html__('Slider Button 01', 'plugin-name'),
                        'btn1_link' => esc_html__('Slider Button 01 Link', 'plugin-name'),
                        'slider_btn2' => esc_html__('Slider Button 02', 'plugin-name'),
                        'btn2_link' => esc_html__('Slider Button 02 Link', 'plugin-name'),
                    ],
                ],
                'title_field' => '{{{ slider_title }}}',
            ]
        );


        $this->end_controls_section();
        // Add or Remove Slider End of Section


        // Slider Control
        $this->start_controls_section(
            'slider_control',
            [
                'label' => esc_html__('Slider Control', 'plugin-name'),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );


        $this->add_control(
            'carousel_speed',
            [
                'label' => esc_html__('Slides Speed', 'plugin-name'),
                'description' => 'Select the slide switch speed.',
                'type' => \Elementor\Controls_Manager::NUMBER,
                'min' => 100,
                'max' => 1000000,
                'step' => 100,
                'default' => 3000,
            ]
        );


        $this->add_control(
            'carousel_autoplay',
            [
                'label' => __('Slides Auto Play', 'plugin-domain'),
                'type' => \Elementor\Controls_Manager::SWITCHER,
                'label_on' => __('On', 'your-plugin'),
                'label_off' => __('Off', 'your-plugin'),
                'return_value' => 'yes',
                'default' => 'yes',
            ]
        );

        $this->add_control(
            'carousel_dots',
            [
                'label' => __('Slides Bullet Navigation', 'plugin-domain'),
                'type' => \Elementor\Controls_Manager::SWITCHER,
                'label_on' => __('On', 'your-plugin'),
                'label_off' => __('Off', 'your-plugin'),
                'return_value' => 'yes',
                'default' => 'yes',
            ]
        );

        $this->add_control(
            'carousel_navs',
            [
                'label' => __('Slides Arrow Navigation', 'plugin-domain'),
                'type' => \Elementor\Controls_Manager::SWITCHER,
                'label_on' => __('On', 'your-plugin'),
                'label_off' => __('Off', 'your-plugin'),
                'return_value' => 'yes',
                'default' => 'yes',
            ]
        );

        $this->end_controls_section();
        // Slider Control

    }


    protected function render()
    {
        $settings = $this->get_settings_for_display();
        $main_slider = $settings['main_slider_items'];
        ?>

        <script type="text/javascript">
            jQuery(function () {
                $('#slider01').owlCarousel({
                    animateOut: 'fadeOut',
                    autoplayTimeout: <?php echo $settings['carousel_speed']; ?>,
                    loop: true,
                    autoplay: <?php if ($settings['carousel_autoplay']) {
                        echo "true";
                    } else {
                        echo "false";
                    } ?>,
                    dots: <?php if ($settings['carousel_dots']) {
                        echo "true";
                    } else {
                        echo "false";
                    } ?>,
                    margin: 0,
                    nav:<?php if ($settings['carousel_navs']) {
                        echo "true";
                    } else {
                        echo "false";
                    } ?>,
                    navText: ["<i class='fas fa-chevron-left'></i>", "<i class='fas fa-chevron-right'></i>"],
                    responsive: {
                        0: {
                            items: 1
                        },
                        600: {
                            items: 1
                        },
                        1000: {
                            items: 1
                        }
                    }
                })
            });
        </script>


        <div id="slider01" class="owl-carousel owl-theme">
            <?php foreach ($main_slider as $slider_item) { ?>

                <?php
                $slider_layout = $settings['slider_layout'];
                if($slider_layout == "design_01"){ ?>
                    <div class="banner-carousel-item"
                         style="background-image:url(<?php echo $slider_item['slider_image']['url'] ?>)">
                        <div class="slider-content">
                            <div class="container h-100">
                                <div class="row align-items-center h-100">
                                    <div class="col-md-12 <?php echo $slider_item['slider_content_align'] ?>">
                                        <h2 class="slide-title"><?php echo $slider_item['slider_subtitle'] ?></h2>
                                        <h3 class="slide-sub-title"><?php echo $slider_item['slider_title'] ?></h3>
                                        <p class="text-white"><?php echo $slider_item['slider_description'] ?></p>
                                        <p">
                                        <a href="<?php echo $slider_item['btn1_link']['url'] ?>"
                                           class="slider btn btn-primary"><?php echo $slider_item['slider_btn1'] ?></a>
                                        <a href="<?php echo $slider_item['btn2_link']['url'] ?>"
                                           class="slider btn btn-primary border"><?php echo $slider_item['slider_btn2'] ?></a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } elseif ($slider_layout == "design_02"){ ?>
                        <div class="banner-carousel-item" style="background-image:url(<?php echo $slider_item['slider_image']['url'] ?>)">
                            <div class="container">
                                <div class="box-slider-content">
                                    <div class="box-slider-text">
                                        <h2 class="box-slide-title"><?php echo $slider_item['slider_subtitle'] ?></h2>
                                        <h3 class="box-slide-sub-title"><?php echo $slider_item['slider_title'] ?></h3>
                                        <p class="box-slide-description"><?php echo $slider_item['slider_description'] ?></p>
                                        <p>
                                            <a href="<?php echo $slider_item['btn1_link']['url'] ?>" class="slider btn btn-primary"><?php echo $slider_item['slider_btn1'] ?></a>
                                            <a href="<?php echo $slider_item['btn2_link']['url'] ?>" class="slider btn btn-primary border"><?php echo $slider_item['slider_btn2'] ?></a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                <?php } else{ ?>
                    <div class="banner-carousel-item" style="background-image:url(<?php echo $slider_item['slider_image']['url'] ?>)">
                    </div>
                <?php }
                ?>



            <?php } ?>
        </div>
        <?php


    }
}
```

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.46 (Win64) PHP/7.3.21
	MySQL version: MySQL Community Server (GPL) v5.7.31
	PHP Version: 7.3.21
	PHP Memory Limit: 1000M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://localhost/wa
	Home URL: http://localhost/wa
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 40M
	Max Memory limit: 1000M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: afg.upload@gmail.com
	Debug Mode: Active

== Theme ==
	Name: White Assembly
	Version: 1.0.0
	Author: Mohammad Ali Khodadadi
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Basic User Avatars
		Version: 1.0.6
		Author: Stranger Studios

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.6
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Simple Lightbox
		Version: 2.8.1
		Author: Archetyped

<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: title in C:\wamp64\www\wa\wp-content\plugins\elementor\core\experiments\experiments-reporter.php on line <i>89</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>414016</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\wa\wp-admin\admin.php' bgcolor='#eeeeec'>...\admin.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.6799</td><td bgcolor='#eeeeec' align='right'>8111048</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\wamp64\www\wa\wp-admin\admin.php' bgcolor='#eeeeec'>...\admin.php<b>:</b>259</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.6799</td><td bgcolor='#eeeeec' align='right'>8111424</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='C:\wamp64\www\wa\wp-includes\plugin.php' bgcolor='#eeeeec'>...\plugin.php<b>:</b>476</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.6799</td><td bgcolor='#eeeeec' align='right'>8111424</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='C:\wamp64\www\wa\wp-includes\class-wp-hook.php' bgcolor='#eeeeec'>...\class-wp-hook.php<b>:</b>331</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.6799</td><td bgcolor='#eeeeec' align='right'>8112552</td><td bgcolor='#eeeeec'>Elementor\Modules\System_Info\Module->display_page(  )</td><td title='C:\wamp64\www\wa\wp-includes\class-wp-hook.php' bgcolor='#eeeeec'>...\class-wp-hook.php<b>:</b>307</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.9647</td><td bgcolor='#eeeeec' align='right'>8317696</td><td bgcolor='#eeeeec'>Elementor\Modules\System_Info\Module->print_report(  )</td><td title='C:\wamp64\www\wa\wp-content\plugins\elementor\modules\system-info\module.php' bgcolor='#eeeeec'>...\module.php<b>:</b>166</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>1.9655</td><td bgcolor='#eeeeec' align='right'>8318824</td><td bgcolor='#eeeeec'>require( <font color='#00bb00'>'C:\wamp64\www\wa\wp-content\plugins\elementor\modules\system-info\templates\raw.php'</font> )</td><td title='C:\wamp64\www\wa\wp-content\plugins\elementor\modules\system-info\module.php' bgcolor='#eeeeec'>...\module.php<b>:</b>320</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.1065</td><td bgcolor='#eeeeec' align='right'>8319200</td><td bgcolor='#eeeeec'>Elementor\Core\Experiments\Experiments_Reporter->print_raw(  )</td><td title='C:\wamp64\www\wa\wp-content\plugins\elementor\modules\system-info\templates\raw.php' bgcolor='#eeeeec'>...\raw.php<b>:</b>13</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.1065</td><td bgcolor='#eeeeec' align='right'>8319200</td><td bgcolor='#eeeeec'>Elementor\Core\Experiments\Experiments_Reporter->get_report(  )</td><td title='C:\wamp64\www\wa\wp-content\plugins\elementor\modules\system-info\reporters\base.php' bgcolor='#eeeeec'>...\base.php<b>:</b>95</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.1065</td><td bgcolor='#eeeeec' align='right'>8319656</td><td bgcolor='#eeeeec'>Elementor\Core\Experiments\Experiments_Reporter->get_raw_experiments(  )</td><td title='C:\wamp64\www\wa\wp-content\plugins\elementor\modules\system-info\reporters\base.php' bgcolor='#eeeeec'>...\base.php<b>:</b>148</td></tr>
</table></font>

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
JS: showing 10 of 10JS: 2022-06-22 09:50:00 [error X 2][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `slider_image` value. Expected array or object.',
)]
JS: 2022-06-22 09:50:00 [error X 2][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `slider_link` value. Expected array or object.',
)]
JS: 2022-06-22 16:01:30 [error X 7][http://localhost/wa/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: \"#tmpl-elementor-section-content\" 
JS: 2022-06-22 16:01:30 [error X 6][http://localhost/wa/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: \"#tmpl-elementor-repeater-row\" 
JS: 2022-06-23 20:54:22 [error X 2][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `icon_box_item_icon` value. Expected array or object.',
)]
JS: 2022-06-24 12:56:53 [error X 1][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `counter_item_icon` value. Expected array or object.',
)]
JS: 2022-06-25 17:34:41 [error X 3][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `testimonials_photo` value. Expected array or object.',
)]
JS: 2022-06-26 05:29:40 [error X 1][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `client_logo_link` value. Expected array or object.',
)]
JS: 2022-06-26 05:29:40 [error X 1][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `client_logo_image` value. Expected array or object.',
)]
JS: 2022-07-06 10:31:45 [error X 2][http://localhost/wa/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897948] Cannot read properties of null (reading \'getBoundingClientRect\') 

Log: showing 5 of 52022-07-05 04:55:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-05 04:55:13 [info] elementor::elementor_updater Started 
2022-07-05 04:55:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-05 04:55:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-05 04:55:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]

== Elementor - Compatibility Tag ==

**Comment by rnt-oak** [comment]
I can confirm that this no longer works. We would like to do the same. Apparently it used to work: #5304.
Elementor version: 3.7.1

**Comment by rami-elementor** [comment]
Hi,

This is an interesting use case. Never tried to use [conditions](https://developers.elementor.com/docs/control-classes/conditional-display/) inside [repeaters](https://developers.elementor.com/docs/control-classes/control-repeater/).

Generally speaking, it should not work as you create a separate repeater instance - `$repeater = new \Elementor\Repeater();`

I'll have to test to see maybe it can be done using conditions on repeater fields defined with the `fields` array (see the [two usage examples](https://developers.elementor.com/docs/control-classes/control-repeater/#usage)).

**Comment by rami-elementor** [comment]
@afgupload @rnt-oak 

I updated the developers docs - https://developers.elementor.com/docs/control-classes/conditional-display/#repeaters-conditional-display

Then new docs have several use cases how to use conditional display with repeaters.

**Comment by devtariq** [comment]
Currently conditional display rule not working on repeater fields.

**Comment by frits000000** [comment]
I did this using JQuerry with the following code

```
jQuery(window).on('elementor:init', function () {
    
    var repeaterControlName = 'Repeater_Limited'; // Change this to your repeater control id

    elementor.hooks.addAction('panel/open_editor/widget', function (panel, model) {

        var settings = model.get('settings');

        if (settings.has(repeaterControlName)) {

            // I have a controll called Layout_select that can have a value like Layout1 or Layout 2 i use this as the condition
            if(settings.get('Layout_select') == "Layout2"){ 

                var ControlToHide = "item_image" // Change this to the id of the field you want to hide if a condition is met

                var Repeater = settings.controls[repeaterControlName]
                delete Repeater.fields[ControlToHide]

                settings.set(settings.controls[repeaterControlName], Repeater);
                
                RepeaterControlls = document.getElementsByClassName('elementor-control-Repeater_Limited')[0].getElementsByClassName('elementor-repeater-fields-wrapper')[0].children

                console.log(RepeaterControlls)

                Array.from(RepeaterControlls).forEach(e => {
                    e.getElementsByClassName('elementor-control-' + ControlToHide)[0].remove()
                });

            }
        }
    });
});
```

Not that clearly documented but i hope someone finds it usefull :)
