### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by webbrosdigital** [elementor/elementor#19105]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Can't build product page templates when using WooCommerce PDF Product Vouchers by SkyVerge and using the voucher product as the previewed product. It results in a fatal error.

### Describe the solution you'd like

Work with SkyVerge as they are the recommended voucher plugin from WooCommerce so that we can use elementor with our woocommerce stores that run vouchers. It makes sense that voucher products would have a different template so it'd be great to be able to make that using Elementor's front end builder.

### Describe alternatives you've considered

I considered using Divi for this project but then decided I'd try make the template on a standard product and then just delete that product and hope the site displays the vouchers well enough as all of our products are vouchers.

**Comment by rami-elementor** [comment]
Hi @webbrosdigital ,

Thank you for submitting a feature request. After review, we have decided not to add the vouchers feature to our roadmap. Elementor is a page builder not a WooCommerce addon. We have tools to display WooCommerce data but we are not extending the base ecommerce functionality.

You have mention **WooCommerce PDF Product Vouchers by SkyVerge**. If the plugin result in a fatal error, you should contact them and file a bug report. 

We understand that our users use many different plugin, but we are not going to develop integrations to each plugin. You can contact them to and ask them to read our [developers docs](https://developers.elementor.com/) to make their plugin Elementor compatible, like many other popular plugins (Yoas SEO, Math Rank, Polylang, WPML, etc.).

Regards,
