### ISSUE TITLE
Get select control value in other select control

### ISSUE THREAD

**Issue by jahur** [elementor/elementor#19112]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi, I have two select controls. I want to access the selected value of ‘first_control’ in the ‘options’ of ‘second_control’. Here is the code

```php
$section->add_control(
	'first_control',
	[
		'label' => __( 'Title', 'text-domain' ),
		'type' => \Elementor\Controls_Manager::SELECT,
		'options' => [
			'default' => esc_html__( 'Default', 'text-domain' ),
			'yes' => esc_html__( 'Yes', 'text-domain' ),
			'no' => esc_html__( 'No', 'text-domain' ),
		],
	]
);

$section->add_control(
	'second_control',
	[
		'label' => __( 'Title', 'text-domain' ),
		'type' => \Elementor\Controls_Manager::SELECT,
		'options' => get_single_tab_values_by_id(selected value of first_control), // Here I want to get the selected value of first_control so that I can fetch some other values from db
	]
);
```

Thanks in advance!

### Describe the solution you'd like

Not sure how to solve it.

**Comment by rami-elementor** [comment]
The short answer is **NO**. There is no way to do that.

But there are workarounds we use in Elementor and Elementor Pro.

You can use the `condition` argument in you controls. Read more [conditional display](https://developers.elementor.com/docs/controls/conditional-display/).

```php
$section->add_control(
	'main_control',
	[
		'label' => __( 'Title', 'text-domain' ),
		'type' => \Elementor\Controls_Manager::SELECT,
		'options' => [
			'default' => esc_html__( 'Default', 'text-domain' ),
			'yes' => esc_html__( 'Yes', 'text-domain' ),
			'no' => esc_html__( 'No', 'text-domain' ),
		],
	]
);

$section->add_control(
	'true_condition',
	[
		'label' => __( 'Title', 'text-domain' ),
		'type' => \Elementor\Controls_Manager::SELECT,
		'condition' => [
			'main_control' => 'yes',
		],
	]
);

$section->add_control(
	'false_condition',
	[
		'label' => __( 'Title', 'text-domain' ),
		'type' => \Elementor\Controls_Manager::SELECT,
		'condition' => [
			'main_control' => [ 'no', 'default' ],
		],
	]
);
```

**Comment by jahur** [comment]
Hi, @rami-elementor Thanks for your help. I really appreciate it but unfortunately, it does not work for my case. I am developing my own custom control to achieve this. 
Thanks a lot!

**Comment by dbjpanda** [comment]
@jahur Could you please paste some snippet on how to access another control value inside your custom control?

**Comment by rami-elementor** [comment]
@dbjpanda 

See this dev doc: https://developers.elementor.com/docs/editor-controls/selectors/#values-from-other-controls

**Comment by dbjpanda** [comment]
@rami-elementor Can you please always try to read the issue and understand it before you reply or close it? It's not about only only selector but other properties also.

**Comment by zbandhan** [comment]
> Hi, @rami-elementor Thanks for your help. I really appreciate it but unfortunately, it does not work for my case. I am developing my own custom control to achieve this. Thanks a lot!

Hi @jahur did you develop it to solve the issue?

**Comment by jahur** [comment]
Hi @zbandhan 
I solved it in a different way. I used ajax to do that. But for my plugin I changed the UI so I don’t need to have both select input.

Thank you
