### ISSUE TITLE
🐞 Bug report: Note replies are shown out of order

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#19123]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've been using the Notes feature with a collaborator, and I notice that the replies display out of order sometimes. 

Here's a screenshot of one example (anonymised). The first comment is in the correct spot, but the other comments are out of order (the number indicates the position that it should be in). You can also spot this by checking the date and time. 

It seems to be occurring on any comment threads longer than 2 replies. 

https://cln.sh/o0BMAo9hKBtUNKuFYpcC

### Steps to reproduce

1) Leave a series of replies on any given comment pin

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Can email this privately on request

**Comment by drawcard** [comment]
Also I don't think the timestamps are displaying correctly either. Here, the timestamps are duplicated on two comments. These two comments were posted at different times (I was replying to an earlier one, and it seems to have inherited that time stamp). https://cln.sh/zjgaKlM5IclhWPIWHjOO

**Comment by avivu** [comment]
This issue has been resolved in Elementor Pro v3.8.0

Feel free to update

Thanks!
