### ISSUE TITLE
🐞 Bug report: Google Font Baskerville loads font "Baskervville"

### ISSUE THREAD

**Issue by makaus** [elementor/elementor#19134]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When setting Baskerville as font in Global fonts in theme settings, it loads Baskervville and not Baskerville.
They look similar but Baskerville is smaller.

See attached photo, i have overwritten it with Baskerville for now.
![Screenshot 2022-07-12 at 13 56 49](https://user-images.githubusercontent.com/8776403/178484828-710d49d2-3b2c-4e54-b219-38e44ab9b3f1.png)

### Steps to reproduce

Choose Baskerville as font gives you Baskervville in front-end.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: Percona Server (GPL), Release 40, Revision 3a1347ec0d4 v5.7.37-40
	PHP Version: 8.1.5
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: http://rudkobingskudehavn.dk.linux4.curanetserver.dk
	Home URL: http://rudkobingskudehavn.dk.linux4.curanetserver.dk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Admin Email: wp@uptime.dk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Duplicator
		Version: 1.4.7
		Author: Snap Creek

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Insert Headers and Footers
		Version: 1.6.2
		Author: WPBeginner

	Smush
		Version: 3.10.2
		Author: WPMU DEV

	Wordfence Security
		Version: 7.5.11
		Author: Wordfence

	Yoast SEO
		Version: 19.2
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		google_maps : 1
		icon-list : 3
		nav-menu : 1
		text-editor : 7
	header : 1
		button : 2
		icon : 1
		nav-menu : 2
		theme-site-logo : 1
	page : 1
		heading : 1
		image : 1
		text-editor : 2
	popup : 1
		nav-menu : 1
	section : 1
		heading : 1
		tabs : 1
		text-editor : 1
	wp-page : 3
		button : 4
		heading : 13
		icon : 6
		icon-list : 6
		image : 13
		image-carousel : 2
		spacer : 2
		tabs : 1
		text-editor : 39
	error-404 : 1
		heading : 1
		nav-menu : 1
		text-editor : 1

== Elementor Experiments ==
	Optimeret DOM-output: Inaktiv som standard
	Forbedret ressourceindlæsning : Inaktiv som standard
	Forbedret indlæsning af CSS ressourcer: Inaktiv som standard
	Inline Font Icons: Inaktiv som standard
	Accessibility Improvements: Inaktiv som standard
	Importer/Eksporter Kit skabelon: Aktiv som standard
	Additional Custom Breakpoints: Inaktiv som standard
	Hide native WordPress widgets from search results: Aktiv som standard
	: Inaktiv som standard
	Flexbox Container: Inaktiv som standard
	Default to New Theme Builder: Aktiv som standard
	Hello sidehoved og sidefod: Inaktiv som standard
	Landingsside: Aktiv som standard
	Color Sampler: Aktiv som standard
	Favorit widgets: Aktiv som standard
	Administrator topbjælke: Aktiv som standard
	Page Transitions: Aktiv som standard
	Notes: Aktiv som standard
	Modtagne formularer: Aktiv som standard
	Scroll Snap: Aktiv som standard

== Log ==
	
Log: showing 20 of 352022-06-13 09:33:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-13 09:33:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-13 09:33:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-13 09:38:39 [info] elementor-pro::elementor_pro_updater Started 
2022-06-13 09:38:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-13 09:38:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-13 09:38:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-13 09:38:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-07-08 13:59:20 [info] elementor::elementor_updater Started 
2022-07-08 13:59:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-08 13:59:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-08 13:59:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-08 13:59:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-08 14:32:11 [info] elementor-pro::elementor_pro_updater Started 
2022-07-08 14:32:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-07-08 14:32:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-08 14:32:11 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-07-08 14:32:11 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-07-08 14:32:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-08 14:32:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

PHP: showing 6 of 6PHP: 2022-05-16 08:58:08 [notice X 226][/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 09:30:44 [error X 1][/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /var/www/www.rudkobingskudehavn.dk/www/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 10:08:49 [notice X 8][/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-13 10:09:27 [notice X 484][/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-07-08 14:32:28 [warning X 8][/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-11 15:40:17 [warning X 2][/var/www/www.rudkobingskudehavn.dk/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-07-11 08:57:23 [error X 3][http://rudkobingskudehavn.dk.linux4.curanetserver.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897948] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by m1ga** [comment]
Google fonts either has: 
`Libre Baskerville` https://fonts.google.com/?query=Baskerville
`Baskervville` https://fonts.google.com/specimen/Baskervville?query=Baskervville
both can be selected in Elementor
