### ISSUE TITLE
🐞 Bug report: Fix documentation highlighting

### ISSUE THREAD

**Issue by m1ga** [elementor/elementor#19160]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The highlighting in the documentation is broken. It's always slightly off:

![Screenshot_20220714_164219](https://user-images.githubusercontent.com/4334997/179009597-d64c7148-c640-4018-8300-26edcd29f57f.png)

Either remove the highlighting or set it to the correct position. The current color makes it harder to read

### Steps to reproduce

Open the documentation https://developers.elementor.com/docs/controls/classes/control-wysiwyg/#usage

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Firefox 102
Chromium 102

**Comment by rami-elementor** [comment]
Hi @m1ga 

I think you are using an old version of the page. Can you please hard-refresh (`CTRL`+`F5`) the page to load non-cached version?

Let me know if it helps.

**Comment by m1ga** [comment]
no, it has been like this for me all the time for month. I'm using different browsers, privacy session and cleared the cache

your highlight divs don't match up with the line number/rows:

![Screenshot_20220717_115531](https://user-images.githubusercontent.com/4334997/179393118-e69ee93c-578e-4f67-b5c8-66af1e6cb5a1.png)

I'm using Fedora/Linux so maybe there is a font issue. It would be good if you test it on different machines
