### ISSUE TITLE
🐞 Bug report: This site can’t be reached, The connection was reset.

### ISSUE THREAD

**Issue by mfrankii** [elementor/elementor#19175]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After installing and enabling this plugin 'Elementor' the site not working.
TYPE ERROR: ERR_CONNECTION_RESET

### Steps to reproduce

1. Install the plugin (version 3.7.0)
2. enable it
3. Log in to a website. get error
4. Remove / Deactivate the plugin, the problem is solved

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.25
	PHP Version: 8.0.20
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://localhost/wordpress
	Home URL: http://localhost/wordpress
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 2
	Admin Email: ******
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.0-dev10
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.8
		Author: WPDeveloper

	Templately
		Version: 1.3.6
		Author: Templately

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
PHP: showing 1 of 1PHP: 2022-07-15 17:39:58 [warning X 2][C:\Bitnami\wordpress-6.0.1-0\apps\wordpress\htdocs\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 7 of 72022-07-16 13:14:29 [info] elementor::elementor_updater Started 
2022-07-16 13:14:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-16 13:14:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-16 13:14:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-07-16 13:14:29 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-07-16 13:14:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0-dev10',
)]
2022-07-16 13:14:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0-dev10',
)]

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible

**Comment by mfrankii** [comment]
**Server Logs:**
```
[Sat Jul 16 17:23:38.093157 2022] [ssl:warn] [pid 1876:tid 384] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 16 17:23:38.261265 2022] [ssl:warn] [pid 1876:tid 384] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 16 17:23:38.308099 2022] [mpm_winnt:notice] [pid 1876:tid 384] AH00455: Apache/2.4.54 (Win64) OpenSSL/1.1.1o PHP/8.0.20 configured -- resuming normal operations
[Sat Jul 16 17:23:38.308099 2022] [mpm_winnt:notice] [pid 1876:tid 384] AH00456: Apache Lounge VS16 Server built: Jun  5 2022 10:18:11
[Sat Jul 16 17:23:38.308099 2022] [core:notice] [pid 1876:tid 384] AH00094: Command line: 'C:\\Bitnami\\WORDPR~1.1-0\\apache2\\bin\\httpd.exe -d C:/Bitnami/wordpress-6.0.1-0/apache2 -f C:\\Bitnami\\WORDPR~1.1-0\\apache2\\conf\\httpd.conf'
[Sat Jul 16 17:23:38.320440 2022] [mpm_winnt:notice] [pid 1876:tid 384] AH00418: Parent: Created child process 13568
[Sat Jul 16 17:23:39.665875 2022] [ssl:warn] [pid 13568:tid 448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 16 17:23:39.848037 2022] [ssl:warn] [pid 13568:tid 448] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 16 17:23:39.915819 2022] [mpm_winnt:notice] [pid 13568:tid 448] AH00354: Child: Starting 64 worker threads.
VirtualProtect() failed [87] The parameter is incorrect
```

**Comment by rami-elementor** [comment]
Hi @mfrankii ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by maxrys** [comment]
About `virtualprotect() failed 87 the parameter is incorrect`

I was investigating the same case.

I tested CMS EFFCORE on the Windows platform (`Windows 10 2021 LTSC x64`).

After installing Apache House (`httpd-2.4.57-win64-VS17.zip`) and PHP (`php-8.2.11-vs16-x64.zip`), I began to include the missing modules to install the system.

I enabled all the required modules and the system installed without problems.

I ran all the tests and they ran successfully.

Then I decided to speed up the system and enabled `OPCache + JIT`.

After enabling `OPCache + JIT` I started getting a "white screen" and the message `virtualprotect() failed 87 the parameter is incorrect`.

After disabling `OPCache + JIT` or `OPCache` the problem went away.

I was wondering what this error was.

I created a small script and placed it in the `test.php` file.

It had the following contents:

    $path = 'data.php';
    $lines_num = 2000;
    if (!file_exists($path)) {
        file_put_contents($path, '<?php'."\n", FILE_APPEND);
        for ($i = 0; $i < $lines_num; $i++)
            file_put_contents($path, '$data['.$i.'] = \'value '.$i."';\n", FILE_APPEND);
        file_put_contents($path, 'print \'COUNT: \'.count($data);', FILE_APPEND);
        print 'FILE WAS CREATED. RELOAD THIS PAGE';
    } else {
        include_once($path);
        print "\n".'FILE WAS INCLUDED';
    }

Next, I ran `test.php` from the browser and got a white screen if `lines_num` was greater than `2000` and a normal result if less than `2000`.
This is an obvious _overflow of some memory segment_.
However, the log did not contain any information about the error.

From the console I ran this script with any number of `lines_num` and no problems arose.

    php -d opcache.jit_debug=1 test.php
    php -d opcache.jit_debug=1 data.php

I concluded that the problem is with the Apache + PHP combination as a module.
However, there were no problems under Linux/Unix.

Here is the complete list of links:
- win: Apache + PHP as a module - `JIT problem`
- win: IIS + PHP as FastCGI - OK
- win: PHP CLI - OK
- nix: Apache + PHP as a module - OK
- nix: NGINX + PHP as FastCGI - OK
- nix: PHP CLI - OK

I had to disable OPCache in `php.ini` via `opcache.enable=0` and the problem went away.

In `php.ini` you can disable only `JIT` via `opcache.jit_buffer_size=0` but this setting cannot be changed directly from PHP code.

Changing other `opcache.*` settings in `php.ini` did not lead to anything.

You can also disable `OPCache + JIT` programmatically with the following code:

     if (DIRECTORY_SEPARATOR === '\\') {
         ini_set('opcache.enable', false);
     }

Thank you for your attention, I hope it helped.

**Comment by vanbess** [comment]
> About `virtualprotect() failed 87 the parameter is incorrect`
> 
> I was investigating the same case.
> 
> I tested CMS EFFCORE on the Windows platform (`Windows 10 2021 LTSC x64`).
> 
> After installing Apache House (`httpd-2.4.57-win64-VS17.zip`) and PHP (`php-8.2.11-vs16-x64.zip`), I began to include the missing modules to install the system.
> 
> I enabled all the required modules and the system installed without problems.
> 
> I ran all the tests and they ran successfully.
> 
> Then I decided to speed up the system and enabled `OPCache + JIT`.
> 
> After enabling `OPCache + JIT` I started getting a "white screen" and the message `virtualprotect() failed 87 the parameter is incorrect`.
> 
> After disabling `OPCache + JIT` or `OPCache` the problem went away.
> 
> I was wondering what this error was.
> 
> I created a small script and placed it in the `test.php` file.
> 
> It had the following contents:
> 
> ```
> $path = 'data.php';
> $lines_num = 2000;
> if (!file_exists($path)) {
>     file_put_contents($path, '<?php'."\n", FILE_APPEND);
>     for ($i = 0; $i < $lines_num; $i++)
>         file_put_contents($path, '$data['.$i.'] = \'value '.$i."';\n", FILE_APPEND);
>     file_put_contents($path, 'print \'COUNT: \'.count($data);', FILE_APPEND);
>     print 'FILE WAS CREATED. RELOAD THIS PAGE';
> } else {
>     include_once($path);
>     print "\n".'FILE WAS INCLUDED';
> }
> ```
> 
> Next, I ran `test.php` from the browser and got a white screen if `lines_num` was greater than `2000` and a normal result if less than `2000`. This is an obvious _overflow of some memory segment_. However, the log did not contain any information about the error.
> 
> From the console I ran this script with any number of `lines_num` and no problems arose.
> 
> ```
> php -d opcache.jit_debug=1 test.php
> php -d opcache.jit_debug=1 data.php
> ```
> 
> I concluded that the problem is with the Apache + PHP combination as a module. However, there were no problems under Linux/Unix.
> 
> Here is the complete list of links:
> 
> * win: Apache + PHP as a module - `JIT problem`
> * win: IIS + PHP as FastCGI - OK
> * win: PHP CLI - OK
> * nix: Apache + PHP as a module - OK
> * nix: NGINX + PHP as FastCGI - OK
> * nix: PHP CLI - OK
> 
> I had to disable OPCache in `php.ini` via `opcache.enable=0` and the problem went away.
> 
> In `php.ini` you can disable only `JIT` via `opcache.jit_buffer_size=0` but this setting cannot be changed directly from PHP code.
> 
> Changing other `opcache.*` settings in `php.ini` did not lead to anything.
> 
> You can also disable `OPCache + JIT` programmatically with the following code:
> 
> ```
>  if (DIRECTORY_SEPARATOR === '\\') {
>      ini_set('opcache.enable', false);
>  }
> ```
> 
> Thank you for your attention, I hope it helped.

Thanks @maxrys! Solved an issue where the connection issue would pop up the moment I activated WooCommerce on localhost (UniseverZ for those wondering). After disabling Opcache as per your example the issue went away. Can't be arsed at this stage to figure out why Opcache is causing issues with WooCommerce in particular (probably some related issue in my php.ini file) - will have to put that on the backburner for now.
