### ISSUE TITLE
✔️ 🚀 Post Grid Element causes "excessive DOM size" google PageSpeed Issue

### ISSUE THREAD

**Issue by confile** [elementor/elementor#19171]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Post Grid Element causes "excessive DOM size" google PageSpeed Issue

![PageSpeed_Insights](https://user-images.githubusercontent.com/64265/179229919-a5dd748e-1157-4db1-9b49-4d6890cf2022.jpg)

Sample Page: https://www.michaelgorski.net/

### Steps to reproduce

Open the sample page with google page speed.

Sample Page: https://www.michaelgorski.net/

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/pXQ5JR8w

**Comment by m1ga** [comment]
I only quickly looked at the DOM but can't you move the inner `<section>`  with the posts below the headline + text out of the outer section? I'm sure that will remove some level of complexity and perhaps the page speed check will pass.

**Comment by m1ga** [comment]
oh and since its a German website: 
use local fonts and not external Google fonts: 
https://www.ra-plutte.de/lg-muenchen-dynamische-einbindung-google-web-fonts-ist-dsgvo/

**Comment by confile** [comment]
Well this did not solve the problem. If you check this: https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.michaelgorski.net%2F&hl=en

Under: 
Avoid an excessive DOM size

You see that the total DOM elements are too much.

**Comment by m1ga** [comment]
but this time its the `fas fa-plus` (from `APT-Response`) and not the `mehr lesen` arrow. At least thats the result for me

**Comment by m1ga** [comment]
and use e.g. https://de.wordpress.org/plugins/autoptimize/ to merge JS files. Will reduce 51 DOM elements to 1 (or at least below 5)

**Comment by m1ga** [comment]
In case you don't use the experimental flexbox containers: they save a lot too!

**Comment by confile** [comment]
I use WP-Rocket and I guess it will do the same right?

**Comment by m1ga** [comment]
I can't help you with that, never used it. But I also think its not related to a Elementor bug ticket and more a optimize my page question 😄 
My tips are:
* restructure your page and don't nest your sections (close them and start a new one) (reduces alot)
* try the flexbox feature, will save you 2-4 divs per column/section (reduces alot)
* merge your files (-50 elements)
* don't use spacer elements, use margin-top or bottom (-4 elements for each appearance)
* don't use external Google Fonts (you sell GDRP consulting so your page shouldn't violate it 😉 )

Elementor uses a lot of DOM elements, no matter what you do, a single Headline always has more divs around it and you can't get rid of all of those. If you can: create custom plugins/widgets in PHP then you can control the inner content. e.g. a 3 column headline + text structure will be like 10 elements difference but you'll lose some flexibility and have to be capable of creating widgets https://developers.elementor.com/docs/controls/simple-example/

thats all I can help here

**Comment by nicholaszein** [comment]
Hello @confile!

### 📢 We're happy to announce that the <ins>stable</ins> version of the Flexbox Container experiment was introduced with Elementor **v3.8**! 🥳 

This means that you can now create layouts with fewer nested elements, which means a much smaller DOM size, which in turn can definitely solve your issue.

✔️ Please feel free to update your plugin to the new version, activate the Flexbox Container experiment, and start enjoying a lighter DOM size! 💪

Cheers 🥂
