### ISSUE TITLE
✅ 🚀 Feature Request: Advanced search widget (Ajax search)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19182]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hello elementor team.
I don't know if this is on your roadmap or not, but the current search widget is really disappointing. Even the simplest customizations such as icon change (elementor icon library or svg icon) are not available in this widget. Advanced search is something that all modern websites have. But in Elementor, this widget has not been paid any attention so far. Therefore, we have to depend on other plugins to meet this need. Like jet search

### Describe the solution you'd like

**Some essential features for the search widget**

- **Ajax search**
- **Ability to assign a search to a specific post type**
- **Advanced pagination of Ajax results**
- Custom message if no results found
- Ability to display search history to users
- The ability to display the most searched words
- The possibility of analyzing the most searched words by the site manager (to analyze the contents or products of interest to users)
- Very strong customization (like jet search plugin)
- The ability to display categories
- **The possibility of inserting two icons. 1- Input field icon 2- Search button icon** 
- Search based on the current query 
- Advanced query section (include and exclude)
- The possibility of searching based on a custom field (loop builder)
- Ability to sort the results based on (day, number of comments, etc. / ascending descending)
- The ability to determine the number of Ajax results + the ability to determine the number of results per page
- Highlight Searched Text
- Ability to display product prices,product category, rating stars, number of comments, publication date
- Open in new tab feature
- **Ability to customize search results items using loop builder (Fully customize the search results item using the loop builder, then add it to the advanced form widget)**
- display results counter
- Custom icons for the previous and next button Pagination
- **Custom icon for Ajax load** Like the spinner icon + The possibility of using an image for Ajax loading (brand image display)
- Custom title length
- The possibility of separate customization for WooCommerce price and previous price
- The ability to display the image in the Ajax search results section

I'd love to hear your feedback on this feature. If you read it

**Comment by pg-los** [comment]
second this

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.23.0! 🥳 

To learn more check this article: https://elementor.com/help/search-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
