### ISSUE TITLE
🐞 Bug report: Security, backdoor creates random woocommerce users

### ISSUE THREAD

**Issue by peterlu2000** [elementor/elementor#19196]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We are getting a lot of spam users registration since we upgraded elementor and elementor pro few months ago. Now we are on the latest version.

### Steps to reproduce

array (
 'shipping_country' => 'NG',
 'email' => '[cherryux20@takayuki4010.masashi15.meta1.in.net](mailto:cherryux20@takayuki4010.masashi15.meta1.in.net)',
 'password' => 'some_random_password',
 'email_2' => '[cherryux20@takayuki4010.masashi15.meta1.in.net](mailto:cherryux20@takayuki4010.masashi15.meta1.in.net)',
 'gglcptch' => '',
 'g-recaptcha-response' => 'xxxsxyxyxyxyxyxyxyxyxyxyxxyxyxyxyxyx............',
 'woocommerce-register-nonce' => '882aSOMENONCE',
 '_wp_http_referer' => '/my-account/',
 'register' => 'Register',
 'action' => 'elementor_pro_forms_send_form',
)

It looks like the BOT is touching the woocommerce /my-account/ page, then ping admin-ajax.php
I believe I have set up recaptcha v3 in the elementor settings. And I don't think I have created any Elementor Forms.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Wordpress 6.0.0

**Comment by shilo-ey** [comment]
Various sources may cause security issues.

I suggest reaching out to our support or creating a bug via our [bug bounty program](https://elementor.com/trust/) for a valid report.
