### ISSUE TITLE
🚀 Feature Request: Elementor loop builder structure

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19194]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi @shilo-ey , @rami-elementor and other elementor developers. We know that you will soon add loop builder to elementor. But we do not know whether its coding has started or not. Also, we don't know what the loop builder structure will be like in elementor. So, before releasing this big update, I would like to request you to please watch [this video](https://www.youtube.com/watch?v=LxrLROitgn8). In this video, the rival page builder uses the most advanced loop builder mode.
In such a way that a container can be converted into a loop, so that all the components inside it can be dynamically converted into a loop. This is really wonderful. And it has two very important advantages.
1- It increases the speed of work.
2- We will have highly optimized coding.

Actually I think if you decide to add loop builder like elementor custom skin plugin, it will become obsolete in near future. **(Because the method implemented in the video above will definitely have many fans.)**
I hope I have not filed this request too late. And I also hope that the loop builder will appear in elementor powerful and without competitors.
If you're read this issue, I'd love to hear your feedback on it.

### Describe the solution you'd like

The possibility of converting the container into a loop (Like the video above)

**Comment by m1ga** [comment]
check the PR section you'll find e.g. an old PR https://github.com/elementor/elementor/pull/18768/files
with a small intro:
> A Loop is a layout you can customize to display recurring dynamic content - like listings, posts, portfolios, products, , etc.

> Start by creating a master item. All the other instances in the grid will match this design. Then go back to the widget in the editor panel and assign both a template and a source of content. Your grid should populate automatically.

And there are is a branch you could try https://github.com/elementor/elementor/tree/feature/loop-builder

**Comment by Michaelgimii** [comment]
> check the PR section you'll find e.g. an old PR https://github.com/elementor/elementor/pull/18768/files with a small intro:
> 
> > A Loop is a layout you can customize to display recurring dynamic content - like listings, posts, portfolios, products, , etc.
> 
> > Start by creating a master item. All the other instances in the grid will match this design. Then go back to the widget in the editor panel and assign both a template and a source of content. Your grid should populate automatically.
> 
> And there are is a branch you could try https://github.com/elementor/elementor/tree/feature/loop-builder

Unfortunately, I did not understand well. According to the documentation, do you think the loop builder structure in elementor will be exactly like ele skin custom?

Another question is whether loop builder will be released in version 3.8 core?

**Comment by m1ga** [comment]
Thats how I understand it, yes. You build a theme, then go to your page inside the "loop" widget and select the theme item you've created. 
There is a discussion at https://github.com/elementor/elementor/discussions/18894 where someone says 3.8 or 3.9. But all of that (impementation and release date) is not fix so it can change 😄 Hopefully it will be good at the end (and in the free version too) 👍
