### ISSUE TITLE
🐞 Bug report: Elementor builder is loading in public site for all users (very slow site)

### ISSUE THREAD

**Issue by v1lle1** [elementor/elementor#19199]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello!

Elementor tier 3 support asked me to write to you about this problem:

Our hosting provider has done some research about this problem.
They said that Elementor is calling elementor-builder even for users
who have not logged in. They can even see the row in code which makes the
site super slow.

Is this something that you can help us with? We had these problems for many
months now and this has cost a lot of money to figure out. Can you please
tell how we can fix this or where we can see more info about elementor
loading page-builder for every user?

How we can fix this, or is there anything we can do?

Thanks!

### Steps to reproduce

This is loading multiple seconds everytime we load site:

Elementor\Frontend->apply_builder_in_content() in file elementor/includes/frontend.php in row 995

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: mariadb.org binary distribution v10.5.15
	PHP Version: 8.0.20
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.3
	Site URL: https://www.hermandia.com
	Home URL: https://www.hermandia.com
	WP Multisite: No
	Max Upload Size: 128 Mt
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fi
	Timezone: Europe/Helsinki
	Admin Email: ville@villelintula.fi
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fi
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.62
		Author: ServMask

	Better Search Replace
		Version: 1.4
		Author: Delicious Brains

	Check & Log Email
		Version: 1.0.6
		Author: WPChill

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Cloudways WordPress Migrator
		Version: 4.78
		Author: Cloudways

	Code Snippets
		Version: 3.1.1
		Author: Code Snippets Pro

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	Hide Shipping Methods based on Shipping Class and Zone
		Version: 1.0.8
		Author: PluginHive

	Insert Headers and Footers
		Version: 1.6.2
		Author: WPBeginner

	JetElements For Elementor
		Version: 2.6.6
		Author: Crocoblock

	JetEngine
		Version: 3.0.1
		Author: Crocoblock

	JetProductGallery For Elementor
		Version: 2.1.2
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.12
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.17
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 1.12.4
		Author: Crocoblock

	Klarna Checkout for WooCommerce
		Version: 2.8.4
		Author: Krokedil

	Klarna Order Management for WooCommerce
		Version: 1.6.10
		Author: klarna, krokedil

	Klarna Payments for WooCommerce
		Version: 2.10.0
		Author: krokedil, klarna, automattic

	Limit Login Attempts Reloaded
		Version: 2.25.3
		Author: Limit Login Attempts Reloaded

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	Product Input Fields for WooCommerce
		Version: 1.3.2
		Author: Tyche Softwares

	PW WooCommerce Gift Cards Pro
		Version: 1.370
		Author: Pimwick, LLC

	Redirection
		Version: 5.2.3
		Author: John Godley

	ShopEngine
		Version: 2.2.2
		Author: Wpmet

	Site Kit by Google
		Version: 1.78.0
		Author: Google

	Smash Balloon Instagram Feed
		Version: 6.0.6
		Author: Smash Balloon

	WooCommerce
		Version: 6.6.1
		Author: Automattic

	WooCommerce Attribute Swatches by Iconic
		Version: 1.11.2
		Author: Iconic <support@iconicwp.com>

	WooCommerce Email Test
		Version: 1.2.2
		Author: RaiserWeb

	WooCommerce Google Analytics Integration
		Version: 1.5.11
		Author: WooCommerce

	WooCommerce Multilingual & Multicurrency
		Version: 5.0.2
		Author: OnTheGoSystems

	WooCommerce PayPal Checkout Gateway
		Version: 2.1.3
		Author: WooCommerce

	WooCommerce PayPal Payments
		Version: 1.9.0
		Author: WooCommerce

	WooCommerce Product Configurator by Iconic
		Version: 1.6.2
		Author: Iconic

	Woocommerce Side Cart Premium
		Version: 3.1
		Author: XootiX

	WooCommerce Stripe Gateway
		Version: 6.4.3
		Author: WooCommerce

	WooCommerce UPS Shipping Plugin with Print Label
		Version: 4.4.2
		Author: PluginHive

	WooThumbs for WooCommerce by Iconic
		Version: 4.15.0
		Author: Iconic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP File Manager
		Version: 7.1.6
		Author: mndpsingh287

	WP Mail Logging
		Version: 1.10.4
		Author: Wysija

	WPML Media
		Version: 2.7.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.5.8
		Author: OnTheGoSystems

	WPML SEO
		Version: 2.0.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.1
		Author: OnTheGoSystems

	WP Store Locator
		Version: 2.2.235
		Author: Tijmen Smit

	YITH WooCommerce Product Add-ons & Extra Options
		Version: 2.11.0
		Author: YITH

	Yoast SEO
		Version: 19.3
		Author: Team Yoast

== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots

== Elements Usage ==
	
	header : 15
		icon : 2
		nav-menu : 1
		woocommerce-menu-cart : 1
		wpml-language-switcher : 1
	footer : 13
		heading : 7
		image : 3
		nav-menu : 1
		social-icons : 1
	page : 10
		button : 12
		divider : 1
		heading : 33
		icon : 6
		image : 32
		jet-cart-table : 1
		jet-cart-totals : 1
		jet-checkout-billing : 1
		jet-single-attributes : 2
		jet-woo-product-gallery-slider : 4
		jet-woo-products : 9
		slides : 1
		template : 2
		text-editor : 21
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-price : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 2
	popup : 13
		heading : 1
	product : 1
		button : 2
		heading : 6
		image : 1
		jet-single-attributes : 1
		jet-woo-product-gallery-slider : 2
		jet-woo-products : 3
		testimonial : 3
		text-editor : 3
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	section : 88
		button : 17
		call-to-action : 4
		divider : 1
		heading : 46
		icon : 14
		icon-box : 6
		image : 10
		jet-checkout-billing : 2
		jet-checkout-order-review : 3
		jet-checkout-payment : 2
		jet-single-attributes : 2
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-radio : 4
		jet-smart-filters-remove-filters : 4
		jet-smart-filters-select : 1
		jet-woo-product-gallery-modern : 1
		jet-woo-product-gallery-slider : 2
		jet-woo-products : 11
		slides : 3
		spacer : 3
		template : 2
		testimonial : 6
		text-editor : 35
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 2
		woocommerce-product-price : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 2
	widget : 0
		jet-checkout-order-review : 1
	wp-post : 8
		heading : 2
		image : 9
		shopengine-checkout-form-billing : 2
		shopengine-checkout-payment : 2
		shopengine-checkout-review-order : 2
		shopengine-checkout-shipping-methods : 1
		text-editor : 7
	wp-page : 145
		button : 21
		countdown : 1
		heading : 62
		icon : 72
		image : 27
		jet-woo-products : 16
		spacer : 3
		template : 3
		text-editor : 103
		video : 2
	product-archive : 38
		button : 4
		call-to-action : 4
		form : 1
		heading : 16
		image : 4
		jet-woo-products : 5
		spacer : 4
		template : 3
		text-editor : 10
		video : 1
	jet-woo-builder-checkout : 0
		jet-accordion : 1
		jet-checkout-order-review : 1
	jet-woo-builder-cart : 0
		button : 1
		divider : 2
		heading : 2
		jet-cart-empty-message : 1
		jet-cart-table : 1
		jet-cart-totals : 1
	jet-woo-builder : 44
		heading : 14
		jet-single-attributes : 4
		jet-single-content : 4
		jet-woo-product-gallery-slider : 8
		jet-woo-products : 2
		spacer : 1
		text-editor : 2
		video : 1
		woocommerce-breadcrumb : 4
		woocommerce-product-add-to-cart : 4
		woocommerce-product-price : 4
		woocommerce-product-short-description : 1
		woocommerce-product-title : 4

== Elementor Experiments ==
	Optimoitu DOM-tulostus: Ei-aktiivinen oletuksena
	Parannettu resurssien lataus: Ei-aktiivinen oletuksena
	Improved CSS Loading: Ei-aktiivinen oletuksena
	Inline Font Icons: Ei-aktiivinen oletuksena
	Saatavuuden parannukset: Ei-aktiivinen oletuksena
	Import Export Template Kit: Aktiivinen oletuksena
	Additional Custom Breakpoints: Ei-aktiivinen
	Hide native WordPress widgets from search results: Aktiivinen oletuksena
	: Ei-aktiivinen oletuksena
	Flexbox Container: Ei-aktiivinen oletuksena
	Default to New Theme Builder: Aktiivinen oletuksena
	Hello Theme Header & Footer: Ei-aktiivinen oletuksena
	Myyntisivut: Aktiivinen oletuksena
	Color Sampler: Aktiivinen oletuksena
	Favorite Widgets: Aktiivinen oletuksena
	Admin Top Bar: Aktiivinen oletuksena
	Page Transitions: Aktiivinen oletuksena
	Notes: Aktiivinen oletuksena
	Form Submissions: Aktiivinen oletuksena
	Scroll Snap: Aktiivinen oletuksena

== Log ==
	
Log: showing 20 of 222022-05-04 09:06:16 [info] elementor::elementor_updater Started 
2022-05-04 09:06:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-05-04 09:06:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-04 09:06:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-05-04 09:06:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-05-12 08:05:08 [info] elementor-pro::elementor_pro_updater Started 
2022-05-12 08:05:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-12 08:05:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-12 08:05:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.0',
)]
2022-05-22 06:31:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-22 06:31:39 [info] elementor-pro::elementor_pro_updater Started 
2022-05-22 06:31:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-05-22 06:31:40 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-22 06:31:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-22 06:31:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-07-12 11:36:40 [info] elementor::elementor_updater Started 
2022-07-12 11:36:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-12 11:36:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.7',
)]
2022-07-12 11:36:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-12 11:36:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.7',
)]

PHP: showing 18 of 18PHP: 2022-04-18 22:41:42 [notice X 14][/data/wordpress/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-20 14:20:39 [warning X 2][/data/wordpress/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-22 18:16:58 [warning X 7][/data/wordpress/htdocs/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-12 15:10:25 [error X 2][/data/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/notes/usage.php::161] Uncaught Error: Call to a member function format() on null in /data/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/notes/usage.php:161
Stack trace:
#0 /data/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/notes/usage.php(43): ElementorPro\Modules\Notes\Usage->get_first_interaction()
#1 /data/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/notes/usage.php(27): ElementorPro\Modules\Notes\Usage->get_usage_data()
#2 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Notes\Usage->ElementorPro\Modules\Notes\{closure}(Array)
#3 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#4 /data/wordpress/htdocs/wp-content/plugins/elementor/includes/tracker.php(563): apply_filters('elementor/track...', Array)
#5 /data/wordpress/htdocs/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#6 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#7 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#8 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#9 /data/wordpress/htdocs/wordpress/wp-cron.php(138): do_action_ref_array('elementor/track...', Array)
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-13 14:36:39 [notice X 111][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(247): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-13 14:36:39 [notice X 111][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(285): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-13 14:36:39 [notice X 111][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-13 14:36:39 [notice X 111][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-13 14:36:39 [notice X 112][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/shopengine/core/elementor-controls/init.php(38): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-13 14:36:39 [notice X 112][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/shopengine/core/elementor-controls/init.php(42): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-05-22 06:31:49 [notice X 114596][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-22 06:40:41 [notice X 7780][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-16 20:02:13 [notice X 9][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(247): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-16 20:02:13 [notice X 9][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/class-jet-elements-integration.php(285): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-16 20:02:13 [notice X 9][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-16 20:02:13 [notice X 9][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/jet-elements/includes/modules/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-16 20:02:13 [notice X 9][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/shopengine/core/elementor-controls/init.php(38): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-16 20:02:13 [notice X 9][/data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L'argomento $control_id è deprecato dalla versione 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /data/wordpress/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /data/wordpress/htdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /data/wordpress/htdocs/wp-content/plugins/shopengine/core/elementor-controls/init.php(42): Elementor\Controls_Manager -> register_control()
',
)]

JS: showing 2 of 2JS: 2022-05-13 11:37:05 [error X 4][https://www.hermandia.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1044\") has already been destroyed and cannot be used. 
JS: 2022-05-13 11:37:06 [error X 1][https://www.hermandia.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1070\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetProductGallery For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	JetWooBuilder For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by m1ga** [comment]
I don't think that `apply_builder_in_content` will load the editor part. 
Try a caching plugin and serve static pages, combine css/js files and lazy load your images. You serve around 5mb at startup and 205 requests. I'm sure that will already boost your stats alot

**Comment by v1lle1** [comment]
Hi! Thanks for your reply. We are using Seravo as hosting provider (https://seravo.com/en/) and cache is handled by them. They have researched this issue a lot with Tideways (https://tideways.com/) and they see that only this one row is loading. So the problem is not about minor optimization things, they can see clearly that is just 1 Elementor hook that is loading.

**Comment by m1ga** [comment]
@rami-elementor thanks for the clarification about the function. I guess you should tell the Seravo people that they shouldn't tell clients that its loading the editor with that function :smile:
