### ISSUE TITLE
IPad and Safari free Elementor Tablet breakpoint Engaging.

### ISSUE THREAD

**Issue by PowerUser1234** [elementor/elementor#19195]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

**My Apple IPad has a software number of 15.5, is an IPad 8th generation, and has had its software fully updated.**

A# On the one hand, I seem to have an Apple IPad which is recent enough. On the other, it has 'aA',
"breakpoint" options for Desktop and Mobile, but not one for Tablet, which is needed.

B# I am both perplexed and vexed. I want all three (3) breakpoints to be used on each of my WordPress
free Elementor Pages. At least, that's what I presently believe I need. Why don't my Tablet breakpoints get
uniquely latched onto and their corresponding page attributes loaded, by Safari, on the very
Apple IPad that I have described, **when an Apple IPad is a Tablet?**

**C# My Safari doesn't seem to have the specific Tablet breakpoint option. Why is this, given its relevant
version numbers included here, previously? For my particular IPad described here, is there anything
simple that can be done to fix this situation with its instance of Safari?** 

### Steps to reproduce

Simply creating a WordPress Page, allocating it to free Elementor, setting the "breakpoint" to tablet mode, and putting
some unique content into the tablet mode, and trying to locally load the WordPress page on Safari, on the described 
Apple IPad, with wireless networking enabled.

It loads the Desktop version of the page, but not the Tablet version of the page.  How on Earth?????

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/7.4.27
	MySQL version: mariadb.org binary distribution v10.4.22
	PHP Version: 7.4.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://192.168.1.108:4443/wordpress
	Home URL: https://192.168.1.108:4443/wordpress
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 9.5
	Admin Email: poweruserweb@protonmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

== Active Plugins ==
	Big File Uploads
		Version: 2.0.3
		Author: Infinite Uploads

	Change Admin Email Setting Without Outbound Email
		Version: 3.1
		Author: John Dee

	Download Plugin
		Version: 2.0.4
		Author: metagauss

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.6.2
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.1.8
		Author: WPDeveloper

	FileBird Lite
		Version: 5.0.1
		Author: Ninja Team

	Ninja Forms
		Version: 3.6.12
		Author: Saturday Drive

	Options for Twenty Twenty-One
		Version: 1.6.6
		Author: Webd Ltd

	Remove "Powered by Wordpress"
		Version: 1.4.6
		Author: Webd Ltd

	Responsive Pagination
		Version: 1.4.1
		Author: Bagus Sasikirono

	Shape Dividers Plus
		Version: 1.2.2
		Author: Marcus Burnette

	Wicked Folders
		Version: 2.18.14
		Author: Wicked Plugins

	WPvivid Backup Plugin
		Version: 0.9.74
		Author: WPvivid Team

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive

== Log ==
	
PHP: showing 4 of 4PHP: 2022-03-15 18:42:45 [notice X 1564][/Applications/AMPPS/www/beta/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 12:16:18 [notice X 6480][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 13:18:40 [notice X 6][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\managers\image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-25 15:09:35 [notice X 3][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 302022-04-14 14:58:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 14:58:43 [info] elementor::elementor_updater Started 
2022-04-14 14:58:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 14:58:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 14:58:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-30 14:46:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-30 14:46:18 [info] elementor::elementor_updater Started 
2022-04-30 14:46:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-30 14:46:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-30 14:46:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-10 13:35:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-10 13:35:28 [info] elementor::elementor_updater Started 
2022-06-10 13:35:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-10 13:35:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-10 13:35:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-10 13:35:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-10 14:53:04 [info] elementor::elementor_updater Started 
2022-07-10 14:53:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-10 14:53:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-10 14:53:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]

JS: showing 6 of 6JS: 2022-03-26 03:40:17 [error X 3][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.1:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_image_gallery_link_one_url` value. Expected array or object.',
)]
JS: 2022-03-26 03:40:17 [error X 3][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.1:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_image_gallery_link_two_url` value. Expected array or object.',
)]
JS: 2022-03-31 08:30:53 [error X 1][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:363181] this.container is undefined 
JS: 2022-04-05 07:08:06 [error X 1][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:338291] this.config.document is undefined 
JS: 2022-04-05 08:40:51 [error X 1][https://localhost:4443/wordpress/wp-content/plugins/premium-addons-for-elementor/assets/editor/js/premium-cross-cp.js?ver=4.9.4:13:21] b is null 
JS: 2022-04-07 05:42:15 [error X 6][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:0] Permission denied to access property \"elementorFrontend\" on cross-origin object 

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified

**Comment by m1ga** [comment]
please go to http://whatismyscreenresolution.net/  and check the output

**Comment by PowerUser1234** [comment]
Dear Michael,

I have done what you have suggested through my IPad 2, and have found:

Apple IPad 2: Screen Resolution: 810x1080, WxH

Asus WideScreen Monitor:  1920x1200, WxH

Benq "Square" Monitor: 1280x1024, WxH

Motorla g 5 g Plus SmartPhone: 414x966, WxH

Is this resolution typical of most Tablets out there?

I want Mobile, Tablet and Desktop WxH settings that will both work locally to me,
and that would work on the internet wordwide, if possible.  At the moment,
my Apple IPad free Elementor Numbers aren't getting "latched on to" by my Apple unit.

What changes do you recommend I make from here, and why?


Yours Sincerely,

Zachary Mitchell.

Z.M.

________________________________

**Comment by m1ga** [comment]
The normal tablet breakpoint is at 1024:

![Screenshot_20220719_112601](https://user-images.githubusercontent.com/4334997/179717267-3aee6651-66b6-4eca-8bd1-3fced747e040.png)

because that is the main tablet resolution. As you can can see: you ipad 10.2 tablet is bigger. Change the breakpoint

**Comment by PowerUser1234** [comment]
Dear Michael,

-On top of everything else so far, you mentioned that I have a
'your ipad 10.2'

-I in fact have iPadOS 15.5, on an IPad 8th generation.

-I am after Mobile, Tablet and Desktop breakpoints that will work on all my screens, and will work for the
vast majority of similar devices and/or screens on the live internet.

-What I need is the correct breakpoint number for Tablet, as described in your included image attachment.
 Unless there is a group of numbers which comes recommended for what I am aiming for, in total.

Can you please reply to me with appropriate values to use, and clear description(s) about where to put them,
to have all three (3) breakpoints working for me, as described, kindly, please?


Yours Sincerely,

Zachary Mitchell.

Z.M.



________________________________

**Comment by m1ga** [comment]
sorry, this is not a real-time chat, don't have to answer right away.
I don't have an answer. I'll leave it to other people to find a solution.

**Comment by PowerUser1234** [comment]
Dear Michael,

My SysInfo file may be viewed here:

https://pastebin.com/bwittS47

I am trying to experiment with Breakpoint numbers on each page,
editing of course with free Elementor 3.6.7, being the values that
can pop up in the top right number, but am encountering problems.

***********************************************
Attempt Replacements:

Desktop W: 1280  H: 1024

Tablet W: 810  H: 1080

Mobile W: 360 H: 736
***********************************************

I can't get these numbers to save in and be taken. They
just wash off, and the Width and Height settings just revert
back to their previous default values.  I am using free Elementor,
and do need to stick with that.  Is there some other way for me
to edit these Width and Height values, and have them taken,
updated and remembered successfully, without them getting
ignored and reverting back?


Yours Sincerely,

Zachary Mitchell.

Z.M.
________________________________

**Comment by rami-elementor** [comment]
Hi @PowerUser1234 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
