### ISSUE TITLE
⛔ 🐞 Bug report: JS error in editor when trying to change a section column width 

### ISSUE THREAD

**Issue by artkrsk** [elementor/elementor#19190]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to change a column width inside a section using visual resize handles or by entering "Column Width" value manually, there appears a JS error in console:

```
web-cli.min.js?ver=3.6.7:3 TypeError: Cannot read properties of undefined (reading 'renderer')
    at SetDirectionMode.getConditions (editor-document.min.js?ver=3.6.7:3:209770)
    at SetDirectionMode.run (editor-document.min.js?ver=3.6.7:3:372171)
    at Ui.runCallback (web-cli.min.js?ver=3.6.7:3:110023)
    at Ui.runCallbacks (web-cli.min.js?ver=3.6.7:3:106655)
    at Ui.run (web-cli.min.js?ver=3.6.7:3:106371)
    at Hooks.run (web-cli.min.js?ver=3.6.7:3:101387)
    at Hooks.runUIAfter (web-cli.min.js?ver=3.6.7:3:102373)
    at Settings.onAfterRun (editor-document.min.js?ver=3.6.7:3:355804)
    at Settings.onAfterRun (editor-document.min.js?ver=3.6.7:3:81139)
    at onAfter (editor-document.min.js?ver=3.6.7:3:354270)
```

### Steps to reproduce

1. Create a new section with 2 columns or more in Elementor editor.
2. Attempt to change "Column Width" value or resize the columns.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://test.dev.local
	Home URL: https://test.dev.local
	WP Multisite: Yes
	Max Upload Size: 146 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: art.krsk@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Envato Theme Check
		Version: 1.0.0
		Author: Scott Parry

	Monster Widget
		Version: 0.3
		Author: Automattic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP Reset PRO
		Version: 6.00
		Author: WebFactory Ltd

== Network Plugins ==
	Multisite Plugin Manager
		Version: 3.1.6
		Author: Aaron Edwards

	Safe SVG
		Version: 2.0.2
		Author: 10up

<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: title in /Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/core/experiments/experiments-reporter.php on line <i>89</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>412248</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-admin/admin.php' bgcolor='#eeeeec'>.../admin.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.1891</td><td bgcolor='#eeeeec' align='right'>8400384</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-admin/admin.php' bgcolor='#eeeeec'>.../admin.php<b>:</b>259</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1891</td><td bgcolor='#eeeeec' align='right'>8400760</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-includes/plugin.php' bgcolor='#eeeeec'>.../plugin.php<b>:</b>476</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1891</td><td bgcolor='#eeeeec' align='right'>8400760</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>331</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.1891</td><td bgcolor='#eeeeec' align='right'>8401888</td><td bgcolor='#eeeeec'>Elementor\Modules\System_Info\Module->display_page(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>307</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.6907</td><td bgcolor='#eeeeec' align='right'>8684696</td><td bgcolor='#eeeeec'>Elementor\Modules\System_Info\Module->print_report(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/modules/system-info/module.php' bgcolor='#eeeeec'>.../module.php<b>:</b>166</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.6907</td><td bgcolor='#eeeeec' align='right'>8685120</td><td bgcolor='#eeeeec'>require( <font color='#00bb00'>'/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/modules/system-info/templates/raw.php'</font> )</td><td title='/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/modules/system-info/module.php' bgcolor='#eeeeec'>.../module.php<b>:</b>320</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>1.1753</td><td bgcolor='#eeeeec' align='right'>8694704</td><td bgcolor='#eeeeec'>Elementor\Core\Experiments\Experiments_Reporter->print_raw(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/modules/system-info/templates/raw.php' bgcolor='#eeeeec'>.../raw.php<b>:</b>13</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>1.1753</td><td bgcolor='#eeeeec' align='right'>8694704</td><td bgcolor='#eeeeec'>Elementor\Core\Experiments\Experiments_Reporter->get_report(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/modules/system-info/reporters/base.php' bgcolor='#eeeeec'>.../base.php<b>:</b>95</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>1.1754</td><td bgcolor='#eeeeec' align='right'>8695160</td><td bgcolor='#eeeeec'>Elementor\Core\Experiments\Experiments_Reporter->get_raw_experiments(  )</td><td title='/Users/art/Local Sites/dev/app/public/wp-content/plugins/elementor/modules/system-info/reporters/base.php' bgcolor='#eeeeec'>.../base.php<b>:</b>148</td></tr>
</table></font>

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @artkrsk,

Thank you for reaching out, and for being so patient! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This issue does not occur using the latest versions of Elementor (v3.11.5), and Elementor Pro (3.11.6).

### ✅ What you can do to solve your issue:
- Update to the latest version of Elementor.

### 👍 For now, that's all we can help with. ]

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
