### ISSUE TITLE
🚀 Feature Request: Ability to use several dynamic tags in one place (For example, title widget, text editor, icon list or...)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19204]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team!

As you know, dynamic tag feature in elementor is great and needed. But there is this limitation that we cannot use several dynamic tags in one widget and only 1 dynamic tag is allowed.
So it would be great if you add the ability to use multiple dynamic tags in one place to elementor. Dynamic content is something you should not neglect. Because it is a feature that all plugins and developers are developing these days.

### Describe the solution you'd like

**Ability to use multiple dynamic tags in one place**
With the addition of this feature, it is enough to select the desired text and then apply the desired dynamic tag to it. In the same way, we can repeat this action several times in a widget. Even to open or close the popup.

**Comment by mcrowell** [comment]
+1

**Comment by Michaelgimii** [comment]
+1 This is really great.

**Comment by elasticeye** [comment]
This is a good suggestion! +1

**Comment by arielk** [comment]
Duplicate of #19402

**Comment by leorcdias** [comment]
+1 I miss this feature a lot when I'm going to do projects for clients... I wonder why they haven't implemented this yet 🤔

**Comment by jgarcianewemage** [comment]
its BAFFLING why you can't just do %post_ID% %category%
they won't add this because you can already add custom tags or a shortcode :-1:  don't know if because they are lazy or dont care.

we have waiting 6 years to add class to a "current" page they says "nah you dont want this, add it to the first section or whatever"

**Comment by AlexSubZero** [comment]
any update on this?
