### ISSUE TITLE
🐞 Bug report:  CSS console errors

### ISSUE THREAD

**Issue by sinanisler** [elementor/elementor#19210]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

console errors for -1px media query :)

from font-end-css

![image](https://user-images.githubusercontent.com/1686324/179982406-ac19de5c-1aac-4473-bd83-c103f51f2bf1.png)

![image](https://user-images.githubusercontent.com/1686324/179982551-65121614-8d30-4430-b64b-b1e13b85c10f.png)

### Steps to reproduce

console errors for -1px media query :)

from font-end-css

![image](https://user-images.githubusercontent.com/1686324/179982406-ac19de5c-1aac-4473-bd83-c103f51f2bf1.png)

![image](https://user-images.githubusercontent.com/1686324/179982551-65121614-8d30-4430-b64b-b1e13b85c10f.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

localhost clean install

**Comment by rami-elementor** [comment]
Hi @sinanisler 

Couldn't recreate and couldn't find `min-width: -1px` in Elementor and Elementor Pro.

**Comment by sinanisler** [comment]
hmm and i dont remember which dev env i was working on. 🤣
i am working lots of parallel project right now.

i will close the issue for now. 
if i see this again i will add a demo link here too.
