### ISSUE TITLE
✅ 🐞 Bug report: Slides widget navigation points are displayed very slowly.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19221]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I really don't know why. But when the user enters the website, the navigation points of the slides widget are loaded much later than other content. Even two or three seconds later.
This is really noticeable. Please check it out.

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.25.0! 🥳 

The Slides widget now uses modern CSS and doesn't require loading of icons for the navigation dots. Making it much faster to load.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
