### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Icon alignment control for icon list widget (Duplicate of #16056) - [ED-9265]

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19237]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In the icon list widget, if the number of lines is greater than 1, the icon will be placed in the text border by default. : https://prnt.sc/oi-_sZ3isgaq
This is really annoying. If possible, please add a new feature to this widget, so we can set the icon position vertically. Display at the [top, center, or bottom of the text](https://prnt.sc/A9mi9f6WAdOj). This is really needed

### Describe the solution you'd like

**Vertical control of icon position in the icon list widget**

**Comment by perks98** [comment]
This is a mix of a bug and feature request. The icon used to align to the top, but since a certain update a long time ago it defaults to center and they refused to update to fix when it happened so it became the new noraml. I fully support this request +1

**Comment by simonclay** [comment]
Completely agree. It's rubbish that everyday users cannot align the icons to the top when a list item has multiple lines.

I add a class `.align-icons-top` to the widget and add this to the Customiser:
```
.align-icons-top .elementor-icon-list-icon {
        align-self: start;
    padding-top: 0.4em;
}
```

It's a bit sad having to instruct non techie editors to add a class to a widget when they want to align an icon.

**Comment by perks98** [comment]
I had done a pull request (first time doing one) for this issue to add vertical top, center, and bottom responsive alignment control for the icon in the icon list widget in #19365 ~ hopefully they might consider it or implement a better solution to that. I haven't touched PHP in 5 years but wanted to look through Elementor's developers docs and found it relatively simple to add that extra option.

But there might need to be more thought added to it, like in @simonclay CSS added padding so it wasn't at the absolute top, so maybe a slider option for spacing is needed depending if set to top or bottom.
