### ISSUE TITLE
🐞 Bug report: Critical error when updating blogname and blogdescription via ACF options page

### ISSUE THREAD

**Issue by bugnumber9** [elementor/elementor#19239]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I created a custom options page via ACF to allow certain non-admin roles to customize Site Title and Tagline.
I added something like this in my custom plugin:

```
function my_custom_site_options() {
	$old_site_name = get_option( 'blogname' );
	$new_site_name = get_field( 'site_name', 'options' );

	if( $old_site_name !== $new_site_name ) {
		update_option( 'blogname', $new_site_name, true );
	}
}
add_action( 'admin_init', 'my_custom_site_options' );
```

Upon non-admin user saving options on that custom page, a fatal PHP error happens:

`PHP Fatal error: Uncaught Exception: Access denied. in .../wp-content/plugins/elementor/core/settings/page/manager.php:105`

I believe the bug is somewhat similar to https://github.com/elementor/elementor/issues/12662

### Steps to reproduce

See above

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

N/A

**Comment by rami-elementor** [comment]
Hi @bugnumber9 

**elementor/core/settings/page/manager.php:105**

```php
		if ( ! Utils::is_wp_cli() && ! current_user_can( 'edit_post', $id ) ) {
			throw new \Exception( 'Access denied.', Exceptions::FORBIDDEN );
		}
```

I don't know your full code, but according to the details you provided here you are trying to give access to non-admin users that have no permission to edit settings. It will throw an exception as the user have no permission to do that. This is a serious security breach that can create an attack vector to malicious parties.

**Comment by bugnumber9** [comment]
@rami-elementor I understand your point of view, however, I'm concerned with the following:

1. Despite the PHP error, the "blogname" option gets updated.
2. We have a very specific setup with 1 administrator (trusted) and 1 author (also trusted), and for a number of reasons we want to allow the author to change site name and tagline. I don't see anything wrong with that.
3. Why would Elementor even have anything to do here? In this part of the project we're dealing with ACF, but it's Elementor throwing that error. Elementor itself isn't even involved in what we're trying to do here, but it chimes in and throws an error.

That being said, I personally believe that Elementor shouldn't dictate or enforce what we can or can't do, especially when the thing we're doing doesn't even involve Elementor.

**Comment by bugnumber9** [comment]
@rami-elementor BTW, looking at the code, specifically at `if ( ! Utils::is_wp_cli() && ! current_user_can( 'edit_post', $id ) )` part of it. Elementor is checking for wp_cli AND whether current user can edit posts (author role has this capability). Shouldn't it be OR condition instead?

**Comment by rami-elementor** [comment]
> @rami-elementor BTW, looking at the code, specifically at `if ( ! Utils::is_wp_cli() && ! current_user_can( 'edit_post', $id ) )` part of it. Elementor is checking for wp_cli AND whether current user can edit posts (author role has this capability). Shouldn't it be OR condition instead?

The check is whether it's NOT WPCLI **and** whether the user DON'T have edit capabilities. It can't be **or**.

**Comment by bugnumber9** [comment]
@rami-elementor Please consider adding another check "if not ACF options page". As you can see from my description, it doesn't add anything in terms of security because the option still gets updated, but adds extra annoyance when we want to do something not-so-usual ;)
