### ISSUE TITLE
🚀 Feature Request: Ability to create metafields for posts/products - loop builder

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19244]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hello elementor developers

I look forward to the release of loop builder. So I wanted to have a proposal for the development of loop builder. With the release of loop builder, will we still need another plugin like jet engine or acf to create a powerful loop? I mean the possibility of creating metafields for different post types.
Does elementor allow its users to create metafields for posts or WooCommerce? So we can display them in Loop?
In the previews released from the loop builder, it shows metafields that are currently only possible using acf and jet engine. So, I wanted to ask, according to [this image](https://prnt.sc/rF-9UgRjTk6u), elementor adds the possibility to create metafields for post types like posts or products along with loop builder? Or should we still depend on jet engine or acf?

### Describe the solution you'd like

Ability to create metafields for posts and products

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being.

Please feel free to contact us again with other feature suggestions.

Regards,
