### ISSUE TITLE
🚀 Feature Request: Advanced button widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19255]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you add an option to button widget, so we can add multiple buttons in just one button widget. Like the image below, which is implemented in the elementor extras plugin : https://prnt.sc/RLhzDYGvxfiE
This feature can be much more convenient for users. For example, they can place two buttons next to each other.

Another feature that is needed for the button widget is the ability to customize the button in two different situations. Normal and Hover mode. For example, we create a button with the desired text and icon. If the user hover over it, both the text and the icon will change. Especially for the download button this is great. (Also, its style also changes)
These two features are really great for the button.

Please add a variable section to the button, so that if we put a file for download, its size can be displayed to the user. This feature is in the jet element plugin : https://prnt.sc/kB9NaHDpYF1W

### Describe the solution you'd like

1- Ability to add multiple buttons in a button widget
2- Style control + text and icons for normal and hover modes
3- Ability to display the file size in the button widget (If the button is to download a file)

**Comment by drawcard** [comment]
If you are looking to line up buttons in a row, like what you have in your screenshot, you can put them in a column and set them to display inline. Or if you're using the new container widget, you can use the flexbox settings to make them sit in a row.

The button widget already has normal and hover style settings too:
<img width="278" alt="CleanShot 2022-07-25 at 23 53 55@2x" src="https://user-images.githubusercontent.com/1435638/180800346-4fa57c54-d9e6-4bb1-b29a-5fb9ab18176d.png">

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for submitting a feature request. We have decided not to add this to our roadmap. You can drag multiple button widgets to get the same result.

Regards,

**Comment by rami-elementor** [comment]
You opened similar featured requests #18824 #18911

We are not planning to create new widgets that add multiple elements. We are planning to do the opposite, break widgets with multiple elements to smaller elements.
