### ISSUE TITLE
🚀 Feature Request: Duplicate/clone a page/post/template

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#19259]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I often want to duplicate a page or a post. Either for a backup before making changes or to create a new post similar to a previous one.

I know we can create a template, then add the template, but that's really cumbersome, really not straightforward to explain to colleagues, and I don't want to have a lot a new templates I'll only use once or twice.

### Describe the solution you'd like

I'd like a simple button or a like in the page/post listing to duplicate the element. It would create a copy of the element and put it in Draft state.

### Describe alternatives you've considered

I used "create a template" and then add the template in a new post/page. But it's more like a workaround then a really solution.

I also saw a clone/duplicate functionality in plugins, but I don't want to buy/add more plugins. 

### Additional context

I've heard many people looking around for an easy way to duplicate posts/pages/custom posts.

**Comment by hitsgee** [comment]
I get round this by adding some code to my function.php theme file.

This website has a guide and code

https://wpengine.co.uk/resources/how-to-duplicate-page-wordpress/#Duplicating_a_Page_in_WordPress_Without_a_Plugin

Your best using a child theme with this method though so it doesn't get rewritten with every update.

**Comment by rami-elementor** [comment]
Hi @vgstef,

You have many WordPress plugins that do exactly that.

This feature should be a WordPress Core feature request, not an Elementor feature.

I'm closing this request as it's not likely that we will add this to our roadmap.
