### ISSUE TITLE
🐞 Bug report: Image widget bug when enabling Link

### ISSUE THREAD

**Issue by Arian-c27** [elementor/elementor#19278]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When adding an image to the page, users can add a Width on the Style tab e.g 100%

This works correctly, unless on the "Content" tab you enable Link.
In that case the img is inserted inside an anchor element which has inline-block display. This prevents the image to extend to 100% width of the container.

Without link enabled
https://www.awesomescreenshot.com/image/30699512

With link enabled
https://www.awesomescreenshot.com/image/30699860

### Steps to reproduce

Add image widget inside container, enable Link and on the style tab set width to 100%

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					

== Theme ==
	Name: Voxel
	Version: 0.9.3-beta.1
	Author: 27collective
	Child Theme: No

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server - GPL v8.0.28
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://192.168.178.55/arian
	Home URL: http://192.168.178.55/arian
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: voxel@test.de
	Debug Mode: Active

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Query Monitor
		Version: 3.9.0
		Author: John Blackbourn

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

**Comment by rami-elementor** [comment]
Links don't work. Closing the issue.

**Comment by Arian-c27** [comment]
I have updated the images. There's also clear instructions provided, not a complex bug to reproduce

**Comment by Arian-c27** [comment]
> Links don't work. Closing the issue.

I have updated the images. There's also clear instructions provided. Should I post this again or can you open it? It's a small issue that has been there for months now.
