### ISSUE TITLE
🐞 Bug report: Star Rating widget doesn't show the WooCommerce rating correctly

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19283]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi
I am using this widget in my customers store. When a customer leaves a review for the product, and rates 5 stars, only one star of this widget will be filled! While all the stars must be filled. Because only one user has registered a comment and rated 5 stars. Please check this thread.

### Steps to reproduce

On the single product page, add the Star Rating widget. Also add a comment section. As a guest user, write a review for one of the products and rate 5 stars. After accepting the registered review (as an admin) if you look closely at the product page, only one star will be displayed and this can be very bad for a store website.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @79ho3ein how are you doing?

Can you please confirm if you were talking about the Product Rating widget instead of the Star Rating (now legacy) widget?

Kind regards

**Comment by 79ho3ein** [comment]
Hi @nicholaszein, great, how are you?

Honestly, I could not check the Pro version in the new version. But I'm a bit confused about the new scoring widget.
Is this a new widget? Or is the former widget developed? In this issue, I mentioned the star rating widget. Is the new star rating widget compatible with WooCommerce? I am well versed in the details of Elementor. But it's strange why I'm confused about the new widget.

**Comment by nicholaszein** [comment]
Hi @79ho3ein!

I'm good! Thank you for asking! 🙏 

This is a completely new widget created from the ground up using better code, making it accessible and compatible with the Container element. It replaces the old widget altogether and adds some styling features that were long requested, like custom icons, custom values, correctly displaying decimal values, and better support for Google rich snippets. 

However, it does not add any additional dynamic capabilities like support for WooCommerce Product Ratings, which the old widget did not support as well. So in the case of this bug report, it should be more of a feature request, as the compatibility is not possible yet, and would require implementing a new Dynamic Tag. However, it does support custom fields.

The old widget was beyond fixing. It did not have the infrastructure to add the functionality this widget has.

I think this means you might need to submit a new feature request if you think this should be implemented.

Let me know if this clarifies your questions.

Regards

**Comment by 79ho3ein** [comment]
>Let me know if this clarifies your questions.

Thanks for the full explanation Nicholas.

You are right. I think I need to add a new request to support Woocommerce review. I just checked this widget and there seems to be a problem with the RTL.

![Screenshot](https://github.com/elementor/elementor/assets/77163248/7d9939d1-befd-4468-91f4-dec11d833941)

Do need to create a new bug report for this bug?

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

apologies for the delay. 🙏 

We've been working hard behind the scenes to finalize the Feature Request triaging and migration to the new Discussions Category. We're almost ready to finalize the entire process.

Regarding RTL support, I saw you submitted a new issue, and I'll answer you there.

Regarding this issue, the Start Rating (legacy) widget, as well as the new Rating widget, don't support WooCommerce ratings. You need to use the [Product Rating](https://elementor.com/help/woocommerce-single-product-rating-pro/) widget.

I'm closing this issue as Not Supported.

Kind regards
