### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by stephroseg** [elementor/elementor#19316]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have upgraded a dev site to Pro 3.7.3 - which contains bug #18357 - I belive this fix has broken my header 

I use the hello-elementor theme and a custom child theme that has very minimal styling and css in it currently.

It is not a sticky header. 

### Steps to reproduce

Upgrade to Elementor Pro 3.7.3 and Elementor 3.6.8 
Header breaks
after screenshot: 
<img width="769" alt="after" src="https://user-images.githubusercontent.com/41652802/182068588-773996d6-0190-46e7-a4df-883e6caa3815.png">

before screenshot 
<img width="1382" alt="before" src="https://user-images.githubusercontent.com/41652802/182068596-1afa223c-4184-49a1-9d21-85207377fc2e.png">

Rollback the site to a version before the eliminator plugin updates and pro updates 

Site header back to normal after rollback 

update all other plugins 

header still works 

Upgrade elementor again 

Header breaks

screenshot of the header ( which is broken as per the after screenshot) as it appears in the elementor page designer 
<img width="1706" alt="preview in designer ( after)" src="https://user-images.githubusercontent.com/41652802/182068867-930f8212-c2a8-47fe-90ab-74d2c19255df.png">

 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v10.6.7
	PHP Version: 8.0.17
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://ecodev.rockingrose.technology
	Home URL: https://ecodev.rockingrose.technology
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 0
	Admin Email: user@example.com
	Debug Mode: Inactive

== Theme ==
	Name: ecoporium child theme
	Version: 1.0.1
	Author: Rocking Rose Pty Ltd
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	ActiveCampaign
		Version: 8.1.10
		Author: ActiveCampaign

	Advanced Custom Fields
		Version: 5.12.3
		Author: Delicious Brains

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.8
		Author: WPDeveloper

	Graphina - Elementor Charts and Graphs
		Version: 1.7.7
		Author: Iqonic Design

	hCaptcha for Elementor Forms
		Version: 1.0.0
		Author: xisonc

	hCaptcha for Forms and More
		Version: 1.17.0
		Author: hCaptcha

	List category posts
		Version: 0.86.1
		Author: Fernando Briano

	Ninja Tables
		Version: 4.2.0
		Author: WPManageNinja LLC

	Ninja Tables Pro
		Version: 4.2.0
		Author: WPManageNinja

	TaxoPress
		Version: 3.6.3
		Author: TaxoPress

	Twenty20 Image Before-After
		Version: 1.5.8
		Author: Zayed Baloch

	WP All Export Pro
		Version: 1.7.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.7.5
		Author: Soflyy

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		form : 2
		heading : 4
		image-gallery : 2
		nav-menu : 2
	header : 2
		nav-menu : 1
		theme-site-logo : 1
	page : 1
		heading : 1
		image : 4
		spacer : 1
	popup : 1
		button : 1
		text-editor : 1
	wp-page : 11
		counter : 2
		donut_chart : 1
		eael-image-accordion : 1
		form : 2
		google_maps : 1
		heading : 27
		icon-box : 1
		icon-list : 1
		image : 4
		image-gallery : 1
		nav-menu : 1
		posts : 1
		progress : 2
		spacer : 12
		tabs : 1
		text-editor : 17
		twenty20 : 1
	single-post : 4
		author-box : 1
		button : 2
		divider : 1
		heading : 10
		image : 1
		post-info : 2
		post-navigation : 2
		posts : 2
		social-icons : 1
		spacer : 8
		text-editor : 3
		theme-post-content : 3
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 2
		video : 1
		wp-widget-listcategorypostswidget : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 292022-06-19 22:37:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-19 22:37:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-19 22:37:06 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-19 22:37:06 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-19 22:37:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-11 02:47:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-11 02:47:06 [info] elementor::elementor_updater Started 
2022-07-11 02:47:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-11 02:47:07 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-11 02:47:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-31 23:38:32 [info] elementor::elementor_updater Started 
2022-07-31 23:38:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-31 23:38:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-31 23:38:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-31 23:38:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-31 23:46:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-07-31 23:46:22 [info] elementor-pro::elementor_pro_updater Started 
2022-07-31 23:46:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-07-31 23:46:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-31 23:46:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

PHP: showing 10 of 10PHP: 2022-05-29 00:19:59 [warning X 73][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-29 01:00:46 [error X 3][/bitnami/wordpress/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /bitnami/wordpress/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /opt/bitnami/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#7 /bitnami/wordpress/wp-content/plugins/elementor/modules/system-info/module.php(335): do_action()
#8 /bitnami/wordpress/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /bitnami/wordpress/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /bitnami/wordpress/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#12 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#13 /opt/bitnami/wordpress/wp-includes/plugin.php(524): WP_Hook->do_action()
#14 /opt/bitnami/wordpress/wp-cron.php(138): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-30 00:16:49 [error X 4][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /opt/bitnami/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /opt/bitnami/wordpress/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-30 04:49:30 [warning X 75][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-01 05:44:27 [warning X 17183][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-02 06:48:28 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::270] Undefined array key "post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-08 09:38:50 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined array key "new_version" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-20 22:40:22 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::1239] Undefined array key "type" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-22 02:42:12 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "http://bd-staging.rockingrose.technology/wp-content/uploads/2022/05/phone-icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-01 03:20:27 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-06-01 05:03:46 [error X 13][https://bd-staging.rockingrose.technology/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-06-20 22:40:28 [error X 5][https://bd-staging.rockingrose.technology/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:21771] Cannot read properties of undefined (reading \'global\') 
JS: 2022-08-01 00:23:55 [error X 1][https://bd-staging.rockingrose.technology/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.8:3:706566] elementorFrontend is not defined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible
	Graphina - Elementor Charts and Graphs: Compatible
	hCaptcha for Elementor Forms: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible
	Graphina - Elementor Charts and Graphs: Incompatible

**Comment by shilo-ey** [comment]
Hey @stephroseg 

Thank you for reporting this issue.

Unfortunately, we couldn't reproduce this issue.

I suggest you contact Elementor Pro support for further examination of the issue you encountered. 

Thanks.
