### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by melissamcgraw** [elementor/elementor#19335]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

there is one page that the entirety of content is built on elementor and it will not let me access elementor. all other pages are working just fine with elementor. 

This page has content entirely made of buttons.

### Steps to reproduce

I dont know, without access to my page it is unlikely.

I created the page content entirely of buttons on an old version of elementor, today i updated elementor and went in to edit that page and the elementor editor will not open. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://www.saddleranchptio.org
	Home URL: http://www.saddleranchptio.org
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Denver
	Admin Email: you@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hestia
	Version: 3.0.23
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0
		Author: Automattic

	Elementor
		Version: 3.8.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.12
		Author: Brainstorm Force, Nikhil Chavan

	Folders
		Version: 2.8.2
		Author: Premio

	GA Google Analytics
		Version: 20220517
		Author: Jeff Starr

	Gutenberg
		Version: 13.7.3
		Author: Gutenberg Team

	Hummingbird
		Version: 3.3.4
		Author: WPMU DEV

	Menu Icons
		Version: 0.12.12
		Author: ThemeIsle

	Orbit Fox Companion
		Version: 2.10.13
		Author: Themeisle

	Smush
		Version: 3.10.3
		Author: WPMU DEV

	TablePress
		Version: 1.14
		Author: Tobias Bäthge

	The Events Calendar
		Version: 5.16.3.1
		Author: The Events Calendar

	Ultimate Category Excluder
		Version: 1.6
		Author: Marios Alexandrou

	UpdraftPlus - Backup/Restore
		Version: 1.22.14
		Author: UpdraftPlus.Com, DavidAnderson

	Widget Options
		Version: 3.8.5
		Author: Widget Options Team

	Wordfence Security
		Version: 7.6.0
		Author: Wordfence

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Browser Cache
		Version: 0.4
		Author: Mike Hansen

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	Endurance PHP Edge
		Version: 0.2
		Author: Mike Hansen

	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 412022-06-08 06:53:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-08 06:53:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-08 06:53:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-08 06:53:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-03 18:37:01 [info] elementor::elementor_updater Started 
2022-07-03 18:37:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-03 18:37:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-03 18:37:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 20:33:46 [info] elementor::elementor_updater Started 
2022-07-27 20:33:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 20:33:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 20:33:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 20:33:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-02 14:53:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.8.0-dev1',
)]
2022-08-02 14:53:07 [info] elementor::elementor_updater Started 
2022-08-02 14:53:07 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-02 14:53:07 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-02 14:53:07 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-08-02 14:53:07 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-08-02 14:53:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.8.0-dev1',
)]

JS: showing 1 of 1JS: 2022-07-28 02:34:42 [error X 4][http://www.saddleranchptio.org/wp-content/plugins/elementor/assets/js/webpack.runtime.min.js:2:153] a[e] is not a function 

PHP: showing 1 of 1PHP: 2022-08-02 16:18:05 [notice X 1][/home4/saddlera/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible

**Comment by rami-elementor** [comment]
Hi @melissamcgraw ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
