### ISSUE TITLE
🚀 Feature Request: nested alert widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19342]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hello elementor developer
Please develop nested alert widget. In this case, we can customize the content of the alert widget. This is something we cannot do now. The ability to customize the content of the alert widget is great because we can create beautiful and completely customized notifications.

### Describe the solution you'd like

nested alert widget

**Comment by rami-elementor** [comment]
Why not using the current "Alert Widget"?

**Comment by Michaelgimii** [comment]
@rami-elementor , Now this widget is very limited. We can only display a plain text. So if we want to create [something like elementor website](https://prnt.sc/vWUGnofoM5Jm) in elementor, we will not be able to create it.
But the nested alert feature will allow us to display any desired widget in the alert. Fully customized.

**Comment by rami-elementor** [comment]
@Michaelgimii The element in the link you provided is not an alert it's an Elementor Popup.

**Comment by rami-elementor** [comment]
I'm closing this request as you can create this with Elementor and we are not planning to create nested alert.

**Comment by rami-elementor** [comment]
GitHub is not the channel for those link of question but try playing with your **Popups Settings**. Remove the overlay and position the popup at the top of your screen. Maybe extra JS/CSS will be required.

Also, try looking for similar popups in the template/popup library.
