### ISSUE TITLE
Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/u871251863/domains/euromaxs.com/public_html/wp-includes/functions.php on line 5379🐞 Bug report: 

### ISSUE THREAD

**Issue by euromax11** [elementor/elementor#19355]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/u871251863/domains/euromaxs.com/public_html/wp-includes/functions.php on line 5379

### Steps to reproduce

Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/u871251863/domains/euromaxs.com/public_html/wp-includes/functions.php on line 5379

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.12
	PHP Version: 7.2.34
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://www.euromaxs.com
	Home URL: https://www.euromaxs.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: euromaxs35@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Besa Child
	Version: 1.0
	Author: Thembay
	Child Theme: Yes
	Parent Theme Name: Besa
	Parent Theme Version: 2.1.3
	Parent Theme Author: Thembay

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	AliDropship Woo Plugin
		Version: 1.6.46
		Author: Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin & Denis Zharov

	All-in-One WP Migration
		Version: 7.62
		Author: ServMask

	All-in-One WP Migration File Extension
		Version: 1.8
		Author: ServMask, Inc.

	CMB2
		Version: 2.10.1
		Author: CMB2 team

	Contact Form 7
		Version: 5.6.1
		Author: Takayuki Miyoshi

	Customer Reviews for WooCommerce
		Version: 5.1.2
		Author: CusRev

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.18
		Author: Facebook

	Google Listings and Ads
		Version: 2.0.2
		Author: WooCommerce

	LiteSpeed Cache
		Version: 5.1
		Author: LiteSpeed Technologies

	MC4WP: Mailchimp for WordPress
		Version: 4.8.7
		Author: ibericode

	Pinterest for WooCommerce
		Version: 1.2.1
		Author: WooCommerce

	Site Kit by Google
		Version: 1.80.0
		Author: Google

	Slider Revolution
		Version: 6.5.14
		Author: ThemePunch

	Template Library and Redux Framework
		Version: 4.3.15
		Author: Extendify

	Thembay Elementor
		Version: 1.1.10
		Author: Team Thembay

	Variation Swatches for WooCommerce
		Version: 2.0.6
		Author: Emran Ahmed

	White Label CMS
		Version: 2.3
		Author: www.videousermanuals.com

	WooCommerce
		Version: 6.7.0
		Author: Automattic

	WooCommerce Google Analytics Integration
		Version: 1.5.11
		Author: WooCommerce

	WooCommerce Payments
		Version: 4.5.0
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.9.1
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 6.5.1
		Author: WooCommerce

	WOOF - WooCommerce Products Filter
		Version: 2.2.6.4
		Author: realmag777

	WP Reset
		Version: 1.95
		Author: WebFactory Ltd

	YITH WooCommerce Wishlist
		Version: 3.11.0
		Author: YITH

	Yoast SEO
		Version: 19.4
		Author: Team Yoast

<br />
<b>Notice</b>:  Undefined index: publish in <b>/home/u871251863/domains/euromaxs.com/public_html/wp-content/plugins/elementor/modules/usage/module.php</b> on line <b>79</b><br />

== Elements Usage ==
	
	page : 2
		besa-brands : 1
		besa-heading : 1
		besa-product-recently-viewed : 1
		button : 1
	wp-post : 
		besa-account : 4
		besa-brands : 2
		besa-heading : 11
		besa-list-menu : 6
		besa-menu-vertical : 26
		besa-mini-cart : 4
		besa-nav-menu : 8
		besa-newsletter : 1
		besa-product-recently-viewed : 4
		besa-search-form : 4
		besa-site-logo : 4
		besa-wishlist : 4
		button : 6
		divider : 1
		image : 7
		spacer : 2
		text-editor : 5
	wp-page : 20
		accordion : 1
		besa-brands : 2
		besa-custom-image-list-categories : 3
		besa-heading : 33
		besa-newsletter : 1
		besa-our-team : 1
		besa-product-categories-tabs : 1
		besa-product-category : 10
		besa-product-flash-sales : 3
		besa-product-recently-viewed : 1
		besa-product-tabs : 1
		besa-products : 3
		besa-testimonials : 1
		besa-title-width-button : 1
		button : 8
		google_maps : 1
		icon : 3
		icon-box : 8
		image : 9
		shortcode : 8
		slider_revolution : 1
		social-icons : 4
		text-editor : 32
		video : 4

<br />
<b>Notice</b>:  Undefined index: title in <b>/home/u871251863/domains/euromaxs.com/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php</b> on line <b>89</b><br />

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
JS: showing 1 of 1JS: 2022-06-24 05:24:40 [error X 2][https://www.euromaxs.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:406242] Cannot read properties of null (reading \'id\') 

Log: showing 10 of 102022-07-23 18:40:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-23 18:40:54 [info] elementor::elementor_updater Started 
2022-07-23 18:40:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-23 18:41:07 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-23 18:41:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 18:01:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 18:01:20 [info] elementor::elementor_updater Started 
2022-07-27 18:01:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 18:01:36 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 18:01:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]

PHP: showing 1 of 1PHP: 2022-07-29 05:45:04 [notice X 53][/home/u871251863/domains/euromaxs.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1004] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Thembay Elementor: Compatibility not specified

**Comment by euromax11** [comment]
How to fix this error

**Comment by rami-elementor** [comment]
Hi @euromax11,

One of the addons on your site is using deprecated code.

We don't have control over 3rd party plugins that don't remove outdated code.

See this developer doc explaining how to fix the issue: https://developers.elementor.com/docs/deprecations/simple-example/

**Comment by muneef1994** [comment]
Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/domain/domaing/wp-includes/functions.php on line 5379. how can i fix this

**Comment by rami-elementor** [comment]
https://github.com/elementor/elementor/issues?q=is%3Aissue+_register_controls+
