### ISSUE TITLE
🚀 Feature Request: seo & social media section in the page settings.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19360]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team

It is true that elementor is a page builder. But it is not bad if it adds very important and specialized features in some sections.
**For example, it would be great if you add seo and social media section in [page settings](https://prnt.sc/yGj9ITxCB7QM).**
Adding this feature would definitely be a huge plus for elementor. Denn dadurch brauchen SEO-Profis in elementor keine weiteren Plugins wie Yoast SEO oder RankMeth. For elementor, what better ad than this?
It should be noted that the bricks page builder already has this feature. But shouldn't elementor users have such a great feature?

**Please see the screenshots below :** 

![screencapture-try-bricksbuilder-io-t7b3ff1b-2022-08-05-21_57_15](https://user-images.githubusercontent.com/88034902/183130181-4dda91df-2886-452f-99f8-4d5b0b870a91.png)
![screencapture-try-bricksbuilder-io-t7b3ff1b-2022-08-05-21_57_55](https://user-images.githubusercontent.com/88034902/183130186-3c88eb5d-99b9-4602-921c-5a9a269376a4.png)

**tip :** If you decide to add these two features to elementor, don't neglect the dynamic tags in these sections. For example, in the SEO title, we can display the current date and many dynamic tags. What is now in the Rank Meth plugin.

I hope you put this on your roadmap.

### Describe the solution you'd like

**seo & social media in page setings**

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being. 

Regards,
