### ISSUE TITLE
✅ 🐞 Bug report: bug in container - Justify Content and Align Items do not change on mobile and tablet mode.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19363]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As you know, if we change the direction of the container, the direction of the Justify Content and Align Items icons will change accordingly. **But if we are in tablet and mobile mode and change the direction of the container, the direction of the Justify Content and Align Items icons will not change.**

### Steps to reproduce

Please watch this video :

https://user-images.githubusercontent.com/77163248/183156790-8c80b59c-2bd4-4bfd-9a4b-88eae116ceb0.mp4

As you can see in the video above, if we change the direction of the container in tablet and mobile mode, the direction of the Justify Content and Align Items icons will not change. **But there is no problem on desktop.**

hi @shilo-ey , Please check this item. thank you

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-2-03-2023.txt](https://github.com/elementor/elementor/files/10865901/system-info-localhost-2-03-2023.txt)

**Comment by 79ho3ein** [comment]
Hi @nicholaszein, Please check this issue. This bug still exists, while the container will be enabled by default in the next release.

thank you!

**Comment by nicholaszein** [comment]
Hello @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.16.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
