### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/

### ISSUE THREAD

**Issue by hirewebsolutions** [elementor/elementor#19367]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Fatal error:  Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /var/...

When edit page with elemetor, it's showing fatal error.

` $settings = $widget->get_data( 'settings' );`

### Steps to reproduce

```
if ( ! class_exists( 'Test_Action_After_Submit' ) ) {
    class Test_Action_After_Submit extends \ElementorPro\Modules\Forms\Classes\Action_Base {
        
        public function get_name() {

            return 'test';
        }

        public function get_label() {

            return esc_html__( 'Test', 'test' );
        }

        public function register_settings_section( $widget ) {

            $widget->start_controls_section(
                'test_section',
                [
                    'label' => esc_html__( 'Test', 'test' ),
                    'condition' => [
                        'submit_actions' => $this->get_name(),
                    ],
                ]
            );
            
            $settings = $widget->get_data( 'settings' );

            $widget->end_controls_section();
        }

        public function run( $record, $ajax_handler ) {

            //
        }

        public function on_export( $element ) {

            //
        }
    }
}
```

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Latest version.

**Comment by hirewebsolutions** [comment]
```
add_action( 'elementor_pro/forms/actions/register', 'test_register_action', 20, 1 );
    function test_register_action( $form_actions_registrar ) {
        
        include_once __DIR__ .  '/action.php';

        $form_actions_registrar->register( new Test_Action_After_Submit() );
    }
```

**Comment by rami-elementor** [comment]
Hi @hirewebsolutions ,

Please read the official developer docs at https://developers.elementor.com/docs/form-actions/

As for your question, we can't debug your code, too much data is missing.

**Comment by hirewebsolutions** [comment]
This is clear Bug and what info you need?

**Comment by hirewebsolutions** [comment]
I purchased PRO
