### ISSUE TITLE
✔️ 🐞 Bug report: Sticky Container doesn't reset the width when the viewport changes size + some padding issues 

### ISSUE THREAD

**Issue by saludstyle** [elementor/elementor#19377]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Here are two bugs of container widget I found, which are really frustrating.
1. The sticky element inside a container will have the following problems: when you narrow down the window to 1111px for example, and then wide up the window, then the sticky element, a sticky header for example, would still keep the width of 1111px.
2. The width problem of the top, boxed container. If the boxed width is set to 1400px, and you give it a padding of 5%. Then, the exact content width is (1400px-10%), and what worse is that, when you narrow down the window under 1400px, then there will be no gap on the left and right edge, which means it misses the 5% of padding. This problem seems only happen on the most out container.

### Steps to reproduce

Here are two bugs of container widget I found, which are really frustrating.
1. The sticky element inside a container will have the following problems: when you narrow down the window to 1111px for example, and then wide up the window, then the sticky element, a sticky header for example, would still keep the width of 1111px.
2. The width problem of the top, boxed container. If the boxed width is set to 1400px, and you give it a padding of 5%. Then, the exact content width is (1400px-10%), and what worse is that, when you narrow down the window under 1400px, then there will be no gap on the left and right edge, which means it misses the 5% of padding. This problem seems only happen on the most out container.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Here are two bugs of container widget I found, which are really frustrating.
1. The sticky element inside a container will have the following problems: when you narrow down the window to 1111px for example, and then wide up the window, then the sticky element, a sticky header for example, would still keep the width of 1111px.
2. The width problem of the top, boxed container. If the boxed width is set to 1400px, and you give it a padding of 5%. Then, the exact content width is (1400px-10%), and what worse is that, when you narrow down the window under 1400px, then there will be no gap on the left and right edge, which means it misses the 5% of padding. This problem seems only happen on the most out container.

**Comment by nicholaszein** [comment]
Hello there @saludstyle!

I'm a little late, but we have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
