### ISSUE TITLE
🐞 Bug report: Team Member Element not displaying images

### ISSUE THREAD

**Issue by mbamz** [elementor/elementor#19384]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I load the team member element in editing mode I am able to see the images. However when I ask the live page the images are not appearing. I've tried this on multiple browsers and still have the same problem.

### Steps to reproduce

Add team member element.
Add Image
Publish/Update Page
Clear Cache
View Page on browsers

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v5.6.49-89.0 |  
PHP Version: | 7.2.34 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by rami-elementor** [comment]
Elementor has no "team member" widget. I think it's an external addon.

You should contact the addon developer.
