### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by sermalefico** [elementor/elementor#19387]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Background gallery images in container no works i nlast update!

### Steps to reproduce

Create new container, check gallery background, put images. No images are dispalyed.
Rollback elementor version all works fine

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.41 (Win64) OpenSSL/1.1.1l PHP/7.4.27
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.4.27
	PHP Memory Limit: 4G
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://boudevara.test
	Home URL: https://boudevara.test
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 4G
	Permalink Structure: /%category%/%postname%/
	Language: gl-ES
	Timezone: Europe/Madrid
	Admin Email: adrian.arcay@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Base
	Version: 1.0.1634558764
	Author: ADF
	Child Theme: Yes
	Parent Theme Name: Kadence
	Parent Theme Version: 1.1.25
	Parent Theme Author: Kadence WP

== User ==
	Role: administrator
	WP Profile lang: gl_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	ACF OpenStreetMap Field
		Version: 1.3.5
		Author: Jörn Lund

	ACF QuickEdit Fields
		Version: 3.1.11
		Author: Jörn Lund

	Advanced AJAX Product Filters for WooCommerce
		Version: 1.6.3.1
		Author: BeRocket

	Advanced Custom Fields: Extended
		Version: 0.8.8.7
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	Advanced Google reCAPTCHA
		Version: 1.0.9
		Author: WP Concern

	Ajax Cart AutoUpdate for WooCommerce
		Version: 1.5.5
		Author: taisho

	Autoptimize
		Version: 3.1.0
		Author: Frank Goossens (futtta)

	Change Quantity on Checkout for WooCommerce
		Version: 2.0
		Author: Bhavik Kiri

	Checkout Field Editor for WooCommerce
		Version: 1.7.1
		Author: ThemeHigh

	Classic Editor and Classic Widgets
		Version: 1.1.1
		Author: WPGrim

	Customer Reviews for WooCommerce
		Version: 5.2.1
		Author: CusRev

	Disable Cart Fragments
		Version: 2.1.1
		Author: Optimocha

	e-addons DISPLAY
		Version: 2.1.1
		Author: Nerds Farm

	e-addons EXTENDED
		Version: 2.3
		Author: Nerds Farm

	e-addons for Elementor
		Version: 3.1.3
		Author: Nerds Farm

	e-addons PRO FORM EXTENDED
		Version: 2.3.4
		Author: Nerds Farm

	e-addons PRO FORM FILTERS
		Version: 2.0.6
		Author: Nerds Farm

	e-addons QUERY
		Version: 2.1.3
		Author: Nerds Farm

	e-addons TEMPLATE
		Version: 2.0.1
		Author: Nerds Farm

	e-addons TWIG
		Version: 2.2.1
		Author: Nerds Farm

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Extensions for Leaflet Map
		Version: 3.1
		Author: hupe13

	Flying Pages
		Version: 2.4.6
		Author: WP Speed Matters

	Flying Scripts
		Version: 1.2.3
		Author: WP Speed Matters

	Hide Google reCAPTCHA Logo
		Version: 1.0.0
		Author: Adeleye Ayodeji

	JSM's Show Post Metadata
		Version: 3.0.4
		Author: JS Morisset

	Lazy Loader
		Version: 8.1.0
		Author: Florian Brinkmann

	Leaflet Map
		Version: 3.0.4
		Author: bozdoz

	MouseWheel Smooth Scroll
		Version: 5.9
		Author: KubiQ

	MultiStep Checkout for WooCommerce
		Version: 2.0.9
		Author: ThemeHigh

	OoohBoi Steroids for Elementor
		Version: 2.0.0
		Author: OoohBoi

	Polylang Connect for Elementor
		Version: 2.3.0
		Author: Creame

	Polylang for WooCommerce
		Version: 1.6.3
		Author: WP SYNTEX

	Polylang Pro
		Version: 3.2.4
		Author: WP SYNTEX

	Qty Increment Buttons for WooCommerce
		Version: 2.7.5
		Author: taisho

	Quick Featured Images
		Version: 13.6.0
		Author: Kybernetik Services

	Rank Math SEO
		Version: 1.0.94
		Author: Rank Math

	Really Simple SSL
		Version: 5.3.3
		Author: Really Simple Plugins

	Robin image optimizer
		Version: 1.5.6
		Author: Creative Motion <info@cm-wp.com>

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	Smash Balloon Instagram Feed
		Version: 6.0.6
		Author: Smash Balloon

	States, Cities, and Places for WooCommerce
		Version: 1.3.2
		Author: Kingsley Ochu

	Stripe Payment Plugin for WooCommerce
		Version: 3.7.3
		Author: WebToffee

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	Swift Performance Lite
		Version: 2.3.6.5
		Author: SWTE

	UpdraftPlus - Backup/Restore
		Version: 1.22.14
		Author: UpdraftPlus.Com, DavidAnderson

	User Menus
		Version: 1.2.9
		Author: Code Atlantic

	Visual Hook Guide for Kadence
		Version: 1.0.0
		Author: Sridhar Katakam

	WC - APG NIF/CIF/NIE Field
		Version: 1.7.3
		Author: Art Project Group

	WebToffee PayPal Express Checkout Payment Gateway for WooCommerce ( Free )
		Version: 1.7.4
		Author: WebToffee

	WooCommerce
		Version: 6.7.0
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.18
		Author: CartFlows Inc

	Woody code snippets (PHP snippets | Insert PHP)
		Version: 2.4.6
		Author: Creative Motion, Will Bontrager Software, LLC <will@willmaster.com>

	WPC AJAX Add to Cart for WooCommerce
		Version: 1.5.1
		Author: WPClever

	WPC Smart Quick View for WooCommerce
		Version: 3.1.1
		Author: WPClever

	WPC Variations Radio Buttons for WooCommerce
		Version: 3.1.7
		Author: WPClever

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation

== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 

	Swift Performance early loader
		Version: 
		Author: 

== Experimentos de Elementor ==
	Salida do DOM optimizada: Activo
	Carga de recursos mellorada: Activo
	Carga de CSS mellorada: Activo
	Fontes de iconas integradas: Activo
	Melloras de accesibilidade: Activo
	Puntos de ruptura personalizados adicionais: Inactivo
	Importar ou exportar un conxunto de modelos: Inactivo
	Ocultar os widgets nativos de WordPress dos resultados da busca: Inactivo
	admin_menu_rearrangement: Inactivo por defecto
	Contedor Flexbox: Activo
	Default to New Theme Builder: Inactivo
	Páxinas de destino: Inactivo
	Mostrario de cores: Inactivo
	Widgets favoritos: Inactivo
	Barra superior de administración: Inactivo
	Page Transitions: Inactivo
	Notes: Inactivo
	Form Submissions: Activo
	Scroll Snap: Inactivo

== Rexistro ==
	
PHP: showing 15 of 15PHP: 2022-06-22 15:21:53 [notice X 12][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-22 17:27:59 [notice X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] O argumento $control_id está obsoleto desde a versión 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/zeus-elementor/modules/query-post/module.php(33): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-22 19:13:04 [notice X 20][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 11:04:16 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/xnmarias/domains/boudev [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-20 12:00:03 [notice X 4][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::120] Undefined index: form_fields [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-22 12:16:09 [notice X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-23 11:59:42 [warning X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://boudevara.gal/wp-content/uploads/2022/07/logotipo-vertical-bou-de-vara.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-28 15:32:52 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/base/module.php::325] Uncaught Error: Class 'ElementorPro\Modules\Woocommerce\Widgets\Product_Images' not found in /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/base/module.php:325
Stack trace:
#0 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Base\Module->init_widgets(Object(Elementor\Widgets_Manager))
#1 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(117): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#4 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(297): Elementor\Widgets_Manager->init_widgets()
#5 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elemen [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 19:13:07 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/autoloader.php::266] require(): Failed opening required '/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/dynamic-tags/tag.php' (include_path='.:/opt/alt/php74/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-29 19:13:21 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/autoloader.php::266] require(): Failed opening required '/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/document-types/page-base.php' (include_path='.:/opt/alt/php74/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-30 15:27:50 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/autoloader.php::266] require(): Failed opening required '/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/settings/page/manager.php' (include_path='.:/opt/alt/php74/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-30 18:15:26 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/elements.php::350] require_once(): Failed opening required '/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/base/element-base.php' (include_path='.:/opt/alt/php74/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-30 18:15:35 [notice X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/plugin.php::153] include(): read of 24348 bytes failed with errno=12 Cannot allocate memory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-03 11:08:33 [error X 1][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::22] Uncaught Error: Class 'ElementorPro\Modules\Forms\Classes\Form_Base' not found in /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php:22
Stack trace:
#0 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor-pro/plugin.php(153): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#2 [internal function]: spl_autoload_call('ElementorPro\\Mo...')
#3 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/e-addons-pro-form-filters/modules/filters/widgets/posts-per-page.php(27): class_exists('\\ElementorPro\\M...')
#4 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/e-addons-for-elementor/core/plugin.php(128): include_once('/home/xnmarias/...')
#5 [internal function]: EAddonsForElementor\Plugin->autoload('EAddonsProFormF...')
#6 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/e-addons-for-elementor/base/module-base.php(232): spl_autoload_call('EAd [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-03 11:08:34 [error X 2][/home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/base/module.php::325] Uncaught Error: Class 'ElementorPro\Modules\Social\Widgets\Facebook_Button' not found in /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/core/base/module.php:325
Stack trace:
#0 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Base\Module->init_widgets(Object(Elementor\Widgets_Manager))
#1 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/xnmarias/domains/boudevara.gal/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(117): do_action('elementor/widge...', Object(Elementor\Widgets_Manager))
#4 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(297): Elementor\Widgets_Manager->init_widgets()
#5 /home/xnmarias/domains/boudevara.gal/public_html/wp-content/plugins/elementor/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-06-22 14:07:25 [error X 165][https://boudevara.gal/wp-content/plugins/elementor/assets/js/editor.min.js:2:391230] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-06-22 14:40:30 [error X 3][https://boudevara.gal/wp-content/plugins/elementor/assets/js/editor.min.js:2:229782] Cannot read properties of null (reading \'fire\') 
JS: 2022-06-23 08:21:36 [error X 1][https://boudevara.gal/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:382071] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-07-21 19:00:15 [error X 2][https://boudevara.gal/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.7.2:1:741] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-07-22 14:13:26 [error X 6][https://boudevara.gal/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:548544] T.getContainer is not a function 
JS: 2022-07-22 16:38:30 [error X 1][https://boudevara.gal/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:287643] Cannot read properties of undefined (reading \'id\') 
JS: 2022-08-01 07:41:37 [error X 1][https://boudevara.gal/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view13070\") has already been destroyed and cannot be used. 

Log: showing 20 of 202022-07-04 10:19:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-04 10:19:04 [info] elementor::elementor_updater Started 
2022-07-04 10:19:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-04 10:19:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-04 10:19:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 18:01:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 18:01:10 [info] elementor::elementor_updater Started 
2022-07-27 18:01:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 18:01:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 18:01:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 18:01:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-01 08:52:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-01 08:52:49 [info] elementor-pro::elementor_pro_updater Started 
2022-08-01 08:52:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-01 08:52:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-01 08:52:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 12:01:11 [info] elementor::elementor_updater Started 
2022-08-08 12:01:11 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 12:01:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 12:01:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

== Elementor - Compatibility Tag ==
	
	e-addons for Elementor: Compatible
	Elementor Pro: Compatible
	OoohBoi Steroids for Elementor: Compatible
	Polylang Connect for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	e-addons for Elementor: Compatible
	OoohBoi Steroids for Elementor: Compatible
	Polylang Connect for Elementor: Compatible

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
