### ISSUE TITLE
🐞 Bug report: Possible bug in version 3.7

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19382]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In version 3.7, after about 5 or 10 minutes of editing, the update button does not save changes. This is a problem that I have not experienced before. But it has happened to me 4 or 5 times since the update. **If this happened to you in the new version, please confirm**

thank you

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by shilo-ey** [comment]
Hey @79ho3ein 

Does this issue occurs consistently or not? can you please share your system info?

**Comment by 79ho3ein** [comment]
hi @shilo-ey 
The problem was not elementor. This is a bug created by the elementor extras plugin with version 3.7. I forgot to close this issue. 

Thank you
