### ISSUE TITLE
✅ 🚀 Feature Request 3.7+: Lower number scrubbing for EM and REM - [ED-8551]

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19399]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In the recent 3.7 core update number scrubbing was added for margin and padding. The current increment is by 1 step as the base use. But for EM and REM as these are more drastic values as the difference between 1 and 2 EM is different to 1 and 2 PX. Ideally, the increment needs to change per value type.
![GIF 09-08-2022 09-59-13](https://user-images.githubusercontent.com/55829113/183608838-a34ea3cb-7f9a-41a9-9106-ed46c9f51bf9.gif)

### Describe the solution you'd like

Change the incremental step value in which the scrubber increases and decreases the value from 1 step to either 0.1 or 0.5.

I would prefer 0.1 step but up to your team to review the best solution.

**Comment by 23Chromosomes** [comment]
It's not rare to use 1.25 rem or something similar, or even 1.125rem. So being allowed to at least use 3 decimals, would be great!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
