### ISSUE TITLE
🐞 Bug report: v3.7 core - max-width: 100% applied only in editor

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19398]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As I have mentioned in the 3.7 beta thread. In the editor only, when you set a custom width for a widget there is an additional CSS value added for max-width that overwrites the existing input value. This 100% is good as it fixes flex-grow and overflow issues, but it is only applied in the editor CSS.

My suggestion is that only for the container experiment enabled is to replace the user-defined max-width (so the standard user input width stays the same) and replace it with 100% so there aren't two overwriting values.
<details>
<summary>
<b>Editor view image:</b>
</summary> 

![Screenshot 2022-08-09 094144](https://user-images.githubusercontent.com/55829113/183605395-21d5b261-f35b-4b29-881a-a4c529de7a97.png)

</details>

<details>
<summary>
<b>Frontend view image:</b>
</summary> 

![Screenshot 2022-08-09 094214](https://user-images.githubusercontent.com/55829113/183605406-096251ae-b882-4b39-94ce-9c3ec42d4037.png)

</details>

### Steps to reproduce

https://user-images.githubusercontent.com/55829113/183603116-1c90d1de-10e1-47c0-91e2-14ef8af65494.mp4

**Key steps:**
- Parent container in row direction
- Set child widget custom width
- Set child widget to flex-grow
- Compare editor view to frontend view

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hey @perks98 , thank you for reporting.

This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!
