### ISSUE TITLE
✅ 🔃 🔗 🚀 Feature Request: Carousel in elementor (Related to #20201)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19405]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team

6 years have passed since the birth of elementor and every year it becomes more powerful. elementor is truly unique. But elementor has not paid attention to a series of very important and necessary features. In this issue, I just want to mention one of them, **the carousel**.

Carousel is used in almost every website. Carousel to display post, product or even image and...
Unfortunately, now we cannot display products or even posts in elementor as a carousel. The only way to solve the need is to refer to third-party plugins.
Of course, I don't know, maybe the carousel will come with the loop builder. But anyway, I had some suggestions for carousel development in elementor, please check them out. Of course, if you decide to develop the carousel in elementor!

### Describe the solution you'd like

1- Firstly, splide js library has much better performance and features than swiper. It is also much more efficient and has a positive effect on performance. Of course, I have already mentioned it in another issue. So it's not bad if you replace it with the swiper you're using now in elementor.

2- Adding different modes to display a carousel would be great. Currently we can only have the simplest possible form of a carousel in elementor. Modes like :

**Side padding**
![side padding](https://user-images.githubusercontent.com/77163248/183667851-db642400-a8cc-4c07-b997-34a49c6cf967.png)

**free drag (Only for tablets and mobile phones)**
https://splidejs.com > free drag

**Carousel Progress**
![Carousel Progress](https://user-images.githubusercontent.com/77163248/183668791-4e020fbd-111f-4ade-8c32-cfd8bb2694e0.png)
(Autoplay is extremely attractive for this mode)

**Vertical Slider**

**Mouse Wheel**

**overflow mode**
![overflow](https://user-images.githubusercontent.com/77163248/183671480-98baef13-4a8b-4a10-af6a-13e81872ad32.png)

And many other things that you definitely know about.

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

this one slipped under my radar, but we can agree the Loop Carousel has been long released and can be used now. As for the other requests about the layout, there are other requests from you and other users to add those changes. To avoid duplicates I'm closing this issue as solved.

The Loop Carousel was released on version 3.11.0.

Thank you so much for contributing! 🙏
