### ISSUE TITLE
🐞 Bug report: bug in version 3.7 - History does not go back properly.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19408]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It seems that there is a problem with going back (history) in the new version. Please watch this video :

https://user-images.githubusercontent.com/77163248/183747319-46e5f3b5-d6b6-427b-ac41-f5470bb9e63d.mp4

As you can see in the video above, after the editor was reloaded, the two icon widgets were using global colors. I changed their color and after that, in the history section, I clicked on editing started, but there was no global color in the two widgets like in the beginning. (If you check the video first, both widgets used global color)
**This bug also occurs in global fonts under similar conditions.**

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

**Comment by momo-fr** [comment]
Same issue for me, big problem!!

**Comment by arielk** [comment]
Hi,

Does this issue resolve upon upgrading to v3.7.2?
