### ISSUE TITLE
🐞 Bug report: Spacer elements are being ignored and not showing up after upgrade to 3.7.0

### ISSUE THREAD

**Issue by elmalak** [elementor/elementor#19409]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating Elementor to version 3.7.0 I noticed that spacer elements are no longer showing on the page, or to be more specific they are still in the code but they have no height, so elements above and beneath it stick to each other.

### Steps to reproduce

Just add a spacer element between any two elements and try to adjust the height you will see that it doesn't change or affect the elements around it and on the page when viewing appears as no spacer is there at all.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.38-41
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Tijuana
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Seclore Astra child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	404page - your smart custom 404 error page
		Version: 11.3.1
		Author: Peter Raschendorfer

	Activity Log
		Version: 2.8.3
		Author: Activity Log Team

	Advanced Custom Fields
		Version: 5.12.3
		Author: Delicious Brains

	Advanced Database Cleaner PRO
		Version: 3.1.7
		Author: Younes JFR.

	Astra Pro
		Version: 3.9.1
		Author: Brainstorm Force

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Disable Feeds
		Version: 1.4.4
		Author: Samir Shah, BBpress support by Matthew Sigley

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Easy Updates Manager
		Version: 9.0.13
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.22
		Author: Till Krüss

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	Gravity Forms
		Version: 2.6.4
		Author: Gravity Forms

	iLightBox
		Version: 1.6.4
		Author: iProDev

	Image Map Pro
		Version: 5.3.2
		Author: Webcraft Plugins Ltd.

	InfiniteWP - Client
		Version: 1.9.8
		Author: Revmakx

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetEngine
		Version: 3.0.2
		Author: Crocoblock

	JetMenu
		Version: 2.2.01
		Author: Crocoblock

	JetSearch
		Version: 3.0.1
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.13
		Author: Crocoblock

	Logo Carousel
		Version: 3.4.12
		Author: ShapedPlugin

	Page Excerpt
		Version: 1.3
		Author: Jeremy Massel

	Page Links To
		Version: 3.3.6
		Author: Mark Jaquith

	Redirection
		Version: 5.3.2
		Author: John Godley

	Schema - All In One Schema Rich Snippets
		Version: 1.6.5
		Author: Brainstorm Force

	SiteGround Optimizer
		Version: 7.2.0
		Author: SiteGround

	SiteGround Security
		Version: 1.3.0
		Author: SiteGround

	Smart Slider 3 Pro
		Version: 3.5.1.8
		Author: Nextend

	Smush Pro
		Version: 3.10.3
		Author: WPMU DEV

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.33
		Author: Sucuri Inc.

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	Ultimate Addons for Elementor
		Version: 1.36.8
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 2.22.14.25
		Author: UpdraftPlus.Com, DavidAnderson

	Virtual Robots.txt
		Version: 1.10
		Author: Marios Alexandrou

	Wonder Carousel Pro
		Version: 18.5C
		Author: Magic Hills Pty Ltd

	Wonder Grid Gallery Pro
		Version: 17.5C
		Author: Magic Hills Pty Ltd

	Wonder Tabs Pro
		Version: 7.5C
		Author: Magic Hills Pty Ltd

	WP All Import Pro
		Version: 4.7.5
		Author: Soflyy

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.1
		Author: WPCode

	WP Migrate
		Version: 2.3.3
		Author: Delicious Brains

	WPMU DEV Dashboard
		Version: 4.11.14
		Author: WPMU DEV

	WP Timeline
		Version: 3.3.3
		Author: ExThemes

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.4
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 9 of 9PHP: 2022-07-06 13:48:10 [notice X 43][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-12 01:38:33 [notice X 3945][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-12 01:39:28 [notice X 5339][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-12 01:39:36 [notice X 596][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/jet-popup/includes/integration.php(134): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-16 09:00:39 [notice X 653][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: apply_indexer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-22 19:26:55 [notice X 1][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/jet-popup/includes/elementor-finder/elementor-finder.php(47): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]
PHP: 2022-08-04 22:57:57 [notice X 1][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-08 18:52:26 [warning X 1][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/uploads/elementor/css/post-32792.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-08 19:15:12 [notice X 2][/home/customer/www/seclore-dev.boldfocus.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 15 of 15JS: 2022-07-07 04:34:49 [error X 25][https://seclore-dev.boldfocus.com/wp-content/plugins/ultimate-elementor/assets/min-js/uael-nav-menu.min.js?ver=1.36.7:1:15401] Cannot read properties of undefined (reading \'left\') 
JS: 2022-07-07 04:53:45 [error X 99][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:13282] r.get is not a function 
JS: 2022-07-11 19:06:59 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3066\") has already been destroyed and cannot be used. 
JS: 2022-07-12 03:30:22 [error X 50][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:362278] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-07-14 09:01:12 [error X 13][https://seclore-dev.boldfocus.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13633] Syntax error, unrecognized expression: .uael-video-player div[data-id=] 
JS: 2022-07-21 05:24:47 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view24665\") has already been destroyed and cannot be used. 
JS: 2022-07-22 21:59:06 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2240\") has already been destroyed and cannot be used. 
JS: 2022-07-25 03:48:19 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.6.7:3:88876] Data commands: `` not found. 
JS: 2022-07-25 23:17:46 [error X 3][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:900533] Cannot create property \'element\' on string \'destroy\' 
JS: 2022-07-25 23:28:18 [error X 7][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:465986] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-07-26 05:57:01 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view16818\") has already been destroyed and cannot be used. 
JS: 2022-07-27 02:23:03 [error X 2][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor-pro/assets/js/nav-menu.3de49ba5ef86f9a22ff5.bundle.min.js:2:2601] Cannot read properties of null (reading \'stretch\') 
JS: 2022-07-27 14:48:07 [error X 4][https://seclore-dev.boldfocus.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:65618] t.toLowerCase is not a function 
JS: 2022-08-01 23:53:18 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view57244\") has already been destroyed and cannot be used. 
JS: 2022-08-05 19:24:50 [error X 1][https://seclore-dev.boldfocus.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1877\") has already been destroyed and cannot be used. 

Log: showing 18 of 182022-07-16 05:10:03 [info] elementor::elementor_updater Started 
2022-07-16 05:10:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-16 05:10:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-16 05:10:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-16 05:10:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 10:10:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 10:10:40 [info] elementor::elementor_updater Started 
2022-07-27 10:10:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 10:10:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 10:10:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-08 18:52:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 18:52:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 18:52:25 [info] elementor-pro::elementor_pro_updater Started 
2022-08-08 18:52:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-08 18:52:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-08 18:52:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 18:52:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 18:52:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by momo-fr** [comment]
Same issue for me on 2 websites.

**Comment by awakekat** [comment]
I tested this with containers active and inactive. The spacer widget did respond to update when I changed its height in PX, VH and EM. 

== Elementor ==
Elementor Version 3.7.0
Elementor Pro Version 3.7.3

System Info
== Server Environment ==
Operating System: MacOS
Local Server Software: LocalWP Version 6.4.2+6012
MySQL version: 8.0.16
PHP Version: 7.4.1
Elementor Library: Connected

== WordPress Environment ==
Version: 6.0.1
WP Multisite: No
Permalink Structure: /%postname%/
Language: en-US
Debug Mode: Inactive

== Theme ==
Name: Hello
Version: 1.0.0
Author: Elementor
Child Theme: Yes
Parent Theme Name: Hello
Parent Theme Version: 2.6.1
Parent Theme Author: Elementor

== User ==
Role: administrator
WP Profile lang: en_US
User Agent: Chrome Version 104.0.5112.79 (Official Build) (x86_64)

== Active Plugins ==
Ele Custom Skin Version 3.1.6
OoohBoi Steroids for Elementor Version 2.0.0
Unlimited Elements for Elementor (Premium) Version 1.5.24
WordPress Importer Version 0.7

**Comment by hein-obox** [comment]
@elmalak @momo-fr @awakekat 

I am trying to reproduce this on my environment. Would it be possible to provide a Screencast (e.g. using https://www.loom.com/) or to list all the steps?

My initial question: 
- Are you using sections or containers (with direction row or column)?
- Do you have any other widgets inside the section or container?

**Comment by elmalak** [comment]
I just upgraded to Elementor 3.7.1 and this seems to have fixed the spacer issue.
I hope it's the same for everyone else.

**Comment by elmalak** [comment]
Hi,
The issue happened when I was using containers not columns.

I think it also happens to spacers within a container and other elements
around them like a heading and image.
At that time it doesn't work.

Hope that helps.

**Comment by Leonieve** [comment]
Hello, same problem after updating to Elementor to 3.8.1  (Free version). I converted some posts to containers and after that the spacers didn't respond anymore and are turned grey as well. I forgot to save the old templates (sections and columns) so deactivating flexbox containers causes the removal of my entire post. Hope this issue get fixed.

**Comment by elmalak** [comment]
@About2git Check if you're using one of the Elementor addons, if you are then you might need to disable the Display Conditions feature in that addon to solve your issue.

**Comment by About2git** [comment]
@elmalak thanks for the fast reply, indeed I have JetTabs, JetElements & JetTricks Addons but these have no Display conditions, I also have Essentials Addons (Free Version, which only has in the paid Version the Display conditions Feature). Maybe I install the Pro Verion and enable/disable it… 

Any else you can recommend?

Thanks for your help!

**Comment by elmalak** [comment]
@About2git you're welcome.

I am not sure if you only have the free version of the Essential addons that would still cause the bug or not.
Try to disable the plugin and see if this fixes the issue, if Yes, then you might need to get the Pro version and disable it like you suggested.

**Comment by About2git** [comment]
@elmalak thanks for your help. Unfortunately this does not fix the problem:

- Downgraded to Elementor 3.7.8, and updated again to 3.8.2
- disabled all third Party addons
- Installed the essentials Addons and disabled the Display conditions feature

… nothing helped… :-(

**Comment by elmalak** [comment]
@About2git 
I am sorry to hear that nothing of the above worked for you.

There is always the possibility of removing the spacer elements and using margin instead but that needs a lot of work of course and it might not be practical depending on how big your site is and how many times you've used it.

**Comment by Pycroyal** [comment]
Same issue !

**Comment by About2git** [comment]
I apologize, it was a fault from the child them functions.php… Now it is working for me again…

**Comment by Pycroyal** [comment]
For me a it's a css issue

Here the css applied to spacer :
Strange "var(--container-widget-height,var(--spacer-size))" ???

.e-con-inner > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner, .e-con > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner { height: var(--container-widget-height,var(--spacer-size)); }

I put this in my custom css to fix it but maybe fix elementor code will be great !

.e-con-inner > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner, .e-con > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner { height: var(--spacer-size) !important; }

**Comment by myBCN** [comment]
> I put this in my custom css to fix it but maybe fix elementor code will be great !
> 
> .e-con-inner > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner, .e-con > .elementor-widget-spacer > .elementor-widget-container > .elementor-spacer > .elementor-spacer-inner { height: var(--spacer-size) !important; }

This fixed the problem for me. Thank you PycRoyal! 🙏
