### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by matiasprego** [elementor/elementor#19407]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

my site looks broken from the Elementor view, okey from the frontend. and also the product category widget looks bad on Safari.

the page is: https://cativelli.connective.com.uy/
<img width="1383" alt="Captura de Pantalla 2022-08-09 a la(s) 16 06 32" src="https://user-images.githubusercontent.com/2658201/183741134-e831d868-9009-4b47-86b9-a54f81b9ae3a.png">
<img width="1196" alt="Captura de Pantalla 2022-08-09 a la(s) 16 07 39" src="https://user-images.githubusercontent.com/2658201/183744839-978a1161-fe7b-4aed-a944-e735c49c3aaf.png">

### Steps to reproduce

Just edit the page with elementor.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.6.51 |  
PHP Version: | 7.3.33 |  
PHP Memory Limit: | 256M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by rami-elementor** [comment]
Hi @matiasprego ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
