### ISSUE TITLE
🐞 Bug report: Elementor 3.7 -> Dynamic switcher don't show for numbers control

### ISSUE THREAD

**Issue by kaskad88** [elementor/elementor#19419]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Dynamic switcher don't show for numbers control in Elementor 3.7 https://tppr.me/BNllp 

### Steps to reproduce

Add example the Star Rating widget and try to set dynamic tag for rating setting.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Elementor 3.7.0
Elementor Pro 3.7.2

**Comment by 79ho3ein** [comment]
That's right, the dynamic tag has disappeared in the star rating widget. Has this happened to other widgets? As far as I could see, the other widgets were fine.

**Comment by kaskad88** [comment]
> That's right, the dynamic tag has disappeared in the star rating widget. Has this happened to other widgets? As far as I could see, the other widgets were fine.

This happens in other widgets as well:
- Counter
- Countdown
- Reviews
- PayPal Button
- and other

**Comment by Michaelgimii** [comment]
+1 same issue

**Comment by lensbreak** [comment]
+1 same issue

**Comment by solinvictus-dame** [comment]
+1 same issue here

**Comment by SargasTM** [comment]
+1 same issue

**Comment by aalexandr21** [comment]
+1

**Comment by originalsmokee** [comment]
+1

**Comment by musedria** [comment]
+1

**Comment by Floydtm** [comment]
+1

**Comment by ObitoTM** [comment]
+1

**Comment by anaslavna** [comment]
+1

**Comment by UraraReika** [comment]
+1 Need this.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.7.1

Feel free to update

Thanks!
