### ISSUE TITLE
🐞 Bug report: Update Free 3.7.0 » Flexbox Container » Background Video disappear, if a fallback picture is chosen 

### ISSUE THREAD

**Issue by RHillhouse** [elementor/elementor#19413]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you chose a fallback picture - the video disappear and only the fallback picture is showing.
if you chose no fallback picture - the video appear and did what it should.

In the editor, frontend and on all devices

### Steps to reproduce

put a video in the flexbox container background - video will showing und playing
then activate a fallback picture - the video will disappear and only the fallback picture will showing

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

WordPress 6.0.1

**Comment by shilo-ey** [comment]
Hey @RHillhouse , thank you for reporting.

This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!
