### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by juanferduque** [elementor/elementor#19426]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

try to open my blog page: https://elduquebipolar.com/blog

### Steps to reproduce

it doesn't work 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.15
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://elduquebipolar.com
	Home URL: https://elduquebipolar.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es-CO
	Timezone: -5
	Admin Email: juanferduque@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: CoachPress Lite
	Version: 1.1.3
	Author: Blossom Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_CO
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0
		Author: Automattic

	BlossomThemes Email Newsletter
		Version: 2.2.0
		Author: blossomthemes

	BlossomThemes Toolkit
		Version: 2.2.3
		Author: blossomthemes

	Contact Form 7
		Version: 5.6.2
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.8.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.12
		Author: Brainstorm Force, Nikhil Chavan

	Gutenberg
		Version: 13.8.1
		Author: Gutenberg Team

	Hostinger
		Version: 1.0
		Author: Hostinger

	Redirection
		Version: 5.3.2
		Author: John Godley

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Starter Templates
		Version: 3.1.13
		Author: Brainstorm Force

	W3 Total Cache
		Version: 2.2.4
		Author: BoldGrid

	Wheel of Life
		Version: 1.0.9
		Author: Kraft Plugins

	WP Force Lowercase URLs
		Version: 2.0.1
		Author: Josh Buchea

	WPForms Lite
		Version: 1.7.5.5
		Author: WPForms

== Uso de los elementos ==
	

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo por defecto
	Carga de recursos mejorada: Activo por defecto
	Carga de CSS mejorada: Activo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Activo por defecto
	Puntos de ruptura personalizados adicionales: Activo por defecto
	Import Export Website Kit: Activo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	admin_menu_rearrangement: Inactivo por defecto
	Flexbox Container: Inactivo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto

== Registro ==
	
JS: showing 2 of 2JS: 2022-08-09 16:15:29 [error X 16][https://elduquebipolar.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:766552] Cannot read properties of undefined (reading \&#039;localized\&#039;) 
JS: 2022-08-09 16:50:23 [error X 14][https://elduquebipolar.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.7.0:2:4795] Cannot read properties of undefined (reading \&#039;data\&#039;) 

PHP: showing 3 of 3PHP: 2022-08-09 17:42:24 [notice X 5][/home/u703069445/domains/elduquebipolar.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-09 17:20:36 [notice X 2][/home/u703069445/domains/elduquebipolar.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1370] Undefined index: content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-10 18:21:18 [notice X 1][/home/u703069445/domains/elduquebipolar.com/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property &#039;email&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52022-08-09 18:57:02 [info] elementor::elementor_updater Started 
2022-08-09 18:57:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 18:57:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 18:57:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.8.0-dev1',
)]
2022-08-09 18:57:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.8.0-dev1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible

**Comment by shilo-ey** [comment]
Please make sure you are updated to the latest Elementor version (not Dev)

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Deactivate all of the Experiments and activate them one by one until you identify the buggy experiment (Elementor > Settings > Experiments tab)
- Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).


And see if the issue still persists.
