### ISSUE TITLE
🐞 Bug report: Copy Style Causes Save To Hang

### ISSUE THREAD

**Issue by wangstein** [elementor/elementor#19420]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Copying an element and then pasting the element as Copy Style to another element then try to save the work, the publish button stays green.

### Steps to reproduce

1. Create any element, i.e. text heading
2. Duplicate the element
3. Copy the first element - no need to set any styles
4. Select the 2nd/duplicated element, right click, paste as style
5. Now click Publish
6. Publish doesn't seem to be doing anything

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.0.21
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 16384
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://22cabf29d4.nxcli.net
	Home URL: https://22cabf29d4.nxcli.net
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Detroit
	Admin Email: dev@mastiffinc.com
	Debug Mode: Inactive

== Theme ==
	Name: Trellis
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	Ele Custom Skin
		Version: 3.1.6
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.9
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.1.6
		Author: WPDeveloper

	Gravity Forms
		Version: 2.6.5
		Author: Gravity Forms

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast

== Must-Use Plugins ==
	Nexcess Managed Apps
		Version: 1.30.0
		Author: Nexcess

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Inactive
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 4 of 4PHP: 2022-07-22 17:37:06 [warning X 1][/chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Attempt to read property "email" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-22 18:52:23 [error X 3][/chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(8, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-22 20:25:13 [warning X 2][/chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-01 10:58:49 [warning X 1][/chroot/home/ac77e55f/22cabf29d4.nxcli.net/html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 222022-07-22 17:42:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-22 17:42:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-07-22 17:42:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-07-22 17:42:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-22 17:42:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-30 09:45:45 [info] elementor::elementor_updater Started 
2022-07-30 09:45:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-30 09:45:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-30 09:45:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-30 09:45:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-01 10:37:29 [info] elementor-pro::elementor_pro_updater Started 
2022-08-01 10:37:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-01 10:37:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-01 10:37:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-01 10:37:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-10 09:43:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-10 09:43:45 [info] elementor::elementor_updater Started 
2022-08-10 09:43:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-10 09:43:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-10 09:43:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

JS: showing 4 of 4JS: 2022-07-23 02:31:40 [error X 29][https://22cabf29d4.nxcli.net/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.7:2:12186] r.get is not a function 
JS: 2022-07-23 04:06:24 [error X 107][https://22cabf29d4.nxcli.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:475108] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-07-23 04:59:36 [error X 21][https://22cabf29d4.nxcli.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:443987] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-08-10 15:44:36 [error X 1][https://22cabf29d4.nxcli.net/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.7.0:2:51477] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment]
hey @wangstein
I also had this problem. But the problem is not from elementor. The problem was from **elementor extras plugin > display conditions**.
If any of your plugins have the display conditions module, disable it and see if the problem goes away.

**Comment by wangstein** [comment]
@79ho3ein Word! Oh wow, you are totally right. I had Display Condition turned on for Essential Addon. I'll let them know. I just turned it off. I also use Dynamic.ooo sometimes, I did not test that... but I'll close this bug so the Elementor team don't waste their time. Thanx!!!
