### ISSUE TITLE
🐞 Bug report: Uncaught TypeError: T.setRegisterConfig is not a function

### ISSUE THREAD

**Issue by nexulino** [elementor/elementor#19434]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating to last version my theme gives this error when loading Elementor Editor

Uncaught TypeError: T.setRegisterConfig is not a function
    at Component.registerCommand (editor.min.js:3:983266)
    at editor.min.js:3:980271
    at Array.forEach (<anonymous>)
    at Component.registerAPI (editor.min.js:3:980202)
    at _default.register (web-cli.min.js:3:79822)
    at Editor.initComponents (editor.min.js:3:523269)
    at Editor.onStart (editor.min.js:3:537559)
    at Editor.onStart (editor.min.js:3:1063408)
    at Object._triggerMethod (backbone.marionette.min.js:24:7999)
    at f.triggerMethod (backbone.marionette.min.js:24:8166)

### Steps to reproduce

don't know

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.35
	PHP Version: 7.4.30
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 6000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://findblend.ro
	Home URL: https://findblend.ro
	WP Multisite: No
	Max Upload Size: 1 Go
	Memory limit: 256M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: ro-RO
	Timezone: 3
	Admin Email: contact@findblend.ro
	Debug Mode: Inactive

== Theme ==
	Name: Minimog Child
	Version: 1.0.0
	Author: ThemeMove
	Child Theme: Yes
	Parent Theme Name: Minimog
	Parent Theme Version: 1.4.2
	Parent Theme Author: ThemeMove

== User ==
	Role: administrator
	WP Profile lang: ro_RO
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	BEAR – Bulk Editor and Products Manager Professional for WooCommerce
		Version: 2.1.2
		Author: realmag777

	Category Order and Taxonomy Terms Order
		Version: 1.6.1
		Author: Nsp-Code

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	CMP - Coming Soon & Maintenance Plugin
		Version: 4.1.2
		Author: NiteoThemes

	Conditional Discounts for WooCommerce by ORION
		Version: 2.28.1
		Author: ORION

	Disable "BIG image" Threshold
		Version: 1.0
		Author: Jonathan Desrosiers

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev32
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.2.0
		Author: WPDeveloper

	GTM4WP
		Version: 1.16.1
		Author: Thomas Geiger

	Insight Core
		Version: 2.4.6
		Author: ThemeMove

	Insight Product Brands for Woocommerce
		Version: 1.0.0
		Author: ThemeMove

	Insight Swatches
		Version: 1.3.1
		Author: ThemeMove

	Shoppable Images Lite
		Version: 1.2.2
		Author: Studio Wombat

	Template Library and Redux Framework
		Version: 4.3.16
		Author: Extendify

	WOLF - WordPress Posts Bulk Editor and Manager Professional
		Version: 2.0.5
		Author: realmag777

	WooCommerce
		Version: 6.8.0
		Author: Automattic

	WooCommerce - Show only lowest prices in variable products
		Version: 0.9.31
		Author: Fernando Tellado

	WooCommerce Stripe Gateway
		Version: 6.5.1
		Author: WooCommerce

	WOOF - WooCommerce Products Filter
		Version: 2.2.6.4
		Author: realmag777

	WPC Frequently Bought Together for WooCommerce (Premium)
		Version: 4.3.1
		Author: WPClever

	WPC Product Bundles for WooCommerce (Premium)
		Version: 6.2.1
		Author: WPClever

	WPC Product Tabs for WooCommerce (Premium)
		Version: 1.6.1
		Author: WPClever

	WPC Smart Compare for WooCommerce (Premium)
		Version: 4.4.3
		Author: WPClever

	WPC Smart Notification for WooCommerce (Premium)
		Version: 2.1.2
		Author: WPClever

	WPC Smart Wishlist for WooCommerce (Premium)
		Version: 3.0.2
		Author: WPClever

	WPC Variation Swatches for WooCommerce
		Version: 2.1.2
		Author: WPClever

	WPForms Lite
		Version: 1.7.5.5
		Author: WPForms

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	page : 4
		tm-blockquote : 4
		tm-button : 5
		tm-heading : 25
		tm-image-gallery : 1
		tm-modern-image : 3
		tm-product-carousel : 1
	tm_footer : 0
		divider : 8
		image : 3
		tm-heading : 93
		tm-image-box : 4
		tm-list : 115
		tm-modern-image : 45
		tm-simple-link : 14
		tm-simple-list : 12
		tm-site-logo : 13
		tm-social-networks : 42
		wpforms : 33
	wp-post : 0
		heading : 3
		tm-heading : 1
		tm-image-box : 1
		tm-product-carousel : 1
		tm-simple-list : 12
	wp-page : 6
		button : 5
		heading : 10
		icon-box : 4
		icon-list : 3
		image : 9
		image-carousel : 1
		spacer : 2
		text-editor : 10
		tm-accordion : 1
		tm-button : 3
		tm-google-map : 1
		tm-heading : 11
		tm-image-box : 3
		tm-modern-image : 3
		tm-social-networks : 1
		wpforms : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactiv
	Încărcare îmbunătățită pentru resurse: Inactiv
	Încărcare îmbunătățită pentru CSS: Inactiv
	Inline Font Icons: Inactiv
	Îmbunătățiri la accesibilitate: Inactiv
	Additional Custom Breakpoints: Inactiv
	Import/export kit de șabloane: Inactiv
	Hide native WordPress widgets from search results: Inactiv
	admin_menu_rearrangement: Inactiv, implicit
	Container Flexbox: Inactiv
	Default to New Theme Builder: Inactiv
	Landing Pages: Inactiv
	Color Sampler: Inactiv
	Favorite Widgets: Inactiv
	Bara de sus în administrare: Inactiv
	Page Transitions: Inactiv
	Notes: Inactiv
	Form Submissions: Inactiv
	Scroll Snap: Inactiv

== Log ==
	
JS: showing 2 of 2JS: 2022-08-11 09:07:13 [error X 12][https://findblend.ro/wp-content/plugins/elementor/assets/js/editor.min.js:3:983266] T.setRegisterConfig is not a function 
JS: 2022-08-11 09:09:43 [error X 8][https://findblend.ro/wp-content/plugins/elementor/assets/js/editor-document.min.js:2:25976] elementorDevTools is not defined 

PHP: showing 1 of 1PHP: 2022-08-11 12:22:45 [notice X 1][/home/findblen/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-08-11 09:07:13 [error X 12][https://findblend.ro/wp-content/plugins/elementor/assets/js/editor.min.js:3:983266] T.setRegisterConfig is not a function  JS: 2022-08-11 09:09:43 [error X 8][https://findblend.ro/wp-content/plugins/elementor/assets/js/editor-document.min.js:2:25976] elementorDevTools is not defined  

PHP: showing 1 of 1PHP: 2022-08-11 12:22:45 [notice X 1][/home/findblen/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (   'trace' => ' #0: Elementor\Core\Logger\Manager -> shutdown() ',
--

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibil
	Essential Addons for Elementor: Compatibil

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatibil

**Comment by pebiti** [comment]
I am also getting an error with the new version of the plugin:

WordPress version 6.0.1
Active theme: Flatsome Child (version 3.0)
Current plugin: GTM4WP (version 1.16.1)
PHP version 8.0.21


Error Details
=============
An error of type E_ERROR was caused in line 136 of the file /home/vinde600/public_html/wp-content/plugins/duracelltomi-google-tag-manager/admin/admin.php. Error message: Uncaught Error: Failed opening required '/home/vinde600/public_html/wp-content/plugins/duracelltomi-google-tag-manager/admin/admin-tab-advanced.php' (include_path='.:/opt/alt/php80/usr/share/pear:/opt/alt/php80/usr/share/php:/usr/share/pear:/usr/share/php') in /home/vinde600/public_html/wp-content/plugins/duracelltomi-google-tag-manager/admin/admin.php:136
Stack trace:
#0 /home/vinde600/public_html/wp-content/plugins/duracelltomi-google-tag-manager/duracelltomi-google-tag-manager-for-wordpress.php(46): require_once()
#1 /home/vinde600/public_html/wp-includes/class-wp-hook.php(307): gtm4wp_init()
#2 /home/vinde600/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /home/vinde600/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#4 /home/vinde600/public_html/wp-settings.php(461): do_action()
#5 /home/vinde600/public_html/wp-config.php(96): require_once('/home/vinde600/...')
#6 /home/vinde600/public_html/wp-load.php(50): require_once('/home/vinde600/...')
#7 /home/vinde600/public_html/wp-admin/admin.php(34): require_once('/home/vinde600/...')
#8 /home/vinde600/public_html/wp-admin/edit.php(10): require_once('/home/vinde600/...')
#9 {main}
  thrown

**Comment by nexulino** [comment]
Seems like they fixed it, without any changes editor works again... lol
