### ISSUE TITLE
🚀 Feature Request: Developer Docs - Add conversion function

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19430]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I've recently started looking at the Elementor Developer docs and thinking of injecting controls to extend Elementor widget controls. But something I am worried about is that if the Elementor team implement the same controls down the line (which is a good thing) I wouldn't know how to convert the added control to the new inbuilt control name to use the already user-inputted data or be able to convert said data. Or even in a use case of changing the control name overall like if it was misspelt for example. Would anyone be able to point me in the right direction?

![Screenshot_518](https://user-images.githubusercontent.com/55829113/184095848-99da204f-fed7-4372-baf6-be3f80973e12.jpg)

**Comment by rami-elementor** [comment]
Hi @perks98 ,

The best practice in naming controls is to use some kind of prefix.

```php
$this->add_control(
	'prefix_icon_vertical_position',
	[
		'label' => esc_html__( 'Alignment', 'elementor' ),
		'type' => \Elementor\Controls_Manager::CHOOSE,
		'options' => [
			'left' => [
				'title' => esc_html__( 'Left', 'elementor' ),
				'icon' => 'eicon-text-align-left',
			],
			'center' => [
				'title' => esc_html__( 'Center', 'elementor' ),
				'icon' => 'eicon-text-align-center',
			],
			'right' => [
				'title' => esc_html__( 'Right', 'elementor' ),
				'icon' => 'eicon-text-align-right',
			],
		],
		'selectors' => [
			'{{WRAPPER}}' => 'text-align: {{VALUE}}',
		],
	]
);
```

As for your request, we have conversion function but not for control name, we have a conversion for control values.

```php
$this->add_control(
	'prefix_icon_vertical_position',
	[
		'label' => esc_html__( 'Alignment', 'elementor' ),
		'type' => \Elementor\Controls_Manager::CHOOSE,
		'options' => [
			'left' => [
				'title' => esc_html__( 'Left', 'elementor' ),
				'icon' => 'eicon-text-align-left',
			],
			'center' => [
				'title' => esc_html__( 'Center', 'elementor' ),
				'icon' => 'eicon-text-align-center',
			],
			'right' => [
				'title' => esc_html__( 'Right', 'elementor' ),
				'icon' => 'eicon-text-align-right',
			],
		],
		'selectors_dictionary' => [
			'left' => 'start',
			'right' => 'end',
		],
		'selectors' => [
			'{{WRAPPER}}' => 'text-align: {{VALUE}}',
		],
	]
);
```

**Comment by perks98** [comment]
Hi @rami-elementor,
Thanks for responding, much appreciated. Are you saying to best use a prefix to avoid overlapping another control or function on the same widget?

In terms of how the value is saved per post, is this done as metadata or is it in some JSON line somewhere?

Also is this place the right place for these types of questions?

**Comment by rami-elementor** [comment]
> Are you saying to best use a prefix to avoid overlapping another control or function on the same widget?

Yes.

> Also is this place the right place for these types of questions?

Yes.
