### ISSUE TITLE
🐞 Bug report: The title of controllers in the editor are not responsive.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19443]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the elementor editor, if the title of the controllers is long, the desired control will be out of the editor : 
![download](https://user-images.githubusercontent.com/77163248/184338420-9dcd8a9d-2b8f-457e-b034-8a80e6f682e7.png)

(This problem occurs especially in translating the editor into different languages.)

This is especially common with third-party elementor plugins. **It is better if the title of each controller is long, the title text should be moved to the second line, but the controller should not be out of the editor box.**

### Steps to reproduce

For example, add a title widget and extend the title of one of the controllers using Inspect. The controller will be out of the editor box :
![download (1)](https://user-images.githubusercontent.com/77163248/184339245-19a4560d-94c8-4a1f-a85b-f9daac7d5c30.png)
 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by arielk** [comment]
This issue is resolved for the next version 3.8

Thanks for your feedback!

**Comment by 79ho3ein** [comment]
I am glad that Elementor is more active these days than ever and that you are interacting with your users. thank you dear @arielk.
