### ISSUE TITLE
🐞 Bug report: Improve your site's performance score: Cannot "learn more" 

### ISSUE THREAD

**Issue by rtpHarry** [elementor/elementor#19448]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This banner has started appearing at the top of the site admin panels.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/1038062/184356973-663f06f3-4189-4ab9-a819-2a17e7f8a1ee.png">

The learn more button automatically closes the notice instead of opening the link.

I'm assuming its the e-notice-dismiss class which is triggering it?

### Steps to reproduce

1. Click the learn more button.
1. Banner will close instead of going to website.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

N/A

**Comment by shilo-ey** [comment]
Thanks! we will fix this.

**Comment by shilo-ey** [comment]
Hey, thank you for reporting.

This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!
