### ISSUE TITLE
✅ 🐞 Bug report: Inner Container Style: Background Slideshow is hidden when Parent container has a color assigned

### ISSUE THREAD

**Issue by SirChopper** [elementor/elementor#19449]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

With the CONTAINERS experiment enabled:
An inner container 'background type' Slideshow is hidden when the parent container has a background color selected.
Adding a z-index (1-99) to the inner container brings it back into view.

### Steps to reproduce

Make a new container.
Choose slideshow as the inner container background type and add images.
Add a color to the Parent container.
Slideshow is hidden.
Slideshow can be displayed if z-index (1-99) is added to inner container.
Note: A single image works fine if that is chosen instead.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 96M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://wordpress-540526-2740998.cloudwaysapps.com
	Home URL: https://wordpress-540526-2740998.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 96 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hello@paulchlopas.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0
		Author: Automattic

	Blackhole for Bad Bots
		Version: 3.3.3
		Author: Jeff Starr

	Breeze
		Version: 2.0.7
		Author: Cloudways

	Crocoblock Wizard
		Version: 1.2.5
		Author: Crocoblock

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	JetBlocks For Elementor
		Version: 1.3.3
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetEngine
		Version: 3.0.2
		Author: Crocoblock

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	JetPopup
		Version: 1.5.6
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.18
		Author: Crocoblock

	JetThemeCore
		Version: 2.0.5
		Author: Crocoblock

	JetTricks
		Version: 1.4.2
		Author: Crocoblock

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 4.78
		Author: MalCare Security

	WP Cerber Security, Anti-spam & Malware Scan
		Version: 9.0
		Author: Cerber Tech Inc.

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.15.2
		Author: Rhubarb Group

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 15 of 15PHP: 2022-07-08 09:15:51 [notice X 1][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::197] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-08 09:22:57 [notice X 1377][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-08 15:40:07 [notice X 3890][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-08 15:41:57 [notice X 324][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/jet-popup/includes/integration.php(134): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-08 15:41:57 [notice X 89][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/jet-theme-core/includes/elementor/manager.php(55): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-08 15:42:56 [notice X 41][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-11 14:37:01 [notice X 133][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/jet-popup/includes/elementor-finder/elementor-finder.php(47): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]
PHP: 2022-07-16 09:58:33 [notice X 2][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-18 14:33:57 [notice X 2][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-18 15:22:21 [error X 1][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/540526.cloudwaysa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 09:15:37 [warning X 1][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/files/uploads-manager.php::257] unlink(/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/uploads/elementor/tmp/62d675db85bf4/): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 15:12:50 [notice X 7][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-03 12:29:39 [notice X 1][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-11 10:07:16 [notice X 40][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/jet-popup/includes/integration.php(134): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-11 10:40:46 [notice X 6][/home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/540526.cloudwaysapps.com/myqcpemqvv/public_html/wp-content/plugins/jet-popup/includes/elementor-finder/elementor-finder.php(47): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]

JS: showing 4 of 4JS: 2022-07-18 20:11:57 [error X 34][https://wordpress-540526-2740998.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:548544] T.getContainer is not a function 
JS: 2022-07-29 08:12:50 [error X 4][https://wordpress-540526-2740998.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:508716] C.getControlModel(...) is undefined 
JS: 2022-08-02 14:06:25 [error X 1][https://wordpress-540526-2740998.cloudwaysapps.com/wp-content/plugins/elementor/assets/lib/e-gallery/js/e-gallery.min.js?ver=1.2.0:2:11113] n is undefined 
JS: 2022-08-12 11:32:34 [error X 2][https://wordpress-540526-2740998.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.7.0:3:102971] Routes: `panel/editor/global` not found. 

Log: showing 15 of 152022-07-29 08:37:11 [info] elementor::elementor_updater Started 
2022-07-29 08:37:11 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-29 08:37:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-29 08:37:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-29 08:37:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-03 10:35:52 [info] elementor-pro::elementor_pro_updater Started 
2022-08-03 10:35:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-03 10:35:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-03 10:35:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-03 10:35:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-11 10:04:30 [info] elementor::elementor_updater Started 
2022-08-11 10:04:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-11 10:04:30 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-11 10:04:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-11 10:04:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetBlocks For Elementor: Incompatible
	JetElements For Elementor: Incompatible
	JetTabs For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetBlocks For Elementor: Incompatible
	JetElements For Elementor: Incompatible
	JetTabs For Elementor: Incompatible

**Comment by 79ho3ein** [comment]
+1
I tested this, it doesn't work for me either.
Please change the title and point to the root of the problem so that developers can see it more easily.

**Comment by nicholaszein** [comment]
Hello there @SirChopper!

Thank you for reporting this issue, and for being so patient! 🙏 

I believe since you submitted this issue, it was eventually solved in one of the subsequent releases. As we prepare to make the Container stable enough for production, we are going over all Container related issues to ensure they were or can be solved in time. This is one of them.


https://user-images.githubusercontent.com/113993460/225045747-3608a01d-d1a5-46b4-8a47-8f655fe13438.mp4

----

You can safely use the Container with the latest versions of Elementor and Elementor Pro without experiencing this issue.

For now, this is it, I'm closing this issue as solved!

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
