### ISSUE TITLE
🚀 Feature Request: Export database tables for theme changes only

### ISSUE THREAD

**Issue by RacheLove** [elementor/elementor#19440]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello! I'm a solo entrepreneur building my website with Elementor.  I have limited development experience.

I was really excited about Flywheel's Local development environment until I realized that I had to "push" my entire site's database in order for Elementor's theme changes to update on my Live site.  This completely negates the option for making theme changes on Local while user content is being added to my Live site (comments especially), as I would have to overwrite the entire database on a push.

I'm seeing other peeps complain about this too:
See the comments on this blog post: https://elementor.com/blog/monday-masterclass-staging-to-live-site/
User posted issue on GitHub: https://github.com/elementor/elementor/issues/17503

### Describe the solution you'd like

My suggestion is to have a way to export *only* the database tables that Elementor updates when a theme change is made. Also, it would be cool if this option was available based on version history where you could select the version of the theme that you want to export. I'm certainly open to other ideas to resolve this.

**Comment by rami-elementor** [comment]
Hi @RacheLove ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being. Elementor is a website builder, it's not a migration tool.

Regards,
