### ISSUE TITLE
🐞 Bug report: The empty content icon is not displayed in some widgets.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19446]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In many widgets, when we add them, if there is no content to display, an empty content icon will be displayed :

![download](https://user-images.githubusercontent.com/77163248/184342760-690d5d4a-e510-492a-a3e0-72008335dd6c.png)

But in some widgets that I will mention below, the empty content icon is not displayed. So they look like the widget is broken : 

![download2](https://user-images.githubusercontent.com/77163248/184342908-4d08783f-6316-4cdb-b088-61aad9608de3.png)

**This bug exists in the following widgets :**

- portfolio
- image carousel
- base gallery
- post widgets
- video (If it is on self host)
- maps (If the address field is empty)
- In the hotspot widget, if the image is deleted, the empty content icon will be displayed, but it will not be displayed in the right place (center).
![download](https://user-images.githubusercontent.com/77163248/184343853-1cd38feb-d3d3-4696-8e50-d9dbc51a01fb.png)

- Icon widget If we remove the icon
- The icon box widget is similar to the hotspot widget (the empty content icon is not in the center)
- If you remove the numbers and title, the counter widget will be displayed in a completely different way.
- Soundcloud widget if the link field is empty
- Text Path like counter
- Sidebar widget
- Facebook Embed
- Facebook Button
- Facebook Comments

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.7.7

Feel free to update

Thanks!
