### ISSUE TITLE
🐞 Bug report: Font Awesome Inline not load in popups

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#19447]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm also having problems when there is an inline icon in the Popup, it doesn't load, it only loads if I've already called it on the page somewhere, but in the popup, it won't.

### Steps to reproduce

Create a page, then a popup (cookie consent for example) if the cookie icon is not on the page, the popup doesn't appear either.

But if I call on the page, it appears in the popup, clearly Elementor is ignoring the popup to load the information.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/WEGr2DRz

**Comment by rami-elementor** [comment]
This issue is resolved and merged to Elementor 3.8
