### ISSUE TITLE
🐞 Bug report: In version 3.7, if we paste a widget on the page, it will be added inside a section.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19452]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The explanation of the title is enough

### Steps to reproduce

In the editor, copy and paste a widget. It was added in a section.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
The latest version is Elementor 3.7

**Comment by 79ho3ein** [comment]
Hi @rami-elementor , Yes, I said it wrong. This bug exists in version 3.7.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.7.7

Feel free to update

Thanks!
