### ISSUE TITLE
🐞 Bug report: Option to add Global Widget missing in 'Edit with Elementor' interface

### ISSUE THREAD

**Issue by kraftpixel** [elementor/elementor#19458]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Currently using the latest versions of the Elementor plugin, but there is no option to save anything as a Global Widget.

### Steps to reproduce

1. Login to WordPress
2. Edit any Page in Elementor

![Screenshot 2022-08-13 at 10 34 33@2x](https://user-images.githubusercontent.com/20551501/184469363-855a2e34-d39b-4e29-9d88-293a1bf43c14.jpg)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: (Ubuntu) v5.7.33
	PHP Version: 7.4.16
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://project.gift
	Home URL: https://project.gift
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@digitalcampfire.ventures
	Debug Mode: Inactive

== Theme ==
	Name: Shoptimizer
	Version: 2.5.5
	Author: CommerceGurus
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.2
		Author: Delicious Brains

	Code Snippets
		Version: 3.2.0
		Author: Code Snippets Pro

	CommerceGurus Commercekit
		Version: 2.0.3.1
		Author: CommerceGurus

	Custom Post Type UI
		Version: 1.12.1
		Author: WebDevStudios

	DCV: Landing page handler
		Version: 0.1.0
		Author: Digital Campfire Ventures

	DCV: Order QR Code Generator
		Version: 0.1.0
		Author: Digital Campfire Ventures

	DCV: Product custom fields and preview
		Version: 0.1.0
		Author: Digital Campfire Ventures

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.6
		Author: Crocoblock

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	MB Custom Table
		Version: 2.1.1
		Author: MetaBox.io

	One Click Demo Import
		Version: 3.1.1
		Author: OCDI

	Query Monitor
		Version: 3.9.0
		Author: John Blackbourn

	Razorpay for WooCommerce
		Version: 3.9.4
		Author: Team Razorpay

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	What The File
		Version: 1.5.4
		Author: Never5

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WooCommerce Order Test - WP Fix It
		Version: 2.1
		Author: WP Fix It

== Elements Usage ==
	
	section : 1
		button : 1
		container : 1
		image : 1
	wp-post : 0
		animated-headline : 2
		button : 1
		container : 1
		heading : 5
		image : -2
		social-icons : 1
		spacer : 1
		text-editor : -24
		video : 1
	wp-page : 7
		button : 4
		heading : 19
		icon-box : 3
		image : 18
		nav-menu : 1
		shortcode : 2
		spacer : 6
		text-editor : 8

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 2 of 2PHP: 2022-06-11 04:27:35 [notice X 4][/home/proj_gift/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-11 04:39:39 [notice X 3][/home/proj_gift/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: motion_fx_transform_x_anchor_point [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-06-30 15:38:16 [error X 248][https://project.gift/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-06-30 15:38:17 [error X 3][https://project.gift/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-06-30 15:50:33 [error X 1][https://project.gift/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-08-12 19:18:16 [error X 1][https://project.gift/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.6.5:2:90835] Routes: `false` not found. 
JS: 2022-08-13 04:01:31 [error X 1][https://project.gift/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:391141] Cannot read properties of undefined (reading \'parent\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetElements For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible

**Comment by bugnumber9** [comment]
You can't save a section as a global widget.

**Comment by kraftpixel** [comment]
Acknowledged that a section cannot be saved as a global widget.

**Comment by kraftpixel** [comment]
Acknowledged that a section cannot be saved as a global widget.
