### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by MrIgorMarkovic** [elementor/elementor#19465]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Since the last update of Elementor, I have a problem on the site with elements. When I insert any element on the page, it is not attached in the form it should. the picture is attached. Please Help. [Picture link.](https://ibb.co/SKdyMXZ). Page were i have problem: https://www.vbkupatila.rs/pocetna/

### Steps to reproduce

Since the last update of Elementor, I have a problem on the site with elements. When I insert any element on the page, it is not attached in the form it should. the picture is attached. Please Help. [Picture link.](https://ibb.co/SKdyMXZ). Page were i have problem: https://www.vbkupatila.rs/pocetna/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Version of WordPress:  6.0.1
Site URL: https://www.vbkupatila.rs/
Home URL: https://www.vbkupatila.rs/
Memory Limit: 256 MB
Language: Serbian
Admin Email: webtehnologycenter@gmail.com
![Picture 1](https://user-images.githubusercontent.com/81252978/184527757-4418559d-6082-4548-9817-f3e5d9badce9.jpg)

**Comment by rami-elementor** [comment]
Hi @MrIgorMarkovic ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
