### ISSUE TITLE
🐞 Bug report: Widget spacing 0 defaults to 20px in frontend

### ISSUE THREAD

**Issue by makaus** [elementor/elementor#19480]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Setting column widget spacing to 0, sets widget spacing to 20px in front-end.

Setting it to 1, sets widget spacing to 1px in front-end.
![Screenshot 2022-08-15 at 11 36 00](https://user-images.githubusercontent.com/8776403/184613117-a1ea1046-9bff-422a-b81f-c1dcce0b72f6.png)

### Steps to reproduce

Set column widget spacing to 0, instead of default 20px.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: Percona Server (GPL), Release 41, Revision da46e5474f9 v5.7.38-41
	PHP Version: 8.1.5
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://spidshundeklubben.dk.linux81.curanetserver.dk
	Home URL: http://spidshundeklubben.dk.linux81.curanetserver.dk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Admin Email: wp@uptime.dk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Duplicate Page
		Version: 4.4.9
		Author: mndpsingh287

	Duplicator
		Version: 1.4.7.1
		Author: Snap Creek

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	JetEngine
		Version: 3.0.2
		Author: Crocoblock

	JetFormBuilder
		Version: 2.1.2
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.13
		Author: Crocoblock

	Smush
		Version: 3.10.3
		Author: WPMU DEV

	Wordfence Security
		Version: 7.6.0
		Author: Wordfence

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.1
		Author: WPCode

	WP Mail SMTP
		Version: 3.5.1
		Author: WPForms

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		icon-list : 1
		nav-menu : 3
		text-editor : 6
		theme-site-logo : 1
	header : 1
		icon : 1
		nav-menu : 1
		search-form : 1
		text-editor : 2
		theme-site-logo : 1
	page : 1
		heading : 1
		image : 1
		text-editor : 2
	wp-page : 4
		button : 6
		call-to-action : 3
		heading : 6
		image-carousel : 1
		jet-form-builder-form : 1
		jet-listing-grid : 3
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-sorting : 1
		text-editor : 16
	single-post : 1
		jet-listing-grid : 1
		theme-post-title : 1
	jet-listing-items : 0
		icon-list : 2
		image : 2
		jet-listing-dynamic-field : 13
		jet-listing-dynamic-image : 1
		jet-listing-dynamic-link : 4
	error-404 : 0

== Elementor Experiments ==
	Optimeret DOM-output: Inaktiv som standard
	Forbedret ressourceindlæsning : Inaktiv som standard
	Forbedret indlæsning af CSS ressourcer: Inaktiv som standard
	Inline Font Icons: Inaktiv som standard
	Accessibility Improvements: Inaktiv som standard
	Additional Custom Breakpoints: Inaktiv som standard
	Importer/Eksporter Kit skabelon: Aktiv som standard
	Hide native WordPress widgets from search results: Aktiv som standard
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Inaktiv som standard
	Default to New Theme Builder: Aktiv som standard
	Hello sidehoved og sidefod: Inaktiv som standard
	Landingsside: Aktiv som standard
	Color Sampler: Aktiv som standard
	Favorit widgets: Aktiv som standard
	Administrator topbjælke: Aktiv som standard
	Page Transitions: Aktiv som standard
	Notes: Aktiv som standard
	Modtagne formularer: Aktiv som standard
	Scroll Snap: Aktiv som standard

== Log ==
	
Log: showing 20 of 312022-07-19 09:29:56 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-07-19 09:29:56 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-07-19 09:29:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-19 09:29:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-07-19 09:29:56 [info] elementor::elementor_updater Started 
2022-07-19 09:29:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-19 09:29:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-19 09:29:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-19 09:29:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-08-09 12:26:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-08-09 12:26:48 [info] elementor::elementor_updater Started 
2022-08-09 12:26:48 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 12:26:48 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 12:26:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-08-09 12:28:14 [info] elementor-pro::elementor_pro_updater Started 
2022-08-09 12:28:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-09 12:28:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-09 12:28:14 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-08-09 12:28:14 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-08-09 12:28:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

PHP: showing 9 of 9PHP: 2022-07-19 09:26:26 [error X 1][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /var/www/www.spidshundeklubben.dk/www/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /var/www/www.spidshundeklubben.dk/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /var/www/www.spidshundeklubben.dk/www/wp-includes/plugin.php(476): WP_Hook->do_action()
#7 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/modules/system-info/module.php(335): do_action()
#8 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 /var/www/www.spidshundeklubben.dk/www/wp-includes/class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#12 /var/www/www.spidshundeklubben.dk/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#13 /var/www/www.spidshundeklubben.dk/www/wp-includes/plugin.php(524): WP_Hook->do_action()
#14 /var/www/www.spidshundeklubben.dk/www/wp-cron.php(138): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 09:30:40 [notice X 3][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 09:30:50 [notice X 1430][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-07-19 09:30:57 [warning X 3][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 09:31:00 [warning X 6][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 10:40:09 [error X 2][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/www.spidshundeklubben.dk/www/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/www.spidshundeklubben.dk/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/www.spidshundeklubben.dk/www/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/www.spidshundeklubben.dk/www/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-19 11:34:50 [notice X 127][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-22 10:00:37 [notice X 8][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-08-15 09:30:15 [notice X 22][/var/www/www.spidshundeklubben.dk/www/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-07-21 08:41:32 [error X 2][http://spidshundeklubben.dk.linux81.curanetserver.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897948] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-07-21 09:17:03 [error X 1][http://spidshundeklubben.dk.linux81.curanetserver.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4521\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by udidol** [comment]
Hi @makaus 
3.7.1 was released with a fix, please upgrade.

**Comment by makaus** [comment]
Alright, thank you.
I don't have any Elementor or Elementor Pro update notification on any of my sites.

**Comment by udidol** [comment]
We will check if there is a problem with the release... Please try again in a few hours.
