### ISSUE TITLE
🐞 Bug report: The custom size option in background overlay is not displayed on mobiles and tablets.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19487]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Please watch the following video :

https://user-images.githubusercontent.com/77163248/184641137-eb4d512a-b25f-4b7b-a26a-112fc838261a.mp4

As you can see in the video above, the width option is not displayed on tablets and mobile phones.

### Steps to reproduce

video

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by portrayaloflife** [comment]
Same issue here

**Comment by atwin0613** [comment]
I have another similar problem but custom position. When you open the "breakpoints"function and use background option (especially after moving the y axis), the custom setting would be failure.

**Comment by Michaelgimii** [comment]
Same issue

**Comment by 79ho3ein** [comment]
hi @shilo-ey  @rami-elementor 
In general, custom width and position controls disappear on tablet and mobile (in editor).

https://user-images.githubusercontent.com/77163248/184846731-b1f186f8-e8ed-4396-bf2b-957cc12c2c76.mp4

**Please note that this bug exists in all three sections below.**
![1](https://user-images.githubusercontent.com/77163248/184847538-21e4ccb9-f0fb-4e63-bb45-7e460b9dfa63.png)
![2](https://user-images.githubusercontent.com/77163248/184847544-603dfba1-aa48-4613-a435-8574cd9eaf33.png)
![3](https://user-images.githubusercontent.com/77163248/184847547-31c4ab34-2879-4aaf-a918-e0d6772b0c7e.png)

**Comment by mcrowell** [comment]
#17298 - This bug has been around since Dec 2021. No update if this will ever be fixed?

**Comment by perks98** [comment]
It is an odd issue. I can replicate the issue on tablet and mobile, but for the other responsive device views it does work, like laptop and extra mobile view.

![GIF 16-08-2022 15-31-16](https://user-images.githubusercontent.com/55829113/184905779-cc466d95-0e8a-459b-9ad8-ab9e4b8bb302.gif)


I tried to have a look at the backend code around this to see if I can point something out and if you comment out the following code [screenshot below] the width will work on tablet and mobile view. I think maybe this area might be redundant code as it is trying to do something specific on tablet and mobile view making the controls disappear while there is no reference to the other views which is why they work.

![Screenshot 2022-08-16 153308](https://user-images.githubusercontent.com/55829113/184906552-9974f51b-dfc4-457b-9695-8e93d2f8615c.png)

**Comment by chasperlisimba** [comment]
Same issue here! Since month no update :-/

**Comment by lennoxcreativeco** [comment]
+1 for this issue. Super frustrating.

**Comment by Vir7us** [comment]
Same issue.

**Comment by captainplod** [comment]
Also getting the same issue! Has anyone managed to fix it yet?

**Comment by portrayaloflife** [comment]
Still broken in 3.7.2

**Comment by sinnebild** [comment]
Also having this issue.
I have noticed that creating a custom breakpoint in the latest elementor version, 3.7.2, will let you set custom x-, y-position and width for that breakpoint.
So i guess the bug arrived at the same time custom breakpoints were introduced.

**Comment by erni83** [comment]
Same issue in all the background options as many people here, frustrating. Tried in different website that use elementor that have different servers, different plugin, just to give a try, and is all the issue.

**Comment by portrayaloflife** [comment]
@rami-elementor Any ETA here? Waiting to update all our sites but bug is still present

**Comment by wisites** [comment]
Same issue.. Bug is not fixed for long time ago.

**Comment by Michaelgimii** [comment]
hi Dear Elementor developers, @KingYes , @shilo-ey , @rami-elementor , @arielk , @matipojo 
Are you aware of these bugs in version 3.7? #19487 , #19542 , #19528
We appreciate that you are constantly releasing updates to improve Elementor these days. But these bugs are really important and have affected old sites that use sections. Please pay attention to these important bugs. I hope you read this issue.
thanks

**Comment by matipojo** [comment]
> hi Dear Elementor developers, @KingYes , @shilo-ey , @rami-elementor , @arielk , @matipojo Are you aware of these bugs in version 3.7? #19487 , #19542 , #19528 , #19643 We appreciate that you are constantly releasing updates to improve Elementor these days. But these bugs are really important and have affected old sites that use sections. Please pay attention to these important bugs. I hope you read this issue. thanks

Hi @Michaelgimii we are on it!

**Comment by mattmckenny** [comment]
Heads up. This "fix" breaks the frontend.

The fix in this PR ( https://github.com/elementor/elementor/pull/19677 ) to simply remove the `device_args` will fix the editor but breaks the frontend. `device_args` were removed from from the `_element_custom_width` control in includes/widgets/common.php and now custom sizing for tablet and mobile doesn't work if desktop is left as "default". 

Reference this:
https://github.com/elementor/elementor/issues/19528#issuecomment-1221177390

**Comment by captainplod** [comment]
Hello - any update on this please? I cannot style the background overlays correctly for many of my clients sites!

**Comment by portrayaloflife** [comment]
@captainplod Looks like they're pushing with 3.8 which I assume will have its own brand new handful of bugs we'll have to wait for them to fix... -_-

**Comment by 79ho3ein** [comment]
hi @portrayaloflife , As @udidol mentioned, an update for this bug is coming soon. But I don't know if the fix for this bug will be released in 3.7.5, or 3.8

**Comment by atwin0613** [comment]
It seems like a new update 3.7.5 Version has been released, the "custom option" has appeared, but the x-axis still not working  after moving the y-axis.🥲🥲

**Comment by Urgul69** [comment]
Same here. In 3.7.5 the controls are visible again on mobile and tablet but the x-axis isn't working at all!

**Comment by udidol** [comment]
@atwin0613 @Urgul69 
So it is true, there is indeed another bug.
The bug is that the X axis value is only taken from the front-end.
This is actually a system-wide bug with a certain case of CSS generation (where one control's value is used in another control) that has existed for a very long time, and fixing the responsive control conditions issue exposed it.

A fix for this newly discovered issue should be released in the next upcoming patch.

**Comment by matipojo** [comment]
Hi, @atwin0613 and @Urgul69 
It's a known issue, we're already working on a fix.

**Comment by 79ho3ein** [comment]
hi @udidol, Thank you very much for your attention.
Please check this[](https://github.com/elementor/elementor/issues/19809)  if possible. Thank you

**Comment by chasperlisimba** [comment]
@udidol Do you have an ETA for this fix? Because we are blocked with our projects at the moment...

**Comment by udidol** [comment]
@chasperlisimba
The custom background size option works.
Only the custom background position (X, Y) doesn't work at the moment.
ETA - I hope it will be sometime next week, could be a bit later, but I cannot make any promises.

**Comment by 79ho3ein** [comment]
> hi @udidol, Thank you very much for your attention.
Please check this if possible. Thank you

oh, I apologize @udidol , I forgot to post the link : https://github.com/elementor/elementor/issues/19809

**Comment by atwin0613** [comment]
@udidol 
I've got it! And the custom background X/Y position seems doesn't work properly in "breakpoint fuction" too.
Thanks for your attention and kindly instant reply😁.
We are looking forward to it and grateful for your support.

**Comment by RD1844** [comment]
Hello, Since the 3.7.7 update - the widgets panel becomes blank when there is an attempt to edit any, Also not changes are saved.
See screen record below

https://screenrec.com/share/LleZdqI9P5

**Comment by udidol** [comment]
@RD1844 you can update to v3.7.8 which has fixes related to this issue
