### ISSUE TITLE
🐞 Bug report: bad UX in text editor widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19489]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the text editor widget, if the mouse is on [these parts](https://prnt.sc/ccN5ss_NzyI3), it is not possible to navigate in the settings of this widget. 
Please fix this. It is very annoying.

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by arielk** [comment]
I can't reproduce this issue, please try deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

And see if the issue still persists.

**Comment by Michaelgimii** [comment]
hi @arielk , I only use Elementor and Elementor Pro. I also use the Hello Elementor theme. Maybe you're using a MacBook and I'm guessing this problem doesn't exist on a Mac. So I will explain this issue in more detail.

in text editor widget, If you hover over [these areas](https://prnt.sc/oFGsRIjwkpzR) and try to scroll through the editor using the [scroll wheel](https://prnt.sc/6qpna0StLzRB), the page will not scroll unless you hover over [these areas](https://prnt.sc/hdgI0svxwgo9) and then scroll.

In general, according to the previous screenshot, if the mouse is on the red areas of this widget, it cannot be scrolled.
