### ISSUE TITLE
🐞 Bug report: Elementor 3.7.1 number issue when using Flexbox.

### ISSUE THREAD

**Issue by mbaierl** [elementor/elementor#19500]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Please see ([#19410](https://github.com/elementor/elementor/issues/19410), [#19391](https://github.com/elementor/elementor/issues/19391), [#19393](https://github.com/elementor/elementor/issues/19393), [#19386](https://github.com/elementor/elementor/issues/19386)) - all not fixed when using Flexbox.

### Steps to reproduce

See the other tickets.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

n/a

**Comment by m1ga** [comment]
Hi, since you write something about "10px padding" in the other tickets: did you change the `container padding` value? It is default to 10px if you don't set anything. Setting it to 0 works fine for me.
