### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by salsalex2001** [elementor/elementor#19505]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the text block, when the block contains text and a picture, the drop cap is ineffective.

### Steps to reproduce

Create a text block in a page or post.
Write or paste some text.
Paste a picture, and align it on the righ border.
Activate the drop cap slider-button.
--> The drop cap IS NOT modified, the letter remains unchanged.

When there is no picture, the drop ap works as expected.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.38
	PHP Version: 7.3.32
	PHP Memory Limit: 512M
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://www.authentiqueavecsoi.com/mystaging04
	Home URL: https://www.authentiqueavecsoi.com/mystaging04
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Paris
	Admin Email: salsalex2001@icloud.com
	Debug Mode: Inactive

== Theme ==
	Name: Kadence
	Version: 1.1.25
	Author: Kadence WP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	Disable Comments
		Version: 2.4.1
		Author: WPDeveloper

	Duplicate Page
		Version: 4.4.9
		Author: mndpsingh287

	Duplicator
		Version: 1.4.7.2
		Author: Snap Creek

	Elementor
		Version: 3.7.1
		Author: Elementor.com

	iThemes Security
		Version: 8.1.2
		Author: iThemes

	Kadence Blocks – Gutenberg Blocks for Page Builder Features
		Version: 2.4.13
		Author: Kadence WP

	Kadence Starter Templates
		Version: 1.2.14
		Author: Kadence WP

	Maintenance
		Version: 4.06
		Author: WebFactory Ltd

	Styler for WPForms
		Version: 2.0.4
		Author: Sushil Kumar

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.33
		Author: Sucuri Inc.

	The Events Calendar
		Version: 5.16.4
		Author: The Events Calendar

	WPForms Lite
		Version: 1.7.5.5
		Author: WPForms

	WPvivid Backup Plugin
		Version: 0.9.76
		Author: WPvivid Team

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast

== Must-Use Plugins ==
	SecuPress COOKIEHASH
		Version: 1.0
		Author: 

	SecuPress Salt Keys
		Version: 1.0.1
		Author: 

== Elements Usage ==
	
	wp-page : 8
		accordion : 3
		button : 5
		google_maps : 1
		heading : 26
		icon : 3
		image : 14
		menu-anchor : 6
		sidebar : 1
		social-icons : 1
		spacer : 11
		tabs : 2
		text-editor : 102
		toggle : 14
		video : 1
		wp-widget-tribe-widget-events-list : 2
		wpforms : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 402022-07-12 17:24:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.7',
)]
2022-07-27 17:17:25 [info] elementor::elementor_updater Started 
2022-07-27 17:17:25 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 17:17:25 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 17:17:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 17:17:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-09 18:00:20 [info] elementor::elementor_updater Started 
2022-08-09 18:00:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 18:00:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 18:00:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-09 18:00:21 [info] elementor::elementor_updater Started 
2022-08-09 18:00:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 18:00:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 18:00:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-09 18:00:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-16 16:23:32 [info] elementor::elementor_updater Started 
2022-08-16 16:23:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-16 16:23:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-16 16:23:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-16 16:23:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]

PHP: showing 2 of 2PHP: 2022-07-31 17:02:59 [error X 3][/home/authenp/www/mystaging04/wp-content/plugins/elementor/core/documents-manager.php::533] Uncaught Error: Call to a member function get_post() on bool in /home/authenp/www/mystaging04/wp-content/plugins/elementor/core/documents-manager.php:533
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/authenp/www/mystaging04/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/authenp/www/mystaging04/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/authenp/www/mystaging04/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /home/authenp/www/mystaging04/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#5 /home/authenp/www/mystaging04/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-01 16:51:09 [error X 2][/home/authenp/www/mystaging04/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/authenp/www/mystaging04/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/authenp/www/mystaging04/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/authenp/www/mystaging04/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/authenp/www/mystaging04/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/authenp/www/mystaging04/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/authenp/www/mystaging04/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /home/aut [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-07-31 15:11:48 [error X 13][https://www.authentiqueavecsoi.com/mystaging04/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.8:3:900527] V is null 

== Elementor - Compatibility Tag ==

**Comment by rami-elementor** [comment]
@salsalex2001 It's not an Elementor issue, it's a browser issue. We can't fix browser behavior.

But you can create a different layout for your page using Elementor.

**Comment by rami-elementor** [comment]
Also, next time please add a heading to github issues.

**Comment by salsalex2001** [comment]
Humm quite easily closed here ! Thee is no such issue with DIVI, in the same browser …..

Any evidence it's a broker issue ? FIY the page displays the same with FFox, Safari and Chrome…
