### ISSUE TITLE
🐞 Bug report: Repeater control within another repeater control

### ISSUE THREAD

**Issue by tom-cwa** [elementor/elementor#19514]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When creating my own widget, whenever I'm trying to use a repeater control within another repeater control, I get the following fatal error: 
```
Fatal error: Uncaught TypeError: Argument 3 passed to Elementor\Core\Files\CSS\Post::add_controls_stack_style_rules() must be of the type array, null given, called in /wp-content/plugins/elementor/core/files/css/base.php on line 793 and defined in /wp-content/plugins/elementor/core/files/css/post.php on line 221
```

The solution I came up with which resolve this issue is to replace one line of code in the following method:

In *wp-content/plugins/elementor/core/files/css/base.php* at line 784

Replace
```php
protected function add_repeater_control_style_rules( Controls_Stack $controls_stack, array $repeater_control, array $repeater_values, array $placeholders, array $replacements ) {
		$placeholders = array_merge( $placeholders, [ '{{CURRENT_ITEM}}' ] );

		foreach ( $repeater_control['style_fields'] as $index => $item ) {
			$this->add_controls_stack_style_rules(
				$controls_stack,
				$item,
				$repeater_values[ $index ], // change this line...
				$placeholders,
				array_merge( $replacements, [ '.elementor-repeater-item-' . $repeater_values[ $index ]['_id'] ] ),
				$repeater_control['fields']
			);
		}
	}
```
By
```php
protected function add_repeater_control_style_rules( Controls_Stack $controls_stack, array $repeater_control, array $repeater_values, array $placeholders, array $replacements ) {
		$placeholders = array_merge( $placeholders, [ '{{CURRENT_ITEM}}' ] );

		foreach ( $repeater_control['style_fields'] as $index => $item ) {
			$this->add_controls_stack_style_rules(
				$controls_stack,
				$item,
				$repeater_values[ $index ] ?: [], // ...to this line
				$placeholders,
				array_merge( $replacements, [ '.elementor-repeater-item-' . $repeater_values[ $index ]['_id'] ] ),
				$repeater_control['fields']
			);
		}
	}
```

### Steps to reproduce

See below how I proceed to register repeater controls in my widget:

```php
protected function register_controls()
    {
        $this->start_controls_section(
            'content_section',
            [
                'label' => 'Contenu',
                'tab'   => Controls_Manager::TAB_CONTENT
            ]
        );

        $tabs = new Repeater();

        $tabs->add_control(
            'title',
            [
                'label'         => 'Titre',
                'type'          => Controls_Manager::TEXT,
                'label_block'   => true,
                'default'       => "# Titre onglet"
            ]
        );

        $items = new Repeater();

        $items->add_control(
            'profil',
            [
                'label'     => 'Image',
                'type'      => Controls_Manager::MEDIA,
                'default'   => [
                    'url'       => Utils::get_placeholder_image_src(),
                ],
            ]
        );

        $items->start_controls_tabs('content_tabs');

        $items->start_controls_tab(
            'front_tab',
            [
                'label' => 'Prévisualisation'
            ]
        );

        $items->add_control(
            'name',
            [
                'label'         => 'Nom',
                'type'          => Controls_Manager::TEXT,
                'label_block'   => true
            ]
        );

        $items->add_control(
            'job',
            [
                'label' => 'Poste(s)',
                'type'  => Controls_Manager::WYSIWYG,
            ]
        );

        $items->end_controls_tab();

        $items->start_controls_tab(
            'back_tab',
            [
                'label' => 'Contenu'
            ]
        );

        $items->add_control(
            'logo',
            [
                'label'     => 'Logo',
                'type'      => Controls_Manager::MEDIA
            ]
        );

        $items->add_control(
            'content',
            [
                'label' => 'Contenu',
                'type'  => Controls_Manager::WYSIWYG,
            ]
        );

        $items->add_control(
            'phone',
            [
                'label' => 'Téléphone',
                'type'  => Controls_Manager::TEXT,
                'label_block'   => true
            ]
        );

        $items->end_controls_tab();

        $items->end_controls_tabs();

        $tabs->add_control(
            'persons',
            [
                'label'         => 'Personnes',
                'type'          => Controls_Manager::REPEATER,
                'fields'        => $items->get_controls(),
                'title_field'   => '{{{ name }}}',
                'default'       => [
                    [
                        'name'      => 'John Smith',
                        'profil'    => [
                            'url'       => Utils::get_placeholder_image_src(),
                        ]
                    ]
                ]
            ]
        );

        $this->add_control(
            'tabs',
            [
                'label'         => 'Sliders',
                'type'          => Controls_Manager::REPEATER,
                'fields'        => $tabs->get_controls(),
                'title_field'   => '{{{ title }}}',
                'default'       => [
                    [ 'title' => '# Titre 1' ],
                    [ 'title' => '# Titre 2' ],
                ],
                'prevent_empty' => false
            ]
        );

        $this->end_controls_section();
}
```

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.38
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://www.cap-sciences.net
	Home URL: https://www.cap-sciences.net
	WP Multisite: No
	Max Upload Size: 100 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: tom@agence-cwa.fr
	Debug Mode: Inactive

== Theme ==
	Name: Cap Sciences
	Version: 0.1.0
	Author: Tom CWA
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Akeeba Backup for WordPress
		Version: 7.6.10
		Author: Akeeba Ltd

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	CWA - Feed Social Networks
		Version: 1.0
		Author: Agence CWA

	CWA Addons Pour Elementor
		Version: 1.0.1
		Author: Agence CWA

	CWA Custom Fields
		Version: 1.0.2
		Author: Tom CWA

	Cwa Map Intéractive
		Version: 1.0.0
		Author: Cwa

	Cwa Récréatex
		Version: 1.0.0
		Author: Cwa

	CWA Web'Inclusion
		Version: 1.0
		Author: Agence CWA

	Elementor
		Version: 3.7.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	Polylang
		Version: 3.2.5
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 2.3.0
		Author: Creame

	Redirection
		Version: 5.3.2
		Author: John Godley

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast

== Must-Use Plugins ==
	akeeba-backup-coreupdate.php
		Version: 
		Author: 

== Utilisation des éléments ==
	
	footer : 4
		button : 3
		copyright : 2
		graphic-element : 1
		heading-colors : 7
		icon-list : 2
		image : 3
		image-mosaic : 2
		nav-menu : 6
		newsletter : 2
		spacer : 1
		stripes : 1
		text-editor : 1
	header : 4
		custom-menu : 2
		header-bottom : 1
		highlighted : 1
		shortcode : 2
		social-networks-links : 2
		theme-site-logo : 2
	page : 18
		accordion : 1
		activity-list : 1
		affiche : 1
		banner : 5
		billetterie : 1
		breadcrumbs : 3
		bubble : 5
		button : 3
		collaborateurs : 3
		color-block : 1
		cwa-maps : 3
		cwa-team : 3
		detached-tabs : 2
		files-download : 1
		form : 1
		graphic-element : 24
		header-bottom : 4
		heading : 4
		heading-colors : 26
		icon-list : 2
		image : 2
		image-mosaic : 3
		image-slider : 1
		list-icon-infos : 1
		related-activities : 1
		slider-step : 1
		social-networks : 1
		spacer : 13
		stripes : 4
		text-editor : 17
		video : 1
	section : 34
		accordion : 3
	widget : 0
		accordion : 1
		button : 1
		collaborateurs : 1
	wp-post : 0
		accordion : 15
		affiche : 23
		banner : 23
		billetterie : 12
		breadcrumbs : 23
		bubble : 3
		button : 6
		collaborateurs : 4
		color-block : 21
		files-download : 2
		graphic-element : 42
		header-bottom : 23
		heading : 77
		heading-colors : 101
		image-mosaic : 10
		image-slider : 4
		list-icon-infos : 23
		related-activities : 21
		resume-datas : 2
		slider-step : 9
		social-networks : 17
		spacer : 94
		stripes : 33
		text-editor : 75
		video : 4
	wp-page : 89
		accordion : 18
		activity-list : 16
		affiche : 1
		animate-text-colors : 1
		banner : 60
		breadcrumbs : 48
		bubble : 14
		button : 7
		collaborateurs : 33
		color-block : 7
		counter : 3
		cwa-faq : 1
		cwa-maps : 5
		cwa-onglets : 1
		cwa-portfolio : 1
		cwa-team : 4
		cwa-testimonials : 1
		detached-tabs : 10
		files-download : 11
		graphic-element : 78
		header-bottom : 61
		heading : 25
		heading-colors : 148
		icon-box : 5
		icon-list : 5
		image : 10
		image-carousel : 4
		image-links-list : 1
		image-mosaic : 7
		image-slider : 2
		infos-slider : 1
		list-icon-infos : 7
		multiple-content-tabs : 1
		offers-tabs : 2
		page-slider : 8
		presse : 5
		resume-datas : 5
		sitemap : 1
		sliders-tabs : 4
		spacer : 70
		stripes : 15
		text-editor : 89
		video-slider : 7
		visit-card-list : 1
	error-404 : 1
		banner : 1
		breadcrumbs : 1
		button : 1
		header-bottom : 1
		heading : 1

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Inactif
	En-tête et pied de page du thème Hello: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Envois de formulaire: Actif par défaut
	Scroll Snap: Actif par défaut

== Journal ==
	
Log: showing 20 of 292022-06-30 12:29:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-05 10:39:51 [info] elementor-pro::elementor_pro_updater Started 
2022-08-05 10:39:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-05 10:39:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-05 10:39:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-05 10:39:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-05 10:40:18 [info] elementor::elementor_updater Started 
2022-08-05 10:40:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-05 10:40:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-05 10:40:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.8',
)]
2022-08-09 08:40:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-09 08:40:21 [info] elementor::elementor_updater Started 
2022-08-09 08:40:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 08:40:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 08:40:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-17 11:36:44 [info] elementor::elementor_updater Started 
2022-08-17 11:36:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-17 11:36:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-17 11:36:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-17 11:36:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]

PHP: showing 4 of 4PHP: 2022-06-30 20:25:06 [error X 142][/home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/post.php::221] Uncaught TypeError: Argument 3 passed to Elementor\Core\Files\CSS\Post::add_controls_stack_style_rules() must be of the type array, null given, called in /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/base.php on line 753 and defined in /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/post.php:221
Stack trace:
#0 /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/base.php(753): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules()
#1 /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/base.php(513): Elementor\Core\Files\CSS\Base->add_repeater_control_style_rules()
#2 /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/post.php(222): Elementor\Core\Files\CSS\Base->add_controls_stack_style_rules()
#3 /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/base.php(753): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules()
#4 /home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/base.p [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 12:05:46 [notice X 1][/home/capsciencnet/www/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-21 10:49:31 [warning X 20][/home/capsciencnet/www/wp-content/plugins/elementor/core/files/css/base.php::871] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-09 08:41:35 [notice X 9][/home/capsciencnet/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2022-07-01 08:20:00 [error X 1][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:21409] undefined has no properties 
JS: 2022-07-01 12:55:09 [error X 434][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:21430] Cannot read properties of undefined (reading \'each\') 
JS: 2022-07-08 13:06:16 [error X 5][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-07-18 14:38:08 [error X 1][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:21409] o.attributes[a.name] is undefined 
JS: 2022-07-19 15:12:23 [error X 1][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:382071] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-07-26 13:51:33 [error X 1][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view322\") has already been destroyed and cannot be used. 
JS: 2022-07-26 13:51:33 [error X 1][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1781\") has already been destroyed and cannot be used. 
JS: 2022-07-29 07:06:39 [error X 10][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.6:2:21430] o.attributes[a.name].each is not a function 
JS: 2022-08-09 12:29:43 [error X 2][https://www.cap-sciences.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:766045] Cannot read properties of undefined (reading \'toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	CWA Addons Pour Elementor: Compatibilité non spécifiée
	Elementor Pro: Compatibilité non spécifiée
	Polylang Connect for Elementor: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==

**Comment by udidol** [comment]
Repeaters within repeaters are not supported.
