### ISSUE TITLE
✅ 🚀 Feature Request: Multi Select

### ISSUE THREAD

**Issue by FODTannis** [elementor/elementor#19519]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm frustrated when I have to move/edit multiple elements/columns for the same change ie. padding margin etc.

### Describe the solution you'd like

I would say one thing that would be pretty cool would be a multi-select toggle similar to how photoshop. I wouldn't say exactly how photoshop has it but it's cool because you can enable your cursor to select multiple elements and style those similarly, additionally you can move multiple objects at the same time.

I envision a enable multi-select box or something where you can toggle it on and off, then you can just select which elements/sections/columns and move them and or style them. I know there is a global widget setting but this would make it easier when you have a lot of similar elements on a single page that you want to move or style.

**Comment by nicholaszein** [comment]
Hello there @FODTannis!

While triaging GitHub issues, I found out that your request was partially solved with the release of Elementor v3.5.

You can now multi-select elements, copy and paste them, paste a style from one element to multiple others, and delete multiple elements.

For full details on how this feature works, please check the documentation [here](https://elementor.com/help/multi-select-feature/).

✅ Feel free to check it out and update your plugin to the new version if you haven't already!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
