### ISSUE TITLE
🐞 Bug report: elemenator style & advance tabs not working

### ISSUE THREAD

**Issue by ahmed6985** [elementor/elementor#19523]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i edit with elementor, style and advance tabs does not work.
![Annotation 2022-08-17 232926](https://user-images.githubusercontent.com/111486427/185309659-09a45a74-c359-4c88-9500-4a00add69562.png)

### Steps to reproduce

![Uploading Annotation 2022-08-17 232926.png…]()

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.51 (Win32) PHP/7.4.26
	MySQL version: MySQL Community Server (GPL) v5.7.36
	PHP Version: 7.4.26
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://localhost/demo
	Home URL: http://localhost/demo
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: sajjad909910@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty
	Version: 2.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.8.0-dev3
		Author: Elementor.com

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
PHP: showing 1 of 1PHP: 2022-08-17 09:00:48 [error X 1][C:\wamp\www\demo\wp-content\plugins\elementor\includes\managers\skins.php::4] Maximum execution time of 120 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-08-17 09:07:46 [error X 342][http://localhost/demo/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.7.1:3:108866] C.replaceAll is not a function 

Log: showing 5 of 52022-08-18 05:54:38 [info] elementor::elementor_updater Started 
2022-08-18 05:54:38 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-18 05:54:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-18 05:54:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.8.0-dev3',
)]
2022-08-18 05:54:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.8.0-dev3',
)]

== Elementor - Compatibility Tag ==

**Comment by VadimR7** [comment]
I have the same issue after updating to the latest version of PRO.

**Comment by ahmed6985** [comment]
Hi
This is browser issue. Change your default browser from chrome to edge.

**Comment by ishnechmad** [comment]
I have the same problem now on the pro version (not dev) after upgrading to version 3.7.2
