### ISSUE TITLE
🐞 Bug report: removing advanced breakpoints mobile extra, tablet extra and laptop

### ISSUE THREAD

**Issue by Veltix** [elementor/elementor#19536]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I removed mobile extra, tablet extra and laptop.
Tried even disable advanced breakpoints feature, still same issue.

Error:
PHP: 2022-08-19 11:30:46 [error X 1][/www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/breakpoints/manager.php::233] Uncaught Error: Call to a member function get_direction() on null in /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/breakpoints/manager.php:233
Stack trace:
#0 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/includes/stylesheet.php(326): Elementor\Core\Breakpoints\Manager->get_device_min_breakpoint('laptop')
#1 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/includes/stylesheet.php(357): Elementor\Stylesheet->hash_to_query(Array)
#2 [internal function]: Elementor\Stylesheet->Elementor\{closure}('min_laptop', 'max_mobile')
#3 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/includes/stylesheet.php(384): uksort(Array, Object(Closure))
#4 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/includes/stylesheet.php(149): Elementor\Stylesheet->add_query_hash('max_mobile')
#5 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/base.php(423): Elementor\Stylesheet->add_rules('.elementor-2103...', 'width: 50%;', Array)
#6 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/base.php(674): Elementor\Core\Files\CSS\Base->add_control_rules(Array, Array, Object(Closure), Array, Array, Array)
#7 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/base.php(543): Elementor\Core\Files\CSS\Base->add_control_style_rules(Array, Array, Array, Array, Array)
#8 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(222): Elementor\Core\Files\CSS\Base->add_controls_stack_style_rules(Object(Elementor\Widget_Image), Array, Array, Array, Array, Array)
#9 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Widget_Image), Array, Array, Array, Array)
#10 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Widget_Image))
#11 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Column), Array, Array, Array, Array)
#12 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(226): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Column))
#13 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(298): Elementor\Core\Files\CSS\Post->add_controls_stack_style_rules(Object(Elementor\Element_Section), Array, Array, Array, Array)
#14 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\Files\CSS\Post->render_styles(Object(Elementor\Element_Section))
#15 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/base.php(636): Elementor\Core\Files\CSS\Post->render_css()
#16 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content()
#17 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/base.php(130): Elementor\Core\Files\Base->update_file()
#18 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/base.php(217): Elementor\Core\Files\CSS\Base->update()
#19 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue()
#20 /www/apache/domains/www.mydomain.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(93): Elementor\Core\Files\CSS\Post->enqueue()
#21 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->enqueue_styles('')
#22 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#23 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#24 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/script-loader.php(2156): do_action('wp_enqueue_scri...')
#25 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('')
#26 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#27 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#28 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/general-template.php(3042): do_action('wp_head')
#29 /www/apache/domains/www.mydomain.com/htdocs/wp-content/themes/bazien/header.php(9): wp_head()
#30 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/template.php(770): require_once('/www/apache/dom...')
#31 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/template.php(716): load_template('/www/apache/dom...', true, Array)
#32 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#33 /www/apache/domains/www.mydomain.com/htdocs/wp-content/themes/bazien/page.php(1): get_header()
#34 /www/apache/domains/www.mydomain.com/htdocs/wp-includes/template-loader.php(106): include('/www/apache/dom...')
#35 /www/apache/domains/www.mydomain.com/htdocs/wp-blog-header.php(19): require_once('/www/apache/dom...')
#36 /www/apache/domains/www.mydomain.com/htdocs/index.php(17): require('/www/apache/dom...')
#37 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

### Steps to reproduce

I had additional custom breakpoints active then edited page with elementor. Then I clicked responsive mode. Up right clicked "Manage breakpoints". Then removed mobile extra, tablet extra and laptop breakpoints (x).

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: FreeBSD
	Software: Apache
	MySQL version: FreeBSD Ports v10.4.25
	PHP Version: 8.0.20
	PHP Memory Limit: 384M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://mahkmed.eu
	Home URL: https://mahkmed.eu
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 384M
	Permalink Structure: /%postname%/
	Language: et
	Timezone: 0
	Admin Email: liis@**********.com
	Debug Mode: Inactive

== Theme ==
	Name: MALL
	Version: 1.0
	Author: mAll
	Child Theme: Yes
	Parent Theme Name: Bazien
	Parent Theme Version: 4.0.4
	Parent Theme Author: Novaworks

== User ==
	Role: administrator
	WP Profile lang: et
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Category Order and Taxonomy Terms Order
		Version: 1.7.1
		Author: Nsp-Code

	E-Abi Omniva Shipping method plugin
		Version: 1.10
		Author: Matis Halmann, Aktsiamaailm LLC

	E-Abi Woocommerce Itella Estonia Autosend method plugin
		Version: 1.14
		Author: Matis Halmann, Aktsiamaailm LLC

	E-Abi Woocommerce Itella Shipping method plugin
		Version: 1.19
		Author: Matis Halmann, Aktsiamaailm LLC

	E-Abi Woocommerce Omniva Autosend method plugin
		Version: 1.18
		Author: Matis Halmann, Aktsiamaailm LLC

	Elementor
		Version: 3.7.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.19.0
		Author: FiboSearch Team

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	GTM4WP
		Version: 1.16.1
		Author: Thomas Geiger

	Headers Security Advanced & HSTS WP
		Version: 5.0.01
		Author: 🐙  Andrea Ferro, Augusto Bombana

	Imagify
		Version: 2.0
		Author: Imagify - Optimize Images & Convert WebP

	Include Klaviyo for Elementor pro
		Version: 1.1.1
		Author: Thong Nguyen

	JetSearch
		Version: 3.0.2
		Author: Crocoblock

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	Klaviyo
		Version: 3.0.3
		Author: Klaviyo, Inc.

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	Max Mega Menu
		Version: 2.9.8
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.2.1
		Author: megamenu.com

	Modena
		Version: 2.0.0
		Author: Modena Estonia OÜ

	Montonio for WooCommerce
		Version: 4.1.8
		Author: Montonio

	Mähkmed Funktsionaalsus
		Version: 1.0.0
		Author: Kristen Lõoke (vDisain)

	Novaworks
		Version: 1.0.4
		Author: Novaworks

	Patchstack Security
		Version: 2.1.21
		Author: Patchstack

	Slider Revolution
		Version: 6.4.11
		Author: ThemePunch

	Smooth Back To Top Button
		Version: 1.1.6
		Author: Tanvirul Haque

	UpdraftPlus - Backup/Restore
		Version: 1.22.14
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 6.8.1
		Author: Automattic

	Woocommerce E-Abi Postoffice plugin
		Version: 1.61
		Author: Matis Halmann, Aktsiamaailm LLC

	WooCommerce PayPal Payments
		Version: 1.9.2
		Author: WooCommerce

	Woocommerce Sale Discount Scheduler
		Version: 1.5
		Author: Geek Code Lab

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

	Woocommerce Sidebar Category Accordion
		Version: 1.1.3
		Author: Marc Randall

	Wordfence Security
		Version: 7.6.0
		Author: Wordfence

	WPC Custom Related Products for WooCommerce
		Version: 2.0.3
		Author: WPClever

	WP Hardening
		Version: 1.2.5
		Author: Astra Security

	WP Rocket
		Version: 3.11.5
		Author: WP Media

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Include Klaviyo for Elementor pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
