### ISSUE TITLE
🐞 Bug report: important bug in elementor 3.7 - section

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19542]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Before updating to 3.7, I had a section and added 4 icon widgets inside it. I had considered the width of each 25%. **(The important bit here is that I entered a width of 25% for tablet mode so that it will be inherited on mobile. But it was the default desktop)**

### Steps to reproduce

1- Add a section and add 4 icon widgets inside it.
2- To determine the width of the icons, enter the tablet mode and consider the width of each icon to be 25%.
3- Now view the website with your mobile phone. 25% width is ignored and icons are compressed to one side.

**some notes**
A: If we enter the width of icon widgets first in desktop mode, this bug does not occur. But if we enter it first in the tablet, the width is ignored in the mobile and the icons are compressed on one side.
B : Everything is fine in the editor. But if you view the website on mobile, the situation is not good.

Please watch the video below : 

https://user-images.githubusercontent.com/77163248/185743746-4d07dd02-ed76-4cf9-aed4-0f176822bb74.mp4

@shilo-ey , Please let me know if you are not successful in reproducing. I tested this bug on 2 websites.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by 79ho3ein** [comment]
one more thing...

In the section, in **tablet and mobile mode**, add a section and place an icon in it and set the width of the icon to 25%, if I duplicate the icon up to 4, the height of the last icon is abnormal. Please watch the video below :

https://user-images.githubusercontent.com/77163248/185743346-62946fee-6148-4071-aa9e-9668df0dd837.mp4

**Comment by m1ga** [comment]
@79ho3ein about the last video:

https://user-images.githubusercontent.com/4334997/185747074-deb23df1-ef49-4507-8423-99813c79cf25.mp4

are you sure that there is no style that affects the last item in your container?

**Comment by 79ho3ein** [comment]
hi @m1ga
Yes, I'm sure. Actually I have this problem in the section. But you tested it in the container.

**Comment by m1ga** [comment]
ohhh...my bad :smile: I thought you are #containerCrew too :smile:

**Comment by 79ho3ein** [comment]
> ohhh...my bad 😄 I thought you are #containerCrew too 😄

I'm very interested in the container and I'm waiting for it to be released to a stable version. But currently my sites use section. Unfortunately, of course

**Comment by Michaelgimii** [comment]
+1

**Comment by Michaelgimii** [comment]
Hello guys
@matipojo said they are working on it. We have to wait for an update for it.

**Comment by Michaelgimii** [comment]
hi @rami-elementor , Is there any update coming for this issue? This is a fatal error that breaks existing sites. Generally, custom width is ignored on tablet and mobile.

**Comment by udidol** [comment]
A fix for this issue will be released in an upcoming patch version.

**Comment by choijun** [comment]
Hi @udidol do you know when this patch will be applied ?

**Comment by udidol** [comment]
@choijun Should be release in the next patch, probably within the next few days

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.7.7

Feel free to update

Thanks!
