### ISSUE TITLE
🐞 Bug report: favicon are not displayed on pages created with Elementor. (version 3.7)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19541]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi
After updating Elementor to 3.7, the fav icon is not displayed on pages edited with Elementor. This bug occurs in theme builder templates and  pages.

### Steps to reproduce

1- Make sure you include a favicon for your website.
2- Create a sheet and test it with Gutenberg first. Favicon is displayed.
3- Now click Edit with Elementor. After opening the Elementor editor, the favicon is not displayed.

**As I mentioned above, this bug exists in the header, footer, pop-up and all the Elementor theme Builder templates.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Windows - Chrome browser

**Comment by rami-elementor** [comment]
If it's inside the Elementor Editor, the favicon is not relevant.

Closing the issue. We are not going to fix this as it is not breaking websites.
