### ISSUE TITLE
🐞 Bug report: Fatal Error > Uncaught TypeError: Unsupported operand types: string * float [ED-8155]

### ISSUE THREAD

**Issue by andrewnotari** [elementor/elementor#19546]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Uncaught TypeError: Unsupported operand types: string * float
Better details: https://wordpress.org/support/topic/typeerror-unsupported-operand-types-string-float/

### Steps to reproduce

Set custom image size

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/Bgygyqfs

**Comment by artuze** [comment]
For what it's worth, I've been having a bit of [a discussion](https://wordpress.org/support/topic/typeerror-unsupported-operand-types-string-float/) about this same issue over in the WordPress plugin support forum.

Basically, there's a regex in includes/controls/groups/image-size.php that's pulling the one or two dimensions out of the image size name and shoving that into the array of additional image sizes. Normally fine, but it's putting them in there as strings, so underlying WordPress functions are trying, somewhere, to do a comparison of image sizes and having an issue with the string vs. number comparison and throwing a TypeError.

Easiest fix going forward is a couple of `(int)`s thrown in there. But that doesn't fix the already broken values saved in the postmeta. For that, you'd need an upgrade script that searches them all out (`select * from wp_postmeta where meta_key="wp_attachment_metadata" and meta_value like '%s:5:"width";s:'` or something like that), changes the type of all the widths and heights, and resaves that postmeta.

**Comment by andrewnotari** [comment]
Really thanks @artuze 

Confirm that it is an issue with PHP 8.X compatibility.
It’s not server configuration.
Confirm that use PHP 7.4 isn’t a solution to the issue.

**Comment by bredington** [comment]
Just following up as I have a Wordpress site that is getting the same error. Is there a solution or fix incoming?

**Comment by zohaibtahir** [comment]
I also face the same issue. please anybody response with the correct solution ASAP.

**Comment by jetbautista** [comment]
I have same issue, my temporary solution is to downgrade my php version to 7.4.

**Comment by ARod84** [comment]
I have the same issue on a WP Engine Server running PHP 8. The downgrade is not an option for my client and we have several sites running elementor on this server. This error displays when a user edits the site, so if anyone have an alternative temporary solution would be appreciated it.

**Comment by amichaidani** [comment]
Any help from Elementor would be highly appreciated. This is critical.

**Comment by vapvarun** [comment]
We also faced the same issue using PHP 8.0.18, for the quick resolution I deleted the attachment id from the post meta value for a specific post.

**Comment by volneanschi** [comment]
Faced the same issue with Hello Elementor and PHP8.0+

**Comment by kelezzy** [comment]
Same issue here. 

Engine: Wordpress Multisite v6.0.2
Theme: Hello Elementor;
Plugin Version: error occurred in v3.7.2 (updating to v3.7.4, and downgrading to as low as v3.6 makes no difference);
server configuration 2x higher than recommended requirements;
PHP version: 8.x ; downgrade not an option for my Bitnami Multisite Instance on AWS Lightsail

Quick Workaround if you've saved problem Post/Page as a Template prior to the fatal error:
- Export the Template, Re-import and Publish as the same content type (i.e Post or Page or Landing Page, etc). 
- Then replace the problem post/page with the newly-created post.
- Remember to turn off all Elementor Experiments beforehand, purge all redundant post revisions from the DB, and to regenerate all Elementor Assets before fix, if you can. 
- Regenerate Elementor Assets, and turn stable experiments back on when you are done to improve performance.


If you have a lot of posts or pages with the same issue, a script that [does this](https://github.com/elementor/elementor/issues/19546#issuecomment-1230584371) might be a better fix. I haven't tested it though:
 
> We also faced the same issue using PHP 8.0.18, for the quick resolution I deleted the attachment id from the post meta value for a specific post.

**Comment by apmx** [comment]
I've downgraded to PHP 7.4 for now. This needs a fix ASAP as this is breaking a lot of sites right now.

**Comment by Tison** [comment]
I'm having this same issue myself.  I'm running php 8.0 I cannot downgrade to 7.4.

Question - It looks to be w/ one particular image that is sized to a particular width - Is there a way to edit this page code and remove this image?  Otherwise I'm completely stuck and have to rebuild the entire page..

**Comment by kegeg** [comment]
I'm having the same issue (PHP 8.0 can't downgrade to 7.4). 

The page was still loading up to a specific image, so I went on the page revision and isolated the image that wasn't loading, then deleted it from WordPress, and it fixed it temporarily for me.

**Comment by amichaidani** [comment]
Use this as a temporary solution.

`add_filter( 'wp_calculate_image_srcset_meta', function ( $image_meta ) {
	if ( ! empty( $image_meta['sizes'] ) ) {
		foreach ( $image_meta['sizes'] as $size_key => $size ) {
			if ( ! is_array( $size ) ) {
				continue;
			}

			if ( absint( $size['width'] ) !== $size['width'] ) {
				$image_meta['sizes'][ $size_key ]['width'] = (int) $size['width'];
			}

			if ( absint( $size['height'] ) !== $size['height'] ) {
				$image_meta['sizes'][ $size_key ]['height'] = (int) $size['height'];
			}
		}
	}

	return $image_meta;
} );
`

**Comment by Tison** [comment]
All,
First - @amichaidani thank you for that code snippet.

Next - I did get a response from Elementor support as well, they said:


Thank you for contacting Elementor! I’m __________ from Tier 2 Customer Experience, and I will assist you today.

I'm sorry to hear that; I understand how you feel, and I apologize for the inconvenience caused!

I want to let you know that this bug is already reported to our development team, and it is in the development stage right now, which means that the fix will be released soon in some of the upcoming updates.

As for fixing this issue, as you said that you already know which images in causing the issue and since I do not have login details to your site, I would advise you to install the [Enable Media Replace](https://wordpress.org/plugins/enable-media-replace/)​ plugin and replace the affected image.

Kindly watch the screencast I created for one of the customers. You can follow the same steps I mentioned in the video to fix the issue.
https://www.loom.com/share/3f7f388015934a00b155c5f5bcf7504f

Let me know if it helps!

I'm sorry for the inconvenience this has caused, and we highly appreciate your patience and support during this time while our team works on resolving this issue.

If you come across any other inquiry/issue using Elementor, please don't hesitate to open a new ticket; we'd be happy to help.

I wish you all the best, and have a wonderful day!
​

**Comment by zohaibtahir** [comment]
If the image is on the dynamic post then upload the new image with a different file name then not edit the size of image with elementor. Use custom CSS to change the image size. 

Hope it will help you because I solve my issue by doing this method on a dynamic post single page.

**Comment by amichaidani** [comment]
> All, First - @amichaidani thank you for that code snippet.
> 
> Next - I did get a response from Elementor support as well, they said:
> 
> Thank you for contacting Elementor! I’m __________ from Tier 2 Customer Experience, and I will assist you today.
> 
> I'm sorry to hear that; I understand how you feel, and I apologize for the inconvenience caused!
> 
> I want to let you know that this bug is already reported to our development team, and it is in the development stage right now, which means that the fix will be released soon in some of the upcoming updates.
> 
> As for fixing this issue, as you said that you already know which images in causing the issue and since I do not have login details to your site, I would advise you to install the [Enable Media Replace](https://wordpress.org/plugins/enable-media-replace/)​ plugin and replace the affected image.
> 
> Kindly watch the screencast I created for one of the customers. You can follow the same steps I mentioned in the video to fix the issue. https://www.loom.com/share/3f7f388015934a00b155c5f5bcf7504f
> 
> Let me know if it helps!
> 
> I'm sorry for the inconvenience this has caused, and we highly appreciate your patience and support during this time while our team works on resolving this issue.
> 
> If you come across any other inquiry/issue using Elementor, please don't hesitate to open a new ticket; we'd be happy to help.
> 
> I wish you all the best, and have a wonderful day!​

Thank the guys at Elementor - they supplied this snippet.
They have alreadymade the bug fix and a migration fix for the corrupted data, Let's wait for the update :)

**Comment by amichaidani** [comment]
Elementor, I've updated the plugin but no migration script was running or whatsoever. My site is still broken without the temporary snippet above.

**Comment by matipojo** [comment]
> Elementor, I've updated the plugin but no migration script was running or whatsoever. My site is still broken without the temporary snippet above.

Hi, @amichaidani, the upgrade script will be delivered soon, in the next release 3.8.0
https://github.com/elementor/elementor/pull/19725

**Comment by sandysaille** [comment]
@matipojo Hi, I'm still found this issue on the latest version which is 3.8.1 after I've updated my site to PHP 8. It shows critical error on my site.
Here's the error log I've got from my site, please see the screenshot below.

![Screen Shot 2565-11-16 at 17 18 28](https://user-images.githubusercontent.com/3271452/202399693-c6744e66-2ac0-47a9-8a8f-428eafffab14.png)


I'm not sure is this issue I found relates with [this fix](https://github.com/elementor/elementor/pull/19725) or not, but it would be great if you can help or any suggestions.

**Comment by JamboMedia** [comment]
Any update on this? It is breaking our website when switching to PHP 8
