### ISSUE TITLE
🐞 Bug report: [v3.8-Beta] Container issues after update...

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#19540]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

https://user-images.githubusercontent.com/60075863/185725817-73024555-44dc-4148-8db6-1c6a503845cb.mov

This happens after the recent updates. When will you stop breaking stuff that works just fine? This is the forever question. Is the testing team on vacation again? This is absurd. Elementor is the opposite of backward compatibility. The code and the decisions taken there are from another world. I understand that the containers are still in alpha, but some of us made them work by adding the CSS you didn't, with !important, yes, so you don't break it, and yet you still managed to.

I've never seen a product with so many bugs constantly, and no, the thing with lots of WP plugins and compatibility issues between them and Elementor is not the case here. All the issues I ever encounter are with only the Hello theme and both Elementor versions installed, so it's not about conflicts, it's Elementor only. Is there anyone caring about this product anymore? There are so many bugs, UX issues, and other things that have been here for years, and no one bothered to fix any of them. It's like the people at Elementor don't even use Elementor on a daily basis, or at least use it, to see this stuff.

### Steps to reproduce

[elementor-4683-2022-08-20.txt](https://github.com/elementor/elementor/files/9386103/elementor-4683-2022-08-20.txt)

How do I even explain what's going on there? I have basic stuff... Change the .txt to .json. It's a template with a few lines of custom CSS that don't influence this behavior. With, or without them, it's just the same.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

No need.

**Comment by azkalex** [comment]
On Version 3.8.0-dev4 it seems to be fixed, hopefully, you'll merge it soon to the core one.

**Comment by azkalex** [comment]
For some reason, there are no issues when the WP bar is showing.

![image](https://user-images.githubusercontent.com/60075863/185824956-a0632126-8625-434c-a4ab-eb91cb22ce9b.png)

But when viewed without it (incognito for example) it behaves weirdly again, the width just doesn't stay 100%.

![image](https://user-images.githubusercontent.com/60075863/185825054-c5bfa4d8-fe1e-42de-b011-b9e8559e221d.png)

**Comment by azkalex** [comment]
I think there is a script causing these issues because it only happens on window resize.
It also only happens on the first nav in the tree (I don't know why the nav gets cloned when the sticky option is on, because it's been like this forever, and using IDs in the elements inside it would cause issues since they are supposed to be unique. Maybe a dev could clarify this), the second nav is alright.

https://user-images.githubusercontent.com/60075863/186030322-387c9feb-d41e-49b9-9cbc-7cbcf17b8cec.mov

Also, why I'm saying it's a script: Even if I try to hardcode the CSS values (for example, width: 100%, it still gets overridden by another width set in px by that script), they still get overridden in the inline CSS, and that inline CSS is managed by that script probably.

![image](https://user-images.githubusercontent.com/60075863/186031132-d7b93bc6-1aa9-4c60-8c6f-c4bbec150fc5.png)

There's also a "right" value popping up for the position of the element, but it doesn't show up anywhere, I'm talking about the 135px value in the image above. And also the paddings got messed up. The top and bottom of 20px are set by me, and so are supposed to be the left and right too, but Elementor decides that they should be 67.5px. Not quite nearing a stable status in my opinion if you keep going on like this.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-6

Feel free to update

Thanks!
