### ISSUE TITLE
🐞 Bug report: "Warning: Attempt to read property "ID" on null" with WooCommerce after update to Elementor Core 3.7.2

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#19553]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

 "Warning: Attempt to read property "ID" on null" after update to Elementor Core 3.7.2

### Steps to reproduce

Create Blank WordPress 6.0.1
- Add Elementor 3.7.2 Plugin
- Add Elementor Pro 3.7.3 Plugin
- Create a Page => Edit with Elementor
- View Page

=> Got Warning:

`Warning: Attempt to read property "ID" on null in ..public_html/wp-content/plugins/elementor/core/base/document.php on line 250`

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

PHP 8.0.x
WordPress 6.0.1
Elementor 3.7.2
Elementor Pro 3.7.3
**WooCommerce 6.8.1**

**Comment by datverse** [comment]
Noted: This issue will got with WooCommerce 6.8.1

**Comment by datverse** [comment]
Noted: This issue will got with WooCommerce 6.8.1

**Comment by peterMadziyire** [comment]
How do you fix

**Comment by MorganIndustrialTech** [comment]
Having the same issue here. Ran through all my code and can't seem to find a fix. Is this a compatability issue with WP and Elementor?

![Screenshot 2022-08-22 131819](https://user-images.githubusercontent.com/111789443/185991067-9c1b7557-13ad-46c4-9375-c4baf9c9e25f.png)

**Comment by datverse** [comment]
By this is php warning. I disable wp_debug and Off show arlert in wp-config.

**Comment by peterMadziyire** [comment]
What if you uninstall woocomerce

**Comment by datverse** [comment]
> What if you uninstall woocomerce

This issue come with WooCommer and Elementor Pro 3.7.3 If I unisstall one of them the issue gone.

**Comment by Treinplezier** [comment]
i have the same problem and then with elementor pro 3.7.2.

**Comment by banyancreative** [comment]
Same issue for me! Any ideas for how to resolve this?

**Comment by WVelunza** [comment]
Hey everyone, I was having the same problem. My solution was to remove the basic elementor plugin and reinstall an older version of it (3.7.0) and it resolved the issue for me. This is a temporary solution.

**Comment by relima** [comment]
I am having the exact same issue on elementor pro 3.7.3

**Comment by Jojo852** [comment]
Temporary fix (as mentioned by [WVelunza](https://github.com/WVelunza) above)...

Roll back to Elementor 3.7.1 and in my case I also rolled back the PHP version from 8.0 to 7.4

The error message no longer appears and the site is behaving once again.

**Comment by HRoger** [comment]
me too

**Comment by jammerinbc** [comment]
I just had this Happen. It is definitely an Issue with Elementor 3.7.4. Rolling back to 3.7.1 fixes issues for now. Elementor you need to nail this down and fix in 3.7.5

**Comment by Jojo852** [comment]
I've got a ticket open with Elementor support and it's been escalated to tier 2.

**Comment by WolfIT-Solutions** [comment]
Same problem on some of my sites. Rollback of Elementor Free in the "Version Control" Tab to 3.7.1 worked for me, I hope they will fix it soon!

**Comment by datverse** [comment]
Hi @ramiy ,
Can you help us about this issue?
Thanks

**Comment by SneakyMouse1** [comment]
Same issue. But helps only rollback from PHP 8.0 to 7.4

**Comment by rami-elementor** [comment]
Hi everyone,

We are aware of this issue and we are already working on a solution.

@datverse, thank you for the bug report. And all the other commenters, it helps us prioritize the bugs and assign developers to this task.

**Comment by datverse** [comment]
> Hi everyone,
> 
> 
> 
> We are aware of this issue and we are already working on a solution.
> 
> 
> 
> @datverse, thank you for the bug report. And all the other commenters, your feedback helps us prioritize the bugs and assign developers to this task.

Thank you ❤️

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.7.4

Feel free to update

Thanks!

**Comment by Nasir369** [comment]
wp version 6.0.2
help  please.?

https://prnt.sc/gXc6kDEN9IkH
