### ISSUE TITLE
🚀 Feature Request: Enlarge boxes in REPLACE URL tool

### ISSUE THREAD

**Issue by arcaswebdesign** [elementor/elementor#19559]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The OLD and NEW URL boxes in the "Replace URL" tool are relatively small which means that we often can't see the full URL we are replacing - given the nature of the action this tool takes it's pretty important that we can clearly check that we have entered the correct URLs but at present we oten can't.

### Describe the solution you'd like

Increase the size of both boxes (perhaps stack them rather than side by side) so that we are more likely to be able to see the entire URL entered.

**Comment by perks98** [comment]
+1 would make sense

**Comment by nicholaszein** [comment]
Hello there!

This feature was released with Elementor **v3.8**! 🥳 

Cheers 🥂
