### ISSUE TITLE
🐞 Bug report: Needs handling for the soft deprecations since v3.7.0

### ISSUE THREAD

**Issue by xlplugins** [elementor/elementor#19562]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

So In the v3.7.0 some soft action hooks are deprecated,  one of the key deprecation is ''elementor/widgets/widgets_registered'' action is now 'elementor/widgets/register' , however many plugins are still using the old action. Which adds elementorDevToolsConfig.deprecation.soft_notices
 to populate but in the recent live versions. when elementor PRO is activated it shows up this error in browsers console on editor. 
 
 dev-tools.js?ver=3.8.0-dev4:508 Uncaught TypeError: Cannot read properties of undefined (reading 'deprecated')
    at dev-tools.js?ver=3.8.0-dev4:508:49
    at Array.forEach (<anonymous>)
    at Module.notifyBackendDeprecations (dev-tools.js?ver=3.8.0-dev4:501:31)
    at new Module (dev-tools.js?ver=3.8.0-dev4:491:10)
    at dev-tools.js?ver=3.8.0-dev4:534:30
    at dev-tools.js?ver=3.8.0-dev4:537:3
    at dev-tools.js?ver=3.8.0-dev4:539:12
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:508
notifyBackendDeprecations @ dev-tools.js?ver=3.8.0-dev4:501
Module @ dev-tools.js?ver=3.8.0-dev4:491
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:534
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:537
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:539
editor-document.js?ver=3.8.0-dev4:1877 Uncaught ReferenceError: elementorDevTools is not defined
    at get CommandHistory [as CommandHistory] (editor-document.js?ver=3.8.0-dev4:1877:5)
    at ../modules/global-widget/assets/js/editor/commands/link.js (editor.js?ver=3.8.0-dev36:3622:23)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at ../modules/global-widget/assets/js/editor/commands/index.js (editor.js?ver=3.8.0-dev36:3493:13)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at ../modules/global-widget/assets/js/editor/component.js (editor.js?ver=3.8.0-dev36:3843:40)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at ../modules/global-widget/assets/js/editor/module.js (editor.js?ver=3.8.0-dev36:4912:41)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at editor.js?ver=3.8.0-dev36:19727:39
    
Since this error triggers prior to loading elementordevtools, making it undefined. 
This error also cause elementorDevTools to not load properly and hence shows up further errors if anywhere elementorDevTools is utilized. 

    
    

### Steps to reproduce

To reproduce, user elementor 3.7.0 or greater and elementor pro 3.7.3 use any plugin that could trigger the soft deprecation. of 'elementor/widgets/widgets_registered' and you could see the issue in editor. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: (Ubuntu) v8.0.30
	PHP Version: 7.3.27-9+ubuntu20.04.1+deb.sury.org+1
	PHP Memory Limit: 128M
	PHP Max Input Vars: 6000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://aero.bwfdemo.in
	Home URL: https://aero.bwfdemo.in
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: harish@wisetr.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Autonami Marketing Automations For WordPress
		Version: 2.1.4.beta.fix-1753
		Author: BuildWooFunnels

	Autonami Marketing Automations Pro
		Version: 2.1.3
		Author: WooFunnels

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	WooCommerce
		Version: 6.8.0
		Author: Automattic

	WooFunnels Funnel Builder
		Version: 2.3.0
		Author: BuildWooFunnels

	WooFunnels Funnel Builder Pro
		Version: 2.3.4
		Author: BuildWooFunnels

	WP File Manager
		Version: 7.1.6
		Author: mndpsingh287

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

== Elements Usage ==
	
	page : 32
		button : 5
		divider : 4
		heading : 59
		icon-list : 1
		image : 13
		shortcode : 1
		text-editor : 4
		video : 1
	wp-post : 1
		accordion : 3
		button : 74
		divider : 90
		heading : 1492
		icon : 86
		icon-box : 66
		icon-list : 196
		image : 511
		image-box : 6
		image-carousel : 4
		image-gallery : 3
		menu-anchor : 3
		progress : 2
		shortcode : 1
		spacer : 76
		star-rating : 62
		testimonial : 12
		text-editor : 228
		toggle : 2
		video : 50
		wfocu-accept-offer-button : 35
		wfocu-offer-price : 8
		wfocu-offer-product-title : 7
		wfocu-offer-reject-button : 1
		wfocu-offer-reject-link : 31
		wfocu-product-images : 7
		wfocu-qty-selector : 5
		wfocu-short-description : 1
		wfocu-variation-selector : 10
		wfty-customer-detail : 1
		wfty-order-detail : 1
	wp-page : 21
		heading : 2
		image : 2
		text-editor : 2

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 2 of 2JS: 2022-05-11 11:37:13 [error X 3][https://aero.bwfdemo.in/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.6.5:2:30599] Cannot read properties of undefined (reading \'model\') 
JS: 2022-08-17 14:01:13 [error X 20][https://aero.bwfdemo.in/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.7.1:2:25976] elementorDevTools is not defined 

Log: showing 20 of 302022-07-28 11:12:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-28 11:12:31 [info] elementor::elementor_updater Started 
2022-07-28 11:12:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-28 11:12:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-28 11:12:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-09 16:03:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-09 16:03:44 [info] elementor::elementor_updater Started 
2022-08-09 16:03:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 16:03:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 16:03:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-14 21:35:20 [info] elementor::elementor_updater Started 
2022-08-14 21:35:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-14 21:35:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-14 21:35:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-14 21:35:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-14 21:35:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-22 12:35:31 [info] elementor-pro::elementor_pro_updater Started 
2022-08-22 12:35:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-22 12:35:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-22 12:35:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.7.3',
)]

PHP: showing 10 of 10PHP: 2022-06-21 12:42:04 [notice X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-21 14:51:12 [notice X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/modules/landing-pages/module.php::127] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 16:30:02 [notice X 2][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/managers/image.php::34] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-03 09:47:51 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/core/files/css/base.php::896] Allowed memory size of 134217728 bytes exhausted (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-04 19:32:19 [error X 3][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/base/controls-stack.php::2127] Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-21 14:01:55 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/base/element-base.php::450] Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-25 03:13:27 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/purchase-summary.php::970] Allowed memory size of 134217728 bytes exhausted (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-26 17:02:53 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 9721144 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-30 15:39:35 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/base/element-base.php::450] Allowed memory size of 134217728 bytes exhausted (tried to allocate 81920 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-22 12:34:47 [notice X 7][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/core/base/document.php::250] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	WooFunnels Funnel Builder: Incompatible
	WooFunnels Funnel Builder Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by jannnfe** [comment]
We need a quick workaround because a lot of plugins don't work anymore since 3.7.0. Elementor 3.7.0+ is not usable at this state.
