### ISSUE TITLE
🐞 Bug report: Call To Action - Human readable date - incorrect translate

### ISSUE THREAD

**Issue by glorpyz** [elementor/elementor#19564]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I, tested the new setting to have two languages [English & Swedish] on the blog I noticed that my Call to action ribbon, with human readable date, shows partly translated text.

Original:  "1 day ago" or   "2 days ago".
Multi language:  "1 dag **ago**" or "2 dagar **ago**" 

It doesn't translate "**ago**" to "**sedan**".

I would prefer if you could do custom settings and be able to skip the word entirely to save space.
My quick fix was to go custom "l, j/n" instead but readable would be better.

### Steps to reproduce

Insert Call to Action, choose ribbon and date/human readable.
Swedish wordpress, English elementor.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Details</summary>

== Server Environment ==
Operating System: Linux
Software: LiteSpeed
MySQL version: MariaDB Server v10.4.25
PHP Version: 8.0.21
PHP Memory Limit: 128M
PHP Max Input Vars: 1000
PHP Max Post Size: 8M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.0.1

== Theme ==
Name: Hello Elementor
Version: 2.6.1
Author: Elementor Team
Child Theme: No

== User ==
Role: administrator
WP Profile lang: sv_SE
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
Classic Editor
Version: 1.6.2
Author: WordPress Contributors

Code Snippets
Version: 3.2.0
Author: Code Snippets Pro

Crocoblock Wizard
Version: 1.2.4
Author: Crocoblock

Duplicate Page
Version: 4.4.9
Author: mndpsingh287

Elementor
Version: 3.7.2
Author: Elementor.com

Elementor Pro
Version: 3.7.3
Author: Elementor.com

EWWW Image Optimizer
Version: 6.7.0
Author: Exactly WWW

Freesoul Deactivate Plugins
Version: 1.9.2.2
Author: Jose Mortellaro

Insert PHP Code Snippet
Version: 1.3.3
Author: xyzscripts.com

JetEngine
Version: 3.0.3.1
Author: Crocoblock

JetEngine - dynamic charts builder
Version: 1.0.0
Author: Crocoblock

JetEngine - dynamic tables builder
Version: 1.0.4
Author: Crocoblock

JetMenu
Version: 2.2.3
Author: Crocoblock

JetSmartFilters
Version: 2.3.13
Author: Crocoblock

LiteSpeed Cache
Version: 5.2
Author: LiteSpeed Technologies

Meow Gallery (Pro)
Version: 4.2.6
Author: Jordy Meow, Thomas Kim

Meow Lightbox
Version: 3.2.1
Author: Jordy Meow, Thomas KIM

Really Simple SSL
Version: 5.3.3
Author: Really Simple Plugins

Regenerate Thumbnails
Version: 3.1.5
Author: Alex Mills (Viper007Bond)

== Must-Use Plugins ==
freesoul deactivate plugins [fdp]
Version: 1.9.2.2
Author: Jose Mortellaro

WordPress automation by Installatron
Version: 
Author: 

== Elementor Experiments ==
Optimized DOM Output: Active by default
Improved Asset Loading: Active by default
Improved CSS Loading: Active by default
Inline Font Icons: Inactive by default
Accessibility Improvements: Active by default
Additional Custom Breakpoints: Inactive
Import Export Template Kit: Active by default
Hide native WordPress widgets from search results: Active by default
admin_menu_rearrangement: Inactive by default
Flexbox Container: Inactive by default
Default to New Theme Builder: Active by default
Hello Theme Header & Footer: Active by default
Landing Pages: Active by default
Color Sampler: Active by default
Favorite Widgets: Active by default
Admin Top Bar: Active by default
Page Transitions: Active by default
Notes: Active by default
Form Submissions: Active by default
Scroll Snap: Active by default

== Log ==

Log: showing 20 of 312022-07-28 06:54:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-01 05:34:25 [info] elementor-pro::elementor_pro_updater Started 
2022-08-01 05:34:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-01 05:34:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-01 05:34:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-01 05:34:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 18:48:35 [info] elementor::elementor_updater Started 
2022-08-08 18:48:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 18:48:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 18:48:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-15 15:28:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-15 15:28:42 [info] elementor::elementor_updater Started 
2022-08-15 15:28:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-15 15:28:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-15 15:28:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-22 14:36:33 [info] elementor::elementor_updater Started 
2022-08-22 14:36:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-22 14:36:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-22 14:36:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-22 14:36:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

JS: showing 8 of 8JS: 2022-06-18 20:30:12 [error X 3][https://www.xxx.xx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:605818] elementorFrontend is not defined 
JS: 2022-06-26 20:24:56 [error X 1][https://www.xxx.xx/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:13639] Syntax error, unrecognized expression: . 
JS: 2022-08-17 20:06:48 [error X 2240][https://www.xxx.xx/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16778] this._lastColor is null 
JS: 2022-08-17 20:07:00 [error X 81][https://www.xxx.xx/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:20993] this._eventListener is null 
JS: 2022-08-18 20:11:59 [error X 1][https://www.xxx.xx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:905570] T is undefined 
JS: 2022-08-20 08:24:23 [error X 9][https://www.xxx.xx/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2022-08-20 08:45:36 [error X 2][https://www.xxx.xx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:1060432] $ is null 
JS: 2022-08-20 21:15:59 [error X 5][https://www.xxx.xx/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.1:2:30915] elementor.settings.page is undefined 

PHP: showing 3 of 3PHP: 2022-08-17 20:07:05 [warning X 6][/home/s47728/domains/xxx.xx/public_html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 18:26:34 [warning X 4][/home/s47728/domains/xxx.xx/public_html/wp-content/plugins/elementor/includes/managers/image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-20 20:14:04 [warning X 1][/home/s47728/domains/xxx.xx/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

</details>

**Comment by rami-elementor** [comment]
Hi @glorpyz 

Thank you for reporting. Translations are added by Elementor community members and ordinary users like yourself. You can help improve the Swedish translation in the following links:

Translating Elementor:
https://translate.wordpress.org/projects/wp-plugins/elementor/stable/sv/default/

Translating Elementor Pro:
https://translate.elementor.com/projects/elementor-pro/sv/default/
