### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by catchlightWeb** [elementor/elementor#19579]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use the Spacing sliders on the Team Members widget, in particular the "Name Bottom Spacing" slider. Nothing happens, in other words the slider doesn't work to change the spacing. Here is a video clip - https://youtu.be/C3890MEkRkw

### Steps to reproduce

Verify that you have the Team Member widget on the page. Add an image, a heading and a description and try to change the spacing using the sliders. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://wordpress-567743-2576835.cloudwaysapps.com
	Home URL: https://wordpress-567743-2576835.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 13
	Admin Email: brock@catchlight.co.nz
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Catchlight Design
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Page Spider
		Version: 3.19
		Author: J7Digital

	Broken Link Checker
		Version: 1.11.18
		Author: WPMU DEV

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.6
		Author: Gravity Forms

	iThemes Security
		Version: 8.1.2
		Author: iThemes

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 4.78
		Author: MalCare Security

	Performance Lab
		Version: 1.4.0
		Author: WordPress Performance Group

	Post Types Order
		Version: 1.9.9.1
		Author: Nsp Code

	ShortPixel Image Optimizer
		Version: 5.0.8
		Author: ShortPixel

	Ultimate Addons for Elementor
		Version: 1.36.9
		Author: Brainstorm Force

	User Role Editor
		Version: 4.63
		Author: Vladimir Garagulya

	White Label CMS
		Version: 2.3
		Author: www.videousermanuals.com

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.14.5
		Author: Rhubarb Group

== Elements Usage ==
	
	footer : 1
		heading : 3
		icon-list : 4
		text-editor : 1
		uael-infobox : 1
	header : 1
		icon : 1
		icon-box : 3
		nav-menu : 1
		theme-site-logo : 1
	page : 7
		button : 1
		call-to-action : 3
		heading : 2
		template : 3
		text-editor : 5
		uael-infobox : 3
		video : 3
	popup : 1
		icon-list : 1
		nav-menu : 1
	section : 11
		button : 2
		google_maps : 1
		heading : 5
		image : 1
		template : 3
		text-editor : 2
		uael-infobox : 7
	wp-page : 14
		button : 3
		call-to-action : 1
		gallery : 1
		heading : 51
		image : 13
		shortcode : 17
		template : 31
		text-editor : 21
		uael-image-gallery : 1
		uael-team-member : 13

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active by default
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active
	Admin Top Bar: Active by default
	Page Transitions: Active
	Notes: Active by default
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 422022-08-04 12:56:07 [info] elementor-pro::elementor_pro_updater Started 
2022-08-04 12:56:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-04 12:56:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-04 12:56:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-04 12:56:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-11 14:13:45 [info] elementor::elementor_updater Started 
2022-08-11 14:13:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-11 14:13:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-11 14:13:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-11 14:13:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-18 11:57:00 [info] elementor::elementor_updater Started 
2022-08-18 11:57:00 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-18 11:57:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-18 11:57:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-18 11:57:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-22 12:45:40 [info] elementor::elementor_updater Started 
2022-08-22 12:45:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-22 12:45:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-22 12:45:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-22 12:45:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

PHP: showing 1 of 1PHP: 2022-06-30 22:02:50 [notice X 1][/home/567743.cloudwaysapps.com/cuajxfvrcd/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ultimate Addons for Elementor: Compatible

**Comment by rami-elementor** [comment]
Hi @catchlightWeb 

The **Team Member** widget is not an Elementor or Elementor Pro widget. I think you are using an external Elementor Addon. Please contact the addon developer.
