### ISSUE TITLE
🐞 Bug report: If the button background color is a gradient, the hover background color will not work.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19574]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As it is clear from the title, if the background of the button is a gradient in normal mode and then we want to consider a simple color for its hover mode, that color will not be applied, unless we also use the gradient color in the hover mode. . 

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/186161529-1c4b0ffe-2860-45d5-87a1-7709c1f4eb8e.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
@79ho3ein there are workarounds for this. Use gradients in both states.

We are not going to change this behavior.
