### ISSUE TITLE
PHP Fatal error - line 294 - elementor-pro/modules/theme-builder/classes/conditions-manager.php

### ISSUE THREAD

**Issue by karinwerner** [elementor/elementor#19578]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Line 294 of elementor-pro/modules/theme-builder/classes/conditions-manager.php
Causes a Fatal Error if the variable is null.

### Steps to reproduce

Unsure. Would have to find out why the variable was null.
Though I have seen the error pop up every once in awhile. So today I checked the issue.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: WEB-SERVER
	MySQL version: Source distribution v8.0.30
	PHP Version: 8.1.9
	PHP Memory Limit: 8192M
	PHP Max Input Vars: 30000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: (hidden)
	Home URL: (hidden)
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 1024M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: (hidden)
	Debug Mode: Inactive

== Theme ==
	Name: Child Theme
	Version: 2.6.1.1660691366
	Author: Hello Elementor
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active by default
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by arielk** [comment]
In order for us to look into this matter, please contact our tech support through your account, with complete login information to access your website and our support team will try to assist.
