### ISSUE TITLE
🐞 Bug report: 2 new bug in section

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19575]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

1- In the inner section widget, the inner section does not have a handle and has been removed : https://prnt.sc/LWP-w1dCw9tZ

2- If you add the inner section widget, the extra space is created at the top : https://prnt.sc/Db6T3fhN6L-m

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
The extra space is not displayed in the frontend.

We are not going change this. Closing the ticket is wontfix.
