### ISSUE TITLE
🐞 Bug report: Style paste not working and not saving the updates on that page (from 3.7.0 version)

### ISSUE THREAD

**Issue by rudlinkon** [elementor/elementor#19586]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I added any repeater field in the advanced tab using the hook named `elementor/element/section/section_advanced/after_section_end` then that section copy/paste style is not working and throwing a console error.

![image](https://user-images.githubusercontent.com/9977447/186364396-aa8d1aa0-dfbe-4320-9015-d90901f64065.png)

And then when I tried to update that page it also not working and throwing another console error. `eael_parallax_layer_image` is the key to my repeater controller.

![image](https://user-images.githubusercontent.com/9977447/186364951-6665a8ba-cb55-4746-988c-d0a451e8b45e.png)

### Step 1: 
add repeater controller in section advanced tab. 

**code example:**
```
add_action( 'elementor/element/common/_section_style/after_section_end', 'register_controls_callback' );

function register_controls_callback( $element ) {
	$element->start_controls_section(
		'extra_section',
		[
			'label' => __( 'Extra Section', 'text-domain' ),
			'tab'   => Controls_Manager::TAB_ADVANCED
		]
	);

	$repeater = new Repeater();

	$repeater->add_control(
		'repeater_title',
		[
			'name'  => 'repeater_title',
			'label' => esc_html__( 'Tab Title', 'text-domain' ),
			'type'  => Controls_Manager::TEXT,
		]
	);

	$element->add_control(
		'main_repeater',
		[
			'label'       => __( 'Tabs', 'text-domain' ),
			'type'        => Controls_Manager::REPEATER,
			'fields'      => $repeater->get_controls(),
			'title_field' => '{{repeater_title}}',
		]
	);

	$element->end_controls_section();
}
```

### Step 2:
Open elementor editor and go to any section panel and add some repeater field then copy that section from the elementor context menu.

### Step 3:
Try to paste style over any other section from the elementor context menu and then you will find the console error then try to update that page and you will get again another console error.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

any system environment.

**Comment by 79ho3ein** [comment]
Hi @rudlinkon 
This is a bug from third party plugins. If you have a plugin that offers the display condition feature, disable it and wait for that plugin to be updated.

**Comment by rudlinkon** [comment]
hello @79ho3ein 
I think you missed my point. I did not mention any 3rd party plugins but I mentioned the causes of the issue. You may reproduce the issue by doing the following step. Of course, when plugins use a repeater controller in the settings panel those plugins also create the same error but it works well in 3.6.9. So the issue appeared in the 3.7.0 version.

**Comment by rudlinkon** [comment]
Hello there,
I found the issue. If we use `'style_transfer' => false` in the repeater controller then the issue is resolved. Thank you, everyone.

code example:
```
$element->add_control(
	'main_repeater',
	[
		'label'          => __( 'Tabs', 'text-domain' ),
		'type'           => Controls_Manager::REPEATER,
		'fields'         => $repeater->get_controls(),
		'style_transfer' => false,
		'title_field'    => '{{repeater_title}}',
	]
);
```
