### ISSUE TITLE
🚀 Feature Request: Allow Custom Buttons in Text Editor Widgets TinyMCE Editor

### ISSUE THREAD

**Issue by SEwebm** [elementor/elementor#19605]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi there, I wanted to extend the Elementor Text Editor Widget, to be more specific the WYSIWYG control which uses the TinyMCE Editor, to which I wanted to add a custom button.

Sadly I had to discover that this is hardly possible.
To extend the TinyMCE is fairly easy using the 'mce_buttons' hook, but in the get_wp_editor_config() method in 'core/editor/editor.php' all actions using this hook are removed. Using Elementor Hooks such as 'elementor/editor/init' to register the actions after the elementor.php init() method executed does not seem to have any effect.

Maybe I am missing something, I read somewhere that custom plugins extending the TinyMCE are disabled due to compatibility reasons. Still I would like to achieve this as it is the most elegant solution to the problem I am trying to solve.
(Adding Tooltips to selected text parts).

### Describe the solution you'd like

Some kind of possibility to achieve this goal would be appreciated a lot, I think using an elementor hook to customize TinyMCE after the config is initialized would be the best solution.

### Describe alternatives you've considered

Adding some kind of context menu to the editor panel, but there currently is no elegant solution to that as well. Adding a context menu to the widget itself, and selecting text in the preview part of the editor page probably would be possible but no good user experience.

### Additional context

I'd be grateful if you find the time to share some insight into why the situation currently is as it is.

**Comment by arielk** [comment]
Hi @SEwebm,

Over time, we had a lot of incompatibilities with the TinyMCE widget and other plugins that extend it in the hack ways, so we did changes to block some hooks. To achieve your specific needs, I would recommend that you create your own widget to achieve the level of customization you are looking for.

Anyway, which functionality do you want to add?

**Comment by SEwebm** [comment]
I'd like the user to be able to select text parts to wrap selected part into a html wrapper (similar to how links are added), thus creating a tooltip. (Imagine the wikipedia explanations when hovering over a link) Of course this would be achievable by simply wrapping the text into html tags in the "text" tab of the Text editor but it is not a good user experience.

That is why I wanted to add a custom button. The content of the tooltip is then added via a repeater control. For every instance of said tooltip in a text the user would have to create such a connection by selecting text and applying the tooltip.

Creating an own widget has come to my mind as well but I think it is not very effective creating a Text Editor Widget with rudimentary controls just for one feature that the standard solution does not cover.

Thanks for your time

**Comment by arielk** [comment]
Thanks for your input!

So I'm closing this issue at this point. If we add the options in the future I will try to update here.

**Comment by SEwebm** [comment]
For anyone coming across this thread, it is indeed possible to do so, you will just have to do it with javascript.

I extended the Elementor Text Widget for a number of additional controls, so I have my own widget where I can enqueue scripts, though you could also place the script in your theme's function.php. Then you have to make sure everything is loaded (elementor and tinymce objects).

You can use the hook:

`elementor.hooks.addAction( 'panel/open_editor/widget/{WIDGET_NAME}', function( panel, model, view ) {}`

to trigger registering the button there like this:

`// get active instances of the editor
    let editor = tinymce.activeEditor;

    // add a button to the editor buttons
    editor.addButton('tooltip', {
      text: 'tooltip',
      icon: false,
      onclick: (editor) => {
        tooltipCallback(editor);
      }
    });

    // the button now becomes
    let button=editor.buttons['tooltip'];

    // find the buttongroup in the toolbar found in the panel of the theme
    let bg=editor.theme.panel.find('toolbar buttongroup')[0];

    // without this, the buttons look weird after that
    bg._lastRepaintRect=bg._layoutRect;

    // append the button to the group
    bg.append(button);`

I am unsure if this has to be done every time the editor panel is opened. Too lazy to test for that :P

**Comment by DevWael** [comment]
@SEwebm Thanks for the tip, did you able to achieve it? I can't find the editor object inside any of this action parameters

`elementor.hooks.addAction( 'panel/open_editor/widget/text-editor', function( panel, model, view ) {}`

**Comment by SEwebm** [comment]
Yeah I achieved it like that

you have to go through the window Object, because the elementor editor view consists of multiple iframes which are accessible by references found in the global window object.

Just dig your way through the object in the console I am sure you will find it!

**Comment by scarydakis** [comment]
> @SEwebm Thanks for the tip, did you able to achieve it? I can't find the editor object inside any of this action parameters
> 
> `elementor.hooks.addAction( 'panel/open_editor/widget/text-editor', function( panel, model, view ) {}`

@DevWael try top.window.tinymce.activeEditor

**Comment by dalbard** [comment]
@hirschferkel Do you still have the answer for this? I'm currently building a custom Elementor widget that uses a WYSIWYG controls, and I want to limit the block formats to only have paragraph and not headings. Basically I want the ability to write pargraphs and lists freely. I managed to do it globally, but not for a specific widget.

Any help is greatly appreciated!
