### ISSUE TITLE
🐞 Bug report: Can't see a Foogallery in editing mode with Elementor

### ISSUE THREAD

**Issue by Edge60** [elementor/elementor#19621]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I add a FooGallery in a Elementor page, i can't see it in the editing mode, just the code.
![Elementor-Foogallery-bug]
(https://user-images.githubusercontent.com/112192548/186948703-61f947ce-1b46-44a4-8938-986b5f69c970.jpg)

### Steps to reproduce

Install the plugin Foogallery
Create a Foogallery
Add the Foogallery in an Elementor page

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.38
	PHP Version: 8.0.22
	PHP Memory Limit: -1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	WP Multisite: No
	Max Upload Size: 64 Mo
	Memory limit: 40M
	Max Memory limit: -1
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: CSE Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.6.2
		Author: Takayuki Miyoshi

	Download Manager
		Version: 3.2.54
		Author: W3 Eden, Inc.

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	EmbedPress
		Version: 3.5.0
		Author: WPDeveloper

	Essential Addons for Elementor
		Version: 5.2.3
		Author: WPDeveloper

	FooBox Image Lightbox
		Version: 2.7.17
		Author: FooPlugins

	FooGallery
		Version: 2.2.16
		Author: FooPlugins

	NextGEN Gallery
		Version: 3.28
		Author: Imagely

	PDF viewer for Elementor
		Version: 2.9.3
		Author: RedLettuce Plugins

	Stratum - Elementor Widgets
		Version: 1.3.13
		Author: MotoPress

	UpdraftPlus - Backup/Restore
		Version: 1.22.18
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.6.0
		Author: Wordfence

	WPDM - Elementor
		Version: 1.1.3
		Author: WordPress Download Manager

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut

== Journal ==
	

Log: showing 19 of 192022-07-04 11:02:16 [info] elementor::elementor_updater Started 
2022-07-04 11:02:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-04 11:02:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-04 11:02:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-04 11:02:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-30 16:05:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-30 16:05:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-30 16:05:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-30 16:05:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-08 14:20:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 14:20:49 [info] elementor::elementor_updater Started 
2022-08-08 14:20:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 14:20:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 14:20:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 14:20:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-25 11:37:00 [info] elementor::elementor_updater Started 
2022-08-25 11:37:00 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-25 11:37:00 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-25 11:37:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.2',
)]

PHP: showing 3 of 3PHP: 2022-07-17 16:50:54 [warning X 1][/homepages/1/d914899980/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-17 16:57:59 [warning X 1][/homepages/1/d914899980/htdocs/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined array key "title" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-03 19:13:00 [notice X 496][/homepages/1/d914899980/htdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibilité non spécifiée
	PDF viewer for Elementor: Compatibilité non spécifiée
	Stratum - Elementor Widgets: Compatibilité non spécifiée
	WPDM - Elementor: Compatibilité non spécifiée

**Comment by m1ga** [comment]
@Edge60 try the shortcode widget https://elementor.com/help/shortcode-widget/

**Comment by Edge60** [comment]
Thanks, but I have the same problem using the shortcode widget.
![Elementor-Foogallery-bug-idem-shortcode](https://user-images.githubusercontent.com/112192548/187031832-790de52f-5196-438c-80b9-443b642b37cc.jpg)

**Comment by m1ga** [comment]
![Screenshot_20220827_153323](https://user-images.githubusercontent.com/4334997/187032552-d3567c38-fb1f-42e9-94ca-b9f3759ac106.png)
think that is more an issue that foogallery should fix. It shows the boxes but doesn't load the images, only in preview mode it works.

**Comment by Edge60** [comment]
I think so. Thanks for your answers !
