### ISSUE TITLE
✔️ 🐞 Bug report: WooCommerce Page component applies an ".elementor-hidden" class in some cases (ED-8377)

### ISSUE THREAD

**Issue by tolvajsanyi** [elementor/elementor#19627]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The content of my WP Woocommerce webshop My Account page has disappeared. In the attached screenshot, you can see that it's all nested in a div with an elementor-hidden class, and when I turn off display: none in inspector, it appears twice nested. 

I didn't hide it in elementor, and I didn't do anything to it to justify this. In fact, I haven't touched it in weeks, and it was working last week.

Elementor 3.7, Elementor Pro 3.7.3, latest Woocommerce.

The bug was fixed by putting back Elementor 3.6.8.

### Steps to reproduce

Use Woocommerce design template with Elementor editor
Open My account page

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

The bug was fixed by putting back Elementor 3.6.8.

**Comment by rami-elementor** [comment]
The attached screenshot is missing. The steps to reproduce are not reproduceable.

We need more information to debug the issue.

**Comment by gameDNAstudio** [comment]
I have exactly the same issue. The problem happened after upgrading to 3.7.0. It's still not fixed in 3.8.0.

![elementor_hidden](https://user-images.githubusercontent.com/15182229/199132642-7dfeb619-5815-4c92-bd8a-d4895485012b.png)

**Comment by gameDNAstudio** [comment]
Any update on this?

**Comment by gameDNAstudio** [comment]
This is critical issue...  I can't use "My Account" widget at all... is there maybe any workaround while waiting for a fix?

**Comment by calebgrove** [comment]
A workaround from the "Global Elementor Community" group on Facebook that worked for me.

> This is a known but unresolved bug in Elementor.
> As a workaround, make sure your single-page template in the theme builder is set to exclude the specific page that your My Account widget is on.
> For whatever reason, the My Account widget will not show up on any page that has a single page template applied.

**Comment by nicholaszein** [comment]
Hi there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by gameDNAstudio** [comment]
It shows the My Account widget now but there is other issues related to the same problem I think. Seems like widget or elements in the widget are duplicated what I can see in the Developer Tools Console. Please check the attached screenshot.

![MyAccountIssue](https://user-images.githubusercontent.com/15182229/209475408-104ca715-3272-40db-a55d-0712a788c050.jpg)

**Comment by calebgrove** [comment]
Can confirm what @gameDNAstudio is reporting. It looks good, but there are definitely duplicate "my account" elements in the ".e-my-account-tab" DOM element. One is just hidden with a .elementor-hidden class. I'm guessing this is some kind of a workaround?

**Comment by gameDNAstudio** [comment]
Any news about this? @nicholaszein
