### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by oncps** [elementor/elementor#19620]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi!
I would like to suggest a feature that would be very useful...

Add an option in the popup to open the popup already pulling a "URL REQUEST PARAMETER"...
to add a popup when no button click only appears the option (open popup, close popup and toggle popup), you can add an option to insert a request parameter when opening along with this popup it no longer has accurate information.. Example:
I have a user registration form, but in this form there is a hidden field and it takes a url that I specified mysite.com/? to another page....
I would like to do this with a popup already pulling this information from the url...
Is it possible to use this?
It would be great, I use the Popup for the user to login, but to register the user, I can't because I need to bring this value mysite.com/?aaa=bbb together with the url....

### Describe the solution you'd like

![popupelementor-request-parameter](https://user-images.githubusercontent.com/61298091/186941865-1ae7712a-a736-4882-88b2-d30eea73b1e8.png)
![popupelementor-request-parameter2](https://user-images.githubusercontent.com/61298091/186941868-458e6a43-4d6d-4d1e-ae34-e08110036533.png)

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by rami-elementor** [comment]
Hi @oncps ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap for the time being. It's a very specific use case.

Regards,
