### ISSUE TITLE
✔️ 🐞 Bug report: Flexbox Container & Scroll Snapping not working as expected

### ISSUE THREAD

**Issue by daniilicic** [elementor/elementor#19637]
### Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm using Flexbox Container experiment which is still in Alpha, but I wanted to point out an issue with it, while using Scroll Snap feature.

Scroll snapping works, but it snaps to each and every container on the page, no matter the nesting level. It all made sense when we had _Sections_ and _Inner Sections_. Then snapping worked properly and it snapped to sections only. Now, I cannot find a way for scroll to snap on the parent containers only (previously known as sections) and for it to ignore nested containers (previously called inner sections).

Here's the page I've been working on: https://ellipsis.hr/ellipsis-v2/ 
And here's the screenshot with a detailed explanation: https://tppr.me/sZqvr. Green lines mark the position where I'd expect scroll to snap, and red ones mark the additional positions to which it snaps.

### Steps to reproduce

Enable Flexbox Container experiment,
Enable Scroll Snap feature,
Use nested containers

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://ellipsis.hr
	Home URL: https://ellipsis.hr
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: daniilicic@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	Site Kit by Google
		Version: 1.81.0
		Author: Google

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Inactive
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 7 of 7PHP: 2021-11-23 05:29:08 [notice X 1][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::1024] Undefined index: pagination [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-11-23 05:43:35 [notice X 11][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 08:50:51 [notice X 1][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::186] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 09:07:02 [error X 1][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/includes/managers/widgets.php::372] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/includes/managers/widgets.php:372
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/ellipsis.hr/public_html/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /home/customer/www/ellipsis.hr/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /home/customer/www/ellipsis.hr/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /home/customer/www/ellipsis.hr/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 09:19:37 [notice X 2][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-12-29 09:24:00 [error X 1][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in /home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/includes/template-library/manager.php:457
Stack trace:
#0 /home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(63): Elementor\TemplateLibrary\Manager->import_template(Array)
#1 /home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates->create_items(Object(WP_REST_Request))
#2 /home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor/data/base/endpoint.php(320): Elementor\Data\Base\Endpoint->base_callback('POST', Object(WP_REST_Request), true)
#3 /home/customer/www/ellipsis.hr/public_html/wp-includes/rest-api/class-wp-rest-server.php(1140): Elementor\Data\Base\Endpoint->Elementor\Data\Base\{closure}(Object(WP_REST_Request))
#4 /home/customer/www/ellipsis.hr/public_html/wp-inclu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-05 02:15:18 [notice X 1][/home/customer/www/ellipsis.hr/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 322022-02-15 11:21:33 [info] elementor-pro::elementor_pro_updater Started 
2022-02-15 11:21:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-15 11:21:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-15 11:21:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.6.2',
)]
2022-02-15 11:21:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.6.2',
)]
2022-04-14 09:43:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.4',
)]
2022-04-14 09:43:05 [info] elementor::elementor_updater Started 
2022-04-14 09:43:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 09:43:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 09:43:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.4',
)]
2022-04-14 09:43:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.4',
)]
2022-07-26 06:18:05 [info] elementor::elementor_updater Started 
2022-07-26 06:18:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-26 06:18:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-26 06:18:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.7',
)]
2022-08-29 11:08:38 [info] elementor::elementor_updater Started 
2022-08-29 11:08:38 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-29 11:08:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-29 11:08:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.2',
)]
2022-08-29 11:08:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.2',
)]

JS: showing 3 of 3JS: 2022-02-15 11:24:40 [error X 3][https://ellipsis.hr/wp-content/plugins/dynamic-content-for-elementor/assets/js/dynamic-google-maps.js?ver=2.3.3:68:13] google is not defined 
JS: 2022-02-18 05:47:27 [error X 1][https://ellipsis.hr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453830] T is null 
JS: 2022-02-18 10:03:17 [error X 7][https://ellipsis.hr/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.5:2:29700] elementor.settings.page is undefined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello there @daniilicic!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
