### ISSUE TITLE
🐞 Bug report: Responsive Control Output not working properly in front-end

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#19643]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello author 
Responsive Control Output not working properly in front-end

### Steps to reproduce

1. Active additional breakpoints & active all available breakpoint like tablet extra, mobile extra..
2. Create a new page and edit with Elementor
3. Drag drop Spacer widget to the page.
4. Open Advanced Tab => Set it's background as Black for testing.
5. Select Responsive Mode: Tablet Extra
6. Open Layout section: 
Select Width: 'Custom'
Custom Width: 75%
![Screenshot at Aug 30 09-07-58](https://user-images.githubusercontent.com/7134267/187332937-8b5bf736-3cd0-4bfa-a58c-bc007e5932d7.png)

You will see it working properly in editor. But please save the page and check it on frontend.
Resize your browser:
When browser width > 1200px
![Screenshot at Aug 30 09-10-59](https://user-images.githubusercontent.com/7134267/187333094-5a9a3009-3278-482d-ab09-e6109a0cfcd8.png)

When browser width < 1200px
![Screenshot at Aug 30 09-11-24](https://user-images.githubusercontent.com/7134267/187333176-225114f9-7aac-400f-ae62-e78c09c8ac06.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-dungnv.local-30-08-2022.txt](https://github.com/elementor/elementor/files/9448977/system-info-dungnv.local-30-08-2022.txt)

**Comment by MarioFleetMon** [comment]
Same here! 🙋‍♂️

https://user-images.githubusercontent.com/112515131/187533393-c8ac4093-d86a-408c-a2e0-54eff143ba85.mov

https://user-images.githubusercontent.com/112515131/187533405-0eaabfab-11d9-412f-bc36-f2f882f97950.mov

I can only get the frontend to look like it does in the editor by pressing "Regenerate Files & Data" in the Elementor settings under "Tools". But I have to do this after each save in the editor. Also using Hello theme and Elementor Pro. Console does not throw any warnings/errors in the frontend.

**Comment by steve231293** [comment]
Please fix this bug asap. thanks

**Comment by jakebrightfire** [comment]
+1 Same here

**Comment by mattmckenny** [comment]
I chatted with Elementor support a couple days ago and, while very helpful, this bug isn't a priority. They have it logged internally as a bug but support said they need more examples of affected live sites to justify fixing the problem. 

I suggest reaching out via chat support and providing them with examples of your broken sites and have them link your support ticket to the existing internal issue on their side.

**Comment by steve231293** [comment]
@mattmckenny 
I do not understand why this issue not listed on High Priority. This bug affected many exist customers. It should be fix it asap

**Comment by steve231293** [comment]
Fixed in Elementor Core 3.7.5, closing.
