### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by bastien47** [elementor/elementor#19640]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello to everyone, I face a big problem with Elementor and JWPlayer, on my WordPress website. I would like to disable some buttons on the video player JWPlayer, by working on the CSS. I know it is possible because the JWPlayer support gave me some blocks to paste, and I saw some other dudes on internet doing this. I was happy with the Free version of Elementor, and I just bought today the Pro Version in order to being able to customize the CSS of the elements.

You can see my screenshot here :
https://postimg.cc/ZBq4ZdCF

The code I use :

**.jw-icon-rewind {display: none;}
.jw-icon-pip {display: none;}**

I also tried : 

**.jw-icon.jw-icon-inline.jw-button-color.jw-reset.jw-icon-rewind {display: none;}
.jw-icon.jw-icon-inline.jw-button-color.jw-reset.jw-icon-pip {display: none;}**

It should hide the “rewind” and “pip” buttons, but sadly it is not working. I’d be very grateful if someone could help me to fix that. And the JWPlayer element is showing from an embed iframe block

Have a nice day 🙂

### Steps to reproduce

The CSS blocks are simply not working when we paste it

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://singe-studio.com
	Home URL: https://singe-studio.com
	WP Multisite: No
	Max Upload Size: 256 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: 0
	Admin Email: dubroca.bastien@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	404page - your smart custom 404 error page
		Version: 11.3.1
		Author: Peter Raschendorfer

	Disable Right Click Ninetyseven Infotech
		Version: 1.0
		Author: Ninetyseven Infotech

	Elementor
		Version: 3.7.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Lightbox with PhotoSwipe
		Version: 5.0.6
		Author: Arno Welzel

	WP Fastest Cache
		Version: 1.0.4
		Author: Emre Vona

== Utilisation des éléments ==
	
	page : 1
		gallery : 2
		heading : 12
		html : 7
		icon : 1
		spacer : 10
		video : 7
	wp-page : 4
		button : 18
		heading : 4
		html : 27
		icon : 6
		image : 1
		spacer : 111
		text-editor : 70
		wp-widget-media_gallery : 2

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Envois de formulaire: Actif par défaut
	Scroll Snap: Actif par défaut

== Journal ==
	
JS: showing 8 of 8JS: 2022-07-16 02:13:03 [error X 18][https://singe-studio.com/wp-content/plugins/html5-video-player/dist/public.js?ver=2.5.6:1:1913] t.includes is not a function 
JS: 2022-07-16 05:13:10 [error X 1][https://singe-studio.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view28312\&quot;) has already been destroyed and cannot be used. 
JS: 2022-07-16 06:35:08 [error X 1][https://singe-studio.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view34483\&quot;) has already been destroyed and cannot be used. 
JS: 2022-07-22 15:56:11 [error X 1][https://singe-studio.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view2107\&quot;) has already been destroyed and cannot be used. 
JS: 2022-07-24 17:11:57 [error X 1][https://singe-studio.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view45795\&quot;) has already been destroyed and cannot be used. 
JS: 2022-07-26 18:26:41 [error X 1][https://singe-studio.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view54790\&quot;) has already been destroyed and cannot be used. 
JS: 2022-07-26 23:26:08 [error X 1][https://singe-studio.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view66292\&quot;) has already been destroyed and cannot be used. 
JS: 2022-08-12 18:07:49 [error X 2][https://singe-studio.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:293916] Cannot read properties of undefined (reading \&#039;html\&#039;) 

PHP: showing 3 of 3PHP: 2022-07-21 16:53:26 [notice X 2][/home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-21 21:27:02 [notice X 3][/home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/gt3-photo-video-gallery/core/elementor/class-core.php(98): Elementor\Controls_Manager -> register()
#4: /home/u966558761/domains/singe-studio.com/public_html/wp-includes/class-wp-hook.php(307): GT3\PhotoVideoGallery\Elementor\Core -> controls_registered()
',
)]
PHP: 2022-07-27 00:32:13 [error X 3][/home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 /home/u966558761/domains/singe-studio.com/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 /home/u966558761/domains/singe-studio.com/public_html/w [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 322022-08-14 12:06:39 [info] elementor::elementor_updater Started 
2022-08-14 12:06:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-14 12:06:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-14 12:06:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-14 12:06:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-21 11:15:26 [info] elementor::elementor_updater Started 
2022-08-21 11:15:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-21 11:15:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-21 11:15:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-21 11:15:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-29 11:31:10 [info] elementor-pro::elementor_pro_updater Started 
2022-08-29 11:31:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-29 11:31:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-29 11:31:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-29 11:31:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-29 13:09:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-29 13:09:47 [info] elementor::elementor_updater Started 
2022-08-29 13:09:47 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-29 13:09:47 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-29 13:09:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by progressmedia** [comment]
+1 Would love a native plugin/app for JW Player on Elementor
