### ISSUE TITLE
🐞 Bug report: Improved Asset Loading increases the amount of js requests.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19653]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Before I enabled the Improved Asset Loading option, the number of js requests on my site's homepage was 13. But when I disabled this option, the number of js requests decreased to 4!
This looks completely unnatural.

### Steps to reproduce

Using the Chrome browser console, compare the number of js requests on your website pages before and after activating the Improved Asset Loading option.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
@Michaelgimii 

What bug are you trying to report here?

**Comment by rami-elementor** [comment]
Please read more about the **Improved Asset Loading** experiment and how we reduce the number of CSS/JS requests: https://elementor.com/help/conditional-and-inline-css-load-experiment/

**Comment by Michaelgimii** [comment]
Thanks for the link @rami-elementor.
By enabling **Improved Asset Loading**, 8 js requests will be added. Is this normal?
