### ISSUE TITLE
🚀 Feature Request: responsive control for opacity options in background overlay (in section & container)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19659]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi
Please add the responsive control to the opacity option. Currently, we can only apply opacity globally, but we cannot control it on desktop, tablet and mobile separately.

### Describe the solution you'd like

Please add the responsive control to the opacity option (in section & container).

![download](https://user-images.githubusercontent.com/77163248/187658506-46623875-6194-4604-a1f5-3cd3c73abb09.png)

**Comment by Michaelgimii** [comment]
+1 for this Great request

**Comment by rami-elementor** [comment]
Love this idea.

**Use Case**: I had bg images that looked good on desktop but in mobile the bg messed the elements. changing the opacity only on mobile could of solved it.

**Comment by rami-elementor** [comment]
Hi @79ho3ein @Michaelgimii 

You request was implemented and merged to Elementor 3.9.

![19659](https://user-images.githubusercontent.com/92088692/192995516-17ac9296-f2d4-450b-9541-63eda795ae94.png)

**Comment by 79ho3ein** [comment]
Thank you for your efforts @rami-elementor

**Comment by nicholaszein** [comment]
Hello! 🙂 

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

Thank you for your contribution! 🙏 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
