### ISSUE TITLE
🚀 Feature Request: Set size of Background Images

### ISSUE THREAD

**Issue by MJNinja** [elementor/elementor#19657]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I have clients who manage their own website but they don't resize the images (background images) that they upload, thus increasing the loading speed of their website. If we had an option to choose the size of the background image, then I wouldn't have to worry how they upload the images as they will be forced to a predefined size.

### Describe the solution you'd like

It would be great if we had the option to set the size of a background image, similar to what we can do with normal images (image widget).
![image-size](https://user-images.githubusercontent.com/35722976/187640697-36abd874-5596-4961-b38b-226fee68d162.png)

### Describe alternatives you've considered

One solution I came up with was to use the image widget and custom css to make it behave like a background image, but it is quite messy to achieve.

**Comment by arielk** [comment]
This feature is part of the new beta version (3.11) please follow this issue: https://github.com/elementor/elementor/issues/6778

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
