### ISSUE TITLE
🐞 Bug report: Not able to edit the size and position when changing the responsive to mobile / tablet when using custom mode.

### ISSUE THREAD

**Issue by UserMing24** [elementor/elementor#19662]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, I've discovered an issue that I'm not able to edit the background size and position when I use the custom mode and set it to either mobile / tablet responsive. The adjustment bar is just not there when switching to mobile/tablet mode. It only appears on desktop mode. For the previous version, I'm able to make different adjustments to each responsive mode respectively.

May I know what is the issue? Your advice is appreciated. Thanks

Screenshots for references:
![Desktop](https://user-images.githubusercontent.com/112555188/187670846-c9f3c35d-ccc3-4dcd-96b9-458027920cb8.png)
![Tablet](https://user-images.githubusercontent.com/112555188/187670849-81b18507-9f86-40d1-8ae4-22dc9ed2eef1.png)
![Mobile](https://user-images.githubusercontent.com/112555188/187670842-fdbba274-5936-4320-bf6f-d87066837b78.png)

### Steps to reproduce

Open elementor editor. Edit a section background image. Select "position" or "size" and choose custom. Then go to either tablet / mobile responsive. Then the adjustments are not there except on desktop mode.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.30
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://www.vmagic-products.com
	Home URL: https://www.vmagic-products.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 8
	Admin Email: admin@vmagic-products.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Crocoblock
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Ajax Cart AutoUpdate for WooCommerce
		Version: 1.5.5
		Author: taisho

	Better Notifications for WP
		Version: 1.8.11
		Author: Made with Fuel

	CartFlows
		Version: 1.10.3
		Author: CartFlows Inc

	CartFlows Pro
		Version: 1.9.2
		Author: CartFlows Inc

	Content Control
		Version: 1.1.9
		Author: Code Atlantic

	Crocoblock Wizard
		Version: 1.2.5
		Author: Crocoblock

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.2.3
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.1.5
		Author: WPDeveloper

	JetBlocks For Elementor
		Version: 1.3.3
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.3.1
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetEngine
		Version: 3.0.3.1
		Author: Crocoblock

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	JetPopup
		Version: 1.5.6
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.6
		Author: Crocoblock

	JetSearch
		Version: 3.0.2
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.13
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.19
		Author: Crocoblock

	JetThemeCore
		Version: 2.0.6
		Author: Crocoblock

	JetTricks
		Version: 1.4.2
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.0.3
		Author: Crocoblock

	Joinchat
		Version: 4.5.9
		Author: Creame

	LiteSpeed Cache
		Version: 5.0
		Author: LiteSpeed Technologies

	LoftLoader Pro
		Version: 2.3.2
		Author: Loft.Ocean

	Loginizer
		Version: 1.7.2
		Author: Softaculous

	LoginPress - Customizing the WordPress Login Screen.
		Version: 1.6.2
		Author: WPBrigade

	LoginPress Pro
		Version: 2.5.2
		Author: WPBrigade

	Qty Increment Buttons for WooCommerce
		Version: 2.7.5
		Author: taisho

	Rank Math SEO
		Version: 1.0.93.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.10.1
		Author: Rank Math

	Simple Custom CSS and JS PRO
		Version: 4.28
		Author: SilkyPress.com

	Site Kit by Google
		Version: 1.79.1
		Author: Google

	Smart Manager - WooCommerce Inventory Management, Bulk Edit & more...
		Version: 6.2.0
		Author: StoreApps

	TranslatePress - Business
		Version: 1.1.2
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu

	TranslatePress - Multilingual
		Version: 2.3.3
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	WooCommerce
		Version: 6.8.2
		Author: Automattic

	WooCommerce Dynamic Pricing & Discounts
		Version: 2.4.3
		Author: RightPress

	Wordfence Security
		Version: 7.5.11
		Author: Wordfence

	WPFront Scroll Top
		Version: 2.0.7.08086
		Author: Syam Mohan

	WP Mail SMTP Pro
		Version: 3.4.0
		Author: WPForms

	YITH WooCommerce Color and Label Variations Premium
		Version: 1.15.0
		Author: YITH

	YITH WooCommerce Tab Manager Premium
		Version: 1.2.35
		Author: YITH

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 12 of 12PHP: 2022-07-26 08:47:03 [notice X 161][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-26 08:51:24 [notice X 1606][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-26 17:29:41 [notice X 29][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/sabahdet/vmagic-products.com/wp-content/plugins/jet-popup/includes/elementor-finder/elementor-finder.php(47): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]
PHP: 2022-07-26 17:29:57 [notice X 4277][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-26 17:30:12 [notice X 469][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/sabahdet/vmagic-products.com/wp-content/plugins/jet-popup/includes/integration.php(134): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-27 12:36:36 [notice X 3][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-28 16:39:56 [notice X 1][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-28 16:48:01 [notice X 2][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/template-library/sources/local.php::1396] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-28 16:59:29 [notice X 120][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: apply_indexer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-08 14:50:58 [notice X 1][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-25 14:36:59 [notice X 36][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/core/base/document.php::250] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-25 14:37:05 [notice X 36][/home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/sabahdet/vmagic-products.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/sabahdet/vmagic-products.com/wp-content/plugins/jet-popup/includes/integration.php(134): Elementor\Controls_Manager -> register_control()
',
)]

JS: showing 10 of 10JS: 2022-07-27 05:37:37 [error X 1][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:490088] Cannot read properties of null (reading \'id\') 
JS: 2022-07-27 08:23:10 [error X 1][https://www.vmagic-products.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.7.2:1:741] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-07-27 08:24:37 [error X 18][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:548544] T.getContainer is not a function 
JS: 2022-07-28 08:59:45 [error X 1][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:205789] C.ui.sync.removeClass is not a function 
JS: 2022-07-28 09:10:45 [error X 1][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view27411\") has already been destroyed and cannot be used. 
JS: 2022-07-29 04:53:40 [error X 12][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897948] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-07-29 09:32:13 [error X 282][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.7:2:12186] r.get is not a function 
JS: 2022-07-29 09:39:52 [error X 11][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:443987] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-08-02 15:27:12 [error X 1][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.7:2:20759] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `custom_thumb` value. Expected array or object.',
)]
JS: 2022-08-05 04:12:57 [error X 1][https://www.vmagic-products.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view29001\") has already been destroyed and cannot be used. 

Log: showing 12 of 122022-08-25 14:33:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.2',
)]
2022-08-25 14:33:05 [info] elementor::elementor_updater Started 
2022-08-25 14:33:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-25 14:33:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-25 14:33:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.2',
)]
2022-08-25 14:33:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.2',
)]
2022-08-25 15:14:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-25 15:14:08 [info] elementor-pro::elementor_pro_updater Started 
2022-08-25 15:14:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-25 15:14:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-25 15:14:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-25 15:14:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified
	JetBlocks For Elementor: Compatibility not specified
	JetBlog For Elementor: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	JetWooBuilder For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by mjcreative** [comment]
Came to report the same issue

**Comment by jamieburchell** [comment]
This is still not working properly in 3.7.6. The controls are shown now, but the values change to zero!

https://watch.screencastify.com/v/7JJQmkVXB9uWEEXpmijf

**Comment by avivu** [comment]
This issue has been resolved in Elementor v3.7.7

Feel free to update

Thanks!
