### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by Wowservicios** [elementor/elementor#19668]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, I have reach the Elementor support and they told me that as is a Code error from Elementor I have to explain it here so I can get support from their developers.

I explain the problem:
I'm the website designer at mini-shirts.com, after the last update the site goes down and breakes the design (most the CSS estetics), sometimes it doesn't alow me to access the site and the visual and funcionality problems are random, sometimes the site doens't load at all giving me a server error, so I've reach the hosting provider thinking it was a problem from them but they answer me the following, then I contacted Elementor support and I end up here.

The hosting answer is:

You will see that although there have been several punctual peaks, the use of resources has already stabilized.

During these spikes we see that many calls to JS and CSS files were being made from a code minification function. I see that you use the Elementor plugin. Is it possible that you have recently purged the cache from the options of said plugin? Since we see that at the moment said cache is partially empty.

We understand that you have been performing maintenance tasks in the last few hours. If you can give us more details of the actions carried out, we may be able to help you avoid resource usage spikes again.

In any case, we see that the problem points to being in the Elementor plugin. This plugin can make very intensive use of resources in certain cases, so we recommend you review its configuration.

We also see that the front end of the web fires several POST calls of the admin-ajax type with the "elementor_menu_cart_fragments" action, which we see corresponds to Elementor Pro.

Since you use Elementor Pro, we recommend that you consult its support for some guidelines on how to optimize its performance.

--
Hope you can help me out, I've deactivated all the rest of the plugins, change the css file to external and back to internal, change the main theme but the problems goes on...

I forgot to mention that besides that with only Elementor plugin activated the server CPU goes crasy consuming all the resourses, and it's a good and a powerful hosting with:
PHP Version: 7.4.29
PHP Memory Limit: 1024M
PHP Max Input Vars: 20000
PHP Max Post Size: 512M

Thank you very much,
Kindly regards,
Darío

### Steps to reproduce

The problems are ramdon, but when editing anything at the site it breaks down.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://mini-shirts.com
	Home URL: https://mini-shirts.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 1
	Admin Email: info@mini-shirts.com
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Theme Code
		Version: 2.5.3
		Author: Ben Pearson and Phil Kurth

	Advanced Custom Fields PRO
		Version: 5.10.1
		Author: Delicious Brains

	Advanced Dynamic Pricing for WooCommerce (Pro) (build 621)
		Version: 4.0.0
		Author: AlgolPlus

	Checkout Fields Manager for WooCommerce
		Version: 6.1.8
		Author: QuadLayers

	Code Snippets
		Version: 3.2.0
		Author: Code Snippets Pro

	Elementor
		Version: 3.6.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.21
		Author: Facebook

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	Google Ads &amp; Marketing by Kliken
		Version: 1.0.8
		Author: Kliken

	Joinchat
		Version: 4.5.9
		Author: Creame

	Mailchimp for WooCommerce
		Version: 2.7.2
		Author: Mailchimp

	Rank Math SEO
		Version: 1.0.96
		Author: Rank Math

	RedSys Gateway for WooCommerce Pro
		Version: 2.8.7
		Author: codection

	StoreCustomizer
		Version: 2.4.3
		Author: Kaira

	WooCommerce
		Version: 6.8.2
		Author: Automattic

	WooCommerce Custom Fields
		Version: 2.3.4
		Author: RightPress

	WooCommerce Multi Currency Premium
		Version: 2.1.21
		Author: VillaTheme

	WooCommerce Multilingual &amp; Multicurrency
		Version: 5.0.2
		Author: OnTheGoSystems

	WooCommerce PDF Invoices &amp; Packing Slips
		Version: 3.0.1
		Author: WP Overnight

	WooLentor - WooCommerce Elementor Addons + Builder
		Version: 2.4.4
		Author: HasThemes

	WP Mail Logging
		Version: 1.10.4
		Author: Wysija

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

	WPML Media
		Version: 2.7.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.5.8
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.1
		Author: OnTheGoSystems

	WP Rocket
		Version: 3.12.0.4
		Author: WP Media

== Uso de los elementos ==
	
	header : 1
		image : 3
		nav-menu : 3
		woocommerce-menu-cart : 3
		wpml-language-switcher : 3
	page : 5
		button : 1
		heading : 1
		icon : 1
		text-editor : 1
	section : 9
		divider : 9
		heading : 42
		icon-list : 5
		image : 17
		social-icons : 2
		spacer : 16
		text-editor : 4
		wl-single-product-image : 1
		woolentor-universal-product : 3
		wpml-language-switcher : 3
	wp-page : 40
		button : 5
		divider : 1
		heading : 44
		icon-list : 1
		image : 48
		image-carousel : 1
		shortcode : 1
		social-icons : 2
		spacer : 47
		tabs : 3
		text-editor : 71
		woolentor-universal-product : 8

== Experimentos de Elementor ==
	Salida del DOM optimizada: Inactivo por defecto
	Carga de recursos mejorada: Inactivo por defecto
	Carga de CSS mejorada: Inactivo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Mejoras de accesibilidad: Inactivo por defecto
	Importar o exportar un kit de plantillas: Activo por defecto
	Puntos de ruptura personalizados adicionales: Inactivo por defecto
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo por defecto
	: Inactivo por defecto
	Contenedor Flexbox: Inactivo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Páginas de destino: Activo por defecto
	Muestrario de colores: Activo por defecto
	Widgets favoritos: Activo por defecto
	Barra superior de administración: Activo por defecto
	Transiciones de páginas: Activo por defecto
	Notes: Activo por defecto
	Envíos de formulario: Activo
	Ajuste de scroll: Activo por defecto

== Registro ==
	
Log: showing 20 of 372022-08-25 11:09:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-25 11:09:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-08-25 11:09:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-08-25 12:11:27 [info] elementor-pro::elementor_pro_updater Started 
2022-08-25 12:11:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-25 12:11:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-25 12:11:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.3',
)]
2022-08-25 12:11:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.3',
)]
2022-08-30 17:24:58 [info] elementor::elementor_updater Started 
2022-08-30 17:24:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-30 17:24:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-30 17:24:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-30 17:25:02 [info] elementor-pro::elementor_pro_updater Started 
2022-08-30 17:25:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-30 17:25:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-30 17:25:02 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-08-30 17:25:02 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products callback needs to run more 1 times 
2022-08-30 17:25:02 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start (2 of 2, 100%) 
2022-08-30 17:25:02 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-08-30 17:25:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]

PHP: showing 5 of 5PHP: 2022-05-14 12:12:42 [error X 12][/home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor-pro/modules/notes/usage.php::161] Uncaught Error: Call to a member function format() on null in /home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor-pro/modules/notes/usage.php:161
Stack trace:
#0 /home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor-pro/modules/notes/usage.php(43): ElementorPro\Modules\Notes\Usage-&gt;get_first_interaction()
#1 /home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor-pro/modules/notes/usage.php(27): ElementorPro\Modules\Notes\Usage-&gt;get_usage_data()
#2 /home2/minishir/public_html/mini-shirts.com/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Notes\Usage-&gt;ElementorPro\Modules\Notes\{closure}(Array)
#3 /home2/minishir/public_html/mini-shirts.com/wp-includes/plugin.php(189): WP_Hook-&gt;apply_filters(Array, Array)
#4 /home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor/includes/tracker.php(563): apply_filters(&#039;elementor/track...&#039;, Array)
#5 /home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor/includes/tracker.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-14 17:50:43 [notice X 1][/home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-29 19:00:25 [notice X 1][/home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-25 15:13:35 [notice X 2][/home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor/core/base/document.php::250] Trying to get property &#039;ID&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-31 18:40:45 [notice X 1][/home2/minishir/public_html/mini-shirts.com/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-08-25 10:38:22 [error X 1][https://mini-shirts.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.2:2:24023] Cannot read properties of undefined (reading \&#039;cid\&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	WooLentor - WooCommerce Elementor Addons + Builder: Compatible

== Elementor Pro - Compatibility Tag ==
	
	WooLentor - WooCommerce Elementor Addons + Builder: Compatible

**Comment by Wowservicios** [comment]
I forgot to mention that besides that with only Elementor plugin activated the server CPU goes crasy consuming all the resourses, and it's a good and a powerful hosting with:

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
