### ISSUE TITLE
✔️ 🐞 Bug report: Issue with elementor dark mode

### ISSUE THREAD

**Issue by JackobStuard** [elementor/elementor#19670]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,

I have Chrome Dark mode on mac
For some reason when I go to **Edit with Elementor -> Theme Builder**
I get a white version of Theme Builder.
Bellow is screenshot of that white version

![Screen Shot 2022-08-31 at 21 57 31](https://user-images.githubusercontent.com/40763985/187771894-f7ccc2ea-ecb7-4504-a5a0-0f24b8002519.png)
![Screen Shot 2022-08-31 at 21 57 37](https://user-images.githubusercontent.com/40763985/187771902-6ee0d1ea-5ae3-4e45-af83-628eeb720077.png)

All other elementor page builders display dark mode but only Theme builder display white mode
I test to remove all plugins and active only Elementor and Hello theme and that issue happened with white mode. 

### Steps to reproduce

I test to remove all plugins and active only Elementor and Hello theme and that issue happened with white mode. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://testingplugins.local
	Home URL: http://testingplugins.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: test@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.5
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 10 of 102022-08-31 19:59:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.4',
)]
2022-08-31 19:59:14 [info] elementor::elementor_updater Started 
2022-08-31 19:59:14 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-31 19:59:14 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-31 19:59:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.4',
)]
2022-08-31 20:00:16 [info] elementor-pro::elementor_pro_updater Started 
2022-08-31 20:00:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-31 20:00:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-31 20:00:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.5',
)]
2022-08-31 20:00:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.5',
)]

PHP: showing 1 of 1PHP: 2022-08-31 20:01:10 [notice X 1][/Users/user/Local Sites/testingplugins/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by hitsgee** [comment]
Mine displays dark mode however I have it set to dark in the editor not auto. You can change it under preferences.

Guess it's a bug with auto not detecting your browser default.

Custom code is always in light mode though. Not sure if they have dark for this yet

**Comment by JackobStuard** [comment]
Can you pls share what exact settings how to put dark mode? as I cant found that preferences?

This issue is for me a very long time, before elementor detect that Theme Builder without any issues and displays dark mode every time. I hope that dev team from elementor will fix this bug with white mode to display dark mode if browser is dark mode.

**Comment by hitsgee** [comment]
Sure. Screenshots below. Hope they can fix this bug on auto, though.

![Elementor-About](https://user-images.githubusercontent.com/40209785/187890725-dffc1527-f209-40e9-b670-a2dfd56661a3.png)
![Elementor-About (1)](https://user-images.githubusercontent.com/40209785/187890719-b6a7988f-7cd6-4027-83ff-246d70b5c00e.png)

**Comment by JackobStuard** [comment]
Yes, thank you, now is awesome!

For new users if example user have light mode in chrome will show that user dark mode? or this setting what I change only affect me?

**Comment by hitsgee** [comment]
It is individual to each user. So only applies to your user account.

Everyone else will be on default unless changed in preferences.

**Comment by JackobStuard** [comment]
Intersting, thank you for info.

Anyway, it will be good for future updates to elementor fix this "auto" settings.
Thank you for helping.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that issue was solved with Elementor **v3.10**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
