### ISSUE TITLE
🐞 Bug report: Elementor Image Element - Attachment Caption (not working when link = media file)

### ISSUE THREAD

**Issue by IMTanuki** [elementor/elementor#19679]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

**Context**
- elementor image element
- median attachment has a caption updated in the media library

Issue
- if caption option is set to "custom" then the custom caption displays correctly
- if the caption option is set to media file (so that lightbox can be used) then no caption is displayed, even though one exists in the media attachmnet

**Workarounds** 
The only workaround is to:
- always set caption option to "custom" and manually enter the caption (even if it's maintained in the media attachment)

 **Other**
- not related to containers

### Steps to reproduce

**Screencast**
https://imtanuki.tinytake.com/msc/NzI5NjQ3NF8yMDEzMjIyNQ
https://imtanuki.tinytake.com/msc/NzI5NjQ5Nl8yMDEzMjI2MQ

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-dev04.sinologix.io-01-09-2022.txt](https://github.com/elementor/elementor/files/9470406/system-info-dev04.sinologix.io-01-09-2022.txt)

**Comment by rami-elementor** [comment]
Hi @IMTanuki 

I can't recreate the issue. Tested on a new WP installation with the latest Elementor & Elementor Pro.

**Comment by IMTanuki** [comment]
Sorry - I had previously updated the caption for every img on my site and for some reason I can't figure out, the caption for the img in question didn't get saved. Should have double-checked. Sorry for the fire drill.
