### ISSUE TITLE
✅ 🚀 Feature Request: improve select field in elementor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19676]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In some sections of the Elementor editor, we have [this field](https://prnt.sc/yeG2bHO6Sf_D) to select options. On the other hand, some third-party plugins use this Elementor field in their plugins and there may be many options to choose from. Like jet woobuilder plugin : https://prnt.sc/XGtfsg3DI_so

It is better to add an attribute to these types of fields in the editor so that if we select an option, it will be highlighted.
An example to describe this request is the WooCommerce feature selection section on the product page. On the add product page, features that are selected have a different color than options that are not selected : https://prnt.sc/wXK6JxZtiTc2

### Describe the solution you'd like

Add a property to this type of select field, so that the options we select are highlighted. This makes the options that are selected different from the options that are not selected. (A bold background for selected options can be great)

**Comment by rami-elementor** [comment]
To refine the request I will state that you are basically requesting to style the selected items inside the **SELECT2** control, when the used is using dark mode.

**Comment by Michaelgimii** [comment]
@rami-elementor , If I understand you correctly, my request was not actually that we can customize it. Rather, it is a simple change in the structure of the SELECT2 control so that the selected options are easy to understand.

For better understanding, please see this : https://github.com/Crocoblock/suggestions/issues/5847

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

This issue was solved a while ago, during one of the updates. For this reason, I'm closing it as solved!

Thanks for your contribution! 🙏
