### ISSUE TITLE
Elementor does not start at all in wordpress

### ISSUE THREAD

**Issue by Amalth87** [elementor/elementor#19685]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm new on Hostinger.
I've launched word press. 
Installed eliminator plugin. Unable to launch it, even in safe mode.
Deactivated all the other plugins.
But still stuck...

And as it's the hostinger's environment, i trust the settings/memory, etc.

Am i the only one to face this issue ?

### Steps to reproduce

just trying to edit a page with elementor.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.16 |  
PHP Version: | 7.4.30 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by rami-elementor** [comment]
Hi @Amalth87 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
