### ISSUE TITLE
🐞 Bug report: The handle of the first container is not in the center. (Occurs only in RTL)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19680]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi 
If you add the first container inside the page in RTL, its handle is not centered and slightly tilted to the left. (image below).

![(1)](https://user-images.githubusercontent.com/77163248/187956054-849b8b05-3ad8-4de8-a6a2-7e8a816cb33e.png)

But if we add the second container, there is no problem (image below)

![(2)](https://user-images.githubusercontent.com/77163248/187956794-bdf0fc29-8dae-4d38-99c0-fc210df6e748.png)

**Generally, this bug occurs in 2 situations.**

- On the RTL website
- In the first page container

**This bug is on all pages as well as Elementor theme builder (header, footer, popup, etc) it happens.**

### Steps to reproduce

1- Make sure it's the RTL website.
2- On one page, add the first container.

The handle of the container will not be in the center.

3- Now add another container below the previous one. Everything will be fine in the second Kanitner.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by 79ho3ein** [comment]
This problem is especially noticeable in mobile mode.

![(1)](https://user-images.githubusercontent.com/77163248/190847644-bc0c3bec-6de1-4b0b-92b4-ac607898727c.png)

I remind you again. **This bug only occurs for the first container**. It displays well in other containers.

![(1)](https://user-images.githubusercontent.com/77163248/190847732-eb3e8725-92ee-46a1-9893-b9f6a0f9f2ee.png)


Oh, I just got it. This bug occurs if the tab mode is on canvas. (also header, footer, pop-up, etc.) @rami-elementor , @udidol.

**Therefore, this bug exists in the following conditions :**

- RTL websites
- canvas mode - header - footer - popup and ...

**Comment by EilamGit** [comment]
@rami-elementor open a fix for this bug: [ED-8234]
