### ISSUE TITLE
Issue in loading a website : Website Page appears white Blank

### ISSUE THREAD

**Issue by Singhvijita5** [elementor/elementor#19682]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My website: www.vijitasingh.com

Blank page is appearing, don't know how to fix it.

### Steps to reproduce

www.vijitasingh.com

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://vijitasingh.com/

**Comment by arielk** [comment]
In order for us to look into this matter, please contact our tech support through your account, with complete login information to access your website and our support team will try to assist.

**Comment by Singhvijita5** [comment]
Please share contact details with me. Where to contact, and what is a
contact detail?
