### ISSUE TITLE
Elementor should not globally reset link & image element styles.

### ISSUE THREAD

**Issue by wpexplorer** [elementor/elementor#19689]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Currently the plugin's CSS - https://github.com/elementor/elementor/blob/cf465842dd6e009cd50847f4ed2b8e289b875a10/assets/dev/scss/frontend/_global.scss - is removing border radius, box shadow and other properties from images as well as text decoration from links.

```
a {
    box-shadow: none;
    text-decoration: none;
}

img {
    height: auto;
    max-width: 100%;
    border: none;
    border-radius: 0;
    box-shadow: none;
}
```

Yes, it targets the ".elementor" class, but this class is a generic class added around all Elementor widgets. The issue is if you have custom widgets or if you are using the Theme Builder where these styles will override default/expected behaviour.

This is especially problematic when using a CSS utility frameworks such as Tailwind. Let's say you you have a custom widget and an option to apply a shadow to an image inside that widget and the shadow is added with a utility class, the shadow will never be applied do to the higher priority of the CSS targeted by Elementor. Example: 

<img width="1448" alt="Screen Shot 2022-09-02 at 5 59 14 PM" src="https://user-images.githubusercontent.com/1128841/188249647-6f3044be-0d8c-4445-83c2-297f17d57406.png">

With the links it's also an issue. Lets say your default theme design has underlined links and that's what you want. Well if you use a text block in Elementor or you use the Theme Builder and the post content widget you would expect your links to be underlined but they won't be.

Ideally Elementor would target widgets/elements as needed and not globally.

I understand this is not a "Bug" per-se but its an issue that I believe should be addressed. Thanks ;)

### Steps to reproduce

1. Install Elementor
2. Use Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not necessary.

**Comment by wpexplorer** [comment]
Just found some other CSS that's doing hard resets on elements inside elementor:

```
.elementor .elementor-widget:not(.elementor-widget-text-editor):not(.elementor-widget-theme-post-content) figure {
    margin: 0;
}
```

**Comment by rami-elementor** [comment]
Hi @wpexplorer ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. Many themes add their own styles, if we want to make the Elementor styling consistent, we have to reset some elements.

Regards,

**Comment by wpexplorer** [comment]
@rami-elementor

Any chance you could at least tweak the CSS to include a general :not() pseudo-class that can be used by custom Widgets. So for example the CSS could be modified to something like this:

<pre>
.elementor .elementor-widget:not(.elementor-widget-no-resets) img {
    height: auto;
    max-width: 100%;
    border: none;
    border-radius: 0;
    box-shadow: none;
}
</pre>

So we could simply use the "elementor-widget-no-resets" class on any widget that we don't want modified by Elementor Styles? This way you aren't "forcing" Elementor styles for everyone while still keeping everything working how it's always worked.

Thank you for considering!

**Comment by rsepierre** [comment]
> Hi [@wpexplorer](https://github.com/wpexplorer) ,
> 
> Thank you for submitting a feature request.
> 
> After review, we have decided not to add this to our roadmap for the time being. Many themes add their own styles, if we want to make the Elementor styling consistent, we have to reset some elements.
> 
> Regards,

Not removing your 

> Hi [@wpexplorer](https://github.com/wpexplorer) ,
> 
> Thank you for submitting a feature request.
> 
> After review, we have decided not to add this to our roadmap for the time being. Many themes add their own styles, if we want to make the Elementor styling consistent, we have to reset some elements.
> 
> Regards,

It is actually a horror to set default link styling with elementor. 
You can not make them "underline" (which is the browser default) without forcing all buttons elementor to be underlined. 
For exemple in a "wordpress menu" widget, set a typography styling to "text-decoration : none" will somehow not override a ".elementor a { text-decoration: underline} that you would have set to override the styling added by elementor. 

There is also no way to set every "wyswig editor" links to underline for exemple  .elementor-widget-text-editor a works, but non elementor content using elementor theme builder will still get overridden by .elementor and will have no specific class enabling to style this type of content specifically.

If you have to do all styling with CSS by hand, uninstall elementor and create a template from a boilerplate.

**Comment by wpexplorer** [comment]
@rami-elementor - Can you at least implement what Gutenberg does by lowering the priority of the builder's styles? This way, the theme styles would take precedence.

Gutenberg accomplishes this by using the CSS :where() pseudo class, ex:

```
:where(a) {
    box-shadow: none;
    text-decoration: none;
}

:where(img) {
    height: auto;
    max-width: 100%;
    border: none;
    border-radius: 0;
    box-shadow: none;
}

```

In the context of a page builder, having the builder override theme styles is problematic because it leads to a mismatch in design, causing inconsistencies between the page builder and the theme.

I understand targeting specific builder elements that are part of Elementor, but elements like images and links (without a class name) are generic, and their styling should come from the theme.

Thank you!

- AJ
