### ISSUE TITLE
bug in Multi-Select feature

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19691]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi
I tried to move the desired widgets to another location using the Multi-Select feature. **But after transfer, each widget was added inside a section.** Shouldn't they all be added in one section?

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/188266421-165e1a69-1b23-4ff2-b786-448a58160bea.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by arielk** [comment]
Hi @79ho3ein,

If you drag a widget to the new section it should open a section for the widget you paste, so if you drag several widgets at once it will open **multiple** sections.

To avoid this, you should open a section first and only then paste the widgets in. So it's not a bug, it's normal behavior.

Thank you very much for the feedback!
