### ISSUE TITLE
Can't add products

### ISSUE THREAD

**Issue by Leax-sneakers** [elementor/elementor#19699]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have this website like three months and just nearly one month i was able to sell and then everything, so all products were gone and i was not able to add products. I am really frustrated right know, because i pay for that website, but i am not able to profit from that.

### Steps to reproduce

1. i just add pictures from the internet for my products i wanted to sell
2. one week after that all was gone
3. even i saved all the products before, all is gone
4. i dont know how it happens

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

i can't do anything, so i can't add some products or view them. I can do nothing with this website i am paying for.

**Comment by learnarabicquranonline** [comment]
h

**Comment by rami-elementor** [comment]
Hi @Leax-sneakers ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
