### ISSUE TITLE
Blank Website technical issue

### ISSUE THREAD

**Issue by Singhvijita5** [elementor/elementor#19703]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I can't access My website. Blank page is appearing
Website:www.vijitasingh.com
WordPress Password: 7A(QnXP%f*DFa!eq

### Steps to reproduce

I don't know, just please help me to fix this issue. My website is appearing blank.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

https://vijitasingh.com/

**Comment by m1ga** [comment]
You shouldn't post your password here! Now everyone can access your site! Please remove it and change your password @Singhvijita5

**Comment by Singhvijita5** [comment]
Oh Gosh, I didn't know that.

**Comment by Singhvijita5** [comment]
Hey Michael, I changed my password. Thanks for informing.
Could you please let me know How to resolve this Blank website issue?

I will appreciate your help.

**Comment by m1ga** [comment]
Sorry, can't do that. But did you follow the old reply https://github.com/elementor/elementor/issues/19682#issuecomment-1235178736 and use https://elementor.com/support/ to contact support?

**Comment by rami-elementor** [comment]
Hi @Singhvijita5 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
