### ISSUE TITLE
🐞 Bug report: Can't add new custom CSS

### ISSUE THREAD

**Issue by AndreasH08** [elementor/elementor#19707]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've been looking into this for a while now, and from what I can tell, the new custom CSS I create is being added to the post CSS file, but it's not being shown on the front end.

So the new custom CSS I write is in the post CSS, but I can't see it on the front end :/

I have tried to clear all cache and regenerate the CSS with no results 

### Steps to reproduce

I have no idea how to reproduce it 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://eloomi.com
	Home URL: https://eloomi.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 96M
	Max Memory limit: 1024M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: Europe/Copenhagen
	Admin Email: info@eloomi.com
	Debug Mode: Inactive

== Theme ==
	Name: Stratus - Child Theme
	Version: 3.0
	Author: Themovation
	Child Theme: Yes
	Parent Theme Name: Stratus
	Parent Theme Version: 4.2.2
	Parent Theme Author: Themovation

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	CookiePro
		Version: 1.0.4
		Author: OneTrust, Llc

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.7.7
		Author: Dynamic.ooo

	Elementor
		Version: 3.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.5
		Author: Elementor.com

	Envato Market
		Version: 2.0.6
		Author: Envato

	Facebook for WordPress
		Version: 3.0.7
		Author: Facebook

	FileBird
		Version: 5.0.5
		Author: Ninja Team

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	Imagify
		Version: 2.0
		Author: Imagify - Optimize Images & Convert WebP

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Max Mega Menu
		Version: 2.9.8
		Author: megamenu.com

	OptionTree
		Version: 2.7.3
		Author: Derek Herman

	Page Builder Widget Pack
		Version: 2.1.14
		Author: Themovation

	Redirection
		Version: 5.3.2
		Author: John Godley

	Simple Page Ordering
		Version: 2.4.1
		Author: Jake Goldman, 10up

	The Plus Addons for Elementor
		Version: 5.1.10
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.8
		Author: POSIMYTH

	UpdraftPlus - Backup/Restore
		Version: 2.22.19.25
		Author: UpdraftPlus.Com, DavidAnderson

	Widget Logic
		Version: 5.10.4
		Author: WPChef

	WP Activity Log
		Version: 4.4.2.1
		Author: WP White Security

	WPForms
		Version: 1.7.5.5
		Author: WPForms

	WPForms Form Abandonment
		Version: 1.6.0
		Author: WPForms

	WPForms Webhooks
		Version: 1.2.0
		Author: WPForms

	WPForms Zapier
		Version: 1.3.0
		Author: WPForms

	WP Mail SMTP
		Version: 3.5.1
		Author: WPForms

	WP Super Cache
		Version: 1.8
		Author: Automattic

	Yoast SEO
		Version: 19.6.1
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Inactive
	Scroll Snap: Active by default

== Log ==
	
JS: showing 20 of 40JS: 2022-09-05 09:11:35 [error X 5][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c17067widgetsticky\": not an object 
JS: 2022-09-05 10:05:14 [error X 1][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c50558widgetsticky\": not an object 
JS: 2022-09-05 10:05:21 [error X 1][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c51337widgetsticky\": not an object 
JS: 2022-09-05 10:11:00 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c129widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c136widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c160widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 2][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c181widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c188widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c233widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 2][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c257widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c263widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 2][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c284widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 2][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c39widgetsticky\' 
JS: 2022-09-05 10:11:00 [error X 2][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c51widgetsticky\' 
JS: 2022-09-05 10:11:01 [error X 3][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40879] Cannot create property \'guid\' on string \'c520widgetsticky\' 
JS: 2022-09-05 10:15:21 [error X 1][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c98sectionsticky\": not an object 
JS: 2022-09-05 10:15:21 [error X 1][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c100widgetsticky\": not an object 
JS: 2022-09-05 10:15:21 [error X 1][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c103widgetsticky\": not an object 
JS: 2022-09-05 10:15:21 [error X 1][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c106widgetsticky\": not an object 
JS: 2022-09-05 10:34:47 [error X 47][https://eloomi.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:40864] can\'t assign to property \"guid\" on \"c65404widgetsticky\": not an object 

PHP: showing 2 of 2PHP: 2022-09-05 10:51:57 [notice X 1207][/var/www/vhosts/eloomi.com/web/site-new/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-05 12:09:45 [notice X 2][/var/www/vhosts/eloomi.com/web/site-new/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/eloomi.com/web/site-new/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /var/www/vhosts/eloomi.com/web/site-new/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/vhosts/eloomi.com/web/site-new/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/vhosts/eloomi.com/web/site-new/wp-content/plugins/theplus_elementor_addon/modules/theplus-integration.php(93): Elementor\Controls_Manager -> register_control()
',
)]

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	The Plus Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
@AndreasH08 can you paste here the custom css you are trying to add?

**Comment by AndreasH08** [comment]
@rami-elementor, this is some custom CSS I put into the section's custom CSS tab, and it's supposed to activate on the images in the section:

@media only screen and (max-width 767px) and (min-width: 500px) {
    selector img {
        height: auto !important;
        width: 50% !important;
    }
    
    selector #g2image img {
        height: auto !important;
        width: 50%;
    }
    
}
