### ISSUE TITLE
🐞 Bug report: Navigation (Dropdown) on Mobile  + Search Form Full Screen Isn't Working Properly 

### ISSUE THREAD

**Issue by mkiii333** [elementor/elementor#19705]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Another update, another bug! It feels like this is becoming a "new normal."

We're using Flex containers.

After recent updates, the drop-down menu (navigation) isn't working correctly on mobile (it feels like something is messed up with the z-index or priorities of how each element should be shown).

Another website uses Elementor version 3.6.8 and Elementor Pro Version 3.6.5 and does not have this issue. However, after updating to the recent Elementor version, this bug also occurs on that website.

https://monosnap.com/file/6YcXGZcHd3P3Pa38d4PtzPnNoOiW4r

In the live version of the website, it's even worse:
https://monosnap.com/file/UHXXIuEyeVWPdKarfrObazuQEoblHU

Another bug: Search Form Full Screen Isn't Working Properly 

I feel this is somehow related to the previous issue.

When you click on the search form (Desktop & Mobile), the full screen with search input doesn't appear.

https://monosnap.com/file/4QK0ilM89ebnm0gGmKaPeEDpU4Jz3h

It feels that each update generates a bunch of bugs. We stopped using the Sticky function (for the sidebar) because it's glitching as well... We're tired of this hit-or-miss approach with each update.

### Steps to reproduce

1. Use flex containers
2. Add navigation to a header, use drop-down hamburger, check mobile
3. Add search form widget and use full-screen skin.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Debian)
	MySQL version: mariadb.org binary distribution v10.6.3
	PHP Version: 8.1.8
	PHP Memory Limit: 1500M
	PHP Max Input Vars: 14900
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://.com
	Home URL: https://.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Max Memory limit: 1500M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.8.4
		Author: Activity Log Team

	Custom Post Type UI
		Version: 1.12.1
		Author: WebDevStudios

	Disable Emojis (GDPR friendly)
		Version: 1.7.4
		Author: Ryan Hellyer

	Elementor
		Version: 3.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.5
		Author: Elementor.com

	LuckyWP Table of Contents
		Version: 2.1.4
		Author: LuckyWP

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Ninja Tables
		Version: 4.2.3
		Author: WPManageNinja LLC

	Ninja Tables Pro
		Version: 4.1.5
		Author: WPManageNinja

	NitroPack
		Version: 1.5.15
		Author: NitroPack LLC

	Pretty Links Beginner Edition
		Version: 3.2.5
		Author: Pretty Links

	Rank Math SEO
		Version: 1.0.96
		Author: Rank Math

	Redirection
		Version: 5.3.2
		Author: John Godley

	ShortPixel Image Optimizer
		Version: 5.0.9
		Author: ShortPixel

	User Role Editor Pro
		Version: 4.63
		Author: Vladimir Garagulia

	WeCanTrack
		Version: 1.4.1
		Author: wecantrack.com

	Wordfence Security
		Version: 7.6.0
		Author: Wordfence

	wpDataTables
		Version: 4.5
		Author: TMS-Plugins

	WP External Links
		Version: 2.55
		Author: WebFactory Ltd

	WPFront Scroll Top
		Version: 2.0.7.08086
		Author: Syam Mohan

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.15.2
		Author: Rhubarb Group

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Active
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 292022-08-29 12:03:22 [info] elementor::elementor_updater Started 
2022-08-29 12:03:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-29 12:03:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-29 12:03:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-29 12:03:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-30 07:20:42 [info] elementor-pro::elementor_pro_updater Started 
2022-08-30 07:20:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-30 07:20:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-30 07:20:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-08-30 07:20:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-03 16:05:52 [info] elementor-pro::elementor_pro_updater Started 
2022-09-03 16:05:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-03 16:05:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-03 16:05:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-03 16:05:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-03 16:05:52 [info] elementor::elementor_updater Started 
2022-09-03 16:05:52 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-03 16:05:52 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-03 16:05:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-03 16:05:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Make Column Clickable Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by mcrowell** [comment]
This sounds like the existing #19333 bug.

Check out that issue for my temp CSS fix.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!
