### ISSUE TITLE
🐞 Bug report: Notes are displayed, even if disabled. [ED-8246]

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19701]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In settings, I [disable](https://prnt.sc/CIVASdnoRTcV) the note feature. But it is still displayed : https://prnt.sc/bPOvIK_nHdPo

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by black-eye** [comment]
+1 Same here. 

Features which have been disabled should be disabled completely, including all the promo stuff. 

The other example is "Default to New Theme Builder" - when I have disabled it, I've done this on purpose and willingly - so I don't want a giant notification banner reminding me to try it again and again, when I open an "old" Theme Builder page.

**Comment by 79ho3ein** [comment]
+1
page transitions as well

**Comment by arielk** [comment]
@Michaelgimii Can you please click the button and take a screenshot? I want to see what kind of button appears

**Comment by black-eye** [comment]
@arielk 
I think @Michaelgimii meant this button in the editor menu:

![obrazek](https://user-images.githubusercontent.com/5634870/190929998-bf892b53-e715-4d6f-a0d3-8974fb5a522a.png)

**Comment by arielk** [comment]
Fixed by https://github.com/elementor/elementor/pull/19138 (v3.8)
