### ISSUE TITLE
Cannot install Elementor Pro Plugin

### ISSUE THREAD

**Issue by pig1831** [elementor/elementor#19713]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am trying to upgrade Elementor on our website to Elementor Pro. I have already purchased a subscription however, when I to to install the Elementor Pro Plugin it does not work. It just spins. When I go to another test website I have and try to install Elementor Pro using the zip file it works, but it just does not work for the website I want it to. 

### Steps to reproduce

1) I go to the "Add Plugins" page 
2) I click on "Upload Plugin"
3) I select the file I downloaded for Elementor Pro, and select. 
4) The file selects but does not upload as a proper install. 

### Isolating the problem
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://labryofertility.com
	Home URL: https://labryofertility.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Taipei
	Admin Email: pig1831@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.8.0-dev4
		Author: Elementor.com

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

== Elements Usage ==
	
	container : 0
		heading : 4
		icon-list : 4
		social-icons : 1
	page : 11
		button : 3
		divider : 5
		google_maps : 2
		heading : 28
		icon : 1
		icon-box : 9
		image : 5
		menu-anchor : 2
		shortcode : 1
		social-icons : 5
		spacer : 2
		text-editor : 12
	section : 1
		heading : 4
		icon-list : 4
	wp-page : 12
		accordion : 1
		button : 7
		divider : 19
		google_maps : 1
		heading : 45
		icon : 10
		icon-box : 1
		image : 54
		image-box : 6
		menu-anchor : 11
		social-icons : 12
		spacer : 38
		text-editor : 60

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
Log: showing 20 of 332022-07-28 16:33:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.8',
)]
2022-07-28 17:06:57 [info] elementor::elementor_updater Started 
2022-07-28 17:06:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-28 17:06:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-28 17:06:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.8',
)]
2022-08-31 21:16:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.3',
)]
2022-08-31 21:27:00 [info] elementor::elementor_updater Started 
2022-08-31 21:27:00 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-31 21:27:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-31 21:27:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.3',
)]
2022-09-06 02:54:10 [info] elementor::elementor_updater Started 
2022-09-06 02:54:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-06 02:54:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-06 02:54:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-06 02:54:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-06 03:15:18 [info] elementor::elementor_updater Started 
2022-09-06 03:15:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-06 03:15:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-06 03:15:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.8.0-dev4',
)]
2022-09-06 03:15:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.8.0-dev4',
)]

PHP: showing 9 of 9PHP: 2022-04-07 08:13:21 [notice X 7526][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-20 22:27:56 [notice X 4][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-24 09:35:36 [warning X 45][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::76] Declaration of ElementorPro\Core\Utils\Collection::unique() should be compatible with Elementor\Core\Utils\Collection::unique($keys = NULL) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-18 11:31:10 [notice X 35][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php(824): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-18 11:31:10 [notice X 35][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-18 11:31:10 [notice X 34][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(72): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-18 11:31:10 [notice X 35][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/forms/module.php(73): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-02 01:44:16 [error X 49][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::47] Uncaught ReflectionException: Method get_site_editor_type does not exist in /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:47
Stack trace:
#0 /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(47): ReflectionClass->getMethod('get_site_editor...')
#1 /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(128): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Mo [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 03:15:18 [notice X 1][/home/customer/www/labryofertility.com/public_html/wp-content/plugins/elementor/core/base/document.php::1467] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-06-30 18:18:57 [error X 11][https://labryofertility.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:450542] T.getContainer is not a function 

== Elementor - Compatibility Tag ==
	

				
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rami-elementor** [comment]
Hi @pig1831 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
