### ISSUE TITLE
🐞 Bug report: Decrease/increase buttons in numeric fields have disappeared.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19711]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In numeric fields, the decrease/increase button is not displayed. https://prnt.sc/uY4jWMXCDegP

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Chrome browser, Windows 10

**Comment by arielk** [comment]
It seems that all your numeric fields do not have these arrows, it's related to the browser and not to our side.

Thanks
