### ISSUE TITLE
Не логические значения 

### ISSUE THREAD

**Issue by Schweddavid** [elementor/elementor#19717]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

при активации елементр эксперимент, есть недоработка, в меню настройки сайта, при переходе во вкладку общие настройки контейнера, ширина указана 1200 в пикселях, при работе с самим элементорм и наполнением страницы контентом, ширина указана в процентах 100%, сто на 3 не делиться в ровном соотношении, следовательно при вложении трех фотографий они не выравниваются а начинаю плавать в разные стороны.  

### Steps to reproduce

[гит  хад.docx](https://github.com/elementor/elementor/files/9494860/default.docx)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

 
[гит  хад2.docx](https://github.com/elementor/elementor/files/9494886/2.docx)

**Comment by rami-elementor** [comment]
@Schweddavid please reopen in English.
