### ISSUE TITLE
🚀 Feature Request: Ability to choose desired code format in custom code

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19720]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Currently, if we use custom code, for example if we want to write css code, we must first type the css tag. JavaScript is the same.
But it would be great if you add a feature so that we can determine what code we are writing before writing the desired code. For example, if we choose css, we don't need to open the <style> tag first. Elementor adds this to the page automatically. (**Of course, tags created by Elementor do not need to be visible. We can directly start writing code)**
One of the important advantages that this feature will have is that users can see what programming languages ​​the custom code supports by using the code format selection section.
If you add this feature, in the code format selection section, add the default section as well. In fact, the default part works as it does now. We can use several different codes (css or js, etc.) in a custom code page at the same time.

### Describe the solution you'd like

![custom code](https://user-images.githubusercontent.com/88034902/188609112-820de829-3dc3-4094-93d4-b3344abaa663.png)

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

After review, we have decided not to add this to our roadmap. Writing  additional `<script>` and `<style>` tags is not a so hard. In addition, the current functionality gives you more flexibility, you can set your own attributes on the tags.

Regards,
