### ISSUE TITLE
🚀 Feature Request: em Units For Adaptive Letter Spacing. Maybe clamp option on font sizing too?

### ISSUE THREAD

**Issue by tekonemedia** [elementor/elementor#19726]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Fluid typography is common practice in today's web designs. Fixed (px unit) font spacing is trash in scenarios that require fluid sized typography, such as vw and % ( sometimes clamp ) font sizing. with such varying screen sizes/resolutions now a day's, we find ourselves resorting to these units for font sizing quite often. Especially with headings/subheadings!! Currently, we have to use custom CSS to add em-based letter spacing any time we want to add letter spacing to vw and % sized text, as fixed unit letter spacing on vw and % font sizing is absolute trash. We have em units for adaptive line height and word spacing, but not letter spacing!!? em letter spacing solves this instantly and would be a very simple implementation.

Also, ( while not as important as the previous )... Font size clamping for vw and % font units would be an awesome feature for building out fluid typography. I believe CSS clamp has great browser support now aday's as well.

### Describe the solution you'd like

An em unit option for letter spacing within elementor's font styling tab. 

Clamp ( min - max ) font size option for vw and % based font sizing would be awesome too.

**Comment by rami-elementor** [comment]
Just to be clear,

You are talking only about "**Typography**" group-control:

![tls](https://user-images.githubusercontent.com/92088692/188834539-ddea82f9-eaec-49fb-8906-0abc559f9b8d.png)

You are asking:

1. Add `em`/`vw`/`%` units to "Letter Spacing".
2. Add the ability to set `clamp()` on "Font Size" (maybe using dynamic-tags as it requires several parameters).

**Comment by tekonemedia** [comment]
Yes I'm talking about the typography group control panel.

1. Only em and px units added to letter spacing (no need for vw or % units for letter spacing I don't think)

2. Correct. Maybe just simple "min font size" and "max font size" number field boxes that appear under the current "size" field when vw/% is selected. This would simplify it for people who don't know css clamp (kind of like the "max width" control currently on the image widget styling options).

**Comment by rami-elementor** [comment]
Hi @tekonemedia ,

The first request was implemented in #19745.

The result:

![tls-2](https://user-images.githubusercontent.com/92088692/189122755-fff67ff1-f1e8-425c-97c8-5c53e04e5608.png)

**Comment by rami-elementor** [comment]
Our policy is to create single issue/request per ticket. So I am going to close this ticket and label it as a resolved issue.

Regarding the CSS clamp(), it's not in our current roadmap. You can create a separate feature request with detailed information, but we are not going to do that any time soon. Our road map has several other features with high demand like containers the the loop builder.
