### ISSUE TITLE
🚀 Feature Request: Default unit of custom width in container

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19743]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In container, when we enter a custom width for a widget, in desktop, the default unit is %. https://prnt.sc/iPBcnB8I68pB
But in tablet and mobile mode, the default unit is changed to **px**. Is there a specific reason for that?

### Describe the solution you'd like

For tablets and mobile phones, set the default unit to percentage. Just like desktop.

**Comment by arielk** [comment]
Hi @Michaelgimii 

For this option you can use "Save as Default" to keep what behavior you want.

Thanks
