### ISSUE TITLE
Updated to ver. 3.7.4, cant run update data, get critical error

### ISSUE THREAD

**Issue by Simonsbs** [elementor/elementor#19742]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When i try to run the update data, i get a critical error and thrown back

### Steps to reproduce

1. click button
2. fail

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 8.1.10
	PHP Memory Limit: 2000M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://techlab.co.il
	Home URL: https://techlab.co.il
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 100000M
	Max Memory limit: 20000M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: Simon@TechLab.co.il
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Crocoblock
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Shipment Tracking for WooCommerce
		Version: 3.4.7
		Author: zorem

	ATUM Inventory Management for WooCommerce
		Version: 1.9.21
		Author: Stock Management Labs™

	ATUM Multi-Inventory
		Version: 1.7.5
		Author: Stock Management Labs™

	Bit Payment Gateway for WooCommerce
		Version: 2.0
		Author: Zorem

	Blog Designer Pack
		Version: 3.1
		Author: InfornWeb

	CardCom Payment Gateway
		Version: 3.4.7.9
		Author: CardCom LTD

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Cloudflare
		Version: 4.11.0
		Author: Cloudflare, Inc.

	CoDesigner
		Version: 3.7
		Author: Codexpert

	CoDesigner Pro
		Version: 3.7
		Author: Codexpert

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Crocoblock Wizard
		Version: 1.2.5
		Author: Crocoblock

	Custom Payment Gateways for WooCommerce
		Version: 1.6.6
		Author: Imaginate Solutions

	Disable Comments
		Version: 2.4.1
		Author: WPDeveloper

	Dynamic Featured Image
		Version: 3.7.0
		Author: Ankit Pokhrel

	Dynamic Menu Pro
		Version: 4.5.8
		Author: AWESOME TOGI

	e-addons for Elementor
		Version: 3.1.3
		Author: Nerds Farm

	Elementor
		Version: 3.7.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.5
		Author: Elementor.com

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Envato Market
		Version: 2.0.7
		Author: Envato

	Facebook for WooCommerce
		Version: 2.6.22
		Author: Facebook

	Force Regenerate Thumbnails
		Version: 2.0.6
		Author: Pedro Elsner

	FraudLabs Pro for WooCommerce
		Version: 2.17.2
		Author: FraudLabs Pro

	Google Listings and Ads
		Version: 2.1.1
		Author: WooCommerce

	Gutenberg
		Version: 14.0.2
		Author: Gutenberg Team

	Head & Footer Code
		Version: 1.3.0
		Author: Aleksandar Urošević

	Health Check & Troubleshooting
		Version: 1.4.5
		Author: The WordPress.org community

	JetBlocks For Elementor
		Version: 1.3.3
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.3.1
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetEngine
		Version: 3.0.3.1
		Author: Crocoblock

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	Jetpack
		Version: 11.3
		Author: Automattic

	JetPopup
		Version: 1.5.6
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.6
		Author: Crocoblock

	JetSearch
		Version: 3.0.2
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.13
		Author: Crocoblock

	JetStyleManager
		Version: 1.3.5
		Author: Crocoblock

	JetTricks
		Version: 1.4.2
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.0.3
		Author: Crocoblock

	Lara's Google Analytics
		Version: 3.3.4
		Author: XtraOrbit Web Development SRL

	LayerSlider
		Version: 7.3.0
		Author: Kreatura Media

	Mailchimp for WooCommerce
		Version: 2.7.3
		Author: Mailchimp

	Max Mega Menu
		Version: 2.9.8
		Author: megamenu.com

	MC4WP: Mailchimp for WordPress
		Version: 4.8.8
		Author: ibericode

	NextMove Lite - Thank You Page for WooCommerce
		Version: 2.15.1
		Author: XLPlugins

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Payment Gateway Based Fees and Discounts for WooCommerce
		Version: 2.7.0
		Author: Tyche Softwares

	Pixel Manager for WooCommerce
		Version: 1.20.2
		Author: SweetCode

	reCaptcha for WooCommerce
		Version: 2.37
		Author: I Thirteen Web Solution

	Regenerate Thumbnails Advanced
		Version: 2.4.0
		Author: ShortPixel

	Relevanssi
		Version: 4.17.1
		Author: Mikko Saari

	Ship description for WooCommerce
		Version: 1.09
		Author: Dovi42

	Ship to a different address unchecked
		Version: 1.0
		Author: RoMedia Design

	Slider Revolution
		Version: 6.5.24
		Author: ThemePunch

	Store Manager Connector
		Version: 1.1.1
		Author: eMagicOne

	Storewide Sale
		Version: 1.0.3
		Author: HighAddons

	ThemeSky
		Version: 1.3.4
		Author: ThemeSky Team

	Widget Context
		Version: 1.3.2
		Author: Kaspars Dambis

	WooCommerce
		Version: 6.8.2
		Author: Automattic

	WooCommerce Blocks
		Version: 8.4.0
		Author: Automattic

	WooCommerce Google Analytics Pro
		Version: 1.12.0
		Author: SkyVerge

	WooCommerce Google Product Feed
		Version: 10.7.5
		Author: Ademti Software Ltd.

	WooCommerce PayPal Payments
		Version: 1.9.3
		Author: WooCommerce

	WooCommerce Upay Payment
		Version: 1.2.5
		Author: EOI

	WooCommerce Zapier
		Version: 2.3.0
		Author: OM4 Software

	Wordfence Security
		Version: 7.6.1
		Author: Wordfence

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

	WP Activity Log
		Version: 4.4.2.1
		Author: WP White Security

	WP Activity Log for WooCommerce
		Version: 1.4.4
		Author: WP White Security

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

	WP Maintenance Mode & Coming Soon
		Version: 2.5.0
		Author: Themeisle

	WP Paint - WordPress Image Editor
		Version: 0.5.3
		Author: ZetaMatic

	WP Search Insights - Privacy-Friendly Search Analytics
		Version: 1.3.8
		Author: Mark Wolters

	WP Sheet Editor - Post Types (Premium)
		Version: 2.24.19
		Author: WP Sheet Editor

	WP Sheet Editor - WooCommerce Orders Pro
		Version: 1.2.29
		Author: WP Sheet Editor

	WP Sheet Editor - WooCommerce Products (Premium)
		Version: 1.7.19
		Author: WP Sheet Editor

	YITH WooCommerce Compare
		Version: 2.18.0
		Author: YITH

	YITH WooCommerce Wishlist
		Version: 3.12.0
		Author: YITH

	Yoast SEO
		Version: 19.6.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== שימוש באלמנטים ==
	
	page : 2
		jet-woo-builder-archive-add-to-cart : 2
		jet-woo-builder-archive-product-price : 1
		jet-woo-builder-archive-product-thumbnail : 2
		jet-woo-builder-archive-product-title : 2
		product-price : 2
		spacer : 2
	wp-post : 5
		text-editor : 5
	wp-page : 8
		cart-items : 1
		heading : 3
		image : 6
		image-box : 6
		shortcode : 2
		spacer : 1
		text-editor : 2
	wl-email : 0
		accordion : 1
		heading : 2
		icon-box : 3
		image-box : 4
		jet-ajax-search : 1
		jet-woo-product-gallery-modern : 1
		menu-cart : 1
		product-stock : 1
		related-products-classic : 1
		shortcode : 1
		social-icons : 1
		text-editor : 4
	jet-woo-builder-shop : 0
		divider : 1
		jet-woo-builder-products-description : 1
		jet-woo-builder-products-loop : 1
		jet-woo-builder-products-ordering : 1
		jet-woo-builder-products-page-title : 1
		jet-woo-builder-products-pagination : 1
		jet-woo-builder-products-result-count : 1
	jet-woo-builder-archive : 0
		jet-woo-builder-archive-add-to-cart : 2
		jet-woo-builder-archive-cats : 1
		jet-woo-builder-archive-product-excerpt : 1
		jet-woo-builder-archive-product-price : 1
		jet-woo-builder-archive-product-rating : 1
		jet-woo-builder-archive-product-thumbnail : 2
		jet-woo-builder-archive-product-title : 2
		jet-woo-builder-archive-tags : 1
		product-price : 1
		spacer : 1

== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: פעיל
	טעינת נכסים משופרת: פעיל
	טעינת CSS משופרת: פעיל
	Inline Font Icons: פעיל
	שיפורי נגישות: פעיל
	Additional Custom Breakpoints: פעיל
	Import Export Template Kit: פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	Flexbox Container: לא פעיל כברירת מחדל
	ברירת מחדל לממשק החדש של בונה התבנית: פעיל כברירת מחדל
	עיצוב כותרת עליונה ותחתונה: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	סרגל אדמין עליון: פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	Notes: פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	קפיצת גלילה: פעיל כברירת מחדל

== יומן שינויים ==
	
PHP: showing 4 of 4PHP: 2022-08-22 18:03:09 [notice X 84706][/home/techlabcoil/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/techlabcoil/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/techlabcoil/public_html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/techlabcoil/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/techlabcoil/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/techlabcoil/public_html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/techlabcoil/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/techlabcoil/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-08-25 11:35:48 [notice X 10][/home/techlabcoil/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-31 11:27:53 [notice X 2832][/home/techlabcoil/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::528] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-01 10:48:54 [notice X 5][/home/techlabcoil/public_html/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 362022-09-01 10:37:42 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-01 10:48:40 [info] elementor-pro::elementor_pro_updater Started 
2022-09-01 10:48:40 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-09-01 10:48:40 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-09-01 10:48:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-01 10:48:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-01 10:48:56 [info] elementor::elementor_updater Started 
2022-09-01 10:48:56 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-01 11:42:58 [info] elementor::elementor_updater Started 
2022-09-01 11:42:58 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-04 11:31:57 [info] elementor::elementor_updater Started 
2022-09-04 11:31:57 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-06 12:09:41 [info] elementor::elementor_updater Started 
2022-09-06 12:09:41 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-07 14:57:34 [info] elementor::elementor_updater Started 
2022-09-07 14:57:34 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-08 11:48:36 [info] elementor::elementor_updater Started 
2022-09-08 11:48:36 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-09-08 13:31:28 [info] elementor::elementor_updater Started 
2022-09-08 13:31:28 [info] אלמנטור/Upgrades - _on_each_version Start  

JS: showing 2 of 2JS: 2022-09-01 09:48:29 [error X 1][https://techlab.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view12768\") has already been destroyed and cannot be used. 
JS: 2022-09-01 09:48:36 [error X 1][https://techlab.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view12800\") has already been destroyed and cannot be used. 

== אלמנטור - Compatibility Tag ==
	
	e-addons for Elementor: תאימות לא הוגדרה
	Elementor Pro: תאימות לא הוגדרה
	JetBlocks For Elementor: תאימות לא הוגדרה
	JetBlog For Elementor: תאימות לא הוגדרה
	JetElements For Elementor: תאימות לא הוגדרה
	JetWooBuilder For Elementor: תאימות לא הוגדרה

== אלמנטור פרו - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @Simonsbs ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
