### ISSUE TITLE
the elementor is not working on my website kindly take a look to my website

### ISSUE THREAD

**Issue by miltcline** [elementor/elementor#19759]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

i am facing a problem on my website elementor pro is not working on my website if i try to edit or create a new page elementor start loading i am unable to edit and work with elementor . kindly resolve my problem . [thanks[](https://www.miltonwcline.com/wp-admin/post.php?post=2553&action=elementor)

### Steps to reproduce

check my website . resolve an issue why elementor not working . how do i get help to resolve this problem[https://www.miltonwcline.com/wp-admin/post.php?post=2553&action=elementor](https://www.miltonwcline.com/wp-admin/post.php?post=2553&action=elementor)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>
<div style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23 |  
PHP Version: | 7.4.28 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 516M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div></div><h3 style="display: block; font-weight: 600; color: rgb(29, 35, 39); font-size: 1.3em; margin: 1em 0px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Copy &amp; Paste Info</h3><div id="elementor-system-info-raw" style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><label id="elementor-system-info-raw-code-label" for="elementor-system-info-raw-code" style="cursor: pointer; vertical-align: middle; padding: 5px; display: block;">You can copy the below info as simple text with Ctrl+C / Ctrl+V:</label></div><br class="Apple-interchange-newline">
</body>
</html>Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23	
PHP Version:	7.4.28	
PHP Memory Limit:	512M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	516M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.0.2	
Site URL:	https://www.miltonwcline.com	
Home URL:	https://www.miltonwcline.com	
WP Multisite:	No	
Max Upload Size:	512 MB	
Memory limit:	512M	
Max Memory limit:	512M	
Permalink Structure:	/%postname%/	
Language:	en-US	
Timezone:	0	
Admin Email:	studio@3cco.com	
Debug Mode:	Inactive	
Theme		
Name:	Astra	
Version:	3.9.2	
Author:	Brainstorm Force	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36	
Active Plugins		
[Contact Form 7](https://contactform7.com/) - 5.6.3	By [Takayuki Miyoshi](https://ideasilo.wordpress.com/)	
[Cool Timeline Pro](http://coolplugins.net/) - 4.2	By [Cool Plugins](http://coolplugins.net/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.8.0-dev4	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Addons & Templates - Sizzify Lite](https://themeisle.com/) - 1.3.2	By [ThemeIsle](https://themeisle.com/)	
[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)	
[Elementor Blocks for Gutenberg](https://elementor.com/?utm_source=block-builder&utm_campaign=plugin-uri&utm_medium=wp-dash) - 1.0.1	By [Elementor.com](https://elementor.com/?utm_source=block-builder&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Header & Footer Builder](https://github.com/Nikschavan/header-footer-elementor) - 1.6.13	By [Brainstorm Force, Nikhil Chavan](https://www.brainstormforce.com/)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.7.5	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
Envato Elements - 2.0.11	By [Envato](https://elements.envato.com/extensions/wordpress/?utm_source=extensions&utm_medium=referral&utm_campaign=elements_extensions_wpplugins)	
[Google Analytics for WordPress by MonsterInsights](https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=pluginurl&utm_content=7%2E0%2E0) - 8.8.2	By [MonsterInsights](https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=authoruri&utm_content=7%2E0%2E0)	
[MC4WP: Mailchimp for WordPress](https://www.mc4wp.com/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-page) - 4.8.8	By [ibericode](https://ibericode.com/)	
[NavMenu Addon For Elementor](https://themeisle.com/) - 1.1.6	By [ThemeIsle](https://themeisle.com/)	
[One Click Demo Import](https://wordpress.org/plugins/one-click-demo-import/) - 3.1.2	By [OCDI](https://ocdi.com/)	
[OptinMonster](https://optinmonster.com/) - 2.9.0	By [OptinMonster Popup Builder Team](https://optinmonster.com/)	
[Orbit Fox Companion](https://orbitfox.com/) - 2.10.17	By [Themeisle](https://orbitfox.com/)	
[Premium Addons for Elementor](https://premiumaddons.com/) - 4.9.32	By [Leap13](https://leap13.com/)	
[Prevent Direct Access](https://preventdirectaccess.com/) - 2.8.2	By [BWPS](https://preventdirectaccess.com/)	
[s2Member Framework](http://s2member.com/) - 220809	By [WP Sharks](http://s2member.com/)	
[s2Member Pro](https://s2member.com/) - 220421	By [WP Sharks](https://s2member.com/)	
[Sticky Header Effects for Elementor](https://stickyheadereffects.com/) - 1.5.3	By [Rwattner](https://stickyheadereffects.com/)	
[TrustPulse API](https://trustpulse.com/) - 1.0.6		
[UpdraftPlus - Backup/Restore](https://updraftplus.com/) - 1.22.20	By [UpdraftPlus.Com, DavidAnderson](https://updraftplus.com/)	
[Wordfence Security](http://www.wordfence.com/) - 7.6.1	By [Wordfence](http://www.wordfence.com/)	
[WPForms Lite](https://wpforms.com/) - 1.7.6	By [WPForms](https://wpforms.com/)	
Must-Use Plugins		
Endurance Browser Cache - 0.4	By [Mike Hansen](https://www.mikehansen.me/)	
Endurance Page Cache - 2.2	By [Mike Hansen](https://www.mikehansen.me/)	
Endurance PHP Edge - 0.2	By [Mike Hansen](https://www.mikehansen.me/)	
SSO - 0.4	By Garth Mortensen, Mike Hansen	
Elementor Experiments		
Optimized DOM Output: 	Active
Improved Asset Loading: 	Active
Improved CSS Loading: 	Active
Inline Font Icons: 	Active
Accessibility Improvements: 	Active
Additional Custom Breakpoints: 	Active
Import Export Website Kit: 	Active
Hide native WordPress widgets from search results: 	Active
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Active
Default to New Theme Builder: 	Active by default
Landing Pages: 	Active
Color Sampler: 	Active
Favorite Widgets: 	Active
Admin Top Bar: 	Active
Page Transitions: 	Active by default
Notes: 	Active by default
Form Submissions: 	Active by default
Scroll Snap: 	Active by default
Log[Clear Log](https://www.miltonwcline.com/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=df4fed5d1f#elementor-clear-log)		
Log: showing 20 of 34
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-09-07 19:04:25 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-09-07 19:04:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.7.5',
)]
2022-09-07 19:04:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.7.5',
)]
2022-09-08 15:13:38 [info] elementor::elementor_updater Started 
2022-09-08 15:13:38 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-08 15:13:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-08 15:13:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.8.0-dev4',
)]
2022-09-08 15:13:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.8.0-dev4',
)]
PHP: showing 4 of 4
PHP: 2022-09-03 06:00:59 [notice X 1][/home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-08 12:39:20 [error X 10][/home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php::895] Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php:895
Stack trace:
#0 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php(153): ThemeIsle\ElementorExtraWidgets\Posts_Grid->grid_title_style_section()
#1 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/base/controls-stack.php(2282): ThemeIsle\ElementorExtraWidgets\Posts_Grid->_register_controls()
#2 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#3 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#4 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elemen [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-08 14:55:14 [notice X 2][/home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/managers/image.php::36] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-08 15:22:27 [error X 4][/home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php::895] Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php:895
Stack trace:
#0 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php(153): ThemeIsle\ElementorExtraWidgets\Posts_Grid->grid_title_style_section()
#1 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/base/controls-stack.php(2326): ThemeIsle\ElementorExtraWidgets\Posts_Grid->_register_controls()
#2 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#3 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#4 /home4/dreamser/public_html/miltonwcline/wp-content/plugins/elemen [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
JS: showing 4 of 4
JS: 2022-09-08 11:58:46 [error X 24][https://www.miltonwcline.com/wp-content/plugins/navmenu-addon-for-elementor/assets/js/frontend.min.js?ver=1.1.6:408:5] this.el is null 
JS: 2022-09-09 00:38:07 [error X 11][https://www.miltonwcline.com/wp-content/plugins/navmenu-addon-for-elementor/assets/js/frontend.min.js?ver=1.1.6:408:37] Cannot read properties of null (reading \'querySelector\') 
JS: 2022-09-09 00:38:45 [error X 14][https://www.miltonwcline.com/wp-content/plugins/navmenu-addon-for-elementor/assets/js/editor.min.js?ver=1.1.6:210:13] elementorSecondaryScreenReaderText is not defined 
JS: 2022-09-09 03:13:55 [error X 5][https://www.miltonwcline.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.7.5:2:19333] this.$element.sticky is not a function 
Elementor - Compatibility Tag		
 Elementor Addons & Templates - Sizzify Lite 	 Compatibility not specified 
 Elementor Header & Footer Builder 	 Incompatible 
 Elementor Pro 	 Incompatible 
 Envato Elements 	 Incompatible 
 NavMenu Addon For Elementor 	 Compatibility not specified 
 Premium Addons for Elementor 	 Incompatible 
 Sticky Header Effects for Elementor 	 Compatibility not specified 
Elementor Pro - Compatibility Tag		
 Elementor Header & Footer Builder 	 Compatible 
 Envato Elements 	 Incompatible 
 Premium Addons for Elementor 	 Compatible 
Copy & Paste Info
You can copy the below info as simple text with Ctrl+C / Ctrl+V:

**Comment by arielk** [comment]
In order for us to look into this matter, please contact our support team via your account, with complete login information to access your website, and our support team will try to assist.

**Comment by miltcline** [comment]
here is log in for www.miltonwcline.com
https://www.miltonwcline.com/wp-login.php?loggedout=true&wp_lang=en_US
dreamser
NwUdH$(5h#t)ZJI)
I have developer helping me and her name is Ammara and email is
***@***.*** please cc her with replies and requests.
Thankyou
Jeff Cline
***@***.***

**Comment by miltcline** [comment]
Why closed, need help please reply

**Comment by miltcline** [comment]
nothing has been resolved and this shows closed . I need to have someone
find out why elementor does not recognize license and allow updates for pro
3.8

**Comment by rami-elementor** [comment]
Hi @miltcline ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by miltcline** [comment]
we still facing elementor issue nothis is to be resloved

**Comment by miltcline** [comment]
we are still facing elementor issue nothing is to be resolved by elementor or github

**Comment by Abhishek-Yesankar** [comment]
Have you tried contacting elementor support
