### ISSUE TITLE
warnign sign

### ISSUE THREAD

**Issue by juanfonsek** [elementor/elementor#19750]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

warning sign persistently showing on slider

### Steps to reproduce

open the website, scrooling the slider

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home1/central/public_html/interlabcorp.com/wp-includes/functions.php on line 5379

Deprecated: Function Elementor\Controls_Stack::_register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home1/central/public_html/interlabcorp.com/wp-includes/functions.php on line 5379

**Comment by rami-elementor** [comment]
See similar issues:

https://github.com/elementor/elementor/issues?q=is%3Aissue+_register_controls
