### ISSUE TITLE
🐞 Bug report: Yoast Premium and Elementor Conflict

### ISSUE THREAD

**Issue by bowmandesign** [elementor/elementor#19757]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Yoast Premium 18.9 and 19.2.1
conflict with
Elementor / Elementor Pro 3.6.8 to 3.7.4/3.7.5

### Steps to reproduce

Edit page with elementor click desired container to edit,

None of the Elementor tool options show up.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Yoast Premium 18.9 and 19.2.1
conflict with
Elementor / Elementor Pro 3.6.8 to 3.7.4/3.7.5

**Comment by swmaguirpi** [comment]
We appear to be having the same issue and have the same Yoast and Elementor versions. 

From some testing, it seems that some containers can still be edited. Might be a random effect, but only new ones or those that do not have a background set can still be edited. The rest (vast majority) look like the image below:
![image](https://user-images.githubusercontent.com/113198326/189394213-1276734b-0ebb-485d-a27c-1084c8a8913f.png)

**Comment by Nick776** [comment]
same here 

![2022-09-10_08h30_28](https://user-images.githubusercontent.com/43967959/189472408-a2c1edbe-258c-4fb0-bc7e-a236019e884b.png)

**Comment by Nick776** [comment]
@rami-elementor 

Rami you changed the title does that mean it's a problem that Elementor needs to fix or is it still a Yoast problem?

**Comment by PatrickKarl** [comment]
I got feedback from Yoast. The problem has occurred several times and will be fixed with the next update. Currently there is no workaround, but it should be fixed as soon as possible.

**Comment by Nick776** [comment]
@PatrickKarl thnx for this info Patrick.

**Comment by Nick776** [comment]
@PatrickKarl 

We are in contact with Yoast development team. They don't know that Yoast has communicated that they are trying to fix the error with the **next update.** Who are you in contact with?

**Comment by PatrickKarl** [comment]
@Nick776 The contact person was Adetola Adeniran. Support Engineer at Yoast.

**Comment by Nick776** [comment]
@PatrickKarl 

Ok, thank you. Then we got the same message.

**Comment by PatrickKarl** [comment]
@Nick776 As a little help for adjustments. Once you disable Yoast, you can edit the containers. Afterwards, don't forget to turn Yoast active again.

**Comment by Nick776** [comment]
@PatrickKarl 

Yeah, so we're working right now too. Thanks for the tip anyway. Easy was yesterday. 🤣

**Comment by ricardomecca** [comment]
I have the same problem!
Have news good notices?

**Comment by dlarmitage** [comment]
burned a half hour tracking this one down.  

Never expected it to be a Yoast issue!  The last plugin I tried.

**Comment by iamazik** [comment]
👋 we merged a PR https://github.com/Yoast/wordpress-seo/pull/19002 for it today and will fix in Yoast SEO v19.9.

**Comment by Nick776** [comment]
message from Yoast!

"...Hi Nico,

Thank you for your continued patience, and we hope you are doing great. You previously contacted us regarding the settings showing as blank and not shown within the Elementor editor when the Yoast SEO Premium or our other addon plugins are active (mostly when trying to access the sections on the flexbox containers).

This email is to inform you that our development team fixed this issue and the issue was closed. The bug fix will be rolled out within our next release. On average, plugin updates are released every two weeks, so it shouldn't be too long.

Let us know if there's anything else we can assist you with; we're happy to help..."
