### ISSUE TITLE
Toolset term custom image field not recognized on Elementor archives

### ISSUE THREAD

**Issue by ADAGEBF** [elementor/elementor#19761]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Toolset term custom image field is not recognized on Elementor archives.

### Steps to reproduce

1) Create a new Toolset term custom image field
2) Create a new Elementor Archive template
3) Add an image field and try to dynamically add the Toolset term custom image field in options

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

reproduced on several systems

**Comment by rami-elementor** [comment]
Hi @ADAGEBF ,

Please read this blog post - https://toolset.com/2022/06/whats-next-for-toolset/

Toolset pause the development of new features. Currently, we are not sure that we will continue to support a plugin whose developers stop supporting it.

We haven't made any decision yet, but as it stands right now, we won't be able to process your request.
