### ISSUE TITLE
Preview Width for loop builder

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19764]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

As you know, in Loop builder we can create a template and then display products or posts based on it. So, it would be great if we could control the width of the loop preview.

### Describe the solution you'd like

Like the jet engine plugin, add a preview width option in the page settings, so that we have much better control over the content when we are designing the loop template.

![loop](https://user-images.githubusercontent.com/88034902/189522260-1883d56e-c194-44a7-8c92-806bbf6a842b.png)

Because if the preview is full width, it won't be interesting.

**Comment by nicholaszein** [comment]
Hey @Michaelgimii !

This option is already available if you open the Loop Item within the Theme Builder. Here's what you need to do:

1. In your WordPress Dashboard, go to Templates (under Elementor) > **Theme Builder > Loop Item**, then create or edit an existing Loop Item;
2. After the Elementor Editor is loaded, click the **gear icon** ⚙️ in the bottom right corner of the Elementor Widget Panel to open the **Loop Item Settings**;
3. Under the **Preview Settings** there is a range slider to select the **Width**.  Just set your width there for Desktop, Tablet or Mobile.

![image](https://user-images.githubusercontent.com/113993460/191558670-5d927f14-2e52-42cd-8b79-53ddf183236a.png)

I hope this answers your request.

Best regards! 😉

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
