### ISSUE TITLE
Make loop item clickable for loop bilder

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19765]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you could add item clickable to the loop builder. Using this option, we can assign the link to the entire box of each loop item. The use of this option will be completely optional.

### Describe the solution you'd like

Please add Make loop item clickable feature like jet engine plugin.

![loop item clickable](https://user-images.githubusercontent.com/88034902/189522458-c90883db-e6f8-47ee-9927-32aa847c868b.png)

**Comment by arielk** [comment]
I'm closing this issue because it's not related to us, it's a feature built by a third party.

Thanks!

**Comment by Michaelgimii** [comment]
@arielk , I did not report a bug. I just wanted to request this feature for the loop builder that will be introduced in the future.

**Comment by arielk** [comment]
@Michaelgimii So please wait for the beta release (hopefully in the next few weeks) :)

**Comment by nicholaszein** [comment]
Hello there @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.0**! 🥳 

All you have to do is to set the wrapping Container's HTML tag of your Loop Item template to be an anchor. You can find out how to do it [here](https://elementor.com/help/how-to-add-html-tags-to-my-section-column/). Choose the option `a (link)`.

![image](https://user-images.githubusercontent.com/113993460/199271748-63289fcd-76bd-4647-badc-7d91db8be7db.png)


✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by jagadish-k** [comment]
I am using v3.11.0 and am trying to make the full loop item clickable and open the `Post URL`. But I do not see an option to set the section to `link`

**Comment by nicholaszein** [comment]
Hi @jagadish-k,

the option to add links is and will only be available for Containers. You can't add the same functionality to Sections and Columns, and we don't plan to add this feature to them.

Kind regards.
