### ISSUE TITLE
Post navigation loop

### ISSUE THREAD

**Issue by michaelbabic** [elementor/elementor#19772]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The posts navigation ends at the last post. 

### Describe the solution you'd like

It would be great if I'd have the option to toggle a navigation loop, so that after the last post you can get to the first one via the navigation.

**Comment by rami-elementor** [comment]
Hi @michaelbabic 

You can with the menu anchor widget - https://www.youtube.com/watch?v=nnOxYEtdZkQ

**Comment by michaelbabic** [comment]
Hej rami
Thank you, but that is not what I meant. The menu anchor has nothing to do with the post navigation widget.

I was talking about the post navigation widget on a single post.
