### ISSUE TITLE
Fatal Error: Elementor\Controls_Stack::sanitize_settings()

### ISSUE THREAD

**Issue by justinrclarke** [elementor/elementor#19784]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Our web host Flywheel brought up this error when investigating the reasoning behind a website running slow or not loading. 

They provided us with this error:
`NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /www/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1107 and defined in /www/wp-content/plugins/elementor/includes/base/controls-stack.php:2369`

### Steps to reproduce

Whenever updating/saving anything to do with Elementor.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Operating System: | Linux |  
-- | -- | --
Software: | Flywheel/5.1.0 |  
MySQL version: | (Google) v5.7.38 |  
PHP Version: | 7.4.30 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 300M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | There are some writing permissions issues with the following directories/files: 		 - WordPress root directory |  
Elementor Library: | Connected

Version: | 6.0.2 |  
-- | -- | --
Site URL: | REDACTED |  
Home URL: | REDACTED |  
WP Multisite: | No |  
Max Upload Size: | 300 MB |  
Memory limit: | 512M |  
Max Memory limit: | 512M |  
Permalink Structure: | /%postname%/ |  
Language: | en-US |  
Timezone: | America/Chicago |  
Admin Email: | REDACTED |  
Debug Mode: | Inactive

**Comment by rami-elementor** [comment]
Hi @justinrclarke ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,

**Comment by rami-elementor** [comment]
Your report is missing the following key information:

* **Steps to replicate** (If the issue can't be recreated on other sites, it's not an Elementor bug - use the support links)
* **System info** (Elementor sys info)

Please feel free to open a new issue with the missing information.

Regards,
