### ISSUE TITLE
🐞 Bug Report : Site Language & User language are reversed

### ISSUE THREAD

**Issue by janmeza** [elementor/elementor#19794]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am working on a website in a non-native language and I've noticed that Site language and user language are reversed.

https://elementor.com/help/set-editor-language/

And this is causing that Elementor language is always the same as Wordpress environment language.

### Steps to reproduce

1) Set site language in settings -> general to [Language 1]
2) Set your user profile language to [Language 2]
3) Check Site health info (Languages should be correct)
4) Check Elementor System info report and search for "lang" and you'll see that the Wordpress environment language is showing WP Profile lang and vise versa.  

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Unix) OpenSSL/1.1.1f
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0

== Active Plugins ==
	Elementor
		Version: 3.7.4
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

**Comment by rami-elementor** [comment]
Hi @janmeza 

For your description it sounds like it's a WordPress issue.

Can you elaborate on the problem in Elementor?

**Comment by rami-elementor** [comment]
@janmeza 

You attached your "System Info" to the issue. I see that:

* WordPress Environment > Language: en-US
* User > WP Profile lang: fr_FR

It means that you have an English website/frontend, but your WordPress dashboard and Elementor panels are in French.
