### ISSUE TITLE
Bon Ton Club critical error

### ISSUE THREAD

**Issue by rubirubi777** [elementor/elementor#19815]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello

Yesterday heppened a critical error on our website

www.bontonclub.net 

Header and footer doesn't look like they used to, menu also, the font changed and the calendar of our offline events also disappeared.

### Steps to reproduce

1) you open the website and it doesn't look like it should and when you are in elementor editor it shows like it should be but the published site is not 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://bontonclub.net
	Home URL: https://bontonclub.net
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: bontonclub77@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15

== Active Plugins ==
	Bluehost
		Version: 2.12.5
		Author: Bluehost

	Creative Mail by Constant Contact
		Version: 1.5.4
		Author: Constant Contact

	Elementor
		Version: 3.8.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0-dev42
		Author: Elementor.com

	Event Manager and Tickets Selling Plugin for WooCommerce
		Version: 3.7.3
		Author: MagePeople Team

	GDPR Cookie Consent
		Version: 2.1.2
		Author: WebToffee

	Google Analytics for WordPress by MonsterInsights
		Version: 8.8.2
		Author: MonsterInsights

	Gutenberg
		Version: 14.0.3
		Author: Gutenberg Team

	Jetpack
		Version: 11.3.1
		Author: Automattic

	OptinMonster
		Version: 2.10.0
		Author: OptinMonster Popup Builder Team

	Tutor LMS
		Version: 2.0.9
		Author: Themeum

	Tutor LMS Elementor Addons
		Version: 2.0.5
		Author: Themeum

	Weglot Translate
		Version: 3.7.3
		Author: Weglot Translate team

	WooCommerce
		Version: 6.9.1
		Author: Automattic

	WooCommerce Memberships
		Version: 1.23.1
		Author: SkyVerge

	WooCommerce Menu Cart
		Version: 2.12.0
		Author: WP Overnight

	WooCommerce Payments
		Version: 4.7.1
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.9.3
		Author: WooCommerce

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

	WPForms Lite
		Version: 1.7.6
		Author: WPForms

	Yoast SEO
		Version: 19.6.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elements Usage ==
	
	footer : 1
		button : 2
		heading : 7
		icon-list : 4
	header : 1
		nav-menu : 1
		social-icons : 2
		theme-site-logo : 1
	page : 1
		button : 1
		heading : 1
		mep-elementor-support : 1
		mep-event-list-widget : 1
		text-editor : 1
	section : 6
		button : 1
		call-to-action : 9
		form : 1
		heading : 4
		icon-box : 1
		text-editor : 5
	wp-post : 0
		text-editor : 1
	wp-page : 22
		button : 9
		call-to-action : 25
		divider : 6
		form : 2
		heading : 45
		icon : 4
		icon-box : 6
		image : 22
		image-box : 7
		mep-elementor-support : 6
		mep-event-list-widget : 6
		price-table : 1
		slides : 1
		text-editor : 36
	product-post : 0
		image : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 8 of 8PHP: 2022-08-10 21:38:11 [notice X 14][/home1/bontoncl/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-19 06:53:34 [notice X 1][/home1/bontoncl/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-19 07:09:49 [notice X 6][/home1/bontoncl/public_html/wp-content/plugins/elementor/includes/managers/image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-20 13:47:01 [notice X 2][/home1/bontoncl/public_html/wp-content/plugins/elementor/core/base/document.php::1467] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-21 09:04:31 [notice X 594][/home1/bontoncl/public_html/wp-content/plugins/elementor/core/base/document.php::249] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-27 13:51:22 [warning X 1][/home1/bontoncl/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::195] unlink(326497_account_circle_icon.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-28 01:39:35 [notice X 1][/home1/bontoncl/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-14 16:53:09 [error X 1][/home1/bontoncl/public_html/wp-content/plugins/elementor/includes/plugin.php::700] Uncaught Error: Class 'Elementor\Core\Experiments\Manager' not found in /home1/bontoncl/public_html/wp-content/plugins/elementor/includes/plugin.php:700
Stack trace:
#0 /home1/bontoncl/public_html/wp-content/plugins/elementor/includes/plugin.php(641): Elementor\Plugin->init_components()
#1 /home1/bontoncl/public_html/wp-includes/class-wp-hook.php(307): Elementor\Plugin->init('')
#2 /home1/bontoncl/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /home1/bontoncl/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /home1/bontoncl/public_html/wp-settings.php(598): do_action('init')
#5 /home1/bontoncl/public_html/wp-config.php(101): require_once('/home1/bontoncl...')
#6 /home1/bontoncl/public_html/wp-load.php(50): require_once('/home1/bontoncl...')
#7 /home1/bontoncl/public_html/wp-admin/admin.php(34): require_once('/home1/bontoncl...')
#8 /home1/bontoncl/public_html/wp-admin/update.php(16): require_once('/home1/bontoncl...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 292022-08-20 13:47:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.8.0-dev3',
)]
2022-08-20 20:56:25 [info] elementor-pro::elementor_pro_updater Started 
2022-08-20 20:56:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-20 20:56:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-20 20:56:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.0-dev36',
)]
2022-08-20 20:56:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.0-dev36',
)]
2022-08-21 08:56:15 [info] elementor::elementor_updater Started 
2022-08-21 08:56:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-21 08:56:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev3',
  'to' => '3.8.0-dev4',
)]
2022-08-21 08:56:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-21 08:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev3',
  'to' => '3.8.0-dev4',
)]
2022-08-29 10:21:28 [info] elementor-pro::elementor_pro_updater Started 
2022-08-29 10:21:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-29 10:21:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev36',
  'to' => '3.8.0-dev39',
)]
2022-08-29 10:21:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev36',
  'to' => '3.8.0-dev39',
)]
2022-08-31 23:09:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev39',
  'to' => '3.8.0-dev42',
)]
2022-08-31 23:09:10 [info] elementor-pro::elementor_pro_updater Started 
2022-08-31 23:09:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-31 23:09:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-31 23:09:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev39',
  'to' => '3.8.0-dev42',
)]

JS: showing 5 of 5JS: 2022-08-19 08:37:44 [error X 222][https://bontonclub.net/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2022-08-19 15:50:35 [error X 1][https://bontonclub.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:571218] null is not an object (evaluating \'elementor.documents.getCurrent().id\') 
JS: 2022-08-27 14:12:27 [error X 2][https://bontonclub.net/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.8.0-dev4:2:4806] undefined is not an object (evaluating \'e.attributes\') 
JS: 2022-09-01 07:41:54 [error X 5][https://bontonclub.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:631944] elementorFrontend.elements.window.jQuery is not a function. (In \'elementorFrontend.elements.window.jQuery(T.el)\', \'elementorFrontend.elements.window.jQuery\' is undefined) 
JS: 2022-09-13 07:39:08 [error X 6][https://bontonclub.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:766834] undefined is not an object (evaluating \'this.store.find((function(T){return T.original===C})).localized\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Tutor LMS Elementor Addons: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @rubirubi777 ,

Thanks for contacting us.

Please note that GitHub issues are reserved for **bug reports** and **feature requests**, they are **not used for support**.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards,
