### ISSUE TITLE
🐞 Bug Report : X position does not work in background and background overlay.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19814]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As mentioned in the title, X position does not work in background and background overlay. Works on desktop. But not tablets and mobile phones.
It seems that this bug and [this](https://github.com/elementor/elementor/issues/19809) are the only remaining bugs from version 3.7.

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/190318289-dfbdf052-f75f-454b-ad53-86e54f1440d8.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by chasperlisimba** [comment]
Same here. The options for X and Y position for tablets and mobile are back in 3.7.5 but the X position is not working.

**Comment by 79ho3ein** [comment]
Duplicate of #19487

**Comment by nicholaszein** [comment]
This issue was solved with Elementor 3.8! 🥳
