### ISSUE TITLE
Feature Request: Elementor Custom Code - Add "Footer" location

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#19811]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The Custom Code feature only allows Header, Body(start), and Body(end). 

### Describe the solution you'd like

Adding the ability to add custom code to the "Footer" as well.

### Describe alternatives you've considered

3rd party plugins

**Comment by rami-elementor** [comment]
Hi @portrayaloflife ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap.

HTML has the following structure:

```html
<html>

  <head>
  </head>

  <body>
  </body>

</html>
```

You can place your custom code at the head, body-start, and body-end.

There is no footer element to place the code. You can use the currently available body-end.
