### ISSUE TITLE
page title is not hidden from browser page name

### ISSUE THREAD

**Issue by uselessgames** [elementor/elementor#19821]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

when creating a page or template and asked to hide the title it is not hidden from the browser page title. it is appended to the WP site title.

the mentioned hide title setting

![image](https://user-images.githubusercontent.com/66875544/190428291-79746558-a8c1-4f52-9205-fc37c3e7ecdf.png)

it is hidden from the page, but still shows on the browser page name

![image](https://user-images.githubusercontent.com/66875544/190427779-e14f934d-44b7-4c4a-94b7-a109805ff9a8.png)

### Steps to reproduce

1. create a page or landing page
2. hide the title in the page or landing page settings
3. publish
4. view the page and see the browser title
5. realise mistake
6. add additional toggle to hide title from page name so people can choose where and when to show/hide.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

n/a

**Comment by rami-elementor** [comment]
Hi @uselessgames 

The title in the browser does not come from the `<h1>` title you try to hide on the page.

The browser takes the title from the `<title>` element located in the `<head>`. You can change this using SEO plugin like Yoast SEO.

In any case, it not a bug.

**Comment by uselessgames** [comment]
you can clearly see in the example i provided that the page title appends the `<h1>` title mentioned.
