### ISSUE TITLE
Ability to Save/Edit pages on Android/Mobile phone

### ISSUE THREAD

**Issue by mayurjobanputra** [elementor/elementor#19828]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm unable to edit any pages in Elementor on the mobile version of my pages on Android Chrome or Android Edge browsers. The save button that is normally present at the bottom of the page in is missing.

I don't edit pages that frequently on mobile, but every once in a while, a client asks me to change something and I'm not at my PC. Ability to edit on mobile is a useful feature to have. 

For more info, see a bug report I posted https://github.com/elementor/elementor/issues/19825

### Describe the solution you'd like

It would be great if I can save/edit pages on a mobile phone

### Describe alternatives you've considered

No alternatives exist as far as I know

### Additional context

https://i.imgur.com/G3lme5B.png

**Comment by rami-elementor** [comment]
Hi @mayurjobanputra ,

Thank you for submitting a feature request. After review, we have decided not to add this to our roadmap.

Mobile devices are not the right tool to create websites. Especially if they require responsive display for larger screens. We may re-consider in the future, but for now this feature won't be developed.

Regards,
