### ISSUE TITLE
Integration of acf with elementor pro

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#19836]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

I don't know, maybe this is a silly question, but do you have a plan to integrate with elementor pro by purchasing a powerful plugin like ACF? This can make elementor much more powerful.
The reason I gave ACF as an example was to be honest... In terms of dynamics, Elementor is very weak against its competitors. Integrating acf with elementor pro along with loop builder will change the game in elementor.

Of course, I guess Elementor has a similar program. I think for elemento to survive it needs such action.

### Describe the solution you'd like

Integration of acf with elementor pro + loop builder(which will be introduced soon) It will turn Elementor into a powerful plugin in every aspect, especially dynamics.

**Comment by rami-elementor** [comment]
Hi @Joliamendi 

We have no plans to purchasing ACF.

Elementor is a site builder; ACF is a WordPress custom fields plugin. Two different plugin types. We do integrate ACF fields inside Elementor using dynamic tags. But we won't be purchasing them and won't be developing custom fields functionality inside Elementor.
