### ISSUE TITLE
🐞 Bug Report: Container's css "isolation: isolate;" is an overkill and will likely cause problems (ED-8350)

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#19834]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This pull request https://github.com/elementor/elementor/commit/57489eb30cc121bf46dc5314604d89ef037900bd fixed the display of the video's fallback image, but brought some negative z-indexes to the overlay and video container, plus the `isolation: isolate` property on the Container element.

This will likely create problems since it creates a new stack context and may lead to issues like other positions, transforms etc. I can't predict exactly everything, but for example a z-index of 100000 on an element inside the container will not leave the container unless the container also has that z-index. This creates a stacking problem.

The solution is pretty simple, just move the `:before` pseudo selector's properties on the video container. The overlay will stay inside the video container while being overlapped by the content of the Container.

Made a quick video recording using the alternative https://d.pr/v/gDT4oG . 

### Steps to reproduce

https://d.pr/v/gDT4oG

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @hogash! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by rally-lad** [comment]
Just to add to this.

This issue also exists in Elementor 3.7.7 with Elementor Forms V3 recaptcha hiding behind flex box containers.
No matter what the z-index is set to on the .grecaptcha-badge it falls behind a container.

**Comment by nicholaszein** [comment]
Thank you @rally-lad! I'll add this to our tracker as well.

Cheers! 🥂

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!
