### ISSUE TITLE
Not sure what to do

### ISSUE THREAD

**Issue by Randye63** [elementor/elementor#19831]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

how to fix this

### Steps to reproduce

im not sure

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Deprecated: Function Elementor\DB::is_built_with_elementor is deprecated since version 3.2.0! Use Plugin::$instance->documents->get( $post_id )->is_built_with_elementor() instead. in /home/nuuvisio/public_html/wp-includes/functions.php on line 5379

**Comment by loucasl** [comment]
This means that one of your plugins has not been updated to be compatible with the latest Elementor versions. You'll need to deactivate and reactivate each of your third party plugins one by one to find the culprit

**Comment by arielk** [comment]
In order for us to look into this matter, please contact our support team through your account with complete login information to access your website, and our support team will try to assist.
