### ISSUE TITLE
✔️ 🐞Bug Report : If the header has a z-index, the container handles are hidden.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19842]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If the header has a z-index value, the handle of the first container will be hidden under it. So, is there a way to make the handles of containers not be affected by the z-index of other content? In this case, the z-index of the header, whatever its value, will not hide the container handle, and that will be fine.

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/190916745-a07f5f0f-0325-4ccd-8fe4-9113ab905058.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by dantetesta** [comment]
my z-index dont works afert free version 3.7.2.... just 3.7.1 is working well

**Comment by nicholaszein** [comment]
Thanks for the report @79ho3ein.

We'll look into improving this part of the UI. 🙏

**Comment by nicholaszein** [comment]
> my z-index dont works afert free version 3.7.2.... just 3.7.1 is working well

Hello @dantetesta, please submit a new bug issue and follow the instructions [here](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

We need you to provide as much information as possible so we can assess if this is indeed a bug.

Thanks 🙏

**Comment by 79ho3ein** [comment]
thank you @nicholaszein

**Comment by nicholaszein** [comment]
This issue has been resolved in Elementor v3.8. 🥳 

Thanks for helping us! 🙏

**Comment by 79ho3ein** [comment]
thank you @nicholaszein 🥂
