### ISSUE TITLE
🐞 Bug Report : important bug in menu cart - container (The menu cart opens below the content)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19845]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you create the header and content of the website using the container, if you use the menu cart widget in the header, after the menu cart is opened, this widget will be displayed below the content. Watch the following video :

https://user-images.githubusercontent.com/77163248/190972397-cbdac388-56f6-4030-8b86-aecf01a60b32.mp4

**please note**

If sticky mode is enabled for the header container, there is no problem. But if sticky is off, this bug will occur.

### Steps to reproduce

- Add a container for the header and place the menu cart widget inside it.
- Also create a page and put contents inside it. For example, a slider or several images.
- Now visit the website and click on the menu cart to open it.

 The bug is quite obvious. The menu cart widget opens below the content.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by navarroido** [comment]
Try to add z-index for the container with the cart, and in addition to the cart itself.

**Comment by 79ho3ein** [comment]
Hi @navarroido 
Yes, that was the method @zeinnicholas recommended as well. But using this method brings problems to another part. I will give an example for it  : 

If we increase the z-index value in the container (in which the menu cart widget is located), it makes the handle of the first container unreachable. Because it is placed under the header container. See the following video :

https://user-images.githubusercontent.com/77163248/191133314-3ff21780-2f2a-4c43-9c83-7160ecea5ff8.mp4

So I think it would be much better if this problem is fixed in the menu cart widget by default and it works like before.

**Comment by zeinnicholas** [comment]
Thanks for the feedback @79ho3ein !

We will pass this along to the people responsible and see what we can do to address the issue with the handle.

Until then, an alternative to the handle issue is to use the navigator to select the container below the header. It's not a proper solution, but at least it will let you get around these limitations. 😉

**Comment by 79ho3ein** [comment]
Thank you for your attention @zeinnicholas

**Comment by mkiii333** [comment]
This one is related https://github.com/elementor/elementor/issues/19705

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!

**Comment by de-er-kid** [comment]
After adding a product to cart it takes a few seconds to view cart data & it's blank for that much time, can we Add 'Loading..' text to elementor Menu Cart Widget while the cart data are being retrieved ?

There could be a 'No products in the cart' when no products are in the cart. But after adding a product to cart it's totally blank until the new cart data is retrived, A loading text with spinner while loading data through ajax is an common used method.

Or could anyone say where is the source code for this widget inside plugin ?
