### ISSUE TITLE
⛔ 🚀 Feature Request: New dynamic tag for add to home screen (only for mobile users)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19844]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

As you know, almost all famous browsers have the add to home screen feature. By activating this option, the website will be added to the user's mobile home screen (like an application). This is a great feature in browsers. But there is a problem for them. Many users are not aware of this feature in browsers. They can also be a bit difficult to reach. Therefore, adding a new feature in elementor can provide this option to website users in the most beautiful way possible.
I think adding this feature in Elementor would be a very useful and great feature. please check this offer.

### Describe the solution you'd like

Add a new dynamic tag (add to home screen).Using this dynamic tag, we can display an option in a pop-up, so that after the user enters the website with a mobile, the message will be displayed (image below) - In the image below, the icon list widget is used. We can use the dynamic tag in other widgets like button.

![download](https://user-images.githubusercontent.com/77163248/190968931-38367794-977e-4af5-9f6e-32b9f7815072.png)

If the user clicks on this option, the website will be added to the user's mobile home screen. This is really wonderful. This makes it easy for the user to enter the website for the next visit. Just click on the website icon on your mobile home screen to enter the website.

This feature can be developed a lot more and work better. But this would be great to start with.

thank you

**Comment by nicholaszein** [comment]
Hi @79ho3ein ,

Thank you for submitting a feature request. 
After review, we have decided not to add this to our roadmap for the time being. This feature is something you can already do using other means, and there are even plugins specialized in providing more control to this browser feature.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Please feel free to contact us again with other feature suggestions.

Regards,

Nick
