### ISSUE TITLE
Elementor Pro (with Flexbox containers) isn’t compatible with Yoast (paid). Styles panel disappears.

### ISSUE THREAD

**Issue by erok415** [elementor/elementor#19853]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Pro (with Flexbox containers) isn’t compatible with Yoast (paid). Styles panel disappears.

### Steps to reproduce

1. You must have Elementor Pro and Yoast (paid) enabled.
2. Elementor Pro Flexbox containers must be enabled.

For any containers you build with Elementor after enabling Yoast (paid plugin), the Elementor containers styles panel disappear with JavaScript errors showing in the browser console.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.6
	MySQL version: MariaDB Server v10.4.25
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://dev-figment-inc.pantheonsite.io
	Home URL: https://dev-figment-inc.pantheonsite.io
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /resources/%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: erik@mollyduggan.io
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	Auto Upload Images
		Version: 3.3
		Author: Ali Irani

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.7.9
		Author: Dynamic.ooo

	Elementor
		Version: 3.7.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.6
		Author: Elementor.com

	Enable Media Replace
		Version: 4.0.0
		Author: ShortPixel

	Figment Protocols
		Version: 0.0.1
		Author: Molly Duggan Associates

	Gravity Forms
		Version: 2.6.6
		Author: Gravity Forms

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	Login by Auth0
		Version: 4.3.1
		Author: Auth0

	Pantheon Advanced Page Cache
		Version: 1.0.0
		Author: Pantheon

	Redirection
		Version: 5.3.3
		Author: John Godley

	Schema & Structured Data for WP & AMP
		Version: 1.9.100
		Author: Magazine3

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP All Export - ACF Export Add-On Pro
		Version: 1.0.4
		Author: Soflyy

	WP All Export Pro
		Version: 1.8.0
		Author: Soflyy

	WP All Import - ACF Add-On
		Version: 3.3.7
		Author: Soflyy

	WP All Import - User Import Add-On Pro
		Version: 1.1.7
		Author: Soflyy

	WP All Import - Yoast WordPress SEO Add-On
		Version: 1.1.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.7.6
		Author: Soflyy

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.6.1
		Author: Team Yoast

== Must-Use Plugins ==
	Pantheon
		Version: 0.3
		Author: Pantheon

== Elements Usage ==
	
	archive : 3
		container : 20
		dce-dynamicposts-v2 : 2
		heading : 1
		icon-list : 1
		nav-menu : 1
		search-form : 1
		theme-archive-title : 2
	container : 23
		button : 19
		container : 165
		heading : 82
		icon-list : 6
		image : 33
		post-info : 8
		shortcode : 4
		testimonial-carousel : 4
		text-editor : 15
		toggle : 6
	footer : 1
		container : 16
		icon-list : 6
		image : 2
		social-icons : 1
		text-editor : 7
	header : 1
		container : 5
		jet-mega-menu : 1
		theme-site-logo : 1
	popup : 1
		button : 1
		container : 7
		icon : 1
		theme-site-logo : 1
	wp-post : 0
		button : 3
		container : 43
		heading : 6
		icon-list : 13
		price-list : 1
		social-icons : 1
	wp-page : 18
		button : 55
		container : 437
		counter : 9
		dce-dynamicposts-v2 : 15
		dce-views : 1
		form : 2
		heading : 140
		icon-list : 3
		image : 80
		image-gallery : 1
		nav-menu : 2
		search-form : 2
		shortcode : 4
		social-icons : 1
		text-editor : 86
	single-post : 1
		container : 25
		dce-dynamicposts-v2 : 1
		form : 1
		heading : 7
		image : 4
		search-form : 1
		share-buttons : 1
		shortcode : 1
		theme-post-content : 1
		theme-post-title : 1
	single-page : 2
		button : 2
		container : 53
		dce-dynamicposts-v2 : 1
		heading : 21
		image : 9
		shortcode : 1
		text-editor : 6
		toggle : 1
	error-404 : 1
		button : 1
		container : 3
		heading : 1
		text-editor : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
Hi @erok415 

We contacted Yoast team. They know about it.

**Comment by erok415** [comment]
Thank you
