### ISSUE TITLE
🐞 Bug Report: v3.8 beta bug - Elementor Pro on Multisite

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19878]
### Description

When using the beta on a multisite with Elementor Pro enabled there is a notice [screenshot below] about updating Elementor, even though Pro is the latest version. When you click on the update button in the notice it takes you to a pages that says 'The plugin is at the latest version.'. I only test plugins on a throwaway multisite so I presume it is only a multisite issue since other users haven't reported this.

![Screenshot 2022-09-21 202611](https://user-images.githubusercontent.com/55829113/191593737-c2a234d6-3b61-4abd-a46a-a6d38281b489.png)

With Pro plugin disabled this notice disappears. Pro is at latest version as the loop builder is available...

**Comment by nicholaszein** [comment]
Hi @perks98!

Thanks for reporting this. This is a known technical issue (internal).

They are working on a solution as we speak and it will be addressed soon. 😉

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.8.0 - Beta 2.

Feel free to update
Thanks!
