### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Serious conflict "bold font" between elementor and SiteGround Optimizer

### ISSUE THREAD

**Issue by Nemesi965** [elementor/elementor#19880]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, I have a bug in the "contact" page of my site. By simply working on some sections and after saving, some entries like the footer and some headers in BOLD appeared. This only happens when I view the site online. If I open that page with "edit with elementor" the problem does not exist. I regenerated the css, cleaned various caches. You told me the problem is generated by SG optimizer, but siteground says that when they regenerate css of elementor, it solve. But it don't solve nothing because after few minute everything return as before. Siteground in the other side told me that this bug is not from their plugin.  Is all ridiculous because your colleague told me that it is a know issue. 

### Steps to reproduce

Hi simply work on my website. I explained everything above in description

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-neurochirurgiaboari.it-21-09-2022.txt](https://github.com/elementor/elementor/files/9620424/system-info-neurochirurgiaboari.it-21-09-2022.txt)

**Comment by nicholaszein** [comment]
Hello @Nemesi965.

I understand your frustration but please understand that cache is generated **_AFTER_** Elementor outputs all its styles. This is not a bug and should be solved by tweaking your performance optimization settings until the issue stops happening. We are not responsible for providing support for 3rd party plugins. 

If the issue doesn't happen inside the editor, it means your performance optimization plugin is affecting the styles generated by Elementor.

To know how to troubleshoot this, please check [this article](https://elementor.com/help/changes-dont-appear-online/).

Please note that GitHub issues are reserved for bug reports and feature requests, and are not used for support.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon for details.

Regards
