### ISSUE TITLE
🐞 Bug Report: [v3.8-Beta] - Loop Builder - Mobile Responsive columns not applying the correct value. (ED-8238)

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#19881]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I found a display bug in default mobile editor view:

<img width="1135" alt="Bildschirmfoto 2022-09-21 um 14 48 17" src="https://user-images.githubusercontent.com/57997262/191508448-53c5fee9-7178-484b-891f-e9f2de542962.png">

### Steps to reproduce

1. I set the columns to "1", but shows "2" from desktop and tablet setting. Front and Backend!
2. The "Edit Template" option looks very buggy in this default mobile width..

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

–

**Comment by fabianenzensperger** [comment]
#19854

**Comment by nicholaszein** [comment]
Awesome! Thanks for submitting your bug here @fabianenzensperger!

Take care! 😉

**Comment by nicholaszein** [comment]
Hello,

this issue was added to our v3.8 Beta roadmap! 💪

Thanks for reporting it! 🙏

**Comment by fabianenzensperger** [comment]
> Hello,
> 
> this issue was added to our v3.8 Beta roadmap! 💪
> 
> Thanks for reporting it! 🙏

Glad I could help! 🙌

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-4

Feel free to update

Thanks!
