### ISSUE TITLE
✔️ 🐞 Bug Report: [v3.8-Beta] - Loop Builder - "Apply & Preview" button returns "the_content not found" error (ED-7381)

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#19882]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I found a Loop Builder Preview bug. It's not very user-friendly and I think it is a bug.

https://user-images.githubusercontent.com/57997262/191510888-3d5df942-55a1-4687-a565-4f09c307e9fd.mp4

### Steps to reproduce

I create a "Loop Grid", create a "Loop Template" and change later under settings the "Preview" and it not works or says it's an error. I "Go Back" and click "Edit with Elementor" again, so then it was taken over.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

–

**Comment by fabianenzensperger** [comment]
#19854

**Comment by nicholaszein** [comment]
Thanks, @fabianenzensperger! 🙏

**Comment by perks98** [comment]
I had this happen late yesterday where it pops up about missing content area too.

**Comment by nicholaszein** [comment]
Hello,

this issue was added to our v3.8 Beta roadmap! 💪 

Thanks for reporting it! 🙏

**Comment by fabianenzensperger** [comment]
> Hello,
> 
> this issue was added to our v3.8 Beta roadmap! 💪
> 
> Thanks for reporting it! 🙏

Thanks! I'm always happy to help.

**Comment by nicholaszein** [comment]
Hey guys, just updating, I'm sure you already know about this, but...

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by fabianenzensperger** [comment]
> Hey guys, just updating, I'm sure you already know about this, but...
> 
> ### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.0**! 🥳
> ✔️ Please feel free to check it out and update your plugin to the new version!
> 
> Cheers 🥂

In 3.9.0 beta, but yeah thanks for the fast fix!! 🤗

**Comment by nicholaszein** [comment]
Hehe, that's correct @fabianenzensperger!

**This issue was resolved with Elementor Pro v3.9.0**, not as I [stated before](https://github.com/elementor/elementor/issues/19882#issuecomment-1309048894). Sorry for that mishap 😅
