### ISSUE TITLE
⛔ 🐞 Bug Report: Wordpress twenty twenty two - header/footer unable to edit edit the header or the footer

### ISSUE THREAD

**Issue by alicedoe** [elementor/elementor#19885]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am unable to edit header/footer using elementor I get the error “Content area not found error” I have found the issue here : https://elementor.com/help/known-bugs-and-user-experience-issues/ but not on github is there an issue already opened ?

### Steps to reproduce

Worpress after 5.9 update (actually on 6.0.2) + elementor/elementor pro (I have tried different versions) + twentytwenty two theme try to create / edit header or footer using elementor : Error “Content area not found error”

- Without elementor pro : no error
- With twentytwenty theme : no error

**Comment by nicholaszein** [comment]
Hello @alicedoe, 

thanks for submitting your report. The **twenty-twenty-two** theme is a block-type theme with Full Site Editing (FSE) capabilities. These types of themes are built differently than the classical way of building themes and do not include key template part files that are usually present in classic themes like the Hello Elementor theme for example. 

**This means Elementor and the twenty-twenty-two theme are incompatible with each other.** 

If you wish to edit your header and footer you will need to use another theme, like the [Hello Theme](https://wordpress.org/themes/hello-elementor/).
