### ISSUE TITLE
🐞 Bug Report: [v3.8-Beta] - Widget's "max-width" prevents flex-grow from working inside fullwidth container. Default values for responsive are wrong (ED-7916)

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19891]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest beta version of Elementor.

### Description

Just for widgets while in a container that is set to full width and you set a custom width of the widget to something like 50% and try and make it grow, it doesn't. From checking the CSS it seems the max-width is the same as user-defined (50%) but the max-width should always be 100%. Flex-grow works in boxed view, so even if 50% width is applied to the widget the max-width is still 100% so it can grow when specified. See reproduce section for video.

Another issue is inputting your own flex-grow or shrink value. If for instance, you set on desktop flex-grow to 4 then on tablet and mobile the placeholder will be 1 even though 4 is applied. Then on the other side of it, if no flex-grow value is set on desktop and you enable custom flex grow and shrink input the placeholder is 1 by default so you assume it is set when it isn't as it is actually value 0 so you have to input 1 where the 1 already is. Video in reproduce section.

### Steps to reproduce

**Flex-grow issue when container is full-width:**

https://user-images.githubusercontent.com/55829113/191836880-14b782d3-bc24-4972-a06e-3987cad0eb7a.mp4

<hr>

**Flex grow and shrink placeholder issue:**

https://user-images.githubusercontent.com/55829113/191838693-39ddf02c-3e04-4b2a-af94-cb89d622343f.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pauserratgutierrez** [comment]
Looks like this must be fixed soon 💯

**Comment by nicholaszein** [comment]
Thank you for reporting this issue @perks98!

We added this to our list of issues to be resolved in this beta. 💪

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!
