### ISSUE TITLE
🐞 Bug Report: [v3.8-Beta] Container - Background image transition not working (Duplicate of #19913)

### ISSUE THREAD

**Issue by domov44** [elementor/elementor#19908]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I noticed a bug in Elementor since the 3.7 update.
I explain it:
when using flexboxes, setting up a container with a background image and putting a second one for hover (or the same one with a different position) the transition between the 2 is broken as if the transition was 0. Normally the option in Elementor allows us to choose the transition time between these 2 background images, but since the update the option doesn't work anymore. 

Important to note, that the transition works for the background overlay, and that it only impacts the flexbox containers and not the classic sections.
I tested on manu themes (astra, woodmart, hello themes)

### Steps to reproduce

1) Installing Elementor's flexbox functionality 
2) Create a container and give it a background image and a hover background image
3) Try to set up the transition (e.g. 3s)
4) Fly over the container and notice that the transition does not work

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://test-maj-elementor.local
	Home URL: http://test-maj-elementor.local
	WP Multisite: No
	Max Upload Size: 300 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 0
	Admin Email: dev-email@flywheel.local
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.7.7
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.11.15
		Author: WPVibes

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.3.0
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.1.5
		Author: WPDeveloper

	Yoast SEO
		Version: 19.7.1
		Author: Team Yoast

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif
	Default to New Theme Builder: Actif par défaut
	En-tête et pied de page du thème Hello: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Page Transitions: Actif par défaut
	Notes: Actif par défaut
	Form Submissions: Actif par défaut
	Scroll Snap: Actif par défaut

== Journal ==
	
PHP: showing 3 of 3PHP: 2022-08-01 08:14:50 [error X 1][C:\Users\rscot\Local Sites\test-maj-elementor\app\public\wp-content\plugins\elementor-pro\license\admin.php::386] syntax error, unexpected ';' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-29 13:25:04 [notice X 2][C:\Users\rscot\Local Sites\test-maj-elementor\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-08 08:17:20 [notice X 14][C:\Users\rscot\Local Sites\test-maj-elementor\app\public\wp-content\plugins\elementor-pro\license\updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 352022-08-31 22:08:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-08-31 22:08:54 [info] elementor::elementor_updater Started 
2022-08-31 22:08:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-31 22:08:54 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-31 22:08:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-14 19:40:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-14 19:40:14 [info] elementor::elementor_updater Started 
2022-09-14 19:40:14 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-14 19:40:14 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-14 19:40:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-21 06:50:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.7.7',
)]
2022-09-21 06:50:56 [info] elementor::elementor_updater Started 
2022-09-21 06:50:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-21 06:50:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-21 06:50:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.7.7',
)]
2022-09-21 06:55:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.7',
)]
2022-09-21 06:55:21 [info] elementor-pro::elementor_pro_updater Started 
2022-09-21 06:55:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-21 06:55:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-21 06:55:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.7',
)]

JS: showing 1 of 1JS: 2022-08-18 21:41:58 [error X 1][http://test-maj-elementor.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:766045] Cannot read properties of undefined (reading \'toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	Elementor Addon Elements: Compatibilité non spécifiée
	Elementor Pro: Compatibilité non spécifiée
	Essential Addons for Elementor: Compatibilité non spécifiée
	Essential Addons for Elementor - Pro: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==

**Comment by perks98** [comment]
I can confirm, I get the same problem; video below.


https://user-images.githubusercontent.com/55829113/192144148-8e5689e3-a74c-4366-b834-6bed019175ad.mp4

**Comment by nicholaszein** [comment]
Hello @domov44! 

Thank you for submitting your report! 🙏 

I can confirm the issue. It seems it's a wider issue happening to other transitions. To make it easy for our team to track this issue, I'll be closing it and redirecting it to @perks98's broader issue report. Please feel free to continue the conversation there.

Best regards

**Comment by nicholaszein** [comment]
Hello there @domov44!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
