### ISSUE TITLE
⛔ 🐞 Bug Report: container not working

### ISSUE THREAD

**Issue by ray14125** [elementor/elementor#19900]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

the container is not working. if i post that i can't do split screen. if I click on the plus in the container on the right, I can choose split screen, but then when the page is live, put under each other and not next to each other. the spacer also suddenly stops working. you can place it and see space coming up, but when the page is live then the whole effect is gone. I now always place separation with a line but this is not the intention.

### Steps to reproduce

![scheidingslijn 1](https://user-images.githubusercontent.com/9366528/191990278-696f0d5d-3e9a-4156-8a70-1ba46a1d9fb2.PNG)
![scheidingslijn](https://user-images.githubusercontent.com/9366528/191990315-0f0b2d0e-1dcf-4d19-9848-9f2664b57777.PNG)
![afstandshouder](https://user-images.githubusercontent.com/9366528/191990341-f95130fe-f833-4bb5-97bf-ecd4122f6353.PNG)
![afstandshouder 1](https://user-images.githubusercontent.com/9366528/191990357-61c019b8-8399-4c6d-9cea-030a91b83d2e.PNG)
the first photo is behind the scenes and the second photo is on the website

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-vakantiehulp.eu-23-09-2022.txt](https://github.com/elementor/elementor/files/9634797/system-info-vakantiehulp.eu-23-09-2022.txt)

**Comment by nicholaszein** [comment]
Hello @ray14125. 

Thanks for contacting us.

Please before posting, make sure you have followed the best practices for troubleshooting your issue outlined [here](https://elementor.com/help/changes-dont-appear-online/).

From your System Info, I see you have multiple active plugins, including performance optimization ones. It seems you might be having cache issues.

Please note that GitHub issues are reserved for bug reports and feature requests, and are not used for support. And that you said this issue only happens with Elementor active, while I can see there are lots of other plugins that might have a role in causing it. We cannot take responsibility for 3rd party plugins. Try following the troubleshooting steps outlined in the article shared above, and if you still are having issues, contact Elementor support.

For support, feel free to check out:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you’ve purchased [Elementor Pro](https://elementor.com/pro), you are entitled to either premier or VIP support. To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.for details.

Regards.
