### ISSUE TITLE
⛔ 📚 🐞 Bug Report: Connect token for CLI's `library connect` command no longer available

### ISSUE THREAD

**Issue by jdsnty** [elementor/elementor#19903]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

[Documentation](https://developers.elementor.com/docs/cli/library-connect/) for the [`library connect`](https://github.com/elementor/elementor/blob/master/modules/wp-cli/library.php#L167) CLI command (including the command help and explanatory comments) indicates that the required `token` parameter can be obtained from the Elementor Account Dashboard, which is not the case.

I understand this might actually be an issue with the _my.elementor.com_ website rather than the Elementor app itself, but this results in a feature being rendered inaccessible. Should there be a different procedure to obtain the `connect-cli-token` (is there one?) then it should be listed instead on the command's help in this repository.

---

I reviewed Elementor's documentation and forums extensively and found no further information on the topic. I was then directed to ask here by Elementor Pro's help desk.

Any information on how to currently get the connect token (as a temporary solution) will be greatly appreciated.

### Steps to reproduce

Calling the `elementor-pro library connect` command from WordPress's CLI requires a `token` parameter.

If no token is given, an `Error: please set connect token.` message is shown.

Any values other than the intended token (which, as far as I can see, is nowhere to be found) result on an `Error: Bad Request` message instead.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not relevant in this case, as it does not affect an installation in particular.

Account with Elementor 3.7.7 and an active Elementor Pro 3.7.7 license.

**Comment by nicholaszein** [comment]
Hello @jdsnty!

Thank you for submitting your issue! 🙏 

I will forward it to the team responsible, and clarify where you can find the information you seek.

Please allow us some time to review your issue, and find a solution. We'll get back to you as soon as possible! 💪 

Thank you!

**Comment by rami-elementor** [comment]
Hi @jdsnty 

This CLI command is not broken and it is [still available](https://github.com/elementor/elementor/blob/master/modules/wp-cli/library.php#L167-L207). But, as you mentioned, the `token` is not available for external developers.

I've updated the docs. Thank you for your feedback!

**Comment by patrick-leb** [comment]
Is there any way or plans to allow us getting tokens? It's a big deal for Agency plan users like us.....

**Comment by nicholaszein** [comment]
Hello @patrick-leb.

There are no plans to allow public access to these tokens for the time being for security reasons.

Kind regards,

Nick
