### ISSUE TITLE
✅ 📚 ❓ API Question: Understanding Render Frontend Elements

### ISSUE THREAD

**Issue by hiviz** [elementor/elementor#19902]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Context:
--------
In going through the Elementor Developers documentation for the "Render Frontend Elements" PHP hook (https://developers.elementor.com/docs/hooks/render-frontend-elements/), the following Hooks are provided:
- elementor/frontend/before_render
- elementor/frontend/after_render
- elementor/frontend/{$element_type}/before_render
- elementor/frontend/{$element_type}/after_render
... where the dynamic portion of the hook name, $element_type, refers to element type.

Issue:
-----
I am trying to understand the difference between:
1. elementor/frontend/before_render and elementor/frontend/after_render
2. elementor/frontend/before_render and elementor/frontend/{$element_type}/before_render
3. elementor/frontend/after_render and elementor/frontend/{$element_type}/after_render

...and what:
4. "element type"
...is.

Can I get some clarification on these points please?

### Steps to reproduce

I was told by Elementor Pro support that raising an issue in the Elementor Github is the best channel to get clarification on the Developer's Documentation.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

N/A

**Comment by nicholaszein** [comment]
Hello @hiviz ! 

Thank you for submitting your issue! 🙏 

The `$element_type` refers to the type of element you're targeting. For example here are some types of elements you can use:

- section (works for both sections and inner sections)
- column
- container
- widget
- $name_of_widget

This allows you to target specific elements or even specific widgets (each widget type is equal to the widget name found inside each widget class), and then parse your code accordingly.

I'll pass this on to the developer-api team to see if they can expand the documentation and make it more accessible.

I hope this helps. 😉

**Comment by nicholaszein** [comment]
@rami-elementor Can you clarify this, please? 🙏

**Comment by rami-elementor** [comment]
@hiviz @nicholaszein 

Docs updated:

https://developers.elementor.com/docs/hooks/render-frontend-elements/

**Comment by nicholaszein** [comment]
Hey @hiviz!

It's option **A**. You nailed it! 😉

**Comment by hiviz** [comment]
Thanks @nicholaszein , (cc: @rami-elementor )

With your confirmation, I can visualise the hook location for `elementor/frontend/{$element_type}/before_render` and `elementor/frontend/{$element_type}/after_render`. Referring to the pseudocode below, they would respectively appear directly below and above every instance of `$element_type`:

```
<head>
  <header_stuff>
  </header_stuff>
</head>

<body>
  <elementor/frontend/{$element_type}/before_render-hook-location>
  </elementor/frontend/{$element_type}/before_render-hook-location>
  <$element_type>
  </$element_type>
  <elementor/frontend/{$element_type}/after_render-hook-location>
  </elementor/frontend/{$element_type}/after_render-hook-location>
  ...
  <body_stuff>
  </body_stuff>
  ...
  <elementor/frontend/{$element_type}/before_render-hook-location>
  </elementor/frontend/{$element_type}/before_render-hook-location>
  <$element_type>
  </$element_type>
  <elementor/frontend/{$element_type}/after_render-hook-location>
  </elementor/frontend/{$element_type}/after_render-hook-location>
</body>

<footer>
  <footer_stuff>
  </footer_stuff>
</footer>
```

However, I'm still not entirely sure where the hook locations for `elementor/frontend/before_render` and `elementor/frontend/after_render` are. Since it's relative to "all the elements in the page", is it in the header and footer respectively? Somewhere else?

Many thanks!

**Comment by nicholaszein** [comment]
Hello @hiviz,

you can find the code [here](https://github.com/elementor/elementor/blob/97f2db9d04a34dd3b1fc9fc101ab2536d6834528/includes/base/element-base.php#L405).

As you can see, `elementor/frontend/before_render` runs exactly before `elementor/frontend/{$element_type}/before_render` (the same with `after_render`). The difference between both is very simple:

- One targets any element with `elementor/frontend/before_render` regardless of which type of element it is.
- The other targets specific types of elements with `elementor/frontend/{$element_type}/before_render`, so you can only apply your code on `sections` for example.

Does that make sense?

**Comment by nicholaszein** [comment]
Hello @witty-code!

yes you can do this using the `$element->get_name()` method. Here's an example:

````php
/** 
 * Adds Hello World text before Heading Title Element
 */
function prefix_before_heading_title_hello_world( $element ) {
	// Get the widget name
	$widget_name = $element->get_name();
	
	// Check if it's the Heading Title widget
        if ( $widget_name === 'heading' ) {
                echo '<span>' . __( 'Hello World' ) . '</span>';
        }
}
add_action( 'elementor/frontend/widget/before_render', 'prefix_before_heading_title_hello_world' );
````

I hope this helps! 😉

**Comment by witty-code** [comment]
> Hello @witty-code!
> 
> yes you can do this using the `$element->get_name()` method. Here's an example:
> 
> ```
> /** 
>  * Adds Hello World text before Heading Title Element
>  */
> function prefix_before_heading_title_hello_world( $element ) {
> 	// Get the widget name
> 	$widget_name = $element->get_name();
> 	
> 	// Check if it's the Heading Title widget
>         if ( $widget_name === 'heading' ) {
>                 echo '<span>' . __( 'Hello World' ) . '</span>';
>         }
> }
> add_action( 'elementor/frontend/widget/before_render', 'prefix_before_heading_title_hello_world' );
> ```
> 
> I hope this helps! 😉

Thank you for your detailed answer, my question is about the header section as a whole

This section starts like this:
```
<div data-elementor-type="header" data-elementor-id="1234" class="elementor elementor-1234 elementor-location-header">
```

The only thing I need to do is add a 'class' to it or wrap it inside another 'div'

**Comment by nicholaszein** [comment]
Hi, @witty-code,

### ⛔ The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
