### ISSUE TITLE
🐞 Bug Report: [v3.8-Beta] - Widgets List not showing the "Layout" section when editing the Loop Item template inside a page (ED-8386)

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19911]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest beta version of Elementor.

### Description

When creating a loop item the layout tab is missing so from the initial list you can't add more nested containers, but if you search for it by typing it appears in the list.

Missing this: 
![Screenshot 2022-09-25 193253](https://user-images.githubusercontent.com/55829113/192159566-cbeb263c-6921-4f1e-a3d0-607d896226ee.png)

### Steps to reproduce

Missing Layout tab on loop item editor, but can search for container:

https://user-images.githubusercontent.com/55829113/192159416-ffb8f664-dc4d-4714-9178-eff8f8371b76.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nicholaszein** [comment]
Hey @perks98! 

Thank you for spotting this issue! 🙏 

I already labeled it to be included in the v3.8 beta! 

Best regards

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-4

Feel free to update

Thanks!
