### ISSUE TITLE
🔗 🐞 Bug Report: [v3.8-Beta] Container transitions not working (Related to #19908) (ED-8387)

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19913]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest beta version of Elementor.

### Description

I'm only testing with beta 3.8 at the moment so I don't know if this issue is before then.

On a container, if you set the box shadow or border the transition on hover doesn't work. When I add my own CSS for the transition it works so something is wrong in the settings. This issue may relate to existing issues with transitions like with issue #19908.

### Steps to reproduce

https://user-images.githubusercontent.com/55829113/192161070-792baaca-1a15-4398-9958-7ffa1d3ee495.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nicholaszein** [comment]
Thanks for the super helpful report @perks98! You rock! 💪 

I've already directed your bug report to the team responsible.

Cheers! 🍻

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-6

Feel free to update

Thanks!
