### ISSUE TITLE
🚀 Feature Request: Forms - Reverse label and input tags rendering order

### ISSUE THREAD

**Issue by JGaulois** [elementor/elementor#19929]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,

I would like to know if it was possible to reverse the order of the input and label tags in the HTML code of Elementor forms (like on the screen-inversion in pj)?

Indeed, I try to integrate material design but it does not work by having the Label tags before the input tags.
The objective is to integrate an animation as on the screen-inversion-good in pj. (It is possible to test the animation on the attached link. You have to reverse the tags in the inspection to see the result.)

Do you think you can help me please :)
I can create temporary identifiers.

See you soon

### Steps to reproduce

1) Inspect the element of the Name fields of the page: https://beta.terroirgaulois.fr/faire-une-reclamation/
2) If we invert the <label> and <input> fields, the animation will work
3) Otherwise it does not work
4) This must be modified on all the forms of the site but I do not see how and which file must be modified

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.30
	PHP Memory Limit: 4096M
	PHP Max Input Vars: 2000000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://beta.terroirgaulois.fr
	Home URL: https://beta.terroirgaulois.fr
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 40M
	Max Memory limit: 4096M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 0
	Admin Email: webmaster@terroirgaulois.fr
	Debug Mode: Inactive

== Theme ==
	Name: Hello-elementor Child
	Version: 1.0
	Author: Terroir Gaulois
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	ACF For Dokan
		Version: 1.3.3
		Author: krazyplugins

	Advanced Custom Fields
		Version: 6.0.0
		Author: WP Engine

	Conditional extra fees for WooCommerce
		Version: 1.0.74
		Author: PI Websolution

	Dokan
		Version: 3.7.0
		Author: weDevs

	Elementor
		Version: 3.7.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.0
		Author: Wpmet

	Jetpack
		Version: 11.3.2
		Author: Automattic

	JetSmartFilters
		Version: 2.3.14
		Author: Crocoblock

	Quantity Plus Minus Button for WooCommerce
		Version: 1.1.1
		Author: CodeAstrology

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WooCommerce Payments
		Version: 4.7.2
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

	WP Cerber Security, Anti-spam & Malware Scan
		Version: 9.0
		Author: Cerber Tech Inc.

== Utilisation des éléments ==
	
	archive : 1
		button : 1
		heading : 1
		jet-smart-filters-checkboxes : 2
		jet-smart-filters-color-image : 1
		jet-smart-filters-range : 1
		text-editor : 2
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-archive-description : 1
		woocommerce-breadcrumb : 1
	footer : 1
		accordion : 1
		divider : 1
		heading : 4
		image : 1
		nav-menu : 4
		social-icons : 1
		text-editor : 2
	header : 1
		html : 1
		nav-menu : 2
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	product : 1
		accordion : 1
		heading : 2
		shortcode : 1
		text-editor : 3
		wc-add-to-cart : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-products : 2
	section : 2
		html : 2
	wp-post : 0
		image : 1
		nav-menu : 1
	single-page : 19
		accordion : 4
		button : 12
		form : 4
		heading : 49
		html : 17
		image : 11
		image-box : 20
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-color-image : 1
		login : 1
		reviews : 1
		search-form : 1
		spacer : 1
		text-editor : 43
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-products : 3
		woocommerce-purchase-summary : 1
	product-archive : 2
		button : 2
		heading : 3
		html : 1
		jet-smart-filters-checkboxes : 4
		jet-smart-filters-color-image : 2
		jet-smart-filters-range : 2
		text-editor : 5
		theme-archive-title : 1
		wc-archive-products : 2
		woocommerce-archive-description : 1
		woocommerce-breadcrumb : 2
	error-404 : 1
		button : 1
		heading : 1
		image : 1
		text-editor : 1

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	En-tête et pied de page du thème Hello: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Envois de formulaire: Actif par défaut
	Scroll Snap: Actif par défaut

== Journal ==
	
PHP: showing 10 of 10PHP: 2022-08-01 12:46:19 [notice X 47][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-01 15:53:39 [notice X 1][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-01 16:12:58 [notice X 2328][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-03 10:00:41 [notice X 1][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-03 14:49:25 [error X 1][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home2/dbfw4094/beta.terroirgaulois.fr/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home2/dbfw4094/beta.terroirgaulois.fr/wp-includes/class-wp-hook.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-05 08:54:20 [notice X 1303][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-05 08:54:23 [notice X 54][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-05 08:54:23 [notice X 54][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-12 08:43:54 [notice X 46][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-12 08:43:54 [notice X 46][/home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home2/dbfw4094/beta.terroirgaulois.fr/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]

JS: showing 2 of 2JS: 2022-08-02 13:39:17 [error X 3][https://beta.terroirgaulois.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.8:3:900529] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-08-05 10:06:38 [error X 1][https://beta.terroirgaulois.fr/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4305\") has already been destroyed and cannot be used. 

Log: showing 20 of 302022-09-12 09:37:17 [info] elementor-pro::elementor_pro_updater Started 
2022-09-12 09:37:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-12 09:37:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-12 09:37:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.5',
)]
2022-09-12 09:37:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.7.5',
)]
2022-09-16 18:45:52 [info] elementor-pro::elementor_pro_updater Started 
2022-09-16 18:45:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-16 18:45:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-16 18:45:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-16 18:45:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-24 00:52:10 [info] elementor-pro::elementor_pro_updater Started 
2022-09-24 00:52:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-24 00:52:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-24 00:52:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-24 00:52:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-27 14:04:22 [info] elementor::elementor_updater Started 
2022-09-27 14:04:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-27 14:04:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-09-27 14:04:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-27 14:04:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @JGaulois,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
