### ISSUE TITLE
🔗 🐞 Bug Report: Additional Breakpoints - Global Fonts styles are not applied on non-desktop devices (Related to #19924) (ED-8329)

### ISSUE THREAD

**Issue by choijun** [elementor/elementor#19930]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The global fonts does not work properly on backend, it's does not work when editing on breakpoints ( External link https://screencast-o-matic.com/watch/c3Quf4VORLj )

https://user-images.githubusercontent.com/6446727/192689643-c0f63188-8342-4087-91f0-15c05ab327b7.mp4

### Steps to reproduce

1) Go to Site Settings -> Global Fonts and add custom fonts with name is Test Global Fonts ) then add font size for each breakpoints 
2) Go back to editor then add custom heading element, go to Style Tab and apply global font for this element

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.46 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 7.4.21
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://localhost/theme-upgrade/veres
	Home URL: http://localhost/theme-upgrade/veres
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: dpv.0990@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.7
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @choijun! 

Thank you for submitting your report! 🙏 

We will look into your issue.

Best regards

(Related to #19924 )

**Comment by choijun** [comment]
Hi @nicholaszein ,

Thanks for your review, this feature is essential in setting up templates and hope this will be solve soon.

Best Regards,
Jun

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!
