### ISSUE TITLE
✔️ 🐞 Bug Report: [v3.8-Beta] Loop Builder - Provide a way to add Dynamic Content via Dynamic tags (ED-8210)

### ISSUE THREAD

**Issue by PatIsGay** [elementor/elementor#19932]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I created a custom post type, called gw products.
I created the loop item and added the Featured Image Widget AND a Container using the Featured Image as Background via the Dynamic Content function.

![image](https://user-images.githubusercontent.com/16137678/192717170-e8b9a26e-66c4-4aeb-9189-8a0306727966.png)

On the Live Page the Featured Image Widget(also Post Title, Post Content,) work fine and pull the right image for each item. 
The way using the dynamic content doesn't work properly, it pulls the featured image of the first item for all loop items inside the grid.

![image](https://user-images.githubusercontent.com/16137678/192717247-e0b3a45c-7d87-41f1-8d52-71e84fed545d.png)

These are my Specs:
![image](https://user-images.githubusercontent.com/16137678/192716942-67b338a9-2fb3-4f02-b20b-8f3148beb5c4.png)

Using Wordpress 6.0.2

### Steps to reproduce

1.) Create Custom Post Type
2.) Set up at least 2 Objects in the CPT
3.) Create Loop Item and create a Container there and set its Background source to 'Featured Image'. 
4.) Create Loop Grid and load the Loop item there

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.16
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://staging.gewena.com
	Home URL: http://staging.gewena.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: tobi.nickolai@googlemail.com
	Debug Mode: Inactive

== Theme ==
	Name: Architecturer Child
	Version: 1.0
	Author: ThemeGoods
	Child Theme: Yes
	Parent Theme Name: Architecturer
	Parent Theme Version: 3.7.8
	Parent Theme Author: ThemeGoods

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	ACF Photo Gallery Field
		Version: 1.8.0
		Author: Navneil Naicker

	Advanced Custom Fields
		Version: 6.0.0
		Author: WP Engine

	Antispam Bee
		Version: 2.11.1
		Author: pluginkollektiv

	Architecturer Theme Elements for Elementor
		Version: 3.4.5
		Author: ThemGoods

	BEAF - Ultimate Before After Image Slider & Gallery
		Version: 4.3.3
		Author: Themefic

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Custom Fonts
		Version: 1.3.7
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Elementor
		Version: 3.9.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Google Map Extended
		Version: 1.2.3
		Author: InternetCSS

	Elementor Pro
		Version: 3.9.0-dev1
		Author: Elementor.com

	Envato Market
		Version: 2.0.7
		Author: Envato

	Folders
		Version: 2.8.5
		Author: Premio

	Instant Images
		Version: 4.6.2
		Author: Darren Cooney

	LoftLoader
		Version: 2.3.8
		Author: Loft.Ocean

	MC4WP: Mailchimp for WordPress
		Version: 4.8.10
		Author: ibericode

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Smush
		Version: 3.11.1
		Author: WPMU DEV

	Typing Effect
		Version: 1.3.6
		Author: 93digital

	UpdraftPlus - Backup/Restore
		Version: 1.22.22
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

	WP Reset
		Version: 1.95
		Author: WebFactory Ltd

	ZM Ajax Login & Register
		Version: 2.0.2
		Author: Zane Matthew

== Elemente Verwendung ==
	
	container : 1
		button : 7
		container : 1
		html : 1
	header : 3
		architecturer-navigation-menu : 6
		architecturer-search : 3
		html : 2
		icon : 3
		image : 3
	loop : 0
		post-info : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-post : 0
		accordion : 4
		architecturer-background-list : 8
		architecturer-distortion-grid : 1
		architecturer-horizontal-timeline : 10
		architecturer-portfolio-classic : 9
		architecturer-portfolio-grid : 1
		architecturer-portfolio-masonry : 4
		architecturer-portfolio-timeline : 1
		architecturer-portfolio-timeline-vertical : 2
		architecturer-slider-animated : 2
		architecturer-slider-fadeup : 5
		architecturer-slider-image-carousel : 2
		architecturer-slider-motion-reveal : 2
		architecturer-slider-parallax : 2
		architecturer-testimonial-card : 2
		button : 21
		counter : 20
		divider : 8
		eb-google-map-extended : 3
		heading : 201
		html : 2
		image : 182
		photographer-blog-posts : 13
		photographer-gallery-fullscreen : 1
		photographer-gallery-grid : 2
		photographer-gallery-horizontal : 7
		photographer-gallery-justified : 2
		photographer-gallery-masonry : 2
		photographer-gallery-preview : 1
		photographer-slider-animated-frame : 1
		photographer-slider-clip-path : 1
		photographer-slider-flip : 1
		photographer-slider-horizontal : 1
		photographer-slider-multi-layouts : 1
		photographer-slider-popout : 1
		photographer-slider-property-clip : 2
		photographer-slider-room : 3
		photographer-slider-slice : 3
		photographer-slider-split-carousel : 1
		photographer-slider-split-slick : 1
		photographer-slider-transitions : 1
		photographer-slider-velo : 1
		photographer-slider-vertical-parallax : 1
		shortcode : 13
		spacer : 4
		text-editor : 296
	wp-page : 85
		architecturer-animated-headline : 1
		architecturer-animated-text : 17
		architecturer-distortion-grid : 1
		architecturer-slider-animated : 1
		architecturer-slider-synchronized-carousel : 1
		button : 8
		container : 2
		divider : 11
		ele-loop-item : 1
		heading : 19
		html : 2
		image : 12
		loop-grid : 6
		photographer-blog-posts : 1
		portfolio : 1
		posts : 1
		spacer : 6
		text-editor : 7
	single-post : 1
		animated-headline : 1
		architecturer-animated-headline : 2
		architecturer-animated-text : 3
		architecturer-navigation-menu : 4
		architecturer-search : 2
		heading : 3
		html : 1
		icon : 2
		image : 4
		image-carousel : 1
		post-info : 1
		spacer : 1
		theme-post-content : 1
		video : 1
	single-page : 3
		animated-headline : 1
		architecturer-animated-text : 3
		image : 3
		post-info : 2
		spacer : 2
		theme-post-content : 1
	loop-item : 2
		container : 2
		heading : 1
		image : 1
		post-info : 1
		theme-post-content : 1
		theme-post-featured-image : 1

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Aktiv
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	Import Export Website Kit: Standardmäßig aktiviert
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig aktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Farbpalette: Standardmäßig aktiviert
	Bevorzugte Widgets: Standardmäßig aktiviert
	Admin Leiste: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert

== Protokoll ==
	
JS: showing 8 of 8JS: 2022-09-09 11:26:21 [error X 15][http://staging.gewena.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Swiper is not defined 
JS: 2022-09-16 13:36:09 [error X 3][http://staging.gewena.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.5:3:646945] this.model.isValidChild is not a function 
JS: 2022-09-19 20:03:28 [error X 6][http://staging.gewena.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.5:3:1060720] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-20 14:54:24 [error X 2][http://staging.gewena.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:873775] elementorFrontend is not defined 
JS: 2022-09-25 13:35:06 [error X 1][http://staging.gewena.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:767341] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-09-26 07:34:23 [error X 1][http://staging.gewena.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:692080] T.getContainer is not a function 
JS: 2022-09-26 12:12:34 [error X 3][http://staging.gewena.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.9.0-dev1:3:98898] Cannot convert undefined or null to object 
JS: 2022-09-26 16:38:06 [error X 2][http://staging.gewena.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:288219] Cannot read properties of undefined (reading \'id\') 

Log: showing 20 of 272022-09-20 12:26:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-20 12:26:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-25 14:27:37 [info] elementor::elementor_updater Started 
2022-09-25 14:27:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-25 14:27:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-25 14:27:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-25 14:27:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-26 10:27:27 [info] elementor-pro::elementor_pro_updater Started 
2022-09-26 10:27:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-26 10:27:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-26 10:27:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-26 10:27:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-26 10:27:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-26 13:27:24 [info] elementor::elementor_updater Started 
2022-09-26 13:27:24 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-26 13:27:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-09-26 13:27:25 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-26 13:27:25 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-09-26 13:27:25 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-09-26 13:27:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]

PHP: showing 8 of 8PHP: 2022-09-14 20:07:32 [warning X 1][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/uploads/elementor/css/post-7.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-20 12:21:44 [notice X 1][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-20 12:26:35 [notice X 52][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-20 14:35:26 [notice X 46][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 14:53:27 [notice X 133][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/includes/widgets/video.php::1200] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-26 13:33:29 [notice X 10][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-09-26 14:10:38 [notice X 1][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /www/htdocs/w00ecfe2/staging.gewena.com/wp-includes/rest-api/class-wp-rest-server.php(1143): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2022-09-27 14:24:55 [notice X 1][/www/htdocs/w00ecfe2/staging.gewena.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Architecturer Theme Elements for Elementor: Die Kompatibilität ist nicht angegeben
	Elementor Google Map Extended: Die Kompatibilität ist nicht angegeben
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==

**Comment by PatIsGay** [comment]
Hey there,

Amazing! I didn't expect that.
Great to see how fast you guys are working on that. Love it.

My best regards,
Tobi Nickolai

Nicholas Zein ***@***.***> schrieb am Mi., 28. Sept. 2022,
20:10:

**Comment by nicholaszein** [comment]
Hello there @PatIsGay!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
