### ISSUE TITLE
Elementor not working

### ISSUE THREAD

**Issue by Troystarz** [elementor/elementor#19942]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

i normally use elementor to make changes to my website but since lately its not showing at the up of my web page so i can use it to make edits 

### Steps to reproduce

i am not sure

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

not sure

**Comment by nicholaszein** [comment]
Hello @Troystarz ,

Thanks for contacting us! 🙏 

Please refer to this article: https://elementor.com/help/the-edit-with-elementor-link-has-disappeared/

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** only, and should not be used for support. ⚠️ 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards
