### ISSUE TITLE
🐞 Bug Report: Container background image position not working on mobile (Duplicate of #19894)

### ISSUE THREAD

**Issue by drmmanzi** [elementor/elementor#19950]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Flexbox container, background image, style > attachment: fixed, position in mobile top center.
The image in editing is displayed correct, in smartphone is displayed aligned to left.

### Steps to reproduce

1) Flexbox container, 
2) background image, 
3) style > attachment: fixed, 
4) position in mobile top center.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 8.1.10
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://www.maxxwebdeveloper.cloud
	Home URL: https://www.maxxwebdeveloper.cloud
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: maxxwebdeveloper@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Aruba HiSpeed Cache
		Version: 1.2.0
		Author: Aruba.it

	Elementor
		Version: 3.9.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Wordfence Security
		Version: 7.6.2
		Author: Wordfence

== Elements Usage ==
	
	page : 1
		heading : 4
		progress : 1
		social-icons : 1
		spacer : 1
	wp-page : 1
		button : 3
		container : 24
		heading : 8
		icon-box : 4
		icon-list : 1
		image : 2
		image-box : 3
		menu-anchor : 3
		social-icons : 1
		spacer : 2
		text-editor : 3
		toggle : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 8 of 82022-09-27 11:34:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-09-27 11:34:16 [info] elementor::elementor_updater Started 
2022-09-27 11:34:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-27 11:34:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-27 11:34:16 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-09-27 11:34:16 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-09-27 11:34:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-09-27 11:34:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @drmmanzi! 

Thank you for submitting your issue! 🙏 

Please allow me some time to investigate it, and get back to you with my findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @drmmanzi,

I can confirm this is a bug, and we are already working on a fix to be released in the upcoming patch version. This issue is related to a few other issues on the same subject, and I'll be closing this issue so we can continue the discussion there  #19894.

If you need it to work right now, you can use the built-in rollback feature or simply [download this file](https://downloads.wordpress.org/plugin/elementor.3.7.6.zip) and upload it as a plugin to your website. It will ask you if you want to replace Elementor v3.7.7 with v3.7.6. Just click to replace it and everything should be back to normal.

Sorry for the inconvenience and thanks for your patience and time spent reporting this issue.

Kind regards,

Nick
