### ISSUE TITLE
Update Replace URL UI

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#19955]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The current Replace URL UI is an inline design and makes it hard to see the whole URL address.

Expanding the input fields to match the UI from the Integrations tab would be ideal.

### Describe the solution you'd like

Match the UI design from the Integrations section. 

### Describe alternatives you've considered

Here's a mockup of how the new Replace URL section could look like:

![Elementor-URL-Replace-Update](https://user-images.githubusercontent.com/7768009/193122698-be1a24cc-1fc3-4348-8348-4357a7a63df5.jpg)

**Comment by arielk** [comment]
Fixed in v3.8: https://github.com/elementor/elementor/pull/19565/commits/ab8f01aa71ca5d3c16c269860c9559743150b014

Duplicate: https://github.com/elementor/elementor/issues/19559

**Comment by arielk** [comment]
Hi @bkjproductions,

Maybe I wasn't clear enough. The topic is closed because it is merged into the next version as a patch (v3.8.0 Beta). In the coming days we will release it to everyone.

Thanks for the feedback!

**Comment by bkjproductions** [comment]
@airelk, thanks!
