### ISSUE TITLE
⌛ Awaiting User Feedback: Tag or style current page/post in Posts widget

### ISSUE THREAD

**Issue by ShadowXVII** [elementor/elementor#19967]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

A posts list used for navigation can't be used to indicate the current page the user is on.

In standard Wordpress, the current page is bolded to style it differently to other pages.

### Describe the solution you'd like

Styling specifically for the "current page" (font weight) the user is on.
OR
CSS tag of current_page so styling can be applied to the current page.

### Describe alternatives you've considered

Using another plugin to list pages for navigation.

**Comment by nicholaszein** [comment]
Hello @ShadowXVII!

Thank you for submitting your issue! 🙏 

Can you clarify if you're talking about [this widget](https://elementor.com/help/posts-widget-pro/)? If you are, it shouldn't be used to do what you're trying to do. Posts widgets are not meant to be used for navigation.

Your post is missing information. Please show us examples of what you're trying to achieve, and with which widgets. 

Thanks

**Comment by ShadowXVII** [comment]
> Hello @ShadowXVII!
> 
> Thank you for submitting your issue! 🙏 
> 
> Can you clarify if you're talking about [this widget](https://elementor.com/help/posts-widget-pro/)? If you are, it shouldn't be used to do what you're trying to do. Posts widgets are not meant to be used for navigation.
> 
> Your post is missing information. Please show us examples of what you're trying to achieve, and with which widgets. 
> 
> Thanks

Hi

Yes, I am. There's no other suitable widget to show a list of pages from a custom query (in this case siblings). Simply want a list of sub pages, with the current page highlighted.

Would be happy to hear an alternative.

Regards
Jake

**Comment by nicholaszein** [comment]
@ShadowXVII have you tried the [Sitemap widget](https://elementor.com/help/sitemap-widget-pro/)?

Either way, the Nav Menu widget is the one that will highlight the current page. If you want to highlight specific pages you're going to have to use custom CSS to target the current post-id (it's a class inside the `<body>` tag), and the item in your Posts or Sitemap widget.

About your request: While it is an excellent suggestion, we are unable to prioritize it at this time. 😕 

If you decide to take it upon yourself to write your own solution, we would be happy to adopt it after reviewing the code. 😉 

Take care!

**Comment by ShadowXVII** [comment]
@nicholaszein 

Sitemap doesn't support:
- Queries OR Siblings
- Current page highlight

Glad I pay elementor pro! Nothing ever gets prioritised 🙄.

**Comment by nicholaszein** [comment]
Hello @ShadowXVII,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
