### ISSUE TITLE
elementor ignores wp date and time format

### ISSUE THREAD

**Issue by uselessgames** [elementor/elementor#19976]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

elementor pro ignores the wordpress site date and time format requiring more scripts that potentially slow down page load. (i know 1 script doesnt slow down, but adding many does and this is just one more)

### Steps to reproduce

1. go to wp settings > general and modify date time settings. 
![image](https://user-images.githubusercontent.com/66875544/193626098-b5d79fc8-1683-4b88-8b18-9eda496bfb86.png)
2. create a post or page with date / time on it . 
3. see the date /  time is ignored.
![image](https://user-images.githubusercontent.com/66875544/193626804-6119403a-bb72-45ac-a6b6-099522ba70b8.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

n/a

**Comment by nicholaszein** [comment]
Hey @uselessgames , 

Thank you for the feedback. 🙏 

While reviewing your report, we noticed it was missing some key pieces of information.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

⚠️ This report is missing key information: 

* Steps to replicate: Is it a Single Template created with Elementor Theme Builder? What are the elements you're using to show the date?
* Isolating the problem: make sure you tested with Hello Elementor.
* System info: Without this information, we can't replicate your issue or find possible conflicts.

Without them, we simply can't help. 😕 

👍 Please feel free to open a new issue in accordance with these guidelines.

Best regards,

Nick
