### ISSUE TITLE
500 Intrnal server error

### ISSUE THREAD

**Issue by Rafail1975** [elementor/elementor#19977]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I can no longer edit pages with Elemento. After I edit an element, the error message "Server erros (500 internal server error) appears. And I don't know where the error comes from

The capacity of the server on which WP with the TEKNOLAB theme is installed is as follows: disk 30 GB, MySQL® Disk Usage 27.06 GB, Physical Memory Usage 3 GB, CPU: 6Ghz

### Steps to reproduce

![image](https://user-images.githubusercontent.com/114944108/193648986-0bce94c5-9bf4-4be8-85d1-47cfc3d66514.png)
![image](https://user-images.githubusercontent.com/114944108/193649073-87e2a06c-789d-4fde-8a1a-71fef8cbbebd.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.39
	PHP Version: 8.1.10
	PHP Memory Limit: 32M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://www.digicont.ro
	Home URL: https://www.digicont.ro
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: office.novacont@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Teknolab
	Version: 1.0.8
	Author: RS Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.9.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Envato Market
		Version: 2.0.7
		Author: Envato

	Extendify
		Version: 0.10.2
		Author: Extendify

	Hello Dolly
		Version: 1.7.2
		Author: Matt Mullenweg

	Limit Login Attempts Reloaded
		Version: 2.25.5
		Author: Limit Login Attempts Reloaded

	MC4WP: Mailchimp for WordPress
		Version: 4.8.10
		Author: ibericode

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	RSElements
		Version: 1.0.2
		Author: rs-theme

	RS Framework
		Version: 1.0
		Author: RS Theme

	RSS Importer
		Version: 0.2
		Author: wordpressdotorg

	Slider Revolution
		Version: 6.5.31
		Author: ThemePunch

	Template Library and Redux Framework
		Version: 4.3.19
		Author: Extendify

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WooCommerce Payments
		Version: 4.8.0
		Author: Automattic

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.7.7
		Author: WPForms

	Yoast SEO
		Version: 19.7.1
		Author: Team Yoast

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Elements Usage ==
	
	page : 7
		container : 1
		google_maps : 2
		image : 11
		portfolio-slider : 2
		rs-accordions : 1
		rs-button : 10
		rs-cf7 : 4
		rs-contact-box : 4
		rs-counter : 10
		rs-featurebox : 12
		rs-heading : 46
		rs-image : 2
		rs-image-hover : 10
		rs-image-shabe-animation-effect : 4
		rs-logo : 8
		rs-progress : 11
		rs-rain-animates : 4
		rs-service-grid : 49
		rs-testimonial-slider : 4
		rs-video : 1
		rsblog-slider : 4
		rsfeatureslist : 5
		rsportfolio-filter : 1
		rsprice : 6
		rsteam-slider : 1
		slider_revolution : 1
		text-editor : 1
	section : 3
		rs-heading : 2
		rs-service-grid : 12
	wp-post : 0
		image : 6
		rs-image : 3
		rs-service-grid : 1
		text-editor : 6
	wp-page : 41
		container : 1
		google_maps : 1
		heading : 15
		html : 4
		image : 52
		portfolio-slider : 4
		rs-accordions : 3
		rs-apps-screenshots : 2
		rs-button : 39
		rs-cf7 : 16
		rs-contact-box : 20
		rs-counter : 40
		rs-dual-button : 2
		rs-featurebox : 18
		rs-heading : 198
		rs-image : 26
		rs-image-hover : 22
		rs-image-shabe-animation-effect : 5
		rs-logo : 22
		rs-progress : 62
		rs-rain-animates : 4
		rs-service-grid : 140
		rs-testimonial-slider : 14
		rs-video : 2
		rsblog-slider : 12
		rsfeatureslist : 25
		rsportfolio : 7
		rsportfolio-filter : 4
		rsprice : 46
		rsteam : 4
		rsteam-slider : 6
		sidebar : 3
		slider_revolution : 2
		spacer : 1
		testimonial : 3
		text-editor : 14

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active

== Log ==
	
PHP: showing 20 of 24PHP: 2022-09-19 11:26:50 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/data/v2/manager.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-19 11:26:50 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/kits/documents/tabs/settings-background.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-19 11:38:17 [notice X 5][/home/digicont/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 05:14:46 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/core/files/css/base.php::738] Uncaught TypeError: Argument 1 passed to Elementor\Core\Files\CSS\Base::get_style_control_value() must be of the type array, null given, called in /home/digicont/public_html/wp-content/plugins/elementor/core/files/css/base.php on line 682 and defined in /home/digicont/public_html/wp-content/plugins/elementor/core/files/css/base.php:738
Stack trace:
#0 /home/digicont/public_html/wp-content/plugins/elementor/core/files/css/base.php(682): Elementor\Core\Files\CSS\Base->get_style_control_value(NULL, Array)
#1 [internal function]: Elementor\Core\Files\CSS\Base->Elementor\Core\Files\CSS\{closure}(NULL)
#2 /home/digicont/public_html/wp-content/plugins/elementor/core/files/css/base.php(448): call_user_func(Object(Closure), NULL)
#3 /home/digicont/public_html/wp-content/plugins/elementor/core/files/css/base.php(347): Elementor\Core\Files\CSS\Base->parse_property_placeholder(NULL, Array, Array, Object(Closure), 'SIZE', 'media_offset_x_...')
#4 [internal function]: Elementor\Core\Files\CSS\Base->Elementor\Core\Files\CSS [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 00:03:34 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/files/file-types/svg.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 00:13:46 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor//includes/controls/section.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 00:23:46 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/schemes/color-picker.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 00:32:07 [notice X 42][/home/digicont/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1565] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 00:43:05 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/role-manager/role-manager.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 02:54:13 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor//includes/controls/groups/background.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 02:54:34 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/kits/documents/tabs/global-colors.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 02:55:48 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/base/background-process/wp-async-request.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 14:53:10 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/settings/page/manager.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 14:56:42 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/managers/widgets.php::88] Uncaught Error: Class 'Elementor\Widget_image_gallery' not found in /home/digicont/public_html/wp-content/plugins/elementor/includes/managers/widgets.php:88
Stack trace:
#0 /home/digicont/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(310): Elementor\Widgets_Manager->init_widgets()
#1 /home/digicont/public_html/wp-content/plugins/elementor/includes/managers/elements.php(74): Elementor\Widgets_Manager->get_widget_types('rs-heading')
#2 /home/digicont/public_html/wp-content/plugins/elementor/core/base/document.php(286): Elementor\Elements_Manager->create_element_instance(Array)
#3 /home/digicont/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(426): Elementor\Core\Base\Document->render_element(Array)
#4 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 /home/digicont/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Eleme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-22 14:56:56 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/modules/page-templates/module.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 19:14:16 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/base/document.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 19:14:59 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/core/schemes/color.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 19:15:04 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor/includes/widgets/traits/button-trait.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-23 19:16:39 [error X 1][/home/digicont/public_html/wp-content/plugins/elementor/includes/autoloader.php::267] require(): Failed opening required '/home/digicont/public_html/wp-content/plugins/elementor//includes/controls/dimensions.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-03 16:06:02 [warning X 6][/home/digicont/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::1565] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 14 of 142022-09-20 15:18:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-09-20 15:18:44 [info] elementor::elementor_updater Started 
2022-09-20 15:18:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-20 15:18:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-20 15:18:44 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-09-20 15:18:44 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-09-20 15:18:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-10-03 17:47:08 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2022-10-03 17:47:10 [info] elementor::custom_task_manger Started 
2022-10-03 17:47:10 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2022-10-03 17:47:11 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2022-10-03 17:47:11 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2022-10-03 17:47:11 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2022-10-03 17:47:11 [info] elementor::custom_task_manger Completed 

JS: showing 4 of 4JS: 2022-09-22 00:45:09 [error X 1][https://www.digicont.ro/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:20460] Cannot read properties of undefined (reading \'id\') 
JS: 2022-09-22 02:34:24 [error X 1][https://www.digicont.ro/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:768903] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-09-22 19:15:49 [error X 1][https://www.digicont.ro/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:1061493] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-23 22:23:52 [error X 3][https://www.digicont.ro/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.9.0-dev1:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `link` value. Expected array or object.',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @Rafail1975,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. But I'll try to help.

It seems your server does not have enough allocated memory for your website. The [minimum recommended system requirements](https://elementor.com/help/requirements/) are **128M** of memory allocated to your website. Your website is pointing to having _**only 32M**_.

Please make sure to contact your hosting provider and ask for an increase in memory.

### ⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** , and should not be used for support. 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards,

Nick
