### ISSUE TITLE
🚀 Feature Request: Dynamic dots for slides & all carousels

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19987]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add dynamic dots feature for carousels if possible.

### Describe the solution you'd like

https://user-images.githubusercontent.com/77163248/192760418-722aab8f-17c1-4476-b7b8-e99b1ece5e70.mp4

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

Thank you for contacting us about this issue. 🙏 

While it is an excellent suggestion, we are unable to prioritize it at this time. 😕 

If you decide to take it upon yourself to write your own solution, we would be happy to adopt it after reviewing the code. 😉 

Take care!
