### ISSUE TITLE
🚀 Feature Request: Form - Improve email formatting for rendered fields

### ISSUE THREAD

**Issue by innoforce-dev** [elementor/elementor#19989]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

We've got a multipage form that is sent via email. The person processing the emails is frustrated that the content is poorly formatted. All field below each other, no sparators, etc

### Describe the solution you'd like

Make the labels-text bold font. 
Add a empty line before field of a new page.

**Comment by nicholaszein** [comment]
Hi @innoforce-dev,

Thank you for contacting us about this issue. 🙏 

While it is an excellent suggestion, we are unable to prioritize it at this time. 😕 

You can however add your own formatting using HTML inside the e-mail message if you want. The `email` and `email2` _Actions after Submit_ accept normal HTML tags, including `<style>`, `<strong>`, and any other HTML5 valid tag. You can learn more about these actions [here](https://elementor.com/help/actions-after-submit/). This allows users to decide how they can format the e-mails without Elementor affecting the design. It's up to you to format the e-mails however you'd like! 😉 

If you decide to take it upon yourself to write your own solution, we would be happy to adopt it after reviewing the code. 😉 

Take care!
