### ISSUE TITLE
ACF not renedring on Site but are in Template Design  3.90 Dev2

### ISSUE THREAD

**Issue by jamboort** [elementor/elementor#19985]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a few ACF linked Elementor widgets on an Elementor Single Product page an HTML, Image, and Text Edit they were all working OK I could see them in the designer and on the site page. When I updated to 3.90 Dev 2 from Dev 1 they no longer were visible on the site but they were still visible in the designer. it is like the site can not get the data from the DB.

### Steps to reproduce

1 create a Single Product page
2 add a text or HTML control
3 link the content to an ACF field and key, 
4 view the page

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.23
	PHP Memory Limit: -1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://linkwave-support.co.uk
	Home URL: https://linkwave-support.co.uk
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: -1
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: andrew.newton@linkwave.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Popularis Business
	Version: 1.0.1
	Author: Themes4WP
	Child Theme: Yes
	Parent Theme Name: Popularis
	Parent Theme Version: 1.0.13
	Parent Theme Author: Themes4WP

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	ACF: Better Search
		Version: 4.0.1
		Author: Mateusz Gbiorczyk

	Advanced Custom Fields
		Version: 6.0.2
		Author: WP Engine

	Advanced Woo Search PRO
		Version: 2.64
		Author: ILLID

	CartFlows
		Version: 1.11.1
		Author: CartFlows Inc

	Checkout Plugins - Stripe for WooCommerce
		Version: 1.4.6
		Author: Checkout Plugins

	Collapse-O-Matic
		Version: 1.8.2
		Author: twinpictures, baden03

	CookieYes | GDPR Cookie Consent
		Version: 3.0.2
		Author: CookieYes

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Depicter
		Version: 1.3.3
		Author: Averta

	Dynamic Visibility for Elementor
		Version: 5.0.1
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.9.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev2
		Author: Elementor.com

	Filter Everything — WooCoomerce Product & WordPress Filter
		Version: 1.7.1
		Author: Andrii Stepasiuk

	Google Listings and Ads
		Version: 2.1.4
		Author: WooCommerce

	Gutenberg Block for WooCommerce Product Table
		Version: 1.0.6
		Author: Barn2 Plugins

	ImageMagick Engine
		Version: 1.7.4
		Author: Orangelab

	Jetpack
		Version: 11.3.2
		Author: Automattic

	MailPoet
		Version: 3.100.0
		Author: MailPoet

	One Time Login
		Version: 0.3.1
		Author: Daniel Bachhuber

	Order Minimum/Maximum Amount for WooCommerce
		Version: 4.2.2
		Author: WPFactory

	Popularis Extra
		Version: 1.2.0
		Author: Themes4WP

	Popularis PRO
		Version: 1.7.0
		Author: PopularisWP

	Search & Filter
		Version: 1.2.15
		Author: Code Amp

	Search & Filter Pro
		Version: 2.5.13
		Author: Code Amp

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WooCommerce Blocks
		Version: 8.6.0
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.19
		Author: CartFlows Inc

	WooCommerce Payments
		Version: 4.8.0
		Author: Automattic

	WooCommerce Product Documents
		Version: 1.13.1
		Author: SkyVerge

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

== Elements Usage ==
	
	archive : 6
		archive-posts : 2
		heading : 8
		image : 2
		spacer : 4
		template : 3
		text-editor : 3
		uael-posts : 1
	custom_grid : 2
		archive-posts : 1
		heading : 2
		posts : 1
		share-buttons : 1
	footer : 1
		heading : 3
		icon-list : 2
		image : 1
		social-icons : 1
		text-editor : 3
	header : 1
		nav-menu : 1
		theme-site-logo : 1
		twp-pro-search : 1
		woocommerce-menu-cart : 1
	loop : 3
		button : 2
		container : 1
		heading : 1
		loop-grid : 1
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 1
	page : 12
		button : 7
		counter : 4
		divider : 6
		heading : 48
		icon : 1
		icon-box : 10
		icon-list : 6
		image : 3
		popularis-extra-posts : 1
		social-icons : 3
		text-editor : 27
		toggle : 1
	popup : 3
		heading : 6
		text-editor : 2
		uael-table : 2
	product : 2
		button : 6
		container : 2
		form : 2
		heading : 31
		html : 1
		image : 8
		shortcode : 2
		spacer : 1
		text-editor : 11
		uael-woo-products : 1
		woocommerce-breadcrumb : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-additional-information : 2
		woocommerce-product-content : 2
		woocommerce-product-images : 2
		woocommerce-product-meta : 2
		woocommerce-product-price : 2
		woocommerce-product-title : 2
		woocommerce-product-upsell : 1
		woocommerce-products : 1
	section : 16
		aws : 1
		button : 5
		flip-box : 5
		form : 2
		heading : 31
		icon-box : 7
		icon-list : 2
		image : 8
		image-box : 5
		popularis-text-block : 1
		posts : 1
		social-icons : 1
		spacer : 1
		text-editor : 13
		twp-pro-search : 1
		uael-table : 2
	wp-post : 0
		button : 9
		divider : 6
		form : 1
		heading : 26
		icon-box : 10
		icon-list : 14
		image : 13
		image-box : 3
		popularis-text-block : 4
		testimonial : 2
		text-editor : 9
	wp-page : 38
		aws : 4
		button : 58
		container : 3
		divider : 7
		flip-box : 19
		form : 16
		google_maps : 1
		heading : 261
		html : 1
		icon : 14
		icon-box : 5
		icon-list : 9
		image : 101
		image-box : 1
		popularis-text-block : 1
		posts : 1
		shortcode : 2
		social-icons : 2
		spacer : 138
		tabs : 1
		text-editor : 145
		toggle : 1
		uael-posts : 2
		uael-woo-products : 5
		video : 2
		woocommerce-cart : 1
	single-post : 3
		button : 6
		divider : 8
		heading : 12
		icon : 2
		icon-list : 1
		image : 3
		post-navigation : 1
		share-buttons : 1
		spacer : 8
		template : 1
		text-editor : 15
		theme-post-content : 1
		theme-post-featured-image : 2
		theme-post-title : 2
	search-results : 5
		archive-posts : 1
		aws : 1
		heading : 20
		image : 3
		posts : 15
		spacer : 5
		text-editor : 1
		theme-archive-title : 1
	product-archive : 9
		aws : 9
		button : 27
		flip-box : 39
		form : 9
		heading : 99
		image : 27
		shortcode : 1
		spacer : 10
		text-editor : 45
		uael-woo-products : 9
		woocommerce-breadcrumb : 9
		wp-widget-woocommerce_layered_nav_filters : 1
	loop-item : 2
		button : 2
		container : 4
		icon-box : 1
		text-editor : 1
	error-404 : 1
		heading : 2
		icon : 1
		icon-list : 1

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Landing pages: Active
	Color Sampler: Active
	Favorite Widgets: Inactive
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Inactive
	Loop: Active
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 292022-09-28 20:05:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.7',
)]
2022-09-28 21:13:46 [info] elementor::elementor_updater Started 
2022-09-28 21:13:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-28 21:13:47 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-28 21:13:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-09-28 21:13:56 [info] elementor-pro::elementor_pro_updater Started 
2022-09-28 21:13:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-28 21:13:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-28 21:13:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-10-04 10:03:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-04 10:03:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-04 10:03:42 [info] elementor-pro::elementor_pro_updater Started 
2022-10-04 10:03:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-04 10:03:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-04 10:03:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-04 10:03:43 [info] elementor::elementor_updater Started 
2022-10-04 10:03:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-04 10:03:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-04 10:03:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-04 10:03:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]

PHP: showing 11 of 11PHP: 2022-09-28 20:21:13 [error X 9][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /homepages/35/d4296234080/htdocs/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /homepages/35/d4296234080/htdocs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /homepages/35/d4296234080/htdocs/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /homepages/35/d4296234080/htdocs/wordpress/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-28 20:35:26 [warning X 15][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-28 20:44:37 [notice X 123][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/dynamic-visibility-for-elementor/class/controls.php(48): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-29 13:02:41 [warning X 13][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-10-03 13:23:23 [warning X 2][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file():                                                                                ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 10:03:40 [notice X 1362][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 10:03:46 [notice X 560][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 10:24:27 [notice X 17][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/popularis-pro/lib/ultimate-elementor/modules/query-post/module.php(69): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-04 10:24:27 [notice X 17][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/popularis-pro/lib/ultimate-elementor/modules/control-query/module.php(315): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-04 10:24:27 [notice X 17][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/popularis-pro/lib/ultimate-elementor/modules/presets-select/module.php(102): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-04 11:30:00 [warning X 1][/homepages/35/d4296234080/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-10-01 12:30:36 [error X 2][https://linkwave-support.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:588204] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-10-04 10:47:34 [error X 1][https://linkwave-support.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:295870] Cannot read properties of undefined (reading \'html\') 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hey @jamboort, 

Thank you for the feedback. 🙏 

While reviewing your report, we noticed it was missing some key pieces of information.

#### Also, you should know that the _Elementor Developer Edition_ should not be used on production websites. This plugin is meant to be used only for testing purposes.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

⚠️ This report is missing key information: 

* Isolating the problem

Without them, we simply can't help. 😕 

👍 Please feel free to open a new issue in accordance with these guidelines.

Best regards,

Nick

**Comment by jamboort** [comment]
This site will not go live until January it is in development and we needed the dev version since your loop functionality is still not in the Pro Version

**Comment by nicholaszein** [comment]
@jamboort

You still need to isolate the problem to see if the issue is not caused by a conflict with other plugins.

I'll wait for a new issue from you.

**Comment by nicholaszein** [comment]
This issue was solved with Elementor Pro v3.8.1.

Feel free to update.

Cheers 🥂
