### ISSUE TITLE
website doesn't work, CSS is broken on the live, not logged in view. 

### ISSUE THREAD

**Issue by Ignacio4Media** [elementor/elementor#19986]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

broken live live page but looks fine on editor. 

### Steps to reproduce

publish, empty cache, reload live page. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel5.7, Revision 26 v5.7.26-29
	PHP Version: 8.0.22
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://pawgle.com
	Home URL: https://pawgle.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: allie.hylton@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.2
		Author: WP Engine

	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	Elementor
		Version: 3.7.0-dev9
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.11.16
		Author: WPVibes

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0
		Author: Elementor.com

	Flexible Checkout Fields
		Version: 3.4.2
		Author: WP Desk

	Subscriptions For WooCommerce
		Version: 1.4.4
		Author: WP Swings

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.35
		Author: Sucuri Inc.

	Ultimate Addons for Elementor
		Version: 1.36.10
		Author: Brainstorm Force

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 6.7.0
		Author: WooCommerce

== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.16.1
		Author: Rhubarb Group

	System Plugin
		Version: 4.41.1
		Author: 

== Elements Usage ==
	
	footer : 2
		heading : 5
		icon-list : 2
		social-icons : 1
	header : 2
		image : 1
		nav-menu : 2
		social-icons : 1
		theme-site-logo : 1
	page : 19
		container : 60
		form : 7
		heading : 24
		html : 5
		image : 30
		progress : 3
		spacer : 4
		text-editor : 58
		toggle : 4
		wc-add-to-cart : 8
	wp-page : 19
		container : 74
		form : 6
		heading : 24
		html : 7
		image : 36
		progress : 2
		spacer : 10
		text-editor : 88
		wc-add-to-cart : 16
		woocommerce-checkout-page : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
JS: showing 7 of 7JS: 2022-09-16 12:59:47 [error X 4][https://q0n.f51.myftpupload.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:608969] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-09-20 18:00:35 [error X 1][https://pawgle.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:571376] Cannot read properties of null (reading \'id\') 
JS: 2022-09-22 12:19:01 [error X 1][https://pawgle.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:287161] Cannot read properties of undefined (reading \'id\') 
JS: 2022-09-27 20:31:35 [error X 1][https://pawgle.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:766327] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-09-27 21:51:12 [error X 29][https://pawgle.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.9.0-dev1:3:98898] Cannot convert undefined or null to object 
JS: 2022-09-29 19:04:27 [error X 29][https://pawgle.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.9.0-dev1:2:15625] Cannot read properties of undefined (reading \'global\') 
JS: 2022-09-29 20:13:36 [error X 1][https://pawgle.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:528558] Cannot read properties of null (reading \'tagName\') 

Log: showing 20 of 232022-09-18 07:38:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-18 07:38:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-27 16:37:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-27 16:37:57 [info] elementor-pro::elementor_pro_updater Started 
2022-09-27 16:37:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-27 16:37:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-27 16:37:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-27 21:45:13 [info] elementor::elementor_updater Started 
2022-09-27 21:45:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-27 21:45:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-09-27 21:45:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-27 21:45:13 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-09-27 21:45:13 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-09-27 21:45:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-09-27 21:47:22 [info] elementor-pro::elementor_pro_updater Started 
2022-09-27 21:47:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-27 21:47:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-27 21:47:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-09-27 21:47:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev1',
)]
2022-09-28 14:43:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.7.9',
  'to' => '2.7.10',
)]

PHP: showing 12 of 12PHP: 2022-09-19 15:35:35 [error X 2][/var/www/wp-content/plugins/elementor/core/frontend/render-mode-manager.php::133] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /var/www/wp-content/plugins/elementor/core/frontend/render-mode-manager.php:133
Stack trace:
#0 /var/www/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(151): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#1 /var/www/wp-content/plugins/elementor/includes/frontend.php(192): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#2 /var/www/wp-includes/class-wp-hook.php(307): Elementor\Frontend->init_render_mode('')
#3 /var/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /var/www/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#5 /var/www/wp-includes/template-loader.php(13): do_action('template_redire...')
#6 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')
#7 /var/www/index.php(17): require('/var/www/wp-blo...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-20 17:19:49 [warning X 30][/var/www/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key "referrer" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-27 19:59:37 [notice X 1086][/var/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-09-27 20:00:14 [notice X 35][/var/www/wp-content/plugins/elementor/includes/controls/groups/base.php::497] str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-27 20:00:29 [notice X 31][/var/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::528] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-27 20:08:17 [notice X 13][/var/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-27 21:47:21 [notice X 5936][/var/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-09-27 22:00:11 [warning X 23][/var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-28 01:10:14 [notice X 2][/var/www/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-29 22:17:06 [warning X 1][/var/www/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::270] Undefined array key "post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 16:27:09 [error X 1][/var/www/wp-content/plugins/elementor-pro/modules/query-control/module.php::835] Uncaught Error: Class "ElementorPro\Modules\QueryControl\Controls\Template_Query" not found in /var/www/wp-content/plugins/elementor-pro/modules/query-control/module.php:835
Stack trace:
#0 /var/www/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\QueryControl\Module->register_controls(Object(Elementor\Controls_Manager))
#1 /var/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /var/www/wp-content/plugins/elementor/includes/managers/controls.php(476): do_action('elementor/contr...', Object(Elementor\Controls_Manager))
#4 /var/www/wp-content/plugins/elementor/includes/managers/controls.php(589): Elementor\Controls_Manager->register_controls()
#5 /var/www/wp-content/plugins/elementor/includes/managers/controls.php(608): Elementor\Controls_Manager->get_controls()
#6 /var/www/wp-content/plugins/elementor/includes/managers/controls.php(779): Elementor\Controls_Manager->get_control('section')
#7 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(421): Elementor\Controls_Manager->add_control_to_stack(Object(ElementorPro\Modules\ThemeBuilder\Documents\Single_Page), 'document_settin...', Array, Array)
#8 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1507): Elementor\Controls_Stack->add_control('document_settin...', Array)
#9 /var/www/wp-content/plugins/elementor/core/base/document.php(1644): Elementor\Controls_Stack->start_controls_section('document_settin...', Array)
#10 /var/www/wp-content/plugins/elementor/core/base/document.php(663): Elementor\Core\Base\Document->register_document_controls()
#11 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(281): Elementor\Core\Base\Document->register_controls()
#12 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-page-document.php(33): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->register_controls()
#13 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/documents/single-base.php(97): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Page_Document->register_controls()
#14 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(2310): ElementorPro\Modules\ThemeBuilder\Documents\Single_Base->register_controls()
#15 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#16 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Controls_Stack->get_stack()
#17 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(2397): Elementor\Controls_Stack->get_controls()
#18 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1107): Elementor\Controls_Stack->sanitize_settings(Array)
#19 /var/www/wp-content/plugins/elementor/includes/base/controls-stack.php(2144): Elementor\Controls_Stack->get_data('settings')
#20 /var/www/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#21 /var/www/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#22 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(149): Elementor\Core\Base\Base_Object->get_settings('page_template')
#23 /var/www/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->template_include('/var/www/wp-con...')
#24 /var/www/wp-includes/plugin.php(191): WP_Hook->apply_filters('/var/www/wp-con...', Array)
#25 /var/www/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/var/www/wp-con...')
#26 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')
#27 /var/www/index.php(17): require('/var/www/wp-blo...')
#28 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 16:32:12 [warning X 2][/var/www/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Addon Elements: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @Ignacio4Media,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. It seems you're having cache issues. 

Please follow the instructions in [this article](https://elementor.com/help/changes-dont-appear-online/). Your Object Cache plugin is the one causing your issue.

Also, I've noticed you're using the Elementor Developer Edition plugin. This plugin **SHOULD NOT BE USED ON PRODUCTION WEBSITES**. It's a plugin meant to be used by developers to **_test_** new Elementor features, but it is not stable enough to be used in production environments (live websites). Please remove the **Elementor Developer Edition** plugin and rollback Elementor to a stable version. You can follow [this article](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) to learn how to rollback.

If following the instructions above you're still experiencing this issue, here are other steps to take:

* Completely disable your performance plugin, or start changing its settings until the issue is resolved;
* Disable the **Improved CSS Loading** _Experiment_ from _Elementor > Settings > Experiments_;
* Disable the **Inline font Icons** _Experiment_ from _Elementor > Settings > Experiments_;
* Disable the active Elementor addons you have installed (you should have done this already as per our instructions);

### ⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** , and should not be used for support. 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
