### ISSUE TITLE
✔️ 🐞 Bug Report: [v3.8-Beta] Container - Padding controls not working on "column type" Containers when they have child containers. (ED-8400)

### ISSUE THREAD

**Issue by jonburdon** [elementor/elementor#19990]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When Container widgets have other Containers within them, the padding controls to not work on the parent element.

NB This is working on standard containers.

NB This bug does not occur if you build the layout yourself with containers.

NB Other layouts based on flex-wrap work fine - this only occurs when there is a next container use case.

### Steps to reproduce

1) Click the + sign to create a new section (Container)
2) Choose the layout with one large container on the left, and two vertically stacked on the right. (Third along on bottom row)
3) Select the second nested Container inside the main container. This container is the one with two containers nested within it. 
4) Try changing the padding on the parent container, it will not work. Try any value, 0px or 500px and it will not apply.
5) In custom css add selector {padding: 0px} and the padding will be set correctly

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.38
	PHP Version: 8.1.11
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://container-test.mysites.io
	Home URL: https://container-test.mysites.io
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Max Memory limit: 128M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: jon.burdon@bertagency.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

== Elements Usage ==
	
	wp-post : 0
		container : 37
		divider : 1
		heading : 18
		image : 4
		text-editor : 3

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 3 of 3PHP: 2022-10-05 11:17:11 [notice X 1][/www/wp-content/plugins/elementor/core/upgrade/manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-05 11:19:08 [notice X 81][/www/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /www/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /www/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /www/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-05 11:19:08 [notice X 23][/www/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-10-05 12:33:31 [error X 16681][https://container-test.mysites.io/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-10-05 12:33:32 [error X 249][https://container-test.mysites.io/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello there @jonburdon!

I'm just passing by to share the news! 😉  

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8.0**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
