### ISSUE TITLE
🚀 Feature Request: Forms - Limit number of submissions in total & in specific options (Duplicate of #12989)

### ISSUE THREAD

**Issue by murbeach** [elementor/elementor#19992]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

- **Case 1 limit total number of submissions:** We often have situations in which an elementor form should be limited in the total number of submissions (like simple event registration with limited space) in that cases it would be highly beneficial to have a generell setting to accept f.e. only 30 submissions 

- **Case 2 limit a specific option:** we also have often the situation, that a specific option (f.e. radio Option) should have a limitation. typical Scenario: workshop booking within a single event / or product sizes in simple order forms

### Describe the solution you'd like

Just in a nutshell

**For Case 1** 

- Field for maximum number of submissions per form
- possibility to fill this field with meta data  (f.e. ACF values of a post.)
- validation if field number is reached
- configurable action for the case when number is reached (like hiding, alternative message etc.)

**For Case 2**
_(more or less the same, but option specific within a field)_

- limitation for specific fields within the string of the option or a seperated field in advanced tab
- possibility to fill this field with meta data  (f.e. ACF values of a post.)
- validation of total number of choosen options from submissions
- configurable action for the case when number of a specific option is reached (like hiding, alternative message etc.)

### Describe alternatives you've considered

- There is an not very specific issue https://github.com/elementor/elementor/issues/12989 which has basically comparable requests
- Other form plugins like CF7, gravity, forminator (WPMU) or WPForms work, but an additional plugin is not optimal to keep the tech-stack clean. 
- We did several individual solutions for specific scenarios within elementor projects, but none of them is general enough to create a pull request out of it.

**Comment by nicholaszein** [comment]
Hello @murbeach!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #12989, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
