### ISSUE TITLE
🔗 🐞 Bug Report: Background image settings do not apply in mobile version (Duplicate of #19938, Related to #19894) (ED-8329)

### ISSUE THREAD

**Issue by Badro0** [elementor/elementor#20001]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

https://user-images.githubusercontent.com/4741856/194379985-4bfc3686-3114-4a2b-ac8c-ccf5938f290c.mp4

As you can see in the video, I have created a section with some content and a background image. I set background image settings for default size and mobile size. The preview for the mobile version is correct but when you view the page in the browser, the mobile version doesn't have the right background position (and other background settings).

### Steps to reproduce

1) Create a section with a background image
2) Set a different background position for the mobile version
3) The mobile version setting doesn't apply

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.23.1
	MySQL version: Homebrew v8.0.30
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://elementordemo.test
	Home URL: http://elementordemo.test
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: test@test.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.6
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 10 of 102022-09-19 17:59:47 [info] elementor::elementor_updater Started 
2022-09-19 17:59:47 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-19 17:59:47 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-19 17:59:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-09-19 17:59:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-10-06 16:58:52 [info] elementor::elementor_updater Started 
2022-10-06 16:58:52 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-06 16:58:52 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-06 16:58:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.8',
)]
2022-10-06 16:58:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.8',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by Badro0** [comment]
It's worth mentioning that the latest version that didn't have this issue is version 3.7.4. All versions from 3.7.5 to 3.7.8 (latest version at the moment) have this bug.

**Comment by MichaelDarko** [comment]
Same problem.

**Comment by Deadlift79** [comment]
https://github.com/elementor/elementor/issues/19861

Same issue there.

Hope will be fixed in 3.8

**Comment by Jeanseb123** [comment]
same here

**Comment by omarut** [comment]
Me too!

**Comment by nicholaszein** [comment]
Hello @XXX!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #19938 , which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

This will be solved when Elementor 3.8 is released. See: #19677 and #19883.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!
