### ISSUE TITLE
✈️ 🔃 🚀 Feature Request: Loop Builder - Provide a way to create Taxonomy Term Loops (+WooCommerce) (Merged with #21372)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20018]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

It would be great if you could add category grid to loop builder. We should be able to display product categories using loop builder. This is a great feature.

### Describe the solution you'd like

Creating categories Grid of products using loop builder

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon. We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future. 

Best regards

**Comment by dsolimini** [comment]
I would add my support for the ability to create taxonomy loops -- including those NOT part of WooCommerce. In more than a few places I've had to use Custom Post Types when a taxonomy would have been better simply because Elementor can't list Taxonomy Terms in any way besides a text list.

**Comment by nicholaszein** [comment]
Hi there,

### 📅  This request is scheduled to be Migrated to the new [Discussions](https://github.com/elementor/elementor/discussions/categories/feature-request) section.

Please do not duplicate this request.

Once we migrate it, we encourage you to cast your **⬆️ Upvote** on the first comment if you feel it should be considered for our roadmap.

**Comment by ayoubkhan558** [comment]
+11111111111111111111111

**Comment by ayoubkhan558** [comment]
[[[](url)](https://github.com/elementor/elementor/issues/8248)](https://github.com/elementor/elementor/issues/8248)

**Comment by formulaclick** [comment]
+1 please do it!!!!!!!

**Comment by ayoubkhan558** [comment]
> Hi there,
> 
> ### 📅 This request is scheduled to be Migrated to the new [Discussions](https://github.com/elementor/elementor/discussions/categories/feature-request) section.
> Please do not duplicate this request.
> 
> Once we migrate it, we encourage you to cast your **⬆️ Upvote** on the first comment if you feel it should be considered for our roadmap.

When It will be added to discussions tab, We are waiting for this?

**Comment by chOse** [comment]
+1

**Comment by tomaszsoin** [comment]
+1

**Comment by arekuki** [comment]
+1

**Comment by mikodigital** [comment]
+1

**Comment by pbaddock** [comment]
+1 - this would be a fantastic addition to the loop grid / carousel.

**Comment by ayoubkhan558** [comment]
Created Discussion for this issue here.
#21372
https://github.com/orgs/elementor/discussions/21372

**Comment by ayoubkhan558** [comment]
> Created Discussion for this issue here. Please continue discussion here.
> 
> #21372 https://github.com/orgs/elementor/discussions/21372

Created Discussion for this issue here.
#1372

**Comment by nicholaszein** [comment]
Hello,

since @ayoubkhan558 already created a new feature request, with multiple comments (despite my asking not to), I'm closing this issue in favor of that feature.

Please continue the discussion here: #21372.

Kind regards
