### ISSUE TITLE
🐞 Bug Report: [v3.8-Beta] Container - z-index has serious problems with Menu Cart widget. (ED-8353)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20011]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor developers.

Please check the z-index issues in the container. There are very serious problems in different situations. I will give examples of some of these problems.

1- If we open the menu cart in the editor, the border of the container is on the menu cart widget.

![download](https://user-images.githubusercontent.com/77163248/194723334-8e3fa9b4-a7c8-454b-a522-c5366e7a6319.png)

2- In general, in the container we have no control over the layers using the z-index. This means that we cannot determine which container is placed on which container. We did not have this problem in the section.

3- If we have two sticky containers, there are massive problems when the menu cart widget is opened.

https://user-images.githubusercontent.com/77163248/194723571-1db50d84-abe0-4849-808b-e3e95bdcfc3d.mp4

4- Another example in the editor

![2](https://user-images.githubusercontent.com/77163248/194723971-a291257b-acc2-4134-b9c1-209fc29bbb41.png)

Please check these items. I've checked the reported cases in rival page builder and everything works fine there. So this is not a normal behavior. Fixing these defects is really necessary for a stable version of the container.

thank you

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @79ho3ein!

Thanks for reporting this. We already discussed this in length [here](https://github.com/elementor/elementor/discussions/19854#discussioncomment-3684560), and a solution was given. But I will be investigating this myself further to confirm if this is a bug. As I mentioned it isn't really a bug and it should be resolved by setting the correct z-index to the parent containers.

Please allow me some time to investigate this further.

Sincerely

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.8.0-beta-5

Feel free to update

Thanks!
