### ISSUE TITLE
✔️ 🐞Bug Report: [v3.8-Beta] Container - [Regression] Icon Box: Vertical Alignment does not maintain position on mobile (ED-8452)

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20021]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This is based on running on Elementor 3.8 beta3. When you use an icon box widget and set the content to middle vertical alignment it works on desktop and tablet but not mobile view. See the steps to reproduce section for a quick video. From having a quick look at the CSS it seems on mobile it changes from `display: inline-flex;` to `display: block;`.

### Steps to reproduce

https://user-images.githubusercontent.com/55829113/195038112-5cb1723e-3511-4603-8001-6589f053618e.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nicholaszein** [comment]
Hello @perks98 ! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello there @perks98!

Just passing by to say:

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8.0**! 🥳 

But I'm sure you already knew that! 😉 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
