### ISSUE TITLE
Elementor with Acf

### ISSUE THREAD

**Issue by ammory03** [elementor/elementor#20030]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

i have form made by custom fields ,everything is fine but for field typed gallery when upload an image i got 100% successful uploading but in admin side i got two blank squares 

i have contacted ACF support and they reply me (Usually, ACF uses the get_field() and the_field() functions to format and render field values on the front end as illustrated at https://drive.google.com/file/d/1F--MWN5-99ZaT1BDdgSNV6r84NRvDVhH/view?usp=sharing. Since you don't use these functions in your context, the frontend rendering is controlled by the Elementor plugin, this is not something that the ACF functions are able to control out of the box.) 

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.13
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://dorrah.sa
	Home URL: https://dorrah.sa
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 3
	Admin Email: ammory03@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 3.3.5
	Author: OceanWP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: ar
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0

== Active Plugins ==
	Admin Columns Pro
		Version: 5.7.4
		Author: AdminColumns.com

	Adminimize
		Version: 1.11.8
		Author: Frank Bültge

	Advanced Custom Fields: Extended
		Version: 0.8.8.10
		Author: ACF Extended

	Advanced Custom Fields PRO
		Version: 6.0.2
		Author: WP Engine

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Advanced Page Visit Counter Premium
		Version: 6.3.0
		Author: Page Visit Counter

	Better Notifications for WP
		Version: 1.9.1
		Author: Made with Fuel

	Custom Fonts
		Version: 1.3.7
		Author: Brainstorm Force

	Custom Login Page Customizer
		Version: 2.1.9
		Author: Hardeep Asrani

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Easy WP SMTP
		Version: 1.5.1
		Author: wpecommerce, alexanderfoxc

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.3.2
		Author: WPDeveloper

	Font Awesome
		Version: 4.3.1
		Author: Font Awesome

	Frontend Admin for ACF
		Version: 3.9.5
		Author: Shabti Kaplan

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	Imagify
		Version: 2.0
		Author: WP Rocket

	Insert PHP Code Snippet
		Version: 1.3.3
		Author: xyzscripts.com

	Joinchat
		Version: 4.5.10
		Author: Creame

	LiteSpeed Cache
		Version: 5.2.1
		Author: LiteSpeed Technologies

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	Ocean Extra
		Version: 2.0.5
		Author: OceanWP

	Premium Addons for Elementor
		Version: 4.9.35
		Author: Leap13

	Site Kit by Google
		Version: 1.85.0
		Author: Google

	User Role Editor
		Version: 4.63.1
		Author: Vladimir Garagulya

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.2
		Author: WPCode

	WP Custom Admin Interface
		Version: 7.28
		Author: Martin Gibson

	Yoast SEO
		Version: 19.8
		Author: Team Yoast

== Elements Usage ==
	
	popup : 3
		eael-creative-button : 1
		heading : 1
		text-editor : 1
		theme-site-logo : 1
	wp-page : 16
		button : 0
		divider : 4
		eael-creative-button : 1
		heading : -2
		icon-box : 1
		icon-list : 1
		image-carousel : 1
		posts : 1
		premium-counter : 8
		shortcode : 1
		text-editor : 1
		theme-site-logo : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Inactive
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 362022-06-18 12:26:49 [info] elementor-pro::elementor_pro_updater Started 
2022-06-18 12:26:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-18 12:26:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-18 12:26:49 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-18 12:26:52 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-18 12:26:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-18 12:26:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-18 12:26:52 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-18 12:26:53 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-18 12:26:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-10-06 10:34:12 [info] elementor::elementor_updater Started 
2022-10-06 10:34:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-06 10:34:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.8',
)]
2022-10-06 10:34:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-06 10:34:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.8',
)]
2022-10-06 10:34:24 [info] elementor-pro::elementor_pro_updater Started 
2022-10-06 10:34:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-06 10:34:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-06 10:34:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-06 10:34:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]

PHP: showing 5 of 5PHP: 2022-05-31 06:01:09 [notice X 32][/home/u989870296/domains/dorrah.sa/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-18 12:27:18 [notice X 878][/home/u989870296/domains/dorrah.sa/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-18 12:45:12 [notice X 6][/home/u989870296/domains/dorrah.sa/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-18 17:22:51 [notice X 3][/home/u989870296/domains/dorrah.sa/public_html/wp-content/plugins/elementor/includes/widgets/video.php::1161] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-03 13:59:38 [notice X 45][/home/u989870296/domains/dorrah.sa/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-10-03 06:54:56 [error X 1][https://dorrah.sa/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \&quot;view320\&quot;) has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Granular Controls Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @ammory03,

Thank you for reaching out! 🙏 

Elementor does not have any action from the Form widget that adds images to ACF galleries. It seems you're describing an issue with another plugin. Maybe a 3rd party add-on. Either way, this is not a native functionality of Elementor. Please check the 
[documentation](https://elementor.com/help/elementor-acf/), [here](https://elementor.com/help/basic-gallery-widget/), and [here](https://elementor.com/help/gallery-widget/) as well, on how to properly use ACF with Elementor.

While we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment! ⚠️ 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards
