### ISSUE TITLE
🚀 Feature Request: Copy the 'Hidden Elements' toggle to responsive mode bar

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20031]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

As with some Elementor features, some areas are not intuitive, like knowing where the 'hidden elements' toggle was, after using Elementor for 3 years now. Ideally, this would be a helpful feature and likely used more if copied in some form to the responsive mode bar at the top.

![Screenshot_626](https://user-images.githubusercontent.com/55829113/195543089-d8609d5c-41a4-4bf4-bc8d-3b77dd161919.jpg)

**Comment by fabianenzensperger** [comment]
I think from Elementor 4.0 there will be a new editor design. Maybe it's better solved there!

**Comment by nicholaszein** [comment]
Hello @perks98 ,

Thank you for submitting a feature request! 🙏 

After reviewing your request, we have decided not to add this to our roadmap for the time being.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
