### ISSUE TITLE
The newest Elementor update has a bug, that damages existing websites.

### ISSUE THREAD

**Issue by bhs67** [elementor/elementor#20032]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I downloaded an update to the basic Elementor => damaged an existing website 3DPrinting.foxping.com.  Music.foxping.com is similar to what it used to look like.

### Steps to reproduce

Download the latest version of Elementor (not Pro).  

1) Make a change to an existing website.  Refresh.  The display is corrupted.  

2) Create a new website.  Refresh.  The display is corrupted.  

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Win10, WordPress, Install Elementor (not Pro). update Elementor.

**Comment by nicholaszein** [comment]
Hello @bhs67,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** , and should not be used for support. ⚠️ 

What you're describing, and with the little information you shared, including:

* Missing detailed description of your issue
* Not isolating the problem
* * Not sharing the System Info as outlined in [our guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards,

Nick
