### ISSUE TITLE
⛔ 📚 ❓ API Question: Registering widget style in the <head> instead of the <body>

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#20049]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, I'm following this guide to add a CSS file to my widget: https://developers.elementor.com/docs/widgets/widget-dependencies/

And that's how I do it inside the widget's PHP:

```
public function get_style_depends() {

	wp_register_style( 'widget-css', plugins_url( 'assets/css/my-widget.css', __FILE__ ) );

	return [
		'widget-css',
	];

}
```

The CSS file gets added, but it gets added in the `<body>` close to the bottom where the usual scripts load, instead of loading it in the `<head>`. It loads at the bottom right before "e-animations-css".

How can I load my widget's CSS in the `<head>`?

### Steps to reproduce

Create a widget and add a CSS file to it with the method from the documentation.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not needed.

**Comment by nicholaszein** [comment]
Hello @azkalex! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by rami-elementor** [comment]
Hi @azkalex 

As a developer, you can define different assets required to run your widget. But Elementor will be the one to decide how and where to embed them.

We built the **registration mechanism** (`get_script_depends` and `get_style_depends`) to allow developers to register assets (JS/CSS) used in their widgets. But the **enqueue mechanism** is controlled by Elementor, this way we can experiment with performance optimization.

A good example is the **Improved CSS Loading** experiment. When the experiment is disables, the CSS files are loaded as external files. But when the experiment is enabled, those assets are loaded inline, reducing HTTP requests and lowering page render blocking resources.

Incompatible plugins that don't use the registration mechanism may cause conflicts. This is why we don't recommend using workarounds.

**Comment by nicholaszein** [comment]
> (...) My question is still, how can I load the widget's CSS file in the <head>? I need to load it in the <head> because I experience FOUC.

The short answer is: You can't because we are the ones controlling how the widget's CSS will be loaded, and we do not provide a way to do this by using our API. You can if you want, create your own method, but as Rami mentioned, you shouldn't be doing this, because it may cause conflicts.
