### ISSUE TITLE
🐞 Bug Report: Margin / padding decimal and negative numbers (Duplicate of #18135)

### ISSUE THREAD

**Issue by simkoG** [elementor/elementor#20047]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Dear Developers, 

Elementor is the "_#<span></span>1 Free WordPress Website Builder_" (source: elementor.com) plugin. Then why is it so hard to allow us to modify the numbers within the margin and padding fields? 

1) To write negative numbers, first you have to write a number, then write a negative sign. Why can't I just simply write `-1`? That is one more step than it should be. 
2) Why is it so hard to write decimal numbers? The best way I've found to give 0.875rem padding to an element is by copying and paste the value from somewhere else. There is no way that I can write a decimal point in the number field by myself. 

### Steps to reproduce

1) Crete element. 
2) Under Advanced > Margin change to REM. 
3) Write a negative value (like `-1`) or a decimal number (like `0.875`).
4) **optional**: Try not trow your computer in the trash.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
	MySQL version: mariadb.org binary distribution v10.6.10
	PHP Version: 7.4.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://e-crayfish-kuya.instawp.xyz
	Home URL: https://e-crayfish-kuya.instawp.xyz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: wpadmin@instawp.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-Two
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.8
		Author: Elementor.com


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default


== Log ==
	


== Elementor - Compatibility Tag ==
```

**Comment by nicholaszein** [comment]
Hello @simkoG!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #18135, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

⚠️ Please remember in the future to check if there isn't an issue similar to yours already opened, and to only submit one issue per thread.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
