### ISSUE TITLE
⛔ 🛟 Support Request: Elementor Pro causes critical error on website when activated

### ISSUE THREAD

**Issue by Bella523** [elementor/elementor#20054]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My site is set to automatically update.  After one of the recent updates, Elementor Pro caused a critical error on my page and I had to enter my site in recovery mode because it would not allow me to enter otherwise.  After updating other Elementor plugins, I then activated Elementor Pro and it immediately went to a critical error.  I have to wait for an email to be sent to me again to enter in recovery mode.  As per my membership, I do have Elementor Pro, I pay once a year for my membership but cannot get full use out of it.  Do I delete and reinstall?  Is there anything I can do on my end, or will I need one of your techs to go in there for me?  Your help in this matter is greatly appreciated.  Thank you for your time, I hope to hear from you soon!

### Steps to reproduce

In the left hand side menu on WordPress, go to plugins and click on it.  Go to Elementor Pro and click Activate.  The site will then go into critical error mode.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

https://bobbyramosbottomline.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

**Comment by Bella523** [comment]
I uninstalled the old version of Elementor Pro and downloaded the newest version of Elementor Pro and everything is working as it should.  Please disregard my original post.

**Comment by nicholaszein** [comment]
Hello @Bella523,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. But I'm glad you figured it out. I was going to suggest it was a problem with the version of Elementor Pro.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind Regards,

Nick
