### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by zee7426** [elementor/elementor#20052]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The feature is still missing

### Describe the solution you'd like

The feature is still missing

### Describe alternatives you've considered

The feature is still missing

### Additional context

The feature is still missing

**Comment by nicholaszein** [comment]
Hello @zee7426,

Thanks for your feedback! 🙏 

🧐 While reviewing your request we noticed it was missing the following key information:

* Description and examples.
* One request per thread

👉 Please follow the guidelines for opening a new [🚀 Feature Request](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml), so we can help you better.

Feel free to submit a new request in accordance with these guidelines. 😉 

Take care,

Nick
