### ISSUE TITLE
API Documentation JS Hooks before save event

### ISSUE THREAD

**Issue by maosalah** [elementor/elementor#20055]
Hi,
i want to add some code before the page saved, 
after some google search i found this code  and its deprecated:
```
    elementor.saver.on("before:save",function(){
      // code here...
    })

```
`elementor.saver.on` is hard deprecated since 2.9.0 - Use `$e.hooks` instead`

so i'm trying to implement it with `$e.hooks` but i could't find any documentation about it.
Is there a solution to convert the code above to `$e.hooks` 

Regards,

Documentation and how to implement `$e.hooks` for `"before:save"` event

**Comment by nicholaszein** [comment]
Hello @maosalah.

Please follow the official Developers Documentation [here](https://developers.elementor.com/docs/hooks/js/).

Regards

**Comment by lushkant** [comment]
Hey @maosalah, 

We recently had to go through implementing a similar action, and it was a nightmare to find relevant docs. But we did so. 
So I'd like to put it out here in case anybody else comes looking and wants to achieve the same. 

The right page to look for docs related to Elementor event hooks is this - https://github.com/elementor/elementor/blob/master/docs/modules/web-cli/assets/js/core/hooks.md

Here's how we hooked in to document save/update method in JavaScript -

```
class CustomUpdaterBeforeSave extends $e.modules.hookUI.Before {
	getCommand() {
		return 'document/save/save';
	}

	getId() {
		return 'custom-updater-before-save';
	}

	getConditions( args ) {
		return true;
	}

	apply( args, result ) {
		// Do whatever you want to do here.
	}
}

$e.hooks.registerUIBefore( new CustomUpdaterBeforeSave() );
```

Just call this inside `elementor/init`.

```
jQuery( window ).on( 'elementor/init', function() {
  //  The above code goes here.
});
```

**Comment by maosalah** [comment]
> Hey @maosalah,
> 
> We recently had to go through implementing a similar action, and it was a nightmare to find relevant docs. But we did so. So I'd like to put it out here in case anybody else comes looking and wants to achieve the same.
> 
> The right page to look for docs related to Elementor event hooks is this - https://github.com/elementor/elementor/blob/master/docs/modules/web-cli/assets/js/core/hooks.md
> 
> Here's how we hooked in to document save/update method in JavaScript -
> 
> ```
> class CustomUpdaterBeforeSave extends $e.modules.hookUI.Before {
> 	getCommand() {
> 		return 'document/save/save';
> 	}
> 
> 	getId() {
> 		return 'custom-updater-before-save';
> 	}
> 
> 	getConditions( args ) {
> 		return true;
> 	}
> 
> 	apply( args, result ) {
> 		// Do whatever you want to do here.
> 	}
> }
> 
> $e.hooks.registerUIBefore( new CustomUpdaterBeforeSave() );
> ```
> 
> Just call this inside `elementor/init`.
> 
> ```
> jQuery( window ).on( 'elementor/init', function() {
>   //  The above code goes here.
> });
> ```

@lushkant  Thank you, It is exactly what I was looking for.
