### ISSUE TITLE
🚀 Feature Request: Displaying Object instead of content of the Object in _register_controls()

### ISSUE THREAD

**Issue by HannahLeaM** [elementor/elementor#20057]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have created a custom widget using 3 controls:
 1. A SELECT Control displaying a list of pre-defined options.
 2. A TEXT Control displaying names fetched from a database via a dynamic tag
 3. A WYSIWYG Control that is supposed to display some text content from a database as its default value after the other two controls are populated.

 The Problem:
 How do I access the Value of the previous control inside the _register_controls() function. I know I can access the values I need in the render function by using $settings['control1'] but this is not working inside the Controls definition.
 Also accessing it via the tags used for conditional controls returns [object Object] instead of the text values. [e.g.: '{{WRAPPER}} .inner_class' => 'control_orgeinheit:transform:translate({{VALUE}})',]

 Please tell me how to access the values inside the _register_controls() function and how to save them to a useable variable like $defaults

 With kindest regards
 Hannah Moeckel

Example of my Class: https://my.elementor.com/wp-content/uploads/sites/2/gravity_forms/22-8fa82d82d4bd295a437b035bfb146a16/2022/10/my_classes.txt

### Steps to reproduce

1) Create a Custom Widget with 3 controls as shown in the Code Example in the link

2) Try populate the default value of the WYSIWYG Control with the values set in the other 2 

3) See [object Object] in the default value of the control 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.30
	PHP Version: 7.4.32
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://lkwb-relaunch.landkreis-wittenberg.de/development_stag
	Home URL: https://lkwb-relaunch.landkreis-wittenberg.de/development_stag
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: netadmin@landkreis-wittenberg.de
	Debug Mode: Inactive

== Theme ==
	Name: Monstroid2
	Version: 1.1.12
	Author: Zemez
	Child Theme: No

== User ==
	Role: lkwb-contentadmin
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Antispam Bee
		Version: 2.11.1
		Author: pluginkollektiv

	Better Search
		Version: 3.1.0
		Author: Ajay D'Souza

	BUSInclude2 - Organistaionseinheiten
		Version: 1.0.0
		Author: Hannah Moeckel

	BUSInclude2 - Variable Input
		Version: 1.0.0
		Author: Hannah Moeckel <moeckelha@landkreis-wittenberg.de>

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Essential Grid
		Version: 3.0.4
		Author: ThemePunch

	GTranslate
		Version: 2.9.13
		Author: Translate AI Multilingual Solutions

	Hello Dolly
		Version: 1.7.2
		Author: Matt Mullenweg

	Import and export users and customers
		Version: 1.20.5
		Author: codection

	JetBlocks For Elementor
		Version: 1.3.4
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.3.1
		Author: Crocoblock

	Jet Data Importer
		Version: 1.2.2
		Author: Zemez

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetGridBuilder
		Version: 1.1.2
		Author: Crocoblock

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	Jet Plugins Wizard
		Version: 1.2.9
		Author: Zemez

	JetPopup
		Version: 1.6.1
		Author: Crocoblock

	JetSmartFilters
		Version: 3.0.0
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.19
		Author: Crocoblock

	JetThemeCore
		Version: 2.0.7
		Author: Crocoblock

	JetTricks
		Version: 1.4.2
		Author: Crocoblock

	Kava Extra
		Version: 1.0.5
		Author: Zemez

	M2ThemeWizard
		Version: 1.0.0
		Author: Zemez

	Members
		Version: 3.2.1
		Author: MemberPress

	Real Media Library (Free)
		Version: 4.18.17
		Author: devowl.io

	Shariff Wrapper
		Version: 4.6.7
		Author: Jan-Peter Lambeck & 3UU

	Slider Revolution
		Version: 6.5.24
		Author: ThemePunch

	Ultimate Post Kit
		Version: 2.11.0
		Author: BdThemes

	W3 Total Cache
		Version: 2.2.6
		Author: BoldGrid

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WP Maintenance Mode & Coming Soon
		Version: 2.5.4
		Author: Themeisle

	WP STAGING PRO - Backup Duplicator & Migration
		Version: 4.2.8
		Author: WP-STAGING

	WP Statistics
		Version: 13.2.6
		Author: VeronaLabs

	Zemez Dashboard
		Version: 1.0.0
		Author: Zemez

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	WP STAGING Optimizer
		Version: 1.5.1
		Author: René Hermenau

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	Vorlagen Kit importieren / exportieren: Standardmäßig aktiviert
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Farbpalette: Standardmäßig aktiviert
	Bevorzugte Widgets: Standardmäßig aktiviert
	Admin Leiste: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert

== Protokoll ==
	
Log: showing 20 of 222022-09-19 11:26:00 [info] elementor-pro::elementor_pro_updater Started 
2022-09-19 11:26:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-19 11:26:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-19 11:26:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-19 11:26:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-27 08:27:49 [info] elementor::elementor_updater Started 
2022-09-27 08:27:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-27 08:27:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-27 08:27:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-27 08:27:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-27 08:28:23 [info] elementor-pro::elementor_pro_updater Started 
2022-09-27 08:28:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-27 08:28:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-27 08:28:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-27 08:28:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-07 09:13:53 [info] elementor::elementor_updater Started 
2022-10-07 09:13:53 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-07 09:13:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-07 09:13:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-07 09:13:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]

PHP: showing 13 of 13PHP: 2022-09-21 09:26:02 [notice X 412][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/ultimate-post-kit/includes/controls/select-input/dynamic-select.php(122): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-27 08:28:04 [notice X 246][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $finder_category_name ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-05 07:57:26 [notice X 1610][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-11 10:25:20 [error X 2][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor-businclude2_org/class-businclude2_org-widgets.php::24] Uncaught Error: Class 'ELEMENTOR_BUSINCLUDE2_ORG\Widgets\BUSInclude2_ORG' not found in /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor-businclude2_org/class-businclude2_org-widgets.php:24
Stack trace:
#0 /srv/www/lkwb-relaunch/development_stag/wp-includes/class-wp-hook.php(307): ELEMENTOR_BUSINCLUDE2_ORG\Widgets->register_widgets()
#1 /srv/www/lkwb-relaunch/development_stag/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /srv/www/lkwb-relaunch/development_stag/wp-includes/plugin.php(524): WP_Hook->do_action()
#3 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(331): do_action_ref_array()
#4 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/widgets.php(107): Elementor\Modules\DevTools\Deprecation->do_deprecated_action()
#5 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/widgets.php(310): Elementor\Widgets_Manager->init_widgets()
#6 /srv/www/lkwb- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-11 13:42:29 [error X 1][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/widgets.php::221] Uncaught TypeError: Argument 1 passed to Elementor\Widgets_Manager::register_widget_type() must be an instance of Elementor\Widget_Base, instance of ELEMENTOR_BI2ORG_Class given, called in /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-org-master/class-businclude2-org-widgets.php on line 37 and defined in /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/widgets.php:221
Stack trace:
#0 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-org-master/class-businclude2-org-widgets.php(37): Elementor\Widgets_Manager->register_widget_type()
#1 /srv/www/lkwb-relaunch/development_stag/wp-includes/class-wp-hook.php(307): ELEMENTOR_BUSINCLUDE2ORG\Widgets->register_widgets()
#2 /srv/www/lkwb-relaunch/development_stag/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /srv/www/lkwb-relaunch/development_stag/wp-includes/plugin.php(524): WP_Hook->do_action()
#4 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/mo [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 11:55:08 [warning X 3][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-tags-master/dynamic-tags/assets/sql-getcontent.php:31) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 11:58:32 [warning X 7][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-tags-master/dynamic-tags/server-variable-dynamic-tag.php:92) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 13:28:02 [warning X 1][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-tags-master/dynamic-tags/server-variable-dynamic-tag.php:95) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 14:44:21 [warning X 1][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-tags-master/dynamic-tags/server-variable-dynamic-tag.php:87) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 14:47:00 [warning X 11][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-tags-master/dynamic-tags/server-variable-dynamic-tag.php:96) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 14:48:52 [warning X 2][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-tags-master/dynamic-tags/server-variable-dynamic-tag.php:88) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-13 10:18:55 [error X 1][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/base/controls-stack.php::377] Uncaught ArgumentCountError: Too few arguments to function Elementor\Controls_Stack::add_control(), 0 passed in /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-org-master/widgets/class-bi2org.php on line 142 and at least 2 expected in /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/base/controls-stack.php:377
Stack trace:
#0 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/businclude2-org-master/widgets/class-bi2org.php(142): Elementor\Controls_Stack->add_control()
#1 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/base/controls-stack.php(2308): ElementorBi2org\Widgets\Businclude2Org->_register_controls()
#2 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#3 /srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#4 /srv/www/lkwb-re [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-13 15:57:39 [warning X 2][/srv/www/lkwb-relaunch/development_stag/wp-content/plugins/elementor/includes/managers/controls.php::790] array_merge(): Expected parameter 2 to be an array, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-10-05 12:17:14 [error X 1][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-content/plugins/elementor-pro/assets/js/app.min.js?ver=3.7.7:2:27991] this.conditionsConfig is null 
JS: 2022-10-05 12:48:52 [error X 1][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:646945] this.model.isValidChild is not a function 
JS: 2022-10-06 09:00:17 [error X 46][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2022-10-11 13:18:48 [error X 54][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-admin/js/editor.min.js?ver=6.0.2:2:734] Cannot read properties of undefined (reading \'style\') 
JS: 2022-10-12 07:52:25 [error X 77][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.7.8:2:3485] Cannot read properties of undefined (reading \'model\') 
JS: 2022-10-12 09:11:48 [error X 1][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:801748] Cannot convert undefined or null to object 
JS: 2022-10-14 07:24:16 [error X 1][https://lkwb-relaunch.landkreis-wittenberg.de/development_stag/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.8:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `BUSInclude2 - Organisationseinheiten` got <[object Object]> as `control_wysiwyg` value. Expected array or object.',
)]

== Elementor - Compatibility Tag ==
	
	BUSInclude2 - Variable Input: Kompatibel
	Elementor Pro: Kompatibel
	JetBlocks For Elementor: Unkompatibel
	JetBlog For Elementor: Unkompatibel
	JetElements For Elementor: Unkompatibel
	JetTabs For Elementor: Unkompatibel
	Ultimate Post Kit: Unkompatibel

== Elementor Pro - Compatibility Tag ==
	
	BUSInclude2 - Variable Input: Kompatibel
	JetBlocks For Elementor: Unkompatibel
	JetBlog For Elementor: Unkompatibel
	JetElements For Elementor: Unkompatibel
	JetTabs For Elementor: Unkompatibel

**Comment by nicholaszein** [comment]
Hello @HannahLeaM,

Thank you for submitting a feature request! 🙏 

The method you're trying to achieve is not supported by our API. If you want to add such functionality you would need to create your own method, and maintain it.

While it is an excellent suggestion, we are unable to prioritize it at this time. 😕 

If you decide to take it upon yourself to write your own solution, we would be happy to adopt it after reviewing your PR. 😉 

Take care!
