### ISSUE TITLE
🚀 Feature Request: Popup - Allow changing Entrance Animation Duration for responsive mode

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20051]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If we create an input animation for the popup in tablet or mobile mode, the Animation Duration (sec) option is not displayed. https://prnt.sc/EvUqeGQFdoTr

We are close to version 4 of Elementor and this simple bug has existed in Elementor since the beginning. Please fix this.

### Steps to reproduce

1- After creating the popup, immediately enter the tablet or mobile mode.
2- Consider an entry animation for the popup.

**The Animation Duration (sec) option will not be displayed.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. You can only set the animation duration on Desktop mode. You need to set it up on desktop mode first before switching to mobile.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by Michaelgimii** [comment]
@nicholaszein , This is not a new feature request! Of course, it was my mistake not to choose the bug tag.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

I've changed this to a feature request because this is not a bug. The interface is working as intended. Both the Duration and Delay controls are meant to be set only on desktop mode. So for now, we are not going to change this behavior.

Best regards
