### ISSUE TITLE
⛔ 📚 ❓ API Question: How to make my theme compatible with Elementor's Theme Builder

### ISSUE THREAD

**Issue by yanemr** [elementor/elementor#20077]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We are calling the header/footer Elementor Pro template in a new template (get_header() and get_footer()) and the hamburger menu icon is not opening. Can someone help us, please?

### Steps to reproduce

1-) Test in mobile/tablet devices[](url)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

![see-bug](https://user-images.githubusercontent.com/65790652/196484083-f9d0155a-7e04-4194-a925-61f7ef39a850.jpg)

**Comment by yanemr** [comment]
![see-bug](https://user-images.githubusercontent.com/65790652/196484083-f9d0155a-7e04-4194-a925-61f7ef39a850.jpg)

**Comment by nicholaszein** [comment]
Hello @yanemr,

Thanks for submitting your issue! 🙏 

You are using the wrong methods for making your theme compatible with Elementor.

please follow this guide to learn how to properly make your theme compatible with Elementor:

https://developers.elementor.com/docs/themes/

**Comment by yanemr** [comment]
Hello and thank you for replying. We are not doing that inside the dashboard. We are creating a /* Template Name: header and footer */ .php to export the header and footer to another website. That was working before but now looks like the frontend.min.js file duplicate (two different versions, one from Elementor and the other one from Elementor pro), and looks like that is the js handling the "toggle" event (hamburger menu). I hope you can help us. Thanks
