### ISSUE TITLE
❌ Invalid Issue: My site send emails by another email.  

### ISSUE THREAD

**Issue by Rodrigolivero** [elementor/elementor#20078]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, I would like to report a problem that is happening on my website.

I set up a forum and registered people receive a welcome email.

My email is "contact@undecember.pro" and my website name is Undecember PRO.

However, the email sent is "wordpress@undecember.pro" and the subject shows "Wordpress" instead of the name of my site.

I don't know how to solve this, can you help me?

### Steps to reproduce

To reproduce the problem just enter my site.

undecember.pro

And create an account, you will receive an email from 
wordpress@undecember.pro 
instead of...
contact@undecember.pro

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

I believe this will not be necessary to resolve the issue.

Because the center of the problem is not in the element, but in wordpress.

**Comment by nicholaszein** [comment]
Hello @Rodrigolivero,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. By default, WordPress sites use php_mail to send e-mails, and these e-mails will be sent using the administrator e-mail defined in your Dashboard > Settings > General as the sender. Please ask how to solve this issue in the [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook. 

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support. ⚠️ 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
