### ISSUE TITLE
[⌛ Awaiting Feedback] Form Builder - Can't remove_render_attribute

### ISSUE THREAD

**Issue by ItsmePNP** [elementor/elementor#20071]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

```
add_filter( 'elementor_pro/forms/render_field/upload', 'upload_message_change', 10, 3 );
 
 function upload_message_change( $item, $item_index, $form ) {
		if ( ! empty( $item['file_sizes'] ) ) {
			//$form->remove_render_attribute(  'input' . $item_index, 'data-maxsize-message');
			$form->add_render_attribute(
				'input' . $item_index,
				[
					'data-maxsize-message' =>sprintf(
                __('The file must be less than %s MB.', 'elementor-pro'),  $item['file_sizes'] ),
				]
			);
		}
	}
```

I wanted to show above message when user upload over the max file size limit. 
Found out elementor extracts value from _data-maxsize-message_ attribute of input filed type file. 
Message was added however was not replaced. 
Couldn't found reference to _remove_render_attribute_

### Steps to reproduce

1. Install plugin
2. Install hello theme
3. make a contact form with upload limit 1 MB
4. apply this code in function.php of child theme.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.0.24
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: private
	Home URL: private
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: private
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.0
		Author: WP Engine

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.0
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.2.4
		Author: WPDeveloper

	Filter Everything — WooCoomerce Product & WordPress Filter
		Version: 1.6.8
		Author: Andrii Stepasiuk

	GTranslate
		Version: 2.9.13
		Author: Translate AI Multilingual Solutions

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	Sticky Side Buttons
		Version: 1.0.9
		Author: Maeve Lander

	UpdraftPlus - Backup/Restore
		Version: 1.22.19
		Author: UpdraftPlus.Com, DavidAnderson

	WPForms Lite
		Version: 1.7.6
		Author: WPForms

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

== Elements Usage ==
	
	archive : 4
		archive-posts : 1
		heading : 8
		posts : 4
		search-form : 4
		sidebar : 1
		text-editor : 1
		theme-archive-title : 1
	footer : 1
		elementskit-post-list : 1
		heading : 5
		icon-list : 2
		image-box : 1
		nav-menu : 1
	header : 1
		button : 1
		icon : 1
		icon-box : 3
		nav-menu : 2
		search-form : 1
		shortcode : 1
		social-icons : 1
		theme-site-logo : 1
	loop : 1
		button : 1
		icon-list : 1
		theme-post-excerpt : 1
		theme-post-title : 1
	page : 1
		button : 2
		form : 1
		heading : 10
		image : 1
		image-box : 10
		spacer : 1
		testimonial-carousel : 2
	popup : 2
		heading : 4
	wp-page : 11
		button : 2
		eael-adv-tabs : 1
		eael-filterable-gallery : 2
		elementskit-blog-posts : 1
		form : 7
		gallery : 5
		google_maps : 1
		heading : 35
		icon-list : 1
		image : 5
		image-box : 13
		image-gallery : 1
		posts : 2
		slides : 1
		social-icons : 1
		testimonial-carousel : 1
		text-editor : -1
	single-post : 3
		button : 1
		divider : 2
		form : 2
		heading : 12
		post-info : 7
		post-navigation : 1
		posts : 2
		search-form : 1
		share-buttons : 2
		spacer : 1
		theme-post-content : 3
		theme-post-featured-image : 2
		theme-post-title : 3
	single-page : 1
		shortcode : 1
	search-results : 1
		archive-posts : 1
		theme-archive-title : 1
	error-404 : 1
		button : 1
		heading : 3
		image : 3
		shortcode : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

**Comment by rami-elementor** [comment]
Hi @ItsmePNP 

In the past the way to do that would be to manipulate existing form fields.

But now, we released new dev docs explaining how to create new form fields - https://developers.elementor.com/docs/form-fields/

The new **best practice** is to build your own field instead of changing existing fields. This way you can choose which attributes to apply on your markup.
