### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Linked category badge in the Posts widget (Duplicate of #13058, #16747)

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#20095]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It's a no-brainer that the category badges in the Posts widget should be linked. What's the point of only showing what category a post belongs to if you can't click on that category badge and see all the posts that belong to that category?

I don't want to get into the "after all these years, this x feature still hasn't been added/fixed" because I'm tired of it. Just like this issue https://github.com/elementor/elementor/issues/18038, which was closed without a real reason. That one is a no-brainer too, like, you already have the code in the Card skin, so why not add that code in the Classic skin too? Why should there be missing features between the skins when they do the same thing? Doesn't make any sense.

"We will look into it in the future if we see a large demand for it". This has nothing to do with demand, just like how this is not a feature. It's something that should've been there from the start, or added over time at least. I, and other people, don't start posting on GitHub for small stuff like this so you can see a demand, when it comes to basic stuff like this, the developers should already know it's needed. So instead of posting on GitHub, I'd rather look for something else because I know it's either going to take a lot of time to be fixed even if it's small stuff, or it'd just get lost in the void, so you'll never see demand for small stuff unless it's something big like containers/loops. I appreciate the current activity on development, and I hope it'll just get better.

### Describe the solution you'd like

I don't want to install a big plugin for something that can be fixed by **editing** a **single** line of code. I'm not a programmer, but I know how to google for stuff.

In the skin-cards.php file (elementor-pro/modules/posts/skins/skin-cards.php), on line 555, you'll find this: 

![image](https://user-images.githubusercontent.com/60075863/196942466-3aecb9bd-9426-4b09-8eaa-d89723ed52d6.png)
`<div class="elementor-post__badge"><?php echo esc_html( $terms[0]->name ); ?></div>`

Changing the `<div>` tag to an `<a>` tag and adding that code to its "href" attribute, fixes it, the category badge can now be clickable, and gets you to the archive page of that category.

![image](https://user-images.githubusercontent.com/60075863/196943056-a78218d7-6114-4a37-896a-ef0c3aa99032.png)
`<a href="<?php echo esc_url( get_category_link($terms[0]->term_id) ) ?>" class="elementor-post__badge"><?php echo esc_html( $terms[0]->name ); ?></a>`

As I said, I'm not a programmer, so I don't know if this is the best possible way to do it, but it makes sense, I tested it, and it works. I hope someone will look into this as my line will get removed on each plugin update. Thank you.

**Comment by nicholaszein** [comment]
Hello @azkalex!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #13058 and #16747, on the same subject. It's also worth mentioning that this will be solved by the Loop Builder, which is discussed in #4440. For this reason, I'm closing this issue and ↔️ **Merging** it with #4440, so we can have all the discussions in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
