### ISSUE TITLE
No Template Kit Export possible with Multisite Installation

### ISSUE THREAD

**Issue by blacckmamba** [elementor/elementor#20109]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I cannot export Template Kits with a multisite installation. The Screen remains gray. 

### Steps to reproduce

Go to Elementor -> Tools -> Import/Export -> Export Kit -> Button "Next". Press on button. Nothing happens. The screen remains gray. No prompts whatsoever.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.37
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: xxx
	Home URL: xxx
	WP Multisite: Yes
	Max Upload Size: 5 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: xxx
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Network Plugins ==
	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

== Must-Use Plugins ==
	assets-manager.php
		Version: 1.1.2
		Author: 

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	Vorlagen Kit importieren / exportieren: Standardmäßig aktiviert
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Farbpalette: Standardmäßig aktiviert
	Bevorzugte Widgets: Standardmäßig aktiviert
	Admin Leiste: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert

== Protokoll ==
	
Log: showing 20 of 412022-05-17 08:14:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-05-17 08:14:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-05-17 08:14:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-06-16 14:18:14 [info] elementor-pro::elementor_pro_updater Started 
2022-06-16 14:18:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-16 14:18:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-16 14:18:14 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-16 14:18:14 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-16 14:18:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-06-16 14:18:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-10-22 12:28:35 [info] elementor::elementor_updater Started 
2022-10-22 12:28:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-22 12:28:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-22 12:28:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.7.8',
)]
2022-10-22 12:28:36 [info] elementor-pro::elementor_pro_updater Started 
2022-10-22 12:28:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-22 12:28:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-22 12:28:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-10-22 12:28:36 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-10-22 12:28:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]

PHP: showing 2 of 2PHP: 2022-05-24 17:23:05 [notice X 2][/www/htdocs/w00ee9eb/designs/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 19:39:13 [notice X 1][/www/htdocs/w00ee9eb/designs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	

== Elementor Pro - Compatibility Tag ==

**Comment by blacckmamba** [comment]
I rolled back the Elementor versions to a time when there was no plugin export possible (before 3.6.0 in the free version) when exporting the Template Kits. And now the export went through. Even if this narrows down the problem, it's of course not the solution. Seems that it is problematic that the plugins are installed in the multisite installation at network level. So I guess at least.

**Comment by blacckmamba** [comment]
Seems to work with future version 3.8! 
Fix: Export kit doesn't work in a Multisite Network [ED-7696] (https://github.com/elementor/elementor/pull/19146)

**Comment by nicholaszein** [comment]
Hello there @blacckmamba!

Thank you for submitting your bug report. It was indeed a bug and it was solved with Elementor 3.8. 🥳 🙌 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
