### ISSUE TITLE
❌ Invalid Issue: Popup UI - Advanced Rules of the Popup Conditions UI appears broken

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20101]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello

If we enable some condition, serious problem will arise in ui. The image below.

![Screenshot (830)](https://user-images.githubusercontent.com/88034902/197049133-7f8ce300-01c8-487b-900d-827065bd3657.png)

So it would be great if you find a solution to improve it.

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii, 

Thank you for the feedback. 🙏 

Can you please provide more information?

* Steps to replicate
* System info

We need to know the environment so we can reproduce the issue, otherwise, we can't validate it!

Best regards,

Nick

**Comment by Michaelgimii** [comment]
Hi @nicholaszein , This bug is quite obvious. In the popup display conditions section, when we activate some conditions (which have long titles), the ui is severely damaged. Please watch the video below : 

https://user-images.githubusercontent.com/88034902/197901363-782374b4-52e9-4d9b-9ba9-f4d894d522e0.mp4

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thanks for your feedback, but you forgot to share the System Info again!

We need to understand what environment you are in, what version of Elementor you are using, and what plugins and themes are installed so we can reproduce your issue internally.

👉 Please follow the guidelines for opening a new [🚀 Feature Request](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml), so we can help you better.

Feel free to submit a new request in accordance with these guidelines. 😉 

Take care,

Nick
