### ISSUE TITLE
🚀 Feature Request: Provide a way to enqueue scripts conditionally based on element/document controls

### ISSUE THREAD

**Issue by hmouhtar** [elementor/elementor#20104]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I have added a custom toggle to the popup element. 

```
add_action('elementor/element/popup/popup_layout/before_section_end', function($element, $args){
	
	$element->start_injection( [
		'at' => 'after',
		'of' => 'close_button',
	] );
	
	$element->add_control(
		'pre_render',
		[
			'label' => esc_html__( 'Pre Render Popup', 'elementor-pre-render-popups' ),
			'type' => \Elementor\Controls_Manager::SWITCHER,
			'label_off' => esc_html__( 'Hide', 'elementor-pro' ),
			'label_on' => esc_html__( 'Show', 'elementor-pro' ),
			'default' => 'no'
		]
	);
	
	$element->end_injection();
	
}, 10, 2);
```

Now I want to enqueue a custom script only if that toggle is set to true in order to replace some of the behavior of popups on the frontend. How can I achieve this? The action `elementor/frontend/popup/before_render` does not exist, I assume that is because popups are documents and not widgets, so what would be the best way to achieve this?

### Describe the solution you'd like

It would be nice if I could enqueue scripts or styles for objects of type Document based on control settings.

**Comment by nicholaszein** [comment]
Hello @hmouhtar,

thanks for submitting your feature request! 🙏 

Currently, there is no supported way to conditionally enqueue scripts based on controls. We do not support this method in our API.

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon. What you can do is enqueue scripts only on pages where popups exist using default WordPress methods for enqueueing scripts.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
