### ISSUE TITLE
❌ Invalid Issue: Design problems using 3rd party addon after update

### ISSUE THREAD

**Issue by ckasnes** [elementor/elementor#20108]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I recently updated Elementor, Elementor Pro and Reobiz theme. Since then, some design elements and visuals changed on my website. When I tried to edit them through Elementor/Elementor Pro I couldn't access the backoffice on Chrome (even with enable mode) but I do on Microsoft Edge. Also, the design of my website is not the exact same depending of the browser I'm using: 
**On Edge :** 
![image](https://user-images.githubusercontent.com/116359496/197212476-7bc4952e-2021-47bf-a393-bc9d056352b7.png) // 
![image](https://user-images.githubusercontent.com/116359496/197212804-33fa4055-4963-46e2-a189-691ca5c0c38d.png)

**On Chrome :** 
![image](https://user-images.githubusercontent.com/116359496/197212397-6d9f1228-ede1-46b8-838b-ad9bd824bf69.png) // 
![image](https://user-images.githubusercontent.com/116359496/197212901-9bb61253-5bcf-428d-8387-d2f679f43a5a.png)

On Edge, when I try to put (for instance) a new heading, the changes are made on the website but not when I try to change the typology (size, color etc.).

Also, when I update my WordPress to 6.0.3, it keeps telling me translations for Elementor and Elementor Pro were not found.

### Steps to reproduce

1) update the plugins Reobiz to 4.8.5 version JetSmartFilters to 3.0.0, and latest version of Elementor / Elementor Pro
2) Try to edit with Elementor on Chrome
3) Try to edit with Elementor on Edge
4) Desactivate one by one all of my plugins RS Elements/Framework 
5) Change my theme
6) Go one the FTP and check if something wrong

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.2
	MySQL version: Debian 10 v10.3.36
	PHP Version: 7.4.32
	PHP Memory Limit: 192M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://ngfinance75-ngfi-expertise.pf28.wpserveur.net
	Home URL: https://ngfinance75-ngfi-expertise.pf28.wpserveur.net
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: ckasnesralla@ngfi.fr
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Breadcrumb NavXT
		Version: 7.1.0
		Author: John Havlik

	Category Ajax Filter
		Version: 2.6.4
		Author: Trusty Plugins

	Contact Form 7
		Version: 5.6.4
		Author: Takayuki Miyoshi

	CookieYes | GDPR Cookie Consent
		Version: 3.0.3
		Author: CookieYes

	Custom Permalinks
		Version: 2.4.0
		Author: Sami Ahmed Siddiqui

	Custom Post Type Permalinks
		Version: 3.4.5
		Author: Toro_Unit

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Disable Comments
		Version: 2.4.2
		Author: WPDeveloper

	Display PHP Version
		Version: 1.7
		Author: David Gwyer

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Elementor
		Version: 3.9.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev2
		Author: Elementor.com

	Envato Market
		Version: 2.0.7
		Author: Envato

	Image Hotspot - Map Image Annotation
		Version: 1.4
		Author: Sk Abul Hasan

	JetSmartFilters
		Version: 3.0.0
		Author: Crocoblock

	Loginizer
		Version: 1.7.4
		Author: Softaculous

	MC4WP: Mailchimp for WordPress
		Version: 4.8.10
		Author: ibericode

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Redirection
		Version: 5.3.4
		Author: John Godley

	RSElements
		Version: 1.0.7
		Author: rs-theme

	RS Framework
		Version: 1.3
		Author: RS Theme

	Slider Revolution
		Version: 6.5.31
		Author: ThemePunch

	Template Library and Redux Framework
		Version: 4.3.19
		Author: Extendify

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WPFront Scroll Top
		Version: 2.0.7.08086
		Author: Syam Mohan

	WP Job Openings
		Version: 3.3.2
		Author: AWSM Innovations

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.8
		Author: Team Yoast

== Must-Use Plugins ==
	.mu-plugin.php
		Version: 
		Author: 

	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Mu-Plugin WP Serveur
		Version: 1.5
		Author: WPServeur

== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 6
		icon-list : 2
		image : 1
		social-icons : 1
	header : 1
		image : 5
		nav-menu : 2
	page : 20
		accordion : 1
		animated-headline : 1
		call-to-action : 1
		divider : 1
		heading : 1
		icon-list : 1
		image : 2
		image-carousel : 1
		posts : 1
		rs-button : 2
		rs-cf7 : 1
		rs-dual-heading : 1
		rs-heading : 5
		social-icons : 1
	wp-post : 6
		text-editor : 7
	wp-page : 120
		breadcrumbs : 70
		button : 1
		call-to-action : 136
		divider : 40
		google_maps : 1
		heading : 235
		icon-box : 78
		icon-list : 8
		image : 86
		image-carousel : 54
		jet-smart-filters-select : 18
		menu-anchor : 72
		nav-menu : 21
		posts : 26
		rs-button : 65
		rs-cf7 : 63
		rs-dual-heading : 54
		rs-heading : 203
		slides : 1
		social-icons : 32
		spacer : 57
		text-editor : 163
	single-post : 3
		divider : 1
		heading : 16
		spacer : 1
		theme-post-content : 2
		theme-post-featured-image : 3
		theme-post-title : 3

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active by default
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
PHP: showing 20 of 28PHP: 2022-10-18 15:51:30 [notice X 1][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 16:25:26 [notice X 21][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 16:57:14 [notice X 20][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 22][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(366): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(20): ElementorPro\License\API :: is_license_active()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(98): ElementorPro\Core\Behaviors\Feature_Lock -> is_locked()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create -> create_item_url_by_document_class()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create -> get_category_items()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 22][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::372] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(372): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(27): ElementorPro\License\API :: is_license_expired()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(101): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create -> create_item_url_by_document_class()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create -> get_category_items()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 22][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(366): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(20): ElementorPro\License\API :: is_license_active()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(38): ElementorPro\Core\Behaviors\Feature_Lock -> is_locked()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(101): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create -> create_item_url_by_document_class()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 22][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::372] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(372): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(48): ElementorPro\License\API :: is_license_expired()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(101): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create -> create_item_url_by_document_class()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create -> get_category_items()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 22][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::372] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(372): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(52): ElementorPro\License\API :: is_license_expired()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(101): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create -> create_item_url_by_document_class()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create -> get_category_items()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(366): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php(197): ElementorPro\License\API :: is_license_active()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php(521): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts_Manager -> can_use_custom_fonts()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Fonts_Manager -> add_finder_item()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(366): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons-manager.php(132): ElementorPro\License\API :: is_license_active()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons-manager.php(183): ElementorPro\Modules\AssetsManager\AssetTypes\Icons_Manager -> can_use_custom_icons()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Icons_Manager -> add_finder_item()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::372] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(372): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(27): ElementorPro\License\API :: is_license_expired()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons-manager.php(186): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Icons_Manager -> add_finder_item()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(366): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(20): ElementorPro\License\API :: is_license_active()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(38): ElementorPro\Core\Behaviors\Feature_Lock -> is_locked()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons-manager.php(186): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Icons_Manager -> add_finder_item()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::372] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(372): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(48): ElementorPro\License\API :: is_license_expired()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons-manager.php(186): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Icons_Manager -> add_finder_item()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::372] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(372): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/core/behaviors/feature-lock.php(52): ElementorPro\License\API :: is_license_expired()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons-manager.php(186): ElementorPro\Core\Behaviors\Feature_Lock -> get_config()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\AssetsManager\AssetTypes\Icons_Manager -> add_finder_item()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
',
)]
PHP: 2022-10-19 07:05:38 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php::366] Undefined index: license [array (
  'trace' => '
#0: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/license/api.php(366): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/popup/module.php(192): ElementorPro\License\API :: is_license_active()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor-pro/modules/popup/module.php(167): ElementorPro\Modules\Popup\Module -> can_use_popups()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Popup\Module -> add_finder_items()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
',
)]
PHP: 2022-10-19 07:41:07 [notice X 1][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-19 07:57:20 [notice X 2][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 13:08:05 [notice X 21][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 13:42:32 [notice X 3][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-21 13:42:32 [notice X 3][/home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/clients/ngfinance75/prod/ngfi_expertise/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]

JS: showing 1 of 1JS: 2022-10-19 13:38:30 [error X 1][https://ngfinance75-ngfi-expertise.pf28.wpserveur.net/wp-content/plugins/elementor/assets/js/common.min.js:2:62522] Commands: `notes/toggle` not found. 

Log: showing 13 of 132022-10-21 13:08:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.9.0-dev2',
)]
2022-10-21 13:08:03 [info] elementor-pro::elementor_pro_updater Started 
2022-10-21 13:08:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-21 13:08:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-21 13:08:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-21 13:08:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-21 13:08:03 [info] elementor::elementor_updater Started 
2022-10-21 13:08:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-21 13:08:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-21 13:08:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-21 13:08:04 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-21 13:08:04 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-21 13:08:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.9.0-dev2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @ckasnes,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we could not reproduce your issue using only Elementor and Elementor Pro with the Hello Elementor theme. 

#### While we do welcome bug reports, we can't provide support for 3rd party add-ons or themes.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️ Back up your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin's support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support. 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
