### ISSUE TITLE
🚀 Feature Request: Paste images from clipboard

### ISSUE THREAD

**Issue by andersonjeccel** [elementor/elementor#20110]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It is currently not possible to paste an image from the clipboard directly into the page as an image widget. Having to develop the entire file upload path simply makes editing pages much slower, even more so when we have a file exclusively available on the clipboard. We are forced to save it in a file so that it can be placed on the page being edited, this makes the professional use of the Elementor unfeasible today, as we have competitors that already provide the function.

### Describe the solution you'd like

It would be great if we could use a keyboard shortcut to paste an image from the clipboard directly as an image widget.

### Describe alternatives you've considered

There are plugins that allow this for WordPress but they don't work inside Elementor

**Comment by nicholaszein** [comment]
Hello @andersonjeccel,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by griffintv** [comment]
That's disappointing. It's very cumbersome to have to jump all around the file system to get images to upload to the gallery, instead of just pasting-in-place.

**Comment by griffintv** [comment]
Screenshots for example.
