### ISSUE TITLE
🐞 Bug Report: Loop Builder - Stripe Button is throwing a 500 error when added to a loop template

### ISSUE THREAD

**Issue by finidev** [elementor/elementor#20117]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I added a stripe button into a loop and it doesn't work.

### Steps to reproduce

1) Create a loop with Stripe Button included.

2) Open dev tools

3) Test using Stripe Test Secret Key.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.1
	MySQL version: mariadb.org binary distribution v10.3.36
	PHP Version: 8.0.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://utahmountainair.staging.tempurl.host
	Home URL: https://utahmountainair.staging.tempurl.host
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: daniel@finidev.tech
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

== Active Plugins ==
	Defender Pro
		Version: 3.3.3
		Author: WPMU DEV

	Duplicate Page
		Version: 4.4.9
		Author: mndpsingh287

	Easy Media Replace
		Version: 0.1.3
		Author: Nabil Lemsieh

	Elementor
		Version: 3.9.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev4
		Author: Elementor.com

	Hummingbird Pro
		Version: 3.3.5
		Author: WPMU DEV

	JetEngine
		Version: 3.0.5
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.0
		Author: Crocoblock

	Smush Pro
		Version: 3.12.2
		Author: WPMU DEV

	Ultimate Dashboard
		Version: 3.7.1.5
		Author: David Vongries

	Ultimate Dashboard PRO
		Version: 3.6.4
		Author: David Vongries

	User Profile Picture
		Version: 2.6.0
		Author: Cozmoslabs

	WPMU DEV Dashboard
		Version: 4.11.17
		Author: WPMU DEV

== Must-Use Plugins ==
	Hosting
		Version: 0.1
		Author: 

== Elements Usage ==
	
	container : 1
		button : 1
		heading : 1
		image : 1
		text-editor : 1
	footer : 1
		heading : 7
		icon : 3
		icon-list : 2
		image : 2
		social-icons : 1
		spacer : 2
		text-editor : 1
		theme-site-logo : 1
	header : 1
		button : 3
		heading : 2
		icon-list : 2
		nav-menu : 1
		theme-site-logo : 1
	loop : 0
		container : 1
		heading : 2
		image : 1
		spacer : 2
		stripe-button : 1
		text-editor : 1
	page : 9
		button : 41
		counter : 16
		divider : 13
		form : 6
		google_maps : 1
		heading : 104
		html : 1
		icon : 3
		icon-box : 17
		icon-list : 10
		image : 72
		image-box : 14
		progress : 7
		social-icons : 1
		spacer : 1
		text-editor : 63
		toggle : 5
		video : 1
	section : 1
		button : 9
		counter : 4
		form : 1
		heading : 17
		icon : 1
		icon-list : 3
		image : 24
		image-box : 1
		text-editor : 7
		video : 1
	widget : 0
		form : 1
	wp-page : 7
		button : 11
		container : 18
		counter : 9
		form : 2
		heading : 35
		html : 2
		icon : 5
		icon-list : 6
		image : 40
		jet-listing-dynamic-field : 2
		jet-listing-grid : 3
		loop-grid : 1
		spacer : 5
		text-editor : 12
		video : 1
	loop-item : 1
		container : 1
		heading : 2
		image : 1
		spacer : 2
		stripe-button : 1
		text-editor : 1
	jet-listing-items : 0
		button : 2
		container : 7
		heading : 2
		icon-box : 1
		image : 3
		jet-listing-dynamic-field : 5
		spacer : 2
		stripe-button : 1
		text-editor : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 352022-10-03 08:08:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-23 18:10:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0-beta5',
)]
2022-10-23 18:10:54 [info] elementor::elementor_updater Started 
2022-10-23 18:10:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-23 18:10:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-23 18:10:56 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-23 18:10:56 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-23 18:10:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0-beta5',
)]
2022-10-23 18:16:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta5',
  'to' => '3.9.0-dev3',
)]
2022-10-23 18:16:37 [info] elementor::elementor_updater Started 
2022-10-23 18:16:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-23 18:16:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-23 18:16:38 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-23 18:16:38 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-23 18:16:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta5',
  'to' => '3.9.0-dev3',
)]
2022-10-23 18:17:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev4',
)]
2022-10-23 18:17:07 [info] elementor-pro::elementor_pro_updater Started 
2022-10-23 18:17:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-23 18:17:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-23 18:17:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev4',
)]

PHP: showing 7 of 7PHP: 2022-10-20 22:46:31 [warning X 5][/var/web/site/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 02:42:03 [error X 30][/var/web/site/public_html/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Elementor\Elements_Manager::create_element_instance(): Argument #1 ($element_data) must be of type array, bool given, called in /var/web/site/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php on line 289 and defined in /var/web/site/public_html/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /var/web/site/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php(289): Elementor\Elements_Manager->create_element_instance(false)
#1 /var/web/site/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Payments\Module->submit_stripe_form('')
#2 /var/web/site/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /var/web/site/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /var/web/site/public_html/wp-admin/admin-ajax.php(202): do_action('wp_ajax_nopriv_...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 03:02:34 [error X 23][/var/web/site/public_html/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Elementor\Elements_Manager::create_element_instance(): Argument #1 ($element_data) must be of type array, bool given, called in /var/web/site/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php on line 289 and defined in /var/web/site/public_html/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /var/web/site/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php(289): Elementor\Elements_Manager->create_element_instance(false)
#1 /var/web/site/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Payments\Module->submit_stripe_form('')
#2 /var/web/site/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /var/web/site/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /var/web/site/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_submit_...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-23 17:50:01 [warning X 3][/var/web/site/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php::300] Undefined array key "stripe_test_env_tax_rates_list" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-23 18:16:38 [notice X 383][/var/web/staging/public_html/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-23 18:23:10 [warning X 1][/var/web/staging/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/web/staging/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/web/staging/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/web/staging/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/web/staging/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-10-23 18:27:05 [error X 4][/var/web/staging/public_html/wp-content/plugins/elementor/includes/managers/elements.php::71] Uncaught TypeError: Elementor\Elements_Manager::create_element_instance(): Argument #1 ($element_data) must be of type array, bool given, called in /var/web/staging/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php on line 289 and defined in /var/web/staging/public_html/wp-content/plugins/elementor/includes/managers/elements.php:71
Stack trace:
#0 /var/web/staging/public_html/wp-content/plugins/elementor-pro/modules/payments/module.php(289): Elementor\Elements_Manager->create_element_instance(false)
#1 /var/web/staging/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Payments\Module->submit_stripe_form('')
#2 /var/web/staging/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /var/web/staging/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /var/web/staging/public_html/wp-admin/admin-ajax.php(187): do_action('wp_ajax_submit_...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @finidev! 

Thank you for submitting your issue! 🙏 

Currently, the Stripe Button is not supported within the Loop Builder, like any other e-commerce feature. These are features that we will look into implementing in the next phases if the 3rd party service supports them (in this case Stripe).

Best regards

**Comment by nicholaszein** [comment]
Hello @finidev,

I can confirm this feature is not on our plans to implement for the Loop Builder in the near future. Please feel free to submit a feature request.

Best regards,

Nick
