### ISSUE TITLE
🚀 Feature Request: Performance - Reduce number of scripts loaded

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#20122]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey guys,

I understand there are many priorities now, but it would be really great if you could bump the Javascript optimisation. There's just too many scripts loaded for no reason. I know a page with a single Heading is not realistic, but either way, some of these scripts are likely not to be needed regardless of that, so why not just enqueue on runtime to be picked up in wp_footer.

<img width="1926" alt="Markup 2022-10-24 at 10 21 57" src="https://user-images.githubusercontent.com/1725925/197470973-a0640313-0331-4444-8afd-86a4c89a2794.png">

PS: Went through tens of issues but couldn't find the one that likely contains the discussion for this topic (as probably others pointed this out too). I'm really sorry!

### Steps to reproduce

Just adding a Heading element.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hey @hogash,

Thanks for your feedback! 🙏 

🧐 While reviewing your request we noticed it was missing the following key information:

* What problem is your feature request going to solve?
* Describe the solution you'd like
* Describe alternatives you've considered
* Additional context

👉 Please follow the guidelines for opening a new [🚀 Feature Request](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml), so we can help you better.

Feel free to submit a new request in accordance with these guidelines. 😉 

Take care,

Nick
