### ISSUE TITLE
🐞 Bug Report: Container - Layout broken after updating to the latest 3.9.0-dev3 version.

### ISSUE THREAD

**Issue by coconet12** [elementor/elementor#20139]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The web layout is messed up, everything is overlap and all the words move to the right side.

### Steps to reproduce

1) layout is messed up, some modules overlapped
2) words move to the right side
![image](https://user-images.githubusercontent.com/116678463/197863257-39a717f1-7716-4dcb-ac70-44bae6c44b8b.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.32
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://yueyingfdesign.com
	Home URL: https://yueyingfdesign.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: zh-CN
	Timezone: 0
	Admin Email: fangyueying1997@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.2.0
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: zh_CN
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Bluehost
		Version: 2.12.9
		Author: Bluehost

	Bluehost Website Builder
		Version: 1.0-2653 : 20220809_085420
		Author: Newfold Digital

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Creative Mail by Constant Contact
		Version: 1.6.0
		Author: Constant Contact

	Elementor
		Version: 3.9.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.3.2
		Author: WPDeveloper

	Gallery by BestWebSoft
		Version: 4.6.9
		Author: BestWebSoft

	Google Analytics for WordPress by MonsterInsights
		Version: 8.9.1
		Author: MonsterInsights

	Jetpack
		Version: 11.4
		Author: Automattic

	OptinMonster
		Version: 2.10.0
		Author: OptinMonster Popup Builder Team

	Templately
		Version: 2.0.2
		Author: Templately

	TrustPulse API
		Version: 1.0.6
		Author: 

	WPForms Lite
		Version: 1.7.7.2
		Author: WPForms

	WP Photo Album Plus
		Version: 8.2.08.006
		Author: J.N. Breetvelt a.k.a. OpaJaap

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elementor Experiments ==
	优化的 DOM 输出: 状态
	改善资源加载: 状态
	Improved CSS Loading: 状态
	Inline Font Icons: 状态
	辅助改进: 状态
	Additional Custom Breakpoints: 状态
	Import Export Website Kit: 状态
	Hide native WordPress widgets from search results: 状态
	admin_menu_rearrangement: 作为默认停用
	Flexbox Container: 状态
	着陆页面: 状态
	Color Sampler: 状态
	Favorite Widgets: 状态
	Admin Top Bar: 状态

== Log ==
	
Log: showing 20 of 312022-08-21 15:57:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev3',
  'to' => '3.8.0-dev4',
)]
2022-09-20 15:50:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-09-20 15:50:20 [info] elementor::elementor_updater Started 
2022-09-20 15:50:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-20 15:50:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-20 15:50:20 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-09-20 15:50:20 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-09-20 15:50:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-09-20 15:50:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-10-11 12:22:27 [info] elementor::elementor_updater Started 
2022-10-11 12:22:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-11 12:22:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-11 12:22:27 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-11 12:22:27 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-11 12:22:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-23 17:04:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-23 17:04:17 [info] elementor::elementor_updater Started 
2022-10-23 17:04:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-23 17:04:17 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-23 17:04:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]

JS: showing 8 of 8JS: 2022-08-16 16:06:31 [error X 1][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev3:3:723918] elementor.documents.currentDocument is null 
JS: 2022-08-16 19:20:01 [error X 26][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.8.0-dev3:2:4761] elementorFrontend.config.elements is undefined 
JS: 2022-08-17 10:29:11 [error X 1][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev3:3:571381] elementor.documents.getCurrent() is null 
JS: 2022-09-17 16:35:33 [error X 4][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:1059976] $ is null 
JS: 2022-10-11 15:01:25 [error X 14][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2022-10-13 20:35:30 [error X 2509][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16778] this._lastColor is null 
JS: 2022-10-13 20:35:30 [error X 50][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:20993] this._eventListener is null 
JS: 2022-10-14 14:22:44 [error X 1][https://yueyingfdesign.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.9.0-dev2:2:30926] elementor.settings.page is undefined 

PHP: showing 3 of 3PHP: 2022-10-04 04:33:17 [notice X 287][/home2/yueyingf/public_html/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-13 20:35:37 [warning X 5][/home2/yueyingf/public_html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key "url" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-14 10:00:14 [warning X 2][/home2/yueyingf/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home2/yueyingf/public_html/wp-content/plugins/elementor/modules/performance-lab/module.php:31) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified

**Comment by nicholaszein** [comment]
Hello @coconet12!

I assume you are using the Flexbox Container experiment with the Elementor Developer Edition plugin installed. The latest **DEV** and **BETA** versions, which should never be used on production websites, had an issue that removed the styles for Container with `Container Width` set to `Fullwidth`. All you need to do is to go to each container and set the `Container Width` back to `Fullwidth`. The control will appear empty.

We are already aware of this issue, and it is going to be fixed in the next releases.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards,

Nick
