### ISSUE TITLE
✅ 🚀 Feature Request: Ability to add widgets on click (in addition to drag and drop) in the Widget Panel - [ED-10566]

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20142]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

It would be great if you add the ability to add widgets with just one click. This is a modern method and in most cases much better than drag and drop.
As you know, Elementor is now working on its new editor ui. In the published video of the concept design of the new editor, it is possible to add widgets by clicking. I hope this is part of the new ui. Do you approve of this?

### Describe the solution you'd like

Ability to add widgets using click

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.14.0X! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
