### ISSUE TITLE
❌ Invalid Issue: Form cannot be submitted when it is in a tab (Merged with #20149)

### ISSUE THREAD

**Issue by jannnfe** [elementor/elementor#20140]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey,
If I create a form and then save it as a global widget and put it as a shortcode in a tab of the tab widget, it can no longer be sent. In addition, the honeypot field, for example, is no longer displayed correctly. It's no longer hidden.

### Steps to reproduce

1) Create a Form with couple fields and also honeypot field
2) Save this Form as global Widget
3) Use the Tab Widget to create some Tabs
4) In the Tab Content use the dynamic Input to insert a Shortcode
5) Insert the Shortcode of the global Widget Form from step 2 (find it in the template section in wp backend)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 18.04 v5.6.49-89.0
	PHP Version: 7.4.32
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /blog/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== Active Plugins ==
	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

**Comment by nicholaszein** [comment]
Hey @jannnfe, 

Thank you for submitting your issue. 🙏 

### ⛔ While reviewing your report, we noticed it was missing some key pieces of information.

* **System info:** You did not provide the full System Info. We need to see the entire report of the System Info to be able to evaluate your issue. Please re-submit it!

Without them, we simply can't help. 😕 

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards

**Comment by nicholaszein** [comment]
Hello @jannnfe!

Thank you for providing more information on issue #20149! 🙏 

I'm closing this issue and ↔️ **Merging** it with the other more complete one, so we can have all the discussion in one location, and deal with it more efficiently.

👉 **Quick tip:** In the future, you can simply edit your original message instead of creating a new issue. 

Please feel free to continue the conversation there. 😉 

Best regards,

Nick
