### ISSUE TITLE
❌ Invalid Issue: New update Elementor turn my images blurry

### ISSUE THREAD

**Issue by ValterVV** [elementor/elementor#20162]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The last elementor update turn my images blurry. In the backoffice it doesn't show any error but online, the column background header images appear all blurry.

### Steps to reproduce

![Sem Título](https://user-images.githubusercontent.com/84964848/198341036-66e10582-1dc2-4e62-9f40-4848016c0c01.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.32
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://caroldebritopalma.com
	Home URL: https://caroldebritopalma.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: 0
	Admin Email: valtervvieira@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	All in One SEO
		Version: 4.2.6.1
		Author: All in One SEO Team

	Checkout Field Editor for WooCommerce
		Version: 1.7.2
		Author: ThemeHigh

	Direct Checkout for WooCommerce
		Version: 2.7.1
		Author: QuadLayers

	Elementor
		Version: 3.9.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev5
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.28
		Author: Facebook

	Google Analytics for WordPress by MonsterInsights
		Version: 8.9.1
		Author: MonsterInsights

	Google Listings and Ads
		Version: 2.2.0
		Author: WooCommerce

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 9.0.338
		Author: HubSpot

	Jetpack
		Version: 11.4
		Author: Automattic

	LoginPress - Customizing the WordPress Login Screen.
		Version: 1.6.2
		Author: WPBrigade

	Multibanco, MB WAY, Credit card and Payshop (IfthenPay) for WooCommerce
		Version: 6.4.0
		Author: PT Woo Plugins (by Webdados)

	OptinMonster
		Version: 2.10.0
		Author: OptinMonster Popup Builder Team

	Prime Slider
		Version: 3.1.3
		Author: BdThemes

	SiteGround Central
		Version: 2.0.9
		Author: SiteGround

	SiteGround Optimizer
		Version: 7.2.5
		Author: SiteGround

	SiteGround Security
		Version: 1.3.5
		Author: SiteGround

	WooCommerce
		Version: 7.0.0
		Author: Automattic

	WooCommerce Colors
		Version: 1.0.7
		Author: WooThemes

	WooCommerce Payments
		Version: 4.9.0
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

	WooLentor - WooCommerce Elementor Addons + Builder
		Version: 2.4.6
		Author: HasThemes

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP Encryption - One Click SSL & Force HTTPS
		Version: 5.8.0
		Author: WP Encryption SSL

	WPForms Lite
		Version: 1.7.7.2
		Author: WPForms

	WP Go Maps (formerly WP Google Maps)
		Version: 9.0.12
		Author: WP Go Maps

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

== Elements Usage ==
	
	container : 3
		container : 6
		form : 1
		heading : 3
		icon : 1
		image : 1
		nav-menu : 1
		social-icons : 2
		theme-site-logo : 1
	footer : 1
		container : 5
		form : 1
		heading : 3
		nav-menu : 1
		social-icons : 1
	header : 2
		container : 2
		icon : 2
		social-icons : 1
		theme-site-logo : 2
		woocommerce-menu-cart : 1
	page : 0
		container : 2
		divider : 1
		woocommerce-cart : 1
	popup : 2
		button : 2
		container : 5
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	product : 1
		container : 6
		star-rating : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	section : 3
		divider : 1
		form : 1
		heading : 4
		icon-list : 1
		text-editor : 1
	widget : 0
		button : 1
		image : 1
		woocommerce-products : 1
	wp-post : 0
		container : 2
		heading : 1
		woolentor-product-archive-addons : 1
	wp-page : 12
		animated-headline : 1
		button : 3
		container : 13
		divider : 2
		form : 2
		heading : 17
		icon-list : 2
		image : 4
		prime-slider-fiestar : 1
		social-icons : 1
		text-editor : 8
		video : 2
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-products : 1
	product-archive : 4
		container : 4
		heading : 3
		wc-archive-products : 2
		woocommerce-products : 2
	error-404 : 1
		button : 1
		heading : 3
		image-carousel : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 372022-10-03 23:01:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-23 22:56:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-23 22:56:34 [info] elementor::elementor_updater Started 
2022-10-23 22:56:34 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-23 22:56:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-23 22:56:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-26 18:22:28 [info] elementor-pro::elementor_pro_updater Started 
2022-10-26 18:22:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-26 18:22:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-26 18:22:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev4',
)]
2022-10-27 11:32:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-27 11:32:39 [info] elementor::elementor_updater Started 
2022-10-27 11:32:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-27 11:32:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-27 11:32:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-27 13:37:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]
2022-10-27 13:37:03 [info] elementor-pro::elementor_pro_updater Started 
2022-10-27 13:37:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-27 13:37:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-27 13:37:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]

PHP: showing 3 of 3PHP: 2022-09-20 10:30:28 [notice X 3538][/home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 09:05:37 [notice X 80][/home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/bdthemes-prime-slider-lite/traits/query-controls/select-input/dynamic-select.php(124): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-22 12:59:06 [notice X 13][/home/customer/www/caroldebritopalma.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-09-21 10:11:18 [error X 2][https://caroldebritopalma.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:1061493] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-10-27 13:28:58 [error X 39][https://caroldebritopalma.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Cannot read properties of undefined (reading \'tools\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Prime Slider: Incompatible
	WooLentor - WooCommerce Elementor Addons + Builder: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	WooLentor - WooCommerce Elementor Addons + Builder: Incompatible

**Comment by BlackBike** [comment]
Had the same issue after update to 3.8.0-dev11. Turning off Elemenor Beta fixed the blurry image issue for me.

**Comment by wigaulogy** [comment]
Since yesterday, I have the same issue.
videos and images are blurry. But on elementor, it shows as if it works.
I turned off elementor beta as blackbike suggested, and now it works again.
Thank you. 
i was so stressed

**Comment by BlackBike** [comment]
> 

Glad it worked!

**Comment by nicholaszein** [comment]
Hello @ValterVV,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

It's also worth mentioning that the Elementor Developer Edition **SHOULDN'T BE USED ON PRODUCTION WEBSITES** as it's built to be used by developers to test **unstable new features**.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards,

Nick
