### ISSUE TITLE
❌ Invalid Issue: Google Font loaded by Elementor backend

### ISSUE THREAD

**Issue by elosha** [elementor/elementor#20169]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It seems Elementor is loading a Google Font in the Wordpress backend:
`<link rel='stylesheet' id='elementor-admin-top-bar-fonts-css'  href='[https://fonts.googleapis.com/css2?family=Roboto&#038;display=swap&#038;ver=3.7.8](view-source:https://fonts.googleapis.com/css2?family=Roboto&display=swap&ver=3.7.8)' media='all' />`

a) This is unnecessary – the WP backend already has a font.
b) Just loading Google Fonts is not GDPR compliant.
c) It is loaded even on non-Elementor pages!

### Steps to reproduce

Install Elementor. Look at backend HTML output.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Wordpress 6.0.1
Elementor (Pro) 3.7.8

**Comment by nicholaszein** [comment]
Hey @elosha, 

Thank you for submitting your issue. 🙏 

### ⛔ While reviewing your report, we noticed it was missing some key pieces of information.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

* **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as defined in our guidelines.

Without them, we simply can't help. 😕 

⚠️ Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Best regards
