### ISSUE TITLE
[⌛ Awaiting Feedback] WordPress Elementor Page issue with binding REST API

### ISSUE THREAD

**Issue by gauravsarwal** [elementor/elementor#20168]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

We are trying to integrate a REST API in one of page created using Element or and have hard time to bind the value because we cannot provide Id or name to html elements like we do in a normal page when use Javascript/Jquery to DOM (document object model) manipulation. We have to use syntax like this:

document.querySelectorAll('#advisor-contact > div > div> div > div')[1].querySelector('a > span').innerText

Such code is problematic and requires a lot of maintenance again and again if the structure of page change. We read some articles on the web and it says Elementor Pro has a way to provide tag to dynamic content. I am not sure if it is talking about giving Id to HTML elements on a page created using Elementor Pro or something else. Considering our use case please suggest/guide us how can we bind response of an REST API on a page created using Elementor. Please provide some links to documentation if available.

### Describe the solution you'd like

I want some way by which I can provide Id or name to html elements on a page created using elementor or some way on page builder to integrate an REST API and refresh it depending upon some event on page which can be a click of button etc.

### Describe alternatives you've considered

I tried this code:

document.querySelectorAll('#advisor-contact > div > div> div > div')[1].querySelector('a > span').innerText

### Additional context

No option to provide name/id to html elements.

**Comment by nicholaszein** [comment]
Hello @gauravsarwal,

Thanks for your feedback! 🙏 

🧐 While reviewing your request we noticed it was missing the following key information:

* Prerequisites.
* **Detailed Description and examples.**: From your description, it wasn't clear which widget you are trying to target. Next time, please provide visual and complete textual examples.
* **System Info**: We need information about your environment to be able to understand what is going on. You can find how to get the System Info [here](https://elementor.com/help/systems-info/).

You can find Elementor's documentation in the [Help Center](https://elementor.com/help/). Please read the documentation before submitting help questions. Especially the following articles:

- How to use the Advanced Tab to add ID and Classes to elements: https://elementor.com/help/advanced-tab/
- Intro to Dynamic Content: https://elementor.com/help/intro-to-dynamic-content/
- Dynamic Content: https://elementor.com/help/dynamic-content/
- Dynamic Tags: https://elementor.com/help/dynamic-tags-pro/
- Use a shortcode: https://elementor.com/help/shortcode-widget/
- Dynamic Shortcode: https://elementor.com/help/dynamic-shortcode-pro/
- Dynamic Request Parameter: https://elementor.com/help/dynamic-request-parameter-pro/
- Developers Documentation: https://developers.elementor.com/

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Take care,

Nick
