### ISSUE TITLE
❌ Invalid Issue: Cant load the page in admin mode

### ISSUE THREAD

**Issue by paraeltrafico** [elementor/elementor#20164]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Can't load correctly the page in Admin Mode

### Steps to reproduce

1. Log in in wp admin mode
2. Edit a page
3. Can't view correctly the page in admin mode

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 10 v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://www.mhe.gob.bo
	Home URL: https://www.mhe.gob.bo
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: es
	Timezone: -4
	Admin Email: user@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 3.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 OPR/92.0.0.0

== Active Plugins ==
	BackWPup
		Version: 3.10.0
		Author: Inpsyde GmbH

	Disable REST API
		Version: 1.7
		Author: Dave McHale

	Ditty
		Version: 3.0.29
		Author: Metaphor Creations

	Download Manager
		Version: 3.2.58
		Author: W3 Eden, Inc.

	Elementor
		Version: 3.9.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev5
		Author: Elementor.com

	Embed Any Document
		Version: 2.7.1
		Author: Awsm Innovations

	Error Log Monitor
		Version: 1.7.2
		Author: Janis Elsts

	Essential Addons for Elementor
		Version: 5.4.1
		Author: WPDeveloper

	Everest Forms
		Version: 1.9.5
		Author: WPEverest

	FileBird
		Version: 3.1.1
		Author: Ninja Team

	Happy Elementor Addons
		Version: 3.7.1
		Author: weDevs

	News Ticker Widget for Elementor
		Version: 1.1
		Author: FlickDevs

	PDF Embedder
		Version: 4.6.4
		Author: WP PDF Embedder Team

	Popup Builder
		Version: 4.1.14
		Author: Sygnoos

	Re-Add Text Justify Button
		Version: 0.1.4
		Author: Salvatore Cordiano

	Secondary Title
		Version: 2.0.8
		Author: Kolja Nolte

	Shortcodes Ultimate
		Version: 5.12.3
		Author: Vladimir Anokhin

	Sina Extension for Elementor
		Version: 3.4.3
		Author: SinaExtra

	Smart Slider 3
		Version: 3.5.1.11
		Author: Nextend

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.35
		Author: Sucuri Inc.

	Timeline Widget For Elementor
		Version: 1.4
		Author: Cool Plugins

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	Velvet Blues Update URLs
		Version: 3.2.10
		Author: VelvetBlues.com

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WPDM - Gutenberg Blocks
		Version: 2.1.8
		Author: WordPress Download Manager

	WP fail2ban
		Version: 4.4.0.8
		Author: Charles Lecklider

	WP Responsive Recent Post Slider
		Version: 3.1
		Author: WP OnlineSupport, Essential Plugin

	WP Rocket
		Version: 3.4.2.2
		Author: WP Media

	WP Statistics
		Version: 13.2.7
		Author: VeronaLabs

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

== Must-Use Plugins ==
	WP Migrate DB Compatibility
		Version: 1.2
		Author: Delicious Brains

== Uso de los elementos ==
	
	archive : 2
		archive-posts : 1
		heading : 1
	footer : 1
		heading : 2
		search-form : 1
		social-icons : 1
	header : 2
		icon-list : 1
		image : 1
		nav-menu : 2
		search-form : 1
		social-icons : 1
		theme-site-logo : 1
	wp-post : 2
		html : 2
		text-editor : 1
	wp-page : 16
		accordion : 1
		audio : 1
		button : 4
		call-to-action : 10
		divider : 26
		facebook-embed : 1
		flip-box : 3
		gallery : 1
		heading : 14
		icon : 1
		image : 26
		image-box : 4
		portfolio : 4
		posts : 2
		progress : 1
		shortcode : 1
		spacer : 2
		tabs : 1
		text-editor : 28
		video : 3
	single-post : 4
		container : 2
		divider : 18
		elementor-news-ticker : 1
		facebook-page : 1
		gallery : 3
		heading : 13
		html : 6
		image : 4
		image-box : 10
		media-carousel : 3
		portfolio : 4
		post-info : 3
		post-navigation : 2
		posts : 5
		search-form : 1
		share-buttons : 2
		theme-post-content : 2
		theme-post-excerpt : 2
		theme-post-featured-image : 1
		theme-post-title : 2
		video : 1
	single-page : 2
		theme-post-content : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		container : 1
		heading : 3
		icon : 1
		posts : 1
		search-form : 1
	loop-item : 1
		container : 3
		image : 2

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Activo
	Mejoras de accesibilidad: Activo
	Puntos de ruptura personalizados adicionales: Activo
	Import Export Website Kit: Activo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Activo
	Por defecto, el nuevo constructor de temas: Activo
	Páginas de destino: Activo
	Muestrario de colores: Activo
	Widgets favoritos: Activo
	Barra superior de administración: Activo
	Lazy Load Background Images: Activo por defecto
	Transiciones de páginas: Activo
	Notes: Activo
	Bucle: Activo por defecto
	Envíos de formulario: Activo
	Ajuste de scroll: Activo

== Registro ==
	
JS: showing 4 of 4JS: 2022-10-14 15:13:16 [error X 2][https://www.mhe.gob.bo/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767848] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-10-14 22:24:20 [error X 1][https://www.mhe.gob.bo/wp-content/plugins/happy-elementor-addons/assets/vendor/threesixty-rotation/circlr.min.js?ver=3.7.0:2:3437] Cannot read properties of null (reading \'getAttribute\') 
JS: 2022-10-27 15:45:37 [error X 31][https://www.mhe.gob.bo/wp-content/plugins/happy-elementor-addons/assets/js/happy-addons.min.js?ver=3.7.1:124:51] Cannot read properties of undefined (reading \'handlers\') 
JS: 2022-10-27 15:45:38 [error X 31][https://www.mhe.gob.bo/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Cannot read properties of undefined (reading \'tools\') 

PHP: showing 9 of 9PHP: 2022-10-14 14:57:26 [notice X 224][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/license/admin.php::303] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-14 18:24:22 [notice X 2][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor/includes/widgets/menu-anchor.php::156] Undefined index: anchor [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-19 18:05:27 [notice X 1][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/modules/query-control/module.php::749] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-26 11:03:15 [notice X 3][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/www.mhe.gob.bo/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-10-27 11:46:00 [warning X 2][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/www.mhe.gob.bo/wp-content/uploads/elementor/css/post-8.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-27 11:55:36 [warning X 1][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/www.mhe.gob.bo/wp-content/uploads/elementor/css/post-3.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-27 11:55:39 [warning X 1][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/www.mhe.gob.bo/wp-content/uploads/elementor/css/global.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-27 13:51:18 [warning X 1][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/var/www/www.mhe.gob.bo/wp-content/uploads/elementor/css/post-1.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-27 14:59:09 [notice X 5][/var/www/www.mhe.gob.bo/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 292022-10-23 11:20:17 [info] elementor::elementor_updater Started 
2022-10-23 11:20:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-23 11:20:17 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-23 11:20:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-23 11:20:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-27 11:18:15 [info] elementor::elementor_updater Started 
2022-10-27 11:18:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-27 11:18:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-27 11:18:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-27 11:18:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-27 14:22:04 [info] elementor-pro::elementor_pro_updater Started 
2022-10-27 14:22:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-27 14:22:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-27 14:22:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev4',
)]
2022-10-27 14:58:31 [info] elementor-pro::elementor_pro_updater Started 
2022-10-27 14:58:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-27 14:58:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-27 14:58:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]
2022-10-27 14:58:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]
2022-10-27 14:58:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada
	Essential Addons for Elementor: Compatibilidad no especificada
	Happy Elementor Addons: Compatibilidad no especificada
	News Ticker Widget for Elementor: Compatibilidad no especificada
	Sina Extension for Elementor: Compatibilidad no especificada
	Timeline Widget For Elementor: Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @paraeltrafico,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

We can't reproduce your issue, and it seems you're not only running multiple Elementor add-ons that might be conflicting with Elementor, but you're also running the Elementor Developer Edition, which **SHOULDN'T BE USED ON PRODUCTION WEBSITES** as it's built to be used by developers to test **unstable new features**.

## ⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

### What you can try to do is follow the troubleshooting steps outlined below:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment! 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If the issue persists, try contacting Elementor support (for Pro Users). To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

Regards,

Nick
