### ISSUE TITLE
❌ Invalid Issue: I logged in for my monthly designs and am told I am no longer a member!  My membership doesn't expire until Jan. 18th.  I have no idea what Elementor is ...but you need to fix your problem.

### ISSUE THREAD

**Issue by gharkness2** [elementor/elementor#20175]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I got notice that my designs are ready from Design Club.  I can't log in and when I reset my password, I'm told I am not a member.

I have no idea what Elementor is - this is your problem, not mine.

### Steps to reproduce

Try logging in under my name, gharkness@gmail.com.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Nope.  This is NOT a system problem.

**Comment by nicholaszein** [comment]
Hey @gharkness2, 

Thank you for submitting your issue! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information.

- **Clear and concise title:** You did not write a clear and concise title;
- **Prerequisites:** please search the repository before submitting an issue;
- **Description:** you did not provide a detailed description and examples of your issue. We do not have a Design Club.
- **Steps to replicate:** You did not provide any way for us to try to reproduce your issue. Logging in where?;
- **Isolating the Problem:** You need to make sure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Without them, we simply can't help. 😕 

👉 Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


#### For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Best regards
