### ISSUE TITLE
[⌛ Awaiting Feedback] 🐞 Bug Report: Video playlist raises error in handleFullScreenChange: Uncaught (in promise) TypeError: this.playerObject.h.addEventListener is not a function

### ISSUE THREAD

**Issue by typeoneerror** [elementor/elementor#20176]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Upgraded to latest elementor and issue persists.

When using the Video Playlist plugin, an error is raised when the player is loaded.

```
this.playerObject.h.addEventListener is not a function
handleFullScreenChange     /wp-content/plugins/elementor-pro/assets/js/video-playlist.0c9d14b28f7b8990e895.bundle.min.js:2
```

From this snippet from the `playerYoutube` class from the looks of it:

```
  handleFullScreenChange(callback) {
    this.playerObject.h.addEventListener('fullscreenchange', () => {
      callback(document.fullscreenElement);
    });
  }
```

I think possibly that `.h.` could be a typo? `playerObject` seems to be a `video` element which I don't think has an `h` property.

### Steps to reproduce

Add a video playlist to the page

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.38
	PHP Version: 7.4.32
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Max Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: XXXX
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Fathom Analytics
		Version: 3.0.6
		Author: Conva Ventures Inc

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

== Elements Usage ==
	
	archive : 1
		button : 1
		heading : 1
		image : 1
		posts : 1
		template : 1
		theme-archive-title : 1
	footer : 1
		text-editor : 2
	header : 2
		button : 1
		image : 3
		nav-menu : 1
		theme-site-logo : 1
	page : 6
		button : 19
		divider : 7
		heading : 86
		html : 12
		icon-box : 29
		icon-list : 22
		image : 69
		image-box : 22
		posts : 1
		price-table : 4
		spacer : 6
		template : 1
		testimonial : 21
		text-editor : 73
		toggle : 2
	section : 11
		button : 7
		heading : 7
		html : 1
		icon-box : 3
		image : 7
		text-editor : 15
		theme-site-logo : 2
	widget : 0
		button : 3
		html : 1
		text-editor : 2
	wp-page : 10
		button : 22
		divider : 13
		heading : 105
		html : 5
		icon-box : 29
		icon-list : 11
		image : 54
		image-box : 11
		nav-menu : 4
		posts : 2
		price-table : 2
		spacer : 6
		template : 5
		testimonial : 15
		text-editor : 83
		toggle : 2
		video : 1
		video-playlist : 1
	single-post : 1
		button : 1
		heading : 2
		image : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		template : 1
		theme-post-content : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 302022-06-08 18:45:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-08 18:45:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-08 18:45:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.7.1',
)]
2022-06-08 18:45:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.7.1',
)]
2022-06-16 18:47:08 [info] elementor-pro::elementor_pro_updater Started 
2022-06-16 18:47:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-06-16 18:47:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-06-16 18:47:08 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-06-16 18:47:09 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-06-16 18:47:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-06-16 18:47:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-10-28 20:03:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.8',
)]
2022-10-28 20:03:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-28 20:03:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-28 20:03:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-28 20:03:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-28 20:03:06 [info] elementor::elementor_updater Started 
2022-10-28 20:03:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-28 20:03:08 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-28 20:03:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.8',
)]

PHP: showing 5 of 5PHP: 2022-06-10 10:33:17 [notice X 33][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-21 23:31:50 [notice X 1][/www/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-27 21:23:46 [notice X 3][/www/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-14 02:26:06 [error X 11][/www/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /www/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /www/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /wordpress/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}('')
#5 /wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#7  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-23 02:23:38 [notice X 1][/www/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-06-17 20:38:56 [error X 785][https://example.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2022-06-17 21:02:53 [error X 1][https://example.com/wp-includes/js/quicktags.min.js?ver=5.9.3:2:3058] o is undefined 
JS: 2022-06-19 04:15:00 [error X 1][https://example.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.7.2:3:104952] t.templateIdView is undefined 
JS: 2022-06-23 15:59:36 [error X 24][https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:450631] T.getContainer is not a function 
JS: 2022-07-27 21:27:44 [error X 1][https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:362263] this.container is undefined 
JS: 2022-10-12 19:44:54 [error X 1][https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:547595] V.view.children.findByIndex(...) is undefined 
JS: 2022-10-22 23:29:50 [error X 6][https://example.com/wp-content/plugins/elementor-pro/assets/js/preloaded-elements-handlers.min.js?ver=3.7.2:2:67236] this.stretchElement is null 
JS: 2022-10-28 21:59:26 [error X 1][https://example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.8:2:30926] elementor.settings.page is undefined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @typeoneerror! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @typeoneerror,

Elementor Pro v.3.8 was released last week, and a lot of bugs were fixed. While testing the Video Playlist widget in this new version, I couldn't reproduce your issue.

Can you confirm this issue still exist with the latest version of Elementor (3.8.0) and Elementor Pro (3.8.1)?

**Comment by typeoneerror** [comment]
@nicholaszein upgraded my staging server to latest and it appears as if it's been resolved.

**Comment by nicholaszein** [comment]
Hello @typeoneerror!

I'm glad to know it was solved, thanks for the feedback! 🙏
