### ISSUE TITLE
❌ Invalid Issue: take a long time to schedule a post

### ISSUE THREAD

**Issue by Kazi1959** [elementor/elementor#20177]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It is taking a long time to schedule and sometimes to publish a post. This is not helping. Thanks. And we found this line that may be responsible, however, we can't locate it where it says it is:

Notice: Undefined index: sr in /home/worldfut/latestmalaysia.com/wp-content/plugins/ietpack/modules/related-posts/ietpack-related-posts.phoonline1454

Help pls. 

Thanks

Kazi

### Steps to reproduce

When I open a new page on wordpress, i get the message pasted above from jetpack 

When i save a post, then i try to schedule it, the schedule button does not work

I have to wait a minute or so for it to start scheduling

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<div style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.15 |  
PHP Version: | 7.3.33 |  
PHP Memory Limit: | 2G |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 1G |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div></div><h3 style="display: block; font-weight: 600; color: rgb(29, 35, 39); font-size: 1.3em; margin: 1em 0px; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Copy &amp; Paste Info</h3><div id="elementor-system-info-raw" style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><label id="elementor-system-info-raw-code-label" for="elementor-system-info-raw-code" style="cursor: pointer; vertical-align: middle; padding: 5px; display: block;">You can copy the below info as simple text with Ctrl+C / Ctrl+V:</label><textarea id="elementor-system-info-raw-code" readonly="" style="box-sizing: border-box; font-family: inherit; font-size: 14px; font-weight: inherit; overflow: auto; padding: 2px 6px; line-height: 1.42857; resize: vertical; box-shadow: transparent 0px 0px 0px; border-radius: 4px; border: 1px solid rgb(140, 143, 148); background-color: rgb(240, 240, 241); color: rgb(44, 51, 56); width: 1249px; height: 200px;"></textarea></div><hr style="border-width: 1px 0px; border-right-style: initial; border-left-style: initial; border-right-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(220, 220, 222); border-bottom-style: solid; border-bottom-color: rgb(246, 247, 247); color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><form action="https://latestmalaysia.com/wp-admin/admin-ajax.php" method="post" style="color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="submit" class="button button-primary" value="Download System Info" style="box-sizing: border-box; font-family: inherit; font-size: 13px; font-weight: inherit; margin: 0px; display: inline-block; text-decoration: none; line-height: 2.15385; min-height: 30px; padding: 0px 10px; cursor: pointer; border-width: 1px; border-style: solid; appearance: none; border-radius: 3px; white-space: nowrap; color: rgb(255, 255, 255); border-color: rgb(34, 113, 177); background: rgb(34, 113, 177); vertical-align: top; text-shadow: none;"></form>Server Environment		
Operating System:	Linux	
Software:	LiteSpeed	
MySQL version:	MariaDB Server v10.5.15	
PHP Version:	7.3.33	
PHP Memory Limit:	2G	
PHP Max Input Vars:	10000	
PHP Max Post Size:	1G	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.0.3	
Site URL:	https://latestmalaysia.com	
Home URL:	https://latestmalaysia.com	
WP Multisite:	No	
Max Upload Size:	1 GB	
Memory limit:	40M	
Max Memory limit:	2G	
Permalink Structure:	/%year%/%monthnum%/%day%/%postname%/	
Language:	en-US	
Timezone:	Asia/Kuala_Lumpur	
Admin Email:	latestmalaysianews@gmail.com	
Debug Mode:	Active	
Theme		
Name:	Adore News	
Version:	1.0.3	
Author:	Adore Themes	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36	
Active Plugins		
[A2 Optimized WP](https://wordpress.org/plugins/a2-optimized/) - 2.1.4.6.2.2	By [A2 Hosting](https://www.a2hosting.com/)	
AdAce - 1.3.25	By [bringthepixel](http://www.bringthepixel.com/)	
[Ad Inserter](https://adinserter.pro/documentation) - 2.7.20	By [Igor Funa](http://igorfuna.com/)	
[Akismet Anti-Spam](https://akismet.com/) - 4.1.11	By [Automattic](https://automattic.com/wordpress-plugins/)	
[Classic Editor](https://wordpress.org/plugins/classic-editor/) - 1.6.2	By [WordPress Contributors](https://github.com/WordPress/classic-editor/)	
[Contact Form DB - Elementor](https://webacetechs.in/) - 1.8.0	By [Web Ace Tech Services](https://webacetechs.in/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.9.0-dev2	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)	
[ElementsKit Lite](https://products.wpmet.com/elementskit) - 2.7.3	By [Wpmet](https://wpmet.com/)	
[Envato Market](https://envato.com/market-plugin/) - 2.0.7	By [Envato](https://envato.com/)	
[EWWW Image Optimizer](https://wordpress.org/plugins/ewww-image-optimizer/) - 6.9.1	By [Exactly WWW](https://ewww.io/)	
[Export media with selected content](https://wordpress.org/plugins/export-media-with-selected-content/) - 2.1.4	By [Joost de Keijzer](https://dkzr.nl/)	
[Facebook for WordPress](https://www.facebook.com/business/help/881403525362441) - 3.0.7	By [Facebook](https://www.facebook.com/)	
[Head, Footer and Post Injections](https://www.satollo.net/plugins/header-footer) - 3.2.5	By [Stefano Lissa](https://www.satollo.net/)	
[Head and Footer Scripts Inserter](https://github.com/ArthurGareginyan/header-and-footer-scripts-inserter) - 4.52	By [Space X-Chimp](https://www.spacexchimp.com/)	
[Image SEO](https://imageseo.io/) - 2.0.7	By [Image SEO](https://imageseo.io/)	
[Jetpack](https://jetpack.com/) - 11.4	By [Automattic](https://jetpack.com/)	
[LiteSpeed Cache](https://www.litespeedtech.com/products/cache-plugins/wordpress-acceleration) - 5.2.1	By [LiteSpeed Technologies](https://www.litespeedtech.com/)	
[Site Kit by Google](https://sitekit.withgoogle.com/) - 1.85.0	By [Google](https://opensource.google.com/)	
[Social Snap Lite](https://socialsnap.com/) - 1.1.20	By [Social Snap](https://socialsnap.com/)	
[Squirrly SEO (Peaks)](https://wordpress.org/plugins/squirrly-seo/) - 12.1.13	By [Squirrly](https://plugin.squirrly.co/)	
[Warp iMagick - Image Compressor](https://wordpress.org/plugins/warp-imagick/) - 1.8	By [PageSpeed Club](https://profiles.wordpress.org/pagespeedclub/)	
What's Your Reaction? - 1.3.18	By [bringthepixel](http://www.bringthepixel.com/)	
[WooCommerce](https://woocommerce.com/) - 5.6.2	By [Automattic](https://woocommerce.com/)	
[Wordfence Security](http://www.wordfence.com/) - 7.7.1	By [Wordfence](http://www.wordfence.com/)	
[WordPress Importer](https://wordpress.org/plugins/wordpress-importer/) - 0.7	By [wordpressdotorg](https://wordpress.org/)	
[WP File Manager](https://wordpress.org/plugins/wp-file-manager) - 7.1.1	By [mndpsingh287](https://profiles.wordpress.org/mndpsingh287)	
[WPForms Lite](https://wpforms.com/) - 1.6.7.3	By [WPForms](https://wpforms.com/)	
[WP GDPR Compliance](https://www.wpgdprc.com/) - 1.5.9	By [Cookie Information](https://cookieinformation.com/)	
Elementor Experiments		
Optimized DOM Output: 	Active by default
Improved Asset Loading: 	Active by default
Improved CSS Loading: 	Active by default
Inline Font Icons: 	Inactive by default
Accessibility Improvements: 	Active
Additional Custom Breakpoints: 	Active by default
Import Export Website Kit: 	Active by default
Hide native WordPress widgets from search results: 	Active by default
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Active by default
Landing Pages: 	Active by default
Color Sampler: 	Active by default
Favorite Widgets: 	Active by default
Admin Top Bar: 	Active by default
Log[Clear Log](https://latestmalaysia.com/wp-admin/admin.php?page=elementor-system-info&elementor-clear-log=1&_wpnonce=1af55e4582#elementor-clear-log)		
PHP: showing 2 of 2
PHP: 2021-08-26 14:11:28 [notice X 1][/home/worldfut/latestmalaysia.com/wp-content/plugins/elementor/includes/template-library/sources/local.php::1407] Undefined index: content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-10 11:02:19 [warning X 1][/home/worldfut/latestmalaysia.com/wp-content/plugins/elementor-beta/modules/developer-edition/core-version-control.php::183] uasort() expects parameter 1 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
Log: showing 6 of 6
2021-08-29 05:46:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.4.2',
)]
2021-08-29 05:46:53 [info] elementor::elementor_updater Started 
2021-08-29 05:46:53 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-29 05:46:54 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-29 05:46:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.4.2',
)]
2021-08-29 05:46:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.4.2',
)]
Elementor - Compatibility Tag		
 Contact Form DB - Elementor 	 Compatibility not specified 
Copy & Paste Info
You can copy the below info as simple text with Ctrl+C / Ctrl+V:
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.15
	PHP Version: 7.3.33
	PHP Memory Limit: 2G
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://latestmalaysia.com
	Home URL: https://latestmalaysia.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 2G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Asia/Kuala_Lumpur
	Admin Email: latestmalaysianews@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Adore News
	Version: 1.0.3
	Author: Adore Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	A2 Optimized WP
		Version: 2.1.4.6.2.2
		Author: A2 Hosting

	AdAce
		Version: 1.3.25
		Author: bringthepixel

	Ad Inserter
		Version: 2.7.20
		Author: Igor Funa

	Akismet Anti-Spam
		Version: 4.1.11
		Author: Automattic

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Contact Form DB - Elementor
		Version: 1.8.0
		Author: Web Ace Tech Services

	Elementor
		Version: 3.9.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.3
		Author: Wpmet

	Envato Market
		Version: 2.0.7
		Author: Envato

	EWWW Image Optimizer
		Version: 6.9.1
		Author: Exactly WWW

	Export media with selected content
		Version: 2.1.4
		Author: Joost de Keijzer

	Facebook for WordPress
		Version: 3.0.7
		Author: Facebook

	Head, Footer and Post Injections
		Version: 3.2.5
		Author: Stefano Lissa

	Head and Footer Scripts Inserter
		Version: 4.52
		Author: Space X-Chimp

	Image SEO
		Version: 2.0.7
		Author: Image SEO

	Jetpack
		Version: 11.4
		Author: Automattic

	LiteSpeed Cache
		Version: 5.2.1
		Author: LiteSpeed Technologies

	Site Kit by Google
		Version: 1.85.0
		Author: Google

	Social Snap Lite
		Version: 1.1.20
		Author: Social Snap

	Squirrly SEO (Peaks)
		Version: 12.1.13
		Author: Squirrly

	Warp iMagick - Image Compressor
		Version: 1.8
		Author: PageSpeed Club

	What's Your Reaction?
		Version: 1.3.18
		Author: bringthepixel

	WooCommerce
		Version: 5.6.2
		Author: Automattic

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WP File Manager
		Version: 7.1.1
		Author: mndpsingh287

	WPForms Lite
		Version: 1.6.7.3
		Author: WPForms

	WP GDPR Compliance
		Version: 1.5.9
		Author: Cookie Information

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 2 of 2PHP: 2021-08-26 14:11:28 [notice X 1][/home/worldfut/latestmalaysia.com/wp-content/plugins/elementor/includes/template-library/sources/local.php::1407] Undefined index: content [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-10 11:02:19 [warning X 1][/home/worldfut/latestmalaysia.com/wp-content/plugins/elementor-beta/modules/developer-edition/core-version-control.php::183] uasort() expects parameter 1 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 6 of 62021-08-29 05:46:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.4.2',
)]
2021-08-29 05:46:53 [info] elementor::elementor_updater Started 
2021-08-29 05:46:53 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-29 05:46:54 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-29 05:46:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.4.2',
)]
2021-08-29 05:46:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.4.2',
)]

== Elementor - Compatibility Tag ==
	
	Contact Form DB - Elementor: Compatibility not specified

**Comment by nicholaszein** [comment]
Hello @Kazi1959,

Thank you for reaching out! 🙏 

Your issue seems related to the **JetPack** plugin, not an Elementor issue. Please contact JetPack's support.

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards
