### ISSUE TITLE
✅ 🐞  Bug Report: RTL - Add Container Dialog shows inverted structure icons

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20184]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

In RTL, the preview of some containers that I have specified in the image below are displayed incorrectly. 

![Screenshot (853)](https://user-images.githubusercontent.com/77163248/198876149-d97e4d04-24ad-4e12-8379-497787b95107.png)

If we choose any of the structures I've marked above in the RTL, the containers will be added exactly the opposite. 

### Steps to reproduce

1- Make sure the website is RTL.
2- Select any of the 4 structures I mentioned above to add the container.

**Containers are added correctly (according to RTL) but the structure preview image is not displayed correctly.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-01-11-2022.txt](https://github.com/elementor/elementor/files/9908810/system-info-localhost-01-11-2022.txt)

**Comment by nicholaszein** [comment]
Hello @79ho3ein! 

Thank you for bringing this to our attention! 🙏 

I can recreate your issue on Elementor v3.8.0.

### ⚠️ Please, ALWAYS SHARE YOUR SYSTEM INFO! We can't properly validate your issue without this information.

Make sure to update your original post with the Elementor > System Info > Copy & Paste section. Until then, we won't validate your issue. 

To learn how to get the System Info please check this article: https://elementor.com/help/systems-info/

Best regards

**Comment by rami-elementor** [comment]
@79ho3ein Good catch. I'll if we have an open ticket to fix it. If not, I'll try to ask to prioritize this issue.

**Comment by 79ho3ein** [comment]
thank you @rami-elementor

**Comment by 79ho3ein** [comment]
Hi @rami-elementor, @nicholaszein,

Is there any news about this matter being resolved? (Just to remind)

**Comment by rami-elementor** [comment]
@79ho3ein thank you for the reminder, we know about this bug, but it was not prioritized yet.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
