### ISSUE TITLE
✔️ 🚀 Feature Already Exists: Highlight all elements in the navigator that contain custom CSS (e.g. with a small icon)

### ISSUE THREAD

**Issue by SiteRider** [elementor/elementor#20180]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

During development, it often happens that you add custom code to many different elements on the page. Unfortunately it is not possible to recognize these elements without clicking through all elements one after the other.

This often makes it difficult to work efficiently and quickly with custom CSS. Transferring the CSS from the individual pages to a central CSS is also very time-consuming etc.

### Describe the solution you'd like

Mark all elements that contain custom CSS with an icon in the navigator.

**Comment by nicholaszein** [comment]
Hello there @SiteRider!

We have great news! 🙌 

### 📢 We're happy to announce that the feature you requested is already present in Elementor and Elementor Pro since **v2.6.0**! 🥳 

✔️ Please feel free to check it out [here](https://elementor.com/help/navigator-indicators/).

Cheers 🥂
