### ISSUE TITLE
[🧐 Evaluating] Elementor 3.8.0 - Not loading shortcodes in post content widget

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#20206]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi There,

After upgrading our site to 3.8.0 both Free and Pro it breaks the shortcodes inserted via gutenberg and loaded via post content widget. 

See some images: 
Not loading: https://imgur.com/a/PYPm3A9
Gutenberg: https://imgur.com/IoQfdPq
What is should do V3.7.8: https://imgur.com/TIwAur4

Thanks. 

### Steps to reproduce

See desc above. 
Load in some elementor templates via shortcode. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: (Ubuntu) v8.0.31
	PHP Version: 8.1.12
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://motokicx.com
	Home URL: https://motokicx.com
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 2048M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Brussels
	Admin Email: info@webtica.be
	Debug Mode: Inactive

== Theme ==
	Name: Webtica Thema
	Version: 1.0
	Author: Webtica
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 5.7.4
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 3.0.4
		Author: AdminColumns.com

	Advanced Custom Fields: Random String Field
		Version: 1.1.0
		Author: luke chapman

	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Advanced Forms Pro
		Version: 1.8.2
		Author: Hookturn with Fabian Lindfors

	Advanced Post Queries
		Version: 1.0.16
		Author: Shabti Kaplan

	CrowdSec
		Version: 1.9.0
		Author: CrowdSec

	Custom Order Numbers for WooCommerce
		Version: 1.3.5
		Author: Tyche Softwares

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	FacetWP
		Version: 4.1
		Author: FacetWP, LLC

	FacetWP - Elementor
		Version: 1.6.7
		Author: FacetWP, LLC

	FacetWP - Flyout menu
		Version: 0.8.1
		Author: FacetWP, LLC

	FacetWP - Range List
		Version: 0.7
		Author: FacetWP, LLC

	FacetWP - Time Since
		Version: 1.6.7
		Author: FacetWP, LLC

	FileBird
		Version: 5.0.8
		Author: Ninja Team

	Forminator
		Version: 1.19.0
		Author: WPMU DEV

	Frontend Reset Password
		Version: 1.2
		Author: Square One Media

	ManageWP - Worker
		Version: 4.9.14
		Author: GoDaddy

	Mollie Payments for WooCommerce
		Version: 7.3.3
		Author: Mollie

	SearchWP
		Version: 4.2.7
		Author: SearchWP

	Simple Local Avatars
		Version: 2.6.0
		Author: Jake Goldman, 10up

	Smush
		Version: 3.12.3
		Author: WPMU DEV

	Sticky Header Effects for Elementor
		Version: 1.5.5
		Author: Rwattner

	The SEO Framework
		Version: 4.2.5
		Author: The SEO Framework Team

	TotalSurvey
		Version: 1.6.1
		Author: TotalSuite

	Ultimate Addons for Elementor
		Version: 1.36.12
		Author: Brainstorm Force

	User Role Editor
		Version: 4.63.1
		Author: Vladimir Garagulya

	User Switching
		Version: 1.7.0
		Author: John Blackbourn & contributors

	WooCommerce
		Version: 7.0.0
		Author: Automattic

	WooCommerce EU Vat & B2B
		Version: 11.9
		Author: Lagudi Domenico

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WP All Export - ACF Export Add-On Pro
		Version: 1.0.4
		Author: Soflyy

	WP All Export Pro
		Version: 1.8.1
		Author: Soflyy

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	WP Users Media
		Version: 4.2.3
		Author: Damir Calusic

	Zapier for WordPress
		Version: 1.0.4
		Author: Zapier

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 322022-09-21 19:38:17 [info] elementor::elementor_updater Started 
2022-09-21 19:38:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-21 19:38:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-21 19:38:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-03 09:06:09 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 09:06:09 [info] elementor::elementor_updater Started 
2022-10-03 09:06:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 09:06:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 09:06:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-31 08:10:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 08:10:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-31 08:10:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-31 08:10:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 08:20:42 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 08:20:42 [info] elementor::elementor_updater Started 
2022-10-31 08:20:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-31 08:20:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-31 08:20:42 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-31 08:20:42 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-31 08:20:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]

PHP: showing 8 of 8PHP: 2022-09-16 13:44:17 [notice X 46][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: /home/motokicx/motokicx.com/public/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: /home/motokicx/motokicx.com/public/wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
#4: /home/motokicx/motokicx.com/public/wp-includes/plugin.php(476): WP_Hook -> do_action()
',
)]
PHP: 2022-09-21 19:06:07 [warning X 1742][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::59] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-10 16:07:40 [warning X 1][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 16:13:00 [notice X 15045][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-31 08:11:01 [notice X 27][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-31 08:11:07 [notice X 552][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-31 08:39:39 [notice X 10][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-10-31 08:48:09 [notice X 3][/home/motokicx/motokicx.com/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-10-03 08:26:21 [error X 38][https://motokicx.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.8:2:15625] Cannot read properties of undefined (reading \'global\') 
JS: 2022-10-12 14:12:02 [error X 2][https://motokicx.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view207\") has already been destroyed and cannot be used. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	FacetWP - Elementor: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hey @Webtica, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:


- **Steps to replicate:** You did not provide any way for us to reproduce your issue; Where and how are you using the Posts Content widget? In what context? Please provide detailed steps so we can try to reproduce your issue.
- **Isolating the Problem:** You need to ensure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. I see multiple plugins and 3rd-party addons installed. We do not provide support for 3rd-party themes and plugins.

Without them, we can't help. 😕 

👉 Please rectify the information above before we continue.

Best regards,

Nick

**Comment by Webtica** [comment]
Hi @nicholaszein ,

1. Steps to reproduce: 
- Create a single post template on the post post type. 
- Create a section as template and copy it's shortcode
- Paste the shortcode in the gutenberg editor and see if it shows up.

**Comment by nicholaszein** [comment]
Thanks for the feedback @Webtica! 🙏 

I'm going to investigate this and get back to you with my findings.

If possible, please share the origin of the shortcode, or if you're the one that created it, please share the snippet of code here.

Thanks!

**Comment by Webtica** [comment]
Hi @nicholaszein, the issue seems to be fixed now in the 3.8.1 release. 

Thank you, 
This issue may be closed.

**Comment by nicholaszein** [comment]
Thank you for your feedback @Webtica! 🙏 

I'm glad the issue has been solved for you!

Cheers 🥂
