### ISSUE TITLE
✔️ 🐞 Bug Report: ACF Dynamic data not rendering correctly  with template shortcode (ED-8562)

### ISSUE THREAD

**Issue by anandau** [elementor/elementor#20235]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

ACF Dynamic data tags are not outputting the data when added using a template shortcode. 
Testing with Elementor & Elementor Pro 3.8 and Hello Theme.  

**Some more info based on my debugging**

As per my understanding, this is happening due to a recent change in the function **get_field_from_current_item** from class **ElementorPro\Modules\DynamicTags\ACF\Module**

### Steps to reproduce

1) Create a Custom Post Type with some ACF custom Fields. 
2) Create an Elementor template of Section type and add a Heading widget with any dynamic ACF data tag selected. 
3) Create a single template for the Custom post type created in step 1.  You can add basic widgets like post-title, feature image etc. 
4) Add a heading widget to display the ACF custom field using dynamic tags. 
5) Add a shortcode of the template created in Step 2. 

 **Expected Output**
 Dynamic data tag (Heading widget) added directly in Single Template (Step 4) and Section template (Step 2), both should display the data. 
 
 **What's Happening**
 Dynamic data tag from shortcode is not displaying the data. 
 
 A valid use case for such implementation is when we want to display some dynamic data on a single template in tabs. In that case, each tag contains a shortcode that has dynamic data tag widgets. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.0.0
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: http://aepro-dev.local
	Home URL: http://aepro-dev.local/au
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: webtechanand@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 3
		ae-post-blocks-adv : 1
		archive-posts : 1
		nav-menu : 1
		theme-archive-title : 1
	header : 1
		nav-menu : 1
		search-form : 1
		theme-site-logo : 1
	page : 10
		ae-post-blocks : 3
		ae-post-title : 1
		button : 2
		divider : 5
		flip-box : 8
		form : 1
		heading : 20
		icon : 1
		icon-box : 3
		image : 2
		menu-anchor : 1
		spacer : 1
		testimonial-carousel : 1
		text-editor : 4
		theme-page-title : 1
	popup : 4
		ae-acf-gallery : 1
		button : 3
		heading : 3
		image : 2
		price-table : 1
		text-editor : 2
	section : 7
		ae-acf : 1
		ae-post-content : 1
		ae-post-title : 1
		heading : 1
		theme-post-title : 1
	single : 2
		ae-acf-repeater : 1
		ae-post-content : 1
		heading : 2
		theme-post-title : 2
	widget : 0
		ae-post-blocks : 1
		heading : 1
	wp-post : 4
		ae-acf : 19
		ae-acf-flexible-content : 1
		ae-acf-gallery : 1
		ae-acf-repeater : 6
		ae-custom-field : 8
		ae-portfolio : 1
		ae-post-blocks : 7
		ae-post-blocks-adv : 4
		ae-post-content : 5
		ae-post-image : 1
		ae-post-meta : 1
		ae-post-title : 16
		ae-taxonomy : 2
		divider : 1
		heading : 25
		html : 1
		icon : 2
		image : 4
		image-box : 1
		posts : 1
		shortcode : 1
		spacer : 4
		text-editor : 4
		uael-timeline : 1
		wts-modal-popup : 1
		wts-textseparator : 1
	wp-page : 40
		ae-acf-flexible-content : 1
		ae-acf-repeater : 1
		ae-dynamic-map : 3
		ae-portfolio : 1
		ae-post-blocks : 2
		ae-post-blocks-adv : 4
		ae-taxonomy-blocks : 2
		heading : 2
		portfolio : 1
		shortcode : 3
		text-editor : 1
	single-post : 1
		shortcode : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		heading : 2
		sidebar : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
PHP: showing 4 of 4PHP: 2022-09-14 13:17:49 [warning X 1][/Users/anand/Local/aepro-dev/app/public/wp-content/plugins/elementor/includes/elements/column.php::1010] Undefined array key "_column_size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 13:41:52 [warning X 3][/Users/anand/Local/aepro-dev/app/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 10:18:25 [warning X 1][/Users/anand/Local/aepro-dev/app/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::59] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 11:33:45 [warning X 3][/Users/anand/Local/aepro-dev/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 362022-10-14 07:06:53 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-14 07:06:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.8.0-beta4',
)]
2022-10-17 07:13:56 [info] elementor-pro::elementor_pro_updater Started 
2022-10-17 07:13:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-17 07:13:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-17 07:13:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.8.0-beta4',
)]
2022-10-17 07:13:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.8.0-beta4',
)]
2022-10-31 05:01:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'AnyWhere Elementor Pro',
  'from' => '2.25.3',
  'to' => '2.25.4',
)]
2022-11-01 13:31:05 [info] elementor::elementor_updater Started 
2022-11-01 13:31:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 13:31:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta4',
  'to' => '3.8.0',
)]
2022-11-01 13:31:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 13:31:06 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 13:31:06 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 13:31:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-beta4',
  'to' => '3.8.0',
)]
2022-11-01 13:39:16 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 13:39:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 13:39:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 13:39:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-beta4',
  'to' => '3.8.0',
)]
2022-11-01 13:39:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-beta4',
  'to' => '3.8.0',
)]

JS: showing 2 of 2JS: 2022-11-02 12:29:39 [error X 2][http://aepro-dev.local/wp-content/plugins/elementor/assets/js/new-template.js?ver=3.8.0:173:91] elementor_new_template_form_controls is not defined 
JS: 2022-11-02 12:30:42 [error X 1][http://aepro-dev.local/wp-content/plugins/elementor/assets/js/editor.js?ver=3.8.0:44118:71] Cannot read properties of undefined (reading \'toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by anandau** [comment]
This was working perfectly fine before 3.8

**Comment by thomas38540** [comment]
Similar problem. ACF Field into shortcode ([elementor-template id="xxx"]) not display the data.
Restore to 3.7.7 Elementor Pro only, and it's work perfectly.

**Comment by SDS-Design** [comment]
Hey, I have the same issue. Searching for help since today. Did 2 Updates and bam, all fucked up. I tried a Elementor Pro Version fallback to v. 3.7.7 and it worked for me.

I tested the issue a bid, a direct linking to the dynamic data is working. Like, when you display the dynamic tag data within the same "template-structure", it works. Like Site - to - Site.
But if the ACF field is declared within a different template-document (like a Header), it breaks. It's not showing anything.

How-to-Rollback
![Bildschirm­foto 2022-11-02 um 15 12 16](https://user-images.githubusercontent.com/62096962/199512430-760cb662-de90-4441-b4b1-562c867acec1.png)

choose "Elementor" > "tools" > "version control" - Select 3.7.7 by the Pro-Version dropdown-list. Save changes. done. picture shows all for our German friends.

**Comment by nicholaszein** [comment]
Hello all! 

Thank you for reporting your issues! 🙏 

We are aware of some compatibility conflicts between the latest version of Elementor and ACF, and are working on a fix. We will get back to you as soon as we have fixed the issue. Thank you for your patience and for the feedback!

Kind regards

**Comment by mocana** [comment]
I am also having the same issue. I'm excited to try the new loop tools but it just knee-capped all of my websites that have custom loops via 3rd party tools like Ele Skin and Dynamic OOO.

**Comment by nicholaszein** [comment]
Hey everybody!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by critdhenz** [comment]
Still the same bug in Elementor Pro. Any updates here?

**Comment by vaccinemedia** [comment]
I'm not even using template shortcodes anywhere and 'm seeing a LOT of this php warning in my logs:
AH01071: Got error 'PHP message: PHP Warning: Undefined array key 0 in [/var/www/vhosts/prolificnorth.co.uk/httpdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php](https://5c7bd29.online-server.cloud:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Felementor-pro%2Fmodules%2Fdynamic-tags%2Facf%2Ftags&subscriptionId=1&file=acf-text.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) on line 33

**Comment by vaccinemedia** [comment]
AH01071: Got error 'PHP message: PHP Warning: Undefined array key 0 in [/var/www/vhosts/prolificnorth.co.uk/httpdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php](https://5c7bd29.online-server.cloud:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fwp-content%2Fplugins%2Felementor-pro%2Fmodules%2Fdynamic-tags%2Facf%2Ftags&subscriptionId=1&file=acf-text.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) on line 33

**Comment by vaccinemedia** [comment]
I downgraded my PHP from 8.x to 7.4 and this has stopped the php warning so it must be a php 8.x compatibility issue.
