### ISSUE TITLE
❌ 🧩 Invalid Issue: Additional Custom Breakpoints + Jet menu

### ISSUE THREAD

**Issue by Anders-Graitor** [elementor/elementor#20246]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When having elementor -> Additional Custom Breakpoints enable
and then using Jetmenu from crocoblock to create a mega menu

The mega menu is not responsive what so ever.

### Steps to reproduce

enable Additional Custom Breakpoints

make a mega menu in jetmenu

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.32
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://humanrisks.webven.dk
	Home URL: https://humanrisks.webven.dk
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Copenhagen
	Admin Email: info@webven.dk
	Debug Mode: Inactive

== Theme ==
	Name: Human Risks
	Version: 1.0
	Author: Webven
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Happy Elementor Addons
		Version: 3.7.1
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 2.6.1
		Author: weDevs

	HappyFiles Pro
		Version: 1.7
		Author: Codeer

	JetEngine
		Version: 3.0.6
		Author: Crocoblock

	JetMenu
		Version: 2.2.4
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.19
		Author: Crocoblock

	JetThemeCore
		Version: 2.0.7
		Author: Crocoblock

	Limit Login Attempts Reloaded
		Version: 2.25.8
		Author: Limit Login Attempts Reloaded

	OoohBoi Steroids for Elementor
		Version: 2.0.4
		Author: OoohBoi

	Really Simple SSL
		Version: 5.3.5
		Author: Really Simple Plugins

	SEOPress
		Version: 6.0.2
		Author: The SEO Guys at SEOPress

	Temporary Login Without Password
		Version: 1.8.0
		Author: StoreApps

	UiPress
		Version: 2.4.2
		Author: Admin 2020

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP Activity Log
		Version: 4.4.2.1
		Author: WP White Security

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.3
		Author: WPCode

	WPvivid Backup Plugin
		Version: 0.9.79
		Author: WPvivid Team

	WPvivid Plugins Pro
		Version: 2.2.11
		Author: wpvivid.com

	WPvivid Staging
		Version: 2.0.13
		Author: wpvivid.com

== Must-Use Plugins ==
	WordPress automation by 1-click-installer
		Version: 
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 3 of 3PHP: 2022-08-30 13:11:27 [warning X 1][/home/webvendk/Humanrisks.webven.dk/wp-content/plugins/elementor/core/breakpoints/manager.php::420] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-31 09:17:14 [error X 2][/home/webvendk/Humanrisks.webven.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /home/webvendk/Humanrisks.webven.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/webvendk/Humanrisks.webven.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(12, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/webvendk/Humanrisks.webven.dk/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/webvendk/Humanrisks.webven.dk/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/webvendk/Humanrisks.webven.dk/wp-includes/class-wp-hook.php(331): WP_Hook->ap [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-03 12:55:00 [notice X 4][/home/webvendk/Humanrisks.webven.dk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 13 of 13JS: 2022-08-30 15:03:31 [error X 2][https://humanrisks.webven.dk/wp-admin/post.php?post=792&action=elementor:6:22] Cannot read properties of null (reading \'url\') 
JS: 2022-08-31 06:23:46 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.2:3:571218] Cannot read properties of null (reading \'id\') 
JS: 2022-08-31 06:36:54 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view70661\") has already been destroyed and cannot be used. 
JS: 2022-08-31 15:46:06 [error X 8][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.3:3:767290] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-09-12 13:35:44 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4272\") has already been destroyed and cannot be used. 
JS: 2022-10-04 16:01:54 [error X 2][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1590\") has already been destroyed and cannot be used. 
JS: 2022-10-06 10:23:15 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view2722\") has already been destroyed and cannot be used. 
JS: 2022-10-06 10:24:56 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view6215\") has already been destroyed and cannot be used. 
JS: 2022-10-06 10:25:03 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view8529\") has already been destroyed and cannot be used. 
JS: 2022-10-06 10:25:04 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9661\") has already been destroyed and cannot be used. 
JS: 2022-10-06 10:25:06 [error X 1][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view10793\") has already been destroyed and cannot be used. 
JS: 2022-10-11 11:36:34 [error X 5][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060992] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-10-19 09:21:52 [error X 8][https://humanrisks.webven.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:693899] this.manager.setPage(...).showView is not a function 

Log: showing 20 of 272022-08-31 08:50:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-31 08:50:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-31 08:50:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-09-05 09:12:39 [info] elementor::elementor_updater Started 
2022-09-05 09:12:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-05 09:12:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-05 09:12:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-05 09:12:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-10-03 11:38:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.8',
)]
2022-10-03 11:38:22 [info] elementor::elementor_updater Started 
2022-10-03 11:38:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 11:38:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 11:38:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.8',
)]
2022-11-02 16:14:59 [info] elementor::elementor_updater Started 
2022-11-02 16:14:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-02 16:14:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-02 16:14:59 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-02 16:14:59 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-02 16:14:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-02 16:14:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Happy Elementor Addons: Compatibility not specified
	Happy Elementor Addons Pro: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	OoohBoi Steroids for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by Anders-Graitor** [comment]
> @Anders-Graitor I have JetMenu as well, unfortunately it's a Crocoblock issue, not an Elementor issue. The JetMenu plugin (like most Crocoblock plugins) haven't been on the same sustained update pace (I think mostly because the team is located in Ukraine).
ah damn alright. Just their support that said its elementor -_-
def makes sense. its a shame

**Comment by nicholaszein** [comment]
Hello @Anders-Graitor,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.
It's Crocoblock's responsibility to add compatibility for Elementor features on their add-ons. Unfortunately, there is nothing we can do about it. They have access to the documentation and can adapt their plugins to make them compatible with the Custom Breakpoints experiment.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards
