### ISSUE TITLE
❌ 🐞  Image widget crach on split screen

### ISSUE THREAD

**Issue by alicedoe** [elementor/elementor#20242]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When you use image widget like carousel, gallery etc ... they have a wrong length or width in split screen mode (on 15" with chrome) and you obtain a color block like on following capture :
![split](https://user-images.githubusercontent.com/24544003/199504827-dc614383-ebb6-4b36-afde-edd2638f6961.PNG)

### Steps to reproduce

Create a page with an image widget : carousel, gallery, sliders
Whatever them you used : sydney, twentytwenty, hello etc ...
Using Google chrome
Do a split screen on a small screen (15")
All image widgets are crashed
The vertical & horizontal scroll bar who are a lot more larger than the website, for example website is 1903px large in split mode it becomes 236843500 px

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.2
	MySQL version: Debian 10 v10.3.36
	PHP Version: 7.4.32
	PHP Memory Limit: 192M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://www.gggggggggggggg.com
	Home URL: https://www.gggggggggggggg.com
	WP Multisite: No
	Max Upload Size: 100 Mo
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: gggggggggggggggg
	Debug Mode: Inactive

== Theme ==
	Name: Sydney Child
	Version: 1.0
	Author: aThemes
	Child Theme: Yes
	Parent Theme Name: Sydney
	Parent Theme Version: 2.12
	Parent Theme Author: aThemes

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	BBQ Firewall
		Version: 20221002
		Author: Jeff Starr

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Column Shortcodes
		Version: 1.0.1
		Author: Codepress

	Conditional Fields for Contact Form 7
		Version: 2.2.9
		Author: Jules Colle

	Contact Form 7
		Version: 5.6.4
		Author: Takayuki Miyoshi

	CookieYes | GDPR Cookie Consent
		Version: 3.0.4
		Author: CookieYes

	Easy Table of Contents
		Version: 2.0.35.2
		Author: Magazine3

	Easy WP SMTP
		Version: 1.5.1
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.5
		Author: Elementor.com

	ELEX WooCommerce Catalog Mode
		Version: 1.2.8
		Author: ELEXtensions

	Flamingo
		Version: 2.3
		Author: Takayuki Miyoshi

	GTranslate
		Version: 2.9.14
		Author: Translate AI Multilingual Solutions

	HappyFiles
		Version: 1.5.1
		Author: Codeer

	HappyFiles Pro
		Version: 1.7
		Author: Codeer

	Imagify
		Version: 2.0
		Author: Imagify - Optimize Images & Convert WebP

	Internal Link Juicer
		Version: 2.0.2
		Author: Internal Link Juicer

	LightStart - Maintenance Mode, Coming Soon and Landing Page Builder
		Version: 2.6.0
		Author: Themeisle

	MailPoet
		Version: 3.102.0
		Author: MailPoet

	MetaSlider
		Version: 3.27.13
		Author: MetaSlider

	NextGEN Gallery
		Version: 3.30
		Author: Imagely

	NextScripts: Social Networks Auto-Poster
		Version: 4.4.2
		Author: NextScripts

	Plugin Security Scanner
		Version: 2.0.2
		Author: Glen Scott

	Rank Math SEO
		Version: 1.0.100.1
		Author: Rank Math

	Really Simple CAPTCHA
		Version: 2.1
		Author: Takayuki Miyoshi

	Simple Custom CSS and JS
		Version: 3.41
		Author: SilkyPress.com

	Simple Sitemap
		Version: 3.5.7
		Author: David Gwyer

	Site Kit by Google
		Version: 1.86.0
		Author: Google

	SiteOrigin Widgets Bundle
		Version: 1.43.0
		Author: SiteOrigin

	Visual Portfolio, Posts & Image Gallery
		Version: 2.20.3
		Author: Visual Portfolio Team

	Web Stories
		Version: 1.26.0
		Author: Google

	WooCommerce
		Version: 7.0.1
		Author: Automattic

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP Rocket
		Version: 3.12.2.1
		Author: WP Media

	WPS Bidouille
		Version: 1.28
		Author: WPServeur, NicolasKulka, Benoti, wpformation

	WPS Cleaner
		Version: 1.6.8
		Author: WPServeur, NicolasKulka, wpformation

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation

	WPS Limit Login
		Version: 1.5.6
		Author: WPServeur, NicolasKulka, wpformation

	YITH WooCommerce Ajax Product Filter
		Version: 4.15.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Mu-Plugin WP Serveur
		Version: 1.5
		Author: WPServeur

== Utilisation des éléments ==
	
	footer : 2
		divider : 12
		form : 4
		heading : 13
		icon-box : 12
		nav-menu : 6
		shortcode : 1
		social-icons : 4
		text-editor : 7
	header : 2
		image : 2
		nav-menu : 4
		shortcode : 2
	page : 5
		divider : 31
		flip-box : 4
		heading : 33
		icon-box : 33
		image : 23
		media-carousel : 4
		spacer : 21
		text-editor : 28
		visual-portfolio : 1
		woocommerce-breadcrumb : 4
		woocommerce-product-related : 4
		woocommerce-product-short-description : 4
		woocommerce-product-title : 4
	section : 6
		call-to-action : 10
		divider : 2
		heading : 8
		image : 7
		shortcode : 1
		text-editor : 7
		woocommerce-breadcrumb : 1
		woocommerce-products : 1
	wp-post : 25
		heading : 20
		image : 14
		text-editor : 48
	wp-page : 22
		alert : 1
		button : 2
		call-to-action : 56
		counter : 5
		divider : 39
		gallery : 2
		heading : 55
		html : 17
		icon-box : 5
		image : 69
		portfolio : 10
		posts : 2
		shortcode : 1
		slides : 4
		spacer : 12
		text-editor : 53
		video : 2
	single-post : 1
		divider : 1
		post-info : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	product-post : 0
		divider : 321
		flip-box : 36
		gallery : 1
		heading : 337
		icon-box : 319
		image : 220
		media-carousel : 36
		spacer : 143
		text-editor : 273
		video : 2
		woocommerce-breadcrumb : 34
		woocommerce-product-related : 3
		woocommerce-product-short-description : 36
		woocommerce-product-title : 36
		woocommerce-products : 35

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Inactif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Envois de formulaire: Actif par défaut
	Accroche de défilement: Actif par défaut

== Journal ==
	
Log: showing 17 of 172022-06-22 20:46:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-22 20:46:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-22 20:46:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-08-02 11:48:09 [info] elementor::elementor_updater Started 
2022-08-02 11:48:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-02 11:48:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-02 11:48:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-08-02 11:50:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-02 11:50:57 [info] elementor::elementor_updater Started 
2022-08-02 11:50:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-02 11:51:00 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-02 11:51:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-02 11:51:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-09-06 08:50:50 [info] elementor-pro::elementor_pro_updater Started 
2022-09-06 08:50:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-06 08:50:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-06 08:50:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.3',
  'to' => '3.7.5',
)]

PHP: showing 19 of 19PHP: 2022-06-24 14:09:28 [warning X 12][ggggggggg/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-24 16:23:13 [warning X 12][ggggggggg/wp-content/plugins/elementor/includes/managers/image.php::81] Undefined array key 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-29 16:02:10 [warning X 3][ggggggggg/wp-content/plugins/elementor-pro/modules/query-control/module.php::748] Attempt to read property "name" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-10 14:42:27 [warning X 1][ggggggggg/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://gggggggggggggggggg/wp-content/uploads/2021/06/iconfinder_7521099_ecology_bicycle_environment_bike_icon.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-23 19:40:03 [warning X 10][ggggggggg/wp-content/plugins/elementor/core/base/document.php::250] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-25 16:30:41 [notice X 24][ggggggggg/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-26 11:42:30 [notice X 9][ggggggggg/wp-content/plugins/elementor/includes/managers/image.php::97] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-26 11:47:21 [notice X 19][ggggggggg/wp-content/plugins/elementor/core/base/document.php::250] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 14:02:40 [notice X 47][ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 14:20:44 [notice X 5][ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: ggggggggg/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-06 14:20:44 [notice X 5][ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: ggggggggg/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-06 14:20:44 [notice X 5][ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: ggggggggg/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-09-06 14:20:44 [notice X 5][ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: ggggggggg/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: ggggggggg/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-19 15:56:12 [warning X 1][ggggggggg/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://www.gggggggggggggg.com/wp-content/uploads/2021/06/iconfinder_7521099_ecology_bicycle_environment_bike_icon-1.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-31 09:11:05 [notice X 1832][ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 14:22:55 [notice X 3][ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1446] Trying to access array offset on value of type null [array (
  'trace' => '
#0: ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1446): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: ggggggggg/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-11-02 14:22:55 [notice X 3][ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1459] Trying to access array offset on value of type null [array (
  'trace' => '
#0: ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1459): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: ggggggggg/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-11-02 14:22:55 [notice X 3][ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1470] Trying to access array offset on value of type null [array (
  'trace' => '
#0: ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1470): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: ggggggggg/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-11-02 14:22:55 [notice X 3][ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: ggggggggg/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1483): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ggggggggg/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: ggggggggg/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: ggggggggg/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]

JS: showing 6 of 6JS: 2022-06-30 09:37:13 [error X 1][https://gggggggggggggggggg/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:235702] T.params.args.data is undefined 
JS: 2022-06-30 15:23:09 [error X 1][https://gggggggggggggggggg/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.6.6:2:67705] C is undefined 
JS: 2022-08-25 07:34:23 [error X 2][https://gggggggggggggggggg/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.7.2:2:25983] elementorDevTools is not defined 
JS: 2022-09-20 12:46:14 [error X 2][https://www.gggggggggggggg.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:897946] V is null 
JS: 2022-10-19 12:03:39 [error X 1][https://www.gggggggggggggg.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:287003] Cannot read properties of undefined (reading \'id\') 
JS: 2022-10-24 11:03:24 [error X 1][https://www.gggggggggggggg.com/wp-content/plugins/seo-by-rank-math/includes/3rdparty/elementor/assets/js/elementor.js?ver=1.0.98:1:39850] elementor is not defined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @alicedoe,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tested every image-related widget and found that they scale correctly to every screen resolution and responsive window we tested.
- The problem is likely caused by your website or browser cache.

### ✅ What you can do to solve your issue:
* Clear every type of cache (server, website, CDN, browser) that you might have enabled, and test the page in private/incognito mode.
* Make sure your performance solution isn't causing conflicts with Elementor.
* Make sure your plugins aren't causing any conflicts with Elementor.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
