### ISSUE TITLE
[🧐 Evaluating] 🚀 Feature Request: Allow sections and containers to be added independently

### ISSUE THREAD

**Issue by steveindzine** [elementor/elementor#20243]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Sections are really good for editors who don't understand containers, it would be great to enable the containers experiement so that the developers can make use of the excellent feature, but also allow editors the ability to still create layouts with sections.

### Describe the solution you'd like

Show the section widget and the container widget when the container experiment is turned on.

**Comment by black-eye** [comment]
+1 Yes please, make it an optional setting, but give us a possibility to do it when needed.

**Comment by perks98** [comment]
+1 I agree. I was on the fence today about building a site with sections or containers due to client ease of usability. If they make containers usability simpler then great but currently I see it as sections as basic and containers as advanced so maybe those types of settings are needed maybe.

**Comment by steveindzine** [comment]
@perks98 as long as I can use both at the same time without being forced to convert a section into a container I will be happy.

**Comment by nicholaszein** [comment]
Hey guys!

Thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon. Allow us to take some time to review your request. We will get back to you with feedback as soon as possible.

Best regards

**Comment by steveindzine** [comment]
This has been added to new feature request discussions: https://github.com/orgs/elementor/discussions/21209#discussioncomment-4833810

**Comment by nicholaszein** [comment]
Hello @steveindzine,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap.  

Sections will soon be replaced by Containers. Older sites with Sections and Columns will remain to function normally, and you can convert them to containers in your own time or leave them as they are, whatever suits your needs. You will be able to edit and duplicate Sections and Columns as many times as you want, but moving forward (in the near future) the Container is going to be used as part of the Core Elementor plugin and set as the default building element for new websites.

Feel free to contact us again with other feature suggestions. 😉 

Best regards
