### ISSUE TITLE
✔️ 🚀 Feature Request: Using ACF fields in the Posts widget

### ISSUE THREAD

**Issue by chriscookz** [elementor/elementor#20245]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I make a podcast and keep track of episode numbers in a custom field. I would like to be able to show that episode number, stored in the custom field, on my posts archive template. Each episode is a post, I should be able to show episode 3, for example, and have it pull the 3 from the custom field of that post. 

### Describe the solution you'd like

As part of the Content > Layout tab for the Posts widget, it would be nice to be able to select custom fields to include in that post grid. And once you can select custom fields to include (or not) in your post grid, having the ability to re-order those fields would be necessary as well (re-ordering any of the Posts widget elements would be awesome, but that's probably another request). 

### Describe alternatives you've considered

I've tried pulling my ACF episode number field into the Read More Text box, there is a "Dynamic Tags" that ACF Field is available as an option in, but my ACF field never actually displays when I select my episode number field.

**Comment by nicholaszein** [comment]
Hello there @chriscookz!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.0**! 🥳 

You can now use the [Loop Builder](https://elementor.com/help/loop-grid/) to build your own templates for anything you'd like, including adding Dynamic Tags with ACF fields.

You can learn more about it on our official [Blog Post](https://elementor.com/blog/introducing-the-loop-builder/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
