### ISSUE TITLE
⛔ 🚀 Feature Request: Portfolio - Add more grid types, such as Masonry, Material & Packery

### ISSUE THREAD

**Issue by mateitudor** [elementor/elementor#20249]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The portfolio component is due for a much needed upgrade, to make it more "Elementor" (meaning more powerful).

### Describe the solution you'd like

One thing that would make the portfolio component more powerful is to have more grid options besides the square items. It could employ the new loop functionality, for instance.

Also it would be awesome to have more creative grid options such as masonry, material, Packery-style (js library).

### Describe alternatives you've considered

Third party plugins.

### Additional context

Thanks in advance.

**Comment by nicholaszein** [comment]
Hello @mateitudor,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
