### ISSUE TITLE
✔️ 🐞 Bug Report: The Plus Addons for Elementor - Custom Loop Skin Issue with New Elementor Update 3.8.0 (ED-8562)

### ISSUE THREAD

**Issue by posimyth** [elementor/elementor#20258]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We are having Custom Loop Skin feature few years back in The Plus Addons for Elementor. https://theplusaddons.com/pluslisting/custom-loop-skin-builder/ 

In which we are using elementor template as a custom loop skin. Which was working perfectly fine till last update. 

In last update, You made elementor template will work only if It's Category is "Loop" in Theme Builder. This way, Thousands site which were using our addons having issue with this new update and having custom loop skin already selected. 

We have tested further in Elementor Ecosystem, We can see same issue in Unlimited Addons, Powerpack, Anywhere and many more. Only it's working in https://wordpress.org/plugins/ele-custom-skin/ but we have checked code and they have some deep connection elementor code and elementor also did compatibility with them to make it working. 

We need help on above as, without that, User will not be able to update to latest version. 

### Steps to reproduce

Sample Page Working in Elementor 3.7: https://elementorsupport.instawp.xyz/index.php/test/
Video : https://posimyth.vmaker.com/record/cyl76JOOwZrCb7nB
Widget File : plugins\theplus_elementor_addon\modules\widgets\tp_dynamic_listing.php
Custom Loop File : plugins\theplus_elementor_addon\includes\dynamic-listing\dl-custom.php

We have test setup ready with wp-admin access but it's having Elementor Pro + The Plus Addons Pro so can not share in public. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/uZgYFKDE

**Comment by nicholaszein** [comment]
Hello there @posimyth!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
