### ISSUE TITLE
❌ Invalid Issue: Error 500

### ISSUE THREAD

**Issue by evelyntts** [elementor/elementor#20257]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Error 500 Internal Server Error.
![image](https://user-images.githubusercontent.com/115194680/199641290-01eda1cd-be93-420c-af2d-9cc0f61cf27f.png)

### Steps to reproduce

It only happens when i click on the "edit with elementor" and "Preview" buttons for "themes" and "Pages - Homepage". This happens after I Publish the pages. i do not have this problem with "Posts".
1) Create Pages
2) Publish
3) Preview
4) Error 500 message

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.28
	PHP Version: 7.4.32
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://pivot.sg
	Home URL: https://pivot.sg
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: m.m.mariamitsi@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Blank Canvas
	Version: 1.2.9
	Author: Automattic
	Child Theme: Yes
	Parent Theme Name: Seedlet
	Parent Theme Version: 1.1.13
	Parent Theme Author: Automattic

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Custom Adobe Fonts (Typekit)
		Version: 1.0.18
		Author: Brainstorm Force

	Elementor
		Version: 3.9.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.9.0-dev5
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.4.2
		Author: WPDeveloper

	Fonts Plugin | Google Fonts Typography
		Version: 3.2.1
		Author: Fonts Plugin

	Google Analytics for WordPress by MonsterInsights
		Version: 8.9.1
		Author: MonsterInsights

	Image Hover Effects - Elementor Addon
		Version: 1.3.7
		Author: Blocksera

	Spectra
		Version: 2.0.13
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	WP Fastest Cache
		Version: 1.0.7
		Author: Emre Vona

	WP Visitor Statistics (Real Time Traffic)
		Version: 5.9
		Author: osamaesh

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

== Elements Usage ==
	
	archive : 2
		button : 4
		navigation-menu : 3
		posts : 1
		text-editor : 1
	section : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	wp-post : 8
		button : 1
		divider : 1
		eael-simple-menu : 1
		gallery : 1
		heading : 1
		image : 98
		navigation-menu : 1
		site-logo : 4
		social-icons : 1
		spacer : 15
		text-editor : 72
	wp-page : 24
		button : 39
		divider : 6
		eael-filterable-gallery : 2
		eael-post-grid : 1
		gallery : 5
		heading : 44
		html : 4
		image : 5
		image-gallery : 1
		media-carousel : 20
		nav-menu : 1
		navigation-menu : 4
		social-icons : 1
		spacer : 38
		text-editor : 29
	single-post : 2
		divider : 1
		heading : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 13 of 13JS: 2022-02-12 13:05:40 [error X 1][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view11334\") has already been destroyed and cannot be used. 
JS: 2022-02-12 15:28:42 [error X 1][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:347253] Cannot read properties of undefined (reading \'holdReady\') 
JS: 2022-03-10 07:43:30 [error X 1][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:573344] undefined is not an object (evaluating \'C.widgetType\') 
JS: 2022-03-10 07:43:56 [error X 1][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:415368] null is not an object (evaluating \'elementor.documents.getCurrent().id\') 
JS: 2022-03-10 07:44:02 [error X 1][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:584794] undefined is not an object (evaluating \'C.elType\') 
JS: 2022-03-16 04:25:52 [error X 7][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.0-dev37:2:5057] Cannot read properties of undefined (reading \'data\') 
JS: 2022-03-16 06:05:41 [error X 4][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:393126] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-03-16 07:39:19 [error X 1][https://pivot-interior.com/directory/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.9.2:2:31703] elementorAdmin is not defined 
JS: 2022-03-17 04:54:41 [error X 5][http://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:681220] Cannot read properties of undefined (reading \'settings\') 
JS: 2022-03-17 05:07:27 [error X 1][http://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:684356] Cannot read properties of undefined (reading \'view\') 
JS: 2022-03-18 09:46:58 [error X 2][https://pivot-interior.com/directory/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:573345] Cannot read properties of undefined (reading \'widgetType\') 
JS: 2022-09-24 23:31:44 [error X 35][https://pivot.sg/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.4:2:515479] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-03 02:28:14 [error X 16][https://pivot.sg/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] Cannot read properties of undefined (reading \'tools\') 

PHP: showing 9 of 9PHP: 2022-02-12 15:28:45 [notice X 60606][/home2/pivotior/public_html/directory/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-12 15:55:08 [notice X 52][/home2/pivotior/public_html/directory/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-17 16:18:34 [warning X 1][/home2/pivotior/public_html/directory/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::180] unlink(arrow.svg): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-10 07:43:32 [notice X 6][/home2/pivotior/public_html/directory/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-16 09:51:23 [notice X 3][/home2/pivotior/public_html/directory/wp-content/plugins/elementor/includes/elements/column.php::1010] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-05 07:33:59 [notice X 1][/var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-26 21:34:00 [error X 21][/var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /var/www/vhosts/pivot.sg/httpdocs/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{c [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-14 14:11:11 [notice X 468][/var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Elements.php(23): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-14 14:27:01 [error X 2][/var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/vhosts/pivot.sg/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/vhosts/pivot.sg/httpdocs/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/vhosts/pivot.sg/httpdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/vhosts/pivot.sg/httpdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/vhosts/pivot.sg/httpdocs/wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 202022-04-13 21:21:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev37',
  'to' => '3.6.4',
)]
2022-04-13 21:21:47 [info] elementor::elementor_updater Started 
2022-04-13 21:21:48 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-13 21:21:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-13 21:21:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev37',
  'to' => '3.6.4',
)]
2022-11-03 02:25:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.9.0-dev4',
)]
2022-11-03 02:25:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev19',
  'to' => '3.9.0-dev5',
)]
2022-11-03 02:25:23 [info] elementor-pro::elementor_pro_updater Started 
2022-11-03 02:25:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-03 02:25:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-03 02:25:23 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-11-03 02:25:24 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-11-03 02:25:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev19',
  'to' => '3.9.0-dev5',
)]
2022-11-03 02:25:24 [info] elementor::elementor_updater Started 
2022-11-03 02:25:24 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-03 02:25:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev19',
  'to' => '3.9.0-dev5',
)]
2022-11-03 02:25:24 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-03 02:25:24 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-03 02:25:24 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-03 02:25:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.9.0-dev4',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible
	Elementor Pro: Incompatible
	Essential Addons for Elementor: Incompatible
	Image Hover Effects - Elementor Addon: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible
	Essential Addons for Elementor: Incompatible

**Comment by nicholaszein** [comment]
Hello @evelyntts,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

You can try following the instructions in [this article](https://elementor.com/help/500-error/).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
