### ISSUE TITLE
❌ Invalid Issue: Adding User

### ISSUE THREAD

**Issue by jocelynmacleod** [elementor/elementor#20254]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I try and add a user to my page and it states the user is added but they are not on my All User list. In addition, any edits that I make to a user (e.g., changing role) will not take effect. Also, even minor changes such as wanting to view 100 users rather than 20 does not take effect.

### Steps to reproduce

1) Click add new user button
2) Input all data
3) Click Add New User at bottom of form

Bar comes up at top that states new user was added, but user is not in user list.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 1G
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://thundercreekrehabilitationassociation.ca
	Home URL: https://thundercreekrehabilitationassociation.ca
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Regina
	Admin Email: codynidesh@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.9.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.9.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	H5P
		Version: 1.15.4
		Author: Joubel

	LearnDash Licensing &amp; Management
		Version: 1.1.3
		Author: LearnDash

	LearnDash LMS
		Version: 4.3.1.3
		Author: LearnDash

	LearnDash LMS - Course Grid
		Version: 2.0.6
		Author: LearnDash

	LearnDash LMS - Notifications
		Version: 1.5.4
		Author: LearnDash

	LiteSpeed Cache
		Version: 5.3
		Author: LiteSpeed Technologies

	Loginizer
		Version: 1.7.5
		Author: Softaculous

	Modal Popup Box
		Version: 1.4.4
		Author: A WP Life

	My Custom Functions
		Version: 4.51
		Author: Space X-Chimp

	Under Construction
		Version: 3.93
		Author: WebFactory Ltd

	WPForms Lite
		Version: 1.7.7.2
		Author: WPForms

== Must-Use Plugins ==
	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	WHC.CA
		Version: 1.0.0
		Author: WHC.CA

	WHC.CA
		Version: 1.0.0
		Author: WHC.CA

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Lazy Load Background Images: Active by default

== Log ==
	
Log: showing 20 of 402022-08-29 12:05:28 [info] elementor::elementor_updater Started 
2022-08-29 12:05:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-29 12:05:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-29 12:05:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-31 13:25:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-08-31 13:25:08 [info] elementor::elementor_updater Started 
2022-08-31 13:25:08 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-31 13:25:08 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-31 13:25:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-14 14:21:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-14 14:21:12 [info] elementor::elementor_updater Started 
2022-09-14 14:21:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-14 14:21:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-14 14:21:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-14 14:21:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-10-30 18:41:39 [info] elementor::elementor_updater Started 
2022-10-30 18:41:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-30 18:41:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-30 18:41:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.8.0',
)]
2022-10-30 18:41:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.8.0',
)]

PHP: showing 2 of 2PHP: 2022-08-10 13:44:31 [error X 1][/home/mlckwo22/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1053] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/mlckwo22/public_html/wp-includes/class-wp-hook.php on line 309 and defined in /home/mlckwo22/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1053
Stack trace:
#0 /home/mlckwo22/public_html/wp-includes/class-wp-hook.php(309): Elementor\TemplateLibrary\Source_Local-&gt;on_save_post(0, NULL)
#1 /home/mlckwo22/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /home/mlckwo22/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
#3 /home/mlckwo22/public_html/wp-includes/post.php(4673): do_action(&#039;save_post&#039;, 0, NULL, false)
#4 /home/mlckwo22/public_html/wp-admin/includes/post.php(700): wp_insert_post(Array, false, false)
#5 /home/mlckwo22/public_html/wp-admin/post-new.php(66): get_default_post_to_edit(&#039;certificate&#039;, true)
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 11:50:04 [error X 2][/home/mlckwo22/public_html/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class &#039;Elementor\Modules\AdminBar\Module&#039; not found in /home/mlckwo22/public_html/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /home/mlckwo22/public_html/wp-content/plugins/elementor/includes/plugin.php(724): Elementor\Core\Modules_Manager-&gt;__construct()
#1 /home/mlckwo22/public_html/wp-content/plugins/elementor/includes/plugin.php(641): Elementor\Plugin-&gt;init_components()
#2 /home/mlckwo22/public_html/wp-includes/class-wp-hook.php(308): Elementor\Plugin-&gt;init(&#039;&#039;)
#3 /home/mlckwo22/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(NULL, Array)
#4 /home/mlckwo22/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#5 /home/mlckwo22/public_html/wp-settings.php(617): do_action(&#039;init&#039;)
#6 /home/mlckwo22/public_html/wp-config.php(98): require_once(&#039;/home/mlckwo22/...&#039;)
#7 /home/mlckwo22/public_html/wp-load.php(50): require_once(&#039;/home/mlckwo22/...&#039;)
#8 /home/mlckwo22/public_html/wp-admin/admin-ajax.php(22): require_once(&#039;/home/mlckwo22/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Incompatible

**Comment by nicholaszein** [comment]
Hello @jocelynmacleod,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
