### ISSUE TITLE
⛔ 🚀 Feature Request: Loop Grid - Provide a way to allow the user to highlight a specific item in the loop

### ISSUE THREAD

**Issue by mateitudor** [elementor/elementor#20250]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Pro user feature: the ability to highlight 1 specific loop item in the grid.

### Describe the solution you'd like

It would be awesome if the items would have settings, such as:
- if it's a "highlighted" post or not,
- if the taxonomy is x then make the card have a different loop item template,
- the editor could create custom controls such as for the size of the card,
- time based cards (only show the card until x date), etc.

### Describe alternatives you've considered

Third party plugins.

**Comment by nicholaszein** [comment]
Hello @mateitudor,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Most of the features you're seeking could be targeted using simple custom CSS.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

⚠️ Please when suggesting new ideas, make sure to add one idea per request, so we can track them and manage them individually.

Feel free to contact us again with other feature suggestions. 😉 

Best regards
