### ISSUE TITLE
✔️ 🐞 Bug Report: Loop Grid - Post title doesn't show on non-archive pages

### ISSUE THREAD

**Issue by jlemonz** [elementor/elementor#20255]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Post title doesnt show on non archive pages in loops.

On archive pages the loop builder works correct. But using a loop on for example the homepage it doesnt show the post title. 

### Steps to reproduce

build a loop

Display it with a post title.
Use it on arvhive page/blog page.

THen also use it on the homepage. 

It misses the post title.

A temp workaround is to use acf to get the post title. This does work.
![1](https://user-images.githubusercontent.com/112578448/199569347-97996191-a87e-4a00-a1d7-6fff47e04eee.png)
![2](https://user-images.githubusercontent.com/112578448/199569360-c6304f30-1488-4c03-9111-b543df0af84b.png)
![3](https://user-images.githubusercontent.com/112578448/199569368-4c9cdf07-49ae-43c4-b592-d1dc5ee160fd.png)

The third image is on the archive page. It does show the post title.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.10
	MySQL version: mariadb.org binary distribution v10.5.10
	PHP Version: 8.1.11
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://smoothiesenzo.nl
	Home URL: https://smoothiesenzo.nl
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: nl
	Timezone: 1
	Admin Email: contact@lemonz.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	Autoptimize
		Version: 3.1.3
		Author: Frank Goossens (futtta)

	CookieYes | GDPR Cookie Consent
		Version: 3.0.4
		Author: CookieYes

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Email Log
		Version: 2.4.8
		Author: Sudar

	Form Vibes
		Version: 1.4.5
		Author: WPVibes

	MailerSend - Official SMTP Integration
		Version: 1.0.1
		Author: MailerSend

	Mouseflow for Wordpress
		Version: 5.1.2
		Author: Mouseflow

	ProfilePress
		Version: 4.3.1
		Author: ProfilePress Membership Team

	Rank Math SEO
		Version: 1.0.101
		Author: Rank Math

	Safe SVG
		Version: 2.0.3
		Author: 10up

	ShortPixel Image Optimizer
		Version: 5.1.1
		Author: ShortPixel

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.3
		Author: WPCode

== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 2.4.8
		Author: Kinsta Team

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Pictogrammen inline lettertype: Actief
	Toegang verbeteringen: Actief
	Extra aangepaste onderbrekingspunten: Actief
	Import export template kit: Standaard actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Actief
	Default to New Theme Builder: Standaard actief
	Hello Theme header & footer: Standaard inactief
	Landingspagina's: Standaard actief
	Kleur sampler: Standaard actief
	Favoriete widgets: Standaard actief
	Beheerder bovenste balk: Standaard actief
	Page Transitions: Standaard actief
	Notes: Standaard actief
	Loop: Actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief

== Log ==
	
Log: showing 20 of 302022-09-21 15:15:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.7',
)]
2022-09-21 15:15:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-09-21 15:15:39 [info] elementor::elementor_updater Started 
2022-09-21 15:15:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-21 15:15:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-21 15:15:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-10-08 11:13:16 [info] elementor::elementor_updater Started 
2022-10-08 11:13:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-08 11:13:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-08 11:13:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-08 11:13:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-08 11:13:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-11-02 14:17:02 [info] elementor::elementor_updater Started 
2022-11-02 14:17:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-02 14:17:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-02 14:17:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-02 14:17:04 [info] elementor-pro::elementor_pro_updater Started 
2022-11-02 14:17:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-02 14:17:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-02 14:17:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]

PHP: showing 10 of 10PHP: 2022-09-08 21:00:56 [notice X 126][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-08 22:28:55 [notice X 641][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/smoothies_684/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /www/smoothies_684/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-09-08 22:30:05 [notice X 15][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 15:24:24 [warning X 4819][/www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 12:09:38 [warning X 8][/www/smoothies_684/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 19:34:52 [notice X 1][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/smoothies_684/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/query-builder.php(189): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(115): ElementorPro\Core\Database\Query_Builder -> add_sub_select()
',
)]
PHP: 2022-11-02 14:21:50 [notice X 140][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/smoothies_684/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /www/smoothies_684/public/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-11-02 17:32:20 [warning X 1][/www/smoothies_684/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 17:43:35 [warning X 4][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /www/smoothies_684/public/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-11-02 17:45:22 [warning X 1][/www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/smoothies_684/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /www/smoothies_684/public/wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /www/smoothies_684/public/wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /www/smoothies_684/public/wp-includes/rest-api/class-wp-rest-server.php(1171): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]

JS: showing 2 of 2JS: 2022-11-02 16:05:00 [error X 2][https://smoothiesenzo.nl/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-02 16:28:50 [error X 1][https://smoothiesenzo.nl/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.0:2:2932] elementor_new_template_form_controls is not defined 

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatibel
	Elementor Pro: Niet compatibel

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatibel

**Comment by drau1** [comment]
same problem

**Comment by nicholaszein** [comment]
Hey @drau1,

I'm still trying to reproduce your issue but with no success. It works every time for me. Some things I thought here that might be causing your issue:

1. Cache:
Server-side caching, especially Object Cache might be causing the issue. It's just a suggestion, but worth checking out.
2. Wrong Query Parameters:
- On archive pages (such as the Posts page (Blog page set in Dashboard > Settings > Reading), the Query should be set to "Current Query".
- On normal pages (such as the homepage) the Query should be set to Posts or your desired CPT. Avoid using the _Current Query_, or _Related_ options.
![image](https://user-images.githubusercontent.com/113993460/199777174-c3bfab32-ead0-4fe8-a25e-d234eb35557c.png)

**Comment by drau1** [comment]
I already do everything of this check .. and the real bug consist in appear and disapper , backend and front end.
many user signal that on github
![2022-11-03-20-30-www luciasardo it](https://user-images.githubusercontent.com/94255240/199817150-ce827f9a-cb1c-4eb3-b4e9-110
![2022-11-03-20-32-www luciasardo it](https://user-images.githubusercontent.com/94255240/199817154-e400ce21-8c64-471d-a8af-eb0d2651188f.png)
c90083c32.png)

**Comment by drau1** [comment]
![2022-11-03-20-30-www luciasardo it](https://user-images.githubusercontent.com/94255240/199817251-45711714-c64f-4bf6-bff7-67f77d03c11b.png)
![2022-11-03-20-32-www luciasardo it](https://user-images.githubusercontent.com/94255240/199817277-a3cac09e-5bd1-48df-a6c1-09995f493c4c.png)

I do all try tha you suggest, the problme is that some page work and some other not

**Comment by jlemonz** [comment]
I can share a staging site if you want.

**Comment by nicholaszein** [comment]
Hello guys!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
