### ISSUE TITLE
🚀 ❓ Feature Question: Loading Sections and Containers

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20263]
### What is your question? Please describe.

My question is if the Flexbox Container experiment is enabled on a website already completely built with sections, inner sections and columns, when adding a new area in which it will use the containers will it load more bloat of CSS and JavaScript as it accommodates for both on the page?

Original: #20215 ~ From checking the discussions area a lot of questions don't get answered

**Comment by nicholaszein** [comment]
Hello @perks98,

thank you for the question. I'm getting there (to the Discussions tab), I just ask for a little more patience until we finish all the preparations for our new Developers Community home (Discussions). I'll make sure to answer it there.

Best regards
