### ISSUE TITLE
✔️ 🚀 Feature Request: Update Elementor Playground to 3.8

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20262]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Update https://playground.elementor.com/demo/flexbox/ to the latest 3.8 update. Also when beta releases come out update it to that too

**Comment by nicholaszein** [comment]
Hey @perks98,

the team is making the final checks to make sure everything is working as expected (all the quizzes) and they will be releasing the updated version of the Playground later on Sunday the 6th, or on Monday. Thanks for raising this question! 😉 👊

**Comment by nicholaszein** [comment]
Hi @perks98!

This was solved a long time ago. The Playground is now using the latest version.

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
