### ISSUE TITLE
✅ 🐞 Bug Report: Button widget adds unnecessary Icon Spacing when no Icon is selected inside the editor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20279]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In this widget, even if we do not select an icon, the Icon Spacing option is displayed. 

![download](https://user-images.githubusercontent.com/113993460/201540102-7064cc10-7d47-4335-b487-bedfd977632b.png)

#### [Added by moderator]

This causes the button widget to show unnecessary spacing for the icon inside the editor.

![image](https://user-images.githubusercontent.com/113993460/201540094-2b36650f-c019-4704-8475-a40a23629665.png)

The problem does not occur on the frontend.

### Steps to reproduce

Add a button widget. By default, the icon is not active. But there is an Icon Spacing option.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-26-10-2022.txt](https://github.com/elementor/elementor/files/9939416/system-info-localhost-26-10-2022.txt)

**Comment by nicholaszein** [comment]
Hello @Michaelgimii! 

Thank you for submitting your issue! 🙏 

I updated your original post to reflect my findings as well. 🤓

We will look into your issue and see if we can find a way to avoid this behavior. But since this does not affect the final result on the frontend, or any other functionality, we might leave this bug untouched for a while until we can handle other, more pressing, issues. Either way, thank you so much for bringing this to our attention! 🙏 

Best regards

**Comment by nicholaszein** [comment]
Hi @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.22.0, and improved further in Elementor v3.24.0 and v3.25.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
