### ISSUE TITLE
⛔ 🚀 Feature Request: Allow to modify the source of the Help videos of elements in the Widget Panel

### ISSUE THREAD

**Issue by sododesign** [elementor/elementor#2027]
Can you have a filter in the future that will allow us to edit the video that looks like tutorial in Elementor? I come from Italy and some customers complain that they do not understand the default video explaining how to use Elementor.

It would be great if we could, by filter, insert our video coming from YouTube or Vimeo for example.

Thank you very much,
Davide

**Comment by arielk** [comment]
We're working on the Preset feature (https://github.com/pojome/elementor/issues/965), so you can save default settings and data to each widget (or any other element).

I think this is the best way to solve the issue. Let me know yout think about this.

**Comment by sododesign** [comment]
Hi @arielk, I did not mean the modules, but the introductory aid, located at the bottom of the left column. I would like to be able to use a filter to open my video tutorial in Italian, not in English

**Comment by arielk** [comment]
Oh good question. This area is going to move to another place in the upcoming versions (v1.7) so we probably can not add a filter for it.

Thanks
