### ISSUE TITLE
✔️ 🐞 Bug Report: Elementor Pro 3.8.0 Background Image Issue using ACF Dynamic Tags

### ISSUE THREAD

**Issue by Havenwebmanagement** [elementor/elementor#20277]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Adding a background image using a Dynamic Tag with Advanced Custom Fields and Taxonomy Template is not working. Was working fine in previous version. Rollback fixes the issue.

### Steps to reproduce

Install Advanced Custom Fields plugin, Create Image Field for a Background Taxonomy, Go to theme builder create Taxonomy template, Create background image using the Dynamic Tag. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.32
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 5000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://www.travelzall.com
	Home URL: https://www.travelzall.com
	WP Multisite: No
	Max Upload Size: 3 GB
	Memory limit: 256
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: info@travelzall.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Haven Websites
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0

== Active Plugins ==
	ACF Post-2-Post
		Version: 1.7.0
		Author: John A. Huebner II

	Admin Columns Pro
		Version: 5.7.4
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 3.0.4
		Author: AdminColumns.com

	Admin Menu Editor Pro
		Version: 2.18
		Author: Janis Elsts

	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	Advanced Custom Fields: Extended
		Version: 0.8.8.10
		Author: ACF Extended

	Advanced Custom Fields: Repeater Field
		Version: 2.1.0
		Author: Elliot Condon

	Advanced Custom Fields: Theme Code Pro
		Version: 2.5.2
		Author: Hookturn with Ben Pearson

	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Advanced Post Queries
		Version: 1.0.16
		Author: Shabti Kaplan

	Ajax Search Pro
		Version: 4.23.3
		Author: Ernest Marcinko

	Better Notifications for WP
		Version: 1.9.1
		Author: Made with Fuel

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Dashboard Welcome for Elementor
		Version: 1.0.6
		Author: IdeaBox Creations

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.8.0
		Author: Dynamic.ooo

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	FacetWP
		Version: 4.1
		Author: FacetWP, LLC

	FacetWP - Cache
		Version: 1.6.1
		Author: FacetWP, LLC

	FacetWP - Conditional Logic
		Version: 1.4.1
		Author: FacetWP, LLC

	FacetWP - Elementor
		Version: 1.6.7
		Author: FacetWP, LLC

	FacetWP - Hierarchy Select
		Version: 0.5.2
		Author: FacetWP, LLC

	FacetWP - Map Facet
		Version: 1.0.1
		Author: FacetWP, LLC

	FacetWP - Range List
		Version: 0.7
		Author: FacetWP, LLC

	FacetWP - Submit button
		Version: 0.4
		Author: FacetWP, LLC

	Imsanity
		Version: 2.8.2
		Author: Exactly WWW

	My-Custom Read settings
		Version: 1.0
		Author: Daniel Clow

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Restrict Media Library Access
		Version: 1.0
		Author: mrfoxtalbot

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	Visibility Logic for Elementor
		Version: 2.3.2
		Author: StaxWP

	WPvivid Backup Plugin
		Version: 0.9.79
		Author: WPvivid Team

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 272022-11-01 10:09:32 [info] elementor::elementor_updater Started 
2022-11-01 10:09:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 10:09:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 10:09:32 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 10:09:32 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 10:09:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 10:09:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 10:10:13 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 10:10:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 10:10:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 10:10:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 10:10:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-04 11:22:41 [notice] Re-migrate 3.0.0 globals: Start 
2022-11-04 11:22:41 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2022-11-04 11:22:41 [notice] System typography already exist. nothing to do. 
2022-11-04 11:22:41 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2022-11-04 11:22:41 [notice] System colors already exist. nothing to do. 
2022-11-04 11:22:41 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2022-11-04 11:22:41 [notice] Custom colors already exist. nothing to do. 
2022-11-04 11:22:41 [notice] Re-migrate 3.0.0 globals: End 

JS: showing 8 of 8JS: 2022-10-21 10:59:36 [error X 2][https://www.travelzall.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.8:2:30926] can\'t access property \"model\", elementor.settings.page is undefined 
JS: 2022-10-21 12:52:33 [error X 4][https://www.travelzall.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060990] can\'t access property \"getBoundingClientRect\", $ is null 
JS: 2022-10-21 13:26:09 [error X 32][https://www.travelzall.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767806] can\'t access property \"localized\", this.store.find(...) is undefined 
JS: 2022-10-22 14:35:33 [error X 5][https://www.travelzall.com/wp-admin/post.php?post=2356&action=elementor# line 4 > injectedScript:1:1] redeclaration of let $dcWidgetIdInput 
JS: 2022-10-28 20:32:43 [error X 5][https://www.travelzall.com/things-to-do/:5449:5] FWP is not defined 
JS: 2022-11-03 15:08:17 [error X 26][https://www.travelzall.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51816] can\'t access property \"replace\", a is undefined 
JS: 2022-11-03 22:23:45 [error X 2][https://www.travelzall.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:694254] T.getContainer is not a function 
JS: 2022-11-04 08:40:10 [error X 1][https://www.travelzall.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51816] can\'t access property \"replace\" of undefined 

PHP: showing 7 of 7PHP: 2022-10-21 13:31:29 [notice X 83][/home/travelzall/public_html/wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-22 14:38:06 [notice X 36][/home/travelzall/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 22:19:51 [notice X 1][/home/travelzall/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 11:24:03 [notice X 10][/home/travelzall/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-03 14:43:03 [notice X 4][/home/travelzall/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::563] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-04 11:05:28 [error X 1][/home/travelzall/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/travelzall/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/travelzall/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/travelzall/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/travelzall/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/travelzall/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home/t [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-04 11:22:41 [notice X 2][/home/travelzall/public_html/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Dashboard Welcome for Elementor: Compatibility not specified
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	FacetWP - Elementor: Compatibility not specified
	Visibility Logic for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello there @Havenwebmanagement!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by tahmidbintaslim** [comment]
Hi @nicholaszein 

Similar kind of issue, I am having where I am using Elementor Pro 3.8.1 with E-Addons for Elementor. 

So my scenario is I am using Elementor Pro Widget called "Slides" that consist of repeater images. With the help of E-Addons for Elementor, I was able to see that Image Upload Field got a dynamic tag that can fetch image from Acf field --> Image Field. But after publishing the Slide Widget, I see no images.

My Config below:
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29
	MySQL version: mariadb.org binary distribution v10.4.24
	PHP Version: 7.4.29
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost/love_potion_v2
	Home URL: http://localhost/love_potion_v2
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Bangkok
	Admin Email: web@relevanceaudience.com
	Debug Mode: Active

== Theme ==
	Name: Glowing Child Theme
	Version: 1.0.0
	Author: G5 Theme
	Child Theme: Yes
	Parent Theme Name: Glowing
	Parent Theme Version: 1.0.6
	Parent Theme Author: G5 Theme

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.5
		Author: WP Engine

	Advanced Database Cleaner
		Version: 3.1.1
		Author: Younes JFR.

	e-addons for Elementor
		Version: 3.3.0.2
		Author: Nerds Farm

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.5
		Author: Wpmet

	G5 Blog
		Version: 1.1.3
		Author: G5

	G5 Core
		Version: 1.5.7
		Author: G5

	G5 Element
		Version: 1.2.3
		Author: G5

	G5 Shop
		Version: 1.2.6
		Author: G5

	Glowing Addons
		Version: 1.0.3
		Author: G5

	Smart Slider 3
		Version: 3.5.1.12
		Author: Nextend

	Ultimate Bootstrap Elements for Elementor
		Version: 1.2.4
		Author: G5Theme

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WPZOOM Instagram Widget & Block
		Version: 2.0.13
		Author: WPZOOM


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Inactive
	Form Submissions: Active
	Scroll Snap: Active


== Log ==
	
PHP: showing 4 of 4PHP: 2022-11-24 17:01:38 [notice X 1][C:\xampp\htdocs\love_potion_v2\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-image.php::48] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 17:02:53 [notice X 5][C:\xampp\htdocs\love_potion_v2\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-image.php::54] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 17:03:26 [notice X 1][C:\xampp\htdocs\love_potion_v2\wp-content\plugins\elementor\includes\conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 17:05:06 [notice X 3][C:\xampp\htdocs\love_potion_v2\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-image.php::67] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	e-addons for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Ultimate Bootstrap Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @tahmidbintaslim,

please submit a [new Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) so we can help you better. We can't track your issue from the comments of another issue.

Thanks 🙏
