### ISSUE TITLE
✔️ 🚀 Feature Request: Editor - save changes by ctrl/cmd + s

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20283]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you add a feature to save changes using ctrl + s in the elementor editor.

### Describe the solution you'd like

save changes by ctrl + s in elementor editor

**Comment by nicholaszein** [comment]
Hey Michael!

We have great news! 🙌 

### ✔️ This feature was added in Elementor v1.7! 🥳

You can learn more about Elementor Hotkeys [here](https://elementor.com/help/hotkeys/). 😉 

Cheers 🥂
