### ISSUE TITLE
🚀 Feature Request: Woocommerce Products widget Enhancements

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20294]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

There aren't very many customizations in the Product Widget.

### Describe the solution you'd like

I would love to be able to create a "Price List" using Woocommerce products.  Currently we use the "Price List" widget throughout our site for various fee's and add-ons for different services.  All of our WooCommerce products are linked to Square so it would be nice to just be able to update the Prices in Square or WooCommerce and have all of the price lists update on our site.

With most widgets there's a lot of customization options for Font, Pictures, Layout, etc... but not currently on the "Products" widget. I prefer more customization to an existing widget vs a Separate New widget. There are a couple of widgets in Elementor that seem close enough in functionality that they could have been a single widget but each is missing a small feature the other has (Portfolio vs Post)

Not sure which widget would be easier to add functionality to make this work but I like the layout and customization of the "Price List" widget but the Query functions of the Product widget.

### Describe alternatives you've considered

Custom CSS for Products widget-- but too much is required.

**Comment by nicholaszein** [comment]
Hello @cranstantinople,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. And this is why:

With **Elementor Pro v3.9** (currently in beta) you will be able to create your own templates for products. If you want to test yourself, join our [Beta Program](https://github.com/elementor/elementor/discussions/20328). 😉 💪 

Feel free to contact us again with other feature suggestions. 😉 

Best regards
