### ISSUE TITLE
🔗 🔃 🐞 Bug Report: Loop Grid - Conflicts with Motion Effects and "Load More" pagination (Merged with #20293)

### ISSUE THREAD

**Issue by medieskolenlyngby** [elementor/elementor#20292]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When working with motion effect within a loop-template there is a problem/bug.

When using infinite scroll-pagination ( and Load on click-pagination ) - the element with motion effect is not showed.

### Steps to reproduce

1. Having a loop with a text and a image (with fade in motion effect on the image)
2. Showing 6 items and the rest to be shown with  Load on click-pagination
3. When clicking to show extra items the images (with fade in motion effect ) is not there (not shown). The text element (with no motion effect) is shown.

Same problem with infinite scroll-pagination  

I'm using container (if this is important?)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Note: I have anonymized my domain	
				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.30
	PHP Version: 7.4.22
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: http://mytestsubdomain.mydomain.dk
	Home URL: http://mytestsubdomain.mydomain.dk
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Copenhagen
	Admin Email: lars@westend.dk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

== Elements Usage ==
	
	header : 2
		nav-menu : 1
		text-editor : 2
	page : 1
		jet-listing-dynamic-field : 2
		shortcode : 1
	wp-page : 1
		container : 2
		loop-grid : 1
		text-editor : 2
	single-page : 1
		container : 15
		divider : 1
		jet-listing-dynamic-field : 1
		jet-listing-dynamic-link : 1
		loop-grid : 1
		shortcode : 1
		text-editor : 4
		toggle : 2
	loop-item : 1
		container : 1
		jet-listing-dynamic-link : 1
		theme-post-featured-image : 1
	jet-listing-items : 0
		jet-listing-dynamic-link : 1
		shortcode : 1
		text-editor : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 7 of 7PHP: 2022-08-06 14:11:41 [notice X 1][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-12 14:20:12 [notice X 1][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/includes/widgets/menu-anchor.php::156] Undefined index: anchor [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-12 14:37:57 [notice X 12][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 23:11:39 [error X 2][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/www/mytestsubdomain.mydomain.dk/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/www/mytestsubdomain.mydomain.dk/wp-includes/class-wp-hook.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-03 18:44:27 [notice X 4][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-04 12:17:51 [notice X 4][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-11-04 12:18:14 [notice X 1][/home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /home/www/mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /home/www/mytestsubdomain.mydomain.dk/wp-includes/rest-api/class-wp-rest-server.php(1171): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]

Log: showing 20 of 262022-08-06 14:15:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-08-06 14:15:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.7.3',
)]
2022-08-06 14:15:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.7.3',
)]
2022-08-12 12:23:32 [info] elementor::elementor_updater Started 
2022-08-12 12:23:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-12 12:23:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-12 12:23:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-12 12:23:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-11-02 12:15:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.8.0',
)]
2022-11-02 12:15:13 [info] elementor::elementor_updater Started 
2022-11-02 12:15:13 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-02 12:15:13 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-02 12:15:13 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-02 12:15:13 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-02 12:15:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.8.0',
)]
2022-11-02 12:30:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.0',
)]
2022-11-02 12:30:22 [info] elementor-pro::elementor_pro_updater Started 
2022-11-02 12:30:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-02 12:30:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-02 12:30:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.0',
)]

JS: showing 3 of 3JS: 2022-11-03 17:34:20 [error X 1][http://mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:1061528] $ is null 
JS: 2022-11-03 20:59:05 [error X 7][http://mytestsubdomain.mydomain.dk/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51816] a is undefined 
JS: 2022-11-04 11:34:18 [error X 15][http://mytestsubdomain.mydomain.dk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:694254] T.getContainer is not a function 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @medieskolenlyngby!

Thank you for your submission! 🙏 

### 🔃 This issue is being merged to issue #20293.

Which is the same issue you've posted in a row but with more details.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to avoid submitting duplicate posts. 

Best regards,

Nick
