### ISSUE TITLE
🔗 🚀 Feature Request: Loop Builder Individual Post Data Could Fed to Dynamic Content on Page or Popup (Duplicate of #7106)

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20297]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Post and Portfolio widgets have overlapping features but each is missing some small features of the other.

### Describe the solution you'd like

Out of the box loop builder seems much more robust and I'm sure it will eventually be able to replace both.  It would be nice if there a way to create a loop from posts being able to feed that post data to dynamic content fields elsewhere on the page or a popup.

### Additional context

I would use this on multiple sites for different functions but a specific use case would be creating a custom post type to create a "Preferred Vendor" portfolio with names and logos of vendors.  When you click the vendor "post", the contact information is populated in a contact card on the top of the page or in a popup.

**Comment by nicholaszein** [comment]
Hey @cranstantinople,

Thank s for your request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. 

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #7106

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

Kind regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.26.0! 🥳 

You can now use the **Off-Canvas** widget inside your **Loop Item** templates to display additional Dynamic Content for each post in your **Loop Grid** widgets! 🎉 🥳 🙌 

You can learn more about the Off-Canvas widget (and how to use it) here: 
https://elementor.com/help/off-canvas-widget/
And about the Loop Grid here: 
https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
