### ISSUE TITLE
⛔ 🚀 Feature Request: Loop Builder - Add hover options similar to those of the Portfolio widget

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20298]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Portfolio and Post widgets have similar functions neither is as robust as loop builder is shaping up to be.  But flexbox can't quite replace the overlay/hover feature that portfolio currently has.

### Describe the solution you'd like

It would be great if there was an option to layer and/or stack flexboxes on top of each other.  When turned on, the tabs for each flexbox could go side by side so each could be selected individually.  I'm not sure if the option to hide/show container on hover exists already but it could be accomplished with simple css if not.  A GUI option would be ideal.

**Comment by nicholaszein** [comment]
Hello @XXX,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

You can use custom positioning and custom CSS to show/hide elements when the parent has hovered over. Here's an example:

1. Add a class to the parent container like `.hover-me` for example.
2. Add a class like `.show-me-on-hover` to the elements inside the parent container that you want to show on hover.
3. Add the following custom CSS to the parent container:

````
.show-me-on-hover {
    transition: all .3s ease-out;
}

.hover-me:not(:hover):not(:focus-within) .show-me-on-hover {
    opacity: 0;
    visibility: hidden;
}
````

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Feel free to contact us again with other feature suggestions. 😉 

Best regards
