### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Elementor Pro affects the functionality of the modern event calendar plugin

### ISSUE THREAD

**Issue by moriczmate** [elementor/elementor#20290]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Pro affects the functionality of the modern event calendar plugin

The modern event calendar modal pupop view of MEC does not work with elementor pro. After disabling the extension the function worked fine. 

When opening events in modal popup view I want to open the event however the event opens in a new window. 

### Steps to reproduce

https://bellamate.muveszpr.hu/#esemenyek

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.32
	PHP Memory Limit: 256M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://bellamate.muveszpr.hu
	Home URL: https://bellamate.muveszpr.hu
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: hu
	Timezone: 0
	Admin Email: moricz.mateen@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: hu_HU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	AJAX Thumbnail Rebuild
		Version: 1.13
		Author: junkcoder, ristoniinemets

	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	AnyWhere Elementor Pro (Premium)
		Version: 2.25.3
		Author: WP Vibes

	Autoptimize
		Version: 3.1.3
		Author: Frank Goossens (futtta)

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.9.0-dev1
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.11.16
		Author: WPVibes

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Modern Events Calendar Lite
		Version: 6.6.12
		Author: Webnus

== Elements Usage ==
	
	container : 1
		button : 2
		container : 14
		heading : 2
		icon : 8
		icon-box : 1
		social-icons : 1
		spacer : 8
		text-editor : 26
		video : 8
		wts-modal-popup : 1
	loop : 3
		container : 6
		heading : 2
		icon : 2
		wts-modal-popup : 1
	page : 7
		MEC : 5
		ae-post-blocks-adv : 8
		button : 21
		container : 6
		heading : 45
		icon : 5
		icon-box : 8
		image : 26
		shortcode : 1
		social-icons : 5
		spacer : 2
		text-editor : 22
	popup : 1
		icon : 1
		nav-menu : 1
		social-icons : 1
	section : 1
		heading : 2
		social-icons : 1
		text-editor : 4
	wp-post : 0
		ae-post-content : 2
		ae-post-title : 1
		container : 21
		heading : 36
		icon-box : 2
		icon-list : 2
		wts-modal-popup : 1
	wp-page : 11
		MEC : 6
		ae-post-blocks-adv : 10
		button : 28
		container : 43
		gallery : 3
		heading : 42
		icon : 6
		icon-box : 14
		image : 40
		image-gallery : 1
		posts : 5
		social-icons : 5
		spacer : 2
		text-editor : 27
		theme-site-logo : 5

== Elementor Experiments ==
	Optimalizált DOM kimenet: Aktív
	Improved Asset Loading: Alapértelmezés szerint aktív 
	Továbbfejlesztett CSS betöltés: Alapértelmezés szerint aktív 
	Inline Font Icons: Aktív
	Hozzáférhetőségi fejlesztések: Aktív
	Additional Custom Breakpoints: Aktív
	Import Export Website Kit: Aktív
	Hide native WordPress widgets from search results: Aktív
	admin_menu_rearrangement: Alapértelmezés szerint inaktív
	Flexbox Container: Aktív
	Default to New Theme Builder: Aktív
	Hello Theme Header & Footer: Aktív
	Landing oldalak: Aktív
	Színválasztó: Aktív
	Favorite Widgets: Aktív
	Admin Top Bar: Aktív
	Page Transitions: Aktív
	Notes: Aktív
	Ismétlés: Alapértelmezés szerint aktív 
	Form Submissions: Aktív
	Scroll Snap: Aktív

== Log ==
	
JS: showing 10 of 10JS: 2022-10-05 23:54:29 [error X 4][https://bellamate.muveszpr.hu/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.7.7:2:10121] Failed to execute \'observe\' on \'IntersectionObserver\': parameter 1 is not of type \'Element\'. 
JS: 2022-10-26 10:56:53 [error X 6][https://bellamate.muveszpr.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:769410] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-11-04 14:49:06 [error X 23][https://bellamate.muveszpr.hu/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] Cannot read properties of undefined (reading \'tools\') 
JS: 2022-11-04 14:59:30 [error X 1][https://bellamate.muveszpr.hu/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view458\") has already been destroyed and cannot be used. 
JS: 2022-11-04 16:22:35 [error X 72][https://bellamate.muveszpr.hu/wp-admin/post.php?post=775&action=elementor#:1:1] Identifier \'$dcWidgetIdInput\' has already been declared 
JS: 2022-11-05 14:22:01 [error X 31][https://bellamate.muveszpr.hu/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-06 10:47:14 [error X 1][https://bellamate.muveszpr.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:768903] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-11-06 10:52:31 [error X 1][https://bellamate.muveszpr.hu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev1:3:595040] Cannot read properties of undefined (reading \'models\') 
JS: 2022-11-06 10:56:10 [error X 5][https://bellamate.muveszpr.hu/wp-content/plugins/elementor/assets/lib/nouislider/nouislider.min.js?ver=13.0.0:2:4604] noUiSlider (13.0.0): \'start\' option is incorrect. 
JS: 2022-11-06 12:06:36 [error X 4][https://bellamate.muveszpr.hu/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.9.0-dev1:2:18515] Cannot delete property \'ae_rule_type\' of # 

Log: showing 20 of 272022-10-06 16:51:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-21 17:35:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'AnyWhere Elementor Pro',
  'from' => '2.25.2',
  'to' => '2.25.3',
)]
2022-11-04 14:48:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev5',
)]
2022-11-04 14:48:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev4',
)]
2022-11-04 14:48:50 [info] elementor::elementor_updater Started 
2022-11-04 14:48:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-04 14:48:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-04 14:48:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev4',
)]
2022-11-04 14:48:53 [info] elementor-pro::elementor_pro_updater Started 
2022-11-04 14:48:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-04 14:48:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-04 14:48:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev5',
)]
2022-11-04 14:55:01 [notice] Re-migrate 3.0.0 globals: Start 
2022-11-04 14:55:01 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2022-11-04 14:55:01 [notice] System typography already exist. nothing to do. 
2022-11-04 14:55:01 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2022-11-04 14:55:01 [notice] System colors already exist. nothing to do. 
2022-11-04 14:55:01 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2022-11-04 14:55:01 [notice] Custom colors already exist. nothing to do. 
2022-11-04 14:55:01 [notice] Re-migrate 3.0.0 globals: End 

PHP: showing 5 of 5PHP: 2022-10-06 17:04:07 [notice X 279][/home/muveszpr/bellamate.muveszpr.hu/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-26 10:53:43 [notice X 3][/home/muveszpr/bellamate.muveszpr.hu/wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 21:20:09 [warning X 2][/home/muveszpr/bellamate.muveszpr.hu/wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://bellamate.muveszpr.hu/wp-content/uploads/2022/11/Glyphter.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-04 14:55:01 [notice X 1][/home/muveszpr/bellamate.muveszpr.hu/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-06 10:52:28 [notice X 2][/home/muveszpr/bellamate.muveszpr.hu/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Compatibility not specified
	Elementor Addon Elements: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @moriczmate,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

Elementor does not have any compatibility support for the Moder Events Calendar plugin, especially when their content is used inside Elementor Pop-ups. You need to contact MEC's support and ask them how to use their plugin inside Elementor Pop-ups. 

In fact, I can see they do have support for Elementor, and have a few [add-ons](https://webnus.net/modern-events-calendar/addons/?ref=16) you can use with Elementor. You should check their [documentation](https://www.webnus.net/dox/modern-events-calendar/?s=elementor), and contact their [support](https://wordpress.org/support/plugin/modern-events-calendar-lite/).

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**), and the Modern Events Calendar plugin.
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
3. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look. But keep in mind that if this is a limitation in compatibility from the MEC plugin with Elementor Pop-ups, you'll need to ask them to add that compatibility to their plugin.

Regards
