### ISSUE TITLE
⛔ 🚀 Feature Request: Allow to add custom PHP to Elementor's Custom Code

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20295]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It's frustrating to have to create a "Custom" plugin or Child Themes to add custom functions.

### Describe the solution you'd like

The "Custom Code" feature has helped a lot in this aspect but it's missing the ability to create custom PHP Functions.  I currently use the "Code Snippets" plugin to add PHP functionality for custom actions, etc... but I would love to be able to accomplish this without an additional plugin.

Elementor has eliminated the need for dozens of plugins I used previously and by using the "Hello Elementor" theme for all new sites, I've saved countless hours troubleshooting compatibility issues.  Would love to be able to keep removing plugins-- especially when Elementor already has a lot of overlapping features of the other plug-ins I'm using.

### Describe alternatives you've considered

"Code Snippets"

**Comment by nicholaszein** [comment]
Hello @cranstantinople,

Thank you for submitting your request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Feel free to contact us again with other feature suggestions. 😉 

Best regards
