### ISSUE TITLE
🔗 🚀 Feature Request : Multiple suggestions form improving the Login Form page (Duplicate of #5184)

### ISSUE THREAD

**Issue by gowthu-cmd** [elementor/elementor#20300]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

1. We can customize the Registration & Login page. ( It gives a lot of flexibility ) Currently, it's pretty limited & we need to use third-party Plugins
2. Every single client of mine has asked about phone number validation which accepts any character length. We can make people add their genuine phone numbers to some extent. So Adding conditions will be very useful. 
3. Adding a calculator or calculation feature ( Along with Range Slider ) will help to build Quote and Return on Investment calculation Forms ( Currently we have to rely on third-party plugins )

### Describe the solution you'd like

1. Add the Registration & Login Form widget either separately or give the option to select between Register, Login & Contact
2. Conditions to the form. Currently, it's pretty limited there is not even a phone number validation where we can set the character length or Add Country Code (It's a basic requirement actually it should come by default ) 🥲
3. Add a calculation or calculator option for the form
3. Add Range Slider Field to the form
4.  Add a feature to set a custom Registration and Login Page which replaces the default WordPress Registration & Login Page.

Thank you for listening to us & bringing the Container & the loop feature it will be pretty useful. Hope you will look into these & incorporate them in future updates 😄

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/5184 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
