### ISSUE TITLE
❌ Really? `.e-container` to `.e-con` without any backward compatibility?

### ISSUE THREAD

**Issue by simkoG** [elementor/elementor#20311]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Dear Developers, 

Why did you replace the container classname from `.e-container` to `.e-con` without any backward compatibility?

https://github.com/elementor/elementor/blob/140626d7bf241d5aef04204d02eaa654636eb321/readme.txt#L262-L265

### Steps to reproduce

none

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

none

**Comment by loucasl** [comment]
Containers were still in Alpha at the time, it's expected that infrastructure and markup changes would be made

**Comment by nicholaszein** [comment]
Hello @simkoG,

this was addressed during our [beta-testing](https://github.com/elementor/elementor/discussions/19854) (Beta-3) program for this release, and it was also widely announced in our [Facebook Community](https://www.facebook.com/groups/Elementors/permalink/5326499360809140/) and [Developers Blog Posts](https://developers.elementor.com/elementor-38-developers-update/). As you know, beta and alpha experiments are not recommended to be used on production websites, as they might receive breaking changes.

This of course will only affect you negatively if you used Custom CSS to target containers, as anything else will be properly replaced once you use the Elementor Data Updater that fires after each update.

The replacement was made to improve performance. We try our best to maintain BC, but there are some times when the only way to improve our products is to introduce breaking changes.

As the Container Experiment matures and is now a Stable experiment, you can use it with the assurance that fewer breaking changes might be introduced.
