### ISSUE TITLE
⛔ 🚀 Feature Request: Add an option to select ContentType for form web hooks

### ISSUE THREAD

**Issue by lesh4wn** [elementor/elementor#20314]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I am trying to submit a webhook after form submission to Microsoft Flow/Power Automate but it appears that Power Automate doesn't natively support the "application/x-www-form-urlencoded" content type. I have researched and found a few third party options but they are relatively expensive for solving this issue. 

### Describe the solution you'd like

I am hoping that there is a way you can currently switch to use the "application/json" content type or that it's a feature that can be added in the near future.

### Describe alternatives you've considered

I have considered sending a webhook to Zapier and then from Zapier sending a POST request to my Power Automate workflow. However, this adds an unnecessary middleman if switching content types was possible.

**Comment by nicholaszein** [comment]
Hello @lesh4wn,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Feel free to contact us again with other feature suggestions. 😉 

Best regards
