### ISSUE TITLE
⛔ 🚀 Feature Request: Domain Mapping on Landing Pages Manager

### ISSUE THREAD

**Issue by gireaud** [elementor/elementor#20317]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Disk usage matters! Some clients just need a simple landing page, not an entire WordPress site.

But when you want to create and manage multiple landing pages on a single WordPress installation, you face a problem related to client's branding and the inconsistency presented on the domain name.

### Describe the solution you'd like

It's simple, I want to avoid installing WordPress sites on every client project who want a landing page… I have an expert plan and would like to be able to manage client's landing pages in one single WordPress installation, so, it would be nice if I can connect a domain name to each landing page I create to match my client branding.

### Additional context

I think Elementor is more than a page builder… It can be an all-in-one tool for marketers like me who wants to create digital experiences for clients that need to sell on the internet.

We need to beat ClickFunnels, and it's ridiculous overpriced plans!

**Comment by nicholaszein** [comment]
Hello @gireaud,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap.

This is something you need to do at a server level, and not something Elementor can control. Contact your hosting support and ask them to help with this issue.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
