### ISSUE TITLE
🔗 🐞 Bug Report: Elementor Doesn't Work with Ninja Forms after WP 6.1 Update (Related to #20285)

### ISSUE THREAD

**Issue by bvickman** [elementor/elementor#20319]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Ninja Forms no longer display in the Elementor page builder after WordPress version 6.1 is installed. 

https://www.loom.com/share/2674680b6652409592114648872b7f3e

### Steps to reproduce

1. Update to all current versions of WP, Elementor, and Ninja Forms
2. Visit a page or post where a Ninja Forms shortcode or widget should be inserted in Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://staging6.projects.charitableventuresoc.org
	Home URL: https://staging6.projects.charitableventuresoc.org
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: admin@charitableventuresoc.org
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Activity Log
		Version: 2.8.4
		Author: Activity Log Team

	All-in-One WP Migration
		Version: 7.67
		Author: ServMask

	Copy & Delete Posts
		Version: 1.3.4
		Author: Copy Delete Posts

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Font Awesome
		Version: 4.3.1
		Author: Font Awesome

	Force Login
		Version: 5.6.3
		Author: Kevin Vess

	Google Language Translator
		Version: 6.0.15
		Author: Translate AI Multilingual Solutions

	Hide Admin Bar From Front End
		Version: 3.4.1
		Author: Ankit Panchal

	Menu Image
		Version: 3.0.8
		Author: Freshlight Lab

	My Custom Functions
		Version: 4.51
		Author: Space X-Chimp

	Ninja Forms
		Version: 3.6.14
		Author: Saturday Drive

	Ninja Forms - Conditional Logic
		Version: 3.1
		Author: The WP Ninjas

	Ninja Forms - Excel Export
		Version: 3.3.4
		Author: Saturday Drive

	Ninja Forms - File Uploads
		Version: 3.3.14
		Author: The WP Ninjas

	Ninja Forms - Layout & Styles
		Version: 3.0.29
		Author: The WP Ninjas

	Ninja Forms - Multi-Part Forms
		Version: 3.0.26
		Author: The WP Ninjas

	Ninja Forms - PDF Form Submissions
		Version: 3.2.0
		Author: Ninja Forms

	Ninja Forms - Save Progress
		Version: 3.0.25
		Author: The WP Ninjas

	Ninja Forms - User Management
		Version: 3.2.0
		Author: WP Ninjas

	Ninja Forms Signature Contract Add-On by ApproveMe.com
		Version: 3.1.7.4
		Author: ApproveMe.com

	Popup Maker
		Version: 1.16.12
		Author: Popup Maker

	SiteGround Optimizer
		Version: 7.2.5
		Author: SiteGround

	SiteGround Security
		Version: 1.3.5
		Author: SiteGround

	SVG Support
		Version: 2.5.1
		Author: Benbodhi

	WP E-Signature
		Version: 1.7.5
		Author: ApproveMe.com

	WP E-Signature Business add-ons
		Version: 1.7.4
		Author: ApproveMe.com

	WP Rollback
		Version: 1.7.2
		Author: GiveWP.com

	WP SVG Images
		Version: 4.1
		Author: ShortPixel

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 422022-10-03 08:02:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 08:02:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 08:02:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 08:02:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-11-01 07:22:59 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 07:22:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 07:22:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 07:22:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:22:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:22:59 [info] elementor::elementor_updater Started 
2022-11-01 07:22:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 07:22:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 07:22:59 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 07:22:59 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 07:22:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 07:22:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-07 06:40:24 [info] elementor-pro::elementor_pro_updater Started 
2022-11-07 06:40:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-07 06:40:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-07 06:40:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 1 of 1PHP: 2022-10-04 14:24:37 [notice X 2][/home/customer/www/projects.charitableventuresoc.org/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @bvickman! 

Thank you for submitting your issue! 🙏 

This issue might be related to #20285.

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by bvickman** [comment]
Hi @nicholaszein!

It seems that WP version 6.1.1 corrected the disconnect between Ninja Forms and Elementor. 

Fingers crossed the issue is corrected with the minor bug fixes in 6.1.1!

**Comment by nicholaszein** [comment]
Hello @bvickman!

Thanks for the feedback! 🙏 

Does it mean this issue was resolved?
