### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Pro - Post widget, "load more" button border color affects border color in loop template too.

### ISSUE THREAD

**Issue by HuibSmeets** [elementor/elementor#20321]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

Just ran into the following: I have a list of posts that I display with a custom loop layout and custom loop grid. I had pagination active with numbers. All fine. Then I switched to the 'Load more' pagination and styled the button with a border color. My custom loop also has a button and when I changed the border color of the 'Load more' button the border color of button in the custom loop also changed! Resetting the 'Load more' button border color to the default --> buttons in the loop also fine again. 

Here it is okay (load more border color = default).

<img width="1213" alt="Schermafbeelding 2022-11-07 om 20 43 01" src="https://user-images.githubusercontent.com/117679210/200400505-851a283f-4650-4d88-89c1-93536c2e9c72.png">

But when I change the border color the color in the loop changes too.

<img width="1213" alt="Schermafbeelding 2022-11-07 om 20 46 49" src="https://user-images.githubusercontent.com/117679210/200401551-ac59d2da-b56e-4ed1-ab5c-ea8280b1a24b.png">

FYI: other button styling options like text color, background do not affect the button in the loop.

### Steps to reproduce

1) Create a post loop template with a button that has a colored border

2) Use the Elementor Pro Post Widget and use the custom post layout template 

3) Set the pagination to 'Load more'.

4) Alter the border color of the 'Load More' button.

Now the button border color in the loop changes also.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Unix)
	MySQL version: MySQL Community Server (GPL) v5.7.38
	PHP Version: 7.4.32
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: http://staging.peterwinteraeken.nl
	Home URL: http://staging.peterwinteraeken.nl
	WP Multisite: No
	Max Upload Size: 5 MB
	Memory limit: 384M
	Max Memory limit: 384M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Amsterdam
	Admin Email: huib@huibsmeets.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

== Active Plugins ==
	ACF QuickEdit Fields
		Version: 3.2.1
		Author: Jörn Lund

	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	Big File Uploads
		Version: 2.1.1
		Author: Infinite Uploads

	Cache Enabler
		Version: 1.8.12
		Author: KeyCDN

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.3.5
		Author: Really Simple Plugins

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Doneren met Mollie
		Version: 2.10.0
		Author: Wobbie.nl

	Duplicator
		Version: 1.5.0
		Author: Snap Creek

	Dynamic Visibility for Elementor
		Version: 5.0.1
		Author: Dynamic.ooo

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Premium Addons for Elementor
		Version: 4.9.36
		Author: Leap13

	PublishPress Future
		Version: 2.7.8
		Author: PublishPress

	Upload Larger Plugins
		Version: 1.7
		Author: David Anderson

	Windows Compatibility Fix
		Version: 1.0.2
		Author: Dave Jesch

	WP Crontrol
		Version: 1.14.0
		Author: John Blackbourn & crontributors

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Elements Usage ==
	
	custom_grid : 1
		ele-loop-item : 1
	footer : 1
		heading : 9
		icon : 5
		nav-menu : 1
		spacer : 2
		text-editor : 5
	header : 1
		icon : 2
		image : 1
	loop : 12
		audio : 1
		button : 7
		flip-box : 1
		heading : 19
		icon : 9
		post-info : 3
		spacer : 1
		text-editor : 6
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 12
		video : 2
	page : 2
		heading : 2
	popup : 5
		button : 2
		divider : 2
		heading : 3
		icon : 1
		nav-menu : 2
		posts : 1
		share-buttons : 2
		text-editor : 2
	widget : 0
		divider : 1
	wp-page : 16
		button : 1
		divider : 13
		form : 6
		heading : 42
		icon : 12
		posts : 6
		premium-carousel-widget : 1
		spacer : 24
		testimonial-carousel : 1
		text-editor : 25
		theme-post-title : 4
	single-post : 3
		button : 2
		divider : 6
		form : 1
		heading : 3
		post-info : 1
		post-navigation : 1
		spacer : 4
		text-editor : 7
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 4
	single-page : 6
		posts : 6
	error-404 : 1
		heading : 2
		nav-menu : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 11 of 11PHP: 2022-10-01 14:36:23 [notice X 32][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/dynamic-visibility-for-elementor/class/controls.php(48): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-03 19:33:30 [notice X 35][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/widgets/audio.php::329] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 20:17:48 [notice X 2][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/dynamic-visibility-for-elementor/class/controls.php(48): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-20 20:17:54 [notice X 265][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 23:31:51 [notice X 4486][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 23:56:53 [notice X 264][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/dynamic-visibility-for-elementor/class/controls.php(48): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-24 09:37:39 [notice X 2][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-25 16:55:24 [notice X 5][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-25 18:30:18 [notice X 2][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 17:15:38 [notice X 3][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-06 12:11:18 [error X 1][/mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor-pro/modules/popup/module.php::120] Uncaught Error: Call to a member function save_display_settings_data() on bool in /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor-pro/modules/popup/module.php:120
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings()
#1 /mnt/web407/a1/83/57710183/htdocs/WP/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2 /mnt/web407/a1/83/57710183/htdocs/WP/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /mnt/web407/a1/83/57710183/htdocs/WP/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /mnt/web407/a1/83/57710183/htdocs/WP/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /mnt/web407/a1/83/57710183/htdocs/WP/wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 222022-10-14 11:25:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-14 11:25:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-14 11:25:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-31 19:41:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 19:41:59 [info] elementor::elementor_updater Started 
2022-10-31 19:41:59 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-31 19:42:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-31 19:42:01 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-31 19:42:01 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-31 19:42:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-02 16:25:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-02 16:25:04 [info] elementor-pro::elementor_pro_updater Started 
2022-11-02 16:25:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-02 16:25:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-02 16:25:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-02 16:25:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-07 17:49:13 [info] elementor-pro::elementor_pro_updater Started 
2022-11-07 17:49:13 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-07 17:49:13 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-07 17:49:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

JS: showing 9 of 9JS: 2022-10-23 22:17:17 [error X 1][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.7.8:2:4806] undefined is not an object (evaluating \'e.attributes\') 
JS: 2022-10-31 17:27:12 [error X 3][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060991] null is not an object (evaluating \'$.getBoundingClientRect\') 
JS: 2022-10-31 18:44:34 [error X 7][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.0:2:2968] Can\'t find variable: elementor_new_template_form_controls 
JS: 2022-10-31 19:28:36 [error X 27][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.8.0:2:19453] undefined is not an object (evaluating \'e.offset().top\') 
JS: 2022-11-01 20:11:20 [error X 80][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2022-11-03 21:42:41 [error X 1][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.8.0:2:51367] undefined is not an object (evaluating \'q.functionName.includes\') 
JS: 2022-11-04 16:41:56 [error X 6757][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16819] null is not an object (evaluating \'this._lastColor.clone\') 
JS: 2022-11-04 16:42:12 [error X 78][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] null is not an object (evaluating \'this._eventListener[t]\') 
JS: 2022-11-04 19:49:31 [error X 1][http://staging.peterwinteraeken.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:768951] undefined is not an object (evaluating \'T.originalEvent.key.toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Ele Custom Skin: Compatible
	Elementor Pro: Incompatible
	Premium Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Incompatible
	Ele Custom Skin: Compatible
	Premium Addons for Elementor: Incompatible

**Comment by nicholaszein** [comment]
Hello @HuibSmeets,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Tested with Elementor v3.8.1 and Elementor Pro 3.8.1, we could not reproduce your issue. See the screenshot below:

![image](https://user-images.githubusercontent.com/113993460/201583390-5dfc5778-8506-4431-8a24-30af4e0776d4.png)

* I see you have a few addons installed, and also cache plugins.
* Your issue is most likely related to cache.


### ✅ What you can do to solve your issue:
* [Regenerate Elementor's CSS & Data](https://elementor.com/help/tools/).
* Clear and temporarily disable any type of performance optimization and cache.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
