### ISSUE TITLE
⛔  🚀 Feature Request: Increase Width Of Scrollbars 

### ISSUE THREAD

**Issue by wmullaney** [elementor/elementor#20324]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

- The scrollbars are too narrow. Most users would agree with me on this. Narrow scrollbars like this were originally only intended to be used as a reference for mobile devices where mouse pointers were never going to be used but a user would still need to know where they were while scrolling a page. On a workstation or laptop narrow scrollbars are a nuisance. I work mainly on a laptop and it is almost impossible to use the scroll bars. Yes I know I can increase the scrollbars using my operating system and I have done that because even gnome in linux is getting ridiculous with how skinny their scrollbars are. The scrollbars for elementor are controlled by css within the plugin which means this is a super easy update. I have been able to manually edit the css and make them wider but updates obviously are a thing and every website I spin up has to be tweaked. I can always work around this but geez. I get it! OK the narrow scroll bars "look cool" or whatever but we can have form with function. I'm almost sure this will get ignored but maybe, just maybe someone will understand what I and many others are talking about.

### Describe the solution you'd like

Just increase the width of the scrollbars a few pixels

### Describe alternatives you've considered

I have manually changed the css to increase the scrollbar width.

### Additional context

Ever wondered why door knobs and light switches are a certain height? Same reason for this feature/update request.

**Comment by nicholaszein** [comment]
Hello @wmullaney,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

#### ❌ Elementor does not modify or control any scrollbar styles. This is either a problem with your Theme, a 3rd party add-on, your Browser, or your Operating System.

Feel free to contact us again with other feature suggestions. 😉 

Best regards
