### ISSUE TITLE
⛔ 🚀 Feature Request: Two similar options to return to the previous page when editing the loop.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20323]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

When we edit the loop item, two options are displayed to return to the previous page. **1- save & back**   **2- edit page**

![Screenshot (881)](https://user-images.githubusercontent.com/88034902/200514424-ef9a9452-e601-4337-821e-35e70f20160b.png)

This does not sound interesting. Because they both do the same thing. Therefore, it is better to delete one of them. I think it is better to delete the edit page option. One option is enough to do this.

### Describe the solution you'd like

To avoid the same action of two buttons, remove the edit page option in the edit page of the loop item.

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

- Each option has a different function. One is to edit a page (this is a global behavior) and works the same way as the options to edit the Header and edit the Footer.
- The Loop Item template's _"Save & Back"_ handle was created to go back directly to the latest template. It doesn't mean it would be the _"Edit Page"_ template.
- It's good to have redundancy, and this doesn't affect the user experience negatively.

We appreciate your concern though! Thanks for sharing your insights! 🤓

Feel free to contact us again with other feature suggestions. 😉 

Best regards
