### ISSUE TITLE
❌ Invalid Issue: My fonts don't look right

### ISSUE THREAD

**Issue by BlaquePrinc3ss** [elementor/elementor#20341]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My fonts suddenly changed. The fonts are still installed on Elementor but still don't look right.

### Steps to reproduce

1. deleted / re-uploaded fonts
2. updated elementor

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v10.6.7
	PHP Version: 8.0.17
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://tommeetippee.me
	Home URL: https://tommeetippee.me
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: asifrazarizvi@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.6.7
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.67
		Author: ServMask

	CMP - Coming Soon & Maintenance Plugin
		Version: 4.1.2
		Author: NiteoThemes

	Elementor
		Version: 3.10.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-dev1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.2
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.3.2
		Author: WPDeveloper

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.9.6
		Author: HasThemes

	Royal Elementor Addons
		Version: 1.3.50
		Author: WP Royal

	WPForms Lite
		Version: 1.7.6
		Author: WPForms

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

== Elements Usage ==
	
	popup : 40
		button : 44
		heading : 24
		image : 23
		spacer : 13
		text-editor : 24
		video : 14
	section : 113
		heading : 191
		image : 25
		spacer : 23
		text-editor : 181
		video : 23
	wp-page : 78
		button : 57
		elementskit-simple-tab : 24
		heading : 177
		icon : 26
		image : 41
		image-carousel : 3
		spacer : 111
		text-editor : 104
		video : 1
		wpr-data-table : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active by default
	Save as Default: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 212022-06-23 14:05:59 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-06-23 14:05:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.6.6',
)]
2022-06-23 14:05:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.6.6',
)]
2022-08-22 09:56:04 [info] elementor::elementor_updater Started 
2022-08-22 09:56:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-22 09:56:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-22 09:56:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.8.0-dev3',
)]
2022-08-22 09:56:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.8.0-dev3',
)]
2022-11-09 11:46:23 [info] elementor-pro::elementor_pro_updater Started 
2022-11-09 11:46:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-09 11:46:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-09 11:46:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.10.0-dev1',
)]
2022-11-09 11:46:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.10.0-dev1',
)]
2022-11-09 13:22:31 [info] elementor::elementor_updater Started 
2022-11-09 13:22:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-09 13:22:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-09 13:22:32 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-09 13:22:32 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-09 13:22:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev3',
  'to' => '3.10.0-dev1',
)]
2022-11-09 13:22:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev3',
  'to' => '3.10.0-dev1',
)]

JS: showing 7 of 7JS: 2022-06-24 10:16:44 [error X 125][http://localhost/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-29 08:48:16 [error X 8][http://tommeetippee.me/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:767576] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-09-29 11:26:52 [error X 2][http://tommeetippee.me/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:632007] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-10-04 11:55:49 [error X 2][http://tommeetippee.me/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:767069] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-10-06 07:59:08 [error X 2][http://tommeetippee.me/wp-content/plugins/premium-addons-for-elementor/assets/editor/js/editor.js?ver=4.9.34:304:55] Cannot read properties of undefined (reading \'removeClass\') 
JS: 2022-10-06 08:30:56 [error X 16][http://tommeetippee.me/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:692080] T.getContainer is not a function 
JS: 2022-10-21 07:29:39 [error X 4][http://tommeetippee.me/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:646945] this.model.isValidChild is not a function 

PHP: showing 15 of 15PHP: 2022-08-22 12:26:56 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Attempt to read property "email" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-16 11:09:31 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-26 06:37:37 [warning X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-27 13:12:06 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /bitnami/wordpress/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /bitnami/wordpress/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /opt/bitnami/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#7 /bitnami/wordpress/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action()
#8 /bitnami/wordpress/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /bitnami/wordpress/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /bitnami/wordpress/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#12 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#13 /opt/bitnami/wordpress/wp-includes/plugin.php(524): WP_Hook->do_action()
#14 /opt/bitnami/wordpress/wp-cron.php(138): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-28 10:06:01 [warning X 18][/bitnami/wordpress/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 09:12:17 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/managers/widgets.php::408] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /bitnami/wordpress/wp-content/plugins/elementor/includes/managers/widgets.php:408
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget()
#1 /bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /opt/bitnami/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /opt/bitnami/wordpress/wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 11:30:40 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php::183] Out of memory (allocated 165675008) (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-21 14:10:43 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 217440256) (tried to allocate 46152272 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 12:28:35 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 219549696) (tried to allocate 46167536 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 12:44:10 [error X 3][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 219553792) (tried to allocate 46169440 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 12:53:29 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php::183] Out of memory (allocated 125829120) (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 13:22:00 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/widget-base.php::183] Out of memory (allocated 73400320) (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-25 08:54:50 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 221671424) (tried to allocate 46192496 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-08 07:18:44 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::620] Out of memory (allocated 71303168) (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-09 13:22:32 [notice X 1][/bitnami/wordpress/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	HT Mega - Absolute Addons for Elementor Page Builder: Compatibility not specified
	Royal Elementor Addons: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @BlaquePrinc3ss,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
