### ISSUE TITLE
✅ 🚀 Feature Request: Offset in products and archive products widget query

### ISSUE THREAD

**Issue by khahina** [elementor/elementor#20342]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Need complexe design with images alone and products sections.
Need product section with offset .
Exemple :
first section , 3 products  
second section : 2 colonnes 1/ picture and 2/ 2 products (vertical align) (continuity of the 3 firsts)
third section : 4 products  (offset 3+2 from previous sections)
4th section : 2 colonnes 1/ 2 products (vertical align) (offset 3+2+4) 2/ 1 picture
...

### Describe the solution you'd like

offset or query id like post widget

### Describe alternatives you've considered

third tiers addons plugins (like jetengine) ... but i didnt link empiled plugins.

**Comment by nicholaszein** [comment]
Hello @khahina ,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

You can try to use the new [Loop Builder](https://elementor.com/blog/introducing-the-loop-builder/) to create your own Posts template and add your custom fields.

Learn more about the Loop Builder:

- [What is the Loop Grid?](https://elementor.com/help/loop-grid/)
- [How do I build a Loop Grid?](https://elementor.com/help/how-do-i-build-a-loop-grid/)
- [How do I customize the layout of a loop?](https://elementor.com/help/customize-layout-loop/)
- [Building a query with the loop grid](https://elementor.com/help/building-query-loop-grid/)
- [How do I paginate my loop?](https://elementor.com/help/paginate-loop/)
- [How do I build a loop from an existing template?](https://elementor.com/help/build-a-loop-existing-template/)

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by khahina** [comment]
loop did'nt allow offset ... it's not the same problem.
And in fact loop may be more usefull with offset possibility in posts elements

**Comment by nicholaszein** [comment]
Hello @khahina,

currently, you can't add multiple loops (multiple Archive Product widgets in your case) inside an archive template. This is a WordPress limitation, not Elementor's. You would need to customize the Query using custom code to apply the changes you're requesting, or simply use custom CSS with the Loop Grid.

We are working on a feature that might solve your issue using the Loop Grid, which can be used for any Post Type (especially WooCommerce) as an Archive template as well. You still shouldn't be adding multiple loops on archive templates. This can cause unwanted behaviors.

[Keep tuned](https://github.com/elementor/elementor/discussions/categories/announcement)! 😉 

Kind regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
