### ISSUE TITLE
🚀 Feature Request: Loop Builder/Map Integration (Location Management)

### ISSUE THREAD

**Issue by jhanten** [elementor/elementor#20343]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The loop builder is awesome and the recent addition of WooCommerce support is great, but what I really need is a way to tie loop data to a map like a Locations page you see for many stores and companies with many offices.

### Describe the solution you'd like

If Map markers could be generated as part of the loop building.  So the map is at the top of the page and the loop is under it showing detailed information.

### Describe alternatives you've considered

I can also solve this issue with plugins, but they don't generally like to play well with Elementor and caching. I currently am doing this on a site with the Toolset plugin, but I either am loading an Elementor page or a Toolset page and it creates basically two different websites.  The loop builder will help me further reduce my need for Toolset, but until I can get a map system working as well I am still stuck with a hybrid website instead of a truly Elementor one.

Just an idea.

**Comment by nicholaszein** [comment]
Hello @jhanten,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
