### ISSUE TITLE
🔗 🚀 Feature Request: Loop Grid Query - Provide a way to query Taxonomy Terms in addition to Post Types. (Duplicate of #20018)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20367]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

Now we can create loop for post and product and that's really nice. But it would be great if, in addition to these two, we could also create a loop for terms (category of post/product).
For example, in the jet engine plugin loop builder, it is possible to create loops for products, posts, and even custom post type.

### Describe the solution you'd like

![WooCommerce-Category-Slider-Pro](https://user-images.githubusercontent.com/88034902/201149207-105a9c1f-3556-4957-8aa6-6a5abec91fcf.png)

**Comment by dsolimini** [comment]
+1 to this. This would make it much easier for me to avoid additional plugins, custom code, and hacks.

**Comment by nicholaszein** [comment]
Hey @Michaelgimii,

thanks for submitting your request! 🙏 

I'm passing this along to the team for future versions! That's a great idea! 💪 

Best regards

**Comment by 79ho3ein** [comment]
+1 , This is really great.
Hi @nicholaszein , If you are adding this great feature, please consider the following three options for it.

1- Hide Subcategories option.
2- Hide Empty (Do not display empty categories)
3- A new dynamic tag to display the number of products in each category.

![download](https://user-images.githubusercontent.com/77163248/201309710-25bf97d3-3b9e-49a2-b952-cc77464ef8b8.png)

thank you

**Comment by dsolimini** [comment]
A few thoughts on features that make sense for this:

Flexibility to show:
- The just the top terms of a hierarchical taxonomy (ie, hide children)
- Ability to start at a particular place in a hierarchy. (ie, Choose a term and see its children.)
- Current Query. Ie, so that on an archive page you could show the relevant children of the current page.
- Hide/unhide empty terms

Same pagination/order/etc as the current grid loop.

Add a dynamic data fields for: 
- the number of items in a term
- Link to parent term

**Comment by nicholaszein** [comment]
Thanks for the suggestions @79ho3ein and @dsolimini!

This feature would be great, and I hope we can find a way to implement it in the future.

Kind regards

**Comment by black-eye** [comment]
+1

**Comment by nicholaszein** [comment]
Hi!

### 🔗 🚀 There is already a similar request submitted here #20018

Feel free to continue the conversation there! 👉. 

Kind regards,

Nick
