### ISSUE TITLE
✅ 🐞 Bug Report: Lottie Animation trigger options not working with Flexbox Containers - [ED-9468]

### ISSUE THREAD

**Issue by Applabprojects** [elementor/elementor#20360]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Since the current update from sections to containers, The lottie animation triggers do not work when column or section is selected.

### Steps to reproduce

How was this noticed:

1) uploaded Lottie as a json file.
2) Inserted the lottie in a container
3) In Settings, Trigger on hover selected
4) Option Hover area: selected on column and section
5) nothing Happens
6) On animation and viewport works ok.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-design2brand.com-10-11-2022.txt](https://github.com/elementor/elementor/files/9979627/system-info-design2brand.com-10-11-2022.txt)

**Comment by nicholaszein** [comment]
Hello @Applabprojects! 

Thank you for submitting your issue! 🙏 

I can reproduce your issue. Good catch! 💪 

I've labeled this issue so the team can take a look and fix the incompatibility.

Best regards

**Comment by nicholaszein** [comment]
Hello there @Applabprojects!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
