### ISSUE TITLE
✅ 📊 🚀 Feature Request: Lazy Load Background Images - Provide a way to disable lazy-loading of bg images on a per-control basis

### ISSUE THREAD

**Issue by fabigrafo** [elementor/elementor#20365]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

If you activate the experiment: "Lazy Load Background Images", the background images are automatically loaded lazy. This is useful and practical, but there are situations in which you sometimes do not want this. But now you have to deactivate the complete experiment.

It would make more sense if there were a switcher for this in the appropriate places, which is only visible when the experiment is active and is then also set to "on" by default. This can then be switched off manually at individual points.

I look forward to opinions and discussions.

### Describe the solution you'd like

Add a on / off switcher for the new experiment: "Lazy Load Background Images".

**Comment by fabianenzensperger** [comment]
#20328

**Comment by 79ho3ein** [comment]
+1

**Comment by nicholaszein** [comment]
Thank you for submitting your feature request @fabianenzensperger! 🙏 

Allow us to review your request. We will get back to you with feedback as soon as possible.

Best regards

**Comment by steveindzine** [comment]
+1

**Comment by nicholaszein** [comment]
Hi there,

### 📅  This request is scheduled to be Migrated to the new [Discussions](https://github.com/elementor/elementor/discussions/categories/feature-request) section.

Please do not duplicate this request.

Once we migrate it, we encourage you to cast your **⬆️ Upvote** on the first comment if you feel it should be considered for our roadmap.

**Comment by Salimoh** [comment]
Hi
what happened to this feature request? is it ongoing?

**Comment by jrstarenlard** [comment]
Hi, the backgrounds at the top are not loaded. It should be a priority to include this functionality and be able to exclude images, otherwise this featured is useless.

**Comment by nicholaszein** [comment]
Hey @everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.21.0! 🥳 

You can now add the `e-no-lazyload` CSS Class to the **parent container** of the elements you don't want to lazyload the background image, and they will be loaded normally with the rest of the page.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
