### ISSUE TITLE
⛔ 🚀 Feature Request: Loop Builder - Add CPT support.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20371]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

As you know, in version 3.9 we can create loop for posts and products. So it would be great if you add custom post type support to loop builder.

### Describe the solution you'd like

Custom post type support for loop builder.

**Comment by fabianenzensperger** [comment]
Loop Builder support Custom Post Types by default, but probably not officially yet. But it would definitely be nice if you could select it separately.

**Comment by Michaelgimii** [comment]
I created a post type using JetEngine plugin and also created metafields for that post type. But I failed to create a loop for it. So I think there is a need for an official compatibility for it. elementor please!

**Comment by avivu** [comment]
Hi @Michaelgimii,

Loop Builder supports custom post types created with JetEngine or CPT plugin and custom fields/metafields.
Any new CPT you are creating will appear under the post Query section.

For example:

1. I created in JetEngine CPT called "Cars"
<img width="487" alt="image" src="https://user-images.githubusercontent.com/76733085/201487498-154dbc35-243f-4e11-90d4-09470523e1b7.png">

 2. The new CPT appears under the Post Query section
<img width="296" alt="image" src="https://user-images.githubusercontent.com/76733085/201487579-b97566d4-98a9-460c-b0c7-57ca60091a47.png">

 3. And when creating a loop item template, you can also change the preview to the new "Cars" CPT.
<img width="299" alt="image" src="https://user-images.githubusercontent.com/76733085/201487646-eed02116-4c6f-41f1-b24f-3014d81aefca.png">

Thank you!

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have concluded that this feature already exists in the latest version of the Loop Builder experiment.

If you're not seeing the CPT in the **Source** list of the Loop Grid query, it might mean that your CPT is not publicly queriable. Check your CPT settings and make sure it is publicly queriable.

Best regards

**Comment by Michaelgimii** [comment]
thank you @avivu  , @nicholaszein

**Comment by ajien** [comment]
I'd like to reopen this issue. I was trying the Elementor Loop Builder and I can't see the custom post types created with Toolset Types in the query source.

**Comment by nicholaszein** [comment]
@ajien and @kulterryan,

this is not a bug. Make sure your CPT is **<ins>NOT</ins>** excluded from the search.

````php
$args = array(
    'exclude_from_search' => false,
````
