### ISSUE TITLE
⛔ 🐞 Bug Report: Container width changes from full to boxed randomly

### ISSUE THREAD

**Issue by tilmanfalke** [elementor/elementor#20370]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey, I've got the issue that containers keep changing their width setting randomly. 

**If've got**
A outer Container set to **boxed** that inner contains two containers. 
These two inner containers are set to **full width**.

**Changes that happen on their own**
The outer Container stays set to boxed.
But the inner Containers **change to boxed** 
This one of the inner containers to leave the canvas.

How can I stop the containers from switching to full width?  

### Steps to reproduce

1) create a container - set width to boxed
2) create to inner containers align horizontal
3) set inner containers to full width
4) wait over night?!

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.38
	PHP Version: 7.4.32
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://tilman-falke.de
	Home URL: https://tilman-falke.de
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 0
	Admin Email: info@tilmanfalke.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15

== Active Plugins ==
	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Antispam Bee
		Version: 2.11.1
		Author: pluginkollektiv

	Broken Link Checker
		Version: 1.11.16
		Author: WPMU DEV

	Cachify
		Version: 2.3.2
		Author: pluginkollektiv

	Custom Icons for Elementor
		Version: 0.3.1
		Author: Michael Bourne

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.10.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.1
		Author: Elementor.com

	IONOS Assistant
		Version: 8.4.0
		Author: IONOS

	Limit Login Attempts Reloaded
		Version: 2.25.3
		Author: Limit Login Attempts Reloaded

	OoohBoi Steroids for Elementor
		Version: 1.9.9
		Author: OoohBoi

	Real Cookie Banner (Free)
		Version: 3.4.0
		Author: devowl.io

	Really Simple SSL
		Version: 5.3.2
		Author: Really Simple Plugins

	Statify
		Version: 1.8.3
		Author: pluginkollektiv

	The Events Calendar
		Version: 5.16.2
		Author: The Events Calendar

	WPForms Lite
		Version: 1.7.5.1
		Author: WPForms

== Must-Use Plugins ==
	1&1 Product Subdomain
		Version: 1.1.0
		Author: 1&1

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Aktiv
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	Import Export Website Kit: Standardmäßig aktiviert
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Farbpalette: Standardmäßig aktiviert
	Bevorzugte Widgets: Standardmäßig aktiviert
	Admin Leiste: Standardmäßig aktiviert
	Lazy Load Background Images: Standardmäßig aktiviert
	Save as Default: Standardmäßig deaktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Aktiv

== Protokoll ==
	
PHP: showing 11 of 11PHP: 2022-09-19 11:38:06 [notice X 13][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-20 23:11:29 [notice X 224][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/base/controls-stack.php::1413] Undefined index: _ob_steroids_underlay_mask_size_mobile_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-20 23:21:03 [notice X 7][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/base/controls-stack.php::1413] Undefined index: _ob_videomasq_mask_size_mobile_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 09:38:04 [error X 5][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 20:25:45 [notice X 1][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/base/controls-stack.php::1413] Undefined index: _ob_harakiri_height_mobile_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 13:45:15 [notice X 974][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 13:56:57 [notice X 27][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 13:56:58 [notice X 71][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-24 13:56:58 [notice X 71][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/theme-builder/module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-24 13:56:58 [notice X 71][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/forms/module.php(74): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-24 13:56:58 [notice X 71][/homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Das Argument $control_id ist seit Version 3.5.0 veraltet! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /homepages/25/d887380752/htdocs/clickandbuilds/Webdesign/wp-content/plugins/elementor-pro/modules/forms/module.php(75): Elementor\Controls_Manager -> register_control()
',
)]

Log: showing 20 of 272022-10-04 09:52:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-04 09:52:56 [info] elementor::elementor_updater Started 
2022-10-04 09:52:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-04 09:52:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-04 09:52:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-04 09:52:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-24 13:43:58 [info] elementor::elementor_updater Started 
2022-10-24 13:43:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-24 13:43:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-24 13:43:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-28 07:18:40 [info] elementor::elementor_updater Started 
2022-10-28 07:18:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-28 07:18:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-28 07:18:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-28 07:18:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-11-09 09:36:29 [info] elementor::elementor_updater Started 
2022-11-09 09:36:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-09 09:36:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-09 09:36:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev4',
  'to' => '3.10.0-dev1',
)]
2022-11-09 09:36:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev4',
  'to' => '3.10.0-dev1',
)]

JS: showing 4 of 4JS: 2022-10-17 09:03:33 [error X 6][https://tilman-falke.de/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.0-dev2:2:2968] Can\'t find variable: elementor_new_template_form_controls 
JS: 2022-10-17 09:08:26 [error X 2][https://tilman-falke.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:1061492] null is not an object (evaluating \'$.getBoundingClientRect\') 
JS: 2022-10-17 09:37:21 [error X 5][https://tilman-falke.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.9.0-dev2:2:19453] undefined is not an object (evaluating \'e.offset().top\') 
JS: 2022-11-10 14:50:44 [error X 74][https://tilman-falke.de/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	Custom Icons for Elementor: Die Kompatibilität ist nicht angegeben
	Elementor Pro: Unkompatibel
	OoohBoi Steroids for Elementor: Unkompatibel

== Elementor Pro - Compatibility Tag ==
	
	OoohBoi Steroids for Elementor: Kompatibel

**Comment by nicholaszein** [comment]
Hello @tilmanfalke,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We can't reproduce your issue on an installation with only Elementor v3.8.1, Elementor Pro v3.8.1, and the Hello Elementor theme v2.6.1.
* It seems you might have a conflict with a 3rd party add-on, a performance optimization plugin, or a server-side cache.
* We see you're using the Elementor Developer Edition plugin, which is not recommended to be used on production websites. It should only be used in staging environments for testing purposes. The Elementor add-ons you're using are most likely not compatible with this version.

### ✅ What you can do to solve your issue:
- Deactivate the Elementor Developer Edition plugin, use Elementor v3.8.1 and Elementor Pro v3.8.1 (or the latest stable versions);
- Deactivate your performance optimization solutions and clear your cache;
- Deactivate server-side cache or cache for logged-in users;
- If the issue persists deactivate all plugins except Elementor and Elementor Pro and then re-activate plugin by plugin until the issue happens again. This way you'll know which plugin is causing your issue.


For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
