### ISSUE TITLE
⛔ 🚀 Feature Request: Allow Block Editor widgets inside Elementor

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20372]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Wordpress block editor has a few widgets that are nice that aren't usable in Elementor.

### Describe the solution you'd like

Tables and Embed File/PDF Blocks would be extremely useful in Elementor.

### Describe alternatives you've considered

I suppose I could solve this by creating a single post theme template and applying it the specific pages I'm wanting Elementor styling with wordpress blocks for simple pages.  But pages that I want custom layouts with Wordpress blocks wouldn't really work.

**Comment by nicholaszein** [comment]
Hello @cranstantinople,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. here's why:

The Block Editor (commonly known as Gutenberg) uses a different technology than Elementor and therefore is incompatible. Only classic widgets can be used inside Elementor. As for the other way around, you can use the [Elementor Block for Gutenberg ](https://wordpress.org/plugins/block-builder/)plugin to display your Elementor templates inside the Block Editor!

I hope this helps.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
