### ISSUE TITLE
⛔ 🔗 🐞 Bug Report: Accordion affects SEO negatively if Gallery is used. (Related to #2756)

### ISSUE THREAD

**Issue by luckyluke4444** [elementor/elementor#20395]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

the Elementor Pro support (Sara Stevic) told me to issue a bug report here:

I have prepared a FAQ page using the Elementor Accordion [here](https://knife-art.de/das-grosse-kochmesser-faq-worauf-du-achten-musst/).
This page was made to improve SEO of my website. However, right now this doesn't work as the Google Search Console gives the following issue: Incorrect structure: "," or "}" missing 

The Sara told me the following:
I've inspected this closer and concluded that the issue is related to the content that's added within the Accordion widget.
Please note that adding a gallery (via shortcode) can cause such issues, as there are certain scripts that need to be loaded and we have no control over that content, which is why you might get Parsing error.

I think it isn't uncommon to use pictures in the Accordion and I'm not even using shortcodes, just the normal editor. 

Is there a way to fix this?

### Steps to reproduce

Just click here:
https://search.google.com/test/rich-results?url=https%3A%2F%2Fknife-art.de%2Fdas-grosse-kochmesser-faq-worauf-du-achten-musst%2F

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: Ubuntu 18.04 v5.6.49-89.0
	PHP Version: 8.1.12
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://knife-art.de
	Home URL: https://knife-art.de
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 1
	Admin Email: lukas@knife-art.de
	Debug Mode: Active

== Theme ==
	Name: Neve
	Version: 3.4.4
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.57
		Author: Borlabs GmbH

	CleverworksForms
		Version: 20.04
		Author: Dipl. Inform. Thomas Schmitt

	Code Snippets
		Version: 3.2.1
		Author: Code Snippets Pro

	Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd
		Version: 6.15.6
		Author: SeedProd

	Doofinder for WooCommerce
		Version: 1.5.38
		Author: doofinder

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	F4 Total Stock Value for WooCommerce
		Version: 2.0.4
		Author: FAKTOR VIER

	Font Awesome
		Version: 4.3.1
		Author: Font Awesome

	Germanized for WooCommerce
		Version: 3.11.1
		Author: vendidero

	Germanized for WooCommerce Pro
		Version: 3.6.0
		Author: vendidero

	Goaffpro Affiliate Marketing
		Version: 2.7.4
		Author: Goaffpro

	GuidePlugin
		Version: 1.0.16
		Author: Sebastian Kraus

	JetMenu
		Version: 2.2.4
		Author: Crocoblock

	Joinchat
		Version: 4.5.11
		Author: Creame

	Limit Login Attempts Reloaded
		Version: 2.25.8
		Author: Limit Login Attempts Reloaded

	Matomo Analytics - Ethical Stats. Powerful Insights.
		Version: 4.12.0
		Author: Matomo

	OMGF
		Version: 5.4.2
		Author: Daan from Daan.dev

	One Stop Shop for WooCommerce
		Version: 1.3.2
		Author: vendidero

	Orbit Fox Companion
		Version: 2.10.20
		Author: Themeisle

	Post Duplicator
		Version: 2.28
		Author: Metaphor Creations

	Redirection
		Version: 5.3.5
		Author: John Godley

	Trustpilot-reviews
		Version: 2.5.914
		Author: Trustpilot

	vendidero Helper
		Version: 2.1.6
		Author: vendidero

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WooCommerce PayPal Payments
		Version: 1.9.5
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.0.1
		Author: WooCommerce

	WPA Product Gallery Slider for WooCommerce
		Version: 1.1
		Author: WPAddons

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	WP Menu Cart
		Version: 2.12.1
		Author: WP Overnight

	WP Rocket
		Version: 3.11.5
		Author: WP Media

	WP Show Posts
		Version: 1.1.3
		Author: Tom Usborne

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Elemente Verwendung ==
	
	header : 3
		jet-mega-menu : 2
		nav-menu : 2
		search-form : 1
		theme-site-logo : 3
		woocommerce-menu-cart : 2
		wp-widget-woocommerce_product_search : 1
	wp-post : 22
		button : 19
		content_form_contact : 1
		divider : 2
		gallery : 4
		heading : 72
		image : 63
		jet-custom-menu : 3
		obfx-services : 4
		shortcode : 19
		slides : 1
		spacer : 32
		testimonial-carousel : 1
		text-editor : 89
		video : 1
		wp-widget-woocommerce_product_search : 2
	wp-page : 19
		accordion : 1
		button : 3
		form : 1
		heading : 16
		html : 2
		image : 4
		image-carousel : 1
		shortcode : 1
		spacer : 11
		text-editor : 42

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Inaktiv
	Verbessertes Laden von Assets: Aktiv
	Verbessertes Laden von CSS: Standardmäßig deaktiviert
	Inline-Schriftarten-Symbole: Inaktiv
	Verbesserungen der Zugänglichkeit: Inaktiv
	Zusätzliche benutzerdefinierte Breakpoints: Inaktiv
	Import Export Website Kit: Inaktiv
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Inaktiv
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Inaktiv
	Default to New Theme Builder: Inaktiv
	Startseiten: Inaktiv
	Farbpalette: Inaktiv
	Bevorzugte Widgets: Inaktiv
	Admin Leiste: Inaktiv
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig deaktiviert
	Form Submissions: Inaktiv
	Scroll Snap: Inaktiv

== Protokoll ==
	
Log: showing 20 of 322022-10-04 11:08:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-04 11:08:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-04 11:08:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-31 07:18:51 [info] elementor::elementor_updater Started 
2022-10-31 07:18:51 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-31 07:18:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 07:18:52 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-31 07:18:52 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-31 07:18:52 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-31 07:18:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-02 08:23:34 [info] elementor-pro::elementor_pro_updater Started 
2022-11-02 08:23:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-02 08:23:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-02 08:23:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-02 08:23:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-14 07:25:17 [info] elementor::elementor_updater Started 
2022-11-14 07:25:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-14 07:25:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-14 07:25:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-14 07:25:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 8 of 8PHP: 2022-09-23 14:14:55 [notice X 2][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-19 11:50:04 [notice X 38453][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-19 12:00:25 [notice X 51][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::528] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-19 12:02:19 [notice X 212][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 15:00:16 [notice X 2][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-11-02 08:26:48 [notice X 11713][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-11-04 09:19:01 [notice X 1][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-04 09:19:03 [error X 1][/var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/vhosts/knife-art.de/httpdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/vhosts/knife-art.de/httpdocs/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/vhosts/knife-art.de/httpdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/vhosts/knife-art.de/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/vhosts/knife-art.de/httpdocs/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-10-12 18:35:22 [error X 9][https://knife-art.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767848] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-11-03 11:16:38 [error X 2][https://knife-art.de/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==

**Comment by luckyluke4444** [comment]
Alright. The problem wasn't the gallery, but the pictures that were inserted without gallery/shortcode. I added all pictures as a gallery now and this is working. However, if you need a sample to check it. I'm happy to setup a page for you!

**Comment by nicholaszein** [comment]
Related to #2756
