### ISSUE TITLE
⛔ 🚀 Feature Request: better ux for navigator

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20415]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In navigation, when we drag a layer to move to another part, this layer is dragged diagonally. This creates a very bad ux when using navigation and moving layers. 

### Describe the solution you'd like

When we drag a layer in navigator, don't move it diagonally. Rather, it better be displayed like this.

![navigator](https://user-images.githubusercontent.com/88034902/201951347-658c87f1-4839-4011-8d93-9cfdcff97b7b.png)

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
