### ISSUE TITLE
❌ Elementor editor has stopped displaying

### ISSUE THREAD

**Issue by tonybrian** [elementor/elementor#20423]
![elemento33](https://user-images.githubusercontent.com/12815396/202146593-da77ed74-aac2-4fed-bdbf-796a0be7e44f.png)
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello !
Since yesterday, Elementor is not displayed on my site anymore. It started to take a long time to open, then it was not responding at all... 

- I deactivated all the plugins of the site to diagnose the problem.
- I enabled Editor Loader Method in the Elementor settings.
- I tried to launch Elementor in safe mode.
- I switched to the default theme of wordpress.
- I downgraded and upgraded wordpress (same for elementor).

Everything I've seen on videos and forums has not worked for me (as always). Even those who have the exact same problem as me.

I solved all error messages appearing in the console except:

```
SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON

error | @ | web-cli.min.js?ver=3.8.1:3
  | catchApply | @ | web-cli.min.js?ver=3.8.1:3
  | (anonymous) | @ | web-cli.min.js?ver=3.8.1:3
  | Promise.catch (async) |   |  
  | _callee$ | @ | web-cli.min.js?ver=3.8.1:3
  | tryCatch | @ | web-cli.min.js?ver=3.8.1:3
  | (anonymous) | @ | web-cli.min.js?ver=3.8.1:3
  | (anonymous) | @ | web-cli.min.js?ver=3.8.1:3
  | asyncGeneratorStep | @ | web-cli.min.js?ver=3.8.1:3
  | _next | @ | web-cli.min.js?ver=3.8.1:3
  | (anonymous) | @ | web-cli.min.js?ver=3.8.1:3
  | (anonymous) | @ | web-cli.min.js?ver=3.8.1:3
  | applyRunAfterAsync | @ | web-cli.min.js?ver=3.8.1:3
  | applyRunAfter | @ | web-cli.min.js?ver=3.8.1:3
  | runInstance | @ | web-cli.min.js?ver=3.8.1:3
  | run | @ | web-cli.min.js?ver=3.8.1:3
  | run | @ | web-cli.min.js?ver=3.8.1:3
  | get | @ | web-cli.min.js?ver=3.8.1:3
  | onElementorInitComponents | @ | editor.min.js?ver=3.8.1:3
  | dispatch | @ | load-scripts.php?c=1…%5D=hooks&ver=6.1:2
  | y.handle | @ | load-scripts.php?c=1…%5D=hooks&ver=6.1:2
  | dispatch | @ | editor.min.js?ver=3.8.1:3
  | initComponents | @ | editor.min.js?ver=3.8.1:3
  | onStart | @ | editor.min.js?ver=3.8.1:3
  | onStart | @ | editor.min.js?ver=3.8.1:3
  | (anonymous) | @ | backbone.marionette.….js?ver=2.4.5.e1:24
  | f.triggerMethod | @ | backbone.marionette.….js?ver=2.4.5.e1:24
  | start | @ | backbone.marionette.….js?ver=2.4.5.e1:25
  | (anonymous) | @ | editor.min.js?ver=3.8.1:3
  | (anonymous) | @ | editor.min.js?ver=3.8.1:3
  | (anonymous) | @ | editor.min.js?ver=3.8.1:3
```
If someone could enlighten me on the origin of this problem, I would be very grateful !

![elementor11](https://user-images.githubusercontent.com/12815396/202142361-7698d45f-28de-4f87-a330-815446e94717.png)
![elementor22](https://user-images.githubusercontent.com/12815396/202142401-f3867eb8-6fee-4d3c-8fdb-af88e705b8d7.png)

Cordially, Brian

### Steps to reproduce

This problem appeared out of nowhere, with no real steps to follow...

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.28
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 250000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://dipongo.co
	Home URL: https://dipongo.co
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 0
	Admin Email: equipage@dipongo.co
	Debug Mode: Active

== Theme ==
	Name: Shoptimizer
	Version: 2.6.2
	Author: CommerceGurus
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 OPR/92.0.0.0

== Active Plugins ==
	ActiveCampaign
		Version: 8.1.10
		Author: ActiveCampaign

	ActiveCampaign for WooCommerce
		Version: 1.9.2
		Author: ActiveCampaign

	Advanced Custom Fields
		Version: 6.0.4
		Author: WP Engine

	Checkout Field Editor for WooCommerce
		Version: 1.8.0
		Author: ThemeHigh

	CommerceGurus Commercekit
		Version: 2.1.1
		Author: CommerceGurus

	Customize My Account for WooCommerce
		Version: 1.1.7
		Author: SysBasics

	Direct Checkout for WooCommerce
		Version: 2.7.2
		Author: QuadLayers

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.4
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.4.2
		Author: WPDeveloper

	Everest Forms
		Version: 1.9.5
		Author: WPEverest

	Facebook for WooCommerce
		Version: 2.6.30
		Author: Facebook

	Hotjar
		Version: 1.0.14
		Author: Hotjar

	JWT Auth
		Version: 2.1.0
		Author: Useful Team

	Kirki Customizer Framework
		Version: 4.0.24
		Author: David Vongries

	ManageWP - Worker
		Version: 4.9.15
		Author: GoDaddy

	MonsterInsights - eCommerce Addon
		Version: 8.3.8
		Author: MonsterInsights Team

	MonsterInsights Pro
		Version: 8.10.1
		Author: MonsterInsights

	Piotnet Addons For Elementor
		Version: 2.4.20
		Author: Piotnet

	PixelYourSite
		Version: 9.2.1
		Author: PixelYourSite

	Premium Addons for Elementor
		Version: 4.9.36
		Author: Leap13

	Stratum - Elementor Widgets
		Version: 1.3.13
		Author: MotoPress

	Stripe Connexion - Pilot'in
		Version: 0.1
		Author: Pilot'in

	Unlimited Elements for Elementor
		Version: 1.5.38
		Author: Unlimited Elements

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WooCommerce Payments
		Version: 5.0.3
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 6.8.0
		Author: WooCommerce

	WooLentor - WooCommerce Elementor Addons + Builder
		Version: 2.4.8
		Author: HasThemes

	WP Delete User Accounts
		Version: 1.2.3
		Author: Ren Ventura

	WP Fastest Cache
		Version: 1.0.7
		Author: Emre Vona

	WPForms Lite
		Version: 1.7.8
		Author: WPForms

	YellowPencil Pro
		Version: 7.5.6
		Author: WaspThemes

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

	WP Password bcrypt
		Version: 1.1.0
		Author: Roots

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Inactif
	Optimisation du chargement du CSS: Actif
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Import Export Website Kit: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Transitions des pages: Inactif
	Notes: Actif par défaut
	Boucle: Inactif par défaut
	Envois de formulaire: Actif par défaut
	Accroche de défilement: Actif par défaut

== Journal ==
	
JS: showing 11 of 11JS: 2022-09-07 11:47:57 [error X 1][https://dipongo.co/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.2:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `brand_link` value. Expected array or object.',
)]
JS: 2022-09-07 14:10:20 [error X 54][https://dipongo.co/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.2:3:766783] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-10-01 15:04:38 [error X 3][https://dipongo.co/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] el.querySelector is not a function 
JS: 2022-10-04 01:44:13 [error X 1][https://dipongo.co/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.8:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `gridimage_btnlink` value. Expected array or object.',
)]
JS: 2022-10-04 13:53:59 [error X 6][https://dipongo.co/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:909298] Cannot read properties of undefined (reading \'view\') 
JS: 2022-10-12 05:59:39 [error X 9][https://dipongo.co/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.7.8:2:4807] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-10-22 17:20:13 [error X 2][https://dipongo.co/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:294654] Cannot read properties of undefined (reading \'html\') 
JS: 2022-10-27 13:38:59 [error X 26][https://dipongo.co/wp-content/plugins/premium-addons-for-elementor/assets/frontend/min-js/premium-addons.min.js?ver=4.9.34:1:32055] times.every is not a function 
JS: 2022-11-03 10:12:24 [error X 14][https://dipongo.co/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,regenerator-runtime,wp-polyfill,jquery-ui-core,jquery-ui-mouse,wp-api-request,wp-&loadchunk_1=hooks&ver=6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-09 11:03:09 [error X 2][https://dipongo.co/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.7.8:2:51471] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 
JS: 2022-11-15 16:27:16 [error X 2][https://dipongo.co/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.8.1:2:4105] Cannot read properties of null (reading \'history\') 

Log: showing 20 of 222022-09-23 10:01:17 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-23 10:01:17 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-23 10:01:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-02 16:49:02 [info] elementor::elementor_updater Started 
2022-10-02 16:49:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-02 16:49:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-02 16:49:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-02 16:49:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-11-15 15:25:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.1',
)]
2022-11-15 15:25:44 [info] elementor::elementor_updater Started 
2022-11-15 15:25:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-15 15:25:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-15 15:25:46 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-15 15:25:46 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-15 15:25:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.1',
)]
2022-11-15 15:38:05 [info] elementor-pro::elementor_pro_updater Started 
2022-11-15 15:38:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-15 15:38:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-15 15:38:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.1',
)]
2022-11-15 15:38:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.1',
)]

PHP: showing 10 of 10PHP: 2022-10-01 18:51:41 [notice X 7][/home/dipongo/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-01 19:59:54 [notice X 167][/home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-01 20:00:54 [notice X 33][/home/dipongo/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-02 12:26:01 [notice X 2][/home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php::69] Undefined index: requires [array (
  'trace' => '
#0: /home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php(69): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php(130): ElementorPro\License\Updater -> check_transient_data()
#2: /home/dipongo/public_html/wp-includes/class-wp-hook.php(309): ElementorPro\License\Updater -> check_update()
#3: /home/dipongo/public_html/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
#4: /home/dipongo/public_html/wp-includes/option.php(1992): class type apply_filters()
',
)]
PHP: 2022-10-02 12:26:01 [notice X 2][/home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: /home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php(84): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/dipongo/public_html/wp-content/plugins/elementor-pro/license/updater.php(130): ElementorPro\License\Updater -> check_transient_data()
#2: /home/dipongo/public_html/wp-includes/class-wp-hook.php(309): ElementorPro\License\Updater -> check_update()
#3: /home/dipongo/public_html/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
#4: /home/dipongo/public_html/wp-includes/option.php(1992): class type apply_filters()
',
)]
PHP: 2022-10-10 13:25:39 [notice X 1][/home/dipongo/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/activecampaign-handler.php::133] Undefined index: textarea [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-17 12:52:30 [notice X 10][/home/dipongo/public_html/wp-content/plugins/elementor-pro/license/admin.php::303] Undefined index: license [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-15 14:01:46 [warning X 47][/home/dipongo/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at /home/dipongo/public_html/wp-content/themes/shoptimizer/functions.php:1) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-15 15:25:46 [error X 1][/home/dipongo/public_html/wp-content/plugins/elementor/core/app/modules/kit-library/data/kits/controller.php::58] Uncaught Error: Class 'Elementor\Core\App\Modules\KitLibrary\Data\Kits\Endpoints\Download_Link' not found in /home/dipongo/public_html/wp-content/plugins/elementor/core/app/modules/kit-library/data/kits/controller.php:58
Stack trace:
#0 /home/dipongo/public_html/wp-content/plugins/elementor/data/v2/base/controller.php(410): Elementor\Core\App\Modules\KitLibrary\Data\Kits\Controller->register_endpoints()
#1 /home/dipongo/public_html/wp-content/plugins/elementor/data/v2/base/controller.php(462): Elementor\Data\V2\Base\Controller->register()
#2 /home/dipongo/public_html/wp-includes/class-wp-hook.php(308): Elementor\Data\V2\Base\Controller->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Server))
#3 /home/dipongo/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /home/dipongo/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/dipongo/public_html/wp-includes/rest-api.php(577): do_action('rest_api_init', Object(WP_REST_Server))
#6 /home/dipongo/public_ht [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-16 04:08:49 [error X 1][/home/dipongo/public_html/wp-content/plugins/elementor/app/modules/kit-library/data/kits/controller.php::58] Uncaught Error: Class 'Elementor\App\Modules\KitLibrary\Data\Kits\Endpoints\Download_Link' not found in /home/dipongo/public_html/wp-content/plugins/elementor/app/modules/kit-library/data/kits/controller.php:58
Stack trace:
#0 /home/dipongo/public_html/wp-content/plugins/elementor/data/v2/base/controller.php(410): Elementor\App\Modules\KitLibrary\Data\Kits\Controller->register_endpoints()
#1 /home/dipongo/public_html/wp-content/plugins/elementor/data/v2/base/controller.php(462): Elementor\Data\V2\Base\Controller->register()
#2 /home/dipongo/public_html/wp-includes/class-wp-hook.php(308): Elementor\Data\V2\Base\Controller->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Server))
#3 /home/dipongo/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /home/dipongo/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/dipongo/public_html/wp-includes/rest-api.php(577): do_action('rest_api_init', Object(WP_REST_Server))
#6 /home/dipongo/public_html/wp-includes/ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibilité non spécifiée
	Elementor Pro: Compatibilité non spécifiée
	Essential Addons for Elementor: Compatibilité non spécifiée
	Piotnet Addons For Elementor: Compatibilité non spécifiée
	Premium Addons for Elementor: Compatibilité non spécifiée
	Stratum - Elementor Widgets: Compatibilité non spécifiée
	Unlimited Elements for Elementor: Compatibilité non spécifiée
	WooLentor - WooCommerce Elementor Addons + Builder: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @tonybrian,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
