### ISSUE TITLE
[🧐 Evaluating] Loop widget doesn't apply custom CSS in the front end

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#20438]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm applying some custom CSS to the loop widget.

In the back end, those custom CSS rules work, but in the front end those custom css rules don't show up.

### Steps to reproduce

1) Create a page with Elementor
2) Add a Loop widget
3) Apply custom CSS. For example:
`selector .e-loop-item {
    background-color: red !important;
}` 
4) Save and see how it looks in the front end.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.39
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.4
		Author: WP Engine

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Duplicator
		Version: 1.5.1
		Author: Snap Creek

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Post Type Switcher
		Version: 3.2.1
		Author: Triple J Software, Inc.

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Inactive
	Admin Top Bar: Active by default
	Page Transitions: Active
	Notes: Active by default
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Inactive

**Comment by nicholaszein** [comment]
Hello @vgstef! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by hein-obox** [comment]
Hi @vgstef,

Has this issue been solved in the latest updates?

**Comment by vgstef** [comment]
Yes, it works now. Thanks.
