### ISSUE TITLE
✅ 🐞 Bug Report: Lazy loading is not working in the Call to Action (CTA) Widget - [ED-9121]

### ISSUE THREAD

**Issue by Kishorchandth** [elementor/elementor#20437]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The background image is **inline** with style="background-image: url()" because of this lazy loading 

`<div class="elementor-cta__bg elementor-bg" style="background-image: url(https://beta.local/wp-content/uploads/2022/11/advocacy@2x-jpg.webp);"></div>`

### Steps to reproduce

No step is required because it happens on the CTA widget image.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://beta.local
	Home URL: https://beta.local
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: @gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.0-beta2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-beta2
		Author: Elementor.com

	Performance Lab
		Version: 1.6.0
		Author: WordPress Performance Team

== Elements Usage ==
	
	archive : 1
		button : 1
		heading : 3
		posts : 1
		text-editor : 1
	footer : 1
		form : 1
		heading : 5
		icon-list : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	header : 1
		image : 1
		nav-menu : 1
	page : 1
		button : 2
		heading : 23
		spacer : 5
	popup : 1
		form : 1
		heading : 1
		text-editor : 1
	wp-page : 5
		button : 6
		call-to-action : 12
		divider : 13
		form : 1
		google_maps : 1
		heading : 46
		image : 1
		image-carousel : 1
		media-carousel : 1
		posts : 1
		spacer : 8
		testimonial-carousel : 1
		text-editor : 32
	single-post : 1
		button : 1
		heading : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		button : 1
		heading : 2

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Inactive
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 202022-11-11 05:51:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.9.0-beta1',
)]
2022-11-11 05:51:37 [info] elementor::elementor_updater Started 
2022-11-11 05:51:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-11 05:51:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-11 05:51:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.9.0-beta1',
)]
2022-11-11 06:10:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.9.0-beta1',
)]
2022-11-11 06:10:02 [info] elementor-pro::elementor_pro_updater Started 
2022-11-11 06:10:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-11 06:10:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-11 06:10:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.9.0-beta1',
)]
2022-11-17 06:25:33 [info] elementor::elementor_updater Started 
2022-11-17 06:25:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-17 06:25:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta1',
  'to' => '3.9.0-beta2',
)]
2022-11-17 06:25:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-17 06:25:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta1',
  'to' => '3.9.0-beta2',
)]
2022-11-17 06:26:07 [info] elementor-pro::elementor_pro_updater Started 
2022-11-17 06:26:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-17 06:26:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-17 06:26:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta1',
  'to' => '3.9.0-beta2',
)]
2022-11-17 06:26:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta1',
  'to' => '3.9.0-beta2',
)]

PHP: showing 3 of 3PHP: 2022-11-11 05:55:48 [notice X 2][C:\laragon\www\beta\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-11 05:58:27 [notice X 24][C:\laragon\www\beta\wp-content\plugins\elementor\includes\managers\image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-17 06:48:46 [notice X 2][C:\laragon\www\beta\wp-content\plugins\elementor\app\modules\import-export\module.php::563] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Thank you for submitting this issue as well @Kishorchandth! 🙏 

We are aware of this and are investigating it. 🧐 

Best regards

**Comment by Ricarditu** [comment]
I have the same issue but happening with popup background. After disabling lazyload, it loads the background normally.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
