### ISSUE TITLE
✔️ 🚀 Feature Request: Add Responsive controls to Advanced > Transform effects

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20439]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

In version 3.9, you added container support to the transform attribute. This was a really great feature. But it would be great if you add support for responsive mode to transform. This is what will complete the transform. I hope you will work on this. It is really important.

### Describe the solution you'd like

Responsive control for transform :

![transform](https://user-images.githubusercontent.com/88034902/202422759-4c9d5b79-8800-459a-a8ac-1e81b1139854.jpg)

**Comment by 79ho3ein** [comment]
I think this is not a reasonable request. We can have full responsive control in transform right now. I think the screenshot below will fulfill your request.

![a](https://user-images.githubusercontent.com/77163248/202432972-e1e5af62-a1c2-41be-abc1-1d065637d443.png)

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

This feature is already present within each Transform control. You're just looking at the wrong place as @79ho3ein promptly pointed out above!

To learn more about this feature check [this article](https://elementor.com/help/css-transform/).

Cheers 🥂
