### ISSUE TITLE
[⌛ Awaiting Feedback] Elementor Forms Returns Incorrect Error on Webhook Response Code 200

### ISSUE THREAD

**Issue by colinmacleod** [elementor/elementor#20452]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is an issue with the Elementor Forms Webhook Response. It appears to time out and give the error code:

> An error occurred.
> Webhook Webhook Error
> This Message is not visible for site visitors.

This error is coming from wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php.

To make this clear, I created a vanilla install of Elementor and Elementor Pro on WordPress with no other plugins or external code:

https://formtest.happybunnies.com/

You can confirm that the backend URL is returning response code 200 by running curl - see this short video:

https://www.loom.com/share/30a3d95b6f914b149cbffcfde52e7491

`curl -i -X POST -H 'Content-Type: application/json' -d '{"First Name":"Bunny","Last Name":"Tester","Email":"test@happybunnies.com","Childs Age":"4 months","How Did They Hear About Us?":"Other (Please Specify)","Other:":"test","Requested Start Date":"test35","Days per Week":"test3","Contact Id":"kem43DCUH3GjF6TkruEb","Tour Result":"Signed Up (Won)","form_id":"be98e48","form_name":"tour-result-form"}' https://n8n.happybunnies.com/webhook/af8ac420-db14-4f62-9831-8f546e24ccba`

I have tried raising this issue with Elementor support, but they refused to look at it as they say they do not support external code of any kind. However, as you can see from the vanilla install above, **there is no external code involved**.

### Steps to reproduce

1. Go to https://formtest.happybunnies.com/
2. Press Submit

**Expected Outcome**

1. Form is successful
2. Backend process executes successfully (returns 200)
3. There is no error shown to the site visitor, and a success message is shown

**Actual Outcome**

1. Form is not successful
2. Backend process executes successfully (returns 200)
3. An error is shown to the site visitor: "Webhook Webhook Error. This Message is not visible for site visitors."

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/Vv0zBLe1

**Comment by nicholaszein** [comment]
Hello @colinmacleod! 

Thank you for submitting your issue! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party code.

However, let's verify your issue further. First of all, make sure we support the webhook your using by checking our documentation:

1. [Actions After Submit (see the Webhook section)](https://elementor.com/help/actions-after-submit/);
2. [Forms API](https://developers.elementor.com/docs/hooks/forms/)

If the webhook you're using does not follow any of the documents above, the issue most likely is related to your webhook code. In this case, we would need to see the entirety of the code, and you will need to provide us with a more detailed steps to reproduce (how you've configured your form, so we can reproduce it on our own environment).

Best regards

**Comment by colinmacleod** [comment]
I can confirm the webhook follows the guidlelines. There is no custom code. It uses the webhook implementation by merely pasting the url into the form as recommended.

**Comment by colinmacleod** [comment]
To allow you to confirm, I would be happy to give you admin access to the test site. This has already been provided using the temporary credentials feature of element or.com.

**Comment by colinmacleod** [comment]
**Update:** It looks like **Cyrus**,
Elementor “**Tier 2 Technical Customer Experience Specialist**,” has solved this issue.

By default, the timeout is set to only 5 seconds. This can be increased by using a webhook. For example, if you are using make.com as the webhook, you can specify:

```
add_filter('http_request_timeout', function($timeout, $url = '') {
    $start_with = 'https://hook.us1.make.com';
    
    //return is_string($url) && str_starts_with($url, $start_with) // PHP 8
    return is_string($url) && strncmp($url, $start_with, strlen($start_with)) === 0 // PHP 7 or older
        ? 30 // TODO: set appropriate timeout, WordPress default is 5 seconds
        : $timeout; // return unchanged url for other requests
}, 10, 2);
```

**Comment by colinmacleod** [comment]
Note - I removed the webhook URL from the curl command above. I will also shutdown the test server now that the issue is resolved.
