### ISSUE TITLE
[🧐 Evaluating] 🐞 Bug Report: Scroll Snap Experiment causes horizontal layout shift on mobile devices

### ISSUE THREAD

**Issue by MB8862** [elementor/elementor#20460]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I noticed a bug happening with the Snappy Scroll feature.
When entering a website from Android mobile on a Chrome browser,
either the website loads and then goes blank,
or the entire website jumps to the right.

Screenshot attached:
![Screenshot_20221117-115203_Chrome](https://user-images.githubusercontent.com/47423526/202900896-bcc6acd0-9abb-4677-8f3f-badb4366fc9b.jpg)

*I have contacted Elementor support in the proper channel, and I was told that although the snappy scroll is a stable feature since it is in the experiments, there's no guarantee this issue will be fixed anytime soon.

### Steps to reproduce

1. turn on the snappy scroll feature.
2. enable it on the website settings
3. open the website in Chrome on an Android mobile

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://ronilitvak.co.il
	Home URL: https://ronilitvak.co.il
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 768M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: michal@michalneimer.co.il
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.2.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	HappyFiles Pro
		Version: 1.7
		Author: Codeer

	Maspik - Spam blacklist
		Version: 0.7.8
		Author: yonifre

	Premium Addons for Elementor
		Version: 4.9.38
		Author: Leap13

	Premium Addons PRO
		Version: 2.8.14
		Author: Leap13

	Rank Math SEO
		Version: 1.0.102
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.24
		Author: Rank Math

	ShortPixel Image Optimizer
		Version: 5.1.3
		Author: ShortPixel

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

== שימוש באלמנטים ==
	
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 2
		heading : 5
		text-editor : 5
	section : 17
		divider : 1
		heading : 18
		icon-list : 1
		image : 5
		menu-anchor : 9
		spacer : 6
		text-editor : 11
	widget : 0
		form : 1
	wp-page : 2
		call-to-action : 2
		divider : 15
		form : 2
		heading : 31
		icon : 4
		icon-list : 1
		image : 30
		jet-scroll-navigation : 1
		menu-anchor : 12
		premium-addon-button : 3
		spacer : 7
		testimonial-carousel : 2
		text-editor : 15

== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: לא פעיל כברירת מחדל
	טעינת נכסים משופרת: לא פעיל כברירת מחדל
	טעינת CSS משופרת: לא פעיל כברירת מחדל
	Inline Font Icons: לא פעיל כברירת מחדל
	שיפורי נגישות: לא פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל כברירת מחדל
	ייבא קיט אתר אינטרנט: פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	פלקסבוקס קונטיינר: לא פעיל כברירת מחדל
	ברירת מחדל לממשק החדש של בונה התבנית: פעיל כברירת מחדל
	עיצוב כותרת עליונה ותחתונה: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	סרגל אדמין עליון: פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	Notes: פעיל כברירת מחדל
	נגן בלולאה: לא פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	קפיצת גלילה: לא פעיל

== יומן שינויים ==
	
Log: showing 20 of 272022-11-03 10:23:25 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-11-03 10:23:25 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-11-03 10:23:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-03 10:23:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-04 10:31:29 [info] elementor::elementor_updater Started 
2022-11-04 10:31:29 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-11-04 10:31:29 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-11-04 10:31:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-04 10:31:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-14 17:28:14 [info] elementor::elementor_updater Started 
2022-11-14 17:28:14 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-11-14 17:28:14 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-11-14 17:28:14 [info] אלמנטור/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-14 17:28:14 [info] אלמנטור/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-14 17:28:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-16 17:39:14 [info] elementor-pro::elementor_pro_updater Started 
2022-11-16 17:39:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-16 17:39:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-16 17:39:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-16 17:39:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

JS: showing 9 of 9JS: 2022-10-19 14:12:14 [error X 5][https://roni.michalneimer.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060992] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-03 08:26:24 [error X 13][https://roni.michalneimer.co.il/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils&ver=6.1:2:31703] elementor_new_template_form_controls is not defined 
JS: 2022-11-03 09:24:12 [error X 68][https://roni.michalneimer.co.il/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-06 09:05:59 [error X 1][https://roni.michalneimer.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:694254] T.getContainer is not a function 
JS: 2022-11-08 15:46:33 [error X 1][https://roni.michalneimer.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view32971\") has already been destroyed and cannot be used. 
JS: 2022-11-08 16:35:47 [error X 1][https://roni.michalneimer.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view61117\") has already been destroyed and cannot be used. 
JS: 2022-11-08 16:35:47 [error X 1][https://roni.michalneimer.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view61153\") has already been destroyed and cannot be used. 
JS: 2022-11-09 12:57:06 [error X 21][https://roni.michalneimer.co.il/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.8.0:2:51471] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 
JS: 2022-11-16 14:54:06 [error X 695][https://ronilitvak.co.il/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.10.3:2:15469] Cannot read properties of null (reading \'data\') 

PHP: showing 6 of 6PHP: 2022-11-04 12:22:38 [notice X 2][/home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/includes/widgets/menu-anchor.php::156] Undefined index: anchor [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-08 16:03:08 [notice X 389][/home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] הארגומנט $control_id הוצא משימוש מאז גרסה 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-08 16:03:44 [notice X 11][/home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] הארגומנט $control_id הוצא משימוש מאז גרסה 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/jet-tabs/includes/modules/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-11-08 16:03:44 [notice X 11][/home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] הארגומנט $control_id הוצא משימוש מאז גרסה 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/jet-tabs/includes/modules/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-11-10 12:02:06 [notice X 1][/home/customer/www/roni.michalneimer.co.il/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-16 17:14:29 [notice X 4][/home/customer/www/ronilitvak.co.il/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: לא תואם
	Premium Addons for Elementor: תואם
	Premium Addons PRO: תואם

== אלמנטור פרו - Compatibility Tag ==
	
	Premium Addons for Elementor: תואם
	Premium Addons PRO: תואם

**Comment by nicholaszein** [comment]
Hello @MB8862,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We cannot reproduce the issue reported. The scroll snap feature works as expected in our tests using only the latest versions of Elementor (v3.8.1) and Elementor Pro (v3.8.1) active with the latest version of the Hello Elementor theme (v2.6.1).
* It seems you might have a conflict with a 3rd party add-on (Premium Add-ons).

### ✅ What you can do to solve your issue:

* Check for the use of absolute positioning of elements, or negative margins, usually these are the ones responsible for causing your issue.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
