### ISSUE TITLE
❌ 🐞 Bug Report: My layout isn't loading like it should + not showing everything on public view

### ISSUE THREAD

**Issue by Picturemy** [elementor/elementor#20476]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I made my page but keep having problems with the font of the text and when public view some things don't show up.... Or show up differently like the background color. When i'm in elementor and look with eye everything seems fine but when publishing not.

### Steps to reproduce

I don't know.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 8.0.25
	PHP Memory Limit: 256M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://picturemy.be
	Home URL: https://picturemy.be
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: nl-BE
	Timezone: 0
	Admin Email: info@picturemy.be
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_BE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.10.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Essential Addons for Elementor
		Version: 5.4.2
		Author: WPDeveloper

	Essential Blocks
		Version: 3.8.0
		Author: WPDeveloper

	Smash Balloon Instagram Feed
		Version: 6.1
		Author: Smash Balloon

	WPForms Lite
		Version: 1.7.8
		Author: WPForms

== Must-Use Plugins ==
	Ensure admin user isn't deleted
		Version: 1.0
		Author: 

	WP CLI Login Command Server
		Version: 1.3
		Author: Evan Mattson

== Elementen gebruik ==
	
	page : 4
		divider : 1
		eael-filterable-gallery : 1
		heading : 5
		icon-list : 1
		image : 1
		navigation-menu : 1
		site-logo : 2
		social-icons : 2
		spacer : 1
		text-editor : 1
		wp-widget-instagram-feed-widget : 1
	wp-post : 0
		heading : 1
		navigation-menu : 1
		site-logo : 2
		social-icons : 1
		text-editor : 2
		wp-widget-instagram-feed-widget : 1
	wp-page : 5
		button : 1
		heading : 6
		image : 9
		spacer : 8
		text-editor : 5

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard actief
	Inline lettertype iconen: Standaard inactief
	Toegang verbeteringen: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	Import export website kit: Standaard actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Standaard actief
	Hello Theme Header & Footer: Standaard actief
	Landingspagina's: Actief
	Kleur sampler: Actief
	Favoriete widgets: Actief
	Beheerder bovenste balk: Actief
	Lazy Load Background Images: Standaard actief
	Save as Default: Standaard inactief

== Log ==
	
Log: showing 17 of 172022-11-14 05:53:02 [info] elementor::elementor_updater Started 
2022-11-14 05:53:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-14 05:53:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-14 05:53:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-14 05:53:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-15 18:38:56 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2022-11-15 18:38:56 [info] elementor::custom_task_manger Started 
2022-11-15 18:38:56 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2022-11-15 18:38:56 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2022-11-15 18:38:56 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2022-11-15 18:38:56 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2022-11-15 18:38:56 [info] elementor::custom_task_manger Completed 
2022-11-21 20:19:39 [info] elementor::elementor_updater Started 
2022-11-21 20:19:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-21 20:19:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-21 20:19:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-21 20:19:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]

JS: showing 3 of 3JS: 2022-11-14 19:35:36 [error X 7][https://picturemy.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:883015] Cannot read properties of undefined (reading \'route\') 
JS: 2022-11-15 18:45:08 [error X 1][https://picturemy.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-16 19:45:36 [error X 8][https://picturemy.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:694254] T.getContainer is not a function 

PHP: showing 3 of 3PHP: 2022-11-15 18:46:53 [error X 1][/data/sites/web/picturemybe/www/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /data/sites/web/picturemybe/www/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /data/sites/web/picturemybe/www/wp-includes/class-wp-hook.php(308): Elementor\Modules\CompatibilityTag\Base_Module->Elementor\Modules\CompatibilityTag\{closure}()
#5 /data/sites/web/picturemybe/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 /data/sites/web/picturemybe/www/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action()
#8 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /data/sites/web/picturemybe/www/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data()
#11 /data/sites/web/picturemybe/www/wp-includes/class-wp-hook.php(308): Elementor\Tracker::send_tracking_data()
#12 /data/sites/web/picturemybe/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#13 /data/sites/web/picturemybe/www/wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /data/sites/web/picturemybe/www/wp-cron.php(188): do_action_ref_array()
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-15 19:13:03 [warning X 33][/data/sites/web/picturemybe/www/wp-content/plugins/elementor/includes/template-library/sources/local.php::1031] Attempt to read property "post_type" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 20:19:39 [notice X 1][/data/sites/web/picturemybe/www/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Niet compatibel
	Essential Addons for Elementor: Niet compatibel

**Comment by nicholaszein** [comment]
Hello @Picturemy,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Avoid using the **Elementor Developer Edition (Beta)** plugin on a production website. This plugin is meant to be used by developers to test new Elementor features **ONLY ON A STAGING ENVIRONMENT**.
* Make sure your performance optimization solutions like **server cache** are not affecting the rendering of your pages. Contact your hosting provider and ask them to provide a way to clear or disable the server cache.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
