### ISSUE TITLE
⛔ 🐞 Bug Report: Video widget doesn't work for Vimeo live-streams

### ISSUE THREAD

**Issue by liveweltDigital** [elementor/elementor#20471]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello all,
as soon as you use the Elementor video widget to embed a Vimeo livestream, Elementor removes the URL parameter "/event/". Since the video ID is not consistent on Vimeo, a video from completely different user is displayed.

Original link:
https://vimeo.com/event/#VideoID#/cc1973913d

The link rendered by Elementor:
https://vimeo.com/#VideoID#/

The video widget, must not remove the parameter "event" (if it is set).

### Steps to reproduce

1. Place the video widget on any Elementor page
2. Paste the URL to the Vimeo event (https://vimeo.com/event/#VideoID#/cc1973913d)
3. Save and open the preview or live-page
4. Click Play, now the video https://vimeo.com/#VideoID# appears (without "/event/") 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '38', Revision '3692a61' v5.7.35-38
	PHP Version: 7.4.30
	PHP Max Input Vars: 1500
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://hp-zbook.de
	Home URL: https://hp-zbook.de
	WP Multisite: Yes
	Max Upload Size: 256 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: no-reply@hp-zbook.de
	Debug Mode: Active

== Theme ==
	Name: Hello_Livewelt
	Version: 1.0
	Author: livewelt digital
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Colorlib Login Customizer
		Version: 1.3.1
		Author: Colorlib

	Elementor GFUnsubscribe Extension
		Version: 1.0.0
		Author: Chris Güthues

	Event
		Version: 0.5.5
		Author: Jan Beerbom & Chris Güthues

	Folio ContentWrapper for Elementor
		Version: 1.0.0
		Author: Chris Güthues

	LwD Restricted Area
		Version: 1.0.1
		Author: Chris

	User Role Editor
		Version: 4.63.1
		Author: Vladimir Garagulya

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

== Network Plugins ==
	Add From Server
		Version: 3.4.5
		Author: Dion Hulse

	Advanced Custom Fields
		Version: 6.0.5
		Author: WP Engine

	Autoren
		Version: 0.1
		Author: Chris Güthues | cgu

	Bulk Media Register
		Version: 1.26
		Author: Katsushi Kawamori

	Check & Log Email
		Version: 1.0.6
		Author: WPChill

	Child Theme Generator
		Version: 2.2.7
		Author: Serafino Corriero

	Download Box for Elementor
		Version: 1.0.0
		Author: Livewelt digital GmbH & Co. KG

	Elementor
		Version: 3.5.4
		Author: Elementor.com

	Elementor Ansprechpartner Extension
		Version: 1.0.0
		Author: Jan Beerbom

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com

	Elementor Sidebar Extension
		Version: 1.0.0
		Author: Chris Güthues

	Email Templates
		Version: 1.3.2.1
		Author: Damian Logghe

	Google XML Sitemaps
		Version: 4.1.5
		Author: Auctollo

	Gravity Forms
		Version: 2.6.8
		Author: Gravity Forms

	Gravity Forms Double Opt In Add-On
		Version: 2.5.7
		Author: Albert Brueckmann

	Hero-Extension for Elementor
		Version: 1.0.0
		Author: Chris Güthues

	Hyphenator
		Version: 5.1.5
		Author: Benedict B., Maciej Gryniuk

	Image Accordion Widget for Elementor
		Version: 1.0.0
		Author: Chris Güthues

	MultiSite Clone Duplicator
		Version: 1.5.3
		Author: Julien OGER, Pierre DARGHAM, David DAUGREILH, GLOBALIS media systems

	Nested Pages
		Version: 3.2.3
		Author: Kyle Phillips

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

	Simple Elementor for Clients
		Version: 1.2.0
		Author: Chris Güthues

	TranslatePress - Multilingual
		Version: 2.4.1
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	Visibility Logic for Elementor
		Version: 2.3.2
		Author: StaxWP

== Elements Usage ==
	
	page : 35
		alert : 1
		button : 120
		countdown : 1
		counter : 76
		divider : 8
		elementor-contentwrapper-extension : 1
		elementor-images-accordion-extension : 8
		elementor-sidebar-extension : 11
		flip-box : 3
		heading : 345
		icon : 2
		icon-list : 100
		image : 200
		image-box : 57
		image-carousel : 11
		networking-chat : 1
		profile-widget : 1
		register-widget : 1
		slides : 9
		spacer : 14
		systemcheck-widget : 2
		text-editor : 162
		theme-page-title : 3
		video : 16
		wp-widget-gform_widget : 3
	popup : 22
		heading : 20
		icon-list : 2
		image : 12
		image-box : 2
		login : 1
		text-editor : 10
		wp-widget-gform_widget : 9
	section : 11
		button : 7
		divider : 1
		elementor-images-accordion-extension : 1
		heading : 17
		icon-list : 2
		image : 10
		image-box : 3
		login : 1
		spacer : 4
		text-editor : 6
		video : 2
	widget : 0
		flip-box : 3
		heading : 9
		icon-list : 88
		image-box : 1
		slides : 1
		text-editor : 8
	wp-page : 96
		alert : 1
		button : 49
		cgu-download-box : 8
		countdown : 1
		counter : -154
		divider : 11
		elementor-gfunsubscribe-extension : 1
		elementor-images-accordion-extension : 1
		elementor-sidebar-extension : 1
		heading : -57
		html : 14
		icon : 1
		icon-list : 56
		image : -29
		image-box : 15
		image-carousel : -21
		login : 8
		networking-chat : 1
		profile-widget : 1
		register-widget : 1
		slides : 7
		spacer : -13
		systemcheck-widget : 1
		text-editor : 72
		theme-page-title : 1
		video : 8

== Elementor Experiments ==
	Optimierte DOM Ausgabe: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive by default

== Log ==
	
Log: showing 20 of 252022-01-20 13:00:34 [info] elementor::elementor_updater Started 
2022-01-20 13:00:34 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-20 13:00:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.3',
)]
2022-01-20 13:00:36 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-20 13:00:36 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-01-20 13:00:36 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-01-20 13:00:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.3',
)]
2022-01-20 13:16:08 [info] elementor-pro::elementor_pro_updater Started 
2022-01-20 13:16:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-01-20 13:16:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-01-20 13:16:08 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-01-20 13:16:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.2',
)]
2022-01-20 13:16:12 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-01-20 13:16:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.1',
  'to' => '3.5.2',
)]
2022-01-26 12:50:19 [info] elementor::elementor_updater Started 
2022-01-26 12:50:19 [info] Elementor/Upgrades - _on_each_version Start  
2022-01-26 12:50:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-01-26 12:50:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-01-26 12:50:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-01-26 12:50:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]

PHP: showing 4 of 4PHP: 2022-01-20 12:19:16 [error X 2][/html/wordpress/wp-content/plugins/elementor-pro/modules/screenshots/module.php::206] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /html/wordpress/wp-content/plugins/elementor-pro/modules/screenshots/module.php:206
Stack trace:
#0 /html/wordpress/wp-content/plugins/elementor-pro/modules/screenshots/module.php(226): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode(Array)
#1 /html/wordpress/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /html/wordpress/wp-content/plugins/elementor-pro/core/modules-manager.php(69): Elementor\Core\Base\Module::instance()
#3 /html/wordpress/wp-content/plugins/elementor-pro/plugin.php(312): ElementorPro\Core\Modules_Manager->__construct()
#4 /html/wordpress/wp-includes/class-wp-hook.php(303): ElementorPro\Plugin->on_elementor_init('')
#5 /html/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#6 /html/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#7 /html/wordpress/wp-content/plugins/elementor/includes/plugin.php(682): do_ac [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-20 14:12:35 [notice X 147][/html/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-08 15:40:04 [error X 1][/html/wordpress/wp-content/plugins/elementor-pro/modules/popup/module.php::98] Uncaught Error: Call to undefined method Elementor\Core\Kits\Documents\Kit::save_display_settings_data() in /html/wordpress/wp-content/plugins/elementor-pro/modules/popup/module.php:98
Stack trace:
#0 [internal function]: ElementorPro\Modules\Popup\Module->save_display_settings(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /html/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /html/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /html/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /html/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /html/wordpress/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 12:07:54 [error X 2][/html/wordpress/wp-content/plugins/elementor/core/documents-manager.php::493] Uncaught Error: Call to a member function is_built_with_elementor() on bool in /html/wordpress/wp-content/plugins/elementor/core/documents-manager.php:493
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /html/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /html/wordpress/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /html/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /html/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /html/wordpress/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 14 of 14JS: 2022-03-15 08:45:29 [error X 4][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.4:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `background_image` value. Expected array or object.',
)]
JS: 2022-06-24 13:35:59 [error X 3][https://hp-zbook.de/wp-content/plugins/elementor-pro/assets/js/gallery.6af8f19f91f1b16c3ab6.bundle.min.js:2:5563] Cannot read properties of undefined (reading \'setSettings\') 
JS: 2022-06-27 08:45:01 [error X 1][https://hp-zbook.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view9217\") has already been destroyed and cannot be used. 
JS: 2022-06-27 12:48:50 [error X 21][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-10-10 14:21:22 [error X 1][https://hp-zbook.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view33057\") has already been destroyed and cannot be used. 
JS: 2022-10-10 15:29:55 [error X 21][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:332595] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2022-10-14 09:00:16 [error X 543][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.4:2:12166] this.parent.children.splice is not a function 
JS: 2022-10-14 09:18:06 [error X 2][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:314999] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-10-14 09:54:00 [error X 5][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:348732] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-10-14 09:54:07 [error X 5][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.4:2:5069] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-10-26 13:30:39 [error X 1][https://hp-zbook.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1589\") has already been destroyed and cannot be used. 
JS: 2022-11-16 17:15:25 [error X 2][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.4:2:18381] Cannot read properties of undefined (reading \'top\') 
JS: 2022-11-17 08:57:20 [error X 1][https://hp-zbook.de/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-18 16:07:32 [error X 1][https://hp-zbook.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:450306] Cannot read properties of undefined (reading \'$el\') 

== Elementor - Compatibility Tag ==
	
	Elementor GFUnsubscribe Extension: Compatibility not specified
	Folio ContentWrapper for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @liveweltDigital,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This feature is not supported by Elementor at this moment.

### ✅ What you can do to solve your issue:
* If you wish this to be added as a feature, feel free to submit a new [🚀 Feature Request](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
