### ISSUE TITLE
⛔ 🐞 Bug Report: hoock action_woocommerce_shop_loop_item_title not working in related product widget

### ISSUE THREAD

**Issue by tonnick** [elementor/elementor#20499]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello !
I am trying to change product title heading in product related loop. I need to change it from h2 to h4. I added some code to function.php which is working. but building the page with elementor widget, the code is not working anymore. Seems that elementor is bypassing the woocommerce hoocks. here is the code :

````php
function action_woocommerce_shop_loop_item_title()
{
global $woocommerce_loop;
// Only for related products
if (isset($woocommerce_loop['name']) && $woocommerce_loop['name'] === 'related') {
// Removes a function from a specified action hook.
remove_action('woocommerce_shop_loop_item_title', 'woocommerce_template_loop_product_title', 10);
echo '<h4 class="' . esc_attr(apply_filters('woocommerce_product_loop_title_classes', 'woocommerce-loop-product__title')) . '">' . get_the_title() . '</h4>';
}
}
add_action('woocommerce_shop_loop_item_title', 'action_woocommerce_shop_loop_item_title', 9);
````

anybody has any idea with this code is not working with elementor related product widget ?! thx !

### Steps to reproduce

1. using elementor template for product single
2. add widget related product
3. add code in function.php
4. and this is not working :) 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: Debian 10 v10.3.36
	PHP Version: 8.0.25
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://lovemysexdoll.fr
	Home URL: https://lovemysexdoll.fr
	WP Multisite: No
	Max Upload Size: 100 Mo
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Blocksy Child
	Version: 
	Author: Creative Themes
	Child Theme: Yes
	Parent Theme Name: Blocksy
	Parent Theme Version: 1.8.58
	Parent Theme Author: CreativeThemes

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.4
		Author: WP Engine

	Advanced Order Export For WooCommerce
		Version: 3.3.3
		Author: AlgolPlus

	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	BEAR – Bulk Editor and Products Manager Professional for WooCommerce
		Version: 2.0.9
		Author: realmag777

	Blocksy Companion (Premium)
		Version: 1.8.58
		Author: CreativeThemes

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	CookieYes | GDPR Cookie Consent
		Version: 3.0.5
		Author: CookieYes

	Cost & Reports for WooCommerce
		Version: 3.0.3
		Author: Consortia

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	DynamicTags
		Version: 1.2.1
		Author: RTO GmbH

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.0.1
		Author: Facebook

	Flexible Shipping
		Version: 4.16.2
		Author: Octolize

	Flexible Shipping PRO
		Version: 2.13.0
		Author: Octolize

	Happy Elementor Addons
		Version: 3.7.1
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 2.6.1
		Author: weDevs

	Hide Categories and Products for Woocommerce
		Version: 1.2.5
		Author: N.O.U.S. Open Useful and Simple

	iThemes Security Pro
		Version: 7.1.0
		Author: iThemes

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	Log cleaner for iThemes Security
		Version: 1.3.5
		Author: Michael Ott

	MainWP Child
		Version: 4.3
		Author: MainWP

	MainWP Child Reports
		Version: 2.0.8
		Author: MainWP

	Ovri Banking
		Version: 1.5.3
		Author: OVRI SAS

	Premium Addons for Elementor
		Version: 4.9.38
		Author: Leap13

	Premium Addons PRO
		Version: 2.8.14
		Author: Leap13

	Rank Math SEO
		Version: 1.0.102
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.24
		Author: Rank Math

	reSmush.it Image Optimizer
		Version: 0.4.11
		Author: reSmush.it

	Shipping Packages
		Version: 1.3.0
		Author: Octolize

	ShopiMind
		Version: 1.2.0
		Author: ShopiMind

	Site Kit by Google
		Version: 1.87.0
		Author: Google

	Tawk.to Live Chat
		Version: 0.7.2
		Author: Tawkto

	TawkTo Manager
		Version: 2.2.2
		Author: Daniel Mulder

	Temporary Login Without Password
		Version: 1.8.0
		Author: StoreApps

	UpdraftPlus - Backup/Restore
		Version: 2.22.23.1
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	Woocommerce - Guaranteed Reviews Company
		Version: 1.2.5
		Author: Guaranteed Reviews Company

	WooCommerce - Store Exporter
		Version: 2.7.1
		Author: Visser Labs

	Woocommerce Custom Product Addons
		Version: 4.1.8
		Author: Acowebs

	WooCommerce Google Analytics Integration
		Version: 1.5.17
		Author: WooCommerce

	WooCommerce Order Status Manager
		Version: 1.13.2
		Author: SkyVerge

	WooCommerce PayPal Payments
		Version: 1.9.5
		Author: WooCommerce

	WooCommerce PDF Invoices
		Version: 4.14.4
		Author: Andrew Benbow

	WooCommerce Shipping & Tax
		Version: 2.0.0
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.0.1
		Author: WooCommerce

	WOOF - WooCommerce Products Filter
		Version: 3.3.0
		Author: realmag777

	Woo Product Category Discount
		Version: 4.4
		Author: WooExtend

	WP Media Folders
		Version: 1.1.8
		Author: WP Hi-Tech

	WP Rocket
		Version: 3.12.2.1
		Author: WP Media

	WP Rollback
		Version: 1.7.2
		Author: GiveWP.com

	WP Sheet Editor - CMB2
		Version: 1.0.0
		Author: WP Sheet Editor

	WP Sheet Editor - Post Types (Premium)
		Version: 2.24.21
		Author: WP Sheet Editor

	YITH WooCommerce Order & Shipment Tracking Premium
		Version: 2.8.1
		Author: YITH

	YITH WooCommerce Wishlist
		Version: 3.15.0
		Author: YITH

== Utilisation des éléments ==
	
	popup : 1
		button : 2
		heading : 1
		image : 1
		text-editor : 1
	page : 1
		heading : 1
		image : 1
	product : 1
		ha-off-canvas : 1
		heading : 1
		post-navigation : 1
		premium-icon-list : 9
		tabs : 1
		video : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 2
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
		yith_wcwl_add_to_wishlist : 1
	section : 24
		button : 4
		shortcode : 16
		text-editor : 16
		woocommerce-product-add-to-cart : 1
		woocommerce-products : 4
		wp-widget-woof_widget : 1
	wp-post : 3
		text-editor : 2
	wp-page : 10
		button : 2
		divider : 4
		form : 3
		google_maps : 1
		ha-logo-grid : 1
		ha-product-category-carousel-new : 1
		ha-product-grid-new : 1
		heading : 25
		icon : 8
		icon-list : 1
		premium-addon-dual-header : 2
		premium-addon-tabs : 1
		premium-divider : 3
		table-of-contents : 2
		text-editor : 13
		theme-site-logo : 1
	product-archive : 2
		ha-off-canvas : 2
		icon-box : 4
		premium-unfold-addon : 2
		theme-archive-title : 2
		wc-archive-products : 2
		wp-widget-woocommerce_recently_viewed_products : 2
		wp-widget-woof_widget : 2

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Import Export Website Kit: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Inactif
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Boucle: Inactif par défaut
	Envois de formulaire: Actif par défaut
	Accroche de défilement: Actif par défaut

== Journal ==
	
Log: showing 20 of 382022-11-03 20:01:06 [info] elementor-pro::elementor_pro_updater Started 
2022-11-03 20:01:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-03 20:01:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-03 20:01:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-03 20:01:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-03 20:01:07 [info] elementor::elementor_updater Started 
2022-11-03 20:01:07 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-03 20:01:08 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-03 20:01:08 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-03 20:01:09 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-03 20:01:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-18 09:44:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-18 09:44:24 [info] elementor::elementor_updater Started 
2022-11-18 09:44:24 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-18 09:44:24 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-18 09:44:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-18 12:39:34 [info] elementor-pro::elementor_pro_updater Started 
2022-11-18 12:39:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-18 12:39:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-18 12:39:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 3 of 3PHP: 2022-09-25 18:49:51 [notice X 22][/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-20 20:41:07 [warning X 21][/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key "referrer" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-14 09:06:36 [warning X 1][/wp-content/plugins/elementor/includes/widgets/video.php::1200] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-11-14 08:40:05 [error X 57][https://lovemysexdoll.fr/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.8.0:2:15625] Cannot read properties of undefined (reading \'global\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Non compatible
	Happy Elementor Addons: Non compatible
	Happy Elementor Addons Pro: Non compatible
	Premium Addons for Elementor: Compatible
	Premium Addons PRO: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Happy Elementor Addons: Non compatible
	Happy Elementor Addons Pro: Non compatible
	Premium Addons for Elementor: Compatible
	Premium Addons PRO: Compatible

**Comment by tonnick** [comment]
hello Nicholas
unfortunalty, this is not working fine. this is removing the title from any other loop ! this means on shop or product cat archive page, the title is removed.

So, yes this is a bug.
The code I provided is working fine on a woocommerce standard product page. problem is that when we build product page with elementor, the code provided is not working anymore.

Code is using standard woocommerce hoock. Elementor should be able to work them. in other words, without elementor > code is working fine. using elementor widget, code is not working anymore.

So, would you mind to help to find an acceptable solution to make elementor compatible with woocommerce hoocks and ctions ?
thx for your help !

**Comment by nicholaszein** [comment]
Sorry @tonnick,

I just realized I gave you the wrong snippet. Please give me a few minutes to share the correct one!

**Comment by nicholaszein** [comment]
And to clarify, Elementor IS using the standard WooCommerce hooks with the `wc_get_template( 'single-product/related.php', $args );` function.

**Comment by tonnick** [comment]
I understand that elementor is using the woocommerce template, 
But as said, for some strange reason, my code, which is quite basic and using woocommerce standard hooks, is working fine with a standard woocommerce page.
Why is it not working anymore building the page with elementor ?
I do not mind to use another code, but I'm wondering why some standard hooks are not working with elementor only.

**Comment by nicholaszein** [comment]
We need to use a different method for this specific case. I'm making some tests to ensure the snippet is correct. Sorry about the confusion!

**Comment by tonnick** [comment]
Hello Nicholas
Following your first code, I modified it a bit like this ;

```
add_action('woocommerce_shop_loop_item_title', 'action_woocommerce_single_product_loop_item_title', 9);
function action_woocommerce_single_product_loop_item_title()	{
	// Set the HTML tag you want to use
	// Make sure you're on the product page
	if (is_product()) {
    remove_action('woocommerce_shop_loop_item_title', 'woocommerce_template_loop_product_title', 10);
    echo '<h4 class="' . esc_attr(apply_filters('woocommerce_product_loop_title_classes', 'woocommerce-loop-product__title')) . '">' . get_the_title() . '</h4>';
	}
}
```
seems to be ok now. thx fo your help !
