### ISSUE TITLE
⛔ 🚀 Feature Request: After saving and previewing in frontend, show a "Generating Styles" loading animation (because it's slow)

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#20504]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

When having a larger and more heavy landing page, after saving it (flushing styles), and then refreshing the page in the frontend (basically re-generating the styles), the page takes quite some time to generate (like 25s).

### Describe the solution you'd like

I believe a solution is to display a "generating styles" animation or message overlay. 

This makes it clear that it's not always this slow, only when generating the styles (which of course makes sense to be slower), but clearly interpreted by the user (not assuming it's always slow).

**Comment by nicholaszein** [comment]
Hello @hogash,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
