### ISSUE TITLE
⛔ 🚀 Feature Request: Default color for shape dividers

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20525]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

There is a very simple request for the shape divider that I don't think would be too much trouble to add...
When we add a shape divider, it is not displayed because it has no color by default!
So if you add a default color to the shape dividers, that would be great. 

### Describe the solution you'd like

Add a default color to shape dividers.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

(Ref: #19368, #9887, #2729)
