### ISSUE TITLE
🔗 🚀 Feature Request: Global setting for Transition Duration (Merged with #965)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20520]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

I think it would be great if you could add an option to globally set the **Transition Duration** in the **site settings**. Just like the **default padding** feature that now exists for containers in site settings.

It would also be great if we could have more control over it in the Transition Duration fields. It would also be great if we could have more control over it in the Transition Duration fields.

**For example, we can type in these fields :** transform 0.3s ease-in

If I'm not mistaken, this is similar to[ this request](https://github.com/elementor/elementor/issues/2219). Hopefully it will be released in 3.10 along with it. thanks

### Describe the solution you'd like

Option in site settings to globally set Transition Duration.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

Thank you for your submission! 🙏 

### 🔃 Merging this issue with #965.

Which is on the same subject. 

Feel free to continue the conversation there. 😉 

Best regards,

Nick
