### ISSUE TITLE
❌ 🐞 Bug Report: I'm not able to access Global Widgets with Developer version of Elementor Pro

### ISSUE THREAD

**Issue by udzrbarik** [elementor/elementor#20531]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm basically not able, to access global widgets for Elementor Pro (with a valid licence), I'm guessing it is Developer's version. It lets me create a global widget, but not use it.. Tells me: 

**Meet Our Global Widget**
With this feature, you can save a widget as global, then add it to multiple areas. All areas will be editable from one single place.

Even tho, I have an active Pro Licence :)

### Steps to reproduce

Install latest developer version of Elementor Pro

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.32
	PHP Memory Limit: 15M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 13M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 12 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: rob.hostak@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Elementor
		Version: 3.10.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-dev1
		Author: Elementor.com

	WP Fastest Cache
		Version: 1.0.8
		Author: Emre Vona

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Lazy Load Background Images: Active by default
	Save as Default: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 2 of 2PHP: 2022-10-24 20:22:45 [notice X 1][/var/www/html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 20:28:15 [notice X 4][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 222022-10-24 21:58:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-24 21:58:41 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-24 21:58:41 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-24 21:58:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.9.0-dev3',
)]
2022-10-24 21:58:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.9.0-dev3',
)]
2022-10-24 22:00:24 [info] elementor-pro::elementor_pro_updater Started 
2022-10-24 22:00:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-24 22:00:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-24 22:00:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev4',
)]
2022-10-24 22:00:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev4',
)]
2022-11-21 19:42:29 [info] elementor::elementor_updater Started 
2022-11-21 19:42:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-21 19:42:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-21 19:42:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.10.0-dev1',
)]
2022-11-21 19:42:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.10.0-dev1',
)]
2022-11-21 19:45:10 [info] elementor-pro::elementor_pro_updater Started 
2022-11-21 19:45:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-21 19:45:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-21 19:45:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.10.0-dev1',
)]
2022-11-21 19:45:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.10.0-dev1',
)]

JS: showing 5 of 5JS: 2022-11-21 19:43:19 [error X 2][http://localhost/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.10.0-dev1:2:30964] elementor.settings.page is undefined 
JS: 2022-11-21 20:11:39 [error X 1][http://localhost/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.10.0-dev1:2:32848] elementorFrontendConfig is not defined 
JS: 2022-11-21 20:55:10 [error X 1][http://localhost/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-21 21:32:22 [error X 6][http://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-dev1:3:776987] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-11-25 20:04:01 [error X 2][http://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-dev1:3:776444] T.originalEvent.key is undefined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @udzrbarik,

Thanks for reporting this bug! 🙏 

⛔ Although this is valuable information, please note that the Elementor Developer Edition (Beta) is meant to be used by developers who want to test new bleeding-edge Elementor features for compatibility purposes (with their themes or plugins).

⚠️ This plugin **SHOULD NOT BE USED ON A LIVE WEBSITE**. It's meant to be used on <ins>**STAGING WEBSITES ONLY**</ins>. This is an unstable version and may have some bugs. We don't provide support for this plugin.

Please <ins>**uninstall the Elementor Developer Edition (Beta) plugin**</ins> and use only the latest stable version of Elementor and Elementor Pro, which in this case are **v3.8.2** and **v3.8.2** respectively.

Best regards
