### ISSUE TITLE
⛔ 🐞 Bug Report: Error with Elementor and Learndash Deprecated: Function _register_controls is deprecated since version 3.1.0!

### ISSUE THREAD

**Issue by rwallacej** [elementor/elementor#20533]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

**https://biblelessons.online**

following error occurs with the LearnDash Course Grid 
Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/customer/www/biblelessons.online/public_html/wp-includes/functions.php on line 5383

Deprecated
: Function bp_core_get_avatar_data_url_filter is
deprecated
since version 1.5.2 with no alternative available. in
/home/customer/www/biblelessons.online/public_html/wp-includes/functions.php
on line
5393

Completed

Elementor	Version 3.8.1
Elementor Pro	Version 3.8.2

LearnDash LMS
Deactivate
LearnDash LMS Plugin - Turn your WordPress site into a learning management system.

Version 4.4.0.1 | By LearnDash | Visit plugin site | Changelog
Select LearnDash LMS - Achievements	
LearnDash LMS - Achievements
Deactivate
Award badges and points to users for the successful completion of LearnDash and WordPress activities.

Version 1.1.1 | By LearnDash | Visit plugin site
Select LearnDash LMS - Certificate Builder	
LearnDash LMS - Certificate Builder
Deactivate
LearnDash certificate builder allows you build certificates for your courses using the Gutenberg WordPress block editor

Version 1.0.3 | By LearnDash
Select LearnDash LMS - Course Grid	
LearnDash LMS - Course Grid
Deactivate
Build LearnDash course grid easily.

Version 2.0.7 | By LearnDash | Visit plugin site
Select LearnDash LMS - Elementor	
LearnDash LMS - Elementor
Deactivate
LearnDash LMS add-on to add Elementor widgets and templates.

Version 1.0.3 | By LearnDash | Visit plugin site
Select LearnDash LMS - Notifications	
LearnDash LMS - Notifications
Deactivate
Create and send notification emails to the users.

Version 1.5.4 | By LearnDash | Visit plugin site
Select LearnDash LMS - ProPanel	
LearnDash LMS - ProPanel
Deactivate
Easily manage and view your LearnDash LMS activity.

Version 2.1.4.1 | By LearnDash | Visit plugin site

### Steps to reproduce

load www.biblelessons.online
add Learndash Course Grid to elementor

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://biblelessons.online
	Home URL: https://biblelessons.online
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: 0
	Admin Email: rwallacej@aol.com
	Debug Mode: Active

== Theme ==
	Name: Astra
	Version: 3.9.4
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 4.5.5
		Author: AdminColumns.com

	Anti-Spam by CleanTalk
		Version: 5.189.1
		Author: СleanTalk <welcome@cleantalk.org>

	Astra Pro
		Version: 3.9.3
		Author: Brainstorm Force

	BuddyBoss Platform
		Version: 2.1.7.1
		Author: BuddyBoss

	BuddyBoss Products Updater
		Version: 1.2.8
		Author: BuddyBoss

	CookieYes | GDPR Cookie Consent
		Version: 3.0.5
		Author: CookieYes

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	GamiPress
		Version: 2.4.7
		Author: GamiPress

	GamiPress - LearnDash integration
		Version: 1.3.3
		Author: GamiPress

	Google Analytics for WordPress by MonsterInsights
		Version: 8.10.1
		Author: MonsterInsights

	Hide Admin Bar
		Version: 0.4.7
		Author: Shelby DeNike

	Imagify
		Version: 2.0
		Author: Imagify - Optimize Images & Convert WebP

	LearnDash Licensing &amp; Management
		Version: 1.1.4
		Author: LearnDash

	LearnDash LMS
		Version: 4.4.0.1
		Author: LearnDash

	LearnDash LMS - Achievements
		Version: 1.1.1
		Author: LearnDash

	LearnDash LMS - Certificate Builder
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - Course Grid
		Version: 2.0.7
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - Notifications
		Version: 1.5.4
		Author: LearnDash

	LearnDash LMS - ProPanel
		Version: 2.1.4.1
		Author: LearnDash

	Meta pixel for WordPress
		Version: 3.0.8
		Author: Facebook

	SiteGround Optimizer
		Version: 7.2.6
		Author: SiteGround

	Starter Templates
		Version: 3.1.18
		Author: Brainstorm Force

	Ultimate Member
		Version: 2.5.1
		Author: Ultimate Member

	Ultimate Member - Social Login
		Version: 2.3.14
		Author: Ultimate Member

	Uncanny Toolkit for LearnDash
		Version: 3.6.4.1
		Author: Uncanny Owl

	When Last Login
		Version: 1.2.1
		Author: Yoohoo Plugins

	WP 2FA - Two-factor authentication for WordPress
		Version: 2.3.0
		Author: WP White Security

	WP AutoTerms
		Version: 2.5.0
		Author: WP AutoTerms

	WPForms Lite
		Version: 1.7.8
		Author: WPForms

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.5
		Author: Team Yoast

== Must-Use Plugins ==
	BuddyBoss API Caching
		Version: 1.0.1
		Author: BuddyBoss

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

== Elementor Experiments ==
	Optimised DOM Output: Inactive by default
	Improved asset loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing pages: Active by default
	Colour Sampler: Active by default
	Favourite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 382022-08-17 18:35:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.8',
)]
2022-08-24 19:26:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.3',
)]
2022-08-24 19:26:07 [info] elementor-pro::elementor_pro_updater Started 
2022-08-24 19:26:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-24 19:26:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-24 19:26:07 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-08-24 19:26:07 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-08-24 19:26:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.3',
)]
2022-11-26 08:44:58 [info] elementor::elementor_updater Started 
2022-11-26 08:44:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-26 08:44:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-26 08:44:58 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-26 08:44:58 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-26 08:44:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.8.1',
)]
2022-11-26 08:44:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.8.1',
)]
2022-11-26 11:36:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.2',
)]
2022-11-26 11:36:15 [info] elementor-pro::elementor_pro_updater Started 
2022-11-26 11:36:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-26 11:36:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-26 11:36:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.8.2',
)]

PHP: showing 5 of 5PHP: 2022-04-18 19:32:46 [notice X 24][/home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php::405] Trying to get property &#039;post_type&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(405): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(116): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> add_meta_publish_options()
#2: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> ElementorPro\Modules\CustomCode\{closure}()
#3: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
#4: /home/customer/www/biblelessons.online/public_html/wp-includes/plugin.php(474): WP_Hook -> do_action()
',
)]
PHP: 2022-05-28 10:09:26 [notice X 1][/home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php::414] Trying to get property &#039;post_type&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(414): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(116): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> add_meta_publish_options()
#2: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> ElementorPro\Modules\CustomCode\{closure}()
#3: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
#4: /home/customer/www/biblelessons.online/public_html/wp-includes/plugin.php(474): WP_Hook -> do_action()
',
)]
PHP: 2022-07-07 14:01:14 [notice X 205][/home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php::414] Trying to get property &#039;post_type&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(414): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(116): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> add_meta_publish_options()
#2: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> ElementorPro\Modules\CustomCode\{closure}()
#3: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(331): WP_Hook -> apply_filters()
#4: /home/customer/www/biblelessons.online/public_html/wp-includes/plugin.php(476): WP_Hook -> do_action()
',
)]
PHP: 2022-11-09 20:30:18 [notice X 47][/home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php::414] Trying to get property &#039;post_type&#039; of non-object [array (
  'trace' => '
#0: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(414): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor-pro/modules/custom-code/custom-code-metabox.php(116): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> add_meta_publish_options()
#2: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCode\Custom_Code_Metabox -> ElementorPro\Modules\CustomCode\{closure}()
#3: /home/customer/www/biblelessons.online/public_html/wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4: /home/customer/www/biblelessons.online/public_html/wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2022-11-21 20:20:57 [notice X 1][/home/customer/www/biblelessons.online/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Elementor Pro: Compatibility not specified
	LearnDash LMS - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @rwallacej,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* It seems the LearnDash integration with Elementor is using a very old deprecated method (it was deprecated on 2021-01-24.
* It's the responsibility of the 3rd party developer to keep his integration up to date with the current [supported methods documented on our API](https://developers.elementor.com/docs/controls/add-new-control/).

### ✅ What you can do to solve your issue:
* Make sure you're using the latest version of both Elementor, Elementor Pro, and especially the <ins>**LearnDash LMS - Elementor add-on**</ins>.
* If you're using the latest version and are still viewing this error, **<ins>contact the LearnDash support**</ins> and reference this issue!

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by rami-elementor** [comment]
Hi @rwallacej 

See [Elementor deprecation](https://developers.elementor.com/docs/deprecations/) tutorials and [this example](https://developers.elementor.com/docs/deprecations/simple-example/).

The error message comes from one of the plugins you installed on your site. One of them is using outdated methods. You need to find the plugin, contact the plugin developers and ask them to update deprecated code.
