### ISSUE TITLE
❌ page content repeating (doubles) on scroll elementor wordpress plugin 

### ISSUE THREAD

**Issue by rvadhvana** [elementor/elementor#20537]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

after creating the page , I see two times the content 
ppls check my website here 
https://dentavibe.com/location/

### Steps to reproduce

I am not a developer so don't know howto do this 
just tried using the elementor plugin and causing this issue 

can check thewebsite link 
https://dentavibe.com/location/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.25
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://dentavibe.com
	Home URL: https://dentavibe.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Toronto
	Admin Email: romikatmiya@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Denticare
	Version: 1.2.0
	Author: BoldThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Bold Builder
		Version: 4.4.8
		Author: BoldThemes

	BoldThemes WordPress Importer
		Version: 2.7.6
		Author: BoldThemes

	Bold Timeline Lite
		Version: 1.1.4
		Author: BoldThemes

	Contact Form 7
		Version: 5.6.4
		Author: Takayuki Miyoshi

	Cost Calculator
		Version: 2.3.7
		Author: BoldThemes

	Creative Mail by Newfold Digital
		Version: 1.6.4
		Author: Newfold Digital

	Denticare Plugin
		Version: 1.2.0
		Author: BoldThemes

	Easy Under Construction
		Version: 5.0
		Author: Abbas Khalil

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Flamingo
		Version: 2.3
		Author: Takayuki Miyoshi

	Gleam
		Version: 1.0
		Author: Crowd9

	Head, Footer and Post Injections
		Version: 3.2.5
		Author: Stefano Lissa

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 9.0.480
		Author: HubSpot

	IONOS Performance
		Version: 1.2.3
		Author: IONOS

	Jetpack
		Version: 11.5.1
		Author: Automattic

	Loginizer
		Version: 1.7.6
		Author: Softaculous

	MailChimp
		Version: 1.5.8
		Author: MailChimp

	Meta Box
		Version: 5.6.8
		Author: MetaBox.io

	Site Kit by Google
		Version: 1.88.0
		Author: Google

	Timetable and Event Schedule
		Version: 2.4.7
		Author: MotoPress

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Must-Use Plugins ==
	1&1 Product Subdomain
		Version: 1.1.0
		Author: 1&1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 6 of 62022-11-25 00:19:50 [info] elementor::elementor_updater Started 
2022-11-25 00:19:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-25 00:19:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-25 00:19:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-25 00:19:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-25 00:19:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @rvadhvana,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
