### ISSUE TITLE
❌ Elementor Header and Footer Hides my Blog Titles

### ISSUE THREAD

**Issue by miamiameow** [elementor/elementor#20539]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, when the plugin is on my blog posts don't show their titles. When I deactivate the Elementor Header and Footer, they show back up. Help!

### Steps to reproduce

turning the plugin off and on

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.imagineelopements.com
	Home URL: https://www.imagineelopements.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: imagineelopements@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Asset CleanUp: Page Speed Booster
		Version: 1.3.8.9
		Author: Gabe Livan

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.1.0
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	GA Google Analytics
		Version: 20221016
		Author: Jeff Starr

	Google Analytics for WordPress by MonsterInsights
		Version: 8.10.1
		Author: MonsterInsights

	Hotjar
		Version: 1.0.14
		Author: Hotjar

	Reading Time WP
		Version: 2.0.12
		Author: Jason Yingling

	SiteGround Optimizer
		Version: 7.2.6
		Author: SiteGround

	SiteGround Security
		Version: 1.3.7
		Author: SiteGround

	Sticky Header Effects for Elementor
		Version: 1.5.5
		Author: Rwattner

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 302022-09-20 16:55:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-20 16:55:46 [info] elementor-pro::elementor_pro_updater Started 
2022-09-20 16:55:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-20 16:55:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-20 16:55:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-31 05:28:39 [info] elementor-pro::elementor_pro_updater Started 
2022-10-31 05:28:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-31 05:28:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-31 05:28:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 05:28:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-10 03:38:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-10 03:38:58 [info] elementor-pro::elementor_pro_updater Started 
2022-11-10 03:38:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-10 03:38:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-10 03:38:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-21 14:59:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-11-21 14:59:12 [info] elementor-pro::elementor_pro_updater Started 
2022-11-21 14:59:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-21 14:59:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-21 14:59:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]

PHP: showing 3 of 3PHP: 2022-09-07 10:30:37 [notice X 1][/home/customer/www/imagineelopements.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::273] Undefined index: query [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-12 12:30:53 [notice X 4][/home/customer/www/imagineelopements.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-22 13:42:52 [notice X 7][/home/customer/www/imagineelopements.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2022-09-12 17:30:20 [error X 1][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:287003] Cannot read properties of undefined (reading \'id\') 
JS: 2022-09-16 17:48:49 [error X 21][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:767576] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-09-18 20:56:26 [error X 1][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:539365] Blocked a frame with origin \"https://www.imagineelopements.com\" from accessing a cross-origin frame. 
JS: 2022-09-19 15:48:58 [error X 2][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:1060720] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-21 17:19:03 [error X 24][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:692080] T.getContainer is not a function 
JS: 2022-09-23 20:14:36 [error X 28][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:767341] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-10-28 19:26:12 [error X 260][https://www.imagineelopements.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js:2:4795] Cannot read properties of undefined (reading \'data\') 
JS: 2022-11-17 19:23:58 [error X 39][https://www.imagineelopements.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-22 21:43:37 [error X 1][https://www.imagineelopements.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading \'getOptions\') 

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	
[system-info-www.imagineelopements.com-27-11-2022.txt](https://github.com/elementor/elementor/files/10097684/system-info-www.imagineelopements.com-27-11-2022.txt)

**Comment by nicholaszein** [comment]
Hello @miamiameow,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards
