### ISSUE TITLE
❌ 🐞 Bug Report: Hebrew IDN ccTLD is classified as an invalid domain format

### ISSUE THREAD

**Issue by ogreenz** [elementor/elementor#20550]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Trying to connect my website with a hebrew ccTLD, the "connect a custom domain" ran into an error saying:
"Enter a valid domain format."

Background:
Recently ICANN allowed a hebrew IDN ccTLD of .ישראל meaning domain names can be entirely in hebrew such as:
משהו.ישראל

Connecting to them should be allowed.

### Steps to reproduce

1. Go on to "connect a custom domain" form
2. enter any hebrew custom domain with .ישראל ccTLD

### Isolating the problem

- [X] I can reproduce this bug consistently using the steps above.

### System Info

This isn't necessary.

**Comment by nicholaszein** [comment]
Hello @ogreenz,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. Contact Elementor Support through your [Elementor Account](https://my.elementor.com/dashboard-support/).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
