### ISSUE TITLE
⛔ 🐞 Bug Report: Embed Javascript don't shows map in popup window but shows in Elementor Editor

### ISSUE THREAD

**Issue by 0618Space** [elementor/elementor#20558]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello.

We're trying to use 3rd side embed JS code that pulls up and show custom Map in pop up Elementor. 

Strange part is that JS code and map showing in Editor just fine and no any problem w/ it but online pop up opens empty, w/o map. 

Here's the JS-code we used:

````html 
<script src="https://widget.pochta.ru/map/widget/widget.js"></script>
<script>
    ecomStartWidget({
      id: 30266,
      callbackFunction: null,
      containerId: 'ecom-widget'
    });
</script>
````
  
This work just fine in Editor but don't work at all Online. Also this code works just fine on the web page. Only Pop up seems need something to let map appear Online properly.

Is there any ideas, solutions how to fix this bug?

Thank you in advance.

### Steps to reproduce

1) Add any pop up in Elementor.
2) Add HTML widget to your pop up element.
3) Add JS code as shown below:

<div id="ecom-widget" style="height: 100vh;">
- JS CODE HERE -
</div>

4) Save it. You'll see Map will appear in Elementor Editor but will not appears Online. Which is strange due we use the same Browser.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 30, Revision 8916819 v5.7.27-30
	PHP Version: 7.4.28
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://optom.store
	Home URL: https://optom.store
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 512M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%
	Language: en-US
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	User Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Admin CSS MU
		Version: 2.7
		Author: Arun Basil Lal

	Admin Menu Editor
		Version: 1.10.4
		Author: Janis Elsts

	All In One WP Security
		Version: 5.1.1
		Author: All In One WP Security & Firewall Team

	AZ Video and Audio Player Addon for Elementor
		Version: 2.0.1
		Author: AZ Plugins

	Duplicate Post Page Menu & Custom Post Type
		Version: 2.2.0
		Author: Inqsys Technology

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	Loginizer
		Version: 1.7.6
		Author: Softaculous

	OoohBoi Steroids for Elementor
		Version: 2.0.5
		Author: OoohBoi

	PDF viewer for Elementor
		Version: 2.9.3
		Author: RedLettuce Plugins

	Pretty Links
		Version: 3.2.7
		Author: Pretty Links

	Rank Math SEO
		Version: 1.0.102.1
		Author: Rank Math

	Real-Time Find and Replace
		Version: 4.0.2
		Author: Marios Alexandrou

	Share Buttons by AddThis
		Version: 6.2.7
		Author: The AddThis Team

	Simple Custom CSS and JS
		Version: 3.41
		Author: SilkyPress.com

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps

	White Label
		Version: 2.5.2
		Author: WhiteWP.com

	WP-Memory-Usage
		Version: 1.2.6
		Author: Bernhard Kux

	WP Fastest Cache
		Version: 1.0.8
		Author: Emre Vona

	WP Force SSL
		Version: 1.65
		Author: WebFactory Ltd

	Yandex.Metrica
		Version: 1.1.7
		Author: Yandex

== Must-Use Plugins ==
	aios-firewall-loader.php
		Version: 
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active by default
	Notes: Active
	Loop: Inactive by default
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 232022-10-24 14:00:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-24 14:00:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev4',
)]
2022-10-24 14:05:45 [notice] Re-migrate 3.0.0 globals: Start 
2022-10-24 14:05:45 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2022-10-24 14:05:45 [notice] System typography already exist. nothing to do. 
2022-10-24 14:05:45 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2022-10-24 14:05:45 [notice] System colors already exist. nothing to do. 
2022-10-24 14:05:45 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2022-10-24 14:05:45 [notice] Custom colors already exist. nothing to do. 
2022-10-24 14:05:45 [notice] Re-migrate 3.0.0 globals: End 
2022-11-03 20:23:25 [info] elementor::elementor_updater Started 
2022-11-03 20:23:25 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-03 20:23:25 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-03 20:23:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-11-03 20:23:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-11-05 21:51:20 [info] elementor-pro::elementor_pro_updater Started 
2022-11-05 21:51:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-05 21:51:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-05 21:51:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]
2022-11-05 21:51:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-dev4',
  'to' => '3.9.0-dev5',
)]

PHP: showing 11 of 11PHP: 2022-10-24 13:59:42 [notice X 583][/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-24 14:02:28 [notice X 7][/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-24 14:05:45 [warning X 1][/var/www/u1132546/optom.store/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable $active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 14:06:15 [notice X 428][/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-24 14:10:31 [notice X 31][/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-05 11:44:54 [warning X 1][/var/www/u1132546/optom.store/wp-content/plugins/elementor/includes/managers/image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-05 13:11:30 [error X 1][/var/www/u1132546/optom.store/wp-content/plugins/elementor/includes/managers/widgets.php::408] Uncaught Error: Call to a member function is_editable_by_current_user() on bool in /var/www/u1132546/optom.store/wp-content/plugins/elementor/includes/managers/widgets.php:408
Stack trace:
#0 [internal function]: Elementor\Widgets_Manager->ajax_render_widget(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /var/www/u1132546/optom.store/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/u1132546/optom.store/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /var/www/u1132546/optom.store/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /var/www/u1132546/optom.store/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/u1132546/optom.store/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-05 13:11:41 [error X 2][/var/www/u1132546/optom.store/wp-content/plugins/elementor/core/documents-manager.php::493] Uncaught Error: Call to a member function is_built_with_elementor() on bool in /var/www/u1132546/optom.store/wp-content/plugins/elementor/core/documents-manager.php:493
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /var/www/u1132546/optom.store/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/u1132546/optom.store/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /var/www/u1132546/optom.store/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /var/www/u1132546/optom.store/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/u1132546/optom.store/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-06 10:08:05 [notice X 3][/var/www/u1132546/optom.store/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Optional parameter $size declared before required parameter $url is implicitly treated as a required parameter [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-06 20:13:02 [notice X 7][/var/www/u1132546/optom.store/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 20:46:05 [error X 1][/var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/u1132546/optom.store/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(237, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/u1132546/optom.store/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/u1132546/optom.store/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/u1132546/optom.store/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /va [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-11-03 17:21:07 [error X 92][https://optom.store/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-03 17:24:34 [error X 3][https://optom.store/:2219:104] Cannot read properties of undefined (reading \'handlers\') 
JS: 2022-11-03 17:24:34 [error X 3][https://optom.store/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] Cannot read properties of undefined (reading \'tools\') 
JS: 2022-11-05 09:28:28 [error X 1][https://optom.store/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0-dev4:3:849720] Cannot read properties of undefined (reading \'val\') 
JS: 2022-11-07 05:55:05 [error X 13][https://optom.store/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.0:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-11-07 05:55:42 [error X 3][https://optom.store/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.8.0:2:4825] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-11-08 18:41:25 [error X 1][https://optom.store/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:634181] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-11-18 17:08:49 [error X 9][https://optom.store/kedrovyj-oreh-1750:2:5] ecomStartWidget is not defined 

== Elementor - Compatibility Tag ==
	
	AZ Video and Audio Player Addon for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	OoohBoi Steroids for Elementor: Compatibility not specified
	PDF viewer for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @0618Space,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Pop-ups only load via Ajax, they are not loaded with the DOM, which means your script has not been initiated when it is loaded.
* You are using the script the wrong way. Try separating 

### ✅ What you can do to solve your issue:
* We do not provide support for custom code. However, you can try to separate the first script and use the [Custom Code](https://elementor.com/help/custom-code-pro/) to add it to the footer of the page. Place this portion of the code you provided: `<script src="https://widget.pochta.ru/map/widget/widget.js"></script>`, and set the location to `<body> - End`.
* Leave the rest of the code inside your popup.

#### ⚠️ Please note that we do not guarantee this will work for you, but you'll have better chances to make it work. If it doesn't work, try asking for help from the Elementor Community on Facebook.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
