### ISSUE TITLE
❌ 🐞 Bug Report: Not able to edit page with Element, blocked by loader on Elementor manager

### ISSUE THREAD

**Issue by redo-interactive** [elementor/elementor#20563]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When editing a page not able to add new elements or update existing ones. There is a loader layer that doesn't disappear. 
![image](https://user-images.githubusercontent.com/62672785/204570028-380b2c24-c9ff-40c3-adbb-a30ef1bcd6b0.png)

### Steps to reproduce

1) Go to page edition
2) Loader does not disappear. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.4.18
	PHP Version: 8.0.14
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://boucheries.com
	Home URL: https://boucheries.com
	WP Multisite: No
	Max Upload Size: 64 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: support@nokytech.fr
	Debug Mode: Inactive

== Theme ==
	Name: boucheries
	Version: 1.1.8
	Author: nokytech
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.3
		Author: WP Engine

	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	CookieYes | GDPR Cookie Consent
		Version: 3.0.5
		Author: CookieYes

	Disable Comments RB
		Version: 1.0.20
		Author: rbPlugins

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.8
		Author: Gravity Forms

	iThemes Security
		Version: 8.1.3
		Author: iThemes

	LoginPress - Customizing the WordPress Login Screen.
		Version: 1.6.3
		Author: WPBrigade

	Neuron Core
		Version: 1.0.0
		Author: NeuronThemes

	Post SMTP
		Version: 2.1.10
		Author: Post SMTP

	Stratum - Elementor Widgets
		Version: 1.3.13
		Author: MotoPress

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	WP Migrate Lite
		Version: 2.5.0
		Author: Delicious Brains

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Must-Use Plugins ==
	WP Migrate DB Compatibility
		Version: 1.2
		Author: Delicious Brains

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Inactif par défaut
	Import Export Website Kit: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut

== Journal ==
	
Log: showing 20 of 412022-07-12 15:00:10 [info] elementor::elementor_updater Started 
2022-07-12 15:00:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-12 15:00:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-12 15:00:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.6.7',
)]
2022-10-05 21:45:37 [info] elementor::elementor_updater Started 
2022-10-05 21:45:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-05 21:45:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-05 21:45:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.8',
)]
2022-10-05 21:45:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.8',
)]
2022-10-05 21:45:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.8',
)]
2022-11-03 12:01:43 [info] elementor::elementor_updater Started 
2022-11-03 12:01:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-03 12:01:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-03 12:01:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-15 10:40:03 [info] elementor::elementor_updater Started 
2022-11-15 10:40:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-15 10:40:03 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-15 10:40:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-15 10:40:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-15 10:40:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 1 of 1PHP: 2022-07-12 14:59:05 [notice X 12394][/home/bouch914/domains/boucheries.com/public_html/assets/plugins/elementor/modules/dev-tools/deprecation.php::301] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Stratum - Elementor Widgets: Compatibilité non spécifiée

**Comment by nicholaszein** [comment]
Hello @redo-interactive,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. Your issue most likely is caused by your 3rd party Elementor add-on (Stratum), and lack of server resources.

👉 Try following [this article](https://elementor.com/help/cant-edit-with-elementor/#panelgray) to troubleshoot your issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
