### ISSUE TITLE
✅ 🚀 Feature Request: Make Numeric Control inputs widths fit-content when using custom values (units) in Dev-3.10

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20576]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It seems that in version 3.10 you plan to expand numeric inputs like the width field. so that we can use css functions like calc in them. So I wanted to make a suggestion to improve this feature before release...

Currently, Elementor inputs are such that if we want to use calc or clamp values, there is not enough space to display it and if we want to edit the entered values, it will be very difficult to do so. Please see the image below.

![width](https://user-images.githubusercontent.com/77163248/204840080-7d547f00-12ae-4842-ab5f-0d54038d628d.png)

### Describe the solution you'd like

It would be great if the width in the width field increased based on the input value.
Please watch the video below. That's exactly what I'm talking about. It would be great if the width field worked like this.

https://user-images.githubusercontent.com/77163248/204841970-98e784d2-bdd9-45f1-95af-a1e5d6d8aa3d.mp4

thank you

**Comment by m1ga** [comment]
I think it would even help to remove the slider and extend the input field to 100%. If you run the 3.10.0 branch you can see that they disable the slider already but it's currently still there

**Comment by 79ho3ein** [comment]
really?
Will they remove the slider from the width fields in version 3.10? I filed a request to remove the slider in the width field almost a year ago, but they said we have no plans to remove it.
In my opinion, the slider in the width field is an outdated method and I don't think users will use it. bricks is a template that has received most of its ideas from Elementor. But in some cases it has worked very well in its editor ui/ux. Numeric fields in bricks are simple yet powerful. So it's not bad if Elementor acts like them.

![d](https://user-images.githubusercontent.com/77163248/204910618-2a012bb6-90a5-4d08-a57e-d4ca46fb8071.png)

**Comment by m1ga** [comment]
> really? Will they remove the slider from the width fields in version 3.10?

no, I just said its disabled :wink: I *hope* they'll remove it. You can download the branch and check it yourself.

Without the styles you can see this:

![Screenshot_20221130_222610](https://user-images.githubusercontent.com/4334997/204912185-69b9d5bd-47d8-4bc4-bd80-cebedb113b52.png)
(see no slider dot when I select custom)

when I build the styles it will extend a bit:

https://user-images.githubusercontent.com/4334997/204912706-c429c5af-65ca-4f28-a4eb-f551cdfdfb83.mp4

but the value fields are missing so I can't switch to "custom" at the moment.

So let's see what they'll make out of it :smile:

**Comment by 79ho3ein** [comment]
Thanks for the great Image and video. In the first image, the unit selection section looks disappointing😃. Anyway, I agree with you. We have to see what the result will be.

**Comment by Joliamendi** [comment]
> > really? Will they remove the slider from the width fields in version 3.10?
> 
> no, I just said its disabled 😉 I _hope_ they'll remove it. You can download the branch and check it yourself.
> 
> Without the styles you can see this:
> 
> ![Screenshot_20221130_222610](https://user-images.githubusercontent.com/4334997/204912185-69b9d5bd-47d8-4bc4-bd80-cebedb113b52.png) (see no slider dot when I select custom)

Is the unit selection section really going to be like this? This ui looks like it's from 20 years ago!
I hope its ui will be revised. **With respect to the great team of Elementor.**

**Comment by m1ga** [comment]
no, please read! Its **without the styles!** Also it's from the 3.10 branch, no release or even an alpha version! Don't judge those images! You can get the branch and look at them yourself, its open source :wink: I didn't run the whole build to see it correctly

**Comment by Michaelgimii** [comment]
This is a great idea!
I also have a proposal to improve the ui/ux in padding, margin and border fields, which I will submit in a new issue. I hope the Elementor team will take a look at it.

**Comment by nicholaszein** [comment]
Hello @79ho3ein!

You are fast! 😅 

Thanks for submitting your request!

As for everybody else, let's not get ahead of ourselves. Everything will be revealed in time. 😉

**Comment by 79ho3ein** [comment]
> Hello @79ho3ein!
> 
> You are fast! 😅
> 

I love Elementor 😃

**Comment by nicholaszein** [comment]
Hey everyone!

This issue was solved some time ago. For this reason, I'm closing it as solved.

Thanks everyone for your contributions! 🙏
