### ISSUE TITLE
🚀 Feature Request: Add filter or action to add content to a container

### ISSUE THREAD

**Issue by webzunft** [elementor/elementor#20577]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I am trying to add content to the container element. Either before or after the `<div class="e-con-inner">` tag in the screenshot.

![missing-container-hook](https://user-images.githubusercontent.com/2728720/204846950-92a2bf23-5b4e-4a2d-a0ee-84d96bf741c7.png)

The `elementor/widget/render_content` filter hook would work for widgets. I need an equivalent for containers, or best, any element.

I have tried hooks like `elementor/frontend/after_render`, but they only add content outside the `elementor-element` container, not inside of it.

### Describe the solution you'd like

A filter hook like `elementor/element/render_content` or `elementor/container/render_content` to filter the output of any element.

### Describe alternatives you've considered

Using `ob_cache` for the whole site and add my own content. But I have seen conflicts with that in the past when other plugins also use `ob_cache` like Elementor does.
Using JavaScript would be another solution for my use case. A PHP hook would be best, though.

**Comment by nicholaszein** [comment]
Hello @webzunft!

Thanks for submitting your issue.

You can already use the `elementor/frontend/{$element_type}/before_render` hook as documented [here](https://developers.elementor.com/docs/hooks/render-frontend-elements/).

````php
/**
 * Add `<div>` before a container in the page.
 *
 * @since 1.0.0
 * @param \Elementor\Element_Base $element The element instance.
 */
function add_div_before_a_container( $element ) {
	?>
	<div class="before-container">Text before container</div>
	<?php
}
add_action( 'elementor/frontend/container/before_render', 'add_div_before_a_container' );

````

As for the request, we do not plan to add the hook inside elements for the time being. We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by imamfirmansyah** [comment]
add_action( 'elementor/frontend/container/before_render', 'add_div_before_a_container' );

is not working
