### ISSUE TITLE
⛔ 🚀 Feature Request: Remember the location of the widget panel when switching between similar widgets

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#20584]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello team

If we have several similar widgets in Elementor, if we are in the responsive tab in the first widget, for example, if we click on the second widget, the content tab will be displayed first, and then we must click on the advanced tab. And then enter the responsive tab. This is a very uncomfortable method.

### Describe the solution you'd like

It is better if we have several similar widgets, if we are in the advanced tab > Responsive (or any other section) in widget A, after clicking on widgets B, C, D, which are similar widgets, automatically open the responsive tab. to be This will greatly increase the speed of work.

The bricks template uses this mechanism. Please see the video below.

https://user-images.githubusercontent.com/103376243/205026107-4ce3864d-1655-4430-ae98-c47d4ca36998.mp4

As you can see in the video above, there were 4 similar widgets (buttons). In one of them I was in the border section. After that, I clicked on other buttons and the border section was automatically displayed.
But in Elementor, after clicking on the same widget, the content tab is displayed first!

Please keep this feature in mind. It seems simple, but very effective. @arielk 

thanks

**Comment by nicholaszein** [comment]
Hello @Joliamendi,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

The way the editor works now is to remember the location of each individual widget, as requested by other users in the past. We do not plan to change this behavior, especially to avoid confusion of which widget is being edited.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
