### ISSUE TITLE
✅ 🚀 Feature Request: Improve Dimension control's UI/UX by allowing fields to grows when in :focus

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20580]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

I hope you have a plan to improve padding, margin and border controls. I think it's time for them to change after 6 years.
In the following, I have two suggestions to improve these controls, which I hope will be useful for you.

### Describe the solution you'd like

**1- UI improvements**

This is what I have in mind, and of course it needs a lot of thought.

![new ui](https://user-images.githubusercontent.com/88034902/204923524-6d079d2f-ddac-4eaa-8796-75dd850b3f30.jpg)

**2- UX improvements**

If we click on any of the options (up, right, down, left), its width will increase. A great ux.

https://user-images.githubusercontent.com/88034902/204923833-e73de2d7-b521-472a-a766-37f31a40f088.mp4

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

thanks for submitting your feature request! 🙏 

We are going to keep this in mind for future UI improvements.

Best regards

**Comment by nicholaszein** [comment]
Hi @Michaelgimii!

Somehow I missed this one. This feature was added to custom units in version **3.10**.

Thanks for the contribution! 🙏 

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
