### ISSUE TITLE
❌ 🐞 Bug Report: Suddenly we are facing an issue in our website - Warning: Undefined array key "publish"

### ISSUE THREAD

**Issue by bdkoder** [elementor/elementor#20585]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The issue - 

Warning: Undefined array key "publish" in /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/modules/usage/module.php on line 79

### Steps to reproduce

It's only facing one of our client websites. Even this issue not happening on our projects.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.26
	PHP Memory Limit: -1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://nailsworthtennisclub.co.uk
	Home URL: https://nailsworthtennisclub.co.uk
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: -1
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: paul.speariett@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hueman
	Version: 3.7.23
	Author: nikeo
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-dev1
		Author: Elementor.com

	Element Pack Pro
		Version: 6.9.0
		Author: BdThemes

	ElementsKit Lite
		Version: 2.7.5
		Author: Wpmet

	ElementsKit Pro
		Version: 2.8.0
		Author: Wpmet

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Events Schedule WP Plugin
		Version: 2.5.17
		Author: Curly Themes

	Font Awesome
		Version: 4.3.1
		Author: Font Awesome

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	Slider Revolution
		Version: 6.6.7
		Author: ThemePunch

	Transients Manager
		Version: 2.0.3
		Author: WPBeginner

	WPForms Lite
		Version: 1.7.8
		Author: WPForms

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.8.1
		Author: 

	WordPress automation by Installatron
		Version: 
		Author: 

<br />
<b>Warning</b>:  Undefined array key "publish" in <b>/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/modules/usage/module.php</b> on line <b>79</b><br />

== Elements Usage ==
	
	footer : 1
		heading : 1
		image : 1
		social-icons : 1
		text-editor : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	section : 13
		accordion : 5
		blockquote : 1
		button : 4
		countdown : 1
		counter : 2
		divider : 11
		elementskit-button : 6
		elementskit-heading : 17
		elementskit-image-box : 1
		elementskit-pricing : 5
		form : 1
		gallery : 2
		google_maps : 1
		heading : 53
		icon : 4
		icon-box : 9
		icon-list : 26
		image : 29
		image-box : 6
		post-comments : 1
		post-navigation : 1
		posts : 4
		search-form : 1
		share-buttons : 1
		slides : 1
		star-rating : 7
		tabs : 2
		testimonial-carousel : 2
		text-editor : 10
	wp-post : 
		author-box : 1
		elementskit-heading : 5
		elementskit-page-list : 5
		google_maps : 1
		image : 1
		post-comments : 1
		post-info : 2
		post-navigation : 1
		posts : 1
		shortcode : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-page : 7
		accordion : 1
		bdt-contact-form : 1
		button : 5
		countdown : 1
		counter : 2
		divider : 5
		elementskit-heading : 5
		google_maps : 1
		heading : 14
		icon : 3
		icon-list : 2
		image : 4
		price-table : 7
		shortcode : 1
		testimonial-carousel : 1
		text-editor : 9
	single-post : 2
		author-box : 1
		blockquote : 1
		heading : 2
		image : 1
		post-comments : 1
		post-info : 2
		post-navigation : 1
		posts : 1
		share-buttons : 1
		table-of-contents : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 262022-11-29 09:38:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-30 11:30:39 [info] elementor-pro::elementor_pro_updater Started 
2022-11-30 11:30:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-30 11:30:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-30 11:30:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.10.0-dev1',
)]
2022-11-30 11:30:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.10.0-dev1',
)]
2022-12-01 09:25:20 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2022-12-01 09:25:21 [info] elementor::custom_task_manger Started 
2022-12-01 09:25:21 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2022-12-01 09:25:21 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2022-12-01 09:25:21 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2022-12-01 09:25:21 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2022-12-01 09:25:21 [info] elementor::custom_task_manger Completed 
2022-12-01 10:06:28 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2022-12-01 10:06:28 [info] elementor::custom_task_manger Started 
2022-12-01 10:06:28 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2022-12-01 10:06:29 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2022-12-01 10:06:29 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2022-12-01 10:06:29 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2022-12-01 10:06:29 [info] elementor::custom_task_manger Completed 

PHP: showing 8 of 8PHP: 2022-11-24 10:19:26 [warning X 6][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 12:05:53 [error X 2][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /homepages/24/d4296895500/htdocs/wordpress/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-27 21:45:55 [warning X 34][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/modules/usage/module.php::79] Undefined array key "publish" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-29 09:38:28 [notice X 380][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 12:11:12 [error X 2][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\Usage\Module" not found in /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/includes/plugin.php(724): Elementor\Core\Modules_Manager->__construct()
#1 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/includes/plugin.php(641): Elementor\Plugin->init_components()
#2 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /homepages/24/d4296895500/htdocs/wordpress/wp-settings.php(617): do_action('init')
#6 /homepages/24/d4296895500/htdocs/wordpress/wp-config.php(189): require_once('/homepages/24/d...')
#7 /homepages/24/d4296895500/htdocs/wordpress/wp-load.php(50): require_once('/homepages/24/d...')
#8 /homepages/24/d4296895500/htdocs/wordpress/wp-admin/admin-ajax.php(22): require_once('/homepages/24/d...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 12:11:15 [error X 3][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\Usage\Module" not found in /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/includes/plugin.php(724): Elementor\Core\Modules_Manager->__construct()
#1 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/includes/plugin.php(641): Elementor\Plugin->init_components()
#2 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /homepages/24/d4296895500/htdocs/wordpress/wp-settings.php(617): do_action('init')
#6 /homepages/24/d4296895500/htdocs/wordpress/wp-config.php(189): require_once('/homepages/24/d...')
#7 /homepages/24/d4296895500/htdocs/wordpress/wp-load.php(50): require_once('/homepages/24/d...')
#8 /homepages/24/d4296895500/htdocs/wordpress/wp-admin/admin.php(34): require_once('/homepages/24/d...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 12:11:29 [error X 1][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/modules-manager.php::53] Uncaught Error: Class "Elementor\Modules\Usage\Module" not found in /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/core/modules-manager.php:53
Stack trace:
#0 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/includes/plugin.php(724): Elementor\Core\Modules_Manager->__construct()
#1 /homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/includes/plugin.php(641): Elementor\Plugin->init_components()
#2 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /homepages/24/d4296895500/htdocs/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /homepages/24/d4296895500/htdocs/wordpress/wp-settings.php(617): do_action('init')
#6 /homepages/24/d4296895500/htdocs/wordpress/wp-config.php(189): require_once('/homepages/24/d...')
#7 /homepages/24/d4296895500/htdocs/wordpress/wp-load.php(50): require_once('/homepages/24/d...')
#8 /homepages/24/d4296895500/htdocs/wordpress/wp-blog-header.php(13): require_once('/homepages/24/d...')
#9 /homepages/24/d4296895500/htdocs/wordpress/index.php(17): require('/homepages/24/d...')
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-01 10:06:29 [notice X 2][/homepages/24/d4296895500/htdocs/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2022-11-24 13:38:26 [error X 10][https://nailsworthtennisclub.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:769459] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-11-24 22:54:15 [error X 2][https://nailsworthtennisclub.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-24 23:22:40 [error X 3][https://nailsworthtennisclub.co.uk/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,underscore,backbone,jquery-ui-core,jquery-ui-mouse,jquery-ui-draggabl&loadchunk_1=e,wp-api-request,wp-hooks&ver=6.1.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-25 10:23:23 [error X 4][https://nailsworthtennisclub.co.uk/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.8.1:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `selected_icon` value. Expected array or object.',
)]
JS: 2022-11-25 15:13:23 [error X 21][https://nailsworthtennisclub.co.uk/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.8.1:2:5140] Cannot read properties of undefined (reading \'toJSON\') 
JS: 2022-11-25 15:15:27 [error X 3][https://nailsworthtennisclub.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:768] Cannot read properties of null (reading \'cid\') 
JS: 2022-11-25 15:16:21 [error X 3][https://nailsworthtennisclub.co.uk/wp-admin/post.php?post=485&action=elementor#:6:9] row_text1 is not defined 
JS: 2022-11-25 16:08:49 [error X 9][https://nailsworthtennisclub.co.uk/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.8.1:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `menu_link` value. Expected array or object.',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Element Pack Pro: Compatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @bdkoder,

Thanks for contacting us! 🙏 

### ❌ This is more of a support question, not really something we can answer here.

This is likely an issue caused by a conflict with another plugin. Try to follow the troubleshooting steps in [this article](https://elementor.com/help/publish-update-button-not-work/). If it doesn't work, try following [this other article](https://elementor.com/help/cant-edit-with-elementor/).

### Please remember to always follow these guidelines:

- **Prerequisites:** please search the repository before submitting an issue;
- **Description:** you did not provide a detailed description and examples of your issue;
- **Steps to replicate:** You did not provide any way for us to try to reproduce your issue;
- **Isolating the Problem:** You need to make sure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
