### ISSUE TITLE
⛔ 🐞 Bug Report: Can not disable "Enable unfiltered file uploads"

### ISSUE THREAD

**Issue by ctl6998** [elementor/elementor#20595]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, 

After enable "Enable unfiltered file uploads" in Elementor/Settings/Advanced to upload SVG files, I can not find a way to disable this. After I chose disable I was still able to upload SVG.

More seriously, I have tried the following way to disable SVG upload, nothing works:
+ Adding: define('ALLOW_UNFILTERED_UPLOADS', fase);
+ Unset all MIMES type in function.php

The problem only occur while I'm activating Elementor. Can you fix this?

### Steps to reproduce

1. Enable "Enable unfiltered file uploads" in Elementor/Settings/Advanced to upload SVG
2. Disable "Enable unfiltered file uploads" in Elementor/Settings/Advanced
3. Still able to upload SVG

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.61-MariaDB-38.13
	PHP Version: 7.4.33
	PHP Memory Limit: 4096M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 4096M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://sma.tmavn.com
	Home URL: https://sma.tmavn.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 4096M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: tmavn.technical@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.5
		Author: WP Engine

	Custom Post Type UI
		Version: 1.13.2
		Author: WebDevStudios

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.5
		Author: Wpmet

	Folders
		Version: 2.8.7
		Author: Premio

	Sticky Header Effects for Elementor
		Version: 1.5.5
		Author: Rwattner

	The Plus Addons for Elementor
		Version: 5.1.14
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.1.3
		Author: POSIMYTH

== Elements Usage ==
	
	archive : 2
		heading : 3
		icon-list : 1
		posts : 2
		search-form : 1
		text-editor : 1
	footer : 1
		button : 1
		form : 1
		heading : 2
		icon-list : 3
		image : 1
		social-icons : 1
		text-editor : 1
	header : 2
		button : 3
		ekit-nav-menu : 2
		heading : 4
		image : 3
		text-editor : 1
	loop : 1
		button : 1
		heading : 2
		tp-post-featured-image : 1
	page : 1
		button : 1
		form : 1
		heading : 6
		image : 1
		text-editor : 1
	wp-page : 5
		button : 11
		divider : 6
		elementskit-accordion : 1
		elementskit-blog-posts : 1
		elementskit-testimonial : 2
		form : 1
		heading : 41
		icon : 2
		icon-box : 6
		icon-list : 11
		image : 5
		image-carousel : 1
		posts : 1
		social-icons : 1
		text-editor : 25
		tp-draw-svg : 4
		tp-dynamic-listing : 2
	single-post : 2
		button : 1
		divider : 1
		form : 1
		gallery : 1
		heading : 11
		icon-box : 3
		icon-list : 1
		image : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		social-icons : 1
		table-of-contents : 2
		text-editor : 3
		theme-post-content : 2
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 5 of 52022-11-24 07:13:21 [info] elementor-pro::elementor_pro_updater Started 
2022-11-24 07:13:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-24 07:13:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-24 07:13:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.8.2',
)]
2022-11-24 07:13:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.8.2',
)]

PHP: showing 13 of 13PHP: 2022-11-24 07:47:11 [notice X 164][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/metform/controls/base.php(50): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-11-24 07:52:47 [notice X 1502][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 07:56:53 [notice X 6][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 08:03:19 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 09:28:17 [error X 6][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#6  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-24 10:18:51 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::270] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-02 09:59:09 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::219] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(219): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render_post_content()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
',
)]
PHP: 2022-12-02 09:59:09 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::226] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(226): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render_post_content()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
',
)]
PHP: 2022-12-02 09:59:09 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::231] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(231): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render_post_content()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
',
)]
PHP: 2022-12-02 09:59:09 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::237] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(237): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render_post_content()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
',
)]
PHP: 2022-12-02 09:59:09 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::243] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(243): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render_post_content()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
',
)]
PHP: 2022-12-02 09:59:09 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php(264): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php(111): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render_post_content()
#2: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\ThemeBuilder\Widgets\Post_Content -> render()
#3: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#4: /var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
',
)]
PHP: 2022-12-02 11:14:19 [notice X 1][/var/www/vhosts/tmavn.com/sma.tmavn.com/wp-content/plugins/elementor-pro/modules/gallery/widgets/gallery.php::1355] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 10 of 10JS: 2022-11-24 07:52:36 [error X 10][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-11-24 08:38:02 [error X 4][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:694254] T.getContainer is not a function 
JS: 2022-11-24 09:29:53 [error X 23][https://sma.tmavn.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,wp-&loadchunk_1=hooks&ver=6.1.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-24 10:22:25 [error X 1][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:572731] Cannot read properties of null (reading \'id\') 
JS: 2022-11-24 13:23:50 [error X 2][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:768952] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-11-24 13:55:48 [error X 9][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-29 12:26:54 [error X 2][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:769459] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-12-02 10:24:21 [error X 1][https://sma.tmavn.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.8.2:3:99294] Cannot convert undefined or null to object 
JS: 2022-12-02 10:47:42 [error X 2][https://sma.tmavn.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.8.2:1:1162] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-12-02 20:19:41 [error X 443][https://sma.tmavn.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:602152] undefined is not an object (evaluating \'B.get\') 

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatible
	Elementor Pro: Incompatible
	Sticky Header Effects for Elementor: Compatibility not specified
	The Plus Addons for Elementor: Compatible
	The Plus Addons for Elementor - Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatible
	The Plus Addons for Elementor: Compatible
	The Plus Addons for Elementor - Pro: Incompatible

**Comment by nicholaszein** [comment]
Hello @ctl6998,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We cannot reproduce your issue using **only** the latest version of Elementor (v3.8.2) and Elementor Pro (v3.8.2).
* Your issue is most likely caused by a 3rd party plugin, server, or WordPress configuration.

https://user-images.githubusercontent.com/113993460/205896907-0baa2e5d-cbf2-4ff7-b661-fb6836768b92.mp4

### ✅ What you can do to solve your issue:
* Test with other plugins deactivated, especially 3rd party add-ons.
* Log out from your WordPress Dashboard, clear your browser cache, and log in again.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
