### ISSUE TITLE
⛔ 🚀 Feature Request: Improve Import/Export feature to include Library Templates thumbnails

### ISSUE THREAD

**Issue by oooh-boi** [elementor/elementor#20596]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

`/elementor/includes/template-library/sources/local.php`, line 259 
says that the "thumbnail" feature of "elementor_library" CPT is supported, and we can see the Featured Image panel in the WordPress post edit screen, however, the thumbnail we add is never been exported with any template. 

As far as I can see `prepare_template_export( $template_id )` method does not include any kind of meta-data (including "_thumbnail_id") to the export: 

```
		$export_data = [
			'content' => $template_data['content'],
			'page_settings' => $template_data['settings'], 
			'version' => DB::DB_VERSION,
			'title' => $document->get_main_post()->post_title,
			'type' => self::get_template_type( $template_id )
		];
```
...which implies that the "thumbnail" feature is completely futile! 

The same goes for the `import_single_template( $file_path )` method!

### Describe the solution you'd like

We are dealing with templates and if no visual representation of the template is available it's very difficult for anyone to effectively use them. A Featured Image (aka Thumbnail) is a great way to improve the workflow. Currently, we can use the "View" button on the list of saved templates (WP Admin table) but that's like a 19th-century feature. 

Please either allow a hook to `prepare_template_export( $template_id )` method or at least add the option to export the `_thumbnail_id` meta with export_data. I stress that the "elementor_library" CPT already supports "thumbnail" feature: 
```
		$export_data = [
			'content' => $template_data['content'],
			'page_settings' => $template_data['settings'], 
			'version' => DB::DB_VERSION,
			'title' => $document->get_main_post()->post_title,
			'type' => self::get_template_type( $template_id ), 

			'thumb_id' => get_post_thumbnail_id( $template_id )

		];
```

Of course, this implies the import side of the template too, `the import_single_template( $file_path )` method: 
```
	        $template_id = parent::save_item( [
			'content' => $content,
			'title' => $data['title'],
			'type' => $data['type'],
			'page_settings' => $page_settings, 

                        '_thumbnail_id' => $data['thumb_id']

		] );
```

Thank you!

### Describe alternatives you've considered

I've tried to monkey patch Elementor\TemplateLibrary\Source_Local but this is just not the right way of doing it.

### Additional context

-----

**Comment by nicholaszein** [comment]
Hello @oooh-boi, Nice to see you around here!

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

If you think this is something you can contribute, please submit a PR and we will gladly review it and try to implement it!

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
