### ISSUE TITLE
⛔ 🚀 Feature Request: Scheduled Dynamic Content on Single URL Updated Daily — With the Ability to Click Hyperlinks on Page

### ISSUE THREAD

**Issue by jogithubb** [elementor/elementor#20591]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm frustrated that I can't offer my users new scheduled content each day via a consistent URL in a way that they can click hyperlinks in the content.

### Describe the solution you'd like

I want to offer my users a page that contains new scheduled content each day via the same URL, and I want to be able to schedule this content in advance so it automatically changes at midnight each day. "Go to [URL] to see our scheduled daily quote," that kind of thing. 

### Describe alternatives you've considered

I've seen a few add-on plugins that offer this feature (along with 40+ extra features), but I don't want to add another plugin to my site and have it load even slower than it does. 

Right now I am using the post widget with full content selected — and to only show the latest single post at a time. But this option doesn't allow users to click hyperlinks because it's the archive view, which is a dealbreaker.

**Comment by jogithubb** [comment]
The more I read about this, the more I realize that I might be looking for what I guess is termed "visibility logic"?

I'm just looking to create a mobile experience where scheduled content automatically changes daily for those who go to a certain URL.

**Comment by nicholaszein** [comment]
Hello @jogithubb,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
