### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Popup "Entire Site" doesn't work for Order Pay endpoint

### ISSUE THREAD

**Issue by rtpHarry** [elementor/elementor#20605]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The order-pay endpoint doesn't seem to have the scripts included for JetPopup, with 'entire site' as the condition.

This is the screen when you make an unpaid order, eg with a phone order made in the backend, and the customer then goes to it to make the payment.

There is no better condition that targets it, so the best that can be done is to use the 'entire site' condition.

If you look in the source, the markup for the popup is there. but the trigger doesn't work.

In my scenario I had put in a custom written plugin, to inject a policy checkbox. The description of the checkbox had a link to a policy which must be accepted. The link to the policy had a custom class. 

The popup is set to be triggered by a custom selector.

The same template is used on the normal checkout, and the order-pay version of the checkout, so the code runs and the checkbox is there on the page.

On the normal checkout the popup works when the policy link is clicked. 

On the order-pay checkout, the popup doesn't work.

### Steps to reproduce

1. Create a popup, with a certain unique word in it (eg apples)
2. Set it's display condition to entire site
4. Make a woo order that is unpaid
5. Go to the order pay screen for that order eg https://example.com/checkout/order-pay/16849/?pay_for_order=true&key=wc_order_Ama6GsNSXf9Qb# (get to it by going to My Account > Orders > and clicking Pay on the unpaid order)
6. Try to trigger the popup
7. For me, I was using a custom policy checkbox with a class and the selector trigger option, but for testing you can simply view source and search for "apples" and see that the markup is in the source code, but it is not triggered and displayed
8. Test the same thing by going to the real/normal checkout and clicking it, then it is displaying the popup

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

`
### WordPress Environment ###

WordPress address (URL): https://knepp.sokastudio.dev
Site address (URL): https://knepp.sokastudio.dev
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 6000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.40-log-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_
Total Database Size: 212.25MB
Database Data Size: 176.52MB
Database Index Size: 35.73MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 8.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.66MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
wp_addonlibrary_addons: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aryo_activity_log: Data: 1.16MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.22MB + Index: 0.55MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.25MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jckwds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_rel_default: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lecm_rewrite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 19.03MB + Index: 0.33MB + Engine InnoDB
wp_pmxe_exports: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 57.27MB + Index: 11.03MB + Engine InnoDB
wp_posts: Data: 51.47MB + Index: 1.38MB + Engine InnoDB
wp_redirection_404: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 5.52MB + Index: 7.03MB + Engine InnoDB
wp_users: Data: 0.33MB + Index: 0.42MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.36MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.52MB + Index: 0.47MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.28MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 13.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.30MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpo_wcpbn_batch_numbers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.50MB + Index: 0.63MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.30MB + Index: 0.17MB + Engine InnoDB

### Post Type Counts ###

acf-field: 6
acf-field-group: 1
attachment: 1313
aw_workflow: 34
bookable_person: 1
customize_changeset: 4
elementor_library: 26
elementor_snippet: 1
global_product_addon: 2
jet-engine: 8
jet-menu: 7
jet-popup: 4
jet-woo-builder: 23
job: 3
nav_menu_item: 96
oembed_cache: 5
page: 138
pewc_field: 1
pewc_group: 1
post: 84
product: 171
product_variation: 388
recipes: 9
revision: 6745
shop_coupon: 447
shop_order: 4713
shop_order_refund: 6
tablepress_table: 3
team-member: 42
wc_booking: 233
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Unlimited Elements for Elementor (Premium): by Unlimited Elements – 1.5.43
Advanced Custom Fields PRO: by WP Engine – 6.0.5
Activity Log: by Activity Log Team – 2.8.5
Astra Pro: by Brainstorm Force – 3.9.4
AutomateWoo: by WooCommerce – 5.6.0
Cachebuster: by Albert Peschar – 1.3
Disable User Login: by Saint Systems – 1.3.3
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Duplicator Pro: by Snap Creek – 4.5.8.3
Elementor Pro: by Elementor.com – 3.9.0
Elementor: by Elementor.com – 3.9.0
ElementsKit Lite: by Wpmet – 2.7.5
Products & Order Export for WooCommerce: by WPWhale – 2.0
Flexible Shipping: by Octolize – 4.17.0
WooCommerce Delivery Slots by Iconic: by Iconic – 1.18.0
JetBlocks For Elementor: by Crocoblock – 1.3.5
JetEngine - Custom visibility conditions: by Crocoblock – 1.0.0
JetEngine - Repeater field values: by Matthew Harris
runthings.dev – 1.1.1

JetEngine - Trim string callback: by Crocoblock – 1.0.0
JetEngine: by Crocoblock – 3.0.8
JetMenu: by Crocoblock – 2.2.4
JetPopup: by Crocoblock – 1.6.3
JetTricks: by Crocoblock – 1.4.3
JetWooBuilder - Category Custom Product Template: by Matthew Harris
runthings.dev – 1.2.0

JetWooBuilder For Elementor: by Crocoblock – 2.1.0
Mailgun: by Mailgun – 1.8.7
MainWP Child: by MainWP – 4.3.0.1
Premium Addons for Elementor: by Leap13 – 4.9.42
Redirection: by John Godley – 5.3.5
Knepp Custom Checkout Question - 12+ Confirmation: by Matthew Harris
runthings.dev – 1.2.1

Current Year Shortcode: by Matthew Harris
runthings.dev – 1.1.0

WooCommerce Accommodation Bookings: by WooCommerce – 1.1.36
WooCommerce Bookings Availability: by WooCommerce – 1.1.24
WooCommerce Bookings: by WooCommerce – 1.15.68
DPD UK & DPD Local Labels and Tracking: by Octolize – 1.13.0
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Knepp Accommodation Bookings: by Matthew Harris
runthings.dev – 1.3.0

WooCommerce Print Order List: by WP Overnight – 1.9.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.5
WooCommerce Product Add-ons: by WooCommerce – 5.0.2
WooCommerce Product Batch Numbers: by WP Overnight – 1.8.0
WooCommerce Shipping & Tax: by WooCommerce – 2.1.0
WooCommerce Store Credit: by Themesquad – 4.2.4
WooCommerce: by Automattic – 7.1.1
Wordfence Security: by Wordfence – 7.8.0
WordPress Importer: by wordpressdotorg – 0.8
Yoast SEO: by Team Yoast – 19.11
WP All Export Pro: by Soflyy – 1.8.1
WP All Import Pro: by Soflyy – 4.7.8
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.5
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.4

### Inactive Plugins (3) ###

CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.6
LiteSpeed Cache: by LiteSpeed Technologies – 5.3
Really Simple SSL: by Really Simple Plugins – 6.0.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
store_credit (store_credit)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #639 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #7544 - /legal/terms-of-use/

### Theme ###

Name: Knepp
Version: 1.0.0
Author URL: https://sokastudio.co.uk/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 3.9.4
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/form-checkout.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/thankyou.php
knepp/woocommerce/emails/customer-new-account.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/dashboard.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/downloads.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/form-edit-account.php version 3.5.0 is out of date. The core version is 7.0.1
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/form-login.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/my-account.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/my-address.php
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.0.1
/home/sokadev/knepp.sokastudio.dev/wp-content/plugins/jet-woo-builder/templates/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-10 16:48:19 +00:00
Options: ✔
Notes: 89
Onboarding: completed

### Action Scheduler ###

Complete: 1,460
Oldest: 2022-11-09 15:41:13 +0000
Newest: 2022-12-10 08:50:04 +0000

Pending: 5
Oldest: 2022-12-10 11:23:00 +0000
Newest: 2023-01-01 07:40:06 +0000

### Store Credit ###

Prices entered with tax: yes
Show My Account: yes
Delete after use: yes
Individual use: no
Include tax: no
Apply to shipping: yes
Coupon code format: {coupon_code}
Overrides: -

### Status report information ###

Generated at: 2022-12-10 11:21:30 +00:00
`

**Comment by nicholaszein** [comment]
Hey @rtpHarry, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Description:** you did not provide a detailed description and examples of your issue;
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

😕 We need this information to be able to reproduce your issue. Without it, we have no way to help you.

Please update your original post with the missing information.

**Comment by rtpHarry** [comment]
ive updated the post a few weeks ago - do i need to comment to trigger this being revisited?

**Comment by nicholaszein** [comment]
Hello @rtpHarry,

sorry for the delay, I had to make sure the issue wasn't caused by Elementor.

In your description of your issue, you mentioned JetPopups. Can you confirm you're using JetPopups to load the popup, not Elementor? Because for us, it works as expected with native Elementor Popups. All we had to do was to use the following conditions:


https://user-images.githubusercontent.com/113993460/209768984-311df20e-6abf-4f21-91de-699c3bad4fa2.mp4


This seems like either an issue of you not adding the correct conditions, or you're not using a native Elementor feature, which in this case we can't help you, and you should contact the 3rd-party Add-on support instead.

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

Regards
