### ISSUE TITLE
⛔ 🚀 Feature Request: Width field in Elementor editor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20600]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team

I wanted to say something about width fields in Elementor...

Currently, when we add a widget, in the advanced tab, the widget width option has 4 options.
- default
- full width (100%)
- inline (auto)
- custom

But is there any necessity to display these 4 options in the width field? Why isn't there just a simple field to enter the width value? 

### Describe the solution you'd like

![width](https://user-images.githubusercontent.com/77163248/205458259-02eff11f-aeac-42e1-8828-dbdccbf23db9.png)

Instead of the current option, just add a simple field to enter the width. Using this simple field, we can control all 4 situations mentioned above.

- default > empty
- full width > 100%
- inline (auto) > This option is not needed in the container.
- custom > -

So, aren't the current options unnecessary?

**Comment by Michaelgimii** [comment]
I am agree too. There should be everything like simple but professional bricks builder.

![bricks](https://user-images.githubusercontent.com/88034902/205458513-6e90d1a5-5c3e-46e7-ae1b-c78733927ea9.png)

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thanks for raising this question! It's a great question and an opportunity for us to discuss it! 🙏 

This is for backward compatibility, and these options are still relevant and useful for different scenarios.

We currently have no plans to change this feature because of these reasons.

Thanks for raising this question though,

Kind regards
