### ISSUE TITLE
⛔ 🚀 Feature Request: Loop the Countdown widget animation after a defined set of time

### ISSUE THREAD

**Issue by CordialGit** [elementor/elementor#20611]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Normally, Elementor Counter Widget counts on page load, then stops.

It remains static forever until the page is reloaded.

It's frustrating just seeing the number counter like a dead lifeless element.  Then I saw the implementation here-- https://www.youtube.com/watch?v=d9QExKb8x5g

On WordPress Repo, here’s the link— https://wordpress.org/plugins/countdown-wpdevart-extended/

**IN ESSENCE**
In essence, I’m asking if Elementor Counter can be made to have a Recurrent Loop Feature– where we can set the Counter to repeat infinitely, after about 5 seconds and so on, without the need for Page reload.

### Describe the solution you'd like

I would like to be able to set the Counter to repeat infinitely, after about 5 seconds and so on, without the need for Page reload.

### Describe alternatives you've considered

For now, this--- https://www.youtube.com/watch?v=d9QExKb8x5g

or this— https://wordpress.org/plugins/countdown-wpdevart-extended/

---- are the alternatives I've tried.

**Comment by nicholaszein** [comment]
Hello @CordialGit,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

The **Countdown** widget (not to be confused with the Counter widget), which seems what you're talking about, already has an Evergreen Timer, which reloads the Countdown after the page is reloaded. For now, we do not have plans to implement the loop feature without the page reload.

You can learn more about the Countdown widget (Pro) and the Evergreen feature in [this article](https://elementor.com/help/countdown-widget-pro/).

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
