### ISSUE TITLE
🔀 🚀 Feature Request: VideoPress integration for self-hosted videos (PR #20569)

### ISSUE THREAD

**Issue by thedebian** [elementor/elementor#20617]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

When using VideoPress, video widget with self-hosted media are not rendered correctly.
The self-hosted link will grab the video URL when it should use the streaming playlist and the VideoPress player.
We also can't paste VideoPress URLs as external URLs.

### Describe the solution you'd like

When using a video widget and selecting a VideoPress video from the media library, the VideoPress player should be used instead of a video tag with the video URL.
When using a video widget and pasting a VideoPress URL in self-hosted "External link", the result should be the same.

### Describe alternatives you've considered

The only solution right now is to use the Gutenberg block editor.

### Additional context

A PR with proposed changes is available here #20569

**Comment by nicholaszein** [comment]
Thanks for the feedback @thedebian! 🙏 

I'll let the team know there is a PR for this issue, but I'm not sure this is something we are looking to implement for the time being due to the nature of the feature relying on 3rd parties to work. I hope you can understand.

Nevertheless, thanks for your submission! 🙏

**Comment by thedebian** [comment]
@nicholaszein I forgot to mention, I first wanted to integrate VideoPress the same way Vimeo or Youtube is integrated in the video widget, but, as it would consist of replicating what the self-hosted type is doing, I did it that way.
If it's a blocker just because it's in the self-hosted part, I see no problem updating the PR to add a new type like Vimeo or Youtube

**Comment by thedebian** [comment]
Hey @nicholaszein, 
It shouldn't be required, as the player is iframed.

For a brief overview of how it works:
* A user has either a Jetpack VideoPress subscription or is on any paid plan on WordPress.com
* When they upload a video, the video goes to our servers and gets transcoded to different formats, but it still appears as a local video on the user's site and media library
* When they want to embed the video, they can either add a video block in Gutenberg that'll get translated to a VideoPress player iframe, hosted on videopress.com or video.wordpress.com
* A user without a subscription can still embed public videos by adding a shortcode or iframing the video player directly.
 
So it pretty much works like embedding a Youtube or Vimeo video, the only difference being its tight integration to the WordPress media library (and transparent for users with a paid plan on WordPress.com).

**Comment by watoft** [comment]
Hi,
When using Elementor in Wordpress, I would like to add a video (self-hosting Jetpack) by including the Video code as saved inside my Jetpack. This would be in the same way as I add the YouTube URL. Thi of  course works. 
If this feature is not available, can it be added? Warren

**Comment by nicholaszein** [comment]
Hello there @thedebian!

Apologies for the delay. 🙏 

If you haven't already noticed, support for VideoPress videos in the Video widget was added to Elementor in version 3.17.0.

Thank you for sharing your request, and for being so patient! 🙏 

Kind regards
