### ISSUE TITLE
🔗 ⛔ 🚀 Feature Request: Allow to Choose Post Types in the Template Type select field in the Loop Grid (Related to #20648)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20649]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In the Loop Grid widget, the Choose template type section shows only two options, posts and products. **But shouldn't the pages and custom post type be displayed in this section?**

Instead, these two options will be displayed in the Query tab > Source when we select the Posts option in the Choose template type section. This seems to be a wrong method.

![2](https://user-images.githubusercontent.com/77163248/206160287-f23fd8e4-fed0-4f43-a885-b7d11a90da2b.png)

### Describe the solution you'd like

The pages option and even custom post types (if we have a custom post type) should be displayed in the Choose template type section.

![3](https://user-images.githubusercontent.com/77163248/206161601-74d638c2-885c-42ae-9999-a988649f30f8.png)

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

The option to choose the Template Type in the Loop Grid does not define the type of post to query. Only the Type of template to Display. If you select Posts, it allows you to display templates for post type normally as you would usually do. If you select Products, it would allow you to display templates for Products, which are different and have special components that need to be rendered differently.

I think the answer I gave to you in [this comment](https://github.com/elementor/elementor/issues/20648#issuecomment-1340928715) covers both this issue and issue #20648, better.

For this reason, I'll be closing this issue and we can discuss this topic there if that's ok with you.

Kind regards
