### ISSUE TITLE
[⌛ Awaiting Feedback] ❓ Question: npm install fails on fsevents

### ISSUE THREAD

**Issue by Djennez** [elementor/elementor#20646]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi all, after yesterdays 3.9.0 release, some of our automations that use Elementor started failing. After some investigation, it looks like `npm install` may fail if the following conditions are met.

- The OS is **not** darwin (Mac OS)
- The NPM version is lower than 16.

We're seeing the following errors:

```
root@bc58167298f0:/var/www/html/elementor# npm i
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

This happens in a Linux Docker container with either `nvm use 12` or `nvm use 14`. Running `nvm use 16` and then trying the install works without problems. We're seeing the same on Windows OS, but not on Mac.

I was unable to verify that Elementor has upped their minimum required NPM version to 16+, hence this report.

Please let me know if I'm doing something wrong (aside from using older NPM versions) or if NPM 16 is now the minimum required version for Elementor

### Steps to reproduce

1) Use NVM to set a NPM version lower than 16 on a non-MacOS system.
2) Try to run `npm i` on a fresh elementor clone.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

```
root@bc58167298f0:/var/www/html/elementor# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by nicholaszein** [comment]
Hello @Djennez! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hey @Djennez!

I just talked to the guys from the team, and they confirmed the requirements were updated.

You can use [Node Version Manager](https://github.com/nvm-sh/nvm) if you want (as you are) to manage the version. It should be the latest.

As for the OS, you can use any OS you'd like. Try updating Node and see if the issue with the OS is fixed.

I hope this answers your question. Please let me know. 🙏

**Comment by Djennez** [comment]
@nicholaszein thanks! We will switch our npm version to be able to build Elementor.

Since I was unable to find the updated (minimum) requirements somewhere; might I suggest that this gets added to your docs somewhere? That might assist future users.

Again thanks for the confirmation!

**Comment by nicholaszein** [comment]
Thanks for the feedback @Djennez! And apologies for taking so long to get back to you. 🙏

I'll send the feedback to the team responsible for maintaining the developer documentation.

Have a happy new year! 🥂
