### ISSUE TITLE
⛔ 🚀 Feature Request: Have more than just Container element

### ISSUE THREAD

**Issue by nerdtech** [elementor/elementor#20655]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

With the introduction of Flexbox in Elementor we now have the "container" element. However containers can have different purposes and also meanings in semantic HTML.

For example a "section" HTML element serves the purpose of separating topical content on a page, whereas a div can be a plain non styled holder for various other elements.

While you can add a html tag to containers in Elementor it would be handy if this would be added automatically for containers you intend to use as a section for example.

### Describe the solution you'd like

Have more than just a "container" element. Have elements that already have the appropriate tags already added with some preset properties when you drag them to the Elementor canvas. This would improve and speed up your workflow.

Which elements would I suggest?

Section element - section html tag added - flex - 100% full width

Container - div html tag - flex - a specified set width

Block (can serve as a column) - div html tag - flex - 100% width

Div - div html tag - block - no set width and un-styled

Hope that makes sense.

Thanks.

**Comment by nicholaszein** [comment]
Hello @nerdtech,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Elementor containers work differently from other builders, and having multiple widgets generates unnecessary overlap, which causes confusion. The container covers all of the options above within the Elementor environment which is very different from other builders in many aspects. We also have to account for backward compatibility, which other builders don't have to worry about. Changing the entire structure is not an option. I hope you can understand.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
