### ISSUE TITLE
⛔ 🐞 Bug Report: Opyacare.com Cont page appears broken in live, but in editor looks fine

### ISSUE THREAD

**Issue by Opyacare1** [elementor/elementor#20666]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Opyacare.com Contact Us page, when viewing from the browser appears broken, the menu is separated, big red X is where the image should be. But, in the editor and preview, everything looks normal.

### Steps to reproduce

visit www.opyacare.com/contactus there you will see the"issue"

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 8.0.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.opyacare.com
	Home URL: https://www.opyacare.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: techsupport@opyacare.com
	Debug Mode: Inactive

== Theme ==
	Name: Dreamscape Customify Child
	Version: 1.1.0
	Author: Dreamscape Media
	Child Theme: Yes
	Parent Theme Name: Customify
	Parent Theme Version: 0.4.0
	Parent Theme Author: WPCustomify

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

== Active Plugins ==
	AddToAny Share Buttons
		Version: 1.8.5
		Author: AddToAny

	Akismet Anti-Spam
		Version: 5.0.2
		Author: Automattic

	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	CallTrackingMetrics
		Version: 1.2.11
		Author: CallTrackingMetrics

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Customify Pro
		Version: 0.1.6
		Author: WPCustomify

	Elementor
		Version: 3.10.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-dev1
		Author: Elementor.com

	Exclude Pages From Menu
		Version: 3.0
		Author: Vinod Dalvi

	Genesis Blocks
		Version: 1.5.3
		Author: StudioPress

	Gravity Forms
		Version: 2.6.8
		Author: Gravity Forms

	Gravity Forms Event Tracking
		Version: 2.4.14
		Author: Ronald Huereca

	Gravity Forms HubSpot Add-On
		Version: 1.8
		Author: Gravity Forms

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 9.2.12
		Author: HubSpot

	Intercom
		Version: 2.6.5
		Author: Intercom

	Performance Lab
		Version: 1.7.0
		Author: WordPress Performance Team

	PowerPack Lite for Elementor
		Version: 2.7.0
		Author: IdeaBox Creations

	Redirection
		Version: 5.3.5
		Author: John Godley

	Simple Custom CSS and JS
		Version: 3.41
		Author: SilkyPress.com

	Site Kit by Google
		Version: 1.89.0
		Author: Google

	The Plus Addons for Elementor
		Version: 5.1.15
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.0.10
		Author: POSIMYTH

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.9
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPCode Lite
		Version: 2.0.4.4
		Author: WPCode

	WP Engine Smart Plugin Manager
		Version: 5.13.5
		Author: WP Engine

	WP External Links
		Version: 2.56
		Author: WebFactory Ltd

	WP Sitemap Page
		Version: 1.9.2
		Author: Tony Archambeau

	Yoast SEO
		Version: 19.11
		Author: Team Yoast

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.1.0
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.0
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

== Elements Usage ==
	
	footer : 1
		animated-headline : 1
		gallery : 1
		heading : 1
		image : 3
		nav-menu : 1
		social-icons : 1
		spacer : 1
		text-editor : 5
	page : 6
		animated-headline : 5
		blockquote : 1
		button : 52
		divider : 2
		flip-box : 6
		form : 1
		google_maps : 2
		heading : 178
		html : 2
		hubspot-form : 2
		icon : 32
		icon-list : 2
		image : 94
		image-carousel : 7
		menu-anchor : 3
		nav-menu : 6
		post-info : 1
		post-navigation : 1
		posts : 2
		share-buttons : 1
		slides : 1
		social-icons : 2
		spacer : 7
		testimonial-carousel : 4
		text-editor : 204
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
		toggle : 1
		tp-gravityt-form : 5
		video : 2
		wp-widget-categories : 1
		wp-widget-gform_widget : 2
	popup : 7
		heading : 7
		text-editor : 7
	section : 10
		animated-headline : 2
		breadcrumbs : 1
		button : 2
		heading : 6
		image : 8
		search-form : 1
		social-icons : 1
		text-editor : 8
		theme-post-title : 1
		tp-gravityt-form : 1
	wp-page : 39
		animated-headline : 5
		button : 22
		gallery : 1
		google_maps : 2
		heading : 97
		hubspot-form : 1
		icon-box : 3
		image : 29
		image-box : 7
		image-carousel : 3
		nav-menu : 2
		social-icons : 2
		spacer : 6
		testimonial-carousel : 3
		text-editor : 131
		tp-gravityt-form : 2
		video : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active by default
	Save as Default: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 11 of 11PHP: 2022-11-08 13:14:20 [notice X 4985][/nas/content/live/opyaproduction/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-11 10:18:19 [warning X 12][/nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::748] A non-numeric value encountered [array (
  'trace' => '
#0: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php(748): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /nas/content/live/opyaproduction/wp-includes/class-wp-hook.php(309): class type bfi_image_resize_dimensions()
#2: /nas/content/live/opyaproduction/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
#3: /nas/content/live/opyaproduction/wp-includes/media.php(556): class type apply_filters()
#4: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php(490): class type image_resize_dimensions()
',
)]
PHP: 2022-11-11 10:18:19 [warning X 6][/nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::750] A non-numeric value encountered [array (
  'trace' => '
#0: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php(750): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /nas/content/live/opyaproduction/wp-includes/class-wp-hook.php(309): class type bfi_image_resize_dimensions()
#2: /nas/content/live/opyaproduction/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
#3: /nas/content/live/opyaproduction/wp-includes/media.php(556): class type apply_filters()
#4: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php(490): class type image_resize_dimensions()
',
)]
PHP: 2022-11-11 10:18:19 [warning X 6][/nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::751] A non-numeric value encountered [array (
  'trace' => '
#0: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php(751): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /nas/content/live/opyaproduction/wp-includes/class-wp-hook.php(309): class type bfi_image_resize_dimensions()
#2: /nas/content/live/opyaproduction/wp-includes/plugin.php(191): WP_Hook -> apply_filters()
#3: /nas/content/live/opyaproduction/wp-includes/media.php(556): class type apply_filters()
#4: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php(490): class type image_resize_dimensions()
',
)]
PHP: 2022-11-15 04:38:10 [warning X 12][/nas/content/live/opyaproduction/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-15 05:43:31 [warning X 13][/nas/content/live/opyaproduction/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 08:49:39 [error X 1][/nas/content/live/opyaproduction/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /nas/content/live/opyaproduction/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /nas/content/live/opyaproduction/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /nas/content/live/opyaproduction/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /nas/content/live/opyaproduction/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /nas/content/live/opyaproduction/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /nas/content/live/opyaproduction/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /nas/content/live/opyaproduction/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 06:07:43 [warning X 3][/nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined array key 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-23 05:05:57 [notice X 93][/nas/content/live/opyaproduction/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /nas/content/live/opyaproduction/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /nas/content/live/opyaproduction/wp-content/plugins/theplus_elementor_addon/modules/theplus-integration.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-11-23 17:22:31 [notice X 157][/nas/content/live/opyaproduction/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-06 08:13:47 [warning X 48][/nas/content/live/opyaproduction/wp-content/plugins/elementor/includes/template-library/sources/local.php::1031] Attempt to read property "post_type" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-11-08 22:35:27 [error X 51][https://www.opyacare.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:1061529] null is not an object (evaluating \'$.getBoundingClientRect\') 
JS: 2022-11-10 18:19:46 [error X 11][https://www.opyacare.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.8.0:2:4824] undefined is not an object (evaluating \'e.attributes\') 
JS: 2022-11-10 18:19:53 [error X 16][https://www.opyacare.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:634187] elementorFrontend.elements.window.jQuery is not a function. (In \'elementorFrontend.elements.window.jQuery(T.el)\', \'elementorFrontend.elements.window.jQuery\' is undefined) 
JS: 2022-11-10 20:03:42 [error X 1][https://www.opyacare.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:768951] undefined is not an object (evaluating \'T.originalEvent.key.toLowerCase\') 
JS: 2022-11-17 17:35:32 [error X 4][https://www.opyacare.com/wp-content/plugins/elementor/assets/lib/e-gallery/js/e-gallery.min.js?ver=1.2.0:2:11156] undefined is not an object (evaluating \'n.ratio\') 
JS: 2022-11-18 23:12:21 [error X 2050][https://www.opyacare.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19667] null is not an object (evaluating \'this.getColorRepresentation().toLowerCase\') 
JS: 2022-12-08 01:51:50 [error X 12][https://www.opyacare.com/wp-content/plugins/elementor/assets/js/lazyload.min.js?ver=3.10.0-dev1:2:332] undefined is not an object (evaluating \'o.classList.add\') 

Log: showing 20 of 242022-11-09 03:00:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-14 00:03:38 [info] elementor::elementor_updater Started 
2022-11-14 00:03:38 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-14 00:03:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-14 00:03:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-14 00:03:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-22 22:46:53 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-11-22 22:46:53 [info] elementor-pro::elementor_pro_updater Started 
2022-11-22 22:46:53 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-22 22:46:53 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-22 22:46:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-11-23 13:51:56 [info] elementor::elementor_updater Started 
2022-11-23 13:51:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-23 13:51:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-23 13:51:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-23 13:51:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-23 13:54:16 [info] elementor-pro::elementor_pro_updater Started 
2022-11-23 13:54:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-23 13:54:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-23 13:54:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.10.0-dev1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	PowerPack Lite for Elementor: Compatibility not specified
	The Plus Addons for Elementor: Compatibility not specified
	The Plus Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @Opyacare1,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* You have multiple performance optimization solutions that might not have cleared their cache after you've updated to v3.9.0.
* ⚠️ This is more of a Support question, not something we can help you with.

### ✅ What you can do to solve your issue:
* Clear your cache.
* Contact Elementor Support.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
