### ISSUE TITLE
🐞 Bug report: Using Dark Mode in Elementor turns Media Library Buttons invisible

### ISSUE THREAD

**Issue by clmnsm** [elementor/elementor#20672]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using Dark Mode or Auto Detect in Elementor, some buttons in the Media Library popup turn invisible when not hovered/selected.

This also happens on an empty install using only Elementor + Pro.

The issue seems to be that dark mode overrides the system color "buttontext" which is also used in the core media library.

### Steps to reproduce

1. Use Elementor in dark mode
2. Add an image element and open the media library popup
3. Either "Upload Files" or "Media Library" tabs will be invisible.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 20.04 v10.3.37
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1

== Active Plugins ==
	Elementor
		Version: 3.9.0
		Author: Elementor.com


== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team
```

**Comment by nicholaszein** [comment]
Hello @clmnsm! 

Thank you for submitting your issue! 🙏 

We are aware of this issue and a fix will be introduced in one of the next versions!

Best regards

**Comment by arielk** [comment]
Fix by https://github.com/elementor/elementor/pull/20688
