### ISSUE TITLE
🚧 🐞 Bug Report: Landing Page Experiment is BREAKING the WordPress old slug redirect causing 404 errors impacting SEO

### ISSUE THREAD

**Issue by tibvee** [elementor/elementor#20679]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After installing the last version of Elementor (as of 09/12/2022), I started seeing many 404 erros in the Google Search Console.
Google started DEINDEXING many of my posts.

I discovered that Elementor BROKE the Wordpress function that automatically redirect an old slug to a new slug when someone choose to change the slug in an article. Default WordPress behavior is to store EVERY old slug in the post_metadat table in the DB, and AUTOMATICALLY redirect 301 any crawl to this old slug to the new slug. This features allow Google to reindex the new slug and keep the SEO ranking of the OLD slug.

BUT ! When using elementor, this feature breaks and the OLD SLUG url returns a 404 error, preventing Google to see any 301 redirect from the old url to the new url, causing your webpage to loose its ranking !

After making some tests, I discovered the problem can be solved by DISABLING the EXPERIMENT calle "Landing Page" under the EXPERIMENT tab.

Enabling it breaks all the 301 redirects
Disabling it solved the issue.

Could you please fix this, and prevent this bug to spread to other features ?
I would hate to see this problem coming back in the next updates and discovered it several days after in the google search console.

### Steps to reproduce

1- Activate last version of elementor
2- Activate ALL the EXPERIMENTS under the "EXPERIMENT" tab.

(To solve the problem, I disable the experiment called "landing page", the 5th before the end).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

php 7.4
LAMP

**Comment by nicholaszein** [comment]
Hey @tibvee, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Isolating the Problem:** You need to make sure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Without them, we simply can't reproduce your issue with precision. 😕 

👉 Please always follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.
Best regards,

Nick

**Comment by nicholaszein** [comment]
Hello @tibvee,

I'm still trying to reproduce your issue, but I can't do it without the missing information. Can you please add the missing information so we can help you?

Thanks 🙏

**Comment by tibvee** [comment]
Hello,
We do not use the Hello theme, but the GeneratePress theme. Anyway I tried with the TwentyXXXX default themes from WordPress and the issue did happen.

Our system is LAMP with php 7.4

Best regards

**Comment by tibvee** [comment]
Mopre on the infrastructure : 
- WEB VPS server on OVH
- PHP 7.4
- MySQL 5.7

I tested the issue with all the THEMES I had (Twenty Twenty-One, Twenty Twenty-Three)

I also disabled ALL plugins... in Fact I HAD to do this to find out which plugin caused the issue.  I activated/deactivated plugins 1 by 1 to isolate the issue coming from ELEMENTOR. 

We also use Jetpack with AKISMET and VaultPRess but I don't think it has anything to do with it.

Finally, as the issue impact 301 redirects, maybe you'll find usefull to see our htaccess file:
# BEGIN WordPress
# Les directives (lignes) entre « BEGIN WordPress » et « END WordPress » sont générées
# dynamiquement, et doivent être modifiées uniquement via les filtres WordPress.
# Toute modification des directives situées entre ces marqueurs sera surchargée.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

# BEGIN Trellis
<IfModule mod_gzip.c>
	mod_gzip_on Yes
	mod_gzip_dechunk Yes
	mod_gzip_item_include file .(html?|txt|css|js|php|woff|woff2|pl)$
	mod_gzip_item_include handler ^cgi-script$
	mod_gzip_item_include mime ^text/.*
	mod_gzip_item_include mime ^application/x-javascript.*
	mod_gzip_item_exclude mime ^image/.*
	mod_gzip_item_exclude rspheader ^Content-Encoding:.*gzip.*
</IfModule>
<IfModule mod_expires.c>
	ExpiresActive On
	ExpiresByType image/jpg "access 1 year"
	ExpiresByType image/jpeg "access 1 year"
	ExpiresByType image/gif "access 1 year"
	ExpiresByType image/png "access 1 year"
	ExpiresByType image/webp "access 1 year"
	ExpiresByType font/woff "access 1 year"
	ExpiresByType font/woff2 "access 1 year"
	ExpiresByType text/css "access 1 month"
	ExpiresByType application/pdf "access 1 month"
	ExpiresByType text/x-javascript "access 1 month"
	ExpiresByType application/x-shockwave-flash "access 1 month"
	ExpiresByType image/x-icon "access 1 year"
	ExpiresDefault  "access 1 month"
</IfModule>
<IfModule mod_headers.c>
	<filesmatch "\.(ico|flv|jpg|jpeg|png|gif|css|swf|webp|woff|woff2|js)$">
	Header set Cache-Control "max-age=31536000, public"
	</filesmatch>
</IfModule>
# END Trellis

**Comment by nicholaszein** [comment]
Hello @tibvee,

can you please provide the **System Info** as requested? Without it, we can't validate or reproduce your issue. Please follow the video guide below, download the System Info, and edit/update your original post with the missing information.

https://www.youtube.com/watch?v=tDXdynsnYuA


![image](https://user-images.githubusercontent.com/113993460/210126649-3b892faa-2fc0-4cf6-9ea2-d5b452e12e1d.png)
