### ISSUE TITLE
❌ Elementor account login broken – Cannot activate pro license

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#20723]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,

For multiple days I am trying to login and activate a site.
The login page is not working on the my elementor portal.
the social login keeps spinning and once we press login it just refreshes the current page.

This is also a JS error in console: Uncaught SyntaxError: Invalid or unexpected token on line login.js:17

Please fix this asap

### Steps to reproduce

Go to the elementor my account page and try to login.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

/

**Comment by nicholaszein** [comment]
Hello @Webtica

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
