### ISSUE TITLE
❓ API Question: How to inject custom control in Popup "Advanced Rules"

### ISSUE THREAD

**Issue by aFluxx** [elementor/elementor#20724]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm trying to add language display option compatibility for Polylang within the Popup Advanced Rules. Preview:
https://i.gyazo.com/84c2359e9b1126fcb6be6a7425be2966.png

The code is already written, I just need to be able to add this to `/elementor-pro/modules/popup/display-settings/timing.php`
```
$this->start_settings_group('polylang', esc_html__('Show in languages', 'elementor-pro'));

$languages = pll_languages_list();
$languageOptions = [];

foreach ($languages as $key => $lang) {
    $languageOptions[$lang] = $lang;
}

$this->add_settings_group_control(
	'active_languages',
	[
		'type' => Controls_Manager::SELECT2,
		'multiple' => true,
		'default' => array_values($languages),
		'options' => $languageOptions,
	]
);

$this->end_settings_group();
```

### Describe the solution you'd like

I found in another ticket that a lot of of widgets have an inject method to add custom controls. I would like to know if this could be possible for my use case.

Source:
https://github.com/elementor/elementor/issues/6499

Possibly this could be implemented like this:
https://developers.elementor.com/docs/hooks/injecting-controls/

**Comment by nicholaszein** [comment]
Hello @aFluxx.

Thanks for submitting your question! 🙏 

Unfortunately, at the moment we do not have a public API for Elementor Pop-ups, and we do not give support to integration requests or documentation guidance. Moreover, the references you made are not applicable to the popup display conditions, triggers, and advanced rules, these are widget controls.

However, there are some translation plugins like TranslatePress that add this option to popups, you can try to check their code to see how they did it. I'm not sure if PolyLang does too, but have you tried checking [this plugin](https://wordpress.org/plugins/connect-polylang-elementor/)?

Kind regards
