### ISSUE TITLE
🔗 🚀 Feature Request: Add Reset button to reset to default unit in numeric fields (Related to #19140)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20735]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

In version 3.10, we can view the other units as a slide by clicking on the default unit and select the desired unit.
As a small suggestion, it would be great if a button to return to the default unit was **displayed after selecting another unit.**
After clicking this button, the selected unit will immediately change to the default unit. This simple button will be very useful in speeding up the workflow.

### Describe the solution you'd like

![download](https://user-images.githubusercontent.com/77163248/207456195-cc0e4f5d-a3da-4710-94bf-1185b0318b8a.png)

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap. I think this is a good request, but perhaps it should be part of something else, like your other issue #19140 which covers all fields.

I think I'll close this one for now and merge it with #19140 so we can discuss this further better.

Thanks for the suggestion though! 👍 

Best regards
