### ISSUE TITLE
✔️ 🚀 Feature Request: Add Hover Animation for Nested Tabs titles

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20733]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Adding [Hover Animation](https://prnt.sc/hD79mDrr_scC) feature for nested tabs widget [tab items](https://prnt.sc/woGZYJe8Y0je) would be great.

### Describe the solution you'd like

The video below is what I have in mind : 

https://user-images.githubusercontent.com/88034902/207434241-1c2dea6f-9c82-499b-a0e6-75091447e235.mp4

**Comment by nicholaszein** [comment]
Hey @Michaelgimii,

thanks for submitting your feature request! 🙏 

Cheers

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.10! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
