### ISSUE TITLE
[⌛ Awaiting Feedback] 🐞 Bug Report: Updating to 3.9.0 breaks WooCommerce Product Bundles in Single Product templates

### ISSUE THREAD

**Issue by bfa** [elementor/elementor#20748]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating Elementor Pro to 3.9.0, a new compatibility issue surfaced with the WooCommerce Product Bundle plugin. It was all working fine at version 3.8.2. See screenshots for before and after updates. 
![Screen Shot 2022-12-14 at 11 13 22 AM](https://user-images.githubusercontent.com/869347/207649701-a4244c08-ce1b-4428-b295-5209f2f7138c.png)
![Screen Shot 2022-12-14 at 11 12 10 AM](https://user-images.githubusercontent.com/869347/207649716-d764d1a3-66a4-465c-9c47-0aee52233716.png)

### Steps to reproduce

1) Install new WP site with Hello Theme activated
2) Install Elementor and Elementor Pro
3) Install WooCommerce and WooCommerce Product Bundles (Premium Plugin)
4) Create new product with bundle
5) The add to cart product single loop is messed up. 
6) Deactivate Elementor Pro and the product single loop appears fine. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.5
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 8.0.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://aircompressorstore.com
	Home URL: https://aircompressorstore.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -4
	Admin Email: benm@aircompressorstore.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 FirePHP/0.5

== Active Plugins ==
	Admin Columns Pro
		Version: 6.0.2
		Author: AdminColumns.com

	Admin Menu Editor
		Version: 1.10.4
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 6.0.5
		Author: WP Engine

	Bulk Term Editor
		Version: 1.1.3
		Author: Yuya Hoshino

	CallRail Phone Call Tracking
		Version: 0.4.12
		Author: CallRail, Inc.

	Category Order and Taxonomy Terms Order
		Version: 1.7.4
		Author: Nsp-Code

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Conditional Shipping Methods
		Version: 1.3.0
		Author: Octolize

	Cost of Goods for WooCommerce
		Version: 2.8.0
		Author: WPFactory

	Cost of Goods for WooCommerce Pro
		Version: 2.6.4
		Author: WPFactory

	Custom links in Elementor Image Carousel
		Version: 1.1.1
		Author: Charlie Etienne

	Custom Post Type UI
		Version: 1.13.2
		Author: WebDevStudios

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Elementor
		Version: 3.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	Export All URLs
		Version: 4.4
		Author: Atlas Gondal

	FiboSearch - AJAX Search for WooCommerce (Pro)
		Version: 1.21.1
		Author: FiboSearch Team

	FileBird
		Version: 5.0.8
		Author: Ninja Team

	Flexible Shipping
		Version: 4.17.0
		Author: Octolize

	Flexible Shipping PRO
		Version: 2.14.0
		Author: Octolize

	GD Mail Queue
		Version: 3.9.3
		Author: Milan Petrovic

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Pixel Manager for WooCommerce
		Version: 1.27.9
		Author: SweetCode

	PixelYourSite PRO
		Version: 9.3.7
		Author: PixelYourSite

	PixelYourSite Super Pack
		Version: 3.0.7
		Author: PixelYourSite

	Plugin Notes Plus
		Version: 1.2.6
		Author: Jamie Bergen

	Rank Math SEO
		Version: 1.0.103.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.25
		Author: Rank Math

	Unlimited Elements for Elementor
		Version: 1.5.43
		Author: Unlimited Elements

	Webgility
		Version: 400
		Author: Webgility

	WooCommerce
		Version: 7.1.1
		Author: Automattic

	WooCommerce AvaTax
		Version: 1.16.5
		Author: SkyVerge

	WooCommerce Payment Gateway Based Fees
		Version: 3.2.5
		Author: InoPlugs

	WooCommerce Product Bundles
		Version: 6.17.3
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.0.1
		Author: WooCommerce

	WP Crontrol
		Version: 1.15.0
		Author: John Blackbourn & crontributors

	WP Grid Builder
		Version: 1.7.0
		Author: Loïc Blascos

	WP Grid Builder - Caching
		Version: 1.0.7
		Author: Loïc Blascos

	WP Grid Builder - Elementor
		Version: 1.2.0
		Author: Loïc Blascos

	WP Offload Media
		Version: 3.1.0
		Author: Delicious Brains

	WP Rocket
		Version: 3.12.3.3
		Author: WP Media

	YITH WooCommerce Checkout Manager
		Version: 1.21.0
		Author: YITH

	YITH WooCommerce Points and Rewards Premium
		Version: 3.16.0
		Author: YITH

	YITH WooCommerce Product Add-ons & Extra Options Premium
		Version: 3.8.3
		Author: YITH

	YITH WooCommerce Request A Quote Premium
		Version: 4.8.0
		Author: YITH

== Must-Use Plugins ==
	FirePHP
		Version: 0.1
		Author: 

	Kinsta Must-use Plugins
		Version: 2.4.8
		Author: Kinsta Team

== Elements Usage ==
	
	archive : 2
		heading : 2
		spacer : 1
		text-editor : 1
		wpgb-facet : 1
		wpgb-grid : 1
	page : 14
		button : 3
		divider : 8
		heading : 78
		image : 6
		text-editor : 4
	popup : 6
		form : 1
		heading : 3
		spacer : 2
		template : 11
	product : 2
		breadcrumbs : 1
		button : 6
		heading : 60
		image : 3
		menu-anchor : 4
		shortcode : 4
		spacer : 9
		theme-site-logo : 1
		wc-add-to-cart : 1
		woocommerce-notices : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	section : 19
		wpgb-facet : 112
	widget : 0
		button : 1
		wpgb-facet : 1
	wp-post : 4
		heading : 1
		text-editor : 8
		video : 5
	wp-page : 18
		button : 4
		divider : 4
		heading : 70
		image : 20
		posts : 6
		template : 1
		text-editor : 9
		ucaddon_drip_popup_button : 5
		video-playlist : 6
		wpgb-facet : 2
		wpgb-grid : 1
	single-post : 2
		heading : 1
		image : 1
		theme-post-content : 1
		woocommerce-breadcrumb : 1
	single-page : 2
		heading : 2
		image : 1
		theme-post-content : 1
	product-post : 0
		button : 30
		divider : 68
		heading : 393
		icon-list : 26
		image : 143
		text-editor : 232
	product-archive : 12
		breadcrumbs : 1
		button : 9
		heading : 4
		icon : 1
		image : 3
		spacer : 2
		template : 9
		text-editor : 2
		ucaddon_dryer_cfm_calculator : 1
		video : 1
		wpgb-facet : 19
		wpgb-grid : 11

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 282022-11-16 10:42:29 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-16 10:42:29 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-16 10:42:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-29 14:43:47 [info] elementor-pro::elementor_pro_updater Started 
2022-11-29 14:43:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-29 14:43:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-29 14:43:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-11-29 14:43:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-12-09 11:14:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-09 11:14:26 [info] elementor::elementor_updater Started 
2022-12-09 11:14:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-09 11:14:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-09 11:14:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-09 11:14:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-09 11:14:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-09 11:25:36 [info] elementor-pro::elementor_pro_updater Started 
2022-12-09 11:25:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-09 11:25:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-09 11:25:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-09 11:25:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]

JS: showing 10 of 10JS: 2022-11-11 20:14:26 [error X 1][https://aircompressorstore.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading \'getOptions\') 
JS: 2022-11-15 19:59:34 [error X 4][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view162\") has already been destroyed and cannot be used. 
JS: 2022-11-17 19:45:47 [error X 42][https://aircompressorstore.com/wp-admin/post.php?post=118&action=elementor#:1:1] Identifier \'$dcWidgetIdInput\' has already been declared 
JS: 2022-12-01 20:08:19 [error X 1][https://aircompressorstore.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:768952] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-12-12 20:13:48 [error X 2][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view158\") has already been destroyed and cannot be used. 
JS: 2022-12-12 20:15:13 [error X 1][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view155\") has already been destroyed and cannot be used. 
JS: 2022-12-12 20:17:28 [error X 1][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view156\") has already been destroyed and cannot be used. 
JS: 2022-12-12 20:19:07 [error X 4][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view153\") has already been destroyed and cannot be used. 
JS: 2022-12-12 20:19:52 [error X 1][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view168\") has already been destroyed and cannot be used. 
JS: 2022-12-12 20:22:14 [error X 1][https://aircompressorstore.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view150\") has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2022-11-16 14:15:54 [warning X 6][/www/aircompressorstorecom_184/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-17 15:44:11 [warning X 2][/www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-12 16:09:26 [warning X 1][/www/aircompressorstorecom_184/public/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 12:05:35 [error X 1][/www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/core/modules-manager.php::75] Uncaught Error: Class "\ElementorPro\Modules\QueryControl\Module" not found in /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/core/modules-manager.php:75
Stack trace:
#0 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/plugin.php(358): ElementorPro\Core\Modules_Manager->__construct()
#1 /www/aircompressorstorecom_184/public/wp-includes/class-wp-hook.php(308): ElementorPro\Plugin->on_elementor_init('')
#2 /www/aircompressorstorecom_184/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 /www/aircompressorstorecom_184/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor/includes/plugin.php(652): do_action('elementor/init')
#5 /www/aircompressorstorecom_184/public/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#6 /www/aircompressorstorecom_184/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#7 /www/aircompressorstorecom_184/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /www/aircompressorstorecom_184/public/wp-settings.php(617): do_action('init')
#9 /www/aircompressorstorecom_184/public/wp-config.php(59): require_once('/www/aircompres...')
#10 /www/aircompressorstorecom_184/public/wp-load.php(50): require_once('/www/aircompres...')
#11 /www/aircompressorstorecom_184/public/wp-blog-header.php(13): require_once('/www/aircompres...')
#12 /www/aircompressorstorecom_184/public/index.php(17): require('/www/aircompres...')
#13 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 12:13:02 [error X 1][/www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/popup/document.php::65] Uncaught Error: Class "ElementorPro\Modules\Popup\DisplaySettings\Triggers" not found in /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/popup/document.php:65
Stack trace:
#0 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/popup/document.php(119): ElementorPro\Modules\Popup\Document->get_display_settings()
#1 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor/core/base/document.php(325): ElementorPro\Modules\Popup\Document->get_frontend_settings()
#2 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(186): Elementor\Core\Base\Document->get_container_attributes()
#3 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(414): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_container_attributes()
#4 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor/includes/frontend.php(1153): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#5 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor/core/base/document.php(1144): Elementor\Frontend->get_builder_content(5330, false)
#6 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor/modules/library/documents/library-document.php(76): Elementor\Core\Base\Document->get_content(false)
#7 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(158): Elementor\Modules\Library\Documents\Library_Document->get_content(false)
#8 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(173): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content()
#9 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(315): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content()
#10 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/theme-builder/api.php(13): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location('popup')
#11 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor-pro/modules/popup/module.php(94): elementor_theme_do_location('popup')
#12 /www/aircompressorstorecom_184/public/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\Popup\Module->print_popups('')
#13 /www/aircompressorstorecom_184/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#14 /www/aircompressorstorecom_184/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 /www/aircompressorstorecom_184/public/wp-includes/general-template.php(3059): do_action('wp_footer')
#16 /www/aircompressorstorecom_184/public/wp-content/themes/hello-elementor/footer.php(23): wp_footer()
#17 /www/aircompressorstorecom_184/public/wp-includes/template.php(783): require_once('/www/aircompres...')
#18 /www/aircompressorstorecom_184/public/wp-includes/template.php(718): load_template('/www/aircompres...', true, Array)
#19 /www/aircompressorstorecom_184/public/wp-includes/general-template.php(92): locate_template(Array, true, true, Array)
#20 /www/aircompressorstorecom_184/public/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(30): get_footer()
#21 /www/aircompressorstorecom_184/public/wp-includes/template-loader.php(106): include('/www/aircompres...')
#22 /www/aircompressorstorecom_184/public/wp-blog-header.php(19): require_once('/www/aircompres...')
#23 /www/aircompressorstorecom_184/public/index.php(17): require('/www/aircompres...')
#24 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Custom links in Elementor Image Carousel: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified
	WP Grid Builder - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @bfa,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We tested both plugins with the latest versions, and everything works and appears as expected.
* Your issue is most likely related to **cache** or one of the other plugins you have installed.

![image](https://user-images.githubusercontent.com/113993460/207985076-dee3a824-bb69-462c-af3e-b5041583ae88.png)
_Example of a WooCommerce Product Bundle page inside a Single Product template in Elementor in a live website using the latest version of Elementor (3.9.1), Elementor Pro (3.9.1), WooCommerce (7.2.0), and WooCommerce Product Bundles (6.17.3), with the latest version of the Hello Elementor theme (2.6.1). The layout appears as expected. This is a personal client's website._

### ✅ What you can do to solve your issue:
* Clear every type of cache.
* If you are using any performance optimization plugin, make sure you are not blocking any of the WooCommerce Product Bundles plugin scripts. As this can completely break their functionality (speaking by experience).
* Follow the troubleshooting steps below.

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by 319heads** [comment]
This needs to be re-opened and re-examined... it's not a cache issue.

Updating pro to any version above 3.8.2 (tested up to 3.10.1) will cause any widgets placed underneath the Bundled product Add to Cart widget not to display properly.

**Comment by bfa** [comment]
This is still broken with the latest version of Elementor.

**Comment by mycarrepair** [comment]
When will this be fixed? It is such a basic feature of a woocommerce store that you should be able to create and use bundled items and this is direct issue with Elementor.

**Comment by mycarrepair** [comment]
For anyone with this issue, I found today that a work around is to use the Custom Add To Cart Button

**Comment by 319heads** [comment]
How has this not been fixed yet?

**Comment by mycarrepair** [comment]
> 

Because Elementor are too busy building a mediocre AI to focus on fixing the most basic pieces of functionality needed to run an online store.

**Comment by jakubforman** [comment]
> For anyone with this issue, I found today that a work around is to use the Custom Add To Cart Button

Use widget **Custom Add To Cart** instead of **Add To Cart** fixed problem!

**Comment by amalg** [comment]
How does the custom add to cart widget solve the problem of all bundled products only being displayed in the Add To Cart element? Also the custom add to cart widget does not seem to include bundled products or bundled pricing anyway. This is barely a workaround, and hardly a fix. The proper thing would be to create a bundled products widget so the bundled products can be designed into the layout properly.

**Comment by mycarrepair** [comment]
@amalg if you enable qualities in the Custom Add To Cart you would get the bundled products and pricing. It was a fix. 

However, I have just tested the standard Add To Cart widget and from what I can see this bug has been resolved. Anyone else notice the same?
