### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: WordPress database error Table 'db365999_17.a' doesn't exist for query

### ISSUE THREAD

**Issue by confile** [elementor/elementor#20757]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After Updating to Elementor Version 3.9.1

I get the following error log: 

Dec 15, 09:06:20

WordPress database error Table 'db365999_17.a' doesn't exist for query SELECT a.action_id FROM a WHERE 1=1 AND a.hook='rocket_preload_job_check_finished' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Plugin->init, do_action('elementor/init'), WP_Hook->do_action, WP_Hook->apply_filters, ElementorPro\Plugin->on_elementor_init, Elementor\Core\Base\Module::instance, Elementor\Core\Base\DB_Upgrades_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->continue_run, Elementor\Core\Base\Background_Task->continue_run, do_action('elementor_1_elementor_pro_updater_cron'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\Background_Task->handle_cron_healthcheck, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->complete, Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete, Elementor\Core\Base\DB_Upgrades_Manager->clear_cache, Elementor\Core\Files\Manager->clear_cache, delete_option, do_action('delete_option__elementor_global_css'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Preload\Controller\Queue->job_preload_job_check_finished_async_exists, WP_Rocket\Engine\Common\Queue\AbstractASQueue->search, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions

 
Dec 15, 09:06:20

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE slug='rocket-preload'' at line 1 for query SELECT group_id FROM WHERE slug='rocket-preload' made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Plugin->init, do_action('elementor/init'), WP_Hook->do_action, WP_Hook->apply_filters, ElementorPro\Plugin->on_elementor_init, Elementor\Core\Base\Module::instance, Elementor\Core\Base\DB_Upgrades_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->continue_run, Elementor\Core\Base\Background_Task->continue_run, do_action('elementor_1_elementor_pro_updater_cron'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\Background_Task->handle_cron_healthcheck, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->complete, Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete, Elementor\Core\Base\DB_Upgrades_Manager->clear_cache, Elementor\Core\Files\Manager->clear_cache, delete_option, do_action('delete_option__elementor_global_css'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Common\Queue\AbstractASQueue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single_unique, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_id

 
Dec 15, 09:06:20

WordPress database error Incorrect table name '' for query SHOW FULL COLUMNS FROM `` made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Plugin->init, do_action('elementor/init'), WP_Hook->do_action, WP_Hook->apply_filters, ElementorPro\Plugin->on_elementor_init, Elementor\Core\Base\Module::instance, Elementor\Core\Base\DB_Upgrades_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->continue_run, Elementor\Core\Base\Background_Task->continue_run, do_action('elementor_1_elementor_pro_updater_cron'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\Background_Task->handle_cron_healthcheck, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->complete, Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete, Elementor\Core\Base\DB_Upgrades_Manager->clear_cache, Elementor\Core\Files\Manager->clear_cache, delete_option, do_action('delete_option__elementor_global_css'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Common\Queue\AbstractASQueue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single_unique, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group

 
Dec 15, 09:06:20

WordPress database error Table 'db365999_17.a' doesn't exist for query SELECT a.action_id FROM a WHERE 1=1 AND a.hook='rocket_preload_job_check_finished' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Plugin->init, do_action('elementor/init'), WP_Hook->do_action, WP_Hook->apply_filters, ElementorPro\Plugin->on_elementor_init, Elementor\Core\Base\Module::instance, Elementor\Core\Base\DB_Upgrades_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->continue_run, Elementor\Core\Base\Background_Task->continue_run, do_action('elementor_1_elementor_pro_updater_cron'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\Background_Task->handle_cron_healthcheck, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->complete, Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete, Elementor\Core\Base\DB_Upgrades_Manager->clear_cache, Elementor\Core\Files\Manager->clear_cache, do_action('elementor/core/files/clear_cache'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Preload\Controller\Queue->job_preload_job_check_finished_async_exists, WP_Rocket\Engine\Common\Queue\AbstractASQueue->search, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions

 
Dec 15, 09:06:20

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE slug='rocket-preload'' at line 1 for query SELECT group_id FROM WHERE slug='rocket-preload' made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Plugin->init, do_action('elementor/init'), WP_Hook->do_action, WP_Hook->apply_filters, ElementorPro\Plugin->on_elementor_init, Elementor\Core\Base\Module::instance, Elementor\Core\Base\DB_Upgrades_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->continue_run, Elementor\Core\Base\Background_Task->continue_run, do_action('elementor_1_elementor_pro_updater_cron'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\Background_Task->handle_cron_healthcheck, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->complete, Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete, Elementor\Core\Base\DB_Upgrades_Manager->clear_cache, Elementor\Core\Files\Manager->clear_cache, do_action('elementor/core/files/clear_cache'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Common\Queue\AbstractASQueue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single_unique, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_id

 
Dec 15, 09:06:20

WordPress database error Incorrect table name '' for query SHOW FULL COLUMNS FROM `` made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Plugin->init, do_action('elementor/init'), WP_Hook->do_action, WP_Hook->apply_filters, ElementorPro\Plugin->on_elementor_init, Elementor\Core\Base\Module::instance, Elementor\Core\Base\DB_Upgrades_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->__construct, Elementor\Core\Base\Background_Task_Manager->continue_run, Elementor\Core\Base\Background_Task->continue_run, do_action('elementor_1_elementor_pro_updater_cron'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\Background_Task->handle_cron_healthcheck, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->complete, Elementor\Core\Base\DB_Upgrades_Manager->on_runner_complete, Elementor\Core\Base\DB_Upgrades_Manager->clear_cache, Elementor\Core\Files\Manager->clear_cache, do_action('elementor/core/files/clear_cache'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\ThirdParty\Plugins\PageBuilder\Elementor->clear_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Common\Queue\AbstractASQueue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single_unique, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group

### Steps to reproduce

Update Elementor to Version 3.9.1

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/3Bf5yFFm

**Comment by nicholaszein** [comment]
Hi @confile!

Thank you for contacting us.

### ❌ 🧩 You seem to have a Plugin conflict with **WP Rocket**.

<ins>**This is not an Elementor issue.**</ins> From the error codes provided we can clearly see that the WP Rocket plugin is having trouble clearing the cache after an update. WP Rockets hooks into Elementor when there is an Update to do that. That's why it appears like an Elementor bug. But the caller for that database table is actually WP Rocket.

👉 Disable WP Rocket, and/or update it to the latest version.

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

👎 If after following these steps the problem persists, contact WP Rocket's support.

Regards
