### ISSUE TITLE
✔️ 🚀 Feature Request: [v3.10-Beta] Nested Elements / Tabs - Please add some options to animate tab transitions!

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#20756]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In the redesigned Tabs-Widget with the new "Nested Elements" there are no options to get a "smooth" transition like it's the case default with accordion etc.! Is looks and feel just now very choppy. You may be able to tackle this in the course of refreshing the widget.

@nicholaszein left me a comment that it's a great idea: https://github.com/elementor/elementor/discussions/20732#discussioncomment-4401893

This would also make sense for all future refreshed widgets that get this new function. Even though this usually looks good in the accordion widget, for example, it would still be nice to have control over it.

https://user-images.githubusercontent.com/57997262/207636395-397497b5-72ca-4f29-a2d1-2316175674f8.mp4

What would be good as a bonus if you could set the transition for each container tab. So on the whole in the styles of the tab and in each individual tab.

### Describe the solution you'd like

Just add options for better transitions. You've also found great ways to implement it elsewhere in the editor, so why not here too? 🤗

**Comment by fabianenzensperger** [comment]
#20732 (for assignment to the topic)

**Comment by nicholaszein** [comment]
Hello @fabianenzensperger,

thanks for submitting your feature request! 🙏 

Let's see if the team can add this option to the tabs widget! 😉 

Best regards

**Comment by elasticeye** [comment]
+1 for this!

**Comment by 79ho3ein** [comment]
+1

**Comment by Michaelgimii** [comment]
+10000

**Comment by Joliamendi** [comment]
+1
Will this be added in version 3.10? @nicholaszein

**Comment by nicholaszein** [comment]
Hi everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.10! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
