### ISSUE TITLE
⛔ 🐞 Bug Report: Font Awesome Icons Are Not Showing Up In Elementor Editor While Using Loop Grid Widget In The Page

### ISSUE THREAD

**Issue by ammar14z** [elementor/elementor#20764]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am designing my website on Elementor cloud hosting and after using Loop Grid widget on my page, Font awesome icons are not showing in Icon & Icon Box widgets (in the editor). Any previously loaded icons keep showing but I cannot be able to modify or add new icons after using Loop Grid widget.
For you reference I am attaching the snapshots as well.
I have also checked this on a blank page with Loop Grid and Icon widget, Font Awesome icons stop showing but if I remove the Loop Grid and reload the page Icons start showing again.
I have tried to find this issue but didn't find any solution.

![WithoutLoopWidget](https://user-images.githubusercontent.com/8939813/207894719-c4e42019-8a8c-4a9f-9774-ed133383c28d.png)
![Loop Grid](https://user-images.githubusercontent.com/8939813/207894730-6313c9dd-3db0-434a-a791-6778d35f0b7a.png)
![WithLoopWidget](https://user-images.githubusercontent.com/8939813/207894739-a4c33407-8bae-45b1-9f94-a8e06928b778.png)

### Steps to reproduce

1. Use Loop Grid Widget 
2. Use Icon or Icon Box Widget
3. Close and Reopen the page
4. Open Icons 
5. There will be no font awesome icone.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: (Google) v8.0.26
	PHP Version: 7.4.26
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://ontracktyping.ae
	Home URL: https://ontracktyping.ae
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 4
	Admin Email: ontrackaweer@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46

== Active Plugins ==
	Activity Log
		Version: 2.8.5
		Author: Activity Log Team

	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Coreapplet
		Version: 1.0.0.
		Author: Coreapplet

	Custom Post Type UI
		Version: 1.13.2
		Author: WebDevStudios

	Elementor
		Version: 3.10.0-cloud1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-cloud1
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		button : 1
		icon : 1
	header : 1
		heading : 1
		image : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
	wp-page : 4
		button : 2
		call-to-action : 1
		heading : 6
		icon-box : 5
		image-box : 1
		loop-grid : 1
		lottie : 1
		reviews : 1
		testimonial-carousel : 1
	loop-item : 1
		call-to-action : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 6 of 6PHP: 2022-12-05 11:38:36 [error X 1][/mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor/core/utils/collection.php::25] Uncaught TypeError: Argument 1 passed to Elementor\Core\Utils\Collection::__construct() must be of the type array, null given, called in /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/core/database/query-builder.php on line 1070 and defined in /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor/core/utils/collection.php:25
Stack trace:
#0 /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/core/database/query-builder.php(1070): Elementor\Core\Utils\Collection->__construct()
#1 /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(69): ElementorPro\Core\Database\Query_Builder->count()
#2 /mnt/customers-2/customers-el-4519612 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-06 05:04:44 [notice X 1][/mnt/customers/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-12 15:28:43 [error X 1][/mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-includes/class-wp-hook.php [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 21:21:17 [notice X 4][/mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-15 10:42:01 [notice X 6][/mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-15 11:55:41 [warning X 1][/mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/plugins/elementor/core/files/base.php::203] unlink(/mnt/customers-2/customers-el-4519612-42837-ontracktyping-wordpress-pvc-638d9f3aee99580020034918/wp-content/wp-content/uploads/elementor/css/post-497.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2022-12-06 13:44:02 [error X 1][https://ontracktyping.ae/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.9.0-cloud2:2:32995] elementorFrontendConfig is not defined 
JS: 2022-12-08 12:35:52 [error X 3][https://ontracktyping.ae/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0:3:881284] elementorFrontend is not defined 
JS: 2022-12-10 10:22:42 [error X 4][https://ontracktyping.ae/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-12-15 08:59:50 [error X 1][https://ontracktyping.ae/wp-admin/post.php?post=4&action=elementor:6:39] Cannot read properties of undefined (reading 'needHelpUrl') 
JS: 2022-12-15 10:05:40 [error X 16][https://ontracktyping.ae/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2022-12-15 12:57:05 [error X 1][https://ontracktyping.ae/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-cloud1:3:781990] Cannot read properties of undefined (reading 'localized') 

Log: showing 20 of 202022-12-08 14:31:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-cloud2',
  'to' => '3.9.0',
)]
2022-12-08 14:31:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-cloud2',
  'to' => '3.9.0',
)]
2022-12-08 14:31:58 [info] elementor-pro::elementor_pro_updater Started 
2022-12-08 14:31:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-08 14:31:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-08 14:31:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-cloud2',
  'to' => '3.9.0',
)]
2022-12-09 09:34:50 [info] elementor::elementor_updater Started 
2022-12-09 09:34:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-09 09:34:50 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-09 09:34:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-cloud2',
  'to' => '3.9.0',
)]
2022-12-15 09:23:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0-cloud1',
)]
2022-12-15 09:23:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.10.0-cloud1',
)]
2022-12-15 09:23:34 [info] elementor::elementor_updater Started 
2022-12-15 09:23:34 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-15 09:23:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-15 09:23:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0-cloud1',
)]
2022-12-15 09:24:26 [info] elementor-pro::elementor_pro_updater Started 
2022-12-15 09:24:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-15 09:24:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-15 09:24:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.10.0-cloud1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @ammar14z,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We tested with the same version of Elementor and Elementor Pro you have `3.10.0-cloud1`, and couldn't reproduce your issue.


https://user-images.githubusercontent.com/113993460/210302044-c49436c1-7088-4dc4-b336-a986cd46e218.mp4



### ✅ What you can do to solve your issue:
* Try isolating the problem by deactivating the other plugins installed.
* Clear the browser cache.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
