### ISSUE TITLE
🐞 Bug Report: Data Updater missing `option_id` in `order_clause` in `option_name` LIKE `elementor\_1\_elementor\_updater\batch\%`

### ISSUE THREAD

**Issue by EbiGSM** [elementor/elementor#20779]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Elementor Data Updater problems continue
And more importantly, there is an error in the "wp-admin/error_log" file and the sudden filling of the disk!

### Steps to reproduce

version 3.9.1

[18-Dec-2022 14:18:15 UTC] WordPress database error Unknown column 'option_id' in 'order clause' for query 
			SELECT *
			FROM wp_options
			WHERE option_name LIKE 'elementor\\_1\\_elementor\\_updater\\_batch\\_%'
			ORDER BY option_id ASC
			LIMIT 1
		 made by do_action('wp_ajax_nopriv_elementor_1_elementor_updater'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\BackgroundProcess\WP_Background_Process->maybe_handle, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->get_batch, Elementor\Core\Base\BackgroundProcess\WP_Background_Process->get_batch
[18-Dec-2022 14:18:15 UTC] WordPress database error Unknown column 'option_id' in 'order clause' for query 
			SELECT *
			FROM wp_options
			WHERE option_name LIKE 'elementor\\_1\\_elementor\\_updater\\_batch\\_%'
			ORDER BY option_id ASC
			LIMIT 1
		 made by do_action('wp_ajax_nopriv_elementor_1_elementor_updater'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\BackgroundProcess\WP_Background_Process->maybe_handle, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->get_batch, Elementor\Core\Base\BackgroundProcess\WP_Background_Process->get_batch
[18-Dec-2022 14:18:15 UTC] WordPress database error Unknown column 'option_id' in 'order clause' for query SELECT * FROM wp_options WHERE option_name LIKE 'wp\\_1\\_wc\\_privacy\\_cleanup\\_batch\\_%' ORDER BY option_id ASC LIMIT 1 made by do_action('wp_ajax_nopriv_wp_1_wc_privacy_cleanup'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Background_Process->maybe_handle, WC_Background_Process->handle, WC_Background_Process->get_batch
[18-Dec-2022 14:18:15 UTC] WordPress database error Unknown column 'option_id' in 'order clause' for query 
			SELECT *
			FROM wp_options
			WHERE option_name LIKE 'elementor\\_1\\_elementor\\_updater\\_batch\\_%'
			ORDER BY option_id ASC
			LIMIT 1
		 made by do_action('wp_ajax_nopriv_elementor_1_elementor_updater'), WP_Hook->do_action, WP_Hook->apply_filters, Elementor\Core\Base\BackgroundProcess\WP_Background_Process->maybe_handle, Elementor\Core\Base\Background_Task->handle, Elementor\Core\Base\Background_Task->get_batch, Elementor\Core\Base\BackgroundProcess\WP_Background_Process->get_batch
[18-Dec-2022 14:18:15 UTC] WordPress database error Unknown column 'option_id' in 'order clause' for query SELECT * FROM wp_options WHERE option_name LIKE 'wp\\_1\\_wc\\_privacy\\_cleanup\\_batch\\_%' ORDER BY option_id ASC LIMIT 1 made by do_action('wp_ajax_nopriv_wp_1_wc_privacy_cleanup'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Background_Process->maybe_handle, WC_Background_Process->handle, WC_Background_Process->get_batch
[18-Dec-2022 14:18:15 UTC] WordPress database error Unknown column 'option_id' in 'order clause' for query 
			SELECT *
			FROM wp_options
			WHERE option_name LIKE 'elementor\\_1\\_elementor\\_updater\\_batch\\_%'
			ORDER BY option_id ASC
			LIMIT 1

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>

نسخه ووکامرس: |   | 7.2.0
-- | -- | --
بسته WICommerce REST API: |   | 7.2.0 /home/storixir/public_html/wp-content/plugins/woocommerce/includes
بسته بلوک‌های ووکامرس: |   | 8.9.2 /home/storixir/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
بسته زمانبندی فعالیت: |   | 3.5.3 /home/storixir/public_html/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler
پوشه Log قابل نوشتن است: |   | /home/storixir/public_html/wp-content/uploads/wc-logs/
نسخه وردپرس: |   | 6.1.1
وردپرس چندسایته: |   | –
محدودیت حافظه وردپرس: |   | 3 گیگابایت
حالت رفع عیب ووکامرس: |   | –
زمانبندی ووکامرس: |   |  
زبان: |   | fa_IR
کش کالا خارجی: |   |  

</body>
</html>نسخه ووکامرس:		7.2.0
بسته WICommerce REST API:		 7.2.0 /home/sttt/public_html/wp-content/plugins/woocommerce/includes
بسته بلوک‌های ووکامرس:		 8.9.2 /home/sttt/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
بسته زمانبندی فعالیت:		 3.5.3 /home/sttt/public_html/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler
پوشه Log قابل نوشتن است:		 /home/sttt/public_html/wp-content/uploads/wc-logs/
نسخه وردپرس:		6.1.1
وردپرس چندسایته:		–
محدودیت حافظه وردپرس:		3 گیگابایت
حالت رفع عیب ووکامرس:		–
زمانبندی ووکامرس:		
زبان:		fa_IR
کش کالا خارجی:		
محیط سرور
اطلاعات سرور:		LiteSpeed
نسخه PHP:		7.4.33
حداکثر اندازه پست PHP:		128 مگابایت
محدودیت زمانی PHP:		250
حداکثر ورودی متغیرهای PHP:		1000
نسخه cURL:		7.86.0, OpenSSL/1.1.1s
SUHOSIN نصب شده است:		–
نسخه MySQL:		5.5.5-10.3.36-MariaDB-cll-lve
بیشینه اندازه آپلود:		128 مگابایت
منطقه زمانی پیش پندار است:		
fsockopen/cURL:		
SoapClient:		 در سرور شما تابع [SoapClient](https://php.net/manual/en/class.soapclient.php) فعال نیست - برخی افزونه‌های پرداخت از SOAP استفاده می کنند و به خوبی کار نخواهند کرد.
DOMDocument:		
GZip:		
رشته چند بایتی (Multibyte String):		
نوشته از راه دور:		 wp_remote_post() ناموفق شد. با ارائه کننده میزبانی وب خود، تماس بگیرید.
گرفتن از راه دور:		 wp_remote_get() ناموفق شد. با ارائه کننده میزبانی وب خود، تماس بگیرید.
پایگاه داده
نسخه پایگاه داده ووکامرس:		7.2.0
پیشوند پایگاه داده	 	wp_
اندازه کل پایگاه داده	 	106.04MB
اندازه داده‌های پایگاه داده	 	46.05MB
اندازه فهرست پایگاه داده	 	59.99MB

**Comment by nicholaszein** [comment]
Hello @EbiGSM, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Clear and concise title:** Please provide a clear and concise title that gives context to your issue. Summarize in one short phrase what is the problem, how it is happening, and where;
- **Description:** In your description, you need to explain in detail what happened, as you would explain to someone that doesn't know anything about your website or Elementor. Give as much information as possible. This is important information that will help solve your issue quicker;
- **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be detailed, lasting error logs do not help us reproduce your issue, they are supposed to be added in the **System Info** section for context.
- **Isolating the Problem:** You need to make sure this only happens while using the latest versions of Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins. Since you have not shared your complete System Info as required in our guidelines, we can't know for sure what's happening with your website.
- **System info:** Please include the [System Info](https://elementor.com/help/systems-info/) report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) available in your _WordPress Dashboard > Elementor > System Info_. This information is crucial for us to create an exact copy of your environment and validate your issue. Watch [this video](https://www.youtube.com/watch?v=tDXdynsnYuA) to learn how to download the report. We can't accept issues without it.

Without them, we simply can't help. 😕 

👉 Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards

**Comment by EbiGSM** [comment]
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://storix.ir
	Home URL: https://storix.ir
	WP Multisite: No
	Max Upload Size: 128 مگابایت
	Memory limit: 3000M
	Max Memory limit: 512M
	Permalink Structure: /%post_id%/%postname%/
	Language: fa-IR
	Timezone: Asia/Tehran
	Admin Email: storix.ir@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Admin category search
		Version: 1.2
		Author: Atilla Ordog

	All In One WP Security
		Version: 5.1.4
		Author: All In One WP Security & Firewall Team

	Contact Form 7
		Version: 5.7.1
		Author: Takayuki Miyoshi

	DIGITS: Forced Login Page Lock Addon
		Version: 2.0.1
		Author: UnitedOver

	DIGITS: Merge Phone Number Addon
		Version: 2.0
		Author: UnitedOver

	DIGITS: One Click Login/Signup Addon
		Version: 3.3
		Author: UnitedOver

	DIGITS: Wordpress Mobile Number Signup and Login
		Version: 7.9.4.2
		Author: UnitedOver

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	ELEX WooCommerce Bulk Edit Products, Prices & Attributes (Basic)
		Version: 1.2.8
		Author: ELEXtensions

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.21.0
		Author: FiboSearch Team

	Filter Everything — WooCoomerce Product & WordPress Filter
		Version: 1.7.1
		Author: Andrii Stepasiuk

	LiteSpeed Cache
		Version: 5.3.1
		Author: LiteSpeed Technologies

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	Rank Math SEO
		Version: 1.0.104.1
		Author: Rank Math

	Rate my Post - WP Rating System
		Version: 3.3.8
		Author: Blaz K.

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	SKU Generator for WooCommerce
		Version: 1.6.0
		Author: WP Wham

	Smart Slider 3
		Version: 3.5.1.12
		Author: Nextend

	Smush
		Version: 3.12.4
		Author: WPMU DEV

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	Template Library and Redux Framework
		Version: 4.3.21
		Author: Extendify

	Variation Swatches for WooCommerce
		Version: 2.0.16
		Author: Emran Ahmed

	WooCommerce
		Version: 7.2.2
		Author: Automattic

	Woocommerce Invoice Pro
		Version: 11.0.2
		Author: S.Reza Salehi

	WooCommerce Min/Max Quantities
		Version: 4.0.6
		Author: WooCommerce

	WooCommerce Return and Warranty (RMA)
		Version: 1.2.3
		Author: chilidevs

	WP Paint - WordPress Image Editor
		Version: 0.5.3
		Author: ZetaMatic

	YITH WooCommerce Brands Add-On
		Version: 2.7.0
		Author: YITH


== آزمایشات عنصر ==
	بهینه سازی خروجی DOM: به صورت پیشفرض غیرفعال است
	بارگذاری دارایی بهبود یافته: به صورت پیشفرض غیرفعال است
	بارگذاری CSS بهبود یافته: غیرفعال
	نمادهای فونت درون خطی: غیرفعال
	بهبود دسترسی: غیرفعال
	نقاط قطع سفارشی اضافی (جهت رسپانسیو سایت به کار میره): غیرفعال
	درون‌ریزی و برون‌بری کیت وب‌سایت: غیرفعال
	ابزارک‌های بومی وردپرس را از نتایج جستجو پنهان کنید: غیرفعال
	admin_menu_rearrangement: به صورت پیشفرض غیرفعال است
	کانتینر فلکس باکس: غیرفعال
	سربرگ و فوتر پوسته سلام: به صورت پیشفرض غیرفعال است
	صفحات فرود: به صورت پیشفرض فعال است
	نمونه‌گیر رنگ: به صورت پیشفرض فعال است
	ابزارک‌های مورد علاقه: به صورت پیشفرض فعال است
	نوار بالایی مدیریت: به صورت پیشفرض فعال است
	Lazy Load Background Images: غیرفعال
	ذخیره به‌عنوان پیش‌فرض: غیرفعال


== گزارش ==
	
Log: showing 20 of 422022-12-22 22:23:35 [info] elementor::elementor_updater Started 
2022-12-22 22:23:56 [info] elementor::elementor_updater Started 
2022-12-22 22:24:16 [info] elementor::elementor_updater Started 
2022-12-22 22:24:39 [info] elementor::elementor_updater Started 
2022-12-22 22:25:00 [info] elementor::elementor_updater Started 
2022-12-22 22:25:21 [info] elementor::elementor_updater Started 
2022-12-22 22:25:41 [info] elementor::elementor_updater Started 
2022-12-22 22:26:02 [info] elementor::elementor_updater Started 
2022-12-22 22:26:23 [info] elementor::elementor_updater Started 
2022-12-22 22:26:43 [info] elementor::elementor_updater Started 
2022-12-22 22:27:03 [info] elementor::elementor_updater Started 
2022-12-22 22:27:24 [info] elementor::elementor_updater Started 
2022-12-22 22:27:44 [info] elementor::elementor_updater Started 
2022-12-22 22:28:04 [info] elementor::elementor_updater Started 
2022-12-22 22:28:24 [info] elementor::elementor_updater Started 
2022-12-22 22:28:45 [info] elementor::elementor_updater Started 
2022-12-22 22:29:05 [info] elementor::elementor_updater Started 
2022-12-22 22:29:27 [info] elementor::elementor_updater Started 
2022-12-22 22:29:50 [info] elementor::elementor_updater Started 
2022-12-22 22:30:11 [info] elementor::elementor_updater Started 

PHP: showing 1 of 1PHP: 2022-12-22 22:16:10 [notice X 42][/home/storixir/public_html/wp-content/plugins/elementor/core/base/background-process/wp-background-process.php::297] Trying to get property 'option_value' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== المنتور - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @EbiGSM,

Thank you for providing your System Info! 🙏 

I'm marking this issue as a bug for not until we can check for the issue.

Please when submitting your issue, make sure to provide the most information you can.

**Comment by EbiGSM** [comment]
> Hello @EbiGSM,
> 
> Thank you for providing your System Info! 🙏
> 
> I'm marking this issue as a bug for not until we can check for the issue.
> 
> Please when submitting your issue, make sure to provide the most information you can.

Our team trusts you. How can we give you access? Where to send the information?

**Comment by EbiGSM** [comment]
We are still waiting for your answer.
We give you access to the site and you can check this problem yourself. Thankful

**Comment by EbiGSM** [comment]
This problem was solved by asking the chatGPT!
The problem was solved very simply by searching and deleting "elementor_1_elementor_updater_batch" in wp_options database!! Thanks

**Comment by EbiGSM** [comment]
This problem was solved by asking the chatGPT!
The problem was solved very simply by searching and deleting "elementor_1_elementor_updater_batch" in wp_options database!! Thanks
