### ISSUE TITLE
🔗 🚀 Feature Request: Prevent tab from becoming accordion in Nested tabs widget (Merged with #7742)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20782]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

As you know, the new tab widget turns into an accordion on mobile. This is a very big weakness. This means we can never display the tab on mobile...

### Describe the solution you'd like

Please correct this. The new tab widget is newly coded, so it will be much easier to change than the old widgets. The tab widget, even on mobile, should be displayed as a tab. If we want to use an accordion, we must use the nested accordion widget. Each widget must be usable in its place.

Anyway, I think it would have been better to fix this issue in version 3.10 (Even if it causes the release of version 3.10 to be released one month late.). **Because if version 3.10 is released, if you want to fix this problem later, we will definitely have the usual problem (backwards compatibility).**

I hope this new widget will not be released incompletely. Not showing the tab on mobile or in other words the tab turning into an accordion on mobile is a very serious defect.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

Thank you for your submission! 🙏 

### 🔗 This issue is Related to #7742.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
