### ISSUE TITLE
❌ BUG Elementor

### ISSUE THREAD

**Issue by PandaFaucheurFR** [elementor/elementor#20796]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, i can't access to wordpress template, as i can access the pages trough elementor ( v3.9.1 )
i can't access nor the elementor debugger or the wordpress debugger.
How can i acces the source code from that point ?

HELP ME PLS

### Steps to reproduce

1) Log on [www.greeneyeshight](https://greeneyesight.org/wp-admin/)
2) And that the error message
          "Il y a une erreur critique sur ce site."

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

I would like to access the code.
I can't desactivate or activate the elementor pluggins, i can only access the site trough the Nav Bar of elementor on "modified with elementor".

**Comment by nicholaszein** [comment]
Hello @PandaFaucheurFR,

Thanks for contacting us! 🙏 

This is more of a WordPress support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
