### ISSUE TITLE
🚀 Feature Request: Supporting Navigator.userAgentData for Chrome/

### ISSUE THREAD

**Issue by egesucu** [elementor/elementor#20798]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Chrome warns web developers to adapt Navigator.userAgentData to give less information about the user agent. This is an [experimental API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData).

### Describe the solution you'd like

It would be better to add this support for chromium browsers, without breaking non-supporting browsers such as Safari, Firefox. It's been supported(Chrome 90+, Edge 90+, Opera (76+ web, 64+ mobile), Samsung Internet 15+)

### Describe alternatives you've considered

Instead of:

- navigator.userAgent --> navigator.userAgentData
//eg: This would bring:
{
    "brands": [
        {
            "brand": "Google Chrome",
            "version": "111"
        },
        {
            "brand": "Not(A:Brand",
            "version": "8"
        },
        {
            "brand": "Chromium",
            "version": "111"
        }
    ],
    "mobile": false,
    "platform": "macOS"
}
- navigator.platform --> navigator.userAgentData.platform
- navigator.mobile can be used to determine mobile/web
- navigator.userAgent.brands can be used to identify browser 
//eg: navigator.userAgent.brands:
[
    {
        "brand": "Google Chrome",
        "version": "111"
    },
    {
        "brand": "Not(A:Brand",
        "version": "8"
    },
    {
        "brand": "Chromium",
        "version": "111"
    }
]

### Additional context

**Google's Warning Detail:**
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

Starting with Chrome 113, the default agent data will be reduced. See details [here](https://www.chromium.org/updates/ua-reduction/).

**The Chrome Desktop User Agent string currently uses the following format:**

Mozilla/5.0 (<platform>; <oscpu>) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/<majorVersion>.<minorVersion>; Safari/537.36
**Post UA-Reduction, the new format will be:**

Mozilla/5.0 (<unifiedPlatform>) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/<majorVersion>.0.0.0 Safari/537.36

**Comment by nicholaszein** [comment]
Hello @egesucu,

Thanks for your feedback! 🙏 

Can you please provide a copy of your [System Info](https://www.youtube.com/watch?v=tDXdynsnYuA) and more context about when or where are you seeing this warning?

We will need this information to understand your report better.

Kind regards

**Comment by egesucu** [comment]
Hi @nicholaszein

I mentioned this warning and why it's showing up with some suggestions. Below, I'm posting the System Info. Yet, this is a feature recommendation to elementor plugin rather than system info.

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 8.0.26
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.egesucu.com.tr
	Home URL: https://www.egesucu.com.tr
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 3
	Admin Email: egesucu@icloud.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

== Active Plugins ==
	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.3.9
		Author: Really Simple Plugins

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	LiteSpeed Cache
		Version: 5.3.1
		Author: LiteSpeed Technologies

	Rank Math SEO
		Version: 1.0.105
		Author: Rank Math


== Elements Usage ==
	
	footer : 1
		button : 1
		container : 1
		social-icons : 1
		text-editor : 1
	header : 3
		container : 3
		nav-menu : 2
		theme-site-title : 2
	wp-page : 4
		animated-headline : 1
		call-to-action : 2
		code-highlight : 1
		container : 8
		gallery : 1
		heading : 13
		image : 1
		text-editor : 8
	error-404 : 3
		button : 1
		container : 1
		heading : 2


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Inactive
	Scroll Snap: Active


== Log ==
	
Log: showing 20 of 372022-12-15 03:54:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-15 03:54:27 [info] elementor::elementor_updater Started 
2022-12-15 03:54:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-15 03:54:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-15 03:54:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-19 23:32:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-19 23:32:34 [info] elementor-pro::elementor_pro_updater Started 
2022-12-19 23:32:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-19 23:32:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-19 23:32:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-21 23:41:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-21 23:41:52 [info] elementor::elementor_updater Started 
2022-12-21 23:41:52 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-21 23:41:52 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-21 23:41:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-22 13:26:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-22 13:26:59 [info] elementor-pro::elementor_pro_updater Started 
2022-12-22 13:26:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-22 13:26:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-22 13:26:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

PHP: showing 5 of 5PHP: 2022-12-07 16:25:52 [notice X 17][/home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/egesucuc/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-12-07 16:26:17 [notice X 4][/home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-07 16:27:58 [notice X 3][/home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-09 15:38:47 [notice X 2][/home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/egesucuc/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/egesucuc/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/egesucuc/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-12-10 13:57:30 [warning X 17][/home/egesucuc/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-12-19 21:02:11 [error X 1][https://www.egesucu.com.tr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:913406] undefined is not an object (evaluating \&#039;T.settings\&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @egesucu,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
