### ISSUE TITLE
🐞 Bug Report: Hover animation on Nested Tabs widget is not working as expected (ED-9162)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20795]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @nicholaszein.

If we use hover animation in the tab widget, there is a problem in the front end. The problem is that the harrow animation is not applied to the title of the current tab.

### Steps to reproduce

1- Add a new Tabs widget and create a hover animation for its title.
2- On the frontend, when the page loads, if you hover over the tabs, the hover animation will work on them.
3- But if you change the tab, the animation title will not work in the current tab title.

https://user-images.githubusercontent.com/88034902/208485210-0a4b4409-2f59-4e00-8588-06121031d50e.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

elementor 3.11 - dev2

**Comment by Michaelgimii** [comment]
Hi @nicholaszein

Hover animation mode does not work on active tab.

https://user-images.githubusercontent.com/88034902/210252569-9c60a054-780b-487f-abf7-387725e1f9bb.mp4

**Comment by 79ho3ein** [comment]
I think this is a natural behavior and it is better to act like this. Note that even if you change the hover color, it will not work on the active tab. I think this is a reasonable method. The active tab should be different from other tabs.

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

thanks for the feedback, and sorry for the delay! 🙏

Let me check with the team about the intended purpose since, from my understanding, I agree with @79ho3ein regarding the intention not to apply the animation on the active tab. From a UX standpoint, the active tab shouldn't be confused with a button that performs an action, since it's already open.

Kind regards

**Comment by nicholaszein** [comment]
This issue was solved in version 3.10.
