### ISSUE TITLE
✔️ 🚀 Feature Request: Space between for icon in the nested tabs widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20805]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

Please add space between option for icon in Nested tabs widget. This feature can be very useful.

### Describe the solution you'd like

space between option for icon in nested tab widget.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

thanks for submitting your feature request, and apologies for the delay! 🙏 

As a reference, here are the discussion comments related to this request: 
- https://github.com/orgs/elementor/discussions/20732#discussioncomment-4422553
- https://github.com/orgs/elementor/discussions/20732#discussioncomment-4461606

We will check and consider this feature for future phases. 😉 

Best regards

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.10! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
