### ISSUE TITLE
❌ Code window formatting

### ISSUE THREAD

**Issue by Bronek-RTB** [elementor/elementor#20803]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

<img width="957" alt="bug" src="https://user-images.githubusercontent.com/79328041/208621960-6dc3e8d5-dc39-4971-b3f0-4c8cf8a3523b.png">

### Steps to reproduce

<img width="959" alt="bug01" src="https://user-images.githubusercontent.com/79328041/208622048-0f380d22-9fdd-4ef0-9ee1-c0ff7021152a.png">

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

WordPress Version: 6.0.2
PHP Version:  8.1.8
Theme: Docy v. 1.6.4
Elementor 3.6.2

**Comment by nicholaszein** [comment]
Hello there @Bronek-RTB, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Clear and concise title:** Please provide a clear and concise title that gives context to your issue;
- **Description:** In your description, you need to explain in detail what happened, as you would explain to someone that doesn't know anything about your website or Elementor. Give as much information as possible. This is important information that will help solve your issue quicker;
- **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be detailed;
- **Isolating the Problem:** You need to make sure this only happens while using the latest versions of Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.
- **System info:** Please include the [System Info](https://elementor.com/help/systems-info/) report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) available in your _WordPress Dashboard > Elementor > System Info_. This information is crucial for us to create an exact copy of your environment and validate your issue. Watch [this video](https://www.youtube.com/watch?v=tDXdynsnYuA) to learn how to download the report. We can't accept issues without it.

Without them, we simply can't help. 😕 

👉 Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue in accordance with these guidelines. 😉 

Best regards,

Nick
