### ISSUE TITLE
[🧐 Evaluating] 🚀 Feature Request: Lazy load self hosted videos in Elementor

### ISSUE THREAD

**Issue by AlexUsernameAvailable** [elementor/elementor#20812]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

There is a lazy load mechanism offered by Elementor from the Video Element> Image Overlay section, titled "Lazy Load", documented here: https://docs.elementor.com/article/48-video

It's available for YouTube, DailyMotion and Vimeo, but not for self hosted videos. This seems like a huge oversight or a bug.

### Describe the solution you'd like

Ability to lazy load self hosted videos in the video element.

### Additional context

 @shilo-ey @danielkatz @KingYes please help. This issue has been posted before with no response.

**Comment by nicholaszein** [comment]
Hello @AlexUsernameAvailable! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by AlexUsernameAvailable** [comment]
Thank you :)

**Comment by marowi85** [comment]
+1

I would love to see this feature as well.

**Comment by arielk** [comment]
Fixed with this issue: https://github.com/elementor/elementor/issues/17308

Thanks for your feedback!
