### ISSUE TITLE
⛔ 🐞 Bug Report: Loop grid in a loop grid item messes up rest of the the page

### ISSUE THREAD

**Issue by jonathangerbaud** [elementor/elementor#20863]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Disclaimer: I'm using ACF and the Advanced Post Queries plugin, but I think that the core of the problem lies within the Loop builder in Elementor.

So I created multiple custom types.

I have a destination page displaying a loop of "resources".
Some of these resources are displaying a loop of "places".

So, Destination is a template. It uses a loop grid, and displays resource loop items.
Resource also uses a loop grid and displays place loop items.

The thing to note is that I'm using an Elementor Block for Gutenberg to insert a template into a Resource, template that is a grid loop of places items.

So, for the sake of example, I have the following list (one column loop grid) being displayed for a destination:

- Resource 1
- Resource 2
- Resource 3
  - Place 1
  - Place 2
- Resource 4
- Resource 5
  - Place 3
  - Place 4
- Resource 6
- Resource 7
- ...

Everything works well until Resource 4. Because at this point, Resources are no longer displayed using the Resource loop item template but with the Place loop item template instead.

So I have the following in the end:

- Resource 1 (Resource loop item template)
- Resource 2 (Resource loop item template)
- Resource 3 (Resource loop item template)
  - Place 1  (Place loop item template)
  - Place 2  (Place loop item template)
- Resource 4  (Place loop item template)
- Resource 5  (Place loop item template)
  - Place 3  (Place loop item template)
  - Place 4 (Place loop item template)
- Resource 6  (Place loop item template)
- Resource 7 (Place loop item template)
- ...
 
So the problem is that the data in itself is correct, but the template used is no longer the right one starting with Resource 4.

I'm not an expert in Wordpress, but my guess is that something gets wrong when the second inner loop (places) modifies the first inner loop (resources), main loop being the Destination post query.

![New Project](https://user-images.githubusercontent.com/3173080/209759369-ce9b28f0-6b93-4218-99c0-5c8e55ddfbd0.jpg)

### Steps to reproduce

Create a custom type Destination.
Create a custom type Resources.
Create a custom type Places.

Add ACF relations:
Destination has a "relationship" with Resources
Resources has a "relationship" with Places

Create a loop item for Place

Create a loop item for Resource, containing a grid loop of places.

Createa single post template for Destination, containing a grid loop of Resources.

For the query of the grid loop widget, I'm using a "_Dynamic Related Posts_" query (thanks to Advanced Post Queries plugin) and "_Post is in Current Post Custom Field_" for the type of relation.

Insert an Elementor Block for Gutenberg in a Resource content, set to a template displaying a grid loop of places item.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.32
	PHP Version: 8.1.12
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://digitalnomading.life
	Home URL: https://digitalnomading.life
	WP Multisite: No
	Max Upload Size: 300 Mo
	Memory limit: 640M
	Max Memory limit: 640M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Zurich
	Admin Email: jonathan.gerbaud@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.0
		Author: Shabti Kaplan

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	Happy Elementor Addons
		Version: 3.7.2
		Author: weDevs

	Instant Images
		Version: 4.6.2
		Author: Darren Cooney

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	Wordfence Security
		Version: 7.8.2
		Author: Wordfence

	WP Armour - Honeypot Anti Spam
		Version: 2.0.1
		Author: Dnesscarkey

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation

== Utilisation des éléments ==
	
	footer : 1
		heading : 1
	header : 1
		image : 1
		nav-menu : 1
		theme-site-title : 1
	section : 3
		button : 1
		heading : 1
		loop-grid : 1
		template : 1
		text-editor : 1
	widget : 0
		template : 1
	wp-post : 0
		button : 1
		heading : 5
		image : 2
		loop-grid : 2
		template : 1
		text-editor : 1
	single-post : 2
		heading : 2
		loop-grid : 3
		template : 1
		theme-post-content : 1
		theme-post-title : 1
	loop-item : 10
		button : 2
		heading : 4
		post-info : 1
		spacer : 1
		theme-post-content : 2
		theme-post-title : 1

== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de site pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	En-tête et pied de page du thème Hello: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut
	Lazy Load Background Images: Inactif par défaut
	Save as Default: Actif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Boucle: Actif par défaut
	Envois de formulaire: Actif par défaut
	Accroche de défilement: Actif par défaut

== Journal ==
	
PHP: showing 13 of 13PHP: 2022-12-23 03:56:58 [notice X 2573][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-12-23 06:03:45 [notice X 624][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-23 08:33:11 [warning X 27][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-23 09:49:47 [warning X 3][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-23 11:15:55 [warning X 82][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-12-23 11:55:10 [notice X 5][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/query-builder.php(1153): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(520): ElementorPro\Core\Database\Query_Builder -> update()
',
)]
PHP: 2022-12-23 12:11:10 [warning X 1][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-includes/rest-api/class-wp-rest-server.php(1171): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2022-12-26 08:53:48 [notice X 14][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-26 09:55:26 [notice X 6][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/query-builder.php(1081): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/core/database/model-query-builder.php(89): ElementorPro\Core\Database\Query_Builder -> get()
',
)]
PHP: 2022-12-26 17:28:44 [notice X 5][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-27 10:35:40 [warning X 1][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-27 10:57:50 [notice X 14][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4: /home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2022-12-27 12:12:16 [warning X 1][/home/clients/efeffbf50e212663cfa8888e36003442/sites/digitalnomading.life/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-12-27 04:42:03 [error X 3050][https://digitalnomading.life/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-12-27 04:42:05 [error X 55][https://digitalnomading.life/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Non compatible
	Happy Elementor Addons: Non compatible

== Elementor Pro - Compatibility Tag ==
	
	Happy Elementor Addons: Non compatible

**Comment by jonathangerbaud** [comment]
More info about this. Looks like the class associated with the section is switching to template id in the middle of the loop.

`
...
<div data-elementor-type="loop-item" data-elementor-id="180" class="elementor elementor-180 e-loop-item-280 e-loop-item">...</div>
<div data-elementor-type="loop-item" data-elementor-id="180" class="elementor elementor-180 e-loop-item-120 e-loop-item">...</div>
<div data-elementor-type="loop-item" data-elementor-id="629" class="elementor elementor-629 e-loop-item-118 e-loop-item">...</div>
<div data-elementor-type="loop-item" data-elementor-id="629" class="elementor elementor-629 e-loop-item-191 e-loop-item">...</div>
`

As you can see, the template id for this grid loop is 180.
But when the second item includes itself another grid loop, then the next items are changing the template id to 629. Hence messing up the CSS.

**Comment by nicholaszein** [comment]
Hello @jonathangerbaud,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Elementor does not support Nested Loop Grids. 
You can't place a Loop Grid inside a Loop Grid.

If you're looking to add this functionality you'll need to use a 3rd party add-on that supports it. We might look into adding this feature in the future, but for the time being there are no plans to support nested Loop Grids.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

Kind regards
