### ISSUE TITLE
Some of Google's fonts don't show

### ISSUE THREAD

**Issue by dhup1117** [elementor/elementor#20864]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Kantumruy Pro  google font doet not support

### Describe the solution you'd like

support all google free font

**Comment by rami-elementor** [comment]
Added in Elementor 3.11.

See PR: https://github.com/elementor/elementor/pull/21073
