### ISSUE TITLE
⛔ 🐞 Bug Report: The editing section in elementor keeps loading in an infinite loop

### ISSUE THREAD

**Issue by Puzulu** [elementor/elementor#20880]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The editing section in elementor keeps loading in an infinite loop and does not allow you to edit anything on the site

### Steps to reproduce

Edit with elementor

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

#20879 #20790
![Opera Captura de pantalla_2022-12-29_144229_odelot space](https://user-images.githubusercontent.com/121633381/209995624-e7edcffd-919c-4bac-85f9-325c90525a26.png)
![Opera Captura de pantalla_2022-12-29_144229_odelot space](https://user-images.githubusercontent.com/121633381/209995787-5b9d6457-c1ed-4cb7-ac2c-7eb0c593e4d2.png)

**Comment by nicholaszein** [comment]
Hello @Puzulu,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

The issue you're reporting is usually related to low server resources, or too many 3rd-party add-on widgets being loaded on your website.

You can follow the documentation in the Help Center to help fix your issue:

https://elementor.com/help/elementor-widget-panel-not-loading/

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
