### ISSUE TITLE
⛔ 🚀 Feature Request: On Elementor -> System Info -> Element Usage add columns to indicate which plugins being used

### ISSUE THREAD

**Issue by joehdevwp** [elementor/elementor#20889]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Elementor's 'Element Usage' section of System Info already is aware of and counts the number of widgets and (generally) where they are but does not indicate which plugins they are coming from. 

There is currently no good way I know of to identify which widgets are being used without opening each and every page and looking through the navigator. 

The 'problem' here is one of wanting to deactivate un-used widgets being supplied by 3rd party elementor addons. Most addon packs allow you to toggle widgets on/off to optimize performance but it can be difficult to know which ones can be safely deactivated. 

### Describe the solution you'd like

Add column(s) to the Element Usage section that returns the name(s) of the plugins that are supplying the widgets. 

e.g. a site may have 67 buttons, but which elementor addons if any are those buttons coming from?  By seeing the names of the plugin it may be much easier to consolidate, eliminate or deactivate widgets. 

### Describe alternatives you've considered

Opening each page and template one at a a time and using the navigator to determine widgets used/not used.

**Comment by nicholaszein** [comment]
Hello @joehdevwp,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap. 

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
