### ISSUE TITLE
elementor in 2023

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20896]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team, happy New Year! We hope this year will be a great year for Elementor.

We are really happy that Elementor is getting stronger every year. As a suggestion, it would be really great to release Elementor's development roadmap in 2023 at the beginning of the year. This makes everything go well. It also creates great enthusiasm for users.

Some of the features that I am personally looking forward to are listed below in order of priority (in my opinion). I hope they will be in the 2023 roadmap.

1- display conditions (https://github.com/elementor/elementor/issues/4246)
2- megamenu (https://github.com/elementor/elementor/issues/3275)
3- preset style (https://github.com/elementor/elementor/issues/965)
5- css Grid (https://github.com/elementor/elementor/issues/18839)
4- nested slider (https://github.com/elementor/elementor/issues/2587)
6- Menu cart widget custom icon

### Describe the solution you'd like

public road map. This is what Elementor users appreciate.

**Comment by lensbreak** [comment]
I agree with that list, I probably would even make **Megamenu to prirority No.1**
Such an essential feature and elementor still does not have it years after years. Really?

**Comment by toineenzo** [comment]
Mega menu is in the making. The nested elements experiment is the start of this. For now only with tabs.

**Comment by lensbreak** [comment]
Oh and also my most missed tooling feature: **Cross-Domain Copy-Past.**

**Comment by Michaelgimii** [comment]
> Oh and also my most missed tooling feature: **Cross-Domain Copy-Past.**

a good news!

It seems that Elementor plans to introduce this feature in the next version (3.11.0).

**Comment by rami-elementor** [comment]
**Elementor Roadmap and Focus for 2023**

(Jan 23, 2023)

https://www.facebook.com/events/729536915114918/?acontext=%7B%22ref%22%3A%2252%22%2C%22action_history%22%3A%22[%7B%5C%22surface%5C%22%3A%5C%22share_link%5C%22%2C%5C%22mechanism%5C%22%3A%5C%22share_link%5C%22%2C%5C%22extra_data%5C%22%3A%7B%5C%22invite_link_id%5C%22%3A501567902063706%7D%7D]%22%7D

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the first beta implementation of the Grid Container is live! 🙌 

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪 

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards
