### ISSUE TITLE
🚀 Feature Request: Add VW to margin and padding and elsewhere! - [ED-9743]

### ISSUE THREAD

**Issue by godlesowned** [elementor/elementor#20890]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi, im building super responsive websites and i always need to add selector { margin: 1vw; } instead of using native elementor. 

### Describe the solution you'd like

Can you add everywhere choose to use VW?

**Comment by rodolphebertozzo** [comment]
Hi, the CSS unit vw (viewport width) is designed to specify the dimensions according to the width of the viewport, so I added it to the margins and padding, it already appears for the width in all elements, there is just for the divider that I opened separate PR.
