### ISSUE TITLE
⛔ 🐞 Bug Report: Activating Elementor Pro breaks Learndash course display

### ISSUE THREAD

**Issue by jruperto100** [elementor/elementor#20912]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am not sure if this can be posted or solved here but Elementor support could not help and suggested I post in here.
Upon activating Elementor Pro, my layouts for Learndash courses are no longer visible.
I have tried the steps listed above and this issue only happens when elementor pro is active, once deactivated the issue is gone.

### Steps to reproduce

Activate Elementor, Pro and Learndash.
goto course archive
click on a course
course overview page does not display.
deactivate elementor pro
course overview page will display.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.6.3
	PHP Version: 8.1.11
	PHP Memory Limit: 2047M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://fithappens.ca
	Home URL: https://fithappens.ca
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 2047M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Vancouver
	Admin Email: support@fithappens.ca
	Debug Mode: Inactive

== Theme ==
	Name: BuddyBoss Child
	Version: 1.0.1
	Author: BuddyBoss.com
	Child Theme: Yes
	Parent Theme Name: BuddyBoss Theme
	Parent Theme Version: 2.2.2
	Parent Theme Author: BuddyBoss

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.6
		Author: WP Engine

	Breeze
		Version: 2.0.14
		Author: Cloudways

	BuddyBoss Platform
		Version: 2.2.3
		Author: BuddyBoss

	BuddyBoss Platform Pro
		Version: 2.2.3
		Author: BuddyBoss

	BuddyPress Integration for WooCommerce Premium
		Version: 3.4.12
		Author: ThemeKraft

	CartFlows
		Version: 1.11.8
		Author: CartFlows Inc

	CartFlows Pro
		Version: 1.11.8
		Author: CartFlows Inc

	Code Snippets
		Version: 3.2.2
		Author: Code Snippets Pro

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.8.3
		Author: Dynamic.ooo

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	GPL Times
		Version: 3.2.3
		Author: Abhijeet Mandal

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	Kadence Blocks – Gutenberg Blocks for Page Builder Features
		Version: 2.4.22
		Author: Kadence WP

	LearnDash LMS
		Version: 4.4.1.2
		Author: LearnDash

	LearnDash LMS - Achievements
		Version: 1.1.1
		Author: LearnDash

	LearnDash LMS - Course Grid
		Version: 2.0.7
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - Notifications
		Version: 1.5.4
		Author: LearnDash

	LearnDash LMS - WooCommerce Integration
		Version: 1.9.6
		Author: LearnDash

	Mailchimp for WooCommerce
		Version: 2.7.6
		Author: Mailchimp

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 4.84
		Author: MalCare Security

	Maximum Products per User for WooCommerce
		Version: 3.8.1
		Author: WPFactory

	Maximum Products per User for WooCommerce Pro
		Version: 3.5.6
		Author: WPFactory

	Profile Builder
		Version: 3.8.6
		Author: Cozmoslabs

	Profile Builder Pro
		Version: 3.8.5
		Author: Cozmoslabs

	SEOPress
		Version: 6.2.0.2
		Author: The SEO Guys at SEOPress

	SEOPress PRO
		Version: 6.2.0.1
		Author: The SEO Guys at SEOPress

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps

	WooCommerce
		Version: 7.2.2
		Author: Automattic

	WooCommerce Bookings
		Version: 1.15.69
		Author: WooCommerce

	WooCommerce Bookings Availability
		Version: 1.1.25
		Author: WooCommerce

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.21
		Author: CartFlows Inc

	WooCommerce Email Customizer
		Version: 1.4.0
		Author: WooCommerce

	WooCommerce Memberships
		Version: 1.24.0
		Author: SkyVerge

	WooCommerce Order Status Control
		Version: 1.15.0
		Author: SkyVerge

	WooCommerce Smart Coupons
		Version: 7.0.0
		Author: StoreApps

	WooCommerce Stripe Gateway
		Version: 7.0.1
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 4.7.0
		Author: WooCommerce

	WP AutoTerms
		Version: 2.5.0
		Author: WP AutoTerms

== Must-Use Plugins ==
	ET Support Center :: Must-Use Plugins Autoloader
		Version: 
		Author: Elegant Themes

	Health Check Troubleshooting Mode
		Version: 1.8.1
		Author: 

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	Object Cache Pro (MU)
		Version: 1.17.0
		Author: Rhubarb Group

	WP Migrate DB Compatibility
		Version: 1.2
		Author: Delicious Brains

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Landing Pages: Active
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 252022-12-07 17:20:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 17:20:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-15 07:48:38 [info] elementor::elementor_updater Started 
2022-12-15 07:48:38 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-15 07:48:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-15 07:48:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-21 08:17:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-21 08:17:21 [info] elementor::elementor_updater Started 
2022-12-21 08:17:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-21 08:17:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-21 08:17:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-21 08:17:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-21 09:03:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2022-12-22 11:50:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.8.2',
  'to' => '2.8.3',
)]
2022-12-29 08:51:40 [info] elementor-pro::elementor_pro_updater Started 
2022-12-29 08:51:40 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-29 08:51:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-29 08:51:41 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-12-29 08:51:41 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-12-29 08:51:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.9.2',
)]

PHP: showing 11 of 11PHP: 2022-11-19 20:37:21 [notice X 2][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/mailchimp.php::345] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-12 09:49:43 [warning X 2][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-15 13:51:59 [warning X 1][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-19 10:55:33 [warning X 1][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::383] Undefined array key "display" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-21 08:16:12 [error X 1][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/plugin.php::848] Uncaught Error: Class "Elementor\Data\Manager" not found in /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/plugin.php:848
Stack trace:
#0 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php(137): Elementor\Plugin->__get()
#1 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/core/app/app.php(85): ElementorPro\Core\App\Modules\SiteEditor\Module->__construct()
#2 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/plugin.php(443): ElementorPro\Core\App\App->__construct()
#3 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/plugin.php(109): ElementorPro\Plugin->__construct()
#4 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/plugin.php(472): ElementorPro\Plugin::instance()
#5 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/home/614424.cl...')
#6 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(308): elementor_pro_load_plugin()
#7 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-settings.php(480): do_action()
#10 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-config.php(98): require_once('/home/614424.cl...')
#11 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-load.php(50): require_once('/home/614424.cl...')
#12 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-blog-header.php(13): require_once('/home/614424.cl...')
#13 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/index.php(17): require('/home/614424.cl...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-21 08:17:23 [notice X 3027][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-28 10:34:45 [warning X 2][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-29 08:51:41 [warning X 1][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-30 10:51:47 [error X 2][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::2412] Uncaught TypeError: Elementor\Controls_Stack::sanitize_settings(): Argument #1 ($settings) must be of type array, null given, called in /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1107 and defined in /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php:2412
Stack trace:
#0 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1107): Elementor\Controls_Stack->sanitize_settings()
#1 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2161): Elementor\Controls_Stack->get_data()
#2 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1121): Elementor\Core\Base\Base_Object->get_settings()
#5 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1210): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#6 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/modules/code-highlight/widgets/code-highlight.php(47): Elementor\Controls_Stack->get_settings_for_display()
#7 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/element-base.php(137): ElementorPro\Modules\CodeHighlight\Widgets\Code_Highlight->get_script_depends()
#8 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(527): Elementor\Element_Base->enqueue_scripts()
#9 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/preview.php(293): Elementor\Widgets_Manager->enqueue_widgets_scripts()
#10 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/preview.php(104): Elementor\Preview->enqueue_scripts()
#11 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(308): Elementor\Preview->Elementor\{closure}()
#12 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#13 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#14 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/script-loader.php(2180): do_action()
#15 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#16 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#17 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#18 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/general-template.php(3043): do_action()
#19 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/themes/buddyboss-theme/header.php(17): wp_head()
#20 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/template.php(783): require_once('/home/614424.cl...')
#21 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/template.php(718): load_template()
#22 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/general-template.php(48): locate_template()
#23 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header()
#24 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/template-loader.php(106): include('/home/614424.cl...')
#25 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-blog-header.php(19): require_once('/home/614424.cl...')
#26 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/index.php(17): require('/home/614424.cl...')
#27 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-30 11:23:28 [notice X 47][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::554] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-02 08:40:47 [error X 13][/home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::2412] Uncaught TypeError: Elementor\Controls_Stack::sanitize_settings(): Argument #1 ($settings) must be of type array, null given, called in /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1107 and defined in /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php:2412
Stack trace:
#0 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1107): Elementor\Controls_Stack->sanitize_settings()
#1 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2161): Elementor\Controls_Stack->get_data()
#2 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#3 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#4 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1121): Elementor\Core\Base\Base_Object->get_settings()
#5 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1210): Elementor\Controls_Stack->get_parsed_dynamic_settings()
#6 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor-pro/modules/code-highlight/widgets/code-highlight.php(47): Elementor\Controls_Stack->get_settings_for_display()
#7 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/base/element-base.php(137): ElementorPro\Modules\CodeHighlight\Widgets\Code_Highlight->get_script_depends()
#8 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/managers/widgets.php(527): Elementor\Element_Base->enqueue_scripts()
#9 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/preview.php(293): Elementor\Widgets_Manager->enqueue_widgets_scripts()
#10 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/plugins/elementor/includes/preview.php(104): Elementor\Preview->enqueue_scripts()
#11 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(308): Elementor\Preview->Elementor\{closure}()
#12 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#13 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#14 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/script-loader.php(2180): do_action()
#15 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts()
#16 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#17 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#18 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/general-template.php(3043): do_action()
#19 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/themes/buddyboss-theme/header.php(17): wp_head()
#20 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/template.php(783): require_once('/home/614424.cl...')
#21 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/template.php(718): load_template()
#22 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/general-template.php(48): locate_template()
#23 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-content/themes/buddyboss-theme/single.php(10): get_header()
#24 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-includes/template-loader.php(106): include('/home/614424.cl...')
#25 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/wp-blog-header.php(19): require_once('/home/614424.cl...')
#26 /home/614424.cloudwaysapps.com/frcbxqhjtt/public_html/index.php(17): require('/home/614424.cl...')
#27 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2022-11-25 16:39:00 [error X 94][https://fithappens.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:367749] Cannot read properties of undefined (reading \'controls\') 
JS: 2022-12-12 17:45:51 [error X 7][https://fithappens.ca/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.0:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-12-19 01:43:17 [error X 5][https://fithappens.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:1068257] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-12-21 22:00:45 [error X 12][https://fithappens.ca/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2023-01-02 18:33:22 [error X 1][https://fithappens.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:655306] this.model.isValidChild is not a function 
JS: 2023-01-03 23:21:34 [error X 2][https://fithappens.ca/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.9.2:2:60518] Cannot convert undefined or null to object 

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	LearnDash LMS - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @jruperto100,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

It seems your site might be running an incompatible version of the **LearnDash LMS - Elementor** add-on. It would be wise to contact LearnDash and ask them to check if there is an incompatibility with the latest version of both Elementor and Elementor Pro. They are the ones responsible for maintaining this integration add-on.

Also, make sure you have followed [their documentation](https://www.learndash.com/support/docs/add-ons/compatibility/#elementor_integration) for installing and using the integration with Elementor.

For now, that's all we can help you with. If you think this is still a bug caused by Elementor, please submit a new bug report and provide a complete copy of the errors you're reporting (if any). This could be a screenshot, a screen recording, or anything else that would help us better identify your issue.

Kind regards
