### ISSUE TITLE
✅ 🚀 Feature Request: Conditional display of the favorite widgets section in the editor - [ED-9471]

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20939]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor!

In the editor, even if we have not added any widgets to favorites, the favorites section is displayed.

![editor](https://user-images.githubusercontent.com/88034902/211168915-a078bc78-dfed-4962-9d54-b894f55deb90.png)

**But it is not interesting that there is no widget but it is displayed.**

### Describe the solution you'd like

**It is much better to hide the favorites widgets section by default. When we add a widget to a favorite, this section will appear in the editor.**

As another suggestion, I think the name "favorite" is not interesting In a page builder (This name reminds more of an online store). But the name "pinned widgets" is much better. @arielk , @KingYes.

thanks

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

thanks for submitting your feature request! 🙏 

This is something we are considering for the Favorite Widgets feature, and we will think of a way to make it more intuitive, logical, and responsive to our users. This might be part of a greater effort to improve the workflow. Stay tuned. 😉 

Best regards

**Comment by black-eye** [comment]
+1 Yes please. Give is the option to disable this feature or at least, don’t show it when empty.

This should be a part of a more complex functionality, allowing us to turn on/off most of the features, including the widgets themselves.

**Comment by 79ho3ein** [comment]
+1
The favorites section really needs to be improved. I totally agree with you about renaming it to "pinned".
In addition, I think the method of adding it to interest should be changed. Right-clicking on the widget now displays a large button, which isn't visually appealing. It will be much simpler and more beautiful to display a simple icon on each widget that is displayed during the hover.
