### ISSUE TITLE
✅ 🐞 Column padding breaks if experiment "optimize DOM output" is disabled

### ISSUE THREAD

**Issue by qantumthemes** [elementor/elementor#20936]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This issue was existing 3 versions ago, was fixed and is back again.
If you disable "optimize DOM output", the internal padding of the columns doesn't produce any output. It appears to be an error in the CSS output of the Column element, which does't fix the selector depending on this option.

I made a video for you

https://www.dropbox.com/s/clm7w1jpzminc0m/Elementor%20columns%20bug%20scr%202023-01-07%20at%2010.51.04.mov?dl=0

### Steps to reproduce

1) Make a column with some padding
2) Disable "optimize dom output"
3) Check back your column

VIDEO:
https://www.dropbox.com/s/clm7w1jpzminc0m/Elementor%20columns%20bug%20scr%202023-01-07%20at%2010.51.04.mov?dl=0

Happens with any theme.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.37
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://demo.pro.radio/pod6
	Home URL: https://demo.pro.radio/pod6
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Podowpress Child
	Version: 1.0.0
	Author: Qantum Themes
	Child Theme: Yes
	Parent Theme Name: PodwoPress
	Parent Theme Version: 1.2.8
	Parent Theme Author: Qantum Themes SL

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.2
		Author: Elementor.com


== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Lazy Load Background Images: Inactive
	Save as Default: Inactive


== Log ==
	
PHP: showing 2 of 2PHP: 2022-11-13 12:32:45 [warning X 13][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::269] Cannot modify header information - headers already sent by (output started at ../wp-includes/functions.php:5383) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-28 14:38:35 [notice X 3][../wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2022-11-13 13:21:44 [error X 24]../wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=6.1:8:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-14 13:04:38 [error X 8]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-28 10:25:55 [error X 1]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:768952] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-12-01 11:16:03 [error X 4]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:769459] Cannot read properties of undefined (reading \'localized\') 

Log: showing 11 of 112022-11-14 08:40:12 [info] elementor::elementor_updater Started 
2022-11-14 08:40:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-14 08:40:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-14 08:40:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-14 08:40:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-12-29 16:49:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.2',
)]
2022-12-29 16:49:35 [info] elementor::elementor_updater Started 
2022-12-29 16:49:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-29 16:49:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-29 16:49:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.2',
)]
2022-12-29 16:49:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.2',
)]



== Elementor - Compatibility Tag ==
	


````

</details>

**Comment by nicholaszein** [comment]
Hello @qantumthemes! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @qantumthemes!

As of version 3.19 the `Optimize DOM output` experimental feature was merged into Core, and is now the default and only option for the DOM output. This change was made so we can continue reducing the DOM size from now forward, and we have no plans to remove it.

From our tests using the latest version of Elementor with Sections and Columns, with the merged `Optimize DOM output` experiment active, we see no problem with padding on columns. If you use custom CSS, make sure you follow the instructions in [this article](https://elementor.com/help/what-is-the-optimized-dom/) to adjust it to make it work with the current version.

It's important to emphasize that this experiment was introduced back in 2020, in version 3.0, and was always meant to be merged to Core. We gave our users the option to migrate to the new output on their time, and now, 4 years later, it's time to move forward. With these changes now being part of Core, we can focus on improving the DOM output further, and making Elementor load faster. We hope you can understand.

I'm closing this issue as solved.

Kind regards
