### ISSUE TITLE
Bug (?) - Drop Caps are only working if the Letter / Character has no BOLD / Strong style

### ISSUE THREAD

**Issue by Manuel-SG** [elementor/elementor#2094]
Strange behaviour - the drop caps are not working, if the first word / first character has a **< strong >** style. If it is bold, no drop cap is created. If I remove the bold styling, the letter is recognized and the drop cap is working fine.
See also: https://www.facebook.com/groups/Elementors/permalink/1225015244290926/

Tested in Elementor v1.55 and v1.6beta RC2.

**Comment by DrDarbin** [comment]
I have the same issue

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
