### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor\Widgets_Manager::register_widget_type is oudated after 3.5.0

### ISSUE THREAD

**Issue by RensSchipper2** [elementor/elementor#20955]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating to Elementor 3.10.0 and Elementor Pro 3.10.0 my website showed errors;

Deprecated: Hook elementor/widgets/widgets_registered is sinds versie 3.5.0 verouderd! Gebruik in plaats daarvan elementor/widgets/register. in /var/www/vhosts/dezo.eu/test.dezo.eu/wp-includes/functions.php on line 5758

After deactivating experiments the errors were still there.
After deactivating all pluggins exept Elementor and Elementor Pro erros were gone.
After activating Royal Elementor Addons (WP Royal) errors came back.
After activating all plugins except Royal Elementor Addons errors are gone.

### Steps to reproduce

After deactivating experiments the errors were still there.
After deactivating all pluggins exept Elementor and Elementor Pro erros were gone.
After activating Royal Elementor Addons (WP Royal) errors came back.
After activating all plugins except Royal Elementor Addons errors are gone.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 768M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://test.dezo.eu
	Home URL: https://test.dezo.eu
	WP Multisite: No
	Max Upload Size: 768 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: Europe/Amsterdam
	Admin Email: rens.schipper@dezo.eu
	Debug Mode: Active

== Theme ==
	Name: Royal Elementor Kit
	Version: 1.0.98
	Author: WP Royal
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0.2
		Author: Automattic

	All-in-One WP Migration
		Version: 7.69
		Author: ServMask

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Elementor
		Version: 3.10.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0
		Author: Elementor.com

	Jetpack
		Version: 11.6
		Author: Automattic

	Jetpack Protect
		Version: 1.1.2
		Author: Automattic - Jetpack Security team

== Gebruik van elementen ==
	
	page : 2
		heading : 2
		spacer : 2
		text-editor : 2
	section : 6
		button : 4
		form : 1
		heading : 16
		icon : 4
		image : 1
		nav-menu : 1
		search-form : 1
		spacer : 36
		text-editor : 6
		wpr-sharing-buttons : 1
	wp-page : 15
		blockquote : 1
		button : 35
		counter : 1
		divider : 2
		form : 5
		heading : 131
		icon : 28
		image : 30
		nav-menu : 15
		search-form : 15
		spacer : 489
		text-editor : 146
		wpr-sharing-buttons : 15

== Instellingen ==
	
	cpt_support: page, wpr_templates, wpr_mega_menu
	allow_tracking: yes
	unfiltered_files_upload: 1

== Eigenschappen ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Inactief
	Verbeterd laden van assets: Inactief
	Verbeterd laden van CSS: Inactief
	Pictogrammen inline lettertype: Inactief
	Toegang verbeteringen: Inactief
	Extra aangepaste onderbrekingspunten: Inactief
	Verberg verouderde WordPress widgets voor zoekresultaten: Inactief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Actief
	Default to New Theme Builder: Inactief
	Landingspagina&#039;s: Inactief
	Nested Elements: Inactief
	Lazy-load achtergrondafbeeldingen: Inactief
	Opslaan als standaard: Inactief
	Page Transitions: Inactief
	Notes: Inactief
	Loop: Inactief
	Form Submissions: Inactief
	Scroll Snap: Inactief

== Log ==
	
PHP: showing 3 of 3PHP: 2022-10-21 08:30:11 [notice X 1][/var/www/vhosts/dezo.eu/test.dezo.eu/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property &#039;email&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-22 15:40:37 [notice X 9][/var/www/vhosts/dezo.eu/test.dezo.eu/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-23 14:48:21 [notice X 2][/var/www/vhosts/dezo.eu/test.dezo.eu/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-10-22 16:19:54 [error X 34][https://test.dezo.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060990] $ is null 
JS: 2022-10-23 12:17:44 [error X 650][https://test.dezo.eu/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2023-01-05 14:05:58 [error X 1][https://test.dezo.eu/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51816] a is undefined 
JS: 2023-01-06 11:05:25 [error X 1][https://test.dezo.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:889730] $e.routes.getHistory(...).reverse()[0] is undefined 
JS: 2023-01-06 11:06:16 [error X 2][https://test.dezo.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:578766] elementor.documents.getCurrent() is null 

Log: showing 14 of 142022-10-30 20:40:35 [info] elementor::elementor_updater Started 
2022-10-30 20:40:35 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-30 20:40:35 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-30 20:40:35 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-30 20:40:35 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-30 20:40:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-30 20:40:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-30 20:40:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-04 09:42:57 [info] elementor-pro::elementor_pro_updater Started 
2022-11-04 09:42:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-04 09:42:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-04 09:42:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-04 09:42:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-04 09:42:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Niet compatibel

== Elementor Pro - Compatibility Tag ==

**Comment by rami-elementor** [comment]
One of your Elementor addon is using outdated code.

You need to find the addon, contact the addon developer and ask him to update the code.

We provide information on our deprecation process: https://developers.elementor.com/docs/deprecations/

In your case, the error you attached is simple to fix, we even have an example how to fix it https://developers.elementor.com/docs/deprecations/advanced-example/

But this is something that should be done by the addon developer.

**Comment by nicholaszein** [comment]
Hello @RensSchipper2,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

It seems the **Royal Elementor Addons** is the plugin causing the incompatibility issue, and Elementor is warning you that it is incompatible.

As Rami mentioned above, contact the add-on developer and ask them to fix the incompatibility.

For now that's all we can help you with.

Kind regards
