### ISSUE TITLE
🔗 🚀 Feature Request: export form submissions (csv file) programmatically (Duplicate of #17775)

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#20953]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Using CRON to expost form submissions (questionnaire) for analysis.
The csv format is required, and no hook provides it.

The feature is to show daily update of submissions statistics.

Currently web-cli is used to download the csv manually.
If there is a way to activate it using CRON, it would be nice. 

### Describe the solution you'd like

A simple hook : `/elemetor/form/submissions/export ` and even  `/elemetor/form/submissions/export /{form-id}`
acticvated by `add_action()` like cron.

The hook will provide the data in CSV format, allowing the developer limitless options on 
using it to its needs

### Describe alternatives you've considered

Must do it manually: 
admin-panel>>Elementor>form>leads>select the relevant form id (assume there are dozens!) then CLICK TO DOWNLOAD CSV

### Additional context

Its missing for years now.

**Comment by nicholaszein** [comment]
Hello @Mulli,

thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap for the time being. 

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.

Best regards

**Comment by nicholaszein** [comment]
### 📅  This request is scheduled to be Migrated to the new [Discussions](https://github.com/elementor/elementor/discussions/categories/feature-request) section.

Please do not duplicate this request.

Once we migrate it, we encourage you to cast your **⬆️ Upvote** on the first comment if you feel it should be considered for our roadmap.

**Comment by nicholaszein** [comment]
Hello, @Mulli!

### 🔗 🚀 There is already a similar request submitted by someone here #17775

Feel free to continue the conversation there! 👉

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards,

Nick
