### ISSUE TITLE
⛔ 🚀 Feature Request: Lifetime Payment and updates.

### ISSUE THREAD

**Issue by albridi** [elementor/elementor#20954]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi, I'm not sure if this is the best place for this request, but: I would like to buy Elementor Pro and I hate subscriptions. In fact, I was a Macromedia Studio MX user and when Adobe made my products impossible to update, I migrated my websites from Dreamweaver to WordPress and Elementor. I lost valuable software this way and Adobe lost a customer who would be upgrading their software for life.

### Describe the solution you'd like

It would be great if you consider the lifetime purchase model as an option. Maybe you could consider what other software developers do: They have upgrade programs that let you upgrade for great new features only if you think you can't live without them, while they continuing to perform maintenance updates to the software version you've purchased. Thanks and regards.

**Comment by nicholaszein** [comment]
Hello @albridi,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
