### ISSUE TITLE
⛔ 🚀 Feature Request: Allow us to add a class to popups that appears when it's visible

### ISSUE THREAD

**Issue by AndreasH08** [elementor/elementor#20964]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I want to create a jQuery code that activates when the popup is open, but as far as I can tell, the only thing that changes when it opens and closes, is that a display: none code is added and removed.

### Describe the solution you'd like

I would love if there was a either a class added to the popups when they open, or the ability to add our own classes that gets added when it opens.

### Describe alternatives you've considered

I've yet to make it work, but the only alternative I've found is to give it a class through jQuery when it opens

### Additional context

I'm trying to build a mega menu only using Elementor, but I need to give my navigation a class when the popup is open

**Comment by nicholaszein** [comment]
Hello @AndreasH08,

### ✔️ the feature you're requesting already exists!

You can use the following hook to listen to when a popup is shown:

````js
// wait for the page to load
jQuery( document ).ready( function() {
  // listen to when the popup is shown
  jQuery(document).on('elementor/popup/show', ( event, id, instance ) => {
      // the id of the popup template
      if ( id == 123) {
        // do something here
      }
  });
});
````

In the same way, you can use the following hook to listen to when a popup is hidden:

````js
// wait for the page to load
jQuery( document ).ready( function() {
  // listen to when the popup is shown
  jQuery(document).on('elementor/popup/hide', ( event, id, instance ) => {
      // the id of the popup template
      if ( id == 123) {
        // do something here
      }
  });
});
````

I hope this helps.

Kind regards

**Comment by AndreasH08** [comment]
> Hello @AndreasH08,
> 
> ### ✔️ the feature you're requesting already exists!
> You can use the following hook to listen to when a popup is **shown**:
> 
> ```js
> // wait for the page to load
> jQuery( document ).ready( function() {
>   // listen to when the popup is shown
>   jQuery(document).on('elementor/popup/show', ( event, id, instance ) => {
>       // the id of the popup template
>       if ( id == 123) {
>         // do something here
>       }
>   });
> });
> ```
> 
> In the same way, you can use the following hook to listen to when a popup is **hidden**:
> 
> ```js
> // wait for the page to load
> jQuery( document ).ready( function() {
>   // listen to when the popup is shown
>   jQuery(document).on('elementor/popup/hide', ( event, id, instance ) => {
>       // the id of the popup template
>       if ( id == 123) {
>         // do something here
>       }
>   });
> });
> ```
> 
> In both cases you need to replace the `id == 123` _(intg)_ with the ID of the Popup Template you created if you want to target a specific popup. Otherwise just remove the _if statement_.
> 
> I hope this helps.
> 
> Kind regards

Thanks for the response. I had never thought of that, although I'm now having an issue where the code from elementor/popup/show is firing twice, once when it opens, and another time when it closes, meaning it overwrites the code for elementor/popup/hide :/

**Comment by AndreasH08** [comment]
@nicholaszein On this page, I have two buttons at the top, and the left one has been given a class called ".test", once the first popup opens, it's being given two classes, one of them adds a background to the button, however, because the show function runs twice, the background is never removed :/

https://eloomi.ashportfolio.dk/popup-mega-menu-test/
