### ISSUE TITLE
🔗 🚀 Feature Request: Improve Elementor Kit - "Replace Settings" Workflow (Duplicate of #20968)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20969]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be really great if we could remove the existing settings by transferring the kit.

### Describe the solution you'd like

We want to create import from website A and transfer to website B. After import on website B, a question is asked. Remove existing settings?
If we choose yes, all current content such as global color and font will be removed, and new content will be placed. This feature can be very useful.

**Comment by nicholaszein** [comment]
Hi @Michaelgimii!

Thank you for your submission! 🙏 

### 🔗 🚀 It seems you created a new request for the same thing requested in #20968.

Logically if you would import Plugin Settings from another site, you would inherently replace the current settings. So there is no need to separate this request. 

It would be better if you separated the requests for Settings, Custom Fonts, Custom Icons, etc., as these are features from Core and Pro...

But I digress, let me evaluate your original request, and if needed you can submit new separate requests.

Kind regards,

Nick
