### ISSUE TITLE
Reuse SVGs

### ISSUE THREAD

**Issue by Arian-c27** [elementor/elementor#20974]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

If I upload let's say a checkmark SVG that I will use it often in lists or whatever, the same SVG is embedded multiple times on the page

### Describe the solution you'd like

Embed the SVG file only the first time it is used, keep it hidden somewhere on the bottom of the page and then reference it if added multiple times

https://stackoverflow.com/a/35723187

**Comment by rami-elementor** [comment]
That is exactly how Elementor works...
