### ISSUE TITLE
⛔ 🚀 Feature Request: improve UI in global custom color

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#20978]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

If we have not added any custom colors in the global colors section, we will see a very poor UI (image below)

![Screenshot (982)](https://user-images.githubusercontent.com/103376243/211681455-efba5b24-fb72-4b97-9bc0-e916a7cfd52f.png)

### Describe the solution you'd like

Improve the user interface by removing some current sections. After clicking the Add Color button, the options will be displayed.

![Screenshot (983)](https://user-images.githubusercontent.com/103376243/211681787-2cd49630-818a-4488-8e76-6d9ea1d3103e.png)

**Comment by nicholaszein** [comment]
Hello @Joliamendi,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

The section is there intentionally to help the user understand they can add more colors and that they are custom.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
