### ISSUE TITLE
Square Peg google font is missing

### ISSUE THREAD

**Issue by quakeboy** [elementor/elementor#20971]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Add a beautiful google font

### Describe the solution you'd like

Accept my PR #20973  so the list gets updated.

### Describe alternatives you've considered

I tried using custom fonts, but I'd like to use this font in a elementor template kit that I'd to sell on ThemeForest and ThemeForest doesn't support custom fonts for Elementor template kits.

**Comment by hitsgee** [comment]
There is a pull request already in place for this. Hopefully Elementor include in the next release.

**Comment by rami-elementor** [comment]
Added in Elementor 3.11.

See PR: https://github.com/elementor/elementor/pull/21073
