### ISSUE TITLE
⛔ 🚀 Feature Request: Items Per Page in archive page - loop Grid widget.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20976]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

I recently ran into a problem with the Grid loop widget that I thought was a bug at first, but it's actually not a bug, but maybe fixable...

If we add the loop Grid widget in the archive page and place query on the current query, we cannot determine the number of posts per page using the Items Per Page option. This option does not work. Instead, we need to control this option through WordPress Settings > [Reading](https://prnt.sc/tJRM6xZPlB11).

This is what will confuse users. So I have two suggestions to solve this issue. Please check these if possible @avivu , @arielk 

### Describe the solution you'd like

1- If we add the loop Grid widget to the archive page, by changing the number of items in the Items Per Page option, this change will be applied directly to the WordPress settings. Therefore, we will not need to refer to the WordPress settings to determine the number of posts on each page. This is the best way.

2- If it is not possible to implement the above solution, it is better if we select the current query option in the loop Grid widget > query, the Items Per Page option in the Loop Grid settings is hidden, instead a message is displayed so that users know They can control this option from WordPress Settings > Reading.

Good luck.

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap. Here's why:

Elementor uses the default settings for Archive Pages, which is the correct and recommended way from WordPress. Changing this may cause pagination issues and a lot of incompatibilities with the default WP_QUERY. This is not possible, and our objective is to maintain compatibility with core WordPress functionality. Moreover, the options in question affect all queries, not only from one archive, and applying the change you're suggesting would mean every time a user decides to change the items per page, it would affect every other query. We must not forget that a website may have more than one Archive template and query.

For now, this is not something we will pursue.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by nicholaszein** [comment]
PS: Please do not tag the Elementor staff on your issues. We have procedures in place, and we all are following GitHub very closely. Tagging Elementor employees without any reason will only make it more time-consuming for us to evaluate other issues, and will take longer to answer yours as well. There is no problem in tagging one in a response inside a comment. But please do not tag Elementor staff on your issues. Thanks.
