### ISSUE TITLE
✅ 🚀 Feature Request: units for Transition Duration

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20997]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi team!

Currently, there is no unit for Transition Duration. We can have s and ms.
The current situation is very misleading. For example, add an image widget. In the hover section of this widget, in the Transition Duration option, the default unit is not specified. So I think this option is much needed.

### Describe the solution you'd like

Add s and ms units for all Transition Duration controls.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

This feature was added to almost all transition durations from various widgets in version 3.19.0, and improved in version 3.20.0.

You can now choose the units for transition duration, including setting custom ones! 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
