### ISSUE TITLE
⛔ 🐞 Bug Report: two nav menus

### ISSUE THREAD

**Issue by yeshabhavsar82** [elementor/elementor#21002]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My pages on the website are showing two menus

### Steps to reproduce

I am not sure

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.0.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://yeshasia.com
	Home URL: https://yeshasia.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@yeshasia.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

== Active Plugins ==
	CMP - Coming Soon & Maintenance Plugin
		Version: 4.1.6
		Author: NiteoThemes

	Easy Updates Manager
		Version: 9.0.14
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.11.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.1
		Author: Elementor.com

	Jetpack
		Version: 11.7
		Author: Automattic

	Simple Full Screen Background Image
		Version: 1.2.10
		Author: AMP-MODE

	Site Kit by Google
		Version: 1.90.1
		Author: Google

	Templates Patterns Collection
		Version: 1.1.30
		Author: ThemeIsle

	WP Reset
		Version: 1.97
		Author: WebFactory Ltd

	WP Super Cache
		Version: 1.9.2
		Author: Automattic

	Yoast SEO
		Version: 19.14
		Author: Team Yoast

== Must-Use Plugins ==
	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elements Usage ==
	
	header : 1
		container : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 3
		button : 4
		divider : 8
		gallery : 2
		heading : 27
		icon : 3
		icon-box : 4
		image : 11
		social-icons : 4
		text-editor : 15
	section : 2
		heading : 3
		image : 1
		media-carousel : 1
		text-editor : 1
	wp-page : 8
		button : 1
		call-to-action : 12
		divider : 4
		form : 1
		gallery : 4
		heading : 47
		icon : 1
		icon-box : 4
		image : 13
		media-carousel : 1
		progress : 3
		testimonial : 1
		text-editor : 17

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 402022-12-20 03:25:06 [info] elementor::elementor_updater Started 
2022-12-20 03:25:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-20 03:25:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-20 03:25:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2022-12-20 03:25:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2022-12-21 15:18:01 [info] elementor-pro::elementor_pro_updater Started 
2022-12-21 15:18:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-21 15:18:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-21 15:18:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-21 15:18:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-29 04:00:15 [info] elementor::elementor_updater Started 
2022-12-29 04:00:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-29 04:00:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-29 04:00:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev2',
  'to' => '3.11.0-dev3',
)]
2022-12-29 04:00:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev2',
  'to' => '3.11.0-dev3',
)]
2023-01-10 17:40:11 [info] elementor-pro::elementor_pro_updater Started 
2023-01-10 17:40:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-10 17:40:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-10 17:40:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-10 17:40:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]

PHP: showing 2 of 2PHP: 2022-12-31 01:25:13 [warning X 8][/home3/yeshasia/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key "referrer" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-13 11:37:36 [warning X 2][/home3/yeshasia/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @yeshabhavsar82,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

Your issue is most likely related to cache. Please clear/purge your cache and check again. You also might want to refine your performance optimization settings with the cache plugin to avoid causing issues to your website.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
