### ISSUE TITLE
❌ Elementor Broke my Site

### ISSUE THREAD

**Issue by dmsacco1011** [elementor/elementor#21016]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor is a bunch of crooks and they are trash. I stopped paying for their shitty software and now my site is completely broken.

### Steps to reproduce

1. Step one: verify If I own or am responsible for elementor
2. Step two: walk into oncoming traffic.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

no thanks

**Comment by toineenzo** [comment]
You stopped paying, didn't get new updates and now you are crying that your site is broken? Yeah right... grow up

**Comment by nicholaszein** [comment]
Hello @dmsacco1011,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick

PS: @toineenzo, thanks for the effort, but please leave it with us to answer issues. No matter what type of content is posted, make an effort to always add value to a conversation. Not everyone understands how things work.
