### ISSUE TITLE
✅ 🚀 Feature Request: Expand custom units to all widgets and areas

### ISSUE THREAD

**Issue by squadcar** [elementor/elementor#21011]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Love the new update with the ability to write custom units. That said, it's not implemented across the entirety of the widget library. Is this planned? And if not, I would suggest it should be. Couple examples where it's missing:

- Nav menu widget -> Toggle button icon size (no units available, forces pixels
- Product Images -> Pretty much everything

Those were just a couple spots I had open at the moment, but obviously it's fairly inconsistent at the moment.

### Describe the solution you'd like

Ideally we should be able to access the custom unit dialogue everywhere a unit input exists.

**Comment by nicholaszein** [comment]
Hello there @squadcar!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
