### ISSUE TITLE
🔗 🚀 Feature Request: The location of the customization sections, in the style tab > loop grid widget (Duplicate of #20667)

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#21024]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

When we activate the pagination in the loop grid widget, in the style tab, the pagination section is first and then the layout. 

### Describe the solution you'd like

In order to comply with UX, it is better to place the layout section first and then pagination.

![a](https://user-images.githubusercontent.com/103376243/212534082-b1aa1b59-1e39-4d02-b935-6efb6ff39134.png)

**Comment by nicholaszein** [comment]
Hey @Joliamendi!

### 🔗 🚀 There is already a similar request submitted by someone here #20667

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

Kind regards
