### ISSUE TITLE
✅ 🐞 Bug Report: If Google Fonts are disabled, there is no Default font selected in the Font Family control

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21025]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @rami-elementor , @nicholaszein 

If we disable Google fonts, in the typography settings, the font family section is empty.

![download](https://user-images.githubusercontent.com/88034902/212538203-470973ef-ff24-4107-9cb7-b8790553229b.png)

I think it would be better if "default" is displayed as a placeholder.

### Steps to reproduce

1- Disable Google fonts from Elementor settings.
2- In the Elementor editor, view the typography settings.

The Family option is empty by default.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
@Michaelgimii Please add your system info for debugging.

**Comment by Michaelgimii** [comment]
Hi @rami-elementor, I apologize for the delay.

[system-info-domain.com-30-01-2023.txt](https://github.com/elementor/elementor/files/10535916/system-info-domain.com-30-01-2023.txt)

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

This issue was solved in subsequent versions of Elementor.

![image](https://user-images.githubusercontent.com/113993460/232661347-6f393f09-f5be-41e7-8152-5e8708a06af2.png)
