### ISSUE TITLE
⛔ 🐞 Bug Report: Fatal Error Message after making updates in wordpress.

### ISSUE THREAD

**Issue by ResilientRise** [elementor/elementor#21037]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am getting this code on my website:

Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home1/resilient/public_html/wp-content/plugins/modal-for-elementor/widgets/popup.php:185 Stack trace: #0 /home1/resilient/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2327): ElementorModal\Widgets\ElementorModal->_register_controls() #1 /home1/resilient/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls() #2 /home1/resilient/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack() #3 /home1/resilient/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack() #4 /home1/resilient/public_html/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\Controls_Stack->get_controls() #5 /home1/resilient/public_html/wp-content/plugins/elementor/core/files/css/global-css.php(66): Elementor\Core\Files\CSS\Global_CSS->render_schem in /home1/resilient/public_html/wp-content/plugins/modal-for-elementor/widgets/popup.php on line 185

I would be open to completely starting over the website, I selected a new theme and received the same message

### Steps to reproduce

1) go to resilientrise.com

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.3.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://resilientrise.com
	Home URL: https://resilientrise.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: ResilientRise@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.0.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.7.2
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.11.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	MC4WP: Mailchimp for WordPress
		Version: 4.9.0
		Author: ibericode

	Ocean Extra
		Version: 2.1.1
		Author: OceanWP

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Save as Default: Inactive

== Log ==
	
Log: showing 20 of 422022-01-26 23:17:01 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2022-01-26 23:17:01 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2022-01-26 23:17:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.5.4',
)]
2022-02-08 16:25:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-08 16:25:26 [info] elementor::elementor_updater Started 
2022-02-08 16:25:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-08 16:25:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-08 16:25:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2023-01-10 07:00:23 [info] elementor::elementor_updater Started 
2023-01-10 07:00:23 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-10 07:00:23 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-10 07:00:23 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-01-10 07:00:23 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-01-10 07:00:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.10.0',
)]
2023-01-10 07:00:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.10.0',
)]
2023-01-16 05:28:59 [info] elementor::elementor_updater Started 
2023-01-16 05:28:59 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-16 05:28:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-16 05:28:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.0-dev3',
)]
2023-01-16 05:28:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.0-dev3',
)]

JS: showing 1 of 1JS: 2022-01-27 04:33:02 [error X 1][http://resilientrise.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	PopBox For Elementor: Compatibility not specified

**Comment by m1ga** [comment]
The error is in `modal-for-elementor/widgets/popup.php` which is https://wordpress.org/plugins/modal-for-elementor/#developers that hasn't been updated for 5 years. So I guess if you remove that it will start working again.

Also: 3.11.0-dev3? I wouldn't use that for a live version.

**Comment by nicholaszein** [comment]
Hello @ResilientRise,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

It seems that the **Modal for Elementor** add-on you're using is incompatible with the latest version of Elementor as @m1ga correctly pointed out above. Which means this is not an Elementor bug.

The best solution is for you to contact the add-on support and ask them to fix the incompatibility. But as @m1ga also correctly pointed out (thanks @m1ga 🙏), it seems the add-on you're using has been abandoned. We strongly recommend you to uninstall the add-on to avoid security risks and incompatibilities.

Make sure you're also not using the Elementor Developer Edition plugin on a production website, as it is not meant to be used that way. Only for testing purposes on a staging environment.

For now, that's all we can help you with. If you have any other issues that are happening only with Elementor and/or Elementor Pro, please feel free to submit a new [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind Regards
