### ISSUE TITLE
✅ 🐞 Bug Report: Lazy Load Background Images Not Loading On Scroll

### ISSUE THREAD

**Issue by elgoots** [elementor/elementor#21045]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Lazy Load Background Images Not Loading On Scroll. 
Scrolling down to point has stopped working since latest update of Elementor. Was running ok prior.

![image](https://user-images.githubusercontent.com/54693378/212775460-dd401924-3a9a-4ff2-9e82-6e65776832d9.png)

### Steps to reproduce

Website to check against that has the issue, ( scroll down to services on homepage ) : https://www.pulsetestandtag.com.au/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.40
	PHP Version: 8.1.13
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.pulsetestandtag.com.au
	Home URL: https://www.pulsetestandtag.com.au
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 0
	Admin Email: stuart@theonlinedirector.com.au
	Debug Mode: Inactive

== Theme ==
	Name: Pulse Test And Tag
	Version: 1.0
	Author: The Online Director
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.0.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	301 Redirects
		Version: 2.72
		Author: WebFactory Ltd

	Astra Pro
		Version: 4.0.0
		Author: Brainstorm Force

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Elementor
		Version: 3.11.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.1
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.9
		Author: Gravity Forms

	Gravity Forms Stripe Add-On
		Version: 4.2
		Author: Gravity Forms

	Gravity Forms Zapier Add-On
		Version: 4.2
		Author: Gravity Forms

	Gravity Forms Zero Spam
		Version: 1.2.3
		Author: GravityKit

	Import / Export Customizer Settings
		Version: 1.0.7
		Author: Brainstorm Force

	LiteSpeed Cache
		Version: 5.3.2
		Author: LiteSpeed Technologies

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	PixelYourSite PRO
		Version: 9.4.1
		Author: PixelYourSite

	Post SMTP
		Version: 2.3.2
		Author: Post SMTP

	PowerPack Pro for Elementor
		Version: 2.9.6
		Author: Team IdeaBox - PowerPack Elements

	Template Library and Redux Framework
		Version: 4.3.21
		Author: Extendify

	Ultimate Addons for Elementor
		Version: 1.36.14
		Author: Brainstorm Force

	WPBakery Page Builder
		Version: 6.10.0
		Author: Michael M - WPBakery.com

	WP Sitemap Page
		Version: 1.9.2
		Author: Tony Archambeau

	Yoast SEO
		Version: 19.14
		Author: Team Yoast

== Must-Use Plugins ==
	turnoffcss.php
		Version: 
		Author: 

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 332022-11-09 01:34:20 [info] elementor::elementor_updater Started 
2022-11-09 01:34:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-09 01:34:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-09 01:34:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.10.0-dev1',
)]
2022-11-10 01:07:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-10 01:07:11 [info] elementor-pro::elementor_pro_updater Started 
2022-11-10 01:07:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-10 01:07:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-10 01:07:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2023-01-08 22:56:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev3',
)]
2023-01-08 22:56:15 [info] elementor::elementor_updater Started 
2023-01-08 22:56:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-08 22:56:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-08 22:56:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev3',
)]
2023-01-16 21:15:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-dev1',
  'to' => '3.10.1',
)]
2023-01-16 21:15:34 [info] elementor-pro::elementor_pro_updater Started 
2023-01-16 21:15:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-16 21:15:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-16 21:15:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-dev1',
  'to' => '3.10.1',
)]
2023-01-16 21:15:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-dev1',
  'to' => '3.10.1',
)]

PHP: showing 7 of 7PHP: 2022-11-02 23:18:15 [notice X 1927][/home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/home/pulsetest/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-11-08 22:38:10 [notice X 78][/home/pulsetest/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-09 01:34:48 [notice X 125][/home/pulsetest/public_html/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Optional parameter $size declared before required parameter $url is implicitly treated as a required parameter [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-09 01:40:15 [notice X 101][/home/pulsetest/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/pulsetest/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/pulsetest/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/pulsetest/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/pulsetest/public_html/wp-content/plugins/powerpack-elements/modules/presets-style/module.php(89): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-11-09 01:47:30 [notice X 191][/home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-10 01:31:20 [notice X 6533][/home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/pulsetest/public_html/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/pulsetest/public_html/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/pulsetest/public_html/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-11-18 03:33:05 [warning X 1][/home/pulsetest/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-11-10 00:42:05 [error X 1][https://www.pulsetestandtag.com.au/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.10.0-dev1:2:52931] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 
JS: 2022-11-11 03:37:36 [error X 1][https://www.pulsetestandtag.com.au/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51824] Cannot read properties of undefined (reading \'replace\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Make Column Clickable Elementor: Compatibility not specified
	PowerPack Pro for Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @elgoots!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.10.2**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
