### ISSUE TITLE
🔗 🚀 Feature Request: woocommerce quick view = (Compatibility of loop builder with popup) (Duplicate of #7106)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21046]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor developer!

Currently, **loop builder does not support popup**. This will be a super useful feature.

Let's say I have a website for buying and selling real estate or cars (in Custom post type). In this website, I show house or car using loop builder. I want to add a button in the loop item so that if the user clicks on it, a popup will be displayed so that the user can see the details immediately. Currently, such a thing is not possible😔

Elementor team, we now have popup and loop builder. So far, much of the path has been covered. Just please make the two compatible. @arielk @avivu @KingYes **(Sorry for tagging, I just want you to read this offer/request)**

### Describe the solution you'd like

Compatibility of loop builder with popup **(Ability to create quick view for post, products and custom post type)**

cheers🥂

**Comment by erizonmacani** [comment]
Something similar still outstanding since 4 years ago.

https://github.com/elementor/elementor/issues/7106

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔗 🚀 There is already a similar request submitted by someone here #7106

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

Kind regards
