### ISSUE TITLE
⛔ 🐞 Bug Report: image

### ISSUE THREAD

**Issue by dbritanija** [elementor/elementor#21044]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Images are not displaying

### Steps to reproduce

1)http://damnfinecopy.co.uk/
2)http://damnfinecopy.co.uk/about/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.35
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://damnfinecopy.co.uk
	Home URL: http://damnfinecopy.co.uk
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hello@monamex.net
	Debug Mode: Inactive

== Theme ==
	Name: Itara
	Version: 1.0.0
	Author: wpkoithemes
	Child Theme: Yes
	Parent Theme Name: Lalita
	Parent Theme Version: 1.4.0
	Parent Theme Author: wpkoithemes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76

== Active Plugins ==
	Contact Form 7
		Version: 5.7.2
		Author: Takayuki Miyoshi

	Cookie Information | Free WP GDPR Consent Plugin
		Version: 2.0.21
		Author: Cookie Information

	Elementor
		Version: 3.11.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Fonts Plugin | Google Fonts Typography
		Version: 3.3.3
		Author: Fonts Plugin

	Gutenberg
		Version: 14.9.1
		Author: Gutenberg Team

	LuckyWP Cookie Notice (GDPR)
		Version: 1.2
		Author: LuckyWP

	MC4WP: Mailchimp for WordPress
		Version: 4.9.0
		Author: ibericode

	Polylang
		Version: 3.3.1
		Author: WP SYNTEX

	Portfolio Gallery
		Version: 1.1.7
		Author: portfoliohub

	ShareThis Share Buttons
		Version: 2.1.7
		Author: ShareThis

	Simple Social Buttons
		Version: 4.0.2
		Author: WPBrigade

	Simple Social Page Widget & Shortcode
		Version: 1.7.0
		Author: Dylan Ryan

	Slider Revolution
		Version: 6.1.1
		Author: ThemePunch

	Smash Balloon Instagram Feed
		Version: 6.1
		Author: Smash Balloon

	Themerex Banner
		Version: 1.0
		Author: Themerex

	UpdraftPlus - Backup/Restore
		Version: 1.22.24
		Author: UpdraftPlus.Com, DavidAnderson

	W3 Total Cache
		Version: 2.2.11
		Author: BoldGrid

	WPKoi Templates for Elementor
		Version: 2.5.0
		Author: WPKoi

	Yoast SEO
		Version: 19.14
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default

== Log ==
	
JS: showing 7 of 7JS: 2022-02-01 17:46:06 [error X 1][http://monamex.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.4:2:453832] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-16 17:12:26 [error X 1][http://monamex.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4066\") has already been destroyed and cannot be used. 
JS: 2022-02-16 17:15:29 [error X 1][http://monamex.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view20018\") has already been destroyed and cannot be used. 
JS: 2022-02-16 17:15:29 [error X 1][http://monamex.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view20099\") has already been destroyed and cannot be used. 
JS: 2022-02-16 17:15:29 [error X 1][http://monamex.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view20164\") has already been destroyed and cannot be used. 
JS: 2022-02-21 20:57:29 [error X 1][http://monamex.net/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view14365\") has already been destroyed and cannot be used. 
JS: 2023-01-16 19:40:13 [error X 1][http://damnfinecopy.co.uk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 

PHP: showing 2 of 2PHP: 2022-02-10 02:05:32 [warning X 1][/home/anmija/domains/monamex.net/public_html/wp-content/plugins/elementor-beta/modules/developer-edition/core-version-control.php::183] uasort() expects parameter 1 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-16 20:11:59 [notice X 1][/home/anmija/domains/damnfinecopy.co.uk/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 7 of 72023-01-13 19:12:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.11.0-dev3',
)]
2023-01-13 19:12:46 [info] elementor::elementor_updater Started 
2023-01-13 19:12:46 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-13 19:12:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-13 19:12:46 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-01-13 19:12:46 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-01-13 19:12:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.11.0-dev3',
)]

== Elementor - Compatibility Tag ==
	
	WPKoi Templates for Elementor: Compatibility not specified

**Comment by m1ga** [comment]
you have a space in the beginning of the image url

**Comment by nicholaszein** [comment]
Hello @dbritanija,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

This is likely caused by something you did to your images since they are missing.

We advise you to ask for help from the great folks at the [Global Elementor Community on Facebook.](https://facebook.com/groups/Elementors/)

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
