### ISSUE TITLE
⛔ 🐞 Bug Report: Enabling Inline Font Icons experiements causes FontAwesome Icons missing.

### ISSUE THREAD

**Issue by Kishorchandth** [elementor/elementor#21058]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

When I enabled Inline Font Icons Experiements **none** of the fontawesome (FA) icons are visible in the Editor.

**Editor**-
![Screenshot_3](https://user-images.githubusercontent.com/39625343/213140226-f6986be2-af24-4f7e-8b68-5765973159fb.jpg)

**Dev tools**-
![Dev Tools](https://user-images.githubusercontent.com/39625343/213140281-9f4f1ea8-8fa8-4343-a62b-67381a2c0cd1.jpg)

But when I disable the experiments, all the FA are visible 

**Editor**
![Visible](https://user-images.githubusercontent.com/39625343/213141219-c55c68b9-2523-4d8b-b8f9-3f1f0f0eba4e.jpg)

**Dev Tools**
![Dev Tools No issues](https://user-images.githubusercontent.com/39625343/213141295-b3b3e96b-6553-4917-aaf9-bbdb60db4b2a.jpg)

Thank you.

### Steps to reproduce

Already in details in my descriptions

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://beta.local
	Home URL: https://beta.local
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: .....
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Asset CleanUp: Page Speed Booster
		Version: 1.3.8.9
		Author: Gabe Livan

	Code Snippets
		Version: 3.2.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Lazy Load Control For Elementor
		Version: 0.0.2
		Author: Jose Mortellaro

	Performance Lab
		Version: 1.9.0
		Author: WordPress Performance Team

	Unlimited Elements for Elementor
		Version: 1.5.47
		Author: Unlimited Elements

== Must-Use Plugins ==
	WP Shifty Loader
		Version: 
		Author: 

== Elements Usage ==
	
	archive : 1
		button : 1
		heading : 3
		posts : 1
		text-editor : 1
	container : 1
		button : 1
		container : 1
		nav-menu : 1
		ucaddon_ue_site_logo : 1
	footer : 1
		container : 1
		heading : 4
		icon : 1
		social-icons : 1
	header : 2
		container : 1
		html : 1
		image : 1
		nav-menu : 1
		progress-tracker : 1
	page : 1
		button : 2
		heading : 23
		spacer : 5
	popup : 1
		form : 1
		heading : 1
		text-editor : 1
	section : 2
		button : 2
		nav-menu : 2
		ucaddon_ue_site_logo : 2
	wp-post : 1
		container : 1
		text-editor : 1
	wp-page : 8
		button : 6
		call-to-action : 12
		container : 3
		divider : 13
		form : 1
		google_maps : 2
		heading : 46
		image : 1
		image-carousel : 1
		loop-grid : 1
		media-carousel : 1
		posts : 1
		spacer : 8
		testimonial-carousel : 1
		text-editor : 32
		ucaddon_lite_vimeo_embedded : 1
	single-post : 3
		call-to-action : 2
		container : 15
		heading : 4
		html : 4
		image : 1
		loop-grid : 3
		post-comments : 1
		post-info : 4
		table-of-contents : 3
		text-editor : 1
		theme-post-content : 3
		theme-post-excerpt : 3
		theme-post-featured-image : 1
		theme-post-title : 3
		ucaddon_disqus_comment : 2
		ucaddon_featured_image : 2
		ucaddon_post_List : 2
	loop-item : 1
		button : 1
		container : 1
		post-info : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
		ucaddon_comment : 1
	error-404 : 1
		button : 1
		heading : 2

== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	font_display: optional
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Save as Default: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Active

== Log ==
	
JS: showing 5 of 5JS: 2022-12-23 05:27:19 [error X 2][https://beta.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1000") has already been destroyed and cannot be used. 
JS: 2022-12-25 07:58:22 [error X 1][https://beta.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view995") has already been destroyed and cannot be used. 
JS: 2022-12-25 08:00:48 [error X 1][https://beta.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view994") has already been destroyed and cannot be used. 
JS: 2023-01-09 08:24:57 [error X 4][https://beta.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:82426] Cannot read properties of undefined (reading 'icons') 
JS: 2023-01-18 07:28:23 [error X 2][https://beta.local/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 

PHP: showing 7 of 7PHP: 2022-12-31 06:22:19 [warning X 1][C:\laragon\www\beta\wp-content\plugins\elementor\core\files\file-types\svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://beta.local/wp-content/uploads/2022/11/Vector-2.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-02 06:43:28 [notice X 1][C:\laragon\www\beta\wp-content\plugins\elementor\core\page-assets\data-managers\font-icon-svg\font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-10 06:13:24 [notice X 7][C:\laragon\www\beta\wp-content\plugins\elementor\core\common\modules\ajax\module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-10 06:13:25 [notice X 6][C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
#3: C:\laragon\www\beta\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: C:\laragon\www\beta\wp-content\plugins\elementor\data\base\endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-01-14 06:52:22 [notice X 7][C:\laragon\www\beta\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-14 07:37:51 [warning X 1][C:\laragon\www\beta\wp-content\plugins\elementor\core\files\file-types\svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://beta.local/wp-content/uploads/2023/01/arrow.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-14 10:10:32 [notice X 5][C:\laragon\www\beta\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 302023-01-10 06:12:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-beta3',
  'to' => '3.10.0',
)]
2023-01-10 06:12:04 [info] elementor::elementor_updater Started 
2023-01-10 06:12:04 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-10 06:12:06 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-10 06:12:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-beta3',
  'to' => '3.10.0',
)]
2023-01-10 06:12:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-beta3',
  'to' => '3.10.1',
)]
2023-01-10 06:12:48 [info] elementor-pro::elementor_pro_updater Started 
2023-01-10 06:12:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-10 06:12:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-10 06:12:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-beta3',
  'to' => '3.10.1',
)]
2023-01-18 06:28:49 [info] elementor::elementor_updater Started 
2023-01-18 06:28:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-18 06:28:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-18 06:28:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-18 06:28:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-18 06:29:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-18 06:29:45 [info] elementor-pro::elementor_pro_updater Started 
2023-01-18 06:29:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-18 06:29:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-18 06:29:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Lazy Load Control For Elementor: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by witty-code** [comment]
I looked to see if this issue has already been reported and found this
I also have the same problem - after running the experiment, the icons are not available in the editor

**Comment by nicholaszein** [comment]
Hello there,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tried to reproduce your issue using versions 3.10, 3.11, and 3.12 and it worked without any problem.
- Your issue might be related to either a performance optimization tweak used on your site or a server-side cache.
- It could also be related to server configuration, security plugins, mixed-content, or CORS policies.

### ✅ What you can do to solve your issue:
- Disable 3rd party add-ons and performance optimizations.
- Clear the cache.
- Check the console for errors with mixed-content.
- Check your WAF.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
