### ISSUE TITLE
⛔ 🐞 Bug Report: Logged PHP Notice with Undefined index: the7_auto_width_table conditions.php on line 87

### ISSUE THREAD

**Issue by zbyyna** [elementor/elementor#21053]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I please you check problem with logging this PHP NOTICE:

[11-Jan-2023 14:51:52 UTC] PHP Notice: Undefined index: the7_auto_width_mobile in /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php on line 87
[11-Jan-2023 14:51:52 UTC] PHP Notice: Undefined index: the7_auto_width_tablet in /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php on line 87

The notice still repeated with any GET request. I know, that the problem has not direct affect to my site, but the notice still fullfill debug.log every day, and this debug.log is very huge after 1 week (about 400 MB). 

My webhosting provider dont allowed me to ini set for ignoring E_NOTICE severity, and for my opinion it is not good practice to hide of any severity.

It seems to me as compatibility issue with The7 theme and Elementor.

Please, dont advise me with ignoring E_NOTICE severity, because I need the NOTICE severity for logging other compatibilities plugin issues.

Thank you.
Zbynek

Some screenshots:

![chktp-notice](https://user-images.githubusercontent.com/22218017/212964551-a8d51c44-a9b1-4b7f-b77a-9129b3b3ce78.png)

[php_error.log](https://github.com/elementor/elementor/files/10437600/php_error.log)

### Steps to reproduce

1) I resolved my page https://choketopus.com/ at 
2) In debug log are:

[error-log-chtktps-one-get.txt](https://github.com/elementor/elementor/files/10437611/error-log-chtktps-one-get.txt)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.3.37
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://choketopus.com
	Home URL: https://choketopus.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Admin Email: zbynek.simek@outlook.com
	Debug Mode: Active

== Theme ==
	Name: the7dtchild
	Version: 1.0.0
	Author: Dream-Theme
	Child Theme: Yes
	Parent Theme Name: The7
	Parent Theme Version: 11.3.0
	Parent Theme Author: Dream-Theme

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Order Export For WooCommerce
		Version: 3.3.3
		Author: AlgolPlus

	Booster for WooCommerce
		Version: 6.0.1
		Author: Pluggabl LLC

	Choketopus Email Flow
		Version: 2.1.0
		Author: Webtories s.r.o

	Duplicator Pro
		Version: 4.5.9.1
		Author: Snap Creek

	Elementor
		Version: 3.10.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.1
		Author: Elementor.com

	GTM4WP
		Version: 1.16.2
		Author: Thomas Geiger

	PDF Invoices & Packing Slips for WooCommerce
		Version: 3.2.6
		Author: WP Overnight

	Product Filter for WooCommerce
		Version: 7.2.5
		Author: 7VX LLC, USA CA

	Product Size Chart for Woocommerce
		Version: 1.1.3
		Author: Ciobanu George

	The7 Elements
		Version: 2.7.1
		Author: Dream-Theme

	WooCommerce
		Version: 7.2.3
		Author: Automattic

	WooCommerce Advanced Bulk Edit
		Version: 5.0
		Author: George Iron

	Woo Fio
		Version: 1.3
		Author: Woo

	Woo GoPay Inline
		Version: 1.6.1
		Author: Woo

	Woo Zásilkovna
		Version: 2.7.5
		Author: WM

	Wordfence Security
		Version: 7.8.2
		Author: Wordfence

	WPML Multilingual CMS
		Version: 4.5.14
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.3
		Author: OnTheGoSystems

	Yoast SEO
		Version: 19.14
		Author: Team Yoast

== Použitím Elements ==
	
	footer : 4
		divider : 1
		form : 1
		heading : 3
		icon-list : 1
		image : 1
		spacer : 1
		the7_button_widget : 9
	header : 2
		divider : 1
		html : 1
		icon : 2
		image : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
		spacer : 2
		text-editor : 1
		woocommerce-menu-cart : 1
	page : 1
		heading : 1
		html : 2
		text-editor : 3
	product : 1
		divider : 1
		heading : 1
		image : 1
		the7-woocommerce-product-images : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
	wp-post : 9
		heading : 5
		html : 8
		image : 2
		spacer : 5
		text-editor : 23
		video : 2
	wp-page : 20
		button : 64
		divider : 94
		form : 2
		heading : 132
		hotspot : 4
		html : 1
		icon-box : 8
		image : 113
		slides : 1
		social-icons : 1
		spacer : 44
		text-editor : 42
		video : 4
	search-results : 1
		archive-posts : 1
		divider : 1
		theme-archive-title : 1
	product-archive : 5
		wc-archive-products : 1

== Nastavení ==
	
	cpt_support: post, page
	allow_tracking: yes
	css_print_method: internal
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Experimenty Elementoru ==
	Optimalizováno DOM Output: Ve výchozím stavu neaktivní
	Vylepšené načítání assetů: Ve výchozím stavu neaktivní
	Vylepšené načítání CSS: Ve výchozím stavu neaktivní
	Inline Font Icons: Ve výchozím stavu neaktivní
	Vylepšení přístupnosti: Ve výchozím stavu neaktivní
	Dodatečné vlastní body zalomení: Aktivní
	Skrýt ve vyhledávání nativní widgety WordPress : Ve výchozím stavu aktivní
	admin_menu_rearrangement: Ve výchozím stavu neaktivní
	Flexbox kontejner: Ve výchozím stavu neaktivní
	Default to New Theme Builder: Ve výchozím stavu aktivní
	Vstupní stránky (Landing page): Ve výchozím stavu aktivní
	Vložené prvky: Ve výchozím stavu neaktivní
	Líné načítání obrázků na pozadí: Ve výchozím stavu neaktivní
	Uložit jako výchozí: Ve výchozím stavu aktivní
	Page Transitions: Ve výchozím stavu aktivní
	Notes: Ve výchozím stavu aktivní
	Loop: Ve výchozím stavu neaktivní
	Form Submissions: Ve výchozím stavu aktivní
	Scroll Snap: Ve výchozím stavu aktivní

== Log ==
	
Log: showing 20 of 332022-12-12 21:28:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.2',
)]
2022-12-19 07:56:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.1',
)]
2022-12-19 07:56:28 [info] elementor-pro::elementor_pro_updater Started 
2022-12-19 07:56:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-19 07:56:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-19 07:56:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.1',
)]
2023-01-11 12:39:46 [info] elementor::elementor_updater Started 
2023-01-11 12:39:46 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-11 12:39:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-11 12:39:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.2',
)]
2023-01-11 15:33:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-11 15:33:07 [info] elementor::elementor_updater Started 
2023-01-11 15:33:07 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-11 15:33:08 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-11 15:33:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-11 15:42:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.1',
)]
2023-01-11 15:42:09 [info] elementor-pro::elementor_pro_updater Started 
2023-01-11 15:42:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-11 15:42:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-11 15:42:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.1',
)]

PHP: showing 9 of 9PHP: 2022-12-13 10:53:50 [notice X 61][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: the7_auto_width_tablet [array (
  'trace' => '
#0: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1383): Elementor\Conditions :: check()
#2: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1169): Elementor\Controls_Stack -> is_control_visible()
#3: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1210): Elementor\Controls_Stack -> get_active_settings()
#4: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/element-base.php(663): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-12-13 10:53:50 [notice X 61][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: the7_auto_width_mobile [array (
  'trace' => '
#0: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1383): Elementor\Conditions :: check()
#2: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1169): Elementor\Controls_Stack -> is_control_visible()
#3: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1210): Elementor\Controls_Stack -> get_active_settings()
#4: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/element-base.php(663): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2022-12-13 10:56:22 [notice X 58582][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: the7_auto_width_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-19 07:56:20 [error X 1][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor-pro/modules/posts/data/controller.php::12] Uncaught Error: Class 'ElementorPro\Data\Base\Controller' not found in /www/doc/www.choketopus.com/www/wp-content/plugins/elementor-pro/modules/posts/data/controller.php:12
Stack trace:
#0 /www/doc/www.choketopus.com/www/wp-content/plugins/elementor-pro/plugin.php(153): include()
#1 [internal function]: ElementorPro\Plugin->autoload('ElementorPro\\Mo...')
#2 /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/data/manager.php(88): spl_autoload_call('ElementorPro\\Mo...')
#3 /www/doc/www.choketopus.com/www/wp-content/plugins/elementor-pro/modules/posts/module.php(99): Elementor\Data\Manager->register_controller('ElementorPro\\Mo...')
#4 /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Posts\Module->__construct()
#5 /www/doc/www.choketopus.com/www/wp-content/plugins/elementor-pro/core/modules-manager.php(86): Elementor\Core\Base\Module::instance()
#6 /www/doc/www.choketopus.com/www/wp-content/plugins/elementor-pro/plugin.php(357): ElementorPro\ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-11 15:33:08 [notice X 2][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/core/base/document.php::1709] Trying to get property 'post_status' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-12 10:07:11 [error X 2][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::266] Allowed memory size of 268435456 bytes exhausted (tried to allocate 872448 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-12 10:12:58 [notice X 1][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-12 10:16:15 [notice X 116][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: the7_auto_width_tablet [array (
  'trace' => '
#0: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1385): Elementor\Conditions :: check()
#2: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1171): Elementor\Controls_Stack -> is_control_visible()
#3: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1212): Elementor\Controls_Stack -> get_active_settings()
#4: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/element-base.php(669): Elementor\Controls_Stack -> get_settings_for_display()
',
)]
PHP: 2023-01-12 10:16:15 [notice X 116][/www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: the7_auto_width_mobile [array (
  'trace' => '
#0: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1385): Elementor\Conditions :: check()
#2: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1171): Elementor\Controls_Stack -> is_control_visible()
#3: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1212): Elementor\Controls_Stack -> get_active_settings()
#4: /www/doc/www.choketopus.com/www/wp-content/plugins/elementor/includes/base/element-base.php(669): Elementor\Controls_Stack -> get_settings_for_display()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Nekompatibilní

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @zbyyna,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

It seems that the **The7 Elements** add-on you're using is incompatible with the latest version of Elementor. Which means this is not an Elementor bug.

The best solution is for you to contact the add-on support and ask them to fix the incompatibility.

For now, that's all we can help you with. If you have any other issues that are happening only with Elementor and/or Elementor Pro, please feel free to submit a new [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind Regards
