### ISSUE TITLE
✅ 🔣 🐞 Bug Report: The Justify option in nested tabs displays the wrong direction (RTL)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21086]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

If the website is RTL, the [Justify option](https://prnt.sc/OBeB12s59ej9) in the new tabs widget will not display the correct directions. For example, if we select start, it will act as end.

### Steps to reproduce

1- Make sure the website is RTL.
2- Add the nested tabs widget.
3- In the Justify option, try **start** and **end**. It works against the direction of the icon.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-21-01-2023.txt](https://github.com/elementor/elementor/files/10470348/system-info-localhost-21-01-2023.txt)

**Comment by nicholaszein** [comment]
Hey @79ho3ein!

### This issue was resolved in Elementor v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
