### ISSUE TITLE
⛔ ❓ Question about Coding widgets in Elementor - Question from developers

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#21085]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team. I hope you see this issue because I have an important question about coding Elementor widgets...

As you know, the biggest weakness of Elementor is that it adds a lot of extra code in the Html structure. I can say the only weakness!
We now have the container with no issues and the html structure in it is clean and optimized.

But an important question. **Why does Elementor produce additional codes?**

Add a button widget to the editor. Each button widget has 5 divs! While it could have been written much cleaner. Like the code below :

```
<dic class="e-con">
   <div class="e-con-inner">
      <a id="elementor-button-wrapper" href="#">elementor button</a>
   </div>
</div>
```

Image widget and other widgets in the same way...

This is why websites built with Elementor always have a large amount of DOM. Meanwhile, the competitors are very sensitive about this issue and are doing great. **So I had some questions for the Elementor developers, I would be very happy if you answer them🙏**

1- To solve the problem of extra code, do you have a program to rewrite old widgets (buttons, images, etc.)?
2- If you overwrite old widgets, won't existing sites be broken?
3- If the answer to the previous question is yes, wouldn't it be better to add a new widget for all the old widgets so that we can replace the old widget with the new widget if desired? Just like the new tabs widget, when you activate it, the old tabs widget is removed and the new widget is replaced with it.
4- What do you think is the best solution? Until this issue is resolved, Elementor will always remain with this weakness. Please don't let new page builders use this elementor weakness for their ads. @arielk , @KingYes 

thanks

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by maximedesro** [comment]
Yes indeed this is the hercules heel of Elementor. Their (in)famous two wrapper system, for every single element. The DIVception.

The solution you propose is interesting, however it's not realistic. The entire Elementor UI is designed to work with this two wrapper system.

For example the padding and margin, the background, border, motion effects, transform... all relies on this two wrapper system. They would not necessarily have to, but they do and changing this is nearly impossible with 10M websites running Elementor already.

![image](https://user-images.githubusercontent.com/39132584/213880229-098915e2-7f4a-47bb-b95f-a2a3b01b00f0.png)

It's the tradeoff of Elementor. Easy to use, with many decisions pre made for the user. But the markup quality is poor.

I've given this a lot of thought and the ONLY solution I see is for Elementor to fork themselve, and come out with a completely new builder, based on the old one, but with clean code, no jQuery, on demand CSS and JS.

Elementor's UI and UX is still the greatest out there... if they could just clean up the code and performance, they could be relevant for decades to come. Without this though, the competition will sooner or later get the better of them.

**Comment by Joliamendi** [comment]
Hi @maximedesro, thanks for the reply.

If I didn't misunderstand you, you say that the extra divs are created because we can use motion effects, transform, etc. But there are two questions here.

1- When we use a widget and do not apply any motion effect or transform on it, why should it already have its divs? It just increases the DOM size.

2- If you check the bricks code in the frontend, it adds only one span for the button. Without any additional code. Even if we use transform for the button, no div tag will be added for it. So how does elementor add a div to apply any attribute like transform? Even if we don't want to use transform or motion effect!

Am I wrong? Maybe I don't know enough about coding...

**Comment by maximedesro** [comment]
Hey @Joliamendi 

_If I didn't misunderstand you, you say that the extra divs are created because we can use motion effects, transform, etc._

Not quite what I was trying to get across. Rather, my point is that all of these settings from the Elementor UI, including margin and paddings, are dependant on that two wrapper system. **They would not have to be. But they are**, and changing this now is impossible as it would break 100% of Elementor websites.

I agree with what you are saying, these 2 divs are useless in most cases. No question about it. This does not mean they can be removed though... the whole system presumes their being there.

That's why I mentioned a fork being the only way to get rid of them.

**Comment by nicholaszein** [comment]
Hi @Joliamendi,

thanks for submitting your question. 🙏 

As @maximedesro kindly pointed out, these "extra" tags are important for many reasons. They allow you to apply spacing, motion effects (not only transforms and transitions, but the actual motion effects available), and many other features. These were not added without deep consideration, and for the time being, they are not likely to be changed, both for compatibility with many of Elementor's features, but also for backward compatibility.

It's important to say as well: Elementor is not Bricks. This might be harsh to hear, but the only thing both builders have in common is their purpose: to build pages visually. Under the hood, they are very different in many aspects, including how things are structured. It's also worth mentioning that Bricks do not have as advanced motion effects as Elementor does. At least not built as Elementor was. Comparing both builders in this way simply does not apply in this case.

So to answer your questions:

1. Not at the moment. We are always investigating and investing in ways to improve performance. DOM size, although pointed out by metrics, is not as important as people make it seem. Yes, having a cleaner code can be beneficial, but this won't affect performance as people say it will.
2. Yes, but also Not exactly. If we would change element structures, we would do it in a conscious, non-destructible way to ensure, you guessed, backward compatibility. We are doing this with tabs for example. Old tabs will remain as they are when you activate the experiment. They will be "frozen in time". You will be able to keep using them as they are and change their style and content. But when you add a new one, it will be a Nested Tab.
3. I guess I answered this one above. If we do replace old widgets, it will be done in a responsible way, allowing backward compatibility as much as we can.
4. Restructuring software that is used on millions of websites is not a simple task. It takes time and responsibility. We are obviously investing in making the Elementor experience better, and we will always do that. We also invite competition and, despite what some people may say, we are not at all intimidated by it. We think competition is good, and we like the work of our competitors. We will continue investing in improving our platform according to our user's needs. But we are not the competition. Our software (Elementor's and the competition's) is different and that's not a bad thing. There is room for all.

I hope this clears your doubts.

### 🙏 That being said, I have an honest request for you. 

Please do not tag the Elementor staff when submitting an issue. It is fine if you are answering someone to tag them in a comment. But tagging them in your issue does not help, and can actually make answering it more difficult and time-consuming, which means other issues (including ones submitted by you), may take more time to be answered. We are all following GitHub closely, even if we take some time to answer. Tagging the staff with no reason will only cause answers to take longer to be made. Thanks
