### ISSUE TITLE
⛔ Navigation button in mobile 

### ISSUE THREAD

**Issue by Vaydor** [elementor/elementor#21084]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

When using the navigation button on my mobile it is not very visible.

### Describe the solution you'd like

Make the button more visible

### Describe alternatives you've considered

A more visible button on my mobile

### Additional context

It is too difficult to see

**Comment by Vaydor** [comment]
When potential customers are searching for the button to search the pages on a mobile phone the navigation button is too small

**Comment by nicholaszein** [comment]
Hello @Vaydor,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

You can control the size of the Nav Menu Toggle button yourself. Please refer to Elementor Academy to learn more about how to style your Nav Menu widget.

https://elementor.com/help/nav-menu-widget-pro/

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
