### ISSUE TITLE
❌ 🚀 Feature Request: Could you add integration with MailWizz?

### ISSUE THREAD

**Issue by LarryKHite** [elementor/elementor#21095]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

MailWizz has a huge number of users but has not been able to solve the integration problem is a great pity！

### Describe the solution you'd like

MailWizz has a huge number of users but has not been able to solve the integration problem is a great pity！

**Comment by nicholaszein** [comment]
Hello @LarryKHite,

Thanks for your feedback! 🙏 

### ❌ 🚀  While reviewing your request we noticed it was missing the following key information:

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and explain in detail what your request is going to solve. Describe the solution and give context. Be thorough.

Feel free to submit a new request following these guidelines. 😉 

Take care,

Nick
