### ISSUE TITLE
✅ 🚀 Feature Request: Add REM units to site settings - [ED-9743]

### ISSUE THREAD

**Issue by 23Chromosomes** [elementor/elementor#21116]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In site settings in Elementor on form fields and button. There is px, em, % but no REM.
Also the new "Custom" option is also not there.

### Describe the solution you'd like

Add REM and Custom unit options to site settings where it's missing.

### Describe alternatives you've considered

No comment

### Additional context

No comment

**Comment by rami-elementor** [comment]
@rodolphebertozzo Do you want me to assign this task to you?

**Comment by rodolphebertozzo** [comment]
Yes, you can @rami-elementor 😉, I'll take care of it in the next few hours

**Comment by rodolphebertozzo** [comment]
Hi, you can see : https://github.com/elementor/elementor/pull/21211
