### ISSUE TITLE
✅ 🚀 Feature Request: Offset loop carousel

### ISSUE THREAD

**Issue by mikekellner** [elementor/elementor#21114]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

With modern design, it would be good to have the upcoming loop carousel have an offset feature, so the next card is only partly visible and it goes off the edge of the page. 

### Describe the solution you'd like

It would be like the first option in this video - https://www.youtube.com/watch?v=QteosgBNe9Q - with new Elementor loop builder, this should be achievable without the need for addons. 

### Describe alternatives you've considered

Custom CSS - although, id prefer to design without code.

**Comment by Michaelgimii** [comment]
+10000

Elementor team, please consider this option. You have added the biggest and most difficult features, adding this feature will definitely not be difficult for you.
As a small idea, the jet woobuilder plugin already offers this feature. It is truly unique @avivu🙏

![overflow](https://user-images.githubusercontent.com/88034902/214145049-49baf0de-64f1-4147-9dd8-d52063e1fe02.png)

**Comment by Emsung** [comment]
I see some commits adding an offset to the nested and loop carousel widget. How would i enable/access these settings?

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
