### ISSUE TITLE
🚀 Feature Request: Ability to customize the e-n-tabs-heading in nested tebs

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21124]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

In the nested tabs widget, there is no option to customize the background of tab items. Rather, there are only customization options for tab items. So we can't create something like the image below : 

![s](https://user-images.githubusercontent.com/88034902/214281989-7f80d96d-fb58-474c-b4a8-5f96b6e76d29.png)

These changes in the above image are made using custom css in the nested tabs widget.

![css](https://user-images.githubusercontent.com/88034902/214282501-fe4e2dcb-6b9d-44fc-b127-29ae7bcd81ff.png)

### Describe the solution you'd like

Please add some new options to customize **e-n-tabs-heading**.

Required options : 

- width
- background color
- border
- border-radios
- box shadow
- padding

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

it seems you [opened a new Feature Request ](https://github.com/orgs/elementor/discussions/21627) for the same subject.

For this reason, I am closing this issue.

In the future, please consider avoiding creating duplicates, even if they are new Feature Requests on the new Discussions page. We will migrate all existing opened Feature Requests on issues to Discussions soon, and it just creates yet another step to identify duplicates and close them, not to mention the unnecessary extra time spent by you trying to re-post everything. 😉 

Feel free to continue the conversation there.

Thanks 🙏
