### ISSUE TITLE
✅ 🚀 Feature Request: Customize the spacing between images and captions (PR #20727) - [ED-10064]

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#21128]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Give the possibility to space the caption of an image from its photo for all widgets

### Describe the solution you'd like

https://github.com/elementor/elementor/pull/20727

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.19.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
