### ISSUE TITLE
⛔ 🚀 Feature Request: Customizable Elementor Navigator Panel

### ISSUE THREAD

**Issue by markymark57** [elementor/elementor#21137]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The navigator panel in Elementor is all the same color and while I can rename each panel or layer..it seems a bit jumbled and bland.

### Describe the solution you'd like

It would be nice if... we could customize the Elementor Navigator side panel.  Similar to layers in PS, if a user had the ability to change colors of each layer background, group, etc. and even saving templated layers would be incredible.

**Comment by nicholaszein** [comment]
Hello @markymark57,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Although Elementor has some visual similarities with Photoshop, they are different tools, for different purposes. The navigator needs to be consistent, and a great part of that consistency relies on an intuitive and organized User Interface. This means we have no plan to add the feature you're requesting for the time being. Having the option to set labels already fills the need for customization enough.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
