### ISSUE TITLE
⛔ 🚀 Feature Request: When clicking "Saved Templates", please display all templates without user having to click "All"

### ISSUE THREAD

**Issue by tuneden** [elementor/elementor#21133]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It seems redundant and unsettling to click into the Saved Templates section and not seeing all.

### Describe the solution you'd like

Show all by default

**Comment by nicholaszein** [comment]
Hello @tuneden,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap. 

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
