### ISSUE TITLE
⛔ 🐞 Bug Report: Template widget : unexpected entrance animation

### ISSUE THREAD

**Issue by DjulLau** [elementor/elementor#21149]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've created a simple template that contains a fixed background-image (to work around attachment: fixed on mobile).
This template is then integrated in each target page via the template widget. Every item is in position:fixed. 

The background is sometimes animated when entering the page in editor mode and in front/live mode. I've checked entrance animation properties at various levels. "default" or "none" make no difference. The animation seems to be a simple translation (vertical or horizontal) and does not always take place. 

You can see it live here by navigating between pages in menu: https://www.lecrieurderue.fr/realisation/

### Steps to reproduce

1. Create a template with a simple full height container and a background image
2. Add this template in a page with the "template widget"
3. Navigate from elsewhere to this page and watch the unexpected background animation taking place

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.11
	PHP Version: 7.4.33
	PHP Memory Limit: 4096M
	PHP Max Input Vars: 2000000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.lecrieurderue.fr
	Home URL: https://www.lecrieurderue.fr
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 4096M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Admin Email: jl@lecrieurderue.fr
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Coming Soon Page, Maintenance Mode, Landing Pages &amp; WordPress Website Builder by SeedProd
		Version: 6.15.7
		Author: SeedProd

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 8.12.1
		Author: MonsterInsights

	UpdraftPlus - Backup/Restore
		Version: 1.22.24
		Author: UpdraftPlus.Com, DavidAnderson

== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 8 of 8PHP: 2022-11-24 14:56:30 [notice X 12][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-25 10:58:00 [notice X 26][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-29 14:26:13 [error X 9][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-02 16:13:17 [notice X 1][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-03 14:58:05 [error X 1][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/api.php::267] Uncaught Error: Cannot use object of type WP_Error as array in /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/api.php:267
Stack trace:
#0 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/updater.php(60): ElementorPro\License\API::get_version(false)
#1 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/updater.php(130): ElementorPro\License\Updater-&gt;check_transient_data(Object(stdClass))
#2 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(310): ElementorPro\License\Updater-&gt;check_update(Object(stdClass))
#3 /home/mjqi4864/lecrieurderue.fr/wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters(Object(stdClass), Array)
#4 /home/mjqi4864/lecrieurderue.fr/wp-includes/option.php(2018): apply_filters(&#039;pre_set_site_tr...&#039;, Object(stdClass), &#039;update_plugins&#039;)
#5 /home/mjqi4864/lecrieurderue.fr/wp-includes/update.php(391): set_site_transient(&#039;update_plugins&#039;, Object(stdClass))
#6 /home/mjqi4864/lecrieurderue.fr/wp-admin/includes/class-wp- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 10:47:45 [error X 3][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 11:14:19 [notice X 9][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 12:19:29 [notice X 16][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 4 of 4JS: 2022-11-24 17:09:44 [error X 105][https://www.lecrieurderue.fr/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51816] a is undefined 
JS: 2022-11-30 12:37:22 [error X 1][https://www.lecrieurderue.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:803353] can\&#039;t convert undefined to object 
JS: 2022-11-30 16:56:04 [error X 2][https://www.lecrieurderue.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:649119] this.model.isValidChild is not a function 
JS: 2023-01-25 09:49:13 [error X 21][https://www.lecrieurderue.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:604955] this.$currentEditingArea is null 

Log: showing 20 of 302023-01-12 11:01:49 [info] elementor::elementor_updater Started 
2023-01-12 11:01:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-12 11:01:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-12 11:01:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-12 11:01:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-13 15:30:04 [info] elementor-pro::elementor_pro_updater Started 
2023-01-13 15:30:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-13 15:30:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-13 15:30:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-13 15:30:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-24 17:56:57 [info] elementor::elementor_updater Started 
2023-01-24 17:56:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-24 17:56:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-24 17:56:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-24 17:56:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-25 09:45:28 [info] elementor-pro::elementor_pro_updater Started 
2023-01-25 09:45:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-25 09:45:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-25 09:45:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-25 09:45:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by DjulLau** [comment]
I had to patch the bug quickly because the site was live. So it's not visible anymore in my link sorry.

It looked like a CSS background transition of .3s was applied so I patched it by adding the following global CSS code.
``` CSS
.elementor-template, .elementor-template * {
    transition: background;
}
```

**Comment by nicholaszein** [comment]
Hello @DjulLau,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We could not reproduce the issue you reported. For us, it works as expected.
But we are glad you found a solution to your particular case.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
