### ISSUE TITLE
🔗 🚀 Feature Request: Export form submissions (leads) programmatically using API (Duplicate of #17775)

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#21145]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

1. I am alwyas frustrated when I have to download leads MANUALLY.

2. I am alwyas frustrated when I have to REORDER csv columns MANUALLY, when in Hebrew. They do not follow the Form fields order.

### Describe the solution you'd like

1. (rest) API to allow export leads.

2. Order of columns in CSV 

### Describe alternatives you've considered

The only way is to do it MANUALLY - its pooor very poor

### Additional context

So many applications can be build on form submissions.
This market should be addressed.

**Comment by nicholaszein** [comment]
Hello, @Mulli!

### 🔗 🚀 There is already a similar request submitted by someone here #20953

Feel free to continue the conversation there! 👉

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards,

Nick
