### ISSUE TITLE
✔️ 🔗 🐞 Bug Report:  Template widget invisible if panel is hidden (fullscreen mode) (Duplicate of #20635)

### ISSUE THREAD

**Issue by DjulLau** [elementor/elementor#21150]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've created a simple template that contains a fixed background-image (to work around attachment: fixed on mobile).
This template is then integrated in each target page via the template widget. Every item is in position:fixed.

The background is visible only if the panel is opened but not in fullscreen/editor mode. It works ok in front mode. Maybe it's related to https://github.com/elementor/elementor/issues/20635 (not sure)

With the panel the background template is visible 
![image](https://user-images.githubusercontent.com/4762354/214656049-021f0fec-f46f-49f9-93eb-dc21d8417ccb.png)

Without it's not anymore
![image](https://user-images.githubusercontent.com/4762354/214656122-244f544b-dda6-4e04-9bed-42c0103df102.png)

### Steps to reproduce

1. Create a template with a simple full height container and a background image
2. Add this template in a page with the "template widget"
3. Hide the panel and watch the background disappear

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.11
	PHP Version: 7.4.33
	PHP Memory Limit: 4096M
	PHP Max Input Vars: 2000000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.lecrieurderue.fr
	Home URL: https://www.lecrieurderue.fr
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 4096M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Admin Email: jl@lecrieurderue.fr
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Coming Soon Page, Maintenance Mode, Landing Pages &amp; WordPress Website Builder by SeedProd
		Version: 6.15.7
		Author: SeedProd

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 8.12.1
		Author: MonsterInsights

	UpdraftPlus - Backup/Restore
		Version: 1.22.24
		Author: UpdraftPlus.Com, DavidAnderson

== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 8 of 8PHP: 2022-11-24 14:56:30 [notice X 12][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-25 10:58:00 [notice X 26][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-29 14:26:13 [error X 9][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-02 16:13:17 [notice X 1][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-03 14:58:05 [error X 1][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/api.php::267] Uncaught Error: Cannot use object of type WP_Error as array in /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/api.php:267
Stack trace:
#0 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/updater.php(60): ElementorPro\License\API::get_version(false)
#1 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/license/updater.php(130): ElementorPro\License\Updater-&gt;check_transient_data(Object(stdClass))
#2 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(310): ElementorPro\License\Updater-&gt;check_update(Object(stdClass))
#3 /home/mjqi4864/lecrieurderue.fr/wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters(Object(stdClass), Array)
#4 /home/mjqi4864/lecrieurderue.fr/wp-includes/option.php(2018): apply_filters(&#039;pre_set_site_tr...&#039;, Object(stdClass), &#039;update_plugins&#039;)
#5 /home/mjqi4864/lecrieurderue.fr/wp-includes/update.php(391): set_site_transient(&#039;update_plugins&#039;, Object(stdClass))
#6 /home/mjqi4864/lecrieurderue.fr/wp-admin/includes/class-wp- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 10:47:45 [error X 3][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php(172): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/mjqi4864/lecrieurderue.fr/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Ar [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 11:14:19 [notice X 9][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 12:19:29 [notice X 16][/home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/mjqi4864/lecrieurderue.fr/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 4 of 4JS: 2022-11-24 17:09:44 [error X 105][https://www.lecrieurderue.fr/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51816] a is undefined 
JS: 2022-11-30 12:37:22 [error X 1][https://www.lecrieurderue.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:803353] can\&#039;t convert undefined to object 
JS: 2022-11-30 16:56:04 [error X 2][https://www.lecrieurderue.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:649119] this.model.isValidChild is not a function 
JS: 2023-01-25 09:49:13 [error X 21][https://www.lecrieurderue.fr/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:604955] this.$currentEditingArea is null 

Log: showing 20 of 302023-01-12 11:01:49 [info] elementor::elementor_updater Started 
2023-01-12 11:01:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-12 11:01:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-12 11:01:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-12 11:01:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.10.0',
)]
2023-01-13 15:30:04 [info] elementor-pro::elementor_pro_updater Started 
2023-01-13 15:30:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-13 15:30:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-13 15:30:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-13 15:30:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.10.1',
)]
2023-01-24 17:56:57 [info] elementor::elementor_updater Started 
2023-01-24 17:56:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-24 17:56:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-24 17:56:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-24 17:56:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-25 09:45:28 [info] elementor-pro::elementor_pro_updater Started 
2023-01-25 09:45:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-25 09:45:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-25 09:45:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-25 09:45:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello there @DjulLau!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.10! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
