### ISSUE TITLE
⛔ 🐞 Bug Report: Order/checkout element not working in phone - Elementor Pro Version 3.10.2

### ISSUE THREAD

**Issue by timovantwout** [elementor/elementor#21180]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I've added the order/checkout element to my checkout page. It is to wide for the phone and it does not scale.
![Webopname_28-1-2023_232323_vechtdal](https://user-images.githubusercontent.com/60403844/215293842-d955f28c-2fe2-42fc-9f6c-39c819296e9b.jpeg) The problem is probably because the button has to much text..

### Steps to reproduce

1) add element
2) order/checkout element
3) view on mobile
4) scaling does not work

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.3.24
	PHP Version: 8.1.1
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://vechtdal.omitdesign.nl
	Home URL: https://vechtdal.omitdesign.nl
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%category%/%postname%/
	Language: nl
	Timezone: 0
	Admin Email: jorn@alvasi.nl
	Debug Mode: Inactive

== Theme ==
	Name: Omit Design Child Thema
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.69

== Active Plugins ==
	Creative Mail by Newfold Digital
		Version: 1.6.7
		Author: Newfold Digital

	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.0.8
		Author: Facebook

	Invoices for WooCommerce
		Version: 3.1.9
		Author: Bas Elbers

	JetElements For Elementor
		Version: 2.6.8
		Author: Crocoblock

	Jetpack
		Version: 11.7.1
		Author: Automattic

	JetSmartFilters
		Version: 3.0.4
		Author: Crocoblock

	Mollie Payments for WooCommerce
		Version: 7.3.5
		Author: Mollie

	PDF Invoices &amp; Packing Slips for WooCommerce
		Version: 3.3.1
		Author: WP Overnight

	Product Video Gallery for Woocommerce
		Version: 1.4.1.1
		Author: NikHiL Gadhiya

	Rank Math SEO
		Version: 1.0.107.2
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.29
		Author: Rank Math

	Sendcloud | Smart Shipping Service
		Version: 2.2.16
		Author: Sendcloud B.V.

	WooCommerce
		Version: 7.3.0
		Author: Automattic

	WooCommerce Shipping &amp; Tax
		Version: 2.2.1
		Author: WooCommerce

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Eigenschappen ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard actief
	Pictogrammen inline lettertype: Standaard inactief
	Toegang verbeteringen: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Inactief
	Default to New Theme Builder: Standaard actief
	Hello Theme header & footer: Standaard actief
	Landingspagina&#039;s: Standaard actief
	Geneste elementen: Standaard inactief
	Lazy-load achtergrondafbeeldingen: Standaard inactief
	Opslaan als standaard: Standaard actief
	Page Transitions: Standaard actief
	Notes: Inactief
	Loop: Actief
	Loop Carousel: Standaard inactief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief

== Log ==
	
Log: showing 20 of 262023-01-15 13:46:12 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-15 13:46:12 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-15 13:46:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.10.0',
)]
2023-01-15 16:00:22 [info] elementor-pro::elementor_pro_updater Started 
2023-01-15 16:00:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-15 16:00:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-15 16:00:22 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2023-01-15 16:00:22 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2023-01-15 16:00:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.1',
)]
2023-01-18 14:13:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-18 14:13:21 [info] elementor::elementor_updater Started 
2023-01-18 14:13:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-18 14:13:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-18 14:13:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-18 14:13:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-28 20:26:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-28 20:26:50 [info] elementor-pro::elementor_pro_updater Started 
2023-01-28 20:26:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-28 20:26:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-28 20:26:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]

PHP: showing 11 of 11PHP: 2022-12-16 21:49:40 [notice X 22][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-16 21:49:41 [notice X 101][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-12-16 21:58:15 [warning X 26][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-17 00:10:26 [warning X 2][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-31 14:45:49 [warning X 34][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-12-31 14:46:10 [warning X 5][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::71] Undefined array key &quot;elementor-preview&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-15 18:53:48 [notice X 44][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-15 22:12:50 [warning X 37][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Attempt to read property &quot;ID&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-18 14:14:36 [notice X 79][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-18 16:23:12 [notice X 7][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2023-01-18 16:23:12 [notice X 7][/home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/u1357p11175/domains/omitdesign.nl/public_html/vechtdal/wp-content/plugins/jet-smart-filters/framework/jet-elementor-extension/jet-elementor-extension.php(96): Elementor\Controls_Manager -> register_control()
',
)]

JS: showing 5 of 5JS: 2022-12-16 23:45:24 [error X 10][https://vechtdal.omitdesign.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:1068257] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2023-01-15 13:49:29 [error X 24][https://vechtdal.omitdesign.nl/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 
JS: 2023-01-15 16:39:20 [error X 1][https://vechtdal.omitdesign.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:582690] Cannot read properties of null (reading &#039;id&#039;) 
JS: 2023-01-15 17:17:33 [error X 1][https://vechtdal.omitdesign.nl/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.1:2:61404] Cannot convert undefined or null to object 
JS: 2023-01-15 19:04:23 [error X 1][https://vechtdal.omitdesign.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:781513] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibel
	JetElements For Elementor: Niet compatibel

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Niet compatibel

**Comment by nicholaszein** [comment]
Hello @timovantwout,

Thank you for reaching out! 🙏 

This is more of a support question, not really something we can answer here.

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We could not reproduce the issue you're reporting using the same language as you are using.
* This is not an Elementor bug, it's rather a problem of style. This is something you can change yourself in the widget's style tab.
* The checkout design and layout are often affected by your theme.

### ✅ What you can do to solve your issue:
* Isolate the problem by temporarily switching to the Hello Elementor theme.
* Tweak the widget's settings to reduce the size and spacing of the submit button.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
