### ISSUE TITLE
⛔ 🐞 Bug Report: Default setttings for container not working when adding new container with plus sign

### ISSUE THREAD

**Issue by aperojo** [elementor/elementor#21205]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I saved as default a container widget with my desired configuration of padding, margin, direction, wrap, etc. 
Then if I use the container as a widget, drag and drop from the sidebar, it works okay, it has all the default configuration that I set before.
The problem is when I add the container with + button, the container will not show the default configuration I set.
![CleanShot 2023-01-31 at 09 19 35](https://user-images.githubusercontent.com/4948017/215706223-06f3e34a-a856-49c3-921e-b483aa262ba9.gif)

### Steps to reproduce

1) Drag and drop a container, set some padding (for example) and save as default the container.
2) Add a new container with the + button.
3) You will see that it won't inherit the default values.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.18
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://pruebas.testap2.com.es
	Home URL: https://pruebas.testap2.com.es
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 0
	Admin Email: hola@albertoperojo.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

	Performance Lab
		Version: 1.9.0
		Author: WordPress Performance Team

	ShopEngine
		Version: 4.0.0
		Author: Wpmet

	ShopEngine Pro
		Version: 2.2.0
		Author: Wpmet

	WooCommerce
		Version: 7.3.0
		Author: Automattic

== Uso de los elementos ==
	
	archive : 1
		archive-posts : 1
		container : 2
		heading : 1
	container : 1
		container : 3
		heading : 2
		text-editor : 1
	footer : 1
		call-to-action : 1
		container : 7
		heading : 4
		icon-list : 2
		image-box : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	header : 2
		container : 4
		heading : 2
		icon-list : 2
		nav-menu : 2
		theme-site-logo : 2
	popup : 1
		container : 3
		form : 2
		heading : 1
		nav-menu : 1
		text-editor : 1
		video : 1
	wp-post : 0
		heading : 3
		icon-list : 2
		shopengine-add-to-cart : 1
		shopengine-advanced-search : 1
		shopengine-archive-products : 1
		shopengine-archive-result-count : 1
		shopengine-checkout-coupon-form : 1
		shopengine-checkout-form-additional : 1
		shopengine-checkout-form-billing : 1
		shopengine-checkout-form-login : 1
		shopengine-checkout-payment : 1
		shopengine-checkout-review-order : 1
		shopengine-checkout-shipping-methods : 1
		shopengine-filter-orderby : 1
		shopengine-filter-products-per-page : 1
		shopengine-notice : 2
		shopengine-product-excerpt : 1
		shopengine-product-filters : 1
		shopengine-product-meta : 2
		shopengine-product-price : 1
		shopengine-product-rating : 1
		shopengine-product-share : 1
		shopengine-product-stock : 1
		shopengine-product-tabs : 1
		shopengine-product-title : 1
		shopengine-recently-viewed-products : 1
		shopengine-single-product-images : 1
		text-editor : 9
	wp-page : 8
		button : 7
		call-to-action : 5
		container : 60
		divider : 6
		form : 1
		heading : 38
		icon : 2
		icon-box : 15
		icon-list : 2
		image : 2
		image-box : 16
		image-carousel : 2
		loop-carousel : 3
		loop-grid : 1
		posts : 1
		template : 1
		testimonial : 9
		text-editor : 15
		toggle : 2
	single-post : 1
		container : 5
		heading : 3
		image : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-title : 1
	loop-item : 9
		button : 1
		container : 9
		heading : 1
		post-info : 3
		theme-post-excerpt : 1
		theme-post-featured-image : 7
		theme-post-title : 2
		woocommerce-product-add-to-cart : 4
		woocommerce-product-price : 4
		woocommerce-product-title : 4
	error-404 : 1
		button : 1
		container : 3
		heading : 2
		testimonial : 3
		text-editor : 1

== Ajustes ==
	
	cpt_support: post, page, product, shopengine-template
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Caracteristicas ==
	Custom Fonts: 0
	Custom Icons: 0

== Integraciones ==
	
	woocommerce: Activo

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Activo
	Mejoras de accesibilidad: Activo
	Puntos de ruptura personalizados adicionales: Activo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Activo
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Activo
	Por defecto, el nuevo constructor de temas: Activo
	Cabecera y pie de página del tema Hello: Activo
	Páginas de destino: Activo
	Elementos anidados: Activo
	Carga diferida de imágenes de fondo: Activo
	Guardar como por defecto: Activo
	Transiciones de páginas: Activo
	Notes: Activo
	Bucle: Activo
	Loop Carousel: Inactivo por defecto
	Envíos de formulario: Activo
	Ajuste de scroll: Activo

**Comment by Gapito2** [comment]
Mmmm interesting... I have noticed this problem too. It seems it's a bug.

**Comment by nicholaszein** [comment]
Hello there,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is the expected behavior. When you use the _Add New Container_ button using the Canvas Drop Area, it is not meant to inherit the defaults you defined for your container, since those are preconfigured layouts.
* We have no plans to change this behavior for the time being.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

Kind regards
