### ISSUE TITLE
⛔ 🐞 Bug Report: no puedo publicar mi pagina web

### ISSUE THREAD

**Issue by estudiojuridicovalderrama** [elementor/elementor#21286]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

buenas tardes
Mi problema que tengo es que no puedo publicar mi pagina web yo use el editor de elementor pero no se como publicar mi pagina a google. Por favor me ayudarían que el problema lo tengo hace 2 días
![error](https://user-images.githubusercontent.com/125042025/218119609-f5b2df5e-a664-48f2-a806-254cc3f88897.png)

### Steps to reproduce

Me voy a la parte de pagina y me voy a todas las paginas  y antes me aparecía un botón de publicar cuando lo presiones ese botón me apareció un error retrocedí y ahora me sale el botón de actualizar
![error](https://user-images.githubusercontent.com/125042025/218116403-056c2077-f4b1-45f3-971e-0931a6cdef1c.png)
 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

quiero que me ayudan a publicar mi pagina web yo pague todo el wordpres por un año dándoles la confianza de diseñar mi pagina y publicarla pero no puedo puedo publicar

**Comment by estudiojuridicovalderrama** [comment]
Por favor ayudarme a este problema para haci publicar mi pagina y seguir con mi pagina con wordpress

**Comment by estudiojuridicovalderrama** [comment]
Por favor ayudarme a este problema para haci publicar mi pagina y seguir con mi pagina con wordpress

**Comment by estudiojuridicovalderrama** [comment]
Ayudar por favor con este problema

**Comment by nicholaszein** [comment]
Hello @estudiojuridicovalderrama,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
