### ISSUE TITLE
🔗 🚀 Feature Request: Hide elements on Google Maps widget when "Prevent Scroll" is ON (Duplicate of #1319)

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#2129]
The title says it all really 😉

A couple of my clients are getting confused as to why Google Maps controls are visible but you can't click on them to do anything (like zoom in or out). 

![image](https://user-images.githubusercontent.com/1435638/28908582-9affc1c0-7863-11e7-835a-d3a8d7782f55.png)

I realise this is due to Prevent Scroll rightfully getting in the way but it would be nice if the PS feature also gave Google Maps a set of different parameters to hide all clickable elements.

**Comment by drawcard** [comment]
Also from a usability perspective it doesn't make sense to display a card with a link saying "View larger map" if you can't click on it at all :D

**Comment by arielk** [comment]
I merged this issue with another issue #1319 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by RonW7** [comment]
It'd be great if one could go to Elementor settings and be presented with a checkbox...
"Prevent Scrolling" Yes/No .... a global setting. (Instead of individually setting each map)
