### ISSUE TITLE
🐞 Bug Report: Save & Back handle in the Loop Carousel is hidden by `.swiper { overflow: hidden }` - [ED-9808]

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21316]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

In loop carousel widget, there is no save and back button (like loop grid). In this case, we have to scroll up the page to be able to access the edit page button. I think this button is missing. Because it is very important.

### Steps to reproduce

1- Add loop carousel widget.
2- Click on the Create Template button.
3- Once loaded, there is no button to save and back.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-domain.com-13-02-2023.txt](https://github.com/elementor/elementor/files/10725316/system-info-domain.com-13-02-2023.txt)

**Comment by nicholaszein** [comment]
Hello @Michaelgimii! 

Thank you for submitting your issue! 🙏 

I can confirm the button is there, it's just hidden behind the `overflow: hidden` property of the `.swiper` loop container. This is related to [this comment](https://github.com/elementor/elementor/discussions/21125#discussioncomment-4872011).

A fix for this issue is being discussed.

Kind regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.11.2**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
