### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Elementor 3.11 init_swiper_settings null error

### ISSUE THREAD

**Issue by cmitchelldatix** [elementor/elementor#21320]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Plugin updated to 3.11 earlier this morning resulting in a critical site error. Narrowed down the issue to the Elementor plugin via disabling plugins one-by-one until the error was no longer occurring.

Wordpress is completely up to date in our sandbox site (error below). Error also occurred in our production site with Wordpress v6.0.3

Enabled debugging and narrowed the error down to the updated 'swiper' initialization logic. To get around the error and re-enable our site, I've commented out the 'swiper' initialization logic to bypass the error (line 176 in wordpress/wp-content/plugins/elementor/includes/frontend.php). We're not currently using 'swiper' in our site, so not concerned with this functionality being commented out.

````txt
[13-Feb-2023 21:09:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_feature_active() on null in /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php:339
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(143): Elementor\Frontend->__construct()
#2 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(135): premiumpress_elementor_shortcode->__construct()
#3 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(158): premiumpress_elementor_shortcode::instance()
#4 /bitnami/wordpress/wp-content/themes/VT10/framework/_config.php(84): require_once('/bitnami/wordpr...')
#5 /bitnami/wordpress/wp-content/themes/VT10/functions.php(17): include('/bitnami/wordpr...')
#6 /opt/bitnami/wordpress/wp-settings.php(585): include('/bitnami/wordpr...')
#7 /bitnami/wordpress/wp-config.php(187): require_once('/opt in /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php on line 339
````

### Steps to reproduce

1) Elementor 3.11 installed
2) Site critical error with error message in description

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.48 (Unix) OpenSSL/1.1.1d
	MySQL version: Source distribution v10.3.30
	PHP Version: 7.4.21
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://sandbox.erp-demos.net
	Home URL: https://sandbox.erp-demos.net
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: UTC
	Admin Email: info@erp-demos.net
	Debug Mode: Active

== Theme ==
	Name: Video Theme
	Version: 10.2.4
	Author: Mark Fail - PremiumPress
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.70
		Author: ServMask

	BackupBuddy
		Version: 8.7.4.0
		Author: iThemes

	Better Search Replace
		Version: 1.4.2
		Author: WP Engine

	Easy Updates Manager
		Version: 9.0.14
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.11.0
		Author: Elementor.com

	Email Templates
		Version: 1.4.2
		Author: wpexpertsio

	Export User Data
		Version: 2.2.6
		Author: Q Studio

	Header Footer Code Manager
		Version: 1.1.32
		Author: 99robots

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	New User Approve Premium (Premium)
		Version: 2.5
		Author: NewUserApprove

	Redirection
		Version: 5.3.9
		Author: John Godley

	UpdraftPlus - Backup/Restore
		Version: 1.22.24
		Author: UpdraftPlus.Com, DavidAnderson

	WP Mail SMTP
		Version: 3.7.0
		Author: WPForms

	WP Super Cache
		Version: 1.9.3
		Author: Automattic


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 


== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default


== Log ==
	
Log: showing 20 of 372021-10-19 12:13:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.5',
  'to' => '3.4.6',
)]
2021-11-01 00:19:39 [info] elementor::elementor_updater Started 
2021-11-01 00:19:39 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-01 00:19:40 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-01 00:19:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.6',
  'to' => '3.4.7',
)]
2021-11-01 00:19:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.6',
  'to' => '3.4.7',
)]
2021-11-16 12:33:27 [info] elementor::elementor_updater Started 
2021-11-16 12:33:27 [info] Elementor/Upgrades - _on_each_version Start  
2021-11-16 12:33:27 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-16 12:33:27 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2021-11-16 12:33:27 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2021-11-16 12:33:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.4.8',
)]
2021-11-16 12:33:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.4.8',
)]
2021-12-15 00:11:53 [info] elementor::elementor_updater Started 
2021-12-15 00:11:53 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-15 00:11:53 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-15 00:11:53 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2021-12-15 00:11:53 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2021-12-15 00:11:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]
2021-12-15 00:11:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.5.0',
)]

PHP: showing 5 of 5PHP: 2021-10-13 01:03:24 [notice X 30002][/bitnami/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php::1479] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-04 00:00:45 [error X 1][/bitnami/wordpress/wp-content/plugins/elementor/includes/widgets/button.php::18] Trait 'Elementor\Includes\Widgets\Traits\Button_Trait' not found [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 12:05:01 [error X 84][/bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php:339
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(143): Elementor\Frontend->__construct()
#2 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(135): premiumpress_elementor_shortcode->__construct()
#3 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(158): premiumpress_elementor_shortcode::instance()
#4 /bitnami/wordpress/wp-content/themes/VT10/framework/_config.php(84): require_once('/bitnami/wordpr...')
#5 /bitnami/wordpress/wp-content/themes/VT10/functions.php(17): include('/bitnami/wordpr...')
#6 /opt/bitnami/wordpress/wp-settings.php(566): include('/bitnami/wordpr...')
#7 /bitnami/wordpress/wp-config.php(183): require_once('/opt [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 21:06:06 [error X 10][/bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php:339
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(143): Elementor\Frontend->__construct()
#2 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(135): premiumpress_elementor_shortcode->__construct()
#3 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(158): premiumpress_elementor_shortcode::instance()
#4 /bitnami/wordpress/wp-content/themes/VT10/framework/_config.php(84): require_once('/bitnami/wordpr...')
#5 /bitnami/wordpress/wp-content/themes/VT10/functions.php(17): include('/bitnami/wordpr...')
#6 /opt/bitnami/wordpress/wp-settings.php(585): include('/bitnami/wordpr...')
#7 /bitnami/wordpress/wp-config.php(183): require_once('/opt [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-13 21:09:44 [error X 9][/bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php:339
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/elementor/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(143): Elementor\Frontend->__construct()
#2 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(135): premiumpress_elementor_shortcode->__construct()
#3 /bitnami/wordpress/wp-content/themes/VT10/framework/new_class/ppt_6_shortcodes.php(158): premiumpress_elementor_shortcode::instance()
#4 /bitnami/wordpress/wp-content/themes/VT10/framework/_config.php(84): require_once('/bitnami/wordpr...')
#5 /bitnami/wordpress/wp-content/themes/VT10/functions.php(17): include('/bitnami/wordpr...')
#6 /opt/bitnami/wordpress/wp-settings.php(585): include('/bitnami/wordpr...')
#7 /bitnami/wordpress/wp-config.php(187): require_once('/opt [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	

				
````

</details>

**Comment by EducatedSingles** [comment]
We have a similar issue with https://findsupervisor.com

**Comment by Digitalins** [comment]
I also have the same problem after updating elementor 3.11 on my wordpress website. 

information
Website Link : https://muslimnikah.lk
Worpress Version: 6.1.1
Elementor Version: 3.11
Php version: 7.4

== Theme ==
Name: Dating Theme
Version: 10.8.8
Author: Mark Fail - PremiumPress
Child Theme: No

Error Details
=============
An error of type E_ERROR was caused in line 339 of the file /home/busijgem/[muslimnikah.lk/wp-content/plugins/elementor/includes/frontend.php](http://muslimnikah.lk/wp-content/plugins/elementor/includes/frontend.php). Error message: Uncaught Error: Call to a member function is_feature_active() on null in /home/busijgem/[muslimnikah.lk/wp-content/plugins/elementor/includes/frontend.php:339](http://muslimnikah.lk/wp-content/plugins/elementor/includes/frontend.php:339)
Stack trace:
#0 /home/busijgem/[muslimnikah.lk/wp-content/plugins/elementor/includes/frontend.php(176)](http://muslimnikah.lk/wp-content/plugins/elementor/includes/frontend.php(176)): Elementor\Frontend->init_swiper_settings()
#1 /home/busijgem/[muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php(149)](http://muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php(149)): Elementor\Frontend->__construct()
#2 /home/busijgem/[muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php(141)](http://muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php(141)): premiumpress_elementor_shortcode->__construct()
#3 /home/busijgem/[muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php(164)](http://muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php(164)): premiumpress_elementor_shortcode::instance()
#4 /home/busijgem/[muslimnikah.lk/wp-content/themes/DA10/framework/_config.php(104)](http://muslimnikah.lk/wp-content/themes/DA10/framework/_config.php(104)): include('/home/busijgem/...')
#5 /home/busijgem/[muslimnikah.lk/wp-content/themes/DA10/functions.php(7)](http://muslimnikah.lk/wp-content/themes/DA10/functions.php(7)): include('/home/busijgem/...')
#6 /home/busijgem/[muslimnikah.lk/wp-settings.php(585)](http://muslimnikah.lk/wp-settings.php(585)): include('/h

**Comment by nicholaszein** [comment]
Hello, there! 

Thank you for submitting your issue! 🙏 

Elementor is preparing to update the Swiper.js library. There is a new experiment called **"Upgrade Swiper Library**.

### 🧐 Before we continue, and in order to solve your issue, please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else. So far we could not reproduce your issue. And it's likely it is caused by cache.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

- 🔛 **Enable / Disable the Experiment:** Try enabling/disabling the **Upgrade Swiper Library** Feature in your WordPress _Dashboard > Elementor > Settings > Features_, and clear the cache again.

### 🧐 Please follow the steps above and get back to us with your feedback so we can troubleshoot your issue faster and better.

Regards

**Comment by erighetto** [comment]
The exception was thrown by a function `premiumpress_elementor_shortcode::instance()` in a custom theme by PremiumPress: 

/home/busijgem/muslimnikah.lk/wp-content/themes/DA10/framework/new_class/ppt_6_shortcodes.php at line 164.



```
class premiumpress_elementor_shortcode {

	private static $_instance = null;

	private static $elementor_frontend;

	public static function instance() {

		if ( is_null( self::$_instance ) ) {
			self::$_instance = new self();
		}

		return self::$_instance;

	}

	public function __construct() {

		if ( defined( 'ELEMENTOR_VERSION' ) ) {
			self::$elementor_frontend = new \Elementor\Frontend();

			add_shortcode( 'premiumpress_elementor_template', array( $this, 'elementor_add_template' ) );
		}
	}

	public function elementor_add_template( $atts ) {
		$atts = shortcode_atts( array(
			'id' => '',
		), $atts, 'elementor_add_template' );

		if ( $atts['id'] !== '' ) {
			return self::$elementor_frontend->get_builder_content_for_display( $atts['id'] );
		}
	}
}

premiumpress_elementor_shortcode::instance();
```

I think the problem relies in `self::$elementor_frontend = new \Elementor\Frontend();`
probably not the best way to get the Frontend plugin instance.

**Comment by nicholaszein** [comment]
> The exception is thrown by the function `premiumpress_elementor_shortcode::instance()` in a custom theme by PremiumPress:
> 

Hello @erighetto,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

The issue you're reporting is caused by an incompatible theme. We can't provide support for that.

Regards
