### ISSUE TITLE
🔗 🐞 Bug Report: RTL issue in Loop Carousel widget (Related to #21338) - [ED-9844]

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21326]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

Loop Carousel widget have problem on RTL websites. When you add the widget, everything is fine :

![Screenshot (1014)](https://user-images.githubusercontent.com/77163248/218699424-7d7df824-020b-46c9-831f-c76806955b99.png)

But after clicking the create template button, the loop item is moved to the other side. While it should be on the right side : 

![Screenshot (1015)](https://user-images.githubusercontent.com/77163248/218699888-f6a1bc30-309a-4d7a-823b-a0551c195fc6.png)

This bug is also visible in the front end. On the front end, posts are displayed in a carousel, from left to right. While the website is RTL : 

![RTL](https://user-images.githubusercontent.com/77163248/218701244-c93dbedb-5a8a-4c2b-ac87-34019c62518e.png)

### Steps to reproduce

1- Make sure the website is RTL.
2- Add the Loop Carousel widget. For now, everything is going as expected.
3- Click on the Create Template button. After the template is loaded, the loop item is moved to the left.

Also, if you check it in the front, the posts are added from left to right in the carousel.

**In general, any widget we add inside the loop carousel template is added as LTR.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-localhost-14-02-2023.txt](https://github.com/elementor/elementor/files/10731115/system-info-localhost-14-02-2023.txt)

**Comment by 79ho3ein** [comment]
As another small bug in RTL, save and back buttons are different in loop grid and loop carousel widgets. **(In the loop carousel, the arrow icon is on the left side of the text. While it should be on the right side of the text)**

Loop Grid (without problem)

![Loop Grid](https://user-images.githubusercontent.com/77163248/218713104-e40b9be8-ca7f-45e2-a7ce-0577106acd8c.png)

Loop Carousel (It has a problem)

![Loop Carousel](https://user-images.githubusercontent.com/77163248/218713290-c4ac77d4-6925-474e-86ea-27ac8dc9a8ad.png)

**Comment by nicholaszein** [comment]
Hi @79ho3ein! 

Thank you for submitting your issue! 🙏 

🏷️ This issue has been labeled and will be forwarded to the team for validation and possible solution. Please keep in mind that we can't provide any ETA on when this issue could be fixed if it is validated. We ask for patience.

Best regards

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

Indeed this is a bug that we could reproduce on our end. Thanks for reporting it! 🙏

We are working on a fix, and it should take some time to conclude it. We ask for some patience until we find a solution.

This issue as well as issue #21338, can be partially solved by changing the Direction from **Left** to **Right** when editing the Loop Carousel like in the video below:


https://user-images.githubusercontent.com/113993460/220611310-0a0a31a7-0157-4d36-8d65-81b567dd22db.mp4



We are working to change the direction by default when RTL is enabled so users don't have to experience such issues.

I hope this helps for now. As soon as we have a working fix, we'll update this thread!

Kind regards

**Comment by 79ho3ein** [comment]
thank you @nicholaszein

**Comment by 79ho3ein** [comment]
Hi @nicholaszein👋

I wanted to ask if there is any news about solving this issue?

**Comment by 79ho3ein** [comment]
Hi @nicholaszein, Thanks for following up. Yes it seems to be solved.

**Comment by nicholaszein** [comment]
Awesome @79ho3ein!

Thanks for letting me know! 😉 I'm closing this issue!
