### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: When picking up colors from the JetEngine Options page it doesn't work

### ISSUE THREAD

**Issue by tizum** [elementor/elementor#21357]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

when using the dynamic tag to get the colors from an options page made with jetEngine, the color is no longer rendered in the widget, text, icons and the like.

when it works using global colors, the color renders in the constructor, however in the front end it loses all style.

you can follow the problem being shown in this video, I speak in Portuguese, but just watching it I'm sure you'll understand.

https://eadvideos.vmaker.com/record/Fguy3VXm22biWtSS

### Steps to reproduce

1 - install wordpress and install plugins, Elementor, Elementor Pro and JetEngine
2- Create a new options page, define the metafields Background 1 (field type = colorpicker), background 2 (field type = text), background 3 (field type = colorpicker)
4- fill in the options with your colors
5- create a new page and drag some widgets to test the options page color.
6- use dynamic tags to get options page color between
  the 3 colors you defined using the options that jetEngine provides.
7- see the bug happening, it doesn't show the color in the constructor nor in the front end.

another method that should work.

after following steps 1,2,3,4 and 5.

instead of using dynamic tags directly in choosing the color of the widget, click on the gear to access the global colors of the element, create a new color and use dynamic tags to get the color from the options page.

the result is that when using the global colors on the page, everything works perfectly, but when going to the front-end, the colors are not rendered.

here's a step-by-step video of everything I did after items 1 and 2 were done.

https://eadvideos.vmaker.com/record/Fguy3VXm22biWtSS

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.4
	MySQL version: (Ubuntu) v8.0.32
	PHP Version: 8.0.27
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://microsite.lp.webtizze.com
	Home URL: https://microsite.lp.webtizze.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Admin Email: webtizze@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.11.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.0
		Author: Elementor.com

	FluentSMTP
		Version: 2.2.4
		Author: FluentSMTP & WPManageNinja Team

	JetEngine
		Version: 3.1.1
		Author: Crocoblock


== Uso dos elementos ==
	
	wp-page : 3
		button : 2
		container : 7
		form : 1
		heading : 9
		icon : 1
		text-editor : 1
	single-post : 1
		button : 1
		container : 3
		heading : 2


== Configurações ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap


== Recursos ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrações ==
	


== Experimentos do Elementor ==
	Saída DOM otimizada: Ativo por padrão
	Carregamento melhorado de recursos: Ativo por padrão
	Carregamento melhorado de CSS: Ativo por padrão
	Ícones da fonte inline: Ativo
	Melhorias na acessibilidade: Ativo por padrão
	Pontos de quebra adicionais personalizados: Ativo por padrão
	admin_menu_rearrangement: Inativo por padrão
	Flexbox Container: Ativo
	Upgrade Swiper Library: Inativo por padrão
	Padrão para Novo Construtor de Tema: Ativo por padrão
	Tema Hello - Cabeçalho & Rodapé: Inativo
	Editor V2: Inativo por padrão
	Páginas de Aterrissagem: Inativo
	Elementos aninhados: Ativo
	Imagens com carregamento gradual: Ativo
	Salvar como padrão: Ativo por padrão
	Transições da página: Inativo
	Atividades Desempenhadas: Inativo
	Repetir: Ativo por padrão
	Envios do formulário: Ativo por padrão
	Pressão da Rolagem: Ativo por padrão
	Mega Menu: Inativo por padrão


== Registo ==
	
Log: showing 10 of 102023-02-14 12:29:12 [info] elementor-pro::elementor_pro_updater Started 
2023-02-14 12:29:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-14 12:29:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-14 12:29:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.0',
)]
2023-02-14 12:29:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.0',
)]
2023-02-14 12:29:12 [info] elementor::elementor_updater Started 
2023-02-14 12:29:12 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-14 12:29:12 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-14 12:29:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]
2023-02-14 12:29:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.0',
)]

JS: showing 1 of 1JS: 2023-02-14 15:42:53 [error X 6][https://microsite.lp.webtizze.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0:3:129011] C.getNamespaceArray is not a function 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatível

== Elementor Pro - Compatibility Tag ==
	


````

</details>

**Comment by nicholaszein** [comment]
Oi Anderson (@tizum),

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

In your specific case, Crocoblock is the one responsible for making JetEngine's Dynamic Tag implementation, not Elementor. Elementor officially provides support only for ACF and Pods.

It would be important to contact Crocoblock and report your issue there.

Unfortunately in your case, we can't help. 

We are still investigating issue #20368, which is on the same subject. I'm aware there are plenty of new comments and that you have mentioned me, I'll make sure to provide some feedback for everyone on that issue soon.

Please continue the conversation there. 👍 

Regards
