### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: "Add to cart" widget on "Loop Item" (Product) template not work with any "variation products swatches plugin(s)".

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#21366]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

"Add to cart" widget on "Loop Item" (Product) template not work with any variation production swatches plugin. 
My websites (Web store) use WooCommerce and always have Variation Products. I use "variation products swatches plugin(s)" to display swatches for variation products on "Archive Products page" "Products list page" and "Single Product page"
When use them with "Add to cart" widget on "Loop Item" (Product) template => only display "Select options"

I test with many "variation products swatches plugin(s)" and non of them work.

Please check thank.

### Steps to reproduce

Create some variation products. Use one of "variation products swatches plugin(s)". Config variation products swatches display for Archive / Shop.

1) Create Loop Item template
2) Choice Product
3) Add "Add to Cart" widget
4) Create a Page
5) Add Loop Grid widget
6) Choice "Product" Loop Item template
7) View page => Got Bug

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.19
	PHP Version: 8.2.1
	PHP Memory Limit: 64M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://my-domain.com
	Home URL: https://my-domain.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: admin@my-domain.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0

== Active Plugins ==
	Elementor
		Version: 3.11.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.1
		Author: Elementor.com

	Swatchly - Variation Swatches for WooCommerce Products
		Version: 1.1.9
		Author: HasThemes

	WooCommerce
		Version: 7.4.0
		Author: Automattic


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @datverse,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

Elementor does not provide any compatibility for 3rd-party WooCommerce add-ons related to variation swatches. Unfortunately, most of these plugins use methods that require a default WooCommerce Product Archive template (with the default WooCommerce Loop), or default WooCommerce Product Single template to work, due to how they were built, and the scripts they use, which is something Elementor can't predict or add support for all the different implementations out there.

But if you think this should be a feature, you can submit a [Feature Request](https://github.com/elementor/elementor/discussions/new?category=feature-request) and connect us with 3rd-party devs and we can see if we can do something about it.

For now, that's all we can help with.

Regards
