### ISSUE TITLE
✅ 🐞 Bug Report: Save as Default breaks the Loop Carousel Pagination and Animation in some edge cases - [ED-9852]

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21371]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @nicholaszein, Related to [this issue](https://github.com/elementor/elementor/issues/21334).

save as default in the loop carousel widget, completely destroys the widget.

### Steps to reproduce

1- Add loop carousel widget.
2- In this widget, change the value of two options Gap between slides and Transition Duration (ms).
3- Then save the widget as default.
4- add the loop carousel widget again.

Due to you closing that issue, I could not post the video here. If you need to watch the video, please watch it [here](https://github.com/elementor/elementor/issues/21334#issuecomment-1431061383).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-localhost-14-02-2023.txt](https://github.com/elementor/elementor/files/10756623/system-info-localhost-14-02-2023.txt)

**Comment by nicholaszein** [comment]
Hi @79ho3ein! 

Thank you for the clarification! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

🏷️ This issue has been labeled and will be forwarded to the team for validation and possible solution. Please keep in mind that we can't provide any ETA on when this issue could be fixed if it is validated. We ask for patience.

Best regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
