### ISSUE TITLE
⛔ 🐞 Bug Report: Lightbox images on search results in Archive Posts pages

### ISSUE THREAD

**Issue by msaari** [elementor/elementor#21373]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I was asked to open an issue here to contact developers directly. A client of mine is using Relevanssi Premium to power a search that has image attachments in the results. Relevanssi is not involved in this issue; the critical part is that it just adds image attachments to the search results.

When those images are opened in the Elementor lightbox, they don't have captions. That's obvious from the source code, as the image links are just links without any of the data attributes that would contain the caption. Now, the question is: is there a way in Elementor to modify the link in the Archive Posts so that we could add the data attributes that would add the captions to the image links? Is there a filter hook we could use?

We can't do it from Relevanssi; with Relevanssi hooks, we can only modify the image URL, not the link tag.

### Steps to reproduce

1) Create a normal Archive Posts search results template.
2) Enable the lightbox.
3) Do a search that returns images as results.
4) Click the image to open the lightbox.
5) No caption!

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

This is on a client site; I don't have all the information.

**Comment by nicholaszein** [comment]
Hello @msaari, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

We need a link to the site to understand what is going on.

As far as I know, Elementor will add the attribute tags to images automatically **_IF_** they are present in the image, meaning, when the image is added to the media library, you need to fill in the Title, Description, and Alt tags in order for them to appear in the library. Here's an example:


https://user-images.githubusercontent.com/113993460/220624124-daa32a83-1ecd-4606-a965-36faf29efd61.mp4



### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards,

Nick
