### ISSUE TITLE
✅ 🐞 Bug Report: Elementor 3.11.1 breaks WP-TOOLKIT - [ED-10136]

### ISSUE THREAD

**Issue by hosting-gl** [elementor/elementor#21431]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Elementor 3.11.1

When using using Wordpress tookit in Cpanel, it throws this error when trying to use "login to wordpress" 

"Error getting administrator credentials: An error has occurred when decoding JSON: illegal Token"

if downgrading elementor, problem goes away. If disabling elementor, problem goes away.

### Steps to reproduce

Try to login to Wordpress via WP-Toolkit in Cpanel

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

Removed system info due to privacy reasons, please dont ask people to post a complete system info profile public........

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12.3**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
