### ISSUE TITLE
✅ 🐞 `Open Sans Condensed` missing from Google Fonts list

### ISSUE THREAD

**Issue by PermaPain** [elementor/elementor#21452]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the latest version of Elementor, the Google Font: Open Sans Condensed
is missing.

It was available in Elementor v3.9.2.

The Elementor [font list](https://github.com/elementor/elementor/blob/master/includes/fonts.php) is indeed missing this font. 

### Steps to reproduce

Install latest Elementor. 
Edit text.
Try to select font "Open Sans Condensed". 
That font is not there.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

n/a

**Comment by nicholaszein** [comment]
Hey there, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:


- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Kind regards

**Comment by KanervaKangas** [comment]
I have the same issue after updating. Open Sans Condensed is just missing from the font list.
[system-info-kiinteistohuoltomaatta.fi-25-02-2023.txt](https://github.com/elementor/elementor/files/10830391/system-info-kiinteistohuoltomaatta.fi-25-02-2023.txt)

**Comment by nicholaszein** [comment]
Thank you for the feedback @KanervaKangas! 

We really appreciate it, especially since you shared your System Info. 🙏 

Let me investigate it and get back to you with my findings. 🧐

**Comment by PermaPain** [comment]
this missing font is literally the only thing preventing me from upgrading

**Comment by sensodia** [comment]
Same issue, can't update to Elementor latest versions without having the Open Sans Condensed font disappearing and being replaced by native fonts.

**Comment by PermaPain** [comment]
> Thank you for the feedback @KanervaKangas!
> 
> We really appreciate it, especially since you shared your System Info. 🙏
> 
> Let me investigate it and get back to you with my findings. 🧐

thanks Nicolas, is there any update?
thanks

**Comment by jellederijke** [comment]
I struggle with this issue, as well. On version 3.12.3. This breaks the style of my client's website, sadly.

**Comment by PermaPain** [comment]
I'm giving up on this.

Apparently it's more important for Elementor to develop ridiculous feature like "Elementor AI Write – Boost your productivity and efficiency, while elevating your website’s design and content." 

Btw there are other condensed-type fonts. 
Search for "condensed" within [Google Fonts](https://fonts.google.com/?query=condensed) or within Elementor font picker. 

Looks like "Fira Sans Extra Condensed" works well for me (sans horizontal spacing). 
Hopefully E won't rid of that one as well.

cheers to all

**Comment by dev-caballero** [comment]
Hi, I confirm this issue, another site affected by this, how long it takes for an entire team to fix this font issue???

**Comment by jellederijke** [comment]
This issue is still present. Please fix this as this prevents upgrading to new version. Thanks!

**Comment by jrothra** [comment]
It seems it wasn't Elementor that removed Open Sans Condensed: [Google Fonts](https://fonts.google.com/?query=Open+Sans+Condensed) removed it from their repository.

**Comment by nicholaszein** [comment]
Hey, everyone!

Open Sans Condensed was indeed removed from Google Fonts.

Open Sans is now a Variable Font. 

Elementor doesn't support variables fonts... yet... 😉 🤫

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.24.0! 🥳 

The **Open Sans** font is now a **Variable font**, and the **Open Sans Condensed font was therefore deprecated by Google**.

In **Elementor Pro v3.24.0** we introduced support for installing **Variable Fonts in Elementor > Custom Fonts**. You can use this feature to download **Open Sans from Google**, and **install it as a local Variable Font**. This feature allows you to change the **Weight and Width of Variable fonts**, solving the issue with the missing Condensed font.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
