### ISSUE TITLE
⛔ 🐞 Bug Report: bundle.min.js files not being loaded in CDN

### ISSUE THREAD

**Issue by rachaelburke-krb** [elementor/elementor#21456]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Confirmed by webhost who provide a bunny.net cdn implementation.

Note from them:
I took a good look at this one and it seems that Elementor includes those references via an existing javascript file [webpack-pro.runtime.min.js](https://titahibay.school.nz/wp-content/plugins/elementor-pro/assets/js/webpack-pro.runtime.min.js) 
﻿
﻿[webpack-pro.runtime.min.js](https://titahibay.school.nz/wp-content/plugins/elementor-pro/assets/js/webpack-pro.runtime.min.js) itself is served from the CDN however the code in that file includes the other ones using the domain of the site after it's loaded so WordPress can't re-write the URL's to the CDN URL.

The following files do NOT get loaded by CDN on the website i'm working on currently

/wp-content/plugins/elementor-pro/assets/js/nav-menu.c8d112707fd7172d2a9d.bundle.min.js
/wp-content/plugins/elementor-pro/assets/js/search-form.0ef02f9fd5e7db2ea91b.bundle.min.js
/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js?ver=5.3.6
/wp-content/plugins/elementor/assets/js/text-editor.2c35aafbe5bf0e127950.bundle.min.js
/wp-content/plugins/elementor-pro/assets/js/form.72b77b99d67b130634d2.bundle.min.js
/wp-content/plugins/elementor-pro/assets/js/popup.483b906ddaa1af17ff14.bundle.min.js

### Steps to reproduce

Run site on a CDN

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - (GPL) v5.7.41
	PHP Version: 8.0.27
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://titahibay.school.nz
	Home URL: https://titahibay.school.nz
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: Pacific/Auckland
	Admin Email: rachael@krbconsulting.co.nz
	Debug Mode: Inactive

== Theme ==
	Name: Titahi Bay School - Astra Customisations
	Version: 1.0.0
	Author: Rachael Burke
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.4
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

== Active Plugins ==
	301 Redirects
		Version: 2.72
		Author: WebFactory Ltd

	Admin Columns
		Version: 4.5.5
		Author: AdminColumns.com

	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.0
		Author: Shabti Kaplan

	All-in-One WP Migration
		Version: 7.69
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.47
		Author: ServMask

	Autoptimize
		Version: 3.1.5
		Author: Frank Goossens (futtta)

	Autoremove Attachments
		Version: 1.3.1
		Author: Polygon Themes

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.11.16
		Author: WPVibes

	Elementor Pro
		Version: 3.11.2
		Author: Elementor.com

	Elementor SuperCat
		Version: 2.9
		Author: Nicola Cavallazzi

	Limit Login Attempts Reloaded
		Version: 2.25.10
		Author: Limit Login Attempts Reloaded

	ManageWP - Worker
		Version: 4.9.16
		Author: GoDaddy

	Post Types Order
		Version: 1.9.9.2
		Author: Nsp Code

	White Label CMS
		Version: 2.5
		Author: www.videousermanuals.com

	Wordfence Security
		Version: 7.8.2
		Author: Wordfence

	Wordify Tools
		Version: 1.0
		Author: wordify.com

	WP Fastest Cache
		Version: 1.0.9
		Author: Emre Vona

	Yoast SEO
		Version: 19.13
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 19 of 192023-01-09 10:51:47 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2023-01-09 10:51:48 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data callback needs to run again 
2023-01-09 10:51:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2023-01-09 10:51:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2023-01-09 10:51:48 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2023-01-09 10:51:48 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2023-01-09 10:51:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.9.2',
)]
2023-02-24 09:46:48 [info] elementor::elementor_updater Started 
2023-02-24 09:46:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-24 09:46:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-24 09:46:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-02-24 09:46:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-02-24 09:46:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-02-24 09:47:07 [info] elementor-pro::elementor_pro_updater Started 
2023-02-24 09:47:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-24 09:47:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-24 09:47:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-02-24 09:47:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]
2023-02-24 09:47:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.2',
  'to' => '3.11.2',
)]

JS: showing 12 of 12JS: 2023-01-08 22:21:34 [error X 20][https://titahibay.school.nz/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51823] undefined is not an object (evaluating \'a.replace\') 
JS: 2023-01-25 16:35:58 [error X 1][https://titahibay.school.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:1068257] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2023-01-25 16:45:24 [error X 4][https://titahibay.school.nz/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2023-01-25 16:59:58 [error X 1][https://titahibay.school.nz/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.2:2:2968] Can\'t find variable: elementor_new_template_form_controls 
JS: 2023-01-26 01:29:29 [error X 366][https://titahibay.school.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:608340] Cannot read properties of undefined (reading \'get\') 
JS: 2023-01-26 02:10:06 [error X 10][https://titahibay.school.nz/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.9.2:2:51477] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 
JS: 2023-01-26 21:24:01 [error X 1][https://titahibay.school.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:1068256] null is not an object (evaluating \'$.getBoundingClientRect\') 
JS: 2023-01-26 21:25:59 [error X 4][https://titahibay.school.nz/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:877] Can\'t create duplicate variable: \'$dcWidgetIdInput\' 
JS: 2023-02-10 01:04:07 [error X 1][https://titahibay.school.nz/wp-admin/post.php?post=2&action=elementor#:1:1] Identifier \'$dcWidgetIdInput\' has already been declared 
JS: 2023-02-23 20:49:11 [error X 1][https://titahibay.school.nz/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51823] undefined is not an object (evaluating 'a.replace') 
JS: 2023-02-23 20:51:53 [error X 1][https://titahibay.school.nz/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.11.2:2:10991] undefined is not an object (evaluating 'this.getExperimentSelect(e).value=t') 
JS: 2023-02-23 21:30:36 [error X 3][https://titahibay.school.nz/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 

PHP: showing 11 of 11PHP: 2023-01-10 10:36:16 [warning X 16][/home/rtuxcuep/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 03:31:56 [notice X 7][/home/rtuxcuep/public_html/wp-content/plugins/elementor/includes/utils.php::791] file_get_contents(): Read of 8192 bytes failed with errno=12 Cannot allocate memory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 03:33:26 [notice X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::604] getimagesize(): Error reading from /home/rtuxcuep/public_html/wp-content/uploads/elementor/thumbs/Illustration-footer-A-lowres-1-p317z9u1vhlzqwvzoknyvt5o4pawia083y4w6fnms2.png! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 03:33:32 [notice X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::460] getimagesize(): Error reading from /home/rtuxcuep/public_html/wp-content/uploads/Illustration-footer-A-lowres-1.png! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 03:33:36 [notice X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php::460] getimagesize(): Error reading from /home/rtuxcuep/public_html/wp-content/uploads/Screen-Shot-2021-02-16-at-11.53.45-PM.png! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-17 13:39:22 [error X 39][/home/rtuxcuep/public_html/wp-content/plugins/elementor/includes/controls/base-multiple.php::65] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 19:56:09 [warning X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key "referrer" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-26 06:03:20 [warning X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-26 08:14:26 [warning X 19][/home/rtuxcuep/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::563] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-27 11:09:14 [error X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /home/rtuxcuep/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/rtuxcuep/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(23, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/rtuxcuep/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/rtuxcuep/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/rtuxcuep/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home/rtuxcuep/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home/rtuxcuep/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-03 19:59:03 [error X 1][/home/rtuxcuep/public_html/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method 'WP_REST_Controller::get_item_permissions_check' not implemented. Must be overridden in subclass. in /home/rtuxcuep/public_html/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /home/rtuxcuep/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller->get_permission_callback(Object(WP_REST_Request))
#1 /home/rtuxcuep/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route->get_permission_callback(Object(WP_REST_Request))
#2 /home/rtuxcuep/public_html/wp-includes/rest-api/class-wp-rest-server.php(1138): Elementor\Data\V2\Base\Base_Route->Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /home/rtuxcuep/public_html/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/elementor/v1/f...', Array, NULL)
#4 /home/rtuxcuep/public_html/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 /home/rtuxcuep/public_html/wp-includes/rest-api.php(410): WP_REST_Server->serve_request('/elementor/v1/f...')
#6 /home/rtuxcuep/public_html/wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))
#7 /home/rtuxcuep/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#8 /home/rtuxcuep/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#9 /home/rtuxcuep/public_html/wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)
#10 /home/rtuxcuep/public_html/wp-includes/class-wp.php(780): WP->parse_request('')
#11 /home/rtuxcuep/public_html/wp-includes/functions.php(1332): WP->main('')
#12 /home/rtuxcuep/public_html/wp-blog-header.php(16): wp()
#13 /home/rtuxcuep/public_html/index.php(17): require('/home/rtuxcuep/...')
#14 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Addon Elements: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Elementor SuperCat: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @rachaelburke-krb,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- Elementor's methods for loading the bundle.js file are meant to improve the performance. Hence the file is only loaded when needed.
- If you want the file to be loaded through your CDN, you need to configure your CDN to load the file manually, as Elementor does not give support to 3rd party software. There are numerous CDN services, and we can't apply different settings for all of them, nor can we identify when they are being used. This is the responsibility of the site's developer to properly configure their CDN. 

### ✅ What you can do to solve your issue:
- You can try to disable the "Improved Assets Loading Experiment", and see if this will help, but this means Elementor will not be able to load assets only when they are needed.
- You can configure your CDN to always fetch and server the mentioned file manually. Contact the CDN support or check their documentation to learn how you can accomplish that. 

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
