### ISSUE TITLE
🐘🐞 Bug Report: wp-cli elementor runs action in wrong installation - [ED-10138]

### ISSUE THREAD

**Issue by semidark** [elementor/elementor#21472]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When running `wp elementor replace-urls` command inside a staging environment which is run on the same server as the production, the command is executed in the wrong wordpress installation. Usually `wp-cli` executes it's commands in the installation's directory that one is currently in ( `${PWD}` )

#### 1. connect to system via SSH as user the Hoster gave me
```
$ ssh user@system.where-its-hosted.com
```
#### 2. Have two Wordpress installations on the same server. For example Production and Staging

```
$ wp find ${HOME} --format=csv
version_path,version,depth,alias
/var/www/vhosts/example.com/staging.example.com/wp-includes/version.php,6.1.1,1,
/var/www/vhosts/example.com/httpdocs/wp-includes/version.php,6.1.1,1,
```
  
The directory structure of the installations is as follows.:
```
$ tree -L 1 ${HOME}
/var/www/vhosts/example.com/ 
├── httpdocs
└── staging.example.com
└── [...]
└── [...]
└── [...]
```

#### 3. move to the staging and ensure wp-cli sees the correct installation
```
$ cd ~/staging.example.com
$ echo $PWD
/var/www/vhosts/example.com/staging.example.com
$ wp config path
/var/www/vhosts/example.com/staging.example.com/wp-config.php
```

#### 4. run wp-cli elementor inside the staging environment folder
```
$ wp elementor replace-urls https://example.com https://staging.example.com
# Authors coment: Won't replicate the output of this again since it breaks my production environment. It said something like 
Success 951 replacements made
$ wp elementor flush-css
# Authors coment: Won't replicate the output of this again since it breaks my production environment. It said something like 
Success css data flushed
```

#### 5. Replacements and flush-css gets executed in wrong Installation which is now broken
wp-cli elementor commands should never for some reason change the directory that they work on. It destroyed my customers production website! I've never seen such a behavior in any other wp-cli plugin I worked with.  

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info
As before I redacted the domain and my customers e-Mail since they are irrelevant for this bug.

 - Staging: [system-info-staging.example.com-27-02-2023.txt](https://github.com/elementor/elementor/files/10841995/system-info-staging.example.com-27-02-2023.txt)
 - Production: [system-info-example.com-27-02-2023.txt](https://github.com/elementor/elementor/files/10842048/system-info-example.com-27-02-2023.txt)

**Comment by semidark** [comment]
I tried to work around this with giving the --path argument to the command. To my supprise this also does not work and my production is messed up again.



```
# wp elementor replace-urls https://perspektivan.de https://staging.perspektivan.de --path=${PWD}
# wp elementor flush-css --path=${PWD}
```

I doublechecked again that I'm in the correct installation directory:
```
# echo ${PWD}
/var/www/vhosts/example.com/staging.example.com

# wp config path --path=${PWD}
/var/www/vhosts/example.com/staging.example.com/wp-config.php
```

What is going on here. Where does the `wp-cli elementor` command take it's working directory from

**Comment by nicholaszein** [comment]
Hello @semidark, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be thorough.

Provide the entire commands you used to perform the actions you're trying to execute, including how you connected with the current installation.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.
   
   Provide the System Info of both websites.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards

**Comment by semidark** [comment]
Hey @nicholaszein ,
thanks for the quick response. I rewrote the Bugreport to meet your specifications.

**Comment by nicholaszein** [comment]
Hello @semidark,

please provide the System Info from your client's website. This doesn't require you to change anything, just follow the instructions in [my comment above](https://github.com/elementor/elementor/issues/21472#issuecomment-1446547011) and share the information required for us to properly reproduce your issue. We can't continue without the System Info. It's THE most important part of a bug report.

As soon as you provide the missing information we can continue.

Kind regards

**Comment by semidark** [comment]
I allready uploaded the system info?

**Comment by nicholaszein** [comment]
Hi @semidark,

apologies, I must have missed the files there. Thanks for the heads up!

I will pass this along to the team so they can see if they can replicate it and find a fix as well!

Thank you very much! 🙏

**Comment by Nevoss** [comment]
Hey, Are both of those WordPress instances working against the same database? if it is, is it multisite where there are tables separately for each instance?

**Comment by semidark** [comment]
@Nevoss The instantes are on separate Databases on the same DB Server.

**Comment by Nevoss** [comment]
@semidark Thanks, Will try to mimic the environment and reproduce the issue.

**Comment by semidark** [comment]
Thank you. If I can be of any assistance, please let me know.

**Comment by KingYes** [comment]
Hello @semidark 
It's bizarre. Why do you have a problem with Elementor integration with WPCli? As you can see in this code: https://github.com/elementor/elementor/blob/69ac5fc4b866c51136dfa9cd75ca29bb39227445/modules/wp-cli/module.php#L57

We are just registering the commands class as expected. We are not adding anything to manipulate the connection with another site. I would appreciate it if you could tell me more about how to reproduce it.

Feel free to reopen this ticket if we need to do something differently.

Could you try to output the DB variables by the WPCli to ensure the staging config is changed from production?
