### ISSUE TITLE
⛔ 🐞 Bug Report: lementor gets affected with WooCommerence

### ISSUE THREAD

**Issue by kamljeet1988** [elementor/elementor#21500]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Whenever I activate any WooCommerce plugin Elementor gets affected.
![Error](https://user-images.githubusercontent.com/113114393/222209111-d9687974-1677-4df9-aec8-30de107b2eed.PNG)

### Steps to reproduce

I have updated Elementor and Elementor Pro Plugin. After updating that My website get down and got a email notification "[MySDS.ca LMS] Your Site is Experiencing a Technical Issue" and they provide me a recovery mode link. Whenever I activate any WooCommerce plugin Elementor gets affected.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.38
	PHP Version: 7.4.33
	PHP Memory Limit: 32M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 600M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://lms.mysds.ca
	Home URL: https://lms.mysds.ca
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Toronto
	Admin Email: kamljeet@mysds.ca
	Debug Mode: Inactive

== Theme ==
	Name: REIGN
	Version: 2.8.4
	Author: Wbcom Designs
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Menu Editor
		Version: 1.10.4
		Author: Janis Elsts

	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Autocomplete WooCommerce Orders
		Version: 3.0.3
		Author: QuadLayers

	Backup Duplicator & Migration - WP STAGING
		Version: 2.12.0
		Author: WP-STAGING, WPStagingBackup

	Clean WP Dashboard
		Version: 1.0
		Author: Jerod Santo

	Contact Form DB - Elementor
		Version: 1.8.0
		Author: Web Ace Tech Services

	Course Scheduler for LearnDash
		Version: 1.5.1
		Author: WooNinjas

	Custom Template for LearnDash
		Version: 1.0.5
		Author: Pratik Chaskar

	Debug This
		Version: 0.6.4
		Author: WPChill

	Design Upgrade for LearnDash
		Version: 2.12
		Author: Escape Creative

	Disable Admin Notices Individually
		Version: 1.3.2
		Author: Creative Motion <info@cm-wp.com>

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.3
		Author: Elementor.com

	Frontend Reset Password
		Version: 1.2.1
		Author: WP Enhanced

	Increase Maximum Upload File Size
		Version: 2.0.4
		Author: Imagify

	LearnDash - Exporter
		Version: 1.0
		Author: Manuel Costales

	LearnDash GravityForms Addon
		Version: 2.0.1
		Author: LearnDash

	LearnDash Licensing & Management
		Version: 1.1.6
		Author: LearnDash

	LearnDash LMS
		Version: 4.5.1.1
		Author: LearnDash

	LearnDash LMS - Course Grid
		Version: 2.0.7
		Author: LearnDash

	LearnDash LMS - Notifications
		Version: 1.6
		Author: LearnDash

	LearnDash LMS - ProPanel
		Version: 2.1.4.2
		Author: LearnDash

	LearnDash Notes
		Version: 1.4.3
		Author: SnapOrbital

	LoginWP (Formerly Peter's Login Redirect)
		Version: 3.0.7.0
		Author: LoginWP Team

	Privileged Menu
		Version: 1.8.4
		Author: <a href="http://www.fuzzguard.com.au/"><strong>Benjamin Guy</strong></a>

	Tin Canny LearnDash Reporting
		Version: 3.3.3
		Author: Uncanny Owl

	Uncanny Codes
		Version: 4.2.0.1
		Author: Uncanny Owl

	Uncanny Groups for LearnDash
		Version: 4.2
		Author: Uncanny Owl

	Uncanny Toolkit for LearnDash
		Version: 3.6.4.2
		Author: Uncanny Owl

	Uncanny Toolkit Pro for LearnDash
		Version: 3.10
		Author: Uncanny Owl

	WP Htaccess Editor
		Version: 1.71
		Author: WebFactory Ltd

	WP Rollback
		Version: 1.7.3
		Author: GiveWP.com

== Must-Use Plugins ==
	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

	WP STAGING Optimizer
		Version: 1.5.1
		Author: René Hermenau

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 342021-06-21 12:14:36 [info] elementor-pro::elementor_pro_updater Started 
2021-06-21 12:14:36 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-06-21 12:14:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.3.1',
)]
2021-06-21 12:14:36 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-06-21 12:14:36 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-06-21 12:14:36 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-06-21 12:14:36 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-06-21 12:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-06-21 12:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-06-21 12:14:37 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-06-21 12:14:37 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2021-06-21 12:14:37 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2021-06-21 12:14:37 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2021-06-21 12:14:38 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data callback needs to run again 
2021-06-21 12:14:38 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start (x2) 
2021-06-21 12:14:38 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2021-06-21 12:14:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.3.1',
)]
2023-02-23 10:17:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.5',
  'to' => '3.11.2',
)]
2023-02-23 10:17:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.1',
  'to' => '3.4.2',
)]
2023-02-27 10:42:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.11.2',
)]

PHP: showing 8 of 8PHP: 2021-03-28 20:07:24 [error X 1][/home/lmsmysds/public_html/wp-content/plugins/elementor/includes/autoloader.php::269] Allowed memory size of 134217728 bytes exhausted (tried to allocate 73728 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-28 21:36:05 [error X 1][/home/lmsmysds/public_html/wp-content/plugins/elementor/includes/frontend.php::977] Allowed memory size of 134217728 bytes exhausted (tried to allocate 69632 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-23 10:02:34 [error X 185][/home/lmsmysds/public_html/wp-content/plugins/elementor/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /home/lmsmysds/public_html/wp-content/plugins/elementor/includes/frontend.php:339
Stack trace:
#0 /home/lmsmysds/public_html/wp-content/plugins/elementor/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(41): Elementor\Frontend->__construct()
#2 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(33): WBCOM_Elementor_Global_Header_Footer->__construct()
#3 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(741): WBCOM_Elementor_Global_Header_Footer::instance()
#4 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(67): require('/home/lmsmysds/...')
#5 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(239): WbcomElementorAddons\Plugin->includes()
#6 /home/lmsmysds/public_html/wp-content/plug [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-27 10:42:33 [error X 611][/home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php:339
Stack trace:
#0 /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(41): Elementor\Frontend->__construct()
#2 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(33): WBCOM_Elementor_Global_Header_Footer->__construct()
#3 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(741): WBCOM_Elementor_Global_Header_Footer::instance()
#4 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(67): require('/home/lmsmysds/...')
#5 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(239): WbcomElementorAddons\Plugin->includes()
#6 /home/lmsmysds/public_html/wp-cont [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-28 11:19:30 [error X 22][/home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php:339
Stack trace:
#0 /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(41): Elementor\Frontend->__construct()
#2 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(33): WBCOM_Elementor_Global_Header_Footer->__construct()
#3 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(741): WBCOM_Elementor_Global_Header_Footer::instance()
#4 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(67): require('/home/lmsmysds/...')
#5 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(239): WbcomElementorAddons\Plugin->includes()
#6 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(59): WbcomElementorAddons\Plugin->__construct()
#7 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(245): WbcomElementorAddons\Plugin::instance()
#8 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/wbcom-essential.php(55): require('/home/lmsmysds/...')
#9 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(308): wbcom_elementor_addons_load_plugin('')
#10 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#11 /home/lmsmysds/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/lmsmysds/public_html/wp-settings.php(480): do_action('plugins_loaded')
#13 /home/lmsmysds/public_html/wp-config.php(93): require_once('/home/lmsmysds/...')
#14 /home/lmsmysds/public_html/wp-load.php(50): require_once('/home/lmsmysds/...')
#15 /home/lmsmysds/public_html/wp-blog-header.php(13): require_once('/home/lmsmysds/...')
#16 /home/lmsmysds/public_html/index.php(17): require('/home/lmsmysds/...')
#17 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-28 11:19:48 [error X 10][/home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php:339
Stack trace:
#0 /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(41): Elementor\Frontend->__construct()
#2 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(33): WBCOM_Elementor_Global_Header_Footer->__construct()
#3 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(741): WBCOM_Elementor_Global_Header_Footer::instance()
#4 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(67): require('/home/lmsmysds/...')
#5 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(239): WbcomElementorAddons\Plugin->includes()
#6 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(59): WbcomElementorAddons\Plugin->__construct()
#7 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(245): WbcomElementorAddons\Plugin::instance()
#8 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/wbcom-essential.php(55): require('/home/lmsmysds/...')
#9 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(308): wbcom_elementor_addons_load_plugin('')
#10 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#11 /home/lmsmysds/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/lmsmysds/public_html/wp-settings.php(480): do_action('plugins_loaded')
#13 /home/lmsmysds/public_html/wp-config.php(93): require_once('/home/lmsmysds/...')
#14 /home/lmsmysds/public_html/wp-load.php(50): require_once('/home/lmsmysds/...')
#15 /home/lmsmysds/public_html/wp-cron.php(46): require_once('/home/lmsmysds/...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-28 11:20:36 [error X 3][/home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php:339
Stack trace:
#0 /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(41): Elementor\Frontend->__construct()
#2 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(33): WBCOM_Elementor_Global_Header_Footer->__construct()
#3 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(741): WBCOM_Elementor_Global_Header_Footer::instance()
#4 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(67): require('/home/lmsmysds/...')
#5 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(239): WbcomElementorAddons\Plugin->includes()
#6 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(59): WbcomElementorAddons\Plugin->__construct()
#7 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(245): WbcomElementorAddons\Plugin::instance()
#8 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/wbcom-essential.php(55): require('/home/lmsmysds/...')
#9 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(308): wbcom_elementor_addons_load_plugin('')
#10 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#11 /home/lmsmysds/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/lmsmysds/public_html/wp-settings.php(480): do_action('plugins_loaded')
#13 /home/lmsmysds/public_html/wp-config.php(93): require_once('/home/lmsmysds/...')
#14 /home/lmsmysds/public_html/wp-load.php(50): require_once('/home/lmsmysds/...')
#15 /home/lmsmysds/public_html/xmlrpc.php(31): require_once('/home/lmsmysds/...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-28 11:25:43 [error X 2][/home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php::339] Uncaught Error: Call to a member function is_feature_active() on null in /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php:339
Stack trace:
#0 /home/lmsmysds/public_html/wp-content/plugins/elementor_bak/includes/frontend.php(176): Elementor\Frontend->init_swiper_settings()
#1 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(41): Elementor\Frontend->__construct()
#2 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(33): WBCOM_Elementor_Global_Header_Footer->__construct()
#3 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/includes/global-header-footer.php(741): WBCOM_Elementor_Global_Header_Footer::instance()
#4 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(67): require('/home/lmsmysds/...')
#5 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(239): WbcomElementorAddons\Plugin->includes()
#6 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(59): WbcomElementorAddons\Plugin->__construct()
#7 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/plugin.php(245): WbcomElementorAddons\Plugin::instance()
#8 /home/lmsmysds/public_html/wp-content/plugins/wbcom-essential/wbcom-essential.php(55): require('/home/lmsmysds/...')
#9 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(308): wbcom_elementor_addons_load_plugin('')
#10 /home/lmsmysds/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#11 /home/lmsmysds/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/lmsmysds/public_html/wp-settings.php(480): do_action('plugins_loaded')
#13 /home/lmsmysds/public_html/wp-config.php(93): require_once('/home/lmsmysds/...')
#14 /home/lmsmysds/public_html/wp-load.php(50): require_once('/home/lmsmysds/...')
#15 /home/lmsmysds/public_html/wp-login.php(12): require('/home/lmsmysds/...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Contact Form DB - Elementor: Compatibility not specified
	Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello there,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is not an Elementor bug. We have multiple testing sites working flawlessly with the latest version of WooCommerce. 

### ✅ What you can do to solve your issue:
- Your issue is related to your website's resources. Contact your hosting provider and ask them to help you with increasing the memory limit to at least 512M, but if possible you should increase it to 1Gb since WooCommerce is very resource intensive. 
- Check Elementor's System Requirements and make sure your website is compatible with them: 
https://elementor.com/help/requirements

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
