### ISSUE TITLE
🔗 🚀 Feature Request: Horizantal scroll menu and Table widgets please!! (Duplicate of #1342)

### ISSUE THREAD

**Issue by radhamantena** [elementor/elementor#2150]
I would love to see Horizontal Scroll menu and Table widgets in elementor....

Any plans to  launch them in the near future?

Radha

**Comment by bainternet** [comment]
I merged this issue with  #1342 , which is about the same subject (table widget) so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

As for horizontal scroll menu, we will look into it in the future if we see a large demand for it.

Thanks for your suggestions!
