### ISSUE TITLE
⛔ 🐞 Bug Report: Swiper.js keeps pausing on mobile 

### ISSUE THREAD

**Issue by aegli84** [elementor/elementor#21527]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm using the Image Carousel widget for which I have added the following CSS code to make it loop infinitely:

selector .elementor-image-carousel {
      -webkit-transition-timing-function: linear !important;
      -moz-transition-timing-function: linear !important;
      -o-transition-timing-function: linear !important;
     transition-timing-function: linear !important; 
} 

In the mobile preview in the editor, it works as it should.
It used to work just fine until recently and I'm wondering if the issue is caused by the latest updates. 

It works fine on desktop.

What is the solution here?

### Steps to reproduce

Add this code: 

1. Add the Image Carousel widget
2. Add the following code into the custom CSS box:
selector .elementor-image-carousel {
      -webkit-transition-timing-function: linear !important;
      -moz-transition-timing-function: linear !important;
      -o-transition-timing-function: linear !important;
     transition-timing-function: linear !important; 
} 
3. Preview 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.11
	PHP Version: 8.0.26
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://egliandreastudios.com
	Home URL: https://egliandreastudios.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hello@egliandreastudios.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.2.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.3
		Author: Elementor.com

	Happy Elementor Addons
		Version: 3.8.2
		Author: weDevs

	Hostinger
		Version: 1.0.2
		Author: Hostinger

	LiteSpeed Cache
		Version: 5.3.3
		Author: LiteSpeed Technologies

	OMGF
		Version: 5.5.5.1
		Author: Daan from Daan.dev

	PhastPress
		Version: 2.10
		Author: Albert Peschar

	Rank Math SEO
		Version: 1.0.109
		Author: Rank Math

	Unlimited Elements for Elementor
		Version: 1.5.55
		Author: Unlimited Elements

	WP Statistics
		Version: 14.0.1
		Author: VeronaLabs

== Must-Use Plugins ==
	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elements Usage ==
	
	container : 8
		button : 4
		container : 25
		divider : 6
		heading : 15
		image : 3
		nested-tabs : 1
		text-editor : 3
		video : 1
	footer : 1
		button : 1
		container : 11
		divider : 1
		heading : 5
		nav-menu : 2
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 1
		container : 1
		html : 1
		nav-menu : 1
	popup : 2
		container : 3
		html : 1
		icon : 1
		nav-menu : 1
	section : 22
		button : 6
		container : 1
		divider : 6
		heading : 19
		html : 2
		image : 14
		image-carousel : 2
		nav-menu : 1
		social-icons : 1
		text-editor : 20
		video : 1
	widget : 0
		button : 7
		heading : 1
		social-icons : 1
	wp-post : 0
		button : 3
		container : 17
		divider : 3
		heading : 6
		image : 3
		image-carousel : 2
		text-editor : 2
	wp-page : 10
		button : 12
		container : 100
		divider : 21
		form : 1
		heading : 49
		icon : 6
		image : 20
		text-editor : 26
		toggle : 1
		video : 1
	single-page : 1
		button : 1
		container : 17
		divider : 2
		heading : 6
		image : 4
		text-editor : 5
	error-404 : 1
		heading : 2
		icon : 1
		image : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 352023-02-16 20:07:54 [info] elementor::elementor_updater Started 
2023-02-16 20:07:54 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-16 20:07:54 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-16 20:07:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-16 20:07:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-16 20:08:10 [info] elementor-pro::elementor_pro_updater Started 
2023-02-16 20:08:10 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-16 20:08:10 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-16 20:08:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-16 20:08:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-02-28 15:14:44 [info] elementor::elementor_updater Started 
2023-02-28 15:14:44 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-28 15:14:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-28 15:14:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-28 15:14:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-28 15:54:36 [info] elementor-pro::elementor_pro_updater Started 
2023-02-28 15:54:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-28 15:54:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-28 15:54:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.3',
)]
2023-02-28 15:54:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.3',
)]

JS: showing 4 of 4JS: 2023-01-29 16:36:40 [error X 36][https://egliandreastudios.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.10.1:2:52931] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2023-02-08 17:17:29 [error X 1][https://egliandreastudios.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.2:3:661609] this.model.isValidChild is not a function 
JS: 2023-02-09 15:11:13 [error X 1][https://egliandreastudios.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.10.3:1:1162] Failed to execute &#039;getComputedStyle&#039; on &#039;Window&#039;: parameter 1 is not of type &#039;Element&#039;. 
JS: 2023-03-02 20:23:05 [error X 6][https://egliandreastudios.com/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&amp;loadchunk_1=hooks&amp;ver=6.1.1:4:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 

PHP: showing 3 of 3PHP: 2023-02-09 13:12:35 [warning X 22][/home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-02-17 06:37:44 [warning X 3][/home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/core/utils.php::373] Undefined array key &quot;name&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-18 06:54:38 [error X 3][/home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php::261] Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php:261
Stack trace:
#0 /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/modules/forms/fields/upload.php(261): count()
#1 /home/u270122318/domains/egliandreastudios.com/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\Forms\Fields\Upload-&gt;validation()
#2 /home/u270122318/domains/egliandreastudios.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#3 /home/u270122318/domains/egliandreastudios.com/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#4 /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php(64): do_action()
#5 /home/u270122318/domains/egliandreastudios.com/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php(123): ElementorPro\Modules\Forms\Classes\Form_Record-&gt;validate()
#6 /home/u270122318/domains/egliandreastudios.com/public_html/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\Forms\Classes\Ajax_Handler-&gt;ajax_send_form()
#7 /home/u270122318/domains/egliandreastudios.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#8 /home/u270122318/domains/egliandreastudios.com/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#9 /home/u270122318/domains/egliandreastudios.com/public_html/wp-admin/admin-ajax.php(203): do_action()
#10 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Happy Elementor Addons: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @aegli84,

Make sure to set the following options:
![image](https://user-images.githubusercontent.com/113993460/229271153-261883e4-063f-49ff-b841-468b9e6d62b5.png)

Adjust the Animation Speed according to your needs.

But most importantly: **Clear the Cache**. You are using the Litespeed cache, which can be very persistent. 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
