### ISSUE TITLE
✅ 🔗 🐞 Bug Report: Elementor break points BUG: When enabled, Flexbox container responsive adjustments per device don't display correctly. (Duplicate of #17020) - [ED-7973]

### ISSUE THREAD

**Issue by Applabprojects** [elementor/elementor#21531]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When additional break points is enabled, My responsiveness per device do not display correctly on the live version. It only displays correctly in the editor. When disabled all is fine.

### Steps to reproduce

1) Enable Additional breakpoints
2) Create popup
2) Make grid with container and elements inside
3) Set responsive adjustment per device for popup
4) Preview is wrong.
5) Disabled additional breakpoints and popup displays correctly.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-atlasrent.dns-systems.net-03-03-2023.txt](https://github.com/elementor/elementor/files/10883065/system-info-atlasrent.dns-systems.net-03-03-2023.txt)

**Comment by Mugseem** [comment]
I'm having a similar issue. Active additional custom breakpoints feature breaks my archive and post templates. When inspecting element in DevTools it inherits styles from tablet, but in the editor mode everything shows correctly. Regenerating CSS doesn't always fix the issue. Disabling custom breakpoints fixes everything.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12*! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
