### ISSUE TITLE
⛔ 🐞 Bug Report: The header menu stays "grouped", only the "more" button appears.

### ISSUE THREAD

**Issue by Newuzar** [elementor/elementor#21540]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

the header menu stays "grouped", only the "more" button appears.
Sometimes it shows the list of header items, but most of the times it show only ”more” button.
Why is that?

### Steps to reproduce

When I reload the site, the header menu is not show. It only show ”more”
![Screenshot from 2023-03-04 21-19-31](https://user-images.githubusercontent.com/91006219/222924840-9988f15d-da55-4956-a7a4-abc9ee337fb9.png)
( I also lost header's design, the second line of it, and the footer. I don't know what happened. but this problem with the "more" button instead of whole menu, was before).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-inlumina.ro-04-03-2023.txt](https://github.com/elementor/elementor/files/10889457/system-info-inlumina.ro-04-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello @Newuzar,

Thanks for contacting us! 🙏 

This is more of a support question, not something we can answer here.

Check if you have selected the correct menu in the Nav Menu widget.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
