### ISSUE TITLE
⛔ 🐞 Bug Report: header menu is not unrolled

### ISSUE THREAD

**Issue by Newuzar** [elementor/elementor#21587]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Header menu is NOT unrolled most of the time. I don t know what makes it so.
It shows only the ”more” button. But there is enough space to display it fully
![Screenshot from 2023-03-07 23-18-27](https://user-images.githubusercontent.com/91006219/223556371-058d0938-d10c-48f3-b449-3165e1c21efb.png)

### Steps to reproduce

I just don t know what makes the header menu compressed into a single button-”more”.
is a random thing.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-inlumina.ro-07-03-2023.txt](https://github.com/elementor/elementor/files/10914091/system-info-inlumina.ro-07-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello again @Newuzar,

Thanks for contacting us! 🙏 

This is more of a support question, not something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
