### ISSUE TITLE
⛔ 📚 Developer-API Question: Group Control (Background) in Repeater -> Tabs Not In Group

### ISSUE THREAD

**Issue by FauzanEdris** [elementor/elementor#21598]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Can Anyone confirm the bug when have Group Control (Ex: Background) in Repeater -> Tabs..

-Repeater
--tabs
---background

<img width="303" alt="Screen Shot 2023-03-09 at 17 47 34" src="https://user-images.githubusercontent.com/30016486/223985105-59c94548-3abc-4fd9-a60a-e937bf8f19b9.png">

### Steps to reproduce

create background option in widget like the description guide, please see the screenshot

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

**Comment by nicholaszein** [comment]
Hello @FauzanEdris, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue following these guidelines. 😉 

Best regards,

Nick
