### ISSUE TITLE
⛔ 🐞 Bug Report: When using "em" on Global Button Settings font-size should increase or decrease uniformly on all button sizes

### ISSUE THREAD

**Issue by brittaweller** [elementor/elementor#21599]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Under Global Settings for buttons I expected the font-size to increase uniformly on all the button sizes when I entered 1.5em.

But instead ALL sizes have now the size of 1.5rem (24px). It should still be different font-sizes for different button sizes.

### Steps to reproduce

1) Place buttons with different button sizes on a page
2) Go to Website Settings -> Buttons 
3) change Typography to  1.5em
4) The font-sizes of the buttons which were different first now all have the SAME font-size.

<img width="417" alt="Bildschirmfoto 2023-03-09 um 15 47 03" src="https://user-images.githubusercontent.com/24314640/223983969-4c29dc02-5d0e-46f4-b2a4-8e7b1102d3e3.png">

<img width="1207" alt="Bildschirmfoto 2023-03-09 um 15 46 35" src="https://user-images.githubusercontent.com/24314640/223984019-5a112587-173a-462f-a8e7-a99f0757137d.png">

A solution would be if you place the global font-size on .elementor-button-content-wrapper instead of overwriting the default font-size on .elementor-button.

See:
<img width="1005" alt="Bildschirmfoto 2023-03-09 um 15 45 13" src="https://user-images.githubusercontent.com/24314640/223984746-5c162880-05be-4841-9348-f3a21b2a481a.png">

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
          Operating System: Darwin
	Software: Apache/2.4.53 (Unix) OpenSSL/1.1.1n PHP/8.0.17
	MySQL version: Homebrew v10.7.3
	PHP Version: 8.0.17
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

	                   == WordPress Environment ==
	                                Version: 6.1.1
	Site URL: https://dev.template.test/stripe/sovd-inklusionslauf
	Home URL: https://dev.template.test/stripe/sovd-inklusionslauf
	WP Multisite: Yes
	Max Upload Size: 63 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: info@steeeg.de
	Debug Mode: Active

	            == Theme ==
	Name: Stripe
	Version: 0.9.3
	Author: Steeeg GmbH
	Child Theme: No

	             == User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0

	                                                                                   == Active Plugins ==
	                                                                                             Elementor
		Version: 3.11.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.4
		Author: Elementor.com

	WP Migrate
		Version: 2.6.1
		Author: WP Engine

		           == Features ==
	Custom Fonts: 1
	Custom Icons: 0

	              == Integrations ==
	

== Elementor Experiments ==
             Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive
	Mega Menu: Inactive by default

== Log ==

   PHP: showing 5 of 5PHP: 2023-03-06 11:40:35 [notice X 1][/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/upgrade/manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-06 11:45:58 [notice X 6][/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
	'trace' => '
#0: /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => '/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-03-06 12:04:11 [notice X 1][/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
	'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 10:14:59 [notice X 3][/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-09 10:00:15 [error X 1][/Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/documents/tabs/theme-style-typography.php::194] Uncaught ArgumentCountError: Too few arguments to function Elementor\Core\Kits\Documents\Tabs\Theme_Style_Typography::add_element_controls(), 2 passed in /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/documents/tabs/theme-style-typography.php on line 184 and exactly 3 expected in /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/documents/tabs/theme-style-typography.php:194
Stack trace:
#0 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/documents/tabs/theme-style-typography.php(184): Elementor\Core\Kits\Documents\Tabs\Theme_Style_Typography->add_element_controls('H1', 'h1')
#1 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/documents/tabs/tab-base.php(43): Elementor\Core\Kits\Documents\Tabs\Theme_Style_Typography->register_tab_controls()
#2 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/documents/kit.php(158): Elementor\Core\Kits\Documents\Tabs\Tab_Base->register_controls()
#3 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/includes/base/controls-stack.php(2329): Elementor\Core\Kits\Documents\Kit->register_controls()
#4 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/includes/base/controls-stack.php(496): Elementor\Controls_Stack->init_controls()
#5 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Controls_Stack->get_stack()
#6 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/includes/base/controls-stack.php(2416): Elementor\Controls_Stack->get_controls()
#7 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/includes/base/controls-stack.php(1109): Elementor\Controls_Stack->sanitize_settings(Array)
#8 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/includes/base/controls-stack.php(2163): Elementor\Controls_Stack->get_data('settings')
#9 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings()
#10 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#11 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/core/kits/manager.php(117): Elementor\Core\Base\Base_Object->get_settings('default_page_te...')
#12 /Websites/dev.template.test/htdocs/stripe/wp-content/plugins/elementor/modules/page-templates/module.php(92): Elementor\Core\Kits\Manager->get_current_settings('default_page_te...')
#13 /Websites/dev.template.test/htdocs/stripe/wp-includes/class-wp-hook.php(308): Elementor\Modules\PageTemplates\Module->template_include('/W...')
#14 /Websites/dev.template.test/htdocs/stripe/wp-includes/plugin.php(205): WP_Hook->apply_filters('/W...', Array)
#15 /Websites/dev.template.test/htdocs/stripe/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/W...')
#16 /Websites/dev.template.test/htdocs/stripe/wp-blog-header.php(19): require_once('/W...')
#17 /Websites/dev.template.test/htdocs/stripe/index.php(17): require('/W...')
#18 {main}
  thrown [array (
	  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
  )]

Log: showing 16 of 162023-03-07 10:11:44 [info] elementor-pro::elementor_pro_updater Started 
2023-03-07 10:11:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-07 10:11:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-07 10:11:44 [info] Elementor data updater process has been completed. [array (
	'plugin' => 'Elementor Pro',
	'from' => '3.10.3',
	'to' => '3.11.3',
)]
2023-03-07 10:11:44 [info] Elementor data updater process has been queued. [array (
	'plugin' => 'Elementor Pro',
	'from' => '3.10.3',
	'to' => '3.11.3',
)]
2023-03-08 03:33:16 [info] elementor::elementor_updater Started 
2023-03-08 03:33:16 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-08 03:33:16 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-08 03:33:16 [info] Elementor data updater process has been completed. [array (
	'plugin' => 'Elementor',
	'from' => '3.11.2',
	'to' => '3.11.3',
)]
2023-03-08 03:33:16 [info] Elementor data updater process has been queued. [array (
	'plugin' => 'Elementor',
	'from' => '3.11.2',
	'to' => '3.11.3',
)]
2023-03-08 07:57:18 [info] elementor-pro::elementor_pro_updater Started 
2023-03-08 07:57:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-08 07:57:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-08 07:57:18 [info] Elementor data updater process has been completed. [array (
	'plugin' => 'Elementor Pro',
	'from' => '3.11.3',
	'to' => '3.11.4',
)]
2023-03-08 07:57:18 [info] Elementor data updater process has been queued. [array (
	'plugin' => 'Elementor Pro',
	'from' => '3.11.3',
	'to' => '3.11.4',
)]
2023-03-08 07:57:19 [info] Elementor data updater process has been queued. [array (
	'plugin' => 'Elementor Pro',
	'from' => '3.11.3',
	'to' => '3.11.4',
)]

JS: showing 1 of 1JS: 2023-03-08 08:15:27 [error X 1][https://dev.template.test/stripe/sovd-inklusionslauf/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:592136] Cannot read properties of null (reading 'id') 

== Elementor - Compatibility Tag ==

                             Elementor Pro: Compatibility not specified

                                                              == Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @brittaweller,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is the expected behavior, especially if you choose to use `em` units. The size of the font will apply to all sizes of the button.

### ✅ What you can do to solve your issue:
- You can submit a feature request, and we will consider it if it has enough demand from users.

### 👍 For now, that's all we can help with. 

Kind regards
