### ISSUE TITLE
🔗 🐞 Bug Report: Bug Sticky Text on column only on Chrome and in live (Merged with #21612)

### ISSUE THREAD

**Issue by Mascalalox** [elementor/elementor#21610]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In this loom, you can see the error, and how it works in the browser microsoft edge, but how it doesnt work on chrome.
I also create a new section to show how i found the bug.

I did the same thing in other website and still without working

https://www.loom.com/share/f4de30a488274b188df7f12d12e7ac4b

### Steps to reproduce

1) Create a new section with 2 columns 50/50
2) In one column add 4/5 images to scroll and in the other column add text with sticky at top and stay in column.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Source distribution v8.0.30 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>
<html>
<body>

Version: | 6.1.1 |  
-- | -- | --
Site URL: |  |  
Home URL: |  |  
WP Multisite: | No |  
Max Upload Size: | 256 MB |  
Memory limit: | 512M |  
Max Memory limit: | 512M |  
Permalink Structure: | /%postname%/ |  
Language: | es |  
Timezone: | 0 |  
Admin Email: |  |  
Debug Mode: | Inactive

</body>
</html>

<html>
<body>

Active Plugins |   |  
-- | -- | --
Elementor - 3.11.3 | By Elementor.com |  
Elementor Pro - 3.11.4 | By Elementor.com

</body>
</html>

**Comment by nicholaszein** [comment]
Hello @Mascalalox! 

Thank you for submitting your issue! 🙏 

We are aware that there is an issue with the latest Google Chrome version, and we are investigating it. 

There is another issue with the same subject, and I'll be merging this issue with that one.

Please continue the conversation there: #21612

Best regards
