### ISSUE TITLE
⛔ 🐞 Bug Report: Updating issues

### ISSUE THREAD

**Issue by sanj33valtrazz** [elementor/elementor#21624]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I tried to update after editing the web page, the image carousel section is not reflecting the changes.

### Steps to reproduce

1) Creating image carousel section with four images.
2) After sometimes I replaced the images in Image carousel and updated the changes.
3) But still the old images didn't changed.
4) Even after Updated so many times noting changed.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://alttraz.org
	Home URL: https://alttraz.org
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: rejeesh.altra@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.0.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Jetpack
		Version: 11.9
		Author: Automattic

	Site Kit by Google
		Version: 1.95.0
		Author: Google

	Tidio Chat
		Version: 6.0.3
		Author: Tidio Ltd.

	Ultimate Member
		Version: 2.5.4
		Author: Ultimate Member

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.12
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Chat App
		Version: 3.2.1
		Author: NinjaTeam

	WPForms Lite
		Version: 1.8.0.2
		Author: WPForms

	WP Job Openings
		Version: 3.3.3
		Author: AWSM Innovations

	Yoast SEO
		Version: 20.2.1
		Author: Team Yoast

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Lazy Load Background Images: Inactive by default

== Log ==
	
Log: showing 15 of 152023-01-12 12:31:33 [info] elementor::elementor_updater Started 
2023-01-12 12:31:33 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-12 12:31:33 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-12 12:31:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0',
)]
2023-01-12 12:31:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0',
)]
2023-01-12 12:31:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0',
)]
2023-03-08 11:42:31 [info] elementor::elementor_updater Started 
2023-03-08 11:42:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-08 11:42:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-08 11:42:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.3',
)]
2023-03-11 12:52:27 [info] elementor::elementor_updater Started 
2023-03-11 12:52:27 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-11 12:52:27 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-11 12:52:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.13.0-dev1',
)]
2023-03-11 12:52:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.13.0-dev1',
)]

JS: showing 5 of 5JS: 2023-01-31 06:57:37 [error X 4][https://alttraz.org/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] this[binder] is not a function 
JS: 2023-03-08 06:39:48 [error X 6096][https://alttraz.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading 'clone') 
JS: 2023-03-08 06:39:50 [error X 173][https://alttraz.org/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading 'changestop') 
JS: 2023-03-10 08:35:25 [error X 1][https://alttraz.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:791161] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-03-10 11:22:10 [error X 8][https://alttraz.org/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 

PHP: showing 2 of 2PHP: 2023-03-08 12:15:04 [notice X 2][/home2/alttrazo/public_html/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 16:39:57 [notice X 2][/home2/alttrazo/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @sanj33valtrazz,

Thanks for contacting us! 🙏 

This is more of a support question, not something we can answer here.

Follow the documentation to troubleshoot your issue:

https://elementor.com/help/cant-edit-with-elementor/

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
