### ISSUE TITLE
Animation Bug with Chrome version 111 !

### ISSUE THREAD

**Issue by nimaaminz** [elementor/elementor#21643]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello 
The chrome version 111 release about 9 march and I found that this version has bug with elementor pro animation scroll effects  
for example look at this url on elementor official website : 
https://elementor.com/products/hosting-website-builder/  
when you open this and scrolling to section that has green background and also contain a header say : " A Complete Solution For Your WordPress Website " 
you will see a world animation on scroll , in chrome  < version 111 when you scroll on this section and the option changes , the world animate will fade into page with increase opacity (by elementor pro ) but in chrome 111 it doesnt work !! 
and the world wont fade anymore !

### Steps to reproduce

update chrome to latest version ( v111  - 9 march 2023) 
then open a website thats build with elementor pro and has scroll effects animation  or visit https://elementor.com/products/hosting-website-builder/   
then you will see that the motions effects doesnt work !!

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

anything

**Comment by 79ho3ein** [comment]
Hi @nimaaminz 

lease update Elementor to the latest version. Are you still experiencing this bug?

**Comment by berkmh** [comment]
> Hi @nimaaminz
> 
> lease update Elementor to the latest version. Are you still experiencing this bug?

i updated last night and still getting bug. (cleared all caches and on incognito)

**Comment by nimaaminz** [comment]
@berkmh i found out that elementor-pro frontend.min.js wont add and download , and all the motions functions exist on this script , i dont know yet why the script doesn't add to page but i think this is a bug with backend , may be elementor check browser or something then add frontend.min.js to page and now it has conflict with chrome v111 or something else ...

**Comment by nimaaminz** [comment]
There is no bug for me now with the new elementor pro update ! 
version 3.11.6
