### ISSUE TITLE
Chrome scrolling not working

### ISSUE THREAD

**Issue by websitestudios** [elementor/elementor#21658]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My websites no longer scroll on chrome. I use elementor and after my last update, all my websites have stopped scrolling. HUGE problem. I read about the sticky header not working on chrome and I do use sticky header. How can I fix this immediately?? I am already using all the additonal custom breakpoints, they are all configured. But my websites still do not scroll on Chrome! Please help someone.

### Steps to reproduce

Same known issues.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-websitestudios.com-14-03-2023.txt](https://github.com/elementor/elementor/files/10974893/system-info-websitestudios.com-14-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello @websitestudios,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here. 

It's likely your issue might be related to cache or a conflicting plugin. Not something we can help you with here.

Try to update Elementor to the latest versions, and also clear your cache. If your problem persist please contact Elementor support.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
