### ISSUE TITLE
🐘 🐞 Bug Report: PHP 8.1.16 Deprecated:  strpos() in /elementor-pro/modules/loop-builder/module.php:200

### ISSUE THREAD

**Issue by EdwardBlack** [elementor/elementor#21655]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey,

just a quick php 8.1 depreciation bug/improvement. Hope it helps to improve elementor and make it 8.1 compatible.
```
PHP: 2023-03-13 20:21:53 [notice X 2365][/home/nginx/domains/domain.com/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```

```
PHP: 2023-03-14 16:03:21 [notice X 1][/home/nginx/domains/domain.com/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```

### Steps to reproduce

1) Install PHP Version: 8.1.16
2) Install Elementor + Pro newest version
3) Install Hello Theme

= php deprecated notice

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Operating System: | Linux |  
-- | -- | --
Software: | nginx/1.23.3 |  
MySQL version: | MariaDB Server v10.3.38 |  
PHP Version: | 8.1.16 |  
PHP Memory Limit: | 2048M |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 2048M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right

WP-Version: | 6.1.1
-- | --

Theme |  
-- | --
Name: | Hello Elementor
Version: | 2.6.1

**Comment by joaodath** [comment]
I get a very similar error and it breaks the loop builder. It used to work some versions ago (I'm sorry I don't really remember the version it was working on, but it was the latest version on black Friday of 2022) on PHP 8.1 but now it refuses to display anything created with Loop Builder. I'd love to hear some feedback on that!

**Comment by mb-joakim** [comment]
Yeah, i got this issue aswell after recent update of Elementor, Elementor Pro and Hello Elementor Theme with PHP 8.1, it completely shutdown the entire site.

"A critical error has occurred on the site."

I tried a check for `$elementor_library`, as php doc recommended if the value is always returning null, but didn't help.

`private function is_editing_existing_loop_item() {
    //phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Nonce verification is not required.
    $elementor_library = Utils::_unstable_get_super_global_value( $_GET, 'elementor_library' );
    if ( isset( $elementor_library ) ) {
        return strpos( $elementor_library, 'elementor-' . static::TEMPLATE_LIBRARY_TYPE_SLUG ) !== false;
    }
    return false;
}`

**Comment by LukeMatPyt** [comment]
Better fix this crap already Elementor Team, because in 24h I am going to chargeback that crap and buy Divi.
The same issue here:
PHP 8.2, 512M 
Nginx 

Issue comes when I install Elementor Pro with activated Elementor with Hello Theme

**Comment by MegaphoneJon** [comment]
I'm not advocating this as a permanent fix, but since I have a site to run and so do many of you, this patch will provide you with PHP7-equivalent functionality (where an implicit bug still exists, but not nearly so serious of one).

Note this is against v3.12.1 so your exact fix might vary slightly.

```diff
diff --git a/wp-content/plugins/elementor-pro/modules/loop-builder/module.php b/wp-content/plugins/elementor-pro/modules/loop-builder/module.php
index 353a964a..9b3577df 100644
--- a/wp-content/plugins/elementor-pro/modules/loop-builder/module.php
+++ b/wp-content/plugins/elementor-pro/modules/loop-builder/module.php
@@ -200,7 +200,7 @@ class Module extends Module_Base {
 
        private function is_editing_existing_loop_item() {
                //phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Nonce verification is not required.
-               $elementor_library = Utils::_unstable_get_super_global_value( $_GET, 'elementor_library' );
+               $elementor_library = Utils::_unstable_get_super_global_value( $_GET, 'elementor_library' ) ?? '';
                return strpos( $elementor_library, 'elementor-' . static::TEMPLATE_LIBRARY_TYPE_SLUG ) !== false;
        }
```

**Comment by joaodath** [comment]
Hey @nicholaszein is there any update on when we're gonna see a fix for this? Maybe on Elementor 3.13?

**Comment by nicholaszein** [comment]
> Hey @nicholaszein is there any update on when we're gonna see a fix for this? Maybe on Elementor 3.13? 

Hi @joaodath,

This issue is still being investigated, as it affects a lot of components. It is likely a fix will be released only on a future patch (not in 3.13 for now).

We recommend rolling back to php 8.0 or 7.4.

I will update this issue when we have more info.

**Comment by joaodath** [comment]
> > Hey @nicholaszein is there any update on when we're gonna see a fix for this? Maybe on Elementor 3.13?
> 
> Hi @joaodath,
> 
> This issue is still being investigated, as it affects a lot of components. It is likely a fix will be released only on a future patch (not in 3.13 for now).
> 
> We recommend rolling back to php 8.0 or 7.4.
> 
> I will update this issue when we have more info.

I rolled back to PHP8.0 and the issue keeps happening. The weirdest part is that I have two identical websites, one for staging and one for production. They share the exact same PHP version and env and the production website is a clean install of WordPress + the same theme (Hello + a variant of Hello Child created by me) + import of website kit (using the elementor tool) from the staging website. Staging looks good, but the production is broken. The loop builder breaks every page it is used, but if we create a page without the loop builder, the page will display correctly.

**Comment by EdwardBlack** [comment]
> We recommend rolling back to php 8.0 or 7.4.

That can't be the solution 🤬

PHP 7.4 End of life'ed somewhere last year and is not even getting security fixes anymore.
PHP 8.0 support ended on 26 Nov 2022, so 4 months ago and security fixes also only going on for 7 more months.

This is nothing that came out of the blue. If I were a competitor, right now, I would advertise with something like 'that Elementor pro is not conforming with any current PHP version'...

**Comment by joaodath** [comment]
> > > Hey @nicholaszein is there any update on when we're gonna see a fix for this? Maybe on Elementor 3.13?
>
>  The loop builder breaks every page it is used, but if we create a page without the loop builder, the page will display correctly.

Here's a copy of the stack trace for the error I'm seeing: 

```
Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::print_content() in wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php:250
Stack trace:
#0 wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(873): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#1 wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(87): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#2 wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#3 wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#4 wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#5 wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content()
#6 wp-content/plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#7 wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#8 wp-content/plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#9 wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#10 wp-content/plugins/elementor/core/base/document.php(1680): Elementor\Element_Base->print_element()
#11 wp-content/plugins/elementor/core/base/document.php(1106): Elementor\Core\Base\Document->print_elements()
#12 wp-content/plugins/elementor/includes/frontend.php(1179): Elementor\Core\Base\Document->print_elements_with_wrapper()
#13 wp-content/plugins/elementor/includes/frontend.php(1074): Elementor\Frontend->get_builder_content()
#14 wp-includes/class-wp-hook.php(308): Elementor\Frontend->apply_builder_in_content()
#15 wp-includes/plugin.php(205): WP_Hook->apply_filters()
#16 wp-includes/post-template.php(255): apply_filters()
#17 wp-content/plugins/elementor/modules/page-templates/module.php(190): the_content()
#18 [internal function]: Elementor\Modules\PageTemplates\Module->print_callback()
#19 wp-content/plugins/elementor/modules/page-templates/module.php(207): call_user_func()
#20 wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(19): Elementor\Modules\PageTemplates\Module->print_content()
#21 wp-includes/template-loader.php(106): include('...')
#22 wp-blog-header.php(19): require_once('...')
#23 index.php(17): require('...')
#24 {main}
``` 

Server details:

```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 22.04 v10.6.12 (MariaDB)
	PHP Version: 8.0.28
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: hidden for privacy
	Home URL: hidden for privacy
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hidden for privacy
	Debug Mode: Active

== Theme ==
	Name: Child Theme (Hello Elementor Child)
	Version: 2023.04
	Author: João Rodrigues (@joaodath)
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48

== Active Plugins ==
	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	Gravity Forms
		Version: 2.7.4
		Author: Gravity Forms

	Post SMTP
		Version: 2.4.7
		Author: Post SMTP

	Safe SVG
		Version: 2.1.1
		Author: 10up

	WebP Express
		Version: 0.25.6
		Author: Bjørn Rosell

	Wordfence Security
		Version: 7.9.2
		Author: Wordfence

	WP Rocket
		Version: 3.13.0.2
		Author: WP Media


== Elements Usage ==
	
	container : 9
		button : 18
		container : 62
		form : 1
		heading : 21
		icon : 8
		image : 11
		loop-grid : 1
		media-carousel : 2
		text-editor : 11
		video : 2
	footer : 1
		container : 11
		heading : 31
		icon : 9
		image : 3
		spacer : 3
		text-editor : 1
	header : 2
		button : 4
		container : 6
		loop-grid : 1
		nav-menu : 2
		spacer : 1
		theme-site-logo : 2
	page : 2
		button : 2
		container : 96
		heading : 35
		icon : 2
		image : 56
		text-editor : 54
		video : 4
	wp-post : 1
		text-editor : 1
	wp-page : 32
		accordion : 6
		button : 36
		container : 1019
		form : 1
		heading : 325
		html : 3
		icon : 79
		image : 493
		loop-grid : 1
		media-carousel : 2
		progress : 6
		shortcode : 1
		spacer : 1
		text-editor : 436
		video : 27
	single-post : 1
		author-box : 1
		container : 11
		heading : 1
		post-comments : 1
		post-info : 4
		post-navigation : 1
		share-buttons : 3
		sidebar : 1
		spacer : 6
		table-of-contents : 1
		theme-post-content : 1
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 2
	single-page : 1
		button : 18
		container : 62
		form : 1
		heading : 21
		icon : 8
		image : 11
		loop-grid : 1
		media-carousel : 2
		text-editor : 11
		video : 2
	search-results : 1
		archive-posts : 1
		container : 4
		theme-archive-title : 1
	loop-item : 3
		button : 1
		container : 5
		heading : 1
		image : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 2


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Inactive by default
```

I hope this can help on the investigation.

**Comment by bobhuf** [comment]
> I was able to resolve the issue by opening the exported template JSON and changing the template_id value within the Loop Grid element settings to a valid Loop Template ID (post ID), then importing the file over again.

Thanks for logging this, you just saved me a lot of time.

**Comment by joaodath** [comment]
If you all are suffering with this obviously broken behavior, consider upvoting my request: https://github.com/orgs/elementor/discussions/23805

**Comment by KingYes** [comment]
It should be fixed in one of the late versions of Elementor Pro. Please reopen this if you see this error again and tell us how to reproduce it.
