### ISSUE TITLE
✅ 🐞 Bug Report: 3.12 beta - Social Icons EM Unit Size Issue - [ED-10204]

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#21719]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the Social Icons widget sizing it with EM, it doesn't work. From having a quick look at the CSS (screenshot below) it seems EM inherits the 0px font size value from the widget container. 

![Screenshot 2023-03-21 101212](https://user-images.githubusercontent.com/55829113/226576017-e9db551b-849b-47c5-8944-9fac198e41b7.png)

This is related to 3.12+ as the extra unit sizes for Social Icons widget was added in that version.

### Steps to reproduce

https://user-images.githubusercontent.com/55829113/226576072-a42ff430-2ed2-44f3-999a-aa444bfb95a1.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.26
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: [private]
	Home URL: [private]
	WP Multisite: Yes
	Max Upload Size: 128 MB
	Memory limit: 2048M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: [private]
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: 
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor Pro
		Version: 3.12.0-beta1
		Author: Elementor.com

	WooCommerce
		Version: 7.4.0
		Author: Automattic

== Network Plugins ==
	Elementor
		Version: 3.12.0-beta2
		Author: Elementor.com

== Must-Use Plugins ==
	StackCache
		Version: 
		Author: Stack CP

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Scroll Snap: Active by default
	Menu: Active

== Log ==
	
Log: showing 20 of 302023-03-05 18:47:25 [info] elementor-pro::elementor_pro_updater Started 
2023-03-05 18:47:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-05 18:47:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-05 18:47:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.0',
  'to' => '3.11.1',
)]
2023-03-06 21:02:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.12.0-beta1',
)]
2023-03-06 21:02:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.12.0-beta1',
)]
2023-03-06 21:02:55 [info] elementor::elementor_updater Started 
2023-03-06 21:02:55 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-06 21:02:55 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-06 21:02:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.12.0-beta1',
)]
2023-03-06 21:02:56 [info] elementor-pro::elementor_pro_updater Started 
2023-03-06 21:02:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-06 21:02:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-06 21:02:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.12.0-beta1',
)]
2023-03-06 21:02:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.12.0-beta1',
)]
2023-03-06 21:02:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.12.0-beta1',
)]
2023-03-14 16:16:23 [info] elementor::elementor_updater Started 
2023-03-14 16:16:23 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 16:16:23 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 16:16:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta1',
  'to' => '3.12.0-beta2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				

</details>

**Comment by nicholaszein** [comment]
Hello @perks98! Thanks for reporting this!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
