### ISSUE TITLE
⛔ 🐞 Bug Report: website just keep loading and dont open 

### ISSUE THREAD

**Issue by omarkh04** [elementor/elementor#21728]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am trying to enter the website, but it does not work, it only downloads and does not work. I tried to solve the problem in many ways, but to no avail

### Steps to reproduce

just open https://matrixtoken.co/ 
and you will see the problem

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.24
	PHP Version: 7.3.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://matrixtoken.co
	Home URL: https://matrixtoken.co
	WP Multisite: No
	Max Upload Size: 120 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 2
	Admin Email: info@matrixtoken.co
	Debug Mode: Inactive

== Theme ==
	Name: Vaximo
	Version: 2.1.0
	Author: EnvyTheme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Font Awesome
		Version: 4.0.4
		Author: Matt Keys

	Advanced Custom Fields PRO
		Version: 5.11.4
		Author: Delicious Brains

	Contact Form 7
		Version: 5.7.4
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.13.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Graphina - Elementor Charts and Graphs
		Version: 1.8.5
		Author: Iqonic Design

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	LiteSpeed Cache
		Version: 5.3.3
		Author: LiteSpeed Technologies

	Loginizer
		Version: 1.7.7
		Author: Softaculous

	PDF viewer for Elementor
		Version: 2.9.3
		Author: RedLettuce Plugins

	Redirection
		Version: 5.3.9
		Author: John Godley

	Unyson
		Version: 2.7.28
		Author: ThemeFuse

	Vaximo Toolkit
		Version: 2.1.0
		Author: EnvyTheme

	Visualizer: Tables and Charts for WordPress
		Version: 3.9.6
		Author: Themeisle

	Yoast SEO
		Version: 20.3
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Container Grid: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Active by default
	Lazy Load Background Images: Inactive by default

== Log ==
	
Log: showing 20 of 362023-01-14 22:04:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.11.0-dev3',
)]
2023-01-14 22:04:37 [info] elementor::elementor_updater Started 
2023-01-14 22:04:37 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-14 22:04:37 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-14 22:04:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.11.0-dev3',
)]
2023-01-14 22:04:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.11.0-dev3',
)]
2023-03-05 12:39:53 [info] elementor::elementor_updater Started 
2023-03-05 12:39:53 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-05 12:39:53 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-05 12:39:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev3',
  'to' => '3.12.0-dev4',
)]
2023-03-06 00:53:19 [info] elementor::elementor_updater Started 
2023-03-06 00:53:19 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-06 00:53:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-06 00:53:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.13.0-dev1',
)]
2023-03-06 00:53:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.13.0-dev1',
)]
2023-03-06 00:53:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-dev4',
  'to' => '3.13.0-dev1',
)]
2023-03-18 17:13:22 [info] elementor::elementor_updater Started 
2023-03-18 17:13:22 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-18 17:13:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-18 17:13:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev1',
  'to' => '3.13.0-dev2',
)]

JS: showing 1 of 1JS: 2022-01-29 15:03:16 [error X 3][http://localhost/wordpress/vaximo/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:768] Cannot read properties of undefined (reading \&#039;cid\&#039;) 

PHP: showing 5 of 5PHP: 2022-04-29 00:43:24 [warning X 4][/home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/compatibility.php::267] strpos() expects parameter 1 to be string, array given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-05 03:30:08 [error X 2][/home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method &#039;WP_REST_Controller::get_item_permissions_check&#039; not implemented. Must be overridden in subclass. in /home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller-&gt;get_permission_callback(Object(WP_REST_Request))
#1 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route-&gt;get_permission_callback(Object(WP_REST_Request))
#2 /home/matrixtoken.co/public_html/wp-includes/rest-api/class-wp-rest-server.php(1110): Elementor\Data\V2\Base\Base_Route-&gt;Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /home/matrixtoken.co/public_html/wp-includes/rest-api/class-wp-rest-server.php(990): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), &#039;/elementor/v1/f...&#039;, Array, NULL)
#4 /home/matrix [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 09:15:11 [error X 2][/home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method &#039;WP_REST_Controller::get_item_permissions_check&#039; not implemented. Must be overridden in subclass. in /home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller-&gt;get_permission_callback(Object(WP_REST_Request))
#1 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route-&gt;get_permission_callback(Object(WP_REST_Request))
#2 /home/matrixtoken.co/public_html/wp-includes/rest-api/class-wp-rest-server.php(1138): Elementor\Data\V2\Base\Base_Route-&gt;Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 /home/matrixtoken.co/public_html/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), &#039;/elementor/v1/f...&#039;, Array, NULL)
#4 /home/matri [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-05 12:48:50 [error X 1][/home/matrixtoken.co/public_html/wp-content/plugins/elementor/core/common/app.php::172] Uncaught Error: Undefined class constant &#039;ELEMENTOR_ICONS_VERSION&#039; in /home/matrixtoken.co/public_html/wp-content/plugins/elementor/core/common/app.php:172
Stack trace:
#0 /home/matrixtoken.co/public_html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\App-&gt;register_styles(&#039;&#039;)
#1 /home/matrixtoken.co/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /home/matrixtoken.co/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#3 /home/matrixtoken.co/public_html/wp-includes/script-loader.php(2180): do_action(&#039;wp_enqueue_scri...&#039;)
#4 /home/matrixtoken.co/public_html/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts(&#039;&#039;)
#5 /home/matrixtoken.co/public_html/wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#6 /home/matrixtoken.co/public_html/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#7 /home/matrixtoken.co/public_html/wp-includes/general-template.php(3043): do_action(&#039;wp_head&#039;)
#8 /home/matrixtoken.co/public_html/wp-cont [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-14 22:04:22 [error X 1][/home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/controls/date-time.php::51] Uncaught Error: Undefined class constant &#039;DATETIME_CATEGORY&#039; in /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/controls/date-time.php:51
Stack trace:
#0 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/controls/base.php(73): Elementor\Control_Date_Time-&gt;get_default_settings()
#1 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/controls/base-data.php(19): Elementor\Base_Control-&gt;__construct()
#2 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/managers/controls.php(436): Elementor\Base_Data_Control-&gt;__construct()
#3 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/managers/controls.php(589): Elementor\Controls_Manager-&gt;register_controls()
#4 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/managers/controls.php(608): Elementor\Controls_Manager-&gt;get_controls()
#5 /home/matrixtoken.co/public_html/wp-content/plugins/elementor/includes/managers/controls.php(779): Elementor\Controls_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Graphina - Elementor Charts and Graphs: Compatibility not specified
	PDF viewer for Elementor: Compatibility not specified

**Comment by nicholaszein** [comment]
Hello @omarkh04,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

It seems you have a loader causing an error in your site. Login to your dashboard and disable the Theme Preloader.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
