### ISSUE TITLE
⛔ 🐞 Bug Report: demo.detheme.com popup

### ISSUE THREAD

**Issue by BatLegion** [elementor/elementor#21732]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have this popup that keeps showing on every page on page load. I have removed all plugins to find the issue as well as looking through the code and the .htaccess files to find the issue. When the Elementor Pro plugin is disabled then the popup goes away.

I have tried to look through all settings to find a solution but cannot unfortunately.

![image](https://user-images.githubusercontent.com/78880068/227120025-8d1bc19e-ebb4-4659-9efe-e6f61c010ad5.png)
,

### Steps to reproduce

All you need to do is load the page and the popup will show

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.28
	PHP Version: 8.0.28
	PHP Memory Limit: 96M
	PHP Max Input Vars: 3500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://dailydosemarketing.co.za
	Home URL: https://dailydosemarketing.co.za
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 448M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@dailydosemarketing.co.za
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 3.4.2
	Author: OceanWP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	All In One WP Security
		Version: 5.1.5
		Author: All In One WP Security & Firewall Team

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Cookie Notice &amp; Compliance for GDPR / CCPA
		Version: 2.4.7
		Author: Hu-manity.co

	Elementor
		Version: 3.13.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.7
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.8.5
		Author: Wpmet

	GetGenie AI
		Version: 3.4.2
		Author: getgenieai

	Jet Appointments Booking
		Version: 2.0.1
		Author: Crocoblock

	JetEngine
		Version: 3.1.3.1
		Author: Crocoblock

	LiteSpeed Cache
		Version: 5.3.3
		Author: LiteSpeed Technologies

	Ocean Extra
		Version: 2.1.4
		Author: OceanWP

	Site Kit by Google
		Version: 1.96.0
		Author: Google

	Theme Editor
		Version: 2.7
		Author: mndpsingh287

	Tidio Chat
		Version: 6.0.4
		Author: Tidio Ltd.

	WPCode Lite
		Version: 2.0.8.1
		Author: WPCode

	Yoast SEO
		Version: 20.3
		Author: Team Yoast

	Yoast SEO: Local
		Version: 13.9
		Author: Team Yoast and Arjan Snaterse

	Yoast SEO Premium
		Version: 18.4
		Author: Team Yoast

== Must-Use Plugins ==
	aios-firewall-loader.php
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 1
		button : 1
		divider : 2
		heading : 5
		icon-list : 4
		image : 1
		text-editor : 1
	header : 2
		elementskit-social-media : 1
		html : 2
		image : 2
		nav-menu : 1
	page : 8
		accordion : 1
		button : 36
		container : 82
		elementskit-blog-posts : 2
		elementskit-lottie : 6
		heading : 82
		icon : 7
		icon-box : 3
		icon-list : 11
		image : 25
		menu-anchor : 1
		price-table : 3
		text-editor : 74
	section : 6
		button : 22
		divider : 4
		elementskit-lottie : 14
		elementskit-testimonial : 2
		heading : 80
		icon : 7
		icon-box : 12
		icon-list : 5
		image : 48
		image-box : 4
		image-carousel : 2
		lottie : 1
		social-icons : 7
		spacer : 8
		testimonial-carousel : 2
		text-editor : 25
		toggle : 1
	widget : 0
		elementskit-icon-box : 1
	wp-page : 13
		button : 45
		container : 157
		elementskit-accordion : 2
		elementskit-blog-posts : 1
		elementskit-icon-box : 15
		elementskit-lottie : 6
		form : 4
		gallery : 4
		google_maps : 1
		heading : 116
		icon : 8
		icon-box : 9
		icon-list : 15
		image : 13
		jet-engine-booking-form : 1
		menu-anchor : 1
		text-editor : 85
	single-post : 1
		container : 3
		heading : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	error-404 : 1
		heading : 1
		lottie : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page, elementskit_template, elementskit_widget
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Container Grid: Inactive by default
	Default to New Theme Builder: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Mega Menu: Active by default

== Log ==
	
Log: showing 20 of 382023-03-13 06:25:33 [info] elementor-pro::elementor_pro_updater Started 
2023-03-13 06:25:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-13 06:25:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-13 06:25:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-13 06:25:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-15 10:19:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev1',
  'to' => '3.13.0-dev2',
)]
2023-03-15 10:19:02 [info] elementor::elementor_updater Started 
2023-03-15 10:19:02 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-15 10:19:03 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-15 10:19:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev1',
  'to' => '3.13.0-dev2',
)]
2023-03-15 10:36:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-15 10:36:23 [info] elementor-pro::elementor_pro_updater Started 
2023-03-15 10:36:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-15 10:36:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-15 10:36:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-15 10:36:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-22 20:10:56 [info] elementor-pro::elementor_pro_updater Started 
2023-03-22 20:10:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-22 20:10:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-22 20:10:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.6',
  'to' => '3.11.7',
)]

JS: showing 4 of 4JS: 2023-02-28 14:03:12 [error X 1][https://dailydosemarketing.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-dev4:3:1090319] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-02-28 14:09:59 [error X 3][https://dailydosemarketing.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-dev4:3:934437] Cannot read properties of undefined (reading &#039;settings&#039;) 
JS: 2023-03-22 06:41:51 [error X 16][https://dailydosemarketing.co.za/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 
JS: 2023-03-22 09:07:37 [error X 1][https://dailydosemarketing.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:678469] this.model.isValidChild is not a function 

PHP: showing 1 of 1PHP: 2023-03-23 06:14:01 [warning X 1][/usr/www/users/dailyphfae/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @BatLegion,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The popup you're seeing was set on your hosting panel, it's a security setting.

### ✅ What you can do to solve your issue:
- Contact your hosting support.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Kind regards
