### ISSUE TITLE
🐞 Bug Report: Dark mode in 3.12-Beta2 affects the Media section.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21735]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If the dark mode is active in the editor, we will have a problem in the Insert Media section. The problem is that between the file upload and media library tabs, only the active option is displayed. Another option is not displayed, but it is displayed when the mouse is hovered over it.
But if the editor is light mode, this bug does not occur.

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/227159324-a230f559-841c-450a-b8a3-f7472464c96f.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-localhost-23-03-2023.txt](https://github.com/elementor/elementor/files/11049695/system-info-localhost-23-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello @79ho3ein! 

Thank you for submitting your issue! 🙏 

We will take a look at this and see if we can fix it! 😉 

Best regards
