### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Google Adsense automatic ads don't display

### ISSUE THREAD

**Issue by alexbaes** [elementor/elementor#21731]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Until a few days ago, Google Adsense auto ads were showing on my website, but after updating Elementor and switching to the new box model, the auto ads are no longer showing. I don't understand the reason. Thank you

### Steps to reproduce

Visit https://lanzamientosespaciales.com and check that automatic ads doesn't work.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.38
	PHP Version: 8.0.28
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://lanzamientosespaciales.com
	Home URL: https://lanzamientosespaciales.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 1024M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: UTC
	Admin Email: info@lanzamientosespaciales.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child Theme
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.0.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.7
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.0
		Author: Shabti Kaplan

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.4.2.1
		Author: Really Simple Plugins

	Duplicate Page
		Version: 4.5.1
		Author: mndpsingh287

	Elementor
		Version: 3.11.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	Elementor Single Builder for MEC
		Version: 1.5.5
		Author: Webnus

	GD Rating System
		Version: 3.5
		Author: Milan Petrovic

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	Modern Events Calendar Lite
		Version: 6.8.25
		Author: Webnus

	Quiz Maker
		Version: 6.4.1.0
		Author: Quiz Maker team

	Rank Math SEO
		Version: 1.0.110.1
		Author: Rank Math

	TablePress
		Version: 2.0.4
		Author: Tobias Bäthge

	TablePress Extension: Responsive Tables
		Version: 1.8
		Author: Tobias Bäthge

	The Plus Addons for Elementor
		Version: 5.1.16
		Author: POSIMYTH

	Timeline Widget For Elementor
		Version: 1.4.1
		Author: Cool Plugins

	WP Rocket
		Version: 3.12.6.1
		Author: WP Media

== Caracteristicas ==
	Custom Fonts: 2
	Custom Icons: 0

== Integraciones ==
	
	recaptcha_v3: Activo

== Experimentos de Elementor ==
	Salida del DOM optimizada: Activo
	Carga de recursos mejorada: Activo
	Carga de CSS mejorada: Inactivo por defecto
	Fuentes de iconos integradas: Activo
	Mejoras de accesibilidad: Inactivo por defecto
	Puntos de ruptura personalizados adicionales: Inactivo por defecto
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Activo
	Actualizar la librería Swiper: Inactivo por defecto
	Por defecto, el nuevo constructor de temas: Activo
	Editor V2: Inactivo por defecto
	Páginas de destino: Activo por defecto
	Elementos anidados: Activo
	Carga diferida de imágenes de fondo: Activo
	Guardar como por defecto: Activo por defecto
	Transiciones de páginas: Activo por defecto
	Notas: Activo por defecto
	Bucle: Activo
	Envíos de formulario: Activo por defecto
	Ajuste de scroll: Activo por defecto
	Mega Menu: Inactivo por defecto

== Registro ==
	
Log: showing 20 of 262023-03-08 09:02:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-08 09:29:19 [info] elementor::elementor_updater Started 
2023-03-08 09:29:19 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-08 09:29:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-08 09:29:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.11.3',
)]
2023-03-08 09:29:19 [info] elementor-pro::elementor_pro_updater Started 
2023-03-08 09:29:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-08 09:29:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-08 09:29:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.11.4',
)]
2023-03-14 10:33:50 [info] elementor::elementor_updater Started 
2023-03-14 10:33:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 10:33:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 10:33:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.11.5',
)]
2023-03-14 10:33:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.3',
  'to' => '3.11.5',
)]
2023-03-14 10:35:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.6',
)]
2023-03-14 10:52:36 [info] elementor-pro::elementor_pro_updater Started 
2023-03-14 10:52:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-14 10:52:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-14 10:52:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.6',
)]
2023-03-14 10:52:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.6',
)]

PHP: showing 8 of 8PHP: 2023-03-05 14:27:04 [warning X 1][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::247] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 18:19:45 [warning X 3][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/base/document.php::1709] Attempt to read property "post_status" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 18:35:33 [error X 1][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/settings/page/manager.php::101] Uncaught Exception: Invalid post. in /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/settings/page/manager.php:101
Stack trace:
#0 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/base/document.php(1646): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings()
#1 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/base/document.php(790): Elementor\Core\Base\Document->save_settings()
#2 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/kits/manager.php(295): Elementor\Core\Base\Document->update_settings()
#3 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/kits/manager.php(461): Elementor\Core\Kits\Manager->update_kit_settings_based_on_option()
#4 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(310): Elementor\Core\Kits\Manager->Elementor\Core\Kits\{closure}()
#5 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/option.php(554): do_action()
#8 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-customize-setting.php(659): update_option()
#9 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-customize-setting.php(685): WP_Customize_Setting->set_root_value()
#10 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-customize-setting.php(541): WP_Customize_Setting->update()
#11 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-customize-manager.php(3572): WP_Customize_Setting->save()
#12 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/theme.php(3573): WP_Customize_Manager->_publish_changeset_values()
#13 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(308): _wp_customize_publish_changeset()
#14 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/post.php(5347): do_action()
#17 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/post.php(4607): wp_transition_post_status()
#18 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-customize-manager.php(2976): wp_insert_post()
#19 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-customize-manager.php(2527): WP_Customize_Manager->save_changeset_post()
#20 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(308): WP_Customize_Manager->save()
#21 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#22 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#23 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-admin/admin-ajax.php(188): do_action()
#24 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-07 19:54:59 [warning X 5][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 10:11:05 [warning X 1][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 10:14:51 [warning X 5][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 14:48:31 [error X 5][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home2/baesaudi/public_html/lanzamientosespaciales.com/wp-admin/admin-ajax.php(188): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-10 14:57:05 [warning X 2][/home2/baesaudi/public_html/lanzamientosespaciales.com/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 9 of 9JS: 2023-03-07 16:58:49 [error X 4][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.11.0:2:10991] undefined is not an object (evaluating 'this.getExperimentSelect(e).value=t') 
JS: 2023-03-07 17:46:24 [error X 1][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0:3:899311] Can't find variable: elementorFrontend 
JS: 2023-03-08 11:07:50 [error X 2][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:592136] Cannot read properties of null (reading 'id') 
JS: 2023-03-08 11:51:55 [error X 4][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:791668] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-08 14:51:24 [error X 1][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.11.3:3:80488] Data commands: `undefined` not found. 
JS: 2023-03-08 16:09:44 [error X 3601][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.3:3:622096] Cannot read properties of undefined (reading 'get') 
JS: 2023-03-10 15:46:10 [error X 15][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.11.3:2:29508] Cannot read properties of undefined (reading 'closest') 
JS: 2023-03-16 09:47:42 [error X 1][https://lanzamientosespaciales.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-03-22 09:59:40 [error X 1][https://lanzamientosespaciales.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:670939] this.model.isValidChild is not a function 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Elementor Single Builder for MEC: Compatibilidad no especificada
	The Plus Addons for Elementor: Incompatible
	Timeline Widget For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	The Plus Addons for Elementor: Incompatible
	Timeline Widget For Elementor: Incompatible

**Comment by nicholaszein** [comment]
Hello @alexbaes,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

It seems your issue might be related to a conflict with one of your plugins or cache. Follow the troubleshooting steps below to solve your issue.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Regards
