### ISSUE TITLE
⛔ 📚 Developer-API Question: Popup visible only for administrators

### ISSUE THREAD

**Issue by gwhispert** [elementor/elementor#21753]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, I am not sure if this is bug, but I will appreciate all help.
I am calling the popup on the page if the post is in the draft state. It works correctly if the user is an administrator, but for all other users, it is not visible. However, it is loaded for all of them, but without some wrapper elements with classess "dialog-widget dialog-lightbox-widget dialog-type-buttons dialog-type-lightbox elementor-popup-modal" , "dialog-widget-content dialog-lightbox-widget-content animated" and "dialog-message dialog-lightbox-message"

Popup does not have any conditions except to be displayed on the custom post type single page.

I call it in functions.php with this code:
```
add_action( 'wp_footer', 'popup_function', 10, 5);
function popup_function(){
    if(is_singular('campaigns') ){
		$popup_publish = '31437'; // Popup ID.
        ElementorPro\Modules\Popup\Module::add_popup_to_location( $popup_publish );
		if(get_post_status() == 'draft'){
			?><script>
				jQuery( document ).ready( function() { 
            	jQuery( window ).on( 'elementor/frontend/init', function() { //wait for elementor to load
                elementorFrontend.on( 'components:init', function() { //wait for elementor pro to load
				elementorFrontend.documentsManager.documents[<?php echo $popup_publish ?>].showModal(); 
                } );
            </script>
		<?php
		}
    }
}
```

### Steps to reproduce

- login as user
- create post(it is custom post type)
- when user opens that new post it is initially in the draft state and pop up with this information has to be opened, but it opens only for administrators.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 ()
	MySQL version: MySQL Community Server (GPL) v5.7.12
	PHP Version: 8.0.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://whispert.de
	Home URL: https://whispert.de
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: harry@whispert.de
	Debug Mode: Active

== Theme ==
	Name: BuddyBoss Child
	Version: 1.0.1
	Author: BuddyBoss.com
	Child Theme: Yes
	Parent Theme Name: BuddyBoss Theme
	Parent Theme Version: 2.2.2
	Parent Theme Author: BuddyBoss

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.7
		Author: WP Engine

	Autocomplete WooCommerce Orders
		Version: 3.0.2
		Author: QuadLayers

	BuddyBoss Platform
		Version: 2.2.2
		Author: BuddyBoss

	BuddyBoss Platform Pro
		Version: 2.2.2
		Author: BuddyBoss

	BuddyBuilder - BuddyPress Builder for Elementor
		Version: 1.7.1
		Author: StaxWP

	BuddyBuilder Pro
		Version: 1.6.7
		Author: StaxWP

	Clickskeks
		Version: 1.3.3
		Author: Papoo Software & Media GmbH

	Custom Profile Menu for BuddyPress
		Version: 1.0.3
		Author: Nahid Ferdous Mohit

	e-addons DEVELOPER
		Version: 2.3.1.1
		Author: Nerds Farm

	e-addons DISPLAY
		Version: 2.1.3
		Author: Nerds Farm

	e-addons EXTENDED
		Version: 2.3.1
		Author: Nerds Farm

	e-addons for Elementor
		Version: 3.3.1
		Author: Nerds Farm

	e-addons PRO FORM ACTIONS
		Version: 2.2.2
		Author: Nerds Farm

	e-addons PRO FORM CONDITIONS
		Version: 2.2
		Author: Nerds Farm

	e-addons PRO FORM EXTENDED
		Version: 2.4.2
		Author: Nerds Farm

	e-addons QUERY
		Version: 2.1.5
		Author: Nerds Farm

	e-addons TWIG
		Version: 2.3.1
		Author: Nerds Farm

	e-addons UI
		Version: 2.2.2
		Author: Nerds Farm

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	GamiPress
		Version: 2.5.7.1
		Author: GamiPress

	GamiPress - Referrals
		Version: 1.1.1
		Author: GamiPress

	German Market
		Version: 3.20
		Author: MarketPress

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	Mollie Payments for WooCommerce
		Version: 7.3.5
		Author: Mollie

	Prepaid for WooCommerce Subscriptions
		Version: 3.2.1
		Author: Meow Crew

	Query Monitor
		Version: 3.11.1
		Author: John Blackbourn

	Tidio Chat
		Version: 6.0.2
		Author: Tidio Ltd.

	UpdraftPlus - Backup/Restore
		Version: 1.23.3
		Author: UpdraftPlus.Com, DavidAnderson

	URL Coupons for WooCommerce
		Version: 1.6.6
		Author: WPFactory

	User Role Editor
		Version: 4.63.2
		Author: Vladimir Garagulya

	Wispert Core
		Version: 1.0.0
		Author: BuddyBoss

	WooCommerce
		Version: 7.4.0
		Author: Automattic

	WooCommerce Subscriptions
		Version: 4.6.0
		Author: WooCommerce

	XML Sitemap & Google News
		Version: 5.3.3
		Author: RavanH

	XML Sitemap & Google News - Google News Advanced
		Version: 1.3.4
		Author: RavanH

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Landing Pages: Inactive
	Color Sampler: Active
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
JS: showing 20 of 36JS: 2023-02-09 10:00:51 [error X 1][https://whispert.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view704\") has already been destroyed and cannot be used. 
JS: 2023-02-09 14:19:22 [error X 1][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:881312] elementorFrontend is not defined 
JS: 2023-02-11 14:58:14 [error X 32][https://whispert.de/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:2:51816] a is undefined 
JS: 2023-02-11 18:56:25 [error X 21][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:749615] C.terms is undefined 
JS: 2023-02-12 21:32:53 [error X 2][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:763689] C.replace is not a function 
JS: 2023-02-13 11:49:43 [error X 275][https://whispert.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.9.2:2:15890] Cannot read properties of undefined (reading \'global\') 
JS: 2023-02-13 14:41:36 [error X 2][https://whispert.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view531\") has already been destroyed and cannot be used. 
JS: 2023-02-13 14:45:12 [error X 23][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:616499] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2023-02-14 09:39:09 [error X 4][https://whispert.de/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.2:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-02-14 19:50:24 [error X 42][https://whispert.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.9.2:2:15873] r[a] is undefined 
JS: 2023-02-21 10:37:30 [error X 8][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:749623] Cannot read properties of undefined (reading \'forEach\') 
JS: 2023-02-27 10:49:53 [error X 2][https://whispert.de/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.17:12:153998] Window.getComputedStyle: Argument 1 is not an object. 
JS: 2023-02-27 13:11:31 [error X 1][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:640368] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-02-27 13:11:31 [error X 1][https://whispert.de/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.17:12:0]  
JS: 2023-02-27 13:11:39 [error X 9][https://whispert.de/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.9.2:2:4823] e is undefined 
JS: 2023-03-06 09:29:37 [error X 5][https://whispert.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.9.2:2:6788] elementorModules.frontend is undefined 
JS: 2023-03-06 15:02:22 [error X 29][https://whispert.de/wp-content/uploads/elementor/js/e-addons-section-transitions.min.js:37:32] currPage.find(...)[0] is undefined 
JS: 2023-03-07 15:19:17 [error X 2][https://whispert.de/wp-content/uploads/elementor/js/e-addons-query-grid.min.js:4:142] eadd_animationReveal is not defined 
JS: 2023-03-09 10:03:54 [error X 2][https://whispert.de/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] Cannot read properties of undefined (reading \'showModal\') 
JS: 2023-03-12 11:20:55 [error X 6][https://whispert.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.2:3:749615] undefined has no properties 

PHP: showing 6 of 6PHP: 2023-01-19 13:49:58 [warning X 473][/var/www/html/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::248] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 14:35:47 [warning X 53][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-12 22:43:51 [error X 1][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-20 18:19:50 [warning X 2][/var/www/html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-08 19:22:54 [warning X 1][/var/www/html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-09 10:02:08 [error X 1][/var/www/html/wp-content/plugins/elementor/core/documents-manager.php::493] Uncaught Error: Call to a member function is_built_with_elementor() on bool in /var/www/html/wp-content/plugins/elementor/core/documents-manager.php:493
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#1 /var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/html/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#3 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	BuddyBuilder - BuddyPress Builder for Elementor: Incompatible
	BuddyBuilder Pro: Incompatible
	e-addons for Elementor: Compatibility unknown
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	BuddyBuilder - BuddyPress Builder for Elementor: Incompatible
	BuddyBuilder Pro: Incompatible
	e-addons for Elementor: Compatibility unknown

**Comment by nicholaszein** [comment]
Hello @gwhispert,

Unfortunately, what you are trying to do is not possible because it's not supported By Elementor. 

You can't display Popups in the WP Admin area. There is no workaround for the time being, and we don't have plans to add this feature to our plugin.

Best regards
