### ISSUE TITLE
⛔ 🐞 Bug Report: Fatal error: Uncaught Error: Call to undefined function trailingslashit()

### ISSUE THREAD

**Issue by confile** [elementor/elementor#21759]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

<div class="elm-entry-body-container" style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elm-entry-body" style="outline: 0px; padding: 0px 12px;"><p class="elm-log-message" style="font-size: 14px; line-height: 1.5; margin: 2px 0px; color: rgb(35, 40, 45);">Fatal error: Uncaught Error: Call to undefined function trailingslashit(<wbr>)<wbr><span> </span>in<span> </span><wbr>/kunden<wbr>/365999_20251<wbr>/webseiten<wbr>/michaelgorski<wbr>.net<wbr>/wp-dmg-www-v4<wbr>/wp-includes<wbr>/class-wp-textdomain-registry<wbr>.php:103</p></div></div><div class="elm-entry-context-container" style="outline: 0px; padding: 0px 12px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elm-context-group" style="outline: 0px; margin-left: 1em; margin-top: 1em; margin-bottom: 1em; border-top: 1px solid rgba(0, 0, 0, 0.06); color: rgb(85, 85, 85);"><h3 class="elm-context-group-caption" style="display: block; font-weight: 400; color: rgb(29, 35, 39); font-size: 14px; margin: 8px 0px; padding: 0px;">Stack Trace</h3>

1. | WP_Textdomain_Registry->set()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/l10n.php:784
-- | --
2. | load_textdomain()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/load.php:1401
3. | wp_load_translations_early()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/load.php:278
4. | wp_maintenance()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-settings.php:74
5. | require_once('/kunden/365999_...')/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-config.php:127
6. | require_once('/kunden/365999_...')/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-load.php:50
7. | require_once('/kunden/365999_...')/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-blog-header.php:13
8. | /kunden in /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/class-wp-textdomain-registry.php on line 103

</div></div>

<div class="elm-entry-body-container" style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elm-entry-body" style="outline: 0px; padding: 0px 12px;"><p class="elm-log-message" style="font-size: 14px; line-height: 1.5; margin: 2px 0px; color: rgb(35, 40, 45);">Fatal error: Uncaught Error: Call to undefined function trailingslashit(<wbr>)<wbr><span> </span>in<span> </span><wbr>/kunden<wbr>/365999_20251<wbr>/webseiten<wbr>/michaelgorski<wbr>.net<wbr>/wp-dmg-www-v4<wbr>/wp-includes<wbr>/class-wp-textdomain-registry<wbr>.php:103</p></div></div><div class="elm-entry-context-container" style="outline: 0px; padding: 0px 12px; color: rgb(60, 67, 74); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elm-context-group" style="outline: 0px; margin-left: 1em; margin-top: 1em; margin-bottom: 1em; border-top: 1px solid rgba(0, 0, 0, 0.06); color: rgb(85, 85, 85);"><h3 class="elm-context-group-caption" style="display: block; font-weight: 400; color: rgb(29, 35, 39); font-size: 14px; margin: 8px 0px; padding: 0px;">Stack Trace</h3>

1. | WP_Textdomain_Registry->set()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/l10n.php:784
-- | --
2. | load_textdomain()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/load.php:1401
3. | wp_load_translations_early()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/load.php:278
4. | wp_maintenance()/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-settings.php:74
5. | require_once('/kunden/365999_...')/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-config.php:127
6. | require_once('/kunden/365999_...')/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-load.php:50
7. | require_once('/kunden/365999_...')/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-blog-header.php:13
8. | /kunden in /kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-includes/class-wp-textdomain-registry.php on line 103

</div></div>

### Steps to reproduce

Update Elementor to 

Elementor - 3.11.5 | By Elementor.com |  
-- | -- | --
Elementor Pro - 3.11.7

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.28
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 75M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.michaelgorski.net
	Home URL: https://www.michaelgorski.net
	WP Multisite: No
	Max Upload Size: 75 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: mg@michaelgorski.net
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	All In One WP Security
		Version: 5.1.6
		Author: All In One WP Security & Firewall Team

	BlogLentor for Elementor
		Version: 1.0.8
		Author: wpsurface

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.63
		Author: Borlabs GmbH

	Broken Link Checker
		Version: 2.0.0
		Author: WPMU DEV

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Docs Viewer Add-On for WP Job Openings
		Version: 1.0
		Author: AWSM Innovations

	Duplicator Pro
		Version: 4.5.10
		Author: Snap Creek

	Elementor
		Version: 3.11.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.7
		Author: Elementor.com

	Embed Plus YouTube WordPress Plugin
		Version: 14.1.5
		Author: Embed Plus YouTube Plugin Team

	Enable Media Replace
		Version: 4.0.3
		Author: ShortPixel

	Error Log Monitor
		Version: 1.7.4
		Author: Janis Elsts

	Instant Indexing
		Version: 1.1.16
		Author: Rank Math

	Meta Tag Manager
		Version: 3.0.2
		Author: Pixelite

	Nginx Cache
		Version: 1.0.5
		Author: Till Krüss

	Page Generator Pro
		Version: 4.1.0
		Author: WP Zinc

	PDF Block
		Version: 1.1.0
		Author: henryholtgeerts

	Resize Image After Upload
		Version: 1.8.6
		Author: ShortPixel

	Seriously Simple Podcasting
		Version: 2.20.2
		Author: Castos

	ShortPixel Image Optimizer
		Version: 5.2.1
		Author: ShortPixel - Convert WebP/AVIF & Optimize Images

	Site Kit by Google
		Version: 1.96.0
		Author: Google

	Smooth Back To Top Button
		Version: 1.1.8
		Author: Tanvirul Haque

	Sticky Side Buttons
		Version: 1.0.9
		Author: Maeve Lander

	Tf Youtube Widgets Addon For Elementor
		Version: 1.0.2
		Author: Themesflat

	Two Factor Authentication
		Version: 1.14.11
		Author: David Anderson, original plugin by Oskar Hane and enhanced by Dee Nutbourne

	WP Activity Log
		Version: 4.4.3.2
		Author: WP White Security

	WP Activity Log for Yoast SEO
		Version: 1.3.0
		Author: WP White Security

	WP Anti-Clickjack
		Version: 1.7.5
		Author: Andy Feliciotti

	WP Armour - Honeypot Anti Spam
		Version: 2.1.3
		Author: Dnesscarkey

	WP Htaccess Editor
		Version: 1.71
		Author: WebFactory Ltd

	WP Job Openings
		Version: 3.3.3
		Author: AWSM Innovations

	WP Mail SMTP
		Version: 3.7.0
		Author: WPForms

	WP Rocket
		Version: 3.12.6.1
		Author: WP Media

	WP Rocket | Change Parameters
		Version: 
		Author: WP Rocket Support Team

	WPS Hide Login
		Version: 1.9.8
		Author: WPServeur, NicolasKulka, wpformation

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 20.3
		Author: Team Yoast

	Yoast SEO: Video
		Version: 14.7
		Author: Team Yoast

	Yoast SEO Premium
		Version: 20.3
		Author: Team Yoast

	Yoast Test Helper
		Version: 1.17
		Author: Team Yoast

== Must-Use Plugins ==
	Page Generator Pro: Performance Addon
		Version: 2.9.3
		Author: WP Zinc

== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 20 of 362023-03-13 09:35:49 [info] elementor-pro::elementor_pro_updater Started 
2023-03-13 09:35:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-13 09:35:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-13 09:35:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 10:45:36 [info] elementor::elementor_updater Started 
2023-03-14 10:45:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 10:45:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 10:45:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 10:45:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 10:45:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.4',
  'to' => '3.11.5',
)]
2023-03-14 11:26:44 [info] elementor-pro::elementor_pro_updater Started 
2023-03-14 11:26:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-14 11:26:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-14 11:26:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-14 11:26:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.5',
  'to' => '3.11.6',
)]
2023-03-23 17:28:19 [info] elementor-pro::elementor_pro_updater Started 
2023-03-23 17:28:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-23 17:28:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-23 17:28:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.6',
  'to' => '3.11.7',
)]
2023-03-23 17:28:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.6',
  'to' => '3.11.7',
)]

JS: showing 5 of 5JS: 2023-03-08 19:13:52 [error X 7][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.11.3:2:53736] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-03-13 15:48:54 [error X 2][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.4:3:931389] Cannot read properties of undefined (reading 'settings') 
JS: 2023-03-13 15:50:34 [error X 6][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.11.4:3:70148] Commands: `panel/global/open` not found. 
JS: 2023-03-14 11:35:20 [error X 1][https://www.michaelgorski.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.4:3:1087291] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-03-23 08:14:34 [error X 3][https://www.michaelgorski.net/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 

PHP: showing 1 of 1PHP: 2023-03-18 15:55:24 [notice X 1][/kunden/365999_20251/webseiten/michaelgorski.net/wp-dmg-www-v4/wp-content/plugins/elementor-pro/core/utils.php::373] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	BlogLentor for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Tf Youtube Widgets Addon For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @confile,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
