### ISSUE TITLE
Gallery widget image opened in Lightbox has [object Object] instead of left and right arrows and the captions are not centered

### ISSUE THREAD

**Issue by mikeadksky** [elementor/elementor#21765]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Gallery widget image opened in Lightbox has [object Object] instead of left and right arrows and the captions are not centered.  See attached screenshot.

Problem experienced while working on Getting Started With Elementor Cloud Website tutorial, step #9 (Designing Your Posts with Elementor) (https://elementor.com/academy/getting-started-with-elementor-cloud/?playlist=4ebcdd8&video=c227474).  

Website is hosted on Elementor Cloud.

I did find someone with same problem (opened 9 days ago in Reddit) doing internet search: https://www.reddit.com/r/elementor/comments/11spuwp/update_has_added_object_object_to_my_slideshows/?rdt=34277
<img width="1552" alt="Screenshot 2023-03-25 at 12 40 58 PM" src="https://user-images.githubusercontent.com/128931073/227739389-aaccf7a8-2dd9-4d41-9921-82ae85c5d849.png">

I have checked for similar issue with open and closed issues with labels: component/gallery, component/lightbox.

### Steps to reproduce

Getting Started With Elementor Cloud Website tutorial, step #9 (Designing Your Posts with Elementor)
1) Added Gallery widget to column
2) Selected 3 images for project from Media Library
3) Created new gallery and added captions for each image
4) Inserted gallery
5) changed layout (Content, Style) per instructions in tutorial including Overlay Title = Caption and Description = None

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: (Google) v8.0.26
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://gettingstartedtutorials.elementor.cloud
	Home URL: https://gettingstartedtutorials.elementor.cloud
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: mike@adksky.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0

== Active Plugins ==
	Elementor
		Version: 3.13.0-cloud1
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.0-cloud2
		Author: Elementor.com

== Elements Usage ==
	
	archive : 3
		heading : 1
		portfolio : 1
	footer : 1
		icon-list : 1
		social-icons : 1
	header : 1
		button : 1
		nav-menu : 1
		theme-site-logo : 1
	page : 2
		blockquote : 1
		button : 1
		divider : 2
		gallery : 1
		heading : 2
		slides : 1
		text-editor : 2
	wp-post : 1
		blockquote : 1
		button : 1
		divider : 2
		gallery : 1
		heading : 2
		slides : 1
		text-editor : 2
	wp-page : 4
		button : 1
		divider : 2
		gallery : 1
		heading : 1
		icon-list : 1
		lottie : 1
		spacer : 1
		testimonial-carousel : 1
		text-editor : 1
	single-post : 2
		icon : 1
		post-navigation : 1
		share-buttons : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1

== Settings ==
	
	allow_tracking: yes
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Container Grid: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Improved Page Actions Layout: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Scroll Snap: Active by default
	Menu: Active by default

== Log ==
	
PHP: showing 5 of 5PHP: 2023-03-21 21:48:52 [notice X 22][/mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-22 13:16:45 [notice X 1][/mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-22 13:17:55 [notice X 3][/mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-22 13:51:48 [warning X 7][/mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor-pro/modules/mega-menu/widgets/mega-menu.php::1567] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-22 20:36:40 [error X 2][/mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in /mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 /mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions()
#2 /mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b0023a911bd/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func()
#3 /mnt/customers-man/customers-el-4922107-50794-gettingstartedtutorials-wordpress-pvc-6416c947cc6b3b002 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2023-03-22 15:04:30 [error X 1][https://gettingstartedtutorials.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-cloud1:3:130000] C.getNamespaceArray is not a function 
JS: 2023-03-22 15:10:38 [error X 3][https://gettingstartedtutorials.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-cloud1:3:907091] $e.routes.getHistory(...).reverse()[0] is undefined 
JS: 2023-03-24 16:24:28 [error X 6][https://gettingstartedtutorials.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-cloud1:3:790958] this.store.find(...) is undefined 

Log: showing 5 of 52023-03-24 21:33:33 [info] elementor-pro::elementor_pro_updater Started 
2023-03-24 21:33:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-24 21:33:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-24 21:33:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0-cloud1',
  'to' => '3.13.0-cloud2',
)]
2023-03-24 21:33:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.0-cloud1',
  'to' => '3.13.0-cloud2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by m1ga** [comment]
Fixed in https://github.com/elementor/elementor/pull/21738 already

**Comment by mikeadksky** [comment]
Per 2023.03.25 email from Michael Gangolf, Fixed in [#21738](https://github.com/elementor/elementor/pull/21738) already

**Comment by mikeadksky** [comment]
Thank you for the quick response.  I have closed issue #21765.  I am new to
Elementor and GitHub Issues and will search more widely in the future
before opening a new issue.

Question... when will the fix be included in the Elementor I use when
logging in to the Elementor Cloud?

**Comment by m1ga** [comment]
I don't know that. I'm not using Elementor cloud. I just saw that this PR was merged some days ago (I used the search to find it) and since it is merged into "release/3.13.0" I would say it will be in the next release since the cloud version is at 3.13.0-cloud1. But that's just speculation since I can only look at the repo as you can too

**Comment by mikeadksky** [comment]
Okay, thanks.

**Comment by nicholaszein** [comment]
This issue was solved with Elementor 3.12! 😉
