### ISSUE TITLE
[Feature request] Custom CSS indicator

### ISSUE THREAD

**Issue by optimizewp** [elementor/elementor#2180]
It would be nice and really useful to have an indicator on widgets that have Custom CSS code added. If it comes the need to work on others project, it is not easy to discover the widgets with Custom CSS added.
Same thing if Custom CSS is added to the Page, in this case an indicator on the left editing sidebar could do the trick.
Thanks

**Comment by arielk** [comment]
@optimizewp This is definitely a nice idea.

Do you have any suggestion how to display the indicator on the element?

**Comment by optimizewp** [comment]
@arielk Using something like the FontAwesome CSS3 icon?

![elementor custom css indicator](https://user-images.githubusercontent.com/30923700/29226828-ca035574-7ed3-11e7-9d84-38c1b38441be.png)

**Comment by ramonztro** [comment]
Maybe the color for the controls could change like it does for Global Widgets. Normal controls are blue/gray, global are gold, css-customized are pink.

I'm not sure about acessibility on that take, though.

**Comment by jefechang** [comment]
+1

**Comment by jefechang** [comment]
Nothing? :)

**Comment by nickyhajal** [comment]
THis would make a huge difference!

**Comment by tomas-eklund** [comment]
Oh, I want this too! I think the Navigator would be a good place to put such an indicator. I think a faint indicator on all parent/ancestor elements and a distinctive indicator on the actual element containing the Custom CSS would be best. 

![image](https://user-images.githubusercontent.com/1409791/52049409-039fec80-254e-11e9-8ac3-c27577be844b.png)

In this mockup there is a gray CSS indicator on the second Section element. This tells you that there is a child element that has Custom CSS. By following the trail of gray indicators you can drill down to the actual element that has the Custom CSS. This element (the Slides element in this example) has an indicator with a more distinctive look. In my mockup I chose the Elementor-red:

![image](https://user-images.githubusercontent.com/1409791/52048985-f2a2ab80-254c-11e9-9960-455ed07799e5.png)

I've found that I very often need to use Custom CSS to implement designs that Elementor currently don't support. But when Elementor catches up it's much better to remove the Custom CSS and use the built in tools in Elementor. 

As time passes, memory fades and after waiting for a certain Elementor feature for years you will most certainly forget ever putting in that Custom CSS. [Airbear737](https://github.com/pojome/elementor/issues/5724) explained it very well, I think.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0 (More options coming soon in Pro v2.6)

Feel free to update

Thanks!

**Comment by ashkanahmadiphp** [comment]
Hi. it says that the issue was resolved in v 2.6, but I still don't see anything. Was this feature added?

**Comment by tomas-eklund** [comment]
I guess it was implemented, although the indicator is so subtle that I haven't noticed it until now (six months later) when I was actively looking for it.

![image](https://user-images.githubusercontent.com/1409791/78372992-42a25580-75ca-11ea-8682-58bbca474270.png)

That thin blue line to the right of the Slides element in the Navigator indicates that it has certain custom properties (such as Custom CSS). 

Hovering the blue line reveals an icon that, when clicked, will take you directly to the Custom CSS panel for the element.

![image](https://user-images.githubusercontent.com/1409791/78373465-ec81e200-75ca-11ea-8cd9-c3c1c2432d58.png)

I see now that it was mentioned in the blog post announcing the 2.6 release back in July 2019:
https://elementor.com/blog/introducing-icon-library/ 
https://elementor.com/blog/wp-content/uploads/sites/9/2019/07/navigator-in.mp4
