### ISSUE TITLE
✅ 🐞 Bug Report: Tabs Widget - When hovering on an active tab, the color return to default. (happens only on 3.12.0) - [ED-10305]

### ISSUE THREAD

**Issue by BarBoost** [elementor/elementor#21849]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When hovering on an active tab, the color change to default.

**Happen only on Elementor 3.12.0. Rolling back to the previous version solves the problem!**

### Steps to reproduce

Add a tabs widget and change the Normal/Hover/Active colors, then hover on any active tab and see the color return to the default green.
![tabs bug](https://user-images.githubusercontent.com/113690127/228840117-a4352866-3123-4886-9517-36cae68c5148.gif)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Irrelevant

**Comment by goulas12** [comment]
I have the same issue.

**Comment by Michaelgimii** [comment]
+1

**Comment by satomiao** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by lensbreak** [comment]
+1

**Comment by DanielsRogulis** [comment]
Same issue

**Comment by tomas-eklund** [comment]
The offending CSS rule seems to be in custom-frontend.min.css

```
:is(.elementor .elementor-element.elementor-widget-n-tabs>.elementor-widget-container>.e-n-tabs>.e-n-tabs-heading .e-n-tab-title,
    .elementor .elementor-element.elementor-widget-n-tabs>.elementor-widget-container>.e-n-tabs>.e-n-tabs-content .e-n-tab-title).e-normal:hover {
    background-color: var(--n-tabs-title-background-color-hover);
    background-image: none;
}
```

**Comment by brent-e** [comment]
Same issue for me on three sites, the active tab hover colour appears to be coming from the global accent colour. I'm using CSS to address it for now:

.e-active:hover {
    /* set to preferred colour */
    background-color: #696969 !important;
}

**Comment by Deep-Chill** [comment]
Any updates?

**Comment by Ulysses888** [comment]
Issue still present on v3.12.1 (free) and v3.12.2 (Pro)

**Comment by TotteAnnerbrink** [comment]
+1 Please fix asap

**Comment by dgodglue** [comment]
thx for the fix ! :)
