### ISSUE TITLE
⛔ 🐞 Bug Report: Cannot Save Template using the Top Bar (alpha) Experiment

### ISSUE THREAD

**Issue by bnovak99** [elementor/elementor#21862]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to save a page as a template from the editor I cannot enter a name for the template or save it.

### Steps to reproduce

1. From the Elelmentor editor click save template (from publish button)
2. Try to name template and save

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-spectralogic.com-30-03-2023.txt](https://github.com/elementor/elementor/files/11114309/system-info-spectralogic.com-30-03-2023.txt)

**Comment by m1ga** [comment]
maybe this one: https://github.com/elementor/elementor/pull/21804 ?

**Comment by avivu** [comment]
Hi @bnovak99,

I can see that you are working with the new Editor Top Bar. Important to know that it's an Alpha experiment and not all functionality is working at this point.

If you will deactivate this experiment, the Save as template will work as expected.
Thank you!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.13.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
