### ISSUE TITLE
✅ 🐞 Cursor in mega menu item is not pointer

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#21880]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi team

If we put Open On on hover in megamenu, if the user puts the mouse on the menu item to display the megamenu, the cursor works normally, which is not interesting at all. 

### Steps to reproduce

1. In Megamenu, first enable Dropdown Content for one of the items.
2. In the settings of this widget, set Open On to hover.
3. On the front end, hover the mouse over the desired item to bring up the mega menu.

When the mouse is placed on the item, the cursor is normal. While it should be in the form of a pointer.

This is an important and very simple matter. Please fix it as soon as possible. thanks team❤

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

-

**Comment by 79ho3ein** [comment]
+1

This is not actually a bug, maybe it was forgotten. But I agree with you. The current situation does not convey a good feeling to the users.

**Comment by erawatech** [comment]
I was able to patch this with some css:
`span.e-n-menu-item-title-text:hover {
    cursor:pointer;
}`

It does **not** work if you leave off the span, despite Elementor's interface complaining about it being "overqualified".

**Comment by arturfalgowski** [comment]
I know you posted it many months ago but maybe somebody will search resolve for this same problem. I have issue:
**general setting (in elementor editor) > Customized CSS**  

```
.e-n-menu-title-text {
    cursor: pointer!important;
}
```

![image](https://github.com/elementor/elementor/assets/149479131/386b040a-ea95-401a-aae3-e7cb126fc9ee)

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
