### ISSUE TITLE
✅ 🐞 Bug Report: Hide editor will push content to left side - [ED-11807]

### ISSUE THREAD

**Issue by iqbalmauludy** [elementor/elementor#21884]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi Elementor, I'm using the latest version. Currently I activated the editor top bar & menu.
When I hide the editor elements, the content will also shift to the left, please watch the video.

https://www.loom.com/share/04b18d4f81e549afb1645ab8ea712f9e

### Steps to reproduce

--

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

--

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
