### ISSUE TITLE
✅ 📊 🐞 Bug Report: Infinite Loading of Header after adding New Mega Menu Experiment - [ED-10424]

### ISSUE THREAD

**Issue by TowyTowy** [elementor/elementor#21903]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have encountered a bug that causes the header to infinitely load after adding the new Mega Menu experiment in Elementor. This issue occurred unexpectedly possibly after I added additional CSS and closed Elementor for the night. The following day, when I tried to reopen Elementor, the header did not load and remained stuck in an infinite loading loop.

I have attempted to resolve the issue by trying all the recommended fixes available on the Elementor documentation, but none of them seem to have worked. The problem persists even after disabling all third-party plugins and clearing my browser cache.

Some but not all steps taken to try and resolve the issue:

Disabled all third-party plugins.
Cleared browser cache and cookies.
Tried to access Elementor from a different browser and device.
Tried to access Elementor from an incognito window.
Tried to access Elementor in safe mode.
Reinstalled Elementor plugin.
Increased the server's PHP limits.
Exported it as template then imported it to another website, and it still doesn't load.
Checked logs, there's none.

### Steps to reproduce

1. Add the new Mega Menu experiment in Elementor.
2. Add a good bit of additional CSS to the website?
3. Close Elementor and reopen it

Since the steps to reproduce are unclear, I'd be more than willing to provide my template file of the header if needed. I really want this working again soon, so I can continue my work on one of my client's website.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

WordPress version: 6.2
Elementor version: 3.12.0

**Comment by jgarcianewemage** [comment]
Also when enabling Nested elements, crashes into the "enable safe mode" screen

**Comment by TowyTowy** [comment]
https://github.com/elementor/elementor/issues/21934
Same issue as this.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved with the release of Elementor v3.23.0! 🥳 

The time to interaction should improve by 60%-98%, and performance overall should be better. For a full breakdown please read [this article](https://developers.elementor.com/elementor-3-23-developers-update/#:~:text=Performant%20Nested%20Elements%20In%20the%20Editor).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
