### ISSUE TITLE
✅ 🐞 Bug Report: Can't see highlighted text in the editor when dark mode is enabled

### ISSUE THREAD

**Issue by formgarten** [elementor/elementor#21935]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The new ui update of elementor 3.12 affects the backend input fields using the dark mode. When marking text the marked part isn't visible at all. Before version 3.12 this text part was highlighted in typical blue color. I contacted elementor support and they told me that they would add this to the list as a feature request. I thought I couldn't hear right! Feature request! This type of processing is used several times a day. The same words are highlighted on the screenshot. Old UI on the left, new UI on the right.
<img width="617" alt="CleanShot 2023-03-30 at 10 27 12@2x" src="https://user-images.githubusercontent.com/55788402/230000970-ab9c4b7a-e42b-41aa-91d4-d565627cddba.png">

### Steps to reproduce

1) clean wp installation
2) install elementor free plugin - nothing more is needed
3) change to dark mode (don't know if there's an issue with light mode, too)
4) change to editing mode in elementor, try to mark some text inside input fields

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.18
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://allfinanz.netfonds-master.contiago.de
	Home URL: https://allfinanz.netfonds-master.contiago.de
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Upgrade Swiper Library: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Inaktiv
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Inaktiv
	Nested Elements: Standardmäßig deaktiviert
	Lazy Load Background Images: Standardmäßig deaktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menü: Standardmäßig deaktiviert


				

````

</details>

**Comment by nicholaszein** [comment]
Closing this issue as it was already solved.
