### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [elementor/elementor#21987]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by nicholaszein** [comment]
Hello @igibek! 

Thank you for reaching out! 🙏 

We take security vulnerabilities very seriously, and we want to ensure they are handled responsibly and solved privately. We have a team dedicated to handling this type of report, and the best place to do it is through our [Bug Bounty Program on Bugcrowd](https://bugcrowd.com/elementor) as indicated on our [Trust Center](https://elementor.com/trust/).

Please submit your findings on Bugcrowd so we can take this forward!

Trust Center: https://elementor.com/trust/
Bug Bounty Program on Bugcrowd: https://bugcrowd.com/elementor

Thank you very much! 🙏
