### ISSUE TITLE
✅ 🔗 🐞 Bug Report: Hard to click on responsive icon in new Elementor Editor

### ISSUE THREAD

**Issue by minty-owen** [elementor/elementor#22073]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The clickable area of the responsive modus icon is on icon itself and not on the container like the rest of the options.

### Steps to reproduce

Have Elementor

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello there @minty-owen!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.12.2**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
