### ISSUE TITLE
✅ 🐞 Bug Report: AI Comtinuity - Wrong language when changing text again

### ISSUE THREAD

**Issue by m1ga** [elementor/elementor#22113]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When testing the new AI feature in 3.13.0 beta 1 the text will change it's language when you open it again and press the "make it shorter" button.

### Steps to reproduce

https://user-images.githubusercontent.com/4334997/233021419-9b393943-06cb-4e87-a966-4184fbe9e490.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


== Server Environment ==
Operating System: Linux
Software: Apache/2.4.57 (Fedora Linux)
MySQL version: MariaDB Server v10.5.18
PHP Version: 8.1.17
PHP Memory Limit: 128M
PHP Max Input Vars: 1000
PHP Max Post Size: 400M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.2
Site URL: http://localhost/~miga/wp
Home URL: http://localhost/~miga/wp
WP Multisite: No
Max Upload Size: 400 MB
Memory limit: 40M
Max Memory limit: 256M
Permalink Structure: /%postname%/
Language: en-US
Timezone: Europe/Berlin

== Theme ==
Name: Astra
Version: 4.1.3
Author: Brainstorm Force
Child Theme: No


== Active Plugins ==

Elementor
Version: 3.13.0-beta1
Author: Elementor.com
````

</details>

**Comment by perks98** [comment]
I've just quickly tried this new AI tool on that beta for a heading widget. It did a good title but when you change the tone it changed it from a short heading sentence to a big long paragraph and you can't go back to the previous output which I can see being an issue for people.

**Comment by nicholaszein** [comment]
Hello @m1ga! 

Thank you for submitting your issue! 🙏 

Best regards

**Comment by nicholaszein** [comment]
> I've just quickly tried this new AI tool on that beta for a heading widget. It did a good title but when you change the tone it changed it from a short heading sentence to a big long paragraph and you can't go back to the previous output which I can see being an issue for people.

Hi @perks98,

this would be a good feedback to add to the Beta Discussion, or submit a new Bug Report! 😉

**Comment by nicholaszein** [comment]
Hi @m1ga!

I've been doing some tests about this issue, and checked our internal changelog, and it seems it has been fixed for some time now.

Here's a video of it working as expected:

https://github.com/elementor/elementor/assets/113993460/e1548aaf-7551-4ac7-a9a5-eec0061baedc

In the video, I ask Elementor AI to write a 3 paragraph text in Brazilian Portuguese about a dog called Teddy that loves to play ball with his owner.

The result was consistent after requesting to make the text shorter.

For this reason, I'm closing this issue as Solved.

If you experience this problem again in the future, please submit a new issue.

Kind regards.

Nick
