### ISSUE TITLE
❌ test

### ISSUE THREAD

**Issue by Kartheeka1985** [elementor/elementor#22155]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

test

### Steps to reproduce

test

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

test

**Comment by nicholaszein** [comment]
Hello @Kartheeka1985, 

please avoid posting empty bug reports without following our guidelines.
