### ISSUE TITLE
⛔ 🐞 Bug Report: Mega Menu if add 3 Level Inner will not open from level 3+

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#22175]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,
I need create Mega Menu with 3 Level Inner.
Level 1: Menu Item 1 - Menu Item 2 (Dropdown Content enable) - Menu Item 3
Level 2 (From Menu Item 2 of Level 1): Menu Item 1 (Dropdown Content enable) - Menu Item 2 - Menu Item 3
Level 3 (From Menu Item 1 of Level 2): Menu Item 1 - Menu Item 2 - Menu Item 3 (Dropdown Content enable)

Issue we got: When we hover (click) on "Menu Item 1 (Dropdown Content enable)" of Level 2 the content don't show

### Steps to reproduce

1. Create a Page, Edit with Elementor
2. Add Mega Menu and Config as above
3. When we hover (click) on "Menu Item 1 (Dropdown Content enable)" of Level 2 the content don't show

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.19
	PHP Version: 8.2.1
	PHP Memory Limit: 64M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://domain.com
	Home URL: https://domain.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 1024M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Ho_Chi_Minh
	Admin Email: admin@email.com
	Debug Mode: Inactive

== Theme ==
	Name: Gấu Theme
	Version: 1.0.10
	Author: 🐻
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0

== Active Plugins ==
	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	LiteSpeed Cache
		Version: 5.4
		Author: LiteSpeed Technologies


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active


== Log ==

== Elementor - Compatibility Tag ==

== Elementor Pro - Compatibility Tag ==
				

````

</details>

**Comment by datverse** [comment]
![mega-menu-issue-1](https://user-images.githubusercontent.com/2121900/233926762-4827ab9a-3425-4ec0-a9a4-1fa398a6afb5.gif)

**Comment by nicholaszein** [comment]
Hello @datverse,

Thank you for submitting your issue! 🙏 

### ⛔ After reviewing your report, we concluded that what you are trying to achieve is not supported.

Currently, you can't add Menu widgets inside Menu contents with content of their own. In other words, you can't add more than one level of content (no sub-menus inside sub-menus).

If you think this should be a feature supported by Elementor, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request) following these guidelines. 😉 


Kind regards
