### ISSUE TITLE
⛔ 🛟 🐞 Bug Report: Paragraph text is overlapping

### ISSUE THREAD

**Issue by larafalcao99** [elementor/elementor#22198]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

i was editing a text on elementor yesterday and out of nowhere the text started overlapping. I tried changing margins and everything but it wouldn't work. So everytime the text should jump to another line it will stay on the same line and start overlapping. I have tried to uninstall the elementor plugin and reinstall and that didn't work. 
![text overlapping](https://user-images.githubusercontent.com/131825183/234416663-05d76264-1560-409b-8f80-bd486b9a26ca.png)

### Steps to reproduce

1) create a new page 
2) select elementor canvas on layout
3) create a widget
4)drag a text box into the widget
5) start typing
6) when you fill up the first line and the text should continue on the next line it starts overlapping

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.12
	PHP Version: 8.0.28
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://clinicanarede.com
	Home URL: https://clinicanarede.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Admin Email: larafalcao99@hotmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.3
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Hostinger
		Version: 1.3.0
		Author: Hostinger

	LiteSpeed Cache
		Version: 5.4
		Author: LiteSpeed Technologies


== Experimentos do Elementor ==
	Saída DOM otimizada: Ativo por padrão
	Carregamento melhorado de recursos: Ativo por padrão
	Carregamento melhorado de CSS: Ativo por padrão
	Ícones da fonte inline: Ativo por padrão
	Melhorias na acessibilidade: Ativo por padrão
	Pontos de quebra adicionais personalizados: Ativo por padrão
	admin_menu_rearrangement: Inativo por padrão
	Flexbox Container: Ativo
	Atualize a biblioteca Swiper: Ativo por padrão
	Grid Container: Inativo por padrão
	Editor Top Bar: Inativo por padrão
	Landing Pages: Ativo por padrão
	Elementos aninhados: Ativo por padrão
	Imagens com carregamento gradual: Inativo por padrão


== Registo ==
	
Log: showing 5 of 52023-04-25 18:08:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0-dev3',
)]
2023-04-25 18:08:04 [info] elementor::elementor_updater Started 
2023-04-25 18:08:04 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-25 18:08:04 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-25 18:08:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0-dev3',
)]



== Elementor - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @larafalcao99,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

It seems you forgot to set a line-height for the text on your Site Settings > Typography styles. Please review your settings and set a line-height accordingly.

Check this article: https://elementor.com/help/how-do-i-set-global-fonts-and-colors/

Also, it's important to note that you are using the **_Elementor Beta (Developer Edition)_** plugin. This plugin shouldn't be used on production websites, as it is meant to be used by 3rd-party developers to test their plugins against Elementor's new features.
Please deactivate the plugin and [Rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) Elementor to the latest stable version.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
