### ISSUE TITLE
✅ 🐞 Bug Report: PHP Errors in Ajax Response WooCommerce cart fragments - [ED-10763]

### ISSUE THREAD

**Issue by wpeasy** [elementor/elementor#22199]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm not sure which version this started in. 

I have Query Monitor installed. and it reports the following. It doesn't appear to affect the operation though.

````
Object
component
: 
"Plugin: elementor-pro"
file
: 
"wp-content/plugins/elementor-pro/modules/woocommerce/module.php"
key
: 
"3ef44e7c7c7743db3c61e372d9d58dde"
line
: 
381
message
: 
"Undefined array key 1"
stack
: 
(9) ['ElementorPro\\M\\W\\Module->ElementorPro\\M\\W\\{closure}()', 'Elementor\\DB->iterate_data()', 'Elementor\\DB->iterate_data()', 'Elementor\\DB->iterate_data()', 'Elementor\\DB->iterate_data()', 'ElementorPro\\M\\W\\Module->get_fragments_in_document()', 'ElementorPro\\M\\W\\Module->get_all_fragments()', 'ElementorPro\\M\\W\\Module->menu_cart_fragments()', "do_action('wp_ajax_elementor_menu_cart_fragments')"]
type
: 
"warning"
[[Prototype]]
: 
Object
````

### Steps to reproduce

Load a page with WooCOmmerce

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.42
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.platinumshowcase.com.au
	Home URL: https://www.platinumshowcase.com.au
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 128M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Brisbane
	Admin Email: info@platinumshowcase.com.au
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Anti-Spam by CleanTalk
		Version: 6.8
		Author: СleanTalk <welcome@cleantalk.org>

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Envato Elements
		Version: 2.0.12
		Author: Envato

	FluentAuth - Auth Security Plugin
		Version: 1.0.4
		Author: Fluent Auth Team

	FluentSMTP
		Version: 2.2.4
		Author: FluentSMTP & WPManageNinja Team

	JetElements For Elementor
		Version: 2.6.9
		Author: Crocoblock

	JetEngine
		Version: 3.1.4
		Author: Crocoblock

	JetMenu
		Version: 2.3.0
		Author: Crocoblock

	JetSmartFilters
		Version: 3.1.1
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.21
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.4
		Author: Crocoblock

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	Query Monitor
		Version: 3.12.1
		Author: John Blackbourn

	Rank Math SEO
		Version: 1.0.112
		Author: Rank Math

	WooCommerce
		Version: 7.6.0
		Author: Automattic

	WooCommerce Australia Post Shipping
		Version: 2.5.0
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.3.0
		Author: WooCommerce

	WPCodeBox
		Version: 1.4.1
		Author: WPCodeBox

	WP Crontrol
		Version: 1.15.2
		Author: John Blackbourn & crontributors

	WPGet Common
		Version: 0.0.1
		Author: Alan Blair

	WP Rocket
		Version: 3.13.1
		Author: WP Media

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Elements Usage ==
	
	archive : 2
		heading : 2
		icon-list : 1
		jet-listing-grid : 1
		jet-smart-filters-range : 1
		posts : 1
		text-editor : 2
		theme-archive-title : 1
		wp-widget-categories : 1
		wp-widget-recent-posts : 1
		wp-widget-tag_cloud : 1
	footer : 1
		heading : 3
		image : 1
		nav-menu : 2
		text-editor : 2
	header : 2
		container : 1
		jet-mobile-menu : 2
		nav-menu : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 2
	page : 5
		accordion : 1
		button : 2
		form : 2
		heading : 169
		html : 1
		icon : 18
		image : 8
		jet-listing-dynamic-field : 1
		login : 1
		menu-anchor : 1
		spacer : 1
		text-editor : 17
	popup : 1
		divider : 1
		form : 1
		heading : 1
		html : 1
	product : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 2
		woocommerce-product-upsell : 1
	section : 4
		heading : 4
		image : 2
		social-icons : 1
		testimonial-carousel : 1
		text-editor : 1
	widget : 0
		divider : 1
		nav-menu : 1
	wp-post : 1
		heading : 2
		icon-list : 2
		text-editor : 2
	wp-page : 8
		button : 2
		container : 17
		form : 1
		heading : 18
		icon-box : 1
		image : 1
		jet-listing-grid : 2
		jet-smart-filters-pagination : 1
		jet-smart-filters-radio : 1
		login : 1
		spacer : 1
		text-editor : 11
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
	product-archive : 1
		heading : 1
		jet-listing-grid : 1
		jet-smart-filters-pagination : 1
		woocommerce-breadcrumb : 1
	error-404 : 1
		divider : 1
		heading : 3
		search-form : 1


== Settings ==
	
	cpt_support: post, page, jet-menu, jet-woo-builder
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	css_print_method: internal
	unfiltered_files_upload: 1
	font_display: fallback
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 77
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 392023-04-03 06:49:46 [info] elementor::elementor_updater Started 
2023-04-03 06:49:46 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-03 06:49:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 06:49:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-03 06:49:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-15 05:46:55 [info] elementor-pro::elementor_pro_updater Started 
2023-04-15 05:46:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-15 05:46:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-15 05:46:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.2',
)]
2023-04-26 07:00:33 [info] elementor::elementor_updater Started 
2023-04-26 07:00:33 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-26 07:00:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-26 07:00:35 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-26 07:00:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-26 07:23:01 [info] elementor-pro::elementor_pro_updater Started 
2023-04-26 07:23:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-26 07:23:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-26 07:23:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-26 07:23:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-26 07:23:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]

JS: showing 1 of 1JS: 2023-04-19 02:29:50 [error X 1][https://www.platinumshowcase.com.au/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view17584") has already been destroyed and cannot be used. 

PHP: showing 2 of 2PHP: 2023-04-20 15:07:04 [warning X 1][/home/platinums/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-26 07:35:22 [warning X 24][/home/platinums/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::381] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Envato Elements: Compatible
	JetElements For Elementor: Incompatible
	JetTabs For Elementor: Incompatible
	JetWooBuilder For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Compatible
	JetElements For Elementor: Incompatible
	JetTabs For Elementor: Incompatible
	JetWooBuilder For Elementor: Incompatible
				
````

</details>

**Comment by HuthDev** [comment]
Have the same issue

**Comment by nicholaszein** [comment]
Hello, @wpeasy! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by splaquet** [comment]
having similar issue:

`Object
component
: 
"Plugin: elementor-pro-3.13.0-beta2"
file
: 
"wp-content/plugins/elementor-pro-3.13.0-beta2/modules/woocommerce/module.php"
key
: 
"df7aca1c9b21c14705ab1545e5eb5c65"
line
: 
381
message
: 
"Undefined array key 1"
stack
: 
Array(11)
0
: 
"ElementorPro\\M\\W\\Module->ElementorPro\\M\\W\\{closure}()"
1
: 
"Elementor\\DB->iterate_data()"
2
: 
"Elementor\\DB->iterate_data()"
3
: 
"Elementor\\DB->iterate_data()"
4
: 
"Elementor\\DB->iterate_data()"
5
: 
"Elementor\\DB->iterate_data()"
6
: 
"Elementor\\DB->iterate_data()"
7
: 
"ElementorPro\\M\\W\\Module->get_fragments_in_document()"
8
: 
"ElementorPro\\M\\W\\Module->get_all_fragments()"
9
: 
"ElementorPro\\M\\W\\Module->menu_cart_fragments()"
10
: 
"do_action('wp_ajax_elementor_menu_cart_fragments')"
length
: 
11
[[Prototype]]
: 
Array(0)
type
: 
"warning"
[[Prototype]]
: 
Object`

**Comment by sixgunnar** [comment]
Same issue here, probably after updating 2 weeks ago.

**Comment by datascientistgonzo** [comment]
same problem here with Elementor 3.13.2 and Elementor Pro 3.13.1:

component
: 
"Plugin: elementor-pro"
file
: 
"wp-content/plugins/elementor-pro/modules/woocommerce/module.php"
key
: 
"39efcb69327063e42ea8c4c1feddea7c"
line
: 
381
message
: 
"Undefined array key 1"
stack
: 
Array(11)
0
: 
"ElementorPro\\M\\W\\Module->ElementorPro\\M\\W\\{closure}()"
1
: 
"Elementor\\DB->iterate_data()"
2
: 
"Elementor\\DB->iterate_data()"
3
: 
"Elementor\\DB->iterate_data()"
4
: 
"Elementor\\DB->iterate_data()"
5
: 
"Elementor\\DB->iterate_data()"
6
: 
"Elementor\\DB->iterate_data()"
7
: 
"ElementorPro\\M\\W\\Module->get_fragments_in_document()"
8
: 
"ElementorPro\\M\\W\\Module->get_all_fragments()"
9
: 
"ElementorPro\\M\\W\\Module->menu_cart_fragments()"
10
: 
"do_action('wp_ajax_elementor_menu_cart_fragments')"
length
: 
11
[[Prototype]]
: 
Array(0)
type
: 
"warning"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()

**Comment by datascientistgonzo** [comment]
no Jet plugins installed

**Comment by wpeasy** [comment]
I installed all updates and disabled all Crocobloc plugins. I had to re-enable JetEengine because the product grids are using JE Custom Queries.

What I have found. As soon as I enable Jet Engine I see the error reported. From then, each time I "Add to cart" the error is reported.

When I get some free time I'll set up a page with a standard product display grid, disable JetEngine and try again.

**Comment by nicholaszein** [comment]
Hi @datascientistgonzo, and @wpeasy!

Thank you for your feedback. We are still investigating the issue and will update you when we have a solution.

Kind regards

**Comment by datascientistgonzo** [comment]
Today the error occured although I have neither JetEngine nor "Query Monitor" installed

**Comment by KnowYourGrow** [comment]
Yup...I have neither Jet or QM and my log is slammed with the error. Hoping to see this resolved soon. Suppose I could just rollback, but that's annoying 😉

**Comment by splaquet** [comment]
i stumbled upon this post when I saw a SWARM of these warning messages fly through.  ...but, I also stumbled upon a fix (at least for my end).

i was having issues with crocoblock checkout on various device sizes (but not desktop).  when i discovered the issue, i also discovered that i couldn't easily fix w/ crocoblock checkout.  So, i added in Elementor checkout.

after i made everything look perfect, i went to test out.  BUT, when i tried selecting the shipping method, the radio button wouldn't select/toggle on.

i realized that i had some of the original crocoblock elements on the page, but ALL hidden via responsive toggles.

i deleted all crocoblock widgets, saved... and shipping toggles worked AND error message went away.

while i realize this might not work for everyone, hopefully it helps out at least 1 person 😉

**Comment by splaquet** [comment]
Anyone using WooCommerce Bundles plugin?

I notice that this error comes through the log when looking at a Bundle page, but not on Simple or Variation Product page.

...and, I'm also now realizing that the layout on my Bundle pages are all sorts of whack. (see screenshots, as the bundle seems to force-slide the front end page into some type of Flex Row)

<img width="1181" alt="image" src="https://github.com/elementor/elementor/assets/6146508/c21e41d0-f833-4f12-9016-216fc224eed4">
<img width="1048" alt="image" src="https://github.com/elementor/elementor/assets/6146508/a470d294-b534-4aeb-9dad-128b2b89f39d">

...but the Bundle page looks 100% normal in the builder
<img width="1287" alt="image" src="https://github.com/elementor/elementor/assets/6146508/766b218f-6375-4a68-95d8-fbe73ca334fb">

**Comment by Sophie-2e** [comment]
Same here, I don't have woocommerce bundles, jet engine, or query monitor. Using the latest version of Elementor and Elementor Pro with Woocommerce on Hello Elementor theme and this error still floods my logs too for weeks now. The bug has been reported to your Customer Support Tier 3. Your team also noticed the issue on their side and promise to work on it. Please fix it, thank you 🙌
