### ISSUE TITLE
⛔ 🛟 🐞 Bug Report: New album appear on my gallery and theyre not mine, need help to remove them 

### ISSUE THREAD

**Issue by Listoa** [elementor/elementor#22210]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Some entries appear on my account and create pirate albums on my gallery, it is not me who integrate them on my site, I delete them and they reappear. 

### Steps to reproduce

![Capture d’écran (46)](https://user-images.githubusercontent.com/131896634/234634367-c3290bc2-d1ca-4b18-b3f0-e09f72dd8c7d.png)
![Capture d’écran (47)](https://user-images.githubusercontent.com/131896634/234634379-9f0a2ef5-ba39-46f5-a2a8-ca1c6695c1ff.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<html><body>
<h3 class="wp-heading-inline">Información del sistema</h3>
			<div>	<div class="elementor-system-info-section elementor-system-info-server">
		

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.19 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 3072M |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 3072M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | There are some writing permissions issues with the following directories/files: 		 - .htaccess file |  
Elementor Library: | Connected |  

</div></div>
</body>
</html>Información del sistema

			
			
				Server Environment
					
					
			

			
			
						
				Operating System:
					Linux
					
			

						
				Software:
					LiteSpeed
					
			

						
				MySQL version:
					MariaDB Server v10.5.19
					
			

						
				PHP Version:
					7.4.33
					
			

						
				PHP Memory Limit:
					3072M
					
			

						
				PHP Max Input Vars:
					5000
					
			

						
				PHP Max Post Size:
					3072M
					
			

						
				GD Installed:
					Yes
					
			

						
				ZIP Installed:
					Yes
					
			

						
				Write Permissions:
					There are some writing permissions issues with the following directories/files:
		 - .htaccess file
					
			

						
				Elementor Library:
					Connected
					
			

						
		

			
			
				WordPress Environment
					
					
			

			
			
						
				Version:
					6.2
					
			

						
				Site URL:
					https://lisetoa.com
					
			

						
				Home URL:
					https://lisetoa.com
					
			

						
				WP Multisite:
					No
					
			

						
				Max Upload Size:
					3 GB
					
			

						
				Memory limit:
					40M
					
			

						
				Max Memory limit:
					3072M
					
			

						
				Permalink Structure:
					/%postname%/
					
			

						
				Language:
					es
					
			

						
				Timezone:
					0
					
			

						
				Admin Email:
					info@lisetoa.com
					
			

						
				Debug Mode:
					Inactive
					
			

						
		

			
			
				Theme
					
					
			

			
			
						
				Name:
					Hello Elementor
					
			

						
				Version:
					2.7.1
					
			

						
				Author:
					Elementor Team
					
			

						
				Child Theme:
					No
					Si quieres modificar el código fuente de tu tema, te recomendamos utilizar un [tema hijo](https://go.elementor.com/wordpress-child-themes/).
			

						
		

			
			
				User
					
					
			

			
			
						
				Role:
					administrator
					
			

						
				WP Profile lang:
					es_ES
					
			

						
				User Agent:
					Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
					
			

						
		

			
			
				Active Plugins
					
					
			

			
			
							
					Converter for Media - 5.8.5
						By [matt plugins](https://url.mattplugins.com/converter-plugin-author-link)
						
				

								
					[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.13.0-dev2
						By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)
						
				

								
					[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1
						By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)
						
				

								
					[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.12.1
						By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)
						
				

								
					[GTranslate](https://gtranslate.io/?xyz=998) - 2.8.62
						By [Translate AI Multilingual Solutions](https://gtranslate.io/)
						
				

								
					[LiteSpeed Cache](https://www.litespeedtech.com/products/cache-plugins/wordpress-acceleration) - 5.3.3
						By [LiteSpeed Technologies](https://www.litespeedtech.com/)
						
				

								
					[Smash Balloon Instagram Feed](https://smashballoon.com/instagram-feed) - 2.9
						By [Smash Balloon](https://smashballoon.com/)
						
				

							
		

			
			
				Uso de los elementos[Recalculate](https://lisetoa.com/wp-admin/admin.php?page=elementor-system-info&elementor_usage_recalc=1&_wpnonce=650997b9c4#elementor-usage-recalc)
					
					
			

			
			
						
				
					
Entrada ( 15 )	Editor de texto: 21
Encabezado: 26
Espaciador: 33
Gallery: 21
Página ( 6 )	Botón: 5
Editor de texto: 13
Encabezado: 15
Espaciador: 9
Form: 1
Icono: 7
Imagen: 17
Instagram Feed: 1
Portfolio: 2
Theme - Header ( 1 )	Site Logo: 1
WordPress Menu: 1
Theme - Footer ( 1 )	Editor de texto: 1
Encabezado: 4
Espaciador: 2
Form: 1
GTranslate: 1
Iconos sociales: 1

				
			

						
		

			
			
				Ajustes
					
					
			

			
			
						
				
					
cpt_support	post, page
allow_tracking	yes

				
			

						
		

			
			
				Features
					
					
			

			
			
						
				Custom Fonts:
					2
					
			

						
				Custom Icons:
					0
					
			

						
		

			
			
				Integrations
					
					
			

			
			
						
				
					
recaptcha_v3	Active

				
			

						
		

			
			
				Experimentos de Elementor
					
					
			

			
			
						
				
					
Salida del DOM optimizada: 	Activo
Carga de recursos mejorada: 	Activo
Carga de CSS mejorada: 	Activo
Fuentes de iconos integradas: 	Activo
Mejoras de accesibilidad: 	Activo
Puntos de ruptura personalizados adicionales: 	Activo
admin_menu_rearrangement: 	Inactivo por defecto
Contenedor Flexbox: 	Activo
Actualizar la librería Swiper: 	Activo
Container Grid: 	Inactivo por defecto
Default to New Theme Builder: 	Activo por defecto
Cabecera y pie de página del tema Hello: 	Activo
Barra superior del editor: 	Activo
Páginas de destino: 	Activo
Elementos anidados: 	Activo
Carga diferida de imágenes de fondo: 	Activo
Page Transitions: 	Activo por defecto
Notes: 	Activo por defecto
Loop: 	Activo por defecto
Form Submissions: 	Activo por defecto
Scroll Snap: 	Activo por defecto
Menu: 	Inactivo por defecto

**Comment by nicholaszein** [comment]
Hello @Listoa,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
