### ISSUE TITLE
⛔ 📚 🐞 Bug Report: Responsive color control issue.

### ISSUE THREAD

**Issue by rickhelmi** [elementor/elementor#22255]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

1. The color picker will be gone after changing the device.
2. the selected color won't be applied to smaller devices.
<img width="365" alt="Screenshot 2023-05-01 at 11 42 07 AM" src="https://user-images.githubusercontent.com/88645201/235427811-b29fe1ac-8db2-499f-9f89-46b3b17f583d.png">

### Steps to reproduce

1) create a custom responsive color control
2) change the editor on the editor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.55 (Unix) OpenSSL/1.1.1f
	MySQL version: Ubuntu 20.04 v10.3.38
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://hooman.artbees.team
	Home URL: https://hooman.artbees.team
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: hooman@artbees.net
	Debug Mode: Active

== Theme ==
	Name: JupiterX
	Version: 3.1.0
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.1.4
		Author: WP Engine

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Jupiter X Core
		Version: 3.1.0
		Author: Artbees


== Elements Usage ==
	
	footer : 2
		icon-list : 1
		image : 1
		raven-heading : 1
		text-editor : 2
	header : 7
		container : 10
		image : 1
		raven-advanced-nav-menu : 3
		raven-button : 2
		raven-nav-menu : 1
		raven-search-form : 2
		raven-site-logo : 3
	page : 8
	section : 3
		container : 5
		heading : 1
		text-editor : 1
	wp-post : 13
		container : 3
		divider : 5
		google_maps : 1
		icon-box : 6
		image-gallery : 1
		raven-button : 12
		raven-call-to-action : 1
		raven-form : 1
		raven-heading : 132
		raven-icon : 3
		raven-image : 13
		shortcode : 1
		sidebar : 1
		spacer : 24
		text-editor : 72
	wp-page : 25
		container : 10
		heading : 3
		image : 2
		raven-advanced-posts : 1
		raven-photo-album : 1
		raven-social-share : 1
		raven-testimonial-carousel : 1
		testimonial-carousel : 1
	error-404 : 0
		container : 10


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Editor Top Bar: Inactive
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @rickhelmi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- You are probably writing your custom color control wrong. Please review your code and follow the instructions from our Developer API.
https://developers.elementor.com/docs/editor-controls/responsive-control/ 

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind regards
