### ISSUE TITLE
✅ 🐞 Bug Report: Beta 3.13 : Custom unit inheritance problem in mobile mode - [ED-10282]

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#22289]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the video below, I set the number of columns on the desktop 1fr 1fr 1fr. Then I view the tablet mode and there is no problem. But when I see the mobile mode, the container looks broken. Because the default value of mobile is 1. **while it should be 1fr. Because I enabled the custom unit on the desktop and it should be inherited.**

### Steps to reproduce

https://user-images.githubusercontent.com/103376243/235671995-e1e18e5c-ac1f-4b3e-8a9e-ad3325c381ca.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

System information does not help in this case. But let me know if needed.

**Comment by nicholaszein** [comment]
Hi @Joliamendi! 

Thank you for the feedback! 🙏 

I see we might have an issue here, and I'm not sure this one will have a fix right away. Currently, we can't predict what will be set as a custom unit, but we need the columns to be `1fr` on mobile, which they are as you saw (the number `1`), but the unit should have been switched back to the normal value of `fr` with the slider.

We will investigate and see what we can do in a future release. Please be patient. And thank you for reporting this! You rock! 💪 

Best regards

**Comment by nicholaszein** [comment]
Hey @Joliamendi!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
