### ISSUE TITLE
✅ 🐞 Bug Report: Beta 3.13 : Drag and drop in the grid is very difficult.

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#22287]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Drag and drop in a grid is very difficult. Without using the structure panel, this is almost impossible. Please see the video below. 

### Steps to reproduce

https://user-images.githubusercontent.com/103376243/235659967-37dafe33-f9e8-4c44-bded-f88b9d9438bf.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

System information does not help in this case. But let me know if needed.

**Comment by nicholaszein** [comment]
Hi @Joliamendi!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **vX3.13.0**! 🥳 
You can now drag & drop elements inside the grid in a much easier way.

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
