### ISSUE TITLE
🐞 Bug Report: Loop builder is caching Ajax response incorrectly

### ISSUE THREAD

**Issue by chrisringrose** [elementor/elementor#22320]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We're using the loop builder to create a unique way to showcase an accordion collapsable list of businesses (which are a custom post type). You can [see here](https://dev.see-net.ca/businesses/), the listings that say "The Website" are the new version not loading from cache, and they update any time I make changes to the shortcode which outputs this info.

But as you go down to about the 15th business (whenever the loop builder stops loading on page PHP load, and loads more via Ajax), all the remaining posts load from browser cache. If the shortcode is modified, the Ajax results for the loop builder are loaded from cache, instead of properly loading the new output.

We have no caching plugins installed right now. This must be an Elementor caching issue related to loading posts via Ajax and the loop builder?

### Steps to reproduce

1. Create an archive template, and on this, add the Loop Grid widget
2. Make the loop builder consist of an Accordion widget, with the Description for the item to be a shortcode
3. Make the loop builder have "Items Per Page" set to 999
4. Make Pagination set to Infinite Scroll
5. Have enough items that will show up on your archive so that the loop builder will load more via Ajax (it seems to ignore the "Items Per Page" value entirely.)
6. Make this shortcode output post details, including `get_the_content()`, `get_post_meta(get_the_ID(), 'A_Custom_Meta_Field', true)`

The archive page should show the results in a series of accordions, and the content and details are loading correctly via the shortcode ... So far so good...

7. Make a change to the shortcode now, so the output HTML is a bit different

... Now when you get further down the list on the archive page, and results are loaded via Ajax and not PHP, the content is loading from browser cache now. The changes made to your shortcode are not reflected on the items lower down on the list.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	PHP Version: 8.2.4
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://dev.see-net.ca
	Home URL: https://dev.see-net.ca
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: GAVAMEDIA®
	Version: 2021
	Author: GAVAMEDIA®
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

== Active Plugins ==
	Defender
		Version: 3.10.1
		Author: WPMU DEV

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	GA Google Analytics
		Version: 20230306
		Author: Jeff Starr

	Jetpack
		Version: 12.1
		Author: Automattic

	The Events Calendar
		Version: 6.0.12
		Author: The Events Calendar

	TranslatePress - Multilingual
		Version: 2.5.1
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	Yoast SEO
		Version: 20.6
		Author: Team Yoast


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active


== Log ==
	
Log: showing 20 of 282023-04-03 04:30:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-06 12:45:59 [info] elementor::elementor_updater Started 
2023-04-06 12:45:59 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-06 12:45:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-06 12:45:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.1',
)]
2023-04-11 04:36:52 [info] elementor-pro::elementor_pro_updater Started 
2023-04-11 04:36:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-11 04:36:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-11 04:36:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-11 04:36:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 10:11:36 [info] elementor::elementor_updater Started 
2023-04-24 10:11:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-24 10:11:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-24 10:11:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 10:11:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 10:13:58 [info] elementor-pro::elementor_pro_updater Started 
2023-04-24 10:13:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-24 10:13:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-24 10:13:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 10:13:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]

JS: showing 5 of 5JS: 2023-04-19 13:31:19 [error X 1][https://dev.see-net.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:632657] undefined is not an object (evaluating 'this.view.container.isDesignable') 
JS: 2023-04-19 14:16:50 [error X 2][https://dev.see-net.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:673305] this.model.isValidChild is not a function. (In 'this.model.isValidChild(C)', 'this.model.isValidChild' is undefined) 
JS: 2023-04-19 16:55:52 [error X 7][https://dev.see-net.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:863322] undefined is not an object (evaluating '$e.routes.getHistory("panel").reverse()[0].route') 
JS: 2023-04-19 17:15:29 [error X 10][https://dev.see-net.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785237] undefined is not an object (evaluating 'T.originalEvent.key.toLowerCase') 
JS: 2023-04-19 19:54:45 [error X 1][https://dev.see-net.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:678550] undefined is not an object (evaluating 'C.getControlModel(T).get') 

````

</details>

**Comment by nicholaszein** [comment]
Hello @chrisringrose! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by brocatus** [comment]
I have the same issue

**Comment by chrisringrose** [comment]
@brocatus, the official "solution" Elementor provided was to pass the blame on the web server. The request for the latest Ajax request from Elementor is exactly the same every time, and thus if the server tells the browser to cache the results (our server does), then the browser simply loads the results from cache every time.

So you can reduce the cache time on the server. But ideally, Elementor should find a way to intelligently use caching, and clear the caching when the content has changed. (Or just give the option to force the browser to not using caching ever for Ajax results.)

**Comment by nicholaszein** [comment]
Elementor can't clear your server cache for you @brocatus. Each hosting company employs different rules and methods to clear that. It's imposible to account for every scenario, and every hosting company in the world.

We are, of course, still investigating this, however we won't create the fix you are suggesting. Purging or clearing cache is something that needs to be solved between you and your hosting company, by excluding the query in question.

If we find a solution for this it won't be one that identifies each server cache and tries to purge it.

Thanks for the suggestion though.
