### ISSUE TITLE
❌ @shilo-ey The code works only for admin users.

### ISSUE THREAD

**Issue by newworldlife1** [elementor/elementor#22331]
@shilo-ey The code works only for admin users.
For users with non-admin roles, there's an error in console, I suspect because the /plugins/elementor-pro/assets/js/popup.6a2540c839ce119e42a7.bundle.min.js is not loaded.

The error is:
jquery.min.js?ver=3.6.0:2 Uncaught TypeError: this.getModal is not a function

Thanks

_Originally posted by @dabesa in https://github.com/elementor/elementor/issues/10056#issuecomment-1046075225_

Still we are facing same issue.
Any solution for it ???

**Comment by nicholaszein** [comment]
Hey @newworldlife1, 

### ❌ Please don't post comments as new issues.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

regards
