### ISSUE TITLE
❌ [i18n] Some texts of the Admin Top Bar are not displayed translated

### ISSUE THREAD

**Issue by DAnn2012** [elementor/elementor#22380]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Some texts of the Admin Top Bar are not displayed translated if the language is not English, for example: "**Search or do anything in Elementor**", "**Connect Account**" and "**Connect your account to get access to Elementor's Template Library & more.**"

![elem1](https://github.com/elementor/elementor/assets/1197819/d6452904-6a89-46b7-9f93-6b2f347de49f)
![elem2](https://github.com/elementor/elementor/assets/1197819/e7491285-1598-437e-bc3e-f44148817b4d)

Also, "`&#8984;`" is shown on Mac and not the Command key symbol (&#8984;).

### Steps to reproduce

With the language set to, for example, Spanish or Italian, go to the WordPress Dashboard and select the "Elementor" menu item

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

It cannot be useful

**Comment by nicholaszein** [comment]
Hello @DAnn2012, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards,

Nick
