### ISSUE TITLE
⛔ 🧩 🛟 Support Request: Error 404 with MetForm add-on

### ISSUE THREAD

**Issue by SGfam** [elementor/elementor#22390]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Error 404 Issue with MetForm and Page in Elementor

Hello Elementor Support,

I hope this message finds you well. I am reaching out to seek assistance regarding an issue I am facing with Elementor and MetForm.

Recently, I encountered an error 404 when attempting to access MetForm and certain pages in Elementor. It seems like the preview and functionality of MetForm are not loading correctly, resulting in the error message. This issue has become a roadblock for me in making necessary changes and updates to my website's contact form.

I have already followed some troubleshooting steps, including clearing cache, checking for plugin conflicts, and ensuring that all plugins and Elementor are up to date. However, the problem persists. I have also tried to open need help page but no page could be found.

I would greatly appreciate it if you could provide guidance and support in resolving this error 404 issue with MetForm and Elementor. Any instructions or insights you can provide to help me troubleshoot and fix this problem would be highly valuable.

I am eager to get this issue resolved as it is hindering the smooth functioning of my website. Your prompt attention and assistance would be greatly appreciated.

Thank you for your time and support. I look forward to hearing from you soon.

Best regards,
Digital E-Yours
https://digitaleyourss.com/
Digitaleyours24@gmail.com

### Steps to reproduce

1. Access your website's dashboard.
2. Navigate to the "Pages" section and select the "Contact Us" page.
3. Ensure that the Elementor plugin is active and the contact form is created using MetForm.
4. Click on the "Edit with Elementor" button to open the page in the Elementor editor.
5. Locate the section or widget that contains the contact form.
6. Verify that the form fields, such as name, email, and message, are properly configured.
7. Save the changes made to the contact form.
8. Publish the page or update the changes if it was already published.
9. Open a new incognito/private browsing window.
10. Enter your website's URL in the browser's address bar and navigate to the Contact Us page.
11. Fill in the contact form with test data, including a name, email, and message.
12. Click the submit button to send the form.
13. Observe the form submission process and check for any errors or unexpected behavior.
14. Note any error messages, warnings, or issues encountered during the form submission process.
15. Take screenshots or record a screencast to document the issue if necessary.
16. Provide the details of the error message or unexpected behavior you observed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.12
	PHP Version: 8.0.28
	PHP Memory Limit: 1536M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://digitaleyourss.com
	Home URL: https://digitaleyourss.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 1536M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: digitaleyours24@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.4
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.74
		Author: ServMask

	All In One WP Security
		Version: 5.1.8
		Author: All In One WP Security & Firewall Team

	Elementor
		Version: 3.13.1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.7.1
		Author: WPDeveloper

	Health Check & Troubleshooting
		Version: 1.6.0
		Author: The WordPress.org community

	Hostinger
		Version: 1.3.0
		Author: Hostinger

	LiteSpeed Cache
		Version: 5.4
		Author: LiteSpeed Technologies

	MetForm
		Version: 3.3.2
		Author: Wpmet

	Site Kit by Google
		Version: 1.99.0
		Author: Google

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	UpdraftPlus - Backup/Restore
		Version: 1.23.3
		Author: UpdraftPlus.Com, DavidAnderson

	WPForms Lite
		Version: 1.8.1.2
		Author: WPForms

	Yoast SEO
		Version: 20.7
		Author: Team Yoast


== Must-Use Plugins ==
	aios-firewall-loader.php
		Version: 
		Author: 

	Health Check Troubleshooting Mode
		Version: 1.9.0
		Author: 


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Lazy Load Background Images: Inactive by default


== Log ==
	
JS: showing 3 of 3JS: 2023-04-21 17:29:15 [error X 1][https://digitaleyourss.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785238] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-04-29 18:50:29 [error X 1][https://digitaleyourss.com/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.12.2:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-05-03 19:06:39 [error X 10][https://digitaleyourss.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:632658] Cannot read properties of undefined (reading 'isDesignable') 

Log: showing 15 of 152023-04-24 15:47:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 15:47:30 [info] elementor::elementor_updater Started 
2023-04-24 15:47:30 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-24 15:47:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-24 15:47:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-05-08 22:13:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-08 22:13:09 [info] elementor::elementor_updater Started 
2023-05-08 22:13:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-08 22:13:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-08 22:13:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-08 22:13:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-09 22:16:50 [info] elementor::elementor_updater Started 
2023-05-09 22:16:50 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-09 22:16:50 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-09 22:16:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0',
  'to' => '3.13.1',
)]

PHP: showing 1 of 1PHP: 2023-05-07 17:30:33 [warning X 10][/home/u578700351/domains/digitaleyourss.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified
				
````

</details>

**Comment by nicholaszein** [comment]
Hello @SGfam,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
