### ISSUE TITLE
❌ 🛟 Support Request: Não estou conseguindo importar mídias

### ISSUE THREAD

**Issue by adminlphf** [elementor/elementor#22418]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Bom dia! Ao tentar importar arquivo (imagens, arquivos) ela demora muito e não importa. A conexão está muito lenta no site criado.

### Steps to reproduce

1) Ao acessar o post consigo editar. 2) quando vou importar algum arquivo ele fica lento e não importa.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Não estou conseguindo importar arquivos pra mídia e as publicações estão lentas.

**Comment by nicholaszein** [comment]
Hello @adminlphf,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can help with here. Please remember to check the Help Center or contact Elementor Support before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
