### ISSUE TITLE
✅ 🔣 🐞 Bug Report: 'Add Tab' button in Nested Tabs widget not showing properly in Dutch and Korean

### ISSUE THREAD

**Issue by toineenzo** [elementor/elementor#22489]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using Elementor in Dutch (Nederlands), the 'Add Tab' or 'Tab Toevoegen' is shown as  **{{ DATA.KNOP_TEXT }}}** 
It seems like this became a bug due to a typo: 3 }}} instead of 2 }} at the end. I reproduced this on a new InstaWP site with only Elementor Core/Pro and Hello Theme activated.
<img width="1512" alt="image" src="https://github.com/elementor/elementor/assets/4921397/b20eeaf1-8d2f-4c40-8547-c9a9685b1c56">

### Steps to reproduce

1. Install new Elementor website with Core and Pro + Hello Elementor Theme. Be sure to set language to Dutch
2. Open a new page an add Tabs widget. Make sure you enabled the Nested Experiment to enable the new Tabs Widget.
3. See that the Add Tabs button doesn't display the string properly in Dutch.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.55 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
	MySQL version: mariadb.org binary distribution v10.6.11
	PHP Version: 8.0.27
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.1
	Site URL: https://fair-fox-tedu.instawp.xyz
	Home URL: https://fair-fox-tedu.instawp.xyz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 128M
	Max Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: Europe/Amsterdam
	Admin Email: toinerademacher@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.1
		Author: Elementor.com

== Eigenschappen ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Pictogrammen inline lettertype: Actief
	Toegang verbeteringen: Actief
	Extra aangepaste onderbrekingspunten: Actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Actief
	Upgrade Swiper bibliotheek: Actief
	Raster container: Actief
	Default to New Theme Builder: Actief
	Hello Theme header & footer: Standaard actief
	Editor top balk: Actief
	Landingspagina's: Actief
	Geneste elementen: Actief
	Lazy-load achtergrondafbeeldingen: Standaard inactief
	Page Transitions: Actief
	Notes: Actief
	Loop: Actief
	Form Submissions: Actief
	Scroll Snap: Actief
	Menu: Actief

== Log ==
PHP: showing 3 of 3PHP: 2023-05-18 22:07:00 [warning X 1][/home/garohivuvo4893/web/fair-fox-tedu.instawp.xyz/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-18 22:07:08 [warning X 1][/home/garohivuvo4893/web/fair-fox-tedu.instawp.xyz/public_html/wp-content/plugins/elementor-pro/core/app/modules/import-export/runners/import/templates.php::103] Undefined array key "conditions" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-18 22:07:56 [notice X 1][/home/garohivuvo4893/web/fair-fox-tedu.instawp.xyz/public_html/wp-content/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==	
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==
````

</details>

**Comment by nicholaszein** [comment]
Hi, @toineenzo! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by toineenzo** [comment]
I think this had to do with this translation: [here, stable](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=15125402&filters%5Btranslation_id%5D=105064914) and [here, trunk](https://translate.wordpress.org/projects/wp-plugins/elementor/dev/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=14996256&filters%5Btranslation_id%5D=100509270)
I will close this issue ones I received an WP translation update that fixes it. I'm not really sure why this dynamic string is in the translation list as it doesn't need to be translated.

**Comment by toineenzo** [comment]
![image](https://github.com/elementor/elementor/assets/4921397/1747ebb1-57ec-47e5-8721-58ec8a2fb623)
This is now fixed as you can see. Not sure where to translate "Add Tab"

**Comment by nicholaszein** [comment]
Hello @toineenzo!

Thank you for your feedback and for contributing to the translation.

Kind regards
