### ISSUE TITLE
⛔ 🚀 Request: Please enable a general Discussions Category

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#22512]
Hi

Please enable discussions so we can talk about different things with the community. The current way the discussions works doesn't really work like a discussion place! I would like to ask and discuss things related to developing addons for elementary and currently, it's not possible.

(don't ever mention the Facebook group)

**Comment by m1ga** [comment]
check the menu: https://github.com/elementor/elementor/discussions it is already enabled

**Comment by perks98** [comment]
I think under discussions you used to be able to ask general questions but they moved feature requests from issues to discussions and now that is the only category option unfortunately. Maybe request it as a feature request 😅

**Comment by m1ga** [comment]
oh I see, I've never started one there :smile:

**Comment by nicholaszein** [comment]
Hello @babakfp,

Thank you for submitting your request! 🙏 

We have no plans to open a General Discussions category for the time being. For the first phase of our migration, we are focusing only on Bug Reports and Feature Requests. Once we have finished organizing both we will consider opening a new Category for General Discussions.

Please, avoid using issues to submit requests. Ironically this could have been submitted as a Feature Request, which is what I'm doing with this issue.

Best regards
