### ISSUE TITLE
❌ 📚 🚀 Request: Write documentation for setting up Elementor development and contributions

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#22522]
Hi

I tried to set up Elementor on my PC so I can contribute and eventually open a PR, but I wasn't successful in getting it to work! Can someone write a step-by-step guide on how we can get it to work? (for Windows).

Thanks

**Comment by nicholaszein** [comment]
Hello @babakfp,

Thanks for reaching out! 

Please, if you have a Feature Request, use the appropriate channel, and follow the guidelines in the form.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Take care,

Nick
