### ISSUE TITLE
⛔ 🐞 Bug Report: Console throws an error the first time I try to open the editor

### ISSUE THREAD

**Issue by Omerisra6** [elementor/elementor#22609]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Can`t load page with error: 
Uncaught TypeError: can't access property "model", elementor.settings.page is undefined
    isScrollSnapActive https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.13.4:2
    getDefaultSettings https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.13.4:2
    e https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.4:2
    Module https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.4:2
    Module https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.4:2
    child https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.4:2
    child https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.4:2
    initOnReadyComponents https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.13.4:2
    init https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.13.4:2
    initFrontend https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3
    onPreviewLoaded https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3
    onPreviewLoaded https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3
    Backbone 2
frontend.min.js🕑

### Steps to reproduce

1) Open console 
2) Reload page
3) Page loads without error

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://morocco-trip-travel.guide
	Home URL: https://morocco-trip-travel.guide
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Neve
	Version: 3.6.0
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0

== Active Plugins ==
	Country Flags for Elementor
		Version: 1.0.1
		Author: wepic

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Otter – Page Builder Blocks & Extensions for Gutenberg
		Version: 2.3.0
		Author: ThemeIsle

	SiteGround Central
		Version: 3.0.1
		Author: SiteGround

	SiteGround Optimizer
		Version: 7.3.1
		Author: SiteGround

	SiteGround Security
		Version: 1.4.5
		Author: SiteGround

	Skyboot Custom Icons for Elementor - Elementor Icons library
		Version: 1.0.6
		Author: Skybootstrap

	Styler for WPForms
		Version: 2.0.4
		Author: Sushil Kumar

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.8.1.3
		Author: WPForms


== Elements Usage ==
	
	wp-post : 0
		button : 6
		container : 18
		heading : 7
		icon-box : 5
		image : 4
		text-editor : 5
	wp-page : 4
		button : 4
		container : 40
		heading : 19
		icon : 3
		image : 10
		image-carousel : 1
		text-editor : 12
		wpforms : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	font_display: swap


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default


== Log ==
	
JS: showing 4 of 4JS: 2023-05-03 08:12:02 [error X 27][https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.12.2:2:30905] can't access property "model", elementor.settings.page is undefined 
JS: 2023-05-03 11:13:55 [error X 8][https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:785699] can't access property "localized", this.store.find(...) is undefined 
JS: 2023-05-14 07:23:22 [error X 1][https://morocco-trip-travel.guide/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:1081261] can't access property "getBoundingClientRect", $ is null 
JS: 2023-05-30 13:07:11 [error X 1][https://morocco-trip-travel.guide/wp-includes/js/wp-auth-check.min.js?ver=6.2.2:2:652] can't access property "hasClass", h is undefined 

PHP: showing 1 of 1PHP: 2023-05-03 09:47:33 [notice X 3][/home/customer/www/morocco-trip-travel.guide/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102023-05-16 23:06:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.2',
)]
2023-05-16 23:27:27 [info] elementor::elementor_updater Started 
2023-05-16 23:27:27 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-16 23:27:27 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-16 23:27:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.2',
)]
2023-05-30 08:19:29 [info] elementor::elementor_updater Started 
2023-05-30 08:19:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-30 08:19:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-30 08:19:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-05-30 08:19:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]



== Elementor - Compatibility Tag ==
	
	Country Flags for Elementor: Incompatible
	Skyboot Custom Icons for Elementor - Elementor Icons library: Compatibility not specified
				

````

</details>

**Comment by nicholaszein** [comment]
Hello @Omerisra6,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We can't reproduce the issue on our end. It seems you have something else causing a conflict. Most likely the server cache.

### ✅ What you can do to solve your issue:
Try deactivating your server cache or whitelisting the cache for the WordPress Admin and the Elementor Editor. Contact your hosting support to help with this task.

### 👍 For now, that's all we can help with. ]

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
