### ISSUE TITLE
⛔ 🐞 Bug Report: Kit imports are not working via Template library

### ISSUE THREAD

**Issue by lushkant** [elementor/elementor#22617]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Importing kits through the library importer doesn't work anymore.

https://github.com/elementor/elementor/assets/18240138/8f253076-5dc2-4fe6-9917-a57367568f6f

### Cause of the Issue
It used to work fine till v3.13.2 but started throwing this error since v3.13.4. Also tested with latest v3.14.0-beta2.

As I tried to look into this further, I saw there is a new commit addressing security issues with how the `save_item()` function at `includes/template-library/sources/local.php` which creates/saves documents.  
Specifically at a conditional where it checks for `is_valid_template_type()` it fails for kit template types.

First commit when `save_item()` was modified - https://github.com/elementor/elementor/commit/e43d559d4c8fef98739398d61fb424874dc1efe8#diff-7197ac5955c6b7881e18d540942ab36bb55b6955b6ce68da9ed2513cc04897a8R516

Next commit when `is_valid_template_type()` was modified - https://github.com/elementor/elementor/commit/372d787162af29638c9844b8b7a073d07ad11b3c#diff-7197ac5955c6b7881e18d540942ab36bb55b6955b6ce68da9ed2513cc04897a8R574-R587

### Possible fix
When `is_valid_template_type()` runs for kit template-type imports, it doesn't get the expected 'cpt' property from its parent document classes unlike other template types instead returns null.
https://github.com/elementor/elementor/blob/b45c385df19f099fd67804c234af675f475f9622/includes/template-library/sources/local.php#L582

### Steps to reproduce

1) Export any kit from the template library.
2) Try importing the same with the template library importer now.
3) It will throw an error saying "Invalid template type..".

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.23.4
	MySQL version: Homebrew v8.0.32
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: http://sk.test
	Home URL: http://sk.test
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Debug
		Version: 1.10
		Author: SoniNow Team

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Query Monitor
		Version: 3.12.2
		Author: John Blackbourn

	Spatie Ray
		Version: 1.7.5
		Author: Spatie


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default


== Log ==
	


== Elementor - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @lushkant,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Kits should be imported through the Kit Library, not through the Template Library.

### ✅ What you can do to solve your issue:
Please go to the Kit Library and use that interface when you are importing Kits.

### 👍 For now, that's all we can help with. 

Kind regards
