### ISSUE TITLE
Text shadow on all modules

### ISSUE THREAD

**Issue by fthiesen** [elementor/elementor#2263]
I'd like suggest that the text shadow option is added to all modules. For example I'd like to be able to add a text shadow when I'm creating a slider. Thank you.

**Comment by bkjproductions** [comment]
Seems like a good idea to me, too! Especially on sliders, when you may need the text shadow to help make text stand out against a photo. It should use the same controls as the Box Shadow that appears on some modules. Something like this:

![idea-for-text-shadow](https://user-images.githubusercontent.com/4551281/60106899-f7524100-9733-11e9-8a78-e8c6d362f83b.jpg)

Basically anywhere you might have a text style, add this feature. (Conceal the detailed settings a little bit, probably, as that palette is getting rather long.) Not that Adobe InDesign has the greatest GUI, but how are they handling it? Somewhere quick and convenient.

It would be great if you could have somewhere else in Elementor that you could set a global style for the shadow. In Photoshop there is a default drop-shadow angle, something like that. (I know, this is css and I could put in my own global CSS, sure, but why am I using Elementor anyway? To avoid code....) Or, as in MS-Word, you could set a global style based on the current attributes, but I digress...

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!
