### ISSUE TITLE
⛔ 🐞 Bug Report: Scrolling is not possible in the text editor widget if the cursor is over the textarea

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#22643]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This is a very annoying bug that I am facing in this version. See the image below. If the mouse is on the specified area (white area) of ​​the image below and then I use the scroll wheel to scroll the text editor widget panel, the scrolling will not be done.

![bug](https://github.com/elementor/elementor/assets/103376243/91a647f5-c2e3-4ff2-aa82-824b02aff065)

Maybe these are important, but I'm experiencing this bug on Windows 10 - Chrome browser. 

### Please note
if you are using a laptop mouse, you will most likely not encounter this bug. But if you use a mouse, you will definitely deal with this bug.

### Steps to reproduce

1. Add the text editor widget.
2. According to the image above, place the mouse pointer in the specified area (typeable area of ​​the Text editor widget).
3. Now try to scroll the widget panel using the scroll wheel of the mouse. **Scrolling will not be done**.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


== Server Environment ==
Operating System: WINNT
Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
MySQL version: mariadb.org binary distribution v5.6.42-84.2
PHP Version: 7.3.2
PHP Memory Limit: 128M
PHP Max Input Vars: 1000
PHP Max Post Size: 64M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.1.1
Site URL: https://domain.com/
Home URL: https://domain.com/
WP Multisite: No
Max Upload Size: 16 MB
Memory limit: 128M
Max Memory limit: 256M
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Language: en-US
Timezone: 0
Admin Email: [REDACTED]
Debug Mode: Inactive

== Theme ==
Name: Hello Elementor
Version: 2.7.0
Author: Elementor Team
Child Theme: No

== User ==
Role: administrator
WP Profile lang: en_US
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
Elementor
Version: 3.14.0-beta1
Author: Elementor.com

== Elementor Experiments ==
Optimized DOM Output: Active
Improved Asset Loading: Active
Improved CSS Loading: Active
Inline Font Icons: Active
Accessibility Improvements: Inactive
Additional Custom Breakpoints: Inactive
admin_menu_rearrangement: Inactive
Flexbox Container: Active
Upgrade Swiper Library: Active
Grid Container: Active
Hello Theme Header & Footer: Inactive
Editor Top Bar: Active
Landing Pages: Inactive
Nested Elements: Active
Nested Accordion: Inactive by default
Lazy Load Background Images: Active
Global Style Guide: Inactive

````

</details>

**Comment by nicholaszein** [comment]
Hello @Joliamendi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected behavior from your browser. If your cursor is over a scrollable element (like the text area in the text editor), the expected scroll behavior is to scroll the element where the cursor is currently over, even if that element does not display a scrollbar. We can't change this behavior, otherwise, users wouldn't be able to scroll inside the text editor if they had long strings of text.

### ✅ What you can do to solve your issue:
Place your cursor outside the text area to scroll the widget panel.

### 👍 For now, that's all we can help with. 

Kind regards
