### ISSUE TITLE
✅ 🔗 🐞 Bug Report: Responsive CSS is not loaded for Single templates (Duplicate of #19394)

### ISSUE THREAD

**Issue by stormit** [elementor/elementor#22670]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I have found a bug. I have a custom post type which is allowed to edit with Elementor. The problem is, when I switch to tablet or mobile editor and change some things (margin/padding, ...). It does not work. It only is updated/worked when I go to **Elementor > Tools > General** and hit **Regenerate CSS & Data**

Please check and fix this issue soon!

### Steps to reproduce

1. Edit a custom post type with Elementor (create one if don't have [https://developer.wordpress.org/reference/functions/register_post_type/](https://developer.wordpress.org/reference/functions/register_post_type/))
2. Switch to tablet or mobile editor
3. Change some things which need to update CSS (Ex: margin/padding, ...)
4. Check frontend

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>

Operating System: | WINNT |  
-- | -- | --
Software: | Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.0.19 |  
MySQL version: | mariadb.org binary distribution v10.4.24 |  
PHP Version: | 8.0.19 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 40M |  
GD Installed: | No |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
