### ISSUE TITLE
❌ 🛟 Support Request: Server Error appears when I try to publish or update a document

### ISSUE THREAD

**Issue by AparSharma1807** [elementor/elementor#22685]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Sever Error is showing when getting the things Updated on Elementor 
![Capture](https://github.com/elementor/elementor/assets/125808382/90c5031c-3ff3-4390-80b9-5086dbba791c)

### Steps to reproduce

make a change on Edit With Elementor 
Click on Update of Elementor and you will see the server error there

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Edit With Elementor > Make any change > Click on Update

**Comment by nicholaszein** [comment]
Hello @AparSharma1807,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

Follow the instructions in this article:
https://elementor.com/help/publish-update-button-not-work/


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
