### ISSUE TITLE
🔣 🐞 The use of `esc_html__()` on labels and default values for some controls creates problems with some strings translated into Italian with single quotes

### ISSUE THREAD

**Issue by DAnn2012** [elementor/elementor#22705]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The use of `esc_html__` creates problems with some strings translated into Italian with single quotes (which are very frequent in Italian), displaying the code `&#039;` instead of the character `'`

![edit-headings](https://github.com/elementor/elementor/assets/1197819/5b66ef60-fed8-44cc-871d-6cf2bcd89054)

[Add Your Heading Text Here](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5519732&filters%5Btranslation_id%5D=53978448)

https://github.com/elementor/elementor/blob/3da6e3bb0c6e67cd18d5e7045a2c0be5f3c487e4/includes/widgets/heading.php#L120

[Paste URL or type](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6547879&filters%5Btranslation_id%5D=56920819)

https://github.com/elementor/elementor/blob/3da6e3bb0c6e67cd18d5e7045a2c0be5f3c487e4/modules/shapes/widgets/text-path.php#L148

https://github.com/elementor/elementor/blob/3da6e3bb0c6e67cd18d5e7045a2c0be5f3c487e4/includes/controls/url.php#L68

### Steps to reproduce

1) Set the WP language to Italian
2) Create a new page with Elementor and choose "Intestazione" (Heading)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: TasteWP-S3 Official/3.0.0
	MySQL version: (Ubuntu) v8.0.32
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 5000
	PHP Max Post Size: 60M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://gianttrip.s3-tastewp.com
	Home URL: https://gianttrip.s3-tastewp.com
	WP Multisite: No
	Max Upload Size: 60 MB
	Memory limit: 96M
	Max Memory limit: 96M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: it-IT
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.13.4
		Author: Elementor.com


== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attivo per impostazione predefinita
	Caricamento delle risorse migliorato: Attivo per impostazione predefinita
	Caricamento CSS migliorato: Attivo per impostazione predefinita
	Icone dei font in linea: Inattivo per impostazione predefinita
	Miglioramenti dell'accessibilità: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Inattivo per impostazione predefinita
	Upgrade Swiper Library: Attivo per impostazione predefinita
	Grid Container: Inattivo per impostazione predefinita
	Header e Footer del tema Hello: Attivo per impostazione predefinita
	Editor Top Bar: Inattivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Nested Elements: Inattivo per impostazione predefinita
	Lazy Load Background Images: Inattivo per impostazione predefinita


== Registro ==
	
PHP: showing 1 of 1PHP: 2023-06-07 09:14:20 [warning X 1][/s3-gianttrip/wordpress/wp-content/plugins/elementor/modules/system-info/reporters/server.php::157] get_cfg_var() has been disabled for security reasons [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	

				

````

</details>

**Comment by Barcov** [comment]
@DAnn2012 thanks for posting this up. 

I've tested this against v3.13 using a similar environment and Wordpress version. But I've not been able to reproduce it yet. 

I've managed to translate some English with single quotes using the AI feature without esc_thml() causing issues. 
![image](https://github.com/elementor/elementor/assets/130742176/e4abc7a6-ed20-419f-8d02-72db4853544e)

- Can you provide some examples of strings you're translating that produce this effect?
- You also mention a blank Hello theme, does this only happen on the first post/page after a fresh install?

**Comment by DAnn2012** [comment]
Hello @Barcov 

I thank you for the answer.

I'm referring to the default strings and placeholders of the Italian translation of Elementor present on translate.wordpress.org, for example:

[Add Your Heading Text Here](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5519732&filters%5Btranslation_id%5D=53978448)

[Paste URL or type](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6547879&filters%5Btranslation_id%5D=56920819)

Thanks.

**Comment by nicholaszein** [comment]
Hi @DAnn2012,

the use of `esc_html__()` on these fields is required to properly sanitize them. In this case, we would need to verify with the translation team if it's possible to change that or change the translations to avoid this error. In any way, it doesn't seem that this can affect the rendering or usage of the widgets, correct?

Let me check with the team if we can do something about it.

Kind regards

**Comment by DAnn2012** [comment]
Hi @nicholaszein 

I sent on translate.wordpress.org the following strings with the replacement of the `'` character with `’`:

[Aggiungi qui il testo dell’intestazione](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5519732&filters%5Btranslation_id%5D=106966090)

[Incolla l’URL o digita](https://translate.wordpress.org/projects/wp-plugins/elementor/stable/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6547879&filters%5Btranslation_id%5D=106966095)

I hope they are approved as soon as possible.

**Comment by DAnn2012** [comment]
Hi @nicholaszein

The two strings in Italian that I sent to translate.wordpress.org were both approved.

Now I can close this issue report.

Thank you.
