### ISSUE TITLE
⛔ 🐞 Bug Report: Advanced Custom Field (ACF) image type not loading in Elementor Pro Gallery Widget

### ISSUE THREAD

**Issue by NabilRedwood** [elementor/elementor#22776]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,
I would appreciate any help with this.
I have created a few custom fields using the ACF plug-in. I have 5 custom fields (with the image) type that were specified for my products category. I am trying to show these images in Elementor Pro Gallery Widget. I set the Gallery type to "Multiple" then I try to set the source of the images. However, the option "ACF Image Field" does not show up from the available menu of Dynamic Tags. 

How can I show the five image custom fields in my Elementor Gallery Widget (the pro version)?

Thank you,
Nabil.

### Steps to reproduce

1. I have created a few custom fields using the ACF plug-in. 
2. I have 5 custom fields (with the image) type that were specified for my products category. 
3. I set the Gallery type to "Multiple" then I try to set the source of the images.
4. However, the option "ACF Image Field" does not show up from the available menu of Dynamic Tags. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 8.1.19
	PHP Memory Limit: 32M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: XXXXXXXXXXX
	Home URL: XXXXXXXXXXX
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.1.6
		Author: WP Engine

	Coming Soon Page, Maintenance Mode, Landing Pages &amp; WordPress Website Builder by SeedProd
		Version: 6.15.7
		Author: SeedProd

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	W3 Total Cache
		Version: 2.3.2
		Author: BoldGrid

	WooCommerce
		Version: 7.8.0
		Author: Automattic


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	header : 4
		container : 4
		heading : 1
		image : 1
		nav-menu : 1
		spacer : 2
	product : 10
		call-to-action : 2
		container : 32
		eael-adv-accordion : 1
		heading : 9
		icon-list : 2
		metform : 1
		nested-tabs : 3
		spacer : 6
		testimonial-carousel : 2
		text-editor : 4
		woocommerce-product-add-to-cart : 2
		woocommerce-product-content : 2
		woocommerce-product-price : 2
		woocommerce-product-related : 2
		woocommerce-product-title : 4
		woocommerce-products : 1
	section : 3
		button : 18
		elementskit-blog-posts : 3
		elementskit-funfact : 15
		elementskit-heading : 27
		elementskit-image-accordion : 9
		elementskit-testimonial : 3
		heading : 33
		icon-box : 9
		icon-list : 6
		image : 33
		image-box : 27
		metform : 3
		text-editor : 30
	wp-post : 1
		container : 6
		eael-feature-list : 1
		heading : 5
		image : 2
		mf-button : 1
		mf-date : 1
		mf-email : 1
		mf-number : 1
		mf-telephone : 1
		mf-text : 2
		mf-textarea : 1
		nav-menu : 1
		premium-addon-title : 3
		spacer : 3
		text-editor : 6
		theme-site-logo : 2
	wp-page : 5
		blockquote : 1
		button : 16
		container : 8
		divider : 7
		eael-post-grid : 2
		elementskit-blog-posts : 1
		elementskit-funfact : 5
		elementskit-heading : 8
		elementskit-image-accordion : 2
		elementskit-testimonial : 1
		form : 1
		gallery : 1
		heading : 39
		icon-box : 6
		icon-list : 2
		image : 21
		image-box : 9
		metform : 1
		nav-menu : 3
		portfolio : 2
		posts : 1
		spacer : 20
		table-of-contents : 2
		testimonial-carousel : 3
		text-editor : 24


== Settings ==
	
	cpt_support: post, page, product
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header &amp; Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active


== Log ==
	
Log: showing 20 of 272023-05-16 19:17:42 [info] elementor-pro::elementor_pro_updater Started 
2023-05-16 19:17:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-16 19:17:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-16 19:17:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.13.1',
)]
2023-05-16 19:17:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.13.1',
)]
2023-05-26 03:00:21 [info] elementor::elementor_updater Started 
2023-05-26 03:00:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-26 03:00:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-26 03:00:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-26 03:00:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.3',
)]
2023-05-26 16:56:05 [info] elementor-pro::elementor_pro_updater Started 
2023-05-26 16:56:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-05-26 16:56:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-05-26 16:56:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-05-26 16:56:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-06-06 23:56:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]
2023-06-06 23:56:15 [info] elementor::elementor_updater Started 
2023-06-06 23:56:15 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-06 23:56:15 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-06 23:56:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.3',
  'to' => '3.13.4',
)]

````

</details>

The rest of the file was truncated for security of the development site but I can provide the data confidentially.

**Comment by nicholaszein** [comment]
Hi, @NabilRedwood,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

You can only use the Gallery widget with Gallery fields if you choose the Dynamic Tag option. What you are trying to do will not work. Please refer to the [documentation](https://elementor.com/help/gallery-widget/) of the Gallery widget.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
