### ISSUE TITLE
⛔ 📚 🐞 Bug Report: Template not found: #tmpl-uploader-editor.

### ISSUE THREAD

**Issue by sanchay6458** [elementor/elementor#22781]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've access elementor widget control setting in content_template() function by using $this->get_settings_for_display() or $this->get_settings(), it show `jquery.js?ver=3.6.4:4095 Uncaught Error: Template not found: #tmpl-uploader-editor` error.
=> **function for get settings**
protected function content_template() {
        $settings = $this->get_settings_for_display();
    }
**Or**
protected function content_template() {
        $settings = $this->get_settings();
    }

=> **Error** 

jquery.js?ver=3.6.4:4095 Uncaught Error: Template not found: #tmpl-uploader-editor
    at n.template (wp-util.js?ver=6.2.2:40:11)
    at n.render (wp-backbone.js?ver=6.2.2:541:25)
    at n.render (media-views.js?ver=6.2.2:9678:25)
    at HTMLDocument.init (media-editor.js?ver=6.2.2:1062:39)
    at mightThrow (jquery.js?ver=3.6.4:3802:29)
    at process (jquery.js?ver=3.6.4:3870:12)
    
   
**Our requirement**:- I've get post from post id and display in editor. this post id come from widget control setting.
_Can you help me for get post and post_meta information by using control post id and display in editor?_

### Steps to reproduce

1) Create widget.
2) Register widget control and give option of post_id to get post_id from user.
3) Create `protected function content_template()` for display text in editor.
4) Access setting in `protected function content_template()` function

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt




WordPress Information
--
Home URL: | http://localhost/wptravel-site
Site URL: | http://localhost/wptravel-site
WP Version: | 6.2.2
WP Multisite: | –
WP Memory Limit: | 512 MB
WP Debug Mode: | Yes
WP Cron: | Yes
Language: | en_US
Upload Directory Location: | http://localhost/wptravel-site/wp-content/uploads
Server Information
Server Info: | Apache/2.4.54 (Unix) OpenSSL/1.1.1q PHP/8.0.23 mod_perl/2.0.12 Perl/v5.34.1
PHP Version: | 8.0.23
PHP Post Max Size: | 40 MB
PHP Time Limit: | 120
PHP Max Input Vars: | 1000
cURL Version: | 7.53.1, OpenSSL/1.1.1q
SUHOSIN Installed: | –
Max Upload Size: | 40 MB
Default Timezone is UTC: | Yes
PHP Error Log File Location: | /opt/lampp/htdocs/wptravel-site/wp-content/debug.log
fsockopen/cURL: | Yes
SoapClient: | Yes
DOMDocument: | Yes
GZip: | Yes
Multibyte String: | Yes
Remote Get Status: | Yes
Current Theme
Name: | Travel Joy
Version: | 1.2
Author URL: | https://wensolutions.com/
Child Theme: | No. If you're want to modifying a theme, it safe to create a child theme. See: How to create a child theme
Active Plugins (4)
WP Travel | by WP Travel – 6.8.0
Easy WP SMTP | by Easy WP SMTP – 2.1.0
Elementor | by Elementor.com – 3.13.4
WP Travel Elementor Extended | by WP Travel – 1.0.0

WordPress Information
Home URL:	http://localhost/wptravel-site
Site URL:	http://localhost/wptravel-site
WP Version:	6.2.2
WP Multisite:	–
WP Memory Limit:	512 MB
WP Debug Mode:	 Yes
WP Cron:	 Yes
Language:	en_US
Upload Directory Location:	http://localhost/wptravel-site/wp-content/uploads
Server Information
Server Info:	Apache/2.4.54 (Unix) OpenSSL/1.1.1q PHP/8.0.23 mod_perl/2.0.12 Perl/v5.34.1
PHP Version:	8.0.23
PHP Post Max Size:	40 MB
PHP Time Limit:	120
PHP Max Input Vars:	1000
cURL Version:	7.53.1, OpenSSL/1.1.1q
SUHOSIN Installed:	–
Max Upload Size:	40 MB
Default Timezone is UTC:	Yes
PHP Error Log File Location:	/opt/lampp/htdocs/wptravel-site/wp-content/debug.log
fsockopen/cURL:	Yes
SoapClient:	Yes
DOMDocument:	Yes
GZip:	Yes
Multibyte String:	Yes
Remote Get Status:	Yes
Current Theme
Name:	Travel Joy
Version:	1.2
Author URL:	https://wensolutions.com/
Child Theme:	 No. If you're want to modifying a theme, it safe to create a child theme. See: [How to create a child theme](https://codex.wordpress.org/Child_Themes)
Active Plugins (4)
[WP Travel](http://wptravel.io/)	by [WP Travel](http://wptravel.io/) – 6.8.0
[Easy WP SMTP](https://easywpsmtp.com/)	by [Easy WP SMTP](https://easywpsmtp.com/) – 2.1.0
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash)	by [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash) – 3.13.4
[WP Travel Elementor Extended](http://www.wptravel.io/)	by [WP Travel](http://www.wensolutions.com/) – 1.0.0


````

</details>

**Comment by nicholaszein** [comment]
Hi, @sanchay6458,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Comment by nicholaszein** [comment]
@amirnafees88,

Submit a new 

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.
