### ISSUE TITLE
⛔ 📚 🐞 Bug Report: Changing control 'type' with saved value from previous control type breaks rendering.

### ISSUE THREAD

**Issue by scarydakis** [elementor/elementor#22799]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I'm customising an existing control for a container background colour from type 'COLOR' to "SELECT2'. This works great unless there is a previously saved value from the previous control type. When there is a previous value, the new value is still saved however there is nothing rendered in the frontend. This bug is not present on new containers. The same occurs in the reverse direction.

To fix the issue I have to revert the control type, edit the page and remove the value. I then can re-apply my customisation and the front end rendering works correctly.

The code I'm using is below.

Thanks,
Steph.
```

add_action( 'elementor/element/before_section_end', function($element, $section_id, $args){

	if ( 'container' === $element->get_name())
	{
		$controls_manager=scwd_elementor_instance()->controls_manager;
		
		foreach ( $element->get_controls() as $control_data)
		{
			if ($controls_manager::COLOR === $control_data['type'])
			{
				$control_data['type'] = $controls_manager::SELECT2;
				$control_data['options'] = scwd_get_color_list();
				$control_data['default'] = '';
				$element->update_control( $control_data['name'], $control_data );
			}
			
		}
	}

}, 10, 3 );


```

### Steps to reproduce

1. Edit a page, add a container and set a container background colour to "Primary" using the default colour control and save page. The background colour is applied on the frontend.
2. Programmatically update the control to use a different type eg "Controls_Manager::TEXT"
3. Re-edit the page and same container using the new control type. Enter a HEX colour '#ff0000' The value is saved but nothing is rendered on the frontend.
4. Add a new container and enter HEX colour '#ff0000'. The colour is rendered correctly.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

```php
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://b-scwd.standeven.net.au
	Home URL: https://b-scwd.standeven.net.au
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-AU
	Timezone: Australia/Melbourne
	Admin Email: [REDACTED] 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Automatic.css
		Version: 2.5.0
		Author: Kevin Geary, Matteo Greco

	Code Snippets
		Version: 3.4.0
		Author: Code Snippets Pro

	Disable Gutenberg
		Version: 2.9
		Author: Jeff Starr

	DynamicConditions
		Version: 1.6.2
		Author: RTO GmbH

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.2
		Author: ShortPixel

	HappyFiles
		Version: 1.5.1
		Author: Codeer

	Meta Box
		Version: 5.7.2
		Author: MetaBox.io

	Meta Box AIO
		Version: 1.21.1
		Author: MetaBox.io

	Nested Pages
		Version: 3.2.4
		Author: Kyle Phillips

	Rank Math SEO
		Version: 1.0.117
		Author: Rank Math

	Restricted Site Access
		Version: 7.4.0
		Author: 10up

	Restricted Site Notifier
		Version: 1.0.1
		Author: Fidgety Lizard

	Search Exclude
		Version: 2.0.2
		Author: QuadLayers


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Active by default
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				
```

</details>

**Comment by nicholaszein** [comment]
Hello @scarydakis,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Please remember to read the entire [documentation] (https://developers.elementor.com). It's not recommended to modify core elements. Especially controls that are already established. If you do that, you're going to experience exactly the issue you're experiencing. Instead, you should create new elements.

Dont try to change controls that have already been using without performing a Data Upgrade. We do not provide support for changes in data structure. This is something you'll need to do by yourself. 

We have no plans to change this functionality. 

Kind regards
