### ISSUE TITLE
🐞 Heading `color: inherit` overrides kit colors if "Disable Default Colors" is checked in Settings

### ISSUE THREAD

**Issue by vladninja** [elementor/elementor#22939]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When the user disable Default Colors in Elementor Settings and add a Heading widget to any place with a link, Elementor not kept a global link color settings, instead of that color: inherit is added and rewrite the correct settings.

### Steps to reproduce

Disable Default Colors in Elementor Settings
![image](https://github.com/elementor/elementor/assets/76119088/8b9cf10c-e8c2-4640-9b5e-7a88b621e723)

Add Heading to any page
Add a link to the Heading

Expected -> Heading is a link take a global link color configuration
Currently -> Heading is a link, but without color (and hover)

![image](https://github.com/elementor/elementor/assets/76119088/675cb545-c7a3-4b89-beaa-b33678a71a23)

Without color: inherit; that works as expected.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:8083
	Home URL: http://localhost:8083
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.14.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.0
		Author: Elementor.com


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active
	Menu: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by vladninja** [comment]
The system info was added

**Comment by nicholaszein** [comment]
Thank you for providing the missing information @vladninja! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐

Kind regards

**Comment by amyriounis** [comment]
Can use something along those lines until this gets fixed by Elementor.

```php
use Elementor\Core\Page_Assets\Data_Managers\Base as Page_Assets_Data_Manager;

function elementor_assets_data_filtering( $assets_data ) {
	$widgets_data = &$assets_data['css']['widgets'];

	if ( isset( $widgets_data['heading'] ) ) {
		if ( isset( $widgets_data['heading']['content'] ) && ! empty( $widgets_data['heading']['content'] ) ) {
			$orig_str = '.elementor-widget-heading .elementor-heading-title[class*=elementor-size-]>a{color:inherit;font-size:inherit;line-height:inherit}';
			$new_str  = '.elementor-widget-heading .elementor-heading-title[class*=elementor-size-]>a{font-size:inherit;line-height:inherit}';
			$widgets_data['heading']['content'] = str_replace( $orig_str, $new_str, $widgets_data['heading']['content'] );
		}
	}

	return $assets_data;
}
add_filter( 'option_' . Page_Assets_Data_Manager::ASSETS_DATA_KEY, __NAMESPACE__ . '\elementor_assets_data_filtering' );
```

This **only** works with "Improved CSS Loading" experiment enabled (i.e. inlined CSS widget styles).

If you're using external CSS files you can use something similar to [this](https://github.com/elementor/elementor/issues/10649#issuecomment-605458514) solution, just make sure to update the `str_replace()` strings accordingly.

**Comment by nicholaszein** [comment]
Hello @vladninja and @amyriounis!

Thank you for your patience! 🙏 

After reviewing this issue, and considering Heading sizes were deprecated and discontinued to make way for CSS Classes, we decided this issue is no longer relevant, as we are unable to implement a fix.

We hope you can understand.

Thank you for contributing!
