### ISSUE TITLE
❌ 🧩 🐞 Bug Report: File permissions change to 600 after every update

### ISSUE THREAD

**Issue by luckdragon** [elementor/elementor#23018]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have elementor pro, I do not have cpanel, nor do I have litespeed and every time elementor pro updates, it changes the entire directory tree to 700/600 permissions and breaks my site.  I can't monitor the site 100% of the time to verify that it is showing the header correctly.  would really appreciate some kind of insight into how to correct this issue.

I'm using an elementor theme, so the theme shouldn't have any bearing on the problem.

thanks in advance

### Steps to reproduce

1) let elementor pro update 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>
<h3 class="wp-heading-inline" style="display: block; font-weight: 600; color: rgb(29, 35, 39); font-size: 1.3em; margin: 1em 0px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System Info</h3><div style="outline: 0px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-block-end: 10px;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.22 |  
MySQL version: | MariaDB Server v10.3.24 |  
PHP Version: | 7.4.22 |  
PHP Memory Limit: | 256M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 2G |  
GD Installed: | Yes |  
ZIP Installed: | No |  
Write Permissions: | All right |  
Elementor Library: | Connected

</div></div>
</body>
</html>

**Comment by nicholaszein** [comment]
Hello @luckdragon,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party services.

Your issue is related to your server configuration, which needs to be resolved with your hosting provider.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

Regards
