### ISSUE TITLE
⛔ 🛟 Support Request: Setting the Home Page as the Shop Page breaks the page design

### ISSUE THREAD

**Issue by JTTraverse** [elementor/elementor#23141]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am using the latest version of Elementor and WooCommerce plugins, on the latest WordPress version. This may ultimately be a problem stemming from WooCommerce, but even so, perhaps the Elementor developers can find a way to keep WooCommerce from wrecking regular Elementor-built web pages. Unfortunately, my site is not active yet so I can't provide a link.

What happens is this: Under the WooCommerce->Products tab is where you designate the 'Shop Page'. But any page that I entered there immediately goes haywire. I discovered this because I don't have a separate page as a shop page, so the other day I set that entry to point to my home page (i.e. Home). The home page immediately went crazy as if all the underlying HTML code had suddenly turned to text being displayed all over the page. Images are still displayed, but they would be lined up arbitrarily above and below these big sections of text made up of the underlying HTML code.

When I realized it was the 'shop page' entry, I tested it by changing that entry to other pages on my site, and each one, in turn, would suddenly show the crazy text-html. On changing the entry to some other page (or leaving it blank), all the pages go back to normal. So, there is something about pointing the 'shop page' entry at a web page that causes the page to go haywire.

### Steps to reproduce

1) Install the Elementor plugin and WooCommerce plugin.
2) Create/Edit home page with Elementor Editor
3) Under WooCommerce->Products tab, change the entry for 'Shop home' to point to the home page (or another similar page)
4) Check the page designated as the 'Shop Home' in '3' above. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.21
	PHP Version: 8.2.7
	PHP Memory Limit: 768M
	PHP Max Input Vars: 6200
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://fullofstars.com
	Home URL: https://fullofstars.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: -6
	Debug Mode: Inactive

== Theme ==
	Name: Woostify
	Version: 2.1.9
	Author: Woostify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0

== Active Plugins ==
	Add From Server
		Version: 3.4.5
		Author: Dion Hulse

	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	Autoptimize
		Version: 3.1.8.1
		Author: Frank Goossens (futtta)

	Change wp-admin login
		Version: 1.1.3
		Author: wpexpertsio

	Clear Cache For Me
		Version: 2.0
		Author: Webhead LLC

	Copy &amp; Delete Posts
		Version: 1.4.0
		Author: Copy Delete Posts

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.14
		Author: Brainstorm Force, Nikhil Chavan

	Essential Addons for Elementor
		Version: 5.8.3
		Author: WPDeveloper

	FunnelKit Funnel Builder
		Version: 2.12.0
		Author: FunnelKit

	Jetpack
		Version: 12.3
		Author: Automattic

	Jetpack Boost
		Version: 1.9.4
		Author: Automattic - Jetpack Site Speed team

	Printify Shipping Method
		Version: 2.7
		Author: Printify

	Slider Revolution
		Version: 6.5.8
		Author: ThemePunch

	Sticky Header Effects for Elementor
		Version: 1.6.5
		Author: Rwattner

	Stripe Payment Gateway for WooCommerce
		Version: 1.4.1
		Author: FunnelKit

	Total Upkeep
		Version: 1.15.7
		Author: BoldGrid

	Total Upkeep Premium
		Version: 1.5.9
		Author: BoldGrid

	Under Construction
		Version: 3.97
		Author: WebFactory Ltd

	weForms
		Version: 1.6.17
		Author: weForms

	WooCommerce
		Version: 7.9.0
		Author: Automattic

	WooCommerce Payments
		Version: 6.2.0
		Author: Automattic

	YITH WooCommerce Wishlist
		Version: 3.23.0
		Author: YITH

	Yoast SEO
		Version: 20.11
		Author: Team Yoast


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==

JS: showing 5 of 5JS: 2023-03-23 02:53:46 [error X 55][https://fullofstars.com/wp-content/plugins/sticky-header-effects-for-elementor/assets/js/she-header.js?ver=1.6:418:12] blur_bg is not defined 
JS: 2023-03-23 02:54:07 [error X 128][https://fullofstars.com/wp-content/plugins/sticky-header-effects-for-elementor/assets/js/she-header.js?ver=1.6:353:26] width_l is not defined 
JS: 2023-07-05 14:19:00 [error X 5][https://fullofstars.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:956327] Cannot read properties of undefined (reading &#039;settings&#039;) 

PHP: showing 6 of 6PHP: 2023-07-02 23:27:14 [notice X 6][../wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-03 21:56:44 [notice X 2][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-05 18:02:14 [notice X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified

````

</details>

**Comment by nicholaszein** [comment]
Hello @JTTraverse,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

When using Elementor you need to use the Theme Builder to create a Products Archive Template and set the Display Condition to Shop Page. This template should replace the Shop Page you set up in your WooCommerce Settings.

Please check this article to learn how to build your Shop page: https://elementor.com/help/creating-a-woocommerce-archive-template/

I also see you are using the Woostify theme. They provide very extensive documentation that helps understand how to build your WooCommerce store. [This article](https://woostify.com/docs/woocommerce/) seems to go through every step. It should help you get started.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please do not use GitHub to request support. 🙏 

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
