### ISSUE TITLE
Taxonomy Filters are not displayed in Elementor settings

### ISSUE THREAD

**Issue by LinusB** [elementor/elementor#23163]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I don't have the option to activate the taxonomy filters in the 3.15 beta version.
I use version 3.15.0-dev5 and WordPress 6.2.2

![image](https://github.com/elementor/elementor/assets/140517427/c0729389-7fd0-4365-883b-3a93b3686b8b)

### Steps to reproduce

I don't know to reproduce this.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: http://dev-wahlen-organisieren.local
	Home URL: http://dev-wahlen-organisieren.local
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: dev-email@wpengine.local
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.15.0-dev5
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

== Elements Usage ==
	
	single-post : 2
		container : 6
		heading : 2
		loop-grid : 2
		theme-post-content : 2
		theme-post-title : 2
	wp-page : 1
		container : 3
		heading : 2
		loop-grid : 2
	loop-item : 4
		container : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header &amp; Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active

== Log ==
	
PHP: showing 3 of 3PHP: 2023-07-14 09:32:21 [notice X 1][C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor\core\upgrade\manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-14 09:46:25 [warning X 4][C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-14 09:46:25 [warning X 6][C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
#3: C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: C:\Users\lb\Local Sites\dev-wahlen-organisieren\app\public\wp-content\plugins\elementor\data\base\endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 4 of 4JS: 2023-07-14 09:40:44 [error X 2][http://dev-wahlen-organisieren.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:417985] Cannot read properties of null (reading &#039;history&#039;) 
JS: 2023-07-14 09:41:13 [error X 1][http://dev-wahlen-organisieren.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:1113620] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-07-14 09:44:22 [error X 1][http://dev-wahlen-organisieren.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:602454] Cannot read properties of null (reading &#039;id&#039;) 
JS: 2023-07-14 09:47:57 [error X 4][http://dev-wahlen-organisieren.local/wp-admin/load-scripts.php?c=1&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.2.2:2:31823] Cannot read properties of undefined (reading &#039;value&#039;) 

Log: showing 15 of 152023-07-17 13:32:19 [info] elementor::elementor_updater Started 
2023-07-17 13:32:19 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-17 13:32:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-17 13:32:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0-dev3',
)]
2023-07-17 13:32:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.0-dev3',
)]
2023-07-24 07:29:17 [info] elementor::elementor_updater Started 
2023-07-24 07:29:17 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-24 07:29:17 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-24 07:29:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev3',
  'to' => '3.15.0-dev4',
)]
2023-07-24 07:29:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev3',
  'to' => '3.15.0-dev4',
)]
2023-07-25 13:02:59 [info] elementor::elementor_updater Started 
2023-07-25 13:02:59 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-25 13:02:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-25 13:02:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev4',
  'to' => '3.15.0-dev5',
)]
2023-07-25 13:02:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev4',
  'to' => '3.15.0-dev5',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @LinusB,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and it's not quite intended for live websites.

Due to the experimental nature of this edition, we're unable to provide support for it. 

Please, [switch back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
