### ISSUE TITLE
elementor\core\kits\manager.php on line 323

### ISSUE THREAD

**Issue by shan140** [elementor/elementor#23271]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

elementor\core\kits\manager.php on line 323

### Steps to reproduce

elementor\core\kits\manager.php on line 323

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

elementor\core\kits\manager.php on line 323

**Comment by avivu** [comment]
This issue has been resolved in Elementor v3.15.1

Feel free to update

Thanks!
