### ISSUE TITLE
✅ 🔣 🐞 Bug Report: Taxonomy filter does not work with slug in Hebrew

### ISSUE THREAD

**Issue by roni-ravitz** [elementor/elementor#23315]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

If the taxonomy slug is in Hebrew, the new taxonomy filter widget does not work

### Steps to reproduce

1. Create taxonomies with an url in Hebrew
2. Add the taxonomies filter widget
3.  not working

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

.

**Comment by nicholaszein** [comment]
Hello @roni-ravitz, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards

**Comment by hein-obox** [comment]
A screencast would be helpful as well.

**Comment by roni-ravitz** [comment]
[system-info-chasiditube.com-10-09-2023.txt](https://github.com/elementor/elementor/files/12568161/system-info-chasiditube.com-10-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello there @roni-ravitz!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
