### ISSUE TITLE
⛔ 🛟 Support Request: MailerLite Integration asks for e-mail field twice

### ISSUE THREAD

**Issue by Justine0026** [elementor/elementor#23394]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I created an integration with MailerLite. But it’s asking two times the email address? See image attached. 

### Steps to reproduce

When only using the required top one, for form doesn't work. When using t
<img width="1112" alt="64d64adee62268e78de48dfe-Scherm_afbeelding 2023-08-11 om 16 39 35" src="https://github.com/elementor/elementor/assets/142116647/a0babda0-a0b7-4600-ad38-8ffced272ee6">
he lower one, is does work.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

https://my.elementor.com/wp-content/uploads/sites/2/gravity_forms/22-8fa82d82d4bd295a437b035bfb146a16/2023/08/system-info-hansvanderklok.com-11-08-2023.txt

**Comment by nicholaszein** [comment]
Hello @Justine0026,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

Follow the steps to correctly configure your MailerLite integration, especially the form fields in both Elementor and MailerLite:

https://elementor.com/help/mailerlite-and-elementor-integration/

Reach out to MailerLite support to understand why there are two fields for e-mail mapping.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
