### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by ianstudio** [elementor/elementor#2350]
Hi,
features I'd like to see:

LINKS FOR IMAGES
Possibility to add URL to a column's background image, so the whole column can "act as a button".
Same for the image image element.

IMAGE SOURCE
Ability to specify image source/size for column background image, just like you can in the image element. Anywhere an image can be invoked one should be able to choose the size form the library.

HOVER EFFECT
Have hover effects for a column background image, as is possible with an image element.
Also hover effect for texts or at least for titles/headlines.

GRADIENT FOR HEADLINES
For title elements.. Namogo's Elementor Extras has that, but since it is not compatible with WPML I cannot use it :/ Or maybe that could be part of the new Animated Headline.

**Comment by arielk** [comment]
Long time, but it's time to clean some old issues:

You can use this plugin for column links: https://wordpress.org/plugins/make-column-clickable-elementor/

For Gradient Text, you can follow this issue: https://github.com/elementor/elementor/issues/4676

Hover Effect we already add this in v1.5.0 https://elementor.com/blog/v150-hover-effect/

So thanks for your ideas,
