### ISSUE TITLE
❌ 🛟 Support Request: Name Shortcode is causing Email 2 server error

### ISSUE THREAD

**Issue by iSohaibKhan** [elementor/elementor#23513]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've created a form with email & email 2 in elementor but it's causing errors when I'm submitting, using this shortcode [field id="name"] in a "Message" field in email 2 but when I'm using this shortcode which I used in "To" field [field id="email"] it's working, I don't know what should I do what's the solution, kindly someone help I want to show in a replied auto mail the user's name. If there any other solution please let me know

### Steps to reproduce

1) Pasted the shortcode [field id="name"] in the Message field in email 2
2) Updated the form in Elementor
3) Fill the details & submit the form
4) Shows Email 2 Server error

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-block-end: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MySQL Community Server - (GPL) v5.7.42 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 128M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>

**Comment by nicholaszein** [comment]
Hello @iSohaibKhan,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

In your case, it is likely your **`name`** field has another ID. Make sure to copy or set the appropriate field ID for every field in their respective **`Advanced`** tab:

![image](https://github.com/elementor/elementor/assets/113993460/c498c85b-3149-414e-88a9-f12cd2cb36ce)

For more information about properly setting your Actions after Submit on Elementor Forms, please refer to the Help Center or contact Elementor Support.

https://elementor.com/help/actions-after-submit/

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

----

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

----

Thank you for understanding! 🙏 

Kind regards
