### ISSUE TITLE
Percentage padding, margin of FLEX elements in Firefox does not work

### ISSUE THREAD

**Issue by Gaspadlo** [elementor/elementor#2370]
**Description**
Using a percent values for padding/margin of columns does not work specifically in Firefox (not exactly an Elementor bug per se, but an issue nevertheless)

**workaround/Feature request**
Allow usage of Viewport units, as a somewhat relevant workaround
100vw = amount of viewport width pixels
100vh = height pixels

**Solution - Moz Hack recalculation**  -_-' 
10 **%**= 10 / number of columns **vw** *minus* pixels of column horizontal padding
(It just looks like a pain for generator and for final printed CSS as well, honestly it's just a messy hypothetical solution)

I have to admit percent & viewport units behave differently, BUT viewport units at least behave consistently across major browsers.

**Optional** (I haven't seen many people actually use it, but i do find it handy): Allow usage advanced calculation values - example:
_font-size: calc(6px + 1vw);_ = minimal size of 6pixels + 1% of viewport width pixels, result ~25px on FHD)

**Comment by arielk** [comment]
I'm closing an issue because we have no ability to change this behavior as long as it depends on the browser.

Thanks!
