### ISSUE TITLE
✅ 🐞 Row-reversed not working in mobile view (portrait mode).

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#23710]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The row-reversed does not work in mobile portrait mode. It works fine in desktop, table portrait and mobile landscape.
See video here: https://hei.vegardbell.no/v/WXJafA

### Steps to reproduce

1. Select mobile portrait mode.
2. Select row-reversed in the container.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-www.psykolog.belldigital.no-08-09-2023.txt](https://github.com/elementor/elementor/files/12558260/system-info-www.psykolog.belldigital.no-08-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello @elasticeye ! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello there @elasticeye!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.22.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
