### ISSUE TITLE
Menu widget wraps entire menu item in anchor tag when URL added

### ISSUE THREAD

**Issue by WebAgencyBlink** [elementor/elementor#23734]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the Elementor Menu Widget, you can choose to add a link to the top level menu items. There is a setting to open the dropdown content on click as well. When you do this though, the menu dropdown opens and you get redirected to the URL for the top menu item before being able to use the dropdown menu.

This is due to both icon and the text being wrapped in the anchor tag when it should just be the text that is a link and the icon used to open the dropdown.

### Steps to reproduce

1. Drag Menu Widget in
2. Activate dropdown content on a menu item
3. Add a url to the top menu item
4. Set the dropdown to open on click
5. Go to your preview and try opening the dropdown

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.24.0
	MySQL version: mariadb.org binary distribution v10.11.5-MariaDB-1:10.11.5+maria~ubu2004
	PHP Version: 8.0.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://stg-mcim24x7-staging.kinsta.cloud
	Home URL: https://stg-mcim24x7-staging.kinsta.cloud
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /resources/%postname%/
	Language: en-US
	Timezone: -4
	Admin Email: web@agencyblink.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.1.1
		Author: WP Engine

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	DynamicConditions
		Version: 1.6.2
		Author: RTO GmbH

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 10.2.3
		Author: HubSpot

	Lazy Load Control For Elementor
		Version: 0.0.2
		Author: Jose Mortellaro

	Safe SVG
		Version: 2.2.0
		Author: 10up

	Usersnap
		Version: 4.18
		Author: Usersnap

== Elements Usage ==
	
	archive : 2
		container : 29
		form : 2
		heading : 2
		loop-grid : 4
		shortcode : 1
		spacer : 5
		text-editor : 4
	container : 1
		container : 1
		heading : 1
		loop-grid : 1
		shortcode : 1
		text-editor : 1
	footer : 1
		container : 11
		form : 2
		heading : 3
		nav-menu : 2
		shortcode : 1
		text-editor : 6
		theme-site-logo : 1
	header : 1
		button : 9
		container : 26
		heading : 7
		icon : 1
		image : 3
		loop-grid : 1
		mega-menu : 1
		nav-menu : 5
		shortcode : 1
		text-editor : 4
		theme-site-logo : 2
	section : 2
		button : 1
		container : 3
		counter : 1
		heading : 1
		image : 1
		text-editor : 2
	widget : 0
		button : 2
	wp-page : 0
		animated-headline : 1
		button : 3
		container : 48
		counter : 3
		heading : 11
		image : 10
		nested-tabs : 1
		shortcode : 3
		text-editor : 6
	single-post : 7
		container : 127
		form : 1
		heading : 26
		image : 8
		loop-grid : 1
		shortcode : 14
		spacer : 6
		text-editor : 15
		theme-post-content : 2
		video : 1
	single-page : 10
		animated-headline : 2
		button : 12
		container : 254
		counter : 11
		form : 2
		heading : 44
		image : 18
		loop-grid : 3
		mega-menu : 1
		nested-tabs : 1
		shortcode : 17
		spacer : 22
		text-editor : 23
		theme-post-content : 1
	loop-item : 32
		button : 2
		container : 110
		counter : 1
		heading : 30
		icon : 7
		image : 29
		post-info : 2
		shortcode : 1
		text-editor : 25
		theme-post-excerpt : 1
		theme-post-title : 1
	error-404 : 1
		container : 9
		heading : 2
		shortcode : 1
		text-editor : 1

== Settings ==
	
	cpt_support: post, page, e-landing-page, case_study, platform_module, solution
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Lazy Load Control For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Lazy Load Control For Elementor: Incompatible

**Comment by Daveden2** [comment]
Elementor 3.16 is expected to fix the issues with the Elementor Menu Widget. You can follow the discussion [here](https://github.com/orgs/elementor/discussions/23486#discussioncomment-6822661). Please test the 3.16 beta release, see if your problems were solved, and provide feedback. Thanks!

**Comment by WebAgencyBlink** [comment]
Looks like the latest update did fix it.

**Comment by nicholaszein** [comment]
Hello there @WebAgencyBlink!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.16.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
