### ISSUE TITLE
✅ 🐞 Bug Report: HTML tags not rendering in the nested Tab Items Title fields - [ED-12178]

### ISSUE THREAD

**Issue by MikeLikesThat** [elementor/elementor#23752]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you upgrade to Elementor version 3.16+, HTML is no longer rendered in the Tab Items Title field.
If you go back to version 3.15.3, HTML will render in the Title field.

This is only apparent when you view a preview or live version of the page. The Editor view renders the HTML correctly.

Elementor Pro 3.16 does not affect the problem.

I tested on the Accordion widget's Items Title field and it is not affected.

Expecting:
![image](https://github.com/elementor/elementor/assets/81569362/6f05bedd-908c-4964-86d8-d3767d86a1a2)

Actual Result:
![image](https://github.com/elementor/elementor/assets/81569362/25bc96dd-84c7-4e86-8525-0ee33b38679d)

### Steps to reproduce

1. Insert the Tabs widget
2. Add HTML to Title, for example: `Tab<br/>#5`
3. Save and view the preview/live page

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 8.0.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL:
	Home URL:
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	Disable Gutenberg
		Version: 3.0
		Author: Jeff Starr

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.16.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0
		Author: Elementor.com

	JetEngine
		Version: 3.2.4
		Author: Crocoblock

	SiteGround Optimizer
		Version: 7.4.1
		Author: SiteGround

	SiteGround Security
		Version: 1.4.5
		Author: SiteGround


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Grid Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Global Style Guide: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
PHP: showing 2 of 2PHP: 2023-09-07 15:33:40 [notice X 1][../wp-content/plugins/elementor/app/modules/import-export/module.php::738] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-07 15:33:42 [notice X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-09-07 20:36:53 [error X 3][https://ln.leadnerds.io/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.15.3:2:55595] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 

Log: showing 14 of 142023-09-12 15:57:57 [info] elementor-pro::elementor_pro_updater Started 
2023-09-12 15:57:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-12 15:57:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-12 15:57:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-12 15:57:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-12 15:58:16 [info] elementor::elementor_updater Started 
2023-09-12 15:58:16 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 15:58:16 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 15:58:16 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-12 15:58:17 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-12 15:58:17 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 15:58:17 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 15:58:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.1',
)]
2023-09-12 15:58:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==



````

</details>

**Comment by jofbe** [comment]
I also have a problem since in 3.16.0 the new html structure was introduced. Since then, shortcodes in the title field are not rendered.

**Comment by maurocarreraok** [comment]
Same here. This happend with the last update for me.

**Comment by rwdesign-kamil** [comment]
Same for me. Is there some workaround for this?

**Comment by maurocarreraok** [comment]
@nicholaszein This is the one I've mentioned.

**Comment by nicholaszein** [comment]
Hello everyone! 

Thank you for your feedback! 🙏 

We are aware of this issue and our team is already working on a fix that should be released on the next patch! 😉

Best regards

**Comment by jofbe** [comment]
@nicholaszein , do you have a release date for this next patch?

**Comment by NAROLLES** [comment]
@nicholaszein On the same subject: an anchor located in the content of tab 1 to the anchor placed in the title of tab 2 does not work

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.16.4! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Thank you all for your patience and for the feedback on this issue. 🙏 

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Comment by nicholaszein** [comment]
@NAROLLES,

what you are reporting is not part of this issue. Please submit a new Bug Report with detailed information so we can take a look. Thanks.

**Comment by nicholaszein** [comment]
@NAROLLES,

what you are reporting is not part of this issue. Please share your feedback here: https://github.com/elementor/elementor/issues/22784

Thanks
