### ISSUE TITLE
✅ 🐞 Bug Report: Nested Accordion displays a second set of tab arrows on Safari

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#23807]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Noticed that on iphone, on a few different sites using the accordion widget with nested items, that it displays a second set of arrows in the tab that aren't displayed on desktop

![IMG_DD68DC896E0A-1](https://github.com/elementor/elementor/assets/24360965/6b7258b1-1641-4419-9a29-720e8c138347)

### Steps to reproduce

Turn on nested elements feature > Add accordion widget to a page and fill some tabs > view on an iPhone

Tested on Iphone 13 // IOS 16.6.1

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to Reveal</summary>	
			
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.42
	PHP Version: 7.4.33.4
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://aabug.mysites.io
	Home URL: https://aabug.mysites.io
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.15.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.0
		Author: Elementor.com

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

== Log ==
	
Log: showing 20 of 312023-06-28 07:45:37 [info] elementor-pro::elementor_pro_updater Started 
2023-06-28 07:45:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-28 07:45:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-28 07:45:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.14.1',
)]
2023-06-28 07:45:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.14.1',
)]
2023-08-15 21:18:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-15 21:18:57 [info] elementor-pro::elementor_pro_updater Started 
2023-08-15 21:18:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-15 21:18:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-15 21:18:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-15 21:19:08 [info] elementor::elementor_updater Started 
2023-08-15 21:19:08 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-15 21:19:08 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-15 21:19:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.2',
)]
2023-08-15 21:19:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.15.2',
)]
2023-09-05 15:26:28 [info] elementor::elementor_updater Started 
2023-09-05 15:26:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-05 15:26:29 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-05 15:26:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]
2023-09-05 15:26:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]

PHP: showing 4 of 4PHP: 2023-05-17 00:06:23 [warning X 84][/www/wp-content/plugins/elementor/includes/db.php::267] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-24 06:31:09 [error X 1][/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::304] Uncaught Error: Call to a member function update_meta() on null in /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:304
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(177): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6271, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /wordpress/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/admin-ajax.php(188): do_ac [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-06 18:28:17 [notice X 2][/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-06 19:26:34 [notice X 2][/www/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-05-17 02:41:32 [error X 2][https://dfpromise.mysites.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:1097282] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-05-17 04:42:26 [error X 2][https://dfpromise.mysites.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:939973] Cannot read properties of undefined (reading 'settings') 
JS: 2023-07-24 16:47:51 [error X 4][https://ohioansunitedforreproductiverights.win/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.14.1:3:82386] Data commands: `` not found. 
JS: 2023-09-06 21:39:34 [error X 32][https://our.mysites.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:620581] Cannot read properties of null (reading 'model') 
JS: 2023-09-06 21:39:58 [error X 5][https://our.mysites.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:740720] this.manager.setPage(...).showView is not a function 
JS: 2023-09-06 21:40:09 [error X 1][https://our.mysites.io/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading 'value') 
JS: 2023-09-06 21:49:46 [error X 1][https://our.mysites.io/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:189752] Cannot read properties of null (reading 'activeTab') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
</details>

**Comment by portrayaloflife** [comment]
Found a temporary fix below, looks like it's a new IOS addition to all accordion-type elements, would be great for y'all to add this fix in

`summary::-webkit-details-marker {
display: none;
}`

**Comment by nicholaszein** [comment]
This issue was fixed in [Elementor Core 3.15.2](https://wordpress.org/plugins/elementor/#developers:~:text=%2323329)-,Fix%3A%20Redundant%20accordion%20icon%20appears%20when%20using%20Safari%20browser%20in%20Accordion%20widget,-3.15.1%20%E2%80%93%202023%2D08).

Please before posting make sure you have the latest version installed.

**Comment by portrayaloflife** [comment]
Ah great to see! A bit of issues with the latest versions so we haven't been able to update just yet. Hopefully, everything gets ironed out soon, appreciate all your hard work!

**Comment by nicholaszein** [comment]
@portrayaloflife version 3.15.2 was released on August, 9, 2023!

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
