### ISSUE TITLE
❌ 🛟 Support Request: Elementor's Google AdWords Ads have a Typo

### ISSUE THREAD

**Issue by jmdfernandes** [elementor/elementor#23833]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

I wanted to log in to Elementor and when I opened the Google page, I ended up with a surprise.
A big company like Elementor does not spell its own name correctly.

Instead  of Elementor is written 4  times **Elemantor**

see screenshot -  https://prnt.sc/gU-5btCH4gPU

![image](https://github.com/elementor/elementor/assets/113993460/7adc4f35-161d-4301-a87d-fa2c73fbd3c6)

I visited the page because I am considering upgrading my version. But 25 websites is a bit too much money.
Do you think that by pointing out this mistake I could get a decent discount???

Best regards
Jose

### Steps to reproduce

not available

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

**I used this support page because is the only way I found to alert for this issue**

**Comment by nicholaszein** [comment]
Hello @jmdfernandes,

Thanks for pointing that out! I'll make sure to let the department responsible for ads to correct this typo. 🙏 

However, this is not a support page. Please use this repository only to report Bugs with the Elementor Editor plugin.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards

**Comment by nicholaszein** [comment]
Hello @jmdfernandes.

I just confirmed with our Marketing team. **The ad you are seeing is not from Elementor**. It's from someone pretending to be Elementor.

If possible, could you be so kind as to share the full links from that ad with us here?

We would like to take action and request the removal of the fraudulent ad.

Thanks

**Comment by jmdfernandes** [comment]
Hello,

 

I have taken the following steps to reproduce yesterday search:

1.	Yesterday  screenshot 1 -elementor  ( elemantor )

             https://prnt.sc/gU-5btCH4gPU

2.	I have inserted the same address as per the above  screenshot 1





Hope that this can help you. 

Best regards

Jose Fernandes

**Comment by nicholaszein** [comment]
Hi, @jmdfernandes.

Thank you for your reply! 🙏 

Could you please do the following?

1. Use the same search term.
2. If the ad reappears, click the ellipsis menu at the top (see image below).
3. A modal will appear with the data information of the advertiser. Please take a screenshot of that screen.
4. Then click on the first link in the ad, and take a screenshot of the Address Bar of the browser with the entire link that will appear.
5. Send both screenshots to us. We would really appreciate it!

![image](https://github.com/elementor/elementor/assets/113993460/a1aae6b4-aa23-4c81-82cb-06be87623ac5)


Kind regards

**Comment by jmdfernandes** [comment]
Hello Nicholas,

 

Please follow the screenshots. This time there is a mistake with an accent on the 2nd letter “e” of Elementor

 

 

1  -  https://prnt.sc/yQKq7AhJtaO-    

-page image . search "elementor log in"



2 -  <https://prnt.sc/XtZNYb-hfIFk> https://prnt.sc/XtZNYb-hfIFk     -   3 dots

 

3 -  <https://prnt.sc/Algfwk3fB6ry> https://prnt.sc/Algfwk3fB6ry   -  new page -  then click

 

4 -  <https://prnt.sc/9PrJPEGj69WF> https://prnt.sc/9PrJPEGj69WF  -  new page with prices

Best regards

 

Jose

**Comment by nicholaszein** [comment]
Hey @jmdfernandes!

Please understand these are not official Elementor ads. They are not controlled by Elementor. These are affiliates who are breaking their affiliation contract by promoting Elementor and using their own language and affiliate links. We have no control over this.

However, we can track who is doing this and penalize them if we have the affiliate information. Unfortunately, though I can't see the same ads as you do, so I can't find the affiliate information. Unless you follow the steps I gave in my last comment and provide me with that information.

Taking a screenshot of the search results page doesn't help.

If you are willing to share the information with us, maybe we can do something about it.

Your contribution is really appreciated.

Kind regards.

**Comment by jmdfernandes** [comment]
Hello Nicholas,

 

The affiliation details  are found on the top address bar

 

https://prnt.sc/osg1PPcbbv0x

 

Please advise

José

**Comment by nicholaszein** [comment]
Thank you @jmdfernandes!

That's all we needed. I'll be passing this along to the team responsible for affiliates.

In the future, if you see an ad with orthographic errors, please click on the ellipsis button at the side of the form, and then select "Report Ad" at the top of the modal that will appear and follow Google's instructions.

![image](https://github.com/elementor/elementor/assets/113993460/5088896a-1544-4fb3-94e0-105747821f5d)

While we do appreciate your efforts to report this, Elementor GitHub Issues are not intended to be used for this kind of report. This was an exception. We will not accept new issues that are not related to the Elementor plugin.

Official Elementor Ads are proofread before being published and do not include affiliate links. These ads made by 3rd-party affiliates go against our terms of affiliation. While we do take action and have scripts that run to catch the offending affiliates, we cannot prevent these ads from being posted on Google.

If you still think you want to report these, please do so by sending your findings to affiliates@elementor.com.

Thank you, and best regards!

I am closing the comments for this issue.
