### ISSUE TITLE
Icons missing when hiding another container in responsive settings

### ISSUE THREAD

**Issue by lw-development** [elementor/elementor#23866]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi there,

I have recently been experiencing an issue where SVG icons within icon box widgets are missing when hiding another container within the responsive settings. When I have two containers with the same icons and hide one on certain devices, the icons within the other container disappear and cannot be seen on the frontend. 

This can be seen [here](https://ghost.10web.site/careers/) as an example.

Thanks,
Louis

### Steps to reproduce

1. Add icon box widgets in a container
2. Duplicate this container 
3. Hide the first container on mobile (as an example)
4. The icons within the icon box widgets in the duplicated container will disappear 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.6
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://ghost.10web.site
	Home URL: https://ghost.10web.site
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: louis@louiswebsdale.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	10Web Booster
		Version: 2.23.16
		Author: 10Web - Website speed optimization team

	Advanced Custom Fields
		Version: 6.2.1
		Author: WP Engine

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Forminator
		Version: 1.26.0
		Author: WPMU DEV

	Page scroll to id
		Version: 1.7.8
		Author: malihu

	Rank Math SEO
		Version: 1.0.201.1
		Author: Rank Math

	WPCode Lite
		Version: 2.1.2
		Author: WPCode

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	10WEB
		Version: 1.9.0
		Author: 10WEB

== Elements Usage ==
	
	container : 1
		button : 1
		container : 9
		text-editor : 3
	footer : 1
		container : 9
		heading : 5
		icon-list : 2
		image : 1
		nav-menu : 4
		social-icons : 1
	header : 1
		container : 3
		image : 1
		nav-menu : 1
		social-icons : 1
	wp-post : 0
		button : 14
		container : 140
		heading : 14
		icon-box : 56
		image : 6
		nested-accordion : 7
		template : 7
		text-editor : 28
		video : 1
	wp-page : 5
		button : 9
		container : 70
		heading : 15
		icon-box : 36
		image : 3
		loop-grid : 1
		nested-accordion : 3
		nested-carousel : 1
		search-form : 1
		shortcode : 1
		text-editor : 42
		video : 1
	single-post : 1
		button : 1
		container : 4
		heading : 2
		loop-grid : 1
		post-info : 1
		theme-post-content : 1
		theme-post-featured-image : 1
	search-results : 1
		container : 1
		heading : 1
		loop-grid : 1
		search-form : 1
	loop-item : 1
		call-to-action : 1
		container : 1

== Settings ==
	
	cpt_support: post, page, services
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

== Log ==
	
JS: showing 3 of 3JS: 2023-09-12 15:24:19 [error X 1][https://ghost.10web.site/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.15.3:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-09-18 13:27:09 [error X 1][https://ghost.10web.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:925647] Cannot read properties of undefined (reading 'route') 
JS: 2023-09-18 13:27:11 [error X 1][https://ghost.10web.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:742356] Cannot read properties of undefined (reading 'widgets_settings') 

PHP: showing 6 of 6PHP: 2023-09-12 15:30:50 [notice X 9][/home/wplive/web/wp-live/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-12 20:46:42 [warning X 13][/home/wplive/web/wp-live/wp-content/plugins/elementor/core/files/file-types/svg.php::158] libxml_disable_entity_loader() has been disabled for security reasons [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-13 08:31:32 [notice X 4][/home/wplive/web/wp-live/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-13 08:37:59 [notice X 2][/home/wplive/web/wp-live/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-18 13:08:44 [notice X 2][/home/wplive/web/wp-live/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-18 13:08:44 [notice X 2][/home/wplive/web/wp-live/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/wplive/web/wp-live/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/wplive/web/wp-live/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/wplive/web/wp-live/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/wplive/web/wp-live/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by lw-development** [comment]
The issue was file specific rather than an Elementor issue.

**Comment by nicholaszein** [comment]
Hi, @lw-development.

Thank you for closing the issue and sharing your solution. 🙏

I am closing the comments on this issue.
