### ISSUE TITLE
❌ Invalid issue

### ISSUE THREAD

**Issue by joomskys** [elementor/elementor#23885]
@dc-z 	

Our the `render_icons()` method is used to render and not get to a var. 
We will look into adding that kind of functionality if we actually see a need for it.

For now, you can always wrap your call with a simple `ob_*` functions, ex:

```PHP
ob_start()
Icons_Manager::render_icon( $settings['selected_icon'], [ 'aria-hidden' => 'true' ] );
$icon_html = ob_get_clean();
```

thanks.

_Originally posted by @bainternet in https://github.com/elementor/elementor/issues/8520#issuecomment-510368937_

**Comment by joomskys** [comment]
@bainternet  and you help me ?
i tried you solution, 
all working file when i choose icon is  font-icon
but it not show  when i upload an SVG icon!

Thanks

**Comment by nicholaszein** [comment]
Hello @joomskys,

please do not post issues by selecting to reference a comment in a new issue. Instead, use the [New Issue](https://github.com/elementor/elementor/issues/new/choose) form.

Thanks
