### ISSUE TITLE
🔗 ⛔ 🐞 Bug Report: My content on almost most of my pages created with Elementor desappeared!!! (Duplicate of #23780)

### ISSUE THREAD

**Issue by SilviaSchnell** [elementor/elementor#23897]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Hello!

I have created my webpage with Elementor, and all suddendly ALL my content on my pages created with Elementor disappeared and I have to rewrite and redesign and add all the links to ALL my pages again!!!!!!!!!!!

WHY???? 

My webpage with its content was working fin a few days ago, and now it looks like I have to start from CERO ????? What happened??

Please send me a solution for this proble as soon as possible!! Otherwise I will never use Elementor again! I can´t afford such kind of issues!

Thanks
Best
Silvia

### Steps to reproduce

Hello!

I have created my webpage with Elementor, and all suddendly ALL my content on my pages created with Elementor disappeared and I have to rewrite and redesign and add all the links to ALL my pages again!!!!!!!!!!!

WHY???? 

My webpage with its content was working fin a few days ago, and now it looks like I have to start from CERO ????? What happened??

Please send me a solution for this proble as soon as possible!! Otherwise I will never use Elementor again! I can´t afford such kind of issues!

Thanks
Best
Silvia

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.41
	PHP Version: 7.4.33
	PHP Memory Limit: 268435456
	PHP Max Input Vars: 1000
	PHP Max Post Size: 67108864
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://kaleida-creations.com
	Home URL: https://kaleida-creations.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Krystal
	Version: 1.4.8
	Author: Spiracle Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	1&amp;1 WP Assistant
		Version: 5.1.0
		Author: 1&1

	a3 Lazy Load
		Version: 2.7.0
		Author: a3rev Software

	Antispam Bee
		Version: 2.11.5
		Author: pluginkollektiv

	Breadcrumb NavXT
		Version: 7.2.0
		Author: John Havlik

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.16.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.16
		Author: Brainstorm Force, Nikhil Chavan

	Envato Elements
		Version: 2.0.12
		Author: Envato

	EU Cookie Law
		Version: 3.1.6
		Author: Alex Moss, Marco Milesi

	Forminator
		Version: 1.26.0
		Author: WPMU DEV

	Image Hover Effects - Elementor Addon
		Version: 1.3.8
		Author: Blocksera

	MailerLite - Signup forms (official)
		Version: 1.6.13
		Author: MailerLite

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Redirection
		Version: 5.3.10
		Author: John Godley

	Royal Elementor Addons
		Version: 1.3.77
		Author: WP Royal

	SiteOrigin CSS
		Version: 1.5.8
		Author: SiteOrigin

	Stratum - Elementor Widgets
		Version: 1.3.15
		Author: MotoPress

	Toolbar Extras
		Version: 1.4.9
		Author: David Decker - DECKERWEB

	UpdraftPlus - Backup/Restore
		Version: 1.23.10
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 8.1.1
		Author: Automattic

	Yoast SEO
		Version: 21.2
		Author: Team Yoast


== Must-Use Plugins ==
	1&amp;1 Product Subdomain
		Version: 1.1.0
		Author: 1&1


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Active by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default


== Log ==
	
Log: showing 20 of 282023-03-20 21:08:31 [info] elementor::elementor_updater Started 
2023-03-20 21:08:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-20 21:08:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-20 21:08:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev1',
  'to' => '3.13.0-dev2',
)]
2023-05-07 18:04:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev4',
)]
2023-05-07 18:04:11 [info] elementor::elementor_updater Started 
2023-05-07 18:04:11 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-07 18:04:11 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-07 18:04:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev4',
)]
2023-05-07 18:04:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev2',
  'to' => '3.13.0-dev4',
)]
2023-06-11 17:22:05 [info] elementor::elementor_updater Started 
2023-06-11 17:22:05 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-11 17:22:05 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-11 17:22:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.0-dev4',
  'to' => '3.14.0-dev3',
)]
2023-07-28 09:59:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev3',
  'to' => '3.15.0-dev6',
)]
2023-07-28 09:59:14 [info] elementor::elementor_updater Started 
2023-07-28 09:59:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-28 09:59:14 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-28 09:59:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev3',
  'to' => '3.15.0-dev6',
)]
2023-07-28 09:59:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0-dev3',
  'to' => '3.15.0-dev6',
)]

JS: showing 9 of 9JS: 2023-03-06 15:54:10 [error X 1][https://kaleida-creations.com/wp-admin/post.php?post=13438&amp;action=elementor:9:22] Cannot read properties of undefined (reading &#039;length&#039;) 
JS: 2023-03-22 13:54:49 [error X 3][https://kaleida-creations.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 
JS: 2023-03-29 15:57:10 [error X 5][https://kaleida-creations.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] elementor_new_template_form_controls is not defined 
JS: 2023-04-13 22:01:56 [error X 5282][https://kaleida-creations.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-04-13 22:02:02 [error X 94][https://kaleida-creations.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2023-04-14 17:25:57 [error X 1][https://kaleida-creations.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.0-dev2:3:790484] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-06-11 17:24:35 [error X 1][https://kaleida-creations.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-dev3:3:601348] Cannot read properties of null (reading &#039;id&#039;) 
JS: 2023-06-11 17:48:04 [error X 1][https://kaleida-creations.com/wp-content/plugins/inavii-social-feed-for-elementor/assets/react/static/js/inavii-social-feed-app.min.js?ver=2.0.4:2:128904] Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
JS: 2023-06-11 19:06:22 [error X 6][https://kaleida-creations.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-dev3:3:806416] Cannot read properties of undefined (reading &#039;localized&#039;) 

PHP: showing 5 of 5PHP: 2023-03-29 15:55:04 [notice X 17][../wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-13 22:31:15 [notice X 1][../wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-11 18:25:45 [error X 1][../wp-content/plugins/elementor/includes/template-library/sources/local.php::1112] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in ../wp-includes/class-wp-hook.php on line 310 and defined in ../wp-content/plugins/elementor/includes/template-library/sources/local.php:1112
Stack trace:
#0 ../wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local-&gt;on_save_post()
#1 ../wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 ../wp-includes/post.php(4715): do_action()
#4 ../wp-includes/post.php(4817):  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-28 10:00:27 [notice X 14][../wp-content/plugins/elementor/core/kits/manager.php::323] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-28 11:43:05 [error X 1][../wp-content/plugins/elementor/includes/template-library/sources/local.php::1113] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in ../wp-includes/class-wp-hook.php on line 310 and defined in ../wp-content/plugins/elementor/includes/template-library/sources/local.php:1113
Stack trace:
#0 ../wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local-&gt;on_save_post()
#1 ../wp-includes/class-wp-hook.php(332): WP_Hook-&gt;apply_filters()
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 ../wp-includes/post.php(4715): do_action()
#4 ../wp-includes/post.php(4817):  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified
	Image Hover Effects - Elementor Addon: Compatibility not specified
	Royal Elementor Addons: Compatibility not specified
	Stratum - Elementor Widgets: Compatibility not specified

````

</details>

[system-info-kaleida-creations.com-26-09-2023.txt](https://github.com/elementor/elementor/files/12725079/system-info-kaleida-creations.com-26-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello @SilviaSchnell,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

I see two problems with your website:

1. You are using the Elementor Beta (Developer Edition) plugin on a production website. This plugin should **never** be used on production websites. It's an unstable plugin meant to be used by developers to test their plugins against the latest new features of Elementor to maintain compatibility, nothing else. Please, [revert back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.
![image](https://github.com/elementor/elementor/assets/113993460/a9c44c1d-eb15-455a-b6cf-2fbef36748cc)

2. We see you are using multiple Elementor add-ons, that may not be compatible with the latest version. Before updating Elementor, you should always check if the add-ons installed on your website are compatible. If they are not, you need to reach out to the developers of the add-ons.

3. The problem you are reporting seems to be a combination of bad cache, conflict with add-ons, and inactive experiments. Please try following these steps:
    1. Make a backup of your site, and if possible do this on a staging environment;
    2. Temporarily deactivate all Elementor add-ons:
        - Elementor HJeader & Footer Builder;
        - Image Hover Effects - Elementor Addon;
        - Royal Elementor Addons;
        - Stratum - Elementor Widgets;
    3. [Revert from the developer edition to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/). Preferably version 3.16.4 or newer; 
    4. Run the Elementor Data Updater after the update (a WordPress notice might appear in your Admin area);
    5. Clear, purge, and temporarily deactivate all levels of cache applicable to your website. This includes Server Cache (contact your hosting support), and browser cache;
    6. You seem to be using the **Flexbox Container** feature. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page and make sure the **`Flexbox Container`** experiment is set to **`Active`**. 
    7. You seem to have the **Improved CSS Loading** experimental feature also active. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page and make sure the **`Improved CSS Loading`** experimental feature is set to **`Inactive`**.
    8. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** page and click to **`Regenerate CSS & Data`**.

If after following these steps you are still experiencing issues, please ask for help in the WordPress community or follow the instructions in the [other issue](https://github.com/elementor/elementor/issues/23780) that is on the same subject.


### ⚠️ Please note I am making this reply as a one-off courtesy. We don't provide support on this GitHub, and you should not use it to get support. What you are reporting is not an Elementor Bug. 

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
