### ISSUE TITLE
🐘 🐞 Bug Report: Container implementation of logical CSS properties throws a Deprecation Warning with PHP 8.2

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#23891]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Got alert after update to v3.16.x in PHP 8.2.x Environment.

```
Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_start is deprecated in /usr/local/lsws/domain.com/html/wp-content/plugins/elementor/includes/elements/container.php on line 42

Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated in /usr/local/lsws/domain.com/html/wp-content/plugins/elementor/includes/elements/container.php on line 43
```

### Steps to reproduce

Create Blank WordPress 6.3.1

Add Elementor 3.16.4 Plugin
Add Elementor Pro 3.16.2 Plugin
Create a Page => Edit with Elementor
View Page
=> Got Warning, Issue

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.22
	PHP Version: 8.2.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://domain.com
	Home URL: https://domain.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 1024M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0

== Active Plugins ==
	Elementor
		Version: 3.16.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

````

</details>

**Comment by Barcov** [comment]
@datverse this notice is about a pending change to an upcoming release and is not a breaking change. 
You should not normally see this kind of notice on your site unless you have WP_DEBUG enabled in wp-config.php

Can you try and update this constant in wp-config.php?
`define( 'WP_DEBUG', false );`

**Comment by jerturowetz** [comment]
Since upgrading to PHP 8.2 I'm getting the same warning on several dynamic properties. For example:

```
Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_start is deprecated in /var/www/html/wp-content/plugins/elementor/includes/elements/container.php on line 42
Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated in /var/www/html/wp-content/plugins/elementor/includes/elements/container.php on line 43
```

While dynamic properties [are only deprecated in php 8.2](https://php.watch/versions/8.2/dynamic-properties-deprecated), these will be fatal errors in 9.0. This is arbitrarily easy to fix by defining the property at the top of the classes.

Just as a point of reference, WP Engine (one of the largest managed WordPress hosts) is force upgrading users from 8.0 to 8.2 so I think this merits a patch.

**Comment by KingYes** [comment]
Fixed in this PR: https://github.com/elementor/elementor/pull/24009
