### ISSUE TITLE
❌ 🛟 Support Request: Can't edit or use Accordion

### ISSUE THREAD

**Issue by drew355** [elementor/elementor#23903]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi there.. I logged in today to continue building my site, and half my accordions are frozen in place. Yesterday it was working perfectly. The first drop down is visible and the other titles are visible, but I cannot click on any of the information and no drop downs occur. Its frozen. I cant even highlight the dialogue. Its as if it doesn't exist, but its visible. This happens both on the edit side and on the live website side. Please help. I have 3 months worth of work on these accordions throughout  the website. 

I have noticed that the accordions were recently updated on elementor this month September 2023. I was using the previous accordions. 

Please help me on this. Thanks 

### Steps to reproduce

The issue is continuous. I tried rolling back updates and the issue is still there. it was working fine yesterday. I noticed if I delete Elementor Developer beta it deletes all my accordions. Again. Half my accordions work, and the other half are frozen. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Wordpress with my current elementor Pro with auto updates. I tried rolling back old updates and the problem is still there.

**Comment by drew355** [comment]
for about three minutes. between 2:40- 2:43 PM PST they all worked again and seemed to have updated to the new accordion, but then it went back to being the old accordion and frozen.

**Comment by nicholaszein** [comment]
Hello @drew355, 

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

You also did not provide the required Elementor System Info that would allow us to verify if this is a bug. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
