### ISSUE TITLE
Programatically set options in select field form

### ISSUE THREAD

**Issue by zovatrop** [elementor/elementor#23958]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've looked to see if this problem has been discussed but I haven't found anything about it.

The feature described in https://github.com/elementor/elementor/issues/6030 doesn't work. Maybe the form item filters have been changed?

Is possible to set choices in form select dropdown programatically?

### Steps to reproduce

1. I set choices programatically as described in https://github.com/elementor/elementor/issues/6030
2. Nothing happens

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.38
	PHP Version: 8.1.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: Europe/Madrid
	Admin Email: desarrollo@portavoz.net
	Debug Mode: Inactive

== Theme ==
	Name: Orenes Gran Casino
	Version: 1.0
	Author: Portavoz / Samuel E. Cerezo
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by nicholaszein** [comment]
Hello @zovatrop!

Thanks for reaching out! 🙏 

Please, before posting a Bug Report about using the Elementor Developer API, make sure you have read the [Developer Documentation](https://developers.elementor.com/docs/).

Thank you
