### ISSUE TITLE
[Feature Request] Adding the 'Background Overlay' section option to the Images Widget

### ISSUE THREAD

**Issue by enviedbymost** [elementor/elementor#2401]
When adding an image, it doesn't always 'fit' with the other elements on a page.

It would be really helpful if I could add a color overlay on top of the image (using a brand color), and then lowering the opacity to say 20%, giving everything a consistent look.

This feature is available under section > advanced > background overlay, but if the section has other widgets in there, you don't want to use the background overlay across all of them, just the image!

**Comment by jayalove** [comment]
I second this request 😉

**Comment by arielk** [comment]
You can achieve the same behavior by using Style > Hover > CSS Filter 

![image](https://user-images.githubusercontent.com/1778512/75237543-35729980-57c8-11ea-9175-8b4812995fc4.png)
