### ISSUE TITLE
✅ 📚 🧩 🐞 Elementor Pro composer install: Failed to download elementor/elementor-pro from dist (version 3.16.2)

### ISSUE THREAD

**Issue by gino-lim-schoeters** [elementor/elementor#24046]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When deploying our projects with Elementor Pro included and using composer to install, we get the following error:

`Failed to download elementor/elementor-pro from dist: The "https://composer.elementor.com/download/3.16.2" file could not be downloaded (HTTP/2 500 )`

### Steps to reproduce

Install Wordpress and Elementor, Elementor Pro with composer (https://developers.elementor.com/docs/cli/composer/#install-elementor-pro)

  "require": {
    "elementor/elementor-pro": "^3.16", (currently using 3.16.2

Important: This happens on deploy + locally with clean composer cache! This worked before (last week), so this seems to be a very recent problem.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

Not applicable

**Comment by juhojama** [comment]
Confirmed. Using official instructions found here: https://developers.elementor.com/docs/cli/composer/

`$ composer require elementor/elementor-pro:3.16.2
./composer.json has been updated
Running composer update elementor/elementor-pro
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading elementor/elementor-pro (3.15.0 => 3.16.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading elementor/elementor-pro (3.16.2)
  - Downloading elementor/elementor-pro (3.16.2)
  - Downloading elementor/elementor-pro (3.16.2)
  - Downloading elementor/elementor-pro (3.16.2)
    Failed to download elementor/elementor-pro from dist: The "https://composer.elementor.com/download/3.16.2" file could not be downloaded (HTTP/2 500 )
    Now trying to download from source
  - Syncing elementor/elementor-pro (3.16.2) into cache`

This should not be a token problem since installing with invalid token responds with `Invalid credentials (HTTP 401)` error.

**Comment by Preen** [comment]
Can also confirm:

```bash
  Cloning into bare repository '/Users/xxx/Library/Caches/composer/vcs/git-github.com-elementor-elementor-pro.git'...                   
  remote: Repository not found.                                                                                                                      
  fatal: repository 'https://github.com/elementor/elementor-pro.git/' not found  
  ```

**Comment by Preen** [comment]
I think its fubar that this isnt looked at sooner, its a paid premium software.

**Comment by dojocreative** [comment]
Same issue here.

**Comment by Preen** [comment]
I created a fork with the fix. and made these changes to my composer.json for a temp fix:

https://github.com/SkimSafe-AB/php-ga-measurement-protocol/tree/guzzle-fix

Composer.json [repositories]
```json
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/SkimSafe-AB/php-ga-measurement-protocol"
    }
  ],
 ```
 Composer.json [require]
 ```json
   "require": {
    "theiconic/php-ga-measurement-protocol": "dev-guzzle-fix",
  }
```

**Comment by Kilbourne** [comment]
It returns 500 Code from Cloudfare with this description 'Worker threw exception'.
One week and no one checked this..

**Comment by paulpoweredbycoffee** [comment]
I'm having the same problem here. 

```
composer show -a elementor/elementor-pro
```

is also not showing the latest version - 3.17.0

```
name     : elementor/elementor-pro
descrip. : WordPress website builder, with no limits of design. A website builder that delivers high-end page designs and advanced capabilities, never before seen on WordPress.
keywords : 
versions : * 3.16.2, 3.16.1, 3.16.0, 3.15.1, 3.15.0, 3.14.1, 3.14.0, 3.13.2, 3.13.1, 3.13.0, v3.12.3, v3.12.2, v3.12.1, v3.12.0, v3.11.7, v3.11.6, v3.11.5, v3.11.4, v3.11.3, v3.11.2, v3.11.1, v3.11.0, v3.10.3, v3.10.2, v3.10.1, v3.10.0, v3.9.2, v3.9.1, v3.9.0, v3.8.2, v3.8.1, v3.8.0, v3.7.7, v3.7.6, v3.7.5, v3.7.4, v3.7.3, v3.7.2, v3.7.1, v3.7.0, v3.6.5, v3.6.4, v3.6.3, v3.6.2, v3.6.1
```

**Comment by pehbehbeh** [comment]
Same here. So nobody is able to install Elementor Pro right now? Our pipelines have been down for two weeks now. We have tried downgrading to another version... with no success. All versions seem to be affected.

Can you please take a look at this? @danielkatz @KingYes @StyleShit

**Comment by Preen** [comment]
@pehbehbeh you can use my fork for the time being.

**Comment by pehbehbeh** [comment]
> @pehbehbeh you can use my fork for the time being.

Thank you, I have already looked into this. I am struggling to understand your workaround. I do not see anything related to **elementor-pro** in **php-ga-measurement-protocol**. How is this supposed to replace the missing package? 🤔

**Comment by Preen** [comment]
@pehbehbeh Sorry, im COMPLETELY OFF the grid, was on the wrong repo. It doesnt have anything to do with this. SORRY!! Will remove my message.

**Comment by gdonoso94** [comment]
3 weeks so far 👎🏻

**Comment by juhojama** [comment]
@gdonoso94 Given the current count of over 3000 open issues and the fact that it took around four years to release the composer installation feature, I wouldn't hold my breath event though this is a paid premium software :smile:

**Comment by markeasting** [comment]
Same issue here, asked premium support but got redirected here. 

The http-basic auth seems to be working, but the server is responding with a server error (500). 
Composer then tries to download from source, but this requires access to the (private) github repository. 

Given that this paid software, I'd expect a bit more support for downloading and installing via methods that are in the **official** documentation...

**Comment by Preen** [comment]
We are now moving away from Elementor for all of our future projects. This is insanely bad from a paid software perspective.

**Comment by gabrielbonifacio** [comment]
Same issue.

**Comment by Davidwmccullah** [comment]
Same issue here.

**Comment by gluoksnis** [comment]
Same issue here.

**Comment by etraininteractive** [comment]
Also frustrated by this issue!

**Comment by lamda** [comment]
Same problem

**Comment by gianmarco27** [comment]
@kobizz i'm honestly really sorry to tag you here like this.
This issue is being ignored, but having pipelines unable to run for over 1 month on a premium product is kind of a critical problem.
Is there a way this issue could be looked into? Or at least triaged?

**Comment by cjstage** [comment]
Same issue here... Can someone please address this?

**Comment by abecuwedahive** [comment]
same issue over here...

**Comment by mvtenney** [comment]
I dealt with premium support as well, 1st level wasn't even aware that elementor-pro had composer support. 2nd level tried to assist, but eventually said that it was not in their support wheelhouse and to post to github issues.

**Comment by broskees** [comment]
Same here!

**Comment by dorshiff** [comment]
Same here, support says they are not supporting this kind of issue.
Any workaround?

**Comment by trsteel88** [comment]
@nicholaszein anything you can do here? Looks like you completed the original https://github.com/elementor/elementor/issues/4042

**Comment by StudioEvolDev** [comment]
Same here!

**Comment by cjstage** [comment]
I wish they wouldn't ignore this.  This is when people will start taking it in their own hands and hosting alternative repositories, which I'm sure elementor will have a problem with.  It's not like this is an open source project either, we're all paying customers...

**Comment by mikestolleronline** [comment]
Same issue.

**Comment by silaswint** [comment]
Getting

`atob() called with invalid base64-encoded data. (Only whitespace, '+', '/', alphanumeric ASCII, and up to two terminal '=' signs when the input data length is divisible by 4 are allowed.)`

for 

curl --location 'https://composer.elementor.com/download/3.16.2' \
--header 'Authorization: Bearer <ELEMENTOR LICENSE KEY>'

**Comment by gianmarco27** [comment]
Today i managed to download again properly elementor-pro up to version 3.18.2.
Thank you for looking into this!

**Comment by trsteel88** [comment]
> Today i managed to download again properly elementor-pro up to version 3.18.2. Thank you for looking into this!

Still failing for me. Did you do anything special?

**Comment by gianmarco27** [comment]
> Still failing for me. Did you do anything special?
Nope, i just tryed to update my dependencies and downloaded correctly  3.18.2 and 3.18.3 (it was served by Varnish by what i can see in the headers), 
after you mentioned me i tryed to download past versions like 3.6.1 as reported available by [this page](https://composer.elementor.com) as well as version 3.19 and both failed with the same error reported in the issue

**Comment by ikanc** [comment]
Had the same issue today.

Spoke with Elementor's support, who suggested that the fix would be to install it through the wp-admin interface.. smh.

Later on, after a few escalations, the dev team closed the ticket saying that it's a GitHub issue, and I should open a ticket to GitHub.

Ugh. Anyone has any solution for this?

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for all the feedback and for your patience.

This issue has been solved, and you can now install Elementor Pro via composer [following the instructions in the documentation](https://developers.elementor.com/docs/cli/composer/).

Kind regards!
