### ISSUE TITLE
Percentage values doesn't work for Letter spacing or Word spacing property

### ISSUE THREAD

**Issue by AF1QUE** [elementor/elementor#24064]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Letter spacing and word spacing doesn't work for percentage unit, I am unable to use explicit values like 2% letter spacing or word spacing for heading widget or text editor widget.

<img width="1440" alt="Screenshot 2023-10-22 at 6 03 33 AM" src="https://github.com/elementor/elementor/assets/46385375/43927156-9239-4b3f-9c3b-a7cdd4f33d83">

### Steps to reproduce

1) Create a heading/paragraph
2) Select Style tab for the heading/paragraph from the editor
3) Try to use percentage values (e.g: -2%, 10%) for Letter spacing or word spacing property.

****

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.22.1
	MySQL version: Percona Server (GPL), Release 29, Revision 11ad961 v5.7.26-29
	PHP Version: 8.0.25
	PHP Memory Limit: 1073741824
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.2
	Site URL: https://golden-girl-71b750.ingress-bonde.ewp.live
	Home URL: https://golden-girl-71b750.ingress-bonde.ewp.live
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 128M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: afique.dev@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.16.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.2
		Author: Elementor.com

== Must-Use Plugins ==
	EasyWP Plugin
		Version: 1.0.12
		Author: Namecheap, Inc.

== Elements Usage ==
	
	wp-page : 4
		button : 14
		container : 29
		heading : 9
		image : 12
		text-editor : 7
		video : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

== Log ==
	
PHP: showing 1 of 1PHP: 2023-10-03 20:55:10 [warning X 12][/var/www/wptbox/wp-content/plugins/elementor/includes/elements/container.php::1847] Undefined array key "size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2023-10-05 08:17:02 [error X 2][https://golden-girl-71b750.ingress-bonde.ewp.live/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:927545] Cannot read properties of undefined (reading 'route') 
JS: 2023-10-05 09:10:08 [error X 1][https://golden-girl-71b750.ingress-bonde.ewp.live/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:804182] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-10-21 21:55:57 [error X 5][https://golden-girl-71b750.ingress-bonde.ewp.live/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.4:3:617558] Cannot read properties of undefined (reading 'isEditable') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by Daveden2** [comment]
This is not a bug. `%` is not a valid unit for letter-spacing in CSS. Use `em` instead
