### ISSUE TITLE
🔗 📉 🐞 Huge DOM size according to pagespeeds (Duplicate of #23059)

### ISSUE THREAD

**Issue by ourtasteforlife** [elementor/elementor#24237]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am having trouble with my DOM size being huge according to Google Pagespeed. It's saying maximum child element and excessive DOM size on all my blog posts (over 200 articles) these blog posts have been created via the templates, so I'm wondering if there's a setting I can change to fix this. Within each blog post, I pretty much use the same structure of elements. Are you able to advise how to reduce this DOM size please? 
Here are some reports from pagespeed - 
https://pagespeed.web.dev/analysis/https-www-ourtasteforlife-com-lesbian-haircuts/iiyliohjyx?form_factor=mobile
https://pagespeed.web.dev/analysis/https-www-ourtasteforlife-com-different-types-of-lesbians-terms/1eayba1k35?form_factor=mobile
I have contacted elementor pro team and they have advised to post the issue here. Many thanks, Natalie

### Steps to reproduce

enter any of my blog post links into pagespeed

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-www.ourtasteforlife.com-10-11-2023.txt](https://github.com/elementor/elementor/files/13319618/system-info-www.ourtasteforlife.com-10-11-2023.txt)

**Comment by m1ga** [comment]
Use Containers and adjust your structure. E.g. one issue is an `ekit-wid-con` ElementsKit container. No Elementors fault.

**Comment by ourtasteforlife** [comment]
Hello, the other link shows it being elementor - https://pagespeed.web.dev/analysis/https-www-ourtasteforlife-com-different-types-of-lesbians-terms/1eayba1k35?form_factor=mobile

**Comment by m1ga** [comment]
But you define the DOM size when nesting your elements. Check the one element that is highlighted: 

on the left my version (container + headline + text + button), on the right your element:
![Screenshot_20231116_120006](https://github.com/elementor/elementor/assets/4334997/2fcd07d5-ad4d-4595-918c-e43f0a225dd1)

Check the blue line, you have so many elements in there that you don't need. So it's not Elementors fault that your DOM size is so big, you can just combine the widgets in a different way to reduce it

**Comment by nicholaszein** [comment]
Hello there, @ourtasteforlife !

Thank you for your submission! 🙏 

This is more of a feature request, not a bug.

### 🔗 🚀 There is already a similar request submitted by someone here #23059

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

Kind regards
