### ISSUE TITLE
✅ 🐞 Icon is not linked in nested Menu widget - [ED-13657]

### ISSUE THREAD

**Issue by Dudeney95** [elementor/elementor#24298]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using Elementor's Menu widget, there is the option to add an icon as well as text to each menu item.

As you can see from this screnshot from the Elementor Editor, I have created a menu with icons:
![image](https://github.com/elementor/elementor/assets/123473359/f559564a-8e55-41a1-9b27-272cee427af2)

The issue is that only the text is linked and not the icon as shown in this video:

[nav-menu-icon-links.webm](https://github.com/elementor/elementor/assets/123473359/7ba1e46b-9728-4b20-b6a9-c7701a09fba8)

I would like the option to have the icons linked as well as the text.

### Steps to reproduce

1) Drag the Menu widget into the editor
2) Add a new menu item
3) Add a title, link, and icon to the menu item
4) Publish the template
5) View the page as a front-end user and try clicking the icon. Sadly, it does not work unlike the text.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[REDACTED]

**Comment by nicholaszein** [comment]
Hello there @Dudeney95!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.22.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
