### ISSUE TITLE
⛔ Popup Animation Duration setting not showing

### ISSUE THREAD

**Issue by anakeme** [elementor/elementor#24328]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There seems to be an issue with the **entrance and exit animations** when first creating a new `Popup`. I have now created two different popups and adjusted the entrance and exit animations to be `Fade In` and `Fade Out` respectively.

Unfortunately, when I published the Popup the first time, I didn't realise that an additional setting had not appeared. The `Animation Duration` was not showing when I selected an animation, therefore I experienced issues in closing said Popup when I pressed the exit button in the corner of the Popup.

I re-entered the Popup editor to find the new `Animation Duration` setting now visible. I found it odd, so I investigated further by creating another Popup. The same event occurred - the `Animation Duration` setting did not first appear when I changed the entrance and exit animations to something other than `None`.
Upon refresh, the setting then appeared.

### Steps to reproduce

1) Create new Popup.
2) Edit 'Entrance' and 'Exit' animations.
3) Change to something such as 'Fade In' and 'Fade Out' respectively.
4) You should see that the next setting `Animation Duration` does not appear.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: https://jessem81.sg-host.com
	Home URL: https://jessem81.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 10
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.3
		Author: WP Engine

	Code Snippets
		Version: 3.6.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.17.3
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.17
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.17.1
		Author: Elementor.com

	Security Optimizer
		Version: 1.4.7
		Author: SiteGround

	Speed Optimizer
		Version: 7.4.3
		Author: SiteGround


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 7 of 7JS: 2023-11-16 07:20:53 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:890462] Cannot read properties of undefined (reading &#039;route&#039;) 
JS: 2023-11-16 10:29:28 [error X 2][../wp-content/plugins/elementor-pro/assets/js/gallery.8ca9a354ce039d1ba641.bundle.min.js:2:5674] Cannot read properties of undefined (reading &#039;setSettings&#039;) 
JS: 2023-11-17 10:41:00 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:639997] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-11-18 05:25:57 [error X 1][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.17.3:2:16880] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2023-11-18 09:20:12 [error X 47][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.17.3:2:11687] Cannot read properties of undefined (reading &#039;params&#039;) 
JS: 2023-11-18 09:28:07 [error X 1][../wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.4.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-11-18 09:34:06 [error X 8][../wp-content/plugins/elementor-pro/assets/js/elements-handlers.min.js?ver=3.17.1:2:14308] Cannot read properties of undefined (reading &#039;size&#039;) 

PHP: showing 3 of 3PHP: 2023-11-16 20:13:01 [notice X 38][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-16 21:19:17 [error X 4][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /home/customer/www/j [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-17 19:10:08 [notice X 9][../wp-content/plugins/elementor-pro/modules/carousel/widgets/base.php::573] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatible


````

</details>

**Comment by nicholaszein** [comment]
Hello @anakeme,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We've tested your issue using the latest version of Elementor (v3.19.4) and Elementor Pro (v3.19.3), and couldn't reproduce your issue. The `Animation Duration` settings appear as expected in the Popup settings. See the video below for confirmation:



https://github.com/elementor/elementor/assets/113993460/d0f34008-a8ad-4546-8b61-5c7ff36cd49f


### ✅ What you can do to solve your issue:
Your issue is most likely caused by a conflict with another plugin, 3rd-party script, or cache. Make sure you have purged and cleared all levels of cache applicable to your website, and test it without using any Elementor addon.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
