### ISSUE TITLE
(Possibly minor) Security vulnerability?

### ISSUE THREAD

**Issue by akrichman** [elementor/elementor#24354]
I've reported a security vulnerability on Bugcrowd and was told it was of Informational level (low severity). 
I was wondering if this meant it wouldn't get fixed or if it was an _eventually_ timeline. There is a simple fix for it.

ID is `deaf8299-e244-4008-aa55-8d14fba5f0d2`

Thanks

**Comment by nicholaszein** [comment]
Hello @akrichman,

we do not track or discuss security reports here. These should be handled directly through our Bugcrowd program. Please refer to our [Contributing Guidelines](https://github.com/elementor/elementor/blob/main/.github/CONTRIBUTING.md#security-issues) for more information.

Thank you
