### ISSUE TITLE
⛔ 🛡️ create security.txt

### ISSUE THREAD

**Issue by DanielRuf** [elementor/elementor#24365]
### Description

Please create a security.txt and put it into the plugin folder so that others know how to contact you, when a security researcher finds a security issue.

https://securitytxt.org/
https://plugins.trac.wordpress.org/browser/elementor/trunk

### Steps to reproduce

There is no security.txt file at https://plugins.trac.wordpress.org/browser/elementor/trunk

**Comment by nicholaszein** [comment]
Hello @DanielRuf,

Thank you for reaching out! 🙏 

We take security vulnerabilities very seriously, and we want to ensure they are handled responsibly and solved privately. We have a team dedicated to handling this type of report, and the best place to do it is through our [Bug Bounty Program on Bugcrowd](https://bugcrowd.com/elementor) as indicated on our [Trust Center](https://elementor.com/trust/).

Please submit your findings on Bugcrowd so we can take this forward!

Trust Center: https://elementor.com/trust/
Bug Bounty Program on Bugcrowd: https://bugcrowd.com/elementor

Thank you very much! 🙏
