### ISSUE TITLE
✅ 🐞 Template Conditions Screen with bad overflow in small desktop screens

### ISSUE THREAD

**Issue by mateuswetah** [elementor/elementor#24379]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the Theme Editor, when entering the Template Display Conditions screens, if you have several conditions the container overflows. As the footer where "Save and close" button is placed is fixed on the bottom, there should be a padding at the bottom of the container, otherwise user in small desktop screens may be in a situation where they cannot click the "add condition" button, because it appears bellow the footer.

To clarify, here is a screenshot at 1366 x 730px:
![image](https://github.com/elementor/elementor/assets/1184874/d0e296e5-b494-4280-9cd5-c9537980b5c7)

The footer should have a white background, to properly cover the button visually indicating that is covered. Then the container height should allow more scrolling down (the screenshot did not captured it, but the scrollbar is in the bottom end max here).

I discovered this issue when a client asked me if there was some type of limit of how much conditions you can add because the button simply was not working 😓 

### Steps to reproduce

1) Go to theme editor
2) Create a template
3) Edit the template display conditions
4) Add several conditions, 6 to 8 maybe
5) In a small desktop screen such as 1366x730, you should already see the problem.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[System Info removed by moderation.]

**Comment by nicholaszein** [comment]
Hello there @mateuswetah!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
