### ISSUE TITLE
PHP 8.2 dynamic property creation  deprecated

### ISSUE THREAD

**Issue by BackuPs** [elementor/elementor#24390]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

 Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated in /var/docs/server.tst/public/wp-content/plugins/elementor/includes/elements/container.php on line 43
Call Stack

Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_start is deprecated in /var/docs/server.tst/public/wp-content/plugins/elementor/includes/elements/container.php on line 42
Call Stack

### Steps to reproduce

Just turn on debug mode in wp and install php 8.2.  Preview a elementor page you will see the messages

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Not needed.

**Comment by m1ga** [comment]
If you search for `logical_dimensions_inline_end` you'll find other posts about 8.x already:

https://github.com/elementor/elementor/issues/24253#issuecomment-1807791530
https://github.com/elementor/elementor/issues/24246
https://github.com/elementor/elementor/issues/23927

**Comment by BackuPs** [comment]
is searched for $logical_dimensions_inline_end   and that was not found!

**Comment by m1ga** [comment]
![Screenshot_20231123_121455](https://github.com/elementor/elementor/assets/4334997/45a63a11-52a4-4b56-a3b3-a9c21a777564)

did you try the current beta version? According to https://github.com/elementor/elementor/commits/3.18/includes/elements/container.php it is merged already. https://github.com/orgs/elementor/discussions/24275 includes 8.2 fixes in the release notes too.

**Comment by BackuPs** [comment]
This is exactly why i will stop reporting issues. Have a great day for whats left of it.  And thank you.

**Comment by nicholaszein** [comment]
Hello there @BackuPs!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
