### ISSUE TITLE
❌ 🔗 🐞 Elementor Editor takes too long to load on MacOS Browsers (Duplicate of #24260)

### ISSUE THREAD

**Issue by hirschferkel** [elementor/elementor#24432]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I did not change my page for month and everything worked properly.

Than I updated to the latest Elementor release, Firefox and Wordpress, and now it takes Elementor to load the editor for 50 seconds (even with no plugins activated and Hello Elementor theme)!

I made a runtime analyses and all I get, is that JIT is somehow the major reason. 

It will load well in Chrome browser (7 seconds, so it seems no website or server specific problem anyway!

### Steps to reproduce

Just go to > edit page with Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

OS X Monterey
latest Elementor and Firefox

**Comment by m1ga** [comment]
duplicate https://github.com/elementor/elementor/issues/24260
and fixed already in https://github.com/elementor/elementor/pull/24424. You can apply that to your editor file to see the difference.

**Comment by hirschferkel** [comment]
Oh great, how do I apply that?

**Comment by m1ga** [comment]
you just edit the file https://github.com/elementor/elementor/pull/24424 and add the two lines in the same place

**Comment by hirschferkel** [comment]
Your right, it fixed it!
Thanxs, best

**Comment by m1ga** [comment]
no problem. Since it is merged into the 3.18 branch it will be available in the first week of December
