### ISSUE TITLE
✅ 🐞 Vide Playlists Widget Not Loading Vimeo Links

### ISSUE THREAD

**Issue by AlexUsernameAvailable** [elementor/elementor#24476]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There are two problems with Vimeo links:
1) When you press "Get Video Data" it doesn't always come through

2) The video only loads in the player if the video's Vimeo privacy setting is set to "Public", the video does not load if the Vimeo privacy setting is "Hide from Video" or "Unlisted". The "Video Widget", on the other hand, loads the video regardless of if the privacy setting is "Unlisted", "Hide from Video", or "Private". In other words, the "Video Playlist" widget should function like the "Video Widget" and load the video for all 3 types of privacy settings

### Steps to reproduce

1) Use a Video Playlist Widget
2) Insert a Vimeo video link that is not on the "Public" privacy setting
3) Boom, the video won't load
4) However, if you repeat the same steps with the "Video Widget" then the video loads just fine

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

file removed by moderation

**Comment by nicholaszein** [comment]
Hello there @AlexUsernameAvailable!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

Now Vimeo videos that have privacy settings enabled should load correctly.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
