### ISSUE TITLE
⛔ 🔗 Loop Grid Showing 2 Loop items even when set to show 1 with Sticky Posts enabled (Related to #23331)

### ISSUE THREAD

**Issue by niendoo** [elementor/elementor#24579]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Loop Grid shows 2 Loop items even when set to show 1 with Sticky Posts enabled. When I set the loop grid to show only 1 post and with the "Ignore Sticky Posts" turned off and you have a post enabled as a sticky post amongst the posts, the loop will display two posts instead of 1.

### Steps to reproduce

1. Make one of your posts sticky
2. Build out a loop grid and set the number of posts to display to 1.
3. Turn off the "Ignore Sticky Posts" settings
4. Preview from the frontend, and you will see 2 posts showing instead of 1.
5. When you turn on the "Ignore Sticky Posts" setting, only the 1 post now shows.
6. So the conflict has to do with the sticky post
7. Here's a [video demonstration](https://www.awesomescreenshot.com/video/23292548?key=57f06b9f2586551160ce2dd70d5e3062): 

### Expected behavior

When the ignore sticky posts setting is turned off, and there's a sticky post, and the loop grid is set to display only 1 post, it should display only 1 post and not 2.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.5.23
	PHP Version: 8.2.13
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.9.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.18.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.1
		Author: Elementor.com

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.42
		Author: MalCare Security

	Perfmatters
		Version: 2.2.0
		Author: forgemedia

	WP All Import - Yoast WordPress SEO Add-On
		Version: 1.1.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.8.5
		Author: Soflyy

	WP Reset
		Version: 1.98
		Author: WebFactory Ltd

	WP Rocket
		Version: 3.15.6
		Author: WP Media

	Yoast SEO
		Version: 21.7
		Author: Team Yoast


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.20.0
		Author: Rhubarb Group


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active
	Build with AI: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by sbkpsbkp** [comment]
Hi! Exactly the same problem here! Need to be able to only shown the Sticky post in a Loop grid. Please advice.

**Comment by niendoo** [comment]
I target the elementor generated class of one of them and used CSS
display:none on it to hide since elementor wouldn't provide any solution.

**Comment by sbkpsbkp** [comment]
Hi @niendoo, thanks! But that would then screw up the loops after, making them miss 1 forcefully hidden element, no?

**Comment by niendoo** [comment]
No since it's a sticky item being shown 2 times. For me, it didn't screw up
anything. Just the duplicate that was hidden. If you'd like to jump on a
call, let me know. I'd be happy to help 🙂

**Comment by sbkpsbkp** [comment]
oh! sorry, I did not get that! So in my case it's Elementor ignoring the '1 post per loop' rule and shows 2 posts: one that is sticky and the latest one without the sticky option on. 
I would like to create a loop that only shows 1 posts: the latest one with the sticky box checked.

**Comment by jfagnonih4** [comment]
> oh! sorry, I did not get that! So in my case it's Elementor ignoring the '1 post per loop' rule and shows 2 posts: one that is sticky and the latest one without the sticky option on. I would like to create a loop that only shows 1 posts: the latest one with the sticky box checked.

i've same problem ! if someone have a solution thx !

**Comment by eknown** [comment]
Looks like this may be related to issue #18689
