### ISSUE TITLE
Crazy high memory limit requirements for very basic websites (also compared to other page builders)

### ISSUE THREAD

**Issue by SolunaCG** [elementor/elementor#24604]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

First of all: I post this in the "Bug" section because of the following situation:

I´m hosting a very basic website for a client. It´s just a onepager with some images and text. However, I´m using the "Nested Tabs" with galleries inside. Not sure if this causes the problem but even after removing them the problem still persists.

The website is pretty much ready. It´s supposed to go live on January 1 next year, so in about 2 weeks which is why I still can´t provide a link to the website. 

The problem is that I cannot really edit the page. I purchased the biggest webhosting package from my server provider which has a memory limit of 512MB and I thought for such a simple website it would be more than enough which turned out it isn´t. 

Long story short, after many hours of calling with the tech department of the server provider and them analyzing where the problem is it turned out that it´s indeed the memory limit which I wasn´t 100% sure about before. They temporarily raised the memory limit from the allowed 512MB to 1GB and the website (the editor) worked again. Obviously they couldn´t allow me to leave it on 1GB cause Webhosting usually doesn´t allow these numbers for memory limit.

Even they as a neutral instance told me that for such a simple website like mine the required memory limit is WAY too high and that I should contact the Elementor support (which I´m doing with this post) to please let them know that they should work on how much memory the page builder actually needs. 

As a long time Elementor user I´m still very happy with the page builder but I can definitely see a problem here with how heavy the page builder is. In the "Elementor help center" I found this:

> WP Memory Limit
WP Memory limit of 256 MB (Elementor and Elementor Pro only), 512 MB recommended, 768 MB for best performance.

> Note: These requirements are for Elementor. If you are using additional plugins on your site that also have minimum requirements such as WooCommerce, you may need to increase your memory to 512 MB to help avoid loading issues. See also, the following documentation [Elementor Widget Panel Not Loading](https://elementor.com/help/elementor-widget-panel-not-loading/).

I´m pretty sure that If I now had a woocommerce site I´d have to go to 2GB or even higher for my site.

Maybe this is something that can be worked on in the long run to make Elementor need much less memory. 

### Steps to reproduce

1. Install Elementor and Elementor Pro
2. Create a Onepager with about 5 sections with text and image galleries (in my case I also used "Nested Tabs" with image galleries inside).

Even on other sites that I created for my previous company I had the same problem. Server Error 500 is pretty much persistent on Elementor sites unless you go crazy with the memory limit.

### Expected behavior

I´d expect Elementor to need a LOT less memory, especially for small websites. I´m pretty sure that I´m not the only one who has experienced many "Server error 500" while working with Elementor.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.21
	PHP Version: 8.2.13
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.2
	Site URL: ------------
	Home URL: -----------------
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: -----------------------------
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.9.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.79
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.52
		Author: ServMask

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.18.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.1
		Author: Elementor.com

	Maintenance
		Version: 4.08
		Author: WebFactory Ltd

	Real Cookie Banner
		Version: 4.2.0
		Author: devowl.io


== Elements Usage ==
	
	footer : 1
		container : 6
		icon-list : 5
		image : 1
	header : 1
		container : 4
		image : 1

	wp-page : 3
		container : 4
		text-editor : 2


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Global Style Guide: Active
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
JS: showing 8 of 8JS: 2023-11-16 16:14:49 [error X 1][https://****/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.17.3:3:82386] Data commands: `` not found. 
JS: 2023-12-03 09:55:59 [error X 1][https://****.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view16702&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-03 10:08:41 [error X 349][https://****/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.17.3:3:7470] Cannot read properties of null (reading &#039;editor&#039;) 
JS: 2023-12-06 16:11:28 [error X 4][https://****/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.0:3:806906] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-12-07 10:26:55 [error X 2][https://****/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.18.1:2:12705] Failed to execute &#039;observe&#039; on &#039;IntersectionObserver&#039;: parameter 1 is not of type &#039;Element&#039;. 
JS: 2023-12-07 10:35:52 [error X 1][https:/****/wp-admin/post.php?post=7&amp;action=elementor&amp;active-document=6:6:39] Cannot read properties of undefined (reading &#039;needHelpUrl&#039;) 
JS: 2023-12-07 13:27:43 [error X 2][https://****/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view7108&quot;) has already been destroyed and cannot be used. 
JS: 2023-12-07 13:29:57 [error X 1][https://****/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view32507&quot;) has already been destroyed and cannot be used. 

PHP: showing 8 of 8PHP: 2023-11-17 19:03:56 [error X 1][/usr/www/users/valontt/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /usr/www/users/valontt/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /usr/www/users/valontt/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 /usr/www/users/valontt/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 /usr/www/users/valontt/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 /usr/www/users/valontt/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 /usr/www/users/valontt/wp-includes/class-wp-hook.php(324): Elementor\Modules\CompatibilityTag\Base_Module-&gt;Elementor\Modules\CompatibilityTag\{closure}(&#039;&#039;)
#5 /usr/www/users/valontt/wp-includes/class-wp-hook.ph [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-06 22:46:21 [notice X 1][/usr/www/users/valontt/wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-07 11:35:45 [notice X 1][/usr/www/users/valontt/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-07 12:10:36 [error X 1][/usr/www/users/valontt/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::312] Uncaught Error: Call to a member function update_meta() on null in /usr/www/users/valontt/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:312
Stack trace:
#0 /usr/www/users/valontt/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(185): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /usr/www/users/valontt/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /usr/www/users/valontt/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module-&gt;handle_ajax_request(&#039;&#039;)
#4 /usr/www/users/valontt/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#5 /usr/www/users/valontt/wp-includes/plugi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-08 13:10:10 [notice X 1][/usr/www/users/valontt/wp-content/plugins/elementor/modules/usage/module.php::80] Undefined index: publish [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-10 16:30:30 [notice X 4][/usr/www/users/valontt/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /usr/www/users/valontt/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /usr/www/users/valontt/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /usr/www/users/valontt/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /usr/www/users/valontt/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-12-16 20:09:50 [notice X 22][/usr/www/users/valontt/wp-content/plugins/elementor-pro/modules/custom-css/module.php::96] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-12-16 20:39:22 [warning X 1][/usr/www/users/valontt/wp-content/plugins/elementor/modules/usage/module.php::80] Undefined array key &quot;publish&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 262023-12-04 15:31:19 [info] elementor::elementor_updater Started 
2023-12-04 15:31:19 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-04 15:31:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-04 15:31:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-06 18:05:03 [info] elementor::elementor_updater Started 
2023-12-06 18:05:03 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-06 18:05:04 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-06 18:05:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-06 18:05:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-06 18:05:11 [info] elementor-pro::elementor_pro_updater Started 
2023-12-06 18:05:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-06 18:05:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-06 18:05:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-06 18:05:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.0',
  'to' => '3.18.1',
)]
2023-12-08 13:40:51 [info] elementor::elementor_updater Started 
2023-12-08 13:40:51 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-08 13:40:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-08 13:40:51 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-08 13:40:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]
2023-12-08 13:40:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.1',
  'to' => '3.18.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by StenderIternum** [comment]
But your memory limit is "Memory limit: 40M" - shouldn't that be set up as well, through either htaccess or wp-config?

**Comment by SolunaCG** [comment]
According to the server support that shouldn´t be necessary. They checked all the values and they said that it´s just the php memory limit. I´m not an expert by any means which is why I´m just wrote what the support told me :-)

And yep, you´re right! 😄  I removed the site link from the debug info. It´s not a big deal but because the site is supposed to go live on January 1, I thought I´d still keep it "private" until then. But if it´s needed for any kind of debugging then I´ll definitely share it with you 😊

**Comment by StenderIternum** [comment]
Well yes and no - 
**PHP Memory Limit** is the total size of memory that your server provides for you.
**WP Memory Limit** is the memory assigned to a particular WordPress site on the server. 

I know that WPML requires **at least 128M** of both **PHP Memory Limit** and **WP Memory Limit** to work correctly using a WordPress default theme (like Twenty Twenty) and no other plugins.

So I would set your wp memory limit up as well.
writing define('WP_MEMORY_LIMIT', '256M'); in your wp-config file, might help.

**Comment by SolunaCG** [comment]
I´ll definitely try that for my specific case! Thanks a lot already! 😊 

But nevertheless, the requirements that Elementor has according to their website (768MB for best performance) are still very high imo. With just a few plugins that´d probably easily exceed the 1GB mark, wouldn´t it? 
I´d love to hear a few opinions on that in general since, as I said, am not an expert here. Is that normal that even such a simple one-pager requires such a high WP Memory limit?

**Comment by SolunaCG** [comment]
I close this topic cause it´s most likely not a bug.

**Comment by postiffm** [comment]
Similar behavior observed with newest versions of Elementor/Pro in early 2026. Memory use on the server often sits at about 200 to 300 MB when the site is idle, then when I load a simple page, it jumps to 1.6 GB, that's right, gigabytes. CPU maxes out, and then it settles back down once the page is loaded--slowly. If we have several clients at one time, the site throws 503 errors and takes 20-30 seconds to load pages sometimes. We are often at the max of 2 GB out of 2 GB permitted on our webhost. Does anyone else experience this behavior?

**Comment by dribgib** [comment]
Bro I consistently have to edit 2.5GB elementor tabs -- I'm sorry but with all the new AI tools, this shit is dead.

**Comment by postiffm** [comment]
Our solution was to eliminate Elementor from our website.

**Comment by krevaestudio** [comment]
I think it's not the same but I have a really frustrating issue with GPU usage when on elementro editor tab, since months. I've tried many other options (Like switching browsers, disabling gpu acceleration graphics, even switching OS) and its horrible how much the GPU/CPU struggles to manage with the elementor editor tab. I also have a laptop where I edit from time to time but editing any Elementor website rise the temperatures over 70 degrees! It's insane. Not to mention the 2.5gb RAM tab
