### ISSUE TITLE
Make "post status" an option in "post-list" Elementor Pro

### ISSUE THREAD

**Issue by l3enito** [elementor/elementor#2466]
By default only post with status "published" are listed by WP. 
By adding code to funcions.php or using a plugin also status "future" will be listed. This is mostly used for anouncing events. Meanwhile "published" will build an archive of events.

The  "post-list" Widget in Elementor Pro has a lot of functionality but "status" is no option. 
Please add this parameter to your wp_query!

**Comment by nuritsha** [comment]
Hi @l3enito,
Thank you for your suggestion, we see it as an advanced capability, however, we also think it is prone to result in unexpected output and users mistakes. 
Therefore we do not plan to add it to Elementor.
Having said that, the requested functionality can be achieved using custom query.
Please see [Custom Query Filter documentation](https://developers.elementor.com/custom-query-filter/).
