### ISSUE TITLE
Feature request:  highlighting of active menu items when scrolling through a one-page design

### ISSUE THREAD

**Issue by knireis** [elementor/elementor#2470]
It would be nice if the menu items of the menu element could be 'highlighted' when the viewport is on the corresponding section.

So when you have a 'one-page' design the active state of the menu items change during scroll down the page.

**Comment by finnsbali** [comment]
I second this 8 months later please

**Comment by shilo-ey** [comment]
Hi @knireis 

This feature has already been implemented in Elementor.

Thanks.

**Comment by knireis** [comment]
I never saw this mentioned, do you have a link to the docs where i can read up about it?

regards
