### ISSUE TITLE
❌ 🔗 🐞 Unable to edit popups in Elementor 3.18.3 - error: Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by b0ss-x** [elementor/elementor#24857]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I'm unable to edit popups in Elementor 3.18.3 - error: Using ${var} in strings is deprecated, use {$var} instead

I recently upgraded to PHP 8.2

![image](https://github.com/elementor/elementor/assets/150304455/6fcae28c-faf0-4451-a49a-e09aab5a51d0)

Preview debug:
![image](https://github.com/elementor/elementor/assets/150304455/0a144740-aa13-42d3-9713-446a5420f437)

### Steps to reproduce

1. Install PHP 8.2
2. Try to edit a popup in elementor

### Expected behavior

1. Popup should load in edit mode

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
WordPress 6.4.2 PHP 8.2 with Elementor 3.18.3 and Elementor Pro 3.18.3
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by KingYes** [comment]
I edited the Popup in Elementor with PHP8.2 and I don't have any issue there. In your error message, do you have a filename for it?
