### ISSUE TITLE
❌ 🐞 Parent Container handles are missing when editing any CPT other than Pages

### ISSUE THREAD

**Issue by hirschferkel** [elementor/elementor#24893]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

There is simply no handle or tab while hovering over containers (not in Chrome, nor in FireFox or Edge) in all kind of post-types visible. It works with pages, but not with posts. It will show up over rows, too, but not over containers, like described in Elementor help (e.g. step 4 to add a container). https://elementor.com/help/how-do-i-create-a-container/

---> It is a Bug in Pro Elements.
So does this issue belong to Elementor, too?
The issue occurs on Windows and OS X and is not related to any specific system setting.

**Comment by nicholaszein** [comment]
Hello @hirschferkel,

please restore the information you removed from your original submission. Without that information, we can't continue.

**Comment by hirschferkel** [comment]
@nicholaszein I added the information to the post again. I am aware that it is a bug with Pro Elements (as I mentioned in the initial post) but maybe it is related to Elementor, too.

**Comment by nicholaszein** [comment]
Thank you @hirschferkel.

Keep in mind we do not provide support for Pro Elements users... You should reach out to their GitHub if you need support.

Please, next time do not remove the submitted fields. We won't accept issues without the required information.

Thanks

**Comment by hirschferkel** [comment]
@nicholaszein I did not want to get Pro Elements support. I guess this issue could be causing troubles in Elementor Pro (at least for some users), too. So it was just to inform you about it and give you the chance to check it out for your WP Plugin.

**Comment by hirschferkel** [comment]
@nicholaszein could you delete this issue, as is still contains personal information in the history, which I forgot to erase in my second answer, while editing the post?

**Comment by nicholaszein** [comment]
@hirschferkel I'm closing this issue as requested.
