### ISSUE TITLE
❌ 🛟 Support Request: It is impossible to join the Facebook community

### ISSUE THREAD

**Issue by TokumeiJG** [elementor/elementor#24940]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi,

I want to join the Facebook community but it is impossible to do so.
There are 3 questions that must be answered but there are no options to choose!  If you try to just select "I will follow the rules" and join, you are rejected by the admins because you "didn't answer the questions"!!

![SCR-20240129-h6a](https://github.com/elementor/elementor/assets/16894079/172ec791-75c1-4e15-9831-ec254ca04014)

### Steps to reproduce

Go to https://www.facebook.com/groups/916625091796611 as a non-member and try to join

### Expected behavior

Should be able to answer the questions

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Not related
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @TokumeiJG,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

👉 Try another browser or another device.

----

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
