### ISSUE TITLE
⛔ 🧩 🐞 Can't scroll the Navigation Menu on Responsive screens when using the Flyout Layout

### ISSUE THREAD

**Issue by matke-84** [elementor/elementor#25012]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

There are some bugs when using layout-flyout on mobile/tablet view. When the menu is scrolled, very often the submenu remains fixed and the main menu scrolls up and down. Also, if landscape mobile view is defined in the theme, the menu is scrolled so high that the entire menu disappears.

### Steps to reproduce

1. Open menu
2. Open submenu
3. Start to scroll
4. If you miss a bit and your finger goes to the side, only the main menu starts scrolling and the sub-menu remains fixed.

### Expected behavior

1. Should always scroll the entire menu with submenus.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.36
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: sr_RS
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

== Active Plugins ==
	Ajax Search Lite
		Version: 4.11.5
		Author: Ernest Marcinko

	All-in-One WP Migration
		Version: 7.79
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.54
		Author: ServMask

	Connect Polylang for Elementor
		Version: 2.4.3
		Author: Creame

	DarkMySite Pro
		Version: 1.2.6
		Author: DarkMySite

	Default featured image
		Version: 1.7.3
		Author: Jan Willem Oostendorp

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.19.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.0
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.9.8
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.8.8
		Author: WPDeveloper

	JetElements For Elementor
		Version: 2.6.15
		Author: Crocoblock

	JetEngine
		Version: 3.3.5
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.2
		Author: Crocoblock

	JetEngine - dynamic tables builder
		Version: 1.0.9
		Author: Crocoblock

	JetEngine Post Expiration Period Module
		Version: 1.1.2
		Author: Crocoblock

	JetSmartFilters
		Version: 3.3.2
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.1
		Author: Crocoblock

	Password Protected
		Version: 2.6.6
		Author: Password Protected

	Polylang
		Version: 3.5.3
		Author: WP SYNTEX

	Premium Addons for Elementor
		Version: 4.10.18
		Author: Leap13

	Premium Addons PRO
		Version: 2.9.11
		Author: Leap13

	Ultimate Addons for Elementor
		Version: 1.36.29
		Author: Brainstorm Force

	Yoast SEO
		Version: 21.9.1
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Особине ==
	Custom Fonts: 0
	Custom Icons: 0

== Интеграције ==
	


== Елементор експерименти ==
	Побољшано учитавање средстава: Подразумевано активан
	Побољшано учитавање CSS: Подразумевано активан
	Редне иконе фонтова: Подразумевано неактиван
	Додатне прилагођене тачке прекида: Подразумевано активан
	admin_menu_rearrangement: Подразумевано неактиван
	Flexbox Container: Активно
	Upgrade Swiper Library: Подразумевано неактиван
	Grid Container: Подразумевано неактиван
	Default to New Theme Builder: Подразумевано активан
	Hello теме заглавље & подножје: Подразумевано активан
	Editor Top Bar: Подразумевано неактиван
	Optimized Gutenberg Loading: Подразумевано активан
	Build with AI: Подразумевано активан
	Одредишне странице: Подразумевано активан
	Nested Elements: Активно
	Lazy Load Background Images: Подразумевано неактиван
	Optimize Image Loading: Подразумевано активан
	Global Style Guide: Подразумевано активан
	Page Transitions: Подразумевано активан
	Notes: Подразумевано активан
	Display Conditions: Подразумевано неактиван
	Form Submissions: Подразумевано активан
	Scroll Snap: Подразумевано активан
	Изборник: Подразумевано неактиван
	Taxonomy Filter: Подразумевано неактиван


== Дневник ==

PHP: showing 2 of 2PHP: 2024-01-26 14:45:39 [notice X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-29 10:15:00 [notice X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::1459] Undefined index: pa_badge_bg_size_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102024-02-01 16:15:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-02-01 16:15:06 [info] elementor-pro::elementor_pro_updater Started 
2024-02-01 16:15:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-01 16:15:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-01 16:15:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-02-01 16:15:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-02-01 16:18:05 [info] elementor::elementor_updater Started 
2024-02-01 16:18:05 [info] Елементор/Upgrades - _on_each_version Start  
2024-02-01 16:18:05 [info] Елементор/Upgrades - _on_each_version Finished 
2024-02-01 16:18:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Елементор',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]



== Елементор - Compatibility Tag ==
	
	Connect Polylang for Elementor: Усклађеност није наведена
	Elementor Pro: Усклађеност није наведена
	Essential Addons for Elementor: Усклађеност није наведена
	Essential Addons for Elementor - Pro: Усклађеност није наведена
	JetElements For Elementor: Усклађеност није наведена
	JetTabs For Elementor: Усклађеност није наведена
	Premium Addons for Elementor: Усклађеност није наведена
	Ultimate Addons for Elementor: Усклађеност није наведена

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by matke-84** [comment]
I found one part of the problem. When the sticky menu is turned on in Motion Effects, it creates these problems. It would be nice if this could be solved with the next update, because now the menu on mobile is almost unusable.

**Comment by nicholaszein** [comment]
Hello @matke-84!

Thank you for submitting your issue.

Please explain exactly which navigation widget you are using, because Elementor does not have a Navigation Menu with a "Flyout" Layout. It seems the problem you are reporting comes from a 3rd-party addon.

It would help if you shared screenshots or a screen recording so we can understand exactly what's going on. Without a link to your website we cannot reproduce your issue. Everything is working as expected on our tests.

Kind regards

**Comment by matke-84** [comment]
@nicholaszein 

Hi Nicholas. This is the widget I use.

![Screenshot 2024-02-06 075419](https://github.com/elementor/elementor/assets/74268331/00a31b54-047f-4eef-8a6a-fc5c3febe38f)
![Screenshot 2024-02-06 075758](https://github.com/elementor/elementor/assets/74268331/9f60a024-8fcb-4d63-b7c8-9db17a34691a)
![Screenshot 2024-02-06 075816](https://github.com/elementor/elementor/assets/74268331/0984b011-afbd-4f50-a988-1de83756cf85)

Unfortunately, the site is not online yet, it is under development, so I cannot give you a link. The problem, as I said, is when the sticky menu is turned on in Motion Effects, there is a glitch so that the submenu remains fixed (it is also duplicated) and the rest of the menu moves up and down. Now I'm currently using jetsticky instead of elementor Motion Effects and everything works normally, it doesn't have this glitch.
Another problem is that when the mobile is in landspace mode, the menu scrolls too high so that it is not possible to see it.
I hope these videos will help a little.

https://github.com/elementor/elementor/assets/74268331/a18b0e49-a46a-4996-8ce5-30682d44771d

https://github.com/elementor/elementor/assets/74268331/90a14a76-c19f-4654-be1e-ea0a879e2002

**Comment by nicholaszein** [comment]
Hi @matke-84,

The WordPress Menu widget does not have a "Flyout" layout natively. It seems one of your add-ons is adding more options to this widget. In this case, you need to find out which addon is doing this and reach out to their support, as we do not give support for 3rd-party addons. Moreover, you indicated you are using the WordPress Menu, but in your screenshots, you are using another widget called Navigation Menu.

![image](https://github.com/elementor/elementor/assets/113993460/df460faa-1412-4642-b565-67481cd43856)


https://github.com/elementor/elementor/assets/113993460/bb4b0e2e-0208-4adc-994a-2b3789281166

----

Please, only use Elementor GitHub issues to report bugs you found in the code of Elementor or Elementor Pro. For anything else, reach out to the addon developers or to Elementor Support.

Thanks

Kind regards
