### ISSUE TITLE
Feature Request: Sticky Posts

### ISSUE THREAD

**Issue by petehawk** [elementor/elementor#2501]
Sticky Posts have been part of the Wordpress "infrastructure"for years, but the Elementor pro Posts widget doesn't support this.

Can you wonderful Elementor people address this please

Pete

**Comment by smpetrey** [comment]
+1 this would be a really cool

**Comment by khelx67** [comment]
+1

**Comment by formulaclick** [comment]
+1 just add a filter!!

**Comment by formulaclick** [comment]
Why isn't this added? Is quite simple and would solve many trouble on designing magazine front pages... @benpines @arielk

**Comment by chocobochick** [comment]
+1 please!

**Comment by mikegriffinn** [comment]
+1 --I'm just finishing rewriting Harvard Medical School's Center for Primary Care website using Elementor. They use Sticky Posts **often**. But they also use a JavaScript drag and drop post reorder plugin. It turns out, works with the Posts widget if the order by is "Menu Order" ASC. So I'm pushing all the sticky posts to the top for now. Sometime, however, they will notice that Sticky isn't working. So - yes, please add Sticky Posts! ~Thanks.

**Comment by corsa** [comment]
+1 Was needing this feature just today for a client.

**Comment by nicomollet** [comment]
Came here to say I need this too.

**Comment by Beremaro** [comment]
+1 I would realy love it 🥇

**Comment by knireis** [comment]
+1 , it is an important feature

**Comment by mrdumont** [comment]
C'mon guys - this is a MUST have

**Comment by momo-fr** [comment]
+1000, I want this feature!!!

**Comment by solanako** [comment]
+1 I have tha same problem. This feature is really very necessary.

**Comment by shilo-ey** [comment]
Thanks for your feedback.

Since Elementor Pro v2.5.0 we've added the ability to use query control to "Ignore Sticky Posts", that way you can unselect this option and get the sticky posts first.

Please note that WordPress "Sticky" feature works only in front pages.

Thanks!

**Comment by iMiek** [comment]
Sticky feature isn't working on my frontpage....

**Comment by miquelangeld** [comment]
Yep, it doesn't work on my site either.

**Comment by jchornenky** [comment]
necessary feature

**Comment by nateomedia** [comment]
Sticky posts do not work on the homepage/front page of my site either. Please fix this.

**Comment by stuffedthings** [comment]
What seems to be impossible is to filter the posts widget to show **only** sticky/featured posts. This is an essential feature.

**Comment by kmpmba** [comment]
+1 required feature
**Workaround:** add a dummy author (with no posts) and Include with that author - Ignore Sticky off.

**Comment by bkjproductions** [comment]
One would think this should work regardless of Front Page status or not! I wonder if @shilo-ey must mean that if the front page of your site is actually "Your Latest Posts" rather than "A static page" (via WP Settings: Reading)?

**Comment by heikohaensge** [comment]
Two years later and this fundamental feature is still not implemented properly. Sticky posts are not shown first in posts widget. 
Just tested in Elemetor Pro 3.21.2
Any news concerning implementation of this feature request from our sweet developers?
