### ISSUE TITLE
❌ 🐞 Template Import not working ReferenceError: elementor is not defined

### ISSUE THREAD

**Issue by neok** [elementor/elementor#25026]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

admin.min.js?ver=3.19.0:3 Uncaught (in promise) ReferenceError: elementor is not defined
    at Function.getUnfilteredFilesNotEnabledImportTemplateDialog (admin.min.js?ver=3.19.0:3:7750)
    at _callee$ (admin.min.js?ver=3.19.0:3:48690)
    at tryCatch (admin.min.js?ver=3.19.0:3:29344)
    at Generator.<anonymous> (admin.min.js?ver=3.19.0:3:30993)
    at Generator.next (admin.min.js?ver=3.19.0:3:29893)
    at asyncGeneratorStep (admin.min.js?ver=3.19.0:3:24778)
    at _next (admin.min.js?ver=3.19.0:3:25011)
    at admin.min.js?ver=3.19.0:3:25127
    at new Promise (<anonymous>)
    at HTMLFormElement.<anonymous> (admin.min.js?ver=3.19.0:3:24947)
<img width="895" alt="Screenshot 2024-02-05 at 11 46 06" src="https://github.com/elementor/elementor/assets/600233/b9648cd5-6ec7-4b3d-8dc8-a1b2bc91b089">
<img width="828" alt="Screenshot 2024-02-05 at 11 46 11" src="https://github.com/elementor/elementor/assets/600233/2f211a59-e1fa-4578-aef7-7ee2ba2e20bd">

### Steps to reproduce

1. Go to /templates -> import templates
2. Select file
3. Click import - see JS error

### Expected behavior

Import should work

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Ubuntu 22
Latest wordpress
Clean install no other plugins
```

### Agreement

- [x] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by neok** [comment]
[elementor-62-2024-02-05.json](https://github.com/elementor/elementor/files/14164501/elementor-62-2024-02-05.json)
Example simple json file to import

**Comment by nicholaszein** [comment]
Hello, @neok.

Thank you for reaching out.

Unfortunately, there is not enough information to troubleshoot your issue. We tested importing templates on our end and we experienced no problems. Since you haven't described the issue in detail as required, and haven't shared the essential Elementor System Info, we cannot continue evaluating your issue.

Please, if you think you found a bug, make sure to submit the information required in the form. Sharing detailed information and the Elementor System Info is not optional.

Thank you
