### ISSUE TITLE
🔗 🚀 Feature Request: Advanced Google Maps Widget like Progress Map by Codespacing (Duplicate of #1319)

### ISSUE THREAD

**Issue by Tommielarsson** [elementor/elementor#2507]
Is it possible that Elementor thought of using a bit more advanced version of the Google Maps widget? With the one I use (Progress Map) you edit your post and enter the adress or coordinates then it shows up on the map depending on category. Would be great if Elementor used it combined with "posts" that I use since your code is more modern, faster and easier to use.

![fewsfse](https://user-images.githubusercontent.com/3650624/31002824-1830d458-a4ed-11e7-88e1-302149a0cf7a.jpg)

**Comment by arielk** [comment]
I do not think we'll make a combination of posts with a map using Elementor

But we have a plan to add integration to Google Map with the API, you can read more here: #1319

Thanks for the feedback!
