### ISSUE TITLE
⛔ ⌛ 🧩 3rd-party Lightbox plugin doesn't work with Containers after converting from Sections

### ISSUE THREAD

**Issue by endyb66** [elementor/elementor#25083]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

After moving from Sections layout to the new Flexbox Containers on all of my pages, my Lightbox plugin does not work anymore. It's the "Meow Lightbox" plugin. I've tried a bunch of others, none of them work. I can reproduce the issue when switching back to Sections on Elementor, so it seems to be an Elementor issue. The plugin has a "Selector" setting, where I can set a class from the div where the pictures are hosted in, this does not work anymore, so it seems that changing to the new Elementor layout does change more things.

### Steps to reproduce

Switching from Sections to the new Flexbox Container layout.

### Expected behavior

Lightbox on images should work.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [x] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.21
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 48M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Blocksy
	Version: 2.0.24
	Author: CreativeThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

== Active Plugins ==
	All in One SEO
		Version: 4.5.6
		Author: All in One SEO Team

	Classified Listing – Classified ads & Business Directory Plugin
		Version: 3.0.1
		Author: RadiusTheme

	CookieYes | GDPR Cookie Consent
		Version: 3.1.8
		Author: CookieYes

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	GTranslate
		Version: 3.0.5
		Author: Translate AI Multilingual Solutions

	Hide Admin Bar From Non-Admins
		Version: 1.0.1
		Author: Stranger Studios

	Image Watermark
		Version: 1.7.3
		Author: dFactory

	Independent Analytics
		Version: 2.2.0
		Author: Independent Analytics

	Limit Login Attempts Reloaded
		Version: 2.26.3
		Author: Limit Login Attempts Reloaded

	Meow Lightbox
		Version: 5.1.3
		Author: Jordy Meow

	Remove Dashboard Access
		Version: 1.2
		Author: TrustedLogin

	WP AutoTerms
		Version: 2.5.0
		Author: WP AutoTerms

	WP Frontend Delete Account
		Version: 1.7.0
		Author: Sanjeev Aryal


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @endyb66!

Thank you for reaching out! 🙏 

As explained in our Bug Report form, we do not provide support for 3rd-party plugins. However, it seems your plugin in particular checks for a class to work.

Just so you know, containers use the following class: **`.e-con`**. This might help you fix your issue. Otherwise, you can try the following class: **`.elementor`**

This should cover anything inside Elementor edited pages.

Elementor comes with a built-in Lightbox, that you can use instead of your custom plugin for anything. You don't really need a dedicated Lightbox plugin for most use cases.

You can learn more about the [Elementor Lightbox in the Help Center](https://elementor.com/help/lightbox/).

For now, that's all we can help you with.

### ⚠️ Please only post Issues about Bugs you found in the code of the Elementor or Elementor Pro plugins.

Kind regards
