### ISSUE TITLE
⛔ Site-wide 'Gaps' setting urgently needs responsive options to be useful

### ISSUE THREAD

**Issue by joexcm** [elementor/elementor#25103]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The option to set a global gap between elements is great (Site settings - Layout - Gaps).
However, if you set a wide column gap for desktop, there is no way of lowering this to an appropriate size on tablet and mobile, because there is no responsive option for Gaps, unlike Content Width and Container Padding.

### Steps to reproduce

1. In Site settings - Layout - Gaps, set a column gap of 40
2. Switch to tablet mode and you will see the gap is too wide, but cannot be altered independently of the desktop gap

Real life example: https://share.cleanshot.com/l2syJgXx

### Expected behavior

1. Go to Site settings - Layout - Gaps
2. There is a responsive desktop/tablet/mobile option next the Gaps preference to set the amount on a device basis

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.11.6-MariaDB-cll-lve
	PHP Version: 8.1.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: -
	Home URL: -
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.6.1
		Author: WP Engine

	Dashboard Welcome for Elementor
		Version: 1.0.7
		Author: IdeaBox Creations

	Easy WP SMTP
		Version: 2.2.0
		Author: Easy WP SMTP

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	LiteSpeed Cache
		Version: 6.1
		Author: LiteSpeed Technologies

	ManageWP - Worker
		Version: 4.9.19
		Author: GoDaddy

	Shield Security
		Version: 19.0.6
		Author: Shield Security

	WP-DBManager
		Version: 2.80.9
		Author: Lester 'GaMerZ' Chan


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Elements Usage ==
	
	wp-page : 1
		container : 5
		heading : 2
		image : 1
		text-editor : 2
		video : 4


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 2 of 2PHP: 2024-02-11 16:31:49 [notice X 1][../wp-content/plugins/elementor/core/experiments/manager.php::161] preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-12 09:40:20 [warning X 1][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Dashboard Welcome for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @joexcm,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Comment by Dionnie** [comment]
Man, you're just doing it wrong, you should use **_clamp_** when it comes to section padding left and right e.g 60px down to 20px, and your biggest gap should be equal and less than 60px (max section padding).
