### ISSUE TITLE
❌ It is not possible to add the <picture> tag to a featured image.

### ISSUE THREAD

**Issue by socialreza** [elementor/elementor#25111]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I want to add the <picture> tag to the featured image, when I use the post_thumbnail_html and wp_get_attachment_image filter, it ignores the <picture> tag and it is sensitive to it, because I put any tag other than the <picture> tag. It displays correctly.

```
function wrap_wp_get_attachment_image_with_picture_tag( $html, $attachment_id, $size, $icon, $attr ) {
    $html = '<picture>' . $html . '</picture>';
    return $html;
} add_filter( 'wp_get_attachment_image', 'wrap_wp_get_attachment_image_with_picture_tag', 10, 5 );
```

```
function custom_post_thumbnail_html( $html, $post_id, $post_thumbnail_id, $size, $attr ) {
    $picture_html = '<picture>';
    $picture_html .= $html;
    $picture_html .= '</picture>';
    return $picture_html;
} add_filter( 'post_thumbnail_html', 'custom_post_thumbnail_html', 10, 5 );
```

### Steps to reproduce

1. I use the post_thumbnail_html and wp_get_attachment_image filter.
2. When the Elementor Pro plugin is active, it ignores the <picture> tag.
3. When the Elementor Pro plugin is disabled, it displays the <picture> tag.

### Expected behavior

1. There shouldn't be a problem when using 2 post_thumbnail_html and wp_get_attachment_image filters to add the <picture> tag with the Elementor Pro plugin and it will display the <picture> tag correctly.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== wordpress : 6.4.3
== woocommerce : 8.5.2
== hello elementor : 3.0.1
== elementor : 3.19.2
== elementor pro : 3.19.2
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @socialreza,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
