### ISSUE TITLE
❌ License activation staging site list missing wpenginepowered.com

### ISSUE THREAD

**Issue by Pikamander2** [elementor/elementor#25138]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

https://elementor.com/help/staging-site-license-activation/

When activating an Elementor Pro license on a staging site, certain domains are supposed to not count toward the activation limit.

You have WPEngine's main domain (wpengine.com) listed as one of them, but they also use wpenginepowered.com these days as well and it's still not on your list, meaning that it can't be used when you only have a single site license.

### Steps to reproduce

1. Create a staging site on WPEngine like https://example.wpenginepowered.com
2. Try to activate Elementor Pro when you've already hit your license limit
3. It won't let you

### Expected behavior

1. Create a staging site on WPEngine like https://example.wpenginepowered.com
2. Try to activate Elementor Pro when you've already hit your license limit
3. It should let you since it's the same thing as https://example.wpengine.com

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
N/A
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Daveden2** [comment]
I would probably not call this request a "bug report". I feel you should contact support directly and they would be able to get this sorted for you.

**Comment by Pikamander2** [comment]
Elementor support said that they couldn't manually override it. It's a change that the Elementor team needs to make on their end.

**Comment by Daveden2** [comment]
Oh I see. I hope you get a favourable response to this request.

**Comment by nicholaszein** [comment]
@Pikamander2 we are reaching out to WP Engine to find out about this staging domain. If they confirm it is part of their staging stack, we will add it to our list.

However, keep in mind this is going to take a while.

A workaround is to use any of the other staging domains we do support for WP Engine:

 * .staging.wpengine.com (example.staging.wpengine.com)
 * stg.wpengine.com (examplestg.wpengine.com)
 * dev.wpengine.com (exampledev.wpengine.com)

You can also use one of these:

* dev.* (dev.example.com). This can also be implemented as:
   * exampledev.* (exampledev.example.com)
* local.* (local.example.com)
* test.* (test.example.com). This can also be implemented as:
   * .test. (example.test.example.com)
* staging.* (staging.example.com). This can also be implemented as:
   * .staging. (example.staging.example.com)
* staging[0-9].* (staging6.example.com). This can also be implemented as:
   * .staging[0-9].(example.staging6.example.com)
* stage.* (stage.example.com). This can also be implemented as:
   * .stage. (example.stage.example.com)

**Comment by imrook** [comment]
For anyone following this issue or arriving here via search, subdomains of `wpenginepowered.com` in the following format should now work:

```
*stg.wpenginepowered.com (examplestg.wpenginepowered.com)
*dev.wpenginepowered.com (exampledev.wpenginepowered.com)
```
