### ISSUE TITLE
⛔ Extra Database calls on non-logged in and logged in view on frontend.

### ISSUE THREAD

**Issue by wparslan** [elementor/elementor#25170]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am receiving some issues with query optimization here, As you can see on every page call the revisions are taken from the database even though I am not using the revisions.
The WP_POST_REVISION is also set to false.

<img width="1389" alt="image" src="https://github.com/elementor/elementor/assets/66727492/088390b0-92fe-4901-98dc-d768e7b0704e">
<img width="1389" alt="image" src="https://github.com/elementor/elementor/assets/66727492/a065e55a-2270-4405-a1d1-a8d7b0c89a9a">
<img width="1389" alt="image" src="https://github.com/elementor/elementor/assets/66727492/4cccfedc-e06b-45c2-b4c6-ebeadcab1b73">

Do let me know if any information is needed.

### Steps to reproduce

1. Add any post and resave it.
2. Go to frontend and you will see the duplicated query.

### Expected behavior

1. Install the Query Monitor Plugin.
2.  Go to frontend and you will see the duplicated query.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Elementor 
Elementor Pro
Query Monitor
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @wparslan!

Thank you for submitting your issue! 🙏 

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Please provide the missing System Info as required in the Bug Report form.

Best regards

**Comment by nicholaszein** [comment]
Hey @wparslan,

can you please provide the missing information?

**Comment by nicholaszein** [comment]
This issue is being closed due to lack of sufficient information, and not response from the author.

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind regards
