### ISSUE TITLE
❌ 🛟 Support Request: Arrow button on testimonial carousel does not work.

### ISSUE THREAD

**Issue by ritambuj** [elementor/elementor#25255]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

bask.ritambuj.tech

Please check the testimonial carousel with the heading - Indulge. Clicking on the right arrow does nothing, swipe to move is working fine, but not the arrow button.

### Steps to reproduce

1) Visit bask.ritambuj.tech.
2) Click on the right arrow button on the testimonial carousel (any one of the three on the homepage).

### Expected behavior

Upon clicking the right arrow the slide should be slide to right - 1 slide at a time.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
AWS - bitnami bundle for wordpress, apache web server.
Latest workpress
Hello theme
All visitors
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @ritambuj,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

Moreover you did not provide the required full Elementor System Information as indicated in the bug report form. While testing the testimonial carousel on our end, everything worked as expected.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
