### ISSUE TITLE
⛔ CAN'T IMPORT SVG ICON FROM EXPORTED TEMPLATES

### ISSUE THREAD

**Issue by FauzanEdris** [elementor/elementor#25366]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

SVG ICON FAILED TO IMPORT FROM THE EXPORTED TEMPLATES

### Steps to reproduce

1) CREATE 2 NEW WEBSITES
2) INSTALL THE HELLO ELEMENTOR THEME AND ELEMENTOR PLUGIN IN THAT 2 WEBSITES
3) GO TO WEBSITE 1
4) CREATE NEW PAGE
5) ADD BUTTON AND ICON WIDGETS
6) CONFIGURE THE ICON BY ADDING A CUSTOM ICON (SVG ICON) (UPLOAD SVG)
7) SAVE OR UPDATE THE PAGE
8) SAVE THE PAGE AS A TEMPLATE
9) DOWNLOAD THE TEMPLATE YOU ARE SAVED BEFORE
10) GO TO WEBSITE 2
11) CREATE NEW PAGE
12) OPEN THE TEMPLATE LIBRARY
13) INSERT THE TEMPLATE YOU DOWNLOADED BEFORE TO THE TEMPLATE LIBRARY IN WEBSITE 2
14) IMPORT THE TEMPLATE YOU INSERT BEFORE TO PAGE
15) AND THAT'S IT, SVG NOT IMPORTED AS EXPECTED

DETAIL IN VIDEO: https://drive.google.com/file/d/10Tn1qFfDmcGHUL4ph1ETklPmP9t3BNQt/view?usp=sharing

### Expected behavior

THE IMPORTED TEMPLATE SAME AS THE SOURCE (EXPORTED TEMPLATES)

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

** WEBSITE 1 **
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.54 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
	MySQL version: MySQL Community Server (GPL) v5.7.39
	PHP Version: 8.1.13
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 0
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://udontknowme.local
	Home URL: http://udontknowme.local
	WP Multisite: No
	Max Upload Size: 0 B
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.19.4
		Author: Elementor.com


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default


== Log ==
	
PHP: showing 1 of 1PHP: 2024-03-05 09:25:01 [notice X 1][../wp-content/plugins/elementor/core/experiments/manager.php::161] preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	

** WEBSITE 2 **
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.54 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
	MySQL version: MySQL Community Server (GPL) v5.7.39
	PHP Version: 8.1.13
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 0
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://udontknowme1.local
	Home URL: http://udontknowme1.local
	WP Multisite: No
	Max Upload Size: 0 B
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.19.4
		Author: Elementor.com


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default


== Log ==
	
PHP: showing 1 of 1PHP: 2024-03-05 09:25:00 [notice X 1][../wp-content/plugins/elementor/core/experiments/manager.php::161] preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by toineenzo** [comment]
That's normal, as the svg also needs to be uploaded to the secondary website

**Comment by FauzanEdris** [comment]
Hi @toineenzo!

For me, that doesn't seem normal. The normal expectation is that if you create an export/import template system, the imported result should match the source, isn't it? Or am I misunderstanding something?

It's not feasible for me to ask my client to download SVGs and replace them one by one in every section that uses SVGs. I feel like that's doubling the work and requiring more time.

Regards,

**Comment by nicholaszein** [comment]
Hello @FauzanEdris! 

Thank you for submitting your issue! 🙏 

SVGs pose a security concern, and won't be migrated from one website to another if they can't be validated. Also, both sites need to have the option to **`Enable Unfiltered File Uploads`** set to **`Enabled`** in the Elementor > Settings > Advanced page for the upload to take place, but it will still only work if the SVG can be validated.

**It's important to Note that template files do not include any assets, just links to the file that needs to be downloaded from the origin site. If you created your template on a local website, the destination site won't be able to import any media file because local websites can't be reached.** The same if you are using a template from a website that doesn't exist anymore, or doesn't allow public access. If this is the case for you, then it's a problem with your workflow, not with Elementor.

As I can see in your **Elementor System Info**, it seems you are testing on two local websites.

Can you clarify if this is the same scenario for your customers? Are you sharing a locally generated template with a public website? If you are, then please let me know.

Thank you.

Best regards

**Comment by nicholaszein** [comment]
This issue is being closed due to lack of sufficient information, and no response from the author.

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind regards
