### ISSUE TITLE
⛔ 🛟 Support Request: Sticky Scrolling Going over header

### ISSUE THREAD

**Issue by adam-poly** [elementor/elementor#25413]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

On a site built with sections, Hello Theme, and Elementor+Elementor Pro. On a page with 2 sections, one of them set for sticky scrolling, the content in the section set for sticky goes over the header. The header is built in Theme Builder using sections also. See attached video screen recording showing incorrect behaviour on Elementor 3.20 verses the correct behaviour on elementor 3.19. 

https://github.com/elementor/elementor/assets/163076118/1f7ba878-6bf8-4c0c-8c25-7a96f414492e

### Steps to reproduce

Make a header in theme Builder with sections
Make a page template with 2 sections, one of them sticky to keep the content under the header as you scroll.
Update from elementor 3.19 to elementor 3.20 

### Expected behavior

The content in the section with sticky scrolling should go under the header on elementor 3.20 like it does on elementor 3.19/ 

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Nginx
Wordpress 6.4.3
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by toineenzo** [comment]
Can you post your full the system info export from Elementor?

**Comment by nicholaszein** [comment]
Did you increase the z-index of the sticky header?

**Comment by adam-poly** [comment]
> Did you increase the z-index of the sticky header?

Thanks for the tip. Have tried now. Increasing the Z Index of the header after the update to 3.20 does fix it.

**Comment by nicholaszein** [comment]
Hi @adam-poly,

Thanks for checking the z-index settings.

I'm closing this issue as this is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
