### ISSUE TITLE
⛔ Message "Don’t miss out on the new version of Elementor" is back on Dashboard

### ISSUE THREAD

**Issue by stefanhz** [elementor/elementor#25474]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

This issue was reported as having been fixed, and it does not seem to be fixed.

A notification shows on the dashboard saying "Don't miss out on the new version of Elementor" ... even though I have updated to the latest version. 

I have disabled all plugins which disappeared that message. With the standard Elementor plugin alone, the message does not show. As soon as I enabled the PRO plugin, the message came back.

I disconnected and re-connected my license to no avail. Even when I disconnected the license, the message was still there.

So I deactivated and deleted the PRO plugin (which had that message disappear), downloaded a fresh copy from the Elementor website, and as soon as I had it uploaded and activated, that pesky message was back.

<img width="666" alt="screenshot_9961" src="https://github.com/elementor/elementor/assets/3057588/42fefe3e-1e95-4b6e-bd86-946d4cfc4327">

### Steps to reproduce

See above. I don't know what else to say. 

List of active plugins:
Active Plugins		
Activity Log - 2.9.0	By Activity Log Team	
Antispam Bee - 2.11.5	By pluginkollektiv	
Copy & Delete Posts - 1.4.5	By Copy Delete Posts	
Elementor - 3.19.2	By Elementor.com	
Elementor Pro - 3.20.0	By Elementor.com	
Error Log Monitor - 1.7.7	By Janis Elsts	
LiteSpeed Cache - 6.1	By LiteSpeed Technologies	
Login Lockdown PRO - 5.52	By WebFactory Ltd	
Post SMTP - 2.8.11	By Post SMTP	
Redirection - 5.4.2	By John Godley	
Security Optimizer - 1.4.10	By SiteGround	
UpdraftPlus - Backup/Restore - 1.23.16	By UpdraftPlus.Com, DavidAnderson	
UsageDD - 2.1	By Dion Designs	
WP 2FA - Two-factor authentication for WordPress - 2.6.2	By Melapress	
WP Armour - Honeypot Anti Spam - 2.1.14	By Dnesscarkey	
WP Last Modified Info - 1.8.9	By Sayan Datta

### Expected behavior

no message asking me to update when I already am on the latest version.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.17
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://dev.loveablize.com
	Home URL: https://dev.loveablize.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Denver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.9.0
		Author: Activity Log Team

	Antispam Bee
		Version: 2.11.5
		Author: pluginkollektiv

	Copy &amp; Delete Posts
		Version: 1.4.5
		Author: Copy Delete Posts

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.0
		Author: Elementor.com

	Error Log Monitor
		Version: 1.7.7
		Author: Janis Elsts

	LiteSpeed Cache
		Version: 6.1
		Author: LiteSpeed Technologies

	Login Lockdown PRO
		Version: 5.52
		Author: WebFactory Ltd

	Post SMTP
		Version: 2.8.11
		Author: Post SMTP

	Redirection
		Version: 5.4.2
		Author: John Godley

	Security Optimizer
		Version: 1.4.10
		Author: SiteGround

	UpdraftPlus - Backup/Restore
		Version: 1.23.16
		Author: UpdraftPlus.Com, DavidAnderson

	UsageDD
		Version: 2.1
		Author: Dion Designs

	WP 2FA - Two-factor authentication for WordPress
		Version: 2.6.2
		Author: Melapress

	WP Armour - Honeypot Anti Spam
		Version: 2.1.14
		Author: Dnesscarkey

	WP Last Modified Info
		Version: 1.8.9
		Author: Sayan Datta


== Elements Usage ==
	
	footer : 1
		container : 6
		heading : 2
		icon : 1
		icon-list : 1
		nav-menu : 1
		text-editor : 2
	header : 1
		container : 3
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 8
		blockquote : 5
		button : 3
		container : 145
		form : 3
		heading : 25
		icon : 4
		image : 31
		loop-carousel : 1
		testimonial-carousel : 1
		text-editor : 45
		video : 2
	single-post : 1
		container : 2
		theme-post-content : 1
		theme-post-title : 1
	loop-item : 1
		container : 3
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 392024-02-10 16:43:38 [info] elementor-pro::elementor_pro_updater Started 
2024-02-10 16:43:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-10 16:43:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-10 16:43:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-10 16:43:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-10 16:43:38 [info] elementor::elementor_updater Started 
2024-02-10 16:43:38 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-10 16:43:38 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-10 16:43:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-10 16:43:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-10 16:43:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-26 15:53:00 [info] elementor-pro::elementor_pro_updater Started 
2024-02-26 15:53:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-26 15:53:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-26 15:53:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.19.3',
)]
2024-03-11 20:09:46 [info] elementor-pro::elementor_pro_updater Started 
2024-03-11 20:09:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-11 20:09:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-11 20:09:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-11 20:09:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]

JS: showing 3 of 3JS: 2023-12-30 18:37:46 [error X 2][../wp-admin/load-scripts.php?c=1&amp;loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&amp;ver=6.4.2:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-01-06 00:32:18 [error X 1][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.18.3:2:10702] Cannot read properties of undefined (reading &#039;params&#039;) 
JS: 2024-01-06 00:38:30 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:1115811] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 

PHP: showing 1 of 1PHP: 2024-01-05 17:42:24 [notice X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by stefanhz** [comment]
Elementor Pro v3.20.1 installed just now, and the situation remains as described above.

**Comment by toineenzo** [comment]
Have you also updated Elementor free to 3.20? In you system info it still says 3.19

**Comment by stefanhz** [comment]
That is correct. 3.19.2 it is (for the free version). I checked for updates just now, and don't get any 3.20 being available for the free version.

**Comment by stefanhz** [comment]
k, I manually downloaded the latest version 3.20.2 from WordPress.org and uploaded it to replace the existing plugin, and now that message is gone.

In case you are wondering why I went that complicated way: I clicked on "force update" several times, and still WordPress would not show me a new version of Elementor standard to be available.

**Comment by nicholaszein** [comment]
Hello @stefanhz,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The latest version as of the time of your submission was Elementor Core version 3.20.0. You were running version 3.19.2.

### ✅ What you can do to solve your issue:
Always check the changelog to ensure you have the latest version. Sometimes WordPress will delay the display of a plugin's update until the next cycle. There is nothing we can do about it. It's a WordPress limitation.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
