### ISSUE TITLE
✅ 🐞 WordPress 6.5 compatibility: "Edit with Elementor" missing for pages previously edited with Elementor

### ISSUE THREAD

**Issue by liviopv** [elementor/elementor#25495]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When WordPress 6.5 RC3 is active, the "Edit with Elementor" button that took over the editor content area for pages previously edited with Elementor is missing

![CleanShot 2024-03-22 at 09 35 17@2x](https://github.com/elementor/elementor/assets/14153300/78f058f2-eb93-4718-b0ec-666e5b3d4b86)

### Steps to reproduce

1. Activate WordPress 6.5
2. Open a page previously edited with Elementor in the default WordPress editor
3. The "Edit with Elementor" button will not be visible

### Expected behavior

1. Open a page previously edited with Elementor in the default WordPress editor
2. The "Edit with Elementor" button will be visible in the content area

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.0.22
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5-RC3
	Site URL: http://localivio.local
	Home URL: http://localivio.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.20.2
		Author: Elementor.com

	WordPress Beta Tester
		Version: 3.5.5
		Author: WordPress Upgrade/Install Team


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default


== Log ==
	


== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by m1ga** [comment]
can reproduce that too. It is still in the page but hidden by CSS

**Comment by m1ga** [comment]
fixed with https://github.com/elementor/elementor/pull/25507 :+1:

**Comment by nicholaszein** [comment]
Elementor Core version 3.20.3 is out with the fix for this issue.

Feel free to update to the latest version!

Thanks for your contribution! 🙏
