### ISSUE TITLE
❌ Using CSS variables in the color picker doesn't work

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#25517]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I remember seeing this in one of the marketing materials back then, but it's 2024 and this still doesn't work.

<img width="305" alt="image" src="https://github.com/elementor/elementor/assets/60075863/db055d8a-8fc5-4aec-9b7f-b036960dc75c">

### Steps to reproduce

1. Define --my-color: blue; in :root.
2. Add var(--my-color) in the color picker on the desired element.

### Expected behavior

It should work right away, but instead, it gets removed. It makes no sense not to allow us to do this

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
No need.
```

### Agreement

- [x] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @azkalex,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Comment by nicholaszein** [comment]
We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.
