### ISSUE TITLE
Carrossel imagem Numbers 

### ISSUE THREAD

**Issue by bombarda-rpd** [elementor/elementor#2553]
Hi!

Elementor is awesome but sometimes little things are also important. 

Think about the possibility of add the number of images on Lightbox carrossel widget, like 1/10, 2/10

Thanks

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
