### ISSUE TITLE
[Feature request] Responsive Content Position

### ISSUE THREAD

**Issue by dave-hiddendepth** [elementor/elementor#2554]
## Feature Request:
Add ability to change content position for mobile, tablet and desktop 

## Why:
Layouts that work on a wide desktop may not work on a tall tablet or mobile. 

## How:
Standard 3 device type options used in other elements.

**Comment by Turanligil** [comment]
+1

**Comment by gabiudrescu** [comment]
now that we have [responsive background images](https://github.com/pojome/elementor/issues/2355), maybe we can get this too. on desktop, you might want the text to be aligned top, while on mobile you need it aligned to bottom - such a behavior would be useful.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!
