### ISSUE TITLE
⛔ 🧩 🛟 Support Request: Incorrect linking for CSS files if the HTTPS site is accessed with HTTP

### ISSUE THREAD

**Issue by frzsombor** [elementor/elementor#25553]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

For many long months, we struggled with an issue where the layout of our simple Elementor website would completely fall apart at entirely random times and would only be restored after clearing the Elementor cache. The error looked simple: for some reason, sometimes Elementor would generate the cache, linking certain CSS files over HTTP instead of HTTPS, which then failed to load on our HTTPS-operated site due to mixed content restrictions.

I tried approaching the problem from countless directions to levels where I debugged the PHP classes responsible for Elementor plugin cache generation - all in vain. I was aware that if the site loaded over HTTP, logically, Elementor would also generate the cache with HTTP links, but since the site by default redirects all requests to HTTPS, I couldn’t reproduce this.

Today, the issue reemerged, even though everything was fine yesterday. I started from the fact that Elementor had automatically updated just after midnight, therefore Elementor automatically cleared the cache. I reviewed the entire last 24 hours of traffic, which, besides regular visitors, included numerous malicious and benign bot requests. And here came the breakthrough. After the plugin update and Elementor cache clearing, there was no real visitor traffic on the site, only bots. Among these requests, I noticed several bots opening the website directly through the IP, including some that redirected to our domain, but the redirections were only set the http://123.4.5.6/ URL, for example, http://123.4.5.6/index.php loaded without issues. And since this was the first opening of the website after the Elementor cache clearing, Elementor generated the cache over HTTP. I tested it: another cache clearing, direct IP opening, HTTPS domain opening, and the site was broken again.

I understand that this problem may not be solely related to Elementor but could also stem from improper server configuration and I have already contacted the company with my findings. However, considering our website is hosted on a popular shared hosting platform, this issue has the potential to impact many other users.

### Steps to reproduce

1. Setup a simple, basic Elementor website on a domain and make sure to use HTTPS in WP site url settings.
2. Make sure you can still access the website with direct IP over HTTP
3. Use a few modules that will make Elementor to import related CSS files for them (no 3rd party widget plugin required)
4. Clear Elementor cache manually
5. Open the website with direct IP over HTTP so Elementor will generate cache with HTTP links
6. Open the website with the domain over HTTPS
8. The layout is broken, because the CSS files are linked with HTTP and will not load

### Expected behavior

1. Setup a simple, basic Elementor website on a domain and make sure to use HTTPS in WP site url settings.
2. Make sure you can still access the website with direct IP over HTTP
3. Use a few modules that will make Elementor to import related CSS files for them (no 3rd party widget plugin required)
4. Clear Elementor cache manually
5. Open the website with direct IP over HTTP so Elementor will generate cache.
6. Elementor sees that (from WP settings) that the site is using HTTPS, so it will generate cache with this protocol.
7. Open the website with the domain over HTTPS
8. The layout looks as expected, because the CSS files are linked with the same protocol that is set for the site URL in WP

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.17
	PHP Version: 8.2.16
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://[redacted]
	Home URL: https://[redacted]
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: hu_HU
	Timezone: Europe/Budapest
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.20.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 5.9.13
		Author: WPDeveloper

	Simple Custom CSS and JS PRO
		Version: 4.36.1
		Author: SilkyPress.com

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	User Role Editor
		Version: 4.64.2
		Author: Vladimir Garagulya

	Wordfence Security
		Version: 7.11.4
		Author: Wordfence

	WP Mail SMTP
		Version: 4.0.1
		Author: WP Mail SMTP

	Yoast SEO
		Version: 22.3
		Author: Team Yoast


== Features ==
	Custom Fonts: 1
	Custom Icons: 1

== Integrations ==
	
	recaptcha: Active


== Elementor Experiments ==
	Improved Asset Loading: Inactive
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 402024-03-14 06:36:27 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-14 06:36:27 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-14 06:36:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-14 06:36:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-14 06:36:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-21 15:25:51 [info] elementor::elementor_updater Started 
2024-03-21 15:25:51 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-21 15:25:51 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-21 15:25:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-26 18:46:43 [info] elementor::elementor_updater Started 
2024-03-26 18:46:43 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-26 18:46:43 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-26 18:46:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-26 18:46:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-26 18:46:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-27 18:23:19 [info] elementor-pro::elementor_pro_updater Started 
2024-03-27 18:23:19 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-27 18:23:19 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-27 18:23:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.20.2',
)]
2024-03-27 18:23:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.2',
  'to' => '3.20.2',
)]

PHP: showing 2 of 2PHP: 2024-02-10 11:28:39 [notice X 58][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::96] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-21 14:47:31 [warning X 1][../wp-content/plugins/elementor/core/page-assets/data-managers/widgets-css.php::29] Undefined variable $asset_url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @frzsombor,

Thanks for contacting us! 🙏 

### 🛟 This is more of a Hosting support question, not really something we can help with here. 

You need to properly configure your site/server to always force a secure connection. You should never login using the https protocol, as this will inadvertently record all saved URLs based on the protocol currently used by the logged-in user. This is the WordPress default behavior. Elementor only fetches the URL that the current user is currently logged-in through via default WordPress Hooks. You are essentially causing mixed content issues, and a security risk by logging in using an insecure protocol.

Reach out to your hosting support and ask for assistance on how to properly force all connections to go through the HTTPS protocol.

After you've finished this process with your hosting provider, follow this tutorial I've created on the Elementor Global Community on Facebook:

https://www.facebook.com/groups/Elementors/permalink/2661661010626335

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
