### ISSUE TITLE
⛔ 🧩 Empty sidebar after click - "style" tab

### ISSUE THREAD

**Issue by firewaterskr** [elementor/elementor#25584]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello. When I edit the page and click on the left sidebar( Editing Heading or Editing Image) and then I click on tab - style... I got an empty sidebar and can't edit this element

### Steps to reproduce

1. Edit page
2. Choose Image or H1 or H2 
3. Click on tab "style" in the left sidebar

### Expected behavior

1. Must works like other tabs in the left sidebar( like,  content and advanced)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Duplicator
Upgrade to Pro | Deactivate
Migrate and backup a copy of your WordPress files and database. Duplicate and move a site from one location to another quickly.

Version 1.5.8.1 | By Duplicator | View details | Manage
Enable auto-updates
Select Elementor	
Elementor
Settings | Deactivate
The Elementor Website Builder has it all: drag and drop page builder, pixel perfect design, mobile responsive editing, and more. Get started now!

Version 3.20.3 | By Elementor.com | View details | Docs & FAQs | Video Tutorials
Enable auto-updates
Select Elementor Pro	
Elementor Pro
Deactivate
Elevate your designs and unlock the full power of Elementor. Gain access to dozens of Pro widgets and kits, Theme Builder, Pop Ups, Forms and WooCommerce building capabilities.

Version 3.20.2 | By Elementor.com | View details | Changelog
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by firewaterskr** [comment]
![зображення_2024-04-01_103641710](https://github.com/elementor/elementor/assets/165642118/319cff99-6285-4238-8c23-bc62f47ae618)

**Comment by firewaterskr** [comment]
![зображення_2024-04-01_103711424](https://github.com/elementor/elementor/assets/165642118/ab7985e3-2ab8-4ce6-bc46-073d8a5a72ae)

**Comment by nicholaszein** [comment]
Hello @firewaterskr.

Please provide the Full Elementor System Info as required in the Bug Report form. It is not optional. We need this information to understand what is going under the hood. The information you provided is not the one instructed to be shared.

To find the Elementor System Info go to your WordPress **`Dashboard`** > **`Elementor`** > **`System Info`** page, scroll down to the last section where it says **Copy & Paste Info**, click on the text field to `copy` and then paste it here.

![image](https://github.com/elementor/elementor/assets/113993460/7fc46629-f1a9-43b8-8da3-2cbb578197e9)

**Comment by firewaterskr** [comment]
== Server Environment ==
	Operating System: WINNT
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.29
	PHP Version: 8.0.18
	PHP Memory Limit: 1536M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://elementor.loc
	Home URL: http://elementor.loc
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 1536M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Admin Email: info@goodgabble.com
	Debug Mode: Active

== Theme ==
	Name: PeepSo Theme: Gecko
	Version: 6.3.12.0
	Author: PeepSo, Inc.
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 OPR/108.0.0.0

== Active Plugins ==
	CM Answers Pro
		Version: 4.7.4
		Author: CreativeMindsSolutions

	Duplicator
		Version: 1.5.8.1
		Author: Duplicator

	Elementor
		Version: 3.20.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com

	PeepSo
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: Audio &amp; Video
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: Chat
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: Email Digest
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: File Uploads
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: Friends
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: Groups
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: Photos
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Core: User Limits
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Monetization: WooCommerce, Dokan and Product Vendors
		Version: 6.3.12.0
		Author: PeepSo

	PeepSo Monetization: WPAdverts
		Version: 6.3.12.0
		Author: PeepSo

	WP Crontrol
		Version: 1.16.2
		Author: John Blackbourn

	WP File Manager
		Version: 7.2.5
		Author: mndpsingh287

	WPMU DEV Dashboard
		Version: 4.11.25
		Author: WPMU DEV


== Must-Use Plugins ==
	Hosting
		Version: 0.1
		Author: 


== Elements Usage ==
	
	section : 8
		button : 29
		counter : 6
		heading : 39
		icon : 13
		image : 15
		sidebar : 2
		spacer : 2
		text-editor : 32
	wp-post : 7
		container : 7
		wprm-recipe : 7
	wp-page : 6
		button : 11
		container : 46
		heading : 30
		icon-list : 1
		image : 16
		image-carousel : 1
		loop-grid : 1
		nav-menu : 1
		shortcode : 8
		sidebar : 2
		social-icons : 1
		spacer : 2
		text-editor : 20
		toggle : 2
		woocommerce-products : 2
	loop-item : 5
		container : 2
		posts : 1
		theme-post-content : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page, product, advert, tpg_builder, sermons, cma_thread, qsm_quiz
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
JS: showing 4 of 4JS: 2024-03-10 23:15:26 [error X 1][https://onlineshepherd.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.19.4:3:108027] Routes: `false` not found. 
JS: 2024-03-27 20:56:25 [error X 24][https://goodgabble.com/wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7564] ReactUtils is not defined 
JS: 2024-03-27 21:05:41 [error X 50][https://goodgabble.com/wp-content/plugins/elementor/assets/lib/nouislider/nouislider.min.js?ver=13.0.0:2:4604] noUiSlider (13.0.0): &#039;start&#039; option is incorrect. 
JS: 2024-03-28 02:11:25 [error X 4][https://goodgabble.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:816057] Cannot read properties of undefined (reading &#039;localized&#039;) 

Log: showing 20 of 372024-03-20 13:48:04 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-20 13:48:04 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-20 13:48:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-20 13:48:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-20 14:20:44 [info] elementor-pro::elementor_pro_updater Started 
2024-03-20 14:20:44 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-20 14:20:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-20 14:20:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-26 07:43:16 [info] elementor-pro::elementor_pro_updater Started 
2024-03-26 07:43:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-26 07:43:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-26 07:43:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-26 07:43:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-26 07:43:17 [info] elementor::elementor_updater Started 
2024-03-26 07:43:17 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-26 07:43:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-26 07:43:17 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-26 07:43:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-26 07:43:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-26 07:43:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]

PHP: showing 1 of 1PHP: 2024-03-27 22:35:15 [warning X 10][/var/web/site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: /var/web/site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/web/site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/web/site/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/web/site/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Thank you @firewaterskr! 🙏

**Comment by nicholaszein** [comment]
Hi @firewaterskr,

after investigating your issue, we concluded this is most likely caused by a conflict with one of your other plugins or your theme. The empty widget panel only happens when an add-on is using deprecated methods.

To isolate this conflict please try these **Troubleshooting** steps:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

2. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

3. 📋 **Meet the Requirements** Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - Your WordPress memory limit is too low. Please increase it to at least 256M, more preferably to 512M. To learn how to increase the Memory Limit follow this article: https://elementor.com/help/elementor-widget-panel-not-loading/#increase-memory-limit

#### Please follow the steps above and let us know if the issue persists.

Regards

**Comment by firewaterskr** [comment]
@nicholaszein, but I don't see any error logs or warnings in the debug.log

**Comment by firewaterskr** [comment]
@nicholaszein When I click on tab style - in the console log, I see this error

```
nouislider.min.js?ver=13.0.0:2 Uncaught Error: noUiSlider (13.0.0): 'start' option is incorrect.
    at Object.g [as t] (nouislider.min.js?ver=13.0.0:2:4610)
    at nouislider.min.js?ver=13.0.0:2:10281
    at Array.forEach (<anonymous>)
    at dt (nouislider.min.js?ver=13.0.0:2:10148)
    at Object.create (nouislider.min.js?ver=13.0.0:2:22928)
    at n.initSlider (editor.min.js?ver=3.20.3:3:322777)
    at n.onReady (editor.min.js?ver=3.20.3:3:323918)
    at Object._triggerMethod (backbone.marionette.…er=2.4.5.e1:24:7999)
    at n.triggerMethod (backbone.marionette.…r=2.4.5.e1:24:21465)
    at n.onRender (editor.min.js?ver=3.20.3:3:240982)
```

from this file - 
http://elementor.loc/wp-content/plugins/elementor/assets/lib/nouislider/nouislider.min.js?ver=13.0.0

**Comment by Alaric84** [comment]
I have exactly the same issue.

`nouislider.min.js?ver=13.0.0:2 Uncaught Error: noUiSlider (13.0.0): 'start' option is incorrect.
    at Object.g [as t] (nouislider.min.js?ver=13.0.0:2:4610)
    at nouislider.min.js?ver=13.0.0:2:10281
    at Array.forEach (<anonymous>)
    at dt (nouislider.min.js?ver=13.0.0:2:10148)
    at Object.create (nouislider.min.js?ver=13.0.0:2:22928)
    at n.initSlider (editor.min.js?ver=3.21.0:3:327530)
    at n.onReady (editor.min.js?ver=3.21.0:3:328671)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:7999)
    at n.triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:21465)
    at n.onRender (editor.min.js?ver=3.21.0:3:245735)`

**Comment by RolandBrian** [comment]
I have the exact same issue.  
For me the issue appears to be the result of "WP Cloud Plugins - Google Drive (Use-your-Drive)". This is a very powerful and useful plugin and I love the capabilities.  Whenever I Deactivate this plugin the Style Tab menus show up properly.  Until I can find a better solution, I disable this plugin, make the necessary page adjustments via the Style Tab then go back and Reactivate the plugin and all my previous text code associated with this plugin is saved and continues to work.

**Comment by nicholaszein** [comment]
Hello,

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Your issue is caused by a 3rd-party plugin conflicting with Elementor. We do not provide support for 3rd-party plugins. You'll need to find the plugin that is causing the issue by following the [instructions in this comment](https://github.com/elementor/elementor/issues/25584#issuecomment-2034282723), and then reach out to the 3rd-party plugin support and ask them to fix the incompatibility.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
