### ISSUE TITLE
✅ Beta v3.21.0 is out 👋

### ISSUE THREAD

**Issue by avivu** [elementor/elementor#25590]
![cover-3 21](https://github.com/elementor/elementor/assets/76733085/2aebea21-a7aa-48b5-8073-64575f4a7df2)

Beta versions of Elementor and Elementor Pro 3.21 are now available, and you can read all about them in [the Announcements section of the Discussion tab](https://github.com/orgs/elementor/discussions/25589). This is also where you will find all future beta version announcements.

- To report a bug related to beta versions - open a new [🐞 Bug Report](https://elemn.to/gh-new-bug-report)
- For feature requests - open a new [🚀 Feature Request](https://elemn.to/gh-new-feature-request)
- For other comments, specifically related to each of our announcements - comment on them directly

**Comment by nicholaszein** [comment]
Hi beta testers!

### Elementor and Elementor Pro version 3.21.0 are now available for update for the general public! 🚀 🥳 🙌 

We'd like to thank you all for contributing to this discussion, and for sharing your feedback!

Special thanks go to our contributors who helped make this release possible:

- @79ho3ein
- @parfilov 
- @efintina 
- @Daveden2 
- @Joliamendi 
- @Kishorchandth 
- @jazir555 
- @black-eye 

Thank you! See you on the next one! 🙏 

**Cheers 🥂**

> Changelogs of Elementor Core and Pro
> [Elementor Core](https://wordpress.org/plugins/elementor/#developers)
> [Elementor Pro](https://elementor.com/pro/changelog/)
