### ISSUE TITLE
❌ Swatch issues collections

### ISSUE THREAD

**Issue by mesmaili151** [elementor/elementor#25605]
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5
	Site URL: https://sakoudar.ir/app
	Home URL: https://sakoudar.ir/app
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Woodmart Child
	Version: 1.0.3
	Author: XTemos
	Child Theme: Yes
	Parent Theme Name: Woodmart
	Parent Theme Version: 7.4.3
	Parent Theme Author: XTemos

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Checkout Field Editor for WooCommerce (Pro)
		Version: 3.5.1
		Author: ThemeHigh

	CMB2
		Version: 2.11.0
		Author: CMB2 team

	Elementor
		Version: 3.20.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com

	Menu Icons
		Version: 0.13.12
		Author: ThemeIsle

	Relevanssi
		Version: 4.22.1
		Author: Mikko Saari

	Safe SVG
		Version: 2.2.4
		Author: 10up

	TFluencer core
		Version: 1.2.0
		Author: Mohammad Esmaeilimoakhar

	WooCommerce
		Version: 8.7.0
		Author: Automattic

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Pages Panel: Inactive by default
	Notes: Active by default
	Display Conditions: Active
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active

== Log ==
	
JS: showing 9 of 9JS: 2024-02-19 21:37:39 [error X 12][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:814165] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-03-11 21:28:01 [error X 76][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.4:3:815250] Cannot read properties of undefined (reading 'localized') 
JS: 2024-03-17 00:11:41 [error X 696][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading 'clone') 
JS: 2024-03-17 00:11:43 [error X 10][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading 'changestop') 
JS: 2024-03-26 21:15:25 [error X 13][../wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7564] ReactUtils is not defined 
JS: 2024-03-29 19:44:37 [error X 31][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.20.1:2:64496] Cannot convert undefined or null to object 
JS: 2024-03-31 19:59:34 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:54583] Cannot read properties of undefined (reading 'activate') 
JS: 2024-04-02 21:04:41 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:586039] Element type not found: 'tp-woo-single-pricing' 
JS: 2024-04-02 21:04:46 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.3:3:648673] Cannot read properties of undefined (reading 'isDesignable') 

PHP: showing 4 of 4PHP: 2024-02-26 20:36:10 [notice X 6][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-02-29 19:11:07 [notice X 6][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-29 22:45:00 [notice X 4][../wp-content/plugins/elementor/core/files/css/base.php::778] Undefined index: padding_mobile [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-28 23:51:54 [notice X 1][../wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 292024-02-29 13:10:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.19.4',
)]
2024-03-24 16:11:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.2',
)]
2024-03-24 16:11:05 [info] elementor::elementor_updater Started 
2024-03-24 16:11:05 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-24 16:11:05 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-24 16:11:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.2',
)]
2024-03-24 16:11:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.2',
)]
2024-03-26 20:56:38 [info] elementor::elementor_updater Started 
2024-03-26 20:56:38 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-26 20:56:38 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-26 20:56:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-27 21:09:08 [info] elementor-pro::elementor_pro_updater Started 
2024-03-27 21:09:08 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-27 21:09:08 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-27 21:09:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.1',
)]
2024-03-31 15:16:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-31 15:16:23 [info] elementor-pro::elementor_pro_updater Started 
2024-03-31 15:16:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-31 15:16:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-31 15:16:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
This issue doesn't follow our Guidelines.
