### ISSUE TITLE
❌ 🔗 🧩 Conflict with the Custom Add to Cart widget inside the Loop Grid (Duplicate of #25606)

### ISSUE THREAD

**Issue by mesmaili151** [elementor/elementor#25612]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

** Please have look at #25606
I also did test it with Hello Elementor and default WordPress default theme! and I was wishing to ask it before closing the issue!

### Steps to reproduce

** Please have look at #25606

### Expected behavior

** Please have look at #25606

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
** Please have look at #25606
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by mesmaili151** [comment]
dear @nicholaszein any idea?

**Comment by toineenzo** [comment]
> dear @nicholaszein any idea?
> 
> 

Have you tried contacting the devs of Woodmart? It's a conflict with a third party plugin! (It's doesn't help to create another issue here)

**Comment by nicholaszein** [comment]
@mesmaili151.

My answer remains the same as in the duplicated issue you've referenced. Please reach out to the developer of the WoodMart theme, or use the normal Add-to-cart widget. The Custom Add to Cart widget was not meant to be used with other themes/addons.

Please don't insist. Respect our [Contribution Guidelines](https://elemn.to/gh-contributing) and [Code of Conduct](https://elemn.to/gh-code-of-conduct).

Kind regards
