### ISSUE TITLE
❌ Nav Menu widget is blank for a second after closing it and reopening it quickly

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#25665]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I have a nav menu widget placed in my header with Elementor pro. When tapping on the hamburger icon in the header, the menu opens with all menu items loading immediately. If I close the hamburger menu and quickly reopen it, the menu content is blank for ~.5s-1s, then the content pops in, which looks incredibly janky.

### Steps to reproduce

1. Place nav menu widget in header.
2. load the page on mobile
3. open the menu, quickly close it then tap the hamburger asap to open it again
4. Watch as the menu is blank for a short period, then the content loads.

### Expected behavior

The menu content should display immediately consistently, even when the menu is closed and reopened quickly.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
N/A
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

Edit: It actually happens on any subsequent menu open after the first one

**Comment by nicholaszein** [comment]
Hello @jazir555, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue following these guidelines. 😉 

Best regards
