### ISSUE TITLE
⛔ New Elementor Controls Loading Performance Feature has no effect when enabled

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#25749]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I have enabled the new Elementor Controls loading experiment introduced in the update released today, and I've had absolutely zero improvement in my pagespeed scores or real world loading time. 

I've tried regenerating the css via Elementor tools, clearing all of my plugin and server caches, deactivated and reactivated Elementor, purged and disabled, disabled and then reactivating my object caching (Docket Cache), purging and disabling my Page Caching plugin (Flyingpress), deactivating and reactivating all of my pagespeed optimization plugins entirely then reactivating them, purged OPCache, restarted my entire VPS server stack (NGINX, PHP, MySQL), cleaned NGINX's FastCGI cache, downgrading from php 8.3 to 8.2, reverting back from 8.2 to php 8.3, and still no improvements. 

The toggle is completely placebo from what I can tell, my pagespeed test metrics are identical before and after enabling the experiment. My TTFB specifically is also exactly the same pre/post enabling the toggle.

### Steps to reproduce

1. Enable the experiment
2. Purge all caches, and clear any optimization plugin settings which may effect Elementor
3. Refresh setup so all performance optimization settings are exactly the same as prior to updating Elementor.
4. Pull up the new pagespeed test results and compare vs the old pagespeed test scores from prior to updating Elementor
5. No difference is observed

### Expected behavior

The new controls loading toggle should have the expected performance benefit, currently it has no effect.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.24.0
	MySQL version: mariadb.org binary distribution v10.11.7-MariaDB-1:10.11.7+maria~deb12-log
	PHP Version: 8.3.6
	PHP Memory Limit: 256M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.4
	Site URL: https://example.com
	Home URL: https://example.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1024M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: -8
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Database Cleaner PRO
		Version: 3.2.8
		Author: Younes JFR.

	Asset CleanUp Pro: Page Speed Booster
		Version: 1.2.4.9
		Author: Gabe Livan

	Disable Gutenberg
		Version: 3.1.1
		Author: Jeff Starr

	Docket Cache
		Version: 23.08.02
		Author: Nawawi Jamili

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Duplicator Pro
		Version: 4.5.16.3
		Author: Duplicator

	Elementor
		Version: 3.21.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.0
		Author: Elementor.com

	File Manager Advanced
		Version: 5.2.3
		Author: modalweb

	Fluent Snippets
		Version: 10.33
		Author: Fluent Snippets

	Flying Pages
		Version: 2.4.6
		Author: WP Speed Matters

	FlyingPress
		Version: 4.13.3
		Author: FlyingWeb

	Hide admin notices
		Version: 3.1.0
		Author: Rémi Leclercq

	Minify HTML
		Version: 2.1.9
		Author: Tim Eckel

	Perfmatters
		Version: 2.2.6
		Author: forgemedia

	Rank Math SEO
		Version: 1.0.216
		Author: Rank Math

	Show IDs by Echo
		Version: 1.1.3
		Author: Echo Plugins

	Stream
		Version: 4.0.0
		Author: XWP

	WooCommerce
		Version: 8.7.0
		Author: Automattic

	WooCommerce Cost of Goods
		Version: 2.13.0
		Author: SkyVerge

	WPCode Lite
		Version: 2.1.11
		Author: WPCode

	WPO Tweaks &amp; Optimizations
		Version: 1.0.4
		Author: Fernando Tellado

	WP Tweaks
		Version: 2.3.4
		Author: Luiz Bills


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Pages Panel: Inactive by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 312024-03-15 22:14:09 [info] elementor-pro::elementor_pro_updater Started 
2024-03-15 22:14:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-15 22:14:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-15 22:14:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-15 22:14:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-15 22:14:09 [info] elementor::elementor_updater Started 
2024-03-15 22:14:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 22:14:09 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 22:14:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.0',
)]
2024-03-15 22:14:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.0',
)]
2024-03-15 22:14:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-15 22:15:09 [info] elementor::elementor_updater Started 
2024-03-15 22:15:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 22:15:09 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 22:15:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-04-15 13:57:27 [info] elementor::elementor_updater Started 
2024-04-15 13:57:27 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-15 13:57:27 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-15 13:57:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.21.0',
)]
2024-04-15 13:57:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.21.0',
)]

PHP: showing 6 of 6PHP: 2024-02-21 01:58:52 [notice X 104][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::626] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-21 16:28:23 [notice X 3][../wp-content/plugins/elementor/includes/api.php::164] Automatic conversion of false to array is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-21 16:37:40 [warning X 32][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-03-22 22:33:05 [warning X 8][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-15 13:57:27 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/custom-widget-icon-box.min.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-15 13:57:27 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/custom-widget-icon-list.min.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2024-02-22 00:11:46 [error X 24][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:575963] Failed to read a named property &#039;elementorFrontend&#039; from &#039;Window&#039;: Blocked a frame with origin &quot;..&quot; from accessing a cross-origin frame. 
JS: 2024-02-22 00:32:28 [error X 14][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.19.2:2:64496] Cannot convert undefined or null to object 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by betatester07** [comment]
Honestly, I've been waiting for the TTFB optimization for a long time and will test it when I will have more time!

However, few points about your testing:
The "Optimize Control Loading" is supposed to improve TTFB by optimizing the rendering process, effectively making the time PHP runs to render the page HTML output shorter. Therefore, to properly test it, most caching solutions, especially page cache and browser cache (plugins or server config that sets expires headers or similar) should be completely disabled (object cache is probably fine)! Then, TTFB of the main document after making HTTP request to some page should checked and compared. The overall time it takes for the browser to load the whole page (including loading all additional CSS, JS files or images) is also irrelevant when evaluating this new optimization. Therefore, the overall PageSpeed score is also not applicable for testing, because it measures many metrics, not only TTFB.

I'm saying this because from what you wrote, I was not sure whether you have done it in a way I described.

Anyway, from what I understand about this "Optimize Control Loading" and according to my own debugging a profiling Elementor code, the optimization should be more noticeable on complex pages with many many elements and complicated nested structure. If you have Elementor pages that are relatively simple with just few widgets, it probably won't be that noticeable, but that is just my  guess.

**Comment by tobias992** [comment]
As @betatester07 said, try this without caching. This feature doesn't optimise the output of the code (less DOM or anything). It "only" renders the elements faster. So with caching enabled you will not see any improvement in google pagespeed.

I have some large and complex pages and I save more than 50% of the loading time. This new feature is a real step forward for better performance in a long time.

**Comment by jazir555** [comment]
@betatester07 

> Honestly, I've been waiting for the TTFB optimization for a long time and will test it when I will have more time!

> However, few points about your testing: The "Optimize Control Loading" is supposed to improve TTFB by optimizing the rendering process, effectively making the time PHP runs to render the page HTML output shorter. Therefore, to properly test it, most caching solutions, especially page cache and browser cache (plugins or server config that sets expires headers or similar) should be completely disabled (object cache is probably fine)! Then, TTFB of the main document after making HTTP request to some page should checked and compared. The overall time it takes for the browser to load the whole page (including loading all additional CSS, JS files or images) is also irrelevant when evaluating this new optimization. Therefore, the overall PageSpeed score is also not applicable for testing, because it measures many metrics, not only TTFB.
 
> I'm saying this because from what you wrote, I was not sure whether you have done it in a way I described.
 
> Anyway, from what I understand about this "Optimize Control Loading" and according to my own debugging a profiling Elementor code, the optimization should be more noticeable on complex pages with many many elements and complicated nested structure. If you have Elementor pages that are relatively simple with just few widgets, it probably won't be that noticeable, but that is just my guess.

The page I was testing is indeed simple/not complex, perhaps that's why I didn't notice a performance benefit.

I was speed testing the site with Debug Bear and specifically looking at the TTFB metric, it didn't change in any noticeable way, I was just mentioning total load time since TTFB is a component of that and I was attempting to indicate neither TTFB or total load time had improved.

@tobias992 

> It "only" renders the elements faster. So with caching enabled you will not see any improvement in google pagespeed.

Well that would explain it I guess. That's unfortunate in my case, since I was really hoping this would put me over the edge to perfect scores. I've gotten my site (with admittedly simple pages) to score high 90s-100/100 on pagespeed insights mobile metrics(depending on the test, it changes each test), but there is this fluctuating inter-test variance which I was really hoping this update would put to rest so the scores stay consistent.

Speaking of complex sites, would you mind if I shoot you an email if I could potentially try my hand at optimizing one of them? I've been itching to test out my optimization skills on a complex Elementor site and haven't yet had the opportunity.

**Comment by nicholaszein** [comment]
Hello @jazir555!

Thank you for your contribution! 🙏 

Receiving feedback like yours is really important for us to understand our customer's perceived understanding about our performance improvements. You might want to take a look at our Developers Blog, where Rami [explains in more detail](https://developers.elementor.com/elementor-3-21-developers-update/#:~:text=query%20post%20types.-,Performance%20Improvements,-Elementor%20engineers%20are) what exactly this new feature does, and how it will impact on your site's performance.

As @betatester07, and @tobias992 correctly pointed out, these changes impact TTFB. Although we are also improving the DOM output of a few elements based on the content they have. You should really take a look at the article.

This isn't really a bug, therefore, I'm closing this issue. I hope you can understand.

Kind regards
