### ISSUE TITLE
❌ Continuous annoying "Elementor AI" popups and upsells

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#25792]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Keep getting popups and upsells to Elementor AI, can't seem to find a way to turn these off. They are obnoxious, unnecessary, not a feature we value, and confuses our clients. PLEASE, give us an option to disable these and AI in general! You're driving loyal Elementor customers away. 

### Steps to reproduce

Open elementor. See bombardment of AI upsells and popups.the 

### Expected behavior

To not do that or have that behavior...

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.44
	PHP Version: 8.2.18
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: -
	Home URL: -
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Chicago
	Debug Mode: Inactive
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by eraybektascomtr** [comment]
I'm tired of the constant pop-ups that pop up every time I click on a text box and prevent me from typing.

**Comment by reedock** [comment]
+1

**Comment by SolunaCG** [comment]
+1 
I couldn´t agree more! Elementor promoting their "additional cost features" everywhere is extremely annoying and usually reminds me of free software that has to do that in order to "earn" a little bit but it´s definitely a no-go for every kind of paid software/plugin! 
I could MAYBE understand it if it was just shown to "Elementor free" users but definitely NOT to paying "Elementor Pro" users!

**Comment by wpturnedup** [comment]
Agreed. The need to satisfy Elementor's investors is becoming increasingly intrusive with every release.

Please provide a switch that disables AI across a WordPress install, not just on a user/account basis.

**Comment by black-eye** [comment]
+1

**Comment by mocana** [comment]
+100 This last year has been heavy and I'm not the only one now questioning if ELE is the best platform to work with. I see a lot of alternatives are catching up and not becoming bloatware, or creating more revenues for income. There has to be a balance and a reason one buys pro to not be bothered by these new features.

**Comment by mcrowell** [comment]
+1 - Please at least give us an option to disable any upsells.

**Comment by joehdevwp** [comment]
Hey Elementor, we dont want your stupid AI tools or the continuous pop ups that keep reappearing despite a 'dont show again' message that obviously doesn't work.

**Comment by black-eye** [comment]
BTW, there are (at least) 2 Feature request for this in the Discussions:
- https://github.com/orgs/elementor/discussions/22259
- https://github.com/orgs/elementor/discussions/22796

Please add your votes there, if you haven't done already. The developers are more likely to use these in their decission making process. Although, I'm afraid, in this case I don't have much hope they will care.

**Comment by sonnyr007** [comment]
+100 %. Just renewed my elementor agency license last month, but the annoying marketing popups are just out of control. It is now costing more time spend explaining to clients. But since I have many sites, now will start looking at Bricks. Too bad. Elementor has become bloatware in the past year. Please remove this for paid customers especially agency ones that pay a lot.

**Comment by brunovon007** [comment]
> @brunovon007 definitely a good decision! Our company moved to Bricks a few weeks ago and we´ve already created a few websites with Bricks and so far we absolutely love it! As a company that has been using Elementor on more than 50 client websites we were just annoyed by the direction that Elementor has been going over the last time with "Image optimizer" here and "Elementor hosting" there. We don´t need all that cause we have our own solutions for these things that work great! We decided to pay Elementor because we need a good page builder for Wordpress and that´s it! And the pagebuilder definitely lacks a lot of essential features that have been listed by many users on other github threads for a long time, so yea.. Bricks will be our main builder from now on :-)

We got a lifetime agency license for Bricks, couple of months back. Now looking to test a few sites and start talking to clients into migrating. The cost of managing support explaining all the popups/ai/hosting and everything else is now more expensive than the annual license we pay. Does not make any business sense. Not sure why Elementor chose to go this way. It is making the software look like those cheesy commercials which say 'But wait' if you buy it now, you will get 2 free.

**Comment by squadcar** [comment]
Just another +1. This is definitely starting to feel like the enshittification stage of Elementor's life cycle has begun. In addition to what other's have said above, as a freelancer, many of my clients are small businesses with limited budgets. I really don't want to have my own software trying to convince them to replace me. Although, guessing you guys probably do.

**Comment by mocana** [comment]
Exploring Bricks as well. ELE is going off the rails anymore when it comes to their business model with this software. Incredibly bloated and I'm interested in starting over with a lighter solution.

**Comment by marowi85** [comment]
+1

These pop-ups are so annoying. Also these for the image optimization plugin, even if you already have another one installed. Elementor, stop spamming the backend!

**Comment by nicholaszein** [comment]
Hello there,

Thank you everyone for voicing your concerns and frustrations! 🙏 

However...

# ⛔ This is not a bug. 

This is a feature of Elementor that is running as expected. We understand you might not like it, and you might be frustrated with it, but it's still not a bug in the software, and does not break any functionality.

Please, respect our [Contribution Guidelines](https://elemn.to/gh-contributing) and file your requests for new features in the correct locations.

It's ok to request an option to disable these notices, but it should be done in the right place. Creating Bug Reports for something that is not broken, and duplicating issues and discussions for the same request won't make us solve it faster. In fact it will produce the exact opposite effect. It will require from us more time to gather data, evaluate all the community sentiment scattered across multiple tickets, count all the comments and reactions on all different places, and recreate individual reports for each one of them. This will require a lot of unnecessary (re)work and time. Something that could be used to actually implement the features and fix the bugs you request and report.

Please, save time by searching for a similar request in the right place **<ins>before submitting a new one</ins>.** It's on YOUR interest and benefit to follow the guidelines defined in the [Contribution Guidelines](https://elemn.to/gh-contributing), [Code of Conduct](https://elemn.to/gh-code-of-conduct), [Bug Report Form](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml), and [Feature Request Form](https://elemn.to/gh-new-feature-request). By ignoring those rules you're just adding more time to actually add the features you request (including this one).

If you think this should be an Elementor feature, please cast your ⬆️ **Upvote** in #22796 and we will consider it in the future if there is enough demand (votes) from other users.

## Thank you for your collaboration with these Guidelines! 🙏 

_A word of advice, and a warning: **Offensive** or **Disrespectful** remarks, or any behavior that does not align with the [Code of Conduct](https://elemn.to/gh-code-of-conduct) will grant the author a block from contributing or participating in this repository. Please, be respectful. Keep the conversation amicable and civilized. I have no pleasure in having to block users. I am a user myself. But I will do if I see any comment breaking the Code of Conduct._

Kind regards
