### ISSUE TITLE
🐞 Superfluous commas in PHP and WordPress version validations in `elementor.php` cause Cron Jobs to fail in some edge cases - [ED-14686]

### ISSUE THREAD

**Issue by MartinW2** [elementor/elementor#25803]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Came here from https://wordpress.org/support/topic/superfluous-commas-in-elementor-php-causing-cron-jobs-to-fail/

`elementor.php` contains superfluous commas within `sprintf` commands in line `85` and `109`, after minimum PHP and WordPress versions to check:
e.g.: ‘7.4’`,`
These commas are not required, as no further parameters are following nor required.
Usually, this should not be a problem, as normal PHP syntax check does not seem to throw an error due to this.
However, for some reason I could not find so far, several different cron jobs (E-mail check and BackWPup) are failing because of this. Maybe there is a more intense check on batch job PHP syntax... ?
**Anyway, if the superfluous commas in `elementor.php` are removed, then all cron jobs are working as expected.** 
Here is an example of the error message:
```php
Returncode:255;
Array ( [0] => PHP Parse error: syntax error, unexpected ‘)’ in [[…]/wp-content/plugins/elementor/elementor.php](http://hd-4d.de/wp-content/plugins/elementor/elementor.php) on line 86 [1] => [2] => Parse error: syntax error, unexpected ‘)’ in […][/wp-content/plugins/elementor/elementor.php](http://hd-4d.de/wp-content/plugins/elementor/elementor.php) on line 86 )
```

Would be great to know why – but even more important: could you please remove these commas in next version of Elementor to prevent this? Thank you!

### Steps to reproduce

I assume it's hard to reproduce on another system with possibly different PHP settings or requirements, but since the commas in fact do not seem to be at the right place, please consider to remove them anyway.

### Expected behavior

No syntax error due to unnecessary commas in `elementor.php`.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 22.04 v10.6.16
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: https://hd-4d.de
	Home URL: https://hd-4d.de
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de_DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Zix Child
	Version: 1.0.12
	Author: Martin Walla
	Child Theme: Yes
	Parent Theme Name: Zix
	Parent Theme Version: 1.1.2
	Parent Theme Author: DroitThemes

== User ==
	Role: administrator
	WP Profile lang: de-DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.2.9
		Author: WP Engine

	Advanced Custom Fields: Font Awesome
		Version: 4.0.6
		Author: Matt Keys

	Allow Webp Image
		Version: 1.0.1
		Author: Top Infosoft

	BackWPup
		Version: 4.0.4
		Author: WP MEDIA SAS

	Canvasio3D Light
		Version: 2.5.0
		Author: Thomas Scholl

	Complianz | GDPR/CCPA Cookie Consent
		Version: 7.0.4
		Author: Really Simple Plugins

	Contact Form 7
		Version: 5.9.3
		Author: Takayuki Miyoshi

	Disable Comments
		Version: 2.4.6
		Author: WPDeveloper

	Elementor
		Version: 3.21.1
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	EWWW Image Optimizer
		Version: 7.5.0
		Author: Exactly WWW

	Extendify
		Version: 1.13.2
		Author: Extendify

	HD-4D-Helper
		Version: 1.0
		Author: Martin Walla (HD-4D.de)

	Health Check & Troubleshooting
		Version: 1.7.0
		Author: The WordPress.org community

	iQ Block Country
		Version: 1.2.21
		Author: Pascal

	Ivory Search
		Version: 5.5.6
		Author: Ivory Search

	MailPoet
		Version: 4.48.2
		Author: MailPoet

	Maintenance
		Version: 4.08
		Author: WebFactory Ltd

	OMGF
		Version: 5.9.0
		Author: Daan from Daan.dev

	Redux Framework
		Version: 4.4.15
		Author: Team Redux

	SEPA Girocode
		Version: 0.5.1
		Author: Michael Hallmann

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.43
		Author: Sucuri Inc.

	Vrm360
		Version: 1.2.1
		Author: Maurice

	Wordfence Security
		Version: 7.11.5
		Author: Wordfence

	WP-ServerInfo
		Version: 1.66
		Author: Lester 'GaMerZ' Chan

	WP Crontrol
		Version: 1.16.3
		Author: John Blackbourn

	WP Fastest Cache
		Version: 1.2.5
		Author: Emre Vona

	WP Photo Sphere
		Version: 3.8
		Author: Jérémy Heleine

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 22.5
		Author: Team Yoast

	Yoast Test Helper
		Version: 1.18
		Author: Team Yoast

	Zix Core
		Version: 1.0.10
		Author: DroitThemes


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.1
		Author: 


== Elementor-Experimente ==
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig deaktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Additional Custom Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Grid Container: Standardmäßig aktiviert
	Nested Elements Performance: Standardmäßig deaktiviert
	Optimized Control Loading: Standardmäßig deaktiviert
	Elementor Home Screen: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Build with AI: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Hintergrundbilder nachladen: Standardmäßig deaktiviert


== Protokoll ==
	
Log: showing 20 of 412024-03-26 20:02:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-03-26 20:02:50 [info] elementor::elementor_updater Started 
2024-03-26 20:02:50 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-26 20:02:50 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-26 20:02:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-04-10 21:06:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-10 21:06:31 [info] elementor::elementor_updater Started 
2024-04-10 21:06:31 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-10 21:06:31 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-10 21:06:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-10 21:06:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-16 00:16:03 [info] elementor::elementor_updater Started 
2024-04-16 00:16:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-16 00:16:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-16 00:16:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.4',
  'to' => '3.21.0',
)]
2024-04-18 21:09:13 [info] elementor::elementor_updater Started 
2024-04-18 21:09:13 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-18 21:09:13 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-18 21:09:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-18 21:09:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]

JS: showing 1 of 1JS: 2024-02-02 17:49:34 [error X 3][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.19.0:3:16087] Cannot read properties of undefined (reading 'global') 



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by m1ga** [comment]
Hi @MartinW2 just a quick note here: the part you are showing is only triggered when you have an outdated PHP version. Keep in mind:
> In 2024, Elementor will cease support for PHP 7.x versions entirely, elevating the minimum required version to PHP 8.0-8.3, based on the available usage data.
([source](https://developers.elementor.com/elementors-roadmap-to-upgrade-php-versions/)).

You are still using 7.4 which reached EoL in Dec 2023. So the quickest solution would be updating to a recommended PHP version. Should be an option in the all-inkl backend.

**Comment by MartinW2** [comment]
Hi @m1ga , thank you for the friendly reminder - I was not aware that PHP 7.4 is already EoL.
I have upgraded now to 8.3 - however, the error remains, if commas are put back in place.
I know this code is only relevant for version checking - but since it's a syntax error it will probably pop up no matter if the specific lines are executed or not.
So I had to remove commas again to make it work. I don't understand why they are having them at this place anyway?
Let's see if I get another reply.

**Comment by m1ga** [comment]
Yeah, lets check what they say. Normally `'7.4'` should be correct

https://github.com/elementor/elementor/blob/0da96c9a46434228113b464d91d9114b16508356/elementor.php#L82-L86

as they use %s in the sprintf command so it wants to replace it with a string.

**Comment by octopush** [comment]
I'm experiencing the same problem. My php version is 8, and this coma:
`'7.4',`
before the closing parenthesis generates the error : 
`[24-Apr-2024 19:55:28 UTC] PHP Parse error:  syntax error, unexpected ')' in /*******/*******/wp-content/plugins/elementor/elementor.php on line 86`
When i remove the coma, the code is ok, and it looks like this : 
` sprintf( 
 	/* translators: %s: PHP version. */ 
 	esc_html__( 'Update to version %s and get back to creating!', 'elementor' ), 
 	'7.4'
 ), `

could you please remove this useless coma in next version ?

**Comment by MartinW2** [comment]
I investigated a bit more, and I found the reason why this only appears during cron jobs for me:
My cron involves an exec command, which was not bound to a specific PHP version. The cron then used PHP 7.2 (!)
PHP 7.2 CLI throws a syntax error for `sprintf("%s","abc",)` , while PHP 8.3 does not.

Conclusion: 
(1) Check your PHP version used during cron, it might differ from the usual version
(2) Still the commas are not necessary at this place, so removing them in next version may be a good idea.

**Comment by nicholaszein** [comment]
Hello @MartinW2! 

Thank you for submitting your issue! 🙏 

We are aware of this issue, and it seems to be related, as you already found out, to the usage of unsupported PHP versions in your Cron Jobs. However, we do see how unnecessary these commas are, and we will take a look at it and remove them if we see fit.

We also still do not support PHP v8.3 (not even WordPress does yet), and we recommend you stick with PHP 7.4, 8.0 or 8.1 for now. We are working on adding full support to all PHP 8.X versions, but we still don't have an ETA on when it will be fully supported.

Best regards
