### ISSUE TITLE
❌ Invalid Issue

### ISSUE THREAD

**Issue by myedgy** [elementor/elementor#25813]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Elementor Version 3.20.4 
Elementor Pro Version 3.21.0

Both are installed and activated.

### Steps to reproduce

Elementor Version 3.20.4 
Elementor Pro Version 3.21.0

Both are installed and activated.

### Expected behavior

that you can close or remove the message "Don’t miss out on the new version of Elementor" is back on Dashboard

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
company info
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
This issue doesn't follow our [Contribution Guidelines](https://elemn.to/gh-contributing) or our [Bug Report Form](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml) requirements.

We cannot continue with the validation without the proper and required information.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Kind regards
