### ISSUE TITLE
🔗 🚀 Feature Request: Responsive control for background overlays for "split section effect" (Related to #2097, #2355, #2729)

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#2600]
I would like to create the following effect with background overlays. (I think you also feature this technique in a few of your templates). The problem is, since I can't adjust the background overlay on tablet or mobile, the effect becomes unusable since you can't read the text. The dark text on the left won't be readable on top of the dark image on the right for both tablet and mobile. It's such an awesome Elementor feature, but one that simply can't be used because it doesn't work on table or mobile.

![background-overlay-divider](https://user-images.githubusercontent.com/29379115/31678413-bb3c9bec-b333-11e7-9af3-c1c34b3d5052.png)

**Comment by bainternet** [comment]
ref:
#2355
#2097 
#2729 

closing as already requested.

@avermat thanks for your suggestions.
