### ISSUE TITLE
WMPL doesn't recognized as RTL because redirect of elementor

### ISSUE THREAD

**Issue by dquak** [elementor/elementor#2652]
Hi, using latest Elementor version 1.7.11 and Elementor Pro 1.9.3,
I'm facing a problem with identify the page as an RTL page when combined with WMPL,
The WMPL configured to put the language of the page as part of the url, eg: "**www.myurl.com/ar/my-page**",
As older elementor version used to put a query of "?elementor" at the end of the url to go into the edit mode, The new version is redirect to the "post.php" edit url, which doesn't include the "/ar/" suffix (eg: "**www.myurl.com/wp-admin/post.php?post=45&action=elementor**").

Any help? 
Thank, 
Itay.

**Comment by amig** [comment]
I have the same problem. 

Fix was found by selecting "Set admin language as editing language." in "User Profile" -> "WPML language settings".

![screenshot-yestrading com-2017-12-17-16-16-46-592](https://user-images.githubusercontent.com/203434/34080411-2cba0f88-e346-11e7-895b-b9ad6a245a36.png)

I would still love to have Elementor interface be RTL even if I don't set this option to keem all admin pages in English.

**Comment by arielk** [comment]
I merged this issue with another issue #5148 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
