### ISSUE TITLE
❌ Invalid Issue

### ISSUE THREAD

**Issue by Paradinight** [elementor/elementor#27251]
The user didn't follow the correct [Contribution Guidelines](https://elemn.to/gh-contributing).

**Comment by nicholaszein** [comment]
Hello @Paradinight.

Please don't use GitHub to submit anything else than Bug Reports.

For security reasons, and for a responsible coordinated disclosure, follow our [Security Policy](https://github.com/elementor/elementor/security/policy) to submit your findings in the correct place.

### ⚠️ As a gentle reminder, issues that do not follow our 🐞 Bug Report Guidelines may need to be closed without troubleshooting. 

Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏
