### ISSUE TITLE
⛔ Elementor not compatible with Arc browser for Windows

### ISSUE THREAD

**Issue by killian-santos** [elementor/elementor#27284]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello, Elementor does not work with the Arc browser for Windows. When using it, it is impossible to use drag-and-drop.
This browser is based on Chromium. How can I explain this? Where does it come from?

### Steps to reproduce

Drag and drop a widget

### Expected behavior

The widget should drag and drop instead, a red crossed-out circle appears

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.17
	PHP Version: 8.1.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 250000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.3
	Site URL: https://vitedeswc.fr
	Home URL: https://vitedeswc.fr
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr_FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr-FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.4.6
		Author: WP Engine

	Code Snippets
		Version: 3.6.4
		Author: Code Snippets Pro

	Crocoblock Wizard
		Version: 1.2.10
		Author: Crocoblock

	Elementor
		Version: 3.21.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.2
		Author: Elementor.com

	JetEngine
		Version: 3.4.4
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.2
		Author: Crocoblock

	JetEngine - dynamic tables builder
		Version: 1.0.10
		Author: Crocoblock

	JetFormBuilder
		Version: 3.3.3
		Author: Crocoblock

	JetSmartFilters
		Version: 3.4.5
		Author: Crocoblock

	JetTricks
		Version: 1.4.9
		Author: Crocoblock

	MainWP Child
		Version: 5.0.1.1
		Author: MainWP

	PWA
		Version: 0.8.1
		Author: PWA Plugin Contributors

	Query Monitor
		Version: 3.16.2
		Author: John Blackbourn

	SEOPress
		Version: 7.7.1
		Author: The SEO Guys at SEOPress

	SEOPress PRO
		Version: 7.7
		Author: The SEO Guys at SEOPress

	Solid Security Basic
		Version: 9.3.2
		Author: SolidWP

	Temporary Login Without Password
		Version: 1.8.3
		Author: StoreApps

	WP All Export Pro
		Version: 1.8.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.8.7
		Author: Soflyy

	WPvivid Backup Plugin
		Version: 0.9.101
		Author: WPvivid Team

	WPvivid Plugins Pro
		Version: 2.2.24
		Author: wpvivid.com


== Fonctionnalités ==
	Custom Fonts: 0
	Custom Icons: 0

== Intégrations ==
	


== Expériences d’Elementor ==
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Polices d’icônes « inline »: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif par défaut
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Conteneur grille: Actif par défaut
	Nested Elements Performance: Inactif par défaut
	Optimized Control Loading: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	En-tête et pied de page du thème Hello: Actif par défaut
	Écran d’accueil Elementor: Actif par défaut
	Barre supérieure de l’éditeur: Actif
	Construire avec l’IA: Inactif
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Panneau des pages: Inactif par défaut
	Conditions d’affichage: Inactif par défaut
	Envois de formulaire: Actif par défaut
	Menu: Inactif par défaut
	Filtre de taxonomie: Inactif par défaut


== Journal ==
	
Log: showing 20 of 362024-04-29 08:27:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.21.3',
)]
2024-04-29 08:27:26 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.21.1',
)]
2024-04-29 08:27:26 [info] elementor-pro::elementor_pro_updater Started 
2024-04-29 08:27:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-29 08:27:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-29 08:27:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.21.1',
)]
2024-05-02 09:44:34 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]
2024-05-02 09:44:34 [info] elementor::elementor_updater Started 
2024-05-02 09:44:34 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-02 09:44:34 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-02 09:44:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]
2024-05-02 09:44:57 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.1',
  'to' => '3.21.2',
)]
2024-05-02 09:44:57 [info] elementor-pro::elementor_pro_updater Started 
2024-05-02 09:44:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-05-02 09:44:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-05-02 09:44:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.1',
  'to' => '3.21.2',
)]
2024-05-08 23:17:56 [info] elementor::elementor_updater Started 
2024-05-08 23:17:56 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-08 23:17:56 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-08 23:17:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.4',
  'to' => '3.21.5',
)]

JS: showing 5 of 5JS: 2024-04-05 21:26:54 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4514") has already been destroyed and cannot be used. 
JS: 2024-04-05 21:27:01 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view6031") has already been destroyed and cannot be used. 
JS: 2024-04-05 21:39:13 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view7881") has already been destroyed and cannot be used. 
JS: 2024-05-04 17:19:09 [error X 3][../wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.5.2:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-05-08 22:23:22 [error X 1][../wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.17:12:0]  

PHP: showing 1 of 1PHP: 2024-05-09 09:25:24 [warning X 8][../wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::271] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
That's definitely not true. You need to check your browser or the scripts and other plugins you're using. Elementor works very well in Arc.

**Comment by killian-santos** [comment]
@nicholaszein : Did you read that right: Arc for Windows? I can't get Elementor to work on the Windows version. I tried disabling all the extensions. I've been looking for a solution ever since Arc was released on Windows...

**Comment by killian-santos** [comment]
> That's definitely not true. You need to check your browser or the scripts and other plugins you're using. Elementor works very well in Arc.

@nicholaszein : Did you read that right: Arc for Windows? I can't get Elementor to work on the Windows version (not macOS). I tried disabling all the extensions. I've been looking for a solution ever since Arc was released on Windows...

**Comment by nicholaszein** [comment]
I use Arc for Windows. No problem there.

**Comment by jfranger** [comment]
I have the same exact issue. Been using Elementor for ages and I use it daily a lot. I was planning on moving all my web work operations in Arc from Chrome. I was in the middle of the transfer and boom. A simple drag'n'drop is putting an hold on this. Who knew. Hopefuly not for too long because after only 12 hours I'm very convinced Chrome is a dinosaur.

**Comment by killian-santos** [comment]
> I have the same exact issue. Been using Elementor for ages and I use it daily a lot. I was planning on moving all my web work operations in Arc from Chrome. I was in the middle of the transfer and boom. A simple drag'n'drop is putting an hold on the project. Who knew. Hopefuly not for too long because after only 12 hours of using Arc, I'm very convinced Chrome is a dinosaur.
> 
> ![Capture d’écran 2024-05-13 181507](https://private-user-images.githubusercontent.com/2447914/330218628-09435f36-036d-4248-8e98-1fcbcb7ba7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODE5NTAsIm5iZiI6MTcxNTY4MTY1MCwicGF0aCI6Ii8yNDQ3OTE0LzMzMDIxODYyOC0wOTQzNWYzNi0wMzZkLTQyNDgtOGU5OC0xZmNiY2I3YmE3YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTAxNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBmNDc5MDBmMWJlMzg0ZjQ4YWQ4ZTM2NDgyYjA1OGU3ZDM3ZjZhODZmMjVmNDMzZDUzNmYyNjRiNzkzYWU0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4SxDpmlVkGrtf1vHZPW4C_MRjjh462E6rvxGukSYNMU)

It's very frustrating, I spent hours searching... (I also wrote to Arc) I was in the same situation, ready to switch to Arc. For the moment, I've settled on Opera. Arc may still be a bit too new and the Android app is missing. In any case, I'll probably be ready to try again when this bug is fixed. Still, I'm glad to see I'm not the only one.

**Comment by raultinelli** [comment]
I have the same problem, I can't drag elements to pages. I've already deleted browser extensions, updated all plugins used, tested with other domains and nothing.

I really liked the Arc browser, but this bug made me go back to Chrome

**Comment by jfranger** [comment]
I just opened a ticket with Elementor. May the force be with them.

**Comment by ibrahimkamay** [comment]
Is there any news? I just opened a ticket to Arc but there was no return.

**Comment by nicholaszein** [comment]
Hello everyone,

we investigated this issue further, and we concluded this is not an issue caused by Elementor. It's likely a conflict with a browser extension, outdated version, or a plugin or theme on your installation.

To confirm this is not a problem both on MacOS and Windows, please refer to the following video below (Windows), and these two YouTubers, who use the Arc Browser on MacOS and have no problem while editing with Elementor:

https://www.youtube.com/@LytboxStudio
https://www.youtube.com/@andreaegli


https://github.com/user-attachments/assets/e0ad916d-5d38-4ca3-9dff-7f4c2cf203c7

Please, check your browser extensions, plugins, and theme.
