### ISSUE TITLE
❌ 🔗 Google Tag Manager Form submission trigger is not fired when using Google reCAPTCHA V3 (Duplicate of #11878)

### ISSUE THREAD

**Issue by Skarema** [elementor/elementor#27330]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

This issue still hasn't been fixed:
https://github.com/elementor/elementor/issues/11878

### Steps to reproduce

https://github.com/elementor/elementor/issues/11878

### Expected behavior

https://github.com/elementor/elementor/issues/11878

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
https://github.com/elementor/elementor/issues/11878
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
@Skarema...

### ⚠️ As a gentle reminder, issues that do not follow our 🐞 Bug Report Guidelines may need to be closed without troubleshooting. 

Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏
