### ISSUE TITLE
Optimized Control Loading bug - menu cart element

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#27342]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi elementor team,

If you enable the Optimized Control Loading option in the settings, the "close" icon in the menu cart element will change to the default icon and will no longer display the SVG icon.

![1](https://github.com/elementor/elementor/assets/77163248/215e6732-7e25-4b7e-b8ab-f97bd2324bcd)

### Steps to reproduce

1- Make sure the Optimized Control Loading option is enabled.
2- Choose an SVG icon for the close button of the menu cart element.
3- Check out the frontend. The svg icon is not displayed.
4- If you disable the Optimized Control Loading option, the problem will be solved.

### Expected behavior

-

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.3
	Site URL: https://domain.com
	Home URL: https://domain.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Asia/Tehran
	Admin Email: hosein.site@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.21.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.2
		Author: Elementor.com

	WooCommerce
		Version: 8.9.0
		Author: Automattic

== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Grid Container: Active
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Pages Panel: Inactive by default
	Display Conditions: Active
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Inactive

== Log ==
	
Log: showing 20 of 412024-04-19 20:45:07 [info] elementor::elementor_updater Started 
2024-04-19 20:45:07 [info] elementor/Upgrades - _on_each_version Start  
2024-04-19 20:45:07 [info] elementor/Upgrades - _on_each_version Finished 
2024-04-19 20:45:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-19 20:45:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-25 23:00:59 [info] elementor::elementor_updater Started 
2024-04-25 23:00:59 [info] elementor/Upgrades - _on_each_version Start  
2024-04-25 23:00:59 [info] elementor/Upgrades - _on_each_version Finished 
2024-04-25 23:00:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.21.1',
  'to' => '3.21.3',
)]
2024-05-10 02:11:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.21.3',
  'to' => '3.21.5',
)]
2024-05-10 02:11:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor pro',
  'from' => '3.21.0',
  'to' => '3.21.2',
)]
2024-05-10 02:11:24 [info] elementor-pro::elementor_pro_updater Started 
2024-05-10 02:11:24 [info] elementor pro/Upgrades - _on_each_version Start  
2024-05-10 02:11:24 [info] elementor pro/Upgrades - _on_each_version Finished 
2024-05-10 02:11:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor pro',
  'from' => '3.21.0',
  'to' => '3.21.2',
)]
2024-05-10 02:11:24 [info] elementor::elementor_updater Started 
2024-05-10 02:11:24 [info] elementor/Upgrades - _on_each_version Start  
2024-05-10 02:11:24 [info] elementor/Upgrades - _on_each_version Finished 
2024-05-10 02:11:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'elementor',
  'from' => '3.21.3',
  'to' => '3.21.5',
)]
2024-05-10 02:11:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'elementor',
  'from' => '3.21.3',
  'to' => '3.21.5',
)]

JS: showing 1 of 1JS: 2024-04-15 11:39:26 [error X 1][https://domain.com/wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.4:3:7564] ReactUtils is not defined 

PHP: showing 1 of 1PHP: 2024-04-18 01:55:03 [error X 1][/home2/gerozair/domains/https://domain.com/public_html/wp-content/plugins/elementor/modules/home/transformations/filter-plugins.php::30] Uncaught TypeError: Argument 1 passed to Elementor\Modules\Home\Transformations\Filter_Plugins::get_add_ons_installation_status() must be of the type array, null given, called in /home2/gerozair/domains/https://domain.com/public_html/wp-content/plugins/elementor/modules/home/transformations/filter-plugins.php on line 21 and defined in /home2/gerozair/domains/https://domain.com/public_html/wp-content/plugins/elementor/modules/home/transformations/filter-plugins.php:30
Stack trace:
#0 /home2/gerozair/domains/https://domain.com/public_html/wp-content/plugins/elementor/modules/home/transformations/filter-plugins.php(21): Elementor\Modules\Home\Transformations\Filter_Plugins->get_add_ons_installation_status(NULL)
#1 /home2/gerozair/domains/https://domain.com/public_html/wp-content/plugins/elementor/modules/home/classes/transformations-manager.php(47): Elementor\Modules\Home\Transformations\Filter_Plugins->transform(Array)
#2 /home2/gerozair/domains/https://domain.com/public_html/wp-content/plugins/elementor/modules/home/api.php(24): Eleme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==	

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by KingYes** [comment]
It will be fixed in the next Pro release; thanks!

**Comment by 79ho3ein** [comment]
Nice! thank you @KingYes

**Comment by nicholaszein** [comment]
Hey @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.22.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
