### ISSUE TITLE
🚧 Posts are redirected to Pages with the same slug when the Permalink structure is /%category%/%postname%/

### ISSUE THREAD

**Issue by dimalepel** [elementor/elementor#27390]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When the Elementor plugin is enabled, an uncontrolled redirection occurs from article /category_name/post_slug to page /page_slug, where post_slug = page_slug. Example, https://top10usenet.com/usenet-providers/tweaknews-review/ -> https://top10usenet.com/tweaknews-review/.

### Steps to reproduce

To reproduce the problem you can do the following steps:
1. Install a new clean version of WP;
2. Create a category with any name;
3. Create an article and add it to the created category;
4. Create a new page with the same name and be sure to slug like the created article;
5. Set up a link structure like this /%category%/%postname%/;
6. Install the Elementor plugin from the WP repository and activate;
When you follow link /category_name/post_slug, you will definitely be redirected to page /page_slug, although you do not have redirect plugins. But if you disable Elementor and follow link /category_name/post_slug, the redirect will not occur.

https://github.com/elementor/elementor/assets/10213719/c46d3910-b2fd-4a56-bf40-d25e876f95f9

### Expected behavior

There should be no redirect when Elementor is enabled

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
Operating System: WINNT
Software: Apache
MySQL version: MySQL Community Server (GPL) v5.7.39
PHP Version: 7.4.30
PHP Memory Limit: 1536M
PHP Max Input Vars: 1000
PHP Max Post Size: 50M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.5.3
Site URL: http://wp-test
Home URL: http://wp-test
WP Multisite: No
Max Upload Size: 50 MB
Memory limit: 40M
Max Memory limit: 1536M
Permalink Structure: /%category%/%postname%/
Language: ru_RU
Timezone: 3
Debug Mode: Inactive

== Theme ==
Name: Hello Elementor
Version: 3.0.1
Author: Elementor Team
Child Theme: No

== User ==
Role: administrator
WP Profile lang: ru-RU
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0

== Active Plugins ==
Elementor
Version: 3.21.5
Author: Elementor.com


== Elementor Experiments ==
Improved resource loading: Active by default
Improved CSS loading: Active by default
Built-in font icons: Active by default
Additional custom breakpoints: Active by default
admin_menu_rearrangement: Inactive by default
Flex container: Active by default
Swiper Library Update: Active by Default
Grid Container: Active by default
Nested Elements Performance: Inactive by default
Optimized Control Loading: Inactive by default
Hello theme header and footer: Active by default
Elementor Home Screen: Active by default
Editor Top Bar: Inactive by default
Build with AI: Active by default
Landing Pages: Active by default
Nested Elements: Inactive by default
Lazy loading of background images: Enabled by default


== Magazine ==



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @dimalepel!

Thank you for submitting your issue, and apologies for the delay! 🙏 

Can you please try to deactivate the Landing Page experimental feature and see if the problem goes away? Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page, and set the **`Landing Pages`** experimental feature to **`Inactive`** and click to **`Save Changes`** at the bottom of the page.

Next go to your WordPress **`Dashboard`** > **`Settings`** > **`Permalinks`** page, set the custom structure to **`/%category%/%postname%/`**, and click to **`Save Changes`** at the bottom of the page.

To ensure all permalink transients are updated, click to **`Save Changes`** in the **`Permalinks`** page at least twice, even if the structure is already set.

Let me know if after following the steps above the problem goes away.

Kind regards

**Comment by nicholaszein** [comment]
Hi @dimalepel!

That's great news! Did you follow the instructions, or it simply started working as expected again?

**Comment by nicholaszein** [comment]
Hello @dimalepel,

since I've not heard back from you, I'll assume this was a problem specific to your site. If you encounter this problem in the future and can confirm this is caused by Elementor after troubleshooting it, feel free to open a new issue.

I'm closing the comments on this issue.

Best regards
