### ISSUE TITLE
⛔ 🛟 Support Request: I can't change the image size

### ISSUE THREAD

**Issue by gauthierbuttez** [elementor/elementor#27575]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

**ENVIRONMENT:**
WordPress 6.5.3

Elementor Version 3.21.8

I want to make a sale page with Elementor. I use a simple free Elementor template. I selected the template "Canva Elementor" in the settings of the page (see screenshot)

**PROBLEM:**

My webp image keeps always the same size whatever size I choose:
[![enter image description here][2]][2]

**WHAT DID I DO?**

I inspected the code and I can see this element class for the image is width:100%

[![enter image description here][3]][3]

I don't understand, so I checked my custom CSS in my "Personalize theme" page :

    .site-title{display:none;}
    .elementor-224 {
        max-width: 100%!important;
    }
    .style-two .header-bottom {
        padding-top: 0px;
        padding-bottom: 0px;
    }
    .main-navigation ul li {
    	font-size: 1em!important;}
    .header-social ul li {
        font-size: 1em!important;
    }
    .footer-t {
        
        padding-top: 30px!important;
        padding-bottom: 30px!important;
        padding-left: 30px!important;
        padding-right: 30px!important;
    }
    .widget {
        margin: 0 0 10px 0!important;
    }
    .footer-b{display:none;}
    
    .wpcf7-form-control.wpcf7-text{
    	width:300px!important;
    	font-size:1.1em!important;
    }
    
    .inline_textfield{
    	display:inline-block;
    	    margin-left: 5px;
        margin-right: 5px;
    }
    
    .post-thumbnail .svg-holder {
        width: 150px; /* Adjust the width as needed */
        height: 150px; /* Adjust the height as needed */
    }
    .post-thumbnail .fallback-svg {
        width: 100%; /* Ensure the SVG scales properly */
        height: 100%; /* Ensure the SVG scales properly */
    }

I don't see anything wrong. So I cleared the cache and tried with different browsers (Firefox, IE, Chrome). There is still the same issue. The image doesn't want to change.
So I switch to the Twenties theme, and I get the same issue.
So I updated Elementor, but I still have the same issue.
So I deactivated all the plugins except Elementor, and I still have the same issue.
So I switched my Webp image with a PNG, and I still have the same issue.

For all these reasons, I think ELementor is bugging or I didn't see something in my parameters.

### Steps to reproduce

1. Create a blank page with Elementor
2. Select the template "Elementor canvas" in the settings of the page
3. Insert an image
4. Change the size
5. Save the page and preview
6. The size image is not correct whatever size I select

### Expected behavior

1. Create a blank page with Elementor
2. Select the template "Elementor canvas" in the settings of the page
3. Insert an image
4. Change the size
5. Save the page and preview
6. The image size is corresponding to what I configured in the ELementor Edition page.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 18.04 v5.6.46-86.2
	PHP Version: 8.1.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.3
	Site URL: https://gauthierbuttez.com
	Home URL: https://gauthierbuttez.com
	WP Multisite: No
	Max Upload Size: 64 Mo
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: fr_FR
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Fashionable Lite
	Version: 1.0.0
	Author: Blossom Themes
	Child Theme: Yes
	Parent Theme Name: Vilva
	Parent Theme Version: 1.2.4
	Parent Theme Author: Blossom Themes

== User ==
	Role: administrator
	WP Profile lang: fr-FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.9.5
		Author: Takayuki Miyoshi

	Contact Form 7 Connector
		Version: 1.2.6
		Author: ARI Soft

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.21.8
		Author: Elementor.com

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	GTranslate
		Version: 3.0.6
		Author: Translate AI Multilingual Solutions

	Head, Footer and Post Injections
		Version: 3.2.8
		Author: Stefano Lissa

	LearnPress
		Version: 4.2.6.8
		Author: ThimPress

	LearnPress - Coming Soon Courses
		Version: 4.0.6
		Author: ThimPress

	LearnPress - Course Review
		Version: 4.1.2
		Author: ThimPress

	LearnPress - Course Wishlist
		Version: 4.0.7
		Author: ThimPress

	LearnPress - WooCommerce Payment Methods Integration
		Version: 4.1.4
		Author: ThimPress

	MailerLite - Signup forms (official)
		Version: 1.7.10
		Author: MailerLite

	MailerLite - WooCommerce integration
		Version: 2.1.12
		Author: MailerLite

	reCaptcha by BestWebSoft
		Version: 1.75
		Author: BestWebSoft

	ReCaptcha v2 for Contact Form 7
		Version: 1.4.7
		Author: IQComputing

	Ultimate Addons for Contact Form 7
		Version: 3.3.12
		Author: Themefic

	WooCommerce
		Version: 8.9.1
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 8.3.1
		Author: WooCommerce

	WP Google Review Slider
		Version: 14.1
		Author: LJ Apps

	WP Mail SMTP
		Version: 4.0.1
		Author: WP Mail SMTP

	Yoast SEO
		Version: 22.8
		Author: Team Yoast


== Utilisation des éléments ==
	
	page : 3
		button : 8
		heading : 24
		icon : 1
		icon-box : 7
		image : 6
		image-gallery : 1
		progress : 4
		shortcode : 2
		spacer : 6
		testimonial : 1
		text-editor : 4
		video : 1
	section : 7
		button : 6
		heading : 12
		image : 1
		image-gallery : 1
		shortcode : 1
		spacer : 6
		testimonial : 1
		text-editor : 1
	wp-post : 0
		button : 3
		container : 2
		google_maps : 2
		heading : 7
		html : 1
		image : 3
		image-box : 1
		shortcode : 2
		text-editor : 6
		toggle : 1
	wp-page : 9
		button : 4
		container : 44
		heading : 12
		icon-box : 4
		icon-list : 1
		image : 12
		image-box : 4
		shortcode : 1
		social-icons : 4
		testimonial : 3
		text-editor : 10


== Réglages ==
	
	cpt_support: post, page, wpr_templates
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes


== Expériences d’Elementor ==
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Polices d’icônes « inline »: Inactif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Conteneur grille: Actif par défaut
	Nested Elements Performance: Inactif par défaut
	Optimized Control Loading: Inactif par défaut
	Écran d’accueil Elementor: Actif par défaut
	Barre supérieure de l’éditeur: Inactif par défaut
	Construire avec l’IA: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut


 == Journal ==
	
Log: showing 20 of 362024-02-27 09:13:21 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2024-02-27 09:13:21 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2024-02-27 09:13:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.19.2',
)]
2024-03-24 18:05:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.2',
)]
2024-03-24 18:05:18 [info] elementor::elementor_updater Started 
2024-03-24 18:05:18 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-24 18:05:18 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-24 18:05:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.2',
)]
2024-03-24 18:05:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.20.2',
)]
2024-06-03 09:31:31 [info] elementor::elementor_updater Started 
2024-06-03 09:31:31 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-03 09:31:32 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-03 09:31:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.2',
  'to' => '3.21.8',
)]

JS: showing 6 of 6JS: 2022-12-09 10:19:05 [error X 7][../wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51816] a is undefined 
JS: 2022-12-09 10:52:17 [error X 6][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0:3:775685] this.store.find(...) is undefined 
JS: 2022-12-09 11:15:49 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0:3:301949] C.ui.form is undefined 
JS: 2024-02-17 19:07:11 [error X 1][../wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:31703] elementor_new_template_form_controls is not defined 
JS: 2024-02-18 09:27:32 [error X 6672][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2024-02-18 09:27:33 [error X 150][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 

PHP: showing 1 of 1PHP: 2024-02-18 10:04:11 [warning X 1][../wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key &quot;url&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @gauthierbuttez,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

Your issue could be solved by consulting the Documentation for the Image widget in the Help Center:
https://elementor.com/help/image-widget/

![image](https://github.com/user-attachments/assets/8388d75e-6ad9-46bc-97d1-6d1ef6f11365)



### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
