### ISSUE TITLE
MyElementor Support Tickets no reply button

### ISSUE THREAD

**Issue by Ezyweb-uk** [elementor/elementor#27661]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

With an Elementor Pro license, when logged into MyElementor, and having submitted a support ticket, there is no Reply button or link, neither in Firefox nor Chrome browsers. How do we reply to a support ticket?

I submitted a ticket asking this same question, the response was essentially 'please be clearer'. So I opened a chat conversation with the same question ..... no reply!

There seems to be a communication issue with Elementor Support.

### Steps to reproduce

Login to My.Elementor.com
View Support Activity
Click on a support ticket link
Look for a reply method, there isn't one - maybe because they are marked as 'done' on the first response?

### Expected behavior

I expect to see a reply button or reply link

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
N/A
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by toineenzo** [comment]
This is not the place for reporting something different then Elementor Bugs. Check your browser console for any errors, disable adblocker if you use any. You can also email support@elementor.com

**Comment by Ezyweb-uk** [comment]
They finally admitted there was an issue with their support portal.

I will try support@elementor.com in future but will expect rejection.
