### ISSUE TITLE
❌ 🛟 Support Request: Need to reveal element when sticky navbar kick in

### ISSUE THREAD

**Issue by Foody2** [elementor/elementor#27673]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Is it possible to to reveal element(heading) when sticky navbar kick in? Because I hide it when the page loads display:none; I tried

.elementor-sticky–active.reveal {
display: block;
}

and

.elementor-sticky–effects.reveal {
display: block;
}

reveal is custom class that I added, but it’s not working. I contacted elementor support but they said it’s not possible atm with elementor native, is there a way to show that element when sticky navbar kicks in (it’s a part of navbar)? Thanks in advance!

### Steps to reproduce

Added those line to custom css, but it's not working

.elementor-sticky–active.reveal {
display: block;
}

and

.elementor-sticky–effects.reveal {
display: block;
}

### Expected behavior

The heading need to be shown when sticky navabr kick in.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation Edit: The contributor did not follow the Bug Report Guidelines and shared the Full Elementor System Info]**

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Foody2,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

I see in your custom CSS that you used invalid classes to apply your customization. More precisely you're missing a `-` in both the `.elementor-sticky--active` and the `.elementor-sticky--effects` classes.

This is the correct implementation of your custom CSS:

```css
.reveal.elementor-sticky--effects {
    display: block;
}
```

This assumes you set `.reveal` to `display: none` initially.

However, it's worth mentioning that using the `display: none` property might cause layout shift, as it literally removes the element in question from the rendering tree. You might want to consider a different approach using opacity instead:

```css
.reveal {
    opacity: 0;
    transition: opacity 0.25s ease-out; /* This adds a smooth transition to the element */
}

.reveal.elementor-sticky--effects {
    opacity: 1;
}
```

Please, in the future don't use this space to ask for support. Thank you!

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
