### ISSUE TITLE
🚀 Feature Request: Add a User Registration Form or Provide an option to change the register redirect link

### ISSUE THREAD

**Issue by Grynn07** [elementor/elementor#2775]
Hey there, 

I love the Pro version of Elementor, I was wondering if I could request a new feature.It has to do with the Login widget, specifically the registration button. Could you make it so we can customize a link for the registration button to direct to? 

Right now it just goes to the default WordPress one, and it's not impressive or attractive. Being able to make a custom page that this link directs to would be fantastic!

Thanks!
--

**Comment by bainternet** [comment]
@Grynn07 

Can you clarify which "registration button" you are talking about?

because the "Login form" widget has no register button or link.

**Comment by Grynn07** [comment]
Here is an example, from a website I'm building for a client: http://prntscr.com/hd0fz2

Notice it gives the option in the Login widget to have a "Register" button, which appears next to the "Lost my Password" button, but there isn't a Register widget, so it just goes to the default WordPress registration page. 

I eventually found a plugin that overrides the default WordPress register page, Registration Magic I believe it's called, but I think I went through all of the user and registration plugins to find one that integrated well with Elementor's Login widget. 

So the two options I believe would be to add a "Registration widget," or make it so the Register button can have a custom link.

**Comment by bainternet** [comment]
I see what you mean.

Currently, this feature is not supported, but we will look into it in the future if we see more demand for it.

Thanks for the feedback.

**Comment by nicholaszein** [comment]
#5184 

Hello!

Thank you for your submission! 🙏 

I'm closing this issue and ↔️ **Merging** it with #5184, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
