### ISSUE TITLE
⛔ Heading widget does not allow any html attributes anymore if role is editor or below

### ISSUE THREAD

**Issue by snandos** [elementor/elementor#27939]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Users with roles of editor and below are not able to save html attributes like class="" in the heading widget.
This seems to be a bug introduced by PR #27542

If i change line 114 of [includes/widgets/heading.php](https://github.com/elementor/elementor/pull/27542/commits/48778806f3dec63c52ed3296aa6d1a489aa752a2#diff-0d615ff65ef4a8abfe6ad2a2ba25ad1cc1974a4a50e2e420b11bbcdc0978d22f) to
```php
return substr( $attribute, 0, 5 ) !== 'data-';
```
it works again.

I guess because of operator precedence.

### Steps to reproduce

Try to create a heading with a `<span class="test">TEST</span>` content and a role below or equal to admin. The class attribute will be stripped because of kses to `<span>TEST</span>`.

### Expected behavior

Basic HTML attributes should work in the heading widget.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.25
	PHP Version: 8.2.20-nmm1
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 768M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 768 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /news/%postname%/
	Language: de_DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: 
	Version: 1.0.1
	Author: 
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de-DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.3.3
		Author: WP Engine

	BackWPup
		Version: 4.1.2
		Author: BackWPup – WordPress Backup & Restore Plugin

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.5
		Author: ShortPixel

	GDPR Cookie Consent
		Version: 2.4.0
		Author: WebToffee

	Intuitive Custom Post Order
		Version: 3.1.5
		Author: hijiri

	JetElements For Elementor
		Version: 2.6.19
		Author: Crocoblock

	JetEngine
		Version: 3.2.5.1
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.3
		Author: Crocoblock

	Redirection
		Version: 5.4.2
		Author: John Godley

	WebP Express
		Version: 0.25.9
		Author: Bjørn Rosell

	Wordfence Security
		Version: 7.11.6
		Author: Wordfence

	WP All Import - ACF Add-On
		Version: 3.3.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.8.1
		Author: Soflyy

	WP Mail SMTP
		Version: 4.0.1
		Author: WP Mail SMTP

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 21.1
		Author: Team Yoast


== Eigenschaften ==
	Custom Fonts: 0
	Custom Icons: 1

== Integrations ==
	
	recaptcha_v3: Aktiv


== Elementor-Experimente ==
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Additional Custom Breakpoints: Standardmäßig aktiviert
	Flexbox Container: Aktiv
	Grid Container: Aktiv
	Upgrade Swiper Library: Standardmäßig aktiviert
	Nested Elements Performance: Standardmäßig deaktiviert
	Optimized Control Loading: Standardmäßig deaktiviert
	Optimized Markup: Standardmäßig deaktiviert
	Plugin Onboarding: Standardmäßig aktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header & Footer: Inaktiv
	Elementor Home Screen: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Build with AI: Standardmäßig aktiviert
	Startseiten: Inaktiv
	Nested Elements: Aktiv
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Element Caching: Standardmäßig deaktiviert
	Conversion Center: Standardmäßig deaktiviert
	Bedingungen anzeigen: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Menü: Aktiv
	Taxonomy Filter: Aktiv


== Protokoll ==
	

JS: showing 2 of 2JS: 2023-09-18 14:56:54 [error X 5][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.16.3:3:48021] l[0] is undefined 
JS: 2023-09-21 09:10:28 [error X 2][../wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben
	JetElements For Elementor: Die Kompatibilität ist nicht angegeben
	JetTabs For Elementor: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by threadi** [comment]
I also encountered this problem during a project today. My temporary solution is to deactivate the sanitizer in general - it is not executed for users with `manage_options` anyway, and with this code it is not executed for all others either:

```
add_action( 'init', function() {
	remove_filter( 'elementor/document/save/data', [
		Plugin::$instance->modules_manager->get_modules( 'content-sanitizer' ),
		'sanitize_content'
	] );
});
```

But I would take this with caution. I'm unsure whether this would be usable for every project.

A fix for the bug would be appreciated.

**Comment by rloes** [comment]
+1

I really got a headache about this today. A fix would be appreciated. Content Sanitation makes sense, but basic HTML tags should be allowed.

**Comment by caspervoogt** [comment]
I am experiencing this in a heading element, using an editor user account. When editing as an admin user it's fine. My heading widget contains spans with class attributes, and the class attributes get stripped when editing as a user with the Editor role. I managed to put a CSS workaround in place for this particular case, but it's not great to have to do that, when class attributes inside spans used to work just fine for editors, until some recent Elementor updates. This is a regression and should be fixed.

**Comment by nicholaszein** [comment]
Hello everyone,

Thank you for your feedback! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's why:
This is part of a security enhancement for the Heading widget introduced with Elementor v3.22. Only administrator roles are allowed to add html to the Heading widget.

We have no plans to change this behavior due to security concerns.

### ✅ What you can do to solve your issue:
Only administrator roles are allowed to add html attributes to the Heading widget. Ensure your user has the adminstrator role.

### 👍 For now, that's all we can help with. 

Kind regards
