### ISSUE TITLE
:x: CTA widget... No Vertical positioning for mobile devices

### ISSUE THREAD

**Issue by dougm1966** [elementor/elementor#28040]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

In the Call To Action widget there is no vertical alignment of the content. 

They are only there for the Alignment and Padding options, but it is missing near the Vertical Position option

### Steps to reproduce

Install the Elementor Pro.
Reference:
Re: Case #TSIPCZRWSUGU - There is a bug in the CTA widget. The button link and color hover doesn't align properly

### Expected behavior

Expect to have all the alignment options needed.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Not necessary.
It's missing from the plugin.
Confirmed by support ticket 

Re: Case #TSIPCZRWSUGU - There is a bug in the CTA widget. The button link and color hover doesn't align properly
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi.

This is more of a feature request, not a but. Please, as stated in the bug report for and contribution guidelines, use GitHub issue only to report bugs. If you wish to request a feature, please, [submit a new feature request](https://elemn.to/gh-new-feature-request).

Required fields are not optional.
