### ISSUE TITLE
✅ 🐞 Mega Menu Item Content causes page horizontal scroll

### ISSUE THREAD

**Issue by hitsgee** [elementor/elementor#28087]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When using the latest Elementor version 3.23.1 and pro 3.23 there is additional browser scroll when using sections in the new menu (mega menu) widget.

See my explanation video here: https://www.awesomescreenshot.com/video/29587463

### Steps to reproduce

1. Use the latest Elementor
2. Create a mega menu item with a full width section
3. Observe how this creates additional browser scroll as per video.

### Expected behavior

1. No excessive browser scroll

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.36-28
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://www.finkleydownfarm.co.uk
	Home URL: https://www.finkleydownfarm.co.uk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: HITS Core Child
	Version: 1.0.1
	Author: HITS
	Child Theme: Yes
	Parent Theme Name: HITS Core
	Parent Theme Version: 3.1
	Parent Theme Author: HITS

== User ==
	Role: administrator
	WP Profile lang: en-GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.3.3
		Author: WP Engine

	Advanced Post Queries
		Version: 1.1.3
		Author: Shabti Kaplan

	Elementor
		Version: 3.23.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.0
		Author: Elementor.com

	HITS CMS
		Version: 3.8.8
		Author: HITS

	ManageWP - Worker
		Version: 4.9.20
		Author: GoDaddy

	PowerPack Pro for Elementor
		Version: 2.10.22
		Author: Team IdeaBox - PowerPack Elements

	Security Optimizer
		Version: 1.5.0
		Author: SiteGround

	Speed Optimizer
		Version: 7.6.2
		Author: SiteGround

	Yoast SEO
		Version: 23.0
		Author: Team Yoast

	Yoast SEO: Local
		Version: 15.1
		Author: Team Yoast and Arjan Snaterse

	Yoast SEO Premium
		Version: 23.0
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Inactive
	Header &amp; Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive
	Build with AI: Inactive
	Landing pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Element Caching: Inactive
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Inactive
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Inactive
	Search: Inactive by default


== Log ==
	
Log: showing 20 of 432024-06-25 08:19:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.1',
  'to' => '3.22.2',
)]
2024-06-26 10:49:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-06-26 10:49:11 [info] elementor::elementor_updater Started 
2024-06-26 10:49:11 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-26 10:49:11 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-26 10:49:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-06-26 12:28:28 [info] elementor-pro::elementor_pro_updater Started 
2024-06-26 12:28:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-06-26 12:28:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-06-26 12:28:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-07-16 09:11:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-16 09:11:12 [info] elementor-pro::elementor_pro_updater Started 
2024-07-16 09:11:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-16 09:11:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-16 09:11:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-16 09:11:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-16 09:11:24 [info] elementor::elementor_updater Started 
2024-07-16 09:11:24 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-16 09:11:24 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-16 09:11:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	PowerPack Pro for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @hitsgee!

I am having trouble viewing your video. Can you please embed the video here on GitHub so we can properly see it and reference it in the future?

When I click on the link I see this screen:

![image](https://github.com/user-attachments/assets/1b1dfe98-ad6c-433b-946d-ce1a6485be8d)

Please, embed the video here.

Thanks

**Comment by hitsgee** [comment]
I'm sorry I think the permissions were incorrect.

Here is the embedded video.

https://github.com/user-attachments/assets/6fe743c7-9d24-4db6-9ad4-f92dcf2bf36a

**Comment by nicholaszein** [comment]
Thank you for sharing the video @hitsgee!

I can now understand what's the problem. I'll check with the team, and we will open a task to solve it! 😉 

Kind regards

**Comment by nicholaszein** [comment]
Hi @hitsgee!

Can you please clarify if you have changed how scripts are loaded on your site? I see you are using the **Speed Optimizer** plugin. Can you check if you have delayed or deferred the execution of scripts? Or if they are set to only load on interaction?

**Comment by hitsgee** [comment]
Hi,

No I do not have anything set to touch scripts. Just HTTP enforce, image optimisation and disable the loading of the emoji script.

The issue is still present with this plugin disabled.

Weirdly a few of my sites with mega menus are not having the issue.

It seems if I manually create the widgets for the menu it works but if I copy from another page into the menu it causes the issue.

Not sure if this is related to the copy functionality but may help.

Giles

**Comment by nicholaszein** [comment]
I haven't been able to reproduce your issue on my end yet @hitsgee. It seems specific to this website of yours.

**Comment by nicholaszein** [comment]
Hi @hitsgee,

we will need to investigate your issue further. Can you please reach out to [Elementor Support](https://my.elementor.com/support-center/), submit a ticket, and follow the instructions to provide access to your website? Once you provide all the information, please share the Ticket Number here with me, and I'll see if we can hop on your website and investigate this closer.

When opening your ticket, please let them know it's about this issue, and that I asked you to reach out so you could provide credentials for us to login to your website in a secure manner. Once we have the ticket number in hand, we will reach out to support to safely get the access to your website. You most likely will need to use [this plugin](https://wordpress.org/plugins/temporary-login/).

We think we might know what is causing your issue, but we would need to verify it by visiting the backend of your website. Rest assured privacy and security are of paramount concern for us, as well as your site data. We won't make any changes, we just need to check it directly.

Please let us know if you agree to do this. Also, please, for your safety, do not share credentials here. 

Thanks

**Comment by hitsgee** [comment]
Hi @nicholaszein,

A support ticket has been open with access credentials.

#TSLPVMCTU56C 

Giles

**Comment by nicholaszein** [comment]
Thanks @hitsgee ! You rock! 💪

**Comment by hein-obox** [comment]
@hitsgee @nicholaszein 

We are looking into the problem, and we are trying to find a general solution:

In the mean time, I think this CSS should solve the problem on the website for you: 

body {
    max-width: 100vw;
    overflow-x: hidden;
}

Below a link with an explanation about how you can add CSS to your website: 

https://www.hostinger.com/tutorials/wordpress-custom-css#:~:text=Adding%20WordPress%20Custom%20CSS%20with%20Theme%20Customizer,-No%20matter%20what&text=Navigate%20to%20Appearance%20%E2%86%92%20Customize,to%20add%20any%20CSS%20code.

**Comment by hitsgee** [comment]
Thank you. I have added it to this site and the issue is gone for now. Thank you.

**Comment by kilianhln** [comment]
Same problem here with the mega menu. 
It has to do with the elementor-sticky__spacer element. If I remove this element the overflow is gone.

**Comment by hein-obox** [comment]
@kilianhln Thank you for your feedback. You were right. This helped me to identify and solve the problem.

This problem will be fixed in the next Elementor Pro 3.23.2 release, next week Monday.

In the mean time you can use the code suggested in this ticket.

@nicholaszein Thank you for your assistance.

**Comment by nicholaszein** [comment]
Hey @hitsgee!

As you can see, we could reproduce this issue, and find a fix. This fix will be released soon! 💪 

Thank you so much for helping us, and for being so patient. 🙏 

On your website, we created a backup using the All-In-One WP Migration plugin while we were investigating this issue, and I just removed that backup and deleted the plugin. Nothing was changed on your website besides that, all work was done on a copy of your website that will be deleted once the fix for this issue is released.

You can safely remove the login credentials and the temporarily login from your website as well.

Please let me know if you need any more information about this procedure!

Kind regards

**Comment by hitsgee** [comment]
Hi @nicholaszein, 

Amazing thank you so much for your help on this.

I have patched the sites I have affected and will await the update to fix.

Giles
