### ISSUE TITLE
❌ Invalid Issue

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#28094]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The title says it all. Elementor continues to overstep with AI. I would guess that most agencies do NOT want this anywhere near their websites. 

Furthermore, Elementor AI has no place in the WordPress block editor. Over. Stepping. Full Stop.

This should be removed immediately, or we need the option to opt-out.

You can say this isn't a bug, but it's certainly not a feature if we cannot opt out. It's a bug because it is breaking sites, slowing down sites, and so on.

### Steps to reproduce

1. Edit a post with WP Block Editor
2. 'Generate with Elementor AI' displays in the editor.

### Expected behavior

Not seeing Elementor AI in the WP Block Editor.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

Redacted by moderation

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @wpturnedup.

Please do not use GitHub Issues to file complaints or request features. Elementor GitHub Issues are reserved only to report bugs in the code. The feature you're referring to is not a bug.

If you need to file a complaint reach out to Elementor Support. If you wish to request a feature check our [Feature Request Discussions](https://elemn.to/gh-feature-requests).

Keep in mind, that by using this space you agree to our [Contribution Guidelines](https://elemn.to/gh-contributing) and [Code of Conduct](https://elemn.to/gh-code-of-conduct).

Here is a Feature Request related to your issue that you can join and vote: #22853  

Kind regards
