### ISSUE TITLE
⛔ 🔗 🛟 Support Request: Mega Menu doesn't show all Menu Items on Mobile (Duplicate of #28117)

### ISSUE THREAD

**Issue by paskalr1** [elementor/elementor#28139]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

After I upgraded Elementor Pro from 3.22.1 to 3.23.0 the Mega Menu toggle on mobile only displays the first menu item. It works fine on desktop. I have the same problem on 2 sites. On my main site I have rolled back the plugin to 3.22.1 but you can check another under dev site http://184.72.201.54/ which is running on latest version

I have done all the troubleshooting, and it looks like it's a bug. The menu toggle does not even work while in the editor in responsive mode. On the Dev site only elementor and woo commerce is enabled.

### Steps to reproduce

You will need Elementor Pro to recreate this.

1. Create a new header
2. Add mega menu
3. Add more than one menu item (e.g. Test-1, Test-2, Test-3, Test-4)
4. Switch to responsive and select mobile
5. Click on menu toggle

### Expected behavior

1. When on mobile, click on the menu toggle
2. it should list all menu items

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v11.2.2-MariaDB
	PHP Version: 8.2.15
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6
	Site URL: http://184.72.201.54
	Home URL: http://184.72.201.54
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.7.3
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.23.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.0
		Author: Elementor.com

	WooCommerce
		Version: 9.1.2
		Author: Automattic


== Elements Usage ==
	
	footer : 1
		container : 6
		google_maps : 1
		heading : 3
		icon-list : 3
		image-box : 1
		social-icons : 1
	header : 2
		container : 17
		icon : 2
		icon-list : 4
		mega-menu : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 2
	product : 1
		container : 4
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	wp-page : 2
		container : 24
		heading : 8
		icon-list : 1
		image : 10
		image-carousel : 1
		text-editor : 3


== Settings ==
	
	cpt_support: post, page, product
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Inactive by default


== Log ==
	
Log: showing 20 of 392024-06-25 07:53:05 [info] elementor-pro::elementor_pro_updater Started 
2024-06-25 07:53:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-06-25 07:53:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-06-25 07:53:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.2',
  'to' => '3.22.1',
)]
2024-06-25 07:53:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.2',
  'to' => '3.22.1',
)]
2024-07-02 13:54:45 [info] elementor::elementor_updater Started 
2024-07-02 13:54:45 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-02 13:54:45 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-02 13:54:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-02 13:54:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-18 12:37:30 [info] elementor::elementor_updater Started 
2024-07-18 12:37:30 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-18 12:37:30 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-18 12:37:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-18 12:37:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-18 12:39:04 [info] elementor-pro::elementor_pro_updater Started 
2024-07-18 12:39:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-18 12:39:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-18 12:39:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-18 12:39:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]

PHP: showing 2 of 2PHP: 2024-07-02 13:56:24 [notice X 4][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-02 14:00:27 [notice X 6][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2024-07-04 17:15:37 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:657336] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-07-19 18:06:28 [error X 1][../wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.6:2:28760] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @paskalr1.

Thank you for sharing a link to a website that I can actually visit.

Your problem is caused because you enabled **Horizontal Scroll** on mobile under the Additional Settings section. Please change it to **`Disable`**.

![image](https://github.com/user-attachments/assets/471e0a0d-598a-42e4-9843-0666b93568bd)

### 🛟 This is more of a personal support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
