### ISSUE TITLE
⛔ Hide Mega Menu Dividers on Mobile

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#28140]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

There's no way to disable or hide the dividers for different devices sizes.

### Steps to reproduce

1. Enable dividers under the styling for the Mega Menu widget.
2. View website on mobile device.

### Expected behavior

1. I would expect there be a way to hide these dividers by device.
2. I have to use custom CSS to hide the dividers. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.38
	PHP Version: 8.1.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://wickydemo.com/wickydesign
	Home URL: https://wickydemo.com/wickydesign
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.3.4
		Author: WP Engine

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	HappyFiles Pro
		Version: 1.8.3
		Author: Codeer

	JetElements For Elementor
		Version: 2.6.19
		Author: Crocoblock

	JetEngine
		Version: 3.5.1
		Author: Crocoblock

	JetFormBuilder
		Version: 3.3.4.1
		Author: Crocoblock

	JetPopup
		Version: 2.0.4
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.1
		Author: Crocoblock

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	Wordfence Security
		Version: 7.11.6
		Author: Wordfence


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Inactive
	Flexbox Container: Active by default
	Grid Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Element Caching: Inactive
	Conversion Center: Inactive by default
	Display Conditions: Inactive
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	JetElements For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by mcrowell** [comment]
![mega-menu-divider](https://github.com/user-attachments/assets/9a577517-f82d-47f9-a2d3-e9a25d53227f)

**Comment by nicholaszein** [comment]
Hi, @mcrowell,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Please, do not use GitHub issue to request features. GitHub issues are reserved for Bug Reports only. Bugs are errors in the code that prevent a feature from working as it was intended. The feature in question does not offer responsive controls. What you are asking is to add an enhancement. Use the correct form to request your enhancement.

Kind regards
