### ISSUE TITLE
⌛ Warning: Attempt to read property “is_block_editor” on null

### ISSUE THREAD

**Issue by BackuPs** [elementor/elementor#28215]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Warning: Attempt to read property "is_block_editor" on null in /var/docs/public/wp-content/plugins/elementor/modules/ai/module.php on line 190

Issue has been reported more then a week ago here.  https://wordpress.org/support/topic/warning-attempt-to-read-property-is_block_editor-on-null/

However no response from your support team.

### Steps to reproduce

1) You need a theme or plugin that includes the tinymce editor on a different level f.e. _**[frontend]**_ as a field in the settings to add some extra content (not in pages and posts).

f.e. like this

![afbeelding](https://github.com/user-attachments/assets/e89803bb-4f56-4e66-aa3f-4be841025aaf)

The moment you open the plugin or theme settings page the error occurs.

### Expected behavior

Please check for is_block_editor exists

The solution is simple and effective. Just change your code to

		if ( function_exists( 'get_current_screen' ) ) {
			if ( isset( get_current_screen()->is_block_editor ) && get_current_screen()->is_block_editor ) {
				return;
			}
		}
		
and the issue is resolved.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.25
	PHP Version: 8.1.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7
	Site URL: https://mywebsite.com
	Home URL: https://mywebsite.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: WP Champion Professional Multi-Purpose WordPress Theme
	Version: 3.7.3 Build 18 july 2024
	Author: <a href="https://online.com/">XCelerated Web, Inc</a>
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

== Active Plugins ==
	Champion Responsive Menu
		Version: 3.1.47
		Author: The  

	Elementor
		Version: 3.23.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.1
		Author: Elementor.com

	Element Pack Pro
		Version: 7.12.21
		Author: BdThemes

	ElementsKit Lite
		Version: 3.2.2
		Author: Wpmet

	ElementsKit Pro
		Version: 3.6.5
		Author: Wpmet

	Envato Market
		Version: 2.0.11
		Author: Envato

	Envato Theme Check
		Version: 1.0.0
		Author: Scott Parry

	Essential Grid
		Version: 3.1.4
		Author: ThemePunch

	Essential Grid Google Fonts Addon
		Version: 1.1.4
		Author: ThemePunch

	Essential Grid Media Filters Addon
		Version: 1.0.2
		Author: ThemePunch

	Essential Grid NGG Adapter AddOn
		Version: 1.0.3
		Author: ThemePunch

	Essential Grid Related Posts AddOn
		Version: 1.0.4
		Author: ThemePunch

	Essential Grid RML Adapter AddOn
		Version: 1.0.3
		Author: ThemePunch

	Essential Grid Social Media AddOn
		Version: 1.0.8
		Author: ThemePunch

	Essential Grid Video Playlists AddOn
		Version: 1.0.6
		Author: ThemePunch

	Essential Grid Watermarks Addon
		Version: 1.0.5
		Author: ThemePunch

	Essential Grid WP Gallery Replace Addon
		Version: 1.0.5
		Author: ThemePunch

	Flexible Elementor Panel
		Version: 2.4.0
		Author: WebMat

	Maintenance
		Version: 4.12
		Author: WebFactory Ltd

	RTL Tester
		Version: 1.2
		Author: <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>, <a href="http://automattic.com">Automattic</a>

	Slider Revolution
		Version: 6.7.15
		Author: ThemePunch

	Widget Importer & Exporter
		Version: 1.6.1
		Author: ChurchThemes.com

	WordPress Beta Tester
		Version: 3.5.6
		Author: WordPress Upgrade/Install Team

	WP Modify Login Error Message
		Version: 1.0
		Author: noone

	WP Statistics
		Version: 14.9.2
		Author: VeronaLabs


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Inactive by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active by default
	Search: Inactive by default


== Log ==
	
Log: showing 20 of 432024-07-16 07:58:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-16 08:02:14 [info] elementor::elementor_updater Started 
2024-07-16 08:02:14 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-16 08:02:14 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-16 08:02:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-23 15:32:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-23 15:32:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-23 16:02:07 [info] elementor::elementor_updater Started 
2024-07-23 16:02:07 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-23 16:02:07 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-23 16:02:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-23 16:02:07 [info] elementor-pro::elementor_pro_updater Started 
2024-07-23 16:02:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-23 16:02:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-23 16:02:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-26 08:49:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-07-26 08:49:29 [info] elementor::elementor_updater Started 
2024-07-26 08:49:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-26 08:49:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-26 08:49:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Element Pack Pro: Compatible
	Flexible Elementor Panel: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @BackuPs!

Thank you for submitting your issue! 🙏 

Unfortunately there is not enough information to understand what you are referring to. Can you please elaborate on your issue? Please answer the following questions:

1. Where does it happen? How can I reproduce your issue on my own environment to get the warning you are receiving? Please, give me exact steps to reproduce it.
2. Did you isolate the problem as instructed in the Bug Report form by deactivating all plugins except Elementor and Elementor Pro?
3. Did you isolate the problem as instructed in the Bug Report form by switching to the Hello Elementor theme?

Please, provide the required information so we can understand where and how your issue is happening. Otherwise, we won't be able to validate your issue.

Thank you

**Comment by BackuPs** [comment]
The issue is that when you call wp_editor() at a different level in f.e. in a theme settings  in the wp admin area or plugin settings in the wp admin area where a editor field is presented by wp_editor()  the error logs get flooded with these warnings and will in the long run result in a fatal when php changes.  

I am not talking about adding or editing wordpress  pages or posts.  I am talking about plugins and themes that add a text editor in their settings by use of wp_editor().  

The editor will  look exactly the same as when you edit a post or page except that get_current_screen()->is_block_editor is not set and does not exist.

Can you please just change your code as suggested and check for existence of get_current_screen()->is_block_editor.

Your code will keep working the same way except the php error logs stay clean and do not get flooded by unneccessary warnings.  

There are more ways to fire uop or call the wp_editor() then just by adding or editing wordpress posts and pages and in which case the tinymce editor text editor is presented by wordpress.

I can create a support request at elementor pro and give you access to a dummy install but you will come to the same conclusion as i describe here and that is:  that get_current_screen()->is_block_editor is not always set by wordpress and does not always exists!

My suggestion is below and will not alter the working of your code.

`	if ( function_exists( 'get_current_screen' ) ) {
		if ( isset( get_current_screen()->is_block_editor ) && get_current_screen()->is_block_editor ) {
			return;
		}
	}`
	
	
You could create a text field in your own elementor settings where you have text field that uses the wp_editor() tinymce editor.  If you have debug mode enabled you will see the warning message.  

In my case i am running the classic editor plugin aswell.

I am not the only one seeying this happening as i hooked into another thread at wordpress.org.

But even with all plugins turned off and only elementor enabled the moment i call wp_editor() to add the tinymce editor in my theme settings i see the error/warning.

**Comment by nicholaszein** [comment]
Hi @BackuPs!

We understand what you are reporting, but unfortunately, we cannot reproduce your issue. It seems the issue is being caused by a conflict with your theme, custom code, or a 3rd-party plugin. We need you to provide the information requested in this comment to be able to pin down the problem. To be clear, we are testing this on a brand new installation using only Elementor, Elementor Pro, and the Hello Elementor theme, and we cannot verify any indications of this error appearing on our web server error logs.

Please, provide the missing information, otherwise we can't continue to evaluate and validate your issue.

Kind regards

**Comment by BackuPs** [comment]
You changed the code in version 3.23.4 so the issue is gone.

There is and was no issue between the theme and any other plugin.  Even in a clean install with only elementor free active the  issue was there after calling wp_editor() in the theme settings to present the tinymce editor where a users could add his custom text with shortcodes etc etc.

Anyway the issue is gone now since you changed module.php  in the ai folder. You are no longer testing get_current_screen()->is_block_editor  in your code.
