### ISSUE TITLE
⛔ 🛟 Support Request: Does Elementor Sanitize Form Fields?

### ISSUE THREAD

**Issue by kaketusse** [elementor/elementor#28243]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello,

I would like to know if by default the user inputs are sanitised when using Elementor form widget before the form actions run ?

But I have run 2 tests, and it seems it's done. Can Elementor team confirme this ?

With a very simple form using the Elementor From Widget with just one textarea field, it seems there is some sanitizing data process by default.

Without any custom code, when I write on the textarea field : <script>alert(‘hello’)</script>
=> on the submission dashboard, the message field is blank
=> on the wp_e_submissions_values table DB, the message field is blank
See screenshots 1 to 4.

When I write on the textarea field : <html><h1>hello</h1></html>
=> on the submission dashboard, the message field is just hello
=> on the wp_e_submissions_values table DB, the message field is just hello
See screenshots 5 to 7.

![1](https://github.com/user-attachments/assets/47f8081b-54a5-4ad6-b58f-e57615a5c73e)
<img width="663" alt="8" src="https://github.com/user-attachments/assets/b55aff40-1f86-475d-bad1-c9f510a1bf3d">
<img width="660" alt="4" src="https://github.com/user-attachments/assets/b21fd998-fd54-44be-a8fb-4b5ac372d0b4">
<img width="1260" alt="7" src="https://github.com/user-attachments/assets/f4094f3f-709e-4b59-aec4-f7513b1cb61b">
![6](https://github.com/user-attachments/assets/51574965-f3b4-48f1-9699-1923a377aeef)
![5](https://github.com/user-attachments/assets/d7d63e2a-738a-482e-9965-b9e64eea012b)
<img width="1259" alt="3" src="https://github.com/user-attachments/assets/d2d18a01-731c-4632-81c4-4b65dd634003">
![2](https://github.com/user-attachments/assets/0c339927-47de-4ddf-8377-a21e56c12e8a)

In the case sanitization in not done by default, how can I can do it using the several sanitize Wordpress functions ?
I have read the documentation about Elementor form hooks : https://developers.elementor.com/docs/hooks/forms/
The sanitizing data means you can read the data, remove some part of it (like the html tag) and then forward them to the form actions.
I don't see in the documentation any ways describing how this can be done....

### Steps to reproduce

1. Elementor form widget documentation should talk a bit about sanitization
2. An exemple should be described in the documentation

### Expected behavior

1. Elementor form widget documentation should talk a bit about sanitization
2. An exemple should be described in the documentation

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: http://elementor-testing.local
	Home URL: http://elementor-testing.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.23.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.1
		Author: Elementor.com


== Elements Usage ==
	
	header : 3
		container : 5
		heading : 1
		html : 1
		icon : 3
		nav-menu : 4
		off-canvas : 1
		text-editor : 4
	popup : 1
		container : 1
		form : 1
		heading : 1
		nav-menu : 1
	section : 1
		button : 1
		container : 1
		heading : 1
		nav-menu : 1
	wp-page : 2
		button : 6
		container : 56
		form : 2
		heading : 36
		html : 1
		icon : 4
		image : 17
		nav-menu : 1
		spacer : 6
		text-editor : 11


== Settings ==
	
	cpt_support: post, page, e-landing-page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active
	Header &amp; Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Element Caching: Active
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Inactive
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Inactive
	Search: Inactive by default


== Log ==
	
Log: showing 20 of 392024-07-16 12:43:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-16 12:43:31 [info] elementor::elementor_updater Started 
2024-07-16 12:43:31 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-16 12:43:31 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-16 12:43:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-23 20:12:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-23 20:13:03 [info] elementor::elementor_updater Started 
2024-07-23 20:13:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-23 20:13:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-23 20:13:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-24 07:08:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.1',
)]
2024-07-25 20:24:59 [info] elementor-pro::elementor_pro_updater Started 
2024-07-25 20:24:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-25 20:24:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-25 20:24:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.1',
)]
2024-07-25 20:26:24 [info] elementor::elementor_updater Started 
2024-07-25 20:26:24 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-25 20:26:24 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-25 20:26:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-07-25 20:26:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]

JS: showing 2 of 2JS: 2024-07-04 15:43:34 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:687045] elementorFrontend.elements.window.jQuery is not a function. (In &#039;elementorFrontend.elements.window.jQuery(T.el)&#039;, &#039;elementorFrontend.elements.window.jQuery&#039; is undefined) 
JS: 2024-07-04 16:02:56 [error X 256][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:17922] null is not an object (evaluating &#039;this.getColorRepresentation().toLowerCase&#039;) 

PHP: showing 1 of 1PHP: 2024-07-06 10:10:42 [notice X 25][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by kaketusse** [comment]
I got the answer from the support : 

Elementor follows the WordPress PHP Coding Standards, which requires us to sanitize data from everywhere, including the Elementor forms. [Please see this document](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#:~:text=text%20that%20goes%20into%20html%20or%20xml%20attributes%20should%20be%20escaped%20so%20that%20single%20or%20double%20quotes%20do%20not%20end%20the%20attribute%20value%20and%20invalidate%20the%20html%2C%20causing%20a%20security%20issue.%20see%20data%20validation%20in%20the%20plugin%20handbook%20for%20further%20details.)


WordPress has sanitizing guidelines that Elementor must follow before storing any information in the database. [Please see this document](https://developer.wordpress.org/apis/security/sanitizing/)​.

Elementor follows these guidelines to ensure every user input prevents any unexpected or unauthorized behavior.
- Escaping: Cleaning the output before rendering on a browser. Cleaning user input (DB/GET/POST) from anything that can break the code (such as escaping HTML chars using esc_html() to prevent XSS, or converting a query parameter to an integer using absint())
- Sanitize: Like escaping, but before saving to the DB. And instead of replacing the “bad” values, just remove them.
- Validation: Making sure that the user input’s type & structure are correct (isset(), empty(), is_numeric(), post_exists(), current_user_can() etc.).

**Comment by nicholaszein** [comment]
Hello @kaketusse!

Thank you for reaching out! 🙏 

This type of question is better answered by [Elementor Support](https://elementor.com/help/how-to-submit-a-support-ticket/) as you realized yourself. We reserve Elementor GitHub issues for actual bug reports, or errors found in the code of Elementor and Elementor Pro. If you have any further questions about any Elementor functionality, please reach out to Elementor Support. They will be better equipped to answer you in a timely manner.

We also ask our users to be familiarized with our [Contribution Guidelines](https://elemn.to/gh-contributing), and one of the most important sections is about security. We have managed Bug Bounty Programs, and we take security very seriously. If in the future you need to report any security issues, please follow our [Security Policy](https://github.com/elementor/elementor/security/policy).

Thank you for understanding!

Kind regards
