### ISSUE TITLE
⌛ ❌ 🧩 Custom Script used for calculating the height of an iframe is not working after updating Elementor to v.3.24.0-could8

### ISSUE THREAD

**Issue by nicomyname** [elementor/elementor#28250]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hall Elementor dev team

I have a code snipet for an iFrame resizer on my website. Now it is the case that the resizer no longer works because of the new Elementor Pro update (Cloud 8). No child theme works anymore and also no code snippet. I have tested by switching off and on the updates of the plugins which update is the reason and it was the one of Elementor Pro. What can I do?

https://www.loom.com/share/cea8da83574d433eae193a80189d18ed

Translated with DeepL.com (free version)

### Steps to reproduce

I explained on this Loom:

https://www.loom.com/share/8b41de3d54944cdaab2bd4a50f3e5358?sid=c4d47688-13fe-4db5-8846-643557fbf539

Here is the code in the functions php:
function hello_elementor_iframe_resizer() {
	wp_enqueue_script( 'jquery_cdn', 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' );
	wp_register_script( 'iFrameResizer', 'https://solarrechner.eturnity.io/muster_solar/static/iframe-resizer-client.js', array('jQuery'), '', true );
	wp_enqueue_script( 'iFrameResizer' );
}
add_action( 'wp_enqueue_scripts', 'hello_elementor_iframe_resizer' );

By the way on the cloud 7 version it also works in the code snippets plugin. I dunno maybe there is a php block on the new update or something.

### Expected behavior

I want that the php code is working for the iFrame i pasted in on the elementor designer with a html widget. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Operating System:	Linux	
Software:	nginx/1.24.0	
MySQL version:	(Google) v8.0.26	
PHP Version:	7.4.33	
PHP Memory Limit:	1024M	
PHP Max Input Vars:	10000	
PHP Max Post Size:	256M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected

Version:	6.6.1	
Site URL:	https://www.seetalsolar.ch	
Home URL:	https://www.seetalsolar.ch	
WP Multisite:	No	
Max Upload Size:	256 MB	
Memory limit:	512M	
Max Memory limit:	1024M	
Permalink Structure:	/%postname%/	
Language:	de_CH	
Timezone:	2
Debug Mode:	Inactive


Name:	Hello Elementor Child	
Version:	3.1.0.1722336324	
Author:	Nico Hodel	
Child Theme:	Yes	
Parent Theme Name:	Hello Elementor	
Parent Theme Version:	3.1.0	
Parent Theme Author:	Elementor Team

Activity Log - 2.11.0	By Activity Log Team	
Child Theme Configurator - 2.6.6	By Lilaea Media	
Code Snippets - 3.6.5.1	By Code Snippets Pro	
Elementor - 3.24.0-cloud8	By Elementor.com	
Elementor Pro - 3.24.0-cloud8	By Elementor.com	
FileBird Lite - 6.3.2	By Ninja Team	
FluentSMTP - 2.2.80	By FluentSMTP & WPManageNinja Team	
JetEngine - 3.5.2	By Crocoblock	
JetSmartFilters - 3.5.2	By Crocoblock	
JetTricks - 1.4.9	By Crocoblock	
Members - 3.2.9	By MemberPress	
SVG Support - 2.5.5	By Benbodhi	
White Label CMS - 2.7.4	By www.videousermanuals.com	
Yoast SEO - 23.0	By Team Yoast
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by m1ga** [comment]
Hallo @nicomyname 
two quick things I see: 
`Uncaught ReferenceError: $ is not defined` as you use 
```js
  $(document).ready(function() {
      $("#iframe-eturnity").iFrameResize({ log: true, checkOrigin: false });
   });
``` 
in your page which should either be `jQuery...` or you'll need to map $ to jQuery. At that point you can't use `$`. And your file https://solarrechner.eturnity.io/muster_solar/static/iframe-resizer-client.js is not available. Are you sure you use the iFrame script correctly?  https://iframe-resizer.com/setup/parent/ just says you call the method and not use it like you did with jquery

**Comment by nicholaszein** [comment]
Hello @nicomyname!

Thank you for reaching out! 🙏 

This is more of a support question, not something we can really help you with from here. We cannot provide assistance for custom code on GitHub.

However, after visiting your site the height is being correctly calculated for me. I believe your problem may be related to cache. Make sure you purge the cache, especially Cloudflare's cache! It would be wise to test on a private/incognito window, and or another browser.

Can you check that and get back to us?

Kind regards

**Comment by nicomyname** [comment]
Hey Nicholas

Thanks for your message.

I fixed the problem know.

But yes, there is a problem with cache. Do you've time to take a quick look?

Am Di., 30. Juli 2024 um 20:19 Uhr schrieb Nicholas Zein <
***@***.***>:
