### ISSUE TITLE
⛔ 🛟 Support Request: History - Action and Revison Menu Tabs unable to easily access in Elementor Top Bar BETA

### ISSUE THREAD

**Issue by SarahMead** [elementor/elementor#28304]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello! This is more of a support question or request for implementation with your new Beta top bar feature.

Unfortunately, since it is in beta, there is no 'help' menus for where features were moved too or removed. So please let me know if we are just unable to find where the feature was moved too.

---------

We are currently using the new UI front of Elementor (the beta top bar). We have noticed that the 'history' feature is no longer a part of this interface. Is this intentional? Or am I missing it in the new interface look?

1) If the 'history/action' feature was removed, I would like to place a request to bring that feature back. It was of great use when building websites.

2) I do see there are the saved revision versions you can go back to if needed, but I am also not sure how to get this menu screen without a pop-up coming up notifying me that we are in a 'draft'

I appreciate your time and hard work!

I have attached a screenshot of the 'history/action' feature I am referring too:
![Screenshot 2024-08-06 at 12 06 44 PM](https://github.com/user-attachments/assets/56dd878b-b77a-48b2-888d-1cc3957da7e8)
![Screenshot 2024-08-06 at 12 06 51 PM](https://github.com/user-attachments/assets/ad209c57-2613-44bc-8317-cd5257860bd1)

### Steps to reproduce

I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.I have clicked through every menu I could see/find.

### Expected behavior

This menu should exist and a way to get to this menu easily:

![Screenshot 2024-08-06 at 12 06 51 PM](https://github.com/user-attachments/assets/a092c5c2-a483-41fb-bc6b-20c6d44e0599)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: Source distribution v8.0.28
	PHP Version: 8.1.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://rebuildmanufacturing.com/appliedlogixnew
	Home URL: https://rebuildmanufacturing.com/appliedlogixnew
	WP Multisite: Yes
	Max Upload Size: 2 GB
	Memory limit: 64M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Redirection
		Version: 5.4.2
		Author: John Godley


== Network Plugins ==
	Better Search Replace
		Version: 1.4.7
		Author: WP Engine


== Must-Use Plugins ==
	Admin Notice
		Version: 0.1.0
		Author: WordPress VIP

	Advanced Post Caching
		Version: 0.2
		Author: Automattic

	Akismet Anti-Spam
		Version: 5.1
		Author: Automattic

	blogpublic-notice.php
		Version: 
		Author: 

	HTTP Concat
		Version: 1.0
		Author: Automattic

	Jetpack
		Version: 13.6
		Author: Automattic

	Lightweight Term Count Update
		Version: 0.1.0
		Author: Automattic, Alley Interactive

	prometheus.php
		Version: 
		Author: 

	query-monitor.php
		Version: 
		Author: 

	REST API Enhancements
		Version: 0.1
		Author: Erick Hitter, Automattic

	Rewrite Rules Inspector
		Version: 1.4.0
		Author: Automattic, Daniel Bachhuber

	VaultPress
		Version: 2.2.1
		Author: Automattic

	VIP AllOptions Safeguard
		Version: 
		Author: Automattic

	VIP Back-compat
		Version: 1.0
		Author: Automattic

	VIP Cache Manager
		Version: 1.1
		Author: Automattic

	VIP Client mu-plugins
		Version: 
		Author: Automattic

	VIP Codebase Manager
		Version: 1.0.0
		Author: Automattic

	VIP Cron Enhancements
		Version: 1.0
		Author: Automattic

	VIP Dashboard
		Version: 3.0.0
		Author: Scott Evans, Filipe Varela, Pau Argelaguet

	VIP Feed Cache
		Version: 
		Author: Automattic

	VIP File Service
		Version: 0.2
		Author: Automattic

	VIP Force Two Factor
		Version: 
		Author: Automattic

	VIP Go Core Modifications
		Version: 
		Author: Automattic

	VIP Go Plugin Compat
		Version: 1.0
		Author: Automattic

	VIP Hosting Miscellaneous
		Version: 1.1
		Author: Automattic

	VIP Init
		Version: 
		Author: Automattic

	VIP Integrations
		Version: 
		Author: Automattic

	VIP Mail
		Version: 1.0
		Author: Automattic

	VIP Parse.ly Integration
		Version: 1.0
		Author: Automattic

	VIP Performance
		Version: 1.0
		Author: Automattic

	VIP Plugins
		Version: 1.0.0
		Author: Automattic

	VIP Schema
		Version: 
		Author: Automattic

	VIP Security
		Version: 1.2
		Author: Automattic

	VIP Stats
		Version: 
		Author: Automattic

	WooCommerce: VIP Specific Changes
		Version: 1.0.0
		Author: Automattic

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WordPress VIP Support
		Version: 3.1.0
		Author: <a href="http://automattic.com">Automattic</a>

	WP-CLI for VIP Go
		Version: 
		Author: Automattic


== Elements Usage ==
	
	container : 48
		button : 16
		container : 175
		heading : 117
		image : 36
		image-carousel : 2
		text-editor : 102
	footer : 1
		container : 10
		heading : 2
		html : 1
		image : 4
		nav-menu : 4
		text-editor : 3
	header : 1
		container : 5
		html : 1
		image : 1
		nav-menu : 3
	wp-page : 4
		button : 4
		container : 82
		heading : 53
		image : 3
		text-editor : 49
	error-404 : 1
		button : 1
		container : 2
		heading : 2
		text-editor : 1


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active by default
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive
	Link In Bio: Inactive
	Floating Buttons: Inactive
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active by default
	Search: Inactive


== Log ==
	
Log: showing 20 of 412024-08-06 11:23:06 [info] elementor::elementor_updater Started 
2024-08-06 11:23:06 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:28:09 [info] elementor::elementor_updater Started 
2024-08-06 11:28:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:32:57 [info] elementor::elementor_updater Started 
2024-08-06 11:32:57 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:38:07 [info] elementor::elementor_updater Started 
2024-08-06 11:38:07 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:43:12 [info] elementor::elementor_updater Started 
2024-08-06 11:43:12 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:48:01 [info] elementor::elementor_updater Started 
2024-08-06 11:48:01 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:53:00 [info] elementor::elementor_updater Started 
2024-08-06 11:53:00 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 11:58:17 [info] elementor::elementor_updater Started 
2024-08-06 11:58:17 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 12:02:57 [info] elementor::elementor_updater Started 
2024-08-06 12:02:57 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 12:08:14 [info] elementor::elementor_updater Started 
2024-08-06 12:08:14 [info] Elementor/Upgrades - _on_each_version Start  

JS: showing 2 of 2JS: 2024-08-06 15:33:27 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:588967] Failed to read a named property &#039;elementorFrontend&#039; from &#039;Window&#039;: Blocked a frame with origin &quot;..&quot; from accessing a cross-origin frame. 
JS: 2024-08-06 15:50:51 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:712932] this.model.isValidChild is not a function 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @SarahMead,

you can find the History panel in the Elementor Menu, at the top-right corner by clicking on the Elementor Logo.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

You can go directly to the Help Center by clicking on the Question Mark icon at the top-right hand corner of the Top Bar, from there you can search for anything, including "Top Bar", which will return the following article with the full documentation for the Top Bar:
https://elementor.com/help/elementor-top-bar/


### ⚠️ Please Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
