### ISSUE TITLE
⛔ 🛟 Website not loading properly when using the Elementor Developer Edition plugin

### ISSUE THREAD

**Issue by patriciarolda** [elementor/elementor#28510]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

<img width="959" alt="26AUG Website Error" src="https://github.com/user-attachments/assets/00c1dd32-f614-4e61-a28c-45da992872ed">
I’m encountering an issue with the layout of my website. I’ve attached a screenshot showing how the site appears when viewed directly. As you can see, the elements are misaligned and appear out of place.

Interestingly, when I edit the site using Elementor, everything appears correctly and loads as expected. This discrepancy between the live site and the Elementor editor is causing confusion.

Could someone help me troubleshoot and resolve this issue? Specifically, I’m looking for guidance on:
1. Potential conflicts or issues between Elementor and the live site display.
2. Steps to ensure consistent layout and design across both views.
3. Any common fixes or adjustments needed to address this kind of problem.

### Steps to reproduce

I’m experiencing a layout issue with my website. When I open the live site, all the elements are misaligned and appear out of place. The site does not load correctly, and the layout is significantly disrupted.

In contrast, when I edit the same page using Elementor, everything displays properly and aligns as expected. The discrepancy between the live site and the Elementor editor is creating confusion.

Here are the details:

Live Site Issue:
<img width="944" alt="LIVE SITE" src="https://github.com/user-attachments/assets/ba76f2a8-fe42-4263-b125-2c3b2c0b5c41">

Description: The layout is broken, with elements appearing all over the place and not in their intended positions.
Steps to Reproduce:
1. Open the website in a web browser (specify browser and version).
2. Observe the layout issues on the live site.
3. Screenshot/Recording: [Attach a screenshot or screen recording of the issue on the live site.]

Elementor Editor:
<img width="953" alt="ELEMENTOR EDITOR" src="https://github.com/user-attachments/assets/67d63925-7f00-4ea5-929f-8cb1bee6a9d1">
Description: The layout appears as expected with all elements in the correct positions.
Steps to Reproduce:
1. Log into Elementor and open the page in the editor.
2. Confirm that the layout is correct within Elementor.
3. Screenshot/Recording: [Attach a screenshot or screen recording of the layout in Elementor.]

Could someone please assist in identifying why the live site layout differs from what is shown in Elementor and advise on how to resolve this issue?

### Expected behavior

When accessing the live site, the following should occur:

1. Proper Alignment: All elements on the website (text, images, buttons, etc.) should be aligned correctly and displayed as intended.
2. Consistent Layout: The layout should match the design specified in the Elementor editor, with no misalignments or visual disruptions.
3. Smooth Loading: The site should load properly without any issues that affect the presentation of elements or their positions.

<img width="953" alt="ELEMENTOR EDITOR" src="https://github.com/user-attachments/assets/b53f96f1-7059-40aa-9b78-2eb4fa08ad31">
In the Elementor editor, the site appears as expected with elements correctly positioned and aligned. The same layout should be reflected on the live site.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.1.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://fashionablyfit.vegas
	Home URL: https://fashionablyfit.vegas
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: Asia/Manila
	Debug Mode: Inactive

== Theme ==
	Name: Radcliffe 2
	Version: 2.0.19-wpcom
	Author: Anders Norén
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	BAW Multipass for Protected Pages
		Version: 1.4
		Author: Juliobox

	Crowdsignal Forms
		Version: 1.7.2
		Author: Automattic

	Crowdsignal Polls &amp; Ratings
		Version: 3.1.2
		Author: Automattic, Inc.

	Elementor
		Version: 3.24.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Expire Password Protected Pages
		Version: 0.1.0
		Author: Troy Glancy

	Gutenberg
		Version: 19.0.0
		Author: Gutenberg Team

	Image Hover Effects Ultimate (Photo Gallery, Effects, Lightbox, Comparison or Magnifier)
		Version: 9.9.3
		Author: Biplob Adhikari

	Jetpack
		Version: 13.8-a.5
		Author: Automattic

	Layout Grid
		Version: 1.8.4
		Author: Automattic

	Page Optimize
		Version: 0.5.5
		Author: Automattic

	Popup Trigger URL for Elementor Pro
		Version: 1.0.5
		Author: Suki WordPress Theme

	WordPress.com Editing Toolkit
		Version: 4.30504
		Author: Automattic


== Must-Use Plugins ==
	wpcomsh-loader.php
		Version: 
		Author: 


== Elements Usage ==
	
	header : 3
		container : 4
		image : 1
		nav-menu : 1
		social-icons : 1
	popup : 25
		button : 1
		container : 3
		gallery : 7
		heading : 2
		image : 2
		image-carousel : 15
		text-editor : 1
		video : 1
	wp-post : 4
		button : 6
		heading : 3
		icon : 3
		image : 6
		nav-menu : 3
		posts : 3
		social-icons : 3
		text-editor : 5
		theme-post-featured-image : 3
		theme-post-title : 1
		video : 3
	wp-page : 10
		button : 1
		call-to-action : 3
		container : 81
		divider : 6
		flip-box : 3
		gallery : 2
		heading : 27
		icon : 3
		icon-box : 4
		image : 22
		image-carousel : 2
		nav-menu : 10
		posts : 4
		price-list : 1
		slides : 1
		social-icons : 19
		spacer : 16
		testimonial-carousel : 1
		text-editor : 24
	single-post : 5
		container : 6
		image : 2
		nav-menu : 1
		progress-tracker : 1
		social-icons : 2
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
	loop-item : 3
		image : 1


== Settings ==
	
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 8
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active by default
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
Log: showing 20 of 312024-07-03 23:29:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev3',
  'to' => '3.23.0-dev4',
)]
2024-07-08 23:29:02 [info] elementor::elementor_updater Started 
2024-07-08 23:29:02 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-08 23:29:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev4',
  'to' => '3.23.0-dev5',
)]
2024-07-08 23:29:02 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-08 23:29:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev4',
  'to' => '3.23.0-dev5',
)]
2024-07-10 23:34:47 [info] elementor::elementor_updater Started 
2024-07-10 23:34:47 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-10 23:34:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev5',
  'to' => '3.23.0-dev6',
)]
2024-07-10 23:34:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-10 23:34:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev5',
  'to' => '3.23.0-dev6',
)]
2024-08-25 23:29:29 [info] elementor::elementor_updater Started 
2024-08-25 23:29:29 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-25 23:29:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]
2024-08-25 23:29:30 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-25 23:29:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0-dev6',
  'to' => '3.24.0-dev1',
)]
2024-08-26 01:34:57 [info] elementor-pro::elementor_pro_updater Started 
2024-08-26 01:34:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-26 01:34:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-26 01:34:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.23.3',
)]

JS: showing 5 of 5JS: 2024-07-08 15:36:07 [error X 10][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev4:3:663219] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-07-10 17:19:35 [error X 8][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev6:3:831949] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-07-11 16:06:37 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.0-dev6:3:588735] Failed to read a named property &#039;elementorFrontend&#039; from &#039;Window&#039;: Blocked a frame with origin &quot;..&quot; from accessing a cross-origin frame. 
JS: 2024-07-11 16:50:02 [error X 4][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-07-17 15:36:24 [error X 1][../wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:91564] Cannot read properties of undefined (reading &#039;toString&#039;) 

PHP: showing 6 of 6PHP: 2024-07-08 23:37:05 [warning X 24][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-07-11 00:11:46 [warning X 1][../wp-content/plugins/elementor/modules/ai/connect/ai.php::89] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-11 00:47:41 [warning X 2][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-12 00:34:53 [warning X 2][../wp-content/plugins/elementor-pro/modules/query-control/module.php::387] Undefined array key &quot;display&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-14 22:51:18 [warning X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-26 00:36:28 [notice X 8][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Popup Trigger URL for Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by crowlsyong** [comment]
Exact same issue for me. Seems to have something to do with the megamenu for me...but I'm not sure. 


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.36-28
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://adventurerock.com
	Home URL: https://adventurerock.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Chicago
	Admin Email: webhost@adventurerock.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.5.0.1644335711
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.3.5
		Author: WP Engine

	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	Business Hours Indicator
		Version: 2.4.1
		Author: StudioWombat

	Constant Contact Forms for WordPress
		Version: 2.6.0
		Author: Constant Contact

	Contest Gallery - PRO Version
		Version: 23.1.4-PRO
		Author: Contest Gallery - PRO

	Elementor
		Version: 3.24.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.3
		Author: Elementor.com

	Elementor Form Builder for MEC
		Version: 1.3.8
		Author: Webnus

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Elementor Shortcode Builder for MEC
		Version: 1.8.2
		Author: Webnus

	Elementor Shortcode Designer
		Version: 1.3.5
		Author: Webnus

	Elementor Single Builder for MEC
		Version: 1.10.1
		Author: Webnus

	Event Tickets
		Version: 5.13.2
		Author: The Events Calendar

	Gravity Booster ( Style &amp; Layouts )
		Version: 5.12
		Author: Sushil Kumar

	Gravity Forms
		Version: 2.8.16
		Author: Gravity Forms

	Gravity Forms Constant Contact Add-On
		Version: 3.1.1
		Author: Katz Web Services, Inc.

	Gravity Forms SendGrid Add-On
		Version: 1.6.0
		Author: Gravity Forms

	Image Optimizer by Elementor – Compress, Resize and Optimize Images
		Version: 1.5.1
		Author: Elementor.com

	Media Library Folders
		Version: 8.2.2
		Author: Max Foundry

	Media Library Folders Reset
		Version: 8.2.2
		Author: Max Foundry

	Modern Events Calendar
		Version: 7.13.0
		Author: Webnus

	Pages with category and tag
		Version: 0.9.0
		Author: YAHMAN

	Redirection
		Version: 5.5.0
		Author: John Godley

	Speed Optimizer
		Version: 7.6.4
		Author: SiteGround

	SVG Support
		Version: 2.5.8
		Author: Benbodhi

	UpdraftPlus - Backup/Restore
		Version: 1.24.4
		Author: UpdraftPlus.Com, DavidAnderson

	White Label CMS
		Version: 2.7.6
		Author: www.videousermanuals.com

	WPS Hide Login
		Version: 1.9.16.7
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 23.3
		Author: Team Yoast


== Features ==
	Custom Fonts: 3
	Custom Icons: 1

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Inactive
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Active
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Active by default


== Log ==
	
JS: showing 7 of 7JS: 2024-07-26 05:25:14 [error X 22][https://adventurerock.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.2:3:832970] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-07-26 05:29:09 [error X 2][https://adventurerock.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.23.1:3:66072] Cannot convert undefined or null to object 
JS: 2024-07-26 06:10:54 [error X 117][https://adventurerock.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.2:3:656179] Cannot read properties of undefined (reading &#039;model&#039;) 
JS: 2024-07-28 21:22:21 [error X 17][https://adventurerock.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.23.3:2:56144] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2024-07-29 09:47:22 [error X 3][https://adventurerock.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.3:3:663451] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-08-02 20:22:43 [error X 7][https://adventurerock.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.3:3:693233] elementorFrontend.elements.window.jQuery is not a function 
JS: 2024-08-15 22:11:32 [error X 1][https://adventurerock.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:832463] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 

Log: showing 20 of 252024-07-30 00:46:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-30 00:50:15 [info] elementor-pro::elementor_pro_updater Started 
2024-07-30 00:50:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-30 00:50:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-30 00:50:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-08-05 12:46:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-05 12:48:59 [info] elementor::elementor_updater Started 
2024-08-05 12:48:59 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-05 12:48:59 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-05 12:48:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-06 00:47:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 00:51:55 [info] elementor-pro::elementor_pro_updater Started 
2024-08-06 00:51:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-06 00:51:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-06 00:51:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-25 12:47:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0-dev1',
)]
2024-08-25 12:49:12 [info] elementor::elementor_updater Started 
2024-08-25 12:49:12 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-25 12:49:12 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-25 12:49:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.0-dev1',
)]

PHP: showing 10 of 10PHP: 2024-07-28 16:39:13 [notice X 10][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-29 20:33:02 [notice X 39][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: background_color [array (
  'trace' => '
#0: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1438): Elementor\Conditions :: check()
#3: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1222): Elementor\Controls_Stack -> is_control_visible()
#4: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1263): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-08-02 15:23:10 [error X 1][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php::29] Uncaught TypeError: Argument 2 passed to ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache::add() must be of the type array, string given, called in /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php on line 135 and defined in /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php:29
Stack trace:
#0 /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-cache.php(135): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache-&gt;add(Object(ElementorPro\Modules\ThemeBuilder\Documents\Footer), &#039;&#039;)
#1 /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(321): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Cache-&gt;regenerate()
#2 /home/customer/www/adventurerock.com/public_html/wp-content/plugins [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-06 00:56:18 [notice X 482][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: background_color [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-07 13:57:28 [notice X 156][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-08-13 03:10:09 [notice X 2][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::277] Undefined index: query [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-13 03:10:55 [notice X 4][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::387] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-13 17:43:39 [notice X 1][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-13 18:36:45 [notice X 4][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-15 17:11:53 [notice X 1][/home/customer/www/adventurerock.com/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::48] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Form Builder for MEC: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Elementor Shortcode Builder for MEC: Compatibility not specified
	Elementor Shortcode Designer: Compatibility not specified
	Elementor Single Builder for MEC: Compatibility not specified
	Image Optimizer by Elementor – Compress, Resize and Optimize Images: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by patriciarolda** [comment]
Tried everything! Elementor team please answer. How can I resolve this issue???? Anyone who can help?

**Comment by Eliasdb** [comment]
I also have this issue, so I rolled back to the latest previous version and the mega menu shows up fine again in production. Hope this might help you, too. Even as a temporary workaround.

**Comment by crowlsyong** [comment]
> I also have this issue, so I rolled back to the previous version and the mega menu shows up fine again in production. Hope this might help you, too. Even as a temporary workaround.

What are the steps you took to roll back to the previous version?

**Comment by crowlsyong** [comment]
> > I also have this issue, so I rolled back to the previous version and the mega menu shows up fine again in production. Hope this might help you, too. Even as a temporary workaround.
> 
> What are the steps you took to roll back to the previous version?

[These are the steps to rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/), straight from elementor and very easy to follow. Worked for me. I also disabled auto updates.

**Comment by luke-anykraft** [comment]
![image](https://github.com/user-attachments/assets/a69b983a-2ebe-4d99-98f4-1aa362c98217)
Rolled back and fixed the issue. QA team missed?

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for reaching out! 🙏 

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and **<ins>it's not quite intended for use on live websites.</ins>**

In the most recent release of this Developer Edition plugin, a conflict between the Core version (3.24.0-dev3) and older versions of the Pro plugin has caused an incompatibility in the rendering of the CSS. This should be fixed with the release of the Elementor Core (Free) version 3.24.0, and Elementor Pro version 3.24.0 tomorrow.

### 🧪 Due to the experimental nature of this Developer Edition plugin, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [revert back to a stable version of Elementor](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

Kind regards
