### ISSUE TITLE
⛔ Loop Grid - Post Taxonomy - Alternate Template Bug

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#28653]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When using the loop grid widget, you can't select an alternate template when using the Post Taxonomy template type.

### Steps to reproduce

1. Add Loop Grid widget
2. Choose Post Taxonomy as template type
3. Choose template layout
4. There's no "Apply an alternate template" option

If you go back and select Posts as template type and click the "Apply an alternate template" option. Then click back to Post Taxonomy. There's a glitch/bug. You can now see the Templates sections for Alternate Template but it doesn't work. 

### Expected behavior

1. Add Loop Grid widget
2. Choose Post Taxonomy as template type
3. "Apply an alternate template" should be an option

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.39
	PHP Version: 8.1.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://wickydemo.com/wickydesign
	Home URL: https://wickydemo.com/wickydesign
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	JetEngine
		Version: 3.5.4
		Author: Crocoblock

	JetFormBuilder
		Version: 3.4.2
		Author: Crocoblock

	JetFormBuilder Hierarchical Select
		Version: 1.0.3
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.4
		Author: Crocoblock

	SVG Support
		Version: 2.5.8
		Author: Benbodhi

	Wordfence Security
		Version: 7.11.7
		Author: Wordfence


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Inactive
	Flexbox Container: Active by default
	Grid Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Element Caching: Inactive
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Inactive
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Inactive by default






== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @mcrowell,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Currently, the Loop Grid only allows alternate templates for Posts and Custom Post Types. It doesn't work with Taxonomies yet.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
