### ISSUE TITLE
Recent update brakes my existing side by side buttons. Had to downgrade.

### ISSUE THREAD

**Issue by odapplications** [elementor/elementor#28695]
Hey everyone!

We have great news! 🙌 

### 📢 We're happy to announce that we just released a patch that solves this issue! 🥳 

✅ Feel free to update Elementor and Elementor Pro to version 3.24.1!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

_Originally posted by @nicholaszein in https://github.com/elementor/elementor/issues/28676#issuecomment-2346851750_
            

Just letting you know that its now broken.

**Comment by odapplications** [comment]
If you have issues with the the flex box going to the right with side by side buttons just downgrade from tools it will fix the issue. 
![image](https://github.com/user-attachments/assets/f4cc2d8f-58d9-46a2-a90c-af98171e0c6c)

**Comment by nicholaszein** [comment]
Hello @odapplications!

Thank you for reaching out! 🙏 

We appreciate your feedback and contribution. We've recently released a new patch for Elementor Core that solves your issue.

### Update Elementor Core to version 3.24.2, and Elementor Pro to version 3.24.1. 😉 

While we appreciate your involvement, please remember to always follow our Contribution Guidelines on [How to Report a Bug](https://github.com/elementor/elementor/blob/main/.github/CONTRIBUTING.md#how-to-report-a-bug), so we can properly address and validate it.

When submitting an issue, always use the [Bug Report Form](https://elemn.to/gh-new-bug-report), and save time by posting the required information.

### ⚠️ As a gentle reminder, issues that do not follow our 🐞 Bug Report Guidelines may need to be closed without troubleshooting. 

Thank you for understanding! 🙏

Kind regards
