### ISSUE TITLE
You guys really go against your words. I disabled beta tester yet you again ship unstable work to prod. 

### ISSUE THREAD

**Issue by luke-anykraft** [elementor/elementor#28719]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am not beta tester - disabled.
I turned off automatic updated.
Yet your issues are happening again. 
Why are you launching to prod without testing? 

Related issue: https://github.com/elementor/elementor/issues/28533#issuecomment-2323418258
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/2037e767-0d7e-4496-8318-89deda8ddc66">

### Steps to reproduce

Just check hamberger menus.

### Expected behavior

Prev version worked.
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/b8c411c6-1aa6-4a65-97ef-3a36de2d31bf">

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
No need as you guys don't analyze.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by luke-anykraft** [comment]
This issue has been reported multiple times already by many many many users. Why are you forcing PROD updates with known issues in build? Just mind blowing how I have to roll back over the weekend.

**Comment by nicholaszein** [comment]
Hi @luke-anykraft .

This is not a place to file complaints. Please reach out to Elementor Support instead. We are unable to handle complaints from here.

Thank you for understanding.
