### ISSUE TITLE
Related issue to #28676 ✅🐞 Social Icons Widget load incorrectly 

### ISSUE THREAD

**Issue by chwebagency** [elementor/elementor#28737]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Icons (most notably social share icons) load incorrectly. They seem to load at a font size larger than what is set in the editor. They appear larger as the page loads before the elementor styles / size set in editor is applied. This bug appears related to [issue #28676 which was initially causing the icons to have wrong padding](https://github.com/elementor/elementor/issues/28676). 

The new issue is that they load at a larger size than set in editor. This applies across different sites with different setups including some using containers and others using sections & columns. This issue occurs in versions 3.24 - 3.24.2. It does not occur in version 3.23.3 or earlier.

https://github.com/user-attachments/assets/f315f628-b645-4d34-874d-64ea9945a773

### Steps to reproduce

1. Add social icons to a page.
2. Set size to .9rem or something similarly small.
3. Publish and load page. 

### Expected behavior

1. Icons should load at .9rem.
2. Icons instead load larger then .9rem size css is applied. 
3. Space and overall size of the social widget also seems to be a larger size as the page loads.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	MariaDB Server v10.3.39
WordPress Environment		
Version:	6.6.2

Theme		
Name:	Hello Elementor Child	
Version:	1.0.1	
Author:	Elementor Team	
Child Theme:	Yes	
Parent Theme Name:	Hello Elementor	
Parent Theme Version:	3.1.1	
Parent Theme Author:	Elementor Team
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @chwebagency!

Thank you for reaching out! 🙏

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.
