### ISSUE TITLE
Elementor removes WordPress block styles from the loading queue even if they are used in the sidebar

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#28743]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

If a page is created in Elementor, but a sidebar containing Gutenberg blocks is displayed (the sidebar is created in the new widget editor) - styles of blocks used in the sidebar are not loaded, because Elementor forcibly removes them from the queue for loading https://prnt.sc/xuBCnCVQsGGK.

Just because the page content doesn't contain blocks doesn't mean they aren't in the final output - they may be in the custom header/footer/sidebar.

It would be nice to at least add the https://prnt.sc/Y98FIif_OzR1 filter here so that the theme or other plugins can adjust the loading of block styles (if they need them).

### Steps to reproduce

1. Create a page in Elementor
2. Add some blocks to the sidebar in Appearance - Widgets https://prnt.sc/QhVdSYY8J7bA.
3. Display the sidebar on the page (by connecting it in the theme settings or at least adding it to the page with Elementor's Sidebar widget https://prnt.sc/h5FyZSkv4CeQ ).
4. open the developer debug panel and check if the WordPress styles ‘wp-block-library’ https://prnt.sc/RmeEmBx8e6qp are loaded.

### Expected behavior

Elementor shouldn't disable loading block styles from WordPress just because they aren't in the page content! Or at least run your solution through a filter so that other plugins/themes can tweak this

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @VadymPogorelov.

This is not a bug. This is a setting you can enable or disable. It's meat to improve performance if you're not going to use the Block editor. If you are, then you can disable this setting.

Go to your WordPress Dashboard > Elementor > Settings > Performance and make sure the "Optimized Gutenberg Loading" option is set to "Disable".

Next time, please check the documentation before submitting your issue. This is more of a Support Question that could have been solved by consulting the Help Center.

https://elementor.com/help/optimized-gutenberg-loading/

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards
