### ISSUE TITLE
✅ ❌ 🔗 🐞 BIG LONG NOT FIXED ISSUE, GAPS IS NOT EXPORTING (Duplicate of #24111)

### ISSUE THREAD

**Issue by HODAKdev** [elementor/elementor#28861]
### Prerequisites

- [x] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

https://github.com/elementor/elementor/issues/24111

### Steps to reproduce

https://github.com/elementor/elementor/issues/24111

### Expected behavior

https://github.com/elementor/elementor/issues/24111

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
https://github.com/elementor/elementor/issues/24111
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @HODAKdev, 

Please do not post duplicates. This only pushes the duplicated issue down in the backlog. Please respect our [Contribution Guidelines](https://elemn.to/gh-contributing) and [Code of Conduct](https://elemn.to/gh-code-of-conduct).

Thank you for your contribution.

**Comment by nicholaszein** [comment]
Hi there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved with the release of Elementor v3.26.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
