### ISSUE TITLE
❌ Elementor Debugger

### ISSUE THREAD

**Issue by Abledry** [elementor/elementor#28930]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Elementor Debugger, this needs to get fix asap 

### Steps to reproduce

Elementor Debugger

### Expected behavior

Elementor Debugger

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Elementor Debugger
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Abledry.

Unfortunately, you did not share the information that is required in the Bug Report Form. For this reason we are unable to analyze and validate your issue.

### ⚠️ As a gentle reminder, issues that do not follow our 🐞 Bug Report Guidelines may need to be closed without troubleshooting. 

Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏
