### ISSUE TITLE
homepage of site is not loading

### ISSUE THREAD

**Issue by Focalinweb** [elementor/elementor#29042]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When I open my website the homepage of the website does not get loaded even after trying may times 
![Screenshot (18)](https://github.com/user-attachments/assets/31d614f3-eda2-4792-894f-4640fc5a00e3)

### Steps to reproduce

search for modnexus.in 
the site will open but there wont be any content loaded on home page

### Expected behavior

The home page should load and show content

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Server Environment		
Operating System:	Linux	
Software:	nginx	
MySQL version:	MariaDB Server v10.6.17	
PHP Version:	8.1.30	
PHP Memory Limit:	512M	
PHP Max Input Vars:	6144	
PHP Max Post Size:	2047M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.6.2	
Site URL:	https://modnexus.in	
Home URL:	https://modnexus.in	
WP Multisite:	No	
Max Upload Size:	2 GB	
Memory limit:	512M	
Max Memory limit:	512M	
Permalink Structure:	/%year%/%monthnum%/%day%/%postname%/	
Language:	en_US	
Timezone:	Asia/Kolkata		
Debug Mode:	Inactive	
Theme		
Name:	AIHub Child	
Version:	1.0	
Author:	Liquid Themes	
Child Theme:	Yes	
Parent Theme Name:	AIHub	
Parent Theme Version:	1.3.4	
Parent Theme Author:	Liquid Themes	
User		
Role:	administrator	
WP Profile lang:	en-US	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36	
Active Plugins		
AIHub Core - 1.3.4	By Liquid Themes	
Akismet Anti-spam: Spam Protection - 5.3.3	By Automattic - Anti-spam Team	
All in One SEO - 4.7.3	By All in One SEO Team	
Crowdsignal Forms - 1.7.2	By Automattic	
Crowdsignal Polls & Ratings - 3.1.2	By Automattic, Inc.	
Elementor - 3.25.0-dev3	By Elementor.com	
Elementor Beta (Developer Edition) - 1.1.3	By Elementor.com	
Elementor Header & Footer Builder - 1.6.44	By Brainstorm Force, Nikhil Chavan	
Gutenberg - 19.4.0	By Gutenberg Team	
Image Optimizer - Compress, Resize and Optimize Images - 1.5.4	By Elementor.com	
Jetpack - 14.0-a.7	By Automattic	
Layout Grid - 1.8.4	By Automattic	
MetForm - 3.9.0	By Wpmet	
Page Optimize - 0.5.5	By Automattic
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Goodmasterops** [comment]
![image](https://github.com/user-attachments/assets/a5028688-f31d-4d60-981e-2a5b630ea883)
hHmm,, website working
