### ISSUE TITLE
❌ Invalid Issue: JavaScript Exceptions

### ISSUE THREAD

**Issue by mehrazmorshed** [elementor/elementor#29163]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

[
    {
        "message": "TypeError: Cannot read properties of undefined (reading 'value')\n    at child.initTemplatesImport (/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.25.3:3:52562)\n    at child.T.each.L.<computed> [as initTemplatesImport] (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:58882)\n    at child.onInit (/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.25.3:3:51091)\n    at child.T.each.L.<computed> [as onInit] (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:58882)\n    at child.Module.trigger (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:58650)\n    at child.T.each.L.<computed> [as trigger] (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:58882)\n    at init (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:58994)\n    at child.Module (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:59010)\n    at child [as constructor] (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:59242)\n    at new child (/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.3:2:59242)",
        "trace": null,
        "code": null
    }
]

![Screenshot from 2024-11-03 10-57-15](https://github.com/user-attachments/assets/db7260b8-9e79-4392-b6eb-32fa06963c22)

### Steps to reproduce

**JavaScript Exceptions in:**
1. /wp-admin/edit.php?post_type=elementor_library&page=e-floating-buttons
2. /wp-admin/edit.php?post_type=elementor_library&page=popup_templates
3. /wp-admin/edit-tags.php?taxonomy=elementor_library_category&post_type=elementor_library

### Expected behavior

**There should be no JavaScript Exception in:**
1. Templates → Floating Elements
2. Templates → Popups
3. Templates → Categories

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Elementor plugin version: 3.25.3
WordPress version: 6.6.2
PHP version: 8.1.12
MySQL version: 10.6.10
PHP memory limit: 512M
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @mehrazmorshed, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔍 **Search Before Posting:** Before creating a new Bug Report, please [search for similar issues](https://github.com/elementor/elementor/issues/) to prevent creating duplicates.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue following these guidelines. 😉 

Best regards
