### ISSUE TITLE
📚 Regenerating CSS via CLI does not regenerate Custom Font styles

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#29227]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When using `wp elementor flush_css --regenerate` the `@font-face` styles are missing from the generated CSS.

The fonts are added locally, directly in Elementor.

Here's a diff showing the kit stylesheet generated with `wp elementor flush_css --regenerate` (top portion) vs a natural creation of the stylesheet by visiting the page (bottom portion). Note how the `@font-face` parts are missing from the top portion:

![Screenshot 2024-11-14 152639](https://github.com/user-attachments/assets/0d916f07-f34d-4a67-85e2-670dee85f407)

### Steps to reproduce

1. Add and use custom fonts on a page
2. `wp elementor flush_css --regenerate`
3. Custom font not applied, CSS is missing `@font-face`

### Expected behavior

Stylesheets should include the CSS to load the font

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: Ubuntu 22.04 v10.6.18
	PHP Version: 8.2.24
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://example.local.test/wp
	Home URL: https://example.local.test
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /news/%postname%/
	Language: en_US
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.2
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Editor Top Bar: Inactive
	Element Caching: Inactive
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive


== Log ==
	
Log: showing 20 of 382024-11-05 13:18:32 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:36 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:45 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:48 [info] elementor-pro::elementor_pro_updater Started 
2024-11-05 13:18:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-05 13:18:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-05 13:18:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]
2024-11-05 13:18:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]

PHP: showing 4 of 4PHP: 2024-11-05 13:18:45 [warning X 1][../plugins/elementor/core/files/manager.php::112] unlink(../uploads/elementor/css/post-3118.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-05 13:19:57 [warning X 44][../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-11-05 13:20:00 [error X 1][../plugins/elementor-pro/modules/screenshots/module.php::229] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../plugins/elementor-pro/modules/screenshots/module.php:229
Stack trace:
#0 ../plugins/elementor-pro/modules/screenshots/module.php(264): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode()
#1 ../plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 ../plugins/elementor-pro/core/modules-manager.php(98): Elementor\Core\Base\Module::instance()
#3 ../plugins/elementor-pro/plugin.php(366): ElementorPro\Core\Modules_Manager->__construct()
#4 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(324): ElementorPro\Plugin->on_elementor_init()
#5 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 ../plugins/elementor/includes/plugin.php(685): do_action()
#8 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(324): Elementor\Plugin->init()
#9 /home/jamie/projects/example.local.test/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /home/jamie/projects/example.local.test/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /home/jamie/projects/example.local.test/web/wp/wp-settings.php(700): do_action()
#12 /home/jamie/projects/example.local.test/web/wp-config.php(9): require_once('...')
#13 /home/jamie/projects/example.local.test/web/wp/wp-load.php(55): require_once('...')
#14 /home/jamie/projects/example.local.test/web/wp/wp-blog-header.php(13): require_once('...')
#15 /home/jamie/projects/example.local.test/web/index.php(6): require('...')
#16 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-05 13:28:11 [warning X 1][../plugins/elementor-pro/modules/posts/skins/skin-content-base.php::271] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @jamieburchell!

Thank you for bringing this to our attention.

From our initial assessment, this is the expected behavior. Once you visit the page the CSS will be generated as expected. This is because Elementor will only load the custom font CSS (`@font-face`) if the font in question is in use on the page. Hence why you only saw it generated after the page was visited.

We will investigate it further to ensure the custom font styles are always loaded when needed.

Kind regards

**Comment by jamieburchell** [comment]
Thanks @nicholaszein. The `--regenerate` switch is a bit useless if it's not going to generate the complete kit CSS ahead of time.

**Comment by nicholaszein** [comment]
@jamieburchell,

Elementor doesn't regenerate CSS when you trigger the CSS regeneration, it only removes the old CSS and signals for the new CSS to be regenerated on page view. If we regenerated the CSS on triggering we could potentially take the site into a halt as this is a resource-intensive task.

**Comment by jamieburchell** [comment]
@nicholaszein That's not actually correct.

`wp elementor flush_css` removes the CSS

`wp elementor flush_css --regenerate` removes and then regenerates the CSS files (minus the `@font-face`)

**Comment by nicholaszein** [comment]
@jamieburchell!

I just confirmed, Custom Font (and Icon) stylesheets are not included in the CSS regeneration via CLI. They will be generated and enqueued once a document using them is viewed, or in other words, on demand. This is the intended behavior and we have no plans to include them in the CLI argument.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Comment by jamieburchell** [comment]
There's little point in having the `--regenerate` switch if it's not going to include all the CSS ahead of time IMO. Being able to regenerate in this way could have solved long a standing [issue](https://github.com/elementor/elementor/issues/27320) with broken pages caused by missing CSS after clearing full page caches.

**Comment by nicholaszein** [comment]
@jamieburchell,

once the page is viewed, the CSS should be generated automatically (before the page is rendered), therefore caching should have no negative effect on rendering the pages with Custom Font styles. Unless the cache being used stores copies of pages without triggering the page view. Then this is more of a problem with the cache solution being implemented than with Elementor.

**Comment by jamieburchell** [comment]
That's the theory, but unfortunately in practice there are issues with pages rendering without styles after regenerating CSS (removing the files only) and then immediately clearing all caches. There's also the issue of stylesheets loading in the footer initially on first page load. Anyway both issues have been raised elsewhere.

**Comment by nicholaszein** [comment]
@jamieburchell,

the functionality of this feature has no correlation with the issues you're mentioning here. As explained, this is how Custom Font stylesheets are handled, and using the CLI command does not include them. We cannot control how cache is handled by other plugins or servers, if you use Elementor without cache, or even if you use it with properly configured cache solutions (WP Rocket, and Elementor Hosting being two valid examples), this is not a problem.

Since this is unrelated, I'm closing the comments to avoid confusion.

Thank you for contributing! 🙏 

Kind regards
