### ISSUE TITLE
⛔ Display Condition's Singular -> Page inclusion doesn't work for WooCommerce shop page

### ISSUE THREAD

**Issue by nviitala** [elementor/elementor#29244]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When I add a display condition for a template as:
Include -> WooCommerce -> Shop Page
The template becomes visible on the Shop Page as it should.

However, if I add the display condition via:
Include -> Singular -> Pages -> Shop (the exact same shop page)
The template isn't visible on the Shop page.

This causes issues for multilingual sites, where the only way to translate Elementor's Floating Elements is to just create the same template multiple times for different languages.

**Moreover, the Display Condition options could include also a current url match, where the admins could check with regex the domain or the url path. This would be beneficial in many scenarios, including when localizing the site. Another condition match addition could be to check if get_locale() matches to XX. It would be beneficial if these options would be added to the single element's display conditions also.**

### Steps to reproduce

1. Create a WooCommerce shop pages in different languages
2. Create an Elementor template (eg. Floating Elements -> Floating Bar). 
3. Set the display condition via Include -> Singular -> Pages -> The title of one of the localized shop pages
4. Visit the shop page, the floating bar isn't visible

### Expected behavior

The template/floating bar should be visible on the shop page also in the scenario where it is set to be included via Singular -> Pages.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.22.1
	MySQL version: mariadb.org binary distribution v10.10.3-MariaDB-1:10.10.3+maria~ubu2204-log
	PHP Version: 8.2.1
	PHP Memory Limit: 512M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 72M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: http://nyytit.test
	Home URL: http://nyytit.test
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /artikkelit/%postname%/
	Language: fi
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Aelia Currency Switcher for WooCommerce
		Version: 5.1.11.240910
		Author: Aelia

	Aelia Foundation Classes for WooCommerce
		Version: 2.6.0.241007
		Author: Aelia

	All-in-One WP Migration
		Version: 7.87
		Author: ServMask

	All-in-One WP Migration URL Extension
		Version: 2.73
		Author: ServMask

	Bugsnag Error Monitoring
		Version: 1.6.3
		Author: Bugsnag Inc.

	Connect Polylang for Elementor
		Version: 2.4.5
		Author: Creame

	Discount Rules Core
		Version: 2.6.6
		Author: Flycart

	Discount Rules PRO 2.0
		Version: 2.6.5
		Author: Flycart

	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.2
		Author: Elementor.com

	F4 Shipping Phone and E-Mail for WooCommerce
		Version: 1.0.19
		Author: FAKTOR VIER

	FunnelKit Automations
		Version: 3.3.3
		Author: FunnelKit

	FunnelKit Automations Connectors
		Version: 3.1.1
		Author: FunnelKit

	FunnelKit Automations Pro
		Version: 3.3.0
		Author: FunnelKit

	FunnelKit Cart for WooCommerce
		Version: 1.7.1
		Author: FunnelKit

	FunnelKit Funnel Builder
		Version: 3.6.2
		Author: FunnelKit

	FunnelKit Funnel Builder Pro
		Version: 3.6.1
		Author: FunnelKit

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	Klarna Order Management for WooCommerce
		Version: 1.9.2
		Author: klarna, krokedil

	Klarna Payments for WooCommerce
		Version: 3.8.1
		Author: klarna

	Metorik Helper
		Version: 2.0.7
		Author: Metorik

	OGOShip API for WooCommerce
		Version: 3.8.0
		Author: OGOShip

	Payment Plugins for PayPal WooCommerce
		Version: 1.0.53
		Author: Payment Plugins, support@paymentplugins.com

	Paytrail for WooCommerce
		Version: 2.1.2
		Author: Paytrail

	Polylang for WooCommerce
		Version: 2.1.1
		Author: WP SYNTEX

	Polylang Pro
		Version: 3.6.5
		Author: WP SYNTEX

	SVG Support
		Version: 2.5.8
		Author: Benbodhi

	WooCommerce
		Version: 9.3.3
		Author: Automattic

	WooCommerce Noutopistehaku
		Version: 1.8.2
		Author: Lauri Karisola / markup.fi

	WooCommerce Stripe Gateway
		Version: 8.8.1
		Author: Stripe

	WP Mail SMTP Pro
		Version: 4.2.0
		Author: WP Mail SMTP

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.8
		Author: Team Yoast

	Yoast SEO: WooCommerce
		Version: 16.1.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 22.1
		Author: Team Yoast


== Must-Use Plugins ==
	Code Profiler (mu-plugin)
		Version: 1.0
		Author: Jerome Bruandet

	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	Container: Active by default
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 422024-08-19 11:59:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-10-15 20:18:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.4',
)]
2024-10-15 20:18:17 [info] elementor-pro::elementor_pro_updater Started 
2024-10-15 20:18:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-15 20:18:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-15 20:18:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.4',
)]
2024-10-15 20:18:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.4',
)]
2024-10-15 20:18:53 [info] elementor::elementor_updater Started 
2024-10-15 20:18:53 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-15 20:18:53 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-15 20:18:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.7',
)]
2024-11-06 16:51:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.4',
)]
2024-11-06 16:51:47 [info] elementor::elementor_updater Started 
2024-11-06 16:51:47 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-06 16:51:47 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-06 16:51:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.4',
)]
2024-11-06 16:52:27 [info] elementor-pro::elementor_pro_updater Started 
2024-11-06 16:52:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-06 16:52:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-06 16:52:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.2',
)]

JS: showing 1 of 1JS: 2024-11-11 06:48:29 [error X 1][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-hooks&ver=6.6.2:2:28760] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==
	
	Connect Polylang for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @nviitala,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's why:
When you set a page to be your Shop page in WordPress, it stops being loaded as a Singular page, and start being loaded as an Archive page. Archive pages in WordPress behave differently, and can't be edited directly. This is why Elementor Pro has the WooCommerce Builder, to allow you to create Product Archive templates and apply them to the Shop page. This is how you should use the Theme Builder to build your Shop pages. 

If you need to create more than one template for the same archive, you can do that using one of the extensions provided by most translation plugins such as WPML, Polylang, and Translatepress to create different languages for the same archive template.

This is not an Elementor limitation, but a WordPress limitation. You should consider changing your method to acomodate this behavior.

Here's an article covering this specific case:
https://elementor.com/help/the-content-area-was-not-found-error/#:~:text=edit%20the%20page.-,Error%20appears%20on%20WooCommerce%20pages,-If%20you%20are

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

Next time, please check one of these channels before submitting your issue:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
