### ISSUE TITLE
⛔ 🧩 Cannot Preview Specific Post ID in Elementor Preview Mode when using custom implementation

### ISSUE THREAD

**Issue by javothemes** [elementor/elementor#29277]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

We have encountered an issue where the Elementor preview mode consistently loads the latest post instead of the specified post ID. We have created a custom "Apply & Preview" button ( just like elementor pro, apply & preview) that is intended to preview a specific post ID in Elementor, but despite our AJAX implementation and multiple filter attempts, only the latest post is displayed in preview mode.

### Steps to reproduce

**Steps to Reproduce:**
1. Create a custom "Apply & Preview" button in Elementor that should fetch a post using a specific post ID.
2. Click the button, which triggers an AJAX request, sending the template ID and post ID.
3. Use the elementor/frontend/the_content and elementor/frontend/builder_content_data filters to try forcing the content of the specified post ID in Elementor's preview mode.

**Expected Behavior:**
Clicking "Apply & Preview" should display the content of the post with the specified post ID, not the latest post.

**Observed Behavior:**
Regardless of the specified post ID, Elementor always displays the latest post in preview mode.

**Code and Filters Used:**
We have tried the following code snippets and filters to force Elementor to load the specified post ID in preview mode. None of these approaches have successfully resolved the issue:

**Custom AJAX Handler:**
```
add_action('wp_ajax_custom_apply_preview', 'custom_apply_preview_handler');
add_action('wp_ajax_nopriv_custom_apply_preview', 'custom_apply_preview_handler');

function custom_apply_preview_handler() {
    $template_id = intval($_POST['template_id']);
    $preview_id = intval($_POST['preview_id']);
    
    wp_cache_flush();

    if (!$template_id || !get_post($template_id) || !$preview_id || !get_post($preview_id)) {
        wp_send_json_error('Invalid template or preview ID');
        return;
    }

    $template_url = add_query_arg(
        [
            'elementor-preview' => $template_id,
            'preview_post_id' => $preview_id,
            'ver' => time(),
        ],
        get_permalink($template_id)
    );

    wp_send_json_success(['template_url' => $template_url]);
}

```
**Elementor Content Filters:**
```

add_filter('elementor/frontend/builder_content_data', function ($data, $post_id) {
    if (isset($_GET['preview_post_id']) && intval($_GET['preview_post_id']) === $post_id) {
        add_filter('elementor/frontend/the_content', 'custom_filter_the_content');
    }
    return $data;
}, 10, 2);

function custom_filter_the_content($content) {
    if (is_preview() && isset($_GET['preview_post_id'])) {
        $post_id = intval($_GET['preview_post_id']);
        if ($post_id && $post = get_post($post_id)) {
            setup_postdata($post);
            return apply_filters('the_content', $post->post_content);
        }
    }
    return $content;
}

```
**Additional Template Redirect:**
```

add_action('template_redirect', function () {
    if (isset($_GET['preview_post_id']) && is_preview() && class_exists('\ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document')) {
        $post_id = intval($_GET['preview_post_id']);
        $preview_manager = \ElementorPro\Modules\ThemeBuilder\Module::instance()->get_preview_manager();
        $preview_manager->switch_to_preview_query();
    }
});
```

**Troubleshooting Steps Taken:**
Tested multiple filters, including elementor/frontend/the_content and elementor/frontend/builder_content_data.
Attempted using template_redirect with custom preview manager calls.
Verified that the AJAX request sends the correct post ID to the backend.
Confirmed that cache is cleared before each preview load.

### Expected behavior

Clicking "Apply & Preview" should display the content of the post with the specified post ID, not the latest post.
The preview should load the content of the post with the ID specified by the "preview_post_id" parameter in the URL, instead of defaulting to the latest post.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
    Operating System: Linux
    Software: Apache/2.4.57 (Debian)
    MySQL version: MySQL Community Server - GPL v8.3.0
    PHP Version: 8.1.27
    PHP Memory Limit: 1024M
    PHP Max Input Vars: 1000
    PHP Max Post Size: 256M
    GD Installed: Yes
    ZIP Installed: Yes
    Write Permissions: All right
    Elementor Library: Connected

== WordPress Environment ==
    Version: 6.6.2
    Site URL: http://localhost
    Home URL: http://localhost
    WP Multisite: No
    Max Upload Size: 256 MB
    Memory limit: 1024M
    Max Memory limit: 512M
    Permalink Structure: /%postname%/
    Language: en_US
    Timezone: UTC
    Debug Mode: Active

== Theme ==
    Name: Custom Theme
    Version: 0.0.9.178
    Child Theme: No

== User ==
    Role: administrator
    WP Profile lang: en-US
    User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
    Advanced Cron Manager (v2.5.10)
    Advanced Database Cleaner (v3.1.5)
    Contact Form 7 (v5.9.8)
    Debug Bar (v1.1.6)
    Debug Log Helper (v1.5.3)
    Debug Log Manager (v2.3.3)
    Elementor (v3.25.4)
    Elementor Pro (v3.25.2)
    Image Optimizer (v1.5.4)
    Javo Core (v2.0.2.415)
    Custom Popularity Enhancer (v1.0.0)
    Query Monitor (v3.16.4)
    WooCommerce (v9.3.3)
    WP Debugging (v2.11.24)
    WP Mail Logging (v1.13.1)
    WP Mail SMTP (v4.1.1)

== Elements Usage ==
    page : 0
        container : 15
        divider : 2
        heading : 2
        (other elements usage redacted for brevity)

== Settings ==
    cpt_support: post, page
    allow_tracking: yes
    font_display: swap

== Features ==
    Custom Fonts: 0
    Custom Icons: 0

== Integrations ==
    woocommerce: Active

== Elementor Experiments ==
    Improved CSS Loading: Inactive by default
    Inline Font Icons: Inactive
    Additional Custom Breakpoints: Active by default
    (other experiments status redacted for brevity)

== Log ==
    Log: showing 20 of 25
    2024-10-30 17:46:59 [info] Elementor data updater process completed.
    (additional logs redacted for brevity)

== PHP Errors ==
    Showing 7 of 7
    PHP: 2024-10-23 12:35:43 [error X 2] Uncaught TypeError in Elementor controls stack.
    (additional errors redacted for brevity)

== JS Errors ==
    Showing 10 of 10
    JS: 2024-10-23 03:49:34 [error X 10] Cannot read properties of null in elementor-editor.js
    (additional JS errors redacted for brevity)

== Elementor - Compatibility Tag ==
    Elementor Pro: Compatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @javothemes!

Thank you for reaching out! 🙏 

Unfortunately, we are unable to provide support for custom code such as the one you've implemented here. By default, if the editor can't find a valid ID, it will fallback to the last published document that was edited with Elementor, which is what is happening in your case.

If you wish to get in touch with our team, you might consider becoming a partner, you can apply to join the [Partnership Program](https://elemn.to/partnerships).

For now, that's all we can help you with.

Best regards
