### ISSUE TITLE
🔗 🚀 Feature Request: Please Introduce Table Builder (Duplicate of #1342)

### ISSUE THREAD

**Issue by gbpmedia** [elementor/elementor#2931]
Hello,

Please introduce a table builder, the kind that Thrive Architect has. It's a pain to use a separate plugin just to build tables. Its very important.

Thanks
Ahmed

**Comment by bainternet** [comment]
I merged this issue with another issue #1342 on the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
