### ISSUE TITLE
⛔ 🛟 Support Request: Deactivating the setting 'landing pages' in Elementor takes pages to 404

### ISSUE THREAD

**Issue by Priyaqb** [elementor/elementor#29455]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Elementor Version : 3.25.10
Elementor Pro Version : 3.25.4

I deactivated the 'landing pages' in Elementor settings and then reverted back to active state which is default. But now I am not able to access any of my landing pages. 

### Steps to reproduce

1. Go to Elementor -> Settings -> Features
2. Change Landing Pages to Inactive and save changes.
3. Revert it back to Default.
4. All the main landing pages redirects to 404.

### Expected behavior

1. All landing pages should open normally.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Windows

== WordPress Environment ==
	Version: 6.7
	Site URL: https://domain.com
	Home URL: https://domain.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Asia/Tehran
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.10
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com


== Features ==
	

== Integrations ==
	


== Elementor Features ==
	Optimized Markup: Default
	Landing Pages: Default
	Nested Elements: Inactive
	Element Caching: Default
	Menu: Default
	Inline Font Icons: Active
        Additional Custom Breakpoints: Default
        Container: Inactive
        Upgrade Swiper Library: Default
        Optimized Control Loading: Default
        Default to New Theme Builder: Default
        Header & Footer: Default
        Editor Top Bar: Default

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Priyaqb,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

In your case all you need to do is to Flush the Rewrite Rules by going to your WordPress **`Dashboard`** > **`Settings`** > **`Permalinks`** and clicking on `Save Chagnes` a couple of times and your issue should be resolved. 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
