### ISSUE TITLE
⛔ 📚 🧩 🛟 Support Request: Populate the value of the button clicked to the form's field

### ISSUE THREAD

**Issue by Rehan507** [elementor/elementor#29477]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I’m working on an Elementor setup where multiple buttons are displayed on a page, each with a unique value (e.g., "Option 1," "Option 2," etc.). I want the value of the button clicked to automatically populate a specific field in an Elementor form.

**Here’s the workflow I’m aiming for:**

- A user clicks on one of the buttons.
- The value of the clicked button is passed to a hidden or visible field in the Elementor form.(in my case its select field)
- The user can then submit the form with the button’s value included as part of the form data.

Is there a built-in way to achieve this functionality in Elementor, or would it require custom JavaScript? If so, could you provide guidance on the best approach to implement this?

### Steps to reproduce

- A user clicks on one of the buttons.
- The value of the clicked button is passed to a hidden or visible field in the Elementor form.(in my case its select field)
- The user can then submit the form with the button’s value included as part of the form data.

### Expected behavior

- The issue to be resolved
- Provide code/guidance in case if its not possible in elementor(as of now)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>
```txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.40
	PHP Version: 8.2.26
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 10009
	PHP Max Post Size: 5120M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://myclinigen.com
	Home URL: https://myclinigen.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.11.2
		Author: Activity Log Team

	Broken Link Checker
		Version: 2.4.1
		Author: WPMU DEV

	Buttonizer - Smart Floating Action Button
		Version: 3.4.7
		Author: Buttonizer

	Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd
		Version: 6.18.12
		Author: SeedProd

	Elementor
		Version: 3.25.10
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com

	ElementsKit Lite
		Version: 3.3.2
		Author: Wpmet

	Essential Addons for Elementor
		Version: 6.0.11
		Author: WPDeveloper

	EWWW Image Optimizer
		Version: 7.9.1
		Author: Exactly WWW

	Happy Elementor Addons
		Version: 3.14.1
		Author: Leevio

	Jetpack
		Version: 14.0
		Author: Automattic

	Popup Builder - Create highly converting, mobile friendly marketing popups.
		Version: 4.3.5
		Author: Looking Forward Software Incorporated.

	Really Simple Security
		Version: 9.1.3
		Author: Really Simple Security

	UpdraftPlus - Backup/Restore
		Version: 1.24.11
		Author: TeamUpdraft, DavidAnderson

	WPCore Plugin Manager
		Version: 1.9.2
		Author: Stuart Starr

	WP File Manager
		Version: 8.0
		Author: mndpsingh287

	WPS Hide Login
		Version: 1.9.17.1
		Author: WPServeur, NicolasKulka, wpformation


== Elements Usage ==
	
	footer : 1
		divider : 1
		heading : 6
		icon-list : 4
		social-icons : 1
		text-editor : 1
		theme-site-logo : 1
	header : 1
		button : 1
		container : 4
		nav-menu : 1
		theme-site-logo : 1
	popup : 1
		container : 1
		divider : 2
		form : 1
		heading : 1
	wp-page : 7
		button : 23
		container : 123
		divider : 6
		form : 2
		heading : 47
		icon-box : 3
		icon-list : 4
		image : 32
		image-box : 3
		slides : 1
		spacer : 1
		star-rating : 3
		testimonial : 3
		text-editor : 36
	floating-buttons : 0
		contact-buttons : 1
		container : 1


== Settings ==
	
	cpt_support: post, page, popupbuilder
	allow_tracking: yes
	font_display: swap
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Active
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Active
	Elementor Home Screen: Active by default
	Landing Pages: Active
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Active
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Active


== Log ==
	
[redacted by moderation]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible
	Happy Elementor Addons: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible
	Happy Elementor Addons: Compatible

```
</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @Rehan507!

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

We are unable to provide support for custom or 3rd-party code. We have an API and Developers Documentation that you can use to create your customization. We cannot provide you with custom code. Please, don't use the bug report form to request assistance. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

You can find our documentation for developers in [https://developers.elementor.com](https://developers.elementor.com).


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
