### ISSUE TITLE
❌ 🧩 📚 [3.26.0-beta3] The removal of `elementor/core/schemes/color.php` is causing a critical compatibility issue

### ISSUE THREAD

**Issue by strategio** [elementor/elementor#29520]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I tested Elementor `3.26.0-beta3` with WPML and the Elementor editor is broken and completely unusable because the WPML Language Switcher widget is using the class `Elementor\Core\Schemes\Color` and it causing a fatal error.

```
[06-Dec-2024 17:19:34 UTC] PHP Fatal error:  Uncaught Error: Class 'Elementor\Core\Schemes\Color' not found in /shared/httpd/wpml/htdocs/wp-content/plugins/sitepress-multilingual-cms/addons/wpml-page-builders/classes/Integrations/Elementor/LanguageSwitcher/WidgetAdaptor.php:156
Stack trace:
#0 /shared/httpd/wpml/htdocs/wp-content/plugins/sitepress-multilingual-cms/addons/wpml-page-builders/classes/Integrations/Elementor/LanguageSwitcher/Widget.php(50): WPML\PB\Elementor\LanguageSwitcher\WidgetAdaptor->registerControls()
#1 /shared/httpd/wpml/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2386): WPML\PB\Elementor\LanguageSwitcher\Widget->register_controls()
#2 /shared/httpd/wpml/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(1050): Elementor\Controls_Stack->init_controls()
#3 /shared/httpd/wpml/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(569): Elementor\Widget_Base->init_controls()
#4 /shared/httpd/wpml/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(184): Elementor\Contr in /shared/httpd/wpml/htdocs/wp-content/plugins/sitepress-multilingual-cms/addons/wpml-page-builders/classes/Integrations/Elementor/LanguageSwitcher/WidgetAdaptor.php on line 156
```

### Steps to reproduce

1. Install, activate and setup Elementor `3.26.0-beta3`
2. Install, activate and setup WPML Core + WPML String Translation (latest versions)
3. Create a new page and edit it with the Elementor editor

=> The left side bar with the available widgets cannot be rendered and the whole editor is lock.

### Expected behavior

The Elementor editor should still be usable.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
This is system agnostic.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by strategio** [comment]
I've ran some tests and it seems that just restoring this specific class is enough to avoid the fatal error.

Then, the Elementor editor works fine.

Finally, the Language Switcher widget works also fine except that the widget setting toggles are not rendered correctly after reloading the Elementor editor. But it has no effect the widget which keeps the right settings.

I believe this is a fair short-term solution.

I've prepared a PR for that.
https://github.com/elementor/elementor/pull/29521

**Comment by nicholaszein** [comment]
Hello @strategio.

Thank you for reaching out.

Please, follow the requirements in the Bug Report Form, and provide the full Elementor System Info. This field is **not optional**. The System Info Contains crucial information that will allow our QA team to test the issue on their environments without going back and forward with you. Not sharing this crucial piece of information wastes a lot of time.

For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

I will get back to you with the subject of this issue on another comment. I see you also submitted a PR.

Please, update your issue with the required information.

Thank you

**Comment by strategio** [comment]
@rami-elementor, please consider this request.

**Comment by nicholaszein** [comment]
As discussed directly,

the **Schemes** method used by WPML was deprecated in version 3.0 released in 2020, and replaced by **Globals**.

Elementor postponed the removal of these methods multiple times in the past, including in July 2023, giving developers plenty of time to update their codebase.

For this reason, we are unable to postpone it further.

I'm closing this issue as it's not a bug.

Regards
