### ISSUE TITLE
⛔ 📚 🚀 Feature Request: Provide a way to add Nested Repeater controls (Repeater inside a Repeater)

### ISSUE THREAD

**Issue by websumon** [elementor/elementor#2955]
[Screensort](https://ibb.co/mK3dEm)
I want to add a repeater field under the repeater in custom elementor element. Is it possible? This is my code.
```php
		$this->add_control(
			'tabs',
			[
				'label' => __( 'Tabs Items', 'elementor' ),
				'type' => Controls_Manager::REPEATER,
				'default' => [
					[
						'tab_title' => __( 'Tab #1', 'elementor' ),
						'tab_content' => __( 'I am tab content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.', 'elementor' ),
					],
					[
						'tab_title' => __( 'Tab #2', 'elementor' ),
						'tab_content' => __( 'I am tab content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.', 'elementor' ),
					],
				],
				'fields' => [
					[
						'name' => 'tab_title',
						'label' => __( 'Title & Content', 'elementor' ),
						'type' => Controls_Manager::TEXT,
						'default' => __( 'Tab Title', 'elementor' ),
						'placeholder' => __( 'Tab Title', 'elementor' ),
						'label_block' => true,
					],
					[
						'name' => 'tab_content',
						'label' => __( 'Content', 'elementor' ),
						'default' => __( 'Tab Content', 'elementor' ),
						'placeholder' => __( 'Tab Content', 'elementor' ),
						'type' => Controls_Manager::WYSIWYG,
						'show_label' => false,
					],

				],
				'title_field' => '{{{ tab_title }}}',
			]
		);
```

**Comment by bainternet** [comment]
@websumon 

Sadly the Repeater controls cannot support a nested repeater.

Maybe we will look at it in the future if we see a large demand for it.

**Comment by soyket** [comment]
This is highly needed actually !

**Comment by Ataurr** [comment]
+1

**Comment by ArekZw** [comment]
+1

**Comment by mademan12** [comment]
+1

**Comment by fikonorbert** [comment]
+1

**Comment by RajuJeelaga** [comment]
This feature very much needed in complex designs for the widgets

**Comment by gerard-cuadras** [comment]
+1, need this

**Comment by mdjwel** [comment]
What is the way to solve the nested repeater issue?

**Comment by Fiestus** [comment]
+1

**Comment by phamtungpth** [comment]
+1

**Comment by ideasandpixels** [comment]
+1 Would love this -- small change that adds so much power.

**Comment by nayem-xpeedstudio** [comment]
Yes It will be use full

**Comment by echtweit** [comment]
+1

**Comment by Raaaa86** [comment]
+1

**Comment by TinBoyko** [comment]
+1

**Comment by Sharifur** [comment]
we need nested repeater feature badly

**Comment by ohid** [comment]
we need this feature badly

**Comment by Tripples** [comment]
+1

**Comment by shuvombm02** [comment]
This feature very much needed. Please, add this feature.

**Comment by samadbau77** [comment]
sometimes I feel the  feature very much. Please, add this feature.

**Comment by DeoThemes** [comment]
+1

**Comment by aktarujjman** [comment]
Nested Repeater is needed

**Comment by gloim** [comment]
> 
> 
> Nested Repeater is needed

yep

**Comment by lxbdr** [comment]
Has anyone found a workaround for this? Maybe a custom control or using ACF?

**Comment by edatastyle** [comment]
This is highly needed  !

**Comment by cagriuckan** [comment]
+1

**Comment by AlexBa** [comment]
+1

**Comment by metariqul** [comment]
Nested repeated is badly needed for the custom widget.

**Comment by Niloys7** [comment]
YES, +1 for Nested repeater

**Comment by Paras16699** [comment]
@bainternet, any update on this? This feature is highly requested. 

Need this in a custom widget I'm developing.

**Comment by Paras16699** [comment]
@bainternet, if you guys don't have plans to integrate it within the source, then at least any hints on how to make it possible would be much appreciated so that we can replicate the repeater control to make our custom repeater control which can be nested..

**Comment by mdjwel** [comment]
We badly need this feature. Please tell us at least, how we can solve this issue. Otherwise, I have to move with another page builder plugin.

**Comment by kamalahmed** [comment]
We need this feature for very simple task too. Here are two use case I faced a  bit problem. 

A team member slider widget has a repeater to add member. Now inside the member, we need to add social info(icon and link) to the member. A member may have multiple social profiles. So, we need a nested repeater for icon and link of social profile for each member in the parent repeater.


Second case, A pricing table widget has a repeater for adding pricing card in a table. (using separate card is not possible for some case). Now each card has features list. Feature list could be a repeater where user could easily add a nice icon and the feature info. But again nested repeater is not available to achieve this. 

Similarly many situation needs nested repeater for best user experience. Please add this feature. Thank you very much.

**Comment by Ataurr** [comment]
@kamalahmed @Paras16699 Elements Kit has features like this to add widgets under another widget and this could be multi-level. 
https://products.wpmet.com/elementskit/advanced-tab-one/
https://products.wpmet.com/elementskit/advance-accordion/

Check this screencast https://www.youtube.com/watch?v=eNMp_6NturY

Hope this solve what you are asking.

**Comment by kamalahmed** [comment]
@Ataurr Sorry. This is not what I am looking for. I am looking for nested repeater to develop my own widget for my theme and plugin. btw, the plugin you shared has some awesome feature. the way nested widget is created there is really cool. Thanks for sharing and trying to help. :)

**Comment by synio-wesley** [comment]
I also need this

**Comment by synio-wesley** [comment]
> Maybe we will look at it in the future if we see a large demand for it.

I think there's a large demand for it, looking at this ticket.

**Comment by dimative** [comment]
@synio-wesley Yes. Of course. This feature is need Elementor developers. I believe it will possible in future.

**Comment by ashikur11** [comment]
Please take a look at this feature to elementor. As it's already has very good development api. but for this thing we loosing some great workflow. as this is not currently supporting this nested repeater now i am depended on custom post to load that data. which is more  tough than creating a widget. 

Good day!

**Comment by webdevs-pro** [comment]
Very need this feature

**Comment by jilani53** [comment]
Very sad news! It's a common feature for all page builder.  I don't understand why people so exciting for  Elementor. The first time, I'm converting my theme into Elementor but shocked!

**Comment by jilani53** [comment]
Very sad news! It's a common feature for all others page builder. I don't understand why people so exciting for Elementor. The first time, I'm converting my theme into Elementor but shocked!

**Comment by alarstyle** [comment]
+1

**Comment by webdevs-pro** [comment]
+1

**Comment by Nincha** [comment]
Big +1, this should be there. :)

**Comment by Kennyboy7** [comment]
+1

**Comment by Solunsky** [comment]
My solution

Create two repeaters and bind them with keys. Good luck

	protected function _register_controls() {
		$this->start_controls_section(
			'section_categories',
			[
				'label' => __( 'Categories', 'elementor' ),
			]
		);

		$repeater = new Repeater();

		$repeater->add_control(
			'category_slug',
			[
				'label'       => __( 'Category Slug', 'elementor' ),
				'type'        => Controls_Manager::TEXT,
				'default'     => __( 'category-name', 'elementor' ),
				'label_block' => true,
			]
		);

		$repeater->add_control(
			'category_title',
			[
				'label'       => __( 'Category Title', 'elementor' ),
				'type'        => Controls_Manager::TEXT,
				'default'     => __( 'Category Title', 'elementor' ),
				'label_block' => true,
			]
		);

		$this->add_control(
			'categories',
			[
				'label'       => __( 'Contacts', 'elementor' ),
				'type'        => Controls_Manager::REPEATER,
				'fields'      => $repeater->get_controls(),
				'title_field' => '{{{ category_title }}}',
			]
		);

		$this->end_controls_section();

		$this->start_controls_section(
			'section_prices',
			[
				'label' => __( 'Prices', 'elementor' ),
			]
		);

		$serviceRepeater = new Repeater();

		$serviceRepeater->add_control(
			'category_slug',
			[
				'label'       => __( 'Category Slug', 'elementor' ),
				'type'        => Controls_Manager::TEXT,
				'default'     => __( 'category-name', 'elementor' ),
				'label_block' => true,
			]
		);

		$serviceRepeater->add_control(
			'service_title',
			[
				'label'       => __( 'Service Title', 'elementor' ),
				'type'        => Controls_Manager::TEXT,
				'default'     => __( 'Service Title', 'elementor' ),
				'label_block' => true,
			]
		);

		$serviceRepeater->add_control(
			'service_price',
			[
				'label'       => __( 'Price', 'elementor' ),
				'type'        => Controls_Manager::TEXT,
				'default'     => __( '40,00', 'elementor' ),
				'label_block' => true,
			]
		);

		$this->add_control(
			'services',
			[
				'label'       => __( 'Services', 'elementor' ),
				'type'        => Controls_Manager::REPEATER,
				'fields'      => $serviceRepeater->get_controls(),
				'title_field' => '{{{ service_title }}}',
			]
		);

		$this->end_controls_section();
	}

Add to render

	foreach ($settings['categories'] as $category) {
		echo $category['category_title'];
		
		foreach($settings['services' as $service) {
			if ($category['category_slug'] === $service['category_slug'] {
				echo $category['service_title'];
			}
		}
	}

**Comment by montepente** [comment]
+1 Would love to have this functionality!

**Comment by rashedulislam** [comment]
Any new update regarding this?Badly need this one :)

**Comment by sbc640964** [comment]
+1

**Comment by jahir07** [comment]
Any update regarding this?

**Comment by creazy231** [comment]
I also would like to see this feature :)

**Comment by hkmsadek** [comment]
Any luck on this problem guys>?

**Comment by aliboy08** [comment]
+1

**Comment by nicolasgalano** [comment]
+1, Please!

**Comment by hiviz** [comment]
+1

**Comment by thecodude** [comment]
Any update about nested repeater?

**Comment by juanobrach** [comment]
+1

**Comment by gr33ngrl** [comment]
+100

**Comment by mdtaufiqul** [comment]
@Elementor_team Please let us know if you have plans about the nested repeater. This has a very high demand. Thank you.

**Comment by wink-media** [comment]
+1000 I can't believe its been this long and still nothing.

**Comment by bnqtoan** [comment]
+1
Still need it today, anyone ?

**Comment by Demonicious** [comment]
+1

**Comment by besimdauti** [comment]
+1. Make nested repeater, we are missing it so much when working with elementor

**Comment by mabezdek** [comment]
+1

**Comment by OTW-DEV-1** [comment]
+1. Make nested repeater, we are missing it so much when working with elementor

**Comment by akashmdiu** [comment]
Hello,
Here is the solution of nested repeater fields. I make this for my custom plugin. 

`$this->start_controls_section(
            'timeline_tab',
            [
                'label' => __('Timeline', 'political-core'),
                'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
            ]
        );
        
        $repeater = new \Elementor\Repeater(); 

		$repeater->add_control(
			'timeline_year', [
				'label' => __( 'Year', 'political-core' ),
				'type' => \Elementor\Controls_Manager::NUMBER,
				'default' => __( '2005' , 'political-core' ),
			]
		);
            $repeater_content = new \Elementor\Repeater();

            $repeater_content->add_control(
                'timeline_title', [
                    'label' => __( 'Title', 'political-core' ),
                    'type' => \Elementor\Controls_Manager::TEXT,
                    'default' => __( '2005' , 'political-core' ),
                    'label_block' => true
                ]
            );
            $repeater_content->add_control(
                'timeline_date', [
                    'label' => __( 'Date', 'political-core' ),
                    'type' => \Elementor\Controls_Manager::DATE_TIME,
                    'label_block' => true
                ]
            );
            $repeater_content->add_control(
                'timeline_content', [
                    'label' => __( 'Date', 'political-core' ),
                    'type' => \Elementor\Controls_Manager::WYSIWYG,
                    'label_block' => true
                ]
            );


            $repeater->add_control(
                'content_list',
                [
                    'label' => __( 'Repeater List', 'political-core' ),
                    'type' => \Elementor\Controls_Manager::REPEATER,
                    'fields' => $repeater_content->get_controls(),
                    'default' => [
                        [
                            'timeline_title' => __( 'Up harmonics material person', 'political-core' ),
                        ],
                        [
                            'timeline_title' => __( 'His likely that just was harmonics', 'political-core' ),
                        ],
                    ],
                    'title_field' => '{{{ timeline_title }}}',
                ]
            );


		$this->add_control(
			'year_list',
			[
				'label' => __( 'Repeater List', 'political-core' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $repeater->get_controls(),
				'default' => [
					[
						'timeline_year' => __( '2005', 'political-core' ),
					],
					[
						'timeline_year' => __( '2008', 'political-core' ),
					],
				],
				'title_field' => '{{{ timeline_year }}}',
			]
		);

        $this->end_controls_section();`

**Comment by beyondsagency** [comment]
+1. Make nested repeater, we are missing it so much when working with elementor

**Comment by MarcoCpDigital** [comment]
+1

**Comment by antohapan** [comment]
+1

**Comment by zookatron** [comment]
+1

**Comment by ryanlabelle** [comment]
+1 I'm still hopeful :)

**Comment by kyndaqtepammy** [comment]
still waiting too

**Comment by rayediaz** [comment]
We need THIS FEATURE!!!

**Comment by euene** [comment]
+1

**Comment by cagriuckan** [comment]
+1

**Comment by DominikProbst** [comment]
+1

**Comment by higorch** [comment]
+1

**Comment by AlexL-JWA** [comment]
Странно но у всех эта функциия есть очень нужна +1

**Comment by davidfmiller** [comment]
+1

**Comment by kurt-unleashed** [comment]
+1

**Comment by Tigriceo** [comment]
I was surprised that there is no such banal thing.
Add it please, it is very relevant now.
Thank you

**Comment by vatheara** [comment]
2022 now i still need this feature

**Comment by Nincha** [comment]
> @websumon
> 
> Sadly the Repeater controls cannot support a nested repeater.
> 
> Maybe we will look at it in the future if we see a large demand for it.

Could you please define "large demand"? 😄

**Comment by rafiul** [comment]
@bainternet Any updates about this feature?

**Comment by codersaiful** [comment]
Any update here?

**Comment by Tigriceo** [comment]
I do not know what to say . This question has been open for 5 years. Such functionality is available almost everywhere, but not in the elementor. All that's left is to wait...

**Comment by azamatx** [comment]
+1

**Comment by Programm1ng** [comment]
+1

**Comment by d-delaey** [comment]
+1

**Comment by MaximilianFlechtner** [comment]
+1

**Comment by MrGrock** [comment]
I did, but there is a bug when creating an element of the second level (an element of both the first and second levels is created)

`$this->start_controls_section(
			'tab_section',
			[
				'label' => esc_html__( 'Tabs', 'armed' ),
				'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
			]
		);

		/* Start repeater */

		$repeater = new \Elementor\Repeater();
		$repeater_links = new \Elementor\Repeater();

		$repeater->add_control(
			'title',
			[
				'label' => esc_html__( 'Title', 'armed' ),
				'type' => \Elementor\Controls_Manager::TEXT,
				'dynamic' => [
					'active' => true,
				],
			]
		);

		$repeater_links->add_control(
			'title',
			[
				'label' => esc_html__( 'Title', 'armed' ),
				'type' => \Elementor\Controls_Manager::TEXT,
				'dynamic' => [
					'active' => true,
				],
			]
		);
		

		/* End repeater */

		$repeater->add_control(
			'links',
			[
				'label' => esc_html__( 'Links', 'armed' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $repeater_links->get_controls(),
			]
		);

		$this->add_control(
			'tabs_items',
			[
				'label' => esc_html__( 'Banner Items', 'armed' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $repeater->get_controls(),
                'prevent_empty' => false,
			]
		);


		$this->end_controls_section();`

**Comment by cartimize** [comment]
> I did, but there is a bug when creating an element of the second level (an element of both the first and second levels is created)
> 
> ` $this->start_controls_section( 'tab_section', [ 'label' => esc_html__( 'Tabs', 'armed' ), 'tab' => \Elementor\Controls_Manager::TAB_CONTENT, ] );
> 
> ```
> 	/* Start repeater */
> 
> 	$repeater = new \Elementor\Repeater();
> 	$repeater_links = new \Elementor\Repeater();
> 
> 	$repeater->add_control(
> 		'title',
> 		[
> 			'label' => esc_html__( 'Title', 'armed' ),
> 			'type' => \Elementor\Controls_Manager::TEXT,
> 			'dynamic' => [
> 				'active' => true,
> 			],
> 		]
> 	);
> 
> 	$repeater_links->add_control(
> 		'title',
> 		[
> 			'label' => esc_html__( 'Title', 'armed' ),
> 			'type' => \Elementor\Controls_Manager::TEXT,
> 			'dynamic' => [
> 				'active' => true,
> 			],
> 		]
> 	);
> 	
> 
> 	/* End repeater */
> 
> 	$repeater->add_control(
> 		'links',
> 		[
> 			'label' => esc_html__( 'Links', 'armed' ),
> 			'type' => \Elementor\Controls_Manager::REPEATER,
> 			'fields' => $repeater_links->get_controls(),
> 		]
> 	);
> 
> 	$this->add_control(
> 		'tabs_items',
> 		[
> 			'label' => esc_html__( 'Banner Items', 'armed' ),
> 			'type' => \Elementor\Controls_Manager::REPEATER,
> 			'fields' => $repeater->get_controls(),
>             'prevent_empty' => false,
> 		]
> 	);
> 
> 
> 	$this->end_controls_section();`
> ```

I too face this issue.

**Comment by nimaaminz** [comment]
Need it !!!!!!

**Comment by cartimize** [comment]
-- Please reply above this line --


Hello Elementor/elementor,

I'm reaching out to confirm that we have received your request.
We'll look into your issue and get back to you asap.
Thanks for your patience. :)

Cheers,
Amrit.

We're available Mon - Fri; 9am - 6pm IST.

**Comment by msshohan** [comment]
Highly needed! Please try to add this feature as soon as possible.
Thank you.

**Comment by synio-wesley** [comment]
I talked to the Global Community Manager of Elementor in September 2022 at Wordcamp Netherlands. I briefly discussed this issue. They told me to send them a mail or message on WhatsApp, so I did both. After a few days I got a reply that they would put a new recruit on this issue. But I haven't heard back yet. 2 months have passed now. I just asked for another status update but I'm still awaiting feedback.

**Comment by cartimize** [comment]
-- Please reply above this line --


Hello Elementor/elementor,

I'm reaching out to confirm that we have received your request.
We'll look into your issue and get back to you asap.
Thanks for your patience. :)

Cheers,
Amrit.

We're available Mon - Fri; 9am - 6pm IST.

**Comment by synio-wesley** [comment]
UPDATE: I got a reply from the Global Community Manager. He says that the new recruit began working at a later time than expected and that he forgot to mention the Github issues to him because of that.

He asked me to tag him and his colleague. So that's what I will do now. Hopefully Elementor (Pro) will soon receive the ability to add subitems under items in the repeater as it is a highly requested feature and once that would be very welcome for everyone using Elementor.

@nicholaszein @VerdiH Thanks for looking into this for us! I briefly looked into the code before but it was a bit difficult to understand quickly for someone not working on the core code and I didn't find a way to quickly fix this. It might take a bit more time to implement this feature. But if you promise to accept a (good) pull request for this feature, then I might take a stab at implementing this missing functionality.

**Comment by nicholaszein** [comment]
Hello everybody! 

This is Nick from Elementor. 👋

You might have seen me around as a volunteer moderator in the [Global Elementor Community](https://www.facebook.com/groups/Elementors) on Facebook. I'm the "new recruit guy" as @synio-wesley mentioned. From now on I'm going to help you guys with everything related to this GitHub community.

I wanted to give you some feedback about this issue.

First of all, thank you for your patience! Your feedback is valuable and we want to make sure you are being heard. 🙏 

Secondly, I want to let you know that I'll be discussing this issue next week with my manager. I want to make sure I will be giving you the correct answer.

As soon as I have an answer, I'll be commenting here. It might not be on the next week right away, regardless this issue is now on my list, and you will receive an answer from me, even if it's not what you expect.

Please allow me some time to investigate it, and get back to you with my findings! 🧐 

Kind regards

**Comment by nimaaminz** [comment]
Hello Thank You
😍😍

**Comment by GustavoGomez092** [comment]
Any updates on this matter? this is a vital feature for complex widgets.

**Comment by NgJason** [comment]
Any update on this ?

**Comment by crestinglight** [comment]
This feature is sorely needed, please update us on progress?

**Comment by soilwork92** [comment]
+1

**Comment by kearisp** [comment]
+1

**Comment by h08831n** [comment]
+1

**Comment by danielescardo** [comment]
+1

**Comment by Tigriceo** [comment]
I think in 5 years this feature will be added )
can anyone write if this is planned at all?  And why is it problematic?

**Comment by waellatiri** [comment]
+1

**Comment by madurapa** [comment]
still waiting :(

**Comment by nicholaszein** [comment]
Hello everyone, it's Nick from Elementor.

I have an update on this issue.

After much consideration and internal discussions, as well as researching different ways to implement this request, we concluded for the time being we are not going to add this functionality, and we do not plan to add it in the near future. There are various reasons for this decision, but the most important one is performance and reliability, especially when it comes to Dynamic Tags.

This is our final decision. I hope you can understand.

Kind regards
