### ISSUE TITLE
✅ ⛔ 🧩 🚀 The New Off-Canvas Widget & Crocoblock JetEngine

### ISSUE THREAD

**Issue by HarbourBob** [elementor/elementor#29557]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I have successfully used the new Off-Canvas widget using ordinary posts, Woocommerce and Custom Post Types, together with some meta-fields created in ACF Pro.  However, when I repeat the earlier experiment using ACF Pro in Crocoblock JetEngine, I run into the following conflict...

I can create the Loop Grid with no problems. The issue arises when I drag the Off-Canvas widget onto the Loop Grid Template. While the pop-up opens as expected, the automatically created Container is not visible in the editor. It is, however, present and visible in the Navigator.

It is not possible to add any widgets to the Off-Canvas Container.

I have tried to isolate the problem by deactivating all plugins except Elementor and JetEngine, but the same conflict persists.  Because Off-Canvas works so well with Posts, ACF Pro and Woocommerce, I think there maybe some conflict with JetEngine.

![off-canvas-bug](https://github.com/user-attachments/assets/f1e13fad-9ca0-4b10-8e41-58278d30462c)

### Steps to reproduce

1. Create a basic CPT with JetEngine.
2. Still using JetEngine, create three meta-fields (2 Text and 1 Image)
3. Populate the CPT with some data.
4. Create a new page in Elementor and add the Loop-Grid widget.
5. Staying on that page, create a Listing Template and populate using the Text and Image fields.  Then, add a button to fire the Off-Canvas pop-up.
6. Add the Off-Canvas widget to the Listing Template.
7. While the Off-Canvas popup is visible, the Container that sits on it is not there, you will notice that while the Container is present in the Navigator, you cannot interact with it or add any widgets.

### Expected behavior

1. On creating the Listing Template and adding the Off-Canvas widget I expected to see the popup in the editor, together with an auto-generated Container - but this was missing and in the case of JetEngine, it was not possible to generate the Off-Canvas popup.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	Source distribution v8.0.39-30	
PHP Version:	8.2.26	
PHP Memory Limit:	768M	
PHP Max Input Vars:	3000	
PHP Max Post Size:	256M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.7.1	
Site URL:	https://robertp324.sg-host.com	
Home URL:	https://robertp324.sg-host.com	
WP Multisite:	No	
Max Upload Size:	256 MB	
Memory limit:	256M	
Max Memory limit:	768M	
Permalink Structure:	/%postname%/	
Language:	en_GB	
Timezone:	Europe/London		
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	3.1.1	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a child theme.
User		
Role:	administrator	
WP Profile lang:	en-GB	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36	
Active Plugins		
Elementor - 3.26.0-dev4	By Elementor.com	
Elementor Beta (Developer Edition) - 1.1.3	By Elementor.com	
Elementor Pro - 3.26.0-beta2	By Elementor.com	
JetEngine - 3.6.0.1	By Crocoblock	
Elements UsageRecalculate		
Listing Item ( 0 )	Button: 2
Dynamic Field: 12
Dynamic Image: 1
Dynamic Link: 1
Heading: 3
Icon: 1
Image: 3
Off-Canvas: 2
container: 7
Page ( 6 )	Button: 4
Code Highlight: 1
Divider: 2
Form: 1
HTML: 2
Heading: 17
Icon: 3
Image: 9
Listing Grid: 2
Loop Grid: 1
Text Editor: 12
Text Path: 1
container: 43
elementskit-button: 1
elementskit-heading: 1
elementskit-icon-box: 5
elementskit-image-morphing: 3
ha-feature-list: 1
ha-infobox: 4
Post ( 0 )	Heading: 2
Image: 1
container: 1
Theme - Single Page ( 1 )	Dynamic Field: 4
Featured Image: 1
Listing Grid: 1
container: 3
Theme - Loop Item ( 3 )	Button: 1
Dynamic Image: 2
Heading: 2
Icon: 1
Image: 1
Off-Canvas: 1
container: 4
Theme - Header ( 1 )	Icon List: 2
Image: 1
container: 7
ha-navigation-menu: 1
Theme - Footer ( 1 )	Heading: 4
Icon List: 2
Image Box: 1
Social Icons: 1
Text Editor: 1
WordPress Menu: 1
container: 6
Library - Page ( 2 )	Listing Grid: 1
container: 1
Settings		
cpt_support	post, page
allow_tracking	yes
Features		
Custom Fonts:	1	
Custom Icons:	0	
Integrations		
Elementor Experiments		
Inline Font Icons: 	Active
Additional Custom Breakpoints: 	Active
Container: 	Active
Upgrade Swiper Library: 	Active by default
Nested Elements Performance: 	Active by default
Optimized Markup: 	Active
Plugin Onboarding: 	Active by default
CSS Smooth Scroll: 	Active by default
Default to New Theme Builder: 	Active
Header and footer: 	Active
Elementor Home Screen: 	Active by default
Landing pages: 	Active
Nested Elements: 	Active
Editor Top Bar: 	Active
Pages Panel: 	Inactive by default
Element Caching: 	Active
Link In Bio: 	Active by default
Floating Buttons: 	Active by default
Elementor Editor Events: 	Inactive by default
Atomic Widgets: 	Inactive by default
Global Classes: 	Inactive by default
Launchpad Checklist: 	Inactive by default
Menu: 	Active

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Daveden2** [comment]
Any reason why you are using the Dev edition of Elementor? That's not supposed to be used in production.

Elementor, please, when will you stop showing us the ad to install the Dev edition when we activate Elementor features? 🙏

**Comment by nicholaszein** [comment]
Hello @HarbourBob,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

Moreover, The feature you're referring to was not yet supported at the time that you published this issue. The Off-Canvas widget only gained support for Dynamic Content inside the Loop Grid widget with the release of Elementor Pro v3.26.0.

You also seem to be using the Elementor Beta (Developer Edition) plugin on a production site. Which is extremely dangerous as this plugin is meant to be used only by 3rd-party developers to test their plugins with the latest version of Elementor. It's not intended to be used on live websites. Please, [revert to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) and uninstall the plugin.

### You can now use the Off-Canvas widget inside the Loop Grid to add dynamic modals to Loops.

However the Off-Canvas is not compatible with Jet Listings or other Jet Elements.

Kind regards

Regards
