### ISSUE TITLE
❌ Invalid Issue: Close Off-Canvas with any Button Located within the Off-Canvas "popup"

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#29593]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:
> 
> ```js
> jQuery( document ).ready( function( $ ) {
> 	$( document ).on( 'click', '.close-popup', function( event ) {
> 		elementorProFrontend.modules.popup.closePopup( {}, event );
> 	} );
> } );
> ```
> 
> Thanks for the feedback.

anything like this snippet that we can use in the new off-canvas "popup" that isn't really a popup? this snippet works great for my footer popup (actual popup), but the off-canvas element doesn't work exactly the same and i can't seem to figure out how to modify this code to get it to work.

_Originally posted by @TomRaraAvis in https://github.com/elementor/elementor/issues/7085#issuecomment-2544639931_

**Comment by TomRaraAvis** [comment]
#27727

**Comment by louiswol94** [comment]
@TomRaraAvis There is a Dynamic Tag to Close the Off-Canvas. The Dynamic Tag is available on anything that has a link (Button, heading, icon etc).

**Comment by nicholaszein** [comment]
Hello @TomRaraAvis.

What you are reporting as a bug is actually already an existing feature. Before posting an issue on GitHub, please check the Help Center for the Documentation of the widget you are referring to.

Here's the documentation for the Off-Canvas widget: https://elementor.com/help/off-canvas-widget/

You can use any link field to select a Dynamic Tag that will allow you to close the Off-Canvas widget. You don't need custom code.

Moreover, this is not how you submit an issue. You need to follow our [Contribution Guidelines](https://github.com/elementor/elementor/blob/66626f3d562461b584f8c2faf37d169d904b1444/.github/CONTRIBUTING.md), and spamming other issues and discussions with complaints violates our [Code of Conduct](https://github.com/elementor/elementor/blob/66626f3d562461b584f8c2faf37d169d904b1444/.github/CODE_OF_CONDUCT.md).

Please, do not do this again, or we will be forced to ban you.
