### ISSUE TITLE
✅ ❌ 🧩 🐞 Custom Swiper Instances are not working after the release of Elementor 3.26.0

### ISSUE THREAD

**Issue by mindray87** [elementor/elementor#29616]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

3.26 overrides custom swipers that have been using swiper 11. this should not happen! also if this contains major breaking changes like this you shoud deactivate auto update before the release... this was our favourite page builder.

### Steps to reproduce

use swiper 11.x and create a custom widget with the dependencoes

### Expected behavior

the custom swiper works no matter what you nilly dillies do while beeing stable on swiper 5 which already is outdated since 5 years :D 

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
as described above.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by KingGrizzly** [comment]
+1 Swiper breaking on sites

**Comment by chrismwalker-portfolio** [comment]
Another +1 for Swiper breaking on sites. Carousels in plugins like Dynamic.ooo are broken, and format their slides as a single overflowing column. Rolling back to Elementor 3.25.11 (non-pro plugin) fixes the problem. Same issue experienced across multiple sites.

**Comment by m1ga** [comment]
I've added a feature request here https://github.com/orgs/elementor/discussions/29612 to keep on version in the main directory.

**Comment by rami-elementor** [comment]
@mindray87 @sunbbon88 @KingGrizzly @chrismwalker-portfolio 

Which elementor widgets are breaking. If you are using external plugins, which ones are you using (Besides Dynamic.ooo).

**Comment by mindray87** [comment]
the normal carousel as well as all custom ones. 
there are, as described above no external plugins active (i did this on a fresh wordpress installation using only elementor). 
i included swiper11 and elementor breaks the pathing even if i use it in the functions.php

**Comment by rami-elementor** [comment]
@mindray87 If I understand correctly, you are trying to add your own Swiper11 to a page which uses Swiper8 (added by Elementor) and the page breaks. Can you add the code?

**Comment by mindray87** [comment]
first there are two issues to be precise. 
first beeing that elementor carousel (the swiper from elementor pro) broke on every site i used it after upgrading to 3.26. which is the biggest suprise for me. Cause even after a major change you either shouldn't allow the auto upgrade option (if you know things might break) to work which should be possible. this is because the old used carousel wants a js file as stated also by m1ga. 

Second we use the current up2date swiper(v11.x atm) for custom designed and programmed swiper elements (this is also a point i can not understand at all. if you upgrade the whole thing, why not go to the current stable v11? ). those broke too, as somehow the new elementor update managed to unload those custom ones. i think this might have to do with the way they now include their swiper package and css. (also in modern days bragging about 16kb saving on page load is in my opinion unnecessary in this case, as the rest of elementor feels bloated af, which is due to usabilty which i understand.) 

we use swiper (dependant on the use case) either by using our custom theme skeleton (via pnpm and vite build) or directly as script dependency for js and css files either globally in the functions.php or the custom widget. (some base line e.g. 
    wp_enqueue_style('swiper', 'https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css', [], null, 'screen');
)

**Comment by m1ga** [comment]
> if you upgrade the whole thing, why not go to the current stable v11

they only enabled it by default, they didn't update swiper again. Swiper v8 was included for some time already. But I agree: still could be updated to a higher version. In fact: there is a PR for v10 (https://github.com/elementor/elementor/pull/23708) already but it's over a year old

**Comment by mkabi** [comment]
Another problem has occurred in the new Elementor update.
In Elementor, I created an image swiper in the templates section, so when I want to use this image carousel on different pages, I don't have to design it every time, and I call the name of that template through the elementor templates widget to display it.
After the recent Elementor update, when this template is called through the template widget, unfortunately the images are not displayed and the corresponding script is not loaded.

![swiper](https://github.com/user-attachments/assets/5d1c0008-e15e-4c1e-86d1-4f9fbb4e0c02)

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.26.3! 🥳 

**We reverted back the removal of the registration of the swiper.js library.**

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
