### ISSUE TITLE
mobile layout - hide columns

### ISSUE THREAD

**Issue by Tim2468** [elementor/elementor#2965]
It should be possible to deactivate individual columns for mobile devices.
At the moment it is only possible to deactivate whole sections.

**Comment by bainternet** [comment]
@Tim2468 

Can you not simply hide the widgets in that column for mobile?

**Comment by Tim2468** [comment]
Yes, it works, but what if I have many widgets in a column, e. g. 20 or more.
In this case I have to hide everything in the column manually.
Also I have to reduce the default padding of a column to zero, because the empty column still exists in mobil view.
It's not really an important feature, but I think it can save some time.

**Comment by bainternet** [comment]
@Tim2468 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by randzgonz02** [comment]
We also need this exact feature that @Tim2468 mentioned.

**Comment by ShadowXVII** [comment]
I tried setting Column Width to 0% but it won't hide :(

**Comment by sambob220** [comment]
I would also benefit from this feature. Makes it a ton easier to optimize block and other layouts across devices.

**Comment by dinhtungdu** [comment]
I need this feature too. Another issue when hide widget is that the column is still visible => the padding of column still affect distance between rows.

**Comment by KimchaC** [comment]
I agree, this is a MUST. It makes working with Elementor MUCH harder.

**Comment by ljgarnes** [comment]
I need this option as well.

**Comment by gahilo** [comment]
I need this option as well

**Comment by juanfran-granados** [comment]
+1

**Comment by bellamystudio** [comment]
Yep, this is still necessary! +1

**Comment by reddykvishal** [comment]
+1 Yes, this is definitely important. It would be immensely useful to hide a column on devices.

**Comment by coreaspect** [comment]
looks like a workaround using CSS, pretty easy - https://www.youtube.com/watch?v=CGQnKgjbdDI

**Comment by clickharder** [comment]
I added this code to a plugin (my guess is it would also work in the functions.php file).

`
if ( !function_exists( 'ch_hide_column_elementor_controls' ) ) {
	add_action( 'elementor/element/before_section_end' , 'ch_hide_column_elementor_controls', 10, 3 );
	function ch_hide_column_elementor_controls( $section, $section_id, $args ) {
		if( $section_id == 'section_advanced' ) :

			$section->add_control(
				'hide_desktop_column',
				[
					'label' => __( 'Hide On Desktop', 'elementor' ),
					'type' => Elementor\Controls_Manager::SWITCHER,
					'default' => '',
					'prefix_class' => 'elementor-',
					'label_on' => __( 'Hide', 'elementor' ),
					'label_off' => __( 'Show', 'elementor' ),
					'return_value' => 'hidden-desktop',
				]
			);

			$section->add_control(
				'hide_tablet_column',
				[
					'label' => __( 'Hide On Tablet', 'elementor' ),
					'type' => Elementor\Controls_Manager::SWITCHER,
					'default' => '',
					'prefix_class' => 'elementor-',
					'label_on' => __( 'Hide', 'elementor' ),
					'label_off' => __( 'Show', 'elementor' ),
					'return_value' => 'hidden-tablet',
				]
			);

			$section->add_control(
				'hide_mobile_column',
				[
					'label' => __( 'Hide On Mobile', 'elementor' ),
					'type' => Elementor\Controls_Manager::SWITCHER,
					'default' => '',
					'prefix_class' => 'elementor-',
					'label_on' => __( 'Hide', 'elementor' ),
					'label_off' => __( 'Show', 'elementor' ),
					'return_value' => 'hidden-phone',
				]
			);
		endif;
	}
}
`

This created the toggles within the advanced tab for hiding columns.  I have been using it for months.  I used to have it in the Responsive section but that was removed in a recent update so I just moved them over to the Advanced section.  Not sure why this couldn't be incorporated in Elementor.

Personally, I like to use background images on my columns.  Even if you hide all of the widgets within the column you still can see a sliver of the background image.

**Comment by yaniv691** [comment]
+1 This is very important and useful. Please add this feature.

**Comment by monaye** [comment]
+1 I think this is a very important feature.

**Comment by Ricarditu** [comment]
Thank @clickharder for this code! Works like a charm!

If it's so simple to create the controls, why not add it to the source code?

**Comment by black-eye** [comment]
@bainternet Please consider reopening this issue. 
15+ supporters since closing this issue - that's large enough demand to reconsider, isn't it?

**Comment by pixelsock** [comment]
+1, please. This doesn't make any sense why this isn't an option already.

**Comment by KimchaC** [comment]
Hurray, it's reopened. Let's hope this gets implemented soon :)

**Comment by pixelsock** [comment]
@clickharder This is a perfect solution in the meantime. Thanks for this!

**Comment by kubik101** [comment]
+ 100
I am using Elementor Pro for the first time and looked for the ability to hide columns responsively almost immediately.

**Comment by SetayWeb** [comment]
+1 This is vital!

**Comment by chrolm** [comment]
+1 for this feature.

@clickharder Awesome! Thank you.

**Comment by marka33** [comment]
+++++ This feature is needed ASAP!!!!!!!!!

**Comment by MPHood** [comment]
Still needed

**Comment by HaileyKay28** [comment]
Needed 👍

**Comment by Turanligil** [comment]
+1

**Comment by hufer** [comment]
https://pafe.piotnet.com/#responsive-hide-column Piotnet Addons For Elementor Responsive Hide Column can do it for you

**Comment by wayheming** [comment]
+1 Yes, this is definitely important. It would be immensely useful to hide a column on devices.

**Comment by clickharder** [comment]
I purchased Piotnet Addons for Elementor and it works exactly as I would have imagined.  The code I provided works as a free option, and it would be best if Elementor included this feature, but that plugin definitely fills the gap in the meantime.

But seriously, it makes no sense that this features hasn't been added it.  It almost feels like we are being ignored on purpose... ;)

**Comment by wayheming** [comment]
@clickharder I sent a pull request #6837 with the addition of these options, wait and see if it can accept.

**Comment by reizen703** [comment]
Please add feature

**Comment by JoeRossPR** [comment]
@bainternet +1 Needed! @clickharder where exactly do I need to put that code?

**Comment by davidmonteromirai** [comment]
+1

**Comment by arielk** [comment]
Closed by https://github.com/elementor/elementor/issues/6898
