### ISSUE TITLE
Feature Request: Make Elementor Carousel Slider Fully Non-Interactive great to see.

### ISSUE THREAD

**Issue by PavelFajman** [elementor/elementor#29707]
I strongly support the idea of making the carousel slider completely non-interactive, as mentioned here:
      
"I would love to have this feature and also to make the slider completely non interactive in any way. It just runs and never stopps, not with hovering or grabbing with the mouse, not with anything. This way I can have 2 sliders side by side, starting together when the page loads and moving forward at the same time. That would be great to see. 

But even better than this, for my own purposes, would be to have the option to have the slider widget time together with a second slider widget on the same page. That would be perfect!"

_Originally posted by @rinibak in https://github.com/elementor/elementor/issues/5614#issuecomment-1784205993_

Here is a reference link to the page where I need this functionality: https://alba-horovice.cz/hp-carousel-test1/.
Thank you for considering this feature!

**Comment by nicholaszein** [comment]
Hello.

Please don't submit issues as feature requests.

Follow our [Contribution Guidelines](https://elemn.to/gh-contributing) to learn how to sobmit issues.
