### ISSUE TITLE
Identify tablet/mobile/desktop elements by different color....(feature request)

### ISSUE THREAD

**Issue by jacksarlo** [elementor/elementor#2989]
Hi,

I have a lot of sections and elements on every page of my site... Some of them are set to be visible only on mobile, same only on desktop.

I wish that those elements or sections that are to be displayed only for mobile have a different colour so I can identify them.

For example I have two almost identical headlines, one for mobile and one for desktop. Several times already both headlines appeared on desktop because I forgot to set correct responsive setting... 

If each element has a unique colour for example red for desktop it will be much easier to find any mistakes.

If I hide a section from desktop by mistake it will be easier to find this error with this feature (in edit mode) rather than in live or preview mode... Currently to check I have to open live page and compare it side by side with page in edit mode which is tedious.

**Comment by norewp** [comment]
+1 for this feature request!

**Comment by HelmutGoebel** [comment]
+1 Maybe it should have 3 different color for desktop, tablet and mobile?

**Comment by Antal72** [comment]
+1 :)

**Comment by yasien-s** [comment]
A most welcomed feature!

**Comment by ThrudUK** [comment]
Yes, this or something similar such as showing / hiding elements based on selected view.

**Comment by chagassilva** [comment]
this is awesome !!!!!

**Comment by jacksarlo** [comment]
My suggestion is a bit different. lordloadalot wants some sort of option in **edit mode** to show only desktop elements (this will hide everything that's supposed to show on tablet/mobile), in this way he can easily edit the desktop version without unnecessary clutter. Likewise, other options to _show only_ tablet elements and _show only_ mobile elements.

My suggestion is to show everything in edit mode (as it is now) but use a different border colour around desktop/tablet/mobile elements so we can easily identify them. For example, those with a red border are desktop elements, green border tablet elements, blue border mobile elements. This helps to find out any mistakes we make. Obviously, this border won't appear on the live website, it's just to identify different elements.

Thanks

**Comment by jayalove** [comment]
I second this request 😉

**Comment by jacksarlo** [comment]
> My suggestion is to show everything in edit mode (as it is now) but use a different border colour around desktop/tablet/mobile elements so we can easily identify them. For example, those with a red border are desktop elements, green border tablet elements, blue border mobile elements. 
> 

I like this feature too.

>
I think the border method could be confusing if your design uses borders...
> 

True. Here's a possible solution:

Currently in edit mode the section, columns and element borders, (which are blue or grey) are not displayed unless you hover over with mouse.

So we need to have an option to view/hide all section/columns/elements default borders.

Then next to the current icons (see attached file), there will be added either a D (for desktop in red), M (green) or T (violet).

![section-border](https://user-images.githubusercontent.com/34690151/49684809-5d99ae00-fad9-11e8-82c0-6a53a672652b.png)

**Comment by fabianenzensperger** [comment]
+100

**Comment by arielk** [comment]
This feature has been added to Elementor v3.3.0 by adding a new control to hide invisible elements (under user preferences). 
 
Feel free to update

Thanks!
