### ISSUE TITLE
[Improvement] Icon Box widget - allow icon to stay on the left/right when on mobile

### ISSUE THREAD

**Issue by ddenev** [elementor/elementor#3040]
Hi,

The current implementation of the Icon Box widget always puts the icon centered, with the title and the text below it, when on mobile. The setting "Icon Position" is not taken into account.

This is because in frontend.css there is a @media (min-width: 768px) query which switches to flex layout but only for desktop and tablet, for mobile it is block layout.

On my website I need to have the icon on the left always, even on mobile.

Could you please allow icon positioning for mobile as well?

Thank you and best regards,
Drago

**Comment by mylimoproject** [comment]
+1 - having same issue with icon box (it works kind of perfect on Desktop/Tablet, but no way of tweaking it to float left on mobile without coding).

**used this template**
![icon-box-template](https://user-images.githubusercontent.com/29313121/39675683-afed4aa6-512c-11e8-953a-487918891a6d.JPG)

**and this is how it displays on mobile (unacceptable)** 
![icon-box-template-bug](https://user-images.githubusercontent.com/29313121/39675684-b438bdfc-512c-11e8-9305-02d98cc26939.JPG)

**Comment by markhagemann** [comment]
+1 for this issue

**Comment by Sekhemty** [comment]
Really needed, this is a problem to be fixed.

The heading should always stay on the same line of the icon, when one select the icon position to be "left" instead of "center".

A minor tweak: probably, on mobile, it is not needed to have the copy text to be indented (so, being aligned to left to the heading) and could be left to be aligned to the left to the icon; probably the best solution would be to let the user choose.

Anyway, the heading should definitely not lie below the icon: please take a look a this.

Thank you!

**Comment by hamadesign** [comment]
I've the same Problem

**Comment by dasignlady** [comment]
+1. Needs to inherit position on mobile

**Comment by zorrigas** [comment]
+1, problem stills

**Comment by emawind84** [comment]
I resolved using custom css and one custom class
```

.keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-wrapper {
  display: flex;
  flex-direction: row;
}

.keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-icon {
  flex: 0 0 auto;
  margin-left: 0px !important;
  margin-right: 14px !important;
}
```

I uploaded a working template
[elementor-keep-icon-box-left.zip](https://github.com/pojome/elementor/files/2570749/elementor-keep-icon-box-left.zip)

**Comment by digitalwordings** [comment]
really need this

**Comment by markd91** [comment]
@emawind84 Can you explain how to use that custom CSS?
Opened your template and it doesn't seem to be working.
Thank you!

**Comment by ShadowXVII** [comment]
I actually like the centered behaviour. Perhaps a better solution would be to make the Icon Alignment setting to be responsive?

**Comment by Elementalel** [comment]
Following

**Comment by tosha420** [comment]
Same problem. emawind84's solution doesn't work.
The only way for now is to use third-party add-on. I've tried them all and the only one that keeps the icon on the left is Essential Addons (icon box widget is in included in free version)
Also in order to use custom icons you need to install another free plugin – Custom icons for Elementor, because new custom icons feature built in Elementor doesn't work with Essential Addons icon box widget.

**Comment by julian-stark** [comment]
same problem but with icon on the right side

**Comment by black-eye** [comment]
+1, Essential

**Comment by emawind84** [comment]
> 
> 
> I resolved using custom css and one custom class
> 
> ```
> .keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-wrapper {
>   display: flex;
>   flex-direction: row;
> }
> 
> .keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-icon {
>   flex: 0 0 auto;
>   margin-left: 0px !important;
>   margin-right: 14px !important;
> }
> ```
> 
You need to put this css in your WordPress theme it still works for me

**Comment by RikvdReijen** [comment]
+1

**Comment by Os-Ha** [comment]
+1 Please solve this in your next update Elementor! We need to be able to set the icon's position on mobile view as well

**Comment by parfilov** [comment]
+1

**Comment by Valdinia** [comment]
My solution is:
@media (max-width: 600px) {
   .elementor-icon-box-icon {
    float: left;
   }

   .elementor-icon-box-content   {
      text-align: left;
      margin-left: 50px;
   }
}

**Comment by parfilov** [comment]
@Valdinia nope, it isn't.

Try somebody this code please. I need your support with test:
`@media (max-width: 600px) {
    
.elementor-icon-box-icon {
float: left; /*not necessary*/
}

.elementor-icon-box-content {
text-align: left;
display: table;
padding-left: 20px;
}
}`

**Comment by Valdinia** [comment]
In my case it works perfectly

Valdinia

**Comment by kneops** [comment]
+1 because it is ridiculous to have to solve this with CSS

**Comment by ivanshum** [comment]
+1

**Comment by docdanijb** [comment]
> @Valdinia nope, it isn't.
> 
> Try somebody this code please. I need your support with test:
> 
> ```
> @media (max-width: 600px) {    
> .elementor-icon-box-icon {
> float: left; /*not necessary*/
> }
> 
> .elementor-icon-box-content {
> text-align: left;
> display: table;
> padding-left: 20px;
> }
> }
> ```

This is next to perfect. However, some tablets I testet with still had the icon on top, but after changing to 900px it's perfekt.

:)

**Comment by iqbalmauludy** [comment]
> I got emawind84's solution to work, but needed to remove `.elementor-widget-icon-box` from the code posted (and of course add the custom class `keep-icon-box-left` to each icon box widget under Advanced as well as set Style > Content >Alignment to LEFT in the widget's settings).
> 
> I am using the Customizer to add the CSS, but will move to a child theme before we launch.

Work perfectly for me :D
thanks mate!

**Comment by Matent** [comment]
In addition to @iqbalmauludy comment, I added `margin-top: 30px !important;` to enable the icon float in the middle. This works perfectly for me.

Thanks everyone

**Comment by gerardreches** [comment]
+1

**Comment by Pagester** [comment]
2 years this ticket is open waiting for a fix. 

We have 2 years worth of client sites using custom css to resolve this.

**Comment by rotimikehinde** [comment]
Thanks Valdinia and co! Here's how I fixed it:

On mobile view, align Content to the Left. Then add the custom CSS below to one of the icons or to the website with a css plugin or in the header.

.iconleft .elementor-icon-box-wrapper {
display: flex;

}

.elementor-widget-icon-box .elementor-icon-box-icon {
margin-right: 10px !important;
}

Finally, add "iconleft" to the CSS Classes for each of the icons.

**Comment by barkoig** [comment]
+1

**Comment by gerardreches** [comment]
> 
> 
> @Valdinia nope, it isn't.
> 
> Try somebody this code please. I need your support with test:
> 
> ```
> @media (max-width: 600px) {    
> .elementor-icon-box-icon {
> float: left; /*not necessary*/
> }
> 
> .elementor-icon-box-content {
> text-align: left;
> display: table;
> padding-left: 20px;
> }
> }
> ```

`float:left` **is necessary**, it doesn't work without it.

**Comment by iamrasmus** [comment]
The best and most responsive method is definitely to use `display:flex;`, like in the emawind84 example. I don't recommend to use `display:table;` or `float:left`, these are outdated solutions. 

> I resolved using custom css and one custom class
> 
> ```
> .keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-wrapper {
>   display: flex;
>   flex-direction: row;
> }
> 
> .keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-icon {
>   flex: 0 0 auto;
>   margin-left: 0px !important;
>   margin-right: 14px !important;
> }
> ```
> 
> I uploaded a working template
> [elementor-keep-icon-box-left.zip](https://github.com/pojome/elementor/files/2570749/elementor-keep-icon-box-left.zip)

Also I would add `align-items:center;` to vertically center all the elements inside div class (to get text in the center of icon).

`.keep-icon-box-left .elementor-widget-icon-box .elementor-icon-box-wrapper { 
 display: flex;
flex-direction: row;
align-items:center;
 }`

**Comment by gerardreches** [comment]
Here is my solution using flex, it works for: 
+ Left-positioned
+ Right-positioned icons
+ All Icon Box Widgets, without needing to add an id or class.

Since it affects all Icon Box Widgets, I suggest to not use it as the custom CSS for each of them, but in a general CSS instead.

```
/* You can omit this part, it's to align icon with text, since they show up a bit above the text */
.elementor-widget-icon-box.elementor-position-left .elementor-icon-box-icon, .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-icon {
    margin-top: 0.125em;
}

@media (max-width: 767px) {
    .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-wrapper, .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-wrapper {
        display: flex;
    }
    .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-wrapper{
        flex-direction: row-reverse;
    }
    .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-icon {
        margin-right: 10px !important;
    }
    .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-icon {
        margin-left: 10px !important;
    }
}
```

**Comment by viveknath322** [comment]
@gerardreches solution is perfect, worked for me.

Any workaround to make the whole icon box clickable?

**Comment by vgstef** [comment]
I also got this problem. Any idea when this is going to be fixed?

**Comment by papigiulio** [comment]
Thought this was only me. Following, id love to see a fix without having to add any additional css code.

**Comment by chkserv** [comment]
Icon position won't go to the left or right on mobile. When will this be fixed?

**Comment by tosha420** [comment]
> The Icon position is stacked on the top, it won't go to the left or right on mobile. When will this be fixed?

We've been waiting for 3 years already, so...
You better use alternative widget

**Comment by devanrome1** [comment]
> > The Icon position is stacked on the top, it won't go to the left or right on mobile. When will this be fixed?
> 
> We've been waiting for 3 years already, so...
> You better use alternative widget

Any minute now. Come on @Elementor. DEW IT! **Your people want this!**

**Comment by yigbau** [comment]
Wow, almost 4 years for an align fix, meamazing!

**Comment by zakfriend** [comment]
+1

**Comment by sergeyrozenblat** [comment]
> My solution is:
> @media (max-width: 600px) {
> .elementor-icon-box-icon {
> float: left;
> }
> 
> .elementor-icon-box-content {
> text-align: left;
> margin-left: 50px;
> }
> }

For those who still want centered icon when you select centered option.

```
@media (max-width: 768px) {    
	.elementor-position-left .elementor-icon-box-icon {
		float: left;
	}

	.elementor-position-left .elementor-icon-box-content {
		text-align: left;
		display: table;
		padding-left: 14px;
	}
}
```

**Comment by gerardreches** [comment]
> For those who still want centered icon when you select centered option.
> 
> ```
> @media (max-width: 768px) {    
> 	.elementor-position-left .elementor-icon-box-icon {
> 		float: left;
> 	}
> 
> 	.elementor-position-left .elementor-icon-box-content {
> 		text-align: left;
> 		display: table;
> 		padding-left: 14px;
> 	}
> }
> ```

Hi @sergeyrozenblat , check my answer above for a solution that works with left, center, and right positioned icons.

> Here is my solution using flex, it works for:
> 
>     * Left-positioned icons
> 
>     * Right-positioned icons
> 
>     * All Icon Box Widgets, without having to add an id or class to each one.
> 
> 
> Since it affects all Icon Box Widgets, I suggest to not use it as the custom CSS for each of them, but in a general CSS instead.
> `NOTE: Since Elementor 3.0, we have a place to add this code to affect all our Elementor pages`
> 
> ```
> /* You can omit this part, it's to align the icons with the text, since they show up a bit above the text */
> .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-icon, .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-icon {
>     margin-top: 0.125em;
> }
> 
> @media (max-width: 767px) {
>     .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-wrapper, .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-wrapper {
>         display: flex;
>     }
>     .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-wrapper{
>         flex-direction: row-reverse;
>     }
>     .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-icon {
>         margin-right: 10px !important;
>     }
>     .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-icon {
>         margin-left: 10px !important;
>     }
> }
> ```
> 
> I use `10px` for margins since it's the default Elementor's horizontal padding, but you can change it to adapt it to your needs.
> 
> `text-align` is not set in order to keep flexibility. You can set it in the widget's `Style > Content > Text Align` options for each case.

**Comment by bouveng** [comment]
Wow. 3 years.

How about fixing this annoyance?
You want me to do a PR?

Br.

/J

**Comment by fxaviers** [comment]
Elementor Team, come on!
It shouldn't be that complicated to make it responsive.
Start looking at these small inconveniences more closely, especially the old ones. Your product is great, but it lacks in small details and makes everyone frustrated.

**Comment by black-eye** [comment]
Trying to convince Elementor developers about fixing these long lasting issues is like talking to a wall. It's really incomprehensible, it would take an hour or two to fix it, but no, no way - you have to beg on your knees for years to make them fix the obvious. 

I ended up by developing my own icon/image box widget, but this is definitely not the way, how we should deal with every little problem. My next site probably won't be using Elementor and I'm probably not the only one on this.

**Comment by fxaviers** [comment]
It's really not understandable. Solve old issues before releasing new stuff and growing the list further.

Unfortunately, I find myself going in the same direction, looking for alternatives. A "Webflow for WordPress" would be a dream come true.
It seems that the "Visual Composer/WPBakery Page Builder" scenario is repeating itself, the product is good but it is stationary.

**Comment by parfilov** [comment]
@fxaviers I talk about it all the time. Oxygen builder is Webflow for WordPress. Very similar structure and functions. The only accordions and sliders are cannon 💪🏻, without "template inside template inside template" needed. And very flexible flexbox layout allows you to get what you want visually (almost of course).

**Comment by fxaviers** [comment]
@parfilov I just didn't go to Oxygen because for me the CrocoBlock suite is extremely powerful, almost everything dynamic in front/back I can do with JetEngine.

I've been giving Elementor second chances, but problems like this issue make the change closer and closer.

**Comment by get8bit** [comment]
It's been FOUR YEARS. How have they not fixed this?

**Comment by sinhgiang** [comment]
I have the same problem

**Comment by 79ho3ein** [comment]
+1

**Comment by dfanaei** [comment]
4 years

**Comment by JonasJason** [comment]
Uh oh... Not what I wanted to find when looking for a solution 😂

**Comment by ofmarconi** [comment]
Ridiculo!

**Comment by heroicP** [comment]
+1

It's things like this that really bug me when using Elementor. Shouldn't any style that messes with the position of an element be responsive?

**Comment by nceeoh7** [comment]
+1

Maybe 2022 is the year...

**Comment by m0e33** [comment]
How is the progress on this?

**Comment by Hammief** [comment]
> How is the progress on this?

Not necessarily a solution, but a work around. Seems that the "Icon List" in Elementor is unaffected on mobile. Creating an icon list with one single entry serves the same purpose an an "Icon Box".

**Comment by shilo-ey** [comment]
This feature has been introduced in Elementor v3.6.0

Feel free to update

Thanks!

**Comment by gerardreches** [comment]
> This feature has been introduced in Elementor v3.6.0
> 
> Feel free to update
> 
> Thanks!

It took almost 5 years, but a fix has been finally released. Thanks @shilo-ey . I hope you guys keep fixing issues like these before adding new features. There's still a long list to go.

**Comment by Grossangriff** [comment]
Hi, 

I still have issues with this. How can I have the icon title float right to the icon image on mobile? My icon is always above the icon title or icon text and not floating left of it. I use elementor 3.6.1 and pro 3.6.4. 

It all looks fine in the elementor preview (all is aligned correctly, like I want it to), but live on the website it does not? Any idea why?

<img width="327" alt="Bildschirmfoto 2022-04-01 um 11 47 46" src="https://user-images.githubusercontent.com/102793536/161240379-23d813e1-5b99-49d3-9f09-a26f3112a5ce.png">

![WhatsApp Image 2022-04-01 at 11 51 24](https://user-images.githubusercontent.com/102793536/161240460-53c81924-02b7-46b8-86da-3cf346ae119f.jpeg)

**Comment by Grossangriff** [comment]
The custom css used to work before and now it doesn´t anymore: 

@media (max-width: 767px) {
    .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-wrapper, .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-wrapper {
        display: flex;
    }
    .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-wrapper{
        flex-direction: row-reverse;
    }
    .elementor-widget-icon-box.elementor-position-left .elementor-icon-box-icon {
        margin-right: 10px !important;
    }
    .elementor-widget-icon-box.elementor-position-right .elementor-icon-box-icon {
        margin-left: 10px !important;
    }
}

**Comment by 79ho3ein** [comment]
If I'm not mistaken, this feature was added in elementor 3.6. Am I wrong?

**Comment by amatesi** [comment]
ouch, not fixed yet.

My lousy fix was to use emojis instead of icon box widgets

**Comment by EVEmpresas** [comment]
Hi... This problem is the same in Icon box and Image box widgets. I simply used google chrome devtools to find the Image box widget's media queries for tablets, copied the codes for the 3 media queries that control the image positions, then changed the values ​​from min-width: 768 to max-width: 767 and pasted those codes into the site's custom css. it worked perfect for me. Here are the modified media queries:

@media (max-width: 767px) {
.elementor-widget-image-box.elementor-vertical-align-middle .elementor-image-box-wrapper {
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
}
}

@media (max-width: 767px) {
.elementor-widget-image-box.elementor-position-left .elementor-image-box-wrapper {
    text-align: left;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -ms-flex-direction: row;
    flex-direction: row;
}
}

@media (max-width: 767px) {
.elementor-widget-image-box.elementor-position-left .elementor-image-box-wrapper, .elementor-widget-image-box.elementor-position-right .elementor-image-box-wrapper {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
}

Best regards from Venezuela

**Comment by arnasofc** [comment]
> Hi... This problem is the same in Icon box and Image box widgets. I simply used google chrome devtools to find the Image box widget's media queries for tablets, copied the codes for the 3 media queries that control the image positions, then changed the values ​​from min-width: 768 to max-width: 767 and pasted those codes into the site's custom css. it worked perfect for me. Here are the modified media queries:
> 
> @media (max-width: 767px) { .elementor-widget-image-box.elementor-vertical-align-middle .elementor-image-box-wrapper { -webkit-box-align: center; -ms-flex-align: center; align-items: center; } }
> 
> @media (max-width: 767px) { .elementor-widget-image-box.elementor-position-left .elementor-image-box-wrapper { text-align: left; -webkit-box-orient: horizontal; -webkit-box-direction: normal; -ms-flex-direction: row; flex-direction: row; } }
> 
> @media (max-width: 767px) { .elementor-widget-image-box.elementor-position-left .elementor-image-box-wrapper, .elementor-widget-image-box.elementor-position-right .elementor-image-box-wrapper { display: -webkit-box; display: -ms-flexbox; display: flex; } }
> 
> Best regards from Venezuela

Is it possible to show it from the right side the icon?

**Comment by elyashivk1165** [comment]
Adds code snippet for layout rtl
`@media (max-width: 600px) {
selector .elementor-icon-box-icon {
float: right;
}

selector .elementor-icon-box-content {
text-align: right;
margin-right: 65px;
padding-top:1px;
padding-bottom:1px;
}
}`

**Comment by abdullahwp** [comment]
my simple fix..

add this code to custom css
`selector .elementor-icon-box-wrapper {
    align-items: center
}`

**Comment by JacobBannier** [comment]
So this was fixed for the Icon Box widget, but not Image Box widget?

A bit ridiculous..

**Comment by levantail** [comment]
Works for me, but needed to make sure that Desktop, Tablet and Mobile have the same icon positioning. In my case, only mobile for some reason was pointing up while all other platforms - left.

**Comment by yogeshkarkar** [comment]
It's been 8 years and the issue with the Image box is still there.

**Comment by talhace** [comment]
This worked for me: Use 767 not 768

/*  ICON BOX SETTINGS ON PHONE */

@media (max-width:767px){

	/* Image box wrapper */
	.elementor-widget-image-box .elementor-image-box-wrapper{
		display:flex;
		text-align:left;
		margin-top: 16px !important;
	}
	
	/* Image box content */
	.elementor-widget-image-box .elementor-image-box-content{
		margin-left: 15px !important;
		
	}
