### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Allow to control the Space Between the Dot Pagination and Active Dot Color in the Image Carousel widget (Related to #3277)

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#3096]
## Description

Enhance the **Image Carousel** widget with new controls:

* **Space Between Dots** - add space between control.
* **Active Dot Color** - add new color control for the active dot.

![imagecarousel](https://user-images.githubusercontent.com/576623/34644401-8d3dff4c-f33e-11e7-8d53-4c3775152c5d.png)

**Comment by bainternet** [comment]
Not sure this kind of request would get a high priority... but if we see a large demand for it then why not.

**Comment by ramiy** [comment]
Related #3277

**Comment by 79ho3ein** [comment]
+1

**Comment by nicholaszein** [comment]
Hey @ramiy (@rami-elementor)!

🎉 **You** have great news! 🙌 🥳 

You just released this feature yourself in the latest Elementor version 3.26.0! 💪

Thank you for your amazing work!

You rock! 👊
