### ISSUE TITLE
Feature Request: Enhance Image Gallery Widget

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#3103]
## Description

Enhance the **Image Gallery** widget with new controls:

* **Caption Background Color** - Currently we can set background color for the entire widget from the Advanced tab. We can't set background color for the caption.

![caption-bg](https://user-images.githubusercontent.com/576623/34649002-7b60fbec-f3ae-11e7-9835-cb4e06c2d477.png)

**Comment by bainternet** [comment]
@ramiy 

send a PR

**Comment by davidefiorio** [comment]
Also, I ask for implementing to set different column number in mobile
![screenshot_55](https://user-images.githubusercontent.com/33546042/48054402-7a2a8980-e1ad-11e8-94f8-83f1599b23e6.jpg)

**Comment by arielk** [comment]
@ramiy We have included these features in one of the previous updates, for the responsive request (@davidefiorio) please follow the following: https://github.com/elementor/elementor/issues/7631
