### ISSUE TITLE
🔗 🚀 Feature Request: Map Marker Icon (Duplicate of #1319)

### ISSUE THREAD

**Issue by carlosnpz** [elementor/elementor#3111]
Please, could you add the option to upload a marker icon on Google Maps feature?!

**Comment by bainternet** [comment]
@carlosnpz 

Our map widget would need to use the Google maps API for that which currently is not the way it works.

so currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Dentalicious** [comment]
+1

**Comment by billyhoiler** [comment]
+1 (coming from BeTheme with Muffinbuilder, this is a major step back regarding google maps integration)

**Comment by bainternet** [comment]
I merged this issue with  #1319, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
