### ISSUE TITLE
Feature Request: Button Gradient

### ISSUE THREAD

**Issue by jayalove** [elementor/elementor#3142]
It would be great to be able to have gradient backgrounds on buttons. (Reg and hover) This is pretty standard and web design people like to use gradients on buttons, especially for marketing purposes. Simple Gradient options like you already have for section backgrounds would be amazing! Thank you

**Comment by silvioghedin** [comment]
+1 ;)

**Comment by mgilank** [comment]
+1 need this

**Comment by Source3Media** [comment]
+1 definitely something that should already exist!

**Comment by forcedlogic** [comment]
+1 it needs to be added

**Comment by hugomedeiros** [comment]
+1 need it too!

**Comment by ICOGiveawaysAlert** [comment]
+1 [need](https://airdropsmarket.com/stayge-airdrop/) this

**Comment by AlessiaFastFwd** [comment]
Definitely need this

**Comment by UncloudedStudio** [comment]
+1

**Comment by erfan-ilyas** [comment]
Found this plugin:

https://wordpress.org/plugins/gradient-button-for-elementor/

**Comment by UncloudedStudio** [comment]
@erfan-ilyas You don't need a plugin, just add some css to the button.
e.g from https://www.cssmatic.com/gradient-generator

**Comment by erfan-ilyas** [comment]
@UncloudedStudio Yeah you are right but only if I knew advanced CSS stuff, I won't be using Elementor at first place!

**Comment by hufer** [comment]
Piotnet Addons For Elementor can make Gradient Text Headings, Grandient Button, Gradient Button Form
https://pafe.piotnet.com/#gradient-text
https://pafe.piotnet.com/#gradient-button

**Comment by atocx** [comment]
+1 definitely want this! In addition background overlay option for buttons as well - same for sections basically.

**Comment by EdwardBlack** [comment]
+1 shouldn't be too complicated I guess

**Comment by MPHood** [comment]
+1

**Comment by kmaradona** [comment]
+1

**Comment by tracyleigh54** [comment]
+1!

**Comment by mountainfly** [comment]
urgently needed!

**Comment by jezweb** [comment]
This is on the advanced tab of the button settings
![gradient button](https://user-images.githubusercontent.com/13249054/62847723-21c78000-bd1b-11e9-98e3-f89d27af7786.JPG)

**Comment by mgilank** [comment]
> This is on the advanced tab of the button settings
> ![gradient button](https://user-images.githubusercontent.com/13249054/62847723-21c78000-bd1b-11e9-98e3-f89d27af7786.JPG)

its background, not the button color.

**Comment by mountainfly** [comment]
Hi,

this sets the background of the container, not of the button itself.
kind regards

**Comment by mountainfly** [comment]
Having a gradient on a button should be not that big of a problem, Elementor, come on!

I tried creating my own "my-button"-css-class and adding it via the "CSS-classes" field in the advanced tab of any element, does not work, effects the container again.

I found a quirky workaround, but this effects ALL BUTTONS on your site, so no way of applying it only to certain buttons, therefore in my case it is useless, because I need at least two different button styles in my recent project.

Nevetheless it might help someone, so here it is:
1. create your desired gradient with an online gradient tool such as https://cssgradient.io/
2. add the following css code to your button (in the "own css" field on the advanced tab):
.elementor-button {
   PUT YOUR GRADIENT CODE HERE
}

kin dregards

**Comment by jdhoneatt** [comment]
> Hi, this sets the background of the container, not of the button itself. kind regards

That is correct, however, if you set the Button Background Color opacity to zero on the Style tab, then then the Container background color set on the Advanced tab will display just fine.  You can also set the border radius of the container on the Advanced tab.

**Comment by shibindinesh** [comment]
> > Hi, this sets the background of the container, not of the button itself. kind regards
> 
> That is correct, however, if you set the Button Background Color opacity to zero on the Style tab, then then the Container background color set on the Advanced tab will display just fine. You can also set the border radius of the container on the Advanced tab.

Yes. This works as a temporary workaround. See example of a gradient button created using the above method:
![gradient button](https://user-images.githubusercontent.com/8279584/66828978-f73eb100-ef6f-11e9-846b-32a8c3824991.PNG)
However, it requires additional work as we have to adjust the margin and you will have to customize it separately for mobile and tab orientation. It would be great if this is added as a feature.

**Comment by Jon222** [comment]
+1 for getting this implemented. Unbelievable this isn't available.

**Comment by DillK** [comment]
+1

#9995  #7227  #5818 #8202 #4676 #3142 etc.

Enhanced Gradient support overall seems to be a common desire, and would be extremely appreciated. Only having two colors for background gradient is too limiting, let alone being able to apply gradients elsewhere. If this gets implemented can we get multi-color support, and just generally more complex gradient options? Yes we can use CSS, but that should be unnecessary ideally.

**Comment by mountainfly** [comment]
Hmm, 2 years in and still unresolved?! *rolleyes* Why is it so hard to implement?

**Comment by gerardreches** [comment]
+1

**Comment by liranCyolo** [comment]
+1

**Comment by liranbp** [comment]
+1

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!
