### ISSUE TITLE
Shaky slider images on internet explorer

### ISSUE THREAD

**Issue by tolba59** [elementor/elementor#3162]
Hi,

I have a slider on this website using elementor slider widget and i'm using Ken Burns effect on all slides.
I noticed that the images are very shaky when viewed from internet explorer while on other browsers it's just fine.
Is there a way to either disable this effect for IE or fix the shaky images?

Thanks
Best regards

**Comment by bainternet** [comment]
@tolba59 

We would need to know/see how you implemented it in order to suggest a workaround. 

Please describe how we can replicate.

**Comment by tolba59** [comment]
Hi ,
Thanks for the response, I just used Elementor Pro slides widget and created 5 slides, and in each slide chose an image and enabled the Ken Burns effect as shown in this screenshot, and it's working great on chrome, FF but is very shaky on IE, you can check the website here http://boylecopper.ie

![image](https://user-images.githubusercontent.com/6570439/34915692-89003438-f922-11e7-8ce2-fb44c94b38d8.png)

Thanks for your support
Best Regards
Eslam

**Comment by bainternet** [comment]
@tolba59 

thanks for your reply,

Its a known issue that IE has problems with CSS transforms like `scale`.

we will have a look.

**Comment by Turanligil** [comment]
+1

**Comment by emv-plus** [comment]
Hi all!
Do we have a solution there already? 
I have a shaking shaky slider on my page too!

**Comment by billyhoiler** [comment]
The Elementor shaky slides problem in IE has been reported more than 2 years ago with no solution to date: https://github.com/elementor/elementor/issues/1370

A fix would be very much appreciated.

**Comment by Aviad-Herman** [comment]
Hi guys,
I'm closing this old thread as we have stopped supporting IE.

**Comment by DavidBenko** [comment]
FWIW, this is probably a dead meme, but I *had* to support IE so this is the answer:

On the element with the ken burns effect background image, add the following custom css under "Advanced":

```css
.swiper-container {
  -ms-transform: scale(1.1);
}
```
