### ISSUE TITLE
🔗 🚀 Feature Request: Table Widget (Duplicate of #1342)

### ISSUE THREAD

**Issue by ddenev** [elementor/elementor#3206]
Elementor currently has a very nice set of widgets but one that is definitely missing is a table widget.

I would like to suggest adding this widget (I am OK if this is a PRO feature, and to be honest this should be a PRO feature IMHO).

Elementor Extras has this widget already (https://shop.namogo.com/elementor-extras/widgets/table/) but I would prefer if this comes from Elementor :)

**Comment by bainternet** [comment]
I merged this issue with  #1342, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your suggestions!
