### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Nav Menu Widget - Different submenu indicators for 2-nd level submenus (Duplicate of #3275)

### ISSUE THREAD

**Issue by ddenev** [elementor/elementor#3225]
Currently the Nav Menu widget has a single option specifying the Submenu Indicator - **Nav Menu -> Layout -> Submenu Indicator** with possible values **None**, **Classic**, **Chevron**, **Angle** and **Plus**. All of them (except None and Plus) are pointing down.

The problem is that the same symbol is used even for 2-nd level submenus, which usually expand to the left/right of the 1-st level submenu and the indicator that points down does not look good.

Would it be OK if you add another option to specify the indicator for 2-nd (and so on) levels of submenus as well as add some horizontal indicators (e.g. ">", "<" and so on)?

**Comment by bainternet** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
