### ISSUE TITLE
🔗 🚀 Feature Request: Nested  repeater (Duplicate of #2955)

### ISSUE THREAD

**Issue by soyket** [elementor/elementor#3246]
Repeater is needed inside repeater

**Comment by soyket** [comment]
[
						'name' => 'icon1',
						'label' => esc_html__( 'Font Awesome Icon', 'bytecodehotel' ),
						'type' => Controls_Manager::ICON,
						'description' => esc_html__( 'If you want to use icofont icon do not select any', 'bytecodehotel' ),
						'default' => '',
						'label_block' => true,
					],	
					[
						'name' => 'icon2',
						'label' => __( 'Icofont Icon', 'bytecodehotel' ),
						'type' => Controls_Manager::TEXT,
						'default' => 'icofont-soup-bowl',
						'description' => 'Get supported icofont class name from <a href="http://icofont.com/" target="_blank">here</a>',
						'condition' => [
							'icon1' => '',
						],
					],

**Comment by bainternet** [comment]
Like you already know form #2955 it's not possible. for now anyway.
