### ISSUE TITLE
✅ 🚀 Feature Request: Nav Menu widget needs more options and  functionality within the widget

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#3275]
I was originally really excited about the Nav Menu widget, but the limitations of creating a header with Elementor becomes very clear, very quickly.

As soon as you start to add a button widget or a search widget to your header, it becomes impossible to make it look good on tablet and mobile. 

It's even impossible to make it look good on different desktop resolutions because columns use a percentage width. So there is no way to make the padding between elements uniform on different resolutions.

**I would like to request that the Nav Menu widget include the option for a button and search icon/box within the Nav Menu widget itself.**

That way, padding between elements would be uniform on all desktop resolutions. And on tablet and mobile, elements could be added to the hamburger drop-down so that I wouldn't end up with such a huge header on mobile like this:

![mobile-menu-elementor](https://user-images.githubusercontent.com/29379115/35203654-3efefae8-ff64-11e7-8f58-a69188f4aee2.png)

**Comment by black-eye** [comment]
I second this.

BTW, this situations is not limited to headers only. There are times I'd like to place the widgets side by side, not only stack them on top of each other or place them in the separate columns.
Something like an "Inline mode" would be really useful.

**Comment by webig** [comment]
also great would be more customizable sub menu, with full screen feature, more menus side by side on dropdown (more columns in one dropdown)... :) or image in dropdown menu and more :)

**Comment by chdonncha** [comment]
Even adding ID's onto the menu items would be helpful, the theme I had ID's on each menu element, just takes away some tedium when editing individual menu items to specific needs.

**Comment by chdonncha** [comment]
ID's on the menu elements would be helpful too for editing them to your needs.

**Comment by michaelnorthern** [comment]
Agreed, really need a search feature WITHIN the menu itself.  Surprised it's not there, seems so obvious.

**Comment by tannedtoni** [comment]
I agree with this as well.  Using columns does NOT work and leaves the button floating somewhere ugly when you resize the window or are viewing it on tablet or mobile.  And, having a CTA in your menu is actually pretty common practice. 

The Astra theme has a spot in the Customizer for a CUSTOM MENU ITEM (about half-way down the page here: https://wpastra.com/docs/primary-header/).  You can add a search, custom text/HTML or a widget.  I haven’t tried the others but the custom text/HTML one allows me to write a little HTML (shown in the screenshot of the Astra link above) and BAM!  I have a menu item IN my navigation.  And, as I reduce my window size or view it on tablet and mobile, the button disappears and becomes a part of the hamburger menu with the rest of the menu items.  

Thing is, I'm not really an Astra fan.  And if Elementor is going to offer up headers and footers, they should offer greater flexibility.

**Comment by zenwebdesign** [comment]
Yes please, I am also trying to build a header with a few icons in a line - like logo, search icon , hamburger and shopping cart all lined up on the mobile devices. It is impossible right now in elementor. Some themes have custom headers and you can choose the one youl like, but I use Astra theme and the options are limited to 2 widgets only in total with Astra header options.

**Comment by smile00000** [comment]
Agreed! I added this feature request: https://github.com/pojome/elementor/issues/5098 and they merged with this one. Hope it gets integrated soon!

Here is a great example of a nice looking dropdown with a top center pointer and info in columns reflecting our feature request from this business we found:

https://www.useloom.com/share/04b594cc3df04a54b46a15cf97179bf1

**Comment by Artneo7** [comment]
I agree. A client just asked for the submenu to be horizontal instead of vertical.

**Comment by pako69** [comment]
Hi

Using percentage width for columns makes your nav widget unusable on different screen width.
So, as I still want to use this Elementor widget instead of using any other plugin, I have completly overriden each width columns to use pixels instead of percentage.

I gave each of columns a CSS ID then each columns is designed with custom CSS. exemple :
```

/* loupe */
#ntls-site-header-search {
    width: 34px !important;
    position: absolute;
    right: 128px;
    height: 40px;
}
/* loupe */
@media (max-width: 768px) {
#ntls-site-header-search {
    width: 34px !important;
    position: absolute;
    right: 152px;
    height: 40px;
}
}
```

This CSS code is used for the search icon you see in my screen shot.

PS: the hamburger menu you see in the mobile version do not come from Elementor because the mobile menu of the Elementor Nav widget is... poor.

I cannot give you a live URL because it's stagging website.

![menu-mobile](https://user-images.githubusercontent.com/28571856/43033914-1d5a9382-8cd3-11e8-844e-decc8105d7fe.jpg)
![menu-old-school_1](https://user-images.githubusercontent.com/28571856/43033915-1d7b1e54-8cd3-11e8-86c4-8bff7651621a.jpg)
![menu-old-school_2](https://user-images.githubusercontent.com/28571856/43033916-1d98fdfc-8cd3-11e8-91db-83ee5757ec46.jpg)
![menu-old-school_3](https://user-images.githubusercontent.com/28571856/43033917-1db74eec-8cd3-11e8-9346-ef664653d00a.jpg)

**Comment by CodyMTX** [comment]
I would like to see the hover effect able to be removed from the top menu items.  GeneratePress offers this feature, but I would like to be able to use Elementor only for designing the headers.  If a menu item has "#" as the custom link you should be able to choose whether you display sub-menu items by hovering over or clicking the top level menu item.

**Comment by jbanne3124** [comment]
hi everyone i keep getttig when i use the nav widget in elementor..
anyone can help me/? i dont really understand php 

Fatal error
: Uncaught ArgumentCountError: Too few arguments to function ElementorPro\Modules\NavMenu\Widgets\Nav_Menu::handle_link_classes(), 3 passed in C:\xampp\htdocs\risenationwordpress\wp-includes\class-wp-hook.php on line 286 and exactly 4 expected in C:\xampp\htdocs\risenationwordpress\wp-content\plugins\elementor-pro\modules\nav-menu\widgets\nav-menu.php:1126 Stack trace: #0 C:\xampp\htdocs\risenationwordpress\wp-includes\class-wp-hook.php(286): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu->handle_link_classes(Array, Object(WP_Post), Object(stdClass)) #1 C:\xampp\htdocs\risenationwordpress\wp-includes\plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 C:\xampp\htdocs\risenationwordpress\wp-content\themes\fusion\inc\vendor\wp-bootstrap-navwalker.php(116): apply_filters('nav_menu_link_a...', Array, Object(WP_Post), Object(stdClass)) #3 C:\xampp\htdocs\risenationwordpress\wp-includes\class-wp-walker.php(145): WP_Bootstrap_Navwalker->start_el('<li itemscope="...', Object(WP_Post), 0, Object(stdClass)) #4 C:\xam in
C:\xampp\htdocs\risenationwordpress\wp-content\plugins\elementor-pro\modules\nav-menu\widgets\nav-menu.php
on line
1126

**Comment by woodynco** [comment]
Nav Menu widget has a very limited use, basically only usable as the main menu. 
If I want to use it as a sidebar or footer menu, it is unusable due to mobile display always switching to dropdown or hamburger.
If I use the code from #3064 to disable dropdown, it messes up the main menu that I actually want to the dropdown.

It is a great widget that could be really useful as a switcher between multiple language variations (e.g. between two options only at above header area), sidebar menu, footer menu. But lack of options make it impossible or very hard to do.

I would really like to see more options in nav menu.

**Comment by jbanne3124** [comment]
thanks men

**Comment by amindiary** [comment]
+1
mega menu needed

**Comment by alirexa** [comment]
Also a menu item separator is a missing feature! with the ability for selecting the separator's character.
Something like : 

> About | Portfolio | Contact

**Comment by farietta** [comment]
Like most everyone else, I think there should really be horizontal sub-menus. Multiple clients have requested this and I haven't been able to deliver on the look/feel that they want.

**Comment by JoeDarko** [comment]
Please, at least give us these basic things:

- Horizontal sub-menu
- Ability to disable hamburger toggle (for vertical menu)
- Menu item separators

Menu widget is super important and right now it's very limited. After so many requests something so obvious is still not implemented. 

Like many others in this thread i've been asked by my clients to make horizontal submenu and it's very hard to explain to them that something so basic can't be done with the system i use. 

I don't want to be negative, but this is just another exaple of Elementor focusing on pumping out many "cool" new niche features and forgetting about the most basic stuff. What's the point of fancy integrations if you still can't build some basic menu layouts. I also think improving current widgets should be as important as releasing new ones, which is not the case right now.

I'm a very heavy Elementor user and there is SO MANY basic things i'm waiting for. Instead most new features are like "Cool, but only small minority of people are gonna use it and none of my clients are ever going to request this". Why not focus on the things that are going to benefit the most people first?.

So... that turned into a tantrum.

**Comment by fery379** [comment]
true
we need better nav menu
Also previous widgets need to be revamped

**Comment by rumyantsekov** [comment]
I would love to see this integrated, instead of using plugins that add the widget to the Elementor list: https://www.megamenu.com/documentation/elementor/ or jetmenu

**Comment by Felipe-NS** [comment]
Vertical Nav Menu +1

**Comment by michaelnorthern** [comment]
@JoeDarko

Agreed, basic menu functionality is missing, really frustrating.

Message to Elementor HQ: drop the superfluous / flashy feature rollouts —
focus on core functionality that's used on most sites. Beyond the weak menu
issues, here's another example: the tablet / mobile previews are an
inaccurate mess and don't even tie-in to the assigned break points.
Useless. Must use Chrome Developer Tools to preview the site.

**Comment by Jordidriesen** [comment]
Megamenu options and vertical menu options (off-canvas) are certainly elements that need to be added in order to replace menu's form well-build themes. Complex menu's are a nightmare in Elementor since there aren't enough options to design it in a userfriendly manner.

**Comment by Artneo7** [comment]
Mega menu option would be great. If the website's menu has more than 10 subpages, it's better to show content divided in 02 columns with 05 options each one.

**Comment by gitlee99** [comment]
Please add a megamenu. This will make sites with more than 10 pages so much easier to navigate.

**Comment by taminoferrari** [comment]
Yes please. Megamenu would be so great. All the plugins which offer mega menu for elementor do have some big drawbacks.

**Comment by WebMagi** [comment]
Elementor Pro does not have the ability to design menu systems with background colors for the "Normal" state of individual menu button items. With this limitation in place, Elementor can only do a very basic look and feel for the top "Normal" menu state, with the background being provided for the entire bar (under Advanced), rather than for each individual button item.

For example, by itself, Elementor Pro cannot create this very simple menu system https://webmagi.com/clients/ufs/ (Not in its entirety).

You don't feel this should be a feature?

**Comment by anastk** [comment]
I really like Elementor Pro but lacking the functionality to design mega menus and add widgets inside of navigation menus is a big setback. I don't want to purchase an additional plug-in for the mega menu, are there any plans to include this feature out of the box in Elementor Pro in the near future?

**Comment by ellegaarddk** [comment]
Add text to the hamburger menu. ![screenshot_31](https://user-images.githubusercontent.com/3447686/53338146-4366b380-3903-11e9-86f3-b16d4a6a2002.jpg)
Add the moment we can choose between have hamburger or full menu. I could be just be a standard "MENU" added before or after the hamburger. Several has reported, that the hamburger icon in itself isn't enough and will confuse users.  It's fancy and makes nice design - but it will damage UX.
[https://www.nngroup.com/articles/hamburger-menus/ ](https://www.nngroup.com/articles/hamburger-menus/ )

**Comment by MattOndo** [comment]
Yes! Please make this a thing, nav menus are very ugly on mobile when the search is included. The ability to add a search box to to the nav drawer on mobile would resolve this perfectly!

**Comment by anastk** [comment]
I am afraid the team is letting go of this feature and replacing it with popups as a solution. Did you get the latest newsletter from the team? It literally says "Mega Menu? That's OLD NEWS! 
We created a tutorial to help you make an eye-popping menu using the Popup Builder. This tutorial will open your mind in terms of what can be done with popups." 

https://elementor.com/blog/responsive-menu-popups/

So I decided to address this claim here: 

Claiming that popup functionality equals mega-menu isn't acceptable. You can't compare this workaround to an actual mega menu. Let's say we need the mega menu to appear on hover, and we have 3 different top menu items like Products | Services | Corporate... The pop-up toggle, in this case, is buggy. I tried designing a separate popup for each of the multiple main menu items, when I click on one the menu it opens the associated popup and when I click on another main menu item the old popup is still opened in the back and you end up with 2 popups opened on top of each other, the user then needs to toggle the two popups off again, which is totally against UX principles...

Also, how to set a fixed position for the popup? in other words, the popup needs to appear relative to the main menu position on the screen, is it doable? it should always appear under the top menu section even on a sticky menu design... 

Can you at least show a tutorial solving these issues before claiming that this is better than a mega-menu design? 

I love the popup feature don't get me wrong, but this doesn't solve the mega menu need and I didn't want this newsletter to justify the case for Elementor dev team to not support the work on the mega menu feature.

**Comment by JoeDarko** [comment]
Would be great if somebody from Elementor told us if they're working on this, or if it's not something thats going to come anytime soon. The demand is large and revamping the nav menu widget is long overdue.

**Comment by fery379** [comment]
WE NEED MEGA MENU AND IT IS *NOT *OLD NEWS.

**Comment by MaxLynam** [comment]
just having a menu descriptions would solve some issues (as most else can get done with a couple of plugins) .... but, why would menu descriptions not be there already ??

**Comment by alriksson** [comment]
- Add click event to open drop down
- Possibility to split into 2 columns of a menu drop down.
- Animation fade in options

**Comment by MichaelDarko** [comment]
Just to summarize the most basic and needed stuff that people are requesting:

- Vertical menu (No hamburger on mobile.)
- Vertical menu - Show subcategories on click (Like it now works on mobile menu.)
- Horizontal submenu (Subcategories in X amount of rows.)
- Menu item dividers (About | Portfolio | Contact - Pretty important visual element.)
- Off canvas menu
- Add text before/after the hamburger icon

- Mega menu (Maybe could be a separate widget.)

Again, nav menu is one of the most important building blocks of a website, so we really should have a state of the art nav menu widget that can replicate any possible nav menu layout.

Elementor could find some inspiration here: http://jetmenu.zemez.io/

**Comment by tannedtoni** [comment]
> Just to summarize the most basic and needed stuff that people are requesting:
> 
> * Vertical menu (No hamburger on mobile.)
> * Vertical menu - Show subcategories on click (Like it now works on mobile menu.)
> * Horizontal submenu (Subcategories in X amount of rows.)
> * Menu item dividers (About | Portfolio | Contact - Pretty important visual element.)
> * Off canvas menu
> * Add text before/after the hamburger icon
> * Mega menu (Maybe could be a separate widget.)
> 
> Again, nav menu is one of the most important building blocks of a website, so we really should have a state of the art nav menu widget that can replicate any possible nav menu layout.
> 
> Elementor could find some inspiration here: http://jetmenu.zemez.io/

Maybe Elementor just need to buy out the JetMenu plugin so they can study it and incorporate it into Elementor Pro as a permanent feature?

**Comment by envyyycreative** [comment]
How is this still open after over a year?! With so many people pouring money into Elementor we still can't get a decent nav menu - **the first thing beginner devs learn to create**. This should be the number 1 priority for future updates. Please please take this seriously Elementor ;_;

**Comment by pako69** [comment]
That’s the reason why I do not use a all elementor nav menu but wp Astra thème or use the plugin Responsive Menu Pro... :-(

**Comment by ctlsadmin** [comment]
Definitely need a way to make sub menus inherit their width from the parent menu item. Adding padding the sub menus doesn't cut it at all.

Seems crazy that Elementor doesn't already have this basic function. I'd hate to pay for another plugin to make an Elementor feature work properly.

**Comment by VenkmanNL** [comment]
+1 for more functionality in the nav menu in general but with the arrival of Elementor 2.6 with custom icons can I please get an option for a custom icon (instead of the thick hamburger)?

**Comment by xavitorrentsDOTes** [comment]
> 
> 
> +1 for more functionality in the nav menu in general but with the arrival of Elementor 2.6 with custom icons can I please get an option for a custom icon (instead of the thick hamburger)?

I was login here to say the same!

**Comment by desparkflux** [comment]
Please how do I make menu nav bar... How do I integrate it on my web?

**Comment by VenkmanNL** [comment]
> > +1 for more functionality in the nav menu in general but with the arrival of Elementor 2.6 with custom icons can I please get an option for a custom icon (instead of the thick hamburger)?
> 
> I was login here to say the same!

For Xavi and all others that want a custom icon (font awesome in this example) add some custom css:

`//closed hamburger status//.eicon-menu-bar:before {
        font-family: fontawesome;
        content: '\f1fd';
}

//opened cross status//
.elementor-menu-toggle.elementor-active i:before {
    font-family: fontawesome;
    content: '\f1fd';
}`

Found it thanks to this link: https://stackoverflow.com/questions/20782368/use-font-awesome-icon-as-css-content

**Comment by mrbenjaminjo** [comment]
Iconic release doesn't let me choose my own hamburger icon. Instead I have to load 70k of e-icon. C'mon guys, that's 15% of my total page payload! GET REALZ!

**Comment by wpacademy** [comment]
> also great would be more customizable sub menu, with full screen feature, more menus side by side on dropdown (more columns in one dropdown)... :) or image in dropdown menu and more :)

Mega Menu feature would be great, so we don't have to use 3rd party plugins and we can build more advanced templates for Elementor prol

**Comment by teoeugene** [comment]
I agree that a robust and much more options/customisability is needed for one of the Nav Menu - one of most significant element in a website.

Recently I tried to do something simple with the menu - having one that I can style properly without meddling with CSS. Furthermore, I had another nav menu with the same menu at the footer, but I'd like to set to only the parent level (without submenus), which I can't. I had to create another menu specifically for the footer without all the sub-level to address something as basic as this.

**Comment by Zach-Toth** [comment]
Also needed (which I simply can't believe hasn't been addressed yet) is the ability for a sub-menu in the vertical nav layout to push the main menu items below it down. The same way every vertical sub menu ever works... Vertical layout is useless if you have any sub-nav items. The sub dropdown is displayed behind the main menu, how was that not immediately identified as an issue when the vertical layout was rolled out??

**Comment by thomasmalley** [comment]
Right!@Zach-Toth The [introduction blog-post](https://elementor.com/blog/introducing-nav-menu/) only contains vertical Menus without Sub-Menu-Items 🙈 now I can guess why. 

Even very small web projects often need 2nd level pages. It would be greatly appreciated!

**Comment by djnolder** [comment]
I also posted this on #4991 

A temporary solution for full width submenus and menu-item alignment.

your nav menu > Advanced > Advanced > CSS Classes = "full_center_dropdown"
your nav menu > Advanced > Custom CSS =
.full_center_dropdown nav ul {
min-width: 100% !important;
}
.full_center_dropdown nav ul a {
justify-content: center;
}

This will give your submenus a minwidth of 100%, and will center the menu items. If you want to right-justify the menu items change "justify-content: center;" to "justify-content: flex-end;"

Hopefully, we will one day git this update.

**Comment by rodolphebertozzo** [comment]
+1

**Comment by mira-fraiyo** [comment]
I've been looking into a solution to this using custom CSS, but something I would like, if it's possible, is for menu items with children to be able to inherit each other's width. For example, if the parent item is the widest, the child items are also that length, but if the child items are the widest, then the parent item is the width of the children so everything is a little more aesthetically pleasing. I've been trying to accomplish this on a plain WordPress navigation menu with no luck, so I'm not sure if it's even possible, but at the very least it would be nice for the child items to be the same width as the parent and not be smaller/bigger than it. Currently my child items are wider than the parent and the above solution doesn't work for me.

**Comment by gerardreches** [comment]
+1 for search in nav menu

**Comment by mrbenjaminjo** [comment]
It would make sense in the context of Elementors "Iconic" release, if the Hamburger and Close icons for the vertical mobile nav could indeed be SVG's the are user selected. Rather than being forced in to using the defaults.

I have eicons and font awesome dequeued as part of my speed optimisations, this forces me to build out a popup based mobile menu when really the default would be fine IF I could pick icons.

**Comment by uzimedia** [comment]
Typography is outside the hover options

**Comment by derKh4N** [comment]
and this would also be very convenient for vertical dropdowns!
https://www.w3schools.com/howto/howto_js_dropdown_sidenav.asp

**Comment by sermalefico** [comment]
Megamenu

**Comment by MichaelDarko** [comment]
Please, guys, do something about the horizontal sub-menus. You can't build a large navigation with the current vertical dropdowns. If you have a lot of items in the dropdown, you need to display them in rows, not in one massive column.

**Comment by srpotman72** [comment]
Hi, yes it would be great to have Elementor enhanced with this. We had it also in the following item:
https://github.com/elementor/elementor/issues/9224

**Comment by rodrigocarlos** [comment]
When opening the menu, the entire header is pushed down: https://prnt.sc/w2glyq

And it is only possible to create a simple menu. It is not possible to insert columns, images, texts (with or without link), ... The resources are very limited.
Here is an example of a more robust menu where Elementor could offer resources for us to create a similar one:
https://prnt.sc/w15ra8
https://prnt.sc/w15qer
https://prnt.sc/w15qp6

**Comment by maurocarreraok** [comment]
Nav Menu should have a LOT of more options. Aligments, Colors in different devices, background images, icons ajustment on menu and submenu, styles of buttons, etc.

**Comment by yorkfrog** [comment]
Until Elementor upgrade things, you might consider looking at 'OoohBoi Steroids for Elementor' plugin.  It's 'Breaking Bad' feature gives you complete control over column widths, from the Elementor properties panel, in any CCS unit you want to use and define custom stacking order for columns on diff devices as well as a lot more.  I've found it really useful and sounds like it solves a few of the issues outlined here.
See https://wordpress.org/plugins/ooohboi-steroids-for-elementor/
Lots of video tuts on his Youtube channel.  -C

**Comment by yorkfrog** [comment]
Until Elementor upgrade things, you might consider looking at 'OoohBoi Steroids for Elementor' plugin.  It's 'Breaking Bad' feature gives you complete control over column widths, from the Elementor properties panel, in any CCS unit you want to use and define custom stacking order for columns on diff devices as well as a lot more.  I've found it really useful and sounds like it solves a few of the issues outlined here.
See https://wordpress.org/plugins/ooohboi-steroids-for-elementor/
Lots of video tuts on his Youtube channel.  -C

**Comment by tomas-eklund** [comment]
A native Mega Menu is a much wanted feature. I've bought a third party plugin to provide this feature for now but the plugin seems to have some bugs and I cannot fully customize it like I want. Also the mega menus it creates doesn't seem to be accessible. I would really like this feature to be native as it is such a core feature of a modern web site.

First I tried using the Elementor popup builder to create a mega menu, and I got pretty close, but I couldn't get it to work fully with regards to positioning relative to the main menu. This experience leads me to believe that most of the things needed to have a native Elementor mega menu are already in place and it shouldn't be too hard to implement.

**Comment by fabianenzensperger** [comment]
Just do it! 👀

**Comment by soulfulwater** [comment]
40 months later.... still waiting for a better menu widget.

**Comment by anastk** [comment]
> 40 months later.... still waiting for a better menu widget.

On the same note WooCommerce widgets are still a joke in terms of styling options, they always release half backed features and then jump to a new thing, then repeat...

Apparently in the last 40 months they were busy planning the price increase...

**Comment by mhsdesign** [comment]
Hi,

I have Elementor Pro and want to use a a mega menu like on the homepage: [https://elementor.com/](https://elementor.com/)
![image](https://user-images.githubusercontent.com/85400359/129025536-b3381257-a23c-4c25-adb0-25a228996969.png)


and how can i use buttons at the end of the mobile menu?
![image](https://user-images.githubusercontent.com/85400359/129025701-850f1ae1-547f-46f7-8d59-ef354397f43d.png)


i cant find this Feature in the Nav Menu Widget.

**Comment by teoeugene** [comment]
> Hi,
> 
> I have Elementor Pro and want to use a a mega menu like on the homepage: https://elementor.com/
> 
> and how can i use buttons at the end of the mobile menu?
> 
> i cant find this Feature in the Nav Menu Widget.


@mhsdesign The mega menu feature is not available yet but it was teased as an upcoming feature this year in a promo video a few months back.

**Comment by mbaierl** [comment]
Yeah, I guess they test their own features before they release them... which is good, if they eat their own dogfood ;-)

**Comment by mhsdesign** [comment]
@teoeugene do they have a public roadmap?

**Comment by mhsdesign** [comment]
> @mhsdesign @rodrigocarlos , you can create these effects using popups linked to menu items. See https://elementor.com/help/how-to-create-a-responsive-popup-menu/ and related help topics for details. -C

that gets way to messy ^^ but thanks.

**Comment by d19dotca** [comment]
> @teoeugene do they have a public roadmap?

Not exactly, but you can use the Milestones feature on GitHub to get an idea sometimes (but it's not always updated properly). They did do a sneak peek video though on everything they expect to have released by the end of 2021, you can check their video out on their YouTube channel. So it was a bit of a roadmap as in we know what to expect for 2021.

**Comment by 79ho3ein** [comment]
Hi everyone
Is there any news about this?
I'm looking forward to the ability to insert icons in the nav menu widget.

**Comment by musosoft** [comment]
#5950 got closed and merged into this, but can't see any reference or discussion implementing the Nav menu widget Description option here. What's the current status, please?

**Comment by anastk** [comment]
We are closing on 2021 and there is no progress on this yet although "Mega menu" was promised in this official Elementor video early on this summer...
https://youtu.be/zUBG27llWKQ?t=6 

I was hoping to see this in 3.5 or 3.6 but knowing how the project is going I doubt to see Elementor with a proper menu solution anytime soon.

**Comment by rodrigocarlos** [comment]
I believe Elementor is planning to only offer menu creation through the popup feature.
The menu creation feature is not a complex thing to develop, so this delay by Elementor in providing a menu creation feature is strange.

**Comment by fabianenzensperger** [comment]
+1000000

**Comment by nesoor** [comment]
Thanks DOrShahar for merging my topic.

**I wrote in my topic:**
I would like to see a Mega Menu and a off canvas menu in Elementor.
I know there are many plugins out there that could do the job but having this feature implemented in Elementor would make life so much easier.

**Comment by mhsdesign** [comment]
i mean there are still 12 days left  😆😂

**Comment by dennylai1990** [comment]
+1 for better Nav Menu Options. Still requires other plugins or themes to have mega menu, slide out menu (mobile) and a menu with breadcrumbs (see https://crocoblock.com/plugins/jetmenu/)

**Comment by Cortexian** [comment]
It's 2022 now. I'm finding the restrictions of the current Nav Menu limiting.

**Comment by SaltedLevity** [comment]
Wish we could get an update on when to expect the mega menu that was teased. I think it's been 9 months? More? It's not even in the dev or beta versions which doesn't bode well...

**Comment by anastk** [comment]
It's planned for 2032 😂

**Comment by fabianenzensperger** [comment]
> It's planned for 2032 😂

Actually already for 2021.. But it seems to take a while. If I know something, I'll write it here. I'm shortlisted for testing this feature.

**Comment by joehdevwp** [comment]
Why are there no responsive controls for alignment on the Nav Menu widget???

![image](https://user-images.githubusercontent.com/64614431/182038155-6bba6ba5-b201-4348-a243-f84ef5befc78.png)

Also why is there no option to hide the submenu on smaller screens?

**Comment by anastk** [comment]
> Why are there no responsive controls for alignment on the Nav Menu widget???
> 
> Use case here is a Footer menu: vertical, left aligned columns on desktop but centered (horizontally) on tablet/mobile
> 
> ![image](https://user-images.githubusercontent.com/64614431/182038155-6bba6ba5-b201-4348-a243-f84ef5befc78.png)
> 
> Also why is there no option to hide the submenu on smaller screens?

No worries, it's scheduled for 2033, so only 11 years left to introduce the Mega menu feature. Elementor team was busy hiking the price and introducing the all-new revolutionary "number scrubber for every numeric field feature", the update we've been eagerly waiting for so long for.

**Comment by parfilov** [comment]
Abandon Hope All Ye Who Enter Here

**Comment by Michaelgimii** [comment]
Megamanu seems to be scheduled for version 3.11. it is so? https://github.com/elementor/elementor/pull/20773

**Comment by toineenzo** [comment]
Mega menu would be nice, this is already in the works with the nested elements experiment. But would rather be able to change indentation of sub items and change icon of sub menu icon

**Comment by Michaelgimii** [comment]
I think Elementor has had the Mega manu widget for a long time. But they needed to make the container stable first and then release mega menu.
In version 3.12, the container will be enabled by default, and most likely, megamenu will come in V3.12.

**Comment by SolunaCG** [comment]
Any update here? Unfortunately the new megamenu isn´t really solving this problem for me... The mobile menu needs a whole revamp imo. I´d be great to have something like a nested mobile menu which we can design just like we can with the new "Tabs"-widget. The current mobile menu is so basic, it already hurts... Just to name a few things I´d love to see here:

- option to load templates within the menu (-> Crocoblock hamburger menu)
- multiple animation presets for the menu container (slide in, zoom in, etc.)
- multiple animation presets for the menu toggle icon (-> https://unlimited-elements.com/animated-hamburger-icon-for-elementor/)
- easy way to make the menu full width and full height for all responsive devices
- NO responsive settings like we already have them in the "Tabs"-widget or the new megamenu! Please get rid of the automatic responsive design for mobile devices! That prevents us users from freely designing the widgets for those devices.

Please, Elementor, add this to your roadmap! 
Imo the mobile menu is still the weakest point when working with Elementor. No matter how great your websites are with Elementor, that old looking mobile menu has always ruined the whole mobile design for our clients because of how simple the current mobile menu is....
