### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Allow to customize the Space Between the Dot Pagination of the Image Carousel widget (Related to #3096)

### ISSUE THREAD

**Issue by hzesen1221** [elementor/elementor#3277]
The range of the Dot Size in Image Carousel is set to be 5 - 10. I am curious what's the logics behind setting this range since many browsers do not support font size less than 12px. To me, I got a PC and a Mac. This range works on my Mac, but on my PC, running Chrome on Windows 7, they all just render as 12px to me.

In contrast, the Dot Size in Media Carousel seems to be implemented differently since it is not using fontawesome, but a self crafted shape. Setting Dot Size in this case simply updates the shape's height and width together. So, for media carousel, the Dot Size under 12px work for both PC and Mac.

Not a big deal since I can hack the core a bit to update the range, but realize I should at least let you guys know about this.

**Comment by bainternet** [comment]
Thanks we will look into it.

**Comment by ramiy** [comment]
Related #3096

**Comment by nicholaszein** [comment]
Hello there @hzesen1221!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.26.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
