### ISSUE TITLE
I would like to see more customization options for the portfolio and gallery widget

### ISSUE THREAD

**Issue by Christian0002002** [elementor/elementor#3318]
I am making a photography site for a client. I would love to see some of the options of the portfolio widget integrated into the gallery widget. I really like how you can add categories to the posts and have the categories displayed as a nav menu over the pictures. The only reason I cant use the portfolio widget is that you can't put a lightbox link instead of a link to posts. Otherwise, it would be perfect for an image gallery. So what I would like to see is for the gallery to be able to categorize images and have the website visitor select categories in a nav menu and when they press on the image, the pics open in a lightbox. I really like the animation when switching between categories. Also, a justified image gallery option would be nice:)

**Comment by Henry8493** [comment]
I´m not entirely sure this feature request https://github.com/pojome/elementor/issues/4013 is on the same page as this one. I would like to have the possibility to open portfolio posts in a Lightbox too instead of loading them on a new page. That would be a clean, comfortable way for users to go through posts without leaving the beautiful portfolio grid.

**Comment by lsaewitz22** [comment]
New to posting; hopefully I'm doing it right? 

I would also like to see a click on a portfolio gallery open into a *lightbox* vs. a page, but not just a lightbox of the image. It'd be great to also have the option to drag & drop widgets in to the lightbox to make almost a mini-page in a lightbox. 

Example: I'd have an image on the left, and on the right I'd have information about the image, perhaps an embedded video, link to more information on the project, etc.

**Comment by wenzelpro** [comment]
The new gallery pro widget from the lates update (Elementor Pro 2.7.0) solved many of the requests in this thread. This is awesome!

However, I would like to see the same update to the Portfolio widget. I want more control on Titles and Excerpts. I.e. to have them visible at all times and disappearing on hover.
