### ISSUE TITLE
{suggestion] inherit values of responsive settings

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#3356]
when adjusting responsive settings mainly for margins and padding, the formerly set custom values should appear in the according boxes. e.g. when set custom padding for section on desktop and and going to adjust them for tablet or phone, the inherited values just should be displayed in light grey to indicate the (before set custom) inherited values.
so for major adjustments there would be no more switching back and forth with time-consuming viewchanges to see what was has been set already.

just like the way you do on several other occasions with elementor-given standard values.
if this could be extended to all places where appropriate - even better.

**Comment by MickCreates** [comment]
Yes please!

I waste so much time switching between responsive modes just to see what values are being inherited in Tablet & Mobile views.

Wherever a value is inherited, it could be displayed as light grey as suggested in the OP, or additionally it could be _italicised_ for additional cognitive recognition that this is an inherited value.

**Comment by webstarspro** [comment]
> Yes please!
> 
> I waste so much time switching between responsive modes just to see what values are being inherited in Tablet & Mobile views.
> 
> Wherever a value is inherited, it could be displayed as light grey as suggested in the OP, or additionally it could be _italicised_ for additional cognitive recognition that this is an inherited value.
> 
> For example:
> ![image](https://user-images.githubusercontent.com/5745047/60227449-b93f5380-98d2-11e9-8784-f3641a1d3337.png)

I agree with you 100%.
I also wait so much time switching these options.
It makes me angry - when I have to switch thousands of time what is the value on computer view and then set.

These inherited values should be displayed and grayed all the time.

**Comment by webstarspro** [comment]
+1000

**Comment by MickCreates** [comment]
I feel we need to revisit this again as the new method for selecting a responsive view has introduced an additional click. So now more than ever we need some sort of visual aid so that we aren't constantly clicking between views to see what values are being inherited.

**Comment by dasigna** [comment]
... some of the things cant comprehend at all.
real issue, really annoying, clear ui problem, complicates things every day - no reaction! since ...?

running out of ideas completely ...

**Comment by black-eye** [comment]
+1

**Comment by MichaelDarko** [comment]
+1

**Comment by DorShahar** [comment]
Hi Camps.
We are working on the specifications of this feature. I hope that in a few weeks you will be able to see live!
Stay tuned

**Comment by Elsteck** [comment]
@arielk There was an interesting presentation of Paul Lacey at the Pagebuilder Summit 2020, Modern mindset techniques for page builder advanced mobile optimisation, that may be inspiration for a solution for rendering designs as intended on all possible sizes of mobile devices. It was nothing short of ingenious in its simplicity (css) I am sure someone within your organization has made an account for this summit.

**Comment by igorchernenko92** [comment]
+1

**Comment by fabianenzensperger** [comment]
Ehhh yes, this thread is underrated. This would be great. Sometimes it is so hard to understand where is the value not correct. 😅

**Comment by zeinnicholas** [comment]
Finally! 3 years later! 🙌

**Comment by datverse** [comment]
Hi, can you add this feature for default values too?
Example: 
- Default Marging of Section is 0px.
- Default Padding of Column is 10px.
- When a Section set Column Gap = No Gap => Default Padding of Column in this Section is 0px.

Thanks.

**Comment by paauserrat** [comment]
> Hi, can you add this feature for default values too?
> Example: 
> - Default Marging of Section is 0px (placeholder value).
> - Default Padding of Column is 10px (placeholder value).
> - When a Section set Column Gap = No Gap => Default Padding of Column in this Section is 0px (placeholder value).
> 
> Thanks.
> 

Interesting and useful

**Comment by simonclay** [comment]
This is still an issue for 'Margin' in inspector. Values set in higher breakpoints are not shown in the Inspector for 'Margin'.
