### ISSUE TITLE
[Improvement] Progress Bar widget: Add more styling options

### ISSUE THREAD

**Issue by drank** [elementor/elementor#3413]
Please consider adding more styling options to the Progress Bar widget.

Some suggestions that come to mind:

- Rounding of corners for the bar
- Height of the bar
- Gradient colors for the progress bar color options
- Placement of the progress percentage: e.g. top-left, top-center, top-right, center-left, center, center-right, bottom-left, bottom-center, bottom-right
- Typography for the progress text
- Typography for the progress percentage

Anything else, anyone else?

**Comment by JoelEadeDesign** [comment]
I've been using custom CSS to work around this for a while. Any chance you can just add the Typography for now?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!
