### ISSUE TITLE
Feature Request – Import text as blocks

### ISSUE THREAD

**Issue by nelsonguda** [elementor/elementor#3571]
I am sure people are working hard at integrating Elementor with Gutenberg. One thing I think should be a priority is creating paragraph based blocks from text the way Gutenberg does. When I take an existing page and edit it with Elementor, it would be VERY useful if the text separated itself into blocks based on paragraphs rather than opening as one solid block of text. Or you could give an option in the text widget to break a block based on paragraphs.Even with a text block created inside Elementor this could be useful. 

Additionally, if you create code to break text into blocks based on <p> or <br>, it would be an easy next step to automatically format other block types such as video links, headings, code, etc. This would give Elementor a huge advantage as Gutenberg is adopted. 

Nelson
--

**Comment by bainternet** [comment]
@nelsonguda 

This is something we are thinking about, we are just waiting for Gutenberg to be something more robust in the core.

**Comment by arielk** [comment]
Sorry, but for now this is not possible, maybe in the future we'll add this feature.

Thanks for your feedback!
