### ISSUE TITLE
Feature Request: Responsive Drawers: Search, Hamburger, Login

### ISSUE THREAD

**Issue by smile00000** [elementor/elementor#3638]
Feature Request/Is this possible now?: Responsive Drawers: Search, Hamburger, Login

Really love how these responsive drawers are at this site: https://www.self.com/

Search: Clicking the search button brings down a drawer bar from the top to search instead of a popup full screen window which can be kind of annoying.

Hamburger: Brings down a drawer menu bar from the top with image icons and two level hierarchy

Login:  Brings down a drawer bar from the top to login instead of having to open up another page.

**Comment by bainternet** [comment]
Closing as all of this is possible with Elementor Pro Popups.

thanks.
