### ISSUE TITLE
Feature Request: noopener for links opening in a new tab

### ISSUE THREAD

**Issue by jokr0815** [elementor/elementor#3642]
Hi,

please add the rel="noopener" Option to the the element, if we add a link which is openening in a new tab.

Thanks and Kind regards
Jo

**Comment by OffCorner** [comment]
THIS. Please just add this option when editing a link. It really shouldn't be a big issue to implement. It would also increase the google pagespeed insights score (in the "best practices" category)

**Comment by rumyantsekov** [comment]
Please, let us know when this will be implemented. The built-in Audit in Chrome reports the error:

Links to cross-origin destinations are unsafe
Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. Learn more...

**Comment by bvbmedia** [comment]
Google Chrome Audit Best Practices:

Links to cross-origin destinations are unsafe
Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. Learn more.

**Comment by bvbmedia** [comment]
I only needed this on the button element.

To fix it I opened the file:
wp-content/plugins/elementor/includes/widgets/button.php

And changed:
if ( $settings['link']['is_external'] ) {
	$this->add_render_attribute( 'button', 'target', '_blank' );
}
if ( $settings['link']['nofollow'] ) {
	$this->add_render_attribute( 'button', 'rel', 'nofollow' );
}

To this:
if ( $settings['link']['is_external'] && $settings['link']['nofollow'] ) {
	$this->add_render_attribute( 'button', 'target', '_blank' );
	$this->add_render_attribute( 'button', 'rel', 'noopener' );
} else {
	if ( $settings['link']['is_external'] ) {
		$this->add_render_attribute( 'button', 'target', '_blank' );
	}
	if ( $settings['link']['nofollow'] ) {
		$this->add_render_attribute( 'button', 'rel', 'nofollow' );
	}
}

**Comment by rumyantsekov** [comment]
Thank you!

**Comment by lucafagherazzi** [comment]
+1

**Comment by bvbmedia** [comment]
I have written more patches on my blog:
https://www.basvanbeek.nl/wordpress/elementor-noopener-for-links-opening-in-a-new-tab/

**Comment by alriksson** [comment]
@bvbmedia Would be better with a php snippet than alter the main and parent code.

**Comment by alriksson** [comment]
+1

**Comment by cmsbased** [comment]
> if ( $settings['link']['is_external'] && $settings['link']['nofollow'] ) {
> 	$this->add_render_attribute( 'button', 'target', '_blank' );
> 	$this->add_render_attribute( 'button', 'rel', 'noopener' );

We toggle `nofollow` + `external` checkboxes and get `noopener` alone? Why not both `nofollow` and `noopener`? If I check `nofollow`, I would expect it to be present in the output.

**Comment by stijnvanouplines** [comment]
+1

**Comment by Bilal-io** [comment]
+1

**Comment by OCpublishing** [comment]
I need this too when '_blank' parameter is used, but **noopener only**
**DO NOT add noreferrer** please though. Not sure all affiliate programs trackers will still be 100% operational with is.

Any ETA on this? It seems sounds like a real security issue and has not been implemented for more than a year

**Comment by alriksson** [comment]
@OCpublishing 

> Does rel=”noreferrer” Affect Affiliate Links in WordPress?
> The rel=”noreferrer” does not affect affiliate links in WordPress. Some users believe that it does because rel=”noreferrer” prevent passing the referrer information to the new tab.
> 
> However, most affiliate programs provide you with a unique URL that has your affiliate ID. This means your affiliate ID is passed along as a URL parameter for the other website to track.
> 
> Secondly, most affiliate marketers use a link cloaking plugin for their affiliate links.
> 
> With link cloaking, the affiliate link that your users click on is actually your website’s own URL which then redirects users to the destination URL.

**Comment by OCpublishing** [comment]
@alriksson 
Very true.
Unfortunately I do not use Cloaking as it is against some affiliate programs rules 'You will not cloak, hide, spoof, or otherwise obscure the URL of your Site containing Special Links'. I think we all know which rules I am referring to.
I am quite sure this is not an issue for the big affiliation programs but I am not quite sure with small ones I may work with from time to time.

But the real issue is the noopener issue, which may be a serious regarding the JavaScript window.opener feature.
Do not take my word for it though. I am far from being an expert on this. I just read some technical explanations on internet.

**Comment by shimsa** [comment]
Why this simple thing is still not implemented? WordPress add target="_blank" rel="noreferrer noopener" automatically. Why Elementor is not doing the same? Or better would be offer checkbox in Elementor widgets.

Thank you for implement such a thing.

**Comment by stijnvanouplines** [comment]
This plugin does a great job! https://wordpress.org/plugins/wp-external-links/

**Comment by joaonew** [comment]
+1

**Comment by kovou** [comment]
+1

**Comment by reachdigitalaus** [comment]
+1

**Comment by nohl** [comment]
The posts above are cool, however, Google Lighthouse is flagging this and not all Elementor users are as clever as these guys. ++1

**Comment by OCpublishing** [comment]
1 and a half year and still nothing done about adding a noopener to an external link.
I understand that your workflow may be difficult sometimes but hey! 20 MONTHS and the problem is still here and no ETA.
Maybe put template kits aside for a moment and focus more on code? Please escalate this topic

**Comment by LucasKovacs** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!

**Comment by adrdsd** [comment]
I am currently using Elementor's "**Social icons**" widget and **there is still no way to add no add a rel = "opener"** (or referrer).

This is a **serious security breach**, can you please fix it?

**Comment by ynotGit** [comment]
I'm currently working on a site that uses Elementor Pro (3.2.2) and I still get this error, specifically on social icons. I've just rebuilt them and still no further forward. Any Ideas?

**Comment by davidmondok** [comment]
Same here. It seems, this issue has resurfaced. I added an Icon List widget and `noopener`is not added to links with `target="_blank"`.

**Comment by fippy** [comment]
Issues seem to still exist with latest version of Elementor (Version 3.11.2) and Elementor Pro (3.11.3) - noopener was not added to links with target="_blank".

**Comment by dpinchukov-ueni** [comment]
Still an issue with 3.20.3

**Comment by shapirus** [comment]
Still an issue with 3.20.3.
