### ISSUE TITLE
Hide columns in tablet, mobile (responsive)

### ISSUE THREAD

**Issue by pulla** [elementor/elementor#3747]
I found options for "hiding section". But I can't find responsive options in columns.

I have 4 columns in PC version. But I'd like to have only 3 columns and hide 1 column in Mobile, Tablet.
How can do that?
I have seen Column Width option. But it's limited to 10%. ( I know it will be 2 % in v2 ). But I need to hide them.

Why you don't have hiding options in columns?
Can you please give me some tips?

Thank you for your great plugin. We love it.

**Comment by bainternet** [comment]
@pulla 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, You can duplicate the section, hide it on desktop and show it only on mobile with only 3 columns, and hide the original section on mobile.
Thanks for the feedback.

**Comment by mshaaban0** [comment]
@bainternet I really think this is an essential feature. duplicating is not the solution, and it should definitely be considered for the next release.

I'll be happy to help on this, please open an issue describing what's required, and I can take it from there. Thanks.

**Comment by jus303** [comment]
Yes agreed - hiding for screens sizes is essential! Especially for footers where a lot of content is not needed for smaller screens

**Comment by Ricarditu** [comment]
Same here!

If there are responsive options for elements and sections to be able to show or hide on desktop, tablet or mobile, there should be the same options for the columns.

Thanks!

**Comment by mshaaban0** [comment]
I'd say we need to reopen this issue, and figure out the solution.. A lot of people are requesting it!

**Comment by coreaspect** [comment]
here is a nice workaround using CSS by this chap Flint Skin
 - https://www.youtube.com/watch?v=CGQnKgjbdDI

**Comment by clickharder** [comment]
This is what I use to hide columns. 

I added this code to a plugin (my guess is it would also work in the functions.php file).

```
if ( !function_exists( 'ch_hide_column_elementor_controls' ) ) {
	add_action( 'elementor/element/before_section_end' , 'ch_hide_column_elementor_controls', 10, 3 );
	function ch_hide_column_elementor_controls( $section, $section_id, $args ) {
		if( $section_id == 'section_advanced' ) :

			$section->add_control(
				'hide_desktop_column',
				[
					'label' => __( 'Hide On Desktop', 'elementor' ),
					'type' => Elementor\Controls_Manager::SWITCHER,
					'default' => '',
					'prefix_class' => 'elementor-',
					'label_on' => __( 'Hide', 'elementor' ),
					'label_off' => __( 'Show', 'elementor' ),
					'return_value' => 'hidden-desktop',
				]
			);

			$section->add_control(
				'hide_tablet_column',
				[
					'label' => __( 'Hide On Tablet', 'elementor' ),
					'type' => Elementor\Controls_Manager::SWITCHER,
					'default' => '',
					'prefix_class' => 'elementor-',
					'label_on' => __( 'Hide', 'elementor' ),
					'label_off' => __( 'Show', 'elementor' ),
					'return_value' => 'hidden-tablet',
				]
			);

			$section->add_control(
				'hide_mobile_column',
				[
					'label' => __( 'Hide On Mobile', 'elementor' ),
					'type' => Elementor\Controls_Manager::SWITCHER,
					'default' => '',
					'prefix_class' => 'elementor-',
					'label_on' => __( 'Hide', 'elementor' ),
					'label_off' => __( 'Show', 'elementor' ),
					'return_value' => 'hidden-phone',
				]
			);
		endif;
	}
}
```

**Comment by bkjproductions** [comment]
Definitely need to make this happen! I will have to try that plugin code, thanks for putting that out there!

As a workaround, I am trying something like this:
I add a class of "nomobile" to the element I don't want to see in mobile, and then write a media query to make that class hidden. I have not thoroughly tested this yet; I may have to do something to the OTHER element(s) that I DO want to show, if they are in the same row as the element I am hiding.

`@media(min-width: 768px) {
    .nomobile {display: none;}
}

@media(min-width: 1025px) {
    .nomobile {display: none;}
}`

**Comment by amindiary** [comment]
+1
yeah needed
I used hidden-sm hidden-xs bootstrap classes

**Comment by amindiary** [comment]
@bainternet  wondering why if it can happen with a small piece of code like this 
https://github.com/pojome/elementor/issues/3747#issuecomment-406270821

elementor team not simply add it (talking about elementor pro)

**Comment by drewclifton** [comment]
+1 this is an obvious need. Creating duplicate sections is not a suitable workaround when in many cases a column could be hidden instead.

Thanks!

**Comment by KB-BL** [comment]
+1

**Comment by geochatz** [comment]
+1

**Comment by raulillana** [comment]
+1

**Comment by ecodinom** [comment]
+1

**Comment by newoceans** [comment]
+1 

Great code, works like a charm @clickharder! Guess you saved my ass today ;-)

**Comment by nsoui** [comment]
+1
I am an Elementor Pro customer

**Comment by kwbtdisk** [comment]
I've also struggled about but just find out that we can use
`.elementor-hidden-phone` `.elementor-hidden-tablet` `.elementor-hidden-desktop`
from the CSS file in Elementor core source 😁

<img width="1154" alt="screenshot 2018-12-07 at 11 40 09" src="https://user-images.githubusercontent.com/2969635/49624647-996b3f80-fa15-11e8-8a30-ce4b21512285.png">

I think this is a better way because it looks using Elementor's responsive breakpoint settings.

**Comment by kwbtdisk** [comment]
@bkjproductions 😎 I've just found out that today. But with the commit history, the classes were existing at least Aug 2016: https://github.com/pojome/elementor/blob/f484daed89f0e85c0703483b4e0e850b15faf8ea/assets/dev/scss/frontend/_visibility.scss

**Comment by hufer** [comment]
https://pafe.piotnet.com/#responsive-hide-column and https://pafe.piotnet.com/#responsive-column-order Piotnet Addons For Elementor can do it

**Comment by eternalhexen** [comment]
> This is what I use to hide columns.
> 
> I added this code to a plugin (my guess is it would also work in the functions.php file).
> 
> ```
> if ( !function_exists( 'ch_hide_column_elementor_controls' ) ) {
> 	add_action( 'elementor/element/before_section_end' , 'ch_hide_column_elementor_controls', 10, 3 );
> 	function ch_hide_column_elementor_controls( $section, $section_id, $args ) {
> 		if( $section_id == 'section_advanced' ) :
> 
> 			$section->add_control(
> 				'hide_desktop_column',
> 				[
> 					'label' => __( 'Hide On Desktop', 'elementor' ),
> 					'type' => Elementor\Controls_Manager::SWITCHER,
> 					'default' => '',
> 					'prefix_class' => 'elementor-',
> 					'label_on' => __( 'Hide', 'elementor' ),
> 					'label_off' => __( 'Show', 'elementor' ),
> 					'return_value' => 'hidden-desktop',
> 				]
> 			);
> 
> 			$section->add_control(
> 				'hide_tablet_column',
> 				[
> 					'label' => __( 'Hide On Tablet', 'elementor' ),
> 					'type' => Elementor\Controls_Manager::SWITCHER,
> 					'default' => '',
> 					'prefix_class' => 'elementor-',
> 					'label_on' => __( 'Hide', 'elementor' ),
> 					'label_off' => __( 'Show', 'elementor' ),
> 					'return_value' => 'hidden-tablet',
> 				]
> 			);
> 
> 			$section->add_control(
> 				'hide_mobile_column',
> 				[
> 					'label' => __( 'Hide On Mobile', 'elementor' ),
> 					'type' => Elementor\Controls_Manager::SWITCHER,
> 					'default' => '',
> 					'prefix_class' => 'elementor-',
> 					'label_on' => __( 'Hide', 'elementor' ),
> 					'label_off' => __( 'Show', 'elementor' ),
> 					'return_value' => 'hidden-phone',
> 				]
> 			);
> 		endif;
> 	}
> }
> ```

This is an absolutely incredible solution. Great code! I added this to functions.php with no problem on the Astra theme. Tested with various elements - works like a charm.

**Comment by shilo-ey** [comment]
This feature has been added to Elementor v2.5.0. Feel free to update
