### ISSUE TITLE
✔️ 🚀 Feature Request: lazy load background images

### ISSUE THREAD

**Issue by wordmagicsoft** [elementor/elementor#3929]
I don't think this is possible right now, even adding a custom HTML attribute like data-bg and then process it via JS code.

It would be very nice to have the possibility to specify a background-image data attribute for a section or div instead of the background image itself, so we could handle a lazy loading afterwards.

Any ideas?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bentalgad** [comment]
+1 This is a real deal for page loading speed, and there isn't any way to do that right now (not a one i can think of) even if you want to do some hard coding..

**Comment by kprimdal** [comment]
Yes please

**Comment by iankh1** [comment]
I have been running page speed tests and background images are dragging down performance. I currently use WP Rocket and they can't support lazyload for background images because Elementor handles them in CSS. I have looked for another plugin and have found the same to be true. I would like to see Elementor support the ability to have images and background images lazyload.

**Comment by bentalgad** [comment]
This is really critical stuff when combined with the enormous amount of dom elements Elementor is producing even for a simple page which also effects the speed and the ranking.

**Comment by ArtakEVN** [comment]
99-100% for desktop and 25-30% for mobile. This is my results for **PageSpeed Insights**. 
The main reason of low mobile results is **Defer offscreen images** . Only way to fix this is lazy load of background images.

**Comment by IwishIcanFLighT** [comment]
We would also really appreciate the lazy load feature for background images and carousels.

**Comment by maykelesser** [comment]
Lazy load on every image inside elementor!

**Comment by wordmagicsoft** [comment]
The latest version of WP Rocket 3.3 supports background image lazy loading, according to their documentation:

WP Rocket will automatically LazyLoad background images that are found in the HTML of your page using this markup:

<div style=”background-image: url(image.jpg)”>

The <div> element can have other attributes or classes, and it will still work.

When LazyLoaded, the element will be transformed into:

<div data-bg=”url(image.jpg)” class=”rocket-lazyload” style=””>

Will this be compatible with Elementor?

**Comment by Deralict** [comment]
The background lazy loading feature of WP-Rocket 3.3.x is NOT compatible with Elementor because Elementor uses external css to specify the image source.

+1 for the ability for Elementor to support background image lazy-loading.

**Comment by raphaellandau** [comment]
why is this closed?
is there a solution for this?

**Comment by jrevillini** [comment]
check this out https://gist.github.com/jrevillini/e2fe088455e4007e43a23b3364720690

**Comment by bcavenagh** [comment]
Any update here on this? Will this be implemented in Elementor or do I need to go find my own solution?

**Comment by jrevillini** [comment]
> Any update here on this? Will this be implemented in Elementor or do I need to go find my own solution?
See my previous comment. It links to a gist solution that worked for the previous guy and myself. My code can be plugged into a code snippet using a plugin or included into functions.php on the active theme. I've only tested it using code snippets myself.

**Comment by jrevillini** [comment]
Today I'm releasing a plugin to handle this:
https://james.revillini.com/projects/lazy-load-elementor-background-images-wordpress-plugin/

**Comment by PrashGupta** [comment]
+1 for Lazy load on every image inside elementor!

**Comment by khahina** [comment]
+1 for Lazy load on background image

**Comment by cristacheda** [comment]
+1 for this feature

**Comment by hoseinit** [comment]
+1

**Comment by PascalClaro** [comment]
+1

**Comment by PrashGupta** [comment]
+1

**Comment by Zach-Toth** [comment]
+1

**Comment by lea-pw** [comment]
+1

**Comment by lea-pw** [comment]
Have a look: http://wp101.net/support/topic/not-working-with-wp-rocket-3-7-and-elementor-3-0-5/

**Comment by markbosky** [comment]
+1

**Comment by wpfixy** [comment]
+1

**Comment by Josh-PCD** [comment]
+1 please

**Comment by jordanmiguel** [comment]
+1 plsssss

**Comment by pcm0nk** [comment]
+1 larger than this? the google CWV is killing us

**Comment by euene** [comment]
+1.

Lazy loading of all images is extremely important. 

It has a much higher impact than the recent performance/speed focused Elementor experiments such as Improved Asset & CSS Loading/Optimized DOM Output.

Image lazy loading (#11085) and background image lazy loading (this issue) should be a top priority for the Elementor dev team.

This issue shouldn't be closed - it should be re-opened and be actively prioritised to be implemented.

@bainternet @shilo-ey @ramiy @DorShahar

**Comment by BrianHsiao** [comment]
+1

**Comment by johntunnel** [comment]
+1

**Comment by jeantardelli** [comment]
+1

**Comment by masoudnkh** [comment]
+999999

**Comment by masoudnkh** [comment]
Elementor is the best wordpress page builder and need this option

**Comment by stasonua0** [comment]
+1

**Comment by sk117** [comment]
+1

**Comment by Tygovanommen** [comment]
+1

**Comment by HuthDev** [comment]
+1

**Comment by mohsinworld** [comment]
Background image lazyload is so important for the header image. Currently, the image takes time to expand as full width which looks bad!

**Comment by meeuwsen** [comment]
+1!

**Comment by micarner** [comment]
This really needs to be implemented. I'm considering moving away from Elementor entirely because of basic stuff like this.

**Comment by tamal-sen** [comment]
Bump

**Comment by masoudnkh** [comment]
> Background image lazyload is so important for the header image. Currently, the image takes time to expand as full width which looks bad!

The all images in the header of site dont need lazyload because its a largest contentful. You should only optimize images in the header. Activate the lazyliad for header and some images in header section , can increase lcp and slow your site. Some of time you need only preload images in header like image logo and get best performance.

**Comment by yorkfrog** [comment]
+1 this has been around for so long and @jrevillini code seems to have stopped working on columns (ok on sections) (https://github.com/elementor/elementor/issues/3929#issuecomment-584106696).

**Comment by discotizer** [comment]
+1

**Comment by jivaneo** [comment]
> Come on please @elementor !!! WHY is this not integrated yet?
+1
Such an important feature! We're waiting...

**Comment by jivaneo** [comment]
> +1.
> 
> Lazy loading of all images is extremely important.
> 
> It has a much higher impact than the recent performance/speed focused Elementor experiments such as Improved Asset & CSS Loading/Optimized DOM Output.
> 
> Image lazy loading (#11085) and background image lazy loading (this issue) should be a top priority for the Elementor dev team.
> 
> This issue shouldn't be closed - it should be re-opened and be actively prioritised to be implemented.
> 
> @bainternet @shilo-ey @arielk @ramiy @DorShahar

Agreed! It shouldn't be closed. is this the way to handle problems? Close topic?

**Comment by BrockwayProd** [comment]
+1

**Comment by fatheaddrummer** [comment]
+1

**Comment by chasperlisimba** [comment]
@arielk comes this feature in 3.8?

**Comment by arielk** [comment]
We are currently working to resolve this issue. Unfortunately, we're not finish developing this feature yet, so for now we're postpone it to version 3.9.0.

**Comment by jivaneo** [comment]
> We are currently working to resolve this issue. Unfortunately, we're not finish developing this feature yet, so for now we're postpone it to version 3.9.0.

OK well noted. We'll ne waiting.
Thanks

**Comment by elgoots** [comment]
oh my lord. with google now confirming the use of their critical signals for speed tests this is the one thing failing on seo reports. sites that i am not using elementor on increased slightly in rankings especially for mobile devices with lazy loaded backgrounds. this is crazy this isnt implemented yet... elementor was always and in allot of the seo world is heavily criticised for being bad for seo. turn it around.

**Comment by jivaneo** [comment]
> oh my lord. with google now confirming the use of their critical signals for speed tests this is the one thing failing on seo reports. sites that i am not using elementor on increased slightly in rankings especially for mobile devices with lazy loaded backgrounds. this is crazy this isnt implemented yet... elementor was always and in allot of the seo world is heavily criticised for being bad for seo. turn it around.

Totally agree! Seems version 3.9.0 will bring this feature...
Lets see.

**Comment by elgoots** [comment]
i would not recommend this however i just activated the developer version. once installed it showed me the option to lazy load background images in experiments. can confirm it fixed the issue. once its released stable I will remove the dev version. for anyone else it isnt recommended to install the dev version in live environments but im confident it hasnt broken anything for me personally.

**Comment by jivaneo** [comment]
> i would not recommend this however i just activated the developer version. once installed it showed me the option to lazy load background images in experiments. can confirm it fixed the issue. once its released stable I will remove the dev version. for anyone else it isnt recommended to install the dev version in live environments but im confident it hasnt broken anything for me personally.

Awesome! Means it will be released for real pretty soon. Can't wait.
Thanks

**Comment by elgoots** [comment]
@arielk actually it still doesnt seem to be working for background overlay options?

**Comment by zeinzulaziz** [comment]
@BrockwayProd you can use manual code like this
```
selector {
    background: url('image-url') no-repeat;
    background-size: cover;
}
```

**Comment by beaxion** [comment]
If WPRocket JS execution delay is enabled even the first (hero) background is not loading until you move the mouse.
