### ISSUE TITLE
Feature Request: Global Widget name displayed in sidebar

### ISSUE THREAD

**Issue by Paul00777** [elementor/elementor#4006]
I've lost a global widget!
I can see it on a page, but I can't find a way it get its name, to then find it in my list of global widgets.

So a simple fix would be to display the global widget name on the left (above the Edit & Unlink buttons)

Thank you.

**Comment by Paul00777** [comment]
Yes. Exactly. Displaying the name of the widget would be helpful. It's easy
to loose track of what they are called.


A thumbnail shot of each widget in the Global area would be nice too! I end
up with different versions and can't easily see them all. Pity we can't see
thumbnails in the wordpress library...
/wp-admin/edit.php?post_type=elementor_library&elementor_library_type=widget
It would be nice to be able to go somewhere to get a real idea of what's
what when things get lost!

Thank you for the great product!


Paul Tottle
+86-185-1606-2704
________________

“We live on a razor's edge. From one instant to another, any of us can
regress to yesterday's mindset or connect with an emerging future
possibility.”  -  Otto Scharmer

**Comment by elasticeye** [comment]
Any progress on this? Please add this to the global widget.

**Comment by bainternet** [comment]
The global Widget name is visible for easy access via the Navigator.

thanks.
