### ISSUE TITLE
[Feature request] Add Flickr galleries

### ISSUE THREAD

**Issue by stefanobartoletti** [elementor/elementor#4054]
Very satisfied Elementor Pro user here. I have a suggestion for the improvement of Elementor.

I think that it could be really handy to have this page builder natively support the creation of galleries (maybe even carousels) made of pictures hosted on Flickr.

Besides providing an useful social integration, it is useful for those sites than need to have a lot of image galleries, in order to reduce the space and the resources used on the hosting service. 

I know that there are other plugins whose shortcodes/widgets could be easily used even inside Elementor, but a native solution would be really better: less code, better integration, more uniform look and feel, less chance of incompatibilities, and so on.

**Comment by ramiy** [comment]
Check out the **[Elementor Flickr](https://wpplugins.io/downloads/elementor-flickr/)** widget, or the **[Press Elements Pro](https://press-elements.com/pricing/)** widgets.

**Comment by Sekhemty** [comment]
Thank you, I'll prefer to have an element integrated with the main plugin rather than relying on an external addon, but I'll have a look.

**Comment by ErenVersu** [comment]
> 
> 
> Check out the **[Elementor Flickr](https://wpplugins.io/downloads/elementor-flickr/)** widget, or the **[Press Elements Pro](https://press-elements.com/pricing/)** widgets.

Hello @ramiy i saw that you are the developer or [Elementor Flickr](https://wpplugins.io/downloads/elementor-flickr/), i am interested in the plugin but have 2 questions. 

1.- Can i put the album ID and show only the images of a certain album or gallery?
2.- Why the plugin have the last update 2 years ago? why you dont have any recent update?

Today i use this plugin "Flickr Justified Gallery", but some update make it not working well.
