### ISSUE TITLE
Revolution Slider widget not working

### ISSUE THREAD

**Issue by notrealdev** [elementor/elementor#4131]
Hi, `Revolution Slider` widget not working for me, i get an error here

![Imgur](https://i.imgur.com/sDrXMwX.png)

![Imgur](https://i.imgur.com/CxuwwP0.png)

// I  get the same error when using `Shortcode` widget
`[rev_slider alias="slider1"]`

Elementor: 2.0.6
Rev Slider: 5.4.7.2
WP: 4.9.5

**Comment by randomfreeform** [comment]
for me I just have a blank area until I click it  rather than the gray area I see in screenshot above.. Hope this gets fixed.

**Comment by duongancol** [comment]
I got the same problem here. Hope it's fixed soon!

**Comment by randomfreeform** [comment]
Sure wish Revolution Slider's developer Theme Punch AND Elementor would talk and find a more elegant solution.. where we can actually SEE the Rev Slider in the El editor. THX.

**Comment by Tristan29photography** [comment]
Well I have the same issue on my site. Strangely, I have another site with exactly the same configuration and plugins,  and it works fine, I can see the preview in the frontend editor...
