### ISSUE TITLE
Do not show Elementor menu item 

### ISSUE THREAD

**Issue by mariobarretta** [elementor/elementor#4206]
Elemetor's role integration has been a very good action for this great pèage builder but i've seen that user excluded continue to see, in the WP dashboard, the menu item of Elementor and they can also show all my work ( template adn widget creaed and saved ) and they are abl to can also export.
I think that this is not a good thing because permti to users to see and export my work can be a problem.
For this reason i hope that Elementtor can fix or upgrade this situation with a new version also because if i choose to exclude a role why it can continue to see elementor?
I think that an use experience look like difference  between author and editor can be the best action ( one of the see post and pages and other see only post ) 
I think that could be great to reach this situation  

**Added info :**

@bainternet 

I've also tried to deactivate all rules in role management of elementor and the situation is exactly the same.
It appear that all input on that section do not work and do not generate any effect,

**Comment by bainternet** [comment]
you mean in the admin or the editor?

**Comment by mariobarretta** [comment]
In the admin.

in the editor is correctly not shown  but in the admin , the users excluded continue to show the menu item and they can see my template and widget work ( also to export )
i thought that excludin role they do not show nothing realted to elementor exactly look like the author and editor example.

**Comment by imagesgroup** [comment]
I believe this is similar to my feature request.

If I restrict a user role via Elementor's **Role Manager** they can still access the **Templates** Admin Menu. This is less than ideal as it means that while we can limit **Editors** from using the more complicated Editor they can still access the **Templates** menu. This means they can access the **Theme Builder** items and delete them (my first test user did exactly this by rapid double-clicking).

For example: I have a site built using CPT & ACF and use Elementor's Theme builder to display these custom posts. The end user only needs to edit the basic posts without even touching Elementors editor. I can restrict them from using the Editor but they can still damage the site by deleting items from the Theme builder.

Ideal outcome would be to allow us to limit access to the Templates Menu by Role.

**Comment by shilo-ey** [comment]
@imagesgroup thanks for your feedback - 
I merged this issue with  #8092, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

@mariobarretta This issue has been resolved in v2.4.0.

Thanks for your feedback!
