### ISSUE TITLE
[Feature Request] Masonry and justified image gallery options plus filter ability

### ISSUE THREAD

**Issue by klarakalko** [elementor/elementor#4279]
Would be helpful and useful to have these options in Elementor Pro (implementation of masonry.js or isotope.js, maybe?) instead of installing additional plugins.

Thank you.

**Comment by BossOz** [comment]
# I'm looking for that too!

**Comment by camelot317** [comment]
I need this one too.please add masonry, there are many photographers around looking to create custom websites...thank you

**Comment by Turanligil** [comment]
+1

**Comment by hufer** [comment]
https://pafe.piotnet.com/#lightbox-image PAFE Lightbox Gallery Masonry in Piotnet Addons For Elementor can make Masonry, lightbox with title and caption, zoom, pan, socials share, fullscreen

**Comment by tilnox** [comment]
Yes please!!!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by sermalefico** [comment]
Justified Gallery with ACF dont works in tablet mode. The row size selector dont do anything and cause gallery disapear in the tablet mode

**Comment by sermalefico** [comment]
Ola? Justified Gallery with ACF dont works in tablet mode. The row size selector dont do anything and cause gallery disapear in the tablet mode
