### ISSUE TITLE
✔️ 🚀 Feature Request: Fallback background color for section background video

### ISSUE THREAD

**Issue by mharding7va** [elementor/elementor#4353]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Please add a fallback color selector for the section background video.  The only currently available option is a fallback image. On a slow device this image shows before video has time to load.  A color or gradient color background would be more appropriate, especially on mobile.

**Comment by mindingear** [comment]
+1 if the section uses a photo gallery, it would be useful to have a fallback color...

**Comment by nicholaszein** [comment]
Hello there @mharding7va, @silvioghedin, and @mindingear!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
