### ISSUE TITLE
✅ 🚀 Feature Request: Feature Request: WooCommerce Product Carousel

### ISSUE THREAD

**Issue by krupte** [elementor/elementor#4490]
Current version support the ability to add an image carousel but it would be great to have the ability to create a carousel from a collection/set of WooCommerce products. Such carousels can be useful to display products you want to promote or on sale and having the ability to add to a carousel without another plugin would be great.

**Comment by adi0071** [comment]
I also think this would be a great asset to woocommerce products and more importantly its usage on the product details pages ....for example up sell, cross sell

**Comment by dinhtungdu** [comment]
+1 on this feature

**Comment by black-eye** [comment]
+1

**Comment by fxaviers** [comment]
Is there an estimated time to release this function?

**Comment by giltiago** [comment]
Also it would be amazing to have the ability to create a carousel using products tags...

**Comment by artheadsgames** [comment]
Yes, really needed!

**Comment by leannerenee** [comment]
+1 would love this for display of products on mobile devices.

**Comment by 79ho3ein** [comment]
+1
The jet woobuilder plugin is the best template for developing this feature.
