### ISSUE TITLE
Feature request: "% read bar"

### ISSUE THREAD

**Issue by JohnMulderFrance** [elementor/elementor#4494]
AirBnB uses a % read bar which looks very useful to me

![screenshot 2018-05-21 at 15 45 37](https://user-images.githubusercontent.com/37953844/40310808-4c02366c-5d0e-11e8-8d09-6724b633f4bf.png)
![screenshot 2018-05-21 at 15 45 28](https://user-images.githubusercontent.com/37953844/40310809-4c253bb2-5d0e-11e8-9e98-424a3bd2f333.png)

**Comment by rami-elementor** [comment]
**Progress Tracker** already implemented in Elementor Pro 3.5.

https://elementor.com/blog/announcing-scroll-snap-and-progress-tracker/
