### ISSUE TITLE
Inactive nav points color for Testimonials slider widget

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#4496]
Hello!
There is a color changeing opportunity for navigation points in Testimonials slider widget. However we can only change active color but not inactive. When I make a dark background, I don't see inactive items.
I do this to solve the issue:
`selector .swiper-pagination-bullet {
    background-color: #ffffff;
    opacity: 0.7;
}

selector .swiper-pagination-bullet-active {
    opacity: 1;
}`

Add inactive color for navigation please!

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
