### ISSUE TITLE
Dynamic content to the Animated Headline

### ISSUE THREAD

**Issue by bentalgad** [elementor/elementor#4625]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**For Header and Lot more...**
It is really essential if using the animated title future in the header, for example, to be able to pull the three content parts from a custom field that will be made for every post/page.

I think if you would have this dynamic content option it would be great for that!

**Comment by samunderwood** [comment]
Just want to +1 this, the animated headline would be a lot more useful if the 'Highlighted Text' field was made to be dynamic also. Currently, it's not really useful as part of a template for a header.

**Comment by samunderwood** [comment]
@bainternet does the milestone need updating for this? Really want this featured adding!

**Comment by wario9k** [comment]
Another +1 Dynamic Animated Headline its some helpful. Anyone have a workaround or solution? :)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
