### ISSUE TITLE
Default Page Layout in Global Settings

### ISSUE THREAD

**Issue by seanvandermolen** [elementor/elementor#4925]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Setting a page layout default to avoid setting it on a per page basis

**Describe the solution you'd like**
A Page layout under global settings or in the Elementor options page to set global page layouts

**Describe alternatives you've considered**
Taking this setting from the theme if its supported

**Additional context**
I'm using Ocean WP and there is a layout style in the customizer.  Wide, Boxed and Separate.  But this does not have an effect on Elementor.  Main Container Width works though.

default and boxed are the same thing and setting content width does nothing.  Stretch with js works of course.  But it seems cleaner to set the page layout to full and have the themes max container width determine the box vs full-width settings.  which works great.

**Comment by mbaierl** [comment]
Same here - Elementor often has "Defaults" which cannot be changed anyhwere in the Elementor settings. This is one of it... column gaps is another one that drives me nuts.

**Comment by jazir5** [comment]
Please add this, this has been an issue for me since the inception of my usage of Elementor. Fixing this would be greatly appreciated.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!

**Comment by TukuToi** [comment]
This issue not entirely resolved in Elementor 3.0 not even using Elementor Hello Theme.

Using Elementor 3.0.7 here, and the Default Template as set in the global settings of Elementor Templates, does *not* apply to either new posts, nor on new pages, as defaulting to "Default Template".

Only old pages/posts will reflect the global setting, but only as long you never update them again.
