### ISSUE TITLE
Use color variables of color picker in custom CSS.

### ISSUE THREAD

**Issue by dinhtungdu** [elementor/elementor#4971]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For complicated element, to match our design, we still need Custom CSS for those items. But when we need to change or modify color, we need to search/replace or manual correction of colors in custom css.

**Describe the solution you'd like**
By somehow we can use Color pickers colors in custom css. Just like we did with `selector`.

**Comment by maxwellhibbert** [comment]
+100
But I'd like the variables available in the colour picker as well as code.

**Comment by black-eye** [comment]
+1

**Comment by ArekZw** [comment]
+1

**Comment by tristanleboss** [comment]
+1

**Comment by cirkut** [comment]
+1 If this was implemented, Elementor would be able to be MUCH more accessible. In my case, I need to implement a color switcher for higher contrast, and it's just not possible without using Javascript to find and replace every hex code on a page. If CSS variables were supported in the color picker, I could just change the variables and maintain accessibility, all while continuing to use the color picker and not needing to worry about the wrong color potentially being selected or used and not being able to have it swapped out for users with higher contrast needs.

**Comment by tristanleboss** [comment]
> arielk added this to the 2.2.0 milestone on Jul 11, 2018
> arielk modified the milestones: 2.2.0, 2.3.0 on Jul 16, 2018
> arielk modified the milestones: 2.3.0, 2.4.0 on Oct 28, 2018
> arielk modified the milestones: 2.4.0, 2.5.0 on Dec 12, 2018
> arielk modified the milestones: 2.5.0, 2.6.0 on Feb 11
> arielk modified the milestones: 2.6.0, 2.7.0 on Jun 11
> arielk removed this from the 2.7.0 milestone on Aug 21

**Comment by JamesJosephFinn** [comment]
+💯!

**Comment by MichaelDarko** [comment]
#11123

**Comment by arielk** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!
