### ISSUE TITLE
🔗 🚀 Feature Request: Sidebar Menu for Mobile (Duplicate of #3275)

### ISSUE THREAD

**Issue by myatminlu** [elementor/elementor#4978]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
### ### 
Could you please add this kind of feature on Elementor Pro for nav? Because this is very useful for me and I hope other people will love that.
![img_20180706_085956](https://user-images.githubusercontent.com/8571048/42384989-94e39548-8161-11e8-9b38-f61286619154.jpg)

**Comment by bainternet** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
