### ISSUE TITLE
Use the "flex justify-content: space-around;" for widgets

### ISSUE THREAD

**Issue by spirau** [elementor/elementor#5083]
Using columns, it is possible to have the last widget aligned to the bottom of the row in each column.
![image](https://user-images.githubusercontent.com/11776643/42759132-2d9873a2-8906-11e8-8d90-92bdd8f18fee.png)
The first image is done using a css class on the columns width "display: flex; flex-direction: column; justify-content: space-between; }", so the buttons which are the last items are aligned.
But if I develop a widget or use the price table for example and each widget has a different height, the last component of each widget will not be aligned and the height of each column is different. Because the widgets are embedded in wrappers it is not possible to use this flex possibility.
![image](https://user-images.githubusercontent.com/11776643/42759191-600a577e-8906-11e8-914d-8b402da24b68.png)
The look & feel is not the same with or without the buttons aligned.
How to get this effect inside a custom widget since the widget wrapper is seen as one unique flex component?

**Comment by black-eye** [comment]
+1

**Comment by jazir5** [comment]
Seconded, this formatting issue is major for whether a site looks like it was done professionally or not. Mismatching margins for identical elements is a major issue when i'm going over clients issues with their prior sites.

**Comment by shilo-ey** [comment]
This feature has been added in Elementor v2.5.0

Feel free to update!

**Comment by muchadesign** [comment]
How do I use this feature to make CTA widgets the same height when in a row?

![Elementor_CTA_heights-uneven](https://user-images.githubusercontent.com/2933088/56680110-314b8c00-668c-11e9-9c66-d27d4e25911a.jpg)
