### ISSUE TITLE
Disable loop for video backgrounds

### ISSUE THREAD

**Issue by besweeet** [elementor/elementor#5129]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will solve the problem of background videos looping...

**Describe the solution you'd like**
Simply add a toggle where you can disable the loop. A video widget has this option, and video backgrounds should, too. All it takes is to remove the loop parameter from the video tag.

**Describe alternatives you've considered**
Using a full-width video widget as opposed to a traditional video background works, but destroys my header and content below the widget by placing the video over or behind those elements...

**Comment by arielk** [comment]
What happens after the video is over, what background will be displayed on the page?

**Comment by besweeet** [comment]
@arielk It simply starts over.

**Comment by bainternet** [comment]
@besweeet 

It starts over because of the loop, what happens if there is no loop???

**Comment by besweeet** [comment]
@bainternet Then the video stops at the last frame, which is what I want. But, that's where the problem is: the loop can't be turned off in Elementor...

**Comment by squasha4416** [comment]
I too would like to +1 this request. Having a background video loop (for example, in the homepage header) is distracting. And it seems like making loop an option is an easy and useful addition.

**Comment by MPHood** [comment]
+1000

**Comment by grandmastertux** [comment]
+1, agree with everyone else to have an option set for this.

**Comment by davidhaywardbevie** [comment]
Yes please

**Comment by solomojo** [comment]
+1, please add this.

**Comment by steve-w** [comment]
+1, want ability to toggle looping

**Comment by kdub718** [comment]
+1

**Comment by drewclifton** [comment]
Reached for this intuitively and it... wasn't there. Agreed! For my video the last frame is where I want to camp on. Another thought is to show image after video?

**Comment by costa863** [comment]
hi
any development on this subject?

**Comment by KarenHind** [comment]
I also need this feature too!  How are people solving this?  Is there code that can be added to the CSS?  Although, I think I would need pro for that.  I too want it to play once through and then stop on the last frame of the video.

**Comment by fvenuto** [comment]
+1
Maybe after the loop you should show the image background. The same loaded if the video isn't starting.

**Comment by savemakeprotect** [comment]
I have the issue where after a random number of loops it will stop and then display other videos from my youtube channel.... Happens in MS Edge and on some mobile apps. 
![Edge - Elementor Video Background](https://user-images.githubusercontent.com/51980260/59733789-6f32ee00-9292-11e9-87c0-dcee04909a89.png)

**Comment by savemakeprotect** [comment]
> I have the issue where after a random number of loops it will stop and then display other videos from my youtube channel.... Happens in MS Edge and on some mobile apps.

After posting this I tried the old ?rel=0 and it has fixed this problem. Still frustrating XD

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!

**Comment by khamisr** [comment]
If you are self hosting the video, set the end time before the actual end time of the video and it will pause in the last frame. For example a 5 second video clip set to 4 seconds

**Comment by khamisr** [comment]
and set Yes for Play Once
