### ISSUE TITLE
🔗 🚀 Feature Request: Style or Replace wp-login.php / wp-admin login with Elementor Pro's Login Form Widget & Template (Duplicate of #5355)

### ISSUE THREAD

**Issue by smile00000** [elementor/elementor#5130]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Style or Replace wp-login.php / wp-admin login with Elementor Pro's Login Form Widget & Template

**Describe the solution you'd like**
A way to use my Elementor Pro Login Form Widget Template Design to style the Wp-Login / wp-admin login

**Describe alternatives you've considered**
N/A

**Additional context**
It's great that I have a login page, but I also want it applied when i go to my site and login via /wp-admin/

**Comment by bainternet** [comment]
I merged this issue with  #5355, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
