### ISSUE TITLE
Elementor Toggle Widget doesn't keep curved edge when adding background color

### ISSUE THREAD

**Issue by smile00000** [elementor/elementor#5156]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor Toggle Widget doesn't keep curved edge when adding background color. 

(Elementor Form Widget does this fine, please use that a guide to fix Elementor Toggle Widget and any other widget that has backgrounds so they are all the consistent)

Steps To Replicate:
Add a section
Add Toggle Widget
Go to Advanced > Border
Width: 1
Border Radius: 16
Color: Choose Whatever color

Go to Style > Title > Choose background color (can be any color). 
Once the background is there it completely wipes out the curve of the border

See our site here for details:
https://bit.ly/2O7pHgd

**Describe the solution you'd like**
Make the elementor toggle widget be able to keep a curve even when theres a background color, like the elementor form widget does.

Please see video for steps and what happens
https://www.useloom.com/share/912ef68e35a34807982a7fa5316dfb67

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lior-sh** [comment]
Hi @smile00000,

Fixed will be released in the next 2.9.0 version.

Thanks!
