### ISSUE TITLE
3 suggestions: Improvements in counters and buttons

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#5180]
Hello guys,

I want to leave here 3 suggestions of features that Elementor could offer for those who create landing page sales with product offers, course registration and ect, for a limited time:

### **First suggestion:**
The Elementor has an counter where I define how much it starts and how far it goes (eg, it starts at 100 and goes up to 1,267). This counter could be more flexible with more settings. When I set the counter to count, for example, from 100 to 1,267 the user will always see the same count. Then you could have the possibility to configure automatic increase of the count. For example, if I want to put a counter of this to show the user the number of vacancies already filled, then I set to starts in "482 filled vacancies" and every hour increases 7 vacancies. So the user when he accesses the page today, he will see a number of filled vacancies and when he accesses the page tomorrow, he will see a greater number of filled vacancies.

This increasing number could be infinite or could also have an end date where it would re-count, ie if for example I have a course where I open subscriptions every Monday and go until Wednesday, so I could set up for on Monday the counter starts at 482 and increases 7 per hour, and when it arrives next Monday at 00:00 the counter returns to the default value of 482 and starts counting again.

### **2nd suggestion:**
In addition to the increasing count I mentioned above, I might also be able to set up this counter, but the other way around. For example, if I open enrollments for a course every Monday and go until Wednesday, then I might want to put on the page the number of vacancies remaining, so for this I set a default number such as "500 remaining vacancies ", and I also set a start and end date and time such as Monday at 08:00 a.m. until Wednesday at 11:59 p.m., and with this Elementor will do the calculation and divide the 500 for 3 days or for 72 hours or 4.320 minutes and thus subtracting this number according to the time (eg, 500/72 hours = 7, then every hour is subtracted 7 until it reaches 0). And when the counter reaches 0 (zero), it could show a message in place of the counter, something like "Unfortunately all the vacancies have already been filled, but you can sign up to be warned of the next open of registrations by accessing here (link to a another page). "

In another contact I gave the suggestion to you guys to create the possibility to configure the Regressive Counter (countdown) so that when it reaches 00:00:00 it was redirected to another page.
If I do not want to redirect to another page, but instead show a message on the same page saying something like "Subscriptions Closed", then in that case I could make a Regressive Counter scheme work together with the numerical counter I mentioned above and also with a button (which would be the signup button), all within the same block. And as soon as the two counters reach 0 (zero), they disappear (along with the button) and in the place a message appears (ex .: "Subscriptions Closed! ...").

### **3rd suggestion:**
I have a page with a button where that button has a link to another page. This page with the button, I send to my mailing list on Thursday and Friday. And on Saturday I also send this page to my mailing list, but I change the link in the button to another page.
So I have to manually change the link every Saturday in the first few hours.
However, if it had a way the first link in the button was automatically changed to the second link, it would be great. So I leave my suggestion to you guys to have Elementor do this automatically. I create a button and I can set two links, where the first link is default, and the second link I set to appear on a specific date and time until another specific end date and time. After the end date and time, it automatically returns to the first link. And if I do not want a specific date, then I could set a specific day of the week (every Monday, every Tuesday, ...):

Link 1 - default
Link 2 - is changed every Saturday at 00:00 and goes until Sunday at 23:59 a.m.
Link 1 - after 23:59 p.m., link 2 is automatically changed to link 1
and when it arrives next Saturday, link 1 is changed to link 2 again at 00:00 until Sunday at 23:59. And so on.

And it could also set up more than two links if I wish.

I leave these 3 suggestions to you.

Thank you for your attention and sorry my english.
Rodrigo

**Comment by Aviad-Herman** [comment]
Hi @rodrigocarlos,
Thank you so much for your input.

I have a personal project to address old GitHub issues.
I found your post and wrote down your ideas.

Thank you so much for these suggestions.
Keep the good ideas coming!

Thanks
