### ISSUE TITLE
🔗 🚀 Feature Request: New feature for Nav Menu (Duplicate of #3275)

### ISSUE THREAD

**Issue by wordmagicsoft** [elementor/elementor#5199]
I wanted to do a menu using the Nav Menu widget that breaks at certain point (on Desktop) and then displays a Hamburger icon for the rest of the items. Hope this is possible for a future update. Right now I could implement it using 2 different Nav widgets.

Like this example:

<img width="1426" alt="screen shot 2018-07-24 at 4 56 49 pm" src="https://user-images.githubusercontent.com/4284398/43170815-488df4f2-8f64-11e8-8d3e-e5d620e6f9b4.png">

and with the hamburger menu open:

<img width="1375" alt="screen shot 2018-07-24 at 4 56 55 pm" src="https://user-images.githubusercontent.com/4284398/43170822-50f1aa76-8f64-11e8-84d5-48f479d47735.png">

**Comment by bainternet** [comment]
I merged this issue with  #3275 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by wordmagicsoft** [comment]
Thanks!

Enviado desde mi iPhone

El jul. 25, 2018, a la(s) 1:15 a. m., Raz Ohad <notifications@github.com<mailto:notifications@github.com>> escribió:


I merged this issue with #3275<https://github.com/pojome/elementor/issues/3275> , which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Aroundme12** [comment]
Is a flyout menu for mobile in the works? Creating menus are cool but not many options for mobile menus.

**Comment by nicholaszein** [comment]
Hello there,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

A workaround is to use custom CSS to hide menu items depending on the breakpoint, and then to create another Menu widget that does the opposite.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
