### ISSUE TITLE
⛔ 🚀 Feature Request: Add support for CSS variables in the Color Picker

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#5227]
To simplify working with colors in Elementor, I've added some CSS variables to my main CSS file.

In WordPress admin-menu go to `customize > custom CSS` and add:

```
:root {
    --p: red;
    --s: green;
    --a: blue;
}
```
* p is primary color.
* s is secondary color.
* a is action color.

I then went to edit an Elementor element (say a button element), and add a background color like with:

`var(--p)`

I did see the color changing in the Elementor preview but clicking "publish" saved the page unchanged and the previous color (or lack of color appeared instead my new color),

**BUT**,

When I changed the color as with `var(--p)` and then clicked the color box near the color field (image attached), and then changed the color again, and then clicked the color box near the color field again (same image relevant), then the color was indeed saved after clicking "publish".

![sss](https://user-images.githubusercontent.com/31392185/45881476-f579dc80-bdb3-11e8-8988-bf30503fd1d9.PNG)

**Comment by bendqh** [comment]
It seems you already support CSS variables but there's an Elementor JS bug:

If your color is `var(--p)` and you hit save, it won't be saved.

If your color is `var(--p)` and you hit the near color icon and then save, it will indeed be saved:

![a](https://user-images.githubusercontent.com/31392185/43311397-fdbd400a-9192-11e8-9616-280a6a985f15.PNG)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bendqh** [comment]
@bainternet  I protest the closing of this ticket. CSS variables make any process of working with Elementor much easier and faster by controlling your palette for one place; it is actually already supported due to the nature of the WordPress API but there is only this JS bug causing the need to paste the content twice.

**Comment by fxaviers** [comment]
I agree. The process of color changes would be millions of times faster, if we had variables. 
+1

**Comment by bendqh** [comment]
Original message updated. @bainternet please review it + likes and comment.

**Comment by ArekZw** [comment]
+1

**Comment by imiweb** [comment]
+1 would be excellent to have this feature.

**Comment by Tvhawk** [comment]
+1 - I've been dying to use css variables and with all but the over 6 years old IE supporting them I think we should be able to start using them.

**Comment by tomerOko** [comment]
+1  as an ElementorPro user I think it is necessary

**Comment by itay1313** [comment]
+1

**Comment by cirkut** [comment]
+1 - I think this would be a great as an Elementor Pro feature. Pro users are far more into the overall experience of creating a top to bottom solution with page templates, so not being able to have colors that are modifiable on a global level is a massive disappointment currently.

**Comment by haiphandesign** [comment]
+1 please consider adding this

**Comment by JamesJosephFinn** [comment]
+💯! At a minimum, variables should be accessible anywhere there is a color-picker.

**Comment by Morgunov-Vitaly** [comment]
+1 please consider adding this

**Comment by lmwp** [comment]
+1 please consider it's a really important functionality for really named this work as develaoppment

**Comment by prantu** [comment]
+1 Please consider adding this, we can easily create light/dark mode in Elementor with this.

**Comment by robbyemmert** [comment]
I need to override variables. Can't do it with Elementor currently. As a pro user, I also agree this is a necessary feature. Please at least consider supporting them in the custom CSS area.

**Comment by CoSciBlog** [comment]
+1

**Comment by pattonwebz** [comment]
:+1: for this feature. I think this issue should be reopened.

**Comment by Micu22** [comment]
+1

**Comment by colinmacleod** [comment]
+1 - really think this feature would make a big difference

**Comment by saschakoeth** [comment]
Even now with variables used in global style settings, there is no support for those variables in the custom CSS fields of the elementor editor??!

**Comment by dplgngr** [comment]
Update?

**Comment by kanalje** [comment]
+1 I concur

**Comment by eldervl** [comment]
+1

**Comment by londonpete1958** [comment]
I can't believe that Elementor does not support one of the most fundamental and helpful functions of CSS. This has been outstanding for so long yet they tinker with hosting!

**Comment by galasio** [comment]
+1

**Comment by GabyLipari** [comment]
+1 
This is basic

**Comment by globalwebforce** [comment]
+1

**Comment by Clemixo** [comment]
+1

**Comment by mateitudor** [comment]
Pls.

**Comment by beelzick** [comment]
+1

**Comment by nadworks** [comment]
+ 1 - an absolute must-have!

**Comment by neobiz** [comment]
+1 we really need this functionnality !

**Comment by frysteen** [comment]
+1 ... variables everywhere except for colour values is quite silly.

**Comment by ItsZubek** [comment]
+1, this would make working with Elementor and custom code a lot easier.
