### ISSUE TITLE
Hide pages and block library for clients

### ISSUE THREAD

**Issue by studi778** [elementor/elementor#5251]
Beaver Builder allows web developers to hide templates from clients and this feature should also be present in elementor so that web developers have the option to hide these from clients. Please can you make it possible to hide the pages and block library for clients asap - this can be by roles i.e editor.

Thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by mayankguptadotcom** [comment]
Would love this feature.
