### ISSUE TITLE
Improve lightbox mobile responsiveness

### ISSUE THREAD

**Issue by ShadowXVII** [elementor/elementor#5260]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The lightbox on mobile is "100% responsive" but is a less usable on mobile due to container padding and margins.

**Describe the solution you'd like**
The margins and padding on the lightbox should be reduced on mobile to improve visibility in a portain view. e.g viewing a screenshot on a mobile vs. desktop.

e.g. http://brutaldesign.github.io/swipebox/ removes nearly all margins and moves the indicators to the footer (It'd be nice to keep the prev/next showing always as it's not immediately clear there's more images).

An balanced solution between what Elementor Lightbox currently does and the larger viewport Swipebox provides would help improve usability. 

**Describe alternatives you've considered**
CSS workarounds to reduce the padding and to try workaround the contrast of the prev/next arrows. Still not great, but better. Not sure what most other lightbox solutions do.

### Before
![image](https://user-images.githubusercontent.com/446329/43441928-be19086c-94df-11e8-981a-2825c06dcfee.png)

### After
![image](https://user-images.githubusercontent.com/446329/43441896-a4fafc1e-94df-11e8-87de-bb28b98e8c57.png)

**Comment by mstudioIL** [comment]
I looking for something like this, can you share what you did?

**Comment by ShadowXVII** [comment]
Sorry, I don't have the CSS anymore. I ended up ditching the Elementor Lightbox and using another one instead. Once Elementor lightbox improves, might move back.

**Comment by mstudioIL** [comment]
Thanks, I found something for it

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!
