### ISSUE TITLE
Schedule parts of a page.

### ISSUE THREAD

**Issue by keithbernard** [elementor/elementor#5261]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Time-sensitive content does not have to be added in real time but can be planned for ahead of a particular date/time. Wordpress allows you to schedule content already but only on a page by page basis. eg for events, tickets may not be available till a certain date and time.

**Describe the solution you'd like**
To be able to schedule when a change to a row or column is displayed on a page. Ideally also to be able to schedule a complete template (section.footer./header).

**Describe alternatives you've considered**
Tried a plugin that is no longer being supported (Granular Controls For Elementor) and does not work in latest version of Elementor anyway.

**Additional context**
None

**Comment by cfoellmann** [comment]
@pojome please tag as feature request.
I would be ok with a scheduling option as a revision of the post/page/cpt. But this would be a big thing.

As a workaround I tried this plugin https://de.wordpress.org/plugins/tao-schedule-update/ but it does not copy some parts of the pages over and the elementor design is broken. So I have to fix this stuff up and dont have an easy workflow.

**Comment by nickdgreen** [comment]
I also liked this feature that was one of the modules in Granular Controls that is now not supported. It is ideal for Restaurants and Pubs where events like Mothers' Day, Fathers' Day etc. can be created in advance and then appear on the "events page" at the defined time and just as importantly be removed when the event has passed; so the site does not look as though it is not maintained correctly. There are plugins available but having an option to switch on "schedule content" and set on and of date and time within Elementor would be much cleaner.

**Comment by cfoellmann** [comment]
@nickdgreen which plugin do you use? I tried tao schedule update and it seemed to work but in the end the schedule was met but the content change was broken.
So my case fell through. The customer was not very happy. It was not critical but I would have liked it to work

**Comment by nickdgreen** [comment]
@cfoellmann I haven't found one. I wish someone who is a plugin guru would take the Granular Controls code and just release this bit of it as a separate plugin.

**Comment by elasticeye** [comment]
+1 for scheduling of content/images!

**Comment by dougdavis22** [comment]
The Elements Plus! plugin in the WP repo has scheduling functionality:

https://wordpress.org/plugins/elements-plus/

**Comment by Memaddog** [comment]
+1 for scheduling of content/images!

**Comment by srack835** [comment]
+1 for scheduling parts or entire pages. Right now, you can only schedule a page if it isn't already published. The plugins I've seen that allow you to schedule a revision to a page only work with Classic or Gutenberg editors, not Elementor pages.

**Comment by shilo-ey** [comment]
I merged this issue with #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by phillipwilhelm** [comment]
Is this a confirmed functionality? If so any advice on how to implement?

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
