### ISSUE TITLE
.load .unload section

### ISSUE THREAD

**Issue by ianstudio** [elementor/elementor#5262]
Hi,
It would be very useful if we could swap content either through some scroll action or the usual click.. by this I mean .unload then .load an Elementor My Library Section on a page.. something along the lines of this:
https://css-tricks.com/ajax-load-container-contents

You could construct all sorts of cool things with this, portfolio entries called from a grid (bypassing the usual post approach with previous, next buttons). And of course loading with CSS effects. Even target multiple sections using a single click. You could quickly transform parts of a page.

Hope someone finds that interesting and implements it :0)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
