### ISSUE TITLE
🔗 🚀 Feature Request: Enable functionality with ipads and tablets (Duplicate of #482)

### ISSUE THREAD

**Issue by rammyleeds** [elementor/elementor#5264]
Dear Sir or Madam, 
Most of the time, I edit and create websites on my PC. However, I want to  move away from my office and start editing in the garden or somewhere other than my office.  So I purchased a large 12" Ipad Pro.     

WordPress works fine.   And actually, nearly all Elementor features and widgets are available too!    Yes - I can even click "Edit with Elementor" and it works.   But there's one massive problem.  You cannot scroll down the webpage for some reason once in editing mode.  I can only see the top slice of it and it won't scroll down any further.   This then means you cannot scroll to the part of the webpage you want to edit and therefore, you can't use any of Elementor's functionality.

I have been reading on other web forum that Elementor does not work with ipads (even though WordPress does).    A number  of people have had this problem and are requesting it.   And as most of it is available, wouldn't this be an easy fix?

 I think that is a terrible shame as 
a) a lot of people are moving towards mobile editing of their websites (including tablets and ipads)
b) it's a shame that most of the funtionality of Elementor actually works with an ipad and it is only the scrolling down bit that doesnt - so surely a fix to this wouldn't take too long to do.
c) Elementor does need to stay with the developing technological times.

 I know people say that Elementor wasn't designed to work with tablets - only PCs.  But in this technologically advancing day of age, that's a silly reason, because a lot of things weren't initially developed for tablet working and yet now so many things are.   Surely, Elementor needs to move in this direction.

Thank you for all the hard work you do.

**Comment by rammyleeds** [comment]
PS For those who say "Elementor is not designed for tablets or ipads", I am not arguing that point with you.  I am asking the simple question WHY.  WHY is not designed for tablets or ipads when a lot of us are moving in that direction.  Did you ever think you would pay for your petrol bill with your phone?   Did you ever think of watching TV programmes on the thing you make a phone call with?    Did you ever envisage reading email on your phone?     You get what I mean.....

**Comment by arielk** [comment]
I merged this issue with another issue ##482 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
