### ISSUE TITLE
Constant Contact Integration

### ISSUE THREAD

**Issue by Maynestreet** [elementor/elementor#5268]
I am an Elementor shop and also a solution provider for Constant Contact.  I would like to see an integration for Constant Contact like you have with ActiveCampaign.  Constant Contact in on the path to do more marketing automation and have a huge client base.  Also, their on-site form solutions are very poor.

I would be happy to play a role in assisting this strategic partnership to happen.

Sincerely,

David Mayne
PIMedia
702-561-2303
david@pimedia.me

**Comment by artconic** [comment]
Yes. I am a Pro member. These plugins are essential.

**Comment by collizo4sky** [comment]
You could use MailOptin to connect Elementor form to Constant Contact  https://mailoptin.io/article/elementor-form-integration/

**Comment by mattiebrownoz** [comment]
@collizo4sky 
I will look into your suggestion, but at first glance it looks more intensive than how easy this same object was to achieve with mailchimp. Elementor should reach out and let Constant Contact know at least 3 people have requested this feature :-P No, but seriously, we are all so busy, when I have to look for a workaround it just feels like the company like CC is not keeping up and that looks bad.

**Comment by mattiebrownoz** [comment]
I actually have this and works with elementor so I may give it a go. I'm using the Astra theme. This was around before elementor came out with popups. 

![Screen Shot 2019-09-01 at 3 02 27 am](https://user-images.githubusercontent.com/45414921/64067050-ffaf8680-cc64-11e9-9a23-b9779b0c3f53.png)
![Screen Shot 2019-09-01 at 3 00 59 am](https://user-images.githubusercontent.com/45414921/64067051-0211e080-cc65-11e9-88e6-c09c3006a1fd.png)

**Comment by oscarhenao** [comment]
+1. Integration to Constant Contact in very important to many!

**Comment by rami-elementor** [comment]
Hi @Maynestreet ,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being.

Please feel free to contact us again with other feature suggestions.

Regards,
