### ISSUE TITLE
Show a list of all customized CSS to fast access to the element itself

### ISSUE THREAD

**Issue by choquo** [elementor/elementor#5269]
**Situation:**
I am working with a small team of designers and they used some custom CSS inside many pages.

**Problem:**
After add custom CSS the designers noticed that is hard to find which element/row/column have the customized CSS (they forgot on which element they put the css), they was clicking everywhere inside the editor and checking manually where the customized CSS is.

**Feature Request:**
Show a list in the tools sidebar of all elements that have a custom CSS attached, something like the attached image

![custom-css](https://user-images.githubusercontent.com/386883/43474460-908a8122-94b8-11e8-9b6b-35341e00b0c4.png)

**Comment by Hanleymade** [comment]
Great idea. I hope Elementor listens to these sort of CSS customization feature requests.

**Comment by twerkema** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @choquo 

Thanks for your feedback, this functionality was added to the Navigator.
