### ISSUE TITLE
Woocommerce: Editable Region stuck with Product Content Widget

### ISSUE THREAD

**Issue by mcodigital** [elementor/elementor#5274]
Using **Elementor Pro Woocommerce Builder**, I've made a single product template that applies to all products. 

I've saved my template and proceeded to open up a single product to add additional content specific to the product. 

Unfortunately the editable region is somehow connected to a Product content widget, the editable region for the individual product only appears below this and I can't seem to add or move this editable region to somewhere else on the page. (please see image attached)

![image](https://user-images.githubusercontent.com/41978408/43498474-af97c900-9579-11e8-8896-f4a9b607fc9a.png)

SYSTEM INFO
==============================
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
	MySQL version: 5.6.38
	PHP Version: 7.2.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: http://localhost:8888/modaudio
	Home URL: http://localhost:8888/modaudio
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.21
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.12
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.5.8
		Author: WebDevStudios

	Elementor
		Version: 2.1.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0-RC3
		Author: Elementor.com

	Ocean Extra
		Version: 1.4.19
		Author: OceanWP

	WooCommerce
		Version: 3.4.4
		Author: Automattic

	YITH Woocommerce Request A Quote
		Version: 1.3.6
		Author: YITHEMES

== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at http://localhost:8888/modaudio/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.5 - 2:138959
			2018-07-30 08:07 +00:00
			x 4 times

**Comment by shilo-ey** [comment]
Hi @mcodigital 

Thanks for your feedback

In your case, the template sets the content area allowed to be edited.
To overcome this - you can either use other theme or change your product page template to Elementor [Full Width](https://docs.elementor.com/article/316-using-elementor-s-full-width-page-template) / [Canvas](https://docs.elementor.com/article/315-using-elementor-s-canvas-page-template)


Learn more here: https://elementor.com/blog/customize-woocommerce-product-page/

Thanks
