### ISSUE TITLE
Carousel & Testimonial Bug (Attached Video of bug)

### ISSUE THREAD

**Issue by a13banger** [elementor/elementor#5288]
Hello, i've not seen this talked about elsewhere so Ill leave this here.. It appears that the carousel auto slider/cycleing as well as the testimonial slider/cycling are connected in a weird way. So I have an images carousel on a page as well as a testimonial element further down the SAME page. I noticed that they were auto cycling at the same time. I didn't think too much about that until I manually advanced the image carousel forward to the next image and noticed that the testimonial advanced as well when I advanced the image carousel. The same is true in reverse, if I advance the testimonial then the image carousel advances as well... Attached is a zip file containing video of the issue occuring..

Thats all for now.. Hope everyone has a great day.
[Bug_elementor_pro.mov.zip](https://github.com/pojome/elementor/files/2255104/Bug_elementor_pro.mov.zip)

**Comment by acal** [comment]
Bummer. I just tested these two elementor elements together and cannot get this issue to reproduce. Maybe to you have some old javascript in your main.js that is affecting this? I remember having this issue with a completely different site where I was using hacked jquery libraries.

**Comment by newminya** [comment]
I have the same issue. Several different slides of Media Carousel on one page changes together when I press left or right arrow.

**Comment by newminya** [comment]
I have the same issue. Several sliders move together.

**Comment by shilo-ey** [comment]
Hi @a13banger 

We can't reproduce your issue.

If the issue persists please contact our support.

Thanks.
