### ISSUE TITLE
⛔ Blend Mode - doesn't work in Edge browser

### ISSUE THREAD

**Issue by AZVO** [elementor/elementor#5290]
Hi there,

I found a new bug.

The Blend Mode (overlay) doesn’t work in Microsoft Edge browser, as you can see on my Elementor bug page: http://luxuryweddingweb.com/elementor-bug/

Can you fix it please?

Thank you.

Best regards, Jaromir, AZVO

**Comment by Jaska** [comment]
Edge and IE doesn't support blend modes, so I think it can't be fixed.

https://caniuse.com/#feat=css-mixblendmode
