### ISSUE TITLE
Link States

### ISSUE THREAD

**Issue by mizejewski** [elementor/elementor#534]
Feature request: It would be great if Elementor settings could control font color for link states. I have default styles in my theme, but there are usually exceptions within any site. I was able to do it by adding a class to the widget and editing my custom CSS file, but it would be much easier if it were built into the Elementor settings.

`.callout-secondary .elementor-widget-container h2 a {
color: #000;
}
.callout-secondary .elementor-widget-container h2 a:hover {
color: #fff;
}
.callout-secondary .elementor-widget-container h2 a:visited {
color: #ffffff;
}`

**Comment by arielk** [comment]
I'm trying to better understand your request. Could you please explain more specifically?

**Comment by mizejewski** [comment]
Sure. I think a better example is the Reserve a Classroom link at https://beta.library.ucsf.edu/technology/. I began with the Icon Box widget instead of the Button widget, because I needed to include subtext. 

Basically, I'm suggesting that the hover state setting you provide for buttons light be included everywhere under custom text (along with letter-spacing, line-height, etc.)

**Comment by arielk** [comment]
I don't want to overload with advanced controls, I think that if we add a custom CSS area it will be able to solve this problem

**Comment by Leloush89** [comment]
please tell me... 1 where in the directory, how the file translator. 2 why word press only uses hex encoding of a color palette can I use hex or rgba with an alpha channel ?

**Comment by mizejewski** [comment]
Thanks Ariel -- that sounds reasonable.

**Comment by paaljoachim** [comment]
I will continue some thoughts on this issue. As I also suggested something similar in 623.

The client just wants to use one word that links to another page. I decided to use the heading element. Selected the text color the user wanted then added the link to it. The text color changed to reflect the themes CSS link color. It would be great to have in the Style tab under title a Link drop down where one can select the various states and apply the color to them outside of having to go into the themes CSS and adjust them.

The default. In the drop down there are then the various link states. Select any of them an a color box will show up below to where one can then select the color state of the specific link state.
![elementor-title-link-state](https://cloud.githubusercontent.com/assets/5323259/18801259/b12a2932-81af-11e6-8686-231f8c31ded1.jpg)

1. A drop down does not take much space. But having it like this the link state colors are a bit hidden away not easily seen. If the color could be seen beside the drop down link states then the user can just click the drop down and also see the link states and the color square beside them.

2. Another option could be to just give the link states and show a color square beside them. Showing the themes default colors and the user could then just click the squares and adjust the link states.

**Comment by black-eye** [comment]
+1

**Comment by papafew** [comment]
+1

**Comment by plasticboxuk** [comment]
+1 

I'm amazed I can't style links within a widget, mainly colour.  It's really important to be able to do quickly, and shouldn't require CSS code.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.0

Feel free to update

Thanks!
