### ISSUE TITLE
✅ 🚀 Feature Request: Ability to add an icon before <h1>..<h6> headings 

### ISSUE THREAD

**Issue by stefanobartoletti** [elementor/elementor#5368]
It would be a nice feature to have the ability to add a Font Awesome icon before any given heading (I mean h1 to h6 html tags), in a similar way to what is already possible with buttons, in example.

This should not necessarily be a different widget: a switch enabling the icon before the heading text could be added in the default Heading widget, then a dropdown box where one can chose the icon itself, pretty much like in every other widget where icons are used.

This feature is already present in many other widgets, so hopefully it should not be that difficult to add it even to headings.

"[Premium Addons](https://premiumaddons.com/heading-widget-for-elementor-page-builder/)" plugin already does this, but installing a new plugin just for this small addition is not really feasible.

**Comment by plxrisa** [comment]
+1

**Comment by formulaclick** [comment]
+1

**Comment by Xiytiifu** [comment]
+1 !

**Comment by qwik3r** [comment]
+1

**Comment by L-U-C-K-Y** [comment]
Would also love the option to add an icon inside the Heading widget.
This way, styling can still be done over theme style, opposed to an Icon List.

**Comment by IlPizza79** [comment]
Yes, please!

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you all for your feedback and apologies for the delay in responding! 🙏

We are currently organizing our GitHub to better separate Issues from Feature Requests, and while reading this request we concluded this is something that can already be solved by using the **Icon Box widget.** Please, refer to the video below:

https://github.com/user-attachments/assets/33e39b4e-ef0f-4e34-bfc1-ac26a232ec41

With this approach, you can remove the Description text and only the Title will be rendered on the frontend. You can align the icon to whatever position you want, as well as the size. You can also change the HTML tag of the Title to a vast list of options, including using H1-H6 tags.

I hope this helps!

If you still think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
