### ISSUE TITLE
Allow Image Max-Width by Pixels and not just Percent

### ISSUE THREAD

**Issue by d-marvin** [elementor/elementor#5376]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Having max-width option for images to be only percent seems silly as a designer, having used max-width using pixels pretty always in max-width situations. For example, an image that you want to fill 100% of its container but not if its container exceeds 300px. A common use would be a thumbnail in a short left column and its corresponding text in a wide right column. When the device is mobile and those columns stack, that thumbnail can now fill the screen and look silly. YES, there are workarounds, for example having to add something like "selector img {width:100%;max-width:350px;}", which I do very often.

It would just be convenient if the choice of pixels was standard.

**Describe the solution you'd like**

What would be nice is like this image. Add a switcher to define Max Width by either % or PX
![max-width](https://user-images.githubusercontent.com/42273482/43962400-9c0b6ab4-9c85-11e8-879b-f69e07504e9f.jpg)

Thank you!

**Comment by willcitizen** [comment]
@d-marvin I know it's not a solution, but I refuse to leave bits of css lying around embedded in widget controls - I created a small sass helper library that matches elementor's media breakpoints and provide some additional flexbox & sizing and squeezing capabilities you can't get from the ui (like making a section 50% width and centered) and then apply those classes as needed.

**Comment by black-eye** [comment]
+1

**Comment by BrookeRaraAvis** [comment]
+1

**Comment by beauwalsh** [comment]
100% agree—am I missing something? I can't figure out any reason to have a percentage max-width.

**Comment by hufer** [comment]
https://pafe.piotnet.com/#max-width Piotnet Addons For Elementor Max Width Feature

**Comment by d-marvin** [comment]
> https://pafe.piotnet.com/#max-width Piotnet Addons For Elementor Max Width Feature

Wow, thanks. So much stuff in there are things I end up hand-coding. Most of it are things you'd think would be standard, like inline blocks (and of course improved max-width). I just hope the plugin is more future-proof than my CSS overwrites.
