### ISSUE TITLE
Elementor Pro: Custom Display Conditionals

### ISSUE THREAD

**Issue by iamntz** [elementor/elementor#5406]
I'm trying to add custom items in any of these dropdowns and I can't figure out how. The [documentation](https://developers.elementor.com/theme-locations-api/) is not very helpful either.

![2018-08-13_21h37_09](https://user-images.githubusercontent.com/132062/44073105-e8817362-9f9a-11e8-9573-2c12f2d3ac32.jpg)

More precisely, what I need is to create a template for level 0 pages and a different template for their children.

Thanks.

**Comment by bainternet** [comment]
We are currently working on the documentation for Template Conditions API, I'll update once its ready.

**Comment by formulaclick** [comment]
Any news on this? I want to display a single post template based on a ACF field. This should be possible with a filter hook for display conditions. Is this possible or will be soon? Thanks

**Comment by formulaclick** [comment]
5 months later... any update? @bainternet

**Comment by lcswillems** [comment]
@bainternet any news on this?

**Comment by rami-elementor** [comment]
Elementor Theme Conditions dev-docs are located here - https://developers.elementor.com/docs/theme-conditions/
