### ISSUE TITLE
Elementor Pro Key exposed in database without any kind of encryption

### ISSUE THREAD

**Issue by choquo** [elementor/elementor#5407]
<img width="781" alt="elementor key" src="https://user-images.githubusercontent.com/386883/44075010-b4a5cd52-9f60-11e8-944e-f57f0b2e4e76.png">

Guys, I recently purchased the Unlimited Elementor pro license but I noticed that in the database in the table wp_options the key of my purchase is totally visible to any person with access to the server (phpmyadmin), if I share the source code with my client and he reinstall the website with another hosting provider other people / developers that begin to work with my client will be able to get my elementor pro key and use it on any other site (yes I know that I can block it from my dashboard) but I think this is a serious security issue.

My suggestion is to add some kind of encryption to the key maybe some md5, sha1 or whatever available in php in order to at least keep the key a little bit more secret and not easily exposed to people with access to the database.

Personally I don't feel too much comfortable knowing that others can view that information.

Hope you can help me/us doing something to fix this.

Thanks in advance.

**Comment by pmallek** [comment]
But isn't this key useless without elementor account access?

**Comment by Aviad-Herman** [comment]
Hi guys,
Thanks for raising this issue.
It's not a security breach since you can choose who to share DB access with.
It is solvable of course but not planned for the near future.
