### ISSUE TITLE
[Feature Request] Add MailChimp tags to form widget options

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#5418]
MailChimp now offers the ability to tag subscribers. It would be great if this was added to the form widget (in addition to the existing Groups option) so we could select which tags to assign to subscribers using that particular form.

About MailChimp tags:
https://mailchimp.com/help/getting-started-tags/

**Comment by svoegeli** [comment]
+1 
Our team would also like to specify MailChimp tags from Elementor forms.

**Comment by rockyviewweb** [comment]
Yes please add the ability to add MailChimp tags to subscribers!

**Comment by collectiefgeluk** [comment]
+1

**Comment by pvlagregor** [comment]
+1   This should be extremely simple to add.

**Comment by scottccoates** [comment]
ETA? Currently using Thrive to get around this, but would love to move to elementor 100%.

**Comment by avermat** [comment]
Also curious about the ETA on this.

**Comment by a5dev** [comment]
+1 for this feature request.

**Comment by gabrielstudart** [comment]
+1

**Comment by dannilou03** [comment]
+1 yes please to this feature

**Comment by gwmbox** [comment]
+1 it is there but does not appear to be working, my mailchimp subscribes are working for all other fields just not tags

**Comment by wmamedio** [comment]
+1 need that too, for multiple tags on different forms.

**Comment by calebweeks** [comment]
+1 - We are the same. Thanks for considering, Elementor Team!

**Comment by james-szuch** [comment]
+1 Definitely need this. Mailchimp is definitely emphasizing tags for segmentation.

**Comment by vinner0** [comment]
+1. Ability to choose in the form all available tags to pick from, and even add a new tag if it does not exist.
Abitily to choose multiple tags for 1 form submission is essential. Elementor, please help!

**Comment by Jordidriesen** [comment]
+1, a missing feature that I'm sure is easy to implement.

**Comment by dannyeldridge** [comment]
I've figured out a work-around, not sure if this is the right place to post. 

Using Zapier's webhook function, you can use a hidden field in Elementor to send some data with a default value of your choosing. Then, by creating a custom field in your Mailchimp's audience settings that receives the value sent from elementor, you can create a second Zap that is as follows: When a new subscriber is added to a list, if {the custom mailchimp value} equals {the custom value sent via Elementor}, then add tags to subscriber. 

I know its a bit hacky, but I used this method to both utilize a double opt-in and automatically add tags so I could trigger a specific welcome email.

**Comment by sunnyt7** [comment]
This is a necessity guys. The integration is rather incomplete without being able to add tags from a form submission.

**Comment by DIntriglia** [comment]
+1 team. Should be a quick implementation, but definitely a need for more complex campaigns.

**Comment by jonpbwd** [comment]
+1 from me. Elementor Pro is advertised to support Mailchimp and so this feature should be added as a priority. It' been almost a year since it was first requested

**Comment by absym** [comment]
Waiting for this feature too ...

**Comment by squarepixel** [comment]
This feels very half baked, this should be an easy integration fix for Elementor.

**Comment by scottccoates** [comment]
For anyone who is still facing this issue, you can around it by setting up a Webhook instead of Mailchimp/ActiveCampaign, etc… Use a free service to create a webhook ([Zapier](https://zapier.com/) or [Integromat](https://www.integromat.com/)). Then, have that webhook create/update the contact with whichever tags necessary.

**Comment by jonpbwd** [comment]
Thanks Scottcoates for that. The point is, this feature should be native in Elementor Pro. It's a simple fix and it is advertised to work with Mailchimp without the need for anything additional. This feature request should not even exist, it should be treated as a bug fix.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by eric-mathison** [comment]
> This issue has been resolved in Elementor Pro v2.7
> 
> Feel free to update
> 
> Thanks!

Is there a way to dynamically populate this field (ie from a field shortcode)?

**Comment by yanissi** [comment]
> > This issue has been resolved in Elementor Pro v2.7
> > Feel free to update
> > Thanks!
> 
> Is there a way to dynamically populate this field (ie from a field shortcode)?

Hey @eric-mathison ! I opened this issue here: https://github.com/elementor/elementor/issues/10088 if you'd like to support it as I think this would help the chances of it being implemented :)
