### ISSUE TITLE
.elementor-sticky--active is applied regardless of scroll position

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#5422]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When setting a section to sticky (top), it is always active.  The page loads and while it is loading I see css styles for when it is NOT sticky but as DOM finishes loading and javascript fires, the `.elementor-sticky--active` class is applied.  Even if you scroll down and back up, it does not release.  This gives us no mechanism to have custom styles for sticky vs non-sticky because it is always sticky.

p.s. Before the 2.1 updates we used to be able to add a new section above it, set it to no gap and then give the actual sticky section below it -1px top margin and that was the fix.  That no longer works.

## Steps to reproduce

1) Create a new Header template
2) Add a new section (i.e. a pre-built header template)
3) Make section sticky "top" (tried varying offsets, no difference)
4) Add some custom css that is only applied when sticky (`.elementor-sticky--active` class on section)
5) Save and apply to a test page (with enough content to make it scroll)
6) Load page and notice `.elementor-sticky--active` class is active regardless of scroll position

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

System info not needed, tested on multiple sites/ diff customers / diff hosting w/ same effect

**Comment by pingram3541** [comment]
Found a fix that worked for me as a temporary work around, similar to the previous fix.

Add an empty section just above the sticky header w/ no-gap for the columns and give it the same background treatment as the sticky section below it.

This creates a 1px section above the header but has the same background so it doesn't hurt the site visually but also allows the sticky header to load without it being sticky "active".

In the past, we would do the same except also adding a top margin of -1px to snug the sticky section up to the top of the page thus hiding the empty section above it from view, eliminating that 1px white space but this no longer works since the updates to the sticky function.

Would love to see some documentation for the 2 added options of "offset" and "effects offset".

**Comment by bainternet** [comment]
@pingram3541 	

The sticky library we used had to many issues so we rewrote the whole thing for our own uses, so with the new library there are 3 states which can be addressed via CSS classes:

- `.elementor-sticky`: any element that was sticky settings.
- `.elementor-sticky--active`: Once the element is sticky
- `.elementor-sticky--effects`: Once the sticky offset was reached.

also, Our guys uploaded a video yesterday with an example.

so If your top most element is defined as sticky with no offset it should always have both `.elementor-sticky` and `.elementor-sticky--active`.



[![How to Create a Transparent Sticky Header in WordPress with Elementor](https://img.youtube.com/vi/0QpeKGfvKy8/0.jpg)](https://www.youtube.com/watch?v=0QpeKGfvKy8 "How to Create a Transparent Sticky Header in WordPress with Elementor")

**Comment by kroeberk** [comment]
Apparently there has been a regression. This bug is happening again. Check https://www.fishpipe.de - the header should not always have the sticky class.

**Comment by pingram3541** [comment]
I've decided to go back to making my own sticky header until there are more options.  First, I've found it better to use a sticky header only when scrolling up so as to not steal any vertical space from the viewport during discovery (i.e scrolling down) vs history (scrolling back up) and UX tests seems to support this too as being more preferrable.

I still do this 100% within Elementor, I just use some custom javascript and though I'd share, maybe it's good enough to inspire possible inclusion as a feature of the sticky header?

https://wplovr.com/sticky-scrollup-menu/

*has complete json for your amusement, hopefully some may find it useful to them

Cheers!

**Comment by dribgib** [comment]
I can confirm this is still occuring - no class toggling regardless of options selected (offset, effect offset, sticky, etc.) - prevents the ability to style sticky vs non-sticky.

**Comment by pingram3541** [comment]
@dribgib Hi Colton, have you tried adding an empty section above your header with a min-height of 1px and a negative bottom margin of 1px?  For some reason this still seems to work on all my older sites using the built-in sticky option you might give it a try.

**Comment by pierrehansen** [comment]
+1 

Yes, 01.10.2019 and still not working. Class is always added. Quite annoying.

**Comment by NestorMenta** [comment]
I used the fix brought by @pingram3541 and it works, but it's strange because I've recently used sticky effects in a site with Generatepress without a problem. I'm working on a new site with Astra and it's the first time I've seen this problem.

**Comment by Displee** [comment]
+1

**Comment by idocme** [comment]
+1

**Comment by andrewvink** [comment]
Also having this issue.

I noticed on the Section if I had padding-top and no margin-top the "active" classes was constantly applied. 

As soon as I zeroed out all padding-top on the Section - I didn't have the issue anymore. The workaround I'm using is just having 1px margin-top and then the padding.

Section > Advanced > 
margin-top: 1px
padding-top: 0px

Haven't fully tested this, but so long as I have margin-top: 1px on the Section it's working for me.

@pingram3541 suggestion also works.

**Comment by bluantinoo** [comment]
Issue is present today with Elementor Pro Version 2.9.3 along with Hello Elementor theme Version: 2.3.0.

This only happens if the sticky section is the very first visible on the page.
If you have anything above (like a topbar) the issue does not occur.
If you use responsive options to hide the topbar on mobiles, issue occurs only on mobiles.

an empty section above all does not prevent the issue for me. the element above must have an height to prevent issue.

**Comment by bentalgad** [comment]
+1 beta 3 with stopped styles, but basic bugs are still waiting...

**Comment by Sadejeal** [comment]
Does someone found or know the solution please ?
Actually i'm struggling to finish my naviguation bar because of this problem, the header is always sticky regardless of effects offset which only apply to my css code.
The thing is I can use the code above because I am trying to change image in my naviguation bar and make it thinner, or because I am not experimented enough to deal with js in my situation.
If someone can help me, you could take a look at the problem on https://paradigma.fr/ I would be grateful.
Thank you !

**Comment by JayCecchine** [comment]
This is still an issue now.

None of the fixes referenced above work.

It is either I deal with a 1px white gap above header section and the stick effect works OR I apply above fixes, lose the 1px white gap but sticky effects are active at all times. 

What a bummer.

**Comment by pierrehansen** [comment]
Yes, PLEASE!

People (+ paying customers like me) are asking for this for years. If annoys me everytime when setting up a webseite with sticky header. Always have to fiddle around with empty sections and strange 1px workarounds.

 What we get with updates is spinning text widgets etc. which nobody needs! Really annoying.

Big question mark why it is not addressed.

**Comment by HighanDry88** [comment]
> 
> 
> Yes, PLEASE!
> 
> People (+ paying customers like me) are asking for this for years. If annoys me everytime when setting up a webseite with sticky header. Always have to fiddle around with empty sections and strange 1px workarounds.
> 
> What we get with updates is spinning text widgets etc. which nobody needs! Really annoying.
> 
> Big question mark why it is not addressed.

Have you found a fix? I'm still trying to get answers from anyone on how to get it working period.
The 1px section on top does not work for me.  I've tried making brand new headers and testing all sorts of methods, none of them work at all!

This is the latest one I tried - https://igniteweb.design/blog/elementor-header-transparent-sticky-scroll-changes/

**Comment by 79ho3ein** [comment]
+1

**Comment by DorShahar** [comment]
Hi Everyone. 
The class you target is not correct. You should target `elementor-sticky--effects` after you enter a number above 0 to the Effects offset control inside Motion effects > Sticky :
![image](https://user-images.githubusercontent.com/19154938/126470009-8b2f2e08-7bb0-44fa-8419-2670c0c93476.png)

Then, the class `elementor-sticky--effects` will be triggered. 
We will improve the UI to explain this as well as changing the documentation. 

Thanks.

**Comment by instadesign** [comment]
Another year later, I'm still having this issue. I've set up my container exactly as described here by @DorShahar but it doesn't work properly I can only get it to work occasionally with the inspector panel open, when viewing the page normally it never seems to work. When I inspect element after scrolling, I see `elementor-sticky--active` in the classes but not the `elementor-sticky--effects`.

If I try adding margin-top the container stops being sticky entirely! If I try adding another container above it still doesn't work. I've sunk 3 hours into this now that I'm not being paid for after telling my client I could do this quite quickly... highly frustrating!

**Comment by fsarnataro** [comment]
That wrong behaviour is still happening and setting the Effects Offset, as suggested by @DorShahar, doesn't return any good result, as of version 3.7.7.
I solved this issue by editing `jquery.sticky.js` in `wp-content/plugins/elementor-pro/assets/lib` directory, altering line 291 from

`if ( distanceFromTriggerPoint > 0 ) {`
to
`if ( distanceFromTriggerPoint > 0 - settings.effectsOffset ) {`

and line 299 from
`if ( distanceFromTriggerPoint <= 0 ) {`
to
`if ( distanceFromTriggerPoint <= 0 - settings.effectsOffset ) {`

Of course I had to minify the script file to replace jquery.sticky.min.js, that is the file called by the loading script.

I hope it can help someone.
Cheers.

**Comment by hasintha** [comment]
This behavior is still apparent though the sticky-effects class can be used with setting a negligible offset value whence the class is added when scrolling. Thanks@bainternet sir for pointing this out. Much obliged for the thread starter sir as well.

**Comment by hasintha** [comment]
> That wrong behaviour is still happening and setting the `Effects Offset`, as suggested by @DorShahar, doesn't return any good result, as of version 3.7.7. I solved this issue by editing `jquery.sticky.js` in `wp-content/plugins/elementor-pro/assets/lib` directory, altering line 291 from
> 
> `if ( distanceFromTriggerPoint > 0 ) {` to `if ( distanceFromTriggerPoint > 0 - settings.effectsOffset ) {`
> 
> and line 299 from `if ( distanceFromTriggerPoint <= 0 ) {` to `if ( distanceFromTriggerPoint <= 0 - settings.effectsOffset ) {`
> 
> This correction makes the `Effects Offset` parameter useful: setting it to 200, for example, the effect will be activated when the page scroll reaches 200px. For an immediate response, set it to 1.
> 
> Of course I had to minify the script file to replace jquery.sticky.min.js, that is the file called by the loading script.
> 
> I hope it can help someone. Cheers.

Thank you sir

**Comment by SirLouen** [comment]
> That wrong behaviour is still happening and setting the `Effects Offset`, as suggested by @DorShahar, doesn't return any good result, as of version 3.7.7. I solved this issue by editing `jquery.sticky.js` in `wp-content/plugins/elementor-pro/assets/lib` directory, altering line 291 from
> 
> `if ( distanceFromTriggerPoint > 0 ) {` to `if ( distanceFromTriggerPoint > 0 - settings.effectsOffset ) {`
> 
> and line 299 from `if ( distanceFromTriggerPoint <= 0 ) {` to `if ( distanceFromTriggerPoint <= 0 - settings.effectsOffset ) {`
> 
> This correction makes the `Effects Offset` parameter useful: setting it to 200, for example, the effect will be activated when the page scroll reaches 200px. For an immediate response, set it to 1.
> 
> Of course I had to minify the script file to replace jquery.sticky.min.js, that is the file called by the loading script.
> 
> I hope it can help someone. Cheers.

Also worked for me this fix... brutal that they have not fixed this for 5 years and @DorShahar closed this still broken
