### ISSUE TITLE
Woo Single Product - Add to Cart Widget Displaying Global Addons in Col vs row

### ISSUE THREAD

**Issue by BravoSaber** [elementor/elementor#5437]
## Prerequisites

- [Done] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [Done] The issue still exists against the latest stable version of Elementor. 
  *Issue was not present in the First beta release prior to RC1.

## Description

When using the Global Add-on Extension by Woocommerce, the additional options made available below Variations are presented in Columns vs Rows.

## Steps to reproduce

Use the official Global Add-on Extension by woocommerce with Elementor Pro 2.1.1 Add to Cart widget and the options will be played out in col vs rows.  The more Add-on options the more compact it will become. 

## Isolating the problem

- [Yes] This bug happens with only Elementor plugin active (and Elementor Pro).
- [Yes] This bug happens with a default WordPress theme active.
- [Yes] I can reproduce this bug consistently using the steps above.
- Also removed all plugins and tried in variations. 
- Wasn't able to narrow down the css responsible, the add ons appear to be shelled under Product-Addon, Product-addon-[Modifier Name].  But not sure whats controlling the width of each Product-Addon thats restricting it to a percentage of width vs 100% width per add-on within the cart shell 

![screen shot 2018-08-15 at 12 59 17 pm](https://user-images.githubusercontent.com/41579815/44161458-629aa380-a08b-11e8-8201-5296a3718879.png)

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.34
	PHP Version: 7.0.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 65M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.hartphotoblog.com
	Home URL: https://www.hartphotoblog.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

== Active Plugins ==
	Advanced Database Cleaner
		Version: 2.0.0
		Author: Younes JFR.

	BJ Lazy Load
		Version: 1.0.9
		Author: Bjørn Johansen, Aron Tornberg, angrycreative

	Easy WP SMTP
		Version: 1.3.7
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.2
		Author: Elementor.com

	Lenix Elementor Leads addon
		Version: 1.2
		Author: Lenix

	SSL Insecure Content Fixer
		Version: 2.7.0
		Author: WebAware

	WooCommerce
		Version: 3.4.4
		Author: Automattic

	WooCommerce Bulk Editor
		Version: 2.0.2
		Author: realmag777

	WooCommerce Checkout Field Editor
		Version: 1.5.13
		Author: WooCommerce

	WooCommerce Photography
		Version: 1.0.14
		Author: WooCommerce

	WooCommerce Product Add-ons
		Version: 2.9.6
		Author: WooCommerce

	WooCommerce Quick View
		Version: 1.1.13
		Author: WooCommerce

	Wordfence Security
		Version: 7.1.10
		Author: Wordfence

	WP Fastest Cache
		Version: 0.8.8.3
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.5.1
		Author: Emre Vona

	WP Media folder
		Version: 4.6.0
		Author: Joomunited

	Yoast SEO
		Version: 8.0
		Author: Team Yoast


== Must-Use Plugins ==
	Joomunited WP Framework
		Version: 1.0.2
		Author: Joomunited

	WP Cerber boot module
		Version: 1.0
		Author: Gregory

		

				<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by BravoSaber** [comment]
Just another ref pic, if I had another Global Add-on, the Cart Widget then condenses further, taking space from the button and other options. 

![screen shot 2018-08-15 at 2 39 16 pm](https://user-images.githubusercontent.com/41579815/44166319-1c4c4100-a099-11e8-8be5-61f617a62c74.png)

**Comment by BravoSaber** [comment]
Anything else needed to demonstrate or reproduce?

**Comment by Bookyourroom** [comment]
Hey, I am a new to the world of custom css and I am experiencing the same problem as BravoSaber and DaCon. His solution seems to be working however I am not able to find the right ID for the object I want to change. Could someone walk me through the solution step by step?
Thanks in advance!

**Comment by baliideas** [comment]
Hi, im currently having this same issue, did anyone ever, find a resolution or a workaround for this problem, really need to the help, thanks

**Comment by Ramshackles** [comment]
Using woocommerce product add-ons and elementor pro looks awfull

**Comment by BravoSaber** [comment]
@bainternet any thoughts on this as of late?  I was able to over come the issue with a css addition to the cart widget.
`#content .cart{
  display: grid;
}`

But that’s been broken, the official woo Global Addon returns to horizon stack vs vertical stack

**Comment by BravoSaber** [comment]
@brainternet @Ramshackles  @smile00000 
Not sure if you already have your own fixes, found this worked under the cart widget.  Basically going from the grid to defining the div as a col under the Display: Flex;. 
`.cart{
  flex-direction:column;
}`

**Comment by Ramshackles** [comment]
Thanks I will try that.

I was actually hoping someone from elementor would havd chimed in by now.

I would much prefer fixing and polishing on current feature set instead of developing new stuff.

@bainternet

**Comment by BravoSaber** [comment]
Should be alright, this is with Global Addons from Woo, as everything within the .Cart widget everything should flow correctly.

![screen shot 2019-02-22 at 1 52 25 pm](https://user-images.githubusercontent.com/41579815/53264380-6ac24400-36a9-11e9-8cdf-f168dfab6e24.png)

**Comment by BravoSaber** [comment]
Don't mind the double class entry, was playing with some shadow ideas prior to merging into the primary button class above.

**Comment by autumnHoward** [comment]
This may be a separate issue entirely but- 
Could anyone clue me in on which Elementor widget y'all used to get the products add-ons to display at all? I have both global and single product add-ons created, and neither are visible in Elementor or the customer views.

**Comment by jordan-beck** [comment]
I hate to necro an old thread, but I am having this same problem and finding little resolution.  The above css did not work for me either.

**Comment by yoske25** [comment]
Same as here. I tried using Booster.io but stuff just breaks and doesn't look good :(

**Comment by 79ho3ein** [comment]
+1
