### ISSUE TITLE
Dynamic content for tabs

### ISSUE THREAD

**Issue by smokingbehind** [elementor/elementor#5454]
## Prerequisites

- [-] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [-] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hi, please add dynamic content (acf fields) for standard Elementor TABS widget

**Comment by black-eye** [comment]
+1

**Comment by Sekhemty** [comment]
+1

**Comment by mikesale** [comment]
+1 
por favor!

**Comment by mylimoproject** [comment]
+1

**Comment by Guang0404** [comment]
Please do guys, if anything, make everything dynamic content capable lol including sliders! If not i might as well switch to Webflow or some other highly customizable CMS like GraphQL.

**Comment by Turanligil** [comment]
+1

**Comment by slomeli79** [comment]
+1

**Comment by hendriq** [comment]
+1

**Comment by AlfaBlue** [comment]
+1

**Comment by harunalikadic** [comment]
Absolutely. +1 
I thought every widget had dynamic option ..

**Comment by ivyliups** [comment]
=1

**Comment by bentalgad** [comment]
+1 This is so basic and still missing. it fills like Elementor has left the building... a lot of posts on how to do fancy effects but the most basic features are still missing from the beginning of the plugin's first release.

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field.

**Comment by moonshinenet** [comment]
+1

**Comment by GiuMagnani** [comment]
+1

**Comment by davewarfel** [comment]
+1

**Comment by prajjwalgeek** [comment]
2 years and still ignored? Seems like elementor is absolutely disconnected to its userbase!?

**Comment by 79ho3ein** [comment]
+1

**Comment by arielk** [comment]
ref: https://github.com/elementor/elementor/issues/5979

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/5979 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
