### ISSUE TITLE
More options for elementor slide (slick)

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#5476]
Please add more options to image/normal slider like

- Center mode
- adaptive height
- lazy loading
- Variable Width

**Callbacks (onLoad, onChange etc)**

Demos: http://kenwheeler.github.io/slick/

The only options we have are these:
![image](https://user-images.githubusercontent.com/2544046/44336559-82154000-a480-11e8-91ef-9c664e84f4ac.png)

![image](https://user-images.githubusercontent.com/2544046/44336617-affa8480-a480-11e8-9c0c-430fc0d02fa0.png)

**Comment by black-eye** [comment]
+1

**Comment by amindiary** [comment]
@bainternet  isnt there any developer api or something like that to be able manipulate data-settings?
I need center mode.
```
jQuery( ".elementor-element-3622918" ).data( "settings" ).centerMode = true;
jQuery( ".elementor-element-3622918" ).slick();
```

tried this, but nothing changed.

**Comment by DJviolin** [comment]
I try to create a horizontal photography portfolio, similar what [Flothemes](https://demo.flothemes.com/crowd-neo/gallery/editorial-wedding-photoshoot/) does with Slick. If you featue portrait and landscape images, the portrait images overflowing to the bottom. Only setting `centerMode` is not enough, you need `variableWidth` too. I created a monkey patch in `elementor/assets/js/frontend.js`:

```js
var slickOptions = {
    centerMode: true,
    variableWidth: true,
    // ...
```

Plus I added the following CSS in my child theme:

```css
.elementor-slick-slider .slick-slide img {
  max-height: 50vh !important;
}
```

Instead of respecting how many images (for example, default is 3) we should display on the screen, we display random number of images, but we use a common height for both portrait and landscape images. My [proposal](https://github.com/pojome/elementor/issues/5704) is to offer a button to turn this on, with the ability to set the maximum height for the slider (in px or vh).

**Comment by DJviolin** [comment]
I'm trying to use the API to modify Slick behaviour, instead of monkey patching, but I can't figure out how to get it work, this is what I tried:

```php
<?php
function elementor_api() {
  if ( ! defined( 'ELEMENTOR_VERSION' ) ) {
    return;
  }
  ?>
    <script type='text/javascript'>
      (function($) {
        /**
         * @param $scope The Widget wrapper element as a jQuery element
         * @param $ The jQuery alias
         */ 
        var imageCarouselHandler = function($scope, $) {
          var prototype = Object.getPrototypeOf($scope);
          console.log(prototype);
          prototype.slick('centerMode', true, true);
          prototype.slick('variableWidth', true, true);
        };

        // Make sure you run this code under Elementor.
        $(window).on('elementor/frontend/init', function () {
          //elementorFrontend.hooks.addAction('frontend/element_ready/global', imageCarouselHandler);
          elementorFrontend.hooks.addAction('frontend/element_ready/image-carousel.default', imageCarouselHandler);
        });
      })(jQuery);
    </script>
  <?php
  if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
  }
};
add_action( 'wp_footer', 'elementor_api', 99 );
```

**Comment by ERROPiX** [comment]
Hi @DJviolin 

Where did you found the documentation on this jQuery event `elementor/frontend/init` this bit saved my life while trying to hook into frontend events

```
...
$(window).on('elementor/frontend/init', function () {
          //elementorFrontend.hooks.addAction('frontend/element_ready/global', imageCarouselHandler);
          elementorFrontend.hooks.addAction('frontend/element_ready/image-carousel.default', imageCarouselHandler);
});
...
```
I didn't seen anything about it in the official docs, and documentation is missing a lot of the PHP and JS APIs

Thanks

**Comment by amindiary** [comment]
@ERROPiX , @DJviolin exactly, my question, where are those useful events I can't find in developer documentation.
Thank you.

**Comment by DJviolin** [comment]
I don't remember. I read these pages:
https://code.elementor.com/js-hooks/
https://code.elementor.com/hooks/

But I think I found in the frontend.js file as well. But for some reason, it's not working with Slick Slider, so I'm using my last example. If you have a working example how to target Slick's settings with it, please share. I also noticed that Slick's Init and reInit events are hijacked by Elementor's own initialization? If I target these events, nothing happens:
http://kenwheeler.github.io/slick/

**Comment by cjmetacrawler** [comment]
+1

**Comment by Dimosthenis** [comment]
There should be more options yes.
For a workaround you can try this:

**Extract the settings object from data-settings**:
let slick_settings = jQuery('.elementor-element.your-class').data('settings');

so slick_settings is: {"navigation":"dots","infinite":"no","pause_on_hover":"yes","autoplay":"yes","autoplay_speed":5000,"speed":500,"direction":"ltr"}

**Add your settings**
slick_settings.rows = 2;
slick_settings.slidesPerRow = 5;

**Unslick elementor carousel**
elementor_image_crousel.slick('unslick');

**And re-init with the updated settings**
elementor_image_crousel.slick(slick_settings);

**Comment by taropaa** [comment]
+1 to lazy loading. I replaced a revolution slider with the built-in Elementor Slider. Was excited about reducing the number of scripts loaded, but then got hit by the fact that the elementor slider tries to load all images at the same time.

**Comment by aronv111** [comment]
Hello all,
Looking for a bit of help with slides and redirecting to another page after the slides are complete with a delay of xxxx milliseconds. Working on a staging / local site with MAMP PRO.

Trying to have an "Intro" page (like a landing page) with non-loop slides, hold for a # of milliseconds after last slide, then redirect to a product page.
I tried the suggested approaches from:
https://stackoverflow.com/questions/7276677/jquery-redirect-to-url-after-specified-time

However, I get following issues: "content" error from Elementor, does not do anything, goes immediately to the next page (I can see a flicker of the slides starting).

Can any of you make a suggestion for code and best placement of the code, ex: use Elementors "/HTML" element.

+1 lazy loading

**Comment by danielmcclure** [comment]
+ Adaptive / Max Height

**Comment by shilo-ey** [comment]
Hi All!

From v2.7 Pro Elementor will deprecate `Slick.js` and start using `Swiper.js` for the carousels created by Elementor.

therefore, this request is no longer relevant.
If you have specific requests for slides widget, please create a new issue and don't forget to follow the guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.

You can read more about this here: https://developers.elementor.com/elementor-2-7-moving-sliders-from-slick-to-swiper/

Thanks!

**Comment by astbarc** [comment]
Hi @shilo-ey ,

Will v2.7 Elementor pro version include lazy loading support for slides?

Thanks!

**Comment by DJviolin** [comment]
Any ETA on when v2.7 will be released?
