### ISSUE TITLE
Elementor Can't Scale Full-Width Image with Text Overlay

### ISSUE THREAD

**Issue by glenviewjeff** [elementor/elementor#5504]
See this thread (with a couple of well-meaning but confused responses.)

There is apparently no way to get an image to display in full without cropping, scaling to the width of the window, with overlaid text centered vertically over the image.

Here’s an example of a website that does this successfully (presumably without Elementor.) See the “Fix Our Parks" text over the image and how the text stays centered and the full image resizes as you resize the window. https://savingplaces.org/ (Note: the image changes with smaller layouts, which is not relevant to the discussion.)

Using an uncropped image as background that displays in full uncropped with centered text overlay  is a basic layout that any page builder should be able to easily accomplish. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by obe1968** [comment]
What you are attempting to do in Elementor is completely possible, and has been done numerous times :) I would suggest that you take a look at the documents on the Elementor site at docs.elementor.com as well as watch some of the fantastic videos that members of the Elementor Community have posted on YouTube. The one that comes to mind are the ones created by Ferdy Korpershoek. Just search on YouTube elementor ferdy korpershoek. There are others, but his are the longest and most in depth for people that are new to web design and/or Elementor. Once you know the ropes and how to use the tools, you will be looking back and laughing about this some day.

Best of Luck!!!

P.S. This is not a bug, and your would have gotten a quicker response from the Elementor Community group on Facebook. If you are not already a member, I suggest joining there as well :)

**Comment by glenviewjeff** [comment]
https://wordpress.org/support/topic/text-overlay-limitation/

**Comment by glenviewjeff** [comment]
Maybe a picture will help? Elementor cannot do this. See how the image and section scale vertically to accommodate the narrower display width so that the entire image is shown?

![Example](https://i.imgur.com/NCnjT3x.jpg)

**Comment by glenviewjeff** [comment]
For others that may also come across this deficiency in Elementor which developers refuse to acknowledge, and to some of the developers who may not know how to implement or understand this basic layout, here's how to kluge it:

1. Create a stretched section, content width: full, columns gap: no gap.
2. Drag the html widget inside and paste the below html inside.
3. Go to your theme's custom css section and paste the below css inside.

html:
<img class="fullimage" src="http://yourdomain.com/yourimage.jpg" />
<div class="captionoverlay">
<p>Your overlaid text</p>
<p>goes here</p>
</div>

css:
.fullimage {
    display: block;
    height: auto;
    width: 100vw;
}
.captionoverlay {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate( -50%, -50% );
    text-align: center;
    color: white;
    font-weight: bold;
}

**Comment by shilo-ey** [comment]
Hi @glenviewjeff 

Thanks for your feedback.

You can use Custom Background positioning to create this scenario and accomplish it with Elementor.
Thanks

**Comment by schmekism** [comment]
I watched the video on "Custom Background positioning"  

That feature appears to only allow for a fixing the background. not elements on top of the background that scale dynamically

**Comment by glenviewjeff** [comment]
Sounds familiar. I may have given up on elementor by the time they
responded.

**Comment by schmekism** [comment]
I should probably go back and change that post.  It ended up working with
the text module briefly.  What I am concluding is that Elementor is REALLY
buggy.  First site I've built with Elementor and I have already sent 10
issues to the Elementor team, all of which I think are bugs, including
dynamic scaling of elements on a background... As that is possible in
Elementor... question is... can you get it to work as designed.
