### ISSUE TITLE
🔗 🚀 Feature Request: Tooltip option for icon list widget (Merged with #16415)

### ISSUE THREAD

**Issue by temsool** [elementor/elementor#5512]
Will be good if we have option for tooltip on icon list widget, like this image: 

![image](https://user-images.githubusercontent.com/2544046/44521973-b6d20300-a6dd-11e8-99b1-b631e1776463.png)

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by amindiary** [comment]
@bainternet found a plugin that add this feature 
[Elements Plus!](https://wordpress.org/plugins/elements-plus/)
hope help other people looking for this feature

![image](https://user-images.githubusercontent.com/2544046/44523078-547b0180-a6e1-11e8-8b7b-ef8cbda9dc09.png)

**Comment by nicholaszein** [comment]
Hello @temsool!

Thank you for your submission! 🙏

📋 There is another issue that is on the same subject, but it's more detailed. For this reason, I'm closing this issue and ↔️ Merging it with issue #16415, so we can have all the discussions in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉

Best regards,

Nick
