### ISSUE TITLE
[Feature Request] WC Single Product Image Carousel for Main Image & Additional Gallery Images

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#5532]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Currently, we can only click on product thumbnails beneath the main image to view additional product gallery images. I'd like to see a back arrow & forward arrow to view all product images in a carousel without having to click on product thumbnails. Gives user 2 options to view product images.

**Comment by lior-sh** [comment]
Hi @TomRaraAvis,

You can use Image/Media Carousel/ Gallery - dynamic

Thanks!
