### ISSUE TITLE
Be able to set positioning absolute | relative ... for each element

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#5568]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It would be good to be able to set **position:absolute** for elements and enter values for **top/bottom/right/left**

something like this:
![image](https://user-images.githubusercontent.com/2544046/44399374-0b477800-a550-11e8-82c5-a669d44d1119.png)

https://github.com/pojome/elementor/issues/5449

**Comment by amindiary** [comment]
@bainternet this is repost of https://github.com/pojome/elementor/issues/5449 with guidelines

**Comment by shilo-ey** [comment]
@amindiary 
Thanks for your feedback,

We are actively developing an absolute position feature that will allow you to position any element exactly where you want in.

Thanks

**Comment by shilo-ey** [comment]
This feature has been added in Elementor v2.5.0

Feel free to update!

**Comment by surjithctly** [comment]
Still no option for Relative? I only see absolute & Fixed.
