### ISSUE TITLE
Inline editor caret position

### ISSUE THREAD

**Issue by vfxdude** [elementor/elementor#5569]
When clicking to edit, the caret position is at the bottom of the text, and not where clicked, so it's necessary to click again. This is a minor issue, but with other editors/builders the caret position is set to where it's clicked (also contentEditable).

**Comment by black-eye** [comment]
+1, this one is really unintuitive.

**Comment by vfxdude** [comment]
This is what messes up the caret position (in editor.js):

`this.$currentEditingArea.html(contentHTML);`

If I comment out this line and modify inline-editor.js like this:

```
//this.getRange().selectNodeContents(editor);
//this.setRange();
this.focus();
```

Then the caret position is where clicked. I guess it's necessary to add unrendered content before editing, but maybe there's a workaround?

**Comment by vfxdude** [comment]
I guess adding the unrendered content is only necessary if there is a shortcode in the text? If so, there is an option to skip adding this if there's no shortcode in it. That would solve the problem for me, since I'm never using shortcodes in the editor (using the shortcode Widget instead).

Another solution would be to treat shortcodes like TinyMCE does (visual editor), as a rendered component that can not be edited. Adding the css `user-select: none;` would fix that.

**Comment by vfxdude** [comment]
![elementor-inline-editor-test](https://user-images.githubusercontent.com/20110677/44945470-84fe2200-adea-11e8-80f1-be65da419f05.gif)

**Comment by shilo-ey** [comment]
Hi @vfxdude 

We previously checked your suggestion, it does resolves this specific minor issue, but it causes other misbehaviors and conflicts.

Currently, I don't see how we are going to change this behavior.

If any breakthrough will occur we will update this issue.

Thanks!
