### ISSUE TITLE
Elementor / Svg / Icons 

### ISSUE THREAD

**Issue by AdamFrish** [elementor/elementor#5570]
Hey folks , what’s up ? i wanna talk today , about future .. future what give more compobilities
I wanna talk about - SVG icons in elementor ( when we can start upload it ) thats give :

- Better performance
- Better quality
- Better control on colors on hover

in my screen i wanna show you example , how i see it :
![screen4](https://user-images.githubusercontent.com/42729189/44716488-1f94f300-aac3-11e8-80ac-816b2c7a69aa.jpg)

**Comment by black-eye** [comment]
+1

**Comment by BrookeRaraAvis** [comment]
+1

**Comment by BrookeRaraAvis** [comment]
related to #110

**Comment by DeoThemes** [comment]
+1 Would like to see ability to connect any icon font for developers.

**Comment by reelism** [comment]
+1

**Comment by amindiary** [comment]
+1
with options to recolor SVG icon

**Comment by Matherone** [comment]
+1.

Adding that svg files should be accepted as standard image input as well, not just as icons.

**Comment by jazir5** [comment]
Agreed, the ability to upload our own icons would be great. +1

**Comment by timsamuelsson** [comment]
+1

**Comment by Ver3** [comment]
@arielk Has been moved to a future milestone?

Ps. small addition: please consider adding shadow settings (same as with fonts)

**Comment by black-eye** [comment]
Hm, unfortunately, this issue seems to be the first one to go, when it comes to postpone something... :( 5 months ago it had pr, and then it moved from 2.3.0, 2.4.0, 2.5.0 to nothingness. Hopefully 2.6.0 appears soon and will be the last one.

**Comment by alekseykurylev** [comment]
+1

**Comment by signrat** [comment]
its in their icon box (pro version) gonna email bout just a icon widget
[](https://premiumaddons.com/icon-box-widget-for-elementor-page-builder/)

**Comment by alriksson** [comment]
+1

**Comment by TheRollingPanda** [comment]
+1 for the option to select SVG for all icon widgets

**Comment by tristanleboss** [comment]
+1

**Comment by alriksson** [comment]
Will it become inline svg or img tag? I would like to have the options within svg to say inline or image.

**Comment by zimirando** [comment]
+1

**Comment by fthiesen** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!
