### ISSUE TITLE
Button icon alignment

### ISSUE THREAD

**Issue by mizejewski** [elementor/elementor#561]
If an icon is added to a button, it should stay aligned with the text. If the button is getting too small, then the line should wrap rather than pushing the icon out of alignment. 

<img width="425" alt="button-icon" src="https://cloud.githubusercontent.com/assets/974442/18492178/be7d3d3e-79be-11e6-8149-8c06d6531b86.png">

**Comment by arielk** [comment]
We can fix it with some CSS like this:
`.elementor-button-content-wrapper {white-space: nowrap;}`

But I think it will cause other problems, so we need some time to figure out

**Comment by mizejewski** [comment]
Thanks for looking into it.

**Comment by Pagester** [comment]
If you move the button text <span into the <span containing the FA icon and remove the display:inline-block from the button text class that will solve your problem.

See code change below, obviously the class names would need to be amended so as to not confuse people, 

`<span class="elementor-align-icon-left elementor-button-icon">
	<i class="fa fa-calendar-check-o"></i>
	<span class="elementor-button-text">Workshops &amp; special events</span>
</span>`

and remove from class like below:

`.elementor-button .elementor-button-text {
    /* display: inline-block; */
}`

**Comment by BradMK** [comment]
Has there been any more progress on this? This issue is still present in the current version.

**Comment by black-eye** [comment]
+1

**Comment by fxaviers** [comment]
More than 2 years and the problem remains. Did the Elementor team give up on this problem?

**Comment by fxaviers** [comment]
I am organizing the 3 year party of this problem. Come'on, is it so complicated to solve a responsive alignment problem on a button with icon?

I have no idea what risks this can bring to other buttons, but in all projects I use the code below to make it less worse:
`.elementor-button .elementor-button-text {
    display: unset;
}`
![image](https://user-images.githubusercontent.com/17536232/62707079-1f85be80-b9c7-11e9-8b13-72bfe010729b.png)
![image](https://user-images.githubusercontent.com/17536232/62707089-23194580-b9c7-11e9-8a95-a7b97cacb4db.png)

@arielk @bainternet @shilo-ey Am I asking too much to fix such a known old problem?
