### ISSUE TITLE
Disable button in product archive page

### ISSUE THREAD

**Issue by zimmiel** [elementor/elementor#5624]
Hi!
Just an idea
In WooCommerce product archive page did not find (disable button)
It would be nice have a choice show or hide buy button in product archive page
![cart](https://user-images.githubusercontent.com/42843497/44863567-25870180-ac86-11e8-8265-d243ba993351.png)

**Comment by black-eye** [comment]
+1
I'd like to have this option too. For now I can disable it via Theme Customizer (WPBF), but it would be more convenient to do it via Elementor. Not to mention, that even when the button is disabled in the Customizer, it's still visible in Elementor Edit view (but not on live page).

**Comment by shilo-ey** [comment]
You can use WC hooks to remove this button:
```PHP
add_action( 'woocommerce_after_shop_loop_item', function(){
	remove_action( 'woocommerce_after_shop_loop_item', 'woocommerce_template_loop_add_to_cart' );
}, 1 );
```

Thanks
