### ISSUE TITLE
⛔ 🔗 🚀 Feature Request: Nav Menu Brand (Duplicate of #3275)

### ISSUE THREAD

**Issue by AppGrind** [elementor/elementor#5651]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Like how bootstrap has been doing, displaying Branding for Navbar e.g Company name, or just the text Navigation, which is what I have on the left navigation in my sites. I know currently if navigation is displayed on top normally one places a site logo on e.g left column and a Nav Menu element on right column.

**Describe the solution you'd like**
I believe it would be ideal if the Nav Menu element had an option to display "Branding" as one of its options, the sub-options being e.g (Image/Logo | Text or/and Icon)

**Describe alternatives you've considered**
Currently as an alternative, I am using an Icon List element with one item, icon set to map-o, text set to Navigation. Background color 787878, color FFFFFF. All that placed above a Nav Menu element. The pain starts when switching to Medium and Small screen, Nav Menu must collapse, which places hamburger just below the Icon List element instead of being inline with it. To fix that I decreased the top margin by -75px. It's all a pain and an inconvenience really.

**Additional context**

**Comment by bainternet** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @AppGrind,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
