### ISSUE TITLE
Style tabs eg for pricing table use

### ISSUE THREAD

**Issue by drewclifton** [elementor/elementor#5654]
Note: this could also be a pricing table feature itself... as in my case the use case is very specific to pricing tables... however some better styling options of the tabs would also be very nice, so one could come at this from either side.

I would like to be able to style tabs in the way very commonly found on pricing tables, ie to switch between pricing period plans (eg, monthly, quarterly, annually).

Currently the tabs are stuck on the left side of the page, and are not visually conducive to such uses... Eg the pricing table use case would require them to be centered, and appear more like links, buttons, switches, etc. (there could be different styles).

If this were in the Pricing Tables widget, then a user could be allowed to either create different versions for each "tab", and/or just update specific fields per tab (eg, the Price and a Discount value being the most relevant).

Thanks. This is my attempt at describing the use case and some ideas...

**Comment by shilo-ey** [comment]
Hi @drewclifton 
Thanks for your feedback.

The power of Elementor lets you create any layout you wish for.

The widget you are describing is very particular, therefore needs to be designed with our other widgets and styling settings.

Thanks!
