### ISSUE TITLE
[Feature request] Icon List Widget – ACF support

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#5657]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
An easy way to align ACF custom fields by each other.

**Describe the solution you'd like**
The same solution available for the 'Text Widget'. A 'Dynamic' option for the Icon List Widget.

![greenshot 2018-09-03 16 51 18](https://user-images.githubusercontent.com/17693529/45000235-9a657e80-af99-11e8-8350-3e8328e964b9.png)

The issue with the 'Text Widget' is the different spacing gaps when the number of characters changes from one ACF field to another.
![greenshot 2018-09-03 16 52 43](https://user-images.githubusercontent.com/17693529/45000287-ff20d900-af99-11e8-9fe7-e14c712ebf1f.png)

**Comment by servitiumpl** [comment]
+1

**Comment by HQRaja** [comment]
+1. This can help design versatile layouts populating dynamic content from custom field values while assigning an icon to them as their label.

**Comment by tbrady85** [comment]
+1. Currently running into the issue also.  I'm using pods for custom post and field types and need to be able to populate my icon list with dynamic content.

**Comment by tonyosuna** [comment]
+1. I don't know why Elementor team doesn't implement this feature.

**Comment by tobiasfeistmantl** [comment]
+1

**Comment by erfan-ilyas** [comment]
I just want to add that please also add the Dynamic Link option as well.

![image](https://user-images.githubusercontent.com/1281946/52692568-0e16a900-2f86-11e9-8a8d-b7f6447920f7.png)


+2

**Comment by kaelhoel** [comment]
This would be an amazing feature to have. I need it for three of my current WooCommerce + Elementor projects.

**Comment by shilo-ey** [comment]
Hi,

This feature has been added since Elementor v2.5 (inline/custom width)

[Learn how to use it here](https://docs.elementor.com/article/519-how-to-place-widgets-side-by-side-in-the-same-column)

Thanks!

**Comment by tbrady85** [comment]
@shilo-ey  I think you closed the wrong thread. This thread is about adding a feature to dynamically populate the Icon List widget. The tutorial you posted is how to list widgets inline of each other.

**Comment by shilo-ey** [comment]
Hi @tbrady85 

For that you have the issue #5979 

This issue was about:


> **What problem is your feature request going to solve? Please describe.**
> An easy way to align ACF custom fields by each other.

Thanks

**Comment by tbrady85** [comment]
@shilo-ey  Ah, I misread. My apologies.
