### ISSUE TITLE
[Feature Request] Dynamic field selection if field type is checkbox (Toolset)

### ISSUE THREAD

**Issue by MarioCipo** [elementor/elementor#5665]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Using Toolset with field type 'checkbox' with multiple values. Want to show this dynamic field within a widget. Currently it is not possible to select a key if toolset field type is a checkbox.

**Describe the solution you'd like**
For a deeper integraton it should be possible to select this field type.

**Describe alternatives you've considered**
Shortcodes provided from toolset also don´t work in widgets with dynamic tags.

**Additional context**
Would be nice to have an deeper integration with toolset in general.

**Comment by servitiumpl** [comment]
+1
Please better integration with the Toolset
The current integration has been poorly performed

More information:
https://toolset.com/2018/07/toolset-elementor-integration/#comment-357899
"The rest of the issues are “how Elementor team chose to implement it”. We also wanted to see a tighter integration, where Elementor respects the output options of different fields. Eventually, Elementor treats all fields as “text”, which limits the possibilities significantly. There’s also no integration between Elementor and Toolset’s taxonomy. This causes additional issues to clients."

**Comment by Maroin** [comment]
There is also the "Ratio" custom field which need to be added, that would be great !

**Comment by Dental-SW-Support** [comment]
Would be great if this exist.... at least it is a standard in every other Ticketsystem i know ^^.

**Comment by arielk** [comment]
Due to the fact that [Toolset stops releasing new features](https://toolset.com/2022/06/whats-next-for-toolset/), we are currently suspending all requests for integration with Toolset, if the status will change in the future we can reopen it.

Thanks for your feedback!
