### ISSUE TITLE
Remove/Control Formatting When Pasting Text to Inline Text Editor from Other Sources

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#5671]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Well, title says it quite clearly. Sometimes it's fine, but mostly it isn't (e.g. when copying from Word). 

The problem is present even when copying a text from other widgets on the page. See the screenshot below, where I've copied the heading "Mobilní aplikace" from the lower column to the intro text.

![obrazek](https://user-images.githubusercontent.com/5634870/45087164-44ade500-b105-11e8-9a54-fa1d9a472a5e.png)

I find this problem quite a huge one, it causes me a huge amount of extra work - my clietnts keep calling me: "Please help, my text is too small/too big, I don't know what I've done wrong, I can't change it anymore."

**Describe the solution you'd like**
I'd like to have an option to strip pasted formating by default or to have some level of customisation, which atributes to strip and which to preserve. Could be done by some kind of filter or so, could be a developer-oriented solution.

It would be superb, if I could do something similar as I do for sanitizing pasted text in TinyMCE Editor - see the article here: https://jonathannicol.com/blog/2015/02/19/clean-pasted-text-in-wordpress/

**Describe alternatives you've considered**
I know, there is an option to use CTRL+Shift+V, but this is something, that is hard to explain to non-techie customers.

I could also paste the text to TinyMCE box in the left panel (where I can sanitize it), but, well, why to have the inline editor then...

**Additional context**
There has been 2 other issues already opened on this topic (one by me) - #2930 and #3453. Both were closed, but not solved (at least not for me).

**Comment by rami-elementor** [comment]
Hi @black-eye ,

I'm not sure it's an Elementor issue.

You have two options to paste content from your clipboard:

- **Paste** (CTRL + V)
- **Paste as plain text** (CTRL + SHIFT + V)

The second option should solve your problem, it strips all the HTML tags.
