### ISSUE TITLE
Margin / Padding option for pagination in posts widget (elementor pro)

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#5682]
There is no option to control padding / margin of pagination , we just can increase spacing between numbers!
I know its possible to add custom CSS, but need controllers there I think.

![image](https://user-images.githubusercontent.com/2544046/45145645-d5e68f80-b1c9-11e8-812c-7eac84c4a812.png)

**Comment by srcek** [comment]
As a workaround, I added 6em Line-Height under Typography to add some spacing to Pagination.

**Comment by Alok-S-Sharma** [comment]
I landed here after searching for how to increase the spacing between the posts and the pagination.

I fully agree with @amindiary, there should be an option to allow the users to adjust the spacing.

**Comment by stevehardaway** [comment]
I too am looking for better styling options for pagination. The ability to add padding, border-radius, background and background hover color, etc. Is this coming in a future update?

**Comment by bpstory** [comment]
I too agree that we need to be able to control the spacing between the posts and the pagination. At the moment, it is way too tight.

**Comment by rich73625** [comment]
Yes, I would love to have this option - other blog layout plugins for Elementor have this...
Unfortunately, I still have to use third party blog grid plugins as the Elementor one is still lacking in several ways, and it looks like it's been forgotten about now....

**Comment by Alok-S-Sharma** [comment]
I doubt it is going to happen.

**Comment by srack835** [comment]
This is also a request I have!

**Comment by amindiary** [comment]
> I doubt it is going to happen.

02/2020 Not Happened yet, Have to add line-height to achieve this :|

**Comment by dwolke** [comment]
I was worried I was the only one with this problem. Any news on when this problem will be fixed? Seems like it's been going on for a while.

BTW: #6260 targets the same problem.

**Comment by amindiary** [comment]
> I was worried I was the only one with this problem. Any news on when this problem will be fixed? Seems like it's been going on for a while.
> 
> BTW: #6260 targets the same problem.

They keep ignoring these issues! it's about 18 months passed and that not solved yet, however it's very easy for Elementor team to add 1 padding input

**Comment by bainternet** [comment]
@amindiary 

thanks, should be implemented soon

**Comment by Alok-S-Sharma** [comment]
Finally…

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.10

Feel free to update

Thanks!
