### ISSUE TITLE
Add all link target options to Link Options for all widgets/elements

### ISSUE THREAD

**Issue by collindavis** [elementor/elementor#5716]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

This feature will allow me to choose more link target options for all links I assign in Elementor.

**Describe the solution you'd like**

Add options for all link targets: 
_parent
_self
_top

Details: https://www.w3schools.com/tags/att_link_target.asp

**Describe alternatives you've considered**

Custom coding a plugin/widget to extend this function of Elementor. This should built in and is fairly easy to implement.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9

Feel free to update

Thanks!
