### ISSUE TITLE
[Feature Request] Add shadow-option for lists to portfolio widget

### ISSUE THREAD

**Issue by tobiashieb** [elementor/elementor#5768]
I would love to be able to set an shadow for lists (boxes) in the portfolio widget. 

<img width="299" alt="bildschirmfoto 2018-09-19 um 15 22 14" src="https://user-images.githubusercontent.com/3649698/45755908-dc402700-bc1f-11e8-8945-59f44a2750a4.png">

**Comment by thehervy** [comment]
Please! This is really must for a clean modern design.
I was used to (and it is really handy) set shadow for the posts in the portfolio widget and ALSO set the shadow when hover!

To be honest I am surprised that this is not in the elementor, since it has sooo many cool small features.

**Comment by shilo-ey** [comment]
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
