### ISSUE TITLE
Syntax Highlighter 

### ISSUE THREAD

**Issue by kghalieh** [elementor/elementor#5815]
I tried to use code highlighter plugin with Elementor but it seems that they are incompatible 
so I wonder if you can make a new block where we can post different codes in WordPress posts and pages or solve the compatibility issue with plugins like crayon

**Comment by ipokkel** [comment]
+1

@kghalieh  I'm using a dirty workaround to achieve this, maybe you could try this in the meanwhile 

- I've installed the prismatic plugin for syntax highlighting
- Added a tag "code" to any post where code snippets are included
- Using Astra Pro's hooks I've targeted all singulars containing the tag "code" and added the prismatic css in the header and js in the footer

The drawback with this workaround is that when you create a post containing <pre><code></code></pre> using the default WP editor and not Elementor the prismatic js & css gets loaded twice, adding to page weight.

Alternatively if you add code snippets you can load the necessary css and js files through using the elementor html widget.

**Comment by kghalieh** [comment]
I am not familiar with css, so I tried to do that using Notepad++ to export to html
but:
1 -  The HTML block is not responsive (maybe because of the exported code) 
2-   I need the line numbers to be there so I tried to have two blocks next to each other (in columns) so that one has line numbers the other has the code. But the issue is they overlapped because they are not responsive. 

Do you recommend any tool to convert my coed to nicely formatted HTML?

check this sample http://eblog.elektrojo.com/17486-2/ to see what I got

**Comment by Jammox** [comment]
I found that SyntaxHighlighter shortcodes did not work in a Shortcode element, probably because of the dual shortcode (tag) like structure e.g.

[sourcecode language="javascript"]
{
  "hello": "world"
}
[/sourcecode]

however they do work if you simply put them in a Text Editor element instead.  Hope this helps :)

**Comment by onetrev** [comment]
Not sure that solution works in all cases. But what Elementor really needs is an **_actual_** "Code" widget, like what Gutenberg has. The Gutenberg "Code" block enables you to simply insert code that displays exactly as is on the front end. That way you can type something like <?php blarg(); ?> and that's what you see on the front end, but wrapped in a `<code>` tag.

Instead the current Elementor "Code" widget really is like the Gutenberg HTML widget, and it's only is for parsing HTML / JS code, not for _displaying_ code.

**Comment by SlaggyWolfie** [comment]
+1 to everything already said here.

**Comment by JackDo283** [comment]
+1 
Elementor needs a "Code" widget. I can't find any syntax highlighter plug-in to work properly with elementor.

**Comment by JusticeBringer** [comment]
Elementor should have a Syntax highlighter or, as said, a "Code" widget or compatibility with syntax highlighting plugins.

**Comment by ag-skyler** [comment]
+1
This would be nice.

**Comment by JusticeBringer** [comment]
Just found out a cool solution.

Check the answer at this link:
https://wordpress.org/support/topic/syntax-highlighting-best-approach/

**Comment by zpunry** [comment]
Hi all!

Any updates on this request? I would also like to add code snippets on my blog.

**Comment by anelad** [comment]
C'mon guys any solutions?

**Comment by turkmuhendisnet** [comment]
Elementor syntax highlighter problem is solved. The solution can be found at this link.
https://turkmuhendis.net/yayinlar/elementor-syntax-highlighter-problemi/

**Comment by anelad** [comment]
@turkmuhendisnet This is a bit of workaround rather than a solution. I still prefer using Prismatic but thanks, it can save lives while waiting for a solution. But I think you should add an English translation to your article since some foreign friends might want to take your path.

**Comment by Code-Bear** [comment]
I agree I would love to see this feature added. My site and a client of mine that has two sites all need a syntax highlighter for code blocks. Not sure how best Elementor should handle this since it isn't exactly all that common for every use case but if we were able to use some of the syntax highlighters with Elementor it would make it so much easier. I don't want to use Gutenberg but I am forced to for posts/pages that have code examples.

**Comment by turkmuhendisnet** [comment]
@anelad I've tried using plugins before, but I think this is the best method.
You're right about the English translation, but you didn't have enough time.

**Comment by tiagomatosweb** [comment]
+1
Did anybody have solution on this.

**Comment by ChrisHarrold** [comment]
+1
I will pile on since squeaky wheels get oil. It is kind of silly that something as powerful as Elementor is missing this incredibly basic feature.

**Comment by mrclrchtr** [comment]
+1 
I really need a solution for my technical blog. (Pro Version)

**Comment by Spaghz** [comment]
+1
Also need a code block for my blog, would be a great addition!

**Comment by Coder84619** [comment]
I need this on my blog ASAP as well.

**Comment by Faremir** [comment]
+1 
Would be greatly appreciated.

**Comment by zhuangzi926** [comment]
+1
a syntex highter would be of great help to tech bloggers

**Comment by DofusCL** [comment]
+ 1 
Come on :)

**Comment by pajtai** [comment]
+100

**Comment by fastpenguin91** [comment]
Elementor obviously doesn't care. I'll look for alternatives to Elementor if I can't get it to work.

**Comment by codetutorde** [comment]
+1
This block would be very nice

**Comment by pajtai** [comment]
I created a simple syntax highlighter widget you can install as a plugin:

https://wordpress.org/plugins/syntax-highlighter-for-elementor/

It uses PrismJS for the highlighting.

**Comment by A-Kiwams** [comment]
Your plugin is working. How do you plan maintaining it @pajtai

**Comment by danielmacuare** [comment]
This is definitely needed!! I would have hoped this comes as a widget in Elementor instead of having to install yet another WP plugin.

**Comment by etherhasan** [comment]
Same with me , it's 2020 and still I am facing the same problem... the most popular syntaxt highlighter isn't compatible with elementor . Elementor must include this in their widget instead of using another 3rd party plugin.., is there anyone from elementor developer team ?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!

**Comment by mrclrchtr** [comment]
Really? 😳

**Comment by ag-skyler** [comment]
Yep. https://elementor.com/widgets/code-highlight-widget/


















( https://ardentgrowth.com/ )









[image: facebook] ( https://www.facebook.com/beingskylerreeves )




[image: twitter] ( https://twitter.com/being_skyler )




[image: linkedin] ( https://www.linkedin.com/in/skylerreeves/ )




[image: instagram] ( https://www.instagram.com/beingskylerreeves/ )

















Skyler Reeves
Founder | Ardent Growth





















( tel:+12702525899 )




(270) 252-5899 ( tel:+12702525899 )






( skyler@ardentgrowth.com )




skyler@ardentgrowth.com ( skyler@ardentgrowth.com )











ardentgrowth.com











Book a Meeting ( https://meetings.hubspot.com/beingskyler/discovery )
















On February 16, 2021 at 2:00 PM, Marcel Richter (notifications@github.com) wrote:
Really? 😳
