### ISSUE TITLE
✔️ 🚀 Feature Request: Video background on column, same as section element

### ISSUE THREAD

**Issue by temsool** [elementor/elementor#5826]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Why we can't set video background on columns same as sections?
I had to put a section widget into column I want to be able to put video background on it so it fills the column+space to fill it.

![image](https://user-images.githubusercontent.com/2544046/46233340-de6e5800-c37a-11e8-9d56-053e2d04f18c.png)

![image](https://user-images.githubusercontent.com/2544046/46233358-ec23dd80-c37a-11e8-94ce-3a564b1c226e.png)

**Comment by silvioghedin** [comment]
+1

**Comment by marcelplanb** [comment]
Would love to have the option to add a video background for a column.

**Comment by absym** [comment]
+1

**Comment by portrayaloflife** [comment]
+1

**Comment by bentalgad** [comment]
+1 What? Why don't you have this option?

**Comment by kskonovalov** [comment]
+1 obviously

**Comment by nicmare** [comment]
but why when you can place an inner section with one column into the target column. then you are able to insert a video in the inner section settings

**Comment by nicholaszein** [comment]
Hello guys!

We have great news! 🙌 

### 📢 We're happy to announce that you can now use the <ins>stable</ins> Flexbox Container experiment introduced with Elementor **v3.8**, and add as many child-container (columns) with video backgrounds as you like! 🥳 

✔️ We invite everyone to update their plugin to the new version and activate the Flexbox Container experiment to enjoy the power of CSS Flexbox!

Cheers 🥂
