### ISSUE TITLE
⛔ 🚀 Feature Request: Posts Widget - Have posts open in modal instead of another page.

### ISSUE THREAD

**Issue by RAOEUS** [elementor/elementor#5884]
Hey there Pojo!

I have a client that actually specifically requested this feature.  They would like the posts widget to open into a modal instead of opening on a separate page. I couldn't think of any other way to keep posts opening as modals while still dynamically showing up on the front end like your posts widget does.  

I found a method to open posts in modals [here](https://allurewebsolutions.com/open-wordpress-post-modal-without-plugin).

Let me know if this is a possibility for the future!  Thanks!

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nicholaszein** [comment]
Hello @RAOEUS,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
