### ISSUE TITLE
Several variable products on the same page

### ISSUE THREAD

**Issue by Javiazpe** [elementor/elementor#5918]
On the widget where I can put several products, Elementor fix for each product 3 info: pic name and price. It would be better if the user could modify these parameters (maybe in one product you don´t want to put the price, or, you want to add the description or the categories). For this reason I think that probably the best solution is, everytime I add a Widget, have an option to choose the product on which the widget is related -as now I can only introduce a group of products and set a query.

My personal request is because I want to create a grouped product as follows:

1st Raw (divided in two columns): picture of the set and description of the set.
2nd Raw(divided on three columns): names of the three products that compound the set.
3rd Raw(divided on three columns): pictures of the three products that compound the set.

Also would be great to choose on the same page the variable attributes of the product.

I received three ´no´ from Mr. Andri so I hope you can turn into Yes soon to make Elementor more flexible.

<<
> About this way, could you tell me how can I add description of the products or delete one price?
Unfortunately, this is not possible. 
> Also, as they are variable products, I would like to choose the possible variances on the same page, how could I do that?
Unfortunately, this is not possible. 
> Could be possible for me to put three single products on three single columns and choose on each column the different options of each product?
Unfortunately, this is not possible. 
>>

Thanks in advance

**Comment by lior-sh** [comment]
Hi @Javiazpe,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
