### ISSUE TITLE
Lightbox bug

### ISSUE THREAD

**Issue by lucafagherazzi** [elementor/elementor#5949]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I encountered a problem with lightbox in tablet devices and smartphones with vertical orientation: the enlarged image comes out from the edges of the screen. In the desktop and in devices with landscape orientation, it works correctly.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Elementor Hello Theme
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.2.8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 30M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8

	WP Multisite: No
	Max Upload Size: 30 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Debug Mode: Inactive

	Elementor
		Version: 2.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.10
		Author: Elementor.com

</details>

![01](https://user-images.githubusercontent.com/40598133/47256609-62e85e00-d483-11e8-950f-5b40fc74ce65.jpg)
![02](https://user-images.githubusercontent.com/40598133/47256615-6d0a5c80-d483-11e8-9936-239b4771f64b.jpg)
![03](https://user-images.githubusercontent.com/40598133/47256617-71cf1080-d483-11e8-9f59-ab30291d19c5.jpg)
![04](https://user-images.githubusercontent.com/40598133/47256621-74316a80-d483-11e8-8d45-987d691e4df5.jpg)

**Comment by lucafagherazzi** [comment]
I have found that the problem occurs with Elementor Hello Theme and not with Wordpress Twenty Seventeen. But I have an entire site based on Elementor Hello Theme and I would not like to replace it because of some differences. The attached screens refer to two sites both with Elementor 2.2.6 and Elementor Pro 2.1.11.

![02](https://user-images.githubusercontent.com/40598133/47339599-ff854880-d69b-11e8-81c8-b73ea9478061.jpg)


![05](https://user-images.githubusercontent.com/40598133/47339604-057b2980-d69c-11e8-8a2f-8911108a035e.jpg)

Thanks.

**Comment by arielk** [comment]
Solved: https://github.com/elementor/hello-elementor-theme/pull/30
