### ISSUE TITLE
⛔ 🔗 🚀 Feature Request: Nav Menu Description Field (Duplicate of #3275)

### ISSUE THREAD

**Issue by Pagester** [elementor/elementor#5950]
Currently there is no option to display the "Description" field within the Nav menu.

When you set a menu item description it does not display in the Nav Menu widget when using PRO. 

I would like to see an option to enable/disable the visibility of the description field for Main Menu items and Drop-down menu items with a styling field to set font size/colour/padding etc.

**Comment by bainternet** [comment]
I merged this issue with  #3275
, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by weboost-fr** [comment]
Hi, 

I don't see any reference to menu description field in #3275 

Any news on this?

**Comment by developerabdan** [comment]
pls i need this description menu to be showed in navigation menu like this
![image](https://user-images.githubusercontent.com/42459820/183257609-f31f1bb6-936e-4eee-ba48-90af6e66bc3d.png)

**Comment by nicholaszein** [comment]
Hello there,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
