### ISSUE TITLE
Add dynamic tag to counter / dynamic number

### ISSUE THREAD

**Issue by mredodos** [elementor/elementor#5952]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

it would be interesting to increase the dynamic fields, above all in some wiodget like the counter and to link them to the numeric fields so that the number of starts is automatically loaded.

it would also be interesting to improve the acquisition of data between the fields in relation to each other so as to be able to retrieve the data of a field related to the post for which the theme is being created.

**Comment by kaskad88** [comment]
+1

**Comment by shilo-ey** [comment]
Depends on implementing Dynamic capabilities to number control.

**Comment by stevewoody82** [comment]
+1 for dynamic content in numbers. This would be helpful for #7716 for me thanks.

**Comment by stevewoody82** [comment]
To add to this - When using the function.php code in the other ticket it messes up the numbers.

0 = 1
1 = 2
2 = 3 in terms of the rating.

It does pull dynamic content through but you have to use 0 1 2 3 4 to get the right rating.

**Comment by taropaa** [comment]
+1 for dynamic content in numbers

**Comment by MPHood** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by rdytogokev** [comment]
+1

**Comment by jess8bit** [comment]
+1 pleeeease

**Comment by andrewkirkcaldy** [comment]
+1 Definitely needs this

**Comment by heyfletch** [comment]
+1 would love to add this cool styling to my ACF data

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by mredodos** [comment]
can you add same features to count down timer with dynamic data or dynamic number ?

**Comment by bombarda-rpd** [comment]
Hello! is it possible to create a repeater field with ACF to show a progress bar?
I need to create a portfolio and in each project I need to change the values.
Thanks

**Comment by mielenzio** [comment]
+1
