### ISSUE TITLE
Commerce Product Carousel

### ISSUE THREAD

**Issue by tmhopper** [elementor/elementor#5956]
Hi,

This is my first feature request and new to github so please if there is anything i need to change or ways to improve my request in the future let me know

The following request is for an addon to the commerce section. It would be a widget which allows for creating a PRODUCT CAROUSEL. Example in link below 

Example
https://aazztech.com/demos/plugins/woocommerce-product-carousel-slider/

**Comment by bainternet** [comment]
Thanks for the feedback,
Next time, please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment]
Related #4440

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/4490 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Carousel widget released with Elementor Pro v3.11.0! 🥳 

With the new Loop Carousel widget, you can customize your post listings with custom templates (including WooCommerce Products)! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Carousel layout, design, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-carousel/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
