### ISSUE TITLE
🔗 🚀 Feature Request: Toggle Product Grid & List View (Duplicate of #4440)

### ISSUE THREAD

**Issue by tmhopper** [elementor/elementor#5980]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As a ecommerce developer I consistently require the need to set the products archive page into a LIST view opposed to the standard GRID view. This would save hours upon hours of time find and implementing a plugin which does not crash or cause bugs. This will also allow for customers to easiy search through hundreds or thousands of products and quickly add them to cart with the quantity they would like. Especially for Wholesale companies where the customer frequently purchases the same product and does not need to go to the SINGLE PRODUCT page

**Describe the solution you'd like**
Would like to have the ability to 
1. create a ARCHIVE PRODUCT "LIST" VIEW with
2. ability to toggle between GRID & LIST view and
3. customize the layout such as 
3. adding a Quantity Field and more

**Describe alternatives you've considered**
Have tried using other plugins, only to find a lot of times they have bugs or conflicts, especially with updates to WooCommerce and other plugins

**Additional context**
Eample 1 
a GIF of the LIST and how it would function
![wholesale order form](https://user-images.githubusercontent.com/43484319/47444917-74c04e80-d76c-11e8-8d15-20138c3b5b2b.gif)

Example 2 
Large static Screenshot of a PRODUCT LIST VIEW with several fields to expedite the ordering process. The list view in the screenshot lacks the ability to switch between grid and list
3rd Product down, shows the selectable fields for products with VARIATIONS 
<img width="1076" alt="screen shot 2018-10-24 at 9 14 11 am" src="https://user-images.githubusercontent.com/43484319/47445181-34ad9b80-d76d-11e8-8ae9-e89433d4542d.png">

**Comment by bainternet** [comment]
This should be possible once we implement #4440 

so follow that.

**Comment by tmhopper** [comment]
Thank you for your response. I read through #4440 and this seems to be mainly related to Posts and not Products. Additionally, on the surface, it appears to be a different request than what I am requesting

This request is directly related to Products and the ability to create a TABLE GRID. There was mention of a Archive loop but nothing specific

Would we instead be able to keep this open, as adding this very specific style of PRODUCT VIEW feature set would greatly enhance every developers ability to provide a highly functional feature for their customers? This style of product view greatly increases sales through providing the customer a highly productive way of shopping and adding product

**Comment by tmhopper** [comment]
@bainternet...would we be able to reopen this as it appears to be different from what you were referencing please?

**Comment by Henry00IS** [comment]
I agree, this issue is different and I would love to have this feature as well.
