### ISSUE TITLE
Feature request: hover styles to still apply to active links

### ISSUE THREAD

**Issue by TheMangoTrain** [elementor/elementor#6071]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When hovering over active links, there's no hover effect or the ability to set one. Currently an active link's style overrides all preceding styles (default and hover), so when a user mouse's over an active link, there's no hover effect.

**Describe the solution you'd like**
I'd like an option for hover styles to apply to active links and/or the ability to define a new hover style for active links.

This kind of feature would obviously open doors for buttons and navigation menus, but also it would give some creative power to other situations, for instance a bunch of thumbnail links with a hover effect (e.g. slight rotation) and the hover effect still applies to the active thumbnail.

**Describe alternatives you've considered**
Trying to coordinate many custom CSS rules with what's going on in Elementor widget styles. It's a pain, especially if making changes and/or trying to use the same rules for other widgets or sections.

**Comment by jazir5** [comment]
+1

**Comment by lior-sh** [comment]
Hi @TheMangoTrain @jazir5 ,

Currently, not in our scope, Elementor helps web creators to simplify their work, but we can’t cover all cases, in this case, you can use Custom CSS / Code.

Thanks!
