### ISSUE TITLE
Allow Excluding of Categories in Post Widget Please!

### ISSUE THREAD

**Issue by drewclifton** [elementor/elementor#6112]
There is an "Exclude" feature in the Posts widget—BUT it apparently doesn't cover categories?

After thinking about it for a bit, I can't think of any post attribute one would more regularly wish to exclude than a category/categories; or even any one "filter" that I would likely want to apply to a query... So the absence of this leaves me scratching my head.

... Unless I'm misunderstanding what the "Exclude" feature does?

Currently as a workaround we are adding every category EXCEPT the one we want to exclude, but this is not an acceptable workflow because if we (or a client) adds a new category, it will need to be manually added to the list. Obviously prone to error/oversight.

Thank you very much for considering adding the ability to exclude categories. :)

**Comment by bainternet** [comment]
@drewclifton 

This is something we are already working on.

**Comment by black-eye** [comment]
+1

**Comment by arielk** [comment]
This issue has been resolved in the past!

Thanks!
