### ISSUE TITLE
Aweber Integration to Elementor

### ISSUE THREAD

**Issue by rainx10** [elementor/elementor#6128]
Is there any way we can integrate Aweber email auto responder service to Elementor or have it in the future?

Thank be great.

**Comment by angelbazan** [comment]
Hi guys, please join Aweber with Elementor please.

**Comment by collizo4sky** [comment]
You could use MailOptin to connect Elementor form to AWeber in the mean time. https://mailoptin.io/article/elementor-form-integration/

And it's free => https://wordpress.org/plugins/mailoptin/

**Comment by PalanceH** [comment]
Hello, can someone comment on when Aweber integration with Elementor will happen?  I paid an additional $279 for mailopi plugin for unlimited websites ... cheaper for me to pay for this level.  It would increase Elementor's value to me to avoid me having to pay for additional functionality (not to mention that 1 less plugin).

**Comment by arielk** [comment]
AWeber just released built-in integration with Elementor Pro, please read more here: https://elementor.com/blog/aweber/

Thanks for your feedback!

**Comment by kevinlampron916** [comment]
The Aweber plugin doesn't work for Elementor and I can see why that plugin has very low reviews. I just activated it today. It shows on the dashboard and allows me to set it up and add it to my widgets area, but will not allow me to use in the elementor elements area. There is no option for aweber when activated.
