### ISSUE TITLE
SVG display bug after update

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#6136]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

After updating to the newest version of Elementor every SVG image is displaying incorectly.

It's because the new version of Elementor started to apply this strange CSS to all SVG images:

`.elementor-widget-image .elementor-image>a img[src$=".svg"], .elementor-widget-image .elementor-image figure>a img[src$=".svg"] { width: 48px; }`

It's happening on every one of my clients websites after the update. Is overrides the width of every SVG image and makes it 48px wide. Why is this code there? Makes no sense.
____

Similar problems with updates are a major pain. Elementor is great but it's super frustrating that after any major update something always breaks. Imagine having 50 clients and you have to fix every single website. If you build something with Elementor you need it to work and stay the same even after many updates.  :-/

**Comment by Darthmaul** [comment]
+1 On this update. Override things via !important on module CSS for width but still very frustrating. Wondering what the justification is here?

**Comment by Darthmaul** [comment]
It's in relation to this issue according to the official changelog: https://github.com/pojome/elementor/issues/5987

**Comment by JoeDarko** [comment]
Ok, so they created a much bigger problem to solve some edge case.

**Comment by yaniv691** [comment]
+1 Who decided on a default of 48px? Why not width: 100% as default? Like @JoeDarko, I have to go and fix quite a few websites because of this.

And if we're on the subject of broken images, why are images suddenly wrapped with a figure tag?

**Comment by Darthmaul** [comment]
While setting it to an arbitrary size of 48px is a poor choice, I agree, I don't think 100% would have fixed the original targeted issue. I'm pretty sure SVG has to have a pixel value(or a container setup that allows it to be 100% of that), thus why just blanketing it to 100% wouldn't have done a whole lot.

Please correct me if I am wrong in this assumption!

**Comment by Darthmaul** [comment]
Yes, but this is a very case-by-case interpretation. In quick testing a similar fix did not work for me, but setting it to actual pixel values had an effect. To say that 100% width would fix everything is too sweeping due to the setup required for this behavior to work properly.

**Comment by JoeDarko** [comment]
Any updates? This is really bad.

**Comment by black-eye** [comment]
Yes please, put it back as it was before, until you'll find a less disruptive solution. Untill then, I'm unable to update my websites.

Not sure what the original issue was, but this one seems to be much bigger. C'mon - all the SVG pictures all over the web are 48px wide now!

**Comment by black-eye** [comment]
Just updated another website and to my surprise, the svg icons were fine there. After some investigation I realized, that the rule applies only to images wrapped in the links. This can be seen in @JoeDarko's CSS excerpt, but strange enough it seems there is no similar rule for a bare img there. 

I'd be really interested what's the real purpose of this whole thing and what was the original issue. Maybe we could help here.

**Comment by Darthmaul** [comment]
It honestly seems like they added this CSS to fix an edge case issue without testing it to see if it would break anything.

**Comment by rfierros** [comment]
Maybe this could give a clue for solving the problem (same explaination as "black-eye"):
If I add a svg image it shows it correctly. But if I add a custom url when clicking then it resizes to a tiny size.
It only affects when we link the image to an url.
It's really critical, and after 2 months there's no answer yet.

**Comment by JoeDarko** [comment]
You can use this CSS to get rid of the problem:

`.elementor-widget-image .elementor-image>a img[src$=".svg"], .elementor-widget-image .elementor-image figure>a img[src$=".svg"] { width: auto !important; }`

I'm getting really fed up with Elementor. They add an arbitrary width to all SVGs with an URL and don't realize, that this is gonna cause trouble to thousands of people? Updating Elementor is a nightmare theese days, because things always break. This shouldn't happen with professional software.

Also no response in 2.5 months. Great job.

**Comment by besweeet** [comment]
@JoeDarko Setting it to auto, at least for me, results in the SVG disappearing completely...

**Comment by JoeDarko** [comment]
@besweeet It probably only works for SVGs that have defined width in their code. So "auto" overrides the arbitrary width set by Elementor and uses the width set in the SVG code. If you have SVG with no width specified, than the "auto" won't work.

**Comment by besweeet** [comment]
@JoeDarko I see. My SVGs were set with the standard WP "full" size. For now, I've set the width to 9999px.

**Comment by mellymine** [comment]
Thank you all for troubleshooting this. I'm brand new to Elementor, sort of trying it out to see if it has potential for my client sites down the road. Initially I was so excited when I researched it. But now that I'm officially trying to learn it, the fact that it took me over an hour to figure out how to add an SVG logo isn't a good sign...

**Comment by Darthmaul** [comment]
> Thank you all for troubleshooting this. I'm brand new to Elementor, sort of trying it out to see if it has potential for my client sites down the road. Initially I was so excited when I researched it. But now that I'm officially trying to learn it, the fact that it took me over an hour to figure out how to add an SVG logo and that I had to use custom CSS for the fix isn't a good sign...

This is just one small issue that is annoying. Overall it's a great product, but some things are annoying sometimes. No product is perfect, and I would argue this still performs better than most solutions on the market.

**Comment by mellymine** [comment]
Thank you for your honest feedback and assessment, that’s exactly what I need to hear right now. 

After adding the logo, I next tried to create a transparent header template. I had to watch a YouTube video and insert custom CSS, and then add more CSS adjustments to fix some stuff with the sticky header when I was done. After all that, it’s not displaying correctly in mobile view for some reason and still needs work. So I’m about 3 hours all-in, and all I’ve got to show for it is a logo and transparent header with mobile problems, haha!

Nothing against CSS, but was hoping that using Elementor would eliminate my having to by about 90%. Not to mention the code editor says that using !important can slow down the page load time, too. 

But, I’m not ready to give up yet. Much of this might be because I’m an Elementor newb and there is a learning curve. The demos I saw looked really great, so perhaps if I can just get past the dang header, things will improve.  I’m coming over from the Goodlayers page builder, which I’ve loved and used for years, but was excited to learn something new. Fingers crossed! 

Also I’m a newb to GitHub, and forums in general, so apologies if I’m commenting incorrectly, not using proper etiquette, or anything else annoying. Thank you!

**Comment by besweeet** [comment]
This continues to be a problem. For now, I'm using the following:

```
.elementor-widget-image .elementor-image>a img[src$=".svg"], .elementor-widget-image .elementor-image figure>a img[src$=".svg"] {
    width: 100%;
}
```

The issue is that, since WP can't detect the normal width of the SVG, 100% isn't truly 100%. Without it, it defaults to 48px wide. If I use `auto !important`, nothing displays whatsoever.

**Comment by bainternet** [comment]
With 2.6.0 you can use an icon with SVG which is displayed inline and you would have control over it.

thanks, everyone.

**Comment by besweeet** [comment]
Early 2020 and the original issue persists.

**Comment by david-dooley** [comment]
Mid 2020 and the original issue is still happening. Does anyone have a fix for using global CSS to specify the exact dimensions of two images. I tried the below but no luck.

`.elementor-widget-image .elementor-image>a img[src="logo 1.svg"], .elementor-widget-image .elementor-image figure>a img[src$="logo 1.svg"] { width: 240px !important; }

.elementor-widget-image .elementor-image>a img[src="logo 2.svg"], .elementor-widget-image .elementor-image figure>a img[src$="logo 2.svg"] { width: 500px !important; }`

**Comment by amyriounis** [comment]
Having a set `width: 48px` default for linked SVG images makes no sense. Please re-open this issue as it is not solved.

Maybe the default widget JS handler can be used to apply the proper width (image's width attr) in case there is no explicit width set from the user?

**Comment by gatlanticus** [comment]
> With 2.6.0 you can use an icon with SVG which is displayed inline and you would have control over it.
> 
> thanks, everyone.

Still a problem in 2022. The icon widget is only useful for square SVGs. If you try to scale a rectangle, it results in big margins to turn it into a square.

**Comment by besweeet** [comment]
2022 and this is _**still**_ a problem...

**Comment by StijnT007** [comment]
Hello , i'm totally new with wordpress and elementor and i don't know if my problem is related to this discussion  but i wanted to add a widget "listitem", i thougt to use a noce svg-icon but when i added the svg-icon. 50% is not any more showed of the page. Also when i click on view page, the word edit with elementor is not visible any more? is this a known issue and easy to resolve?
