### ISSUE TITLE
Ctrl+? shortcut does not work on many keyboard layouts

### ISSUE THREAD

**Issue by tomas-eklund** [elementor/elementor#6145]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The Ctrl+? shortcut does not open the Shortcut Cheatsheet on many (most?) keyboard layouts. 

Unfortunately I don't have a perfect solution to the problem. I would suggest Ctrl+H (as in Help) but maybe that shortcut is reserved by the browser? 

## Steps to reproduce

Press Ctrl+? on a Swedish, Norwegian, Danish, Finnish, German, French, Spanish etc... keyboard and you will NOT be presented with the Keyboard Cheatsheet, as promised. 

Pressing Ctrl+* on a Swedish keyboard will, however, display the Keyboard Cheatsheet.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Personally I'm on a Swedish keyboard layout. The "?" key is situated at the topmost row of the keyboard, just to the right of the number 0 (zero). Actually, you have to press Shift+? to get the "?" character. The unshifted character on the same key is "+". So pressing Ctrl+? actually just zooms the window in most browsers. Pressing Ctrl+Shift+? does the same thing.

The other Scandinavian keyboard layouts are very similar to the Swedish. By doing a quick Google Image search on different keyboard layouts, I am assuming that French and German keyboard users will experience the same problem and a Spanish commenter on the [blog](https://elementor.com/blog/introducing-finder/#comment-8059) just confirmed that he has the same problem.

**Comment by Matherone** [comment]
I can replicate this problem - the keyboard shortcut for displaying the Elementor shortcut cheatsheet does not work here, just like described above. Some other shortcuts, however, like displaying Finder, do work.

I am using a keyboard with a standard Nordic layout. This keyboard layout is used by about 27 million people. This problem is possibly affecting about 100 million German-speaking individuals as well. So this may be something of what they call a "non-starter".

Please make all Elementor shortcuts work for us Europeans.

**Comment by grrog** [comment]
+1

**Comment by Gamewalker** [comment]
Same problem here, cant find the related code either

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!

**Comment by tomas-eklund** [comment]
How did you resolve it?

**Comment by creativemouse** [comment]
I'm sorry, this issue has not been resolved. In fact, I have lost the ability to perform several shortcut items for Elementor including this one and I'm in the USA. I can't retrieve the Hotkeys using Ctrl + ?, I can't exit using the ESC, the only thing that does work is the shortcuts themselves if I can remember them. So, I'm going to make my own cheat sheet for that and paste it on my desk.

**Comment by Soulgear99** [comment]
Not working for me also for the Shortcut Cheatsheet.

**Comment by clip1492** [comment]
In Firefox with a Spanish Keyboard, the hotkey CMD+? opens "Firefox Support" page when in Elementor.

**Comment by Soulgear99** [comment]
> In Firefox with a Spanish Keyboard, the hotkey CMD+? opens "Firefox Support" page when in Elementor.

Ok, thank you for your advice.

**Comment by clip1492** [comment]
A Tooltip or text behind each link on the menus, will help to avoid depending on the hotkey list, which in fact I’ve never been able to fire on the GUI.

I always had search on google to consult Elementor hotkey list.
