### ISSUE TITLE
Bug: Icon list alignment if 2 lines of text

### ISSUE THREAD

**Issue by CaptainJakethe1st** [elementor/elementor#6179]
Hey, 

I searched for it, there are several issues on this, but the bug is still not fixed. 

The alignment of the icon list widget gets out of line everytime when you write more than 1 line of text but less than 4 (see picture). 

Detailed description: 
- it has to do with the number and length of lines of text 

description of picture: 
for 1: I used the <br> command -> everything works fine, alignment of all list icons is fine
for 2: as soon as text breaks into line 2 the icon and the text will be pushed to the left side (more text means it will be pushed more to the left side)
for 3: as soon as you reach line 4 of text the icon and text is pushed to the maximum left
for 4: for 1 line of text everything works fine

So problem lies in text lines between 2-3 this somehow pushes icon and text to the left... 
![image](https://user-images.githubusercontent.com/41577927/48544480-f4e95800-e8c3-11e8-8953-e5d560cf5d87.png)

How do I fix it?!

Theme: Astra Pro
Plugin: Elementor Pro 
Tried: Everything, disabled all plugins, etc. -> nothing worked

Best
Jakob

**Comment by Netzlichter** [comment]
It happens when you customize the size of the icon. WHen you set a other height than default one this happens. You can check this with browser inspector - deactivate the "width: xx px" of the icon.

Elementor Team. Please fix this!

**Comment by Netzlichter** [comment]
add this to your custom css file:

.elementor-icon-list-icon {
    width: auto !important;
}

**Comment by CaptainJakethe1st** [comment]
@Netzlichter 

Nice, that works fine :-) thx a lot :-)

**Comment by shilo-ey** [comment]
Hi @CaptainJakethe1st 

This issue seems to be fixed in v2.6.0 which will be released soon (including vertical alignment)

Please follow this repo for further information.

Thanks.
