### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Off Canvas Widget (Merged with #21769) - [ED-13937]

### ISSUE THREAD

**Issue by terryhauptza** [elementor/elementor#6225]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
An Off Canvas widget will allow for an off canvas section (with any content inside) that is revealed  from any direction. Would be great for building more customized mobile menus. (Menu Cart widget currently does this)

**Describe the solution you'd like**
A new Off Canvas Pro widget to create slide-in menus/custom content boxes and can display any saved widgets/templates/sections. Off Canvas can be triggered by link, button, image, icon etc..
Off Canvas can be revealed with animations such as slide, reveal, push, slide along, fade etc and from any direction.

**Describe alternatives you've considered**
Essentially the reason for this is to build a better mobile experience where instead of drop down menus you can choose to have it slide from either left or right. Also the ability to change the default hamburger icon to a "user icon" for instance if the menu is member/user specific. These menus could then also be better structured with any content (saved widgets/sections/templates).

**Comment by artconic** [comment]
This will be the BIGGEST move for Elementor. It will be the number one seller, and different from all competitors.

**Comment by jazir5** [comment]
I think this would better be described as mobile menu feature enhancements rather than an off-canvas widget

**Comment by jcmatoskx** [comment]
I achieved this with the Elementor PopUps, however they dont move the content. Maybe there is some CSS that could be inserted on the Popup that would move the website gutter/width? 
I tried adding a margin with CSS to a few elementor row classes and it works except that it also affects the content on the popup as well.

**Comment by philmatt** [comment]
+1

**Comment by desidm** [comment]
Yes please +1. I have to add an extra elementor add-on plugin every time I build a site just to get a decent mobile menu.

**Comment by Aryehhirsc** [comment]
I wish they would implement this already

**Comment by 79ho3ein** [comment]
+1000

**Comment by ahmedzeidan** [comment]
I can see this working on Elementor's main website when they are announcing Black Friday sale in a popup (content is being pushed down)... However, no idea what custom code they are using to achieve this... I would appreciate if the Elementor team would take a look at this and release such a feature...

**Comment by Fjashaw** [comment]
Yessssss please!!

**Comment by raabmar** [comment]
Anyone found a nice workaround for this?

Basically something like this: if popup is shown, add top margin of first section and transition it. If popup is closed, delete top margin.

**Comment by rossclurman** [comment]
+1 

Would love some CSS guidance and/or an Elementor fix!

This may help anyone willing to try a PHP workaround:
https://www.reddit.com/r/elementor/comments/qxs79s/comment/hlbn7g9/?utm_source=share&utm_medium=web2x&context=3

**Comment by tamal-sen** [comment]
+1 Now I need to install a whole new plugin just to achieve this.

**Comment by csarigoz** [comment]
+1 I think this should have been solved until now.

**Comment by ayoubkhan558** [comment]
This featured is shippped, still issue is open?

**Comment by nicholaszein** [comment]
Hi everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.22.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
