### ISSUE TITLE
Add spacing above pagination on Posts widget

### ISSUE THREAD

**Issue by slamdive** [elementor/elementor#6260]
The Posts module does not include any spacing options for above the pagination.
It is almost attached to the bottom of the post cards and requires additional CSS to look correct:

.elementor-pagination {
    padding-top: 40px;
}

**Comment by iugo-robert** [comment]
I would love to see this fixed.

**Comment by ipsq** [comment]
+1, this looks really bad out of the box. Especially with Masonry turned off.

**Comment by pless84** [comment]
Some control of the spacing would be nice also

**Comment by gwashbrook** [comment]
+1

**Comment by avermat** [comment]
Yes, please fix this.

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.10

Feel free to update

Thanks!

**Comment by BackuPs** [comment]
where is this setting in pro as in the latest version it is still missing ! I cant find it. Still have to use the custom css field.
