### ISSUE TITLE
Pods many to many support for elementor

### ISSUE THREAD

**Issue by lexvd** [elementor/elementor#6288]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve?**
I am searching for a way to have a many to many solution for pods. For example, I have a game with reviews from different websites. But those websites also reviewed other games. So I would like to reuse the websites for different reviews of different games.

See below for an example
Game 1
review1 - site1
review2 - site2
review3 - site3

Game 2
review1 - site2
review2 - site3
review3 - site5

**Describe the solution you'd like**
I would like to be able to make use of Elementor so people can fill in the information in pods and that the design can be switched with ease if needed. I would be thinking of a 'many-to-many' loop element where a template can be chosen. This template would be build of all available pods unless you select for which 'pod' it would be used. It would be nice if this is visualized in Elementor.

**Describe alternatives you've considered**
I've considerd to use AE pro with the ACF repeater solution and am following issue https://github.com/pojome/elementor/issues/5979 this would be a great alternative i guess. But I think pods is just better database wise.

**Comment by lior-sh** [comment]
Hi @lexvd,

Currently not supported in Elementor and not in our scope for now.

Thanks.
