### ISSUE TITLE
Toggle and Accordion widgets don't collapse

### ISSUE THREAD

**Issue by collindavis** [elementor/elementor#6289]
The widets for Accordion and Toggle don't work. When clicked (to expand) it collapses then hides and reloads the page. This is occurring with the most recent version of Elementor (2.3.2). I'm using the widget within a LOOP template.

Solution: 

event.preventDefault should be in the level of <a> instead of .elementor-tab-title
(e.g.: .elementor-tab-title > a)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.


> I'm using the widget within a LOOP template.

What is that?

**Comment by collindavis** [comment]
LOOP template is setup via Ele Custom Skin plugin: https://github.com/dudaster/ele-custom-skin

Prerequisites: 
- Elementor 2.3.2

Replicate: 
1. Create LOOP template and add Toggle or Accordion widget.
2. Create new page using Elementor, add Posts List widget, choose Custom Skin > and select LOOP template that contains Toggle or Accordion widget.
3. Preview page and click Toggle or Accordion widget to expand text. Text will show, then hide, then the page will reload.

System Info:
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.36-83.0
	PHP Version: 7.1.17
	PHP Max Input Vars: 3000
	PHP Max Post Size: 55M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://ncs.cartender.co
	Home URL: https://ncs.cartender.co
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: -8
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.2.1
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 4.3.8
		Author: AdminColumns.com

	Admin Columns Pro - Pods
		Version: 1.2
		Author: Admin Columns

	Adminimize
		Version: 1.11.4
		Author: Frank Bültge

	Cartender - Static Pages
		Version: 1.1.4
		Author: Cartender

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Ele Custom Skin
		Version: 1.0.9
		Author: Liviu Duda

	Elementor
		Version: 2.3.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.2.0
		Author: Elementor.com

	Formidable Forms
		Version: 3.04.02
		Author: Strategy11

	Formidable Forms Pro
		Version: 3.04.02
		Author: Strategy11

	GP Premium
		Version: 1.7.5
		Author: Tom Usborne

	LiteSpeed Cache
		Version: 2.7.3
		Author: LiteSpeed Technologies

	MVP | Shortcode
		Version: 1.0.1
		Author: 

	NCS - Cache
		Version: 1.0.2
		Author: Cartender

	NCS - Gateway
		Version: 1.0.3
		Author: Cartender

	NCS - Media
		Version: 1.0.3
		Author: Cartender

	Pods - Custom Content Types and Fields
		Version: 2.7.9
		Author: Pods Framework Team

	Public Post Preview
		Version: 2.8.0
		Author: Dominik Schilling

	ReOrder Post Within Categories
		Version: 1.5.0
		Author: Aurélien Chappard, Aurovrata Venet

	Shortcoder
		Version: 4.1.9
		Author: Aakash Chakravarthy

	WP Custom Login Page Logo
		Version: 1.4.8.3
		Author: Lars Ortlepp

	WP Google Analytics Events Pro
		Version: 2.2.9
		Author: PineWise

	Yoast SEO
		Version: 9.2.1
		Author: Team Yoast

	Yoast SEO: Search index purge
		Version: 1.1.0
		Author: Team Yoast


== Must-Use Plugins ==
	closte-requirements.php
		Version: 
		Author:

**Comment by bainternet** [comment]
The problem is that all Items are printed from a template with the same id's for widgets instead of issuing a unique id for each widget.

should be possible once we implement #4440 

thanks.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Nested Accordion widget released with Elementor v3.15.0! 🥳 

With the new Nested Accordion widget, you can customize the content of each accordion widget with nested elements! 💪 
Drag & Drop widgets to create complex designs, fine-tune your accordion layout, design, interactions, and much more!

Check out the beta announcement here: https://github.com/orgs/elementor/discussions/23010

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
