### ISSUE TITLE
⛔ 🚀 Feature Request: Add Menu as a Source to Sitemap Widget

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#6294]
## Prerequisites
- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I like the new Sitemap Widget, but I'm missing one important (and pretty obvious) source there - native WP Menu.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I've tried to use Elementor Menu Widget, but it didn't work work for me, as it has unwanted responsive behaviour - see #5912.

**Additional context**

**Comment by rami-elementor** [comment]
Hi @XXX,

Thank you for submitting a feature request.

After review, we have decided not to add this to our roadmap for the time being. Please note that you can use the Menu widgets for that.

Please feel free to contact us again with other feature suggestions.

Regards,
