### ISSUE TITLE
Dynamic CSS Classes and IDs.

### ISSUE THREAD

**Issue by Otakumouse** [elementor/elementor#6302]
I super love elementor. Currently working on a page where a user can set a "class/ID name" via ACF field and that will be applied to one of the elementor widgets.

Is it possible to make the class name and id name fields in elementor dynamic (where you get to select a custom field like the other widgets?)

**Comment by bainternet** [comment]
@Otakumouse 

Can you explain the use case better?

**Comment by Otakumouse** [comment]
Hello @bainternet ! I was like wondering if it's possible to maybe use a ACF CUSTOM FIELD value on the class name/id name in elementor?

**Comment by bainternet** [comment]
@Otakumouse 

I understand that but can you explain why? what is the use case?

**Comment by black-eye** [comment]
+1

**Comment by tristanleboss** [comment]
@Otakumouse I think we all do things the same way ;)

**Comment by MPHood** [comment]
Great idea +1

**Comment by affinitycloud** [comment]
I have a very similar use case for this.

Using ACF I have an ID field in a repeater field.

In a different repeater field I have set up custom on page anchor navigation to each separate row of the first repeater, so I need a way to dynamically assign the ID from the first repeater so that my jump links work.

**Comment by papilia** [comment]
+1

**Comment by teolaz** [comment]
+1 for this 

> In a perfect world, every Elementor control should be able to be turned dynamic.

**Comment by Barns-be** [comment]
great idea +1

**Comment by fracii** [comment]
+1

**Comment by bainternet** [comment]
Already available since Elementor 2.5.0

thanks.

**Comment by dainemedia** [comment]
I can see Elementor now has dynamic IDs, which is great. But, is there a way to assign the dynamic ID via an ACF repeater field?

For example, I have a repeater field group and in it, it has a field called ID.

In my AnywherElementor template, I'd like to assign the value of the ID field that is within the repeater to the section ID dynamically.

Is this possible?
