### ISSUE TITLE
Elementor Pro and WP-CLI

### ISSUE THREAD

**Issue by redpik** [elementor/elementor#6311]
Hi,

For automatic deployment, we need to download / install / activate Elementor Pro.

Example with Elementor : 

`wp plugin install elementor --activate`

It works.
We need the same thing with Elementor Pro, for example : 

`elementorpro_zip_file="$(wp plugin path)/elementor-pro.zip"`

get Elementor Pro zip file. Please add this feature :)
`wget -O ${elementorpro_zip_file} "https://my.elementor.com/index.php?p=pro&a=download&k=MY_ELEMENTOR_KEY"`
`wp plugin install ${elementorpro_zip_file} --activate`

remove zip file
`rm ${elementorpro_zip_file}`

add Elementor Pro key
`wp elementor add-key=MY_ELEMENTOR_KEY`

Thank you !

**Comment by bainternet** [comment]
@redpik 	

Thanks for the feedback,
Next time, Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Now, 
You can alreay activate your elementor pro via CLI:

`wp elementor-pro license activate <license-key>`

as for 
>get acf zip file. Please add this feature :)

You probbably mean "get Elementor Pro zip file" and that is a valid feature request that we are thinking about.

**Comment by redpik** [comment]
Hi @bainternet,
Thank you for your answer.
it's OK for Elementor activation :+1:  

But can I download it with WP-CLI, wget or something else ? You are thinking about this feature, right ?

**Comment by cristacheda** [comment]
+ 1

**Comment by edpittol** [comment]
+1

**Comment by dalguji** [comment]
@bainternet 
> You probbably mean "get Elementor Pro zip file" and that is a valid feature request that we are thinking about.

It would be greatly beneficial if we could download the Elementor Pro zip file using WP CLI, similar to what is offered with ACF Pro. Do you have any plans to implement this feature?

`wp plugin install 'https://connect.advancedcustomfields.com/v2/plugins/download?p=pro&k={USER_KEY}'`
