### ISSUE TITLE
Image carousel should be more like media carousel 

### ISSUE THREAD

**Issue by Luxamman** [elementor/elementor#6371]
Once mentioned in https://github.com/pojome/elementor/issues/219

**What problem is your feature request going to solve? Please describe.**
Since the media carousel is much nicer than the image carousel (image carousel still has problems with mixing portrait and landscape, scaling picture, no thumbnails like in media carousel...) I miss having dynamic content in a nice carousel - because the image carousel is not that nice and the media carousel can't handle dynamic content. 

**Describe the solution you'd like**
The best way should be to make the image carousel to look and work more like the media carousel. This includes better scaling of the pictures, handling portrait and landscape better, include the thumbnails like in media carousel and all of the other features included in media carousel. 

**Describe alternatives you've considered**
Or is it a better way to add dynamic content to the media carousel? Is this possible, because it is working very different to other dynamic content inputs. But the image carousel SHOULD really be updated to the much better functionality of the media carousel.

**Comment by bainternet** [comment]
@Luxamman 

So mainly adding dynamic capabilities to media carousel?

**Comment by Luxamman** [comment]
Not necessarily. 

The mechanic of adding media (picture/videos) to the media carousel is much different to the image carousel, so I don't know if this is even possible with dynamic content - but would be great because this mechanic is used on many other places. 

Overall I think the image carousel should have the same great capabilities than the media carousel. Alternative is of course adding dynamic content to the media carousel.

**Comment by saulobraine** [comment]
> 
> 
> @Luxamman
> 
> So mainly adding dynamic capabilities to media carousel?

For me, the media carousel should have the dynamic capability. In this way, we can do amazing single posts/pages and products design.
I'm hoping for this.

**Comment by arielk** [comment]
Unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback

**Comment by thomasbonsirven** [comment]
hello,

II use Elementor and ACF pro, and the layout with the thumbnails below, for the carousel media, is great.

The problem, for me, is that I would like to use a dynamic source for setting up an image portfolio.

So it would be really interesting to set up.

Is it possible, if so how, I'm ready to put your hands in the code!

It is possible to make screenshots to better understand my request!

Thanks in advance

**Comment by torlior** [comment]
I strongly feel for this issue as well - dynamic content in the awesome media carousel is needed!

**Comment by DustinHanke** [comment]
https://github.com/elementor/elementor/issues/10314#issuecomment-631605223

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Carousel was released with Elementor Pro v3.14.0! 🥳 

You can now create Carousels or Slides with custom nested widgets without needing to use shortcodes or other features! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
