### ISSUE TITLE
🔗 🚀 Feature Request: Send Elementor E-Mail Form Attachments as Regular E-Mail Attachments instead of a link that is saved in the ftp server (Duplicate of #4868)

### ISSUE THREAD

**Issue by RUSxDeviL1979** [elementor/elementor#6515]
good day I do not know how to reach you and explain I'm writing this letter for the tenth time ! finally, pay attention to the form of sending a message . the problem is as follows . when attaching the file it went to the hosting path /CLAIFLOWER//uploads / elementor / forms and the files are downloaded to the folder . what is it ? the file should come to the post office and then it turns out the mail comes with a link to the specified file and folder https://claiflower.ru/wp-content/uploads/elementor/forms/5c19d6c2038c7.jpg this is wrong . if we consider the security on the hosting can get malicious files through the submission form . moreover, the hosting where the site is located limit Disk space: 20.0 GB it thus becomes clogged . I bought your elementor for website design and correct work and it turns out the money was spent in vain .
.................................

What about the code is not an option! need to solve this problem. I bought about the version and I suffer with it for a long time and more than once wrote silence only in response. Dear developers, you sell your creation should work out as this product is paid.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bainternet** [comment]
ref #4868

**Comment by nicholaszein** [comment]
Hello there @RUSxDeviL1979!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
