### ISSUE TITLE
Add Custom Shapes Filter Not Working Properly

### ISSUE THREAD

**Issue by sajadk48** [elementor/elementor#6550]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

i have read this :
https://github.com/pojome/elementor/issues/4759

when i use your filter hook ,  shape item name display correct but when i use it i get an error in console about not found svg on this address ( Jquery Error ) :

GET http://localhost/test/wp-content/plugins/elementor/assets/shapes/madona.svg 404 (Not Found)

Code : 
```
define("THEMEURLL", get_template_directory_uri());
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
	$additional_shapes['madona'] = [
		'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
		'has_flip' => true,
		'height_only' => true,
		'path' => THEMEURLL.'/includes/elementor/shapes/', //could be in your theme/child/plugin
	];

	return $additional_shapes;
});
```

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```

last version of Wordpress

last stable version of Elementor

Default Wordpress Theme (and other themes also checked)
</details>

**Comment by mike2410** [comment]
It looks like the path supplied in 'path' only gets applied in the fronted, while the shape has to be available in elementor/assets/shapes, assuming the key supplied for $additional_shapes + '.svg' as the filename.

I got it to work by supplying the full path to my svg-file (incl. filename and .svg-extension), and by copying the .svg into elementor/assets/shapes (which, of course is not ideal.)

**Comment by patrick-wyzorski** [comment]
Hey, does this filter hook work? If so, then is there any clear documentation around how it works.

**Comment by mshihinski** [comment]
The latest merge appears to fix backend issues, but still not seeing the custom shapes being pulled into the frontend. Can anyone else confirm?

add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
    $file = get_stylesheet_directory_uri() . '/svg/polytrontop.svg';
    
	$additional_shapes['polytrontop'] = [
		'title' => _x( 'Polytron Shape 1', 'Shapes', 'elementor' ),
		'has_flip' => false,
		'path' => $file
	];
    
    $file = get_stylesheet_directory_uri() . '/svg/polytronbottom.svg';
    
	$additional_shapes['polytronbottom'] = [
		'title' => _x( 'Polytron Shape 2', 'Shapes', 'elementor' ),
		'has_flip' => false,
		'path' => $file
	];

	return $additional_shapes;
});

**Comment by mshihinski** [comment]
Upon further research. It appears that the backend requires the path parameter (frontend.js) to be a URI and the frontend implementation requires the path parameter to be a filesystem path (shapes.php).

Will probably need either a way to load the svg using the single parameter in both places or an additional parameter to allow passing in both a path and a uri.

**Comment by bainternet** [comment]
Path needs to be a full URL for the svg file for both editor and frontend.

**Comment by mshihinski** [comment]
@bainternet 
> Path needs to be a full URL for the svg file for both editor and frontend.

I am using a full URL and it does not work. 

If I use a filesystem path it shows on the frontend, if I use a URL it only shows in the backend editor.

**Comment by mshihinski** [comment]
The only way a full URL for the svg would work, is if we turn on allow_url_include which is off as default. It is not recommended to have allow_url_include on.

Where the code prints the shape divider in includes/elements/section.php it tries to include it, having a URL here will not work and has security issues.

![image](https://user-images.githubusercontent.com/6787394/53504296-abda9f80-3a7f-11e9-8567-3946e501da03.png)

**Comment by patrick-wyzorski** [comment]
When will this feature/fix be released?

**Comment by davideprevosto** [comment]
I there, I am not able to use this filter.

I'd try:

```
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
    $additional_shapes['myshape'] = [
        'title' => _x( 'My Shape', 'Shapes', 'elementor' ),
        'has_flip' => true,
        'height_only' => true,
        'path' => get_stylesheet_directory_uri() . '/elementor/assets/shapes/myshape.svg',
    ];
    return $additional_shapes;
} );
```

In the backoffice are I am getting a 404 error, 'cause it's searching my svg in the Elementor plugin folder. In frontend nothing appears.

May I ask your further help?

**Comment by mshihinski** [comment]
@davideprevosto you are missing the url parameter. See below.

`add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {

        $uri = get_stylesheet_directory_uri() . '/path/to/file.svg';
        $path = get_stylesheet_directory() . '/path/to/file.svg';
    
	$additional_shapes['polytronbottom'] = [
		'title' => _x( 'Shape Name', 'Shapes', 'elementor' ),
		'has_flip' => true,
                'height_only' => true,
		'url' => $uri,
                'path' => $path
	];

	return $additional_shapes;
});`

**Comment by davideprevosto** [comment]
Thank you @mshihinski 

Now I am able to use it and view it on the frontend. Unfortunately I am getting a 404 in the backoffice area (Elementor search our svg in his folder)

**Comment by mshihinski** [comment]
@davideprevosto is the path parameter pointing to a file system path as shown in my example? 

e.g. get_stylesheet_directory() and not get_stylesheet_directory_uri()

**Comment by davideprevosto** [comment]
```
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {

    $uri = get_stylesheet_directory_uri() . '/elementor/assets/shapes/heartshape.svg';
    $path = get_stylesheet_directory() . '/elementor/assets/shapes/heartshape.svg';

    $additional_shapes['heartshape'] = [
        'title' => _x( 'Heart Shape', 'Shapes', 'elementor' ),
        'has_flip' => true,
        'height_only' => true,
        'url' => $uri,
        'path' => $path
    ];

    return $additional_shapes;
}); 
```

**Comment by tjlabais** [comment]
Thanks for this solution! For those who don't get it, you need to create a child theme and upload your shapes there ;-)

A child theme prevents the stuff you uploaded from being deleted if your main theme needs to update.
