### ISSUE TITLE
Section video background on Edge browser.

### ISSUE THREAD

**Issue by hectorfarahani** [elementor/elementor#6575]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When we set a background video for a section, the video is correctly covering the section in any size of screens in Chrome & Firefox; But in **Edge** browser it can't fill the section in smaller screens (portrait).
I think it is because of setting `max-width` for video, because when I set it to `none` it works correctly.

Here is an image that shows how a video background behaves on a smaller screen.
https://monosnap.com/file/ZurRyt2sqNgSp6N92cpvT9NkG7Armr

The expectation is:
https://monosnap.com/file/ZLRAeIgI8IFX534ConLK4hPtuZ2Xab (Fills section in any size of screen )

## Steps to reproduce
1. Add a section.
2. Add a video link in Section->Styles->Background->Video Link.
3. Publish the page and check it on edge browser.
4. In order to see the issue, you can simply resize browser to decrease width of window.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Tested with WordPress 5.0.2 + Elementor in Twenty-sixteen theme without any other active plugin.
Windows 10 (1809) + Edge browser latest update. (Microsoft Edge 44.17763.1.0)

**Comment by Aviad-Herman** [comment]
Hi I think this issue has been resolved in the latest versions of Elementor and Edge.
Let me know if it's still an issue.
Thanks!
