### ISSUE TITLE
Search and Filter system

### ISSUE THREAD

**Issue by lph2004** [elementor/elementor#6641]
Hello Elementor. You guys do a wonderful work. I have Two suggestions:

1. Can you guys do support  to  Search & System Plugin  from  Designs & Code.  or any other similar   search and filter systrem.  They have in their documentation an explanation how to make it work with Elementor from their end....  I am sure you guys  would do it very better. Also Toolset have some but it is complicated.

2.  Can you also do more  ACF integration for more widgets like slider, iconlist, image box, tabs, testimonials, etc.

Thank you

**Comment by shilo-ey** [comment]
Hi @lph2004 ,

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your actual request:
1. Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
2. We will look into adding Dynamic tags support for these widgets.

Thanks for the feedback.

**Comment by srcek** [comment]
It would be great if existing Search widget would be able to limit search result to certain categories or post types.

**Comment by bainternet** [comment]
I merged this issue with  #5598, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
