### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Front-end Form Posting (Merged with #1686)

### ISSUE THREAD

**Issue by GH-RPDN** [elementor/elementor#6682]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will resolve the workaround issues faced when trying to connect multiple plugins for front-end form posting.

**Describe the solution you'd like**
To create a front-end posting form.
Taking the existing Form Widget and inserting a toggle for this functionality of switching between the two.
The ability to select the post type and to map custom created fields created with ACF/Pods/Toolset etc
Having the Conditional Logic etc created with ACF/Pods/Toolset etc pull through
Retaining the STYLE & ADVANCED tabs as with all Elementor Widgets

**Describe alternatives you've considered**
I have tried:
Advanced Forms - PHP knowledge required to delve into code and attach to webhooks (not UI friendly for non-coders)
WP User Frontend - I was actually successful in getting the fields to map to my ACF fields and then entering the custom created form via the Short Code Widget. But styling would need to be done via the Custom CSS dialog box in the Advanced tab of the Widget. Also, there seems there would not be a need for ACF-pro as WPUF-pro seems to offer exactly what ACF-pro can offer.

**Additional context**
I found this. It may assist in what Im trying to express with this feature request.
https://codecanyon.net/item/acf-front-form-for-elementor-page-builder/21887968?fbclid=IwAR04AeZrgDxGXsjst6u4V4RBkP9GAwrkvES0pIW6Yjoask5uoSG_QuZtVmM

**Comment by Webtica** [comment]
+1 Vote

**Comment by bainternet** [comment]
Currently, this is only possible via [Custom webhook](https://developers.elementor.com/forms-api/).

I merged this issue with  #1686, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by MolyMalon** [comment]
Publicación y edición de formularios personalizados desde el FRONT ~ END con elmentor y ACF

https://es.wordpress.org/plugins/acf-frontend-form-element/
