### ISSUE TITLE
Slider Widget dynamic background image not working

### ISSUE THREAD

**Issue by emascarinas** [elementor/elementor#6683]
Hi

I'm trying to add support for dynamic data (ACF field) for the background image on the Slider Widget. Adding dynamic - active to true works on the Elementor editor/ui but on the frontend the image is not showing. Please see code below. Is there something I need to add? It seems the frontend CSS does not have the background image on the generated post.css.

```
		$repeater->add_control(
			'background_image',
			[
				'label' => _x( 'Image', 'Background Control', 'elementor-pro' ),
				'type' => Controls_Manager::MEDIA,
				'dynamic' => [
					'active' => true,
				],
				'selectors' => [
					'{{WRAPPER}} {{CURRENT_ITEM}} .slick-slide-bg' => 'background-image: url({{URL}})',
				],
			]
		);


```

**Comment by litonarefin** [comment]
Facing same problem. {{CURRENT_ITEM}} not working.

**Comment by riadcitaku** [comment]
I've faced the same issue, try adding the following class in the repeater item.

`elementor-repeater-item-' . $item['_id']`

**Comment by shilo-ey** [comment]
Hi @emascarinas 

Currently, we do not support dynamic background images in a repeater. 

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

Thanks
