### ISSUE TITLE
Form element: "To Email" with dynamic content

### ISSUE THREAD

**Issue by Luxamman** [elementor/elementor#6691]
To include for example a form into an employee single site, created with custom fields (ACF/Pods), the form element should include a dynamic field in the "E-Mail to" field. 

So you can build a single site for employees and include a form, to directly reach out to the selected employee. 

Thanks!

**Comment by Luxamman** [comment]
Any news? Waiting for this improvement :)

**Comment by MPHood** [comment]
+ 1000 I need that!

**Comment by stickypages** [comment]
Not ideal, but in the default value, you can place a shortcode here and it will populate the data. I've done that in the past.

**Comment by MPHood** [comment]
> Not ideal, but in the default value, you can place a shortcode here and it will populate the data. I've done that in the past.

I dont quite get it - How does that work?

**Comment by lucafagherazzi** [comment]
+1
I really need it.
Thanks!

**Comment by m2sahin** [comment]
It's a simple request and I need it a lot. Please, i don't want to wait for years.

**Comment by MOSHE1111** [comment]
I need to define a post type (product) for the post author to receive the completed form.
How do I set it up?
Would you please agree to develop this thing as soon as possible?
That would be a nice idea

**Comment by Matt-bott** [comment]
Has anyone found a workaround I need this

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!
