### ISSUE TITLE
🔗 🚀 Feature Request: Support for Variable Fonts (Duplicate of #11333)

### ISSUE THREAD

**Issue by haemeulrich** [elementor/elementor#6703]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The new OpenType variable fonts are a big typographical improvement also on the web. It would be extremely great if Elementor would support these fonts and you could also enter the variables per breakpoint.

(https://medium.com/variable-fonts/https-medium-com-tiro-introducing-opentype-variable-fonts-12ba6cd2369)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by MrWhite214** [comment]
I would really like to see this feature added to Elementor as well. Especially since there is now a decent amount of Google Fonts that support variables weights.

**Comment by joexcm** [comment]
+1 for variable fonts. Real pain not being able to use the weights easily

**Comment by Lonsdale201** [comment]
+1
