### ISSUE TITLE
🔗 🚀 Feature Request: In accordion choose what tab do you want open (Duplicate of #2756)

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#6710]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to choose if the first tab is open, if I want close all tabs or in my case If I need open only second item.

**Describe the solution you'd like**
In every tab I can mark open or close

**Describe alternatives you've considered**
In my case I needed other plugin of accordions where I can choose open only second item.

**Additional context**
Other plugins You can choose what open tabs, in my case is essencial open only second tab for construct a vertical menu

**Comment by bainternet** [comment]
Duplicate of #2756 

https://github.com/pojome/elementor/issues/2756#issuecomment-396028468
