### ISSUE TITLE
🔗 🚀 Feature Request: Post popup, product popup, dynamic popup (Merged with #7106)

### ISSUE THREAD

**Issue by sbc640964** [elementor/elementor#6713]
Show link to post / product as Lightbox / Popup

**Comment by parfilov** [comment]
I want to clarify that to open page/post or WooCommence product content inside popup. With this feature we could make the dynamic popups with showing native data (heading, featured image, excerpt), custom fields, lead forms.

That's great for shops. Click on button in products archive listing to fast look and buy.
 
Also, with this feature we could to create one page shops without cart for fast niche and business hypothesis testing before creating full functional shop. 

Another reason is to sell products which don't need the shopping cart. Just click button on product in listing, fill the form and send order. The cornerstone here is to send data to email with post heading to identify which product was ordered.

I have one example http://coffee-online.kz It's in Russian but you will understand basic meaning.
1. I created custom posts for goods with custom fields and one lead CF7 form;
2. Then call the custom post content inside Magnific Popup.
So, the Contact Form 7 sends the product custom post's title (with [_post_title] shortcode) to the shop manager and she can to identify which product was ordered.

@sbc640964 please edit the heading of this issue to:
Post popup, product popup, dynamic popup
and provide more detailed information about what you want or approve that you want what I've wrote above.

@bainternet @arielk please don't close this issue! I wanted to create the same but decorated a little bit better and by guidelines. If you need some clarifications I'll try to provide them.

**Comment by sbc640964** [comment]
Yes, I would like it to be like a quick display of a plug-in, so you can make a product page temp that will jump in the archive and not go to the product page, also page post archives.

Simply make the purchase from one page without going to the product pages and back.

I do not write English, so I translate with a robot, sorry for the disruptions.

**Comment by parfilov** [comment]
@sbc640964 English isn't native for me too.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Champdor** [comment]
+1 for CPT. Second project I have to make this work.

**Comment by SayedTareq** [comment]
You guys can check this https://www.elementoraddons.com/tutorial/elementor-open-post-readmore-modal-popup/

**Comment by Tafmakura** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔃  This issue is being Merged with #7106

Which is on the same subject. 

Feel free to continue the conversation there. 😉 

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hey there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.26.0! 🥳 

You can now use the **Off-Canvas** widget inside your **Loop Item** templates to display additional Dynamic Content for each post in your **Loop Grid** widgets! 🎉 🥳 🙌 

You can learn more about the Off-Canvas widget (and how to use it) here: 
https://elementor.com/help/off-canvas-widget/
And about the Loop Grid here: 
https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
