### ISSUE TITLE
✅ 🚀 Make Elementor + WooCommerce Products Page Work with a Plugin with Ajax Live Search Capability

### ISSUE THREAD

**Issue by smile00000** [elementor/elementor#6747]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Make Elementor + WooCommerce Products Page Work with a Plugin with Ajax Live Search Widget Capability

Has anyone been able to effectively use any of the Ajax Live Search Widgets with Elementor Product Page such as:
Option 1. WooCommerce Product Search by Itthnx: https://woocommerce.com/products/woocommerce-product-search/

Option 2. Yith WooCommerce Ajax Search: 
https://yithemes.com/themes/plugins/yith-woocommerce-ajax-search/

Option 3. SearchWP (w/ Woo & Ajax Add On: 
https://searchwp.com/

Right now with any of these, the elementor woo product page will live sort and diminish the quantity list based on the attribute, size, etc, when you click a color, etc...but if you implement a live search bar the products list page will not live diminish to just that product.  I have the Woo product page products set to "Current Query" and it doesn't work. Think its an elementor connectivity issue with search.

Here is a demo of how it should effectively work with any live search plugin...as you type the images diminish to just what you are typing about (ie. dress), then it live switches to just dresses.
http://demo.itthinx.com/wps/

For some reason, I can't get that to work with any of the 3 plugins above. Can ANYONE else get it to work? If not, this must be a feature request.

**Describe the solution you'd like**
Make Elementor + WooCommerce Products Page Work with a Plugin with Ajax Live Search Widget Capability for Entire Wordpress Page & WooCommerce Products

**Describe alternatives you've considered**
Anything you think would work best

**Additional context**
I am using the latest Elementor & Elementor Pro, Latest WooCommerce, and WooCommerce Storefront theme. None of those 3 ajax search plugins work with your Elementor Product page template.

**Comment by jazir5** [comment]
+1

Ajax Live search functionality compatibility would be great. I had a ton of trouble trying to implement something like this months ago and could never figure it out.

**Comment by Skyagent42** [comment]
Such an excellent idea :)

**Comment by RetourtjeVos** [comment]
1+

**Comment by adi0071** [comment]
**Major importance** for any website especially e-commerce sites.
Much needed today

**Comment by mbrinson** [comment]
Definitely needed.  Of course we can just use the "Shortcode" widget in elementor, but then we loose all of the extra control that we started using Elementor for in the first place.

**Comment by mbrinson** [comment]
Actually... I just found a plugin that might fit the bill:

https://ajaxsearchpro.com/elementor-live-product-filter/

I haven't tested thoroughly yet (just getting started) but looks promising so far.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.23.0! 🥳 

To learn more check this article: https://elementor.com/help/search-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
