### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Elementor Pro Forms Submission Count (Merged with #1686)

### ISSUE THREAD

**Issue by remingtonchan** [elementor/elementor#6753]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor Pro Forms is a great feature to use in lead generating web pages. However, sometimes it's also great to show the number of submissions made so far. For example, applications forms. I found an external plugin that is able to list down and records all "leads" or submissions made into Elementor Forms, but there's no current way to display the number.

**Describe the solution you'd like**
A way to display the number submitted forms so far.

**Describe alternatives you've considered**
I found an external plugin that is able to list down and records all "leads" or submissions made into Elementor Forms, but there's no current way to display the number.

**Comment by bainternet** [comment]
I merged this issue with  #1686, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
