### ISSUE TITLE
[Feature Request] Dynamic Content in Button ID / Widget Attributes

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#6779]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
By enabling us to pull dynamic data to populate the Button ID (Button Widget) and/or all widgets attributes, we can dynamically populate those fields with data from custom fields so we can trigger different actions like custom popups (for the upcoming E Pro feature), modals, off-canvas or even custom styles for each element.

**Describe the solution you'd like**
1. Add the Dynamic tag to the button ID so each page with the same template can leverage the use of the same button for N actions or styles depending on what page the user is and the information we input on each page's custom field.

2. Add the Dynamic tag to all the widgets, sections and columns so we can populate that field with dynamic attributes that can be leveraged to change styles, trigger action scripts and all sorts of interactions based on a custom field of the page we are.

**Describe alternatives you've considered**
Doing the other way around, like triggering actions or making style changes based on a static information, but this way you limit the interactivity and usability of these functionalities. It can be simpler to do like I'm proposing and also less resource intensive since we won't need to make multiple templates and workarounds to achieve the same result.

**Additional context**
I was trying to open popups from the same layout and find that functionality would greatly improve and simplify what I was trying to do. In the end I had no viable solution without too much workarounds.

![capturar2](https://user-images.githubusercontent.com/26891676/51358119-1d025c80-1aa9-11e9-9416-b7c009c8e3f5.JPG)
![capturar1](https://user-images.githubusercontent.com/26891676/51358121-1d025c80-1aa9-11e9-80dc-3fa9cf257d8f.JPG)

**Comment by black-eye** [comment]
+1

**Comment by zeinnicholas** [comment]
I've just saw this feature was added to Elementor 2.5 (I know I'm late). But I just wanted to thank you for considering it and adding it to the master branch! You guys rock!

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field.

**Comment by mathetos** [comment]
Though this feature was released a while back, the implementation of it is still not desirable. 

The Dynamic Content tool now appears in the Attributes text area, but if you choose it, it takes over the whole area. This doesn't allow for dynamic content of specific data-attributes. 

Here's what I'm trying to accomplish:
```
data-vars-ga-category|blog-cta
data-vars-ga-action|Click to Pricing
data-vars-ga-label|{post_id}
```
This would allow me to have specific event clicks via Google Analytics. The markup is specific, and if the `{post_id}` part was dynamic then I'd be able to pass that everywhere this template appears throughout the site and pass the Post ID to GA. 

Is there something like the mergetags example I have here available for this purpose in Elementor? 
![image](https://user-images.githubusercontent.com/930724/152057946-c3c83adb-36e4-44b2-ba5b-d84fe85b34d4.png)

**Comment by LexPlayGames** [comment]
> Though this feature was released a while back, the implementation of it is still not desirable.
> 
> The Dynamic Content tool now appears in the Attributes text area, but if you choose it, it takes over the whole area. This doesn't allow for dynamic content of specific data-attributes.
> 
> Here's what I'm trying to accomplish:
> 
> ```
> data-vars-ga-category|blog-cta
> data-vars-ga-action|Click to Pricing
> data-vars-ga-label|{post_id}
> ```
> 
> This would allow me to have specific event clicks via Google Analytics. The markup is specific, and if the `{post_id}` part was dynamic then I'd be able to pass that everywhere this template appears throughout the site and pass the Post ID to GA.
> 
> Is there something like the mergetags example I have here available for this purpose in Elementor? ![image](https://user-images.githubusercontent.com/930724/152057946-c3c83adb-36e4-44b2-ba5b-d84fe85b34d4.png)

How do I assign 2 values to the same key?
I already tried everything.

hide-system-id|class04
hide-system-id|class05
In this case, Elementor only assumes the last value.

hide-system-id|aula04;aula05 doesn't work

hide-system-id|aula04,aula05 doesn't work

I'm lost here. hahahaha
