### ISSUE TITLE
🔗 🚀 Feature Request: Build form with any Cf by ACF PRO to directly submit post ( USP ) (Duplicate of #1686, #6828)

### ISSUE THREAD

**Issue by mariobarretta** [elementor/elementor#6845]
I've searched on GH and the issue https://github.com/pojome/elementor/issues/1686 is not a duplicate of my request.

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I’m an Elementor Pro User and i'd need to can build a form that integrate all the CF created by ACF PRO.

Actually there is not this feature and i'm very frustrated for this missing.

I would like to use Elementor and to do an advanced step on the web site design using the power of Elementor + ACF Pro to creating directory sites and Events and Books and many other sites with custom fields managed on a form accessed from external user that can publish on my site.

I see that team develop a lot of new features but, for now, no any attention to USP ( User Submitted Post ) and i hope to can finally and totally use your page builder .

I'd like to can open the form editor and to choose on my CF to can directly build a form using them how i do on the build of a template

I've tried a lot of external plug in but no one has a good feeling with elementor so i think that could be the best thing that elementor team develop this feature look like have done with the last pop up service

Thank you very much for attention and any feedback from you

**Comment by shilo-ey** [comment]
Hi @mariobarretta 

I merged this issue with  #1686, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by mariobarretta** [comment]
Hi @shilo-ey 
That issue is one year old and appear to not generate interest in elementor staff.

**Comment by shilo-ey** [comment]
@mariobarretta we track all issues. when we will decide to implement this feature you will get notified by subscribing to this thread.

We invite you to contribute to the conversation there.
