### ISSUE TITLE
Image Widget: figcaption is not linkable

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#6848]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The **Image Widget** has the option to show a **caption** bellow the image. It is implemented using the `<figcaption>` tag. In addition we can set custom links to the image.

The issues it that while the image has a link, the caption does not. Users can't really control this, they can't apply the link on the caption too.

## Steps to reproduce

1. Add an image.
2. Select caption (or write custom caption text).
3. Add link to custom URL.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@ramiy 	

Why would you need to link the caption? whats the use case>?

**Comment by ramiy** [comment]
What? I need to caption to be linkable! This is the client requirement.

**Comment by ramiy** [comment]
BYW: it's an easy fix [see here](https://github.com/pojome/elementor/blob/master/includes/widgets/image.php#L711-L730).

The question is whether to add a new control or not.

**Comment by gwmbox** [comment]
Needing the same as well.

With the "easy fix" how do I set that up?  Something I add to my functions.php file?

**Comment by Onecton** [comment]
> @ramiy
> 
> Why would you need to link the caption? whats the use case>?

For Example if you use the Image Caption as a Makeshift Button under an Image, users tend to klick on the "box" which isn't a link.

**Comment by DorShahar** [comment]
Hi @ramiy ,
Thank you for your feedback.

Unfortunately, at the moment we will not support this request.
Off curse that you can develop that on your own as you suggested.

Thanks.

**Comment by bkno** [comment]
Sharing my simple JS solution to this:

```
    $(".link-image-caption").each(function() {
        $(this).find("figcaption").appendTo( $(this).find("a") );
    });
```

You can use this on a case-by-case basis by applying the utility class `link-image-caption` to the Elementor image.

**Comment by sarit026** [comment]
> Sharing my simple JS solution to this:
> 
> ```
>     $(".link-image-caption").each(function() {
>         $(this).find("figcaption").appendTo( $(this).find("a") );
>     });
> ```
> 
> You can use this on a case-by-case basis by applying the utility class `link-image-caption` to the Elementor image.

not working

**Comment by sarit026** [comment]
+1

**Comment by kallekallovsky** [comment]
Sorry für digging this out, but stumbled across and felt like sharing:
Running Elementor v 3.23.4, the script was also not working. Updated the selectors and have it up and running fine.

$(document).ready(function () {
    $("figure.wp-caption").each(function() {
        $(this).find("figcaption").appendTo( $(this).find("a") );
    });
});

**Comment by dulakshirb** [comment]
<script>
    jQuery(document).ready(function($) {
        $("figure.wp-caption").each(function() {
            // Find the figcaption and anchor within this figure
            const $figure = $(this);
            const $anchor = $figure.find("a");
            const $caption = $figure.find("figcaption.wp-caption-text");
            
            // Move caption inside the anchor tag
            if ($anchor.length && $caption.length) {
                $caption.appendTo($anchor);
            }
        });
    });
</script>
