### ISSUE TITLE
⛔ Elementor stores page css in uploads folder, making any kind of load balancing or automated deployments impossible

### ISSUE THREAD

**Issue by epoplive** [elementor/elementor#6859]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor stores page css in uploads folder, making any kind of load balancing or deployments involving spinning up a new server essentially impossible.  The css either needs to be stored in the database, rather than as static files in the uploads folder, or there needs to be a way to have an automated deployment system be able to regenerate all css for all sites in a multi-site install.

## Steps to reproduce
Create a new server using wordpress and plugins from a git repo.  All css for all sites and their associated pages needs to be regenerated.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
This has nothing to do with the environment.

**Comment by shilo-ey** [comment]
@epoplive 
This is how Elementor uses CSS files for better optimizing the page load.

If you want to change this method you can add the CSS inline.

Go to Elementor > Settings > Advanced > and change "CSS Print Method" to Internal Embedding.

![image](https://user-images.githubusercontent.com/45009641/51661340-3e87aa80-1fb9-11e9-9d6e-de94d84975f4.png)


thanks.

**Comment by barrychapman** [comment]
This is not an acceptable fix as it is quite slow and makes CDN usage worthless. The site needs to check for existence of these css cache files and generate them if they do not exist.

**Comment by mims92** [comment]
Having the same problem too. This is very annoying...

**Comment by AgilePixelStudio** [comment]
Also having this problem. would be great to be able to choose an s3 bucket to host the files in /wp-content/uploads/elementor/css/

**Comment by d0ky** [comment]
Same here, quite annoying bug to close it without any real help or workaround

**Comment by gdonoso94** [comment]
+1 over here. Need to regenerate multiple times the CSS files in order to affect all instances behind LB.

**Comment by dcambria** [comment]
same here. Any solution?

**Comment by joeFordTheNerd** [comment]
This issue should not be closed

**Comment by maikelnight** [comment]
This should not be closed. Beside, this makes it really hard to embedd Elementor created sites and styles to a front end framework.

**Comment by dcambria** [comment]
Please reopen this topic. It’s an important issue to work load balanced.Em 2 de mar. de 2023, à(s) 16:14, Maik Linnemann ***@***.***> escreveu:﻿
This should not be closed. Beside, this makes it really hard to embedd Elementor created sites and styles to a front end framework.

**Comment by rebofel** [comment]
Same issues with load balancing!!!

**Comment by karjogedhe** [comment]
I hope the developer team would be add this issue as their priority. 

Meanwhile, I had to sync the css files at certain time using AWS SYNC and use S3 for collect the files. It's working for now, but I hope there would be another time saver for everyone.

**Comment by cardovaeric** [comment]
this is still a problem, i didnt find a clean way to do it.

i have multi-node wordpress and whenever we regenerate the css, other nodes are broken

**Comment by Jojo109** [comment]
Hi all, 
any update on this ticket. We have muti wordpress node behind the load balancer, as css files are not sync and web page is broken. 
Any temporary solution for this issue. Thanks

**Comment by nicholaszein** [comment]
Hello everyone, I want to replicate the comment I gave in #25290 to @Jojo109 here, so you can understand our position regarding this matter:

> Elementor uses the default [wp_upload_dir()](https://developer.wordpress.org/reference/functions/wp_upload_dir/) function to find out where to generate the CSS files. It does not, however have any way to identify if you are using a load balancer. 
> This is something you need to setup yourself, and identify the proper paths for each instance by using the [UPLOADS](https://developer.wordpress.org/apis/wp-config-php/#moving-uploads-folder) constant in your `wp-config.php` file if you wish to leverage the external CSS generation, or use a file replicating/sync tool like GlusterFS for synchronizing files between your nodes. 
> Otherwise you should follow the instructions in [this comment](https://github.com/elementor/elementor/issues/6859#issuecomment-457093366) and change the **`CSS Print Method`** to **`Internal Embedding`**.

This is not a bug, and we have no plans to change this functionality. We are following all the WordPress best practices here, and you should be able to change the location of the uploads directory based on your needs.

I am closing the comments on this matter.

Kind regards
