### ISSUE TITLE
🔗 🚀 Feature Request: Popup scheduler (Duplicate of #6899)

### ISSUE THREAD

**Issue by kangoo13** [elementor/elementor#6863]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I need to create all popup's for X multi-websites and then come back day X to activate the popup on every websites, and then come back day X + 7 to disable every popups.

**Describe the solution you'd like**
The solution I would like is a kind of planner for popups, you set a start date and an end date. between those 2 dates the popup is activated.

**Describe alternatives you've considered**
No alternatives but take a look at https://wppopupmaker.com/extensions/scheduling/ or https://premium.wpmudev.org/project/the-pop-over-plugin/

**Additional context**
Would be ideal if we could deploy the created popup on a selected list of mini site that we own.

**Comment by nicomollet** [comment]
I would like to unpublish popups too. Thank you.

**Comment by remyrichard** [comment]
Obviously, it would be very useful! Thanks.

**Comment by MafuraG** [comment]
This could be a very useful addition.

**Comment by roicarl** [comment]
I would like a start and end date for the popup. Possibly to include begin and start time within date.

**Comment by roicarl** [comment]
I would like to see the popup show by day of the week.

**Comment by shenom-x** [comment]
All 3 thumbs up! Totally missing that feature here. We´re using the popups for raffles / lottery that have these nice countdown fields in it. An auto-shutdown would be very welcome!

**Comment by nicomollet** [comment]
I don't get why feature requests are closed.
It sends a poor message.

**Comment by Barns-be** [comment]
I also want to be able to set  a start/end date to a popup (eg. a popup that announces a company's presence on a fair. After the fair has ended, I shouldn't have to remember to deactivate the popup - it does it by itself.)

**Comment by Rifqa123** [comment]
I also think this is an important feature and look forward to seeing it coming available.

**Comment by patbell101** [comment]
Yes this would be good for marketing, events and general notifications - even "Happy Christmas" Perhaps it will be in time for this Xmas?

**Comment by tristanmason** [comment]
+1 on having a start/end date. Thanks!

**Comment by studiogrynn** [comment]
+1 on popup scheduling for publish/unpublish.

**Comment by neznakomov** [comment]
+1 Please!!!

**Comment by yesterselga** [comment]
+1 this must be included thanks

**Comment by PrintableCuttableCreatables** [comment]
+1 Yes please! Elementor advertises the use of Popups for Promotions/Sales, and even has several templates for this use, so naturally there should be a way to Schedule the popup to publish and unpublish when the Promotion starts and ends. Popups were introduced over a year ago, and this seems like a pretty key part of popups!

**Comment by digitalinksol** [comment]
+1

I think a scheduler for popups only makes sense since one of its prime uses is for promotions/sales.

**Comment by TheCosmonaut** [comment]
+1 Would really like a scheduler supporting date and time that supports both one-time schedules and recurring schedules

**Comment by teddyskokos** [comment]
+1 This is a very needed feature for many time-sensitive popups, like a Black Friday promotional for instance.

**Comment by black-eye** [comment]
+1

**Comment by fpuccine** [comment]
I would like to see a start and end date for the popup. Possibly to include begin and end time within date.
To be used for Black Friday and Cyber Monday Sales, Holidays, New Year and other holidays
All that is needed is to roll in some of the add on like Dynamic Visibility for Elementor Plugin.

**Comment by ludekcerny** [comment]
+1

**Comment by johodesign** [comment]
+1

**Comment by neylwalecki** [comment]
+1

**Comment by Lisguincio** [comment]
+1

**Comment by missnene** [comment]
I would like to have a recurring popup. +1 for this feature request.

**Comment by busymick** [comment]
+1 for adding a schedule feature for pop-ups

**Comment by it7steve** [comment]
+1 here too

**Comment by lkjune** [comment]
2021 I am still waiting for the option to set a start and end date to a popup.

**Comment by black-eye** [comment]
@bainternet @shilo-ey Please consider reopening this issue, the demand seems to me quite large... And the popup feature definitely needs a few other options too (like https://github.com/elementor/elementor/issues/8187 for instance). Thanks

**Comment by patbell101** [comment]
I solved this by using the Dynamic Conditions free plugin

**Comment by lkjune** [comment]
> I solved this by using the Dynamic Conditions free plugin

If possible, I try to avoid use one more plugin.

**Comment by shakeel173** [comment]
+1

**Comment by pascal-klaeres** [comment]
24 Jan 2019 and still not done? +1

**Comment by stephenwayne** [comment]
Yoooooooooo why is this still not a thing!?

**Comment by andressavw** [comment]
04 Jan 2022 and still not done? +1

**Comment by rafaviana** [comment]
> Hi there, here is a tip to schedule the elementor popup :
> 
> * use the Wordpress schedule functionnality
> * use Post expirator plugin (https://wordpress.org/plugins/post-expirator/) and schedule to unpublish.
> * et Voilà ;)

it works this way, a good workaround ;)

**Comment by rafaviana** [comment]
But that plugin lets you set visibility conditions for the whole popup, including the overlay? Or only to the content section of the popup?

**Comment by johodesign** [comment]
You can set the condition on the popup advanced settings for the whole popup.

**Comment by rafaviana** [comment]
I'm trying to use it but the popup it's always showing up. The conditions I have are these ones:
![Elementor-Campanha](https://user-images.githubusercontent.com/5817213/153624926-a6885173-f8c3-4fd3-9a03-078161084371.png)

And the popup has a display condition to show on front page after 4sec

**Comment by johodesign** [comment]
At the Dynamic Tag you have to set the tag to Current Date.

**Comment by nicholaszein** [comment]
Hello @steve-manes!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #6899

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

We are also beta-testing our new [Popup Advanced Rule for Date and Time range](https://github.com/elementor/elementor/discussions/21125), which covers part of what you're asking. Try the new beta version and let us know if it helps to manage popups better.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
