### ISSUE TITLE
🔗 🚀 Feature Request: Allow do_shortcode() support for slides content (Duplicate of #2445)

### ISSUE THREAD

**Issue by pingram3541** [elementor/elementor#6874]
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Wanting more content than just the title, description and button within the slide's content.

**Describe the solution you'd like**
Allow for shortcode's to be used in the "description" field as mentioned here - https://github.com/pojome/elementor/issues/2445#issuecomment-452210450

**Describe alternatives you've considered**
n/a

**Additional context**
Since this is a Pro feature I cannot submit a PR but the code is as follows:

Wrap $slide['description'] with do_shortcode() on line 1175 of /modules/slides/widgets/sides.php

`$slide_html .= '<div class="elementor-slide-description">' . do_shortcode( $slide['description'] ) . '</div>';`

**Comment by pingram3541** [comment]
Better yet, instead of just the description, it's better to wrap the final $slide_html instead.

Wrap $slide_html with do_shortcode() on line 1190 of /modules/slides/widgets/sides.php

`$slides[] = '<div class="elementor-repeater-item-' . $slide['_id'] . ' slick-slide">' . do_shortcode( $slide_html ) . '</div>';`

**Comment by pingram3541** [comment]
Interesting, I've been using this snippet successfully on a live site with no formatting issues at all.  I'm loading a 2-column section, heading text and 2 custom buttons within an inner section that each trigger popup overlays and a video with lightbox effect in the other column per slide and having no issues, even with custom css carrier over.

**Comment by Aviad-Herman** [comment]
Hi,
Merging this old issue with #2445 (comment)

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel introduced in Elementor Pro v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
