### ISSUE TITLE
Feature Request: trigger popup from a menu item and text link

### ISSUE THREAD

**Issue by JohnMulderFrance** [elementor/elementor#6876]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I would like to trigger a popup from a menu item (like issue 6871) and in addition from a text link.
Compared to all the possible advanced ways to trigger a popup, these two might look too simple, but i now need to keep my current popup plugin to get this done. Ofcourse i would like to deactivate this plugin and do all in Elementor.

**Comment by parfilov** [comment]
Yeah! I and my subscribers need it too. ID trigger as in Popup Maker would be great.

**Comment by laratuk** [comment]
You can use Popup Trigger URL feature in this plugin https://www.youtube.com/watch?v=ev3dfxgt-Xs

**Comment by silvioghedin** [comment]
+1 totally need this feature

**Comment by zeinnicholas** [comment]
+1 any ETA? This is something I'm missing greatly.

**Comment by shilo-ey** [comment]
This feature has been added in Elementor Pro v2.5.0

Feel free to update!

Thanks!

**Comment by kroeberk** [comment]
Sadly, it only seems to work when you click on an item. It would be great if this worked just on pageload. I want to have a /page/ that's normal - but when you open it with /page/#special-offer the popup should show. Would this be possible to implement?

**Comment by oceandiveloper** [comment]
> This feature has been added in Elementor Pro v2.5.0
> 
> Feel free to update!
> 
> Thanks!

How do I use this new feature? I've installed Elementor Pro 2.5.2 but don't seem to figure out how exactly I can trigger a popup from a menu item with the id?

**Comment by parfilov** [comment]
@oceandiveloper you can set ID or class on advanced tab and then set the condition of view but it doesn't work anyway 😂
Seem I should to create the new issue.

**Comment by shilo-ey** [comment]
@parfilov @oceandiveloper 

You have to set the conditions for the popup to be loaded in the page you wish the trigger will set off.

e.g, you want your nav menu item which has a class ".popup" to open a popup.
First, go to the desired popup, go to advanced tab, and under the selector field type in ".popup". 
Click on update > and under "Conditions" set "Entire site"

Now it should work.

Thanks

**Comment by jackslayer1234** [comment]
> @parfilov @oceandiveloper
> 
> You have to set the conditions for the popup to be loaded in the page you wish the trigger will set off.
> 
> e.g, you want your nav menu item which has a class ".popup" to open a popup.
> First, go to the desired popup, go to advanced tab, and under the selector field type in ".popup".
> Click on update > and under "Conditions" set "Entire site"
> 
> Now it should work.
> 
> Thanks

I tried doing this but it did not work. So for a form, I had a field type Acceptance. This was the html.

`<div class="elementor-field-subgroup"><span class="elementor-field-option"><input type="checkbox" name="form_fields[field_10]" id="form-field-field_10" class="elementor-field elementor-size-sm  elementor-acceptance-field" required="required" aria-required="true" checked="checked"> <label for="form-field-field_10">I accept and understand the Terms and Conditions.</label></span></div>`

In the advanced tab of the popup I indicated "div.elementor-field-subgroup". When I reloaded my page and clicked the area, the popup appeared to just flicker appearing and disappearing so fast that a user will not be able to see it.

What's the solution to this? Thanks.

**Comment by garylevansjr** [comment]
I was able to do this:

```
var popup = elementorFrontend.documentsManager.documents[529];
popup.showModal();
```
Not sure if this will cause issues with anything else, but thought I would share.

**Comment by JohnMulderFrance** [comment]
I use the plugin https://wordpress.org/plugins/popup-trigger-url-for-elementor-pro/
to solve my needs. Works fine for me.

**Comment by cohler** [comment]
> You have to set the conditions for the popup to be loaded in the page you wish the trigger will set off.
> 
> e.g, you want your nav menu item which has a class ".popup" to open a popup.
> First, go to the desired popup, go to advanced tab, and under the selector field type in ".popup".

When editing a popup, there is no "selector field" under the Advanced tab. There is a CSS Classes field. Is that what you are referring to?

**Comment by jackslayer1234** [comment]
> > You have to set the conditions for the popup to be loaded in the page you wish the trigger will set off.
> > e.g, you want your nav menu item which has a class ".popup" to open a popup.
> > First, go to the desired popup, go to advanced tab, and under the selector field type in ".popup".
> 
> When editing a popup, there is no "selector field" under the Advanced tab. There is a CSS Classes field. Is that what you are referring to?

@cohler you are not clicking the right area. See this: https://i.imgur.com/efunJeO.png

**Comment by cohler** [comment]
> > > You have to set the conditions for the popup to be loaded in the page you wish the trigger will set off.
> > > e.g, you want your nav menu item which has a class ".popup" to open a popup.
> > > First, go to the desired popup, go to advanced tab, and under the selector field type in ".popup".
> > 
> > 
> > When editing a popup, there is no "selector field" under the Advanced tab. There is a CSS Classes field. Is that what you are referring to?
> 
> @cohler you are not clicking the right area. See this: https://i.imgur.com/efunJeO.png

Where is that "Popup Settings" window you show in that image?? When click on Templates=>Popups from the Dashboard and then edit a Popup with Elementor I get a screen that looks as follows...

> > > You have to set the conditions for the popup to be loaded in the page you wish the trigger will set off.
> > > e.g, you want your nav menu item which has a class ".popup" to open a popup.
> > > First, go to the desired popup, go to advanced tab, and under the selector field type in ".popup".
> > 
> > 
> > When editing a popup, there is no "selector field" under the Advanced tab. There is a CSS Classes field. Is that what you are referring to?
> 
> @cohler you are not clicking the right area. See this: https://i.imgur.com/efunJeO.png

Thank you. This should be made clear, as the present instructions are totally unclear. 

In other words, the correct instructions would be: (1) edit the desired popup in Elementor, (2) click on the Settings wheel icon at the lower left of the window to open "Popup Settings", (3) Click on the "Advanced" tab at the top right of the "Popup Settings" frame, (4) enter the desired class name (including the period) such as ".classname" in the "Open By Selector" field.

**Comment by beezwings** [comment]
@ jackslayer1234, thank you! Now it works when I click the link, but the popup disappears as soon as the new page is loaded. How can I prevent the popup from closing on page load?
