### ISSUE TITLE
Error saving Elementor settings

### ISSUE THREAD

**Issue by andyp05** [elementor/elementor#6890]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
 
Completely new wordpress install V 5.0.3 (new directory and database) running on Siteground servers. No pages created yet and Elementor is only plugin installed and active. Using default WP theme. 

When I go to save Elementor settings, the following error pops up:

Warning: time() expects exactly 0 parameters, 1 given in /home/xxx/public_html/xxx.com/wp-includes/class-wp-hook.php on line 288

Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/xxx.com/wp-includes/class-wp-hook.php:288) in /home/xxx/public_html/xxx.com/wp-includes/pluggable.php on line 1223

## Steps to reproduce
Go to Elementor->Settings and hit Save.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.3.1
	PHP Max Input Vars: 500000000000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.4
		Author: Elementor.com


== Log ==
	: 
				
				
```
</details>

**Comment by andyp05** [comment]
More info...I tracked it down to the PHP Version. If I set the PHP Version to 7.2.14 the error goes away. When I upgrade to PHP 7.3.1, the error appears.

**Comment by andyp05** [comment]
I do not see php errors related to this in the cPanel Error Logs app.

Maybe I am looking at the wrong log. Can you give me path and filename you want me to check?
________________________________

**Comment by shilo-ey** [comment]
Try saving, then you will have to check immediately to see if any errors are logged.

If nothing happens, try adding the debug mode to wordpress:
```PHP
 // Enable WP_DEBUG mode
define( 'WP_DEBUG', true );

// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );

```

Then try saving again, and go to /wp-content/debug.log to check your errors.

Thanks.

**Comment by andyp05** [comment]
Changed to php 7.3.1 and got the following:
`
[06-Feb-2019 15:07:53 UTC] PHP Warning:  time() expects exactly 0 parameters, 1 given in /home/yyy/public_html/xxx.com/wp-includes/class-wp-hook.php on line 288

[06-Feb-2019 15:07:53 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/yyy/public_html/xxx.com/wp-includes/class-wp-hook.php:288) in /home/yyy/public_html/xxx.com/wp-includes/pluggable.php on line 1223
`
changed back to 7.2 and error goes away.
The happens with default theme or OceanWP. Elementor and Elementor Pro are only plugins activated.
Hope this helps.

**Comment by shilo-ey** [comment]
Does changing your theme to twenty seventeen solves the problem?

**Comment by andyp05** [comment]
No. Both themes cause the error.
________________________________

**Comment by synio-wesley** [comment]
I have the same problem using Trellis + Vagrant with PHP 7.3

**Comment by jskerchner** [comment]
I have the same issue and, as others have noted, I had to switch to PHP 7.2 to work around the error. I'm using Elementor Pro with the Hello theme.

**Comment by synio-wesley** [comment]
I do think the settings are saved though. It also only happens in debug mode because otherwise the warning won't be rendered to the screen and then the redirect will work as usual.

**Comment by jskerchner** [comment]
> I do think the settings are saved though.

The settings were definitely not saved for me.  I was trying to add a Mailchimp API key and it wasn't being saved.

**Comment by JoeDarko** [comment]
Same here. Clean install, PHP 7.3 and i'm getting this warning when i'm trying to save the Elementor settings:

Warning: time() expects exactly 0 parameters, 1 given in /data/web/virtuals/215841/virtual/www/domains/xxx.cz/wp-includes/class-wp-hook.php on line 288

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/215841/virtual/www/domains/xxx.cz/wp-includes/class-wp-hook.php:288) in /data/web/virtuals/215841/virtual/www/domains/xxx.cz/wp-includes/pluggable.php on line 1251

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/215841/virtual/www/domains/xxx.cz/wp-includes/class-wp-hook.php:288) in /data/web/virtuals/215841/virtual/www/domains/xxx.cz/wp-includes/pluggable.php on line 1254


Why is this still not solved?
