### ISSUE TITLE
[Has pull request] Column responsive options

### ISSUE THREAD

**Issue by wayheming** [elementor/elementor#6898]
Hello everyone, this is a duplicate of problem #2965 made to draw attention to the problem. I made a pull request #6837 can someone look at it? Thanks in advance!

**Comment by wayheming** [comment]
Hello @shilo-ey can you please check my request? Thanks

**Comment by wayheming** [comment]
Sorry, can somebody pay attention to the question?

**Comment by shilo-ey** [comment]
Hey @wayheming 

Thanks for your time creating this enhancement.

We will look at the PR and if we will find it useful after our review we will add it to the version.

Thanks!

**Comment by wayheming** [comment]
@shilo-ey Hello thank you!

**Comment by KimchaC** [comment]
You are the hero we needed!

**Comment by wayheming** [comment]
> You are the hero we needed!

haha 😂

**Comment by shilo-ey** [comment]
This feature has been added in Elementor v2.5.0

Feel free to update!
