### ISSUE TITLE
🔗 🚀 Feature Request: Section vertical divider (Duplicate of #2729)

### ISSUE THREAD

**Issue by twistiff** [elementor/elementor#6918]
Split the section in two areas.
Currently you can use background gradient to achieve this. However, I also want to make the divider wavy. Kind of like how they work with the divider on bottom/top of the section.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

I merged this issue with  #2729, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
