### ISSUE TITLE
mislocated transparency color bar [bug] still there

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#6968]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and can find not solved duplicates.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

transparency selection bar is still mislocated when using firefox developer edition ...

o.k. on chrome
o.k. on standart firefox
not o.k. on firefox developer

this was already posted weeks ago and still persists  #6501
![50235775-fa512b00-03b8-11e9-9f62-115f4962861c](https://user-images.githubusercontent.com/22448174/52204026-41b14f00-2873-11e9-80dc-5c7da6c4cf04.png)

was posted some days ago by another user and still persists #6946
![52133331-64f4b800-2641-11e9-87bc-a22db3c3e7e1](https://user-images.githubusercontent.com/22448174/52204115-86d58100-2873-11e9-8543-0a03d5e04e62.JPG)

dont know whats causing this exactly, but can tweak it by css - so you should be able to do so too - permanently ...
and please dont post you "cant replicate" again. you can by using the claimed browser :)

## Steps to reproduce

use firefox developer edition for editing color and see ...
thanks

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

could provide system info of 20 completely different installations - always the same. so this doesnt seem to make any difference!
...

**Comment by shilo-ey** [comment]
@dasigna 
Thanks for the missing replicating info, we will look into it.

**Comment by black-eye** [comment]
Confirming this issue. Since version 65 it's present on standard Firefox edition as well.
Wasn't there yesterday, before I did Firefox restart and update (not sure, which version was that).

**Comment by black-eye** [comment]
Actually, there is more to it...

The color pointer is misplaced as well. So it's impossible to select colors near the topline and corners. See the picture, where the pure white is situated:

![obrazek](https://user-images.githubusercontent.com/5634870/52384960-fb7d0b00-2a7f-11e9-8f16-912373b8c1b4.png)

This color was selected from the predefined palette, othervice it wouldn't be possible to select it at all - see picture below: instead of #ffffff I'm getting #efefef

![obrazek](https://user-images.githubusercontent.com/5634870/52385269-0d12e280-2a81-11e9-86e9-354fd46325fa.png)

Please fix it ASAP, Thanks.

**Comment by shilo-ey** [comment]
Hi @dasigna 

The issue with the mislocated alpha picker is fixed in Elementor 2.4.6.

As for the color picker offset issue - we are still experimenting solutions and will update soon.

Thanks.

**Comment by freelancesam** [comment]
Please look into my issues merged with this #7171 , it would be nice for designers to be able to use HSL to build more coherent/intuitive color schemes.

**Comment by black-eye** [comment]
Hi @shilo-ey , anything new on the "color picker offset issue"? It's still there and it's quite annoying, making the picker quite unusable. Thanks

**Comment by shilo-ey** [comment]
@black-eye We're investigating new color pickers to embed in Elementor.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.8

Feel free to update

Thanks!
