### ISSUE TITLE
Dynamic link for Flip Box

### ISSUE THREAD

**Issue by Domineeer** [elementor/elementor#6986]
Dear Elementor support,
I really need dynamic link for Flip Box.
There is only https://your-link.com option.

I need pop up to show when clicked on button.

Thank you for your help.

**Comment by mgustavs** [comment]
I need that too! So far I got around with Make Column Clickable Elementor plugin by Fernando Acosta, but it does not want to open a popup. Maybe cause flipbox code overrides it..
