### ISSUE TITLE
Dynamic Tags for Elementor Form Integration with Drip Email Marketing

### ISSUE THREAD

**Issue by craiggrella** [elementor/elementor#7000]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I asked a question of support team and they said the request was not available currently. They put in a feature request and suggested I post it here as well. That's what this post is for.

**Describe the solution you'd like**
============

I'm working with elementor forms and drip email integration.Form allows pushing a tag to drip. This seems to be static, meaning I can put a static tag text name there, or list of them separated by commas.

But can I do a list of tags dynamically from form. For example, lets say i create a form that has checkbox fields like this:
- option 1
- option 2
- option 3
- option 4

Those fields are put into an array/object.

If there a way to then put that into the tag box like this {{tags}} where it would essentially insert a comma-separated list of those checkbox values to sync with Drip, that would nearly complete the drip integration and allow for dynamic tag additions based on checkbox selections.

--

============

**Describe alternatives you've considered**

**Additional context**

**Comment by benallfree** [comment]
Just came here to suggest this.

To add another use case, I use WP Toolset extensively to manage custom post types. I would LOVE to make a Landing Page post type where I can plug in all my particular variables (video, description, drip tags, etc) and let Elementor do the work of rendering a page template.

**Comment by shilo-ey** [comment]
Hi @craiggrella ,

Thanks for your feedback, we will look into it and update this issue.

@benallfree , this is already available using [Dynamic Tags](https://docs.elementor.com/article/310-dynamic-content)

Thanks.

**Comment by benallfree** [comment]
@shilo-ey I'm aware. Like @craiggrella suggests, the dynamic tags are not available on every field.
