### ISSUE TITLE
Image ratio not working for extended custom post card skin

### ISSUE THREAD

**Issue by mariofox** [elementor/elementor#7019]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by mariofox** [comment]
Hi! I extended the post skin to create a custom one as stated here:

https://github.com/pojome/elementor/issues/4397

I extended Card Skin like this:

Note I didn't even overwrote any render method
`<?php

class Custom_Post_Card_Skin_Aloha extends \ElementorPro\Modules\Posts\Skins\Skin_Cards {
    public function get_id() {
        return 'post-card-custom-skin-aloha';
    }
    public function get_title() {
        return __( 'Custom Cards Aloha' );
    }
}`

Then I added:
`add_action( 'elementor/widget/posts/skins_init', function( $widget ) {
    require( 'modules/elementor/skins/skin-card-custom.php' );
    $widget->add_skin( new Custom_Post_Card_Skin_Aloha( $widget ) );
} );`

Now I'm able to select my  custom skin, but when I select any image ratio to my custom skin, the image won't work as expected (an extra padding is applied, instead of fitting the image). 

I compared the codes of both native card skin and my custom card skin and elementor is not adding the class "elementor-has-item-ratio" to the posts container.

You can reproduce it simply extending the post card skin to create a custom skin and applying any image ratio to the custom skin.

Thank you!

**Comment by mbaierl** [comment]
Hey @mariofox!

I have the exactly same problem and are unable to figure out what triggers the JS code, which adds the elementor-has-item-ratio class... 

How did you solve the problem? Obviously not through this bug report...

Michael

**Comment by mariofox** [comment]
> Hey @mariofox!
> 
> I have the exactly same problem and are unable to figure out what triggers the JS code, which adds the elementor-has-item-ratio class...
> 
> How did you solve the problem? Obviously not through this bug report...
> 
> Michael

I haven't solved my problem :(

Honestly, I used another Elementor plugin (Ultimate Addons) for generating my post card, and it's much easier to do customization on the skin for the Ultimate Addons.

**Comment by mbaierl** [comment]
Hi @mariofox ,

I've solved it by overriding the get_container_class method:

```
public function get_container_class() {
	return 'elementor-has-item-ratio elementor-posts--skin-' . $this->get_id();
}
```

**Comment by shilo-ey** [comment]
Hi @mariofox @mbaierl 

Glad you figured it out, 

Closing this issue for now.

Thanks!

**Comment by ShadowXVII** [comment]
I had this issue too -- I think the underlying cause is something to do with how the JavaScript front-end picks up image ratio settings?

I'm guessing this is similar to #1708 and #8761

The more elegant solution would be to understand why the JavaScript doesn't apply.

**Comment by saulobraine** [comment]
Hey everyone, I'm having this same issue.
Here I'm trying to extend the Classic Skin to include categories on Meta Data, well I'm using last Elementor and Elementor Pro, and this issue, unfortaly keeps.

> Hi @mariofox ,
> 
> I've solved it by overriding the get_container_class method:
> 
> ```
> public function get_container_class() {
> 	return 'elementor-has-item-ratio elementor-posts--skin-' . $this->get_id();
> }
> ```

This solution do not solved in completed, now here I'm have a new issue that Elementor do not include the "elementor-fit-height" on need  images and some of then show wrong.

How to fix that?

**Comment by souragency** [comment]
> Hey everyone, I'm having this same issue.
> Here I'm trying to extend the Classic Skin to include categories on Meta Data, well I'm using last Elementor and Elementor Pro, and this issue, unfortaly keeps.
> 
> > Hi @mariofox ,
> > I've solved it by overriding the get_container_class method:
> > ```
> > public function get_container_class() {
> > 	return 'elementor-has-item-ratio elementor-posts--skin-' . $this->get_id();
> > }
> > ```
> 
> This solution do not solved in completed, now here I'm have a new issue that Elementor do not include the "elementor-fit-height" on need images and some of then show wrong.
> 
> How to fix that?

Hey, Saulobraine,

did you manage to fix the height issue that arises after you fix the ratio issue? :) I have this problem for a couple of months already, and can't find any solution to it :/

**Comment by saulobraine** [comment]
> > Hey everyone, I'm having this same issue.
> > Here I'm trying to extend the Classic Skin to include categories on Meta Data, well I'm using last Elementor and Elementor Pro, and this issue, unfortaly keeps.
> > > Hi @mariofox ,
> > > I've solved it by overriding the get_container_class method:
> > > ```
> > > public function get_container_class() {
> > > 	return 'elementor-has-item-ratio elementor-posts--skin-' . $this->get_id();
> > > }
> > > ```
> > 
> > 
> > This solution do not solved in completed, now here I'm have a new issue that Elementor do not include the "elementor-fit-height" on need images and some of then show wrong.
> > How to fix that?
> 
> Hey, Saulobraine,
> 
> did you manage to fix the height issue that arises after you fix the ratio issue? :) I have this problem for a couple of months already, and can't find any solution to it :/

Unfortunately not yet, I'm using just like this anyway
