### ISSUE TITLE
🔗 🚀 Feature Request: Post Types as Featured in Posts Archives (Duplicate of #4440)

### ISSUE THREAD

**Issue by josimarcordeiro** [elementor/elementor#7021]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add Videos and Audio as a highlight in Posts Archives

**Describe the solution you'd like**

In the Post settings you can define the Post Format. It can be Standard, Video, Image, Citation, and other formats.

It would be really cool if Archives of Posts was possible to define videos as a highlight in place of the image. This could be done based on the Post Format.
Examples:
1) If the Post format was set to Video then the first video of the post would be shown as Highlight in Archives Posts.

2) If the Post format was set to Image then the station image of the Post would be displayed as a highlight image.

This feature is present in the competing US Divi of Elegant Themes. See this link:
https://www.elegantthemes.com/preview/Divi/blog-masonry/

It remembers in the link above that in Archives of Posts it is possible to have Videos, Audios and Images as highlighted and this is defined simply changing of the Format of the Post in the configurations of the Own WordPress

**Comment by shilo-ey** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Josimarcsilva** [comment]
Hi

Any predictions of when this feature will be released?
The world today is driven by videos.
Post Files Page needs to be compatible with videos.
See an example below:
https://www.elegantthemes.com/preview/Divi/blog-masonry/

**Comment by Josimarcsilva** [comment]
> I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!

Hi

Any predictions of when this feature will be released?
The world today is driven by videos.
Post Files Page needs to be compatible with videos.
See an example below:
https://www.elegantthemes.com/preview/Divi/blog-masonry/

**Comment by Josimarcsilva** [comment]
> I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> 
> Thanks for your feedback!

Hi

Any predictions of when this feature will be released?
The world today is driven by videos.
Post Files Page needs to be compatible with videos.
See an example below:
https://www.elegantthemes.com/preview/Divi/blog-masonry/
