### ISSUE TITLE
"data-elementor-device-mode" issue in Safari

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#7036]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

I am using an elementorFrontend.getCurrentDeviceMode() function to get the current device mode. It's working properly on all the browsers except Safari. Am I missing something? Can you please check this issue?

## Steps to reproduce
Paste elementorFrontend.getCurrentDeviceMode(); in the console of the page.
It returns empty string on safari browser.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@sushmak02 	

It's not you, its Safari 🤪

Apparently, they don't allow CSS Pseudo properties to `head` element,
We'll take a look and find a solution.

thanks for reporting.

**Comment by sushmak02** [comment]
Thanks, @bainternet for taking a look into this issue.

I will be looking forward to hearing from you!
