### ISSUE TITLE
Meta viewport edit

### ISSUE THREAD

**Issue by stefanocavaliere** [elementor/elementor#7043]
Hello, 
is it possible to edit default meta viewport tag in Elementor? 
I would need to add user-scalable attribute to the default meta viewport. 

Anyone can help?

**Comment by shilo-ey** [comment]
Hi @stefanocavaliere 

The meta viewport tag originally comes from your theme files.

In `Canvas` & `header-footer` page templates, Elementor injects its own meta viewport tag, which for now cannot be changed, but we will consider adding an ability to change this behavior soon.

Thanks.

**Comment by stefanocavaliere** [comment]
Hello, 
I found a strange behavior of the meta viewport only on Chrome on Android devices. It seems that the lack of "user-scalable=no" makes the website zooming progressively during the navigation. In fact the more I scroll, the more the main container of the website seems to enlarge out of the screen. 

Any idea to fix this? 

Thank you!

**Comment by logancollman** [comment]
> Hello,
> I found a strange behavior of the meta viewport only on Chrome on Android devices. It seems that the lack of "user-scalable=no" makes the website zooming progressively during the navigation. In fact the more I scroll, the more the main container of the website seems to enlarge out of the screen.
> 
> Any idea to fix this?
> 
> Thank you!

Same problem brought me here as well. The functionality to change the meta tag to resolve this would be very helpful, imo.

**Comment by ALPSIT** [comment]
need a fix for this. how can we edit this so user cannot zoom website? i am using elementor pro with Hello Theme + Child
