### ISSUE TITLE
woocommerce variation options in dynamic content

### ISSUE THREAD

**Issue by knireis** [elementor/elementor#7055]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I build a site for a school for languages. I set up woocommerce for clients to subscribe to a course. Woocommerce has nice possibilities with variations. So the products are the courses. And variations are the location where the course is given and the starting day of the course.
Since it is not really a shop and clients buy only 1 product, i don't need people to login, a shopping basket, checkout page etc. So i want to create a form where clients (after selecting the desired variations) can subscribe to a course. Some woocommerce details are available as dynamic content but not the variations selected by the visitor.
 
**Describe the solution you'd like**
On the single product page i want to place a form which needs to be prefilled with the woocommerce product details, the price and title are available but not the selected variations off the product.

**Describe alternatives you've considered**
Don't know yet, maybe leave woocommerce as it is, but because people 'buy' only 1  product the checkout procedure is too complex.

**Comment by shilo-ey** [comment]
Hi @knireis 

This option is not supported, it's more of a 3rd party territory.

Thanks for the feedback.
