### ISSUE TITLE
[bug] Testimonial Carousel oval image inline on mobile

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#7058]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

![oval-image](https://user-images.githubusercontent.com/17693529/52698596-f1b14700-2f5a-11e9-8378-fe16c9e51be3.png)

## Steps to reproduce

**Testimonial Carousel** widget set layout to **Image Inline** and view it **on mobile**. When the text inside cite is too long the image becomes oval.

There're 03 solutions:
01. Enable Layout to be changed on mobile view.
02. Add dynamic option to create two different testimonials carousel (one for mobile and other for desktop/tablet)
03. Fix it with an option to set how much width the image has in comparison with the text (cite).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by black-eye** [comment]
+1
Yes, this is long-term pain.

**Comment by shilo-ey** [comment]
Thanks for reporting @Artneo7 

This will be updated in the next release.

**Comment by shilo-ey** [comment]
Hi @Artneo7 

This issue is fixed in Elementor Pro v2.4.5

Feel free to update!

thanks.
