### ISSUE TITLE
Adding Popup Exit Animations Roadmap

### ISSUE THREAD

**Issue by Worldwebscapes** [elementor/elementor#7063]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Many people including myself would like to see exit animations on popups for better UX

**Describe the solution you'd like**

Adding exit animations to the core would satisfy this need. (See Attached Image)

**Describe alternatives you've considered**

Using Jet Popups or a third party rather than Elementor to achieve this.

**Additional context**

I played around and I got this working on my testing site up to about 90%.  It looks good in the toolbar side and all seems to be in order, but does not show the closing animation once published. This is where I got to in my testing, but I am missing that last step.

![popupexitanimation](https://user-images.githubusercontent.com/7572038/52715809-64c2b980-2f6b-11e9-82ff-00324f396632.jpg)

**Comment by shilo-ey** [comment]
Hi @Worldwebscapes 

Thanks for your suggestion. 
We will look into adding it in the future releases.

Thanks.

**Comment by knireis** [comment]
+1 the popup entry can be made nice and smooth, the exit is rather sudden

**Comment by black-eye** [comment]
+1

**Comment by Ver3** [comment]
This is actually a good idea, I can see some great possibilities. Wish I could try this out as a plugin. Have you considered creating one just as a test case / to get traction and feedback?

**Comment by Worldwebscapes** [comment]
Thank you Verdi. I kinda "retired" from making any more plugins. I do not wish to get into that side of the game anymore too much support and maintaining my plugin. I was a developer for my last builder and really enjoyed just being a designer again. CrocoBlock and a few other companies also have closing animations. I feel there is already a boat on the third-party market. I would rather work on the core itself.

**Comment by Ver3** [comment]
> Thank you Verdi. I kinda "retired" from making any more plugins. I do not wish to...

Very understandable. Will check out the ones form Crocoblock, I have an account there and didn't even notice they had it (big package they offer). Cheers!

**Comment by RafaelDeJongh** [comment]
This is exactly what I was looking for, thought I was looking something over my head, but guess this is something not implemented yet.

Would really like to see this feature be added as soon as possible!

**Comment by Ver3** [comment]
I've been creating Menu's using Modals for a while now (see this old example https://lagant.co) but I love to use a few plugins as possible. As soon as Exit animations are supported I will create new menu's using the popup builder. Menu that slide in and slide out for example, instead of taking over the entire screen.

So basically I'm just saying I hope this gets added to the roadmap :-)

**Comment by ScottMadore** [comment]
I'm using the pop up for the mobile navigation menu.
Many sites have a slide left - open — slide right - closed.
Or — slide down - open — slide up closed. Check out uber.com.

This would be great to have this. It would really help.
Thanks.

**Comment by coltsman4ever** [comment]
+1 on this for sure. I'm here researching this now because I need this feature.

**Comment by VenkmanNL** [comment]
+1 for this one

**Comment by gahawkey** [comment]
+1 Really necessary for smooth exit from popups is expected as a core feature. Looking forward to this being added!

**Comment by crispee2000** [comment]
+1 -- I'm using CSS animations now which is a clunky way to have to do this.

**Comment by RafaelDeJongh** [comment]
> +1 -- I'm using CSS animations now which is a clunky way to have to do this.

What are you currently using to make it somewhat smooth then?

**Comment by crispee2000** [comment]
> > +1 -- I'm using CSS animations now which is a clunky way to have to do this.
> 
> What are you currently using to make it somewhat smooth then?

You'll have to change to your element number:

```
#elementor-popup-modal-75 {
     animation:overlay-fade 2.0s 1;
    -webkit-animation:overlay-fade 2.0s 1;
    animation-fill-mode: forwards;
    
    animation-delay:9s;
    -webkit-animation-delay:9s; /* Safari and Chrome */
    -webkit-animation-fill-mode: forwards;
	
}
```

**Comment by RafaelDeJongh** [comment]
> > > +1 -- I'm using CSS animations now which is a clunky way to have to do this.
> > 
> > 
> > What are you currently using to make it somewhat smooth then?
> 
> You'll have to change to your element number:

Alright chill thanks man!

**Comment by elasticeye** [comment]
+1 for exit animations.

**Comment by paddytakes** [comment]
I concur. Popup exit animations would be most excellent.

**Comment by laurentvergnaud** [comment]
+1

**Comment by jpgif** [comment]
+1

**Comment by jcmatoskx** [comment]
+1 It doesn't make sense to have a beautiful slide in animation on the popup if when someone closes it it weirdly pops out of existence

**Comment by yescreative** [comment]
+1

**Comment by caplang** [comment]
+1

**Comment by zrk4444** [comment]
+1

**Comment by drewclifton** [comment]
Aye, what they said.

**Comment by drewclifton** [comment]
> > > +1 -- I'm using CSS animations now which is a clunky way to have to do this.
> > 
> > 
> > What are you currently using to make it somewhat smooth then?
> 
> You'll have to change to your element number:
> 
> ```
> #elementor-popup-modal-75 {
>      animation:overlay-fade 2.0s 1;
>     -webkit-animation:overlay-fade 2.0s 1;
>     animation-fill-mode: forwards;
>     
>     animation-delay:9s;
>     -webkit-animation-delay:9s; /* Safari and Chrome */
>     -webkit-animation-fill-mode: forwards;
> 	
> }
> ```

@crispee2000 - If you don't mind, where did you place this CSS and is there anything else I need to know? I placed it in the Popup Settings > Advanced > Custom CSS area (being sure to update my ID), but alas, nothing happened. Thanks!

**Comment by crispee2000** [comment]
just in my child theme style.css file.  Nothing special otherwise.

**Comment by alulu17** [comment]
+1

**Comment by codeorlov** [comment]
+1

**Comment by pierrehansen** [comment]
+1 I'm almost begging for this feature to be added soon. I was quite amazed when I found that this isn't part of the popup's. Please! Thanks!

**Comment by pierrehansen** [comment]
All my popups do slide in from the right. Could anyone help me out with providing code for slide out when exiting? That would be great.

**Comment by codeorlov** [comment]
+1 for exit animations.

**Comment by Zexler** [comment]
+1

**Comment by bmarsilio** [comment]
+1

**Comment by pheta** [comment]
+1000 :)

**Comment by Seifertson** [comment]
+1

**Comment by Affinity-Harmonics** [comment]
NEEED!! <3

**Comment by jennareallyspeaking** [comment]
+1 Yes, please!  My menu looks so elegant...and then, it doesn't.

**Comment by erizone** [comment]
Would definitely love to see this added!

**Comment by wpturnedup** [comment]
+1

**Comment by draganche77** [comment]
+1

**Comment by millend** [comment]
+1  Much needed for UX improvement.

**Comment by ollima** [comment]
+1
Googled to see if someone had already requested this feature. Thumbs up for pop-up exit animations.

**Comment by Steriotis** [comment]
Please add exit animations!!!

**Comment by astanar01** [comment]
any way to implement this with CSS as of right now? I've tried what @crispee2000 said but it does not work ;(

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by acornavi** [comment]
Hi guys, how to smooth entrance and exit animation by shortening animation distance in fade up. down, left, the right option?
For example, instead of moving a popup window from the bottom to a setup ending popup position, how to fade the popup window and translate/animate only 30% or 15 %. That looks much more elegant.

Code to do the same for the Animations is:
@keyframes fadeInDown {
	from {
		opacity: 0;
		transform: translate3d(0, -30%, 0)
	}
	to {
		opacity: 1;
		transform: none
	}
}
@keyframes fadeInLeft {
	from {
		opacity: 0;
		transform: translate3d(-30%, 0, 0)
	}
	to {
		opacity: 1;
		transform: none
	}
}
@keyframes fadeInRight {
	from {
		opacity: 0;
		transform: translate3d(20%, 0, 0)
	}
	to {
		opacity: 1;
		transform: none
	}
}
@keyframes fadeInUp {
	from {
		opacity: 0;
		transform: translate3d(0, 30%, 0)
	}
	to {
		opacity: 1;
		transform: none
	}
}

What would be a good CSS option for my case?

Thank you!
