### ISSUE TITLE
Not working ACF Dynamic field And ACF sync in json

### ISSUE THREAD

**Issue by fhfournier** [elementor/elementor#7069]
## Prerequisites
- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

Hi,

If my ACF is not sync to my database (in json, in my theme)
![image](https://user-images.githubusercontent.com/3278753/52735984-b9c7f500-2f96-11e9-98ea-0ec278e38729.png)

I could not retrieve my field in elementor. It's said "option" and picture not showing. Look into HTML code. <img src="h"...

![image](https://user-images.githubusercontent.com/3278753/52736044-e67c0c80-2f96-11e9-94be-49880baeb47c.png)

So, if y go to ACF and sync my fields

![image](https://user-images.githubusercontent.com/3278753/52736081-feec2700-2f96-11e9-9855-d0ea5141e718.png)

![image](https://user-images.githubusercontent.com/3278753/52736142-2642f400-2f97-11e9-933f-d051b0797f8b.png)

And now, my field is there in elementor dynamic field

![image](https://user-images.githubusercontent.com/3278753/52736176-4377c280-2f97-11e9-854d-0c2c6c712735.png)

It's not supposed to be like that. ACF in json is what many people need to have ACF sync with GIT 

## Steps to reproduce
0 : have ACF field in JSON in your theme
1 : add image to elementor
2 : set Dynamic content
3  : select ACF field
4 : nothing

## Isolating the problem
- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: mariadb.org binary distribution v5.6.41-84.1
	PHP Version: 7.0.33-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://activis.devstack.fhfournier.activ.is
	Home URL: http://activis.devstack.fhfournier.activ.is
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: fr-CA
	Timezone: America/Toronto
	Debug Mode: Active

== Theme ==
	Name: Activis (2017)
	Version: 1.0.0
	Author: Activis, votre agence web
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_CA
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.10
		Author: Elliot Condon

	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com

== Log ==
	: 
Log: showing 2 of 22019-02-05 13:20:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.4.5',
)]
2019-02-05 13:22:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.3',
)]

PHP: showing 2 of 2PHP: 2019-02-05 13:21:26 [warning X 18][/var/www/activis.devstack.fhfournier.activ.is/htdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::86] Illegal string offset 'url' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-05 13:25:58 [notice X 3][/var/www/activis.devstack.fhfournier.activ.is/htdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::44] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2019-02-05 18:56:43 [error X 9][http://activis.devstack.fhfournier.activ.is/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:82347] Blocked a frame with origin \"http://activis.devstack.fhfournier.activ.is\" from accessing a cross-origin frame. 

				
</details>

**Comment by fhfournier** [comment]
Look the diference : 
Not Sync ACF : Option: Feature image (front page)
Sync ACF : Feature image (front page)

**Comment by shilo-ey** [comment]
Hi @fhfournier 

Elementor ACF Dynamic tag uses the native ACF API (`acf_get_field_groups`) to get the defined field groups.

If it's not returned by it, you should check it with ACF support.

Thanks.

**Comment by fhfournier** [comment]
ACF in son are loaded after a hook. I don't search the right hook but look

I just opened a ticket with ACF but i think you should look where the call are is from your side.

/* acf_get_field_groups (correct)
================================================== */
if ( ! function_exists( 'activis_test' ) ) :
	function activis_test() {
		$acf_groups = acf_get_field_groups();
		echo '<pre class="debug">' . print_r( $acf_groups, true ) . '</pre>';

		// retuning all array even if in json

		exit();
	}
	add_action('init', 'activis_test');
endif;


/* acf_get_field_groups (empty)
================================================== */
$acf_groups = acf_get_field_groups();
echo '<pre class="debug">' . print_r( $acf_groups, true ) . '</pre>';

// retuning empty array

exit();
