### ISSUE TITLE
Animation intensity parameter

### ISSUE THREAD

**Issue by yankiara** [elementor/elementor#7073]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor animations are too brutal and it's not possible to adjust them to make them more subtil or elegant.

**Describe the solution you'd like**
I would love to see an "intensity" parameter for animations (like the one in Divi builder), so that starting point would be closer to end point.
For instance, for a slide animation, 5% would be a few pixels (like 10px) slide-in only.

**Describe alternatives you've considered**

**Additional context**

**Comment by black-eye** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @yankiara 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by yankiara** [comment]
OK,
Could you tell us what property is used for this?
I can't find it when I check source code.
Thx.

**Comment by KingPrawnBalls** [comment]
Not sure why this issue has been closed?  Seems so fundamental to making Elementor animations useful.  Would love to see it implemented, so no more pasting custom CSS each time I want to use animations in a subtle way (i.e. every time!).

Thanks!

Related: https://github.com/elementor/elementor/issues/3598 (also closed)

**Comment by larucheweb** [comment]
I agree this feature is fundamental to make animations smoother. They are coming from such a long distance it's almost weird. It's one of the first things I noticed when I switch from Divi to Elementor.

**Comment by bilalkhan891** [comment]
If someone is still looking for a solution. You can modify the Elementor CSS properties and override the default behavior of animation.

Look into the below code for FadeIn animations. If you copy this code to your elementor CSS tab and apply the FadeIn animation you will see the difference. 

`@keyframes fadeIn1 {
  from {
    opacity: 0.5; 
  }
  to {
    opacity: 1; 
  }
}
.fadeIn {
  animation-name: fadeIn1 !important;
}


@keyframes fadeInUp1 {
  from {
    opacity: 0.5;
    transform: translate3d(0, 10%, 0);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
.fadeInUp {
  animation-name: fadeInUp1 !important;
}

@keyframes fadeInRight1{
    from{
        opacity:0.5;
        transform:translate3d(10%,0,0)
    }
    to {
        opacity:1;
        transform:none
    }
}
.fadeInRight {
    animation-name: fadeInRight1 !important; 
}


@keyframes fadeInDown1 {
  from {
    opacity: 0.5;
    transform: translate3d(0, -10%, 0);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
.fadeInDown {
  animation-name: fadeInDown1 !important;
}
@keyframes fadeInLeft1 {
  from {
    opacity: 0.5;
    transform: translate3d(-10%, 0, 0);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
.fadeInLeft {
  animation-name: fadeInLeft1 !important;
}

`

If you need further assistance, dm me.
