### ISSUE TITLE
Elementor Pro Saved templates - Missed Header & Footer

### ISSUE THREAD

**Issue by h71** [elementor/elementor#7075]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
We have created the templates of type page and section in Elementor PRO and it does list them in Saved Templates Tab as shown in screenshot 1.

Screenshot 1: http://prntscr.com/mkzq3z

After creating page & section type templates we created header and footer templates but Elementor Pro doesn't list them on Saved Templates Tab even though header & footer templates are created successfully. Please check screenshot 2 & 3 for this issue.

Screenshot 2: http://prntscr.com/mkzzxm
Screenshot 3: http://prntscr.com/mkzvga

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.34 (Win32) OpenSSL/1.1.0h PHP/7.2.8
	MySQL version: mariadb.org binary distribution v5.6.39-83.1
	PHP Version: 7.2.8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://localhost/jx
	Home URL: http://localhost/jx
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Sixteen
	Version: 1.8
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com


== Log ==
	: 
Log: showing 1 of 12019-02-12 05:14:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]

```

</details>

**Comment by shilo-ey** [comment]
Hi @h71 

Since [Elementor v2.4](https://wordpress.org/plugins/elementor/#developers) we reorganized the admin menu for Elementor settings & Template Library. 

All of the saved templates (Section, Page, Global widget) are in the "Saved Templates" section.

Header, Footer, Single, Archive, Single Product & Product Archive are under "Theme Builder" section.

Hope that solves the issue for you.

Thanks.

**Comment by h71** [comment]
You are right. But the number of published templates is confusing. It is better to change it.
Thanks for explanation.
