### ISSUE TITLE
Accordion Widget Titles Color & Typography

### ISSUE THREAD

**Issue by NerminPh** [elementor/elementor#7076]
- Trying to change the title color of the Accordion, But the changes applied to the icons without the text of the title (As the title styling applied to the <h> tag however the Accordion has <a> tag which inherit its color from the theme customizer styling (I have added color styling for all links  by using astra theme )
)

## Steps to reproduce

- Setup Astra theme 
- Add color for links 
- go to elementor builder to add accordion widget
- try to change the color of title.

![elementor-accordion](https://user-images.githubusercontent.com/5070946/52790259-cddf2580-306e-11e9-8945-6bd4f145a663.jpg)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.

It seems like your issue resolves from a setting from your theme/plugin/custom setting.

We can't replicate the described issue.

Thank

**Comment by NerminPh** [comment]
Hello,
No the settings of Elementor didn't solve the issue 

## Prerequisites
- I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Isolating the problem

- Accordion Title color Issue This bug happens with only Elementor plugin active and Elementor Pro.
- Accordion Title color Issue happens with a Astra theme when Added default colors for all links.
- I can reproduce this bug consistently using the steps:

- [ ] * Setup Astra theme
- [ ] * Add color for links
- [ ] * go to elementor builder to add accordion widget
- [ ] * try to change the color of title.

* System info.
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: (Debian) v5.5.62
	PHP Version: 7.0.32-1~dotdeb+8.1
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://cubsdev.leap13.com
	Home URL: https://cubsdev.leap13.com
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: cubs
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.8
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com

	JetMenu
		Version: 1.5.7
		Author: Zemez

	Premium Addons for Elementor
		Version: 3.0.9
		Author: Leap13

	Premium Addons PRO
		Version: 1.3.8
		Author: Leap13

	SEOPress
		Version: 3.3.8.1
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.3.6
		Author: Benjamin Denis

	WooCommerce
		Version: 3.5.4
		Author: Automattic

	WooCommerce Accept Payments
		Version: 5.2.2
		Author: Accept

	WooCommerce Wishlist Plugin
		Version: 1.9.12
		Author: TemplateInvaders

	WPC Smart Quick View for WooCommerce
		Version: 1.1.9
		Author: WPclever.net


== Log ==
	: 
Log: showing 5 of 52019-01-27 12:41:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.6',
  'to' => '2.4.4',
)]
2019-01-27 12:41:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.0',
  'to' => '2.4.2',
)]
2019-01-31 08:17:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-02-10 09:49:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-02-13 11:52:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]

PHP: showing 2 of 2PHP: 2019-02-04 07:43:11 [notice X 1][/home/189621.cloudwaysapps.com/ptznudgsum/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-14 13:59:18 [warning X 3][/home/189621.cloudwaysapps.com/ptznudgsum/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::84] sprintf(): Too few arguments [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2019-02-07 11:26:19 [error X 3][https://cubsdev.leap13.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.2:2:15986] Cannot read property \'model\' of undefined 
JS: 2019-02-14 08:51:09 [error X 1][https://cubsdev.leap13.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view24808\") has already been destroyed and cannot be used. 
JS: 2019-02-14 11:33:32 [error X 1][https://cubsdev.leap13.com/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.4.6:733:35] self.attributes[control.name].each is not a function

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by silkogelman** [comment]
Closed, but for those that don't want to go through support:
Adding Custom CSS to the Widget (or site-wide to Customizer) can probably solve this.

In our case the problem was that the title color we set for the the Accordion widget was overridden by the link color (blue) we set in Customizer, so Accordion titles where always blue regardless of the color we set in the Accordion Widget.

The CSS Fix we added to Customizer
```
/*
Elementor Accordion title color fix
*/
.elementor-tab-title a {
    color: inherit;
}
```
its based on this code:
https://wordpress.org/support/topic/color-hover-elementor-tab-title-ahover/
