### ISSUE TITLE
Dynamic Link for icon list

### ISSUE THREAD

**Issue by mikesale** [elementor/elementor#7078]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Enable dynamic links for icon list items, specifically this enables the following that is otherwise not possible: Trigger Elementor popup from list item
**Describe the solution you'd like**
The standard dynamic option for the link field in the icon list widget
**Describe alternatives you've considered**
Create a custom HTML popup and custom CSS.
**Additional context**
n/a

**Comment by shilo-ey** [comment]
Hi @mikesale 

Thanks for your feedback,

We will look into it and update this thread.

Thanks.
