### ISSUE TITLE
MultiStep form into Flipbox

### ISSUE THREAD

**Issue by Zeeshan99** [elementor/elementor#7080]
**What problem is your feature request going to solve? Please describe.**
I would like to have Multi-Step Form in FlipBox  Widget similar to like below Link 
https://www.fluenthome.com/build/

How can i do that ?

**Comment by shilo-ey** [comment]
I merged this issue with  #3911, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
