### ISSUE TITLE
Unexpected (unusable) results when using shortcode within text editor element

### ISSUE THREAD

**Issue by jpknz** [elementor/elementor#7084]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
When using a shortcode (that returns a full url) within a text editor element there are two unexpected results as described below.
1. If the shortcode is used with other text in the text editor element as part of a link then the `:` is removed from the link. e.g. `https://example.com` becomes `https//example.com` 
Things to note

- if simply used with other text (not part of a link) it will display correctly as `https://example.com`

- if the shortcode returns full content (e.g text with link) then the link will display and work correctly ("this is some returned text with the link https://example.com")

2. If just the shortcode is used in the editor element (on it's own) then the resulting display is a box displaying what appears to be an attempt to resolve the URL twice in a box (not sure if this is by design but it's a horrible looking either way). Neither of the links are the link returned from the shortcode however. See screenshot for example
![image](https://user-images.githubusercontent.com/36459775/52813975-e9f4be00-3092-11e9-80c9-220ddad62fa2.png)

e.g. returned link is `https://example.com/my-account/setup/`
A - Link goes to `https://example.com/my-account/`
B - Link goes to `https://example.com`

## Steps to reproduce

```
add_shortcode( 'returnsetuplink', 'returnsetuplink' );
function returnsetuplink( $attributes ) {
    $content = "https://example.com/my-account/setup/";
    return $content
}
```
Add a text editor element to a page. 
To reproduce 1 (above) add some text then add a link on a word and use the shortcode as the link
To reproduce 2 A & B (above) simply add the shortcode in the text element on it's own

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.23
	PHP Version: 7.0.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://***REMOVED***
	Home URL: https://***REMOVED***
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Customify
	Version: 0.2.8
	Author: WPCustomify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.4
		Author: Elementor.com

	Pluginception
		Version: 1.3
		Author: Otto

	Really Simple SSL
		Version: 3.1.3
		Author: Rogier Lankhorst, Mark Wolters

	stopAds WooCommerce Functions
		Version: 
		Author: 

	WooCommerce
		Version: 3.5.4
		Author: Automattic

	WooCommerce Blocks
		Version: 1.3.1
		Author: Automattic

	WooCommerce Services
		Version: 1.18.0
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.14
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.5.1
		Author: Prospress Inc.

	Woo Preview Emails
		Version: 1.5.0
		Author: Digamber Pradhan

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms


== Log ==
	: 
PHP: showing 2 of 2PHP: 2019-02-03 01:33:44 [notice X 2][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-08 10:18:20 [notice X 4][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/query-control/module.php::263] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 2 of 22019-02-12 18:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-12 18:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @jpknz 

Thanks for your feedback.

This behavior occurs due to the fact that the link adding module of WordPress text editor adds "http://" before the shortcode and for the matter of fact does not origins from Elementors editor.

Try recreating this behavior in Wordpress's native editor.

We can offer you to add the shortcode in the text tab in the text editor or by removing the "http://" prefix of the link before the URL in the `a` tag.

Thanks.
