### ISSUE TITLE
Popup - Close when you click on a button

### ISSUE THREAD

**Issue by JoeDarko** [elementor/elementor#7085]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

When you build a popup with any button in it, the popup should close after clicking the button. Or there should be an option to set it like that.

Let's say you have one page website, you create a popup with a button that links to some anchor. When you click the button, the page scrolls to the anchor, but the popup is still there. This makes the popups unusable for linking to anchors, which is pretty bad.

When you click a button in a popup, the popup should go away, that's obvious. When you're linking to some other page, the popup goes away. But you forgot about people linking to anchors within the same page. 

I've found other people facing the same problem. For example here: 

https://wordpress.org/support/topic/close-elementor-popup-on-button-click/

Please give us the option to close popup on button click.

**Comment by shilo-ey** [comment]
@JoeDarko 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:

```JS
jQuery( document ).ready( function( $ ) {
	$( document ).on( 'click', '.close-popup', function( event ) {
		elementorProFrontend.modules.popup.closePopup( {}, event );
	} );
} );
```
Thanks for the feedback.

**Comment by zeinnicholas** [comment]
+1

This would unlock so many options on website designing! I always tough that it was a missing opportunity to separate actions from dynamic links, and give them a special place to work besides the link. Just like you did with the form. This way we could not only close but open popups as well on actions like add-to-cart button on.click or other events, like muilti-step popups, and so forth.

**Comment by loreez** [comment]
> @JoeDarko
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:
> 
> ```js
> jQuery( document ).ready( function( $ ) {
> 	$( document ).on( 'click', '.close-popup', function( event ) {
> 		elementorProFrontend.modules.popup.closePopup( {}, event );
> 	} );
> } );
> ```
> 
> Thanks for the feedback.

Hi, I need to close a popup on click on mobile, I tried this solution and it works fine in Chrome's mobile view, but it doesn't work on an actual smartphone. I added 'touch' along with 'click' but it's still not working. Can you help me understand why? Thanks a lot!

**Comment by monkeywhovapes** [comment]
@shilo-ey , Can you explain more thoroughly about creating the class? I've added the code to the header but I am not sure how to get the onclick class set up for the button. Thanks in advance!

**Comment by shilo-ey** [comment]
[**@loreez**](https://github.com/loreez) commented on [Apr 5, 2019, 4:56 PM GMT+3](https://github.com/elementor/elementor/issues/7085#issuecomment-480284803 "2019-04-05T13:56:49Z - Replied by Github Reply Comments"):
> > @JoeDarko
> > 
> > Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> > 
> > For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:
> > 
> > ```js
> > jQuery( document ).ready( function( $ ) {
> > 	$( document ).on( 'click', '.close-popup', function( event ) {
> > 		elementorProFrontend.modules.popup.closePopup( {}, event );
> > 	} );
> > } );
> > ```
> > 
> > Thanks for the feedback.
> 
> Hi, I need to close a popup on click on mobile, I tried this solution and it works fine in Chrome's mobile view, but it doesn't work on an actual smartphone. I added 'touch' along with 'click' but it's still not working. Can you help me understand why? Thanks a lot!

Try changing "click" to "mousedown" and see if it resolved.


[**@monkeywhovapes**](https://github.com/monkeywhovapes) commented on [May 9, 2019, 2:29 AM GMT+3](https://github.com/elementor/elementor/issues/7085#issuecomment-490687858 "2019-05-08T23:29:45Z - Replied by Github Reply Comments"):
> @shilo-ey , Can you explain more thoroughly about creating the class? I've added the code to the header but I am not sure how to get the onclick class set up for the button. Thanks in advance!

Simply set a class to your button and name it `close-popup` (such as in this example).

**Comment by govusfi** [comment]
Hi, I too wish this to be a core feature soon :) Such a cool way to create mobile menus, but on a onepager the menu should close when user clicks a menu item.

**Comment by IanJSaul** [comment]
Definitely a great feature to have, simple click to close toggle.

**Comment by monkeywhovapes** [comment]
@IanJSaul , this functionality actually exists after all. It is somewhere in the popup settings, I can't remember how I got it to work.

**Comment by IanJSaul** [comment]
I'm adding the above code to my popup buttons as we speak, on the latest builds, and I'm not seeing that as an option in Popup Settings... If it is here, I'd love to use it!

**Comment by tron-git** [comment]
Hi, I have never used JS / JQuery in an Elementor page, how is this done? I tried an HTML element but I am not sure it's right, or missing some code. Any help is appreciated.

**Comment by govusfi** [comment]
> 
> 
> Hi, I have never used JS / JQuery in an Elementor page, how is this done? I tried an HTML element but I am not sure it's right, or missing some code. Any help is appreciated.

Hi, did you paste the code inside <script></script> ?

**Comment by tron-git** [comment]
That did it! I used <javascript></javascript> last time (honestly was just guessing) but yours worked perfectly! 
Thank you, and the class worked as well, I ended up setting the class on the entire menu but seems to work fine. 
Thanks for the quick help!

**Comment by tron-git** [comment]
Meant to say I used javascript last time

**Comment by monkeywhovapes** [comment]
@tron-git , @govusfi , @IanJSaul , see the following screenshot for solution on how to close popup window when clicking the button:
![image](https://user-images.githubusercontent.com/50428613/63926497-f2528c00-ca19-11e9-9f76-df318a1d67c8.png)

**Comment by giuliagasp** [comment]
Hi, how can I set "don't show again" option to my custom html button?

**Comment by mtdn-tech** [comment]
@monkeywhovapes 

My button options don't have the spanner icon to select the close popup option. I suspect this is to do with the JS code and CS class requirements. However being new I don't understand how this works in wordpress or Elementor Pro.

Can anyone explain, or point me to a good for the ill informed tutorial ?

Thanks

Matthew

**Comment by garciacrew** [comment]
> @JoeDarko
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:
> 
> ```js
> jQuery( document ).ready( function( $ ) {
> 	$( document ).on( 'click', '.close-popup', function( event ) {
> 		elementorProFrontend.modules.popup.closePopup( {}, event );
> 	} );
> } );
> ```
> 
> Thanks for the feedback.

This is not working for me for some reason.

**Comment by NickCa12** [comment]
> @tron-git , @govusfi , @IanJSaul , see the following screenshot for solution on how to close popup window when clicking the button:
> ![image](https://user-images.githubusercontent.com/50428613/63926497-f2528c00-ca19-11e9-9f76-df318a1d67c8.png)

You have to choose popup from 'dynamic' option first.

**Comment by AlexVene** [comment]
> @tron-git , @govusfi , @IanJSaul , see the following screenshot for solution on how to close popup window when clicking the button:
> ![image](https://user-images.githubusercontent.com/50428613/63926497-f2528c00-ca19-11e9-9f76-df318a1d67c8.png)

Yes, this does close the initial button for the popup, or for that matter results in the popup not opening ;) I thought the reason for this thread was instead that by clicking on a menu item in a popup that has an achor on the current page, the popup shall close.

This is indeed should be a basic feature and I am kind of disappointed that this still is not an impremented feature. I tried the Jquery above. But it did not work for me. 

Using popups for menu is a basic idea and one pager websites are very common. 

@shilo-ey what's the status for this?
Any other idea for a workaround?

**Comment by alexplayer** [comment]
Also need this feature - shocked it was not included. Please add.

**Comment by EnglishNinja** [comment]
Hi there, I had the same issue. For a workaround I set the popup to automatically close after a certain amount of time. 

<img width="1268" alt="Screenshot 2019-12-14 at 23 26 11" src="https://user-images.githubusercontent.com/58889987/70853579-1fdc1c00-1ec9-11ea-86ef-a33470723341.png">

**Comment by Fubart** [comment]
+1!!!

**Comment by maryeller** [comment]
I am facing the same "issue" when trying to create a mobile menu with the Popup but indeed, for anchors, the page scrolls but popup doesn't close.

I saw another code we can add using a HTML widget on the popup editor itself (no class/ID needed):

`<script> jQuery( document ).ready(function($){ $(document).on('click','.elementor-location-popup a', function(event){ elementorProFrontend.modules.popup.closePopup( {}, event); }) });</script>`

(credits to a Michael TH 🙃)

It worked for me, hope it works for anybody else until this option is integrated. 

Cheers!

**Comment by black-eye** [comment]
+1

**Comment by amillionbazillion** [comment]
Amazing.... Thanks @maryeller

**Comment by Mikk123** [comment]
> I am facing the same "issue" when trying to create a mobile menu with the Popup but indeed, for anchors, the page scrolls but popup doesn't close.
> 
> I saw another code we can add using a HTML widget on the popup editor itself (no class/ID needed):
> 
> `<script> jQuery( document ).ready(function($){ $(document).on('click','.elementor-location-popup a', function(event){ elementorProFrontend.modules.popup.closePopup( {}, event); }) });</script>`
> 
> (credits to a Michael TH 🙃)
> 
> It worked for me, hope it works for anybody else until this option is integrated.
> 
> Cheers!

Where do I insert the code?
I tried to insert an HTML widget into the popup, but I can't save it with the code.

**Comment by Ale-Digitale** [comment]
Please add this feature ( closing popups clicking on custom links ) in Elementor. We need it so badly !!!

**Comment by spaceneverends** [comment]
yes, please implement it.
most onepager come with anchors in the menu, and as of now, the menu won't close. Please put some importance on this feature. can't be a big thing isn't it?

**Comment by TomRaraAvis** [comment]
+1

until it becomes a built-in function, thank you so much @maryeller for sharing ... it works like a charm!

**Comment by spaceneverends** [comment]
Agree and also confirmed. Works perfect. Thank you @maryeller

Best wishes

**Comment by Kei001** [comment]
@maryeller Thank you so much !

**Comment by Kei001** [comment]
Does anyone know if this feature will be added soon ?

**Comment by portrayaloflife** [comment]
+1

**Comment by viveksingh4045** [comment]
Where I need

> @JoeDarko
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:
> 
> ```js
> jQuery( document ).ready( function( $ ) {
> 	$( document ).on( 'click', '.close-popup', function( event ) {
> 		elementorProFrontend.modules.popup.closePopup( {}, event );
> 	} );
> } );
> ```
> 
> Thanks for the feedback.
In which file I need to add this code please help

**Comment by aalandes** [comment]
+1 this is a musst

**Comment by 1302580MK** [comment]
Popup closing is currently not working for me on mobile.
Neither with the built in "close-button" nor with the close-pop-up button variation or the above mentioned scripts.

Any suggestions?

**Comment by anybany** [comment]
hey @maryeller 
> .elementor-location-popup a

is a link inside the popup itself. do you know if it is somehow possible to close the popup from outside?

for example my popup is only half height of viewport and the in the other half (on the main page, outside of the modal) is a button to close it....

**Comment by sjshaffer** [comment]
+1
Please add this capability to short codes as well.  Include option to "permanently" close pop up.  I presume this is a cookie  of some sort?  What's the javascript to set that cookie?

**Comment by eachlife** [comment]
Please add close popup when clicking on a menu item on the same page. Thanks. I'm surprised this hasn't been added yet after so many people have voted for it. More important yet, it's been a very common menu function since maybe 2-3 years? Thanks!

**Comment by DNS-13** [comment]
This is the code you need to have the popup closed when using a mobile device:

<script>
document.addEventListener('DOMContentLoaded', function() {
jQuery(function($){
$(document).on('click','.elementor-location-popup a', function(event){
elementorProFrontend.modules.popup.closePopup( {}, event);
});
});
});
</script> 

I got it from: https://elementorcodes.com/elementor-close-popup-on-click-link/

**Comment by JeejD** [comment]
Hi All, 

I found the solution to this problem. For those who are still in need for this function.

1. Add an HTML widget to the pop-up you want the code to work.
2. Copy and paste the following code into the HTML widget:

<script>
jQuery(function($){
$(document).on('click','.elementor-location-popup a', function(event){
elementorProFrontend.modules.popup.closePopup( {}, event);
});
});
</script>

I tried it and it works. Thanks to Elementorcodes.com

**Comment by alewis729** [comment]
Hey @shilo-ey, It'd be great if you guys added the possibility to pass a popup id to `closePopup()`.

Currently, the following code would close a popup only if the `event.target` element is a descendant of the popup. The popup id I passed to `closePopup()` does nothing.

```js
elementorProFrontend.modules.popup.closePopup({ id: 1234 }, event);
```

The implementation would be very similar to `showPopup(settings)`.

```js
key: "closePopup",
value: function closePopup(settings, event) {
  var popupID = jQuery(event.target).parents('[data-elementor-type="popup"]').data('elementorId');

  if(!isEmpty(settings.id)) {
    popupID = settings.id; // <--
  }

  // ...
}
```

**Comment by zachkinsey** [comment]
How do we close the popup when the element isn't a descendant of the popup?

**Comment by ajithsimon** [comment]
> I am facing the same "issue" when trying to create a mobile menu with the Popup but indeed, for anchors, the page scrolls but popup doesn't close.
> 
> I saw another code we can add using a HTML widget on the popup editor itself (no class/ID needed):
> 
> `<script> jQuery( document ).ready(function($){ $(document).on('click','.elementor-location-popup a', function(event){ elementorProFrontend.modules.popup.closePopup( {}, event); }) });</script>`
> 
> (credits to a Michael TH 🙃)
> 
> It worked for me, hope it works for anybody else until this option is integrated.
> 
> Cheers!

@maryeller  Thank you so much..

**Comment by tobiasbossin** [comment]
Hi there,

Just found this super helpful discussion but adjustments are quite hard for me because I am not a developer.
I managed with the help of your comments to close an elementor popup when I hit the 'Submit' button on a form which is nice.

On the other hand it doesn't respect the standard validation of a form field which is in the same segment. So the idea is to insert an IF condition which checks if the email field of the form is filled or not .
If email field is empty and click on submit button -> Don't do nothing, let elementor to the magic (showing email validation error message)
If email field is !empty and click on submit button -> Close the popup

Where and how do I need to adjust the code for this:

`<script>
	jQuery( document ).ready( function( $ ){
    $(document).on( 'click', '.elementor-button', function( event ) {			
		elementorProFrontend.modules.popup.closePopup( {}, event );
    } );
	});
</script>`

BG to all and everybody ;)

**Comment by anybany** [comment]
@tobiasbossin 
I didn’t test it but I think you don’t need any custom code for that anymore.
See elementor documentation about action after form submit. There is something about popups ;)

https://elementor.com/help/actions-after-submit/

**Comment by anybany** [comment]
@tobiasbossin 
Okay, got it. Again i didn't test it but try the following:

```javascript
<script> 
jQuery(document).ready(function($) {
	$("#MYFORM").bind('ajax:complete', function() {
		elementorProFrontend.modules.popup.closePopup({}, event);
	});
}); 
</script>
```
Replace #MYFORM with your forms id ;)

**Comment by tobiasbossin** [comment]
@anybany 
So I did following:
- Gave the form the name 'form01'
![image](https://user-images.githubusercontent.com/23315815/129088877-08beb35a-4050-4dca-bbb1-27d2a9474659.png)

- Replaced the old code with yours and replaced '#MYFORM' with 'form01'. I needed to replace the quotations mark with single quotes like you see in the picture below
![image](https://user-images.githubusercontent.com/23315815/129088933-b4b738a7-f7b9-4b32-baaa-4b6aed18752e.png)

- Tested then the form but it doesn'T close after hitting the subscribe button. With the code I had before in place the popup closed

Any idea what I am missing?

BG

**Comment by monkeywhovapes** [comment]
@tobiasbossin , remove line 8.

**Comment by anybany** [comment]
Yes you can remove line 8 and also your selector isnt correct. It should be #form01 in quotations. 

Maybe also this isn’t correct. I am not sure but I think elementor gives the id to a container not to the form itself. So it could be '#form01 form' or something alike.

Is your site live? Can we check it?

**Comment by tobiasbossin** [comment]
@monkeywhovapes 
Ok, this was stupid by me haha. Thank you for the hint

@anybany 
It is a staging environment. Could give you access via a temporary link.

**Comment by anybany** [comment]
@tobiasbossin okay, do you want to share the link here?

**Comment by tobiasbossin** [comment]
@anybany Sure, no problem, like I said it is a staging/environmental area
http://www.test.todoalemania.es/blog/wp-admin/?wtlwp_token=97202d2fb13c0366e8ddae3ca6401670

**Comment by anybany** [comment]
Got it!
This is the code i used. Have a look at the comments.
``` javascript
<script> 
jQuery( document ).ready( function( $ ) {
	$( document ).on( 'submit_success', function(event, response){ // when form submits successfully
		if (event.target.id == "form01"){ // if form has id form01
			elementorProFrontend.modules.popup.showPopup( { id: 2068 }, event); // show popup with ID 2068
			elementorProFrontend.modules.popup.closePopup( { id: 618 }, event); // then close popup with ID 618
		}
	});
}); 
</script>
```

Whenever the form ID or popup IDs change you have to update them in the code snippet.
And also you have to make sure that the popups display conditions are set to "entire site" or to the page/post type where you want to trigger them.

**Comment by tobiasbossin** [comment]
Yeah, tested and works nice!!!

Thanks a lot @anybany . So whenever you come to Berlin, Germany you deserve a well tasting beer. Just ping me and I will make it happen ;)

I will also soon start to deep dive a bit more into HTML, CSS, Javascript and then Jquery to get a bettter understanding of all this

**Comment by anybany** [comment]
yes i'll do that!
your're welcome ;)

**Comment by tobiasbossin** [comment]
Another question related to the origin code. As far as I understood it just works when the icon/button is before the next section, so that it checks for the next section and shows/hide it.
But is it also possible to call it from another place, e.g. a button which is further below the section? 
My idea is to use the code at several areas like buttons or icons to jump to the section (like an anchor) and execute always the same behavior (open the section when clicking on the icon/button)

**Comment by anybany** [comment]
@tobiasbossin 
Can you be more specific? Which "origin code" do you mean?
I am not sure what you mean by "section". Do you mean popups?
Opening popups by clicking on a button, link or icon is a nativ function of elementor and you can setup this in the editor without custom code.

**Comment by tizoy1984** [comment]
Hi everyone,

The solution is very simple.

1. I made a mobile menu using "Heading"
2. Then I set it up an anchor
3. I fill in the Title and paste the given code just after the title

So if the button name is "About" then I simply insert:
About<script> jQuery( document ).ready(function($){ $(document).on('click','.elementor-location-popup a', function(event){ elementorProFrontend.modules.popup.closePopup( {}, event); }) });</script>

And now it scrolls and closes ;)

**Comment by lamvh** [comment]
> @tron-git , @govusfi , @IanJSaul , see the following screenshot for solution on how to close popup window when clicking the button: ![image](https://user-images.githubusercontent.com/50428613/63926497-f2528c00-ca19-11e9-9f76-df318a1d67c8.png)

Thank you, this worked for me now.

**Comment by agusgonzalezs** [comment]
> I am facing the same "issue" when trying to create a mobile menu with the Popup but indeed, for anchors, the page scrolls but popup doesn't close.
> 
> I saw another code we can add using a HTML widget on the popup editor itself (no class/ID needed):
> 
> `<script> jQuery( document ).ready(function($){ $(document).on('click','.elementor-location-popup a', function(event){ elementorProFrontend.modules.popup.closePopup( {}, event); }) });</script>`
> 
> (credits to a Michael TH 🙃)
> 
> It worked for me, hope it works for anybody else until this option is integrated.
> 
> Cheers!

Funciona perfecto!

**Comment by claytoncout** [comment]
> <script> jQuery(function($){ $(document).on('click','.elementor-location-popup a', function(event){ elementorProFrontend.modules.popup.closePopup( {}, event); }); }); </script>
[Mensagem Original]
Senhores, eu vim do futuro , 2023 pós pandemia e no meio da guerra, para dizer que este código ainda é totalmente fucional kkkkk! 

[Mensagem traduzida]
fellas, I came from the future, 2023 post pandemic and in the middle of war, to say that this code is still fully functional, lol!

**Comment by tomherold** [comment]
Anyone knows why this code is not working? I try to close a popup when

jQuery(document).ready(function($) {
    jQuery(window).scroll(function(event) {
        if (jQuery(this).scrollTop() >= 100) {
            elementorProFrontend.modules.popup.closePopup({}, event);
        }
    });
})

**Comment by anybany** [comment]
try the following

`jQuery( document ).ready( function( $ ) {
    $( window ).scroll( function( event ) {
        if ( $( this ).scrollTop() >= 100 ) {
            elementorProFrontend.modules.popup.closePopup( {}, event );
        }
    });
})`

**Comment by tomherold** [comment]
@anybany Thank you for the quick reply. Does not work either. It must have to do with the event trigger, because with a click or mouseout event it works.

**Comment by anybany** [comment]
@tomherold do you got a live site? it would be easier to help when i can have look at it ;)

**Comment by tomherold** [comment]
Yes, please go here:
https://metawende.de/

I have a search popup that slides in when you click on the search icon in the menu bar. Currently, I have a jQuery script that hides the popup when either a certain scroll position happens, or when a user goes for 2 seconds out of the search box. All what I wanted, was to use the correct closePopup that slides it back out.

Thank you for helping! Thomas

**Comment by roenschr** [comment]
Just used maryeller's solution, thank you!
It would be very nice if this would be possible without scripting.

**Comment by xlgabriel** [comment]
Am I the only one who needs to close current popup but at the same time open another one? I literally just need that, but when I click the button, opens the next one and when I close the next one for any reason, the previous popup where I clicked is still open. Like, why? Can anyone help me please...

**Comment by EmmadSiddiqui** [comment]
> Got it! This is the code i used. Have a look at the comments.
> 
> ```js
> <script> 
> jQuery( document ).ready( function( $ ) {
> 	$( document ).on( 'submit_success', function(event, response){ // when form submits successfully
> 		if (event.target.id == "form01"){ // if form has id form01
> 			elementorProFrontend.modules.popup.showPopup( { id: 2068 }, event); // show popup with ID 2068
> 			elementorProFrontend.modules.popup.closePopup( { id: 618 }, event); // then close popup with ID 618
> 		}
> 	});
> }); 
> </script>
> ```
> 
> Whenever the form ID or popup IDs change you have to update them in the code snippet. And also you have to make sure that the popups display conditions are set to "entire site" or to the page/post type where you want to trigger them.



Hi, I saw this and it is related to my query I tried editing this code accordingly but it's not working out for me. In my case, I have one pop-up open where there is a heading and when I click on it it opens another pop-up now I have added a heading in this 2nd pop-up too and I want it to work like if someone clicks on it then this pop-up get closed and only the 1st one remains open.

**Comment by buckmanhands** [comment]
+1 for making at least a toggle that forces the popup to close on any click. Just expand the dynamic option available to us on the close button already.

**Comment by speedxcz** [comment]
+1 - I'm asking for an addition. Shilo-ey's solution is functional, but why not have it integrated directly?

**Comment by black-eye** [comment]
Hi @nicholaszein, I can see that you were the first one to comment here back in 2019. Since your voice has much higher impact inside Elementor now, could you please convince the devs to make it happen? 

Yes, there's a simple trick for it, but why not have the UI for it. After all, Elementor was made for non-coders, so why do we have to write a code for such simple feature, right?

**Comment by TomRaraAvis** [comment]
> @JoeDarko
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can set the link to the anchor and close the popup via custom JS code, ex, give your button CSS class of 'close-popup' and you can catch the click event to close the popup:
> 
> ```js
> jQuery( document ).ready( function( $ ) {
> 	$( document ).on( 'click', '.close-popup', function( event ) {
> 		elementorProFrontend.modules.popup.closePopup( {}, event );
> 	} );
> } );
> ```
> 
> Thanks for the feedback.

anything like this snippet that we can use in the new off-canvas "popup" that isn't really a popup? this snippet works great for my footer popup (actual popup), but the off-canvas element doesn't work exactly the same and i can't seem to figure out how to modify this code to get it to work.

**Comment by TomRaraAvis** [comment]
#8125 — Trigger to close popup
#27727 — Add an option to close the Off-Canvas widget when a link inside is clicked
