### ISSUE TITLE
_content_template method does not overide render method in editor

### ISSUE THREAD

**Issue by skapator** [elementor/elementor#7086]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have a custom element widget, following guides from [https://developers.elementor.com/render-widget-template/](https://developers.elementor.com/render-widget-template).

Regardless if I have a _content_template method or not, the render method always gets rendered in the editor/preview.

## Steps to reproduce

Create a custom widget following [https://developers.elementor.com/render-widget-template/](https://developers.elementor.com/render-widget-template).

Add the _content_template() method.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.0
	MySQL version: (Ubuntu) v5.7.23
	PHP Version: 7.2.11-2+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://ecan-consultants.test
	Home URL: https://ecan-consultants.test
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Entre
	Version: 2.0
	Author: Novel Digital Agency
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==

	Advanced Custom Fields PRO
		Version: 5.7.11
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 6.84
		Author: ServMask

	Better Search Replace
		Version: 1.3.2
		Author: Delicious Brains

	Debug Bar
		Version: 1.0
		Author: wordpressdotorg

	Elementor
		Version: 2.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.4
		Author: Elementor.com

	Greeklish Slugs
		Version: 1.1.0
		Author: Kostas Charalampidis

	User Role Editor
		Version: 4.49
		Author: Vladimir Garagulya

	WPML Multilingual CMS
		Version: 4.2.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.10.1
		Author: OnTheGoSystems

	WPML Widgets
		Version: 1.0.6
		Author: Jeroen Sormani

== Log ==

**Comment by shilo-ey** [comment]
@skapator 	

`_content_template()` method doesn't disable the PHP rendering compleatly.

PHP `render()` will always run on the editor initial load and on the every page load in the front end.

thanks.
