### ISSUE TITLE
Keep toolbar view to save lots of unnecessary hours, spent by clicking around.

### ISSUE THREAD

**Issue by steffanhalv** [elementor/elementor#7087]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When editing many items in a row (Ex. update font-sizes or colors) it takes very long time, because the toolbar resets every time I switch element.

Ex.

1. Click an element
2. Click advanced tab in toolbar
3. Click & choose background color
4. Click another identical element
5. Now toolbar is reset back to Layout view.

**Describe the solution you'd like**
Toggling between content, style, advanced tabs & font-style / design modal etc. should be remembered and kept if possible. At least if we are selecting an identical element.

**Describe alternatives you've considered**
None.

**Additional context**
This could save us hundreds of clicks and hours + let us focus more on design instead of spending time clicking around.

Btw. Elementor is a very nice builder 👍 :)

**Comment by black-eye** [comment]
+1 
Yes pls. This is something that drives me mad ;) Especially when editing font attributes, which are in another extra popup (and you dont see their settings right away), it becomes complete clickfest.

**Comment by lucafagherazzi** [comment]
+1

**Comment by black-eye** [comment]
Actually, exploring 2.5.0 dev branch, it seems that this feature might be coming quite soon:

![obrazek](https://user-images.githubusercontent.com/5634870/52854007-7f3c9480-311d-11e9-99e7-96320ae37e11.png)

Hopefully it is what it seems to be from the description. That would be awesome.

**Comment by shilo-ey** [comment]
Hi @steffanhalv 

Thanks for your feedback.

As @black-eye mentioned, this is actually something that is coming to Elementor v2.5.0

thanks!

**Comment by black-eye** [comment]
I've given it a try, but I realized it's not what I expected from it.
Instead of remembering the tab position in general, it remembers the last tab for the each particular widget.

See my comment on Beta Release issue: https://github.com/elementor/elementor/issues/7145#issuecomment-468925251

I found it a bit confusing...

**Comment by shilo-ey** [comment]
This feature has been added in Elementor v2.5.0

Feel free to update!
