### ISSUE TITLE
jQuery@1.12.4 ???

### ISSUE THREAD

**Issue by denis1001** [elementor/elementor#7090]
Doesn't that bother you? how to fix?
![sds](https://user-images.githubusercontent.com/1194498/52873829-9cdb1f80-3158-11e9-8614-37d1ec98076b.JPG)
![sfd](https://user-images.githubusercontent.com/1194498/52876104-db73d880-315e-11e9-8b03-0633a51bf337.JPG)

**Comment by ArekZw** [comment]
This is Wordpress dependency:

https://core.trac.wordpress.org/ticket/37110
https://wordpress.stackexchange.com/questions/244537/why-does-wordpress-use-outdated-jquery-v1-12-4

You can use:
https://wordpress.org/plugins/jquery-updater/

But read warning!

**Comment by denis1001** [comment]
Это не правда

**Comment by shilo-ey** [comment]
Hey @denis1001 

As @ArekZw mentioned and you can see by inspecting its source - the jQuery origins from the WordPress core. you can see it even if you will disable Elementor plugin.

[Read more here](https://wordpress.org/support/topic/google-lighthouse-sees-jquery-1-12-4-as-vulnerable/)

Thanks
