### ISSUE TITLE
Post template repeater

### ISSUE THREAD

**Issue by benallfree** [elementor/elementor#7091]
Is there anything like the Posts repeater widget that can use an Elementor Section template for its item layout? I want to customize how posts are shown.

For contrast, I'm not talking about ACF/Toolset/Pods repeater fields (#5979), I mean doing exactly what the Posts widget does with a custom query but supplying a template for its item repeater.

Edit: the only think I can think of now is to use Toolset Views to create a view that renders an Elementor template via shortcode in its loop.

**Comment by shilo-ey** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
