### ISSUE TITLE
Wistia Integration for LMS / Presentations

### ISSUE THREAD

**Issue by blk709** [elementor/elementor#7092]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I use Wistia for LMS on a different website using Beaver Builder. It allows segmentation into Chapters within the same video so a user can jump right to that section. Right now, it does not look like Wistia is integrated for video, at all.

**Describe the solution you'd like**

One method would be to use our Standard Embed code followed by anchor links: 

https://wistia.com/support/developers/embed-links#simple-video-replacement-example

If you would like to take a deeper dive into triggering events and player customizations, please feel free to check out our developer APIs: 
https://wistia.com/support/developers/player-api#methods

The Chapters icon on the player allows your viewers to see a full index of chapters available to view. Clicking on any of the chapters from the index (or as indicated with the small dots on the play bar) will take them to that point in the video. Here is a screenshot of what that would look like:

Feel free to check out our support documentation on implementing Chapters:
https://wistia.com/support/player/chapters

I hope this helps! Please let me know if there's anything else I can provide! 

**Describe alternatives you've considered**
Youtube and Vimeo do not allow the same control over video that Wistia allows.

**Additional context**

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can use either a Text widget which provides oEmbed support and their [official Plugin](https://wistia.com/support/integrations/wordpress) supports that. Or you can use an HTML widget and insert the embed Links code manually.

I merged this issue with  #4518, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for the feedback.
