### ISSUE TITLE
Suggested upgrade to formapi documentation

### ISSUE THREAD

**Issue by denised** [elementor/elementor#7094]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm trying to figure out how to do a custom form handler, and my attempts so far haven't worked.  Trying to understand why, as I browse documentation and this issues list, I see a lot of questions / confusion similar to mine.   User bainternet does a great job of answering questions here, but I think there could be a couple of improvements to the documentation that would help clarify things without handling them case by case.

**Describe the solution you'd like**
First of all, a single diagram of the flow of hook execution would go a *long* way to making the processing model clear.

Second, when dealing with extensions to a system like Elementor, there is always a fundamental question of whether we are talking about one-off customization to make my site run, or reusable customization that might ship in a plugin.  In the case of forms processing there are actually three choices:

1. custom hard-wired form handler in functions.php,

1. 'webhook' action-after-submit, and

1.  extension to add a new entry to the 'actions after submit' list.  

I find the questions and answers often don't specify which of 1-2-3 is under discussion.  And there really especially seems to be confusion between custom php code and the webhook action.  Adding *three* examples, one in each category, and highlighting how they are different, also help a lot.    And, with or without the diagram suggested above, clarify for each hook whether it is involved in each case.

**Describe alternatives you've considered**
I've looked for blog posts etc., that cover this in any depth (and authority), and haven't found any.  I suppose I could end up writing one myself if I end up delving far enough.

**Additional context**

**Comment by peacockesq** [comment]
I second this. 👍 When "beinternet", who I assume works for Elementor (or is just a great dude) describes their webhooks implementation as a "mess," it is a problem.

I'm driving myself insane trying to figure out how to get a simple contact form to post data to a URL. The documentation I can find are conversations here where a sample code with no elaboration or further instructions is available for pasting in a functions.php file, basically because the native webhooks feature is half-baked. 

As a non-developer, I can handle pasting something in a PHP file, but since there is no documentation on how to customize the code shared, I'm at a dead end (and I'll end up starting yet another thread on here). :-)

**Comment by bainternet** [comment]
@denised @peacockesq 	

Few clarifications:

First, I do work for Elementor. 🤪
Second, I remember saying something like:
> The current implementation of Webhooks are a little limited in the way they work. 

But they were designed with a purpose in mind and they do serve that purpose.

As for classifications of the types, In my mind there are only two kinds, which are:

* `Custom Processing` - No UI.
* `Custom Action` - With Elementor Form widget panel integration.

Both can achive all of the things you have listed above, and can be added via custom code, Plugin or even a Theme. But the main differance is that only the second has UI of configuration in the editor (like the native actions after submit).

So in regards to the classifications here on Gihub issues, unless we discussed adding a `Custom Action` after submit, its always the `Custom processing`.

Now we have updated our docs recently with a tutorial on creating a [`Custom action`](https://developers.elementor.com/forms-api/custom-form-action/) so be sure to give it a look.

@peacockesq 

I can't see where you can go wrong if you simply follow the [example in our docs](https://developers.elementor.com/forms-api/#Form_New_Record_Action):

```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'MY_FORM_NAME' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
        'body' => $fields,
    ]);
}, 10, 2 );
```
This is pretty self explanatory, and in this example we did place everything that needs changing/updating in all CAPS, but If we need to add documention on how to edit/customize an example snippet on our documention, well never see the end of it.

But I'll make sure to update it with comments in the code.

Thanks.

**Comment by peacockesq** [comment]
Well done, @bainternet. The problem, from a non-coder's perspective, is I had no idea which parts of the code had to be replaced. On the documentation page, it now says (or perhaps always said) in the coding comments:
"// Replace MY_FORM_NAME with the name you gave your form"

The beauty of elementor is that it is code free and idiot-proof. The examples you posted here previously weren't idiot-proof, haha, so I wasn't sure what needed replacing: URLs, all field names ... everything in ALL-CAPS? 

The comments in the code and "we did place everything that needs changing/updating in all CAPS" is enough for this idiot. Thank you!

**Comment by pingram3541** [comment]
At some point it was told that we could add the fields directly to the redirect url field and NOT haver to add custom code.  I can't seem to find this info.

I don't mind if I am forced to do it via code but kind of curious what happened to the simple method of adding the fields in a specific format to the redirect url so we can grab the data from the url query vars in a simple way?

**Comment by Mulli** [comment]
Unfortunately I MUST agree with the frustration.

I am using the following code (as above):
FEW issues:

1. Is handler is $ajax_handler, and why is it there if not used at all??
2. Almost all works well for me, until: wp_remote_post()
I am using $response = wp_remote_post() ; Just to see that "page not found"
Trying to get to _<MY-URL>/wp-json_
WHY this is happening??

// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'MY_FORM_NAME' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
        'body' => $fields,
    ]);
}, 10, 2 );
