### ISSUE TITLE
What's purpose of not displaying template lib for non logged in user?

### ISSUE THREAD

**Issue by webangon** [elementor/elementor#7097]
I have to show elementor template library for non logged user. But this is preventing me to do so.
`add_action( 'template_redirect', [ $this, 'block_template_frontend' ] );`

Any idea how to bypass this except editing core elementor file?

**Comment by shilo-ey** [comment]
@webangon 

You can use the native WordPress action hook (the same one elementor uses) to disable this block, for example:

```PHP
add_action( 'template_redirect', function() {
	$instance = \Elementor\Plugin::$instance->templates_manager->get_source( 'local' );
	remove_action( 'template_redirect', [ $instance, 'block_template_frontend' ] ); 
}, 9 ); // 9 so it runs before elementor's block template action
```
