### ISSUE TITLE
Form Fieldset

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#7100]
When creating a form with a larger number of fields, for example, a home address and details block and a delivery address and details block. It would be great to group form fields into formset groups to make it more easily uderstood by the person submitting the form and to better organise the data on the page.

**Comment by greendesigned** [comment]
I just went looking for this too, @nickdgreen. The best you can do is insert a 'HTML' type and add some form of headings...  

Would definitely like to see fieldsets supported.

**Comment by lior-sh** [comment]
Hi @nickdgreen,

You can use custom JS code to achieve this or use HTML field as @green… mentioned $('form').wrapInner('<fieldset />');

Thanks!
