### ISSUE TITLE
Inherit a Default (Theme) Button color

### ISSUE THREAD

**Issue by ChristianWH** [elementor/elementor#7102]
If "Disable Default Colours" is selected in Elementor's settings, the color from the theme should be taken. But from what theme component? E.g. within Astra you can define a "Theme Button"-color. But unfortunatelly Elementor doesn't respect that setting and just uses a gray background color.

Therefore one has to edit all single buttons within a website manually... :-( 

In the meantime... Any idea if I can workaround that missing feature?

**Comment by shilo-ey** [comment]
Hi @ChristianWH 

When selecting "Disable Default Colors" - all of the CSS properties are taken from your theme default CSS rules.

Elementor button widget is actually an `a` tag, and therefore inherits its properties from your theme settings for `a` element. 


You can override this by adding 
```CSS
a.elementor-button {
	background-color: #HEX_COLOR;
}
```

to your theme CSS settings.
