### ISSUE TITLE
Css entered on one widget applies to entire page

### ISSUE THREAD

**Issue by Elementalel** [elementor/elementor#7107]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When I enter a piece of CSS code on a specific widget, all the widgets of said page are affected. For example, if I write the  following code within the column widget's custom CSS:

a:link {color:#3fff00;font-weight: bold;}

All other widgets will be affected.

## Steps to reproduce

1. Create a Nav Menu and a column. Write something in it and include a link.

2. Copy a:link {color:#3fff00;font-weight: bold;} in custom css of the column widget only

3. See the Nav Menu also being affected by above piece of code

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @Elementalel 

You sure can target the specific element you're adding the CSS code to.

Simply use `selector` before the property you want to add. ex:

```CSS
selector a:link {
	color:#3fff00;
	font-weight: bold;
}
```

Thanks.

**Comment by Elementalel** [comment]
Wow it was that simple. Thank you very much!
