### ISSUE TITLE
Improve Elementor Custom fonts import

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#7114]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

- Export WordPress website with Elementor and Custom fonts through WordPress integrated export function.
- Import on another WordPress website through this exported file requires Custom fonts set in Elementor in source WordPress website. If it is not set in Elementor at source WordPress website, then import of the Custom fonts not fill in Elementor in target WordPress website.
- But this requirement is unnecessary, because all informations are contained in exported file.
- This works for all Elementor templates of the source WordPress website. They are contained in this exported file. Why not Custom fonts?
- For import is sufficient if font files are present in Media library of the source WordPress website.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
