### ISSUE TITLE
Export/import Default Colors, Default Fonts and Color Picker

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#7115]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Include Default Colors, Default Fonts and Color Picker with the Elementor in the integrated WordPress export/import.

**Comment by heyfletch** [comment]
+1 Would be very helpful.

**Comment by MichaelDarko** [comment]
I really hope this comes as soon as possible. Releasing the functionality of global values without being able to export/import them is not great.

**Comment by gsusI** [comment]
Got to agree on this one. Being deployments one of the weaknesses of wordpress and where things can get pretty complex, this functionality is a must.

FYI, as other users here -I'm sure- I hold a number of Elementor Pro licenses for my websites.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #4417, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by ahmetsali** [comment]
+1 also mentioned here;

https://github.com/elementor/elementor/issues/12340

**Comment by VoidZA** [comment]
For anyone looking to do this sort of manually, here is how to do it (its pretty straight forward):
On the source site, find your default-kit post id, easiest place to find it is under your Elementor templates, on the right it will show the shortcode for each template with the id in it, something like: [elementor-template id="**3438**"]

Now go to your `wp_postmeta` table in your database, and find/search for the fields with `post_id` = the id you found for default kit. You will find a couple of fields. Now do the same for your destination site, note that the default kit will have a different id on the destination. You can use this SQL query to find the fields you are looking for, just replace the id:
`"SELECT * FROM wp_postmeta WHERE post_id = YOUR_ID_HERE"`

Then simply copy the field values (`meta_value`) from the source to the destination in your databases.
In my case I only copied the `_elementor_page_settings` and `_elementor_css` to get my colors and fonts cloned.

Remember to refresh any open editor pages for it to sync.
