### ISSUE TITLE
Elementor Plugin Dev: How to hook to "Global Settings" menu

### ISSUE THREAD

**Issue by djekanovic** [elementor/elementor#7118]
Hey,

So i wanna create new plugin after some time, and i cant find any working hook that enables me to create additional settings - controls in "Global Settings" menu. Is it even possible? 

Thank you!
![2019-02-18 6](https://user-images.githubusercontent.com/23662556/52978435-973c3e80-33d1-11e9-886e-2b5df080debf.png)

**Comment by bainternet** [comment]
@djekanovic 

Currently, there is no easy way or a valid API to do it with, and we have plans to overwrite this area anyway.


thanks.
