### ISSUE TITLE
Woocommerce checkout

### ISSUE THREAD

**Issue by jordanancel** [elementor/elementor#7119]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The native woo pages for Cart & Checkout look terrible and can't be styled with Elementor
**Describe the solution you'd like**
Please add design functionality to style woocommerce cart & checkout pages, including styling all fields, layout, colors, etc. in order to make the cart and checkout pages look nice in any theme.

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
I merged this issue with #5383, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
