### ISSUE TITLE
Ninja forms not loading in Popup

### ISSUE THREAD

**Issue by rlaurent** [elementor/elementor#7124]
Hello guys,

I've tried to insert a Ninjaforms form inside a popup but it's not working. I've an error in my console and the form is not loading.

```
front-end-deps.js?ver=3.4.4:20 Uncaught constructor message: "An "el" .nf-before-form must exist in DOM" 
```

**Comment by shilo-ey** [comment]
Hi @rlaurent 
Thanks for reporting,

This error is rooted from Ninja Forms plugin. 
Please contact their support and ask them for guidance.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by Alexmp4** [comment]
Hi, any news on this issue... I get the same one :/

**Comment by rlaurent** [comment]
Il think the probleme is that elementor popup load the content via ajax and the ninja forms too. Use jetpopup and disabling Ajax content loading option (in jetpopup) works for me.

**Comment by Alexmp4** [comment]
Right it works better ;) Thanks

**Comment by lacccci** [comment]
> Il think the probleme is that elementor popup load the content via ajax and the ninja forms too. Use jetpopup and disabling Ajax content loading option (in jetpopup) works for me.

The problem is my company bought $199 Elementor Pro for a reason, and I do not want to pay more $15 for a plugin to do what Elementor should(?) do. 
Ninja form support redirect to Elementor support, so I'm afraid nobody are working on this issue.

**Comment by Pikamander2** [comment]
So to summarize: Ninja Forms [blames this on Elementor](https://wordpress.org/support/topic/form-not-load-on-elementor-popup-shortcode/) and Elementor blames this on Ninja Forms.

Great...

**Comment by murcoder** [comment]
Did someone fix this? My ninja formular is still not loading on the elementor popup.

**Comment by slopeside-graham** [comment]
This is still an issue. Ninja forms work fine everywhere except in Elementor Popups. Seems like an Elementor issue.

**Comment by pitchpublications** [comment]
Same issue........

**Comment by Yop-La** [comment]
same issue for me

**Comment by Yop-La** [comment]
![image](https://user-images.githubusercontent.com/10812063/110090305-6bf9d180-7d97-11eb-8e26-a26a46397a29.png)

Ninja form is not loading on my elementor popup ...

**Comment by Jon-Burnett** [comment]
Same - Error: An "el" undefined must exist in DOM 

Very annoying!

**Comment by tonypartridge** [comment]
Still nothing? Seriously... It's a relatively simple fix from a codebase, elementor just needs to initialise the elements into the dom because they do not it's not initialisable.

**Comment by meghanboyd** [comment]
Same issue here, we definitely would not have bought Elementor Pro if we knew there would be so many issues. Please fix !

**Comment by mohsinsarvani** [comment]
still facing same issue

**Comment by christianmagill** [comment]
Facing this issue sporadically in bricks builder as well.

**Comment by uadhikari-enee** [comment]
I found a workaround for this. I added a section in Elementor Header with a Lightbox/Modal. In the content for the modal, I added the ninja form shortcode. This did the trick for me. However, doing the same in Footer did not work as intended.

**Comment by LMcGhee-zz** [comment]
Hi Elementor!

I just contacted Ninja Forms support about this issue and they said that they have tried to get Elementor to fix this issue many times and it's in their hands. I think both parties should work together to get this fixed as a lot of developers use Elementor Popups for newsletter sign up forms. Both the Wordpress Ninja Form Element and The Plus Element do the same thing as you can see from the screenshot below.

![ninja-form-x-elementor-enewsletter-popup](https://github.com/user-attachments/assets/aed51151-e9ba-4f08-9740-e25e23d6b96f)

Please fix ASAP! 

Thank you :)

**Comment by Jon-Burnett** [comment]
Nothing wrong with Ninja forms, it's the way elementor loads the popup. Has anyone tried it with the new off-canvas widget? I suspect putting that in the site header might work.

**Comment by LMcGhee-zz** [comment]
I am literally attempting this now.

**Comment by LMcGhee-zz** [comment]
> Nothing wrong with Ninja forms, it's the way elementor loads the popup. Has anyone tried it with the new off-canvas widget? I suspect putting that in the site header might work.

Great minds think alike as I was trying it as I saw your comment.... and I have success with the Off-Canvas Widget so that's a great solution.

Cheers!

**Comment by Jon-Burnett** [comment]
Ah good stuff. played with it the other day and simple to make it look like a popup in the middle of the screen etc. Will remember it for next time!
