### ISSUE TITLE
custom filter to present the custom templates 

### ISSUE THREAD

**Issue by simopetrelli** [elementor/elementor#7126]
Hi Elementor team,

I'm looking for a method to improve the presentation of custom templates. my goal is to be able to give him a cover image and the possibility to see a preview.
I discovered that the jupiter theme uses what I'm looking for (see screenshots https://prnt.sc/mn3s9v)

- Is it possible to insert a custom filter to present the custom templates as in the Jupiter theme?
-  Is there a documentation or link tutorial explaining how to insert this filter?
- Can you explain to me if there is a method to recall the templates from the theme and not from the outside?

Thanks a lot for any info.

**Comment by shilo-ey** [comment]
Hi @simopetrelli 

There is no API for that, I guess Jupiter used kind of a "Hack" to place it there.

thanks.
