### ISSUE TITLE
Elementor Posts Widget - First Post Blank

### ISSUE THREAD

**Issue by jxsn** [elementor/elementor#7128]
Hey there,

I have Elementor Pro, the newest version (2.4.5) and this happens to my posts widget
![capture](https://user-images.githubusercontent.com/32853223/53053931-1a799500-34a3-11e9-8003-23644c866757.PNG) 

The space for the first post is empty and I have set 4 colums and 8 posts, and there are 3 lines for the post. Why is the widget doing that, I even reinstalled elementor and  checked for new updates, nothing works.
 
Thank you very much for your help

**Comment by shilo-ey** [comment]
Hi @jxsn 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.

We simply cannot replicate this issue.

**Comment by CamColson** [comment]
Hi shilo-ey and jxsn, I am having this same issue and wonder if you found a resolution? Any advice welcome.
<img width="1174" alt="Screen Shot 2022-02-08 at 10 15 20 pm" src="https://user-images.githubusercontent.com/99256102/152976491-25560148-f299-4f3f-af87-da0fded17031.png">

**Comment by jxsn** [comment]
@CamColson Hey there! I'm sorry but i dont have a solution! Its quite some time ago, but I think I used different post tools from other plugins like 'unlimited elements' or 'premium addons for elementor' (i think they're named). These also have post widgets I think! Just search for 'elementor' in the install plugins tab in wordpress and you'll find many addon plugins for elementor. Try them out! 
Hope this helps! 
Jxsn

**Comment by CamColson** [comment]
@jxsn thanks for the quick response. Yeah I'm struggling to work this out and yours was the only instance I could find. Was about to look at third party addons, thanks for the tip.
Cheers!
