### ISSUE TITLE
Section Fixed Height

### ISSUE THREAD

**Issue by DIntriglia** [elementor/elementor#7129]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

There is only a fit to screen and min height option for sections. Most of the time this works fine, but for overlapping elements, like on my header on https://estus.co, fixed-height is required as min height simply expands to fit all of the elements, even though the element is supposed to be outside of the block. 

I created a Pull Request (#5434) to make this implementation that much easier. Figured I’d submit an issue to start a commentary and explain my reasoning.

## Steps to reproduce

Try to recreate my header from https://Estus.co without using the custom CSS block. While the custom css block does work, responsive Height changes, which Elementor handles amazingly no longer is easy. 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
```
</details>

**Comment by arielk** [comment]
Hi @DIntriglia, 

Sorry for the late reply, but we are not going to merge this request into the plugin because we are going to switch to the new container method in the future. For now the solution I would suggest is to use custom CSS to solve this problem.

So thank you very much for your comment and contribution! Much appreciated.
