### ISSUE TITLE
Yoast SEO integration

### ISSUE THREAD

**Issue by simonemontrucchio** [elementor/elementor#7130]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor states to "work great with Yoast SEO plugin" https://docs.elementor.com/article/126-elementor-related-plugins
Instead, in the backend the text highlight feature doesn't work since Elementor "hide" the content
![screenshot1](https://user-images.githubusercontent.com/12949275/53074850-17ef5d80-34ec-11e9-93bb-f1299c5eae66.jpg)

**Describe the solution you'd like**
The BEST solution would be to have the Yoast SEO metabox in the frontend Elementor editor, maybe like the Navigator floating widget.
Otherwise, at least the possibility to see content in the backend to see highlighted text in backend.

**Describe alternatives you've considered**
I tried click on "Back to WordPress Editor" in backend: it let me show the content and text highlight but all the wonderful layout created with Elementor breaks up.

**Additional context**
 A visual page builde should help people making their job easier, not harder.

**Comment by Raza83** [comment]
![capture](https://user-images.githubusercontent.com/26858890/53109874-a7802500-355b-11e9-845e-9ce45c1b2c0c.PNG)

**Comment by Raza83** [comment]
here is what is see when i open the page

**Comment by Raza83** [comment]
As the js is not loading.
![capture-2](https://user-images.githubusercontent.com/26858890/53110085-0e9dd980-355c-11e9-8dd4-acae21f3db29.PNG)

**Comment by JosiahCarberry** [comment]
I share the specific request that Elementor display the highlighting that Yoast proposes as part of its Readability Analysis. I do not share the idea of reverting to the Wordpress editor in order to be able to see that highlighting, which is not useful and is potentially destructive. Furthermore, visualizing  the Yoast Metabox in Elementor editor is an entirely separate issue, AFAICS. It has nothing to do with the very significant advantage to a post's author of easily viewing the text extracts that lower readability.

**Comment by ShadowXVII** [comment]
I was just searching about to post about this. I use Yoast also, and find the disconnect between the Wordpress and Elementor editor a bit cumbersome.

With Gutenberg the Yoast plugin has its own "plugin" section.
Maybe the wider solution would be to allow those gutenberg "plugins" to show in the elementor editor?

![image](https://user-images.githubusercontent.com/446329/54409496-1dcb0e00-473b-11e9-88b5-fccd9bef27ef.png)

**Comment by JosiahCarberry** [comment]
I wouldn't mind being able to temporarily open from within the Elementor editing page a panel giving access to all those controls from WordPress and plugins like Yoast. I would not want such a panel to be open permanently, because it would take up too much space that I prefer to use for editing.
But this is a different issue from the one raised above. Independently of how and where you can view the Yoast plugin controls, the control to display readibility issues is simply not working in the Elementor editor.

**Comment by DigiCooke** [comment]
Would be better if there were actual tools allowing you to do SEO tasks via Elementor. I could envision SEO widgets even that would allow you to update things like metadata, keywords, etc.., which Elementor then adds to the appropriate sections of the code. It could also make suggestions for SEO content based on what you already have on the page or what you could add based on what you intend the page/site to be about.

**Comment by physiostasis** [comment]
You guys at Elementor are awesome! I am sure you can find a creative way to integrate Yoast SEO checker with Elementor. I try to go back and forth between the WP editor and Elementor, but it doesn't work so well. There is a guy with a YouTube video with great suggestions if you search "elementor yoast" and I hope you guys figure it out. Helping us rank high in SEO will make us more and more happy! haha Thanks!

**Comment by JosiahCarberry** [comment]
I would think that this functionality would require the editors of Yoast and Elementor to work together. I hope they decide to do so.

**Comment by verak1** [comment]
I absolutely add my voice to this request.
Jumping back and forth from Elementor to Yoast (or, most probably, any other SEO plugin) is just a colossal waste of time, and I would say that ANYONE using Elementor AND an SEO plugin is faced with this.
Just as there are widgets, for example, for styling Caldera forms in Elementor - so there should be some sort of a widget, or tab, some sort of extension which one installs when one chooses the SEO plugin, and which would allow one to work on his page/post in a flowing manner, doing everything in the same editor.
Until then, Elementor just cannot claim it "works great with Yoast" - for it doesn't. It makes our heads spin. Or it makes us work with both editors open for the same page at once. Either way is not what Elementor set out to so.
I do believe the Elementor creators are awesome, came up with a great tool and are improving it all the time, so they must come to understand that this is not "an nice to have improvement" - but a burning necessity, an (understandable) omission which MUST be remedied.
Hope you make this a priority ASAP.
Thank you.

**Comment by the-gap-decaders** [comment]
Absolutely agree this needs a fix.  Currently I have to edit with both screens open as I am unable to see highlighted text in either Elementor or Wordpress edit mode.  I am a new blogger and need the highlights to help me understand where my writing needs to improve; at the moment I am having to guess.  This is really frustrating and putting me off using Elementor as I think the writing is more important than the visuals.

**Comment by delphilife** [comment]
It's beyond me why it would be so complicated for Elementor to move only formatted text between Elementor and the WP Editor, where Yoast SEO can be fully utilized. When I say "fully utilized," I mean having the ability to use the "Highlight the result in Text" - image below. That is the least Elementor could do... Adding a yoast widget in Elementor would be great but I understand the work that might take.

![image](https://user-images.githubusercontent.com/42851817/57252086-9302e300-7008-11e9-893d-d2c75a158652.png)

**Comment by velajrg** [comment]
I'm also stuck with this issue. A few days ago I read in a Youtube video one possible solution to this problem but I haven't been able to reproduce it. I leave it here:

"Could you build your pages and post templates in Elementor's theme builder first then manage your dynamic content the old fashioned way on WordPress back end (with the classic editor)? obviously this wont work with static pages with fancy designs etc but for the day to day blog posts etc this should work right?﻿"

Can anyone explain this please?

**Comment by JosiahCarberry** [comment]
I suppose what they are saying is create your post with Elementor, but don't use any fancy widgets. Then revert to the Classic editor and check the text with Yoast and make any updates you want. But you don't see any of those updates in the Elementor revisions afterwards. So you might just as well stay with Gutenburg for the whole process. Not much of a solution, so far as I can see.

**Comment by LogoLogics2** [comment]
Yes, a workaround is to start a new page without even publishing it, and add desired text using the default WordPress editor. When all is good for SEO, copy paste that text in the real page where you use Elementor.

**Comment by verak1** [comment]
I'm sorry, but THAT is purely idiotic.
Going back and forth is the only option. I usually have the page open in both the Elementor Edit view AND in the regular Edit view, to update after the corrections are placed. 
It is extremely awkward and a huge waste of time, but yes, ultimately it works. 
It MUST be addressed and solved.

**Comment by LogoLogics2** [comment]
Charming as ever!

**Comment by verak1** [comment]
Stupid as ever... :)

**Comment by encreinformatique** [comment]
I add my voice to the concern.

The only solution I found to work is migrating the posts to Gutenberg but it is not quite good as it adds a lot of work to migrate all. The Yoast SEO missing integration would help a lot not to migrate every post.

PS : thank you both @verak1 and @LogoLogics2 for having pointed this current Github issue in the Wordpress plugin support.

**Comment by Marksson** [comment]
Hoping that the people of Elementor will read this and feel the urgency, I am adding my vote too for this.

**Comment by Kevinsmak** [comment]
I am very surprised these two features don't work together correctly.  Please fix this and make it so.  Just bought Yoast and was considering elementor.  Now wondering if I should refund Yoast.

**Comment by UnknownGuy123** [comment]
I'm an Elementor Pro user and this would definitely be a nice extra feature since right now I cannot read Yoast suggestions to me

**Comment by EricJammin** [comment]
+1 for this feature.

Totally understand the complexities involved, but it would be great if there is a way. 

I hope everyone commenting here is also doing the same for the feature request with yoast...

**Comment by bgkoss** [comment]
+1 for this feature

**Comment by drawcard** [comment]
Just had a client ask me why nothing happened when they tried to click on readability suggestions on the blogpost.

@LogoLogics2 solutions works but isn't practical for dozens of blog posts. My client tried switching back to classic editor mode as a workaround, but Gutenberg now features a 'classic editor' block that doesn't work with Yoast's highlighters either. You have to cut and paste the text into a blank Gutenberg post (and do right click -> Paste and match existing style to avoid using classic editor blocks.)

**Comment by hackernewbie** [comment]
+1 to the feature request.
That would save a ton of time (and frustration)!

**Comment by thomasbonsirven** [comment]
+1 too, for the feature request

**Comment by millneckinternational** [comment]
+1 for the feature request. Having two windows open is a workaround but not the best solution. It would make better sense for Yoast to be available through Elementor front end editing as well

**Comment by josabidafra** [comment]
+1000000. 
We just had a lovely designer update our site, only to realize that we now need to create the whole thing in the main WP text editor and THEN paste it to Elementor- please help! Thanks lovely Elementor peeps!!!!

**Comment by surajv** [comment]
Hi @simonemontrucchio, @Raza83, @JosiahCarberry, @ShadowXVII, @DigiCooke, @physiostasis, @verak1, @the-gap-decaders, @delphilife, @velajrg, @LogoLogics2, @encreinformatique, @Marksson, @Kevinsmak, @TimSun-Code, @EricJammin, @bgkoss, @drawcard, @hackernewbie, @thomasbonsirven, @millneckinternational, @josabidafra
I'm sure this is not the type of reply you were expecting, but we at Rank Math launched an update that integrates the SEO panel directly inside Elementor's editor.

**You can read more about that here:**
https://rankmath.com/blog/elementor-seo/
Every single task related to SEO can now be handled without leaving the editing screen of Elementor.
Also, the role manager features works there as well, so one can restrict the type of SEO settings one can make.

Also, we have a one-click importer from other SEO plugins to Rank Math.

You can check the detailed feature list on this page:
https://rankmath.com/wordpress/plugin/seo-suite/

**The plugin is 100% FREE!**

**Comment by hackernewbie** [comment]
I have already been trying RankMath on one of my client-websites and have been pretty happy so far.

Good luck @surajv !

**Comment by JosiahCarberry** [comment]
I think the point being raised is that integration between Yoast and Elementor is technically feasible on the Yoast side. I _don't know_ if it is feasible or even desirable to change Elementor to accommodate Yoast, or whether the Yoast and Elementor people should be talking with each other to find an optimal solution.
I do hope this thread does not degenerate into a comparison of Yoast to other products, which would be misplaced here.
But it would be nice to get a position statement from Elementor.

**Comment by simonemontrucchio** [comment]
> Hi @simonemontrucchio, @Raza83, @JosiahCarberry, @ShadowXVII, @DigiCooke, @physiostasis, @verak1, @the-gap-decaders, @delphilife, @velajrg, @LogoLogics2, @encreinformatique, @Marksson, @Kevinsmak, @TimSun-Code, @EricJammin, @bgkoss, @drawcard, @hackernewbie, @thomasbonsirven, @millneckinternational, @josabidafra
> I'm sure this is not the type of reply you were expecting, but we at Rank Math launched an update that integrates the SEO panel directly inside Elementor's editor.
> 
> **You can read more about that here:**
> https://rankmath.com/blog/elementor-seo/
> Every single task related to SEO can now be handled without leaving the editing screen of Elementor.
> Also, the role manager features works there as well, so one can restrict the type of SEO settings one can make.
> 
> Also, we have a one-click importer from other SEO plugins to Rank Math.
> 
> You can check the detailed feature list on this page:
> https://rankmath.com/wordpress/plugin/seo-suite/
> 
> **The plugin is 100% FREE!**

Oh My God!

This is astonishing amazing!!!

**Comment by 9doors** [comment]
another +1 for the feature request.
not having the integration between Yoast and Elementor just makes me want to shop around for other options for both Page Builder and SEO.
Oh and I emailed Yoast about the eye marker not working in the page builder & they just said that "We understand this is not the desired option, but unfortunately, it is not something we can fix on our end." so....

**Comment by Skillstekerp** [comment]
Absolutely agree. No doubt Elementor is a great tool and is very user-friendly. But its integration with Yoast is really difficult to work upon. I write for [Skillstek Blog](https://skillstek.com/blog). I used to edit a lot with Yoast SEO analysis results. But it becomes nearly impossible for me to edit and improve in elementary as I cannot see the highlights (eye) in Elementor editor. It would be great if Elemrntor adds a Yoast panel in its tools panel to make it easier to work for people like me.
![image](https://user-images.githubusercontent.com/60967696/80341443-18b61900-8880-11ea-93e3-64cf677262c2.png)

**Comment by Hameedhudeen** [comment]
I'm surprised to see that this has not been addressed for over an year.

**Comment by LogoLogics2** [comment]
Me too, however, there is a fairly new kid in town: [](https://rankmath.com/wordpress/plugin/seo-suite/), that integrates very well with Elementor.

I tested this one and love it. Converting my 60+ sites now from Yoast to this one. Converting is a breeze, it imports all from Yoast with a few clicks.

**Comment by giobi** [comment]
> I'm surprised to see that this has not been addressed for over an year.

Same here.. I'd pay for this

**Comment by drawcard** [comment]
Sounds like an opportunity for someone to develop a 3rd party plugin to facilitate this.

**Comment by arenis** [comment]
same problem problem her how long we must wait ?

**Comment by jarle0db** [comment]
> Sounds like an opportunity for someone to develop a 3rd party plugin to facilitate this.
> 
> Edit: I see someone already has 👍

Would you have a link to the integration? Did some Googling but couldn't find it.

**Comment by jarle0db** [comment]
Still crickets on Elementor and Yoast SEO integration, I see. Very disappointing.

**Comment by LogoLogics2** [comment]
@jarle0db,
 
> > Sounds like an opportunity for someone to develop a 3rd party plugin to facilitate this.
> > Edit: I see someone already has 👍
> 
> Would you have a link to the integration? Did some Googling but couldn't find it.

Sure here it is: [](https://wordpress.org/plugins/seo-by-rank-math/)
Works great with Elementor, I said goodbye to Yoast and never looked back! ;-)

**Comment by jarle0db** [comment]
> Sure here it is: https://wordpress.org/plugins/seo-by-rank-math/
> Works great with Elementor, I said goodbye to Yoast and never looked back! ;-)

Hehe, so solution to Yoast integration with Elementor is getting rid of Yoast?

Not sure I am happy with that solution, but it is an option.

**Comment by LogoLogics2** [comment]
> > Sure here it is: https://wordpress.org/plugins/seo-by-rank-math/
> > Works great with Elementor, I said goodbye to Yoast and never looked back! ;-)
> 
> Hehe, so solution to Yoast integration with Elementor is getting rid of Yoast?
> 
> Not sure I am happy with that solution, but it is an option.

@jarle0db,

That is totally up to you of course, you can wait this out and hope Elementor integrates with Yoast, but that question is her for a long time........... I have been using Yoast for about 12 years, but if I have to chose between Yoast and Elementor, Elementor wins.

And switching is a breeze, with the build in migration tool in Rank Math.

**Comment by JosiahCarberry** [comment]
In my view, the place where good integration would really pay off would be in the editing of the document to improve readability. This is a highly interactive task involving going back and forth between the suggestions made by Yoast and the editing of the widgets themselves. I am thinking of things like shortening sentences, going from passive to active voice, etc.
Updating all the other aspects of SEO, such as the images, the snippets, the key words, etc., is really  a minor inconvenience by comparison.
I think this is important to mention because the solution to the problem proposed by some, namely, to use a different SEO plugin, does _not_ solve the problem at all. Whereas Yoast will show you exactly where the readability issue occurs, other SEO plugins merely indicate that there is an issue but give no indication of where the issue is. So, the integration with Elementor is of minor value, IMHO.

**Comment by wp-seopress** [comment]
SEOPress' users will be happy to know that we provide an Elementor integration since few weeks!
Learn more here: https://www.seopress.org/blog/elementor-integration-semi-automatic-redirections-seopress-4-0/
<img width="494" alt="elementor-integration-seopress-google-preview" src="https://user-images.githubusercontent.com/30056254/94367626-382bc900-00e0-11eb-908f-70c4ada14c12.png">
And it's free!

**Comment by shilo-ey** [comment]
Hey all, I'm happy to announce that Elementor partnered with Yoast to provide an extensive integration in Elementor editor. 
In order to get the new feature please make sure you are using Yoast v15.4 and Elementor v3.0.14 (minimum version requirement).

Thanks for sharing this request.

**Comment by Skillstekerp** [comment]
Yes, I am using the updated versions as you mentioned.  Still, Problem
persists. please see the image below.

[image: image.png]
