### ISSUE TITLE
Elementor Ignores Display Conditions 

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#7132]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor ignores the display conditions set for Custom Single post pages built using the theme builder when used on Custom Posts created with Toolset.

## Steps to reproduce

I have created a custom post type in Toolset. 
I have created a "persona" page under "Templates > Theme Builder" within Elementor. 
For the "Display Conditions" I have "Include Personas All" - Personas being the custom post type (Personas/Persona/persona).
I already have a custom template defined in Toolset which would serve as the page "content". 

My page template consists of a menu and the content of the post. 

Everything works fine when I edit the template within Elementor, but the actual pages do not load the theme I defined. IE Elementor ignores the "Where do you want to display your single?" options. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
  (need toolset types and views active to create the custom post and post templates)
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: 
	Home URL: 
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name:Elementor Hello Master
	Parent Theme Version: 1.1.0
	Parent Theme Author: 

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Dynamic Animations for Elementor
		Version: 1.0.0
		Author: Dynamic.ooo

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.10
		Author: Namogo

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.6
		Author: rocketgenius

	Logged-in-only
		Version: 2.0.0
		Author: Ralf Wiechers

	Mailgun
		Version: 1.7
		Author: Mailgun

	Toolset Access
		Version: 2.6.2
		Author: OnTheGoSystems

	Toolset Forms
		Version: 2.3
		Author: OnTheGoSystems

	Toolset Types
		Version: 3.2.6
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.7.3
		Author: OnTheGoSystems

	Ultimate Addons for Elementor
		Version: 1.9.1
		Author: Brainstorm Force

== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.8
		Author: Janis Elsts

	Cache Enabler
		Version: 1.3.3
		Author: KeyCDN

	Defender Pro
		Version: 2.1.1
		Author: WPMU DEV
	Safe SVG
		Version: 1.9.3
		Author: Daryll Doyle

	Smush Pro
		Version: 3.1.1
		Author: WPMU DEV

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	WPMU DEV Dashboard
		Version: 4.6
		Author: WPMU DEV

	WP Ultimo
		Version: 1.9.7
		Author: Arindo Duque - NextPress

== Log ==
	: <table><thead><th>Log: showing 8 of 8</th></thead><tbody class="elementor-log-entries"><tr><td>2019-01-23 12:02:43 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.1',
  'to' => '2.4.3',
)]</td></tr><tr><td>2019-01-23 12:02:43 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]</td></tr><tr><td>2019-01-28 05:31:00 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]</td></tr><tr><td>2019-01-28 05:31:00 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.2',
)]</td></tr><tr><td>2019-02-06 00:14:52 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]</td></tr><tr><td>2019-02-06 00:14:52 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]</td></tr><tr><td>2019-02-20 01:30:49 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.5',
  'to' => '2.4.7',
)]</td></tr><tr><td>2019-02-20 01:30:49 [info] <strong>Elementor data updater process has been completed.</strong> [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.5',
)]</td></tr></tbody></table><table><thead><th>PHP: showing 1 of 1</th></thead><tbody class="elementor-log-entries"><tr><td>PHP: 2019-01-25 20:14:37 [notice X 3][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php::129] <strong>Undefined index: scheme</strong> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]</td></tr></tbody></table><table><thead><th>JS: showing 1 of 1</th></thead><tbody class="elementor-log-entries"><tr><td>JS: 2019-02-20 06:40:12 [error X 6][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:6883] <strong>Cannot read property \&#039;select2\&#039; of undefined</strong> </td></tr></tbody></table>
</summary>
</details>

**Comment by shilo-ey** [comment]
Hi @taropaa 

We can't replicate,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by taropaa** [comment]
So you created a content template in Toolset. Then you used a singles template and added the post content block and you were able to get it to display a single custom post (not within the Elementor preview, but just a custom post by itself). I can reproduce this issue on a localhost install with nothing but those plugins installed. This is a bug.
