### ISSUE TITLE
Custom display conditions based on php filter

### ISSUE THREAD

**Issue by formulaclick** [elementor/elementor#7137]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have 2 types of single post templates made with Elementor's theme builder:
- Default (with a sidebar)
- Full width (with no sidebar)
I have created a ACF checkbox field for every post named "Use Full width template". If this option is checked, then I want to be displayed "Full width" post template instead of the "Default" post template. In "display conditions" section, is not possible to select a ACF value.

**Describe the solution you'd like**
I'd like to use a custom php filter to be able to customize conditions.

**Describe alternatives you've considered**
Show ACF fields on "display conditions" section

**Comment by shilo-ey** [comment]
Hi @formulaclick 

Thanks for your feedback, 
Currently, we do not provide a hook/filter for custom conditions, but you can set custom taxonomy for your posts, and set it for "Full width"/"Default".
This way you can use the existing conditions system.

Thanks.

**Comment by formulaclick** [comment]
@shilo-ey Is this planned? It should be easy to implement....
Thanks!
