### ISSUE TITLE
field for adding class or id to page in Page Settings

### ISSUE THREAD

**Issue by emailjough** [elementor/elementor#7147]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently there is no field in Page Settings or elsewhere to add a class or Id to an entire page (body tag). Yes we can add it to a section and put all other content inside this section but in some cases this is not desirable. 

By adding a class or Id to the body tag we could then more easily target elements on specific pages in our stylesheets. For example, if you want to style one page with blue text, borders, buttons, etc and another page with red text, borders, buttons, etc. these 'color themes' could be styled in a stylesheet and added to a page as easily as adding a .blue or a .red to the body tag, and the elements would inherit these color schemes. 

**Describe the solution you'd like**
A field on Page Settings: Advanced for adding a class or ID to the page that would add this class or ID to the body tag just like the custom css field in Page Settings already does.

**Describe alternatives you've considered**
There are plugins and custom php that can do this. Some themes have this as a meta box in Page-> Edit

**Additional context**
Example:

In style.css:
.red .h2 {color: red;}
.red  a.elementor-button:hover  {border: 2px solid red;}
.red  .elementor-tab-title:hover,
.red  .elementor-tab-title.elementor-active {background-color: red;}

.blue .h2 {color: blue;}
.blue  a.elementor-button:hover  {border: 2px solid blue;}
.blue  .elementor-tab-title:hover,
.blue  .elementor-tab-title.elementor-active {background-color: blue;}

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can use the native WP filters, eg. `body_class`, `post_class`.

Thanks for the feedback.

**Comment by rtpHarry** [comment]
This is something that I would like to see implemented. 

I've had a few situations where there are slight variations of the header required, which could be done through css.

Instead I have to implement duplicate copies of the header, which then need to be kept in sync, and use the display conditions, which I'm not sure if its designed to scale. I always use the minimum amount of conditions that I can, as I don't know how "heavy" they are.
