### ISSUE TITLE
Adding Dynamic Popup in WordPress Menu

### ISSUE THREAD

**Issue by hannahrosecalapiz** [elementor/elementor#7148]
** We want to show the Elementor popup by clicking via WordPress menu using Menu Custom link or it is possible in the future to add a dynamic menu that we can select popup or a custom field easily. something like this https://docs.wppopupmaker.com/article/51-open-a-popup-from-a-wordpress-nav-menu

**Comment by shilo-ey** [comment]
Hi @hannahrosecalapiz 

I merged this issue with  #6876, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
