### ISSUE TITLE
THIS PROBLEM AFTER ACTIVATION BETA ELEMENTOR 5

### ISSUE THREAD

**Issue by mattiatester2** [elementor/elementor#7150]
I Guys, after installing this beta, this screen appears: (which is the problem)?

 Fatal error: Declaration of Elementor\TemplateLibrary\Astra_Sites_Batch_Processing_Elementor::get_items($args = Array) must be compatible with Elementor\TemplateLibrary\Source_Base::get_items(array $args = Array) in /home/public_html/wp-content/plugins/astra-sites/inc/importers/batch-processing/class-astra-sites-batch-processing-elementor-v2.php on line 38

**Comment by shilo-ey** [comment]
Thanks, already reported.
