### ISSUE TITLE
Weird extra space below icon widget

### ISSUE THREAD

**Issue by formulaclick** [elementor/elementor#7154]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

I'm using 2.5 Beta but this also happens with previous versions.

## Description

When I add an icon widget, there is always an extra space at the bottom that shouldn't be there. And there is no way to center it vertically.

## Steps to reproduce

Create an icon widget, add a background to that widget for better visibility, and check it. Here there is an screenshot:
![image](https://user-images.githubusercontent.com/2376672/53159480-42154e00-35c6-11e9-811b-8e4bc5e6f5b2.png)

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment
		
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Debian) v5.6.42-84.2
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://wp-test.formulaclick.com
	Home URL: http://wp-test.formulaclick.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: es
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.0-beta1
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

== Must-Use Plugins ==
	WP Time Capsule
		Version: 
		Author: Revmakx

== Log ==
	: 
Log: showing 3 of 32019-02-20 16:16:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.7',
)]
2019-02-20 16:24:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0-beta3',
  'to' => '2.4.5',
)]
2019-02-21 10:40:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.0-beta1',
)]

**Comment by MrTyree** [comment]
The quick fix for this is just using negative margins.

**Comment by formulaclick** [comment]
Yes, but now with Elementor 2.5 if we use inline display, we have to use
negative padding each time, is a bit painful...
Is this a bug and will be fixed or this behavior has some explanation?

**Comment by shilo-ey** [comment]
Hi @formulaclick 

This issue resolves from CSS rule on your <body> which origins from your theme.

Add `line-height: 0;` property to the specific item/s you want to have no line height.

Thanks.

**Comment by formulaclick** [comment]
Hi

For me, it doesn't solve that CSS rule. On which selector should be put?

Anyway. If this is a bug, why is not solved? And if not, what is the explanation?

Thanks

**Comment by rorydesign** [comment]
Issue still persists. Unsure why, but I do have a fix.

.elementor-icon {
    vertical-align:middle;
}

Put this in the global 'Custom CSS' area in Elementor under 'Site Settings'

**Comment by hanna-III** [comment]
Same issue here. The solution above helped but it's still really annoying.

**Comment by musa90** [comment]
I also have problem with this icon widget, this helped me too:
.elementor-icon {
vertical-align:middle;
}

**Comment by cmsajidul** [comment]
> Hi [@formulaclick](https://github.com/formulaclick)
> 
> This issue resolves from CSS rule on your which origins from your theme.
> 
> Add `line-height: 0;` property to the specific item/s you want to have no line height.
> 
> Thanks.

This solved my issue. Thank you!

**Comment by alanstainerPMW** [comment]
I solved this simply by adding this little bit of CSS.
`.elementor-icon-wrapper {
    display: flex;
}`
