### ISSUE TITLE
Transparent header and absolute positioning

### ISSUE THREAD

**Issue by stefanocavaliere** [elementor/elementor#7157]
Hello, 
I'm using sticky header for my website. With the support of a third party plugin (Sticky Header Effects - Sticky Header Effects for Elementor) I made it working better but I have a problem.
I need the header in absolute position over an hero image (gradient) however, activating the scrolling effect, it leaves the header in a separate section and it's not possible to overlay the menu. 
I saw some video tutorials and it seems that the absolute positioning is automatic when the sticky effect is activated without adding custom CSS. 
Could it be an issue of my theme? 

Thank you in advance for any suggestion!

**Comment by shilo-ey** [comment]
Hi @stefanocavaliere 

Thanks for reporting, but please keep beta related issues in the beta thread.

In addition, from your issue report are missing some reproduction info.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
