### ISSUE TITLE
More Options on PopUps

### ISSUE THREAD

**Issue by crispee2000** [elementor/elementor#7158]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I am using the PopUp template as a site interstitial and it is working great.  However, there are a couple of things I wish it had:

1)  Ability to "Fade Out" after XX seconds rather than just "Close"  -- or give us a choice of exit animation

2)  I would like to show it once per session or once per day or once every X days, etc.  Seems like I've seen this in similar add-ons and it would really benefit the great options available.

**Comment by MarkChadbourne** [comment]
I agree it would be helpful to have both entrance and exit animation for pop-ups, which could also differ. Eg slide in and fade out. It would be helpful to have as much control on how the pop-up exits and enters the page.

**Comment by shilo-ey** [comment]
@crispee2000 

Thanks for your feedback.

Your first request is already asked in issue #7063.

As for your second request - you already can add one per session popup condition.
I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 

Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by crispee2000** [comment]
> As for your second request - you already can add one per session popup condition.

I'm looking for how to do this but don't see "per session".  I see show Up to X times which doesn't seem to be the same thing as it seems to be permanently hide it after showing it.

Can you let me know where I set that?

**Comment by crispee2000** [comment]
This question has come up again from client -- show up to X times only that many times per DAY?  Or is that total so that if i put in 1 will it show up the next day or never again?  It's unclear.  No where does it mention per session.

**Comment by shilo-ey** [comment]
[**@crispee2000**](https://github.com/crispee2000) commented on [Mar 22, 2019, 9:27 PM GMT+2](https://github.com/elementor/elementor/issues/7158#issuecomment-475751023 "2019-03-22T19:27:41Z - Replied by Github Reply Comments"):
> This question has come up again from client -- show up to X times only that many times per DAY?  Or is that total so that if i put in 1 will it show up the next day or never again?  It's unclear.  No where does it mention per session.

Thanks for your feedback. [this has been updated](https://docs.elementor.com/article/472-popups).

**Comment by robert1112** [comment]
@shilo-et Hi Does it now allow to show only once each new session? 

I don’t see such thing in the update. Up to X times each session on open/close doesn’t work. Or it should do and didnt because of a bug? Please kindly advise. Thank you.

**Comment by robert1112** [comment]
@shilo-ey Hi Can you kindly advise? Thanks.

**Comment by neylwalecki** [comment]
+1
