### ISSUE TITLE
Price Table, Header Styling Options

### ISSUE THREAD

**Issue by maintdirect** [elementor/elementor#7159]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Price Table, Header Formatting Options, Background Colour. Very limited options, just a simple background colour is allowed, its missing the usual gradient fill, image background options etc to snazz the table design up a bit.

**Describe the solution you'd like**
To have more background color options on the Price Table formatting tab for each section 

**Describe alternatives you've considered**
Without messing with custom CSS can't see away around it

**Additional context**

**Comment by shilo-ey** [comment]
@maintdirect 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
