### ISSUE TITLE
Pagination Arrow on RTL Websites

### ISSUE THREAD

**Issue by yaaashaaar** [elementor/elementor#7161]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
It's a minor bug
When ussing "Products" and "Archive Product" elements on a RTL website with pagination enabled, the arrow on the "Next" page link should be backward and point to left. (and probably on any other elements with pagination and arrow icon)
Solution: Maybe using transform:rotate(180deg) style on it.

## Steps to reproduce
Create new Products element on a RTL website and enable pagination.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @yaaashaaar 

Thanks for reporting.

This issue resolves from WooCommerce plugin generated HTML arrow.
You can contact their developers and ask them for changing this icon to the opposite one.
This is a screenshot of "Shop" page without Elementor activated.

![image](https://user-images.githubusercontent.com/45009641/53296492-ae878b80-3818-11e9-9bf3-f0ff0d70e545.png)

Alternatively, you can add a simple css rule to rotate this widgets 180deg, as you mentioned.

Thanks
