### ISSUE TITLE
Reply-to field include sender

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#7162]
## Prerequisites

- [ x  ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x  ] The issue still exists against the latest stable version of Elementor.

## Description

I have a contact form made with Elementor Pro form widget. I use the last version on Elementor Pro.

I set the From Email field to a general email in our domain, so I set to Reply-to field to the Email field in the form.

The bug is when we receive this email from the website, the Reply-field contains 2 emails: the email from the Email field, but also the From Email.

The Reply-to field should only contains the email from the person that contacts us.

## Steps to reproduce

1. Create a form widget which contains an email field.
2. Set the From Email to an email in the domain of the website.
3. Set the Reply-to to the email field in the form
4. Test the form

**Comment by bainternet** [comment]
@vgstef 

We can't replicate which leads me to think (more of an educated guess) that there is a 3rd party plugin/code involved.

If you look at the actual code you will see that Elementor Pro Email action after submit, only sets a single "Reply To" address.

please try:
- Deactivate all your plugins besides Elementor and Elementor Pro. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.


And see if the issue still persists, Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by vgstef** [comment]
You were right. There was a plugin that was adding a reply-to to all emails sent by our website. Thanks for the help.
