### ISSUE TITLE
2.5.0-beta2 issue

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#7166]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Awesome new features on 2.5.0
But I had some breaks on my current website that I used my custom class (inline-flex) for some elements.
```
.inline-flex{
  display: inline-flex;
  margin-bottom: 0!important;
  vertical-align: middle;

} 
```
Since you used Flex to manage layouts I think.
![image](https://user-images.githubusercontent.com/2544046/53243828-255a4280-36ba-11e9-9edd-2a43663034d8.png)

![image](https://user-images.githubusercontent.com/2544046/53243759-f217b380-36b9-11e9-9d27-43c3de92951c.png)

**Comment by shilo-ey** [comment]
@amindiary 

Thanks for your feedback.

For obvious reasons, we can't support your custom class. 
You can change your custom class for better compatibility.

Thanks
