### ISSUE TITLE
[Nav Menu Widget] Typography settings are the same for Hover/Normal/Active

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7167]
In the "Nav Menu Widget", the typography settings are shared between the 3 modes: Hover/Normal/Active

The color of the text is not shared.

I think this is a bug because it's really usefull to be able to set "Text decoration" to "Underline" or to make the text appear bold for the "Hover" status, for example.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by tristanleboss** [comment]
Ok, I always do all the checks before submiting an issue... and all the issues I submited to you are always real.

But if you do want all the checkboxes, I will recreate an issue with them tomorrow ;)
