### ISSUE TITLE
Auto-Hide Sticky Header and parametric behaviors

### ISSUE THREAD

**Issue by mrprunen** [elementor/elementor#7168]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Auto-Hide Sticky Header.**
An Auto-Hide Sticky Header is an elegant way to increase screen aerea and reduce reading distraction.

The requested behavior is as follows:
When you scroll down the header disappears so it is not sticky.
When you scroll up the header reappears.

at this link you can see an example of the required functionality.
https://osvaldas.info/examples/auto-hide-sticky-header/?reactive-plus

Other important features could be parametric behaviors
**Parametric behaviors**
Another important thing when using sticky headers is to be able to manage the coloring and the aspects in the two phases: At the beginning of the page (sticky not active) and during the scroll (sticky activated).
For example, it may be necessary to handle different images because the  not-sticky header (when at top of the page) has a transparent color and blends with the background while the sticky header has a solid or semi-transparent color.
The headers images may be different for color (positive or negative) and / or size; in general, the image is smaller in the stickyheaders.

The last consideration, perhaps taken for granted, is that the sticky header that will be hidden could be the second section of the header.
So one section is always visible while another one does auto hide.

**Comment by shilo-ey** [comment]
Hi @mrprunen 

I merged this issue with  #5972, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

As for your second request (next time please open a separate issue per request), this is something we will consider in the future and is on our roadmap.

Thanks for your feedback!

**Comment by mrprunen** [comment]
Plese re-open.
Some issues here are more detailed and in the other 3d nothing moves :-)

In the link (https://osvaldas.info/examples/auto-hide-sticky-header/?reactive-plus) there is also a perfect example of the required functionality
