### ISSUE TITLE
Add new style class to first post

### ISSUE THREAD

**Issue by ginafinch** [elementor/elementor#7169]
I want to layout the first post in an archive differently, but I don't know how to hook into the posts loop when using Elementor template structure.

Can anyone advise how to hook into the posts loop in an Elementor Archive Template? 
Thanks

**Comment by shilo-ey** [comment]
You don't need to code to get this option.
Add two posts widgets.

For the first one select the latest post (in the query tab),
For the second one set the query to include all of your posts with an offset of 1 (the first post).

Thanks.

**Comment by ginafinch** [comment]
I can't do it this simple way, because the Category Filter widget does not work on Post widget - you need to use Post Archive Widget if you want Category Filter, which doesn't have these options.

**Comment by sermalefico** [comment]
@shilo-ey  This no works, this break the pagination. If i have 6 post per page in second widget when click to the second page, the first widget display the second post from second widget of the first page loop while second widget display next 6 post in order.
