### ISSUE TITLE
Add the ability to switch to HSL instead of HEX colors

### ISSUE THREAD

**Issue by freelancesam** [elementor/elementor#7171]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like to use CSS HSL (or HSLA) color codes in elementor instead of HEX.

**Describe the solution you'd like**
The ability to switch CSS color systems

**Describe alternatives you've considered**
N/A

**Additional context**
https://medium.com/samsung-internet-dev/human-friendly-colours-using-hsl-4944bcdb6e27

**Comment by shilo-ey** [comment]
Hi @freelancesam 

I merged this issue with  #6968, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
