### ISSUE TITLE
How do enqueue scripts/styles to be included in Elementor editor (another plugin)

### ISSUE THREAD

**Issue by onassar** [elementor/elementor#7174]
Hi there -
I'm the developer of a plugin that adds a tab to the Media Library modal (https://wordpress.org/plugins/stencil/) and our users are asking for us to support Elementor. Elementor seems to work differently than I expected when I was writing the plugin.

Notably, the admin css/js we register doesn't get included on the editor page. Do you have any examples of how to get those same css/js files registered so that they're included on Elementor sites (if in fact the plugin is installed)?

I looked around for about an hour on your company website and in the issues here, but haven't been able to find any specific examples.

Thanks!

**Comment by bainternet** [comment]
@onassar 	


If you want your assets to load in Elementor You need to use our hooks to enqueue them, either `elementor/editor/before_enqueue_scripts` or `elementor/editor/after_enqueue_scripts` depending on your actual needs.


thanks.

**Comment by onassar** [comment]
Thanks @bainternet I appreciate the quick response.
I was originally (successfully) using the `elementor/widgets/widgets_registered` action, but I've since changed to your recommended usage of the `elementor/editor/before_enqueue_scripts`.

I also want to note for you that the [PHP Hooks](https://code.elementor.com/php-hooks/) page on your documentation doesn't mention the `elementor/editor/after_enqueue_scripts` hook.

For anyone finding this in the future, this is the code I added to my plugin:
``` php
add_action('elementor/editor/before_enqueue_scripts', function() {
    wp_enqueue_style( ... );
    wp_enqueue_script( ... );
});
```

**Comment by abetoots** [comment]
Hello @bainternet  , I don't know if this is good manners( you can tell me if I should create a new issue). My question is does before_enqueue_script fire each time I add/insert a widget in the editor? If not, which action allows me to enqueue a style/script ONLY if a certain widget is inserted?

**Comment by zoynulabedin** [comment]
@bainternet can you tell me How can add style or script for admin in Elementor addon plugin?

**Comment by mabnawp** [comment]
tanks for you. This method worked for me

**Comment by liongvincent** [comment]
Not sure if this method is recommended but this worked for me (for enqueue scripts on individual widgets).

`add_action( 'elementor/editor/before_enqueue_scripts', function(){
    wp_register_script('lesson-card-js', get_stylesheet_directory_uri() . 'location-to/js-file.js' );
});
`

`public function __construct( $data = [], $args = null ) {
    parent::__construct( $data, $args );
    wp_enqueue_script('lesson-card-js');
}`

**Comment by ShawnJW** [comment]
This is what's working for me, right from the documentation https://code.elementor.com/php-hooks/#elementoreditorbefore_enqueue_scripts.

`add_action( 'elementor/editor/before_enqueue_scripts', function() {
   wp_enqueue_script(
   	'plugin-name-editor',
   	'plugin-url/assets/editor.js',
   	[
   		'elementor-editor', // dependency
   	],
   	'plugin_version',
   	true // in_footer
   );
} );`
