### ISSUE TITLE
Button Inside Hamburger Menu

### ISSUE THREAD

**Issue by joychetry** [elementor/elementor#7175]
I have been using elementor for almost 2 years now, and I am absolutely loving the new beta 2.5.0 update. Pretty happy that elementor is powerful then ever.
However, I have been wanting to be able to add Button Inside Hamburger Menu forever now. I always have to hide the button in mobile view in order to get a clean view.
I know many people would absolutely love it if this feature was integrated in Elementor.
Thank You.

**Comment by bainternet** [comment]
Thanks for the suggestion,

I merged this issue with  #4787, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
