### ISSUE TITLE
custom menu :first-child works for all items

### ISSUE THREAD

**Issue by mgustavs** [elementor/elementor#7176]
Hi Guys,

I have made a custom Header, added 2 menus in it and wrote a custom CSS to add seperating lines :

.menu-item > a { border-left: 1px solid #bdbdbe; }

So far so good, BUT I fail to write a code to remove the line for first menu item. Tried heaps - :first-child, :first-of-kind, .first-menu-item, etc. but unsuccessfully..

:first-child took it down for all items...

Thanks, for help! Martins
*I host page locally on my compu atm..*
<img width="1059" alt="screen shot 2019-02-21 at 18 15 36" src="https://user-images.githubusercontent.com/47918624/53286444-80e20a00-3766-11e9-9a2a-fd4d7b20044d.png">

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by mgustavs** [comment]
Isn't that a bug when :first-child applies to all menu items?...
