### ISSUE TITLE
How to disable drop down menu?

### ISSUE THREAD

**Issue by mgustavs** [elementor/elementor#7177]
Hi Guys,

I wish to have items listed in top menu's 2nd/sub? level to have the underline for active path, BUT I do not need the drop down menu of any kind to show up on hover (I know - weird request). How can I do it?..

Thanks a lot, Martin
*I host page locally on my compu atm..*

<img width="1059" alt="screen shot 2019-02-21 at 18 15 36" src="https://user-images.githubusercontent.com/47918624/53286473-f8179e00-3766-11e9-9eb0-d677089376c3.png">

**Comment by shilo-ey** [comment]
Hi @mgustavs 

Currently, this feature is not supported, 

You can manually add a secondary menu under the header and get the behavior you wish for.

Thanks for the feedback.
