### ISSUE TITLE
Bug with twenty seventeen theme

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#7178]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hi after the latest update with wordpress 5.1 & twnetyseventeen i get a Jquery error on some woocommerce pages: 

Uncaught TypeError: Cannot read property 'top' of undefined
    at belowEntryMetaClass (global.js?ver=1.0:124)
    at HTMLDocument.<anonymous> (global.js?ver=1.0:211)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

When I check it seems to be the global.js file in twentyseventeen theme. 
This issue causes the Header cart to stop working when you click on it it does nothing. 

## Steps to reproduce
- Install wordpres 5.1 & latest twenty seventeen theme
- Install elementor, elementor pro & woocommerce 
- add header cart to the header and some product pages. 
On the product archive i cannot open the shopping cart

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Webtica 

Thanks for reporting.

We couldn't replicate your issue:

![image](https://user-images.githubusercontent.com/45009641/53327889-7902a100-38f1-11e9-906c-f828896cff6f.png)



Make sure your theme is updated as well Elementor.

Thanks.
