### ISSUE TITLE
Form Field Design Enhancements

### ISSUE THREAD

**Issue by zrk4444** [elementor/elementor#7180]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It'll make Elementor forms have better design capabilities.

**Describe the solution you'd like**
Able to change border width/border color etc. depending on the state of an element (hover,visited, etc.)
without having to use CSS.

This request actually extends beyond forms and into all of Elementor.

Able to make form labels do animations like this: https://codepen.io/nathanlong/pen/kkLKrL

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
