### ISSUE TITLE
Sidebar Request

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7182]
The only thing I need to use a theme for at the moment is sidebar control. If I wanted to create a side header that was always fixed it would be good to have an option (like header / footer) but for sidebars. That allowed us to create different sidebars that displayed with the same condition as the headers do, but gave control over the sidebar design form Elementor. Thus not needing to rely on a theme for anything other than because WordPress made me :)

**Comment by shilo-ey** [comment]
Hi @stevewoody82 

You can do this using our Locations API.

First of, you need to [register your new location](https://developers.elementor.com/theme-locations-api/registering-locations/#Registering_New_Locations).
After you registered your location, you need to display your location inside your sidebar. [read more about displaying your new location here](https://developers.elementor.com/theme-locations-api/displaying-locations/#Location_with_Fallback_Design).

After you implemented all the necessary code for registering your new sidebar location and displayed it - go to Templates > Add New > Type: Section > Sub-type: "Your Location name"

Hope this will work out for you.

Thanks.
