### ISSUE TITLE
Colour Pallette

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7183]
Can you please consider having a similar colour option as you do to fonts - the the ability to add more than the standard 8 that you do right now. 

https://en-gb.wordpress.org/plugins/kt-tinymce-color-grid/

Gives us a perfect example of what I would love to see as built into Elementor. 

Also to replace the current colour picker with a new version. Right now the small picker tabs of pre-defined colours is limiting and small. It would be better to take the lead from what Gutenberg have in terms of more padding and larger circle spaces. 

Not limiting the numbers / showing labels / having a colour option panel and maybe only allowing 4 in a row that stack would be very welcome.

**Comment by shilo-ey** [comment]
I merged this issue with  #6968, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
