### ISSUE TITLE
Add Tab to Popup

### ISSUE THREAD

**Issue by coltsman4ever** [elementor/elementor#7184]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be amazing, when creating a popup that slides in from an edge of the screen, if you could trigger the popup without adding a dynamic trigger from another element.

**Describe the solution you'd like**
I would like to see the ability to add a tab located on any side, in any location around the popup, that would trigger the popup to slide out onto the screen. The "tab" would be part of the popup and slide out with it. This could also be used in conjunction with exit animations if/when added. The tab would always be visible on the screen, either as sticky or non-sticky. This would be a great feature to add for creating slide-out menus or slide-out contact forms or anything of the sort. It would be much more cohesive and integral with the popup than the use of buttons or other elements.

**Describe alternatives you've considered**
N/A

**Additional context**

![menu tab](https://user-images.githubusercontent.com/47944758/53300684-b21b1280-3818-11e9-948b-1adeb98887d8.JPG)

![menu tab3](https://user-images.githubusercontent.com/47944758/53300888-b0eae500-381a-11e9-8f4b-6d365f18925a.jpg)

**Comment by shilo-ey** [comment]
I merged this issue with  #6225, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
