### ISSUE TITLE
Dynamic background images not working on new WP 5.1 

### ISSUE THREAD

**Issue by luispedroferreira** [elementor/elementor#7185]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @luispedroferreira 

Couldn't reproduce,
Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* System info.

**Comment by luispedroferreira** [comment]
Hi.
Did you even try it?
As far as I understand I wrote the steps to replicate. Create a loop widget with WP 5.1 and create the same widget with WP 5.0. So please, tell me how can I explain the steps to replicate the issue even better?

Maybe I missed the system info but that doesn’t stoped you to answer my previous ticket also without the system info.

The bug is yours and with your product, you’re not helping only me but also all your customer who paid for your product and I was only trying to help you.
I already found a workaround but let me know if you still need my help.

Kind regards.
Luis Pedro

**Comment by shilo-ey** [comment]
Of course we tried.

There is no such thing "Loop Item", and you didn't mention steps to reproduce.

If you wish to contribute, please open a proper issue with all the required missing information.

We simply cannot replicate.
