### ISSUE TITLE
Outdated Youtube icon

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#7188]
Social share icons use the old outdated and off-brand youtube icon. The stacked words "youtube" rather than the play icon that they use now. 

Updated the social share buttons so youtube uses the correct and current icon and not the dated one.

Currently, we have to hardcode these elements now when a client wants youtube featured as to not use outdated icons

This would be a really easy fix, as the correct youtube play icon is already a part of font awesome 4.7.0 being used. https://fontawesome.com/v4.7.0/icon/youtube-play

**Comment by shilo-ey** [comment]
I merged this issue with #4430 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by portrayaloflife** [comment]
Nothings being done, youtube branding has been updated years ago and you guys are still using the old outdated icon. Pushing this off until you "get around" to FA5 is a mistake. It would be easy to update the youtube icon since it exists in FA4 or just add a new option called "play" for example with the correct youtube logo so we can at least have the current youtube logos shown. No use in having all these modern design tools if something as simple as a social icon is so dated...
