### ISSUE TITLE
[BUG] pop ups not aligned in safari

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#7189]
[X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[X] The issue still exists against the latest stable version of Elementor.

## Description
In Safari, tested on version 10.1.2 (10603.3.8)

Elementor popups do not align center screen as they should. On a fresh install, the pop-up element taken right out of a template floats right on the screen rather than centered, for every pop up template or custom creation. 

Screenshot:
http://testpopups.flywheelsites.com/wp-content/uploads/2019/02/Screen-Shot-2019-02-24-at-10.14.30-PM.png

Live:
http://testpopups.flywheelsites.com/

## Steps to reproduce
Create a pop up in Safari

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: (Ubuntu) v5.6.32
	PHP Version: 7.1.26-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: http://testpopups.flywheelsites.com
	Home URL: http://testpopups.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.6.9
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

== Log ==
	: 
Log: showing 1 of 12019-02-25 00:52:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.2.0',
  'to' => '2.4.5',
)]

**Comment by shilo-ey** [comment]
Hi @portrayaloflife 

Thanks for reporting.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by rkl122** [comment]
Same problem here.  What was solution?

**Comment by portrayaloflife** [comment]
no solution but updating your browser

**Comment by romain-code** [comment]
Hi. Same issue whith Safari 10.1.2. 

Look my test page : https://drumartcollective.com
and then, click on the first item (Thommas) in top/left. 
The popup doesn't align in center. 

Updating browser is not a solution. Amazon don't say to his consummer "update your browser", because some people have an old mac where updates are not possible since 2017 for example. The market share of users using an outdated browser is important, so we lose customers if they can not browse our sites.

Please, we need developer help ! 👍

**Comment by max-zipsites** [comment]
+1 for this issue. 

Safari 10.1.x is a very common browser and surely worth supporting?

**Comment by romain-code** [comment]
My clients tell me: "but what is this horror? !!!". And I have to answer them that the Elementor page builder system is not compatible with half of the world's browsers. They answer me: "So, let's look for another page builder". Unfortunately I think that's what I'm going to have to do. Unless Elementor reacts, which would be a good thing.

**Comment by jdlitson** [comment]
The way I worked around this issue is by using an Elementor 3rd party plugin (Dynamic Content for Elementor) ([dynamic.ooo](https://www.dynamic.ooo/)). There are two widgets included which both work without alignment issues. 

1. Modals
2. Fire  Modal Window

I didn't purchase the plugin for this feature but now I am happy I have it.
There may be some free plugins with modal / popups somewhere as well?

**Comment by chooomedia** [comment]
Quick&Dirty Solution via CSS:

1. Add custom code inside Elementor
2. Execute after body
3. Add:
<style>
[data-elementor-type=popup] .elementor-section-wrap:not(:empty)+#elementor-add-new-section, [data-elementor-type=popup]:not(.elementor-edit-area) { display: block!important; }
4. Save
5. Test and have fun :-)

**Comment by Kubot12** [comment]
Why is this issue marked closed? It's still happening. If a 3rd party plugin can open a popup on Safari without a bug, why won't Elementor fix this? This is a true browsers compatibility bug! Please fix. 

PS - The hack from @chooomedia isn't working for me.
