### ISSUE TITLE
Link in text editor of Elementor should open new tab

### ISSUE THREAD

**Issue by StephDLaw** [elementor/elementor#7191]
Hello,
I contacted tech support about this issue and was told I should post here. I have searched and cannot find the issue already posted.

I am designing a website with WordPress and Elementor Pro. I have put links to external websites in my project, but unfortunately I do not have the option of the link opening the other website in a new tab. It comes into the same tab closing our site. From a marketing standpoint, this is a big mistake. I would really like to have this option.

It occurs in the text editor, titles and with image links.
Thanks

**Comment by shilo-ey** [comment]
Hi @StephDLaw 

You sure can open a link in a new tab.

Text editor: click on the link, then in the popover menu click on the cog. from the options shown, select the checkbox for open in a new tab.

In buttons or other elementor widgets/controls - click on the cog icon next to the link field and select the option to open in a new tab.

I strongly recommend you to learn more about Elementor using our [knowledge base](https://docs.elementor.com/).

Thanks.

**Comment by StephDLaw** [comment]
Thank you shilo-ey. Not sure why your tech support emailed me that it wasn't possible, but good to know.

**Comment by brunocerq** [comment]
Hi there,
Since last update, this option to open a link in new tab as disappeared!?
Screenshot attached.
Please make it available again.
Thanks
![Capture](https://user-images.githubusercontent.com/30045642/69917063-2f378000-145a-11ea-97a4-451d70ca406f.JPG)
