### ISSUE TITLE
Recaptcha v3 site keys not valid

### ISSUE THREAD

**Issue by StephDLaw** [elementor/elementor#7192]
We are developing a new website with WordPress an Elementor Pro. Just last week, I followed the instructions to generate the site keys for recaptcha, but they are invalid because it is v3. I saw on an earlier closed post that you will only consider an update if there is demand. Since we have no possibility to filter spam, I consider this lack of an update to be a serious fault and would like to let you know that there is absolutely demand. Please send us an update as soon as possible.
Thank you.

**Comment by shilo-ey** [comment]
Hi @StephDLaw 

Currently, we support reCaptcha v2. Please use those keys for your website.

Thanks.

**Comment by StephDLaw** [comment]
shilo-ey, I would love it if you could please tell me how to get v2 keys when Google does not offer them anymore. I have been back and forth with your tech support to no avail. Please develop an update, and do not close a thread before it is resolved.

**Comment by shilo-ey** [comment]
@StephDLaw 

Those issues does not relate to Elementor. it relates to general question to Google support, therefore the issue is closed.

A simple search directed me to this: https://www.google.com/recaptcha/admin/create

Good luck

**Comment by StephDLaw** [comment]
I agree that Google creates a huge problem by not allowing an account to change to v2 after choosing v3. Searches for v2 were blocked and the only way to change to v2 was to create a new Google account. Something I was not aware of. However, if Elementor was updated to recognize v3, this would be solved as well.
