### ISSUE TITLE
Cannot use recaptcha v2 site keys

### ISSUE THREAD

**Issue by StephDLaw** [elementor/elementor#7198]
I posted earlier about this, but the thread was closed before I could respond. Google does not offer v2 site keys for recaptcha anymore which means our new website will not have any spam filters for the contact forms. They only offer v3 keys which elementor does not support. Please update this as soon as possible, or tell me specifically how to get v2 keys. I have searched and tried and cannot find a way.

**Comment by bainternet** [comment]
@StephDLaw 	

Not sure what you mean by 
>Google does not offer v2 site keys for recaptcha anymore

![tvuojs8](https://user-images.githubusercontent.com/660572/53347353-8fc0ec00-3921-11e9-8082-13da1975136e.png)

**Comment by StephDLaw** [comment]
For anyone reading this, you will have to create a new google account. Once you have chosen v3 as I must have done before I realized there would be a conflict with Elementor, Google will not let you change back to v2. They even block searches for it. Once I created a new account and started from scratch, I came to the screen above and I had a choice again.
