### ISSUE TITLE
Hotkey for Elements

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7199]
As the title suggests. 

Hotkey to open the elements window. I've seen other issues like this but they have been merged with things that are not related.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Click CTRL+? to open the shortcuts screen.

Thanks.

**Comment by stevewoody82** [comment]
Sorry, Will update.
