### ISSUE TITLE
Keyboard Delete Shortcut

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7200]
Please consider changing the delete shortcut for backspace for those mac users (or add both options)

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by stevewoody82** [comment]
Sorry
