### ISSUE TITLE
Element Window Hotkey

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7201]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Easy access to the element window to remove moving the mouse and clicking.

**Describe the solution you'd like**
Hotkey to open the elements window.

**Describe alternatives you've considered**
 I've seen other issues like this but they have been merged with things that are not related.

**Additional context**

**Comment by bainternet** [comment]
@stevewoody82 

Can you explain/elaborate what you mean exactly?

How do you see this working?

**Comment by stevewoody82** [comment]
Hope this helps @bainternet  https://www.useloom.com/share/ea96772ccd484181a3c90558da8d4f61

**Comment by shilo-ey** [comment]
Hi @stevewoody82 

Thanks for your feedback.

Maybe you're new to Elementor, and maybe you didn't notice but if you click outside of element area - the screen changes to the widgets screen.

In addition, when you need to use and drag a widget, you have to go to the panel and click on it, therefore this feature request will not be processed.

Thank you for contributing.
