### ISSUE TITLE
Image widget custom size issue with ACF dynamic content

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#7203]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The dynamic feature of ACF Pro, Image Widget and Call to Action Widget does not bring the correct custom image size. But, when selecting the same image using the WordPress standard selection way it works.

![acf-custom-image-issue](https://user-images.githubusercontent.com/17693529/53346356-a3565d80-38f5-11e9-858b-e9c278bc58d5.jpg)

The video explains the problem better:
https://streamable.com/aoq3d

## Steps to reproduce
01. Create an Image Widget or Call to Action Widget and set a custom image size;
02. Add the image dynamically using an ACF custom field;
03. Dynamic image does not use the custom width x height sizes.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
Need ACF to show bug.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Unix) OpenSSL/1.0.2g
	MySQL version: (Ubuntu) v5.7.25
	PHP Version: 7.3.2
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: http://mhr.artneo.com.br
	Home URL: http://mhr.artneo.com.br
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.12
		Author: Elliot Condon

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

== Log ==
	: 
JS: showing 10 of 10JS: 2019-02-18 12:19:13 [error X 5][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:9:78] Unexpected token , 
JS: 2019-02-18 12:20:51 [error X 1][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:16:41] Unexpected token && 
JS: 2019-02-18 12:30:27 [error X 5][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:27:3] missing ) after argument list 
JS: 2019-02-18 12:30:28 [error X 6][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:27:3] Invalid or unexpected token 
JS: 2019-02-18 12:31:34 [error X 4][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:33:1] Unexpected end of input 
JS: 2019-02-18 12:32:46 [error X 3][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:32:1] Unexpected token } 
JS: 2019-02-18 12:35:25 [error X 1][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:25:28] Unexpected token . 
JS: 2019-02-18 12:35:28 [error X 3][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:25:39] Unexpected identifier 
JS: 2019-02-20 21:05:37 [error X 8][http://mhr.artneo.com.br/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.4:2:15986] Cannot read property \'model\' of undefined 
JS: 2019-02-22 19:53:38 [error X 1][http://mhr.artneo.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:6883] Cannot read property \'select2\' of undefined 

Log: showing 2 of 22019-02-20 11:35:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-22 08:55:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]

PHP: showing 3 of 3PHP: 2019-02-24 18:46:30 [notice X 24][/srv/users/serverpilot/apps/artneo-mhr/public/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-24 18:47:24 [notice X 3][/srv/users/serverpilot/apps/artneo-mhr/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::44] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-24 21:04:22 [notice X 1][/srv/users/serverpilot/apps/artneo-mhr/public/wp-content/plugins/elementor/includes/template-library/sources/local.php::674] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by shilo-ey** [comment]
Hi @Artneo7 

Thanks for your feedback.

This behavior occurs because the return value you set is "Image URL", and not "Image Array" or "Image ID".

When retrieving ID/Array, the original file can be reached and not the cropped image, and with those parameters, Elementor can change the size based on your custom dimensions.

To change this, change the return value to "ID" / "Array".

Thanks!

**Comment by Artneo7** [comment]
That's it, can't believe I didn't tried that before…

Thank you so much for the support!

**Comment by Eddimor** [comment]
I'm using jetengine and when im using a dynamic link the same thing happens. I did set the value format to "array with meda ID and URL". The Problem stays and the set aspect ratio braks as soon as i insert the dynamic link.
