### ISSUE TITLE
Keyboard Delete Shortcut for Mac Users

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7204]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Most mac keyboards only have backspace and not a delete key

**Describe the solution you'd like**
Please consider changing the delete shortcut for backspace for those mac users (or add both options)

**Comment by shilo-ey** [comment]
Hi @stevewoody82 

We cannot allow the use of backspace because it is already used for other uses (delete text etc.)

You can use right click > delete.

Thanks

**Comment by bentalgad** [comment]
Would be nice to use cmd+backspace.

**Comment by Next-Door-Tech** [comment]
I second cmd+backspace.

**Comment by MakhouT** [comment]
Same issue here, pretty time consuming to right click and delete items

**Comment by Next-Door-Tech** [comment]
Lets move the conversation to open issue #11308

**Comment by hirschferkel** [comment]
It is so annoying to use click + delete.
vote for cmd+backspace.
