### ISSUE TITLE
Integration with Landing Pages plugin

### ISSUE THREAD

**Issue by atwellpub** [elementor/elementor#7205]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Hi! 

I'm the lead developer of Landing Pages plugin. A mutual customer is asking for support with Elementor Page Builder. 

Landing Pages provides basic split testing capabilities to a WordPress custom post type. We're storing post_content data into meta pair placeholders that represent variations, and hooking into the_content and get_the_content to make sure we retrieve the correct variation on page load. 

I started writing an integration with Elementor but have hit a hard wall. I originally thought I could use elementor/documents/ajax_save/return_data to intercept the Elementor data being saved and store it within our meta-pair placeholder (See https://github.com/atwellpub/inbound-elementor-scratchwork/blob/master/inbound-elementor.php#L58)

But then discovered this would not work. The post_content only contains the most basic content and does not contain the CSS/Widget wrappers included in a normal Elementor page. 

I was wondering if Lead dev could take a look at my integration asset (link below and above) and get a feel for what I am trying to do, and advise me the best way to hook into Elementor data storage and retrieval. 

It looks like elementor data is being stored into and called from the _elementor_data metapair. Is there a clean way I can tap into the storage and retrieval of this data? I'd like to save it into something like _elementor_data-0 for variation 1 and _elementor_data-1 for variation 2 and _elementor_data -2 for variation 3 and so forth. 

Landing Pages plugin code:
https://github.com/inboundnow/inbound-pro/tree/master/core/landing-pages

Landing Pages / Elementor integraton framework: 
https://github.com/atwellpub/inbound-elementor-scratchwork

**Describe the solution you'd like**
Integration between Landing Pages and Elementor  might require a filter added to the retrieval and storage of the _elementor_data meta key. I'm not certain though. Looking for help and guidance. 

**Additional context**
Landing Pages plugin is a free WordPress plugin available from the WordPress plugins directory here:
https://wordpress.org/plugins/landing-pages/

Thanks for any and all help! I'm also a contractor with Codeable.io and every now and then see Elementor jobs come through. Any attention with dev staff is great attention. 

Warm regards,
Hudson Atwell

**Comment by bainternet** [comment]
@atwellpub 	

Elementor saves only pain content in `post_content` and it's there only for cases where you choose to revert back to the native editor. When a page/template is rendered by Elementor, it actually uses the `_elementor_data` meta value to generate the page/template.

So to intercept retrieval and storage, I would suggest you use our hooks:

retrieval: 
https://github.com/elementor/elementor/blob/1a0a22a337e2cdd62cb02512e769f5e0081403b0/includes/frontend.php#L797-L807

storage:
https://github.com/elementor/elementor/blob/35190a72760b8a1a4978fdb88280ca5598944ecd/core/base/document.php#L854-L864


Also you can always use the native `update_post_metadata` and `get_post_metadata` filter/action hook.

thanks.

**Comment by atwellpub** [comment]
@bainternet Awesome. Thanks a ton! These helped me improve the asset! 

I'm going to send the updated integration asset over to the client for testing. 

Thanks again! I'll jump back on if I need any more help.

**Comment by atwellpub** [comment]
@bainternet 

Hi Raz,

I've got the frontend loading the correct content through intercepting elementor/frontend/builder_content_data, but what I can't seem to tap into is the preview area of the builder. 

If I'm on variation A and save and switch to Variation B and created content and save and then switch back to A, B's is visible because the preview is still loading the normal saved elementor data.  

Is there a filter available like elementor/frontend/builder_content_data for the preview area? 

Warm regards,
Hudson

**Comment by atwellpub** [comment]
@bainternet 

Hi Raz,

Do you have any leads on how to intercept and retrieve the custom CSS that accompanies an Elementor page? The current integration asset always pulls the last saved variation's CSS. 

I've tried setting to internal CSS and external CSS. 

Any help at this point is greatly appreciated.
