### ISSUE TITLE
Clickable badge in archive posts

### ISSUE THREAD

**Issue by Cecile-Lebleu** [elementor/elementor#7206]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

This is related to the Badge in Archive Posts widget in Elementor Pro. [More about it in the docs (number 15)](https://docs.elementor.com/article/464-archive-posts-widget-pro)

### Original feature request:
It would be really cool if you could make the badge clickable. When the user clicks on it, they're taken to the archive page for the corresponding tag or category.

### Bonus points:
It would also be great if you add the option to have more than one badge (with a selector for how many badges to show), and the option to select colors for a set category or tag.

### Example use case:
Using categories:
Say for an example that I have a blog about food recipes, and on the home screen I show the latest posts. Some are meals, some are desserts, some are drinks... and I want the "meal" category to be green, the "dessert" tag to be pink, and the "drink" to be orange. When a user wants to see more desserts, they can click on the pink badge on the corner of a dessert recipe, and they are taken to see all the posts that have the dessert category.

Using tags:
Continue the previous example. Now they are looking at the desserts category where the same Archive posts is used. In this case, I selected to show tags, not categories. As there is an option to show multiple badges, now on each post I can see tags like "sugar free", or "vegan", or "quick". The user is able to quickly see some attributes about the recipes without having to open it. (And, again, if a user only wants to see "quick" recipes, they can click on that and be taken only the quick recipes).

Thanks a lot for considering this! Maybe the colors and multiple badges are more complicated to make, but I would really appreciate the clickable badge for starters!

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can achieve this by creating custom posts skin.

also please follow #4440 which will make this possible via the editor.


Thanks for the feedback.

**Comment by lauranunez** [comment]
But I have to install a new plugin only for this little feature?

I am WordPress Designer and 90% my customers say me.: "click in badge and it doesn´t work". 

Is possible this feature with a function?

**Comment by richpav** [comment]
You will add it if you see a large demand for it. Where do I cast my vote so that it will register as popular demand for this feature? I don't want to add a plugin just to have this tiny UI function that should already exist.

**Comment by neilparnold** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Definitely adding my +1 here. Thanks for the great plugin.

**Comment by philrp** [comment]
+1

**Comment by sotplugy** [comment]
+2

**Comment by jhweb2** [comment]
+3

**Comment by markus4000** [comment]
+4

**Comment by nicmare** [comment]
+1 badge-click choice: badge term archive / post single page

**Comment by webndesign** [comment]
Definitely a feature I'd love to see! Come on guys, being able to selectively add some sort of a badge on posts/archive pages etc is a useful UX attribute!
I'm positive if you made it a permanent option in your Content or Style tabs a lot of people would benefit from it!!

**Comment by askejlacen** [comment]
Is this a thing already?

**Comment by quasemineira** [comment]
I need this too!

**Comment by webinfinitynz** [comment]
+1

Why was this closed?

Having the badge clickable is very important for UX. Come Elementor devs, this is needed.

**Comment by webndesign** [comment]
Cause they didn't want to know about it!!

**Comment by bbua97** [comment]
+1

**Comment by dinapal** [comment]
Yes, that will help full for us. please add the feature.

Thank you

**Comment by Trevor143** [comment]
+1

**Comment by xtremeproximity** [comment]
Please! Such a needed feature! +1

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
