### ISSUE TITLE
Remeber last active tab on page refresh

### ISSUE THREAD

**Issue by christofferols** [elementor/elementor#7207]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In case of Tab elements on a page, whenever the page is refreshed it looses whatever tab was last active and goes back to first tab.

**Describe the solution you'd like**
Is there a way to make the last active tab remain selected even on page refresh?

**Describe alternatives you've considered**
I have tried various solutions and so far was unable to make anyone work available from Stackoverflow, but none of them worked.

https://stackoverflow.com/questions/4299435/remember-which-tab-was-active-after-refresh

https://stackoverflow.com/questions/36741626/how-to-remember-last-tab-used-after-submit-refresh

https://stackoverflow.com/questions/50423148/keep-active-tab-on-page-refresh-in-bootstrap-4-using-local-storage

**Additional context**

**Comment by bainternet** [comment]
@christofferols 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, this can be easily done with this JS snippet:

```HTML
<script>
jQuery( document ).ready( function( $ ) {
	// Add tab ID as url hash when a tab is changed
	$( '.elementor-tab-title' ).on( 'click', function(){
		window.location.hash = $(this).attr( 'id' );
	});	
	// Check if we need to activate a tab based on the has
	if ( window.location.hash && $( window.location.hash ).length ) {
		$( window.location.hash ).click();
	}
} );
</script>
```

this is an example which should work out of the box, but if you have more than on tabs widget on a page you will need a different solution to store each tab widget active tab, like WIDGET|TAB based hash or cookie/localstorage.


Thanks for the feedback.

**Comment by MickeyMick00** [comment]
Yeah I'm too looking for this feature.

**Comment by adventurepro** [comment]
Hi - I need the function mentioned here and tried the script, but it crashes the site (fatal error). Has anything changed?

**Comment by SusanSuna** [comment]
I also need this function. I think a lot of people do. I think they don't know to post here.

**Comment by vektor007** [comment]
I would also love this function. The code snippet does not work, or sometimes crashes the archive template (where I want to use this function).

**Comment by AwaisTheDev** [comment]
Try this updated code if you are facing issues like page jump on reload. Also works with new Elementor tabs

```
<script>
jQuery(document).ready(function($) {
  // Function to update the URL with the active tab ID as a parameter
  function updateURLParameter(param) {
    var url = new URL(window.location.href);
    url.searchParams.set('active-tab', param);
    history.pushState({}, '', url);
  }

  // Function to retrieve the active tab ID from the URL parameter and trigger the click event
  function triggerActiveTabFromURL() {
    var urlParams = new URLSearchParams(window.location.search);
    var activeTabID = urlParams.get('active-tab');
    if (activeTabID && $('#' + activeTabID).length) {
      setTimeout(function activateTab(){
          $('#' + activeTabID).click();
      },300);
    }
  }

  // Attach click event handler to the tab elements
  $('.e-n-tab-title').on('click', function(e) {
    e.preventDefault();
    var tabID = $(this).attr('id');
    updateURLParameter(tabID);
  });

  // Trigger active tab from URL when the page is reloaded
  triggerActiveTabFromURL();
});
</script>
```

add code to html widget on the page

**Comment by nicolaslagiosrkpt** [comment]
I wrote a totally new function, it works 100% with elementor 2025 versions if you put an id on each tab. It remembers the last tab by storing it in memory and only changes it if you visit another tab and reload the page:
```
<script>
jQuery(document).ready(function($) {
  const storageKey = 'activeProfileTab';

  $('.e-n-tab-title').on('click', function() {
    const tabId = $(this).attr('id');
    if (tabId) {
      localStorage.setItem(storageKey, tabId);
    }
  });

  const savedTabId = localStorage.getItem(storageKey);
  if (savedTabId && $('#' + savedTabId).length) {
    setTimeout(function() {
      $('#' + savedTabId).trigger('click');
    }, 300); // Delay ensures Elementor or JS tabs are ready
  }
});
</script>
```
