### ISSUE TITLE
Elementor Smoothscroll anchor did not work

### ISSUE THREAD

**Issue by c0dem0re** [elementor/elementor#7208]
Hello, everybody, 
i have a problem with the smoothscroll anchor in elementor.
On my start page I have several buttons that link to a subpage.
e.g. /services#consulting
The link works, but the smoothscroll doesn't. If someone has a solution here

These are my installed plugins:  https://cl.ly/1fc4def899c5

Everything is up to date.

Thanks for your help Cheers
Marcel

**Comment by shilo-ey** [comment]
Hi @c0dem0re 

That's not how the anchor system in Elementor works.

In Elementor - only links with ID that are in the same page get this effect.

In order to use smooth scroll with this behavior - you will need to add another smooth scroll module for direct links.

Thanks

**Comment by mustafaturksavas** [comment]
Hi @shilo-ey 

Where is the smooth scroll module? How can I add one? Because I have the same exact issue.

**Comment by TheMangoTrain** [comment]
I'm also interested in smooth scrolling (between sections on a single page).

I see all kinds of posts here touching on this. People talk like it's already included in Elementor, or that it's easy to implement or it was working but now it isn't. Lots of vague information, no explicit statements.

I will kick myself if after spending 40hours researching and tweaking a 3rd-party plugin, that I find all along the exact same functionality was always being loaded in Elementor and my end-user is just downloading redundant scripts.
