### ISSUE TITLE
image Carousel custom height bug

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7209]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

This video shows the bug and how to reproduce.

Image Carousel does not recognize custom width or height.

https://www.useloom.com/share/f52e813b12334e468c9eb041e80f8c2d

**Comment by shilo-ey** [comment]
@stevewoody82 

Couldn't replicate on our side.

It seems like you have a caching issue.
Please try to empty your cache or try to display the page in an incognito tab.

Thanks
