### ISSUE TITLE
Background Overlay Bug

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7212]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

Background Overlay Images are not showing on Safari or Firefox.

Tested and working on Chrome.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.

Works on our side - couldn't reproduce your issue.
