### ISSUE TITLE
Image overlay & border padding

### ISSUE THREAD

**Issue by mauritzbotha92** [elementor/elementor#7215]
* [ x] Border padding is mentioned here: https://github.com/elementor/elementor/issues/5606

* [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Feature request

Hi all, I would like to request 2 minor things be added to elementor.

1. Ability to add overlay for images with normal and hover states which will allow you to have a colour overlay or gradient overlay for example directly on the image.

2. The ability to add padding for borders. I don't always want a border to be only on the outside of an image. Sometimes I would like a border to have padding on the element it applies to, so the border can be on the inside of the element as well with a space around it. And maybe add more border patterns to choose from as well.

Many thanks,
Mauritz

**Comment by shilo-ey** [comment]
Hi @mauritzbotha92 

1. Use Call to action widget to get this effect or use CSS filters for creating similar behavior.
2. Currently, we support adding a border that is attached to the image or the box of the widget. we do not support padding for the border.
Alternatively, you can achieve this behavior by adding custom CSS such as:
```CSS
selector img {
    padding: 10px;
}
```

Thanks
