### ISSUE TITLE
Social Icons - Title incorrect

### ISSUE THREAD

**Issue by dzined** [elementor/elementor#7216]
When using the Social Icons widget, the title attribute for LinkedIn is actually written as "Linkedin" where it should be "LinkedIn" - i.e. capitalised I on in.

It would be great to see title added as an editable option with show/hide functionality at some point, but for now it would be great to get the spelling above corrected.

We also have have an issue with the Share Icons widgets, the screen reader only text has the brand names in lower case

Thanks

Matt

**Comment by shilo-ey** [comment]
Hi @dzined 

The LinkedIn title will be corrected.

Thanks.

**Comment by shilo-ey** [comment]
Hi @dzined 

The current state of how Elementor Social Widget works is that it takes the icon name (e.g fa fa-linkedin) and capitalizes it.

Please follow #4430 when we will upgrade the icon system, and only then we can address your issue.

Thanks.

**Comment by dzined** [comment]
Great, thank you
