### ISSUE TITLE
Shortcodes not processing sometimes

### ISSUE THREAD

**Issue by jpknz** [elementor/elementor#7218]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

In certain circumstances shortcode are not processed meaning the customer sees the shortcode request rather than the resulting content. NB This could be something to do with the way I'm displaying the page but I can't work out why.

## Steps to reproduce

1. Create a page in Elementor that has a button.  Use a shortcode for the URL and also for the button text.
2. The correct content will display (including the generated urls which also use shortcodes) if you access the page at example.com/pageinquestion/ - [see this screenshot](https://imgur.com/a/JvB2sQS)
3. If the page is displayed with the below code inside Woocommerce (Subscriptions) then the result is as [shown in this screenshot](https://imgur.com/a/zMKvlpl). The button text displays (the prices) but obviously the page is not formatted correctly and the text isn't links (so no urls)
    `		$post = get_post(1013); 
		$content = apply_filters('the_content', $post->post_content); 
		echo $content;`
4. If the page is displayed with the below code inside Woocommerce (Subscriptions) then the results is as [shown in this screenshot](https://imgur.com/a/TGkMITl). In this case the URL (also uses a shortcode) is generated and displayed/works correctly but the button text remains as the shortcode request
    `$content = \Elementor\Plugin::$instance->frontend->get_builder_content_for_display( 1013 );
		echo $content;`

The only way I can work out to get around this is to process the loaded page content, search for shortcode tags and process them directly replacing the tag with the content that it generates when processed as below.

```
function display_subswitch_template() {
	echo 'testing2';
		$content = \Elementor\Plugin::$instance->frontend->get_builder_content_for_display( 1013 );
		$content = process_subswitch_content_for_shortcodes( $content );
		echo $content;
		
	}
```
.
```
function process_subswitch_content_for_shortcodes( $content ) {
		
		$keepprocessing = true;
		$searchstart_pos = 0;
		do {
			
			$startchar_pos = strpos( $content, "[subswitch", $searchstart_pos );
			if ( $startchar_pos == false ) {
				$keepprocessing = false;
			}
			
			$endchar_pos = strpos( $content, "]", $startchar_pos );
			$shortcode_request = substr( $content, $startchar_pos, $endchar_pos );
			if ( $shortcode_request == false ) {
				//return $content;
				$keepprocessing = false;
			}
			
			$shortcode_content = do_shortcode( $shortcode_request );
			$content = str_replace( $shortcode_request, $shortcode_content, $content );
			
			$searchstart_pos = $endchar_pos;

		} while ( $keepprocessing ); 

		return $content;
	}
```

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.23
	PHP Version: 7.0.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://test.***removed***.co.uk
	Home URL: https://test.***removed***.co.uk
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

	Pluginception
		Version: 1.3
		Author: Otto

	Really Simple SSL
		Version: 3.1.3
		Author: Rogier Lankhorst, Mark Wolters

	stopAds WooCommerce Functions
		Version: 
		Author: 

	WooCommerce
		Version: 3.5.4
		Author: Automattic

	WooCommerce Blocks
		Version: 1.3.1
		Author: Automattic

	WooCommerce Services
		Version: 1.18.0
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.14
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.5.1
		Author: Prospress Inc.

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms


== Log ==
	: 
PHP: showing 2 of 2PHP: 2019-02-03 01:33:44 [notice X 2][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-08 10:18:20 [notice X 4][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/query-control/module.php::263] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 4 of 42019-02-12 18:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-12 18:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-02-23 15:00:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-23 15:00:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]

JS: showing 1 of 1JS: 2019-02-17 11:36:30 [error X 3][https://test.***removed***.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.6:2:47187] undefined is not an object (evaluating \'t.element\') 


				
```
</details>

**Comment by bainternet** [comment]
@jpknz 

We are having a real hard time to understand what you are actually reporting here.

The steps you provided are more of a guide or status report than steps to reproduce.

So I'll just say this: When you use a shortcode in elementor use a [shortcode widget](https://docs.elementor.com/article/72-shortcode). And when you want to use shortcode for a control value, use [Dynamic Shortcode](https://docs.elementor.com/article/449-dynamic-shortcode)

Thanks.

**Comment by jpknz** [comment]
Hi @bainternet 

Sorry if it wasn't clear.  I'll try again.

Steps to reproduce
1. Create a page in elementor
2. On the page add the button widget
3. For the text of the button enter a shortcode e.g. [myshortcode request='buttontext']
4. For the url of the button select shortcode and enter a shortcode e.g. [myshortcode request='buttonurl']
5. Create the shortcode function that returns 'this is some text' when the request type is buttontext and url 'example.com' when the request is buttonurl

If you preview the page from elementor or if you access it directly (e.g. mysite.com/elementorpagecreated the button will display correctly with the button text as 'this is some text' and the url as 'example.com' (see [https://imgur.com/a/JvB2sQS](https://imgur.com/a/JvB2sQS )that shows a page created in the above manner that displays correctly)

If you display the page using the below code it will display completely incorrect as shown at [https://imgur.com/a/zMKvlpl](https://imgur.com/a/zMKvlpl). Here the button text shortcodes are being processed but not the URL (or any other page formatting for that matter - possibly not the correct way to display an elementor page using php)
`$post = get_post(1013);  
$content = apply_filters('the_content', $post->post_content);  
echo $content;`

If you display the page using the below code then the url is correct (e.g. 'example.com') however the button text shortcode is not processed and simply displays as the shortcode (e.g.[myshortcode request='buttontext']) . See [https://imgur.com/a/TGkMITl](https://imgur.com/a/TGkMITl) for an example.
`$content = \Elementor\Plugin::$instance->frontend->get_builder_content_for_display( 1013 );
 echo $content;`

Hopefully that's clearer.

**Comment by bainternet** [comment]
So like I said, If you want to use a shortcode as a control value, use 
Dynamic Shortcode and not just enter the shortcode string in the control.

thanks.

**Comment by jpknz** [comment]
Sorry I didn't notice the Dynamic button next to the text label field earlier.  Works as expected.
