### ISSUE TITLE
Manually creating a custom post type doesn't show ACF fields

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#7219]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I created a custom post type with the following code:

<pre>
function custom_post_type_servicos() {
register_post_type('servicos', array(
'label' => 'Serviços',
'description' => 'Serviços',
'public' => true,
'show_ui' => true,
'show_in_menu' => true,
'capability_type' => 'post',
'map_meta_cap' => true,
'hierarchical' => false,
'rewrite' => array('slug' => 'servicos', 'with_front' => true),
'query_var' => true,
'supports' => array('title', 'editor', 'page-attributes','post-formats'),
'menu_icon' => 'dashicons-menu',
'menu_position' => '1.1',

'labels' => array (
'name' => 'Serviços',
'singular_name' => 'Serviço',
'menu_name' => 'Serviços',
'add_new' => 'Novo serviço',
'add_new_item' => 'Adicionar novo serviço',
'edit' => 'Editar',
'edit_item' => 'Editar serviço',
'new_item' => 'Novos serviço',
'view' => 'Ver serviço',
'view_item' => 'Ver serviço',
'search_items' => 'Procurar serviços',
'not_found' => 'Nenhum serviço encontrado',
'not_found_in_trash' => 'Nenhum servios encontrado no lixo',
)
));
}
add_action('init', 'custom_post_type_servicos');
</pre>

The custom field appears, but it does not show the image as you can see in this video: https://streamable.com/zrch4Do

![custom-post-type-issue](https://user-images.githubusercontent.com/17693529/53407424-f6ceb700-399a-11e9-9ca1-8fa9465fd302.jpg)

Do I need [Custom Post Type UI plugin](https://wordpress.org/plugins/custom-post-type-ui/) to make it work the integration between new custom post types, ACF Pro and Elementor Pro?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>			
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Unix) OpenSSL/1.0.2g
	MySQL version: (Ubuntu) v5.7.25
	PHP Version: 7.3.2
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: http://mhr.artneo.com.br
	Home URL: http://mhr.artneo.com.br
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.12
		Author: Elliot Condon

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.10
		Author: Namogo

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

	Redirection
		Version: 3.7.3
		Author: John Godley

== Log ==
	: 
JS: showing 10 of 10JS: 2019-02-18 12:19:13 [error X 5][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:9:78] Unexpected token , 
JS: 2019-02-18 12:20:51 [error X 1][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:16:41] Unexpected token && 
JS: 2019-02-18 12:30:27 [error X 5][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:27:3] missing ) after argument list 
JS: 2019-02-18 12:30:28 [error X 6][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:27:3] Invalid or unexpected token 
JS: 2019-02-18 12:31:34 [error X 4][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:33:1] Unexpected end of input 
JS: 2019-02-18 12:32:46 [error X 3][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:32:1] Unexpected token } 
JS: 2019-02-18 12:35:25 [error X 1][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:25:28] Unexpected token . 
JS: 2019-02-18 12:35:28 [error X 3][http://mhr.artneo.com.br/wp-admin/post.php?post=13&action=elementor:25:39] Unexpected identifier 
JS: 2019-02-20 21:05:37 [error X 8][http://mhr.artneo.com.br/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.4:2:15986] Cannot read property \'model\' of undefined 
JS: 2019-02-22 19:53:38 [error X 2][http://mhr.artneo.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:6883] Cannot read property \'select2\' of undefined 

Log: showing 2 of 22019-02-20 11:35:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-22 08:55:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]

PHP: showing 3 of 3PHP: 2019-02-24 18:46:30 [notice X 38][/srv/users/serverpilot/apps/artneo-mhr/public/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-24 18:47:24 [notice X 3][/srv/users/serverpilot/apps/artneo-mhr/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::44] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-24 21:04:22 [notice X 1][/srv/users/serverpilot/apps/artneo-mhr/public/wp-content/plugins/elementor/includes/template-library/sources/local.php::674] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
</details>

**Comment by shilo-ey** [comment]
Hi @Artneo7 

Please provide steps to reproduce. Currently we cannot understand where from the problem origins.

Where from the images are withdrawn? is it the same field in all of the posts/categories?

**Comment by Artneo7** [comment]
First, I created the custom post type with the code above.

![02](https://user-images.githubusercontent.com/17693529/53414327-3dc5a800-39ad-11e9-8f23-e2c0cb1f5b68.jpg)

Then, created a custom image field with ACF Pro.

![03](https://user-images.githubusercontent.com/17693529/53414342-533ad200-39ad-11e9-92fb-37a99809620e.jpg)

Then, integrated it with Elementor Pro dynamic field. It appears, but when clicked doesn't show any output.

![01](https://user-images.githubusercontent.com/17693529/53414344-4918d380-39ad-11e9-9249-7b6c4ca7981e.jpg)

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
