### ISSUE TITLE
Mosaic of images page / gallary

### ISSUE THREAD

**Issue by BasilBahrani** [elementor/elementor#7222]
I have made a mosaic of images page on my website, www.tinamacnaughton.co.uk , on my general portfolio page, however, the way I have done it makes it a mess when viewed on a mobile phone. I have tried the image gallery widget but that only lets me have the images in line with each other rather than a mosaic effect or the images not aligned.

What I am looking for is a page template or an mosaic gallery widget that allows images to be brought in to create a simple mosaic effect.

**Comment by shilo-ey** [comment]
It is supported within Elementor. 

You can achieve this by using Image Gallery widget:
![image](https://user-images.githubusercontent.com/45009641/53413282-3f569680-39d4-11e9-840a-1cbff6d15e8f.png)

[Read more here](https://docs.elementor.com/article/66-image-gallery).

Thanks.

**Comment by BasilBahrani** [comment]
Sorry that is not a mosaic at all and not what I am trying to achieve and it is not supported by using image gallary so I am very disappointed with this reply.

    On ‎Tuesday‎, ‎26‎ ‎February‎ ‎2019‎ ‎12‎:‎39‎:‎39‎ ‎GMT, shilo-ey <notifications@github.com> wrote:  
 
 
It is supported within Elementor.

You can achieve this by using Image Gallery widget:


Read more here.

Thanks.

**Comment by BasilBahrani** [comment]
Are you kidding me ???? ….. if this is the level of understanding then I am very disappointed.  The issue has now been addressed and I would like it re-opened ASAP please.
Not impressed at the moment.
    On ‎Tuesday‎, ‎26‎ ‎February‎ ‎2019‎ ‎12‎:‎39‎:‎39‎ ‎GMT, shilo-ey <notifications@github.com> wrote:  
 
 
Closed #7222.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
