### ISSUE TITLE
Elementor Multisite key enable

### ISSUE THREAD

**Issue by tuf08694** [elementor/elementor#7224]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Hello, We just purchased Elementor Pro today and we are doing some testing in our multisite environment. I wanted to know if there is a way to enable the license key for all sites that have the plugin enabled, this way end users do not have to add the key when ever they add the plugin. 

**Describe the solution you'd like**

An example of this is gravity forms has a define variable that lets you add the license key for every site on the multisite environment. 

https://docs.gravityforms.com/wp-config-options/#gf-license-key 

**Describe alternatives you've considered**
Have a setting where you can enter the key for all sites across the multisite environments sites.

**Additional context**

**Comment by shilo-ey** [comment]
@tuf08694 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

for now, you can use the WP CLI command with looping over the sites, ex:
```
wp site list --field=url | xargs -n1 -I % wp --url=% elementor-pro license activate XXXXXXX
```
Thanks for the feedback.
