### ISSUE TITLE
Mosaic page template or widget

### ISSUE THREAD

**Issue by BasilBahrani** [elementor/elementor#7225]
I have made a mosaic of images page on my website, www.tinamacnaughton.co.uk , on my general portfolio page, however, the way I have done it makes it a mess when viewed on a mobile phone. I have tried the image gallery widget but that only lets me have the images in line with each other rather than a mosaic effect or the images not aligned.

What I am looking for is a page template or an mosaic gallery widget that allows images to be brought in to create a simple mosaic effect.

Before anyone replies saying that you can achieve this by using Image Gallery widget, no you can not as the image gallary only allows you to have images all the same size in a matrix and not a mosaic.

**Comment by shilo-ey** [comment]
Hi @BasilBahrani 

If you had followed our issue report or feature request templates, we would have a better understanding of what you're asking/requesting/reporting.

Now that you have clarified, this feature is not supported, but we will look into it in the future if we see a large demand for it.

I merged this issue with #4279, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
