### ISSUE TITLE
Header Display Conditions not working in Beta 2.5

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7226]
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

Can choose the second level in the display options but not the third

![screenshot 2019-02-26 at 15 21 47](https://user-images.githubusercontent.com/5225886/53426193-703bc900-39de-11e9-8ad9-ab1d91e549f0.png)

Roll back to 2.7 and it works. Using Beta 2.5 and it allows all pages but no 3rd level selection (same for categories etc)

**Comment by shilo-ey** [comment]
Hi @stevewoody82 

Thanks for reporting, but please keep beta related issues in the beta thread.

This issue has already been reported and fixed, please update to beta3 and you will see the fixed conditions.

Thanks
