### ISSUE TITLE
Social Icon "official" background color for Instagram

### ISSUE THREAD

**Issue by Mycelus** [elementor/elementor#7227]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It will display the official color gradient for the Instagram icon for the social icons 

**Describe the solution you'd like**

Update the color background gradient to https://cdn2.hubspot.net/hubfs/2973355/blog/blog-images/original-1.jpg

**Describe alternatives you've considered**

**Additional context**

Currently it is black, example: https://i.imgur.com/yUV0kdn.png

Instagram color gradient: https://freebiesui.com/wp-content/uploads/2017/06/instagram-color-palette-psd-resource-2017.jpg

Instagram official logo: https://cdn2.hubspot.net/hubfs/2973355/blog/blog-images/original-1.jpg

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

maybe this could be possible once we implement #4430 
Thanks for the feedback.

**Comment by MDCR55** [comment]
Hello @shilo-ey, is there any update on fixing the color of the icon ?

**Comment by Franky-Four-Fingers** [comment]
Still not fixed, the official background color of IG is not black!!

**Comment by glanglois** [comment]
Hi Team,

I have the same issue as described here. The Instagram logo background is black instead of using the Official Color, when I am setting this option. Is the issue currently solved? If yes, is there a specific fix to apply?

Thanks. Regards,

**Comment by FrostyTeeth** [comment]
Following

**Comment by scottnailon** [comment]
Thank you. That was bugging the hell out of me :D
