### ISSUE TITLE
Text Drag in Preview Window

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7229]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The ability to easily drag text / headline elements in the preview window

**Describe the solution you'd like**
On first click, allow the ability to drag the text element so that (like with images) we can move them into different locations

**Describe alternatives you've considered**
right now to achieve this I need to click and drag from the top left corner

**Comment by shilo-ey** [comment]
Hi @stevewoody82 

You can already do that by dragging the widgets form the edit handle (pencil icon).

thanks.
