### ISSUE TITLE
2.5.0-beta 3 issue - 500 error when Jet Elements Version 1.15.3 is enabled

### ISSUE THREAD

**Issue by mjpaulus** [elementor/elementor#7230]
@shilo-ey 
Beta 3 gives 500 error if Jetelements plugin is installed. Works after it´s deleted, wasn´t any problems with beta 2.

System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.0.0
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.15-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: http://clangnbang.flywheelstaging.com
	Home URL: http://clangnbang.flywheelstaging.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Clang N Bang
	Version: 1.0.0
	Author: DullRazor
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.9
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

== Active Plugins ==
	Advanced Excerpt
		Version: 4.2.5
		Author: WPKube

	Astra Pro
		Version: 1.6.14
		Author: Brainstorm Force

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Ele Custom Skin
		Version: 1.0.9
		Author: Liviu Duda

	Elementor
		Version: 2.5.0-beta3
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.6
		Author: rocketgenius

	Login or Logout Menu Item
		Version: 1.1.1
		Author: cartpauj

	Menu Items Visibility Control
		Version: 0.3.7
		Author: Hassan Derakhshandeh

	PowerPack Elements
		Version: 1.3.9.1
		Author: Team IdeaBox - PowerPack Elements

	Raven
		Version: 1.0.3
		Author: Artbees

	Restrict Content Pro
		Version: 3.0.0-beta-1
		Author: Restrict Content Pro Team

	Restrict Content Pro - Campaign Monitor
		Version: 1.0.3
		Author: Pippin Williamson

	Restrict Content Pro - WooCommerce Member Discounts
		Version: 1.0.4
		Author: Restrict Content Pro Team

	SmartCrawl
		Version: 2.2.5
		Author: WPMU DEV

	Smush Pro
		Version: 3.1.1
		Author: WPMU DEV

	Ultimate Addons for Elementor
		Version: 1.9.2
		Author: Brainstorm Force

	WooCommerce
		Version: 3.5.5
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.14
		Author: WooCommerce

	WPMU DEV Dashboard
		Version: 4.6
		Author: WPMU DEV

== Log ==
	: 
Log: showing 12 of 122019-01-23 13:14:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.3',
)]
2019-01-23 13:14:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0-beta3',
  'to' => '2.4.0',
)]
2019-01-28 01:21:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-28 14:14:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.2',
)]
2019-01-31 15:25:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-01-31 15:27:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-02-12 00:11:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-02-13 01:00:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-19 21:22:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-19 21:23:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-02-21 13:05:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.0-beta1',
)]
2019-02-26 12:22:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.0-beta1',
  'to' => '2.5.0-beta3',
)]

PHP: showing 6 of 6PHP: 2019-01-28 01:11:49 [notice X 1][/www/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-01-28 01:21:30 [error X 32][/www/wp-content/plugins/elementor-pro/includes/modules-manager.php::57] Uncaught Error: Class 'ElementorPro\Modules\QueryControl\Module' not found in /www/wp-content/plugins/elementor-pro/includes/modules-manager.php:57
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/plugin.php(319): ElementorPro\Manager->__construct()
#1 /wordpress/wp-includes/class-wp-hook.php(286): ElementorPro\Plugin->on_elementor_init('')
#2 /wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /www/wp-content/plugins/elementor/includes/plugin.php(475): do_action('elementor/init')
#5 /wordpress/wp-includes/class-wp-hook.php(286): Elementor\Plugin->init('')
#6 /wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#8 /wordpress/wp-settings.php(453): do_action('init')
#9 /www/wp-config.php(97): require_once('/wordpress/wp-s...')
#10 /wordpress/wp-config.php(5): require('/www/wp-config....')
#11 /wordpress/wp-l [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-01-28 05:37:08 [error X 20][/www/wp-content/plugins/elementor-pro/includes/modules-manager.php::57] Uncaught Error: Class 'ElementorPro\Modules\QueryControl\Module' not found in /www/wp-content/plugins/elementor-pro/includes/modules-manager.php:57
Stack trace:
#0 /www/wp-content/plugins/elementor-pro/plugin.php(319): ElementorPro\Manager->__construct()
#1 /wordpress/wp-includes/class-wp-hook.php(286): ElementorPro\Plugin->on_elementor_init('')
#2 /wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /www/wp-content/plugins/elementor/includes/plugin.php(475): do_action('elementor/init')
#5 /wordpress/wp-includes/class-wp-hook.php(286): Elementor\Plugin->init('')
#6 /wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#8 /wordpress/wp-settings.php(453): do_action('init')
#9 /www/wp-config.php(103): require_once('/wordpress/wp-s...')
#10 /wordpress/wp-config.php(5): require('/www/wp-config....')
#11 /wordpress/wp- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-03 15:59:35 [notice X 1][/www/wp-content/plugins/elementor-pro/modules/library/wp-widgets/elementor-library.php::140] Undefined index: template_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-06 01:34:52 [notice X 8][/www/wp-content/plugins/elementor/core/files/css/base.php::703] Undefined index: _id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-06 01:40:07 [error X 1][/www/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /www/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /www/wp-content/plugins/raven-v1.0.3/includes/modules/posts/module.php(79): Elementor\Elements_Manager->create_element_instance(Array)
#1 /wordpress/wp-includes/class-wp-hook.php(286): Raven\Modules\Posts\Module->ajax_get_render_posts('')
#2 /wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /wordpress/wp-admin/admin-ajax.php(99): do_action('wp_ajax_raven_g...')
#5 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2019-02-15 00:48:32 [error X 6][http://clangnbang.flywheelstaging.com/wp-admin/post.php?post=1977&action=elementor:2:5] Unexpected token < 
JS: 2019-02-15 00:49:02 [error X 2][http://clangnbang.flywheelstaging.com/wp-admin/post.php?post=1977&action=elementor:4:1] Unexpected end of input 
JS: 2019-02-15 00:49:04 [error X 3][http://clangnbang.flywheelstaging.com/wp-admin/post.php?post=1977&action=elementor:2:63] missing ) after argument list 
JS: 2019-02-20 00:47:37 [error X 6][http://clangnbang.flywheelstaging.com/wp-content/plugins/powerpack-elements/assets/lib/instafeed/instafeed.min.js?ver=1.4.1:2:5254] No user specified. Use the \'userId\' option.

**Comment by shilo-ey** [comment]
Hi @mjpaulus 

Thanks, we will update JetElements developers to revert the change we made as well.

Thank you for sharing this info.
