### ISSUE TITLE
Elementor: How do i get rid of the blue active background colour in the enu?

### ISSUE THREAD

**Issue by n1k1dk** [elementor/elementor#7233]
Hey guys!
i have the problem that my Elementor nav menu shows me in the active mode a blue colour that i can´t change anywhere. 
Do maybe someone knows where i can fix that?

Thanks for your help!

![unbenannt](https://user-images.githubusercontent.com/48036278/53455277-32fd2880-3a2a-11e9-8582-39b827df2165.PNG)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
