### ISSUE TITLE
javascript frontend/element_ready/{elementType.skinName} hook is not fired when dragging and dropping in same location

### ISSUE THREAD

**Issue by Spartanace1024** [elementor/elementor#7234]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementors `elementorFrontend.hooks.addAction( 'frontend/element_ready/{elementType.skinName}')` hook is not fired when dragging and dropping a widget in the same place.

## Steps to reproduce

1. Create a widget.
2. Add javascript below to view when element ready of widget is fired
```
    elementorFrontend.hooks.addAction( 'frontend/element_ready/{elementType.skinName}', (scope,jquery) => {
                console.log("Element Ready");
            } );
```
3. Drag widget into page.
4. Drag and drop widget into same location on page Example below.
![ea9d65f7-5862-495c-ab3f-deb37b325fb7](https://user-images.githubusercontent.com/2967721/53462313-41cae780-39f8-11e9-8a12-2c8502c5e659.GIF)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: MySQL Community Server (GPL) v5.7.23
	PHP Version: 7.2.9
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://fun-fast-chinese-sutitle-videos.local
	Home URL: http://fun-fast-chinese-sutitle-videos.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Nineteen
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.84
		Author: ServMask

	Debug Bar
		Version: 0.8.4
		Author: wordpressdotorg

	Double Subtitled Video
		Version: 1.0
		Author: Thomas Brown

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.0
		Author: Elementor.com

	Jetpack by WordPress.com
		Version: 6.8.1
		Author: Automattic

	MemberPress Basic
		Version: 1.3.52
		Author: Caseproof, LLC

	WooCommerce
		Version: 3.5.3
		Author: Automattic


== Log ==
	: 
Log: showing 1 of 12019-02-27 02:48:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.6',
  'to' => '2.4.7',
)]


				
```
</details>

**Comment by bainternet** [comment]
@Spartanace1024 	


Seems like the right and expected behavior, since there is no real change, the hook should not be triggered.

thanks.

**Comment by Spartanace1024** [comment]
Hmm is there any way to tie into this event then? Unfortunately a widget of mine stops functioning when the drag and drop at the same position occurs. Because the event doesn't fire it doesn't reinitialize properly. 

So I'm wondering how I might detect this drag and drop on the same location so I can reinitialize it.

**Comment by Spartanace1024** [comment]
Would still love a response on this one :)
