### ISSUE TITLE
Regenerate post CSS (in wp-content/uploads/elementor/css) when missing

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7237]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

If a post CSS file auto-generated by Elementor in the folder `wp-content/uploads/elementor/css` folder is missing, it's not recreated when either a logged-in or not logged-in user displays the page.

I have the feeling that it was different at some point and the behaviror changed recently. Indeed, when we deploy a site, we flush the CSS cache using the dedicated WP CLI command. Beofre, Elementor was recreating the styles automatically (don't know exactly when). Now, it doesn't and we have to go to "Tools" > "Regenerate CSS".

I think it would be a good idea to regenerate the CSS file if missing on page load.
Adding a WP Cli command to regenerate the CSS cache globally after being flushed could be usefull.

## Steps to reproduce

Create a post with Elementor. Publish it. Go to the `wp-content/uploads/elementor/css` folder. Delete the `post-XX.css` file. Browse to the page. You will get a 404 error on the style file you just deleted. Elementor will never recreate it.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Elementor v2.4.7
Elementor Pro v2.4.5
WordPress 5.1

**Comment by bainternet** [comment]
@tristanleboss 

Elementor create the CSS file only once unless you update and there is regenerated for the updates to apply.  

There is no reason for the file to get deleted unless you have a 3rd party code which does that, then it should be up to him to notify Elementor that the CSS needs to be regenerated.

Checking if the file exists on every page load is simply bad performance and like I said there is no real reason for that.


Also, there is a WP-CLI command to flush the CSS files:
`wp elementor flush_css` 

ref: https://docs.elementor.com/article/461-wp-cli

thanks.

**Comment by tristanleboss** [comment]
Yes but, for me, flush means "To clear something of its contents.". Does the "flush_css" WP Cli command remove the files AND recreate them?

**Comment by pacotole** [comment]
> There is no reason for the file to get deleted unless you have a 3rd party code which does that, then it should be up to him to notify Elementor that the CSS needs to be regenerated

How can inform Elementor that the CSS needs to be regenerated for a Header/Footer template?

**Comment by NAROLLES** [comment]
@pacotole @tristanleboss @bainternet 
Good morning
I'm joining this discussion because I'm having the same problem.
I seem to have identified the problem....I emptied memcached on the server and I deactivated the jetpack plugin and at the same time as I make this message I open a ticket with jetpack
To be continued

**Comment by abdobsg** [comment]
> > There is no reason for the file to get deleted unless you have a 3rd party code which does that, then it should be up to him to notify Elementor that the CSS needs to be regenerated
> 
> How can inform Elementor that the CSS needs to be regenerated for a Header/Footer template?

going to WP admin > Elementor > Tools > Regenerate CSS. Then, you can clear the cache (WP cache and browser cache) and refresh the page.

**Comment by buckmanhands** [comment]
What do you do when using the Tools->Regenerate CSS does not bring the missing CSS file back?

**Comment by shane-js** [comment]
I am experiencing this too using Azure Wordpress which sets up W3 Total Cache Azure blobstorage CDN. Manually looking the css files are not found in the uploads dir anywhere. Regenerating appears to do nothing as well (even if followed uploading custom files in W3).

**Comment by huynhlongdev** [comment]
How to move "wp-content/uploads/elementor/css/post-x" in footer when using Elementor\Plugin::instance()->frontend->get_builder_content_for_display(12, true) to head tag. I want the css to load before the DOM is finished loading

**Comment by shashwat-kalpvaig** [comment]
After regenerating, it doesn't do anything. There is no css file.

**Comment by miguel-cravidao** [comment]
I get the same problem, specifically on some projects. Although, all the projects use the same WordPress stack and hosting.

Once the problem starts... I dont understand how i can solve it. Tried all the steps/tips previously shared, but in some cases it just doesn't work.

I've disabled also Object Cache, Varnish Cache, NGINX Cache and WordPress cache and the problems persists. Very hard to debug and even harder to fix.

**Comment by alexbovey** [comment]
I also have this issue on lots of sites and have been unable to find the cause.  With all of those experiencing the issue, is there a particular pattern?  The majority of my sites are hosted on Cloudways with their Breeze/varnish cache.  I haven't 100% been able to verify it, but I presume that setting Elementor to output the CSS in the page <head> will solve the issue.

**Comment by ezoer-elementure** [comment]
Same here. It seems to be happening randomly and 'regenerating' CSS files does not bring back the missing CSS files. It would be nice if it did... So Elementor, how do you force the editor (because the pages look just fine in the editor) force to regenerate CSS for a page?

**Comment by ichx123** [comment]
We have the same problem, some css-files are missing, if i update the plugins above 3.26.2 and no "regenerate css"-files gets them back. I even attempted to change a little thing on the sites and save it again, but i could not get them working. We work on hello-theme, so the theme should not be the problem... I deactivated every caching-plugin (wp fastest cache) and memcached - but no difference. When rolled back to 3.26.2, everything is working again. It looks like it is a caching problem, but with everything disabled, i no longer know what to do, to solve this issue.

Strange is, that the staging-site, on the same server, just in another subfolder and on a subdomain with the exact same setup has no problems with this.

**Comment by ezoer** [comment]
Just wanted to chip in a bit more. Last week I moved one of my sites to another server and sure enough regenerating the CSS files did not work. I looked at the logs and found the error causing this in the website logs. Basically, the WordPress database maintains absolute path names for the CSS files. So guess what if your website paths change? Regenerating CSS files no longer works. There are two ways to fix this:

1. Edit the database (post_meta) and fix the references to CSS files to point to the correct path names
2. Change the CSS to be included in the page's HEAD

Personally, in the end I did not feel like editing the database and opted to include the CSS in the page's HEAD instead. Apparently not the best for performance but my site loads fine.

@elementorbot You should not store absolute paths in the database to reference the post CSS files.

**Comment by web043** [comment]
> Just wanted to chip in a bit more. Last week I moved one of my sites to another server and sure enough regenerating the CSS files did not work. I looked at the logs and found the error causing this in the website logs. Basically, the WordPress database maintains absolute path names for the CSS files. So guess what if your website paths change? Regenerating CSS files no longer works. There are two ways to fix this:
> 
> 1. Edit the database (post_meta) and fix the references to CSS files to point to the correct path names
> 2. Change the CSS to be included in the page's HEAD
> 
> Personally, in the end I did not feel like editing the database and opted to include the CSS in the page's HEAD instead. Apparently not the best for performance but my site loads fine.
> 
> [@elementorbot](https://github.com/elementorbot) You should not store absolute paths in the database to reference the post CSS files.

What you're describing also sounds like these issues:
- https://github.com/elementor/elementor/issues/25855
- https://github.com/elementor/elementor/issues/25553
- https://github.com/elementor/elementor/issues/27205#issuecomment-2123633774

Where the URL is also generated and stored incorrectly

Storing absolute paths doesn't have to be an issue by itself, WordPress does so itself as well. However, they should be generated **and** updated correctly at all times.

**Comment by ulkoalex** [comment]
> regenerating the CSS files did not work.

Also had this issue, the reason was in object cache conflict, but also "Regenerate CSS" doesn't actually regenerate anything, only deletes the existing files, and writes them when requested to enqueue only.

I found there's always `false` returned in `\Elementor\Core\Files\CSS\Post::is_update_required()` (extended from `\Elementor\Core\Files\CSS\Base`) so the CSS file is never written if it's missing on the server due to some reason (just deleted or `_elementor_css` post meta gets out of sync due to some cache issues etc)
From `\Elementor\Core\Files\CSS\Base::enqueue()`:
```
do_action( 'elementor/css-file/before_enqueue', $this );
// First time after clear cache and etc.
if ( '' === $meta['status'] || $this->is_update_required() ) {
	$this->update();
	$meta = $this->get_meta();
}
```
Adding a simple `file_exists()` or checking file timestamp would solve the issue. As @bainternet [said](#issuecomment-467822193) it's avoided as unnecessary, but if you need it - you can add it without much worrying about few extra microseconds added by file_exists (it's SSDs everywhere now). Can be added externally via the action:
```
add_action( 'elementor/css-file/before_enqueue', function( $css ) {
	if ( $css instanceof \Elementor\Core\Files\CSS\Post ) {
		$meta = $css->get_meta();
		if ( is_array( $meta ) ) {
			// If these $meta params are empty then Elementor will update the file and we don't have to, to avoid double update
			if ( $css::CSS_STATUS_FILE === $meta['status'] && $meta['time'] ) {
				$path = $css->get_path();
				if ( $path && ! file_exists( $path ) ) {
					$css->update();
				}
			}
		}
	}
} );
```
Hope it helps someone!
