### ISSUE TITLE
Display categories through menu without title

### ISSUE THREAD

**Issue by slatuff** [elementor/elementor#7238]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by slatuff** [comment]
Hello! I want to display different post categories on different pages (so it will look like two separate blogs). The title of categories: xxx shows up and I can't figure out how to remove it. I'm pretty new to all this. Thanks.
![screen shot 2019-02-25 at 16 29 49](https://user-images.githubusercontent.com/48053139/53484974-f870ab80-3a7c-11e9-9175-ba1f743da578.png)

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
