### ISSUE TITLE
Popup closes when you scroll down the month of a date field inside the popup

### ISSUE THREAD

**Issue by Knoclar** [elementor/elementor#7240]
Hi elementor,
There's a bug when I use date field (in form widget):
When I want to change the month by clicking on left or right arrow to the top of datepicker, the popup closes automatically, and only date picker stays

**Comment by shilo-ey** [comment]
Hi @Knoclar 

Thanks for reporting, we will take a look and try to fix it.

Stay tuned to this thread.

Thanks

**Comment by shilo-ey** [comment]
@Knoclar 
This behavior is known issue with flat-picker (the library we are using)

Currently, you set the datepicker to use the Native HTML5 when using popup.

Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.0

Feel free to update

Thanks!
