### ISSUE TITLE
Remove Image size custom

### ISSUE THREAD

**Issue by timsamuelsson** [elementor/elementor#7242]
Hi,

Is there a way to remove the image size value "Custom" in the image size dropdown?

I found that it is added on row 352 in image-size.php:

`		
if ( ! empty( $args['include']['custom'] ) || ! in_array( 'custom', $args['exclude'] ) ) {
	$image_sizes['custom'] = _x( 'Custom', 'Image Size Control', 'elementor' );
}
`

I cant figure out how to add the exclude arg :(

**Comment by bainternet** [comment]
You can use the `update_control` method and provided hooks to remove an option for a control, for example:

```PHP
add_action( 'elementor/element/image/section_image/before_section_end', function( $control_stack, $args ) {
	// Get existing control
	$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), 'image_size' );
	// remove custom
	unset( $control['options']['custom'] );
	// Update the control
	$control_stack->update_control( 'image_size', $control );
}, 10, 2 );
```

thanks.

**Comment by timsamuelsson** [comment]
Thanks alot it helps for the image widget. But what i need is a solution to remove it for all inctances of the "Image Size dropdown". For example The feature image wiget.

I know i can check all widgets for that , but whats im really looking for is a general solution to remove that option from all Widgets. Its a pain when using thirdparty widget libraries...

Do you know if that is possible?

**Comment by timsamuelsson** [comment]
Is there a filter that i missed that could help me to set $this->args in Group_Control_Image_Size?

**Comment by timsamuelsson** [comment]
I managed to solve it my self, but sharing the info if some one else needs it.

```php
add_action('elementor/element/before_section_end', function (\Elementor\Controls_Stack $control_stack, $args) {
    $control = $control_stack->get_controls('image_size');

   //Exit early if $control_stack dont have the image_size control
    if (empty($control) || !is_array($control)) {
        return;
    }

    //remove custom
    unset($control['options']['custom']);
    // Update the control
    $control_stack->update_control('image_size', $control);
}, 10, 2);
```

**Comment by Shopdev99** [comment]
Great, thanks for sharing. This is solving a big problem of mine.

**Comment by tfrank77** [comment]
Hi,
Any chance you updated your code, so it works with the new Elementor version? (v3.20)

Thanks

**Comment by ahait** [comment]
The way I made it work, was I only wanted my custom image presets in elementor, so it's like this:
`function remove_extra_image_sizes() {
    foreach ( get_intermediate_image_sizes() as $size ) {
        if ( in_array( $size, array( 'thumbnail', 'medium', 'medium_large', 'large', 'small', '1536x1536', '2048x2048') ) ) {
            remove_image_size( $size );
        }
    }
}
add_action('init', 'remove_extra_image_sizes', 90);
add_action('after_setup_theme', 'remove_extra_image_sizes', 90);`

**Comment by tfrank77** [comment]
> The way I made it work, was I only wanted my custom image presets
Have you tried the latest Elementor version?
It didn't work for me, unfortunately.
<img width="471" alt="Screenshot 2024-04-23 at 09 48 06" src="https://github.com/elementor/elementor/assets/28020154/9e85a8b5-3c97-4475-a0e0-50660da0b131">
