### ISSUE TITLE
Mailster compatible with elementor form widget

### ISSUE THREAD

**Issue by antonio86itna** [elementor/elementor#7247]
Hi, I hope you implement mailster compatibility in the next update. This would be very important for thousands of people. I can guarantee you that many people use mailsters, but those who love easy things, would be happy to have compatibility with your widget for the forms.

Mailster does not allow you to create forms easily and you need to know html and css, while if among your options "actions after sending" put the full compatibility even with mailster would be super fantastic.

I think you also know me mailster better and that many people use it. I think it is a good addition for you, which would also bring more traffic to you for those who just do not know anything about html and do not want to pay external services for newsletters.

So Elementor + Mailster would become the TOP to choose for experts and less experts.

I hope it is implemented, I would like it too soon :) One more reason to renew my pro subscription with you

**Comment by shilo-ey** [comment]
Hi @antonio86itna 

Welcome to Elementors' GitHub,
Next time please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.


As for your request: a quick search in the repo lead me to this [previous request and the response](https://github.com/elementor/elementor/issues/2397#issuecomment-361175579)

Thanks.
