### ISSUE TITLE
Hide specific form after submit_success

### ISSUE THREAD

**Issue by caluwaek** [elementor/elementor#7249]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Users with multiple forms will be able to choose which form to hide and replace by a success message

**Describe the solution you'd like**
After a user has succesfully submitted a form that form will be closed and a success message will be shown.

**Describe alternatives you've considered**
This issue is related to issue #5031 and #3397.  I built further on the code shown in issue 5031.  This is what I came up with:

```HTML
<script>
jQuery( document ).ready(function( $ ){
$( document ).on('submit_success', function(){
// form has been succesfully submitted
$("#Japan_Checklist_UK_popup_form").hide();
$("#Japan_Checklist_UK_popup_form_submit_succes").removeClass('hidden');
$("#Japan_Checklist_UK_popup_form_submit_succes").addClass('visible');
});
});
</script> 
```

I place the code in my header in Wordpress but the issue is that I have multiple forms.  I want to be able to hide the form that is submitted.  So my code should rather be something like:

```HTML
<script>
jQuery( document ).ready(function( $ ){
$( document ).on('submit_success', function(){
// form has been submitted check which form
  if(submitted_form = 'Japan_Checklist_UK_popup_form) {
        $("#Japan_Checklist_UK_popup_form").hide();
        $("#Japan_Checklist_UK_popup_form_submit_succes").removeClass('hidden');
        $("#Japan_Checklist_UK_popup_form_submit_succes").addClass('visible');
   }
   if(submitted_form = 'other_popup_form) {
        .....
   }
});
});
</script> 
```

The other solution would be to place the Jquery code for each popup only on the pages where that popup is shown but I don't think that is possible.

**Additional context**

**Comment by bainternet** [comment]
@caluwaek 

Once the form is submitted successfully the `submit_success` event is triggered directly on that form so you can act on the form directly, ex:

```JS
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		$submitted_form = $( this );
		$submitted_form.hide();
	});
});
```

Or you can set handlers per each spesific form:

```JS
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', '#FORM_ID', function(){
		$submitted_form = $( this );
		$submitted_form.hide();
	});
});
```

thanks.

**Comment by jcues** [comment]
I was able to hide the form. However, I would like to show a custom message. Could you please help me with that? Thanks a lot!

**Comment by tatumrae** [comment]
@jcues 

I was able to just complete this by further modifying the code that @bainternet posted...

First - I created a success message with the text editor and hid it on all devices. I also gave it a unique ID.

Then I modified the code to show:
`<script>
   jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', '#credit-report-form', function(){
		$submitted_form = $( this );
		$submitted_form.hide();
		$('#form-success-message').show(); // this is the sucess message that I created.
	});
	
});
</script>`

It might not be the cleanest option, but it worked for me!

**Comment by gb3000** [comment]
This doesn't work on multistep forms, as it seems to reset on every submit. Any clue how to achieve this on multistep?

**Comment by wordpressman** [comment]
The original code works, but the @jcues doesn't work anymore, because the message doesn't display.
It seems that Elementor form code changed, because I don't see any "#form-success-message" in the code.
I see a class ".elementor-message-success", so I tried that to replace it with that, but it doesn't work !

If anybody could help, that would be great, because this is quite useful...

**Comment by williamjdvries** [comment]
Not a coding expert, but I modified the code a bit. This works for me:

`<script>
   jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', '#FORM_ID', function(){
		$submitted_form = $( '#FORM_ID .elementor-labels-above');
		$submitted_form.hide();
	});
	
});
</script>`
