### ISSUE TITLE
🚀 Add VideoPress support to the Image Carousel widget

### ISSUE THREAD

**Issue by xbnextel** [elementor/elementor#7251]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add videos to image carousel hosted in videopress
**Describe the solution you'd like**
add videopress shortcode support
**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
