### ISSUE TITLE
🔗 🚀 Feature Request: Timed announcements with popups (Duplicate of #6899)

### ISSUE THREAD

**Issue by bellamystudio** [elementor/elementor#7252]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to make some eyecatching TIMED popup announcements to let people know when a public facility is unavailable (ie due to weather, or maintenance)

**Describe the solution you'd like**
Essentially I want to publish a custom post ('announcement') - give it a start and end date, a title and some copy (and maybe a category) and have a popup appear while this announcement post is live (ie after start date, before end date) - I can handle the dates with a plugin, but not the popup (I don't think)

**Describe alternatives you've considered**
I looked at the 3rd party 'widget options' plugin to see if I could make this work with that, but it's not possible

**Comment by sweethoneycode** [comment]
What about an announcement bar and have it use a function to check beginning and end date?

Popups are meant to be dismissed and if this is announcement for something major like facilities under maintenance, you wouldn't want it to go away with a close box.

**Comment by bellamystudio** [comment]
I think this could still work under the 'Advanced Rules' section - "Show between these dates" [start_datetime] [end_datetime] - I think the ability to schedule popup announcements would be useful for a lot of people (retailers etc)

**Comment by lior-sh** [comment]
Same as [#6899](https://github.com/elementor/elementor/issues/6899). Closed
