### ISSUE TITLE
Icons in menu and text aligned to the left

### ISSUE THREAD

**Issue by emv-plus** [elementor/elementor#7254]
Hi all!

I'm not sure whether I'm at the right place here, so please let me know If I'm wrong :-)

I have a problem using icons in my main menu. Page and menu was created using elementor. 
Whenever I add an icon to the menu (tried several methods), the icon appears on the left and the text is aligned to the right. That looks awful!
That's how I did it in the end:

![image](https://user-images.githubusercontent.com/46753954/53568438-490e0480-3b62-11e9-9e2f-c277439a0c3c.png)
Coming to that result:
![image](https://user-images.githubusercontent.com/46753954/53568604-c89bd380-3b62-11e9-9f86-1654657f99ee.png)

Can anyone let me please know how I can make it look nicer? I'd like to have all icons aligned to the left, then a little space (equal in every line) and the the text, as well aligned to the left.

Please note: I'm not tooooo experienced with all that, but for sure I can follow instructions :-)

Thank you very much!!

Bye,
Eva

**Comment by shilo-ey** [comment]
Hi @emv-plus,

You are currently adding the FontAwesome class to your menu items list.
The only way you can modify the desired style is with custom CSS.

Try something like:

```CSS
li.menu-item.fa:before {
    float: right;
}
```

Although we can't give you general code, this needs to be done specifically for each website.

Good luck!
