### ISSUE TITLE
A "stack widget" to create content animations.

### ISSUE THREAD

**Issue by NanaDada** [elementor/elementor#7255]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor Pro. 

**What problem is your feature request going to solve? Please describe.**
It enables us to create more interesting content.

**Describe the solution you'd like**
The idea is this:
1. Imagine a variable number of pages/cards placed on top of each other.
2. Each of this pages/cards contains arbitrary html.
3. Rotate through each of these pages/cards and display only one of them for a configurable number of seconds. 
4. Don't have any animations to switch between the pages/cards.  

This would enable us to create content-animations. For example, it could be used to slowly add bullet points to a list. Product descriptions and tutorials could be made more interesting with this.

**Describe alternatives you've considered**
* It's basically very similar to the "Tabs" component. Just without the tabs/frame around it, but with a delay to switch between the shown content.
* The "Slides" component of Elementor-Pro is very similar as well, however it does not provide the full editor for it's content and neither the animation nor the button can be disabled.

**Additional context**
In an ideal case all of pages/cards in the stack would share the same height to prevent any content below it from bouncing. It would also be useful if the last page could have a longer delay than the previous pages.

**Comment by shilo-ey** [comment]
Hi @NanaDada 

I merged this issue with  #219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Carousel was released with Elementor Pro v3.14.0! 🥳 

You can now create Carousels or Slides with custom nested widgets without needing to use shortcodes or other features! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
