### ISSUE TITLE
Unregister WordPress Elementor widgets

### ISSUE THREAD

**Issue by vegancreampie** [elementor/elementor#7256]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I've been cleaning out the widget library on my site of widgets that don't/shouldn't be used by me or anyone else by using `$widgetManager->unregister_widget_type($widget)` ([similarly like this](https://github.com/elementor/elementor/issues/1896#issuecomment-314370960)). I've figured out each widgets name and id by using `Elementor\Plugin::$instance->widgets_manager->get_widget_types_config()` but I can't find a way to get the information I need for removing the WordPress widgets. They seem to be handled by a separate manager (`wordpress_widgets_manager`) which doesn't seem to contain much of functionality. 

Although, I found that by manually removing the WordPress category from the `Elements_Manager` I got rid of all the WordPress widgets in the editor. But I don't seem to find any function to do it properly for me (ex: `Elements_Manager::remove_category()`).

Not sure if you have any solution for me at the moment and that it might be a feature request. I hope for the former.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
You can use the same method to unregister these widgets, you just need to know their names. See this snippet which loops over all of the WordPress widgets and unregistered the Elementor version of them.

```PHP
add_action( 'elementor/widgets/widgets_registered', function( $widgets_manager ) {
	global $wp_widget_factory;
	/**
	 * @var \Elementor\Widgets_Manager $widgets_manager
	 */
	foreach ( $wp_widget_factory->widgets as $widget_class => $widget_object ) {
		$widgets_manager->unregister_widget_type( 'wp-widget-' . $widget_object->id_base );
	}
}, 200 );
```

thanks.
