### ISSUE TITLE
Dynamic Content in Price List Widget

### ISSUE THREAD

**Issue by ThrudUK** [elementor/elementor#7258]
Would be really useful to have dynamic content in the price list widget.  Particularly for the link so that we can use it to open a popup!

**Comment by shilo-ey** [comment]
Hi @ThrudUK 

Thanks for your feedback, we will add this option the next version of Elementor Pro.

Next time, please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by lacccci** [comment]
Hi Elementor

You have changed the Title, the Description, the Image and the Link to dynamic, but the PRICE?
I think it is only a mistake. If not all of the elements are dynamic this "dynamic" feature is barely usable.

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field.
