### ISSUE TITLE
Pop Up in Nav Menu

### ISSUE THREAD

**Issue by Maxphill** [elementor/elementor#7259]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's not possible to create Pop Ups that will be activated by clicking a point in nav menu.

**Describe the solution you'd like**
With Popup Maker Plugin it's possible to create individual links for the nav menu with a PopUp Function. Would be great to have this feature in Elementor.

BTW: creating a seperate button and placing it beside the Nav widget is not the solution. Because I want to have hamburger navigation only.

**Comment by shilo-ey** [comment]
I merged this issue with  #6876, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
