### ISSUE TITLE
Page layout automatically changes to default after inserting saved template

### ISSUE THREAD

**Issue by humanware** [elementor/elementor#7260]
I have saved templates, like page header, testimonials block etc.

Everytime I import templates to my elementor page it automatically changes page layout from 'Elementor Full Width' to 'default'.

Is this the bug? it really annoys to change page layout to 'full' after importing templates.

![screenshot_3](https://user-images.githubusercontent.com/4326658/53602166-1271d180-3bd6-11e9-8081-94a8ca7282e3.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by marclucraft** [comment]
# I have the same issue!
I hadn't linked it with using items from "My Templates" though, which could be the bug, Ijust thought it was after saving any page that I created.

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Page layout is not stored after creating a page. It reverts to Default, which is adding a sidebar that is not wanted.

## Steps to reproduce
1. Add a new page, and set Page Layout (in backend).
![1](https://user-images.githubusercontent.com/3025406/57078992-515ff880-6ce7-11e9-9189-ae00dca2f469.png)
2. Click "Edit with Elementor" and see canvas as intended
![2](https://user-images.githubusercontent.com/3025406/57079136-a56add00-6ce7-11e9-8d4f-4c2b89619f7b.png)
3. Add content, click Update in Elementor
![3](https://user-images.githubusercontent.com/3025406/57079354-13af9f80-6ce8-11e9-9e35-d03a1df8e667.png)
4. View the page - Voila, the sidebar is back?!
![4](https://user-images.githubusercontent.com/3025406/57079545-74d77300-6ce8-11e9-9ddd-81ee64bd266c.png)
5. Clicking "Edit with Elementor",  changing the "Page Layout" and clicking "Update" doesn't seem to rectify this.
-- Editing the page in WP Dashboard, and changing the Template saves the Page Layout (without a sidebar)

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.3, Revision 71967c9 v5.6.43-84.3
	PHP Version: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://moblicitinew.wpengine.com
	Home URL: https://moblicitinew.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: JupiterX
	Version: 1.3.0
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.7.12
		Author: Elliot Condon

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Jet Elements For Elementor
		Version: 1.15.10
		Author: Zemez

	Jupiter X Core
		Version: 1.2.0
		Author: Artbees

	Jupiter X Pro
		Version: 1.0.0
		Author: Artbees

	Raven
		Version: 1.2.0
		Author: Artbees

	Slider Revolution
		Version: 5.4.8.3
		Author: ThemePunch


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine System
		Version: 3.2.1
		Author: WP Engine


== Log ==
	: 
JS: showing 8 of 8JS: 2019-04-16 15:49:51 [error X 1][https://moblicitinew.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:212877] Cannot read property \'html\' of undefined 
JS: 2019-04-26 10:19:52 [error X 2][https://moblicitinew.wpengine.com/wp-admin/js/editor.min.js?ver=5.1.1:1:694] Cannot read property \'style\' of undefined 
JS: 2019-04-26 10:19:52 [error X 2][https://moblicitinew.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:215671] Cannot read property \'on\' of null 
JS: 2019-04-29 08:35:12 [error X 2][https://moblicitinew.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:130662] Cannot read property \'0\' of undefined 
JS: 2019-04-29 09:23:17 [error X 7][https://moblicitinew.wpengine.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:10531] n.attributes[t.name].each is not a function 
JS: 2019-04-29 15:57:20 [error X 1][https://moblicitinew.wpengine.com/wp-content/plugins/raven/assets/js/frontend.min.js?ver=1.2.0:1:40512] Cannot read property \'indexOf\' of null 
JS: 2019-05-02 13:01:28 [error X 1][https://moblicitinew.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:200070] Cannot read property \'css\' of undefined 
JS: 2019-05-02 13:01:28 [error X 1][https://moblicitinew.wpengine.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.5.14:2:8029] Cannot read property \'attributes\' of undefined 

PHP: showing 2 of 2PHP: 2019-04-24 14:34:19 [error X 2][/nas/content/live/moblicitinew/wp-content/plugins/elementor/includes/managers/elements.php::81] Uncaught Error: Call to a member function get_default_args() on array in /nas/content/live/moblicitinew/wp-content/plugins/elementor/includes/managers/elements.php:81
Stack trace:
#0 /nas/content/live/moblicitinew/wp-content/plugins/raven/includes/modules/posts/module.php(79): Elementor\Elements_Manager->create_element_instance(Array)
#1 [internal function]: Raven\Modules\Posts\Module->ajax_get_render_posts('')
#2 /nas/content/live/moblicitinew/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#3 /nas/content/live/moblicitinew/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /nas/content/live/moblicitinew/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /nas/content/live/moblicitinew/wp-admin/admin-ajax.php(167): do_action('wp_ajax_raven_g...')
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-26 15:40:09 [notice X 8][/nas/content/live/moblicitinew/wp-content/plugins/elementor/core/files/css/base.php::703] Undefined index: _id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by marclucraft** [comment]
@bainternet Should I have done this as a new issue???

**Comment by hiproductions** [comment]
I am having this same issue today in June 2022 - this has been going on a long time - has anything been done about this?
When I add a saved template to a page in Elementor, it automatically reverts back to the "default" template and I have to either repeatedly go back into the main page to change it back or just avoid using saved templates. This is horrible!

**Comment by scifirm** [comment]
Same issue faced by me also repeatedly.
Page layout changed automatically in elementor .
Date: 27/10/2022

**Comment by TuomoTiussa** [comment]
### I had the same issue!

I inserted a container template I had made and it gave this warning when inserting:
<img width="612" alt="Näyttökuva 2023-7-18 kello 14 20 58" src="https://github.com/elementor/elementor/assets/139871898/83241959-c236-4cad-a36f-5e283debbad0">

Obviously I clicked "yes" like rest of the people on this thread because I'm only inserting a container right?
Well sure enough it changed the layout and I needed to go to change the layout back to full width and hide page detailed
(change settings to what they used to be before inserting the container template)

### I resolved it

So I went back to insert the same element again but this time I clicked "don't apply" to the box
<img width="612" alt="Näyttökuva 2023-7-18 kello 14 20 58" src="https://github.com/elementor/elementor/assets/139871898/83241959-c236-4cad-a36f-5e283debbad0">

It inserted the template without changing the layout.

I hope this help, let me know if works for you
 @humanware
 @hiproductions 
 @scifirm

**Comment by charlieVallum** [comment]
Heya, mine also works if you press "Don't Apply" , but if you've already pressed "apply" is there a way to revert it back to how your page looked before? I've tried everything!

**Comment by charlieVallum** [comment]
That worked! Thanks so much, that's been bugging me forever!
