### ISSUE TITLE
run JavaScript code on click (button, image, etc.)

### ISSUE THREAD

**Issue by stefanhz** [elementor/elementor#7261]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor / Elementor Pro as confirmed by Elementor Support.

**What problem is your feature request going to solve? Please describe.**
I'd like to be able to run own JavaScript code and have it be launched by button or image click.

**Describe the solution you'd like**
One simple use case: Imagine having three separate sections with information and above those are three images (or buttons) all on the same page. Clicking any of the images (or buttons) would run a little JS code/function that displays one section and hides the other two. 

**Describe alternatives you've considered**
I understand this can be done via the HTML widget today but would require manual coding of the images and their formatting which defeats the point of Elementor.

**Additional context**

**Comment by unclerom** [comment]
https://docs.elementor.com/article/59-button this works for me

**Comment by sf-steve** [comment]
You can add CSS IDs or classes to the elements and attach click handlers to them in your JavaScript.

**Comment by shilo-ey** [comment]
Hi @stefanhz 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

As for now you can use custom JS code to listen to events in your page and trigger actions based on it. e.g:

```JS
jQuery( document ).ready(function( $ ){
	$( '#CSS_ID' ).on('click', function(){
		// Your action here
	});
});
```

Thanks for the feedback.
