### ISSUE TITLE
The global settings' values are not applying to the theme in 2.5.0-beta3

### ISSUE THREAD

**Issue by gulhangulez** [elementor/elementor#7262]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The global settings' values are not applying to the theme. I found this issue while testing Widget Space option in Global Settings which had no any effect on theme.

## Steps to reproduce
1- Create a new elementor page
2- Drag few elements into same column. (i.e: Text Editor element)
3- Go to Global settings > Widget Space and enter some value here to see the effect. Nothing will happen. (Regenerating Styles or Hard reload does not solve the problem.)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 5.6.40
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://devbees.net/jupiterx
	Home URL: https://devbees.net/jupiterx
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: JupiterX
	Version: 1.2.0
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.10
		Author: Elliot Condon

	Customizer Export/Import
		Version: 0.9
		Author: The Beaver Builder Team

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Jet Elements For Elementor
		Version: 1.14.10
		Author: Zemez

	Jupiter X Core
		Version: 1.1.0
		Author: Artbees

	Raven
		Version: 1.1.0
		Author: Artbees

== Log ==
	: 

				

```
</details>

**Comment by shilo-ey** [comment]
Hi @gulhangulez 

Thanks for reporting.

We couldn't replicate the issue you described.

Thanks.

**Comment by gulhangulez** [comment]
Hi @shilo-ey ,

I have recorded a video for you. Hope this helps.

Here is the video: https://monosnap.com/file/273jfu4SpRyEMlQkzLWa8Db5J1p3bz

Test details: Elementor Beta4 - With only 1 active plugin (http://prntscr.com/mszo3i) and "Twenty Sixteen" theme. Live & shared environment (Godaddy).

**Comment by shilo-ey** [comment]
Hi @gulhangulez 

Thanks for clarifying this.

Another user has reported this issue and we will address it ASAP.
Please follow here: #7309

Thanks!
