### ISSUE TITLE
Elementor Pro Menu Not Sticky on Chrome Browser

### ISSUE THREAD

**Issue by wacaszafar** [elementor/elementor#7263]
Hi, 

I have made a test site as below. Once I check is on browser stack like responsinator.com my menu is sticky on it however on Android in chrome browser menu is not sticky but works fine on firefox. please let me know what am I doing wrong?

You can see for yourself by opening below url. Thanks.

https://giloci.cloudaccess.host/

**Comment by Artneo7** [comment]
After latest updates the Scrolling effect > Stay In Column > ON does not work anymore. If it's turned off it works again…
![scrolling-effect-issue](https://user-images.githubusercontent.com/17693529/53656529-4ed31b00-3c32-11e9-8dbd-c5f8d44fd595.jpg)

**Comment by wacaszafar** [comment]
I don't see the option stay in column in the sticky section in my example site https://giloci.cloudaccess.host/ . I have made a section and then inserted a 3 columns one for logo on left then in the middle i put nav menu and last one i left for button. my header is no sticky in chrome browser but works fine on firefox browser on android real mobile. please help.

**Comment by shilo-ey** [comment]
Hi @wacaszafar 
Thanks for reporting,

We're having trouble reproducing your issue.
In the example you've attached the nav menu doesn't have any sticky options enabled.

If the issue persists, please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

thanks.
