### ISSUE TITLE
Custom options for column

### ISSUE THREAD

**Issue by wayheming** [elementor/elementor#7264]
Hello in this topic #6470, you really helped me by telling me how to add custom control and use it to add a class. Now I have a need to add controls that take parameters and should add a data attribute for the column. I try to use the hook `elementor/frontend/column/before_render` but the code only works on the frontend and not in the editor. Tell me how to run the code in the editor. Thanks.

```
function add_column_control( $element ) {
	$element->add_control(
		'scroll_x',
		[
			'label'       => esc_html__( 'X axis translation', 'theme' ),
			'description' => esc_html__( 'Recommended -200 to 200', 'theme' ),
			'type'        => Controls_Manager::TEXT,
			'default'     => 0,
			'render_type' => 'template',
		]
	);
}
add_action( 'elementor/element/column/layout/after_section_start', 'add_column_control' );

add_action(
	'elementor/frontend/column/before_render',
	function( $widget ) {
		$settings = $widget->get_settings_for_display();

		$widget->add_render_attribute( '_wrapper', 'data-parallax-x', $settings['scroll_x'] );
	},
	10
);
```

Frontend: http://prntscr.com/mrvjp3
Editor: http://prntscr.com/mrvkad

**Comment by bainternet** [comment]
@wayheming 

Currently, sadly, there is no way to do that other than creating a custom JS behavior to a column element. 



thanks.

**Comment by wayheming** [comment]
@bainternet thanks

**Comment by udayraj07** [comment]
https://prnt.sc/untuby

How to move with elementor/frontend/column/before_render in "elementor-column" class html inner section.
