### ISSUE TITLE
Feature request:"View More" button for the Elementor portfolio widget

### ISSUE THREAD

**Issue by lochsaty** [elementor/elementor#7265]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lochsaty** [comment]
It would be very helpful if the Elementor portfolio widget provided the option for a "view more" button, so fewer items would be displayed upon loading. The JetElements add-on contains this feature in their portfolio widget, but their styling and functionality options are rather limited. Would love it if Elementor added this simple feature...

**Comment by jvorld** [comment]
+1

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

I merged this issue with  #1284, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
