### ISSUE TITLE
Whatsapp Dynamic Link with custom field integration

### ISSUE THREAD

**Issue by soccernatic** [elementor/elementor#7266]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently the Dynamic Link feature for Whatsapp gives you the option to add the phone number, but you have to manually type it because it was designed for one number (usually the website`s contact), but for a directory or classified website where there are hundreds of contact numbers, it's impractical and should have been though of before. Also the current version does not give the option to add text (pre-written text where the receiver would get).

Therefore, my feature request would solve this manual impracticality needed in order to add a whatsapp contact for every single post that requires a different whatsapp number and it would include a pre-written text making it easy for the customer just to click send. Note: it's not a whatsapp share button, it's a message button. Here is an example, if you click on the whatsapp number, it will open whatsapp messenger in the browser or go directly to whatsapp on mobile. It has a pre-written message. https://www.destackterapias.com/ana/

**Describe the solution you'd like**
When choosing the Dynamic link and choosing Whatsapp, Elementor should give us another dynamic link option where we could choose the custom field type for the phone number and for the text.

**Describe alternatives you've considered**
I've been using Toolset for my custom fields and type, it would be nice to have an integration with such. So far I have not found an alternative yet for this problem.

**Additional context**
Images with examples attached

![whatsapp feature request_2](https://user-images.githubusercontent.com/38053201/53649337-acf70280-3c20-11e9-99b3-78640b16f3ae.jpg)
![whatsapp feature request](https://user-images.githubusercontent.com/38053201/53649338-acf70280-3c20-11e9-9231-1ad7fe7a25fd.jpg)

**Comment by bainternet** [comment]
Currently, this feature is not supported.

It's not possible to implement a dynamic value for a dynamic tag (nested dynamic)

what you can do is either create a custom dynamic tag that will return the value for the link dynamically be following the [our docs](https://developers.elementor.com/dynamic-tags/)

Or you can create a shortcode that will return the value for you after all the link to a WhatsApp is a simple link to 
`https://api.whatsapp.com/send?phone=XXXXXX`


Thanks for the feedback.

**Comment by soccernatic** [comment]
I'm not a programmer, so I would not know how to start a dynamic tag, but I took a look at maybe adding a shortcode and I'm learning how to implement it. Could you help me figure out how to create a shortcode that would include in the whatsapp the post name and pre-written text?

For example, https://api.whatsapp.com/send?phone=[post_title]&text[pre-written-text]

Do I create two shortcodes, or three? One for the post_title, one for pre-written-text, or another one for the whole whatsapp link?

I'm just not sure how to start.

Thank you for your help!
