### ISSUE TITLE
Full Width Items inside Boxed Layout

### ISSUE THREAD

**Issue by grrben** [elementor/elementor#7267]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Display images full width inside a boxed layout. Or not entirely full width but at least that e.g. a photo ignores the boxed width for text, so that it appears a little larger. Images description below photos should be boxed though. 

**Describe the solution you'd like**
Settings for content to keep it within the boxed layout or to allow it to ignore the boxed area. Not only for images but also for things like headings.

**Additional context**
Example of how such content should look after publishing: 
<img width="1081" alt="screenshot 2019-03-01 at 19 36 11" src="https://user-images.githubusercontent.com/32160769/53658586-77224000-3c59-11e9-9051-81b3f3f566ab.png">

**Comment by sf-steve** [comment]
Can you not just create 3 sections, with the middle one having a wider content width?

**Comment by shilo-ey** [comment]
Hi @grrben 

You can achieve this layout using negative margins for your images

**Comment by grrben** [comment]
Hi @shilo-ey, I'm afraid your suggestion doesn't work as it will apply to all content inside the section. I can't see a way to apply certain settings to single items within a section.
