### ISSUE TITLE
Costum taxonimies integration in site/template/product/page

### ISSUE THREAD

**Issue by Supermarky** [elementor/elementor#7268]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by Supermarky** [comment]
I have created several **Costum taxonimies** in the _functions.php_ and would like to integrate them on  **single product page** (_WooCommerce_) for the output. It does not appear in _Elementor_ to integrate this code. How do I do that ? Only with a paid plugin? Wich? 
Should I write a whole woocommerce template?
Or should I use a special plugin? 
Thanks!

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
