### ISSUE TITLE
Un-wanted bottom-padding on <div class="elementor-post__thumbnail">

### ISSUE THREAD

**Issue by mylimoproject** [elementor/elementor#7270]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description
This is the issue below (elementor adding unwanted padding to post widget and post archive):
   " **padding-bottom: calc(.45*100%)**"

https://travelsfy.com/great-barrier-reef-australia-queensland-whitsunday-islands-main-tourist-attraction/
**Note**: Issue present on every page except the HOME/INDEX page => https://travelsfy.com/

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
[system-info-travelsfy.com-02-03-2019.txt](https://github.com/elementor/elementor/files/2921833/system-info-travelsfy.com-02-03-2019.txt)</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
![unwated-elementor-padding](https://user-images.githubusercontent.com/29313121/53678552-b4ed8b80-3c8e-11e9-8550-0eda1fb8b02f.JPG)
![elementor-enabled](https://user-images.githubusercontent.com/29313121/53678561-c040b700-3c8e-11e9-96d9-8c83ad368865.JPG)

**Comment by bainternet** [comment]
@mylimoproject 

When you use Image ration in posts widget there is a JavaScript handler that runs on the frontend, Not the page you have linked has a few JS errors which could cause the handler not to run, so please try to change your WordPress theme to WordPress TwentySixteen/TwentyNinteen and see if the issue still persists it it does,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by galiainfographics** [comment]
Same bug happened on my elementor pro built site, any workaround since March 19?

**Comment by soundatech** [comment]
Same problem!
With this CSS 👍

.elementor-43520 .elementor-element.elementor-element-2b3e4d08 .elementor-posts-container .elementor-post__thumbnail {
    padding-bottom: calc( 0.48 * 100% );
}

Anyone find the solution?

**Comment by hellatan** [comment]
I found this from the following post - https://wordpress.org/support/topic/issue-with-elementor-pro-post-widget-media/:
```
For your image issue, you can copy the following CSS and paste it in
Appearance -> Customize -> Addtional CSS


.elementor-posts .elementor-post__card .elementor-post__thumbnail {
    padding-bottom: 0 !important;
}
```

**Comment by NWTrailers** [comment]
If you are experiencing this issue, it is because javascript errors are preventing a necessary script from running. Check your console and resolve the errors and then this padding issue, as well as some other layout issues, will resolve.

**Comment by Tahiticom** [comment]
Solution: Add this css 

.elementor-posts .elementor-post__card .elementor-post__thumbnail {
    padding-bottom: inherit !important;
}
.elementor-posts-container .elementor-post__thumbnail {
  padding-bottom: 0 !important;
}
