### ISSUE TITLE
HOVER Shadow effect for buttons

### ISSUE THREAD

**Issue by jasonb4u** [elementor/elementor#7275]
This is NORMAL shadow settings: https://prnt.sc/msihdm 

This is HOVER shadow settings: https://prnt.sc/msii0z 

Then when I change the HOVER shadow and then look back at NORMAL it has been overridden by the changes from HOVER settings. Low and behold I didn’t realize the NORMAL & HOVER weren’t for the SHADOW effects

Can we get this feature for HOVER please:  https://prnt.sc/msil0z

**Comment by bainternet** [comment]
@jasonb4u 	

There are only one Box Shadow control and settings for a Button widget, and it is stateless, meaning its the same for both normal and hover.

thanks.

**Comment by jasonb4u** [comment]
I believe I put that in one of my screen shots which means this was a request and wasn't meant to be cloaed down after someones first response: https://prnt.sc/mspb7v

Sooo how is Elementor going make it so there is a HOVER effect Box shadow happening without having to add the CSS every time ?

**Comment by jasonb4u** [comment]
I meant myself not having to add it each time, WOW.

The button adds it, not me physically typing it everytime, ya know ! 

Like this BOOOM we have shadow from a HOVER button: http://prntscr.com/msuzgo 
instead of having to manually put it in yeah!

**Comment by DmitriyDSWEB** [comment]
+1 often need add other shadow, normal, hover and active, when press button off shadow or change size button

**Comment by WEBLOTI** [comment]
Too bad his reaction was that way. You can tell how much they are interested in meeting customer requests! 🤨
