### ISSUE TITLE
Column Mobile view

### ISSUE THREAD

**Issue by tobias992** [elementor/elementor#7278]
Hello,

first sorry for my bad English but i hope you can understand my "problem".

All Columns in mobile view are shown vertical. First Column 1 -> under this Column 2 and so on...

Maybe you can add a option (only for mobile view) that a User can Swipe left or right to see other Column. All Columns also be shown horizontal like in Gallery Element. In Gallery Element i also can Swipe left or right to see other Pictures. And this Feature i mean with a complete Column.

**Comment by shilo-ey** [comment]
Currently, there is no way to do this without incorporating a fair amount of code.

If you, however, decide to write a patch for it, we'll gladly include it after some code review.

Thanks.

**Comment by tobias992** [comment]
Hmmm, Maybe...

If view.mobile = true then
display.column.horizontal = true
End If

 xD xD xD
