### ISSUE TITLE
BedBooking

### ISSUE THREAD

**Issue by alfonsocarmelo** [elementor/elementor#7280]
Hi, Elementor have a problem with the BedBooking script on mobile.
Is there a way to fix this problem?
In this moment i cannot see the calendar of script in a page made with Elementor
Try! and let me know if you can choose an interval dates
https://www.tenutadonpaolino.com/room/camera-1

**Comment by shilo-ey** [comment]
Hi @alfonsocarmelo 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

In addition, your website is unreachable.

**Comment by drawcard** [comment]
Why is your link redirecting to a phishing website @alfonsocarmelo ?
