### ISSUE TITLE
It is TIME FOR Globals, please upvote ~ font limiting & font switcher 

### ISSUE THREAD

**Issue by gravnetic** [elementor/elementor#7281]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Granular control of available fonts available in Text Styles set in the Elementor Tools tab.  Find and replace loaded fonts, part of the Global settings.

Problem:  If a font is selected in an Elementor Block that is outside the style guide of a site or brand it can be very difficult to find the offending font and change it to be inline.  

I would like to be able to only make specific fonts available in the Elementor settings.  While it is wonderful for many to have such a wide selection of fonts, most designs benefit more from a limited font stack. 

Alternatively, I would like to see all fonts used in Elementor with a change dropdown so that any font that is used can be switched to another and then saved which updates the site stylesheet.  This would solve quickly updating fonts that are outside the brand style guide...this could be extended to colors.

Come on guys, it is time for GLOBALS!!!

**Comment by shilo-ey** [comment]
I merged this issue with  #1324, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by gravnetic** [comment]
I understand that the issue aligns here but while the global is a universal theme here the font limiting is specific and not mentioned above, so I hope by closing my ticket it is not overlooked.  It is EXTREMELY time-consuming to track down a single use font in an Elementor element on a site!  Font limiting actually is a professional and highly appreciated item I assure you.
