### ISSUE TITLE
Elementor selectors

### ISSUE THREAD

**Issue by synt1xerr0r** [elementor/elementor#7284]
I cant figure out elementor's selectors. I'm trying to use them for a plugin for infinite scroll but it just doesnt work and tried it with different plugins.
Selectors I need are: ( Content Selector, Item Selector, Navigation Selector, Next Selector)

**Comment by shilo-ey** [comment]
Can you please elaborate on what you are trying to achieve and what you're asking for?

Thanks

**Comment by synt1xerr0r** [comment]
I am trying to activate Infinite Scroll feature on my website, but it just doesn't work. I use Elementor Pro with my OceanWP theme. 

I tried differenet plugins for doing this and they all ask for selectors. my theme selectors dont work so I thought they needed Elementor's selectors.

Anyway I just want to make my website load more posts when people scroll all the way down a post

**Comment by drawcard** [comment]
*Generally speaking* - To get infinite scroll working, generally you need to specify the class or ID's of global containers inside your theme, plus page elements like prev / next links. It depends greatly on your individual circumstances but generally speaking you can add ID / classnames to Elementor elements as you need them (in the Advanced tab):

![image](https://user-images.githubusercontent.com/1435638/53780413-493c4480-3f54-11e9-88e0-629e8f383435.png)

However this would only achieve what you need for a single given page. To do it globally you will need to examine your theme for the containers / prev & next links etc. and figure out what their classes are (or create template parts in Elementor with the prerequisite containers etc.).

If you have Pro you can also add key/value pairs to the element's tag as well (eg. data attributes) if your infinite scroll plugin supports it.
![image](https://user-images.githubusercontent.com/1435638/53780435-61ac5f00-3f54-11e9-9f8b-6bff17adbef5.png)

**Comment by shilo-ey** [comment]
Thanks.

@drawcard basically answered your question.

You can set custom attributes to the wrapper, and specify your containers by it.

Thanks.
