### ISSUE TITLE
Trigger Entrance Animation after Ajax Request

### ISSUE THREAD

**Issue by ikristher** [elementor/elementor#7289]
In my website, I am fetching elementor page using ajax request through the wp-api. Is there a way for me to trigger the animation after loading the content?

**Comment by shilo-ey** [comment]
Currently no. 

Thanks

**Comment by Ba5nanas** [comment]
elementorFrontend.init();

**Comment by Ba5nanas** [comment]
> In my website, I am fetching elementor page using ajax request through the wp-api. Is there a way for me to trigger the animation after loading the content?

try this function "window.elementorFrontend.init()"
