### ISSUE TITLE
Texturized Transparent Background Overlay

### ISSUE THREAD

**Issue by RoldanAncajas** [elementor/elementor#7291]
Hi Elementor,

How I wish if you could include in your future update the capability to put **Texturized Background Overlay** especially on Image Sliders.

Kindly check attached image for references:

![xcg5j](https://user-images.githubusercontent.com/48211630/53737757-5ca1ce00-3ec8-11e9-9853-24079a574bf8.png)

Regards,
Roldan Ancajas

**Comment by shilo-ey** [comment]
Hi @RoldanAncajas 

You can do this by adding a background image and in addition adding a background overlay image.

Thanks.
