### ISSUE TITLE
Trigger Update button in the editor ?

### ISSUE THREAD

**Issue by mattiasghodsian** [elementor/elementor#7292]
How do i trigger the UPDATE button to show up in the editor when a field changes of my widget to update the visual?

**Comment by shilo-ey** [comment]
Hi @mattiasghodsian 

Elementor uses Wordpress native autosave mechanism.

You can change the interval by setting in `wp-config.php` file the following line:
`define( 'AUTOSAVE_INTERVAL', X );`

Which X replaces the time you want to wait after a change (set it to 1 for immediate page save)

Please note that performance wise this is not recommended.

**Comment by mattiasghodsian** [comment]
That's not what i meant. I'm working on a plugin for elementor and i saw on other plugins there is a Preview Update button that pops up on the sidebar when inputs are change.

My plugin contains PHP and that cant be displayed on the live editor on changes.
