### ISSUE TITLE
`Inline (auto)` option not working in 2.5.0

### ISSUE THREAD

**Issue by kaskad88** [elementor/elementor#7293]
`Inline (auto)` option for widgets not working in 2.5.0. Widget width remain 100%. http://prntscr.com/mt29ok

**Comment by shilo-ey** [comment]
Hi @kaskad88 

Thanks for the feedback.

We are currently working on a fix for this issue and will release a patch soon.

Thanks.

**Comment by shilo-ey** [comment]
Elementor v2.5.1 has been released. 

Feel free to update!

thanks.

**Comment by ag-skyler** [comment]
This exact issue seems to have returned as of v2.5.4

**Comment by shilo-ey** [comment]
@ag-skyler
This is not an issue. Please update your page and then you will be able to use the inline features.

This behavior has been added to prevent immediate change of the display method to flexbox in pages that have been created before 2.5.0

Thanks

**Comment by ag-skyler** [comment]
> @ag-skyler
> This is not an issue. Please update your page and then you will be able to use the inline features.
> 
> This behavior has been added to prevent immediate change of the display method to flexbox in pages that have been created before 2.5.0
> 
> Thanks

Perfect. I missed that behavior being added when I reviewed the notes. Thanks!

**Comment by Pixelinity** [comment]
> 
> 
> @ag-skyler
> This is not an issue. Please update your page and then you will be able to use the inline features.
> 
> This behavior has been added to prevent immediate change of the display method to flexbox in pages that have been created before 2.5.0
> 
> Thanks

You should probably mentioned that to everyone so they are not all freaking out!

**Comment by Pixelinity** [comment]
> 
> 
> @ag-skyler
> This is not an issue. Please update your page and then you will be able to use the inline features.
> 
> This behavior has been added to prevent immediate change of the display method to flexbox in pages that have been created before 2.5.0
> 
> Thanks

that's dumb I had a panic attack for a second and I'm a web designer, what about all the stupid people out there running around like chickens with their heads cut off? Elementor couldn't have found a more automated way?

**Comment by ag-skyler** [comment]
> > @ag-skyler
> > This is not an issue. Please update your page and then you will be able to use the inline features.
> > This behavior has been added to prevent immediate change of the display method to flexbox in pages that have been created before 2.5.0
> > Thanks
> 
> that's dumb I had a panic attack for a second and I'm a web designer, what about all the stupid people out there running around like chickens with their heads cut off? Elementor couldn't have found a more automated way?

Yeah, I was sort of stumped too and I do full-stack development. I was in using Chrome dev tools trying to figure out where the issue was. I can't imagine how other folks might expect things to go. I'll let the Elementor community know as I'm sure they'll be asking.

**Comment by Pixelinity** [comment]
> 
> 
> > > @ag-skyler
> > > This is not an issue. Please update your page and then you will be able to use the inline features.
> > > This behavior has been added to prevent immediate change of the display method to flexbox in pages that have been created before 2.5.0
> > > Thanks
> > 
> > 
> > that's dumb I had a panic attack for a second and I'm a web designer, what about all the stupid people out there running around like chickens with their heads cut off? Elementor couldn't have found a more automated way?
> 
> Yeah, I was sort of stumped too and I do full-stack development. I was in using Chrome dev tools trying to figure out where the issue was. I can't imagine how other folks might expect things to go. I'll let the Elementor community know as I'm sure they'll be asking.

I'm an affiliate trying to sell the simplicity of elementor to the common person who has no clue and I can guarantee they would be freaking. least elementor could do was have a huge ass popup telling people what to do to fix this cause most people don't read changelogs.

**Comment by taropaa** [comment]
I had already updated my page prior to 2.5.4? This is ridiculous. Do I have to keep checking ALL PAGES ON ALL SITES every time you guys decide to drop an update and break all previously designed layouts?! Then spend 2 hours every time trying to figure out what the heck you guys broke again...

**Comment by ScottMadore** [comment]
I don't get it.
It's not working for me. I have saved the page. Reloaded it.
It's not working.
