### ISSUE TITLE
Elementor Interface issue

### ISSUE THREAD

**Issue by rostheboss** [elementor/elementor#7296]
= update 2.5.1 

"Style" and "Advanced" tabs' are empty. So i can't edit sections, paddings, margins, set bg color etc. 
working on kava pro theme

**Comment by shilo-ey** [comment]
Hi @rostheboss 
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Try cleaning your browser's cache.
