### ISSUE TITLE
Login Checkbox Styling

### ISSUE THREAD

**Issue by zrk4444** [elementor/elementor#7297]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem is, default checkboxes are ugly and need to be able to be styled/animated.

Like this: https://codepen.io/zFunx/pen/dWbevd

**Describe the solution you'd like**
Styling options for all checkbox elements.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

for now, you can do that via custom CSS.

Thanks for the feedback.

**Comment by zrk4444** [comment]
Apparently, I'm not that good at CSS because I couldn't figure out how to style the elementor login widget checkbox.

The label tag is outside the input tag so I can't select it with a + selector via CSS.
