### ISSUE TITLE
CSS Autoprefixing

### ISSUE THREAD

**Issue by jphilung** [elementor/elementor#7298]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The changelog for version 1.5.0 mentions this :
> Tweak: CSS autoprefixer now supports last 5 versions of browsers

Does Elementor still support CSS autoprefixing ? Does that apply to the custom CSS in each widget ?

My flexbox declarations do not seem to get prefixed after the final CSS is generated, so my guess is that autoprefixing is not supported.

**Comment by bainternet** [comment]
Elementor now has its CSS autoprefixer set to 10 last version of browsers and it has been like that for a while.

As for your question, only Elementor core CSS is prefixed. Custom CSS is not and that's up to you.

Thanks.

**Comment by jphilung** [comment]
Great thanks !
