### ISSUE TITLE
Uncaught TypeError: Cannot set property 'controls' of undefined

### ISSUE THREAD

**Issue by MohmmedAshraf** [elementor/elementor#7300]
after updating to latest version i got this error,

`Uncaught TypeError: Cannot set property 'controls' of undefined
    at Object.<anonymous> (editor.min.js?ver=2.5.1:2)`

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

we can't really help without it.

thanks.

**Comment by chiqui3d** [comment]
the same problem

**Comment by steffanhalv** [comment]
Me to

**Comment by baatten** [comment]
I had the same issue.

I disabled a transition plugin and now it works.

**Comment by PauloBoaventura** [comment]
Can someone describe a solution option for this problem?

**Comment by chiqui3d** [comment]
In my case my problem was that I had a redirect on the htaccess.

**Comment by geekysihag** [comment]
I had the same issue, turns out it was because of "WOOF - WooCommerce Products Filter" plugin, i disabled it and all worked fine, strange....and i got this issue on Elementor V2.5.16 and Elementor Pro  V2.5.9

**Comment by vuhanguyen** [comment]
It seems to conflict with Black Studio TinyMCE Widget, everything has been working fine since I disactivated that plugin

**Comment by MiguelAngelParragaC** [comment]
> I had the same issue, turns out it was because of "WOOF - WooCommerce Products Filter" plugin, i disabled it and all worked fine, strange....and i got this issue on Elementor V2.5.16 and Elementor Pro V2.5.9

We have de same issue and we find here de solution: https://products-filter.com/conflict-with-elementor-page-builder/

**Comment by chandlerbing26** [comment]
mine had conflicts with Quick Adsense

**Comment by redpik** [comment]
Same bug. Conflict with Yoast SEO.
Solution : disable Yoast SEO :/

**Comment by chandlerbing26** [comment]
Hi @redpik I checked in the elementor Facebook group and it was reported there that adsense has changed some of their codes for the responsive ads so the problem and the team of eleentor has replied that they are working on it.
