### ISSUE TITLE
would love a price query wiget that works on any page not just single product page but any page. The Elementor is up to date , yes. The problem i am having is not with single product pages, but with custom category pages for example i was able to connect each row with the quantity and add to cart that does work but for the price per box i had to add using the simple title, as i cannot find a woo tool, widget to drag over exept for the price wiget that seems to only work with a single product page. To make a very customizable category page the one thing i need is to have a price query to connect to product so that when the client updates the product price it will also update her on the custom category page.  Thanks, Cynthia

### ISSUE THREAD

**Issue by DESIGNSWIZARD** [elementor/elementor#7302]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
