### ISSUE TITLE
[BUG} Elementor Popups do not work in IE11.

### ISSUE THREAD

**Issue by DJaskerDJG** [elementor/elementor#7303]
I submitted a support request that I hope can be expedited to the development team.  Elementor Popups don't work in IE11.  Example: [ http://wordpress-166050-684371.cloudwaysapps.com/ ].  If you scroll down a short bit you will see a "blue" menu button.  When clicked on in IE11, it doesn't do anything or isn't showing as intended (like in Chrome / Firefox).

Support has seen it and has been able to replicate it (using admin access), but suggested I put a comment here as well.

Before we all say screw IE, this site is for a healthcare group so most hospitals here in the U.S don't use the latest versions of software.  Any help would be great.

**Comment by shilo-ey** [comment]
Hi @DJaskerDJG 

Elementor uses [Flexbox](https://caniuse.com/#search=flex) for the popups location and display.
Unfortunately, Flexbox isn't fully supported on IE11.

We will take a look if there's something we can do.

As for now, you can add this [Polyfill script](https://github.com/jonathantneal/flexibility) to support flexbox in IE11.

Thanks

**Comment by DJaskerDJG** [comment]
Do I need to do anything other than simply attach this script into my site?  Do I need to target the popup or button in any way?

Thank you for the response.

**Comment by RobertShippey** [comment]
I added the pollyfill script to our site doing that alone doesn't appear to work. As per @DJaskerDJG's comment, could you advise what steps we would need to take to target the popup and/or button please?

**Comment by RobertShippey** [comment]
@shilo-ey Any advances on our queries here?

**Comment by maitNoserYoung** [comment]
This really isn't an option. Could you at least create a fallback using aboslute positioning relative to the body? Or how about you include a polyfill in Elementor if needed?

**Comment by Netzlichter** [comment]
Is there a solution for opening popups via IE11? There is nothing happening if I click on a button which points to a Elemenotr PopUp...

**Comment by Jamie4** [comment]
Hi. Was wondering if you found a solution found to this issue of Elementor pop-ups not working correctly in IE? @DJaskerDJG

**Comment by connorwebdev** [comment]
I used the following in my child themes CSS file which seems to be working so far. It detects IE and positions the popups absolutely if it is IE.

@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
   /* IE10+ CSS */
	.dialog-widget-content{
		position:absolute;
		left:50%;
		top:50%;
		transform:translate(-50%, -50%);
	}
}
