### ISSUE TITLE
Remove Notification Views Elementor

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7304]
Hello guys,

At levels other than Administrator levels, Elementor is not accessible. However, I am testing author-level access and see that an Elementor notification message appears on the admin home page:

https://screenshot.net/pt/7oke7cv?

How do I remove the display of any Notification from Elementor to levels other than Administrator?

If this is not possible, I leave here as a suggestion for an upcoming update, because although Administrator levels may not have access to Elementor, it is still unnecessary to show these notifications to Authors, Contributors, ... This breaks the privacy of the site.

Thank you,
Rodrigo Carlos

**Comment by black-eye** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @proddigital 

Thanks for your suggestion.
We will look into it and update this thread.

Thanks.

**Comment by black-eye** [comment]
The problem of this notification is even more significant, when used for renewal appeal, which:
a. cannot be closed,
b. has nothing to do with non admins, who have no rights to upgrade.

Clients kept calling me, what's going on and if their site would stop working. Didn't look very proffessional.

**Comment by proddigital** [comment]
Yes @black-eye  this is a bit annoying.
A few months ago I already sent Wordpress support this idea of terms (us admins) an option to hide for the non administrator level, any notification of the plugin. This would be great to be offered by WP, as I always request a plugin for them to hide these notifications from them, they do this, but then there appear notifications from other plugins, and this never ends.

So it would be great for WP to offer this as a central resource.

If more people offer this idea to Wordpress, the greater the chances they take that into account.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!
