### ISSUE TITLE
Please add compatibility for wordpress post formats in the posts widget.

### ISSUE THREAD

**Issue by webdesigner29** [elementor/elementor#7307]
My biggest issue with Elementor Pro is that the posts widget does not have post format compatibility. For example, I would like to be able to have posts with the “link” format to simply be able to go to the first link in the post when clicked, or posts with the “video” format to be able to play the video inline on the posts page without having to click on the post, or posts with the “image” format to simply open the image in a lightbox when clicked. Other page builders like [Divi](https://www.elegantthemes.com/documentation/divi/post-formats-divi/) have this functionality and so do some wordpress themes like [Gazette](https://wordpress.com/theme/gazette). This is a built in feature on wordpress and I would like to see this added to Elementor Pro.

**Comment by shilo-ey** [comment]
Hi @webdesigner29 

Thanks for your feedback. we are currently working on a solution that suits your requirements. 

Please follow this thread.

Thanks.
