### ISSUE TITLE
Slow loading widget panel since v2.5 upgrade

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#7308]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Since upgrading E + E Pro to 2.5 I have noticed a bit of slowness with the widget panel, it takes about 25-30 seconds for the panel to activate. Elementor itself loads faster though (presumably because some of the loading has been offloaded to this stage). It's more of a nuisance when creating a brand new page, while waiting to drag a new element onto the page.

## Steps to reproduce

1. New page & fire up elementor
2. Wait for elementor to load
3. Wait for sidebar widget panel to load

![image](https://user-images.githubusercontent.com/1435638/53780700-6f161900-3f55-11e9-8e02-81015a1af6ed.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29
	MySQL version: (Ubuntu) v5.7.25
	PHP Version: 7.2.11-2+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-AU
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.6
		Author: Elementor.com

	Health Check & Troubleshooting
		Version: 1.2.5
		Author: The WordPress.org community

	WP Cerber Security, Antispam & Malware Scan
		Version: 8.0
		Author: Gregory

	WP Migrate DB Pro
		Version: 1.9.4
		Author: Delicious Brains

	WP Migrate DB Pro CLI
		Version: 1.3.5
		Author: Delicious Brains

	WP Migrate DB Pro Media Files
		Version: 1.4.13
		Author: Delicious Brains

	WP Migrate DB Pro Multisite Tools
		Version: 1.2.5
		Author: Delicious Brains

	WP Migrate DB Pro Theme & Plugin Files
		Version: 1.0.5
		Author: Delicious Brains


== Log ==
	: 
JS: showing 1 of 1JS: 2019-01-31 06:45:14 [error X 1][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:6883] Cannot read property \'select2\' of undefined 

Log: showing 2 of 22019-03-05 01:20:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.5.1',
)]
2019-03-05 01:20:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.6',
)]


				
```
</details>

**Comment by reardestani** [comment]
We had same issue in our GoDaddy and SiteGround servers. We enabled the Gzip via `.htaccess` (https://monosnap.com/file/9umgCNEWfjJQhfIZih3EWGavRmkza6). It may help you.

Consider that Gzip module was active but it wasn't doing anything by default. After the following codes it loads faster.

```
<IfModule mod_deflate.c>
AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css
AddOutputFilterByType DEFLATE text/json
AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript
AddOutputFilterByType DEFLATE application/json
</IfModule>
```

**Comment by adrianabelei** [comment]
I was having problems with low loading speed widget on Elementor and now the website is working perfectly. Thanks for this!
