### ISSUE TITLE
Elementor v2.5 breaks front end on WP 5.0 and Breaks whole site on WP 5.1 running PHP5

### ISSUE THREAD

**Issue by RealBenihime** [elementor/elementor#7310]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
Updating to latest version, at the time 2.5 or Installing and Activating version 2.5

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Unable to get System Info, site is completely broken, including Dashboard after updating to WP 5.1

<h2>NB: The test site server is not accessible outside organization network</h2>

<strong>The below is copied from a different site running on the same server as broken site</strong>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.7 (Ubuntu)
	MySQL version: (Ubuntu) v5.5.62
	PHP Version: 5.5.9-1ubuntu4.26
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://wptest113.ukzn.ac.za
	Home URL: https://wptest113.ukzn.ac.za
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Active

== Theme ==
	Name: UKZN SubSite Child
	Version: 2.0
	Author: Sibongiseni Msomi
	Child Theme: Yes
	Parent Theme Name: UKZN SubSite
	Parent Theme Version: 1.0
	Parent Theme Author: Media Platform

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	All-in-One Event Calendar by Time.ly
		Version: 2.5.36
		Author: Time.ly Network Inc.

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

	Essential Addons for Elementor - Pro
		Version: 2.14.1
		Author: WPDeveloper

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Max Mega Menu
		Version: 2.5.3.2
		Author: megamenu.com

	Memphis Documents Library
		Version: 3.9.17
		Author: Ian Howatson

	Premium Addons for Elementor
		Version: 3.1.1
		Author: Leap13

	Premium Addons PRO
		Version: 1.4.0
		Author: Leap13

	Smart Slider 3
		Version: 3.3.15
		Author: Nextend

	UKZN SiteFininty Content Import
		Version: 1.1
		Author: Daniel Holland

	Wordfence Security
		Version: 7.2.2
		Author: Wordfence

	WP Fastest Cache
		Version: 0.8.9.1
		Author: Emre Vona

	WP File Manager
		Version: 4.1
		Author: mndpsingh287


== Log ==
	: 
Log: showing 4 of 42019-01-22 10:46:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-30 10:09:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-02-21 11:55:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.7',
)]
2019-02-21 11:55:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.5',
)]

JS: showing 1 of 1JS: 2019-01-23 08:05:15 [error X 3][https://wptest113.ukzn.ac.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.3:2:6883] Cannot read property \'select2\' of undefined 
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by RealBenihime** [comment]
![error](https://user-images.githubusercontent.com/19819312/53787979-1892e580-3f29-11e9-948a-9369fbda198a.png)

**Comment by bainternet** [comment]
@RealBenihime 

PHP's [ucwords](http://php.net/manual/en/function.ucwords.php) `delimiters` parameter (2nd parameter) was added in PHP 5.4.32, 5.5.16 and 7.x

looking at your system info, it seems like your PHP version is outdated the cause of the warning you are seeing.

so try upgrading your PHP version.

Thanks.

**Comment by hmosselaer** [comment]
Outdates, you telling you support PHP 5.4? do not call that outdated, it is in your compatibiltiy version.

Fix this issue, or stop supporing PHP 5.4, and tell your suppoer people you NOT supporting this.

By the way, if you fix this issue, it works, but so far yoru compatiblity starts from PHP 5.4.32 due to this change which can be easy fixed, by a php programmer, thast why i am confused you guys not allowing to fix it and just act weird telling 5.4 is supported.

Install it, and see yourself, will give you the same error.

**Comment by hmosselaer** [comment]
Do not expect this to be closed, until you really fix your issue? why, wordpress should not even be allowed to install if you got your PHP Version check integrated correctly, which is not the case either.

User for ages, even paying, but thats over, if this is not be taken care off, elementor works, so its not a issue about php 5.4.32+

Issue is here, 5.4.32 is supplied on ubuntu, not on a ton of another servers, so you making a huge closing this task, even latest centos runs 5.4.16, NOT .32, reason i informed you.

**Comment by hmosselaer** [comment]
Prooff
http://prntscr.com/mtyi1s

5.4.16 is latest on all centos installations, so you suggest to upgrade a entire server farm, because a coder using a later function which is not covered in 5.4, very unproressional.

**Comment by hmosselaer** [comment]
PS: After this issue, entire elementor works aswell, however cant auto upgrade, its just plain stupid you closing this, get a centos box, even latest ppp is 5.4.16

**Comment by RealBenihime** [comment]
@hmosselaer Thanks for this... I got so busy yesterday I couldn't even analyze the reasoning behind the closure of this issue... I agree that Elementor should either clearly state which PHP versions it supports OR Fix this issue. At the moment I'm unable to convince the organization to upgrade to PHP 7+ and they have close to 500 websites running on their PHP web servers. Unfortunately this error clearly says to me "THIS IS IT, YOU'RE STUCK WITH VERSION 2.4.6"... I truly love Elementor but this is disappointing

**Comment by bainternet** [comment]
[**@RealBenihime**](https://github.com/RealBenihime) commented on [Mar 6, 2019, 11:31 AM GMT+2](https://github.com/elementor/elementor/issues/7310#issuecomment-470035361 "2019-03-06T09:31:09Z - Replied by Github Reply Comments"):
> @hmosselaer Thanks for this... I got so busy yesterday I couldn't even analyze the reasoning behind the closure of this issue... I agree that Elementor should either clearly state which PHP versions it supports OR Fix this issue. At the moment I'm unable to convince the organization to upgrade to PHP 7+ and they have close to 500 websites running on their PHP web servers. Unfortunately this error clearly says to me "THIS IS IT, YOU'RE STUCK WITH VERSION 2.4.6"... I truly love Elementor but this is disappointing


[**@hmosselaer**](https://github.com/hmosselaer) commented on [Mar 6, 2019, 11:17 AM GMT+2](https://github.com/elementor/elementor/issues/7310#issuecomment-470030399 "2019-03-06T09:17:08Z - Replied by Github Reply Comments"):
> If you close this ticket, please inform your people you NOT supporting PHP 5.4.0 like you posting.
> 
> You supporting PHP 5.4.32+
> 
> Let one thing be clear, thats a HUGE differnce.
> 
> Programmer myself for 30 years and seriously impressed about your ignorance, this is a very small bug and can make it work for tons of people.
> 
> Even paying for elementor, if i can not get this support, i am gone, very unprofessional, you asking for money and cant even fix the smallest bug.
> 
> PS: If you know how to be a programmer? then please upgrade the 5.4 php check to 5.4.32 and dont tell people you support 5.4, know things change something, but if you not willing to fix that function, you gotta change your requirments, let that be clear, things are not for free in my case.

You have both replied after a [workaround PR was submitted](https://github.com/elementor/elementor/pull/7333)!! should be released soon.

**Comment by hmosselaer** [comment]
Thanks guys, you all amazing.
