### ISSUE TITLE
`Inline (auto)` option not working in 2.5.0 - After update 2.5.1 > Broken inline block or float left

### ISSUE THREAD

**Issue by AlainMelsens** [elementor/elementor#7314]
Hello,
After I did the new update from Elementor 2.5.0 to 2.5.1 I have a section with 2 widgets in it that has broken. I tried to put some CSS to fix it as before but now with version 2.5.1 it's not working anymore.
I have tried it with display: inlineblock or with float: left but nothing changed now.
See my first situation in version 2.5.0 where the phone number is good followed by a email address:
![image](https://user-images.githubusercontent.com/25772012/53794111-94902c00-3f2f-11e9-9348-2d68a2342a01.png)
And now with the broken situation in version 2.5.1., the email address is now not inline but on a line below it:
![image](https://user-images.githubusercontent.com/25772012/53794222-d4efaa00-3f2f-11e9-8ea7-1b370d690503.png)
How can I fix this now? 
Thanks in advance.

**Comment by shilo-ey** [comment]
Thanks for reporting,

Try to remove all of your Custom CSS and create the inline effect using native Elementor controls.

If the issue still persists please reopen a new issue with proper steps to reproduce and explanation of the issue.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by AlainMelsens** [comment]
Hello,
Thanks for your fast answer. I have fix it myself by made a combination of the 2 widgets to 1 single widget. 
Now the line is not broken, so problem is resolved. Sorry to interrupted you.
Ticket is already closed.
