### ISSUE TITLE
Missing common controls

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#7317]
@joshmarom @arielk 

The widgets have inconsistent controls. We can improve the UX by standardizing controls.

Here is an example for the four most common "**Basic**" widgets:

----

**Image**: nothing is missing here

![image](https://user-images.githubusercontent.com/576623/53800784-2c007980-3f46-11e9-942d-b4ec7377ac18.png)

----

**Heading**: missing bg color

![heading](https://user-images.githubusercontent.com/576623/53800790-302c9700-3f46-11e9-9edd-a1c922a186b3.png)

----

**Text Editor**: missing bg color and text shadow

![text-editor](https://user-images.githubusercontent.com/576623/53800796-328ef100-3f46-11e9-9909-f89b1369a322.png)

----

**Button**: missing text shadow

![button](https://user-images.githubusercontent.com/576623/53800798-33c01e00-3f46-11e9-99ee-a4c6d8c4d809.png)

**Comment by moogoor** [comment]
The "Section" also has the missing controls on the Style tab. Please check the screenshot 
(Elementor Pro 2.4.6 and Elementor 2.5.2)

<img width="301" alt="screen shot 2019-03-05 at 18 05 09" src="https://user-images.githubusercontent.com/25787050/53818815-5d426f00-3f71-11e9-85fd-db89ff2c0d73.png">

**Comment by AndyLQ** [comment]
Theres bg and border / border shadow options in the advanced tab

**Comment by shilo-ey** [comment]
Hi @ramiy 

Thanks for your PR, we will review it and consider adding it to the next major version.
As for background color - as @AndyLQ mentioned you can use the background in the advanced tab.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!
