### ISSUE TITLE
does not align the image in Post Content

### ISSUE THREAD

**Issue by konservat0r** [elementor/elementor#7320]
Good day! Faced such a problem in Elementor, on the pages where (Post Content) images are shifted to the left (although they are centered in the editor) and there is no text wrap, they just stand right next to it. I tried different templates, nothing changes. Plugins disconnected. Without Elementor, everything falls into place. 

![screenshot-28feb2019-10 53 34](https://user-images.githubusercontent.com/25728333/53807131-d8028e80-3f5f-11e9-8471-638f80fe342e.png)
![screenshot-28feb2019-10 30 08](https://user-images.githubusercontent.com/25728333/53807132-d89b2500-3f5f-11e9-8695-2984f2e6f276.png)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
