### ISSUE TITLE
The "mobile-phone" List Icon is comparatively really little

### ISSUE THREAD

**Issue by badcat** [elementor/elementor#7322]
Any chance of Elementor team adjusting specific List Icons like the "mobile-phone" one?  Here it appears really small as compared to the others.

![mobile-phone](https://user-images.githubusercontent.com/26096/53820592-138a6200-3f3a-11e9-9c4f-ea97c4925ee7.png)

**Comment by shilo-ey** [comment]
Hi @badcat 

Thanks for your feedback,

The icons font library origin is FontAwesome. we do not control the sizes of the icons, we only specify the `font-size` attribute and display it accordingly.

You can either change the icon or use inline positioning options.

Thanks.
