### ISSUE TITLE
Get shortcode after saving as a new template

### ISSUE THREAD

**Issue by amircoh28** [elementor/elementor#7324]
Get shortcode after saving as a new template.

Hi Elementor sharks. 

I'd like to have a new feature in Elementor.

So now, when saving a section or any other template besides Global, I need to go back to my templates and pull out the shortcode.

It would be great if you could implement the shortcode code immediately when saving a new template, it'll save us a lot of time.

Thanks.

**Comment by shilo-ey** [comment]
Hi @amircoh28 

Thanks for your feedback!

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now you can use the finder (cmd/ctrl + E) to open the templates page in a new tab.

Thanks
