### ISSUE TITLE
Shape options without movement

### ISSUE THREAD

**Issue by proddigital** [elementor/elementor#7329]
Hello guys,

To place a strikethrough in a text, I needed to insert a horizontal line over the text and use the absolute position to organize it correctly, on the desktop, tablet, and mobile.

https://screenshot.net/pt/lj5kdtj?

But, a simpler way would be to use the "Shape" feature in the "Strikethrough" option, but without movement.
Incidentally, you could give the possibility of choosing "no movement" for any of these Shape options.

Thank you,
Rodrigo

**Comment by shilo-ey** [comment]
Hi @proddigital 

Using Typography control you can add a strikethrough to your texts. no need for dividers & margins.

![image](https://user-images.githubusercontent.com/45009641/53864021-2bbeb780-3ff4-11e9-8f21-096439775472.png)

Thanks

**Comment by proddigital** [comment]
Yes, but this strikethrough in the typography is in the same color as the text. However, I'd like it to stay in another color, as in the screenshot of the above link.
