### ISSUE TITLE
Elementor Single Template Condition Page, Add Non Elementor Page/Posts

### ISSUE THREAD

**Issue by dudaster** [elementor/elementor#7332]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm using clear no css blank templates to save unnecessary space and because of that I need to make for every post type a default single template. 

**Describe the solution you'd like**
It would be nice to have a condition like: "Include All Pages" -> "Non Elementor"

**Comment by bainternet** [comment]
@dudaster 

Currently, this feature is not supported.

The main reason it's not implemented yet is that the  "Include All Pages" or "Any Post Type" conditions are too greedy and cause issues with 404-page templates or endpoint pages like WooCommerce checkout or my account pages.

So you can either manually add each type to the condition or create a custom condition but there are no API docs for that yet.

Thanks for the feedback.

**Comment by dudaster** [comment]
It's funny that you can select in conditions Pages > All 
but you say it is to greedy Pages > Non elementor
