### ISSUE TITLE
Elementor can't load widgets when editing post

### ISSUE THREAD

**Issue by psycho-coder** [elementor/elementor#7336]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Frontend doesn’t font the `wp-widget-jnews_social` widget and some others. Frontend calls the `requestWidgetsConfig` function with a backend request. Backend forms and sends to frontend JSON with a list of widgets. By the way, JSON is correct — I’ve saved it before sending and checked. And inside the `.each` loop the `wp-widget-jnews_social` widget doesn’t exist (and some others as well) in the `this.config.widgets` dictionary and the page loading stops.

## Steps to reproduce

1) Open post to edit with Elementor;
2) The web-console has an error: `TypeError: i is undefined` (logs have record about it).

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
	
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.7
	MySQL version: Percona Server (GPL), Release 83.1, Revision da5a1c2923f v5.6.39-83.1
	PHP Version: 7.1.26
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://thedesignest.net
	Home URL: https://thedesignest.net
	WP Multisite: No
	Max Upload Size: 1,000 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: JNews - Child Theme
	Version: 1.0.0
	Author: Jegtheme
	Child Theme: Yes
	Parent Theme Name: JNews
	Parent Theme Version: 4.0.1
	Parent Theme Author: Jegtheme

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.7.12
		Author: Elliot Condon

	Akismet Anti-Spam
		Version: 4.1.1
		Author: Automattic

	Contact Form 7
		Version: 5.1.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.5.2
		Author: Elementor.com

	Jetpack by WordPress.com
		Version: 7.1
		Author: Automattic

	JNews - Breadcrumb
		Version: 4.0.0
		Author: Jegtheme

	JNews - Essential
		Version: 4.0.0
		Author: Jegtheme

	JNews - Gallery
		Version: 4.0.0
		Author: Jegtheme

	JNews - JSON-LD
		Version: 4.0.0
		Author: Jegtheme

	JNews - Meta Header
		Version: 4.0.0
		Author: Jegtheme

	JNews - Social Share
		Version: 4.0.0
		Author: Jegtheme

	JNews - Split
		Version: 4.0.0
		Author: Jegtheme

	JNews - View Counter
		Version: 4.0.0
		Author: Jegtheme

	Mailchimp Digest
		Version: 2.5
		Author: 

	OneSignal Push Notifications
		Version: 1.16.13
		Author: OneSignal

	Publish to Apple News
		Version: 1.4.3
		Author: Alley Interactive

	Slider Revolution
		Version: 5.4.8.3
		Author: ThemePunch

	Slider Revolution Before/After Add-On
		Version: 1.0.3
		Author: ThemePunch

	Vafpress Post Formats UI
		Version: 1.5
		Author: vafpress

	VaultPress
		Version: 1.9.8
		Author: Automattic

	WPBakery Page Builder
		Version: 5.7
		Author: Michael M - WPBakery.com

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms

	Yoast SEO Premium
		Version: 9.7
		Author: Team Yoast


== Log ==
	: 
Log: showing 8 of 82019-01-21 10:30:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
2019-01-22 11:30:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-01-24 17:05:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-31 11:37:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-02-12 10:34:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-19 11:46:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-03-05 09:34:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.1',
)]
2019-03-06 08:46:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.1',
  'to' => '2.5.2',
)]

JS: showing 3 of 3JS: 2019-02-06 11:45:24 [error X 1][https://thedesignest.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:194865] Cannot read property \'css\' of undefined 
JS: 2019-03-05 06:34:52 [error X 11][https://thedesignest.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.1:2:82676] Cannot set property \'controls\' of undefined 
JS: 2019-03-05 11:03:16 [error X 47][https://thedesignest.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.1:2:82666] i is undefined 
```
</details>

**Comment by bainternet** [comment]
@psycho-coder 

We can't replicate, please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

**Comment by psycho-coder** [comment]
The disabling of plugins, which are delivered with the system, solve the problem.

I've double checked once again and found out that the data, transferred through JSON is full, but they're not present in `ElementorConfig` inside the page's code. Due to this reason, the widget can't be found by its name from the received JSON in `ElementorConfig`. So there appears a discrepancy of a local version and the one generated on the backend.

**Comment by psycho-coder** [comment]
@shilo-ey 

Why the issue was closed without resolution?

**Comment by shilo-ey** [comment]
[**@psycho-coder**](https://github.com/psycho-coder) commented on [Mar 7, 2019, 9:37 AM GMT+2](https://github.com/elementor/elementor/issues/7336#issuecomment-470418795 "2019-03-07T07:37:40Z - Replied by Github Reply Comments"):
> The disabling of plugins, which are delivered with the system, **solve the problem.**

**Comment by psycho-coder** [comment]
@shilo-ey 

Unfortunately, we can’t turn off other plugins we use. That would make our blog difunctional, so this resolution is not acceptable for us.

**Comment by shilo-ey** [comment]
Create a development clone site and contact our support with credentials for us to take a look and try to isolate the problem.

Thanks
