### ISSUE TITLE
Sticky section does not work

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#7339]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Sticky section does not work. See video here: https://www.useloom.com/share/bf81a9b77df848989f4e529570b266ec

Using WP 5.1, Astra theme.  
Versions for Elementor: 2.5.2 and 2.4.6.

**Comment by drawcard** [comment]
A couple of things spring to mind - is there any CSS overriding the position: sticky; delcaration on the header element? And are there any JS conflicts or errors showing in the browser dev console?

**Comment by elasticeye** [comment]
Hi there.
Thanks for responding.

I created a new section, and then it suddenly worked. Thanks.

cheers,
Vegard Bell

ᐧ

Den tor. 7. mar. 2019 kl. 06:03 skrev Drawcard <notifications@github.com>:

**Comment by shilo-ey** [comment]
Hope you managed to resolve your issue.

Thanks.
