### ISSUE TITLE
Block Reveal Animations

### ISSUE THREAD

**Issue by loosedogs** [elementor/elementor#7341]
It would be great, in addition to the already available entry animations, to add these:

[https://tympanus.net/codrops/2016/12/21/block-reveal-effects/](url)

**Comment by shilo-ey** [comment]
Hi @loosedogs 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by debihazelden** [comment]
+1 for this feature!
