### ISSUE TITLE
Google Analytics event triggering after form submission success

### ISSUE THREAD

**Issue by asagala** [elementor/elementor#7343]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It is very complicated to add Google Analytics event triggering on successful form submission. Triggering anything after form success is complicated.

**Describe the solution you'd like**
Would be nice to have an option either in the After Action Submit to insert custom javascript or the ability to hook into the form success javascript like you can do in Instapage. Something like this
window.instapageFormSubmitSuccess = function( form ){
  // trigger GA event here 
}

**Describe alternatives you've considered**
Tried google tag manager element visibility feature. Works but it is very complicated to trigger different events on different forms since everything has to be based on visibility of success message in DOM.

**Additional context**
Nothing more to say.

**Comment by shilo-ey** [comment]
Hi @asagala 

A quick search in the repo would have given you the answer you needed, please [read here](https://github.com/elementor/elementor/issues/5305).

Thanks

**Comment by asagala** [comment]
Was more looking for actual integration in the UI of Elementor.
