### ISSUE TITLE
Post Module Customization

### ISSUE THREAD

**Issue by tickyboom** [elementor/elementor#7344]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am a Beaver Builder user and have come to Elementor. One thing that BB had was on their post module, you could create a custom design. So, when selecting 'Custom' you would be taken to the markup, and you could rearrange, add tags etc. This would be a massive improvement to the Elementor module.

**Describe the solution you'd like**
Have a 'Custom' option, that then opens a tab with the markup and the ability to add meta tags anywhere you like - example: [wpbb site:title]

**Describe alternatives you've considered**
I can reflex or restyle with CSS - but that can be cumbersome.

**Additional context**
This a KB article on how BB does this: https://kb.wpbeaverbuilder.com/article/572-beaver-themer-shortcode-index

**Comment by shilo-ey** [comment]
Hi @tickyboom 

Thanks for your feedback.

Welcome to Elementor, we hope you'll enjoy using it.

As for your request - it's already can be done using Dynamic Tags and/or Theme Builder.

Read more about it [here](https://docs.elementor.com/article/310-dynamic-content), and [here](https://elementor.com/blog/customize-your-theme/)

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by tickyboom** [comment]
Hi @shilo-ey! Thanks for the response! 

While your information was wonderful, it actually does not answer the question. To better clarify here is a video walkthrough: https://www.useloom.com/share/e6713f014d054e5c8d7afc31802fd818

I think if you could re-open this and give it more weight you would benefit a lot of users!

Thanks again

**Comment by shilo-ey** [comment]
If you meant to customize the posts module for example, we currently do not support this option, but this is something we are considering.

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
