### ISSUE TITLE
The advanced panel is completely blank. 

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#7345]
The advanced panel is completely blank. This occurs with elementor's built in widgets, as well as multiple different element addon packs elements.

![blank advanced](https://user-images.githubusercontent.com/31750063/53841300-4ee45b00-3f51-11e9-9067-df1692a62f59.PNG)

Steps to reproduce: I placed any element on the page, doesn't matter if it's stock elementor widgets or any add-on pack. No modifications or changes to the element whatsoever, just placed it on the page. Admin panel looks as it does in the picture, blank.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Like you were told before, we simply can't help without these.

thanks.

**Comment by farah4** [comment]
Hi, What was the fix to this?
