### ISSUE TITLE
Connect style of copy paste objects - different content same style

### ISSUE THREAD

**Issue by Lorenzoup** [elementor/elementor#7346]
**What problem is your feature request going to solve? Please describe.**

In creating a site with so many sections that have the same layout, by doing copy paste they are independent of each other. 

**Describe the solution you'd like**

A function to connect the style of all the copied sections even in different pages.
It would be a fundamental function! 
It allows to drastically reduce the generated css since with only one section styled it is possible to connect more sections and for example: if I change the background of one the change is applied to all the connected ones.

**Here is a easy Mockup of the new Right click Copy/paste:**

![image_rightclick](https://user-images.githubusercontent.com/48300157/53947107-66445500-40c5-11e9-830b-bf9129997c18.jpg)
`

**Comment by black-eye** [comment]
+1 Oh yes!

**Comment by Lorenzoup** [comment]
[https://www.useloom.com/share/abc665b4aa4049e38f62804c538c2937](url)

Here is a video of how it could change the speed of customization using linked objects without copying to paste every single element.

**Comment by bainternet** [comment]
I merged this issue with  #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
