### ISSUE TITLE
Sticky search widget box in editor

### ISSUE THREAD

**Issue by reardestani** [elementor/elementor#7348]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Ad the moment, if we scroll a bit down in list of elements, we can't see the **search box** (http://take.ms/XLFs4). We need to scroll top again to see search.

**Describe the solution you'd like**
Make the search box sticky so it appears after scrolling. http://take.ms/gB9qJ

It improves UX and helps to find elements faster without being forced to scroll to top to search again.

**Comment by shilo-ey** [comment]
Hi @reardestani 

Thanks for your suggestion.
Currently, we do not see the need for such behavior.
If it will be needed in the future we will consider your option.

Thanks!
