### ISSUE TITLE
Unable to track form submissions with Google Analytics

### ISSUE THREAD

**Issue by GiladWereach** [elementor/elementor#7352]
Hi,

I researched here and went through the same solved issue - [Here](https://github.com/elementor/elementor/issues/5305)
 
BUT, when I added the JS snippet to my website, it hasn't fired any event after submitting a form.

This is the snippet in my website - 

```JS	
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		 ga('send', 'event', 'Contact Form', 'Submit');
	});
});
```

The UA  and gtag tags are placed correctly and working perfect.
Is there something else that can prevent the tag from firing?

Thanks in advance

**Comment by shilo-ey** [comment]
Hi @GiladWereach .
This code should work:
```JS
jQuery( document ).ready(function( $ ){
    $( document ).on(`submit_success`, function(){
        console.log(`Form Submitted`); // Replace this line with the action line.
    });
});
``` 

Try looking in your JS Console for errors and search a solution for them.

Thanks

**Comment by GiladWereach** [comment]
Hi, Thanks for the quick response.

I looked at the console and it says the jQuery is not defined. 
Any suggestions? :) 

Thanks !

**Comment by shilo-ey** [comment]
add `$ = jQuery;` before your function.
