### ISSUE TITLE
Input fields not displaying properly in Popups, on Safari Browsers

### ISSUE THREAD

**Issue by IvanIntern** [elementor/elementor#7353]
Popup Input fields view and responsiveness doesn't work properly both on mobile and on desktop
Input fields from Contact Form 7

![20190307_111225](https://user-images.githubusercontent.com/48215661/53945576-96dabd80-40ca-11e9-9611-5e789c75c6a9.png)

Mac OS Version: 12.0.3
iPhone XS Max: 12.1.4

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
