### ISSUE TITLE
Fancy Elementor Flipbox plugin not displaying properly 

### ISSUE THREAD

**Issue by Falkus57** [elementor/elementor#7354]
Hi there, 

Fancy Elementor Flipbox plugin not displaying properly. I have four small images in a row that are supposed to flip and reveal content. However in the editor, the images seem great, but when I publish the page the images all bunch up together and distort. 

![image](https://user-images.githubusercontent.com/48315344/53946988-c5519c00-40bc-11e9-9900-a7c9ab195266.png)

**Comment by shilo-ey** [comment]
Hi @Falkus57 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by strve4excellence** [comment]
Hi there, I also have the same problem 
![Screenshot_5](https://user-images.githubusercontent.com/84643781/119240245-b006a200-bb4e-11eb-9e0d-bcd8a35cf35b.jpg)
