### ISSUE TITLE
"data-elementor-device-mode" issue in IE

### ISSUE THREAD

**Issue by kaskad88** [elementor/elementor#7356]
## Description
Hello.

I am using an `elementorFrontend.getCurrentDeviceMode()` function to get the current device mode. It's working properly on all the browsers except IE. http://prntscr.com/muip5u, https://prnt.sc/muiq4l - empty or  `normal` value. Tested in IE Edge and IE 11.

Can you please check this issue?

**Comment by shilo-ey** [comment]
Thanks for reporting, we will look into it.

**Comment by bainternet** [comment]
Fixed in 2.5.4

thanks.
