### ISSUE TITLE
Post Content Widget Issues With Gutenberg

### ISSUE THREAD

**Issue by CODYatLC** [elementor/elementor#7357]
There appears to be issues with the Gutenberg blocks and using the post content widget inside of a custom single page template. I have added the post content widget to the page without any custom settings and I'm seeing the following issues below:

1. Center aligned images inside the Wordpress post editor are showing left justified when using the custom single page template. 
2. Spacing between the images and between image/headers is non existent when using the custom single page template, but show normal spacing within a standard post page.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by hzv4424** [comment]
i have same issue:
wp 5.2.2
astra theme
elementor pro 2.6.1

**Comment by hzv4424** [comment]
> Thanks for reporting,
> Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
> This report is missing key information:
> 
> * Prerequisites.
> * Steps to replicate.
> * Isolating the problem.
> * System info.

same issue:
all plugins disabled and just elementor  & elementor pro 2.6.1 active
theme: elementor hello
wp 5.2.2
