### ISSUE TITLE
Just a little help with html, and elementor forms

### ISSUE THREAD

**Issue by mortendahl2010** [elementor/elementor#7360]
Hello , when elementor send a  email to me with a lead, i have made this HTML from the page https://polermestrene.dk/omraader/haslev/ 

But in some webmail programs, the line with links, and email does not show as link, just as a text. Outlook sees it with no problem. Elementor says it´s not a bug, and the host company says the webmail program i fine. So any one can solve this:

Regards

Code is in this message

<table>
<table width="400">
<table border="3">
<tr>
<td>Navn</td>
<td>[field id="navn"]</td>
</tr>
<tr>
<td>Adresse</td>
<td>[field id="adresse"]</td>
</tr>
<tr>
<td>Postnummer</td>
<td>[field id="postnummer"]</td>
</tr>
<tr>
<td>By</td>
<td>[field id="by"]</td>
</tr>
<tr>
<td>Telefon</td>
<td>[field id="telefon"]</td>
</tr>
<tr>
<td>Email</td>
<td>[field id="email"]</td>
</tr>
<tr>
<td>Besked</td>
<td>[field id="besked"]</td>
</tr>
<tr>
<td>Alm. ruder</td>
<td>[field id="alm_ruder"]</td>
</tr>
<tr>
<td>Store Ruder</td>
<td>[field id="store_ruder"]</td>
</tr>
<tr>
<td>Palæ Ruder</td>
<td>[field id="palae_ruder"]</td>
</tr>
<tr>
<td>Bondehus Ruder</td>
<td>[field id="bondehus_ruder"]</td>
</tr>
<tr>
<td>Ovenlys Ruder</td>
<td>[field id="ovenlys"]</td>
</tr>
<tr>
<td>Frekvens</td>
<td>[field id="frekvens"]</td>
</tr>
<tr>
<td>Boligtype</td>
<td>[field id="type"]</td>
</tr>
<tr>
<td>Udvendig/Indvendig</td>
<td>[field id="udv_indv"]</td>
</tr>
<tr>
<td>Billeder uploadet</td>
<td>[field id="billeder"]</td>
</tr>
</table>

<br><br>

**Comment by bainternet** [comment]
@mortendahl2010 

We can only make sure it is sent correctly, we can't solve issues on outlook or other webmail clients.

What you can do is to force HTML links with actually defining links in your email template
```HTML
<tr>
	<td>
		Field Name
	</td>
	<td>
		<a href="[field id="fieldid"]">[field id="fieldid"]</a>
	</td>
</tr>
```

thanks

**Comment by mortendahl2010** [comment]
EXCELLENT, THANK YOU, just what i needed
