### ISSUE TITLE
Recent Pro update (possibly 2.4.0) rendering Custom CSS useless

### ISSUE THREAD

**Issue by easygav** [elementor/elementor#7365]
Hi guys. 

The following custom CSS which has created transparent headers effectively suddenly stopped working on all instances immediately after a recent Elementor Pro update (checked by rolling back to previous version which sees the custom CSS work fine again).

Custom CSS:
body:not(.elementor-editor-active) .elementor-type-header.elementor-location-header {
    position: absolute;
    width: 100%;
    z-index: +1;
}

The update in question could be 2.4.0 from looking at the changelog, which included, Fix: selector replacement in Custom CSS).

 My business cannot be the only one affected by this so is it worth raising as a minor conflict, or just simply a case of sharing what the new selector(s) need to be to ensure it continues working as before? 

Any help, very much appreciated.

Gavin

**Comment by shilo-ey** [comment]
Thanks for reporting,

Please provide examples for us to understand your issue better.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by easygav** [comment]
Ah, ok, sincere apologies for not doing this before. I've tried my best below.

Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The following custom CSS which has created transparent headers effectively suddenly stopped working on all instances immediately after a recent Elementor Pro update (checked by rolling back to previous version which sees the custom CSS work fine again).

Custom CSS:
body:not(.elementor-editor-active) .elementor-type-header.elementor-location-header {
position: absolute;
width: 100%;
z-index: +1;
}

The update in question could be 2.4.0 from looking at the changelog, which included: Fix: selector replacement in Custom CSS

Example of the issue in action when updated to the latest version of Elementor Pro 2.4.7:
https://gjlandscapes.com

Example of the issue temporarily resolved by rolling back to Elementor Pro version 2.3.1:
https://cdcleaningservices.co.uk

## Steps to reproduce

Rolling back to a previous version of Elementor Pro (suspected anything before v. 2.4.0) on one of our customer websites (for example https://cdcleaningservices.co.uk) and the custom CSS noted below renders the header transparent, displaying correctly throughout the site according to the conditions set: 

Custom CSS:
body:not(.elementor-editor-active) .elementor-type-header.elementor-location-header {
position: absolute;
width: 100%;
z-index: +1;
}

Updating Elementor Pro on another of our customer websites (https://gjlandscapes.com) to the latest version 2.4.7 and the transparency is lost.

It's presumed that the custom CSS is no longer recognized but this is based on logic; I'm not technical in any way and don't know how to alter the custom CSS so that it is still recognised.




## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

System Info for example of the issue in action (https://gjlandscapes.com):
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Unix) mod_hive/6.25 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
	MySQL version: Percona Server (GPL), Release 82.1, Revision 1a00d79 v5.6.36-82.1
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://gjlandscapes.com
	Home URL: https://gjlandscapes.com
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.7.0
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.86
		Author: ServMask

	All-in-One WP Migration File Extension
		Version: 1.4
		Author: ServMask, Inc.

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Cookiebot | GDPR Compliant Cookie Consent and Notice
		Version: 2.2.2
		Author: Cybot A/S

	Disable Site
		Version: 1.3.1
		Author: Jimmy K. <jimmy@nintencode.com>

	Elementor
		Version: 2.5.3
		Author: Elementor.com

	Elementor Pro
		**Version: 2.4.7**
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Imagify
		Version: 1.8.4.1
		Author: WP Media

	iThemes Security
		Version: 7.3.1
		Author: iThemes

	ManageWP - Worker
		Version: 4.7.5
		Author: GoDaddy

	SG Optimizer
		Version: 5.1.1
		Author: SiteGround

	UpdraftPlus - Backup/Restore
		Version: 1.16.6
		Author: UpdraftPlus.Com, DavidAnderson

	WP-SpamShield
		Version: 1.9.17
		Author: Scott Allen

	Yoast SEO
		Version: 9.7
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP



System Info for example of temporary resolve by rolling back to previous Elementor Pro version (https://cdcleaningservices.co.uk):				

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Unix) mod_hive/6.25 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
	MySQL version: Percona Server (GPL), Release 82.1, Revision 1a00d79 v5.6.36-82.1
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://cdcleaningservices.co.uk
	Home URL: https://cdcleaningservices.co.uk
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.7.0
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.86
		Author: ServMask

	All-in-One WP Migration File Extension
		Version: 1.4
		Author: ServMask, Inc.

	Astra Pro
		Version: 1.7.0
		Author: Brainstorm Force

	Autoptimize
		Version: 2.4.4
		Author: Frank Goossens (futtta)

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Cookiebot | GDPR Compliant Cookie Consent and Notice
		Version: 2.2.2
		Author: Cybot A/S

	Disable Site
		Version: 1.3.1
		Author: Jimmy K. <jimmy@nintencode.com>

	Elementor
		Version: 2.5.3
		Author: Elementor.com

	Elementor Pro
		**Version: 2.3.1**
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Imagify
		Version: 1.8.4.1
		Author: WP Media

	iThemes Security
		Version: 7.3.1
		Author: iThemes

	ManageWP - Worker
		Version: 4.7.5
		Author: GoDaddy

	SG Optimizer
		Version: 5.1.1
		Author: SiteGround

	UpdraftPlus - Backup/Restore
		Version: 1.16.6
		Author: UpdraftPlus.Com, DavidAnderson

	W3 Total Cache
		Version: 0.9.7.2
		Author: Frederick Townes

	WP-SpamShield
		Version: 1.9.17
		Author: Scott Allen

	Yoast SEO
		Version: 9.7
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP


I've really tried to give as much information as possible but am totally new to this and, being completely honest, didn't expect to be sent to you by Elementor Premium Support. 

Please accept my apologies if there is anything above that is incorrect or appears plain stupid!

Thank you for any help and support with this urgent issue.

Gavin.

**Comment by easygav** [comment]
Sorry, closed in error.

**Comment by easygav** [comment]
Apologies, I closed the issue by accident - now reopened and very much in need of help.

**Comment by shilo-ey** [comment]
Hi @easygav 

Thanks for elaborating.

The CSS code you provided simply sets the position of the header to absolute and sets 100% width with some z-index.

```CSS
body:not(.elementor-editor-active) .elementor-type-header.elementor-location-header {
position: absolute;
width: 100%;
z-index: +1;
}
```

What you are trying to achieve? Transparent header?

Please explain better with examples.

Thanks

**Comment by easygav** [comment]
Hi @shilo-ey - thanks for your response. 

Yes, a transparent header (in effect) is exactly what has been achieved on countless customer websites over the last 12 months by using this custom CSS. However, a recent Elementor Pro update (which I suspect is v2.4.0 - see examples below to illustrate) has seen every single website with this custom CSS lose its transparent header.

Examples below show the CSS working and not working:

Example of the CSS not working (i.e. transparent header effect lost); this website is running the latest version of Elementor Pro 2.4.7 as explained in my previous reply:
https://gjlandscapes.com

Example of the transparent header effect in action, which has been achieved by rolling back to Elementor Pro version 2.3.1 (also noted in my previous reply):
https://cdcleaningservices.co.uk

I'm not technical enough, but logic clearly suggests something within the Elementor Pro update is stopping the custom CSS in question working - I need to know why and would assume this is affecting other peoples/ businesses websites. 

I am hoping you can help provide fix for this custom CSS issue so that it is possible to update my customer websites to the latest version of Elementor Pro now and in the future whilst maintaining the transparent header effect using custom CSS - is this possible? 

Best regards
Gavin.

**Comment by shilo-ey** [comment]
Hi @easygav 

Try adding this custom CSS in your Header template:
```CSS
.elementor.elementor-location-header {
    position: absolute;
    width: 100%;
    z-index: 999;
}
```
Or this one in your header template:
```CSS
selector {
    position: absolute;
    width: 100%;
    z-index: 999;
}
```

Let me know if that solved the issue for you.
BTW - nothing has changed, just your custom CSS has been deleted somehow.

Thanks.

**Comment by easygav** [comment]
Thank you for this, @shilo-ey , I really do appreciate it - I'll have a go and let you know if it solves the issue. 

Your point about the custom CSS being deleted is strange, as it hasn't been deleted; it is showing in the custom CSS just like it always way?? I'll double check and report back on this as well to ensure there is nothing else going on here...

Thanks again, speak soon.
Gavin

**Comment by easygav** [comment]
@shilo-ey - just coming back to you as agreed. 

Neither of those Custom CSS snippets works, unfortunately. 

You said 'the CSS has been deleted somehow' which is exactly how the affected websites look; as if the custom CSS is just not working (like its not there). The thing is, it is there. It is sitting in the Builder header template (section) custom CSS box on each and every website as it was when I created them...

Custom CSS on gjlandscapes.com:
![image](https://user-images.githubusercontent.com/48327226/54289295-cb55ea00-45a0-11e9-8ea0-bffe97a5d3f3.png)

Front-end Screenshot as if the custom CSS is not there, like its been deleted:
![image](https://user-images.githubusercontent.com/48327226/54289379-f7716b00-45a0-11e9-9447-87ed94bc69b2.png)

Could this be a bug in an update that is somehow rendering this custom CSS useless?

Any further help or guidance you have is greatly appreciated.
Thanks.

**Comment by shilo-ey** [comment]
Hi @easygav 

This is not an issue.
You simply need to add custom CSS correctly. By inspecting your website - you didn't implement the code I provided correctly because it is not printed in the CSS.

Try clearing your cache, regenerating CSS, and check if it appears.

Thanks.

**Comment by easygav** [comment]
@shilo-ey 

The reason I'd not saved your CSS in the Builder (hence why you couldn't see it) is because when I tried it, it didn't show any change... It does show now (thank you so much for that!), and it was actually a server level cache clearance that sorted this. 

If you have a quick moment to try explain why the other custom CSS suddenly stopped working (due to an Elementor Pro) update I'd really (really) appreciate it? [This issue has cost my business and customers a huge amount of time and stress to resolve, and I want to avoid it happening again at all costs - not to mention bothering good people like you with what must feel like 'silly little' issues!!]

Any insight as to why it happened is much appreciated - thank you once again, seriously.
