### ISSUE TITLE
PopUps do not allow for navbar/menu dropdown widgets

### ISSUE THREAD

**Issue by jcmatoskx** [elementor/elementor#7369]
I am trying to use the Elementor Popup as an alternative to creating Mega menus, as suggested by Ben [here](https://www.facebook.com/groups/Elementors/permalink/1887771634681947/) and as sort of shown[ here](https://elementor.com/blog/responsive-menu-popups/?fbclid=IwAR2Jz0LiHh2-dQcWtuccqfwL_k9tX5uM5THIY89NuzaYvP81-RB-_vmhf1s)

However the Elementor Popup does not seem to allow for content to go render outside of it, so when I try to add a navbar widget with a dropdown, the dropdown never shows

I showed this issue more in depth in this video.
https://photos.app.goo.gl/77CWp11ZVuvFjsgRA

Is there any way, with CSS or something, to allow the content to render through and outside of the popup area? I have tried setting the Z parameters to 9999 but it doesn't affect anything

Increasing the area of the Popup, making 2 columns and making the background transparent works, but doesn't let to click through it to click in the website content, which is the main purpose, as I am trying to create an auxiliary menu.

Thank you for the attention and advice in advance.

**Comment by shilo-ey** [comment]
Hi @jcmatoskx 
This is not a bug, this is the wanted behavior.

You can't see the menu because the popup width is too narrow. Try using Dropdown nav-menu layout instead of vertical.

Alternatively you can set custom CSS to your popup document (please note that it might cause some issues)

```CSS
selector .elementor-popup-modal .dialog-message {
	overflow-x: visible;
}
```

Thanks

**Comment by jcmatoskx** [comment]
Awesome @shilo-ey , I really appreciate you sharing a CSS code possibility, however I am not managing to get it to work. I have tried adding it on different levels, (from the master popup custom CSS all the way to the widget layer, tried adding !important tags and also used the inspector to try out a few different class variations but I still haven't managed to make the drop menu appear through the popup sides. 

Thank you in advance for the attention and advice.

**Comment by kingfisher64** [comment]
Thanks for the solution @shilo-ey 

Why would this be intentional behaviour? Off the top of my head, I could say dynamic menu options could mess up the display? Just curious.

Thanks @jcmatoskx for asking the question which leads to a solution.

**Comment by Hamzadev119** [comment]
> Awesome @shilo-ey , I really appreciate you sharing a CSS code possibility, however I am not managing to get it to work. I have tried adding it on different levels, (from the master popup custom CSS all the way to the widget layer, tried adding !important tags and also used the inspector to try out a few different class variations but I still haven't managed to make the drop menu appear through the popup sides.
> 
> **EDIT:** I managed to make it work very nicely if I edit the CSS overflow directly on the browser inspector, however when I add the same CSS code to the popup through elementor I can't get it to work. I made a video showing this here: https://photos.app.goo.gl/AtM434hXe55ZcXvB6
> 
> **Edit 2** Scratch that, I managed to make it work with
> 
> ```
> .dialog-message.dialog-lightbox-message {
>     overflow: visible;
> }
> ```
> 
> Thank you in advance for the attention and advice.

Hi, these codes are in the custom CSS of elementor popup. 
Can you let me know where I need to add this code? I'm facing the same issue but am unable to resolve it.
Thank you in advance for the attention and advice
