### ISSUE TITLE
Option to download the Page (with html, css, js embedded) to use outside of WordPress

### ISSUE THREAD

**Issue by salvimateus** [elementor/elementor#7370]
## Prerequisites
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Take advantage of the page builder for sites outside of WordPress.

**Describe the solution you'd like**
Create a page normally through the page builder of Elementor and have an option to download the page's HTML (with embedded CSS, JS) to use the layout on a website outside of Wordpress.

**Describe alternatives you've considered**
None.

**Additional context**
This plugin already has this feature. Watch her working live:
http://www.brizydemo.com/guest
(It's also a page builder for Wordpress - https://brizy.io)

**Comment by shilo-ey** [comment]
Hi @salvimateus 

As mentioned in #4743 currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by t3m1sHack** [comment]
Please yes this feature is highly demanded! 

Create a page normally through the page builder of Elementor and have an option to download the page's HTML (with embedded CSS, JS) to use the layout on a website outside of Wordpress.

When would you enable this feature?

**Comment by tapasfun** [comment]
Yes, I also looking for this feature and come here. Please add this feature.

**Comment by fal90210** [comment]
Yes this feature is very much needed. Thank You!

**Comment by pythonDON0161** [comment]
would love this feature as well

**Comment by rajkavinchetty** [comment]
Seriously, this will help us in a lot of ways - like to create a sales page for a client who doesn't use WordPress for his main site. Consider adding this!
