### ISSUE TITLE
Slider Builder

### ISSUE THREAD

**Issue by salvimateus** [elementor/elementor#7371]
## Prerequisites
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Create slider with animations and with different structures in each item.

**Describe the solution you'd like**
Create a session normally through the page builder and have an option to convert it to a slider item. And on each item, use the page builder freely.

**Describe alternatives you've considered**
None.

**Additional context**
The "Brizy" page builder already has this feature to create a session> convert it to a slider item.

**Comment by simonclay** [comment]
Great idea :) +1

**Comment by shilo-ey** [comment]
Hi @salvimateus 

I merged this issue with #2445, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel introduced in Elementor Pro v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
