### ISSUE TITLE
Facebook Like Popup Box

### ISSUE THREAD

**Issue by alalone2017** [elementor/elementor#7372]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
_A clear and concise description of the idea._ 
This is actually a feature I would like Elementor to have. I am suggesting a dedicated Popup Facebook Page Like template, that gives the possibility to the website owner to promote their Facebook Page. 

**Describe the idea you'd like**
_A clear and concise description of what you want to happen._
My idea for the template is to have a dedicated space to insert the FB Page (already possible by putting the Facebook Page widget, but it could be done more professionally), and an algorithm to check if the user has liked the page or not. If yes, it shouldn't show the Popup anymore, otherwise continue to show it. I would suggest adding a maximum amount of times the Popup should show up if the client/visitor doesn't like it, to not become annoying. Let me explain better with some examples: 

_First scenario:_ Visitor comes to website -> Popup shows up -> Visitor clicks "Like" button and likes the page -> Visitor spends some time on the website and then leaves -> After some time, visitor comes back to website -> Popup **doesn't** show up because **visitor has already** liked the page

_Second scenario:_ Visitor comes to website -> Popup shows up -> Visitor ignores the Popup and closes it -> Visitor spends some time on the website and then leaves -> After some time, visitor comes back to website -> Popup **shows up** because **visitor has NOT** liked the page the last time -> This time visitor **likes** the page -> Popup **doesn't show up** anymore

_Third scenario:_ This is similar to the second scenario described above, only that the visitor refuses to like the page, let's say 3 times he visited the website, so after third time of refusal Popup **shouldn't show up** anymore, in order not to become annoying

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
What I have now is a Popup with the "Facebook Page" and "Facebook Like" widget, with one condition: Don't show the Popup more than 3 times in total. This means the Popup won't show more than 3 times, regardless if the visitor liked the page or not. This is exactly the point. Let's assume the visitor liked the page the first time he visited the website, and when he comes back for the second and the third time, he sees the Popup again and says: "Excuse me, I've already liked the page last time I visited, so why are you showing me this again?!". So there needs to be an algorithm that check whether the visitor has liked the page or not. And I repeat, if he refuses to like it continuously, the Popup **should not** show up after certain amount of times. I hope I made myself clear.

**Additional context**
_Add any other context or screenshots about the feature request here._
As a back-end programmer, I think this could be done easily with cookies, but we can think maybe of a more professional solution. I am open to contribute and help, it will be a pleasure. 

Thank you guys, I think this is a must-have feature for Elementor, and I think I'm not the only one who needs this. 

Cheers,

Robert

**Comment by bainternet** [comment]
I merged this issue with  #6899 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
