### ISSUE TITLE
[Feature request] Section "Custom positioning" everywhere

### ISSUE THREAD

**Issue by thehervy** [elementor/elementor#7373]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Custom positioning is sooo cool feature which can be done with css, but the way you guys implemented it is so intuitive, BUT - it works only on single elements only.  I have to do it manually in case of sections/rows etc..

**Describe the solution you'd like**
Have the posibility to customize position on every element, section, row etc.. basically everytime I open option of something on my page.

**Describe alternatives you've considered**
I tried CSS but it is not intuitive and i bit problematic in case of responsiveness..

**Additional context**
None. I hope it is self-explanatory, otherwise I will be in touch :)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Bannerman** [comment]
This would save me a lot of time!

**Comment by thehervy** [comment]
For others: I am currently using negative (and positive) margins set and playing with that to do such positioning. It works quite well, but it is not that intuitive as Custom positioning feature.

**Comment by Vodnick** [comment]
Any update on planning to introduce this feature?
