### ISSUE TITLE
v2.5.3 breaks background video responsive.

### ISSUE THREAD

**Issue by dollhauss** [elementor/elementor#7374]
Elementor v2.5.3 breaks section background video responsive.
It no longer maintains full section height responsively.
CSS 'cover' has stopped working, it is stuck on 'contain'.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
