### ISSUE TITLE
Proper usage of Ajax in Custom Widgets

### ISSUE THREAD

**Issue by DeoThemes** [elementor/elementor#7375]
## Prerequisites
- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description
I'm trying to create load-more function in custom widget. Currently it's working, but only if I'm calling Ajax from the main plugin Class inside **init()** method. I have to place Ajax hook in the the same Class in order to make it work. Is there a way how to call Ajax and all it's hooks directly in widget class?

**Comment by bainternet** [comment]
I merged this issue with  #6899 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bainternet** [comment]
@DeoThemes 

Nope, the widgets are registered too late for hooking AJAX actions.

thanks.

**Comment by mapsmarketing** [comment]
Hi @DeoThemes 

You have to register the ajax hooks from within the widget's module, see following link for more info: https://github.com/elementor/elementor/issues/8045#issuecomment-491405275
