### ISSUE TITLE
Get control value in other control

### ISSUE THREAD

**Issue by wayheming** [elementor/elementor#7377]
Hi Elementor team =)
I need your help again. How can I get the value of a control inside another control to create a selector?
```
$this->add_control(
	'popup_id',
	[
		'label'   => esc_html__( 'ID', 'theme' ),
		'type'    => Controls_Manager::TEXT,
		'default' => 'popup_1',
	]
);

$this->add_group_control(
	Group_Control_Background::get_type(),
	[
		'name'     => 'background',
		'selector' => '#{{popup_id.VALUE}}.popup-content',
	]
);
```

I found several examples of this behavior in your code, but I could not find a example to get the value of a text control. http://prntscr.com/muyo5f http://prntscr.com/muyo7v

I will be very grateful for your help. Thanks in advance!

**Comment by bainternet** [comment]
@wayheming 

You are using it correctly except that in group controls (like `Group_Control_Background` ) you can only use controls from inside the group itself.

thanks.

**Comment by wayheming** [comment]
@bainternet 
Thank you, I understand. Is there any other way to build a selector for groups of controls based on the value of another control?

**Comment by vlthemes** [comment]
Hello!
Did you solve this?

**Comment by nimaaminz** [comment]
I can get value by  {{your_control_id.VALUE}} very well by I have problem in responsive mode ,
{{your_control_id.VALUE}}  just return the value on desktop and in mobile mode it will return desktop value again ! 
what should I do ?

**Comment by nimaaminz** [comment]
> I can get value by {{your_control_id.VALUE}} very well by I have problem in responsive mode , {{your_control_id.VALUE}} just return the value on desktop and in mobile mode it will return desktop value again ! what should I do ? with using your_control_id_mobile the proplem will solve but i want to use all mode value ! how can i tell to control and selector in which screen use desktop and mobile

I find the solution ! 
i
I added two more selector and just before the {{WRAPPER}}  I added (mobile ) / (tablet) /(desktop )  like this  : 

`
'selectors' => [
					'(desktop){{WRAPPER}} {{CURRENT_ITEM}} htt' => 'transform:translate({{rp_translatex_text.VALUE}}vw,{{VALUE}}vh)',
					'(tablet){{WRAPPER}} {{CURRENT_ITEM}} htt' => 'transform:translate({{rp_translatex_text_tablet.VALUE}}vw,{{VALUE}}vh)',
					'(mobile){{WRAPPER}} {{CURRENT_ITEM}} htt' => 'transform:translate({{rp_translatex_text_mobile.VALUE}}vw,{{VALUE}}vh)',
				] ,
`
and for each responsive mode get the responsive id like your_id_mobile.VALUE !

**Comment by satindersinghsidhu** [comment]
@bainternet Can we use one VALUE from elementor group control to another class?

Suppose I'm using typography group control for title and I want to apply its font-family on description, not any other values like font-size, weight etc.
