### ISSUE TITLE
HTML Widget 403 Error on WP Multisite

### ISSUE THREAD

**Issue by bigwilliam** [elementor/elementor#7379]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After adding code in an HTML widget and trying to save, I'm getting the following error: https://cl.ly/705b7460696c

Before adding code to the box, the page will save fine, it only fails after adding code snippets inside of `<script>` tags.

Please see the following gif video with an example: https://cl.ly/2670eba6ca4b

This example is on a WP Multisite install with Elementor Pro. When trying on a single site this error does not happen. I've already tried this with a standard WP theme (i.e. TwentySeventeen) and with all other plugins disabled besides Elementor. The only difference is this happens on Multisite. 

## Steps to reproduce

1. Set up a WP Multisite install
2. Install Elementor and Elementor Pro
3. On one of the sites, create a page and add the HTML widget
4. Paste any kind of Javascript inside the box `<script> ... </script>`
5. Try to save the page

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: (Debian) v5.6.42-84.2
	PHP Version: 5.6.40-0+deb8u1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://d3fy.d3fy.site
	Home URL: https://d3fy.d3fy.site
	WP Multisite: Yes
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.3
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.2
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 2.4.7
		Author: Elementor.com

	Favicon by RealFaviconGenerator
		Version: 1.3.15
		Author: Philippe Bernard

	Gravity Forms
		Version: 2.4.6
		Author: rocketgenius

	Insert Headers and Footers
		Version: 1.4.3
		Author: WPBeginner

	Nested Pages
		Version: 3.0.7
		Author: Kyle Phillips

	Really Simple SSL
		Version: 3.1.5
		Author: Rogier Lankhorst, Mark Wolters

	Resize Image After Upload
		Version: 1.8.5
		Author: ShortPixel

	The SEO Framework
		Version: 3.2.3
		Author: Sybre Waaijer

== Network Plugins ==
	Antispam Bee
		Version: 2.9.1
		Author: pluginkollektiv

	BackWPup
		Version: 3.6.8
		Author: Inpsyde GmbH

	Breeze
		Version: 1.0.10
		Author: Cloudways

	Wordfence Security
		Version: 7.2.3
		Author: Wordfence

== Log ==
	: 
Log: showing 7 of 72019-01-21 22:31:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.4.3',
)]
2019-01-21 22:31:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.2.3',
  'to' => '2.4.0',
)]
2019-01-24 21:51:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-31 14:42:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-01-31 14:42:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.3',
)]
2019-03-08 12:05:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.5.3',
)]
2019-03-08 12:05:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.7',
)]

JS: showing 9 of 9JS: 2019-01-31 21:16:21 [error X 1][https://d3fy.d3fy.site/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view7659\") has already been destroyed and cannot be used. 
JS: 2019-01-31 21:56:04 [error X 1][https://d3fy.d3fy.site/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view533\") has already been destroyed and cannot be used. 
JS: 2019-01-31 22:38:28 [error X 1][https://d3fy.d3fy.site/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view14185\") has already been destroyed and cannot be used. 
JS: 2019-01-31 23:20:06 [error X 3][https://d3fy.d3fy.site/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.3:2:15986] Cannot read property \'model\' of undefined 
JS: 2019-02-01 23:24:30 [error X 1][https://d3fy.d3fy.site/wp-admin/post.php?post=392&action=elementor:1:36] gformInitSpinner is not defined 
JS: 2019-02-04 21:05:19 [error X 1][https://d3fy.d3fy.site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:6883] Cannot read property \'select2\' of undefined 
JS: 2019-02-07 21:45:53 [error X 6][https://d3fy.d3fy.site/wp-admin/post.php?post=491&action=elementor:19:41] Cannot read property \'replace\' of undefined 
JS: 2019-03-08 12:17:20 [error X 1][https://d3fy.d3fy.site/wp-admin/post.php?post=491&action=elementor:2:5] v is not defined 
JS: 2019-03-08 12:17:21 [error X 3][https://d3fy.d3fy.site/wp-admin/post.php?post=491&action=elementor:3:1] Unexpected end of input 

				
</details>

**Comment by bainternet** [comment]
@bigwilliam 	


We can't replicate, which means its most likely a server security configuration issue (ex: mod_security) or a security plugin which is blocking the save request. 

Please check with your host, and if the issue still persists,  
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by bigwilliam** [comment]
I found the solution, putting it here for reference:

The culprit was my Wordfence security plugin firewall. This article helped me fix the issue: https://www.ownerreservations.com/support/articles/403-error-whitelisting-wordfence
