### ISSUE TITLE
dynamic shortcode backgroun image error

### ISSUE THREAD

**Issue by webdee** [elementor/elementor#7380]
Hello,

i want to use this shortcode:

```
function get_the_typology_acf_image () {
$image = get_field('immagine', get_queried_object());
return $image;
}
add_shortcode( 'the_typology_acf_image', 'get_the_typology_acf_image' );
```

inside a dynamic shortcode field on background image of a section.

The image not appear and this is the error that result:

Warning: Illegal string offset 'url' in .../wp-content/plugins/elementor/includes/controls/base-multiple.php on line 87

i tested the shortcode and work fine, the result is the ACF image field array.

**Comment by bainternet** [comment]
@webdee 	

what does the returned array look like?

steps to replicate?
ACF field settings?

**Comment by webdee** [comment]
Hello @bainternet ,

the array returned is:

`array(24) { ["ID"]=> int(556) ["id"]=> int(556) ["title"]=> string(12) "tipologia-bg" ["filename"]=> string(16) "tipologia-bg.png" ["filesize"]=> int(2139185) ["url"]=> string(76) "http://www.testsite.test/wp-content/uploads/2019/03/tipologia-bg.png" ["link"]=> string(56) "http://www.testsite.test/?attachment_id=556#main" ["alt"]=> string(0) "" ["author"]=> string(1) "1" ["description"]=> string(0) "" ["caption"]=> string(0) "" ["name"]=> string(12) "tipologia-bg" ["status"]=> string(7) "inherit" ["uploaded_to"]=> int(505) ["date"]=> string(19) "2019-03-07 11:50:14" ["modified"]=> string(19) "2019-03-07 11:50:14" ["menu_order"]=> int(0) ["mime_type"]=> string(9) "image/png" ["type"]=> string(5) "image" ["subtype"]=> string(3) "png" ["icon"]=> string(69) "http://www.testsite.test/wp-includes/images/media/default.png" ["width"]=> int(3840) ["height"]=> int(1368) ["sizes"]=> array(12) { ["thumbnail"]=> string(84) "http://www.testsite.test/wp-content/uploads/2019/03/tipologia-bg-150x150.png" ["thumbnail-width"]=> int(150) ["thumbnail-height"]=> int(150) ["medium"]=> string(84) "http://www.testsite.test/wp-content/uploads/2019/03/tipologia-bg-300x107.png" ["medium-width"]=> int(300) ["medium-height"]=> int(107) ["medium_large"]=> string(84) "http://www.testsite.test/wp-content/uploads/2019/03/tipologia-bg-768x274.png" ["medium_large-width"]=> int(768) ["medium_large-height"]=> int(274) ["large"]=> string(85) "http://www.testsite.test/wp-content/uploads/2019/03/tipologia-bg-1024x365.png" ["large-width"]=> int(1024) ["large-height"]=> int(365) } }`

the steps are:

inserted section widget, after going to style->background->background image->selected dynamic->shortcode and inserted: "[the_typology_acf_image]"

the ACF field setting are:

`acf_add_local_field_group(array(
	'key' => 'group_5c81073f6440d',
	'title' => 'Dettagli tipologia',
	'fields' => array(
		array(
			'key' => 'field_5c810756b59d2',
			'label' => 'Immagine',
			'name' => 'immagine',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'typology',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));`

**Comment by stickypages** [comment]
@webdee Did you figure this out by chance?

**Comment by webdee** [comment]
Unfortunately not yet, even if i use the ACF Image field option and i select the ACF image field created for the custom taxonomy it is not appear, i think it is because i am in the archive taxonomy template and elementor get the loop of the posts and not the query of the taxonomy.

**Comment by shilo-ey** [comment]
Hi @webdee @stickypages 

Please [see here](https://github.com/elementor/elementor/issues/7730#issuecomment-480578240)

Thanks.
