### ISSUE TITLE
Dynamic Shortcode per user

### ISSUE THREAD

**Issue by nathnath9** [elementor/elementor#7382]
Is it possible to display specific shortcode elements depending on the user logged in?

Thanks

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your question - This kind of thing should be done inside the shortcode function.

See if using [dynamic tags](https://docs.elementor.com/article/310-dynamic-content) helps you.
