### ISSUE TITLE
Site Tagline widget

### ISSUE THREAD

**Issue by lcswillems** [elementor/elementor#7384]
## Prerequisites

- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

**Describe the solution you'd like**
A widget "Site Tagline". Currently, there are only a widget "Site Logo" and "Site Title".

**Describe alternatives you've considered**
Trying to install some themes that would propose a Elementor Tagline widget, but no such widget proposed.

**Comment by bainternet** [comment]
@lcswillems 

You can create a simple shortcode for that and call it using [Dynamic Shortcode](https://docs.elementor.com/article/449-dynamic-shortcode)

```PHP
add_shortcode( 'site_tag_line', function( $atts = [] ) {
	return get_bloginfo( 'description' );
} );
```
