### ISSUE TITLE
Hello all , i am new to elementor plugin extension development i want to created a custom product archive woocommerce extension in elementor which overide template the shop page pro-grammatically just like the elementor pro plugin does but i am not able to do this can you please help me out from the same

### ISSUE THREAD

**Issue by SwapnilPandyathegr8** [elementor/elementor#7385]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Galaykos** [comment]
It is an Elementor Pro feature, I suggest to just buy the license, people worked hard for it.

**Comment by bainternet** [comment]
Elementor Pro uses the native WordPress `template_redirect` action hook for that.
