### ISSUE TITLE
Unable to Init Swiper Carousel for Custom Widget Based on Testimonial Carousel

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#7386]
I know this is not a place for support, but I've submitted a regular support ticket, and was refered here.

I'm trying to make a custom widget based on EPro Testimonial Carousel. For a starter, I downloaded Hello World plugin (https://github.com/elementor/elementor-hello-world) and simply copied there the Testimonial Carousel widget from elementor-pro/modules/carousel/widgets/.

The controls seem to work quite nice, but the carousel is not "carouseling". The html/class structure of the carousel is the same, but it seems like it wasn't initialized. How can I make it work? 

Here is the carousel test page: https://behaviolabs.com/dev/carousel-test/. First carousel is the original one, the second is my dyplicate.

From inspectioning EPro code it seems, that the init is triggered in this part:

```
module.exports = function () {
elementorFrontend.hooks.addAction('frontend/element_ready/testimonial-carousel.default', __webpack_require__(6));
};
```
How and where I could use something similar in my plugin?

Javascript is not mine domain and I'm really not familiar with webpack principles, so I've got lost here.

I've also tried to init swiper manually in plugin's hello-world.js, but it didin't work either.

```
( function( $ ) {
	var WidgetHelloWorldHandler = function( $scope, $ ) {
		  var mySwiper = new Swiper ('.my-carousel', {
			  direction: 'vertical',
			  loop: true,
                          ...
			  },
		  })
	};
	// Make sure you run this code under Elementor..
	$( window ).on( 'elementor/frontend/init', function() {
		elementorFrontend.hooks.addAction('frontend/element_ready/my-carousel.default', WidgetHelloWorldHandler );
	} );
} )( jQuery );
```

I've tried to study dev docs and several similar issues here, but haven't found the answer. 
Thanks a lot.

**Comment by black-eye** [comment]
In the meantime, I've managed to init the caousell manually by this JS code

```
( function( $ ) {
	var WidgetHelloWorldHandler = function( $scope, $ ) {

		  var mySwiper = new Swiper ('.elementor-widget-lide-carousel .swiper-container', {
			  loop: 0,
			  slidesPerView: 3,
			  slidesPerGroup: 3,
                          ....
		  })
	};

	$( window ).on( 'elementor/frontend/init', function() {
		elementorFrontend.hooks.addAction('frontend/element_ready/lide-carousel.default', WidgetHelloWorldHandler );
	} );
} )( jQuery );
```

The trick was to get to the right selector, in this case `.elementor-widget-lide-carousel .swiper-container`.

Unfortunately, all the Swiper settings need to be hardcoded now. I've tried to use the settings from data attribute (e.g. `loop: $scope.data('settings').loop`) but it worked only partially. On the frontend it works fine, but in the editor the carousel is broken and not initialized (the $scope.data is undefined).

Pls, @bainternet, @shilo-ey, how should I do it right? I suppose, there should be some simple trick to it, but my JS knowledge is not on the level I can sort it out by myself.

**Comment by jphilung** [comment]
i have the same issue. because the JS related to the swiper widget is in a webpack module which is not accessible through a global variable, i can't reuse the code. basically, to get all the options, i'd need to copy all the JS code related to the module.

is there any other way i could reuse the module code without copying it ?

cheers !

**Comment by udidol** [comment]
Hi @black-eye ,
The Testimonial Carousel widget inherits from a base class. This base class enqueues the Swiper JS. If you use the Testimonial Carousel's code, you need to use the base as well.

I would recommend you go over the base class (it is also in the same `carousel/widgets` directory), take all the necessary parts from there, then add them to your widget in order for everything to work properly.

I know this is very old now but it is good to have this info here for future reference.

**Comment by perforsberg77** [comment]
Hi,

Can anyone explain what parts from base class that needs to be added when you do a custom widget based on the testimonial carousel? I got everything else right, just missing the swiper connection.

**Comment by udidol** [comment]
Why would you want to extend the Testimonial Carousel?
I would recommend just building your own Carousel widget.

Here is the `SwiperBase` class: https://github.com/elementor/elementor/blob/master/assets/dev/js/frontend/handlers/base-swiper.js

To initialize Swiper, just call `new Swiper( container, options )`. The `container` element is the one on which you want Swiper to take over and build the carousel. The `options` variable is an object, containing options, which you can check out in [SwiperJS's documentation](https://swiperjs.com/swiper-api).

**Comment by perforsberg77** [comment]
Yes, I´m building my own by extending the testimonial carousel class, adding some controls and changing the rendering. I got it all working php/html/css wise, but not the js part. I can do like @black-eye above, but I don´t want to hardcode the settings when initializing Swiper. How can I initialize swiper and use the settings from elementor, just like the default testimonial carousel does?

**Comment by udidol** [comment]
@perforsberg77 
In your PHP, where you call `add_control()` to add the controls to your widget, in the options array, you pass a property:
`'frontend_available' => true,`.
Then, in your widget's JS handler, you can get all the frontend-available control values by calling `this.getElementSettings()`.

**Comment by mapsmarketing** [comment]
This is an old issue, but this might answer it for anyone wanting to use `SwiperBase`: https://github.com/elementor/elementor/issues/19858
