### ISSUE TITLE
Updating section control's condition arguments, overwrites all controls inside

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#7387]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hey! I wanted to make my own Column video background options because they're not yet added ( saw #5826 is still opened). 

I wanted Background overlay section to be applied on these settings so i wanted to override its condition eg:
```
$this->start_controls_section(
	'section_background_overlay',
	[
		'label' => __( 'Background Overlay', 'elementor' ),
		'tab' => Controls_Manager::TAB_STYLE,
		'condition' => [
			'background_background' => [ 'classic', 'gradient', '__new_condition_here__' ],
		],
	]
);
```

I used the hook below, after the section ends, and it seems that the condition is added to all its controls inside this section. Basically all controls inside are opened https://d.pr/i/p5Ei0k.

```
add_action( 'elementor/element/column/section_background_overlay/after_section_end', function ( $stack )
{
	// get section args
	$section_bg_overlay = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $stack->get_unique_name(), 'section_background_overlay' );
	// pass custom condition
	$section_bg_overlay['condition']['background_background'][] = '__new_condition__';
	// update control
	$stack->update_control( 'section_background_overlay', $section_bg_overlay );

});
```

I also tried adding `['recursive' => false]` as the 3rd parameter of  `$stack->update_control();`, but no luck.

Is this its expected behaviour?

**Comment by bainternet** [comment]
@hogash 

Basically yes, because the section has already ended his "setup" at the `../after_section_end` action hook.

maybe try using the `../after_section_start` hook instead sho in your case:

`elementor/element/column/section_background_overlay/after_section_start`

thanks.

**Comment by hogash** [comment]
@bainternet 🤦‍♂️ dooh!! Thanks Raz!!
