### ISSUE TITLE
PDF viewer

### ISSUE THREAD

**Issue by Zegklitz** [elementor/elementor#7389]
Hello,
do you plan to add some PDF viewer widget. It would be nice to show PDF file content inside the Elementor's page.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

I merged this issue with #2814, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by kazbekkadalashvili** [comment]
Hi @Zegklitz 
https://wordpress.org/plugins/pdf-viewer-for-elementor/
