### ISSUE TITLE
webhook does not POST to URL

### ISSUE THREAD

**Issue by danasmoove** [elementor/elementor#7391]
Hi,
We are trying to send form data to our email marketing system – Smoove.

We have set up a webhook in our elementor form with the following address:
https://members.viplus.com/subscribe.aspx....

in the form field advanced tab we have changed the field id’s to our systems required id’s.

tried to submit the form: https://www.sitesuccess.co.il/elementor-14618/ but nothing happens and the data is not transmitted

Can you say what is the problem?
Thank You.
![1](https://user-images.githubusercontent.com/48401957/54082108-4e650f00-4319-11e9-8811-7d15d910a5e7.JPG)
![2](https://user-images.githubusercontent.com/48401957/54082110-4efda580-4319-11e9-977e-457692254791.jpg)

**Comment by bainternet** [comment]
@danasmoove 	


I can only guess that the webhook expects the data to come in separate fields and when you set "Advanced Data" to true/on then all of the form data is sent as an array as one field.

thanks.

**Comment by danasmoove** [comment]
Hi,
I turned of advanced data and it still does not work
what can  do?
