### ISSUE TITLE
Allow the [space] character in the Telephone Validation

### ISSUE THREAD

**Issue by FlyThePlanet** [elementor/elementor#7394]
Hi,

Since the new Telephone Validation feature is available, only 0-9  (  )  *  #  +  -  . characters are allowed...
https://elementor.com/blog/advanced-form-fields/

But a huge majority of national conventions for writing telephone numbers include the [space] character...
https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers

So can you please allow the [space]?
It would allow visitors to enter their phone number as they are used to and would allow to read phone numbers much more easily for the addressee.

Thanks.
Best regards.

**Comment by bainternet** [comment]
@FlyThePlanet 

You have two options, either create a custom field via Forms API (examples: #6139, #7285 ) that will allow spaces or use the provided hooks to removed the native render and validations functions and replace with your own, ex:

```PHP
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {
	//remove native validation
	/**
	 * @var \ElementorPro\Modules\Forms\Module $forms_module
	 */
	$forms_module = \ElementorPro\Plugin::instance()->modules_manager->get_modules( 'forms' );
	remove_action( 'elementor_pro/forms/validation/tel', [ $forms_module->field_types['tel'], 'validation' ] );

	// run your own validation, ex:
	if ( empty( $field['value'] ) ) {
		return;
	}
	if ( preg_match( '/^[0-9()#&+*-=. ]+$/', $field['value'] ) !== 1 ) {
		$ajax_handler->add_error( $field['id'], 'Your validation failed message here.' );
	}
}, 9, 3 );

add_action( 'elementor_pro/forms/render_field/tel', function( $item, $item_index, $form ) {
	//remove native render
	/**
	 * @var \ElementorPro\Modules\Forms\Module $forms_module
	 */
	$forms_module = \ElementorPro\Plugin::instance()->modules_manager->get_modules( 'forms' );
	remove_action( 'elementor_pro/forms/render_field/tel', [ $forms_module->field_types['tel'], 'render' ] );

	// add your custom render ex:
	$form->add_render_attribute( 'input' . $item_index, 'class', 'elementor-field-textual' );
	$form->add_render_attribute( 'input' . $item_index, 'pattern', '[0-9()#&+*-=. ]+' );
	$form->add_render_attribute( 'input' . $item_index, 'title', __( 'Only numbers and phone characters (#, -, *, etc) are accepted.', 'elementor-pro' ) );
	echo '<input size="1" ' . $form->get_render_attribute_string( 'input' . $item_index ) . '>';
}, 9, 3 );
```


thanks.

**Comment by FlyThePlanet** [comment]
Very disappointing answer, while the fix would have just been so easy.
It's not because it exists heavy workarounds that Elementor should not look at how numbers are written all over the world and answer the question according to its relevance and usefulness.
The issue remains, even if you got rid of the ticket...
https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers

**Comment by odivius** [comment]
@FlyThePlanet @bainternet 

I also need spaces in the phone field.
The above solution generates 2 phone fields.
I placed the hooks in functions.php.

What am I doing wrong and what should I do?

**Comment by pauleroni** [comment]
The above code adds another "Phone" field to the form, I can confirm. The code is not accurate. I'm not sure where it's wrong, but  hoping to have a reply from Elementor on allowing spaces in the phone # field.

**Comment by preyes24973** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by NaudhizSowilo** [comment]
Instead of
`	remove_action( 'elementor_pro/forms/render_field/tel', [ $forms_module->field_types['tel'], 'render' ] );`
use
`	remove_action( 'elementor_pro/forms/render_field/tel', [ $forms_module->field_types['tel'], 'field_render' ] );`

complete code:
```php
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {
	//remove native validation
	/**
	 * @var \ElementorPro\Modules\Forms\Module $forms_module
	 */
	$forms_module = \ElementorPro\Plugin::instance()->modules_manager->get_modules( 'forms' );
	remove_action( 'elementor_pro/forms/validation/tel', [ $forms_module->field_types['tel'], 'validation' ] );

	// run your own validation, ex:
	if ( empty( $field['value'] ) ) {
		return;
	}
	if ( preg_match( '/^[0-9()#&+*-=. ]+$/', $field['value'] ) !== 1 ) {
		$ajax_handler->add_error( $field['id'], 'Your validation failed message here.' );
	}
}, 9, 3 );

add_action( 'elementor_pro/forms/render_field/tel', function( $item, $item_index, $form ) {
	//remove native render
	/**
	 * @var \ElementorPro\Modules\Forms\Module $forms_module
	 */
	$forms_module = \ElementorPro\Plugin::instance()->modules_manager->get_modules( 'forms' );
	remove_action( 'elementor_pro/forms/render_field/tel', [ $forms_module->field_types['tel'], 'field_render' ] );

	// add your custom render ex:
	$form->add_render_attribute( 'input' . $item_index, 'class', 'elementor-field-textual' );
	$form->add_render_attribute( 'input' . $item_index, 'pattern', '[0-9()#&+*-=. ]+' );
	$form->add_render_attribute( 'input' . $item_index, 'title', __( 'Only numbers and phone characters (#, -, *, etc) are accepted.', 'elementor-pro' ) );
	echo '<input size="1" ' . $form->get_render_attribute_string( 'input' . $item_index ) . '>';
}, 9, 3 );```

**Comment by lstplcwnr** [comment]
Checking in in 2022, this is still giving showing me two Tel fields, one of the new field with the right validation and the other old tel field. Any fixes to this?

**Comment by lstplcwnr** [comment]
Checking back in to let you know this is 100% working now. My next question would be if you would how to set maxlength and minlength of text form field (with specific ID) to 10 characters? Thank you very much @ivankuraev
