### ISSUE TITLE
Animation doesn't repeat

### ISSUE THREAD

**Issue by stefanocavaliere** [elementor/elementor#7395]
### Description
I have a popup where I put some heading texts. Every text has slideIn animation. 
The problem is that when I trigger the popup the first time the animation works perfectly but when I close the popup and reopen it the animation doesn't restart and the texts are hidden. 

### Steps to reproduce
a) Select some texts and add them animations inside a popup. 
b) Open the popup, close it and reopen it

### Environment
Elementor v2.5.3
Elementor Pro v2.4.7
Wordpress 5.1

**Comment by shilo-ey** [comment]
Hi @stefanocavaliere 

Thanks for your feedback.

We will consider adding this enhancement in the next versions.

Thanks.

**Comment by stefanocavaliere** [comment]
Hello shilo-ey, is there any workaround to make it work? 
I didn't think it could be an improvement...

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor Pro v2.5.7

Feel free to update!
