### ISSUE TITLE
Gray background color on mobile

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7399]
Hello guys,

I'm noticing that Elementor is automatically inserting a gray background (# c1c1c1) into the mobile (https://screenshot.net/pt/mpnd1i3? / https://screenshot.net/pt/m7wp6sm?) template. See the links below and notice that on the desktop the background color is white, but on the mobile it is gray:

https://idiomas.proddigital.com.br/lp/entrevista-de-emprego-em-ingles/download/
https://idiomas.proddigital.com.br/lp/vocabulario-em-ingles/download/
https://idiomas.proddigital.com.br/lp/ingles-com-musica/download/
https://idiomas.proddigital.com.br/lp/pronuncia-em-ingles/download/
https://idiomas.proddigital.com.br/lp/filmes-series/download/

It's strange because on another page, for example, the page below, it's showing me that in the mobile it is white normally and in the page editing it is showing me that it has no color set (https://screenshot.net/pt/4z4p3c4?), but when checking the code in the Chrome browser console, is also showing the gray background (https://screenshot.net/pt/89xres5?).

https://idiomas.proddigital.com.br/e-books-gratuitos/

I've checked in other browsers like IE and Opera, and have the same gray background problem.

But I checked in the Forefox browser and realized that the gray color in the background is not being set (https://screenshot.net/pt/jno5lsj?).

What can this be?

**Comment by shilo-ey** [comment]
This gray color origin from your theme:
```CSS
body {
  visibility: visible !important;
  background-color: #c1c1c1;
}
```
https://idiomas.proddigital.com.br/wp-content/themes**/Newspaper/mobile/style.css?ver=9.6**

Remove it from your theme's option / CSS file and it should be solved.

Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Thanks.

**Comment by rodrigocarlos** [comment]
Hello @shilo-ey,

If that background-color is from the CSS of my site's theme, then I could not remove it since it should be being used somewhere.
Elementor should not be using the theme CSS of my site.

By the way, as I mentioned above, the page https://idiomas.proddigital.com.br/e-books-gratuitos/ was also created with Elementor and is not gray.

Thank you!

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

This is not an overall issue but a specific compatibility issue with your theme

thanks.
