### ISSUE TITLE
Animated headline is cut off so the longest words only show the first half

### ISSUE THREAD

**Issue by AndyLQ** [elementor/elementor#7403]
i have 3 Rotating text no after text
and one of them is "Guest loyalty" and it is cut off for some users to only "Guest loyal"

**Comment by AndyLQ** [comment]
Not sure what the trigger is, only happens sometimes on phones so far

**Comment by AndyLQ** [comment]
https://youtu.be/Xh9iv4hW2dk
here a video with the bug

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it we simply can't help.

Thanks.

**Comment by enes993** [comment]
> i have 3 Rotating text no after text
> and one of them is "Guest loyalty" and it is cut off for some users to only "Guest loyal"

I had the same issue 
You have to put **Width : 100%;**  in the tag or class of the text in css !!
