### ISSUE TITLE
Form widget translation issue

### ISSUE THREAD

**Issue by FlyThePlanet** [elementor/elementor#7405]
When we use the Elementor Form widget and use WPML for the translations, there's an issue on 2 strings.
In the WPML "Page translation" form:
- the "Form: Email subject" string appears twice and it's the 2nd one that seems to come from nowhere
- the "Form: Required message" string is missing

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for the translations, Elementor has nothing to with them nor do we have control over them, please direct this to your translations plugin developers.

thanks.

**Comment by FlyThePlanet** [comment]
"As for the translations, Elementor has nothing to with them nor do we have control over them, please direct this to your translations plugin developers."

Again a very disappointing answer.
I doubt you're right. It's most probably linked to the coding of the Elementor Form widget if the "Form: Email subject" string is displayed twice and the "Form: Required message" string missing.
For the 1st case there must be a piece of code around this string obsolete and not deleted yet and for the 2nd one it must be hard coded by mistake so WPML can't detect the string.
