### ISSUE TITLE
Popup Menue and Anchor Navigation Links Problem Need Help!

### ISSUE THREAD

**Issue by AngelzGFX** [elementor/elementor#7408]
Heya

i was testing the new popup feature and i notice a big Problem Maybe u can help me to solve this issue…
i rebuild a menue for mobile if i click on a button the menue open in full screen at the Moment i use a onepage Setup this means my page only have one site and all links are anchor links scroll to id section if i click in the menue a anchor link like #contact in the Background my Content is Scrolling down but the menue dont close from self is there any trick to trigger this that the menue close from self or any Java script? I really Need it soon as possible for a Client Website

**Comment by shilo-ey** [comment]
I merged this issue with  #7085 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
