### ISSUE TITLE
Animated headline is being cut off for some users, so it only shows some of the words rotating

### ISSUE THREAD

**Issue by AndyLQ** [elementor/elementor#7409]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

I have the animated headline widget on my landingpage, and have received many notices that it is being cut off.
I have 3 rotating words and the 2 longest ones are cut off; see video on the link;
https://youtu.be/Xh9iv4hW2dk

## Steps to reproduce

I cant seem to find out how to make this happen, but it happens mostly on mobile. I reproduced it using the Google Chrome browser on my phone.

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
     X - Not sure, i am using the ASTRA theme 1.7.1

- [  ] I can reproduce this bug consistently using the steps above.

## Environment 

WP 5.1
Astra 1.7.1
Elementor 2.5.3
Elementor Pro 2.4.7

**Comment by shilo-ey** [comment]
@AndyLQ 

I Can't understand what you are experiencing without any steps to reproduce, Isolation of the problem and full environment details (including the page with your issue)

Please fill it in.

**Comment by AndyLQ** [comment]
Sorry it was in comment brackets

**Comment by shilo-ey** [comment]
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Link to your website for inspecting? We cannot ask for any second detail.

Without it we simply can't help.

Thanks.

**Comment by AndyLQ** [comment]
@shilo-ey dev.digitalguest.com
What do you need to help me?
As a pro user this is very frustrating to deal with and seems unprofessional to my users and future customers

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues are not for support!

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by AndyLQ** [comment]
But you are not even adressing the bug, which is clearly a bug for one of ur features.
plus you are adressing it at "Without it we simply can't help."

**Comment by AndyLQ** [comment]
my company email is:
christian@digitalguest.dk

**Comment by shilo-ey** [comment]
@AndyLQ 

I Can't reproduce any bug without information you need to provide.

If it's a specific bug caused by one of your plugins or themes you need to isolate the problem before opening two tickets.

If you would like some premium support - Please contact our support, which you are entitled to as a Pro member.

Thanks.

**Comment by dallasisthedog** [comment]
I'd like to add that I've experienced the same issue with the Animated Headline widget (last bit of headline is cut off). I see the issue only on mobile on my end. Similar to the OP's example (https://youtu.be/Xh9iv4hW2dk).

**Comment by viveknath322** [comment]
Hey, did you found the solution? I'm also facing the same issue.

**Comment by dallasisthedog** [comment]
> Hey, did you found the solution? I'm also facing the same issue.

Since my headline is only 2 words, I ended up using a 2-column section to split it up: 
https://www.legalshempflower.com/
"Experience" is in one column, and the animated headline "whenever/wherever" is in the other column. That was the best I could do to 'fix' the issue. Hope that helps anyone out there :)

**Comment by enes993** [comment]
> Hey, did you found the solution? I'm also facing the same issue.
I had the same issue
You should to put **Width : 100%;** in the tag or class of the text in CSS !! , its worked for me !!
