### ISSUE TITLE
Image box Issue the .svg images set in the image frame are no longer displayed

### ISSUE THREAD

**Issue by Lorenzoup** [elementor/elementor#7411]
After the update the inline objects didn't show correctly. I make update on every single page but when I import template on new page the svg icons are no longer displayed.
Even if the elementor panel is displayed in the image panel.

![BEFORE](https://user-images.githubusercontent.com/48300157/54111659-b6345c00-43e4-11e9-9e95-06e3f6fb189b.jpg)
![AFTER](https://user-images.githubusercontent.com/48300157/54111667-b92f4c80-43e4-11e9-91c2-04f18cae464c.jpg)
![AFTER2](https://user-images.githubusercontent.com/48300157/54111669-baf91000-43e4-11e9-8d29-16b0ffe269a6.jpg)

**Comment by m-kaddatz** [comment]
Any fixes to that issue? We have exact the same one.
