### ISSUE TITLE
Single Post Template Rendering bug on frontend

### ISSUE THREAD

**Issue by descifixer16** [elementor/elementor#7413]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description
Hi, I have an issue with my single post template editor vs. frontend view, but first of all this are my configurations so you can replicate my issue:

![image](https://user-images.githubusercontent.com/10729422/54121173-b5c3b180-4434-11e9-9c39-e8ff74c8dfb5.png)

a **_twentyseventeen child-theme_** with only this **functions.php**:

```PHP
<?php  

	function child_theme_enqueue_styles() {
	    wp_enqueue_style( 'parent-styles', get_template_directory_uri() . '/style.css' );
	    wp_enqueue_style( 'child-styles',  get_stylesheet_directory_uri() . '/style.css', array( 'parent-styles' ) );
	}
	add_action( 'wp_enqueue_scripts', 'child_theme_enqueue_styles' );
	
    // Remove jquery migrate on console
    add_action( 'wp_default_scripts', function( $scripts ) {
        if ( ! empty( $scripts->registered['jquery'] ) ) {
            $scripts->registered['jquery']->deps = array_diff( $scripts->registered['jquery']->deps, array( 'jquery-migrate' ) );
        }
    });
    
    // remove query string issue on pagespeed test
    function rm_query_string( $src ){   
        $parts = explode( '?ver', $src );
        return $parts[0];
    }
    
    if ( !is_admin() ) {
        add_filter( 'script_loader_src', 'rm_query_string', 15, 1 );
        add_filter( 'style_loader_src', 'rm_query_string', 15, 1 );
    }

?>
```

**header.php** :

```PHP
<?php
/**
 * The header for our theme
 *
 * This is the template that displays all of the <head> section and everything up until <div id="content">
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Twenty_Seventeen
 * @since 1.0
 * @version 1.0
 */

?><!DOCTYPE html>
<html <?php language_attributes(); ?> class="no-js no-svg">
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">

<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<div id="page" class="site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'twentyseventeen' ); ?></a>
	<?php if ( function_exists( 'hfe_header_enabled' ) && true == hfe_header_enabled() ): ?>
		
	<?php else: ?>

		<header id="masthead" class="site-header" role="banner">

			<?php get_template_part( 'template-parts/header/header', 'image' ); ?>

			<?php if ( has_nav_menu( 'top' ) ) : ?>
				<div class="navigation-top">
					<div class="wrap">
						<?php get_template_part( 'template-parts/navigation/navigation', 'top' ); ?>
					</div><!-- .wrap -->
				</div><!-- .navigation-top -->
			<?php endif; ?>

		</header><!-- #masthead -->
		
	<?php endif; ?>

	<?php

	/*
	 * If a regular post or page, and not the front page, show the featured image.
	 * Using get_queried_object_id() here since the $post global may not be set before a call to the_post().
	 */
	if ( ( is_single() || ( is_page() && ! twentyseventeen_is_frontpage() ) ) && has_post_thumbnail( get_queried_object_id() ) && ! ( function_exists( 'hfe_header_enabled' ) && true == hfe_header_enabled() ) ) :
		echo '<div class="single-featured-image-header">';
		echo get_the_post_thumbnail( get_queried_object_id(), 'twentyseventeen-featured-image' );
		echo '</div><!-- .single-featured-image-header -->';
	else:
		echo hfe_render_header();
	endif;
	?>

	<div class="site-content-contain">
		<div id="content" class="site-content">
```

**footer.php**:

```PHP
<?php
/**
 * The template for displaying the footer
 *
 * Contains the closing of the #content div and all content after.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Twenty_Seventeen
 * @since 1.0
 * @version 1.2
 */

?>

		</div><!-- #content -->

		<?php if ( function_exists( 'hfe_footer_enabled' ) && true == hfe_footer_enabled() ): ?>
			<?php echo hfe_render_footer(); ?>
		<?php else: ?>

			<footer id="colophon" class="site-footer" role="contentinfo">
				<div class="wrap">
					<?php
					get_template_part( 'template-parts/footer/footer', 'widgets' );

					if ( has_nav_menu( 'social' ) ) : ?>
						<nav class="social-navigation" role="navigation" aria-label="<?php esc_attr_e( 'Footer Social Links Menu', 'twentyseventeen' ); ?>">
							<?php
								wp_nav_menu( array(
									'theme_location' => 'social',
									'menu_class'     => 'social-links-menu',
									'depth'          => 1,
									'link_before'    => '<span class="screen-reader-text">',
									'link_after'     => '</span>' . twentyseventeen_get_svg( array( 'icon' => 'chain' ) ),
								) );
							?>
						</nav><!-- .social-navigation -->
					<?php endif;

					get_template_part( 'template-parts/footer/site', 'info' );
					?>
				</div><!-- .wrap -->
			</footer><!-- #colophon -->

		<?php endif; ?>
		
	</div><!-- .site-content-contain -->
</div><!-- #page -->
<?php wp_footer(); ?>

</body>
</html>
```

**style.css:**

```CSS
/*
	Theme Name: **** any name ***
	Description:  *** any description ***
	Author: *** any author ***
	Version: 1.0.0
	Template: twentyseventeen
*/

.elementor-widget-container div.js-marquee{
	vertical-align: middle;
}

.elementor-widget-container div.js-marquee>a{
	color: #fff;
}

.elementor-nav-menu .current_page_item > a,
.elementor-nav-menu .current_page_item > a:hover{
	background-color: transparent;
}

.site-content{
	padding-top: 0;
	padding-bottom: 0;
}

                    /* News events pagination */

.prev.page-numbers, .next.page-numbers{
    background-color: transparent;
}
```

**template-parts/post/content.php:**

```PHP
<?php
/**
 * Template part for displaying posts
 *
 * @link https://codex.wordpress.org/Template_Hierarchy
 *
 * @package WordPress
 * @subpackage Twenty_Seventeen
 * @since 1.0
 * @version 1.2
 */

?>

<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>

	<header class="entry-header">
		<?php
		    twentyseventeen_posted_on();
    	    the_title( '<h1 class="entry-title">', '</h1>' );
		?>
	</header><!-- .entry-header -->
	
	<div class="post-thumbnail">
		<a href="<?php the_permalink(); ?>">
			<?php the_post_thumbnail( 'twentyseventeen-featured-image' ); ?>
		</a>
	</div><!-- .post-thumbnail -->

</article><!-- #post-## -->
```

and that's all there is to it.
Now my issue is that on my elementor **single post template:**

![single-post](https://user-images.githubusercontent.com/10729422/54120409-9592f300-4432-11e9-98ed-c390b9f27985.png)

**post-excerpt** on the left and **featured-image** on the right and :

![image](https://user-images.githubusercontent.com/10729422/54121252-f6232f80-4434-11e9-9090-7f6debf27d44.png)

**post-content** at the bottom that looks like this on editor:

![image](https://user-images.githubusercontent.com/10729422/54121283-0804d280-4435-11e9-9dc2-676aee134062.png)

..that looks absolutely like a clone of the actual post using a **media carousel widget**:

![image](https://user-images.githubusercontent.com/10729422/54121482-81042a00-4435-11e9-98bf-fce1e61e5e2f.png)

... but on the actual **frontend**, it looks like this:

**post-excerpt** on the left and **featured-image** on the right are missing and:

![image](https://user-images.githubusercontent.com/10729422/54121740-3505b500-4436-11e9-920a-885b9003c8c7.png)

**media carousel widget** looks like this:

**all other images are missing**

![image](https://user-images.githubusercontent.com/10729422/54121922-a0e81d80-4436-11e9-886f-39a4eb0ad953.png)

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win64) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received)

== WordPress Environment ==
	Version: 5.1
	Site URL: https://localhost/pcem.ph
	Home URL: http://localhost/pcem.ph
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 8
	Debug Mode: Inactive

== Theme ==
	Name: PCEM
	Version: 1.0.0
	Author: rpafurong@gmail.com
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 2.1
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.7
		Author: Elementor.com

	Header, Footer & Blocks for Elementor
		Version: 1.1.2
		Author: Brainstorm Force, Nikhil Chavan

	Horizontal scrolling announcements
		Version: 1.2
		Author: Gopi Ramasamy

== Log ==
	: 
Log: showing 3 of 32019-03-11 17:55:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-03-11 17:55:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.4',
)]
2019-03-11 17:56:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.2.4',
  'to' => '2.4.7',
)]

PHP: showing 2 of 2PHP: 2019-03-11 17:55:25 [warning X 1][C:\xampp\htdocs\pcem.ph\wp-content\plugins\elementor-addon-widgets\vendor\codeinwp\themeisle-sdk\class-themeisle-sdk-widget-dashboard-blog.php::376] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-11 17:59:32 [warning X 1][C:\xampp\htdocs\pcem.ph\wp-content\plugins\elementor\modules\safe-mode\module.php::107] rmdir(C:\xampp\htdocs\pcem.ph/wp-content/mu-plugins): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

</details>

**Comment by shilo-ey** [comment]
Hi @descifixer16 

Thanks for your detailed info.
We can't replicate your issue.

Please try:
- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

If it does, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.

**Comment by descifixer16** [comment]
Hi @shilo-ey 

I was about to close this today 'coz I just found out that it was just some,, database cache? I believe,, 'coz I just recreated the section then that resolved my issue.

Thanks for your immediate reply thou @shilo-ey.

**Comment by shilo-ey** [comment]
Great, I'm glad you've managed to figure it out!

Best regards
