### ISSUE TITLE
AJAX Add to Cart button for Woocommerce Product Pages in Elementor

### ISSUE THREAD

**Issue by cFonzy** [elementor/elementor#7415]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Having to reload the page and scroll down to find where you where each time you click add to cart is becoming a hassle for customers.  This happens when you use the elementor woocommerce product page widget.

**Describe the solution you'd like**
Make single product pages AJAX enabled or create an option to enable it.

**Describe alternatives you've considered**
3rd party plugins dont seem to work

**Additional context**
Would like the button to work just like the built-in functionality that WooCommerce offers for AJAX on archive pages.  When you click the add to cart button a check mark appears on the button to confirm the product was added to cart.  Also a link "view cart" appears.

**Comment by bainternet** [comment]
@cFonzy 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it, and if WooCommerce will implement this we will try to support it.

For now, I can only suggest one of a 3rd party plugin or custom code.

Thanks for the feedback.

**Comment by erwinfrancis** [comment]
Just encountered this issue and I'm pulling my hair. Please add this functionality.

**Comment by espermedia** [comment]
Ditto - frustrating that you can enable Ajax add to cart in other areas, but not in the Elementor Add to Cart module (have tried multiple third-party add-ons as well). This causes the user to be taken to the Product Details page after they click Add to Cart rather than leaving them on the current page.

**Comment by fattusmaximus** [comment]
Disappointing response.

You have widgets for related products, upsells and archive pages with ajax buttons. Then you leave it off of the product page itself.

**Comment by jazir5** [comment]
Please add this, every additional extra loading causes customer drop-off, this is proven through multitudes of research into online conversion rates. 

https://blog.hubspot.com/marketing/page-load-time-conversion-rates

https://neilpatel.com/blog/loading-time/

https://www.portent.com/blog/analytics/research-site-speed-hurting-everyones-revenue.htm

Every additional page load means lost sales. You'll increase the amount of revenue, sales and conversions generated by every e-commerce store built with elementor by adding this feature.

**Comment by mangomaniax** [comment]
Is an AJAX add-to-cart-button planned? That would be so cool!

**Comment by Felipe-NS** [comment]
up

**Comment by zohar** [comment]
> @cFonzy
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it, and if WooCommerce will implement this we will try to support it.
> 
> For now, I can only suggest one of a 3rd party plugin or custom code.
> 
> Thanks for the feedback.

@bainternet can you please suggest any 3rd party plugin or custom code until this feature is added?
Not having an ajax option in single product is a real barrier for using Elementor with woocommerce...

**Comment by jazir5** [comment]
You can use Briefcase for Elementor or Powerpack, The Plus, really the
majority of add-on packs that have Woocommerce support have Ajax add to
cart widgets

**Comment by hrzip** [comment]
I too struglled with this but managed to find working solution. There are many plugins but I finally managed to find working one. Just install this and everything will work flawlessy with elementor: https://wordpress.org/plugins/woo-ajax-add-to-cart/

**Comment by hrzip** [comment]
And yes, plugin is completely free :)

**Comment by hrzip** [comment]
My advice is to install "add to cart pop-up" plugin t,oo so customer can more easily follow payment path.

**Comment by acal** [comment]
> I too struglled with this but managed to find working solution. There are many plugins for this that for some reason doesn't work with elementor but I finally managed to find working one. Just install this and everything will work flawlessy with elementor: https://wordpress.org/plugins/woo-ajax-add-to-cart/

Unfortunately, I have not been able to make this specific plugin to work (July 30, 2020).

**Comment by desis123** [comment]
Please include this feature.

**Comment by chitiore** [comment]
Please too

**Comment by numanagit** [comment]
So, the answer is always the same: "we will look into it in the future if we see a large demand for it". **Translated: we have no desire to implement it**. They don't know ajax... All of their widgets are so outdated with its reloading page funcitonalities. But now we have global colors and typography, ohh... You can't even select background images sizes yet, a Wordpress core functionality. Forgot they will add ajax to their widgets. Get some globals colors and use third party plugins.

Unfortunately what is always happening with successful plugins, they believe they are invincible... until another product appears.

**Comment by visualtribe** [comment]
So I have looked at this and it doesn't make any logical sense. You made a button that says add to cart, but it passes back to the product page, and ignore the internal Ajax system in Woocommerce if turned on, which mine is. The class for this plugin ajax call and the class for the Elementor button is the same, so there isn't any reason that this button wouldn't ajax properly. I have tried this plugin and it doesn't work. 

The only reason this would fail is if Elementor coders built in a force to single product page stopping both the functioning of this plugin and the functioning of Woocommerce Ajax option. This is both blantanly stupid and incompetent, stopping Woocommerce built in ajax to fail. Stop being idiots and fix this ASAP!!!!!!!!! Take your heads, rub them together and make some fire and solve this.

**Comment by mina998** [comment]
Hope to support this feature

**Comment by michaelCcity** [comment]
Okay, i found a solution problem to it,
programmatically:
https://aceplugins.com/ajax-add-to-cart-button-on-the-product-page-woocommerce/?unapproved=13338&moderation-hash=c907f2c132095d7505def57704196edf

**Comment by rems035** [comment]
please add this feature

**Comment by ishnechmad** [comment]
I'm also looking for it. A lot of my clients have requested this feature.

**Comment by morosmo** [comment]
+1

**Comment by gameDNAstudio** [comment]
+1

**Comment by hax1** [comment]
+1

**Comment by jaysonwebtel** [comment]
+1

**Comment by Goodmasterops** [comment]
UP!

**Comment by mateitudor** [comment]
The Elementor strategy:

Good functionality: 😒
Some AI feature hype that nobody uses: 😏

**Comment by hoodvisions** [comment]
+1

**Comment by arekuki** [comment]
+1

**Comment by dalir-sys** [comment]
+1

**Comment by kingsuhaib** [comment]
For God's sake make it already. This is so frustrating.

**Comment by BrockwayProd** [comment]
> For God's sake make it already. This is so frustrating.

i think they dont consider such no brainer imrpovement unless it's been 5 years that the users complain about it.
Hell, it took them 6 month to fix a bug with caching when using their minicart element.
The bug was totally messing up the order process for many people, it was critical tier, but still they waited 6 month to deploy an easy fix.
Dont get your hopes too high, best thing to do is to look et better builder.

**Comment by kingsuhaib** [comment]
> > For God's sake make it already. This is so frustrating.
> 
> i think they dont consider such no brainer imrpovement unless it's been 5 years that the users complain about it. Hell, it took them 6 month to fix a bug with caching when using their minicart element. The bug was totally messing up the order process for many people, it was critical tier, but still they waited 6 month to deploy an easy fix. Dont get your hopes too high, best thing to do is to look et better builder.

Yeah buddy seems like it. I worked my way around it somehow using like 5 different php and js code snippets as well as a plugin. Works good enough for now.

**Comment by jimon07** [comment]
This problem still exists as of 2024.. Will this ever be fixed?

**Comment by mateitudor** [comment]
they will look into it if "there's a large demand"

**Comment by gameDNAstudio** [comment]
I would recommend you guys to switch to better page builder because seems like Elementor doesn't care about this and other issues. I switched to Kadence and they have implemented AJAX Add to Cart button and it works amazing.

**Comment by arnasofc** [comment]
still have this issue. +1

**Comment by thijmenvdijk** [comment]
After 6 years it seems like its logical to add such feature... I made a poem about it.

Oh, Elementor, sleek and bright,
A builder's dream, a coder's plight.
With blocks and widgets, swift and true,
Yet one key feature's overdue.

For six long years, the voices cried,
"An AJAX cart, let it ride!"
A simple click, no page reload,
Yet still, we walk the long, old road.

The devs have spoken, users plead,
A smoother flow is what we need.
Yet every update comes and goes,
But AJAX stays in phantom throes.

Merchants sigh, their patience thin,
A cart refresh? A mortal sin!
Competitors do it, swift and keen,
Yet Elementor stays unseen.

Is it pride, or sheer neglect?
Or features lost in some defect?
The forum echoes, tickets stack,
Yet still, we lack... we lack... we lack.

So here we stand, no change in sight,
Installing plugins, patching blight.
Oh, Elementor, hear our song—
AJAX shouldn't take this long!

**Comment by mateitudor** [comment]
Would you like some AI?
Us, not a single aye
  Anyway we'll concentrate on AI
But the bugs make us want to die
  Hosting, marketing, more AI!
Even if, I wouldn't trust "israel" with AI
  New: site planner, with AI!

**Comment by mikkelaveo** [comment]
+1

**Comment by Goodmasterops** [comment]
+1
