### ISSUE TITLE
Divider Functionality

### ISSUE THREAD

**Issue by krann** [elementor/elementor#7418]
I would like to create text divider lines varying from Space Age to Dickensian to suit the content being presented.

However, the 'Divider' Widget offers only three choices of horizontal line - 'solid, double, dotted & dashed'

Why can't it offer a 'Divider Designer' similar to the Section's 'Shape Divider' facility, which offers waves and curves and zig-zags that can be sculpted with a variety of sliders?

Could this be done?

**Comment by shilo-ey** [comment]
Those options origins from the CSS options that border property has.

Currently, we do not support this feature, but you can use "Inline" positioning + separator image.

Thanks.
