### ISSUE TITLE
create sidebar

### ISSUE THREAD

**Issue by lwoods** [elementor/elementor#7421]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lwoods** [comment]
Add a simple "Create Sidebar", possibly to the Sidebar element.  All of the 3rd-party plugins that I have found that create sidebars also require you to specify the page(s) where the sidebar will be used.  This duplicates what Elementor already asks for when you drag in the Sidebar element.  I am concerned that this duplication between a 3rd-party plugin and Elementor will cause problems.

**Comment by shilo-ey** [comment]
Hi @lwoods 

The Sidebar widget in Elementor lets you embed an existing sidebar you have already created in your WordPress website.

Saying that we provide a more advanced toolset for creating a sidebar with Elementor. 

Therefore, we currently don't see the value of adding this feature.

Thanks!

**Comment by lwoods** [comment]
So you are saying that the Elementor "Add Sidebar" widget will not conflict with the many "Create Sidebar" plugins that are available that also perform the "Add Sidebar" function???
