### ISSUE TITLE
Add a featured file element that works like featured image.

### ISSUE THREAD

**Issue by kwerondaa** [elementor/elementor#7422]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**
Can we have another custom field called 'featured file' that works the same as featured image.  I am building a website that has alot of files that we want our site visitors to be able to download, however, I was looking for a 'download file' element from the elementor elements section but I can't find any.
I have built a files template and I'm using to generate hundreds of similar pages. On that template I have a button called 'Download file' and I want to dynamically link it to each page's file. Here is one of the pages(that link is self linking because I couldnt find a way to dynamically link to the corresponding file: http://africhild.kweronda.online/afri/downloads/investing-in-ugandan-children-a-response-to-ugandas-national-development-plan-ii/

**Describe alternatives you've considered**
I am cuurently using a plugin called advanced custom fields but I am failing to dynamically add the file url to the download button.
**Additional context**
The image I have attached is from a third party plugin but it's not a free plugin. But the picture shows what the feature I am talking about looks like.
[FireShot Capture 060 - Download Button - JetElements - Addon for Page Builder Elementor_ - jetelements.zemez.io.pdf](https://github.com/elementor/elementor/files/2954120/FireShot.Capture.060.-.Download.Button.-.JetElements.-.Addon.for.Page.Builder.Elementor_.-.jetelements.zemez.io.pdf)

**Comment by shilo-ey** [comment]
Hi @kwerondaa 

This is not related to Elementor, but to Wordpress in general.

Simply add a custom file field, and use elementor [Dynamic Tags](https://docs.elementor.com/article/556-dynamic-tags) to enable the link to it.

Thanks.
