### ISSUE TITLE
Custom CSS text editor is broken after update

### ISSUE THREAD

**Issue by JoeDarko** [elementor/elementor#7423]
After updating to the newest version i'm unable to use the custom CSS text editor, because there is a really strange bug, that makes editing impossible.

In some cases, the editor somehow ignores the last letter. So when you type, everything is being typed before the last letter. And when you try to delete the last letter using the backspace button it's deleting the letters before the last letter but never the last letter itself. 

It doesn't happen straight away, you have to type in a little bit of code. I can't quite say when exactly it starts happening, but it's happening very often, so just try to play with some code for a minute and you will see it.

It's imposibble to explain with words so i captured the problem on video:

https://photos.app.goo.gl/6vuFULmAq5DQe5Tp6

(It's me mostly just hitting the backspace button.)

Please fix this quickly, right now the custom css editor is pretty much unusable.

**Comment by shilo-ey** [comment]
Hi @JoeDarko 

We can't replicate this issue.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
