### ISSUE TITLE
Hide form after submission

### ISSUE THREAD

**Issue by vind** [elementor/elementor#7424]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.*
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
From a designer's perspective, I would prefer that input forms could be configured to automatically hide after user submission, and then display a custom text message. I believe this is a fairly common behaviour on the web when dealing with input forms, which helps to prevent spam submissions, while clearly communicating to the user that the form has been sent.

*While I did find two closed tickets that previously addressed this request, the answers that were given in both requires knowledge of PHP and JQuery, implying code work outside of Elementor itself. This also exceeds my personal ability to get any further with the matter.

**Describe the solution you'd like**
I think a tag in the Actions After Submit list and a corresponding tab for the option to hide a form and display a custom message would be the most convenient solution. A custom message could be optional, with the option to give it a class or ID for customisation in the Custom CSS field for the form widget.

**Describe alternatives you've considered**
I attempted to apply the code-specific answers given in the other two threads, however without any success, as I'm not knowledgeable with either PHP or JQuery.

**Comment by shilo-ey** [comment]
Hi @vind 

Thanks for your feedback.

Currently this feature is not supported out of the box, and you will have to use our Forms API.
You can look in #7249 which answers your question.
Simply add the first code to your theme's `functions.php` file.

Thanks.

**Comment by walidbousseta** [comment]
just go to the **Additional Options** and activate the **Custom Messages**, there you can just delete the message 
![Capture](https://user-images.githubusercontent.com/34287356/134771606-aa1f8cc0-94c0-414a-8ff9-de04d671822f.PNG)

**Comment by Nodws** [comment]
5 years later and we have cheap AI gimmicks but no real solutions.
on the success message you can add this css code after your message `<style>.elementor-form-fields-wrapper{display:none!important}</style>`
