### ISSUE TITLE
What is the class for an entire Elementor Built Page without the header included so we can Push our page wrapper to the left using a Hamburger Menu Plugin

### ISSUE THREAD

**Issue by smile00000** [elementor/elementor#7425]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

What is the class for an entire Elementor Built Page without the header included?
Elementor Email Support told us to ask the question here as they had no idea.

When we use a plugin called Responsive Menu Pro https://responsive.menu/, we have it so when you click the hamburger it pushes the entire page to the right. We want to push the whole page except the header as the hamburger/header moves with it and it looks weird.

Please advise what the class would be for an Elementor page discluding the header.

Right now in the Responsive Menu Pro plugin settings in wp-admin > responsive menu pro we have entered the following code for the Push Wrapper:: ".elementor-page"

Details about this field:
"Push Wrapper
The CSS selector(s) of your page that you want pushed when using the push animation above.
For example #page-wrapper, #wrapper"

Responsive Menu Pro support told us that Elementor needs to advise the class for a whole page without the header in order for this to work. As mentioned above, Elementor Support told us to write this in Github.

Our Site:
https://bit.ly/2JyZzaK

## Steps to reproduce
N/A What is the class?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

This isn't an environment issue. Just a question about class and headers. But we are using the latest version of Wordpress, Elementor Pro and Elementor, with Storefront theme.

**Comment by shilo-ey** [comment]
Hi @smile00000 

There isn't any general selector for the content area, because each theme creates its own classes and rules.

you can use `.elementor[data-elementor-type="post"]` to target your content without the header, but please note that in your website you are embedding the header inside the page and not through the theme builder (with conditions)

Thanks.

**Comment by smile00000** [comment]
@shilo-ey that actually pushed too much, even the hamburger. I shared what you wrote with the plugin developer and they told me to simply put ".elementor-1342" instead and it worked for anyone else who needs it!

**Comment by shilo-ey** [comment]
@smile00000 

.elementor-1342 is your section id. if you will create a different page it will be changed, therefore I didn't give you that class.

I'm glad you managed to work it out. I recommend you to take a good look at your entire site.

Thanks

**Comment by sermalefico** [comment]
And whats is the class in Hello theme? or how to add a class to hello theme to push content?
the data type dont works for me

thx
