### ISSUE TITLE
Product Inquiry Form

### ISSUE THREAD

**Issue by Manning404** [elementor/elementor#7426]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
_I would like to add a product inquiry form to a single product in woocommerce._

**Describe the solution you'd like**
_I would like to add the product inquiry form which automatically adds the product name to the email subject line_

**Describe alternatives you've considered**
_I have considered another 3 party plug in, but not sure if any will work with Elementor_

**Additional context**

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
