### ISSUE TITLE
Save Style as Global

### ISSUE THREAD

**Issue by mateuszkania** [elementor/elementor#7432]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like to save as global only "Style" tab. 

**Describe the solution you'd like**
For example, I would like to define button and then I want to use it on many pages and in many situations and change href for everyone and having them connected wants to change the background color for all at once. Now it is not possible because if I want to change something I must unlink it.

I often create a website for customers where the whole typography and global elements are and I would like to be able to change the global styles of these elements without interfering with the content

**Comment by Lorenzoup** [comment]
We have been requesting this function for over 2 and a half years but we have never been listened to unfortunately 😢

**Comment by drawcard** [comment]
#965 for more info @mateuszkania

**Comment by shilo-ey** [comment]
I merged this issue with  #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by tristanleboss** [comment]
@shilo-ey

> we could deal with it more efficiently

#965  is 2.5 years old..
