### ISSUE TITLE
Inline auto option not working 2.5.5

### ISSUE THREAD

**Issue by slatemates** [elementor/elementor#7433]
Inline auto option works only after updating even on new pages created with 2.5.5

**Comment by reardestani** [comment]
Same issue here

**Comment by jnicotra** [comment]
I have the same issue as well.

**Comment by miguel-cravidao** [comment]
Same here

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will update here when it's fixed.

Thanks.

**Comment by MPHood** [comment]
Same here

**Comment by tollube** [comment]
Same issue here...

**Comment by shilo-ey** [comment]
This issue has been fixed in 2.5.6

Feel free to update!

**Comment by slatemates** [comment]
Thanks , now working .

**Comment by scott8035** [comment]
This is still an ongoing issue...I'm using E 2.5.8, and when I apply Inline (auto) to three stacked heading widgets, they do not budge, so I had to add selector `{ display: inline-block; }` to Custom CSS to make it work.

**Comment by pingram3541** [comment]
Please check issue 7671 (https://github.com/elementor/elementor/issues/7671)
