### ISSUE TITLE
Popup opens first time on page click instead on button click

### ISSUE THREAD

**Issue by nemanjasipka** [elementor/elementor#7434]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by nemanjasipka** [comment]
Popup opens first time on page click instead on button click. Then after that it opens normally. You can check it here.
https://successive.no/landing-page

**Comment by shilo-ey** [comment]
Can't reproduce. works fine.

Try viewing it with incognito mode. it might be your browsers caching.
