### ISSUE TITLE
Menu Item Active when in View Pane

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#7435]
On a "single page site" or with 'in-page' navigation all ID sections (#thisIsASection) that are included in the menu as Custom Links are shown as active. So on a single page with five sections in the menu all would be shown as active. This can be overcome by using the "Page scroll to ID plugin" but this is far from intuitive to implement.

 It would be great to have an option within the Elementor menu widget for menu items to be flagged to be "Only Active In the View Frame". Then on a single page site, the active menu section would only be highlighted when it was in the view pane particularly important if a sticky menu is used.

**Comment by shilo-ey** [comment]
Hi @nickdgreen 

This is the default behavior, as you can see in the [following screen recording](https://www.useloom.com/share/061557ef59eb48e987f3ee1a35f46e22).

Please make sure you are adding the id in the menu item link field:

![image](https://user-images.githubusercontent.com/45009641/54267365-c5044580-4581-11e9-8ed1-8b006a8cd076.png)

**Comment by nickdgreen** [comment]
Did you actually read the post? I know how to navigate to sections on a page. This is about the menu showing any sections on the same page as active in the menu. You have to use a plugin to only show the section in the view pane as active. Would you please reopen this as you have not answered the request at all.

**Comment by shilo-ey** [comment]
Hi @nickdgreen 

Actually, I have read your issue and gave it plenty of attention. I've also tried to reproduce it. I gave you screenshots and video capture of the behavior of Elementor, without any other plugins. Therefore this is not an issue, and if you're struggling with creating this kind of behavior - please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

Thanks
