### ISSUE TITLE
Elementor Document Settings extension example not working

### ISSUE THREAD

**Issue by Paras16699** [elementor/elementor#7438]
Description
----------

I am trying to extend the Elementor document settings in my theme by adding one of my own controls, so, to try, I copy-pasted the example code from here https://developers.elementor.com/elementor-document-settings/#Adding_a_new_settings to the `functions.php` file of my theme.

But apparently, it isn't showing the Color control in the Document Style settings which it's supposed to do. (I am checking it in the post edit page which has Elementor active)

Am I missing something here?

While trying to debug, I put a sample string to dump in the function that the action `elementor/element/page-settings/section_page_style/before_section_end` executes, but it isn't showing that string as well.

Btw, I've made sure that this action is added after Elementor gets loaded so that isn't the issue. Several other Elementor actions are executing fine before this one.

So, it seems like the action isn't executing. Is it an inexistent action?

**Comment by Paras16699** [comment]
Bump. Can someone check and confirm this please?

**Comment by mrcliffbailey** [comment]
@Paras16699 Based on this comment (https://github.com/elementor/elementor/issues/3928#issuecomment-376812639) it appears that the hook name has changed from `elementor/element/page-settings/section_page_style/before_section_end` to `elementor/element/post/document_settings/after_section_start`.

**Comment by Paras16699** [comment]
@mrcliffbailey Thanks a lot. 

Their documentation isn't updated to reflect this change which might misguide other people as well. 

@bainternet, @shilo-ey it would be nice if you can forward this issue and get the documentation for the document settings updated.

**Comment by MehbubRashid** [comment]
Got misguided too

**Comment by SiteSpot** [comment]
me too. please update ya docs

**Comment by dbjpanda** [comment]
Not yet updated. :(
