### ISSUE TITLE
🔗 🚀 Feature Request: iPad support (phone/tablet) (Duplicate of #482)

### ISSUE THREAD

**Issue by quentintricoire** [elementor/elementor#7439]
I use elementor on computer but sometimes I use an iPad for more mobility. But elementor doesn't work correctly the sidebar with widget is perfect that just the interface rating site is not possible to scroll. I’m not a developer, I think is be possible on the next version no ? I can make test if you need. (sorry for my English)

**Comment by shilo-ey** [comment]
I merged this issue with  #482, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
