### ISSUE TITLE
Preview changes feature doesn't work for static Homepage

### ISSUE THREAD

**Issue by Lordblubb** [elementor/elementor#7440]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor provides a "Preview Changes" button to preview changes made in a page before pubhlishing it. When using this feature on the page defined as Homepage in Wordpress (->Settings->Reading: A static page: Homepage), the changes made are not shown in the preview browser window. This effect does not happen for other pages. On these pages, the preview browser window correctly shows the changes made.

## Steps to reproduce
- Create wordpress db.
- Copy wordpress folder to htdocs folder.
- Install web page.
- Run updates if provided by Wordpress backend
- Configure Wordpress backend:
  a) Perma links: post name
  b) Date format: d/m/Y
  c) Time format: H:i
- Create and publish 3 pages, e.g. start, contact and blog.
- Assign start and blog in the Wordpress backend under ->Settings->Reading: A static page.
- Delete all plug-ins; install elementor and activate it.
- Configure Elementor: Show editing handles.
- Edit start page ("Homepage") with elementor and preview changes -> no changes are shown in the preview window.
- Edit contact page with elementor and preview changes -> changes are shown correctly in the preview window.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Issue was found on local server (Xampp) and also hosted web page (1&1 Ionos).
Issue was found with Wordpress 4.9.9 and 5.1.
Issue was found with standard theme 2019 and Phlox Pro.
<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.3.1
	MySQL version: mariadb.org binary distribution v5.6.41-84.1
	PHP Version: 7.3.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://localhost/wp2
	Home URL: http://localhost/wp2
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.5
		Author: Elementor.com

== Log ==
	: 
		

</details>

**Comment by shilo-ey** [comment]
Hi @Lordblubb 

Thanks for reporting.

We will take a look and resolve this issue.

Thanks.

**Comment by Lordblubb** [comment]
Hi,

does this bug also occur in the PRO version?

Thanks.

**Comment by shilo-ey** [comment]
Hi @Lordblubb 

This issue has been fixed in Elementor v2.5.10 (CORE).

Feel free to update!

**Comment by CleopatraDeniz** [comment]
Hi @shilo-ey 
I have the same issue of @Lordblubb. 
I'm working with Elementor v2.5.16. The changes made to the page defined as newhome in Wordpress (->Settings->Reading: A static page: newhome) with Elementor and already saved, were perfectly working until my last revision yesterday. 
Today, without having made any other changes, the page layout that I can see in the Elementor editor are not shown in the preview browser window, nor elsewhere (incognito navigation page, mobile).
I just refreshed my homepage view and the homepage was gone, while still there in the Elementor editor.
I would very much appreciate your help :)
Thanks

**Comment by TranquilBS** [comment]
Hi, I am having this issue on the free and paid version...
