### ISSUE TITLE
Elements_Manager class needs categories setter method

### ISSUE THREAD

**Issue by Rowayda-Khayri** [elementor/elementor#7445]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

`'elementor/elements/categories_registered'` action in elements.php can't be used to modify categories as it's a private property. So, a set_categories() method is needed to be implemented in `class Elements_Manager`.

**Comment by bainternet** [comment]
@Rowayda-Khayri 	

What or why would you need to modify? whats the use case?

**Comment by Rowayda-Khayri** [comment]
@bainternet  I've defined custom categories and don't want all the other categories to be displayed in the panel.

**Comment by sf-steve** [comment]
You can easily use closure binding to get around this, we do so to put our custom widgets at the top:

```php
add_action( 'elementor/elements/categories_registered', function(\Elementor\Elements_Manager $elements_manager ) {

            //add our categories
            $category_prefix = 'aqb-';

            $elements_manager->add_category(
                $category_prefix . 'widgets',
                [
                    'title' => 'Blah Blah',
                    'icon' => 'fa fa-plug',
                ]
            );

            //hack into the private $categories member, and reorder it so our stuff is at the top

            $reorder_cats = function() use($category_prefix){
                uksort($this->categories, function($keyOne, $keyTwo) use($category_prefix){
                    if(substr($keyOne, 0, 4) == $category_prefix){
                        return -1;
                    }
                    if(substr($keyTwo, 0, 4) == $category_prefix){
                        return 1;
                    }
                    return 0;
                });

            };
            $reorder_cats->call($elements_manager);

        } );
```

**Comment by Rowayda-Khayri** [comment]
@sf-steve  I don't want to put my custom categories at the top keeping the other categories. I want my custom categories only to be displayed.

**Comment by sf-steve** [comment]
@Rowayda-Khayri yes, thats just an example of how we are using closure binding the edit a private property.

Within the closure `$this` refers the `Elements_Manager` instance, so you have full access to all private properties, to do whatever you want, such as setting categories:

```php
    add_action( 'elementor/elements/categories_registered', function(\Elementor\Elements_Manager $elements_manager ) {

             $custom_categories = ['rowayda-widgets', 'rowayda-somethingelse'];
             //use closure to gain access to private properties
            $set_categories = function( $categories ){
                //$this referes to whatever instance we bind later
               //in this case the $elements_manager instance
                $this->categories = $categories;
            };
            $set_categories->call($elements_manager, $custom_categories);

        } );
```

**Comment by bainternet** [comment]
@Rowayda-Khayri 	

thanks for the PR see https://github.com/elementor/elementor/pull/7447#issuecomment-502439895

**Comment by sayem-xs** [comment]
> You can easily use closure binding to get around this, we do so to put our custom widgets at the top:
> 
> ```
> add_action( 'elementor/elements/categories_registered', function(\Elementor\Elements_Manager $elements_manager ) {
> 
>             //add our categories
>             $category_prefix = 'aqb-';
> 
>             $elements_manager->add_category(
>                 $category_prefix . 'widgets',
>                 [
>                     'title' => 'Blah Blah',
>                     'icon' => 'fa fa-plug',
>                 ]
>             );
> 
>             //hack into the private $categories member, and reorder it so our stuff is at the top
> 
>             $reorder_cats = function() use($category_prefix){
>                 uksort($this->categories, function($keyOne, $keyTwo) use($category_prefix){
>                     if(substr($keyOne, 0, 4) == $category_prefix){
>                         return -1;
>                     }
>                     if(substr($keyTwo, 0, 4) == $category_prefix){
>                         return 1;
>                     }
>                     return 0;
>                 });
> 
>             };
>             $reorder_cats->call($elements_manager);
> 
>         } );
> ```

This solution is not working. Still it is loading after some category.

**Comment by Silbad** [comment]
Hello, I made this to put my category on top : 

`function add_elementor_widget_categories( $elements_manager ) {

	$categories = [];
	$categories['toto'] =
		[
			'title' => 'Toto',
			'icon'  => 'fa fa-plug'
		];

	$old_categories = $elements_manager->get_categories();
	$categories = array_merge($categories, $old_categories);

	$set_categories = function ( $categories ) {
		$this->categories = $categories;
	};

	$set_categories->call( $elements_manager, $categories );

}

add_action( 'elementor/elements/categories_registered', 'add_elementor_widget_categories') ;`

**Comment by mertafor** [comment]
> Hello, I made this to put my category on top :
> 
> ```
> function add_elementor_widget_categories( $elements_manager ) {
> 
> 	$categories = [];
> 	$categories['toto'] =
> 		[
> 			'title' => 'Toto',
> 			'icon'  => 'fa fa-plug'
> 		];
> 
> 	$old_categories = $elements_manager->get_categories();
> 	$categories = array_merge($categories, $old_categories);
> 
> 	$set_categories = function ( $categories ) {
> 		$this->categories = $categories;
> 	};
> 
> 	$set_categories->call( $elements_manager, $categories );
> 
> }
> 
> add_action( 'elementor/elements/categories_registered', 'add_elementor_widget_categories') ;
> ```

Thanks to @Silbad , I was able to add my custom category to the top. But if you prefer adding it to right after Basic section in order users to allow accessing basic widgets first, this works fine :  
`
                 $categories = [];

		$old_categories = $elements_manager->get_categories();

		if( is_array($old_categories) ) {
			foreach($old_categories as $k => $v) {
				$categories[$k] = $v;
				if($k=='basic') {
					$categories['elementor-mine'] = [
								'title' => 'My Category',
								'icon' => 'fa fa-plug',
							];
				}
			}
		}

		$set_categories = function ( $categories ) {
			$this->categories = $categories;
		};

		$set_categories->call( $elements_manager, $categories );
`
