### ISSUE TITLE
Need expected response format for webhook documented

### ISSUE THREAD

**Issue by jasenf** [elementor/elementor#7449]
Was told by Elementor support to post this here:

I have Elementor form posting a webhook to our system.  The webhook needs to respond sometimes with an error message that gets displayed to the end user.   I can't find any documentation that explicitly shows what to respond from an HTTP response perspective.  

Right now we are sending this back to Elementor but it doesn't deliver the message to the client.

HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 35
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Wed, 13 Mar 2019 12:28:24 GMT
Connection: close

"The username is already in use. "

**Comment by bainternet** [comment]
@jasenf 	

Elementor Pro Form webhook is a "Set and forget" webhook. 
catch the response of you webhook using the 
`elementor_pro/forms/webhooks/response` action hook which accepts two paramters:
```php
/**
 * @param \WP_Error|array $response The response or WP_Error on failure.
 * @param Form_Record     $record   An instance of the form record.
 */
```

but if you need to add/show a custom message based on the response of the webhook, you would need to implement a [custom webhook](https://developers.elementor.com/forms-api/#Form_New_Record_Action) and maybe even use the [validation hook](https://developers.elementor.com/forms-api/#Form_Validation_Action) to actually run your webhook and avoid submission if the data is not valid.


if you have a more specific question I'd be happy to help.
