### ISSUE TITLE
Elementor calling shortcodes multiple times

### ISSUE THREAD

**Issue by jpknz** [elementor/elementor#7452]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
Using Elementor to display a page that contains 21 buttons.  Each of the buttons calls a shortcode to get the button text and the URL it should go to.  When the page loads I would expect 42 calls to the shortcode (21 buttons x 2 requests per button) however I get 126 requests each time.

I created a new page with just one button that uses shortcodes to get the button text and url and in this instance it only calls the shortcode twice.  There is no difference (that I can tell) between the test button I created and the buttons on the pages that is calling multiple times.

The page with 21 buttons seems to call in the following order
button 1 - button text
button 1 - button url
button 1 - button text
button 1 - button url
button 2 - button text
button 2 - button url
button 2 - button text
button 2 - button url
repeat for 21 buttons then it continues to call as below
button 1 - button text
button 1 - button url
button 2 - button text
button 2 - button url
repeat for 21 buttons

What would cause one page to call it correctly while another calls each it multiple times?

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.23
	PHP Version: 7.0.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://***removed***.co.uk
	Home URL: https://***removed***.co.uk
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Customify
	Version: 0.2.8
	Author: WPCustomify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

	Font Awesome
		Version: 4.0.0-rc7
		Author: Font Awesome

	Pluginception
		Version: 1.3
		Author: Otto

	Query Monitor
		Version: 3.3.2
		Author: John Blackbourn

	Really Simple SSL
		Version: 3.1.5
		Author: Rogier Lankhorst, Mark Wolters

	stopAds WooCommerce Functions
		Version: 
		Author: 

	TablePress
		Version: 1.9.2
		Author: Tobias Bäthge

	Tabs - Responsive Tabs with  Accordions
		Version: 2.6
		Author: Biplob Adhikari

	Temporary Login Without Password
		Version: 1.5.15
		Author: StoreApps

	WooCommerce
		Version: 3.5.6
		Author: Automattic

	WooCommerce Blocks
		Version: 1.4.0
		Author: Automattic

	WooCommerce Services
		Version: 1.19.0
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.14
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.5.2
		Author: Prospress Inc.

	Woo Preview Emails
		Version: 1.5.0
		Author: Digamber Pradhan

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms

== Log ==
	: 
PHP: showing 2 of 2PHP: 2019-02-03 01:33:44 [notice X 2][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-08 10:18:20 [notice X 4][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/query-control/module.php::263] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 6 of 62019-02-12 18:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-12 18:56:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-02-23 15:00:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-23 15:00:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-03-12 11:13:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.5',
)]
2019-03-12 11:13:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.5',
  'to' => '2.4.8',
)]

JS: showing 1 of 1JS: 2019-02-17 11:36:30 [error X 3][https://***removed***.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.6:2:47187] undefined is not an object (evaluating \'t.element\') 

				
```
</details>

**Comment by carlosromanxyz** [comment]
Please post your shortcode code, thanks

**Comment by jpknz** [comment]
Please see below.

`add_shortcode( 'myshortcode', 'myshortcodefunc' );
	function myshortcodefunc ( $attributes ) {
		
		$attributes = array_change_key_case((array)$attributes, CASE_LOWER);
		$content = '';
		$user_subscriptions = wcs_get_users_subscriptions();		
		
		if( ! empty( $user_subscriptions ) ) { 
			if ( is_admin() || is_preview() || \Elementor\Plugin::$instance->preview->is_preview_mode() ) {
				$variation_id = 194;
			}
			else {
				$variation_id = 0;
			}
			
			foreach( $user_subscriptions as $user_subscription_id => $subscription )
			{
				switch( $subscription->get_status() ) {
					case 'active':
						foreach( $subscription->get_items() as $item_line_number => $item_arr ) {
							if( $user_subscription_id == $item_arr['order_id'] ) { 
								$product_id = $item_arr['product_id'];
								$current_variation_id = $item_arr['variation_id'];
								$active_sub = $user_subscription_id;
								$active_line_item_number = $item_line_number;
								break 3; 
							}
						}
						break;
				}
			}
			
			$devicecount = isset($attributes['devices']) ? $attributes['devices'] : '';
			$billingperiod = isset($attributes['billingperiod']) ? $attributes['billingperiod'] : '';			
			$variation_id = get_variation_id_from_attributes( $product_id, $devicecount, $billingperiod );
			
			if ($variation_id == 0 ) {
				return 'Product not found';
			}
			
			switch ( $attributes['request'] ) {
				case 'price':
					
					if ( $variation_id === $current_variation_id ) { 
						$content = get_formatted_sub_price( $variation_id, 'existingplan' );
					}
					else {
						$content = get_formatted_sub_price( $variation_id, 'pricingwithbillingperiod' );
					}
					break;
				case 'url':
					if ( $variation_id === $current_variation_id ) {
						$content = '';
					}
					else {
						$content = add_query_arg( array(
								'add-to-cart'           => $product_id,
								'switch-subscription'   => $active_sub,
								'variation_id'          => $variation_id,
								'item'                  => $active_line_item_number,
								'_wcsnonce'             => wp_create_nonce( 'wcs_switch_request' )
							),
							wc_get_cart_url()
						);
					}
					break;
			}		
		}
		return $content;
	}`

**Comment by jpknz** [comment]
Please see below.

```
	add_shortcode( 'myshortcode', 'myshortcodefunc' );
	function myshortcodefunc ( $attributes ) {
		
		$attributes = array_change_key_case((array)$attributes, CASE_LOWER);
		$content = '';
		
		if ( is_admin() || is_preview() || \Elementor\Plugin::$instance->preview->is_preview_mode() ) {
				$product_id = 181;
				$active_line_item_number = "linenumbergoesherenormally";
				$active_sub = "subgoesherenormally";
		}
		else {
			$user_subscriptions = wcs_get_users_subscriptions();		
			if( ! empty( $user_subscriptions ) ) { 
				foreach( $user_subscriptions as $user_subscription_id => $subscription )
				{
					switch( $subscription->get_status() ) {
						case 'active':
							foreach( $subscription->get_items() as $item_line_number => $item_arr ) {
								if( $user_subscription_id == $item_arr['order_id'] ) { 
									$product_id = $item_arr['product_id'];
									$current_variation_id = $item_arr['variation_id'];
									$active_sub = $user_subscription_id;
									$active_line_item_number = $item_line_number;
									break 3; 
								}
							}
							break;
					}
				}
			}
			else {
				return '';
			}
		}
			
			$devicecount = isset($attributes['devices']) ? $attributes['devices'] : '';
			$billingperiod = isset($attributes['billingperiod']) ? $attributes['billingperiod'] : '';
			$variation_id = get_variation_id_from_attributes( $product_id, $devicecount, $billingperiod );
			
			if ($variation_id == 0 ) {
				return 'Product not found';
			}
			
			switch ( $attributes['request'] ) {
				case 'price':
					
					if ( $variation_id === $current_variation_id ) { 
						$content = get_formatted_sub_price( $variation_id, 'existingplan' );
					}
					else {
						$content = get_formatted_sub_price( $variation_id, 'pricingwithbillingperiod' );
					}
					break;
				case 'url':
					if ( $variation_id === $current_variation_id ) {
						$content = '';
					}
					else {
						$content = add_query_arg( array(
								'add-to-cart'           => $product_id,
								'switch-subscription'   => $active_sub,
								'variation_id'          => $variation_id,
								'item'                  => $active_line_item_number,
								'_wcsnonce'             => wp_create_nonce( 'wcs_switch_request' )
							),
							wc_get_cart_url()
						);
					}
					break;
			}		
		}
		return $content;
	}
```

**Comment by jpknz** [comment]
Hi

Any update on this one at all?

Thanks

**Comment by bainternet** [comment]
@jpknz where are you seeing these requests?

In the editor? If so it's ok because that's how Elementor works. As for the front end you should not see any requests for the shortcode because it's all rendered on the main page request via a single PHP process.

If that's not the case please feel free to reopen.

**Comment by jpknz** [comment]
Not sure how to reopen???

This is on the frontend.

A developer is looking at this now - please reopen and leave for them to deal with. They have all the details of how to see what is happening on the frontend.

**Comment by bainternet** [comment]
@jpknz 

We can't replicate, 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by jpknz** [comment]
Hi @bainternet 

You said to reopen if this wasn't in the editor and it's not.  As mentioned previously a developer is (supposedly) working on this and they have all of the requested credentials to login and see what is happening.

Those credentials were provided 4 days ago and support has simply stopped responding since.  The credentials have not been used.

I'm not sure where to go from here since nobody from elementor (support and on here) responds with any haste.

I'd still like this ticket reopened until the issue is resolved - by whoever that may be - otherwise I fear that the issue is going to be simply lost.

**Comment by BaldoTuttle** [comment]
Hi,

any news on that? I have the same problem. My shortcode is called twice in frontend. The shortcode just increments an integer in a wp_option for testing puposes now.

I did insert the shortcode in a new page inside a Gutenberg block (not elementor) and the shortcode is called one time when the page is opened in the front end.

As soon as I add the shortcode in a shortcode widget in elementor, the shortcode is called twice when the page is opened in the front end.

**Comment by Mulli** [comment]
I have the same issue. super simple shortcode:

`
add_shortcode('consult-meeting-strip', 'consult_meeting_strip');
function consult_meeting_strip(){
    if(!get_field('hide_bottom_contact') && !wpmd_is_device()){
        $shortc = do_shortcode('[contact-form-7 id="4" title="פגישת ייעוץ"]');
        $str = '
            <div id="pre-footer-contact">
              <div class="boxed">
                <div id="consule-img"></div>' 
                . $shortc 
             . ' </div>
            </div>';
        return $str;
    }
    return '';
}
`

**Comment by ssentic** [comment]
The same problem here. My "quick fix" was to hide the duplicated shortcode with CSS, but the problem is still there.. Did anyone found a solution? 

`function contactsWidget() { ?>
    <div id="contact-widget">
        <div class="contact-list-items">
        	<div class="contact-list-item">
        		<a href="/en/contact" target="_blank">					
        			<i aria-hidden="true" class="fas fa-envelope-open-text"></i>
        		</a>
        	</div>
        	<div class="contact-list-item">
        		<a href="tel:0038641748336" target="_blank" rel="nofollow">						
        			<i aria-hidden="true" class="fas fa-phone-alt"></i>
        		</a>
        	</div>
        </div>
        
        <button id="toggleButton"><i aria-hidden="true" class="far fa-comment-dots"></i></button>
    </div>    
        
    <script>
        jQuery(document).ready(function($) {
          $(".contact-list-items").hide();    
            
          $("#toggleButton").click(function() {
            $(".contact-list-items").toggle();
          });
        });
    </script> <?php
}

add_shortcode('quick_contacts', 'contactsWidget');`

**Comment by kentabg** [comment]
got the same problem with Frontend publishing pro plugin shortcode

**Comment by rodrigotezen** [comment]
The same problem here! Even a Content Editor widget can not resolve the problem.

**Comment by rodrigotezen** [comment]
Here is a good solution to the problem: https://github.com/elementor/elementor/issues/3152 
`function daily_profit() {
  ob_start(); // SOLUTION
  include( locate_template( './daily_profit-layout.php', false, false ) );
  return ob_get_clean(); // SOLUTION
}
add_shortcode('daily_profit', 'daily_profit');`

**Comment by techlawctopus** [comment]
In my case, the shortcode was being called multiple times, as I had left an unclosed html tag. 
Soon as I closed it, my problem was fixed! 

Here is what was earlier missing closing </a> tag
![image](https://github.com/elementor/elementor/assets/115222815/7fe107de-091a-4a4b-b06a-6b40c889f221)

**Comment by Mramorov** [comment]
> @jpknz where are you seeing these requests?
> 
> In the editor? If so it's ok because that's how Elementor works. As for the front end you should not see any requests for the shortcode because it's all rendered on the main page request via a single PHP process.
> 
> If that's not the case please feel free to reopen.

Hello, in my case, the shortcode is actually called three times when the editor is loaded. The shortcode is executed the first time in the context of the post, which is used as template demo data (this is normal execution of the shortcode) and two more times in the context of the template itself, where there is no source data for its normal execution. Is this really normal?

**Comment by nviitala** [comment]
Same happens to me. If I add a shortcode to a Heading element, it gets called 5 times (in the frontend, not in the editor).
<img width="290" alt="Screenshot 2024-10-28 at 0 08 06" src="https://github.com/user-attachments/assets/399828a4-3009-421c-ac6a-7b862bcbd2db">

**Comment by Mouja0412** [comment]
I had the same issue with elementor, it turns out that the plugin All in one seo pack was parsing the shortcode.
Solution here : https://aioseo.com/docs/aioseo_disable_shortcode_parsing/
