### ISSUE TITLE
Dynmaic Taxonomy Images (by ACF) not displaying.

### ISSUE THREAD

**Issue by MPHood** [elementor/elementor#7454]
Hey guys. I have added an Image for every Taxonomy using Advanced custom Fields! 

I also am able to choose the metakey of this field in the elementor editor, but nothing is happening.

I tried adding it as backround fpr sections, Columns or as a regular image widget. Same result: the picture is neither showing in the editor, nor in frontend.  

Im using elementor pro, ACF Pro, and the regular Astra Theme.

**Comment by valentincauro** [comment]
Really interested for an answer 👍 💯

**Comment by sermalefico** [comment]
#5147

**Comment by shilo-ey** [comment]
I merged this issue with  #5147, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
