### ISSUE TITLE
[PRO] Elementor Pro Slides Arrow Navigation Issue

### ISSUE THREAD

**Issue by djoeni** [elementor/elementor#7456]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Pro Slides arrow navigation clicking on hover not covering on all arrow only on top tip of the arrow. With large arrow cant click on arrow except hovering on top tip of the arrow.
## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.25
	PHP Version: 7.3.2
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://www.medicelle.co.id
	Home URL: https://www.medicelle.co.id
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Jakarta
	Debug Mode: Inactive

== Theme ==
	Name: JupiterX Child
	Version: 1.0.0
	Author: Artbees
	Child Theme: Yes
	Parent Theme Name: JupiterX
	Parent Theme Version: 1.2.0
	Parent Theme Author: Artbees

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.12
		Author: Elliot Condon

	Elementor
		Version: 2.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

	Jet Elements For Elementor
		Version: 1.15.4
		Author: Zemez

	Jupiter X Core
		Version: 1.1.0
		Author: Artbees

	Raven
		Version: 1.1.0
		Author: Artbees

	The Plus Addons for Elementor Page Builder Lite
		Version: 1.1.0
		Author: POSIMYTH Themes

	Ultimate Addons for Elementor
		Version: 1.10.0
		Author: Brainstorm Force

	Use Any Font
		Version: 5.1
		Author: Dinesh Karki

	White Label CMS
		Version: 2.1.1
		Author: www.videousermanuals.com

	WP Rocket
		Version: 3.2.6
		Author: WP Media
</details>

**Comment by manektechmayank** [comment]
I have a same issue of misplace arrow icons in slides widget. Can anyone from Elementor Team have a look please.

**Comment by zatmar** [comment]
Same....

Theme: Elementor Hello

![bug](https://user-images.githubusercontent.com/11079007/63227946-8f2c5280-c1ec-11e9-8585-f5c53d62fb2b.PNG)

**Comment by gammaWave96** [comment]
![elementorbug](https://user-images.githubusercontent.com/52972059/63855488-ceeafb00-c99f-11e9-894f-e17aa7fd96ed.png

**Comment by Hynek-O** [comment]
the same problem as gammaWave96 and in the safari arrows disappear, they work poorly.

**Comment by zatmar** [comment]
Please reopen this issue and fix it.

**Comment by SchnetzApps** [comment]
I am also having trouble with the arrows not being spaced correctly.
![Annotation 2019-09-30 101915](https://user-images.githubusercontent.com/36321253/65900841-c7868b00-e36b-11e9-9a1e-a97a71d7643a.jpg)
