### ISSUE TITLE
2.5.6 It is not possible to create a new elementor page in the editor.

### ISSUE THREAD

**Issue by vaka2vaka** [elementor/elementor#7457]
2.5.6 It is not possible to create a new elementor page in the editor.  Disappeared button in the page bar.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
Hi @vaka2vaka 

This issue has been fixed in v2.5.7 

Feel free to update!

Thanks

**Comment by vaka2vaka** [comment]
Everything is working. Thank!

**Comment by danolar** [comment]
Hi ! after update it appears this and elementor is not opening :

Warning: Declaration of Jet_Woo_Builder_Archive_Document::save($data) should be compatible with Elementor\Core\Base\Document::save($data = Array) in /home/mypage12/public_html/wp-content/plugins/jet-woo-builder/includes/documents/class-jet-woo-builder-archive-document.php on line 0

Warning: Declaration of Jet_Woo_Builder_Category_Document::save($data) should be compatible with Elementor\Core\Base\Document::save($data = Array) in /home/mypage12/public_html/wp-content/plugins/jet-woo-builder/includes/documents/class-jet-woo-builder-category-document.php on line 0
