### ISSUE TITLE
Fixed Sidebar / Menu Example

### ISSUE THREAD

**Issue by Creativenauts** [elementor/elementor#7459]
Just wanted to see if anyone would be interested in learning how I setup this fixed sidebar within elementor which can be viewed here:

https://wpgalore.com/landing-pages/portfolio-landing-page/

I just had run into this issue at work where someone wanted this but found it wasn't built into elementor by default.

I'm working on the phone enhancements right now as I know that will be a question asked.

Let me know if you have thoughts / suggestions. Thank You.

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by Creativenauts** [comment]
@shilo-ey hi, this isn't for support, it's a feature request with an example of how it could be achieved.
