### ISSUE TITLE
Is there a Controls_Manager selectors syntax that we can use to do conditional CSS output based on the VALUE?

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#7462]
I searched trough everything including the docs and I am just not able to figure out if there is a condition that I can use to output selector CSS based on the VALUE. 

I am looking for something like this to float an element if value is left or right

`float:{{VALUE=="left" || VALUE=="right"}}`

		$this->add_responsive_control(
			'align',
			array(
				'label' => __( 'Alignment', 'domain' ),
				'type' => Controls_Manager::CHOOSE,
				'options' => array(
					'left' => array(
						'title' => __( 'Left', 'domain' ),
						'icon' => 'fa fa-align-left',
					),
					'center' => array(
						'title' => __( 'Center', 'domain' ),
						'icon' => 'fa fa-align-center',
					),
					'right' => array(
						'title' => __( 'Right', 'domain' ),
						'icon' => 'fa fa-align-right',
					),
				),
				'default' => '',
				'selectors' => array(
					'{{WRAPPER}} .heading-holder' => 'text-align:{{VALUE}};',
					'{{WRAPPER}} .heading-underline:after' => 'float:{{VALUE=="left" || VALUE=="right"}};',
				),
			)
		);

Any help is appreciated.

**Comment by crazypsycho** [comment]
You could do this:
```php
'{{WRAPPER}} .heading-underline:after' => 'float: {{VALUE}};'
```

Than float is left, right or center. Cause float: center is invalid, the browsern won´t float the element.

**Comment by danyj** [comment]
@crazypsycho  that leaves the unnecessary invalid CSS which is why I asked for possible syntax.

**Comment by bainternet** [comment]
@danyj 

The syntax in none existing, its plain search-replace of tokens and not some kind of template engine.

Thanks.
