### ISSUE TITLE
Change text colour in button on click

### ISSUE THREAD

**Issue by braakiebraak** [elementor/elementor#7463]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There seems to be no 'active' state for buttons.

**Describe the solution you'd like**
I want a text to change colour on-click, without this text being linked to somewhere. As in a button that is not linked, but just changes colour on-click.

**Comment by shilo-ey** [comment]
Hi @braakiebraak 

Thanks for your feedback.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

You can achieve this by using custom CSS (place it into the Custom CSS field under your button advnaced tab):
```CSS
selector span.elementor-button-text:focus {
    color: red; /* your color */
}
```

Thanks

**Comment by feidaman** [comment]
Any progress on this one? When I click a button, the focus state is basically the same as the hover state.

**Comment by vs999** [comment]
Can you please add this on Elementor??? 
I need to change the button background when some click once on it.

**Comment by JBLivmore** [comment]
Agreed, you need an active state in some situations, release it already...

**Comment by peterforensys** [comment]
+1
