### ISSUE TITLE
Where to embed the code

### ISSUE THREAD

**Issue by kapachon** [elementor/elementor#7466]
Was referred here by the support team.
I want to embed a chat code so it will load last (like with footer.php)
How can i do it with elementor?
Thank you

**Comment by chrisschwartze** [comment]
Can't you just add this to your functions.php @kapachon ? I don't think this is an Elementor question.

```php
function scripts_in_footer() {
      ?>
      // Your script <script> etc.
      <?php
}
add_action( 'wp_footer',  'scripts_in_footer' );
```

**Comment by shilo-ey** [comment]
Hi @kapachon 

It depends on the code.
You need some instructions from the chat developers.

Usually, you need to embed your code in your theme's `function.php` file as @chrisschwartze mentioned.

Thanks
