### ISSUE TITLE
2.5.7 loading on safe mode only

### ISSUE THREAD

**Issue by tiendadehipnosis** [elementor/elementor#7467]
After updating to 2.5.7 the Elementor editor only loads in Safe Mode.

I restored a backup that I made before updating to 2.5.7 and everything works fine. Then I updated Elementor plugin and the problem came back immediately.

**Comment by danolar** [comment]
Hi, same issue, and this appears : 
Warning: Declaration of Jet_Woo_Builder_Archive_Document::save($data) should be compatible with Elementor\Core\Base\Document::save($data = Array) in /home/mypage12/public_html/wp-content/plugins/jet-woo-builder/includes/documents/class-jet-woo-builder-archive-document.php on line 0

Warning: Declaration of Jet_Woo_Builder_Category_Document::save($data) should be compatible with Elementor\Core\Base\Document::save($data = Array) in /home/mypage12/public_html/wp-content/plugins/jet-woo-builder/includes/documents/class-jet-woo-builder-category-document.php on line 0

**Comment by nickvh1** [comment]
This update also caused a break between elementor and PODS plugin for custom content pages and posts. Gives a safe mode error when trying to open pages/post in elementor for some reason. V2.4.7 was working 100% though.

**Comment by tiendadehipnosis** [comment]
There is a new version, 2.5.8 and in the version details it says:
"Fix: Restore wp_localize_script for Gutenberg editor"

It doesn't look like a fix to our problem. I am afraid of installing 2.5.8. Did anybody with my problem tried it out?

Honestly it doesn't look like Elementor developers care about our bug report at all.

I guess we have not choice but to start giving them a 1 star review for bad support at:

https://wordpress.org/support/plugin/elementor/reviews/

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by tiendadehipnosis** [comment]
Thank you for acknowledging our issue and for releasing version 2.5.9.

In my case, I had to clear my browser images and files after updating the plugin. Now it is working fine.

Thank you.
