### ISSUE TITLE
Elementor is not compatible multilingul plugin “Bogo”

### ISSUE THREAD

**Issue by k-kikuchi-idea-hack** [elementor/elementor#7470]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I tried to create the multilingual page with Bogo(https://wordpress.org/plugins/bogo/) and Elementor, but when I tried to open the Elementor editor on a duplicated page, I could not realize it with the following Fatal error. Post type was page.

## Steps to reproduce

1: Push [Create New] buttons and open editor.
2: Open Elementor builder.
3: Publish the page.
4: Create Multilingul page with the function of bogo.
5: Open the duplicated page.
6: Open Elementor builder.
7: Fatal Error.
`Warning: Illegal string offset ‘template’ in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\core\settings\page\manager.php on line 257
Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, string given, called in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1018 and defined in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\includes\base\controls-stack.php:1952 Stack trace: #0 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\includes\base\controls-stack.php(1018): Elementor\Controls_Stack->sanitize_settings(‘d:12:{s:21:”bac…’) #1 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\includes\base\controls-stack.php(1771): Elementor\Controls_Stack->get_data(‘settings’) #2 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\core\base\base-object.php(132): Elementor\Controls_Stack->get_init_settings() #3 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\core\base\base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings() #4 C:\xampp\apps\wordpress\htdocs\wp-content\plug in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1952`

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/e9xJGTRg

```
</details>

**Comment by shilo-ey** [comment]
Hi @k-kikuchi-idea-hack 

Thanks for your feedback.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by grafickepracecom** [comment]
+1 to that
