### ISSUE TITLE
[Icon Box] Inconsistent behaviour with icon/content alignment options

### ISSUE THREAD

**Issue by ShadowXVII** [elementor/elementor#7471]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The Icon Box widget has both an Icon Position option and a Content Alignment option. However, the Content Alignment option incorrectly takes over the Icon Position when in responsive mobile/tablet mode.

<img width="223" alt="2019-03-15_19-45-01" src="https://user-images.githubusercontent.com/446329/54419499-b5405900-475b-11e9-810c-2a816d157d5d.png">

This seems to be because the Icon Box wrapper `elementor-icon-box-wrapper` is where the `text-align: left;` is set as opposed to applying to the content only: `div.elementor-icon-box-content`.

Leaving the Content alignment to blank/none behaves as expected.
![image](https://user-images.githubusercontent.com/446329/54418720-d0aa6480-4759-11e9-9f47-823700afc990.png)

Also, I like that the Icon Box centers itself when the viewport gets smaller (contrary to #3040).
 
## Steps to reproduce

1. Create an Icon Box
2. Set the Icon Position to Left
3. Add Content and set Content Alignment to Left (explicitly, not default/none)
4. In responsive mode, the icon gets stuck left.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
I'm a bit confused, what is your desired behavior and what is happening now that is not as expected.

Looking forward to your reply.

**Comment by ShadowXVII** [comment]
The icon should remain centred in responsive (tablet/phone mode). It gets left aligned because content alignment is set to left.

**Comment by Elementalel** [comment]
Following

**Comment by klainser** [comment]
+1

**Comment by ivanshum** [comment]
+1

**Comment by mamartinez** [comment]
+1

**Comment by DorShahar** [comment]
Hi @ShadowXVII ,
Thank you for your input.

I understand the reason for the request and the volume of it, but, unfornunatly at the moment we cannot support this request.

Thanks
