### ISSUE TITLE
After update 'Edit with Elementor' not available

### ISSUE THREAD

**Issue by hannahloibl** [elementor/elementor#7474]
I have recently started a website on Wordpress.org (hosted by Siteground) and I have been using OceanWP for my template which uses Elementor. It's been working relatively well since I installed it but since yesterday the ability to edit pages with Elementor has disappeared on all channels. I can't do it via the 'view page' option on word press or on the 'Site pages' section (where there would ordinarily be a 'Edit with Elementor' option.) 

I have disabled and re-enabled the plugin, hoping that might do something. Everything is updated now to it's most recent version etc. but still no luck. Very frustrating as I can't edit my website at all until I can get access to the Elementor editor!

Can anyone advise whats happening here?

**Comment by shilo-ey** [comment]
Thanks for reporting.

This issue was fixed in v2.5.8

Thanks
