### ISSUE TITLE
2.5.8 only safe mode

### ISSUE THREAD

**Issue by tobias992** [elementor/elementor#7475]
Hello,

with new version update i get these errors:

JS: 2019-03-15 10:11:44 [error X 9][https://daskeks.com/wp-content/plugins/elementor/assets/js/frontend.min.js:2:12372] Argument 1 of Window.getComputedStyle is not an object.
--
JS: 2019-03-15 10:12:26 [error X 9][https://daskeks.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.8:2:83363] i is undefined

Elementor addons also not work... edit sites only in safe mode.

**Comment by bainternet** [comment]
@tobias992 	

If it works in safe mode, it means that there is a 3rd party plugin conflicting.

Please make sure to update to the latest version and try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.


thanks.
