### ISSUE TITLE
Ninja Forms conflict

### ISSUE THREAD

**Issue by kjohnson** [elementor/elementor#7476]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Some Ninja Forms customers are reporting a conflict with Elementor and Ninja Forms when a Ninja Forms is not on the page, specifically with the page builder. Further, we are seeing issues with GDPR fields (in Ninja Forms), being scrubbed when Elementor is active.

Related: https://wordpress.org/support/topic/bug-in-compatibility-php-conflicting-with-ninja-forms-and-causing-loss-of-data/

## Steps to reproduce

With Elementor and Ninja Forms installed, active:

- Edit a page (without a Ninja Forms form).
  - Page Builder doesn't load.
  - CPU Maxes out.
  - VPS crashes.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Ninja Forms).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Contact for more specific details or access to VPS: kyle@saturdaydrive.io

<details>
<summary>System Info</summary>

### Environment ###

Ninja Forms Version: 3.4.4
Ninja Forms DB Version: 1.1
Ninja Forms Gatekeeper: 99
WP Version: 5.1 - Supported
WP Multisite Enabled: No
Web Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.15-0ubuntu0.18.04.1
MySQL Version: 5.7.25
PHP Locale: negative_sign:

WP Memory Limit: 40M
WP Debug Mode: No
WP Language: Default
WP Max Upload Size: 16 MB
PHP Post Max Size: 16M
Max Input Nesting Level: 64
PHP Time Limit: 60
PHP Max Input Vars: 1000
SUHOSIN Installed: No
Server IP Address: 45.55.53.26
Host Name: KMF01
SMTP: localhost
smtp_port: 25
Default Timezone: America/New_York

### Plugins ###

Activated Plugins: All In One SEO Pack by Michael Torbert version 2.12
Coming Soon Page & Maintenance Mode by SeedProd by SeedProd version 5.0.24
Elementor by Elementor.com version 2.4.7
Mailgun by Mailgun version 1.7.1
Ninja Forms - Addon Manager by The WP Ninjas version 3.0.13
Ninja Forms - PayPal Express by The WP Ninjas version 3.0.14
Ninja Forms by The WP Ninjas version 3.4.4
UpdraftPlus - Backup/Restore by UpdraftPlus.Com
DavidAnderson version 1.16.6
</details>

**Comment by shilo-ey** [comment]
Hi @kjohnson 

Thanks for your feedback,

We would be glad if you could contact our support for better troubleshooting this issue.

Thanks!

**Comment by kjohnson** [comment]
@shilo-ey I did contact support, and they directed me to GitHub.

Is there an individual that I can make contact with?

**Comment by shilo-ey** [comment]
Hi @kjohnson 

We will contact you shortly through your email

**Comment by SrtaBrunaBozz** [comment]
Hi there! Did you solve this problem?
Would you please share with me, I have the same problem.

Thanks

**Comment by KimBesser** [comment]
I'm having the same issue.

**Comment by happy-harry** [comment]
I'm the one who originally discovered the issue and contacted @kjohnson to help me out. 

We found a workaround but it's not ideal. 

Commenting out the section of code called "Hack for Ninja forms in Elementor (lines 93-103 in "includes/compatibility.php") seems to resolve the issue,but it needs to be done any time Elementor is updated.

The plugin seems to work fine without this section of code, so it would be great if Elementor could either fix or remove the code so it doesn't cause the freezing. Or am I literally the only one having this issue?

Ninja support opened a ticket with Elementor and I gave them access to the server, then never heard back from either company.

I emailed Ninja support a few weeks ago to see if they made any progress and they never responded.

I'm working around the issue by disabling the Ninja plugins any time I need to make any edits with Elementor.

**Comment by Steve2Go** [comment]
I have the exact same issue, except when commenting the lines in includes/compatibility.php the editor does not load. This does stop the VPS from crashing however.
I do notice that prior to the commenting, the cause of the VPS crashing is mysql maxing out CPU if it's helpful.
Anything I can do do help debug, let me know.

**Comment by bsmith125** [comment]
I'm having the same issue with Elementor conflicting with Ninja Forms on the back end. When I go to edit a form, I get a blank screen. Any updates on an official fix?

**Comment by ouzdohan** [comment]
Here we go again, more BUGS in plugin conflicts! What is going on chaps? Can you please fix it asap. I can't edit elementor and niether can I disable Ninja forms.

I don't think I should waste time fixing this problem. Can't edit any pages with elementor.

Looks like I've got to do my own forms after all. Now avoiding all future forms in both Elementor and Nnja. 

Not good enough!

**Comment by happy-harry** [comment]
Try bugging them on the new thread. This one got closed for some reason.

https://github.com/elementor/elementor/issues/8267

**Comment by happy-harry** [comment]
@shilo-ey @kjohnson Any word on a permanent fix for this? It's been 4 months since the issue was [originally reported. ](https://github.com/elementor/elementor/issues/7476)

**Comment by markd91** [comment]
Still having this issue

**Comment by Yop-La** [comment]
same for me :/
