### ISSUE TITLE
⛔ 🔗 🚀 Feature Request: Mobile Sub Menu Colours (Duplicate of #3275)

### ISSUE THREAD

**Issue by Nikster1968** [elementor/elementor#7478]
Hi all,

I am suggesting an addition to the menu element.

At present when you design your menu and it happens to have a sub menu, for desktop you can make it look however you want with regard to colours. This however directly effects the mobile menu and makes it the same colours as the sub menu on desktop.

The problem with this is that when a sub menu is opened on a mobile device, the opened menu items are the same colour as the main menu making it very difficult to see. (i have attached an image to show what i mean).

An option to create contrasting Mobile Sub Menu item colours would be amazing as i am having trouble sorting it.

Many thanks for reading

Kind regards

Nick
<img width="470" alt="Screenshot 2019-03-15 10 25 20" src="https://user-images.githubusercontent.com/31955933/54444543-dcd2f980-473a-11e9-8f29-6d475d8e5c1d.png">
<img width="283" alt="Screenshot 2019-03-15 10 26 04" src="https://user-images.githubusercontent.com/31955933/54444544-dd6b9000-473a-11e9-954c-9cca22def57f.png">

**Comment by shilo-ey** [comment]
I merged this issue with #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @Nikster1968,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
