### ISSUE TITLE
Reviews widget glitch

### ISSUE THREAD

**Issue by Pixelinity** [elementor/elementor#7479]
I have found that the reviews slider widget has a problem not displaying the first persons face on the second round and subsequent rounds thereafter. I found this is due to the "Jetpack" plugin option under "settings" for the "image lazy loader" this must be turned off for reviews widget to work right.

**Comment by shilo-ey** [comment]
Hi @Pixelinity 

Try telling JetPack to exclude the images inside the carousels in elementor from Lazy Load.

Thanks.
