### ISSUE TITLE
Responsivenes in tablet mode does not respond

### ISSUE THREAD

**Issue by mgustavs** [elementor/elementor#7481]
Dear Elementor,

I am working on a page in Elementor Pro on Mac and I have problem with Responsiveness for Tablets - any change I make does not take place in live mode and seems also not in front end...
Desktop and Mobile views work fine. I have attached a photo where you can see that one of columns should be 80% but both are still 50%..

Amindiary mentioned this on September 10, 2018. One of you closed it because of too much rules and that hasn't solved the issue itself. Can this maybe come up on surface now for a resolve?

Thanks a million!

<img width="1195" alt="Screen Shot 2019-03-15 at 19 37 14" src="https://user-images.githubusercontent.com/47918624/54451877-7ced4a80-475c-11e9-9edf-2973aee60794.png">

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it we simply can't help.

Thanks.

**Comment by mgustavs** [comment]
Great Shilo-ey instead of diving into it let's close it - that just solved the problem :)
