### ISSUE TITLE
🔗 🚀 Feature Request: Add the ability to change the url slug/permalink for elementor created pages in the classic editor (Duplicate of #7044)

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#7483]
I would like the ability to be able to change the slugs/permalinks of elementor created pages. 

Currently they display this way in the classic editor when trying to edit an elementor page:

![example](https://user-images.githubusercontent.com/31750063/54464387-b65d9000-4733-11e9-994c-1ba9d858b033.PNG)

In the normal classic editor in the pages section, next to the slug there is an edit button:

![classic](https://user-images.githubusercontent.com/31750063/54464412-caa18d00-4733-11e9-8e5b-539a528abc3a.PNG)

My request is to add the same edit button functionality for the slugs/permalinks of elementor pages inside the classic editor, or quick edit or within elementor itself

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
Yes
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
Yes

**What problem is your feature request going to solve? Please describe.**
Allow you to change the slug to something cleaner

**Describe the solution you'd like**
Add a method to edit the slug to quick edit, edit, or within elementor's editor itself

**Describe alternatives you've considered**
Using a yoast 301 redirect.

**Comment by SniffleValve** [comment]
@jazir5 
In the WP classic editor, select Screen Options (upper right), enable Slug, then the Slug edit box will be available in the WP editor.
Cheers!
Lyle

**Comment by jazir5** [comment]
I ticked the check box, I am still unable to change the permalink. I should
clarify these are sections in the my templates section in the sidebar, not
"pages" or "posts"

**Comment by SniffleValve** [comment]
Yep, the slug field is there for me in any template in My Templates .... can change it no problem :)

**Comment by jazir5** [comment]
That doesn't work for me. What I found as a solution is to install the
plugin "post type switcher", and then I changed the post type of the page I
wanted to change the slug of to "page". Once I did that, I could change the
slug at will. Roundabout, but it works.

**Comment by shilo-ey** [comment]
I merged this issue with #7044, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by systmuk** [comment]
@jazir5  the permalink doesnt have an edit button like post and pages, but you can change it, using the slug box
see screenshot for clarification.
[https://prntscr.com/se8uwd](url)
hope that helps

**Comment by AliHussain85** [comment]
Just enable Slug from "Screen Option".

![image](https://user-images.githubusercontent.com/42221390/116939538-ef477e80-ac85-11eb-86a7-d068153e7a99.png)

Then find the Slug Option at bottom of the screen. It will look like this: 

![image](https://user-images.githubusercontent.com/42221390/116939627-13a35b00-ac86-11eb-96e0-396abf177f9a.png)

**Comment by Ssendam0101** [comment]
I ran into this issue as well. The problem appears to be related to archive templates created for custom taxonomies (at least it is in my case). So I have a custom taxonomy of "property-types" that you can create an archive template for in Wordpress and associate with the Property Types Archive. When viewing it on the site though, it will display with the ending of ?elementor_library=property-types . 

Changing the slug doesn't matter in this case because the slug is set correctly - it shows up as "property-type" in the slug. The ?elementor_library part is being dynamically added by elementor. And permalink options are not available in the theme builder section of elementor (where you can see the archive templates and edit them).

**Comment by jgarcianewemage** [comment]
this feature has been  put in hiatus by the team, only solution is to make your own post type with   Pods

**Comment by frederike-petzschner** [comment]
Same issue. Still no solution?

**Comment by atheraries** [comment]
Don't know why elementor has some stupid issue. I've 2 websites, On using the same theme Astra, there is no permalink issue on one website. But on the other website for some unknown reason, I'm facing the same permalink problem. ?elementor_library= :@ 

I am wondering why elementor has no post on this issue. Another main feature that elementor is missing is email verification of the user who submits the form. These are some basic issues of the customers which elementor has failed to resolve.
