### ISSUE TITLE
Popover in popover closes the parent on child mouseup

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#7484]
I am trying to group set of options in popover and it works fine until I add box shadow.
Tested with nesting popovers and same issue.  If I open parent popover and than change any box-shadow slider the parent popover closes. 

Here is video 

https://monosnap.com/file/2MgOMPEtYiy2sqn8dQsLCyAdzEloXv

test code 

```
  // Start Popover
  $this->add_control(
	  'popover_group',
	  array(
		  'label' => __( 'Popover', 'plugin-name' ),
		  'type' => \Elementor\Controls_Manager::POPOVER_TOGGLE,
	  )
  );
		  
  $this->start_popover();
			  
  $this->add_control(
	  'el_margin',
	  array(
		  'label' => __( 'Margin', 'plugin-name' ),
		  'type' => \Elementor\Controls_Manager::DIMENSIONS,
		  'size_units' => array( 'px', '%', 'em' ),
	  )
  );	
  
  
  $this->add_group_control(
	  \Elementor\Group_Control_Box_Shadow::get_type(),
	  array(
		  'name' => 'el_bsh',
		  'label' => __( 'Box Shadow', 'plugin-name' ),
	  )
  );
	  
  $this->end_popover();
```

**Comment by shilo-ey** [comment]
Hi @danyj 

We do not support popover inside a popover because of UI and technical issues, such as the one you described.
I recommend you to set the first popover to a switcher control with conditional display for the child controls.

Thanks!

**Comment by danyj** [comment]
The intended use of the popover is not to kill the user with to many options at once. 
This is an actual bug not a support or feature request and I think it should be handled as such and not closed and advised not to use. 

Popover as well as tabs are control containers and we should be able to use default controls within them , no matter what the control is.
