### ISSUE TITLE
Latest Patch Internet Explorer Bug / Elementor + Master Slider 

### ISSUE THREAD

**Issue by AngelzGFX** [elementor/elementor#7485]
since today half of my website not working anymore on Internet Explorer but on FIrefox and google all is fine some image gallerys also master slider not working anymore...

cheers

**Comment by AngelzGFX** [comment]
ok found the problem essentials addons pro for elementor cause the problem

**Comment by shilo-ey** [comment]
Thanks, 

Glad you managed to troubleshoot the issue.
