### ISSUE TITLE
Firefox not loading SVG

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#7491]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello, 

When loading an SVG image as logo in the site header it does not show up in latest firefox.
Could this be a bug? 

Thanks 

## Steps to reproduce

1. add image widget with SVG
2. Check in firefox.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Webtica 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* System info.

Without it we simply can't help.

As for your question, currently, we do not have official support for SVG.

Thanks.
