### ISSUE TITLE
Sticky element stop point

### ISSUE THREAD

**Issue by JoeDarko** [elementor/elementor#7492]
I'm trying to make a basic sticky ad banner in a sidebar, but i'm finding it impossible to do with Elementor.

Here is a sketch of what i'm trying to achieve:

![Sticky Banner](https://i3.yapics.com/03/16/3316q7ls03.png)

If i set the banner to be sticky, it works, but it doesn't stop at the end of the sidebar and continues to overlap everything under the sidebar.

If i set the option "Stay in column", the banner doesn't move at all, because the columns in Elementor never have height of 100% but instead end exactley where the last widget ends.

I'm i missing something and is there a way to achieve this in Elementor? Sticky banner in a sidebar is one of the most commont uses of sticky elements in webdesign, so surely this should be possible to do in Elementor.

Thank you for any answers.

**Comment by shilo-ey** [comment]
Hi @JoeDarko 
What do you mean by 
> "because the columns in Elementor never have height of 100% but instead end exactley where the last widget ends."

That's supposed to work in your editor. see here: https://www.useloom.com/share/c89f6540a62a48d6a7e437dfeb0d3b7b

**Comment by JoeDarko** [comment]
It seems the problem is only in my edge case. I created the sidebar as a template and then inserted it into the column as a WordPress Elementor Library widget. In this case it doesen't work because there is so many nested elements. If i just build simple two columns than it works, so i guess there is no problem.

Thank you.

**Comment by ELSENO** [comment]
Hi there,
we're trying to make a sticky sidebar with a widget. 
Unfortunately the sidebar overlaps (or underlaps) the footer by scrolling down, but should stop above. Any ideas to solve this?

**Comment by shilo-ey** [comment]
[**@ELSENO**](https://github.com/ELSENO) commented on [Mar 21, 2019, 9:56 AM GMT+2](https://github.com/elementor/elementor/issues/7492#issuecomment-475138809 "2019-03-21T07:56:57Z - Replied by Github Reply Comments"):
> Hi there,
> we're trying to make a sticky sidebar with a widget. 
> Unfortunately the sidebar overlaps (or underlaps) the footer by scrolling down, but should stop above. Any ideas to solve this?

Please create a new issue with all the required information.

@JoeDarko Thanks!
