### ISSUE TITLE
Elementor Customized Search Results Page Issue

### ISSUE THREAD

**Issue by wacaszafar** [elementor/elementor#7493]
I have customised my Search Results Page using elementor. Now when I search it shows me the search results directly. it does not show like showing results for: searched keyword also it does not highlight the keywords searched like for example on below site you can search for "world" it will directly show the result and does not show showing results for "world" also does not highlight world please resolve. thank you.

also there is two close buttons on the search pop up one is for the pop up understandable however what is the second close button for and how to make it stop appearing.

my site is below.

https://giloci.cloudaccess.host

**Comment by shilo-ey** [comment]
Hi @wacaszafar 

The behavior you are describing is not an issue, but a misconfigured search results page.

Please customize it for your needs. [more info here](https://www.youtube.com/watch?v=kPAUEShgdoo).

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
