### ISSUE TITLE
Cannot insert Nextgen Gallery with Elementor 2.5.8

### ISSUE THREAD

**Issue by nocloo** [elementor/elementor#7494]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Cannot insert Nextgen Gallery in Elementor.

## Steps to reproduce
1- Edit/Create a post and edit with elementor
2- Add a text element
3- On top of text box editor, click on "Add gallery"
4- There is a pop-up blank page.

## Isolating the problem

- [] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.9
	MySQL version: mariadb.org binary distribution v10.3.13
	PHP Version: 7.3.3-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://XXX
	Home URL: https://XXX
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

== Active Plugins ==
	Elementor
		Version: 2.5.8
		Author: Elementor.com

	NextGEN Gallery
		Version: 3.1.7
		Author: Imagely

== Log ==
	: 
PHP: showing 3 of 3PHP: 2019-03-14 17:32:43 [notice X 3][/var/www/XXX/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-14 20:16:52 [notice X 1][/var/www/XXXa/wp-content/plugins/elementor/core/files/css/global-css.php::136] Undefined index: font_weight [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 1 of 12019-03-16 13:43:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.7',
  'to' => '2.5.8',
)]

			

</details>

**Comment by shilo-ey** [comment]
Can you add a gallery without Elementor activated? 

From our inspection - there's a loop and we cannot insert a gallery (the specific error is: "This block has encountered an error and cannot be previewed.")

Thanks.

**Comment by nocloo** [comment]
Yes, I can add a gallery using the classic editor. However, when I wants to edit the post in elementor again, it removed the gallery and sometimes it left the gallery shortcode there.

**Comment by shilo-ey** [comment]
Sorry but cannot reproduce this.

If the issue persists please open a new issue with steps to reproduce.

Please try our troubleshooting basics including clearing your server and browser cache.

Thanks!
