### ISSUE TITLE
How can I get the template id of a post?

### ISSUE THREAD

**Issue by wavesforthemasses** [elementor/elementor#7495]
Hi, before posting this I sent aa similar message to your Facebook Group and had no answers. Then I contacted support on your website and they redirected me to github. I'm not saying this to complain :) just, cause I know you don't offer support on github usually.

I'm developing my first Elementor extension and so far everything works great. Now I'm trying to have a sort of infinite scroll for single pages: if I scroll till the end of a single page it loads the next one of the same post type.
I know how to do it, but I'm stuck on this small thing: if I know a post ID, is there a way to get his template ID?

To be clear: I made a template using elementor Theme Builder for a single post type. Now I want a function to return that template id when I'll pass to it a postID as parameter.. of course only if that post actually use that template as layout.

P.S. if this is impossible, I'd be ok also with knowing how I could get the current template ID inside a widget: if I'll drop my widget on a template with ID 679, I should get the ID 679 inside that widget php code.
Hope my question is enough clear :)

Vincenzo

**Comment by SniffleValve** [comment]
@wavesforthemasses 
The very simplest way is to hover over the template title in My Templates and look in the lower left corner of your browser, where you will see xxxx post=xxx ... that' the ID :)
The next simplest way, and what I do, is to use the CatchIDs plugin :)
Cheers!
Lyle

**Comment by wavesforthemasses** [comment]
Sorry I wasn't clear enough: I need a function :)

example:

$templateID = functiontogettemplateid($postID);

**Comment by shilo-ey** [comment]
Hi @wavesforthemasses 

Elementor uses custom post type named templates to generate the templates, therefore the Template ID is the same as the Post ID 

You can get all Post IDs using JS function.

Let me know if that points you out to solve your issue.

Thanks

**Comment by wavesforthemasses** [comment]
No it doesn't, because it's not correct: the Template ID is not the same as the Post ID because many posts can have the same template.

Anyway I fixed this one year ago hardcoding the template ID on a field in a "Infinite Scroll" widgtet. :)

Thanks!

**Comment by udidol** [comment]
Hi @wavesforthemasses ,
There is currently no function that you can use that returns a post/page's template's post ID. We use the template ID in one place in the post's loading sequence and that is it, we do not externalize it. We will consider doing that in the future for convenience.

**Comment by webdevs-pro** [comment]
In case someone looks for solution how to get template id that contain current widget
```
$e = new Exception();
$key = array_search( 'get_builder_content', array_column( $trace, 'function') );
$template_id = $trace[$key]['args'][0];
```

**Comment by albionselimaj** [comment]
> In case someone looks for solution how to get template id that contain current widget
> 
> ```
> $e = new Exception();
> $trace = $e->getTrace();
> $key = array_search( 'get_builder_content', array_column( $trace, 'function') );
> if ( $key ) {
>    $template_id = $trace[$key]['args'][0];
> } else {
>    $template_id = get_the_ID();
> }
> ```

In PHP 7.4+ you'll also need this ini setting for this to work `ini_set( 'zend.exception_ignore_args', 0 );`

**Comment by cybersholt** [comment]
> > In case someone looks for solution how to get template id that contain current widget
> > ```
> > $e = new Exception();
> > $trace = $e->getTrace();
> > $key = array_search( 'get_builder_content', array_column( $trace, 'function') );
> > if ( $key ) {
> >    $template_id = $trace[$key]['args'][0];
> > } else {
> >    $template_id = get_the_ID();
> > }
> > ```
> 
> In PHP 7.4+ you'll also need this ini setting for this to work `ini_set( 'zend.exception_ignore_args', 0 );`

This solution worked for me, noticed an issue with powerpack-elements > registration form widget. 

== Server Environment ==
Operating System: Linux
Software: nginx/1.19.8
MySQL version: Source distribution v10.4.14
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected
== WordPress Environment ==
Version: 6.1.1
Debug Mode: Active

**Comment by pedrowoobik** [comment]
`function si_get_elementor_single_template_id() {
    $manager = \ElementorPro\Plugin::instance()->modules_manager->get_modules( 'theme-builder' )->get_conditions_manager();
    $templates_by_condition = $manager->get_documents_for_location( 'single' );
    if($templates_by_condition) {
        $single_template = reset($templates_by_condition);
        $template_id = $single_template->get_post()->ID;
        return $template_id;
    }
}`

**Comment by davilera** [comment]
@pedrowoobik I've tested this code and it only works if I'm logged in -- as soon as I log out and run the same code, it returns `false`. Is this the expected behavior or am I missing something?

**Comment by pedrowoobik** [comment]
> @pedrowoobik I've tested this code and it only works if I'm logged in -- as soon as I log out and run the same code, it returns `false`. Is this the expected behavior or am I missing something?

Sorry about the late @davilera , Maybe you have your template in draft? Or assigned only for logged in users... Cache activated for non logged in users? Tiene que ser algo de esto, no se me ocurre nada más :D
