### ISSUE TITLE
[Feature Request] Scroll trough fonts with live preview

### ISSUE THREAD

**Issue by Yagu-znal** [elementor/elementor#7497]
I'd love to be able to browse trough the font list with the scroll wheel or up and down arrows á la photoshop or illustrator with the right live preview following.

**Comment by shilo-ey** [comment]
Hi @Yagu-znal 
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.

As for your request, elementor works with a dropdown select field for the fonts. if you will pause your scroll you can see a preview of the font.

Thanks.
