### ISSUE TITLE
Elementor popup trigger on hoover

### ISSUE THREAD

**Issue by jase0** [elementor/elementor#7502]
I would like to make a popup that triggers on hover instead of click. This is for a mega menu. 

When you hover over the text a popup will appear next of the text. When the cursor is off the text the popup closes.

An example of what I’m trying to do is the stussy.co.uk mega menu.

**Comment by shilo-ey** [comment]
I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bentalgad** [comment]
+1

And no, it's the same subject as #6899 at all.

**Comment by cboydst** [comment]
+1

Agreed, this issue is not related to #6899 at all

**Comment by simonozzy** [comment]
+ 1 
Would be super useful for tooltip style "more info" boxes.

**Comment by PPjev** [comment]
+1 we need to utilize pop up OR section for mega menu. So basically a trigger for it to show on menu item hover, and hide it when canvas is left.

**Comment by htmlswift** [comment]
Hello everyone, 
I made it work like this. Cheers!

Step 1 - Setup your Popup. 
Step 2 - Add Display Condtions. 
Step 3 - Add a Class on which element you want hover to trigger.
Step 4 - In the Link Section - Under Dynamic Tags in Link Field - Select Popup
Step 5 - Select - Action - Open Popup
Step 6 - Select the Popup you want to open, and Save the Changes.
Step 7 - Add the Code below in your custom javascript file or even inline.

`<script>
    jQuery('.popup-trigger a').hover(function(){
        jQuery(this).trigger('click');  
    }); 
</script>`

**Comment by pkongawi** [comment]
Thank you HTML Swift.  Where do I put the ID for the Javascript hover feature?
<script> jQuery('.popup-trigger a').hover(function(){ jQuery(this).trigger('click'); }); </script>

**Comment by htmlswift** [comment]
@pkongawi Why do you need to put ID? did not understand. Can you eleborate more? thanks!

**Comment by pkongawi** [comment]
@htmlswift Thank you for responding.  I implemented your code but I am not sure if I did it correctly. I connected the popup to an Icon but the hover feature is still not working.  I found you on Upwork but for some reason, it would not allow me to send you a message. I really need help with this.

**Comment by htmlswift** [comment]
@pkongawi I found you on Skype and sent you a message there. did you recived that? It would be from Sumit Sharma :) 
If you did not get any, leave me one  on skype - live:htmlswift thanks!

**Comment by jonnymueller** [comment]
This idea works as well:
https://elementorcodes.com/elementor-hover-popup/

But only open on Hover works fine. Because if you make it close when leaving the trigger, that's not really what I want. 
As @PPjev said, most of us need it to close only when you leave the popup canvas again, not just the trigger.

**Comment by mdanielou** [comment]
hello community, any update / new idea on that issue?

I have the same issue as @jonnymueller 
when I implement the JS code, the popup disappears as soon as the mouse pointer is not focused on the menu item
right now i have a mega menu that needs to be clicked, so it's not the best UX :-/ 

http://trajaan.io/

**Comment by debihazelden** [comment]
+1

**Comment by mdanielou** [comment]
found the solution!
https://element.how/elementor-hover-popup/

**Comment by ChristianZamboni** [comment]
> Obrigado HTML Swift. Onde coloco o ID para o recurso de foco do Javascript?
> 
> <script> jQuery('.popup-trigger a').hover(function(){ jQuery(this).trigger('click'); }); </script>

Estou com o mesma dúvida. Poderia me ajudar na solução?

**Comment by htmlswift** [comment]
@ChristianZamboni hi, what is your website and what is your requirement exactly?
