### ISSUE TITLE
Heading font, style and other settings show when i press preview, but disappear once i hit "update"

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#7518]
I couldn't find an open issue describing this.

I've tried using multiple different heading elements to try to make a custom heading, the default included. Any changes i make appear inside the editor. If i click the preview(eye) icon at the bottom left next to the update button, it opens a preview of the page and the heading is displayed correctly with the typography settings i have specified: with the font i have selected, the size, italics/bolding/underline, weight etc.

When i press update and then view the page, the heading changes i've made simply do not appear. It simply resets to the defaults as if i had changed nothing. Everything i actually have done remains on the editor, but the live site simply never updates with any custom styles. I've tried changing to a bunch of different fonts, moving the location of the element, and adjusting tons of other settings. Nothing i do seems to fix this. 

This bug is affecting all of my pages. I effectively cannot change any heading settings whatsoever. I do not know if this is the first version of the editor to contain this bug, this is the first time i have run into this issue.

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by jazir5** [comment]
This is a bug report, not a support request @shilo-ey
