### ISSUE TITLE
Elementor lightbox - Navigation Elements missing in WordPress Gallery

### ISSUE THREAD

**Issue by Netzlichter** [elementor/elementor#7519]
I added a WP Gallery block to a post.

Elementor applies a lightbox to the images. The Lightbox of Elementor basically just replaces the default functionality for when clicking an image in the gallery. Here is a short video for your reference:
https://www.useloom.com/share/7791e7675165483e8ad335524cb8f50e

Currently the navigation functionality is missing on the lightbox of the WP Gallery block.

Would be great if you can add the navigation arrows to the normal WordPress gallery in posts.

Thanks for your great work :)!

**Comment by fxaviers** [comment]
I has open a issue for this almost after one year ago. #5231
No one response.

**Comment by MichaelDarko** [comment]
+1 I had to install some other crappy lightbox plugin just to have the arrows functionality. You really should add this essential thing. What's the point of having Elementor lightbox if you can't use it for galleries?

**Comment by freedomalone** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.9.1

Feel free to update

Thanks!

**Comment by sano7** [comment]
Hallo,

I cannot see that it is working. I habe Elementor 3.1.4.

**Comment by caspervoogt** [comment]
I am using 3.14.0 (pro) and the lightbox navigation links are missing when I use the a Gallery widget. This should be reopened.
