### ISSUE TITLE
Hide elements after X seconds

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#7520]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hide an element (image, text box etc...) after a given amount of time, for example 10 seconds.

**Describe the solution you'd like**
In every elements options, have a settings to enable "hide element after x seconds"

**Describe alternatives you've considered**

**Comment by shilo-ey** [comment]
Hi @elasticeye 


You can achieve this by using custom JS:

```JS
$ = jQuery;
$( document ).ready(function(){
	$('#hide').fadeIn('slow', function(){
		$('#hide').delay(5000).fadeOut(); 
	});
});
```

Simply add the ID `hide` to each element you want to hide and alter the delay parameter for the miliseconds you wish to wait before hiding the element.

Thanks.

**Comment by Clubware** [comment]
I would like this feature as well.

**Comment by AjayS21** [comment]
> hide

Can you give code in this similar way to show the element after few seconds?

**Comment by bagiak** [comment]
> Can you give code in this similar way to show the element after few seconds?

You can just add a Motions Effect -> Animation and apply Animation Delay, in Elementor :)
