### ISSUE TITLE
elementor-hello-theme: Cannot get custom css to work

### ISSUE THREAD

**Issue by GlennBonde** [elementor/elementor#7522]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

Hello,   I have installed and activated the elementor-hello-theme. I want to use my own definitions of e.g h1-h6 site wide and for that purpose I have tried to follow the directions under Style on https://github.com/elementor/elementor-hello-theme/blob/master/README.md

I have created the file comexpert.scss and there I have put all custom css code. In the file _custom.scss, in the same folder, I have added @import "custom/comexpert.scss";   I cannot seem to get it to work. Am I doing something wrong or is this a bug?      

I would also like to add custom css-tags, e.g titel in the css-file and have them   show in the dropdown list in the elementor text editor. Is that possible?

Thanks   Glenn
--

## Steps to reproduce

Please see above under Description

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [N/A] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.49-MariaDB-38.0
	PHP Version: 7.2.10
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://comexpert.eu
	Home URL: https://comexpert.eu
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 96M
	Permalink Structure: /%category%/%postname%/
	Language: sv-SE
	Timezone: 1
	Admin Email: glenn.bergvall@comexpert.se
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: sv_SE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

== Active Plugins ==
	Elementor
		Version: 2.5.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

== Log ==
	: <table><thead><th>JS: showing 2 of 2</th></thead><tbody class="elementor-log-entries"><tr><td>JS: 2019-03-15 15:37:58 [error X 18][https://comexpert.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.8:2:65734] <strong>Ogiltigt argument.</strong> </td></tr><tr><td>JS: 2019-03-15 16:10:20 [error X 1][https://comexpert.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.8:2:75360] <strong>setting getter-only property \&quot;type\&quot;</strong> </td></tr></tbody></table><table><thead><th>PHP: showing 1 of 1</th></thead><tbody class="elementor-log-entries"><tr><td>PHP: 2019-03-15 15:40:45 [notice X 2][/storage/content/68/146368/comexpert.eu/public_html/wp-content/plugins/elementor/includes/template-library/manager.php::232] <strong>Undefined index: types_data</strong> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]</td></tr></tbody></table>

**Comment by nuritsha** [comment]
Hi @GlennBonde,

Thank you for reporting, 
After adding new scss code, the theme needs to be re-built, using `grunt`.

(In the future, please open Elementor-Hello-Theme issues in the theme's repo)

Thanks

**Comment by GlennBonde** [comment]
Hi @nuritsha,
First of all, I appologize for not opening this follow-up question in the theme's "repo". I cannot seem to find a way to post there.
I have done some searching on how to re-build the theme using grunt but have so far not found any conclusive info. Would you be so kind as to point me to some helpful documentation.
Thanks

**Comment by nuritsha** [comment]
Hi @GlennBonde,

in general, you should run:
```
npm install
npm i grunt-cli
grunt styles
```

Thanks
