### ISSUE TITLE
Missing eicons Icons in Multisite Subdomain Setup

### ISSUE THREAD

**Issue by StefanS-O** [elementor/elementor#7524]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I have a Wordpress Multisite Installation using subdomains. On the main url everything works as expected. If i switch to a network subsite wp-admin all icons from Elementor are missing.
This happens in the Wordpress Sidebar as well as in the Elementor Editor.

I see some errors in the Network tab of chrome, where eicons are not being loaded from the main domain with net:ERR_FAILED. When i copy the whole url from the network tab and paste it in the browser, the file loads correctly.

Maybe it has something to do with x-origin settings?

I think it is the same issue described in the Wordpress Support Forums:

https://wordpress.org/support/topic/dont-load-in-multisite-domain-mapping/

I am also using Bedrock: https://roots.io/bedrock/
I don't think it is Bedrock related, but if it helps i could just install Wordpress normally and check again.

It seems to work on Safari though. Only Chrome and Firefox seem to block eicons.ttf

## Steps to reproduce

1. Install Wordpress and Enable Multisite with Subdomains
2. Create New Network Site
3. Switch to New Network Site and Enable Elementor and Elementor Pro
4. Activate License
5. Icons are missing

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.25
	PHP Version: 7.2.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://***.***.**/wp
	Home URL: https://***.***.**
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com


== Network Plugins ==
	Elementor
		Version: 2.5.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.0
		Author: Roots

	Disallow Indexing
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Log ==
	: 

				
```
</details>

**Comment by StefanS-O** [comment]
Update: i have tested it using normal Wordpress MU setup and everything works. Seems to be related with roots.io bedrock. Sorry :)

**Comment by fabienlege** [comment]
Same issue for me with bedrock.

@StefanS-O have you found any solution ?

**Comment by StefanS-O** [comment]
@fabienlege as far as i can remember i didn't use roots.io bedrock and stuck to the normal Wordpress MU installation

**Comment by fabienlege** [comment]
Ok, For everyone who get here to searching a solution for the same problem I post here a fix I've found for bedrock : 

in file /config/application.php find this line : 
``` Config::define('WP_CONTENT_URL', Config::get('WP_HOME') . Config::get('CONTENT_DIR')); ```

Delete and replace this line by :
```Config::define( 'WP_CONTENT_URL', ( $_SERVER['HTTPS'] ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . Config::get( 'CONTENT_DIR' ) );```

With this fix, Wordpress use your site domain (instead of network root domain) for loading assets. that solve CORS problem since css files has loaded from same domain
