### ISSUE TITLE
Newly saved global templates stopped appearing in pink Elementor Editor global pane - Using Elementor Canvas Template

### ISSUE THREAD

**Issue by stefancaliaro** [elementor/elementor#7527]
Hi there,

Not sure if this is the same issue as this closed issue (https://github.com/elementor/elementor/issues/5289), but it feels related.

I contacted Elementor Support and they said to raise a github request.

**Prereqs:**

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro). (I have a bunch of plugins, testing each one will be a tedious task, however this seems more structurally Elementor code based related. (I've  been working in IT for over 5 years).
- [ ] This bug happens with a default WordPress theme active. (Pretty sure the theme doesn't affect this, since I always used Astra for a long time and the issue wasn't there the whole time I had Astra active).
- [x] I can reproduce this bug consistently using the steps below.

**The issue:**

I've **noticed my global templates save, but have recently stopped appearing in Elementor Editor under global** when I need to use them to drag and drop onto Elementor Canvas.

My **new global templates still appear in My Templates prompt** (when I right click and hit Save as Template) **AND in WordPress dashboard** under (Elementor) Templates > Saved Templates **but they do not appear in Elementor editor under global**, why is this? I'm using Elementor Canvas too like the poster in the issue linked above. **This is a HUGE bug**. Please fix. It was working up until a point. Maybe up until 10 or so saved global templates was the bug trigger?

I've updated to the latest Elementor (Version 2.5.9) and Elementor Pro (Version 2.4.8) too. I've always been using the Astra theme and it was working before with this theme. I'm using Elementor Canvas though so I don't even touch the WordPress native active theme.

**Screenshots:**

<img width="1343" alt="Screen Shot 2019-03-19 at 04 35 39" src="https://user-images.githubusercontent.com/4954497/54551782-d9719380-4a02-11e9-9a29-ab725a894e48.png">
<img width="1612" alt="Screen Shot 2019-03-19 at 04 27 19" src="https://user-images.githubusercontent.com/4954497/54551783-d9719380-4a02-11e9-894d-c54aa735a630.png">
<img width="357" alt="Screen Shot 2019-03-19 at 04 26 26" src="https://user-images.githubusercontent.com/4954497/54552387-0ffbde00-4a04-11e9-8666-ac0b1de7e88b.png">

**System Info:**

== Server Environment ==
Operating System: Linux
Software: Apache **(I'm using Nginx from GCP - Nginx for WordPress Bitnami Marketplace Image - not sure why it says Apache by default, maybe it couldn't detect Nginx).**
MySQL version: MySQL Community Server (GPL) v5.7.22
PHP Version: 7.0.30
PHP Max Input Vars: 1000
PHP Max Post Size: 40M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 5.1.1
Site URL: https://siteroo.com.au
Home URL: http://siteroo.com.au
WP Multisite: No
Max Upload Size: 40 MB
Memory limit: 268435456
Permalink Structure: /notebook/%postname%/
Language: en-AU
Timezone: Australia/Sydney
Debug Mode: Inactive

== Theme ==
Name: Astra
Version: 1.7.2
Author: Brainstorm Force
Child Theme: No

== User ==
Role: administrator
WP Profile lang: en_AU
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
All In One SEO Pack
Version: 2.12
Author: Michael Torbert

AnyWhere Elementor Pro
	Version: 2.11
	Author: WebTechStreet

Disqus for WordPress
	Version: 3.0.17
	Author: Disqus

Drift
	Version: 1.8.4
	Author: Drift

Elementor
	Version: 2.5.9
	Author: Elementor.com

Elementor Pro
	Version: 2.4.8
	Author: Elementor.com

Google Analytics Dashboard for WP (GADWP)
	Version: 5.3.7
	Author: ExactMetrics

Gutenberg
	Version: 5.2.0
	Author: Gutenberg Team

Gutenberg Blocks and Template Library by Otter
	Version: 1.1.5
	Author: ThemeIsle

Image optimization service by Optimole
	Version: 2.0.4
	Author: Optimole

Open Graph for Facebook, Google+ and Twitter Card Tags
	Version: 2.2.5
	Author: Webdados

Orbit Fox Companion
	Version: 2.7.5
	Author: Themeisle

Really Simple SSL
	Version: 3.1.5
	Author: Rogier Lankhorst, Mark Wolters

SOGO Add Script Header Footer
	Version: 3.2
	Author: orenhav (SOGO)

SSL Insecure Content Fixer
	Version: 2.7.2
	Author: WebAware

Sucuri Security - Auditing, Malware Scanner and Hardening
	Version: 1.8.20
	Author: Sucuri Inc.

TinyMCE Advanced
	Version: 5.1.0
	Author: Andrew Ozz

Visualizer: Tables and Charts Manager for WordPress (Lite)
	Version: 3.1.3
	Author: Themeisle

W3 Total Cache
	Version: 0.9.7.2
	Author: Frederick Townes

Wordfence Security
	Version: 7.2.3
	Author: Wordfence

WPForms Lite
	Version: 1.5.1.3
	Author: WPForms

WPFront Scroll Top
	Version: 2.0.1
	Author: Syam Mohan

WP Hotjar
	Version: 0.0.3
	Author: Thiago Guimarães

WP Product Review Lite
	Version: 3.5.2
	Author: ThemeIsle

WP Super Cache
	Version: 1.6.4
	Author: Automattic
**== Log ==**
:
Log: showing 4 of 42019-03-09 22:26:57 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '2.3.8',
'to' => '2.5.3',
)]
2019-03-10 17:26:28 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '2.1.11',
'to' => '2.4.7',
)]
2019-03-19 03:29:08 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '2.5.3',
'to' => '2.5.9',
)]
2019-03-19 03:30:21 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '2.4.7',
'to' => '2.4.8',
)]

JS: showing 6 of 6JS: 2019-03-10 15:04:06 [error X 4][https://siteroo.com.au/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.4.7:2:11221] this.$element.sticky is not a function
JS: 2019-03-10 15:06:03 [error X 31][https://siteroo.com.au/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.5.3:2:14761] e.elementorWaypoint is not a function
JS: 2019-03-10 15:20:40 [error X 4][https://siteroo.com.au/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.4.7:2:73510] e.slick is not a function
JS: 2019-03-10 15:47:26 [error X 1][https://siteroo.com.au/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: "view682") has already been destroyed and cannot be used.
JS: 2019-03-10 18:04:52 [error X 4][https://siteroo.com.au/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: "view911") has already been destroyed and cannot be used.
JS: 2019-03-18 16:37:04 [error X 67][https://siteroo.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.3:2:238680] Cannot read property 'statusText' of undefined

**Please fix, thank you, much appreciated!** :) 
![Uploading Screen Shot 2019-03-19 at 04.26.26.png…]()

**Comment by shilo-ey** [comment]
Hi @stefancaliaro 

The "Save As Template" action does not refer to the global widgets. 
The Global widgets are widgets that share common settings across the site. [see here](https://docs.elementor.com/article/100-global).

Save using "Save as Global" and you should see the global widget in the panel.
![image](https://user-images.githubusercontent.com/45009641/54595315-093c8d80-4a3b-11e9-958d-aff384f53418.png)


Thanks.
