### ISSUE TITLE
Enable the ability to directly preview the mobile view and interact with all elements

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#7529]
SImilar issue here: https://github.com/elementor/elementor/issues/1861

My problem: If i hit preview icon next to update in the bottom of the sidebar while in the mobile editor view:
![preview](https://user-images.githubusercontent.com/31750063/54559094-750bf100-497c-11e9-9402-2aa0b86855db.PNG)

It jumps straight to the desktop when it opens the preview in a new tab. I would like the preview button to be contextual to the responsive editor mode. If i'm in the tablet editor view for instance and i click preview, i would like a preview to open in a new tab as if i was viewing it on an iPad, in the same aspect ratio as the ipad is in the actual elementor editor for that responsive view mode(Tablet or mobile).

In the referenced issue, @arielk says to close the editor via the sidebar panel arrow to collapse the panel. I have done so, but i am unable to interact with and trigger the mobile nav menu element in the editor. I have to make the page live and visit it from a mobile device to be able to test the menus functionality and see what the actual design of the hamburger menu looks like when i open it.

![mobile editor](https://user-images.githubusercontent.com/31750063/54560920-abe40600-4980-11e9-9e0c-3b134cbba02a.PNG)

I have no way to see what the interior of it looks like without actually opening the page on a mobile device.

**Comment by stefancaliaro** [comment]
Also sometimes just recently when I hit update it updates but the button remains green as if there's more to save but there isn't.

**Comment by shilo-ey** [comment]
Hi @jazir5 

This is how Elementor works if you want to preview the page without collapsing the panel, open it in a new tab and emulate a mobile device.

Thanks.
