### ISSUE TITLE
Animated Headline Element will not center align in column

### ISSUE THREAD

**Issue by daddylogan** [elementor/elementor#7532]
Dragging an ANIMATED HEADLINE ELEMENT into a column that is set to center content, the element snaps to TOP ALIGN and not middle. I tested on Elementor 2.4.7 and Pro 2.4.4 - I passed the error onto a top level community member who is using all Elementor "up-to-date" plugins and he recreated the same issue and told me to report here.

This is how I created the section with issue:

1) Create a new section with with 2 columns.  Columns and Content set to middle and min. height set to 200 - set style bg color to rgba(45,90,175,0.87) and zero out padding and margins.

2) Set column 1 to middle content and zero out margins only. Do the same for column 2

3) Drag a button into right column, Set as large and center align.

4) Drag ANIMATED HEADLINE ELEMENT into left column. (now this is where you should see the issue if it is a bug. It will not center up but top align on it's own) - I set text at 36 px and align left.

At STEP 4 it will not align center. Can be set to center by changing the HTML Tag to "div" instead of default of H3 - but this only solves on a desktop. Tablet and mobile will not center up. The "before" text will but the "animated" text will not.

**Comment by shilo-ey** [comment]
Hi @daddylogan 

This issue origins from your theme's CSS settings.

I can recreate this behavior, but when I disable the margin top and bottom specifically for this widget - the issue resolves.

Try adding this to your theme's CSS file:
```CSS
.elementor-widget-animated-headline h3.elementor-headline {
    margin: 0;
}
```

or directly to your widgets Custom CSS:
```CSS
selector h3.elementor-headline {
    margin: 0;
}
```

Thanks

**Comment by daddylogan** [comment]
Hi,

Thank you for replying. However your solution only solves 1/3 of the issue.

I do use the Astra basic theme and your CSS corrected the issue in centering it within the “column” and viewing on a desktop when all on “ONE LINE”

However when you switch to tablet mode or mobile phone (where the text will wrap – and this would be most cases since this feature is used with mostly sentences) and you then switch the “align” to center (so the text will stack up nicely) only the BEFORE text aligns properly. The animated text itself does not inherit the centering and stays LEFT ALIGNED. Basically it renders horribly in tablet and mobile mode.

I very much appreciate you looking into this and I think it needs to go a bit deeper to resolve completely.

Please keep me updated and thank you again.

Mike (daddylogan)
