### ISSUE TITLE
How to execute PHP code on Document Settings custom controls?

### ISSUE THREAD

**Issue by Paras16699** [elementor/elementor#7533]
I added a `SELECT` control to the document using the hook `elementor/element/post/document_settings/after_section_end`.

Now, on change to the `SELECT` value, I would like to run PHP code to modify the page query and reset it back to normal.

In case of a widget, I would be able to do it using the `before_render` and `after_render` functions, but when I try to do it with the Document Settings with these hooks `elementor/element/post/document_settings/before_render` and `elementor/element/post/document_settings/after_render`, they don't work. 

Even after a manual reload, the page settings are appearing fine but the before and after render codes are not working. So, I guess there aren't any such hooks.

Any help regarding this would be much appreciated. @bainternet, @shilo-ey

**Comment by shilo-ey** [comment]
@Paras16699 

Document settings don't work like widgets, so you would have to catch the change event, trigger an AJAX request to run your PHP code, and once the response is returned you can reset it back to normal (or whatever it means).

Thanks
