### ISSUE TITLE
Video does not auto play with lightbox, Absolute positioning doesnt work in rtl, popup forms not integrating with hubspot, popup close button horizontal control not working

### ISSUE THREAD

**Issue by alonep1** [elementor/elementor#7534]
Tried contacting ele support but no respond, so might aswell report here the bugs.
-->

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

 First issue - 
       For some reason auto play in the video widget is not working with a lightbox, I want the 
       video to auto play after someone clicks on the photo, but instead it takes two clicks to start 
       the video.

 Second issue-
        Absolute positioning does some funky thing on an rtl client.
        It kinda works in reverse (puting an element in the far right would place it on the far left - 
        adding a video to demonstrate)

        https://www.useloom.com/share/44b6696a79df4a11b23e5090c8356821

  Third issue-
        I have a form in a popup, and when trying to make it integrate with hubspot, the normal 
        forms on the page work but the popup form doesnt, the system dont recognize it at all.

   Forth issue-
         Popup close button horizontal placement controll doesnt work.

## Steps to reproduce

Have an rtl client, doesnt matter what theme

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v5.6.42-84.2 |  
PHP Version: | 7.0.33 |  
PHP Max Input Vars: | 10240 |  
PHP Max Post Size: | 24M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  


```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* One issue per thread

Thanks.

**Comment by alonep1** [comment]
With the amount of bugs currently in elementor , I can't be bothered creating a different thread per issue.

**Comment by alonep1** [comment]
> Thanks for reporting,
> Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
> This report is missing key information:
> 
> * One issue per thread
> 
> Thanks.
With the amount of bugs currently in elementor , I can't be bothered creating a different thread per issue.
