### ISSUE TITLE
Request for Disabling or Customizing Scroll 2 ID

### ISSUE THREAD

**Issue by rconcrown** [elementor/elementor#7539]
## Prerequisites

- [ ] I'd like an option to disable linear elementor scroll to id. I want to handle this myself or have an option to handle this myself.

**What problem is your feature request going to solve? Please describe.**
It will help making the site more customizable.

**Describe the solution you'd like**
Smoothscroll Settings

**Describe alternatives you've considered**
Tried editing the core files, but thats a stupid solution

**Comment by shilo-ey** [comment]
Hi @rconcrown 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by black-eye** [comment]
+1
