### ISSUE TITLE
How to activate the tabs menu from mainmenu of WordPress ?

### ISSUE THREAD

**Issue by arnoldkiti** [elementor/elementor#7546]
Hello everyone,

In my test website I try to selected my tabs title by clicking on my mainmenu.
See (https://ak-webserver.000webhostapp.com/services)

Best regard,
Arnold K.

**Comment by shilo-ey** [comment]
Hi @arnoldkiti 

Add this JS inside an HTML element:
```HTML
<script>
jQuery( document ).ready( function( $ ) {
	// Check if we need to activate a tab based on the has
	if ( window.location.hash && $( window.location.hash ).length ) {
		$( window.location.hash ).click();
	}
} );
</script>
```

The menu items should be the unique id of each tab.

See more here: #7207

**Comment by arnoldkiti** [comment]
Hi @shilo-ey I use an extension Custom JS /CSS for my script JS and CSS.
Can I put  this code in this extension. I think is better.

**Comment by lordaker** [comment]
Hi @shilo-ey You tell me to put this code in an HTML Element. It's a JS Code. 
I use the extension Custom JS/CSS for my custom JS and CSS code.
