### ISSUE TITLE
Image in the post can not be align center if it has caption

### ISSUE THREAD

**Issue by jmf3** [elementor/elementor#7548]
Hello, 
There is a bug in Elementor Pro.  An Images in WP posts can be align to left, center and right. A Align works   as expected, BUT the bug appears if the IMAGE has filed CAPTION.    how to induce bug.   
1) create template "single post page" in elemetor. 
2) create post in wordpress, insert some text and add image (linked to url)   
4) do not fill caption and alternative text   
5) align image to center. In backend and frontend you will see image align to center.  
6) BUG - let everything as is and fill caption and alternative text. In backend you still see image align to center (with caption under image), but   in frontend there will be image align to left.  If I will deactivate Elementor Pro, the image is align to center on backend and frontend too.
url: https://moraviantravelers.cz/renovace-hotelu-monte-palace/

Information from Elementor support team:
I can see the issue and I have identified the CSS that causes it (http://prntscr.com/n01cyd). Unfortunately, this will require the intervention of our development team. You could post this to our GitHub project and our developers will provide you with the CSS needed to correct this issue. Via this support channel, we are not able to provide CSS or custom code. We appreciate your patience and understanding.

I hope, that you got all necessary information.

**Comment by shilo-ey** [comment]
Thanks!

I merged this issue with #7331, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Talco100** [comment]
Any update on this bug?

**Comment by jmf3** [comment]
> 
> 
> Any update on this bug?

Hi,
I got this help from netpasja:

For wordpress gallery margins this works great:
.single-post .gallery-icon { margin: 5px; }

I pasted it into theme css.
This helps me.

**Comment by buithucdong** [comment]
Hi, 

You can try my code below: 

.elementor-element .wp-caption{
	margin-right: auto!important;
	margin-left: auto!important;
}
