### ISSUE TITLE
Can't create or edit Popups

### ISSUE THREAD

**Issue by JourneysCT** [elementor/elementor#7549]
I have not changed anything except to install the Version 2.5.0-beta1 yesterday and now Version 2.5.0-beta2  today. I did not try anything with the Popup feature with the Beta1, but today I did. It will not allow me to edit any popups, but I can still edit pages.

I hope this information is helpful. 
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://journeysgp.walnutcreekhoa.com
	Home URL: https://journeysgp.walnutcreekhoa.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Denver
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.2.2
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.87
		Author: ServMask

	Analytify - Google Analytics Dashboard
		Version: 2.2.10
		Author: Analytify

	Central Color Palette
		Version: 1.13.6
		Author: Gáravo

	Code Snippets
		Version: 2.13.3
		Author: Shea Bunge

	CSS Hero
		Version: 3.41
		Author: The CSS Hero Team

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Easy Theme and Plugin Upgrades
		Version: 2.0.1
		Author: Chris Jean

	Elementor
		Version: 2.5.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.0-beta2
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.18
		Author: Till Krüss

	Envato Elements - Template Kits (Beta)
		Version: 0.1.7
		Author: Envato

	Flexible Elementor Panel
		Version: 1.9.2
		Author: Flexible-Elementor-Panel.com

	GP Premium
		Version: 1.8.0-alpha.1
		Author: Tom Usborne

	JetBlocks For Elementor
		Version: 1.1.4
		Author: Zemez

	JetBlog For Elementor
		Version: 2.1.10
		Author: Zemez

	JetElements Dynamic Data Addon
		Version: 1.1.0
		Author: Zemez

	Jet Elements For Elementor
		Version: 1.15.5
		Author: Zemez

	Jet Plugins Wizard
		Version: 1.2.1
		Author: Zemez

	Jet Popup
		Version: 1.2.5
		Author: Zemez

	JetTabs For Elementor
		Version: 1.1.6
		Author: Zemez

	JetThemeCore
		Version: 1.1.8
		Author: Zemez

	JetThemeCore Compatibility Kit
		Version: 1.1.0
		Author: Zemez

	Make Column Clickable Elementor
		Version: 1.2.0
		Author: Fernando Acosta

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	TRO Brochure Rack
		Version: 1.0
		Author: Travel Research Online

	UpdraftPlus - Backup/Restore
		Version: 1.16.8
		Author: UpdraftPlus.Com, DavidAnderson

== Must-Use Plugins ==
	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== Log ==
	: 
Log: showing 20 of 402019-03-18 14:59:41 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-18 14:59:41 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-18 14:59:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.0-beta1',
)]
2019-03-19 14:59:09 [info] elementor-pro::elementor_pro_updater Started 
2019-03-19 14:59:09 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-19 14:59:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.0-beta1',
  'to' => '2.5.0-beta2',
)]
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-19 14:59:10 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-19 14:59:11 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-19 14:59:11 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-19 14:59:11 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-19 14:59:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.0-beta1',
  'to' => '2.5.0-beta2',
)]

JS: showing 2 of 2JS: 2019-03-19 21:00:13 [error X 8][https://journeysgp.walnutcreekhoa.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.5.0-beta2:2:23758] this.countTimes is not a function 
JS: 2019-03-19 21:00:35 [error X 1][https://journeysgp.walnutcreekhoa.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.9:2:83373] Cannot set property \'controls\' of undefined

**Comment by bainternet** [comment]
@JourneysCT 

thanks for reporting,  will be fixed shortly. for any other issue related to current beta please use the [beta thread](https://github.com/elementor/elementor/issues/7526) and follow it for updates.

thanks.

**Comment by daniele77ba** [comment]
I've got suddenly the Same issue from elementor 2.9 Beta but ONLY on my iMac. Everything on my MacBook seems to work properly...
![Schermata 2020-02-11 alle 23 37 07](https://user-images.githubusercontent.com/60903894/74287353-0d942800-4d2a-11ea-864b-f436fc0757b8.png)
