### ISSUE TITLE
[PRO] Add a filter to change default form submission email address

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7551]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Feature

In the file `elementor-pro\modules\forms\actions\email.php`, you preset the default value and placeholder of the `email_to` field with the admin email address using `get_option( 'admin_email' )`.

Can you add a WordPress filter on this value so we can change it? On many customers website, the admin email address is ours but we want to use our customer email address for form submissions.

**Comment by bainternet** [comment]
@tristanleboss 

It's a WordPress native function which means (most of the times) there are action and filter hooks in place already and in this case `option_admin_email` filter hook.

The only problem is identifying where the call for it is coming from. 
ex:

```PHP
add_filter( 'option_admin_email', function( $value ) {
    $caller = debug_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS, 4 );
    if ( isset( $caller[3] ) && isset( $caller[3]['file'] ) && false !== strpos( $caller[3]['file'], 'forms/actions/email') ) {
        //this is most likly comming from elementor pro forms module
        //so you need to return tclients email 
        return 'other@email.com';
    }
    // default value
    return $value;
} );
```

this is not the best solution but it should work just fine.

thanks.

**Comment by tristanleboss** [comment]
@bainternet Thanks. I already do that but it's really uggly...

Having a filter cost nothing on both performance and development sides, it's too bad you closed the issue :(
