### ISSUE TITLE
[PRO] Convert the form redirect URL field to a dynamic one

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7552]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Feature

I feel like the `redirect_to` field of the `elementor-pro\modules\forms\actions\redirect.php` file (the `Redirect` action for a form) would be so much better if it was a dynamic URL field as introduced by https://github.com/elementor/elementor/issues/255#issuecomment-406346596

Often, customers want to set a thank you page and having to copy/paste its url is so complicated.

Can you convert this field to a dynamic URL one with autocomplete like everywhere else in Elementor?

**Comment by bainternet** [comment]
@tristanleboss 

Currently, this is not possible because the form "Redirect To" field is a text field and can only accept Text dynamics and the autocomplete Works on URL fields.

thanks.

**Comment by tristanleboss** [comment]
@bainternet Why can't we convert it to an URL field? What's the point of having a text field for an URL?

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by drawcard** [comment]
Currently running Elementor 2.7.3 / Pro 2.7.0 and this feature doesn't seem to be working:

![image](https://user-images.githubusercontent.com/1435638/66100167-f198b100-e5e8-11e9-87d3-d88a4c1112eb.png)

**Comment by drawcard** [comment]
Sorry - just realised my enquiry is slightly different - the Dynamic URL function is there, but I can't type in a page name and have the autocomplete guess which page I am referring to.

Do I need to open a new issue @shilo-ey @bainternet ?
