### ISSUE TITLE
Extras Tooltip needs unique ID per instance on a single page

### ISSUE THREAD

**Issue by collindavis** [elementor/elementor#7555]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using the Extras > Tooltip feature within a Loop template, it uses the same ID for the element. The result is multiple tooltips using the same values on the page wherein multiple Loop templates display different post data.

## Steps to reproduce

Create a single template. Assign a tooltip element with dynamic data coming from a custom field.
Create a page with Posts widget and use the Single template. Query posts that contain custom data that's assigned to tooltip. Make sure the data for each tooltip is different for each post.
Preview page and hover/click each tooltip. The data will be the same for every post instead of unique to the data that's specific to the post.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.36-83.0
	PHP Version: 7.1.26
	PHP Max Input Vars: 3000
	PHP Max Post Size: 55M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.9
	Site URL: https://ncs.cartender.co
	Home URL: https://ncs.cartender.co
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.2.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Ele Custom Skin
		Version: 1.0.9
		Author: Liviu Duda

	Elementor
		Version: 2.5.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

== Must-Use Plugins ==
	closte-requirements.php
		Version: 
		Author: 

		
```
</details>

**Comment by shilo-ey** [comment]
Hi @collindavis 
Please explain what are you referring to?

Elementor does not have any tooltip or loop elements.

Thanks.

**Comment by collindavis** [comment]
Elementor allows you to setup a Single template which can then be looped through using Posts widget.

Elementor has an Extras property for Tooltip I thought? I’m using it with a button. I believe this is a newer feature?

**Comment by bainternet** [comment]
@collindavis 	

This is not something native to Elementor or Elementor Pro, it's a 3rd party plugin.

thanks.
