### ISSUE TITLE
Elementor Pro for Prestashop

### ISSUE THREAD

**Issue by mk1salami** [elementor/elementor#7556]
Hi All. First time posting on Github! I've been using Elementor Pro on Wordpress but have gone with a different direction and using Prestashop. I have a version of Elementor 

Hi all. I bought the Pro version of Elementor for Wordpress. Since then I've changed direction and I'm using   Prestashop 1.7.5 for my website. I bought the Warehouse theme which comes bunded with a version of Elementor but doesn't seem as fully featured as that on Wordpress.       For example, I'd like to use a countdown timer feature, which is simply not there on the Prestashop version. Can you help?

**Comment by bainternet** [comment]
Elementor and Elementor Pro officially build and work only in WordPress, we have no relation nor are we affiliated in any way with "Warehouse theme" creators.

please contact them for help. 

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details but again anything now WordPress related they can't really help.


thanks.

**Comment by HartLarsson** [comment]
so this is not a plugin for prestashop officially developed by you? https://addons.prestashop.com/it/amministrazione/44064-creative-elements-elementor-based-pagebuilder.html

it uses your code and your interface.
