### ISSUE TITLE
Fatal Error with Gutenberg plugin v5.3.0 because of deprecated/removed function

### ISSUE THREAD

**Issue by deckerweb** [elementor/elementor#7557]
The function `gutenberg_can_edit_post_type()` from the Gutenberg plugin was deprecated with 5.1.0 and now got removed in 5.3.0 of the plugin. See: https://github.com/WordPress/classic-editor/issues/87

You should switch to the WP Core function `use_block_editor_for_post_type()`

This effects the file` /elementor/includes/compatibility.php`, L54, as of Elementor 2.5.9:
Change:
`! gutenberg_can_edit_post_type( $typenow )`
to:
`! use_block_editor_for_post_type( $typenow )`

**Comment by bainternet** [comment]
Thanks for reporting.

should be fixed in next version.

**Comment by shilo-ey** [comment]
Hi @deckerweb 

This issue has been fixed in v2.5.10

Feel free to update!
