### ISSUE TITLE
Media Carousel / Image Gallery Lightbox - Dragging on arrows causes wrong behavior

### ISSUE THREAD

**Issue by JeffPlo** [elementor/elementor#7561]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor Pro.

## Description

After clicking on arrow (left or right) and dragging some pixels away, the slide moves in the same direction. For example: clicking on right arrow an move the mouse to the right, causes the slider to slide to the right and not to the left.

## Steps to reproduce

- Click on arrow
- Hold mouse button down
- Move the mouse some pixels to the left or right
- Release mouse button
- The slider slides in the same direction as a mouse move

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active (Twenty Nineteen).
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: MySQL Community Server (GPL) v5.7.25
	PHP Version: 7.3.3
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received)

== WordPress Environment ==
	Version: 5.1
	Site URL: http://localhost:8000
	Home URL: http://localhost:8000
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

== Log ==
	: 

</details>

**Comment by shilo-ey** [comment]
Hey @JeffPlo 

This is how the slider acts in drag interaction.

See more [here](https://idangero.us/swiper/demos/) (based on Swiper library).

Thanks.

**Comment by JeffPlo** [comment]
Swiping on images is nice, but not on arrows. I think the arrows should be excluded from swipe. Our graphic designers have this problem with drawing pads. I imagine old people have difficulty using it too.

**Comment by JeffPlo** [comment]
I found a workaround to disable this behavior:

if (typeof Swiper === 'function') {
  Swiper.defaults.noSwipingClass = 'elementor-swiper-button';
}
