### ISSUE TITLE
Connect "counter" element with social media platforms: e.g. if you have 1,340 likes on Facebook, then the counter would show that, and update automatically.

### ISSUE THREAD

**Issue by Svarmind** [elementor/elementor#7563]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Svarmind** [comment]
I have seen something like this on other wp sites, but not with elementor.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your request, this is already possible in Elementor Pro [Share Buttons Widget](https://docs.elementor.com/article/206-share-buttons)

thanks.
