### ISSUE TITLE
[Bug beta] Filtering posts by source: current query not working for product archive

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#7568]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
It's working ok in Elementor 2.4.8 – the issue is happening in Pro 2.5.0-beta2 (and I don't know where to post this issue.

## Description

Filtering posts by source: current query is not working for product archive in Pro 2.5.0-beta2.

## Steps to reproduce

Create post widget and set source to current query:
![current-query](https://user-images.githubusercontent.com/17693529/54720259-bdbed800-4b3d-11e9-8dfa-53ec49cd647d.jpg)

Create a product category and click to view it:
![click-category](https://user-images.githubusercontent.com/17693529/54720282-cc0cf400-4b3d-11e9-8809-1327ac1e4bd5.jpg)

No results appears in 2.5.0-beta2:
![no-results](https://user-images.githubusercontent.com/17693529/54720299-d7f8b600-4b3d-11e9-8b97-5af62d40d993.jpg)

It's fine on Elementor Pro 2.4.8:
![working-fine](https://user-images.githubusercontent.com/17693529/54720469-4178c480-4b3e-11e9-9464-3e84cfb86d55.jpg)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Artneo7 

Elementor Posts widget doesn't show the price/category meta.

Please explain how it works in 2.4.8, if there's no option to show the product meta inside the Posts Widget.

Thanks

**Comment by Artneo7** [comment]
I created using Ele Custom Skin (https://www.eletemplator.com/ele-custom-skin/). Maybe this plugin is optimize for the stable version 2.4.8 only, and that's why it's not working yet in beta versions. I know you guys can't help in the support of third party plugins, but now I see what could be happening. Thanks for the support!
