### ISSUE TITLE
Page Templates Overwriting Gutenberg Video Embed Width

### ISSUE THREAD

**Issue by JeremyL** [elementor/elementor#7571]
I am using the theme builder to design my pages and inserting the Gutenberg edited posts into the design. 

Elementor seems to be overwriting the video embed width that Gutenberg is properly setting, specifically for YouTube in my case. 

If I embed a video on a post without an Elementor template, it looks like this. 

![image](https://user-images.githubusercontent.com/4141/54730845-07530580-4bc6-11e9-813d-e452964a5ac4.png)

But when I apply the template to the page/post it stretches it to 100% width like this. 

![image](https://user-images.githubusercontent.com/4141/54730866-28b3f180-4bc6-11e9-88e3-61b3a3e60e6a.png)

It is both wider than I wanted and also the aspect ratio is messed up. 

This seems to be the offending code. 

`.elementor embed, .elementor iframe, .elementor object, .elementor video {
    max-width: 100%;
    width: 100%;
    margin: 0;
    line-height: 1;
    border: none;
}`

I tried to fix it by doing "width: unset;" style, but that also removed the Gutenberg  sizing.

Gutenberg is doing it's job properly and adding in the code at the proper width and responsiveness for the video. Is there a reason Elementor is overwriting that and if not can it be removed?

I checked and if I was adding the video on a page which was completely Elementor (no Gutenberg), _see a width option in the advanced tab, so that shouldn't be a reason to overwrite Gutenberg settings.

**Comment by shilo-ey** [comment]
Hi @JeremyL 

This CSS has been added in order to provide a fluent responsive layout to Elementor.

If you wish to change this behavior please add custom CSS to your customizer/theme CSS file in order to override these settings:
```css
[data-elementor-type="single"] iframe {
    min-width: 560px;
    width: initial;
}
```

Thanks.

**Comment by J4m3s1701** [comment]
Hi there, I am having this same issue, I have managed to resolve it with CSS, but it breaks the mobile layout with the video sticking half off the page. 

Is there a way around this?

Thanks

**Comment by speedxcz** [comment]
> Hi there, I am having this same issue, I have managed to resolve it with CSS, but it breaks the mobile layout with the video sticking half off the page.
> 
> Is there a way around this?

Hi, something like the code below might help ;). It's one of the many little things that Elementor makes its work easier for itself and assigns it to others. I understand, most people probably don't deal with this.

CSS
/* Elementor correction video 100% width */
@media screen and (min-width:560px) {
    .elementor embed,.elementor iframe,.elementor object,.elementor video {
        min-width: 560px;
        width: initial;
    }
}
