### ISSUE TITLE
Lightbox - Populate All single asset images on page when a lightbox is called

### ISSUE THREAD

**Issue by phoenixeii** [elementor/elementor#7572]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Our wants their images showcased individually on the page, but with a gallery of all images on the page to pull up when the lightbox is called... 

**Describe the solution you'd like**
Get a single image lightbox to populate all assets on a page instead of only the single, like a gallery lightbox. 

**Describe alternatives you've considered**
Foo gallery + lightbox, wordpress gallery w/ custom url link, closest successful solution: created an elementor popup with image gallery widget loaded with the pages images - but of course the popup's gallery is going to start on its default image and not the original single clicked calling on the popup

**Additional context**
The site, with single images: 
http://www.zachshow.com/indian-motorcycle/never-ending-summer-event/

--

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by TheMangoTrain** [comment]
Yes, without a grouped lightbox gallery, this feature is kind of useless.

For the most part, this would be standard UX practice and expectation. When an end-user opens a lightbox, they expect to see multiple images and continue to flow in their experience. They can consume the "story" (or "message") visually or drop back into the text article and keep reading. Can you think of any major website or app that doesn't do this?

Conversely, an end-user does not expect to have to separately open-and-close multiple lightbox modal's on a given page (that requires effort). There may be special cases for this kind of UX, but it's hard for me to think of one; maybe something that requires forced focus on one piece of content and not allowing the user to "fast-forward" e.g. an e-course, scientific documentation or some kind of legal context.

All lightbox plugins have handled this for years simply by using class names. e.g. image_orange and image_apple both have class name "lightbox_group_fruit", therefore they are in the same lightbox. It's rudimentary lightbox functionality.
