### ISSUE TITLE
Injecting markup into an element

### ISSUE THREAD

**Issue by dzmarc** [elementor/elementor#7577]
I have been trying to inject some markup inside the 'section' tag generated by Elementor. The 'elementor/frontend/section/before_render' and 'elementor/frontend/section/after_render' hooks are close but don't do what I am looking for. Something like 'elementor/frontend/section/before_closing_tag' would be a great hook or before_closing_tag() method. 

The reason I am trying to use this is to inject some markup or svgs into a section tag based on some custom section controls. Similar to how the print_shape_divider() method in includes/elements/section.php works.

**Comment by lior-sh** [comment]
Hi @dzmarc,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
