### ISSUE TITLE
Popup triggering outside of custom trigger rule

### ISSUE THREAD

**Issue by djnorrisdev** [elementor/elementor#7578]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Description

I am using Elementor Pro with Oceanwp/ Oceanwp child theme (which is active). I have a page with 23 image boxes, and a dynamic link is set to one of 23 popups. When the page loads and anywhere in the browser window is clicked, all of the popups appear (stacked one on top the other, so only the last shows). I have only set a trigger of on click in each image box with a dynamic link to trigger each popup. I have only set a custom trigger of click once to open the popup, and only set the trigger to each image box. This seems like an unintended effect.

The google drive link below has a video that shows the issue. I load the page, and the first click in a non-targeted area opens all of the popups. I close the popup, click the spot again, and no popup is triggered unless by the image boxes (which was set with a dynamic link). 
Google drive video: https://drive.google.com/open?id=16qkkHr8sZ0lMnIf50yvb7TRtXwJ-Xj6i

[system-info-.txt](https://github.com/elementor/elementor/files/2992468/system-info-.txt)

**Comment by bainternet** [comment]
@djnorrisdev 	

we can't replicate, 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
