### ISSUE TITLE
font selection does not work

### ISSUE THREAD

**Issue by LuxRN** [elementor/elementor#7583]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

if I select a different font from the "style" tab it is not applied to the text
## Steps to reproduce
- select title > style tab > Typography > select font family  (title font don't change)
- view page preview > inspects title > font-family not correct (there is a comma)

![54741786-cd7f0080-4bbf-11e9-9fd6-94dc5be49da3](https://user-images.githubusercontent.com/48787497/54808829-ad177a80-4c81-11e9-9c2b-de1f90c3d8b6.PNG)
 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 9.1 v5.6.36-82.1
	PHP Version: 7.0.27-0+deb9u1
	PHP Max Input Vars: 66600
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.10
	Site URL: https://elementor.edita.it
	Home URL: https://elementor.edita.it
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 400M
	Permalink Structure: /%postname%
	Language: it-IT
	Timezone: Europe/Rome
	Debug Mode: Active

== Theme ==
	Name: Twenty Seventeen Child
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 1.7
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Custom Icons for Elementor
		Version: 0.2.2
		Author: Michael Bourne

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Edita Landing
		Version: 0.0.1
		Author: Edita

	Edita Seo
		Version: 2.2.04
		Author: matteo roselli @edita

	Elementor
		Version: 2.5.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.6
		Author: rocketgenius

	Multiple Domain
		Version: 0.8.1
		Author: Gustavo Straube (straube.co)

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	User Role Editor
		Version: 4.50.1
		Author: Vladimir Garagulya

	W3 Total Cache
		Version: 0.9.7.2
		Author: Frederick Townes

	WordPress Social Login
		Version: 2.3.3
		Author: Miled

	WP Media folder
		Version: 4.7.9
		Author: Joomunited

== Log ==
	: 
Log: showing 20 of 202019-02-21 11:03:30 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (5 of 14, 36%) 
2019-02-21 11:03:31 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (6 of 14, 43%) 
2019-02-21 11:03:32 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (7 of 14, 50%) 
2019-02-21 11:03:33 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (8 of 14, 58%) 
2019-02-21 11:03:33 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (9 of 14, 65%) 
2019-02-21 11:03:34 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (10 of 14, 72%) 
2019-02-21 11:03:36 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (11 of 14, 79%) 
2019-02-21 11:03:38 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (12 of 14, 86%) 
2019-02-21 11:03:40 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (13 of 14, 93%) 
2019-02-21 11:03:41 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start (14 of 14, 100%) 
2019-02-21 11:03:42 [info] Elementor/Upgrades - _v_2_3_0_widget_image Finished 
2019-02-21 11:03:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.2.5',
  'to' => '2.4.7',
)]
2019-03-05 09:31:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.1',
)]
2019-03-05 09:40:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.1.10',
  'to' => '2.4.6',
)]
2019-03-06 09:24:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.1',
  'to' => '2.5.2',
)]
2019-03-08 09:26:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]
2019-03-11 16:48:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.3',
  'to' => '2.5.5',
)]
2019-03-11 16:49:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-03-20 12:37:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.5',
  'to' => '2.5.9',
)]
2019-03-20 12:37:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.7',
  'to' => '2.4.8',
)]

JS: showing 10 of 10JS: 2019-02-21 10:07:34 [error X 534][https://elementor.edita.it/wp-includes/js/jquery/jquery.js line 2 > eval:1:36] gformInitSpinner is not defined 
JS: 2019-02-25 20:20:00 [error X 1][undefined:1:52] Can\'t find variable: gformInitSpinner 
JS: 2019-02-28 11:12:02 [error X 5][https://landing.edita.it/wp-content/plugins/elementor/assets/js/editor.min.js:2:74603] setting getter-only property \"type\" 
JS: 2019-02-28 13:24:34 [error X 22][https://landing.edita.it/wp-content/plugins/elementor/assets/js/editor-modules.js:733:35] self.attributes[control.name].each is not a function 
JS: 2019-03-01 15:24:43 [error X 1][https://landing.edita.it/wp-content/plugins/elementor/assets/js/editor.min.js:2:205167] n.ui.input is undefined 
JS: 2019-03-05 08:51:47 [error X 452][https://landing.edita.it/wp-content/plugins/elementor/assets/js/frontend.min.js:2:41747] o is undefined 
JS: 2019-03-05 08:54:10 [error X 9][https://elementor.edita.it/wp-admin/load-scripts.php?c=0&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.9 line 5 > Function:28:7] isMultiple is not defined 
JS: 2019-03-05 16:18:38 [error X 5][https://landing.edita.it/wp-content/plugins/elementor/assets/lib/slick/slick.min.js:1:19325] e.$slides is null 
JS: 2019-03-11 15:59:39 [error X 11][https://landing.edita.it/wp-content/plugins/elementor/assets/js/editor.min.js:2:238660] n is undefined 
JS: 2019-03-13 12:31:39 [error X 2][https://landing.edita.it/wp-includes/js/jquery/jquery.js line 2 > eval:1:2418] gf_apply_rules is not defined 

PHP: showing 2 of 2PHP: 2019-03-04 09:13:22 [notice X 1][/var/www/clients/client1/web111/web/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-18 12:14:48 [notice X 8][/var/www/clients/client1/web111/web/wp-content/plugins/elementor/includes/elements/column.php::1070] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>

**Comment by bainternet** [comment]
@LuxRN 

We can't replicate,  please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists, Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by LuxRN** [comment]
i've done rollback to 4.9.10 and font selection works good
