### ISSUE TITLE
Problems with Open Graph in single posts

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#7585]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

When I write a post with classic editor the opengraph work right.

When I write a post with elementor editor the opengraph doesn´t work right

Elementor > https://blog.despierta.org/retos-del-plastico-dentro-y-fuera-de-casa/
Classic Editor > https://blog.despierta.org/hacer-florecer-una-rosa/

You can try share this links in twitter or facebook and you can see the diferent. 
-->

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

Last Version Elementor and WordPress

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.6.37
	MySQL version: MariaDB Server v5.7.24
	PHP Version: 7.2.10RC1
	PHP Max Input Vars: 100000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://blog.despierta.org
	Home URL: https://blog.despierta.org
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Clean Blogging
	Version: 1.1.3
	Author: designgrande
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.9
		Author: Elementor.com

	Feed & LikeBox For Facebook
		Version: 2.7.9
		Author: Weblizar

	Google Captcha (reCAPTCHA) by BestWebSoft
		Version: 1.42
		Author: BestWebSoft

	Instagram Feed
		Version: 1.11.3
		Author: Smash Balloon

	JM Twitter Cards
		Version: 10.0.1
		Author: Julien Maury

	UpdraftPlus - Backup/Restore
		Version: 1.16.8
		Author: UpdraftPlus.Com, DavidAnderson

	W3 Total Cache
		Version: 0.9.7.2
		Author: Frederick Townes

	Weblizar Twitter Tweets
		Version: 1.8.2
		Author: Weblizar

	Yoast SEO
		Version: 10.0.1
		Author: Team Yoast

== Log ==
	: 
Log: showing 1 of 12019-03-21 13:27:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]

				
```
</details>

**Comment by bainternet** [comment]
@lauranunez 

I don't see any issues, both seem to work just fine, the only problem I see is that the image on this page is 9.5 MB  and 5765px/3799px which is crazy big

and according to Twitter:
`twitter:image`

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.


As for Facebook, not sure what the limit is but if you look at the [link debugger](https://developers.facebook.com/tools/debug/) it seems like all of the data is listed correctly.

thanks.

**Comment by kerr-nz** [comment]
I have this issue too - not sure their reply resolved your question.

The default Elementor Pro share widget does not correctly tag the OpenGraph tag for the Featured Image, resulting in posts on FB and Twitter not rendering correctly.

Strangely, Elementors own site works fine.

Been trying to solve this issue for a while

See the second page of the attached PDF for example

[ElementorISSUES.pdf](https://github.com/elementor/elementor/files/3409371/ElementorISSUES.pdf)

**Comment by kerr-nz** [comment]
Implicitly, Facebook report:

Warnings That Should Be Fixed
Inferred Property
The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

**Comment by vgstef** [comment]
I also have this problem. Any solution or workaround? I use the Hello theme and Elementor Pro. How and where can we set the og:image property with the featured image ?

**Comment by kerr-nz** [comment]
You need a plug-in 

We use all in one seo to do it
