### ISSUE TITLE
Centralized Information

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7587]
Hello guys,

I have several pages created with Elementor, and in several of pages I even divulge product where I put price, discount percentage and ect.

When I need to change this information, I will need to go through each of these pages and make the change.

So, Elementor could offer a centralized information scheme. For example, somewhere in the Elementor I would create an information like "price", Elementor would generate a code where I would insert this code into every page of my site. So whenever I needed to change the price of the product on all those pages, I would not have to go into each of those pages, just go to that centralized location and change the price, and that information would change on every page where I put it this code.

For each different information (price, discount percentage, ...) a different code would be generated.

This would be great to minimize our work in those times where the price, discount and other product information are changed and we have to change on each page where we enter this information. In fact, we even have to remember all the places where we enter this information. And that would have a time interval, where until the change is made, the user will be seeing the old information.

Now, with the use of this centralized information (code insertion), we just need to change it in one place. Much faster.

I leave this suggestion to you.

Thank you,
Rodrigo Carlos

**Comment by shilo-ey** [comment]
Hi @rodrigocarlos 

You can create a template using [Global Widgets](https://docs.elementor.com/article/100-global), and then only edit the global widgets inside the template (the section you used).

In addition, you can create a page with conditions using our [Theme Builder](https://elementor.com/theme-builder/), so there's a single template for multiple pages.

**Comment by rodrigocarlos** [comment]
Hello @shilo-ey 
Thank you!
I think Global Widgets would be perfect.

And taking advantage of the contact to make a suggestion... in Global Widgets, you could have, in each widget, an option to see where this widget is being used. Maybe it would be an icon in each widget where clicking this icon opens a little window showing all the pages where the widget is being used. And if the widget is no longer being used on any page, then the widget would be a gray color.
This would help clear the widgets that are no longer being used.

I have global widgets created, but I do not know if everyone is still being used. So I have to go into each of my pages created with the Elementor to check if the widget is being used, and if it is not, delete the widget. This is a little hard work.

Another suggestion ... could have option of organizing the Global Widgets into groups (folders, tabs, accordion, ...), and each group I could give a custom name.
This would be good for when we have many widgets created.
For example, for product 1 I create several Global Widgets for use on multiple pages; for product 2 I also create several Global Widgets to be used on several pages. So I could create two groups and give the name of Product 1, Product 2 and arrange the corresponding widgets in these two groups.

Thank you,
Rodrigo
