### ISSUE TITLE
Option to center HTML widget

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7588]
Hello guys,

When I enter an external code in the HTML widget, for example a code from a form in my email tool, it appears in the popup on the left when the popup window is wider than the form: https://screenshot.net/44zdjb0

So, for me to center it, I had to manually enter the <div align="center"> </div> (https://screenshot.net/8qk8dcy).

But, Elementor could give us the option of centralizing the insert code in the HTML widget.

I leave this suggestion to you.

Thank you,
Rodrigo Carlos

**Comment by shilo-ey** [comment]
Hi @rodrigocarlos 

We cannot control inline html, for that you can add custom CSS 

```CSS
selector {
    text-align: center;
}
```

or directly target your element in the global CSS.

Thanks
