### ISSUE TITLE
Duplicate Link

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7592]
Hello guys,

When duplicating a popup the margin settings of the first popup (https://screenshot.net/pt/mk04kco?) are not inherited in the duplicate (https://screenshot.net/pt/r46k4sz?) popup.

Another thing...
I wanted to take this opportunity to give you a suggestion.
If I want to duplicate a popup, just enter it and save it as a template, then go to the saved popups section and open the template I saved. OK!
This process is the same for when I want to duplicate a section or a whole page to create another equal.
However, it could have a Duplicate link in the list of saved models. Clicking this Duplicate link quickly creates a new popup, section, or page without the need to open the edit page and save as a template. It would be a faster process.

In the case of a page created with Elementor (in the Page section of Wordpress - /wp-admin/edit.php?post_type=page), it could also have a Duplicate link where clicking once would create another completely equal page (https://screenshot.net/pt/jjgdmh3?). Then just rename and publish it.

Thank you,
Rodrigo Carlos

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by rodrigocarlos** [comment]
Hi shilo-ey
OK! I put the problem in the correct section.

As for my suggestion, I believe it's for this section right here. So, I'll leave it for you to consider in an upcoming update, , if at all possible.

Thank you,
Rodrigo
