### ISSUE TITLE
Elementor Filter for WYSIWYG Control's default P Tag 

### ISSUE THREAD

**Issue by sagarpatel124** [elementor/elementor#7597]
I can not find filter for Elementor which remove <p> while using WYSIWYG editor controller.

Wordpress already have that filter for the content. https://codex.wordpress.org/Function_Reference/wpautop 

Can we have that similar in elementor? 

Note : Best If we can setup that for individual widgets.

**Comment by bainternet** [comment]
@sagarpatel124 

Elementor doesn't run `wpautop` on the text-editor content, it comes for the default settings of the tinyMCE. You can use the `tiny_mce_before_init` hook to prevent that.

Ex:

```PHP
add_filter( 'tiny_mce_before_init', function( $init ) {
	$init['forced_root_block'] = false;
	$init['force_br_newlines'] = true;
	$init['force_p_newlines'] = false;
	$init['convert_newlines_to_brs'] = true;
	return $init;
} );
```

**Comment by sagarpatel124** [comment]
Ok. Thanks for your information. 

Is there any option in which we can set up that for individual?

Above solution might be for all together.
