### ISSUE TITLE
[Bug] ACF field doesn't appear on Search Results template

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#7598]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
Version: 2.4.8

## Description

![giphy](https://user-images.githubusercontent.com/17693529/54865568-0ea11d00-4d46-11e9-824b-f8316896b794.gif)

ACF field doesn't appear on Search Results template. The GIF above shows the text appearing on **Category** template, but after a search it vanishes on the **Search Results** template.

I created an **Options Page with ACF** and tried to display the dynamic text on the Search Results page.

## Steps to reproduce

Create a **Search Results template** page and add a **Text widget** with a **text dynamic field** and try to  display it.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active. (Elementor Hello Theme)
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by Artneo7** [comment]
Anatoly replied: “Unfortunately, custom fields are not supported at the moment on the Archive templates. You can only display Custom fields on the pages where they were filled up, but relationships don't work yet. **We understand the importance of this feature and will add it one day as a part of an update**.”

I'm looking forward to this update… is there a roadmap ou label that could be addressed to this issue to let people know it's already been planned for future releases?

Thanks!
