### ISSUE TITLE
Manage Unused Third Party Widgets 

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#7602]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When using multiple Addons featuring lots of features, it is easy to load way too many features and widgets, which remain unused and "slow" down a users website. If two "extras" plugins are used, without deactivating unused widgets, the site can get bloated with unnecessary javascript and CSS by 100%. 

The solution for this is to deactivate unused widgets. The problem is, that for a larger site, it is difficult to determine which widgets are in use. 

**Describe the solution you'd like**

A solution would be to create an admin section that displays currently used widgets, or allow and encourage third party plugin developers to highlight widgets that are currently unused. This would allow to greatly reduce the number of scripts being called and speed up the site. 

**Describe alternatives you've considered**
Manually going through the site and deactivating unused widgets from various plugins.

**Comment by shilo-ey** [comment]
Hi @taropaa 

If the widget is properly written, it's assets will be enqueued only if the widget is in use.

I merged this issue with  #7530, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @taropaa!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.18.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
