### ISSUE TITLE
Popup email address validation

### ISSUE THREAD

**Issue by born2fly** [elementor/elementor#7606]
It appears that when a user inputs an email address into a form(popup), it does not get validated and anything can be typed in.

Ideally it would great if MX and DNS checking were built in so a 3rd party plugin to do this wouldn't be required.

**Comment by shilo-ey** [comment]
Hi @born2fly 

Regardless of the popup, our Forms module uses the native browsers HTML5 validation API for the email validation.

If you need further validation, you can follow our Forms API examples provided [here](https://github.com/elementor/elementor/issues/5616#issuecomment-417212158) and [here](https://github.com/elementor/elementor/issues/3164#issuecomment-357464718).

Thanks!
