### ISSUE TITLE
Login Widget and Password Manager

### ISSUE THREAD

**Issue by fdeross** [elementor/elementor#7607]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description 

Indicators for saved login username/email and password are hidden in the corresponding box when using the login widget. I am using the Elementor Pro popup template (the one that is Christmas themed) and LastPass. I assume this would work with other password managers.  Normally there would be an indicator on the right side of each input box where the user can select from a list of saved logins.  The functionality still works but there is no indicator visible to click on.  Indicators are visible throughout the rest of the site.

Here is a screen recording:

https://www.dropbox.com/s/5x8u2hht24c0qyd/screencast%202019-03-24%2014-53-22.mp4?dl=0

## Steps to reproduce

 
1.  Select the template from the popup template library.

2.  Save and activate

3.  Attempt to log in.

4.  Click the far right edge of the input box.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

https://pastebin.com/dfp621fE

</details>

**Comment by bainternet** [comment]
@fdeross 	

thanks for notifying us, sadly we have no control over when and how they display their indicator.

If you have information that we can act on, we'd be happy to do so.

thanks.
