### ISSUE TITLE
WYSIWYG Pods not well formatted when in textfield on single template #6519 reopened

### ISSUE THREAD

**Issue by Luxamman** [elementor/elementor#7611]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets. Reopened the #6519 because there is **no solution working** and the bug is here since then. 
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The text format from pods WYSIWYG fields is not 1:1 transferred to Elementor text field. Seems the problem is primarily with breaks and text paragraphs.
Could be a problem from pods framework? When using "plain text" in pods, the line breaks are used normally.

Here a picture of the WYSIWYG pods field:
![50339980-5b901000-0519-11e9-9204-67d558fc2fa9](https://user-images.githubusercontent.com/20417555/54909752-2fef3e00-4eeb-11e9-8ac4-da296fae1a41.jpg)

And here the final output:
![50339977-57fc8900-0519-11e9-8900-d11cd609e9ca](https://user-images.githubusercontent.com/20417555/54909762-354c8880-4eeb-11e9-8327-debf1e64c0e4.jpg)

You can see, the simple line breaks are ignored, also double breaks are converted in white space between words.

## Steps to reproduce
Create a pod, create a single template and include the WYSIWYG pods field into a Elementor single site text field.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active. (Elementor Hello Theme 1.2)
- [x] I can reproduce this bug consistently using the steps above.

Seems it is a Elementor problem, since @jimtrue from Pods had a look at it. Also @kroeberk is considering this bug as not closed. Only headers like h1 are producing a line break. Paragraphs are not showing line breaks at all. Problem is also with different servers, PHP7.1-7.3 and latest Elementor Pro and Pods versions. 

Dirty solution not working: 
add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );

## Important Note

Please don't just close this again, since this is a **major problem** using dynamic content and Elementor for every day projects. 
Also "her is some code to maybe fix it" is not a well and working solution for everyone. 
Don't want to be rude about it, but we are paying good money for the Pro version and this IS a problem we facing in several projects. So please have a look into it to find a solution, we will deliver answers and content as far as we can to help get rid of that bug.

Thanks!

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.15
	PHP Version: 7.3.2-3+0~20190208150725.31+stretch~1.gbp0912bd
	PHP Max Input Vars: 1000
	PHP Max Post Size: 150M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	WP Multisite: No
	Max Upload Size: 150 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

**Comment by simonclay** [comment]
I too am experiencing this issue. A major problem.

Elementor Version 2.5.12
Elementor Pro: Version 2.5.5
Pods: Version 2.7.12

**Comment by youliaaa** [comment]
I'd like to second this. Elementor team, can we please get this fixed? The Elementor/pods combo is awesome, but really not working if wysiwyg fields don't integrate properly. thank you!

**Comment by youliaaa** [comment]
Hi Elementor team! Are there any updates on this issue please? This issue is really frustrating and incredibly important one to fix since it's basic functionality that is urgently needed...

**Comment by amguguy** [comment]
Same here! Can you P-L-E-A-S-E fix this issue? thanx

**Comment by Jendarran** [comment]
I, too, would love to see this resolved!

**Comment by shilo-ey** [comment]
Hi all,

As @bainternet mentioned in #6519, this behavior is due to the fact that by default we run all Pods field output via `wp_kese_post()` for security reasons, this is not an issue and it's not going to change in the near future.

>However, you can use the native Pods shortcode and use the dynamic shortcode tag for it. Still, a problem since we also run the output of the shortcode tag via `wp_kese_post()` but here you can disable it via a filter:
> ```
> add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
> ```

Thanks

**Comment by youliaaa** [comment]
@shilo-ey where and how do you add the filter? 
Inside the template or is there a specific plugin page this should be added to? 

Many thanks, 
Julia

**Comment by youliaaa** [comment]
Hi Elementor team, given that Elementor is designed for no coders (I'm one of those users) is it possible to create a clear tutorial or example on how to bypass this problem? I'm getting increasingly frustrated by this. It's taken me months of waiting around to get told that you won't fix this, and the solution is not well documented. When I click on shortcode it comes up with a blank screen. When I insert [pods field="field_name"] in the text field it shows it correctly in preview my template but renders it blank on the actual page. I've added your provided filter code to the generaltemplate.php but no idea if this is the right place to add this filter. I've read most of your documentation on php hooks on your dev site and github but none the wiser as to where to put this filter. So can you please please provide some clear instructions that non coders can follow to solve this issue? Especially since it's NOT WORKING correctly and many users asking you to fix this and the answer has been a Mexican stand off between pods and elementor...

**Comment by KeriCaraher** [comment]
Any solutions yet?

**Comment by quasel** [comment]
> Hi all,
> 
> As @bainternet mentioned in #6519, this behavior is due to the fact that by default we run all Pods field output via `wp_kese_post()` for security reasons, this is not an issue and it's not going to change in the near future.
> 
> > However, you can use the native Pods shortcode and use the dynamic shortcode tag for it. Still, a problem since we also run the output of the shortcode tag via `wp_kese_post()` but here you can disable it via a filter:
> > ```
> > add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
> > ```
> 
> Thanks

I don't see why this is necessary as pods already sanitizes it's output for security reasons if you use the proper functions and even allows you to further restrict the output… 

<img width="587" alt="image" src="https://user-images.githubusercontent.com/9464217/93577965-fd69b880-f99c-11ea-8e6d-6114c4cae028.png">

@shilo-ey Did you find any issues within pods? Then please report them to @sc0ttkclark or our GitHub Repo! 

@bainternet https://github.com/elementor/elementor/issues/6519#issuecomment-450546665 - I would like to hear about the "obvious" reasons as pods "obviously" does properly sanitize it's output if not pleas report back to us! 

Thanks 
Bernhard

**Comment by Black-Rooster** [comment]
Has this been resolved yet?
I cannot find a solution to this anywhere and i don't understand what to do with this:

add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );

**Comment by contrastxxx** [comment]
![image](https://user-images.githubusercontent.com/68115204/133737473-bb6dde06-fc96-43ed-9346-22d40e510a26.png)
only solution for my is change editor to CLEditor

**Comment by iMiek** [comment]
@contrastxxx thanks for your tip.
I use the Quill editor, that works too.

**Comment by fwunder** [comment]
Still an ongoing problem.

Wordpress Version: 6.1
Elementor Pro Version 3.8.1

**Comment by Nikolai2** [comment]
Switching to the Quill editor fixed the issue as well for now.
