### ISSUE TITLE
[Bug] Categories archive pagination return error 404

### ISSUE THREAD

**Issue by Artneo7** [elementor/elementor#7613]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Video (0:40) explaining the issue:
https://streamable.com/bwu3b

## Steps to reproduce

Templates > Theme builder > Archive > Categories

Create posts so you'll have more than one page.

Click the access page 02:
![page-02-issue](https://user-images.githubusercontent.com/17693529/54922784-a1c58880-4ee7-11e9-8bb0-5a8986b1f815.jpg)

You'll get error 404…

If you create a **page** and put the **Posts widget** the pagination works just fine.

If you create an **archive template** and put the **Posts widget** the pagination will return 404.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: MySQL Community Server (GPL) v5.7.23
	PHP Version: 7.2.9
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://github.local
	Home URL: http://github.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

== Log ==
	: 
Log: showing 14 of 142019-01-21 15:21:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.3',
)]
2019-01-21 20:00:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-24 13:00:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-24 13:04:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.1',
)]
2019-01-25 15:12:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
2019-01-31 07:17:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-01-31 08:01:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-02-11 15:49:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-11 20:29:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-02-18 15:54:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-18 20:38:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-03-18 11:19:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.8',
)]
2019-03-18 11:19:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.5',
  'to' => '2.4.8',
)]
2019-03-18 14:24:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]

JS: showing 2 of 2JS: 2019-02-25 17:53:54 [error X 11][https://artneo.com.br/wp-content/themes/twentyseventeen/assets/js/global.js?ver=1.0:8:58] Cannot read property \'top\' of undefined 
JS: 2019-03-18 17:29:12 [error X 1][https://artneo.com.br/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.9:674:36] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `html` got <30> as `sticky_offset` value. Expected array or object.',
)]
</details>

**Comment by javiercriado** [comment]
I was facing the same issue until now.

Try adjusting in Settings: Reading the same quantity of posts per page you're using in your Elementor Theme Builder

**Comment by Artneo7** [comment]
Thanks for the suggestion @javiercriado! I've just tried it, but it didn't work in my case. And even if this was a solution for this issue, you wouldn't be allowed to have different quantity of posts per page for different design layouts inside your project.

**Comment by shilo-ey** [comment]
Hi @Artneo7 

When applying Posts Archive widget inside Archive template, it inherits the attributes that the archive itself contains.

Posts widget isn't meant for this purpose. 

The pagination in the Posts archive widget is coming from the WP settings itself (you cannot set a number of posts to show in this widget but under settings > reading).

In Posts widget you can create pagination with "virtual" pagination URLs, and the URL inside the archive arrives from the archive itself.
eg.
`../category/cat_1/page/2`


Therefor we cannot create this kind of behavior, and we created the Archive Posts widget.

Thanks!

**Comment by Artneo7** [comment]
Now I see @javiercriado… when using the **Posts widget** your solution wasn't working for me. But, now I changed to the **Archive Posts widget** and the pagination is working correctly – if I match the one set inside the widget with the _Settings > Reading > Blog pages show at most_.

**Comment by javiercriado** [comment]
yes.
I jumped into some limitations with Elementor regarding f.e. working with archives from custom post types and saw some complementary third party plugins which do manage those.
regarding this pagination matter I just thought it had something to do with the main query object, so I tried matching the pagination parameters in Settings and in Elementor template and it worked.
anyway...I would like this functionality to be more open and complete.
I have to create pages to list custom post types as archives...
good luck with your project!

**Comment by swamiv1984** [comment]
This is the culprit "Wordpress Settings > Reading > Blog pages show at most". This setting should be less than or equal to the number of post per page in elementor template(posts widget). Say If I set 3 blogs per page in elementor template(posts widget), then in wordpress settings, blog pages show at most will be less than or equal to 3. This setting is currently working for me now.

**Comment by Hembi** [comment]
Same problem here on Archive page. If the two number (Elementor Post widget Post per Page -  "Wordpress Settings > Reading > Blog pages show at most") limit is equal than got no 404 error.
Please provide a notice on this module, or disable on archive template! Why I have to search and read a comment in a GitHub issue to notice what's wrong, cmmn.
An AJAX pagination also would be nice, its 2020.

**Comment by isber-es** [comment]
It does not work for me.
I am using custom post type.
I create a list and the pagination does not go ...
Any solution out there?

**Comment by Hembi** [comment]
If you use Posts widget on Archive Page then simply change the Posts widget to "Archive Posts widget" as @shilo-ey mentioned above.

**Comment by isber-es** [comment]
Yes, I tried it, but I can't find the content ... It comes out empty.

**Comment by andreiger** [comment]
Unfortunately it seems no elementor widget could help me. The pagination simply won't work.
In the end I just set the "Wordpress Settings > Reading > Blog pages show at most" to 9999999

**Comment by soulreverie** [comment]
This is still an issue!! I had to use the following: 

`function owp_cb_pagination_rewrite() {
  add_rewrite_rule(get_option('category_base').'/page/?([0-9]{1,})/?$', 'index.php?pagename='.get_option('category_base').'&paged=$matches[1]', 'top');
}
add_action('init', 'owp_cb_pagination_rewrite');`

Credit to 
http://dejanjanosevic.info/elementor-archive-posts-widget-pagination-404-error/

**Comment by P4KM4N** [comment]
WOW! setting the same number of post per page in Elementor and WordPress settings fix the issue for myselft! I would have never found it without  @javiercriado ! Thanks!

**Comment by Merlin-the-Warlock** [comment]
> This is still an issue!! Everything on my end is correct - the Elementor archive template, the Archive Post widget, etc. My problem is specific to the main blog page. Pagination is broken when on the main blog archive page. Categories and tags pagination works just fine.

Hey @soulreverie ! I had the same problem as you but I fixed it w/o the hacky functions.php stuff.

Go to **Settings > Permalinks > Optional**. Make sure there's nothing in the Category Base/Tag Base. 

I think my problem was that I had something in Category base which confused Wordpress. 

Hopefully that at least points you in the right direction!!

**Comment by pioNavarro** [comment]
I use to resolve the issue using this code

`function vessel_pagesize( $query ) {
    if ( ! is_admin() && $query->is_main_query() && is_post_type_archive( 'vessel' ) ) {
        // Display 1 posts for a custom post type called 'vessel'
        $query->set( 'posts_per_page', 1 );
        return;
    }
}
add_action( 'pre_get_posts', 'vessel_pagesize', 1 );`

**Comment by ehsanham** [comment]
Hey guys , I am using post widget and the pagination is not working on the archive page  at all .
 two number (Elementor Post widget Post per Page - "Wordpress Settings > Reading > Blog pages show at most") limit is equal but its still shows a 404 .
I also tried this code `add_action( 'pre_get_posts', 'jp_search_filter' );
function owp_cb_pagination_rewrite() {
  add_rewrite_rule(get_option('category_base').'/page/?([0-9]{1,})/?$', 'index.php?pagename='.get_option('category_base').'&paged=$matches[1]', 'top');
}
add_action('init', 'owp_cb_pagination_rewrite'); `
 But the 404 still exists  .
What should I do ? is using the archive post widget the only way to do ? 
I have lots of different template page and its a time consuming thing for me to change all of them.
Somebody help me from this headache .

**Comment by BackuPs** [comment]
This can be easily achieved by adding a pre_get_post for post archives....  f.e.  here you set the number of post per page to 9.  After adding this code all archivies work just fine with the post list element set to 3 columns and 9 posts.  No more 404 on the 3rth page when wordpress reading has been set to 10.  I do not understand why this is not added by default to the elementor code.

`function theme_set_post_type_archive_pagesize( $query ) { 
if ( ! is_admin() && $query->is_main_query() && is_archive( 'post' ) ) { 
	$query->set( 'posts_per_page', 9 ); 
	return; 
} 
} 
add_action( 'pre_get_posts', 'theme_set_post_type_archive_pagesize');`

**Comment by markhhg** [comment]
Make sre YOAST SEO "Show the categories prefix in the slug" has the correct value ;)
It was the issue in my case
