### ISSUE TITLE
pre_get_posts and Elementor [BUG]

### ISSUE THREAD

**Issue by bentalgad** [elementor/elementor#7614]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I use the hello theme and child theme. in the child theme functions.php i have this code:
```PHP
function set_posts($query) {
if ( !is_admin() && !is_post_type_archive('post') && $query->is_main_query()) {
$query->set('orderby', 'rand' );
$query->set('posts_per_page', '-1' );
$query->set('post_type', 'mycustom_post_type' );
}
return $query;
}
add_action('pre_get_posts','set_posts');
```
(which alters the main query of course).

Now with this code, when i edit page with elementor i get the "You must call the_content..." Error. 

If i remove this line:
`$query->set('post_type', 'mycustom_post_type' );`
it's fine again.

## Steps to reproduce

Just add this code to your functions i guess (but maybe you need to have a custom post type).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Latest everything :)

**Comment by shilo-ey** [comment]
Hi @bentalgad 

In your custom post type there is no content, and therefore the message is displayed. 
You need to add a condition that checks if it has no preview using: `\Elementor\Plugin::$instance->preview->is_preview_mode()`

Thanks.

**Comment by bentalgad** [comment]
It does have content.

**Comment by shilo-ey** [comment]
sorry, not content, but `the_content()` function

**Comment by bentalgad** [comment]
So what "In your custom post type there is no content" mean? custom post type doesn't have the_content, custom post type is not a template file.
