### ISSUE TITLE
Popups breaking with SWIFT caching

### ISSUE THREAD

**Issue by phases-design** [elementor/elementor#7615]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!
SUPPORT WON'T ANSWER ME. THEY SENT ME HERE. 

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 
I TRIED THAT. THEY WON'T ANSWER ME

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/
SUPPORT SENT ME HERE.

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

I am using SWIFT to cache the site and improve page speed. It works great with Elementor, except for with the new popups. The popups display in the wrong location, and in a scroll box window. I would like to know what files (scripts or css) to exclude from being merged and optimized in SWIFT in order to prevent SWIFT from messing with the popups. I am not requesting that you tell me how to use SWIFT, I am simply asking for the names or a string in the name of scripts and css specific to elementor popups. 

If you feel this is an issue with SWIFT, please provide specifics so I can get back with them. 

The following image shows the popup working without SWIFT, and then the same popup displaying incorrectly with caching enabled. 

![popup-issues](https://user-images.githubusercontent.com/15133817/54946932-c4af6700-4efe-11e9-9106-c4e659667d16.jpg)

**Comment by shilo-ey** [comment]
Hi @phases-design ,

Thanks for contacting us.

I apologize, but this question needs more information, therefore you shouldn't be directed here, but you should have been taken care of our support team.

I've asked them to contact you privately and receive additional information required for providing a proper answer.

Thanks.
