### ISSUE TITLE
Code - Reference isn't working

### ISSUE THREAD

**Issue by mcl11** [elementor/elementor#7617]
Hi, just a short note...

I noticed that the code reference isn't working for quite a few days https://code.elementor.com
It's saying "404 page not found"... ;)

So, maybe you are currently working on the docs. It's hard to understand the logic what's behind Elementor without it. ;)

Thanks a lot & kind regards...

**Comment by shilo-ey** [comment]
Hi @mcl11 

Thanks for bringing this issue to our attention!

We will take care of this soon, in the meanwhile, you can use: [https://developers.elementor.com/](https://developers.elementor.com/)

Thanks!
