### ISSUE TITLE
Allow shortcode usage for Price Table -> Original Price

### ISSUE THREAD

**Issue by jpknz** [elementor/elementor#7618]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Currently it is not possible to use a shortcode for the Original Price field of the Price Table widget (only shows when Sale toggle selected on).

If a shortcode was allowed on this field then the original price could be pulled in meaning price changes to a product could automatically be updated rather than having to manually update each price table tile when prices are updated.

**Comment by shilo-ey** [comment]
I merged this issue with  #5952, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
