### ISSUE TITLE
After elementor pro 2.5.0 update my custom query broke...

### ISSUE THREAD

**Issue by Turanligil** [elementor/elementor#7619]
I have a event section in my webseite. The events (events -> Veranstaltungen in german language) are custom post types with custom ACF fields ...

I'm using the "Snippets" plugin  to create a custom query code wich i included to my post widget in elementor... the query filtered my posts (events) and excludes the events wich are older than today (not the post date is compared -> the custom date field in ACF wich show the date of the event) AND ALSO ordering the posts by this custom date field...

**it worked well but after the update nothing works. Neither the expire filter is working still the ordering... when i go back to the older elementor version everything works fine :(**

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.

Here is my code:
https://www.die-saege.de/screen1.png
https://www.die-saege.de/screen2.png

**Comment by shilo-ey** [comment]
Hi @Turanligil 
Thanks for reporting.

This issue has been fixed in Elementor Pro v2.5.1.

Feel free to update!
