### ISSUE TITLE
Add toggle button to collapse all, expand all Elementor Elements Groups in UI

### ISSUE THREAD

**Issue by kdawg1406** [elementor/elementor#7620]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Each time I edit with Elementor, every category section in the Elements List on the left is expanded.  No matter if I left them collapsed in the last usage.  Very frustrating to work with a category of elements and having to collapse all the sections above it EACH time I edit with Elementor.

**Describe the solution you'd like**
Add a toggle button (clickable icon) to collapse all, expand all Elements sections.  (see image below)

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
See attached image for requested UI. 

![add-collapse-expand-all](https://user-images.githubusercontent.com/5623887/54996186-fe37af00-4f9e-11e9-9d48-44df137af8b0.jpg)

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
