### ISSUE TITLE
API response failures cause A_ARRAY / Object failure on PRO

### ISSUE THREAD

**Issue by philip-jonas** [elementor/elementor#7621]
## Description

When forcing a activation failure to result in a WP_Error response, the validation of those responses fail because its using WP_Error object as a Associative Array.

## Steps to reproduce
Block the request to the activation url and load / edit any page or post using elementor.

`Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in elementor-pro/license/admin.php:318 Stack trace: #0 wp-includes/class-wp-hook.php(286): ElementorPro\License\Admin->admin_license_details('') #1 wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 wp-admin/admin-header.php(276): do_action('admin_notices') #4 wp-admin/index.php(111): include('w...') #5 {main} thrown in elementor-pro/license/admin.php on line 318`

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Nginx / PHP-Fpm / Mysql / PHP7.2
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon.

Please follow this thread for updates.

Thanks!

**Comment by benfavre** [comment]
` if(typeof i !== 'undefined') { i.controls=n.controls,i.tabs_controls=n.tabs_controls}`

**Comment by bainternet** [comment]
@philip-jonas 

do you have some kind of object cache in place (redis, memcached, etc...)?
Maybe a filter on our transient?

Because if you look at the code at line 317, which calls `API::get_license_data();` you can see that it will never return WP_Error.

**Comment by philip-jonas** [comment]
@bainternet it seems you are correct.. you can close this ticket... Thank you for the time and feedback..
