### ISSUE TITLE
Filter Google fonts weights or make a public method for getting Google fonts

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#7622]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Minimize Google fonts's request by decreasing the font weights/variants list. Currently it loads everything, which does cover 99% of use cases, however it's a general forced (and most likely temporary) solution. 

It's really frustrating to load all these variants (maybe hundred of kb), when i'm only using regular and bold.

**Describe the solution you'd like**
Would like to filter the font weight list eg: https://github.com/elementor/elementor/blob/master/includes/frontend.php#L651 .  eg:
```
foreach ( $google_fonts['google'] as &$font ) {
	$font_weights = apply_filters('elementor/frontend/google_fonts_weights', '100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic', $font, $google_fonts_index);
	$font = str_replace( ' ', '+', $font ) . ':' . $font_weights;
}
```
.. or instead of a comma separated list, an array. Afterwards I would condition it with `!is_admin()` to only trim the rest publicly. 

**Describe alternatives you've considered**
I did thought about using `elementor/frontend/print_google_fonts` filter to disable and continue "my way", but i couldn't find any hook or public list of fonts in `Frontend` class.

**Additional context**
Refs: #2088 #4624 

PS: if i'd have a green light i could pull request that in no time :)

**Comment by hogash** [comment]
Nevermind about the filter for font weights.

I thought about this better, and i believe that just a public method for getting fonts would be enough so i could make my own font loader and disable the current Elementor loading method.

I would then be able to combine with other plugin's fonts (for example Kirki) and make a single request.

As far as i can see now, `fonts_to_enqueue` is private and also reset at some point.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!

**Comment by shaneonabike** [comment]
@hogash This is a great addition. I'm just struggling with understanding how I can get the current Elementor instance in order to access this global variable... Do you think you could drop a quick example just for others to see as well...

**Comment by hogash** [comment]
Try `\Elementor\Plugin::instance()->frontend->fonts_to_enqueue`. It might return empty though if it's not requested at the right time. Unfortunately i'm not sure exactly which hook is fit for this though, try looking throughout the code or php hooks docs.

**Comment by shaneonabike** [comment]
Yeah I couldn't get it to work properly. I had to revert to turning off Google fonts printing and rebuilding the fonts myself :/

I created the following issue in order to attempt to address this and request a simple filter call so that people can modify it b/c in my case they are appending waaaaaaaaaaay to many fonts which is increasing the payload massively. #13065 

Thanks so much for attempting to help me though I really appreciate that

**Comment by augustoms** [comment]
Hi @shaneonabike and @hogash. I'm also looking to manage how to remove some unnecessary styles from the elementor automatic google font queue. Tried the `fonts_to_enqueue` filter but couldn't figure it out.
