### ISSUE TITLE
How to enqueue scripts using conditional logic in get_script_depends() based on a control's value?

### ISSUE THREAD

**Issue by Paras16699** [elementor/elementor#7623]
I want to only enqueue a script based on a Dropdown selection of a control available for that widget.

**Here's what I have tried so far:**

1.
```
public function get_script_depends() {

        $scripts = [];

        if ( $this->get_settings_for_display( 'layout_style' ) == 'carousel' ) {
            $scripts[] = 'jquery-slick';
        }

        return $scripts;
 }
```

2. 

```
public function after_render() {
    $settings = $this->get_settings_for_display();
    if ( $settings[ 'layout_style' ] == 'carousel' ) {
        $this->add_script_depends( 'jquery-slick' );
    }
}
```

**Results:**

Both of them don't work. 

1. Throws an error on `control-stack.php:1018` saying that the data settings is NULL. So I guess that it's too early to be accessing `$settings` in the `get_script_depends()` function.
2. Doesn't enqueue the script at all. I went through the `Element_Base` class source code and theoretically, `after_render()` executes after the `render()` function (as the name suggests) and before the `enqueue_scripts()` function so this implementation should work (since `render()` is able to fetch `$settings` so `after_render()` should also be able to), but it isn't working.

Any help or pointers would be much appreciated.

**Comment by Paras16699** [comment]
Update: 

The `after_render()` example that I posted above is working on the frontend (don't know what I missed the last time) but it still isn't enqueuing the scripts in the editor.

So, for enqueuing scripts specially in the editor mode, I added this code:

```
public function get_script_depends() {
    if (\Elementor\Plugin::$instance->editor->is_edit_mode() || \Elementor\Plugin::$instance->preview->is_preview_mode()) {
        return ['jquery-slick'];
    }
}
```

But the script isn't getting enqueued at the editor end. I tried debugging by outputting the value of the edit and preview mode condition using `var_dump()` which outputs `true` but the script isn't enqueuing.

**Comment by Paras16699** [comment]
Solved. In the edit mode, `get_script_depends()` does not have access to `get_settings()` or `get_settings_for_display()` functions, though, on the frontend, these functions execute after the `render()` functions which means they have access to it.

So, the solution would be, enqueue all the scripts for edit and preview mode, whereas use conditional enqueue for the frontend render.

**Example:**

```
public function get_script_depends() {

    if (\Elementor\Plugin::$instance->editor->is_edit_mode() || \Elementor\Plugin::$instance->preview->is_preview_mode()) {
        return ['jquery-slick', 'other_conditional_script'];
    }

    if ( $this->get_settings_for_display( 'layout_style' ) == 'carousel' ) {
        return [ 'jquery-slick' ];
    } else if ( $this->get_settings_for_display( 'condition' ) === 'yes' ) {
        return [ 'other_conditional_script' ];
    }

}
```

**Comment by hassan-weshore** [comment]
Plugin::instance()->editor->is_edit_mode() || Plugin::instance()->preview->is_preview_mode()
