### ISSUE TITLE
[Feature Request] Form Widget - Email Metadata Dynamic Tags

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#7627]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor Pro.

**What problem is your feature request going to solve? Please describe.**
Improving the list of metadata available to send with the e-mail from a form, would greatly increase the possibilities to use the same form along a variety of pages, posts and templates. 

**Describe the solution you'd like**
Tapping into the already available dynamic tags feature of Elementor Pro would allow us to give more detail about where the form was filled, improving context and user experience. 

**Describe alternatives you've considered**
Using custom shortcodes would do the trick, but this would not be an easy solution.

**Additional context**
For example, sending Page Title, current post category or any other information available as dynamic data in the dynamic tag list.

**Comment by bainternet** [comment]
@zeinnicholas

**Comment by zeinnicholas** [comment]
Thanks @bainternet Raz, that's cool to know. This could help us until the demand is grate enough!
