### ISSUE TITLE
Width and Height of popup is not being inherited on saved models

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7629]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

Hello guys,

When duplicating a popup the margin settings of the first popup (https://screenshot.net/pt/mk04kco?) are not inherited in the duplicate (https://screenshot.net/pt/r46k4sz?) popup.

Thank you,
Rodrigo Carlos

## Steps to reproduce

Create a pop with Width and Height (https://screenshot.net/pt/mk04kco?) and then save it as a template. In the saved popups section, edit this second saved popup and you will see that Width and Height were not inherited (https://screenshot.net/pt/r46k4sz?).

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/embed_js/MuGGnD9w
```
</details>

**Comment by shilo-ey** [comment]
Hi @rodrigocarlos 

Thanks for reporting.

We will address this issue soon and will update this thread.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor v2.5.11

Feel free to update!
