### ISSUE TITLE
Custom post query not working

### ISSUE THREAD

**Issue by StreetDog1971** [elementor/elementor#7633]
Hi there,

My custom post queries stopped working after Elementor Pro 2.5.0.
I turned on WordPress debug and realized you changed the hooks for filters and actions for this kind of custom query. Luckily I only had custom post queries on a few websites. This could lead to a lot of trouble.

Anyway, after I changed the action syntax, I get another error:
Fatal error: Uncaught Error: [] operator not supported for strings...

Here's the code that triggers the error message:

$tax_query[] = [
'taxonomy' => 'product_visibility',
'field'    => 'name',
'terms'    => 'featured',
'operator' => 'IN'
];

Has anything else changed in this hook?

It would be great if you guys updated the documentation on every update. It would be extra nice if you could keep compatibility with older versions. I understand the need to optimize some code, but this could quickly turn into a nightmare with complex websites.

Thanks!

**Comment by StreetDog1971** [comment]
Looks like this is a PHP related issue.
If I add $tax_query = array(); before the code above it works fine.

It's strange, because before this code I'm getting the content of $tax_query:
$tax_query = $query->get( 'tax_query' );
So, it should already be an array.

Any clue?

**Comment by shilo-ey** [comment]
Please update to Elementor Pro v2.5.1 and let us know if that worked for you.

Thanks

**Comment by StreetDog1971** [comment]
I was already using 2.5.1

**Comment by shilo-ey** [comment]
@StreetDog1971 

Please paste here your system info (including PHP version)

Thanks

**Comment by momo-fr** [comment]
I have a Woocommerce store where all display modules (publications, woocommerce products) no longer work with queries. The category settings are not taken into account or partially display the products, nothing is working properly, even the duplicate function is inefficient. It's a nightmare.
Back on 2.4.8 obligatory !!

**Comment by shilo-ey** [comment]
[**@momo-fr**](https://github.com/momo-fr) commented on [Mar 28, 2019, 5:19 PM GMT+2](https://github.com/elementor/elementor/issues/7633#issuecomment-477641146 "2019-03-28T15:19:24Z - Replied by Github Reply Comments"):
> I have a Woocommerce store where all display modules (publications, woocommerce products) no longer work with queries. The category settings are not taken into account or partially display the products, nothing is working properly, even the duplicate function is inefficient. It's a nightmare.
> Back on 2.4.8 obligatory !!

Thanks for reporting,
Please create a proper issue report.

Please follow guidelines and kindly open a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
In your report is please provide the following information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by StreetDog1971** [comment]
Sorry for the delay. Here it goes (I masked out the name of the website):

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.23
	PHP Version: 7.2.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://xxxxxxxxxxxxxx
	Home URL: https://xxxxxxxxxxxxxx
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: Europe/Lisbon
	Debug Mode: Inactive

== Theme ==
	Name: xxxxxxxxxxxxxx
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.6.4
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields Multilingual
		Version: 1.1
		Author: OnTheGoSystems

	Advanced Custom Fields PRO
		Version: 5.7.13
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 6.87
		Author: ServMask

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Ele Conditions
		Version: 1.0.5
		Author: Liviu Duda

	Ele Custom Skin
		Version: 1.0.9
		Author: Liviu Duda

	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.14
		Author: Namogo

	Elementor Pro
		Version: 2.5.2
		Author: Elementor.com

	Flexible Checkout Fields
		Version: 1.9.1
		Author: WP Desk

	Formidable Forms
		Version: 3.06.03
		Author: Strategy11

	Formidable Forms Pro
		Version: 3.06.03
		Author: Strategy11

	Google Maps Easy
		Version: 1.9.17
		Author: supsystic.com

	Intuitive Custom Post Order
		Version: 3.1.2
		Author: hijiri

	Ocean Extra
		Version: 1.5.3
		Author: OceanWP

	Profile Builder - Customization Toolbox Add-On
		Version: 1.0.4
		Author: Cozmoslabs, Georgian Cocora

	Profile Builder - Custom Profile Menus Add-On
		Version: 1.0.9
		Author: Cozmoslabs, Cristophor Hurduban

	Profile Builder - MailChimp Add-On
		Version: 1.1.8
		Author: Cozmoslabs, Mihai Iova

	Profile Builder - WooCommerce Sync Add-on
		Version: 1.5.6
		Author: Cozmoslabs, Adrian Spiac

	Profile Builder Pro
		Version: 2.9.7
		Author: Cozmoslabs

	ShiftNav Pro - Responsive Mobile Menu
		Version: 1.6.3
		Author: Chris Mavricos, SevenSpark

	Simple Image Sizes
		Version: 3.2.0
		Author: Rahe

	Slider Revolution
		Version: 5.4.8.1
		Author: ThemePunch

	Table Rate Shipping
		Version: 1.2.1
		Author: Kahanit

	UberMenu 3 - The Ultimate WordPress Mega Menu
		Version: 3.3.1
		Author: Chris Mavricos, SevenSpark

	Wine Details
		Version: 1.0
		Author: MindProcess

	WooCommerce
		Version: 3.5.7
		Author: Automattic

	WooCommerce Multilingual
		Version: 4.4.2.1
		Author: OnTheGoSystems

	Woo Discount Rules
		Version: 1.7.11
		Author: Flycart Technologies LLP

	WPML Multilingual CMS
		Version: 4.2.4.1
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.10.2
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.8.3
		Author: OnTheGoSystems


== Log ==
	: 
JS: showing 9 of 9JS: 2019-02-05 13:38:16 [error X 1][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.4.5:2:41563] undefined is not an object (evaluating \'i.attributes\') 
JS: 2019-03-09 16:33:52 [error X 2][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.3:2:170817] undefined is not an object (evaluating \'this._parent.errors\') 
JS: 2019-03-10 01:25:54 [error X 1][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:12787] Syntax error, unrecognized expression: unsupported pseudo: add_to_cart_button 
JS: 2019-03-18 12:19:54 [error X 1][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.8:2:53459] undefined is not an object (evaluating \'this.ui.sliders.filter(\'[data-input=\"\'+t+\'\"]\')[0].noUiSlider\') 
JS: 2019-03-18 16:22:02 [error X 4][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.8:736:39] self.attributes[control.name].each is not a function. (In \'self.attributes[control.name].each(function (item) {
					styleFields.push(self.getStyleControls(control.fields, item.attributes));
				})\', \'self.attributes[control.name].each\' is undefined) 
JS: 2019-03-18 16:25:58 [error X 67][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-admin/load-scripts.php?c=0&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.1.1:10:5130] undefined is not an object (evaluating \'l[m]\') 
JS: 2019-03-18 16:28:27 [error X 3][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.8:2:75360] setting getter-only property \"type\" 
JS: 2019-03-27 00:02:39 [error X 10][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.10:2:6881] undefined is not an object (evaluating \'this.ui.select.select2\') 
JS: 2019-03-28 00:04:15 [error X 3][https://dev.hnc.pt/xxxxxxxxxxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.10:2:73100] undefined is not an object (evaluating \'this.panel.currentView\') 

Log: showing 20 of 272019-03-26 12:56:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.0',
)]
2019-03-26 12:56:55 [info] elementor-pro::elementor_pro_updater Started 
2019-03-26 12:56:55 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-26 12:56:57 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-26 12:56:57 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-26 12:57:00 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-26 12:57:00 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-26 12:57:03 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-26 12:57:03 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-26 12:57:04 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-26 12:57:04 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-26 12:57:05 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-26 12:57:05 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-26 12:57:07 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-26 12:57:07 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-26 12:57:07 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-26 12:57:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.0',
)]
2019-03-26 23:07:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-26 23:07:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.0',
  'to' => '2.5.1',
)]
2019-03-27 18:07:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.1',
  'to' => '2.5.2',
)]

PHP: showing 6 of 6PHP: 2019-03-26 13:18:29 [notice X 17][/home/hncptusr/public_html/dev/xxxxxxxxxxxxxx/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::97] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-26 13:27:38 [notice X 8][/home/hncptusr/public_html/dev/xxxxxxxxxxxxxx/wp-content/plugins/elementor-pro/modules/query-control/module.php::280] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-27 17:05:29 [error X 14][/home/hncptusr/public_html/dev/xxxxxxxxxxxxxx/wp-content/plugins/elementor/includes/fonts.php::649] Allowed memory size of 41943040 bytes exhausted (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-27 17:07:04 [error X 1][/home/hncptusr/public_html/dev/xxxxxxxxxxxxxx/wp-content/plugins/elementor/includes/fonts.php::64] Allowed memory size of 41943040 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-27 17:12:50 [error X 1][/home/hncptusr/public_html/dev/xxxxxxxxxxxxxx/wp-content/plugins/elementor/includes/fonts.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 32768 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-27 17:50:25 [notice X 3][/home/hncptusr/public_html/dev/xxxxxxxxxxxxxx/wp-content/plugins/elementor-extras/extensions/display-conditions.php::621] Undefined index: ee_display_conditions_enable [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor Pro v2.5.3

Feel free to update!

**Comment by momo-fr** [comment]
> Le 31 mars 2019 à 16:42, shilo-ey <notifications@github.com> a écrit :
> 
> This issue has been fixed in Elementor Pro v2.5.3
> 
> Feel free to update
> 
Hi, I am very sorry but the query not work correctly with the 2.5.3, I have same issue with partial products, incorrect number of products and some problem to visualize the complete shop page.

Regards.

Jean

—
06 75 55 17 43

http://www.momofr.net

**Comment by shilo-ey** [comment]
@momo-fr 

Please contact our support at support @elementor.com for guidance in resolving this issue and **mention that you were directed by me and reference this issue.**

When you contact the support please provide as many details as possible (including credentials for logging in to your environment, pages that are affected and description of the desired behavior)

Thanks.

**Comment by shilo-ey** [comment]
@StreetDog1971 @momo-fr 

Can you please provide us some login credentials for debugging this issue?

If so - please send it to our support and mention that you were directed by me and reference this issue.

Thanks
