### ISSUE TITLE
Manual query post widget not working

### ISSUE THREAD

**Issue by KiQdev** [elementor/elementor#7634]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
In the latest versions 2.5.10 and pro 2.5.0, post widget manual query for pages don´t work, it displays all pages.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @KiQdev 

Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by pmfarmer** [comment]
Thank you @shilo-ey - this affects my website as well.
Do you know when you expect a patch to be released?
#planning :)

**Comment by shilo-ey** [comment]
Hi @KiQdev @pmfarmer 

This issue has been fixed in Elementor Pro v2.5.2

Feel free to update!

**Comment by pmfarmer** [comment]
Thank you @shilo-ey. Should that be available on the Wordpress admin > Plugins? 

I'm not seeing it yet.

**Comment by KiQdev** [comment]
Seems like Terms categories are not working now for Post widget in 2.5.2

**Comment by shilo-ey** [comment]
[**@KiQdev**](https://github.com/KiQdev) commented on [Mar 28, 2019, 12:15 PM GMT+2](https://github.com/elementor/elementor/issues/7634#issuecomment-477533077 "2019-03-28T10:15:57Z - Replied by Github Reply Comments"):
> Seems like Terms categories are not working now for Post widget in 2.5.2

Hi @KiQdev 
Kindly create a new issue with steps to reproduce and system info.

Thanks!

**Comment by MikeG327** [comment]
Yepk this jacked up terms categories and tags for me too on sites that have lots of categories and tags. Broke homepages and landing pages.
