### ISSUE TITLE
Custom Cart pop up for Woocommerce with elementor

### ISSUE THREAD

**Issue by Smaakgenot** [elementor/elementor#7637]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

A customer get a quick overview of all the items in the cart + the possibility to add related items. It will help to create upsells (many webshops have this feature)

**Describe the solution you'd like**

When you click on the button 'add to cart' a popup will show up with a mini 'cart'. See for a great example the following demo: http://demo.xootix.com/cart-pop-up-for-woocommerce/

It will be great if a user of elementor  can customise this popup, for example add related items  to the cart or give them extra important information. 

**Describe alternatives you've considered**

There are 3rd party plugins (check the link above as example) but this is less reliable for future updates. 
<img width="1399" alt="Schermafbeelding 2019-03-27 om 13 32 12" src="https://user-images.githubusercontent.com/48989511/55076285-551fb000-5095-11e9-8a1c-63bb2f002f53.png">
<img width="1021" alt="Schermafbeelding 2019-03-27 om 13 30 35" src="https://user-images.githubusercontent.com/48989511/55076295-5d77eb00-5095-11e9-81fb-958d107c7d12.png">

**Additional context**

**Comment by shilo-ey** [comment]
Hi @Smaakgenot 

Thank you for your feedback!

I merged this issue with #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

For the meanwhile, you can set an ID on the add to cart button, and on click - set a rule (Advanced tab > open on selector) to open the popup when clicking on it.

Thanks again!
