### ISSUE TITLE
Is there a way to programmatically update page settings?

### ISSUE THREAD

**Issue by mauryaratan** [elementor/elementor#7638]
I've tried `elementor.settings.page.setSettings()` which doesn't throw any errors but the editor doesn't reflect the changes.

What I'm trying to do is reset/update some settings via JS. I also tried `elementor.settings.page.save()` and `elementor.settings.page.trigger( 'save' );` to no success.

Any tips towards this are highly appreciated 🙏

**Comment by hogash** [comment]
Hey,

Maybe something like this could help if it's triggered by a specific setting:

```elementor.settings.page.addChangeCallback("any_page_setting", function(newValue) {
    elementor.saver.update({
        onSuccess: function() {
            elementor.reloadPreview();

            elementor.once("preview:loaded", function() {
                elementor.getPanelView().setPage("page_settings");
            });
        }
    });
});
```

It'll reload the preview and will also open back the page settings panel.

**Comment by mauryaratan** [comment]
Thanks @hogash, but unfortunately that didn't help.

On further investigation, I found what I needed :)

`elementor.settings.page.model.setExternalChange(key, value)` does the trick. While the preview takes the effect immediately, the editor still shows the old value. Running `elementor.panel.currentView.getCurrentPageView().render();` takes care of that and updates the value in editor as well.

I can't say yet if this is the best way to do it but it looks and works so far.

**Comment by Paras16699** [comment]
@mauryaratan, I'm looking for a method to programmatically update a control's value using JS so that it also reflects on the frontend. More description here - #9154  

Any idea how to do that? Any help would be much appreciated.
