### ISSUE TITLE
Text formatting within sidebar widgets

### ISSUE THREAD

**Issue by PeteBartram** [elementor/elementor#7639]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The sidebar widget does not offer any text formatting ability.  A Recent Posts widget placed in it had headings that were far too big & I couldn't edit them; there doesn't seem to be any other way to ediit the style of that text.

**Describe the solution you'd like**
A Style option similar to that used for the Text Editor & other sections would be ideal. 

**Describe alternatives you've considered**
I've had a very helpful suggestion (from @cavalierlife) via the WP Forum to set a CSS class for the sidebar widget, then specify the size for (in this particular case) h3 via the Customizer Additional CSS option.  This worked well.

**Additional context**

**Comment by SniffleValve** [comment]
+1
I find this to be a glaring omission to this widget.
Cheers!
Lyle

**Comment by lior-sh** [comment]
@PeteBartram 
Close, this is WordPress native widget, you can use custom CSS to customize it
