### ISSUE TITLE
Image Carousel not showing when saved as global widget

### ISSUE THREAD

**Issue by andrijanasv** [elementor/elementor#7643]
Hi - I did not test with disabled/default theme, not possible in my case. 

Image carousel that is also a Global widget does not show on "live" page. This started happening with the latest release (2.5.10/2.5.1).

Hope the attached screen recording helps in reproducing the issue
[global image carousel widget bug.mov.zip](https://github.com/elementor/elementor/files/3014623/global.image.carousel.widget.bug.mov.zip)
.

Unlinking from Global widget resolves the issue, needles to say, it took me a while to figure that out :)

Thanks,

Andrijana

**Comment by blaisck** [comment]
I update Elementor and my Image Carousel became a problem too,

and unlinking from Global Widget resolve the issue too, but if a problem like this happens again and again, it will become a pain in the ass.

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by shilo-ey** [comment]
Please update to the latest version of Elementor and Elementor Pro, this should fix the issue.


Thanks
