### ISSUE TITLE
Allow use of all CSS units

### ISSUE THREAD

**Issue by squadcar** [elementor/elementor#7644]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I find the lack of certain units for certain design aspects frustrating at times. Not having access to em/vh/vw, and only px (or %), or vice versa, or something other arbitrary arrangement. I realize this is likely due to the fact that use of certain units in specific situations might break the layout, resulting in more support requests. For experienced developers though trying to use Elementor to save time when building sites, it would be a welcome feature to have access to way more unit options when defining rules.

**Describe the solution you'd like**
Access to all CSS units all the time everywhere. Maybe as a "developer mode" in the settings or something with a warning.

**Describe alternatives you've considered**
Custom CSS, but this is bothersome, and at some point begins to make one question why they're using a page builder in the first place.

**Comment by twiginteractive** [comment]
This is part of an ongoing & frustrating lack of flexibility in the CSS UI - check out #2219 
Really hope someone reads + addresses it.

**Comment by Helmi** [comment]
I want to support the idea of a developer mode for stuff like this. I get why you wanna hide some stuff from the average joe and better not clutter the UI too much but for a more advanced group of customers this stuff is frustrating.

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by tristanleboss** [comment]
+1 Having to ressort to custom css for this is not admissible.

Btw, I hope they will start to address some of the features power users ask for because, recently, the word "frustration" and its derivatives can be read on a lot of issues. @thimfy hidden comment is also a manifestation of this frustration. The clear lack of communication from the Elementor team is dramatic.

**Comment by owynter** [comment]
It's sad that this is a 6 month old issue that's not being addressed. I literally just signed up for  Git account to submit this as a feature request. Can't believe that there' so much variance between widgets/modules and even within when it comes to measurements. 

For responsive design, using px as a unit will only cause frustration because not every pixels is the same. I want to use best practices and create relative sizes as much as possible to keep things tidy no matter the format. It's so frustrating that this isn't being offered. +1 for a developer mode.

**Comment by gregamer** [comment]
I'm a new pro user and generally like the Elementor workflow and especially speed. While building my first page with it I was quite limited with not being able to use custom units in layout related parameters like column width, elements paddings and margins etc.

Example of what I'd like to achieve:
2 column layout, first 100px wide, 2nd rest of it (could be easily achieved with 100px, calc(100% - 100px)

Use mixed units when setting paddings/margins: e.g. top: 10px, right: 4vw, bottom: 20px, left 4vw, or even use calc: top: 10px, right: calc(10px + 1vw), bottom: 20px, left: calc(10px + 1vw)

Solution would be as easy as adding a new option (CUSTOM) in the unit selection:
![elementor-custom-units](https://user-images.githubusercontent.com/4144796/70427435-ffe5cc00-1a74-11ea-92a3-95e9ebc49b44.png)


Reading through all the issues here I'm now starting to doubt if I made the right decision buying a pro. I mean so far the Elementor is by far the easiest and fastest to use of all page builders but lack of functionalities and user support is worth as much (if not more) than UI and UX.

This is not the only issue I have with Elementor but I'll rather find appropriate topic and share my thoughts there.

**Comment by arielk** [comment]
Long time, but I merged this issue with another issue https://github.com/elementor/elementor/issues/2219 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello,

in order to keep the conversation only in one place, I'm closing the comments here.

Please, feel free to continue the conversation there: 👉 [#2219](https://github.com/elementor/elementor/issues/2219)

Thanks! 🙏

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
