### ISSUE TITLE
Mobile Background Image Settings

### ISSUE THREAD

**Issue by adamwayne** [elementor/elementor#7647]
Since we are in a mobile-first world, I am running into an issue with mobile imagery. 

When I create a section and add a background image to that section, I lose out on options that I have in the desktop view. For example, I don't have the option to use the "cover" function. 

If I want to have a specific image for mobile, right now my workflow is as follows:

1. Work with a section for desktops and hide this for mobile
2. Duplicate that section and hide this on tablets and desktops
3. Go to desktop view
4. Add an image
5. Change to mobile view
6. Add the cover feature

It would be much better if I have the same options on desktop view as I do on mobile view, regardless.

Thanks!

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by black-eye** [comment]
+1 Had the same issue too.

**Comment by arielk** [comment]
This issue has been resolved in Elementor v2.4.0 ([4 years ago](https://elementor.com/blog/responsive-image-background/))

Thanks!
