### ISSUE TITLE
Remove widget settings from Advanced Tab

### ISSUE THREAD

**Issue by dtmgs** [elementor/elementor#7648]
Is it possible to remove some settings from widgets advanced tab?

![](https://user-images.githubusercontent.com/362935/51611655-b5da2180-1f5a-11e9-8ef0-a023523afe71.png)

I would like to remove some and leave Responsive and Custom CSS since other settings are not applicable on the widget im working on.

Kindly share code snippet to remove "background" section in advanced tab.

**Comment by bainternet** [comment]
@dtmgs 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by welly2103** [comment]
@bainternet here is another one who would likely see this implemented :D keep up the great work on elementor 👍

@dtmgs 

There is no hook or function for this, but you can override the common widget anyway, so just override the `Widget_Common` and return the `_register_controls` function. In `_register_controls` normally all default controls will be set, so in this case none. This will not affect the general "Inner Section" Element, but all other widgets!

The advanced tab should be completely removed.

Not really great, but as there is no implementation for this, its currently the only way in my eyes.

Example:

```sh
<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class Widget_Common extends \Elementor\Widget_Base
{

    public function get_name()
    {
        return 'common';
    }

    public function show_in_panel()
    {
        return false;
    }

    protected function _register_controls()
    {
        return;
    }
}
```

Just implement this, as if its a custom / new widget (https://developers.elementor.com/creating-a-new-widget/)

**Comment by black-eye** [comment]
+1

**Comment by wayheming** [comment]
+1

**Comment by dionysos-ambelonas** [comment]
+1
