### ISSUE TITLE
Double scrollbar on Popup when popup height is greater than viewport

### ISSUE THREAD

**Issue by peterhrnciar** [elementor/elementor#7650]
## Prerequisites

[x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[x] The issue still exists against the latest stable version of Elementor.

## Description

I'm using elementor popups and if the popup is higher than vh, it has v-scrollbar inside itself. Is it possible to have the popup higher than vh and have the scrollbar on the page instead of inside the popup? I've tried custom CSS, but even with Disable Page Scrolling setting on the background page still shows scrollbar on the right side so when popup opens there are two scrollbars on the right side.

## Steps to reproduce

1. Create popup which is higher than vh

## Isolating the problem
[x] This bug happens with only Elementor plugin active (and Elementor Pro).
[x] This bug happens with a default WordPress theme active.
[x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: (Debian) v5.5.62
	PHP Version: 7.1.26-1+0~20190113101856.12+jessie~1.gbp7077bb
	PHP Max Input Vars: 2500
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://wordpress-231677-779344.cloudwaysapps.com
	Home URL: https://wordpress-231677-779344.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: nWave
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.7.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 1.7.1
		Author: Brainstorm Force

	Breeze
		Version: 1.0.10
		Author: Cloudways

	Custom Fonts
		Version: 1.0.7
		Author: Brainstorm Force

	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.2
		Author: Elementor.com
</details>

**Comment by shilo-ey** [comment]
Hi, 

It is not recommended using this kind of height behavior, but if you wish so you can add the following Custom CSS:
```CSS
.elementor-popup-modal .dialog-message.dialog-lightbox-message {
    overflow: hidden;
}
```

That should hide the scrolling inside the popup and enable it outside of it.

Thanks

**Comment by zavod-dev** [comment]
This does not work anymore. It removes the scrollbar but locks scrolling

**Comment by punktoy** [comment]
> 
> 
> This does not work anymore. It removes the scrollbar but locks scrolling

I do this and works

`selector .elementor-section{
    padding: 0px !important;
}`

Put this into the css section in elementor pro

**Comment by 517Design** [comment]
Use this 

`.elementor-popup-modal .dialog-message.dialog-lightbox-message::-webkit-scrollbar {display: none;}`

Add it to your Popup Settings > Advanced > Custom CSS

screenshot: https://snipboard.io/VispU2.jpg

**Comment by theedebugger** [comment]
> Hi,
> 
> It is not recommended using this kind of height behavior, but if you wish so you can add the following Custom CSS:
> 
> ```css
> .elementor-popup-modal .dialog-message.dialog-lightbox-message {
>     overflow: hidden;
> }
> ```
> 
> That should hide the scrolling inside the popup and enable it outside of it.
> 
> Thanks

thank you so much
