### ISSUE TITLE
Make a Popup move the website gutter/width with it 

### ISSUE THREAD

**Issue by jcmatoskx** [elementor/elementor#7655]
Hello! I created an Elementor popup to use as a vertical sidebar navigation mega menu, however when it is open on smaller screens it blocks part of the website.

is it possible to make it so that when the vertical popup "sidebar" appears, it also forces the website gutter/width to move the same amount of pixels to the right (the popup appears on the left side)

A functional example of this is this website: https://www.pccomponentes.com/
When you press the hamburger button on the left, as I am building something very similar.

Thank you in advance for the attention and advice, much love!

**Comment by shilo-ey** [comment]
I merged this issue with #6225, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
