### ISSUE TITLE
Best way to add control for existing widgets

### ISSUE THREAD

**Issue by carlosromanxyz** [elementor/elementor#7657]
Hello, I'm looking for the best way to add extra fields to an existing widget without the use of plugins, only via functions.php

For example:

I need to add 3 extra buttons to the "Posts list" widget, show a Custom Meta Field with the excerpt and other data that is included in a Custom Post Type.

The documentation only refers to the creation of controls for new widgets, but nothing says for existing widgets. https://developers.elementor.com/register-widget-controls/
https://developers.elementor.com/add-controls-to-widgets/

I tried to add one to an existing widget by following this example https://gist.github.com/Basilakis/aecec9d0d2d0c7cc3b8c260892167b6b, but my widget belongs to Elementor Pro.

I appreciate the suggestions.

**Comment by hogash** [comment]
Try hooking into `elementor/element/{$section_name}/{$section_id}/before_section_end` https://code.elementor.com/php-hooks/#elementorelementsection_namesection_idbefore_section_end  and you can add your own controls. Try searching the issues (closed one) you'll find tons of examples , eg: https://github.com/elementor/elementor/issues/6171#issuecomment-439184421 .

**Comment by shilo-ey** [comment]
Hi @carlosromanxyz 

Thanks for your feedback,

Follow the instructions [provided here](https://github.com/elementor/elementor/issues/6499).

Thanks!

**Comment by shahmanish877** [comment]
How can I add control to global Site settings? I need to add global color for woocommerce. Any idea how can I implement it?

**Comment by faihadev** [comment]
Hi,
how to add a new control section for widget "column"
![FireShot Capture 039 - Elementor - tt - bethub pro](https://user-images.githubusercontent.com/90391918/159476825-ef7904f2-1c1a-49e8-bf7e-e77330f8bdb0.png)
|Here I need a control section just behind the layout

**Comment by hmbashar** [comment]
I've explored various methods, but I find this particular way of adding control to existing Elementor widgets to be the easiest. I specifically applied this to the tabs widget.



```
// add color control for tab triangle
add_action('elementor/element/before_section_end', function( $section, $section_id, $args ) {		
	if( $section->get_name() == 'nested-tabs' && $section_id == 'section_tabs_style' ){				
		$section->add_control(
			'abc-tab-tringle-color' ,
			[
				'label'        => 'Traingle Color',
				'type'         => Elementor\Controls_Manager::COLOR,
				'selectors' => [
					'{{WRAPPER}}.abc-var-tabs .e-n-tabs-heading > button[aria-selected="true"]:after' => 'border-left-color: {{VALUE}}',
				],
				'prefix_class' => 'abc-tab-tringle-color-',
			]
		);
	}
}, 10, 3 );
```

[Here is code on my Github Profile](https://gist.github.com/hmbashar/938df2ebe91afb170a5dfb08b0c635b3)
