### ISSUE TITLE
Empty Posts and Portfolio Queries

### ISSUE THREAD

**Issue by s-e-privalov** [elementor/elementor#7659]
After upgrading to the latest version of Elementor (2.5.1 and 2.5.2 too), some (not all) pages have lost blog entries and portfolios. In the Element editor, I choose "Include by Term" option and the name of the rubric in the Query field, but the entries are not shown. Just an empty field. When I rolled it back to the previous version ( 2.4.8), it works well. 

I tried to deactivate all plugins - it did not help. 
I tried to change the Theme - it did not help.
I tried to deactivate my licence and activate it on my other sites - it works well...

The problem for me, as i see is in file elementor-post-query.php - start from line 218.

By default $term_data = get_term_by( 'term_taxonomy_id', $id); returns term_id, but expected - term_taxonomy_id.
I have changed this part of code to $term_data = get_term_by( 'id', $id, 'category'); - it works well. 

So where is the problem - somewhere in my MySql database or in Elementor-query? Can anyone help me to resolve this problem?

**Comment by s-e-privalov** [comment]
No one knows?

**Comment by shilo-ey** [comment]
Hi @s-e-privalov 

Thanks for reporting.

We will address this issue soon and release a patch.

I merged this issue with #7653, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
