### ISSUE TITLE
Countdown reset feature. 

### ISSUE THREAD

**Issue by blackgoku** [elementor/elementor#7663]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

To run contest or automatic sales pages or frequent announcements of offers. 
If you search on github 'countdown' you will notice that this same features is requested in 30+ threads. 

**Describe the solution you'd like**

A option to reset the countdown like the other ootion already present. 

**Describe alternatives you've considered**

I am searching for this from a year and didnt find anything, even not a 3rd party plugin. 
coding it is also not feasible because have to code again after every update and as elementor rolls new update very week or 2, its very time consuming and  complex.

**Comment by blackgoku** [comment]
i have found the solution to this problem, need to add some custom codes.
If anyone need help with it contact me on skype or gmail - swapnilsbl17@gmail.com (same id for both)

**Comment by rafaelfigueiredo-l** [comment]
+1 wanting this feature.

**Comment by lior-sh** [comment]
Hi @blackgoku,

 The code made properly doesn’t need to be rewritten after every update.

Thanks for your feedback!
