### ISSUE TITLE
Subscription to MailChimp is not running in a Popup

### ISSUE THREAD

**Issue by haemeulrich** [elementor/elementor#7665]
We have a form for a MailChimp list (made with Elementor Form Widget). As long as we have this form in a normal page the subscription process with MailChimp ist running.
As soon as we copy the very same form into a popup the subscription process is not working.

A bug?

We are using
- WordPress - 5.1.1	
- Elementor - 2.5.10	By Elementor.com	
- Elementor Google Map Extended - 1.1.5	By InternetCSS	
- Elementor Pro - 2.5.1	By Elementor.com

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by bainternet** [comment]
@haemeulrich 

Please update Elementor Pro, re-save the form and try again and see if the issue still persists. if it does, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
