### ISSUE TITLE
Popup Template selector not showing popup templates

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#7667]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I create a popup template, the intention is to be able to insert it in a new popup. However when I click on "my templates" when creating a new popup, I can see only pages and sections, but no popups.

Furthermore, if I export a popup as a json and then at then create a new popup, and try to import the json template, it creates a new popup (I guess a template), then shows me the template it just created under my templates, which I can then select.

The result of this process is that for 10 popups based on one template, I end up with 20 pupups in WP-admin and no way to figure out which ones are actually used on the front end.

## Steps to reproduce

Try to create multiple popups based on one template. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Not Relevant for this bug report as it is a workflow design issue, rather than a program error/crash etc.

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by lior-sh** [comment]
Hi @taropaa,

This issue resolved in the last version.
Thanks.
