### ISSUE TITLE
Single Post Template issue with LayersWP + ELEMENTOR

### ISSUE THREAD

**Issue by rafaelfigueiredo-l** [elementor/elementor#7669]
Hi,

I'm having an issue with elementor and layers wp. When I assign a template to all my single posts then create a post without using elementor the single post template is showed. But if I try to edit my post with Elementor the single post template is disabled, and my post appears without styles.

Elementor Version: 2.5.10
Elementor Pro: 2.5.2
LayersWP Version: 1.0.1

Someone can confirm this issue?

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by rafaelfigueiredo-l** [comment]
It was solved. My team found that the bug was with the wp layers. Thanks. This issue can be closed.
