### ISSUE TITLE
add social functon that is popular in Asia, ex: Line App

### ISSUE THREAD

**Issue by cagewei** [elementor/elementor#7672]
sorry, My English grammar is very bad.

## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We always need to use the social function that Line App, It's popular App in Asia, Ex: Japan, Taiwan, Korea, Thailand, Vietnam

**Describe the solution you'd like**
we can select the LINE button in the Share Buttons Widget (Pro), 
or tell me what can I do to call function in child theme files.

**Describe alternatives you've considered**
I have two planing but it's not easy for designer to maintain.
1. set function
add_filter('the_content', 'LineSocialPlugin');
function LineSocialPlugin($content){
// load Line js
$content .= '<script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>';
// reset Line default style
$content .= '<style>.lineWrap{margin: 1rem 0 0 0;}.lineWrap iframe{ margin-right: .5rem; }</style>';
// add Line share button
$content .= '<div class="line-it-button" data-lang="en" data-type="share-a" data-url="'. get_permalink() .'" style="display: none;"></div>';
}

2. use class and coding js
var $thisUrl = document.location.href + "?socialShare";		
$('.shareToLine').attr({href:"http://line.me/R/msg/text/?" + $thisUrl , target:"_blank"});

3. fix share-buttons module...............

**Additional context**
1. LIN Social API
https://developers.line.biz/en/reference/social-api/

2. Icon
https://fontawesome.com/icons/line?style=brands

3. front-end setting
https://social-plugins.line.me/en/how_to_install

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by cagewei** [comment]
> Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

Unfortunately....., I have spent $199.

**Comment by shilo-ey** [comment]
Hi @cagewei 

Thanks for your feedback,
As mentioned in #2739 and in #7330, we will look into adding this feature as soon as we will integrate FontAwesome5 icon library.

Therefore, I merged this issue with #4430, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
