### ISSUE TITLE
Missing custom order in product categories query

### ISSUE THREAD

**Issue by itsgauravjain22** [elementor/elementor#7675]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor Pro.

**What problem is your feature request going to solve? Please describe.**
When I showcase my product categories on my home page, I have no freedom to order which category will show first and likewise. Elementor currently lacks custom ordering of woocommerce product categories. There exist only order by Name, Slug, Description, and Count, which is not useful for my purpose.

**Describe the solution you'd like**
I want elementor to have custom ordering by drag and drop product categories.

**Describe alternatives you've considered**
Curremtly, I am using UX Builder shipped with my flatsome theme, which has this nice option.

**Additional context**
![screenshot-www kalashcards com-2019 03 30-16-01-12](https://user-images.githubusercontent.com/11793930/55275000-48a18e80-5305-11e9-9748-c3039b956938.png)

**Comment by shilo-ey** [comment]
Hi @itsgauravjain22 

Thanks for your feedback.

This feature is not supported in Elementor, but you can use 3rd party extensions to achieve this (example: [https://wordpress.org/plugins/intuitive-custom-post-order/](https://wordpress.org/plugins/intuitive-custom-post-order/) )

Thanks.

**Comment by itsgauravjain22** [comment]
Thanks for the prompt reply along with another plugin hack. It would be great if elementor pro supports this feature in its own plugin. It's ridiculous to install another plugin for such small functionality.
As mentioned, I am using UX Builder for this purpose shipped with the flatsome theme.
![1](https://user-images.githubusercontent.com/11793930/55379588-327d1380-553b-11e9-8fd8-75126353ce71.png)

**Comment by iMiek** [comment]
In the product categories widget I need to order the query by "Category Order".  I ordered more than 100 woocommerce categories. Please help!!!! Can i hook in or code it myself???

**Comment by mocheaz** [comment]
Any solution on this?

We have the same request

**Comment by DavidTheSimon** [comment]
It would be great to have this feature. One more request from me.

**Comment by HQv2** [comment]
This feature is much needed. Thanks 👍

**Comment by drumanshoo** [comment]
Why is this not included already?! Please add. This is core WC functionality.

**Comment by murxaxo** [comment]
The same problem, incredible that there is no option.
