### ISSUE TITLE
error 400 when saving after copying widgets or using global widgets

### ISSUE THREAD

**Issue by legion1978** [elementor/elementor#7679]
theres an issue when copying widgets from one page to another (same site) or using global widgets, the page wont save (error400). after deleting the copied widget (or page reload), it saves correctly

**Comment by shilo-ey** [comment]
Thanks for reporting,

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it we simply can't help.
In your case, we can't replicate the issue. I recommend you to contact our support for more personalized inspection of the issue.

Thanks.
