### ISSUE TITLE
Price list - Split Title and Price Styleing

### ISSUE THREAD

**Issue by CrazyShades91** [elementor/elementor#7688]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
With the styling of the price and title in the Price List Widget linked you can't have larger headers without have huge prices. 
Sometimes you don't want huge prices just slightly larger headers or the other way around and there is no easy way to do this when the styling of the two elements are linked. 

**Describe the solution you'd like**
The ability to style the price and title in the Price List Widget separately.

**Describe alternatives you've considered**
You can use heading tags directly on the content but it breaks the rest of the formatting and creates more work. 
You can also use a header outside the widget but again, it looses flow and looks out of place.

**Additional context**
![Screen Shot 2019-04-01 at 11 05 53 am](https://user-images.githubusercontent.com/47806430/55297298-925ab800-5470-11e9-93c6-93d42b020d04.png)

**Comment by ramiy** [comment]
+1

**Comment by fabianenzensperger** [comment]
+1

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!
