### ISSUE TITLE
Weird set of options

### ISSUE THREAD

**Issue by markusila** [elementor/elementor#7696]
I was exploring my database - wp_postmeta table,
Weird, but besides the **_elementor_data** metakey i have another one, taking lots of space,
it is called _elementor_data_previous
![Screen Shot 2019-04-01 at 17 24 28](https://user-images.githubusercontent.com/5987968/55339516-204f9680-54a3-11e9-8e5f-983c4b1d92cf.png)

Is that by Elementor? Or some scam?

**Comment by bainternet** [comment]
@markusila 	


Not by Elementor, probably a backup plugin.

thanks.
