### ISSUE TITLE
Uses Polylang, when Editing page with Elementor can't add translated images

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#7697]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

My site is some years old and dual-languaged with Polylang (Swedish (default) and English). I have translated media which in Polylang case means that the image file is shared between languages but the meta information for the image is translatable. It worked very well. Six months ago added Elementor Pro to the site. The problem now is I can't add English images to a English page when editing in Elementor. This must be a bug.

## Steps to reproduce

I can open the English page and edit the page in a regular (non-Elementor way), open the Media finder and add an English image file to the Featured image field. It works as expected.
If I edit the exact same English page in Elementor, and open the Media finder to add an image, the images shown are the Swedish ones. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - (GPL) v5.7.25
	PHP Version: 7.2.16
	PHP Max Input Vars: 3000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: sv-SE
	Timezone: Europe/Stockholm
	Debug Mode: Inactive

== Theme ==
	Name: customizr-pilen
	Version: 1.0
	Author: Administrator
	Child Theme: Yes
	Parent Theme Name: Customizr
	Parent Theme Version: 4.1.25
	Parent Theme Author: nikeo

== User ==
	Role: administrator
	WP Profile lang: sv_SE
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Advanced Menu Widget
		Version: 0.4.1
		Author: Ján Bočínec

	Advanced Sidebar Menu
		Version: 7.5.1
		Author: Mat Lipe

	Autoptimize
		Version: 2.4.4
		Author: Frank Goossens (futtta)

	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Blackhole for Bad Bots
		Version: 2.3
		Author: Jeff Starr

	Blighty Explorer
		Version: 2.2.1
		Author: Blighty

	Block Bad Queries (BBQ)
		Version: 20190311
		Author: Jeff Starr

	Broken Link Checker
		Version: 1.11.8
		Author: ManageWP

	Check Email
		Version: 0.5.5
		Author: Chris Taylor

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.25
		Author: SeedProd

	Content Views
		Version: 2.1.3.2
		Author: Content Views

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.3
		Author: Elementor.com

	Enable Media Replace
		Version: 3.2.8
		Author: ShortPixel

	Feed Them Social (Facebook, Instagram, Twitter, etc)
		Version: 2.6.7
		Author: SlickRemix

	Formidable Forms
		Version: 3.06.03
		Author: Strategy11

	Formidable Forms Pro
		Version: 3.06.03
		Author: Strategy11

	GA Google Analytics
		Version: 20190311
		Author: Jeff Starr

	Google Photos & Picasa Viewer Pro
		Version: 3.2
		Author: Cheshire Web Solutions

	Google XML Sitemaps
		Version: 4.1.0
		Author: Arne Brachhold

	Inline Google Spreadsheet Viewer
		Version: 0.13.0
		Author: Meitar Moscovitz <meitarm+wordpress@gmail.com>

	Instagram Feed
		Version: 1.11.3
		Author: Smash Balloon

	Jetpack by WordPress.com
		Version: 7.1.1
		Author: Automattic

	Livemesh SiteOrigin Widgets
		Version: 2.5.1
		Author: Livemesh

	Max Mega Menu
		Version: 2.6
		Author: megamenu.com

	Nextend Accordion Menu
		Version: 9.3.8
		Author: Nextend

	Page Builder by SiteOrigin
		Version: 2.10.1
		Author: SiteOrigin

	Page Templater For Elementor
		Version: 1.2.9
		Author: ThemeIsle

	Polylang
		Version: 2.5.2
		Author: Frédéric Demarle

	Polylang Connect for Elementor
		Version: 1.0.0
		Author: David Decker - DECKERWEB

	Polylang Theme Strings
		Version: 4.0
		Author: Modeewine

	Post SMTP
		Version: 1.9.6
		Author: Jason Hendriks, Yehuda Hassine

	Really Simple SSL
		Version: 3.1.3
		Author: Rogier Lankhorst, Mark Wolters

	Redirection
		Version: 4.1.1
		Author: John Godley

	Relevanssi
		Version: 4.1.3
		Author: Mikko Saari

	Reusable Content & Text Blocks by Loomisoft
		Version: 1.4.3
		Author: Loomisoft

	Self-Hosted Google Fonts
		Version: 1.0.1
		Author: asadkn

	Shortcake (Shortcode UI)
		Version: 0.7.4
		Author: Fusion Engineering and community

	ShortPixel Image Optimizer
		Version: 4.12.7
		Author: ShortPixel

	SiteOrigin Premium
		Version: 1.5.4
		Author: SiteOrigin

	SiteOrigin Widgets Bundle
		Version: 1.15.4
		Author: SiteOrigin

	smart Archive Page Remove
		Version: 2
		Author: Peter Raschendorfer

	The SEO Framework
		Version: 3.2.4
		Author: Sybre Waaijer

	The SEO Framework - Extension Manager
		Version: 2.0.4
		Author: Sybre Waaijer

	Toolset Types
		Version: 3.2.7
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.7.5
		Author: OnTheGoSystems

	UpdraftPlus - Backup/Restore
		Version: 1.16.10
		Author: UpdraftPlus.Com, DavidAnderson

	Widgets On Pages
		Version: 1.4.0
		Author: Todd Halfpenny

	Wordfence Security
		Version: 7.2.4
		Author: Wordfence

	WP Fastest Cache
		Version: 0.8.9.2
		Author: Emre Vona

	WP Store Locator
		Version: 2.2.22
		Author: Tijmen Smit

	YouTube
		Version: 13.1
		Author: EmbedPlus Team

== Log ==
	: 
Log: showing 20 of 272019-03-29 09:47:48 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-29 09:47:49 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-29 09:47:49 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-29 09:47:50 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-29 09:47:50 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-29 09:47:50 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-29 09:47:50 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-29 09:47:50 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-29 09:47:50 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-29 09:47:51 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-29 09:47:51 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-29 09:47:51 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-29 09:47:51 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-29 09:47:51 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-29 09:47:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.5.2',
)]
2019-04-01 14:49:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-01 14:49:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-01 14:49:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-01 14:49:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-01 15:00:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]

</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @tamelander 
Under Languages > Settings > turn off the Media option and see if it resolves your issue.

Anyway, I would recommend contacting Elementor support.

Thanks!

**Comment by tamelander** [comment]
I did contact the Elementor Techical support. But I got a not very helpful response from Soyket telling me to go with WPML, implying that everybody else besides me use WPML. 

"I am sorry but this has to be reported to polylang since they don't keep compatibility with us properly and we can't solve issues with a plugin from our end always. Our users use WPML and don't face such issues and they always are up to date with issues with us and try to resolve it with us. 
Many users use patches to work with polylang and Elementor. So, I would advise you to join our Facebook community and check with our users there as well on this if polylang support does not help you with this. "

The Media option in Polylang settings is just what I am already using: being able to translate the meta information for a media file.  I can't deactivate that as it would break the site.

**Comment by shilo-ey** [comment]
@tamelander 

Thanks for your response. 

Please contact our support at support @elementor.com for guidance in resolving this issue and **mention that you were directed by me and reference this issue.**

I'll make sure that you will get proper treatment

thanks.

**Comment by tamelander** [comment]
Thank you. I will do that. Much obliged.

**Comment by tamelander** [comment]
I hate to sound like a whiner, but I got a e-mail from Gabriel asking for an account and login 48 hours from now. I sent that. Still waiting now. Patience is a virtue, I've heard :).
