### ISSUE TITLE
Popup on buttons

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7699]
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

When using a button and adding a popup in a dynamic link. You can click the button but if you close the popup you cant open it again without a refresh.

Suggested solution to be that when the modal is closed the button is clickable to reopen the popup with settings to either continue or reset contents.

**Comment by shilo-ey** [comment]
Hi @stevewoody82 

Thanks for your feedback.

As you can see in [this screencast](https://www.useloom.com/share/3af4174f7bd3422390b5892abaf3be15), the popup should open multiple times.

Make sure you didn't set any other advanced rule or trigger to this popup.

Thanks
