### ISSUE TITLE
Large request body causes problems

### ISSUE THREAD

**Issue by tomsommer** [elementor/elementor#7701]
The way Elementor saves content data using admin-ajax, by sending the entire data blob as a non-file, triggers `SecRequestBodyNoFilesLimit` in ModSecurity2 (and sometimes `LimitRequestBody` in Apache).

The data should be sent as a POST file, or split into smaller chunks, in order not to trigger limits in WAF systems.

The problematic AJAX call is `action: elementor_ajax`, and on some pages the `Content-Length` in the request can be several MB

**Comment by tareqhassan** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/9674371/55390096-513dd300-5558-11e9-9151-9d661ad43094.jpg)

Is this the reason for why I'm facing this issue now? According to my network console, save entire page template trigger admin-ajax.php with 404 temporary and failed to save the page.

**Comment by shilo-ey** [comment]
@tomsommer 

Can you please export a JSON file of a page that it occurs in and upload it?

Thanks

**Comment by tareqhassan** [comment]
@shilo-ey I can send you my json file which is working in siteground but not working in hostpapa, a2hosting and namecheap.

**Comment by tomsommer** [comment]
@tareqhassan Your issue is not related, please open a new Issue about this.

**Comment by tareqhassan** [comment]
@tomsommer sorry for that... im not that much super pro like you. At least I can get an idea from your issue that "MAYBE" "undefined" error is showing only for the larger post templates only, like having 16+ sections in my end.

Whenever I split that template into two parts and save them, no errors. But whenever I tried to save it as a complete version, it failed. 

Not only that, my older page templates (the larger one) which I created last January and save them, export them without any issues, is also showing "undefined" errors now. The hosting is same, plugins are the same. Everything remains the same but now it is "undefined" :-(

**Comment by shilo-ey** [comment]
[**@tareqhassan**](https://github.com/tareqhassan) commented on [Apr 2, 2019, 3:06 PM GMT+3](https://github.com/elementor/elementor/issues/7701#issuecomment-478966393 "2019-04-02T12:06:11Z - Replied by Github Reply Comments"):
> @shilo-ey I can send you my json file which is working in siteground but not working in hostpapa, a2hosting and namecheap.

As mentioned in #7704 please contact our support for site-specific assistance

Thanks.

**Comment by bainternet** [comment]
[**@tomsommer**](https://github.com/tomsommer) commented on [Apr 2, 2019, 3:14 PM GMT+3](https://github.com/elementor/elementor/issues/7701#issuecomment-478968681 "2019-04-02T12:14:10Z - Replied by Github Reply Comments"):
> @tareqhassan Your issue is not related, at least I am not seeing "Undefined" errors when this occur.
> 
> @shilo-ey [elementor-1473-2019-04-02.zip](https://github.com/elementor/elementor/files/3033852/elementor-1473-2019-04-02.zip)
> 
> The .json is 3MB alone, so surely this will hit limits when saving.


Thanks for providing the JSON, It seems like you have an unusual amount of elements in that page which causes the large `content-length`.

For example, if you import 2 elementor templates to a page and hit the save button the `content-length` of the save request us usually less the 90Kb so for you to hit 3MB or more is not a typical usuage.

Also the solution you are suggesting is not a valid one, Creating a file of the data and uploading this file is not something I see Elementor doing anytime soon.

I can only suggest either create a custom widget which will create the loop/repetion of items you have or change the data structure and use the Posts Widget to pull the data for you which will again be a single element and not over 138 like you have now.

thanks.

**Comment by raddnoa** [comment]
Moving my site to a server with more memory (512mb to 2gb) fixed this problem. Everything else remained equal. So I guess template inserting in Elementor is such a memory-hungry task. And therefore Elementor is not suitable for small servers. Period.
