### ISSUE TITLE
Blogging is awful.  Number bullets always change back to Letters.

### ISSUE THREAD

**Issue by kylebones** [elementor/elementor#7708]
I have a numbered bullet list of 10 and random numbers will turn to letters, and then switch back, and then again.  Very frustrating.  Also, when we publish the blog post and view it on the website, the social share icons are hovering over the first paragraph.  Lastly, how do we remove the Google Plus icon?

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
