### ISSUE TITLE
Star Rating Widget supports Dynamic Data

### ISSUE THREAD

**Issue by mikesale** [elementor/elementor#7716]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to use the Star Rating Widget with Dynamic Data. 

**Describe the solution you'd like**
Star Rating is populated by Custom Field (ACF field in my case) number value from 1 to 5 in an Elementor Single Template for a "Review" type that shows the review rating in the top of the left part of the page.

**Describe alternatives you've considered**
No work around using Elementor product, alternative with 3rd party widget has huge memory consumption issues.

**Additional context**
Would also be very useful for reviews for WC products in a product single template.

**Comment by black-eye** [comment]
+1 Oh yes. 
It was mentioned in several other issues and FB commets, but it seems (strangely enough) it never gained it's own issue.

**Comment by bainternet** [comment]
@mikesale , @black-eye 

This is something that has already been requested but depends on implementing dynamic capabilities to a Number Control.

For now, you can use the provided filters and change the control type form number to text and activate dynamic capabilities on it, ex:

```PHP
add_action( 'elementor/element/star-rating/section_rating/before_section_end', function( $control_stack, $args ) {
	// Get existing control
	$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), 'rating' );

	if ( is_wp_error( $control ) ) {
	    return;
    }

	$control['type'] = 'text';
	$control['dynamic'] = [
		'active' => true,
	];
	// Update the control
	$control_stack->update_control( 'rating', $control );
}, 10, 2 );
```

for a more permanent solution please follow #5952.

thanks.

**Comment by stevewoody82** [comment]
To add to this - When using the function.php code above it messes up the numbers. 

0 = 1
1 = 2
2 = 3 in terms of the rating. 

It does pull dynamic content through but you have to use 0 1 2 3 4 to get the right rating.

**Comment by reachadam** [comment]
@stevewoody82 Did you find a workaround?

**Comment by reachadam** [comment]
@bainternet Is it possible to have a similar function for the counter module?
