### ISSUE TITLE
Absolute position pushing page content

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#7717]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

I inserted an image and positioned it through the Absolute Position feature. But it seems that in the tablet the absolute position is pushing the content to the side: https://screenshot.net/pt/e92ce9k?

See the page without the image with absolute position: https://screenshot.net/pt/399j5bd?

Notice that in the page without the image in absolute position, the content is normal. And notice that it have a Chat (balloon at the bottom right of the screen), but the page with the image in absolute position the content is wrong and the balloon does not appear. This balloon also does not appear on the mobile when the absolute position is activated in the image.

I believe that the demarcation of the absolute position is pushing the content: https://screenshot.net/pt/w3ytzm3?

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Try setting your arrow image (global) to custom width and check if that solves the issue for you.

If the issue persists, please contact our support for further assistance.

Thanks

**Comment by rodrigocarlos** [comment]
Hello

Ok, I set the Width to 100% (https://screenshot.net/pt/kg2s07k) and then control the size of the image through the custom position, and now it's better.

Just a note... it's a bit tricky to use custom position since it never gets correct on all screen sizes. See the images below for you to understand:
https://screenshot.net/pt/rk5uj2o
https://screenshot.net/pt/zkeugqw
https://screenshot.net/pt/8d7hyr2
https://screenshot.net/pt/r4kh48k

How to avoid this?
