### ISSUE TITLE
Can not override Element_Base class in custom plugin

### ISSUE THREAD

**Issue by mukeshpanchal27** [elementor/elementor#7720]
## Description

We are trying to override section and column elements in our custom plugin. but when we had included same file ( for column ) as in elementor gives, then it throws Fatal error like Fatal error: Class ‘Elementor\Element_Base’ not found.

Ticket already submitted in plugin support at wordpress.org - https://wordpress.org/support/topic/can-not-override-element_base-class-in-custom-plugin/

For your information, we have register elementor_type with below code

```<?PHP
add_action( 'elementor/controls/elements_registered', [ $this, 'register_elements' ] );
public function register_elements() {
	\Elementor\Plugin::instance()->elements_manager->register_element_type( new Elements\Element_Column() );
}
```

## Error
Fatal error: Class 'Elementor\Element_Base' not found in /var/www/html/litho/wp-content/plugins/litho-addons/elements/column.php on line 20

## Environment
Operating System: Linux
Software: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.15-0ubuntu0.18.04.2

## WordPress Environment
Version: 5.1.1
Site URL: http://localhost/
Home URL: http://localhost/
WP Multisite: No
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Debug Mode: Active

## Theme
Name: Twenty Nineteen
Version: 1.3

## User
Role: administrator

## Active Plugins
Elementor
Name: Elementor
Version: 2.5.9
Author: Elementor.com

**Comment by bainternet** [comment]
@mukeshpanchal27 

Not sure what you are doing but it seems like the Elementor Autoloader hasn't kicked in before you include your extending class. So make sure to include the extending class only after or at the `elementor_init` action hook.

**Comment by mukeshpanchal27** [comment]
@bainternet thanks for your prompt reply.

i can't found "elementor_init" action/filter hook in Elementor can you please explain how to use that hook in plugin?

My goal is that i have to override column element in my custom plugin to change it's structure. I have added below code in my plugin column.php file after run it will show below error on.

## Error
Fatal error: Class 'Elementor\Element_Base' not found in /var/www/html/project/wp-content/plugins/project-addons/elements/column.php on line 3

## Code
column.php file code
```PHP
use Elementor\Element_Base;
use Elementor\Controls_Manager;
abstract class Element_Column extends Element_Base {
```

**Comment by mukeshpanchal27** [comment]
Found the solution issue is in action that i used below action fix my issue.

add_action( 'elementor/elements/elements_registered', [ $this, 'register_elements' ] );

**Comment by pegues** [comment]
@mukeshpanchal27 I just found this post. Were you by any chance creating a custom section element that would allow you to have your own custom section wrapper with custom widget nesting capability? If so, any chance you wouldn't mind sharing your code for this?

**Comment by mbos01** [comment]
@mukeshpanchal27 is it possible for you to share an example of how you did this? Appreciate it!
