### ISSUE TITLE
Saving comment cookies

### ISSUE THREAD

**Issue by Immanuelbh** [elementor/elementor#7721]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allowing people to comment with ease, without the need to re-enter their information everytime they want to comment.

**Describe the solution you'd like**
adding the built-in wordpress checkbox of "Show comments cookies opt-in checkbox, allowing comment author cookies to be set. "

**Describe alternatives you've considered**
adding it to all pojo themes. Currently this feature is not available.

**Additional context**
This is something wordpress has already addressed and added, the problem is that pojo theme 'Buzz' does not include this feature. 
I contacted the pojo team through their site, after a few mails we realised that this issue is not something they have a solution for and advised me to open a new ticket here on github.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input, and sorry for the ultra late reply.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

Thank you for your understanding.
