### ISSUE TITLE
Database upgrade does not run in v2.5, all form ID's gone causing back blank forms be sent

### ISSUE THREAD

**Issue by atMaarten** [elementor/elementor#7725]
Found problem on bug reported in #7691 Still a open issue.

I have the problem here. Over 150 websites all with this same problem. All form IDs are gone, which results in blank emails / submits. And error messages when connected with ActiveCampaign / MailChimp.

By downgrading to Elementor Pro to 2.4.8 the issue is also resolved here (temp solution, because v2.5.4 does not working).

**Found the problem**: the database Upgrade script in the background is not running. This happens when these lines are in wp-config.php
`define('DISALLOW_FILE_EDIT', true); `
`define('DISALLOW_FILE_MODS',true);`

When commetting out this lines, the upgrade script can run in the background and all IDs are back again.

Question now is: Why does Elementor Pro v2.4.8 does not have this issue while v2.5.x does? And is there a way to force the database upgrade with the DISALLOW_FILE_EDIT and DISALLOW_FILE_MODS enabled? Or at least warn the user that the database upgrade is not been made so they / we know that action needs to be taken?

Manually changing 150+ wp-config.php files is a lot of work. 
So how to solve this problem in bulk other than reverting all the sites back to v2.4.8?

**Comment by shilo-ey** [comment]
Hi @atMaarten 

Thanks for reporting.

It is indeed an issue with the update script. we are looking into it and keep you posted.

In the meantime, please share here your system info from at least one of your affected sites.

This will be very helpful.

Thanks!

**Comment by shilo-ey** [comment]
Hi @atMaarten 

What or who added the line 
`define('DISALLOW_FILE_MODS',true);` ?

Is it a plugin (ManageWP-Worker) or yourself?

**Comment by atMaarten** [comment]
Both lines are added once by ourselves in our main website. This main website is used to create new websites by cloning them, which gives the new website these lines as well. 

Adding both lines is a common used security enhancement. This way when a hacker manages to login to a Wordpress website, he of she cannot change files, code or install malicious plugins. The Wordpress & plugin updates are executed by ManageWP.

**Comment by atMaarten** [comment]
I see the fix is in development. Great news!
@KingYes @matipojo @shilo-ey 

Quick question: What kind of fix will this be? Only a notice to the user? Or also a real fix that when the database upgrade is not been done, the forms still will work?

Or will the fix be that the upgrade can be done, without having to edit the wp-config files?
