### ISSUE TITLE
Where do I save my custom action for forms?

### ISSUE THREAD

**Issue by c0ldlimit** [elementor/elementor#7726]
I was told by Elementor support that my question was more appropriate for the development team.  

I am trying to follow the following tutorial to add a custom form action the Form widget:
https://developers.elementor.com/forms-api/custom-form-action/

What's not clear to me is where do I save my php file and how do I register my action when I'm ready to test it?

Thank you!

**Comment by c0ldlimit** [comment]
In particular the php file containing the add_action to hook to 'elementor_pro/init'?  I think the autoloader would pick up this file, but where does one save it so that autoloader sees it?

**Comment by shilo-ey** [comment]
You can add it to your theme's `functions.php` file.

Thanks.

**Comment by deangenovski** [comment]
Hey, 

Could you please provide an answer to "What's not clear to me is where do I save my php file and how do I register my action when I'm ready to test it?"
