### ISSUE TITLE
Request: Trigger form action [X] ONLY if checkbox [Y] is checked

### ISSUE THREAD

**Issue by Talco100** [elementor/elementor#7727]
Requested: The option to set each form action separately to trigger ONLY if checkbox [the one relevant, or any other condition in form] is TRUE.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Talco100** [comment]
Hi @shilo-ey and thanks for your help.
I've read #6899 and couldn't seem to understand how is it relevant :-)
I am talking about a situation in FORMS in which I want to trigger the WEBHOOK (or any other action) **only** if the checkbox is checked. It has nothing to do with popups as far as I understand it.
Item #6899 is quite different and won't necessarily solve my feature request, isn't it?
Cheers
Tal

**Comment by shilo-ey** [comment]
You are correct and I'm sorry about that.

Although we have another issue for that matter. Please follow #4469 for further information.

You can achieve this behavior by using our [Forms API](https://developers.elementor.com/forms-api/).

See example here:
```PHP
// A send custom WebHook when user checked the acceptance field
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );

    // Replace MY_FORM_NAME with the name you gave your form
    if ( 'YOUR_FORM_NAME' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
	$fields = $record->get_field( [
        'id' => 'YOUR_FIELDS_ID',
	] );
	$form_fields = [];
	
	$field = current( $fields );

	if ( 'on' === $field['value'] ) {
		foreach ( $raw_fields as $id => $field_data ) {
			$form_fields[ $id ] = $field_data['value'];
		}
	} else { 
		return; 
	}

    // Replace HTTP://YOUR_WEBHOOK_URL with the actuall URL you want to post the form to
    $response = wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
        'body' => $form_fields,
	]);

}, 10, 2 );
```

Thanks!

**Comment by Talco100** [comment]
Thanks again @shilo-ey for the update and the code!
I am no programmer - just a simple(?) Elementor PRO user.
We ask this feature to make this conditional action easy **_inside the user interface_**, without asking someone to code PHP for each form and action separately...
Hope that you understand and that it will be possible soon.
Best

**Comment by as1414** [comment]
@shilo-ey can we use your code sample above to control whether the form will complete an "action after submit"?

I hope I'm clear... I'm trying to add 3 actions, 1) record submission, 2) email me the information, 3) send to MailChimp.  But, I want to capture these before they run and only execute the third one if a checkbox is checked.

I suppose I could go through MailChimps API and code it myself - but that seems like re-inventing the wheel a little.  Hoping I can just intercept the form before it does anything and control it from there.
