### ISSUE TITLE
Column Transition Duration

### ISSUE THREAD

**Issue by DmitriyDSWEB** [elementor/elementor#7729]
Hello, Pls. add Column Transition Duration
Column - Style - Border - Hover - **Transition Duration**

Thanks

**Comment by lior-sh** [comment]
Hi @DmitriyDSWEB,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by DmitriyDSWEB** [comment]
))))
