### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by BumperTDM** [elementor/elementor#7731]
Hey there,

I've had issues with passing an image into a dynamic image widget and have received on the error of "Warning: Illegal string offset 'url' in /home ... wp-content/plugins/elementor/includes/conditions.php on line 86" and have as yet had no luck passing the jpg file into the widget. I've been onto support and they've advised they can'r assist me. I've since just made the function return a html img tag with src being the url of the image I was looking to pass in. I now have the images I want where I want, yet still I have this message show up and destroying the look.

Anyone know how to bypass the error or at least remove the message?

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
