### ISSUE TITLE
More than 5 tilt dividers render page elements invisible on preview

### ISSUE THREAD

**Issue by plasterius** [elementor/elementor#7733]
Hi,

Just noticed that when i add more than 6 shape dividers with tilt option other page elements (buttons) go missing . If i however disable one of the tilt dividers then they appear. 

If you need more clarification let me know i'll post the website i'm working on.

**Comment by Aviad-Herman** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Thanks.
