### ISSUE TITLE
Dimension field can not leave empty

### ISSUE THREAD

**Issue by mdjwel** [elementor/elementor#7739]
I can not leave empty the dimension field's single value. When I delete the value it's returning value to 0 every time. But I have to leave empty some value of dimension field. 
How can I leave empty the dimension field? 

Thanks

**Comment by reardestani** [comment]
We have same issue here.

**Comment by Flipback8** [comment]
The same issue as well, it would be nice if we could just drag the margins and padding in the front end like in Divi and Oxygen.

**Comment by lior-sh** [comment]
Hi @mdjwel,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
