### ISSUE TITLE
How to replay an animation with JS

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7740]
Hello,

How can we replay an animation set with the new Motion Effect system of Elementor?

When the page load, the animations play. I want to be able to trigger one specific animation to play again with the use of Javascript without having to recreate it using animate.js, for example.

**Comment by bainternet** [comment]
@tristanleboss 

The Motion Effects system has nothing to do with animations like our entrance animation.

The Motion Effects work either on events (scroll) or by tracking mouse so there is nothing really to replay.

Now if you are asking about entrance animation, then, we use [Animate.CSS](https://daneden.github.io/animate.css/) which is CSS class based so if you want to replay you simple need to remove and re-add the right classes, see this for reference: https://blog.diogomartino.com/index.php/2018/11/10/how-to-replay-an-animation/

**Comment by SolunaCG** [comment]
Hi! I know this thread is old and already closed but I´d love to know how to replay the entrance animations. Unfortunately the link doesn´t work anymore. 
Could someone maybe help me with this?

Thanks in advance!
