### ISSUE TITLE
Elementor consistently slow on TTFB

### ISSUE THREAD

**Issue by clickharder** [elementor/elementor#7741]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I contact support because I am a paying pro member, however, they sent me here to request support...

Elementor is consistently slowing down my websites response time from my server and I can't figure out the cause.  I am see 300% increases in TTFB on Elementor pages compared to pages using Gutenberg with the exact same content.

This isn't a resource problem as I am testing on servers with 4-8GB of Ram and 4-8 processors and little to no load on the server.  

## Steps to reproduce

https://elementor.clickharder.net

Test 1
Elementor with fifty h2 headers - 158ms TTFB
https://tools.pingdom.com/#5a7a49ca9a000000

Test 2
Gutenburg (with fifty headers) - 53ms TTFB
https://tools.pingdom.com/#5a7a4a9237000000

I see this on live sites too.  The more complex the content, the longer the TTFB.  Some of my sites are taking 1-2 seconds just for the server to respond.  When I remove Elementor, I see times in the 200-500ms.

I provided login credentials in my support ticket to Elementor since this site is devoted to figuring out this issue.  So if you want to test, that info is available.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.38 (Unix) OpenSSL/1.0.2g
	MySQL version: (Ubuntu) v5.7.25
	PHP Version: 7.3.3
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://elementor.clickharder.net
	Home URL: https://elementor.clickharder.net
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Zephyr
	Version: 5.4.1
	Author: UpSolution
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

== Active Plugins ==
	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.3
		Author: Elementor.com

	Header Builder
		Version: 2.4
		Author: UpSolution


== Log ==
	: 
PHP: showing 1 of 1PHP: 2019-04-01 15:52:53 [notice X 1][/srv/users/serverpilot/apps/elementor/public/wp-content/plugins/elementor/core/common/modules/connect/apps/base-app.php::310] Trying to get property 'code' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 17 of 172019-04-01 15:55:24 [info] elementor-pro::elementor_pro_updater Started 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-04-01 15:55:24 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-04-01 15:55:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.6',
  'to' => '2.5.3',
)]
2019-04-01 15:55:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.6',
  'to' => '2.5.3',
)]


				```
</details>

**Comment by Webtica** [comment]
+1 Following

**Comment by clickharder** [comment]
I re-did the page above to display more accurate testing.  I tested two blank pages (Elementor and Gutenberg), 1 Heading Pages, and 50 Heading Pages.  I didn't bother with any designs more complex because it gets harder to do an apples to apples comparison.

What I am continually finding is an increase in server response time as I add more elements.  Latest results are displayed on that home page and are quite dramatic.

Essentially Gutenberg remains at about 25-30ms server response time no matter how many headers I throw at it.  Elementor increase significantly as I add more headings going from 53ms to 112ms.

On live websites, I have found that those numbers just continually increase until they are in the 800ms to 1500ms on complex pages.  I have also include the full server info as provided within Elementor.

**Comment by SeitenDesign** [comment]
If you put so much weight on speed, use a cache plug-in + Litespeed web server instead of apache. The differences will not be that big anymore.

https://tools.pingdom.com/#5a80714e3d000000

**Comment by clickharder** [comment]
@SeitenDesign 

I do use cache plugins and CDNs whenever possible.  Unfortunately, using Litespeed is not an option for us.  However, there are several situation where caching plugins and CDNs are not usable.  

For example, I have run into issues with real estate websites not being able to use caching due to property listings not updating properly.  I also turn off caching for admins so we don't have to clear the cache every time we make an update and want to view it during development.

Regardless, I don't think it is unreasonable to want to know why or how a plugin is impacting a website's loading speed.  Why is it, that all of Wordpress, all the other plugins installed, and Elementor itself do not add that much time to the server response.  But when adding elements to a page, the server response time increase linearly. 

For example, what is significantly harder about displaying 50 headers instead of 1 header that would increase the server response time significantly?

**Comment by bainternet** [comment]
@clickharder 

TTFB - Time to First Byte is depended on 3 major things:

1. Making the request - This depends on a user's network speed, DNS lookups, and distance from the server. (Elementor has no effect here).

2. Processing the Request - This depends on your server, the applications running, database calls and external services in use. (Elementor plays a part here).

3. Responding to the request - This depends on both 1 and 2 in parts, meaning this depends again on the user's network speed on the one hand and on the server response received from the processing. (Elementor has no effect here).

So when you look at what builds up the TTFB in a WordPress site with Elementor, more specifically the "Processing the Request", Naturally the more elements you have for elementor to render the longer it will take to process them and the longer your TTFB will be.

Now you can easily and drastically bring down the time it takes to process the request by having a page cache in place and it will remove the whole dependency on the actual processing.

**Comment by MichaelFomenko** [comment]
> @clickharder
> 
> TTFB - Time to First Byte is depended on 3 major things:
> 
> 1. Making the request - This depends on a user's network speed, DNS lookups, and distance from the server. (Elementor has no effect here).
> 2. Processing the Request - This depends on your server, the applications running, database calls and external services in use. (Elementor plays a part here).
> 3. Responding to the request - This depends on both 1 and 2 in parts, meaning this depends again on the user's network speed on the one hand and on the server response received from the processing. (Elementor has no effect here).
> 
> So when you look at what builds up the TTFB in a WordPress site with Elementor, more specifically the "Processing the Request", Naturally the more elements you have for elementor to render the longer it will take to process them and the longer your TTFB will be.
> 
> Now you can easily and drastically bring down the time it takes to process the request by having a page cache in place and it will remove the whole dependency on the actual processing.

You clearly dont know what you talking about, he showed an comperrison with simmilar elements with Elementor and with Gutenberg and the results are clear, why you ignoring this facts?

**Comment by bentalgad** [comment]
@bainternet you are just ignoring the hard fact that was raised here, it was better if you didn't answer at all. your plugin does the worst job ever at loading times and all the plugins, caches and servers in the world won't solve this problem, it's something you have to do!

**Comment by PieterT2000** [comment]
Why is this issue closed? It isn't solved yet! I have exactly the same problem with my client's websites. However, I managed to drastically bring down the overall loading time by hooking into the elementor dependencies and removing the ones which weren't needed on a specific page. Right now, Elementor loads some heavy scripts on all of your pages (like swiper.js or jquery-migrate) without even needing them, which largely impacts your overall speed.

If you're interested in the script, please drop me a line.

**Comment by clickharder** [comment]
@PieterT2000 Can you post a copy of your script?  I would love to see how you solved this problem.

**Comment by bentalgad** [comment]
@PieterT2000 isn't it funny that the purpose of page builders is to make you code less but in the end we code more to fix the things the page builder mass? :)

**Comment by PieterT2000** [comment]
@bentalgad Yeah, exactly! 

@clickharder see [elementor-hacks](https://github.com/PieterT2000/elementor-hacks)
You can adjust the script to your own needs. For example I don't use swiper.js on the homepage which decreases the page load with a whopping 175ms. I've also included some other scripts (wp-embed, migrator, etc.) that aren't used on your frontend. To compensate the TTFB I would also recommend combining your css files, which improves a lot.

**Comment by Asiancookingmom** [comment]
Did anyone figure out a solution to this problem?  I'm having the EXACT same issue where I can see the page load time go up and down as I add and remove elements to elementor.  This is with all other addons removed and with the server running on local flywheel to eliminate any hosting issues.  Was there a solution to this?  I noticed the thread is closed.

**Comment by gsusI** [comment]
Another Elementor Pro user here, may I ask why the issue was closed @bainternet. Is there any solution to the performance issues raised by @clickharder?

My performance issues still happen on localhost, therefore the explanation that was given of how TTFB is measured falls short.

Maybe we should talk about **slow server response caused by Elementor's poor performance on complex pages**?

In any case, it feels like there are sufficient details in this thread to identify a significant performance issue with how Elementor renders widgets.

@PieterT2000, thanks for sharing your script, although it doesn't really help with performance **it does help with pagespeed**.

**Comment by gsusI** [comment]
Same page.

280 milliseconds with no plugins enabled.
7.16 seconds with **only** Elementor and Elementor Pro plugins enabled.

![image](https://user-images.githubusercontent.com/4558016/99650735-b1df9380-2a4d-11eb-99d2-b18903f755a1.png)

**Comment by gsusI** [comment]
@bainternet, just a quick note, for simplicity I've only included two requests in the screenshot, however:

- the results are consistent over time;
- not affected by the order in which I make the requests (first with plugins disabled then enabled or viceversa);
- there are no other plugins installed;
- no caches of any kind enabled.;

@shilo-ey,  as this thread is a bit old I'm cc-ing you, as I know from other interactions that you are currently focused on this repository.

**Comment by black-eye** [comment]
@gsusI, I'd recomment to open a new issue. These long-closed reguests don't get much attention here, at least according to my experience.

Your feedback seems valuable to me, so it would be a pity if it wouldn't be noticed.

**Comment by gsusI** [comment]
Thanks @black-eye, I'll do so

**Comment by gsusI** [comment]
Done, #13099, in case someone has the same problem

**Comment by malikmalhan** [comment]
+1 . ttfb is too high on elementor

**Comment by nicholaszein** [comment]
Hey everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this issue was resolved with the introduction of the Optimized Control Loading feature in Elementor v3.21.0! 🥳 

The Optimize Control Loading feature reduces the Time To First Byte (TTFB) metric by 20%-30%, which decreases the loading time for your visitors and boosts their engagement by providing a smoother browsing experience. The improvement is achieved by preventing unnecessary editor-related controls from loading when your website is rendered for visitors.

**Activate “Optimize Control Loading” by going to WordPress Dashboard → Elementor → Features.**

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
