### ISSUE TITLE
✅ 🔃 🚀 Feature Request: Provide a way to prevent Tabs from turning to Accordions on mobile - [ED-9306]

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#7742]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Well, the title says it clearly: I need the tabs to stay as tabs even on mobile. I don't need them to become accordeon. I have only 3 small tabs and in each one is different form. Accordeon is too triky for that case.

**Describe the solution you'd like**
For the time being, I would be fine if you provide me with the script to turn this behavior off.

**Describe alternatives you've considered**
I've started a support ticket, but the support answered me, that it isn't possible and I should raise a request here. 

But it seems to me quite strange - I suppose this behavior is managed by a script, which is triggered at some point: all I need is to turn this script off. It shouldn't be that difficult, right? I don't want to add anything, I just want to turn something off.

**Comment by followeyes** [comment]
And Maybe aslo adding an option that closes all tabs reload on the frontend as a default state.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by nicholaszein** [comment]
Hello @black-eye and @ConsultMePL,

as requested, I'm reopening this issue to address <ins>[these](https://github.com/orgs/elementor/discussions/20732#discussioncomment-4401112)</ins> <ins>[comments](https://github.com/orgs/elementor/discussions/20732#discussioncomment-4401962)</ins> in the [Beta 3.10 discussion](https://github.com/orgs/elementor/discussions/20732).

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap for the time being. 

But nonetheless, I'm including this so the team can take a look and see if it's possible to implement it, even if it's not in this beta.

Allow us to take some time to review your request. We will get back to you with feedback as soon as possible.

Kind regards

**Comment by jlemonz** [comment]
pls add this right now its usseles to use for mobile design

**Comment by otomasz** [comment]
> 

the function is very much needed, for you it's a small effort and for us it's a big 👍🏻🙃

**Comment by Joliamendi** [comment]
This is really strange! Elementor rewrites the tabs widget, but again repeats the weakness of the former widget.

**Comment by jlemonz** [comment]
I had a small discussion about the issue with a dev. And the funny thing is that they do have the tabs below the content on there **own** website for the mobile website. So it is possible. 
![210409252-eaf84e2d-6cf7-455b-837b-cacf3ad9688e](https://user-images.githubusercontent.com/112578448/211169719-ddf79107-044f-4abd-aeaa-bfc6b07cf679.png)

**Comment by Vossha** [comment]
+1. 

There are a lot of use cases where tabs should stay tabs for better content and user experiences. It would be ideal to be able to choose if tabs should turn into toggles on tablet or mobile devices.

Example of use case where tabs are better than toggles: 
[https://www.facebook.com/groups/Elementors/posts/5525192364273171/](https://www.facebook.com/groups/Elementors/posts/5525192364273171/)

**Comment by Michaelgimii** [comment]
Elementor team, please put this on your roadmap. The new tab widget is really awesome. But this weakness is really annoying.
If you need to use the accordion, add the accordion widget. But the tab widget should not become an accordion.
Please do not forget this❤

**Comment by perks98** [comment]
+1 for the existing tabs and the new nested tabs

**Comment by vcpaige** [comment]
+1
I'm using Tabs to display 3 different forms. On mobile, it's not obvious that there are multiple tabs because you would have to scroll a lot to see the other options. I would like to display the tabs all at the top, or at least be able to have no tabs active by default on mobile.

**Comment by sebasvnleeuwen** [comment]
+1
Currently facing the same problem with nested tabs. On mobile I need to be able to show the 3 tabs with the content underneath it. The content is too long for visitors to see that there are multiple tabs.

**Comment by SolunaCG** [comment]
+1

**Comment by Pixelharmonist** [comment]
+1 

There are some Tutorials to change it. But it´s still for Tabs before came the Nested Variation.
I´m not the badest css´ler but i don´t understand where the "accordion" - orders are written...

**Comment by Pixelharmonist** [comment]
Hey Folks!

I asked me through Elementor Groups@Facebook.
One guy (mind) had an impulse and for me is it the solution.

Play around with following css-code:
`.e-n-tabs-heading.e-n-tabs-heading.e-n-tabs-heading.e-n-tabs-heading {
overflow-x: auto; /* enable horizontal scrolling */
display: flex;
flex-wrap: nowrap;
justify-content: start;
padding-bottom: 10px;
}

.e-n-tabs-heading > .e-n-tab-title{
white-space: nowrap; /* optional, prevent tabs title from breaking into 2 lines */
}

.e-n-tabs-content .e-n-tab-title {
display: none; /* don't display mobile tab titles */
}`
From: https://element.how/elementor-tabs-mobile-scroll

Don´t be Confused with the Topic "Mobile Scroll". It´s still the code underneath of that page...

If it´s matched for you, let me know it! 

Greets from [Pixelharmonie](https://pixelharmonie.de)

Stefan

**Comment by SolunaCG** [comment]
Amazing!! Just tried it and it worked for me. Thanks a lot for letting us know!!

**Comment by Michaelgimii** [comment]
It seems that this issue is in progress and will be available in future updates. Thanks to the Elementor team 🥂

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Tabs widget in Elementor v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
