### ISSUE TITLE
Missing arguments for widget_filter hook

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#7745]
in Elementor Pro plugin, you used hook apply_filter('widget_filter') but you just input only 1 argument.
[http://prntscr.com/n7q3du](http://prntscr.com/n7q3du) in Class Elementor_Library

It's caused Falal Error ( Uncaught ArgumentCountError: Too few arguments to function )
if theme or any plugins used this filter too, & used 3 arguments

Please edited it to:
$title = apply_filters( 'widget_title', $title, $instance, $this->id_base );
echo $args['before_title'] . $title . $args['after_title'];

Sorry for my english.

**Comment by bainternet** [comment]
@steve231293 

Thanks for reporting, should be fixed in next patch version.
