### ISSUE TITLE
it would be great if the pop-up was possible in the form builder - as a link to reading privacy policy

### ISSUE THREAD

**Issue by creativemacmac** [elementor/elementor#7749]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by creativemacmac** [comment]
Hey there folks :) this is just a suggestion, but it would be phenomenal if  it was possible to use a pop-up for the 'acceptance' category of the form builder - e.g. being able to read privacy policy on the spot before submitting the form

**Comment by tristanleboss** [comment]
Great idea

**Comment by bainternet** [comment]
@creativemacmac @tristanleboss 

You can alredy do that using the "Open by Selector" option of the popup in the popup settings >> advanced panel:

![imaepF9](https://user-images.githubusercontent.com/660572/55681603-d9ddba00-5930-11e9-8df3-794c821bb008.png)


and in the acceptance filed add an element with that ID, ex:
![xkLu41G](https://user-images.githubusercontent.com/660572/55681622-02fe4a80-5931-11e9-8829-7c578d696e7e.png)

which will give you something like this:

![DRKHBEp](https://user-images.githubusercontent.com/660572/55681625-0d204900-5931-11e9-8220-1c268b8c5bbe.png)


thanks.

**Comment by creativemacmac** [comment]
Hey there @bainternet :) thanks for this, I just added it as a html link, but mine is only popping on the backend not on the live site...
I added:
Please confirm that you accept our <a id="privatpolitikkur">privacy policy</a>
am I getting this wrong?
thanks in advance
Linda
