### ISSUE TITLE
Query for parent categories acting strange in post widget

### ISSUE THREAD

**Issue by dibeja** [elementor/elementor#7751]
I've noticed a strange behaviour on the post widget.
Prior to Elementor Pro 2.5.4 when I filtered my post for term > "parent category" it showed me all the post both the ones in the parent category AND the ones in the related child categories.

Now it shows me only those explicitly filed in the Parent Category. 

Elementor version: 2.5.11
Elementor Pro: 2.5.4
Wordpress: 5.1.1
Theme: Elementor Hello Theme

**Comment by shilo-ey** [comment]
Hi @dibeja 

This issue has been fixed in Elementor Pro v2.5.5

Thanks.
