### ISSUE TITLE
Bug. Problem with the Archive of goods widget. Pagination does not work

### ISSUE THREAD

**Issue by igorek-zxz** [elementor/elementor#7752]
I found a bug in Elementor Pro!

The problem with the Archive of goods widget. Pagination does not work (ERR_TOO_MANY_REDIRECTS), if I activate the filter by attributes from the WooCommerce widget.

The essence of the problem (watch the video https://drive.google.com/file/d/1XzZQz23KZHVM9kEqDB-3eeQ6YVfRvynP/view?usp=sharing ): when I apply any  filters of attributes (widget by WooCommerce) pagination is not working. Filtr of prices(widget by WooCommerce) works well.

PS: I already wrote about a similar bug with pagination and filters (you fixed it, but a new one appeared), here is my previous appeal:
"I found a bug in Elementor Pro!
The problem with the Archive of products widget. WooCommerce can work with this pagination ("/product-category/name/page/3"), and you use another one ("/product-category/name/?product-page=3").
Why is that? In the Blog widget, you are using this kind of link ("name/page/3"). Why was it necessary to do differently?
The essence of the problem (watch the video): when I apply any WooCommerce filters the pagination is not removed from the link and I remain on the same page. Sometimes this leads to an error if the filtered product pages exist less than the current page number.
It seems to me that this can be solved by editing this file ("/plugins/woocommerce/includes/widgets/class-wc-widget-layered-nav.php") or in these files of your plugin.
Looking forward to your answering!"

[system-info-barez.su-05-04-2019.txt](https://github.com/elementor/elementor/files/3047377/system-info-barez.su-05-04-2019.txt)
Domain is not delegated, the site is available by technical domain http://barez.su.xsph.ru
Or go to the site through IP, write in the hosts 141.8.196.166 barez.su www.barez.su

**Comment by bainternet** [comment]
@igorek-zxz 

I see that our support has already answered you, thanks for reporting.

**Comment by igorek-zxz** [comment]
It did not help me ... Pagination in both cases does not work!
