### ISSUE TITLE
Image "wrong" resize when using LINK URL

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#7754]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using a custom URL on an image and custom % width, the size changes. See this video:
https://www.useloom.com/share/72cdb5fd11e042a1a2e4d1159cfaf258

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

[system-info-belldigital.no-05-04-2019.txt](https://github.com/elementor/elementor/files/3048815/system-info-belldigital.no-05-04-2019.txt)

**Comment by bainternet** [comment]
@elasticeye 

We have tested and you are correct, this only happens if you set the width of the Image in percentage and you set it to something bigger than the image itself.

Sadly there is no real fix we can implement here because the other way around it will happen if you set your width in percent to something smaller.

I can only suggest using a bigger image or a different width unit like PX or VW

thanks.

**Comment by emmavelazquez** [comment]
Hello, I'm using a .svg image as a button and it resized it to a minimal size, it's unreadable. Did you guys ever fix this?

**Comment by ifstudiodev** [comment]
Ran into the same problem, this worked for me:

.elementor-widget-image .elementor-image > a img[src$=".svg"], .elementor-widget-image .elementor-image figure > a img[src$=".svg"] {
	width: auto !important;
}

**Comment by cobekone** [comment]
> Ran into the same problem, this worked for me:
> 
> .elementor-widget-image .elementor-image > a img[src$=".svg"], .elementor-widget-image .elementor-image figure > a img[src$=".svg"] {
> width: auto !important;
> }

You are my hero. I had the exact same problem. Never imagined I will have a solution for my problem this quickly!

**Comment by turiugaidy** [comment]
> > Ran into the same problem, this worked for me:
> > .elementor-widget-image .elementor-image > a img[src$=".svg"], .elementor-widget-image .elementor-image figure > a img[src$=".svg"] {
> > width: auto !important;
> > }
> 
> You are my hero. I had the exact same problem. Never imagined I will have a solution for my problem this quickly!

Hey, I'm completely new to this, having same problem. Where and how should I add this code? Would be a great help, thank you!

**Comment by gessic-apps** [comment]
> > > Ran into the same problem, this worked for me:
> > > .elementor-widget-image .elementor-image > a img[src$=".svg"], .elementor-widget-image .elementor-image figure > a img[src$=".svg"] {
> > > width: auto !important;
> > > }
> > 
> > 
> > You are my hero. I had the exact same problem. Never imagined I will have a solution for my problem this quickly!
> 
> Hey, I'm completely new to this, having same problem. Where and how should I add this code? Would be a great help, thank you!

Hi , This worked for me.

To add this code, simple go to the "Customize page". Two ways to get there: 1 - if you're on the page itself, and logged in, customise will appear at the top. In the admin panel, go the Appearance, then 'customise'. Next, choose 'Additional CSS' , and simply copy and paste that above code, and choose publish.

**Comment by jeffwebsys** [comment]
You can use this CSS code on your image under advance > custom CSS and paste this code to stop it from shrinking

selector a {
width: 100% !important;
}

**Comment by prowhiz** [comment]
This is the code that worked for me

`.elementor-widget-image a img[src$=".svg"]{
    width:100%;
}`

**Comment by prowhiz** [comment]
> This is the code that worked for me
> 
> `.elementor-widget-image a img[src$=".svg"]{ width:auto; }`

If the image appears wonky, change the width from auto to 100%

**Comment by b0r0mir** [comment]
> > This is the code that worked for me
> > `.elementor-widget-image a img[src$=".svg"]{ width:auto; }`
> 
> If the image appears wonky, change the width from auto to 100%

Yeah that's what I needed, thanks. I'm using an svg in the header with at link. Before this as soon as a link was added the image would shrink to a tiny size.

I can't believe this is not being fixed when the fix has been know for two years. Thanks again to you guys who figured this out.

**Comment by Shalice1218** [comment]
I need something else. I am using the Astra theme. I tried the above code, but it doesn't work. the page need support is https://pearlshine.co.uk/

**Comment by domingoapineiro** [comment]
It works for me:
`.elementor-widget-image a {
width: 100%;
}`
