### ISSUE TITLE
adding section with sticky header

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#7755]
When using a sticky header and creating a new template - it's almost impossible to add and edit the first section without being forced to open the navigator. 

There is no way to interact with the empty section or elements that are added when they sit behind the header. 

I would suggest that when a sticky header is used (a new section is pushed down 100px) so that we can interact with it from the viewport and without the need to rely on the navigator.

**Comment by bainternet** [comment]
@stevewoody82 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Now as for your request,
We try to keep the preview as close to real frontend view as possible and for cases like this (and negative margins), we actually implemented the navigator.

thanks.
