### ISSUE TITLE
Feature Request - loading ... button

### ISSUE THREAD

**Issue by gwmbox** [elementor/elementor#7759]
Would like to request the addition of a loading style button (and other animations) that is similar to the loading/running button you use on the Builder page when you select the Publish or Update button.

**Comment by jasonb4u** [comment]
I'm one for this also

**Comment by bainternet** [comment]
@gwmbox @jasonb4u 

How do you see that working?

**Comment by gwmbox** [comment]
This was a request via a few people asking me how to do this within Elementor.  I showed them how to do it using code only.  

This request is based on the loading animation within the Elementor Widgets box on the left when you select Publish or Update a loading icon appears until done.

Their request is to display the loading animation on the button where there is a delay in some action, like going to another page, submitting a form and so on.

 

It would also be suitable to have a whole page loading option as well.  So when you go to a page and it is a bit slow to load, a loading icon appears over a lower opacity page until the page is fully loaded.

 

I hope these examples make sense to the request I have made.  If not please get back to me

 

Greg

**Comment by bainternet** [comment]
@gwmbox 

not really, how would you see that working in elementor?

**Comment by gwmbox** [comment]
I'm not sure how else to explain it?

When a button is created add an option to have an animation shown while the whatever is loading.

For example when editing in Elementor and doing an update

![image](https://user-images.githubusercontent.com/7844638/55716583-edb91700-5a29-11e9-9845-340df11d4264.png)

As I said before there is a way to do this via code, it was simply asked if it can be done in Elementor itself.

As for defining it, I'd suggest that the user can select an onclick action which the animation desired could be selected

Note sure if that helps but that pretty much is the best I can describe it

**Comment by jasonb4u** [comment]
I dont know if this is what we need, and I havent a clue how to use it lol

Something like this, scroll to this section of page: [](http://prntscr.com/ncf2fv)  |  found here with demo link:  `https://github.com/hakimel/Ladda  `

**Comment by gwmbox** [comment]
Yes that is exactly what has been requested

 

Cheers

**Comment by jasonb4u** [comment]
Well Well Well, looksy what I just came across.  No excuses no to not know what we are talking about NOW!!!!.

Elementor themselves know exactly whats going on, they have it their own buttons and this is what we want available to us, so we can set our buttons to do the exact same thing if we want !!!
https://prnt.sc/nefhh8

**Comment by jasonb4u** [comment]
Throwing some more ideas seeing tho Elementor say we going via the road map PMSL....
https://www.w3schools.com/howto/howto_css_loading_buttons.asp

**Comment by bainternet** [comment]
Thanks for clarifying,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

for now, you can easily do that with a very little custom CSS, for example on a button widget with icon:

```CSS
selector i {
    animation: fa-spin 2s infinite linear;
}
```

Thanks for the feedback.

**Comment by jasonb4u** [comment]
You saying to already have an ICON in the button, then when it's clicked it will spin until the page has changed correct ?

Another thing you mentioned: http://prntscr.com/ol7feb hows that suppose to happen when you are always closing these requests?

**Comment by jasonb4u** [comment]
All I see to that code you provided above makes a permanent spin without click.  The code you provided does NOT work as this thread requested.

**Comment by Abatjour3407** [comment]
This I feel is more than aesthetics... I have a form on a page that includes uploads. I've had people click submit and think the site is broken and then close the window. It is essential that a user is notified that something is happening after they hit the send/submit button. I'm going to play around with some javascript options but this should be built in that we don't need hack solutions.

**Comment by varunjani94** [comment]
We need this feature working. 

On my website I have a button and when I click on the button which is a stripe payment link -> It takes 3-5 seconds until the strip window is loaded. So would be great to have a loading spinner on the button for set period of time. 

Is there a work around for this?
