### ISSUE TITLE
creating a new control

### ISSUE THREAD

**Issue by lathieuhiep** [elementor/elementor#7760]
https://developers.elementor.com/creating-a-new-control/

I have registered a new type but cannot use it when add_contro () Controls_Manager :: new_type. Help me

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
