### ISSUE TITLE
Groundhogg CRM Integration

### ISSUE THREAD

**Issue by tobeyadr** [elementor/elementor#7761]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Our plugin https://wordpress.org/plugins/groundhogg/ is currently providing a built in integration for the Elementor form widget, but it's limited by the inability to map custom fields well.

Currently, to map Elementor form fields to the contact record fields in the db one has to rename the fields in the form and we make our "best guess" as to the intention of where the user wanted the data to end up.

This is not ideal and not a great User experience.

We see that Field Mapping is supported in your baked in integrations, and we tried to emulate that in our design but the JS portion was not a straight forward copy paste.

**Describe the solution you'd like**
It would be awesome to either:

A. Get a JS snippet that we could use in our plugin that would allow use to support field mapping.

B. Have Groundhogg added to your list of baked in integrations. I've attached what the Form_Action class might look like using the form API we built into it. The only component missing is the JS.

**Describe alternatives you've considered**

We tried to do it ourselves a couple ways, but the limiting factor is you can't dynamically create controls based on widget settings without causing a 500 error when the editor loads, also issues were present if multiple forms were on the same page...

**Additional context**

Again, not totally expecting you to add us as a supported integration (but it would be cool), but allowing us to add a field map control would be great.

Below is a working Form_Action minus the JS component. It was modified from the ConverKit Form_Action class.

```php
<?php
namespace ElementorPro\Modules\Forms\Actions;

use Elementor\Controls_Manager;
use ElementorPro\Modules\Forms\Classes\Form_Record;
use ElementorPro\Modules\Forms\Classes\Integration_Base;
use ElementorPro\Modules\Forms\Controls\Fields_Map;
use ElementorPro\Classes\Utils;
use Elementor\Settings;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class Groundhogg extends Integration_Base {

	public function get_name() {
		return 'groundhogg';
	}

	public function get_label() {
		return __( 'Groundhogg', 'elementor-pro' );
	}

	public function register_settings_section( $widget ) {
		$widget->start_controls_section(
			'section_groundhogg',
			[
				'label' => __( 'Groundhogg', 'elementor-pro' ),
				'condition' => [
					'submit_actions' => $this->get_name(),
				],
			]
		);

		$widget->add_control(
			'groundhogg_fields_map',
			[
				'label' => __( 'Field Mapping', 'elementor-pro' ),
				'type' => Fields_Map::CONTROL_TYPE,
				'separator' => 'before',
				'fields' => [
					[
						'name' => 'remote_id',
						'type' => Controls_Manager::HIDDEN,
					],
					[
						'name' => 'local_id',
						'type' => Controls_Manager::SELECT,
					],
				],
			]
		);

		$widget->add_control(
			'groundhogg_tags',
			[
				'label' => __( 'Tags', 'elementor-pro' ),
				'type' => Controls_Manager::SELECT2,
				'options' => [],
				'multiple' => true,
				'label_block' => true,
			]
		);

		$widget->end_controls_section();
	}

	public function on_export( $element ) {
		unset(
			$element['settings']['groundhogg_fields_map'],
			$element['settings']['groundhogg_tags']
		);

		return $element;
	}

	/**
	 * @param Form_Record $record
	 * @param \ElementorPro\Modules\Forms\Classes\Ajax_Handler $ajax_handler
	 */
	public function run( $record, $ajax_handler ) {

		$form_settings = $record->get( 'form_settings' );
		$subscriber = $this->create_subscriber_object( $record );

		if ( ! $subscriber ) {
			$ajax_handler->add_admin_error_message( __( 'Groundhogg Integration requires an email field', 'elementor-pro' ) );
			return;
		}

		if ( '' !== $form_settings['groundhogg_tags'] ) {
			$subscriber->apply_tag( wp_parse_id_list( $form_settings['groundhogg_tags'] ) );
		}
	}

	/**
	 * Create subscriber array from submitted data and form settings
	 * returns a subscriber array or false on error
	 *
	 * @param Form_Record $record
	 *
	 * @return \WPGH_Contact|bool
	 */
	private function create_subscriber_object( Form_Record $record ) {

		$map = $this->get_fields_map( $record );
		$fields = $this->get_normalized_fields( $record );

		if ( ! isset( $fields['email'] ) ) {
			return false;
		}

		$contact = wpgh_generate_contact_with_map( $fields, $map );

		return $contact;
	}

	/**
	 * @param Form_Record $record
	 *
	 * @return array
	 */
	private function get_fields_map( Form_Record $record ) {
		$map = [];

		// Other form has a field mapping
		foreach ( $record->get_form_settings( 'groundhogg_fields_map' ) as $map_item ) {
			if ( empty( $fields[ $map_item['local_id'] ]['value'] ) ) {
				continue;
			}

			$map[ $map_item[ 'local_id' ] ] = $map[ $map_item[ 'remote_id' ] ];
		}

		return $map;
	}

	/**
	 * @param Form_Record $record
	 *
	 * @return array
	 */
	private function get_normalized_fields( Form_Record $record )
	{
		$fields = [];
		$raw_fields = $record->get( 'fields' );
		foreach ( $raw_fields as $id => $field ) {

			$fields[ $id ] = $field['value'];
		}

		return $fields;
	}

	/**
	 * @param array $data
	 *
	 * @return array
	 * @throws \Exception
	 */
	public function handle_panel_request( array $data ) {

		$tags = WPGH()->tags->get_tags_select();

		$mappable_fields = wpgh_get_mappable_fields();
		$fields = [];

		foreach ( $mappable_fields as $field_id => $field_label ){
			$fields[] = [
				'remote_id'         => $field_id,
				'remote_label'      => $field_label,
				'remote_type'       => 'text',
				'remote_required'   => in_array( $field_id, [ 'email' ] ),
			];
		}

		$response = [
			'tags'      => $tags,
			'fields'    => $fields
		];

		return $response;
	}
}
```

**Comment by bainternet** [comment]
@tobeyadr 

We currently don't have an API for our field mapping controls and in each of our built-in integrations, we code the JS handler manually.

But you do have a few options:
* [Create a custom control](https://developers.elementor.com/creating-a-new-control/) yourself.
* Use a regular repeater with two fields to map ( form field name -> responder field name ).
* Have static fields for mapping as we show on [our doc](https://developers.elementor.com/forms-api/custom-form-action/)s.

Thanks.

**Comment by tobeyadr** [comment]
Forgive me, but none of those options sound Ideal. I'm capable of coding the JS handler manually as well. I notice that in your JS file you reference extending `var BaseIntegrationModule = __webpack_require__(1);` in editor.js on line 1191 (ConvertKit). Is there a way I can access that. I've looked for it in several areas with no luck. It seams that If I were able to access that I could simply add the integration to the elementorPro.modules.forms object

**Comment by tobeyadr** [comment]
Disregard. I kind of hacked it together.
I had to use the ActiveCampaign module to extend rather than the BaseIntegration object which I believe would have been more suitable. But I digress. I was also able to extend the Field_map object to a custom one which helped in the field mapping.

`
(function ( e, fields, $ ) {

    /**
     * Groundhogg Integration.
     *
     * @type {{updateFieldsMapping: updateFieldsMapping, getName: (function(): string), onTagsUpdate: onTagsUpdate, getGroundhoggCache: getGroundhoggCache, onElementChange: onElementChange}}
     */
    var GroundhoggIntegration = {
        flag: false,
        fields: fields,

        getName: function getName() {
            return 'groundhogg_v2';
        },

        onElementChange: function onElementChange( setting ) {
            var self = this;
            if ( setting.indexOf( "groundhogg" ) !== -1 ){
                self.updateFieldsMapping();
            }
        },

        updateFieldsMapping: function updateFieldsMapping() {
            this.getEditorControlView( 'groundhogg_fields_map' ).updateMap();
        },

        getGroundhoggCache: function getGroundhoggCache(type, action, cacheKey, requestArgs) {
            if (_.has(this.cache[type], cacheKey)) {
                var data = {};
                data[type] = this.cache[type][cacheKey];
                return jQuery.Deferred().resolve(data);
            }

            requestArgs = _.extend({}, requestArgs, {
                service: 'groundhogg_v2',
                groundhogg_action: action,
            });

            return this.fetchCache(type, cacheKey, requestArgs);
        }
    };

    GroundhoggIntegration = $.extend( e.modules.forms.activecampaign, GroundhoggIntegration );
    e.modules.forms = $.extend( { groundhogg: GroundhoggIntegration }, e.modules.forms );

    /**
     * Gh Fields Map.
     */
    var GhFieldsMap = elementor.modules.controls.Fields_map.extend({

        updateMap: function updateMap() {
            var self = this,
                savedMapObject = {};

            self.collection.each(function (model) {
                savedMapObject[model.get('local_id')] = model.get('remote_id');
            });

            self.collection.reset();

            var fields = self.elementSettingsModel.get('form_fields').models;

            _.each(fields, function (field) {

                var model = {
                    local_id : field.get( 'custom_id' ),
                    local_label : field.get( 'field_label' ),
                    remote_id: savedMapObject[field.get( 'custom_id' )] ? savedMapObject[ field.get( 'custom_id' ) ] : ''
                };

                self.collection.add( model );
            });

            self.render();
        },

        getFieldOptions()
        {
            return elementorPro.modules.forms.groundhogg.fields;
        },

        onRender: function onRender() {

            elementor.modules.controls.Base.prototype.onRender.apply(this, arguments);

            var self = this;

            self.children.each(function (view) {

                var localFieldsControl = view.children.last(),
                    options = {
                        '': '- ' + elementor.translate( 'None' ) + ' -'
                    },
                    label = view.model.get( 'local_label' );

                _.each( self.getFieldOptions(), function (model, index ) {
                    // console.log( model );
                    options[ model.remote_id ] = model.remote_label || 'Field #' + (index + 1);
                });

                localFieldsControl.model.set( 'label', label );
                localFieldsControl.model.set( 'options', options );
                localFieldsControl.render();

                view.$el.find('.elementor-repeater-row-tools').hide();
                view.$el.find('.elementor-repeater-row-controls').removeClass('elementor-repeater-row-controls').find('.elementor-control').css({
                    padding: '10px 0'
                });
            });

            self.$el.find('.elementor-button-wrapper').remove();

            if (self.children.length) {
                self.$el.show();
            }
        }
    });

    elementor.addControlView( 'Gh_fields_map', GhFieldsMap );

})( elementorPro, ghMappableFields.fields, jQuery );
`
