### ISSUE TITLE
view.addInlineEditingAttributes for repeater

### ISSUE THREAD

**Issue by aumkarthakur** [elementor/elementor#7764]
There is not a single example in Elementor documentation for using inline editor with repeater. I did alot of research and found that we have to use get_repeater_setting_key inside render function so each repeater field will get unique render_attribute_string. 

But I am unable to find something like that for addInlineEditingAttributes.

My Code:

```
protected function _content_template() {
		?>
		<# if ( settings.list.length ) { 


		#>
		<dl>
			<# _.each( settings.list, function( item ) { 

		view.addInlineEditingAttributes( 'item.list_title', 'none' );

			#>
				<dt {{{ view.getRenderAttributeString( 'item.list_title' ) }}} class="elementor-repeater-item-{{ item._id }}">{{{ item.list_title }}}</dt>
				<dd>{{{ item.list_content }}}</dd>
			<# }); #>
			</dl>
		<# } #>
		<?php
	}
```

**Comment by bainternet** [comment]
@aumkarthakur 

You can look at our implementation for the tabs widget as an example:

https://github.com/elementor/elementor/blob/f0b36dbdb948b81ce2aab5e840d0f3396590b4c3/includes/widgets/tabs.php#L391-L429

**Comment by mapsmarketing** [comment]
A repeater has a unique ID for each item already which is the `_id`.

**render()**
```
foreach ( $settings['list'] as $item ) {
    echo $item['_id'];
}
```

**content_template()**
```
<# jQuery.each( settings.list, function( index, item ) { 
    view.addInlineEditingAttributes( 'text-' + item._id, 'basic' );
#>

    <div {{{ view.getRenderAttributeString( 'text-' + item._id ) }}}>{{{ item.text }}}</div>

<# } ); #>
```
