### ISSUE TITLE
Vertical Scroll Widget

### ISSUE THREAD

**Issue by Haim6130** [elementor/elementor#7768]
Hi,

It'll be great if you could develop an official Vertical Scroll Widget, like this: https://premiumaddons.com/vertical-scroll-widget-for-elementor-page-builder/

There are some problems with the Jet / Premium Addons's Vertical Scroll Widget, and It's very necessary tool that i'm using at almost every project.

Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Haim6130** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

Thanks!
Just imagine what we can do with Vertical Scroll Widget + Motion Effects :)

**Comment by lucbas** [comment]
+1 would love to see this feature!

**Comment by madbradj** [comment]
+1. Hate relying on 3rd party plugins

**Comment by jbalbinpe** [comment]
+1 !
