### ISSUE TITLE
The wiggets progress bar does not appear when viewing the web on an iPhone.

### ISSUE THREAD

**Issue by BOTELLA1** [elementor/elementor#7771]
The wiggets progress bar does not appear when viewing the web on an iPhone. 
when viewing it from an IOS device (iPad or Iphone) the widgets: progress bar is not displayed.
On an anndroid device yes. and on a mac too:

in Mac o Windows:

![captura_mac](https://user-images.githubusercontent.com/49367349/55684493-8331a980-594b-11e9-9656-3651f39499ea.jpeg)

In Iphone or iPad:

![captura_iPhone](https://user-images.githubusercontent.com/49367349/55684497-947ab600-594b-11e9-8f80-ea80a5daadec.jpg)

on an android device looks perfectly like on a pc or mac

**Comment by shilo-ey** [comment]
Hi @BOTELLA1 

Could not reproduce.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* Steps to replicate.
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.
