### ISSUE TITLE
Responsive options in Video Background section

### ISSUE THREAD

**Issue by zimmiel** [elementor/elementor#7777]
## Prerequisites

- [+] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [+] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If I want to use Video Background on the Desktop, I will be able to adapt a normal image for mobile (use options)
Surprise for me this is that I did not find settings for Video Background for Mobile. Even if video is not working on Mobile, let give the settings for Mobile version (what picture to put, how to place).
If in mobile version no video - image settings very important. But I did not find them.
Fallback image blinking on Desktop (when refreshing page), not have options correct image. Fallback image - this is not serious.

**Describe the solution you'd like**
I am not strong in english (using translator). I can not clear and concise description solution. I use picture in this letter.
Need add in Video Background responsive options in Mobile version options for Image (as in image options)

**Describe alternatives you've considered**
Duplicate the section and hide on mobile and have the image showing for mobile section

**Additional context**
picture
![vidbg](https://user-images.githubusercontent.com/42843497/55689314-a2e8c200-598b-11e9-9f41-57687c3bd47e.jpg)

**Comment by black-eye** [comment]
+1

**Comment by black-eye** [comment]
Also more responsive options for the video itself would be nice. 
I'm missing the options for alignment and cover (yeah, I know, image background and video background are two different beasts, but give us at least the option to center it).

**Comment by MariaOchoa17** [comment]
The video background does not work on mobile. It only works with a image but it does not load the video. 
Can someone help me please?

**Comment by shilo-ey** [comment]
Hi @zimmiel 

Most of the browsers do not allow background videos to play on mobile devices, and therefore Elementor won't enable this unexpected result.

With that being said, from v2.7 you will be able to decide if you want to try showing the video on mobile or not.

Adding responsive controls to those features is not a thing we are currently going to add due to the reasons mentioned above and due to performance reasons.

Thanks for your feedback!
