### ISSUE TITLE
Custom post type - better dynamic selection

### ISSUE THREAD

**Issue by Luxamman** [elementor/elementor#7783]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When having a lot of custom post types with pods or AFC and so on and then select them in Elementor for a single page element, the selection pop up gets really filled and the overview is gone after a few post types with lots of content. For example - I try to work with about 80 keys in two types and one is still missing.

**Describe the solution you'd like**
Separate the post type from the post type key in the pop up. So when clicking on for example a textelement, then on dynamic content and select a Pods field. We should be able to select the type and than the key in separate selection fields. 

Example of how it is now and how it could be:

![example](https://user-images.githubusercontent.com/20417555/55714069-3ce35580-59f2-11e9-8ea1-fc63414ed316.png)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by bainternet** [comment]
@Luxamman 

We don't separate the custom fields per type because our templates can be used for multiple types at once.

however, using our API, you can always create your own [Custom Dynamic Tag](https://developers.elementor.com/dynamic-tags/) which will act and work exactly as you want it to.


Thanks for the feedback.
