### ISSUE TITLE
elementorFrontend.init() breaking certain features

### ISSUE THREAD

**Issue by mgibbs189** [elementor/elementor#7786]
Hello,

FacetWP developer here - a customer received this reply from your Support team, hence the ticket:

```
I am afraid development issues are not handled here at the support channel. Here we can only provide support for existing features. This needs to be asked on the GitHub project where our developers can assist you with this.
```

### Context
FacetWP is an ajax-based plugin that dynamically refreshes the results. It calls `elementorFrontend.init()` to re-initialize any necessary Elementor JS after each ajax refresh.

### Problem
**URL**: https://investlleida.demoswp.com/oportunitats-de-negoci/

On mobile (or when the browser is made narrow), a hamburger menu appears. After selecting a facet choice, the hamburger menu no longer opens.

### Question
There appears to be a problem with `elementorFrontend.init()` specifically. Commenting it out prevents the hamburger menu issue, but also prevents *any* Elementor JS from re-initializing. Is there a better way to do this? Or perhaps this is a bug with `.init()` itself?

**Comment by MarketingGeek** [comment]
Following....

**Comment by bainternet** [comment]
@mgibbs189 

Simply put, `elementorFrontend.init()` should not be called.

you need to initialize the elements manually by mimicking the method and exclude function may break stuff or calling the element handler and triggering its own init.

Thanks.

**Comment by mgibbs189** [comment]
@bainternet is there a way to programmatically tell which Elementor "features" are active on a given page? And could you give an example of `triggering an element's own init`?

This is for FacetWP's [Elementor integration add-on](https://github.com/FacetWP/facetwp-elementor/blob/master/assets/js/front.js#L2-L5) -- FacetWP refreshes the listing via AJAX, it works by replacing the HTML and thus destroying event listeners attached to the prior elements... hence the need to re-initialize any necessary Elementor JS.

**Comment by mgibbs189** [comment]
@bainternet @KingYes sorry to bother but a response here would be much appreciated.

**Recap:** our plugin (FacetWP) dynamically updates result listings via ajax and, as such, needs to re-initialize any relevant JS afterwards. Here's the relevant code: https://github.com/FacetWP/facetwp-elementor/blob/master/assets/js/front.js#L2-L6

We were advised not to use `elementorFrontend.init()` (see above), but we haven't been able to find a good alternative.

As mentioned before, we're developers for FacetWP. We're not building any sites directly, and therefore we need a **generalized** solution for (a) determining which Elementor JS features are enabled on the current page, and (b) re-initializing those features.

Does that make sense? Thanks for your time.

**Comment by maxjutras** [comment]
+1 for a way to reinit some elements (such as the page animations) that breaks when navigating using Ajax.

elementorFrontend.init seemed to do the job but it breaks all the js events such as the hamburger menu.

Any alternatives?

Thanks

**Comment by omarkasem** [comment]
I just faced a similar issue for a client using FacetWP, the elementor accordion wasn't working after filtering with FacetWP so here's how i solved it so if anyone face the same issue

`				jQuery(document).on("facetwp-loaded", function() {
					var in_use = ("" != FWP.build_query_string());
					if(jQuery(".search_results_kit")){
						if(in_use === true){
							jQuery(".search_results_kit").show();
							if(FWP.is_refresh === false){
								jQuery(".elementor-widget-ae-acf-repeater").each(function() {
									elementorFrontend.elementsHandler.runReadyTrigger( jQuery( this ) );
								});
							}
						}else{
							jQuery(".search_results_kit").hide();
						}
					}
				});`

**Comment by willryanuk** [comment]
@mgibbs189 @maxjutras did you get any further with this? I want to load an Elementor block over ajax, and then initialise it. Did you find a way to make this work reliably?

**Comment by m16averick** [comment]
I found solution, but it is less agressive than frontent init

<script>
	jQuery('.elementor-element').each(function() {

		elementorFrontend.elementsHandler.runReadyTrigger( jQuery( this ) );

	});
	</script>

It triggers every element back to work :) I've put it in my theme, but you can implement it anywhere you like ^^

**Comment by ofmarconi** [comment]
@m16averick Have you tried running a page containing e-lottie in the console?

It duplicates all e-lottie elements each time it runs, similar to: elementorFrontend.init();

**Comment by coadr93** [comment]
> omarkasem

thanks!

**Comment by portnovyury** [comment]
[omarkasem](https://github.com/omarkasem) this solution worked for me, thank you very much!
