### ISSUE TITLE
Check for vulnerability

### ISSUE THREAD

**Issue by djekanovic** [elementor/elementor#7792]
I got 2 sites hacked in last 2 days. On one i found code in elementor plugin. Can you check if elementor haves vulnerability, or they just used it to put it there

File in place

public_html/wp-content/plugins/elementor1/core/files/manager.php
[elementor injection.txt](https://github.com/elementor/elementor/files/3056493/elementor.injection.txt)

**Comment by dameer** [comment]
!WOW! don't even try to open the above file...

**Comment by bainternet** [comment]
@djekanovic 

Not that we know of, this file should look like this:

https://github.com/elementor/elementor/blob/master/core/files/manager.php

thanks.
