### ISSUE TITLE
Copy from one domain, paste on another domain page

### ISSUE THREAD

**Issue by k040711** [elementor/elementor#7794]
**What problem is your feature request going to solve? Please describe.**

Hi, i love the current copy and paste, very nice feature, but would also like a copy from one domain and paste on another domain page if possible.

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
currently im exporting the full page and importing on to the new domain, but its a pain in the *** if you got a lot of sites and build a lot of page...

**Additional context**
yeah just a simple copy paste to any domain would be great, thanks guys!

**Comment by black-eye** [comment]
+1 Yes pls! 
If the cross domain copy of the images is the issue, than just paste the page without them. Export/import is the solution but not as easy as copy/paste.

**Comment by bainternet** [comment]
@k040711 @black-eye 

Elementor Copy/Paste is so powerful because it's based on [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), sadly the one limitation is that it can't be accessed cross-domain.

thanks for the feedback.

**Comment by mcarv2018** [comment]
+1 Very helpful!
