### ISSUE TITLE
Stretch Section issue since 2.5.12 update when resize window

### ISSUE THREAD

**Issue by ppulpipatnan** [elementor/elementor#7795]
## Prerequisites

- Fresh installation of WordPress 5.1.1
- Activate "Twenty Nineteen" theme and Elementor plugin only. No other plugins activated.
- Issue fixed if roll back to Elementor v 2.5.11

## Description

Create a page using Elementor Page builder. Then use "Stretch Section" option and save changes. See screenshot here http://prnt.sc/n9e8a3

## Steps to reproduce

Preview "Stretch Section" on frontend. Once page loaded. It displays correctly but when you resize window width. The main section width isn't resized like previous version of Elementor. So it caused responsive layout issue. See screenshot here http://prnt.sc/n9e8d1

If you take a look at browser console. You will see that main section width is fixed and isn't resize at all. See screenshot here http://prnt.sc/n9e8mh

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
- WordPress 5.1.1
- Elementor 2.5.12
- Twenty Nineteen Theme
```
</details>

**Comment by fontesjoaquim** [comment]
This is exactly what started to happened with me yesterday.
That "Stretch Section" tool it's very useful, but it has to work well!

What can I do to solve this? Will this bug be fixed soon in the Elementor version 2.5.12?
(I'm afraid I will not be able to roll back the version...)

**Comment by MapSteps** [comment]
In one of my plugins, I'm using jQuery to fire an event on resize.
This stopped working for me as well with 2.5.12.

Basically, running any action inside

```
$(window).resize(function() {
    ....
});
```

is being ignored.

Rolling back to 2.5.11 worked for me as well.

**Comment by sermalefico** [comment]
Bug, lost responsiveness. Rollback.

**Comment by Netzlichter** [comment]
Same problem here. Resize of several plugins stopped working. Like Essential Grid for example...

**Comment by freelancesam** [comment]
Same problem

**Comment by gicobi** [comment]
I had this issue for the past 2 hours and didn't realize that it was happening to other people until I saw a thread in a Facebook group linking to this issue in Github. I cannot work until this problem is fixed, the sites are now all messed up because of this.

**Comment by Netzlichter** [comment]
For now you can easely rollback to 2.5.11 with this plugin:
https://de.wordpress.org/plugins/wp-rollback/

It is working without issues!

**Comment by Netzlichter** [comment]
Content should not be lost because it is stored in the database. And 2.5.12 was only a bugfix release. Or maybe a bugged release ;)...

**Comment by xeonboy** [comment]
> Content should not be lost because it is stored in the database. And 2.5.12 was only a bugfix release. Or maybe a bugged release ;)...

Thanks bro, that's a real life saver! :D

**Comment by gicobi** [comment]
Thank you Netzlichter it worked perfectly and started work late but at least a completed some things.

> For now you can easely rollback to 2.5.11 with this plugin:
> https://de.wordpress.org/plugins/wp-rollback/
> 
> It is working without issues!

Thank you Netzlichter it worked perfectly and started work late but at least a completed some things.

**Comment by mcrowell** [comment]
I can also confirm that the stretch section is causing responsive issues on 2.5.12

**Comment by Berno57** [comment]
I am experiencing the same responsive issues on 2.5.12
When I rollback Elementor to 2.5.11 my version of Elementor Pro is disabled and will not work.
How do I, also, roll back Elementor Pro?

**Comment by Netzlichter** [comment]
After Rollback to 2.5.11 my Elementor Pro (2.5.5)  was not deactivated.

**Comment by electro-Z** [comment]
rolled back to 
elementor 2.4.7
elementor pro 2.4.8

all went back to normal

**Comment by xeonboy** [comment]
I rolled back to 2.5.11 and it works now (Elementor Pro is still latest version). It seems Elementor Pro also has a bit of issues in the backend part when it comes to responsiveness.

**Comment by tauseefch** [comment]
Having same issue my self since the latest update please fix it as soon as possible.

**Comment by black-eye** [comment]
Honestly, the updates started to be quite a huge issue lately - was there any update/bugfix in 2.5.x that haven't introduced some other issues, usually even more serious? I'm really afraid to do (even minor) updates now... :-(

**Comment by pinguinlands** [comment]
Also on mobile version it's impossible to work.... https://prnt.sc/n9zu7n

**Comment by nesoor** [comment]
Same issue here!
