### ISSUE TITLE
Dynamic Featured Image in Editor Mode

### ISSUE THREAD

**Issue by SeitenDesign** [elementor/elementor#7800]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have created a page header template that takes the Featured Image as background. When I edit the page with Elementor, the background is not displayed in Editor Mode. To see the whole design, I have to constantly swap between the editor and the live page.

**Describe the solution you'd like**
The dynamic background image should shown in editor mode as well.

![elementor-bg](https://user-images.githubusercontent.com/11595359/55798001-198dd880-5ace-11e9-85a4-c365eedc6b25.jpg)

**Comment by bainternet** [comment]
@SeitenDesign 

Make sure you set the Preview Settings, so Elementor Will know where to get the dynamic data from.


![llgDIGF](https://user-images.githubusercontent.com/660572/55870638-b06f9900-5b91-11e9-8e4f-787c8ddde179.png)

**Comment by SeitenDesign** [comment]
I can not find these settings
