### ISSUE TITLE
Prevent Easing on Parallax - Animation should stop when scrolling stops

### ISSUE THREAD

**Issue by d-marvin** [elementor/elementor#7804]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

New parallax is awesome. But it lags, perhaps on purpose, like an inertia effect: It eases into position after scrolling has stopped. This length of this effect is inconsistent among browsers.

**Describe the solution you'd like**
I'd like to have the ability to switch this off, please. I'd like parallax to stop when the page stops scrolling. If you have a static foreground element above a parallax background, the extra half second of easing into position ruins the effect of having multiple planes.

**Describe alternatives you've considered**
I've used a third-party plugin (piotnet) which animates parallax "correctly" (i.e. it stops when page scrolling stops), but I prefer Elementor's new native version better because it allows device-specific control (yay!). I'd rather stay with Elementor and not use plugins. Alternatively, I could try patching this with code (also not preferred alternative).

**Additional context**

**Comment by shilo-ey** [comment]
Hi @d-marvin 

Thanks for your feedback.

This behavior is due to `animation-duration` CSS property.

You can simply add the following CSS rule to your website:

```CSS
.elementor-motion-effects-element, .elementor-motion-effects-layer { 
   animation-duration: 0; 
}
```

If your rule is not strong enough, try adding `!important` to it.

Thanks!

**Comment by d-marvin** [comment]
Hi and thank you for helping.

Unfortunately, I tried it but it didn't work. However "**transition**-duration:" worked.

It'd be great if it didn't need a code "hack" to work like normal web parallax. Perhaps they can add an inertia on/off toggle button to the Editor.
