### ISSUE TITLE
Elementor still having stretch / responsive issues in backend despite latest v2.5.13 update

### ISSUE THREAD

**Issue by xeonboy** [elementor/elementor#7815]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

1) Create a new Page and edit it with Elementor. Or just open an existing page in Elementor.

2) Now, try previewing it in Desktop / Tablet / Mobile preview (https://i.gyazo.com/971fea4be9a53ccee8a3bd5ae3328c5a.png), switch it around and play with the different preview modes. You'll see there's some big issues with the responsiveness of all the elements (same as #7795).

I've cleared all cache, everything. The recent versions of Elementor is becoming a total nightmare and there's no way to roll-back Elementor Pro.

It seems v2.5.13 did not fully fix all the responsiveness issues that v2.5.12 threw out.
Even on v2.5.11, this issue existed as well.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

[SystemInfo.txt](https://github.com/elementor/elementor/files/3064706/SystemInfo.txt)

```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @xeonboy 

Thanks for your feedback.

Unfortunately, we cannot reproduce this issue.
If this issue persists please contact our support with your login credentials and mention this thread.

Thanks.
