### ISSUE TITLE
Clean code: Make Elementor powerful and performance omptimized

### ISSUE THREAD

**Issue by alriksson** [elementor/elementor#7817]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor is good but I'm frustrating new page builders like Oxygen page builder is doing a great job when it comes to smoothness, controls and performance. They do not load anything that isn't needed on that page. This means CSS and JS, if an element or function isn't used it will not load that code. See: https://youtu.be/RmIrqJ9Wd0U?t=623

**Describe the solution you'd like**
- Elementor is great but I think oxygen is taking market share since it's powerful look at their list of why:
- https://oxygenbuilder.com/why/
- Remove the bottleneck using theme (yes hello theme is possible but why) and add theme functions into the page builder.
- Improve how things load, don't load unused CSS and JS or code in general that is not in use. Easy 1.0 vanilla version would be to add global control of enable/disable widgets/elements from elementor settings. If I never use a widget then I can disable it. And if I try to use it with page builder gray it out and overlay it with "disabled in setting".
- Make it more development friendly for advance users. Maybe a toggle in elementor settings which open ups more advanced features. 

https://youtu.be/RmIrqJ9Wd0U?t=623

**Describe alternatives you've considered**
Oxygen page builder!

**Additional context**
Just check the performance (non of you have optimized it, but using your own page builder to design)

Oxygen: https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Foxygenbuilder.com%2Ftour%2F

Elementor: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Felementor.com%2Ffeatures%2F

I feel Elementor is missing the advanced user. Would like more control make Elementor more powerful and performance optimized.

You have prioritized, designers, marketing now it's time for advanced users and performance, don't you think?

**Comment by infinitnet** [comment]
I was about to open a ticket about not loading unused CSS, but it looks like this one covers this already. However, I'd like to see this done automatically rather than having to disable widgets manually.

The visual editor would just store which widgets are in use when saving a page and then load only the CSS and JS that's required for the widgets used on each particular page.

When launching the visual editor, it would load all the CSS/JS to make sure that all widgets are available when editing a page.

This way this would work automatically and one a per-page level and there would be no need to manually mess with disabling and enabling widgets you may or may not use somewhere on the site.

Shouldn't be too hard to implement and would be a huge advantage. I've already considered moving to Beaver Builder simply because of all the bloat that Elementor loads on every single page even though I use very little of it, meaning 95% of the CSS it loads is just unused and heavily impacts page size and performance.

**Comment by black-eye** [comment]
+1

**Comment by alriksson** [comment]
@shilo-ey something you would like to comment about? I struggle a lot with performance. It loads decent and around 2-3 seconds with a good connection. But users is on mobile and 3g we have to tackle the core problem for performance. It's too much css and js that is not used that is loaded. And I have optimized a lot with offloading things and everything that I can do and control in terms of performance from the side. But that is not the issue, it is as optimized it can be there. The issue is the code within the core files that are loaded. That we don't use and I can not and should not touch core files.

See what @infinitnet wrote above. Why not compile everything upon saving? Or show a pop up one save. "save and generate new css and js files".  This is the future if we are going to compete with a custom built website. Styling is no issue, everything is possible you will keep on improving such as well. But performance on this level is not there. Many DOM elements which make the CSSOM tree much more complex to render and then a lot of css and js that is not used.

If you add this and force third-party addons to elementor to hook into this, we would have a game changer.

**Comment by ramonkcom** [comment]
IMHO, this is more important than new widgets or fancy effects. It's the most important issue for the long term success of Elementor. I hope the E team take it seriously.

**Comment by kroeberk** [comment]
100% support this. This will in the long run determine if we use elementor. Especially DOM size reduction is a huge thing for SEO mobile optimization.

**Comment by alriksson** [comment]
@kroeberk Indeed, mobile optimization in general. Makes it much more complex to render the DOM tree and so even the CSSOM tree, when all individual sections get their own identical code but threated individually since they are individual divs. Just a lot of extra code.

Yes, some users want individually sections but for some who don't, I think there should be a setting to remove it and treat it globally. And then you can unlock specific sections just like global elements. A settings tab and we would reduce a lot of extra code as well.

By doing so we reduce the multiple rows of styling that is doing the same thing but it has to add by targeting each individual section. As long as the user doesn't use custom css classes and add custom css to do this. But then we remove parts of the idea of using a page builder.


I think and hope the elementor team can come up with a smart solution here👍

**Comment by lempengstudio** [comment]
+1

Desperately need this. I've been thinking of migrating to Oxygen Builder when their custom post loop feature is available with version 3 - it's now still in Alpha.

**Comment by alriksson** [comment]
@lempengstudio Also fighting against myself to do so. Elementor is still much better UX and UI even though I even there miss some things to build smoother and faster.

But oxygen builder is really ahead when it comes to performance and a few other things for the advanced user: https://www.youtube.com/watch?v=AZCeVLpZ8is&t=1092s

**Comment by bentalgad** [comment]
+1 +1 +1 +1 Elementor's performance is probably the worst ever and it's really a shame because it's really really convenient to use other then that!

**Comment by danisaurus** [comment]
Agreed. We've done everything possible to increase our site speed and every time we update Elementor it decreases again. We need it to compile based on page and not serve all the bloat!

**Comment by dainemedia** [comment]
I absolutely love Elementor and it’s flexibility and design options and just how fast we can produce great looking designs, but as an SEO and marketer, performance is hugely important and excessive DOM nodes make crawling a nightmare, never mind speed and performance. The HTML to content ratio is ridiculous.

We had a site that was growing well in organic search, then recently switched it to an Elementor template build and set up we’d been working on and the rankings ranked.

Suffice to say, we’re now scrapping Elementor and building a custom theme from scratch.

So disappointing, considering the huge potential.

I’ll be recommending to my group of 3.1k affiliate marketers and SEOs to move away from it.

**Comment by shilo-ey** [comment]
Hi All,

Elementor has been built in order to allow developers, designers, and marketers better experience and allow them to build beautiful sites faster. 
Improving the user experience and our code is always on our mind.

The following versions of Elementor will take care of this aspect by providing better infrastructures for various product improvements that are on our pipeline.

As for your requests, we will deal with the concrete ones after the infrastructure phase is over. our API is constantly improving and we urge you to visit our [developers blog](https://developers.elementor.com/blog) to receive frequent updates.

We appreciate your feedback.

Thanks!

**Comment by alriksson** [comment]
@shilo-ey Sounds great to hear some news from you guys regarding this concerns. I'm happy to hear.

What are the concrete fixes you have received or gathered so far would be good if we could receive more information from your side?

I, of course, wonder when and that is always difficult and something I understand you won't be able to answer. But maybe you can answer how long or how many major updates will be improving the infrastructures och the products?

Thanks!

**Comment by shilo-ey** [comment]
In the following versions (2.7, 2.8, 2.9) we will work on several improvements and features.
In the upcoming version, we will introduce a new Editor JS API (under the hood changes), converted JS to ES6 and much more.

to get the latest news you can follow our [developers blog](https://developers.elementor.com/blog)

thanks

**Comment by infinitnet** [comment]
@shilo-ey I think the main question here is when you're going to implement on-demand loading of JS and CSS, ie. only load required/actually used JS and CSS on a per page level and work on reducing DOM size. These are the main concerns that currently result in performance and SEO issues and are the reason some people are moving away from Elementor towards Oxygen or custom themes.

**Comment by mickaelperrin** [comment]
Closed ??

For what I understand, is that Elementor team is focused on bringing easy to use and fancy addons but not to deliver optimized code.

With the everyday increase of new extensions, fancy widgets based on elementor, I guess that it will be a huge task to update the base engine and ensure a compatibility with all the existing plugins. At least, less JS and CSS could be achieved but regarding the html DOM, I guess it will be far more difficult.

So, in my opinion, only builders that have performance as main goal since the beginning will be able to offer reasonable results in comparison to custom development in the near future.

Sadly.

**Comment by black-eye** [comment]
@mickaelperrin I'm affraid, you're right. Changes in DOM would be really complicated backward compatibility wise.

Maybe Elementor developers could consider building a new more powerful and performance oriented version prepared from scratch. With less starter widgets, but more options in the core (post loop, custom breakpoits, conditions, global settings, nested sections, better work with columns and gaps - you know, basicaly first 10 most requested/commented issues here on github).

I can imagine lots of these features would be qiute hard to implement on the basic's of the current core. Starting all over again with the knowledge (and mistakes) gained so far (and knowing there would be no need for 100% compatibility) would be probably easier. 

This new Elementor "Developer Edition" would be more like a framework, prepared for custom extending.

I would be more than hapy to pay extra money for as it would be a completely new plugin.
Just my 2 cents. ;-)

**Comment by bentalgad** [comment]
> Elementor has been built in order to allow developers, designers, and marketers better experience and allow them to build beautiful sites faster.
Improving the user experience and our code is always on our mind.

Is this the promotion newsletter or GitHub ? :)

**Comment by alriksson** [comment]
I think this demonstrates the performance issues compared with the other page builders: https://www.youtube.com/watch?v=yCXjASm4j_w

How much better oxygen as an example performs.

**Comment by infinitnet** [comment]
I'm moving all my sites to Oxygen. It's frustrating to see this ticket just getting closed and not taken seriously but instead just ticking it off with some generic response about working on new features which isn't the point here at all. Based on that I expect Elementor to just get more and more bloated over time. It's a shame because it's otherwise an amazing product.

**Comment by srikat** [comment]
More info on what's wrong with Elementor (and other builders) w.r.t bloat (unnecessary loading of assets):

https://youtu.be/oKr9T2U4lno?t=1411

**Comment by alriksson** [comment]
> In the following versions (2.7, 2.8, 2.9) we will work on several improvements and features.
@shilo-ey 

Please be more specific what to expect in 2.8, 2.9 and **3.0**. What to expect? Reducements of DOM elements and start utilize flex-box and ID's instead? Reduce bloated code? What time frame to expect, 2019 or 2020?

I think many users in this thread and more want some more transparency. More and more move over to the builders which do ni bloat and create 50 of divs for 1 single  <h1> element. And we would not expect a final date but we would like to know what to expect and some kind of roadmap where it's heading.

- What, when and how long do we need to wait? If we don't really see what to expect or it's not enough of what the audience expect it's not worth waiting or maybe it is?
- Maybe the community can help out solving things?

**Comment by LauGau** [comment]
Yes, I'am really looking to move for Oxygen.
What I hope for Elementor : 

- Ability to detect modules effectively used on each page (disable all the other scripts & styling related to them)
- Move to flexbox (it's time to finish the crazyness of all that unecessary DIVs)
- The ability to use css GRID.
- Use CLASS & ID Styling (like in Oxygen) 

No need for other modules !
There is plently of addons for that.

I expect from Elementor team to work on the CORE and it's main problem : performance.
Because there is no point to build websites FASTER, if the websites are SLOWER.

**Comment by black-eye** [comment]
Another piece of the puzzle: https://woocart.com/blog/best-woocommerce-page-builder
😞

**Comment by maeonian** [comment]
+1

As a new (and fan) of Elementor, I was really surprised to see the serious amount of DOM elements / nested divs. I have my site logo within ten whole divs.

I know it would break a lot of current designs but something needs to be done about the quality of the code being applied. Theme builders / WYSIWYG have the reputation of being bloated and slow, and I would love for Elementor to not be in that same league.

**Comment by beposss** [comment]
> 
> 
> Yes, I'am really looking to move for Oxygen.
> What I hope for Elementor :
> 
>     * Ability to detect modules effectively used on each page (disable all the other modules's scripts & styling related to them)
> 
>     * Move to flexbox (it's time to finish the crazyness of all that unecessary DIVs)
> 
>     * The ability to use css GRID.
> 
>     * Use CLASS & ID Styling (like in Oxygen)
> 
> 
> No need for other modules !
> There is plently of addons for that.
> 
> I expect from Elementor team to work on the CORE and it's main problem : performance.
> Because there is no point to build websites FASTER, if the websites are SLOWER.

Any updates?

After 3 years of using Elementor, I think that I will move to Oxygen too with other my partners.. :(

**Comment by lempengstudio** [comment]
> After 3 years of using Elementor, I think that I will move to Oxygen too with other my partners.. :(

Wow.. talk about timing 😄 

I've just finished converting one of my Elementor Pro website to Oxygen - my first Oxygen website. 

98% same design, 60% less page size - and Google pagespeed Insight was like night and day. 

First time I've achieve score of 94 on mobile with Google Insight for WP with Toolset. Can't wait to migrate other website to Oxygen.

However, in my opinion Elementor Pro is still the easiest page builder for WP. With Oxygen you have to get your hand dirty on custom function and css.

**Comment by keremnymn** [comment]
Problems of too long DOM tree and unused CSS loading for Elementor is still an issue for me. Google is freaking out because my website in mobile connection takes more than 3 seconds.
Any updates on this?

**Comment by blinkbat** [comment]
+1 for easy unloading of unneeded scripts / styles, better DOM architecture w/ less nesting

**Comment by Jordidriesen** [comment]
Definitly needs more attention, Oxygen is what i'm leaning towards since elelemtor performance is only getting worse...

**Comment by yansircc** [comment]
+1
Elementor google insight speed is really slow.
I used:
WP Rocket
SG Optimize
CleanUp Assets
GTmetrix score is great but no use for GIS.
Take every effort but the score is always under 80.
I love Elementor but the performance of E really need a huge improvement..

**Comment by MichaelDarko** [comment]
The more I'm looking into performace issues with Elementor, the more I'm sceptical about Elementor's future and Elementor's focus on being a professional tool.

Professional tool should produce professional results. WebFlow produces clean code and is super-fast. Oxygen produces clean code and is also fast. Elementor produces crazy amount of divs, loads unnecessary files and is just painfully slow, if you build something more complex. (All the reasons why professionals hate page builders.)

Elementor is great at marketing, attracting users, releasing good looking fancy features, but the fundamentals are not getting enough attention.

I've been trying out Oxygen page builder and my early conclusion was this:

- It's posibble to build more complex websites with Oxygen.
- Performance is on a different level with Oxygen.
- Elementor is nicer and more comfortable to use.

I'm still not ready to switch from Elementor, but I'm more and more concerned about Elementor's focus. Is it going to be a "toy" page builder for amateur users, or is it going to be a professional tool (like WebFlow) for WordPress that professionals can confidently use to build professional websites?

**Comment by jefechang** [comment]
Can this issue be considered close since unnecessary css is loaded?

**Comment by Sven74Muc** [comment]
So how does version 3.0 handles the issue of this threat?

**Comment by webenadam** [comment]
2 Years later, Still the same issue.

**Comment by denizbinay** [comment]
the elementor team is not even responding properly? An important discussion that should worry the team. We have used Elementor for all customer projects so far. Next time we will try oxygen.

**Comment by jessejamesrich** [comment]
What a timely thread. I'm just trying to remove the unnecessary scripts and css, but this highlights a boatload of other issues I was willing to look past and like, the takeaway a couple years later is Oxygen Builder is better?

**Comment by srikat** [comment]
> What a timely thread. I'm just trying to remove the unnecessary scripts and css, but this highlights a boatload of other issues I was willing to look past and like, the takeaway a couple years later is Oxygen Builder is better?

Better, best etc. is subjective.

Why don't you watch the videos on their site, in YouTube and play with a demo in the sandbox? https://oxygenbuilder.com/try/atomic/
