### ISSUE TITLE
Woocommerce action & filters not working

### ISSUE THREAD

**Issue by doruradu** [elementor/elementor#7819]
Hi, I'm not sure if it's a bug or I'm not doing it right. Hope I won't waste your time with a stupid question :-s I'm trying to add an personalisation feature to the product page, but the woocommerce hooks are not working. I tried using 3 different plugins (woocommerce custom fields, woocommerce product addons, woocommerce ppom) and with a custom code, but neither of them worked.

Here is what I'm trying to achive:

![Screenshot 2019-04-11 at 13 51 51](https://user-images.githubusercontent.com/8161136/55951931-10814080-5c61-11e9-978b-283e822f67d4.png)

This is the code I'm using:

`function personalizare_custom_field() {
 global $post;

 $product = wc_get_product( $post->ID );
 
echo '<div class="cfwc-custom-field-wrapper"><input type="text" id="cfwc-personalizare" name="cfwc-personalizare" value="Vreau un text aici"></div>';

}
add_shortcode( 'arata_personalizare', 'personalizare_custom_field' );

function personalizare_adauga_date( $cart_item_data, $product_id, $variation_id, $quantity ) {
    
 if( ! empty( $_POST['cfwc-personalizare'] ) ) {
 $cart_item_data['title_field'] = $_POST['cfwc-personalizare'];
 $product = wc_get_product( $product_id ); 
 $price = $product->get_price(); 
 $cart_item_data['total_price'] =  $price + 29; 
 }
 return $cart_item_data;
}
add_filter( '**woocommerce_add_cart_item_data**', 'personalizare_adauga_date', 10, 4 );

function personalizare_calculeaza_pret( $cart_obj ) {
 
 // Iterate through each cart item
 foreach( $cart_obj->get_cart() as $key=>$value ) {
 if( isset( $value['total_price'] ) ) {
 $price = $value['total_price'];
 $value['data']->set_price( ( $price ) );
 }
 }
}
add_action( '**woocommerce_before_calculate_totals**', 'personalizare_calculeaza_pret', 10, 1 );

function personalizare_arata_text( $name, $cart_item, $cart_item_key ) {
 if( isset( $cart_item['title_field'] ) ) {
 $name .= sprintf(
 '<p>%s</p>',
 esc_html( $cart_item['title_field'] )
 );
 }
 return $name;
}
add_filter( '**woocommerce_cart_item_name**', 'personalizare_arata_text', 10, 3 );`

After a lot of debugging, I ended up writing to the elementor support team which directed me here. I'm pretty sure the hooks I'm trying to used are ignored by elementor.

Can you, please, help me fix this? Thanks for reading. Have a great day!

**Comment by nuritsha** [comment]
Hi @doruradu,

The hooks you are using are cart related hooks, and you should be able to see their output either on the  cart page or when using the menu-cart & add-to-cart widgets.

Thanks!
