### ISSUE TITLE
VueJs in Elementor Widget

### ISSUE THREAD

**Issue by devrobinkroeker** [elementor/elementor#7823]
Hi,
I want to create an elementor widget with vuejs in it. Does anyone know how to do this or know where I can find resources?

**Comment by joezimdelta** [comment]
Well, as long as you have VueJS imported somewhere (I'm already investigating [the "correct" way to import scripts/styles related to a widget](https://github.com/elementor/elementor/issues/7907)), you should be able to write any HTML/CSS/JS you'd like in your rendered template, so it shouldn't be too hard to adapt some Vue components to that. The one thing that might be difficult is dynamically generating an ID for each Elementor widget so you can specifically mount a separate Vue instance to each widget.

Now, if you're trying to use a single large Vue instance and make Elementor widgets act like individual Vue components, I'm not sure how to help there.

**Comment by joshlacey** [comment]
So I tried copying a Vue component into the HTML widget within elementor. At the bottom of my footer.php file in my theme I added a `new Vue({ el: '#vue-container' });` script which allows me one container per page. 

It almost worked except that the HTML widget likes to sometimes strip out unrecognized html which breaks the Vue component. I'm trying to hunt down where that is happening. Anyone have any ideas?

**Comment by devrobinkroeker** [comment]
@joezimdelta Thanks. Yeah I think in our team we would need these ids.

**Comment by joezimdelta** [comment]
It's not particularly difficult to [create custom widgets](https://developers.elementor.com/creating-a-new-widget/) and you can definitely create one that generates those custom IDs, allows you to add custom Vue template code without stripping anything, and even add the `new Vue(...)` itself.

**Comment by hkmsadek** [comment]
Did you find any solution for this?
