### ISSUE TITLE
Safari: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by golokios** [elementor/elementor#7824]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor worked fine for me on a few other sites. But now i wanted to redesign our Agency website wit the newest version of elementor and pro.

In Chrome everything works fine, but in safari, there are no animations and my content is not even loading in correctly (besides the hero section).

I get the same error 2 times in Safari:
- RangeError: Maximum call stack size exceeded. (isPlainObject --- jquery.js:2:2217)
- RangeError: Maximum call stack size exceeded. (isPlainObject --- jquery.js:2:1578)

You can check the error yourselve: http://redesign.okapi-werbeagentur.de/

sorry if my english isn't so good, i am from germany :).

## Steps to reproduce

Haven't tried to reproduce jet, but i am using the following plugins:
- Elementor 2.5.13
- Elementor Pro 2.5.5
- AnalogWP Templates 1.1.2
- Envato Elements 1.0.1
- InfiniteWP - Client 1.9.1
- Jet Elements For Elementor 1.15.8
- JetEngine 1.3.1
- JetThemeCore 1.1.8
- Kava Extra 1.0.3

And my theme is Kava 1.2.5

And Wordpress is 5.1.1

And yes, i tried to turn every plugin off and i tried to go with a standard Theme from WP.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Hosted on Hetzner.de

```
</details>

**Comment by shilo-ey** [comment]
Thanks @golokios 

We will take a look and update this thread.

Thanks

**Comment by shilo-ey** [comment]
Hi @golokios 

We can see that your website has changed. why have you changed it?

Thanks

**Comment by golokios** [comment]
@shilo-ey I did that, because i need to work on this website at the moment. But the error is still there

**Comment by shilo-ey** [comment]
Can you reproduce this issue on a different page and send us a link?

**Comment by sermalefico** [comment]
Motion effects dont works in ios safari. Las animaciones no se reproducen.

**Comment by golokios** [comment]
@shilo-ey ok... I just rolled back to an older version of my domain. And the error is still there.
you can check it out here: http://redesign.okapi-werbeagentur.de

But if i try to use motion effects on another side i made, there are no problems in safari

**Comment by sermalefico** [comment]
I'm on safari. Everything works correctly when I'm editing in elementor in the backend. But in the frontend the effects are not reproduced and give error.

extend jquery.js:86

`                    a = g[d], c = e[d], g !== c && (j && c && (n.isPlainObject(c) || (b = n.isArray(c))) ? (b ? (b = !1, f = a && n.isArray(a) ? a : []) : f = a && n.isPlainObject(a) ? a : {}, g[d] = n.extend(j, f, c)) : void 0 !== c && (g[d] = c));

`
isPlainObject jQuery.js:116
` if (!a || "object" !== n.type(a) || a.nodeType || n.isWindow(a))    `

**Comment by shilo-ey** [comment]
[**@golokios**](https://github.com/golokios) commented on [Apr 23, 2019, 6:14 PM GMT+3](https://github.com/elementor/elementor/issues/7824#issuecomment-485846820 "2019-04-23T15:14:13Z - Replied by Github Reply Comments"):
> @shilo-ey ok... I just rolled back to an older version of my domain. And the error is still there.
> you can check it out here: http://redesign.okapi-werbeagentur.de
> 
> But if i try to use motion effects on another side i made, there are no problems in safari


Have you tried to disable the additional plugins you have and changing your theme?

Please contact our support at support @elementor.com for better troubleshooting and isolation of this issue and mention that you were directed by me and reference this issue.


[**@sermalefico**](https://github.com/sermalefico) commented on [Apr 23, 2019, 7:20 PM GMT+3](https://github.com/elementor/elementor/issues/7824#issuecomment-485874372 "2019-04-23T16:20:16Z - Replied by Github Reply Comments"):
> I'm on safari (Rev. 2–12-2018 BPC Safari). Everything works correctly when I'm editing in elementor in the backend (effects works but console warning errors). But in the frontend the effects are not reproduced and give errors.
> 
> extend jquery.js:86
> 
> `                    a = g[d], c = e[d], g !== c && (j && c && (n.isPlainObject(c) || (b = n.isArray(c))) ? (b ? (b = !1, f = a && n.isArray(a) ? a : []) : f = a && n.isPlainObject(a) ? a : {}, g[d] = n.extend(j, f, c)) : void 0 !== c && (g[d] = c));
> 
> `
> isPlainObject jQuery.js:116
> ` if (!a || "object" !== n.type(a) || a.nodeType || n.isWindow(a))    `


Can you please paste here your system info?

**Comment by shilo-ey** [comment]
@golokios 
I can see that you changed your page again, please recreate it in a different page so we could check it out.

Thanks

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor Pro v2.5.7

Feel free to update!

**Comment by shilo-ey** [comment]
Hi,

After investigating this issue, we found that it's originated in the WordPress jQuery native used version.

This bug [has been reported before](https://github.com/jquery/jquery/issues/3045) and has been fixed by the jQuery developers, but WordPress still uses this version natively.

Until WordPress will upgrade the jQuery version, you can dequeue the current one and enqueue a new one. [more details here](https://wordpress.stackexchange.com/questions/236466/deregister-wordpress-jquery-on-specific-page).

**Comment by joelnewcomer** [comment]
The easiest way to fix this issue is to install jQuery Updater: https://wordpress.org/plugins/jquery-updater/
