### ISSUE TITLE
Compatibility with WP Rocket 3.3 new feature for lazy loading background images

### ISSUE THREAD

**Issue by wordmagicsoft** [elementor/elementor#7825]
The latest version of WP Rocket 3.3 supports background image lazy loading, according to their documentation:

_WP Rocket will automatically LazyLoad background images that are found in the HTML of your page using this markup:

`<div style=”background-image: url(image.jpg)”>`

The element can have other attributes or classes, and it will still work. When LazyLoaded, the element will be transformed into:

`<div data-bg=”url(image.jpg)” class=”rocket-lazyload” style=””>`_

**Will this be compatible with Elementor?**

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xeonboy** [comment]
Following

**Comment by shilo-ey** [comment]
Hi @wordmagicsoft 

Elementor uses CSS file to load the background image and not inline, therefore this is not relevant for this feature.

Thanks.
