### ISSUE TITLE
Allow users to change colors of typing animation

### ISSUE THREAD

**Issue by qdl2020** [elementor/elementor#7826]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Why don't users have the option to change the background color of the typing animation? 

I've tried a number of approaches to hack the default CSS and nothing worked. As a result, I have searched in this Github community and via thorough Google search on how to change the background color of the typing animation (found in the Animated Headline widget), which is currently defaulted to black. 

The only relevant thread I came across was [this one](https://github.com/elementor/elementor/issues/5403). 

The kind fellow user's suggestion didn't work. So, I reached out to your team directly and was told by a rep: "I'm afraid there's no mechanism In Elementor to change that. I'm not sure if this would be possible with CSS, Elementor's support does not include developing custom code, if possible, I would recommend consulting with a developer."

Here's the thing: This goes against the philosophy of Elementor, doesn't it? Which is to enable users to develop and design WordPress sites with ease. Not to mention, this isn't exactly a difficult proposition, i.e. change the background color. 

Moreover, to suggest that one should consult with a developer, strictly for the purpose of getting advice on changing the background color... It did not take into consideration the context of the issue that was described to him. Moreover, it seems to smack against the user-oriented customer service approach that Elementor has adopted.

**Comment by Bexolo** [comment]
This workaround is OK to use, through custom CSS, until this issue is actioned: 

`.elementor-headline-animation-type-clip .elementor-headline-dynamic-wrapper:after 
{
    background-color: white;
}`

**Comment by Bexolo** [comment]
Works for me! 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/31006885/64925450-94c78900-d7e8-11e9-8332-4d21e96db81a.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/31006885/64925455-a446d200-d7e8-11e9-993f-0823c93beb36.png">

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!
