### ISSUE TITLE
When I swipe left or right on mobile my whole site moves.

### ISSUE THREAD

**Issue by bopedesign** [elementor/elementor#7828]
The page is https://jess.bopedesign.com/home-temp.  The same thing happens on iPhone and android.  When A visitor misses the photo slider and just swipes right/left somewhere the whole site slides sideways.  When I visit other sites like elementor.com this does not happen.  I'm wondering if anyone knows a fix.

I've tried OceanWP and WP Bootstrap 4 themes and they both have the issue.

Thx in advance.

**Comment by shilo-ey** [comment]
Hi @bopedesign 

You probably have an element that exceeds the responsive grid. 
Try finding it and set it to the proper position. (I'd start with absolute position elements).

If you can't manage to find it - contact our support for assistance.

Thanks.
