### ISSUE TITLE
Tags system

### ISSUE THREAD

**Issue by dazurit** [elementor/elementor#7830]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Tags are a powerful tool to use in a WordPress site, but nobody cares about them because you can't use them easily.

**Describe the solution you'd like**
Very simple from my vision, maybe it's really hard to backend this??>>
For example, you have x products or x type of content, let's say products for zodiac sign scorpion.
I will like to be able to create a main tag group like Zodiac signs and have in that tag group the zodiac signs, like Scorpio, Aries, etc.
And to be able to put in the site, like the tag cloud but only the tags from a specific group.
This will make the design automatic.
For example, a product has the ability to display the tags from x group ....not all the tags. 
I can't stress how much benefit will this bring to an e-commerce shop. 

**Describe alternatives you've considered**
Alternatives, again, using stone age tools in this century, and not an automatic process.
There is a plugin for this but another design, compatibility problems, etc....
Common guys, make this plugin the ultimate in web design!!!!!

**Additional context**
Hire me and I will make the builder TOP 1!!!!
My motto will be, "You need just WordPress and Elementor"
And that's how it will be!!!!!!!!

**Comment by dazurit** [comment]
I can't believe how somebody can have so much power (developer knowledge) and is not conquering this world...
Maybe knowledge without vision it's just playing in the sandbox...

**Comment by bainternet** [comment]
@dazurit 


Thanks for the suggestion, Well as you probably know, Elementor runs in WordPress and luckily WordPress comes with that built in!!! its called taxonomies.

here is some reference: https://codex.wordpress.org/Taxonomies

Thanks again and may the force be with you.

also check out: https://careers.elementor.com/explore/ in your pursuit to make the builder TOP 1!!!

**Comment by dazurit** [comment]
Perfect it is, thank you.
Sent from Yahoo Mail on Android 
 
  On Thu, Apr 18, 2019 at 15:37, Raz Ohad<notifications@github.com> wrote:   
Closed #7830.
