### ISSUE TITLE
🔗 🚀 Feature Request: [deleted] (Duplicate of #4440)

### ISSUE THREAD

**Issue by Elementalel** [elementor/elementor#7831]
[deleted]

**Comment by Elementalel** [comment]
Possible to get an answer please?

**Comment by Elementalel** [comment]
Can I get any kind of answer? It's been nearly over a month. Thank you.

**Comment by shilo-ey** [comment]
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
