### ISSUE TITLE
Elementor Pro + Toolset and shortcodes

### ISSUE THREAD

**Issue by nextend** [elementor/elementor#7832]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a Toolset field which contains a WYSIWYG editor. The data from this field displayed in Elementor. The problem happens when this field contains shortcode. Several HTML codes might be removed from it while displays through Elementor.

## Steps to reproduce
1. Create a simple shortcode which outputs HTML which contains not kses allowed content. (in style attribute, position is not allowed by kses)
```
add_shortcode('test', function(){
return '<div style="position:absolute">test</div>';
});
```
2. Create a Toolset field
3. Go to your post, place the [test] shortcode inside the Toolset field
4. Display the Toolset field in Elementor
5. The content of the shortcode will be stripped: <div>test</div>

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## What causes the problem
`ElementorPro\Modules\DynamicTags\Toolset\Tags\Toolset_Text`

Elementor renders the field with the Toolset function called `types_render_field`. With this function Toolset will apply `the_content` filter on the content of the field which use `do_shortcode`. Later on Elementor use `wp_kses_post` on the field value.

Probably Elementor should trust in value which Toolset returns and shouldn't call `wp_kses_post`. Also Toolset should use `wp_kses_post` when saves the user data (I haven't checked, so it might does).

**Comment by arielk** [comment]
Due to the fact that [Toolset stops releasing new features](https://toolset.com/2022/06/whats-next-for-toolset/), we are currently suspending all requests for integration with Toolset, if the status will change in the future we can reopen it.

Thanks for your feedback!
