### ISSUE TITLE
[Feature Request] Hide Button Text (with responsive options) + title attribute

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#7834]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This is a silly request (since it's easy to do this using CSS), but one that would improve in usability. 

It would be awesome if we could select to hide a button text if we just want an icon to show. Adding a full option to hide on specific devices would be perfect.

And while we're at it, adding a title attribute field (yes, I know we can add attributes to widgets, but not to the inner button widget link) would improve on SEO and Accessibility.

Its simple as that.

Thanks ;)

**Comment by shilo-ey** [comment]
Hi @zeinnicholas 

If you want a button with an icon, simply add a button without any title inside it, or select an icon widget and add a link.

As for title attribute: https://moz.com/community/q/does-the-link-title-attribute-benefit-seo-2 

thanks for the suggestions.

**Comment by zeinnicholas** [comment]
@shilo-ey Thanks for the reply.

It's a little too late and honestly I don't even know why I asked for this, so I'm sorry it took you from dealing with more pressing issues.

I think I was hoping to have a setting where I can specify if the button text would be visible on desktop but not on mobile (leaving only the icon for mobile) and other options like that. This is easily achieved by using custom CSS, which is what I've been using. So I think this has no widely needed implementation.

Thank you anyway for taking your time to answer my question!

Cheers!
