### ISSUE TITLE
Hover Option for Title widget

### ISSUE THREAD

**Issue by wacaszafar** [elementor/elementor#7835]
I am using Title Widget on few locations on my site and made it link to other pages. I want to enable hover options like text will change color on hover. Am I missing something or the feature is simply not available. If not I would like the same to be available soon.

**Comment by shilo-ey** [comment]
Hi @wacaszafar 

This feature is not supported, but you can achieve it by using custom CSS.

Simply add this to your Heading custom CSS:
```CSS
selector *:hover {
    color: red;
}
```

**Comment by dani88dani** [comment]
Quick workaround: Use a button, remove any borders, paddings and use the same background as where you want to apply the heading. Buttons have hover options :)

**Comment by JennyPower** [comment]
As a heading has the option of a link, shouldn't it therefore have a hover state without having to resort to custom css?

**Comment by pfdundar** [comment]
Is it tough work to add a hover option to the heading widget? "Use custom CSS" is doesn't make sense in principles of design. 
In the future, I should be able to change my hover color globally without writing extra CSS codes for every title.

**Comment by jfranger** [comment]
This is clearly a basic feature that should be available since we can add a link to the element, and it's a very popular element. There is no reason why we should find workarounds using custom CSS code for such a simple option in Elementor. DEVS, please make this happen, it should be considered as a bug with high priority IMO.

**Comment by ProvoRone** [comment]
Hi, checking in (after a year) to see if this issue have been fixed?
Change title color on hover still not possible.

**Comment by kanishkabodaragama** [comment]
Select the title, go advanced and then go to CSS at the bottom.
selector .elementor-heading-title:hover {
    color: #color_code;
}

**Comment by codewizard13** [comment]
I agree with @JennyPower and @jfranger that this is basic feature that should be included already. I'd love to know the logic behind not having this available yet.

**Comment by ayoubkhan558** [comment]
Now it's available in elementor.

![Image](https://github.com/user-attachments/assets/9a2e3590-e1c8-48e3-b0d7-1260cf20d096)
