### ISSUE TITLE
Reverse order in page nav widget

### ISSUE THREAD

**Issue by momo-fr** [elementor/elementor#7836]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I use the navigation widget on my pages with categories, I would like to reverse the order of navigation so that the pages suiaventes is right in the navigation. I note that the order of the adminsitration is not respected in the navigation.
How to make these changes via a function?
![initial-page-order-in-admin](https://user-images.githubusercontent.com/29410831/56027580-a0cd8d00-5d16-11e9-8d48-39fe957b969a.jpg)
![reverser-and-order-page-nav](https://user-images.githubusercontent.com/29410831/56027603-a7f49b00-5d16-11e9-87d8-dd7112abfe03.jpg)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@momo-fr 

The Post Navigation widget uses WordPress native `previous_post_link` and `next_post_link` functions to get the links. you can either play around with its filters and try to return something else or create a custom widget, extending this one and replacing the whole `render` to do whatever you want.

thanks.

**Comment by gbludesign** [comment]
The easiest with elementor post nav, if you are only using arrows, no 'next' or 'previous' labels, is CSS:

.elementor-post-navigation {
transform: rotate(180deg);
}

**Comment by JanineKall** [comment]
If you want labels as well, you can switch the labels 'previous' and 'next' (or whatever you want, of course) and than also add this CSS code:
.elementor-post-navigation {
transform: rotate(180deg);
}
.post-navigation__next--label {
transform: rotate(180deg);
}
.post-navigation__prev--label {
transform: rotate(180deg);
}
