### ISSUE TITLE
Columns not displaying properly in the builder preview when switched to 'tablet' mode

### ISSUE THREAD

**Issue by bastien-rom** [elementor/elementor#7838]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When the builder preview is switched to "tablet", columns are not displayed properly. It seems like it comes from the iframe around the preview, which has a width of 767.99px instead of 768px. (768px being the mobile breakpoint set in Elementor's Style settings.)
Things I tried to fix the problem :

- Uninstall and reinstall Elementor,
- Regenerate CSS in Elementor/Tools
- Deactivating all my plugins except Elementor

## Steps to reproduce
1. Open Elementor Editor
2. Switch builder preview to tablet mode.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.
## Environment

<details>
Wordpress : 5.1.1  Elementor: 2.5.13
<summary>System Info</summary>

Server Environment |--
-- | -- 
Operating System: | Linux 
Software: | Apache 
MySQL version: | MySQL Community Server (GPL) v5.6.33 
PHP Version: | 7.0.33
PHP Max Input Vars: | 1000  
PHP Max Post Size: | 300M 
GD Installed: | Yes   
ZIP Installed: | Yes  
Write Permissions: | All right 
Elementor Library: | Connected 

User |  --
-- | -- 
Role: | administrator 
WP Profile lang: | fr_FR 
User Agent: | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

</details>

**Comment by shilo-ey** [comment]
Hi @bastien-rom 

Thanks for reporting.

Unfortunately, we can't reproduce your issue.

Please try to find the specific scenario when it occurs and create a new issue report, or if you have Pro license - contact our support.

Thanks

**Comment by Lanxalot** [comment]
For anyone else with this problem, check the zoom settings on your browser. I had the exact same issue (Chrome), and my browser was zoomed to less than 100%. I reset it to 100% zoom, and all is fine. I found the fix on WordPress.org here: [https://wordpress.org/support/topic/elementor-is-broken-in-tablet-mode/#post-15780679]
