### ISSUE TITLE
inner section with 3 columns

### ISSUE THREAD

**Issue by progmastery** [elementor/elementor#7839]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It is impossible to create an inner section with three columns.

Section may contain up to six columns. However inner section may contain only up to two columns. Sometimes it is necessary to use inner section with three columns and it cannot be replaced by a section, e.g. when the parent section has a background image, heading element and inner section with three columns with widgets. It is common to see sections with three column content, such as image boxes, especially in landing pages. 

**Describe the solution you'd like**
Allow up to three inner columns inside inner section instead of two.

**Describe alternatives you've considered**
The alternative is to use normal section with 3 columns. But it fails if some other widgets (besides those in three columns) have common background with columns.

**Additional context**

**Comment by cavalierlife** [comment]
Right-click either of the two Column icons in the inner section and select Add Column. This will give you a 3rd column.

**Comment by progmastery** [comment]
yeah, it works
