### ISSUE TITLE
Template widget adds additional 10px padding

### ISSUE THREAD

**Issue by Helmi** [elementor/elementor#7841]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When templates are inserted using the template widget an addition 10px padding is inserted on the .elementor-element-populated div.

As no other widget adds this padding and it doesn't seem to be correctable through the settings on the widget or the column it should be removed.

## Steps to reproduce

Elementor Version 2.5.13
Elementor Pro Version: 2.5.5

- Create a template for some content without any paddings or margin around
- Insert the template via shortcode or template loading feature in the UI
- Insert it again using the template widget and see the addition 10px padding around the whole content.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

not environment specific

**Comment by shilo-ey** [comment]
Hi @Helmi 

I've tried to reproduce your issue.

I came across some mismatch between the shortcode version and the imported one based on the fact that the section containing the shortcode had columns gap:

![image](https://user-images.githubusercontent.com/45009641/56639621-c1cca100-6679-11e9-8d34-6540aab0dc78.png)


After I set it to `None` the dimensions are identical.

Moreover, using shortcodes to add your own created templates is a nice feature, but not the recommended way of use. 
By adding a template via shortcode it doesn't inherit the entire settings, and because of that, some inconsistencies might occur. e.g:
Full-width section with carousel and title -> saved as a template -> imported to a new doc (so far so good) -> added via shortcode - the width of the section will be different (boxed)

this is only one example of the changes that might occur.

Thanks.

**Comment by Helmi** [comment]
@shilo-ey I understand that it's not the recommended way, but is there any other way to have global sections? (not talking about widgets here).

Shortcodes are the only way, I guess.

**Comment by shilo-ey** [comment]
@Helmi 
For that matter, you can set a CSS class that "fixes" this behavior and add it wherever you wish in your site (send us an example and we can help with providing one if needed)

**Comment by tsz1412** [comment]
> @Helmi
> For that matter, you can set a CSS class that "fixes" this behavior and add it wherever you wish in your site (send us an example and we can help with providing one if needed)

I getting the same problem.
Which CSS class should I assign to the template? or should it be assigned to a wrapping element?

**Comment by cfytrok** [comment]
@shilo-ey
I getting the same problem. Please reopen this isue. 
You can not easy set CSS class that "fixes" this behaviour. Padding is related to widget wrapper and there is no way to distinguish template widget wrapper from other widget wrappers.

**Comment by awbnext** [comment]
Click edit section where you want to remove the extra padding then go to layout tab and set Columns Gap to "No Gap".

**Comment by nisiwi** [comment]
Did anybody manage to resolve this ?

I'm having the same problem when using a Template Widget.

There is a

padding: 10px !important;

set to the target below

.elementor-container .elementor-row > .elementor-column > .elementor-element-populated

Which I could only override with CSS using a parent ID and the same selector, again using !important, however this then prevents CSS cascading any further, so the contents of the widgets lose some of their styling.

How do we prevent the template widget from inheriting this padding to achieve a full width as it is in the original template?

Setting column gaps and padding on either the original section or the imported template makes no difference.

**Comment by nisiwi** [comment]
Oops realised this was coming from a piece of custom css.  Tracking it down to resolve.

**Comment by d-korolkov** [comment]
maybe a crutch, but 
`.elementor-element-populated:has(_your elementor class_) {padding-top:0 !important;}`
helped

**Comment by faisal1534** [comment]
> Click edit section where you want to remove the extra padding then go to layout tab and set Columns Gap to "No Gap".

Resolved by this. Thank you.
