### ISSUE TITLE
I have a 413 ERROR that Help desk couldn't resolve. 

### ISSUE THREAD

**Issue by jonorr1** [elementor/elementor#7842]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
I have been in contact with helpdesk and they couldn't resolve the issue and referred me here. 
I'm having a 413 Error when saving a large page. The error occurs on that page when duplicating a section. 

I have been in contact with my hosting provider and we have upped the PHP limits as directed by the helpdesk. 

## Steps to reproduce
On my page http://makemathmoments.com/academy 
Duplicating any section will cause the error. 

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release rel79.0, Revision 79.0 v5.6.32-78.0
	PHP Version: 7.2.15
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://makemathmoments.com
	Home URL: http://makemathmoments.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Divi
	Version: 3.18.9
	Author: Elegant Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.1
		Author: Automattic

	bbPress
		Version: 2.5.14
		Author: The bbPress Community

	Bloom
		Version: 1.3.4
		Author: Elegant Themes

	BuddyPress
		Version: 4.2.0
		Author: The BuddyPress Community

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Contact Widgets
		Version: 1.5.2
		Author: GoDaddy

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.5.13
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.5
		Author: Elementor.com

	GoDaddy Email Marketing
		Version: 1.3.0
		Author: GoDaddy

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Jetpack by WordPress.com
		Version: 7.2.1
		Author: Automattic

	Leadpages Connector
		Version: 2.1.6.21
		Author: Leadpages

	LifterLMS
		Version: 3.23.0
		Author: LifterLMS

	LifterLMS Labs
		Version: 1.5.0
		Author: Thomas Patrick Levy, codeBOX LLC

	Redirection
		Version: 4.2.1
		Author: John Godley

	Smart Podcast Player
		Version: 2.7.1
		Author: Smart Podcast Player

	SumoMe
		Version: 1.30
		Author: SumoMe

	WP101 Video Tutorials
		Version: 0.3
		Author: WP101Plugin.com

== Must-Use Plugins ==
	System Plugin
		Version: 3.9.3
		Author: 

== Log ==
	: 
JS: showing 4 of 4JS: 2019-03-22 16:36:59 [error X 1][http://makemathmoments.com/wp-admin/js/editor.min.js?ver=5.1.1:1:694] Cannot read property \'style\' of undefined 
JS: 2019-03-22 16:36:59 [error X 1][http://makemathmoments.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.9:2:214455] Cannot read property \'on\' of null 
JS: 2019-03-26 00:52:57 [error X 6][http://makemathmoments.com/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.9:736:35] self.attributes[control.name].each is not a function 
JS: 2019-03-31 17:23:16 [error X 1][http://makemathmoments.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5351\") has already been destroyed and cannot be used. 

Log: showing 20 of 312019-04-03 14:14:44 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-04-03 14:14:45 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-04-03 14:14:45 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-04-03 14:14:45 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-04-03 14:14:45 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-04-03 14:14:45 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-04-03 14:14:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.0-beta3',
  'to' => '2.5.3',
)]
2019-04-06 22:10:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-06 22:10:37 [info] elementor-pro::elementor_pro_updater Started 
2019-04-06 22:10:37 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-04-06 22:10:38 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-06 22:10:38 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-06 22:10:39 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-06 22:10:39 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-06 22:10:40 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-06 22:10:40 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-06 22:10:41 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-06 22:10:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-10 16:55:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.11',
  'to' => '2.5.13',
)]
2019-04-10 16:56:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.4',
  'to' => '2.5.5',
)]

PHP: showing 1 of 1PHP: 2019-04-06 22:10:06 [error X 1][/home/content/p3pnexwpnas13_data02/39/41781939/html/wp-content/plugins/elementor-pro/includes/modules-manager.php::58] Class 'ElementorPro\Modules\RoleManager\Module' not found [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.5.14

Feel free to update!
