### ISSUE TITLE
img map usemap and hash sign – 403 Err

### ISSUE THREAD

**Issue by 4bluedog** [elementor/elementor#7844]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I’m trying to use Elementor with multiple image maps. With one image map works perfect but when add a second or just duplicate it I’m getting 403 error when saving. I’ve tried to put the code into text or HTML section. 
Did some tests:
– removing # from `usemap="#A1"` or `usemap="#A2"` allows to save page like it would be one # sign allowed.
– changing one of href PDF file extension to something else allows to save page (with both # on)

## Steps to reproduce

Put below code into HTML or pure text section and try to save:
```
<img class="map" src="http://site.pl/wp-content/uploads/2019/04/A1.jpg" usemap="#A1" />
<map name="A1"> <area coords="865,488" shape="poly" href="http://site.pl/wp-content/uploads/2019/04/A1.0.1.pdf"/> </map>

<img class="map" src="http://site.pl/wp-content/uploads/2019/04/A2.jpg" usemap="#A2" />
<map name="A2"> <area coords="865,488" shape="poly" href="http://site.pl/wp-content/uploads/2019/04/A2.0.1.pdf" /> </map>
```
## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.0
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://apartamentynatura2.pl
	Home URL: http://apartamentynatura2.pl
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Debug Mode: Active

== Theme ==
	Name: Twenty Seventeen
	Version: 2.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.13
		Author: Elementor.com


== Log ==
	: 
Log: showing 3 of 32019-04-02 11:16:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.11',
)]
2019-04-09 10:53:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.11',
  'to' => '2.5.12',
)]
2019-04-10 16:33:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.12',
  'to' => '2.5.13',
)]

JS: showing 9 of 9JS: 2019-04-03 09:18:38 [error X 14][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.11:2:53459] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-04-05 07:09:38 [error X 1][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view12936\") has already been destroyed and cannot be used. 
JS: 2019-04-05 07:09:41 [error X 1][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13015\") has already been destroyed and cannot be used. 
JS: 2019-04-05 07:09:46 [error X 1][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13141\") has already been destroyed and cannot be used. 
JS: 2019-04-05 07:09:46 [error X 1][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view13059\") has already been destroyed and cannot be used. 
JS: 2019-04-05 11:33:54 [error X 18][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.11:2:180006] Cannot read property \'errors\' of undefined 
JS: 2019-04-10 15:20:58 [error X 2][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.13:2:83438] Cannot set property \'controls\' of undefined 
JS: 2019-04-12 14:10:23 [error X 7][http://apartamentynatura2.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.13:2:65784] Nieprawidłowy argument. 
JS: 2019-04-12 15:01:19 [error X 2][http://apartamentynatura2.pl/wp-admin/post.php?post=1240&action=elementor:1:48] jq(...).mapTrifecta is not a function 

PHP: showing 2 of 2PHP: 2019-04-04 10:47:15 [notice X 3][/home/prodlik/ftp/apartamentynatura2/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-10 17:57:53 [notice X 1][/home/prodlik/ftp/apartamentynatura2/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @4bluedog 

We cannot reproduce your issue,

Please try to:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

If it persists please contact our support.

Thanks.

**Comment by 4bluedog** [comment]
Hi @shilo-ey 

Already did it before posting this bug ticket to be sure it's not plugin/theme conflict. I've upgraded also PHP to the latest version. 
But I've just tried to reproduce issue on different server and WP site and there was no 403 error during save. What should I check next?

Thanks

**Comment by shilo-ey** [comment]
@4bluedog 

Seems like security issue with your server.

You need to check your server log file to see if there's any clue there.

Thanks

**Comment by 4bluedog** [comment]
@shilo-ey

As You suggested found some errors in logs like this;

[Sun Apr 14 10:25:50.818195 2019] [:error] [pid 22:tid 139723035363072] [client 83.10.24.59:50212] `[client 83.10.24.59] ModSecurity: Access denied with code 403 (phase 2). Pattern match "http://[a-zA-Z0-9._]{1,}?/.{0,}?\\\\.pdf\\\\b[^\\\\n\\\\r]{0,}#" at ARGS:actions. [file "/usr/share/waf/09_Global_Other.conf"] [line "21"] [id "211050"] [rev "1"] [msg "COMODO WAF: Universal PDF XSS URL Detected.||||2"] [severity "CRITICAL"] [tag "CWAF"] [tag "Other"] [hostname "apartamentynatura2.pl"] [uri "/wp-admin/admin-ajax.php"] [unique_id "XLLuji-rd8LEo8cW@BkbIQAAAAM"], referer: http://apartamentynatura2.pl/wp-admin/post.php?post=1240&action=elementor`

Thanks

**Comment by 4bluedog** [comment]
@shilo-ey

I've disabled Comodo WAF on server cPanel and no more 403 errors during saving. I wish to disable only this false positive rule rather than completely disable WAF. Try to ask for it my server provider.

Thank You very much for clues :)

**Comment by 4bluedog** [comment]
@shilo-ey

Just got response from server provider nazwa.pl: they won't disable this rule because my web page is created with use of cms outside of nazwa.pl and disabling it could lead to other errors in functioning of services. They advised to contact with the support of the plugin. Well, it makes sense because in Elementor can't save combination of hash sign in `usemap="#A1"` and PDF hyperlinks files extension. This can be done in default WP editor with no problem. 
I can't disable WAF and re-enable it after saving because this page will be edited many times by the end user during time. I wanted to use Elementator's capabilities but in this case can't.
If You can't give me any other advice then finally I would like to change the topic of this ticket so that it would better suit the problem presented, make it more readable to other users.

Thanks
