### ISSUE TITLE
Custom Elementor Query Does not work in 2.5

### ISSUE THREAD

**Issue by bfrye26** [elementor/elementor#7845]
We are having major issues with version 2.5. It seems when we upgrade, all the widgets with the custom query simply do not show anything.

The query is here:
```PHP
// Showing multiple post types in Posts Widget
add_action( 'elementor_pro/posts/query/review_filter', function( $query ) {
// Here we set the query to fetch posts with
// post type of 'custom-post-type1' and 'custom-post-type2'
$query->set( 'post_type', [ 'post', 'reviews' ] );
} );
```
Please find my system info:

To replicate it, install Elimentor Pro 2.5.+

and use query in the post block:

"review_filter"
[system-info-www.cgmagonline.com-12-04-2019.txt](https://github.com/elementor/elementor/files/3074147/system-info-www.cgmagonline.com-12-04-2019.txt)

**Comment by shilo-ey** [comment]
You are missing another parameter (`$widget`).
Try changing your query to:

```PHP
/**
 * @param \WP_Query $query
 * @param \Elementor\Widget_Base $widget
 */
function your_custom_query( $query, $widget ) {
    $query->set( 'post_type', [ 'post', 'reviews' ] );
}

add_action( 'elementor_pro/posts/query/review_filter', 'your_custom_query', 10, 2 );
```

**Comment by alexandramclarty** [comment]
This is actually really confusing to troubleshoot. The [documentation here](https://developers.elementor.com/custom-query-filter/) could be a lot more explicit.

The example doesn't differentiate between elementor_pro/ and elementor/, nor does it include $widget. I got lucky in finding this thread to troubleshoot my issue. Updating your documentation would help users like me in the future.
