### ISSUE TITLE
Accessing $settings object outside of a widget render() function

### ISSUE THREAD

**Issue by joeczucha** [elementor/elementor#7850]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I've been referred here by Elementor Technical Support 

I've written a custom plugin to provide a Pricing page widget in Elementor and it works great.

But I now need to create an API end point which will return the pricing details (so that it can link into our commerce system). I'm comfortable with writing the end point, that side of stuff all works great. But I just need a way to access the raw data that has been entered into the widget.

When I am rendering the widget output, I can use:

    $settings = $this->get_settings_for_display();
    $property = $settings['property'];

However, I was wondering if there is a way to access the widget data outside of this function.

So, if I know my pricing page ID is `3534` and I know that it has a widget on there called `widget-pricing-table`, is there a way that I can retrieve the `$settings` object, and subsequently `$settings['property']` for that widget, so that I can do things with the values?

I have found:

    echo \Elementor\Plugin::$instance->frontend->get_builder_content( 3534 );

But that seems to output the entire HTML rather than just retrieving an array of the data.

Thanks in advance.

**Comment by bainternet** [comment]
@joeczucha 

Elementor saves its data in the postmeta database table under `_elementor_data` meta key.


so you can get that from there.
