### ISSUE TITLE
Menu Cart Widget - Add Text Field to Widget & Format Number of Items

### ISSUE THREAD

**Issue by estevez96** [elementor/elementor#7854]
Hello. I am writing to recommend the following updates to the Menu Cart Widget:

1. Ability to add text to the Left or Right of the Cart icon //OR// a feature to add the word "Cart" to the left or right of the icon

2. Ability to further format the "number of items" inside a cart beyond only the red badge

**Comment by shilo-ey** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it.

If you, however, decide to write a patch for it, we'll gladly include it after some code review.

Thanks for the feedback.
