### ISSUE TITLE
Adding option for different text formatting (style, font, size) for different language translations with WPML plugin!

### ISSUE THREAD

**Issue by acornavi** [elementor/elementor#7855]
Please add an option to format text (style, size, font, etc) differently for different language translations with WPML plugin.

You can add options for the current languages in the style formatting menu for every text element.

Thank you,
Ivan Roca

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for your actual request, Elementor is not aware of the languages defined in WPML, its all done by and via WPML.

Thanks.
