### ISSUE TITLE
Line Over Text

### ISSUE THREAD

**Issue by kendranix** [elementor/elementor#7856]
Hello,

After I edit my text box, there is always a line that appears over the text. The 2019 theme from Wordpress is still active but its not being used since building with Elementor. Any help with this will be appreciated.
<img width="1440" alt="Screen Shot 2019-04-12 at 1 42 06 PM" src="https://user-images.githubusercontent.com/49593572/56082495-0422f200-5ddf-11e9-86ae-df89d3a848ac.png">

**Comment by shilo-ey** [comment]
Hi @kendranix 

This is caused by your theme's CSS,
I can assume you are using TwentyNineteen theme, which causes this behavior.

Switch your theme or use [this workaround](https://wordpress.org/support/topic/removing-short-line-above-headings-in-twenty-nineteen/) 

Thanks
