### ISSUE TITLE
I am using 4 addon packs, activating any more than that causes an infinite spinning wheel in the element side panel, making the editor unusable.

### ISSUE THREAD

**Issue by sajox5** [elementor/elementor#7857]
Elementor plugins activated:

Elementor,

Elementor pro,

Element pack,

Elementor extras

Essential addons

Ultimate addons

Steps to reproduce:

Activating any additional plugin which contains an addon pack to the ones listed breaks the sidebar. Plugin packs i have individually tried to activate in addition to the 4 above that are activated are: Element Plus, Jet Blocks, JetMenu, Premium Addons, Elements Plus!. Once activated, in addition to the 4 listed, so 5 addon packs total activated total. (extras, essential, ultimate, element pack) + one of(element plus, jetblocks, jetmenu, premium addons or elements plus!). 

I disabled each additional pack once the panel crashed to move on to the next to test. I have tried various combinations of activated Element pack addons.

From what i can discern is happening, it seems Elementor may currently have some sort of bug which has a maximum number of elements which can be active in the sidebar before the editor crashes. I believe this bug is unspecific to the activated addon packs and is crashing the sidebar due to Elementor not being able to handle that many elements in the sidebar. Varying the combinations of addons seems to have no effect, but once it hits a certain count of elements on the sidebar is what seems to prevoke the crash.

**Comment by bainternet** [comment]
@sajox5 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for the issue you are describing, I can only guess that your server is running out of memory the more elements you have installed.

Thanks.

**Comment by sajox5** [comment]
@bainternet 

If it is a memory issue, would changing the memory values in the PHP settings potentially fix the issue?
