### ISSUE TITLE
Ability to completely disable theme to improve performance when using theme builder

### ISSUE THREAD

**Issue by sajox5** [elementor/elementor#7858]
Request: 

Allow the ability to completely disable the currently selected theme when using the Elementor editor. While using Elementor, at least how i understand how the editor currently functions, the theme's code is still loaded in the background, even when Elementor overrides the themes options such as header/footer. 

Disabling the theme's code completely would speed up the loading times of the editor and website, so i was wondering if this is possible to implement. I was unable to locate a thread asking for this specifically. Thanks.

**Comment by shilo-ey** [comment]
Hi @sajox5 

When using "Safe Mode", all of your plugins and theme are disabled while using the editor.

We do not recommend using this as a default way of work, because it might cause some inconsistencies and differences between the editing preview and the frontend view.

Thanks.

**Comment by sajox5** [comment]
@shilo-ey 

I was talking in a general sense. I would want to disable the theme site wide at all times. As i mentioned, the intention is to improve performance by not loading the themes code at all, at any time.
