### ISSUE TITLE
Elementor Header / Footer as Regular HTML Header / Footer Element

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#7859]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Current implementation inserts header/footer as regular div, wouldn't it be better to insert it as a header/footer HTML element? I know I can select these HTML elements for the section inside Elementor's header/footer, but sometimes it's not the right way, e.g., when there are several sections.

It would be nice to have the schema.org implemented for these sections as well.

**Describe the solution you'd like**
See the problem description.

**Describe alternatives you've considered**
See the problem description.

**Comment by bainternet** [comment]
Hi @black-eye

Thanks for your feedback.
The header & footer templates parts can be embedded everywhere in the site, therefore, we don’t enforce `header` and `footer` tags in those documents.

However, you do have a few options:

You can extend the documents yourself and add the wrapping semantic tags ex:

```PHP
// Semantic Header template type
add_action( 'elementor/documents/register', function( $document_manager ) {
	class Semantic_Header extends \ElementorPro\Modules\ThemeBuilder\Documents\Header {
		public function get_name() {
			return 'semantic-header';
		}

		public static function get_title() {
			return __( 'Semantic Header', 'text-domain' );
		}

		public function print_content() {
			echo '<header>';
			echo parent::print_content();
			echo '</header>';
		}
	}
	$document_manager->register_document_type( 'semantic-header', 'Semantic_Header' );
}, 50, 1 );

// Semantic Footer template type
add_action( 'elementor/documents/register', function( $document_manager ) {
	class Semantic_Footer extends \ElementorPro\Modules\ThemeBuilder\Documents\Footer {
		public function get_name() {
			return 'semantic-footer';
		}

		public static function get_title() {
			return __( 'Semantic Footer', 'text-domain' );
		}

		public function print_content() {
			echo '<footer>';
			echo parent::print_content();
			echo '</footer>';
		}
	}
	$document_manager->register_document_type( 'semantic-footer', 'Semantic_Footer' );
}, 50, 1 );
```
![ngVz9yJ](https://user-images.githubusercontent.com/660572/56367344-ba327580-61fd-11e9-8712-f69630458182.png)


As for schema.org attribute, either add them to the wrapper or use [custom attributes](https://docs.elementor.com/article/445-custom-attributes).

thanks.
