### ISSUE TITLE
sticky columns

### ISSUE THREAD

**Issue by zrk4444** [elementor/elementor#7861]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm currently making a membership dashboard and ran into the problem of not being able to make sticky columns.

Example, I have a 3 column layout, nav menu on the left-hand side, page content in middle, and other stuff like a buy button and more details about the course on the right-hand side.

When I scroll down, the nav menu and right side column buy button disappear and you're left with an ugly looking, empty layout.

**Describe the solution you'd like**
Ability to add sticky columns similar to how you can add sticky sections etc.

**Comment by shilo-ey** [comment]
Hi @zrk4444 

We are not allowing this option to be enabled in column options.

Alternatively, you can use inner section to achieve this behavior.

Thanks.
