### ISSUE TITLE
Toggle Popup not working

### ISSUE THREAD

**Issue by JoeHana** [elementor/elementor#7862]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Popups can be triggered by various kind of actions - among them there is the manual trigger by clicking on a button for example - like Open, Close or Toggle. While Open and Close work as expected, the Toggle action doesn't seem to work properly but works exactly the same as open: Clicking on it a second time it will open the popup again instead of closing it.

## Steps to reproduce

1. Create empty page
2. Add Button
3. Choose dynamic link option and attach any popup to it
4. Select "Toggle"
5. Test the result

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @JoeHana 

Thanks for your feedback.

Unfortunately, we cannot reproduce your issue.

If this issue persists, please contact our support for better debugging.

**Comment by JuanMTech** [comment]
I'm having the same issue. The toggle option works the same as Open.

**Comment by JoeHana** [comment]
@JuanMTech According to support, this is the only way to make it work propery:

> 

To make toggle function work perfectly, closing on overlay must be  disabled.Make sure you choose 'Prevent Closing on Overlay' in advance popup  settings like this - https://prnt.sc/nc07y4. | To make toggle function work perfectly, closing on overlay must be  disabled.Make sure you choose 'Prevent Closing on Overlay' in advance popup  settings like this - https://prnt.sc/nc07y4. | To make toggle function work perfectly, closing on overlay must be  disabled.Make sure you choose 'Prevent Closing on Overlay' in advance popup  settings like this - https://prnt.sc/nc07y4.
-- | -- | --
To make toggle function work perfectly, closing on overlay must be  disabled.Make sure you choose 'Prevent Closing on Overlay' in advance popup  settings like this - https://prnt.sc/nc07y4. | To make toggle function work perfectly, closing on overlay must be  disabled.Make sure you choose 'Prevent Closing on Overlay' in advance popup  settings like this - https://prnt.sc/nc07y4.
To make toggle function work perfectly, closing on overlay must be  disabled.Make sure you choose 'Prevent Closing on Overlay' in advance popup  settings like this - https://prnt.sc/nc07y4.

>

**Comment by JuanMTech** [comment]
Didn't think about that. That did the trick. Thank you for sharing.

**Comment by scott8035** [comment]
Hi @shilo-ey and crew. This issue still persists for me. I'm using Elementor 2.5.15 and Pro 2.5.8. I turned on 'Prevent Closing on Overlay' as suggested above with no change in result. You can see the issue in action at https://thefeed.blog by clicking the "Who We Are" selection in the blue navbar.

**Comment by shilo-ey** [comment]
[**@scott8035**](https://github.com/scott8035) commented on [May 15, 2019, 4:57 PM GMT+3](https://github.com/elementor/elementor/issues/7862#issuecomment-492665798 "2019-05-15T13:57:11Z - Replied by Github Reply Comments"):
> Hi @shilo-ey and crew. This issue still persists for me. I'm using Elementor 2.5.15 and Pro 2.5.8. I turned on 'Prevent Closing on Overlay' as suggested above with no change in result. You can see the issue in action at https://thefeed.blog by clicking the "Who We Are" selection in the blue navbar.

Your site is under maintenance.

If the issue persists, please create a new issue with an example provided.

Thanks

**Comment by brianwoodlief** [comment]
I found the answer that helped me on another blog. You need to remove the entrance/exit animation on tablet and mobile. ONLY apply entrance animation on desktop view.
