### ISSUE TITLE
Enable the ability to collapse an Inner Region

### ISSUE THREAD

**Issue by kdawg1406** [elementor/elementor#7863]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using the Inner Section Feature, layouts can get complex and very busy.  It would be much easier to use the product if we could collapse Inner Regions, especially when they are stacked vertically.

**Describe the solution you'd like**
A design-time right-click action on Inner Region Section to collapse it in the UI until restored.

**Describe alternatives you've considered**
Deal with the busy screen.

**Additional context**
None

**Comment by zeinnicholas** [comment]
If it's only on the Editor area, this is already an option (although a little different). Fire up the navigator, go to the desired Inner Section and click on the eye icon that appears when you hover over. This will hide any element inside the editor.

For more information follow this link: https://docs.elementor.com/article/378-navigator

**Comment by kdawg1406** [comment]
Thank you for the explanation.  Outstanding!!!  Thank you!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.0

Feel free to update

Thanks!
