### ISSUE TITLE
Form shortcode

### ISSUE THREAD

**Issue by daw8706** [elementor/elementor#7865]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
On pages where Toggle, Tab or Accordion elements are used, a form can not be inserted inside the element. 

**Describe the solution you'd like**
I would like to be able to have a contact page with three different tabs or toggles for different users. Each user would select the tab/toggle that relates to them, and then a different form would be displayed. This would best be achieved with the use of a form shortcode; each form with a different shortcode ID. This feature would also allow me to insert an Elementor Form into a WooCommerce product page, even when I'm not building the product page using Elementor but rather with the standard template file.

**Describe alternatives you've considered**
I am currently using WP Forms Lite to achieve this, but would prefer to use fewer plugins. Plus, Elementor's form builder is far more powerful

**Additional context**
None

**Comment by bainternet** [comment]
@daw8706 

This is already possible, 
Save the form as in a section as section template and you can use the shortcode to insert it.

thanks.

**Comment by daw8706** [comment]
I contacted Elementor and they told me it wasn't possible.

Your answer solved my problem. Thank you!
