### ISSUE TITLE
Add Heading and Link Styling Options to Text Editor

### ISSUE THREAD

**Issue by edcoyne** [elementor/elementor#7866]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There are many options for styling text, in the text editor widget, but no options for styling links or headings (of the included text). One would be able to enter a block of text, including headings and links, and then be able to style them.

**Describe the solution you'd like**
A section in the Text Editor "Style" tab, that includes options for headings and links.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
