### ISSUE TITLE
Global breakpoint error in all versions of Elementor

### ISSUE THREAD

**Issue by STARTERO** [elementor/elementor#7869]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

There is a problem in elementor and elementor pro, if you choose 768px breakpoints or some other thing on the previous pixel for example 767px there will be an error of all elements (all elements that are hidden in the editor will be visible, as well as all elements of the blocks go to the left, and the sticky header does not work etc)

  We are waiting for an early resolution of the problem.

## Steps to reproduce

An example is your website https://elementor.com/, put a resolution of 767 px (where you look at the code) in Google Chrome and you will see errors on your screen that I have described. Same with all sites written in Elementor. 
Example:
https://files.fm/f/w4qfkv99

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
Operating System: Linux Debian
Software: Apache2
MySQL version: Percona Server (GPL), Release rel78.0, Revision 78.0 v5.6
PHP Version: 7.0
PHP Max Input Vars: 10000
PHP Max Post Size: 1000M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

</details>

**Comment by shilo-ey** [comment]
Hi @STARTERO 

Thanks for your feedback.
It looks like the issue is local, hence we could not reproduce it on our side in several computers and environments.
![image](https://user-images.githubusercontent.com/45009641/56360365-180a9180-61ed-11e9-8aea-60f427269e6f.png)

Thanks

**Comment by chandupalasith** [comment]
How did you resolve that issue? @STARTERO

**Comment by mjmadani** [comment]
> Hi @STARTERO
> 
> Thanks for your feedback. It looks like the issue is local, hence we could not reproduce it on our side in several computers and environments. ![image](https://user-images.githubusercontent.com/45009641/56360365-180a9180-61ed-11e9-8aea-60f427269e6f.png)
> 
> Thanks

**Greetings. However, the issue at hand is not confined to a specific location. It seems to be a widespread occurrence. Take a moment to observe the Get Started button when the screen size is 767 pixels:**


<img width="631" alt="Screenshot 2023-11-05 131023" src="https://github.com/elementor/elementor/assets/103977686/ba5785dd-7638-4704-b089-ecedebb7d6f1">
<img width="633" alt="Screenshot 2023-11-05 131009" src="https://github.com/elementor/elementor/assets/103977686/29332f6c-62c9-48d4-87dc-e1ec903f9d82">
<img width="607" alt="Screenshot 2023-11-05 130953" src="https://github.com/elementor/elementor/assets/103977686/2cff48e2-54b2-420a-a07a-85f6ea201a1e">
