### ISSUE TITLE
Responsive selector desktop/pad/mobile for Lightbox toggle

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#7873]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Lightboxes are most useful on desktop devices where the screen is most likely much larger than the image. When on a mobile or pad device you zoom in with your fingers directly in the image; clicking it up in a Lightbox on a mobile device often doesn't make it bigger since the Lightbox adds paddings and whatnot . 

**Describe the solution you'd like**
Thus I would like to be able to disable lightbox on pad and mobile devices for an image. Have the regular 1-2-3 (desktop / pad / mobile) selector for the Lightbox [standard / yes / no ].

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
