### ISSUE TITLE
Video in popup continues playing in background after closing

### ISSUE THREAD

**Issue by HannesDesignplus** [elementor/elementor#7875]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Using Elementor Pro, i placed a popup on a page (http://uniqueisland.org/unique-island-event/), that contains a video. If you close the popup while the video is still playing, it continues playing in the background so does the music. The video/music should stop playing when closing the popup. I have no javascript knowledge, so it would be nice, if somebody could help me with that.

Thanks in advance.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Debian) v5.5.60
	PHP Version: 5.6.40
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://uniqueisland.org
	Home URL: http://uniqueisland.org
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: -1
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.7.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==
	Astra Starter Sites – Elementor, Beaver Builder & Gutenberg Templates
		Version: 1.2.15
		Author: Brainstorm Force

	Astra Widgets
		Version: 1.1.0
		Author: Brainstorm Force

	Custom Fonts
		Version: 1.0.7
		Author: Brainstorm Force

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 2.10.0
		Author: WPDeveloper

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	Make Column Clickable Elementor
		Version: 1.2.0
		Author: Fernando Acosta

	MouseWheel Smooth Scroll
		Version: 5.1
		Author: KubiQ

	Ocean Extra
		Version: 1.5.3
		Author: OceanWP

	Page Links To
		Version: 3.0.1
		Author: Mark Jaquith

	Preloader Plus
		Version: 1.1.1
		Author: Massimo Sanfelice | Maxsdesign

	Premium Addons for Elementor
		Version: 3.2.1
		Author: Leap13

	Redirection
		Version: 4.1.1
		Author: John Godley

	Typing Effect
		Version: 1.5
		Author: 93digital

	Ultimate Addons for Gutenberg
		Version: 1.12.4
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.16.10
		Author: UpdraftPlus.Com, DavidAnderson

	Use Any Font
		Version: 5.1
		Author: Dinesh Karki

	WP Fastest Cache
		Version: 0.8.9.2
		Author: Emre Vona

	WPForms Lite
		Version: 1.5.1.3
		Author: WPForms

	Yoast SEO
		Version: 10.0.1
		Author: Team Yoast

== Log ==
	: 
JS: showing 20 of 38JS: 2019-04-02 09:54:26 [error X 1][http://uniqueisland.org/wp-admin/js/editor.min.js?ver=5.1.1:1:694] Cannot read property \'style\' of undefined 
JS: 2019-04-02 09:54:27 [error X 1][http://uniqueisland.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.10:2:214612] Cannot read property \'on\' of null 
JS: 2019-04-04 11:58:35 [error X 2][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1528\") has already been destroyed and cannot be used. 
JS: 2019-04-08 08:55:57 [error X 6][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1602\") has already been destroyed and cannot be used. 
JS: 2019-04-08 09:42:55 [error X 1][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4876\") has already been destroyed and cannot be used. 
JS: 2019-04-10 08:33:42 [error X 7][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1498\") has already been destroyed and cannot be used. 
JS: 2019-04-10 12:31:26 [error X 1][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view10228\") has already been destroyed and cannot be used. 
JS: 2019-04-10 12:31:52 [error X 1][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view10387\") has already been destroyed and cannot be used. 
JS: 2019-04-11 07:36:34 [error X 1][http://uniqueisland.org/wp-admin/post.php?post=1305&action=elementor:2:5] Invalid or unexpected token 
JS: 2019-04-11 07:38:33 [error X 4][http://uniqueisland.org/wp-admin/post.php?post=1305&action=elementor:1:8] Unexpected token ) 
JS: 2019-04-11 08:14:27 [error X 6][http://uniqueisland.org/wp-admin/post.php?post=1305&action=elementor:5:19] WTCGL is not defined 
JS: 2019-04-11 08:59:38 [error X 1][http://uniqueisland.org/wp-admin/post.php?post=6&action=elementor:11:15] SimplexNoise is not defined 
JS: 2019-04-11 09:21:42 [error X 1][http://uniqueisland.org/wp-admin/post.php?post=6&action=elementor:3:17] chroma is not defined 
JS: 2019-04-11 09:47:14 [error X 94][http://uniqueisland.org/wp-admin/post.php?post=1305&action=elementor:156:11] dat is not defined 
JS: 2019-04-11 12:33:13 [error X 5][http://uniqueisland.org/wp-admin/post.php?post=1305&action=elementor:14:12] THREE is not defined 
JS: 2019-04-11 12:34:29 [error X 60][http://uniqueisland.org/wp-admin/post.php?post=1305&action=elementor:97:16] CCapture is not defined 
JS: 2019-04-11 13:54:29 [error X 1][http://uniqueisland.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.10:2:122124] n is undefined 
JS: 2019-04-11 14:16:04 [error X 1][http://uniqueisland.org/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.5.10:2:0]  
JS: 2019-04-11 14:39:16 [error X 2][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1611\") has already been destroyed and cannot be used. 
JS: 2019-04-11 14:42:46 [error X 2][http://uniqueisland.org/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1770\") has already been destroyed and cannot be used. 

Log: showing 1 of 12019-03-27 15:22:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]

PHP: showing 3 of 3PHP: 2019-03-27 17:32:21 [notice X 1][/homepages/18/d71418163/htdocs/ui/wp-content/plugins/elementor/includes/template-library/sources/local.php::676] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-04 10:50:09 [notice X 14][/homepages/18/d71418163/htdocs/ui/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-10 11:06:20 [notice X 1][/homepages/18/d71418163/htdocs/ui/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by kreasIT** [comment]
The same thing happens to me too

**Comment by lajolladesigngroup** [comment]
Having the same issue. Does anyone have a workaround for this?

**Comment by garciacrew** [comment]
me too.  perhaps in the ajax load option when it is closed it can destroy the contents and in doing so the video would stop playing.

**Comment by pixelxcode** [comment]
Same issue here, doesn't matter which video element i use. Have tried with elementor's video element and elementor extras video element. Both have the same issue.

**Comment by Mactidji** [comment]
This is what the support has to say: 
-------------------------------------------------

Thanks for contacting us.

At this time the popup builder does not have that functionality. In the meantime, please feel free to use a third party plugin to achieve this. We cannot recommend a specific plugin as we cannot guarantee compatibility with Elementor, however, I would advise you to join our Facebook community (https://www.facebook.com/groups/Elementors/) and check with our users which solutions have worked best for them.

Unfortunately, custom code is beyond the scope of our support. Development issues are handled only in our GitHub project.

I hope that this answers your question. If this is not the case, do not hesitate to contact us again.

Kind Regards, 
------------------------------------------

**Comment by pixelxcode** [comment]
> At this time the popup builder does not have that functionality. In the meantime, please feel free to use a third party plugin to achieve this. We cannot recommend a specific plugin as we cannot guarantee compatibility with Elementor, however, I would advise you to join our Facebook community (https://www.facebook.com/groups/Elementors/) and check with our users which solutions have worked best for them.
> 
> Unfortunately, custom code is beyond the scope of our support. Development issues are handled only in our GitHub project.

Wow. So they're saying we can't put videos in the pop up? This is not good at all, as I think it's a very  common use-case! The thing is we don't want to use a third party plugin when elementor already has a pop up function built-in.

**Comment by kreasIT** [comment]
My workaround is to use a Video widget. In its, in the Overlay image panel, I use an image as icon. The image should be for example a youtube play icon or a text, or whatever. I deactivate the "play icon" function and activate the  "Lightbox" function so to open the video in a "popup" windows.
To be able to resize the image as I want, in the advanced tab I set the "custom positioning" to the width I need.
Sorry if in my screenshot labels are italian, but I hope they can still be useful!
![Schermata 2019-04-29 alle 17 27 15](https://user-images.githubusercontent.com/47925728/56907215-11f59a00-6aa4-11e9-91cb-17e056a195a0.png)
![Schermata 2019-04-29 alle 17 30 29](https://user-images.githubusercontent.com/47925728/56907439-87616a80-6aa4-11e9-902e-64b6edfaa5dc.png)

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor Pro v2.5.7

Feel free to update!

**Comment by Berkman-weptile** [comment]
I'm using v2.7.2 but the same problem still exists
