### ISSUE TITLE
Better ActiveCampaign integration

### ISSUE THREAD

**Issue by wpmarmite** [elementor/elementor#7877]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Right now, the ActiveCampaign integration let's us :
- subscribe a contact to a list
- map fields
- add tags

But we can't subscribe a contact to an ActiveCampaign form (and enable double optin).

**Describe the solution you'd like**
Add a dropdown with forms available to the ActiveCampaign panel will be awesome !

**Comment by bainternet** [comment]
@wpmarmite 

You can already set the form (which can be defined to [enable double opt-in via ActiveCampaign](https://help.activecampaign.com/hc/en-us/articles/115000839230-How-do-I-enable-double-opt-in-confirmation-)).

Simply set the ActiveCampaign form id as the Elementor Form id in the "Additional Setting" section.

![Screen Shot 2019-04-18 at 12 28 28](https://user-images.githubusercontent.com/660572/56351331-8c393b00-61d5-11e9-9444-67191a865f34.png)


thanks.

**Comment by theDanielJLewis** [comment]
I, too, would like to see better integration with ActiveCampaign and other email service providers. Elementor doesn't handle multi-choice fields properly, and allowing (or actually defaulting to) double opt-in is an absolutely must with all the spam and privacy laws.

**Comment by FuturiaMarketing** [comment]
We also have ALWAYS problems with the form integration.
Contacts do go into AC, but tags, lists and other info are never passed along.
This is a complete dealbreaker. The only solution we could find so far it's been to use tools such as zapier, but it's not convenient nor fast.
