### ISSUE TITLE
Remove "Elementor" Branding from HTML

### ISSUE THREAD

**Issue by zdesigner1** [elementor/elementor#7880]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be great to hide the fact that we're using Elementor, this would mean removing Elementor branding from html. This includes a lot of div tags and a few wordpress URLs the mention wordpress/plugins/elementor. I find it valuable to be able to hide this to make the site seem more legitimate.

**Describe the solution you'd like**
Hide all Elementor branding, urls, and mentions from the html. 

**Describe alternatives you've considered**
A solution would be to change the name of the div tags to something that's not branded and URLs that don't mention the plugin.

**Comment by m2sahin** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @zdesigner1 
Thank you for your suggestion.

This is not branding but the way elementor classes and ID's work.

We simply cannot alter this way of use, for it will break the entire selectors system.

Thanks

**Comment by steinmacher** [comment]
It should not be that difficult to rename the selector. Would be awesome if Elementor lets customers choose variable selector names instead of "elementor" and "e".

**Comment by magnetoid** [comment]
It can be done at the end of the final HTML print..
