### ISSUE TITLE
Fatal error: Cannot declare class Elementor\Element_Column

### ISSUE THREAD

**Issue by mackelito** [elementor/elementor#7882]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

Installed the plugin using the wordpress admin (just searched for elementor and installed it) not the site just shows an error:

Fatal error: Cannot declare class Elementor\Element_Column, because the name is already in use in /customers/3/d/8/www/httpd.www/wp-content/plugins/elementor/includes/elements/column.php on line 1116

## Steps to reproduce
Just installed the plugin

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment
Can't reach system info thru admin now but it runs on:
```
nginx/1.14.0
PHP 7.2.15-0ubuntu0.18.04.1
MariaDB 10.3.10
```

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by mackelito** [comment]
Update: I have tried the following versions with same result: 

elementor.2.5.13
elementor.2.5.12
elementor.2.5.0

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **are not for support!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by mackelito** [comment]
@shilo-ey could you please explain what's missing for this to qualify as a bug?
I'm a dev my self and was kind of surprised to see this closed like this :/

**Comment by reyo** [comment]
> @shilo-ey could you please explain what's missing for this to qualify as a bug?
> I'm a dev my self and was kind of surprised to see this closed like this :/

This is a legit bug.

**Comment by mackelito** [comment]
hmmm.. making me think twice about going pro ;)

**Comment by QTRichieRich** [comment]
I have the exact same issue... I am pretty sure this is a bug.

**Comment by brownemint** [comment]
Any solutions to this? Happening to me when I fully deactivate Ninja Forms on a site.

**Comment by cehojac** [comment]
hey! there in 2023. in some plugins when activate send this bug. 

content/plugins/elementor/includes/elements/column.php. Error message: Cannot declare class Elementor\Element_Column, because the name is already in use

this class is not redeclare in plugins

but some plugins have composer.json or vendor folder.

**Comment by aguisoft** [comment]
Hello, i have the same problem when one plugin is activated, some solution?

**Comment by aguisoft** [comment]
I resolve it, updating php from  7.4 to 8.0
