### ISSUE TITLE
[BUG] Sticky element stop point stops working when resizing window

### ISSUE THREAD

**Issue by sylphid3** [elementor/elementor#7884]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have created a sticky sidebar with Elementor Pro in a 2 column section.
I have set the sidebar widget to sticky + stay in column. It works fine when you see the page in action, but when you resize the page **below the stop point**, the widget comes out of the column and the stop point doesn't work anymore.

Bug in action here : https://youtu.be/4zgkzlbRGmo

## Steps to reproduce

- Create a 2 column section.
- Add content to first column + sidebar widget to second column.
- Apply sticky effect on sidebar widget as below:
    - Sticky: Top
    - Sticky On: Desktop
    - Offset: 0
    - Effects Offset: 0
    - Stay in column: Active
- Save and view page.
- Scroll below stop point and resize browser window.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
			
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.42
	PHP Version: 7.0.33
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Web browser used ==
        Google Chrome Version 73.0.3683.103

</details>

**Comment by kroeberk** [comment]
Can confirm. This is a big issue. You can also check this page: https://ausbildung.thekey.community/inklusivleistungen/

We make extensive use of this effect and after resize the headings are all wrong.

**Comment by godschisel** [comment]
yop, also have problem with this. 
Elementor v. 2.5.15
Elementor Pro 2.5.8

Anybody know some workaround?

**Comment by sproutedweb** [comment]
## Your ticket has been created. ##


Ticket subject: Re: [elementor/elementor] [BUG] Sticky element stop point stops working when resizing window (#7884)


----
Author: godschisel 
Date: Tue, 05/14/19 12:38 pm
Message:
yop, also have problem with this. 
Elementor v. 2.5.15
Elementor Pro 2.5.8

Anybody know some workaround? 

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/elementor/elementor/issues/7884#issuecomment-492219327



Powered by https://www.livechatinc.com/powered-by-livechat/?utm_source=ticket_footer&utm_medium=email&utm_campaign=lc_10152642"

**Comment by sylphid3** [comment]
> yop, also have problem with this.
> Elementor v. 2.5.15
> Elementor Pro 2.5.8
> 
> Anybody know some workaround?

I tried some Jquery instead but somehow I couldn't get it to work correctly :/
If someone has a solution, or if the bug could be fixed in an update that would be perfect :)

**Comment by sylphid3** [comment]
I still have this problem.

Any information on this bug?
Any workaround would be very helpful!

Thanks!

**Comment by kaelmawn** [comment]
I still have this problem. This issue is now 2 months old.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by sylphid3** [comment]
Yes it works! A big thank you!
