### ISSUE TITLE
Toogle non-js initial state

### ISSUE THREAD

**Issue by robertjohnandrews** [elementor/elementor#7886]
If I disable JS from the browser the state of the toggle entries is closed. Is there a way for the default state to be ‘open’ and then when the JS is applied it closes the entries to be toggled?

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by shilo-ey** [comment]
Hi @robertjohnandrews 

Thanks for your feedback.

Unfortunately, this can be achieved only by using JS code.

Thanks.
