### ISSUE TITLE
View tags in a post

### ISSUE THREAD

**Issue by networking-web** [elementor/elementor#7887]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
**In a large site, at the bottom of each post must have tags in order to facilitate the surfer.**
You can now see the tags in a post info widget.
But can not be changed in the design :(

**Describe the solution you'd like**
Designed in Atlanta designed design tags,
So that each tag on a separate button, looks aesthetically beautiful.
In Elementor you can not touch design other than color ....
Tags are separated by commas that do not add beauty.
It's important to have tag design options!
Thank you
**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
@networking-web 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, this is only possible via custom CSS.


Thanks for the feedback.
