### ISSUE TITLE
Custom Backend Admin UI With Elementor

### ISSUE THREAD

**Issue by zrk4444** [elementor/elementor#7890]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Do you know what sucks?

The WordPress Admin UI.

In fact, it's complete trash.

It looks ugly, and after installing so many plugins your Admin menu is completely swamped and makes for a horrible UI.

And to make matters worse?

The plugin UI's don't match at all and are also ugly.

Often times the navigation is outright abysmal at best.

Oh, and good luck impressing clients.

I've tried plenty of so-called 'back end admin' themes and they all suck in comparison to what I could do with Elementor.

**Describe the solution you'd like**
Being able to make backend Admin Menu and topbar templates would be a good start.

Then instead of trying to navigate through confusing navigation, I can create Admin menus with much better nesting than the wordpress default.

Like this: http://prntscr.com/nd1u5d

However, the Admin menu and topbar is only the beginning.

Elementor needs a 'Shortcode Selector' and an 'Element Mapper'.

Let me explain.

This 'Shortcode Selector' should be able to select any element within the Wordpress Admin [or anywhere in general] and create a shortcode out of it.

The result?

I'm able to display backend data on the front-end or anywhere I'd like.

Perhaps I want to create a shortcode by selecting the element that displays my Woocommerce Order volume, or ROI, or any reporting data etc.

Now I can create sexy back end or front end dashboards that display this data, anywhere I'd like.

But, what if I want to create new inputs for my new sexy dashboard?

This is where the 'Element Mapper' comes in.

Essentially, you'd be able to map an input, let's say any of these inputs in this Woocommerce example: http://prntscr.com/nd1xmi  , to an input created by Elementor.

Through this mapping process, you can create entirely new UIs for ANY plugin etc. based on the original input's backend logic.

Another example would be if I wanted to create a new 'Add new Post' UI.

With the Element Mapper one could map the logic of the 'Publish', 'Preview', or 'Save Draft' button with another button element created by Elementor.

**Describe alternatives you've considered**
Pay a developer to create a custom plugin for this one day.

**Comment by bainternet** [comment]
@zrk4444 

Sadly neither, Elementor nor WordPress work in a way that would actually allow this kind of functionality you are describing here.

As for the way the dashboard looks or how it works, It's really up to WordPress, however, there is a way you can design custom admin pages using elementor, [see this tutorial](https://elementor.com/blog/custom-dashboard/).

thanks.

**Comment by Ssaa19** [comment]
Ddgfs

**Comment by Ssaa19** [comment]
Ddgfsa
