### ISSUE TITLE
Media carousel lightbox, closes popup from which it's launched

### ISSUE THREAD

**Issue by luukwvd** [elementor/elementor#7891]
I have made a popup which can be launched from a page which functions as expected. Within that popup I have made a media carousel which has a video + multiple images in it. Once you click the play button of the video the lightbox opens with the video (youtube) in it, remember the popup is still open since i haven't closed it. Once i close the video (with the 'x') or click somewhere beside the video which also closes the lightbox, the lightbox with the youtube video closes, but it also closes the popup which was still open. This seems like a small bug to me.

**Comment by shilo-ey** [comment]
Hi @luukwvd 

This is caused by user action.
Both lightbox and Popups uses the modal, which closes on based on same trigger.

Try disabling the close of the popup on click (under popup settings > advanced)

Thanks
