### ISSUE TITLE
How to cancel mail if form has error

### ISSUE THREAD

**Issue by kl3sk** [elementor/elementor#7894]
Hello,

I hook a custom plugin with `elementor_pro/forms/validation` that works as intended. I can programmatically raise an error on the form.

On the backend side of the form elementor page, I add an email action on it, but when my raise a custom error on form, this action is not cancelled. 
I follow some step explained [here]( https://github.com/elementor/elementor/issues/5006), but it not cancel the submit.

I originally post my question [here](https://wordpress.org/support/topic/stop-form-submit-after-elementor_pro-forms-validation-hook/#post-11438603).

As I said in this post I send a question to the support with no answer yet.

Thanks

**Comment by shilo-ey** [comment]
Hi @kl3sk 

Please paste your code here and we will see what seems to be the error.

In addition, you can read more in [this issue](https://github.com/elementor/elementor/issues/4994#issuecomment-404106176).

Awaiting your response.

Thanks!

**Comment by kl3sk** [comment]
Hi @shilo-ey,

Thank you for your answer, with your link I think I have fixed my problem.
If I understand it correctly, the form is stopped (in this case) if and only if I had:

```php
$handler->add_error($field, $msg)
```
and not on only
```php
$handler->add_error_message($msg)
```
I think `add_error_message` could be consider a global form error that stop this handler.

Anyway, thank you for your help that the support said this is beyond their scope 😢

**Comment by shilo-ey** [comment]
Great :)

Good luck
