### ISSUE TITLE
Feature request : add "postmeta" inside "Dynamic" function

### ISSUE THREAD

**Issue by fhfournier** [elementor/elementor#7896]
Hi,

I really need that! Add a new option in Dynamic DropDown to select "postmeta" and after that. 

Do not populate a bunch a data (because there are so many postmeta!) but just a text field and we can enter the postmeta we want to get!

This could be very nice if we use custom field without ACF! Please :)

![image](https://user-images.githubusercontent.com/3278753/56313041-9a2c8480-611f-11e9-91bd-19c63472dc63.png)

**Comment by bainternet** [comment]
@fhfournier 

We already have that and its called "Post Custom Field", the very top option, Not really sure what is it called in your language.

![Screen Shot 2019-04-18 at 10 25 45](https://user-images.githubusercontent.com/660572/56343802-6e170f00-61c4-11e9-9a46-b09e0414ea72.png)

Thanks.

**Comment by fhfournier** [comment]
Yes but read again my feature request!

It's work with ACF but if i set custom post_meta without using ACF i can't get it there!

![image](https://user-images.githubusercontent.com/3278753/56360209-efb17180-61b1-11e9-8acb-f62f87d016c2.png)

You should add a option "text field" and i can write my custom post_meta there!

**Comment by fhfournier** [comment]
Like that!

![image](https://user-images.githubusercontent.com/3278753/56360362-69495f80-61b2-11e9-9296-ede805896747.png)
