### ISSUE TITLE
Check for Proper URLs in Social Media Element

### ISSUE THREAD

**Issue by squadcar** [elementor/elementor#7897]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

There's no prompt or indication that URLs entered into the social media icons element need to include http:// or https://, nor does the builder check for the absence of them when building the page on the front end.  Leads to easily ending up with links like http://mydomain.com/instagram.com/username

## Steps to reproduce

1. Add the Social Icons element to a page.
2. Add short urls to the link input.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @squadcar 

This behavior is intentional and applies to all URL fields.

[As you can see](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_test) - that's how HTML works, for allowing site owners to use relative links.

Thanks

**Comment by squadcar** [comment]
Why would you use a relative link for a social media/external link? There's literally zero situations where you would use a relative url with this element.

**Comment by shilo-ey** [comment]
Elementor is a modular system which uses the same controls in varying contexts.
In this case - the Elementor URL control works as designed leaving the common sense to the site builder.

Thanks.
