### ISSUE TITLE
Detect elementor_theme_do_location issue??

### ISSUE THREAD

**Issue by notrealdev** [elementor/elementor#7899]
Hi, how to check current page build with Elementor? I put this code in `header.php` file.
```php
if ( elementor_theme_do_location( 'header' ) ) {
	var_dump( 1 );
}
```
I want check the condition if this page build with Elementor but it always prints the Header Template? Why?

**Comment by bainternet** [comment]
@notrealdev 

`elementor_theme_do_location` does exactly as its name says:

Elementor Theme Do Location - which means you are telling it to print the `header` and that is why it does what you tell it to, print the Header template.

If you want to check if a page is built with elementor you can use the `is_built_with_elementor` method of the db class, ex:
```PHP
if ( Elementor\Plugin::$instance->db->is_built_with_elementor( $post_id ) ) {
    // This page is built with elementor
}
```

If you want to check if the current page has elementor in any of its parts ( header, content, footer, etc...) then you can use the `has_elementor_in_page` method of the Frontend class, ex:
```PHP
if ( Elementor\Plugin::$instance->frontend->has_elementor_in_page() ) {
    // The current page has elementor
}
```

as for the Theme Location API, I would suggest taking a look at our [docs](https://developers.elementor.com/theme-locations-api/)

thanks.

**Comment by notrealdev** [comment]
Hi, sorry.
I'm mistake a bit, I want to ask how to defined if page has the Footer Template Location?
```php
if ( function_exists( 'elementor_theme_do_location' ) && elementor_theme_do_location( 'footer' ) ) {
	// This page have Footer Template Location. But this code alway print html result.
}
```
![image](https://i.imgur.com/wW2BvLj.jpg)
