### ISSUE TITLE
Add Printing Stylesheet

### ISSUE THREAD

**Issue by janfehlis** [elementor/elementor#7901]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
E.g. for business website users printing pages is still a thing. They need to show content to their superiors, for approval (e.g. further education)

**Describe the solution you'd like**
Please add a print stylesheet to Elementor

**Describe alternatives you've considered**
Using third party plugin, writing a stylesheet myself.

**Additional context**
n/a

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by blenkhn** [comment]
I have a large requirement for this feature.  I ama web-developer and all of my clients want to be able to print out the pages for brochures and other reasons.  Especially printing to a PDF.
 When do you think this will be done?

**Comment by vgstef** [comment]
Personally, I have clients that have recipes on their website so they need a way to print the pages correctly.
