### ISSUE TITLE
Custom stylesheets/scripts per widget

### ISSUE THREAD

**Issue by joezimdelta** [elementor/elementor#7907]
Some widgets we've created have stylesheets associated with them and right now we throw something like this at the top of the `render` method:

```php
if (is_admin()) {
	// The admin editor doesn't respond to `wp_enqueue_script` or `wp_enqueue_style`, so you need to pull things in manually
	?><link rel="stylesheet" href="PATH_TO_WIDGET_STYLESHEET" /><?php
} else {
	// Enqueue custom script and styles for this widget
	wp_enqueue_script('our-widget-script', PATH_TO_WIDGET_SCRIPT,  ['jquery'], '1.0', true );
	wp_enqueue_style('our-widget-styles', PATH_TO_WIDGET_STYLESHEET, null, '1.0' );
}
```

Notes:

1. `wp_enqueue_style`/`wp_enqueue_script` get run too late when using the admin, so we use a `link` tag directly to pull things in on the admin.
2. Not bothering to bring in the script on admin because the interactivity isn't needed there (at least for this particular widget)

This seems to work, but I'm curious if there is an "official" way to do this? I see some hooks connected to enqueueing/registering scripts/styles, but no real context around them as to how and where to use them. I also don't like the separate `link`/`script` tag for admin, so if there's a way to do it that works on both front end and back end, that'd be wonderful.

**Comment by bainternet** [comment]
@joezimdelta 

The way to add custom styles and JavasScript files to a widget would be to use the `get_script_depends` and `get_style_depends` method of your widget class. For example to specify which scripts you need and elementor will enqueue them for you:

```PHP
public function get_script_depends() {
	return [ 'jquery','other_script_handle' ];
}
```
the same goes for styles:
```PHP
public function get_style_depends() {
	return [ 'MainStyleSeet','other_style_handle' ];
}
```
You only need to make sure you register your scripts and styles using `wp_register_script` and `wp_register_style`.

**Side note**: currently when you use `get_style_depends` it will only enqueue the styles in the footer and not in the head tag.


thanks.

**Comment by joezimdelta** [comment]
Thanks. Is this documented more somewhere?

**Comment by joezimdelta** [comment]
Inside my widget I have this:

```php
	public function __construct( $data = [], $args = null ) {
		parent::__construct( $data, $args );

		wp_register_script('membership-table-widget-js', get_template_directory_uri() . '/elementor-widgets/membership-table/membership-table.js', ['jquery'], '1.1', true );
		wp_register_style('membership-table-widget-css', get_template_directory_uri() . '/elementor-widgets/membership-table/membership-table.css', [], '1.1' );
	}

	public function get_script_depends() {
		return [ 'membership-table-widget-js' ];
	}

	public function get_style_depends() {
		return [ 'membership-table-widget-css' ];
	}
```

I'm registering in the constructor because I don't really have a better place to do it. Anyway, the script is loading fine on both front and back end, but the stylesheet is only loading on the front end, not in the editor. What's up with that?

**Comment by joezimdelta** [comment]
Any ideas?

**Comment by lxbdr** [comment]
I am facing the same issue right now and used the following workaround:

the place I'm calling `wp_register_style` I check if it's in preview mode and if it is, I'm enqueueing it right away like:

```php
wp_register_style('membership-table-widget-css', get_template_directory_uri() . '/elementor-widgets/membership-table/membership-table.css', [], '1.1' );
if ( \Elementor\Plugin::$instance->preview->is_preview_mode() ) {
	wp_enqueue_style( 'membership-table-widget-css' );
}
```

I am registering the styles on the `elementor/frontend/after_enqueue_styles` hook and scripts on `elementor/frontend/after_register_scripts` like they're showing here: https://developers.elementor.com/add-custom-functionality/

Downsides to this approach:

1. The stylesheets of ALL widgets you're doing this with are loaded in the editor but only the ones in use are loaded on the frontend. So if you have interfering styles you might see something different in the editor than you see on the frontend.
2. `get_style_depends()` is still not called for the editor so you might consider specifying additional deps when calling `wp_register_style(handle, path, deps, ...)`

There might be a more elegant way using the right hook at the right place but I also would prefer to have this fixed and not have these workarounds

**Comment by JimJ92120** [comment]
Does get_script_depends() and get_style_depends() load scripts and styles dynamically?
If the element is rendered ONLY -> enqueue associated script and style / else do not enqueue.

**btw scripts and styles must be enqueued either in the header or the footer. Should never been append aside the element it is used for...

**Comment by timrross** [comment]
For anyone searching for a solution for this, I found that as long as I registered the style, and had added the `get_style_depends` call in my widget, then I needed to hit the `Regenerate CSS` button in Elementor->Tools, and the new widgets styles started to show up in the editor.

**Comment by jared-rice** [comment]
I found a solution for this from this: [issue #3670](https://github.com/elementor/elementor/issues/3670)

Although, I am not sure if this has changed in the last few years, but I did not need to use an action for `'elementor/preview/enqueue_styles'` and enqueue the style manually for the editor show my styles.

You should register beforehand and then use `get_script_depends()` or `get_style_depends()` inside your widget file to have Elementor enqueue them.

Here is my code for these specific functions if it helps (I am not using a plugin just a directory in my theme named `elementor-widgets` with a folder for each widget and the files inside)

**widgets.php**
```
/**
 * Register Custom Styles and Scripts
 * 
 */
add_action( 'elementor/frontend/after_register_scripts', 'my_elementor_register_scripts');

function my_elementor_register_scripts() {
    wp_register_script( 'my-widget', get_stylesheet_directory_uri() . '/elementor-widgets/my-widget/my-widget.js');
}


add_action( 'elementor/frontend/after_register_styles', 'my_elementor_register_styles');

function my_elementor_register_styles() {
    wp_register_style( 'my-widget', get_stylesheet_directory_uri() . '/elementor-widgets/my-widget/my-widget.css' );
}


//Not sure if this is required feel free to uncomment and test (maybe for plugins it is)
/*
add_action( 'elementor/preview/enqueue_styles', 'my_elementor_preview_enqueue');

function my_elementor_preview_enqueue() {
	wp_enqueue_style( 'my-widget' );
}
*/
```



**my-widget.php**
```
/**
 * Enqueue Custom styles & scripts.
 *
 */
public function get_script_depends() {
	return [ 'my-widget' ];
}

public function get_style_depends() {
	return [ 'my-widget' ];
}
```

I did not have to do `Regenerate CSS` for this to start working, but you may have to. Hope this helps!
