### ISSUE TITLE
Background Video effect site loading speed

### ISSUE THREAD

**Issue by raroDev** [elementor/elementor#7909]
## Prerequisites
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm using video background feature on my site. I found that it break my scores on gtmetrix.
![gtmetrix-bad](https://user-images.githubusercontent.com/38188761/56364204-49d02800-61ee-11e9-92e4-85b49fbd5746.png)

When i switch off video background feature I end with this:
![gtmetrix-good](https://user-images.githubusercontent.com/38188761/56364299-800da780-61ee-11e9-940f-2cf70e676dd2.png)

**Describe the solution you'd like**
Solution : https://scottdeluzio.com/defer-parsing-javascript-youtube-videos/

**Comment by shilo-ey** [comment]
Hi @raroDev 

You can use custom code to defer it yourself to improve performance.

Thanks.

**Comment by raroDev** [comment]
I have no idea how to do it. I dont know how to find this particular code in elementor files. Any sugestions ?
