### ISSUE TITLE
Turn off the resposive mode

### ISSUE THREAD

**Issue by Seloha** [elementor/elementor#7910]
It has come to my dreadful attention that the page builder has not a disable responsive mode.  I mean, come on. Whyy? I am crying and going batshit crazy over some little mobile adjustment that makes the site uncomfortable to look at. For my page it would be much sexier with the desktop version on mobile.
Is there any way I still can disable responsive?

**Comment by shilo-ey** [comment]
Hi @Seloha 

Elementor is a **Responsive** page builder.
You can either [request a desktop site](https://www.techbout.com/request-desktop-version-website-android-phone-17720/) in your client, or set the breakpoints to different ones.

Thanks.
