### ISSUE TITLE
Fallback Posts Widget When Nothing Found

### ISSUE THREAD

**Issue by saulobraine** [elementor/elementor#7912]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I recently had to create a search template for a project.
I use Elementor PRO, and I used the POSTS widget.
But I was frustrated when I did not find the option to set a fallback when no posts were found.

**Describe the solution you'd like**

I directly see three options:

1 - Create an option in the post widget "No posts found". Which is exactly as the option suggests.

2 - Possibility to define a layout for "No posts found" (more flexible, in my point of view).

3 - Inclusion of HOOK, to be made like "Custom Query". But in case you have not found any POST.

**Describe alternatives you've considered**

So far I have not made any changes to the functionality change. I will wait for your return.

**Comment by Makramgit** [comment]
I have exactly the same requirement. Did you find any workaround for this?

**Comment by saulobraine** [comment]
> 
> 
> I have exactly the same requirement. Did you find any workaround for this?

I'm waiting a support response. Until now I don't found any friendly solution.

**Comment by noodleyness** [comment]
I also have this problem - still no solution for this?

**Comment by saulobraine** [comment]
Hi, @shilo-ey, did you have any quick solution, please?

**Comment by shilo-ey** [comment]
This issue has been solved in Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by lennertdaniels** [comment]
A working code snippet added to `functions.php` using @shilo-ey 's update:

```
add_action('elementor/query/query_results', function($query) {
	$total = $query->found_posts;
	if ($total == 0) {
		echo '<p class="text-align-center">No items found.</p>';
	}
});
```

You could even change the text depending on the post type or category the query is acting on:
```
if ( $query->get("post_type") == "some_other_post_type_slug" ) {
	echo "My customized message.";
}
```

Refer to the [WP_Query docs](https://developer.wordpress.org/reference/classes/wp_query/) to see which parameters are available.

**Comment by matar360** [comment]
Hey,
Did you guys notice that on last version of elementor this went back? 
I've created a custom query and when the query returns zero posts elementor is ignoring the qiery and presenting the post as usual.

**Comment by javiercriado** [comment]
Yes...I'm facing the same problem with the Loop Grid

**Comment by javiercriado** [comment]
you can use the plugin "dynamic conditions" and hide the posts widget

**Comment by pixeldesignstudio** [comment]
> 

@javiercriado I tried, but what condition did you use? 

That's a huge bug Elementor is facing here.

**Comment by javiercriado** [comment]
@pixeldesignstudio I really don't remember even the project I used this, but you can paste here screenshots for me to help you.

you could use the condition "Number of posts" and specify the category or post type.

for something more advanced you could create a shortcode function which returns 0 if no posts have been found and use the condition "Shortcode"

it seems this thread is closed because this issue was solved in a newer version of the plugin, but if I posted that reply, my guess is that it's solution wasn't good enough

**Comment by pixeldesignstudio** [comment]
> @pixeldesignstudio I really don't remember even the project I used this, but you can paste here screenshots for me to help you.
> 
> you could use the condition "Number of posts" and specify the category or post type.
> 
> for something more advanced you could create a shortcode function which returns 0 if no posts have been found and use the condition "Shortcode"
> 
> it seems this thread is closed because this issue was solved in a newer version of the plugin, but if I posted that reply, my guess is that it's solution wasn't good enough

@javiercriado 

I tried both, but "number of posts" or  $query->found_posts is always 0. I also print_r the $query, but it doesn't hold any information about the result count. Which is weird.

**Comment by javiercriado** [comment]
I've just made a test using the latest version of Elementor Pro (3.15.1) and if your loop grid doesn't have any posts it wont show at all.

if you don't have the latest version well I guess you could give a query id in the option there, then create a shortcode function in functions.php with that same query id and then apply the dynamic condition shortcode

<img width="268" alt="image" src="https://github.com/elementor/elementor/assets/11529913/800c4701-103c-42bc-96c7-e4dff19b6a58">

**Comment by saulobraine** [comment]
@pixeldesignstudio If you haven't gotten it yet, you can use my plugin https://github.com/saulobraine/template-for-not-found-posts just download zip and install, this will add a field for you select a template as a fallback for not found posts.
