### ISSUE TITLE
Exclude pop up for multiple visits

### ISSUE THREAD

**Issue by KptainB** [elementor/elementor#7913]
Hi there, 

You have already a function called "show after X sessions", it could be great if a new function "unshow after X session" came out. 

It could be a great improvement to be able to make our pop up only appear once time for a user who is navigating many pages (with the pop up activated) on our website.

**Comment by silvioghedin** [comment]
+1

**Comment by shilo-ey** [comment]
@KptainB 

You can limit the number of times popup will show to a certain user:
![image](https://user-images.githubusercontent.com/45009641/56469592-a62c8500-6444-11e9-9378-dae4f0a419ef.png)

You can set it to count when the user sees the popup or when he closes it.

Thanks
