### ISSUE TITLE
Product gallery dynamic field stoped working after update to woocommerce 3.6

### ISSUE THREAD

**Issue by doruradu** [elementor/elementor#7914]
Hi,

After updating to woocommerce 3.6, the Product gallery dynamic field breaks (no images are passed to the widget). Is there a quick fix? Thanks!

<img width="1349" alt="Screenshot 2019-04-19 at 12 31 23" src="https://user-images.githubusercontent.com/8161136/56418514-cbcc5980-629f-11e9-99a3-ad33eed869f0.png">

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

We couldn't reproduce.
Please see reference in [this issue report](https://github.com/woocommerce/woocommerce/issues/23357) from WooCommerce GitHub repo

Thanks.

**Comment by bdthemes** [comment]
Same problem me too,

**How to reproduce the problem:**

1. Go to any product page and edit with elementor
2. Insert a image gallery
3. select dynamic > product gallery
4. Look there nothing show by woocommerce 3.6 version: http://prntscr.com/nffmi5

In version 3.5.4 it's working: http://prntscr.com/nffvwp

**Solution is:**

Need to post ID in \elementor-pro\modules\woocommerce\tags\product-gallery.php  (line 28) http://prntscr.com/nfg5r6

**Comment by shilo-ey** [comment]
@bdthemes 
Please see the provided link above- it seems to be an issue with WooCommerce version, they are working on a patch. there's a workaround there for the meanwhile.

**Comment by bdthemes** [comment]
Hi @shilo-ey, Yeah it's woocommerce version issue in 3.6+ `wc_get_product()` need a post ID as parameter.
