### ISSUE TITLE
Dynamic fields - search function and manually edit and save.

### ISSUE THREAD

**Issue by alriksson** [elementor/elementor#7918]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When building at scale and try to fetch correct meta field I run into UX/UI problems and would like to be able to search for dynamic fields especially keys.

**Describe the solution you'd like**
It would be great with a search functions within the dynamic field but especially in key fields. Add search function directly into dynamic and key fields for amazing UI, quickly navigate to the correct dynamic field.

Would also be good if I could open up the dynamic key and adjust the field name and save. This if I just have to change a fields number from 3 to 4. This would speed up the templating since repeater fields is not possible today in Elementor I have to do work arounds. And if I could search and additionally open a fields and manually edit the name it should fetch and save/apply that would speed up my work.

Let's do dynamic!

**Comment by bainternet** [comment]
@alriksson 

Currently, this feature is not supported, Mainly for the reason that there are too many custom fields plugins and each one works differently, not to mention the native custom fields. So we built it as generic as possible to allow us to support as many of them as possible.

Thanks for the feedback.

**Comment by alriksson** [comment]
@bainternet Why not create a hook so that ACF and other developers of custom fields can hook into Elementor? And you off-load the work to them to be compatible?
