### ISSUE TITLE
Several custom post type in the same Grid

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#7920]
Hello

I have 4 Custom post type. (Videos, snippets, books and audios)

And I want a Grid post with the last posts from 2 custom post type. (videos and audios) in the same grid.

Is it possible.?

**Comment by shilo-ey** [comment]
Hi @lauranunez 

You can achieve this by using a [Custom Query](https://developers.elementor.com/custom-query-filter/#Multiple_Post_Types_in_Posts_Widget)

Next time please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Thanks.
