### ISSUE TITLE
Name custom post type in Filtering Grid?

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#7923]
I am working with custom query filter, it works fine I have filtered 3 custom post type in Grid Posts

https://developers.elementor.com/custom-query-filter

But I need to show the title of custom post type as metadata. Is it possible?

Any function?

**Comment by bainternet** [comment]
@lauranunez 

Currently, this feature is not supported, follow #4440 

or for now, you can either create a custom skin (just search it here on Github issues) or use a 3rd party plugin https://wordpress.org/plugins/ele-custom-skin/



Thanks for the feedback.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
