### ISSUE TITLE
Show Custom Post type name Dinamic

### ISSUE THREAD

**Issue by lauranunez** [elementor/elementor#7925]
Hello,

I am using Ele Custom Skin.

I have added image Dinamic, Title Dinamic, Url Dinamic... But I want to show title custom post type.

I have found archive title. With archive title you show Custom Post Type Name + Title. I want to show only Custom post type name.

Is it possible?

**Comment by shilo-ey** [comment]
Elementor custom skin is a 3rd party plugin and not an official one.

Contact their support for assistance.

Thanks.
