### ISSUE TITLE
Re require an option for no image in testimonials and testimonial carousel #6606

### ISSUE THREAD

**Issue by gwmbox** [elementor/elementor#7927]
I know this has been asked for before but it would seem that the original request has been closed when it was not resolved.  I have made a comment on that but I am thinking it will not be seen or action since the post is closed.

https://github.com/elementor/elementor/issues/6606

In testimonials, and where ever else an image is used there needs to be an option for 'no image', or 'none' at all and then NOT use the placeholder.png file.

![50614649-760da600-0e96-11e9-9447-0d7124c98148](https://user-images.githubusercontent.com/7844638/56484781-d5ee9200-6503-11e9-99f8-c0bc4f227e84.png)

Here is how the placeholder.png file is called when we do not add an image - this needs to be removed and thus not called by Elementor as a default if no image is selected.

`<div class="caption"><img src="https://mysite.com/wp-content/plugins/elementor/assets/images/placeholder.png" alt=""><div style="height: 667px; width: 1000px; opacity: 0.7; display: block;"></div></div>`

As per that other request selecting no image is not an option, there needs to be a way to not show any image at all.

I hope this reopens the request and that this is very soon added to Elementor as a standard feature.

**Comment by shilo-ey** [comment]
Hi @gwmbox 

As mentioned earlier in #6606 you can remove the placeholder image.
When removing the placeholder images there is no reference for them in the code. 

Search for yourself here:
```HTML
<div class="elementor-widget-container">
					<div class="elementor-swiper">
			<div class="elementor-main-swiper swiper-container swiper-container-horizontal" style="cursor: grab;">
				<div class="swiper-wrapper" style="transition-duration: 0ms; transform: translate3d(-2148px, 0px, 0px);"><div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-next" data-swiper-slide-index="2" style="width: 1064px; margin-right: 10px;">
									<div class="elementor-testimonial">
							<div class="elementor-testimonial__content">
					<div class="elementor-testimonial__text">
						I am slide content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.					</div>
									</div>
						<div class="elementor-testimonial__footer">
								<cite class="elementor-testimonial__cite"><span class="elementor-testimonial__name">John Doe</span><span class="elementor-testimonial__title">CEO</span></cite>			</div>
		</div>
								</div>
											<div class="swiper-slide swiper-slide-prev" data-swiper-slide-index="0" style="width: 1064px; margin-right: 10px;">
									<div class="elementor-testimonial">
							<div class="elementor-testimonial__content">
					<div class="elementor-testimonial__text">
						I am slide content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.					</div>
									</div>
						<div class="elementor-testimonial__footer">
								<cite class="elementor-testimonial__cite"><span class="elementor-testimonial__name">John Doe</span><span class="elementor-testimonial__title">CEO</span></cite>			</div>
		</div>
								</div>
											<div class="swiper-slide swiper-slide-active" data-swiper-slide-index="1" style="width: 1064px; margin-right: 10px;">
									<div class="elementor-testimonial">
							<div class="elementor-testimonial__content">
					<div class="elementor-testimonial__text">
						I am slide content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.					</div>
									</div>
						<div class="elementor-testimonial__footer">
								<cite class="elementor-testimonial__cite"><span class="elementor-testimonial__name">John Doe</span><span class="elementor-testimonial__title">CEO</span></cite>			</div>
		</div>
								</div>
											<div class="swiper-slide swiper-slide-next" data-swiper-slide-index="2" style="width: 1064px; margin-right: 10px;">
									<div class="elementor-testimonial">
							<div class="elementor-testimonial__content">
					<div class="elementor-testimonial__text">
						I am slide content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.					</div>
									</div>
						<div class="elementor-testimonial__footer">
								<cite class="elementor-testimonial__cite"><span class="elementor-testimonial__name">John Doe</span><span class="elementor-testimonial__title">CEO</span></cite>			</div>
		</div>
								</div>
									<div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-prev" data-swiper-slide-index="0" style="width: 1064px; margin-right: 10px;">
									<div class="elementor-testimonial">
							<div class="elementor-testimonial__content">
					<div class="elementor-testimonial__text">
						I am slide content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.					</div>
									</div>
						<div class="elementor-testimonial__footer">
								<cite class="elementor-testimonial__cite"><span class="elementor-testimonial__name">John Doe</span><span class="elementor-testimonial__title">CEO</span></cite>			</div>
		</div>
								</div></div>
															<div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 1"></span><span class="swiper-pagination-bullet swiper-pagination-bullet-active" tabindex="0" role="button" aria-label="Go to slide 2"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 3"></span></div>
																<div class="elementor-swiper-button elementor-swiper-button-prev" tabindex="0" role="button" aria-label="Previous slide">
							<i class="eicon-chevron-left" aria-hidden="true"></i>
							<span class="elementor-screen-only">Previous</span>
						</div>
						<div class="elementor-swiper-button elementor-swiper-button-next" tabindex="0" role="button" aria-label="Next slide">
							<i class="eicon-chevron-right" aria-hidden="true"></i>
							<span class="elementor-screen-only">Next</span>
						</div>
												<span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>
		</div>
				</div>
```

Thanks

**Comment by gwmbox** [comment]
Can I ask then how do I remove the placeholder for a single testimonial?  Here is the code I am getting that shows that the placeholder image is being used still

 

<div class="elementor-element elementor-element-43a88fc1 elementor-widget__width-auto testimonial-content elementor-widget elementor-widget-testimonial" data-id="43a88fc1" data-element_type="widget" data-widget_type="testimonial.default">

  <div class="elementor-widget-container">

    <div class="elementor-testimonial-wrapper elementor-testimonial-text-align-left">

      <div class="elementor-testimonial-content">Michelle is not only an amazing photographer and artist, but a simply lovely human who goes out of her way to make sure you are fully happy.​</div>

 

      <div class="elementor-testimonial-meta elementor-has-image elementor-testimonial-image-position-aside">

        <div class="elementor-testimonial-meta-inner">

          <div class="elementor-testimonial-image">

            <img src="https://mysite.com/wp-content/plugins/elementor/assets/images/placeholder.png" title="" alt=""></div>

 

            <div class="elementor-testimonial-details">

              <div class="elementor-testimonial-name">Jo</div>

            </div>

          </div>

        </div>

      </div>

    </div>

</div>

 

Is there a way to turn it off?  If so where?

 

Thanks

**Comment by gwmbox** [comment]
my mistake and yes it works, sorry.  I did not realise you can Delete the placeholder image itself.

**Comment by LIEL-ZOHAR** [comment]
Hey, where should i paste that code you mentioned **(<div class="caption"><img src="https://mysite.com/wp-content/plugins/elementor/assets/images/placeholder.png" alt=""><div style="height: 667px; width: 1000px; opacity: 0.7; display: block;"></div></div>)**  ?

i suppose that is html? how can i remove the testamonials crousel's images?

**Comment by Karendev** [comment]
Is there a way to style each sliders background individually, say by index number, so if data-swiper-slide-index=0, do this style, data-swiper-slide-index=1, do this style.............etc.

**Comment by lisabrig** [comment]
> my mistake and yes it works, sorry. I did not realise you can Delete the placeholder image itself.

Gitbox - can you say specifically what you did in order to delete the placeholder image for Testimonials in Elementor?
