### ISSUE TITLE
Automatic names for items in Navigator where possible

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#7932]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The Navigator is super helpful, but naming each widget is time consuming.

This feature request will save time by automatically naming some widgets in the navigator in cases where the name/title is obvious.

**Describe the solution you'd like**

If the widget has a field for 'Title', apply that title to the item in the Navigator. 

Examples of widgets with a title or similar:

Title widget
Animated Headline widget
Flipbox widget
Call to Action widget
Template widget (name of template selected)
Image Box widget
Icon Box widget
Alert widget
Anchor widget (#id)
Form widget (form name)

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback

**Comment by black-eye** [comment]
+1 Without such automated naming, the navigator is quite unpractical and hard to orient in. For this reason I hardly use it, just in cases where there are overlapping objets.

On the other hand, this is not a crucial feature, it's better if you'll concentrate on more important stuff.
