### ISSUE TITLE
Rearrange Price Table

### ISSUE THREAD

**Issue by maxvreeken** [elementor/elementor#7933]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I want to start with showing features and value instead of asking for money

**Describe the solution you'd like**

I want to show the price in dthe pricing table at the bottom.

**Describe alternatives you've considered**

Build the entire thing from scratch with sections

**Additional context**

To have a nice customer journey I first want to show value.
Let customers compare the different packages and then show the price.
This way he will see that the Pro version is the best and wants this.
If he sees the price last the will find psychological excuses why it's worth.

If he sees a price first and features later he will develop psychological excuses why he does not need the most expensive version.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #2297, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
