### ISSUE TITLE
Add vertical drag and drop positioning/size options for sections and columns

### ISSUE THREAD

**Issue by sajox5** [elementor/elementor#7934]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The new positioning options(absolute and inline) are very useful. However, the current column structure is very frustrating to deal with. Horizontal margins can easily be adjusted via drag and drop, but cannot be adjusted vertically or diagonally via drag and drop. This leads to me to have to adjust vertical height via margins and padding, and this generally breaks the mobile version of the page when I create and edit the page for desktop first, and then switch the editor to the mobile version. 

Vertical spacing in elementor is currently quite frustrating, as there really isn't any easy way to do it besides margins and padding, and that makes the page display differently on different screen sizes, which i can't really account for in the editor itself, as there are only 3 different responsive size breakpoints. I have to publish the page and test it on multiple devices to make sure the pages i have created function correctly and placement of elements works across devices. Being able to adjust the column/section structure itself should fix these responsive formatting issues, as far as i understand how elementor works.

My understanding of the way the editor currently functions is that  if you design a page entirely via the grid based system, it should accurately adjust position across screen sizes correct?

**Describe the solution you'd like**

Allow vertical/diagonal drag and drop position of columns and elements in addition to the current horizontal drag and drop column width adjustments that are currently possible. This would massively speed up workflow and allow much more accurate positioning of elements. A system similar to oxygen builder would be great. The video linked below has a timestamp that starts the video immediately at the time where the feature i am describing is demoed.

https://youtu.be/9HIBD3PUOj0?t=284

If that drag and drop padding/margins could be added to the columns in elementor, responsive positioning would be not only more intuitive, but more accurately guarantee the site will display in the same format across devices. This reduces the necessity of testing the site on multiple different screen sizes, as it will not require me to break the grid with margin and padding numbers.

**Describe alternatives you've considered**

Adjusting the margins and padding of either the elements within the columns or the columns themselves. Doing so has repeatedly broken pages for me across mobile devices, requiring me to manually adjust the padding in the mobile responsive editor. This more than doubles the time i need to design the page, as i have to move elements pixel by pixel sometimes to have elements aligned correctly.

**Additional context**

None

**Comment by parasshah195** [comment]
@sajox5 This is being requested since a long time (you can see a ticket from July 2018 - https://github.com/elementor/elementor/issues/5018) and it seems that Elementor doesn't want to prioritize this anytime soon.

So, we built the solution as a part of our own add-on to speed up the workflow. You can check it out here - https://pixify.net/products/designer-powerup-for-elementor/features/quick-spacer/

Hope this helps.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #5018 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
