### ISSUE TITLE
Semantic HTML 5 

### ISSUE THREAD

**Issue by alriksson** [elementor/elementor#7935]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

- [x] The feature i should be implemented into core Elementor free version not Pro so all users can build semantic HTML5 websites.

I would like to wrap the sections into to `<main>` and `<article>` today I would have to wrap sections in Elementor into inner section but here it stops I can not wrap one more meaning I can not work around this issue. And neither would that solution be suitable for design and workflow.

The article should not be duplicated and the main should wrap the article meaning I neither extremely limited in design due to follow proper semantic HTML5 or I have to implement default in Elementor and broken semantic HTML5 will apply.

**Describe the solution you'd like**
When using default all sections have <section> tags correct. But it should always be wrapped into `<main>` and `<article>`. This is how semantic HTML5 is built up and should be structured.

From there you should give me the option in the main to wrap the core content block into different tags if users want. Exactly how you let me control the tags on each section.

```
<header>
<nav>
<main>
<article>
<section>
<aside>
<footer>
```

Maybe HTML5 options here: https://tppr.me/EFcep for users that want to break or change.

By default wrap the the whole single or page into <main> and <article>. See proper semantic HTML5 here: https://tppr.me/HwYYZ

 Following can be the hook to wrap:
```
<main>
  <article>
    <div data-elementor-type="post" data-elementor-id="38" class="elementor elementor-38 elementor-bc-flex-widget" data-elementor-settings="[]">
     <div class="elementor-inner">
```

**Additional context**
Critical, at least giving us a php snippet hook as a work around until implemented!

**Comment by shilo-ey** [comment]
Hi @alriksson 

[See here](https://github.com/elementor/elementor/issues/7859) for more details.

Thanks

**Comment by alriksson** [comment]
@shilo-ey thanks but I'm not looking into creating own documents in the theme builder. I'm looking for wrapping <main> and <article> as described above. That thread does not help me doing so you have to be more specific how I can work around this.

Or you mean I should create the public function print_content? Can't I add it directly to the existing single? Please send me the code example here in the ticket so more users also can benefit from it by wrapping everything in the single <main> and <article>. Thanks!

```
<main>
  <article>
<div data-elementor-type="single" data-elementor-id="379" class="elementor elementor-379 elementor-location-single post-290 page type-page status-publish hentry" data-elementor-settings="[]">

```
And closing the ticket I do not understand. This is standard HTML5, how a semantic build up should be created, and right now I have no option in elementor to do it properly,  and you consider this to be trash and close the thread? I consider this to be a part of the core not a special case and work around.

**Comment by alriksson** [comment]
What you show I can not replicate and not how I see it. Created a single template in the theme builder.

I do not see `<main>``<article>` do you have all elements and sections in elementor as default? I do not see what you just show me. That si exactly what I want.`<main>` and `<article>` and each section i create within elementor to be default which then is `<section>.` So the semantic html5 is as

```
<header>
<nav> (standard for navigation)
<--- Single start--->
<main>
<article>
<section>
<aside> (if specified or a sidebar is used)
<footer>

```


> Regarding closing this issue - when given an answer we close the issue for better managing all of our other issues. A closed issue can be commented on and is searchable.

Sure but removes it from feature request and for you to track and look into manage into the core.

**Comment by shilo-ey** [comment]
Try switching your theme to "Twenty Seventeen" and let me know if you can see this layout.

**Comment by alriksson** [comment]
Same issue as when using Elementor Hello Theme: https://github.com/elementor/elementor-hello-theme

Have you tried with your own Vanilla theme?

**Comment by shilo-ey** [comment]
[**@alriksson**](https://github.com/alriksson) commented on [Apr 24, 2019, 12:54 PM GMT+3](https://github.com/elementor/elementor/issues/7935#issuecomment-486154759 "2019-04-24T09:54:54Z - Replied by Github Reply Comments"):
> Same issue as when using Elementor Hello Theme: https://github.com/elementor/elementor-hello-theme
> 
> Have you tried with your own Vanilla theme?

I wasn't asking about Hello theme. I'm trying to isolate your issue.

**Comment by alriksson** [comment]
I see the same issue with the theme I use, "Elementor Hello Theme" as with "Twenty Seventeen".

Using "Default template".

**Comment by shilo-ey** [comment]
OK, now I can understand what you meant.

In pages created without Elementor Theme Builder - if your theme supports this structure it will be printed (try creating a page/post with default page template and with "Twenty Seventeen" theme.)

Currently, Elementor Theme Builder goes around the theme layout and uses the page templates provided.

To workaround this, you can use our Developers API and inject your desired structure:
```PHP
add_action( 'elementor/page_templates/header-footer/before_content' , 'open_main_article_inject' );
add_action( 'elementor/page_templates/canvas/before_content' , 'open_main_article_inject' );
function open_main_article_inject(){
    echo '<main><article>';
}
add_action( 'elementor/page_templates/header-footer/after_content' , 'close_main_article_inject' );
add_action( 'elementor/page_templates/canvas/after_content' , 'close_main_article_inject' );
function close_main_article_inject(){
    echo '</article></main>';
}
```

Read more about our [Develoers API here](https://developers.elementor.com/)

Thanks.

**Comment by alriksson** [comment]
@shilo-ey Worked perfectly! Great development support, very much approached! But, may I ask.. shouldn't this work like this from default and something you should integrate directly into the core of Elementor theme builder? So users don't have ot mess with developers API and custom php snippet?

Thinking about the broader audience that is less tech-savvy.

**Comment by shilo-ey** [comment]
@alriksson 

Thanks for bringing this to our attention, we will consider adding this.

**Comment by alriksson** [comment]
@shilo-ey You are most welcome, thanks for providing me with the development API workaround meanwhile. Very much appreciated! Great Dev support!

**Comment by alriksson** [comment]
@shilo-ey Would it be possible to inject more HTML tags this way as well? https://docs.elementor.com/article/353-how-to-add-html-tags-to-my-section-column

Would like to be flexible and build a table with elementor sections, inner sections, and columns. And this would be great to be able to do with the table html tags. Instead of using table widgets from the third party. Since I need to use dynamic conditions to hide if empty etc. And this is not possible with third-party plugins for items within a widget since elementor has no hook for it.
