### ISSUE TITLE
Button overlay

### ISSUE THREAD

**Issue by Slessmess** [elementor/elementor#7939]
## Prerequisites
<!-- MARK COMPLETED ITEMS WITH AN [x] --

**What problem is your feature request going to solve? Please describe.**
I want to have a button that pops up an overlay that I can edit from the editor instead of always making new pop ups. Optimize press has had this feature for years and it makes adding pop ups and videos inside those pop ups quick and easy. not to mention I can have a bunch of them specific to that one page I'm working on. 

**Describe the solution you'd like**
I would like to be able to place a button or an image or even text on a page and when someone clicks it, that opens a pop up just like optimize press does

**Describe alternatives you've considered**
I've tried using the pop-ups you have now but it's just too many steps  compared to optimize press
**Additional context**

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
