### ISSUE TITLE
Anytime i try to place a twitter feed in the footer via any addon packs, the element shows in the editor, but disappears instantly when previewing the footer.

### ISSUE THREAD

**Issue by sajox5** [elementor/elementor#7940]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am using some addon pack plugins for Elementor. I've tried both Essential Addons and Premium addons. Essential Addons twitter feed displays perfectly inside the editor when the sidebar is showing. The instant i collapse the sidebar, or use the eye icon to preview the page, the twitter feed disappears immediately. 

I don't have any settings enabled in the footer created entirely via the Elementor theme builder.
-->

## Steps to reproduce

All steps: 

1. Enable an addon pack with a twitter feed, the ones i attempted to use were Essential Addons and Premium Addons. 

2. Create or edit a footer in the theme builder

3. Attempt to place the twitter feed element inside the footer

4. Preview the page, either collapse the editing sidebar panel or use the preview button.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).

Elementor does not have a twitter widget by default, requiring usage of an element addon pack.

- [ ] This bug happens with a default WordPress theme active.

I cannot do so as the clients site is currently live.

- [x] I can reproduce this bug consistently using the steps above.

## Environment

Version: | 5.1.1 |  
-- | -- | --
WP Multisite: | No |  
Max Upload Size: | 128 MB |  
Memory limit: | 3000M |  
Permalink Structure: | /%postname%/ |  
Language: | en-US |  
Debug Mode: | Inactive

</details>

**Comment by shilo-ey** [comment]
Hi @sajox5 

We do not provide support for 3rd party plugins (such as add-on pack)


Please contact its developers and ask for support.

Thanks!
