### ISSUE TITLE
[Request] A way to sort various media in separate folders

### ISSUE THREAD

**Issue by Elementalel** [elementor/elementor#7943]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's very frustrating to go through dozens of pictures all the time. It's a big loss of time.

**Describe the solution you'd like**
A feature that allows users to sort their pictures, videos, and other media by specific folders.

**Describe alternatives you've considered**
Another plugin. But why use one when Elementor is already awesome?

**Additional context**
/

**Comment by shilo-ey** [comment]
Hi @Elementalel 

This is not Elementor related feature request because it's relates to a different aspect of WP.

You can use other plugins to achieve this goal ([for example](https://wordpress.org/plugins/enhanced-media-library/))

Thanks
