### ISSUE TITLE
Typography Control - UX improvement

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#7944]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### What problem is your feature request going to solve? Please describe.

Simpler user experience for the typography control.

### Describe the solution you'd like

Merge control types. Make all the sliders appear next to each other. And than all the select box.

### Additional context

Why? Because the sliders are the most used features in the typography control. In most cases I change the size, the line-height and the letter-spacing. It would be a huge improvement if they would be stacked together, one after the other. As for the select boxes, I rarely use them. That is why I think they should be at the bottom.

In addition, the user experience is different:
* With **sliders** we move the mouse from **left-to-right**.
* With **select boxes**, we move the mouse from **top-to-bottom**.

## Old Typography

![Typography-Old](https://user-images.githubusercontent.com/576623/56653683-d8352580-6696-11e9-9e80-53bc7eec81b0.png)

## New Typography

![Typography-New](https://user-images.githubusercontent.com/576623/56653685-db301600-6696-11e9-9fb9-baac7037acfa.png)

**Comment by arielk** [comment]
After an in-depth discussion with the product team, we do not think it's the right hierarchy for this control, so for now I'm closing the problem. I hope in the future we can redesign this control from scratch.

Thanks for your feedback!
