### ISSUE TITLE
Support for portrait and landscape views on tables

### ISSUE THREAD

**Issue by tomabowen** [elementor/elementor#7946]
I'm way new at this, but I've been looking for some solution for portrait and landscape views.  It would be great it the preview modes in Elementor added landscape mode to its options.

**Comment by codeorlov** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/2043 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
