### ISSUE TITLE
Current user avatar image as dynamic tag

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#7947]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello,
Feature request: 
Possibility to add 'current user avatar image' as dynamic tag to image widget. 
This would be nice to use on profile pages to show the user their current profile image.

**Comment by MPHood** [comment]
+1

**Comment by zachkinsey** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!
