### ISSUE TITLE
Elementor and WooCommerce storefront theme not showing notices & error for myaccount page

### ISSUE THREAD

**Issue by manektechmayank** [elementor/elementor#7952]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
1) First of all, I have installed all required plugins like Elementor, Elementor Pro, Woocommerce
2) Then I had installed the storefront theme.
3) Then I setup a woocommerce store and access myaccount without doing anything and it's working fine, it also genereate woocommerce notices & errors
4) But after added header using inbuild header templates of elementor pro plugin. My account page stopped showing error & notices of woocommerce.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Screenshot

1) This should be worked after using elementor & elementor pro plugin in my storefront theme.

![image](https://user-images.githubusercontent.com/31854318/56735628-97670a80-6783-11e9-8d9b-ed686cc8937e.png)

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.9
	MySQL version: MySQL Community Server (GPL) v5.7.12
	PHP Version: 7.2.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 15M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://beachbums.siteset.digital
	Home URL: http://beachbums.siteset.digital
	WP Multisite: No
	Max Upload Size: 15 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Storefront Child Theme
	Version: 1.0.0
	Author: Stuart Duff
	Child Theme: Yes
	Parent Theme Name: Storefront
	Parent Theme Version: 2.4.5
	Parent Theme Author: Automattic

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:67.0) Gecko/20100101 Firefox/67.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.13
		Author: Elliot Condon

	BackupBuddy
		Version: 8.3.9.0
		Author: iThemes

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.15
		Author: Namogo

	Elementor Pro
		Version: 2.5.5
		Author: Elementor.com

	Elementor Siteset
		Version: 1.8.2
		Author: Elementor Siteset

	WooCommerce
		Version: 3.6.2
		Author: Automattic

	WooCommerce Blocks
		Version: 2.0.1
		Author: Automattic

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.11
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 4.1.16
		Author: WooCommerce

	WPC Product Bundles for WooCommerce
		Version: 3.4.5
		Author: WPclever.net

	WP File Manager
		Version: 4.6
		Author: mndpsingh287

	WP Offload SES Lite
		Version: 1.0
		Author: Delicious Brains


== Log ==
	: 
JS: showing 8 of 8JS: 2019-03-22 11:47:14 [error X 2][http://beachbums.siteset.digital/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.9:2:75360] setting getter-only property \"type\" 
JS: 2019-04-23 07:48:26 [error X 2][http://beachbums.siteset.digital/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `heading` got <0> as `sticky_offset` value. Expected array or object.',
)]
JS: 2019-04-23 07:48:26 [error X 1][http://beachbums.siteset.digital/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `text-editor` got <0> as `sticky_offset` value. Expected array or object.',
)]
JS: 2019-04-23 07:48:26 [error X 1][http://beachbums.siteset.digital/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `button` got <0> as `sticky_offset` value. Expected array or object.',
)]
JS: 2019-04-23 07:48:26 [error X 5][http://beachbums.siteset.digital/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `image` got <0> as `sticky_offset` value. Expected array or object.',
)]
JS: 2019-04-23 07:48:26 [error X 1][http://beachbums.siteset.digital/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `section` got <0> as `sticky_offset` value. Expected array or object.',
)]
JS: 2019-04-23 08:48:09 [error X 1][http://beachbums.siteset.digital/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.5.5:2:16961] Cannot read property \'render\' of undefined 
JS: 2019-04-24 07:20:57 [error X 1][http://beachbums.siteset.digital/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.1.1 line 1 > Function:9:8] settings.link is undefined 

Log: showing 20 of 262019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-04-23 07:29:56 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-23 07:29:57 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-23 07:29:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.5',
)]
2019-04-23 07:29:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.5',
)]

PHP: showing 1 of 1PHP: 2019-04-24 07:21:51 [notice X 1][/var/www/wordpress/beachbums/wp-content/plugins/elementor-pro/modules/woocommerce/classes/current-query-renderer.php::36] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



```
</details>

**Comment by manektechmayank** [comment]
@shilo-ey  Would you please look at this issue?

**Comment by lewclarke** [comment]
I'm having exactly the same issue, but I noticed this also happens on other pages. In my case, I noticed it on the single product page, any notices no longer display, "added to cart" etc.

**Comment by shilo-ey** [comment]
@manektechmayank 
Thanks for contacting us,

Can't manage to reproduce your issue with Storefront + Elementor Pro:
![image](https://user-images.githubusercontent.com/45009641/57211507-2cba9800-6fe9-11e9-8c6e-640f215e4987.png)

**Comment by manektechmayank** [comment]
@shilo-ey Thank you for your response. I have submitted the query to support@elementor.com
Thank you so much. :)

**Comment by vickylester** [comment]
> @shilo-ey Thank you for your response. I have submitted the query to [support@elementor.com](mailto:support@elementor.com)
> Thank you so much. :)

Hello,

I have the same issue. Did you have a reply for the Elementor Support?

Thanks

**Comment by pawelgabski** [comment]
Hi guys,
I have the same issue. It's happened when elementor header templates is ready. Can anybody help?
Thanks.

**Comment by halunk3** [comment]
Hi, 
is there a soution to the problem, we have the same Issue. 

Thanks !

**Comment by vickylester** [comment]
Hello,
here's the reply I had:

> It is currently under observation but we cannot tell the exact time for the solution. This is why we don't recommend a theme, if a problem comes up we don't have control over their products. However, I would advise you to join our Facebook community and check with our users there.

I gave up storefront and installed the Elementor theme, Hello. It works fine so far.

**Comment by halunk3** [comment]
Hi vickylester, 
does the Elementor Theme Hello work with woocommerce perfectly ?  
I customized a good Shop in Storefront and would be reluctant switch. 

Thanks !

**Comment by pawelgabski** [comment]
> 
> 
> Hi vickylester,
> does the Elementor Theme Hello work with woocommerce perfectly ?
> I customized a good Shop in Storefront and would be reluctant switch.
> 
> Thanks !

Yes it's work very good. I moved from storefront to Hello elementor theme. This is the best way to fix this issue :)

**Comment by halunk3** [comment]
Ok, thanks, we switch to the Hello Elementor Theme in a few days.

**Comment by mehmet-london** [comment]
Hi,

I have the same problem. But differently it didn't solve when I start to use Hello Theme. 
It is starting work only when I deactivate Elementor Pro.

Something must be wrong with elementor Pro

Elementor + any theme = works fine
Elementor + Hello = works fine
Elementor Pro + Anytime = no woocommerce notice
Elementor Pro + Hello Theme = no woocommerce notice

I have last version of Woocommerce + Elementor + Elementor Pro + Hello Theme

No any custom code, no plugin etc.

Thanks.

**Comment by manektechmayank** [comment]
> 
> 
> Hi,
> 
> I have the same problem. But differently it didn't solve when I start to use Hello Theme.
> It is starting work only when I deactivate Elementor Pro.
> 
> Something must be wrong with elementor Pro
> 
> Elementor + any theme = works fine
> Elementor + Hello = works fine
> Elementor Pro + Anytime = no woocommerce notice
> Elementor Pro + Hello Theme = no woocommerce notice
> 
> I have last version of Woocommerce + Elementor + Elementor Pro + Hello Theme
> 
> No any custom code, no plugin etc.
> 
> Thanks.

@mehmet-london 
I have resolved this issue by using this "ELementor Hello Theme" : https://wordpress.org/themes/hello-elementor/

It will distorted the design of my account page and payment card. But you will get that easily from Google. 

Let me know if you have still issue, I can help you anytime.

**Comment by milouser** [comment]
Hi shilo-ey 

This problem still exists. Is it possible to reopen it and find a solution? I've already reported this issue to Elementor support and in your internal system as a possible theme compatibility issue, and was told to post here.

From My-Account Page Login messages like "ERROR: The password field is empty." are not displayed when:
- Elementor Pro and Storefront are activated

The are displayed when:
- Elementor and Storefront are activated (and Elementor Pro is deactivated)
- Twenty Seventeen and Elementor are activated
- Twenty Seventeen and Elementor Pro are activated

All tests were done with the child theme deactivated and the latest version as for 2 weeks ago.

I had a lengthy support chat with Automattic (Storefront) and went through the cases "live" with them. They confirmed the issue, but see the problem on the side of Elementor...

Two screenshots for a better understanding:
Elementor Pro & Storefront: <img width="669" alt="Pro activated - Screenshot 2019-08-17 at 10 51 12" src="https://user-images.githubusercontent.com/43952852/63789643-0f8f3980-c8f8-11e9-806f-f5b6759588ce.png">

Elementor without Pro and Storefront: 
<img width="559" alt="Pro deactivated - Screenshot 2019-08-17 at 10 54 18" src="https://user-images.githubusercontent.com/43952852/63789713-3188bc00-c8f8-11e9-98e6-cd9b2bf04c8d.png">

Cheers!

**Comment by lewclarke** [comment]
I agree with milouser above. I feel this was closed to early, as this issue is not resolved.

The suggestion above about moving to use the hello theme doesnt seem like a solution, elementor doesnt support customisation of the most important pages for WooCommerce (cart, checkout, my account) and look awful with the hello theme, so not sure how thats a solution!

**Comment by kulikovdigitalspace** [comment]
I have the same problem only with Elementor + Storefront. 
Works fine with Hello Elementor theme and Html5 blank theme.

**Comment by degregar** [comment]
Hi, got the same problem. I've disabled all plugins and themes, switched to Hello theme and I have no notices. If I turn off Elementor PRO it works.

**Comment by jomskidoodle** [comment]
Following.. I also have the same problem with Elementor Pro + Storefront. hope someone already solved this.

**Comment by DeanForde** [comment]
I also have the same problem with Elementor Pro + Storefront.

**Comment by DeanForde** [comment]
can anyone confirm that if we remove the header template the notices will be enabled again?

**Comment by DeanForde** [comment]
issue resolved 

// In your functions.php

```
function remove_storefront_notices(){
	remove_action('storefront_content_top', 'storefront_shop_messages', 15 );
}
```
add_action( 'wp_head', 'remove_storefront_notices' );
The problem is related with elementor pro's theme-support.php#get_header function around line 70, which gets storefront/header.php that contains the storefront_content_top hook. That hook displays and clears WC notices, but because of the way it's set up it's not actually rendered. The above snippet just removes messages from that particular hook, which leaves them free to be displayed later on. I don't believe this will cause any compatibility issues if you're using Elementor Pro's header instead of Storefront. Happy building.
