### ISSUE TITLE
Static for Popup

### ISSUE THREAD

**Issue by arnoldkiti** [elementor/elementor#7953]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by arnoldkiti** [comment]
Hi @everyone,

I build a popup (Modal Window) for a website with the page builder Elementor Pro. 
But I can have some static like Google Analytics.

Best regards,

**Comment by shilo-ey** [comment]
Hi @arnoldkiti 

Thanks for your feedback.

Currently, you can achieve this by using a custom code each time a popup is activated by using jQuery.

e.g:
```JS
jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
    if ( document.getModal ) { // It's a popup document
        document.getModal().on( 'show', () => {
            console.log( 'Run your script here' );
        } );
    }
} );
```

Thanks
