### ISSUE TITLE
Including a template partial with a shortcode makes Elementor give a the_content error

### ISSUE THREAD

**Issue by darylknight** [elementor/elementor#7954]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I'm replacing an old site with Elementor, and there's some custom functionality in a template that lists all the entries in a custom post type, on multiple pages on the website. As far as I can tell, the best way for me to port this in to Elementor is to put the code in a partial file, write a function in functions.php to include it, then add a Shortcode widget to the Elementor page. The code for that function is:

    add_shortcode('team_section', 'includeTemplatePartial');
        function includeTemplatePartial($atts) {
            get_template_part( 'partials/team' );
    }

Once I've added that shortcode to a page, it displays correctly. As soon as I click Update, then refresh the editor, I get this:

![image](https://user-images.githubusercontent.com/1250017/56748141-f9297380-6787-11e9-9afe-4d704b1de41e.png)

As far as I can tell, Elementor is including the template partial in to the main template, recognises that the included partial doesn't have a the_content tag, and complains about it - even though it works if I don't add the shortcode.

If I should be adding custom code to the page in some other way I'd love to hear it, but it seems like this should be doable, and Elementor is incorrectly flagging the page as not having a content tag.

## Steps to reproduce

- Create an Elementor Page
- Add a Function which creates a shortcode to include a template partial- 
- Add that shortcode to an Elementor page builder
- Click Update
- Refresh the page

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>

<summary>System Info</summary>

Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.39 (Unix) OpenSSL/1.0.2g |  
MySQL version: | (Ubuntu) v5.7.25 |  
PHP Version: | 7.1.28 |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 1024M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected
</details>

**Comment by bainternet** [comment]
@darylknight 

can you please paste the content of `partials/team` so we could help you identify the cause?

**Comment by darylknight** [comment]
```
<?php
# Get team Groups
$groups = get_categories(array('taxonomy' => 'wck_team_group'));

foreach($groups as $group) {
  # Query the team members.
	$args = array(
		'post_type' => 'wck_team',
		'tax_query' => array(
			array(
				'taxonomy' => 'wck_team_group',
				'field'    => 'slug',
				'terms'    => $group->slug,
			),
		),
		'posts_per_page' => -1
	);
	$team = new WP_Query( $args );
	set_query_var( 'team', $team );
	?>
<div class="container">
	<div class="row">
		<div class="col-12">
			<h3 class="team-heading"><?php echo($group->name); ?></h3>
			<?php if($group->description) { ?>
				<p><?php echo($group->description); ?></p>
			<?php } ?>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<?php
			while ( $team->have_posts() ) : $team->the_post();
				$photo = reset(rwmb_meta('wck_photo', 'type=image&size=medium'));
			?>
			<div class="col-12 col-sm-6 col-lg-4 col-xl-3 mx-auto">
				<a class="team-block" href="<?php esc_url( the_permalink() ) ?>" title="<?php the_title(); ?>">
					<img src="<?php echo($photo['url']); ?>" class="team-avatar" alt="">
					<p>
						<span class="team-name"><?php the_title(); ?><?php if(rwmb_meta('wck_creds')) { echo(', ' . rwmb_meta('wck_creds')); } ?></span><br/>
						<span class="team-title"><?php echo(rwmb_meta('wck_title')); ?></span>
					</p>
				</a>
			</div>
			<?php
			endwhile;
		?>
	</div>
</div>

<?php
	}
?>
```

**Comment by bainternet** [comment]
@darylknight 

try adding `wp_reset_query();` after your `foreach`. Thats the only thing I can think of since you are changing the global `$post` via `$team->the_post();`

Hope this helps.

**Comment by darylknight** [comment]
This solved the problem, thank you!

**Comment by jrolweb** [comment]
I had the same problem using shortcode!
Had been looking for the solution for hours. That way it worked.
Thank you very much! @bainternet
