### ISSUE TITLE
Section background video for mobile and tablet (self-hosted)

### ISSUE THREAD

**Issue by cenemil** [elementor/elementor#7955]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will solve the video background limitations in mobile and tablet screens. Currently, elementor has the background fallback image for mobile and tablet when the main background is set to a video(self-hosted)

**Describe the solution you'd like**
Add the html video attributes "webkit-playsinline" and "playsinline" coupled with the autoplay and muted default attributes.

**Describe alternatives you've considered**
Add the above attributes into the video wrapper or inject it via javascript or jquery
jQuery('.elementor-element .elementor-background-video-container').find('video').attr('playsinline','').attr('webkit-playsinline','');
The above code targets all elementor sections with video background

**Additional context**
Nothing

**Comment by cenemil** [comment]
The following css lines are also required for the video to be shown in mobile and tablet screens particularly 768px downwards

section.elementor-section.elementor-section-height-full {
  height: 100vh; /* Elementor front-end css only applies the full viewport height to 768px up */
}

.elementor .elementor-element .elementor-background-video-container.elementor-hidden-phone{
  display: unset; /* Elementor front-end css hides the background video markup to screens 768px down */
}

**Comment by exploredesign** [comment]
Hello I find this solution to be a nice temporary fix until Elementor implements video backgrounds for mobiles devices. However the YouTube video title and account profile appear for a second or so which I would prefer it didn't. Does anyone know an extra piece of code that will disable this. thank you

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.7

Feel free to update

Thanks!
