### ISSUE TITLE
Inner Section Sticky Scroll

### ISSUE THREAD

**Issue by zdesigner1** [elementor/elementor#7956]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

When using an inner section in Elementor and applying the Sticky Scroll effect, it's unable to "stay inside column". 

I have seen a lot of other requests regarding this. It'd be great to have this as a feature for Inner sections.

**Comment by MichaelDarko** [comment]
Agree, this would make things much easier if you want to stick more widgets at once and also want the whole thing to stay in column.

**Comment by LauGau** [comment]
+ 1 on that.
I have to use "Namogo Extras" for now...

**Comment by daniilicic** [comment]
+1

Really don't see a reason why inner section doesn't have the same Stay In Column option as any other element.

**Comment by taropaa** [comment]
I believe this is a bug, not a feature request. "Stay In Column" is part of the "Sticky" Motion Effect. It's a development oversight.

**Comment by Zach-Toth** [comment]
+1
I agree with @taropaa, definitely seems like a development oversight. 

A workaround is to save the section you want to make sticky as a template then insert with a template widget which has the option to "stay in column" but that seems a bit ridiculous and far too much work.

**Comment by javiercriado** [comment]
@Zach-Toth that did the trick. thank you!

**Comment by CasFrank** [comment]
+1

**Comment by CasFrank** [comment]
> +1
> I agree with @taropaa, definitely seems like a development oversight.
> 
> A workaround is to save the section you want to make sticky as a template then insert with a template widget which has the option to "stay in column" but that seems a bit ridiculous and far too much work.

@Zach-Toth  -  Thanks for the tip, that's a neat little work-around, i'll def use this for the time being (but yeah creates a few extra steps when it could be just included in the inner section)

**Comment by ParkerPhoto** [comment]
+1 Agree.  Please fix.

**Comment by daniilicic** [comment]
Any update guys? Do you plan to work on this sometime soon?

**Comment by Zunichi** [comment]
+1 This is super annoying. Please fix.

**Comment by black-eye** [comment]
+1

**Comment by prajjwalgeek** [comment]
It's disappointing to see that such a minor error isn't fixed even after 1 year...

**Comment by emirambel** [comment]
Why do the developers are not getting attention is on this issue?

**Comment by chrisgscott** [comment]
Just adding my +1 to have this addressed by the dev team.

**Comment by meeuwsen** [comment]
Yes please fix it :)

**Comment by 319heads** [comment]
How is this still not fixed? Super annoying.

**Comment by benstone326** [comment]
+1 to fix this please!

**Comment by Panagiotis-Kouvelis** [comment]
Allowing the full sticky options is a great addition. This is a very useful feature, especially for checkbox filters added on desktop on the side of the products' catalog. I use both Elementor and Elementor Pro for clients and my own stores, this would be a great addition to the inner section module.

**Comment by Panagiotis-Kouvelis** [comment]
> 
> 
> +1
> I agree with @taropaa, definitely seems like a development oversight.
> 
> A workaround is to save the section you want to make sticky as a template then insert with a template widget which has the option to "stay in column" but that seems a bit ridiculous and far too much work.

@Zach-Toth thanks for the useful tip, that would do it for now.

**Comment by xyberscript** [comment]
+1

**Comment by M-Marbouh** [comment]
Another +1... Must have

**Comment by HarryLoat** [comment]
This issue is due to the css that is added by the elementor when we make any element sticky. The developer of Elementor give the " postion:fixed " to the sticky element but if they give "position:sticky" to that then element will be sticky in its section not on the whole page.

+1 from my side to this issue

**Comment by MichaelDarko** [comment]
Not being able to make more than one widget sticky and stay in column is very limiting. I hope the devs figure out a solution to enable "Stay in column" for Inner sections.

**Comment by igorchernenko92** [comment]
+1 really need that

**Comment by tofrus** [comment]
Almost 2 years, and still no solutions. If you have more than 1 widget, both will overlap or keep going until the footer.

**Comment by shilo-ey** [comment]
Hey all,

This feature has been released in Elementor Pro v3.2.0

Feel free to update!

**Comment by kskonovalov** [comment]
Hi, @shilo-ey !
It looks like the issue appeared again after updating to 3.8.0, can you check?

**Comment by ronaldpostma** [comment]
> Hi, @shilo-ey ! It looks like the issue appeared again after updating to 3.8.0, can you check?

+1 issue has re-ocurred after updating to 3.8.0, I reverted back to 3.7.8 and 3.7.7(Pro) and this make the sticky inner section function as it should.
