### ISSUE TITLE
CPT Elementor Template  - WordPress Password Protection not working

### ISSUE THREAD

**Issue by dollhauss** [elementor/elementor#7960]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When a custom post type is created and an Elementor template is created for this post type. The WordPress Password Protected option no longer works.

The Elementor template appears to be removing something required to make the password protection work correctly.

## Steps to reproduce

Using CPT-UI.
1) Create CPT.
2) Add new post to CPT.
3) Publish post and set visibility to 'password protected'.
4) View post - you should see the password box.
5) Create Elementor Template - Single - Post / Display Conditions - [CPT name]. 
Save.
6) Go back to the CPT post and view - the password box does not appear.
The post is immediately viewable.
The post title says "Protected", but no password option was given.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: Percona Server (GPL), Release 84.3, Revision 71967c9 v5.6.43-84.3
	PHP Version: 7.2.16-1+0~20190307202206.17+jessie~1.gbpa7be82
	PHP Max Input Vars: 2500
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

== Active Plugins ==
	Custom Post Type UI
		Version: 1.6.1
		Author: WebDevStudios

	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.5
		Author: Elementor.com


== Log ==
	: 

				
```
</details>

**Comment by shilo-ey** [comment]
Hi @dollhauss 

Make sure your CPT is added properly, specifically the capabilities for `elementor` and `'show_in_rest' => true,`

e.g:
```PHP
// Register Custom Post Type
function custom_post_type_test() {

	$labels = array(
		'name'                  => _x( 'Custom Post Type', 'Post Type General Name', 'cpt_test' ),
		'singular_name'         => _x( 'Custom Post Type', 'Post Type Singular Name', 'cpt_test' ),
		'menu_name'             => __( 'Custom Post Type', 'cpt_test' ),
		'name_admin_bar'        => __( 'Custom Post Type', 'cpt_test' ),
		'archives'              => __( 'Item Archives', 'cpt_test' ),
		'attributes'            => __( 'Item Attributes', 'cpt_test' ),
		'parent_item_colon'     => __( 'Parent Item:', 'cpt_test' ),
		'all_items'             => __( 'All Items', 'cpt_test' ),
		'add_new_item'          => __( 'Add New Item', 'cpt_test' ),
		'add_new'               => __( 'Add New', 'cpt_test' ),
		'new_item'              => __( 'New Item', 'cpt_test' ),
		'edit_item'             => __( 'Edit Item', 'cpt_test' ),
		'update_item'           => __( 'Update Item', 'cpt_test' ),
		'view_item'             => __( 'View Item', 'cpt_test' ),
		'view_items'            => __( 'View Items', 'cpt_test' ),
		'search_items'          => __( 'Search Item', 'cpt_test' ),
		'not_found'             => __( 'Not found', 'cpt_test' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'cpt_test' ),
		'featured_image'        => __( 'Featured Image', 'cpt_test' ),
		'set_featured_image'    => __( 'Set featured image', 'cpt_test' ),
		'remove_featured_image' => __( 'Remove featured image', 'cpt_test' ),
		'use_featured_image'    => __( 'Use as featured image', 'cpt_test' ),
		'insert_into_item'      => __( 'Insert into item', 'cpt_test' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'cpt_test' ),
		'items_list'            => __( 'Items list', 'cpt_test' ),
		'items_list_navigation' => __( 'Items list navigation', 'cpt_test' ),
		'filter_items_list'     => __( 'Filter items list', 'cpt_test' ),
	);
	$args = array(
		'label'                 => __( 'Custom Post Type', 'cpt_test' ),
		'description'           => __( 'Custom Post Type Description', 'cpt_test' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'elementor' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'show_in_rest'          => true,
	);
	register_post_type( 'cpt_test', $args );

}
add_action( 'init', 'custom_post_type_test', 0 );
```

**Comment by dollhauss** [comment]
Hi @shilo-ey , thanks for your response but this does not fix the issue.

If you create a CPT in this way, password protection works with Elementor.
But if you create an Elementor template for this CPT it STOPS working.

Please follow the 'Steps To Reproduce' - Especially points 5 & 6.

1) Create CPT.
2) Add new post to CPT.
3) Publish post and set visibility to 'password protected'.
4) View post - you should see the password box.
5) Create Elementor Template - Single - Post / Display Conditions - [CPT name].
Save.
6) Go back to the CPT post and view - the password box does not appear.
The post is immediately viewable.
The post title says "Protected", but no password option was given.

Thanks.

**Comment by shilo-ey** [comment]
Hi @dollhauss 

That's exactly what we've tested, and worked fine.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists. If so please contact our support.

Thanks

**Comment by dollhauss** [comment]
Hi @shilo-ey,

Definitely not working here.
I have no plugins installed except Elementor, Elementor Pro and CPT-UI.
Using Twenty Sixteen theme.

Here is a quick video that goes through the steps and shows that it does not work:
[https://www.dropbox.com/s/9jzbz06d51do3an/CPT-Password-issue.mp4?dl=0]

The CPT output is as follows:

`function cptui_register_my_cpts_cpt_test() {

	/**
	 * Post Type: CPT Test.
	 */

	$labels = array(
		"name" => __( "CPT Test", "twentysixteen" ),
		"singular_name" => __( "CPT Test", "twentysixteen" ),
	);

	$args = array(
		"label" => __( "CPT Test", "twentysixteen" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"delete_with_user" => false,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => true,
		"rewrite" => array( "slug" => "cpt_test", "with_front" => true ),
		"query_var" => true,
		"supports" => array( "title", "editor", "thumbnail", "elementor" ),
	);

	register_post_type( "cpt_test", $args );
}

add_action( 'init', 'cptui_register_my_cpts_cpt_test' );
`

Please let me know if I have anything wrong here but everything I have tried does not work at all.

Thanks.

**Comment by dollhauss** [comment]
@shilo-ey 
I also added the CPT code you supplied to a blank Twenty Sixteen Child Theme with nothing installed apart from Elementor and Elementor Pro.
https://cl.ly/fea0e49e056c

As you can see the password protection still does not work when the Elementor Template is active for the CPT.

Thanks.

**Comment by dollhauss** [comment]
Quick update @shilo-ey 

I found the solution.
You have to set the Page Attributes - Template to 'Elementor Full Width'.

If you are using the themes 'Default' template it will not work.

Thanks!

**Comment by alfredo49** [comment]
I have the same issue

i cant fix it changing to "Elementor Full Width" because when i do this individual template isnt shown, only the post content..

**Comment by anybany** [comment]
Hi, are there any news on this issue?

when i set the page template of a password protected post to "elementor full width" the password forms shows up but after entering the password nothing is shown...
only after changing it back to "default temple" and deleting the password it shows up again.

i also tried setting a password for the elementor template (post type: elementor_library) i use for the custom post type - doesn't work.

How can one password protect custom post types which have a elementor template assigned (display conditions) and also the custom post types archive?

**Comment by thomasmalley** [comment]
@anybany I can confirm. In my Opinion there ist still an issue here.

**Comment by AivahThemes** [comment]
Do we have any updates on this? Still have an issue with that if we add condition in Elementor to use Single Page Template as explained by @slamdive

**Comment by moseskerub** [comment]
Still persists... that's a major problem

**Comment by gilbertb22** [comment]
In using CPT UI with a Divi builder template for the custom post type in question, I'm replicating this issue. Same condition but using Divi with a child theme.

**Comment by rubenoam** [comment]
Still an issue, but it actually returns a '.' now
