### ISSUE TITLE
Highlight parent menu of active child menu element

### ISSUE THREAD

**Issue by jespersandell** [elementor/elementor#7961]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When you have a submenu in the menu system, and a submenu icon is active, the parent isn't highlighted as active. 
**Describe the solution you'd like**
An example: In the top menu of the page, there is one item called "Resources". Resources has several options in a drop-down menu. When I select on of the options in the drop-down, they are highlighted as active. However, the parent isn't highlighted. It would be great to have the option to have the parent element highlighted as active. Either as a feature in the interface, or at least as a CSS snippet.

**Describe alternatives you've considered**
Custom coding my own CSS. Doing it with Javascript.

**Additional context**

**Comment by shilo-ey** [comment]
Elementor uses the WordPress native wp_nav_menu, so you can use the hooks and filters provided to add classes as needed.

not something that will be controlled via Elementor anytime soon.

thanks.

**Comment by jklovance** [comment]
This only works if sub-menu urls are in the form '/menu1/sub1', '/menu2/sub1', etc.

There is a js way to do this based on the URL and the menu item;
`   const pages = ['menu1','menu2','menu3'];
    const menuItems = ['menu-item-111', 'menu-item-2222', 'menu-item-333'];
    const url = window.location.href;
    jQuery.each(pages, function( index, page ) {
        if (url.search(page) > -1) {
            const search = '.'+menuItems[index]+' a';
            jQuery(search).addClass('elementor-item-active');
        }
    });`
The variable 'pages' is the list of url fragments to look for. The variable 'menuItems' is the class of the <li> tag for the top menu item All this does is finds the URL of a page from a menu and then added the active class to the top menu anchor.

Hope this helps

**Comment by primathon** [comment]
Finally worked out how to do this with a PHP snippet using core WP functionality:
```
// Add required highlight classes to menu parent <li> tag
if ( ! function_exists('highlight_parent_menu_list_item_on_child_page'))
{
  function highlight_parent_menu_list_item_on_child_page($classes, $item, $args)
  {
    if (in_array('current-page-ancestor', $item->classes))
    {
      $classes[] = 'current_page_item';
      $classes[] = 'current-menu-item';
    }
    return $classes;
  }
  add_filter('nav_menu_css_class','highlight_parent_menu_list_item_on_child_page', 10, 3);
}

// Add required highlight classes to menu parent <a> tag
if ( ! function_exists('highlight_parent_menu_link_on_child_page'))
{
  function highlight_parent_menu_link_on_child_page($atts, $item, $args)
  {
    if (in_array('current-page-ancestor', $item->classes))
    {
      if ( ! isset($atts['class']))
      {
        $atts['class'] = '';
      }
      $atts['class'] = trim($atts['class'] . ' elementor-item-active');
    }
    return $atts;
  }
}
add_filter('nav_menu_link_attributes', 'highlight_parent_menu_link_on_child_page', 10, 3);
```

**Comment by momo-fr** [comment]
HI, I want the same function for le mega menu widget.
Any idea??
