### ISSUE TITLE
Archive Page Number of Posts

### ISSUE THREAD

**Issue by Luxamman** [elementor/elementor#7963]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When creating a archive page with the theme builder, there is no setting in the post archive widget to set the number of shown posts per page. Seems there are always 10 posts, but this leads to uneven rows and less flexibility.

**Describe the solution you'd like**
Like the settings for post per row in the post archive element, a setting to set the number of shown elements per page, based on devices, should be added. 

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by hojtfredrik** [comment]
Found this too. 
The workaround I use is to always use three columns in desktop mode. And set the number of posts to 9 in the general settings in wordpress.

**Comment by shilo-ey** [comment]
The number of posts is determined by the native WordPress settings.

Go to WP Dashboard > Settings > Reading and change the number of posts you wish to retrieve.
![image](https://user-images.githubusercontent.com/45009641/56902680-72d0a280-6aa3-11e9-8b87-8914332ef2c6.png)

Thanks!

**Comment by PieterT2000** [comment]
Thanks @shilo-ey, that helped me too!

**Comment by JohannaShiri** [comment]
> The number of posts is determined by the native WordPress settings.
> 
> Go to WP Dashboard > Settings > Reading and change the number of posts you wish to retrieve. ![image](https://user-images.githubusercontent.com/45009641/56902680-72d0a280-6aa3-11e9-8b87-8914332ef2c6.png)
> 
> Thanks!

Helped me a lot thanks!

**Comment by ChrisASearles** [comment]
Can I ask why this was closed? If the setting in the widget does nothing, why does it exist?

**Comment by dingkai031** [comment]
> The number of posts is determined by the native WordPress settings.
> 
> Go to WP Dashboard > Settings > Reading and change the number of posts you wish to retrieve. ![image](https://user-images.githubusercontent.com/45009641/56902680-72d0a280-6aa3-11e9-8b87-8914332ef2c6.png)
> 
> Thanks!

Helped me, thanks! but this one is global settings right? how can we set for individual?
