### ISSUE TITLE
✅ 🐞 Video autoplay support in iframes with feature policy

### ISSUE THREAD

**Issue by TomasAgoston** [elementor/elementor#7964]
The iframes in elementor are missing the 'allow="autoplay"' attribute. Although Elementor has support for URLs rewrite to "autoplay=1", those URLs (e.g. Youtube) will not start to play automatically due to the missing attribute and changes in browser policy (Chrome/Chromium). Muted videos are working though.

See:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
https://w3c.github.io/webappsec-feature-policy/

The issue is in several places. See below, with suggestions how to alter the code, together with allowing 'fullscreen'.

**includes/widget/video.php**

`$video_html ='<iframe src="' . $video_url . '" scrolling="no" allow="autoplay, fullscreen" frameborder="0" allowfullscreen></iframe>';`

`$video_html = Embed::get_embed_html( $video_url, $embed_params, $embed_options, [ "allow" => "autoplay, fullscreen"] );`

Should fix #7728 also.

**assets/js/frontend.js**

`$videoElement = jQuery('<iframe>', { src: videoURL, allowfullscreen: 1, allow: 'autoplay, fullscreen' });`

`$videoFrame = jQuery('<iframe>', { src: videoURL,  allowfullscreen: 1, allow: 'autoplay, fullscreen' }),`

NOTE: combining "allowfullscreen" and "allow: 'fullscreen'" will result in a warning. The later can probably be omitted.

**Comment by pgrafix** [comment]
I have a similar issue with section background video in Chrome and Safari on desktop. Neither will autoplay the video - but FF does. I believe it is due to a possibly malformed video constructor:

<video class="elementor-background-video-hosted elementor-html5-video" autoplay="" loop="" muted="" src="http://example.com/wp-content/uploads/2019/05/example.mp4" style="width: 2545px; height: 1431.56px;"></video>

Notice the empty attributes. For one, autoplay is not designated and more importantly, the muted attribute isn't set correctly. Regardless if autoplay was set correctly, the absence of a muted designation would still prevent the video from playing - both Chrome and Safari require the video to be muted before autoplaying.

**Comment by pgrafix** [comment]
Actually, now that I have looked at it closer, the current syntax is wrong according to HTML 5 standards. The proper syntax would be:

`<video class="elementor-background-video-hosted elementor-html5-video" autoplay loop muted src="http://example.com/wp-content/uploads/2019/05/example.mp4" style="width: 2545px; height: 1431.56px;"></video>`

Notice the difference from my example code above - **autoplay=""** is replaced with simply **autoplay**. Same for the other attributes. They are not Boolean like the old HTML 4 ways of doing things. In HTML 5 thier presence or absence sets the functionality.

**Comment by cliftonc0613** [comment]
Has anyone heard an update on this issue? I have a client that wants this autoplay option for his video.

**Comment by debihazelden** [comment]
Is there a fix for this? I am using Elementor with a video as the section background and it won't auto play in Chrome or Safari.

**Comment by shaneonabike** [comment]
This is pretty basic and would be nice to see setup. Wouldn't it just be a matter of adding another variable that was passed to showModal to make this happen?

**Comment by JxxIT** [comment]
@TomasAgoston @rodolphebertozzo @cliftonc0613 @debihazelden @shaneonabike. My PR has been merged: #24324, this should be in the next update.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
