### ISSUE TITLE
Anchor Text Color Not Working for "a:link" & "a:hover"

### ISSUE THREAD

**Issue by Agapiou1** [elementor/elementor#7965]
I have created a "List" using an "HTML Element".

I have tried adding CSS to get Anchor Text in the list to initially appear white and then on hover to change to magenta. No matter what I do the Anchor Text will not initially appear in white but seems to be stuck permanently on magenta.

However, the anchor hrefs are working ok and I've noticed an increase in site traffic.

I initially tried adding the relevant CSS to my theme as Custom CSS and have also tried adding it to the page that the Element appears on, without success.

At present I have added Custom CSS to the HTML Element which I would expect to work since it is focused on the actual Element/ List.

Here's the link to my page - https://www.falmouthbayholidayapartments.co.uk/

See file attachment/screenshots.

Any help appreciated since I'm no expert at code :-)

Regards

John Morgan 

![Additional Sydney Theme CSS](https://user-images.githubusercontent.com/49680398/56801281-fb85df00-6814-11e9-83fb-f988b7adfe43.png)
![Custom CSS on HTML](https://user-images.githubusercontent.com/49680398/56801282-fb85df00-6814-11e9-9f51-be8e6959c90d.png)
![Customising Athemes Sydney Theme View](https://user-images.githubusercontent.com/49680398/56801283-fb85df00-6814-11e9-9284-04a0b645f08d.png)
![HTML Element CSS Setttings](https://user-images.githubusercontent.com/49680398/56801284-fb85df00-6814-11e9-99a5-291ef7525769.png)
![Live Page View](https://user-images.githubusercontent.com/49680398/56801285-fb85df00-6814-11e9-9f81-03735ae6eb26.png)

**Comment by shilo-ey** [comment]
Try using more specific selector (e.g when editing the HTML widget > advanced > Custom CSS > add `selector` before the `a` selector) to make it "stronger" than other selectors.

Thanks
