### ISSUE TITLE
Menu Cart Widget (Pro) - Show subtotal discount included

### ISSUE THREAD

**Issue by arcensoft** [elementor/elementor#7969]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
I would like to Show in the menu cart widget the subtotal and or the subtotal discount included. 

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

I would like to Show in the menu cart widget the subtotal and or the subtotal discount included. 

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
