### ISSUE TITLE
Open a new tab when clicking on a woocommerce product

### ISSUE THREAD

**Issue by DeysonOrtiz** [elementor/elementor#7971]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Hello, I am looking for a way to open a new tab when we click on a woocommerce product.

**Describe the solution you'd like**

When we click on a product on the archive or product page, I would like the product to open a new page, we can see this happen in Airbnb and Zillow.  This allows people to compare products and see different products without losing the original page.

Thank you.

**Comment by bainternet** [comment]
@DeysonOrtiz 

This can be done in the same way its done without Elementor, using WC hooks, ex:

```PHP
// Remove the native link opener
remove_action( 'woocommerce_before_shop_loop_item','woocommerce_template_loop_product_link_open', 10 );

// add your custom link open with target="_blank" to open in an new tab
add_action ( 'woocommerce_before_shop_loop_item', function() {
    global $product;
    $link = apply_filters( 'woocommerce_loop_product_link', get_the_permalink(), $product );
	echo '<a target="_blank" href="' . esc_url( $link ) . '" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">';
}, 10 );
```
thanks.
