### ISSUE TITLE
Transparent header?

### ISSUE THREAD

**Issue by drewclifton** [elementor/elementor#7984]
Opening a here ticket to request a proper transparent header option with Elementor.

I have researched and found the rather hackish workaround of adding a negative top margin to the top section of a page in accordance with the current pixel height of the header. There are a number of videos and blog posts explaining this, so it's obviously important to enough people out there (but not much attention from Elementor publicly from what I have found).

This is one of the most common web design trends in recent years and would be much appreciated to be able to do with our favourite page/site builder! :)

Current issues with the workaround:

- Adding a negative margin to the top section is janky.
- It requires manual updating of all pages in order to implement!
- When you edit your header height, it breaks the design (and you have to manually update the pages again).

Also I would love to hear some ways that people in the community have been working around this for now.

Finally, as for myself (and many others), it would be great to get some info about whether this is forthcoming at all (ie coming down the pipe soon, or on a roadmap perhaps?).

Thanks much! :)

**Comment by shilo-ey** [comment]
Hi @drewclifton 

You sure can create a transparent header, we even made a [tutorial about it](https://www.youtube.com/watch?v=0QpeKGfvKy8)

Thanks

**Comment by drewclifton** [comment]
Sorry - I should have clarified my definition of a transparent header. I simply mean a header that is transparent in its default state; not anything to do with scrolling. Perhaps this thread still has a place. Your definition is different from mine, and perhaps you didn't understand my first post.

Here's an example page I have created to clarify exactly what I mean:

https://wordpress-260255-819850.cloudwaysapps.com/

![Screen Shot 2019-04-29 at 8 41 48 PM](https://user-images.githubusercontent.com/33555978/56939789-41fe6680-6abf-11e9-8279-31308a68d4be.png)

Again, this is a very common trend in web design.

From what I have found online it seems that a hack is required, ie adding a negative top margin to the top section of any page you want to use your transparent header.

The issue seems to be that the header takes up its own vertical space, and offsets the top of the first section accordingly (with no native option/setting for any different behaviour).

Perhaps there could be a way to add a new setting/toggle to suppress the height of the header itself rather than have to adjust this at the individual page level (ie, as per the negative top margin section hack).

Thank you! Sorry if I'm missing something in your response.

**Comment by shilo-ey** [comment]
This kind of header will always need a background image to be shown, I would recommend you to create a layout which grabs the images and the texts dynamically using our dynamic tags. This way you can set the background image as the featured image of the page/post and will always have your layout correct.

Otherwise, you need to use the margins method.

Thanks
