### ISSUE TITLE
Is param type ok in get_render_attribute_string?

### ISSUE THREAD

**Issue by mlbd** [elementor/elementor#7988]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As you can see in here https://code.elementor.com/methods/elementor-element_base-get_render_attribute_string/ param type `array|string` documented. But there only string should be expected not array.

So, here is my question, there is anyway we can pass array on `get_render_attribute_string` ?
If yes, then can I have any and example about it. If not then I think docs needs to update as well doc comment where is method written.

By the way thanks for The Great Plugin.

**Comment by bainternet** [comment]
@mlbd 

nice catch and thanks for reporting, this will be corrected.
