### ISSUE TITLE
Error showing calendar of the Booked plugin using Accordion and Toggle

### ISSUE THREAD

**Issue by ebaru** [elementor/elementor#7991]
Using Accordion and Toggle I put a shortcode of the Booked plugin to show a calendar but in Mozilla Firefox it is not shown complete.  If I put this shortcode in an html it is displayed in a normal way.

See Figure:
https://www.dropbox.com/s/r6jdrm5cv4wtduh/accordion-toggle-error.png?dl=0

The page I need help with: https://migrar.parroquiasenlinea.org

**Comment by shilo-ey** [comment]
Hi @ebaru 

Thanks for your feedback.

The issue occurs due to a lack of CSS configuration in your booking plugin.
Chrome browser "knows" how to compensate this absence but it still not performing best.

I would recommend contacting this plugin developers for better troubleshooting.

Thanks
