### ISSUE TITLE
Disable autosave

### ISSUE THREAD

**Issue by jleitner** [elementor/elementor#7992]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by jleitner** [comment]
There is no option to disable auto save. When a page or template in Elementor, the page is automatically saved as a draft, which I need to discard if  I'm not making changes. Just because some users need automatic saves, doesn't imply that everyone wants the auto saves.  There should be an option to disable the feature. It doesn't check to see if there have been changes. If nothing has been changed, why is it automatically saving a draft?

**Comment by shilo-ey** [comment]
Hi @jleitner 
Elementor uses Wordpress native autosave mechanism.

You can change the interval by setting in `wp-config.php` file the following line:
`define( 'AUTOSAVE_INTERVAL', X );`  while X is in seconds.

Which X replaces the time you want to wait after a change (set it to 1 for immediate page save or 999,999 for probably almost never to autosave)

Thanks

**Comment by SubtleMonsters** [comment]
I would personally benefit from a way to just exempt Elementor from autosave. Autosave for posts is beneficial to my clients, but the autosave revisions system within Elementor has caused me problems on several occasions.

**Comment by gerardreches** [comment]
For some reason the autosave in Elementor is publishing changes that we haven't manually saved.

**Comment by alon42** [comment]
I found this plugin and it solved my problem

https://ultimateblocks.com/disable-autosave-in-wordpress/
