### ISSUE TITLE
Add new fields into all Elementor widgets

### ISSUE THREAD

**Issue by CreativForm** [elementor/elementor#7993]
Hello.

I'm plugin developer and customers of my plugin wants few things from my plugin to be included inside Elementor. I need some guide how I can add in all available PRO and free widgets custom fields and do some smal manipulations like section visibility?

I googling and looking docs and not figureout.

Can you help me?

Thanks!

**Comment by bainternet** [comment]
@CreativForm 

If you have Elementor Pro, then look at how we add the Custom CSS section to all widgets.

Other than that I would suggest you search the GitHub issues here labeled with "developer API".

Feel free to open a new issue and ask if you have a specific question.
thanks.

**Comment by CreativForm** [comment]
Yes. I have it. This is a good point. Thank you!
