### ISSUE TITLE
Woocommerce productpage VAT and delivery time are not displayed

### ISSUE THREAD

**Issue by itintime** [elementor/elementor#7994]
How can i add the vat and delivery time infos to the product page created by elementor?

Please help.

Nice Regards
Markus

**Comment by bainternet** [comment]
@iamntz 

is this something that is native to WC or are you using some kind of 3rd party plugin?

**Comment by itintime** [comment]
mostly yes, some changes comes fom woocommerce germanized extension

**Comment by Aviad-Herman** [comment]
Hi guys, 
Closing this old thread.
If it's still relevant feel free to reopen.
