### ISSUE TITLE
Custom style dependency not loading in the Elementor editor preview panel

### ISSUE THREAD

**Issue by mdjwel** [elementor/elementor#7996]
I have used the `get_style_depends()` function in the Elementor widget according to https://developers.elementor.com/add-custom-functionality/#Registering_Custom_Styles.
The dependent stylesheets are loading as on the frontend of the page. But the dependent stylesheets are not loading in the Elementor editor preview panel.
That's the main problem with the `get_style_depends()`.
I need to load the stylesheet file in the Elementor editor preview. 

Thanks

**Comment by MattOndo** [comment]
+1 Still an issue. A poor user experience is the result of this, is there already a hook to accomplish this or a workaround until this is fixed?

**Comment by rami-elementor** [comment]
Hi @mdjwel @MattOndo ,

We have updated our Dev Docs. The link you are referring to is a redirect. Please read the new docs focusing on [Scripts & Styles](https://developers.elementor.com/docs/scripts-styles/).

Elementor has several methods to register and enqueue custom scripts & styles. You mentioned the `get_style_depends()` method which refers to [Widgets Dependencies](https://developers.elementor.com/docs/widgets/widget-dependencies/). Using this method inside your widget class will enqueue the stylesheet in the frontend and in the editor preview.

If it's not happening, follow the docs, or share your code here, and we'll try to assist.
