### ISSUE TITLE
Tabs and Accordion on mobile: clicking a stacked tab should jump to the top of that tab's content, but it doesn't 

### ISSUE THREAD

**Issue by david-wingtra** [elementor/elementor#7998]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate (they are poorly described and have been closed)
- [x] The issue still exists against the latest stable version of Elementor.
- [x] An Elementor support specialist also reproduced the error and asked me to open a bug/feature ticket

## Description

**Screencasts of the issue**
The user has to scroll up every time he opens a new tab or accordion to be able to see the content.
Iphone X, iOS [https://www.loom.com/share/8ddb90dc903b47eb8d732c5eef93b601](https://www.loom.com/share/8ddb90dc903b47eb8d732c5eef93b601) 
Samsung S9, Firefox [https://www.loom.com/share/68665ef280ed4e249711603188f88370](https://www.loom.com/share/68665ef280ed4e249711603188f88370) 

**Normal behaviour**
Every time the user opens a tab, it should display the content from the top

**Widgets**
The issue happens with the:
- Tab widget
- Accordion widget

The issue doesn’t happen with the Toggle widget

**Devices/Browsers**
The issue is happening on the following devices/configuration:
- iPhone - safari (both tabs and accordion have the issue)
- Android - Firefox mobile browser (both tabs and accordion have the issue)
- Android - Android browser (tabs works, accordion not)
The issue is not happening in Chrome mobile

**Sites where this happens**
It seems to be a general Elementor issue and not related to our configuration as the problem happens on every site where we use Elementor, including our test server with only Elementor installed.
- Our live production site https://wingtra.com/mapping-drone-wingtraone/
- Our test site is private and cannot be shared here. Please contact me privately if you want the URL and password

## Steps to reproduce

1. Create a tabs or accordion widget
2. Add content inside (try with a longer text, 4-5 paragraphs)
3. Use an iphone with Safari browser
4. Click around to open and close the different tabs/accordion

You will notice that the user has to scroll up every time he opens a new tab to be able to see the content

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Log of our test site (not production site)

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.1.28
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://sandbox.wingtra.com
	Home URL: https://sandbox.wingtra.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.2.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

== Active Plugins ==
	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.6
		Author: Elementor.com

== Log ==
	: 
Log: showing 20 of 322019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-04-27 19:03:25 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-27 19:03:26 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-27 19:03:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.5',
)]
2019-04-30 12:54:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.12',
  'to' => '2.5.14',
)]
2019-04-30 12:56:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.5.6',
)]
</details>

**Comment by david-wingtra** [comment]
Hello,

thank you for the quick reply. Indeed bootstrap also works this way. But whatever if native or not, the point is that it is really bad usability. So I do not understand how you can justify not seeing the point of fixing this issue.

**Comment by ElColo** [comment]
I'm experiencing the exact same problem, and I too think it's bad usability. That said, I'll keep looking and report back if I have anything useful.

**Comment by Netzlichter** [comment]
I really don't get it why this ticket is closed. Users do not understand what is happening if you are using tabs on mobile phones...

**Comment by MohamedBouzid00** [comment]
Hi,
I am not sure if this still open.
I am not a programmer but I found an easy solution to keep going away. in those steps for all tabs.
Before tabs I insert a transparent spacer and, in advanced setting of element, 
in CSS ID : tabs-up-ID (Just an example)
Now you click on Tabs Item -- Title & Description
and you use ahref : 
1st tab (Description)
 <a href="#my-tabs-id">Description</a>  
2nd tab (Pictures)
 <a href="#my-tabs-id">Pictures</a>
So each time in phone you select a tab, content go back to the spacer, it mean to the begining or tabs.
It work fine now. 
I hope it will help someone who had same problem.

**Comment by david-wingtra** [comment]
Hi,

Wow thanks, that's a very creative work-around! I just tested it and it does work! Alternatively, instead of the empty spacer it is also possible to use the anchor widget.

Elementor should work on a proper solution though, as this work-around has some limitations:
- It works well on accordion with few tabs. With many tabs, then the user is being sent to the top of the accordion and not to the specific tab
- It works only if the user clicks on the tab title, it doesn't work when one clicks the arrow / chevron icon
- The HTML produced behind is not so clean, there are two links, one empty and one with the link to the anchor

**Comment by MohamedBouzid00** [comment]
I will keep trying other idea and I will write if I get better solutions. I have the same problem and for moment I hope that visitors by mobile click in title 🤷🏻‍♂️
Negative thing is that the solution is generating more links, that true but I guess the team of Elementor in some moment they will correct the issue.

**Comment by vb123ax** [comment]
> Hi,
> 
> Wow thanks, that's a very creative work-around! I just tested it and it does work! Alternatively, instead of the empty spacer it is also possible to use the anchor widget.
> 
> Elementor should work on a proper solution though, as this work-around has some limitations:
> 
> * It works well on accordion with few tabs. With many tabs, then the user is being sent to the top of the accordion and not to the specific tab
> * It works only if the user clicks on the tab title, it doesn't work when one clicks the arrow / chevron icon
> * The HTML produced behind is not so clean, there are two links, one empty and one with the link to the anchor

Hi, new to github and elementor.  I've run into the same issue.  I've tried making the title name on each tab a hyperlink that points to an anchor link inside its tab.  But for some reason depending on which one I click first it seems to work differently.  If I click one of the bottom tabs first then scroll back up and click on a tab above it, that newly clicked tab will open correctly.  But the first link I click will always scroll to the wrong place still.  If you have any idea why that may be or have found a better way to fix this scrolling issue, can you please let me know?  Thanks so much.

**Comment by bentographics** [comment]
I believe @MohamedBouzid00 solution doesn't work with the current tabs widget anymore. 

This is still an issue. It's very disorienting for users if they open a tab on mobile and the associated content jumps out of view. 

Strangely the behaviour is fine on desktop browsers if viewed at a mobile break point.

**Comment by cgn24** [comment]
If someone needs it, I found how to solve this problem. Adding this script to html field anywhere on your page.
Where "my-tabs" is a Tab-section ID (you can add it in the Advanced settings of tours Tabs). Works fine for desktop and mobile. 

For desktop and mobile:
<script>
document.addEventListener('DOMContentLoaded', function() {
    const tabButtons = document.querySelectorAll('#my-tabs .e-n-tab-title');

    tabButtons.forEach(function(button, index) {
        button.addEventListener('click', function() {
            // Wait for the content to change and then scroll
            setTimeout(function() {
                // Target the #tabs-kitchen div for scrolling
                const section = document.getElementById('my-tabs);
                if (section) {
                    section.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                } else {
                    console.error('Section not found!');
                }
            }, 300); // Adjust delay if needed
        });
    });
});
</script>


For mobile only:
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Media query to check if the screen width is less than or equal to 768px (adjustable)
    if (window.matchMedia('(max-width: 768px)').matches) {
        const tabButtons = document.querySelectorAll('#my-tabs .e-n-tab-title');

        tabButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                // Wait for the content to change and then scroll
                setTimeout(function() {
                    // Target the #tabs-kitchen div for scrolling
                    const section = document.getElementById('my-tabs');
                    if (section) {
                        section.scrollIntoView({
                            behavior: 'smooth',
                            block: 'start'
                        });
                    } else {
                        console.error('Section not found!');
                    }
                }, 300); // Adjust delay if needed
            });
        });
    }
});
</script>

**Comment by neerajjangir** [comment]
I', having the same issue so what if someone has hundreds of tabs on the page?
