### ISSUE TITLE
[Enhancement Request] Title widget with background-clip: text

### ISSUE THREAD

**Issue by vovkasolovev** [elementor/elementor#8002]
It would be great to have option to select image for masking the title with **background-clip: text** in Title widget and all other kinds of widgets with titles. This effect have unofficial support by all browsers now.

**Comment by shilo-ey** [comment]
I merged this issue with #4676, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
