### ISSUE TITLE
Bug with Repeater control

### ISSUE THREAD

**Issue by mauryaratan** [elementor/elementor#8004]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When adding a repeater field via action `elementor/element/after_section_end` there seems to the following error:
```js
Uncaught TypeError: Cannot read property 'set' of undefined
    at N.d.setEditSetting (editor.js:199)
    at N.d.updateActiveRow (editor.js:13968)
    at N.d.onAddChild (editor.js:14030)
    at Object._triggerMethod (backbone.marionette.js:690)
    at N.d.triggerMethod (backbone.marionette.js:1944)
    at N.d.addChild (backbone.marionette.js:2586)
    at N.d.<anonymous> (backbone.marionette.js:2418)
    at underscore.min.js:1
    at Function.s.each.s.forEach (underscore.min.js:1)
    at N.d.showCollection (backbone.marionette.js:2416)
```

When adding the same code per Element, for example `elementor/element/{$element}/{$section}/after_section_start`, it works flawlessly.

Here's the link to sample code used on [Gist](https://gist.github.com/mauryaratan/8ef33622abd4a3695f40652732014761).

Please let me know if you need any further information.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
<a href="https://pastebin.com/sDUUx7JB">https://pastebin.com/sDUUx7JB</a>
</details>

**Comment by bainternet** [comment]
@mauryaratan 

This is not a bug, it's simply a wrong use, You should never add a control outside of a section, and when you use `.../after_section_end` hook a section has already been closed. 

simply use the correct filters.

thanks.

**Comment by mauryaratan** [comment]
@bainternet I've now tried it with all possible filters 
- `../after_section_end`
- `../after_section_start`
- `../before_section_end`
- `../before_section_start`
with no luck :/

I've also tried it with and without `$element->start_controls_section()` given how the thrown errors suggest. Not sure what else to try.

Adding it to `before_section_start` make the section appear, but as soon as I toggle the section, I get the same JS error.

Think you can quickly suggest the right filter?

Btw, what I'm trying to do here is to add it inside Page Settings > Styles.

**Comment by Xammie** [comment]
I'm having the same exact issue. @mauryaratan have you found a solution?

**Comment by mauryaratan** [comment]
@Xammie Can't recall properly, but I probably ended up using `before_section_end`

https://github.com/mauryaratan/analogwp-templates/blob/cc1134c0b86eb3671d3e447fe75181dd3da3fdd5/inc/elementor/class-typography.php#L52
