### ISSUE TITLE
[BUG] Woocommerce variable product dropdown interfering with phlox

### ISSUE THREAD

**Issue by OliCey** [elementor/elementor#8008]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi,

I'm creating a webshop by using elementor Pro and the phlox template. When adding the Elementor add to cart widget (which also includes the variable product dropdowns) the dropdowns are not verry visible. Anyone any idea on how to solve this? 

![Screenshot from 2019-05-01 08-35-13](https://user-images.githubusercontent.com/50163645/57007866-15943880-6bec-11e9-99ed-aa0a4ccda20f.png)

**Comment by shilo-ey** [comment]
Hi @OliCey 

This issue has been resolved and will be released in the next Pro patch version.

Thanks

**Comment by OliCey** [comment]
Hi @shilo-ey ,

Thank you for the fast response.
Any idea when de next release is foreseen?
Thx,

Olivier

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor Pro v2.5.7

Feel free to update!
