### ISSUE TITLE
Popup widget bug: Form plugin Date/Time picker

### ISSUE THREAD

**Issue by froggstar** [elementor/elementor#8009]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

The elementor form provides a tab called "date", which inserts a date-picker. There is a bug when displaying this date-picker within a popup, and the pop-up settings are set to "close on overlay". When choosing a date, the date-picker is handled as a pop-up. Thus, the pop-up closes when one clicks anywhere within the date picker except for available dates. The same happens for the timeslot-picker. 

## Steps to reproduce

1. 
create a popup 
2. set the popup under advanced to "close on overlay"
3. Insert the form widget into the pop-up
4. set one of the form widget's tabs to "date" / "time"
5. update and preview
6. open the popup (if it does not automatically open)
7. choose a time slot / unavailable date or switch to next month
8. the popup will close

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @froggstar 
Thanks for your feedback,

This is not an issue. 
The datepicker is another popup on top of your existing one.
If you click outside of your popup - it will close, and that is exactly what happens.
You can set your popup not to be closed when clicking on the overlay and that will solve your issue (Popup settings > Advanced tab).

Thanks!

**Comment by IlPizza79** [comment]
Sorry to bump a closed topic, but I have the same issue... and I think this IS a issue.
Of course, "technically speaking" it's not an issue, but for any end-user the datepicker is INSIDE the modal, so it should not close the modal. I guess you should treath this problem as an issue.
Thanks!

**Comment by IlPizza79** [comment]
If someone is interested, it seems that adding "static: true" to flatpickr options fixes the issue.
You just need to add ".elementor-field-type-date .flatpickr-wrapper {width:100%;}" in your css.

**Comment by webdiner** [comment]
This is still an issue with jQuery Datepicker. Does anyone have a workaround or a fix?

**Comment by gravnetic** [comment]
jQery Datepicker selection closes the popup while leaving the date picker visible.  I am using a Gravity Form, but this is happening.

**Comment by abdulsamad544** [comment]
I was also facing this issue via Formidable forms datepicker field and found the solution to this problem when datepicker not works in Elementor popups.

Simply add an extra class to the "datepicker" field in the place provided by formidable forms to add extra classes.
