### ISSUE TITLE
Is there a way to send a backend email to either our Support team or Sales team when they select Support or Sales? 

### ISSUE THREAD

**Issue by JDr21** [elementor/elementor#8013]
Is there a way to send a backend email to either our Support team or Sales team when they select Support or Sales? 
[http://ebsta.moreapps.co.uk/about/contact](url)
So when they select from that dropdown is there a way of sending an email to support and sales after they submitted?

**Comment by shilo-ey** [comment]
Hi @JDr21 

Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

As for your question, you can achieve it by using [custom labels & values](https://docs.elementor.com/article/371-custom-labels-and-values), and with the select field shortcode as "to" address.

thanks.
