### ISSUE TITLE
Best way to write a plugin that adds dashboard functionality AND an elementor widget

### ISSUE THREAD

**Issue by bellamystudio** [elementor/elementor#8014]
I'm trying to build a simple notification plugin that adds some date fields to the dashboard so that an admin can publish a scheduled outage and it appear on the site. I want to handle the display with an elementor widget. I've written other elementor widgets before but I'm struggling with the mixed functionality here (ie dashboard level changes as well as frontend builder) - is there a demo plugin or some best practice that I can look at so that I can activate one plugin that handles both?

**Comment by bellamystudio** [comment]
More info: I've tried adding the dashboard functions inside the Plugin class, based on the demo elementor widget:
`class Plugin
{
...
 public function register_announcements()
    {`

But this gives me an error when I try to instantiate it (inside the __construct() function):
( ! ) Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'register_announcements' not found or invalid function name in wp-includes/class-wp-hook.php on line 286

Should I break this out into two plugins - one for the dash and one for Elementor?

**Comment by Aviad-Herman** [comment]
Hello @bellamystudio,
Due to the age of this ticket I assume it's no longer relevant so I'll close this issue.
Hope you figured it out ;-)
