### ISSUE TITLE
Feature request : Call To Action (link title)

### ISSUE THREAD

**Issue by fhfournier** [elementor/elementor#8017]
Hi,

For SEO friendly the widget "Call To action" should need a title attribute for link.

And the widget as a input field "Title & Description". So you should use it!

The render is perfect but if i look at the HTML source, i can't see the title attribute for the link.

![image](https://user-images.githubusercontent.com/3278753/57022282-a96e0080-6bfc-11e9-8355-e0ce407269fa.png)

Like
`<a href="..." title="Collecte résidentiel">...</a>`

![image](https://user-images.githubusercontent.com/3278753/57022216-79bef880-6bfc-11e9-9db2-9a4e10b042c3.png)

**Comment by lior-sh** [comment]
@fhfournier 


invalid Feature request
----
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread
Thanks.
