### ISSUE TITLE
Add control in Row & Column settings

### ISSUE THREAD

**Issue by alidemirci** [elementor/elementor#8018]
Hi Guys,

I want to add control group in row or column settings area. I search everywhere but nothing found about this. So i guess it doesn't exist. Could you guide me if this exist or please add this feature.

Have a nice day :)

**Comment by shilo-ey** [comment]
Hi @alidemirci 

Please read more [here](https://github.com/elementor/elementor/issues/7799), and [here](https://developers.elementor.com/register-widget-controls/).

Thanks.
