### ISSUE TITLE
Media Carousel, CSS ID for each image

### ISSUE THREAD

**Issue by thatdudepaco** [elementor/elementor#8022]
I got some Images which i want to refer to another image trough CSS ID.

The problem I face is that I can only give the whole Media carousel Section a CSS ID.

But I have 4 Images (icons) which i want to refer to each image in the Media carousel. But I do not have the possibility to give the images a CSS ID only the whole section.

Can you please fix this and add this feature?

kind regards

Paolo

**Comment by shilo-ey** [comment]
Hi @thatdudepaco 

You can achieve this with direct CSS selector, for example:

```CSS
div[data-swiper-slide-index="1"] {
    width: 100px !important;
}
```

Simply change the number to each of your slides.

Thanks

**Comment by thatdudepaco** [comment]
Hi Shilo-ey,

this is absolutely not working for me can you be more specific? Do i need to use some other codes too? Or maybe you can make a short clip of how/where to put it? Would be very useful then. :)

thanks

kind regards

Paolo

**Comment by shilo-ey** [comment]
Hi @thatdudepaco 

Each slide of swiper has data id ranging from 0 to the number of slides you have.

Add this code to your custom CSS in order to set the custom property you wish to achieve.

Thanks
