### ISSUE TITLE
Price comparison sets created by Datafeedr plugin not appearing when using Single Product template

### ISSUE THREAD

**Issue by tlofts** [elementor/elementor#8024]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I am setting up an affiliate marketing website (https://www.8k-tv.co.uk) and using the Datafeedr plugin to pull across product information and prices to Woocommerce Products. One of the great features of the plugin is the ability to display price comparison sets and although I can get them to work by manually adding a shortcode to a page, they are not automatically appearing when displaying the product pages which are created in Elementor Pro using the Single Product template.

I have contacted Datafeedr and they have said they can provide the necessary code if you are able to provide details of which hooks are available when creating product pages to display additional content for the product.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by EricBusch** [comment]
Hi Elementor Devs,

This is Eric from Datafeedr.com.

What action hooks are available to display content on a page created by Elementor Pro using the Single Product template?

Thanks
Eric

**Comment by lior-sh** [comment]
@tlofts 


Not support
----
Thanks,
Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.
