### ISSUE TITLE
Elementor stuck on loading screen

### ISSUE THREAD

**Issue by CarsonCollins** [elementor/elementor#8025]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

 When I try to open Elementor (not Pro) it gets stuck on the loading screen. I’ve done all the recommended troubleshooting and nothing has worked. I really need this fixed for work.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ --> 


Log: showing 1 of 1
--
2019-04-26 19:49:06 [info] Elementor data updater process has been completed. [array (   'plugin' => 'Elementor',   'from' => '2.4.0',   'to' => '2.5.14', )]


JS: showing 2 of 2
--
JS: 2019-04-29 14:42:16 [error X 70][https://www.infolob.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:83715] Can\'t find variable: ElementorConfig
JS: 2019-04-30 16:21:07 [error X 3][https://www.infolob.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:83700] ElementorConfig is not defined
```
</details>

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
