### ISSUE TITLE
CHANGE POST WIDGET

### ISSUE THREAD

**Issue by hasnbzk** [elementor/elementor#8026]
Hello,

how I could modify [the post widget](https://1drv.ms/u/s!AriOeGr25LyygawthP0mHX_-wUzqqQ) to put [this informations](https://1drv.ms/u/s!AriOeGr25LyygawuwV8U7ZDmI0yyVw) on the home page ?

king regards.

**Comment by GertjanTanghe-KoomBanaBay** [comment]
With which plugin you've built the custom fields?

**Comment by hasnbzk** [comment]
Now i am just in Elemntor pro to built the page.

**Comment by lior-sh** [comment]
@hasnbzk 


Not support
----
Thanks,
Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.
