### ISSUE TITLE
Elementor latest doesn't work with script_loader_tag filter

### ISSUE THREAD

**Issue by carasmo** [elementor/elementor#8027]
This filter doesn't work with Elementor.

https://developer.wordpress.org/reference/hooks/script_loader_tag/

    add_filter( 'script_loader_tag', 'clean_script_tag'  );
    /**
     * Clean up output of <script> tags on local loaded
     * Does not work on some plugins that don't use the correct WP way
     * Localization also does not apply
     */
    function clean_script_tag( $input ) {
        $input = str_replace( "type='text/javascript' ", '', $input );
        return str_replace( "'", '"', $input );
    }

**Comment by carasmo** [comment]
Just a note that with this filter you can't edit with Elementor and there's not anything to tell you what's wrong.

**Comment by ofmarconi** [comment]
@carasmo and how did you solve it?

I need to modify some scripts like this example with jQuery:
https://wordpress.stackexchange.com/questions/358679/disable-cloudflare-rocket-loader-for-jquery-javascript-and-make-it-load-first

**Comment by ofmarconi** [comment]
I'm in need of the same solution.
