### ISSUE TITLE
Fields Position, Attachment, etc. do not appear unless the selected picture for Desktop in the responsive control Image

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#8030]
Description:
I need to set the background image in the column for mobile resolution, but not for desktop and tablet. In this case, the choice of image for mobile does not show the fields to select 'Position', 'Attachment', etc. because when you create these fields do not have parameters 'device_args'.

Video showing the problem: https://www.screencast.com/t/13e68We4FdRJ

**Comment by lior-sh** [comment]
@VadymPogorelov 


invalid issue report
----
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
