### ISSUE TITLE
Integration of Toolset Post Reference Fields in Elementor Template pages

### ISSUE THREAD

**Issue by Barns-be** [elementor/elementor#8033]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Possibility to integrate Toolset Post Reference Fields in an Elementor Template page.

**Describe the solution you'd like**
Just like other Toolset Fields (text, URL, date..), be able to select a Post Reference Field from the Toolset Fields dropdown, so I can insert the text of this field (with a link to it).

**Describe alternatives you've considered**
None.

**Additional context**
I've checked https://docs.elementor.com/article/384-elementor-integration-with-toolset and noticed you don't support this yet. Hopefully this will be added in the near future?

**Comment by arielk** [comment]
Due to the fact that [Toolset stops releasing new features](https://toolset.com/2022/06/whats-next-for-toolset/), we are currently suspending all requests for integration with Toolset, if the status will change in the future we can reopen it.

Thanks for your feedback!
