### ISSUE TITLE
Ajax in Popup not working

### ISSUE THREAD

**Issue by Felipe-NS** [elementor/elementor#8039]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Ajax search don't work on elementor Popup. Don't matter the popup configuration or triggers.

Here you can read about a similar problem: https://wordpress.org/support/topic/elementor-bug-with-popups/#post-11490612 

## Steps to reproduce

- Install Ajax Search Lite(I don't know about other ajax plugins)
- Create a popup in Elementor and add the Ajax search
- Do a preview or publish the popup

**Comment by shilo-ey** [comment]
Hi @Felipe-NS 

We do not provide support for 3rd party plugins. please contact their support.

Thanks.
