### ISSUE TITLE
Coding Hint on Creating Advanced rule for Pop UP

### ISSUE THREAD

**Issue by MohiuddinSumon** [elementor/elementor#8040]
Hi, 
I am trying to add an advanced_rule in elementor popup section. As you know there is only option 'Hide for logged in users' what I am adding is 'Show for logged in users'. I have added the front end option from timing.php file and it shows like this: 
![image](https://user-images.githubusercontent.com/10167383/57188620-8062ae00-6f23-11e9-89e8-03c341526a16.png)

Now I just want to know where can I find the codes that works against this function. Like where is the code that execute when 'Hide for logged in users' is selected.

If someone can give me a control flow of code then it would be very helpful. More specifically Where Should I put My Custom code/ functions. 

my plan is something like this might solve my issue:

```
if( ! empty( $par['users_show'] ) ) 
{
	$is_user_logged = is_user_logged_in();
	if ( in_array( 'Admin', $par['roles_show'] ) ) 
	{
		if ( $is_user_logged == false) 
		{
			return false;
		}
	} 
	elseif ( in_array( 'User', $par['roles_show'] ) ) 
	{
		if ( $is_user_logged == true) 
		{
			return false;
		}
	} 
	else 
	{
		if ( $is_user_logged == false ) 
		{
			return true;
		}
		$user = wp_get_current_user();

		foreach ( $par['roles_show'] as $setting ) 
		{
			if ( in_array( $setting, (array) $user->roles ) ) 
			{
				return false;
			}
		}
	}
}

```

But any advice is welcomed.
Thanks,
Mohiuddin Sumon.

**Comment by lior-sh** [comment]
@MohiuddinSumon 

Not support
----
Thanks,
Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.

**Comment by fishnyc22** [comment]
@MohiuddinSumon did you ever figure this out. Looking to do the same thing. Thanks.

**Comment by MohiuddinSumon** [comment]
> @MohiuddinSumon did you ever figure this out. Looking to do the same thing. Thanks. 

In the end I used other plugin for this.
