### ISSUE TITLE
See what plugin added each of the elements on search

### ISSUE THREAD

**Issue by DIntriglia** [elementor/elementor#8043]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When searching for an element, having multiple add on packs installed, you have search results that all have the same name, but are from different plugins. 

**Describe the solution you'd like**
While some have different icons, it would be very nice to instead make the search results show which group they are from, so a from builder from PAFE will show PAFE above the title as that’s the group it is categorized in, instead of Simply showing a generic name that multiple plugins use. 

**Describe alternatives you've considered**
Due to the dynamic nature of the group names, the only concern I would have with doing the solution I outlined was due to a really long title. Another option is you simply use the group view still, instead of removing the groups from the search screen. If no elements are found that match a search query, the entire group including the group name is hidden. 

**Additional context**
Would love to continue thinking about this solution as having to tell my developers which “Form” to use when there are four different ones is very difficult as I have to describe the icon of the one we use, instead of simply saying the normal “General” form.

**Comment by shilo-ey** [comment]
When registering new widgets the flexible developers API allow creating a new section for differentiating the 3rd party widgets from the core widgets.

Therefore, this request should be directed to the 3rd party developers and not here.

Thanks.

**Comment by DIntriglia** [comment]
I was referring to the search part of Elementor, which removes all groups whenever you search for anything.
