### ISSUE TITLE
Tablet responsiveness (products columns)

### ISSUE THREAD

**Issue by denisbrais29** [elementor/elementor#8046]
As soon as i get on tablet mod i get this weird bug but on other devices like, phone or computer everything works just fine. I would really appreciate some help.
Link:  https://idealrent.be/

![elementor issue pc](https://user-images.githubusercontent.com/49476136/57202579-0d028000-6fa7-11e9-9310-548d5a478136.PNG)
![elementor issue](https://user-images.githubusercontent.com/49476136/57202580-0d028000-6fa7-11e9-8cf2-acac0980a84a.PNG)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
