### ISSUE TITLE
MIssing option to display label & field on the same line

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#8048]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

I want to have the label & field value on the same line: `name: [filed value]`
The interface does not have checkbox.
In the CSS I can see the `elementor-labels-above` selector which gives me the required result when removed.

I also searched the documentation with no luck.
Is this a BUG or am I missing something??

## Steps to reproduce

Just build a form and try to set label & form field on the same line.
I need the label

## Isolating the problem

- [Yes ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ Yes] This bug happens with a default WordPress theme active.
- [ Yes] I can reproduce this bug consistently using the steps above.

## Environment

Latest WP, Elementor, Elementor Pro, Hello theme.

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback

**Comment by grounch** [comment]
Hi is there any update on this? It's really a shame to not have such a basic and essential functionnality in elementor..
