### ISSUE TITLE
Developer Docs Syntax Highlighting

### ISSUE THREAD

**Issue by daviddunnington** [elementor/elementor#8049]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate

**What problem is your feature request going to solve? Please describe.**
Will make the developer docs easier to read and navigate.

**Describe the solution you'd like**
I would like to ask for Syntax highlighting adding to the developer docs. 

**Additional context**
The developer docs are absolutely brilliant but I find myself sometimes just needing a snippet of the code however, it's quite difficult to read through and find what I need without copying the entire code to an editor.

**Comment by bainternet** [comment]
@daviddunnington 

This is something we are looking at implementing,

thanks for the suggestion.
