### ISSUE TITLE
Forms: allow label only elements

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#8050]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a questionnaire (survey) with many questions.
There is no way to set titles to sections of the form.

**Describe the solution you'd like**
A title, implemented as "label only" element - can easily do the trick.
Preferrably, with option to set h2, h3 headings etc...
Idealy, allow (almost) any widget between the form fields (e.g. Tiles, Text, Image, at first... )

**Describe alternatives you've considered**
Other form plugins or even Google Forms.

**Additional context**
Currently form widget is for simple forms.
Questionnaire (survey or quiz) may be the next level.
My suggestion is simple. Allowing gradual progrgress towards more complex forms.

**Comment by bainternet** [comment]
@Mulli 

You Can use the HTML field type for exactly that, which in the next version will also get some typography control.

thanks.

**Comment by Mulli** [comment]
GREAT. Thanks. Smart. I did not notice it in the long list of elements.
