### ISSUE TITLE
🔃 🚀 Feature Request: Global "Style" Widget (Merged with #5252)

### ISSUE THREAD

**Issue by Stml-St** [elementor/elementor#8051]
### Global Widget Button (1. "Unlink Content." and 2. "Unlink Style" )

[x] I have searched for similar issues in both open and closed tickets and cannot find a exact duplicate. (I think feature request #1810 did not mean the "Groupselection"- feature request(#912) it was merged to by arielk)

As a feature request I think of two unlink buttons for Global Widgets that say something like this:
1. "Unlink Content." and 2. "Unlink Style" 

I dont know how complicated this would be but i think it would be a very great addition to global widgets workflow. And it would speed up sitecreation a lot. Because with this feature i can use GlobalWidgets from the beginning of the designprocess and i dont have to copy and paste widegtstyles for every single widget on every single page when just some "global" style has to be changed.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/5252 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
