### ISSUE TITLE
Javascript don't work in modal pop elementor

### ISSUE THREAD

**Issue by corke** [elementor/elementor#8057]
Hello !

I used your feature for making a pop up, then inside this pop up I have put a text with an id and I have create a JS function when I over the text it's show me a message in the console.

When I use this outside the pop up all work fine. But when it's inside the pop up that don't work : /

You have an idea ?

My code JS :

jQuery.noConflict();
console.log("display mega");
setTimeout(test, 10);

function test() {

    jQuery( '#testtest' ).hover(function() {
                console.log('show mega');
    });

}

So this code work fine on normal page but not in pop up

thanks !

Best regards

**Comment by shilo-ey** [comment]
Hi @corke 

Currently, you can achieve this by using a custom code each time a popup is activated by using jQuery.

e.g:
```JS
jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
    if ( document.getModal ) { // It's a popup document
        document.getModal().on( 'show', () => {
            console.log( 'Run your script here' );
        } );
    }
} );
```

Thanks

**Comment by corke** [comment]
Hi @shilo-ey 

Oh nice ! Big thank you :)

**Comment by corke** [comment]
@shilo-ey 
not working : /
https://gyazo.com/62f986a2d63c6135281f7ad7e4cdec52

**Comment by formulaclick** [comment]
@shilo-ey Is not available a cleaner method to catch the popup open event without having to use setTimeout? Anyway, the code you suggested is not working for my popup. Any working example?

**Comment by shilo-ey** [comment]
If you can hook it after the content is fully loaded - you can just use this:
```JS
jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
			if ( document.getModal ) { // It's a popup document
				document.getModal().on( 'show', () => {
					console.log( 'Run your script here' );
				} );
			}
		} );
```

But we gave it as a general implementation without knowing what is the loading order of the website.

**Comment by formulaclick** [comment]
It worked for me like this:

`
			jQuery(window).load(function() {
				jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
					if ( document.getModal ) { // It's a popup document
						document.getModal().on( 'show', () => {
							console.log( 'Run your script here' );
						} );
					}
				});
			});	
`

Thanks!

**Comment by corke** [comment]
Hello guys,

In my side, I add JS file like this in function.php :

```
function enqueue_js() {
//Charger le script du mega menu
wp_enqueue_script( 'pop-up-switch', get_stylesheet_directory_uri()  . '/js/switch-login-registration.js', array() );
}
add_action('wp_enqueue_scripts','enqueue_js');
```
And with the settimeout it's work fine for me ! but without no, so maybe I call bad my JS file ?

thanks for the help anyway help me to do very nice things :) 

best

**Comment by IlPizza79** [comment]
> ```
> 			jQuery(window).load(function() {
> 				jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
> 					if ( document.getModal ) { // It's a popup document
> 						document.getModal().on( 'show', () => {
> 							console.log( 'Run your script here' );
> 						} );
> 					}
> 				});
> 			});	
> ```

Thanks, this one it's working also for me :-)
Just a question: this code will add my script to every popup document, right? Is there a way to add my script to only one popup document with a specific class/id?
Thanks :-)

**Comment by formulaclick** [comment]
@IlPizza79 that's right, you should specify using popup ID:

`jQuery(window).load(function() {
				jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
					if ( document.getModal && id == 12345) { // It's a popup document
						document.getModal().on( 'show', () => {
							console.log( 'Run your script here' );
						} );
					}
				});
			});	`

Change 12345 with your popup post ID

**Comment by Angiolettocoppola** [comment]
Hi, i have the same problem. I want to open a booking form in javascript in elementor popup but it dosn't work.  
This is my code: 
`<script type="text/javascript">
(function (i, s, o, g, r, a, m) {
    i['SBSyncroBoxParam'] = r; i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
    m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
})(window, document, 'script', 'https://cdn.simplebooking.it/search-box-script.axd?IDA=1234','SBSyncroBox');
</script>`

To load a booking form in a page i use this html code: <div id="sb-container"></div> 

I'm not sure how to insert this in the suggested code, please can you help me with right code for function.php

**Comment by rafaviana** [comment]
> It worked for me like this:
> 
> ```
> 			jQuery(window).load(function() {
> 				jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
> 					if ( document.getModal ) { // It's a popup document
> 						document.getModal().on( 'show', () => {
> 							console.log( 'Run your script here' );
> 						} );
> 					}
> 				});
> 			});	
> ```
> 
> Thanks!

Hi! This function is running well when I click to open the popup (because I can see the console log) BUT the Gravity Form I have embed inside the popup doesn't work at the first try I submit the form, it only submit the form when I press the submit button again...

**Comment by Khudoyor-Rakhmatov** [comment]
> jQuery(window).load(function() {
> 				jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
> 					if ( document.getModal ) { // It's a popup document
> 						document.getModal().on( 'show', () => {
> 							console.log( 'Run your script here' );
> 						} );
> 					}
> 				});
> 			});

Where should I place the code? html widget or functions.php? Thanks

**Comment by Desiatnychuk** [comment]
Hello !

i used sript for fliating label CF7 its work greate on page but don't work in elementor popups. can you help me add script in elementor popups?

const formsWithAnimatedLabels = document.querySelectorAll(
    ".form-with-animated-labels"
);
const focusedClass = "focused";
 
for (const form of formsWithAnimatedLabels) {
    const formControls = form.querySelectorAll(
        '[type="text"], [type="email"], [type="tel"], textarea'
    );
    for (const formControl of formControls) {
        formControl.addEventListener("focus", function () {
            this.parentElement.nextElementSibling.classList.add(focusedClass);
        });
 
        formControl.addEventListener("blur", function () {
            if (!this.value) {
                this.parentElement.nextElementSibling.classList.remove(
                    focusedClass
                );
            }
        });
    }
 
 
    form.parentElement.addEventListener("wpcf7mailsent", function () {
        const labels = document.querySelectorAll(".focused");
        for (const label of labels) {
            label.classList.remove(focusedClass);
        }
    });
}


<ul>
  <li class="form-wrapper one-coloumn">
    [text* your-fullname class:field__input id:your-fullname placeholder "e.g. Albert"]
    <label for="your-fullname">Name</label>
    <span class="border"></span>
  </li>
  <li class="form-wrapper two-coloumn">
    [email* your-email class:field__input id:your-email placeholder "e.g. office@altadea.com"]
    <label for="your-email">Email</label>
  </li> 
<li class="form-wrapper one-coloumn">
    [text* your-city class:field__input id:your-city placeholder "e.g. Kyiv"]
    <label for="your-city">City</label>
    <span class="border"></span>
  </li>
  <li class="form-wrapper two-coloumn">
    [tel* your-phone class:field__input id:your-phone placeholder "e.g. +38 093 3414464"]
    <label for="your-phone">Phone</label>
  </li>
  <li class="form-wrapper form-textarea-wrapper one-coloumn">
    [textarea* your-message id:your-message]
    <label for="your-message">Message</label>
  </li>
  <li class="form-wrapper form-submit-wrapper">
    [submit "Send request"]
  </li>
</ul>

**Comment by kitsunecreativeco** [comment]
> @IlPizza79 that's right, you should specify using popup ID:
> 
> `jQuery(window).load(function() { jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => { if ( document.getModal && id == 12345) { // It's a popup document document.getModal().on( 'show', () => { console.log( 'Run your script here' ); } ); } }); }); `
> 
> Change 12345 with your popup post ID

Hi - I tried this but it doesn't seem to be working. I've replaced the ID with the elementor popup, and the code with the Klaviyo embed code (<div class="klaviyo-form-FORMID"></div> (obviously with the correct form ID) but it doesn't seem to be working. I have this same code in the HTML widget on the popup still and just replaced the original code with the one above between the script tags - have I entered something incorrectly somewhere? Will this note work with this kind of embed code?
