### ISSUE TITLE
action_hook elementor/element/after_section_end not working on newly added widgets after 2.4.7

### ISSUE THREAD

**Issue by NinjaCortez** [elementor/elementor#8062]
## Description

I have developed an integration for a plugin and Elementor that adds a custom settings panel to the Advanced tab for all elements (widgets, sections, etc).

I am adding this custom panel using the Elementor action_hook [elementor/element/after_section_end](https://code.elementor.com/hooks/elementor-element-after_section_end/) 

The Elementor functionality is being run in the Wordpress hook 
[plugins_loaded](https://codex.wordpress.org/Plugin_API/Action_Reference/plugins_loaded)

With the newer version of the plugin ( after 2.4.7 ) my panel is no longer appearing on newly added elements and only shows up after an element has been saved and the page refreshed.

## Steps to reproduce

1) Add a plugins_loaded hook
2) Add an elementor/element/after_section_end hook to the plugins_loaded hook
3) Within the elementor/element/after_section_end function add in custom panel and controls. Example triggering a function called **elementor_custom_advanced** :

```
public function elementor_custom_advanced( $section, $section_id, $args ){

	if( $section_id == 'section_advanced' || $section_id == '_section_style' ){

		#Start Custom Settings Section
		$section->start_controls_section( 'my_custom', array(
			'label' => __( 'My Custom', 'plugin-name' ),
			'tab' => \Elementor\Controls_Manager::TAB_ADVANCED
		 ) );

		$section->add_control( 'control-name', [
			'label' => __( 'Control Name', 'plugin-name' ),
			'type' => \Elementor\Controls_Manager::TEXT,
		 ] );

		#End Custom Settings Section
 		$section->end_controls_section();
	}
}
```

4) Add an element to the page
5) See that your "My Custom" panel does not appear under the Advanced Tab
6) Save the page
7) Refresh the page
8) See that your "My Custom" panel now appears on the saved element and any new element added after it's been saved

## Isolating the problem

- [x] This bug was not prevalent on the 2.4.7 version of Elementor and I can not recreate 
- [x] This bug now happens with both Elementor active and Elementor Pro (active or inactive).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above

**Comment by bainternet** [comment]
@NinjaCortez 	

just tested with this exact code:

```PHP
add_action( 'elementor/element/after_section_end', function( $section, $section_id ) {

	if ( 'section_advanced' === $section_id || '_section_style' === $section_id ) {
		#Start Custom Settings Section
		$section->start_controls_section(
			'my_custom',
			[
				'label' => __( 'My Custom', 'plugin-name' ),
				'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
			]
		);

		$section->add_control(
			'control-name',
			[
				'label' => __( 'Control Name', 'plugin-name' ),
				'type' => \Elementor\Controls_Manager::TEXT,
			]
		);

		#End Custom Settings Section
		$section->end_controls_section();
	}
}, 10, 2 );
```

every thing works as expected.

if we can't replicate we can't help, please contact our support at support @elementor.com with the full code and steps to replicate for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
