### ISSUE TITLE
Extend default widgets

### ISSUE THREAD

**Issue by assadnazar** [elementor/elementor#8065]
I want to add a control in default widgets e.g Posts and the control will be a button used to link to the post single page. Lets call it Read More button.

How can i hook into "Content Section" of Post widget and add the control and finally render it?

**Comment by lior-sh** [comment]
@assadnazar 

Not support
----
Thanks,
Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.
