### ISSUE TITLE
Uncaught ReferenceError: elementorFrontend is not defined

### ISSUE THREAD

**Issue by corke** [elementor/elementor#8070]
Someone tell me to use this for using scrip inside elementor popup, but I have this error : 
Uncaught ReferenceError: elementorFrontend is not defined

thanks

jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
    if ( document.getModal ) { // It's a popup document
        document.getModal().on( 'show', () => {
            console.log( 'Run your script here' );
        } );
    }
} );

**Comment by shilo-ey** [comment]
@corke 

You will need to use it after the page fully loaded.
Try adding `setTimeout` interval to this:

```PHP
/* Describe what the code snippet does so you can remember later on */
add_action('wp_footer', 'footer_popup_action');
function footer_popup_action(){
?>
	<script>
	setTimeout(() => {
		jQuery(document).ready(function($) {
		jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
			if ( document.getModal ) { // It's a popup document
				document.getModal().on( 'show', () => {
					console.log( 'Run your script here' );
				} );
			}
		} );
	});
	}, 2000);
	</script>
<?php
};```

**Comment by aktarujjman** [comment]
Try to wrap your code inside this
```
if( typeof elementorFrontend !== 'undefined'  ){
    //Your code here
}
```

**Comment by corke** [comment]
Hello,

@aktarujjman with this code I don't have error but the script isnt runing haha.

The solution actually work is with the settimeout : 

`setTimeout(() => {
	jQuery(document).ready(function($) {
		jQuery.each( elementorFrontend.documentsManager.documents, ( id, document ) => {
			if ( document.getModal ) { // It's a popup document
				document.getModal().on( 'show', () => {
					console.log( 'Run your script here' );

				} );
			}
		});
	});
}, 2000);

Thanks for your help !`

**Comment by DJviolin** [comment]
PSA: It took a day to figure out, but maybe useful for others. After developing in localhost, I launched my site and got this console error when I clicked on my popup links. It was my adblock plugin that caused this, blocking a google maps resource for a UAEL block...

**Comment by ido4491** [comment]
Timeout is a bad practice. is there an hook or event we can listen to that will notify when the elementorFrontend is ready??

**Comment by chrisschwartze** [comment]
> Timeout is a bad practice to solve this problem. is there an hook or event we can listen to that will notify when the elementorFrontend is ready??

There's the `init` hook https://code.elementor.com/js-hooks/

**Comment by Rayraz** [comment]
I'm still not sure if this is the 'correct' way, but this seems to work for me without hideous hack such as timeouts:

```JavaScript
// Fires when document is ready
$(function() {

    // Define your startup function
    var start = function() {
        // Startup code goes here...
    };

    // Elementor hooks are available, you're probably in the editor
    if(typeof elementorFrontend.hooks !== 'undefined') {

        // This hook will call your startup function when your widget is ready
        elementorFrontend.hooks.addAction( 'frontend/element_ready/{elementType.skinName}', start);
    }
    // Elementor hooks aren't available, you're probably on the front-end of your website
    else {

        // Call your startup function
        start();
    }
});
```

**Comment by szaleq** [comment]
I know it's been two years now, but for anyone who came here from Google, like me:

The proper solution would be to make sure that the Elementor Frontend script is enqueued BEFORE your script which makes use of `window.elementorFrontend` global. To make this happen include `elementor-frontend` in your script's dependencies while registering or enqueueing your script:

```php
wp_enqueue_script(
    'your-script-handle',
    'your-script-src.js',
    ['elementor-frontend'] // Dependency array containing `elementor-frontend` does the trick.
);
```

This way, the global `window.elementorFrontend` variable gets set BEFORE your script is run, so it's always available in your entire script.

**Comment by RosAtMAKS** [comment]
Check if plugins like WP-Rocket are enabled. I disabled it and now everything works fine. There are so many potential causes and solutions to consider.

**Comment by frempongandrews** [comment]
I solved it on the surface: I simply used css to hide the loading panel by inspecting with chrome inspector. but it will show again if the page reloads; so if you always want to hide it, use something like fluentSnippets and setting in the css: 

#elementor-panel-state-loading{
    display: none !important;
} 

Hope that helps
