### ISSUE TITLE
Woocommerce Cross-Selling widget

### ISSUE THREAD

**Issue by kevinleclerc-com** [elementor/elementor#8071]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I team, 
Current version of E.P. have a "Woocommerce Up-Selling widget" and a "Woocommerce Related Product widget".  But it lacks a "Woocommerce Cross-Selling widget" to build a complete "classic" e-commerce single product page. 

The related product widget can be use as a cross-selling feature, but we don't have the complete control on wich product it display. 

**Describe alternatives you've considered**
A way to displaying cross-selling on a product page currently is to use woocommerce related product widget with the WooCommerce Custom Related Products plugin (https://fr.wordpress.org/plugins/woo-custom-related-products/) 

It's working. But it will be cool to have the option directly with an Elementor Widget

**Additional context**
screenshoot :

1. the cross selling option which will be cool to have a widget for 
 http://prntscr.com/nm2wep

2. A way to control the related product which are displaying on a product page with the WooCommerce Custom Related Products plugin
http://prntscr.com/nm30tw

3. The custom (controlled) related product on a product page with elementor related product widget and WooCommerce Custom Related Products plugin
http://prntscr.com/nm3270

**Comment by stannvanheusden** [comment]
Please give this issue/request priority. The "Related products" widget doesn't show related products, but only random products. It should give priority to cross-sells set in WooCommerce.

**Comment by ellomumsy** [comment]
I would like this widget, too. I want to be able to control which products show up as related (which cross sells does).

**Comment by tomeda** [comment]
Also would like to see cross sales widget available...

**Comment by knireis** [comment]
me too

**Comment by nesoor** [comment]
I was looking for the cross sell block and couldn't find it until I stumbled on this topic which surprised me that there actually isn't a cross sell block available yet for Elementor.

**Comment by davidamarek** [comment]
+1

**Comment by Barns-be** [comment]
+1

**Comment by jrswebdesign** [comment]
Hi, i have a Elementor Widget for Cross Selling

Let me know if you want to use it.

<img width="273" alt="Schermafbeelding 2020-07-25 om 17 57 51" src="https://user-images.githubusercontent.com/25005457/88460974-7f0eff80-cea0-11ea-8109-60505c5aa8b8.png">

**Comment by AnaMS20** [comment]
Hi @jrswebdesign, 

Could I use that widget, please?

Thank you, 

Ana

**Comment by jrswebdesign** [comment]
Hi @AnaMS20,

Send us e-mail @info@jrs-webdesign.nl

Thanks

**Comment by AnaMS20** [comment]
Done, thank you! :)

**Comment by paandittya** [comment]
+1

**Comment by pixelicous** [comment]
@jrswebdesign hey, any chance i can get a hold of this widget as well?

This is such a basic functionality for an ecommerce shop, too bad elementor doesnt provide this.. (finding so many things that aren't supported lately)

**Comment by Chris-Gett** [comment]
Hi @jrswebdesign may i get the widget to?

**Comment by giuliano-gvnn** [comment]
Hi @jrswebdesign would it be possible to try your widget?

**Comment by davidamarek** [comment]
Hi @jrswebdesign, I'd love to try this too please.

**Comment by spajar** [comment]
Hi @jrswebdesign, keen to try your widget!

**Comment by MindwireAustralia** [comment]
+1 for this. Need a cross-sell widget! Strange how it has been omitted from from Elementor Pro for this long.
@jrswebdesign, I'm very keen to try your widget.

**Comment by amjulash** [comment]
This worked for me using posts widget. First, add the function and then apply query 'cross_sell_products' in Query ID. Source must be Products and include by should be empty.

```
add_action( 'elementor/query/cross_sell_products', function( $query ) {
	
	// Get WooCommerce Global
	global $woocommerce;

	$crosssells = get_post_meta( get_the_ID(), '_crosssell_ids',true);

    if(empty($crosssells)){
        return;
    }

	$query->set( 'post__in', $crosssells );

});
```

**Comment by knireis** [comment]
+1 for the widget. Can anyone share it? The above code only works on a product page, not on the cartpage

**Comment by Dudeney95** [comment]
@amjulash I don't suppose you have a custom query filter for Upsells too please? I know there is an upsells widget but this is very limited in terms of styling. By using the posts widget, we can set a custom skin where with upsells you cannot.
Please do let me know if it possible for upsells

**Comment by ashbryant** [comment]
@amjulash It doesn't seem to work. Any advice? I followed your instructions.

**Comment by amjulash** [comment]
> @amjulash It doesn't seem to work. Any advice? I followed your instructions.

@ashbryant I just did it again with the same code on another new website. For me, it worked just fine. I copy/paste the same code from above and here is the result https://ibb.co/86svf4f

FYI, the post layout in the screenshot is elementor's default classic layout. Will use ele-custom-skin to make it look better later.

**Comment by 79ho3ein** [comment]
+1

**Comment by 79ho3ein** [comment]
**This is excellent as well as required. But one point.** You do not need to add a new widget to add this feature. Instead, it is better to develop a query section in the products widget. The Jet woobuilder plugin has done a great job in this regard. I think elementor should be modeled on this plugin.
The jet woobuilder plugin has a widget called product grid, which is great and displays products in grid and carousel. Displays the grid by default, but if we want to display products as a carousel, we enable the carousel option.

This widget (jet woobuilder product grid), like the products widget in elementor, has a section called query in its settings. And it has very useful queries. Such as: category, sale, featured, related, cross sell, up sell, bestseller and most recently visited.
**This is clever. Multiple queries in one widget!**  I think so far elementor has gone the wrong way. It is not interesting to create a separate widget for each query.
I ask elementor developers to please check the product grid widget of the jet woobuilder plugin. Both in terms of customization and features. It is incredibly powerful. Please consider this. This is an important part of WooCommerce development in elementor. @arielk , @avivu 

thank you

**Comment by MindwireAustralia** [comment]
> **This is excellent as well as required. But one point.** You do not need to add a new widget to add this feature. Instead, it is better to develop a query section in the products widget. The Jet woobuilder plugin has done a great job in this regard. I think elementor should be modeled on this plugin. The jet woobuilder plugin has a widget called product grid, which is great and displays products in grid and carousel. Displays the grid by default, but if we want to display products as a carousel, we enable the carousel option.
> 
> This widget (jet woobuilder product grid), like the products widget in elementor, has a section called query in its settings. And it has very useful queries. Such as: category, sale, featured, related, cross sell, up sell, bestseller and most recently visited. **This is clever. Multiple queries in one widget!** I think so far elementor has gone the wrong way. It is not interesting to create a separate widget for each query. I ask elementor developers to please check the product grid widget of the jet woobuilder plugin. Both in terms of customization and features. It is incredibly powerful. Please consider this. This is an important part of WooCommerce development in elementor. @arielk , @avivu
> 
> thank you

This is the most user-friendly, logical and simple solution. If I were building a "listing" widget, that is how I would build it. **Elementor:** can you please implement this natively instead of us having to go to 3rd party widgets for basic things like this?

**Comment by inspiredearth** [comment]
+1
Astounding this hasn't yet been implemented.

**Comment by Traeonna** [comment]
> Hi, i have a Elementor Widget for Cross Selling
> 
> Let me know if you want to use it.
> 
> <img alt="Schermafbeelding 2020-07-25 om 17 57 51" width="273" src="https://user-images.githubusercontent.com/25005457/88460974-7f0eff80-cea0-11ea-8109-60505c5aa8b8.png">

OMG, I've been looking all over for a cross-selling widget for Elementor/Woocommerce.

**Comment by kincau2** [comment]
> This worked for me using posts widget. First, add the function and then apply query 'cross_sell_products' in Query ID. Source must be Manual Selection.
> 
> ```
> add_action( 'elementor/query/cross_sell_products', function( $query ) {
> 	
> 	// Get WooCommerce Global
> 	global $woocommerce;
> 
> 	$crosssells = get_post_meta( get_the_ID(), '_crosssell_ids',true);
> 
>     if(empty($crosssells)){
>         return;
>     }
> 
> 	$query->set( 'post__in', $crosssells );
> 
> });
> ```

This code works well on single product page. For those who would like to display cross sell item on cart page using elementor widgets, here is my little modification on it.

`add_action( 'elementor/query/cross_sell_products', function( $query ) {
	
	$crosssells = array();
	
	foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
		$product_id = $cart_item['product_id'];
		$crosssells = array_merge($crosssells,get_post_meta( $product_id , '_crosssell_ids',true)); 
	}

    if(empty($crosssells)){
        return;
    }

	$query->set( 'post__in', $crosssells );

});`

Please dont forget to select "product" as source under query tab of post widget and input "cross_sell_products" on Query ID.

The only bad thing is it doesnt have add to cart button. If anyone can provide a better workaround on this I would be much appreciated.

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Comment by Traeonna** [comment]
> Hello, This issue has been resolved in Elementor Pro v3.7.0
> 
> Feel free to update
> 
> Thanks!

However, it isn't working properly. Nothing shows up! I am assuming this is the Products widget and under Query you select Cross-Sells as the Source. I did this and none of my cross-sells are showing.

**Comment by ChrisASearles** [comment]
I'm also having issues with this. I have a couple of items showing up when I select Cross Sells but they're not the cross sell items defined for the product.

**Comment by zdeem** [comment]
Issue still persists..

**Comment by sequoi** [comment]
This is true! It doesn't work at all. Changelog from 3.7.0 says this:

_Tweak: Added Related, Upsells and Cross-Sells query sources to Products widget ([#8071](https://github.com/elementor/elementor/issues/8071))_

You add a product widget to Single Product template, you select Cross-Sell as a query source, and the product has defined cross-sells items but on the front end or on the backend (editor) - NOTHING is showing.

Clearly, this is not working as others pointed out.

**Comment by sequoi** [comment]
Update: found this info when digging more:

"Note: The Cross-Sells Query is available when creating a Cart page"

So it seems they think this is only useful when the user is on the Cart page. While this has some logic, can someone explain how can we offer "cross-sells" items when the user is browsing the Product page? I mean why limit this only to a Cart page while clearly, we want to offer our buyers cross-sell products while they are visiting the Product page (Single Product template)

**Comment by sequoi** [comment]
Yep - working perfectly.

**Comment by Sophie-2e** [comment]
+1 to make the cross sell query work on single product template

**Comment by Sophie-2e** [comment]
Any update on this as it still does not work even after updating to 3.18.3 and Pro 3.18.4?

**Comment by Studiostekker** [comment]
> Hello, This issue has been resolved in Elementor Pro v3.7.0
> 
> Feel free to update
> 
> Thanks!

It's not resolved, since the OP asked about cross sells on the Single product page; where it's still not showing.

**Comment by Studiostekker** [comment]
I personally fixed it in the following way. 

My single page has spot for 'Related products' which the customer will define themselves with Upsells. 
And I had to show accessories using cross-sells. 

Since the related products are 'unused', I rewrote that query to show the cross-sells as following;

```
add_filter( 'woocommerce_related_products', 'stekker_make_related_products_crosssells', 10, 3 );
function stekker_make_related_products_crosssells( $related_posts, $product_id, $args ) {
	$crosssells = get_post_meta( get_the_ID(), '_crosssell_ids',true);

	$posts_ids = get_posts( array(
		'post_type'      => 'product',
		'posts_per_page' => -1,
		'post__in'       => $crosssells
	) );

	return count($posts_ids) > 0 ? $posts_ids : $related_posts;
}

```

**Comment by LaunchPad-GroundCrew** [comment]
> Hi, i have a Elementor Widget for Cross Selling
> 
> Let me know if you want to use it.
> 
> <img alt="Schermafbeelding 2020-07-25 om 17 57 51" width="273" src="https://user-images.githubusercontent.com/25005457/88460974-7f0eff80-cea0-11ea-8109-60505c5aa8b8.png">

Hi - would love to have a copy of your Cross Sell Widget.
