### ISSUE TITLE
Filter Bar - Is not resposive 

### ISSUE THREAD

**Issue by tilnox** [elementor/elementor#8072]
### **Filter bar-Portfolio Widget**

The filter bar responsiveness, is non existen.
On mobile the _categories filters_, just piled up, it looks terrible, and worse, users have no way to edit that section.

![image](https://user-images.githubusercontent.com/49846018/57395997-4e6e7780-71c1-11e9-8270-9c48ca000ef5.png)

![Screen Shot 2019-05-08 at 04 13 47](https://user-images.githubusercontent.com/49846018/57346948-7a99e200-7148-11e9-9ef3-87e1ed3583d5.png)

**heres one solution that can be implemented**

on Desktop
![filter desktop](https://user-images.githubusercontent.com/49846018/57347194-5094ef80-7149-11e9-9950-0d75312fdf55.png)
_exemple from https://koncept-demo.krownthemeswp.com/_

onMobile
![filter mobile](https://user-images.githubusercontent.com/49846018/57347199-57bbfd80-7149-11e9-861f-0eb1d9bcfe0e.png)
_exemple from https://koncept-demo.krownthemeswp.com/_

_The filter bar_ is automatically turn to a drop down. 

Thank you

**Comment by lior-sh** [comment]
@tilnox 

Invalid issue report
----
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
