### ISSUE TITLE
Archive Page not displaying on front end 

### ISSUE THREAD

**Issue by EllieHenderson** [elementor/elementor#8076]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Editor View
![image](https://user-images.githubusercontent.com/7107483/57445927-596dea00-724b-11e9-935a-dd349e7c55fe.png)

Font-End View
![image](https://user-images.githubusercontent.com/7107483/57445973-7c989980-724b-11e9-863c-464870504cbc.png)

Actual View
![image](https://user-images.githubusercontent.com/7107483/57445880-380cfe00-724b-11e9-8ea5-d3489f25455b.png)

Example 2 Back-End
![image](https://user-images.githubusercontent.com/7107483/57446656-1c0a5c00-724d-11e9-9f97-652dead842e8.png)

Example 2 Front-End
![image](https://user-images.githubusercontent.com/7107483/57446682-2debff00-724d-11e9-99ea-8c60ec2b8d6e.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v |  
PHP Version: | 5.4.19 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 33M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

Theme |   |  
-- | -- | --
Name: | Divi |  
Version: | 3.19.9 |  
Author: | Elegant Themes |  
Child Theme: | No

</details>

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* **Steps to replicate.**
* **Isolating the problem.**
* System info.
* One issue per thread

Without it we simply can't help.


From your screenshots it seems like your posts excerpts contain shortcodes, and therefore causes the query to break/show the posts improperly. 

Thanks.

**Comment by adrianrjones** [comment]
https://codex.wordpress.org/Function_Reference/strip_shortcodes is not called in the edit view.
