### ISSUE TITLE
Page content shifting / jumping when change scrolling directions. (Mobile Android)

### ISSUE THREAD

**Issue by JinxyDEV** [elementor/elementor#8081]
## Prerequisites
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

On certain pages, specially long pages, page content shifting / jumping when change scrolling directions in chrome, opera, edge (not present in Firefox) on android mobile devices.

VIDEO PRESENTATION: https://drive.google.com/open?id=1rtezlarWDbnfJ3ag3KvZA_WpurmcHrSM

## Steps to reproduce

Open url: http://rocket.hekko24.pl/ (test site to show issue)

Start scrolling down, when You see "Our Trainers" section, sscroll a bit UP again, etc. You will see that page content ist shifting, jumping up and down. When You scroll in the same direction, everything seems ok, but issue appears when you change scrolling direction. 

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.36-82.0
	PHP Version: 7.2.16
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.10
	Site URL: http://rocket.hekko24.pl
	Home URL: http://rocket.hekko24.pl
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.2.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.15
		Author: Elementor.com

== Log ==
	: 
JS: showing 3 of 3JS: 2019-05-08 11:08:37 [error X 2][http://rocket.hekko24.pl/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:60824] Cannot read property \'query\' of null 
JS: 2019-05-08 11:48:41 [error X 1][http://rocket.hekko24.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.15:2:8507] Cannot read property \'select2\' of undefined 
JS: 2019-05-09 09:02:27 [error X 1][http://rocket.hekko24.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.15:2:19593] Cannot read property \'hoverIntent\' of undefined 

PHP: showing 1 of 1PHP: 2019-05-08 17:30:50 [notice X 7][/home/rocket/domains/rocket.hekko24.pl/public_html/wp-content/plugins/elementor/core/files/css/global-css.php::136] Undefined index: font_weight [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by Aviad-Herman** [comment]
Hi,
I'm closing this old issue. Let me know if it is still relevant.
