### ISSUE TITLE
Not expected result using "do_hook" from issue 5638/5574

### ISSUE THREAD

**Issue by milouser** [elementor/elementor#8082]
Hello 

I'm new to Elementor Pro, Woocommerce and php, so my question might be naive. 

1. What I did:

I created the do_hook function in my function.php file as explained in your previous post.
[https://github.com/elementor/elementor/issues/5638]

Then I placed some custom hook on the single product page with elementor using the shortcode widget ([do_hook hook='my_elementor_single_product_after_price'])

The I added this code in function.php:
add_action('my_elementor_single_product_after_price', 'displayTest', 10);
function displayTest()
{echo 'test';}

2. What I expected: 
'test' to be displayed on the single product page where I placed the shortcode

3. What I got: 
Nothing displayed.
Something nevertheless happened. When I inspect html, I see this output on the page:
<div class="elementor-element elementor-element-f7e13bb elementor-widget elementor-widget-shortcode" data-id="f7e13bb" data-element_type="widget" data-widget_type="shortcode.default">
				<div class="elementor-widget-container">
					<div class="elementor-shortcode"></div>
				</div>
				</div>

What am I doing wrong? Your help would be greatly appreciated, as this pattern would help me tremendeously to tweek my pages!

**Comment by bainternet** [comment]
@milouser 

just tested again myself and it seems to work just fine:

```php
/**
 * Usage: [do_hook hook="hook_name"]
 **/
add_shortcode( 'do_hook', function( $atts = array(), $content = null, $tag = ''){
	if ( isset( $atts['hook'] ) ) {
		ob_start();
		do_action( $atts['hook'] );
		return ob_get_clean();
	}
	return '';
} );

add_action( 'banana', function() {
	echo 'banana test';
} );
```

using a shortcode widget with `[do_hook hook="banana"]`

there was an error in the only snippet of the do_hook shortcode, which is now fixed.

thanks.

**Comment by milouser** [comment]
Thanks a lot! Works fine now!
