### ISSUE TITLE
Issue with Storefront (narrow product column) -> follow up #5442

### ISSUE THREAD

**Issue by milouser** [elementor/elementor#8088]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Product are displayed narrowly when using Products widget (see https://ibb.co/YhMZtKY).

Issue already described under https://github.com/elementor/elementor/issues/5442, with no solution for my case.

## Steps to reproduce

I'm use the latest Storefront Theme (2.5.0) with the latest Elementor / Elementor Pro version (2.5.18 / 2.5.5).

1. Create a page using elementor
2. Add Product widget. Set Column = 4, Rows = 1 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.26
	PHP Version: 7.2.17
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://staging.swissbrew.ch
	Home URL: https://staging.swissbrew.ch
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 640M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: Storefront Child Theme
	Version: 1.0.0
	Author: Stuart Duff
	Child Theme: Yes
	Parent Theme Name: Storefront
	Parent Theme Version: 2.5.0
	Parent Theme Author: Automattic

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15

== Active Plugins ==
	Captcha Code
		Version: 2.6.7
		Author: Vinoj Cardoza

	Cookie Notice
		Version: 1.2.46
		Author: dFactory

	Elementor
		Version: 2.5.15
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.8
		Author: Elementor.com

	Instant Images
		Version: 4.0.1
		Author: Darren Cooney

	Really Simple SSL
		Version: 3.1.5
		Author: Rogier Lankhorst, Mark Wolters

	Smush
		Version: 3.2.0.1
		Author: WPMU DEV

	WooCommerce
		Version: 3.6.2
		Author: Automattic

	WooCommerce Bulk Discount
		Version: 2.4.5
		Author: Rene Puchinger

	WooCommerce Force Sells
		Version: 1.1.18
		Author: WooCommerce

	WooCommerce Frontend Manager
		Version: 6.1.0
		Author: WC Lovers

	WooCommerce Frontend Manager - Product Hub
		Version: 1.0.7
		Author: WC Lovers

	WooCommerce Frontend Manager - Ultimate
		Version: 6.1.0
		Author: WC Lovers

	WooCommerce Multilingual
		Version: 4.6.2.1
		Author: OnTheGoSystems

	WooCommerce Multivendor Marketplace
		Version: 3.0.5
		Author: WC Lovers

	WooCommerce Multivendor Membership
		Version: 2.4.4
		Author: WC Lovers

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.2.12
		Author: Ewout Fernhout

	WooCommerce Services
		Version: 1.20.0
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.16
		Author: WooCommerce

	WPML CMS Nav
		Version: 1.5.1
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.2.6
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.5.0
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.10.4
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.8.5
		Author: OnTheGoSystems

== Log ==
	: 
JS: showing 5 of 5JS: 2019-05-01 13:05:02 [error X 1][https://staging.swissbrew.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:212627] undefined is not an object (evaluating \'this.ui.form.elementorSerializeObject()[e].REPLACE_TO_ID\') 
JS: 2019-05-01 13:17:37 [error X 4][https://staging.swissbrew.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:212876] undefined is not an object (evaluating \'e.ui.form.html\') 
JS: 2019-05-01 16:27:05 [error X 2][https://staging.swissbrew.ch/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:10535] n.attributes[t.name].each is not a function. (In \'n.attributes[t.name].each(function(e){r.push(n.getStyleControls(t.fields,e.attributes))})\', \'n.attributes[t.name].each\' is undefined) 
JS: 2019-05-06 13:04:01 [error X 2][https://staging.swissbrew.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:8506] undefined is not an object (evaluating \'this.ui.select.select2\') 
JS: 2019-05-09 14:51:46 [error X 1][https://staging.swissbrew.ch/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.5.15:2:8028] undefined is not an object (evaluating \'i.attributes\') 

PHP: showing 1 of 1PHP: 2019-05-03 17:03:06 [notice X 11][/home/clients/983bd5e2d7565c212abddbb843e41f30/staging/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/add-to-cart.php::130] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 3 of 32019-05-06 09:48:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.5.7',
)]
2019-05-07 08:56:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.7',
  'to' => '2.5.8',
)]
2019-05-09 14:52:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.14',
  'to' => '2.5.15',
)]

				</details>

**Comment by mrAlexandrovski** [comment]
Had the same problem. I changed the page's layout. Go to the settings menu at the bottom-left of the elementor page bulding screen and change the page's layout from "default" to "Elementor full width".

https://d33v4339jhl8k0.cloudfront.net/docs/assets/573acfa69033602af6969ed2/images/5ae6c7710428631126f18045/file-ZnVA8rATsc.gif 

By the way, do you know how to add an attribute filter and make it work so clients could use it? I could add it without elementor (in default Storfront page builder). In elementor there is a template called "attribute filter" but it just does not work though I already added a few colums of products.

**Comment by milouser** [comment]
Thanks a lot mrAlexandrovski! Works perfectly. You made my day:)
