### ISSUE TITLE
Controls in the section inherit conditions when calling the "update_control" method

### ISSUE THREAD

**Issue by nonamich** [elementor/elementor#8089]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Control has a unique "condition", but with the "update_control" section in the bark, this control is found, the "condition" will be overwritten by the argument in the "update_control"

**[!!!Demo!!!!](https://i.imgur.com/iboeIIJ.png)**

I had to call "update_control_in_stack" to bypass "update_control"

## Steps to reproduce

```php        
$this->start_controls_section(
	'section1',
	[
		'label' => __( 'section 1', 'text-domain' ),
		'tab' => Controls_Manager::TAB_CONTENT,
	]
);

$this->add_control(
	'switcher1',
	[
		'label' => __( 'switcher 1', 'text-domain' ),
		'type' => Controls_Manager::SWITCHER,
		'render_type' => 'ui',
	]
);

$this->end_controls_section();

$this->start_controls_section(
	'section2',
	[
		'label' => __( 'section 2', 'text-domain' ),
		'tab' => Controls_Manager::TAB_CONTENT,
	]
);

$this->add_control(
	'switcher2',
	[
		'label' => __( 'switcher 2', 'text-domain' ),
		'type' => Controls_Manager::SWITCHER,
		'render_type' => 'ui',
	]
);

$this->add_control(
	'switcher3',
	[
		'label' => __( 'switcher 3', 'text-domain' ),
		'type' => Controls_Manager::SWITCHER,
		'render_type' => 'ui',
		'condition' => [
			'switcher2!' => '',
		],
	]
);

$this->end_controls_section();

$this->update_control(
	'section2',
	[
		'condition' => [
			'switcher1!' => '',
		],
	]
);

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
