### ISSUE TITLE
Change heading level of price table header

### ISSUE THREAD

**Issue by renemorozowich** [elementor/elementor#8090]
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am using a pricing table but getting accessibility errors because of a skipped heading level. This feature would solve any accessibility errors related to heading levels.

**Describe the solution you'd like**
I would like to be able to choose the heading level when entering the title. Or I think the default heading style should be Heading 2 and not Heading 3.

**Describe alternatives you've considered**
I could add a Heading 2 to my page, but the layout doesn't really work. I could also try to hack it with JavaScript, but that seems like a lot of effort.

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!
