### ISSUE TITLE
form acceptance checkbox

### ISSUE THREAD

**Issue by odivius** [elementor/elementor#8091]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by odivius** [comment]
When selecting border styling there is no way to do this for the form fiels acceptance checkbox. 

I only need border-bottoms for all form fields exept the checkbox.
The checkbox should always have borders: under, top, left and right.

**Comment by odivius** [comment]
![Elementor _ Contact](https://user-images.githubusercontent.com/29161391/57561566-ac9b8600-738c-11e9-8a01-67d595f70901.png)

**Comment by shilo-ey** [comment]
Hi @odivius 
Thanks for reporting,
We can't reproduce this behavior.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by odivius** [comment]
I found the sollution. I gave the acceptance box an ID: acceptance. Now it works: #form-field-acceptance{
border-width: 2px 2px 2px 2px;
}
