### ISSUE TITLE
Defining Default Fonts will not cause them to load on new pages.

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8093]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Only loads custom fonts when they are explicitly defined on a content type. 
Defining a custom google font for use in a header, without explicitly defining it on the header element when creating a page results in the font not being loaded. 

Using Elementor + Elementor Pro + Hello Theme

## Steps to reproduce

1. In default fonts pick a Google Font for Primary and/or secondary headline. 
2. Create a new page and add a new header element (not the homepage)
Within the header element do not change the font. 
The font displayed in the Page Builder will be the correct font you chose in step 1. 
If you load the live page, the font resets to a default sans-serif, non-google font. 

3. If you edit the page again and change the font of the header element to the google font, it works. 

This happens with Autoptimize set to not interfere with the loading of Google Fonts (does not affect the behaviour).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2
	Site URL: https://
	Home URL: https://
	WP Multisite: Yes
	Max Upload Size: 15 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -4
	Debug Mode: Inactive

== Theme ==
	Name: Webtemple Hello
	Version: 1.0.0
	Author: TD Labs Ltd.
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 1.2.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.5.0
		Author: Frank Goossens (futtta)

	Dynamic Content for Elementor
		Version: 1.4.1
		Author: Dynamic.ooo

	Elementor
		Version: 2.5.15
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.15
		Author: Namogo

	Elementor Pro
		Version: 2.5.8
		Author: Elementor.com

	Format Price
		Version: 1.0
		Author: TD Labs Ltd.

	Gravity Forms Event Tracking
		Version: 2.3.8
		Author: Ronald Huereca

	Logos Showcase
		Version: 2.0.4
		Author: Carlos Moreira

	Slider Revolution
		Version: 5.4.8.3
		Author: ThemePunch

	Toolset Types
		Version: 3.3
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.8.0.1
		Author: OnTheGoSystems

	Ultimate Addons for Elementor
		Version: 1.11.0
		Author: Brainstorm Force

	Webtemple Testimonials
		Version: 9.9.4
		Author: Webtemple


== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 6.93
		Author: ServMask

	All-in-One WP Migration Google Drive Extension
		Version: 2.48
		Author: ServMask

	All-in-One WP Migration Multisite Extension
		Version: 3.73
		Author: ServMask

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Compress JPEG & PNG images
		Version: 3.2.0
		Author: TinyPNG

	Gravity Forms
		Version: 2.4.9
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	User Role Editor Pro
		Version: 4.50.5
		Author: Vladimir Garagulia

	Wordfence Security
		Version: 7.2.5
		Author: Wordfence

	WP-Cron Control
		Version: 0.7.1
		Author: Thorsten Ott, Erick Hitter, Automattic

	WPMU DEV Dashboard
		Version: 4.7.1.1
		Author: WPMU DEV

	WP Ultimo
		Version: 1.9.10
		Author: Arindo Duque - NextPress


== Must-Use Plugins ==
	Webtemple Styles
		Version: 4.6
		Author: TD Labs Ltd.


== Log ==
	: 
PHP: showing 1 of 1PHP: 2019-05-10 21:18:23 [notice X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2019-05-11 08:10:12 [error X 2][https:///wp-admin/post.php?post=87682&action=elementor:2:1] Unexpected token < 
JS: 2019-05-11 08:12:42 [error X 1][https:///wp-admin/post.php?post=87682&action=elementor:3:28] Unexpected token , 
JS: 2019-05-11 08:12:42 [error X 1][https:///wp-admin/post.php?post=87682&action=elementor:3:28] tr is not defined 
JS: 2019-05-11 08:23:51 [error X 1][:2:15] $(...).smoothWheel is not a function 
JS: 2019-05-11 08:24:08 [error X 1][:2:13] document.ready is not a function 
JS: 2019-05-11 08:24:09 [error X 1][:2:2] j is not defined 
JS: 2019-05-11 08:24:09 [error X 1][:2:2] jQue is not defined 
JS: 2019-05-11 09:00:19 [error X 1][/wp-content/plugins/dynamic-content-for-elementor/assets/js/elements-inertiaScroll.js?ver=62856547567ab3d94ce6b39b89a260cd:116:3] requestId is not defined 
```
</details>

**Comment by formulaclick** [comment]
Same issue here. I need to load fonts using code snippet. Default fonts configured with Elementor are not being loaded in frontend. They are loaded just in Elementor live editor.

**Comment by sproutedweb** [comment]
## Your ticket has been created. ##


Ticket subject: Re: [elementor/elementor] Defining Default Fonts will not cause them to load on new pages. (#8093)


----
Author: formulaclick 
Date: Tue, 05/14/19 1:56 am
Message:
Same issue here. I need to load fonts using code snippet. Default fonts configured with Elementor are not being loaded in frontend. They are loaded just in Elementor live editor.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/elementor/elementor/issues/8093#issuecomment-492150155



Powered by https://www.livechatinc.com/powered-by-livechat/?utm_source=ticket_footer&utm_medium=email&utm_campaign=lc_10152642"

**Comment by aliajellu** [comment]
Hi everyone, 
Having the same issue. This seems super basic!!
Are there any updates / fixes? Any workarounds you can suggest for this? 

I'd rather not have to explicitly define header + body fonts on every single page in order for them to be loaded. 
Cheers

**Comment by deep-ops** [comment]
I was having this same problem. Under Elementor, got to Tools. Click the Regenerate CSS  button, actually says "Regenerate Files". Then empty any caches and refresh your page. Hope that helps.

**Comment by shilo-ey** [comment]
Is this issue still occurs? @taropaa
