### ISSUE TITLE
No keyboard shortcut to add a column ?

### ISSUE THREAD

**Issue by papafew** [elementor/elementor#8095]
Bonjour à tous 

I'm still wondering if there is a way to add or modify shortcuts in Elementor?

The option to add quickly a new column with a hotkey for example would really help the workflow...

My dream is to be able in the future to add or modify every kind of shortcut on a customization panel

But it's only a dream...

f e w

**Comment by DorShahar** [comment]
Hi @papafew,
Thank you for your input.

We are currently not supporting this option. Maybe someday in the feature... 

Thanks.
