### ISSUE TITLE
Open a pop-up window by selector

### ISSUE THREAD

**Issue by GOHA81177** [elementor/elementor#8103]
There is a button that should open a pop-up window by selector, but this does not happen.
I set a selector for the pop-up window, bind it to a button,set the display conditions... clicking on the pop-up button only appears once! and it needs to pop up every time... nothing happens when you press again

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
