### ISSUE TITLE
Maintenance/Coming soon Backdoor

### ISSUE THREAD

**Issue by ianstudio** [elementor/elementor#8104]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I usually use:
https://www.seedprod.com/features/
for maintenance/coming soon, but they hiked up their pricing and I'd like to b able to count on Elementor for that functionality but they have a great option...

**Describe the solution you'd like**
This option creates a user, which then allows to visit a site without logging in, but by visiting a backdoor url of choice like: mysit.com/bypass

Would love to have something like that implemented in E. It makes it very easy to show a site at work to a client. They also have redirect option etc.. all in all  great plugin, but too expensive IMO.

**Comment by shilo-ey** [comment]
Hi @ianstudio 

You can simply create a subscriber role user, which cannot change anything in the website but view the website that is under construction.

Unfortunately, we don't see the value in this particular feature, therefore I don't see us implementing this "backdoor". you can still use 3rd party plugins to achieve this behavior.

Thanks!

**Comment by ianstudio** [comment]
The value ? Very obvious:
the site can be visited using a simple link, no login required.
Elegant.
