### ISSUE TITLE
Which plugins in PHP Storm that you used to format backbone code?

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#8105]
Hello team,

Could you Please tell me which plugins in Php Storm that your team used to format/highlight JS code in 
`<?php function _content_template() {} ?>`

I try beautiful php code then code in the function become uglify & has bug in Editor mode.

Sorry for any inconvenience.

Thank you in advance.

**Comment by shilo-ey** [comment]
Hi @steve231293 

In those functions, there is plain JS inserted, and therefore it is not being highlighted. We also use it non-highlighted :)

Sorry to let you down...
