### ISSUE TITLE
popup callback

### ISSUE THREAD

**Issue by formulaclick** [elementor/elementor#8107]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Is there a javascript callback function to capture the Elementor's Popup opening events? I need to execute some Javascript code once Popup is opened. I've searched for a solution with no luck. Any help? Thanks

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @formulaclick 

Next time please search our closed tickets.

[see here](https://github.com/elementor/elementor/issues/8057)

Thanks

**Comment by formulaclick** [comment]
> Hi @formulaclick
> 
> Next time please search our closed tickets.
> 
> [see here](https://github.com/elementor/elementor/issues/8057)
> 
> Thanks

Sorry. I searched but didn't find this issue.
