### ISSUE TITLE
Adding a shortcode in the heading widget

### ISSUE THREAD

**Issue by lcswillems** [elementor/elementor#8108]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Adding a shortcode in the heading widget.

**Describe the solution you'd like**
I would like to be able to add shortcuts in the heading widget. Currently, it is only possible in text editor widget.

I know I can create a heading in the text editor widget, but I have to use the heading widget.

**Comment by shilo-ey** [comment]
Hi @lcswillems 

Add a shortcode using dynamic tag

![image](https://user-images.githubusercontent.com/45009641/57632827-1b562a80-75ab-11e9-8d5a-1b5c8452d2bc.png)

Thanks

**Comment by lcswillems** [comment]
THANK YOU!!
