### ISSUE TITLE
_elementor_data meta and get_settings_for_display  do not match

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#8114]
I am trying to find widget data outside  of Elementor. 
Maybe the data is saved somewhere else but I looked trough all issues and it seems like all elements settings should be available in  `_elementor_data`  meta  https://github.com/elementor/elementor/issues/7850

when I print it out via 

`json_decode(get_post_meta( 2, '_elementor_data', true ),true);`

I see this  as the element data http://prntscr.com/nonfg1

if I print the settings  in render I see everything else
http://prntscr.com/nonfzd

I saved the post several times but no change. 

What am I missing?

**Comment by bainternet** [comment]
@danyj 

Elementor doesn't save store default value in the database so when you get the data via `get_settings_for_display` elementor loads all of the default values, as well as dynamic values for you and that, is why you see a difference.

thanks.

**Comment by danyj** [comment]
@bainternet  @KingYes OK how is this going to help me than? I asked how to get settings 
and did not get an answer but an explanation why not. Here you refereed the developer to the meta https://github.com/elementor/elementor/issues/7850 knowing that the info you are giving him is wrong. 

I mean I am trying hard to understand "your" way of doing things but you guys are simply put developer unfriendly.  I am in Open Source since 15 years and have not seen these kind of brush offs ever. 
We cant ask a simple how to question and are forced to dig trough thousands of lines of code. And if we ask direct question we get evasive answers that simply do not help.

What now , I open another issue and get blown off again?
