### ISSUE TITLE
List icons stacked icons

### ISSUE THREAD

**Issue by alriksson** [elementor/elementor#8115]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can not have the list icons lined but the icon on top of the text.

**Describe the solution you'd like**
The problem describes the issue and solution. Enable me to align the icon to be above/below the text. A simple feature that doesn't limit my ideas and design.

**Comment by alriksson** [comment]
Please consider adding background color option to widget icon list as well for "Normal" "Hover" and "active". 

Since the nav menu is so limited many users like me use the list icons to create more appealing top navigations. But we miss those features. Adding support for a background color for normal and hover should not be a big of a deal for you guys to add.

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these requests in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
