### ISSUE TITLE
Section Width is Boxed but The Other Columns is Full width

### ISSUE THREAD

**Issue by IdioticDoodler** [elementor/elementor#8116]
Hello There!
Just want to asked if this is possibe? 
The section is still in the boxed so we can still have a container.
The problem is the design I'm converting is the other columns should be fit in the screen(the Image), the other content is on the boxed container. Check the image below. Can we do this on Elementor Pro. Thanks
![image](https://user-images.githubusercontent.com/39472759/57753980-07800500-7720-11e9-8aa1-8dde1fa08fb7.png)

**Comment by shilo-ey** [comment]
Hi @IdioticDoodler 

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


As for your question - you can do this with margins to the left column.


thanks.
