### ISSUE TITLE
Next / previous newsfeed arrows running smoothly 

### ISSUE THREAD

**Issue by IsDyn** [elementor/elementor#8117]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The newsfeed (post navigation widget) 'next' or 'previous' buttons reload the whole page. This means I can't add this widget, which I am trying to on our homepage. It would be nice if it was possible to show for example the first 3 posts and if someone clicks next, for it to scroll to the next, without reloading the entire page and adding extra rows in the newsfeed.

**Describe the solution you'd like**
Either (1) the 'next' and 'previous' post navigation to prompt a scrolling to new posts rather than reloading the whole page and adding extra post to the bottom. Or (2) a simple left/right arrow as per the carousel function that people can click on to scroll through previous posts.

**Describe alternatives you've considered**
I've tried:
1) using the carousel and portfolio widgets and seeing if I can get posts in there.
2) using different newsfeed widgets
3) currently looking for a plugin that does this 

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1284, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
