### ISSUE TITLE
How do we get all page/post elements settings outside Elementor?

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#8120]
I tried to get the info here but it is closed and no details are provided

https://github.com/elementor/elementor/issues/8114

I am trying to get all elements settings, `_elementor_data`  contains only changed values and  `get_settings_for_display`  is not accessible. 

How do we get ALL elements data from a specific post/page ? 

This does not help https://github.com/elementor/elementor/issues/7850#issuecomment-485253787

Docs have no global method/class/function for it
and I am not able to find any usable code reference that would do this.

**Comment by bainternet** [comment]
@danyj 

there is no way to get all of the data outside Elementor because of the dynamic nature of how Elementor works.

what it is that you are trying to do to?

**Comment by danyj** [comment]
I need to do some ajax on posts and need to get the all current element options, but I think I got it now. created a class that pulls the  `get_elements_data()` https://github.com/elementor/elementor/blob/bc251b81afb626c4c47029aea8a762566524a811/core/base/document.php#L711    and looped trough it via element ID

what I was looking for was this basically ,  took me few days to digg it out 


`\Elementor\Plugin::$instance->documents->get( $this->postid )->get_elements_data();`


This is what I was trynig to replicate because I am moving our Unsyon elements to E 

https://github.com/Themezly/Creatus/blob/master/inc/utility.php#L502-L578

**Comment by danyj** [comment]
There really  should be an easy way to pull all data for specific page/post.  @bainternet  if you see a better way or an actual function/class that I should use please do let me know.

**Comment by danyj** [comment]
Here , if anyone needs it 
https://gist.github.com/danyj/317e0fdc9e18d2857f331245f2cedd1d

**Comment by bainternet** [comment]
@danyj 

Still not sure what it is you are trying to do, but glad you figured it out.
