### ISSUE TITLE
CSS Alert in Widget Header

### ISSUE THREAD

**Issue by RonR-WebDesign** [elementor/elementor#8121]
It is so easy to lose track of which widgets have entries in Custom CSS.  I suggest adding an icon to the widget header that indicates added css; maybe a simple small "css"?

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Also, what would you call "Widget header"??

**Comment by RonR-WebDesign** [comment]
I was making a feature request.  Sorry if that wasn't clear.  This should help.  Note the "CSS" in the top right:

http://dev.stsroundtable.com/wp-content/uploads/elem-css.jpg

**Comment by shilo-ey** [comment]
I merged this issue with  #2180, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
