### ISSUE TITLE
lazy load self hosted video overlay

### ISSUE THREAD

**Issue by T4ngml** [elementor/elementor#8122]
Self hosted video overlay has no lazy load option, and thus... Won't be lazy loaded.
Is there a technical limitation, justifying its absence?

Thanks,

**Comment by shilo-ey** [comment]
Hi @T4ngml 

The Lazy load function is a parameter that Elementor passes to Slick slider, which means that currently in Elementor there's no mechanism for handling the lazy load.

You can use external plugins such as WP-Rocket to achieve this behavior.

Thanks.

**Comment by T4ngml** [comment]
Thanks for your answer @shilo-ey, but I have to say your answer doesn't make sense to me.
What Slick Slider has to do with video image overlay?

On my side, I just notice there actually is a lazy load mechanism offered by Elementor from the Video Widget > Image Overlay section, titled "Lazy Load", and also documented here: https://docs.elementor.com/article/48-video
It's available for YouTube, DailyMotion and Vimeo videos, but not for self hosted videos.

I also notice  an exception coded in Elementor in: https://github.com/elementor/elementor/blob/master/includes/widgets/video.php:507

Therefore... I wonder what prevents you from allowing that feature for self hosted videos?

Thanks

**Comment by T4ngml** [comment]
Should I open a new ticket with that same question to get an answer... ?

**Comment by shilo-ey** [comment]
Thanks for clarifying.

Please re open a new issue with all of the required information.

Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
