### ISSUE TITLE
Reopen: Color picker dynamic pull #6485

### ISSUE THREAD

**Issue by drewb1** [elementor/elementor#8130]
I am trying to use ACF pro to create a custom field type for colors, ACF Pro comes with a color picker. I would like it to make a custom field that asks for primary, secondary, font, and accent, as well as other custom ones. I have done this but my question is how do I make those color selections within a custom field auto propagate into Elementor's color picker? Is there a dynamic (pull from a post-meta/acf field) setting I am missing on the color picker? If this is not something you offer can I make a product suggestion to make this happen and/or can you suggest a plugin/integration or work flow that will allow this?

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

anyway, reopened #6485 

thanks.
