### ISSUE TITLE
Send to whatsapp after send | elementor forms

### ISSUE THREAD

**Issue by electro-Z** [elementor/elementor#8131]
**What problem is your feature request going to solve? Please describe.**
Cannot Send form content to whatsapp user after hitting send on an elementor form.

**Describe the solution you'd like**
Add the option to Send form content to whatsapp user after hitting send on an elementor form.
If I add "send to whatsapp" in the "after send" option I will be able to add a whatsapp user phone number or multiple users and the content of the form will be sent to them.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for your request, WhatsApp does not have an API available for public use. it's a closed system so we can't really send data from the server to them.

thanks.
