### ISSUE TITLE
Related post by Main Category

### ISSUE THREAD

**Issue by miguelventura** [elementor/elementor#8133]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've more than one category in my posts and I create a section for related by category but the results doesn't make sense for us.

**Describe the solution you'd like**
In this case it makes sense if we can only related by Main category.
Maybe we can have a checkbox to select "only by main category".

**Describe alternatives you've considered**
In alternative, somebody helps me with a query for this.

**Comment by bainternet** [comment]
@miguelventura 

Thanks for clarifying,

There is no concept of "main category" / "primary" term in WordPress. Taxonomies are a grouping mechanism. Post belongs to multiple terms on equal terms (no pun intended). No term is "more" of a group than the rest.

So what you call "Main category" comes from a 3rd party plugin, most likely Yoast SEO and if that is the case then you can use a "[Custom Query Filter](https://developers.elementor.com/custom-query-filter/)" to achieve that.

Set your query to related by term >> category and set a "query id" ex: 

```php
// Showing related posts by Yoast main category in Posts Widget
add_action( 'elementor/query/my_custom_related_query_id', function( $query ) {
	// 'Primary' category, is a Yoast feature so make sure its available
	if ( ! class_exists( 'WPSEO_Primary_Term' ) ) {
		return;
	}
	// Get the post's 'Primary' category, if this Yoast feature is available, & one is set. category can be replaced with custom terms
	$wpseo_primary_term_obj = new \WPSEO_Primary_Term( 'category', get_the_id() );
	$wpseo_primary_term = $wpseo_primary_term_obj->get_primary_term();
	$term = get_term( $wpseo_primary_term );

	if ( is_wp_error( $term ) || ! isset( $term->term_taxonomy_id ) ) {
		return;
	}
	// If we got here then we have a primary/main category term so we can modify the query

	// Get current tax_query
	$tax_query = $query->get( 'tax_query' );

	// Set our tax query to get related by current main term
	$tax_query[0]['terms'] = [ $term->term_taxonomy_id ];

	// Modify the query
	$query->set( 'tax_query', $tax_query );

	// Make sure we don't get current post
	$not_in = $query->get( 'post__not_in' );
	$not_in[] = get_queried_object_id();

	// Modify the query
	$query->set( 'post__not_in', $not_in );
} );
```

hope this helps.

**Comment by miguelventura** [comment]
@bainternet, thanks for the explanation and for the solution. It works!
Thank a lot.
