### ISSUE TITLE
Pagination in custom query archive returns 404 

### ISSUE THREAD

**Issue by miguelventura** [elementor/elementor#8134]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

We create a custom query to show a post archive form custom post type. But, it just show the first page and returns 404 when we try to move to another page.

## Steps to reproduce

This is the query
```
add_action( 'elementor_pro/posts/query/all_posts_types', function( $query ) {
    // Here we set the query to fetch posts with
    // post type of 'custom-post-type1' and 'custom-post-type2'
    $query->set( 'post_type', [ 'receita', 'bricolage', 'posts' ] );

    $queried_object = get_queried_object();
    $term_id = $queried_object->term_id;
    $query->set( 'cat', $term_id);
} );
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v5.5.59-MariaDB-38.11 |  
PHP Version: | 7.1.29 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</details>

**Comment by bainternet** [comment]
@miguelventura 

we can't replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
