### ISSUE TITLE
Responsive behaviour in Elementor edit panel and Chrome/Firefox responsive is different

### ISSUE THREAD

**Issue by muaz234** [elementor/elementor#8135]
Hi Elementor team,

Recently I bought Elementor Pro for business to build my company website using Wordpress + Elementor theme builder. As I am working on responsive in Elementor, I found that whenever I am testing them on Chrome or Firefox web browser it turns out that is having some glitch like margin/padding issue. Tried both refresh and remove browser cache and the issue is still unsolved. I utilize fully media queries in CSS but as I fixed the margin/padding from the elemento r edit panel site, it is still behaving differently on my normal browsers(Chrome/Firefox) while in Elementor it is seems as it was already in right position. Hopefully your team could try to test this issue to rectify and let me know the solutions to this problem. I am using latest elementor  5.2.12 version prior to this issue.
Do contact me privately if you would like to see the screenshots. I can screenshots those affected media queries CSS.

Thanks

Best Regards,
Muaz
ahmedmuaz0152@gmail.com

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
