### ISSUE TITLE
[images] locate specific images used within widgets in media library

### ISSUE THREAD

**Issue by cpanfilio** [elementor/elementor#8138]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
 I'm  frustrated when I click on an image used in a widget and the only option is delete. I want an option to take me to the specific image in the media library, but that functionality isn't available. Unfortunately, the user has to search for the image visually. (to compound the problem we, in many cases, have different cropping of the same image in the library.)

**Describe the solution you'd like**
I would like an edit as well as a delete functionality in the window that takes the user to the specific image currently being used in a widget.)

**Describe alternatives you've considered**
There are none that I'm aware of. 

**Additional context**
![Screen Shot 2019-05-17 at 11 19 24 AM](https://user-images.githubusercontent.com/23561522/57950646-b5b0b980-789c-11e9-9faa-dfc5970462e5.jpg)

**Comment by shilo-ey** [comment]
I merged this issue with  #7937, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
