### ISSUE TITLE
[Editor] repeater-generated Select input as a control in another repeater of the same Widget

### ISSUE THREAD

**Issue by b4rracuda** [elementor/elementor#8140]
I have a repeater, which can generate categories:

		$this->start_controls_section(
			'catlist',
			[
				'label' => __( 'Case Categories'),
			]
		);
		$catrep = new \Elementor\Repeater();

		$catrep->add_control(
			'cat_title', [
				'label' => __( 'Title' ),
				'type' => \Elementor\Controls_Manager::TEXT,
				'default' => __( 'Case title'  ),
				'label_block' => true,
			]
		);

		$this->add_control(
			'catslist',
			[
				'label' => __( 'Case Categories List' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $catrep->get_controls(),
				'default' => [
					[
						'cat_title' => __( 'Title #1' ),
					],
				],
				'title_field' => '{{{ cat_title }}}',
			]
		);

		$this->end_controls_section();

And another Repeater, where one of controls is the Select input, where the options should be generated from 1st repeater's values.

```
		$this->start_controls_section(
			'caselist',
			[
				'label' => __( 'Cases', 'elementor-hello-world' ),
			]
		);

                $repeater = new \Elementor\Repeater();
		$repeater->add_control(
			'img',
			[
				'label' => __( 'Image', 'plugin-name' ),
				'type' => \Elementor\Controls_Manager::MEDIA,
				'default' => [
					'url' => \Elementor\Utils::get_placeholder_image_src(),
				]
			]
		);

		$repeater->add_control(
			'list_title', [
				'label' => __( 'Title' ),
				'type' => \Elementor\Controls_Manager::TEXT,
				'default' => __( 'Case title'  ),
				'label_block' => true,
			]
		);
               //HERE IS THE PROBLEM STARTING
              //Got to generate options from 1st repeater
              $caseOptions;
		add_action( 'elementor/CasesListMain/before_section_end', function($element, $args) {
			$caseCategories = $this->get_settings_for_display('catslist');
				foreach ($caseCategories as $key => $value) {
					$caseOptions[$key]= __($key.' : '.$value['cat_title']);
				}
			});

		$repeater->add_control(
			'casecat',
			[
				'label' => __( 'Case Category' ),
				'type' => \Elementor\Controls_Manager::SELECT,
				'default' => 0,
				'options' => $caseOptions
			]
		);
               //Options list empty...
              
		$this->end_controls_section();
```

1) can the functionality I am trying to achieve, be implemented?
2) Where could be my possible mistake, if I am trying to hook options generation function  to the   section 'caselist' of class CasesListMain extends Widget_Base?

Thanks

**Comment by bainternet** [comment]
@b4rracuda 


1) This can only be achieved on the frontend via some custom JS handler that will populate the 2nd control values based on the first one.

2) Your mistake is that the code you posted only runs on the server before the widget is loaded so using `'elementor/CasesListMain/before_section_end'` hook makes no sense.


Thanks.

**Comment by Paras16699** [comment]
@bainternet, I am also trying to achieve the same. You mention that this can be achieved with some custom JS handler, but it would be great if you can give some more info on that.

Like,
1. How to expose the repeater settings using JS on the frontend?
2. How to set or change the select option settings with that?

Any help would be much appreciated.

**Comment by b4rracuda** [comment]
@Paras16699 , Here is how I handled it:
My situation was:
I had a Widget, where there were 2 repeaters:
One generates categories, the second one generates 'Case' Blocks, which has some options along with a Select for 'Case Category'. This Select values needed to be generated based on the Categories repeater.

1) Using my custom theme's functions.php, I load some .js file in Editor:
```
add_action('elementor/editor/before_enqueue_scripts', function() {
	wp_enqueue_script( 'editorcase', get_stylesheet_directory_uri().'/js/casecategories.js', array('jquery') );
});
```
2) In this .js file I used a hook on opening the Editor window for my Widget (both repeaters and repeater-generated select are the things of the same widget 'caselist-main'):
```
elementor.hooks.addAction( 'panel/open_editor/widget/caseslist-main', function( panel, model, view ) {
   refreshCaseCategories();
} );
```
```
function refreshCaseCategories(){
	//We get select options data from preview HTML (as the HTML elements being generated based on the settings of the repeater), and fill them in selector

	var frame=jQuery('iframe#elementor-preview-iframe').contents();
	var frameElements=frame.find('#verticalNav ul li a p'); // in this place I had raw generated data

	var frameCases=frame.find('.case-item-box'); // This is the selector for the target items that needed to have attributes inserted based on the Select, when its options are generated by Category repeater values

	frameElements.each(function(i, v){
        //We append each of HTML-parsed elements as the options for our Select which stands for 'casecat' a.k.a Case Category setting

		jQuery('select[data-setting="casecat"]').append('<option value="'+i+'">'+jQuery(v).text()+'</option>');
	});

	// set defaults for already set items (actual items that already had some option from the 'casecat' select selected previously. The changes are being saved on every load, despite that select options are generated every time
	frameCases.each(function(idx, elem){
		jQuery('select[data-setting="casecat"]').eq(idx).val($(elem).attr('data-elementor-casecat'));
	});
	return true;
}
```

Might seem somewhat complicated, and it was indeed. But if you get the idea of my Task, then it gets a bit more clear. Took me like 3 days to come up with that

Hope that helps!

**Comment by Paras16699** [comment]
@b4rracuda, Thanks for sharing.

Though this does the task of achieving custom option based on the value of select, I believe that so much DOM manipulation on every change would be very taxing on the memory.

The result that I'm trying to achieve is pretty complicated and requires more than 1 such manipulation. So, I also have to keep in mind the performance so that it does not slow down on low-end specs.

Would be great if I could get some hint on how to do it the Elementor way, by using some of the available Elementor object variables to set up a watcher on data change and update the appropriate object that stores the second control value. That would help make the manipulation performant...

**Comment by b4rracuda** [comment]
@Paras16699 I get your idea. I've also tried to achieve that with using php variables/objects within the widget file itself, but all of the ways were either not working or breaking the whole widget. Elementor widgets seemed to me not to be very flexible with custom PHP. However, as @bainternet said, you can still use some JS, while trying to optimize the code and the DOM operations

**Comment by dbjpanda** [comment]
@bainternet Any hints please.

> This can only be achieved on the frontend via some custom JS handler that will populate the 2nd control values based on the first one. 

Do you mean a custom control?
