### ISSUE TITLE
Show/Hide Elements

### ISSUE THREAD

**Issue by Clubware** [elementor/elementor#8141]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I have a video playing but want to give people the option to read the transcript. I don't want to cover the video with an overlay. I don't want the video to stop or be interrupted in any way. I want people to be able to read along with the video.

**Describe the solution you'd like**

A button action would allow to show or hide specific elements.

**Describe alternatives you've considered**

Having it custom coded. Searching for a 3rd party plugin.

**Additional context**

**Comment by shilo-ey** [comment]
@Clubware 

Give your button a CSS ID or Class and catch the click event to run your action, for example, say your button as an ID of `MY_BTN` and you have a widget you want to show/hide with the ID of `MY_WIDGET` then you can catch the click event like this:

```Javascript
jQuery( document ).on( 'click',  '#MY_BTN', function( event ) {
   event.preventDefault();
   // Show/Hide the widget
   jQuery( '#MY_WIDGET' ).toggle();
});
```

Thanks
