### ISSUE TITLE
Trigger JS on control change

### ISSUE THREAD

**Issue by DeoThemes** [elementor/elementor#8144]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I'm trying to make slider widget with dynamic space between. The problem is when I adjust the spacing with CSS, Slick slider should recalculate JS and change width of the slides. Is there a way to trigger JS resize on control or widget change? I can't find proper hook for this. This is important as it also can be used for masonry, since the masonry has to be recalculated in preview as well.

**Comment by DeoThemes** [comment]
After searching I found similar thread here - https://github.com/elementor/elementor/issues/5153
I finally got it.

Here is the example of code if someone else need it.
**Reference code:**
` 
var deoSlickSlider = function( $scope, $ ) {

		// Watch the changes of spacing control
		if ( elementorFrontend.isEditMode() ) {
			elementor.channels.editor.on( 'change', function( view ) {
				let changed = view.elementSettingsModel.changed;

				if ( changed.slide_margin ) {
					$window.trigger("resize");
					$window.on('resize orientationchange', function() {
						$('.slick-testimonials').slick('setPosition');
					});
				}
			});
		}	
		
	}
`

**Comment by nimaaminz** [comment]
Doesn't works on repeaters controls ! 
can anyone help how to use on repeater controls
