### ISSUE TITLE
button On Click Method

### ISSUE THREAD

**Issue by khubdikar** [elementor/elementor#8146]
Dear Team
Please check this code
```HTML
<!-- Place this before your Lucky Orange tracking code -->
<script>
  window.loChatAvailable = true
  function loInitiateChat () {
    window.loChatAvailable ? LO.page() : LO.away_form()
  }

  function lo_chat_agent_unavailable () {
    window.loChatAvailable = false
  }

  function lo_chat_agent_available () {
    window.loChatAvailable = true
  }
</script>

<!-- You can add onclick="loInitiateChat()" to any element on the page -->
<a href="javascript:void(0);" onclick="loInitiateChat()">Chat with us</a> 
```
---------------------------------------------------------------------------------------------------
The Above code is lucky orange code, which enables chat option.

I want to enable chat option via button Click in Elementor.
I don't see any option of onClick in Elementor Widgets.

Plz Guide me on how to apply the below code on Button widget.

---------------------------------------------------------------------------------------------------------
```HTML
<!-- You can add onclick="loInitiateChat()" to any element on the page -->
<a href="javascript:void(0);" onclick="loInitiateChat()">Chat with us</a>
```

**Comment by khubdikar** [comment]
Dear Team
Please check this code


<script>
  window.loChatAvailable = true
  function loInitiateChat () {
    window.loChatAvailable ? LO.page() : LO.away_form()
  }

  function lo_chat_agent_unavailable () {
    window.loChatAvailable = false
  }

  function lo_chat_agent_available () {
    window.loChatAvailable = true
  }
</script>


a href="javascript:void(0);" onclick="loInitiateChat()">Chat with us</a>
---------------------------------------------------------------------------------------------------
The Above code is lucky orange code, which enable chat option.

I want to enable chat option via button Click in Elementor.
I don't see any option of onClick in Elementor Widgets.

Plz Guide me on how to apply the below code on Button widget.

---------------------------------------------------------------------------------------------------------

a href="javascript:void(0);" onclick="loInitiateChat()">Chat with us</a>




Regards
Ashwin P

**Comment by shilo-ey** [comment]
Hi @khubdikar 

1. Try adding the code in your footer as an enqueued script or as HTML block (less preferred)
```HTML
<script>
  window.loChatAvailable = true
  function loInitiateChat () {
    window.loChatAvailable ? LO.page() : LO.away_form()
  }

  function lo_chat_agent_unavailable () {
    window.loChatAvailable = false
  }

  function lo_chat_agent_available () {
    window.loChatAvailable = true
  }
</script>
```

2. Set `open-chat` as a class for the required button
3. add the following code in the footer as an enqueued script or as HTML block (less preferred)

```JS
jQuery( document ).ready( function( $ ) {
	$( document ).on( 'click', '.open-chat', function( event ) {
		event.preventDefault()
		loInitiateChat();
	} );
} );
```
