### ISSUE TITLE
Accessibility by Users

### ISSUE THREAD

**Issue by tomekwebdeveloper** [elementor/elementor#8148]
Hi. We need an extension that will allow us to control and adapt content for people with disabilities, people with visual impairments, etc. 

Something like that plugin: (https://pl.wordpress.org/plugins/userway-accessibility-widget/) 

We need this accessibility on dedicated widget.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Now as for your actual request, we feel that this should be a 3rd party plugin territory and we are actively developing such a 3rd party plugin https://wpaccessibility.io/ which you are welcome to try.

thanks.
