### ISSUE TITLE
Give possibility to set up column width 100% on desktop

### ISSUE THREAD

**Issue by land0r** [elementor/elementor#8150]
I saw [this feature request](https://github.com/elementor/elementor/issues/5072), but you just closed that almost year ago. It would be great if you give me wide comment about this feature, it is really important and give for users more flexibility in page building. I don't want to leave comment below this feature request, because as always there will be zero attention to it

The principles:
<img src="https://user-images.githubusercontent.com/696956/42735204-921b4b9e-8882-11e8-884a-9d4be27d5c08.png">

We discuss it in Russian community and I thought, that is small, but important feature. 
Thanks for attention, waiting for your feedback

**Comment by black-eye** [comment]
+1
Related to #2218

**Comment by shilo-ey** [comment]
I merged this issue with  #2218, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
