### ISSUE TITLE
Storefront Theme Header Disappear & Custom Elementor Footer

### ISSUE THREAD

**Issue by dmquin** [elementor/elementor#8152]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
When i set a Footer Template Condition to display in all pages, the Header of the Storefront theme disappears

## Steps to reproduce

1- Add a Custom Elementor Footer
2- Set condition to Entire Site

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win64) OpenSSL/1.1.1b PHP/7.3.3
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.3
	PHP Max Input Vars: 1000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2
	Site URL: http://localhost/qrc
	Home URL: http://localhost/qrc
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: es
	Timezone: Europe/Madrid
	Admin Email: dmqarg@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Storefront Child
	Version: 1.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Storefront
	Parent Theme Version: 2.5.0
	Parent Theme Author: Automattic

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.6
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 1.9.2
		Author: Flexible-Elementor-Panel.com

	JetWoo Widgets For Elementor
		Version: 1.1.1
		Author: CrocoBlock

	Slide Anything - Responsive Content / HTML Slider and Carousel
		Version: 2.3.1
		Author: Simon Edge

	Toolbar Extras
		Version: 1.4.3
		Author: David Decker - DECKERWEB

	UpdraftPlus - Backup/Restore
		Version: 1.16.14
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 3.6.2
		Author: Automattic

	WooLentor - WooCommerce Elementor Addons + Builder
		Version: 1.1.0
		Author: HT Plugins

	WP Create Multiple Posts & Pages
		Version: 1.0.0
		Author: Sajjadur Rahman Sagor

== Log ==
	: <table><thead><th>PHP: showing 2 of 2</th></thead><tbody class="elementor-log-entries"><tr><td>PHP: 2019-04-28 11:14:34 [notice X 2][C:\xampp\htdocs\qrc\wp-content\plugins\elementor\includes\template-library\manager.php::232] <strong>Undefined index: types_data</strong> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]</td></tr><tr><td>PHP: 2019-04-29 19:14:04 [notice X 1][C:\xampp\htdocs\qrc\wp-content\plugins\elementor-pro\modules\woocommerce\widgets\add-to-cart.php::130] <strong>Undefined index: post_id</strong> [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]</td></tr></tbody></table><table><thead><th>JS: showing 16 of 16</th></thead><tbody class="elementor-log-entries"><tr><td>JS: 2019-04-29 20:46:37 [error X 1][http://localhost/qrc/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:60824] <strong>Cannot read property \&#039;query\&#039; of null</strong> </td></tr><tr><td>JS: 2019-04-30 18:58:58 [error X 4][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <http://localhost/qrc/wp-content/plugins/essential-addons-for-elementor-lite//assets/front-end/img/accordion.png> as `eael_accordion_bg` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:01:11 [error X 3][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `portfolio_thumb_image` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:01:11 [error X 3][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `portfolio_full_image` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:02:16 [error X 3][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `testimoni_image_1` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:02:26 [error X 2][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `testimoni_image_2` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:02:32 [error X 3][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.facebook.com/themesgrove> as `social_link` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:02:32 [error X 3][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.twitter.com/themesgrove> as `social_link` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:02:32 [error X 3][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.linkedin.com/themesgrove> as `social_link` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:03:05 [error X 1][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.facebook.com/themesgrove> as `team_4_social_link` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:03:05 [error X 1][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.twitter.com/themesgrove> as `team_4_social_link` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:03:05 [error X 1][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.linkedin.com/themesgrove> as `team_4_social_link` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:03:31 [error X 2][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `slider_image` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:03:48 [error X 2][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `slider_animation_image` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:04:08 [error X 2][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `tgx_slider_3_image` value. Expected array or object.',
)]</td></tr><tr><td>JS: 2019-04-30 19:04:08 [error X 2][http://localhost/qrc/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.5.1:666:36] <strong>An invalid argument supplied as multiple control value</strong> [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <https://www.themesgrove.com> as `tgx_slider_3_button_link` value. Expected array or object.',
)]</td></tr></tbody></table>

</details>

**Comment by bainternet** [comment]
@dmquin 

This is the correct behavior in themes that don't support elementor [Theme Location API](https://developers.elementor.com/theme-locations-api/) to avoid broken markup in cases when a theme opens an HTML element (ex: div) in the header and closes it in the footer.


thanks.
