### ISSUE TITLE
Elementor Pro "Page Template" Condition

### ISSUE THREAD

**Issue by JoelEadeDesign** [elementor/elementor#8155]
I have use-case whereby different pages require different headers/footers. Having the choice to create a [page template](https://developer.wordpress.org/themes/template-files-section/page-template-files/) to manage this would be helpful.

![image](https://user-images.githubusercontent.com/1729832/57995829-82259780-7b07-11e9-81a9-d3b9d00ac60e.png)

The workaround from ticket [5792](https://github.com/elementor/elementor/issues/5792) isn't suitable in my use-case, as the client would like the slug to behave as a top-level page e.g. `domainname.com/page-name`.

**Comment by bainternet** [comment]
@JoelEadeDesign 

Not sure I understand how adding a custom taxonomy which is the workaround suggested in #5792 has any effect on your permalinks (unless you explicitly insert them in the permalinks) so It's still a valid solution to your use case.

And if for some reason that is still not good enough you can always add your own conditions, for ex:

```php
add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) {
	class Page_Template_Condition extends ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base {
		public static function get_type() {
			return 'singular';
		}

		public static function get_priority() {
			return 30;
		}

		public function get_name() {
			return 'page_template';
		}

		public function get_label() {
			return __( 'Page Template' );
		}

		public function check( $args ) {
			return isset( $args['id'] ) && is_page_template( $args['id'] );
		}

		protected function _register_controls() {
			$this->add_control(
				'page_template',
				[
					'section' => 'settings',
					'label' => __( 'Page Template' ),
					'type' => \Elementor\Controls_Manager::SELECT,
					'options' => array_flip( get_page_templates() ),
				]
			);
		}
	}

	$conditions_manager->get_condition( 'singular' )->register_sub_condition( new Page_Template_Condition() );
}, 100 );
```

which will give you something like this:

<img width="798" alt="Screen Shot 2019-05-22 at 15 14 55" src="https://user-images.githubusercontent.com/660572/58173633-8509bf00-7ca4-11e9-9511-2e51173c98f8.png">


Just remember that this is an example and will probably never work with a non-theme page template (ex: Elementor Canvas...)

thanks.

**Comment by JoelEadeDesign** [comment]
Thanks @bainternet ! My knowledge of manipulating permalinks for CPTs is pretty limited, so that code snippet is perfect for my needs. Thanks!

**Comment by nndesign40** [comment]
Hello, can someone help me create a condition? The target is to create a template for pages that are a parent. For example, "every page that has children". I would be very happy because this part of Elementor is very new to me.

**Comment by JoelEadeDesign** [comment]
@nndesign40 I popped @bainternet snippet into ChatGPT, asked it to refactor for child pages and it gave me this, which I've tested and got working:

```
add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) {
	class Child_Page_Condition extends ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base {
		public static function get_type() {
			return 'singular';
		}

		public static function get_priority() {
			return 30;
		}

		public function get_name() {
			return 'child_page';
		}

		public function get_label() {
			return __( 'Child Page' );
		}

		public function check( $args ) {
			if ( isset( $args['id'] ) ) {
				$post = get_post( $args['id'] );
				return $post && $post->post_parent != 0;
			}
			return false;
		}

		protected function _register_controls() {
			// No controls needed as this condition checks if the page is a child page
		}
	}

	$conditions_manager->get_condition( 'singular' )->register_sub_condition( new Child_Page_Condition() );
}, 100 );

**Comment by nndesign40** [comment]
Thank you for the quick response and the brilliant idea. Unfortunately, your code was for "children's pages" but I needed it for "parent page" but the hint with ChatGPT is great! I would never have come up with that, but now ChatGPT has given me the right code. Thanks again!
