### ISSUE TITLE
Elementor Backend Language should depend on the user language

### ISSUE THREAD

**Issue by haemeulrich** [elementor/elementor#8159]
Today the language of Elementor is based on the Site Language. For non English speaking regions this is bad. How we work in Switzerland as an example:

The most of our sites are German or French. But almost everyone is using software in English. So if you have the site Language to German then Elementor ist running in German (at least the translated entries). This is confusing because help is English, Forums are English...
It would be extremely helpful if Elementor would use the language of the user settings in WordPress.

**Comment by arielk** [comment]
I merged this issue with another issue #5148 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
