### ISSUE TITLE
On screen margins and padding

### ISSUE THREAD

**Issue by MartyBell56** [elementor/elementor#8164]
As the features of Elementor and Elementor Pro increase, so does the raft of menus, settings and the learning curve.

Having done a little work in Oxygen and looked at CSS Hero, both offer something that Elementor currently does not, namely the capability to alter margins and padding in the onscreen page editor.

Pixel precision is obviously advantageous but it would be great to get the general spacing set up without recourse to the menus.

Obviously one could add CSS Hero as a plugin but it would be great not to have to.

**Comment by bainternet** [comment]
I merged this issue with  #5018 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
