### ISSUE TITLE
Ability to Choose Which Post Types are Displayed in Related Posts (Posts Widget)

### ISSUE THREAD

**Issue by KaiHeff** [elementor/elementor#8166]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The new 'related posts' is a great feature, but it only displays related posts of the same post type. There is no option to select and display different post types that are related by author or term.

**Describe the solution you'd like**
I would like the option to select which post types are displayed when using the 'related posts' option in Elementor's post widget.

**Describe alternatives you've considered**
I have considered:
 - Having the 'post type' selectable amongst 'author' and 'terms' in the 'Include By' query filter. 
 - Having all post types included by default (backend?), and having the ability to exclude unwanted posts by term (currently doable I think)
 - Moving 'related posts' from source, and instead have it as a selectable option when selecting a post type from source

**Additional context**
An example as to why this feature would be useful: 
Users often have both a profile page and the ability to make posts, list products, etc. It would be nice to display these different post types on their profile pages.

**Comment by shilo-ey** [comment]
Hi @KaiHeff 

The Related Posts option builds the query according to its context.
Meaning, based on the specific page/post/CPT the Posts widget is in.

Thanks.

**Comment by gravnetic** [comment]
There is a plugin called Related that allows you to select custom queries for your related posts for all post types.  I would look at using it if you want custom queries on related post items.  It think it can be extended to support search as well.

**Comment by KaiHeff** [comment]
Thank you both for your help.

Would it be possible to add custom query filters to add multiple custom post types while also filtering by current author, by putting something like below into functions.php? And would the 'exclude by' filters still work alongside the custom query ID? I wouldn't need to use the related posts option if this were possible. I don't really know much about coding, so apologies if the below is an abomination!

<?php
add_action( 'elementor/query/my_custom_filter', function( $query ) {
} );
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$query->set( 'post_type', [ 'custom-post-type1', 'custom-post-type2', 'custom-post-type3' ] );
} );
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$author_id = get_queried_object_id();
	$query->set( 'author', $author_id );
} );

**Comment by KaiHeff** [comment]
`<?php
add_action( 'elementor/query/my_custom_filter', function( $query ) {

} );

add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$query->set( 'post_type', [ 'custom-post-type1', 'custom-post-type2', 'custom-post-type3' ] );
} );
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$author_id = get_queried_object_id();
	$query->set( 'author', $author_id );
} );`

**Comment by KaiHeff** [comment]
`<?phpadd_action( 'elementor/query/my_custom_filter', function( $query ) {
} );
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$query->set( 'post_type', [ 'custom-post-type1', 'custom-post-type2', 'custom-post-type3' ] );
} );
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	$author_id = get_queried_object_id();
	$query->set( 'author', $author_id );
} );`
