### ISSUE TITLE
License to work on localhost (PC)

### ISSUE THREAD

**Issue by almasdepapel** [elementor/elementor#8169]
Hi, it would be interesting to have a license to work in local mode, and another to work on projects online and in production.

Keep in mind that as designers it is better to work locally and then take it to the web.

Thank you

**Comment by bainternet** [comment]
@almasdepapel 

see this: 
https://docs.elementor.com/article/159-i-use-elementor-with-a-localhost-can-the-license-be-transferred-to-the-real-server

**Comment by almasdepapel** [comment]
Hi, I mention this, because on the Elementor website I have it active with my domain. But in the local it tells me that there are no activations.

So I suggest you create one for localhost, not linked to domain or IP, obviously can not be used for a site in production and active.
