### ISSUE TITLE
Clean up the WordPress Elementor navigation and UI please!

### ISSUE THREAD

**Issue by gravnetic** [elementor/elementor#8170]
I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.  The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The Elementor admin menu UI is failing users!  

1.  I hardly think that there is a need for the Templates menu item.  However, if you do, I suspect it should have a priority higher than 'Elementor' menu which is handling settings.

2.  There is really no need for the templates menu item at all (READ NEXT ITEM).  I don't see any difference between the parent item of 'Templates' and 'Saved Templates' since one only shows the redundant child?  The submenu item of Popup is hardly an admin menu item as it is a TAB in the 'Templates' and the 'Theme Builder'.

3.  'Templates' and 'Theme Builder' are more or less the same functionality currently and should be combined into a single post list area!  Clean that up please into a single menu item.  It is so confusing for no apparent reason.

4.  Since the 'Templates' does not logically meet the main menu item as outlined above for a parent menu I don't support its position in the main menu, so please consider putting it in the Elementor menu item as it should have been all along.

Finally, the TABS are terrible!   I have to click the tiny 'saved templates' link everytime I want to find my dynamic templates.  I greatly appreciate that when you select the kind of template that it shows you some example options, but can't we just use the post list like every other Wordpress post page and possibly a post list filter?  <strong>If this were to be used all the basic features of WordPress such as my drag and drop list plugin would work as expected.</strong>

Cheers,

Jake

**Comment by shilo-ey** [comment]
Hi @gravnetic 

1. Templates menu item is an approach that we added to ease the use of Elementor Theme Builder for all of the users, technical ones and non-technical ones.
2. UI improvements are constantly under development and implemented on a regular base. I assume tabs changes will be implemented in the future.
3. quick tip - under saved templates click on "all" and see all of the templates: `https://yoururl.com/wp-admin/edit.php?post_type=elementor_library`

Thanks for the feedback.

**Comment by gravnetic** [comment]
Why would you close my ticket?

Wordpress has a clear menu structure and Elementor takes up a position in that menu already.  Since Templates and Saved Templates are redundant and popups is a child of Saved Templates there is absolutely no need for this menu item.  It doesn't make it easier and in fact, it makes it confusing when you have 'Theme Builder' and 'Templates' which are also the same thing.

KEEP IT DRY please!

**Comment by alexlii1971** [comment]
> 3. quick tip - under saved templates click on "all" and see all of the templates: `https://yoururl.com/wp-admin/edit.php?post_type=elementor_library`
> 
> Thanks for the feedback.

If so, why not display the tabs by default? :)
