### ISSUE TITLE
Persian date

### ISSUE THREAD

**Issue by mohammadr3z** [elementor/elementor#8171]
Hello
I want to add a Persian date to form widget.
How should I do this?

This code is for Persian date

<pre>
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (global = global || self, factory(global.fa = {}));
}(this, function (exports) { 'use strict';

  var fp = typeof window !== "undefined" && window.flatpickr !== undefined
      ? window.flatpickr
      : {
          l10ns: {}
      };
  var Persian = {
      weekdays: {
          shorthand: ["یک", "دو", "سه", "چهار", "پنج", "جمعه", "شنبه"],
          longhand: [
              "یک‌شنبه",
              "دوشنبه",
              "سه‌شنبه",
              "چهارشنبه",
              "پنچ‌شنبه",
              "جمعه",
              "شنبه",
          ]
      },
      months: {
          shorthand: [
              "ژانویه",
              "فوریه",
              "مارس",
              "آوریل",
              "مه",
              "ژوئن",
              "ژوئیه",
              "اوت",
              "سپتامبر",
              "اکتبر",
              "نوامبر",
              "دسامبر",
          ],
          longhand: [
              "ژانویه",
              "فوریه",
              "مارس",
              "آوریل",
              "مه",
              "ژوئن",
              "ژوئیه",
              "اوت",
              "سپتامبر",
              "اکتبر",
              "نوامبر",
              "دسامبر",
          ]
      },
      firstDayOfWeek: 6,
      ordinal: function () {
          return "";
      }
  };
  fp.l10ns.fa = Persian;
  var fa = fp.l10ns;

  exports.Persian = Persian;
  exports.default = fa;

  Object.defineProperty(exports, '__esModule', { value: true });

}));
</pre>

**Comment by shilo-ey** [comment]
Hi @mohammadr3z 

As you know, we are using Flatpickr library in the datepicker.

Simply add the code using jQuery to your themes `functions.php` file environment:
```PHP
function your_scripts() {
	?>
		<script>
		jQuery( document ).ready( function( $ ){
                    function waitForFlatpicker( callback ) {
                        if ( typeof window.flatpickr !== 'function' ) {
                            setTimeout( function() { waitForFlatpicker( callback ) }, 100 );
                        }
                        callback();
                    }
                    waitForFlatpicker( function(){
                        flatpickr.l10ns.fa = {
                            weekdays: {
								shorthand: ["یک", "دو", "سه", "چهار", "پنج", "جمعه", "شنبه"],
								longhand: [
									"یک‌شنبه",
									"دوشنبه",
									"سه‌شنبه",
									"چهارشنبه",
									"پنچ‌شنبه",
									"جمعه",
									"شنبه",
								]
							},
							months: {
								shorthand: [
									"ژانویه",
									"فوریه",
									"مارس",
									"آوریل",
									"مه",
									"ژوئن",
									"ژوئیه",
									"اوت",
									"سپتامبر",
									"اکتبر",
									"نوامبر",
									"دسامبر",
								],
								longhand: [
									"ژانویه",
									"فوریه",
									"مارس",
									"آوریل",
									"مه",
									"ژوئن",
									"ژوئیه",
									"اوت",
									"سپتامبر",
									"اکتبر",
									"نوامبر",
									"دسامبر",
								]
							},
                        };
                        //set translations
                        flatpickr.localize(flatpickr.l10ns.fa);
                        flatpickr('.flatpickr-input');
                        //set format
                        $('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'dd/mm/yyyy');});
                    });
        });
		</script>
	<?php
}
add_action( 'wp_footer', 'your_scripts' );
```

Thanks.

**Comment by mohammadr3z** [comment]
How do I get this?

https://github.com/bgsrb/flatpickr-jalali
