### ISSUE TITLE
Question: Disable Elementors drag & drop feature for custom widget

### ISSUE THREAD

**Issue by kmob2** [elementor/elementor#8174]
I developed my own basic WordPress plugin, a widget which creates a grid of the latest posts. It comes with my own custom built-in drag and drop solutions that can be used inside the live preview of the post/page or in the cutomizer, to reorder the content of the grid items (title, thumbnail, excerpt, date, author etc.).

Basic example: https://jsfiddle.net/aobrien/ru1Lcmqp/

When using Elementor, and adding the widget to the page, the built-in Elementor drag & drop feature is preventing me to interact with my own drag and drop function within the rendered widget section.
Whenever I start dragging anywhere within the rendered section of my widget, it acts like most other widgets, as if I want to reorder the position of that entire widget, rather than allowing me to interact with the section, so my drag & drop function is used.

I need to be able to drag & drop around within my rendered widget section, without triggering the Elementors drag and drop function.
I see certain widgets, such as the toggle and accordion widgets don't trigger the Elementors drag & drop function when trying to drag within those sections. They can only be rearrange by dragging the "edit" button (or using the Navigator). That's exactly what I would like to have in my widget. 

I couldn't find any info in the docs on how to disable the drag and drop. It's probably something super simple that I am missing.

I'm fully aware that the widget with all my functions will not work out of the box with Elementor, but before I tackle all the other issues, I need to get this sorted first.

How can I disable the drag and drop feature in my rendered widget section.

**Comment by kmob2** [comment]
Update: I did come across a single thread here, which suggested to use `event.stopPropagation()` on the element.

I ended up using this:

```
jQuery(function() {
	//In my case .grid-container-wrap is the most outer div element of the rendered widget, just before the .elementor-widget-container element.
	jQuery(".grid-container-wrap").mousedown(function(event) {
		event.stopPropagation();
	});
});
```

This does seem to work so far. However I am still curious on if there is an official way to do this, as part of the API, rather than a hack, to avoid possible unexpected issues.

**Comment by shilo-ey** [comment]
Hi @kmob2 

Elementor, as a Drag & Drop page builder, is using the dragging method and not designed for disabling it, therefore the answer to your question is no. there's no official way to do so. 

Thanks
