### ISSUE TITLE
Elementor Finder - Show Private/Draft Pages

### ISSUE THREAD

**Issue by lparkyn** [elementor/elementor#8175]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Elementor Finder is quite handy. However, it doesn't include private or draft post/pages in the Finder results list. We have a number of pages that are private for holding information for internal use by WP admin. These are referenced or updated somewhat often. So it would be nice to access them using Elementor Finder.
Does it make sense to offer this in future release? (PS: it does for us)

**Describe the solution you'd like**
Include private/draft pages/posts in Finder results.

**Describe alternatives you've considered**
Make it configurable whether to include private and/or draft post/pages in Finder results.

**Additional context**
n/a

**Comment by arielk** [comment]
long time, but as far as I know this is something that should work with posts or pages that built by Elementor, please check it again and let me know.

Thanks

**Comment by lparkyn** [comment]
Hi Ariel,
 
Elementor Finder will find Draft documents (marked draft using elementor
page settings). But, I have about a dozen pages marked Private that it won't
find. 
-lyle

  _____
