### ISSUE TITLE
Shadow feature for Header Template for Elementor Pro

### ISSUE THREAD

**Issue by ahan101** [elementor/elementor#8179]
**What problem is your feature request going to solve? Please describe.**
When making a header for the site in Elementor templates, there is not an option for a drop shadow to help it stand off of the main background.

**Describe the solution you'd like**
A drop shadow feature button in the settings. Turning it on will allow headers to stand off of a background with a similar color.  

**Describe alternatives you've considered**
Currently trying to accomplish the same effect by adding an additional section scrolling at the same rate. This results in a few different problems like a gap between the "shadow" and the main header or a white bar under the grey "shadow" part.

**Additional context**
![Shadow effect using another section scrolling at the same rate](https://user-images.githubusercontent.com/50925936/58199633-e7f85780-7c9e-11e9-83c8-23c793078171.PNG)

**Comment by shilo-ey** [comment]
Hi @ahan101 

As you can see in [Elementor's website](https://elementor.com/support/), you sure can create a shadow for the header.

Just use one section and apply box-shadow on it. [see more here](https://www.youtube.com/watch?v=PKIdWmNvQdQ).

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com) 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Thanks.
