### ISSUE TITLE
Horizontal align: Space-Evenly does not work Microsoft Edge

### ISSUE THREAD

**Issue by Deftwun** [elementor/elementor#8181]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor uses *justify-content: space-evenly* when setting a column's horizontal alignment to space-evenly. This works as expected in all browsers except Microsoft edge which may be related to this open bug:  
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15947692/

Also see https://caniuse.com/#feat=justify-content-space-evenly

## Steps to reproduce
Create a column in elementor, add several image elements with custom positionion width set to *inline*, set the column layout horizontal alignment to *space-evenly*. Looks as expected in all browsers except Microsoft Edge

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @Deftwun 

Thanks for reporting.
This is a browser related bug.

Unfortunately, The only thing I can offer right now is to use a different property and comment on the Microsoft thread.

Thanks

**Comment by Deftwun** [comment]
In case anyone else needs it I added a custom class to the column in elementor advanced tab and add some CSS to theme to get the expected behaviour

```
/* Fix MS Edge bug: https://github.com/elementor/elementor/issues/8181 */
.ms-edge-elementor-space-evenly-bug-fix .elementor-widget-wrap{
	justify-content: center !important;
}
.ms-edge-elementor-space-evenly-bug-fix .elementor-widget-wrap .elementor-element{
	margin:auto;
}
```
