### ISSUE TITLE
Unload scripts and styles if not used 

### ISSUE THREAD

**Issue by Rivmedia** [elementor/elementor#8188]
Typically if we choose to use elementor we use it across the entire site.  However recently we've used it on individual pages,  post types or taxonomies. 

I have since noticed that even if Elementor is not being used on a page,  there are scripts, styles and classes being inserted sitewide. 

For the time being we are using a plugin called WP Asset manager to "unload" these scripts and styles,  but the classes and inline scripts still remain. 

It would be good by default for elementor only loaded "anything" to do with elementor if there is something Elementor based on the page.   I don't really understand why this isnt good practice from the outset to reduce bloat.

**Comment by bainternet** [comment]
@Rivmedia 

Elementor Only loads its scripts and styles if its in use, If you are seeing Elementor assets on a page that doesn't use Elementor then you are probably logged in as a user and these assets are there to support the Finder functionality.

Thanks.

**Comment by Rivmedia** [comment]
@bainternet 

Yes you are correct,  I actually noticed that a few hours ago and was going to update this issue as a result.  One thing I would like to see removed is the class inserted into the body tag "elementor-default".   As it seems that is still present even when not logged in.  But obviously this is a minor thing. 

Thanks for updating.
