### ISSUE TITLE
Dimension control + isLinked false issue

### ISSUE THREAD

**Issue by pmallek** [elementor/elementor#8190]
When i create Dimension control and set isLinked default to 'false', other default values are not visisble. Example:

        $this->add_control(
            'test_margin',
            [
                'label' => __( 'Margin', 'plugin-domain' ),
                'type' => Controls_Manager::DIMENSIONS,
                'size_units' => [ 'px', '%', 'em' ],
                'default' => [
                    'top' => 16,
                    'right' => 0,
                    'bottom' => 8,
                    'left' => 0,
                    'isLinked' => false
                ],
                'selectors' => [
                    '{{WRAPPER}} .your-class' => 'margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};',
                ],
            ]
        );

And final result:

![dimension_islinked](https://user-images.githubusercontent.com/6318627/58311685-d089ad80-7e09-11e9-8545-cb5291239cf9.png)

When i change 'isLinked' to true (or remove it so it's default true) values are displayed properly.

**Comment by jscontrust** [comment]
I think you have to define the default values as strings:

            'default' => [
                'top' => '16',
                'right' => '0',
                'bottom' => '8',
                'left' => '0',
                'isLinked' => false
            ],

Then they are shown in the Editor. But I have the problem, that they are not applied until you touch the control. [I created this issue for that](https://github.com/elementor/elementor/issues/9345)
