### ISSUE TITLE
Change button title from "Edit with Elementor" to "Elementor"

### ISSUE THREAD

**Issue by AiratHalitov** [elementor/elementor#8191]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

"**Edit with Elementor**" button looks too big and takes a lot of space in Gutenberg editor when **Top Toolbar** is activated. 
You can see details on this gif:
![ENG](https://user-images.githubusercontent.com/4050715/58349497-e84e4980-7e7c-11e9-9108-0cbbf0283f15.gif)

The button looks much bigger in other languages. For example in Russian it will be "**Редактировать в Elementor**". The top panel is shifted too much to the right.
You can see details on this gif:
![RUS](https://user-images.githubusercontent.com/4050715/58349543-074cdb80-7e7d-11e9-9c00-2a183bfce29c.gif)

**Describe the solution you'd like**

I propose to replace button text from "**Edit with Elementor**" to "**Elementor**". You can see the result in the gif files above.
It will be better for interacting with other plugins. In my example I used Yoast SEO and WPGlobus plugins. As you can see Yoast SEO plugin is using the button with logo (without any text) and this is looks great and compact.
"Edit with Elementor" text was written before Gutenberg editor was included in WordPress and should be updated for Gutenberg.

**Additional context**

- Elementor 2.5.15
- Gutenberg 5.7.0
- WordPress 5.2.1
- Yoast SEO 11.2.1
- WPGlobus 2.2.3

**Related files:**
https://github.com/elementor/elementor/blob/master/modules/gutenberg/module.php#L95

**PR:** #8192

**Comment by shilo-ey** [comment]
Hi @AiratHalitov 

Thanks for your feedback and for your contribution.

For UX reasons, I don't see us implementing this PR (might cause confusion amongst new users).

For now, you can use string replace to change this string.
for your convinence I added a snippet here, feel free to add it to your `function.php`

```PHP
function replace_text($text) {
	$text = str_replace('Edit with Elementor', 'Elementor', $text);
	return $text;
}
add_filter('gettext', 'replace_text');
```

**Comment by AiratHalitov** [comment]
You can add tips for newbies for better UX.
