### ISSUE TITLE
Fatal error system info

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#8194]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello, 
When using system info i get the following PHP Fatal error (PHP7.3):

2019/05/25 11:11:49 [error] 22654#22654: *3704 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::get_name() in /public/wp-content/plugins/elementor/core/logger/loggers/base.php:80
Stack trace:
#0 /public/wp-content/plugins/elementor/core/logger/log-reporter.php(39): Elementor\Core\Logger\Loggers\Base->get_formatted_log_entries(20, true)
#1 /public/wp-content/plugins/elementor/includes/settings/system-info/classes/abstracts/base-reporter.php(105): Elementor\Core\Logger\Log_Reporter->get_log_entries()
#2 /public/wp-content/plugins/elementor/includes/settings/system-info/main.php(266): Elementor\System_Info\Classes\Abstracts\Base_Reporter->get_report('')
#3 /public/wp-content/plugins/elementor/includes/settings/system-info/main.php(147): Elementor\System_Info\Main->load_reports(Array)

## Steps to reproduce
1. Run system info

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
I cannot get system info for reason above. 
</details>

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by scrobbleme** [comment]
Same here. 
Why is this closed? This is a bug report. Isn't solved.

**Comment by scrobbleme** [comment]
@shilo-ey This is releted to corrupted `elementor_log` data in in the `options` table. If I delete this -> the report ist working again...

**Comment by kirchnerto** [comment]
@scrobbleme What exactly did you delete? I'm facing the same issue on my site.

**Comment by scrobbleme** [comment]
> @scrobbleme What exactly did you delete? I'm facing the same issue on my site.

The entry with `meta_key="elementor_log"` from `wp_options`.

**Comment by indigitpt** [comment]
The problem is PHP Version. We were getting same issue at PHP7.3, upgrading to 7.4 or downgrading to 7.2 fixes the issue :) . Try also disable Opcache Temporary to debug the issue

**Comment by mwittmann** [comment]
This is still an open issue. It's occurring for me on the latest version of WP (v.5.4.1) and Elementor (v.2.9.8, Pro v.2.9.4). `PHP Version 7.2.30`. As suggested I tried:

    DELETE FROM wp_options WHERE option_name = "elementor_log";

The above makes no difference.
  
    [14-May-2020 07:52:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::get_name() in /home/myhome/sites/mysite.org/wp-content/plugins/elementor/core/logger/loggers/base.php:80
    Stack trace:
    #0 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/core/logger/log-reporter.php(64): Elementor\Core\Logger\Loggers\Base->get_formatted_log_entries(20, false)
    #1 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/modules/system-info/reporters/base.php(105): Elementor\Core\Logger\Log_Reporter->get_log_entries()
    #2 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/modules/system-info/module.php(262): Elementor\Modules\System_Info\Reporters\Base->get_report('html_')
    #3 /home/myhome/sites/mysite.org/wp-content/plugins/elementor/modules/system-info/module.php(151): Elementor\Modules\System_Info\Module->load_reports(Array, 'html')
    #4 /home/myhome/sites/mysite.org/wp-includes/class-wp-hook.php(287): Elementor\Modules\System_Info\Module->display_page('')
    #5 /home/dharmag1/sites/dharm in /home/myhome/sites/mysite.org/wp-content/plugins/elementor/core/logger/loggers/base.php on line 80

**Comment by embertech1** [comment]
I am also having this error when trying to load 'system info'

Installed is just Wordpress 5.5.1 with a basic theme OceanWP (also same issue with Twenty Twenty or Astra) and Elementor - nothing else.

Fatal error: Uncaught Error: Call to undefined method stdClass::get_name() in /home/sites/selectasofa.co.uk/public_html/wp-content/plugins/elementor/core/logger/loggers/base.php:80 Stack trace: #0 /home/sites/selectasofa.co.uk/public_html/wp-content/plugins/elementor/core/logger/log-reporter.php(64): Elementor\Core\Logger\Loggers\Base->get_formatted_log_entries(20, false) #1 /home/sites/selectasofa.co.uk/public_html/wp-content/plugins/elementor/modules/system-info/reporters/base.php(105): Elementor\Core\Logger\Log_Reporter->get_log_entries() #2 /home/sites/selectasofa.co.uk/public_html/wp-content/plugins/elementor/modules/system-info/module.php(262): Elementor\Modules\System_Info\Reporters\Base->get_report('html_') #3 /home/sites/selectasofa.co.uk/public_html/wp-content/plugins/elementor/modules/system-info/module.php(151): Elementor\Modules\System_Info\Module->load_reports(Array, 'html') #4 /home/sites/selectasofa.co.uk/public_html/wp-includes/class-wp-hook.php(287): Elementor\Modules\System_Info\Module->display_page('') in /home/sites/selectasofa.co.uk/public_html/wp-content/plugins/elementor/core/logger/loggers/base.php on line 80
There has been a critical error on your website. Please check your site admin email inbox for instructions.
