### ISSUE TITLE
Right Click Context Menu ALTERNATIVES

### ISSUE THREAD

**Issue by Sognista** [elementor/elementor#8196]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sognista** [comment]
THe Right context menu doesn't work in Chrome.
Every item in the menu is achievable by other ways except "save as template" inherited by a single section/column/widget, so I strongly suggest to add this feature in the Navigator.

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


As for your issue - you can always enable the editing handles.
Go to Settings > Advanced > Editing Handles > Enable.

![image](https://user-images.githubusercontent.com/45009641/58378396-a49e3180-7f9b-11e9-8473-df0527436f31.png)


thanks.

**Comment by Sognista** [comment]
Hello Shilo-ey,
thank you for your reply, but I think you miss the point.
That's not my personal problem, it's a problem concerning EVERY CHROME OS systems.
Using browser Chrome in Chromebook (Chrome OS) the Elementor contextual right click menu is hidden.

**Comment by Sognista** [comment]
In Chrome on Chromebook, when you righ click everywhere on Elementor (including the plus sign etcetera) it shows only the default Chrome contexctual menu, so it's IMPOSSIBLE to:
- copy / past single elements
- save as template

![elementor right click menu issue chrome os chromebook](https://user-images.githubusercontent.com/11969112/76681107-a2bb6280-65ef-11ea-8ef4-bdecf7d824f1.png)

**Comment by Sognista** [comment]
Sorry Shilo-ey,
you right this wasn't a general issue, I have just discovered it was due to an extension I had that force the Chrome contextual menu to show always on right click so it was covering the Elementor contextual menu, MY APOLOGIES!!!
You can keep the ticket closed, then, and sorry for bothering you 👍 

Yuri
