### ISSUE TITLE
Autoplay Video On hover effect

### ISSUE THREAD

**Issue by glaringeye76** [elementor/elementor#8200]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/
![Video Hover Effect](https://user-images.githubusercontent.com/50119409/58383983-1c9b4480-7ffa-11e9-9b8c-98b67d59188f.JPG)

Video Hover effect - I am using elementor pro on wordpress. I have attached an image. With reference to the image, I wanted to request for a feature. Till now you see the thumbnails of the product, when we hover over the product the trailer video of the product start playing. How can add this feature to my website?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by get8bit** [comment]
+1 on this feature! Please add this.

**Comment by wlopz** [comment]
+1 on this feature as well!

**Comment by Likwix** [comment]
+1 on this feature as well!

**Comment by benkaranja** [comment]
+1 on this feature! Please add this.

**Comment by USDESIGN** [comment]
+1 on this feature! Please add this.

**Comment by DaKSK** [comment]
As the issue is closed, does this mean there's a feature now that can do this?

**Comment by collingibson** [comment]
+1 on this feature! Please add this.

**Comment by Chertii** [comment]
+1 on this feature!

**Comment by briannyagol** [comment]
+1 on this feature

**Comment by SirotyukD** [comment]
+1 on this feature

**Comment by feperrella** [comment]
+1 on this feature!

**Comment by leansights** [comment]
+1 on this feature as well

**Comment by weboost-fr** [comment]
+1

**Comment by fernanda-herrera** [comment]
yes please add it

**Comment by ibantxillo** [comment]
+1, yes please add it

**Comment by isaacgalvan10** [comment]
+1, please add the play on hover feature!

**Comment by Kenerpo** [comment]
+1 on this feature! Please add this.

**Comment by JoelEadeDesign** [comment]
+1 please :)
