### ISSUE TITLE
Control Color - UX Improvement

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#8203]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Please add alpha percent value when dragging alpha range: http://prntscr.com/ntus6u

For now, to know exactly what alpha value is, we have to focus on textfield end move to end of this field.

It will be better to show directly alpha value like this: http://prntscr.com/ntuubm

**Comment by shilo-ey** [comment]
I merged this issue with #6968, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
