### ISSUE TITLE
WordPress REST API - create new post with Elementor

### ISSUE THREAD

**Issue by tmikeska** [elementor/elementor#8205]
hi, is there a way to use WordPress REST API to create a new post to support Elementor? I have an Laravel-based application with wysiwyg editor creating new posts in WP, but syncing them with Elementor-based posts does not keep the layouting.

**Comment by bainternet** [comment]
@tmikeska 	

There is if you know what you are doing and how Elementor stores its data. Meaning to achieve that Elementor and WordPress provide all of the needed functions and methods, it just requires major custom coding.

thanks
