### ISSUE TITLE
Mobile and Tablet Display of elements

### ISSUE THREAD

**Issue by Tris055** [elementor/elementor#8209]
Hello,

I am busy with a website www.padmoshoeve.nl . I built the website with Elementor and checked all responsive modes. But when i open the website on Mobile version in live view its not showing all the elements. 

Could someone tell me why its not working correctly? I checked all buttons of responsive mode and no content is hidden by Elementor responsive buttons. When i am in editor mode everyting looks great..

Hope u guys can help me out.

Tristen

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
