### ISSUE TITLE
Is there any way I can get extend class Portfolio?

### ISSUE THREAD

**Issue by PhongGCS** [elementor/elementor#8210]
I am using Elementor Pro. I would like to use the Portfolio Widget. But Portfolio only show image, title. I would like to show ACF for it. I try to edit on portfolio.php at the render_post() function that is working.  But It would be removed when updating  plugin.
So Do you have any way to use ACF in this case.

More thing
I am develop a elementor extention plugin. Is there any way to extend class Portfolio?

**Comment by bainternet** [comment]
@PhongGCS 

Portfolio widget is just like any other Elementor widget which means you can simply extend the widget class an override the only the methods you want, for example, if I want to replace the title and show with a code of my own, I can do something like this:

```PHP

add_action( 'elementor/widgets/widgets_registered', function( $widgets_manager ) {
	class Phong_Portfolio extends \ElementorPro\Modules\Posts\Widgets\Portfolio {
		public function get_name() {
			return 'phong-portfolio';
		}

		public function get_title() {
			return 'Phong Portfolio';
		}

		// Override the title as you need
		public function render_title() {
			// do your stuff
		}
	}

	$widgets_manager->register_widget_type( new Phong_Portfolio() );
}, 250 );
```

Thanks.

**Comment by pablobb** [comment]
This is not a perfect solution, because changing return of get_name() causes no default settings from javascript and portfolio section is broken.

**Comment by blaifm** [comment]
This has worked until I started trying late Elementor DEV versions. I have installed 3.5.0-dev9 - 2021-08-27 and it seems to be ignoring this code snippet.
Is there any change I should do to the code that targets the widget again?

**Comment by alibori** [comment]
> This has worked until I started trying late Elementor DEV versions. I have installed 3.5.0-dev9 - 2021-08-27 and it seems to be ignoring this code snippet. Is there any change I should do to the code that targets the widget again?

I have this issue too. Any solution?

**Comment by symplTech** [comment]
After extending this class it all works perfect but the filter bar doesn't seem to response.

**Comment by symplTech** [comment]
@bainternet This doesn't work anymore.. doesn't load the js for the filters

**Comment by absikandar** [comment]
I was able to modify the Default Portfolio widget using the code below. 

This creates the following layout. 

1) Remove thumbnail overlay including link. 
2) Display Post Title Under Image.
3) Display Post Excerpt under Post Title with read more link.

![Uploading image.png…]()


```
//extends default portfolio widget
add_action( 'elementor/widgets/register', function( $widgets_manager ) {
	class New_Portfolio extends \ElementorPro\Modules\Posts\Widgets\Portfolio {
		
		protected function render_post_header() {
			global $post;
	
			$tags_classes = array_map( function( $tag ) {
				return 'elementor-filter-' . $tag->term_id;
			}, $post->tags );
	
			$classes = [
				'elementor-portfolio-item',
				'elementor-post',
				implode( ' ', $tags_classes ),
			];
	
			// PHPCS - `get_permalink` is safe.
			?>
			<article <?php post_class( $classes ); ?>>
			<?php
		}

		protected function render_post_footer() {
			?>
			</article>
			<?php
		}

		protected function render_post_excerpt() { ?>
			<div class="elementor-portfolio-item__excerpt">
				<?php
					$more = sprintf( ' <a class="more" href="%1$s">%2$s</a>', get_permalink( get_the_ID() ), __( 'MORE', 'text_domain' ) );
					echo wp_trim_words( get_the_excerpt(), 20, $more );
				?>
			</div>			
			<?php
		}

		protected function render_post() {
			$this->render_post_header();
			$this->render_thumbnail();
			$this->render_overlay_header();
			$this->render_title();
			$this->render_post_excerpt();
			//$this->render_categories_names();
			$this->render_overlay_footer();
			$this->render_post_footer();
		}
	}

	$widgets_manager->register( new \New_Portfolio() );
}, 250 );
```

**Comment by absikandar** [comment]
I have written a small plugin for modifying default portfolio layout. Here is the complete post on it. 
https://wppatch.com/how-to-modify-portfolio-widget-in-elementor-pro/
