### ISSUE TITLE
Popup Builder Entrance Animation

### ISSUE THREAD

**Issue by purepixels** [elementor/elementor#8212]
## Prerequisites

- [yes] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [yes ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Is it possible to add extra Entrance Animations  to the Popup Builder?
Animations like Push and slide. Just like this addon:

https://powerpackelements.com/demo/offcanvas-content/

Regards,
Jeroen

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
