### ISSUE TITLE
Recaptcha V3 Request

### ISSUE THREAD

**Issue by mdrideout** [elementor/elementor#8213]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Requesting that Recaptcha V3 be integrated with Elementor forms. Contact Form 7 recently moved to Recaptcha V3. This is great because there is no user interaction required for it to work.

Elementor forms needing the V2 implementation seems outdated, and for lead generation forms is bad for conversion optimization. 

**Describe the solution you'd like**

Elementor forms to support Recaptcha V3

**Describe alternatives you've considered**

Using contact form 7, but I want to use Elementor's form builder. 

**Additional context**

**Comment by dalarso** [comment]
+1

**Comment by bainternet** [comment]
Related: #6454

**Comment by FlyThePlanet** [comment]
+1

**Comment by lpcoding** [comment]
+1

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!
