### ISSUE TITLE
Custom Code Theme Hook Feature (Like Astra Custom Layouts)

### ISSUE THREAD

**Issue by mdrideout** [elementor/elementor#8214]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I am trying to integrate custom code into my site, that I want to show up in certain areas on specific pages only, or only in specific conditions. (Tracking and analytics codes, special animation scripts, etc.)

**Describe the solution you'd like**

Astra Custom Layouts feature allows you to create custom HTML, Javascript, and PHP code to be hooked into the theme in various areas. As part of the transition away from Astra and into "Hello", this is a feature I'd be very interested in having. 

**Describe alternatives you've considered**

Continuing to use Astra.

**Additional context**

**Comment by bainternet** [comment]
@mdrideout 

The main idea of using a Theme like Hello is to use Elementor Theme Builder functionality with maximum support.

meaning if you can create a section template with the Custom HTML, CSS and JavaScript for example and using the theme builder you can Drag 'n Drop it anywhere you want, there is no need for hooks.

As for PHP code, Elementor has its own hooks which you can hook your PHP code to, please see our [developers docs](https://code.elementor.com/php-hooks/).

Thanks.
