### ISSUE TITLE
Font Awesome Symbol issue + suggested fix.

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#8217]
Relates to Version 2.5.16
File: elementor/assets/lib/font-awesome/css/font-awesome.min.css?ver=4.7.0
.fa-mail-reply:before,.fa-reply:before{content:"\f112"}

Issue:
/f112 NON existant Font Awesome symbol.

Suggested Fix:
Update Font-Awesome to latest version

**Comment by shilo-ey** [comment]
I merged this issue with  #4430 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
