### ISSUE TITLE
Center icon list icons

### ISSUE THREAD

**Issue by theDanielJLewis** [elementor/elementor#8219]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Wide and narrow icons in an icon list look weird due to default left alignment.

**Describe the solution you'd like**
Either default `.elementor-icon-list-icon` to `text-align: center;`, or else give an icon-alignment option.

**Additional context**
Current view with default left alignment. Notice the weird gaps between the icons and the text.
<img width="197" alt="Left" src="https://user-images.githubusercontent.com/154936/58504751-52a30a80-8159-11e9-9284-05f82e1c10dc.png">

Custom-CSS view with center alignment.
<img width="201" alt="Center" src="https://user-images.githubusercontent.com/154936/58504750-52a30a80-8159-11e9-84e0-1b28119f842f.png">

**Comment by shilo-ey** [comment]
Hi @theDanielJLewis 

Thanks for your feedback.

We will consider adding this option in the next major release.

Thanks

**Comment by Helmi** [comment]
@shilo-ey out of curiosity: By putting it on a milestone are you still considering a change or is this means as a clear indication as what will come in this release? Just curious as there's some stuff on the 2.6.0 milestone that I'm waiting for quite a long time. It's crucial for me to know if this is coming or only be considered and possibly thrown away again.

**Comment by shilo-ey** [comment]
A pull request has been submitted to our review team.

If they will find it Ok, it will be in v2.6.0

Thanks
