### ISSUE TITLE
Avoid duplicate

### ISSUE THREAD

**Issue by divinedot** [elementor/elementor#8225]
I have used different widget in my post page like 'Related post widget' 'Recent post' and 'Normal post widget'. I found that I am getting duplicate posts in different secitons. I have tried to remove duplicate posts from different widget but it is not working. I have used 'avoid duplicate' option in my home page and its working but in my post page its not working. How can I remove duplicate post from my post page.
Home page link - https://fitandelegant.com/
Post page link - https://fitandelegant.com/how-to-apply-foundation-for-facial-perfection/

**Comment by nuritsha** [comment]
Hi @divinedot,

Thank you for reaching out, in order to investigate I need access to the site admin. 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.
