### ISSUE TITLE
[Pro] Archive post settings won't accept HTML elements

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#8226]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In Elementor Pro > Archive Posts Widget > Content, a ```<br>``` tag in the "Nothing Found Message" text field will not render as HTML (whereas it does elsewhere, eg Headings Widget).

Example:

![image](https://user-images.githubusercontent.com/1435638/58600736-ef35eb80-82c4-11e9-87f9-ae6154c40962.png)

![image](https://user-images.githubusercontent.com/1435638/58600746-f65cf980-82c4-11e9-9d33-8a27a53b5911.png)

**Comment by drawcard** [comment]
Just another observation (maybe this needs a seperate bug report) - the search message seems to be constrained by the width of the column settings. So for example, if you have the widget set to display items in a 3 column row, that search message will be constrained to 33% the width of the page.

**Comment by shilo-ey** [comment]
Hi @drawcard 

The "Nothing Found Message" is escaped by default and that's why you're seeing the HTML tags.

However, luckily, if you want to bypass this escaping, we have implemented a filter hook that allows you to do just that:
```PHP
add_filter( 'elementor_pro/theme_builder/archive/escape_nothing_found_message', '__return_false' );
```

Thanks

**Comment by asanger** [comment]
Is there an update for this? The above filter doesn't seem to be working for me.

**Comment by TrigodaUG** [comment]
We have the same problem currently on themes that are for Product Searches. Not search result, no HTML in message. The filter does not help.
