### ISSUE TITLE
After disabled Lightbox it is still working on frontend

### ISSUE THREAD

**Issue by aktarujjman** [elementor/elementor#8227]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
I am developing a WordPress theme where I am using Magnific Popup. So, I want to disable Elementor lightbox when my theme is activated.

```php
function cafetora_load_elementor_options() {  

    update_option( 'elementor_disable_color_schemes', 'yes' );
    update_option( 'elementor_disable_typography_schemes', 'yes' );
    update_option( 'elementor_global_image_lightbox', 'no' );
}

add_action( 'after_switch_theme', 'cafetora_load_elementor_options' );
```

I used  **after_switch_theme** hook to do that and Image Lightbox option is disabling fine but popup still working on frontend.

![image](https://user-images.githubusercontent.com/16398283/58616693-1ea62180-82e0-11e9-94fa-0c6249e1e756.png)

![image](https://user-images.githubusercontent.com/16398283/58616740-38dfff80-82e0-11e9-9ba0-c817ff96205a.png)

**Phpmyadmin:**
![image](https://user-images.githubusercontent.com/16398283/58616814-6e84e880-82e0-11e9-8fe9-f1eb4a879a59.png)

When I save again the option from the dashboard then the lightbox successfully stopped working.

What is the issue? Am I used the correct method to disable it?

**Comment by bainternet** [comment]
@aktarujjman 

if you want to disable the global lightbox via the Options API, simply set the value to an empty string, ex:

```PHP
update_option( 'elementor_global_image_lightbox', '' );
```

thanks.
