### ISSUE TITLE
Klaviyo integration coming anytime soon ? 

### ISSUE THREAD

**Issue by LexGabrees** [elementor/elementor#8232]
Hi,

Klaviyo is arguably the best ESP for ecommerce related sites. It would be a great addition to have an integration in Elementor for Klaviyo .... 

Lex

**Comment by bainternet** [comment]
@LexGabrees 	

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by evanomondi** [comment]
I see this as closed, is there a solution to it?

**Comment by maxtabi** [comment]
I want this feature so bad ! please integrate Klaviyo with Elementor !

**Comment by patrick-kontukids** [comment]
+1

"I got a fever! And the only prescription.. is Klaviyo!" 🐮🔔

Klaviyo is a beast and by far the best value/service for an eCommerce site like mine. Klaviyo already integrates well with WooCommerce for new customers, abandoned carts, etc. but for newsletter sign-up forms you still need to purchase a plan from Zapier for around $30-50 depending on your sign-up volume. That blows.

Elementor could start by releasing a Klaviyo integration for forms that adds a user to the default Newsletter list in Klaviyo. Later if interest is there, release deeper integrations (list selection, tagging, etc.)

**Comment by achchu93** [comment]
I have the plugin for it. currently user can be added to a list. But if more features are requested by the users will do them. Will publish it to codecanyon this weekend. Contact me through achchu.zats@gmail.com

**Comment by achchu93** [comment]
https://klaviyotor.brixyt.com/ Here it is!

**Comment by lavellotron** [comment]
Lex. The Buy Now button doesn't seem to work.

**Comment by achchu93** [comment]
> Lex. The Buy Now button doesn't seem to work.

Hey it works now! Check it out. With more options...

**Comment by patrick-kontukids** [comment]
Awesome, thanks!

*  Patrick Greenwood *- Founder
  p: 415-810-0672 <//415-810-0672>    e: patrick@kontukids.com    w:
kontukids.com <https://www.kontukids.com>


  Shop <https://kontukids.com>     Facebook
<https://www.facebook.com/kontukids/>     Twitter
<https://twitter.com/kontukids>     Instagram
<https://www.instagram.com/kontukids/>     YouTube
<https://www.youtube.com/channel/UCzHPsGbBlnSr2a64fD9NZug>

This transmission, including any attachments, may contain Confidential
and/or proprietary information. If you have received this correspondence in
error, please delete it and notify the sender immediately.
