### ISSUE TITLE
Use of ACF Email field in a Dynamic URL field should prepend mailto:

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#8234]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

If you use an ACF Email field in an Elementor Dynamic URL field (like in the Button widget), Elementor uses the email address directly in the href attribute... rendering it useless.

Elementor should detect this combination (ACF Email field + Elementor Dynamic URL field) and automaticaly prepends "mailto:" in the href attributes...

## Steps to reproduce

Create a Button widget.
Set the URL field to use an ACF Email field.
Click the resulting button.

**Comment by shilo-ey** [comment]
Hi @tristanleboss 

Thanks for your feedback.

The behavior you provided cannot be reproduced.

![image](https://user-images.githubusercontent.com/45009641/58791603-2ecd4200-85fb-11e9-90f9-3d07ad821bfe.png)

This is the validation we are doing in our code:

![image](https://user-images.githubusercontent.com/45009641/58791848-a69b6c80-85fb-11e9-8f10-4da38719c522.png)



Thanks

**Comment by shilo-ey** [comment]
After inspecting this issue again we have found that the ACF dynamic field is not being retrieved in preview mode and we are working on a solution.

Please check your button in a published page.

**Comment by iamdanbarrett** [comment]
Did this issue ever get resolved? I am having the exact same issue...

**Comment by joelnewcomer** [comment]
+1 to making this happen please!

**Comment by sitzt** [comment]
Same problem with Version 2.9.6 / PRO Version 2.9.1
