### ISSUE TITLE
override an existing widget?

### ISSUE THREAD

**Issue by stivoox** [elementor/elementor#8235]
Hi Friends . 
I just want to know how to override an existing elemntor widget , I can't find any solution .
regards

**Comment by crazypsycho** [comment]
You have to unregister the old widget and register your widget.

[code]
add_action('elementor/widgets/widgets_registered', function($widgetsManager) {
  $widgetsManager->unregister_widget_type( 'slug-of-old-widget' );
  $widgetsManager->register_widget_type( new MyWidget() );
});
[/code]

**Comment by bainternet** [comment]
@stivoox 

please see our developer docs at https://developers.elementor.com/creating-a-new-widget/ And if you have a specific question we would be happy to help.

**Comment by stivoox** [comment]
@bainternet : I tried to override the image scroll page but the live preview doesn't work , the original widget doesn' have _content_template function

**Comment by Tofandel** [comment]
For anyone like me stumbling here in the future the hook has changed

It's now

```php
add_action('elementor/widgets/register', function($widgetsManager) {
  $widget = new MyWidget();
  $widgetsManager->unregister_widget_type( $widget->getName() );
  $widgetsManager->register_widget_type( $widget );
});
```
