### ISSUE TITLE
Enhancement: add dynamic capabilities to Star Rating widget

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#8237]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Missing dynamic capabilities in the Star Rating widget.

**Describe the solution you'd like**
Add dynamic capabilities to the Star Rating widget.

**Additional context**
Currently I can only display only fixed rating values. In my use case, In my use case, I need to use the widget in posts with rating score saved by an external plugin in a custom field.

**Comment by ramiy** [comment]
Add dynamic capabilities to the "Rating" control. To allow users load data from "Custom Fields".

![elementor-star-rating](https://user-images.githubusercontent.com/576623/58748516-b3e11b80-8482-11e9-9539-8ef48d17b6be.png)

**Comment by ramiy** [comment]
Maybe the title can also receive dynamic capabilities?!

**Comment by shilo-ey** [comment]
Hey @ramiy

Thanks for your suggestion and for your PR.

Currently, this feature cannot be implemented because the dynamic tag doesn't support "number" fields.

See more here: #5952

Thanks!
