### ISSUE TITLE
Set the Menu Cart Widget to automatically open when a product is added.

### ISSUE THREAD

**Issue by ManageFlaiks** [elementor/elementor#8241]
Hi there, I'm trying to figure out how to set the Menu Cart Widget to automatically open when a "buy now" or "add to cart" button is pressed. There doesn't seem to be an option for that in the theme builder by the looks of it and I'm not too good with CSS so I'm having a difficult time having to figure that out. 

Just to reiterate I'm not looking for customers to be automatically transferred to flaiks.com/cart page but instead I would like the Cart Widget to serve as a cart page and automatically open up/slide into view when a product is added to the basket without the customer having to scroll all the way back up and having to click on the cart to see it's contents and proceed to the checkout. Thanks for your help, Dan.

**Comment by bainternet** [comment]
@ManageFlaiks 

This functionality is not something that is available in WooCommerce out of the box so we can't really support it.

thanks.

**Comment by Zach-Toth** [comment]
I've found a solution to this. Check out my gist: https://gist.github.com/Zach-Toth/ca5286dfd550c76ba890231e6869dad5

Works great on single product pages but still working out the kinks on archives
