### ISSUE TITLE
Social Icons: Bloglovin Missing

### ISSUE THREAD

**Issue by samerz816** [elementor/elementor#8242]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The social icons widget is great, however it is missing Bloglovin'. This is a very important social media network for serious bloggers. I'd imagine it would be a very simple fix - to simply add the Bloglovin' logo in the social icons widget drop down.

**Comment by shilo-ey** [comment]
I merged this issue with  #4430 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
