### ISSUE TITLE
Address book plugin

### ISSUE THREAD

**Issue by authenticlife** [elementor/elementor#8246]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by authenticlife** [comment]
Address book plugin

Hi - I have Elementor Pro and am wondering if any of you know of a compatible address book plugin where members can each have their own address book (and perhaps the form content can even be created with elementor???)

Please can anyone point me in the right direction, including providing a cost to create an address book for a wordpress member site.

The elements I need are first name | surname | ID/social security number | occupation e.g. dentist | relationship e.g. mother | 3 address lines | city | province | country | country code

Thanks and regards

**Comment by authenticlife** [comment]
Address book plugin

Hi - I have Elementor Pro and am wondering if any of you know of a compatible address book plugin where members can each have their own address book (and perhaps the form content can even be created with elementor???)

Please can anyone point me in the right direction, including providing a cost to create an address book for a wordpress member site.

The elements I need are first name | surname | ID/social security number | occupation e.g. dentist | relationship e.g. mother | 3 address lines | city | province | country | country code

Thanks and regards

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
