### ISSUE TITLE
Make Elementor forms responsive

### ISSUE THREAD

**Issue by authenticlife** [elementor/elementor#8247]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by authenticlife** [comment]
Needing a developer to make Elementor Forms Pro work as follows:
1) Each member of a wordpress member site must be able to fill in a standard form.
2) That member's form is saved along with the content the member filled in
- ideally, it must be routed to, stored in and downloadable via the Azure Cloud
3) The member must be able to retrieve the form and edit the information
4) The member must be able to email the content to an email address of their choice
5) An address book form needs to be created which can be prepopulated with certain fields entered onto forms

Can anyone do this form me and give me a cost please? Also, to make this secure, must I changed from wordpress to some other type of development?

Thanks and regards

susan@adimpact.co.za

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
