### ISSUE TITLE
Dark Mode Design Support

### ISSUE THREAD

**Issue by a13banger** [elementor/elementor#8249]
Love to see design support for device browsers using on-device Dark Mode themes. For example, Dark Mode is coming to iOS 13 and it would be nice to easily design alternate/dark mode themes for users who use dark mode on device in a similar manner to how we currently design for different device types currently in Elementor i.e. Desktop, tablet and mobile.

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/9263
