### ISSUE TITLE
Menu Cart Widget CSS

### ISSUE THREAD

**Issue by ManageFlaiks** [elementor/elementor#8251]
Hi there, I am currently in the process of finishing touching up the cart widget but I can't seem to figure out how to line up/centre the product title and price + quantity with the product image as there's a big white gap in between the two text lines. I've been playing around with CSS but can't seen to figure out the right formula to adjust the cart table. I have included a Photoshoped cart version of what I'm trying to achieve. 

If you are trying to access the website and the cart is empty then please head over to https://www.flaiks.com/colorbuds and add either product from the bottom of the page and proceed back to https://www.flaiks.com/ to view the recently updated CSS cart. 

Thank you for you help, Dan. 

![cart css details](https://user-images.githubusercontent.com/51290520/58842720-6e317800-8667-11e9-9d6e-e16fe5c0ae06.jpg)

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
