### ISSUE TITLE
[Menu] Faster and changeble speed for dropdown submenu and full width mega menu

### ISSUE THREAD

**Issue by EvalcoNL** [elementor/elementor#8253]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
- I like to have a mega menu option that can created with elementor (like https://crocoblock.com/school/articles/jetmenu-how-to-create-a-mega-menu-using-elementor-with-jetmenu-widget/)

- Changeble speed for the dropdown menu. Now when i hover over a menu item it takes to long to show the dropdown.

**Comment by MichaelDarko** [comment]
We need mega menu and much more. Nav menu widget is the weakest part of Elementor when it comes to the most basic building blocks of a website.

#3275

**Comment by envyyycreative** [comment]
We need the Nav Menu to be improved! If the users can't navigate well, it doesn't matter how good our designs are. Please focus on the Nav for the next update E team  <3

**Comment by shilo-ey** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
