### ISSUE TITLE
Archive Template Condition: Category AND Its Children

### ISSUE THREAD

**Issue by mdrideout** [elementor/elementor#8256]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have several categories nested under a parent category that all need to use the same template for their archive page. Currently, I must managed individual "include" conditions for each separate category archive page. If I add more "child" categories, I have to also update the Elementor conditional to support the new child.

**Describe the solution you'd like**
I would like to automatically include all child categories nested under a chosen parent category. 

**Describe alternatives you've considered**
Not aware of an alternative

**Additional Context**
Screenshot demonstrating tediousness of making sure all child archive page categories use the same template.
![screenshot](https://i.ibb.co/thN7Xhw/Screen-Shot-2019-06-04-at-2-04-45-PM.png)

**Comment by Webtica** [comment]
+1

**Comment by javiercriado** [comment]
Great to have this tagged as a request/feature
This was asked to here #5587 but ignored.

We'll be waiting for this new feature!

**Comment by TheCrystalRose** [comment]
+1

**Comment by zeinnicholas** [comment]
+1

**Comment by MainioMooses** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by paradisiacor** [comment]
Will this be available any time soon?

**Comment by notnaus** [comment]
Same problem, i dont want to enter each category manually!
Elementor Version 3.5.1 Pro

**Comment by RollemaMedia** [comment]
Same problem here. Will this be available soon?

**Comment by cessholden** [comment]
Same here - I've 400 product categories which are constantly changing so could really do with managing everything at the top level. Not to mention the processing overheads of a query with 50+ OR statements in it.

**Comment by MySpot1** [comment]
Hey, Defiantly one of the most needed.
Any news about it?

**Comment by MaximMatrosov** [comment]
Hi comrades! Tonight I spent some time and wrote this one. Add this to functions.php and you will have a condition for subcategories of a special product category:
`class Subcategory_Archive extends ElementorPro\Modules\ThemeBuilder\Conditions\Taxonomy {

	private $taxonomy;

	public function get_name() {
		return 'child_of_' . $this->taxonomy->name;
	}

	public function get_label() {
		return sprintf( __( 'Direct Child %s Of', 'elementor-pro' ), $this->taxonomy->labels->singular_name );
	}

	public function __construct( $data ) {
		parent::__construct( $data );

		$this->taxonomy = $data['object'];
	}

	public function is_term() {
		$taxonomy = $this->taxonomy->name;
		$current = get_queried_object();
		return ( $current && isset( $current->taxonomy ) && $taxonomy === $current->taxonomy );
	}

	public function check( $args ) {
		$id = (int) $args['id'];
		$current = get_queried_object();

		return $this->is_term() && $id === $current->parent;
	}
}

	$taxonomy = get_taxonomy('product_cat');
$conditions_manager->get_condition( 'product_archive' )->register_sub_condition( new Subcategory_Archive([ 'object' => $taxonomy ]) );
}, 100 );`

**Comment by javiercriado** [comment]
Hello!

I was facing the same issue again, three years after this one, but now applied to a product category archive #12977 
<img width="986" alt="Captura de Pantalla 2022-05-12 a la(s) 11 25 25" src="https://user-images.githubusercontent.com/11529913/168126691-46984129-c1e6-4efb-90aa-d7b22f66da52.png">

I thought this solution had been applied to a product archive template too but it hasn't.

it's really necessary. Having a list of child categories which will be growing constantly and adding a condition manually for every child category can be avoided

I applied @MaximMatrosov solution and it works fine!

<img width="986" alt="Captura de Pantalla 2022-05-12 a la(s) 11 58 35" src="https://user-images.githubusercontent.com/11529913/168129854-e50d02bc-3402-4a74-aa4b-a080f2685d65.png">

although it's missing the first line in your code which I complemented

`add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) {
` 

It would be nice to have the condition "any child of" not just "direct child of" as being applied with @MaximMatrosov solution.

Thanks to you all!

**Comment by fildenis** [comment]
@MaximMatrosov @javiercriado

Please help! How to create condition for listing of parent categories instead of child categories?

**Comment by ehsanham** [comment]
guys , I need your help . 
I just add below code:
`add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) {
class Subcategory_Archive extends ElementorPro\Modules\ThemeBuilder\Conditions\Taxonomy {
	private $taxonomy;

	public function get_name() {
		return 'child_of_' . $this->taxonomy->name;
	}

	public function get_label() {
		return sprintf( __( 'Direct Child %s Of', 'elementor-pro' ), $this->taxonomy->labels->singular_name );
	}

	public function __construct( $data ) {
		parent::__construct( $data );

		$this->taxonomy = $data['object'];
	}

	public function is_term() {
		$taxonomy = $this->taxonomy->name;
		$current = get_queried_object();
		return ( $current && isset( $current->taxonomy ) && $taxonomy === $current->taxonomy );
	}

	public function check( $args ) {
		$id = (int) $args['id'];
		/**
		 * @var \WP_Term $current
		 */
		$current = get_queried_object();
		if ( ! $this->is_term() || 0 === $current->parent ) {
			return false;
		}

		while ( $current->parent > 0 ) {
			if ( $id === $current->parent ) {
				return true;
			}
			$current = get_term_by( 'id', $current->parent, $current->taxonomy );
		}

		return $id === $current->parent;
	}
}
$taxonomy = get_taxonomy('product_cat');
$conditions_manager->get_condition( 'prdoucts-archive' )->register_sub_condition( new Subcategory_Archive([ 'object' => $taxonomy ]) );
}, 100 );`

But I got this error : 
`Uncaught Error: Call to a member function register_sub_condition() on bool in E:\xampp\htdocs\tpwire\wp-content\themes\hello-theme-child-master\functions.php:77
Stack trace:
#0 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(308): {closure}(Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager))
#1 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 E:\xampp\htdocs\tpwire\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#3 E:\xampp\htdocs\tpwire\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(274): do_action('elementor/theme...', Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager))
#4 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions('')
#5 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 E:\xampp\htdocs\tpwire\wp-includes\plugin.php(517): WP_Hook->d`
What's wrong with it ? 
Thanks.

**Comment by MaximMatrosov** [comment]
> guys , I need your help . I just add below code: `add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) { class Subcategory_Archive extends ElementorPro\Modules\ThemeBuilder\Conditions\Taxonomy { private $taxonomy;
> 
> ```
> public function get_name() {
> 	return 'child_of_' . $this->taxonomy->name;
> }
> 
> public function get_label() {
> 	return sprintf( __( 'Direct Child %s Of', 'elementor-pro' ), $this->taxonomy->labels->singular_name );
> }
> 
> public function __construct( $data ) {
> 	parent::__construct( $data );
> 
> 	$this->taxonomy = $data['object'];
> }
> 
> public function is_term() {
> 	$taxonomy = $this->taxonomy->name;
> 	$current = get_queried_object();
> 	return ( $current && isset( $current->taxonomy ) && $taxonomy === $current->taxonomy );
> }
> 
> public function check( $args ) {
> 	$id = (int) $args['id'];
> 	/**
> 	 * @var \WP_Term $current
> 	 */
> 	$current = get_queried_object();
> 	if ( ! $this->is_term() || 0 === $current->parent ) {
> 		return false;
> 	}
> 
> 	while ( $current->parent > 0 ) {
> 		if ( $id === $current->parent ) {
> 			return true;
> 		}
> 		$current = get_term_by( 'id', $current->parent, $current->taxonomy );
> 	}
> 
> 	return $id === $current->parent;
> }
> ```
> 
> } $taxonomy = get_taxonomy('product_cat'); $conditions_manager->get_condition( 'prdoucts-archive' )->register_sub_condition( new Subcategory_Archive([ 'object' => $taxonomy ]) ); }, 100 );`
> 
> But I got this error : `Uncaught Error: Call to a member function register_sub_condition() on bool in E:\xampp\htdocs\tpwire\wp-content\themes\hello-theme-child-master\functions.php:77 Stack trace: #0 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(308): {closure}(Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager)) #1 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #2 E:\xampp\htdocs\tpwire\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #3 E:\xampp\htdocs\tpwire\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(274): do_action('elementor/theme...', Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager)) #4 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(308): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->register_conditions('') #5 E:\xampp\htdocs\tpwire\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #6 E:\xampp\htdocs\tpwire\wp-includes\plugin.php(517): WP_Hook->d` What's wrong with it ? Thanks.

You have mistake here “>get_condition( 'prdoucts-archive' )->register_sub_condition( new Subcategory”. You write “ prdoucts-archive” instead of “ products-archive”

**Comment by ehsanham** [comment]
@MaximMatrosov Hey thanks for the reply , No the name of the archive file Is  the same as "prdoucts-archive"  but I got the error I mentioned that means its a empty array ,
I have different categories attached to my custom post type and I dont want to create 10 different elementor template files  .
What should I do really ?

**Comment by MaximMatrosov** [comment]
> @MaximMatrosov Hey thanks for the reply , No the name of the archive file Is the same as "prdoucts-archive" but I got the error I mentioned that means its an empty array ,
> I have different categories attached to my custom post type and I don't want to create 10 different elementor template files .
> What should I do really ?

So why are you trying to make it with categories? You need to use condition based on post type rather than based on post category

**Comment by ehsanham** [comment]
@MaximMatrosov I have a archive template page and several categories in my custom post type .
I want to show each category items in this archive page but with conditions it will shows all the products in the categories not only for "dress" categories as an example .
What should I do to manage the archive page only shows the "dress" category if somebody clicks on the dress category and show anything else if selected ?

**Comment by Vorteri** [comment]
Perhaps it will be useful to someone because I did not find a solution so I had to write it myself, but take an example from the upper function. I needed to display products only on the last subcategory, all I could do was display products on all subcategories - it didn't work for me, I needed a hierarchy of categories, and the last category had products. Now I have two templates... One for all categories, and the other for the last category where the corresponding products are displayed

```
class Last_Category_In_Hierarchy extends ElementorPro\Modules\ThemeBuilder\Conditions\Taxonomy {
	private $taxonomy;

	public function get_name() {
		return 'last_category_in_hierarchy_' . $this->taxonomy->name;
	}

	public function get_label() {
		return sprintf( __( 'Last Category In Hierarchy Of %s', 'elementor-pro' ), $this->taxonomy->labels->singular_name );
	}

	public function __construct( $data ) {
		parent::__construct( $data );

		$this->taxonomy = $data['object'];
	}

	public function is_term() {
		$taxonomy = $this->taxonomy->name;
		$current = get_queried_object();
		return ( $current && isset( $current->taxonomy ) && $taxonomy === $current->taxonomy );
	}

	public function check( $args ) {
		/**
		 * @var \WP_Term $current
		 */
		$current = get_queried_object();
		if ( ! $this->is_term() ) {
			return false;
		}

		$children = get_term_children( $current->term_id, $current->taxonomy );

		if ( empty( $children ) ) {
			return true;
		}

		return false;
	}
}

add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) {
	$taxonomy = get_taxonomy('product_cat');
	$conditions_manager->get_condition( 'product_archive' )->register_sub_condition( new Last_Category_In_Hierarchy([ 'object' => $taxonomy ]) );
}, 100 );
```

**Comment by gsqrt2** [comment]
> Perhaps it will be useful to someone because I did not find a solution so I had to write it myself, but take an example from the upper function. I needed to display products only on the last subcategory, all I could do was display products on all subcategories - it didn't work for me, I needed a hierarchy of categories, and the last category had products. Now I have two templates... One for all categories, and the other for the last category where the corresponding products are displayed
> 
> ```
> class Last_Category_In_Hierarchy extends ElementorPro\Modules\ThemeBuilder\Conditions\Taxonomy {
> 	private $taxonomy;
> 
> 	public function get_name() {
> 		return 'last_category_in_hierarchy_' . $this->taxonomy->name;
> 	}
> 
> 	public function get_label() {
> 		return sprintf( __( 'Last Category In Hierarchy Of %s', 'elementor-pro' ), $this->taxonomy->labels->singular_name );
> 	}
> 
> 	public function __construct( $data ) {
> 		parent::__construct( $data );
> 
> 		$this->taxonomy = $data['object'];
> 	}
> 
> 	public function is_term() {
> 		$taxonomy = $this->taxonomy->name;
> 		$current = get_queried_object();
> 		return ( $current && isset( $current->taxonomy ) && $taxonomy === $current->taxonomy );
> 	}
> 
> 	public function check( $args ) {
> 		/**
> 		 * @var \WP_Term $current
> 		 */
> 		$current = get_queried_object();
> 		if ( ! $this->is_term() ) {
> 			return false;
> 		}
> 
> 		$children = get_term_children( $current->term_id, $current->taxonomy );
> 
> 		if ( empty( $children ) ) {
> 			return true;
> 		}
> 
> 		return false;
> 	}
> }
> 
> add_action( 'elementor/theme/register_conditions', function( $conditions_manager ) {
> 	$taxonomy = get_taxonomy('product_cat');
> 	$conditions_manager->get_condition( 'product_archive' )->register_sub_condition( new Last_Category_In_Hierarchy([ 'object' => $taxonomy ]) );
> }, 100 );
> ```

Thank you very much, you're the real MVP!

**Comment by amrikhsn** [comment]
Has anyone created a woocommerce single product condition based on price.  for free products for example.

**Comment by Jamesbinda** [comment]
> This issue has been resolved in Elementor Pro v2.6.0
> 
> Feel free to update
> 
> Thanks!

Not at all resolved.

**Comment by Jamesbinda** [comment]
Why is this closed? This has not been addressed. People coming up with custom code for a pretty basics need is not the solution!

**Comment by DownHouse** [comment]
6 years have passed and they still haven't found the time to write 20 lines of code.  🤣
