### ISSUE TITLE
Mobile Menu Upgrade

### ISSUE THREAD

**Issue by envyyycreative** [elementor/elementor#8257]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro).

**What problem is your feature request going to solve? Please describe.**
I am an Elementor Pro (Expert Plan) user, and I really love everything about it. However, because I am not code savvy enough to modify themes or create my own, I rely very heavily on the Theme Builder. Thus the issue: **I am unsatisfied with the mobile navigation on E's Nav Menu Widget. Mainly because the hamburger icon never matches my design and there is no open/close animation, also because there is no "fullscreen menu" option.**

**Describe the solution you'd like**
Please make it possible to select from different hamburger icons with animations, as well as menu types for mobile-first design.

**Describe alternatives you've considered**
At the very least, please make it possible to select a custom SVG icon for both the hamburger and close icons and the ability to change the transition animations.

**Additional context**
Observe below how a sharp and cleanly animated icon would make a difference as one of the most prominent features of a mobile-first design.
![menu](https://user-images.githubusercontent.com/51323128/58944150-81386b00-8781-11e9-8022-c23c03f639cf.gif)

**Comment by shilo-ey** [comment]
I merged this issue with #3275, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
