### ISSUE TITLE
Getting Elementor data in JS

### ISSUE THREAD

**Issue by DeliciousThemes** [elementor/elementor#8258]
How do you guys access the Elementor elements options in JS? I created a new element which uses the slick slider and need to pass the variables into JS. Any thoughts? 

It seems to be something related to elementSettings or GetElementSettings...is there any doc related to the subject? 

Thanks!

**Comment by DeoThemes** [comment]
You can initialize Slick slider via HTML data attributes:
```
<div data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
```

**Comment by bainternet** [comment]
@DeliciousThemes 	

currently, there is no documentation or API for that, but, You can add `'frontend_available' => true` parameter to the control and then you can access it via `this.getElementSettings( controlName )` if you are running a handler that extends `elementorModules.frontend.handlers.Base`

Or you can access it from `data-settings` attribute of the widget ex:
```JS
var settings = $(elementSelector).data('settings');
console.log(settings[controlName] );
```

thanks

**Comment by DeliciousThemes** [comment]
@bainternet thanks a lot!

PS: I appreciate your work since "my meta box" :)

**Comment by NatalieMac** [comment]
It seems like from the post above that something like this should work to access the settings inside JavaScript:

`elementorFrontend.hooks.addAction( 'frontend/element_ready/my-widget', function( $scope, $ ) {
	console.log($scope.data('settings'));
} );
`
But that's just logging `undefined` for me. Do I need to manually add the `data-settings` attribute in my render function?

**Comment by OffCorner** [comment]
> It seems like from the post above that something like this should work to access the settings inside JavaScript:
> 
> `elementorFrontend.hooks.addAction( 'frontend/element_ready/my-widget', function( $scope, $ ) { console.log($scope.data('settings')); } ); `
> 
> But that's just logging `undefined` for me. Do I need to manually add the `data-settings` attribute in my render function?

Do you check in the frontend or in the backend? I seem to be getting the data-settings attribute, but only in the frontend. Still not quite sure how to get it when the editor is open...

**Comment by NatalieMac** [comment]
@OffCorner You know, I don't remember if I checked after publishing the page - perhaps just while editing. I'm having an awful time figuring out how to enqueue scripts and styles while editing as well. I really really wish there were some developer documentation on this.

**Comment by amorouscreations** [comment]
@OffCorner I am also unable to get settings in the backend using 
```
$scope.data('settings'));
```

Anyone knows how can I get settings when the editor is open?

**Comment by nomad-mystic** [comment]
I have figured out how to get the data you need on the front end using dataset. 

```javascript
class Carousel  {
    constructor() {
        const self = this;

        // For the editor page
        jQuery(document).ready(function () {
            // Sanity Check
            if (window.elementorFrontend && 'undefined' !== window.elementorFrontend) {
                // Make sure our widget is ready
                elementorFrontend.hooks.addAction('frontend/element_ready/carousel.default', function ($scope) {

                    self.buildSwiftCarousel($scope);
                });
            }
        });

        // Front end
        jQuery(window).on('elementor/frontend/init', function () {

            // Sanity Check
            if (window.elementorFrontend && 'undefined' !== window.elementorFrontend) {

                elementorFrontend.hooks.addAction('frontend/element_ready/carousel.default', function($scope) {

                    self.buildSwiftCarousel($scope);
                });

            }
        });
    }

    /**
     * @description Foreach of the carousel elements initiate a Swiper carousel.
     *
     * @param {object} $scope
     * @return void
     */
    buildSwiftCarousel($scope) {
        // Scope carousel creation to the currently created widget
        let selector = `.elementor-element-${$scope[0].dataset.id}`;

        // Make sure our widget is ready
        const swiperContainer = window.document.querySelector(`${selector} .Carousel-swiper-container`);

        // Check for our element
        if (swiperContainer && swiperContainer !== 'undefined') {

            // Setup our carousel
            const carouselSwiper = new Swiper(`${selector} .Carousel-swiper-container`, {

                slidesPerView: swiperContainer.dataset.slidesPerview, // @todo this is where you can get the slides per-view based on the dataset

           
            });
        }
    }
}

new Carousel();
```

Hopefully that helps.
