### ISSUE TITLE
Make Certain Dates Unavailable To Be Chosen

### ISSUE THREAD

**Issue by erizone** [elementor/elementor#8260]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be great to have the ability to make certain dates unavailable for users to select on the datepicker form element.

**Describe the solution you'd like**
Maybe have an underneath the date picker to select certain dates to make them unavailable. When the date is clicked by the dev it will blur out indicating that it is not available.

**Comment by shilo-ey** [comment]
Hi @erizone 

Currently this feature is not availble natively in Elementor, but you can do so by adding few lines of code to your functions.php

read more here: #6372 

Thanks!
