### ISSUE TITLE
🔗 🚀 Feature Request: Use on Mobile (Duplicate of #482)

### ISSUE THREAD

**Issue by serenason** [elementor/elementor#8262]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am trying to design a page from my phone using elementor.
**Describe the solution you'd like**
A clear and concise description of what you want to happen**
The solution is to make elementor mobile usable.

**Describe alternatives you've considered**
None
**Additional context**

**Comment by shilo-ey** [comment]
Duplicate of #482

**Comment by quentintricoire** [comment]
I’ve use the beta too, but is not working very well with the touch screen, yes pwa work but not correctly for serious utilisation ! I’ve test in responsive mode is not possible to make what i want...
