### ISSUE TITLE
Custom content width is not written to custom.frontend.min.css

### ISSUE THREAD

**Issue by yankiara** [elementor/elementor#8263]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When regenerating CSS files from Elementor/tools, custom content width in Elementor Settings page is not written to custom.frontend.min.css in /uploads/elementor/css.

Whenever I edit the file, it is written:
.elementor-section.elementor-section-boxed>.elementor-container{max-width:1140px}

Custom setting is only written in global.css in /uploads/elementor/css.

Therefore, global default setting (1140px) takes precedence over custom setting when custom.frontend.min.css is generated (for instance if you set a custom mobile breakpoint).

## Steps to reproduce

WP 5.2.1 and Elementor 2.5.16

1. With only Elementor plugin activated, create a page with a normal section and any widget, like text widget.
2. Set a 1400px content width and 640px mobile breakpoint in Elementor settings.
3. Regenerate CSS files in Elementor tools.

When I reload and inspect page, I get:
-- custom.frontend.min.css:
.elementor-section.elementor-section-boxed > .elementor-container {
    max-width: 1140px;
}
-- global.css:
.elementor-section.elementor-section-boxed > .elementor-container {
    max-width: 1400px;
}

In /uploads/elementor/css, custom.frontend.min.css still mentions default content width 1140px:
.elementor-section.elementor-section-boxed>.elementor-container{max-width:1140px}

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.15
	PHP Version: 7.2.18
	PHP Max Input Vars: 2000000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.1
	Site URL: http://testelem.yankiara.odns.fr
	Home URL: http://testelem.yankiara.odns.fr
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 4096M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

== Active Plugins ==
	Elementor
		Version: 2.5.16
		Author: Elementor.com

**Comment by sinashamsizadeh** [comment]
I have the same problem. @KingYes @kobizz @iNewLegend

**Comment by sinashamsizadeh** [comment]
I have the same problem. @KingYes @kobizz @iNewLegend @lior-sh
screenshots
Elementor version 2.9.13
WordPress version 5.4.2
https://prnt.sc/td6cso
https://prnt.sc/td6d3g
https://prnt.sc/td6d8p
https://prnt.sc/td6ddr
https://prnt.sc/td6dfx

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
