### ISSUE TITLE
Importing template on activation through WP-CLI Gives permission error

### ISSUE THREAD

**Issue by Sidlegionair** [elementor/elementor#8264]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When I try importing a template through a plugin on activation elementor will not accept importing it because the save function in elementor/core/base/document.php will return false due too is_editable_by_current_user() returning false (which in turn is caused by the property is_editable being false). This will only happen when I activate my plugin with the WP_CLI, when I activate my plugin through the wordpress gui everything will work just fine.

## Steps to reproduce

- Create a plugin
- Add activation hook to plugin:
```
public static function importTemplate( $filepath )
{
    $fileContent = file_get_contents($filepath);
    $fileJson = json_decode($fileContent, true);

    $result = \Elementor\Plugin::instance()->templates_manager->import_template([
            'fileData' => base64_encode($fileContent),
            'fileName' => 'test.json',
        ]
    );

    if (empty($result) || empty($result[0])) {
        return;
    } else {
        return $result;
    }
}
public function activate() {
   $imported_items = YourClassName::importTemplate('your/path/to/template.json');
}
```
- Run activation through wp-cli with command:
wp plugin activate yourpluginname --user=youruserid 

- Check elementor template library and template will be empty.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.34 (Unix) OpenSSL/1.0.2l
	MySQL version: MariaDB Server v5.6.36-83.0
	PHP Version: 7.2.10
	PHP Max Input Vars: 8000
	PHP Max Post Size: 72M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.1
	Site URL: http://test.loc/wp
	Home URL: http://test.loc
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 2G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Hello
	Version: 1.0.0
	Author: Me
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.9
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.0
		Author: Roots

	Disallow Indexing
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots

				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@Sidlegionair 

This is how our import works, in terms of security and permissions validation, you must specify a user with the needed capabilities. when you activate the plugin via the admin panel, you are the current user which has the correct permissions. When you activate via WP-CLI there is no user and its the same for our native WP-CLI import command `wp elementor import_library`. which will also give you the same error unless you specify a user with the correct permissions.

As for your import process, you can try to simplify it using the correct API:

```PHP
public function activate() {
	$file_path = 'your/path/to/template.json';
	/** @var Source_Local $source */
	$source = Plugin::$instance->templates_manager->get_source( 'local' );
	$imported_items = $source->import_template( basename( $file_path ), $file_path );
}
```

thanks.

**Comment by Sidlegionair** [comment]
@bainternet The thing is, I am acting as a certain user by using the --user=1 ( user with id 1 has administrator role) flag on the wp-cli command,  which I confirmed is working by doing get_current_user_id() and printing it to the console despite that it will not work.

This is causing it:

```	/**
	 * @since 2.0.0
	 * @access public
	 */
	public function is_editable_by_current_user() {
		return self::get_property( 'is_editable' ) && User::is_current_user_can_edit( $this->get_main_id() );
	}
```

I var_dumped both in wp_cli and found it is the property is_editable causing this function to return false, because the one checking for user permissions is in fact returning true.

Thanks for looking into this.

**Comment by Sidlegionair** [comment]
@bainternet Found a workaround by importing template first with post type 'page' instead of 'elementor_library' the is_editable attribute will return true. Then after saving I can change it to 'elementor_library' type, though I am still not sure why  'elementor_library' type does not have the property is_editable return true.
