### ISSUE TITLE
Changing section typography does not effect all contained widgets

### ISSUE THREAD

**Issue by theDanielJLewis** [elementor/elementor#8266]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I set the typography of a section, I expect it to affect all the elements (or are they "widgets"? I see them called both things) within that section. For example, if I give a section a black background and change the typography color to white, I expect all elements I place within that section to default to white text. The Heading element does that, but headings inside the Text Editor element do not inherit that color. And it's the same with counters, and maybe some other elements I haven't tried yet.

I _do_ have default colors turned off, and I'm coloring the Heading and Text in the section's Style settings. I'm _not_ overriding the colors within the individual element, but this bug requires me to do so for some elements. 

## Steps to reproduce

1. Disabled default colors from the Elementor settings.
1. Create a section with any layout.
2. Style the section with a dark background color and light heading and body typography colors.
3. Add a Text Editor element, enter heading and paragraph text.
4. Add a counter element.
5. Maybe add other elements to test (I'm only reporting what I've tried thus far in my workflow).
6. Apply all changes and see that the heading and counter text has not inherited the section's typography color.

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.12.1
	MySQL version: Percona Server (GPL), Release 84.2, Revision 6b2b987 v5.6.42-84.2
	PHP Version: 7.2.17-1+ubuntu14.04.1+deb.sury.org+3
	PHP Max Input Vars: 1000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://mypodcastreviews.com
	Home URL: https://mypodcastreviews.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Themify Ultra
	Version: 2.4.2
	Author: Themify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

== Active Plugins ==
	ActiveCampaign
		Version: 7.1.2
		Author: ActiveCampaign

	Akismet Anti-Spam
		Version: 4.1.2
		Author: Automattic

	Builder Button Pro
		Version: 1.2.7
		Author: Themify

	Builder Counter
		Version: 1.1.8
		Author: Themify

	Builder Pricing Table
		Version: 1.1.6
		Author: Themify

	Crayon Syntax Highlighter
		Version: 2.8.4
		Author: Aram Kocharyan

	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.9
		Author: Elementor.com

	Freshchat
		Version: 2.3.0
		Author: Freshchat

	Google Analytics for WordPress by MonsterInsights
		Version: 7.6.0
		Author: MonsterInsights

	Gravity Forms
		Version: 2.4.9
		Author: rocketgenius

	Gravity Forms ActiveCampaign Add-On
		Version: 1.6
		Author: rocketgenius

	Gravity Forms MailChimp Add-On
		Version: 4.6
		Author: rocketgenius

	Gravity Forms Placeholder Add-On
		Version: 1.1.0
		Author: Able Engine, William Wilkerson

	iThemes Security Pro
		Version: 6.0.0
		Author: iThemes

	iThemes Sync
		Version: 2.0.15
		Author: iThemes

	Leadpages Connector
		Version: 2.1.6.21
		Author: Leadpages

	ManageWP - Worker
		Version: 4.8.0
		Author: GoDaddy

	NGA Save Cookie
		Version: 1.0
		Author: Chetan Giri

	Pretty Links
		Version: 2.1.9
		Author: Blair Williams

	Redirection
		Version: 4.3
		Author: John Godley

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	Themify Updater
		Version: 1.1.2
		Author: Themify

	WP Migrate DB Pro
		Version: 1.9.8
		Author: Delicious Brains

	WP Migrate DB Pro Media Files
		Version: 1.4.14
		Author: Delicious Brains

	WP Migrate DB Pro Theme & Plugin Files
		Version: 1.0.5
		Author: Delicious Brains

	Yoast SEO
		Version: 11.3
		Author: Team Yoast


== Must-Use Plugins ==
	Liquid Web Managed WordPress
		Version: 1.4
		Author: Liquid Web <support@liquidweb.com>

	Liquid Web Managed WordPress Platform Manager
		Version: 1.0.0
		Author: Liquid Web

	Liquid Web Update Manager
		Version: 1.0
		Author: Liquid Web <support@liquidweb.com>

	Liquid Web Varnish Cache Purger
		Version: 1.1
		Author: Liquid Web <support@liquidweb.com>

	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

	WP Migrate DB Pro Compatibility
		Version: 1.2
		Author: Delicious Brains


== Log ==
	: 

```
</details>

**Comment by DorShahar** [comment]
Hi 
Sorry for the late reply and thank you for reaching out.
This is the default behavior - since we want to allow more drivers styles of widget-column-section combinations. 

Thanks.
