### ISSUE TITLE
Conflict with NinjaForms

### ISSUE THREAD

**Issue by CPoncet** [elementor/elementor#8267]
Hi,

Please provide a fix regarding this issue : https://github.com/elementor/elementor/issues/7476

You can get more details here : https://wordpress.org/support/topic/bug-in-compatibility-php-conflicting-with-ninja-forms-and-causing-loss-of-data/

The issue has been closed while it's still occuring.

Thank you.

**Comment by happy-harry** [comment]
I'm the one who originally discovered the issue and contacted @kjohnson to help me out.

We found a workaround but it's not ideal.

Commenting out the section of code called "Hack for Ninja forms in Elementor (lines 93-103 in "includes/compatibility.php") seems to resolve the issue,but it needs to be done any time Elementor is updated.

The plugin seems to work fine without this section of code, so it would be great if Elementor could either fix or remove the code so it doesn't cause the freezing. Or am I literally the only one having this issue?

Ninja support opened a ticket with Elementor and I gave them access to the server, then never heard back from either company.

I emailed both companies a few weeks ago to see if they made any progress and they never responded.

I'm working around the issue by disabling the Ninja plugins any time I need to make any edits with Elementor.

**Comment by KimBesser** [comment]
Thanks to happy-harry, I managed to 'solve' temporarily the issue :

In `includes/compatibility.php`

Comment these lines
```
// Hack for Ninja Forms.
		/* if ( class_exists( '\Ninja_Forms' ) && class_exists( '\NF_Display_Render' ) ) {
			add_action( 'elementor/preview/enqueue_styles', function() {
				ob_start();
				\NF_Display_Render::localize( 0 );`

				ob_clean();

				wp_add_inline_script( 'nf-front-end', 'var nfForms = nfForms || [];' );
			} );
		} */
```
Of course you will need to redo this as soon as you apply an Elementor update...

I can now edit with Elementor again without crashing the website.

I do not know if that solves the issue with the loss of submissions data on the Ninja Forms side though.

**Comment by happy-harry** [comment]
> I do not know if that solves the issue with the loss of submissions data on the Ninja Forms side though.

Based on my testing, commenting the code out also fixes the data loss issue. It seems the data loss happens at the same time that Elementor freezes/crashes. If Elementor is no longer freezing, the data loss shouldn't happen.

**Comment by LeodanDesign** [comment]
Not the best way to solve this in the long run, but an option

I think this would be a good place for a filter to be inserted.

```
<?php
$execute_hack = apply_filters('elementor_ninja_forms_hack', true);

// Hack for Ninja Forms.
if ( class_exists( '\Ninja_Forms' ) && class_exists( '\NF_Display_Render' && $execute_hack ) ) {
    add_action( 'elementor/preview/enqueue_styles', function() {
	    ob_start();
		\NF_Display_Render::localize( 0 );
		ob_clean();
		wp_add_inline_script( 'nf-front-end', 'var nfForms = nfForms || [];' );
	} );
}
```

You could then disable the hack by using add_filter in a plugin or functions.php, which would then be "upgrade proof"

```
<?php
add_filter('elementor_ninja_forms_hack', '__return_false');
```

**Comment by KimBesser** [comment]
Might be useful indeed!

**Comment by shilo-ey** [comment]
Thanks, we will take a look and update this thread.

**Comment by yhwhdesign** [comment]
THe issue I have is when I use elementor and add a short code for a ninja forms, it breaks when i update.

What I mean by it breaks is that, when you view the page after updating it and publishing it... where the form is supposed to be, it shows the code all kind of code.

is there any help for that?  I will make a page via elemntor just to show if need be and provide a link... but would rather not have to do that if the description is good enough.

If it matters... this also happens with live composer as well..

**Comment by happy-harry** [comment]
@shilo-ey @kjohnson Any word on a permanent fix for this? It's been 4 months since the issue was [originally reported. ](https://github.com/elementor/elementor/issues/7476)

**Comment by RazielKanos** [comment]
There is more...
With Elementor active, all changes you make within the styles & layout addon for ninjaforms get completely ignored. If i turn elementor off, the form shows as it should, if i turn elementor on, all changes are gone...

**Comment by happy-harry** [comment]
@razielkanos does commenting out the line in compatibility.php fix this issue as well, or is it unrelated?

**Comment by shilo-ey** [comment]
Hi All,

We contacted @kjohnson and informed him about this issue, and recommended creating a new Ninja Forms Elementor widget. 

We will remove this compatibility code in the next versions of Elementor in order to overcome this issue.

Thanks for reporting!

**Comment by happy-harry** [comment]
@shilo-ey I don't believe this was fixed in the next version as you had stated.

There is nothing in the changelog to indicate that this issue has been fixed, and the problematic code still exists in compatibility.php

`		// Hack for Ninja Forms.
		if ( class_exists( '\Ninja_Forms' ) && class_exists( '\NF_Display_Render' ) ) {
			add_action( 'elementor/preview/enqueue_styles', function() {
				ob_start();
				\NF_Display_Render::localize( 0 );

				ob_clean();

				wp_add_inline_script( 'nf-front-end', 'var nfForms = nfForms || [];' );
			} );
		}`

**Comment by CPoncet** [comment]
@happy-harry I can confirm it hasn't been removed on the recent updates.

I had to comment out the lines in `compatibility.php` each time I updated the plugin.

**Comment by happy-harry** [comment]
> @happy-harry I can confirm it hasn't been removed on the recent updates.
> 
> I had to comment out the lines in `compatibility.php` each time I updated the plugin.

Ok thanks. I've re-submitted the issue here: #9249

**Comment by russel575** [comment]
@RazielKanos @yhwhdesign  @LeodanDesign @CPoncet 

Using this plugin I was able to get rid of this issue!
https://wordpress.org/plugins/all-contact-form-integration-for-elementor/
Was able to get submissions in its own DB and that helped me a lot.

Thanks
