### ISSUE TITLE
Image Gallery Widget - Not only title, but also description text

### ISSUE THREAD

**Issue by andreschauer** [elementor/elementor#8271]
Hello, in the Wordpress backend you can setup an ACF image gallery field – and give the images a title, and also a description text. The Elementor Image Gallery Widget unfortunately does not grab the image descriptions, although it might be a very very handy feature?

Thank you,

André

**Comment by shilo-ey** [comment]
Hi @andreschauer 

Thanks for your feedback.

The Image Gallery Widget uses WordPress's native `[gallery]` shortcode, which does not include the option to display the images' descriptions.

Therefore we cannot add this functionality.

Thanks!
