### ISSUE TITLE
content duplicate after footer

### ISSUE THREAD

**Issue by sm7awy** [elementor/elementor#8272]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

the content duplicated after the footer, my theme is ApexumTheme.

**Comment by incubateurdigital** [comment]
Probably because you have a the_content() function in your footer.

**Comment by sm7awy** [comment]
> Probably because you have a the_content() function in your footer.

thank you, and how I can fix it?

**Comment by incubateurdigital** [comment]
remove it... i don't know, i need to see your code...

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
