### ISSUE TITLE
Image widget dynamic tags - add current user

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#8278]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Trying to add an image of the current logged-in user. The dynamic tag has only the current post author.

(`post author !== current logged-in user`)

**Describe the solution you'd like**

New dynamic tag for the image widget, that renders the following code:

`get_avatar( get_current_user_id() )`

**Describe alternatives you've considered**

I use a custom shortcode in all my client sites.

**Additional context**

![Elementor-image-widget-dynamic-tags](https://user-images.githubusercontent.com/576623/59150475-07c4a500-8a2d-11e9-853c-36517b04b065.png)

**Comment by ramiy** [comment]
Copy the existing **Author Profile Picture** tag:

https://gitlab.com/elementor/elementor-pro/blob/master/modules/dynamic-tags/tags/author-profile-picture.php

replace:

`get_the_author_meta( 'ID' )`

with:

`get_current_user_id()`

and maybe change the group to site group.

That's it!

**Comment by ramiy** [comment]
@matipojo @bainternet @joshmarom

**Comment by zeinnicholas** [comment]
+1 This one is simple and would supplement all the other user oriented dynamic data.

**Comment by bentalgad** [comment]
+1 So simple yet not added until now.

**Comment by ramiy** [comment]
![eupp](https://user-images.githubusercontent.com/576623/81931535-f39d0680-95f2-11ea-8148-addde9264513.png)

Checked E Pro 2.8 - it exists!
