### ISSUE TITLE
[Enhancement request] Add a 'close all' or 'root' arrow button on top of the navigator

### ISSUE THREAD

**Issue by OCpublishing** [elementor/elementor#8279]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I often need only to see main sections in the navigator. I have sometime very long pages and huge number of lines open on the navigator, but to get back to the 'root' listing I need to expend everything first before the arrow button pointing up appears so I can get back to 'sections only' base.

Can you please enhance the navigator with an additional 'up arrow button' always available at the top of the navigator?

Thanks for considering my request

**Comment by shilo-ey** [comment]
Hi @OCpublishing 

Do you mean the top left always-available-on-top collapse/expand button?
![image](https://user-images.githubusercontent.com/45009641/59175573-c03e3600-8b5e-11e9-9447-382050d7b0d4.png)
![image](https://user-images.githubusercontent.com/45009641/59175606-dc41d780-8b5e-11e9-8628-8e97053cd1e3.png)

This is already present.

Thanks

**Comment by OCpublishing** [comment]
Hi Shilo-ey

Yep, but to me this is the left-always-on-top **expand-only** button.
Even when I have opened plenty elements on my document like the column example, the top arrow is always Expend. Not collapse.
In order to get the collapse button available we always have to 'Expend All' first, Then and only then we can collapse.
In case of large documents like I use to work with its can be pretty tedious as I use this hundreds of times and this take some second to get done (for large document with plenty elements). That is why I ask for this.

![001](https://user-images.githubusercontent.com/41859489/59184198-e5867080-8b6d-11e9-9a9f-f48d1e98c2eb.JPG)


And BTW It would be nice to have a setting in Elementor to ALWAYS display the navigator when opening a document. Should I create another enhancement request topic for that or here is ok ?

Thank you for considering my request and for your fast answer
Best regards

**Comment by shilo-ey** [comment]
This is exactly how it works.
https://www.loom.com/share/3c6783601c5542168487d25fd76bcf16

As for the other request, please open a new issue.
