### ISSUE TITLE
How can I use event of  \Elementor\Controls_Manager::BUTTON control in render()?

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#8280]
I have added a button control in the settings of my custom widget. I want to trigger an event on the click of a button.
I have implemented Skins for the widget so, I am not able to use the content_template(). I can see the event from the button control can only be accessed in the content_templte().

How can I get the event triggered on the button control in the render() function?

**Comment by joelnewcomer** [comment]
I believe this answers your question: https://github.com/elementor/elementor/issues/9478
