### ISSUE TITLE
View chages override existing but other elemntor tab 

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#8284]
- [yes ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ yes] The issue still exists against the latest stable version of Elementor.

## Description and ## Steps to reproduce

1. Open 2 tabs with elemntor to edit separate posts/page concurrently
2. Modify one and click view changes

Elementor will take over the other tab that is used to edit the other post/page

**Comment by Aviad-Herman** [comment]
Hi,
This issue is fixed in the latest versions of Elementor.
