### ISSUE TITLE
WooCommerce Archive Products Widget - Column Spacing

### ISSUE THREAD

**Issue by ChrisStanyon** [elementor/elementor#8285]
[X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[X] The issue still exists against the latest stable version of Elementor.

## Description
When using the Product Archive widget, the Style->Products->Columns Gap and Style->Products->Rows Gap has no effect. 

In the previous version of EPro, this had the effect of applying a given space between the rows and columns (10px / 30px etc). If I insert one of the pre-built EPro Archive Product blocks, it inserts an older (deprecated) Archive Product block and this works as expected. Manually inserting the Product Archive Widget (new, non-deprecated widget) and the rows / columns gap doesn't work.

I only have Elementor, Elementor Pro and WooCommerce enabled. I've tested this across 6 different themes - Elementor Hello, Astra, WP Ocean, TwentySixteen, TwentyNineteen, and Storefront - all fail with the new widget. All work with the deprecated widget!

I've raised this issue with Elementor directly via Support email and they've acknowledged that it is a bug. The issue was raised over 8 weeks ago and having sent several emails to them asking for an update, I've been told they can't tell me when it will be sorted. There's no mention of it on the GitHub issues tab, hence the reason for now submitting directly. 

## Steps to reproduce
1 // Theme Builder -> Add New -> Select Product Archive -> Create Template

2a // Insert any of the pre-built Product Archive blocks from the Library
This inserts the _deprecated_ Archive Product widget and everything works as expected (change the rows/columns settings).

2b // Cancel the Library, and drag in the Archive Products Widget.
This inserts the newer, _non-deprected_ Archive Product and the Columns / Rows fail to work. Changing the rows/columns settings has no effect.

![ProductArchive - Deprecated](https://user-images.githubusercontent.com/6706076/59196769-7ddd1f00-8b87-11e9-8286-77aa7b3ed920.png)
![ProductArchive - New](https://user-images.githubusercontent.com/6706076/59196770-7ddd1f00-8b87-11e9-973e-2f8e5d682562.png)
      
## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
      Can't test as it needs WooCommerce!
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
<details>
<summary>System Info</summary>
[PasteBin](https://pastebin.com/b0GP13KH)
</details>

**Comment by shilo-ey** [comment]
Hi @ChrisStanyon 
Thanks for reporting.

We will address this issue soon and update this thread.

Cheers

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.5.10

Feel free to update

Thanks!
