### ISSUE TITLE
How can I bind an event listener on `dragstop` event of absolute positioned widget

### ISSUE THREAD

**Issue by dbjpanda** [elementor/elementor#8289]
I wanted to execute a script when we drag and drop an absolute positioned widget. E.g

```
        jQuery( ".my-class" ).on( "dragstop", function( event, ui ) {
               console.log(jQuery('.my-class').attr('data-offset-x'));
        } );
```

Also I found that unlike changing value of a controller, the widget content doesn't get refreshed after position changes of an absolute position element.

**Comment by parasshah195** [comment]
@dbjpanda, you'll have to extend the behavior of the widget view by hooking into the behavior filter, extending the Marionette Behavior class and then add an event hash of `dragstop` linking it to a function which would then contain the script you want to execute.
