### ISSUE TITLE
Make Default Fonts expanded by default

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#8293]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In Default Fonts section, there is lot of free space, so Primary Headline, Secondary Headline, Body Text and Accent Text may be expanded by default for saving useless clicks.

**Describe the solution you'd like**
Make Default Fonts expanded by default.

**Comment by arielk** [comment]
Long time, but I think that version 3.0 will solve this issue, you can read more about it here: https://github.com/elementor/elementor/issues/11821

Thank you for your feedback
