### ISSUE TITLE
Replace icon fonts with SVGs

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#8294]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Icon fonts (Font Awesome) is not considered best practice. The worst is, that Elementor is using them also for example in Nav Menu widget for sub menu icon. Usually for this tiny icon, whole Font Awesome CSS must load.

**Describe the solution you'd like**
Replace Font Awesome at least in Nav Menu and other similar cases with SVG pictures. Also by default, when Font Awesome is not using, won't load their CSS in the HTML. Similar case is with Eicons.

**Describe alternatives you've considered**
Wonderful would be replace whole Font Awesome and Eicons with SVGs.

**Comment by black-eye** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue #5570 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by robtucker168** [comment]
+ for this. The load times this huge font file, for such small icons is ridiculous. The option to use your own icons and completely stop eicons loading seems like a no brainer.
