### ISSUE TITLE
section 'widget - template' update with ajax after submit-form success

### ISSUE THREAD

**Issue by sbc640964** [elementor/elementor#8295]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I am trying to make a form to insert new lines into an ACF post. I would like to see that soon after a successful posting, the table area containing the post rows will be updated, all in the Ajax.

The table area is in a different tamplete

The idea is that you can refresh a specific area (tamplete) on the page after successful submission

I hope I explained well.

**Comment by shilo-ey** [comment]
Hi @sbc640964 

You can only reload your page after a successful page submission, but cannot reload a section.

Thanks

**Comment by sbc640964** [comment]
Is what I asked to be able to load a section
Looks like jquery load ()
