### ISSUE TITLE
Removing Advanced Tab

### ISSUE THREAD

**Issue by kmob2** [elementor/elementor#8297]
Hello,

Is it possible to removed the Advanced Tab from my plugin only? All the setting in the advanced tab have zero functions for my plugin and will only confuse users.

I've come across this thread here https://github.com/elementor/elementor/issues/7648, which suggest the following:
```

<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class Widget_Common extends \Elementor\Widget_Base
{

    public function get_name()
    {
        return 'common';
    }

    public function show_in_panel()
    {
        return false;
    }

    protected function _register_controls()
    {
        return;
    }
}
```
However this removes Advanced Tabs across all plugins and widgets and not just my plugin.

Then I found this thread https://github.com/elementor/elementor/issues/6852 which suggest to use `remove_control()` https://github.com/pojome/elementor/blob/7aa486c4b0c57685ecd95d535801493ac0fc04ca/includes/base/controls-stack.php#L413-L425

I am not really sure how to implement this, nor does the person in that thread seem to be able to get it to work.

I am sure there is a way to remove the Advanced Tab from just my specific widget. Does anyone know? I'd be grateful for any hints or tips into the right direction.

**Comment by shilo-ey** [comment]
@kmob2 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by IanDelMar** [comment]
I came across this old issue when looking for the same feature. The solution, which was available back in 2019 as well, is to paste this in your widget:
```php
public function get_stack( $with_common_controls = true ) {
	return parent::get_stack( false );
}
```
It tells Elementor to not add the controls of the common widget.

See https://github.com/elementor/elementor/blob/74ac97ce22b77032aca471a932788e9208928b73/includes/base/widget-base.php#L171-L184 for the parent method.

**Comment by lDissanayake** [comment]
> I came across this old issue when looking for the same feature. The solution, which was available back in 2019 as well, is to paste this in your widget:
> 
> ```
> public function get_stack( $with_common_controls = true ) {
> 	return parent::get_stack( false );
> }
> ```
> 
> It tells Elementor to not add the controls of the common widget.
> 
> See
> 
> https://github.com/elementor/elementor/blob/74ac97ce22b77032aca471a932788e9208928b73/includes/base/widget-base.php#L171-L184
> 
> for the parent method.

This is Working

**Comment by cowgill** [comment]
This worked for me:

```
public function get_stack( $with_common_controls = true ) {
    $stack = parent::get_stack();

    if ( isset( $stack['tabs']['advanced'] ) ) {
	unset( $stack['tabs']['advanced'] );
    }

    return $stack;
}
```
