### ISSUE TITLE
Copy a popup including settings

### ISSUE THREAD

**Issue by knireis** [elementor/elementor#8298]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need around 20 popups with the same settings (not advanced settings), it seems i cannot copy and paste these settings.

**Describe the solution you'd like**
An easy copy and paste way to duplicate a popup, not only the content, but also the settings.

**Describe alternatives you've considered**
I tried the duplicate post plugin, but the copy is not seen as a popup by elementor. Elementor sees the copy as a normal template.

**Comment by knireis** [comment]
I was informed about a possible solution: export the popup and  import it again. This is working indeed. Still it would be easier to copy/paste.

**Comment by shilo-ey** [comment]
Hi @knireis 

Currently, we do not support the ability to copy the document settings, but this is something we are working on from a broader aspect.

In the meanwhile, you can use the provided solution.

Thanks
