### ISSUE TITLE
Display section horizontally in slides.

### ISSUE THREAD

**Issue by iamitsoni** [elementor/elementor#8305]
Hello there, I need some help. I am thinking of displaying elementor sections horizontally. I want to display elementor sections in slides of a slider so that I can slide these sections. Sections which are not selected to be displayed as slider element will be displayed vertically with their default flow. There will be a slider made of elementor sections with some other sections also being displayed below this slider if needed. Is there any way of doing this without affecting the default functionalities of elementor. Is there any option of doing this through the elementor section editor live customizer or from somewhere else.

**Comment by shilo-ey** [comment]
Hi @iamitsoni 
Thanks for your feedback.

The only options you got is to use the Slides widget, to use an external slider with the sections shortcode, or create your own widget.

Thanks
