### ISSUE TITLE
Feature Request: CSS calc() Function on Section Height

### ISSUE THREAD

**Issue by webbteche** [elementor/elementor#8307]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When designing the first section of the page I want the section to be relative to my header like if I have a header with a height of 100px and I want it to display fit to screen including the first section so would have the variable in my section's height: "height: calc(100% - 100px)"

**Describe the solution you'd like**
On the layout settings there should be this option to have a custom calculation base height

**Comment by shilo-ey** [comment]
Hi @webbteche,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by uzimedia** [comment]
I would like to have this feature also

**Comment by gabrielbarbera** [comment]
Me too. In small pages we can use css calc to make the section min-height to be 100vh - (header hight + footer height). That way the footer can stick to the bottom always.

**Comment by Cristilupchian** [comment]
That would be a great feature to have especially for the fit-to-screen sections.

**Comment by IlPizza79** [comment]
+1, right now I need to add custom css but it would be easier to manage it by elementor section panel.

**Comment by marvtub** [comment]
would be nice!

**Comment by nicholaszein** [comment]
Hello, all!

This is part of a wider request to add keywords and functions (`auto`, `inherit`, `calc()`, `minmax()`, `clamp()`, etc.) to numeric fields, discussed here: 👉 #2219.

Please continue the conversation there.

For now, I'm closing the comments.

Thanks! 🙏

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
