### ISSUE TITLE
Style UI Options for Form Field :focus State

### ISSUE THREAD

**Issue by katart** [elementor/elementor#8310]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like a visual editor to change border styles, background color based on the Form Field state (:focus state specifically). I can do this with CSS, but a UI style editor would be better.

**Describe the solution you'd like**
Add a UI Style Option for Form Field states (similar to the Button "Normal/Hover" option). So you can have a "Normal/Focus" option for Form Fields.

**Comment by steve231293** [comment]
+ 1

**Comment by shilo-ey** [comment]
@katart 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can use custom CSS for that.

Thanks for the feedback.

**Comment by theavic** [comment]
I feel like this isn't an issue to be closed. Even something as simple as an option to apply hover styles also to focus styles would be a decent stop-gap
