### ISSUE TITLE
Lazy load background images

### ISSUE THREAD

**Issue by freelancesam** [elementor/elementor#8313]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Google pagespeed on mobile is awful because because elementor doesn't defer offscreen images. Lazy load would fix this

**Describe the solution you'd like**
Lazy load on all background images 

**Describe alternatives you've considered**
There are 3rd party plugins but user's shouldn't have to add extra plugins for this functionality

**Additional context**

**Comment by gabyferman** [comment]
+1

**Comment by vask** [comment]
+1

Moreover, CSS backgrounds are also used in the Slider widget. jQuery supports lazy loading css backgrounds, so it would be nice to **add an option to lazy load Slides**.

WordPress plugins for lazy loading, usually lazy load only img tags.

**Comment by Elementalel** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @freelancesam 

Elementor uses a CSS file to load the background image and not inline, therefore this is not relevant for this feature.

If you are familiar with a way to utilize lazy load to CSS background images we would be happy to look into it.

Thanks.

**Comment by freelancesam** [comment]
@shilo-ey what about something like this? It's very important that pagespeed is prioritised as performance is the one thing letting elementor down right now

http://jquery.eisbehr.de/lazy/example_load-background-images

**Comment by shilo-ey** [comment]
@freelancesam 

This method doesn't use background images located in the CSS file, but as a custom attribute to the container itself, thus this is not relevant for this case.

thanks!

**Comment by freelancesam** [comment]
@shilo-ey Do you have any plans to increase page load speed and performance? If not, I'll have to abandon elementor as a web developer as it's detrimental to SEO

**Comment by jrevillini** [comment]
check this out https://gist.github.com/jrevillini/e2fe088455e4007e43a23b3364720690

**Comment by jrevillini** [comment]
Today I'm releasing a plugin to handle this:
https://james.revillini.com/projects/lazy-load-elementor-background-images-wordpress-plugin/

**Comment by PrashGupta** [comment]
+1

**Comment by khahina** [comment]
+1
Ticket close but question is always open with insight tools on mobile and new cores indices in GG. 
(james revillini plugins not always working, and not updated since 3 majors releases).
This option might be a major point of elementor optimisation.
Thank you

**Comment by Ki-Tan2934** [comment]
Would be very nice for slideshows to not load all images at once

**Comment by ogio** [comment]
+1 
Needed feature, because new way of speed checking is killing design and sliders on homepage, no usage if you want good marks... this feature will return back faith to sliders ;)

**Comment by zeinzulaziz** [comment]
https://codepen.io/imagekit_io/pen/RBXVrW

you can follow this, it's work!!, but little tricky.

This set for section or column with backgorund image
`section.elementor-section.elementor-top-section.elementor-element.lazy, .elementor-column.elementor-top-column.lazy .elementor-column-wrap.elementor-element-populated{
   background-image: none;
   background-color: #2B3E79;
}

`

And give your Section or Colum with class (.lazy)
