### ISSUE TITLE
Missing Google Font Variants

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8317]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Several Google Font Variants are missing. 
I recently noticed with Open Sans Condensed, that only the weight 300 and 800 works. Nothing inbetween. Anything below 600 will load the 300 weight and above the 600. I need to use 400 and 500 and am shit out of luck. 

Please, either remove the unsupported variants or make sure that fonts are being loaded as intended. 

Console shows no errors. 

## Steps to reproduce

Try to use Open Sans Condensed with a weight of 400 and 500 and see if you can get anything other than the 300 variant to show up.  

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.1
	WP Multisite: Yes
	Max Upload Size: 15 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: websites@webtemple.ca
	Debug Mode: Inactive

== Theme ==
	Name: Webtemple Hello
	Version: 1.0.0
	Author: TD Labs Ltd.
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.0.5
	Parent Theme Author: Elementor Team

== User ==
	Role: 
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	Dynamic Animations for Elementor
		Version: 1.0.0
		Author: Dynamic.ooo

	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.17
		Author: Namogo

	Elementor Pro
		Version: 2.5.9
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.10
		Author: rocketgenius

	Mailgun
		Version: 1.7.1
		Author: Mailgun

	Schema Pro
		Version: 1.3.0
		Author: Brainstorm Force

	SEOPress
		Version: 3.5.7
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.5.7
		Author: Benjamin Denis

	Ultimate Addons for Elementor
		Version: 1.12.0
		Author: Brainstorm Force


== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 6.97
		Author: ServMask

	All-in-One WP Migration Google Drive Extension
		Version: 2.51
		Author: ServMask

	All-in-One WP Migration Multisite Extension
		Version: 3.75
		Author: ServMask

	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Compress JPEG & PNG images
		Version: 3.2.0
		Author: TinyPNG


	Gravity Forms
		Version: 2.4.10
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	User Role Editor Pro
		Version: 4.51
		Author: Vladimir Garagulia

	Wordfence Security
		Version: 7.3.3
		Author: Wordfence

	WP-Cron Control
		Version: 0.7.1
		Author: Thorsten Ott, Erick Hitter, Automattic

	WPMU DEV Dashboard
		Version: 4.7.1.3
		Author: WPMU DEV

	WP Ultimo
		Version: 1.9.12
		Author: Arindo Duque - NextPress
```
</details>

**Comment by shilo-ey** [comment]
Hi @taropaa 

Thanks for your feedback.
The Elementor Google fonts integration works as follows: 
- Font weights are static options for all fonts
- If there's a font with the requested weight - it will retrieve it. Otherwise, it will fall back to another weight.
- As you can see in [Google Fonts](https://fonts.google.com/specimen/Open+Sans+Condensed?selection.family=Open+Sans+Condensed:300) - there are no 400 and 500 weight variants for Open Sans Condensed.
![image](https://user-images.githubusercontent.com/45009641/59408851-946cbb80-8dbd-11e9-9905-6f28c354d879.png)


I understand that your request is to hide/show the weights according to its availability but I can't see this happening due to performance considerations.

Thanks!
