### ISSUE TITLE
In Line Position on Mobile View

### ISSUE THREAD

**Issue by houseshawbash** [elementor/elementor#8319]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I don't know if this is a valid question here or not. But the menu and everything else transforms to a list on mobile view. I thought it was just a menu, however, we're currently developing a blog site of our website. So what we'd wanna do is use the Post widget just below the nav menu. Showing just title of the article and make it scrollable horizontally, so readers on both mobile and desktop view can scroll through it. But turns out, even that transforms to a list on mobile view.

**Describe the solution you'd like**

Can we have an in-line menu instead of menu transforming to a list on mobile view (or whatever your chosen mobile view breakpoint is)
Also, can we have an additional toggle menu, the hamburger icon is just so 2014 when Material design was still a thing. For most people, like me, we purchase Elementor so we can create web pages minus the coding. 

**Describe alternatives you've considered**

I have tried several css code, but none of them made the menu or the post widget to be in line on mobile view nor scrollable. 

**Additional context**

We'd want to make the post widget something similar to this https://www.buzzfeednews.com but scrollable horizontally, and in mobile view too

**Comment by shilo-ey** [comment]
Hi @houseshawbash 

Thanks for your feedback.

In v2.6.0 Pro we are adding the option to disable the dropdown menu in mobile and tablet devices.

I merged this issue with  #7916, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks!
