### ISSUE TITLE
Elementor conflicts with WordPress built-in 'edit_published_posts' capability

### ISSUE THREAD

**Issue by hzesen1221** [elementor/elementor#8320]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

I coded a custom post type named 'Project', and a custom role named 'Project Contributor', which functions pretty much the same as the default Contributor role of WordPress but just for the Project custom post type.

With Elementor disabled, everything works perfectly:

1. the project contributor creates a new project, submit it for review.
2. the admin then publishes the project.
3. the project contributor is now no longer able to edit his published project.

However, with Elementor active, the 3rd stage becomes:
..
..
3. the project is now still able to edit his own published project.

After debugging for the whole night, I found that the problem is caused by this line from 'elementor/core/documents-manager.php':

$allcaps[ $caps[0] ] = $document::get_property( 'is_editable' );

I don't really understand the rationale behind this line, but it seems to me that, this line just adds one of the actual caps (after mapping, which is edit_published_projects) directly to $allcaps, granting the current project contributor this undesirable cap accidentally.

any fixes? thank you!

![Screenshot](https://my.elementor.com/index.php?gf-download=2019%2F06%2Fsceen.jpg&form-id=2&field-id=13&hash=5637ca167f002e04d52d57bd7b45fb56774b71d0ec4baae1f3e003f5df9701c9)

**Comment by shilo-ey** [comment]
Hi @hzesen1221 

Contributor role works as expected, it seems like you misconfigured your role or forgot some capabilities.

I'm closing this issue due to the fact that the support team will take care of this.

Thanks
