### ISSUE TITLE
Generate a Design - Page Build Design Generator - Feature Request

### ISSUE THREAD

**Issue by MaximPro** [elementor/elementor#8321]
### **Generate a Design - Page Build Design Generator - Feature Request**

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Of course we can choose a template and make something new, however it would be much nicer sometimes, if we could just get a premade design with a push of a button (a subfield in the black admin bar, wich could have some more feature btw including:) 

### **"Generate a new design"**

**Describe the solution you'd like**

Wich should work like Artisteer.com - Elementor will get & generate a new Design each time with a press of a button. Just give out a new compilation of premade designblocks with best practices in mind and also get always new images from like unsplash or other free image platforms, new iconsets from like flaticon.com and also change colors by harmony, like from https://coolors.co and alike.
Also Text can be generated by cipsum.com or others (better lorem Ipsum Tools)

**That would be epic!**

**Describe alternatives you've considered**

**Additional context**
check artisteer and you know what I mean.
It would be a unique feature, wich every advanced page builder should have.

This can inspire alot to work from there, also to have creative generated design will support each user and make the design process sometimes much easier!

Please make it your mission to make this happen soon.
Discuss it with your team, because this is a real and good feature, wich would be a market lead.
You would also compete with others, who will be first gets the most attention & Sales ;)

The Race who will be first to implement this Feature is on ;)

Best regards
Maxim

**Comment by shilo-ey** [comment]
Hi @MaximPro 
Thanks for your detailed feature suggestion.

Elementor is focusing on letting the users (Designers, marketers etc...) a simple and intuitive tool for creating beautiful web designs.

Generating random web designs are not our current goal.

That's being said, we do have plans for expanding our templates library for users to have more "Building blocks" for their websites.

If you wish, with a bit of development you can create a pool of predesigned templates and import them to your Elementor builder so you could achieve this feature.

Thanks again for your feedback!
