### ISSUE TITLE
Elementor cannot find post custom fields in templates

### ISSUE THREAD

**Issue by jcalabrese9044** [elementor/elementor#8325]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I am using Elementor Pro (updated fully).  When I try to find a dynamic custom field created by my theme (a post custom field, NOT an ACF field) using a post template, Elementor cannot find the field.  It finds the field perfectly when not using a template.  In fact I can copy the widget from the single post and copy to the template and the field works (but still isn't found).  

Ideally, Elementor would find fields related to the post regardless of it is in a template or not.

## Steps to reproduce

1) Use a theme with a custom field already developed... in this case it was a google maps address field
2)  Create a new post
3)  Use elemntor widget (like text editor) and place it in the post.  
4)  Click dynamic and field the field (it should find it just fine.)
5)  Create an elementor template for a post
6)  Try to do steps 3-4 above... you won't find the field.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active. - I haven't tired this, but it shouldn't matter
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.1.30
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.1
	Site URL: https://thechildrensagenda.org
	Home URL: https://thechildrensagenda.org
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Charitas WPL
	Version: 2.5
	Author: Victor Tihai
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

== Active Plugins ==
	ACF Content Analysis for Yoast SEO
		Version: 2.3.0
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Advanced Custom Fields
		Version: 5.8.1
		Author: Elliot Condon

	amr shortcode any widget
		Version: 3.7
		Author: anmari

	Antispam Bee
		Version: 2.9.1
		Author: pluginkollektiv

	Anywhere Elementor
		Version: 1.1
		Author: WebTechStreet

	AnyWhere Elementor Pro
		Version: 2.12
		Author: WebTechStreet

	Broken Link Checker
		Version: 1.11.8
		Author: ManageWP

	Card Elements for Elementor
		Version: 1.0.1
		Author: Techeshta

	Category Posts Widget
		Version: 4.9.2
		Author: TipTopPress

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Custom Sidebars
		Version: 3.2.3
		Author: WPMU DEV

	Duplicate Menu
		Version: 0.2.1
		Author: Jonathan Christopher

	Dynamic Visibility for Elementor
		Version: 2.0.4
		Author: Dynamic.ooo

	Easy WP SMTP
		Version: 1.3.9.1
		Author: wpecommerce, alexanderfoxc

	Ele Custom Skin
		Version: 1.0.9
		Author: Liviu Duda

	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.5.3
		Author: WebTechStreet

	Elementor Addons & Templates - Sizzify Lite
		Version: 1.3.2
		Author: ThemeIsle

	Elementor Google Map Extended
		Version: 1.1.5
		Author: InternetCSS

	Elementor Pro
		Version: 2.5.9
		Author: Elementor.com

	Elements Plus!
		Version: 2.5.1
		Author: The CSSIgniter Team

	Essential Addons for Elementor
		Version: 3.0.5
		Author: WPDeveloper

	FileBird Lite
		Version: 2.1
		Author: Ninja Team

	Flexible Elementor Panel
		Version: 1.9.2
		Author: Flexible-Elementor-Panel.com

	Flexible Posts Widget
		Version: 3.5.0
		Author: DPE WS&D LLC

	Google Analytics for WordPress by MonsterInsights
		Version: 7.6.0
		Author: MonsterInsights

	Health Check & Troubleshooting
		Version: 1.3.2
		Author: The WordPress.org community

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.1.0
		Author: HT Plugins

	Increase Maximum Upload File Size
		Version: 1.3
		Author: WebFactory Ltd

	JetWidgets For Elementor
		Version: 1.0.2
		Author: CrocoBlock

	jQuery Updater
		Version: 3.4.1
		Author: Ramoonus

	Livemesh Addons for Elementor
		Version: 2.6.2
		Author: Livemesh

	Menu Image
		Version: 2.9.1
		Author: Alex Davyskiba aka Zviryatko

	Optimize Database after Deleting Revisions
		Version: 4.8.0
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Password Protected Categories
		Version: 1.3.3
		Author: Barn2 Media

	Plugin Groups
		Version: 1.2.1
		Author: David Cramer <david@digilab.co.za>

	Post Expirator
		Version: 2.3.1.1
		Author: Aaron Axelsen

	PowerPack Lite for Elementor
		Version: 1.2.2
		Author: IdeaBox Creations

	Premium Addons for Elementor
		Version: 3.4.4
		Author: Leap13

	Press Elements - Widgets for Elementor
		Version: 1.7.2
		Author: Press Elements

	Real-time Visitor Statistics
		Version: 1.9
		Author: osamaesh

	Redirection
		Version: 4.3.1
		Author: John Godley

	SG Optimizer
		Version: 5.1.3
		Author: SiteGround

	Shortcodes Ultimate
		Version: 5.3.0
		Author: Vladimir Anokhin

	Simple Custom CSS and JS
		Version: 3.26
		Author: SilkyPress.com

	Sina Extension for Elementor
		Version: 2.1.2
		Author: shaonsina

	Smart Recent Posts Widget
		Version: 0.0.6
		Author: Idenovasi

	Smart Slider 3
		Version: 3.3.20
		Author: Nextend

	Tabs - Responsive Tabs with  Accordions
		Version: 2.8
		Author: Biplob Adhikari

	The Plus Addons for Elementor Page Builder Lite
		Version: 1.1.0
		Author: POSIMYTH Themes

	Toolbar Extras
		Version: 1.4.3
		Author: David Decker - DECKERWEB

	To Top
		Version: 1.8.1
		Author: Catch Plugins

	UpdraftPlus - Backup/Restore
		Version: 1.16.15
		Author: UpdraftPlus.Com, DavidAnderson

	Wicked Folders
		Version: 2.13.1
		Author: Wicked Plugins

	Widget Importer & Exporter
		Version: 1.5.5
		Author: ChurchThemes.com

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.5.2.3
		Author: WPForms

	WP Maximum Execution Time Exceeded
		Version: 1.0.2
		Author: Johnnie J. O'Dell Jr.

	WP Post Page Clone
		Version: 1.0
		Author: Gaurang Sondagar

	WP Scheduled Posts
		Version: 2.3.0
		Author: WPDeveloper

	Yoast SEO Premium
		Version: 11.4
		Author: Team Yoast

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.6.0
		Author: 

== Log ==
	: 
Log: showing 8 of 82019-04-12 12:46:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.5.13',
)]
2019-04-16 14:26:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]
2019-04-29 17:22:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.5.6',
)]
2019-05-06 13:06:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.6',
  'to' => '2.5.7',
)]
2019-05-07 01:19:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.7',
  'to' => '2.5.8',
)]
2019-05-07 17:58:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.14',
  'to' => '2.5.15',
)]
2019-05-28 13:47:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.15',
  'to' => '2.5.16',
)]
2019-05-28 14:11:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]

JS: showing 19 of 19JS: 2019-04-12 16:25:09 [error X 66][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.13:2:53509] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-04-12 17:15:39 [error X 1][http://new.thechildrensagenda.org/wp-admin/post.php?post=407&action=elementor:14:11] yes is not defined 
JS: 2019-04-12 17:15:43 [error X 5][http://new.thechildrensagenda.org/wp-admin/post.php?post=407&action=elementor:14:11] Unexpected token , 
JS: 2019-04-15 15:44:24 [error X 28][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.13:2:8507] Cannot read property \'select2\' of undefined 
JS: 2019-04-16 15:30:38 [error X 2][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:154150] elementor.getPanelView(...).getCurrentPageView(...).activateTab is not a function 
JS: 2019-04-16 20:07:17 [error X 3][http://new.thechildrensagenda.org/wp-content/plugins/addons-for-elementor/assets/js/jquery.stats.min.js?ver=2.6.2:1:10541] Couldn\'t cast `[object Object]` to a date object. 
JS: 2019-04-17 14:19:54 [error X 1][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:60824] Cannot read property \'query\' of null 
JS: 2019-04-17 14:48:48 [error X 1][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:139321] e.ui.sync.removeClass is not a function 
JS: 2019-04-17 19:14:09 [error X 2][http://new.thechildrensagenda.org/wp-content/plugins/premium-addons-for-elementor/assets/js/premium-addons.js?ver=3.2.7:337:33] PremiumProSettings is not defined 
JS: 2019-04-17 19:14:38 [error X 2][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:10531] n.attributes[t.name].each is not a function 
JS: 2019-04-17 20:07:21 [error X 106][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:212877] Cannot read property \'html\' of undefined 
JS: 2019-04-22 12:36:34 [error X 1676][http://new.thechildrensagenda.org/wp-content/themes/charitas-wpl/js/base.js?ver=5.1.1:182:75] Cannot read property \'top\' of undefined 
JS: 2019-04-23 20:06:12 [error X 12][http://new.thechildrensagenda.org/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/dce-editor.js?ver=2.0.4:44:9] elementorFrontend is not defined 
JS: 2019-04-30 15:55:35 [error X 1][http://new.thechildrensagenda.org/wp-includes/js/media-editor.min.js?ver=5.1.1:1:10792] wp.media.view.EditorUploader is not a constructor 
JS: 2019-05-03 16:19:10 [error X 2][http://new.thechildrensagenda.org/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/dce-editor.js?ver=2.0.4:117:64] Cannot read property \'attributes\' of undefined 
JS: 2019-05-14 17:34:43 [error X 5][http://new.thechildrensagenda.org/wp-admin/post.php?post=3750&action=elementor:182:3] Unable to get property \'top\' of undefined or null reference 
JS: 2019-05-30 18:38:46 [error X 1][http://new.thechildrensagenda.org/wp-content/uploads/siteground-optimizer-assets/base.min.js?ver=5.2.1:3:241] jQuery(...).offset(...) is undefined 
JS: 2019-05-31 19:57:34 [error X 4][http://new.thechildrensagenda.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:204753] Cannot read property \'getChildViewContainer\' of undefined 
JS: 2019-06-10 16:54:40 [error X 2][https://thechildrensagenda.org/wp-content/plugins/addon-elements-for-elementor-page-builder/assets/js/eae.min.js?ver=1.0:1:1525] Cannot read property \'lat\' of undefined 

PHP: showing 6 of 6PHP: 2019-04-15 15:49:25 [notice X 3][/home/new99140/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-16 15:17:26 [notice X 1][/home/new99140/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::714] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-17 15:07:12 [notice X 1][/home/new99140/public_html/wp-content/plugins/elementor/includes/managers/image.php::33] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-19 20:13:56 [notice X 1][/home/new99140/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::122] Trying to get property of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-05-28 14:11:57 [warning X 1][/home/new99140/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::714] Illegal string offset 'type' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-05-29 15:47:48 [notice X 8][/home/new99140/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-custom-field.php::62] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by jcalabrese9044** [comment]
Anyone?

**Comment by shilo-ey** [comment]
Hi @jcalabrese9044 

When editing your post template you need to set the "Preview dynamic content as" option to your desired post. 

![image](https://user-images.githubusercontent.com/45009641/59832196-0019d000-934c-11e9-87b4-d71a9b130882.png)

Thanks

**Comment by jcalabrese9044** [comment]
That did not work.  Still not showing fields in question.

**Comment by jcalabrese9044** [comment]
thank you... after saving and refreshing, it found the fields.
