### ISSUE TITLE
Developer example to add dynamic css from within widget class

### ISSUE THREAD

**Issue by dbjpanda** [elementor/elementor#8328]
I am developing a widget and I want to add some custom dynamic css for each skin. But I am not able to do that. Need an example for the same. I am not asking about `selectors`.
I tried something like below but unable to find a proper way. It adds those css inline and multiple times. I also wanted to add css as per conditional value from control section. 

```
use Elementor\Controls_Manager;
use Elementor\Skin_Base as Elementor_Skin_Base;
use Elementor\Widget_Base;
use Elementor\Scheme_Color;
use Elementor\Group_Control_Text_Shadow;
use Elementor\Group_Control_Typography;
use Elementor\Scheme_Typography;
use Elementor\Group_Control_Border;

use Elementor\Core\DynamicTags\Dynamic_CSS;
use Elementor\Core\Files\CSS\Post;
use Elementor\Element_Base;



if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

abstract class Skin_Base extends Elementor_Skin_Base {


    public function __construct(Widget_Base $parent)
    {
        parent::__construct($parent);
        $this->add_actions();
    }

    protected function add_actions() {
        add_action( 'elementor/element/parse_css', [ $this, 'add_post_css' ], 10, 2 );
    }

    /**
     * @param $post_css Post
     * @param $element  Element_Base
     */
    public function add_post_css( $post_css, $element ){
        
        $css = '.ke-toc-headings-nav ul{counter-reset:item}.ke-toc-headings-nav li{display:block}.ke-toc-headings-nav li:before{content:counters(item, ".") " ";counter-increment:item}';
        $post_css->get_stylesheet()->add_raw_css( $css );

    }


    }
```

**Comment by TheFirsh** [comment]
I also want to know!

**Comment by udidol** [comment]
Hi @dbjpanda and @TheFirsh,
There is no built-in way to do what you are looking to do in the PHP side.
BUT
If this is a custom widget you are building, you can add a JS handler to the widget, receive the control values in that handler, and then according to the control values, use JS to inject your custom CSS to the `<head>` tag.

See https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/
