### ISSUE TITLE
Widget to select and display single posts image and meta

### ISSUE THREAD

**Issue by Syncopated1** [elementor/elementor#8329]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Syncopated1** [comment]
I have been using Single Post Sidebar Widget for a long time and it works great (https://wordpress.org/plugins/single-post-sidebar-widget/) My site is very dependent on it at this point.
Unfortunately it hasn't been updated in a long time and is likely abandoned.  Elemenotor should have something with similar functionality as a default widget. It seems simple enough. I'm using Elementor Pro and about to adapt my site to Hello Theme, I'd like to use as few plugins as possible after I do. I can replecate what I do now by combining a headline widget with an image widget and playing with styling but I'd prefer something all in one like I'm used to.

**Comment by shilo-ey** [comment]
Hi @Syncopated1 

You can sure do so in Elementor Pro.

Use our Theme Builder in combination with Dynamic tags to achieve this goal.

You can try looking for specific instructions in our knowladge bases:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by Syncopated1** [comment]
Yes I do use Elementor pro. I've exhaustedly tried things with the widgets
available. Spending 5 minutes on each one isn't viable for me. I need to
use two widgets to replicate what I'm doing now. By using the default posts
widget you can almost do what I would like, the three things that would
need to be added to that widget to replicate Single Post Widget would be
selecting the size of the picture from all the available size options, the
ability to put the headline above the image, and a way to quickly select
the post you want to display through an in widget search.

Look at the widget I'm suggesting, I think it features offer some great
options for you to have as default:
https://th.wordpress.org/plugins/single-post-sidebar-widget/#description

If you added that functionality to the existing post widgets, which is
meant for displaying a block of posts, or made a separate widget for
displaying one post it would be very helpful.  Right now I would need to
use both a headline widget and image widget to replicate what I quickly do
on pages like this one using this now abandoned plugin:
https://syncopatedtimes.com/june-2019/

Joe Bebco
Associate Editor
SyncopatedTimes.com (315) 507-5490
A monthly newspaper covering Hot Jazz, Ragtime, and Swing.
