### ISSUE TITLE
Share buttons widget produce wrong sharing title and description for woocommerce products

### ISSUE THREAD

**Issue by artjomzab** [elementor/elementor#8332]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

![Screenshot 2019-06-14 10 26 36](https://user-images.githubusercontent.com/524580/59495162-03feab80-8e8f-11e9-8225-0e1acd60e53f.png)

As you can see from the image, I placed a share widget onto the product theme. When I share view whatsapp, I get following text:

![Screenshot 2019-06-14 10 29 27](https://user-images.githubusercontent.com/524580/59495290-55a73600-8e8f-11e9-87e8-cb2ae1f13ca2.png)

It shows the correct link, but wrong text and description (of another product). The same problem exists with sharing via mail.

## Steps to reproduce

- place the sharing widget onto the product theme
- try to share via whatsapp or mail
- see how title and description show always the same product

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.7.25 |  
PHP Version: | 7.0.33-0+deb9u3 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected



WordPress Environment |   |  
-- | -- | --
Version: | 5.2.1 |  
WP Multisite: | No |  
Max Upload Size: | 100 MB |  
Memory limit: | 256M |  
Permalink Structure: | /%postname%/ |  
Language: | de-DE |  
Timezone: | Europe/Berlin |  
Debug Mode: | Inactive


Theme |   |  
-- | -- | --
Name: | Astra |  
Version: | 1.8.5 |  
Author: | Brainstorm Force |  
Child Theme: | No


Active Plugins |   |  
-- | -- | --
Advanced Custom Fields - 5.8.1 | By Elliot Condon |  
Classic Editor - 1.5 | By WordPress Contributors |  
Code Snippets - 2.13.3 | By Shea Bunge |  
Cookie Notice - 1.2.46 | By dFactory |  
Disable Comments - 1.9.0 | By Samir Shah |  
Disable Emojis (GDPR friendly) - 1.7.2 | By Ryan Hellyer |  
Elementor - 2.5.16 | By Elementor.com |  
Elementor Pro - 2.5.9 | By Elementor.com |  
Hide Admin Toolbar - 1.0 | By Aftab Muni |  
Merge + Minify + Refresh - 1.8.12 | By Launch Interactive |  
Smush - 3.2.1 | By WPMU DEV |  
The SEO Framework - 3.2.4 | By Sybre Waaijer |  
Ultimate Addons for Elementor - 1.12.0 | By Brainstorm Force |  
User Role Editor - 4.51 | By Vladimir Garagulya |  
WooCommerce - 3.6.4 | By Automattic |  
WOOF - WooCommerce Products Filter - 1.2.2.1 | By realmag777 |  
WordPress Importer - 0.6.4 | By wordpressdotorg |  
WP-Stateless - 2.2.7 | By Usability Dynamics, Inc. |  
WP Mail SMTP - 1.4.2 | By WPForms |  
WP Server Stats - 1.6.7 | By Saumya Majumder |  
WP Super Cache - 1.6.7 | By Automattic


<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @artjomzab 

Our share widget uses the page's excerpt as a description. which is by default stripped out of tags, in cases like WC you need to strip it manually, ex:

```PHP
add_filter('woocommerce_short_description', function( $the_excerpt ) {
    return wp_strip_all_tags($the_excerpt);
} ,10, 1);
```

Thanks.

**Comment by artjomzab** [comment]
@shilo-ey thanks! However the filter has no effect. Besides that as you can see from the images, the description is static and does not reflect the shared product.
