### ISSUE TITLE
checkbox alignment in forms widget

### ISSUE THREAD

**Issue by boverman** [elementor/elementor#8335]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [
checkbox fields do no align under title and to not space properly
--]

**Describe the solution you'd like**
Under field checkbox title check boxes should align flush left with equal space under title and check boxes

**Describe alternatives you've considered**
email tech support:
How do you align a checkbox field
How do you bold the title of the field
![check-box-1](https://user-images.githubusercontent.com/51838422/59541122-d9274e00-8eb4-11e9-8105-8d7b64ffbd34.jpg)
![check-box](https://user-images.githubusercontent.com/51838422/59541123-d9274e00-8eb4-11e9-86a3-43f5f46f9c3e.jpg)
Why is the content of the checkbox field not under title of field (seems to center in space)
--

**Additional context**

**Comment by boverman** [comment]
please correspond to this request at my registered email address: jeff@boverman.com

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* **Description and examples.**

We can't understand what you are asking for...

Thanks.
