### ISSUE TITLE
After Recent Elementor Update, Mailchimp Lists not loading.

### ISSUE THREAD

**Issue by stephengzarate** [elementor/elementor#8336]
After the most recent update, my Elementor Form widget won't load my MailChimp lists. I apologize if this issue has already been addressed in a different thread.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
