### ISSUE TITLE
star rating is not working

### ISSUE THREAD

**Issue by hapkemedia** [elementor/elementor#8337]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by hapkemedia** [comment]
Elementor Newscomer: I set star rating like you present in the support video. Rating scale 0-5, rating 0 or others tried out. Diffenret colours for marked and not marked. Users cannot rate.

**Comment by shilo-ey** [comment]
The rating widget is not for users to rate, but to display the rating of the product/article etc.

Thanks
