### ISSUE TITLE
Image box html inside description

### ISSUE THREAD

**Issue by MrAndreius** [elementor/elementor#8338]
When you insert html in the description, then on the page this code displays outside the tag **p** 
besides, the tag **p**  displays twice
Can make it so that the content in the description is not wrapped **p**  automatically?
![Знімок екрана (1783)](https://user-images.githubusercontent.com/1025948/59552850-a2c10000-8f94-11e9-8bf8-45f228fc841b.png)

**Comment by shilo-ey** [comment]
Hi @MrAndreius 

This is created due to the fact that you cannot place a `<p>` tag inside another `<p>` tag.

Remove it and it will be fixed.


Thanks

**Comment by MrAndreius** [comment]
Again
tag is added automatically
if in the field add html div or ul
And on the frontend it is not displayed correctly in the end.

I’m talking about leaving the possibility of entering html into the field, but so that the code would be processed correctly

![1806](https://user-images.githubusercontent.com/1025948/59982659-748b9200-961e-11e9-8930-5835aeb78961.png)

**Comment by MrAndreius** [comment]
@shilo-ey   You did not solve the problem, did not even understand it, but just waved away
