### ISSUE TITLE
How to create pre-designed sample for a widget in Elementor

### ISSUE THREAD

**Issue by hosseinhashemi** [elementor/elementor#8339]
Hi There

I would like to create some pre-designed styles to a simple widget like heading. For example, consider a heading widget, I want to have 3 pre-designed demo and when user click on every style, it changes the heading styles. Please note the styles/changes is available in the widget settings and I don't need to use Elementor Skins. Actually, I need exactly something like Elementor Default colors schema but for widgets. Please check my screenshot:
http://prntscr.com/o2hhht

Is it possible in Elementor?

**Comment by shilo-ey** [comment]
Hi @hosseinhashemi 

For now, you can use a global widget or create a saved template.
I merged this issue with #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
