### ISSUE TITLE
Elementor Cart Widget (Custom Icon)

### ISSUE THREAD

**Issue by ManageFlaiks** [elementor/elementor#8342]
Hi, I'm looking for a way to place my own custom icon in the Elementor Cart Widget instead of the default ones available but I can't seem to figure it out through CSS. What's the right way of doing it? Many thanks

**Comment by shilo-ey** [comment]
I merged this issue with  #110, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
