### ISSUE TITLE
Enable Add New Template popup in new tab

### ISSUE THREAD

**Issue by RichardUUU** [elementor/elementor#8344]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In Chrome, right-click on Dashboard / Templates / Add New and choose Open in a new tab. Everything works properly. 

However, in Saved Templates right-click on the Add New button near the top and choose Open in a new tab, and you will bypass the popup that allows you to specify the template Type. Instead, it creates a template with Type = Page. Furthermore, I see no way to change the Type of a Template once it's been created.

**Describe the solution you'd like**
Either: 
1. enable the New Template popup when opened in a new tab from the Add New button at the top of Saved Templates; 
or,
2. a quick way to change the Template Type

**Describe alternatives you've considered**
Duplicate my Template tab and then click Add New.

**Additional context**
n/a

**Comment by shilo-ey** [comment]
Hi @RichardUUU 

Thanks for your feedback

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

**Comment by RichardUUU** [comment]
I'm not up to that task, but maybe someone else will see this. Thanks.
