### ISSUE TITLE
Implement 'required' arg in control field ? 

### ISSUE THREAD

**Issue by dbjpanda** [elementor/elementor#8348]
I wanted to make a Icon field value as required as below but it doesn't work. 

```
$this->add_control(
            'active_toggle_button_class',
            [
                'label'       => __( 'Active Button', 'toc-headings' ),
                'type'        => Controls_Manager::ICON,
                'required' => true,
                'default'     => 'ke-show-button',
                'label_block' => true,
                'condition' => [
                    'is_toggle_button' => 'yes'
                ]
            ]
        );
```

Do we have an option like that for all the controls. If not can it be implemented as a common arg available to all controls like type, label etc. If available then please update the [documentation](https://developers.elementor.com/elementor-controls/icon-control/).

**Comment by shilo-ey** [comment]
Hi @dbjpanda 

There's no option for adding required field and it may create bad UX when forcing the users to fill in some fields.

We usually use the `default` option to insert the first value, so the widget won't be "blank".

Thanks for your suggestion!

**Comment by dbjpanda** [comment]
Sorry, @shilo-ey I don't agree with you. Take an example, a text field may be compulsory in a plugin to process further data. Both php and js depends upon that data. I know you  can set something default text. But what happen if the user deletes the default and make it blank !!! Yes, you can write some extra code to check if the value is empty then don't proceed. Again same thing in js. So why not prevent it from the beginning ?? But if we can add a field like 'label_block' => true/false in base control field args then some extra code to check ' if value is empty'  can be redundant.
