### ISSUE TITLE
Move fontawesome inline CSS out of body tag for W3C validation.

### ISSUE THREAD

**Issue by MrWuBo** [elementor/elementor#8350]
Hi

![image](https://user-images.githubusercontent.com/33325823/59664155-135d5c00-91e3-11e9-9e22-1aac1690662c.png)

See the picture, it's the source codes of my page, and this part is generated by Elementor. I want to move the font awesome inline CSS out of the body tag, for example, put into the head tag. Because W3C Validation always shows "Error: Element style not allowed as child of element body in this context. (Suppressing further errors from this subtree.)".

Thanks

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.
This is what we are seeing:
![image](https://user-images.githubusercontent.com/45009641/59673463-0c761f80-91ca-11e9-9e1d-34d1060fd5d0.png)


Thanks.
