### ISSUE TITLE
Fluid fonts with rem font style unit!

### ISSUE THREAD

**Issue by acornavi** [elementor/elementor#8351]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by acornavi** [comment]
Overall Elementor have good options to do responsive layouts, but more and more due to more complicated designs problem with the font size with responsive templates makes fonts to small or too big on some desktops.

I was looking for a solution and I found this code that works like charm 

:root {
  font-size: calc(1vw + 1vh + .5vmin)!important;
}

body {
  font: 1rem/1.6 "Open Sans", sans-serif !important;
}

Essentially, if you use rem font size unit font will become fluid and will nicely adapt to most desktop situations.

It would be great to have one global option where you can turn on this option (fluid fonts) and have some customization options for specific situations. This way responsiveness will be greater which will contribute to readability and beauty of the web sites.

Kind regards,
Ivan Roca

**Comment by shilo-ey** [comment]
Hi @acornavi 

Thanks for your suggestion.

I merged this issue with  #3345, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks
