### ISSUE TITLE
Translate Press plugin issue with Elementor

### ISSUE THREAD

**Issue by mcparrish** [elementor/elementor#8357]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by mcparrish** [comment]
Having a problem with Elementor and Translate Press plugin, where it says there is an issue of too few arguments in the post.php file at line 119.  The steps to reproduce it are below:

The navigation, in Japanese:
<img width="1508" alt="Screen Shot 2019-06-18 at 6 47 03 PM" src="https://user-images.githubusercontent.com/1039589/59731073-a7d2b900-91f9-11e9-9a17-78eb8256d17e.png">

The error thrown by the server:
<img width="1202" alt="Screen Shot 2019-06-18 at 6 47 11 PM" src="https://user-images.githubusercontent.com/1039589/59731075-ac976d00-91f9-11e9-99f0-81b0292acbb9.png">

<img width="1203" alt="Screen Shot 2019-06-18 at 6 15 29 PM" src="https://user-images.githubusercontent.com/1039589/59731140-df416580-91f9-11e9-8561-e3859d3378b1.png">

And the line 119 in the post.php file.
<img width="986" alt="Screen Shot 2019-06-18 at 6 15 18 PM" src="https://user-images.githubusercontent.com/1039589/59731156-ec5e5480-91f9-11e9-94f8-2a6a64f1cfb3.png">

The issue does not happen all the time, but rather randomly.

**Comment by shilo-ey** [comment]
Hi @mcparrish 
Thanks for reaching out.

This is not an issue we can reproduce due to the fact that it occurs randomly and not followed by specific steps. 

I can see differences in your `post.php` file, try updating your Elementor plugin to the latest version.

If you're a Pro user you can contact our support for better troubleshooting this issue.

Thanks
