### ISSUE TITLE
[Elementor pro] More than 1 checkbox cause problem

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#8359]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I add more than 1 checkbox in form widget, type sets as "checkbox checkbox" and that cause problem, the field not set as checkbox actually!
how can I solve it?
![image](https://user-images.githubusercontent.com/2544046/59758005-9f2fc080-9295-11e9-90ab-7644ec7c2687.png)

![image](https://user-images.githubusercontent.com/2544046/59757773-2892c300-9295-11e9-9bbf-3eb14b6e790f.png)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.26
	PHP Version: 7.1.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://testhosting.co.uk/box
	Home URL: http://testhosting.co.uk/box
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.10
		Author: Elliot Condon

	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Duplicate Page
		Version: 3.5
		Author: mndpsingh287

	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Elementor Google Map Extended
		Version: 1.1.5
		Author: InternetCSS

	Elementor Inline SVG
		Version: 1.2.0
		Author: Namogo

	Elementor Pro
		Version: 2.5.9
		Author: Elementor.com

	HTTP Headers
		Version: 1.13.3
		Author: Dimitar Ivanov

	Max Mega Menu
		Version: 2.7.1.1
		Author: megamenu.com

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	WidgetKit for Elementor
		Version: 1.2.2
		Author: Themesgrove

	WP Mail SMTP
		Version: 1.4.2
		Author: WPForms

	Yoast SEO
		Version: 11.4
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Log ==
	: 
JS: showing 8 of 8JS: 2019-02-13 11:59:53 [error X 2][http://testhosting.co.uk/box/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.4.6:671:36] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <> as `slider_animation_image` value. Expected array or object.',
)]
JS: 2019-02-15 10:45:36 [error X 5][http://testhosting.co.uk/box/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.6:2:206587] Cannot read property \'html\' of undefined 
JS: 2019-02-15 11:07:27 [error X 2][http://testhosting.co.uk/box/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.4:2:16531] Cannot read property \'children\' of undefined 
JS: 2019-02-18 12:01:24 [error X 2][http://testhosting.co.uk/box/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.6:2:6883] Cannot read property \'select2\' of undefined 
JS: 2019-05-24 13:13:45 [error X 1][http://testhosting.co.uk/box/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.6:2:146494] this.jqueryXhr.abort is not a function 
JS: 2019-05-28 21:24:47 [error X 1][http://testhosting.co.uk/box/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view460\") has already been destroyed and cannot be used. 
JS: 2019-05-28 21:25:25 [error X 1][http://testhosting.co.uk/box/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2393\") has already been destroyed and cannot be used. 
JS: 2019-06-19 10:11:31 [error X 3][http://testhosting.co.uk/box/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.4:2:15986] Cannot read property \'model\' of undefined 

Log: showing 20 of 332019-06-19 10:06:42 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-06-19 10:06:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.5.9',
)]
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_form callback needs to run more 2 times 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (2 of 3, 67%) 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start (2 of 3, 67%) 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (3 of 3, 100%) 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-06-19 10:06:43 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start (3 of 3, 100%) 
2019-06-19 10:06:44 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-06-19 10:06:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.4',
  'to' => '2.5.9',
)]

PHP: showing 1 of 1PHP: 2019-06-19 10:06:44 [warning X 1][/home/hakunamatata/public_html/box/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::705] in_array() expects parameter 2 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				

```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by amindiary** [comment]
Rolled back to  Elementor pro Version 2.4.8 and solved.

**Comment by shilo-ey** [comment]
Hi @amindiary 

Thanks for reporting.

We can't reproduce your issue.
Please make sure you have an ID in your checkboxes fields, otherwise - add one (located under the **fields** advanced tab)

If this hasn't solved the issue for you, please contact our support for specific assistance.

Thanks!
