### ISSUE TITLE
Disable Desktop Mode

### ISSUE THREAD

**Issue by MrWuBo** [elementor/elementor#8360]
Hi

I develop a mobile page builder for Elementor, so I only need the tablet and mobile mode when editing the page, is there any method to disable the desktop mode for the specific post type?

Thanks

**Comment by shilo-ey** [comment]
Hi @MrWuBo 

To achieve this you'll need to use a JS+CSS "Hack":
- On editor load, you'll need to change the view to tablet
- You'll need to disable the option to select desktop in the bottom footer and in the responsive controls (prevent the user from clicking on it)

**Comment by petr00101101** [comment]
Hello, how did you solve the problem?
