### ISSUE TITLE
Strip HTML-code from the dynamic post terms taxonomy

### ISSUE THREAD

**Issue by Barns-be** [elementor/elementor#8366]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Be able to display the raw dynamic post terms (taxonomy) title WITHOUT the link to the taxonomy.

**Describe the solution you'd like**
I want to be able to display the category of a post type on its singe page template (this is possible I know), BUT without the HTML A-tag wrapped around it. So question: is there a way to strip this HTML content from the dynamic post terms element, so the raw taxonomy-title is all that's left?

**Describe alternatives you've considered**
I found a solution in case I just want to display the title: I disable the link using CSS. HOWEVER, I also want to use the taxonomy's title as a CSS class, and in that case the HTML-tag should be really stripped from the dynamic post term.

**Comment by shilo-ey** [comment]
Hi @Barns-be 

Thanks for your suggestion.

We will consider adding this option in the near future. 

Thanks

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!
