### ISSUE TITLE
Shortcodes are getting parsed in frontend-instance of TinyMCE-editor if page got created with Elementor

### ISSUE THREAD

**Issue by Asgaros** [elementor/elementor#8371]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If a WordPress-page is created by using Elementor and the page contains an instance of TinyMCE in the frontend, shortcodes are getting parsed/executed inside of the TinyMCE editor textfield instead of showing the shortcode-markup. This makes it impossible to modify the shortcode because its getting replaced by the logic behind the registered shortcode.

## Steps to reproduce

Install and activate the following three WordPress extensions:
- Elementor
- [Asgaros Forum](https://wordpress.org/plugins/asgaros-forum/)
- [Better Font Awesome](https://wordpress.org/plugins/better-font-awesome/)

Now create a new WordPress-page with the Elementor page-builder:
- Add a text-editor widget to that page
- Add the [forum] shortcode to that page - this is necessary because the Asgaros Forum-plugin uses the WordPress TinyMCE-editor in the frontend which is used in this example to reproduce the issue
- Save/Publish the page and open the page in the front-end

![forum](https://user-images.githubusercontent.com/12525671/59919463-c1f1de80-9427-11e9-8c9e-e94a1242a00c.PNG)

Now navigate to the "First Forum" and press the "New Topic" button:
- Enter some subject of your choice
- Add the following shortcode to the TinyMCE textarea: [icon name="coffee"]

![init](https://user-images.githubusercontent.com/12525671/59919748-97545580-9428-11e9-96d5-11c62c22ca6e.PNG)

This shortcode is part of the "Better Font Awesome" extension and should show a coffee-icon. So lets create the topic by pressing the "Submit" button. You get redirected to the topic and the coffee-icon is shown as expected:

![show](https://user-images.githubusercontent.com/12525671/59919786-acc97f80-9428-11e9-8ce2-7aefe387c1c4.PNG)

Now edit the forum-post by pressing the "Edit" button. Instead of showing the shortcode-tag inside of the editor, the shortcode-tag gets executed/parsed inside of the editor which makes it impossible to edit it (actually in this example its not even visible anymore):

![gone](https://user-images.githubusercontent.com/12525671/59919904-05008180-9429-11e9-97cc-8c2763f36d3d.PNG)

Now do the following:
- Enter the administration-area in another tab
- Disable Elementor
- Go back to the forum-post edit-screen
- Refresh the page
- Now the shortcode-tag is shown as expected without getting executed/parsed

![correct](https://user-images.githubusercontent.com/12525671/59919968-3da05b00-9429-11e9-813b-078de6f36911.PNG)

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.3.5
	MySQL version: mariadb.org binary distribution v5.6.43-84.3
	PHP Version: 7.3.5
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://localhost/wordpress
	Home URL: http://localhost/wordpress
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Debug Mode: Active

== Theme ==
	Name: Asgaros
	Version: 2016.12.26
	Author: Thomas Belser
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

== Active Plugins ==
	Asgaros Forum
		Version: 1.14.11
		Author: Thomas Belser

	Better Font Awesome
		Version: 1.7.1
		Author: Mickey Kay

	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Loco Translate
		Version: 2.3.0
		Author: Tim Whitlock

	Query Monitor
		Version: 3.3.6
		Author: John Blackbourn


== Log ==
	: 
JS: showing 1 of 1JS: 2019-05-28 20:59:18 [error X 1][http://localhost/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.15:2:53511] Cannot read property \'noUiSlider\' of undefined 

Log: showing 1 of 12019-05-30 16:32:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.15',
  'to' => '2.5.16',
)]


				
```
</details>

**Comment by FlyThePlanet** [comment]
I confirm, I have this exact same issue! :(

**Comment by FlyThePlanet** [comment]
Any news on this important issue?

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
