### ISSUE TITLE
editing elementor through child theme 

### ISSUE THREAD

**Issue by mmalgaz** [elementor/elementor#8372]
Hello, I would like to edit the elementor login.php file in my created child theme. In that way I can change the language of some labels on the elementor login page safely (I am not a developer). I tried adding the login.php file directly to my child theme, but that doesn't work. Do I have to create a folder in my active theme's folder (child theme)? What would be the name of the folder? This worked on my website with the Plugin Restrict Content Pro. With adding the "rcp" file to the theme, I am now able to make a lot of changes to the pages of Restrict Content Pro, even though I don't know any CSS. 

 thanx in advance, 

Marie

**Comment by shilo-ey** [comment]
Hi @mmalgaz 

Elementor has an API with Hooks & filters, so you can do so quite easily.

[Read more here](https://developers.elementor.com/)

**Comment by mmalgaz** [comment]
Hi Shilo, 

thank you for answering. Unfortunately, using Hooks & filters is to complicated for me. I am not a developer, just using elementor pro to create a site for my self. It would have been so easy for me if I could just edit the login.php file in my child theme. 

Marie
