### ISSUE TITLE
Add Hyperlinks to Color Palette

### ISSUE THREAD

**Issue by niftydesigns** [elementor/elementor#8376]
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I love that Elementor released the Hello theme. However, the Hello theme, like many others, does not allow for global changing of hyperlink colors. Hello theme defaults to an ugly pink color. In Elementor Pro, the only way to change hyperlink colors is on a section by section basis. This is both time consuming and completely unnecessary. We should be able to, within Elementor Pro, globally select a color for hyperlinks and then have the option to change it on a per-section basis, if necessary. 

**Describe the solution you'd like**
The easiest solution would to add a 5th option to the default color palette that is simply for global hyperlink colors. This would save the time of having to worry about changing it on the theme level as well as reduce possibility of issues with having to write custom CSS to try and fix it. It would also save a ton of time by not having to deal with each hyperlink on each section of every page we build.

**Describe alternatives you've considered**
A secondary solution would be to add color customization to the Hello Theme. However, this would not be helpful for anyone who chooses to not use that particular theme.

**Comment by shilo-ey** [comment]
Hi @niftydesigns 

I merged this issue with #5252, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
