### ISSUE TITLE
Allow plugins / themes to add body classes to the editor wrapper

### ISSUE THREAD

**Issue by aj-adl** [elementor/elementor#8397]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I'm frustrated that as a developer I cannot add styles to the `<body>` tag of the editor, without using javascript. 

**Describe the solution you'd like**

As is the norm in WordPress, I should be able to affect these classes via a filter

**Describe alternatives you've considered**

Enqueuing a custom script in my theme / modules that adds these classes, however this is verbose, as I need to perform all checks /logic, then pass the results to the front end via `wp_localize_script`, then use JS to add classes to the editor `<body>` based on these values.

**Additional context**

Should have no side effects, filter has been named in accordance with established conventions. 

PR completed, this issue is for referencing from the incoming PR.

**Comment by bainternet** [comment]
@aj-adl 

Thanks for the suggestion,

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
