### ISSUE TITLE
Saving custom CSS when resetting styles

### ISSUE THREAD

**Issue by kneops** [elementor/elementor#8401]
The situation:

I styled a nav menu. I added a background that could not be removed and although I set no animation, the background kept sliding in. So I reset the styles. But that also deleted all my custom css..... :(

Adding custom css can be a lot of work and should be pretected from deleting. So do NOT delete custom css or add an extra checkbox 'Reset custom css as well?' Or a global setting that does this.

**Comment by arielk** [comment]
It's a Reset style, that's exactly what this ability is supposed to do. Anyway you can go back by CMD\CTRL+Z or by revision history.

Thanks
