### ISSUE TITLE
Elementor Form - Scroll to Anchor after submit

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#8420]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When a form is submitted successfully, the success message, if it is long, is not fully displayed if the submit button is near the bottom of the page.

**Describe the solution you'd like**
Ability to add an anchor as an action after submit. Like 'Redirect' but with an anchor.
Eg, action after submit #footer 

**Describe alternatives you've considered**
I tried 'Redirect', but it didn't scroll to the anchor

**Comment by bainternet** [comment]
@simonclay 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can catch the submit event and trigger a scroll to your anchor,

```JS
jQuery( document ).ready( function( $ ) {
	jQuery( document ).on( 'submit_success', function() {
		// form has been submitted do your scroll
		var aTag = $( "a[name='"+ YOUR_ANCHOR_NAME_HERE +"']" );
		jQuery( 'html,body' ).animate( { scrollTop: aTag.offset().top }, 'slow' );
	});
});
```
Thanks for the feedback.

**Comment by simonclay** [comment]
Thank you, that's helpful.

**Comment by jshapi05** [comment]
Hey @bainternet - just stumbled across this thread since I'm looking for this functionality. I tried to implement your jQuery into the Customer Code section of Elementor, and inserted the corresponding anchor name, but it doesn't seem to be working. Any chance you could help me out here?

**Comment by tomherold** [comment]
I would be interested in a solution too, especially for the multipage form. It is confusing for the user.
