### ISSUE TITLE
Loading Elementor Template with Form Using AJAX

### ISSUE THREAD

**Issue by chris-castillo-dev** [elementor/elementor#8428]
I have a page where there are four user options to choose from. 

[https://www.pdms.ca/discovery](https://www.pdms.ca/discovery)

Once the user clicks on an option I want to load the Elementor form that corresponds to the option the user selected using an AJAX call to a simple PHP script I wrote.  

The PHP script gets the Elementor ID that corresponds to the Elementor template I created that has the form included in the template. Using:
 `<?php echo do_shortcode('[elementor-template-ID]'); ?>` 
I return the code back to the Ajax call and then use jQuery to insert the template code into the page. 

So far, I've managed to get this to work well and have even added the template's stylesheet in the Ajax complete callback function. The only problem I've run into is that the form doesn't submit properly when it's loaded using AJAX. 

If I preview the template for any of the forms, I can submit the form fine. Is there a specific javascript file I need to add to the page in my AJAX   complete callback function? How can I get this to work?

**Comment by royhas** [comment]
Hey, did you manage to find solution for this? @chris-castillo-dev

**Comment by chris-castillo-dev** [comment]
> Hey, did you manage to find solution for this? @chris-castillo-dev

Yeah, I did actually but it was a while ago and I can't recall what the solution was. I looked at the code and I don't see anything that shows that I included any specific scripts to get the form to work - so I think the form may not have been submitting because of a problem unrelated to the AJAX loading of the form (perhaps a javascript error from a different script).
