### ISSUE TITLE
Mobile preview displays shape divider height incorrectly

### ISSUE THREAD

**Issue by zimirando** [elementor/elementor#8432]
Hi,
I have a shape divider on my website that looks great on the desktop and tablet, but on the smartphone is way too long, although I've set the height so that it is correct in the preview. After a few days, I came up with the idea to change the theme and was in the mobile preview of the Page Builder Framework: The shape divider was presented as I could see it on my phone. I would ask you to fix this problem as soon as possible.

Best regards

**Comment by lior-sh** [comment]
invalid issue report
----
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
