### ISSUE TITLE
Five Stars in testimonial Carousel

### ISSUE THREAD

**Issue by mike425900** [elementor/elementor#8440]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've added a testimonial carousel to my website and see others with five star graphics underneath the testimonial. I believe this added feature would be a great way to enhance both my website and the feature. Ideally I'd be able to post the testimonial, post the picture of the person who left the testimonial and have a visual image of how many stars they left consistent with their google/yelp/bing review. 

**Describe the solution you'd like**
I envision a slider to enable or disable the feature to add stars and when enabled, have a drop down box with 1,2,3,4, or 5 stars. The stars would then appear under the persons picture or quoted text testimonial.

**Describe alternatives you've considered**
I've looked for additional plug ins to make this happen and there are options out there which do this including Essential Addons for Elementor however, this seems like such a small reason to purchase a whole new premium package and what i'd imagine to be an easy addition to the existing feature.

**Additional context**

**Comment by shilo-ey** [comment]
Hi @mike425900 

Have you tried our [Reviews widget](https://docs.elementor.com/article/442-reviews-widget)?

It acts the same... Try it :)

Thanks
