### ISSUE TITLE
"Insert" button for icon box does not appear until you hover

### ISSUE THREAD

**Issue by Mycelus** [elementor/elementor#8441]
Version 2.6.0-beta1

When attempting to add an icon to an icon box element, the "INSERT" button does not appear until you hover over the invisible white section, where the button then appears.

Before hover: https://i.imgur.com/uY4B7Mv.png
After hover: https://i.imgur.com/73E6aiY.png

**Comment by shilo-ey** [comment]
Hi @Mycelus 

Thanks for reporting.

This has already been reported in the beta thread. Please report beta related issues only there.

#8431
