### ISSUE TITLE
Dynamic content popup trigger button not working with custom post type

### ISSUE THREAD

**Issue by aidanweltner** [elementor/elementor#8442]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I created a custom post type, 'Projects', that is meant to just add a custom slug structure to project posts (i.e. localhost/work/post). I have a global footer and header that I made using the Elementor theme builder. Both the header and the footer have a custom link that opens a popup (also built with the Elementor theme builder). The link works throughout the site: on the home page, archive pages, and standard Wordpress blog post pages. This link does not work on the custom post type pages, however. The popup is a lead generator and the site is currently under development. I would love to figure out a temporary code fix or have a fix in the newest release of Elementor before launch!  

## Steps to reproduce

1. Made a global header and footer using the Elementor theme builder
2. Made a popup (with no display conditions) using the Elementor Theme builder
3. Copied the link structure from a button with a dynamic content trigger -- "#elementor-action%*very long string*"
4. Added the link to a footer and header menu
5. Tested the menu link on a custom post type page with no popup triggered
6. Tested the menu link on all other pages and posts and the popup triggers no problem

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- I can't test using a default Wordpress theme because I wrote the custom post type php into the child theme to Hello
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '28', Revision 'c335905' v5.7.25-28
	PHP Version: 7.2.18-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.1
	Site URL: https://fldtraces.wpengine.com
	Home URL: https://fldtraces.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.1.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

== Active Plugins ==
	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.5.16
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.9
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.9
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	ShortPixel Image Optimizer
		Version: 4.13.1
		Author: ShortPixel

	SyntaxHighlighter Evolved
		Version: 3.5.0
		Author: Alex Mills (Viper007Bond)


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine System
		Version: 3.2.1
		Author: WP Engine


== Log ==
	: 
JS: showing 2 of 2JS: 2019-05-13 11:48:44 [error X 1][https://fldtraces.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.14:2:53462] this.ui.sliders.filter(...)[0] is undefined 
JS: 2019-06-04 23:50:07 [error X 6][https://fldtraces.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:53511] Cannot read property \'noUiSlider\' of undefined 

Log: showing 2 of 22019-05-31 18:22:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.14',
  'to' => '2.5.16',
)]
2019-05-31 18:22:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.5.9',
)]

PHP: showing 1 of 1PHP: 2019-06-04 22:36:51 [notice X 16][/nas/content/live/fldtraces/wp-content/plugins/elementor/includes/managers/image.php::80] Undefined offset: 2 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by carlenmy** [comment]
👍 I have the same problem. Any support would be greatly appreciated. I am using Custom Post Type UI 1.6.2, Elementor pro Version 2.5.2. 

When the custom post type is open in the Elementor Editor the popup works just fine, but does not activate when live.

**Comment by arielk** [comment]
Sorry for the delay, if you are still having trouble please contact support@elementor.com with full login information for accessing your site and our support team will try to help.
