### ISSUE TITLE
preserve original filename on upload via form

### ISSUE THREAD

**Issue by PP100** [elementor/elementor#8443]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When image files are randomly renamed when uploaded via the form the original filename (which may  contain descriptive, important or useful information ) is not preserved

**Describe the solution you'd like**
I appreciate the renaming may be for security reasons or to avoid overwriting an existing file so I suggest if possible a random part is appended to the original filename  as long as the original file name  remains readable eg filename.jpg becomes filename94928428.jpg

**Comment by bainternet** [comment]
@PP100 

Currently, we are not going to change this behavior, however, we are passing the filename via `wp_unique_filename()` a WordPress native function that has a filter you can catch and alter the filename, ex:

```PHP
/**
 * @param string        $filename                 Unique file name.
 * @param string        $ext                      File extension, eg. ".png".
 * @param string        $dir                      Directory path.
 * @param callable|null $unique_filename_callback Callback function that generates the unique file name.
 */
add_filter( 'wp_unique_filename', function( $filename, $ext, $dir, $unique_filename_callback ) {
	static $file_count = 0; //used to get the current file when multiple uploads in a form
	// first make sure its an upload via elementor forms
	if ( false === strpos( $dir, '/elementor/forms' ) ) {
		return $filename;
	}

	// get the original file name
	$path_parts = pathinfo( $_FILES['SET_FORM_FIELD_ID_HERE'][ $filename ] );
	// Bump counter for next file
	$file_count++;
	// Return your desired file name (original-unique_suffix.extension)
	return $path_parts['filename'] . '-' . $filename;

}, 10, 4 );
```

You can actually return the original filename but as you know and understand, we recommend against it.

**Comment by PP100** [comment]
Ok but where  do I use that code? Paste into  functions.php? I do not write code but can copy and paste if straightforward (obviously at my own risk)

**Comment by bainternet** [comment]
In a custom plugin or your themes functions.php would be just fine.

**Comment by PP100** [comment]
Ok I though it might be .Thanks. I might experiment with it.

**Comment by ted-mccarthyfinch** [comment]
Hi

I have tried using the function you have provided and it didn't seem to work. It simply added the '-' to the start. I've changed 'SET_FORM_FIELD_ID_HERE' to the id of the file upload field.

Any suggestions?

Cheers

**Comment by mohammad-mekawy** [comment]
Check this please #20170

**Comment by pshaughnessy88** [comment]
Trying to use the code provided by nicholaszein in my child theme. I am not getting the original file name. I added the field id of my upload field and all I see is -uniqueID.ext. How do I get the original file name.

**Comment by rwkyyy** [comment]
@bainternet thank you, was just what I needed to make the file rename; is there a way to also rewrite the links that are saved and showed in: e-form-submissions and mailed ?
