### ISSUE TITLE
[Bug] Star rating widget responsive alignment not working

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#8444]
When I adjust the alignment (left-justify, center, right-justify) of the _Star Rating_ widget it changes the alignment on all devices. I can't seem to set a different alignment on different devices. 

For example, if I center the _Star Rating_ widget on mobile it changes the desktop and tablet alignment to also be centered.

**I've reproduced this issue on a fresh local install using:**
Elementor (latest)
Elementor Pro (latest)
Astra (latest)
No other plugins installed

**Comment by shilo-ey** [comment]
Thanks, we will address this issue and update here.
