### ISSUE TITLE
Elementor Background custom size height.

### ISSUE THREAD

**Issue by AshekurRahman** [elementor/elementor#8445]
![Screenshot_1](https://user-images.githubusercontent.com/31946194/60393155-898e8680-9b32-11e9-997f-7cb7d5620579.png)

I think there are need to add background size height property.

**Comment by shilo-ey** [comment]
Hi @AshekurRahman 

We allow setting only one dimension because the other dimension (height) is set to `auto` and more likely to be changed due to responsive screen sizes.

**Comment by black-eye** [comment]
+1 Sometimes you need to adjust the bg image by height not width. Having this option would be really handy, I'm really missing it. When the second dimension is left empty, "auto" would be used as default.

I was really excited when updated bg settings was released, but it's still not complete and this is one of the shortcomings. Still using plain css for more complicated bgs.
