### ISSUE TITLE
Trigger popup on document ready

### ISSUE THREAD

**Issue by shirokoweb** [elementor/elementor#8449]
Hi,

Because of restricted age content, I need to display a popup until visitor submits a form.
"Are you over 21? YES lemme in / NO take me out !"
This can be done via a simple condition get / set cookie, but I can't figure how to open a popup with javascript. How do I open a popup on document ready please ?
I asked on support but they suggested ask on GitHub.

```JS
(function($) {
    $(document).ready(function() {
        // check for verified cookie
        var verified = Cookies.get("verified")

        if (verified == null) {
            // CODE TO OPEN POPUP  
        }

        // set cookie on form submit
        $( document ).on('submit_success', function(){
            Cookies.set('verified', 'yes', { expires: 1, path: '/' });
        });
    });
})(jQuery);
```

**Comment by shilo-ey** [comment]
Hi @shirokoweb 

Please use [our documentation](https://docs.elementor.com/article/508-how-to-create-a-content-lock-popup) to create what you wish.

Thanks
