### ISSUE TITLE
Dynamic content with popup conditions and triggers ( Mega update for elementor )

### ISSUE THREAD

**Issue by amoyastudio** [elementor/elementor#8450]
Guys, you did a great job in the popup trigger and conditions ( i sew some minor bugs but it's good!! ) I have an idea for a great great feature that will boost elementor higher ... 

It's Called,
Dynamic Content

the idea is the have the option to make a section\coloumn to a dynamic one...
you can control the show\hide of it by the conditions and triggers of the popup options.

_**but you just need to make a little bit more thing in the rules of it, please add OR | AND to the rules so i can have several rules that are true to make the section\coloumn show.**_

**examples of use:**
- make dynamic content to people who is returning to my site
- make dynamic content to people who come from facebook\google\organic source
- make dynamic content to people and offer coupons
- make dynamic content and split test A/B ( this is more advanced option that will need to be track also, maybe it's not relevant to the main feature for now  )
- make dynamic content for people who press specific buttons 
and more....

Hope you'll like it and make it already !! :)

**Comment by shilo-ey** [comment]
I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
