### ISSUE TITLE
Gravity forms Total field not updating when adding items in Elementor popups

### ISSUE THREAD

**Issue by wellnix61** [elementor/elementor#8452]
Still having one issue with Gravity forms inserted into Elementor popups. The Totals field will not update the amount total after adding product items. It stays as $0.00. Using test environment with Stripe, the correct amount does get sent, but the viewer doesn't see the total until they get their receipt email. This doesn't happen using Popup maker plugin, just Elementor popups.  I have tried ajax="true" and "false" and different tabindexes.

https://ncsfa.site/2019-convention/#schedule-2019

Click on any of the "Click for Details" text links and then click the "Purchase a Ticket" button to see the gravity form. Try adding a ticket and watch the total field.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
