### ISSUE TITLE
lighttpd "The Content Area Was Not Found in Your Page"

### ISSUE THREAD

**Issue by Mr-Krab** [elementor/elementor#8453]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The editor does not open when using any links other than simple ones.

## Steps to reproduce

Install lighttpd and php 7.3
Install WordPress
Change link settings to any option other than the default
Install Elementor
Create a page with Elementor
Save the page and exit the editor.
Try to open the page in the Elementor editor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/RvDNMH7t
</details>

<details>
<summary>Screenshot</summary>
https://imgur.com/a/wMbohVj
</details>

**Comment by oscarsao** [comment]
Same Here.

**Comment by shilo-ey** [comment]
Hi @Mr-Krab @oscarsao 

Please add `?elementor-preview=<YOUR_POST_ID>`
to the post URL you are trying to edit (to the frontend link, not the editor link...)

Replace `<YOUR_POST_ID>` with the post ID you are trying to access.

This will lead you to the preview mode. Let us know what you see and if you have any console errors.

In addition, please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And see if the issue still persists.

Thanks

**Comment by Mr-Krab** [comment]
I tried what you told me and my page was displayed normally. And I didn't even need to disable plugins or change the subject.
However, in the case of the editor itself, nothing helps except changing the links to the following format `https://domain//?p=123`

**Comment by shilo-ey** [comment]
Does the timestamp of this issue is identical to the occurrences of this issue?

**Comment by Mr-Krab** [comment]
The problem appeared long ago, I can not even say exactly when. I just recently found out that it is linked to links.

**Comment by shilo-ey** [comment]
@Mr-Krab 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
