### ISSUE TITLE
Elementor Pro v2.5.10 shows PHP notice regarding notice bar

### ISSUE THREAD

**Issue by StreetDog1971** [elementor/elementor#8461]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The latest update of Elementor Pro is causing an error on WooCommerce checkout page.
I can place an order, but when I go to the checkout page it keeps loading forever.

With debug turned on I get this message:

Notice: Undefined property: Elementor\Editor::$notice_bar in /home/server/public_html/website/wp-content/plugins/elementor-pro/plugin.php on line 332

## Steps to reproduce

Add a product to the cart.
Go to checkout.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by StreetDog1971** [comment]
I was able to make it work by commenting the following lines in the plugin.php file listed in the error message:

/** TODO: BC for Elementor v2.6.0 */
if ( $elementor->editor->notice_bar ) {
$elementor->editor->notice_bar = new Notice_Bar();
}

**Comment by teoeugene** [comment]
I found that this issue happened in my sites that I've updated to Elementor Pro to 2.5.10

**Comment by astbarc** [comment]
Same error on my sites with Elementor Pro to 2.5.10

**Comment by Daniel-Richard** [comment]
Yeps. Query monitor shows this error in Dashboard upon updating Elementor Pro to 2.5.10.

Undefined property: Elementor\Editor::$notice_bar | 1 | +wp-content/plugins/elementor-pro/plugin.php:332

**Comment by crazypsycho** [comment]
You can just replace the line 332 in plugin.php with
´´´
if ( isset( $elementor->editor->notice_bar ) ) {
´´´

But i think this notice will disapear when elementor 2.6 is out, cause than notice_bar will exists.

**Comment by shilo-ey** [comment]
Thanks for reporting. We are aware of this issue and a patch version will be released soon.

We will update this thread when there's an update. stay tuned.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.5.11

Feel free to update

Thanks!
