### ISSUE TITLE
HTTPS and Mobile background

### ISSUE THREAD

**Issue by ToToL** [elementor/elementor#8462]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I set the background reminder with the WP internal library. When I use this elsewhere, all URL are translated to HTTPS. But with the background reminder, the CSS generated do not do this translation so this URL is in HTTP.

## Steps to reproduce

Set the background reminder and access the WP in HTTPS

**Comment by shilo-ey** [comment]
Hi @ToToL 

One of your website/server SSL settings is not set up correctly. please make sure your website is set with HTTPS properly or contact your hosting provider.

Thanks
