### ISSUE TITLE
Access Denied - half way through the day

### ISSUE THREAD

**Issue by tlhintoq** [elementor/elementor#8469]
I don't believe this is related to #3935 - Because it didn't start happening until 3/4 of the way through the day.  Had this been a general security rules or plug-in conflict it would have happened from the start.

I had been making new pages for my site from 9am-3pm.  Added about 5 content-packed pages. Normal working with occasional 'save as draft' to be safe.  Around the 6th one I thought I'd try out the [ShortCode] widget.  Some time after adding that and pasting in actual CSharp code block I wanted to display on the page I started noticing a small popup appear and disappear over the [Publish] button.  It would come and go so I thought it was a temporary network issue.  NOPE:  Somehow after a full day of working fine I could no long save, publish, nothing.   To top it off, none of the work for that page was saved.

Being new to Elementor I couldn't find any "save off line" kind of feature. I'm sure its there and I'm just too new to find it.  But once I navigated [back] and [forward] or tried to reload the page it wouldn't have mattered: It was gone for good.

Could this have just been some sort of time-out from the BlueHost hosting provider? Or is this related to use of the [ShortCode] widget with code tags?

**Comment by shilo-ey** [comment]
Hi @tlhintoq 

This issue might be caused by a server error or invalid code running and causing this issue in the server. 

We do have history and revisions support, but not locally.

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

thanks.

**Comment by horstenegger** [comment]
@tlhintoq were you able to resolve this? We just started facing the exact same issue, curiously only for certain pages of the same type, but not for all ¯\_(ツ)_/¯

If you have anything to share, thank you in advance for your time.

**Comment by duedeu36** [comment]
Similar problem here with the same message "Access denied"
When I try to save my page as "save as draft" the message pops up. Furthermore, when I upload images and trying to add them throught Elementor, the image kinda disappears or is shown as broken

**Comment by VuyiChaza** [comment]
So I was able to solve this by simply going to edit page with wordpress, saving it then saying edit page with Elementor. The page that I was denied access to editing came back. Another option to try is to revert to an earlier version.

**Comment by Gaia4131** [comment]
> So I was able to solve this by simply going to edit page with wordpress, saving it then saying edit page with Elementor. The page that I was denied access to editing came back. Another option to try is to revert to an earlier version.

Thank you so much :-* you saved my life.

**Comment by DanishBux** [comment]
I am also getting the same problem but I got a easy solution:
Scenario:
First I have edited my "homepage" with Elementor and later I started editing my "About us" page, I am on my half way and I tried to update page to save 50% changes but I saw a small error near update button which was "Access denied", at first, I got confused but I think off a solution as I was editing my site on localhost "XAMMP" which was:
Solution:
I duplicated the the tab in which my "About us" page was open, there was nothing on duplicated tap and then I clicked on my first "About us" tab and clicked on "update" at this point the error is fixed.
