### ISSUE TITLE
EA Advanced Accordion

### ISSUE THREAD

**Issue by Edgewood58** [elementor/elementor#8470]
I have been using the EA Advanced Accordion on pages throughout the site including 2 on a page. It works great and when using it with the templates it's a great tool. On one page thought I have an accordion that is using text from the content area and have tried to include hard returns and soft returns and for some reason on this particular page only the hard return doesn't work as it should. It looks like a soft return. On other pages that are in similar format the hard return works.

**Comment by shilo-ey** [comment]
Hi @Edgewood58 

EA is a 3rd party add-on for Elementor, try contacting them for support in their product.

Thanks
