### ISSUE TITLE
after_add_attributes not working in preview mode

### ISSUE THREAD

**Issue by beezio** [elementor/elementor#8471]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I tried to add some data and class to `_wrapper` selector of all widgets with action `after_add_attributes` and its working fine on frontend but not working on preview mode.

## Steps to reproduce

- I added one control to all available widgets with action `after_section_end`
- I added data of my new control to all widget with action `after_add_attributes`
- Everything is fine but in the preview mode, I can't get the data attribute for the widget wrapper
- I can't find also how to call JS function after each widget changes

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@beezio 	

These filters do not, nor are they supposed to affect the JavaScript Template of the editor.

You can, however, listen for `frontend/element_ready/widgetname` hook event and use the `$scope` to add your class.

But if all you are doing is adding a class then you can do that directly for the control using `prefix-class` parameter of the control ex:

```PHP
$element->add_control(
	'btn_style_class',
	[
		'label' => 'Button Style',
		'type' => \Elementor\Controls_Manager::SELECT,
		'options' => [
			'fancy' => 'Fancy',
			'stylish' => 'Stylish',
			'rounded' => 'Rounded',
			'square' => 'Square',
		],
		'prefix_class' => 'btn-style-',
	]
);
```

thanks.

**Comment by beezio** [comment]
@bainternet `prefix-class` works as expected, Thanks, just JS not telling me about class changes.

```JS
$(window).on( 'elementor/frontend/init', function() {

  elementorFrontend.hooks.addAction( 'frontend/element_ready/beezio_tabs.default', function( a, b ) {
    console.log( a, b );
  } );

});
```

The code works when element change via AJAX for rendering new data, but not works for class changes. 

Not sure I am on the right way or no.
