### ISSUE TITLE
Can permissions plugins hook into Elementor capabilities

### ISSUE THREAD

**Issue by stevejburge** [elementor/elementor#8474]
We were told to ask here after trying to help this user:
https://wordpress.org/support/topic/capability-manager-enhanced-conflict/

Is it possible for other plugins to hook into the Elementor permissions system?

**Comment by bainternet** [comment]
@stevejburge 	

It is possible in some levels, What are you trying to achieve?

**Comment by stevejburge** [comment]
Thanks @bainternet 

We run the Capability Manager Enhanced plugin. We'd like to add support for Elementor.

**Comment by bainternet** [comment]
Can you please elaborate, support in what why?

**Comment by stevejburge** [comment]
If you install the Capability Manager Enhanced plugin, you can automatically access the permissions for almost every WordPress plugin.

However, not Elementor. People have been asking why they can see permissions for other plugins but not Elementor

**Comment by stevejburge** [comment]
Hi @bainternet Any luck with this, please?

**Comment by bainternet** [comment]
@stevejburge 

There is no Public API for this, So you can get this done but with some custom hacking.

Sorry I can't help more than that.
