### ISSUE TITLE
Elementor Exit Intent on Phone on back button Click

### ISSUE THREAD

**Issue by Farukh1x95** [elementor/elementor#8479]
I want to open Elementor pop up on Exit intent On the phone. When I clicked on back button Elementor pop Will Be Trigger.

I create an alert on the click back button on the phone. so my alert function is properly working.

But the Elementor pop up trigger is not Working.

**Comment by bainternet** [comment]
@Farukh1x95 	

As far as I know, you can only trigger browser native ( alert, confirm ) dialogs,
So unless you know something else ... this is currently, not really possible.

thanks.

**Comment by web1design1agency** [comment]
this feature has been soooo needed and so much requested since 2019 and so many popup plugins offer it today why is elementor being left so much behind so that i need to go pay for another plugin just for this one feature, i think i'mma quit paying for elementor since i have to pay for plugins that do give exit popup on smartphone back button instead of letting them leave rightaway and losing all of the leaving 85% of my visitors on mobile as the feature is useless on desktop, no one uses computers to shop nowdays anymore!!!!!!

**Comment by staenglitzy** [comment]
How to Add an Exit Intent Pop-Up for mobile and desktop  in Elementor - stan Abara

If you want a pop-up to show when a user tries to leave your form page by clicking links or using the back button, follow these steps:

### Steps:

1. Copy the Code and paste in your website:

    <script>
document.addEventListener("DOMContentLoaded", function() {
    // Function to show Elementor popup
    function showExitPopup() {
        elementorProFrontend.modules.popup.showPopup({ id: "YOUR_POPUP_ID" });
    }

    // Detect back button click (popstate event)
    window.onpopstate = function() {
        // Prevent the user from going back and show popup
        history.pushState(null, null, window.location.href);
        showExitPopup();
    };

    // Push initial state to history to track back button
    history.pushState(null, null, window.location.href);

    // Prevent clicking on any links except form submit button
    document.querySelectorAll('a').forEach(function(link) {
        link.addEventListener('click', function(e) {
            if (!e.target.closest('form') || e.target.type !== 'submit') {
                e.preventDefault(); // Stop the default link behavior
                showExitPopup(); // Show popup instead
            }
        });
    });
});
</script>

   
    


**Hey?**

If this was helpful, and you think I deserve it, follow me on [[LinkedIn](https://www.linkedin.com/in/stan-abara-686059197/)](https://www.linkedin.com/in/stan-abara-686059197/) 😉

---
