### ISSUE TITLE
Hide in Show popup automatically

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#8481]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Popup has no option to be hidden or automatically shown on a specific date.

**Describe the solution you'd like**
Sometimes we campaign with an end date, and during the campaign we use popup on the pages of our site. And when we finish the campaign, we want this popup to be hidden. But to not have to do this manually, you could have the possibility to do this automatically, that is, we insert an end date and when that date arrives, the popup is hidden. It would look like the countdown timer.

In addition to automatic popup hiding after a specific date has arrived, you could also be able to enter a specific date for the popup to be shown automatically. So when a campaign starts tomorrow at 8am, we can already set it to start automatically.

Thank you!
Rodrigo

**Comment by shilo-ey** [comment]
I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there @rodrigocarlos!

### 📢 We're a bit late, but are happy to announce that this feature was released with Elementor Pro **v3.11**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
