### ISSUE TITLE
Image Carousel Widget preview image size

### ISSUE THREAD

**Issue by filipp8** [elementor/elementor#8482]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Fast render when editing pages with image carousel

**Describe the solution you'd like**
When editing pages with Image Carousel there is lag caused by full size image squeezed inside the preview. Use thumbnail instead

![image](https://user-images.githubusercontent.com/15673118/60759238-008bb980-a022-11e9-9df7-08e88d41d647.png)

**Comment by bainternet** [comment]
@filipp8 	


Thanks for the suggestion,
Sadly this is not currently possible as the rest of the image sizes URLs are not available to the Panel and simple to fetch each and every one of them would definitely cause a lag, even in cases when there is no lag today.

thanks.
