### ISSUE TITLE
HTML email will keep the carriage returns/line feeds.

### ISSUE THREAD

**Issue by CryBabyOne** [elementor/elementor#8485]
I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor form
Textform sent with HTML email

Using a textform for example in a open essay or a list and adding text with carriage returns/line feeds sent as HTML email it strips all carriage returns/line feeds and the text comes in one long row (oneliner).

For example:
First sentence
Second sentence
Third sentence

Comes out like:
First sentence Second sentence Third sentence

Feature request
I would like the HTML email keep the carriage returns/line feeds.

**Comment by bainternet** [comment]
@CryBabyOne 

When some inputs new lines in a textarea field, it is sent to the server as "\n", now when you send an email as HTML this "\n" is not translated to a new line.
But you can easily translate it using the provided hooks of [Elementor Pro Forms API](https://developers.elementor.com/forms-api/) ex:

```PHP
add_action( 'elementor_pro/forms/process/textarea', function( $field, $form_record, $ajax_handler ) {
	/**
	 * @var array        $field        Form field.
	 * @var \ElementorPro\Modules\Forms\Classes\Form_Record  $form_record         An instance of the form record.
	 * @var \ElementorPro\Modules\Forms\Classes\Ajax_Handler $ajax_handler An instance of the ajax handler.
	 */

	// First check if its you field
	if ( 'YOUR_FIELD_ID_HERE' !== $field['id'] ) {
		return;
	}

	// Update the value with br's instead of "\n"
	$form_record->update_field( $field['id'], 'value', nl2br( $field['raw_value'] ) );
}, 10, 3 );
```

thanks.
