### ISSUE TITLE
Page ID numbers visible within Theme Builder.

### ISSUE THREAD

**Issue by jasonb4u** [elementor/elementor#8488]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. The one made before was CLOSED as wasn't completed properly.  No need to close this immediately!
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This would help minimize confusion when adding items to the Theme Builder if there are other pages/posts etc with the same names with different ID's and the ID's and can narrow down and identify exactly which
 item is needed.

**Describe the solution you'd like**
Codes that pull the ID's into visibility which helps make selections easier

**Describe alternatives you've considered**
I am not a full stack developer therefore I can execute the functions.

**Additional context**
Example of the outcome image screen snap here: https://prnt.sc/obkpgj
![image](https://user-images.githubusercontent.com/20693414/60774099-6c6d3f80-a152-11e9-8799-2515cd4beeff.jpg)

**Comment by zeinnicholas** [comment]
I'm sorry but why would you give the same name to different pages?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by jasonb4u** [comment]
> 
> 
> I'm sorry but why would you give the same name to different pages?

The builder shows the TITLE, not the URL or the ID....

**Comment by jasonb4u** [comment]
@bainternet why the hell are you closing these right away, whats with you.  How the heck is anyone to get items properly looked at or others comment when you close threads, WOW!!!!
Make it open!
Thank you!

Feed up with having to make new threads just coz you close them when you want.
