### ISSUE TITLE
Dynamic field showing all ACF fields as ACF options page fields

### ISSUE THREAD

**Issue by DanSiTDan** [elementor/elementor#8493]
Using Elementor Pro and ACF Pro.

So i have setup all acf post/page fields in the acf/init hook. I also setup an options page within the same hook.

In the Elementor editor, when selecting a dynamic field. all ACF fields for posts/pages are listed as an option field. e.g option:banner image. And Nothing is displayed when selecting one.
If i remove the options page. All goes back to normal and can select the actual ACF fields in the dynamic dropdown.

Any ideas why this could be happening?

**Comment by DanSiTDan** [comment]
Found the cause of this. Seems its on the ACF side. 
Registering fields in code doesn't assign them an id, in fact its always 0, same with the options page fields. When Elementor grabs the list of dynamic acf fields there is a check to see if any of the acf fields are an option field. As both have an id of 0, this is always true so marks all fields as an option field. 
Annoying "Bug" but giving your field group an ID on creation sorts this, although this may cause further problems as the post ids are assigned manually.

**Comment by DorShahar** [comment]
Thanks for finding it out (and sorry for the delay).
Closing the issue.
