### ISSUE TITLE
Integrate Webforms with Moosend E-Mail Marketing

### ISSUE THREAD

**Issue by kirchmeier** [elementor/elementor#8496]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem to be solved is not getting contacts into my newsletter/e-mail-marketing-system with elementor. My system is called Moosend, as far as i can see they have an API. 

**Describe the solution you'd like**
Moosend to be integrated with Elementor, so i can choose it from the options of what should happen when a webform is sent.

**Describe alternatives you've considered**
There is a plugin in the WP-repository, but it's very basic and doesn't solve all use-cases.

**Additional context**
Moosend is a high quality Newsletter and E-mail-Marketing system. I can see that it's not possible to integrate with all systems out there but imho this one is worth to take a look at, esp because of the possibility to integrate it deeply with wordpress and woocommerce.

Thank you! :)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can code your own integration following our [Custom Form Action API DOC](https://developers.elementor.com/forms-api/custom-form-action/)

Thanks for the feedback.

**Comment by GBallzus** [comment]
@bainternet please reopen this issue and merge with #10989 as there is a large demand for this feature; over 500 elementor users are using the [Moo Elements plugins ](https://wordpress.org/plugins/moo-elements/) as an alternative to a native integration between Elementer and Moosend. 

Thanks.

**Comment by GBallzus** [comment]
+1
