### ISSUE TITLE
Possible Bug in the "Paste Style" feature

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#8497]
When copying from a styled nav menu widget and paste style to another one, I observed that everything was pasted correctly, but not the pointer style. Looks like a little bug to me. I haven't checked, if every style elements is copied, other than pointer. So there might be more. The font style and the pointer color is definetly copied.

![image](https://user-images.githubusercontent.com/14095280/60820267-694d7000-a1a1-11e9-89e3-dc5684e1fd53.png)

**Comment by shilo-ey** [comment]
Hey @HelmutGoebel 

Thanks,

Have you spotted this issue in other widgets as well?

**Comment by HelmutGoebel** [comment]
No, I don't use it that often.

**Comment by HelmutGoebel** [comment]
Background color and shape dividers works fine.

**Comment by arielk** [comment]
Fixed in Pro Beta 3

Thanks

**Comment by HelmutGoebel** [comment]
Awesome!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.0

Feel free to update

Thanks!

**Comment by HelmutGoebel** [comment]
Yes, works fine. Thank you.
