### ISSUE TITLE
JS issue when loading share-buttons widget programatically in singlular page

### ISSUE THREAD

**Issue by bayasebastien** [elementor/elementor#8498]
I am loading a share-buttons widget programatically in a singular page based on this issuse:
https://github.com/elementor/elementor/issues/5817.
Everything is displaying fine but the JS responsible for sharing the page on facebook is not working. Adding the same widget through the page builder is working fine.

Below is my code:
```PHP
    $social_share = \Elementor\Plugin::instance()->elements_manager->create_element_instance([
        'elType' => 'widget',
        'widgetType' => 'share-buttons',
        'id' => 'recette-page-share',
        'settings' => [
            'share_buttons' => [ [ 'button' => 'facebook' ], [ 'button' => 'twitter' ]],
            'view' => 'icon',
            'skin' => 'flat',
            'shape' => 'circle',
            'alignment' => 'center',
            'share_url_type' => 'current_page',
        ]
    ], []);

    $social_share->print_element();
```

**Comment by shilo-ey** [comment]
Hi @bayasebastien 

This way of implementing widgets programmatically only "prints" the widget content without initiating the widget's assets or even loading them.

So basically you need to enqueue and init the widget yourself.

Thanks
