### ISSUE TITLE
Forcing Video Backgrounds in Mobile

### ISSUE THREAD

**Issue by batterykevin** [elementor/elementor#8499]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

We are trying to figure out how to get youtube video backgrounds working in mobile...I know you guys have it disabled for bandwidth reasons but we are replicating a client's site and would like to get this to work.  Their site was originally on Squarespace and they're somehow able to make the video BG's happen on mobile.  Is there a snippet I can add or perhaps I can edit the .elementor-hidden-phone class in CSS to force a display?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@batterykevin 	

Currently, this feature is not supported, for many reasons like browser support or youtube API guidelines.

So there is no way to do it without some custom hacking 🤪

Thanks for the feedback.
