### ISSUE TITLE
Why does elementor need jquery?

### ISSUE THREAD

**Issue by helvetica123** [elementor/elementor#8500]
when i dont call that files from header.php;

bootstrap-4.0.0-dist/jquery-3.3.1.slim.min.js
and
bootstrap-4.0.0-dist/popper.min.js ,

my theme wont work fully.some part of page doesnt load; some of them are default elements.however when i edit the page with elementor, everything is ok.doesn't jquery come from the plugin normally? or what is the problem?

**Comment by bainternet** [comment]
Not sure I understand your question,

> Why does elementor need jquery?

Elementor needs jQuery because Elementor uses jQuery, so if you are on a page built with Elementor, Elementor will load jQuery.

**Comment by helvetica123** [comment]
so why page doesnt show normally when i remove bootstrap jquery? i dont want to add more jquery if it is unnecessary.
