### ISSUE TITLE
Custom styles for new widget not working in editor mode

### ISSUE THREAD

**Issue by uxdesignit** [elementor/elementor#8504]
Hi,
We create new addon for Elementor with some new widgets. I met issue with custom style [css] for some new widget, it work for frontend / preview mode, but not work in editor mode.
When we create new widget, we use this:

```
 public function get_style_depends() {                
        return [ 'widget-style' ];
    }
```

And it work well for Preview / Frontend, but it is not work in Editor mode
So how to use custom style for some widget ?
Please advice!

Thanks in Advances
Harry Le

**Comment by bainternet** [comment]
@uxdesignit 	

You need to manually enqueue the style for the editor because the render in the editor runs either by js which can enqueue for you are via ajax which only returns the HTML (no `wp_head` or `wp_footer' calls to actually run the enqueue).

so something like this:

```PHP
add_action( 'elementor/preview/enqueue_styles', function() {
	wp_enqueue_style( 'widget-style' );
} );
```

thanks.

**Comment by CreativForm** [comment]
> @uxdesignit
> 
> You need to manually enqueue the style for the editor because the render in the editor runs either by js which can enqueue for you are via ajax which only returns the HTML (no `wp_head` or `wp_footer' calls to actually run the enqueue).
> 
> so something like this:
> 
> ```
> add_action( 'elementor/preview/enqueue_styles', function() {
> 	wp_enqueue_style( 'widget-style' );
> } );
> ```
> 
> thanks.

Hey, I try this code and not working.

I have a registered styles for the custom widgets built inside my theme. I add your code where I enqueue styles and it not working.

I try to wrap this action also inside init action, after_setup_theme action plugins_loaded action and not working.

I working inside functions.php

Any advice?
