### ISSUE TITLE
Bug After v2.6.0 Update: Cart Icon Missing

### ISSUE THREAD

**Issue by TomRaraAvis** [elementor/elementor#8507]
Bug After v2.6.0 Update: Cart Icon Missing
Screenshot:
![cart-gone](https://user-images.githubusercontent.com/1435355/60905469-2512ac00-a243-11e9-8750-98104677d9cf.PNG)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Make sure you have the latest version of Elementor Pro.
