### ISSUE TITLE
Bug After v2.6.0 Update: Entrance animations don't work

### ISSUE THREAD

**Issue by yaniv691** [elementor/elementor#8508]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
All widgets with entrance animations just "show up", with out any sliding, fading, etc.

## Steps to reproduce

Just open the page. 
For example: http://grth.s611.upress.link/

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.10
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.3.5
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Operation timed out after 5001 milliseconds with 0 out of -1 bytes received)

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://grth.s611.upress.link
	Home URL: http://grth.s611.upress.link
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.1.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.11
		Author: Elementor.com

	Envato Elements
		Version: 1.1.1
		Author: Envato

	WeSafe by uPress
		Version: 1.7.2
		Author: uPress

	Yoast SEO
		Version: 11.6
		Author: Team Yoast


== Log ==
	: 
JS: showing 1 of 1JS: 2019-07-09 07:20:24 [error X 1][http://grth.s611.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:8507] Cannot read property \'select2\' of undefined 

Log: showing 5 of 52019-07-09 16:40:37 [info] elementor::elementor_updater Started 
2019-07-09 16:40:37 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-09 16:40:37 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-09 16:40:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.0',
)]
2019-07-09 16:40:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.0',
)]

```
</details>

**Comment by yaniv691** [comment]
I actually found the issue and fixed it. It's this change to version 2.6:
Tweak: Reduce-motion accessibility support for CSS animation library (#7968)

I disabled animations on my Windows 10 machine for better performance. Turns out this also sets a browser setting called 'prefers-reduced-motion' to 'reduce' which actually removes all animations if the developer addressed that setting in the CSS, which Elementor did on version 2.6. I enabled animations in the Windows 10 settings and the Elementor entrance animations came back. :-)

**Comment by Grafs** [comment]
I also have problems with animation.
Disabled all the animation after upgrading to version 2.6.1
I tried on the default theme Twenty Nineteen with all the plugins disabled, the animation in the new version 2.6.1 of the plugin does not work.

**Comment by yaniv691** [comment]
@Grafs did you try enabling animations in the Windows settings?

**Comment by Grafs** [comment]
@yaniv691 In version 2.5.16, everything worked, but after the update version 2.6.1 it did not.

**Comment by yaniv691** [comment]
@Grafs In 2.6, Elementor added support for accessibility CSS that is based on Windows (or other OS) animation settings.  Check if animations are disabled in your **Windows** settings, and enable them to see the animations on your Elementor site.

**Comment by Grafs** [comment]
@yaniv691 Yes, turned on.
Why such an implementation?
Site settings should not depend on the operating system. If I do not want to use animation in Windows, this does not mean that I do not want to see the animation on the site!
**Please make the setting so that the connection with Windows can be turned off.**

**Comment by ohanafilms** [comment]
I am confused because my entrance animations no longer work and I'm on a Mac. I

**Comment by derrickmg** [comment]
I have had to rollback to previous elementor, until this issue is fixed please can you fix quickly as I need to keep plugins updated.

**Comment by ohanafilms** [comment]
I don't believe it is going to be fixed because they see it is as "compatibility with the "reduce motion" setting has been introduced for accessibility purposes". So now what? My site looks like garbage now.

**Comment by derrickmg** [comment]
Well they just trashed their own product then,because that is a major
functionality  drawcard for elementor and it doesnt work.
Good luck to them,I hope more people complain. Windows settings are for
windows, browser settings are for browsers,don't get them mixed up.

**Comment by FilipSkalak** [comment]
This is kind "it is not a bug but a feature" argument. Animations were tasty and pleasant cream on the top of the web cake, now they are gone. I hope there will be some extra plugin to bring it back. Come on Elementor Team, bring it back!

**Comment by HansK76** [comment]
Totally agree here. Why would you trash your own product.This should at least be an optional feature to turn on, not by default!!

**Comment by FilipSkalak** [comment]
I wonder is there a way to make some change in php to fix this, until Elementor will be able to make one button which makes this feature optional?

**Comment by HansK76** [comment]
Well I have made the necessary changes in the elementor .css files, and now it works. That is until the next update.

**Comment by FilipSkalak** [comment]
Dear Hans, I may miss something, but what changes did you make in css?

**Comment by erfan-ilyas** [comment]
Not working for me as well.

**Comment by Gapeeq** [comment]
Not working for me either. are they planning to fix that or what?

**Comment by erfan-ilyas** [comment]
For me it was my windows issue.

To fix this I have unchecked "Turn off all unnecessary animations (when possible)
 
![image](https://user-images.githubusercontent.com/1281946/67633779-10cbeb00-f8d6-11e9-8b2d-614878f4aa8f.png)


I suggest the Elementor developers to give a notification that they have detected the "Reduce-motion accessibility" and animations will not work.

Here is the issue that explains it:

https://github.com/elementor/elementor/pull/7968

**Comment by drawcard** [comment]
Hi, I wrote the original PR and I think there's some misunderstanding here of what it's supposed to do.

The 'reduce motion' system setting is designed to be coupled with to the browser window, this is a decision of the browser manufacturers who respect @prefers-reduced-motion declarations: https://developers.google.com/web/updates/2019/03/prefers-reduced-motion

The PR is not designed to trash or break your site. It should have no effect on the vast majority of your visitors (who have system setting off by default.) 

It is however intended to provide greater accessibility and control to certain visitors of your site, who might not want their medical condition triggered by animations within the browser window (which is the point of the media query). 

Hope that helps explain the purpose of the PR and why it might be a bad idea to reverse it.

**Comment by drawcard** [comment]
Might also be worth noting that Chrome now lets you simulate what @prefers-reduced-motion does to your website if it's enabled: https://developers.google.com/web/updates/2019/10/devtools#userpreferences

So that is handy if you wanted to test your site quickly, to see how it falls back when animations are disabled.

**Comment by numanzahid** [comment]
Please +1 https://github.com/elementor/elementor/issues/9726

**Comment by numanzahid** [comment]
@HansK76 
Hans,
can you please let us know what css changes did you make. I am trying to get help from elementor team, even asked pro support. but they have decided not to help in anyway.

I have solved the problem using this css

**Comment by RonR-WebDesign** [comment]
Hans, thanks.  That fixed it for me.  I'm shocked that this is still an issue.  But.... I removed this CSS because I found:

I'm on Win 10 and I did a bit more digging.  I found that I had animations turned off in Ease of Use Settings.  Turned it back on and now they work.

Settings > Ease of Use > Display > Simplify and personalize Windows > Show animations in Windows > ON

**Comment by Haf1988** [comment]
I am a novice, I have a Mac, please can someone assist, my front page animation has stopped working using Elementor and I have a Wordpress's site.  What is the quickest way round it, I am on the new version of Elementor.

**Comment by drawcard** [comment]
@Haf1988 you probably have 'reduce motion' enabled on your Mac:

https://support.apple.com/en-au/guide/mac-help/mchlc03f57a1/mac

Turn the feature off and you'll see animations working again on your website.

**Comment by Haf1988** [comment]
@drawcard I did try, but it did not work.  

Thanks for you help .

**Comment by juliomorri** [comment]
Hi friends, I found the solution for most of the cases.

Go to Edit Plugins, Elementor, CSS, frontend.min.css and then find this:

” @media (prefers-reduced-motion:reduce){.animated{-webkit-animation:none;animation:none}} ”

And then just delete that line, cause that is for “users who experience motion sickness / vertigo”

So from nowon in every single browser your entrance animations will work.

Because I saw people giving the solution to change the settings in Accesibility from Windows in reactivating the “desactivate all the unnecessary animations (when it’s possible)”, and that solution will ONLY work for your computer and no for the rest.

Thanks!

You can visit my website juliomorri.com

**Comment by drawcard** [comment]
@adnanalbeda wrote:
> This feature is designed for like 5% of people, so I'm not ready to sacrifice some cool entrance animation for them.

[50 million people](https://www.who.int/news-room/fact-sheets/detail/epilepsy) worldwide have epilepsy, that's not counting other non-epileptic conditions like PNES. Given the wide reach of Wordpress and Elementor, many are bound to be using our websites. The feature is there to respect the decisions of the user, who have a preference set in their OS system settings to reduce the risk of triggering a seizure while using their computer.

On top of that, [many countries](https://www.w3.org/WAI/policies/) have legislation requiring websites to be as accessible as possible. So removing that capability from Elementor is a step backward for compliance and would make many government websites invalid. 

Having a checkbox to turn it off is a fine suggestion, if you really don't care for it, but it should be switched on by default.

**Comment by Phomar** [comment]
It's not "Your" Windows settings. Do you think other users opening your site will go and change their settings? I don't think so... So all of my posts, for example, have an intro image fly in animation, and now none of those images shows up, it's not just animation canceled, the image is not there...
