### ISSUE TITLE
Gutenberg Block

### ISSUE THREAD

**Issue by asadkn** [elementor/elementor#8509]
If you have been an active user of WordPress, you'd have realized by now most of the developers have accepted and shifted focus to the new Gutenberg editor. New plugins commonly go about creating blocks now, what would previously be a shortcode.

This is a problem for **all** pagebuilders as the whole larger ecosystem of WP community is becoming inaccessible. 

Previously, we commonly used shortcodes in Elementor. Now that it's changing and developers are increasingly creating Gutenberg blocks instead of shortcodes, you really need to include a "Gutenberg Block" (or just "WordPress Editor"?)

I noticed you made some progress towards it but discarded it? https://github.com/elementor/elementor/pull/5729

Other pagebuilders like Visual Composer already have a gutenberg block. This is a serious limitation in Elementor now.

**Comment by bainternet** [comment]
@asadkn 	

We already released it as a standalone plugin a few months ago [https://wordpress.org/plugins/block-builder/ ](https://wordpress.org/plugins/block-builder/ )

thanks.

**Comment by asadkn** [comment]
That's the opposite of what I explained here. Please check again. 

Using your plugin, users can insert an Elementor "template" from Elementor to Gutenberg, but it's not really visual. And in most common scenarios, when building a whole page with Elementor, users want to insert a Gutenberg block in middle of the page (not above or below the page template). Ex: building a homepage, you want to use a recipe block from Gutenberg in middle of page, not above or below the homepage. 

This is the right way to do it: https://visualcomposer.com/blog/visual-composer-block-for-gutenberg/

**Comment by jillro** [comment]
I don't understand neither why it is closed. I also need this feature ! I have my front page created with Elementor, and I need to integrate just one block from the [AMP plugin](https://wordpress.org/plugins/amp/).
