### ISSUE TITLE
[BUG] Elementor 2.6 - Icon Library empty

### ISSUE THREAD

**Issue by fedeoasis** [elementor/elementor#8513]
Hi,
after the update to release 2.6 of Elementor Pro, the new icon library is empty and I cannot edit previous icon widgets.
No cache system is active, I'm working in staging environment.

Could you help me pls?

Thanks so much!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We can't really help without these.

Thanks.

**Comment by fedeoasis** [comment]
I try to respond:

Steps to replicate
Starting from an existing WP site with the previous release of Elementor Pro, I have update to last 2.6 release.
I have also update the icon library to latest Fontawesome 5, as requested by Elementor.

Isolating the problem
After the update, when i try to insert in page a new icon, i cannot choose it because the new icon library is empty. I see the menu of the library ("Font Awesome Regular", "Font Awesome Solid", "Font Awesome Brand"), but on the right is empty, no icons shown
The same, when I try to edit a previous icon widget.

System INFO
WP 5.2.2 (latest release)
Elementor Pro 2.6 (latest release)
Generatepress 2.3.2 (latest release)

**Comment by fedeoasis** [comment]
Hi,

I have update Elementor to release 2.6.1 and Elementor Pro to release 2.5.12 but the issue of the empty icon library is still here.

**Comment by NTuneMusic** [comment]
I am having the same issue, only my entire Icon Library popup is completely empty of everything.

![Icon Library](https://user-images.githubusercontent.com/35422914/61994055-9aec8500-b043-11e9-8ddd-77dac3812a18.jpg)

**Comment by stapolin** [comment]
I'm having the same issue as NTuneMusic..  

Trying to get a site finished for a client, but this is really causing issues in delivering the site on time.

![screenshot-motor stapolin ie-2019 08 12-14_25_42](https://user-images.githubusercontent.com/17647985/62868250-1a00df00-bd0d-11e9-931f-6b2a4c7d5e58.jpg)

**Comment by duck-toy** [comment]
I have the excact same problem please help

**Comment by mitothebee** [comment]
the same problem :/

**Comment by jharajnish30** [comment]
The way I troubleshooted the issue for me suggests that the ICONS were loading already.

It was rather petty CSS issue which prevented it from displaying..

Follow the steps given below.. 
close any open editor page... 
Modify the CSS as given (don't forget to backup the original file).. > save > close CSS. 
And done... 

Steps:
1. find "/wp-content/plugins/elementor/assets/css/editor.min.css" file
2. search following elements
3. and modify the ORIGINAL value with the ONE GIVEN below
4. DONE.. the icons will load as normal...

.elementor-icons-manager__tab__item{height:81px;width:101px;}
.elementor-icons-manager__tab__item__icon{font-size:40px;color:#000;}
.elementor-icons-manager__tab__item__name{color:#000;font-size:11px;padding:0;}
#elementor-icons-manager__main{padding: 5px 5px 0;}
