### ISSUE TITLE
Feature request: View SVGs in Media Library view

### ISSUE THREAD

**Issue by besweeet** [elementor/elementor#8516]
Currently, all of my SVGs display as placeholders (https://i.imgur.com/AKoPJIZ.png). https://wordpress.org/plugins/wp-svg-images/ doesn't do anything different. Is it possible for Elementor to bake something into it?

**Comment by drawcard** [comment]
That's to do with Wordpress Media Library, it doesn't want to render the SVG for security reasons. That plugin you mention should render them though, you may need to do thumbnail regeneration. 

Also take a look at https://gist.github.com/benfrain/9422862 for a functions.php solution.

**Comment by arielk** [comment]
Starting with version 2.6 of Elementor this should work, so please update and you get it.

**Comment by besweeet** [comment]
@arielk I noticed SVG previews do work, but only on newly-uploaded files. Existing SVGs will display the placeholder preview. Is this expected behavior?

**Comment by drawcard** [comment]
Have you tried running a thumbnail generator? https://en-au.wordpress.org/plugins/regenerate-thumbnails/

**Comment by besweeet** [comment]
@drawcard I tried that plugin, but it says "ERROR: Unable to load the metadata for this attachment." for SVGs :/.
