### ISSUE TITLE
Elementor 2.6 Navigator Position and CSS are Hidden

### ISSUE THREAD

**Issue by RonR-WebDesign** [elementor/elementor#8531]
Oh... I so wanted to designate this as a bug.   Why oh why would you make the Position and CSS indicators hidden?   Why???  And that blue vertical bar so small and the same color as when hovering.  

I found elementor function to fix this:
```
add_action('elementor/editor/before_enqueue_scripts', function() {
	wp_enqueue_style('load-Child-stylesheet', get_template_directory_uri() . '/elementor-style.css', array(), null);
});
```
With this in the style file:
```
.elementor-navigator__element__indicators:not(:hover) {
    transform: none !important;
}
```
Works great now!

**Comment by shilo-ey** [comment]
Hi @RonR-WebDesign 
Thanks for your feedback.

The way we implemented CSS navigator indicator allows us to extend this feature in the future and not to create an overload on the UI.

Thanks.
