### ISSUE TITLE
[BUG] Elementor 2.6 - Empty Icon Library

### ISSUE THREAD

**Issue by fedeoasis** [elementor/elementor#8532]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
After the update to release 2.6.1 of Elementor, the new icon library is empty.
I also cannot edit previous icon widgets.

## Steps to reproduce
Starts from an existing WP site with the previous release of Elementor and Elementor Pro. Update to latest 2.6.1 release.
Update the icon library functionality to latest Fontawesome 5, as requested by Elementor.
Try to insert an Icon Widget: the Icon library is empty, only show the left menu ("Font Awesome Regular", "Font Awesome Solid", "Font Awesome Brand")

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
<details>

**Server Environment**
Operating System: WINNT
Software: Microsoft-IIS/8.5
MySQL version: MySQL Community Server (GPL) v5.5.42
PHP Version: 7.2.2
PHP Max Input Vars: 1000
PHP Max Post Size: 58M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

**WordPress Environment**
Version: 5.2.2

**Theme**
Name: GeneratePress Child
Version: 0.1
Child Theme: Yes
Parent Theme Name: GeneratePress
Parent Theme Version: 2.3.2

</details>

**Comment by sanna-work** [comment]
I have the same problem on a couple different sites

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by sanna-work** [comment]
Problem solved, json was blocked, so i had to allow it in the .htacess file

**Comment by enventa** [comment]
> 
> 
> Problem solved, json was blocked, so i had to allow it in the .htacess file

@sanna-work could you please explain how you fixed this issue? What do you mean by "json was blocked"?

Thanks!!

**Comment by sanna-work** [comment]
I’m not 100% sure how it works, I got help from some server guys. But I wrote this code in the .htacess file in the WP-content folder http://imgur.com/twSfCGw

**Comment by mhdomidifard** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/53738665/62690897-d2174a80-b9e2-11e9-86fa-402dfde019c4.png)

**Comment by mirquezdrm** [comment]
I have the same problem.

I modified the .htaccess like said @sanna-work, but is doesn't work.

also reinstall the elementor pro and nothing happened.

**Comment by duck-toy** [comment]
i have the same problem please help

**Comment by pacotole** [comment]
Same problem here:

```javascript
Uncaught TypeError: Cannot read property 'name' of undefined
    at t.getActiveTabIcons (editor.min.js:7)
    at editor.min.js:7
    at Array.forEach (<anonymous>)
    at t.getAllIcons (editor.min.js:7)
    at t.getActiveTabIcons (editor.min.js:7)
    at t.getActiveTabIcons (editor.min.js:7)
    at t.render (editor.min.js:7)
    at Mr (editor.min.js:23)
    at Er (editor.min.js:23)
    at Vr (editor.min.js:23)
```

**Comment by mitothebee** [comment]
the same problem :/

**Comment by pacotole** [comment]
In [wordpres.org support forum](https://wordpress.org/support/topic/problem-after-elementor-plugin-update-2-6-with-icons/#post-11781090) I found a solution that worked for me:

> From your WP Dashboard go to -Elementor – Custom Icons. Open the trash folder and if there are any icons there, select and permanently delete them all. Refresh the page that had that problem and try again.

**Comment by mitothebee** [comment]
> In [wordpres.org support forum](https://wordpress.org/support/topic/problem-after-elementor-plugin-update-2-6-with-icons/#post-11781090) I found a solution that worked for me:
> 
> > From your WP Dashboard go to -Elementor – Custom Icons. Open the trash folder and if there are any icons there, select and permanently delete them all. Refresh the page that had that problem and try again.

thx, that worked :)

**Comment by lanzalf** [comment]
I had the same problem.  Although I didn't have any custom icons, if you add one and remove it, it fixed the issue for me.

**Comment by wedodigital** [comment]
> I had the same problem. Although I didn't have any custom icons, if you add one and remove it, it fixed the issue for me.
Same with me, thank you.

Developer should look into this one..

**Comment by techitint** [comment]
Hi Everyone, I've solved my problem in two different ways.

1st. Almost desperate to finish the job, I have created the block with desired icons on external website, exported as a template and imported the template in the "icon-non-working" website.
The block imported as template worked fine showing the icons correctly.

2nd. I made a zip of a small bunch of icons on _Fontello_ and imported in "custom icons" in Elementor. When I went to check for the upload custom icons, magically all the other icons appeared in the empty white icon panel.

**Comment by princ-imran** [comment]
Elementor Version 2.7.3 Icon library now what can i do? 
Theme Name: RealHomes
Many way to try but not solve.

**Comment by LRA1** [comment]
+1

**Comment by clickharder** [comment]
Same problem.  Used the 2nd solution of @techitint and it solved the problem.  Other support suggestions have said to delete the custom icon set after creating it.  I tried that and then the Icon library disappeared again.  Using Elementor 2.7.4 and Elementor Pro 2.7.2

**Comment by redantsolutions** [comment]
Pacotole solution worked for me: 

From your WP Dashboard go to -Elementor – Custom Icons -> add an icon -> press enter to save -> delete new icon -> refresh Elementor page.

**Comment by mulik91** [comment]
I Solved it buy just adding a new font in wp dash -> elementor -> icons -> add new
just write some gibrish on the title hit enter, and ten delete it in trash.
vualla

**Comment by umairakram500** [comment]
> Pacotole solution worked for me:
> 
> From your WP Dashboard go to -Elementor – Custom Icons -> add an icon -> press enter to save -> delete new icon -> refresh Elementor page.

works for me

**Comment by jharajnish30** [comment]
The way I troubleshooted the issue for me suggests that the ICONS were loading already.

It was rather petty CSS issue which prevented it from displaying..

Follow the steps given below.. 
close any open editor page... 
Modify the CSS as given (don't forget to backup the original file).. > save > close CSS. 
And done... 

Steps:
1. find "/wp-content/plugins/elementor/assets/css/editor.min.css" file
2. search following elements
3. and modify the ORIGINAL value with the ONE GIVEN below
4. DONE.. the icons will load as normal...

.elementor-icons-manager__tab__item{height:81px;width:101px;}
.elementor-icons-manager__tab__item__icon{font-size:40px;color:#000;}
.elementor-icons-manager__tab__item__name{color:#000;font-size:11px;padding:0;}
#elementor-icons-manager__main{padding: 5px 5px 0;}

**Comment by valiceadm** [comment]
This issue is closed but I also had this issue and just want to know that it's resolved. As of the most recent release, this was still an issue and then the trick for adding a custom icon worked but has the actual underlying problem been fixed?

**Comment by Zjadlbymcos** [comment]
Same issue with Elementor 2.9.4 and Pro 2.8.4

**pacotole** solution works for me too

**Comment by rishiichaudharyy** [comment]
Problem Solved.
Make sure you give font name in Fontello in nav bar.

**Comment by jujudellago** [comment]
Problem seems to still exist in 2021, customer support is nowhere to be found

**Comment by TipoSamuel** [comment]
This issue is closed and even 3 years later Elementor still has the same problem.

![image](https://user-images.githubusercontent.com/107733998/183820172-9e315477-45f2-45e9-b458-4986623b08a7.png)

**Comment by MichaelDev96** [comment]
I have the same problem, for me it looks like something in nginx.. I use wordpress in forge..

**Comment by Luke-SF** [comment]
Same thing, not on Nginx and it recurs even after adding a custom font icon.

**Comment by stackhouse0** [comment]
![Screenshot 2023-08-17 183139](https://github.com/elementor/elementor/assets/93806856/da7de135-9f4a-4613-bd27-b5046a623fde)
i'm having similar issue now and i can seem to fix it with everything i've seen

**Comment by TheRealFreelancer** [comment]
I have the same issue with Elementor 3.16.6 and Elementor Pro 3.16.2. 

Why is this still an issue? 

And why is this closed then?

**Comment by VGAisdead** [comment]
Same issue..

**Comment by dsbaykut** [comment]
same issue as of today
