### ISSUE TITLE
Slides widget navigation icons are misplaced

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#8533]
The slides next/previous navigation icons are not aligned correctly.
Refer - https://cl.ly/a02db377dde7

**Comment by black-eye** [comment]
@ShaMSofT Is it the same problem like described here: #8527 ?

**Comment by manektechmayank** [comment]
I have same issue please some help.
I just drag & drop the slides widget and got following.

![image](https://user-images.githubusercontent.com/31854318/61941341-e7d54a80-afb4-11e9-956c-b48297b29998.png)

![image](https://user-images.githubusercontent.com/31854318/61941355-ec016800-afb4-11e9-93c6-7f0be0d2659d.png)

**Comment by philrp** [comment]
The thread mentioned above (#8527) claims it was fixed in 2.7, but I'm on 2.7.1 and the issue remains.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!
