### ISSUE TITLE
How can I get the icon HTML in a variable?

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#8536]
I am using Icons_Manager::render_icon() function to display the icon HTML in my custom widget.
But, is there any way to get the icon HTML and save it in a string. 
I want to return the icon HTML through a function.

Also, how can I pass the custom classes to the icon?

**Comment by drawcard** [comment]
If you can extract the particular icon as a variable from within the class, you could try implode() to convert the variable to a string. You might have to construct the HTML around the output though, using echo or return.

**Comment by sushmak02** [comment]
Yes, you are right @drawcard!
We can get the icon class name and add custom HTML for this.
But, in case if the SVG is selected, then it will result in an incorrect HTML. So, I was looking for if there is any way to get the HTML in a variable.

**Comment by drawcard** [comment]
What's the output of the variable at the moment, when you try to access it? or does it return null?

**Comment by sushmak02** [comment]
This is the code I have written - 
```
function test_icons( $settings ) {
$output = Icons_Manager::render_icon( $settings['new_icon'], [ 'aria-hidden' => 'true' ] );
return $output;
```
}

It prints the icon in the when execution comes to the function.

**Comment by drawcard** [comment]
The workaround in this thread may help: https://github.com/elementor/elementor/issues/8520

**Comment by sushmak02** [comment]
Thank you @drawcard. 
This is the same I was looking for.
