### ISSUE TITLE
Template menu on the backend

### ISSUE THREAD

**Issue by Web-Granny** [elementor/elementor#8541]
Done

## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro.)

**What problem is your feature request going to solve? Please describe.**

The backend menu that contains the templates and theme builder is frustrating. I want to see all of the template categories with one click. The only way to see them all now is to click on templates or theme builder and then click the ALL option. I should not need to do this in the paid version. I need to be able to access sections and widgets when working in any template, not just pages and posts.

I’m surprised that you haven’t figured out that you are missing a marketing opportunity with this configuration. A one click access to all templates, both paid and pro, would show all of the options available to users of the free version. They could be grayed out with a PRO label, but visible to the users of the free version and tempt them to go Pro.

**Describe the solution you'd like**

On the backend menu change the Folder as follows:

Elementor Templates (Branding is currently missing) - brings up all possible template categories with pro categories marked as Pro and grayed out if using the free version
   Add New

Get Rid of the rest of the choices because they are all incorporated in the two options. Sometimes simpler is better.

**Describe alternatives you've considered**

I've used the Admin Menu to rename the menu items as Free templates and Pro templates. Not a real solution, but it saves me from stopping to think that I am looking for the pro templates under the confusing name of Theme Builder. Yes they are templates that build a theme, but the language is confusing even to native English users.

**Additional context**

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
