### ISSUE TITLE
Is there any way to add affiliate code on Elementor links in the backend?

### ISSUE THREAD

**Issue by pulla** [elementor/elementor#8547]
We have affiliate code from Elementor.

We are doing our best to assist Elementor sales for win & win.
But many of our clients who use our theme, click "pro" link on yours. ( because you have added the link a lot of places ) :)
It's a little bit sad. We strongly recommend Pro version. But they use your link from your plugin in our theme.
Is there any way to add our affiliate code to your links in our theme?
Any hooks for affiliates? 

Thank you for a great plugin.

**Comment by shilo-ey** [comment]
Hi @pulla 

Since Elementor v2.6 only `Administrator` role can see the notices (promotion, license expired, renew license etc...)

Other than that, you can learn more about [our affiliates program here](https://elementor.com/affiliates/).

Thanks!

**Comment by vrabota** [comment]
Hello @shilo-ey, 

I create premium WordPress themes and a lot of users go and buy premium Elementor license from Admin Dashboard after they installed my theme. I will be happy to have a filter and change "Buy Elementor Pro" with my affiliate id. The same approach I discovered for Beaver Builder.

```
function my_bb_upgrade_link() { return 'YOUR_LINK_HERE'; }

add_filter( 'fl_builder_upgrade_url', 'my_bb_upgrade_link' );
```
In that case, we will have a win-win, we will generate for you new customers and Elementor will pay us a bonus for that.

Thank you!
