### ISSUE TITLE
Flex align everything in a container.

### ISSUE THREAD

**Issue by Flipback8** [elementor/elementor#8548]
If flexbox is a feature that was added why can't you just align everything in a column with one click? It would be nice to be able to use the flexbox property to align everything one shot vs having to select each element one by one.

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

Thanks.
