### ISSUE TITLE
Widget icon

### ISSUE THREAD

**Issue by DmitriyDSWEB** [elementor/elementor#8549]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
After updating the widget icon, the default icon is a star, can you do it by default without an icon?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DmitriyDSWEB** [comment]
After updating the widget icon, the default icon is a star, can you do it by default without an icon?

**Comment by shilo-ey** [comment]
This icon was the default icon before the update. 

If you add a new widget - this is the default icon, and can be easily changed using the Icon Library.

Thanks

**Comment by DmitriyDSWEB** [comment]
after the last update, all widgets, their 400+, again returned the default icon, it was previously disabled and now it is not possible to delete it

**Comment by DmitriyDSWEB** [comment]
Why close if the problem is not solved?

**Comment by DmitriyDSWEB** [comment]
> This icon was the default icon before the update.
> 
> If you add a new widget - this is the default icon, and can be easily changed using the Icon Library.
> 
> Thanks

Why close if the problem is not solved?

**Comment by DmitriyDSWEB** [comment]
<img class="aligncenter size-full wp-image-2749" src="https://staging.meowkai.com/wp-content/uploads/2019/07/widgeicon1.png" alt="" width="467" height="531" />

**Comment by shilo-ey** [comment]
Please explain your issue again. the regular behavior is when you drag a widget which incorporates an icon - the default icon is star icon. what am I missing in your report?

Please create a new issue and follow the guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

Thanks.

**Comment by DmitriyDSWEB** [comment]
> Please explain your issue again. the regular behavior is when you drag a widget which incorporates an icon - the default icon is star icon. what am I missing in your report?
> 
> Please create a new issue and follow the guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
> This report is missing key information:
> 
> * Prerequisites.
> * **Steps to replicate.**
> * **Isolating the problem.**
> * **System info.**
> * One issue per thread
> 
> Without it we simply can't help.
> 
> Thanks.

I have created a lot of widgets icon, after the update, the default icon appeared again but I can not delete it
