### ISSUE TITLE
Add horizontal spacer widget - Elementor pro

### ISSUE THREAD

**Issue by lucafagherazzi** [elementor/elementor#8550]
- [x] I have searched for similar features requests in both open and closed tickets: #4745.
- [x] The feature is still missing in the latest stable version of Elementor (Elementor Pro).

**What problem is your feature request going to solve? Please describe.**
When, for example, I add 2 widgets inline, there is no possibility to space them at will.

**Describe the solution you'd like**
It would be useful to be able to space out at will as in the icon list widget.

**Describe alternatives you've considered**
I use the icon list widget but it is not customizable like, for example, the buttons.

**Additional context**
first list icons widget
second buttons widget

<img width="360" alt="Schermata 2019-07-12 alle 12 22 05" src="https://user-images.githubusercontent.com/40598133/61121573-d4e45580-a49f-11e9-9d99-23fb66165f45.png">

**Comment by fxaviers** [comment]
Horizontal space between 2 widgets in line, you can add padding, or use the horizontal alignment of the column.

**Comment by arielk** [comment]
As @fxaviers wrote you can do it in many options, you can learn more here: 
https://elementor.com/blog/introducing-flexible-layout/

Thanks
