### ISSUE TITLE
add text to image

### ISSUE THREAD

**Issue by jevgenijaleksandrov** [elementor/elementor#8552]
make it possible to add text to the image inserted as image widget i.e. to write on/over the image in image widget, like here https://www.befunky.com/features/text-editor/

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for the actual request,  you can set the image as the background of the Section or column and add a Text widget or whatever you want on top of it.

thanks.
