### ISSUE TITLE
Bug with HTML widgets redirection script

### ISSUE THREAD

**Issue by asafmazon** [elementor/elementor#8553]
Hello, I've installed Elementor Pro on my local server and I used redirect script on HTML widget.

When I'm doing that Elementor gives an error.
I'm still able to edit the page as regular but I have to bypass the system.

I used this script for redirection:
<style>body {display: none;</style>
<script>window.location.replace("/login");</script>

So every time I edit a page with this script I have to bypass the system in order to be able to edit it.

Please fix.

https://www.loom.com/share/226003ca56094edbb3a5dbb6ad7ad82e

**Comment by asafmazon** [comment]
There us a way to stop redirections on the preview? if it causes it to broke I suggest adding an option to enable/disable this option or to do something about it

**Comment by Aviad-Herman** [comment]
Hi,
Thanks for the feedback.
Currently we will not fix this issue, it's too unique of a usecase.
I'm closing this old issue.
