### ISSUE TITLE
custom icon font broken with new icon library

### ISSUE THREAD

**Issue by epoplive** [elementor/elementor#8554]
Previously I was loading my own custom css font icon set into elementor via a hook during 'elementor/controls/controls_registered' like this:

```php
public function icons_filters( $controls_registry ) {
        $icons = $controls_registry->get_control( 'icon' )->get_settings( 'options' );
        
        $css_source = file_get_contents( MFH::PLUGIN_DIR . '/css/mfh-icons.css' );
        preg_match_all( "/\.(icon-mfh-.*?):\w*?\s*?{/", $css_source, $matches, PREG_SET_ORDER, 0 );
        foreach ( $matches as $match ) {
            $new_icons[$match[1] ] = str_replace('icon-', '', $match[1]);
        }

        if ( !empty($new_icons) && is_array( $new_icons ) ) {
            $icons = array_merge($new_icons, $icons);
        }
        // send back new array
        $controls_registry->get_control( 'icon' )->set_settings( 'options', $icons );
    }
```

this seems to no longer work, as my icons don't appear in the icon library anymore.  I need information on how to add my icons into the library as this has completely broken how we used elementor.

**Comment by epoplive** [comment]
ok so I think I've figured it out, this may help someone else so I'm posting my solution.  First I had to add a filter:

`add_filter( 'elementor/icons_manager/additional_tabs', function(){
                return [
                    'mfh' => [
                        'name' => 'mfh',
                        'label' => __( 'ManufacturedHomes', 'elementor' ),
                        'url' => \Initialization\FileLoader::$pluginURL . 'css/mfh-icons.css',
                        'enqueue' => [ \Initialization\FileLoader::$pluginURL . 'css/mfh-icons.css' ],
                        'prefix' => 'icon-mfh-',
                        'displayPrefix' => 'mfh',
                        'labelIcon' => 'mfh',
                        'ver' => '5.9.0',
                        'fetchJson' => \Initialization\FileLoader::$pluginURL . 'css/mfh-icons-json.php',
                        'native' => true,
                    ]
                ];
            }
        );`

this basically needs urls to your css file with your icon font, and a url of a json file containing the names for your icons.  '\Initialization\FileLoader::$pluginURL' is just a helper I have in my code that gives back the url to my plugin directory.  Instead of using a static list of the icon names, i created a script that parses the css file and generates the json.  Here's what that file is:
`<?php
include_once '../src/MFH.php';
$css_source = file_get_contents(\MFH::PLUGIN_DIR . '/css/mfh-icons.css' );
preg_match_all( "/\.(icon-mfh-.*?):\w*?\s*?{/", $css_source, $matches, PREG_SET_ORDER, 0 );
$iconList = [];
foreach ( $matches as $match ) {
    $new_icons[$match[1] ] = str_replace('icon-', '', $match[1]);
    $iconList[] = str_replace('icon-mfh-', '', $match[1]);
}

$icons = new stdClass();
$icons->icons = $iconList;
echo json_encode($icons);
`

One thing you should notice is that the json file shouldn't have the prefix from the add_filter stuff.

**Comment by DeoThemes** [comment]
@epoplive Thanks for the example mate, however I can't understand how the second part works. Are you loading this php file in your main Elementor custom plugin file and when it's hooked? And how it's exactly generating the json? If you provide full gist it would be very helpful :)

**Comment by bainternet** [comment]
Closing as no real issue here,

please feel free to continue the conversion.
