### ISSUE TITLE
Cannot Add Button - Stuck in Font Awesome Notification Loop

### ISSUE THREAD

**Issue by bbubbs** [elementor/elementor#8558]
I cannot add a button. I have used Elementor in the past and am used to the drag-and-drop button creation. But now when I drop in a new button, I am notified of Font Awesome 5 upgrade and cannot add a button. I do not want Font Awesome 5. Help!

**Comment by bainternet** [comment]
@bbubbs 	

Elementor 2.6.0 works with and requires Font Awesome 5.
If you don't want Font Awesome 5 use previous versions of Elementor.

thanks.
