### ISSUE TITLE
Add new transitions to slider widget

### ISSUE THREAD

**Issue by passievlassie** [elementor/elementor#8559]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
More options in the slider widget like more transitions, an overlay option

**Describe the solution you'd like**
Add more variation of transitions like this example. And don't forget to push de slidearrows ;)
https://revolution.themepunch.com/filmstrip-add-on-slider/
It is great isn't?

For overlay put a shortcode to a section so that we can setup some text

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
