### ISSUE TITLE
Widget toggle

### ISSUE THREAD

**Issue by DmitriyDSWEB** [elementor/elementor#8560]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
The active icon is empty, I have a lot of these widgets, now I need to fix everything, can't I immediately add it as it was configured? Do you test your widgets a bit before releasing a new version?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@DmitriyDSWEB 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by DmitriyDSWEB** [comment]
> @DmitriyDSWEB
> 
> Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.
> 
> thanks.

send
