### ISSUE TITLE
Image gallery: Control the number of images displayed

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#8562]
In the gallery widget, I would like to display not all selected images. I would like to select a limited number of images randomly. Could you add that control to the widget?

**Comment by bainternet** [comment]
Our Gallery Widget uses the WordPress native `[gallery]` shortcode which doesn't support a number of images, only a fixed set of images.

but since its a naive WP shortcode you can use hooks to alter the output, ex:

```PHP
// randomize gallery shortcode output
add_filter( 'shortcode_atts_gallery', function( $out, $pairs, $atts, $shortcode ) {
	// get attachment ids
	$ids = explode( ',', $atts['ids'] );

	// Randomize the $ids
	shuffle( $ids );

	// Cut the number of attachments you want
	// in this example i set it to 3
	$ids = array_slice( $ids, 0, 3 );

	// return this to shortcode
	$out['include'] = implode( ',', $ids );
	return $out;
}, 10, 4 );
```

**Comment by HelmutGoebel** [comment]
There is a more easy way to do it with CSS.
Given, you want to display 8 images, the css-snippet is like:

.gallery-item:nth-child(n+9) {
	display: none; 
}

And that can't be incorporated in the controls???
