### ISSUE TITLE
how to manually change the pages on previous & next on Post Navigation Widget?

### ISSUE THREAD

**Issue by nikmors** [elementor/elementor#8563]
Hi,
I was looking through the display options i was given by the Post Navigation Widget, but i couldn't find the one i was looking for. I was wondering if it is possible to manually change the Previous page and the Next page (ex: by adding a url, shortcode) displaying on the widget. Could it be a future feature?
For what i noticed so far, if i am right, the previous & next page are a reflection of which page you created in Wordpress as last, presenting the next page, or before the last one, as a previous one. You need to do a lot of deleting and creating on posts or pages section to get this order right the way you want them to appear (specially when you have a portfolio displaying lots of projects as pages).
Please consider this feature, thanks.

**Comment by bainternet** [comment]
@nikmors 	

Post Navigation Widget uses the WordPress Native `previous_post_link` and `next_post_link` native functions. Meaning, you can use the native filter hooks to 
`next_post_link` and `previous_post_link` to alter the output of these functions.

thanks.
