### ISSUE TITLE
Post Content Widget with display options

### ISSUE THREAD

**Issue by GH-RPDN** [elementor/elementor#8566]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This feature request will give more customized control over the Post Content.
Currently, when you use the Post Content widget it displays all post content (obvious) as one ie text/images etc altogether.
But this feature would allow the user the option to select what to display from the post content and then style accordingly.
This will give the user much more creative freedom.

**Describe the solution you'd like**
Options to select what to display from the Post Content.
In a multi-column layout the user can use the Post Content Widget multiple times - each time displaying something different from the post content.

**Describe alternatives you've considered**
I've tried using the Text Editor widget to dynamically display the text from the Post Content (no option for this).
The dynamic Excerpt or Custom Fields do not allow formatting (without basic html knowledge).
Creating a ACF Custom Field (text area) also does not allow formatting (without basic html knowledge).

**Additional context**
Alternative solution would be applying a Post Content dynamic option to the Text Widget and then selecting the appropriate Key.
And then doing this similarly for other Widgets throughout.

**Comment by GH-RPDN** [comment]
Hello.
In the interim I have managed a workaround using E-Pro & ACF-Pro.
I uploaded all images to the post using the Gallery Block from within Wordpress.
In the template,
1. Using the Image Gallery widget I dynamically pulled the Post Image Attachments
2. I did NOT upload a Feature Image, but rather created a Custom Image Field with ACF-Pro
3. I then also created a WYSIWYG Custom Field with ACF-Pro
4. Both of the ACF fields were created on condition of Post
5. Custom Image Field became my Feature Image by dynamically pulling this through the Image Widget
6. WYSIWYG Custom Field became my Text Post Content
Thanks

**Comment by shilo-ey** [comment]
Hi @GH-RPDN 

If I understand you correctly, you can do so with our Theme Builder > Single Template, and using the Single template elements. Read [more here](https://docs.elementor.com/article/354-creating-a-single-post-template)

In addition, you can use as you mentioned the ACF dynamic tags.

Thanks!
