### ISSUE TITLE
Dynamic button on widgets

### ISSUE THREAD

**Issue by asafmazon** [elementor/elementor#8569]
Hello, I've noticed a few of your Elementor PRO widgets doesn't contain a dynamic button, Please add it :) As I'm using ACF I can't use dynamic content on specific widgets.

Widgets I've noticed missing the dynamic button:
- Toggle
- Testimonials Carousel
- Facebook Button
- Animated headline

Thanks in advance!

<img width="301" alt="Dynamic button" src="https://user-images.githubusercontent.com/52833071/61187339-fea4a480-a678-11e9-9828-ef507565cfd6.png">
<img width="301" alt="Animated Headline" src="https://user-images.githubusercontent.com/52833071/61187343-05331c00-a679-11e9-875a-255d5d225f46.png">
<img width="302" alt="Facebook Button" src="https://user-images.githubusercontent.com/52833071/61187344-05cbb280-a679-11e9-8aad-80a93412421a.png">
<img width="302" alt="Testimonials Carousel" src="https://user-images.githubusercontent.com/52833071/61187345-05cbb280-a679-11e9-878c-de59aa868842.png">
<img width="297" alt="Toggle" src="https://user-images.githubusercontent.com/52833071/61187346-05cbb280-a679-11e9-803b-726f8f080be1.png">

**Comment by DorShahar** [comment]
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!
