### ISSUE TITLE
Dynamic Progress Bar connected to ACF

### ISSUE THREAD

**Issue by jcmatoskx** [elementor/elementor#8575]
I need to have a progress bar (the same one) on different parts of the website that has to be updated/changed daily. To do this on several parts manually is very time consuming, so it would be awesome if the ACF dynamic field could be applied to the progress bar progress, so that I could just update the progress value of all the bars in the backend

**Comment by bainternet** [comment]
@jcmatoskx 

Currently, we don't have support for dynamic in number control, once its implemented we should have no problems to add this.

I merged this issue with  #5952, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
