### ISSUE TITLE
Preview could not be loaded: We failed to recognize your Server software. Please contact your hosting provider.

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#8578]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
While editing the Elementor page, I am getting this error - "We failed to recognize your Server software. Please contact your hosting provider."
Refer - https://cl.ly/c3f6e6986032

I am facing this issue after Elementor 2.6 update. 

I checked the Elementor system configuration of my website, and I can see that the Server Software field is empty here - https://i.imgur.com/Ma9wO7Y.png

My website is hosted with Pagely, so I contacted their support regarding this issue.

This is what they say - 
It would be a security risk to have that information available and should not be required by a PHP script. With that said, it could be manually defined.

How can I fix this error, is there any hook from which I can set the custom server software variable like this?
```
<?php
$_SERVER['SERVER_SOFTWARE'] = 'custom-software';
return $_SERVER['SERVER_SOFTWARE'];
?>
```

**Comment by bainternet** [comment]
@sushmak02 

This is just a symptom and won't fix your issue, we use that to better identify the issue, which in your case we can't.

Try heading to Settings >> Permalinks >> save your permalinks, and see if that helps.

If not, Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
