### ISSUE TITLE
WooCommerce Menu Cart Icon is Broken on New Update

### ISSUE THREAD

**Issue by Spark3000** [elementor/elementor#8584]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Spark3000** [comment]
![Screenshot 2019-07-16 at 15 15 36](https://user-images.githubusercontent.com/4939629/61274027-7390ef00-a7dd-11e9-893b-ba857db7317f.png)

**Comment by shilo-ey** [comment]
Hi @Spark3000 

Please make sure you update to the latest version of Elementor Pro (v2.5.13) and you don't have cache stored.

Thanks.

**Comment by Jozku** [comment]
I have the same issue.

Used theme - Astra
Browsers tested: Chrome (PC & Android), Edge

**Comment by Spark3000** [comment]
Works. Sorry I thought I had updated Pro already.
