### ISSUE TITLE
Add pattern property for input to text fields for elementor pro forms

### ISSUE THREAD

**Issue by parkbroom** [elementor/elementor#8587]
Seems that we cannot add our own custom regex pattern in elementor form fields.

I see a lot of use cases like Zip Code, SKU, country code or some unique pattern that doesn't exist in the field type.

For reference: http://html5pattern.com

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, You can simply add it yourself using the provided hooks, ex:

```PHP
class Elementor_Forms_Patterns_Validation {

	public $allowed_fields = [
		'text',
		'email',
		'url',
		'password',
	];

	public function __construct() {
		// Add pattern attribute to form field render
		add_filter( 'elementor_pro/forms/render/item', [ $this, 'maybe_add_pattern' ], 10, 3 );

		add_action( 'elementor/element/form/section_form_fields/before_section_end', [ $this, 'add_pattern_field_control' ], 100, 2 );
	}

	/**
	 * add_pattern_field_control
	 * @param $element
	 * @param $args
	 */
	public function add_pattern_field_control( $element, $args ) {
		$elementor = \Elementor\Plugin::instance();
		$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'form_fields' );

		if ( is_wp_error( $control_data ) ) {
			return;
		}
		// create a new pattern control as a repeater field
		$tmp = new Elementor\Repeater();
		$tmp->add_control(
			'field_patten',
			[
				'label' => 'Pattern',
				'inner_tab' => 'form_fields_advanced_tab',
				'tab' => 'content',
				'tabs_wrapper' => 'form_fields_tabs',
				'type' => 'text',
				'conditions' => [
					'terms' => [
						[
							'name' => 'field_type',
							'operator' => 'in',
							'value' => $this->allowed_fields,
						],
					],
				],
			]
		);

		$pattern_field = $tmp->get_controls();
		$pattern_field = $pattern_field['field_patten'];

		// insert new pattern field in advanced tab before field ID control
		$new_order = [];
		foreach ( $control_data['fields'] as $field_key => $field ) {
			if ( 'custom_id' === $field['name'] ) {
				$new_order['field_patten'] = $pattern_field;
			}
			$new_order[ $field_key ] = $field;
		}
		$control_data['fields'] = $new_order;

		$element->update_control( 'form_fields', $control_data );
	}

	public function maybe_add_pattern( $field, $field_index, $form_widget ) {
		if ( ! empty( $field['field_patten'] ) && in_array( $field['field_type'], $this->allowed_fields ) ) {

			$form_widget->add_render_attribute( 'input' . $field_index,
				[
					// Add pattern attribute
					'pattern' => $field['field_patten'],
					// Add pattern to validation message
					'oninvalid' => 'this.setCustomValidity( "Please match the requested format \"' . $field['field_patten'] . '\" ")',
					// Clear validation message when needed
					'oninput' => 'this.setCustomValidity("")',
				]
			);
		}
		return $field;
	}
}
new Elementor_Forms_Patterns_Validation();
```

This will add the control in the panel 
![IDPxrlA](https://user-images.githubusercontent.com/660572/61879057-e9dad300-aefa-11e9-9209-4673d302d326.png)

And the validation + custom message that shows the pattern requested:
![image](https://user-images.githubusercontent.com/660572/61879073-f95a1c00-aefa-11e9-9977-20e663d7c59f.png)

Thanks for the feedback.

**Comment by dbjpanda** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

+1

**Comment by lupetalo** [comment]
@bainternet How does one actually use this snippet? pasting in functions does not do anything...

**Comment by lupetalo** [comment]
Oh here it is without using class:
`add_filter( 'elementor_pro/forms/render/item', 'maybe_add_pattern', 10, 3 );
add_action( 'elementor/element/form/section_form_fields/before_section_end','add_pattern_field_control', 100, 2 );

	function add_pattern_field_control( $element, $args ) {
		$allowed_fields = [
		'text',
		'email',
		'url',
		'password',
	];
		$elementor = \Elementor\Plugin::instance();
		$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'form_fields' );

		if ( is_wp_error( $control_data ) ) {
			return;
		}
		// create a new pattern control as a repeater field
		$tmp = new Elementor\Repeater();
		$tmp->add_control(
			'field_patten',
			[
				'label' => 'Pattern',
				'inner_tab' => 'form_fields_advanced_tab',
				'tab' => 'content',
				'tabs_wrapper' => 'form_fields_tabs',
				'type' => 'text',
				'conditions' => [
					'terms' => [
						[
							'name' => 'field_type',
							'operator' => 'in',
							'value' => $allowed_fields,
						],
					],
				],
			]
		);

		$pattern_field = $tmp->get_controls();
		$pattern_field = $pattern_field['field_patten'];

		// insert new pattern field in advanced tab before field ID control
		$new_order = [];
		foreach ( $control_data['fields'] as $field_key => $field ) {
			if ( 'custom_id' === $field['name'] ) {
				$new_order['field_patten'] = $pattern_field;
			}
			$new_order[ $field_key ] = $field;
		}
		$control_data['fields'] = $new_order;

		$element->update_control( 'form_fields', $control_data );
	}

	function maybe_add_pattern( $field, $field_index, $form_widget ) {
		if ( ! empty( $field['field_patten'] ) && in_array( $field['field_type'], $this->allowed_fields ) ) {

			$form_widget->add_render_attribute( 'input' . $field_index,
				[
					// Add pattern attribute
					'pattern' => $field['field_patten'],
					// Add pattern to validation message
					'oninvalid' => 'this.setCustomValidity( "Please match the requested format \"' . $field['field_patten'] . '\" ")',
					// Clear validation message when needed
					'oninput' => 'this.setCustomValidity("")',
				]
			);
		}
		return $field;
	}`

**Comment by crisland** [comment]
hi, please where do i put this code, i´ve tryed on
elementor-pro/modules/forms/widgets/form.php
and
elementor-pro/modules/forms/module.php 

and is not working there

**Comment by felipeealvess** [comment]
@crisland 
elementor-pro.php

✌️

**Comment by poukill** [comment]
I'm also looking for regex validation. 
In the meantime, I just tested your "hack" and it works fine ! :)
Only question I have is : what about Elementor PRO updates ? Will it overwrite elementor-pro.php and I will have to copy/paste the code everytime ?

**Comment by AmjadSaeeddev** [comment]
> I'm also looking for regex validation.
> In the meantime, I just tested your "hack" and it works fine ! :)
> Only question I have is : what about Elementor PRO updates ? Will it overwrite elementor-pro.php and I will have to copy/paste the code everytime ?

Yes of course everything will be overside but there is one solution for it and the solution is that create a child theme then make changes in child theme and your changes will be saved

**Comment by ArnabAssiduus** [comment]
I am also try to use patthen in number filed, can you help me where and how can I use this code.

**Comment by pingram3541** [comment]
FYI, the code above causes a fatal.  However it's an easy fix:

Change line: `$tmp = new Elementor\Repeater();
`
To: `$tmp = new Repeater();`

I've created a gist (tested and working) that can be included in a custom plugin or your theme's functions.php - https://gist.github.com/pingram3541/37d1d274893fcc40a1e96c5e368c0b99

**Comment by ElchananLevavi** [comment]
@bainternet I created a tiny plugin based on your code that available here: https://github.com/ElchananLevavi/form-fields-pattern 
I still have one big issue:
While I'm adding attributes to a simple field (e.g Text field) everything works fine
But if a field already has specific attribute (Like pattern or oninvalid. e.g. Tel field that contains default pattern attribute) the new value adds to the current value instead of override it.

Can you offer me an idea to solve the problem?
Thanks!
Elchanan

**Comment by mihaiEDW** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

There is indeed a demand for it 😄 . It would be great to have this feature.

**Comment by JMauclair** [comment]
Any news on this feature ? Any ETA ?
