### ISSUE TITLE
Duplicate "Not Supported" templates created on upgrade from 2.5.16 to 2.6.2; causing affected templates to throw "the_content missing" error

### ISSUE THREAD

**Issue by evandonovan** [elementor/elementor#8588]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

When we upgraded last week from Elementor 2.5.16 to 2.6.1, we saw that there were "Not Supported" templates showing. We also were no longer able to edit some of the templates on our site (mainly Section templates) that had corresponding "Not Supported" templates.

It may be that these "not supported" templates were other drafts of templates, and Elementor was getting confused about which one to use.

We had previously enabled Toolset for custom content types, but switched to the CPT UI plugin. We had to do some work in the database to migrate the Toolset content, so it is possible that created some kind of conflict with the ID field on posts.

**Do you know if there are circumstances that would cause "Not Supported" templates to be created?**

Note that our theme is Astra, and the single.php template does include the_content. I also followed other recommendations for fixing "the_content" issue, such as clearing permalinks. This was the only thing that fixed it.

Other plugins enabled that may be relevant are:

* Astra Pro
* Content Views Pro
* CPT UI
* Duplicate Post
* Envato Elements
* Post Type Switcher
* Ultimate Addons for Elementor

We had a few other plugins enabled, but they are things like Yoast, which I don't think would affect this.

## Steps to reproduce

1. Have Elementor, Elementor Pro, and Ultimate Addons for Elementor (1.13.1) enabled.
2. Upgrade from Elementor 2.5.15 to 2.6.1.
3. There may be "Not Supported" templates that are duplicates of other templates, but with a lower ID. (But as I said above, not sure where these had come from in the DB.)
4. Any templates for which there are corresponding "Not Supported" templates may not be editable due to the "the_content area is missing" error.
5. After the "Not Supported" templates are deleted, the templates that have the same name as them will be editable again, and will not give the "the_content area is missing" error.

## Environment

<details>
<summary>System Info</summary>
```
See https://pastebin.com/60w4dt5E

Details taken from /wp-admin/admin.php?page=elementor-system-info

```
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
