### ISSUE TITLE
Custom Global Settings

### ISSUE THREAD

**Issue by sabuz** [elementor/elementor#8590]
I would like to know if there is any way to create custom global settings. I injected a section in global settings using `elementor/element/global-settings/style/after_section_end` hook and here is the preview http://tinyurl.com/y2wejcfr. But saving the page has no effects.

Can you please clarify:

- How to add custom global settings
- How to get the settings value

**Comment by bainternet** [comment]
@sabuz 	

Currently, there is no easy way to get the data to save without hacking around a little, meaning there is no API for it in place yet.

thanks.

**Comment by crazypsycho** [comment]
@bainternet 
There would be a easy way to implement this feature.
We need just one hook in
/elementor/core/settings/general/model.php
on get_controls_list() where we can manipulate the settings-array.

**Comment by webbudesign** [comment]
Here is the example to add control into Global Settings;
`add_action( 'elementor/element/global-settings/style/before_section_start',  [ $this, 'global_page_settings'],10, 2);//Also you can use after_section_end
public function global_page_settings($element, $args) {
		$element->start_controls_section(
			'topline_settings2',
			[
				'label' => esc_html__( 'Top Line Settings', 'pointfindercoreelements' ),
				'tab' => \Elementor\Controls_Manager::TAB_SETTINGS,
			]
		);
		$element->end_controls_section();
	}
`

**Comment by crazypsycho** [comment]
This will add a control, but the control can´t be saved.

**Comment by webbudesign** [comment]
> This will add a control, but the control can´t be saved.

Yes, you are right.
