### ISSUE TITLE
Hello Elementor Theme Option or Elementor plugin Theme Option

### ISSUE THREAD

**Issue by kizume** [elementor/elementor#8592]
Hello Team,

We all love Hello Elementor.
It would be so lovely to have an option like a Theme Option?
Where there is an option to choose what page to display in mobile devices?

To find out more about what I was trying to show, please check the Theme Option of this wonderful WP Theme: https://themeforest.net/item/revo-multipurpose-responsive-woocommerce-theme/18276186

https://snag.gy/yxNlAX.jpg

There are other Elementor Themes that are asking for paid version nowadays. But it brings a lot of conflict to the Elementor itself. Maybe that is why Elementor developed their own WP Theme, the Hello Elementor.

Please guys, help me have a a theme option for it. It is really most appreciated. I am also willing to support the developer. Just kindly do let me know. Thank you!

**Comment by bainternet** [comment]
@kizume 

Elementor Is a responsive page builder, so I don't see an option like that being implemented anytime soon.

Also, feature requests for Hello Theme should be placed in its own [repo](https://github.com/elementor/hello-theme) as its not related to Elementor Development.

thanks.
