### ISSUE TITLE
Popup link doesn't work with woocommerce hook

### ISSUE THREAD

**Issue by Bookyourroom** [elementor/elementor#8595]
Hey,
I used a woocommerce hook to insert a checkbox with a text before the add to cart button. The label of the checkbox contains a an anchor tag that is linked to a popup which I created. The problem is that the link doesn't open the popup. I tried the exact same link with an ordinary button and it worked but for some reason the link in the hook doesn't. 

I created a video to illustrate the issue:
https://www.loom.com/share/6b2de5a2d10d48afa335a4aac6e528b3

As can be seen the normal button works really well and
opens the popup seamlessly (even though there isn't much of a popup to
show as I wanted to test it before I design it). When it comes to the
link added with the hook, something strange happens. Instead of opening
the popup, the link just gets added to the url and nothing happens.

This is the hook I used (for reference):

```
add_action( 'woocommerce_before_add_to_cart_button', 'bbloomer_add_checkout_privacy_policy', 9 );

function bbloomer_add_checkout_privacy_policy() {

woocommerce_form_field( 'privacy_policy', array(
'type' => 'checkbox',
'class' => array('form-row privacy'),
'label_class' => array('woocommerce-form__label woocommerce-form__label-for-checkbox checkbox'),
'input_class' => array('woocommerce-form__input woocommerce-form__input-checkbox input-checkbox'),
'required' => true,
'label' => 'I\'ve read and accept the <a href="#elementor-action%3Aaction%3Dpopup%3Aopen%20settings%3DeyJpZCI6IjEzNDUiLCJ0b2dnbGUiOnRydWV9">Privacy Policy</a>',
));

}
```

Is there any way this issue can be fixed?

Thanks in advance :)

**Comment by bainternet** [comment]
@Bookyourroom 

This will not work, it's blocked as a security measurement. What you can do is give your link a class and set your popup to "Open By Selector"

![XOsXIMF](https://user-images.githubusercontent.com/660572/61874537-56e96b00-aef1-11e9-9cdc-5886a184798a.png)

**Comment by Bookyourroom** [comment]
> 
> 
> @Bookyourroom
> 
> This will not work, it's blocked as a security measurement. What you can do is give your link a class and set your popup to "Open By Selector"

Thanks for the reply. I tried it by adding the class to the link and setting the open by selector to the same class but it still didn't work.

Is there anything else I could do in order to make this work?
Thanks
