### ISSUE TITLE
After 2.6 update Star icon appears where Icon Box is used

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#8596]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

On my site, I have used the Iconbox widget. The icon is unset.

With Elementor version 2.5.16 - https://cl.ly/f489a48a2d41

After the Elementor 2.6.2 update, the star icon is added to all the icon boxes on my website.
Refer this screenshot - https://cl.ly/08ad2293c00b

This is changed on all my websites. How can I fix this?

## Steps to reproduce
- Add an Icon box on your page with Elementor 2.5.16 version.
- Remove the icon from Select icon selection - https://cl.ly/f489a48a2d41
- Upgrade to Elementor latest version.
- Check the IconBox on your page.
- The default Star icon appears in the Icon Box.

**Comment by ahemads** [comment]
I also have the same issue.

**Comment by sushmak02** [comment]
@bainternet Any update on this issue? Are you planning to fix it?

**Comment by shilo-ey** [comment]
Thanks for reporting. this issue will be addressed soon in the stable version.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.6

Feel free to update

Thanks!

**Comment by sushmak02** [comment]
Hey @shilo-ey,

The above issue seems to be fixed only at the backend editor of Elementor. 

In the above case, with your fix, the Star icon does not display in the output and fixes the issue.

But, when I try to set a new icon it does not display at the frontend. It appears correctly in the backend.

I tried to debug your code and seems like the **$migrated** variable always returns false in the **render()** even if the icon is changed.
 $migrated = isset( $settings['__fa4_migrated']['selected_icon'] );

Can you please look into this and fix this ASAP?

**Comment by sushmak02** [comment]
Here is a screencast of the same - https://cl.ly/6bf906b09845
