### ISSUE TITLE
New Icons Compatibility to custom widgets

### ISSUE THREAD

**Issue by sushmak02** [elementor/elementor#8597]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

We have added icon compatibility to our custom widget as per this doc - https://developers.elementor.com/new-control-icons/

The icons control is working fine except the issue with the empty icon control - 

I have registered icons like this - 

```$this->add_control(
		'icon',
		[
			'label' => __( 'Icon', 'text-domain' ),
			'type' => Controls_Manager::ICONS,
			'default' => [
				'value' => 'fas fa-star',
				'library' => 'solid',
			],
		]
	);
```

If the icon is unset by a user and we add compatibility to the control it takes the "fas fa-star" as a default icon.

The default icon appears everywhere even if the icon is unset. How you have managed this condition in Elementor?

How can I fix this issue? Is there anything else we need to add in our code?

Also, I can see you have added "function on_import()" in your widgets. Why is this used?

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@sushmak02 	

This really depends on the use case, so without seeing your whole code, I can't really tell but if you look at our native Widgets you can see how we managed to deal with many cases.
