### ISSUE TITLE
 fatal error -  בעיית התנגשות עם תוסף הרחבה שפותח עבור אלמנטור 

### ISSUE THREAD

**Issue by dkag** [elementor/elementor#8604]
יש לי תוסף שפותח כהרחבה לתוסף אלמנטור פרו. התוסף מבצע התממשקות בין האתר למערכת zebracrm ומאפשר לשלוח נתונים מטפסים הבנויים על בסיס אלמנטור אל zebracrm. בעת הפיתוח גרסת אלמנטור הייתה 2.2.4 והכל היה תקין. לאחרונה עדכנתי את הגרסה ל-2.5.12 וצצ בעיה של fatal error.

בבדיקתינו גילינו שבקוד האלמנטור התווספה שורה 51 בקובץ module.php אותה ניתן לראות בתצלום מסך http://prntscr.com/ofd4k8 ובעקבות זה בנסיון כניסה לעריכת עמוד באלמנטור מקבלים fatal error. יש התנגשות כלשהיא בין שורה זו לתוסף ההרחבה. במידה ומבטלים את השורה אז הכל עובד תקין.

מה היא שורה זו? האם יש דרך לבטל אותה מבחוץ במלי להתערב בקוד של תוסף האלמנטור? האם יש לכם רעיונות לפתרון של הבעיה?

**Comment by arielk** [comment]
Hi

Please contact the developer of your add-on to solve the problem or please
