### ISSUE TITLE
Form Input deleted when closing popup (without any warning)

### ISSUE THREAD

**Issue by OffCorner** [elementor/elementor#8605]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

So I have a form inside a popup (a pretty standard thing to do); however, when someone enters text in the form (it's a bit longer than usual) and then closes the popup, there is no warning that the text will be lost. This could lead to a loss in sales (since this is a popup that is being used for contacting the owner). This is especially dangerous when closing on overlay is enabled.
Is there even a way to listen when a popup is being closed and prevent it, in case there is still text inside the form?

## Steps to reproduce

Create a popup, add a form. Enter text and close the popup. The text will be gone without any warning when you reopen the popup.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Hi @OffCorner 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.
