### ISSUE TITLE
New PHP hook before parsed CSS property added into Stylesheet object

### ISSUE THREAD

**Issue by MjHead** [elementor/elementor#8607]
Could you please consider an opportunity to add new PHP hook into **elementor/core/files/css/base.php**, into method add_control_rules exactly before parsed CSS added into current Stylesheet instance (line `$this->stylesheet_obj->add_rules( $parsed_selector, $output_css_property, $query );`). Something like:

```php
do_action(
	'elementor/css-file/' . $this->get_name() . '/parse-control-property',
	$this,
	array(
		'output_css_property' => $output_css_property,
		'parsed_selector'     => $parsed_selector,
		'query'               => $query,
	),
	array(
		'control'        => $control,
		'controls_stack' => $controls_stack,
	)
);

$this->stylesheet_obj->add_rules( $parsed_selector, $output_css_property, $query );
```

Such hook allows to add any custom CSS depends on current control settings and current controls stack. For example we can create cross-browser CSS rules for Grid-layouts based on columns/rows settings set in stack, dynamically add hover (active) styles by make current color lighten or darken, automatically calculate any other CSS properties based on value from given control. Also this hook could be usable for adding any dynamically calculated global styles based on default Schemes.

As 3rd-party developer (or maybe you some day will need such functionality in Elementor Pro :) ) I can add function on this hook, inside this function I can get any values from current control or any other controls in current stack, get all date required to create correct selector for current instance, get current Stylesheet object and add new rules into this object.

**Why so much arguments**
To create correct selector and add it to current rules set we need current File instance to get Stylesheet object and replacements array. Also we could need information about current control and current controls stack to make required calculations.

**Alternative solutions**
At ttis moment I've found only way to do something like this only for posts by using hooks `elementor/element/before_parse_css` or `elementor/element/parse_css` form **elementor/core/files/css/post.php**. But on this hooks we need to manually call all function stack between these hooks and adding CSS rules into stylesheet object.

And last point - this is action, not filter, so styles couldn't be broken from 3rd party, only could be added new rules. Also this solution, if no function added on it, is not created any additional weight while page processing.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
