### ISSUE TITLE
Elementor Theme Builder / WPML Conflict

### ISSUE THREAD

**Issue by thepranxter** [elementor/elementor#8612]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am using Elementor Pro Theme Builder and WPML (including Translation, CMS and String Translations) (latest versions). The main language of the page is English, some of the pages are also available as translations in Dutch. I am running Hello Theme and both header and footer are created through theme builder (see the live website here: ecochain.com)

I also use the Popup builder frequently. So far I have only used it on the English pages. I encountered this reproducible bug while trying to create a Dutch only Popup.

When creating a popup in the secondary language, everything goes wrong:
- Firstly, the popup does not get displayed in the backend. Instead, the blank interface "Create a popup" indicates that no popup exists yet. However, I can find the popup when I switch back to English (main language)
- The theme functionality of the theme builder completely falls apart. The header does not get displayed on any page anymore (falls back to Hello theme header). I tried to deactivate it and activate it again, delete cache,... the only thing that works is editing every page manually again. It seems like the page templates don't get pulled anymore as the pages go completely unstyled  in terms of templating and header. Footer still works, weirdly enough.
- Deactivating the popup or deleting it doesnt help, page stays broken after
- I also added manual translations of all theme builder elements, didnt help.
-> Essentially, it's not possible to create a popup in the secondary language without breaking the theme builder.

I do not know if this is an Elementor or WPML issue, but for obvious reasons I cannot deactivate either to test it individually...

## Steps to reproduce

1. Create a secondary language in WPML
2. Create header on entire site in Elementor Theme Builder
3. Create page templates for entire site (or posts, post types...)
4. Switch to secondary language
5. Create popup in secondary language, publish and make sure to set conditional to certain pages

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | nginx/1.17.1 |  
MySQL version: | mariadb.org binary distribution v5.7.26 |  
PHP Version: | 7.1.30-1+ubuntu16.04.1+deb.sury.org+1 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 2000M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

WordPress Environment |   |  
-- | -- | --
Version: | 5.2.2 |  
Site URL: | https://ecochain.com |  
Home URL: | https://ecochain.com |  
WP Multisite: | No |  
Max Upload Size: | 2 GB |  
Memory limit: | 512M |  
Permalink Structure: | /%category%/%postname%/ |  
Language: | en-US |  
Timezone: | 0 |  
Admin Email: | xxx |  
Debug Mode: | Active

Theme |   |  
-- | -- | --
Name: | Hello Elementor |  
Version: | 1.2.0 |  
Author: | Elementor Team |  
Child Theme: | No

User |   |  
-- | -- | --
Role: | administrator |  
WP Profile lang: | en_US |  
User Agent: | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

</details>

**Comment by bainternet** [comment]
@thepranxter 	

This is mainly a WMPL issue since we do not alter the query based on the "Current language" nor are we actually aweare of the "Current language".

As for theme functionality, As far as we know everything works fine as long as you follow WMPL's guide https://wpml.org/documentation/plugins-compatibility/elementor/#translate-elementor-templates

thanks.

**Comment by gerardreches** [comment]
I'm experiencing the same thing, my header built with the Theme Builder disappears when WPML String Translation is activated.

@thepranxter could you please explain me your workaround to fix the header? 🙏
