### ISSUE TITLE
Vertical Margin on Popup position doesn't work

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#8614]
When I try to position a popup with margin it works on left/right, but not on top/bottom, no matter which basic positioning (top/bottom and left/right) I'm using.

**Comment by DorShahar** [comment]
Thanks for reporting, and sorry for the delay with the response. 

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without it, we simply can't help.

Thanks.
