### ISSUE TITLE
Popup trigger settings Input Element to small

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#8616]
The input element for popup trigger settings "After Inactivity" is to small to show more than one digit. The width should be wider.
![image](https://user-images.githubusercontent.com/14095280/61536278-936e2000-aa34-11e9-9fc4-bcf995b96c0c.png)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.2

Feel free to update

Thanks!
