### ISSUE TITLE
Video-widget - make start time and end time Dynamic

### ISSUE THREAD

**Issue by sommarzan** [elementor/elementor#8617]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am fetching videos dynamically (am using PODS). The video url gets fetched correctly, but on almost every video I want to set start time and end time. That is not possible.

**Describe the solution you'd like**
Add "Dynamic" to the start time field and end time field

**Additional context**
Cheers!
![elementor-video-widget](https://user-images.githubusercontent.com/48725261/61538913-9ff57700-aa3a-11e9-8fae-8e929e7e08ec.png)

**Comment by bainternet** [comment]
I merged this issue with  #5952, which is on the same subject so we could deal with it more efficiently, and this actually depends on it.
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by eisber** [comment]
I followed the link to the closed issue, but since Start Time and End Time is not a dynamic content field, it doesn't seem to be supported. Is there another way? @bainternet ?
