### ISSUE TITLE
{FEATURE REQUEST] Dynamic Post-URLS with UTM Parameter

### ISSUE THREAD

**Issue by TeamowBee** [elementor/elementor#8619]
It would be great if the dynamic field "Post-Url" can become a dynamic UTM-Parameter to make Posts / Pages more dynamic depending on where the user came from (like Archive-Pages).

f.e.: User is in Taxonomy "Events New York" -> clicks an event in this taxonomy -> will see the event-name + "in [NEW YORK].

any chance to have that?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can add your own custom dynamic tags: https://developers.elementor.com/dynamic-tags/

Thanks for the feedback.
