### ISSUE TITLE
Statistics for social buttons

### ISSUE THREAD

**Issue by rodrigocarlos** [elementor/elementor#8620]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Elementor social sharing buttons, we have no idea how many people are sharing a particular page where the buttons are inserted.

**Describe the solution you'd like**
So you could insert statistics of those shared social buttons that we insert into the pages created with the Elementor.
And these statistics could be separated by buttons, that is, every time we create a group of sharing buttons (Facebook, Twitter, Instagram, ...) we can write a name for this statistic, and when we create another group of buttons for insert another page, we can write another name of statistics. So we will have statistics separated by groups of buttons to identify which statistics belong to certain button

The same case for normal social networking buttons (the buttons where we enter the profiles of our social networks). We have no statistics on how many people are clicking on these buttons and going to our social networking pages.
Then you could also provide statistics for these buttons.

I leave here these suggestions for improvement.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
