### ISSUE TITLE
[Feature Req] Hide responsive elements in Editor 

### ISSUE THREAD

**Issue by mskks64** [elementor/elementor#8623]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

It'd be nice if we elements did not display if they are hidden for the different views in the editor. (I.E. Element should be hidden in desktop view. If I'm currently editing Desktop view, please hide.) 

Sometimes it's necessary to have duplicate elements due to how they will fit on the page or need to rearrange a section for media queries. Unfortunately this looks bad inside the editor making the editor view look clunky. It can also make it difficult to find the right element/section. 

I think a media query(active/inactive) display option near the preview button would work nicely.

**Comment by fxaviers** [comment]
You can hide any element, column or section with the navigator. This helps keep the editor "cleaner".
![image](https://user-images.githubusercontent.com/17536232/61566593-1605d800-aa53-11e9-9696-55036df034bc.png)

**Comment by shilo-ey** [comment]
Hi @mskks64 

As @fxaviers you can now hide all elements (including columns) via the Navigator.
In addition, you can set responsive conditions to your widgets and preview them by collapsing the panel (or by clicking `CTRL/CMD + P`)

Thanks
