### ISSUE TITLE
Please add RocketResponder

### ISSUE THREAD

**Issue by stefan57** [elementor/elementor#8627]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

RocketResponder.com is much cheaper to use than the other services included and it is also great. Their cost is $20/month for unlimited contacts and emails, compared to the services included in Elementor that charge many times more.

Info about their API is found here:
https://www.rocketresponder.com/devzone

**Describe the solution you'd like**
Not needed

**Describe alternatives you've considered**
Not needed

**Additional context**
https://www.rocketresponder.com

**Comment by shilo-ey** [comment]
Hi @stefan57 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

For now, you can add your own custom action [using our documentation](https://developers.elementor.com/forms-api/custom-form-action/).

Thanks!
