### ISSUE TITLE
Two Pop Overs are active at a time.

### ISSUE THREAD

**Issue by AbmSourav** [elementor/elementor#8630]
## Description
On Advanced tab > Motion Effects, if I click "Horizontal Scroll" and then click "Vertical Scroll". The Vertical Scroll pop over goes behind the Horizontal Scroll. 

## One pop over tab should open at a time.
![popover](https://user-images.githubusercontent.com/39233955/61588833-9d725900-abc3-11e9-94c3-c7bc0349a681.png)

## Environment

<details>
<summary>System Info</summary>
Local Server.
</details>

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/3183 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
