### ISSUE TITLE
add a client-side variable to the form's after-submit webhook action

### ISSUE THREAD

**Issue by dangub** [elementor/elementor#8635]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I need a way to pass a Google Analytics clientID (this is generated on a client-side) to the after-submit webhook action.

I _think_ the right approach here is to add a hidden field, and then somehow to populate this hidden field with a client-side variable.

**Use case** 
Completion of a form is a step in the user conversion funnel. I need the Google Analytics clientId to continue to send events to GA from my service against this original Analytics session.

**Describe the solution you'd like**
Add a new "client-side dynamic tag" that can run arbitrary javascript code.

**Describe alternatives you've considered**
Assign a form-id to the form (available in Additional Options), then add the HTML element with <script> that finds the form and populates the value.

This solution is brittle (change in form ID breaks it) and hard to maintain

**Additional context**
N/A

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can catch the submit event and rub any code you want, ex:
```JS
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	jQuery( document ).on('submit_success', function(){
		// form has been submitted do your tracking here...
	});
});
```

Thanks for the feedback.

**Comment by dangub** [comment]
@bainternet Is there an event that I could hook into _before_ the form is submitted. I need to pass the clientId with the form as a hidden field.
