### ISSUE TITLE
Newest Google Fonts

### ISSUE THREAD

**Issue by DeoThemes** [elementor/elementor#8637]
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We designed a new page using Google font [DM Sans](https://fonts.google.com/specimen/DM+Sans), but I've noticed there is no such font in Elementor, so we can't complete the project.

**Describe the solution you'd like**
Update Google fonts list in the next release.

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can add it for yourself using simple code: #4624

Thanks for the feedback.
