### ISSUE TITLE
Google Fonts query string

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#8643]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It could be better showing Google Fonts query string something like `ver=1563746264` instead of WordPress version.

![google-fonts-query-string](https://user-images.githubusercontent.com/7617350/61597857-a429bc00-ac15-11e9-9c1d-4bafd3802d07.png)

- Is better to not reveal WordPress version to hackers
- Better browser caching

**Comment by shilo-ey** [comment]
Hi @shimsa 

This is the native WordPress behavior when enqueuing styles and scripts.

You can [read more about it here](https://wordpress.stackexchange.com/questions/132282/removing-wordpress-version-number-from-included-files) and learn how to remove it.

Thanks!
