### ISSUE TITLE
Error when setting a background gradient then using non-gradient on hover

### ISSUE THREAD

**Issue by barrychapman** [elementor/elementor#8644]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When creating an element, and then using the Style panel to set a background, if you set the background as a GRADIENT, and then for the HOVER STATE, set a background of color (non-gradient), the background-image of the gradient still overrides on hover the defined background color.

## Steps to reproduce

1. Set background for element as a gradient, any kind, doesnt matter
2. Set background for same elements HOVER STATE as a color, not a gradient
3. Save
4. when viewing in browser, the background gradient for default state overrides the hover color
5. This is because background-image css property is not set to NONE when using hover state. The background-image takes precedence over the background-color property.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.12.2
	MySQL version: Source distribution v5.7.24
	PHP Version: 7.2.20
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://ngfd.ghosttown.io
	Home URL: http://ngfd.ghosttown.io
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Active

== Theme ==
	Name: FloorDetective
	Version: 1.0.0
	Author: Ghosttown Development, LLC
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.8.4
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

== Active Plugins ==
	ACF Options Page Admin
		Version: 3.9.4
		Author: John A. Huebner II

	Advanced Cron Manager
		Version: 2.3.4
		Author: BracketSpace

	Advanced Custom Fields PRO
		Version: 5.7.13
		Author: Elliot Condon

	AnyWhere Elementor Pro
		Version: 2.11.4
		Author: WebTechStreet

	Astra Pro
		Version: 1.8.2
		Author: Brainstorm Force

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Custom Sidebars
		Version: 3.2.3
		Author: WPMU DEV

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	DynamicConditions
		Version: 1.3.2
		Author: RTO GmbH

	Dynamic Visibility for Elementor
		Version: 2.0.4
		Author: Dynamic.ooo

	Easy WP SMTP
		Version: 1.3.9.1
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 2.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.14
		Author: Elementor.com

	Essential Addons for Elementor - Pro
		Version: 2.15.0
		Author: WPDeveloper

	Font Awesome
		Version: 4.0.0-rc9
		Author: Font Awesome

	GEO my WP
		Version: 3.3
		Author: Eyal Fitoussi

	GMW Add-on - Premium Settings
		Version: 2.3
		Author: Eyal Fitoussi

	GMW Add-on - WordPress Users Locator
		Version: 1.4.3
		Author: Eyal Fitoussi

	GP Conditional Pricing
		Version: 1.2.36
		Author: Gravity Wiz

	GP Nested Forms
		Version: 1.0-beta-6.14
		Author: David Smith

	Gradient Button for Elementor
		Version: 1.0.2
		Author: BloomPixel

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	Gravity Forms
		Version: 2.3.6.4
		Author: rocketgenius

	Gravity Forms Constant Contact Add-On
		Version: 3.1.1
		Author: Katz Web Services, Inc.

	Gravity Forms Coupons Add-On
		Version: 2.8
		Author: rocketgenius

	Gravity Forms Stripe Add-On
		Version: 2.6
		Author: rocketgenius

	Gravity Perks
		Version: 2.1.1
		Author: Gravity Wiz

	Header, Footer & Blocks for Elementor
		Version: 1.1.2
		Author: Brainstorm Force, Nikhil Chavan

	Heroic Knowledge Base
		Version: 2.16.0
		Author: HeroThemes

	HT Mega - Absolute Addons for Elementor Page Builder
		Version: 1.1.0
		Author: HT Plugins

	Inspection Report Generator
		Version: 1.0.0
		Author: Ghosttown Development, LLC

	JetBlog For Elementor
		Version: 2.1.12
		Author: Zemez

	JetElements For Elementor
		Version: 1.15.12
		Author: Zemez

	JetEngine
		Version: 1.4.2
		Author: Zemez

	JetSmartFilters
		Version: 1.3.2
		Author: Zemez

	Loginizer
		Version: 1.4.2
		Author: Raj Kothari

	MailOptin - Lite
		Version: 1.2.15.1
		Author: MailOptin Team

	MemberPress Constant Contact
		Version: 1.0.2
		Author: Caseproof, LLC

	MemberPress Corporate Accounts
		Version: 1.4.9
		Author: Caseproof, LLC

	MemberPress Developer Tools
		Version: 1.1.21
		Author: Caseproof, LLC

	MemberPress Downloads
		Version: 1.0.3
		Author: Caseproof, LLC

	MemberPress Importer
		Version: 1.5.1
		Author: Caseproof, LLC

	MemberPress Math CAPTCHA
		Version: 1.1.4
		Author: Caseproof, LLC

	MemberPress Plus
		Version: 1.4.4
		Author: Caseproof, LLC

	MemberPress User Roles
		Version: 1.0.4
		Author: Caseproof, LLC

	Members
		Version: 2.1.0
		Author: Justin Tadlock

	miniOrange Malware Protection
		Version: 2.42
		Author: miniorange

	Nav Menu Roles
		Version: 1.9.3
		Author: Kathy Darling

	Password Protected
		Version: 2.2.5
		Author: Ben Huson

	Premium Addons for Elementor
		Version: 3.2.9
		Author: Leap13

	Premium Addons PRO
		Version: 1.3.7
		Author: Leap13

	QuadMenu
		Version: 1.8.5
		Author: Mega Menu

	QuadMenu PRO
		Version: 1.7.8
		Author: Mega Menu

	Query Monitor
		Version: 3.3.7
		Author: John Blackbourn

	Redirection
		Version: 4.3
		Author: John Godley

	Redis Object Cache
		Version: 1.4.3
		Author: Till Krüss

	Simple Custom Post Order
		Version: 2.4.3
		Author: Colorlib

	SupportCandy
		Version: 2.0.4
		Author: SupportCandy

	SupportCandy - Automatic Close Ticket
		Version: 2.0.0
		Author: Support Candy

	SupportCandy - Email Piping
		Version: 2.0.1
		Author: Support Candy

	SupportCandy - Export Ticket
		Version: 2.0.0
		Author: Export Ticket

	SupportCandy - FAQ Integration
		Version: 2.0.0
		Author: Support Candy

	SupportCandy - Reports
		Version: 2.0.0
		Author: Support Candy

	SupportCandy - Satisfaction Survey
		Version: 2.0.0
		Author: Support Candy

	SupportCandy - SLA
		Version: 2.0.1
		Author: Support Candy

	SupportCandy - Usergroup
		Version: 2.0.0
		Author: Support Candy

	Toolset Types
		Version: 2.3.5
		Author: OnTheGoSystems

	Ultimate Addons for Elementor
		Version: 1.12.1
		Author: Brainstorm Force

	User Role Editor
		Version: 4.51
		Author: Vladimir Garagulya

	Webcraftic Clearfy – WordPress optimization plugin
		Version: 1.5.3
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	Widgets in Menu for WordPress
		Version: 1.0.0
		Author: saurabhshukla, yapapaya

	WP-Optimize
		Version: 2.3.3
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPSHAPERE
		Version: 5.0.3
		Author: AcmeeDesign Softwares and Solutions

	WP Staging Pro
		Version: 2.5.6
		Author: WP-Staging, René Hermenau

	wp_upload_rename
		Version: 1.2
		Author: Nolan Chou

	YellowPencil
		Version: 127.1.9
		Author: WaspThemes

== Must-Use Plugins ==
	WP Staging Optimizer
		Version: 1.0
		Author: René Hermenau

== Log ==
	: 
Log: showing 20 of 302019-04-13 00:08:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.4',
  'to' => '2.5.5',
)]
2019-05-04 21:51:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]
2019-05-04 21:51:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.5',
  'to' => '2.5.6',
)]
2019-05-20 01:36:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.6',
  'to' => '2.5.8',
)]
2019-05-20 01:37:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.14',
  'to' => '2.5.15',
)]
2019-05-28 23:41:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.15',
  'to' => '2.5.16',
)]
2019-05-28 23:41:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]
2019-07-12 11:52:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-12 11:53:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.5.13',
)]
2019-07-12 11:53:52 [info] elementor::elementor_updater Started 
2019-07-12 11:53:52 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-12 11:53:52 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-12 11:53:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-12 11:53:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-12 11:53:54 [info] elementor::elementor_updater Started 
2019-07-12 11:53:54 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-12 11:53:54 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-12 11:53:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.1',
)]
2019-07-18 23:05:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.1',
  'to' => '2.6.5',
)]
2019-07-18 23:09:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]

PHP: showing 5 of 5PHP: 2019-04-10 00:03:21 [notice X 3][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-21 22:55:39 [error X 2][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php::163] Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php:163
Stack trace:
#0 /var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/managers/controls.php(844): Elementor\Controls_Stack->get_unique_name()
#1 /var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php(482): Elementor\Controls_Manager->get_element_stack(Object(Elementor\Element_Column))
#2 /var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php(278): Elementor\Controls_Stack->get_stack()
#3 /var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php(1954): Elementor\Controls_Stack->get_controls()
#4 /var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/includes/base/controls-stack.php(1018): Elementor\Controls_Stack->sanitize_settings(Array)
#5 /var/www/vhosts/floordetective.ng/wp-content/plugin [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-05-05 00:24:16 [notice X 79][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/files/css/base.php::703] Undefined index: _id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-06-02 07:51:00 [notice X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-19 21:46:59 [error X 1][/var/www/vhosts/floordetective.ng/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Out of memory (allocated 173178880) (tried to allocate 33159632 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2019-04-13 05:22:26 [error X 12][https://ng.floordetective.com/wp-content/plugins/dynamic-visibility-for-elementor/assets/js/dce-editor.js?ver=2.0.4:44:9] elementorFrontend is not defined 
JS: 2019-04-20 13:16:57 [error X 1][https://ng.floordetective.com/wp-content/plugins/premium-addons-pro/assets/js/lib/jquery.multiscroll.min.js:1:7190] Cannot read property \'top\' of undefined 
JS: 2019-04-21 03:55:22 [error X 2][https://ng.floordetective.com/wp-content/plugins/ultimate-elementor/assets/lib/jquery-element-resize/jquery_resize.min.js:9:229] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2019-04-22 04:16:05 [error X 1][https://ng.floordetective.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5335\") has already been destroyed and cannot be used. 
JS: 2019-05-18 07:19:27 [error X 2][https://ng.floordetective.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.14:2:10531] n.attributes[t.name].each is not a function 
JS: 2019-05-26 05:12:15 [error X 1][https://ng.floordetective.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.5.15:2:9579] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `eael-creative-button` got </content/purchase-floor-detective-book> as `creative_button_link_url` value. Expected array or object.',
)]
JS: 2019-06-03 04:06:03 [error X 3][https://ng.floordetective.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:130676] Cannot read property \'0\' of undefined 
JS: 2019-07-19 04:35:07 [error X 4][http://ngfd.ghosttown.io/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.6.5:2:38135] n.attributes[e.name].each is not a function 

				
</details>

**Comment by shilo-ey** [comment]
Hi @barrychapman 
Thanks for your feedback.

We are aware of this issue, and this is caused by the reason you mentioned.

Currently this is the behavior we can allow, but for now, you can add a gradient with the 2 identical colors to walk around this issue.

Thanks!

**Comment by MeltingOpera** [comment]
Almost 4 years later this is still a problem. I set my button background as a gradient in the theme stlyle settings and in order to override it for individual buttons, I have to use the gradient with two identical colors way.
