### ISSUE TITLE
Interaction between Elementor and Media Library Assistant

### ISSUE THREAD

**Issue by dglingren** [elementor/elementor#8649]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I have opened the following topic in the Elementor Support Forum:

https://wordpress.org/support/topic/interaction-between-elementor-and-media-library-assistant/

"cavalierlife" suggested that I post it here as well.  Briefly, when my Media Library Assistant plugin is active the "text color preview span" does not update properly. You can find the details in this support topic:

https://wordpress.org/support/topic/after-2-years-2/

I have reproduced the problem on my test system, but my JavaScript skills are limited and I do not understand the Elementor scripts well enough to identify the cause of the problem.

If you can find the cause of the problem I will make any changes to my plugin required to resolve it. Thanks for any help you can provide!

## Steps to reproduce

Install and activate Media Library Assistant. That's it, no configuration required.
Edit a page/post with Elementor, create a Heading widget, enter some text and try to change its color.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@dglingren 

Thanks for reaching out,

I tried taking a look at what could be the cause and the only thing I can come up with is jQuery version collision more specifically The `$.fn.css()` method.

But I wouldn't worry about it too much as we are upgrading our Color Control in the upcoming versions.

thanks.
