### ISSUE TITLE
User access control for Pages

### ISSUE THREAD

**Issue by moisb** [elementor/elementor#8650]
It would be very useful if Elementor Pro had an access control option in the menu. Since it is a plugin used to create pages, I find it quite user friendly. Thus, when creating a page, we can choose whether it will be visible publicly or only to logged in users, without the need to install additional plugins just for that.
I currently use a community plugin to do this. And the bad thing is that after creating the page with the Element Editor, I need to go back to the default Wordpress editor to select the access restriction.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
