### ISSUE TITLE
Please make the Counter Widget's Title, Prefix, and Suffix text boxes capable of dynamic content.

### ISSUE THREAD

**Issue by rdytogokev** [elementor/elementor#8652]
## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When adding/editing a Counter Widget, the Title text box, and the Prefix and Suffix text boxes cannot be set to a Dynamic value.

**Describe the solution you'd like**
I would like to have the Dynamic icons available to the Title text box, and the Prefix and Suffix text boxes of the Counter Widget.

**Describe alternatives you've considered**
I have looked at other WordPress Elementor plugins.

**Additional context**
Just want to clarify that I am not referencing changing a number. I understand that there is already an issue open for adjusting number fields dynamically. I am requesting a text field.

**Comment by shilo-ey** [comment]
Hi @rdytogokev 

Thanks for your feedback.

We will consider adding this option in the future and will update this thread.

Thanks!
