### ISSUE TITLE
Sticky vide only when video is playing

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#8654]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sticky video pop up shows when the video is NOT playing

**Describe the solution you'd like**
An option that only has the stick video pop up show when the video is actually playing

**Describe alternatives you've considered**
None

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
