### ISSUE TITLE
Price table panel bug

### ISSUE THREAD

**Issue by astanar01** [elementor/elementor#8660]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Clicking on "Features" in the price table widget shows an empty column. 
Inspecting the page leads to this:

TypeError: e.replace is not a functioneditor.min.js:32:16763

https://imgur.com/a/dWPGwWf

## Steps to reproduce

Create a page. Add a price table.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '29', Revision '11ad961' v5.7.26-29
	PHP Version: 7.3.5-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://*****
	Home URL: http://*****
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.1.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

== Active Plugins ==
	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.0
		Author: Elementor.com

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine System
		Version: 3.2.1
		Author: WP Engine

== Log ==
	: 
Log: showing 7 of 72019-07-16 12:24:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.6',
  'to' => '2.5.14',
)]
2019-07-23 11:07:43 [info] elementor::elementor_updater Started 
2019-07-23 11:07:43 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-23 11:07:43 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-23 11:07:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.6',
)]
2019-07-23 11:07:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.6',
)]
2019-07-23 11:07:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.14',
  'to' => '2.6.0',
)]

JS: showing 3 of 3JS: 2019-07-17 12:11:47 [error X 7][https://******/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.2:7:41783] setting getter-only property \"type\" 
JS: 2019-07-23 11:47:11 [error X 3][https://**********/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.6:7:19723] this.ui.sliders.filter(...)[0] is undefined 
JS: 2019-07-23 12:02:36 [error X 12][https://*******/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.6:32:16763] e.replace is not a function

**Comment by shilo-ey** [comment]
Thanks for reporting!

We will address this issue soon and release a patch.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.1

Feel free to update

Thanks!

**Comment by IAmEvyatar** [comment]
Still experiencing the same issue with v2.6.1 

> This issue has been resolved in Elementor Pro v2.6.1
> 
> Feel free to update
> 
> Thanks!

**Comment by dsfrederic** [comment]
> This issue has been resolved in Elementor Pro v2.6.1
> 
> Feel free to update
> 
> Thanks!

Still experiencing this issue in Elementor pro v2.6.2
