### ISSUE TITLE
Ability to insert SVG icons into text fields

### ISSUE THREAD

**Issue by xavierbergantz** [elementor/elementor#8663]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It is a real pity that it is impossible to insert SVG icons in a text field.

**Describe the solution you'd like**
I would like to be able to access the icon library without having to use the widgets specifically designed to use it, nor  using another plugin (they are very rare).

**Describe alternatives you've considered**
Perhaps you could add a "insert icon" button to the text field editing menu, without having to change sections (such as an icon meaning the opening of a new tab next to a link).

**Additional context**

Many thanks for your attention.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
