### ISSUE TITLE
Social Icons Secondary Colour not working since 2.6

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#8666]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by stevewoody82** [comment]
This is confirmed when adding Font Awesome Pro code to integrations

**Comment by stevewoody82** [comment]
Happens when webkit has SVG enabled instead of webfonts

**Comment by bainternet** [comment]
Glad you figured it out

**Comment by bainternet** [comment]
@stevewoody82 

Secondary color Won't work with SVG's only Font Icons.

Thanks
