### ISSUE TITLE
Responsive settings in the posts widgets

### ISSUE THREAD

**Issue by HelmutGoebel** [elementor/elementor#8670]
Why is there no responsive settings for row and column gap? for a good design, this is necessary.

![image](https://user-images.githubusercontent.com/14095280/61779150-70f75080-ae00-11e9-9fee-1082829faef5.png)

**Comment by shilo-ey** [comment]
Hi @HelmutGoebel 

I merged this issue with #1851, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
