### ISSUE TITLE
Medialibrary frame launching mode

### ISSUE THREAD

**Issue by hokoo** [elementor/elementor#8671]
Hi, guys! 
WordPress provides the API for create custom tabs in the modal media frame (media library). I use this and I have my custom tabs in left sidebar of the frame. This sidebar appears when media frame starts in post-mode. 
```
var frame = wp.media({
  frame : 'post'
})
```
But Elementor initiate this modal frame in default mode, and left sidebar is hidden. 
```
  /**
   * Create a media modal select frame, and store it so the instance can be reused when needed.
   */
  initFrame: function initFrame() {
    // Set current doc id to attach uploaded images.
    wp.media.view.settings.post.id = elementor.config.document.id;
    this.frame = wp.media({
      button: {
        text: elementor.translate('insert_media')
      },
      states: [new wp.media.controller.Library({
        title: elementor.translate('insert_media'),
        library: wp.media.query({
          type: this.getMediaType()
        }),
        multiple: false,
        date: false
      })]
    }); 
```
I offer to use the filter to manage (if necessary) mediaframe mode.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
