### ISSUE TITLE
Posts widget include by Term Taxonomy returns empty in elementor 2.6

### ISSUE THREAD

**Issue by TzahiFadida** [elementor/elementor#8672]
I have elementor pro and the bug happened after an upgrade.
It happened on 2 different sites and servers.

When attempting to select from the taxonomy it cannot find post categories or anything. Nothing is actually being returned rendering the posts widget useless.

Thanks.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.1

Feel free to update

Thanks!

**Comment by TzahiFadida** [comment]
Fixed. Thanks!

**Comment by shilo-ey** [comment]
This issue has been fixed in Elementor Pro v2.6.2

Feel free to update

Thanks
