### ISSUE TITLE
Duplicated post content not working.

### ISSUE THREAD

**Issue by netkata-dev** [elementor/elementor#8674]
The client creates a view for post and he has one view for desktop and tablet and below the view for mobile-only. In each view, he has "post content" block (so two times).

And now:
When we have the block in desktop/tablet view it's working for desktop and tablet, and below the same block not working for mobile.
When we don't have the block in desktop/tablet and have this block in mobile view it working on mobile view.

So the bug is that we cannot have post content block more than once.

It renders only once in HTML.

**Comment by shilo-ey** [comment]
You can't call `the_content` twice in the same page.

That's why this is not working for you.

Thanks
