### ISSUE TITLE
Issue with Portfolio and Posts widget; query term does not pull up any categories

### ISSUE THREAD

**Issue by the-gap-decaders** [elementor/elementor#8676]
- Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before. x
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.x
- Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.x
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).x
- If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific.

I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
The issue still exists against the latest stable version of Elementor.

Description

I updated to Elementor Pro 2.6.0 today.  Since then the Posts and Portfolio widgets will not pull up categories in the query, term box.  In the screenshot I am looking for posts categorised as 'essential country guides'.  

I can re-produce this problem each time I add or try to edit an existing Portfolio or Posts widget.

Isolating the problem
This bug happens with only Elementor plugin active (and Elementor Pro). x
This bug happens with a default WordPress theme active. x
I can reproduce this bug consistently using the steps above. x

Environment

<img width="582" alt="Screenshot 2019-07-24 at 17 10 35" src="https://user-images.githubusercontent.com/50086184/61805764-b6367500-ae36-11e9-87b0-2f9ccd962602.png">

**Comment by rathert** [comment]
I can confirm this. After the update today (Elementor 2.6.6, Elementor Pro 2.6.0), queries addressing terms show no results. Existing queries continue working, but cannot be edited.

**Comment by HmCody** [comment]
I can also confirm this problem. Using Elementor 2.6.6 & Elementor Pro 2.6.0 with Hello Elmentor theme. Using a Pods CPT with a custom taxonomy. No results found, but existing query still works.

**Comment by rathert** [comment]
There was another update to Elementor Pro 2.6.1 that solved the query issue. Just install this version, and queries will work again.

**Comment by bainternet** [comment]
Fixed in Elementor Pro 2.6.1

thanks for reporting.

**Comment by Hynek-O** [comment]
The latest version Elementor & Elementor PRO. But it also doesn't work for me (query) for porfolio (elementor module PRO). **A slightly different problem:** It just doesn't show all the posts. E.g. are 3 and shows 1 and the like. Nonsense. Can anyone solve this? Thanks.
