### ISSUE TITLE
How to hook $setting object in the elementor widget render() function

### ISSUE THREAD

**Issue by adan2g2f** [elementor/elementor#8679]
**My need:**
I want to update the object settings['tabs'] in the elementor widget: 
/wp-content/plugins/elementor/includes/widgets/toogle.php

Inside the function render():
```
	protected function render() {
		$settings = $this->get_settings_for_display();
```

I have tried some hook from elementor documentation:
`add_action( 'elementor/widget/render_content', function( $content, $widget ) `
this update the settings but after render() function, so not usable for my need.

```
add_action( 'elementor/element/toggle/section_toggle/before_section_end', function ( $element )
```
this is call before the render() function but it seems that the set_settings update is not working as expected, because $settings['tabs'] are not updated:

```PHP
$settings_tabs = [
			[
				'tab_title' => __( 'Toggle D01X', 'elementor' ),
				'tab_content' => __( 'Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.', 'elementor' ),
				'_id' => 'x78f1580',
			],		
		];

		$element->set_settings( 'tabs', $settings_tabs);
		$settings = $element->get_settings('tabs');
```

**Comment by bainternet** [comment]
You can try to use these hooks:

https://github.com/elementor/elementor/blob/9243298ee61140875065f642bb91631f06d4efc5/includes/base/element-base.php#L519-L529

https://github.com/elementor/elementor/blob/9243298ee61140875065f642bb91631f06d4efc5/includes/base/element-base.php#L519-L529

**Comment by adan2g2f** [comment]
Hello Bainternet,
Yes it's working fine, great job :)
Now I will search for same on the widget edition side.
Many thanks to you 👍 !
