### ISSUE TITLE
Feature Request: Clone/Duplicate Page/Post at Pages/Posts Dashboards

### ISSUE THREAD

**Issue by greenhouse-dwm** [elementor/elementor#8680]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Being able to clone/duplicate from the pages/posts dashboards (like the Duplicate Post plugin: https://wordpress.org/plugins/duplicate-post/) would expedite site development and allow for any SEO configurations in the initial page/post to be preserved in the duplicated post/page.  

**Describe the solution you'd like**
Inclusion of this feature in the Elementor Pro build.

**Describe alternatives you've considered**
I use https://wordpress.org/plugins/duplicate-post/ but would like to reduce plugins.

**Additional context**
Love Elementor and thanks for your consideration. Cheers.

**Comment by bainternet** [comment]
@greenhouse-dwm 

Thanks for the suggestion, 

We feel that this is more of a 3rd party plugin territory for now.

Thanks for the feedback.
