### ISSUE TITLE
Feature Request: Slideshow Additional Features

### ISSUE THREAD

**Issue by greenhouse-dwm** [elementor/elementor#8681]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Expansion/more feature-rich slider functionality. Reduction of plugins.

**Describe the solution you'd like**
Allowing for 1) split contents (i.e. 50% text 50% image) or columns in a slide 2) allowing for video in a slide.

**Describe alternatives you've considered**
I currently use SmartSlider.

**Additional context**
Love Elementor and thanks!

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Description and examples.**
* **One request per thread**

Thanks.
