### ISSUE TITLE
Entrance Animation not working on some iOS devices

### ISSUE THREAD

**Issue by ratsoid** [elementor/elementor#8682]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

The Entrance Animations do not work on some iOS devices like iPhone 6 and 7, iPad Air 2 but they apparently work on iPhone X. The animation delay seems to exist but needless to say it's hard to inspect something on an iPhone. I am having the same issue on different websites, on different servers, with different iOS browsers (not that it should it matter).
I have tried both Internal and External CSS print methods.

## Steps to reproduce

Visit any site with the latest Elementor from on pre-iPhone X phone (maybe)

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.26
	PHP Version: 5.6.40
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://nubsite.ro
	Home URL: http://nubsite.ro
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 3
	Admin Email: my@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Filme
	Version: 1.0.0
	Author: Echipa
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.1.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

== Active Plugins ==
	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.0
		Author: Elementor.com

	Ultimate Addons for Elementor
		Version: 1.14.0
		Author: Brainstorm Force


== Log ==
	: 
Log: showing 9 of 92019-07-15 15:38:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.1',
  'to' => '2.6.2',
)]
2019-07-18 15:39:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.4',
)]
2019-07-19 12:37:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.4',
  'to' => '2.6.5',
)]
2019-07-23 15:39:44 [info] elementor::elementor_updater Started 
2019-07-23 15:39:44 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-23 15:39:44 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-23 15:39:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-07-23 15:39:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.5',
  'to' => '2.6.6',
)]
2019-07-23 15:54:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.6.0',
)]

JS: showing 1 of 1JS: 2019-07-23 21:07:36 [error X 3][http://nubsite.ro/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.6:7:41783] setting getter-only property \&quot;type\&quot; 

PHP: showing 1 of 1PHP: 2019-07-24 00:35:49 [notice X 2][/home/nubro/nubsite.ro/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

```
</details>

**Comment by ratsoid** [comment]
Weirdly enough, the animations work alright on iPhone 6 Plus and iPhone 8 Plus :|

**Comment by bainternet** [comment]
@ratsoid 

Entrance animation won't work if you have "reduce motion" turned on, which makes this an accessibility feature more then a bug

check your ios devices to see if you have it turn on, usually at:
Settings > General > Accessibility > Reduce Motion.

if not, please feel free to reopen.

thanks.

**Comment by steinerevado** [comment]
Im facing the same issue on a iPad mini iOS 9.3.5. Entrance animation is not working so there is empty white space. Reduce Motion is disabled.

**Comment by ratsoid** [comment]
well you have to enable Reduce Motion to make it work. It's probably an iOS thing that disables CSS animations so it might not be something that's fixable within elementor

**Comment by steinerevado** [comment]
It's not working independently if setting is enabled or disabled.

**Comment by wasim-abuzaher** [comment]
Has there been any progress on this? I have the same issue when Reduce Motion is either enabled or disabled. Also Image Carousel isn't showing on iOS devices (iPad and iPhone)

**Comment by ewokee** [comment]
same problem here - no animations, no popups, no menus in a popup for iphones - even iphone X is blank - any idea how to fix? ...

**Comment by wasim-abuzaher** [comment]
To me it was a bad entry animation (placed on the column instead of the item inside of it) and then all following animations that occurs after that problematic column didn't render. Once I fixed that one animation, everything worked fine.

You'd have to debug (deactivating animations from top to bottom of the page kind of trial and error). 

Hope this helps

**Comment by ewokee** [comment]
all animations deactivated, if i activate one animation on an item again, its again not showing. in combination no single pop opening on iOS. very weird.

**Comment by ArtyshukPavlo** [comment]
Same issue. Element animations not working, same as Counter widget on iOS =< v12. Elementor 5.3.

**Comment by worldwise5** [comment]
Hi
Element animations not working
I have the same issue with the latest Elementor pro version 3.6.1, no animation on the entrance, any sort of movement whether its a "Fade in" slider etc, all the issues are happening on iPhone 10, I found the only way to sort the matter out was to STOP all animation in Mobile-Table-& Desktop when editing. if I let one of them have any sort of animation the corresponding item will not work on the IOS. for instance if I allow the animated divider to work in desktop mode it will not appear on the iPhone web version. turning off the "Reduce motion" on the iPhone had no effect.

**Comment by AdrianPaulV** [comment]
Same issue here. Reduce Motion is not on, Using Hello theme, and no plugins besides Elementor and Pro.

**Comment by meisterleise** [comment]
I first thought, I have the same problem. But the animations only don't work on iOS Simulator of Xcode. On a real iPhone the animations work.

So for all with this issue:
a) Do you test on a real phone or a simulator?
b) on which browser and version do you test it?
