### ISSUE TITLE
Search Form Widget Ajax Search Functionality

### ISSUE THREAD

**Issue by webbteche** [elementor/elementor#8683]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Like the one on google when you type a letter there are suggestion below when you type so for easy searching.

**Describe the solution you'd like**
Add functionality on Search form widget

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/5598 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
