### ISSUE TITLE
Elementor Form - Add new field type for "Email Confirmation"

### ISSUE THREAD

**Issue by ramiy** [elementor/elementor#8684]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Elementor forms comes with a regular "**Email**" field type. But no "**Email Confirmation**". The new field type should check whether the two fields are equal when clicking the Submit button. If they are not equal, an error should be displayed.

**Describe the solution you'd like**

A new "**Field Type**" called "**Email Confirmation**" with all the controls the regular Email field type has. In addition, a new control where the user can select an email field to compare to.

**Describe alternatives you've considered**

Am alternative is to write custom JS to compare the two fields.

**Additional context**

![1414](https://user-images.githubusercontent.com/576623/61848829-0b669b00-aeb8-11e9-8181-566373acfaa8.png)

![1515](https://user-images.githubusercontent.com/576623/61848942-5aaccb80-aeb8-11e9-8094-6232684ea339.png)

![1616](https://user-images.githubusercontent.com/576623/61849211-3a314100-aeb9-11e9-9c23-50c892cdeb0f.png)

**Comment by bainternet** [comment]
@ramiy 

You don't really need a new field type just for validation, you can use the current Emil type field twice and add the validation yourself, ex:

```PHP
// Validate confirmation email
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {

	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );

	// Replace MY_FORM_NAME with the name you gave your form
	if ( 'YOUR_FORM_NAME' !== $form_name ) {
		return;
	}

	$first_email_field = $record->get_field( [
		'id' => 'main_email_field_id',
	] );

	$second_email_field = $record->get_field( [
		'id' => 'confirmation_email_field_id',
	] );

	if ( $first_email_field['value'] !== $second_email_field['value'] ) {
		$ajax_handler->add_error( $second_email_field['id'], 'Confirmation Email must match the Email field' );
	}
}, 10, 2 );
```

thanks.

**Comment by papplebee** [comment]
Hello,

Where do I need to add this code? I have tried putting it in the theme functions.php and changing the field ids and form name where required, but it is not working.

Do I need to put it in a custom plugin instead?

Many thanks.

**Comment by bodhi1970** [comment]
No answer here but closed? Where should that code go @bainternet?

**Comment by jcleiva4532** [comment]
Hello Ramiy,,,,
It is possible for you to let me know where exactly I need to put the code to validated  the email?
I was looking into the elementor pro/plugins I don't see where to add the code you are suggesting
Thank a lot in advance for any tip....

**Comment by jcleiva4532** [comment]
Did any one figure out where to put the code?

Thanks

**Comment by IlPizza79** [comment]
@ramiy jcleiva4532, you should add it in functions.php of your child theme or you can use a plugin to add "Code snippets" to your website, like this one: https://it.wordpress.org/plugins/code-snippets/

@bainternet why close this request? it's true it can be done using a custom code snippet (many thing can be done using custom code snippets!) but people use Elementor because they can't (or don't want to) use custom code snippets :-)

**Comment by haywirephoenix** [comment]
+1 for built in email validation switch or field

**Comment by haywirephoenix** [comment]
The code was incorrect. After some diagnosing I got it working.

`$form_name = $record->get_form_settings( 'form_name' );

	// Replace MY_FORM_NAME with the name you gave your form

  if ( 'MY_FORM_NAME' !== $form_name ) {
    return;
  }

//Make sure your field ID's are set to match these in each field's Advanced > Field ID
  $first_email_field = $record->get_field( [
    'id' => 'MY_FIELD_ID_1'
  ] );

//Make sure your field ID's are set to match these in each field's Advanced > Field ID
  $second_email_field = $record->get_field( [
    'id' => 'MY_FIELD_ID_2'
  ] );

//Make sure your field ID's are set to match these in each field's Advanced > Field ID
	if ( $first_email_field['MY_FIELD_ID_1']['value'] !== $second_email_field['MY_FIELD_ID_2']['value'] ) {
		$ajax_handler->add_error( $second_email_field['MY_FIELD_ID_2']['id'], 'Confirmation Email must match the Email field' );
	}

}, 10, 2 );
`

**Comment by AchiD0313** [comment]
> The suggested code was incorrect. After some diagnosing I got it working, the arrays are nested.
> Here it is if anyone needs it.
> 
> ```
> $form_name = $record->get_form_settings( 'form_name' );
> 
> // Replace MY_FORM_NAME with the name you gave your form
> 
>   if ( 'MY_FORM_NAME' !== $form_name ) {
>     return;
>   }
> 
> //Replace MY_FIELD_ID_1 to match the field's Advanced > Field ID
> 
>   $first_email_field = $record->get_field( [
>     'id' => 'MY_FIELD_ID_1'
>   ] );
> 
> //Replace MY_FIELD_ID_2 to match the field's Advanced > Field ID
> 
>   $second_email_field = $record->get_field( [
>     'id' => 'MY_FIELD_ID_2'
>   ] );
> 
> //Make sure your field ID's are set to match these in each field's Advanced > Field ID
> 	if ( $first_email_field['MY_FIELD_ID_1']['value'] !== $second_email_field['MY_FIELD_ID_2']['value'] ) {
> 		$ajax_handler->add_error( $second_email_field['MY_FIELD_ID_2']['id'], 'Confirmation Email must match the Email field' );
> 	}
> 
> }, 10, 2 );
> ```

I Have used the code but i encounter this error... 

Your PHP code changes were rolled back due to an error on line 70 of file wp-content/themes/[my theme directory here ]. Please fix and try saving again.

syntax error, unexpected '}', expecting end of file

the error is referring to this line at last " }, 10, 2 ); " 

Will you be able to help me with this???

**Comment by haywirephoenix** [comment]
> > The suggested code was incorrect. After some diagnosing I got it working, the arrays are nested.
> > Here it is if anyone needs it.
> > ```
> > $form_name = $record->get_form_settings( 'form_name' );
> > 
> > // Replace MY_FORM_NAME with the name you gave your form
> > 
> >   if ( 'MY_FORM_NAME' !== $form_name ) {
> >     return;
> >   }
> > 
> > //Replace MY_FIELD_ID_1 to match the field's Advanced > Field ID
> > 
> >   $first_email_field = $record->get_field( [
> >     'id' => 'MY_FIELD_ID_1'
> >   ] );
> > 
> > //Replace MY_FIELD_ID_2 to match the field's Advanced > Field ID
> > 
> >   $second_email_field = $record->get_field( [
> >     'id' => 'MY_FIELD_ID_2'
> >   ] );
> > 
> > //Make sure your field ID's are set to match these in each field's Advanced > Field ID
> > 	if ( $first_email_field['MY_FIELD_ID_1']['value'] !== $second_email_field['MY_FIELD_ID_2']['value'] ) {
> > 		$ajax_handler->add_error( $second_email_field['MY_FIELD_ID_2']['id'], 'Confirmation Email must match the Email field' );
> > 	}
> > 
> > }, 10, 2 );
> > ```
> 
> I Have used the code but i encounter this error...
> 
> Your PHP code changes were rolled back due to an error on line 70 of file wp-content/themes/[my theme directory here ]. Please fix and try saving again.
> 
> syntax error, unexpected '}', expecting end of file
> 
> the error is referring to this line at last " }, 10, 2 ); "
> 
> Will you be able to help me with this???

Ah yes the top line was missing, I've updated the comment for you.

**Comment by DavidGMiles** [comment]
This action hook doesnt appear to work for me - it still allows through mismatched pairings of email addresses - this is basic validation that should be built in

**Comment by itslive2020** [comment]
Hi! the email-fields still can be different. Form is sent. Any suggestions? Thank you!

**Comment by DavidGMiles** [comment]
None and seemingly not important to the team - but hey look ‘we’ve added gradient buttons’

**Comment by haywirephoenix** [comment]
Hey guys let me know if you've changed the following fields in my code. They have to match the id of your form and email fields for it to work.

MY_FORM_NAME
MY_FIELD_ID_1
MY_FIELD_ID_2

@bainternet Please reopen as a feature request to add an email validation field.

**Comment by DavidGMiles** [comment]
I did - no joy for me - I am running the Optimised DOM experiment though

**Comment by itslive2020** [comment]
Hi!

the nam of the form is: formular_1
the name of field email is: field_email_1
the name of confirmation field email is: field_email_2

Here the code i tried:

// Validate confirmation email 

add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) { 

$form_name = $record->get_form_settings( 'form_name' );

// Replace MY_FORM_NAME with the name you gave your form

  if ( 'formular_1' !== $form_name ) {
    return;
  }

//Replace MY_FIELD_ID_1 to match the field's Advanced > Field ID

  $first_email_field = $record->get_field( [
    'id' => 'field_email_1'
  ] );

//Replace MY_FIELD_ID_2 to match the field's Advanced > Field ID

  $second_email_field = $record->get_field( [
    'id' => 'field_email_2'
  ] );

//Make sure your field ID's are set to match these in each field's Advanced > Field ID
	if ( $first_email_field['field_email_1']['value'] !== $second_email_field['field_email_2']['value'] ) {
		$ajax_handler->add_error( $second_email_field['field_email_2']['id'], 'Confirmation Email must match the Email field' );
	}

}, 10, 2 );


Still there can be different emails put in, it will be sent.
Thank you.

**Comment by haywirephoenix** [comment]
Try this I think this line also needs to change from

$form_name = $record->get_form_settings( 'form_name' );

To

$form_name = $record->get_form_settings( 'MY_FORM_NAME' );

(MY_FORM_NAME) in your case @itslive2020 being formular_1

I must have missed it when adding the extra line in the edit,  give that a try!

**Comment by haywirephoenix** [comment]
Just compared the above to mine and it works for me. Is the code placed in the functions.php file of your active theme? If so turn on debugging and see if any errors? Also note that this is pointing to elementor_pro

**Comment by itslive2020** [comment]
Hi! Yes, sure. All does not work, even when i change the line

$form_name = $record->get_form_settings( 'form_name' );

to

$form_name = $record->get_form_settings( 'formular_1 );

**Comment by Christofer92** [comment]
Hello,

Could I do the same process using "Password" and "Confirm password"?

Thanks a lot!

**Comment by loisgirard** [comment]
Can we get the same with password confirmation ?

**Comment by zhair185** [comment]
Worked For Me, Thank You

**Comment by jadeye** [comment]
Worx here/ Thanx ;-)

**Comment by Jmcassociates** [comment]
A little late the the party.  For Form_Name are you talking about "form_id"?

**Comment by haywirephoenix** [comment]
I can't believe it if this still isn't solved, I regret buying premium. Open a new ticket since he closed this one for no reason. 

form_name stays like that. Scroll up to my code and change only the ones in upper case. 

You can do a find a replace to make sure you get them all.

MY_FORM_NAME
MY_FIELD_ID_1
MY_FIELD_ID_2

**Comment by redheaddigi** [comment]
@haywirephoenix option worked for me.

**Comment by easypeasydigital** [comment]
I looked at the examples above and created a version that works for both email and telephone.
I added the code using the code snippets plugin.
I have left my settings in as it marginally easier to read
form name = 'Registration Form'
email id = 'email'
email confirm id = 'email_confirm'
phone id = 'phone'
phone confirm id = 'phone_confirm'

Don't forget to set these IDs in Elementor

```
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
	
	$form_name = $record->get_form_settings( 'form_name' );

	// EMAIL
	// Replace MY_FORM_NAME with the name you gave your form

	  if ( 'Registration Form' !== $form_name ) {
		return;
	  }

	//Replace MY_FIELD_ID_1 to match the field's Advanced > Field ID

	  $first_email_field = $record->get_field( [
		'id' => 'email'
	  ] );

	//Replace MY_FIELD_ID_2 to match the field's Advanced > Field ID

	  $second_email_field = $record->get_field( [
		'id' => 'email_confirm'
	  ] );

	//Make sure your field ID's are set to match these in each field's Advanced > Field ID
		if ( $first_email_field['email']['value'] !== $second_email_field['email_confirm']['value'] ) {
			$ajax_handler->add_error( $second_email_field['email_confirm']['id'], 'Confirmation Email must match the Email field' );
		}
	
	//PHONE
	//Replace MY_FIELD_ID_1 to match the field's Advanced > Field ID

	  $first_phone_field = $record->get_field( [
		'id' => 'phone'
	  ] );

	//Replace MY_FIELD_ID_2 to match the field's Advanced > Field ID

	  $second_phone_field = $record->get_field( [
		'id' => 'phone_confirm'
	  ] );

	//Make sure your field ID's are set to match these in each field's Advanced > Field ID
		if ( $first_phone_field['phone']['value'] !== $second_phone_field['phone_confirm']['value'] ) {
			$ajax_handler->add_error( $second_phone_field['phone_confirm']['id'], 'Confirmation Phone Number must match the Phone Number field' );
		}

}, 10, 2 );
```
