### ISSUE TITLE
Elementor for gutenberg - design sets

### ISSUE THREAD

**Issue by alriksson** [elementor/elementor#8685]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor for gutenberg does not allow me to create block templates to edit in gutenberg editor. Just to insert static fields. They should be dynamic and be able to edit in the gutenberg editor

**Describe the solution you'd like**
Like how Oxygen v3 is doing it https://youtu.be/AZCeVLpZ8is?t=1080 by creating a block library for gutenberg. Which then is just the template and in gutenberg I can select the block from the normal gutenberg block editor and edit the content in gutenberg. While I edit the design in elementor.

**Additional information:**
It should still be possible to lock section fields from not editing in gutenberg. So that I can lock some fields I e.g Would like to be dynamic with ACF and users should not be able to edit those.

**Comment by DatsTheSparrow** [comment]
+1

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
