### ISSUE TITLE
Bug: 2.6.1 - 2019-07-24 not solve complete the problem (#8672, #8661) query control 

### ISSUE THREAD

**Issue by Visiodot** [elementor/elementor#8687]
when you use extern elementor plugin like elementor extras the query not work and on one of my sites not work the templete (by elementor) widget. i have update all plugins to the last version.

<img width="1175" alt="Schermata 2019-07-25 alle 18 07 27" src="https://user-images.githubusercontent.com/53310373/61891084-2a414d80-af09-11e9-9db7-e01c00750755.png">

<img width="1439" alt="Schermata 2019-07-25 alle 18 09 06" src="https://user-images.githubusercontent.com/53310373/61891085-2a414d80-af09-11e9-9156-188a24e512e0.png">

<img width="978" alt="Schermata 2019-07-25 alle 18 10 44" src="https://user-images.githubusercontent.com/53310373/61891086-2ad9e400-af09-11e9-8595-f286422b55e1.png">

<img width="1564" alt="Schermata 2019-07-25 alle 18 10 54" src="https://user-images.githubusercontent.com/53310373/61891087-2ad9e400-af09-11e9-8f54-cf6222fcb7ab.png">

**Comment by laboiteare** [comment]
Any news about this ? (I'm concerned too and it's pretty urgent)
Otherwise, could you tell me how to downgrade to version 2.6 temporarily ?

**Comment by Visiodot** [comment]
i have do a downgrade in the settings of elementor (STRUMENTI in english it is tools i think) but the problem is not resove for now

**Comment by laboiteare** [comment]
Edit: Elementor Extras made an upgrade today for fixing this issue (2.1.5)

**Comment by Visiodot** [comment]
yes they have resolve the problem whit elementor extra but ACF non work whith the new versione of elementor
<img width="1134" alt="Schermata 2019-07-29 alle 17 15 51" src="https://user-images.githubusercontent.com/53310373/62060178-f5910700-b224-11e9-851e-8469d3964ffe.png">

**Comment by Visiodot** [comment]
a lot of contents are hiden

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.2

Feel free to update

Thanks!

**Comment by Visiodot** [comment]
sorry but the ACF problem is not resolve  in stay not work correctly. 
<img width="1120" alt="Schermata 2019-07-30 alle 16 44 35" src="https://user-images.githubusercontent.com/53310373/62139297-597d0380-b2e9-11e9-98a1-fe5427dfe451.png">

**Comment by Visiodot** [comment]
> This issue has been resolved in Elementor Pro v2.6.2
> 
> Feel free to update
> 
> Thanks!

acf not work correctly whith the new version
<img width="1120" alt="Schermata 2019-07-30 alle 16 44 35" src="https://user-images.githubusercontent.com/53310373/62139401-93e6a080-b2e9-11e9-99d4-8ff738a5ae5b.png">

**Comment by laboiteare** [comment]
> This issue has been resolved in Elementor Pro v2.6.2
> 
> Feel free to update
> 
> Thanks!
Thanks for that. But I can confirm that v.2.6.2 don't resolve bug with ACF field
