### ISSUE TITLE
ElementorProConfig is not defined

### ISSUE THREAD

**Issue by ockang** [elementor/elementor#8690]
Hello community, I have a problem. the elementor when I edit the page, the editing icons are not displayed, and this appears in the console

![Captura de pantalla 2019-07-26 a la(s) 05 54 23](https://user-images.githubusercontent.com/4240285/61922778-46290b80-af6a-11e9-8542-271056246768.png)

**Comment by shilo-ey** [comment]
Hi @ockang 

You have some JS conflict.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

- If you have questions or need general support, Please try:

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
