### ISSUE TITLE
Added padding around text box in elementor

### ISSUE THREAD

**Issue by daarmstrong** [elementor/elementor#8691]
Hi,
New to github so not really sure what to do here.

I am getting unwanted padding around text boxes when i add via the visual editor however when i delete the last character and re-add it via the HTML editor it removes the spacing.

I have tried disabling all plugins and changed themes from Astra to OceanWP & Twenty Nineteen.

I have contacted the support team from Astra & ELementor who are advising that its each others problem so not really getting anywhere

The address to the site is http://52.63.38.210/test

is anyone able to help?

![OceanWP](https://user-images.githubusercontent.com/37885928/61924040-a6cf3d00-af98-11e9-8bed-97d642d15939.png)
![Astra](https://user-images.githubusercontent.com/37885928/61923957-653e9200-af98-11e9-9a82-1ba503640ef7.png)
![Twenty Nineteen](https://user-images.githubusercontent.com/37885928/61923958-653e9200-af98-11e9-9065-594a35c255a5.png)

**Comment by daarmstrong** [comment]
Sorry the first screenshot Is OceanWP, second is Astra and third is Twenty Nineteen

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
