### ISSUE TITLE
Errors in JS Elementor version 2.6.6

### ISSUE THREAD

**Issue by jaespinosa** [elementor/elementor#8692]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have custom post type that produces the error "Uncaught TypeError: Cannot read property 'top' of undefined at belowEntryMetaClass (global.js?ver=1.0:124)". I am using twentyseventeen theme with child theme. This only happens to that custom post type but not on products/pages. I tried to create a new template for the post type but the error is still present even without content (just header and footer), but goes away when there is no template applied.

## Steps to reproduce

Custom Post type:
https://kalesjer.no/stoler/zealand/

Feel free to navigate the website and you can see that the error is just for this custom post type.

## Isolating the problem

- [x] This bug happens with only Elementor 2.6.6 plugin active (and Elementor Pro 2.6.1).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v5.7.25 |  
PHP Version: | 7.2.20 |  
PHP Max Input Vars: | 50000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

Theme |   |  
-- | -- | --
Name: | Twenty Seventeen Child |  
Version: | 1.0 |  
Child Theme: | Yes |  
Parent Theme Name: | Twenty Seventeen |  
Parent Theme Version: | 2.2 |  
Parent Theme Author: | the WordPress team

JS: showing 10 of 10
--
JS: 2019-06-18 04:32:28 [error X 1][https://kalesjer.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:218730] elementorFrontend.elements.window.jQuery is not a function
JS: 2019-07-09 04:50:16 [error X 2][https://kalesjer.no/wp-admin/js/editor.min.js?ver=5.1.1:1:694] Cannot read property \'style\' of undefined
JS: 2019-07-09 04:50:16 [error X 2][https://kalesjer.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:215844] Cannot read property \'on\' of null
JS: 2019-07-11 09:10:58 [error X 45][https://kalesjer.no/wp-content/themes/twentyseventeen/assets/js/global.js?ver=1.0:124:33] Cannot read property \'top\' of undefined
JS: 2019-07-11 09:29:20 [error X 6][https://kalesjer.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.0:2:41610] Cannot read property \'select2\' of undefined
JS: 2019-07-16 09:03:38 [error X 3][https://kalesjer.no/wp-admin/post.php?post=38024&action=elementor:1:1] Unexpected token <
JS: 2019-07-16 09:57:26 [error X 1][https://kalesjer.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.6.0:7:50661] Blocked a frame with origin \"https://kalesjer.no\" from accessing a cross-origin frame.
JS: 2019-07-23 12:16:11 [error X 1][https://kalesjer.no/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3886\") has already been destroyed and cannot be used.
JS: 2019-07-24 09:12:49 [error X 39][https://kalesjer.no/wp-admin/post.php?post=38016&action=elementor:17:1] Unexpected end of input
JS: 2019-07-25 08:54:17 [error X 1][https://kalesjer.no/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4358\") has already been destroyed and cannot be used.

PHP: showing 1 of 1
--
PHP: 2019-07-10 11:37:03 [notice X 35608][/home/kalesjer/public_html/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1248] Undefined index: button_icon [array (   'trace' => ' #0: Elementor\Core\Logger\Manager -> shutdown() ', )]

</details>

**Comment by shilo-ey** [comment]
Hi @jaespinosa 

This issue does not originate in v2.6.6 but in TwentySeventeen.

The theme assumes there are some elements present in your pages even though you are not using its page templates.

Thanks

**Comment by trondhuso** [comment]
Which template is best to use then? Or just change to the latest from WP?
