### ISSUE TITLE
Template Widget (Pro) style

### ISSUE THREAD

**Issue by lucafagherazzi** [elementor/elementor#8694]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I encountered a problem with the Widget Template (Pro) styles.

## Steps to reproduce
- I create some individual Template Section, for example:
   - Template Section A
   - Template Section B
   - Template Section C
     etc.

![01](https://user-images.githubusercontent.com/40598133/61935140-2a356200-af8a-11e9-936a-8ac8cba0fccd.jpg)

![02](https://user-images.githubusercontent.com/40598133/61935159-315c7000-af8a-11e9-88fa-701efd926922.jpg)

- I customize the styles of the individual sections

![03](https://user-images.githubusercontent.com/40598133/61935212-4fc26b80-af8a-11e9-8d1e-a58c30b1c099.jpg)

![04](https://user-images.githubusercontent.com/40598133/61935219-54871f80-af8a-11e9-9841-4c9653fc84ee.jpg)

- I create other Template Section going to use the individual sections just created, for example:
   - Template Section C + Section A
   - Template Section A + Section B
   - Template Section C + Section A + Section B
   - Template Section A + Section C + Section B
     etc.

![05](https://user-images.githubusercontent.com/40598133/61935282-7385b180-af8a-11e9-999d-a73e6b512129.jpg)

- then I create a post and insert, for example, the Template Section C + Section A + Section B via the Template Widget (Pro)

![06](https://user-images.githubusercontent.com/40598133/61935337-944e0700-af8a-11e9-84d3-4d42d32348a4.jpg)

- I update and so far everything is correct

- I leave Elementor

- return and the section has reset the style in the backend; in the frontend it is correct.

![07](https://user-images.githubusercontent.com/40598133/61935418-c65f6900-af8a-11e9-97d0-4094331b4639.jpg)

![08](https://user-images.githubusercontent.com/40598133/61935428-cbbcb380-af8a-11e9-8ae7-8600a2e08e4b.jpg)

Can the problem be solved?

Thank you.

**Comment by Aviad-Herman** [comment]
Hey,
I'm closing this old issue.
If the problem still occurs in the latest versions of Elementor don't hesitate to reopen
