### ISSUE TITLE
Display Condition: Child Category Not Working

### ISSUE THREAD

**Issue by mdrideout** [elementor/elementor#8695]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Applying the template display conditions "Direct Child Category Of" and "Any Child Category Of" does not actually effect the child categories.

## Steps to reproduce
Select those display conditions in elementor. Preview the child categories. Defaults to the theme's default archive display instead of Elementor's.

### Nested Categories Example
![img1](https://i.ibb.co/BKH5d94/Screen-Shot-2019-07-26-at-7-42-24-AM.png)

### Settings Example
_Same with "Any Child Category Of" setting_
![img3](https://i.ibb.co/mNzwpC6/Screen-Shot-2019-07-26-at-7-42-37-AM.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.2.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://rideout.us/ganek
	Home URL: https://rideout.us/ganek
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.8.7
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 1.8.7
		Author: Brainstorm Force

	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Duplicate Post
		Version: 3.2.3
		Author: Enrico Battocchi

	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.1
		Author: Elementor.com

	Really Simple SSL
		Version: 3.2.3
		Author: Rogier Lankhorst, Mark Wolters

	Regenerate Thumbnails
		Version: 3.1.1
		Author: Alex Mills (Viper007Bond)

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	Ultimate Addons for Elementor
		Version: 1.14.0
		Author: Brainstorm Force


== Log ==
	: 
JS: showing 2 of 2JS: 2019-06-04 01:45:03 [error X 1][https://dev.rideout.us/ganek/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2806\") has already been destroyed and cannot be used. 
JS: 2019-06-04 17:04:54 [error X 14][https://dev.rideout.us/ganek/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:8507] Cannot read property \'select2\' of undefined 

Log: showing 12 of 122019-07-15 14:53:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.9',
  'to' => '2.5.14',
)]
2019-07-15 14:53:09 [info] elementor::elementor_updater Started 
2019-07-15 14:53:09 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-15 14:53:09 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-15 14:53:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.2',
)]
2019-07-15 14:53:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.2',
)]
2019-07-26 11:21:51 [info] elementor::elementor_updater Started 
2019-07-26 11:21:51 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-26 11:21:51 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-26 11:21:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.6',
)]
2019-07-26 11:21:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.2',
  'to' => '2.6.6',
)]
2019-07-26 11:22:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.14',
  'to' => '2.6.1',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Thanks for reporting. we will take a look and update this thread soon.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.2

Feel free to update

Thanks!

**Comment by pingram3541** [comment]
Only works if the post type is public.  If you use a LMS or Membership system this DOES NOT work.

**Comment by PabloLombriz** [comment]
For some reason I can't see that option of "Direct Child Category of" in the Available Conditions? Some  ideas?

**Comment by gfdesign** [comment]
> 
> 
> For some reason I can't see that option of "Direct Child Category of" in the Available Conditions? Some ideas?

Do I neither :(

**Comment by gfdesign** [comment]
This is not available in product categories of WooCommerce
Am I the only one facing to this problem? :(

**Comment by sebas-web** [comment]
> This is not available in product categories of WooCommerce Am I the only one facing to this problem? :(

I also have the same problem, I do not see it in the product Archive, were you able to solve it?

**Comment by Strangerous-Artworks** [comment]
In fact, I think you're not facing a bug, but it's a bit confusing for sure : 

- To apply your template with conditions **to posts of a specific category, use Unique instead of Archive**, like this : 
_Include > Unique > in Post Category or in Child of Post Category > Choose your Parent Category_ 
Tada ! Your template is displayed on these posts !

- And use **Include > Archive to apply your template to archives pages** : _Archive Categories or Direct/Any Child of Category_ 
Tada ! Your template is displayed on these archives !

- Do the same with **Exclude** condition if needed

**Comment by scottsdesigns** [comment]
I need "Direct Child Category Of" and "Any Child Category Of" for WooCommerce product categories ... how?

**Comment by MrOizo79** [comment]
2024, 8 years asking for this feature. Elementor is garbage
