### ISSUE TITLE
Elementor Flipbox Image Alignment Issue

### ISSUE THREAD

**Issue by piadey** [elementor/elementor#8696]
I am using Elementor Pro Flip Box. There are three options in Flipbox and the default image position is "**centre**".**"Thats what i understood so far".** 

When i am using the flipbox, the image appears in left as a default on my website.

I have tried to clear cache and i am using latest ver of elementor pro. I have deactivated all other plugins as they might create an issue

**Details of plugins:**
Elementor - 2.6.6 | By Elementor.com 
Elementor Pro - 2.6.1 | By Elementor.com 
WP Fastest Cache - 0.8.9.6 | By Emre Vona
**My screencast:**
![Elementor-Flipbox-issue](https://user-images.githubusercontent.com/53340998/61953772-ec116000-afd4-11e9-9a36-702bc12ca389.PNG)
The image box appears in left as show in the pic. I tried to change the style but only text alignment changes, and the image stays as it is.

Help me to set the image in centre!

**Comment by shilo-ey** [comment]
Hi @piadey 

Thanks for reporting,
We can't reproduce your issue.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it we simply can't help.

In the new thread you're creating please add a link to a page where this issue occurs.


Thanks.
