### ISSUE TITLE
Keeping "Add to Cart" buttons level

### ISSUE THREAD

**Issue by rkl122** [elementor/elementor#8699]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rkl122** [comment]
I will paste in an exchange I've had with your own support.  **With comment added below.**

****************paste************
 I'm using archive products. Each product box shows several fields,
with name followed by sku (added in code) followed by price followed by an add to cart
button. The names of products can take from one to three lines. When
there is variation from one to the next, the add to cart buttons are
not aligned from one product to the next.

 How do I fix this?
***********support response**************

Mansoor replied, on Jul 26 @ 12:11 (UTC):

Hello,

Thanks for reaching out to us,

The alignment of buttons relies on the titles of the products.
Unfortunately, we do not have this feature available at this moment to
align the buttons without bothering titles.

I have tagged this ticket as a feature request. You could even
directly contact our developers and request for such a feature on our
GitHub project [1]. This is where feature requests are handled and
suggestions are taken into consideration.

Sorry for the inconvenience. 

If you need further assistance, We'd be happy to help.

Kind Regards,

**************end paste**************

Well c'mon guys.  Response appreciated, but really it's not good enough.  All we need is some CSS that will assign three line lengths to the product title, regardless of the actual size of that title.  Surely you can provide me that code while you make a permanent fix in Elementor?

Thank you.  -RonL

**Comment by shilo-ey** [comment]
Please provide a link to your page with the issue described.

Thanks!

**Comment by rkl122** [comment]
My site is unpublished, but as reported separately to Brainstorm Force support, I fixed this issue with a plugin ("Woo Align Buttons") and some CSS.  I still think this was an Elementor bug of omission, but if they want to regard this as a "feature request," fine, as long as it gets fixed.

Thanks,  Ron L.

**Comment by shilo-ey** [comment]
Hi Ron, glad you managed to handle your request.
This is not an issue but a feature request.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
