### ISSUE TITLE
My slider stops working when Enable Elementor

### ISSUE THREAD

**Issue by iqbalzain997** [elementor/elementor#8701]
I am going to make my plugin(PTSC) Elementor compatible (Great Page builder BTW). My Plugin has Slider also, which uses the jQuery-ui.min.js library. The slider works properly until Elementor is activated. But when I activate the Elementor I received the JS error
**this._addclass() is not the function**
and slider stop working.
What I have done to solve this issue but not fruitful

1. Update my jQuery-ui.min.js to the latest version
2. Add Jquery(document).ready in the file
3. Double-check this file is not including twice.

I will really appreciate if you guys can help me to solve this issue. Thanks to everyone in advance :)

Regards,
zain

**Comment by bainternet** [comment]
@iqbalzain997 	

We can't really help without reproducing the problem.
Please provide more details and your code if you want us to take a look.

**Comment by iqbalzain997** [comment]
Hi bainternet,
Thanks for consideration. I have resolved the issue. We can close this thread.
thanks
