### ISSUE TITLE
Can't use Popup templates

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8704]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I can't use custom popup templates (ones I define) when creating new popups.

## Steps to reproduce

1. Create a new popup.
2. Save it as a template (Using save options from next to the update/publish button).
3. Create a new Popup.
3. When you see the Elementor Library with the pre-defined popups, switch tab to custom.
4. The popup template you just saved will not be displayed inside that list. 

It may not be an error (PHP or JS), since my console is clear, but as a user I defintely expect to see my custom popup templates under the "My Templates" Tab. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active. (Elementor Hello Theme)
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL:
	WP Multisite: Yes
	Max Upload Size: 15 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello
	Version: 1.0.0
	Author: TD Labs Ltd.
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.0.5
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	Dynamic Animations for Elementor
		Version: 1.0.0
		Author: Dynamic.ooo

	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Extras
		Version: 2.1.4
		Author: Namogo

	Elementor Pro
		Version: 2.5.11
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.11
		Author: rocketgenius

	Mailgun
		Version: 1.7.1
		Author: Mailgun

	Premium Addons for Elementor
		Version: 3.5.8
		Author: Leap13

	Premium Addons PRO
		Version: 1.6.1
		Author: Leap13

	Schema Pro
		Version: 1.3.0
		Author: Brainstorm Force

	SEOPress
		Version: 3.6
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.6.1
		Author: Benjamin Denis

	Ultimate Addons for Elementor
		Version: 1.14.0
		Author: Brainstorm Force

== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 7.2
		Author: ServMask

	All-in-One WP Migration Google Drive Extension
		Version: 2.53
		Author: ServMask

	All-in-One WP Migration Multisite Extension
		Version: 3.75
		Author: ServMask

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Compress JPEG & PNG images
		Version: 3.2.0
		Author: TinyPNG

	Gravity Forms
		Version: 2.4.11
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	User Role Editor Pro
		Version: 4.51.1
		Author: Vladimir Garagulia

	Wordfence Security
		Version: 7.3.5
		Author: Wordfence

	WP-Cron Control
		Version: 0.7.1
		Author: Thorsten Ott, Erick Hitter, Automattic

	WPMU DEV Dashboard
		Version: 4.7.3.1
		Author: WPMU DEV

	WP Ultimo
		Version: 1.10.0
		Author: Arindo Duque - NextPress

== Log ==

PHP: showing 2 of 2PHP: 2019-04-30 14:53:03 [notice X 7][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-28 18:29:55 [warning X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/manager.php::101] unlink(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/sites/41/elementor/css/post-12.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2019-07-12 20:10:54 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view19107\&quot;) has already been destroyed and cannot be used. 
JS: 2019-07-12 20:10:54 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view19839\&quot;) has already been destroyed and cannot be used. 
JS: 2019-07-12 21:15:27 [error X 2][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:53511] Cannot read property \&#039;noUiSlider\&#039; of undefined 
JS: 2019-07-28 19:42:10 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \&quot;view2164\&quot;) has already been destroyed and cannot be used. 
</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @taropaa 
This issue has been reported and is taken care of.

A patch should be released soon.

Try disabling the Elementor Extras plugin to select the popup you wish and re-activate it.

I merged this issue with #8687, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
