### ISSUE TITLE
🔗 🚀 Feature Request: Custom Widget Creator

### ISSUE THREAD

**Issue by careercoder** [elementor/elementor#8705]
I would love to see a drag and drop widget creator that could interact with a dataset, JSON data or DB table.

**Comment by shilo-ey** [comment]
Duplicate of #4440

**Comment by nicholaszein** [comment]
Hello @careercoder,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
