### ISSUE TITLE
'Your site's htaccess file appears to be missing'

### ISSUE THREAD

**Issue by Razerwire** [elementor/elementor#8706]
Hi there,

We're running **Elementor 2.6.6** and **Elementor Pro 2.6.1** on a VPS we don't use a .htaccess file, since the necessary parameters are configured in Apache's config files. 

When trying to edit a page Elementor complains that:
"_The preview could not be loaded
Your site's .htaccess file appears to be missing. File path: /var/www/html/.htaccess_".

Wordpress and Elementor work fine without a .htaccess file and with .htaccess disabled (since we've disabled reading htaccess files in Apache entirely) yet Elementor complains the file is missing. 

**Please allow Elementor to work without a .htaccess file.**

(Using .htaccess should be avoided if possible since it is detrimental to performance).

**Comment by drtobbyas** [comment]
me too having the same issue

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v2.6.7

Feel free to update

Thanks!

**Comment by epileftro85** [comment]
This is happening to me as well 3 years later, any hints on this?
