### ISSUE TITLE
Ability to override help link in v2.6

### ISSUE THREAD

**Issue by blocksera** [elementor/elementor#8707]
Hello Elementor team, the "Need help?" button in v2.6 is very useful for beginners and alike but as developers we need control over it. They link to non-existing pages on elementor for custom widgets, like this one https://go.elementor.com/widget-emage_hover_effects

If we could override this link to our documentation, it would be great!

**Comment by bainternet** [comment]
@blocksera 

You can already do that, Simply add `get_custom_help_url()` method in your widget and return your docs URL.

ex:
```PHP
public function get_custom_help_url() {
	return 'https://URL.TO/MY-DOCS';
}
```

**Comment by shamimbdpro** [comment]
HI. 

I have added the support URL in the widget but it's not working for me. 

https://prnt.sc/16f7i61
