### ISSUE TITLE
Elementor Pro + Woocommerce Theme Builder styles are overwritten by theme

### ISSUE THREAD

**Issue by joiboii** [elementor/elementor#8709]
Hello,

I want to create a shop with those two plugins combined (Elementor Pro+Woocommerce) but my stylesheets are always beeing overwritten somehow (maybe by the theme) and the layout I am building with Elementar Pro are not applied (see screenshots)…

I can only see my custom design (screenshot_1) when I preview the page on element (theme builder for woo commerce) but when I save and visit the URL this just happens (screenshot_2)

Maybe you already solved this problem? I’d be very thankful for any help guys.

![screenshot_2](https://user-images.githubusercontent.com/53429187/62038929-f4e17c00-b1f6-11e9-89f0-943e4f419bf6.png)

![screenshot_1](https://user-images.githubusercontent.com/53429187/62038934-f6ab3f80-b1f6-11e9-94af-9f8278ff4c7e.png)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by matichek** [comment]
Yes, this is still the problem. Woocommerce gives its own styles to custom elementor single product and also doesn't display variable products.
