### ISSUE TITLE
Add option for dependent style like dependent script for widget 

### ISSUE THREAD

**Issue by manektechmayank** [elementor/elementor#8711]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will improve the page speed issue related to the Elementor widget. If we disabled the widget from setting then styles related to that widget should be delete.

**Describe the solution you'd like**
We can give option for the widget to define the dependent style as we are giving for the javascript. Then we can combine and minify that style or javascript.

**Describe alternatives you've considered**
I am using page speed improvement plugin to increase speed like WP fastest cache and Autoptimize.

**Additional context**

**Comment by bainternet** [comment]
@manektechmayank 

This feature is already implemented. There is a `get_style_depends()` method to widget classes just like there is a `get_script_depend()`.

thanks
