### ISSUE TITLE
Column gap only between columns

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#8712]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

In my layout, I have 3 columns. I want a large gap between them. But if I choose "Wider" in the columns gap layout settings, Elementor adds the gap on both sides of each columns (even the left and the right ones). So this looks like there is a margin on the left and the right of the sections columns, making the column not align with the rest of the text.

**Describe the solution you'd like**
Columns gap should be added only between the columns, not on the outside. So the left side of the first column and the right side of the last columns could stay aligned with the rest of the page.

**Describe alternatives you've considered**

I thought of add a padding in the column, I'd need to customize it for tablet and mobile when the layout change.

**Comment by lucafagherazzi** [comment]
+1
similar to #8550

**Comment by bainternet** [comment]
@vgstef 	@lucafagherazzi 

Same answer (https://github.com/elementor/elementor/issues/8550#issuecomment-513154031) still applies.

thanks.
