### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by stevewoody82** [elementor/elementor#8716]
Removed all plugins, rolled back to previous version, reinstalled elementor and elementor pro, tried default theme. Nothing works. Even removing the database and FTP files and using known working ones are still showing the same problem. Cleared cache, used incogneto, used different wifi, used different machine. Given up.

https://www.loom.com/share/fe37735b1e254984b22e12b9e578559d

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
