### ISSUE TITLE
Custom font Weights not working

### ISSUE THREAD

**Issue by taropaa** [elementor/elementor#8717]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Custom font weights are only displaying one weight. Creating multiple font weights 

## Steps to reproduce

1. Create a new Custom font. 
2. Upload various variants of the font (300, 400, 700, bold)
3. Create a new page and use the 700 variant. Only the 400 variant will be used across the website. 

Even in the previews, it seems that only one width is shown despite another file being uploaded. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: 
	Home URL: 
	WP Multisite: Yes
	Max Upload Size: 15 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Child
	Version: 1.0.0
	Author: TD Labs Ltd.
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.0.5
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.5.1
		Author: Frank Goossens (futtta)

	Dynamic Animations for Elementor
		Version: 1.0.0
		Author: Dynamic.ooo

	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Extras
		Version: 2.1.4
		Author: Namogo

	Elementor Pro
		Version: 2.6.1
		Author: Elementor.com

	Gravity Forms
		Version: 2.4.11
		Author: rocketgenius

	Mailgun
		Version: 1.7.1
		Author: Mailgun

	Premium Addons for Elementor
		Version: 3.5.8
		Author: Leap13

	Premium Addons PRO
		Version: 1.6.1
		Author: Leap13

	Schema Pro
		Version: 1.3.0
		Author: Brainstorm Force

	SEOPress
		Version: 3.6
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.6.1
		Author: Benjamin Denis

	Ultimate Addons for Elementor
		Version: 1.14.0
		Author: Brainstorm Force

== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.9
		Author: Janis Elsts

	All-in-One WP Migration
		Version: 7.3
		Author: ServMask

	All-in-One WP Migration Google Drive Extension
		Version: 2.54
		Author: ServMask

	All-in-One WP Migration Multisite Extension
		Version: 3.76
		Author: ServMask

	Cache Enabler
		Version: 1.3.4
		Author: KeyCDN

	Compress JPEG & PNG images
		Version: 3.2.0
		Author: TinyPNG

	Gravity Forms
		Version: 2.4.11
		Author: rocketgenius

	Safe SVG
		Version: 1.9.4
		Author: Daryll Doyle

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	User Role Editor Pro
		Version: 4.51.1
		Author: Vladimir Garagulia

	Wordfence Security
		Version: 7.3.5
		Author: Wordfence

	WP-Cron Control
		Version: 0.7.1
		Author: Thorsten Ott, Erick Hitter, Automattic

	WPMU DEV Dashboard
		Version: 4.7.3.1
		Author: WPMU DEV

	WP Ultimo
		Version: 1.10.1
		Author: Arindo Duque - NextPress

== Log ==
	: 
Log: showing 20 of 342019-04-11 18:47:13 [info] Webtemple Pro/Upgrades - _v_2_5_4_products Start  
2019-04-11 18:47:13 [info] Webtemple Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-11 18:47:13 [info] Webtemple Pro/Upgrades - _v_2_5_4_form Start  
2019-04-11 18:47:13 [info] Webtemple Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-11 18:47:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.2',
  'to' => '2.5.5',
)]
2019-04-21 21:29:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple',
  'from' => '2.5.13',
  'to' => '2.5.14',
)]
2019-04-30 14:52:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.5',
  'to' => '2.5.6',
)]
2019-05-06 20:59:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.6',
  'to' => '2.5.8',
)]
2019-05-08 18:44:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple',
  'from' => '2.5.14',
  'to' => '2.5.15',
)]
2019-05-30 22:04:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple',
  'from' => '2.5.15',
  'to' => '2.5.16',
)]
2019-05-30 22:04:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]
2019-07-10 08:05:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.9',
  'to' => '2.5.11',
)]
2019-07-28 18:29:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Webtemple',
  'from' => '2.5.16',
  'to' => '2.6.6',
)]
2019-07-28 18:29:55 [info] elementor::elementor_updater Started 
2019-07-28 18:29:55 [info] Page Builder/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-07-28 18:29:55 [info] Page Builder/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-07-28 18:29:55 [info] Page Builder/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-07-28 18:29:55 [info] Page Builder/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-07-28 18:29:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.5.16',
  'to' => '2.6.6',
)]
2019-07-29 18:55:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Webtemple Pro',
  'from' => '2.5.11',
  'to' => '2.6.1',
)]

PHP: showing 4 of 4PHP: 2019-04-30 14:53:03 [notice X 9][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-28 18:29:55 [warning X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/manager.php::101] unlink(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/sites/41/elementor/css/post-12.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-29 18:55:20 [warning X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/manager.php::101] unlink(/opt/bitnami/apps/wordpress/htdocs/wp-content/uploads/sites/41/elementor/css/post-33.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-07-29 20:49:01 [notice X 6][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2019-07-12 20:10:54 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view19107\") has already been destroyed and cannot be used. 
JS: 2019-07-12 20:10:54 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view19839\") has already been destroyed and cannot be used. 
JS: 2019-07-12 21:15:27 [error X 2][/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.16:2:53511] Cannot read property \'noUiSlider\' of undefined 
JS: 2019-07-28 19:42:10 [error X 1][/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2164\") has already been destroyed and cannot be used. 
</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment]
Hi @taropaa 

Thanks for reporting.

We couldn't reproduce your issue,

![image](https://user-images.githubusercontent.com/45009641/62108072-ba88e500-b2b1-11e9-8324-5839cd698c3c.png)

Can you please try to:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen / Hello theme (or other default WordPress theme).

And see if the issue still persists.


Thanks!

**Comment by shilo-ey** [comment]
@taropaa 

Any updates?

**Comment by taropaa** [comment]
Hi @shilo-ey after a few hours of trial and error, I was able to re-upload the fonts and it worked. My guess is that a combination of caching was the cause here. 
I will keep ana eye on this and once I pinpoint the exact culprit, I will post back on this thread to hopefully help others that may face a similar issue. 

Thank you for looking into this.

**Comment by omacac24** [comment]
did u manage to find the problem? I am also not being able to change the font weight of a custom font despite having added multiple weights when adding it to elementor.

**Comment by jbalbinpe** [comment]
Any update?, i have similar problem. In my Builder Elementor show my custom font-weight peftect, but in FrontEnd is different font-weight.
