### ISSUE TITLE
Dynamic content for Share Buttons URL 

### ISSUE THREAD

**Issue by maoxiong** [elementor/elementor#8722]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It would be great if the target URL for the "Share Buttons" widget could support dynamic content.

This way it can pull data from ACF fields.

In my case I am using a custom post type to store research papers, so I'd like the link to go to the PDF of the paper itself (stored in the ACF field) rather than the post url.

**Comment by bainternet** [comment]
@maoxiong 	

Share Button widget uses fixed URL which is triggered via JavaScript for **sharing** to social networks.

What you are looking for is [Social Icons Widget](https://docs.elementor.com/article/87-social-icons) which already has these dynamic capabilities you are asking for.

Thanks.

**Comment by maoxiong** [comment]
Hi! 

Yes I know that! 😊

I want to share the ACF field url to social networks, not the post url itself.
