### ISSUE TITLE
The way browser tabs are shown with ELEMENTOR

### ISSUE THREAD

**Issue by Hoffkids** [elementor/elementor#8723]
Hi,
When I am working in Elementor Pro and I have tabs open in any browser, the tabs look like this... 

Elementor | About

When I have multiple tabs open, they get smaller and now ALL look like this
ELEMENTOR  ELEMENTOR  ELEMENTOR  ELEMENTOR

making it VERY hard to find the page to work on. This is faster than going to the WP dashboard and opening each page each time. Just keep open in browser, but hard to find!

Is there any way in the world you guys could change the way tabs view to put the PAGE name first when in edit mode?

so like  
About | Elementor

This would be HUGE to speed up work flow!

Thanks

Barry

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
