### ISSUE TITLE
[Feature request] GetResponse Integration - updating existing contacts

### ISSUE THREAD

**Issue by yositsitsu** [elementor/elementor#8725]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Enable updating existing contacts - in marketing, often you gradually collect additional fields about a lead or a customer. It can start with a simple form that collects just the email.
Later it can be phone number, age, address etc.
Being unable to update a contact's fields / custom fields is a pain in the butt.
P.S>
sometimes people have typos too, and submitting the correct or preferred phone a minute later will not save the correct or preferred data.

**Describe the solution you'd like**
An optional checkbox on the form for Getresponse action:
[V] Update contact if already exists

**Describe alternatives you've considered**
An alternative would be to use new lists all the time - sometimes it makes sense, sometimes not. And over time it causes a single contact to have 5-10 copies with different metadata on it, which is not good. Avoiding unnecessary duplication in the first place, would be the best solution.

**Additional context**
[GetResponse & Elementor Integration doc](https://docs.elementor.com/article/260-getresponse) clearly states:
"Note: The integration with GetResponse creates a new contact in your GetResponse account It does not update existing contacts."

Would be great to have that note disappear in the near future :)

**Comment by DorShahar** [comment]
Hi
Your request is part of our Form Submission project.
Therefore, I merged this issue with  #1686, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
