### ISSUE TITLE
Add background option for menu items instead of only the complete nav menu

### ISSUE THREAD

**Issue by kneops** [elementor/elementor#8726]
Right now you can only add a background to the complete nav menu, but it would be great if we can add a background to the menu items themselves, like a small icon or (png) images popping up next to the menu item when hovering it and on active state.

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
