### ISSUE TITLE
Add Icon Library to Popup Close Button section

### ISSUE THREAD

**Issue by dzined** [elementor/elementor#8728]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This will allow users to specify which icon they would like to use as the close button on the popup

**Describe the solution you'd like**
I would like to see the new icon library integrated with the popup builder close button section in order to let us upload an svg or choose an icon for the close icon in the popup. Currently the selected icon is quite chunky, and for many modern sites this doesn't work well with cleaner designs.

**Describe alternatives you've considered**
An alternative i to try and do with css in the custom css, but this would be an advanced required for the majority of end users

**Additional context**
<img width="344" alt="Screenshot 2019-07-31 at 08 11 14" src="https://user-images.githubusercontent.com/3873308/62191150-d69c8d00-b36a-11e9-98d7-98db44448e4e.png">

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by jotcreative** [comment]
+1

**Comment by Waleedviews** [comment]
+1
