### ISSUE TITLE
Advanced Custom Fields broken after Update 2.6.x

### ISSUE THREAD

**Issue by eladore** [elementor/elementor#8729]
I still can't use ACF any more. They are previewed correctly on the single instance of a Post inside Elementor but not any more in live view or Posts Extra View... I also have problems with ACF Text fields... they are always empty after the update... it happens with all ACFs used in the dynamic function inside of elementor... 

My setup:
Template with Single 3D Flip Box with ACF Image field for Icon
Use Template with Posts Extra

Icon visible in single 3D Box preview. Icons not visible at Postsextra Preview nor in the live site. See screenshots...

I tested it as well without the 3D Flip Box. Same problem. Rollback to previous Elementor Pro Version and the problem is gone but there are other problems with Font Awesome... 

Best,

Chris
![2019-07-31 10_40_12-Window](https://user-images.githubusercontent.com/53255259/62197616-73b5f080-b380-11e9-88fe-416d6aaf41cc.png)
![2019-07-31 10_38_58-Window](https://user-images.githubusercontent.com/53255259/62197615-73b5f080-b380-11e9-869b-d2de9fc10d18.png)
![2019-07-31 10_40_41-Window](https://user-images.githubusercontent.com/53255259/62197618-73b5f080-b380-11e9-9c03-e8e032be66f8.png)
![2019-07-31 10_55_46-Window](https://user-images.githubusercontent.com/53255259/62198401-d65bbc00-b381-11e9-93e9-dd02c964151f.png)
![2019_07_31_10_53_27_Window](https://user-images.githubusercontent.com/53255259/62198508-099e4b00-b382-11e9-996d-5285630614b0.png)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Prerequisites.**
* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**
* **One issue per thread**

Without it we simply can't help.

Thanks.
