### ISSUE TITLE
Advanced Custom Fields in nested Templates broken after Update 2.6.x

### ISSUE THREAD

**Issue by eladore** [elementor/elementor#8730]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Advanced Custom Fileds don't work any more. They are previewed correctly on the single elementor preview instance but not in live view. It happens with all ACFs used in the dynamic function inside of elementor. If is there since elementor pro 2.6.

## Steps to reproduce
- Create a Custom Field
- Create a Custom Post
- Attach the custom Field to custom Post
- Create some Posts with filled ACF

- Create a Elementor Single Template which uses the ACF
- Use Posts Extra or anything else to show a post grid with a template
- Select the Template in the Post Grid
- Bug: The ACF will be empty. In the preview as well as in the live site

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | (Debian) v5.6.42-84.2 |  
PHP Version: | 7.2.20 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

WordPress Environment |   |  
-- | -- | --
Version: | 5.2.2 |  
Site URL: | http://staging.lplusp.com |  
Home URL: | http://staging.lplusp.com |  
WP Multisite: | No |  
Max Upload Size: | 2 MB |  
Memory limit: | 2000M |  
Permalink Structure: | /%postname%/ |  
Language: | en-GB |  
Timezone: | Europe/Berlin |  
Admin Email: | ninos.ego@faber-network.de |  
Debug Mode: | Inactive

Theme |   |  
-- | -- | --
Name: | Hello Elementor |  
Version: | 2.2.0 |  
Author: | Elementor Team |  
Child Theme: | No | If you want to modify the source code of your theme, we recommend using a child theme.

User |   |  
-- | -- | --
Role: | administrator |  
WP Profile lang: | en_GB |  
User Agent: | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

Active Plugins |   |  
-- | -- | --
Advanced Custom Fields - 5.8.2 | By Elliot Condon |  
AnyWhere Elementor Pro - 2.12.1 | By WebTechStreet |  
Custom Adobe Fonts (Typekit) - 1.0.11 | By Brainstorm Force |  
Custom Post Type UI - 1.6.2 | By WebDevStudios |  
Duplicate Page - 3.8 | By mndpsingh287 |  
DynamicConditions - 1.3.2 | By RTO GmbH |  
Easy Populate Posts - 3.4 | By Iulia Cazan |  
Elementor - 2.6.7 | By Elementor.com |  
Elementor Blocks for Gutenberg - 1.0.1 | By Elementor.com |  
Elementor Extras - 2.1.5 | By Namogo |  
Elementor Pro - 2.6.2 | By Elementor.com |  
Element Pack - 3.2.2 | By BdThemes |  
Imagify - 1.9.6 | By WP Media |  
JetBlog For Elementor - 2.1.19 | By Zemez |  
JetElements For Elementor - 1.15.16 | By Zemez |  
JetTabs For Elementor - 2.0.2 | By Zemez |  
JetTricks - 1.2.0 | By Zemez |  
Page Templater For Elementor - 1.2.9 | By ThemeIsle |  
Premium Addons for Elementor - 3.6.1 | By Leap13 |  
Premium Addons PRO - 1.6.2 | By Leap13 |  
Smart Slider 3 Pro - 3.3.21 | By Nextend |  
TeamPress - 1.4 | By Ex-Themes |  
UpdraftPlus - Backup/Restore - 1.16.16 | By UpdraftPlus.Com, DavidAnderson |  
WordPress Importer - 0.6.4 | By wordpressdotorg |  
WP Config File Editor - 1.6.7 | By AHMeD SAiD |  
WP Hash Password - 1.0.7 | By Ninos Ego

Best,

Chris
![2019-07-31 10_40_12-Window](https://user-images.githubusercontent.com/53255259/62204787-39ebe680-b38e-11e9-985e-034664c5fdec.png)
![2019-07-31 10_40_41-Window](https://user-images.githubusercontent.com/53255259/62204789-3c4e4080-b38e-11e9-95c3-fe967bc7270f.png)
![2019-07-31 10_55_46-Window](https://user-images.githubusercontent.com/53255259/62204803-440de500-b38e-11e9-9aa0-8f4277c3bf1a.png)
![2019_07_31_10_53_27_Window](https://user-images.githubusercontent.com/53255259/62204809-453f1200-b38e-11e9-9c21-ba48ffe2c49a.png)

**Comment by shilo-ey** [comment]
Hi @eladore 

In your report are you referring to 3rd party widgets/capabilities?

If so, please specify which (scenario A is explained properly, but B is unclear...) 

Waiting for your reply.

Thanks!

**Comment by eladore** [comment]
@shilo-ey 

Variation B doesn't use any 3rd party widgets, Thats why I made it....
It is just a basis elementor template set to be used on a post types. Use the ACF on the dynamic attribute function on any widget (non 3rd person and 3rd person) like title, text... and it goes empty.

It is very easy to reproduce. Just try to use a ACF in any dynamic variable filed in elementor and look at the live page of it.  It is always empty... 
Rollback to 2.5 and it works as intended...

Best,

Chris

**Comment by eladore** [comment]
Ahh you are maybe right. I just tested variation B and it worked out. So it seems that it just happens when it is inside of nested widgets via templates.... I will test that with an even easier scenario....

**Comment by eladore** [comment]
@shilo-ey 
Yes the database update fixed the varaiation b. sorry for that... 
With Posts Extra I can't get it running in any configuration when I use a template... I will try more 3rd party tools with template function...

**Comment by shilo-ey** [comment]
Great, glad you managed to make it work again.

I would contact your plugin authors and let them know about this issue.

Thanks!

**Comment by eladore** [comment]
I also wrote to the posts extra support. We will see if he says that it is his problem and not a elementor one
