### ISSUE TITLE
Notice while editing with elementor

### ISSUE THREAD

**Issue by sagarpatel124** [elementor/elementor#8732]
Hello Elementor Team, 

We are getting below notice, When we click on any page "Edit with elementor". 

NOTICE: C:\wamp\www\plus-elementor\wp-content\plugins\elementor\core\documents-manager.php:411 - Undefined offset: 0
require_once('wp-admin/admin-header.php'), require('wp-admin/menu-header.php'), _wp_menu_output, current_user_can, call_user_func_array, WP_User->has_cap, apply_filters('user_has_cap'), WP_Hook->apply_filters, call_user_func_array, Elementor\Core\Documents_Manager->remove_user_edit_cap

Notice : Elementor\Core\Documents_Manager->remove_user_edit_cap

This issue raised after we hae updated to latest elementor version 2.6.7

**Comment by shilo-ey** [comment]
Hi @sagarpatel124 

Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment]
@sagarpatel124 

Can you please send us administrator credentials to your website in order we could make sure our fix resolves this issue?

Please send them to our support at support @elementor.com and mention that you were directed by me and reference this issue.

thanks.

**Comment by sagarpatel124** [comment]
Hello Shilo-ey,

We have updated code as per your instruction https://github.com/elementor/elementor/commit/e94286993adf4eac74db3031d3fba4ac3853665b and It's working now. 

So you still need administrator access? We would love to help you to make elementor better.

**Comment by shilo-ey** [comment]
Thanks! this will be released soon.

No need for additional credentials.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elemento v2.6.8

Feel free to update

Thanks!

**Comment by sagarpatel124** [comment]
Thanks for informing me. We will update it.
