### ISSUE TITLE
Widget Control conditions and multi control css values

### ISSUE THREAD

**Issue by ianlee** [elementor/elementor#8737]
Hi, 
Currently trying to build a custom widget with css transformations - multiple values need to put into a single css statement.

As I haven't found a way to include multiple controls into  a 'selectors' css, I am currently using a Dimensions control to be able to pass multiple values into a css selector.  This is working so far though I'd like to know if there is a better way to do this (pulling multiple values from other controls into a css statement).

```
'selectors'=> [
	'{{WRAPPER}} .col-image' => 'transform: translate(0px, {{TOP}}{{UNIT}})  scale({{RIGHT}})',
	'{{WRAPPER}} .split-col-container' => array(
		'padding-top'=> 'calc(0px - {{RIGHT}} * calc({{TOP}}{{UNIT}}))',
		'padding-bottom'=> 'calc({{RIGHT}} * {{TOP}}{{UNIT}})',
	),
],
```

I have another control which I want to have a condition based on one of these values.  How can I do this?

```
'conditions' => [
    'terms' => [
        [
            'name' => 'img_offset', // I'd like to check  img_offset RIGHT value
            'operator' => '!=',
            'value' => 0
        ],
    ],
],
```

Thanks.

**Comment by TheFirsh** [comment]
Maybe I can be of help.

### Selectors
Your workaround is nice but you can easily access values from other controls. Try:

```
{{other_control.VALUE}}
{{other_numeric_control.SIZE}}
{{other_numeric_control.UNIT}}
{{other_dimension_control.TOP}}
{{other_dimension_control.RIGHT}}
```
Learn more at [Use Selectors in Elementor](https://letswp.io/selectors-elementor-control-css-values/)

### Conditions
Similar goes for conditions, but you need to specify what you need from the other control if it's not the outright `value` (multi-controls such as Dimensions don't have a single value).
```
'conditions' => [
    'terms' => [
        [
            'name' => 'img_offset[right]',
            'operator' => '!=',
            'value' => 0
        ],
    ],
],
```
Learn more at [Control Conditions in Elementor](https://letswp.io/conditional-controls-in-elementor-extensions/)

**Comment by ianlee** [comment]
This looks perfect.  Thanks for the articles.
