### ISSUE TITLE
Is there a full screen popup overlay control? (Like WP media popup)

### ISSUE THREAD

**Issue by kmob2** [elementor/elementor#8738]
Hello,

I was wondering, is there already a control field that opens a full screen overlay for options, Basically like the current popup field used in typography, but have it almost full screen, like the media popup overlay when selecting an image.

If there's no such built in control field, does anyone know have a good idea on an easy way to build it myself? Maybe copying the code from the small built in popup control field, and modify it to go almost full screen?

Any hint would be appreciated.

Thank you.

**Comment by bainternet** [comment]
@kmob2 

Currently, there is no such thing. However, there is a modal dialog (which we use for Icon library, Display conditions, and popup triggers) you can use if you know a little BackboneJs.

thanks.
